### ISSUE TITLE
Activate extra destination fields

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#10006]
### Description

Hi there.
Many iD mappers don't know that destination:symbol and destination:colour exists, so why doesn't iD help with that?
My suggestion is to activate those fields whenever the destination field is filled with one or more values.
I think this would be a great addition to add more useful info to highway links, and also would help mappers to investigate further other more complex info, like lanes, :forward and :backward keys.

Regards.

**Comment by nickrsan** [comment]
I like this idea, though I think this one belongs on https://github.com/openstreetmap/id-tagging-schema/issues instead of here. I can't transfer issues, but if you open one over there and link it here, I can close this one if you'd like.

**Comment by AntMadeira** [comment]
Thanks, @nickrsan. I've posted it [here](https://github.com/openstreetmap/id-tagging-schema/issues/1065) as you suggested.

**Comment by k-yle** [comment]
I'm gonna close this one as a Duplicate of https://github.com/openstreetmap/id-tagging-schema/issues/1065

**Comment by k-yle** [comment]
Duplicate of openstreetmap/id-tagging-schema#1065
