### ISSUE TITLE
Background>Overlays>OpenStreetMap GPS traces: Option to hide traces older than X

### ISSUE THREAD

**Issue by nicolas-raoul** [openstreetmap/iD#10020]
### Description

# Context
Two new huge redeveloped areas just opened in Tokyo.
New GPS traces are appearing along the new streets/pathways, but most of the GPS traces are for now-destroyed streets.
This makes mapping redeveloped areas very hard.

# Suggested solution
How about having a filter to show only traces that were added since s specific date? (I would set it to the date whe the redeveloped area opened)

This feature would also be useful for some countries' forests, where unofficial paths come and go.
Thanks!

**Comment by pnorman** [comment]
iD cannot load GPS traces from the API, it relies on pre-rendered tiles which have all traces baked into them.

**Comment by tordans** [comment]
I am closing this for the reason explained in [the previous comment](https://github.com/openstreetmap/iD/issues/10020#issuecomment-1842573689). 
More background: The whole GPS Traces Part of osm website has not been touched for a long time. I know there are comments about it somewhere in https://github.com/openstreetmap/openstreetmap-website/issues but I could not find them ATM.
