### ISSUE TITLE
Unwanted disconnexion

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#10057]
### URL

https://www.openstreetmap.org/edit#map=18/-3.12018/11.29427

### How to reproduce the issue?

1. Select the way 1227899918, remove the relation 16887284 (grassland)
2. Do the same with the way 1234595972 (remove the same relation), the way 1228017725 (remove relation 16775099) and the way 1236063955 (remove relation 16775099)
3. Merge the 4 ways 1227899918, 1234595972, 1228017725 and 1236063955 : the result way will have 1995 nodes
4. Add 6 nodes : the result way will have 2001 nodes
5. Try to save : you will have a message "too much nodes"
![2024-01-01_131849](https://github.com/openstreetmap/iD/assets/3121119/f1c5aa76-d434-43da-8ead-9bcd1375d0fb)
6. Cut the way in 2 parts
7. Try to save : a new Firefox window opens with an error message
![2024-01-01_132228](https://github.com/openstreetmap/iD/assets/3121119/47103b3c-5f77-42f7-9954-b36857b08cc2)
8. Close this window and look at the main window : all is frozen, you can do nothing except to close the tab or Firefox (and lost your last changes)

![2024-01-01_132500](https://github.com/openstreetmap/iD/assets/3121119/ba032977-acb6-488f-a87c-6e7bb3180775)

I tried this on Firefox (v121), I don't know if this issue is on Chrome, Edge or another browser

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.3

### Which browsers are you seeing this problem on?

Firefox

**Comment by k-yle** [comment]
This was fixed in #8808, but that PR hasn't been merged yet...

**Comment by Mahabarata** [comment]
Ok, great. 
And sorry for the duplicate : I close my issue.
