### ISSUE TITLE
Concept: "shift" the polygons

### ISSUE THREAD

**Issue by Vectorial1024** [openstreetmap/iD#10053]
### Description

Sometimes, the outlines of a building (as a single area) are very nicely drawn on the map, but its position is unfortunately off by just a bit when cross-checking with satellite images. It would be nice to therefore have a feature where I can "shift" the building area without losing the exact shape of the area.

**Comment by k-yle** [comment]
You can do this by selecting an area, then pressing <kbd>M</kbd>, then using the mouse to drag the area.

Alternatively, you can select an area and press <kbd>Shift</kbd> + <kbd>⬇️</kbd> (or any other arrow key)

**Comment by Vectorial1024** [comment]
Thanks for the answer!

I basically forgot about this question after those initial few days. I'm closing this since it is answered.
