### ISSUE TITLE
Add supporting.openstreetmap.org call to action to edit confirmation screen

### ISSUE THREAD

**Issue by grischard** [openstreetmap/iD#10054]
### Description

OpenStreetMap relies on donations to run.

The edit confirmation screen is a moment when I'm in a good mood after mapping. It would be a good place for a call to donate.

The icon I used for my mock up is from https://uxwing.com/charity-donation-hand-love-icon/ but a mock up is all it is - a different icon and text is fine.

### Screenshots

<img width="448" alt="Screenshot 2023-12-30 at 18 36 58" src="https://github.com/openstreetmap/iD/assets/1556567/9310fa17-d023-4b9c-ab0e-ef78a5e145a7">

**Comment by 1ec5** [comment]
The “free to use but not to run” messaging might be a bit off in this context, since the user may feel that they’ve just given to OSM through their edits, rather than taking from OSM. The user can’t be counted on to understand that iD just connected to a server API managed by the OWG and affiliated with the OSMF.

Another consideration is that the iD software is designed to be modular enough to reuse in a non-OSM-hosted envirornment. The “Connect with others” links are powered by the [OSM Community Index](https://github.com/osmlab/osm-community-index/). Could a fundraising message live there instead of being baked into iD? That would also make it easier to fine-tune the message and the financial report link periodically.

**Comment by grischard** [comment]
> The “free to use but not to run” messaging might be a bit off in this context, since the user may feel that they’ve just given to OSM through their edits, rather than taking from OSM. The user can’t be counted on to understand that iD just connected to a server API managed by the OWG and affiliated with the OSMF.

Most of the donations on supporting.openstreetmap.org come from mappers like you and I. People edit OpenStreetMap because they find it useful, and therefore editors want to help keep it running.

> Another consideration is that the iD software is designed to be modular enough to reuse in a non-OSM-hosted envirornment. The “Connect with others” links are powered by the [OSM Community Index](https://github.com/osmlab/osm-community-index/). Could a fundraising message live there instead of being baked into iD? That would also make it easier to fine-tune the message and the financial report link periodically.

Ah, the OHM variable :). I'm not against building the call to action is a modular way if it doesn't significantly increase development time. Putting a donation message directly under "Connect with others" won't work, but defining a special type in the community index and showing it differently like this could work.

**Comment by 1ec5** [comment]
> Most of the donations on supporting.openstreetmap.org come from mappers like you and I. People edit OpenStreetMap because they find it useful, and therefore editors want to help keep it running.

Of course. I think it’s still worth being sensitive about the context in which we solicit a donation though. This isn’t a criticism of the overall idea, but rather a suggestion to fine-tune the messaging for the audience. For example: want your OSM contributions to have a wider impact? I’m sure others could come up with something even better.

> Ah, the OHM variable :). I'm not against building the call to action is a modular way if it doesn't significantly increase development time. Putting a donation message directly under "Connect with others" won't work, but defining a special type in the community index and showing it differently like this could work.

Heh, OHM is already hacking this screen to bits as of OpenHistoricalMap/iD#183, but there are other forks such as the one for Public Domain Map, as well as OSM-focused deployments of iD that are hosted elsewhere. The last thing OSMF should have to worry about is tracking down each of these deployments and getting them to upgrade to a newer release of iD that links to the correct annual report.

The community index already lists non-contact resources like tagging guidelines on the wiki, so I think it would make a lot of sense for iD to split the section by resource type or introduce the section more generically.

**Comment by grischard** [comment]
@tyrasd flagging this for your attention please.

**Comment by tyrasd** [comment]
The message is now implemented with the suggested text[^1] and icon. 

For non-OSM deployments this can be easily disabled by setting the following environment variable: `ID_SHOW_DONATION_MESSAGE=false`.


[^1]: excluding the link to the financial report for now: I think that information would be better suited to be included in the [supporting osm](https://supporting.openstreetmap.org/) page, wouldn't it?
