### ISSUE TITLE
Wikipedia link with question mark

### ISSUE THREAD

**Issue by alnzrv** [openstreetmap/iD#10065]
### URL

https://www.openstreetmap.org/edit?way=394705975#map=19/44.81767/20.45303

### How to reproduce the issue?

1. Clear the wikipedia tag.
2. Select language "српски / srpski".
3. Start typing "Кафана „?”". Select such value from the drop-down.
4. Click on the button "view on wikipedia.org".
5. You will get the error page in the browser.

### Screenshot(s) or anything else?

Tag "wikipedia=sr:Кафана_„%3F”" works, tag "wikipedia=sr:Кафана „?”" doesn't.
If you save tag "wikipedia=sr:Кафана „?”" problem will stay in the view (not the edit) mode too.

![1](https://github.com/openstreetmap/iD/assets/7187657/c253edd9-fbc9-4074-b2b9-5aaffb36a9d1)
![2](https://github.com/openstreetmap/iD/assets/7187657/ece3bc43-a79b-451d-8a43-56727d0efb04)
![image](https://github.com/openstreetmap/iD/assets/7187657/01ff2a9a-3222-43b9-9ca9-7747537531ca)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.3

### Which browsers are you seeing this problem on?

Chrome

**Comment by Asif-Sheriff** [comment]
In URL encoding, "?" is represented as "%3F" 
That is why Кафана_„%3F” works while the former doesn't.
