### ISSUE TITLE
Correct streetside (typo) to street_side (automatically)

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10097]
### Description

if manually adding 'streetside', it should be corrected (validated) to `street_side`

### Screenshots

![image](https://github.com/openstreetmap/iD/assets/67521919/97bf93fa-6568-45cd-8af2-05f572fec7d1)

**Comment by snehalchaudhari98** [comment]
Hi! I want to try to fix the issue. It's the first time I'm contributing to an open-source project, so I think I would be able to fix it and contribute something. Could you please assign this issue to me?

**Comment by danieldegroot2** [comment]
@snehalchaudhari98 I would suggest reading [CONTRIBUTING.md](https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md) and checking out also [list of examples of other projects](https://wiki.openstreetmap.org/wiki/Develop) and [Google Summer of Code ideas](https://wiki.openstreetmap.org/wiki/Category:Google_Summer_of_Code_ideas) ([announcement for 2024](https://community.openstreetmap.org/t/google-summer-of-code-2024-call-for-project-ideas-and-mentors/108515)). Usually there is issues labeled [good first issue](https://github.com/openstreetmap/iD/labels/good%20first%20issue) (for iD there is currently only 'don't display deprecated tags' issue without existing PR). You can consider this issue as good first issue instead, though.

You can deprecate `streetside` in [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema) at [data/deprecated.json](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/deprecated.json).

You don't have to be assigned to an issue to be able to work on it.

**Comment by snehalchaudhari98** [comment]
Hi @danieldegroot2, thanks for sharing the above resources.  I would work on your suggestion and look out for good first issues.

**Comment by danieldegroot2** [comment]
Closing in favour of https://github.com/openstreetmap/id-tagging-schema/issues/1111.
