### ISSUE TITLE
Keep getting redirect error

### ISSUE THREAD

**Issue by CatRBLX** [openstreetmap/iD#10106]
### Screenshot(s) or anything else?

For the past few days, i've been getting this error that is really annoying. Everytime I press save, it opens up a pop-up with the text:
"The requested redirect uri is malformed or doesn't match client redirect URI." Please help, many thanks are appreciated.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Opera

**Comment by 1ec5** [comment]
This error comes from the OSM website application when iD attempts to authenticate using OAuth: openstreetmap/openstreetmap-website#4363. I’m not sure why you’re suddenly running into this though. If iD doesn’t have the permissions it needs yet, it might have opened a popup window in which osm.org prompts you to give iD permission. You might need to disable your browser’s popup blocker to see it.

As a temporary workaround, you can click the “Download osmChange file” link at the bottom of the save screen. This will download an .osc file that you can upload using either JOSM or [Level0](https://level0.osmz.ru/).

**Comment by CatRBLX** [comment]
Hello. While your answer is probably really helpful and could work for some people, the pop-up appears when I hit Save. It doesn't allow me to do the Download osmChange file since it just goes gray.

Although I will try to disable my pop-up blocker for openstreetmap.org, I have my doubts it will work.

**Comment by tordans** [comment]
@CatRBLX we did not hear form anyone else about this so I a assume this is a local issue that resolved itself. I will close this issue but feel free to reopen it should the error still show up.

**Comment by AtmosphericIgnition** [comment]
Hi, I'm having this exact issue with my local build. I presume this has something to do with OAuth not liking the site running outside openstreetmap.org. Any help would be greatly appreciated. Thanks.
