### ISSUE TITLE
Missing en translation: community.uk-london-mastodon.name

### ISSUE THREAD

**Issue by hb0nd** [openstreetmap/iD#10109]
### How to reproduce the issue?

Make an edit on osm.org in London
see the recommended community suggestions

(locale is en-GB)

only reproducible on osm.org, not on dev or rapid

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/26939824/f68b67ec-b2ad-4637-bc47-0baa87c1ed91)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.8

### Which browsers are you seeing this problem on?

Firefox

**Comment by linfindel** [comment]
It's also missing translation for `tagging.presets.fields.address.placeholders.street+place` on Chrome & Firefox.

Full error in the console:
`Missing en-GB translation: _tagging.presets.fields.address.placeholders.street+place
r.tInfo @ id-16bcaddcb38f23c3e3ce0c22e4c2b6207b68ed9b9995945c545034e4e8ecf3d6.js:5
`

**Comment by tordans** [comment]
@RedAuburn can you re-check if this is still an issue? I am pretty sure that the translations are managed in https://github.com/osmlab/osm-community-index?tab=readme-ov-file (see https://github.com/osmlab/osm-community-index/wiki/Translations) and only pulled to iD. There might be race conditions when a new index is pulled but not the latest translations.

Please close here, in case this resolved itself. Thank you.

**Comment by hb0nd** [comment]
can confirm it's fixed 👍️

![Screenshot from 2024-05-03 13-23-39](https://github.com/openstreetmap/iD/assets/26939824/f4eb6fa8-9b36-48aa-9ed8-b95955a21fbb)
