### ISSUE TITLE
Map data (not imagery) loads very slowly in Firefox (Arch Linux)

### ISSUE THREAD

**Issue by yaomtc** [openstreetmap/iD#10105]
### How to reproduce the issue?

Using Firefox 122 on [Plasma 6.0](https://community.kde.org/Plasma/Plasma_6) RC2 (Wayland) on Arch Linux. In Firefox, the map data is extremely slow to load, while the imagery loads fine. Chromium does not experience this issue.

This occurs both on a new Firefox profile and on a new account on the system.

### Screenshot(s) or anything else?

https://profiler.firefox.com/public/r65167qf1h8sr0nyvj78p3p2y0bqj07pqkdmz58/calltree/?globalTrackOrder=0w2&implementation=js&thread=2&v=10

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by matheusgomesms** [comment]
Same here

**Comment by yaomtc** [comment]
What OS, @matheusgomesms?

**Comment by matheusgomesms** [comment]
MacOS, Safari

**Comment by yaomtc** [comment]
I see, I wonder if iD has just not been tested in non-Chromium browsers in a while?

**Comment by linfindel** [comment]
I'm getting this in Google Chrome in Fedora 39, as well as in Firefox.

**Comment by yaomtc** [comment]
Seems to be working fine now.
