### ISSUE TITLE
Source field does not allow to add a source that contains comma

### ISSUE THREAD

**Issue by SLMapper** [openstreetmap/iD#10125]
### URL

openstreetmap.org/edit

### How to reproduce the issue?

1. do any change
2. hit save button (ctrl+s)
3. in the source > "add" filed add text containing a comma, e.g. `http://example.com/?foo,bar`
![grafik](https://github.com/openstreetmap/iD/assets/104768113/516de824-d384-4103-a581-12fbe0e29de6)

4. hit the enter key
Result: source wrongly gets split at the comma. neither wrapping in quotes nor trying to use a backslash to escape it works.
![grafik](https://github.com/openstreetmap/iD/assets/104768113/0a4626a9-3881-4311-8052-9a9a9b0b8cea)

Seems to correctly work when adding source to a feature.
![grafik](https://github.com/openstreetmap/iD/assets/104768113/5d16b14e-f2cc-4d2f-b69f-e256a2e97bc7)

Work around: url escape the comma as `http://example.com/?foo%2Cbar`
![grafik](https://github.com/openstreetmap/iD/assets/104768113/26311683-cb03-438f-a060-8a4a92e266fb)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.3

### Which browsers are you seeing this problem on?

Firefox

**Comment by riQQ** [comment]
Another workaround is to add the source via the changeset `Tags` textbox (key `source`).

![image](https://github.com/openstreetmap/iD/assets/3404787/d753f7a8-0145-4a9a-a74c-7a6ada355ea5)

**Comment by SharanRP** [comment]
It is not some kind of bug, it is done intentionally , In the context of domain names, the comma character is rarely used, while the semicolon; is commonly used as a delimiter. The code replaces all occurrences of , with ; in a given string. This is done intentionally to standardize the format of the data, making it easier to split the string into an array of substrings later on.
![image](https://github.com/openstreetmap/iD/assets/136159249/596f2700-f3e4-4de7-8b99-7918d7ca7fca)
this the part of the openstreetcode , here it replaces all the ',' with ';' and then splits

**Comment by SLMapper** [comment]
Thank you. I think I read something like it is intentional for the sake of being able to mass add sources into the textfield - however could not again find the issue mentioning it now.
I just would have wanted a way to overcome this behavior.
I'm fine now as I found/was pointed to work arounds. Having this documented as an issue with work around info here may help others to find and solve it and so I will close this.
