### ISSUE TITLE
Mapillary viewer link to viewed image

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#10135]
### URL

https://github.com/facebook/Rapid/issues/1337

### How to reproduce the issue?

Something somewhere changed, and now there is no direct link to the Mapillary Image on mapillary.com anymore from the image viewer inside iD/Rapid.

<img width="360" alt="image" src="https://github.com/openstreetmap/iD/assets/111561/a6d52d5e-3f07-4cff-a68f-4da1301e82bc">

(The mouse hovers the Mapillary Logo which AFAIK was the direct link once but now opens the Mapillary homepage.)

There is an issue at https://github.com/facebook/Rapid/issues/1337 which tracks the same topic.

**Comment by Sushil642** [comment]
@tordans 
 This issue was happening just because of anchor tag link.I made changes and now the mapillary logo work as direct link to 
mapillary image on mapillary.com.
I submitted the PR #10141 .Please approve my Pr.

**Comment by tyrasd** [comment]
Turns out this is a bug in the upstream library. iD _might_ be able to hot-patch the output produced by the mapillary-js library to work around this, but it would be better if this could be fixed at the root.

**Comment by tordans** [comment]
@tyrasd It might not be a bug but the feature changed upstream. @eneerhut wo created https://github.com/facebook/Rapid/issues/1337 is from Mapillary (https://github.com/eneerhut) so I assumed by the fact that he reported it the issue should be solved by the editor(s).

Update: Having read https://github.com/openstreetmap/iD/pull/10141#issuecomment-1972783620 more carefully I agree that this should be fixed in https://github.com/mapillary/mapillary-js – FYI @eneerhut.

**Comment by tyrasd** [comment]
Hmm, wait… You might be right, actually. :see_no_evil:  To me this looked like an oversight, as the library does produce the "seemingly correct" image link on the mapillary logo when it is using the code path for the case where the username is not present ([here](https://github.com/mapillary/mapillary-js/blob/a1df915/src/component/attribution/AttributionComponent.ts#L146)). But what I had missed is that the function that is called with the username present, there is an additional (deep) link produced. But for some reason that link is however currently [hidden](https://github.com/openstreetmap/iD/commit/7a0d8adb7b074cbf4a40cfbfe47a3f0cfc09ddaf#diff-56fc787113948ee3ddbf3d4979def5dbe8a49fc58cd98ebfd25c8ef364d4fa93R319) in iD.

IMO it is kinda confusing that only the link containing the username goes directly to the image (I would have expected that one to go to a user profile or something like that), but I guess that's up to the library to decide.

**Comment by tyrasd** [comment]
fixed with #10141
