### ISSUE TITLE
:wikipedia bug

### ISSUE THREAD

**Issue by UKChris-osm** [openstreetmap/iD#10140]
iD seems to now be suggesting to add empty "_:wikipedia_" tags for NSI items. These tags were removed a long time ago, so I'm not sure why iD is now suggesting to add empty ones?

Ref: https://github.com/osmlab/name-suggestion-index/issues/9284

![nsi-bug](https://github.com/openstreetmap/iD/assets/59393694/5f120873-9504-4e65-9c21-63300e71956b)

**Comment by arch0345** [comment]
This seems to be caused by https://github.com/openstreetmap/iD/commit/4829f8a1dabf833b8b11fa707280bf5b1b707ab2

**Comment by UKChris-osm** [comment]
> This seems to be caused by [4829f8a](https://github.com/openstreetmap/iD/commit/4829f8a1dabf833b8b11fa707280bf5b1b707ab2)

Yes, that's what I'm thinking - so not something we can fix from the NSI end?

**Comment by UKChris-osm** [comment]
`   if (preset.tags['brand:wikidata']) {
          preset.addTags['brand:wikipedia'] = '';
        }`

... the code seems to be checking for a :wikidata tag, and just adding an empty :wikipedia tag to the item - was this intentional?

**Comment by tyrasd** [comment]
>  adding an empty :wikipedia tag to the item - was this intentional?

yes, this was intentional, as you can read in the source code comment:

> nsi does not specify *:wikipedia (anymore):
> clean up previous values to prevent that the wikidata/wikipedia information
> is going to be out of sync, see #9103

I went with the fix proposed in https://github.com/openstreetmap/iD/issues/9103#issuecomment-1125646368, but unfortunately this introduced/triggered a bug in the validation module, which no one found before the release. It should not be too hard to fix, though.

**Comment by tyrasd** [comment]
FYI: I created a patch release (v2.28.1) for this: see https://github.com/openstreetmap/openstreetmap-website/pull/4551
