### ISSUE TITLE
Character in wikidata box was displayed in strange linebreak

### ISSUE THREAD

**Issue by LaoshuBaby** [openstreetmap/iD#10143]
### URL

https://www.openstreetmap.org/edit?way=1255852379

### How to reproduce the issue?

Wait for editor load finish and see wikidata infobox

You can try different languages's UI to test:

* https://www.openstreetmap.org/edit?way=1255852379&locale=zh-CN#map=19/21.03809/105.84943
* https://www.openstreetmap.org/edit?way=1255852379&locale=en#map=19/21.03809/105.84943
* https://www.openstreetmap.org/edit?way=1255852379&locale=vi#map=19/21.03809/105.84943

You can see the width of "market in Hanoi, Vietnam" and "Q1094375" and its cell height are different in languages, the line height in Chinese and Vietnamese are higher is because strings was splited to 2 lines (And I must say the line break of "描述" "标识符" are too strange)
The space used for description is very sufficient, and even the horizontal space of a short QID is more than that of short description sentences.

I think there's a typographical problem here because iD didn't display like this in the past

### Screenshot(s) or anything else?

**Please see where to enter Wikidata on the left**

<details>
<summary><b>**screenshots (click to expand)**</b></summary>

![图片](https://github.com/openstreetmap/iD/assets/42690037/fa46ccbd-9c2f-4a6c-b0ba-ef16154c88fc)

![图片](https://github.com/openstreetmap/iD/assets/42690037/f2c2d1f8-2a12-4224-8429-d6f2d2f00f6b)

![图片](https://github.com/openstreetmap/iD/assets/42690037/095d1f61-f9eb-474d-a61e-1e103ec5cd41)

Older version on OGF (2.20.1) split column correctly （Sorry, this is the fastest way I can find a living old version of iD）

![图片](https://github.com/openstreetmap/iD/assets/42690037/de9b62a5-8c78-47ba-9f1b-93913b06028e)

</details>

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

>2.28.0 (those days)

### Which browsers are you seeing this problem on?

Firefox

**Comment by tordans** [comment]
Thanks for the good report @LaoshuBaby that made it easy to track down.
It looks like I broke this with https://github.com/openstreetmap/iD/pull/10127/files by changing the requirement for the first column to use `div` instead of `span`.

https://github.com/openstreetmap/iD/pull/10144 should fix it. See before/after screenshots in the PR.
