### ISSUE TITLE
amenity=bicycle_parking area should not require area=yes

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#10167]
### URL

https://www.openstreetmap.org/edit?editor=id&way=618040591#map=19/50.08583/19.97116

### How to reproduce the issue?

Create `amenity=bicycle_parking` area

Create `amenity=bicycle_parking` `area=yes` area

Second should not get better rendering

### Screenshot(s) or anything else?

![screen02](https://github.com/openstreetmap/iD/assets/899988/a030d34d-d049-43d8-ba3e-35012c2d4b5d)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.28.1

### Which browsers are you seeing this problem on?

Firefox

**Comment by matkoniecz** [comment]
I know about https://github.com/ideditor/id-area-keys ( https://wiki.openstreetmap.org/wiki/Area#Tags_implying_area_status  ) but it got redesigned ago and I failed to find where it stores actual data definitions.

Also, not sure is iD using it for that purpose here.

**Comment by matkoniecz** [comment]
I made https://github.com/matkoniecz/id-area-keys/commit/d7a3ff383bd67fb96612b5715257c0b75b07cce3 but I see no info in readme how to run tests, maybe I will try random stuff like `npm test` later

**Comment by hirako2000** [comment]
> I made [matkoniecz/id-area-keys@d7a3ff3](https://github.com/matkoniecz/id-area-keys/commit/d7a3ff383bd67fb96612b5715257c0b75b07cce3) but I see no info in readme how to run tests, maybe I will try random stuff like `npm test` later

`nom run test`, one can find all the npm scripts available in [package.json](https://github.com/openstreetmap/iD/blob/develop/package.json). In `scripts`

**Comment by matkoniecz** [comment]
@hirako2000 Have you meant `npm run test` ?

If yes, then

```
> id-area-keys@6.5.0 test
> run-s test:node


> id-area-keys@6.5.0 test:node
> node --test test/

node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module '/home/mateusz/Desktop/tmp/id-area-keys/test'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v21.7.0
✖ test (26.835304ms)
  'test failed'
```

**Comment by hirako2000** [comment]
> Node.js v21.7.0
> ✖ test (26.835304ms)
>   'test failed'

I see.

I suggest for now to use node 18 for this project. 
Make sure to do an `npm install` then `npm run test` with that version and see what result you get.

Use nvm if you have other projects that do require v21.

**Comment by danieldegroot2** [comment]
Should be resolved by https://github.com/openstreetmap/iD/commit/ee56b9c8ae1ec1e5f7544b9644409b82e4e63e3a

**Comment by maro-21** [comment]
Since a bicycle parking can also be mapped as a line, the `area=yes` tag is necessary here to distinguish a closed line from an area. Therefore, it is fine.

**Comment by matkoniecz** [comment]
Not for closed ways, and for unclosed ways it is a mistake anyway.

Interpreting closed ways with `amenity=bicycle_parking` as lines is silly and a bug. Basically all are actually areas, if not all of them.

(if someone really wants to map bicycle parking as a closed way and treat it as a line they need to add `area=no` - though I would strongly advise against mapping them as lines)

**Comment by tordans** [comment]
@matkoniecz I think this [is resolved](https://github.com/openstreetmap/iD/issues/10167#issuecomment-2027199101) so I will close it. Please reopen if I missed anything.
