### ISSUE TITLE
Add building:levels to building=construction

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#10187]
Buildings under construction also have floors... And this field is not in this preset at all. To add floors, I have to first select another building type, add the number of floors, and then change to `building=construction`.

**Comment by tordans** [comment]
This sounds like a Preset issue which needs to be raised and solved in https://github.com/openstreetmap/id-tagging-schema

I will close this for this Repo.

**Comment by maro-21** [comment]
Can you move the issue there instead?

**Comment by tordans** [comment]
> Can you move the issue there instead?

Unfortunately not due to missing permissions.
