### ISSUE TITLE
Don't remove spaces after the semicolon in the [inscription] field

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#10188]
Currently when I type
```
description=sth; sth; sth
inscription=sth; sth; sth
note=sth; sth; sth

cuisine=sth; sth; sth
source=sth; sth; sth
sport=sth;   sth;   sth
```
iD changes it to

```
description=sth; sth; sth
inscription=sth;sth;sth
note=sth; sth; sth

cuisine=sth;sth;sth
source=sth;sth;sth
sport=sth;sth;sth
```

It is correct to remove spaces for `cuisine`, `source` and `sport` (there should be no spaces).
It is correct to not remove spaces for `description` and `note`.
But for `inscription` there should be the same behavior as for `description` and `note` becuase it is the similar type of key.

**Comment by 1ec5** [comment]
`inscription` needs to be added to this regular expression (which should probably become a dedicated property in schema-builder and id-tagging-schema):

https://github.com/openstreetmap/iD/blob/a38d7a1b8d50a3e358f4e0f0a5ae5a42b3d7cf58/modules/util/clean_tags.js#L20
