### ISSUE TITLE
Block non-compatiable license map: NLSC map from Taiwan

### ISSUE THREAD

**Issue by Supaplextw** [openstreetmap/iD#10195]
### Description

Hi, 

The Taiwan map survey center have released a open data version map wich can be use on tracing roads or waterways to OpenStreetMap. But the full version of the map: NLSC map(http://wmts.nlsc.gov.tw/wmts/PHOTO2/default/EPSG:3857/{zoom}/{y}/{x}) is not compatible with the OpenStreetMap license. There are some mappers in Taiwan ignore the community's warning and still use this image source. 

Can the iD editor block the use of NLSC map as customs image layer?

Supaplex

**Comment by tordans** [comment]
@Supaplextw given Martins answer in https://github.com/openstreetmap/iD/issues/9708#issuecomment-1632115212 I will close this ticket since this need to be reported in the osm website project. Please raise the issue over there.
