### ISSUE TITLE
Icons for form elements

### ISSUE THREAD

**Issue by samanpwbb** [openstreetmap/iD#1019]
This goes on the "if I have infinite time" list, but I think there would be usability benefits from adding descriptive icons to form elements. Here's a quick mock-up of how this could look:

![Screen Shot 2013-03-13 at 11 36 38 AM](https://f.cloud.github.com/assets/108094/254435/01e0670c-8bf4-11e2-8723-4bc5fa219284.png)

Dependent on #1000

**Comment by bhousel** [comment]
Pruning the issue list.. @samanpwbb do you still want this?
