### ISSUE TITLE
 Warning! NSFW street name

### ISSUE THREAD

**Issue by Uladzimir-Bulakhau** [openstreetmap/iD#10196]
### URL

https://www.openstreetmap.org/#map=13/53.8335/27.6123&layers=N

### How to reproduce the issue?

https://www.openstreetmap.org/note/4192878#map=14/53.8439/27.5543&layers=N

**Street name "Andy Townsend Loves ch... po..."**
How to see it
[Link](https://www.openstreetmap.org/note/4192878#map=14/53.8439/27.5543&layers=N)
zoom 13-14 (map=13/14 in url parameters)
Standard layer
This fake street is not visible at all magnifications, for me it is displayed on zoom settings 13/14/15

**This street is not available in the map editor**

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

**Comment by Dimitar5555** [comment]
That's not an iD problem. That is vandalism that has been removed by the Data Working Group. Sometimes the map tiles are cached and you may see already deleted data.
