### ISSUE TITLE
`npm run start` does not pick up css changes

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#10193]
### URL

-

### How to reproduce the issue?

For https://github.com/openstreetmap/iD/pull/10046 I did a new checkout of this branch
- ran npm i
- ran npm run start
- [tested locally](http://127.0.0.1:8080/#background=Berlin-2021&disable_features=boundaries&locale=en&map=21.21/52.52084/13.39184&photo=mapillary/2067309883618118&photo_overlay=mapillary)

The css from https://github.com/openstreetmap/iD/pull/10046/files#diff-56fc787113948ee3ddbf3d4979def5dbe8a49fc58cd98ebfd25c8ef364d4fa93R36 was not picked up.

Second test
1. stop server
2. run npm run build
3. run npm run start
4. now the css is picket up

So something does not happen which happens in `build` which should also happen in `start`, right?

### Screenshot(s) or anything else?

-

### What version numbers does this issue effect?

https://github.com/openstreetmap/iD/pull/10046

### Which browsers are you seeing this problem on?

Chrome

**Comment by k-yle** [comment]
I always run `npm run all` after editing non-JS files, but for this case `npm run build:css` is probably sufficient?

**Comment by MeteSayan** [comment]
If I understand correctly, the `npm run start` command includes `start:watch`, which in turn only encompasses `build:js:watch`. Therefore, it's normal that the CSS distribution isn't updated with the `npm run start` command alone. As @k-yle mentioned, running the `npm run build:css` command is necessary to update the CSS distribution.

I'm relatively new to contributing to this repository, so if I've misunderstood the issue, I'll gladly correct my response.

**Comment by laigyu** [comment]
I think only js has --watch, so if editing non-js files, need to build the corresponding file type first.
```npm run all``` : ```clean``` + ```build``` + ```dist``` , I think is cover most part

```npm run build```: ```build:css``` + ```build:data```(ex. core.yaml) + ```build:js``` , 3 type

not sure what ```clean``` and ```dist``` doing, 
My understanding is that ```clean``` is remove some type of file in dist/, and dist is build some type of  file(ex. svg) to dist/

```npm run start``` : ```build:js:watch``` +  ```start:server``` , only build js

```npm run test```: ```lint``` +  ```build``` + ```test:spec``` , 3 type + lint + test

time(although comparing time is meaningless)
```npm run test``` >>>>> ```npm run all```  > ```npm run build``` 

I usually use ```npm run build``` + ```npm run start``` to test ui, I think is ok

---
[package.json](https://github.com/openstreetmap/iD/blob/develop/package.json#L14)
[npm run all](https://github.com/mysticatea/npm-run-all/blob/bf91f94ce597aa61da37d2e4208ce8c48bc86673/docs/npm-run-all.md)
[svg-sprite](https://github.com/svg-sprite/svg-sprite)
[shx](https://github.com/shelljs/shx)

**Comment by tordans** [comment]
Thanks for the help. I will close this and hope to remember to run all first next time…
