### ISSUE TITLE
 outdated image

### ISSUE THREAD

**Issue by sfcr33** [openstreetmap/iD#10214]
### URL

https://www.openstreetmap.org/edit#map=16/36.3381/33.4002

### How to reproduce the issue?

Hello. I use your platform a lot, but you need to upload updated satellite images. You are showing images from about 5 years ago. It causes us to receive incorrect data. Google Earth images seem more up to date. I would be very happy if you do a study on this subject. :)

### Screenshot(s) or anything else?

If you compare the images with Google Earth images, you will already see whether they are up to date or not.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.28.1

### Which browsers are you seeing this problem on?

Chrome

**Comment by Dimitar5555** [comment]
Google Satelite imagery can't be used on OpenStreetMap because it has incompatible license. The other imageries (Bing/Esri/Mapbox) are maintained by the respective company and only they can update them. Neither the iD editor nor it's maintainers have control over those companies.

**Comment by tordans** [comment]
@sfcr33 bad aerial imagery is a big issues in many regions but it is not something we can solve in this repository. The imagery is managed at https://github.com/osmlab/editor-layer-index.
However, the work to find a usable image source for your regions is something that the local community has to do. Sometimes there is government imagery with a OSM [compatible license](https://osmfoundation.org/wiki/Licence/Waiver_and_Permission_Templates/Template_text_for_aerial_imagery_waivers) that can be used…

I am closing this for this repo.
