### ISSUE TITLE
Edit mode won't load in all browsers (SOLVED)

### ISSUE THREAD

**Issue by indiradefa** [openstreetmap/iD#10217]
### URL

https://www.openstreetmap.org/edit#map=19/-6.92823/107.77545

### How to reproduce the issue?

Simply clicking the edit button with in-browser editor

### Screenshot(s) or anything else?

There has been frequent update logs from users claiming to be with the "Apple team". Wonder if this causes an **overload - likely the issue**

### What version numbers does this issue effect?

SOLVED, I can't see version number in viewing mode, only editing - 2.28.1

### Which browsers are you seeing this problem on?

Chrome, Microsoft Edge

**Comment by tordans** [comment]
I am closing this given the update to the title to be "SOLVED"
