### ISSUE TITLE
Charging Stations for E-Bikes

### ISSUE THREAD

**Issue by eWolfgangC** [openstreetmap/iD#10237]
### Description

There should be an Icon for Charging-Stations for E-Bikes in the map for bycicles.

**Comment by tordans** [comment]
Hey! This is a topic for the id-tagging-schema Project https://github.com/openstreetmap/id-tagging-schema.
Please open a new issue there and add some background on tagging, usage and so on.
But please check the existing issues first, there are some that touch on that topic https://github.com/search?q=repo%3Aopenstreetmap%2Fid-tagging-schema+charging&type=issues

One question to answer will be, which Icon to choose. There is more info on existing icons that can be used in https://github.com/ideditor/schema-builder/blob/main/ICONS.md which is a project/repo related to the one linked before.

For this project, I will close the issue. (I cannot move them, unfortunately.)
