### ISSUE TITLE
addr:housenumber tag changes/deletes on its own

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#10260]
### How to reproduce the issue?

When editing different buildings/nodes, sometimes when you click on the next building/node to edit it, the addr:housenumber tag is either changed or deleted from the previous one. 

For example in changeset 151866677, I moved n3655584338 to create a new node n11935548098 and the addr:housenumber tag disappeared from the first node.

This has happened recently when adding lots of houses and addresses too. The postcode tag might also have been affected on that occasion.

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/20193716/0325a2ab-5dc0-47e6-9f32-12f9b116375b)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
I can confirm the bug. Slightly more precise steps to reproduce:

1. select an existing map feature with an _Address_ field, e.g. an address node with `addr:housenumber=1`
2. put cursor in housenumber sub-field
3. select a different feature with an _Address_ field, e.g. an address node with `addr:housenumber=2`
4. sometimes, the full address of the now selected feature will be overwritten with the information in the previous feature. e.g. now reading `addr:housenumber=1`
    - this does not happen every time; in my testing sometimes it happened immediately, sometimes it required 10 clicks
    - it does not happen if the cursor is not in one of the address sub fields of the

**Comment by tyrasd** [comment]
fixed in 97d1aa5e2d003b8fb21924b536ca87c4eb3257b9
