### ISSUE TITLE
Query run for highway key gives me a critical error

### ISSUE THREAD

**Issue by gybe777** [openstreetmap/iD#10279]
### Screenshot(s) or anything else?

<img width="1792" alt="Screenshot 2024-06-13 at 15 57 55" src="https://github.com/openstreetmap/iD/assets/172617473/24063dd2-99b3-42d7-ad09-ed8b0ad75ef1">

### What version numbers does this issue effect?

gpl 2

**Comment by Dimitar5555** [comment]
This issue tracker is for the iD web based editor for OpenStreetMap. The software you are using seems to be QGIS.

**Comment by gybe777** [comment]
oh sorry yeah just noticed that
