### ISSUE TITLE
Enhance User Engagement by Delaying Login Requirement Until Changes Are Saved

### ISSUE THREAD

**Issue by Gustavo22Soaresh** [openstreetmap/iD#10285]
### Description

Allowing new users to explore the editor without the need to log in initially can be a highly effective strategy. The Nielsen Norman Group article on login walls highlights how this barrier can deter new users. If the ID adopted the approach of requesting login only when saving changes, it could reduce initial frustration and increase participation. By letting users experience the editor first, they may feel more engaged and motivated to register, knowing their contributions will be meaningful. This change can turn curious visitors into active contributors, boosting the project's growth and quality.

### References
https://www.nngroup.com/articles/login-walls/

**Comment by 1ec5** [comment]
Are you referring to the user experience on openstreetmap.org? Indeed, that website places this editor behind a login wall. By contrast, when iD is embedded on other websites, such as [this preview site](https://ideditor.netlify.app/), you only need to log in once you’re ready to save. [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website/) is the codebase for the openstreetmap.org website. Your suggestion would be more actionable there.

**Comment by Gustavo22Soaresh** [comment]
thanks I move this issue to [OpenStreetMap-NG](https://github.com/Zaczero/openstreetmap-ng)
