### ISSUE TITLE
ImproveOSM service deprecated 

### ISSUE THREAD

**Issue by tBeata-grab** [openstreetmap/iD#10302]
### Description

The ImproveOSM project has been phased out. Consequently, the URLs for the publicly accessible ImproveOSM services are no longer active:
- Missing Geometry Service: previously available at https://community.improveosm.org/missingGeoService/
- Direction of Flow Service: previously available at https://community.improveosm.org/directionOfFlowService/
- Turn Restriction Service: previously available at https://community.improveosm.org/directionOfFlowService/
- 
We kindly request the removal of ImproveOSM issues map data from the iD editor.

Thank you.

**Comment by westnordost** [comment]
Note the following information after reaching out to them: In a nutshell, ImproveOSM continues, but only in the SEA region. So, keeping ImproveOSM support in iD might still be useful for mappers in this region, I don't know, so, just FYI:

> Hello Tobias,
> 
>  You can access the Oneway ImproveOSM data dumps at [this link](https://dumps.improveosm.org/?prefix=AdditionalNewDumps/OneWays/). This data, updated nightly, contains data from the SEA area. In addition to one-way data, we also publish information on:
> 
> -    2w/4w accessibility
> -    Street names
> -    Speed limits
> -    Turn restrictions
> 
> For other regions (USA, EU, etc.), we have older data available at [this link](https://dumps.improveosm.org/?prefix=ExistingDumps/OneWays/). Please note that this data will no longer be updated as we deprecated the corresponding services and JOSM plugins at the end of June.
> 
> Feel free to reach out if you have any further questions.
> 
> Best regards, Beata.

**Comment by tBeata-grab** [comment]
Just to clarify, we discontinued the ImproveOSM services mentioned in this ticket at the end of June. The data associated with these services was outdated, and client components were minimally used. 

The ImproveOSM project will continue only in the format of data dumps, available at: https://dumps.improveosm.org/?prefix=AdditionalNewDumps/.

**Comment by MASangys** [comment]
> Just to clarify, we discontinued the ImproveOSM services mentioned in this ticket at the end of June. The data associated with these services was outdated, and client components were minimally used.
> 
> The ImproveOSM project will continue only in the format of data dumps, available at: https://dumps.improveosm.org/?prefix=AdditionalNewDumps/.

Just need to confirm, the data dumps license is same as KartaView license, that editors can freely refer to the database to edit on OSM right?
