### ISSUE TITLE
Add natural=shrubbery and shrubbery:density

### ISSUE THREAD

**Issue by Swarkin** [openstreetmap/iD#10311]
### Description

- [natural=shrubbery](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dshrubbery)
- [shrubbery:density](https://wiki.openstreetmap.org/wiki/Key:shrubbery:density)

### Screenshots

![chrome_yVm5L0awN1](https://github.com/openstreetmap/iD/assets/102416174/18806bd7-f95b-4bf5-adf4-4f5fb7d620ff)

**Comment by tordans** [comment]
Hey! This is a topic for the tagging schema repo and there is an issue for it already.

**Comment by Swarkin** [comment]
Can you point me to it?

**Comment by tordans** [comment]
Yeah, sorry, was just about to, its over here https://github.com/openstreetmap/id-tagging-schema/issues/406

**Comment by tordans** [comment]
The [shrubbery:density](https://wiki.openstreetmap.org/wiki/Key:shrubbery:density) is mentioned there. It may be best to have a separate issue for that.
