### ISSUE TITLE
iD surreptitiously changes addresses

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#10314]
iD automatically changes addresses without notice. Building has an address and POI within this building has an address. Change street  name in the building, click on the node within this building which has the same address. Now the address has changed automatically, and  there are "2 changes". There is no message that it has been changed. It changes more than just the street. I added a POI in a building with housenumber=5/77, clicked on an address that has the number 5, and it added 77 to that address.

It is not only with addresses that this is the case. If, for example, I edit the opening hours at one node and then click on another, iD automatically deletes the opening hours from the latter point.

For example here in the version 4 https://osm.org/node/6633331312/history iD added the address itself, I didn't edit this ice cream parlor. Moreover, it added `addr:place` instead of `addr:street`.

**Comment by tordans** [comment]
This sounds like https://github.com/openstreetmap/iD/issues/10260 ?
Which was fixed, but there was no release since the fix AFAIK.

**Comment by 1ec5** [comment]
Either that or #9850 maybe.

**Comment by maro-21** [comment]
Yes, it's probably the same issue!

One more point I want to emphasize is that iD itself added `addr:place`, even though there is no such field in the editor.

**Comment by maro-21** [comment]
An example of this bug is highly visible here:
https://overpass-api.de/achavi/?changeset=155078172
iD changed housenumbers while adding the postcodes by the user.

**Comment by nickrsan** [comment]
It looks like the fix Tobias mentioned was released yesterday - can you confirm if your issue is still present?

**Comment by maro-21** [comment]
This error probably no longer occurs. I tested it a little and didn't notice. If I ever notice it again, I will let know. I'm closing the issue now.
