### ISSUE TITLE
Localized field hidden despite nonempty subkeys

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#10323]
The Name field is a `localized` field that displays not only `name=*` but also a very large number of potential `name:xyz=*` subkeys. The Name field is universal, so it’s enabled for every preset. However, some presets don’t display it by default. For these presets, the field stays hidden even if the feature has `name:xyz=*` set.

## Steps to reproduce

To reproduce this issue, create a Windpump (`man_made=windpump`) and manually tag it with `name:es=El Gran Molino`. Observe that the Name field doesn’t appear.

<img src="https://github.com/user-attachments/assets/32db1e7a-09a1-4af9-a152-88abf5675cf9" width="399" alt="No Name field despite name:es being set">

## Impact

In general, it’s incorrect to set `name:xyz=*` without setting `name=*`. However, this is a subject of debate for some very international features, such as [oceans and seas](https://community.openstreetmap.org/t/atlantic-ocean-repeated-name-removal/101196). Even if it’s a tagging error, the field should automatically show because it isn’t empty. This will be a bigger problem for the name fields being added in openstreetmap/id-tagging-schema#215. Those fields are universal but aren’t included by default in any preset, because the local language isn’t guaranteed to need them all, even as some other language may need one of them.

## Diagnosis

The logic for showing a field needs a special case for fields of type `localized` that tests for any key beginning with the field’s key and a colon:

https://github.com/openstreetmap/iD/blob/aaa144191c5eea5d0155b262d89f88c924672431/modules/ui/field.js#L90-L102

We should use the same regular expression added in #9124 to test whether the field would show the subkey:

https://github.com/openstreetmap/iD/blob/aaa144191c5eea5d0155b262d89f88c924672431/modules/ui/fields/localized.js#L127-L131

**Comment by samhoooo** [comment]
Hi @1ec5, I created a fix for the above issue. 

This is my first time to contribute here, so would be really appreciate if you could give some comments. Thank you!
