### ISSUE TITLE
Newlines contradict with the wiki, flagged by Osmose

### ISSUE THREAD

**Issue by unnervingduck** [openstreetmap/iD#10326]
### URL

https://www.openstreetmap.org/node/11067184591

### How to reproduce the issue?

1. Create an inscription textfield
2. Add some text and press enter to create a new line
3. iD uses `\n` which contradicts with the [wiki](https://wiki.openstreetmap.org/wiki/Key:inscription) that suggests `|` or `/`. This approach is flagged by [Osmose](https://osmose.openstreetmap.fr/en/issue/cf0b4bd8-30b6-9aa4-b0e9-15e9c2894a27) too for non printable characters

Although `\n` seems to be a standard Unix way to mark them, who's wrong here? 

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29.0

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
I can reproduce this issue in Firefox on macOS. Confusingly, newlines don’t appear in the raw tag editor:

<img src="https://github.com/user-attachments/assets/de58b220-6455-49ec-b92e-2e55fe488b78" width="545" alt="Newlines in the Description field but not in the raw tag editor">

And if you save out a osmChange file, it shows a line feed character (though it might also contain a carriage return on Windows?):

```xml
<tag k="description" v="It was a dark and stormy night;&#xA;Water water everywhere,&#xA;But not a drop to drink."/>
```

https://github.com/openstreetmap/iD/issues/7249#issuecomment-574755960 suggests that newlines are intentionally supported. But if you actually upload the edit, something either on the client side or server side is normalizing the newline to a space. For example, here’s [a grocery store aisle](https://www.openstreetmap.org/way/664344293) that I uploaded using newlines to describe the hanging aisle marker sign:

```xml
<tag k="description" v="cups &amp; plates dried fruit cookware cake mixes sugar spices"/>
```

**Comment by Openstreetmapler** [comment]
Happens for me too. On [this node](https://www.openstreetmap.org/node/10579179653), I am replacing the newline characters with spaced pipes ` | `. (Edit not uploaded yet.)

**Comment by tyrasd** [comment]
> But if you actually upload the edit, something either on the client side or server side is normalizing the newline to a space. 

Hmm… At least in recent versions of iD and/or the OSM API this does not seem to happen anymore. See for example [node 9253903028](https://www.openstreetmap.org/api/0.6/node/9253903028) which I edited a few weeks ago with a newline:

```
  <tag k="inscription" v="Heiligkreuzsteinach 1,4 km Heddesbach 2,? km&#10;Fußweg nach Heddesbach"/>
```

**Comment by tyrasd** [comment]
That said, I'm not quite sure how to read the [wiki](https://wiki.openstreetmap.org/w/index.php?title=Key:inscription&oldid=2702230) on this matter:

> `|` or the spaced slash ` / ` **may** be used to represent line breaks and `||` or the spaced double slash ` // ` to paragraph breaks depending on the style guide preferred.

The word _may_ would [usually](https://datatracker.ietf.org/doc/html/rfc2119#section-5) indicate that this possibility is truly optional. :shrug:  I also don't really see what would speak against actually using newlines in such tags?!

**Comment by tyrasd** [comment]
> Confusingly, newlines don’t appear in the raw tag editor

OK, that one is what I would actually call a bug: A tag value with `\n` will get it's newline characters removed when one edits in the (table mode of the) raw tag editor.

**Comment by 1ec5** [comment]
> That said, I'm not quite sure how to read the [wiki](https://wiki.openstreetmap.org/w/index.php?title=Key:inscription&oldid=2702230) on this matter:

That’s just a convention, like using ` / ` or ` - ` to separate two `name=*` values in certain regions. I’m not sure iD can do anything particularly intelligent based on this convention, because there are plenty of inscriptions that contain a literal space–slash–space sequence in real life, and that wiki page doesn’t define an escape sequence.

**Comment by tyrasd** [comment]
@unnervingduck could you please report this to the osmose developers that this is a false positive on their side. :pray:

**Comment by unnervingduck** [comment]
> @unnervingduck could you please report this to the osmose developers that this is a false positive on their side. 🙏

Got it! I suppose there needs to be some discussion with the wiki people too, because I agree that there are many cases where a written slash may exist in real life.
