### ISSUE TITLE
False positive suspicious name in Brazil: Supermarket

### ISSUE THREAD

**Issue by nighto** [openstreetmap/iD#10334]
### URL

https://www.openstreetmap.org/edit?way=434830734#map=19/-22.90013/-43.20179

### How to reproduce the issue?

There is a supermarket operator name called... "[Supermarket](https://redesupermarket.com.br/)" (in English). When you try to map it, iD raises a suspicious name warning, which in this case is a false positive.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29.0

### Which browsers are you seeing this problem on?

Chrome

**Comment by 1ec5** [comment]
Interesting! Consider adding this brand to the [name suggestion index](https://github.com/osmlab/name-suggestion-index/). That might suppress the warning, but if not, at least it would make it easier to fix iD so that it doesn’t warn about this brand.

**Comment by nighto** [comment]
Thanks for the suggestion @1ec5, just opened a PR there :)
