### ISSUE TITLE
Crossing icons are missing

### ISSUE THREAD

**Issue by nighto** [openstreetmap/iD#10335]
### How to reproduce the issue?

Create or edit a crossing (`highway=crossing`). There used to be little icons on the preset for choosing the crossing markings (`crossing:markings`) and now those are gone.

![image](https://github.com/user-attachments/assets/d1be0035-6c31-4564-a0aa-27183d2dc53d)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29.0

### Which browsers are you seeing this problem on?

Chrome

**Comment by k-yle** [comment]
Thanks for opening an issue, this is a Duplicate of #10301 

the issue has been fixed, hopefully it will be released soon

**Comment by k-yle** [comment]
Duplicate of #10301

**Comment by nighto** [comment]
Sorry about the noise, and thanks for your reply. Closing the issue.
