### ISSUE TITLE
Way cannot be added to relation

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#10342]
### URL

https://www.openstreetmap.org/edit?node=4294262327#map=19/50.70340/-3.30986

### How to reproduce the issue?

Note that https://www.openstreetmap.org/relation/3720599 has a gap in it, as shown by http://ra.osmsurround.org/analyzeRelation?relationId=3720599 .  Browse to the gap in iD http://ra.osmsurround.org/analyzeMap?relationId=3720599 .
I can see two relations either side of the gap and only one in the gap.  When I try and add the way in the gap to the other relation, it is not shown.

### Screenshot(s) or anything else?

<img width="473" alt="Capture01" src="https://github.com/user-attachments/assets/c3b949bb-d896-4a2c-901a-5067fbe91d3e">
<img width="470" alt="Capture02" src="https://github.com/user-attachments/assets/abf485a2-1c0f-494b-aee5-0a36dee637fc">
<img width="192" alt="Capture03" src="https://github.com/user-attachments/assets/892ee010-5c1f-426e-8cbe-bba5d397a74a">

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29.0

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
I can’t reproduce the issue in this case, but I have seen something similar in the past. Forcing iD to load the whole relation may allow you to work around this issue. You can either open iD from [this relation page](https://www.openstreetmap.org/relation/3720599#map=19/50.70354/-3.30988) or search for the relation ID in iD’s main search bar, then select the relation. Another workaround I’ve had success with in the past is to select an existing member of the relation, remove it from the relation, and undo the change. I have no idea why this works.

**Comment by SomeoneElseOSM** [comment]
Yes, opening iD from https://www.openstreetmap.org/relation/3720599#map=19/50.70354/-3.30988 did work.

**Comment by tyrasd** [comment]
This one was very intriguing… The code for this combo box is very simple ([see here](https://github.com/openstreetmap/iD/blob/v2.29.0/modules/ui/sections/raw_membership_editor.js#L291)): it just shows all relations which are loaded and intersect the map screen. After a bit of digging I found that the relation in question did have a too small bounding box in [`tree.js`](https://github.com/openstreetmap/iD/blob/v2.29.0/modules/core/tree.js) for some reason. I was able to narrow it down to a pretty old part of iD's code (introduced in 5f1e40561aab2bafd72cf8f265f9bc10b60e0454). Its interesting that this was not causing bigger problems earlier.
