### ISSUE TITLE
Panoramax: Errors when image is not present in the cache

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10367]
### How to reproduce the issue?

Ref #9941 

When rapidly pressing the forward/backward button, the following error is returned
```
Uncaught TypeError: Cannot read properties of undefined (reading 'loc')
    at HTMLButtonElement.<anonymous> (panoramax.js:595:52)
    at HTMLButtonElement.<anonymous> (on.js:3:14)
```

Sidenote: when zoomed in, the map may not follow. The camera will go out of frame, it is stuck; no new images are loaded.

Chrome 127.0.6533.89 on Windows 10

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by neehhaa06** [comment]
Hello! @danieldegroot2 :)

I think this might be helpful!!

## To resolve the "Uncaught TypeError: Cannot read properties of undefined (reading 'loc')" error and the camera going out of frame when zoomed in:

>    Add null checks before accessing properties
>    Implement button click throttling/debouncing
>    Maintain map state properly
>    Review image loading logic
>    Thoroughly test with rapid button presses and zooming
>    Use console logs for debugging
>    Ensure all edge cases are handled in event handling and state management

**Comment by tyrasd** [comment]
@danieldegroot2 – I'm having a little trouble reproducing the issue. Perhaps this specific to a certain panoramax sequence where the API does return corrupted data?? Do you remember the location/photo-sequence where you encountered this?

@mattiapezzotti – regardless, let's make sure that if the image is not present in the [cache](https://github.com/openstreetmap/iD/blob/b4eaeb3/modules/services/panoramax.js#L593), the `step` function does not crash.

**Comment by danieldegroot2** [comment]
I think I got it somewhere on the Ring of Antwerp going west, but it does not come up again.
https://api.panoramax.xyz/#pic=398b3d80-5838-46f3-a12a-9e0399e6589a&focus=pic

**Comment by danieldegroot2** [comment]
This error does actually happen when it goes out of frame -and image is not cached- as mentioned. Here are the following errors

https://api.panoramax.xyz/#pic=b5175f1e-4fc3-44b8-9cee-6257bc2b350b&focus=pic
to the north coming out of the bend going straight east

```
hash.js:158 Uncaught TypeError: g.selectedIDs is not a function
    at c (hash.js:158:57)
    at on.js:3:14
c @ hash.js:158
(anonymous) @ on.js:3
hashchange
updateUrlImage @ panoramax.js:377
selectImage @ panoramax.js:386
(anonymous) @ panoramax_images.js:190
Promise.then
A @ panoramax_images.js:188
(anonymous) @ on.js:3
```
```
panoramax.js:595 Uncaught TypeError: Cannot read properties of undefined (reading 'loc')
    at HTMLButtonElement.<anonymous> (panoramax.js:595:52)
    at HTMLButtonElement.<anonymous> (on.js:3:14)
(anonymous) @ panoramax.js:595
(anonymous) @ on.js:3
```
In this short section, first error returned only once, undefined 'loc' error happened numerous times.

**Comment by tyrasd** [comment]
Ah, thanks, I can reproduce it now: one has to click prev/next quite fast for a while until the map needs to load the neighboring vector tile. As this loading will take a few milliseconds, there is a short interval where the data is not yet in cache. Makes sense.

I'd say that just aborting the step operation is probably sufficient to fix this. Disabling the button(s) until the data is properly loaded would also work, but would make the implementation quite a bit more complex and not have too much benefit in the use case where one just wants to follow where the sequence leads as fast as possible.

**Comment by mattiapezzotti** [comment]
This prevents iD crash, it's not a real fix but gets the job done. If we need a real one (with something like the button turning grey while waiting for the images to load) just let me know, but it would be kinda hard I think

**Comment by tyrasd** [comment]
I'd say it's ok for now, thanks @mattiapezzotti
