### ISSUE TITLE
quotation marks in the text field are ignored

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#10369]
- Find any point with tags
- Swtich from "list" of tags to "text"
- Modify tags, add tags or delete tags
- Add manualy any key with quotation marks, but not as a first character, e.g. `note = this is "TEST"`
- Switch back to "list" view - no tags have changed
- Switch back to "text" - they are still there

**Comment by tyrasd** [comment]
this is a side effect of 16ec25753d093ea67dfff74b54371b10be3f5313 - it was meant that allow to enter quoted strings with special characters, e.g. `note="line1\nline2"`. This meant that one had to escapt quotation marks to use them as proper characters, e.g. `note=this is \"TEST\"` or `note="this is \"TEST\""`. That said, this is documented nowhere (AFAIK), and IMO also slightly unintuitive (I would think one might expect either minimal CSV-style escape syntax or full JSON style strings for strings with escape-characters in such a situation).
