### ISSUE TITLE
Panoramax: Sequences stay loaded outside their intended zooms

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10365]
### URL

https://ideditor.netlify.app/#background=EsriWorldImageryClarity&disable_features=boundaries&map=20.07/48.85434/2.33115&photo=panoramax/487906d0-60af-4ca1-a197-a1e554875a5f&photo_dates=2024-02-01_&photo_overlay=mapilio,panoramax

### How to reproduce the issue?

Ref #9941

With the sequence
https://api.panoramax.xyz/#pic=487906d0-60af-4ca1-a197-a1e554875a5f&focus=pic

is a non-existing(?) ghost sequence which seems to zig zag alongside it. (only shown in iD)

Similar at https://ideditor.netlify.app/#background=EsriWorldImageryClarity&disable_features=boundaries&map=20.67/48.82421/2.40831&photo=panoramax/9a763f23-9f5c-4b4a-875a-8f3487cdedb9&photo_dates=2024-02-01_&photo_overlay=panoramax
might indicate it also breaks on sharp turns / bad GPS.

Chrome 127.0.6533.73 on Windows 10

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/0679dd63-5c76-4250-a161-5ec9e029d0c2)

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by mattiapezzotti** [comment]
Mhh this is weird, I have seen this before but cannot replicate it, maybe something to do with the cache and how sequences are saved
![image](https://github.com/user-attachments/assets/9a879957-f0d0-4868-a189-857df884713a)

**Comment by tyrasd** [comment]
I think this always happens when one starts with iD zoomed out quite far (where only the sequences are shown) and then zooms in to a higher zoom level. The simplified sequences loaded for the low zoom view should not be rendered then.

**Comment by danieldegroot2** [comment]
At z15, the whole layer has to reload. Let's see if this improves with half the amount of traces being loaded.

---

Let's zoom in to this roundabout.
(you should be able to ignore the offset, this is due to the terrain)

https://ideditor.netlify.app/#background=fr.ign.bdortho&disable_features=boundaries&map=9.00/-20.9173/55.5424
Zoom 9: No layer yet

https://ideditor.netlify.app/#background=fr.ign.bdortho&disable_features=boundaries&map=10.00/-20.9173/55.5424&photo_overlay=panoramax
Zoom 10: There is the layer with simplified traces

https://ideditor.netlify.app/#background=fr.ign.bdortho&disable_features=boundaries&map=15.00/-20.9173/55.5424&photo_overlay=panoramax
Zoom 15: There is the bubbles, layer has to unload and load in again for a moment.

---

After PR, simpified traces should disappear / regular traces should start to appear also at this zoom. will see what happens to loading then.

**Comment by danieldegroot2** [comment]
Hooray, it is fluid.
