### ISSUE TITLE
Panoramax: Rotate camera triggers move background layer

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10360]
### How to reproduce the issue?

Ref #9941 

> Some minor "bug" or suggestion: When focusing the panoramax imagery I one can use arrow keys to move left/right, but the map will move left/right at the same time, which probably isn't intended?
> https://mapstodon.space/@gedankenstuecke@scholar.social/112874679255238117

@gedankenstuecke

When a 360(/wide) image is selected, rotating the camera with the arrow keys will also move the background layer.

Chrome 127.0.6533.73 on Windows 10

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by gedankenstuecke** [comment]
Thanks for opening this up here - and sorry for not doing so myself! :heart:
