### ISSUE TITLE
Panoramax: Bubbles are insufficiently simplified

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10378]
### How to reproduce the issue?

Ref #9941 

Sequences contain multiple bubbles, then a gap, etc. There are still many images which can't be clicked (clutter/redundant)

Let's zoom in to this roundabout. (but let's skip to the proper zoom level)

https://ideditor.netlify.app/#background=fr.ign.bdortho&disable_features=boundaries&map=15.00/-20.9173/55.5424&photo_overlay=panoramax
Zoom 15+: Could the bubbles be further clustered so there is only one every so often and at more consistent interval?

Sidenote: Mapillary's behaviour for loading certain bubbles was also somewhat random in this regard.

Chrome 127.0.6533.89 on Windows 10

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/7e6571e6-4144-485c-9717-78f7a0f2ae62)

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
the markers are now more evenly sampled in mid zoom levels where not all photos can be rendered:

![image](https://github.com/user-attachments/assets/7c13c22f-f89f-48a6-8781-d2a1e786287a)
