### ISSUE TITLE
Panoramax: Maximum zoom seems lower than for Mapillary

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10391]
### Description

Ref #9941

Maximum zoom for Panoramax seems lower than for Mapillary and Panoramax web. Is there a reason for this?
Ex. https://ideditor.netlify.app/#background=EsriWorldImageryClarity&disable_features=boundaries&map=20.73/52.65048/-7.25185&photo=panoramax/13dc27e1-8404-400e-bbf6-2b543a748f39&photo_dates=2024-01-01_&photo_overlay=mapillary,panoramax

Chrome 127.0.6533.89 on Windows 10
2.30.0-dev

### Screenshots

![image](https://github.com/user-attachments/assets/72c47dc1-4c18-49a9-bc30-f2a260308a54)
Mapillary

![image](https://github.com/user-attachments/assets/fd81ecc8-4b76-446c-a9fa-929adc6d3ff9)
Mapillary web

![image](https://github.com/user-attachments/assets/465390b6-6c10-444a-94d7-bc6393766a1a)
![image](https://github.com/user-attachments/assets/6861eaca-786a-4457-bea8-1dc0a1ee0e77)
Panoramax: Restricts zoom regardless of resolution -or size of the panellum window-

![image](https://github.com/user-attachments/assets/b35227b3-3e08-4f49-a6bf-439cd0a7c68e)
Panoramax web: Allows to zoom in further than Mapillary.

Sidenote: This trace was likely imported from Mapillary to Panoramax.

**Comment by tyrasd** [comment]
the reason for this is that mapillary uses its own viewer, which has a different default max zoom level compared to the panorama viewer for panoramax (and other services).  I do agree that the max zoom level could be a little increased for panoramax & co.

**Comment by tyrasd** [comment]
@danieldegroot2 does this feel better now?

**Comment by danieldegroot2** [comment]
Yes, for reference an after image of this change
![image](https://github.com/user-attachments/assets/c1b1e1b2-f2f0-426f-86b3-0a12f6f2acce)
