### ISSUE TITLE
Not all relations are shown when I want to fill in a gap in one

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#10410]
### URL

https://www.openstreetmap.org/edit?node=10577413960#map=24/51.52962/-1.74322

### How to reproduce the issue?

Browse to that URL.
Click on https://www.openstreetmap.org/way/1230635235 , which has all the relations.
Hover the mouse over https://www.openstreetmap.org/relation/12014183 , and I can see that there's a gap 
Note that the name of relation https://www.openstreetmap.org/relation/12014183 is "Sarsen Way".   I'll need that later.
Click on one of the ways that is missing the relation, https://www.openstreetmap.org/way/24892021
Click "add to a relation"
Click Choose a parent relation
Scroll through the list and painstakingly read though each of the names (because iD won't show me to relation id) comparing with the name I remembered above.
Note that the name I want is not shown

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29.0

### Which browsers are you seeing this problem on?

Firefox

**Comment by boothym** [comment]
> Scroll through the list and painstakingly read though each of the names (because iD won't show me to relation id) comparing with the name I remembered above.
> Note that the name I want is not shown

I've just tried this (Chrome), for me it is the sixth option (Hiking Route Sarsen Way) in the dropdown? Can you find if you start typing Hi or Sa?

**Comment by SomeoneElseOSM** [comment]
> Can you find if you start typing Hi or Sa?

Who knew that typing values into a drop-down box (the label of which says "Choose a parent relation" was an option?  If an option is available, please document it in a way that's visible to the user when they're doing the thing that the documentation is for.

To answer the questions - yes, in iD 2.30.2, I don't see this problem.  Yes, typing in something does restrict what is shown in the drop-down box.  

Even better - I can type in a relation ID and search for that!  If this was _documented_, it would drastically help reduce the issues referred to at https://www.openstreetmap.org/user/tyr_asd/diary/404900#comment58045 .

**Comment by boothym** [comment]
Yes it would be good if relations UX was improved. Things like showing recently used relations at the top, sorted by type or limited  by type (e.g. railway relations showing only for ways tagged as rail) - I brought these up in issues a while ago:

https://github.com/openstreetmap/iD/issues/5329 

https://github.com/openstreetmap/iD/issues/5997
