### ISSUE TITLE
update on osm.org to get ELI update ?

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/iD#10412]
### Description

the default imagery in Brussels has changed url since the april version.
is it possible to have a deployment of version 2.29.0 with an ELI upgrade on osm.org?
in general, is it possible to have a monthly update for this kind of reason? 
I'd be happy to help with deployment

**Comment by bhousel** [comment]
Time for your regular reminder that the time I fixed this problem in 2020 by building an imagery index that could be published with version numbers (so that iD could always run with the latest imagery) - rather than allow iD to use it, Guillaume and Mikel forced me out of the iD maintainer position, lobbied to have me fired from my job, and forced Quincy to rollback the change.

https://github.com/openstreetmap/iD/pull/7428
https://github.com/openstreetmap/iD/issues/7425

**Comment by tordans** [comment]
Hey @Marc-marc-marc 

> the default imagery in Brussels has changed url since the april version.

Yes, we have quite a few updates from ELI but also other fixes and updates that need to be released.

> is it possible to have a deployment of version 2.29.0 with an ELI upgrade on osm.org?

@tyrasd is working on a release. AFAIK the last bit that needs to be polished are the recently merged Panoramax Features.

> in general, is it possible to have a monthly update for this kind of reason?
> I'd be happy to help with deployment

Monthly releases is generally the plan @tyrasd has ([see here](https://github.com/openstreetmap/iD/pull/10395/files#diff-b60c6a93e9f74ee52e71bf33781c2870b8395c8c5a34f00f61305343cb8d8447R82)), but this is off track ATM.
We recently started working on documenting some of the processes and roles to pave the road for co-maintainers to help with iD, see for more https://github.com/openstreetmap/iD/pull/10395

---

Lets keep this ticket open until the release is done so others have a place to read about the status quo.

**Comment by UKChris-osm** [comment]
The GB OS OpenMap Local Layer imagery is also nearly two years out of date, so hopefully [#2372](https://github.com/osmlab/editor-layer-index/pull/2372) can be merged into the ELI as well.

**Comment by tyrasd** [comment]
v2.30 (https://github.com/openstreetmap/openstreetmap-website/pull/5102) has new imagery

**Comment by Marc-marc-marc** [comment]
thanks
