### ISSUE TITLE
Regression - 2.30.2 does not work on Firefox 129.0.2 on Linux

### ISSUE THREAD

**Issue by mdykierek** [openstreetmap/iD#10418]
### URL

https://www.openstreetmap.org/edit#map=13/50.95502/19.37731

### How to reproduce the issue?

Empty view. No backgrounds, most options gone.
Console shows error:
Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 4365237 of the JSON data
Chrome seems to work.

**Comment by Dimitar5555** [comment]
I'm on Linux Mint using Firefox 129.0.0 and it works fine. Can you downgrade Firefox and see if it works?

![image](https://github.com/user-attachments/assets/9c29fb52-1613-4d2c-9c6c-99379f4f0baf)

**Comment by mdykierek** [comment]
No it doesn't work on downgraded FF. I am on Ubuntu. FF downloaded from firefox website - tar.bz2. Same error. Worked previously like a charm:
![image](https://github.com/user-attachments/assets/b90b54d4-a908-49a4-b5dc-3f66482a2055)

**Comment by mdykierek** [comment]
Lower the priority. Clearing the cookies and cache fixed the problem.

**Comment by tyrasd** [comment]
@Firefishy do you have any idea why this could be happening? 

> Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 4365237 of the JSON data

The causing file is almost certainly the `imagery.min.json` file (currently as asset: https://www.openstreetmap.org/assets/iD/data/imagery.min-cd263495de30d2db72076219027524ea05f895454f7ad0f5279fe382ba396b96.json), which should be slightly bigger file with 4436859 bytes uncompressed. :shrug:

**Comment by convissor** [comment]
Happening on Chrome too (127.0.6533.99 Official Build). Clearing cache (per mdykierek) cleared it up.

**Comment by Firefishy** [comment]
> @Firefishy do you have any idea why this could be happening?
> 
> > Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 4365237 of the JSON data
> 
> The causing file is almost certainly the `imagery.min.json` file (currently as asset: https://www.openstreetmap.org/assets/iD/data/imagery.min-cd263495de30d2db72076219027524ea05f895454f7ad0f5279fe382ba396b96.json), which should be slightly bigger file with 4436859 bytes uncompressed. 🤷

The 3 primary frontend servers are serving identical content:
```sh
% curl -k --compressed https://spike-06.openstreetmap.org/assets/iD/data/imagery.min-cd263495de30d2db72076219027524ea05f895454f7ad0f5279fe382ba396b96.json | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  962k  100  962k    0     0  8195k      0 --:--:-- --:--:-- --:--:-- 8230k
d57d034af07d49c6558109f8610f18c7  -

% curl -k --compressed https://spike-07.openstreetmap.org/assets/iD/data/imagery.min-cd263495de30d2db72076219027524ea05f895454f7ad0f5279fe382ba396b96.json | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  962k  100  962k    0     0  8540k      0 --:--:-- --:--:-- --:--:-- 8597k
d57d034af07d49c6558109f8610f18c7  -

% curl -k --compressed https://spike-08.openstreetmap.org/assets/iD/data/imagery.min-cd263495de30d2db72076219027524ea05f895454f7ad0f5279fe382ba396b96.json | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  962k  100  962k    0     0  6787k      0 --:--:-- --:--:-- --:--:-- 6829k
d57d034af07d49c6558109f8610f18c7  -

% curl -k --compressed https://www.openstreetmap.org/assets/iD/data/imagery.min-cd263495de30d2db72076219027524ea05f895454f7ad0f5279fe382ba396b96.json | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  956k    0  956k    0     0  2176k      0 --:--:-- --:--:-- --:--:-- 2173k
d57d034af07d49c6558109f8610f18c7  -
```

The assets look ok to me. Might be broken browser cached versions I guess.

**Comment by boothym** [comment]
Had this same problem, weirdly enough I opened Chrome developer tools to check the console and then iD worked again - which must be because I had "disable cache" ticked in the network conditions options (not sure if that's default or not).

**Comment by Firefishy** [comment]
@tyrasd Worth doing a dummy version bump to change the asset filenames?

**Comment by tyrasd** [comment]
something like this @Firefishy? https://github.com/openstreetmap/openstreetmap-website/pull/5112 – though this does not touch the imagery.json file, so it probably will only result in a new asset file name for the js file. If you want I can also create a proper release with updated imagery data set from ELI

**Comment by tyrasd** [comment]
There haven't been any more reports of this error over the last few days. Hopefully, whatever had caused it has resolved itself. Let's close this and continue monitoring the situation.
