### ISSUE TITLE
URGENT ! PRIORITY ! HUGE BUG ! NO MAP !

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#10419]
### URL

https://www.openstreetmap.org/edit?way=96403967#map=19/4.894264/-52.331584

### How to reproduce the issue?

Select on the right the Background settings.
See the result in the Backgounds section : there is 0 map, all is black !!!

### Screenshot(s) or anything else?

![2024-08-21_191325](https://github.com/user-attachments/assets/071720ca-7601-46f4-b2cb-71210937bc1c)

### Which deployed environments do you see the issue in?

Windows 11

### What version numbers does this issue effect?

2.30.2

### Which browsers are you seeing this problem on?

Firefox 129.0.2

**Comment by riQQ** [comment]
See also #10418

**Comment by Mahabarata** [comment]
I cleared cookies and caches and it works again on Windows 11.
Thanks for your help.
