### ISSUE TITLE
Do not force name for vending_machine excrement_bags

### ISSUE THREAD

**Issue by ThomDietrich** [openstreetmap/iD#10422]
### URL

https://www.openstreetmap.org/edit?node=12109214685

### How to reproduce the issue?

1. Click the link
2. Recognize that the `brand` tag is set
3. Wonder why iD wants to define the `name` tag with the `brand` name
4. Wonder even more when another potentially more meaningful name also throws an error in iD

### Screenshot(s) or anything else?

This issue follows out of the discussion at https://community.openstreetmap.org/t/name-dog-station-fur-hunde-kot-tuten-spender/89127/38 where we agreed that
 - `name` is not a mandatory tag according to the OSM wiki
 - Forcing `name` to be equal to `brand` does not make sense
 - This enforcement must be a bug in iD's ruleset

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.2

### Which browsers are you seeing this problem on?

Firefox

**Comment by tordans** [comment]
This is a topic for the name suggestion index. 
See https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=bello

I will close this here.
