### ISSUE TITLE
reproducible build : version node/os

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/iD#10426]
### Description

the last time I installed iD (a few years ago... gasp !) on my local computer to do a PR, I didn't get the same code as the one deployed on osm.org
what is the version of the node used for the build? on what os and os version? that would make things easier when you want to avoid adding bugs linked to version differences :)

**Comment by tyrasd** [comment]
I'm pretty sure the build output (`npm run dist`) should be the same regardless of OS / js version. In the past (before March 2023), we did not bundle the `package-lock.json` file with the repository, which meant that different installations could end up with slightly different versions of required dependencies: For example, when iD requires a dependency in version `1.2.*`, you might end up with `1.2.3`, while a different user might work with `1.2.2`. That would have potentially lead to slight differences in the final build output. But as we do now bundle the `package-lock.json` file with more precise dependency version locking, this should be a thing of the past. Just make sure you have the "correct" dependencies installed (`npm clean-install`) before making a build.
