### ISSUE TITLE
Some icons do not show the image.

### ISSUE THREAD

**Issue by Rockedf** [openstreetmap/iD#10428]
### URL

https://www.openstreetmap.org/edit?node=10605504425#map=19/-23.559488/-46.662565

### How to reproduce the issue?

In all maps, at the time of editing with ID version 2.30.2, some icons do not show the image.

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/87638394-53c4-45f1-8084-0fc1a3d5b009)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.2

### Which browsers are you seeing this problem on?

Firefox

**Comment by tordans** [comment]
They show up for me. Could you check if a hard reload helps?

**Comment by danieldegroot2** [comment]
For reference
without node selected https://www.openstreetmap.org/edit#map=19/-23.559395/-46.662319
related changeset https://www.openstreetmap.org/changeset/155659760

Seems the 'Settings' icon in the sidebar is broken for you besides the other icons

Note, you are in 'wireframe' mode. Press 'W' to exit this mode. You can find more shortcuts in the right sidebar at the bottom under 'Help Menu' (book with the question mark) => Keyboard Shortcuts.
This likely won't resolve the issue unless it is only a temporary a visual one.

Press F12 or similar to enable the web console. Check if there is any errors and copy them and/or post a screenshot of it.

Works fine with Chrome 128.0.6613.85 on Windows 10

@tordans can you verify your browser and version is the same as the author's?

Sidenote: Opening iD with a node open prohibits the user from i.e. entering wireframe mode immediately. User has to deselect the node first. Not sure if this is intended.

**Comment by tyrasd** [comment]
I can also not reproduce the issue.

@Rockedf It would help a lot if you could post if there are any error messages visible in your browser console. In firefox: `F12` (or hamburger menu -> more tools -> web developer tools), then switch to the _console_ tab.

**Comment by Rockedf** [comment]
> wireframe'

Sorry for the delay in responding. Now trying the options that I have been advised and still the same, with the W key I have activated and deactivated the “wireframe” mode.

I have opened the developer console with F12 and these are the errors that appear.
![Captura de pantalla_2024-08-23_20-28-48](https://github.com/user-attachments/assets/4f040234-3059-4f94-a6c0-0afc603dfd9a)

**Comment by Rockedf** [comment]
Update: Apparently it's something with Firefox, I tried opening an incognito window and it showed everything as it should. 

Hopefully the next Firefox update will fix it.

Thanks for your concern and effort.

**Comment by tyrasd** [comment]
If it works in the incognito window, it's probably still something cached… Manually [clearing the firefox cache](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache) should help.
