### ISSUE TITLE
Incorrect positioning of Minnesota Composite Image Service imagery

### ISSUE THREAD

**Issue by knkski** [openstreetmap/iD#10430]
### URL

https://www.openstreetmap.org/edit#map=21/44.9770183/-93.2263605

### How to reproduce the issue?

Go to the above URL and toggle between "Minnesota Composite Image Service" and "Hennepin County Orthoimagery (2024)", see that "Minnesota Composite Image Service" appears offset by approximately a meter

### Screenshot(s) or anything else?

Screenshots of the difference:

![Screenshot from 2024-08-22 14-03-42](https://github.com/user-attachments/assets/334d941d-1a54-4192-a0ed-c0f1ec3b4d4e)

![Screenshot from 2024-08-22 14-03-49](https://github.com/user-attachments/assets/28b23b2d-73f1-4cec-a364-865ae5b435f6)

I reached out to the contact for the MCIS imagery dataset, who said "My first thought is, has the imagery been converted to the appropriate coordinate system? I believe OSM uses WGS84, and the imagery is in UTM NAD83 Zone 15". That appears to be the issue to me.

The file is too big to link directly to the line, but in `data/imagery.json`, there's the section with `"id": "Minnesota-Composite-Image-Service"`, that is listed as `"projection": "EPSG:3857"`. This seems incorrect, as it should be https://epsg.io/26915 instead of https://epsg.io/3857, from what I can tell.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.2

### Which browsers are you seeing this problem on?

Firefox

**Comment by tordans** [comment]
Please check the "editor layer index" repo for the PR that added this imagery an reach out there or open an new issue there. iD does take the images from there.

**Comment by knkski** [comment]
@tordans This might be an issue with the import process for iD? Here's the relevant file from that repo:

https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/mn/MinnesotaCompositeImageService.geojson?short_path=bf2fb59#L807-L810

It lists both `EPSG:3857` and `EPSG:26915` as available projections, but the file in this repo only lists `EPSG:3857`. Is that an issue?

**Comment by danieldegroot2** [comment]
Opened a PR as possible quick solution. https://github.com/osmlab/editor-layer-index/pull/2459

Ref https://github.com/osmlab/editor-layer-index/pull/1031

@rbuffat Could you have a look at this, please? It seems this is another issue with generated projections, though maybe it was already fixed for future files.

**Comment by tordans** [comment]
https://github.com/osmlab/editor-layer-index/pull/2459

**Comment by tordans** [comment]
@knkski I am wondering why you think this is an projection issue? Comparing Bing vs. the other options, it looks to me that all the other options show the buildings in the same position but Bing is off. It is not uncommon that different image layers are off by a bit which is why you can adjust the image layer position to fit the commonly used mapping in that area.

**Comment by danieldegroot2** [comment]
The author seems to have been confused by OSM using EPSG:3857 instead of the more local NAD83. (not a preference of the editor itself), or it is a typo they mixed up the projections.

@tordans First layer shown on screenshots is Hennepin County, second is Minnesota Composite. Objects line up with both Bing and Hennepin but not with Minnesota Composite.

**Comment by tyrasd** [comment]
> It lists both EPSG:3857 and EPSG:26915 as available projections, but the file in this repo only lists EPSG:3857. Is that an issue?

No, that's fine: as iD can only consume EPSG:3857 (and its aliases) or EPSG:4326 (#4858) sources, all other projections are not included in the bundled file for iD.
