### ISSUE TITLE
iD should update the editor layer index due to license issues

### ISSUE THREAD

**Issue by Rainer-o** [openstreetmap/iD#10483]
### Description

Some background imagery from Geodata Service in Bavaria, Germany have been removed in https://github.com/osmlab/editor-layer-index/pull/2438 due to license objections.

Details of the license issues see conversation of PR 2438 and discussion in the forum https://community.openstreetmap.org/t/bayern-ab-01-01-2023-sind-viele-geobasisdaten-der-vermessungsverwaltung-kosten-frei-verfugbar-nutzbarkeit-fur-osm-ist-noch-zu-prufen/7051

However the iD editor still offers these layers; therefore mappers use these imagery despite the license is not compatible with OSM.

Means: the editor layer index should be updated asap, not only with the ext iD release in some weeks or months.

**Comment by tyrasd** [comment]
fixed in [v2.30.3](https://github.com/openstreetmap/iD/releases/tag/v2.30.3) patch release
