### ISSUE TITLE
Extreme loading time

### ISSUE THREAD

**Issue by kuba743** [openstreetmap/iD#10496]
### URL

https://www.openstreetmap.org/edit#map

### How to reproduce the issue?

1. Load the website
2. Click "Edit"

### Screenshot(s) or anything else?

The Edit part of the website loads extremely long, and also loading data takes an eternity. **Not an issue with my internet!**

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

### Which browsers are you seeing this problem on?

Chrome, Firefox, Microsoft Edge, Opera

**Comment by 1ec5** [comment]
Does the issue reproduce consistently for you? If you open your browser’s developer tools, do you see any errors in the Console tab or any requests in the Network tab that appear to be hung?

**Comment by kuba743** [comment]
It happens only a few days, then it's working normal. I will remember to check it when it's slow again.

**Comment by kuba743** [comment]
> Does the issue reproduce consistently for you? If you open your browser’s developer tools, do you see any errors in the Console tab or any requests in the Network tab that appear to be hung?

![obraz_2024-10-13_093852488](https://github.com/user-attachments/assets/5576009a-63b0-47cf-82aa-a4caac44a100)
This is what I got! Right now I am seeing a blank page with only the UI on the top of the page.

**Comment by 1ec5** [comment]
The OSM website normally loads iD in an iframe. However, it sounds like it didn’t even get to the point of loading iD. [This discussion](https://meta.discourse.org/t/refused-to-load-the-script-xxxx-com-cdn-cgi-speculation-because-it-violates-the-following-content-security-policy-directive/327466/2) about a similar error makes it sound like it might be a CloudFlare configuration issue, which the developers here unfortunately have no control over. Please open an issue in the [operations](https://github.com/openstreetmap/operations/issues/) repository. Thanks!

**Comment by mmd-osm** [comment]
fyi: @Firefishy

**Comment by Firefishy** [comment]
I have now disabled Cloudflare Speed Brain which was automatically enabled by Cloudflare a few days ago.

**Comment by mmd-osm** [comment]
Thanks @Firefishy ... I would assume the issue is fixed now. @Filosiq : can you confirm that the issue is no longer occurring?

**Comment by kuba743** [comment]
> Thanks @Firefishy ... I would assume the issue is fixed now. @Filosiq : can you confirm that the issue is no longer occurring?

It is faster now, but it's still a bit slow. I think it's an issue on my end. Thanks!

**Comment by olegykz** [comment]
@Filosiq I had the same issue and I resolved it by disabling `Experimental QUIC protocol` in Chrome (here - `chrome://flags/`)
With the `Default` value my network requests were hanging with a `Pending` state. Somehow the glitch took place only with OSM editor, no issues with other sites.

**Comment by Filosiq** [comment]
> @Filosiq I had the same issue and I resolved it by disabling `Experimental QUIC protocol` in Chrome (here - `chrome://flags/`) With the `Default` value my network requests were hanging with a `Pending` state. Somehow the glitch took place only with OSM editor, no issues with other sites.

I am using **Opera.** Is there any way I can do this on here?

**Comment by kuba743** [comment]
> @Filosiq I had the same issue and I resolved it by disabling `Experimental QUIC protocol` in Chrome (here - `chrome://flags/`) With the `Default` value my network requests were hanging with a `Pending` state. Somehow the glitch took place only with OSM editor, no issues with other sites.

**NOTE: I AM USING OPERA.** I have disabled this, but it did not help.

**Comment by olegykz** [comment]
@Filosiq what OS do you use? I think in my case the issue started after upgrading to `macOS Sequoia 15.1`

**Comment by kuba743** [comment]
> @Filosiq what OS do you use? I think in my case the issue started after upgrading to `macOS Sequoia 15.1`

Windows 11 23H2

**Comment by kuba743** [comment]
The issue has resolved for me. Thanks for helping me!

**Comment by olegykz** [comment]
@Filosiq what exactly helped? This might be useful for everyone else with the same trouble

**Comment by kuba743** [comment]
> @Filosiq what exactly helped? This might be useful for everyone else with the same trouble

I don't know, it just fixed itself.
