### ISSUE TITLE
Street level imagery: Viewer overlaps right click menu

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10495]
### How to reproduce the issue?

**Observed behaviour**
1. Enable street level imagery
2. Select an image to view
3. Create an object
4. Move the map manually so the object is above the street level imagery viewer [1]
5. Right click on the object
6. The right click / edit menu and associated hover tooltips are partially obscured by the street level imagery viewer

**Expected behaviour**
The right click / edit menu and tooltips are moved in front of the viewer.
Additionally the orientation of the menu could be changed to horizontal so it does not overlap the viewer.

Related #7368 

---

[1]; can be useful, as it is closer to the user's reading direction as well as being closer to the 'Tag this photo id on the currently selected map feature'.

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/9118a9d7-fee8-418b-a3c3-b58ecf8b7f44)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

### Which browsers are you seeing this problem on?

Chrome

**Comment by FrankOHara43** [comment]
hi, can you please specify how to open street level imagery? As a new contributor I am finding it difficult to find that option. Also, I am interested in working on this issue.

**Comment by 1ec5** [comment]
Hi @FrankOHara43, thanks for your interest. The screenshot above shows the Mapillary image overlay, which you can enable from the Photo Overlays section of the Map Data pane (accessible from the strip of buttons on the right side of the map). You’ll need to zoom into a location that has Mapillary imagery, such as https://ideditor.netlify.app/#map=20.43/39.28200/-84.28412&photo=mapillary/172552988091232.

If you haven’t used iD before, please go to https://ideditor.netlify.app/ (or go to https://www.openstreetmap.org/, create a free account, zoom in to your neighborhood, and click Edit), and follow the on-screen tutorial.

**Comment by danieldegroot2** [comment]
Ref #10504.

**Comment by tyrasd** [comment]
This can also happen with the info panels on the bottom right part of the screen. I guess the easiest solution would be to render the right click menu over all UI elements (as one would expect from regular OS context menus). https://github.com/openstreetmap/iD/pull/10504#issuecomment-2419906458 has some pointers for how to approach this issue should @FrankOHara43 not like to continue working on this.

**Comment by FrankOHara43** [comment]
i am interested to continue working on this.

**Comment by haresahani** [comment]
I’d like to work on this issue. Could you assign it to me?
