### ISSUE TITLE
When dragging the editing map with mouse, the osm elements become misplaced potentially due to photo overlays layer active

### ISSUE THREAD

**Issue by EwenH** [openstreetmap/iD#10506]
### URL

https://www.openstreetmap.org/edit#map=20/-38.2134512/145.1094302

### How to reproduce the issue?

1. Go to https://www.openstreetmap.org/edit#map=20/-38.2134512/145.1094302
2. Turn on Mapillary photo layer 
3. Select a polygon or line by clicking on it. 
4.  Left Click  and hold anywhere where there isn't an osm object and drag the map 30 metres or so,
5. The osm elements will not move but the base imagery will making them unaligned<<< Not always producible (~70% of the time) 
6. Click anywhere else on the map without an OSM object and the base imagery and all elements are realigned correctly. 
7. Turn off Mapillary image layer
8. Repeat from Item 3 to 5 and the editor works as expected.

### Screenshot(s) or anything else?

Aligned
![aligned](https://github.com/user-attachments/assets/16dad86c-aa5a-4188-939c-839599a8b712)
Misaligned after dragging
![misaligned](https://github.com/user-attachments/assets/30a07d96-f178-4ec2-892b-cfe6847e878d)

This has been happening since about the end of September 2024. I assume that this is photo layer related due to no other bug reports found and is on both Mac and Windows

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

### Which browsers are you seeing this problem on?

Chrome

**Comment by danieldegroot2** [comment]
It should work if you try the development version at https://ideditor.netlify.app/
This will be available on the openstreetmap.org website at a later time.

Duplicate of #10417.

**Comment by EwenH** [comment]
Thank you @danieldegroot2 - and can confirm that the dev branch rectifies this issue.
