### ISSUE TITLE
Tags sometimes get copied inadvertently from previously selected element onto next one

### ISSUE THREAD

**Issue by dankarran** [openstreetmap/iD#10514]
### How to reproduce the issue?

This bug doesn't happen all the time, but I've been seeing it on and off for quite some time (at least 9 months). These are the steps taken on the times I've noticed it happen:

1. click on a way
2. perhaps edit its tags(?)
3. click onto another way
4. click off to deselect

If the bug has occurred, the tags from the second selected way get replaced by the tags on the first way.

Examples:

Some example changesets (will add to the list if I rediscover them):

- https://www.openstreetmap.org/changeset/146633825 fixed by https://www.openstreetmap.org/changeset/158356254
- https://www.openstreetmap.org/changeset/153161857 address tags copied inadvertently from new node https://www.openstreetmap.org/node/12009773327 to nearby road https://www.openstreetmap.org/way/39187489/history/16

Workaround:

I believe that clicking off a way before clicking the next has helped prevent the bug occurring.

### What version numbers does this issue effect?

2.27.3, 2.29.0

### Which browsers are you seeing this problem on?

Safari

**Comment by danieldegroot2** [comment]
Duplicate of #9850

**Comment by dankarran** [comment]
Thanks @danieldegroot2 - I had a quick search but didn't see an existing issue. That sounds like exactly the same thing.
