### ISSUE TITLE
Additional row of map area could be gained by merging top area

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#10518]
### Description

Just the other day I realized that **one entire row of precious screen real estate** could be salvaged and reappropriated to the main map area!

All that needs to be done is compact the two lines via the red arrows, into one line! 

### Screenshots

![Screenshot 2024-10-27 18 05 01](https://github.com/user-attachments/assets/7f2dce21-329b-4ec2-95a3-b3a2c02b5bc2)

(Naturally I have snipped off a few _complications_ on the left and right ends to enhance my point. But you get the picture!)

**Comment by danieldegroot2** [comment]
Try pressing **`F11`** (fullscreen); it is possible in most browsers, though your setup may use a different key.

It is unlikely the osm.org header will be modified/removed.
The iD editor is contained within the osm.org website. The header is preferably reserved for osm.org UI only, to stay consistent with the rest of the website. This keeps maintenance needed for the combination to work low.

The v3 prototype moved towards / discussed this but noteably also new tools were added ( #6461, #6717, #7368 )
As for narrower screens, see also #7639.

Related #3250 .

**Comment by jidanni** [comment]
> Try F11

Actually I was already in fullscreen mode.

By the way the "Edit | v" shown could be also removed, as we are already editing... Also we are busy editing, not important to always offer GPX traces 24 hours a day while we are editing. But I suppose the future design will allow iD to leave the OSM.org "frame", and use the whole screen.

**Comment by tyrasd** [comment]
The UI is designed like this on purpose: the top has the OSM website interaction buttons, while everything inside the editing window is for iD. Anything else would be confusing. 

> Try pressing F11 (fullscreen);

I would also recommend this if you are working on a potentially small display. If you open the fullscreen mode from within the iD editor, the top OSM header should be hidden, btw.
