### ISSUE TITLE
Street level imagery: Right click on overlay selects also the image

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10517]
### How to reproduce the issue?

In Mapillary, Bing right clicking on the image link at the bottom or any of the overlay buttons (i.e. 'next image') returns only 'Open link ...' options. In Panoramax, KartaView it returns also 'Open image ...' options as if the underlying elements are being selected as well rather than just the link.
I personally expect only the 'open link' options, as I only intend to right click on the link itself.

Only happens on single images, not on 360 images.

This is only slightly inconsistent, it is not directly an issue for the user. (might be case of `wontfix-low-impact`)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

### Which browsers are you seeing this problem on?

Chrome

**Comment by Mradulg** [comment]
Can you share the screenshots of the issue?

I would like to pick it up @danieldegroot2

**Comment by danieldegroot2** [comment]
Example: most providers have images around https://www.openstreetmap.org/edit#map=20/52.6506551/-7.2517812

Panoramax single-direction image
![image](https://github.com/user-attachments/assets/31883bd2-d084-45c4-be2d-08679d159568)

KartaView single-direction image
![image](https://github.com/user-attachments/assets/51873612-f7b9-474c-9f1e-2d4ad3fd65f4)

Example of expected behaviour: Mapillary single-direction image
![image](https://github.com/user-attachments/assets/c76bb272-9e2e-41cb-a717-01aed36e84a8)

**Comment by tyrasd** [comment]
Mapillary uses its own mapillary-js library (apparently, mapillary does not like us to see the image URL :sweat_smile: ), which is why there is a small inconsistency here. I would say as this does not cause any issues, we can simply live with the small difference in right click behaviour.
