### ISSUE TITLE
Translations deleted in Transifex by API

### ISSUE THREAD

**Issue by matheusgomesms** [openstreetmap/iD#10529]
Several translations were deleted by API, according to Transifex. I went to add some translations and many were empty, which I knew I had translated before. Checking History, I could confirm it.

It was deleted by API at 9 Jul 2024, 19:27.

I don't know it this was overall or just in Community resource.

Did anything wrong happen? Is there some way to recover the deleted translations?

![Captura de Tela 2024-11-06 às 11 18 24](https://github.com/user-attachments/assets/8b59f4da-dd4f-4d9b-b895-969411ae7e9c)

**Comment by bhousel** [comment]
Oh it was actually me that deleted some of the translations from the community resource, we discussed it here:
https://github.com/osmlab/osm-community-index/issues/724

My script removed a bunch of translations that were redundant, but I realized later that some people would prefer to keep the redundant translations there.

**Comment by matheusgomesms** [comment]
Oh, thanks! I'll keep discussion there.
