### ISSUE TITLE
Add warnings for route continuity

### ISSUE THREAD

**Issue by StC-OSM** [openstreetmap/iD#10530]
### Description

Many of the QA issues that maintainers of bus/hiking/cycling routes are faced with come from modifications of ways with ID. Many of these are made by contributors who are not aware of what they are doing, or even not aware of what route relations are.

It would help considerably if ID would alert these users to the consequences of their changes, or even prevent them from uploading until there are no more new route continuity issues.

**Comment by tyrasd** [comment]
First of all, ideally no route relations should get broken by iD at all. Especially after iD version 2.29, the relation code should be much more robust (see #7653, #8415). So, if you are aware of situation where this still is happening, please let us know by opening a new issue.

Route continuity warnings could also potentially be a topic for a data validation message, but there it would be important to have a concise and actionable message text to display, and instructions for the user for how to fix the problems. Concrete suggestions in this directions are very welcome.

**Comment by StephaneChatty** [comment]
I may have expressed myself unclearly: I am not interested in how ID breaks relation. I am interested in how ID users break relations. If you need an example of that, open ID, find any way that belongs to any relation and delete this way.

This ticket is not about a bug in ID. It is about a new feature that would greatly help reduce QA workload and sub-standard quality in OSM routes.

**Comment by StC-OSM** [comment]
I may have expressed myself unclearly: I am not interested in how ID breaks relation. I am interested in how ID users break relations. If you need an example of that, open ID, find any way that belongs to any relation and delete this way.

This ticket is not about a bug in ID. It is about a new feature that would greatly help reduce QA workload and sub-standard quality in OSM routes.

**Comment by 1ec5** [comment]
iD doesn’t let you delete or disconnect a way that’s part of a route relation. You have to first remove it from the route relation. This is already more safety than other editors provide – a point of contention among some users, in fact: #9561.

**Comment by StC-OSM** [comment]
Still, I did it yesterday before writing the above lines, and got no warning.

I may have hit a bug in a safety check that needs to be tracked. But the issue I was raising is that there are some edits that you just can't prevent. For instance take a way in a route, add nodes at one of its ends, you have just broken the continuity of the route.

I am not asking for users to be prevented from editing. I am asking for them to be warned, at save time, when a route that was continuous before is not continuous anymore.

**Comment by 1ec5** [comment]
> Still, I did it yesterday before writing the above lines, and got no warning.
> 
> I may have hit a bug in a safety check that needs to be tracked.

Given [this forum discussion](https://community.openstreetmap.org/t/us-route-relations/122274/98), I wonder if the relation was actually a `type=superroute` relation, which iD doesn’t know anything about: #9942. iD only prevents you from deleting a member of certain relation types that are known to require contiguity:

https://github.com/openstreetmap/iD/blob/18de00a7bfd26155cb5fe25789c926a6aff27ec5/modules/operations/delete.js#L122-L124

> I am not asking for users to be prevented from editing. I am asking for them to be warned, at save time, when a route that was continuous before is not continuous anymore.

That’s fair, though [many routes are discontiguous in reality](https://community.openstreetmap.org/t/why-are-historical-railways-mapped/120413/7). The edit to make it discontiguous may well be correct. Presenting a warning might incite mappers to map incorrectly for the validator. #6101 would introduce a lower severity level that looks more like a reminder than a warning, mitigating this risk.

**Comment by StC-OSM** [comment]
> Given [this forum discussion](https://community.openstreetmap.org/t/us-route-relations/122274/98), I wonder if the relation was actually a `type=superroute` relation, which iD doesn’t know anything about: #9942. iD only prevents you from deleting a member of certain relation types that are known to require contiguity:

I am nearly 100%  that it was a plain route, that I had selected randomly from my favorite QA tool. Indeed I see now that this is not so easy to reproduce. I nearly regret not saving my change, now.

>>I am not asking for users to be prevented from editing. I am asking for them to be warned, at save time, when a route that was continuous before is not continuous anymore.

>That’s fair, though many routes are discontiguous in reality

My proposal is that the warning comes only when the route was continuous originally. Not sure it's easy, but it's worth spending time investigating.

**Comment by 1ec5** [comment]
> My proposal is that the warning comes only when the route was continuous originally. Not sure it's easy, but it's worth spending time investigating.

Yeah, I don’t think we have any existing rules that work like this. There is a filter by default that only warns if you’ve edited the feature, but that’s slightly different than what you’re suggesting. I have no idea if it’s feasible without reworking how the validator evaluates features.
