### ISSUE TITLE
KartaView: Only highlight sequence on hover

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10531]
### Description

Minor visual remark

For KartaView, only highlight sequence and cone in focus on hover, not also all individual image cones.
This is inconcistent with all other providers. This behaviour has existed for a long time.

### Screenshots

![image](https://github.com/user-attachments/assets/e77bfcd9-300a-4da3-aca7-81240928bace)

**Comment by draunger** [comment]
@danieldegroot2 i have done this issue as https://github.com/openstreetmap/iD/pull/10565
