### ISSUE TITLE
Panoramax: Caching images

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10533]
### Description

Just a quick question, since I personally know little about caching.
Do recently viewed Panoramax images remain cached?
At least on selecting the same image twice (you could also try going to a different image and back)
It seems Bing Streetside images remain cached, while Panoramax images are not
I tried checking for a cache header in the network tab in the web console, but could not find it, though I likely missed something. also, data (transfer) at the bottom keeps increasing for panoramax while for bing it does not (or perhaps panoramax needs to load some other data on every request which influences this number).

**Comment by tyrasd** [comment]
> Do recently viewed Panoramax images remain cached?

If they aren't it's something to be fixed at the Panoramax server side of things. iD itself doesn't do caching of images, as the browser can do that 
perfectly fine.

PS: I'll investigate this later today and forward it to the panoramax dev team if there's anything to do.

**Comment by tyrasd** [comment]
Ok, so it seems like the panoramax endpoint does not provide any `Cache-Control` HTTP header, which leaves the browser to decided wether and how long the images should be cached. Usually, browsers do however cache such assets for a certain time (see https://webmasters.stackexchange.com/a/111299). In my tests, the panoramax images are indeed cached in the browser. I'm not sure why in your case, the browser didn't cache it. Maybe you have some nonstandard configuration and/or browser extension which interferes with the default browser cache. Or maybe it was a problem related to a specific panoramax instance which is not the "default" openstreetmap.fr one: do you still remember the location where you experienced this issue?

I've opened https://gitlab.com/panoramax/server/api/-/issues/215 for the suggestion to explicitly return HTTP cache headers in Panoramax results.

PS: For future bug reports: it never hurts to give additional information in a bug report. For example, which browser you were using, a link to the specific instance of iD and location where one can immediately reproduce the problem, and any other potentially useful information. Thanks! :bow:

**Comment by danieldegroot2** [comment]
Sorry, was just curious about the missing caching header. There are no problems loading the images themselves.
