### ISSUE TITLE
Address field dropdowns should choose a name in the relevant language

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#10541]
As far as I know, most postal services and other addressing authorities use only one name at a time in each part of an address (street, city, etc.), even if OSM would give those features multiple values in `name=*` as a linguistic compromise.

For example, I recently had to [retag](https://www.openstreetmap.org/changeset/159141323) a bunch of POIs where a mapper had previously accepted iD’s suggestion of `addr:street=Bellaire Boulevard;Đại Lộ Sàigòn` based on [this nearby street](https://www.openstreetmap.org/way/1067465473), which is tagged `name=Bellaire Boulevard;Đại Lộ Sàigòn`. This street has two values in `name=*` because of [dual wayfinding signs](https://www.mapillary.com/app/?pKey=314599710013458). But neither the U.S. Postal Service nor the county records manager recognizes “Đại Lộ Sàigòn” as a street name for addressing purposes. Even if they did, they still wouldn’t recognize a dual name. (Do other countries’ postal systems work like this? Please correct me if I’m wrong.)

Ideally, iD would somehow know that it should use `name:en=Bellaire Boulevard` instead, because that’s the standard language for addressing in most of the U.S. We might be able to use data/territory_languages.json for this purpose, but it gets tricky in multilingual countries where the countrywide default language may not be a good fit. Since iD also consults Nominatim, maybe it can access the `default_language=*` from the surrounding boundaries, or it could base the decision on the interface language. (Not great, but this is a fallback.) Or maybe iD could simply use the `name=*` but truncate it at the first delimiter (a semicolon in this case).

https://github.com/openstreetmap/iD/blob/4ffc0bcd824b98ac69ca8ce4c9ab83ac2f309db9/modules/ui/fields/address.js#L58

**Comment by Deeptanshu-sankhwar** [comment]
Hello! Please take a look at this solution @1ec5 whenever you can. I have prioritized `name:en` values if it exists for a given nearby address, else I have resorted to `name` with the fallback to return the string before the delimiter `;` in case it exists. I have attached a screenshot below on how the nearby address dropdown looks now.

![Screenshot 2024-11-27 at 10 28 42 AM](https://github.com/user-attachments/assets/00b74f24-4dac-49e3-b23c-c81d8dcfb600)

**Comment by 1ec5** [comment]
Following up on some of my half-baked suggestions in https://github.com/openstreetmap/iD/issues/10541#issue-2659764981:

> Since iD also consults Nominatim, maybe it can access the `default_language=*` from the surrounding boundaries

Note that this file currently only consults country-coder, but country-coder has declined to include language-territory information: rapideditor/country-coder#131. So that’s why I suggested [Nominatim](https://github.com/osm-search/Nominatim/). Consulting Nominatim isn’t foolproof, but it’s more language-neutral than what’s currently in this PR.

The Nominatim API integration lives in modules/services/nominatim.js. There’s a [`countryCode`](https://github.com/openstreetmap/iD/blob/b5d45e3f28ccb9a39d243e7504415152e1ce8ec2/modules/services/nominatim.js#L30) method that grabs the country code out of [a Nominatim reverse geocoding result](https://nominatim.openstreetmap.org/reverse.php?lat=29.7030951&lon=-95.5681432&zoom=20&format=jsonv2&debug=1), but it isn’t quite what we’re after, since the `default_language` would be on [the containing country](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=148838&class=boundary) or perhaps a political subdivision of the country. Unfortunately, a standard reverse geocoding request doesn’t seem to include any metadata about those containing boundaries.

That’s as far as I got at a glance, but feel free to explore this approach some more and ask in [Nominatim’s discussion board](https://github.com/osm-search/Nominatim/discussions/) if you need more help.

> or it could base the decision on the interface language. (Not great, but this is a fallback.)

You’d call [`utilDisplayName`](https://github.com/openstreetmap/iD/blob/b5d45e3f28ccb9a39d243e7504415152e1ce8ec2/modules/util/util.js#L184) to get the same name that iD is currently showing as the label for the street on the map. The label already prefers the user’s language, irrespective of the language spoken locally. This is a lot simpler but can be inaccurate, for example, if an English speaker from the U.S. happens to edit in Japan.

One other potential approach I had forgotten was that the Multilingual Name field already fetches information about which countries speak which languages. You could make this field behave similarly.

https://github.com/openstreetmap/iD/blob/b5d45e3f28ccb9a39d243e7504415152e1ce8ec2/modules/ui/fields/localized.js#L36-L39

Unfortunately, it isn’t very granular. For example, the entry for the U.S. lists a lot of languages that the postal service does not speak, and you’d have no way of knowing that the preferred language in Québec is French, not English:

https://github.com/openstreetmap/iD/blob/b5d45e3f28ccb9a39d243e7504415152e1ce8ec2/data/territory_languages.json#L241 https://github.com/openstreetmap/iD/blob/b5d45e3f28ccb9a39d243e7504415152e1ce8ec2/data/territory_languages.json#L40

But in combination with the user’s preferred language as used by `utilDisplayName`, maybe it could work.

**Comment by tyrasd** [comment]
The question here is if the _linguistic compromise_ led to multiple languages to be included in the name tag, should it not also be the same for the address tag?! Because otherwise it could easily lead to edit wars when one of the two (or more) languages have to be chosen in the address tag. Also, having the same value in both the highway `name` and `addr:street` makes it easier for data consumers to ingest the data, and is as far as I know the current standard to map addresses.

> But neither the U.S. Postal Service nor the county records manager recognizes “Đại Lộ Sàigòn” as a street name for addressing purposes.

That said, this seems to be rather specific situation here. Usually, when roads have multilingual names (e.g. in Belgium or South Tyrol), the postal services accept all recognized languages also in the postal address. So, this would require to add a special exception for the US only?


PS: Slightly off topic, but semicolons should probably be avoided in (multilingual) names in general, see https://wiki.openstreetmap.org/wiki/Multilingual_names

**Comment by 1ec5** [comment]
> That said, this seems to be rather specific situation here. Usually, when roads have multilingual names (e.g. in Belgium or South Tyrol), the postal services accept all recognized languages also in the postal address. So, this would require to add a special exception for the US only?

Maybe. I guess this gets into whether the dropdown should be more helpful than merely looking at `name=*`. For example, a vast number of addresses in the U.S. are along roads that only have numbers, not names. There are [specific formats](https://pe.usps.com/text/pub28/28c2_018.htm) for those numbers in addresses, such as “State Route 123” for `ref=SR 123` on the way (or `network=US:XY` `ref=123` on the route relation). Encoding these formats as `name=*` is [controversial](https://community.openstreetmap.org/t/names-are-not-refs-vs-some-names-are-based-on-refs/109995), to say the least.

> Slightly off topic, but semicolons should probably be avoided in (multilingual) names in general, see https://wiki.openstreetmap.org/wiki/Multilingual_names

There’s [a _long_ discussion questioning that premise on the forum](https://community.openstreetmap.org/t/multiple-delimited-names-in-the-name-tag/6803)…

**Comment by 1ec5** [comment]
Anyways, this issue is not really about semicolons. It came up in the context of [this debate](https://community.openstreetmap.org/t/rfc-feature-proposal-add-languages-tags-for-name-rendering/121558/55) about hybrid street names in Canada. “Rue John Road” is not a street name that Canada Post would recognize in either French or English, and not a name that anyone would search for, regardless of the language they speak. iD would ideally suggest either `name:en=John Road` or `name:fr=Rue John`. Truncating at a semicolon was only a suggestion about how to solve part of that issue more easily.
