### ISSUE TITLE
Street level imagery: Limit maximum viewer size

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10558]
### How to reproduce the issue?

Limit the maximum viewer size to stay inside the interactable frame, at least in height.
While the resize button can still -barely- be interacted with at this size, the viewer itself gets cut off vertically.

Alternatively, the viewer could be visible through the top toolbar UI (as it is already transparent), but this is likely not desirable.

Chrome 131.0.6778.86 on Windows 10

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/5fc5068f-daa1-4d61-971d-5774b0f9d570)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.4, 2.31.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by draunger** [comment]
@danieldegroot2 i will do this issue

**Comment by draunger** [comment]
@danieldegroot2 i have make PR of this issue as https://github.com/openstreetmap/iD/pull/10563
