### ISSUE TITLE
Walkthrough: Add short reminder that data should be objective

### ISSUE THREAD

**Issue by Woazboat** [openstreetmap/iD#10566]
### Description

The iD walkthrough is the first point of contact with OSM for many new users who are not yet familiar with our customs and mapping practices. That includes business owners wanting to add their business to OSM, who might be tempted to embellish the information they are adding. Subjective descriptions, 'reviews' or SEO optimization fluff text have no place in OSM, but new users unfortunately might not be fully aware of that.

Adding a short sentence about the OSM subjectivity standards to the walkthrough could help to cut down on the amount of SEO spam descriptions that are added by new users.
(Obviously some people will unfortunately still choose to do it anyway, but ignorance about the topic would be less of a factor.)

A good spot for this reminder would be during the walkthrough section where users are guided to add a new cafe POI. A simple short sentence along the lines of _"All information should be objective and not a personal opinion."_ would be helpful.

### Screenshots

![image](https://github.com/user-attachments/assets/12e60ca6-5119-42c7-b777-0f58dc20ed13)
#

**Comment by Deeptanshu-sankhwar** [comment]
Hey @Woazboat , thanks for sharing the issue. Do you think this PR handles it gracefully?

**Comment by tyrasd** [comment]
In principle it's probably not a bad idea to make this explicit somewhere in the walkthrough. But the formulation "personal opinion" could probably be improved… :thinking: Maybe this can work: _All entered information should be objective and verifiable._ ?

**Comment by Deeptanshu-sankhwar** [comment]
That's actually very true @tyrasd , lemme make the edit in my PR. Thanks
