### ISSUE TITLE
Keyboard Shortcuts option becomes unclickable when the Quality Assurance tab is open in the Help section.

### ISSUE THREAD

**Issue by StillAbeginnerr** [openstreetmap/iD#10573]
### URL

https://ideditor.netlify.app/#background=Bing&disable_features=boundaries&map=2.00/0.0/0.0

### Description
When the "Quality Assurance" tab is open in the Help section, the "Keyboard Shortcuts" option becomes unclickable. This issue does not occur with other tabs in the Help section, where the "Keyboard Shortcuts" option remains accessible without any problems.

### Steps to Reproduce
Open the Help section.
Navigate to the "Quality Assurance" tab.
Attempt to click the "Keyboard Shortcuts" option.

### Expected Behavior
The "Keyboard Shortcuts" option should remain clickable and open the keyboard shortcuts panel regardless of the tab currently open in the Help section.

### Actual Behavior
The "Keyboard Shortcuts" option becomes unclickable when the "Quality Assurance" tab is active.

### Screenshot(s) or anything else?

Image 1 : For example, the Keyboard Shortcuts options is clickable in case of points tab.
<br>
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/2a98b414-7816-4d50-8169-3c2c0950e19d">

Image 2 : When the Quality Assurance tab is open in the Help section, the Keyboard Shortcuts option becomes unclickable. 
<br>
![WhatsApp Image 2024-12-03 at 11 03 13](https://github.com/user-attachments/assets/8aacaa74-b384-4dbf-87ce-f6c73c49bae0)

Image 3 :
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/892de634-5346-4776-9c76-c024c96ff499">

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### Which browsers are you seeing this problem on?

Chrome, Safari

**Comment by tyrasd** [comment]
I can confirm the problem. Hmm, what's peculiar that the menu appears to work fine when a different locale is selected (e.g. https://ideditor.netlify.app/#locale=it). :shrug:

**Comment by StillAbeginnerr** [comment]
Damn, interesting 🤔
