### ISSUE TITLE
User Role based Permission

### ISSUE THREAD

**Issue by Uranbold** [openstreetmap/iD#10574]
### Description

Hello,

I've got the question. Can we Define only Road fix for some users. Also define the Editor role should change the only Building etc?

How can we achieve this?

**Comment by tyrasd** [comment]
Hey. I'm not sure if I correctly understood your suggestion. Your idea is to introduce "user roles" in iD which would limit the data the respective users see and can edit. Is that correct? If yes, this is not quite inline with the core principles of iD (and OSM in general). There's some ideas floating around to streamline mapping tasks for mappers who are interested in mapping certain subsets of OSM data (e.g. by changing the emphasis of rendered map data or changing the suggested feature presets depending on the mapping context), but introducing user roles/permissions is not the right way to address this.
