### ISSUE TITLE
FR: Ability to import georeferenced tiff and xml files that are how QGIS exports them

### ISSUE THREAD

**Issue by micahchoo** [openstreetmap/iD#10572]
### Description

This would streamline the workflow between QGIS and iD editor, particularly useful for tracing historical features and ensuring spatial accuracy when working with historical maps.

**Comment by tyrasd** [comment]
GeoTiffs would in principle be a nice to have feature, but as it is a rather specialized usecase that is already possible in JOSM, this is low priority for iD.

> xml files

you could instead use QGIS to export a GeoJSON which is supported in iD.
