### ISSUE TITLE
ways or lines ?

### ISSUE THREAD

**Issue by richlv** [openstreetmap/iD#1123]
https://github.com/systemed/iD/blob/master/data/locales.js seems to be undecided whether to call linear features ways or lines.

demonstrating the lack of consistency :
a) draw a 2-segment _line_, select middle point;
b) mouse cursor over scissors - "split this into two _ways_";
c) split it, mouse cursor over "+" - "merge these _lines_"

personally, i'd love to see only one of these words stay, everywhere

**Comment by tmcw** [comment]
The one case of calling lines ways has been translated away:

![Uploading 2016-04-15 at 10.27 AM.png…]()
