### ISSUE TITLE
Use the upcoming imagery offset database

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/iD#1124]
Manually adjusting every layer is hard, non-obvoius and usually unneeded task which duplicates the efforts of previous mappers in an area. In a week or two I'm announcing the imagery offset server which allows users to determine an offset for each area once, and then just use the shared value.

See [the description](http://wiki.openstreetmap.org/wiki/Imagery_Offset_Database) and [API documentation](http://wiki.openstreetmap.org/wiki/Imagery_Offset_Database/API). There is also [a map](http://offsets.textual.ru/map) and [a list](http://offsets.textual.ru/all) (refreshes every hour).

Also I'd like you to check [the alpha-version of a JOSM plugin](https://www.dropbox.com/s/abqlwa57pkrck81/imagery_offset_db.jar) (it should be put into `~/.josm/plugins`). It shows that the user interface mostly consists of informational messages and a dialog for choosing an offset. The latter is the most important part: its design should give users enough information to correctly choose an offset and rid them of doing the same work twice.

I plan to release beta on Monday or Tuesday, and before that I'm open to any suggestions, even those which could reqiuire structural changes to the database and the plugin.

**Comment by planemad** [comment]
The offset db has been super useful during the recent realignment of over 50,000km of roads in Taiwan by the data team at Mapbox. Both Bing and Mapbox imagery has varying offset throughout the country and we now run the risk of the data being moved back to the incorrect location by new users who are unaware of the concepts of offsets

Even a warning message in areas with known imagery misalignments like the one in JOSM could be a huge help for beginners.

<img width="601" alt="screenshot 2016-10-17 23 33 52" src="https://cloud.githubusercontent.com/assets/126868/19449222/45f30064-94c2-11e6-82ad-4bb43494d7be.png">

It seems like a lot of southeast Asia is affected by this issue.

**Comment by Zverik** [comment]
Can I "up" this? It would be great to notify iD users that the imagery can be offset, especially outside US / Western Europe. Or at least have an option to download the nearest offset from the database — we can promote this option outside of iD, I guess.

**Comment by bhousel** [comment]
> Can I "up" this? It would be great to notify iD users that the imagery can be offset, especially outside US / Western Europe

Sure, I'll label it as <sub>[![priority][priority]][priority_link]</sub> since it does affect a lot of users.

[priority]: http://labl.es/svg?text=priority&bgcolor=0e8a16
[priority_link]: https://github.com/openstreetmap/iD/issues?q=is%3Aopen+is%3Aissue+label%3Apriority

**Comment by bhousel** [comment]
wip at #4166

**Comment by jidanni** [comment]
In
https://wiki.openstreetmap.org/wiki/Talk:Using_Imagery#Results_of_years_of_.22Adjust_imagery_offset.22_use I propose a solution based on having a grey framework of official high contrast edge locations, which they naturally will want to pull the imagery to align with, before editing.

**Comment by jgscherber** [comment]
Can the WIP label be removed from this? This issue is marked as priority and appears like it's being worked on with the label, but the pull request is from 2017

**Comment by bhousel** [comment]
> Can the WIP label be removed from this? This issue is marked as priority and appears like it's being worked on with the label, but the pull request is from 2017

Sure, I can remove it..

**Comment by rugk** [comment]
Is this implemented? If not it may be re-opened, does not it?

**Comment by controversial** [comment]
@bhousel should this be reopened?

**Comment by bhousel** [comment]
> @bhousel should this be reopened?

No
