### ISSUE TITLE
WMS support

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/iD#1141]
via http://www.microformats.dk/2013/03/22/se-et-preview-af-det-nye-id-openstreetmap-redigeringsv%C3%A6rkt%C3%B8j/ + http://www.microformats.dk/2013/03/14/sadan-kalder-du-geodatastyrelsens-wms-tjenester-fra-josm/

Question is really whether there will be many WMS providers that support EPSG:900913

**Comment by bhousel** [comment]
Let's support the easy WMSs via [whoots-js](https://github.com/mapbox/whoots-js). 

TODO:
- [ ] add whoots-js library to dependencies
- [ ] edit `update_imagery.js` to 
  - [ ] include WMSs that support EPSG:3857
  - [ ] with a tile url including a replacement token like `bbox={bbox-epsg-3857}` - [like how mapbox-gl-js does it](https://www.mapbox.com/mapbox-gl-js/example/wms/)
- [ ] add whoots-js call to `tile_source.js` to replace the token
- [ ] make sure these WMS sources that support EPSG:3857 are listed that way in `editor-layer-index`.  There is a [property for available projections](https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json#L122), but most WMS sources don't have it filled in.

**Comment by simonpoole** [comment]
@bhousel I suspect you are opening a can of worms. While I have now and then seen WMS servers supporting EPSG:3857, it is in my experience, the absolute exception (hey for once I agree with @tmcw). Which implies that you are not going to get around at least EPSG:4326 support.

**Comment by pnorman** [comment]
> TODO:

You might need to handle deduplication for sources which have both TMS and WMS

> While I have now and then seen WMS servers supporting EPSG:3857, it is in my experience, the absolute exception

There's about 15 or so in editor-layer-index which have 3857 or 900913 listed. The JOSM list has more, with about 20 900913 and 30 3857 (and duplication between them I'm sure).

As a ballpark guess I'd estimate 20 new sources, since some of those will have TMS equivalents.

**Comment by geowOSM** [comment]
> Which implies that you are not going to get around at least EPSG:4326 support (the request that kicked off reopening this issue, is BTW, exactly such a case).

Exactly, would be nice if ID will support EPSG:4326 in the short to medium term and best flag Bavaria DOP80.

**Comment by bhousel** [comment]
> Exactly, would be nice if ID will support EPSG:4326 in the short to medium term and best flag Bavaria DOP80.

I opened https://github.com/mapbox/whoots-js/issues/19 to track EPSG:4326 support.
Would appreciate help with it by anybody who knows 🌐 real well.

My best understanding of the issue is that we can request the images from the server, but they won't be square or they won't be the right part of a square tile that we can just plop into a tile grid.  But the tile grid is just `<img>`'s that the browser will scale for us, so implementing variable height tiles might not be too awful.

EPSG:3857 is easy though and can come quickly by ticking the boxes in my comment above.

**Comment by bhousel** [comment]
> You might need to handle deduplication for sources which have both TMS and WMS

Hmm, maybe we should change editor-layer-index schema so that each source can include all the various supported types, rather than duplicating them across files.

I opened https://github.com/osmlab/editor-layer-index/issues/179 for this.

**Comment by simon04** [comment]
Currently, there are 18 sources with EPSG:3857 or EPSG:900913 support specified in editor-layer-index:
```
$ ag -l 'EPSG:(3857|900913)'
world/Landsat.geojson
north-america/ca/GeobaseRoads.geojson
north-america/ca/GeobaseHydrography.geojson
north-america/ca/Canvec.geojson
europe/it/SouthTyrolOrthofoto2011WMS20cm.geojson
europe/hu/Torokbalint-ortophoto-2013.geojson
europe/fr/CRAIG-Auvergne20092010-30cm.geojson
europe/at/TirisDOM-Surfacemodel.geojson
europe/at/GrazBasiskarte-basemap.geojson
europe/at/TirisContourlines.geojson
europe/at/TirisDGM-Terrainmodel.geojson
europe/at/GeoimageatMaxRes.geojson
australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-StateForest.geojson
australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-Suburb.geojson
australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-LGA.geojson
australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-NPWSReserve.geojson
australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-Parish.geojson
australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-County.geojson
```

… and 3 sources made available through whotts:
```
$ ag -l whoots
north-america/us/nj/NJNatural2015.geojson
north-america/us/nj/NJInfrared2015.geojson
north-america/us/md/MD_SixInchImagery2014.geojson
```

**Comment by NKAmapper** [comment]
WMS support would be great. We have several WMS sources supporting EPSG:3857 which I could add from here: [/Maps/Norway](https://josm.openstreetmap.de/wiki/Maps/Norway)

**Comment by bhousel** [comment]
@tyrasd added support for the tile-compatible WMS sources in #4814  🎉

**Comment by tyrasd** [comment]
Should we open a follow-up ticket for "supporting" EPSG:4326 wms services as described above in https://github.com/openstreetmap/iD/issues/1141#issuecomment-15469807?

**Comment by bhousel** [comment]
> Should we open a follow-up ticket for "supporting" EPSG:4326 wms services as described above in #1141 (comment)?

Yes, please open one... 👍

**Comment by NKAmapper** [comment]
Now that WMS support is implemented, it would be great to have support for WMS in the custom background menu as well.

**Comment by NKAmapper** [comment]
#4977
