### ISSUE TITLE
iD can create ways with duplicate nodes

### ISSUE THREAD

**Issue by richlv** [openstreetmap/iD#1249]
several buildings have been create using id, where some nodes are used multiple times - for example, see :
http://www.openstreetmap.org/browse/way/215366570/history
http://www.openstreetmap.org/browse/way/215366567/history
http://www.openstreetmap.org/browse/way/215367487/history

(i'm leaving them unfixed as that might help to find out the cause)

would be nice finding out how this can happen, and maybe also have some internal validation ?

**Comment by grinapo** [comment]
Yes we do:
http://www.openstreetmap.org/browse/way/322455138
