### ISSUE TITLE
Expose some preset options in search

### ISSUE THREAD

**Issue by ansis** [openstreetmap/iD#1268]
Options for current preset, such as *alley*, *parking aisle*, *pizza (cusine)*, etc should be exposed thorugh the preset search.

They could be individual presets, but thats a lot of repetition. And it might be good if you could change the cuisine without search all presets. This needs some thought

**Comment by bhousel** [comment]
Closing - certain option-specific presets like *alley*, *parking aisle* presets have been in iD for a while.
