### ISSUE TITLE
Inspector View: Missing help/documentation

### ISSUE THREAD

**Issue by bussed** [openstreetmap/iD#1290]
I am on OSX, FF and language is german.

- Select a street with just "highway=residental"
- inspector view pops up

Clicking help/docu on Name, Oneway or Structure results in  "no documentation found."
Two things:
- If there is really no wiki page then there should be no help button.
- But in these cases there are wiki pages:
http://wiki.openstreetmap.org/wiki/DE:Key:name
http://wiki.openstreetmap.org/wiki/DE:Key:oneway

Structure is perhaps a special case. The help button should be on each line underneath (bridge, tunnel,..). 

Access, maxspeed and surface display correct docu and point to the correct wikipages.

**Comment by bhousel** [comment]
Closing, as this has improved since #2222 / 4261fef.  Simple field tag reference just depends on the wiki having documentation, and for complex fields we can now specify which tag documentation should be fetched.
