### ISSUE TITLE
Holding down an arrow key to pan starts to buffer drawVector

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/iD#1294]
Right now we're limiting drawVector, saying that we should only redraw every 300ms - which is fine for mouse input but tricky for panning. If you jam on an arrow key to pan far, the pan actions build up and the map moves in stutters. Maybe:

* We should have a non-queued redraw call?
* Queue the keybinding's pan calls to 400ms or so
* Pan by more?

**Comment by bhousel** [comment]
Panning was improved with #2691 
* default pan amount was increased from 5px to 10px and feels much nicer
* panning with modifier key (shift or cmd) pans by one screen
