### ISSUE TITLE
Another round of preset icons

### ISSUE THREAD

**Issue by samanpwbb** [openstreetmap/iD#1314]
Hey, I think it's time for me to do another pass on preset icons. @jfirebaugh @tmcw @ansis can you guys help add to this list of top priority icons to take care of?

I know there are a few issues in the Maki repo to track icons, but having an issue here to coordinate all this, and take advantage of GitHub's checkbox system, would make it easier for me.

### Lines

- [ ] weir
- [ ] highway=pedestrian
- [x] highway=living_street
- [ ] barrier (to use with a variety of barrier types
- [ ] leisure/slipway
- [ ] natural/cliff
- [ ] natural/coastline
- [ ] waterway/dam
- [ ] administrative boundary

### Points/Areas

- [ ] historical / archaeological site
- [x] city
- [x] town
- [x] village
- [ ] hamlet
- [ ] court
- [ ] playground 
- [x] farm
- [ ] doctor's office
- [ ] dentist's office
- [ ] lighthouse
- [ ] racecourse
- [ ] marina
- [ ] bench

### Vertices

- [ ] crossing
- [ ] level crossing
- [ ] traffic signals
- [ ] turning circle
- [ ] mini-roundabout
- [ ] motorway junction
- [ ] "other" specifically for vertices

### Categories

- [x] Land Use

edit: removed line:marina
edit #2: added cliff and coastline as distinct icons

**Comment by bhousel** [comment]
Closing as old, and nobody sees to be complaining about this.
