### ISSUE TITLE
Use shift+drag for zooming when zoom level is too low

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/iD#1413]
Since the only useful buttons in that mode are +/-, it'd be better to allow user to zoom to a small fragment of the map immediately, without waiting for all the features to load while they are zooming in.

**Comment by bhousel** [comment]
Closing this because 1. the minimap is draggable to move viewport quickly to a new location and 2. cmd/control key modifiers allow for faster zooming (with +/-) and panning (with arrow keys).
