### ISSUE TITLE
Support Internet Explorer 10

### ISSUE THREAD

**Issue by apmon** [openstreetmap/iD#1431]
It appears iD does not work correctly in IE 10 on Windows 8. When I try and load it, the general interface shows up and the background bing images load and can be dragged, but none of the data is shown. It appears to load the data, but then not display it. Furthermore, when trying to add a feature, nothing happens.

The IE javascript console shows the following errors:

SCRIPT438: Object doesn't support property or method 'extent' 
iD-ca0d96647da2ba2a04fc7661eaf85497.js, line 7 character 25448
SCRIPT5007: Unable to get property 'getElementsByTagName' of undefined or null reference 
iD-ca0d96647da2ba2a04fc7661eaf85497.js, line 7 character 9635
SCRIPT5007: Unable to get property 'getElementsByTagName' of undefined or null reference 
iD-ca0d96647da2ba2a04fc7661eaf85497.js, line 7 character 9635
SCRIPT5007: Unable to get property 'getElementsByTagName' of undefined or null reference 
iD-ca0d96647da2ba2a04fc7661eaf85497.js, line 7 character 9635
SCRIPT5007: Unable to get property 'getElementsByTagName' of undefined or null reference 
iD-ca0d96647da2ba2a04fc7661eaf85497.js, line 7 character 9635

**Comment by bhousel** [comment]
Bumping this issue.  I don't see these specific errors anymore in IE10, but I will post here what I do see.  It actually works mostly well.

**Comment by bhousel** [comment]
placeholder text overlaps magnifying glass in "Search":
![screenshot 2015-03-30 20 15 26](https://cloud.githubusercontent.com/assets/38784/6909902/9aecff4c-d719-11e4-8db9-d4c4d1d5c94a.png)

**Comment by bhousel** [comment]
Oneway markers don't transform properly.   They are correct when D3 enters the object, but don't update when panning/zooming:

![screenshot 2015-03-30 20 17 04](https://cloud.githubusercontent.com/assets/38784/6909924/ec015360-d719-11e4-94e5-dc41a92020a8.png)

**Comment by bhousel** [comment]
IE10 clear field button gets in the way of other UI.. 
[It can be removed](http://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs)

Also, we can probably trim down the scrollbars..

![screenshot 2015-03-30 21 27 56](https://cloud.githubusercontent.com/assets/38784/6910653/ee3481e8-d723-11e4-8d72-3ca1be2b3c10.png)

**Comment by bhousel** [comment]
IE treats custom cursors a little differently.  It expects them to be relative to the html document, not relative to the css:
```
192.168.1.9 - - [30/Mar/2015 21:46:44] code 404, message File not found
192.168.1.9 - - [30/Mar/2015 21:46:44] "GET /img/cursor-select-acting.png HTTP/1.1" 404 -
192.168.1.9 - - [30/Mar/2015 21:46:54] code 404, message File not found
192.168.1.9 - - [30/Mar/2015 21:46:54] "GET /img/cursor-select-acting.png HTTP/1.1" 404 -
192.168.1.9 - - [30/Mar/2015 21:46:59] code 404, message File not found
192.168.1.9 - - [30/Mar/2015 21:46:59] "GET /img/cursor-select-acting.png HTTP/1.1" 404 -
```

**Comment by bhousel** [comment]
Finally some event defects:

Can't place new points, lines, areas on an empty part of the map, (though you can create them on a hovered line or vertex).  

When moving vertexes, lines, midpoints, etc, - the move stops after one event so you can't drag things very far.


(That is really all the issues I could find.  Not too bad)

**Comment by bhousel** [comment]
From IRC, we've decided to just focus on IE11 and Edge.

Current OSM browser usage: IE8 = 1.2%, IE9 = 1.4%, IE10 = 1.4%, IE11 = 10.8%, Edge = 1.1%
Microsoft is dropping support for IE10 as of Jan 2016
