### ISSUE TITLE
Better rendering for tags with left/right semantics (e.g. coastline, cliff)

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#1475]
The following tags make ways "non-reversible":(aka the semantics depend on way direction) natural=cliff, natural=coastline,    barrier=retaining_wall and man_made=embankment. 

There is no "good" way of handling these outside of showing an "are you sure" alert or similar, this needs to be done for both explicit reversal and implicit (when merging ways).

Updated list of tags:

natural=cliff
natural=coastline
barrier=retaining_wall
barrier=kerb
barrier=guard_rail 
man_made=embankment. 
barrier=city_wall if two_sided != yes

some people believe that waterway=\* belongs in this list too

**Comment by slhh** [comment]
@bhousel Better rendering is useful, but it is not a full solution.
We should considerer the normal safe reversal, which is not changing any meaning of data, and the reversal, which is intentionally swapping left/right properties, as two different operations with different icons. A merge operation should only use the normal safe reversal and be unavailable otherwise. If required the user can swap left/right first and merge afterwards.
Both reversal operations can share the same place in the radial menu because they can't be available both.

**Comment by lakedistrictOSM** [comment]
Cliffs could be rendered like osm-carto does or with a thick line at top and a glow on the bottom. Would save me having to check the wiki each time!

**Comment by tordans** [comment]
Ideas for the rendering in iD:

I looked for an easy way to draw a css-border with triangles but apparently there is none. (Except for some (crazy?) [svg+border-image workarounds](https://codepen.io/yoksel/pen/GjgYgj).)

However iD has the ability to draw arrows over a line:

<img width="440" alt="bildschirmfoto 2018-09-29 um 17 18 56" src="https://user-images.githubusercontent.com/111561/46247493-6ea8ad80-c40c-11e8-8aea-74d6f6beb266.png"> (Left waterway=stream, Right selected highway=unclassified)

So, **there might be a way to use this, to draw arrows above (or next to) the line for this usecase?**

A very (very) rough scribble for natural=cliff and man_made=embankment:

<img width="440" alt="bildschirmfoto 2018-09-29 um 17 20 49" src="https://user-images.githubusercontent.com/111561/46248090-11652a00-c415-11e8-898a-fcf30e43382d.png">

The arrows are already direction-aware.

With this it should be possible to – more or less – recreate styles like [in this OSM-Wiki-Image](https://wiki.openstreetmap.org/wiki/File:Tagebau.jpg): 

<img width="166" alt="bildschirmfoto 2018-09-29 um 18 28 38" src="https://user-images.githubusercontent.com/111561/46248126-8a648180-c415-11e8-9242-ac3f45bc728c.png">

---

Something different: To further point out, that the way is direction aware, we could try to find a place for the **"switch direction" button** that is used for the "oneway=yes"-preset. However, I don't see a good place for that in tags like natural=cliff and man_made=embankment.

<img width="360" alt="bildschirmfoto 2018-09-29 um 18 23 47" src="https://user-images.githubusercontent.com/111561/46248149-db747580-c415-11e8-9317-a2da313b594b.png">

**Comment by tordans** [comment]
Thanks a lot for adding this @huonw!

Btw, it can be viewed on http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&map=19.05/52.47535/13.45292 already.

As a follow up: I wonder if the styling and behaviour of barrier=kerb should be tuned down a bit.

What I notice:
- The arrows are not visible on areas, only on just barrier=kerb-tags. So eg. having a landuse=residential + barrier=kerb does not show arrows. That is both good (looks better) and bad (we loose the direction info).
- Maybe the kerb arrows should only be visible for selected objects?
- Maybe the kerb design in iD should be tuned down (thinner line, softer gray, smaller arrows)?

An example of a not-ideal place (source link above):
<img width="640" alt="bildschirmfoto 2018-11-28 um 09 50 12" src="https://user-images.githubusercontent.com/111561/49140002-747b1c00-f2f3-11e8-8c0c-34de235ea62b.png">

What do you think, is this worth creating an issue to discuss and improve it further?

**Comment by huonw** [comment]
That does look rather overwhelmingly busy! It wouldn't be very hard to give the kerb tag a different style/size of arrows. For instance, `natural=coastline` is special cased, and adding more special cases should involve changing only two places, following the coastline example.
