### ISSUE TITLE
Show keyboard shortcut popup on `?` keypress

### ISSUE THREAD

**Issue by lhersah** [openstreetmap/iD#1481]
... I suspect not really (in the code the shortcut definitions seem to be spread of several files) and e.g. the [shortcut M is used twice](https://github.com/systemed/iD/issues/1482). 

The in-editor documentation is not really mentioning shortcuts and I could not find a list.

Would be useful for https://help.openstreetmap.org/questions/22379/list-of-keyboard-shortcuts-for-id-editor respectively the new wiki page.

**Comment by bhousel** [comment]
Idea here is to hit <kbd>?</kbd> key and see a popup window like how github.com does.

**Comment by ajithranka** [comment]
@bhousel Is this list of shortcuts up to date? http://wiki.openstreetmap.org/wiki/ID/Shortcuts

**Comment by bhousel** [comment]
@ajithranka, yes the list looks pretty good.. There are some situations where certain translations use different keys than the defaults, but we can worry about that later.

**Comment by bhousel** [comment]
this was done
