### ISSUE TITLE
Let users play with the data before asking to login or register

### ISSUE THREAD

**Issue by kachkaev** [openstreetmap/iD#1491]
Every new user being curious about OSM faces a serious barrier when clicking the ‘Edit’ button on osm.org – they have to register before moving things around on the map. I don't have any statistics at my disposal, but I'm sure we are losing quite a lot of newcomers because of this. It would be much nicer if the need to register or login would occur at the moment when a user is ready to submit the changes they’ve made.  

That’s how it happens in most of the online shops: you first choose what you put into your cart and only then enter your email and other details. Such reversing of the order significantly increases the conversion rates, because the users feel much more encouraged to overcome any barriers when they are close to the completion of their goals. If you force them to register before they realise that they need what you’ve got, it’s quite likely that they will simply not bother and just go away.

If a user is not logged in, iD can let them to explore the data and even edit it, showing a warning message on top of the screen about the need to login / register to save the contribution. This may show up after a few changes in the data, not disturbing people while they are completing the tutorial and doing very first attempts to add something. Ideally the authentication or registration could be also done internally, inside the iD’s interface, but I guess it’s not an easy task though.

Unfortunately, I’m not able to implement this feature, but I’m sure that it would have a clear positive impact on the OSM community. What do you think?

**Comment by bhousel** [comment]
Closing this, as the registration barrier to entry is more an issue with the rails port.

Users can still play around with iD on http://openstreetmap.us/iD/master or one of the other forks.
