### ISSUE TITLE
Allow multiline input field for note, fixme, etc.

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#1518]
For some keys it would be really nice to allow the values to span over more than one narrow line, e.g. note, fixme, description, opening_hours, wikipedia, ...

Right now you have to scroll the line to see the whole value, it would be better to get the whole content at a glance. I wouldn't reduce this to particular keys (like the above mentioned ones) but to all values (and potentially keys) that don't fit into the single line.

**Comment by maxerickson** [comment]
Are there further blockers for adding multi line support for the additional tags? The UI is in place for note. There is some interest from users:

https://help.openstreetmap.org/questions/47538/how-to-add-description-tag-with-id

**Comment by bhousel** [comment]
I don't think there are any blockers.  The issue is just old and we forgot about it.
