### ISSUE TITLE
support for other name tags

### ISSUE THREAD

**Issue by jfirebaugh** [openstreetmap/iD#1554]
Reuse the UI for multilingual names to add support for `alt_name`, `loc_name`, `old_name` etc.

http://wiki.openstreetmap.org/wiki/Name

Ideally the combo menu would have two optgroups, one with languages and one with "Alternate Name", "Local Name", "Old Name", etc.

**Comment by matkoniecz** [comment]
Not sure whatever such comments are useful here - but at least displaying alt_name would be useful and maybe would reduce problems of people adding multiple names in name tag.

**Comment by matkoniecz** [comment]
Also, showing old_name would be very helpful - currently iD mappers almost never keep old name in old_name tag on change of street name, what requires cleanuping their edits.

**Comment by 1ec5** [comment]
Per #5314, `int_name` would be useful especially in parts of the world where non-Latin writing systems are commonplace.

**Comment by Lukas458** [comment]
Is anybody interested in working on this issue? I ask myself at the moment why there aren't any developments here.

**Comment by matkoniecz** [comment]
> why there aren't any developments here

Because nobody worked on it so far. Are you interested in making pull request solving it at least partially?

**Comment by Lukas458** [comment]
I see, thanks. I#M not experienced in making pull requests and those things, but maybe I can learn about it...

**Comment by 1ec5** [comment]
This is waiting for review in openstreetmap/id-tagging-schema#215.

**Comment by 1ec5** [comment]
openstreetmap/id-tagging-schema#1288 implements most of the fields mentioned in the original post. openstreetmap/id-tagging-schema#1288 tracks `old_name=*`, which is not yet implemented. openstreetmap/id-tagging-schema#1289 tracks `int_name=*`, which was proposed in an issue duplicated to this issue.
