### ISSUE TITLE
Reproduce Potlatch2 external data merging tool

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/iD#1569]
Potlatch2 has an external data merging system which enables third-party data processed into an OSM format to be visually inspected and manually merged. It would be excellent if this were to be reproduced in iD.

This is shown at:
http://wiki.openstreetmap.org/wiki/England_Cycling_Data_project

and there is a short video at:
http://www.youtube.com/watch?v=A_sMxpWptCQ
which shows how it is used.

In outline:
- It contacts a server to obtain the data, which becomes the 'background layer', e.g.: http://gravitystorm.dev.openstreetmap.org/cnxc-snapshot/projects/1
- The user clicks on a line in the background layer, and then ctrl+click (or cmd+click on a Mac keyboard) the relevant OSM feature to see a side-by-side comparison of the tags
- An arrow appears to add/remove each feature when the user has inspected the comparison. If the user clicks the arrow, the tag is copied across from the left (background) to right (OSM), and this has the same effect as if the user had manually typed in that tag.
- When the user is happy that all has been reviewed, they click a button to mark it as complete.
- The user saves in the standard way when they've finished mapping.

In this way, users can manually merge in large quantities of detailed tags pretty quickly.

**Comment by mvl22** [comment]
> eventually an iD plugin

Is there an iD plugin architecture now?

Supposing we wanted to support the creation of a conflation system, for various types of data but presented as a second OSM API call, what is the best way that a conflation system could be added such that all the other benefits of iD are thus made use of? Would it be a case of maintaining a local fork?

**Comment by bhousel** [comment]
> Is there an iD plugin architecture now?

Unfortunately we don't have a plugin architecture, so for now a local fork does sound like the best option for you.

But iD now has a pretty good example of how to pull third party data down from a service and layer it on top of the OSM data - check out the Mapillary Imagery and Signs layers for how to accomplish this.

I plan to use this same approach to implement an OSM Notes layer at some point in the next few months.  It's not exactly conflation, but it is data coming from another endpoint that will need to show up on the map and have some interactivity built into it.
