### ISSUE TITLE
discourage excessive changesets

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/iD#1598]
I'm seeing users Save after every single edit. For example, http://www.openstreetmap.org/user/Rps333/edits?page=1

Two ideas
1) Keep changesets open for a time, even after uploading changes. I think potlatch2 used to do this. 
2) A help dialog to suggest to users that they can save less often.

**Comment by RicoElectrico** [comment]
Bump bump bump. I have people in Poland that click 'save' every single building. They clearly don't understand how it works. 
It's nuts. A user with 1200 edits not even a week old. Good luck at reverting this pile of crap:
https://www.openstreetmap.org/changeset/32310453#map=18/51.20153/19.49770

**Comment by bhousel** [comment]
#2251 is the issue for keeping a changeset open if the user is making a bunch of similar changes over a short period of time, and we agree it's worth implementing.

> It's nuts. A user with 1200 edits not even a week old. Good luck at reverting this pile of crap. Or using OSMHV to check someone's edits thoroughly, as it works on per-changeset basis.

Why would anyone need to revert all those edits?  Couldn't a power user with JOSM just select them all and remove the unnecessary name tags in a few seconds?  It's not vandalism.  Just send the user a nice message telling them thank you and they don't need to write "single family home" in the name field for each building.
