### ISSUE TITLE
Please don't discard the tiger:tlid or tiger:cfcc

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#1612]
discarded.json has:
[
    "tiger:upload_uuid",
    "tiger:tlid",
    "tiger:source",
    "tiger:separated",
]    

Fair game, except the tlid.  Having the original tiger line identifier may not be the be-all-and-end-all of conflation, but it is very nice confirmation.  The tlid is still useful, please don't destroy it.  If you want fewer tags how about deep sixing:
[
    "tiger:upload_uuid",
    "tiger:source",
    "tiger:separated",
    "tiger:reviewed",  <--- this especially!
    "tiger:county",
    tiger:name_base. tiger:name_base_1, tiger:name_base_2, 
    tiger:name_type, tiger:name_type_1, tiger:name_type_2,
    tiger:zip_left, tiger:zip_left_1, tiger:zip_right, tiger:zip_right_1,
]    

---

Please keep **tiger:cfcc** and  **tiger:tlid**
It is useful to know data came from tiger, and to have  hint of tracking down where it came from.  Same goes for  **gnis:feature_id**.  Even if some people have already deleted some tags.

**Comment by pilyfond** [comment]
@brycenesbitt I think we should finally change this and drop "tiger:reviewed" instead of "tiger:tlid".
