### ISSUE TITLE
Diagonal labels take too much space

### ISSUE THREAD

**Issue by mourner** [openstreetmap/iD#1645]
Copied from #1641 

> I also noticed that diagonal lines are covered by one big rectangle, and that means that a lot of labels that could be drawn aren't because of false positives. In Kothic JS, we cover diagonal lines by a set of small offset rectangles, and I think you should try the same. Because of bulk insertion, it shouldn't affect performance much.

**Comment by bhousel** [comment]
whoa, I had a hunch about the area labels being off, but iD's collision boxes are worse than I realized:

<img width="678" alt="screenshot 2016-04-17 00 29 07" src="https://cloud.githubusercontent.com/assets/38784/14585058/910d2c0c-0433-11e6-8ddc-a91a3ef1719e.png">

**Comment by mourner** [comment]
Wow. If you decide to tackle this, you can reuse some [rectangle covering code from GL JS](https://github.com/mapbox/mapbox-gl-js/blob/master/js/symbol/collision_feature.js).

**Comment by bhousel** [comment]
I did this today, looks pretty cool!

<img width="1028" alt="screen shot 2016-10-18 at 2 08 08 pm" src="https://cloud.githubusercontent.com/assets/38784/19490252/6fb00c6a-953c-11e6-84df-ca656076c17e.png">
