### ISSUE TITLE
admin_level input display value should be textual despite its storage being numerical

### ISSUE THREAD

**Issue by fgnievinski** [openstreetmap/iD#1664]
so that, e.g., user would select "national border" and iD would store 2, 4=states, 8=municipalities, etc.

that will open the door for supporting language-specific textual descriptions, e.g., 2=Límite Nacional, 4=Provincia, etc.

on a final level of refinement, country-specific descriptors could also be supported.  the defaults could be offered based on the coordinates being editted.

this would be a very rich editting feature that would attract a lot of local knowledge.

some work would be needed to provide this information; it's being discussed as part of the iD localization efforts.

see <http://wiki.openstreetmap.org/wiki/Key:admin_level#admin_level>

**Comment by bhousel** [comment]
> Hm, this may veer too close to making iD the axis of a political debate: unless there's real consensus about the meaning and labelling of these values, we should not abstract their values too much.

Closing.. It's been 3 years and OSM is still no closer to consensus here.
