### ISSUE TITLE
Validation: crossing ways, same layer, no common node

### ISSUE THREAD

**Issue by grinapo** [openstreetmap/iD#1669]
> crossing ways without common node at the same layer

Especially when both share common type, eg. both highways or waterways (most common).

via #1657

**Comment by danstowell** [comment]
Just to note that this can occasionally be not an error, although it usually is. If one of the ways is a bridge and the other isn't, then it's probably best not to flag it. (The user *could* mark them with layer tags but that's not compulsory)

**Comment by grinapo** [comment]
@danstowell It ''is'' compulsory; it is technically impossible that a bridge/tunnel crosses a road on the same level. Technically culvert can cross a road on level (it's a dent in the road, for example to direct rain water) but it's rather an exception than the norm.
