### ISSUE TITLE
Sometimes can't select existing features

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#1676]
Sometimes when I want to select an existing feature, it won't let me. Instead when I click it moves the feature a little bit.  It seems to do it for points, lines and areas. If I refresh my browser it will work for the first feature, then go back to just moving it and not selecting it.

I'm using Chrome on a PC.

**Comment by ro32xx** [comment]
Does anyone have a better Chrome fix and/or workaround to below? without suggesting another browser.

Main fix: logoff of OpenStreetMap, close ALL chrome browser windows, launch chrome again, re-logon to OpenStreetMap. Although sometimes i need to do this more than once to fix.

Workaround: hold SHIFT and select one or more objects, hit M then move the selection to new location, hit ENTER to confirm new location.
