### ISSUE TITLE
Proposed alternative to trash can in radial menu (make "delete" harder to hit).

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#1698]
This is a proposal to make deleting a feature harder with iD.  Or, put another way, to make delete prominent at the "right level" compared to expected editing patterns.  First the proposal:

1. Remove the *Trash Can* from the radial menu.  This means when clicking on a POI no radial menu will come up at all.  iD would become a bit more opinionated : encouraging the user to first scan the feature's associated tags.  Thus the feature removal trash can moves to the bottom of the "Edit feature" pane.

2. Remove the shortcut binding to *Backspace*.  Just because P2 and JOSM have this, does not make it right for iD.

3. Retain the *Trash Can* in the radial menu, but only for nodes that are part of a way.  The trash can removes only the node.  When you hover over a way node with tags, it would say "This node has (X) tags, and is part of a larger feature with (X) tags, and (Y) relations".  This will help keep people from deleting barrier=toll_both or highway=turnnig_circle, if all they really wanted to do was adjust the geometry of the way.  And help new users understand that every node can have tags, even if it is part of something larger.

----
In general this will allow the radial menu to control only geometry, rather than geometry plus existence. 

One downside is on features with a lot of tags, since you'll often need to scroll to find the trash can.  But I think this is good: if someone took the trouble to add that many tags, perhaps it is only courtesy to force the user to read the tags prior to deleting the entire thing ;-).

**Comment by bhousel** [comment]
I think this issue can finally be closed

**Comment by pmailkeey** [comment]
I'm in favour of keeping it as it is - there's always the 'undo' function for erroneous deletions.

Unfortunately, iD is difficult to use with complex objects and deleting and starting again is an easier solution despite some data loss.
