### ISSUE TITLE
Disable disconnecting that would damage relations

### ISSUE THREAD

**Issue by Janjko** [openstreetmap/iD#1714]
Disconnecting 'from' and 'to' members from the 'via' point or way in the same turn restriction should be prevented. Also, 'via' and 'via' from the same relation shouldn't be disconnected (there is not a lot of turn restrictions with more 'via' ways, but it's possible).

This issue is closely related to #1512

**Comment by jfirebaugh** [comment]
From duplicate:

> The "Disconnect" operation should be disabled for vertices that connect two member ways of a multipolygon. Disconnecting such ways produces an invalid multipolygon.

**Comment by SHARCRASH** [comment]
I work a lot with MP. This breaks the workflow! Instead of disallowing the disconnection, why hasn't there been inserted some sort of simple warning before saving?

**Comment by matkoniecz** [comment]
> This breaks horribly the workflow!

Splitting ways should still work, right? In the worst case, splitting way then removing it from relation?

(I know that comment is ancient, but this is linked from few places...)
