### ISSUE TITLE
Have save pane show a "change log" rather than a vertex count

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#1735]
I went and hit a few buttons at random and pressed SAVE in iD. It said something like:

```
  *48* Modified
  Vertex Other(46)
  area Day Use Parking
  vertex Other(2)
  *2* deleted
  point Point(2)
```

Why does a beginner editor use a mathematical term like "vertex"? How about saying what actions lead to those node changes? It could look a little like undo buffer comments sorted by object:

```
  area Day Use Parking 
      Made circular
      Deleted two nodes
  river Merced River
      Moved by 525 miles
      Added attribute 'opening_hours'
  supermarket Safeway deleted from map semi-permanently
  (Total of 2 lines moved, 1 attribute added, over a span of 4000 square miles)
```

(edited by tmcw / removing exclamations, narration beyond the necessity)

**Comment by bhousel** [comment]
Closing, the current behavior of the changeset summary is much friendlier now

<img width="335" alt="screenshot 2016-02-05 13 38 47" src="https://cloud.githubusercontent.com/assets/38784/12855512/e90b953c-cc0d-11e5-9b43-7ab41a7bbc1e.png">

**Comment by brycenesbitt** [comment]
Is better thanks. Sorting by object would be nice (summarize all changes to a given way/node/relation in one place).
