### ISSUE TITLE
Allow seeing contour lines and/or hillshades as background

### ISSUE THREAD

**Issue by berolinux** [openstreetmap/iD#1736]
It would be useful to see contour lines and/or hillshades (e.g. from OpenCycleMap and SRTM) when doing some edits (e.g. small mountain rivers flowing through woods -- hard to see on satellite images, but the location is usually clear when seeing details about the elevation).

**Comment by bhousel** [comment]
Closing as stale, and not directly an iD issue.  
Imagery sources with contour lines can be added to the [editor-imagery-index](https://github.com/osmlab/editor-imagery-index) project, if available.
