### ISSUE TITLE
Parameter order wrong?

### ISSUE THREAD

**Issue by lsces** [openstreetmap/iD#1750]
http://myhomecloud.co.uk/id/#map=17.00/-1.94142/52.08280 is my local working copy of id, but note that the lat and lon are the wrong way around! I'd copied from osm to get back in after scanning around which is http://www.openstreetmap.org/edit?editor=id#map=17/52.08280/-1.94142 and got a blank screen.

**Comment by pmailkeey** [comment]
The order is Lat Long in OSM and Google. It'd be nice to have it the same in iD !

**Comment by lsces** [comment]
pmailkeey ... this post was closed two years ago ;) The bottom line is that it's OSM which is wrong, probably because it followed google when it should have followed the rest of the geo infrastructure? It's one of those stupid mistakes we simply have to live with now and check which rule applies :(

**Comment by pmailkeey** [comment]
Actually, it's iD that's wrong - which is why I ask for it to be corrected. It's lat first then Long as that's what everyone else is using .... insignificant orgs like US navy, UK navy, Garmin, TomTom, random co-ordinate converters, http://www.findagrave.com/ etc. etc. all give lat first then long.

**Comment by tmcw** [comment]
Everyone's wrong and right: it's an opinion. Feel free to discuss for the next two years, though.

**Comment by pmailkeey** [comment]
It's an inconvenience when they're in the wrong order!

**Comment by tmcw** [comment]
I think the word you're looking for is "different", and [good luck making everyone agree](http://www.macwright.org/lonlat/).

**Comment by pmailkeey** [comment]
That's simple - if iD displayed them in both formats, everyone would be happy ;)
