### ISSUE TITLE
Draging the background off screen produces a click

### ISSUE THREAD

**Issue by Janjko** [openstreetmap/iD#1751]
Steps to reproduce:

* Select Line from menu
* Drag background
* Release when mouse over left pane

When I do this quickly, ID produces a click where I released the mouse (behind the left pane). It does this with Points and Areas too. If I release the mouse button over the background, or If I drag the background slowly, this doesn't happen.

Firefox 20.0, Ubuntu

**Comment by bhousel** [comment]
Believe this is closed already - dup of #2758
