### ISSUE TITLE
Remember selected imagery between sessions

### ISSUE THREAD

**Issue by pauliuszaleckas** [openstreetmap/iD#1756]
Each time I start editing I have to change background imagery.
It would be nice if iD remembered last selected imagery and set it automatically if it is available for area being edited.

**Comment by afmenez** [comment]
Part of this was recently implemented on  #2566, the last imagery is remembered between sessions.  Now only the auto-select is missing.

**Comment by bhousel** [comment]
Oh thanks!  I didn't even see this issue. I suppose we can auto-select the user's preferred imagery, first checking that:
* it is valid for where the user happens to be looking, and
* an imagery parameter has not been supplied in the url hash

**Comment by bhousel** [comment]
This was done in #4720   🎉
