### ISSUE TITLE
Import Multiple GPX Tracks

### ISSUE THREAD

**Issue by chuyler1** [openstreetmap/iD#1770]
Previous version of OpenStreetMap allowed me to import and display multiple GPX tracks on the map so I could use them all to determine the location of paths and trails.

**Comment by HughWarrington** [comment]
I don't think it is covered by either of those tickets. Those refer to large and or vague features which don't include the specific request from the first comment:

> import and display multiple GPX tracks on the map

**Comment by HaleTom** [comment]
@jfirebaugh I also looked at the two tickets you mentioned.

Maybe they are prerequisites, but they don't seem to cover the functionality requested here.

**Comment by chuyler** [comment]
It's been almost 10 years LOL, I'm still using Potlatch instead of iD.
