### ISSUE TITLE
Offer to upload the Local GPX File when saving

### ISSUE THREAD

**Issue by ericfischer** [openstreetmap/iD#1804]
If you've dragged a GPX file onto iD to use as a Local GPX File to trace, it would be nice if, when you hit Save, it had a checkbox that let you also upload the GPX file as a public or identifiable trace to the OSM GPS collection.

Sure, you can also upload it manually from the web site, but having it right there in the user interface might offer more encouragement.

**Comment by bhousel** [comment]
Closing as stale.  I don't think it improves the editing experience or OpenStreetMap enough to spend time on it.
