### ISSUE TITLE
Focus switches oddly when tabbing from All Tags

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#1881]
I had an existing node with name, note, phone, source and website. I added shop under all tags, hit tab, then focus was lost from the all tags area and the all tags section was collapsed.

**Comment by quincylvania** [comment]
A rather old issue, but I was still able to produce it with @tyrasd's steps… thanks!

> There is another glich which is closely related, I guess: Open a new edit session, add a POI with a regular preset, expand and close the "All tags" list. Add another POI, this time with the generic "Point" preset. Now the "All tags" section appears to be expanded, but the table is invisible:

Couldn't reproduce this, so I'm assuming it's been fixed by now 👍
