### ISSUE TITLE
Railway platforms under construction look like rail lines rather than platforms

### ISSUE THREAD

**Issue by smsm1** [openstreetmap/iD#1893]
A line tagged as railway=construction; construction=platform looks like a rail line rather than a platform, which is confusing.

e.g. this selected line in Peterborough Station http://www.openstreetmap.org/#map=19/52.57471/-0.25056 :
![openstreetmap-3](https://f.cloud.github.com/assets/82719/1329192/6e701e22-3512-11e3-95b6-fcc4ad650653.png)

**Comment by bhousel** [comment]
actually fixed in 7288806
