### ISSUE TITLE
way not redrawn when move of offscreen vertex is undone

### ISSUE THREAD

**Issue by jfirebaugh** [openstreetmap/iD#1905]
Move a vertex that's at the edge of the screen, then pan the map so that it's just barely offscreen. Undo. Even though the node isn't visible, the visible way geometry should still adjust to reflect the undo, but it doesn't.

**Comment by bhousel** [comment]
> Solve the bigger problem: undos should always produce visible effects. I checked in a few desktop apps and they seem to always pan/scroll to ensure that the effect of an undo/redo is visible. We could remember the map bounds at each change, and if an undo produces no difference within the current map bounds, jump to the old map bounds.

Old issue - this was done in #2204 / 6ca4b133047b64e1adb5df581cb4986f0fd2bbac
The view transform from when the edit was made is now stored in the undo/redo stack and iD will ease the user back to it.
