### ISSUE TITLE
How do I add a way to an existing, but not adjacent, relation?

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#1906]
See this help question:

https://help.openstreetmap.org/questions/27100/id-how-do-add-a-way-to-an-existing-but-not-adjacent-relation

There were no replies there, so I presume that the answer is "you can't, yet".

I was looking for information about iD because a new mapper has added new bits of a walking route in iD by naming them "blah trail" instead of adding to the existing "blah trail" relation. Whilst it may be easier to add to relations currently in Potlatch (or JOSM) I was wondering whether I could suggest something that didn't involve learning a different editor.

**Comment by HolgerJeromin** [comment]
We have a nice text input field in the relation section. 
It would be nice and easy if i could paste the full osm-url or only the number of the target relation here.

**Comment by bhousel** [comment]
moved to #3487
