### ISSUE TITLE
Improve handling of *=construction/construction=*

### ISSUE THREAD

**Issue by eliasp** [openstreetmap/iD#1922]
Currently it is very cumbersome to edit complex construction sites, as every item has to be edited manually from e.g.

    highway=primary

to

    highway=construction
    construction=primary

and the other way round once a construction site has been removed.

I'd like to see this improved by a function which just applies this changes to a node/way with a single click.

**Comment by bhousel** [comment]
#2341 will track development of a field for lifecycle tagging.
In the mean time, 7288806 at least sorts out the styling of construction=* and *=construction, as well as other similar-working tags.
