### ISSUE TITLE
Walkthrough - it's possible to think that you have got "stuck"

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#1963]
At the "line" part of the walkthrough I tried drawing a road north rather than south.  I'm now in the shaded area (I got there by scrolling with arrow keys) and clicking on the map or dragging has no effect (you can, however, click on "Lines" at the bottom again to restart this segment).

**Comment by bhousel** [comment]
I've made a bunch of changes recently that should improve this part of the walkthrough.

related:
afca7c5 - prevent most keyboard shortcuts
a2f3227 - prevent user from editing during pause when restarting the line drawing task
46ac91a - dont show an error when removing the wrong line that the user drew
