### ISSUE TITLE
Searchable online help

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#1971]
Currently there appears to be no searchable online help available for iD.  There is

https://wiki.openstreetmap.org/wiki/Id
https://github.com/systemed/iD/wiki

but neither of these are very relevant.  There's also the text of the "inline" help here:

https://github.com/systemed/iD/blob/master/dist/locales/en.json

but that's not really very easy to search - and even if you've found the text you're looking for, you don't see the context in which that piece of inline help would be displayed.

What's needed is some documentation that people can actually read, on a web page, and search, on the same web page.  For example, if I want to undo an action the information that the inline help provides "you can undo changes by clicking the undo button" is not helpful if I don't know what the "undo" button looks like (and it's not actually labelled as such).

**Comment by bhousel** [comment]
Closing, LearnOSM has built this: http://learnosm.org/en/beginner/id-editor/

**Comment by SomeoneElseOSM** [comment]
Unfortunately, 7 years later, there's still no searchable online help in iD.

There is a "help" button in the UI, which displays a message on the screen which looks like a clickable link titled "help".  However, right-clicking on that and opening in new tab does not work - I just get another copy of the editor window.
There is also no link to http://learnosm.org/en/beginner/id-editor/ (which was suggested above).
