### ISSUE TITLE
Odd behaviour: square-an-area moves connected way

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#1979]
I have a parking-space http://www.openstreetmap.org/browse/way/244586733
and a driveway leading to it http://www.openstreetmap.org/browse/way/246844101

When using "square corners" on the parking-space, 
the point where the driveway joins it moves to the lower left corner.

I tried to reproduce it, building a similar area+road elsewhere,
but there, squaring works as expected.  
But undoing this test, leaves me with 
an active undo-button (but "nothing to undo"), 
as well as "Save: 1" (but nothing to save).  

iD 1.3.2, Opera 17.0, WinXP

**Comment by bhousel** [comment]
I haven't thought about this issue in a while, but I think post-#3659 I will take a look at it and see where the nodes are going.
