### ISSUE TITLE
Selecting objects using a graphics tablet is difficult (requires zero movement)

### ISSUE THREAD

**Issue by danstowell** [openstreetmap/iD#1981]
Selecting objects in iD appears to require **exactly zero** movement of the cursor at the moment of clicking. This becomes evident when you try it with a graphics tablet plugged in, when it becomes very difficult to select anything!

This lack of tolerance for clicking is different to the behaviour of everything else within the web browser. For example I can click normal links (like the "History" link) in a fluid pass without ever stopping still.

> (My system, btw: Ubuntu 13.04, Firefox 25.0, Wacom Bamboo.)

I presume that you're not using the standard web browser's "onClick" behaviour, but some kind of internal "onMouseDown/onMouseUp" logic? If so, please could you add a small tolerance for slight movement during clicking?

(I'd like to remark that this is not just an issue of convenience, but of interface consistency and accessibility.)

**Comment by quincylvania** [comment]
A lot's changed in six and a half years!

We now have pointer events (#5505) and can thus treat stylus and mouse interaction differently. I don't have a graphics tablet but selecting nodes without dragging them using an Apple Pencil on iPad was near-impossible, as described. I added a higher pixel tolerance for styluses which solved the issue. Selecting ways and areas appears to be unproblematic, so whatever changed about that behavior in the long interim must have already fixed the issue.
