### ISSUE TITLE
Missing presets - Gas-stations

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#1987]
Missing presets for Gas-stations: 
fuel:diesel, fuel:e10  etc.

Maybe also car_wash, car_repair, car_parts,
as well as kiosk / shop=newsagent / shop=convenience / lottery=*
because many gas-stations around here offer a lot more than just gas.

**Comment by bhousel** [comment]
Works great with multiCombo:

<img width="356" alt="screenshot 2016-05-01 11 44 07" src="https://cloud.githubusercontent.com/assets/38784/14942670/324c2e24-0f92-11e6-9426-c98222badc33.png">
