### ISSUE TITLE
Radial menu gets in the way

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#1994]
e.g. when you want to select several points that are close to each other,
the radial menu is covering the next point you want to select.

This is a case where the UI makes it really hard to do a simple task.

It would be nice to have an alternative to fiddling around,
like clicking on different places so the menu is not in the way
for the next point you want.

E.g. an alternative menu (straight dropdown, to the left / right of cursor),
or simple switch off the radial menu, and use keyboard-shortcuts.

**Comment by tmcw** [comment]
I vote to close this issue. The radial menu has drawbacks but I don't see a viable alternative solidifying on this issue. At this point in iD's development a change to this interaction would be likely be disruptive to documentation and user habits in a way that outweighs the potential benefit.

Anyone else 👍 to close?

**Comment by bhousel** [comment]
sure we can close it
