### ISSUE TITLE
When creating new ways, let users undo creation of the most recent node using the Backspace key

### ISSUE THREAD

**Issue by WillPittenger** [openstreetmap/iD#2057]
Google Earth has something that I think would be handy in iD.  While you create the equivalent of a way in GE, you can press the Backspace key to delete the last node in the list.  There have been many, many many ways in iD that I created, but added on accident one or more nodes I didn't want or was in the wrong location.  iD makes me way until I complete the way to fix it.  Pressing the Backspace key to delete that node(s) would be handy.  Just be sure to make the Delete key a handy alternative for users with no handy Backspace key.

**Comment by bhousel** [comment]
Let's support undo for removing the last drawn node.. moved to #3530
