### ISSUE TITLE
Straighten should work on selected subpaths, not be limited to straightening entire ways

### ISSUE THREAD

**Issue by WillPittenger** [openstreetmap/iD#2058]
To often I want to straighten part of a way, but not the whole way.  Or I may want to align parts of a street represented by multiple ways.  The existing straighten tool works only on ways and will straighten the entire way.

So if there are three or more nodes selected, but no ways, add a tool to the context menu that would let me straighten those nodes regardless of which ways they are part of.  (After the straighten operation is complete, it may be appropriate to look for redundant nodes.)

**Comment by bhousel** [comment]
Done in #5740
