### ISSUE TITLE
Add the layer= tag to the editor presets

### ISSUE THREAD

**Issue by bborkmiller** [openstreetmap/iD#2087]
It would be handy to have a dedicated field for the layer= tag, rather than have it buried down in the "All tags" section. It would be _handiest_ if it the value of the layer tag showed up in the Structure box, since it's most likely to be used in conjunction with a bridge or tunnel.

**Comment by Codain** [comment]
I tag `man_made=bridge` a lot and it is tipically something missing.

It can be displayed as soon as one of those tags are set:

- `man_made=bridge`
- `bridge=*` (with a value different from 'no')
- `tunnel=*` (with a value different from 'no')
- `layer=*` (as already the case I assume)

Which also means that if I manually add one of those tags I would expect this field to be automatically shown.

**Comment by bhousel** [comment]
This was done in #3911
