### ISSUE TITLE
"edit" button active when not editing

### ISSUE THREAD

**Issue by malenki** [openstreetmap/iD#2108]
How to reproduce:
Go to some part of the map.
Edit using iD
Leave edit mode by clicking "Edit"
Result: edit button still active/hilighted
See a screenshot series:
http://malenki.ch/d/2014-01-27_185455_scr.png
http://malenki.ch/d/2014-01-27_185507_scr.png
http://malenki.ch/d/2014-01-27_185516_scr.png

**Comment by bhousel** [comment]
closing, as this is an issue with [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website).
