### ISSUE TITLE
Make it possible to download the osc file

### ISSUE THREAD

**Issue by wapolinar** [openstreetmap/iD#2154]
Since the iD editor is a great editor, but is not able to resolve conflicts, it would be nice, if it is possible to download the osc and then edit/resolve the conflicts using another editor.

This is at least the first step to introduce some kind of conflict resolution and will help users that did many changes and are then not able to upload them because of a conflict in the first change they did (here undo does not help, because it does not allow to undo "only" the first change (and yes that just happened to me)).

This issue is a feature request and was also suggested in #1053

**Comment by bhousel** [comment]
closing, as this will be implemented in #2489
