### ISSUE TITLE
Grid lines/Ruler needed

### ISSUE THREAD

**Issue by net127** [openstreetmap/iD#2186]
When analyzing satellite imagery for hotosm, it was very difficult to quickly analyze a large amount of low-contrast satellite images at a high zoom level without grid lines.

Please consider adding grid lines to prevent looking at some areas multiple times while (possibly) missing others.

Here is a MIT licensed javascript library that implements rulers and grid lines in javascript:
https://github.com/mark-rolich/RulersGuides.js

I am willing to work on integration if it is believed that this would be generally useful (and well-made patches accepted).

**Comment by gy-mate** [comment]
> This is highly task-specific, so I don't think it's suitable for iD core.

This wouldn't only help HOT users but also anyone that would like to, e.g. add a node at GPS coordinates that were measured beforehand.

@jfirebaugh If you agree with it, could you please reopen this issue? Many thanks in advance!

**Comment by gy-mate** [comment]
It could be implemented in a way similar to https://www.map.army.
