### ISSUE TITLE
Sharpen the Background aerial imagery

### ISSUE THREAD

**Issue by adivik2000** [openstreetmap/iD#2211]
I sharpen the imagery on potlatch when the imagery is a bit hazy or the locality is densely populated - helps a lot when adding streets. Is this left out on iD on a deliberate note?

**Comment by bhousel** [comment]
Would like to reopen this following discussions at SOTM-US with some HOT folks.  This would really be useful for tracing.

CSS filters offer a way do do this without needing to worry about CORS, and [support in modern browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#Browser_compatibility) is pretty good.

Live example here: http://stackoverflow.com/questions/29599794/how-to-sharpen-an-image-in-css

For example, the below rule bumps up the contrast and brightness slightly on all loaded tiles, and this does make a noticeable improvement in some places.
```
img.tile-loaded {
  opacity: 1;
  -webkit-filter: contrast(120%) brightness(120%);
}
```

We could make a very minimal UI for this in the background pane similar to the opacity switcher.
Thoughts?

**Comment by tmcw** [comment]
@mikelmaron Do you think this is a top priority for HOT, or a nice-to-have?

**Comment by bhousel** [comment]
This was just merged!  (It only took about 4 years, haha)

Now iD can adjust brightness, contrast, saturation, and sharpness (implemented as an unsharp mask) using sliders on the background pane. 

Please check out #4575 for more info, and try it out at http://preview.ideditor.com/master/

(I just realized that while it should work on _most_ browsers, I need to check all of them).

![imagery adjustment](https://user-images.githubusercontent.com/38784/33491848-76a62dda-d689-11e7-988c-3e48d216c8cb.gif)

**Comment by iandees** [comment]
Nice!

A feature suggestion: it would be neat if these settings could be passed in via URL params so that HOT managers could find good settings and send them to the browser directly.

**Comment by bhousel** [comment]
> A feature suggestion: it would be neat if these settings could be passed in via URL params so that HOT managers could find good settings and send them to the browser directly.

Yes, some things that would be great include:
- pass in settings via url hash
- let users save them somehow
- maybe stand up a service like the imagery offset database that will adjust imagery for the user automatically

Not sure what's next, but I'm planning to let users try it out a bit before deciding..
