### ISSUE TITLE
Problem joining ways together

### ISSUE THREAD

**Issue by howdystranger** [openstreetmap/iD#2214]
Hello!
I've noticed a problem in iD which I mainly encounter when I'm joining a driveway to a bigger road. Normally when you try connect two ways together the existing way glows red to let you know you're going to connect them. But when I attempt to connect the end of the new way to the existing road, I often have trouble selecting the existing way, such that I could end a way right on top of the existing one and they wouldn't be formally connected. Once the problem appears, it's very difficult to select the existing road - I often have to move my pointer up and down very slowly to find the exact right spot. It seems to be particularly a problem when I'm attempting to connect a vertical driveway to a horizontal road if that helps.

I'm using Firefox on Windows 7 and 8.1.

**Comment by jfirebaugh** [comment]
I believe this is the same Firefox bug as #2494.
