### ISSUE TITLE
Level field for features likely to be within buildings

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#2218]
Below the tag presets, there’s a button to set the selected feature’s elevation in the `ele` tag. Because new users tend to map POIs like shops, they are likely to think this field indicates what floor the POI is on. For example, [changeset 22192377](http://www.openstreetmap.org/changeset/22192377) set the elevation of a shop to “1” (1 m) in a city that sits at an elevation of 482 feet.

There should be a separate button for setting the `level` tag for POIs likely to be inside buildings. It might be too confusing to have it replace the elevation button, though.

**Comment by pavlo-dudka** [comment]
It seems that lot of users confuse elevation with level or height. Since it is used quite rarely, I would remove elevation as optional tag.

**Comment by bhousel** [comment]
@pavlo-dudka That does seem odd that a user would enter building levels in the `elevation` field, especially when we provide a visible `building:levels` field for buildings, and the `elevation` field is hidden.  Can you (or somebody who knows) check on the translations for these fields in this area (Ukraine?)

**Comment by pavlo-dudka** [comment]
@bhousel Some ukrainian people filled ele-tag with building height(height-tag), not with building levels. You are right, that was probably done because of incorrect translation of *elevation* to ukrainian.

Incorrect understanding of elevation also occured in USA. It was confused it with level(shop level above the ground floor). See initial post of @1ec5.
http://www.openstreetmap.org/node/2842085937/history

**Comment by 1ec5** [comment]
The user who incorrectly put the level in `ele` on that building was likely using iD in English. I think they probably were aware that the `building:levels` tag was for the total number of floors. Being a new mapper who was mainly there to add Bitcoin tags, they wouldn't've known about the ability to specify custom tags.

In the U.S. at least, the floor can be considered an informal part of the address, so that would be a good place for a `level` tag. But we'd have to account for regional differences about how to number the ground floor.

**Comment by bhousel** [comment]
I added this as a 'universal' field, so mappers can add this to any feature that happens to be indoors.
