### ISSUE TITLE
warning for unclosed multipolygons

### ISSUE THREAD

**Issue by maxerickson** [openstreetmap/iD#2223]
The validator should include multipolygons in the area checks. Or the multipolygon editor could have a check geometry button, downloading the missing pieces would be less disruptive there.

**Comment by Nakaner** [comment]
see also issue https://github.com/openstreetmap/iD/issues/1461

**Comment by Nakaner** [comment]
an example: https://www.openstreetmap.org/relation/4578550

This multipolygon has been created by an iD changeset but was not valid.

**Comment by bhousel** [comment]
> an example: https://www.openstreetmap.org/relation/4578550

What's wrong with that one?

**Comment by maxerickson** [comment]
Just to add some info, I filed this after assisting a user that posted on help.osm.org asking for help fixing a relation they had broken. Here's the relation I fixed:

http://www.openstreetmap.org/relation/1483563

And the post asking for help:

https://help.openstreetmap.org/questions/33068/reversing-a-changeset-after-i-broke-a-large-national-park-and-state-forest

I'm not sure, but I think https://github.com/openstreetmap/iD/pull/2526 would have prevented most of the problem. A checker would still be useful for users that notice they have saved a mistake.

**Comment by Nakaner** [comment]
https://www.openstreetmap.org/relation/4578550

The ring was not closed. [At this node](4578550) two independent nodes laid over each other. Both were end nodes of an outer way. If want to see this in JOSM, just revert changeset 28844787 manually. (I don't know if you can see this in Achavi)
