### ISSUE TITLE
Raster layers in Brazil

### ISSUE THREAD

**Issue by astoff** [openstreetmap/iD#2256]
Two extremely useful raster layers have been made available for use in Brazil: "IBGE Mapa de Setores Rurais" and "IBGE Mapa de Setores Urbanos".  They are listed in JOSM's imagery preferences, and the TMS addresses can be found there.

These options should appear in the background settings panel when editing in Brazil, just like the USGS topographic map appears there when editing in the USA.

**Comment by vgeorge** [comment]
We've added the IBGE layers to the index, but they still don't show in iD:

https://github.com/osmlab/editor-imagery-index/blob/gh-pages/imagery.geojson

These layers should be appearing for edits anywhere in Brazil. 

How iD uses the imagery index? I thought they would appear at the optional layer list when I type `B`.

**Comment by vgeorge** [comment]
cc @jfirebaugh @pnorman

**Comment by bhousel** [comment]
Hi @vgeorge, if the layers were accepted into the editor-imagery-index, they will be in the next release of iD.  

The code is stable enough that I could probably make a release in the next few days.  Lots of people are at SOTM-US this past weekend, so they may be a bit slow to respond.

**Comment by naoliv** [comment]
@bhousel it would be really good if iD could be updated to include the new imagery index.

**Comment by bhousel** [comment]
Thanks everyone for your patience, looks like iD 1.7.3 is live now on the main openstreetmap.org site and it includes the new imagery sources for urban and rural Brazil.

**Comment by naoliv** [comment]
Thank you!
