### ISSUE TITLE
better handling of multipolygon inner members

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#2259]
iD sometimes is a little counter-intuitive when working with (closed) inner ways of multipolygons. I'd suggest the following changes to make it a better experience:
- [ ] suggest area presets for closed inner members
- [ ] use area operations for closed inner members (i.e. drop the reverse operation for these)
- [ ] drop the `area=yes` tag of a way when it is added as an inner member to a multipolygon using the merge tool. 

Would this make sense?

**Comment by bhousel** [comment]
Closing.. I'm not sure we can do this - the closed inner ways of multipolygon relations could be holes, but the could also consist of traditional OSM ways (highways or paths or whatever) and so we can't always treat them like holes.  While we could probably write some clever logic to answer the question of "is it (entirely) a hole, or does it have some way-like parts to it", I don't think the effort involved justifies the work.
