### ISSUE TITLE
Handle 509 Bandwidth Limit Exceeded

### ISSUE THREAD

**Issue by mikemorris** [openstreetmap/iD#2262]
When many people are editing OpenStreetMap from the same IP address, this error occurs frequently, but is not reported by iD. OSM API requests appear to just hang, when in fact the request has errored out.

**Comment by bhousel** [comment]
There is some good news here from @zerebubuth!
https://lists.openstreetmap.org/pipermail/dev/2016-October/029544.html
https://github.com/openstreetmap/operations/issues/36

[cgimap 0.5.5](https://github.com/zerebubuth/openstreetmap-cgimap/releases/tag/v0.5.5) will rate limit oauth-signed requests by user not by IP.  This means we can:
- [ ] oauth sign all API calls if the user is already logged in
- [ ] prompt the user to login if we receive a 509 response 

Note that on openstreetmap.org, users are required to log in before editing with iD.  So the vast majority of cases will be solved by ticking the first box above.  

The second box above would only apply when iD is running on a site like Strava, which delays authentication until the user tries to save something.

**Comment by bhousel** [comment]
#3519 ticks the first box

**Comment by Rahulrokkz666** [comment]
You can handle 509 Bandwidth limit exceeded error by following below methods:

1. Use CDN Caching
2. Disable Hotlinking
3. Remove Junk Files
4. Optimize WordPress Files
5. Contact your web hosting provider
For in complete step by step method, you can refer to WPOven's comprehensive post on " [How to Fix the “509 Bandwidth Limit Exceeded” Error?](https://www.wpoven.com/blog/509-bandwidth-limit-exceeded) ".
