### ISSUE TITLE
Localization of name suggestion in iD

### ISSUE THREAD

**Issue by hlaw** [openstreetmap/iD#2267]
On top of my earlier PR #2258 which tracks country code information in `iD.context`, and based on a revised version of name suggestion index (https://github.com/osmlab/name-suggestion-index/issues/11), I have worked on a branch of iD which does localized name suggestions, by reloading country specific suggestion index / presets whenever the user moves to another country.

A live demo is at http://codegrid-osmhk.rhcloud.com/iD.html. The demo covers name suggestion in Asia only (as I only have the asia osm extract to generate the index).

The iD branch is here - https://github.com/hlaw/iD/compare/code-suggest.  (Since the suggestion data is not complete I have not made this into a PR). 

Some other changes have been made:
- The test for using imperial units for maxspeed, previously based on multipolygon test, is changed to use the context country code (test if country = us or gb).  The polygon is no longer necessary.
- Name suggestion under the `name` field is changed such that it would work beginning from 1 character if the user input consists of CJK ideographs. (Currently name suggestion for the field is for 3 or above input characters regardless of language).  Given the higher infomation content per character, meaningful suggestions are available with fewer input characters.
## Some screenshots-

Partitioning the name suggestion index by country allows lowering the count threshold for inclusion (from 50 to 5).   Much more local suggestions which are relevant would be available to local users.
- Typing a common kanju character for preset search (in Japan) currently returns no suggestions.
  ![screenshot from 2014-06-22 00 17 13](https://cloud.githubusercontent.com/assets/4372879/3349596/69ac3a4e-f96e-11e3-8f3e-5c48a638a6e9.png)
- Typing the same character in the new branch returns local brands -
  ![screenshot from 2014-06-22 00 16 41](https://cloud.githubusercontent.com/assets/4372879/3349599/69b5f9da-f96e-11e3-918e-5d77ae8087c4.png)
---

In English:
- Typing "bank" in Japan presently return some banks from overseas
  ![screenshot from 2014-06-22 00 28 30](https://cloud.githubusercontent.com/assets/4372879/3349595/69aa3744-f96e-11e3-842b-0f952f554b57.png)
- Doing the same in the new branch would return banks in Japan with the word "bank" in English translations
  ![screenshot from 2014-06-22 00 29 04](https://cloud.githubusercontent.com/assets/4372879/3349597/69af932e-f96e-11e3-9e4b-8f05bb57b8b9.png)
- Doing the same in China, a different set of local banks returned. (Some clean up is needed to sort out duplicate data)
  ![screenshot from 2014-06-22 01 21 18](https://cloud.githubusercontent.com/assets/4372879/3349594/69a4d362-f96e-11e3-868b-48b77149a7dd.png)

**Comment by bhousel** [comment]
closing as stale
