### ISSUE TITLE
Display "last edited by" for objects in iD

### ISSUE THREAD

**Issue by Mashin6** [openstreetmap/iD#2273]
I think it would help to make editing in iD better to have a way how to browse through history of the objects. Now the only way is to follow the link to View on osm.org and then select history, which is not always easy to understand.

I would imagine that upon choosing history for selected object, iD would show list of previous versions in the left panel. Each version item would expand on click to reveal tags from given time in the past.

Maybe too ambitious would be to change the shape of the object in real time to reflect how it looked in given version.

**Comment by bhousel** [comment]
I don't want to add a full history browser, but there are some situations where seeing "last edited by" for a selected feature would be useful.  We can sneak this into the "secret" `Ctrl-I` infobox.

**Comment by slhh** [comment]
@bhousel "Last edited by" seems to be useless information without knowing what has been changed. A deteted or added node? A tag change? It doesn't help to find out if a specific user has changed the object because someone else might have added/deleted a node later. Which usecase do you have?

The original request is useful. The community would benefit from encouraging users to view the history, at least in regions with an active community.

**Comment by bhousel** [comment]
> Which usecase do you have?

If a feature doesn't appear on aerial imagery, and it was "last edited by" bot-mode 4 years ago, it's probably garbage.  If it was "last edited by" some actual user 4 months ago, it's probably a real feature that is just newer than the imagery.  There are a handful of active users around where I live, so if I recognize that it's something added by one of them, I know it's fine.

> The community would benefit from encouraging users to view the history, at least in regions with an active community.

Yes, so we can put a link to the history viewer on openstreetmap.org for people that want to see the full history.

**Comment by bhousel** [comment]
Sneak preview:

![history](https://user-images.githubusercontent.com/38784/27759878-c27b7e1c-5e08-11e7-8510-6623c977d081.gif)
