### ISSUE TITLE
Draw a rectangle in two clicks

### ISSUE THREAD

**Issue by dmromanov** [openstreetmap/iD#2277]
A large number of areas (building) has rectangel form. It would be nice to have an ability to draw rectangles (areas with right angles) in two clicks.

A current way to draw rectangles is quite difficult: draw an area, transform it to a rectangle with a hotkey or a context menu. Move / rotate the rectangle to make it aligned as it is supposed to be.

Example usage:
1. Hold "Shift" key;
2. Draw a diagonal line with an "area tool" (point two corners);
3. The diagonal is expanded to a rectangular area.

**Comment by jidanni** [comment]
Yeah, I was just going to say:
Got an idea for a quick building addition mode:
Two clicks to define a rectangular building!
(OK, maybe a third click in the same spot to mean "I'm finished".)
That way, say in rural area with lots of rectangular barns,
or communities with lots of rectangular homes,
one could make a lot of buildings in a jiffy!
