### ISSUE TITLE
Make an exception to space removal after ; for opening_hours

### ISSUE THREAD

**Issue by afita** [openstreetmap/iD#2301]
I noticed that the current iD editor on openstreetmap.org is removing the space characters after semicolons(;) from tag values. Spaces should not be removed, having space chars is essential for opening_hours http://wiki.openstreetmap.org/wiki/Opening_hours. Tools like http://osm24.eu stopped parsing the opening_hours tag correctly for opening_hours inserted in the last few days.

**Comment by jfirebaugh** [comment]
Reopening per @rjw62's request.
