### ISSUE TITLE
Add logic for feature snapping

### ISSUE THREAD

**Issue by valleyofdawn** [openstreetmap/iD#2302]
Thanks for this wonderful editor!

A bugging feature:
It is often the case that roads overlap with other lines (e.g. field or forest edges). 
Id snaps roads to such lines as well.
Attaching a highway to such such overlapping lines requires several attempts to get it right, and if it goes unnoticed results in discontinuous road grid.
It would be better to prioritize snapping to the nearest road if two lines are within snapping distance.

**Comment by bhousel** [comment]
Closing as stale.  Let's push the idea of "things that shouldn't be joined to things" into the domain of QA tools like KeepRight, etc.
