### ISSUE TITLE
history not cleared after save to OSM

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#2304]
At least on opera 12 (and chrome?) on linux i have the problem that with every start of iD on the main osm page it will tell me that there are unsaved edits in the browser cache.
I tried a little bit of debugging and found that
history.toJSON()
is called after every change of a tag or so. But it was NOT called after saving to osm. 
Thats why the function history.restorableChanges is happy to report about a (outdated) history on load.

**Comment by bhousel** [comment]
Closing this issue.. If someone else wants to do the work to get the old version of Opera and fix the history clearing issue, we'll accept a pull request.  But it just doesn't seem to be something that will be affecting anybody going forward.
