### ISSUE TITLE
Tabbing through address tags on node does not switch focus properly when inputting text

### ISSUE THREAD

**Issue by landonreed** [openstreetmap/iD#2320]
Using Chrome 35 for OS X, I've noticed that when adding address information for a node that tabbing does not switch focus sequentially, i.e. it does not switch from addr:number to addr:street after typing the address number.

This only occurs after inputting text into the fields.

**Comment by cweiske** [comment]
This also happens on Firefox 38 on Linux.

**Comment by bhousel** [comment]
This is fixed in 23b22fd
