### ISSUE TITLE
automatically removing the LRM character

### ISSUE THREAD

**Issue by jgpacker** [openstreetmap/iD#2323]
If possible, the iD editor should automatically remove the LRM character [[1]]. (an *invisible* unicode character used in some languages)

This character can be accidentally introduced by editors that copy and paste information from other sources. Fortunately it seems this character only appears in the end (and maybe at the beginning) of an URL.

Usually this character is no big deal, but it can be nasty in tags like `website=*`, `contact:website=*` and similar ones, because it can *corrupt* their address.
Examples of such tags can be seen in [[2]].
Note that recently I removed this character from URLs across the globe (around 1200), and yet it is growing again (around 60 right now).

[1]: https://en.wikipedia.org/wiki/Left-to-right_mark
[2]: http://overpass-turbo.eu/s/3eJm

**Comment by bhousel** [comment]
I implemented these simple cleanups today because I was in this code anyway for #2301.

This code does not do complete validation of emails and websites, it only strips out troublesome characters likely caused by users pasting in bad data.
