### ISSUE TITLE
Make help more obvious

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/iD#2364]
Er, so one of the mistakes made by the usability study is:

![image](https://cloud.githubusercontent.com/assets/32314/4406229/7ad15a40-44c1-11e4-849c-a97e1d009f79.png)

and

![2014-09-25 at 10 38 am](https://cloud.githubusercontent.com/assets/32314/4406258/9581e63e-44c1-11e4-9c8f-dfbb93d4295d.png)

Basically, it looks like the researchers didn't actually use iD enough to know that it has great built-in help, and thus guided their users toward non-core resources that we haven't focused on. Besides being a major flaw in the research method, this might illuminate some potential for improvement - do we point to the built-in manual in the walkthrough?

**Comment by bhousel** [comment]
I changed the wording a bit, embed the button icon, and let the curtain linger over it for a few more seconds.


<img width="284" alt="screenshot 2015-12-17 15 14 53" src="https://cloud.githubusercontent.com/assets/38784/11880873/4983236c-a4d1-11e5-9504-c9c0a11b0e8a.png">
