### ISSUE TITLE
Relation presets for common road route networks

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#2369]
The Road Route relation preset needs a Network field corresponding to the `network` tag. Currently it has only two fields: Name and Reference. But [road route relations](http://wiki.openstreetmap.org/wiki/Relation:route#Road_routes) also need to specify a network to distinguish between same-numbered routes in different highway networks.

Unfortunately, `network` is a [very overloaded tag](http://wiki.openstreetmap.org/wiki/Key:network), and taginfo’s API doesn’t seem to offer a good way to suggest just road networks. [This query](https://taginfo.openstreetmap.org/api/4/key/values?key=network&page=1&rp=25&sortname=count_relations&sortorder=desc&relations) for example gives the most popular `network` values on relations, but the suggestions are led by cycle and walking networks.

Ideally there would be presets for all the common road networks, just as there are for common fast food restaurants. You’d simply search for “interstate” and get a preset that comes with `network=US:I`. You might search for “state” and get a preset for U.S. state routes with a State combo box. That way you wouldn’t have to remember the `network` tag’s format at all.

**Comment by 1ec5** [comment]
#2372 added a simple `network` field to road route relation presets. #3280, #3298, #3299, #3301, and #3302 all improve the experience of using this field.

**Comment by 1ec5** [comment]
Currently working on individual route presets on my [network-presets-2369](https://github.com/1ec5/iD/tree/network-presets-2369) branch. So far I’ve added nationwide and statewide networks in the U.S., including secondary systems such as Texas Farm to Market roads and Missouri supplemental roads. Before posting a PR, I’d like to add presets for more countries’ networks – perhaps any road network with more than a hundred elements in [this taginfo table](http://taginfo.openstreetmap.org/keys/network#values), plus any other notable networks from the same country.

Supporting county or township routes or bannered routes would require invasive changes to how presets are matched. (I was always a fan of using the `modifier` tag instead of appending the modifier onto the `network`, but that ship sailed long ago.) To avoid putting an extreme burden on localizers, there should only be for instance one preset for all U.S. county roads that features state and county dropdowns.

**Comment by bhousel** [comment]
It would be really cool to introduce the idea of "preset packs" and put these route relations into one.  Currently we have the base presets, and the name suggestion presets, and we just smash those together into one big preset dataset, but it would be cool to have a bit more modularity.  I could easily see there being hundreds of route presets and it would make sense for them to live in their own repo that can be pulled in to iD when it starts.

This is just bluesky thinking, not necessarily a blocker to shipping what you are working on.

**Comment by 1ec5** [comment]
> It would be really cool to introduce the idea of "preset packs" and put these route relations into one.

There is the concept of a preset pack now and it’s the name suggestion index! osmlab/name-suggestion-index#4768 tracks introducing road route networks as a category.

**Comment by bhousel** [comment]
Haha wow!  Yeah I guess we did this huh? 😆 
We can do road routes too, I just need to find the time to make it happen.
