### ISSUE TITLE
Key and value tagging autocomplete woes

### ISSUE THREAD

**Issue by skylerbunny** [openstreetmap/iD#2376]
Autocompletion in iD has a tendency at times to create tags and values a user probably didn't intend. Here's how to reproduce the issue:

1. Select a way in iD.
2. Click on the '+' to add a new tag.
3. Type the letters 'r' 'e', or even 'r' 'e' 'f', intending to create a new 'ref' tag.
4. iD will autocomplete the tag, with no user intervention, to ref:bag. I figured out with http://taginfo.openstreetmap.org/search?q=ref and based on the order in which results are provided for the autocomplete, that it's using 'the most times this tag is used' as the first autocomplete hit.

The problem with this is, that it's very easy to, if in a hurry, type 'ref' to manually add a tag, and tab to the next field, and not to realize that the tool has autocompleted to ref:bag. This is a tag that has no meaning outside the Netherlands, and yet, if you consult http://taginfo.openstreetmap.org/keys/ref%3Abag#map , you can see that it accidentally gets populated in this way. There are probably other tags, values, and variations for which this also happens.

(1) If the current behavior for autocomplete is going to be kept, then when autocompleting a potential tag's key or value, the first hit - that is, the one forcefully autocompleted to - should **always** be 'the shortest logical tag the user may be trying to use in the autocomplete list'. IMHO 're' or obviously 'ref' really ought to produce the autocomplete 'ref' first, not 'ref:bag'.

(2) Having said this, it would be better still if autocomplete required a positive action on the part of the user, like a 'down arrow' to select the first or other entry in the list, to autocomplete it to the first suggested item.

This feature can really be difficult to work with if I'm trying to put in, say 'hov:lanes' values by pasting them from my clipboard (because I know exactly what I want it to be, like 'designated|' or 'designated|yes', and the tool autocompletes to a much longer string that is not intended, meaning the paste is a two step process (paste then delete extra).

Thanks for reading!

**Comment by nighto** [comment]
Any progress on this issue? I don't want to just rant - and I know that patches are welcome - but since I'm mapping a lot of points with ```ref``` tags, this is driving me crazy. Perhaps manually overriding specifically for the ```ref``` tag?

Sometimes even if I press backspace to remove the ```:ruian:addr``` bit, when I press ```TAB``` it autocompletes wrongly again. It is very annoying.

Thanks a lot.

**Comment by bhousel** [comment]
Although in an ideal world people would clean up bad data, I'm closing this issue simply by sorting namespaced keys (i.e. keys containing `:`) below non-namespaced keys.
