### ISSUE TITLE
Too easy to switch away from save side-dialog without saving

### ISSUE THREAD

**Issue by risicle** [openstreetmap/iD#2378]
Hi,

The other night at a mapathon I had a new user faithfully regularly hitting save all evening, but each time not noticing the side dialog and thus never hitting the *actual* save button, assuming the top "save" button did what it said. This resulted in a full evening's work being lost.

Could be solved by something as simple as a dialog warning them if they switch away from the save-mode without saving. Preferably with a "don't warn me again" option.

**Comment by kerosin** [comment]
@danstowell As far as I understand this issue, it is not about how the saving interface is presented, but about the user-awareness that you need to hit a button to save your changes. This is what all OSM editors are doing: you need to hit a button to save after you made changes. The difference between iD and other editors is that the users are warned that their changes haven't been saved until now. This is about loosing data as well as conflicts that might raise if your editing a lot over a long period. Ideas, proposals or discussions about a different saving dialog might better fit in a new issue (or a existing one).

**Comment by danstowell** [comment]
@kerosin - I disagree. This github issue is about users pressing Save in iD but not realising they need to press the second Save button (see original message) - this issue is not about users failing to realise they need to save.

Editors such as JOSM and Potlatch2 show a modal dialog when you press Save (and this is a pattern that users will be familiar with from standard apps, even though the role of it is a bit different) - **this modal dialog is the mechanism that prevents the current issue from arising**, i.e. prevents the two-stage saving process from being abandoned half-way through by accident. It's not necessarily the only solution, but I've argued that it's a good choice.

**Comment by kerosin** [comment]
Oh yeah, sorry my fault misunderstood this and had a closer look at iD. Imho a sidebar doesn't differ to much to a modal/dialog box expect the position on the screen. The bad thing is that your able to continue mapping in this context. Like already said at this point it makes sense to force the user to finish his action. I would blur the map and disable all controls. Of course a color change could improve this too. At the moment the only thing happening: focus on changeset description and a big save button. And if you're continuing the only thing that is making you attentive is that there is count of changes next to the save button.

**Comment by bhousel** [comment]
I've replaced the close 'X' with an actual Cancel button, which should be clearer to new users.  We don't have any keys bound here (like escape) so as far as I know the only way out of this panel is to click the Save or Cancel button.

Before | After
--------- | -------
![screenshot 2015-07-30 12 18 52](https://cloud.githubusercontent.com/assets/38784/8991124/7c8c32a6-36c4-11e5-9a73-f92fb659d032.png) | ![screenshot 2015-07-30 14 09 42](https://cloud.githubusercontent.com/assets/38784/8991145/aa06d542-36c4-11e5-80e2-4815658e8da0.png)

**Comment by danstowell** [comment]
There's a third way "out" of the panel, which is to ignore the panel and carry on editing. That's the problem we saw recurring, and your change doesn't seem to address that. It looks to me like an improvement in itself, but I don't see how this prevents the error described in this issue?

**Comment by danstowell** [comment]
@bhousel no wait, I spoke too soon. I've poked around in iD and I see how it makes it clearer. When the user tries to "make their next edit" without having completed the save action, they are then confronted with the idea of cancelling rather than just "pressing x". Thanks.

**Comment by bhousel** [comment]
> @bhousel no wait, I spoke too soon. I've poked around in iD and I see how it makes it clearer. When the user tries to "make their next edit" without having completed the save action, they are then confronted with the idea of cancelling rather than just "pressing x". Thanks.

Yes that's a relatively recent change, I removed a bunch of behaviors from save mode with 80f5f65, so users can't make changes or quit save mode while the conflict resolution is happening.
