### ISSUE TITLE
more guidance in name-adding portion of walkthrough

### ISSUE THREAD

**Issue by jfirebaugh** [openstreetmap/iD#2382]
![image](https://cloud.githubusercontent.com/assets/98601/4546702/e56a8fd8-4e45-11e4-9a42-e2a73523c6fe.png)

**Comment by bhousel** [comment]
This becomes much less confusing now as a consequence of 2bbe968 / #2342.
As soon as the user starts typing, the close button changes from an ✕ to a ✓, and the intro advances to the next instruction.
