### ISSUE TITLE
change feature editor close X to check mark

### ISSUE THREAD

**Issue by jfirebaugh** [openstreetmap/iD#2384]
This would hopefully be a better hint that closing the feature editor doesn't discard changes.

It could always be a check mark, or we could have it be an X if no feature changes have been made in the current selection, and change to a check mark when they have.

**Comment by bhousel** [comment]
I did this today.. It plays nice with undo/redo too..

![checkmark](https://cloud.githubusercontent.com/assets/38784/11799439/17908790-a2a2-11e5-9d6c-87d3d7d6ed86.gif)
