### ISSUE TITLE
Loading local .gpx.gz files silently fails

### ISSUE THREAD

**Issue by rdoeffinger** [openstreetmap/iD#2397]
When loading a .gpx.gz file (as e.g. Osmand creates) it does not work, without any indication that something went wrong.
I also could not find any indication/documentation whatsoever that this format is not actually supported.
This is doubly annoying as clicking the edit link on e.g. https://www.openstreetmap.org/user/KaloRobi/traces/1812466 just doesn't display the track without any hint why/what went wrong.
The only way editing based on these traces that works seems to be downloading them, decompressing them and then manually showing them as local file, however I'd think most people wouldn't be able to figure it out and just assume that the editor just isn't working.

**Comment by rdoeffinger** [comment]
Documented unsupported feature makes a lot of sense when there's good reason to assume it is supported.
For example since it's supported by almost all other parts of the openstreetmap.org (including the potlatch editors it seems).
However it seems there should be a simpler way to fix this at least for non-local files:
When getting an URL like http://www.openstreetmap.org/edit?gpx=1887877, iD should open the URL
http://www.openstreetmap.org/trace/1887877/data.xml
instead of
http://www.openstreetmap.org/trace/1887877/data
which should always return an uncompressed version.

**Comment by rdoeffinger** [comment]
The below change once merged should fix the direct edit links:
https://github.com/tomhughes/openstreetmap-website/commit/d6bbcae9dbd51414fd5b0d22129df9bd81650e62
From my point of view this makes it mostly a error-handling issue, there should be some kind of indication when someone tries to load a broken/unsupported gpx file.

**Comment by jfirebaugh** [comment]
If there's anything to change here, it's upstream -- the API should serve gzipped GPX tracks with the correct `Content-Encoding` header.
