### ISSUE TITLE
"comment" URL pre-fill param fails to work if comment contains equals sign (%3D)

### ISSUE THREAD

**Issue by danstowell** [openstreetmap/iD#2406]
Thanks for adding the URL parameter to pre-fill changeset comment (commit 21da76cf8060832e36, closing issue #2311). It works, but it seems to fail when there's an equals sign included in the comment (URL-encoded as %3D) ... which happens in quite a lot of HOT Tasks!

Here's the URL which I originally discovered the issue in, a URL constructed by the HOT Tasking Manager: http://www.openstreetmap.org/edit?editor=id&#map=13/-0.968384792013/20.7398745496&comment=DRC%2C+%23hotosm-ebola-drc-661%2C+%23MapGive%2C+source%3DWorldView-2%2C+DigitalGlobe%2C+NextView%2C+8+March+2011+or+16+September+2014&gpx=http://tasks.hotosm.org/project/661/task/48.gpx&background=custom:http://hiu-maps.net/hot/1.0.0/boende-2-flipped/{z}/{x}/{y}.png

The `comment` param is quite long. So I experimented to find a minimal reproducer and I found the following:

* This works: http://www.openstreetmap.org/edit?editor=id#map=19/51.56473/-0.04403&comment=new%20changeset%20comment%20taken
* This works: http://www.openstreetmap.org/edit?editor=id#map=19/51.56473/-0.04403&comment=new%20changeset%20comment%23taken (it has a URL-encoded hash sign in the comment)
* This fails: http://www.openstreetmap.org/edit?editor=id#map=19/51.56473/-0.04403&comment=new%20changeset%20comment%3Dtaken (it has a URL-encoded equals sign in the comment)

Here, "works" means that if you make simple edit and press save, you see the desired comment pre-filled in the text box. "fails" means you just see the last comment you used in iD, whatever that was.

(BTW, I'm using Firefox v33)

**Comment by jfirebaugh** [comment]
The Firefox bug will be fixed in FF 41: https://www.fxsitecompat.com/en-US/docs/2015/urlutils-hash-no-longer-decodes-fragment/.

**Comment by jfirebaugh** [comment]
Browser fix has landed; this is now working in FF.
