### ISSUE TITLE
Preferred languages

### ISSUE THREAD

**Issue by hiddeneyes02** [openstreetmap/iD#2429]
Hi everyone,

I have a suggestion about language list. I'm trying to add arabic translations for all the cities in Algeria, the problem is I have to scroll through the list to find Arabic.

Can you plz put preferred languages (which can be selected elsewhere) at the beginning of the list so users can find them faster ?

Thanks.

**Comment by jfirebaugh** [comment]
I think #2933 is a great 90% solution here.
