### ISSUE TITLE
Cursors too small on Windows with high DPI screen

### ISSUE THREAD

**Issue by johsin18** [openstreetmap/iD#2439]
The custom cursors are shown extremely small on Windows high DPI machines. E.g. on a 13-inch notebook with 3200x1800, you usually set the Windows UI zoom to 200%, but the ID cursors don't scale up according to that. In particular, the crosshair is almost invisible. Why not use standard cursors in most cases? Happens on both Chrome and Firefox.

Problem might be related to/caused by issues #1205 and #2157.

**Comment by tmcw** [comment]
Can anyone confirm if this still occurs, or if Microsoft has fixed the behavior? It has been over a year since this issue was reported, and this is a platform-dependent bug.

**Comment by johsin18** [comment]
Fixed on Chrome, still exists on Firefox.
No custom cursors in IE an Edge at all really.

**Comment by bhousel** [comment]
Closing as stale. Cursors seem fine on my test surface pro in Edge and IE11.
