### ISSUE TITLE
Many Openstreetmap GPS traces do not show up

### ISSUE THREAD

**Issue by horsey2014** [openstreetmap/iD#2450]
There are a lot of Openstreemap traces that do not appear in iD compared with Potlatch2. see the following for an example:

with "OpenStreetMap GPS traces" turned on
https://www.openstreetmap.org/edit#map=17/45.30247/-75.93540

and on Potlatch 2 with "GPS data" turned on
https://www.openstreetmap.org/edit?editor=potlatch2#map=17/45.30247/-75.93540

**Comment by bhousel** [comment]
Hey @ericfischer , just checking in on this issue
We get occasional issues (like #5057) opened up on the iD repo which are already covered by
https://github.com/ericfischer/gpx-updater/issues (https://github.com/ericfischer/gpx-updater/issues/3)

I'd love to help out with this.  Let me know what's the best way!

Some things we could try:
* talk about the code to get more people to help maintain it?
* put it on another server that more people can access?

**Comment by bhousel** [comment]
More info here
https://wiki.openstreetmap.org/wiki/Visibility_of_GPS_traces

**Comment by jidanni** [comment]
Anyways, the user can only edit one version of a path,
then adjust it to be closer to the second version,
etc. third, etc. forth, as there is no way to show more than one trace unless they are lucky...

**Comment by mmd-osm** [comment]
@tomhughes: a few people on the forum mentioned that the gps layer isn’t updating anymore, probably since a few weeks. Is this a known issue?

**Comment by tomhughes** [comment]
No. Is it really a few weeks? or might it actually be less than a week, which would be a lot more likely...

**Comment by mmd-osm** [comment]
The first report is from end of May: https://forum.openstreetmap.org/viewtopic.php?id=62475 ... unfortunately no one created an issue for it back then. I don’t know exactly if it was working for some time since then and now fails again.

**Comment by tomhughes** [comment]
The original issue is caused by https://github.com/ericfischer/gpx-updater/pull/5 and there's also a more recent issue from last week in https://github.com/ericfischer/gpx-updater/pull/6.

Both have been patched in production for now.

**Comment by bhousel** [comment]
closed?
