### ISSUE TITLE
Usability: Feature type reselection method not obvious and object loses focus

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/iD#2453]
After adding a geometry feature, iD prompts the user to 'Select feature type', which the user then clicks on. However, if the user picks the wrong choice (e.g. realises perhaps another choice would have been better, or clicks by accident), it is not obvious how to return to the list, and the geographical object loses focus.

There are three problems with this UI presently, as shown by this reproduce case.

1. Click area, then draw out the geometry
2. 'Select feature type' appears in the left panel.
3. Click Area (or whatever)
4. User changes their mind.
5. Problem 1: There is no back button. I suggest there should be one in the top-left. Instead there is only the top-right 'X' which indicates a close-and-cancel operation. The user presses the X button. This does not take them back to the previous state where they were before.
6. Problem 2: The geographical object on the map has now lost its focus. The user probably will not have noticed this. All future operations they want to attempt will now fail because the object is not selected.
7. Problem 3: The user now has a 'Search features' panel. They may assume that this is what they wanted, namely a way to return to selecting a feature type. But actually 'Search features' means 'Search existing features in current view'. This label needs to be renamed.

**Comment by bhousel** [comment]
Added a back button to make feature reselection more obvious..

I was skeptical of this, but seeing it work, I like it.  Thanks!

<img src="https://cloud.githubusercontent.com/assets/38784/11860438/dae9237c-a442-11e5-967d-b387e06d3eb1.gif" width="500px"/>

**Comment by mvl22** [comment]
Thanks; this is a significant improvement, and I found myself doing this naturally, and finding the arrow was there.
