### ISSUE TITLE
Use CLDR for language list source

### ISSUE THREAD

**Issue by kmilos** [openstreetmap/iD#2457]
Currently iD only supports the 'name:sr' tag in the locale dropdown list, and wrongly labeled as 'Српски / Srpski' at that.

This locale is not intended to be used with both scripts, but Cyrillic only, and should be labeled as 'Српски' only, or 'Serbian (Cyrillic)'.

For Serbian written in Latin script, we have a separate locale 'name:sr-Latn' which should be added to iD dropdown as 'Srpski' only, or 'Serbian (Latin)'.

**Comment by 1ec5** [comment]
The `wikipedia` tag's value specifies a Wikipedia edition, not necessarily a language. Other examples of mismatches include `zh-min-nan` instead of the ISO code `nan` and `simple`, which doesn't correspond to any ISO language code. So it isn't a great source for language codes.

**Comment by tmcw** [comment]
@1ec5 is CLDR the answer, then?

**Comment by 1ec5** [comment]
CLDR would work, certainly, but it’s a very large package that contains much more than language names. Someone may’ve already created a subset of it specifically for this use case.

**Comment by bhousel** [comment]
Just a quick followup to this issue that it's now easy to pull in just the parts of CLDR that we want.  It has been split into subpackages, automatically converted from xml to json, and published on npm:
https://github.com/unicode-cldr/cldr-json#package-organization

**Comment by 1ec5** [comment]
Per #4632, we’ll need to introduce some iD-specific overrides to support `name:*` tags that are qualified with an ISO 15924 or ad-hoc script code, such as [`name:sr-Latn`](https://taginfo.openstreetmap.org/keys/name:sr-Latn) or [`name:zh-hant`](https://taginfo.openstreetmap.org/keys/name%3Azh-hant).
