### ISSUE TITLE
Squaring-Error

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#2472]
"Square an area" should align the corners of an area / building,
to beautify it to a more right-angled shape.
But sometimes this does not work right, and ends up with an unuseble shape,
e.g. one corner is lost (or 2 points moved to the same coordinates).

When mapping small villages, there are quite a lot of old buildings with odd shapes.
This is where I encounter the buggy behaviour of "square an area" more frequently,
but it can happen with simple 4-cornerd houses too. 
(I just didn't bother to write a bugreport yet)

Here some examples from the village [Rossdorf/Zeilhard](http://www.openstreetmap.org/#map=16/49.84368/8.79194) :
- [Way/316791604](http://www.openstreetmap.org/way/316791604) - simple house
- [Way/316801542](http://www.openstreetmap.org/way/316801542) - 8-corner house gets distorted
- [Way/316794583](http://www.openstreetmap.org/way/316794583) - another big building with "indent".
- [Way/316873578](http://www.openstreetmap.org/way/316873578) - some kind of storage building
- [Way/316794582](http://www.openstreetmap.org/way/316794582) - Farm-building
- [Way/320705754](http://www.openstreetmap.org/way/320705754)

Find all those places I marked with notes: http://overpass-turbo.eu/s/6tN

Note: since the report, there has been an automatic mass-edit, 
that might have corrected the data that leads to the error,
see http://www.openstreetmap.org/changeset/27512311

**Comment by rivermont** [comment]
I'm assuming this has been fixed @bhousel ?

**Comment by bhousel** [comment]
> I'm assuming this has been fixed @bhousel ?

I don't think anything has changed on this.
