### ISSUE TITLE
Closebutton does not work ("success"-panel after saving)

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#2473]
The "success"-panel "You just edited OpenStreetMap!" that appears after saving some edits
does not go away when the close-button is pressed.

As a workaround, I press "Export", and the close-button there...

Also, it would be nice to show something useful in that success-panel,
e.g. the changeset-number, the number of edits done,
that kind of info...

**Comment by bhousel** [comment]
@hajo4 is this also in Palemoon browser
(you mentioned in #2490)
