### ISSUE TITLE
Preset for junction=yes

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#2484]
Hello.

It would be great to have a preset for junction=yes (a junction as such – independent of its type – see http://wiki.openstreetmap.org/wiki/Tag:junction%3Dyes for details).

Applicable to: nodes, areas
Fields: a field for name=*
Pitfalls: for translation, probably it makes sense to comment that “junction” means here not exclusivly crossroads, but any type of junctions (T junction, Y junctions, Spaghetti junctions...)

Use case: In some countries (for example Korea) we have junctions with names, and they are even more important thant the street names.

**Comment by bhousel** [comment]
Reopening this because now closed ways with `junction=roundabout` is rendering as an area.  This is probably because of `areaKeys` finding the new junction preset.

I'm not sure the best way to tell `areaKeys` that only `junction=yes` should be considered a area.

**Comment by jfirebaugh** [comment]
Probably to add a preset for `junction=roundabout` that disallows the area geometry. Also it looks like the logic [here](https://github.com/openstreetmap/iD/blob/10f507732d1552e37a0ba56f784570bbc0a114bc/js/id/presets.js#L65-69) probably needs fixing, as it is sensitive to the order of presets. If a non-area supporting preset for a given key is encountered before the first area-supporting preset for that key, the former will not be correctly blacklisted.
