### ISSUE TITLE
Inaccessible hotspot for inserting new points into line

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#2490]
For inserting new points in a line between existing points,
the UI provides a hotspot in the middle between those existing points,
but inside the edit-window if the points are too far away.

The edit-window has some areas where clicks don't register,
e.g. menubars at top and right, and the "bing-banner" at the bottom.

It looks like the calculation for placing the hotspots 
does not take into account these "dead areas" of the edit-window,
see screenshot:
![osm_2014-12_line-hotspot](https://cloud.githubusercontent.com/assets/5838618/5542733/58eaf1ec-8aea-11e4-8ee2-604e19606cab.jpg)

Also, the top bar could be narrower (providing more workspace),
if the field for the save-count wouldn't be so high.

**Comment by bhousel** [comment]
@hajo4 what browser/version/OS is this?

**Comment by hajo4** [comment]
I am using Palemoon (a Firefox-Fork) on Windows

**Comment by pmailkeey** [comment]
Did you know - once a line is selected, you can double-click most places on that line to add a point ? Unlike the '+' centre arrow, double-clicking does not reposition the line either.

**Comment by pmailkeey** [comment]
Chrome / win7 - me too - bottom: bing bar in the way.
