### ISSUE TITLE
Scale in bing-banner only shows ft

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#2491]
When not editing, the scale is shown in feet as well as meters.

I prefer meters, so in edit-mode, I would like to have both,
or an option to select ft / m.

**Comment by jidanni** [comment]
$ locale
LANG=zh_TW.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=zh_TW.UTF-8
LC_NUMERIC="zh_TW.UTF-8"
LC_TIME="zh_TW.UTF-8"
LC_COLLATE=C
LC_MONETARY="zh_TW.UTF-8"
LC_MESSAGES=C
LC_PAPER="zh_TW.UTF-8"
LC_NAME="zh_TW.UTF-8"
LC_ADDRESS="zh_TW.UTF-8"
LC_TELEPHONE="zh_TW.UTF-8"
LC_MEASUREMENT="zh_TW.UTF-8"
LC_IDENTIFICATION="zh_TW.UTF-8"
LC_ALL=
give me meters.

**Comment by jidanni** [comment]
LC_MEASUREMENT="zh_TW.UTF-8" what more must I do?

**Comment by jidanni** [comment]
And the problem is not only in the Bing banner.
Why not be like Google and show both meters and feet on either side of the bar.

**Comment by bhousel** [comment]
Either your browser's preferred language is reporting `en-US` or your profile on openstreetmap.org "preferred languages" is set to `en-US`.

You can click on the scale bar to toggle it between imperial and metric.

**Comment by jidanni** [comment]
Please add a preferred units setting on the profile.

P.S., clicking it indeed toggles, but that is promptly forgotten next
time one opens the browser.

**Comment by bhousel** [comment]
Why not just change your preferred language to `en-GB`?

**Comment by jidanni** [comment]
Because I don't talk or spell like them!
