### ISSUE TITLE
Show date of aerial data

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#2492]
When mapping in areas where demolition & construction is taking place,
and the map is different from the image, it would be useful to see
the date of aerial images shown.

**Comment by cgiovando** [comment]
:+1:   Would be nice to be able to pass some imagery metadata automatically, especially when adding custom background imagery (WMS/TMS from HOT-OSM Tasking Manager) and automatically add a source=* and source:date=YYYY-MM-DD to whatever element is created or modified with that specific imagery layer turned on.

**Comment by jfirebaugh** [comment]
Even if the image tile comes with response headers indicating the vintage, we can't make use of them -- there's no way to get response headers for an `<img>` element. The only way to do this is to make a _separate_ request: either an ajax request for the same image (doubling the transfer cost for background imagery) or to another API that provides vintage in another format (hopefully for all tiles in a given area, so that we can make a single request).

**Comment by pnorman** [comment]
Based on experience, the metadata for the middle is sufficient. The per-tile info is not perfectly accurate at imagery boundaries anyways.

We should also make use of editor-imagery-index supplied dates.

**Comment by aawiseman** [comment]
Hi @bhousel I talked with @gmaclennan about this, he has worked on something similar, here's what he had to say: 

> I had some code from a Leaflet Bing Layer plugin that I created for parsing metadata from Bing imagery. That code is here:
> 
> https://github.com/gmaclennan/leaflet-bing-layer/blob/gh-pages/index.js#L160-L246
> 
> I mentioned this because from what somebody said at Sotmus I thought that iD did not currently display imagery date for Bing, but I see that it does actually display some metadata which you can see here: https://github.com/openstreetmap/iD/blob/af776501d3e8445c94d8d5f4198df5a06ccf1ba2/modules/renderer/background_source.js#L89-L133
> 
> It looks like iD is not currently reading metadata specific to the current center point, which my Leaflet plugin does. I'm not sure how this data is different, or whether it is useful - it's a while since I worked on this. The relevant docs from Bing are linked in my code comments.

**Comment by bhousel** [comment]
Nice!  Thanks @aawiseman for pointing me at @gmaclennan's code...  We could definitely perform that jsonp query to fetch the bing metadata.

**Comment by dalekunce** [comment]
👍 for this feature.

**Comment by bhousel** [comment]
Coming soon!
Added the code today to get the vintage from Bing's REST service, and use whatever is in editor-layer-index for all other sources..

![vintage](https://user-images.githubusercontent.com/38784/27759822-98268b76-5e07-11e7-825f-24739a70aa01.gif)

**Comment by cgiovando** [comment]
Now, can we inject that automatically to the source tag of any feature that is created off of the image layer being displayed? ;)

**Comment by bhousel** [comment]
> Now, can we inject that automatically to the source tag of any feature that is created off of the image layer being displayed? ;)

We _could_ add `source` tags to everything, but it might upset some people.  I regularly get people on here complaining about tags created by iD that they don't like looking at.

In fact when I map in New Jersey, I mostly use Bing even though the NJ 2015 Aerials are newer, simply because the Bing server loads much faster.  I do swap between the two layers with <kbd>⌘B</kbd> whenever I want a second look at something.

My next thing I want to sneak into this panel - if it doesn't take too long - is #1124 - some support for the imagery offset database.

**Comment by cgiovando** [comment]
> We could add source tags to everything, but it might upset some people. I regularly get people on here complaining about tags created by iD that they don't like looking at.

I don't see why it should upset anyone. It would add a very useful piece of metadata that is often just left blank. Even if shown in the overlay box that you just added (:+1:), I don't think many people would take the time to copy and paste into the source tag of every feature they map.

Adding it directly, as I'm suggesting, would be a major improvement in quality management of the map data. We should suggest adding the same function to JOSM as well :wink:

Personally I would go even further, and advocate for making the `source` and `source:date` tags mandatory for any  feature in OSM!

**Comment by magol** [comment]
Is it any plans to get the vintage for other aerial images to? Is it any standard that providers of aerial images can use to give that possibility? If not, it is anything that should be created?

**Comment by bhousel** [comment]
@cgiovando:
> I don't see why it should upset anyone. It would add a very useful piece of metadata that is often just left blank. Even if shown in the overlay box that you just added (👍), I don't think many people would take the time to copy and paste into the source tag of every feature they map.

Maybe ask on the OSM mailing lists to see what people think about this?  I don't have any strong opinion about it, but I know in my own mapping I probably wouldn't take the time to adjust the `source` tags on each new feature that I add or update.

@magol:
>Is it any plans to get the vintage for other aerial images to? Is it any standard (or best practices) that providers of aerial images can use to give that possibility? If not, it is anything that should be created?

If we can get the vintage from the other providers, I'll add code to do so.  I think [DigitalGlobe maps API](https://platform.digitalglobe.com/maps-api/) might provide this information for the Standard layer (@kevinbullock may know?).   DigitalGlobe Premium and Mapbox Satellite layer do not currently provide imagery vintage, as they are composites of several sources.  (But they could eventually provide a date range the way that Bing does).

Here is another cool screenshot - I'm adding imagery vintage to the tile debugging, and I'll add a button to toggle this display:
<img width="956" alt="screenshot 2017-07-02 10 23 26" src="https://user-images.githubusercontent.com/38784/27795424-184dd57a-5fd4-11e7-8992-500d97337912.png">

**Comment by boothym** [comment]
@bhousel Just to let you know, using Ctrl+Shift+B as described in the keyboard shortcuts swaps between the background like when using Ctrl+B.

Also, your changelog shows ⌘⇧B - you should really add the Windows shortcut as well 😉

**Comment by magol** [comment]
In the next version, it should also be any way to toggle this and the other panels even if I don't remember the shortcuts. The panels is great, but I always forgot the shortcuts. Maybe create a separate issue for that?

**Comment by bhousel** [comment]
> @bhousel Just to let you know, using Ctrl+Shift+B as described in the keyboard shortcuts swaps between the background like when using Ctrl+B.

Thanks @boothym can you open up a new issue for this?  The fix is probably to `stopPropagation` once the event is handled, so <kbd>Ctrl+B</kbd> doesn't get a chance to happen.

> Also, your changelog shows ⌘⇧B - you should really add the Windows shortcut as well 😉

Good suggestion - I agree, the changelog should show both.  I try to write release notes for a broader audience now, since new releases link to it via the 🎁 icon.

**Comment by bhousel** [comment]
> In the next version, it should also be any way to toggle this and the other panels even if I don't remember the shortcuts. The panels is great, but I always forgot the shortcuts. Maybe create a separate issue for that?

It's a good suggestion but I don't want to add buttons to the main iD user interface for these advanced features.  iD's main strength is its simplicity, and the panel shortcuts are discoverable from the keyboard shortcuts screen <kbd>?</kbd>. 

I have considered adding a button bar that only appears if the user has enabled the panels.  This is partly because I'd like to better support mobile/tablet users someday.  Right now I'm still waiting to see how this feature evolves, whether people use it, whether we add more of them, etc.

**Comment by d3netxer** [comment]
I did not know this feature existed. It is very useful. I think it is even more useful now that it has been implemented to work with the ESRI World Imagery layer as well. I often get questions of users asking if there is a way to tell when the date when the imagery was collected. I would like to see the date of the imagery in the bottom bar (along where the scale is and the usernames are displayed). Or maybe in the bottom bar there can be a metadata icon that will display the metadata panel. Metadata is important! @bhousel @magol

**Comment by tordans** [comment]
@bhousel did this feature (showing the date) make it to the live system? I cannot find it in the editor. 

I am in a HOT task and wondering if a building was demolished or build from one image to the next.

**Comment by bhousel** [comment]
> did this feature (showing the date of the image) make it to the live system? I cannot find it in the editor.

Yes it was merged to iD about a year ago.. Try using the Ctrl+Shift+B / Command+Shift+B key combo mentioned above to bring up the background info panel.. any luck?

**Comment by tordans** [comment]
Yes, thanks, thats great.
For this task there does not seem to be any year-information unfortunately :).
I will need to spent a bit more time with this info layer to understand it, there seems to be quite a few states.

Btw, this image date feature might also be a thing to consider for https://github.com/osmlab/osm-planning/issues/18.

**Comment by boothym** [comment]
@bhousel For me in the UK, the date shows up on Bing, but not anymore for the Esri imagery - something has changed recently. 

The DG imagery has a "show vintage" button which then requires you to zoom out to see the yellow boxes/text, but it's always been like that.

**Comment by bhousel** [comment]
> For me in the UK, the date shows up on Bing, but not anymore for the Esri imagery - something has changed recently.

Thanks @boothym it looks like openstreetmap.org needed a rule added to allow the connection to the Esri metadata servers.  @tomhughes [fixed this](https://git.openstreetmap.org/rails.git/commitdiff/a516d13) today - thanks Tom!

**Comment by bgirardot** [comment]
Hi all, Kevin Bullock suggested I put my issue in this thread, but I am not 100% sure this is the best place.

My issue is that when using DG Premium imagery, I can see the date using the imagery info panel. 

However when I zoom in, the imagery clearly changes to older imagery for DG Premium (DGP) which is not reflected in the vintage information. this happens in a lot of places around the world for the DGP layer.

You can see that ESRI World Imagery, which is the same the DGP layer does not do this and stays the same imagery even at z18 and higher.

Please see below.

DGP z17 is probably the 2017 the vintage layer says:
![2018-06-07_15h43_40](https://user-images.githubusercontent.com/265831/41104755-6da246a2-6a6c-11e8-87e1-1be136b63da3.png)

However, when I zoom into the z18 you can see the imagery clearly changes to what I am pretty sure is older imagery as significant development disappears without a trace. This is no longer the 2017 imagery the vintage layer indicates:
![2018-06-07_15h44_13](https://user-images.githubusercontent.com/265831/41104917-c9daca0c-6a6c-11e8-9f2d-5ee5f2bd3bf7.png)

You can see that Esri World imagery, which is the same as the DGP imagery, stays the same even at z18 and higher:
![2018-06-07_15h44_24](https://user-images.githubusercontent.com/265831/41104984-f3f220ec-6a6c-11e8-9f55-2cb3471f624f.png)

This really makes it impossible to date the DGP imagery that is actually used at a comfortable mapping z lvl and makes the DGP vintage layer incorrect as it is only for the z17 and lower z lvls.

**Comment by bhousel** [comment]
hey @bgirardot - the best place to discuss the Digital Globe vintage might be here:  https://github.com/osmlab/editor-layer-index/issues/371

There is some more info about them on that thread, and @marracci might be able to answer specific questions.  If the imagery changes when you zoom in, then you're right that it's kind of impossible to date it this way.

We all see these raster layers as kind of a "beta" feature, with the desired goal to either have a metadata server to query for more accurate results, or maybe store the metadata in vector tiles.

**Comment by bhousel** [comment]
also osmlab/osm-planning#18 has some more thoughts. I'd really like to build something to solve this!

**Comment by tordans** [comment]
> > did this feature (showing the date of the image) make it to the live system? I cannot find it in the editor.
> 
> Yes it was merged to iD about a year ago.. Try using the Ctrl+Shift+B / Command+Shift+B key combo mentioned above to bring up the background info panel.. any luck?

@bhousel I don't manage to see the image-dates for this are https://www.openstreetmap.org/edit?editor=id&#map=19/-4.44157/37.16185 - not for DG sources or Esri. I am pretty sure I tried all possible shortcut combinations (this time ;)). 

I cannot see any broken request in the network panel, so maybe I am really doing it wrong cause no API is requested? Or is it something else?

Apart from the shortcut, is there a clickable way to activate this layer/info?

**Comment by bhousel** [comment]
> @bhousel I don't manage to see the image-dates for this are https://www.openstreetmap.org/edit?editor=id&#map=19/-4.44157/37.16185 - not for DG sources or Esri. I am pretty sure I tried all possible shortcut combinations (this time ;)).

Ah yeah I don't see them either.  It looks like 2 separate problems.

For the Esri layers, it would show the vintage on the Background Info Panel, and also on the tiles themselves, but apparently not working now.
<img width="700" alt="screenshot 2018-12-21 12 02 29" src="https://user-images.githubusercontent.com/38784/50354108-6e561500-0518-11e9-933c-99c6972f9a63.png">

For the DG layers, you need to click "Show Vintage" and it will show some raster overlays.  These are supposed to have the vintage dates on them, but they don't have them.

<img width="700" alt="screenshot 2018-12-21 12 04 54" src="https://user-images.githubusercontent.com/38784/50354193-b2e1b080-0518-11e9-882f-de88fdbba720.png">

**Comment by d3netxer** [comment]
I don't see image dates for Bing either.

![vintage_unk_bing](https://user-images.githubusercontent.com/2665840/72901969-acfc6700-3cf8-11ea-83b1-3697ef95e9f9.JPG)

**Comment by quincylvania** [comment]
@d3netxer If the dates aren't showing up in iD then it's most likely that they're not provided by Bing.

**Comment by d3netxer** [comment]
Thanks. I now checked different cities around the world (Madrid, Paris, London, New York City, Lima, Sydney) and it is displaying at multiple zoom levels 'Vintage:Unknown'.
