### ISSUE TITLE
Selecting (nearly) horizontal ways is very hard in Firefox

### ISSUE THREAD

**Issue by kerosin** [openstreetmap/iD#2494]
Hi,

There is problem with selecting way, that are nearly horizontal. A [post in the german forum](http://forum.openstreetmap.org/viewtopic.php?pid=473532#p473532) called my attention to this issue  
### Issue description
Clicking on line to select a way is very hard and frustating on horizontal ways. To make it visible that a way is selectable by clicking the icon changes to a arrow. You need a lot of patience to get there and it is not suitable for a good workflow on editing OSM data.

### Steps to reproduce
1) open Firefox (so far only tested on Ubuntu)
2) enter url: http://openstreetmap.us/iD/release/#background=Bing&map=19.44/13.14187/46.34748
3) try to select Roggia Portis (horizontal way)
4) (optional) lower zoom level to maximum to see how hard it is to change the icon to select/editing icon

### Checked OS and Browser
✔does mean: clicking to select a horizontal way is nearly impossible
✖does mean: no problems occured

✔ Ubuntu 12.04 Firefox 34 (no addons)
✖ Ubuntu 12.04 Google Chrome 39
✖ OS/X Safari 8
✖ OS/X Firefox 34
✖ OS/X Chrome 39
✖ Windows 7 Chrome 34

If people can reproduce this on a platform or browser that isn't mentioned here, I will add it.

Thanks in advance!

**Comment by bhousel** [comment]
Looks like it is supposedly fixed in FF45, scheduled to ship March 2016.

**Comment by bhousel** [comment]
FF45 is out now and this looks fixed to me.
