### ISSUE TITLE
Support bicycle repair station

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#2497]
There are less than 50 of these mapped in OSM now, but these are getting popular fast.

(One small vendor in the USA sold close to 1000 of these stations in 2014 alone.... they've mapped none of them... and we've mapped only one of theirs).

```
{
    "icon": "wrench",
    "fields": [
        "operator",
        "opening_hours",
        "service:bicycle:pump",
        "service:bicycle:chaintool",
    ],
    "geometry": [
        "point",
        "area"
    ],
    "terms": [
        "diy",
        "fix"
    ],
    "tags": {
        "amenity": "bicycle_repair_station"
    },
    "name": "Bicycle Repair Station"
}
```

With suggested icon:
http://www.endlessicons.com/free-icons/wrench-icon/
And sketchy details at:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station
https://taginfo.openstreetmap.org/tags/amenity=bicycle_repair_station

**Comment by brycenesbitt** [comment]
Here's JOSM's icon for this feature: https://trac.openstreetmap.org/changeset/30898/subversion

**Comment by bhousel** [comment]
iD uses [Maki](https://github.com/mapbox/maki) for its preset icons, so I added it with a bicycle icon because Maki doesn't have a wrench.

**Comment by brycenesbitt** [comment]
Cool.  Could you add "brand="? 
Turns out the vendors want to be able to create maps of just stations of their designs.

**Comment by bhousel** [comment]
I added `brand` in 1ca44a2.. `opening_hours` is already there, but labeled as "Hours"

**Comment by Klumbumbus** [comment]
The key "service:bicycle:chaintool" changed to "service:bicycle:chain_tool" See http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station
