### ISSUE TITLE
When I put 2nd language for street name it appears in iD map instead of the 1st language

### ISSUE THREAD

**Issue by hariskar** [openstreetmap/iD#2501]
All street names are in Greek. When I put for a street a 2nd language eg English, the name of this street in iD map is in English. Is it a bug? How could street with 2nd language appear in Greek in the iD map?
Thank you

**Comment by kerosin** [comment]
Reproducable...
1) Open https://www.openstreetmap.org/edit?editor=id#map=18/38.91369/21.81152
2) Add a language-specific name tag: like name:de=test to a highway (does only happen for valid language codes)

Maybe it is a feature, not a bug. Reason might be to get visual feedback for what has been changed. imho the expected output would be the "official" name.

**Comment by hariskar** [comment]
Thank you, this happens in JOSM too, so it may be a feature. But why? I live in Greece, so I want to see Greek names, but I also would like to help a foreigner who seeks a Greek street with Latin characters. There should be an option to choose what language is visible, or output of "name" should be what is written there.

**Comment by Abbe98** [comment]
I think this is because the default language in OSM is English...

**Comment by kerosin** [comment]
Oh just saw that this happens only for "your" language (maybe the one you defined for osm.org? browser?). If I add a name:de the new name shows up and if I add name:en it displays the default name tag.

**Comment by hariskar** [comment]
If I put 2nd language name:de the name saws in Greek, but if I put 2nd language name:en English saws up. I have as preferred language el. Till now it was en,el. Now I changed it to el, but the problem remains. Thank you for replies!

**Comment by hariskar** [comment]
When I put
name= Greek characters
int_name= Latin characters for street names there is no problem. Should I continue this way?
Thank you

**Comment by kerosin** [comment]
Seems to be a browser language detection...  I created a new OSM account, changed locale to en and it is still displaying the new names (instead of the official name tag) only if they are entered as name:de. Maybe it is a OS thing?

Anyways regarding your question:
Depends on what the name your trying to enter. There are some discussions about this two tags (name:en and int_name), see http://wiki.openstreetmap.org/wiki/Multilingual_names#Greece, but I would use int_name for transliterations and name:en for common "translations"/names in that language.

**Comment by hariskar** [comment]
The streets here have a Greek name and the same name is under the Greek name with Latin characters, isn't it a transliteration?

Thank you for help!

**Comment by kerosin** [comment]
Yep, right

**Comment by hariskar** [comment]
According to this http://en.wikipedia.org/wiki/Transliteration it is a not transliteration but transcription, so I should choose name:en or int_name for this? Confused..
Is there a problem if I choose int_name for a foreigner that comes to Greece and looks for a Greek street with Latin characters in his GPS program? Will he find this street if I have put the Latin name in int_name?
Thank you

**Comment by kerosin** [comment]
Ελληνική Δημοκρατία -> transliteration: Ellēnikḗ Dēmokratía  / transcription: Elliniki Dhimokratia / english translation: Hellenic Republic

I think this is not the right platform to talk about tagging style. Please open a question at http://help.openstreetmap.org . You could ask which tag to use for transliteration/transcription/translation and which will be used by established apps (of course there are a lot).  I guess there is no consens about that, but this question might be interesting for other users.

**Comment by hariskar** [comment]
Thank you kerosin

**Comment by jfirebaugh** [comment]
To clear up any confusion on the iD side -- yes, it uses [`navigator.language`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage.language) as the preferred locale for translations and place names. So if your browser language is English, it will look for `name:en` tag first, and fall back to `name`.

**Comment by hariskar** [comment]
Thank you jfirebaugh. My browsers language is English :-/

**Comment by jfirebaugh** [comment]
Right, so showing English street names is by design. If you would rather see Greek street names, you need to change your browser language to Greek.
