### ISSUE TITLE
It is very hard to edit turn restrictions on iPad

### ISSUE THREAD

**Issue by socketpair** [openstreetmap/iD#2502]
After selecting point over which restriction should work (VIA) it is very hard to choose branches at left. Selection does not always work. Instead, i jump to properties of branch selected. When retrying, after some time, everything works fine. But in most cases selection of branch does not work.

**Comment by quincylvania** [comment]
Just tested this on iPad and had no trouble using the restrictions editor. A lot's changed since this issue was opened and lots will continue changing as we work on #5505. Closing as stale but we should continue to keep an eye out for problems here.
