### ISSUE TITLE
Introductory help text

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#2504]
The introductory help text (help on the side-bar) states

```markdown
Edits that you make on this map will be visible to everyone who uses
OpenStreetMap. In order to make an edit, you'll need a
[free OpenStreetMap account](https://www.openstreetmap.org/user/new).
```

Although technically correct, when viewed on OpenStreetMap.org this text can only be seen by someone who already has an account, so directing them to /user/new is not helpful.

A second more minor problem is that it directs to www.openstreetmap.org, and I was using the dev site, so it was the wrong link anyways.

**Comment by harkirat96** [comment]
Kindly check the pull request
https://github.com/openstreetmap/iD/pull/2563
Redirected the person directly to login rather than new user
