### ISSUE TITLE
Add Copy operation to the radial menu

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2508]
Now that we can Copy and Paste with ⌘-C and ⌘-V (see #2498), it would be nice to add a Copy operation to the radial menu for discoverability.

@samanpwbb, can you work your magic to make a copy icon?

Not sure whether or not a "Paste" button makes sense here too.

**Comment by pmailkeey** [comment]
I take this as a different 'copy'. Using keys to copy can utilise the clipboard. Copying using the annular menu ought to work differently - i.e. as per the move function that leaves the original in place.

**Comment by quincylvania** [comment]
> Not sure whether or not a "Paste" button makes sense here too.

I think it'd be frustrating to have copy without paste. This does mean we'd have to enable right-clicking on blank areas of the map and move the edit menu controller out of `modeSelect`.

---

Now that we've done #7577, the edit menu is also accessible on touch devices. Thus, implementing menu buttons for copy and paste would make these operations possible on mobile devices where keyboard shortcuts aren't generally available.
