### ISSUE TITLE
Unglue a point using Shake

### ISSUE THREAD

**Issue by Janjko** [openstreetmap/iD#2511]
I had an idea which would make ungluing a point effortless. Just hold a glued point, and shake your mouse. You end up holding one point, the other one returns to the original place. Shaking would work just like the windows shake function:

http://windows.microsoft.com/en-US/windows7/Minimize-windows-on-the-desktop-using-Shake

The same could be utilized with areas. Select an area, click "move" and shake your mouse.

**Comment by bhousel** [comment]
I don't think we should do this, as it's not very intuitive.  Offering an explicit "disconnect" operation is a better choice.

**Comment by harry-wood** [comment]
There is now an explicit "disconnect" operation:  Select the node to see a disconnect (<-->) icon. Keyboard shortcut 'D'.   Afterwards you can move one node off the other.

**Comment by bhousel** [comment]
> There is now an explicit "disconnect" operation: Select the node to see a disconnect (<-->) icon. Keyboard shortcut 'D'. Afterwards you can move one node off the other.

Yes, disconnecting a point from a line is something I've probably never needed to do in real editing, but it would look something like this, involving multiple disconnects and splits:

![disconnect_point](https://cloud.githubusercontent.com/assets/38784/15676011/8d591d94-2712-11e6-8bf8-63dfdb2dccee.gif)

**Comment by bhousel** [comment]
Or this, still tricky but pretty rare that anyone would need to do it:

![disconnect_point2](https://cloud.githubusercontent.com/assets/38784/15676217/60ed3294-2713-11e6-8bdb-f73b21cba9c4.gif)

**Comment by RAytoun** [comment]
It is a magnificent tool for fixing poor mapping. I have used it on a number of occasions. For example ... Where someone has accidentally linked two separate buildings with one corner node the same I use that tool to separate the buildings from each other so that I can then reposition them and square them separately. It also works where roads have been drawn at different times with different offset imagery. I can disconnect the roads from each other and realign them separately before reconnecting.

**Comment by slhh** [comment]
The need to disconnect a POI from a line doesn't seem to be rare, at least when unexperienced users are using iD.
Main usecase:
- Place or drag a POI near to a line without intention to connect.
- POI is connected to line automatically. (Alt modifier is hard to discover)
- POI needs to be disconnected from line. This might be detected too late or by a different user. Therefore, undo might not work.

Trying to work around the missing function offers a quite good chance to damage relations.
