### ISSUE TITLE
Lock imagery to a certain zoom level

### ISSUE THREAD

**Issue by kkaefer** [openstreetmap/iD#2513]
Sometimes, increasing the zoom level loads worse imagery than at a lower zoom level, so it would be cool to be able to lock the imagery zoom level and overzoom instead.

**Comment by bhousel** [comment]
Probably related: osmlab/editor-imagery-index#46 so that iD can make better decisions about which imagery to show at which zoom.

**Comment by bhousel** [comment]
ah this is also #2654

**Comment by kkaefer** [comment]
@bhousel nope, this is a completely different issue. The other one is about zooming the website, this one is about using tiles from another  zoom level.

**Comment by bhousel** [comment]
> nope, this is a completely different issue. The other one is about zooming the website, this one is about using tiles from another zoom level.

My reading of #2654 is that they are zooming the browser _because_ overzooming the tiles is not an option.
