### ISSUE TITLE
Wrong diagonal non existing parallel streets at certain zoom level over the city of Rho, Italy

### ISSUE THREAD

**Issue by silvandy** [openstreetmap/iD#2514]
While editing opencycle map to add some recently built cycle paths in the city of Rho (Italy), I found that at certain zoom levels a group of totally non existing huge straight main roads were shown on top of the real map (see attached screenshot). However, when going to iD editing functions, these streets were not there so it was impossible to get rid of them.
What can be done?
Please help, this thing is terrible
![non existing parallel streets](https://cloud.githubusercontent.com/assets/10667886/5872380/2dee5e20-a2eb-11e4-8464-8f65a80fc395.jpg)

**Comment by bhousel** [comment]
I don't see these artifacts on the standard map, or in iD - only on the cycle map.
(The area is [here](http://www.openstreetmap.org/#map=15/45.5390/9.0201))

It's not an iD issue, but maybe @gravitystorm can provide some more info..

**Comment by pnorman** [comment]
These look to ways that are not in the bounding box, but go through it.

As ways do not truely have a geometry themselves and are a list of nodes, the API only returns ways that have nodes in the bounding box, even if a way has a node on either side of the bounding box.

**Comment by bhousel** [comment]
But the artifacts only appear on the cyclemap tiles at z15.  They don't appear on standard, mapquest open, or humanitarian. 

I think it probably was an error that was fixed already and the cyclemap tiles need to update?

**Comment by gravitystorm** [comment]
the tiles have updated - it was apparently a mapping mistake that had unfortunate timing, and showed longer on that zoom level than elsewhere.
