### ISSUE TITLE
Display location in the footer of interface

### ISSUE THREAD

**Issue by tristen** [openstreetmap/iD#2515]
With tools like http://osmlab.github.io/to-fix when you select an error to edit it could any location in the world. It would be nice to get a sense of its geographic spot. ie:

![screen shot 2015-01-23 at 11 44 43 pm](https://cloud.githubusercontent.com/assets/61150/5886154/2c626640-a35a-11e4-8e79-bd91eaab6a50.png)

**Comment by tas50** [comment]
+1 this would be incredibly useful

**Comment by bhousel** [comment]
We're planning to add a small "map-in-map" popup pretty soon to help users better know where they are editing.  (Think like a little zoomed out map with a square representing the current viewport bbox).  I think I'll find a way to include the location text in this feature.

**Comment by bhousel** [comment]
see #2554

**Comment by 1ec5** [comment]
A breadcrumb would be useful on the main map as well: openstreetmap/openstreetmap-website#848.

**Comment by bhousel** [comment]
I have been using this gist to test out nominatim reverse geocode:
https://gist.github.com/bhousel/05be464d7f53c95c4eab

Even `zoom=10`, which I would think should return 'cities', nominatim is still returning hamlets, and the hamlet data in the USA is [pretty bad](http://www.openstreetmap.org/user/samely/diary/34541). 

If I go out to `zoom=9`, it returns county/region data, which is less useful.

**Comment by pnorman** [comment]
I think it would be useful to go ahead, even if there is bad data in a region which makes it less useful.

**Comment by bhousel** [comment]
Coming soon - A location pane that toggles with <kbd>⌘L</kbd>

<img width="776" alt="screenshot 2017-06-29 01 29 10" src="https://user-images.githubusercontent.com/38784/27672664-687412de-5c6a-11e7-825d-1b3083af6fe9.png">
