### ISSUE TITLE
Error de imegen

### ISSUE THREAD

**Issue by Pablo-Giunta** [openstreetmap/iD#2517]
Hola en esta ubicacion se ve todo negro.
https://www.openstreetmap.org/edit#map=16/-54.8061/-68.3228

**Comment by aaronlidman** [comment]
![screen shot 2015-01-26 at 7 36 53 pm](https://cloud.githubusercontent.com/assets/58878/5911363/b9b91eaa-a592-11e4-8e1c-156aca713e74.png)

This is a problem with the imagery. We can't do anything about that.

Interesting that it coincides with the border though.
