### ISSUE TITLE
Add distance/area measurement tool

### ISSUE THREAD

**Issue by mobina** [openstreetmap/iD#2519]
I am interested to add 'measure area' for area digitized.. Any clue to implement this tool ?

**Comment by bhousel** [comment]
Yeah this is a feature that would be really useful, and we do want to build it.. 
Can you describe how you might use the tool?  What kinds of features are you measuring?

**Comment by pnorman** [comment]
I recall this having come up in the past as being out of scope for iD, but cannot find the issue.

**Comment by jfirebaugh** [comment]
See #2039 -- I'm not convinced that this is a common enough need to justify permanent UI space in iD. At this point the bar is very high for adding features with visible UI. Every new feature adds complexity, and reduces the relative prominence of other, more commonly used, features.

**Comment by mobina** [comment]
To measure the length of the road or area of the building..

**Comment by pnorman** [comment]
> To measure the length of the road or area of the building..

I think you need to explain why in the context of a **mapping** workflow. Collecting distance measurements is not conventional. I have done it with a laser rangefinder, but it's a very specialized task.

**Comment by hajo4** [comment]
E.g. estimating the capacity of a car-parking-space from length or area.

**Comment by pnorman** [comment]
That sounds like a data consuming task, not a mapping task. If you're estimating the capacity, the parking lot is already mapped, and it's not like you should be putting an estimate into the tags.

**Comment by hajo4** [comment]
While mapping, after marking the area of some carparking, I would like to also fill in the capacity.
But I usually don't bother to count more than 5-10 cars/spaces.
So, to make a reasonable estimate, it would be nice to have a tool 
for measuring/displaying length/width/area.

**Comment by hajo4** [comment]
Regarding UI:
This could use a shortcut (say "i" for "info"), but even that could be left out.
Options to consider for displaying of the values:
* Area at the top and to the right of the "save-counter"
* Tooltip - say, after hovering 5 seconds over selected object --> no shortcut needed
* new "Info"-section in the right bar, say below "All tags" --> could be "displayed" at all times,
 but is only visible when scrolling down --> no button or shortcut needed

**Comment by hajo4** [comment]
Also, in some areas it is hard to estimate the size of objects.

There, a measurement-tool would help to see if some building
is a proper house, or just a hut/shed/garage, or a trailer/container.

**Comment by bhousel** [comment]
merged now, closing..
