### ISSUE TITLE
Add junction preset for nodes

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#2520]
The fix for #2484 was incomplete. I’ve tested it today at http://openstreetmap.us/iD/master/ and the junction support works only on areas. But it should also work on nodes.

**Comment by bhousel** [comment]
It does look like the junction preset should be available for vertices (meaning nodes that are a part of a way).  Do you need this preset also for freestanding nodes, not attached to any way?

see [junction.json](https://github.com/openstreetmap/iD/commit/3348ef8c724f62e590979fe230b372722b0e4916#diff-1490389bee18c2e4de49c57237ed60d8R3)

**Comment by sommerluk** [comment]
Oh, sorry. I wasn’t aware that iD dintinguishes between freestanding nodes and nodes that are port of a way. And I had done only a quick-and-dirty test.

It is perfectly fine to allow junction=yes on nodes only for vertices.

Sorry for inconveniance.

Closing this issue as invalid.
