### ISSUE TITLE
Remove support for landuse=yes

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#2530]
iD 1.7.0 supports landuse=yes (for nodes and for areas). The search term is “landuse”.

Probably landuse=yes is not very usefull - neither on nodes nor on areas.

I propose to remove the support for this.

**Comment by jfirebaugh** [comment]
There's not a preset for `landuse=yes` specifically, there is a preset for `landuse=*`, which means "any `landuse` tag for which there is not a specific preset". This is a pattern iD uses for presets in recognition that tags are flexible and user-generated and presets are necessarily incomplete. When this type of preset is matched to existing features, or selected by the user for a new feature, it shows a "Type" field to show the value or allow the user to enter their own. If the user does not enter a value, then it is true that `landuse=yes` will be used. This doesn't make as much sense as say `building=yes`, but I'm not sure what a better behavior would be.

**Comment by bhousel** [comment]
We should probably take it off from point and vertex (re: #2518).. I did this for all the other ones but forgot the generic landuse preset.
