### ISSUE TITLE
Horizontal strip above status bar refuses mouse clicks

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#2531]
Starting with 1.7.0, a horizontal strip above the status bar (where the background layer’s attribution is shown) refuses mouse clicks and drags. This dead zone has always been present, but it never used to span the entire page. It makes it very difficult to insert a node into a north-south way, because you can’t drag the little triangle that insists on appearing down there:

![Triangle](https://cloud.githubusercontent.com/assets/1231218/6186112/62dcda22-b32a-11e4-9916-0ec4909464d0.png)

Firefox 37.0a2 (2015-02-12)

**Comment by samanpwbb** [comment]
I noticed the same and fixed this in https://github.com/openstreetmap/iD/pull/2525 

Undisciplined of me (should have made a separate PR), but ideally that gets merged soon.

**Comment by bhousel** [comment]
thanks @samanpwbb !
I actually just opened this up to change the `pointer-events` and now I see that I don't need to..

I think I'll finally have a chance to look at it today...
