### ISSUE TITLE
Feature filtering checkboxes working opposite of how they should in Chrome

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2532]
This only seems to happen: 
* in Chrome (tested with 40.0.2214.111 on OS X) and 
* ~~on production iD embedded on openstreetmap.org and~~
* on the feature filtering checkboxes  

The checkboxes work as expected:
* with other browsers (Firefox, Safari) or
* ~~in Chrome when iD is standalone (e.g. openstreetmap.us/iD/master) or~~
* all other checkboxes in iD except those ones

Also: inspecting the `<input>` `DOMElement` in Chrome developer toolkit shows that the `checked` property is being set correctly, Chrome is just getting things mixed up.

~~Maybe related to something that `uglifier` does?~~

e.g. here they are all unchecked, when they should be all checked:
![screenshot 2015-02-13 15 36 10](https://cloud.githubusercontent.com/assets/38784/6194854/3ccaf366-b396-11e4-9d59-6b82761475e3.png)

**Comment by tyrasd** [comment]
Funny: I don't see this in the same version of Chromium (on Linux).

**Comment by bhousel** [comment]
Yes this is a weird one.. I spent way more time on it yesterday than I'd like to admit.
I really just want to say it's a Chromium bug, but I can't figure out their issue tracker.

**Comment by bhousel** [comment]
I realized that a lot of what I said above is wrong.

The issue really is:  if the map starts out uneditable (zoom < 15) the checkboxes don't get entered correctly and work reverse of how they should.  It still seems to only happen in Chrome, but it does happen whether embedded or standalone.  It makes more sense now.
