### ISSUE TITLE
Lock some features

### ISSUE THREAD

**Issue by flemmens** [openstreetmap/iD#2534]
It would be useful to have an option to lock some features in order to avoid selection errors.

For instance, when I am editing a new area, I would like to "lock" streets, so I can view them and eventually snap my new area to them as usual, but they should be in a "read only" mode, so I cannot click on a road by mistake or highlight them when it is not necessary.

I think it would speed up the edit process. I would like to try to change the code on my local version to check this but I am not sure which js I need to update, any help ?

**Comment by bhousel** [comment]
As of 1.7.0 you can hide features.  This isn't exactly the same as what you're suggesting but might be helpful.  

Click this icon to open the "Map Data" panel:
![screenshot 2015-02-23 12 03 39](https://cloud.githubusercontent.com/assets/38784/6332518/09315e9e-bb54-11e4-8430-6962d86c151d.png)

Then expand "Map Features" and unselect the feature types that are getting in the way of your editing..
