### ISSUE TITLE
junction=roundabout represented as a closed area

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#2538]
`junction=roundabout`s are being represented as a closed area recently:

![1](https://cloud.githubusercontent.com/assets/982338/6270106/b9d8c30e-b83e-11e4-8a01-7986463d483c.png)

Some users are starting to unnecessarily add `area=no` to have the old (and correct) behavior.

**Comment by bhousel** [comment]
Yes, I reopened #2484 for this.
