### ISSUE TITLE
map data not visible?

### ISSUE THREAD

**Issue by nomwerp** [openstreetmap/iD#2540]
Maybe I'm being _very_ stupid here (or more likely something to do with my set-up here) but i can't get any of the existing map features to show , background layers work, locator overlay shows, can create new features fine.

FF35 on linux , also happens with all addons disabled

no interesting errors in javascript console either:
```javascript
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create 
```

anyone any ideas?

![snapshot18](https://cloud.githubusercontent.com/assets/10109262/6313849/d87de4ba-b9bf-11e4-96fb-cc387c91fd76.png)

**Comment by bhousel** [comment]
When you uncheck the "Map Features" checkboxes, do things start appearing on the map?  It could be like #2532 where the boxes are working backwards of how they should be.

**Comment by nomwerp** [comment]
hi, thanks for the suggestion but that doesn't seem to be the issue, checked or unchecked nothing is showing.

**Comment by bhousel** [comment]
Just noticed this from your screenshot:
![screenshot 2015-02-23 11 44 36](https://cloud.githubusercontent.com/assets/38784/6332110/761b7f88-bb51-11e4-84f8-5edbac91b3f5.png)

Can you click on the warning triangle and dig into the SSL error?
It should show as a valid wildcard RapidSSL cert signed by GeoTrust..

**Comment by nomwerp** [comment]
well spotted , but unfortunately doesn't seem to be the issue FF is only complaining about some mixed content and just html is showing same problem.

more interestingly potlatch is giving same problem for me (so definitely seems to be an issue on my side) but is kind enough to show an error message:
 
>There was a problem loading the map data.
>Please check your internet connection, or try zooming in.
>
>https://www.openstreetmap.org/api/0.6/map?bbox=8%2E490864027352334%2C55%2E94319385276623%2C8%2E494124252409936%2C55%2E94433556402555
>

that got me to look into the http requests back in iD, i was getting "400 Bad Requests" for the map data for example for the request:
>GET http://www.openstreetmap.org/api/0.6/map?bbox=9.327392578124924,55.91227293006363,9.332885742187422,55.91535151540656

>Host: www.openstreetmap.org
>User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0
>Accept: text/html,application/xhtml+xml,application/xml;*/*
>Accept-Language: en-us
>Accept-Encoding: gzip, deflate
>DNT: 1
>Cookie: _osm_welcome=hide; _osm_session=64cf130b47d068cea8719d30141f9886; >_pk_id.1.cf09=9349377576f5241f.1424711278.1.1424712312.1424711278.; _pk_ses.1.cf09=*; >_osm_location=9.3234%7C55.9082%7C13%7CM; lock=1
>Connection: keep-alive

i  get the response:

>Cache-Control: no-cache
>Connection: close
>Content-Length: 0
>Content-Type: text/html; charset=utf-8
>Date: Mon, 23 Feb 2015 17:25:37 GMT
>Error: Accept header could not be parsed.
>Server: Apache/2.4.7 (Ubuntu)

turns out that a long long time ago i had been playing around with network.http.accept.default setting in FF and openstreetmap.org is the first webserver that didn't like it....

sorry to be wasting your time , i'll leave this here a lesson to others
