### ISSUE TITLE
Forest coloring differences 

### ISSUE THREAD

**Issue by cmyk** [openstreetmap/iD#2541]
This forest area appears darker than the surrounding ones:
https://www.openstreetmap.org/relation/1437836
How come?

**Comment by bhousel** [comment]
Good question..
e.g. this area shows the difference: https://www.openstreetmap.org/edit?relation=1437836#map=16/47.3999/9.3404

![screenshot 2015-02-23 11 05 51](https://cloud.githubusercontent.com/assets/38784/6331261/2f48d5ec-bb4c-11e4-8274-be23ff95abcb.png)

I think what's happening is the feature on the left is a simple `landuse=forest`, and the one on the right is a multipolygon with `landuse=forest` but the outer ways all have `natural=wood`.

So the multipolygon gets styled with both tags and it throws off the opacity..

**Comment by pnorman** [comment]
Given that there's a tagging error, the colour differences are probably fine.

**Comment by bhousel** [comment]
Thanks @pnorman I agree.. I revisited this today just to make sure I'm not missing something before closing it.

[The multipolygon wiki](http://wiki.openstreetmap.org/wiki/Relation:multipolygon#Usage) says

>Tags describing the multipolygon (e.g., landuse=forest) should go on the relation. The outer way(s) should be left untagged, unless they describe something in their own right. 

So it's reasonable for iD to apply both the `landuse=forest` from the multipolygon and the `natural=wood` for the outer ring.  Really this `natural=wood` tag should be removed.
