### ISSUE TITLE
An error occurred while trying to save

### ISSUE THREAD

**Issue by sebbehr** [openstreetmap/iD#2542]
I have this issue all the time. Sometimes I have to click the save button at least 5 times until it saves my updates. In this example I made over 290 changes and it will not save! It really freaks me out, because I already trying it for an hour ...

![an error](https://cloud.githubusercontent.com/assets/11173143/6345795/f3ab8d04-bc22-11e4-8657-c0a6b95bf651.jpg)

**Comment by bhousel** [comment]
Whenever I get this message, it's an actual connectivity issue with one of the 3 `api.openstreetmap.org` servers.

If you are ever stuck in iD and it won't upload, you can try opening a new browser tab and visiting `http://api.openstreetmap.org/api/0.6/capabilities` to see if the api is actually available.

You can also check: http://wiki.openstreetmap.org/wiki/Platform_Status to see if there is an outage.

Sometimes you can get even more info by running it through curl with verbose option:
`curl -v http://api.openstreetmap.org/api/0.6/capabilities`

(e.g. This happened to me once:  I had been editing on a network with ipv6, then closed laptop, and woke it back up on a network with no ipv6 route to the dns cached api server).   

Closing this issue, as it's not really something that we can do much about from the iD side, but hope some of this info might be helpful..

**Comment by pnorman** [comment]
I think we could give a more descriptive message when this is encountered

**Comment by bhousel** [comment]
Yes, in the next version the errors screen will have an expandable section so we can show more details.

**Comment by sebbehr** [comment]
Thanks Guys
