### ISSUE TITLE
Remove preset landuse=farm

### ISSUE THREAD

**Issue by henningvs** [openstreetmap/iD#2544]
When tagging a new area as a farmland the suggestion is always to tag it as landuse=farm, but nowadays it should be tagged as landuse=farmland (see here: http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfarm) .

Do you see this as an issue and if yes would it be solved by deleting the preset for landuse=farm? (https://github.com/openstreetmap/iD/blob/3b88fe999b954e0b8c8e6001b7884bd3de0be986/data/presets/presets/landuse/farm.json)

**Comment by bhousel** [comment]
Agree, we are using the new `farmland` preset now, see #2478 
We did miss changing it in one place, and I fixed this in 0b083f6
