### ISSUE TITLE
Symbol layer disaligned with imagery in edit mode

### ISSUE THREAD

**Issue by gunnargr** [openstreetmap/iD#2547]
![skjermbilde 2015-03-04 kl 14 49 47](https://cloud.githubusercontent.com/assets/131134/6484639/dbc3e72a-c27d-11e4-887a-eb990ab161dd.png)

**Comment by bhousel** [comment]
This is a common issue with background imagery.  Sometimes it just doesn't line up perfectly to the actual gps data in OpenStreetMap.

But there are some things you can try to make editing easier.
Click to open the Background pane:
![screenshot 2015-03-04 09 18 44](https://cloud.githubusercontent.com/assets/38784/6485183/d9af54fc-c24f-11e4-9e89-0224b9f6bbba.png)

You will see a list of background imagery choices that should work for the part of the map you are looking at.  Some will be better than others (Bing might not be the best one).

Also, at the bottom of the Background pane, you can expand the "Fix alignment" option, and use these buttons to shift the background imagery to better match the map data.
![screenshot 2015-03-04 09 24 22](https://cloud.githubusercontent.com/assets/38784/6485243/53f97e2c-c250-11e4-8089-8adc0e4086d1.png)

Hope this helps!

**Comment by gunnargr** [comment]
Thank You!
