### ISSUE TITLE
Building is describing a building type

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#2550]
Currently iD doesn't encourage users to add building types, instead it rather hides the fact that building is about a building type. Nonetheless "building" is a first class citizen in the simple editor, there are only 2 possibilities for the building values: "yes" and "unknown". This should rather become a textfield.

**Comment by jfirebaugh** [comment]
> Currently iD doesn't encourage users to add building types, instead it rather hides the fact that building is about a building type.

Here's what you see right away for the "Building" category:

![image](https://cloud.githubusercontent.com/assets/98601/6586005/591c243a-c733-11e4-85a5-c9b23ec98c5b.png)

Here's what you see if you search for "Building" (note, this is only partial results):

![image](https://cloud.githubusercontent.com/assets/98601/6586018/6edcd83c-c733-11e4-83ff-ff2ef796f2f0.png)

Here's what you see in the "Building" field if you nevertheless select the generic "Building" preset:

![image](https://cloud.githubusercontent.com/assets/98601/6586044/92889460-c733-11e4-8787-c1562cf074d9.png)

I think this qualifies as "encouraging users to add building types".

Where you see Building: Yes / Unknown is for other kinds of presets in which `building=yes` is a perfectly acceptable way to tag. E.g. `amenity=cafe`, `building=yes`. If you really want to be specific about the building type even in this case, you can use the advanced tags editor.

Closing here, let me know if there's something I'm missing.

**Comment by dieterdreist** [comment]
Thank you for explaining this better. I was looking at an existing object and tried to change the building type, but all iD offered me was "unknown" instead of the "yes" that was set. IMHO it would make sense to provide access to all these building types that you cite in your reply. The meaning of the key "building" is not changing with the presence of other tags.

**Comment by bhousel** [comment]
My thought on this is that there should build a special preference pane for **Building Details** that includes building type (#2550), roof type (#1829), height, levels (#2455, #2218).  It would only show up if the building checkbox field is checked.  Maybe someday some limited support for `building:part` and 3D stuff. 

It would be kind of like the turn restriction editor, but for structures.  

Side note:  a thing I find annoying about OpenStreetMap is that often when we talk about *buildings*, we really mean *structures*.  There are a few dozen `building=*` tags, but also `amenity=shelter` and at least 4 kinds of parking garages... The [feature matching code](https://github.com/openstreetmap/iD/blob/master/js/id/renderer/features.js#L92-L98) tries to hide some of this complexity.

This would make a pretty decent plugin.  I think its probably time to start thinking about how to make a plugin interface for iD, and try to "pluginify" some of the existing iD functions..

@jfirebaugh Do you think it's a worthwhile idea to go through the issue list, and label some of the  items as 'plugin', meaning "there's a good idea in here but it won't happen anytime soon and probably doesn't belong in iD core?"

**Comment by danieldegroot2** [comment]
> I think its probably time to start thinking about how to make a plugin interface for iD, and try to "pluginify" some of the existing iD functions..

_See openstreetmap/iD#1392 ._

**Comment by bhousel** [comment]
> See openstreetmap/iD#1392 .

Yes thanks.  I was aware back when I wrote that comment 7 years ago.
