### ISSUE TITLE
Add "tagging note" to presets.json

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#2551]
Is it possible to add to a preset a tagging note?  My specific example is people have found the "bicycle tool stand" preset, and used it to tag bike repair shops.  It's an understandable confusionL

"tagging_note:en" [
    "For bicycle shops offering repair, use the 'shop' preset.  This is for unattended bicycle tool stands.",
],

I'm aware this requires translation.

**Comment by bhousel** [comment]
Maybe it would be useful and not too intrusive to put this as a tooltip when the user hovers over the preset name/icon.

**Comment by jfirebaugh** [comment]
Please give this tag a description in its [wiki page](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station) template. Then iD will pull in the description in the tag help:

![image](https://cloud.githubusercontent.com/assets/98601/6630819/88cb435c-c8da-11e4-8c74-e59c4721ae18.png)

**Comment by brycenesbitt** [comment]
Done @jfirebaugh 
Though will iD pick up the language translations, if those are done on the wiki?
