### ISSUE TITLE
Add a UI for the railway service tag

### ISSUE THREAD

**Issue by bborkmiller** [openstreetmap/iD#2552]
I would be useful if the the railway editing presets had a control for the [service](http://wiki.openstreetmap.org/wiki/Key:service) tag, similar to the Type option for service roads. Railways don't have the same top-level service type as highways, the UI probably wouldn't be the same as it is for highways, but I think the same kind of drop-down menu with the possibility for free text would be fine.

Service=yard, spur, and siding get used quite a bit when mapping railroads, and it's a pain to have to go to the advanced tag editor to add this attribute.

**Comment by bhousel** [comment]
Is it a list limited to `yard, siding, spur, crossover` or is it a freeform `service=*`

If the former, I'll make a translatable combo field with just those options.  

If the latter, it will be a regular combo field that shows all the most common values from taginfo (which would include the highway ones).

**Comment by bborkmiller** [comment]
I've only ever seen `yard`, `siding`, and `spur`, and didn't even know about `crossover` until I looked at the wiki page. I don't see anything else in [TagInfo](http://taginfo.openstreetmap.org/keys/service#overview) that looks like it sees any regular usage, so I think having a combo field would be fine.

**Comment by bborkmiller** [comment]
:+1: Thanks!
