### ISSUE TITLE
Conflict between js/id/core/oneway_tags.js and wiki

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#2555]
According to http://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_link#Tagging_oneway "Most motorway_link roads will be one way, and should be tagged oneway=yes. Any unusual motorway link road which is two-way should be explicitly tagged oneway=no.". Added in http://wiki.openstreetmap.org/w/index.php?title=Tag:highway%3Dmotorway_link&diff=929508&oldid=917617

But motorway_link is assumed to be oneway by iD according to https://github.com/openstreetmap/iD/blob/master/js/id/core/oneway_tags.js

I have no opinion about what should be changed.

Found during reviewing https://github.com/gravitystorm/openstreetmap-carto/pull/1363

**Comment by bhousel** [comment]
@pnorman what do you think?

Is this a situation where the wiki is outdated and it's now safe to imply oneway for both `highway=motorway` and `highway=motorway_link`?

I kind of feel like the explicit `oneway=yes` tags are unnecessary at this point.

**Comment by mkoniecz** [comment]
Note that 94% of highway=motorway_link is explicitly tagged as oneway=yes. 4% has other oneway values. It seems that "explicit tagging of oneway status on motorway_link is expected" is accurate description of tagging practice.

http://taginfo.openstreetmap.org/tags/highway=motorway_link#combinations

Pointed out by @dieterdreist.

**Comment by pnorman** [comment]
explicit tags are strongly preferred from what i've seen.
