### ISSUE TITLE
Cannot add new points to Areas

### ISSUE THREAD

**Issue by jimmyrocks** [openstreetmap/iD#2556]
OS: MacOS X 10.9.5
Browser: Chrome Version 40.0.2214.115 (64-bit)
To replicate the error: Add a point to any existing area and save

As of commit 50a3fe320e4652409f3d5aa99ed3931e2e77b9b1, iD is not able to save an area after a new point is added.

iD attempts to query the nodes that it is modifying (which I think is a new feature), but it also sends the new (negative) nodes to the server, which the server cannot process.

Example:
http://www.openstreetmap.org/api/0.6/nodes?nodes=3396032737,3396032738,3396032739,3396032740,3396032741,-22,-21,-20,-19,3396032742

**Comment by bhousel** [comment]
Thanks for catching this!  I'll fix this tonight.

**Comment by bhousel** [comment]
this is fixed in 50a3fe3
