### ISSUE TITLE
on creation of a shape, context menu (for rectification, deletion, move,etc.) shows only at second activation

### ISSUE THREAD

**Issue by baumanager** [openstreetmap/iD#2560]
Previously, when you created an area / shape, the context menu showed up immediately when the shape was finished and you clicked somewhere on the boundary. Now, you first have to click somewhere else, so that the shape is deselected, click on the shape a second time to activate it again. Then everything works as before.
My browser is Firefox 35 for Windows.
This behaviour is causing me a lot of grieve because of all the unnecessary clicking around.

**Comment by donovaly** [comment]
I see this too and it is very annoying regression to all former iD versions.

(tested on Firefox 35, 36 and 37 on Windows 7)

**Comment by pmailkeey** [comment]
Fixed in next version: http://openstreetmap.us/iD/master/#background=Bing

**Comment by bhousel** [comment]
Yes this was fixed in 6ecca72
