### ISSUE TITLE
Need a way to visually diferentiate paved/unpaved roads

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#2564]
The areas I usually edit all have lots of unpaved roads.  It is very boring to manually select every via and then scroll down to check if the tag "surface" is correct.  it would be very nice to have a visual differentiation between paved (or asphalt, concrete, sett, etc) and unpaved (or gravel, dirt, cobblestone, etc) vias.

**Comment by pmailkeey** [comment]
All information should be visible on the map. Like this, the number of lanes should be visible too. I've rated unpaved roads as a track - but this may be more appropriate in the UK.

**Comment by afmenez** [comment]
Sorry, I can't see the difference on iD nor the main site.  I am referring to ways with the same classification, but with different "surface" tags.  I can't see any difference in ways with different number of lanes.  Is there some setting I have to change to see this?

**Comment by bhousel** [comment]
> Is there some setting I have to change to see this?

It hasn't actually been implemented yet, so no way to enable it..

**Comment by pmailkeey** [comment]
Track type relates to the surface and is used by OSM standard map to choose line type - usually the softer the track surface, the more broken the line. Nothing to do with surface tags. Got to make you query why OSM has two tags for surface !

**Comment by bhousel** [comment]
Looks like this now:
<img width="584" alt="screenshot 2015-11-25 15 19 40" src="https://cloud.githubusercontent.com/assets/38784/11408877/f05c2502-9389-11e5-9ac8-94366f7c7baa.png">

All highways can be paved or unpaved; unpaved ones render with bumpy casing.

`highway=track` is assumed to be unpaved, all others are assumed to be paved (though `surface` and `tracktype` tags are honored in all cases).

The list of "paved surface" tags is stored in [`js/id/core/tags.js`](https://github.com/openstreetmap/iD/blob/fc1ae42e5b2143814c4a6398f241522e02856275/js/id/core/tags.js#L33), and is currently:
```javascript
iD.pavedTags = {
    'surface': {
        'paved': true,
        'asphalt': true,
        'concrete': true
    },
    'tracktype': {
        'grade1': true
    }
};
```

**Comment by SHARCRASH** [comment]
Not here, normal?

**Comment by afmenez** [comment]
Great!  I can't wait for these changes to go online!

I'd like to suggest adding 'sett' and 'paving stones' to id.pavedTags,
since they usually lend to a smoother drive, unlike 'cobblestone' for
example.

Best regards,

    Alexandre
