### ISSUE TITLE
Save user's custom background imagery source in localstorage

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#2566]
Almost every time I open the editor i have to define a custom background image for IBGE, which is the official source for geographic information in Brazil:

http://{switch:a,b,c}.tiles.mapbox.com/v3/tmpsantos.hgda0m6h/{zoom}/{x}/{y}.png

This should be available by default for edits inside Brazilian borders.  Or at least the editor should save it on my configuration.

**Comment by pnorman** [comment]
iD imagery comes from [editor-imagery-index](https://github.com/osmlab/editor-imagery-index).

#2094 implies that iD should remember custom imagery, but I haven't tested it myself.

**Comment by afmenez** [comment]
Yes, this seems to be the same issue, but it doesn't work for me.  I have to reenter the URL every time I open the editor.

**Comment by Skippern** [comment]
It will be solved when this PR is pulled: https://github.com/osmlab/editor-imagery-index/pull/89

**Comment by bhousel** [comment]
> #2094 implies that iD should remember custom imagery, but I haven't tested it myself.

Looks like #2094 is only to remember it between background changes, not between sessions.
