### ISSUE TITLE
Symbolic links don't work when repo is cloned on Windows

### ISSUE THREAD

**Issue by kto-nado** [openstreetmap/iD#2574]
Sorry for mistakes in the text

Created a website on localhost and uploaded the files to the root. Instead of a window with the program I see a blank screen. 

![2015-04-04 15-56-12](https://cloud.githubusercontent.com/assets/11796924/6992706/61b9b1a2-dae3-11e4-86bd-494b1b5580b4.png)

**Comment by bhousel** [comment]
There isn't really anything special that you need to do, as iD is a single page javascript app.  If you clone the project somewhere that a web server will serve it, things should just work.

As a simple test, use a console to go into the project root and start the web server this way:
`python -m SimpleHTTPServer`
Then visit `localhost:8000` with a supported browser (webkit or firefox) and you should see something.

**Comment by Abbe98** [comment]
Note: on Windows you won't see images because Windows does not support symbolic links, also if you have Python 3 and not Python 2 the you start the web server by running ` python -m http.server 8000 --bind 127.0.0.1`.

**Comment by bhousel** [comment]
> Note: on Windows you won't see images because Windows does not support symbolic links,

Interesting.. I guess someone motivated enough could fix the symlinks on Windows using a technique like [described here](http://stackoverflow.com/questions/5917249/git-symlinks-in-windows).

**Comment by kto-nado** [comment]
So, if you transfer the program on Linux it should work?

**Comment by Abbe98** [comment]
In the case of symlinks it does fix it, but in this case it's something else. Does the console give you any errors?

**Comment by kto-nado** [comment]
Thanks for the help, the program works on Linux.

**Comment by kto-nado** [comment]
Thanks for the help, the program works on Linux.
