### ISSUE TITLE
Remove "denotation=cluster" from presets (iD 1.7.0)

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#2575]
All 250,000 uses of "denotation=cluster" were purged from the OSM database in March 2015.
Could you remove the corresponding "cluster" value from iD, under natural=tree?  The value comes back occasionally from iD users.

For comparison JOSM's preset does not offer denotation at all.

**Comment by bhousel** [comment]
These values are sourced automatically from taginfo.  I notice that `cluster` is not showing up in the `denotation` combo box anymore since the removal, so looks like the combo is working like it should...
