### ISSUE TITLE
Selecting 'Long Road'

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2579]
[tagging issue]

When selecting a segment, the length selected is up to where it's cut - whether the cut is needed or not. Let's now assume a situation where Long Road passes through Village. As Village has a speed limit, Long Road is cut into 3 segments - the middle one having an additional maxspeed tag. Now let's say maxspeed is going to be applied to the whole of Long Road.

It would be useful if on clicking on Long Road we got a menu allowing us to choose the segment to the cuts or the whole of Long Road - as the latter is what we want to do in this case. In more complex tagging situations, there will be the possibility of intermediate lengths of sensible selection options. The other point being that once selected, it'd be useful if the left panel showed all tags and where there are conflicts, to have them greyed out. I see no reason why iD can't allow users to work with several segments at the same time.

Similarly to buildings - e.g. selecting a row of houses on a street and applying address details to those houses (excluding name or number).

**Comment by jfirebaugh** [comment]
Sorry, I can't understand this issue.
