### ISSUE TITLE
Duplicated changesets

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2581]
Changeset: 29992575 appears to be one of two identical changesets. iD doesn't appear to offer an 'undo changeset'. This would be a useful tool for correcting mistakes.

**Comment by bhousel** [comment]
I don't see another changeset like that one..  Do you have a changeset id for me to check?

Reverts can be pretty complicated, so it's not something that we could put into iD.  This is because after the changeset is accepted, the objects could have been modified by someone else.

**Comment by pmailkeey** [comment]
Someone with reversion gear has deleted the duplicate. A whole bunch of trees were duplicated!
