### ISSUE TITLE
GPX/GPS unit interface

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2582]
As an obvious tool for editing OSM maps, one would have expected OSM to be GPS-friendly. Is there anyone on the iD team keen to implement a GPX file / GPS unit interface ?

I know OSM has a part one allowing traces to be used but that's all it does. All the waypoint data isn't accessible - so notes of stiles, gates, mailboxes has to be accessed from files/units by different software rather than being presented on the map for addition to OSM.

I've also not yet found a good data route-planning application to export data to either a GPX file or GPS unit. Anyone got any suggestions ?

OSRM doesn't allow start-end placement other than by typing a location, doesn't do walking routes and doesn't allow route planning across fields. It can create a GPX file though !

**Comment by bhousel** [comment]
iD will open a gpx file if you drag and drop it onto the map. The tracks and notations are displayed on a special layer (which you can toggle in the Map Data panel) and you can trace over it. 

What other gpx support do you think would be useful? Definitely open to ideas. 

As for services, all of my devices are Garmin sports watches, so I really only have experience with the Garmin tools for course planning and transfer to/from devices.

**Comment by pmailkeey** [comment]
"iD will open a gpx file if you drag and drop it onto the map." 

How can you make this functionality more obvious - it's a great feature but how are newbies supposed to know of it ?

"The tracks and notations are displayed on a special layer (which you can toggle in the Map Data panel) and you can trace over it."

"What other gpx support do you think would be useful? Definitely open to ideas."

Opening GPX should include waypoints - having gone surveying making waypoint notes in the GPS it'd be good if these were accessible while editing the map. Stuff like whether it's a gate or a stile.

I look at the map and see features that I feel need surveying. A means of creating or editing the GPX overlay to plot route or mark features to be queried to be then saved as GPX for upload to GPS unit prior to surveying would be useful to me as I haven't found a satisfactory alternative. There are OSM/GPS interfaces but the tend to only create routes and those routes are along vehicular ways. I prefer to plan where I want to go - and this might involve visiting a feature in the middle of nowhere.

**Comment by bhousel** [comment]
> How can you make this functionality more obvious - it's a great feature but how are newbies supposed to know of it ?

The Help pane does talk about this under the GPS section.  Also the "Map Data" panel has the GPX layer item where the user can pick a GPX file, and there is a tooltip that explains that they can browse for the file or drag and drop.  So I think we probably have this documented in enough places that users can discover it.

> Opening GPX should include waypoints - having gone surveying making waypoint notes in the GPS it'd be good if these were accessible while editing the map. Stuff like whether it's a gate or a stile.

I think we do support waypoint/trackpoint labels on the map now.  Can you try with a GPX file that you have and let me know if there are features in the file that are not being displayed on the GPX layer.

> A means of creating or editing the GPX overlay to plot route or mark features to be queried to be then saved as GPX for upload to GPS unit prior to surveying would be useful to me as I haven't found a satisfactory alternative.

Exporting from iD to GPX is really out of scope.  I do think there are probably better tools for what you are trying to do (google things like create a gpx file and send it to your device).  I only know of Garmin's ability to create courses and "send to device", but this works ok for me.

**Comment by pmailkeey** [comment]
How can you make this functionality more obvious - it's a great feature but how are newbies supposed to know of it ?

The Help pane does talk about this under the GPS section. Also the "Map Data" panel has the GPX layer item where the user can pick a GPX file, and there is a tooltip that explains that they can browse for the file or drag and drop. So I think we probably have this documented in enough places that users can discover it.

Generally, I look for help on things I know about. If I don't know a feature exists at all, I've no reason looking for help on it !  "Map Data" means nothing to me and the icons are reasonably meaningless. If I saw "Settings", I'd be tempted to have a look to see what settings and options were available.

When you've been with something for a long while it's easy to get familiar with it. For a newbie, it's a different matter - things need to be made obvious - whether there on the screen now or appear alongside other features - where they'll be seen while the user is doing something else.

**Comment by pmailkeey** [comment]
"I think we do support waypoint/trackpoint labels on the map now. Can you try with a GPX file that you have and let me know if there are features in the file that are not being displayed on the GPX layer."

 - found the problem - GARMIN again.

Doesn't put the waypoints in the same file - stores them separately!
