### ISSUE TITLE
Directly specify lat/long of a node

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2583]
Can we have a pseudo tag for location - to display the 'lat,long' of a point's position which is editable so that the point can be moved to a precise lat/long by typing in or editing its location?
Similarly, it'd permit a lat/long to be read and copied to the computer clipboard for pasting into another application.

**Comment by mobina** [comment]
I too have a similar requirement .. Any suggestion to include it..

**Comment by jfirebaugh** [comment]
This is out of scope for iD.
