### ISSUE TITLE
Connected entities are disconnected after copy and paste

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2584]
Copying and pasting - if you select several joined items (sharing points) as a group, copy and paste them elsewhere, the pasted items are no longer connected and can be moved individually. I guess this will create an error of more than one node in the same place unless things are reconnected.

**Comment by bhousel** [comment]
Yeah I can see how this would be an issue. I'm thinking if a user copies a bunch of stacked up nodes with uninteresting tags, we should only paste a single node.

**Comment by pmailkeey** [comment]
On 12 April 2015 at 04:26, Bryan Housel <notifications@github.com> wrote:

> Yeah I can see how this would be an issue. I'm thinking if a user copies a
> bunch of stacked up nodes with uninteresting tags, we should only paste a
> single node.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openstreetmap/iD/issues/2584#issuecomment-91977717>.
>

Not keen on 'data loss'. Whatever's copied should be pasted as is - if
objects are joined at nodes then they should paste joined up too. That's
the issue.

-- 
Mike.
@millomweb <https://sites.google.com/site/millomweb/index/introduction> -
For all your info on Millom and South Copeland
via *the area's premier website - *

*currently unavailable due to ongoing harassment of me, my family, property
& pets*

T&Cs <https://sites.google.com/site/pmailkeey/e-mail>

**Comment by bhousel** [comment]
Oh, I think I misunderstood... 
You are saying if a user selects some points that are connected and copy/pastes them, they should stay connected as a way?

Copying this:
![screenshot 2015-04-14 14 00 49](https://cloud.githubusercontent.com/assets/38784/7143682/bc57b74e-e2ae-11e4-965b-c711b165804c.png)

Should result in this:
![screenshot 2015-04-14 14 02 48](https://cloud.githubusercontent.com/assets/38784/7143762/1fdcea3c-e2af-11e4-8a81-fc8550558b08.png)

Not this:
![screenshot 2015-04-14 14 03 06](https://cloud.githubusercontent.com/assets/38784/7143775/2f2593a4-e2af-11e4-981b-abf20d9c01e4.png)


Is that right?

**Comment by pmailkeey** [comment]
Good job you didn't change the issue number as well ;)

Yes, that's right and this (2 squares)

![image](https://cloud.githubusercontent.com/assets/11827386/7149719/069db4e8-e309-11e4-8913-1fe89c2ce94d.png)

should paste like this:

![image](https://cloud.githubusercontent.com/assets/11827386/7149731/44874fbc-e309-11e4-8a04-891f7fc0076d.png)

and not like this:

![image](https://cloud.githubusercontent.com/assets/11827386/7149751/8dd0ee58-e309-11e4-8e4d-e5b40583d305.png)

i.e. shared nodes of the two squares remain shared, not as 2 separate squares with nodes in the same place but not connected.

**Comment by jfirebaugh** [comment]
This is out of scope for iD.

**Comment by slhh** [comment]
@jfirebaugh I'd agree on copying of segments beind out of scope. It is rarely required and other methods to acceive the result exist.
The original was describing a copy and paste bug which still exists and seem to be quite valid. The comments seem to be a series of misunderstandings. "Copy segments" is only what @bhousel has made out of the original issue due to misunderstanding.

**Comment by jfirebaugh** [comment]
Ah, I see. Thanks for clarifying.
