### ISSUE TITLE
Request to support marine focused "fuel" tag

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#2589]
The iD editor presently supports tagging of amenity=fuel, calling it a gas station in English.

This is a request to support tagging of a marine fuel facility.  These are not interchangeable features.  There are two candidate tags for this:

seamark:small_craft_facility:category=fuel_station
waterway=fuel

Note that separate amenity=fuel and waterway=fuel may exist within the same leisure=marina.  So proximity is not enough to determine the facility type.

**Comment by bhousel** [comment]
> seamark:small_craft_facility:category=fuel_station
318 uses in taginfo

> waterway=fuel
166 uses in taginfo

so it seems that the seamark tag is the better one, yes?

**Comment by brycenesbitt** [comment]
The seamark:small_craft_facility:category tag takes a semicolon separated list, and is
not processed by anything other than OpenSeaMap.  The tags have long diverged from OpenStreetMap.
So while the numbers are higher, it's not clear if the tag is actually better.
A pragmatic solution is to tag both, not trying to predict a winner, but helping support the mapping of the feature.

**Comment by pnorman** [comment]
Any idea how often `amenity=fuel` occurs on water?

**Comment by brycenesbitt** [comment]
@pnorman I've seen this tagging, but don't know how to readily make a query to count.

Note that marine fuel stations are invariably on a floating dock, and thus for new mapping can reasonably be tagged on a node of a man_made=pier.

**Comment by bhousel** [comment]
> The seamark:small_craft_facility:category tag takes a semicolon separated list, and is
> not processed by anything other than OpenSeaMap. The tags have long diverged from OpenStreetMap.

Oh, I see.  Yeah the iD presets are not able to adjust specific values inside a semicolon separated list and that not something we will support.

`waterway=fuel` is my preference also..  Looks like you added a wiki stub for it recently?

**Comment by brycenesbitt** [comment]
Yes, I added the stub.  It's in use, it makes sense, and it sets a nice pattern (amenity=fuel/waterway=fuel,  amenity=sanitary_dump_station/waterway=sanitary_dump_station).  This is a case of structuring data well for later rendering also.

**Comment by pnorman** [comment]
I'm downloading the data, I suspect water and land-based fuel stations are tagged the same.

**Comment by brycenesbitt** [comment]
@pnorman I'm interested in your results.

Note the past is not to be ignored, but a preset is about _future tagging_. If fuel stations are tagged as amenity=fuel, it's probably because that's all that renders. The downside is someone types "show me a nearby gas station" in OSMAnd, and they have a bad experience with OSM data.

A semi-mechanical edit can probably hit several 9's on separating out the feature.
A future policy where osm-carto leads tagging change (rather than following the lead of the editors) would also alter how tags like this play out.

**Comment by brycenesbitt** [comment]
@pnorman unfortunately there are marine facilities that are on land like https://www.openstreetmap.org/node/853853620/history .  Proximity alone can't reliability make the distinction.

**Comment by pnorman** [comment]
165 amenity=fuel points or polygons intersecting the ocean. I didn't think to include `natural=water` or `waterway=river` when importing, so I don't have that data.

So, my preference would be for `waterway=fuel` but I'm not sure the tagging has settled out enough for it to be added to presets.

**Comment by brycenesbitt** [comment]
@pnorman that count of 165 is .006% of the total mapped fuel stations.

You've got a probably large undercount, as most freshwater marinas use some combo like natural=water.

How many of those are rendering hacked amenity=fuel +  waterway=fuel?

--
We won't know the true mapper preferences on this issue until waterway=fuel renders in osm-carto.  The lack of rendering no doubt pushes people to other tags.    Would you support starting at osm-carto, and then circling back to a preset after a year or so?

**Comment by brycenesbitt** [comment]
Note the same issue presents itself for aviation fuel... only it's harder to disambiguate as both land & aviation fuel are sold at airports.

**Comment by pnorman** [comment]
> Would you support starting at osm-carto

It's not an established tag. Tags have been getting established without presets or renderer support for a long time, so this isn't necessary for tagging to become settled.

**Comment by brycenesbitt** [comment]
It's not necessary, but it's terribly helpful, especially in the iD context.  A new powerboat enthusiast coming to the map is clearly either going to be confused (why the fuel station did not show up), or guided to using amenity=fuel. 

But that is a separate discussion from the iD tag.

**Comment by brycenesbitt** [comment]
There's a lot of this out there also:
https://www.openstreetmap.org/node/3142399948/history

**Comment by brycenesbitt** [comment]
Note I was concerned that OpenSeaMap might object to this tagging.  Turns out the
majority position seems to be that dual tagging is good:
http://sourceforge.net/p/openseamap/mailman/message/31471886/

**Comment by sabas** [comment]
I used seamark:type=bunker_station (https://www.openstreetmap.org/node/3257385215#map=19/44.30195/9.21109) but I could switch to another tag :-)
It would be needed to tag also facilities which give fuel to both vessels and cars.

**Comment by brycenesbitt** [comment]
@sabas there are only seven (7) bunker stations in the OSM data.  Bunker also implies bunker fuel oil, which is for heavy ships, and not used for small craft.  

The JOSM editor implements *waterway=fuel*.  OpenSeaMap uses and renders fuel_station if it is part of a seamark:small_craft_facility:category=fuel_station tag.

It's pretty rare to have a single fuel pump with  long enough hose to serve boats and cars.  But if so just tag:

amenity=fuel
waterway=fuel
name=Fred's Boat & Car Fuel Station

**Comment by sabas** [comment]
Thanks @brycenesbitt!
