### ISSUE TITLE
Lat/Long Display in Status bar on Mouse Over

### ISSUE THREAD

**Issue by mobina** [openstreetmap/iD#2590]
I want to display the lat/long (on the status bar) of mouse over on the map. Is it possible to display? If yes, Please suggest to implement this.

Thanks in advance

**Comment by bhousel** [comment]
We're probably not going to add this into iD, but [here is a gist](https://gist.github.com/bhousel/29571cc966757aed4aec) I threw together quickly to show you how I would do it.

**Comment by mobina** [comment]
I am new to the D3 Frame work. Can U please suggest me where to include this code in my iD.js .

**Comment by mobina** [comment]
Thank you sooo Much.. Perfectly it worked...
