### ISSUE TITLE
Wireframe mode - missing data

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2591]
Fill area options - offers wireframe mode. Unfortunately, a lit of other data is lost - all points not connected to lines. Perhaps these should appear as per the filled circles for intersecting nodes ?

**Comment by pmailkeey** [comment]
When will the change be visible in iD beta ?

**Comment by bhousel** [comment]
The update to wireframe mode is on http://openstreetmap.us/iD/master
That site is pulled from master every 15 minutes or half hour or something like that..

**Comment by pmailkeey** [comment]
Maybe I've not explained the issue properly as I'm using the /master iD as beta testing. Here's an image with partial fill and wire frame.


![image](https://cloud.githubusercontent.com/assets/11827386/7255217/ca3954b2-e83f-11e4-97bf-f33eed73cda9.png)


In the latter, the trees are missing. That is the issue. I feel they and other 'lone points' should appear like the grey circles used at intersections. I note that points such as entrance/exit appear just the same in either view mode.

**Comment by pmailkeey** [comment]
Another image:
![image](https://cloud.githubusercontent.com/assets/11827386/7255325/65444840-e840-11e4-9e0a-52eec7c1933c.png)

This shows connected points (entrance exit) + the grey node circles I feel would be 'correct' for wireframe mode of points like ent/exit, mailboxes etc.
