### ISSUE TITLE
Grass and kerbs

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2592]
![image](https://cloud.githubusercontent.com/assets/11827386/7193198/3ed8ce8c-e495-11e4-9a69-e67e7921c4ee.png)

Top left: grass with kerb on bottom edge
Bot left: grass with kerb all the way round
Right: grass and kerb as one object - but iD doesn't show the kerb's line (like the bottom edge of the top left image). 

Can this be fixed ?

**Comment by bhousel** [comment]
Good suggestion.. I've added a style for `barrier=*` now - it looks like this:

![screenshot 2015-04-21 11 44 17](https://cloud.githubusercontent.com/assets/38784/7256230/e277cafa-e81b-11e4-8053-14bac6024b05.png)

**Comment by pmailkeey** [comment]
NICE !

I wonder if you could distinguish barrier types into 2? categories: permeable and impermeable ? Barrier=kerb is a permeable example and wall/hedge/fence impermeable.

**Comment by pmailkeey** [comment]
I also wonder if iD can 'tidy up' data by finding areas and lines with 100% matched nodes and then combining the line tags with the area - hence deleting the separate line ?

**Comment by bhousel** [comment]
> I wonder if you could distinguish barrier types into 2? categories: permeable and impermeable ? Barrier=kerb is a permeable example and wall/hedge/fence impermeable.

We could give any of the barrier types own rendering styles, but I don't want to overdo it and make the map confusing.  The styles we use must support the task of editing, and not try to be a general cartography style that tries to render every possible thing.  Does knowing whether a barrier is permeable or not matter to a user editing - or do they just need to see that a barrier exists here?

> I also wonder if iD can 'tidy up' data by finding areas and lines with 100% matched nodes and then combining the line tags with the area - hence deleting the separate line ?

I think a lot of people would complain if we automatically merged perimeter tags with an area, because it kind of violates the [one feature, one element rule](http://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element).  Lots of people prefer these things to be separate.

**Comment by pmailkeey** [comment]
Is it not 'valuable' to be able to 'see' that the object depicted is correct in every aspect ? ID is the interface between mappers and the map and as such should indicate to mappers what the map contains. I'm kind of disappointed the OSM standard render doesn't show the whole content of the map. Only if errors are visible (it's taken me some magic to sort out Windermere - thanks to iD showing partially filled areas, it showed the outline had been drawn over more than once - and in faffing around with it it could well have been retraced twice more causing it to effectively have 3 outlines ('outers') yet there were only one inner per internal item. As the lake is quite complex, it is represented as a multipolygon. I spotted within that that it had 2 outers - one removed. The lake also had a separate line depicting the lake - so that in its entirety I deleted. Those 2 errors, iD could have 'eaten' itself automatically. For the purpose of editing, I think it is wrong to shy away from displaying the detail.

As for the one feature one element (thanks for the link) rule, automatically 'tidying up' would be doing exactly what that rule is about. An area surrounded by a fence is delineated by the presence of the fence - the fence is integral to the area. It is therefore correct to have the fence as part of the area rather than as a separate item as it is the fence that describes the area's boundary. This is only possible where the fence completely surrounds the area. An element may be a barrier. That barrier may comprise of a low wall, topped up with a fence above which is a hedge. This is not uncommon. It is one barrier so one element should describe the wall, fence and hedge aspects of the barrier - rather than describing three items in the same place.

Yesterday, I filled in quite a few farmers' fields. Generally, each field was independently mapped (one of them 'twice' as the field is split in two with 2 different crops!). There is also a strip of fields of a particular nature that aren't likely to be used any differently - so these I've combined into one area although there are fences and hedges making separate fields.

Is a fence part of a field ? In all honesty, there's no definitive answer; sometimes it is and sometimes it isn't. In the case where it completely goes around the field then I think it's fair to say that it is.

It's like we don't put walls around buildings as it is presumed the building has walls. However, one could argue that if a rectangular building had a wall missing, it would be reasonable to mark the other three walls as walls as well as having the building there?

**Comment by pnorman** [comment]
> think a lot of people would complain if we automatically merged perimeter tags with an area, because it kind of violates the one feature, one element rule. Lots of people prefer these things to be separate

Yes - line and area features should be separate objects.

@pmailkeey Perhaps you could edit your previous comment to be more concise and targeted at this specific issue, as it's not clear what you're proposing.

**Comment by pmailkeey** [comment]
Paul, all areas are bordered by lines. Such objects usually have parameters: Fill, Fill colour, shading, line colour, line width, line style and perhaps corner type (square, round, mitre).

Power pole, telecoms pole and street light are three different objects - but where one pole served all three purposes, all the tags would be set on the one element. I see no reason for making an area bounded by a line two objects when the single feature can be described as one object.

**Comment by pmailkeey** [comment]
Re walled garden: #319611760

I've removed the wall (in iD, I couldn't select the garden due to the wall) and added a wall tag to the garden. Now, I can chose the item in iD easily and select the tag (garden or wall) easily depending on which I want to edit. So that's a positive edit. The interesting thing is now that OSM Standard shows the single item as a garden and iD shows it as a wall ! P2 shows it as a wall too. OSM Query used to show the wall as a 'way' but now it's a garden.
