### ISSUE TITLE
upload photograph for digitized feature

### ISSUE THREAD

**Issue by mobina** [openstreetmap/iD#2593]
We are using iDeditor for crowd soucing. Now we are planning to give upload photo/Changephoto option in the editor. Is there any chance of including upload photo option  in near release of iD?

**Comment by bhousel** [comment]
We aren't going to add any photo uploading capability, as Mapillary already handles this nicely.  My recommendation is to take a look at the [mapillary_layer.js](https://github.com/openstreetmap/iD/blob/master/js/id/renderer/mapillary_layer.js)  as a starting point, and change the code in there to suit your needs in your fork.
