### ISSUE TITLE
Handle Bandwidth Exceeding errors better

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/iD#2594]
During a recent Mapathon, numerous computers were sharing the same IP address, and started triggering error 509 on the OSM API. 

This could be better communicated to users (tell em to go take a break ;)

Also, iD appeared to have allowed editing and uploading, despite download failing in an area. If data hasn't been downloaded for an area, seems sensible to not allow editing and uploads.

**Comment by bhousel** [comment]
This is a dup of #2262 - yeah we definitely need to communicate to the user when these api limit failures occur.
