### ISSUE TITLE
Background brightness widget is counter intuitive

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/iD#2595]
100% brightness is shown darkest in the widget, 25% brightness is shown lightest.

This is consistently confusing, even to experienced users. Can it be reversed?

**Comment by bhousel** [comment]
Yes, I've always wondered about this.. They seem backwards to me too.

**Comment by pnorman** [comment]
As with me. I always have to mouse over to see which one I want to tell people to use.
