### ISSUE TITLE
Click to select (item) failure

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2596]
I've a really weird problem with selecting items to edit. I've just opened an image with Windows photo viewer - and now I'm having to double-click items to select them in iD. The problem remains until I restart the browser (Chrome).
There's obviously some strange interaction with other other software - the issue has also arisen when I've opened another tab that has 'slippy' images.

It's a puzzle !

**Comment by bhousel** [comment]
Weird.  Is the other app (or a plugin) stealing focus?  So that the first click restores focus to Chrome and the second click actually does the thing you were trying to do?  This doesn't really sound like an issue with iD specifically.

**Comment by pmailkeey** [comment]
No, not a focus issue. the next object to be selected will have the same symptom. The other weird thing is that I've not pinned it down to a specific application running. There was one website I felt was linked to the problem (but maybe not!) and now Windows image previewer. Maybe it was the previewer all along - but only when that other webpage was loaded at the same time! The double-click to select was at a different rate than the double-click to zoom - such that too slow, I'd get the zoom without the selection !

**Comment by bhousel** [comment]
Closing this for now, as I don't think it's an iD issue..
