### ISSUE TITLE
Recognize by header when there's no Bing coverage

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/iD#2597]
So Bing spits out a `X-VE-Tile-Info: no-tile` header when there is no imagery at given zoom level. I propose that in such case the user gets a message to check other layers - if there are any country- or region-specific. My rationale is that there's still no perfect coverage for Bing in eg. Poland, whereas Geoportal.gov.pl (which is included in imagery presets) covers the whole country.

**Comment by bhousel** [comment]
Does the user really need a message?  It seems like the imagery not being there would make it obvious enough that the user would consider switching background sources.

**Comment by jfirebaugh** [comment]
Also, there's no way to read HTTP headers for `<img>` elements. So, even if there were a strong case for doing this, it simply isn't possible.
