### ISSUE TITLE
background brightness configured by link arg

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/iD#2599]
allow background brightness level to be set by link argument. OSMTM could set this level, depending on quality of background imagery in an area.

**Comment by bhousel** [comment]
I'm pretty reluctant to override the user's preference here.  If it were me, I'd be annoyed if the software decided this for me.

**Comment by mikelmaron** [comment]
Fair enoughMikelAt Apr 21, 2015, 4:00:51 PM, Bryan Housel wrote:I'm pretty reluctant to override the user's preference here.  If it were me, I'd be annoyed if the software decided this for me.
