### ISSUE TITLE
Changeset comment title

### ISSUE THREAD

**Issue by ethan-nelson** [openstreetmap/iD#2600]
I have been asked a few times what "commit message" is in the iD editor. This is especially the case when there is a centralized set of instructions for new editors, or perhaps a suggestion to a specific user, to include a changeset comment.

Would you all be open to changing [this label](https://github.com/openstreetmap/iD/blob/b6a3e8a58cf8877d6a470cdf1a597dfdb6003e6a/data/core.yaml#L194) from "Commit message" to "Changeset comment"?

**Comment by bhousel** [comment]
Yes, sounds reasonable to call this what everyone else calls it.
