### ISSUE TITLE
Somehow improve conflict handling, especially with multiple people editing (or touching) the same feature

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#2601]
This happens a lot when we are doing mapathons so many people are editing the same general area -- even if people don't edit anything outside their bounding box, if they edit a way that goes outside the tile (say, a road or river) often somebody else will be unknowingly editing it simultaneously, which means one person's edits get wiped out wholesale. It also happens even if you just join something to that existing way, since I guess you are adding a node to that way.

It would be great if there were some way to make the error handling easier -- maybe it warns you if you select a huge thing, or lets you revert selectively?

The way around it, as best I can tell, is selecting the node or way ID from the error message, going to OSM and finding that way/node, then either just deleting it (not ideal) or hitting undo back past that point, or refresh on the screen, then refresh on the popup you get (I think?) And that doesn't always seem to work, sometimes users are just out of luck and all of their edits get erased.

**Comment by bhousel** [comment]
Yes we did this!  Save time conflict resolution is in #2525 which was merged about a month ago and will be in the next release.  It's been available for a little while on the master branch iD mirror here: http://openstreetmap.us/iD/master/   

I've heard good feedback from people testing there, so I think I'll probably make an official release for the main openstreetmap site this week.

**Comment by aawiseman** [comment]
Oh wonderful! Thanks!
