### ISSUE TITLE
Overview Map in idEditor

### ISSUE THREAD

**Issue by mobina** [openstreetmap/iD#2602]
We are planning to add overview map for my iDeditior. How can we implement this or any clue to implement?

**Comment by aaronlidman** [comment]
@mobina This was recently implemented by @bhousel.

![screen shot 2015-04-22 at 10 27 47 am](https://cloud.githubusercontent.com/assets/58878/7270154/3f7fa97a-e8da-11e4-85c0-316047b05693.png)

You can try it out here: http://openstreetmap.us/iD/master
- When the map loads, press `/` and a mini-map will appear in the top left corner.

This will be released to openstreetmap.org in the next release. Soon.

**Comment by mobina** [comment]
Thanks You so much.. Its worked for me
