### ISSUE TITLE
Deprecate tag tourism=bed_and_breakfast

### ISSUE THREAD

**Issue by tyndare** [openstreetmap/iD#2605]
When we enter a "Tourism" point, and click on the "Type" combo box, we have the choice for "bed and breakfast" which is translated into this deprecated tag:
http://wiki.openstreetmap.org/wiki/Tag:tourism%3Dbed_and_breakfast

Example here: https://www.openstreetmap.org/node/1429480651

I think that deprecated tag should not be proposed in the list, or at least not without a warning.

**Comment by bhousel** [comment]
iD doesn't have `tourism=bed_and_breakfast` as a preset.. Can you reach out to that user via changeset discussion or private message and ask them if they perhaps typed it in manually?

**Comment by tyndare** [comment]
Right, it is not in the preset. But it is the second to last value proposed by iD in the Type combo box when I create a tourism=yes point. I imagine this may comes from taginfo values.
I'll contact that user.

**Comment by bhousel** [comment]
> I imagine this may comes from taginfo values.
> I'll contact that user.

Thanks!  You're right that we are just pulling the most popular `tourism=*` values from taginfo (and indeed `guest_house` is listed far higher on the list than `bed_and_breakfast`).  Once the values are converted over to the new tag, it won't appear in this list anymore.

**Comment by daanvr** [comment]
I was the user who used 'bed_and_breakfast' wrongly. Is it because of my lak of Open Street Map knowledge or should I be abel to use any proposed value in the ID editor?

**Comment by bhousel** [comment]
@daanvr, you can use any values that you want in OpenStreetMap.

If somebody now prefers `guest_house` to `bed_and_breakfast`, they are free to change it.  If this is in fact a deprecated tag, somebody should propose a mechanical edit or maproulette challenge to cleanup all the old values, and until that happens, really nobody has any right to complain about what you did.
