### ISSUE TITLE
Nearly junctions

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2606]
Where a point is close to a line, could iD prompt for a connection confirmation ? If the connection request is denied, should iD suggest moving the point further away for clarity and offer an automated process to do that (a calculated distance).

The point of this being to avoid the map showing apparently connected highways which are in fact not connected. The issue arising out of the fact that highway lines have a width - which at certain zoom levels may overlap nearby points.

**Comment by jfirebaugh** [comment]
As a design guideline, iD doesn't use modal prompts. They interrupt editing flow and users quickly learn to click through and ignore them.

iD already shows a different rendering for connected versus unconnected highways. Connections are shown with a grey filled dot, unconnected with a white dot or no dot.

**Comment by pmailkeey** [comment]
iD gives 'wrong prompts' in the tag fields. It's 'not happy' with either 'ref' or 'farm' but wants to extend tag names causing me to need to use the delete key too often.

Irrespective of your comments, the issue still exists - that highways could look connected when not. For a (bad example)

![image](https://cloud.githubusercontent.com/assets/11827386/7346719/1df6a6a2-ecd9-11e4-823b-9f1f739c5465.png)
If it wasn't for a line of trees across the road, it looks like Flinders St continues in a long line - and my query is whether iD could move the end of the separate bit of Flinders St further away for clarity.

**Comment by pnorman** [comment]
You've shown a screenshot of a rendered map, not iD.

**Comment by pmailkeey** [comment]
Are you saying the renderer should deal with this issue ?

**Comment by pnorman** [comment]
I'm saying you're not showing an iD bug. There might be an iD bug, but a screenshot of something other than iD is not helpful.
