### ISSUE TITLE
Roundabouts in oppose direction

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [openstreetmap/iD#2607]
In the past iD had a button to make a roubabout go in the oppose direction, now it doesn't, I don't like to put -1 on oneway. Can it be readded?

![roundbaout](https://cloud.githubusercontent.com/assets/3578953/7333121/959f0462-eb38-11e4-8e5c-f4f18b141737.jpg)

**Comment by tyrasd** [comment]
It's already fixed (see #2484), but the respective code hasn't made it into a stable release yet.
