### ISSUE TITLE
Simplifying complex data input by tabulation

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2608]
![image](https://cloud.githubusercontent.com/assets/11827386/7334006/1aff79e6-eb7c-11e4-93e5-3b84072620df.png)

![image](https://cloud.githubusercontent.com/assets/11827386/7333991/23708e4a-eb7b-11e4-886e-c77170879e68.png)

A suggestion of showing highway data in a tabular form where there's a column for each lane and a row for each attribute.

In an effort to encourage people to include lane information such as sidewalks, turn lanes and different restrictions on the use of each lane as applicable.

**Comment by jfirebaugh** [comment]
I can't understand what you are requesting here. Can you try to explain again?

**Comment by pmailkeey** [comment]
Current tags are listed in 2 columns. Fine for most things but where there are multiple lanes, each of which can have its own attributes, would it not be easier to understand if the details for each lane was in one column ? so a column for each lane where attributes can be different.

**Comment by jfirebaugh** [comment]
Okay, there's an existing issue for support for lane tags: #387. Please post your suggestions there.

**Comment by pmailkeey** [comment]
can you move this onto the end of that thread then ?
