### ISSUE TITLE
hard to move connected areas

### ISSUE THREAD

**Issue by PalmerAL** [openstreetmap/iD#2609]
If there are two connected areas, it is extremely hard to move them to a new location. The problem is that there is no way to select both areas at the same time, and if you select one area, moving it causes the other area to change shape. Either of the following could solve this:

 - allow selecting multiple areas at the same time
 - don't move the original area when dragging an area connected to it.

I'll try to find an example when I have time.

**Comment by bhousel** [comment]
You should be able to shift-click on areas to select multiple at a time.  While holding down shift, clicking will add or remove the feature from the selection group.

**Comment by PalmerAL** [comment]
Oh, I didn't know that. Thanks!
