### ISSUE TITLE
iD beta / master URL lat Long in the wrong order

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2610]
Beta:

http://openstreetmap.us/iD/master/#background=Bing&map=21.62/0.24891/51.46566

'normal':

https://www.openstreetmap.org/edit#map=21/51.46566/0.24891

Which 'agrees' with Google etc.

Is it just the 'master' access option that has the lat and long in the wrong order - in other words, when the beta version is approved and becomes accessible through the usual osm interface, will the lat long be in the correct order ?

**Comment by bhousel** [comment]
Yes, when iD is embedded in an iframe on the main OSM site, the urls will use lat/lng.
There's no right or wrong way to do it, see also issue #1750
