### ISSUE TITLE
Need to revisit russian translation of education steps

### ISSUE THREAD

**Issue by Sergeant007** [openstreetmap/iD#2612]
Most probably it's quite old and a lot of subjects have changed. For example, "Улица" has been renamed to "Дорога между домами" and so on. This really makes life of newcomers much harder.

**Comment by jfirebaugh** [comment]
iD translations are handled through [Transifex](https://www.transifex.com/projects/p/id-editor/) -- feel free to create an account there and help out with the Russian translations.
