### ISSUE TITLE
cannot see background map for humanitarian project in Nepal

### ISSUE THREAD

**Issue by SednaBoo** [openstreetmap/iD#2614]
I select "contribute," and i see black space.  I try adding:

tms[22]:http://hiu-maps.net/hot/1.0.0/gorkha-apr2015-flipped/{zoom}/{x}/{y}.png

and:

http://hiu-maps.net/hot/1.0.0/gorkha-apr2015-flipped/{zoom}/{x}/{y}.png

And neither work.  Using Id on firefox.

**Comment by bhousel** [comment]
That's odd - the server is returning 200 OK but empty images for everything.  Wish I could be more helpful.

I was able to get the instructions here working for yesterday's DigitalGlobe imagery:
https://www.mapbox.com/blog/nepal-earthquake-imagery-0427/

It currently only works around Kathmandu at zoom 12.5 and higher, though I suppose better imagery is becoming available all the time.

**Comment by SednaBoo** [comment]
I was working on the map near Gorkha.  If i go to the image link directly it has all sorts of odd errors.
