### ISSUE TITLE
basemap.at overlay missing

### ISSUE THREAD

**Issue by rorso** [openstreetmap/iD#2616]
the map overlay "basemap.at" for Austria is not visible in the editor anymore. Selecting this overlay results in a black background like "none". Perhaps the recent change to PNG tiles in the "basemap.at" service causes this behaviour.
Please make this overlay available again, as it is the most valuable source for current building data.

**Comment by bhousel** [comment]
Looks like this was already fixed by @tyrasd in d2a05f5
