### ISSUE TITLE
Cannot Save changes 

### ISSUE THREAD

**Issue by DavidSmith2125** [openstreetmap/iD#2619]
Error: Version mismatch: Provided 1, server had: 2 of Node 3479021810

**Comment by bhousel** [comment]
Conflict resolution is available in the latest iD version which is just released, so your best option may be to copy the URL and close your browser, then reopen it and revisit that URL whenever iD is updated with the version 1.7.1 (It should be sometime today, and I'll reply to this thread when it's available).  

Then restore your history, try to save, and you should be able to use the conflict resolution UI described in #2525

**Comment by bhousel** [comment]
Just an update: looks like 1.7.1 is live on openstreetmap now - can you try refreshing your browser and save your changes again.  Let me know if it works for you!
