### ISSUE TITLE
Support for only_straight_on turning restrictions

### ISSUE THREAD

**Issue by socketpair** [openstreetmap/iD#2622]
Today, we can easily add turn restrictions named no_\* but only_\* can be added only by hand as creating restriction and then fixing its type.

It will be nice if these restriction tyoes can be switched like second clicking on that. Note that shift click is not acceptable for ipad.

**Comment by bhousel** [comment]
There's some discussion on #224, @jfirebaugh knows more what's involved here.

**Comment by afmenez** [comment]
That issue is closed already.  i liked the suggestion to cycle red/green/blue on each click.  It is not mentioned there, but maybe there should be an "optimization" phase were redundant restrictions are eliminated (if I have an only_forward I don't need a _no_left and no_right restrictions).

**Comment by jfirebaugh** [comment]
No plans to add a UI for this; I'm happy with the current balance between complexity and functionality.

**Comment by bhousel** [comment]
Reopening this.. We'll probably add it, but will need to be careful to preserve the previous state of the intersection so we can cycle through `only_` states without destroying all the `no_` restrictions.  A lot is moving on turn restriction tagging to support #2346, which will land soon.

**Comment by bhousel** [comment]
This was done in #2346!
