### ISSUE TITLE
Automatically propose to square or round buildings

### ISSUE THREAD

**Issue by severinmenard** [openstreetmap/iD#2624]
Many beginning mappers forget to square or round their buildings and it takes a lot of time for other mappers to clean this. iD could propose, as soon as the building key is selected, to square or round the buildings.

**Comment by bhousel** [comment]
I'm working on an orthogonal drawing mode that will make it much faster to draw square buildings.  I'll extend it to round buildings too (like for huts or other shelters) sometime later, if I can come up with a reasonable UI for them.
see #528

**Comment by severinmenard** [comment]
From my experience with teaching JOSM and the building tool, beginners may totally skip the building school, even if you taught them more than once. I think you will not prevent the unsquare issue with people using only the polygon drawing tool.
