### ISSUE TITLE
Apostrophe

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2625]
Just a query, what character(s) does iD accept for an apostrophe ?

On 1 May 2015 at 18:30, Imre Samu <pella.samu@gmail.com> wrote:
> .. McDonald's  problem...

Please don't forget the   true "McDonald's" problem!  It is a content encoding hell.
and very hard to detect by any ordinary field mappers.

  #1.
name="McDonald’s"    ( count=126 )  U+2019 ’ e2 80 99 "RIGHT SINGLE QUOTATION MARK"
http://taginfo.openstreetmap.org/tags/name=McDonald%E2%80%99s
http://overpass-turbo.eu/s/97c

 #2.
name="McDonald´s"    ( count=40 )   U+00B4 ´ c2 b4 "ACUTE ACCENT"
http://taginfo.openstreetmap.org/tags/name=McDonald%C2%B4s
http://overpass-turbo.eu/s/97e

 #3.
name="McDonald's"   ( count=14039)   U+0027 ' 27 "APOSTROPHE"
http://taginfo.openstreetmap.org/tags/name=McDonald's

Regards,
 Imre

_______________________________________________
talk mailing list
talk@openstreetmap.org
https://lists.openstreetmap.org/listinfo/talk

**Comment by bhousel** [comment]
Anything UTF-8

**Comment by pmailkeey** [comment]
Is it something iD could standardise to the correct apostrophe where a wrong one is used?

**Comment by jfirebaugh** [comment]
Yes, iD has many build in presets for common chains with standardized spelling:

![image](https://cloud.githubusercontent.com/assets/98601/7438798/79264c00-f038-11e4-9963-36dccd1619f4.png)
