### ISSUE TITLE
Saving fails when some of the nodes is not found

### ISSUE THREAD

**Issue by oiva** [openstreetmap/iD#2626]
I'm having trouble saving different change sets. The browser launches a GET request to OSM API for the nodes I've edited, but apparently some of them is not found?

`http://www.openstreetmap.org/api/0.6/nodes?nodes=3492811281,3492811281,3492811286,3492811286,3492811312` returns 404.

This prevents me from saving. ID-editor says "Errors occurred while trying to save: Server returned status code 404"

In one case I had over 50 changes that could not be saved. It turned out that only one building blocked the save, and once deleted I could redo the edits and save them successfully. It would have been nice if the other edits could have been saved without redoing them.

**Comment by oiva** [comment]
Actually now that I look at the GET request, it seems some of the IDs are duplicated. If I remove the duplicated IDs, the request works.

**Comment by bhousel** [comment]
Thanks for the report and for figuring out the issue so quickly!  I'll push out a fix for this asap.

**Comment by oiva** [comment]
@bhousel: I'm curious if this could / should also be fixed in the API? I'm not 100% how a REST API should behave when asked same IDs multiple times in one request. My gut feeling is that it could return each unique element once, but I'm not sure if it would break something.

**Comment by bhousel** [comment]
> I'm curious if this could / should also be fixed in the API? I'm not 100% how a REST API should behave when asked same IDs multiple times in one request.

Yeah it's definitely not what I would expect the API to do :)
I'll put the quick fix into iD, and if I have time I'll fix it there too and reference this issue.

**Comment by bhousel** [comment]
(see #2628 for temporary workaround that should allow saving)

**Comment by pnorman** [comment]
regardless of the changes in https://github.com/zerebubuth/openstreetmap-cgimap/commit/0d62c3228a8bfa53b0c390cecfd5504d6ee3f53f it's probably best to keep de-duplicating in iD to cut down on the HTTP requests needed for long lists of nodes

**Comment by bhousel** [comment]
> regardless of the changes in zerebubuth/openstreetmap-cgimap@0d62c32 it's probably best to keep de-duplicating in iD to cut down on the HTTP requests needed for long lists of nodes

Yes, definitely agree.  I even think we should up the chunk size [here](https://github.com/openstreetmap/iD/blob/master/js/id/core/connection.js#L77) for browsers that we know support longer urls.  I chose 150 conservatively to fit the url under 2MB. [See also](http://www.boutell.com/newfaq/misc/urllength.html)
