### ISSUE TITLE
Save button doesn't work + 404 code

### ISSUE THREAD

**Issue by alluk** [openstreetmap/iD#2628]
I have 834 edits done with iD 1.7.1 editor (the newest Firefox as a browser) but this ***** program don't let me save the edits. When I'm watching the list of edits and have the Save button in front of me, the button doesn't just do anything. At the first time it gave me an error code 404 Page cannot be found, even all the other web pages were working. I know, should save more regularly, but this time I didn't.

After this I will never use this program any more, but before that I'd like to get my edits out or even save them to the map.

**Comment by shrddr** [comment]
Same here. Save button generates a request with duplicate node id's: http://www.openstreetmap.org/api/0.6/nodes?nodes=277098967,277098969,277098970,277098973,277098974,277098976,277098967,...

**Comment by bhousel** [comment]
I'm really sorry that you had this issue.  This is a dup of #2626, and I'm going to push a patch for it tonight.

In the meantime, here is how you can get your edits to save:

First, close the save dialog.

Now, we're going to replace the problem code.  
Under Firefox's menu, choose "Developer" and open "Web Console" and enter the following:
```
cd('#id-embed')
```

Then enter:
```
id.connection().loadMultiple = function(ids, callback) {
        function chunk(arr, chunkSize) {
            var result = [];
            for (var i = 0; i < arr.length; i += chunkSize) {
                result.push(arr.slice(i, i + chunkSize));
            }
            return result;
        }

        _.each(_.groupBy(_.uniq(ids), iD.Entity.id.type), function(v, k) {
            var type = k + 's',
                osmIDs = _.map(v, iD.Entity.id.toOSM);

            _.each(chunk(osmIDs, 150), function(arr) {
                id.connection().loadFromURL(
                    'http://www.openstreetmap.org/api/0.6/' + type + '?' + type + '=' + arr.join(),
                    function(err, entities) {
                        if (callback) callback(err, {data: entities});
                    });
            });
        });
    };
```

Then you can the save again.  Please let me know if this works for you..

**Comment by bhousel** [comment]
Thanks all, 1.7.2 is live on openstreetmap now, so anyone with edit history can refresh the page, restore the history, and should be able to save.

**Comment by alluk** [comment]
Thanks's for all (and sorry for a delay when it comes to an answer)! I got it to work with these instructions.
