### ISSUE TITLE
Map notes

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/iD#2629]
Hello,

thank you so much for this editor! It is a huge help when training people for the first time for OpenStreetMap, and this is so important.

One thing which is really missing, in order to get people into mapping, and to have a complete mapping workflow, is a map notes (https://wiki.openstreetmap.org/wiki/Notes) integration as there is for JOSM (https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Notes).

Thank you.

**Comment by bhousel** [comment]
Thanks, glad you like the editor!  Some work started on adding an OSM notes layer a while ago (see #1895), but it's pretty much stalled.  I agree we should finish it up and make this a priority.

**Comment by konfiot** [comment]
I agree, that would be much easier

**Comment by brycenesbitt** [comment]
+1 on map notes.  I'm working with a group that is using iD, and creating certain map notes at the same time.  It's a barrier to understanding that they have to write down the node number, flip to the OSM home page, enter the node number, find the place, create a map note.

**Comment by xamanu** [comment]
I was just conducting two workshops for people from rural areas in Kyrgyzstan. They had no big computer experience. The first workshop we did with JOSM and it was very hard for them to get into it. The second one we did using iD, which was a lot better, but the only big missing issue was map notes support. Surveying data with map notes, on the other side, seems just to be the perfect workflow.

**Comment by boothym** [comment]
At the very least could we get an icon within iD showing the location of a note? Sometimes you click edit and want to know exactly where a note was placed, especially if it's a busy area of the map.

I do usually middle click the edit button to open iD in a new tab, but even then it's not always easy to figure out where the note is.

**Comment by homersimpsons** [comment]
@boothym when you are in the note : openstreetmap.org/note/xxxx this one is centered in the map (no map= part in the URL) so when you edit it with iD the note remain centered, you can start zooming using the '+' button to hold the center.

**Comment by avanc** [comment]
Is this feature not on the development roadmap anymore?
There are a lot of notes in my area by another user:
https://www.openstreetmap.org/#map=13/52.3784/10.0784&layers=N

The approach of @homersimpsons is a lot of overhead for so many notes.

**Comment by thomas-hervey** [comment]
@avanc I will be working on this feature this summer as a Google Summer of Code project with the supervision of @bhousel. I can keep you in the loop with my progress and welcome any suggestions.

**Comment by avanc** [comment]
@thomas-hervey Great to hear that development of this feature continues. Let me know when you need a beta tester.

**Comment by thomas-hervey** [comment]
Hello again everyone. @bhousel and I have been discussing the UI a bit for the new notes feature. We likely don't want to add a 'add note' button to the top toolbar, but it may still need to be a mode, much like editing points, lines, areas. I've considered adding it to the bottom of the menu-controls list (like is is on osm.org). Thoughts?

**Comment by homersimpsons** [comment]
All like the osm.org website, in the right side bar, seems good to me (select whether or not the notes should be shown, add note). If it's possible show the active note (even if note layer is disabled, just like osm.org)

**Comment by thomas-hervey** [comment]
Hello everyone,
So I have made some progress on the notes, but I ran into a few snags displaying them. Therefore, I cloned a new copy of iD (which has solved some other issues), and I will be committing small steps from now on. Check out the [notes branch](https://github.com/openstreetmap/iD/tree/notes).

**Comment by bhousel** [comment]
This was done in #5107 and #5162  🎉
