### ISSUE TITLE
Server returned status code 404

### ISSUE THREAD

**Issue by sebbehr** [openstreetmap/iD#2630]
While I try to save my updates, I always receive this error report:

Please ensure you are connected to the internet.
Server returned status code 404

I am hundert-percent sure that I am connected to the internet.

So, where is the problem? Had this never before.

**Comment by EwenH** [comment]
Appears to be the same for me. 
**Process:**
* Open ID, 
* Make changes (I am adding areas connected to other recent areas)
* Save
* Error appears 
 * Errors occurred while trying to save
 * Please ensure you are connected to the internet.
 * Server returned status code 404
* It does appear some or all of the change set is executed.

I switched browsers from FF to Chrome and it appeared to work but now I am receiving the same in Chrome.

The error in my instance appears to come from http://www.openstreetmap.org/api/0.6/nodes?nodes=3494208518,3494546867,3494196556,3494196532,3494196530,3494196531,3494211668,3494196530,3494196540,3494546874,3494546875,3494546876,3494546877,3494546873,3494546872,3494546871,3494546868

**Comment by sebbehr** [comment]
Okay, I have the same issues. I also use chrome and I also did edits in Open ID.

**Comment by hanchao** [comment]
same issues. Chrome 39.0 return 404. Safari 8.0 ok

**Comment by shrddr** [comment]
There is a temporary fix here https://github.com/openstreetmap/iD/issues/2628

**Comment by ciubex** [comment]
I used on Chrome bellow workaround, based on #2628 temporary fix.

```javascript
id.connection().loadMultiple = function(ids, callback) {
        function chunk(arr, chunkSize) {
            var result = [];
            for (var i = 0; i < arr.length; i += chunkSize) {
                result.push(arr.slice(i, i + chunkSize));
            }
            return result;
        }

        _.each(_.groupBy(_.uniq(ids), iD.Entity.id.type), function(v, k) {
            var type = k + 's',
                osmIDs = _.map(v, iD.Entity.id.toOSM);

            _.each(chunk(osmIDs, 150), function(arr) {
                id.connection().loadFromURL(
\\ HTTPS or HTTP depends by the current connection
                    'https://www.openstreetmap.org/api/0.6/' + type + '?' + type + '=' + arr.join(), 
                    function(err, entities) {
                        if (callback) callback(err, {data: entities});
                    });
            });
        });
    };
```

**Comment by bhousel** [comment]
Thanks all, 1.7.2 is live on openstreetmap now, so anyone with edit history can refresh the page, restore the history, and should be able to save.

**Comment by EwenH** [comment]
Thanks for the rapid fix @bhousel

**Comment by bhousel** [comment]
> Thanks for the rapid fix @bhousel

You're welcome!  But I think in this case @oiva is the real hero...
https://github.com/openstreetmap/iD/issues/2626#issuecomment-98346966
