### ISSUE TITLE
entity n926428439 not found

### ISSUE THREAD

**Issue by shrddr** [openstreetmap/iD#2631]
Could not save due to a 404 error yesterday, closed the browser tab. Opened iD today, restored the session with 163 edits, still can't save. No error shown after clicking the save button. In developer console: 

Uncaught Error: entity n926428439 not found
iD.Graph.entity @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:24106
iD.Graph.childNodes @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:24166
(anonymous function) @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:22267
reduce @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:10444
withChildNodes @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:22264
save @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:22281
event @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:757
(anonymous function) @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:29425
(anonymous function) @ id-a71417bd3856e58b0f2540f0ac7f6c6a.js:1639

Using Chrome Version 42.0.2311.135 m

**Comment by shrddr** [comment]
OK so I found a workaround for that. Find the missing node on the map http://www.openstreetmap.org/node/92642843 and touch it with the editor (move+undo). Guess that adds the missing node to entities list.

**Comment by bhousel** [comment]
Yes, this is a consequence of a known issue: #2142 
When restoring your history, iD will restore your edited way, but not the un-edited child nodes that go with it.
