### ISSUE TITLE
show "changeset tags" to the user before saving changes.

### ISSUE THREAD

**Issue by ImreSamu** [openstreetmap/iD#2633]
related to #2449  ( + privacy )

For  greater transparency,  it would be useful showing to the user  the  "changeset tags" before saving changes.  ( or create an options to see )  

statistics:
-   https://gist.github.com/ImreSamu/0fc3b8015e6dd16595c5

**Comment by pnorman** [comment]
I'd like to be able to add changeset tags so we can properly tag changesets in iD, but believe the privacy issue is a red herring. Presumably the full changeset tags aren't going to be shown by the standard workflow, only if a user decides to add/remove tags, vaguely similar to the JOSM way of not showing changeset tags by default. Most users won't see them, so it doesn't change their awareness of the details of what is uploaded.

**Comment by bhousel** [comment]
@ImreSamu very cool!

I do see in the report that we should probably be more consistent with the locale (e.g. having both 'en-us' and 'en-US' in the results is sloppy, so I can just lowercase them all).

Agree, @pnorman  I think we addressed the privacy concerns already in #2559.  Maybe I can find  a way to put a collapsed raw tag editor on the save screen, so users can actually add their own changeset tags.

**Comment by ImreSamu** [comment]
My latest osm changeset statistics : https://gist.github.com/ImreSamu/2b31315ef2328cb482c7
