### ISSUE TITLE
Two background layers at once and image slider tool

### ISSUE THREAD

**Issue by cgiovando** [openstreetmap/iD#2635]
It would be nice to be able to add two background layers at once and have an image slider tool to swipe between the images. The main use of this feature would be for before and after comparison when two imagery layers of the same areas are available for different moments in time. This would allow the user for quick change detection visual analysis and understand what new features could be mapped.

The feature would be implemented either with a "swiping" handle or by flickering (rapidly switching) between the two background images with a keyboard shortcut.

Here is an [example](http://demosthenes.info/blog/819/A-Before-And-After-Image-Comparison-Slide-Control-in-HTML5) of what I mean by image slider.  It is also a feature used or [wished for](http://gis.stackexchange.com/questions/87770/qgis-quickly-switching-overlapping-raster-images) in GIS and image analysis software (see [swipe](http://resources.arcgis.com/en/help/main/10.1/index.html#/Interactively_reveal_rasters_using_the_Swipe_Layer_tool/009t00000099000000/) and [flicker](http://resources.arcgis.com/en/help/main/10.1/index.html#/Revealing_rasters_using_the_Flicker_tool/009t0000009m000000/) methods in ArcGIS).

**Comment by bhousel** [comment]
We didn't build a slider tool, but #2854 provides the ability to quickly switch between 2 backgrounds.
