### ISSUE TITLE
The bigger picture can't be edited - bug

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2636]
![image](https://cloud.githubusercontent.com/assets/11827386/7550579/305eee0a-f65f-11e4-8c2a-b130ecd0d572.png)

Please fix this 'bug'.

**Comment by jfirebaugh** [comment]
This is intended behavior; see #542 and 874a3e2ad67e77e8896ff9580d40bf990eaed974.

**Comment by pmailkeey** [comment]
I suspected the intention hence bug in inverted commas. Please add an option to disable the restriction then - either via the pop-up message (change 'can't' for 'are you sure?'  or other less publicised option.
