### ISSUE TITLE
Higher resolutions in Bing imagery not showing in iD

### ISSUE THREAD

**Issue by planemad** [openstreetmap/iD#2640]
Came across a lot of offset building footprints create in iD, while editing in JOSM. When looking into the area in iD, I noticed that the imagery was overzoomed and was not switching the the higher resolution imagery I was seeing in JOSM.

Not sure if this is a bug, but having users of JOSM and iD seeing different imagery at the same zoom level can lead to inconsistent data like this. 

OSM link: https://www.openstreetmap.org/#map=19/16.81692/81.53699

![screenshot 2015-05-12 17 00 38](https://cloud.githubusercontent.com/assets/126868/7586248/a99f17f2-f8c8-11e4-9f0d-8ab24334e220.png)

[GIF comparing the switching of imagery in JOSM and iD (9mb)](https://cloud.githubusercontent.com/assets/126868/7586154/7f02ac3a-f8c7-11e4-8b4b-201c8e2622ee.gif)

**Comment by bhousel** [comment]
Yeah JOSM is definitely switching imagery beyond z19.. I don't know what they are doing, but I'm pretty sure that imagery is not coming from Bing. 

I did try requesting tiles from Bing for this area, but they are not returning anything for z19, so iD overzooms.

For example, [this request](https://ecn.t2.tiles.virtualearth.net/tiles/a1233102333133213103.jpeg?g=587&mkt=en-gb&n=z) returns a 200 response but `X-VE-Tile-Info: no-tile`.

**Comment by planemad** [comment]
Cross posted on JOSM trac for further details https://josm.openstreetmap.de/ticket/11431
