### ISSUE TITLE
please add preset for amenity=biergarten

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#2641]
Is there a reason amenity=biergarten is missing in the presets?

**Comment by bhousel** [comment]
No specific reason why it's not included.  There are [around 7000](http://taginfo.openstreetmap.org/tags/?key=amenity&value=biergarten) now so it seems reasonable to create a preset for it.  :beer:

**Comment by KathleenLD** [comment]
:beers:
