### ISSUE TITLE
Feature request: Hotkeys for tags

### ISSUE THREAD

**Issue by their** [openstreetmap/iD#2642]
This is a follow-up to a brief conversation with Bryan. Google Chrome browser extension which shows the basic functionality for this feature: https://chrome.google.com/webstore/detail/osm-id-browser-tools/fmgcpkpdhcbfjnleinolnagnlpabiplc, https://github.com/their/OSM-iD-Browser-Tools.

The features desired are something like the following: 1) user may edit keybindings for tagging hotkeys; 2) user may set a list of tags (key/value pairs) for each tagging hotkey and/or create tagging profiles; 3) user may optionally add an "action" to a tagging hotkey which will run after the area has been tagged (any of create new point, line, or area); 4) user may optionally select to have Orthagonalize() called as part of the keybinding on the areas (on lines?). 

1) It seems that there are many hotkeys already set up in iD. Does the hotkey behavior for adding tags already exist, and/or do you know of anyone who already has a program to do this? Similar functionality exists in JOSM where it seems users are able to add tags using CTRL+R which copies the tags of one area to another area.

2) How might you go about programmatically editing tag information for selected areas? It is acceptable to edit the tags object for id.graph().entities[ `selected area id` ].tags? When the map redraws it correctly adds the tags from the tags object here. Is it simply a matter of making a call to re-render the map, something like .render() or .Render()? As we know the tags we would like to add, it does not appear to be necessary to make sanity-checking calls to the tags, such as a GET request (https://taginfo.openstreetmap.org/api/4/key/values?filter=ways&key=idp%3Acamp_site&page=1&rp=25&sortname=count_ways&sortorder=desc). Is this correct? Is it okay to change tag information, call the .Orthagonalize() function, or make other changes to the user's selection, when the user's selection is not complete, i.e., when a user is still in the process of creating an area or line and the user has not closed the area / line?

**Comment by bhousel** [comment]
I think the idea of having a Chrome extension for iD power tools is awesome!  

I'm following your repository now, so if you raise any issues there I will see them and try to point you in the right direction.  

I wrote up a [gist](https://gist.github.com/bhousel/0af881a621a2efb83719) that does what you're trying to do... This code will take any selected areas and change them into buildings when you press ⌘B (or Control-B on Windows/Linux).  It seems likethe sort of thing a person doing a HOT task might want.

So, because I know iD can be a bit impenetrable, I'm going to paste the gist code here but heavily comment it to explain what all the parts do.  I hope it's helpful..

```javascript
// Setup some global variables..
context = id;
addTags = { building: 'yes' };
removeTags = ['area','natural','landuse'];
 
// Define the callback function.  It will get bound to the key we select below..
function changeTags() {
    var actions = [],

// 'context' is the main iD object in the active window..
// see js/id/id.js for what context can do.
// Get all selected OSM IDs, run the 'entity' function on each one to get its Entity object..
// Then filter them so that we are only selecting areas..
// '_.' is a library called lodash that provides some useful high level functions..
        entities = _.filter(_.map(context.selectedIDs(), context.entity), 
            function(entity) { return entity.geometry(context.graph()) === 'area'; });
 
// With each entity, create an 'action' to change its tags..
// (actions are functions that take the editing graph and update it somehow)
    _.each(entities, function(entity) {

// Get the original tags from the entity..
// _.clone them first because _.merge and _.omit want to work on the original object..
// _.merge brings in the addTags, _.omit leaves out the removeTags..
        var newTags =  _.omit(_.merge(_.clone(entity.tags), addTags), removeTags);

// Luckily there is already a 'ChangeTags' action that does exactly what we need..
// see js/id/actions/change_tags.js
        actions.push(iD.actions.ChangeTags(entity.id, newTags));

    });
 
// If we have actions in the array, call 'context.perform' to perform them..
// 'context.perform' runs all the action functions in one undo-able step..
// I call it with 'apply' because I want to pass an array instead of an argument list..
// The final argument can be an optional annotation that will appear as the undo text..
// The 't()' function takes some standard text from data/core.yaml and translates it..
    if (actions.length) {
        actions.push(t('operations.change_tags.annotation'));
        context.perform.apply(context, actions);
    }
}

// Bind the 'changeTags' callback function to a key.
// iD.ui.cmd is a utility function that changes ⌘ on Mac to Control on Windows/Linux..
// Instead of iD.ui.cmd('⌘B'), we could also just pass a single keychar like 'B'.. 
myKeybinding = d3.keybinding('changeTags')
    .on(iD.ui.cmd('⌘B'), changeTags);
d3.select(document).call(myKeybinding);
```


Also, you mentioned 'orthagonalize'.. iD has an action for that too, so if you want your hotkey to perform that step also, just push `iD.actions.Orthogonalize(entity.id, context.projection)` onto the actions array as well.

**Comment by their** [comment]
Awesome! This looks really great. Will look into implementing. Thank you for checking this out, the code and explanation!
