### ISSUE TITLE
Storage of map

### ISSUE THREAD

**Issue by kto-nado** [openstreetmap/iD#2644]
Sorry for mistakes in translation.

Is it possible to make the data stored on my server and not on the OSM server?
Perhaps there is a ready modification?

**Comment by jfirebaugh** [comment]
Hi @kto-nado -- see [the FAQ entry "Can I use iD with my own OSM server?"](https://github.com/openstreetmap/iD/blob/master/FAQ.md#can-i-use-id-with-my-own-osm-server).
