### ISSUE TITLE
Add actual tag values to comments on Transifex

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/iD#2646]
Sometimes it's unclear what a preset means. Adding tag values that are associated with presets in the comment could speed up translation, as currently I have to look it up in iD manually.

**Comment by bhousel** [comment]
Good idea!  I'm not too familiar with Transifex, but it does look like if we add comments into the YAML source files, they will appear on the site where translators will see them.  Just putting this here as reference to come back to later:  http://docs.transifex.com/formats/yaml

**Comment by jgpacker** [comment]
For reference, there is a field that roughly indicates what the text is for, which is located in the "Details" tab.

For example, the `amenity=childcare` preset has:

> Key:  presets.presets.amenity/childcare.name

However not all translators may be aware of that, mainly because the "Details" tab may be hidden at first (as a tab that should be clicked on) depending on the screen size of the user.

**Comment by bhousel** [comment]
I added this today in 549a14f.   There's no way of testing it other than to wait for Transifex to pick up the new `presets.yaml` tonight and see how it looks on their side.  

We'll watch this for a bit and I'll close if it looks good.  Definitely let me know if there are any other ideas on how to comment up the `presets.yaml` or `core.yaml` to make translators' jobs easier...

**Comment by bhousel** [comment]
I see that these comments are now showing up as "Developer note" on the "Details" tab.  I guess this is a little bit better than what already appears in the "Key" field.


![screenshot 2015-05-30 22 24 17](https://cloud.githubusercontent.com/assets/38784/7900286/df464992-071a-11e5-81d2-8de76fd0a6b0.png)
