### ISSUE TITLE
"Sklep spożywczy" and "Spożywczy" should be deleted from name suggestions

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/iD#2647]
These just mean "grocery". So it's kind of pleonasm and I guess many will regard it bad tagging like a pond named "Pond" and so on.

**Comment by bhousel** [comment]
Thanks for the suggestion - iD actually pulls these name suggestions from another repository automatically.  Can you open this issue in [osmlab/name-suggestion-index](https://github.com/osmlab/name-suggestion-index) instead?

**Comment by RicoElectrico** [comment]
So I reviewed the list and added these, among others that I found. Now how does this whole system work? I see it needs to run against planet pbf, after it's completed how will it be deployed in iD?

BTW, wouldn't it be sensible to delegate presets and translations out of the codebase so they can be updated regularly and automatically without manual deployment?

**Comment by bhousel** [comment]
> So I reviewed the list and added these, among others that I found. Now how does this whole system work? I see it needs to run against planet pbf, after it's completed how will it be deployed in iD?

iD treats it like the background imagery sources - whenever there are new additions we can run a command to get the latest data file from the other project.

> BTW, wouldn't it be sensible to delegate presets and translations (mainly translations) out of the codebase so they can be updated regularly and automatically without manual deployment?

These things can be overridden by the page that contains the iD container.  Although I don't know of anyone doing it, it is possible to host iD and replace the presets, translations, imagery with more updated versions (e.g. using a daily cron job).
