### ISSUE TITLE
Please stop tracking the users browser, OS and locale 

### ISSUE THREAD

**Issue by rponline** [openstreetmap/iD#2649]
Hi!
I just discovered, that iD saves the ID of the users Browser and operating system:
![2015-05-17 23_29_24-openstreetmap _ anderungssatz_ 31224934](https://cloud.githubusercontent.com/assets/1266260/7672410/1eaccb98-fcf2-11e4-9de7-2f6f2954db75.png)

I can't imagine, why this data should be useful for OSM. 
Also, it's not clear for users, that this data gets published.
So please remove this behaviour.

**Comment by bhousel** [comment]
Browser and Platform is already removed in #2643
