### ISSUE TITLE
Make a survey for casual mappers

### ISSUE THREAD

**Issue by kocio-pl** [openstreetmap/iD#2651]
I think we could try to get in touch with new mappers. I guess after 30-90 days or 50-100 editions (whatever comes first - those numbers are just assumptions when somebody may already know the project, but still have a fresh look at it) it would be good to ask them few simple questions:

1. What do you like the most in OSM?
2. What you don't like the most in OSM (major obstacles)?
3. What is really missing in OSM?

(probably with a note like: "Please be specific, it will help us get better!")

The same questions can also be asked about iD, of course. I just think iD users are perfect target to get to know what we as a whole project could make better for the average mapper and a message here would be the best way to contact without disturbing non-editors.

Survey should be translated of course.

**Comment by jfirebaugh** [comment]
Conducting surveys isn't directly related to editing, so I think it's best done outside of iD. Thanks for the suggestion though!

**Comment by kocio-pl** [comment]
I thought if it's for iD users, it belongs to iD (as it is a webapp) and still think like this. Making it on [OSM website](https://github.com/openstreetmap/openstreetmap-website) would be for everyone logged in, and Id like to reach only editors. What do you think would be the best solution then?

**Comment by jfirebaugh** [comment]
You could look at changeset tags, and contact only users who have made changes with iD, via the messaging system.

Please discuss your proposed survey with the community (via the mailing lists) before sending lots of messages though -- it'll help to clarify what you're trying to accomplish and what the community can expect to get back in return for responding.

**Comment by kocio-pl** [comment]
Ok, thanks for the suggestion! There is ongoing discussion on Tagging list regarding surveying users, however with no final conclusions yet.
