### ISSUE TITLE
Suggestion: removal of text - instead, use icons

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2652]
Hi,

Re 'language conflicts' how about changing point/line/area with symbols and the left-hand list of taggy things to symbols - e.g. 'building' being replaced by the building icon ? Any chance of live imports of icons from the rendered map being edited ?
After editing, the user should be returned to their original map, not the default one.

**Comment by jfirebaugh** [comment]
I'm not sure what you mean by "language conflicts". Textual explanations are important for a usable UI because icons can be unclear or ambiguous.
