### ISSUE TITLE
Rotational dismantlation

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2653]
![image](https://cloud.githubusercontent.com/assets/11827386/7746365/896fda56-ffa9-11e4-8f88-bdf6572af564.png)

Stairways:

The upper portion  of the image consists of stairs (E/W) attached to a vertical (N/S) landing attached to (W/E) stairs. I wanted to duplicate the stairs but rotate them 180° so attached a temporary area to the four nodes and added a 5th node area only on the left hand side. Both ends of the upper stairs moved correctlybut only the 'clockwise' ends of the landing and lower stairs moved. The other ends broke free from the things they were joined to and remained stationary. The lower portion of the image shows an anticlockwise rotation of the area of approx 25°.

Can this be fixed please - so a shape moved or rotated has everything attached move as well ?

Another 'nice' feature perhaps would be the ability to 'flip' a shape - either E-W or N-S to generate a mirror image of the objects.

Cheers.

**Comment by bhousel** [comment]
I tried this out today but I can't reproduce the issue.  When I try this, the attached ways always stay attached (see below)..

Can you create a test shape someplace that demonstrates the issue?

![rotate connected objects](https://cloud.githubusercontent.com/assets/38784/7942951/8cc1a93e-092f-11e5-8124-66220226333e.gif)

**Comment by pnorman** [comment]
> Can you create a test shape someplace

On http://master.apis.dev.openstreetmap.org/, not the live DB

**Comment by pmailkeey** [comment]
Ahh - I know what it is - it's after the three items have been copied and pasted as the pasted items' nodes no longer remain connected. This issue is reported elsewhere.

(the live DB is fine for sandbox activities)

**Comment by bhousel** [comment]
Nice, glad it makes sense now..
