### ISSUE TITLE
Support locking imagery and overzooming

### ISSUE THREAD

**Issue by sebastian-philipp** [openstreetmap/iD#2654]
Hi,

I'm mapping for Nepal where bing is not available. In order to map buldings, I'm currently zooming with the browser, which looks kind of wired:

![mapbox-overzoom](https://cloud.githubusercontent.com/assets/2574405/7757818/51ede0d0-0005-11e5-9c79-dc4b8b847957.png)

It would be nice, if you could - instead of displaying an X - over zoom the last layer to 300% at least.

Thanks. 

Edit: I just found #784 , where nighto had the same issue.

**Comment by bhousel** [comment]
Closing this here, as we're pulling in a bunch more worldwide imagery sources now from [editor-layer-index](https://github.com/osmlab/editor-layer-index) with the recent addition of the Digital Globe layers and the Esri World Imagery layer.  Users have more options now where Bing doesn't look so good.

We currently support the `best` flag for picking an imagery that is better than Bing, but it's not a great solution and so we can explore ways upstream in editor-layer-index to mark which imagery is the best for a particular region.
