### ISSUE TITLE
Two issues when saving

### ISSUE THREAD

**Issue by SuzanReed** [openstreetmap/iD#2655]
MacBook Pro   OS 10.6.8    Chrome and Firefox

1. After Saving edits, unlocking the Task, and going to another Task, a dialog box appears with two icons that indicates past edits have not saved, and asks if I want to restore the edits and save them. Clicking on the Restore icon, these edits can be saved, but I know I already saved them before exiting the Task. I believe doing this over writes the last Task, doubling the images. John Whelan has verified several of my Tasks (asked him to do this) and he has reported numerous doubled buildings and roads. 

2. Other times, independent of the above issue, a dialog box appears after pressing the Save button in the top menu: 
"Errors occurred while trying to save
Bad Gateway. The proxy server received an invalid response from an upstream server.
Apache/2.4.7 (Ubuntu) Server at www.openstreetmap.org Port 80"  (html tags have been removed for brevity.) (I have a screen shot.)

When Saving after getting this kind of dialog box, the Save button has to be pressed several times. There can be long delays. Eventually the edits Save and I get the white dialog box that shows they are being saved, with the twirly thing, and the blue images in the left column appear. 
![screen shot 2015-05-21 at 2 14 29 am](https://cloud.githubusercontent.com/assets/12556671/7766515/bf7c4dd0-001e-11e5-8901-6527f156b73f.png)

![screen shot 2015-05-21 at 2 14 29 am](https://cloud.githubusercontent.com/assets/12556671/7766497/9260470c-001e-11e5-8f9c-d4abd0d78d3e.png)

**Comment by pnorman** [comment]
It sounds like you might be having significant internet problems. Is that possible?

**Comment by SuzanReed** [comment]
I have high speed internet and haven't had any other issues when I work online in other situations. I thought that, too, but pinged my connection, and it was indeed fast. 


On May 22, 2015, at 1:18 AM, Paul Norman wrote:

It sounds like you might be having significant internet problems. Is that possible?

�

**Comment by SuzanReed** [comment]
Paul, 

Are you saying both of these issues could be related to a slow internet connection? 

Suzan 


On May 22, 2015, at 1:18 AM, Paul Norman wrote:

It sounds like you might be having significant internet problems. Is that possible?

�

**Comment by techlady** [comment]
Paul,
A number of people are having these issues. 
--Saves are not saved and the dialog box giving the choice of Save or Reset appears. 
--Also, saves are taking a long time
--Third, I am getting messages that the server is too busy to accept saves.
Like Susan, I have high-speed Internet with service at 6MB to 7MB per second.
But, most important, why is there no page on the web site to make these reports?? Github is a tool for geeks writing software. It is certainly not something that new mappers can use easily. It uses its own internal language with terms that most people don't know ("fork" What does that mean?) .
Both iD and the OSM web site need to be fixed ASAP.

**Comment by gmaclennan** [comment]
Hi Suzan, the second issue looks like an issue with the OpenStreetMap server, likely that it is overloaded or down. It doesn't look like a problem with your internet connection. I don't know about the first issue. It sounds like you're using the tasking server right?

**Comment by SuzanReed** [comment]
Hi Gregor, 

No idea what the "tasking server" is! 

Suzan 


On May 22, 2015, at 10:04 AM, Gregor MacLennan wrote:

Hi Suzan, the second issue looks like an issue with the OpenStreetMap server, likely that it is overloaded or down. It doesn't look like a problem with your internet connection. I don't know about the first issue. It sounds like you're using the tasking server right?

�

**Comment by gmaclennan** [comment]
Sorry I meant to say "Tasking Manager" as in the HOT Tasking Manager. Was wondering what "Task" you refer to in your issue

**Comment by SuzanReed** [comment]
Oh! Yes, I'm using the Task Manager. 

You might call them squares or tiles, but in the Task Manager they are referred to as Task #x, so I was going with what I thought was official language. 



On May 22, 2015, at 3:12 PM, Gregor MacLennan wrote:

Sorry I meant to say "Tasking Manager" as in the HOT Tasking Manager. Was wondering what "Task" you refer to in your issue

�

**Comment by SuzanReed** [comment]
These issues are still prevalent as of May 31, 2015. No solution.

**Comment by bhousel** [comment]
Issue #1, re duplicate items saved - I did some digging into this and will reply to it on issue #2667 
Issue #2, re 502 Bad Gateway error is likely that the OSM servers were overloaded.  The overloaded servers could have possibly caused issue #1..
