### ISSUE TITLE
Spaces after semicolons are stripped from description, note tags

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#2659]
As noted in https://github.com/openstreetmap/iD/issues/2657#issuecomment-105255209, `cleanVal()` [scrubs spaces after semicolons](https://github.com/openstreetmap/iD/blob/420647f5034083db905b5bf320e7c21b52379a3f/js/id/ui/entity_editor.js#L143) in every tag as soon as any tag is edited. However, the `description` and `note` tags always contain prose, so a space after a semicolon is usually intentional and not an indication of a multi-value tag. (`fixme`/`FIXME` is almost in the same boat, but so many import bots have used it for keyword-style values that I wouldn’t bother blacklisting it.)

**Comment by bhousel** [comment]
Good idea.. I thought about it more and did include `fixme` in the blacklist.  Probably better to just leave those tags alone instead of trying to clean them up.
