### ISSUE TITLE
Indoor editing

### ISSUE THREAD

**Issue by franckt** [openstreetmap/iD#2660]
i'm currently working on an iD branch for indoor editing
with data structure similar than IndoorOSM[http://wiki.openstreetmap.org/wiki/IndoorOSM], 

relation Building contains :
--building geometry
--relation floor1 contains
----features in the floors (rooms, walls, poi, indoor routing ...)
--relation floor2 ...

the idea is to simplify the edition by having a sort of indoor editing context : 
user select a buildilng / floor relation from a list to make it current :
- to avoid adding all geometries to floor relation, so added rooms, floor, walls are automatically added to current floor relation
- to filter all indoor features in current floor because they overlapped with others floor features instead

Another feature would be adding a georeferenced (rotated and scaled) floor PNG plan as a transparent background layer to help editing

Does anyone work on this ? Have you some ideas to enrich iD the good way ?

**Comment by jfirebaugh** [comment]
https://github.com/openfloorplan/ofp-editor is a previous effort in this vein.

Check out [ARCHITECTURE.md](https://github.com/openstreetmap/iD/blob/master/ARCHITECTURE.md) and [API.md](https://github.com/openstreetmap/iD/blob/master/API.md) for code-level documentation.

If you have specific enhancement requests, feel free to open tickets.
