### ISSUE TITLE
Disappearing letters in streetname when zooming in.

### ISSUE THREAD

**Issue by filipca** [openstreetmap/iD#2663]
Chrome Version 42.0.2311.90
When zooming in, the short branch of the "Schrijnstraat" in Mechelen, Belgium, becomes "Schrijrat".
Or is this only temporary, after shortening a street ?

**Comment by bhousel** [comment]
Can you post the url where you see this happen?

**Comment by filipca** [comment]
http://www.openstreetmap.org/#map=19/51.03342/4.47448

**Comment by filipca** [comment]
I witnessed it on an old and new computer under IE as well as Chrome.
I deleted another node in the street.
As I cannot always reproduce it, I attached this screenshot.

![image](https://cloud.githubusercontent.com/assets/6695589/7882202/79fcb676-060b-11e5-91f1-a4abd9e1fe32.png)

**Comment by talllguy** [comment]
Possibly related to https://github.com/gravitystorm/openstreetmap-carto/issues/950

**Comment by pnorman** [comment]
The screenshot is not one of I'd, but of a rendered map.

**Comment by bhousel** [comment]
Just realized now that this is not an issue with iD.. Closing.
