### ISSUE TITLE
Old Sattelite Map

### ISSUE THREAD

**Issue by Nori30** [openstreetmap/iD#2665]
The Image of the Sattelite View is too old compare to the 20th century.. the place is modern.. you should help make map a new.. so i can help edit

**Comment by bhousel** [comment]
Hi, thanks for the report. iD's background imagery sources come from the [editor-imagery-index](https://github.com/osmlab/editor-imagery-index) project. If you know of a more recent imagery source that is licensed for this use, please open a request there with the link and license details.
