### ISSUE TITLE
Double or triple images after returning to a task.

### ISSUE THREAD

**Issue by SuzanReed** [openstreetmap/iD#2667]
Coming back to a task after a break and relocking it, numerous images have been doubled. Older edits show up with newer edits. For instance, there will be two buildings on top of each other; a path and a track are on top of each other. 

OS 10.6.8 Firefox MacBookPro
http://tasks.hotosm.org/project/686

**Comment by bhousel** [comment]
I'd like to check to see if maybe multiple people are editing in the same location.  Locking a HOTOSM task doesn't actually prevent this.

Can you post the url of the map where you see the doubled buildings?

**Comment by SuzanReed** [comment]
Thank you for the quick response. The url is in the body of the report. I 
am the only person editing that area of Cameroon, but you never know!

Suzan

**Comment by bhousel** [comment]
Thanks @SuzanReed.. The URL I really need is a URL of the map, not the task.

Can you do this:  Zoom in close on a location where you had this issue, then click on "Contribute", scroll the sidebar all the way down and click "OSM Changesets".  This will take you to an openstreetmap url where we can see the history of what happened at that spot.  There are likely several users other than you that have made changes, so I also need to know your OSM username.

Upon a successful save, iD is really supposed to wipe out its stored history and reload fresh map data from the server, so it's important for us to know what changesets went in around the time the issue occurred.

**Comment by SuzanReed** [comment]
I'll do that later today. I may be able to find the changeset, too. 

Suzan 


On Jun 1, 2015, at 1:12 PM, Bryan Housel wrote:

Thanks @SuzanReed.. The URL I really need is a URL of the map, not the task.

Can you do this: Zoom in close on a location where you had this issue, then click on "Contribute", scroll the sidebar all the way down and click "OSM Changesets". This will take you to an openstreetmap url where we can see the history of what happened at that spot. There are likely several users other than you that have made changes, so I also need to know your OSM username.

Upon a successful save, iD is really supposed to wipe out its stored history and reload fresh map data from the server, so it's important for us to know what changesets went in around the time the issue occurred.

�

**Comment by SuzanReed** [comment]
http://www.openstreetmap.org/history?bbox=12.5793457009,6.47906728961,12.590332029,6.48998333151

Yes, there were other people working on that area. My OSM username is SReed. 

I also thought a new map would load from the server, so was quite surprised by the old data being 'served back up'.

Previously reported: 
I'm also still getting the dialog telling me I have unsaved changes when I close a Task and go to a new one. If I click on Restore and Save, this overwrites the last task with this data, causing two sets of data to appear. So double buildings, roads, paths, etc. Ask JohnWhelan as he is validating my work, and has seen this a couple of times. I have gone to several tasks in this Cameroon area and found two sets as well. Something will be a path and a track, or I can see two images of buildings, but one will be slightly different so I can see the stack. I think new users will see this dialog and Restore and Save causing validators and other mappers a lot more work. 


On Jun 1, 2015, at 1:12 PM, Bryan Housel wrote:

Thanks @SuzanReed.. The URL I really need is a URL of the map, not the task.

Can you do this: Zoom in close on a location where you had this issue, then click on "Contribute", scroll the sidebar all the way down and click "OSM Changesets". This will take you to an openstreetmap url where we can see the history of what happened at that spot. There are likely several users other than you that have made changes, so I also need to know your OSM username.

Upon a successful save, iD is really supposed to wipe out its stored history and reload fresh map data from the server, so it's important for us to know what changesets went in around the time the issue occurred.

�

**Comment by bhousel** [comment]
Thanks for the details.  I did some digging and it does look like it's possible for duplicate edits to get saved.

An example of this in the area that you sent:

* [changeset 31621501](http://www.openstreetmap.org/changeset/31621501)  2015-05-31T23:06:06Z, you added 3 buildings..

* [changeset 31621517](http://www.openstreetmap.org/changeset/31621517) 2015-05-31T23:07:08Z, you added the 3 buildings again..

* At this point iD probably refreshed and you saw the duplicates..

* [changeset 31621520](http://www.openstreetmap.org/changeset/31621520) 2015-05-31T23:07:30Z, you deleted the duplicate buildings..


I think the problem code is in [`save.js`](https://github.com/openstreetmap/iD/blob/master/js/id/modes/save.js#L156-L172) and [`connection.js`](https://github.com/openstreetmap/iD/blob/master/js/id/core/connection.js#L261-L284)

When `connection.js` tries to open the changeset, post the change, and close the changeset, each of those things can generate an error that bubbles back up to `save.js`.  It's possible for the changes to post ok, but then we get a timeout on the close (which can safely be ignored).  I'll make some improvements here.

**Comment by bhousel** [comment]
Some of this could be caused by #1646 too.
I did some testing today to check whether my fix worked, and definitely got stale data back from the server after uploading my changes.  

@pnorman you produced some postgres replication data on that other thread.. Is the situation still the same, getting worse?

**Comment by SuzanReed** [comment]
Thank you so much for working on this, Bryan. I'm grateful. 

I haven't gotten stale data back for several days, but I'm not mapping as many hours as I was. 

I am still getting this issue: 
After closing a task and opening a new task I get a large dialog saying I have unsaved changes, do I want to restore them or dump them. I dump them. However, I don't think newbies do this as it causes a bit of panic. Yes, someone might have unsaved changes, but if the instructions are clarified it may eliminate this issue. I'm hopeful the review of the Tasking Manager will address this issue and it can be integrated with iD. 

I'm curious, can you add shortcuts? There are a few I'd like. Most notably a shortcut for selecting the tag Building=building, Road=path, and Road=track. I read "m" or "control/command+m toggles iD full screen, but it doesn't work for me. Let me know on these. 

 
On Jun 3, 2015, at 7:56 AM, Bryan Housel wrote:

Some of this could be caused by #1646 too.
I did some testing today to check whether my fix worked, and definitely got stale data back from the server after uploading my changes.

@pnorman you produced some postgres replication data on that other thread.. Is the situation still the same, getting worse?

�

**Comment by bhousel** [comment]
Added a few changes to make saving a bit more reliable.  29160d2 removes a condition that made it possible to save data twice, 9311ee6 makes it more difficult to fetch stale data after saving, and  78c484a makes extra sure that the localStorage edits are cleared out before the user can make new edits.

> I'm curious, can you add shortcuts? There are a few I'd like. Most notably a shortcut for selecting the tag Building=building, Road=path, and Road=track. I read "m" or "control/command+m toggles iD full screen, but it doesn't work for me. Let me know on these.

There are some open issues about making it easier for users to repeat the tags that they have already entered.  I'm hoping to add an improvement in the next month or so, in addition to making it easier to trace buildings. If there is a shortcut to enter full screen, it's something that your browser does (Chrome/Firefox/Safari) or possibly your operating system.  For example, under Chrome's View menu there are fullscreen options there.  Each browser does this a little differently.

**Comment by SuzanReed** [comment]
Hi Bryan, 

Impressive fixes. 

I got the dialog again over the past few days where I'm told I have unsaved changes. The one that asks if you want to save or refresh. 

Thank you for all the work. Appreciated. 

Suzan 



On Jun 9, 2015, at 10:29 PM, Bryan Housel wrote:

Added a few changes to make saving a bit more reliable. 29160d2 removes a condition that made it possible to save data twice, 9311ee6 makes it more difficult to fetch stale data after saving, and 78c484a makes extra sure that the localStorage edits are cleared out before the user can make new edits.

I'm curious, can you add shortcuts? There are a few I'd like. Most notably a shortcut for selecting the tag Building=building, Road=path, and Road=track. I read "m" or "control/command+m toggles iD full screen, but it doesn't work for me. Let me know on these.

There are some open issues about making it easier for users to repeat the tags that they have already entered. I'm hoping to add an improvement in the next month or so, in addition to making it easier to trace buildings. If there is a shortcut to enter full screen, it's something that your browser does (Chrome/Firefox/Safari) or possibly your operating system. For example, under Chrome's View menu there are fullscreen options there. Each browser does this a little differently.

�
