### ISSUE TITLE
Images not deleted while mapping

### ISSUE THREAD

**Issue by SuzanReed** [openstreetmap/iD#2668]
Example: 
Deleted one image of a building. Replaced it with three images of three buildings. Moved down the tile. Suprised to see the old deleted image of one building still there, and none of the three new buildings. Deleted the old image again, mapped the three new images again. Saved. There are now three buildings on top of three buildings. Deleted all the images and remapped them. Saved. 

Happened throughout the session. Saved frequently. Unlocked the task, locked it again several times but issue continued. 

OS 10.6.8  Firefox MacBook Pro  Fast internet speed. 
http://tasks.hotosm.org/project/689

**Comment by bhousel** [comment]
dup of #2667 related to save issues
