### ISSUE TITLE
Incorrect rending of riverbank around Fargo, ND

### ISSUE THREAD

**Issue by jblaufuss** [openstreetmap/iD#2669]
The riverbank of the Red river next to Fargo, ND appears to have some problems.  It has incorrect, angular projections into the city area (see attached picture), which seem to change from viewing to viewing at with zoom level.

I am using version 1.7.2 of the map editor.

An example can be seen around the the site of the former Cardinal Muench Seminary at 46.924229, -96.766882.

![openstreetmap bug](https://cloud.githubusercontent.com/assets/12689535/7905494/0fa218cc-07df-11e5-8cda-0c528d7d556a.jpg)

**Comment by pnorman** [comment]
Looks like #1201

**Comment by bhousel** [comment]
Yes, I think so.  I wonder if we should just fetch missing multipolygon parts while the iD.connection is sitting idle.  

re: #2284 too
