### ISSUE TITLE
Improve handling of merging of objects with incompatible properties

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#2670]
Inspired by looking at odd taginfo values for "oneway" I have discovered that the behaviour of iD could be improved for merges. I have drawn 2 ways connected at one point, with different directions and with the tags "oneway=no" and "oneway=yes". On merging iD automatically creates a double value (yes;no or no;yes), first tag value and the direction is taken from the first way selected (e.g. 1st way selected is oneway=no and 2nd way is oneway=yes and pointing in the opposite direction will revert the direction of the oneway=yes way without notice and will create a oneway value of no;yes also without notice. 

I see several problems:

1. if ways have to be reversed in their order so that a certain operation can be performed, this should be confirmed by the mapper. If there are ways with oneway=yes and others with no oneway tag or oneway=no, the direction of the oneway=yes way should be the reference and should not be reversed.

1b. the values of direction dependent ways should be suggested to be reversed when the way gets reversed, e.g. incline=up should become incline=down (to be confirmed by the mapper) or oneway=yes should become oneway=-1 (to be confirmed). Currently the way get reversed without any notice and without the tags being changed. Some documentation can be found here:
http://wiki.openstreetmap.org/wiki/Category:Way_Direction_Dependent

2. multiple values should be avoided, they are mostly errors, creating them should be discouraged and should require explicit confirmation by the mapper.

I have tested this case also with current JOSM, if you combine a way with oneway=yes and one with oneway=no you will get to a window which asks to choose from "yes, no, /none/, /all/" and you have to deliberately choose "all" to get an ambiguous value. IMHO this behaviour should also be adapted for iD.

Multiple values should be avoided generally, they are hardly what the mapper wants to achieve, but rather typically the result of a mapper overlooking incompatible properties when trying to merge 2 ways. I would prefer that there was a warning popping up, requiring the mapper to explicitly confirm the problematic tagging (or not allow it at all and require to first make the properties compatible and then allow the merge).

**Comment by bhousel** [comment]
Yes, there's a lot of discussion on #908 about this.   I agree this one is high priority.

I think I can pretty easily detect these tag conflicts and disable the merge operation with a helpful message in the tooltip.
