### ISSUE TITLE
tag value is urlencoded if it contains the string "http" anywhere

### ISSUE THREAD

**Issue by tilmanb** [openstreetmap/iD#2671]
A tag value is urlencoded if it contains http anywhere in the value.

See https://github.com/openstreetmap/iD/blob/6e27b55061ffbd68f5ab5efba34b945c6372c800/js/id/ui/entity_editor.js#L155

This incorrectly encodes values like "0.2.6.11 / 2007-12-04 / http://fa-technik.adfc.de/code/opengeodb/dump/" in the tag opengeodb:version, see for example here: http://osmlab.github.io/osm-deep-history/#/node/240088799 .

I propose to change this behaviour, so that a string is only urlencoded if it starts with "http".

**Comment by bhousel** [comment]
Yes, this issue is already fixed in 51dfbb1..
