### ISSUE TITLE
Mapillary traffic signs are visible only at low zoom

### ISSUE THREAD

**Issue by Michael21011** [openstreetmap/iD#2675]
I can not see traffic signs on big zoom to edit a map. They are visible only on small value of zoom. When I press Zoom In they disappear.
Firefox 38.0.1
[link to map](http://mapillary.github.io/iD/#background=Bing&map=13.64/27.6645/53.9419)
Please find attached
![20](https://cloud.githubusercontent.com/assets/9266780/7944408/1aa15c48-0973-11e5-94df-3893d7902a92.jpg)
![21](https://cloud.githubusercontent.com/assets/9266780/7944409/1aa55b9a-0973-11e5-9aea-393381abcf53.jpg)
![22](https://cloud.githubusercontent.com/assets/9266780/7944410/1aacd6cc-0973-11e5-87b6-e164f18e412e.jpg)

 files with different zoom level.

**Comment by bhousel** [comment]
The Mapillary traffic sign layer is still a work in progress.  It's pretty awesome though - hoping to put together a pull request to merge it in soon.

**Comment by bhousel** [comment]
As of 2729241 / #2730 this is working really well now.
iD will download all the Mapillary data it can, and will selectively show more images as you zoom in and the viewport is less cluttered.  You'll at least be able to see the data coverage out to z12.
