### ISSUE TITLE
Adding nodes to a way with iPad or touch device

### ISSUE THREAD

**Issue by kaligrafy** [openstreetmap/iD#2677]
Is it possible to add a node to an existing way using an iPad? While double-clicking with the iPad, it keeps zooming in. When zoom is at maximum value, it is still not possible to create node.

Also, when one node has been created elsewhere (not on a way), it is almost impossible to move it with the iPad.

**Comment by bhousel** [comment]
If the way is selected, you should see triangular midpoints between the existing points.  I think you should be able to drag these and create new points that way.  Can you let me know if this works on iPad?

**Comment by kaligrafy** [comment]
Yes, that works, but I cannot move the new node closer to the intersection. Thanks anyway for the cue!

**Comment by bhousel** [comment]
I'll leave this issue open for now because we should really improve this behavior on touch devices.  E.g. add nodes with long press or something.

**Comment by weajd** [comment]
I have a similar problem when trying to add an area such as a building with an iPad and Safari.  I can add the first node of the frame but subsequent nodes do not take for some reason.  Maybe I am too much of a newbie!

**Comment by quincylvania** [comment]
You can now both drag nodes and double-tap to add nodes on touch devices, so I'm considering this closed.
