### ISSUE TITLE
Features Disappear when saving in Firefox on OS/X

### ISSUE THREAD

**Issue by Gugym** [openstreetmap/iD#2678]
In OS/X 10.10.3 and Firefox 38.0.5, having created and then saved features, the new features disappear from the edit view. If I log out and back in the features are still present and have been saved correctly.

**Comment by bhousel** [comment]
Yes, unfortunately the data fetched from the server *immediately* after a save may not contain your edits.  A refresh within a few seconds will solve the issue.

see also [#2667-comment](https://github.com/openstreetmap/iD/issues/2667#issuecomment-108469635) and #1646 

Not sure what to do about this yet, but it's something we are aware of, and seems to be a problem that is affecting a bunch of users recently.  (It happened to me today too).

As stupid as it sounds - adding a few seconds delay after changeset is accepted might be the easiest way to fix this for now.  Processing diff upload is doable but scary.  We'd basically need to copy the diffed things out of the graph into another place, context.flush, and then rebase them back in.  It's a bit like refreshing from localStorage I guess.

**Comment by bhousel** [comment]
Closing this, as 9311ee6 adds a brief pause which should fix this in almost all cases.  It still would be better to process diff upload eventually, so leaving #1646 open.
