### ISSUE TITLE
Feature Request: Redo Button To Work

### ISSUE THREAD

**Issue by Gugym** [openstreetmap/iD#2679]
It would be really good to have the redo button, that is in the UI but greyed out, operational. For repetitive tasks such as adding addresses it would really save time having the ability to repeat creating a point with the same attributes so that just the house number can be altered.

Anticipated UI: create point at location, add address (or other attributes), select point and the hit the redo button and the last set of attributes would be copied to the new point. The attributes could then be quickly edited (i.e. one) without the need to have to keep retyping all other address details as an example.

**Comment by bhousel** [comment]
That Redo button is actually to restore edits that have been Undo'ed, that's why it shows as greyed out (until you Undo something).

But what you are describing, repeating tag edits, is a useful feature, and I want to add it soon..
Some good ideas already discussed on #1761 #590 #839
