### ISSUE TITLE
WIkidata tagging

### ISSUE THREAD

**Issue by pigsonthewing** [openstreetmap/iD#2680]
Please add a feature for tagging objects with their Wikidata ID:
- Include Wikidata in presets
- If the coordinates in Wikidata vary wildly from those in OSM, issue a warning.
- If the item in WIkidata has no coordinates, issue a warning, but also suggest the user might add them
- If an object already has a Wikidata ID, fetch (via API) and display the Wikidata label (and description?) in the user's preferred language (with fallback to English/ whatever is available?) link to the Wikidata item (e.g. for Q5642705, display "Hall of Memory, Birmingham" and link to https://www.wikidata.org/wiki/Q5642705 )
- If the user enters a Wikipedia tag, fetch the corresponding Wikidata ID, and add that too. 

Wikidata IDs are more persistent than Wikipedia URLs, and act as identifiers for open linked data, including links to Wikipedia articles in multiple languages.

**Comment by pigsonthewing** [comment]
Regarding my final bullet point:

For example, for "wikipedia=en:St James' Church, Handsworth", the Wikidata item's ID is "Q16908818"; see [1], [2].

Show a validator warning if no Wikidata item is found (the Wikidata item may not exist yet; or the value entered may contain an error.

Show a validator warning if two or more Wikipedia articles are linked, with different Wikidata item IDs (may indicate a user error; or there may be duplicates on Wikidata).

[1] ​https://en.wikipedia.org/wiki/St_James%27_Church,_Handsworth

[2] ​https://www.wikidata.org/wiki/Q16908818

**Comment by 1ec5** [comment]
What if you’re editing an object that already has a `wikipedia` tag? Should there be a way to replace it with the corresponding `wikidata` tag?

**Comment by bhousel** [comment]
These all look like pretty good suggestions to me.. I think an easy first step would be this one: "If the user enters a Wikipedia tag, fetch the corresponding Wikidata ID, and add that too."

@1ec5 I don't think we should replace `wikipedia` tags yet, but I don't see an issue with adding `wikidata` tags alongside them.

**Comment by 1ec5** [comment]
The biggest blocker I’ve seen so far is that wikidata.org and wdq.wmflabs.org [don’t allow CORS requests](https://phabricator.wikimedia.org/T46994) from openstreetmap.org or any other site that currently uses iD. I could host a Wikidata-aware instance of iD on my WMF Tools Lab account, but that won’t help adoption of the `wikidata` tag among the general mapping community.

**Comment by 1ec5** [comment]
In the course of working on #2732, some other ideas came up based on the data we get “for free” alongside the entity IDs:

* Issue a warning if an `amenity=cafe` is tagged `wikipedia=en:Eiffel Tower` `wikidata=Q243`, based on the fact that [Q243](https://www.wikidata.org/wiki/Q243) is associated with [`ref:mhs`](https://wiki.openstreetmap.org/wiki/Key:ref:mhs) (by way of [Q916475](https://www.wikidata.org/wiki/Q916475)) rather than `amenity=cafe` (via [Q30022](https://www.wikidata.org/wiki/Q30022)).
* Issue a warning if `wikipedia` refers to a Wikipedia disambiguation page. (Not all disambiguation pages have “(disambiguation)” in the title.)
* Suggest `name:*` tags based on localized Wikidata labels (and instigate a contentious, million-word debate on talk@).

**Comment by 1ec5** [comment]
Here’s the [corresponding JOSM ticket](https://josm.openstreetmap.de/ticket/11541).

**Comment by pnorman** [comment]
https://phabricator.wikimedia.org/T46994 is closed with the comment

> (In reply to Derk-Jan Hartman from comment #9)

> > Oh and actually exposing resources for CORS (the json blobs) should be a
separate bug request, it requires software changes.
> Yes, making the special page usable with JS from remote sites would require extra changes (this should go into a separate bug).

My reading of the ticket is that that another ticket was needed for getting CORS on what we wanted from wikidata.org

**Comment by 1ec5** [comment]
Based on the comments in that ticket and in informal discussions with some developers at Wikimania today, it sounds like getting CORS enabled for iD would be a nonstarter, particularly since iD isn’t tied to a particular domain. For #2732, I went with JSONP instead.

**Comment by bhousel** [comment]
@pigsonthewing & @1ec5,  iD's wikidata integration is now working pretty well, and many of the validation suggestions above are now being handled by other tools.  Do you see any other tasks that we should do for now?  I'm going to close this ticket, and we can open new issues for any other follow-on wikidata tasks.

**Comment by pigsonthewing** [comment]
@bhousel LGTM; thank you.

**Comment by boothym** [comment]
>Issue a warning if wikipedia refers to a Wikipedia disambiguation page. (Not all disambiguation pages have “(disambiguation)” in the title.)

@bhousel recently someone added the correct wiki info to a node I had edited, because I had link to the disambiguation page by mistake. Is there any way to detect a disambiguation page and let users know in the wikipedia drop-down?

**Comment by bhousel** [comment]
> @bhousel recently someone added the correct wiki info to a node I had edited, because I had linked to the disambiguation page by mistake. Is there any way to detect a disambiguation page and let users know in the wikipedia drop-down?

I'm not sure but we should look into it and avoid it if possible - can you open this as a new issue so we don't lose it, thanks!
