### ISSUE TITLE
Wikipedia list is outdated

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#2682]
[wikipedia.json](https://github.com/openstreetmap/iD/blob/master/data/wikipedia.json) lists 285 Wikipedias, but [Wikimedia’s site matrix](https://meta.wikimedia.org/wiki/Special:SiteMatrix?uselang=en) lists 288 and new Wikipedias are added somewhat regularly as they graduate from Wikimedia Incubator. iD’s build process should call the [MediaWiki API](https://en.wikipedia.org/wiki/Special:ApiSandbox#action=sitematrix&format=json) to regenerate the list more easily.

/cc @aaronlidman

**Comment by aaronlidman** [comment]
Just noting today:
- direct url is here: https://en.wikipedia.org//w/api.php?action=sitematrix&format=json
- conversion to wikipedia.json mapping should happen in an [osmlab](https://github.com/osmlab/) project and not iD

**Comment by bhousel** [comment]
related #2457 
`wikipedia.json` may not be what we want to use anyway.

**Comment by 1ec5** [comment]
wikipedia.json (or the separate project @aaronlidman suggests) is the right way to go. #2457 is specific to `name:*`.
