### ISSUE TITLE
Bing Map issue

### ISSUE THREAD

**Issue by mdkaleel** [openstreetmap/iD#2683]
Hi 

the Below Bing map is not clear, unable to see the Road.
https://www.openstreetmap.org/edit#map=16/11.4852/79.7535

**Comment by bhousel** [comment]
We can't do anything about the Bing imagery - they source their images from various places and this spot happens to be on a boundary between higher and lower quality.

But you can switch which imagery provider iD uses. In this area, Mapbox Satellite looks better. The available list is in the "Background" pane and can be switched like this:

![screenshot 2015-06-02 07 55 27](https://cloud.githubusercontent.com/assets/38784/8054456/d9474aa2-0e66-11e5-8e1b-c2083ac1b21d.png)
