### ISSUE TITLE
please add presets for casino and adult_gaming_centre

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#2684]
We have the main two tags 

*    [`amenity=casino`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcasino)
*    [`leisure=adult_gaming_centre`](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dadult_gaming_centre)

Thanks a lot for your work.

**Comment by bhousel** [comment]
I took a look at those, and the [accepted Gambling tag proposal](http://wiki.openstreetmap.org/wiki/Proposed_features/Gambling), and unfortunately I'm at a loss for how to add presets for these tags in a way that is not confusing to normal users.

The difference as far as I can tell is - "Casinos" have table games and "Adult Gaming Centres" do not (but both commonly have the word "casino" in the name of the establishment)?

**Comment by bhousel** [comment]
Also worth noting that the `amenity=casino` wiki page seems to have a wrong description in the template box.  iD pulls from here to display inline tag help.

**Comment by HolgerJeromin** [comment]
Yes, that is the reason i only added amenity=casino and leisure=adult_gaming_centre to my list. These are IMO the most useful of the proposal. 
Perhaps @math1985 can give some advice.

I just fixed the template box.
