### ISSUE TITLE
please add recycling_type option for every amenity=recycling

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#2689]
It is a big difference if the recycling feature is a [centre or just a container](http://wiki.openstreetmap.org/wiki/Key:recycling_type).

Thanks!

**Comment by boothym** [comment]
@bhousel don't know if it's just me, but the recycling_type field is no longer available. Can't see where it has been removed - surely it's still meant to be in iD?

**Comment by bhousel** [comment]
Weird, yeah the type field should be there.. I'll check and see what happened.

**Comment by bhousel** [comment]
Looks like we lost it by accident in 9261752.. I'll put it back! ♻️
