### ISSUE TITLE
Remove tiger:reviewed tag when user performs certain edits

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2697]
I feel bad that `tiger:reviewed=no` is [used by the cycle.travel router to penalize roads](https://lists.openstreetmap.org/pipermail/talk-us/2015-June/014991.html), but iD (rightly) hides this tag from users.  New users are doing substantial cleanup to the US map and they shouldn't need to know anything about what `tiger:reviewed` is or how to use the raw tag editor to remove it.

Are we at the point now where we can safely remove the tag for the user if they make a substantial edit to a way?  I'm thinking it's probably safe to remove `tiger:reviewed` (and maybe certain other `tiger:` tags) after any change to:

* road classification (preset)
* visible fields: oneway, maxspeed, structure, access, surface, cycleway
* realignment (moving child nodes)

I don't think it's safe to remove the `tiger:reviewed` tag for every kind of edit (e.g. splits or merges or connecting ways to other ways), but only for the ones listed above..

Just putting this out there for discussion.. Thoughts?

**Comment by pnorman** [comment]
I wouldn't base the discussion around what a data consumer is doing. Most of the changes you mentioned would make `tiger:reviewed` irrelevant to cycle.travel anyways.

**Comment by darrell** [comment]
I think those are entirely reasonable situations to move the tag. All of those imply that the way has, in fact, been reviewed.

**Comment by simonpoole** [comment]
@bhousel I'm likely not untypical in that I've done two of the three tasks on 100s, more likely 1000s of roads in the US and would have never considered changing/removing tiger:reviewed .... simply because I was not there (I'm not actually sure if I've removed it on all roads that I surveyed in person, but that is a different story)..

**Comment by bhousel** [comment]
@simonpoole I though about what you said some more, and I still think it's entirely reasonable to remove this tag even if someone is armchair mapping.  The TIGER data is from 2005 and I believe all of the Bing imagery covering the United States (at least, at the zooms that iD works in) is much newer than that.

**Comment by brycenesbitt** [comment]
I think that either tiger:reviewed needs to be explained to the mapper (not hidden).
Or, removed when the node/way is edited.

Most of the time I find edited tiger ways, the mapper has not felt bold enough or been empowered enough to remove the tag tiger:reviewed

**Comment by jfirebaugh** [comment]
There are (at least) four common problems with imported TIGER data:

* Misalignment, both minor and gross
* Incorrect names, mostly commonly the presence of names from nearby roads on tracks or service roads that should be unnamed
* Incorrect classification
* Lack of surface tags

Technically `tiger:reviewed` should be removed only after _all_ of these issues are addressed, and I'm not confident that iD can reliably detect that in an automated way.

**Comment by bhousel** [comment]
@jfirebaugh How about a different approach.  We implement changeset hashtags (#2834), and if a magic hashtag like #tiger is present, we remove `tiger:reviewed` from everything the user touched.

(I've been doing a lot of these cleanups lately and really looking for ways to make this kind of editing easier. :tiger: )

**Comment by pnorman** [comment]
> Technically tiger:reviewed should be removed only after all of these issues are addressed, and I'm not confident that iD can reliably detect that in an automated way.

This is not a universally held view - part of the problem with `tiger:reviewed` is that there's no clear conditions on when to remove it.

**Comment by jfirebaugh** [comment]
@pnorman Yes, that's also a problem.

I do a lot of TIGER cleanup as well. Personally, I'm happy just deleting `tiger:reviewed` in the raw tags editor after I fix all the issues with a given way. To me that seems like an interaction and level of effort commensurate with the experience and effort necessary to perform TIGER cleanup.

**Comment by bhousel** [comment]
Fair points, I'm dropping this issue for lack of interest.
