### ISSUE TITLE
iPad: Editing existing objects doesn't work

### ISSUE THREAD

**Issue by saerdnaer** [openstreetmap/iD#2700]
When I try to modify the attributes of an existing node or way by touching the corresponding text field in the left sidebar the keyboard opens and the node gets unselected. This leads to closing of the sidebar which then only displays the search box.

When I try to use the same form fields during creating a new node everything works, so it's only the edit mode which causes problems.

**Comment by quincylvania** [comment]
I'm not seeing this particular issue in mobile Safari on iPhone (not that mobile editing is all roses now). I'm closing this, but let us know if you're still this problem!
