### ISSUE TITLE
Render cycleway:left and cycleway:right on highways

### ISSUE THREAD

**Issue by ebrelsford** [openstreetmap/iD#2701]
Now that it will be easier to add cycleway:left and cycleway:right to a highway (fda81469), it would be awesome for the person editing to be able to see that the cycleway is on the road and _which side_ of the road they're putting the cycleway on. "Left" and "right" aren't always obvious in OSM since the direction of the way isn't always clear.

I have started a branch where I add another layer to the map (like `oneway`) that would render the cycleways on the appropriate side of the street.

Would this be an acceptable solution?

**Comment by bhousel** [comment]
Yes I think you'll definitely need to add some more layers to render the things that go on the sides of the road.  

I've thought it would be nice to put some code into [js/id/svg/lines.js](https://github.com/openstreetmap/iD/blob/master/js/id/svg/lines.js) to figure out all the different *uses* that a single way might be tagged with (railway/highway/cycleway/parking/sidewalk, with left/right) and then render these things as separate svg paths offset from the centerline a little bit.  It's a tricky problem.

But if you could get it working just for cycleways - that would be a start!

related: #1298 and #664

**Comment by ebrelsford** [comment]
Cool, I'll get going on it then.

**Comment by bhousel** [comment]
> Cool, I'll get going on it then.

Hey, just checking in!  Did you ever get very far with this?   
It is a difficult problem...

**Comment by bhousel** [comment]
stale
