### ISSUE TITLE
wish: easy keystroke to bring up or dismiss the radial menu

### ISSUE THREAD

**Issue by martenjj** [openstreetmap/iD#2706]
I know there are lots of issues and suggestions regarding the radial menu, but I'd like to add a simple one that would help in two situations that I've noticed that result in much frustration:

1.  Clicking on something that has lots of nodes close together results in the menu obscuring just the part that I'd like to work on.  There is no way to dismiss the menu apart from either clicking on some blank space, so deselecting the target object, or clicking on another part of it further away and then going back to the point of interest.

2.  I'd like to be able to perform a second menu operation on an object that is still selected after a previous operation (menu or keystroke) after it has disappeared.  For example, square and then move.  There seems to be no way to get the menu back apart from clicking on another part of the object.

Both of these could be addressed by having a single and easy to use keystroke - for example, Space - which would dismiss the menu if it is showing (but not change the selection or anything else) or bring up the menu if it is not showing (equivalent to a click on the currently selected line or node).

**Comment by bhousel** [comment]
Good idea, I like it..
