### ISSUE TITLE
wish: tags-only editor mode

### ISSUE THREAD

**Issue by andrisi** [openstreetmap/iD#2707]
No map data needed, and downloading them puts pressure on servers when I only want to edit a few tags on a given (big) relation. I'm trying to remove a tag from Lake Geneva, but loading fails in iD. Smaller areas load their maps OK, but what's the point if I only want to edit it's tags? Like Level0, just nicer.

**Comment by bhousel** [comment]
Yes, [the level0 editor](http://wiki.openstreetmap.org/wiki/Level0) is really more what you are looking for.  If you want improvements to that, please fork or open an issue under their [GitHub project page](https://github.com/zverik/level0).

Also, not sure if you have done this already, but I would definitely confirm with the French or Swiss OpenStreetMap communities before making changes to the tags on Lake Geneva.

**Comment by andrisi** [comment]
It was actually a duplicate of Lake Geneva, so it's OK. Level0 is OK, but iD's tag editor is much nicer, and so I thought a tag-only mode is no big deal to add. But OK.

**Comment by ImreSamu** [comment]
@andrisi  :
> I only want to edit a few tags  ...

maybe relevant :
*  "Direct editable tags in osm" http://www.openstreetmap.org/user/Aury88/diary/35165
*   Andy Allan : https://youtu.be/b6yRH5Ics7I?t=14m38s ( stateofthemap.us 2015 )

**Comment by andrisi** [comment]
@ImreSamu Thanks. I'm happy & not surprised that others come to this idea too. :-)
