### ISSUE TITLE
Integrate slide tool from Strava Labs

### ISSUE THREAD

**Issue by planemad** [openstreetmap/iD#2716]
[Dr Paul Mach](https://twitter.com/paulmach) work on the [strava slide tool](http://labs.strava.com/slide/) is a great addition to the drawing tools in Id. The tool can cut a lot of manual work that goes into creating smooth geometries and gives impressive results when used with GPS or custom raster imagery sources.

Slide to GPS data
![untitled](https://cloud.githubusercontent.com/assets/126868/8430730/47532cfa-1f51-11e5-95c9-a472a9f1f459.gif)

Slide to raster lines from TIGER
![untitled](https://cloud.githubusercontent.com/assets/126868/8430019/c051bfe2-1f4a-11e5-922c-8289c27d9718.gif)

- [Interactive demo](http://labs.strava.com/slide/demo.html#16/-122.54277/38.05392)
- [Slide tool homepage](http://labs.strava.com/slide/) 
- [Presentation on Slide at SOTMUS 2014](http://labs.strava.com/slide/slide-SOTM-2014.pdf)
- [Github Code](https://github.com/paulmach/slide)

**Use cases**
- Help tracing in areas that have GPS data but no OSM geometries
- Realigning poorly traced roads to GPS traces
- Quickly aligning old TIGER imports to accurate TIGER geometries using a custom raster layer

cc @bhousel @jfirebaugh

**Comment by bhousel** [comment]
Yes we love the Slide tool!

@paulmach thoughts on this?  I understand the heatmap data is licensed for tracing in OSM yes?

**Comment by planemad** [comment]
@bhousel for starters, we can already use TIGER as in the demo.

**Comment by paulmach** [comment]
The tiger stuff is fine. But that is probably less useful. The powers at be at Strava have decided that the heatmap layer should only be available on our version of iD.

**Comment by bhousel** [comment]
Closing this, as the Strava tool is available in their iD fork, and snapping to TIGER lines is only in rare cases likely to improve the basemap.
