### ISSUE TITLE
Close icon doesn't work after make a change

### ISSUE THREAD

**Issue by lupa18** [openstreetmap/iD#2717]
After making a change in editor mode, the left panel close button doesn't work. It always happen and attached image show the exactly place of problem. 

![seleccion_048](https://cloud.githubusercontent.com/assets/463429/8432865/8d9aa8be-1f10-11e5-8e64-d521dc8acf31.png)

When I click there, nothing happen so I must reload the page to have the whole screen again.

**Comment by bhousel** [comment]
> When I click there, nothing happen so I must reload the page to have the whole screen again.

You said that clicking on that 'X' does nothing.. Which browser are you using?

When I try clicking there, it does remove that "successful edit" text, and replaces it with iD's search box.  Is that different from what you see?

**Comment by lupa18** [comment]
I use Firefox 38.0 for Linux
Nothing happens. If you need I can make a video.

**Comment by bhousel** [comment]
Thanks for the report!  This seems to be a Firefox only issue, but it's fixed now.

**Comment by lupa18** [comment]
Problem appears again. This time in FF 40.0.3
