### ISSUE TITLE
support real osm tags in preset dialog 

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#2719]
As a power mapper I know the tag amenity = atm, but I have to guess the preset name in my translated language. 
So it would be nice if I could enter "atm" and get the right preset.

**Comment by bhousel** [comment]
We won't show the tag values, but with 8459995 it will now include the tag values in the search, so that if you do enter a tag value like `atm` it will be sorted a little higher than the other partial match suggestions.

**Comment by HolgerJeromin** [comment]
Thanks for the quick code. Will try it.

**Comment by bhousel** [comment]
Sure, you can try it now here:  http://openstreetmap.us/iD/master
