### ISSUE TITLE
German translation for man_made=embankment

### ISSUE THREAD

**Issue by xorx1** [openstreetmap/iD#2723]
Currently the German translation for embankment is "Fahrdamm", a type of elevated street. But the use of the tag is more like a "Böschung" (one sided descend).

My suggestion is to use "Böschung" as German translation.

**Comment by pnorman** [comment]
Translations are managed using Transifex. See [CONTRIBUTING.md#translating](https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating)
