### ISSUE TITLE
Unable to move way into desired location

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#2731]
With [way 244637266](https://www.openstreetmap.org/way/244637266) I am unable to move it to the desired location with the move tool

![image](https://cloud.githubusercontent.com/assets/1190866/8710996/cb1b60fe-2b02-11e5-894b-4fa3907b9740.png)

The red dot is where I want the right node to be after the move, and the blue parallelogram is the approximate area I can't get it to move into. 

The desired move makes more sense on other imagery

**Comment by bhousel** [comment]
I know that what's happening here is that the way movement code is trying to prevent you from crossing over the non-moving way.  But this is a case where the ways are only joined at that corner vertex, so they can't cross over each other.  I think I can improve it..
