### ISSUE TITLE
convert GPX track data to line (OSM way)

### ISSUE THREAD

**Issue by PaloTT** [openstreetmap/iD#2737]
In another OSM editors (Potlatch 2, JOSM) it is possible to direct convert track data from GPX files to OSM ways. Why is this feature missing in ID? Please add it to ID.
GPX file is standard for storing spatial data and not a synonym for a raw track log from GPS device. There is lot of third party tools where people can prepare (simplify, correct, etc.) their raw track GPS logs before adding data to OSM.

**Comment by bhousel** [comment]
Yes, some discussion of this on issue #2586.
