### ISSUE TITLE
Fix Delicatessen preset

### ISSUE THREAD

**Issue by adrianojbr** [openstreetmap/iD#2738]
the preset to "delicatessen" is incorret (shop=delicatessen), because the correct is shop=deli.

http://wiki.openstreetmap.org/wiki/Tag:shop%3Ddeli

**Comment by bhousel** [comment]
Hmm, looks like we already do have this preset as `shop=deli`, and it has been this way since it was added 2 years ago.  Is there a reason you opened this issue?
