### ISSUE TITLE
Make highway=proposed more distinguishably different from highway=unclassified

### ISSUE THREAD

**Issue by Skippern** [openstreetmap/iD#2740]
I have problems maintaining an area where long stretches of proposed highway seems to never get ahead of the proposal, the problem is that these proposed stretches makes part of official highway networks, but users of iD seems not to be able to see them so easily as being proposed, and keeps deleting them **as they don't exist**. All of these are part of route relations, so I had the impression after several discussions about breaking relation, they where advised about this. I think the best solution is to make these proposed highway clearly distinguishable from other highways, the current colouring makes them quite similar to unclassified highways (I know, light greyish and white are not the same colour). I suggest to make it clearer, for example an intermittent line, or a thinner line, something that avoids the confusion with constructed highways.

One example of a [proposed stretch of BR-484](https://www.openstreetmap.org/way/300894984/history)

I don't think it have been deleted on purpose, I believe that they have thought it as wrongly mapped and tried to correct the map. Therefor I think this is a highly needed correction of the style presentation.

**Comment by matkoniecz** [comment]
I am not sure whatever it would help with iD users, but for highway=proposed it is highly valuable to add also source=* to show that it is really a road "about to be built" ( http://wiki.openstreetmap.org/wiki/Tag:highway%3Dproposed ).

**Comment by Skippern** [comment]
All of the stretches I talk about form part of a ``route=road`` type relation forming the complete official extension of those federal roads.
The ones I have had to restore have all been deleted by iD users, I don't know if it is because JOSM users are more advanced and knowledgable of the use of ``highway=proposed``, or that JOSM and other editors are showing them distinctively different than other highways. I just noticed that in iD these where represented almost equal to already built highways, and are guessing that users are given the wrong impression.
If it is necessary I can go through them all and add ``source=DNIT`` and ``note=Proposed highway, do not delete``, but I am afraid that this will still not give the users enough hint to leave them.

**Comment by matkoniecz** [comment]
I though about something like source=https://dnitwebsite/path/document_confirming_route_and_timeline_of_construction.pdf

**Comment by Skippern** [comment]
That one is tricky as there is no clear document I know off stating a construction timeline, some of these have been on the drawing board as proposed for 50 years, where actual road itinerary is negotiated with, but still not approved by IBAMA (environmental agency), funding priority too far down on the list, etc. But I can include link to shapefile where this have been taken from.
I am loading all of these now to add ``note=`` and ``source=`` to all those that are part of the federal highway system (leaving the others as they would need separate confirmation from other sources)

Adding ``source=DNIT`` and ``source:url=http://www.dnit.gov.br/mapas-multimodais/shapefiles``, but it doesn't change the fact that iD displays proposed highways too similar to existing highways

**Comment by bhousel** [comment]
I put some thoughts on lifecycle tagging on #2347 and #2341... 

I don't think I can make a status field now, but improving the styling of the lines and adding a `source` field sound like easy improvements.

**Comment by Skippern** [comment]
I was basically just asking to change the style so that it is different from ``highway=unclassified`` by something more than a slight shade of grey
