### ISSUE TITLE
GPS trace not displayed in "Map" mode

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#2741]
I do not know if it is related to #2450 but currently if I go in top-right menu ["GPS Traces"](http://www.openstreetmap.org/traces) and select "more" option near a trace (for instance using [this one](http://www.openstreetmap.org/#map=14/44.9002/5.55638)), my map box matches the GPS traces bounding box, but the trace is not displayed. If I select "edit" instead, it works great but I guess this is due to the fact that these 2 options do not use the same API according to #2450.

I thought it was an issue with visibility of the trace so I tried a public GPS trace (link above) but it seems there are no differences. Same behavior on Firefox (Debian), Chrome (Debian) and also Firefox (Windows).

**Comment by bhousel** [comment]
I think when you say "Map" mode, you mean the [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website) project.   I also see that clicking a "map" link from a GPS trace list seems to only take you to the location but not display the trace, so you could try opening an issue in their repository and see if it's something that is supposed to work.
