### ISSUE TITLE
Render highway=road differently from highway=unclassified

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#2742]
`highway=road` is a temporary tag. 
Right now in iD it seems OK to use the tag. I saw it on a normal parking aisle and other pretty clear (from the surrounding osm data) cases.
I have no idea how to reduce the usage. Painting ugly or give a warning would be some ideas.

**Comment by matkoniecz** [comment]
JOSM renders highway=road as ugly red line and gives validator warnings.

**Comment by bhousel** [comment]
In iD we are already:
* calling the preset "Unknown Road"
* sorting it below everything else (which makes it kind of hard to find)
* pulling from the wiki the description "Highway with unknown classification"
* rending it as a generic (ugly?) grey line

If I saw a new user in my neighborhood doing this, I'd simply message them and ask them why they added the road that way.. If they really don't know which preset to pick, `highway=road` seems appropriate.

**Comment by HolgerJeromin** [comment]
> rending it as a generic (ugly?) grey line

The same rendering is used for unclassified, so the user is used to this presentation. :-/

**Comment by bhousel** [comment]
> The same rendering is used for unclassified, so the user is used to this presentation.

Oh you are right, I guess we should render them a bit differently than `highway=unclassified`.  Honestly I'm not used to seeing those, and I don't know a situation where I would use one in the US.

**Comment by bhousel** [comment]
`highway=road` now renders thinner and darker than `highway=unclassified`

![screenshot 2015-07-29 19 00 09](https://cloud.githubusercontent.com/assets/38784/8972026/152a12c2-3624-11e5-81c2-a783699a0faf.png)

**Comment by HolgerJeromin** [comment]
You sadly did not fixed the reported problem at all. 
A user loading an area is not invited to change a road. 
He has to read the description to get a slight hint that this tag is not optimal on the long run. 

Id users will continue to produce roads and josm users will stumble over them and fix them.
