### ISSUE TITLE
Lat/Long Search in IDeditor

### ISSUE THREAD

**Issue by mobina** [openstreetmap/iD#2745]
Dear Sir,

   We are planning to include Lat/Long search in the editor. Please Suggest me to implement on this?

**Comment by bhousel** [comment]
It's already a feature of iD:  Just type Lat/Long into the search box..

![screenshot 2015-07-30 05 41 32](https://cloud.githubusercontent.com/assets/38784/8980346/cc83ee3a-367d-11e5-9d41-8f5830beb59a.png)
