### ISSUE TITLE
USGS Large Scale Imagery, Topo Maps Not Loading

### ISSUE THREAD

**Issue by jonahadkins** [openstreetmap/iD#2747]
Having issues with USGS Imagery & Topo Maps not loading. Have confirmed with other users as well.

Errors in Chrome:
* USGS Imagery:   
  * `Failed to load resource: the server responded with a status of 502 (Bad Gateway)`  
  * `Mixed Content: The page at 'https://www.openstreetmap.org/id#map=18.40/-76.58646/37.15031' was loaded over HTTPS, but requested an insecure image 'http://b.tile.openstreetmap.us/usgs_large_scale/7/36/49.jpg'. This content should also be served over HTTPS.`

**Comment by maxerickson** [comment]
The issue is with the openstreetmap.us server. See:

https://twitter.com/iandees/status/630466006482309120

**Comment by jonahadkins** [comment]
:+1: :+1: :+1:
