### ISSUE TITLE
iD's Locator overlay shows things at null island

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#2751]
If you go to https://www.openstreetmap.org/edit?editor=id#map=13/-0.0068/0.0278 with iD's locator overlay enabled, you notice "Black River", "Blue Street" etc.

They probably shouldn't be there.

**Comment by bhousel** [comment]
@ericfischer is the Mapbox locator overlay something you know about?  I know it probably lags the data by a little while, and there is no garbage data showing there now.

**Comment by SomeoneElseOSM** [comment]
Actually, the most recent "Blue Avenue" was pretty recent:

http://www.openstreetmap.org/way/364466827/history

**Comment by ericfischer** [comment]
The locator overlay style might be pointing at an old data source. I'll
check when I get to the office.

**Comment by bhousel** [comment]
@ericfischer any update on this?

**Comment by ericfischer** [comment]
All I can say for sure is that it's not in general pointing to old data because it has picked up recent changes of mine [like this one](http://www.openstreetmap.org/changeset/33608484). This tile must have failed to update some other way and I'll try to figure out how.

**Comment by bhousel** [comment]
With 2d987a3, I'm blacklisting null island data from the iD side, as it doesn't look like it can be fixed easily upstream.

**Comment by SomeoneElseOSM** [comment]
Re https://github.com/hotosm/learnosm/issues/335 ("Cat Forest" etc.), Learnosm have created a JOSM ticket for it: https://josm.openstreetmap.de/ticket/12731 .

**Comment by bhousel** [comment]
@SomeoneElseOSM, yes edits have appeared here and been cleaned up, but there is some issue with generating the overlay tiles that makes it unlikely for this to get fixed soon.

I also found that it's a good idea to blacklist Mapillary data around here too.
