### ISSUE TITLE
Terms preset does not work properly

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#2756]
If I understood it correctly, `terms` list in `preset` are synonyms for one kind of structure. For instance, given the [French presets](https://github.com/openstreetmap/iD/blob/7b4c6d2a1603dfda73f8e7f417b1b3c088ec72b7/dist/locales/fr.json), `Digue` should be equivalent of `Terre-plein` (for key `embankment`). However if a select a line and type `Digue`, `Terre-plein` is the 32nd of 34 total results while it should have been the 1st.
The same goes for other words (`WC` is not leading to `toilets`, etc.), so am I misinterpreting these `terms` or is something wrong?

Using iceweasel 40.0 on Debian 4.1.5-1, same behavior on 2 different computers as well as on Windows/Firefox. French installed on both computers but one has iceweasel in French while the other has it in English.

**Comment by M1dgard** [comment]
Same here.
Steps to reproduce:
1. set your OSM account to Dutch
2. open the iD instance at osm.org
3. add a point
4. search for 'wc'
Expected result: 'Toiletten' is the top match
Actual result: 'Toiletten' isn't even in the list at all

**Comment by bagage** [comment]
OK, I think I found the reason behind that semi-random behavior. `terms` array must be filled with synonyms **[lowercase](https://github.com/openstreetmap/iD/blob/master/js/id/presets/collection.js#L25)  AND [comma-separated (without space)](https://github.com/openstreetmap/iD/blob/master/js/id/presets/preset.js#L49)**. For instance, `amenity/toilets` for French is:

> "terms": "Toilettes, WC"
 
To work properly, it must be changed to:

> "terms": "toilettes,wc"

I am not sure where the fix should be though. Some solutions could be:

1.  `preset.terms` should trim terms after splitting?
2.  `collection.search` should convert to lowercase everything when comparing 2 strings?
3.  format `presets.json` and all translated JSON so that `preset.terms` are correctly formatted. Must be done automatically after fetching new translations from Transifex (maybe in `Makefile`). This solution is not needed if both 1) and 2) are done.

**Comment by M1dgard** [comment]
> OK, I think I found the reason behind that semi-random behavior. terms array must be filled with lowercase AND comma-separated (without space) synonyms.

No, that should not have any impact. It is true that lowercase and without spaces is preferable, but it is not necessary to have the search work.

**Comment by bagage** [comment]
What is doing the work for it then? I tried on a local copy and had it working only by changing as mentioned. But I am not `js` programmer so I believe you. However I could not find the code handling that; can you point me in its direction? :)

**Comment by M1dgard** [comment]
I haven't looked at that code myself, I was told so by an iD developer some time ago. IIRC it splits on commas and then calculates the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance).

**Comment by M1dgard** [comment]
This seems to be the relevant code:
https://github.com/openstreetmap/iD/blob/master/js/id/presets/collection.js#L75, but I am not really familiar with the code.

**Comment by bagage** [comment]
Well, Levenshtein distance is not the only method used; basically `search` is documented to do the following. It will compare  the given value converted to lowercase:

1. with all presets' name (**lowercased**)
2. then all presets' terms (**not lowercased**)
3. then all presets' tags (**not lowercased**)
4. then levenshtein distance for all presets' name (maybe is it case insensitive, but not sure about that)
5. then levenshtein distance for all presets' terms (maybe is it case insensitive, but not sure about that)
6. then it concatenates all these result in the order above (not sure about that totally).

So even if levenshtein distance will find the result some time, in will not give the expected result - when a given input value is **exactly** a `term` value, it should be the first in the results list . And moreover, Levenshtein may not behave correctly to trailing space nor case issues while it should not affect results list.

**Comment by M1dgard** [comment]
Observation of the app's behaviour:
1. changing the case does not affect the search results
2. putting a space in front of your word does, but it still doesn't find our toilets in the Dutch version.

**Comment by bagage** [comment]
What did you modify? [In `nl.json` there is only one entry in `terms` which is `WC`](https://github.com/openstreetmap/iD/blob/master/dist/locales/nl.json#L1745). If you change it to:

>                 "terms": "wc"

Then recompile the application entirely with `make clean && make` (otherwise it seems to not be reloaded). Then launch `python -m SimpleHTTPServer` and try again. It is working for me, I do not see why we would get different behaviors.

**Comment by M1dgard** [comment]
I was trying on the production version on osm.org. Will try locally now.

**Comment by M1dgard** [comment]
Seems you are right. Without capitals it finds it.

**Comment by M1dgard** [comment]
I am working on this. I first changed js/id/presets/preset.js # 49:
```js
/*from*/ return preset.t('terms', {'default': ''}).split(',');
/* to */ return preset.t('terms', {'default': ''}).toLowerCase().split(',');
```
but then I thought: why make the client do all that work, when we can settle this at `make translations`-time. Now I am learning lodash to accomplish this.
