### ISSUE TITLE
Mouseout event outside of map container creates a point while panning

### ISSUE THREAD

**Issue by deepankverma** [openstreetmap/iD#2758]
Working with editor, sometimes when map is out of view, holding and dragging  MMB results in click and thus point is made unnecessarily.

**Comment by M1dgard** [comment]
This is not the middle mouse button, but the left one.

**Steps to reproduce**, on [master](http://openstreetmap.us/iD/master/):

1. Enter Point mode
2. Start panning the map (click with LMB and move your mouse to the left)
3. End your pan movement above some other control element than the map view, and release LMB

**Expected result**: No point is created, just like when you pan and release while still hovering the map.
**Actual result**: A point is created upon releasing the LMB.

**Comment by bhousel** [comment]
Just adding a note to myself, [look here] at what `point()` is doing.  (https://github.com/openstreetmap/iD/blob/90bc645e441b27785ef2862ed4fc2cd08cc7d4ce/js/id/behavior/draw.js#L36-L37)
