### ISSUE TITLE
POIs are hidden with "No Fill" option

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#2759]
Unexpected behaviour or misleading text labels:
1. open http://openstreetmap.us/iD/release/#map=20.00/-77.02271/38.90085 (1.7.0)
2. press F
3. disable everything but "Points" in "Map Features"
observe: POIs are visible (for now)
4. set "Fill Areas" to "No Fill (Wireframe)"
observe: POIs are invisible
expected: POI are still visible

**Comment by M1dgard** [comment]
This has already been fixed in master, the fix will be available in the next release. When reporting bugs, you should use http://openstreetmap.us/iD/master/: this is always the bleeding edge version.

**Comment by M1dgard** [comment]
@bhousel Please close.

**Comment by bhousel** [comment]
yes this was #2591
