### ISSUE TITLE
Rename "Access" section to "Legal access"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#2761]
It would reduce confusion of how this tags are applied.

It is common mistake to tag for example bicycle=no because way is not suitable for bicycles (but using it is perfectly legal) or using bicycle=yes to mark way where using bicycle is illegal but infrastructure itself is friendly for cyclists.

See http://wiki.openstreetmap.org/wiki/Key:access "For describing the legal accessibility of a element."

Inspired by https://lists.openstreetmap.org/pipermail/tagging/2015-August/026211.html

**Comment by matkoniecz** [comment]
Note - maybe there is better phrase than "Legal access" to specify that it is about legal status. I am not a native speaker.

**Comment by d1g** [comment]
Yes, I was forced to translate it incorrectly as *legal access* in order to prevent damage to access tags/user confusion.

[smoothness](https://wiki.openstreetmap.org/wiki/Key:smoothness) may be considered as candidate for impassibility tag: 

Some Russian users use following surface/smoothness table to get measure of impassibility/average speed: https://wiki.openstreetmap.org/wiki/User:Danidin9/Variants_of_smooth_surfaces

**Comment by M1dgard** [comment]
@d1g Or [mtb:scale](https://wiki.openstreetmap.org/wiki/Key:mtb:scale) specifically for (mountain)bikes

**Comment by systemed** [comment]
"Legal access" isn't very clear. P2's dropdown is:

Pedestrians permitted: [Allowed/Prohibited/Designated/Destination]

and similarly for 'Bicycles permitted'. It could probably be shorter still:

Pedestrians: [Allowed/Prohibited/Designated/Destination only]

**Comment by d1g** [comment]
@systemed 
> "Legal access" isn't very clear

User faced with **access table**, not single dropdown in iD

> Pedestrians permitted: [Allowed/Prohibited/Designated/Destination]
> and similarly for 'Bicycles permitted'. It could probably be shorter still:
> Pedestrians: [Allowed/Prohibited/Designated/Destination only]

Every case will be **always** displayed to user (unlike drop down). Currently there 5 cases:
* access=* tag
* foot=* tag
* bicycle=* tag
* horse=* tag

Values yes/no/permissive/private/destination/designated are not translated ATM but user will be given title with very detailed description in their language.

"Legal access" is just caption/title for that table.

**Comment by matkoniecz** [comment]
@d1g Entire section may be edited - it would require more work but effects seems to be better (the only negative effect is further hiding tags from mapper).

**Comment by d1g** [comment]
@matkoniecz if you hide translated definitions even deeper it would be even worse. There shouldn't be be contest who have to memorise every tag before he is ready to make his first edit.
"Legal access" table: accesss "for everyone", foot "for pedestrians", bicycle "for cyclists"

I don't see problem that legal access tags will be hidden with meaningful captions and efficiently replacing tags.

There no tools to operate on tags in iD other than simple text window. No filter, no search function, no editing tabs in table, no copy/paste for tags and many others.

**Comment by bhousel** [comment]
We already do display the wiki image and description if the user clicks the tag help button:

<img width="359" alt="screenshot 2015-08-31 07 39 17" src="https://cloud.githubusercontent.com/assets/38784/9580339/e3b8408a-4fc6-11e5-9f5f-610e18527489.png">

Unfortunately this image and description is not very helpful.

**Comment by bhousel** [comment]
Like @systemed says above, in the English language the phrase "Legal Access" is not very clear.  It sets the bar much higher than just "Access" and would likely put users off from entering anything here.  I work with lawyers extensively, and I know even most of them would be reluctant to offer a legal opinion of whether a horse can be taken down a cycleway.

That said, I would like to make this field as clear as possible, and to let users know that this is not about "physical suitability". 

How about "Allowed Access"?

**Comment by bhousel** [comment]
Also I'd like to avoid using the phrase "permitted", even though we use that phrase loosely in American English to mean that you can do something, I wouldn't want anyone to think that it means "permit required".

**Comment by M1dgard** [comment]
> I work with lawyers extensively, and I know even most of them would be reluctant to offer a legal opinion of whether a horse can be taken down a cycleway

If you don't know for sure whether you can ride a horse on a cycleway, then don't map it. Are you saying you would put `horse=yes` on a way even if you're not 100% sure you can ride a horse there?

**Comment by matkoniecz** [comment]
"Allowed Access" also seems better than simple "Access". It seems worse than "Legal access" - but I am not a native speaker.

**Comment by bhousel** [comment]
> If you don't know for sure whether you can ride a horse on a cycleway, then don't map it. Are you saying you would put horse=yes on a way even if you're not 100% sure you can ride a horse there?

All I'm saying is that "legal access" makes it sound like you need to be a lawyer to use the field.
