### ISSUE TITLE
Legal Access All = Yes displayed when there's no such tag

### ISSUE THREAD

**Issue by mourner** [openstreetmap/iD#2763]
Here's a [cycleway](http://www.openstreetmap.org/way/26534273) without any access tags:

![image](https://cloud.githubusercontent.com/assets/25395/9574797/7d5b1dcc-4fca-11e5-8451-9d81f8d087fa.png)

When looking at the tags for the same cycleway in iD, it says "Legal Access - All - Yes" instead of "not set" (sorry for Russian, didn't find a way to change the language):

![image](https://cloud.githubusercontent.com/assets/25395/9574820/ae14f1c2-4fca-11e5-8986-52c48fe45aeb.png)

This is the reason why mappers won't set legal access tags on cycleways, leading to them never being considered for walking routes (this is how I discovered the bug).

cc @bhousel @Zverik

**Comment by bhousel** [comment]
This is what the cycleway access tag box looks like in English.
Is the issue that those strings aren't being faithfully translated, maybe by someone who wants to push the "legal access" issue #2762? 

We don't currently use the phrase Legal Access in English.

<img width="358" alt="screenshot 2015-08-31 09 48 34" src="https://cloud.githubusercontent.com/assets/38784/9580151/a5abe856-4fc5-11e5-9330-4614572aa6d3.png">

**Comment by mourner** [comment]
@bhousel why does it say "General - yes"? It looks like it implies that everyone is allowed on the path (especially in the Russian translation which looks "For all") so no need to set specific access e.g. foot.w

**Comment by bhousel** [comment]
It could probably be better.  That field supplies the value for the generic `access=*` tag, and might be read as "default access".  Except that really the defaults depend on the [kind of highway and regional convention](http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions).  The greyed out values are be the implied access values, as best that iD can figure them out.

More about `access=*` from [osm wiki](http://wiki.openstreetmap.org/wiki/Key:access#Transport_mode_restrictions):

>Use the access=* key to describe a general access restriction that applies to all transport modes.
 
That might be where the "general" word came from?

>Note, that, for example, adding access=yes to highway=footway changes default restrictions (which usually are foot=yes and vehicle=no for highway=footway) to yes, highway=footway + access=yes means "road, which is open for all pedestrians and vehicles". 

iD doesn't actually do this in the UI.  If you add an explicit `access=yes` to a footway, we don't switch the implied `motor_vehicle=no` over to an implied `motor_vehicle=yes`.  I think we had an issue for this last year, and my gut tells me what iD does is more expected and what the wiki says is wrong.

**Comment by matkoniecz** [comment]
> what the wiki says is wrong

Where wiki may be wrong?

**Comment by bhousel** [comment]
> Where wiki may be wrong?

Does adding `access=permissive` to a sidewalk really mean you can drive on it with a car?

Common sense says no, but the part of wiki I quoted above says yes.  I'm inclined to just remove the general access tag completely if we all agree that the meaning of this tag really is to clobber over every other kind of implied access tag.

**Comment by matkoniecz** [comment]
Note that access=yes/permissive is either pointless or resulting in really strange results - but access=private/no makes perfect sense in many cases.

**Comment by bhousel** [comment]
Oh I think I understand.  We should really show "Unknown" not "yes" for the "General" box.  Is that it?

**Comment by matkoniecz** [comment]
It would encourage people to set "access=yes" everywhere, with all problematic consequences. I think that "not set" would be slightly better - but it still too encouraging to set something.

Maybe rename "general" to "everything" with "not set" for ways without set "access" tag? But it still not great.

**Comment by bhousel** [comment]
Maybe I could display this field only if it already has a value.  Then we are not encouraging users to put a value into it - they'd need to use the raw tag editor for that.

I agree with renaming "General" to "Everything", so that people understand what the field really implies.

**Comment by matkoniecz** [comment]
Using "access" for completely closed ways is perfectly OK (and better than [foot=no, vehicle=no, horse=no, (...)]).

Maybe rename "General" to "Everything", hide if not set and add button that would add no/private. I wonder though about naming it - "mark as generally inaccessible"?

The main goals IMHO are
- discourage slapping "access=yes" on everything
- do not discourage using "access=no" or roads closed completely, with some exceptions ("access=no, emergency=yes" tagging is perfectly fine)
- show access=no/yes properly
- avoid problem described by reporter
- show other values of access properly (some are clear mistakes like access=designated, some are valid access=customers - http://taginfo.openstreetmap.org/keys/access#values )

**Comment by bhousel** [comment]
> do not discourage using "access=no" or roads closed completely, with some exceptions ("access=no, emergency=yes" tagging is perfectly fine)

I usually see these tagged as `access=emergency` and nothing else.

But ok, I think I have some ideas on how to improve these.

**Comment by bhousel** [comment]
Here's what I have changed, they are little improvements but I think they help:

* The `access

<img width="358" alt="screenshot 2015-09-06 22 21 10" src="https://cloud.githubusercontent.com/assets/38784/9708150/a5bb675c-54e5-11e5-88ff-205ef00ba7ad.png">

**Comment by mourner** [comment]
The changes look great to me. That would certainly solve the original issue.

**Comment by bhousel** [comment]
Thanks @mourner, just merged it in.
