### ISSUE TITLE
Incomplete preset translations are a Really Bad Thing™

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#2766]
Okay, incomplete core translations look unprofessional, but they can be used.

On the other hand, preset translations where the labels have not all been translated, result in a very frustrating editing experience, potentially scaring away new mappers.

Consider this scenario:

You use iD in Norwegian (`no`) and search for a swimming pool by typing the Norwegian word `svømmebasseng`. You find what you want to map.

But if you want to map a vending machine, and search for `salgsautomat`, you don't find anything.

You decide to try the English term `vending machine` and find what you are looking for, because iD obviously falls back to English if no translation is present yet.

Now you may have realised that the translation is not complete<sup>[note 1]</sup>, and that you will not find everything in Norwegian. Then you want to map a town hall and based on this experience you decide to search for the English term right away. **However, you won't find the preset**, because the label has already been translated (`Rådhus`).

It was upon realizing this that I completed iD's translation to Dutch<sup>[note 2]</sup>. Unfortunately, I am not sufficiently fluent in Bosnian, Chinese (Yue), Korean, Chinese (Hong Kong), Arabic, Greek, Persian, Turkish, Serbian, etc to translate to those languages as well, and I don't know if and when they will be completely translated.

___

**Notes**

1. Not everyone may realise this. It would be useful to display some warning somewhere if not all labels are translated.
2. The attentive reader may note that Dutch has a translation completeness of 86% on Transifex. This is because of the terms lists, which were deliberately left blank if I could not think of synonyms and related terms.

**Comment by bhousel** [comment]
I agree that they are a Really Bad Thing.  Is there anything actionable we can do about it?  Maybe to improve `Rådhus` we could also include the English tag value 'town_hall' in the terms list? 

I did send an update on Transifex to the translators today to let them know we are releasing soon.  We need to do a better job keeping them engaged, I'm not sure best way to do it.

**Comment by M1dgard** [comment]
Well, it's a lot of work if you're alone. If you're not, you have to make some agreements on how you will translate or you will end up with am incoherent translation. This is basically out of your control of course. The glossary function on Transifex can be a huge help.

Firstly I'd not include translations with too low a completion rate (say 62%). You'd need to know English anyway if you wanted to use them.

Secondly, I'd just include all English terms and labels as well in searches, be it with a somewhat lower priority rate. (Is that feasible?)

**Comment by M1dgard** [comment]
And thirdly display a warning when you start searching for presets if not all labels have been translated. Something like: 'Not all features have been translated into your language. Also try the English term if you don't what you're looking for.' And maybe also something along the lines of 'If you'd like to help translate iD into {Language}, check out the project on <a ...>Transifex</a>.'

**Comment by matkoniecz** [comment]
> Maybe to improve Rådhus we could also include the English tag value 'town_hall' in the terms list? 

It may be a good idea, especially for incomplete presets.

**Comment by bhousel** [comment]
So I spent some time digging into this tonight and.. iD already does include OSM tag values in the preset search. (As a test, I forced the language into Chinese, and I was able to use iD easily by typing OSM tags into the search box, despite not being able to read the language at all.)

Instead of changing the search code, maybe this instead:  I could add a small "help translate" icon down by the "report a bug" icon.  This could push a lot of users to the Transifex project that otherwise wouldn't know about it.

Crappy mockup:

<img width="615" alt="screenshot 2015-09-18 23 46 25" src="https://cloud.githubusercontent.com/assets/38784/9974507/51dd0eae-5e60-11e5-950c-6b87070c171b.png">

**Comment by pnorman** [comment]
> I could add a small "help translate" icon down by the "report a bug" icon.

This would be a good idea, probably linking to the https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating page.

Would it be shown for all languages, all languages except en (en_US), or only languages with incomplete translations?

The latter two would show it for en_GB, since en_GB falls back to en_US for much of its text.

**Comment by bhousel** [comment]
I think I'll just show it for everyone. There are probably users browsing in `en` or `en-US` that would help translate if they knew how to.

**Comment by jfirebaugh** [comment]
Also, please turn down requests on Transifex for country-specific translations like "Danish (Denmark)" -- these are almost always confused users who actually wanted to help with an existing translation like "Danish". Here's the message I send to the user after denying such requests:

> Hi ___,

> You requested a ____ (____) translation for iD. Unless there is a specific reason you require a country-specific translation, please join the team on the existing ____ translation: `<link>`.

> Thanks for your help!

> John

**Comment by bhousel** [comment]
FWIW, I received this response from a language requestor today:

>Sorry for the confusion, as I'm new to Transifex. I had no idea my language choices were for the iD translations. These are the languages I am fluent in (and their respective locale) and that I could contribute to. I thought I was filling out my profile.

I believe this, because I also find Transifex's UI pretty confusing.
