### ISSUE TITLE
Set of prompt selections for conflicts with another user restarting endlessly

### ISSUE THREAD

**Issue by SHARCRASH** [openstreetmap/iD#2768]
I got a set of prompt selections for conflicts with another user (22 in total) during a long edit (+/-224 edits if i recall correctly). Some were not for edits that happened at the same time during mine, I believe some were about the former edits that were already in place, others indeed from a user that edited the same elements in between. That's not the big issue though. After having compared all prompts in favor of mine because far more influent (positionning, MP integrations, corrections...), I encountered a second set of prompt selections (3 of them which were part of the first set), i responded again but at the saving the second set was endlessly restarting itself. Had to save the XML... *sigh* 

Further I closed the window, told myself that maybe if i relaunch what's temporarily saved, the bug will disappear. I got only 152 edits back.

Please, can someone upload my edits too? 

By the way i know 224 edits is exaggerated but i enter often huge edits because of massive MP integrations

I do this because :
- it's easier to create complex areas
- it makes areas of multiple elements more clear while keeping its precision (less parallel or interconnected lines)
- it lowers data usage
- since Mapnik changed its Forest & Wood tiles with a transparency, the transparency will over tile the inner element if no relation is defined, many users plotted inner areas without relations, so now proper MP integration will be needed to be set or there will be errors in OSMi (in my home country Luxembourg, it's often near zero errors)
- last but not least, for future edits in those MP, it's way easier and less time consuming, full beneficial.

**Comment by bhousel** [comment]
Do you still have the xml file?  Can you share on Dropbox or another file sharing service?

I think you hit the bug in #2735 that has been fixed already..

**Comment by SHARCRASH** [comment]
Thank you for the fast reply!  :)
Trying for the first time Drive, you should be able to access it here :
https://drive.google.com/file/d/0BzU9J1u6HDyCUWpyQUd4dThjaGM/view?usp=sharing

Will check the other topic, tomorrow, it's near midnight here.

**Comment by bhousel** [comment]
Looking into it more, I think some of this has been fixed already.. Do you still have the history saved in your browser?  Meaning, when you start iD, does it offer to restore your edits?  Or did you clear them?  

If you still have them, you can try your save again when when we release the new version in a few days...

**Comment by SHARCRASH** [comment]
No the history didn't come up after i rebooted my computer. The XML i saved is all what is left. Can you import those changes in OSM's database?

**Comment by bhousel** [comment]
I've never tried this, but I did try to make the XML something that JOSM can process.  There is some possibly helpful info [here](https://github.com/openstreetmap/iD/issues/1053#issuecomment-48415079). 

I really don't know how to help, but someone on IRC or the [help forum](https://help.openstreetmap.org/) may be able to.

**Comment by SHARCRASH** [comment]
I installed JOSM and can't run it, it needs to run an older Java version than the one i have now... So even if it will add security risks i tried download the older version. I click on the DL button and... i have to sign in... seriously???! This is crazy... it's the drop that makes the ship sink!

**Comment by tyrasd** [comment]
@SHARCRASH I've uploaded your changes in http://www.openstreetmap.org/changeset/33814222. Please check if everything is alright now.

I'm wondering why JOSM won't run on your machine. Have you tried the [webstart](https://josm.openstreetmap.de/) version? Perhaps this is something you should report on [JOSM's bug tracker](https://josm.openstreetmap.de/newticket#ticket)?

**Comment by SHARCRASH** [comment]
Thank you! Really appreciated! :) Yeah, the big picture seems right.

I tried to reinstall Java... it seems that it was the source of the problem. JOSM starts normally now.
