### ISSUE TITLE
Safari 9 fails to load during Raven setup

### ISSUE THREAD

**Issue by friedbunny** [openstreetmap/iD#2769]
Safari 9 fails to initialize (on http://openstreetmap.us/iD/master/) and throws the following console error:

```js
TypeError: Attempting to change access mechanism for an unconfigurable property.
   defineProperty master:47
   (anonymous function) master:47
```

<img width="769" alt="screen shot 2015-09-03 at 6 06 44 pm" src="https://cloud.githubusercontent.com/assets/1198851/9672271/2ed2d448-5267-11e5-8658-7bb8924e3233.png">

/cc @bhousel @1ec5

**Comment by jfirebaugh** [comment]
I don't think the canary ever helped. We can remove it.

**Comment by bhousel** [comment]
removed!
