### ISSUE TITLE
Zooming under heavy load can translate the map center far away

### ISSUE THREAD

**Issue by andrew-hill** [openstreetmap/iD#2773]
I find that occasionally when I'm editing, and zooming in/out at a time when the browser is for whatever reason under heavy load (usually zoomed out a little and there's a lot of editable features on-screen), a small zoom/scroll gesture during that second of high-CPU will send my viewport to some random place on the earth.

e.g. just now it went from 33ºS 151ºE (in Sydney) to about 38ºS 178ºE (somewhere in the ocean, many thousands of kilometres away).

I get that zooming might go 'too far' in or out when scrolling, but to translate the viewport vast distances across the world doesn't really make sense. I'm seeing it quite a bit if I zoom in and out a lot, almost always ending up looking very closely at a random section of the ocean—at first I thought the rendering had just failed and would have to exit the editor and reload OSM, not realising it'd just moved to an area with just a lot of near-black tiles.

I've seen this on both Safari and Chrome (up-to-date versions of both as of July/August 2015) on Mac OS X.

**Comment by bhousel** [comment]
I have noticed this a few times also..

**Comment by andrew-hill** [comment]
I'm no longer sure the "heavy load" is the cause, as I just had it happen after waiting for the 'heavy load' to end. There's something about the way it renders after zooming that makes me realise it's about to happen (its happening a lot!), though I'm not exactly sure what it is. This time I intentionally stopped interacting and waited a few seconds after trying to zoom and realising it was going to happen. Despite waiting for it to settle, as soon as I tried to pan the viewport it did the random jump (to somewhere in the northern hemisphere this time). So it looks like the *pan* action is what's triggering the jump, though its always in my case preceded by a zoom-out action.

**Comment by SHARCRASH** [comment]
I came in here to report a similar/same issue in Firefox.  :) The viewport starts zooming in and out randomly. Had even tried to switch off my wireless mouse.

**Comment by SHARCRASH** [comment]
Weird... it just happened that entering/exiting the visual wired mode (ctrl+w) triggers that random zooming.

**Comment by pnorman** [comment]
I've seen this a couple times, but only ever in busy complex areas, and mainly on pan.

#2757 might be related

**Comment by abellao** [comment]
I'm still seeing this bug with Chrome 50 on a Macbook.

**Comment by trakais** [comment]
I can easily repeat this, I would even go as far as to say, that editing is unusable. This happens every 5 seconds or so. I have a MagicMouse with touch scroll and have suspicion that this is related to the touch scrolling.

**Comment by kepta** [comment]
I spent some time investigating this bug.
In my opinion the problem originates whenever   [`zoomended`](https://github.com/openstreetmap/iD/blob/master/js/lib/d3.v3.js#L1822-1825) is called prematurely and zooming didn't actually end.

Let us focus on mousewheelTimer inside function [`mousewheeled`](https://github.com/openstreetmap/iD/blob/master/js/lib/d3.v3.js#L1968) dispatches  [`zoomended`](https://github.com/openstreetmap/iD/blob/master/js/lib/d3.v3.js#L1822-1825).

I believe bug arises when `zoomended(dispatch)` is called and it clears `centre0. Then some event occurs probably `zoomstart` and calls `mousewheeled` to only get center0 being null.


``` Javascript
 // js/lib/d3.v3.js#L1968
  function mousewheeled() {
    var dispatch = event.of(this, arguments);
    if (mousewheelTimer) clearTimeout(mousewheelTimer);
    else translate0 = location(center0 = center || d3.mouse(this)), d3_selection_interrupt.call(this), zoomstarted(dispatch);
    mousewheelTimer = setTimeout(function() { mousewheelTimer = null; zoomended(dispatch); }, 50);
    d3_eventPreventDefault();
    scaleTo(Math.pow(2, d3_behavior_zoomDelta() * .002) * view.k);
    translateTo(center0, translate0);
    zoomed(dispatch);
  }
```

What we have here is a complicated d3 event calling going on. @bhousel could you please comment on these findings, do they actually lead to the bug ?

**Comment by bhousel** [comment]
That is awesome analysis, I know the d3 internals can be tricky to know what's going on.  I'll try to reproduce it using your steps above..

Can you check on the [d3 repo](https://github.com/d3/d3) to see if this is a known bug with zooming?  

They are almost ready to release d3 v4 and I know a lot has moved there..

**Comment by kepta** [comment]
@bhousel [this](https://github.com/d3/d3/issues/2205) issue exactly describe the bug we are facing. 

And I am happy incorrectly diagnosed the bug 😬, the [patch](https://github.com/d3/d3/pull/2351) for this bug mentions similar things. 

How to go about patching our copy of d3 with it?

**Comment by bhousel** [comment]
> How to go about patching our copy of d3 with it?

You can just patch [d3.v3.js](https://github.com/openstreetmap/iD/blob/master/js/lib/d3.v3.js#L1971) directly, but make sure to add a note to the Makefile with the commit hash [here](https://github.com/openstreetmap/iD/blob/master/Makefile#L318) so we don't forget and need to rebuild `d3.v3.js` later.

Alternatively you can upgrade d3 in package.json and try to rebuild it and apply those other changes mentioned in the Makefile.  This is more work though, and I kind of think it's not worth the trouble of upgrading d3 until v4 lands (any day now).

**Comment by kepta** [comment]
okay you left me confused, version bump is out of the option as v4 will land soon.

Do you want to patch d3.v3.js or just hang on until v4 lands ?

**Comment by bhousel** [comment]
It's up to you, you can bump d3 to something newer on the 3.x branch that includes the mouse wheel fix.. Just that rebuilding it is a pain so patching is probably easier.

**Comment by kepta** [comment]
I can't wait for v4 and this bug really annoys me.
So I will probably patch `d3.v3.js` and send a PR.
