### ISSUE TITLE
Unable to click on View this image on Mapillary link

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#2775]
When I mouse to where the red dot is, I see the mapillary image in the bottom right

![image](https://cloud.githubusercontent.com/assets/1190866/9747776/9f309088-5634-11e5-95c2-57c579690544.png)

if I click, then mouse to "View this image on Mapillary" the image disappears once I am off of the symbol, so I cannot click on the link.

**Comment by pnorman** [comment]
Might be #2151 related

**Comment by bhousel** [comment]
The way markers get selected and hovered in #2720 is a little different now, so there should be an improvement with this.  One thing I also changed is that the thumbnail will now get positioned on the opposite side of the screen from the hovered marker.  Previously there were problems trying to hover over a marker on the right side of the screen and have the Mapillary image pop up on top of the marker.
