### ISSUE TITLE
Housing Preset for Semi-Detached

### ISSUE THREAD

**Issue by rossgoodacre** [openstreetmap/iD#2776]
I am based within the United Kingdom and a large number of our residential properties are semi-detached houses i.e. one property attached to another, this is a common configuration within the UK. 
As it stands the OSM editor feature attribution pane only contains values for terraced houses, house or residential buildings. Given how common semi-detached houses are within the UK I feel it is important that we add this option to ensure the most accurate attribution possible.

I realise this may seem trivial, however I think it is much more efficient to add this field when the data is being generated as opposed to revising the data at a later stage.

Regards

Ross

**Comment by bhousel** [comment]
Sounds good.  Although there is no wiki page for this, the most popular tag for this seems to be [`building=semidetached_house`](http://taginfo.openstreetmap.org/tags/building=semidetached_house), with 19,996 uses.

Less common is [`building=duplex`](http://taginfo.openstreetmap.org/tags/building=duplex) with 4850 uses.

**Comment by M1dgard** [comment]
@rossgoodacre Please create documentation for this on the wiki (with status De Facto). Personally I am strongly against adding undocumented values in editors.

**Comment by M1dgard** [comment]
Also you typed 'House**s**' implying that both houses can be covered by a single Area, which is probably not how it's meant to be used?

**Comment by M1dgard** [comment]
`building=semidetached_house` seems to be the result of [this import](https://wiki.openstreetmap.org/wiki/Rostocker_Geb%C3%A4udeumrisse_Import_2009) in 19,826 of the 19,995 occurences. The importers fancied creating a whole new tagging scheme for buildings: [Rostock: Gebäude und Strukturen](https://wiki.openstreetmap.org/wiki/Rostock:Geb%C3%A4ude_und_Strukturen). Please remove this from iD, wait for an approved tag (or have this one approved) and add it.

**Comment by bhousel** [comment]
Well @rossgoodacre made a good suggestion and a tag already exists with 20,000 uses for the thing he wants.  I don't see a problem with it.

It's not his (or anyone's) job to make wiki pages, proposals, or mechanical edit scripts to cleanup the tag data.

**Comment by bhousel** [comment]
> Also you typed 'Houses' implying that two connected semi-detached houses can be covered by a single Area, which is probably not how it's meant to be used?

Oh true, I will fix this, it's probably wrong.  They should ideally be mapped as 2 separate areas (because they likely have 2 separate addresses).

**Comment by M1dgard** [comment]
Ok, I'll bring it up on tagging so it can be canonized.
