### ISSUE TITLE
Arabic strings in map view are not joined when they are placed on a non-horizontal line

### ISSUE THREAD

**Issue by forabi** [openstreetmap/iD#2778]
The first image is a screenshot of iD showing an Arabic name for a street. The characters are not joined and the name is completely unreadable. In addition, they are placed in reverse order.
![screenshot from 2015-09-14 22-06-40](https://cloud.githubusercontent.com/assets/1012761/9859065/0a919708-5b2d-11e5-95a0-fd88a475b5bb.png)
The same street on Google Maps is rendered correctly:
![screenshot from 2015-09-14 22-07-21](https://cloud.githubusercontent.com/assets/1012761/9859063/09f3127c-5b2d-11e5-9bc0-a4ae4067ca74.png)

**Comment by morteza1618** [comment]
It seems the problem is with all languages that use the same alphabet, e.g., Farsi. It also happens in the horizontal lines.

![screen shot 2015-09-30 at 3 32 07 pm](https://cloud.githubusercontent.com/assets/4723941/10208538/d18ffc5c-6788-11e5-818d-796e3a989f84.png)

**Comment by jfirebaugh** [comment]
This is a browser bug that iD isn't going to be able to work around, unfortunately. See #1806 / https://code.google.com/p/chromium/issues/detail?id=374526.
