### ISSUE TITLE
Inconvenient or impossible to "switch" a line feature to an area feature

### ISSUE THREAD

**Issue by Circeus** [openstreetmap/iD#2782]
In the database, there is technically no difference between a line and an area, at least as far as the data goes.

iD however makes it very difficult to apply tag it has assigned to a feature format to another. The example everyone will inevitably run into eventually is that of drawing an area using the line tool (i.e. because it's more convenient for very large or elaborate areas) or various actions on an area (replacing/deleting tags, splitting the way and deleting the relation this creates), It is impossible to apply area tags to such a feature without first selecting an arbitrary setting and then manually typing in your tags.

This is extremely counterintutive behavior especially for newcomers who are otherwise working very well with the editor. Similar issues often creep up with certain PoI tags wanting to be used on linear features (e.g. tourism=artwork for murals)

**Comment by jfirebaugh** [comment]
Yep, this is a known issue -- see #1828.
