### ISSUE TITLE
the map is old

### ISSUE THREAD

**Issue by BOSAQER** [openstreetmap/iD#2783]
Maps in Saudi Arabia is very old.
Hofuf no bridge and tunnel underneath him, but he does not exist on the map.
It may not have finished working on it, but you must update the lunar imaging for the Middle East in particular, and I will Odamkm.

Regards BO SAQER
msaqrm@yahoo.com

" Excuse me, there may be an error in the speech because I do not speak English, and this speech was translated by Google Translate.
 Greetings "

**Comment by jfirebaugh** [comment]
Hi @BOSAQER. The background imagery in iD comes from external sources and OpenStreetMap doesn't have control over getting updates to it. See this FAQ item for how to report an issue to the folks that do: https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery
