### ISSUE TITLE
Replace png assets with svg

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2785]
These things are all available in svg and will look much better on retina.  Using svg would also eliminate the extra build step generating the png.

- [X] line preset icons -> move to `sprite.svg`
- [X] relation preset icons -> move to `sprite.svg`
- [X] Maki
- [ ] cursors?  check browser support first.
- [X] cleanup `/svg` folder

capturing convo w/@samanpwbb

**Comment by bhousel** [comment]
Rolling most of this into #2811, will merge what is done in the next few days, and consider svg cursors another time.

**Comment by sisskind** [comment]
@bhousel Having an issue getting the SVG icons to appear.  Have run the ```npm install``` command and make clean && make, but just getting blank icons.  Is there something I am missing?

**Comment by bhousel** [comment]
We did have an error in the makefile that was causing the svg sprite to not get built unless `svg-sprite` was in your path.  Are you testing this with latest code from `master`?

You can also try `rm -rf node_modules` and the redo the `npm install` step.  This sometimes can clear things up, e.g. if you got stuck with an unlucky combination of dependency versions.

**Comment by tmcw** [comment]
According to [this document](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_User_Interface/Using_URL_values_for_the_cursor_property), SVG cursors aren't supported in WebKit and [this testcase](http://bl.ocks.org/tmcw/3478294ed1ea794f552e6f0f011bd3f3) confirms that.

**Comment by bhousel** [comment]
Thanks for checking!  We'll close this..
