### ISSUE TITLE
Key "1" toggles fullscreen 

### ISSUE THREAD

**Issue by schlasim** [openstreetmap/iD#2786]
Key "1" toggles fullscreen mode in Chrome and Firefox under Ubuntu 12.04

**Comment by bhousel** [comment]
That's weird... Is it possible the "1" key is sending "F11"?

**Comment by ernop** [comment]
I'm seeing this in Windows 7 in firefox, too.  It's not the browser full
screen that's linked to "1"; it looks like more of an OSM thing.

repro steps:

1. open opensteetmap.org
2. click edit
3. F11 (normal browser full-screen) top OSM bar still visible (with my
username, etc.)
4. press 1 to select "point"
5. this triggers some other kind of fullscreen, and a popup "OSM is now
fullscreen".   In this view, the map takes up the entire vertical height of
the window.  Pressing 1 repeatedly toggles this kind of fullscreen on and
off.

**Comment by tyrasd** [comment]
Well, the keybinding here: https://github.com/openstreetmap/iD/blob/master/js/id/ui/full_screen.js#L67 doesn't actually bind to the `F11` key, because `iD.ui.cmd` decomposes the identifier to `f+1+1` (which is [later](https://github.com/openstreetmap/iD/blob/master/js/lib/d3.keybinding.js#L72-L76) interpreted as a simple `1` keypress.

**Comment by bhousel** [comment]
> Well, the keybinding here: https://github.com/openstreetmap/iD/blob/master/js/id/ui/full_screen.js#L67 doesn't actually bind to the F11 key, because iD.ui.cmd decomposes the identifier to f+1+1 (which is later interpreted as a simple 1 keypress.

Oh you are right @tyrasd.. 

Funny thing is I actually did test this in Chrome, Firefox, and Safari, but never noticed the issue because `iD.ui.cmd` [exits early on Mac](https://github.com/openstreetmap/iD/blob/110b8b6b6df30c0da90e09ff04913e9f6f9ed59f/js/id/ui/cmd.js#L4-L5).

**Comment by ernop** [comment]
I am seeing this behavior again today on firefox & chrome in windows on
http://openstreetmap.org/

**Comment by bhousel** [comment]
> I am seeing this behavior again today on firefox & chrome in windows on http://openstreetmap.org/

Yes I haven't made a new release yet.. I'll fix a few more bugs and do it soon!
