### ISSUE TITLE
Measurement Tool does not calculate polygon perimeter correctly

### ISSUE THREAD

**Issue by sisskind** [openstreetmap/iD#2789]
When you create a polygon feature, the measurement tool only measures the lines created by the user.  If the user double-clicks to create polygon, the last segment is not included in the perimeter measurement.  Double-checked with line tool.  Will open an issue - but wanted to document here.

Created line feature with perimeter = 318 meters
![image](https://cloud.githubusercontent.com/assets/6191659/10140586/51d5487c-65d6-11e5-8ca7-4f0275dc7623.png)

Created polygon snapped to line segment and double-clicked to complete polygon, with perimeter = 207.8 meters
![image](https://cloud.githubusercontent.com/assets/6191659/10140604/6af3bed8-65d6-11e5-8d7f-1b08ca654f7a.png)

**Comment by bhousel** [comment]
Good catch, thanks!
