### ISSUE TITLE
Presets created unusual spelling of values

### ISSUE THREAD

**Issue by stephankn** [openstreetmap/iD#2791]
Observed multiple unusual values for surface: "GRAvel" and "CONcrete".

User claimed to have only used ID presets. Please check presets for usage of uncommon spellings.

happened for multiple users. Samples:

http://www.openstreetmap.org/way/362188660
http://www.openstreetmap.org/way/332720872

**Comment by stephankn** [comment]
I can't figure out how the "presets" of surface are filled. Does it just suggest based on common tagging it sees in the database? Something like top20 values in Taginfo?

If so the GUI could be improved to help novice users distinguish manual, verified "presets" from "suggested" values which need to be better checked before using.

**Comment by pnorman** [comment]
> Observed multiple unusual values for surface: "GRAvel" and "CONcrete".
> 
> User claimed to have only used ID presets. Please check presets for usage of uncommon spellings

They probably had caps-lock on.

**Comment by stephankn** [comment]
So it is a UI usability issue. That user had the impression to chose a value from a predefined list, not entering his own value. So probably less care was taken on what was entered, because "if editor offers it then it must be right".

How could the UI be changed so it is clear that this is a freetext field in the editor which just has suggested values?

**Comment by pnorman** [comment]
> How could the UI be changed so it is clear that this is a freetext field in the editor which just has suggested values?

I'm not sure that's the solution here. I think the case of someone inputting text in caps and it autocompleting to something in lower case needs handling.

**Comment by bhousel** [comment]
> I think the case of someone inputting text in caps and it autocompleting to something in lower case needs handling.

Yeah, if they pick a value from an autocomplete list we should fix the capitalization.
