### ISSUE TITLE
Presets depend on tag order, users unable to see real presets

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#2793]
Currently iD depends on tag order. I.e. for object tagged as

    building=retail 
    shop=mall
iD will display preset for building=retail

    shop=mall
    building=retail 
iD will display preset for shop=mall

Same with any other tag combination: building=* + real POI tag (shop=pet + building=yes)

Should we fix iD or should we sort tags<s> in database</s>?

**Comment by bhousel** [comment]
> Should we fix iD or should we sort tags in database?

We should probably bump down the priority on `building` presets so that other tags match first.

**Comment by d1g** [comment]
@bhousel that't neat. But how exactly "priority" works:

1. It may rank/sort presets when user searches by presets (lets call it "search_rank")
2. it may pick different preset when user selects some object(s) (lets call it "pick_rank")

In this issue we talk about case 2, scenario 1 should be ranked by another tunable variable IMO. Otherwise you will "bump down" priority of "buildings" but they are still important in the regions without buildings.

If I were developing iD, I would consider search_rank as "country-specific" in configs, so users would get more useful suggestions in default presets. "country-specific" tags/presets was a long awaited feature in Russian community. Some tags/presets will never useful in some territory. Other country-specific tags will also benefit from search_rank feature, even it may be hard to implement/maintain correctly.

**Comment by d1g** [comment]
But actually country-specific settings/ranks may be activated per each instantiation of editor. I.e. openstreetmap.org front-end should spawn iD with configcountryA, configcountryB since this functionality was implemented already. 

But case 2/ "pick_rank" is still relevant.

**Comment by pnorman** [comment]
> Should we fix iD or should we sort tags in database?

Tags have no order.

**Comment by d1g** [comment]
@pnorman good note, yes this statement was imprecise. I meant that tag order is important after we fetch data from db. I shouldn't mention db here.
