### ISSUE TITLE
Invalidate upload of highway=footway AND bicycle=designated

### ISSUE THREAD

**Issue by geowOSM** [openstreetmap/iD#2796]
Please consider presenting a warning - like JOSM does - before uploading highway=footway AND bicycle=designated.
bicycle=designated should require highway=path/track/cycleway.

Thanks!

**Comment by bhousel** [comment]
How would I explain a nuance like this to a user who really know much about OSM tagging and just wants to put their favorite walking path on the map?

**Comment by geowOSM** [comment]
In the interest of quality assurance IMHO an editor should at least warn users (popup etc), if they are likely to upload inconsistent data. Regardless if they create new entries or mess with existent data.

The combination of highway=footway with bicycle=designated is clearly invalid, because a footway is mainly or exclusively for pedestrians. Nonetheless iD will not warn the user or provide information, that highway=path or cycleway would be more appropriate, if a way is designated for bicycle or foot and bicycle. 

The distinction footway vs path might appear at first sight as a nuance, but it's a profound difference both for data consumers and for human map users. 

BTW: The standard presets for path in ID are OK. Even a casual mapper will have no trouble creating a foot path with consistent tags: Line  > Path > Foot Path > Allowed Access: Foot=designated und Motor Vehicles=no.

**Comment by bhousel** [comment]
> The combination of highway=footway with bicycle=designated is clearly invalid, because a footway is mainly or exclusively for pedestrians.

I'm not convinced that this is "clearly invalid".  Taginfo suggests that the combination is used around 18,000 times, and the [`highway=footway` wiki page](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway) says that footways can have bicycle access tags too.

If there were a dedicated effort to deprecate this tagging and remap the keys to something else, then I would agree, but as it stands now I think JOSM is just being a little too fussy with its warning.

**Comment by matkoniecz** [comment]
> If there were a dedicated effort to deprecate this tagging and remap the keys to something else, then I would agree, but as it stands now I think JOSM is just being a little too fussy with its warning.

This JOSM warning is a part of effort to deprecate this tagging and remap the keys to something else.
