### ISSUE TITLE
More relevant wiki link for type=multipolygon preset 

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#2797]
Still present in openstreetmap.us/iD/master/:
https://wiki.openstreetmap.org/wiki/Key:type - current link won't help them
https://wiki.openstreetmap.org/wiki/Relation:multipolygon - better link with images and translations

**Comment by tyrasd** [comment]
Hm. The issue appears to be that [taginfo's API](https://taginfo.openstreetmap.org/api/4/tag/wiki_pages?key=type&value=multipolygon) doesn't return a `description` for the respective tag and therefor [triggers](https://github.com/openstreetmap/iD/blob/9248ad7d5b5811ceec3e11c75d09d256b7b6981f/js/id/ui/tag_reference.js#L43) the fallback to the key-only case which does get a description from [taginfo](https://taginfo.openstreetmap.org/api/4/key/wiki_pages?key=type).

Not sure if this is to be fixed on taginfo's side or in iD. //cc @joto

**Comment by tyrasd** [comment]
Ah, I almost forgot that taginfo has a separate API endpoint for [relation types](http://taginfo.openstreetmap.org/taginfo/apidoc#api_4_relation_wiki_pages). That one [returns](https://taginfo.openstreetmap.org/api/4/relation/wiki_pages?rtype=multipolygon) a proper description.

I guess iD should use this special taginfo endpoint for values of the `type` tag on relation objects, right?
