### ISSUE TITLE
Users confuse building type with POI proper

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/iD#2799]
When doing a review and cleanup of mappers' edits, I noticed there are numerous times when users place building=school on a node (which in itself is incorrect) and don't add amenity=school to that point. In presets we have "School Building" vs "School Grounds" which is not exactly intuitive.

What about moving building type from presets to a drop-down? This could ease the confusion a lot.

**Comment by bhousel** [comment]
> What about moving building type from presets to a drop-down? This could ease the confusion a lot.

We do have a building type dropdown for some area type amenities, but we specifically don't have this for ones where the current recommended tagging is to map property separate from the buildings on it. (schools, hospitals, maybe a few others).

I think for presets with this kind of ambiguity, we can just remove `node` as allowable geometry for the `building=*` preset.  Then if a user starts by entering a node, they are only offered the `amenity` when they search for the preset type.

**Comment by RicoElectrico** [comment]
Honestly, I would go even further. Having seen very brain-dead things made by newbies I think we would be better off by changing the workflow from "select node/line/area, then select a preset" to the opposite. This way you can easily convey which geometry types are allowable for given presets.
Users sometimes mark POIs as very crooked areas that aren't cartometric (because imagery isn't that great) even though a point could be better.
As per buildings themselves - some really struggle to understand how to draw them. The proposed workflow change would make it possible to insert some context mini-help before drawing is started.
