### ISSUE TITLE
Relation: Add to Scattered (Non-Local)

### ISSUE THREAD

**Issue by ax3l** [openstreetmap/iD#2805]
When adding a local area to a relation, this only works if there are already local elements in the zoomed area.

Adding to a "scattered" relation, e.g., "great surfing spots in Switzerland" won't work because the current selected element will be de-selected on zoom-out/zoom-to-next-element (assume: Switzerland shall be large and has great beaches on various adjacent oceans).

If one could search for global relations by name this would help. Currently only "close by relations" and "new relation" is suggested and one needs to go to an other editor to fix/update relations that contain elements that are not close by.

**Comment by bhousel** [comment]
> Adding to a "scattered" relation, e.g., "great surfing spots in Switzerland" won't work because the current selected element will be de-selected on zoom-out/zoom-to-next-element (assume: Switzerland shall be large and has great beaches on various adjacent oceans).

My understanding is that these kinds of group-by-category relations are strongly discouraged by the OSM community...  So I really don't think we should change iD to support them at this time.

**Comment by ax3l** [comment]
good to know, thanks!
