### ISSUE TITLE
Discard yh:WIDTH tags

### ISSUE THREAD

**Issue by planemad** [openstreetmap/iD#2806]
As per recent [talk-ja discussion](https://lists.openstreetmap.org/pipermail/talk-ja/2015-October/009128.html), the `yh:WIDTH` tag from the Yahoo Import of Japan is ok to discard as it holds inconsistent values that are not usable.

This can be added to the list at https://github.com/openstreetmap/iD/blob/master/data/discarded.json and would greatly help in the [Japan OSM data cleanup process]( https://github.com/mapbox/mapping/issues/120)

**Comment by pnorman** [comment]
> As per recent talk-ja discussion, the yh:WIDTH tag from the Yahoo Import of Japan is ok to discard as it holds inconsistent values that are not usable.

It's worth making sure that similar issues are opened up on JOSM and P2 to keep the lists in agreement

**Comment by planemad** [comment]
@pnorman filed in JOSM as well https://josm.openstreetmap.de/ticket/11969
