### ISSUE TITLE
Impossible to add turning restictions

### ISSUE THREAD

**Issue by massic80** [openstreetmap/iD#2807]
I'm trying to add turning restrictions on this node
http://www.openstreetmap.org/node/3102914057
but looks like it's impossible. Arriving from Corso Regina, heading west, you can't turn left (to south).
There is no apparent way to indicate it.

**Comment by pnorman** [comment]
![image](https://cloud.githubusercontent.com/assets/1190866/10522882/63ec8dbe-732c-11e5-8662-4aa931f4405b.png)

Possibly related: clicking on the intersecting oneway road doesn't bring up the turn restrictions

intersecting is http://www.openstreetmap.org/way/154889905, which is circular. If I manually cut the circular way at some  other point, everything works

**Comment by bhousel** [comment]
This bug happens when the intersection vertex is also the start and end node on the (circular) intersecting way. Fixing this now..

**Comment by massic80** [comment]
Hi,
I re-tried adding the turn-left restriction when reaching the node from Corso Regina Margherita heading west, but still find out how...
Massi

**Comment by bhousel** [comment]
The fix hasn't yet been released yet to the main OpenStreetMap site.  I will probably do a release soon.
 
But for now, can you try to use the latest iD in the link below and let me know if it allows the turn restriction?
https://openstreetmap.us/iD/master/

**Comment by massic80** [comment]
Hi,
looks like working :)
Massi
