### ISSUE TITLE
Cannot open Minimap on Non-US keyboards

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#2812]
The keyboard shortcut to open the minimap (#2554) is the slash `/` character, which is input on a German keyboard layout via `shift`+`7`. iD doesn't trigger the minimap-toggle when pressing this key combo. Strangely, pressing the `#` character on a German keyboard opens the minimap on Chrome, but not on Firefox.

I'm assuming this is because of using the `keyCode` property [here](https://github.com/openstreetmap/iD/blob/0543f684d2b431eb64f3918bad344f50d3c17733/js/lib/d3.keybinding.js#L75), which seems to be a [bit broken](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode):

> Web developers shouldn't use the keycode attribute for printable characters […] especially those input with the Shift or Alt key pressed. When implementing a shortcut key handler, the keypress event is usually better.

**Comment by bhousel** [comment]
Hmm, yeah keycode detection is kind of broken.  

It's hacky, but maybe for now (in lieu of changing `d3.keybinding`) we can find a keycode on the German keyboard that isn't used for anything.

What codes do you get when you visit this jsfiddle, and try keys like ä,ö,ü,ß
http://jsfiddle.net/YKeye/

**Comment by tyrasd** [comment]
character | keycode (chromium) | keycode (firefox) | keycode (old presto based opera)
------------ | ------------- | ------------- | -------------
`/` | 55 (then 16 on releasing the shift key) | 55 (then 16) | 55 (then 16)
`ä` | 222 | 0 | 222
`ö` | 192 | 0 | 186
`ü` | 186 | 0 | 219
`ß` | 219 | 63 | 109

It's a mess! :poop:

**Comment by Abbe98** [comment]
This is broken using Swedish and Norwegian keyboards too.

**Comment by bhousel** [comment]
I did some research today, and yeah it's a mess.  This will hopefully get better when [DOM Level 3 Keyboard Events](http://www.w3.org/TR/DOM-Level-3-Events-key/) are implemented in all browsers, but that's a long way off.

For now some decent resources are [Unixpapa's summary](http://unixpapa.com/js/key.html) and [this implementation](http://stackoverflow.com/questions/5306132/translate-javascript-keycode-into-charcode-for-non-u-s-keyboard-layout-i-e-az) by the noVNC developer.

**Comment by bhousel** [comment]
Check French keyboard too, per #3660

**Comment by manfredbrandl** [comment]
at the latest preview '/' (Shift-7) now works on my German keyboard

**Comment by magol** [comment]
And it works on Swedish keyboard to 😀

**Comment by tyrasd** [comment]
perfect
