### ISSUE TITLE
Locator overlay in minimap sometimes misaligned

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#2813]
After panning around a bit by panning directly in the minimap, I got to a state where the locator overlay is largely misaligned from the minimap's content, see below:

![selection_083](https://cloud.githubusercontent.com/assets/1927298/10639085/91cd2cf2-780e-11e5-9555-f7170b0dd534.png)

(tested in Firefox and Chromium)

**Comment by brianreavis** [comment]
To reproduce: toggle any overlay. This causes `map-in-map-overlay` to be placed *after* `map-in-map-gpx` (which has the block svg in it, which bumps the overlay layer down the height of the SVG)
