### ISSUE TITLE
Core iD OSM data types as separate module

### ISSUE THREAD

**Issue by gmaclennan** [openstreetmap/iD#2817]
According to https://github.com/openstreetmap/iD/blob/master/ARCHITECTURE.md#core

> [iD] eventually aims to be a reusable, modular library to kickstart other JavaScript-based tools for OpenStreetMap.

This is great, but iD is not currently written in a way that allows just these core types to be included in other projects. I have made an initial attempt at extracting these core types in [iD-core](https://github.com/digidem/id-core). It essentially picks the relevant pieces from iD and joins them together.

There is some complexity around instantiating presets and making tests work. I would love [any feedback](https://github.com/digidem/id-core/issues) and recommendations about how to do this right.

**Comment by bhousel** [comment]
Just took a look - glad you got something working!

I guess at one point there was an effort to refactor iD core into node-flavored commonjs as supported by browserify, but it needs a restart.

#889
#890 
#891

**Comment by bhousel** [comment]
I'm closing this here just because #890 covers it..
