### ISSUE TITLE
Pressing 1 selects Point AND screen goes into Full Screen

### ISSUE THREAD

**Issue by Stalfur** [openstreetmap/iD#2820]
This is the weirdest thing I've seen and we've had some strange things going on.

Using Chrome and Firefox on different PCs, if I press 1 to select Point feature, then screen goes into Full Screen just like if I had pressed F11.

This is consistent and my Chrome console also reports this:

requestFullscreen() is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by bhousel** [comment]
Yeah this was reported as #2786 and fixed in b365a20.
I'm hopefully rolling a new release this week with the new osm-carto colors, so it will go with that.
