### ISSUE TITLE
Support Microsoft's Edge browser

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#2822]
Trying to start iD in MSs new browser for W10 results in a wide sense of the word in a crash, the symptoms seem to vary between returning to the main map display to an in browser error display.

**Comment by bhousel** [comment]
> Trying to start iD in MSs new browser for W10 results in a wide sense of the word in a crash, the symptoms seem to vary between returning to the main map display to an in browser error display.

Weird, I just tried using Edge and it seems to run really well for me.  I didn't test too extensively, just tried a few presets, looked at the side panels, traced a few buildings and saved.  It feels like a faster version IE11 - meaning, everything pretty much works but the oneway markers are missing.

Of course I did just download a fresh vm for it this morning, and tested against the latest master branch of iD with the svg icons, so I could just be using a lucky combination of things.

I did notice that it got hung up on the oauth challenge the first time I tried to save.  But I closed Edge and opened it again, restored my changes and was able to save ok the second time.  This probably isn't an iD issue.

**Comment by simonpoole** [comment]
Interesting I just tried on a different machine and it works there. Might be a problem with the setup on my laptop, I'll see if I can nail it down any better.

**Comment by simonpoole** [comment]
Half repeatable, just tried again first attempt errored again then after refreshing it seems to work. However I can still repeatedly get it to fail, but not if I have the debugging console open (grrrrrrr).

Edge version see screenshot

![screenshot 2015-11-05 23 13 06](https://cloud.githubusercontent.com/assets/1011860/10983482/f7becede-8412-11e5-93ad-716e8677965e.png)

**Comment by bhousel** [comment]
Tested some more today and it looks good to me.  I'm considering Edge "supported" at this point, with the caveat that it is unreleased software.  Going to make an announcement on the mailing lists to ask for people to take a look.
