### ISSUE TITLE
Austrian background imagery: use basemap.at instead of Geoimage.at 

### ISSUE THREAD

**Issue by wernerschka** [openstreetmap/iD#2823]
Dear iD-Team.
I would recommend to use basemap.at (maptype "Orthofoto") Imagery instead of the former Geoimage.at for Austria. For general information about this map, have a look at http://basemap.at/index_en.html
Both are from the same organisation (geoland.at) with the same licensing when using in Openstreetmap. By the way, we already use basemap.at within iD (maptype "Standard", so maybe you should change its name within iD's background map list to "basemap.at Standard")

Basemap.at is the latest, newest free mapping portal of Austrian federal states. It is kind of successor of the former geoland.at WMS-service. Even if the most of the Imagery is the same within both services, the ones of basemap.at are of better image-quality (JPEG-compression, brightness...), in some areas newer (e.g. Vienna), and have less image-artefacts (like zig-zag lines at a straight edge of a building).

The Tilemap-URL template is:
http://maps{s}.wien.gv.at/basemap/bmaporthofoto30cm/normal/google3857/{z}/{y}/{x}.jpeg
where {s} could be 1,2,3,4
Maxzoom level=19

**Comment by pnorman** [comment]
iD doesn't have an imagery list, it pulls from https://github.com/osmlab/editor-imagery-index

**Comment by wernerschka** [comment]
I see. Should I open the same issue there?

**Comment by tyrasd** [comment]
@wernerschka: Yes, please!
