### ISSUE TITLE
Can we make 100% brightness default?

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#2824]
The default brightness when you start is really dark, and people (especially newbies) don't know to change it. I did a mapathon in my neighborhood a couple weeks ago and everybody was struggling. Can we make 100% brightness the default? I think that would make it easier from the beginning. Thanks.

**Comment by bhousel** [comment]
sounds good!

**Comment by aawiseman** [comment]
It looks like it's still at 25% for me when I log in from a new browser

**Comment by bhousel** [comment]
I haven't released it yet to the main openstreetmap.com site.
Can you test this on https://openstreetmap.us/iD/master ?

**Comment by aawiseman** [comment]
Ah, that would explain it! Woo, it works! Thanks!
