### ISSUE TITLE
Change tags of multiple items at once

### ISSUE THREAD

**Issue by wernerschka** [openstreetmap/iD#2831]
Hi iD-Team!
The feature I'm missing most in iD is to change tags of multiple selected items at once. 

For example: I want to just add name & ref to a 10 Km-road, which consists of 100 consecutive 100 meter ways. Right now i've to select each way, and add name+ref 100 times! :-(
Much better would be to multi select (by holding down "Shift" or "Ctrl"-key) and left click lets say 30 or even each of the 100 ways and then ONCE assign name+ref to all of them.

That would improve and speed up tagging of long roads dramatically.

**Comment by jfirebaugh** [comment]
Thanks for the suggestion. See #1761 where this has previously been requested.
