### ISSUE TITLE
The editor doesn't indicate data loading errors

### ISSUE THREAD

**Issue by ignace72** [openstreetmap/iD#2832]
Hello,
The editor no longer displays any data, no road, no building, no trade, nothing. There's just a satellite photo.
Someone has any idea of the problem?
Thank you
Ignace

**Comment by Synesso** [comment]
I tried an alternate editor in case it was a problem with iD. Potlatch reported "There was a problem loading the map data. Please check your internet connection, or try zooming in."

**Comment by ignace72** [comment]
So it is a server problem.
Wholesale: Take a break, you're working too hard.
Thank you. I'll try in a few hours to see if it is arranged.

**Comment by bhousel** [comment]
Yep, the API is currently down. It's not an issue with iD.
http://stats.pingdom.com/p310g2klasry/435275

**Comment by tyrasd** [comment]
But, there's still the issue that iD silently ignores API errors and doesn't indicate that there may be a server outage. A user may think that data is simply missing and start mapping stuff. When only the cgimap part of the API is down (as it seems to be the case right now), OSM still accepts uploaded changesets (http://www.openstreetmap.org/changeset/35428589 :confounded:).

**Comment by bhousel** [comment]
Yes, I agree it's a real problem.  We really do need to restrict edits where the map is not completely loaded, and make it clear to users what happened.  

Let's keep #2262 as "Handle API failures gracefully" issue, and #2248 as the "Don't let users edit there" issue.
