### ISSUE TITLE
iD: Logged out between selecting a tile and going to the next screen. 

### ISSUE THREAD

**Issue by SuzanReed** [openstreetmap/iD#2833]
Several times tonight (PST 1 to 2 AM) I have selected a tile in #1133 - Nara Circle (Mali) where I have been mapping for some time, I click on iD to begin mapping, and I am directed to a screen that says I need to log in. I log back in, and when the next screen appears with the arial image, I am in the general area, but there is no magenta square. 

SReed
Suzan Reed
MacBookPro  OSX Yosemite
Chrome v.Version 46.0.2490.86 (64-bit)

**Comment by bhousel** [comment]
Yes, the servers powering the OpenStreetMap API had some issue last night - see #2832

**Comment by SuzanReed** [comment]
Thanks, Brian. Good to know. 


On Nov 19, 2015, at 6:04 AM, Bryan Housel <notifications@github.com> wrote:

Yes, the servers powering the OpenStreetMap API had some issue last night - see #2832
