### ISSUE TITLE
Support for additional external changeset tags.

### ISSUE THREAD

**Issue by maxerickson** [openstreetmap/iD#2834]
A recent discussion on the talk mailing list raises the issue of separating project tracking information out of changeset comments. Starts here:

https://lists.openstreetmap.org/pipermail/talk/2015-November/thread.html#74992

A prerequisite for making this work for HOT would be support in id. I don't have a patch, but looking at #2311 I gather that deciding what to do would be a bigger problem than the implementation. It's also not entirely clear if there is really widespread buy-in for omitting hashtag like stuff from comments.

**Comment by bhousel** [comment]
Yes I'm following the discussion.  I agree that this is a case where getting community consensus is more work than the actual implementation itself.  I'd happily add another field for tags next to the changeset comment field, and make it settable via the api, if that's how the discussion shakes out.

**Comment by maxerickson** [comment]
There is also already a tracking bug here: https://github.com/hotosm/osm-tasking-manager2/issues/703

**Comment by pnorman** [comment]
There are a number of common changeset tags like `import`, but those wouldn't normally be used within iD.

**Comment by bhousel** [comment]
> I'd happily add another field for tags next to the changeset comment field,

Sorry @pnorman I just re-read what I wrote and I realize it's confusing.  I meant that I'd add another field for *hashtags*.

**Comment by pnorman** [comment]
This issue is about changeset tags, not trying to encode information in the comment where we have structured alternatives.

**Comment by bhousel** [comment]
> This issue is about changeset tags, not trying to encode information in the comment where we have structured alternatives.

Yes exactly - the proposal is to add a new changeset tag (TBD but named something like `hashtags`), if I understand it correctly.

**Comment by maxerickson** [comment]
One way to implement `hashtags` would be to support adding arbitrary tags to the changeset, for example by checking parameters for the prefix `changeset_` and using the rest of that name for the key, so that `changeset_comment` would create a `comment` tag and `changeset_hashtags` would create an `hashtags` tag.

Imports would be a possible motivation for supporting arbitrary tags. I guess it might be nice to have QA tools identify themselves too (they aren't always quite a source). But those things would probably fit into a single additional key.

**Comment by pnorman** [comment]
> Imports would be a possible motivation for supporting arbitrary tags. I guess it might be nice to have QA tools identify themselves too (they aren't always quite a source). But those things would probably fit into a single additional key.

Some imports have had multiple keys, `import=yes`, `source=...`, `website=<link to wiki page>`

**Comment by Hedaja** [comment]
Some important/useful changeset tags could be shown similar to commonly used features if you tag things (like max speed/oneway/.. for roads)
I think the most important would be "source". And for statistics it would be "hashtag".
For any additional tags the same principal like tagging things could be used. --> List of all tags for the changeset

**Comment by bhousel** [comment]
Also #2633

**Comment by woodpeck** [comment]
Thank you! I have mentioned this in the "good changeset comments" wiki page: https://wiki.openstreetmap.org/w/index.php?title=Good_changeset_comments&type=revision&diff=1501895&oldid=1495359
