### ISSUE TITLE
bicycle parking type strings are not translatable

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#2835]
I registered to https://www.transifex.com/ideditor/id-editor with intention of translating values displayed for Polish iD version during selecting bicycle_parking tag value. It appears that this value is not translatable.

To reproduce:
- request pl version of iD
- select/create amenity=bicycle_parking node
- see section "Typ" (name of section is translated)
- see "stands, wall_loops, rack..." placeholder and values in dropdown
- register on https://www.transifex.com/ideditor/id-editor/
- go to https://www.transifex.com/ideditor/id-editor/translate/#pl
- select either presets or core, search for translatable values containg "wall", "loops" etc
- no values are found

I would expect that this values are translatable.

**Comment by bhousel** [comment]
Yes see #2708 

The tags in OpenStreetMap are basically free-form entry, but expected to contain English values.  For the fields with a strict set of defined values (like the mountain bike difficulty) we support translation of the values, and for the fields where the user can type in anything they want, we haven't thought up a good way to support i18n, and instead just lookup the most common values from taginfo.

**Comment by matkoniecz** [comment]
In this case it is strict set of defined values. I will open a new issue for that.
