### ISSUE TITLE
Add menu category for natural / landcover areas

### ISSUE THREAD

**Issue by d3netxer** [openstreetmap/iD#2843]
Is this an option? I don't see it come up when I create an areas. I only see Land Use. There are a few useful land cover features that use the 'natural' key (wood,wetland,coastline). 

I think that the current menu is leading many editors to create forests using the landuse=forest tag. The OSM wiki signifies this tag to be used for land managed for forestry; where many times the editor may want to use the natural=wood tag instead (natural=wood is used to mark areas covered by trees).

**Comment by bhousel** [comment]
iD does have presets for many of the `natural=*` tags.. `natural=wood`, and `natural=wetland` are included.

Just so I understand - Is your issue that you typed "landcover" in the search and didn't see these things in the results?

**Comment by d3netxer** [comment]
thanks for point that out, I see the presets pop up when you search for them. 

I guess is my issue is that I don't see the presets in the main menu options when I draw an area.

![area-menu](https://cloud.githubusercontent.com/assets/2665840/11408511/97e24534-9387-11e5-977d-11da9d0c0276.PNG)

**Comment by bhousel** [comment]
Ok, I understand now... In iD we call these groups "categories" and you're right we don't have one for common natural / landcover presets.

**Comment by bhousel** [comment]
btw, creating the category is easy, but closing this is contingent on having a better icon for natural/landcover. 

Ideally we'd split replace maki [`land-use`](https://github.com/mapbox/maki/blob/mb-pages/src/land-use-24.svg) into one icon for landuse things (commercial, residential, industrial, shop) and one icon for landcover/natural things (forest, water, scrub, wetland)

We don't _really_ need to wait for a maki icon - we can stick the icons we need into iD-sprite and use them just as easily.

This relates to #2344 - adding a barrier category, also stalled for the same reason (that we have no icon for it).

Will probably close these myself when I get spare time.

cc @samanpwbb, just fyi, nothing you need to do
