### ISSUE TITLE
taginfo help is broken

### ISSUE THREAD

**Issue by jfirebaugh** [openstreetmap/iD#2844]
Clicking the "i" icon on a preset item doesn't work:

![image](https://cloud.githubusercontent.com/assets/98601/11408043/6cb5cb86-936b-11e5-9877-16f6c45df56b.png)

In the JS console I see "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined"

**Comment by brycenesbitt** [comment]
Verified.

**Comment by bhousel** [comment]
That's because taginfo broke it :smile: 
https://github.com/joto/taginfo/commit/d3faa4665105f38fab80d81427bba2f579fc3d17
cc @joto

**Comment by joto** [comment]
Ups. Sorry. @jfirebaugh: do you want me to roll back the taginfo API change? I want that API change in any case but can use a new version number for it. (Sooner or later I'll have to deprecate the API anyway, but if the fix is not so easy on your side, it would give you some time.)

**Comment by bhousel** [comment]
No worries @joto, it's an easy fix.  I'll change it on our end this morning.
