### ISSUE TITLE
Add "terms" to "shop/bicycle" to lower user misuse of "bicycle_repair_station"

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#2845]
The tag  "amenity=bicycle_repair_station" is for unattended tool stands, not shops.
To reduce the number of mistakes, would you considering adding preset shop/bicycle.js:

    "shop/bicycle": {
        ...
        "terms": {
            "bicycle repair, bike repair"
        },

So that a search for "repair" brings up both bike shop (a store that sells and repairs bikes), and bicycle_repair_station (a DIY tool stand with no shop).

Right now people are finding bicycle_repair_station first and using it.

**Comment by matkoniecz** [comment]
Note that there are bicycle shops not offering repair and places where section selling bicycles and repairing them are separated.

**Comment by brycenesbitt** [comment]
Matkoniecz,this tagging works for those cases:

    shop=bicycle
    service:bicycle:retail=yes
    service:bicycle:repair=no

"amenity=bicycle_repair_station" is a do it yourself tool stand, and has nothing to do with a shop.

**Comment by bhousel** [comment]
> "amenity=bicycle_repair_station" is a do it yourself tool stand, and has nothing to do with a shop.

Why not just make the tag `amenity=diy_tool_stand`?

**Comment by brycenesbitt** [comment]
I will push for that, though some including Andy Allen, have objected.
Adding the terms to iD makes sense regardless.
