### ISSUE TITLE
Safari 9.0.1 has issues with loading imagery and data 

### ISSUE THREAD

**Issue by leonmvd** [openstreetmap/iD#2848]
Since tonight I have issues in Safari 9.0.1 on Macbook Pro with Yosemite 10.10.5. I just see a black screen. No problems in Chrome right now.
<img width="1440" alt="screen shot 2015-11-26 at 21 20 28" src="https://cloud.githubusercontent.com/assets/9214202/11430220/89dd11ec-9483-11e5-9524-bfc7cb6ee6ae.png">

**Comment by bhousel** [comment]
Weird, yes I'm also seeing some strange behavior in Safari 9.0.1 (11601.2.7.2).

Looks like when I start an editing session at z15, I see no images.  When I attempt to zoom in, I get some corruption in the sidebar.   After a bunch of zooming and panning, it seems to fix itself somehow.

I don't see any messages in the dev console about this (only warnings about loading the image tiles with http).  Seems like a Safari issue to me?  

<img width="1237" alt="screenshot 2015-11-26 17 33 08" src="https://cloud.githubusercontent.com/assets/38784/11431348/4ca22624-9464-11e5-899b-3661d4aae474.png">

**Comment by leonmvd** [comment]
Looks like it, but it worked pretty well before, so that's why I opened this issue.

**Comment by abellao** [comment]
I'm having the same problem, using Safari 9.0.1 on OS X 10.11.1.

It seems to work fine from time to time.

**Comment by celoyd** [comment]
Resizing the window causes some kind of redraw that fixes this (temporarily).

**Comment by bhousel** [comment]
Closing this, as Safari 9.0.2 was pushed out and doesn't seem to have these issues.
