### ISSUE TITLE
Zwei überlagerte Straßen

### ISSUE THREAD

**Issue by wahnfried** [openstreetmap/iD#2850]
Ich wollte korrigieren, dass in Rhoden/Osterwieck die Krugstraße zu weit bis zur Fallsteinstraße geführt wurde. Der Abschnitt ab westlicher Abzweig Glockenkuhle bis zur Fallsteinstrasse ist ein Teil der Kirchstrasse. Nun habe ich zwar die Kirchstrasse verlängern können, beim Klicken auf die Krugstraße wird aber weiterhin der Abschnitt zwischen westlichem Glockenkuhle-Abzweig bis zur Fallsteinstrasse mit-markiert und in bestimmten Vergrößerungen der Karte wird hier als Strassenname sowohl Kirchstrasse als auch Krugstrasse angegeben. Wie kann man dies ändern oder übernimmt das Jemand? H.Gehlig

**Comment by wahnfried** [comment]
Hallo, die Krugstrasse ist auch am anderen Ende kürzer und "Hinter dem Dorfe" geht durch bis zur Kreisstrasse/Beembeck - allerdings ab Einmündung der Krugstrasse nicht mehr als Einbahnstrasse... H.Gehlig

**Comment by wahnfried** [comment]
Hallo, ist jetzt geschafft (vermutlich mit einem unbekannten Helfer, der schonmal "Hinter dem Dorfe" verlängert hatte). Grüsse, H.Gehlig

**Comment by tyrasd** [comment]
Hallo! Bitte melde solche Mapping-Probleme in der Zukunft lieber an einer anderen Stelle (z.B. als "Note": http://wiki.openstreetmap.org/wiki/DE:Notes oder auf http://help.osm.org). Hier befindet sich das (in der Regel englischsprachige) Ticketsystem des iD-Editors wo hauptsächlich Programmfehler und Verbesserungswünsche diskutiert werden. Vielen Dank!
