### ISSUE TITLE
Embedded help doesn't get displayed

### ISSUE THREAD

**Issue by naomap** [openstreetmap/iD#2855]
Clicking on the information 'i' at the right of the feature or tag fails to show the description, thumb image and link to the Wiki.

The request (e.g. https://taginfo.openstreetmap.org/api/4/tag/wiki_pages?key=highway&value=residential) is properly sent and the response received, however the console then shows an error in the JS code that parses the response : 
TypeError: e.lang is undefined
 ... oLowerCase();if(t=_.find(e,function(e){return e.lang.toLowerCase()===n}))return ...

I can reproduce this issue on Firefox and Chrome.
Antoine.

**Comment by bhousel** [comment]
Already fixed! See #2844

**Comment by naomap** [comment]
Ok great ! Sorry I didn't spot the issue.
When will the fix be rolled out ?  I am training a group of 12 people on Dec 11th and it would make it so much easier and nicer to be able to get this help in iD !
Regards, Antoine.

**Comment by bhousel** [comment]
It will probably be rolled out before 12/11... 
v1.8.1 contains the fix and is already released and available for use here:  https://openstreetmap.us/iD/release

**Comment by bhousel** [comment]
@naomap, FYI the new version of iD v1.8.2 was just deployed on openstreetmap.org.
Hope your training event goes well!

**Comment by naomap** [comment]
Excellent, just in time !  The training went well and the fix did help. Thanks for that.

**Comment by bhousel** [comment]
You're welcome, I'm glad to hear it went well... :smile:
