### ISSUE TITLE
mark untagged new features

### ISSUE THREAD

**Issue by joostschouppe** [openstreetmap/iD#2856]
As you add new features, iD invites you to tag them. However, there is some room for confusion. For example, as you click on "building", you might get the impression that you actually added a tag. But you have to press the subitem building to get a generic building (building=yes).
I see two solutions:
- give the generic tag if the user doesn't pick a subitem. (you might want to avoid this as it would result in a lot of vague tagging where the contributor actually might have had more detailed info)
- mark untagged things much more clearly. For example a very bright red would give a clear visual clue when a tag has been added. Potlatch uses simple black lines, but the dark theme of iD makes that impossible.

(I often check new contributors changesets, and I had a real a-ha erlebnis when I was really using iD as to why we so often find untagged lines by newbies)

**Comment by bhousel** [comment]
We already do display warnings when saving if the user created any untagged features.  And we explain pretty clearly in the walkthrough how to pick a preset from a category of items.  And we already render untagged things in a generic way - nobody would confuse an untagged area for a building.

I'm don't think picking the generic tag from a category is the right thing to do either.  For buildings this would be ok, but for most other category (like landuse or roads) the feature would be tagged with a wrong tag, which is maybe is worse than no tag.

Really not seeing much that we can do to improve this other than making the walkthrough a bit better.

**Comment by joostschouppe** [comment]
You're right, of course. I tried it again, and it is really almost impossible to do it wrong.  Maybe the examples I though of are too old. Or maybe they aren't, and people are people.

**Comment by bhousel** [comment]
Yes, I think it's just that some people are in a hurry, or just experimenting.   At least untagged things are really easy to fix or delete.

If I see people doing this where I tend to edit, I send a friendly private message or changeset comment if it looks like they were in fact trying to add something and got confused.
