### ISSUE TITLE
Get addr:street from associatedStreet relation

### ISSUE THREAD

**Issue by Larry0ua** [openstreetmap/iD#2859]
Hi!

There are several countries that work with associatedStreet address relations, but currently there is no support of them in iD. It means that when people try to edit (iD) an area in my city they think houses have housenumbers, but there is no street data assigned to them.

I would like to ask you to fill the addr:street preset field with corresponding name of the majority (or just any) name of the 'street' members of the relation. 
- If addr:street tag is already present on the building, it should be displayed. 
- If there is no relation or no 'street' members on the relation, street field should be blank. 
- No need to change the model data until user modifies the field. 
- If he does modify the street field, iD should simply fill addr:street tag and drop the building from the relation.

Any code points/suggestions where to put these improvements is appreciated, I may try to do it in this case.

Background:
relation type=associatedStreet/street is used for around 7% of addresses, mainly over Europe. It may have members with roles: 'house' or 'address' that refer to the houses that share the same street name, and role 'street' refers to the highways with the street name. More at http://wiki.openstreetmap.org/wiki/Relation:associatedStreet and http://wiki.openstreetmap.org/wiki/Relation:street

**Comment by bhousel** [comment]
Let's close here, I feel like `associatedStreet` has fallen out of favor these days..
