### ISSUE TITLE
Turn restrictions broken on Firefox

### ISSUE THREAD

**Issue by mxa** [openstreetmap/iD#2860]
There used to be red or green arrows, but now it's all black and stays black when I click on it.
Firefox 43.0a2 Linux Mint
![Turn Restrictions](https://cloud.githubusercontent.com/assets/1220707/11612785/fe7a7eee-9c4a-11e5-9f65-8055bfeceadd.png)

**Comment by bhousel** [comment]
Thanks for the report - I can confirm they are also broken on OS X, Firefox 42.0.  Instead of blacked out icons, I don't see anything at all.  Will fix..

**Comment by bhousel** [comment]
I think I fixed this issue - Can you test against https://openstreetmap.us/iD/master/ and let me know if it looks right?

**Comment by mxa** [comment]
Yes! I can confirm that it works there.
