### ISSUE TITLE
Merge lines tip should say merge features instead

### ISSUE THREAD

**Issue by nvkelso** [openstreetmap/iD#2861]
When selecting two features in iD to merge (common when a landuse polygon has been digitized after a GNIS node import for the USA), the wheel menu of buttons shows a + icons (good), but the tool tip says `Merge these lines` when in fact these are a point and a polygon. Instead the language should say `Merge these features`.

![screen shot 2015-12-07 at 10 09 12](https://cloud.githubusercontent.com/assets/853051/11635323/d0597896-9cca-11e5-9f55-8ccc79099244.png)

**Comment by nvkelso** [comment]
Related: https://github.com/openstreetmap/iD/issues/815

**Comment by nvkelso** [comment]
When will this be live on OSM.org?

**Comment by bhousel** [comment]
Pending acceptance of PR https://github.com/openstreetmap/openstreetmap-website/pull/1106
So.. maybe today?
