### ISSUE TITLE
When manually adding a way with role "outer" to a multipolygon, move tags

### ISSUE THREAD

**Issue by emj** [openstreetmap/iD#2862]
1. have two areas (ways), with tags, and one of them enclosed in the other.
2. create a multipolygon
3. add the ways as outer/inner

Results:
an relation with no tags other than "type=multipolygon"

Expected results:
The tags on the outer way should be moved to the multipolygon.

Note there might be other "Expected results", and there might be better ways to do this in the interface. But creating empty multipolygons can not be a good idea. IMHO.

**Comment by bhousel** [comment]
We already do move the tags from the outer way to the multipolygon relation if you use the Merge operation.  See below:

![multipolygon](https://cloud.githubusercontent.com/assets/38784/11785394/a16ab15a-a24f-11e5-94be-397d5b0ba469.gif)


But I guess we could also handle the situation where a user wants to manually create a multipolygon and specify the inner and outer ways.  We'd just need to add a special case to do the same things the merge operation does when the role is set to "outer".

**Comment by jfirebaugh** [comment]
I think this use case is properly addressed with the merge operation, and iD should not do anything special if you add relation members with the raw relation editor.
