### ISSUE TITLE
Persist wireframe area fill and feature filtering preferences in localstorage

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#2864]
We can change these two options during a session but when the tab is closed, their value are lost. Same applies for last map layer used while the "custom map layer" URL is saved for future uses.

Is there a reason behind that or would it be possible to save user options so that they stay persistent through multiple tabs?

**Comment by bhousel** [comment]
> Is there a reason behind that or would it be possible to save user options so that they stay persistent through multiple tabs?

No reason really.  Traditionally iD tried to avoid the idea of having user "preferences", but most feedback I hear from users lately is that they prefer to retain their preferences between editing sessions, so we do more of that now.

**Comment by bagage** [comment]
Hey @bhousel, is there anything new around some user storage preferences since this issue? I'm using Osmose a lot which opens a new browser tap for each issue so I have to reconfigure my context everytime. I can see some similar issues like #2947 and #1756.
The alternative solution would be to manually modify lat/lon coordinates in URL bar and refresh tab but unfortunately iD does not support that. Should this be entered as another issue?

**Comment by bhousel** [comment]
Hey @bagage, I was putting off working on the storage-of-preferences, hoping to get #4418 in first.  Since we aren't doing that, I think we could just do the simple thing of putting more preferences into localStorage.

**Comment by bagage** [comment]
Thanks for the insight @bhousel :). I'll take a look at the local storage code and try to submit PR for this issue. Any documentation around and/or tips before getting started is good to hear if there is any?

**Comment by bhousel** [comment]
- [ ] persist wireframe area fill
- [x] persist preferred feature filters

Thanks for the PR @bagage  - I'm just marking here that you did the feature filters part already..
