### ISSUE TITLE
Cannot continue a line if last point is shared with another ENDING way

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#2865]
I do not know how other users deal with this but currently I have to:

1. split ways to have 2 independent points
* select the node - it will select one of the 2 points. Move it somewhere else
* select my way, and modify it as wished
* take the point from step 2. and merge it to its previous location

It is a fastidious process and from what I understand, "continue this line" option is grayed out because iD do not know which way the point belongs to, right? This limitation is not present when the selected point is not end-point of both ways.

Could we do a 2-step selection in that case (select way to expand, then select end-point. iD is now aware of which way to continue)? Or am I in a very specific situation where it's not worth the trouble :-)?

**Comment by bhousel** [comment]
Don't you see a tooltip like this?

<img width="289" alt="screenshot 2015-12-14 10 16 20" src="https://cloud.githubusercontent.com/assets/38784/11784729/f9ca8d10-a24b-11e5-825f-50ed7208a658.png">

When multiple ways can be continued, the continue operation is disabled.  But you can shift click on one of the ways to pick the line that you want to continue, and then the operation becomes available.

**Comment by bagage** [comment]
Oops... you are right. I never saw that earlier... but it is there! Is that from latest release or did I miss it the whole time?!
In any case, thanks a lot @bhousel, and sorry for the inconvenience!

**Comment by bhousel** [comment]
No problem!  I think it's been there for a long time, but it is easy to miss..
