### ISSUE TITLE
Display warning on save if over X street name changes

### ISSUE THREAD

**Issue by nighto** [openstreetmap/iD#2868]
Don't know if it's specific from users in Brazil, but here we have many examples of users that commit changesets with many street names, without citing source. When asked on changeset messages, many users tell that they copied street names from Google Maps or other local paper maps, and there we have to revert everything.

My proposition is that when over X street name changes (let's say, over 10) a big warning message appears, saying "Warning: it is strictly forbidden to copy street names from Google Maps, paper maps or any other copyrighted sources", or something along these lines. I'd make it non skippable, as in user have to wait at least three to five seconds to click "OK". To be perfect, it could also not appear if the user is using a layer with names that we already have authorization to use, such as (brazilian example) IBGE Mapa Urbano.

What do you think about this?

**Comment by marcioaguiar** [comment]
People copying from copyrighted sources are frequent and annoying. We need a clear and direct way to guide mappers about that before they even start to map.

I support the message when the user clicks on save, but I think there should also be a warning message when the user enters the editor, to avoid useless work.

**Comment by naoliv** [comment]
I have to agree that some kind of warning or concise message is needed.
Names copied from Google and other commercial sources are increasing so much here in Brazil and, most of the time, the person didn't know that it wasn't allowed to do this.

While there is an explanation when the user accepts the contributor terms¹, I think that we should also have a message reinforcing this (when the user starts mapping or when he saves his changeset, for example).

¹ I see some problems when the user is at the contributor terms: it's in English, most probably they accept without reading and, even if they read it, I don't think that the text is clear enough. But of course, this isn't a problem in iD.

**Comment by nighto** [comment]
About the contributor terms, I think that most people would confirm/sign it without reading it, as it is so common with Terms of Service.

**Comment by vgeorge** [comment]
+1

**Comment by jfirebaugh** [comment]
While I appreciate the problems with contributors adding copyrighted content, we're not going to add a warning message to iD about this (especially not an intrusive one that forces the user to wait some number of seconds before continuing). If we added warning messages for every case people requested, submitting changes would be a tiresome and frustrating experience.

**Comment by naoliv** [comment]
Couldn't we have a small message here, at least for `pt_BR` only?
![Suggestion](http://i.imgur.com/uqTJbhb.png)

**Comment by jfirebaugh** [comment]
Yes, you could add some text to the [translation](https://www.transifex.com/ideditor/id-editor/translate/#pt_BR/core/13589222?key=upload_explanation_with_user) (looks like someone already did).

**Comment by bhousel** [comment]
I was going to suggest to add it to the welcome splash instead, but looks like it has been added there also.

https://www.transifex.com/ideditor/id-editor/translate/#pt_BR/core/11326075

**Comment by naoliv** [comment]
Is it possible to use some HTML code in the translation?
For example, will `<b>something</b>` or `<i>otherthing</i>` be correctly interpreted as bold and italic?

**Comment by bhousel** [comment]
Yes, both the commit and splash strings support html.

**Comment by naoliv** [comment]
Very good. Thanks!

**Comment by nighto** [comment]
I was the one who changed the translations. I'll edit them to add HTML tags. Thanks!

**Comment by alexandre-mbm** [comment]
marcioaguiar says:
> I support the message when the user clicks on save, but I think there should also be a warning message when the user enters the editor, to avoid useless work.

naoliv says:
> I think that we should also have a message reinforcing this (when the user starts mapping or when he saves his changeset, for example).

nighto says:
> About the contributor terms, I think that most people would confirm/sign it without reading it, as it is so common with Terms of Service.

**+1**

---

jfirebaugh says:
> If we added warning messages for every case people requested, submitting changes would be a tiresome and frustrating experience.

But messages for questions really important could save much time (efforts) and money.

---

naoliv says:
> Couldn't we have a small message here, at least for `pt_BR` only?

**+1** :+1: This will appear always... :-1:
