### ISSUE TITLE
Rename doctors file name

### ISSUE THREAD

**Issue by math1985** [openstreetmap/iD#2869]
The file data/presets/presets/amenity/doctor.json should probably be called data/presets/presets/amenity/doctors.json, with an s in doctors.

**Comment by djgould** [comment]
If you look at all the other files in that folder they are named in the singular form. Changing doctor.json to doctors.json would conflict with the other file names.

**Comment by jfirebaugh** [comment]
The convention iD uses is that a preset whose primary tag is `a=b` should be located at `presets/a/b.json`. [`amenity=doctors`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddoctors) is indeed the approved tag, so @math1985 is correct.

**Comment by djgould** [comment]
Ah. It does seem a little odd to have `amenity=doctors` when you have `amenity=dentist` but your convention should definitely trump any nitpicking over plural vs singular
