### ISSUE TITLE
Official street name homologation in Brazil and similar countries

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/iD#2870]
As remembered by #2868 and others, OSM need some kind of "spell checking"  for **street names**...

In many developing  countries like Brazil, the official names are not checked by "the official street data authority", so, maps reproduce old errors and never corrected... But there are a superior authority, that make the official names. This superior authority do the "street baptism".

In Brasil the "street *name* authority" is the [City council](https://en.wikipedia.org/wiki/City_council) of the city where the street is placed, and the records of the baptism, are law-documents. Like in [UK-legislation](http://www.legislation.gov.uk/browse) or [N-Lex](http://eur-lex.europa.eu/n-lex/index_en.htm), in Brazil the law-documents have good and reliable public IDs and a [persistent](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator) ID-resolver to point the law-document ... Example: [all the "baptism law" of streets of the city of Campinas are here (!)](http://www.lexml.gov.br/busca/search?f1-tipoDocumento=Legisla%C3%A7%C3%A3o;f2-localidade=Munic%C3%ADpios::Campinas%C2%A0-%C2%A0SP&keyword=denomina).

So, an automatized solution to any  "name dispute", and to 100% reliable name's "spell checking" is 

 1. Use as "oficial ID"  of the street name, the ID of the "batism law" of the street. In the Brazilian case, it is the URN LEX international standard. Example: the oficial spelling of "RUA CARLOS EDUARDO POSSOLO NISTA" is in the document-law [urn:lex:br;sao.paulo;campinas:municipal:lei:2007;12963](http://www.lexml.gov.br/urn/urn:lex:br;sao.paulo;campinas:municipal:lei:2007;12963). 

 2. Extract by software the name from the law-document, to use it in an official name assignment.

There are a software to do this operations in bulk, for a thousand of streets.

**Comment by nighto** [comment]
I'm sorry @ppKrauss but you're bringing the discussion to the wrong forum, this is the bug tracker for the iD Editor. This issue is not related to the editor and should be closed.

**Comment by ppKrauss** [comment]
I think the place is here (as *new issue*), because any changes in data structure will be reflected in the iD editor: when a user edit a street name, or when need to check/edit another attributes (in this case  the baptism law ID).

**Comment by bhousel** [comment]
Agree with @nighto that this has nothing to do with iD, closing..
