### ISSUE TITLE
IE11 throws exception on iD load. Object doesn't support property or method 'find'

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/iD#2871]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility

**Comment by bhousel** [comment]
Thanks!   We realized that we're using a not-standard `find` in the code that picks the best imagery.  I didn't catch this before because it was on a separate branch from the IE work.. Will release a fix today.
