### ISSUE TITLE
Improve vending machine presets

### ISSUE THREAD

**Issue by g4rpch** [openstreetmap/iD#2872]
Dear all

I really appreciate the new vending machine presets, but could you please improve it adding:

**Vending Machine Excremental bag**
bin=yes/no
fee=yes/no

**Vending Machine Parking Tickets**, **Snacks**, **Drinks**, **Condoms**, **Public_Transport_Tickets** and **Cigarettes**
currency:XXX=yes/no -> http://wiki.openstreetmap.org/wiki/Key:currency
payments:XXX=yes/no -> http://wiki.openstreetmap.org/wiki/Key:payment

**Vending Machine News Paper**
fee=yes/no

Thanks a lot
G4rp

**Comment by bhousel** [comment]
We have no good way in iD to do multiselections like `currency:XXX` or `payments:XXX`, but the other suggestions look fine.

**Comment by bhousel** [comment]
These improvements have all been made.. New `multiCombo` field makes payment and currency options possible:

<img width="373" alt="screenshot 2016-05-01 14 19 09" src="https://cloud.githubusercontent.com/assets/38784/14943443/c3e18e28-0fa7-11e6-8e55-7189e6057065.png">
