### ISSUE TITLE
Improve amenity=recycling

### ISSUE THREAD

**Issue by g4rpch** [openstreetmap/iD#2873]
Dear all

Can you please update amenity=recycling with the most common materials
recycling:cans
recycling:clothes
recycling:glass
recycling:batteries
recycling:paper
recycling:plastic_bottles
recycling:cooking_oil
recycling:engine_oil
recycling:aluminium
recycling:plastic

Thanks a lot
G4rp

**Comment by bhousel** [comment]
We don't have a good way in iD to handle multiselection fields like this.  

By this I mean, it would not work well to create a checkbox for every kind of material.  A better UI would be a single field that lets users check multiple items.

**Comment by g4rpch** [comment]
Dear bhousel

for me doesn't matter the way, the important is the result :)
I have no dev skills to say with is the better way :(

G4rp

**Comment by bhousel** [comment]
This is now done!  see #3080
