### ISSUE TITLE
amenity tags related to `amenity=waste_basket`

### ISSUE THREAD

**Issue by matiasdahl** [openstreetmap/iD#2880]
I have recently been analysing the edit history of OpenStreetMap to find common edit patterns among `amenity=..`-tags. For example, a common pattern is that `amenity=hospital`-tags are edited into `amenity=clinic`-tags. This has occurred for 3200 map elements over the history of the OSM. This is also reasonable as both tags are related to health care. A blog writeup with more background can be found [here](http://matiasdahl.iki.fi/2015/finding-related-amenity-tags-on-the-openstreetmap).

A motivation for this is to better understand how different tags are related to each other. As an example, the [waste_basket.json](https://github.com/openstreetmap/iD/blob/0543f684d2b431eb64f3918bad344f50d3c17733/data/presets/presets/amenity/waste_basket.json) file in the iD editor currently lists the synonyms `rubbish`, `litter`, `trash` and `garbage`. However, by querying for edit patterns **to** the `amenity=waste_basket`-tag one can find the following related amenity tags: `bin`, `waste_bin`, `trash_can`, `lit_bin`, `litter_bin`, `waste_backet` (typo), `waste_bucket`, `basket`, `garbage`, `trash`, `waste basket`, `trash_bin`, `waste`, `dog_bin`, `wastebasket`, `cestino` (Italian), `rubbish`, `trashbin` and `trashcan`. See: [matiasdahl.github.io/osm-tag-dynamics/index.html?amenity=waste_basket](http://matiasdahl.github.io/osm-tag-dynamics/index.html?amenity=waste_basket). 

I am not sure if one should include all of the above synonyms, typos, and related tags. For example, it might not make sense to include `litter_bin` if `litter` is already included. But, it might make sense to include `bin` and `basket`: the edit `amenity=bin` to `amenity=waste_basket` has occurred for 290 map elements. (This can be seen by hovering over the corresponding arrow in the previous link). In comparison, `rubbish → waste_basket` has occurred for 5 elements. 

I am unsure about the licensing issues if one would import this type of data into the iD editor (licensed under the ISC License). Even if `bin` and `basket` are only two synonyms, they were found by analysing a lot of OSM data (licensed under the ODbL). This might also depend on whether such imports are done as one-offs or systematically.

**Comment by bhousel** [comment]
Awesome work!  It is interesting to see how OSM evolves.

> I am not sure if one should include all of the above synonyms, typos, and related tags. For example, it might not make sense to include `litter_bin` if `litter` is already included. But, it might make sense to include bin and basket:

The `search` method in [`js/id/presets/collection.js`](https://github.com/openstreetmap/iD/blob/master/js/id/presets/collection.js) prepares the suggestions that the user is presented when they pick or change a preset.   The code prioritizes leading match on name, terms, tag, followed by levenstein distance on name, terms, tag, etc.  Meaning, it isn't necessary to include the `litter_bin` if `litter` is already included.  

Also worth mentioning is that each translation of iD will likely contain different terms lists.  This is because we don't ask translators to literally translate "rubbish, litter, trash, garbage" but rather instruct them to "translate with synonyms or related terms for 'Waste Basket', separated by commas", so they are free to include whatever synonyms make sense in their language.

> I am unsure about the licensing issues if one would import this type of data into the iD editor (licensed under the ISC License).

I don't think importing your data makes sense here, but if you analysis can suggest improvements to our preset terms we can add them manually.

**Comment by matiasdahl** [comment]
Thank you! I agree here that this data can not be imported as-is. It contains a lot of noise, typos, unrelated terms, etc. Adding terms to the preset files also involve choices. But: I tried to go through the top 10 amenity tags and manually compare their edit patterns with the preset files in the iD editor. Below are some possible synonyms that are not listed in the preset files.

##### `amenity=bench`: [edit patterns](http://matiasdahl.github.io/osm-tag-dynamics/index.html?amenity=bench) 

Possible synonym: `seat`. 

At the moment there are 42 live map elements with `amenity=seat`. The OSM wiki for [amenity=bench](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench) lists `seats=..` as an optional field recording the number of seats on the bench. So: adding `seat` as a synonym to `bench` would imply that a single seat could be treated as a bench with one seat. This would extend the OSM wiki's description of a bench: "A place for people to sit; allows room for several people."

##### `amenity=fuel`:  [edit patterns](http://matiasdahl.github.io/osm-tag-dynamics/index.html?amenity=fuel) 

Possible synonym: `gasoline`. 

Over the entire history of the OSM, only 7 map elements have used the `amenity=gasoline` tag, 5 have been edited into `amenity=fuel`, and one `amenity=gasoline` is currently live. 

##### `amenity=cafe`: [edit patterns](http://matiasdahl.github.io/osm-tag-dynamics/index.html?amenity=cafe) 

Possible synonym/related term: `bistro` (`amenity=bistro` has been used by less than 40 map elements over the history of the OSM). The `amenity=cafe` [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe) lists bistros as being part of cafe:s.

----- 

I am not sure how qualified I am to judge whether these should be included. I am rather new to the OSM and I am not an active mapper.

**Comment by bhousel** [comment]
Thanks!  I will add these as term synonyms.  There is no harm at all in adding more of these.
