### ISSUE TITLE
Add presets for various tags

### ISSUE THREAD

**Issue by math1985** [openstreetmap/iD#2883]
Would it be possible to add presets for the following tags?

* [ ] [amenity=hunting_stand](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhunting_stand)
* [ ] [amenity=parking_space](https://wiki.openstreetmap.org/wiki/Tag:amenity=parking_space)
* [ ] [amenity=ferry_terminal](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dferry_terminal)

These are the only POI tags that seem non-problematic and have more than 10.000 instances. Other common unsupported tags (more than 10.000 instances) are tourism=information, amenity=public_building, shop=yes, historic=yes, amenity=waste_disposal, leisure=recreation_ground, historic=yes, office=building, and amenity=nursing_home, but I can imagine they are problematic for various reasons.

(Please let me know if you prefer such requests in one or multiple issues.)

**Comment by bhousel** [comment]
Thanks @math1985 - it's fine to put multiple preset requests into a single issue..
If you can link to osm wiki for each one that would be great too.

I agree we should just do the 3 non-problematic ones for now.  I guess some of the ones on the problematic list have been superseded by newer presets.

**Comment by math1985** [comment]
Thanks, I added links to the wiki.
