### ISSUE TITLE
Multiple relations of same category (and name) are only shown once

### ISSUE THREAD

**Issue by IntendedCrash** [openstreetmap/iD#2891]
When trying to add an entity as a member to an already existing relation, the relation list shows relations of the same category (and with the same name) only once. Especially generic multipolygon relations (e. g. landuse=forest) without any name create such kinds of collisions. If there are multiple relations of that kind in the area, the users can see only one thus they are adding the object maybe to the wrong one just because it's the only one visible. Even if they would be aware of the situation, there is no possibility to select a relation not shown in the list.

Reason for this is the construction of the keys for the selection list. The function [RawMembershipEditor.relations()](https://github.com/openstreetmap/iD/blob/d8e627b9b13af1e1d03e8001673cdcb67955f892/js/id/ui/raw_membership_editor.js#L57) creates non-unique values, which are redirected via [d3.combobox.render()](https://github.com/openstreetmap/iD/blob/66e8f78aa77f96ff860aceb8b5c188d67b32d9c1/js/lib/d3.combobox.js#L209) as keys to [d3_selectionPrototype.data()](https://github.com/openstreetmap/iD/blob/f67d51492a81a325ed1a63ff3dcf2e4df7d7349c/js/lib/d3.v3.js#L1127) where they are required to be unique.

My proposal for a solution would be to implement a value check within [RawMembershipEditor.relations()](https://github.com/openstreetmap/iD/blob/d8e627b9b13af1e1d03e8001673cdcb67955f892/js/id/ui/raw_membership_editor.js#L67) before returning the result array. If there are multiple relations with the same value in result, add the respective IDs to the affected values. Thus keys for the selection list would be unique and also users can distinguish between multiple relations (because a list with "Forest", "Forest", "Forest" wouldn't be very useful when making multiple edits; would require to look for the correct relation every time again).

**Comment by bhousel** [comment]
Thank you for the very descriptive bug report.
I fixed this in 4dd4ccb using your suggestion to append the id to any duplicate names.
