### ISSUE TITLE
Wrong URL encoding?

### ISSUE THREAD

**Issue by nikslor** [openstreetmap/iD#2892]
Hi all

I'm not sure if the following is a bug or if I'm doing something wrong, so please bear with the young Padawan ;)

I tried to set the website of a local restaurant using iD on openstreetmap.org - the correct URL is "http://www.bären-bönigen.com" however after saving the value appears as "http://www.b%C3%A4ren-b%C3%B6nigen.com" which looks to me like some "url encode" went wrong (or the "url decode" is missing).

Am I right here or should I report this somewhere else?

If you want to try it out, you can have a look at the element here:
http://www.openstreetmap.org/node/3904919515

If I can help in any way, please let me know :)

Have a nice day and thanks for looking into this!

Best regards
Nicolas

**Comment by pnorman** [comment]
Looks like it's been encoded when it shouldn't have been, and it's been encoded wrong too.

**Comment by bhousel** [comment]
> Looks like it's been encoded when it shouldn't have been, and it's been encoded wrong too.

Yeah I agree we shouldn't touch the hostname...
