### ISSUE TITLE
Add presets for various tags (2)

### ISSUE THREAD

**Issue by math1985** [openstreetmap/iD#2893]
Would it be possible to add presets for the following tags? They all have more than 10,000 occurrences.

* [ ] man_made=works
* [ ] man_made=surveillance
* [ ] amenity=waste_disposal
* [ ] man_made=chimney
* [ ] man_made=groyne
* [ ] man_made=gasometer

**Comment by bhousel** [comment]
Sure, can you please add wiki links - makes things easier for us..
This will probably go in after the next release which is any day now, because I like to give the translators some time to catch up.

**Comment by manfredbrandl** [comment]
Hope that helps:
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dworks
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_disposal
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dchimney
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dgroyne
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dgasometer

**Comment by manfredbrandl** [comment]
Now that 1.8.4 is out I would like to help including new presets. Is there something like a "Howto create a PR to add presets"? I did not find that,

**Comment by math1985** [comment]
I don't know, but at least here you have an example PR:

https://github.com/openstreetmap/iD/commit/da0319677497d69f7036d8e8bd8cac00e6591741

**Comment by bhousel** [comment]
> Now that 1.8.4 is out I would like to help including new presets.

Great!  I appreciate the help..

There is a [README in the presets folder](https://github.com/openstreetmap/iD/blob/master/data/presets/README.md) with more info about how the presets work.

**Comment by tyrasd** [comment]
done in #2897
