### ISSUE TITLE
Option to collapse fields section

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/iD#2894]
It would be nice to have a user selectable option in the iD editor to show the **"All tags"** and **"All relations"** widgets *above* the different preset widgets now shown by default at top in the left tag editing toolbar.

While I understand the preset widgets may be nice for novice users, they take up quite a lot of screen estate, and I continuously find myself scrolling down, once I selected a node or way, to see all of its tags and possible relations a node or way is involved in.

It would be nice if this was a user selectable option, including preferably showing the "All tags" widget opened up, instead of collapsed.

This would really save a lot of scrolling and unnecessary clicking for more advanced users.

**Comment by manfredbrandl** [comment]
I agree.

**Comment by JLZIMMERMANN** [comment]
I do agree also.
In fact this is why sometimes I prefer to use Potlach.

Jean-Louis

Envoyé de mon iPhone

**Comment by bhousel** [comment]
I'll think about it - I'm surprised people want this.  It really sounds like something more appropriate for a Greasemonkey/Tampermonkey kind of userscript.

In the mean time if you really want to remove the field section, you can do this in a developer console:
`d3.select('.inspector-border.inspector-preset').classed('hide', true)`

**Comment by mboeringa** [comment]
> It really sounds like something more appropriate for a Greasemonkey/Tampermonkey kind of userscript.
> 
> In the mean time if you really want to remove the field section, you can do this in a developer console:
> d3.select('.inspector-border.inspector-preset').classed('hide', true)

This is not a developer question, but a question from a user's perspective. I doubt the target audience for iD knows what a "Greasemonkey userscript" is... (well, actually, I don't know either, as I only used iD as a user and haven't had a look at it from a developer's perspective).

**Comment by bhousel** [comment]
> I doubt the target audience for iD knows what a "Greasemonkey userscript" is...

Sure, but the target audience for iD also needs to see that `div` that you want the option of hiding.  Anyway it might be ok to make it collapsable like the other sections in the sidebar, I'll try it sometime and see.

**Comment by mboeringa** [comment]
> Sure, but the target audience for iD also needs to see that div that you want the option of hiding...

Yeah, sure, but that is what I wrote in my initial post: it should be *an option*. I never suggested to make it default. I fully concur the current layout should be maintained as default.

**Comment by vespax** [comment]
We just asked this question on our team since we use the ALL TAGS area more than the top section.  Enabling all three areas to be collapsable would really help us out to get more info into OSM quicker.

I vote a **BIG** yes on this enhancement.

**Comment by bhousel** [comment]
> We just asked this question on our team since we use the ALL TAGS area more than the top section. Enabling all three areas to be collapsable would really help us out to get more info into OSM quicker.
> 
> I vote a BIG yes on this enhancement.

Awesome!   My favorite comments are the ones that say "we are using iD and this is why this issue matters to us". 

Who are you and who is "your team"?  Feel free to message me privately if you don't want to say here.

**Comment by vespax** [comment]
Thinking about this more.  Here are two scenarios that may help this along.  #1 is preferred scenario.

1. Allow the ALL TAGS tab to be floatable (dragging it now displays a green + icon) so users can order the three sections as they like.  In this case I could drag ALL TAGS to the top of my side pane to avoid scrolling to it often.

2.  Add collapsable structure to all three sections.  The issue here is with polygons we try to add street addresses as much as possible and this would cause us to open section to add that one tag.

**Comment by bhousel** [comment]
Thanks for your feedback @vespax... Option 2 is the most technically straightforward, so the one I was planning to do.  

Also - we already persist to localstorage whether or not the user wants the raw tag editor section expanded, so that's something that we could do for the field section also.

**Comment by mboeringa** [comment]
> Also - we already persist to localstorage whether or not the user wants the raw tag editor section expanded, so that's something that we could do for the field section too.

That would be great. Having to redo the collapsing or opening each time the section needs to be accessed would be tiresome in the long run too, so if the setting is preserved, it is big bonus.

**Comment by slhh** [comment]
How about using three tabs (preset fields, tags, relations) below the main feature type? Each tab may contain all sections, but with the respective section being shown on top.

The relation tab should become red if there are any relations listed in it.
The tags tab should become red if there are any tags contained which are not covered by the preset field.
That would make the user aware which tab/section is containing important information.

**Comment by bhousel** [comment]
@mboeringa, @vespax this section is now toggleable:

![collapse_fields](https://cloud.githubusercontent.com/assets/38784/12668098/5b3fe254-c621-11e5-830a-c8f0a6c9e499.gif)

**Comment by mboeringa** [comment]
That looks really good. A simple but effective solution for the main problem. Fancier stuff like re-ordering of the sections can wait for a later date if still desired.

**Comment by vespax** [comment]
In v1.8.5 in Safari I'm unable to see this collapsable menu structure.  Anyone else missing it or what is the trick to enable?  Thanks for pulling this together.

**Comment by tyrasd** [comment]
@vespax: This feature hasn't made it into a release yet. In the meantime you can try it out here: https://openstreetmap.us/iD/master/

**Comment by vespax** [comment]
I didn't know about that sandbox.  Tested it out and seems to be working well.  Thanks!

**Comment by vespax** [comment]
Any estimate when this might go into release iD editor?

**Comment by bhousel** [comment]
> Any estimate when this might go into release iD editor?

Probably late this week / early next.  The marquee feature of the next release will be finally merging in the Mapillary street sign layer and I'm almost done with that.

**Comment by vespax** [comment]
Right on!

**Comment by mboeringa** [comment]
> Probably late this week / early next. The marquee feature of the next release will be finally merging in the Mapillary street sign layer and I'm almost done with that.

Thanks, I now noticed it to be online. I really like the simple solution and it was just what I was hoping for.
