### ISSUE TITLE
Cannot edit existing object with Google Chrome

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#2895]
Using the latest Google Chrome Browser (Version 47.0.2526.106 m) on Windows 7 i cannot edit existing objects. Using Firefox 43.0.1 on the same machine allows me editing existing objects.

**Comment by tyrasd** [comment]
Strange. I have no troubles editing on a very similar version (47.0.2526.73) of Chromium on Ubuntu.

Did you see any error messages on the javascript console?

**Comment by manfredbrandl** [comment]
I already did some Footpath-Routing and I did see the following Error in the javascript console:
GET http://piwik.openstreetmap.org/piwik.php?action_name=OpenStreetMap&idsite=1…lp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1200x1920&gt_ms=10 400 (Bad Request)

Aftern opening the javascript console with F12 I selected the Openstreetmap in the upper left corner and "Bearbeiten" ("Edit") and now everything is fine.

**Comment by pnorman** [comment]
I'd guess is this is #2151, but there's the piwik 400 error. Of course, that could just be a red herring.

**Comment by manfredbrandl** [comment]
As I cannot reproduce the error and there is another issue about that I close it. I will reopen this or start another issue if it occures again.

**Comment by manfredbrandl** [comment]
Now i can confirm that the piwik Error does not prevent selecting and editing objects with iD.

**Comment by bootmii** [comment]
I still have this problem, there's no error or workaround in the console except using Firefox. On iD 1.3.6 by the way, the site said it can't update.

**Comment by pnorman** [comment]
> I still have this problem, there's no error or workaround in the console except using Firefox. On iD 1.3.6 by the way, the site said it can't update.

The 1.3.6 release is almost two years old, so I don't think anyone is planning on supporting it. If they want to use it they could try backporting https://github.com/openstreetmap/iD/commit/77b78a73ca6343006e089df505a0dec062d1edad. The other option that comes to mind is continuing on with 1.3.x, but like backporting, it would require the site that uses it to do the development work.

**Comment by bhousel** [comment]
Yes, @bootmii did you really mean to say iD 1.3.6?   That's a very old release.  
Who is using it?  Maybe I can help them upgrade?
