### ISSUE TITLE
RELEASING.md errors

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#2900]
* prior to `make translations` you need to run `npm install`
* make translations errors

```
$ make translations
node data/update_locales

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './transifex.auth'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/home/pnorman/osm/iD/data/update_locales.js:23:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
make: *** [translations] Error 8
```
* make suggestions installs node bindings for osmium. this seems unnecessary
* `git checkout release && git reset --hard master` errors with `error: pathspec 'release' did not match any file(s) known to git.

**Comment by bhousel** [comment]
Unfortunately `make translations` will error unless you have a `transifex.auth` file, the contents of which just look like:
```
{"user": "bhousel", "password": "*******"}
```
I may need to add you as an admin on the ideditor project so that you can run the command to login and download the files.  We have a functional `ideditor` account, but the password got changed and I don't know what it is anymore, so I just use my own credentials.

**Comment by pnorman** [comment]
Is it possible to set it up so anyone can download the translations without auth?

**Comment by jfirebaugh** [comment]
Last time I checked, no; Transifex required authorization for all API calls. That was a while ago; feel free to check again.

**Comment by bhousel** [comment]
> Transifex required authorization for all API calls. That was a while ago; feel free to check again.

Yes it's still true. [All API requests must be authenticated with HTTP Basic auth](http://docs.transifex.com/api/#authentication).

Ideally anybody can signup for Transifex, join [the ideditor team](https://www.transifex.com/ideditor/), then make a `transifex.auth` file like I described above, and be allowed to download our translation data with `make translations` without necessarily being an admin.  

@pnorman can you try this?
