### ISSUE TITLE
Mocha and PhantomJS 

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2905]
PhantomJS has transitioned to v2 but the version of Mocha we use as a testrunner is somewhat capped at PhantomJS v1.9.7, which is starting to show its age.  

A consequence of this:  running our tests was generating a bunch of ["SSL handshake failed" errors](
https://github.com/nathanboktae/mocha-phantomjs/issues/173) because PhantomJS has better TLS support starting in v1.9.8.  

I worked around the issue by adding 
~~`--ssl-protocol=any --ignore-ssl-errors=true`~~
`--ssl-protocol=tlsv1`  ([better] (http://stackoverflow.com/a/26417660/7620))
to the [test command](https://github.com/openstreetmap/iD/blob/1afab94a321e504044105d758764bfca287110a2/package.json#L11), but I don't view this a permanent fix.

Just opening this issue to keep track of the situation until either Mocha resolves the issue (ideal) or we switch to a different testrunner (bigger lift).

**Comment by jfirebaugh** [comment]
https://github.com/nathanboktae/mocha-phantomjs/issues/175

**Comment by jfirebaugh** [comment]
Sounds like we want to switch to https://github.com/nathanboktae/mocha-phantomjs-core and bring our own `phantomjs` binary.
