### ISSUE TITLE
Enter key clears feature selection search

### ISSUE THREAD

**Issue by bborkmiller** [openstreetmap/iD#2912]
Prior to 1.8.4, one of the flows for tagging a new object went like this:

* Create the object
* Press Enter: The Select feature type pane appeared and focus went to the search box
* Type in the name of the appropriate feature type
* Press Enter: The topmost search result was selected and applied to the object

Beginning in 1.8.4, pressing Enter after searching for a feature type clears the search box and de-selects the new object. This breaks the previous flow, which didn't require any mouse clicks until after the feature type had been searched for and applied.

**Comment by bhousel** [comment]
I broke this in 8139ca7.
