### ISSUE TITLE
Visibility of Select Halos when objects very close together

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2914]
The visibility of the select halos with the current breathe behavior is not always good.
Copied from #2879:
- Visibility of the halo is bad here:
  
  ![selection halos](https://cloud.githubusercontent.com/assets/13684947/12213216/f96290a6-b674-11e5-8865-ead8b081b6e7.PNG)
  https://openstreetmap.us/iD/master/#background=Bing&id=w111263466&map=17.52/7.00132/49.22868
  
  Visibily of the ends of the way is good, but these might be outside of the visible area in general.
  
  I believe selection halos need to be drawn on top of all objects except of selected objects.
  
  > Comment bhousel:
  > I agree that looks bad there - I'll try to adjust the draw order so that the halos appear above neighboring features.
- Due to the breathe behavior the selection halos are quite invisible for some time. This might be an issue if the user is not working slowly.
  How about making the halo more intense during the time of being thin?
  
  > Comment bhousel:
  > I did try this originally, an early version looked more like the "radar ping" that iOS Maps app uses to show the user's location - their halo starts out bright and then drops off as it spreads out. I found that although that style looked "prettier" (less "throbby") it was also much less visible during most of the animation.

**Comment by slhh** [comment]
>I'll try to adjust the draw order so that the halos appear above neighboring features.

Selecting multiple neighboring parallel ways it's likely looking bad. Therefore I believe the selected objects need to be drawn on top of the halos.

**Comment by bhousel** [comment]
closed by #3917
