### ISSUE TITLE
Address addr:housenumber Looses Focus After First Number Input

### ISSUE THREAD

**Issue by Gugym** [openstreetmap/iD#2915]
When using Firefox to edit an address the focus is lost from the addr:housenumber field after entering the first number. The user has to re-click in the box to continue typing. E.g. Go to an address, type 19 and only 1 appears without re-clicking on the input field box.

Please investigate.

I have also noticed (in Windows 8.1) that the focus has been going to the key short cut (e.g. type 11 and the second 1 will try to add a new point) which is slightly frustrating.

**Comment by bhousel** [comment]
Yes, this is being tracked in #2903
