### ISSUE TITLE
make failes

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#2917]
When I download a fresh copy of iD and start make it fails:
===
manfred@xxx:~/src$ git clone https://github.com/openstreetmap/iD iD >out 2>err
manfred@xxx:~/src$ cd iD
manfred@xxx:~/src/iD$ make >>../out 2>>../err
manfred@xxx:~/src/iD$ cd ..
manfred@xxx:~/src$ tail -30 err
npm ERR! git clone git://github.com/osmlab/editor-imagery-index.git Cloning into bare repository '/home/manfred/.npm/_git-remotes/git-github-com-osmlab-editor-imagery-index-git-0dd189be'...
npm ERR! git clone git://github.com/osmlab/editor-imagery-index.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/osmlab/editor-imagery-index.git github.com[0: 192.30.252.128]: errno=Connection timed out
npm ERR! Error: Command failed: Cloning into bare repository '/home/manfred/.npm/_git-remotes/git-github-com-osmlab-editor-imagery-index-git-0dd189be'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Socket.<anonymous> (child_process.js:956:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/manfred/src/iD
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/manfred/src/iD/npm-debug.log
npm ERR! not ok code 0
make: *** [node_modules/.install] Error 1
manfred@stvg-osm:~/src$ 
===

**Comment by bhousel** [comment]
> npm ERR! git clone git://github.com/osmlab/editor-imagery-index.git github.com[0: 192.30.252.128]: errno=Connection timed out

Have you tried digging into why the connection to github might fail here?

**Comment by manfredbrandl** [comment]
Thank you, the git port 9418 had to be opened on our firewall.
