### ISSUE TITLE
Change name of "OpenStreetMap (Mapnik)" layer to "OpenStreetMap (Standard)"

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#2919]
(logging this here after reading the somewhat cryptic reply at https://github.com/osmlab/editor-imagery-index/issues/133#issuecomment-172623479 )

The "Mapnik" name made sense when the alternative was "Osmarender"; but now that there are multiple Mapnik-based renderings just on osm.org it doesn't make a whole lot of sense. Users get understandably confused; there's been at least one example of a mapper logging a bug against Mapnik (the piece of software) for a perceived shortcoming in OSM Carto because iD's imagery layer talks about that layer as "OpenStreetMap (Mapnik)".

**Comment by bhousel** [comment]
Yes, I haven't yet changed anything related to `editor-imagery-index`.  I do plan to keep the "OpenStreetMap (Standard)" layer around, even though it was removed upstream.

**Comment by SomeoneElseOSM** [comment]
Apologies for any confusion - I'm not suggesting the removal of the layer currently described as "OpenStreetMap (Mapnik)" - I think what I'm suggesting is a change to the name in https://github.com/openstreetmap/iD/blob/14c618c3a8259eb3f9433c8fe24173d66a95c08a/data/update_imagery.js#L43 to "OpenStreetMap (Standard)".

**Comment by bhousel** [comment]
No problem, I understood what you meant.  I updated the name along with the other `editor-imagery-index` changes in aaaf830
