### ISSUE TITLE
Line of "backgroundless" map through Norway

### ISSUE THREAD

**Issue by 7rTheSuperPotato** [openstreetmap/iD#2920]
I don't know if this is a bug, but it is a bit strange. [From the village Svarstad and up](http://www.openstreetmap.org/edit#map=12/59.3986/9.9704). Does someone know wy and when it will be fixed? It does make it alot harder to map with a blurred bigger version of the map. It is actually impossiple. Help pls?

**Comment by jfirebaugh** [comment]
FYI: https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery

**Comment by bhousel** [comment]
@7rTheSuperPotato, please do not scrub the contents of closed tickets unless you have a good reason
