### ISSUE TITLE
Stop rendering amenity=swimming_pool?

### ISSUE THREAD

**Issue by math1985** [openstreetmap/iD#2926]
The tag leisure=swimming_pool is about 11 times as popular as amenity=swimming_pool. In addition, a proposal to discourage amenity=swimming_pool [has been accepted with an overwhelming majority](http://wiki.openstreetmap.org/wiki/Proposed_features/Discourage_amenity%3Dswimming_pool). The tag amenity=swimming_pool  is now [marked as discouraged on the wiki](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dswimming_pool).

iD (correctly) proposes the tag leisure=swimming_pool when searching for 'Swimming pool'. However, iD still displays a swimming pool icon for objects with the tag amenity=swimming_pool.

What do you think is best? Keep rendering the icon for discouraged tag because it is still in common use, or drop the icon in the hope that this will speed up the unification of the tags?

**Comment by math1985** [comment]
Some additional information: iD is the only of the big projects that does anything with amenity=swimming_pool. The tag is not rendered by openstreetmap-carto or Osmand, nor treated special in any way by JOSM.

**Comment by bhousel** [comment]
> What do you think is best? Keep rendering the icon for discouraged tag because it is still in common use, or drop the icon in the hope that this will speed up the unification of the tags?

We keep presets for deprecated tags that are in common use, but we mark them as unsearchable so users can not pick them.

[current stats on taginfo](http://taginfo.openstreetmap.org/search?q=swimming_pool#values):

count | tag
--- | ---
521 789 | `leisure=swimming_pool`
45 746 | `amenity=swimming_pool`


Tags do not magically change when editors prefer new tags over old ones.  If people want the tag to be changed, somebody needs to do the work of changing it.  Discussion on the tagging mailing list, and editing the osm wiki are not going to change the tags.

**Comment by math1985** [comment]
Thanks for explaining the rationale!
