### ISSUE TITLE
Use of the leisure=swimming_pool tag

### ISSUE THREAD

**Issue by math1985** [openstreetmap/iD#2927]
The tag leisure=swimming_pool is mainly used by mappers to mark the water area of a swimming pool. However, some mappers also use this tag to map an area that includes a swimming pool's facilities (for example a building that houses a swimming pool). A separate tag to capture the latter concept was [rejected](http://wiki.openstreetmap.org/wiki/Proposed_features/Aquatics_centre#Voting). However, the discussion did point out that the overwhelming consensus is to map the facilities of a swimming pool as leisure=sports_centre, sport=swimming.

Users of iD tend to use the tag for both the water area and the entire facility, which is understandable as the word 'Swimming pool' in English can mean both. The data would be more useful if iD could better support users to choose the correct tag.

I have some suggestions which might improve data quality. They are not mutually exclusive, but some of them might perhaps be better than others:

* [x] Render leisure=swimming_pool with a blue rather than a white outline.
* [ ] Call leisure=swimming_pool something like 'Swimming pool (water area only)'
* [ ] Add a searchable preset 'Swimming pool (facility)' or 'Swimming pool (sports centre)' or something of the sort for the tag combination leisure=sports_centre, sport=swimming.

If you have any other ideas how users can be helped to pick the right tag here that would be good too!

Thanks for having a look at this issue!

**Comment by bhousel** [comment]
These are good ideas..

I think 
* "Swimming Pool" is a good name for `leisure=swimming_pool`.. blue rendering will help.
* "Swimming Pool Facility" is a good name for `leisure=sports_centre + sport=swimming`

**Comment by math1985** [comment]
Yes, I think that would work!

**Comment by slhh** [comment]
The tag combination leisure=sports_centre + sport=swimming has been suggested for sport focused facilities.
>"Swimming Pool Facility" is a good name for leisure=sports_centre + sport=swimming
This would led to using it also for the more play focused facilities, where leisure=water_park should be used.

**Comment by bhousel** [comment]
> This would led to using it also for the more play focused facilities, where leisure=water_park should be used.

So we can also make a preset for:
- [ ] [`leisure=water_park`](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dwater_park)

And make sure that the terms for that include "swimming pool" so that anyone searching for a preset like that will see both options.

**Comment by HolgerJeromin** [comment]
Amenity =swimming_pool should not be used anymore. But your recent commit adds blue color to this tag...

**Comment by bhousel** [comment]
> Amenity =swimming_pool should not be used anymore. But your recent commit adds blue color to this tag...

The tag is still used.  When it is no longer used, I'll remove the blue color.

**Comment by HolgerJeromin** [comment]
Sorry, just read #2926 You can ignore my comment. ☺

**Comment by bhousel** [comment]
merged in fe246c6
