### ISSUE TITLE
Interact with layer beneath layer-data

### ISSUE THREAD

**Issue by sisskind** [openstreetmap/iD#2934]
Is it possible to draw a new layer beneath layer-data but still be able to interact with it?  For example, creating a new layer where the user can click to draw a new line segment which is below #surface in the stack.  When attempting to do this, it appears that the layer cannot be accessed on the click event.

**Comment by jfirebaugh** [comment]
Yeah, that's how HTML events work generally -- only the topmost element receives the event. You can adjust the behavior somewhat with the CSS `pointer-events` property, but then the data layer wouldn't get events.

**Comment by bhousel** [comment]
Yeah, I wanted to comment on this too, but I forgot to.

@sisskind, the `Behaviors` in iD are attached to the surface node [here](https://github.com/openstreetmap/iD/blob/e7a7e2edc58c2483075961551e6e7df93e829433/js/id/id.js#L223-L229).  So the #surface tends to grab all the mouse and touch events.

The only way I can think of to get around this would be to draw a separate invisible layer of hit targets (e.g. invisible rectangles or something) over the surface.
