### ISSUE TITLE
Freeform lasso shapes

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2937]
I want to be able to draw a freeform lasso shape instead of being limited to an axis aligned box.

**Comment by bhousel** [comment]
possibly useful:  https://github.com/d3/d3-plugins/tree/master/lasso

**Comment by kepta** [comment]
@bhousel  , I want to work on this.
Any heads up?

**Comment by bhousel** [comment]
Great!  

So we already have these 2 files:
* [`iD.behavior.Lasso`](https://github.com/openstreetmap/iD/blob/master/js/id/behavior/lasso.js)  - in iD _behaviors_ are just collections of event handlers that can activate/deactivate themselves depending on what mode you are in.  This code watches for `mousedown` `mouseup` `mousemove`.  On `mousemove`, handler calls `iD.ui.Lasso` to display it on the surface; on `mouseup`, selects the contained nodes.
* [`iD.ui.Lasso`](https://github.com/openstreetmap/iD/blob/master/js/id/ui/lasso.js) - draws the lasso box.

The example `d3.lasso` will not be a drop in replacement for what we have.  But you can look at what `d3.lasso` does on `mousemove`.  

`iD.behavior.Lasso` can still use the same event handlers it already has, but may need to send different data over to `iD.ui.Lasso`. 

The code to draw an SVG `path` will go into `iD.ui.Lasso`, replacing the existing code that draws a `rect`.
