### ISSUE TITLE
What if admin boundaries were disabled by default?

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#2942]
I'm not sure if data layers feature is coming or already implemented, but it will be easier for newcomers to edit/natigate uncluttered areas.

For instance, here is user added several highways, but they share node with admin boundary. Thus, there were disconnected roads like this one:
https://www.openstreetmap.org/way/367969949/history

See also
http://www.openstreetmap.org/node/3718359759
http://www.openstreetmap.org/changeset/33640372
http://nrenner.github.io/achavi/?changeset=33640372

**Comment by bhousel** [comment]
I have considered this.  It's how I prefer to edit, personally...

**Comment by bhousel** [comment]
Closing as stale, I think the existing map filters are working ok, and hiding certain data by default is likely to only increase newcomer confusion.
