### ISSUE TITLE
Rendering of incomplete multipolygons wrong

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2945]
The following two bugs have been discovered using iD master.

When drawing an incomplete multipolygon, the virtual edge seems to start at the wrong vertex, or is this an intended feature indicating the MP is broken?
![incomplete mp](https://cloud.githubusercontent.com/assets/13684947/12691259/773783e4-c6ea-11e5-97e3-af8404e3388e.PNG)
How to reproduce: Draw a line, set to "Line", and add multipolygon.

When removing a member from the "all members" section the member is still shown as selected until ckicking in the map window. 
![mp with deleted member](https://cloud.githubusercontent.com/assets/13684947/12692012/d7985de2-c6f1-11e5-9fc8-657e55f0ab7e.PNG)
How to reproduce: Select a multipolygon, remove one of its segmented outer members from "all members" section.

**Comment by bhousel** [comment]
Not quite sure what to do about these.

I know some people will say we should tighten up the rules for adding and removing things from multipolygons in the raw member editor, but I'm kind of more inclined to just let people do what they want and then run validations for these errors later.

Would #2223 be ok instead?

**Comment by slhh** [comment]
There seems to be a misunderstanding. The title may be a ambiguous: I don't mean it is wrong to render incomplete multipolygons; but the current rendering of these incomplete multipolygons seems to have two bugs.

**Comment by bhousel** [comment]
@slhh Can you retest these situations with the current release of iD?

c79c65f fixed a bug where the multipolygon rendering wouldn't update when member ways were changed.  I don't know if it fixes this issue, but it might..

**Comment by slhh** [comment]
Unfortunately, both bugs do still exist using master deployment.
