### ISSUE TITLE
Highlight relations/members when mouse is over item in all members or all relations

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2946]
- [x] When the mouse is over an item in all relations section the relation or all of its members should be highlighted in the map instead of the current selection.

- [X] When the mouse is over an item in all members section, the respective member should be highlighted in the map instead of the current selection. ( done in #5402 )

- [x] When the mouse is over an item of the selection list for adding of members/relations the same applies.

That would make identifying members and relations much easier.

**Comment by sun-geo** [comment]
Nice :-)
Thnak you!
