### ISSUE TITLE
Shift+Drag selection is broken

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2948]
Shift+Drag selection does only select nodes, but not lines and areas.

**Comment by bhousel** [comment]
I'm pretty sure it is that way by design, not broken.

I've always assumed the usecase for this feature is realigning a badly drawn segment:

![multiselect](https://cloud.githubusercontent.com/assets/38784/12707286/3010a276-c860-11e5-8850-f84645be85a3.gif)

**Comment by jfirebaugh** [comment]
Yes, it's this way by design.

**Comment by slhh** [comment]
I have changed the description in the shortcut list in the OSM wiki, which was wrong then.

Another usecase for block selection would be copying a complex building, maybe including the relations for 3d-modeling. This doesn't work with the current design.

What if it were selecting all fully enclosed objects? I believe it would still work for your usecase. Either a way wouldn't be selected, because any node is outside of the box, or the way would be moved in total anyway, because all nodes of the way are selected and moved.
