### ISSUE TITLE
With multiple features selected, indicate which one is mouse-hovered in the sidebar multiselect list 

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2949]
Edit: The remaining task is highlighting the list item when hovering the selected feature on the map, which is discussed and agreed on starting here: https://github.com/openstreetmap/iD/issues/2949#issuecomment-431540750
Original issue:

Identification of items in the multiselect list should be improved:

When the mouse is over an item of the list, selection halos of all other selected elements should be disabled temporarily.

This will likely require similar software infrastructure as #2946 , and is a prerequisite for some further potential enhancements of iD.

**Comment by bhousel** [comment]
I'm not removing the halo from the other selected items.  They are still selected and the user shouldn't forget about that just because they happen to put their mouse over that selection list. 

But I agree that:
* when mousing over a list item, that feature should get a `hover` style (maybe it does already)
* the `hover` style should be more distinguishable from the select style with consideration for colorblind users (I think it may only get a slight opacity bump)
* breathe behavior needs to be aware of `hover` style if it is mucking with opacity

**Comment by slhh** [comment]
> I'm not removing the halo from the other selected items.

I believe the user wants to go through the list quite fast searching for an item. Anything delaying the visisual detection of the hovered feature seems to be bad.

> They are still selected and the user shouldn't forget about that just because they happen to put their mouse over that selection list.
I would disagree in this specific case. While the mouse is over the buttton the users can't do anything harmful with the mouse. The only hamful thing they can do is using some shortcut keys, but they can't really work on the map for any significant time period without moving the mouse away from the hovered item; therefore they don't really have time to forget.

If the users were able to fill in the inspector with the keybord during hovering the item, I would agree; but the inspector is unavailable while the multiselect list is open.

In addition multiple items being selected is still visible, because the multiselect list is shown.

If you still want to protect something, you can consider disabling shortcut keys which are changing map data according to the hidden selection; but I think the risk is very low anyway.

**Comment by slhh** [comment]
In adition to the hover function, which has been discussed above, a reserse hover function would be useful. If the mouse is over one or more selected items on the map, the respective item of the multiselect list should be highlighted

**Comment by slhh** [comment]
@quincylvania, @bhousel, 
How do you think about my last comment here?

Everything else was done in #5402, thanks @quincylvania.

**Comment by quincylvania** [comment]
@slhh Reverse hover-highlighting does sound useful! I'd recommend creating a new issue for it and closing this issue since the original task was completed. I think it's more likely that someone will decide to work on an issue if it is clearly defined with a small scope (though this isn't always possible.)

**Comment by bhousel** [comment]
> If the mouse is over one or more selected items on the map, the respective item of the multiselect list should be highlighted. The list should be automatically scrolled to to show this item if required.

Sounds ok to me 👍

**Comment by slhh** [comment]
> I'd recommend creating a new issue for it and closing this issue since the original task was completed.

@bhousel, feel free to request this, but I think we don't need to do so in this special case. The title does still fit and I have edited the oriigal post to make clear what is remaining.

Otherwise, please update the label. We seem to have consent, and the considering label might prevent contributions.

**Comment by bhousel** [comment]
oh yeah, we don't really need a new issue.  I'll just retitle it..

**Comment by bhousel** [comment]
Just to restate the issue with a gif - it's this:
We currently support hovering on list items to highlight map features.  We should also support hovering on map items to highlight list features.
![multi select](https://user-images.githubusercontent.com/38784/47262106-2f222e00-d4ad-11e8-86c3-164660791fba.gif)

**Comment by TAQ2** [comment]
Hi I'm a new contributed and would like to look at this. Please could someone give me a hint as to where the code for this is, its a new and large codebase so a few comments from someone will save me a few hours of digging
