### ISSUE TITLE
Multiselect list: Additional space for (symmetric) multiselect operation icons. 

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2952]
The space in the radial menu is limited, and the number of potential operations for multiple selected feature is large.

Therefore, additional tool icons, which are specific for multiselect, could be placed on top of the multiselect list.

Example Operations:
* Group features (site relation)
* Make Area defined by lines
* Make Multipolygon

**Comment by bhousel** [comment]
It's no secret that I am [not a fan of the radial menu](https://github.com/openstreetmap/iD/pull/2145). 

I've always thought that iD would get a few more operations and we would outgrow the radial menu and need to do something different.  But it works well enough for now and nobody has come forward and written code for any new operations that would go on that menu.

Anyway I don't think we are at the point now where we are out of space on the menu and need to make another menu over by the select list.  I think before that happens, the radial menu itself would get a refresh.

I think open issues already exist for those example operations (if not go ahead and add them) - lets worry about those first before we worry about what menu they get attached to.
