### ISSUE TITLE
All Tags section: The key and the value should be visible in full length

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2953]
In the all tags section of the inspector the key and the value of a tag should be always visible in full length.

If the key or the value of any tag are too long for the current fields, the tag should be displayed in a two row style:
1. row: same as current style, but the key field is occupying the space of the current key and the current value field together.
2. row: value field is occupying the full width except of a little indentation.

If this is still not enough for a specific tag, key and value should be shown as multiline fields.

Especially tags which are not handled by the preset fields could have very long keys and values.
An example from taginfo:
destination:lanes = A2␣(West);London␣(South␣East␣&␣Central);Bexleyheath;A2␣(East);Canterbuy␣(M2);Dartford␣(A225)|M25;Dartford␣Toll␣Crossing␣(A282);Stansted␣(M11)␣(M1)|M25;Dartford␣Toll␣Crossing␣(A282);Stansted␣(M11)␣(M1)|M25;Dartford␣Toll␣Crossing␣(A282);Stansted␣(M11)␣(M1)

**Comment by bhousel** [comment]
I'd have to think about how to do that.. I don't think we could display the full value, but we could maybe add an icon that lets the user edit the value in a textfield. 

BTW, the example you gave is 254 characters, which is at the limit for what OSM allows in a tag value. 
Do people really tag lane signage this way? :grimacing:

**Comment by bhousel** [comment]
The full length values now show up as tooltips when hovering over a field that is too long to display.
see #3054
