### ISSUE TITLE
All Tags section: Tags not covered by preset fields should be indicated.

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2954]
Tags which are not covered by te preset fields should be marked in the all tags section of the inspector. These tags are the essential information of the all tags section for users working with the preset fields.

**Comment by bhousel** [comment]
It's not clear to me why anyone would care about this?   How does it help with editing?

**Comment by jfirebaugh** [comment]
https://github.com/openstreetmap/iD/issues/2971#issuecomment-180173058
