### ISSUE TITLE
If a feature is a relation or member of a relation should be visible at a look.

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2955]
If a feature is a relation or member of a relation is important information; therefore, it should be visible at a look, and not hidden in the all members or all relations section.

Idea for this:
If a feature is a relation or member of a relation, place an icon in the main feature box on top of the inspector, and also in the box of the item in the multiselect list:

![relation icon](https://cloud.githubusercontent.com/assets/13684947/12707150/464f7226-c890-11e5-8359-e1818fc64652.PNG)

If the feature is member of a relation, use the left icon.
If the feature is a relation itself, use the right icon.
If the feature is both, use the middle icon.

Example:
![relation icon example](https://cloud.githubusercontent.com/assets/13684947/12707329/3bc9c66e-c893-11e5-8eb0-af00b055f209.PNG)

**Comment by bhousel** [comment]
Why is knowing if a feature is a member of a relation important?  How does it help with editing?

**Comment by stephan75** [comment]
Because some novice users delete or replace small ways that are part of something like boundary relations ...
and that is one of the main reason why boundary relations get defect.

But IIRC there was some improvement on this issue inside iD, not?

We also have route relations or similar, or turn restrictions.

**Comment by slhh** [comment]
> Why is knowing if a feature is a member of a relation important? How does it help with editing?

Some examples:
* Each structural change of an highway needs special care, if there is a route.
* How to find where a turn restriction is set? ID doesn't support all turn restrictions yet.
* How to find where a name comes from if it is set in a site relation?
* If a line is extended, which is a segmented multipolygon member, the multipolygon is broken.

**Comment by manfredbrandl** [comment]
There is an additional requirement: I sometimes need to replace a relation member with another feature. That cannot be easily done with iD and I dont know JOSM. Any Chance?

**Comment by jfirebaugh** [comment]
https://github.com/openstreetmap/iD/issues/2971#issuecomment-180173058

**Comment by slhh** [comment]
@jfirebaugh , advanced users do likely know where relations are to be expected and when to check for relations carefully. In most cases they would avoid dangerous operations anyway.
The feature is more intended for less experienced users, who need to be aware of something being special. Please reopen.
