### ISSUE TITLE
Share transifex translation memory

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2961]
Explore ideas for mirroring iD's translation memory to the [openstreetmap organization](https://www.transifex.com/openstreetmap/public/) on Transifex. 
- [API docs](http://docs.transifex.com/api/tm/)
- download .tmx file and check into our repository?
- reupload it to an `id-editor-mirror` project under `openstreetmap` org?

**Comment by althio** [comment]
A few items for linking and reference:
[OpenStreetMap Forum » Development» Internationalized Tag dictionary](https://forum.openstreetmap.org/viewtopic.php?id=56889
)
https://github.com/westnordost/StreetComplete/issues/224#issuecomment-301276191

[iD - Transifex](https://www.transifex.com/ideditor/id-editor/)
[JOSM - launchpad](https://translations.launchpad.net/josm/trunk/)
[Maps.me - github](https://github.com/mapsme/omim/wiki/strings.txt)
[LearnOSM - Transifex](https://www.transifex.com/hotosm/learnosm-1/)
[StreetComplete - POEditor](https://poeditor.com/join/project/IE4GC127Ki)

**Comment by bhousel** [comment]
This was done!  Last week we moved the iD project to the OpenStreetMap organization and I think we are now sharing our translation memory in the `osm` group.

**Comment by magol** [comment]
What about the dictionary? Had not it been good to share that too?

**Comment by bhousel** [comment]
> What about the dictionary? Had not it been good to share that too?

I think when we switched the project to the OpenStreetMap organization, the individual language glossaries didn't move over.  I'm not sure.

**Comment by magol** [comment]
It is correct that the dictionary did not migrate over. I have worked a bit to restore the dictionary for iD, but it would be good if this dictionary could be used for the other projects to.
