### ISSUE TITLE
Selected items should be rendered at all zoom levels

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2962]
Selected items should be rendered at all zoom levels including the non-editable levels. In case of large features the user should be able to zoom out and see the full extension of the selected features.

**Comment by jfirebaugh** [comment]
I think this is a good idea, and it would be a natural extension of #2442.

**Comment by bhousel** [comment]
:+1: and we should show them in the minimap too.

**Comment by HolgerJeromin** [comment]
To make it worse right now zooming out and in drops the selection. (tried to fight against #1906)

**Comment by quincylvania** [comment]
I did this in dc7c3238fc8224ef0ad9ab98130b9b22e399960f.
