### ISSUE TITLE
Add backward/forward buttons to the inspector when jumping between features along relation links.

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2963]
When user is jumping to a member or relation he should be able to come back easily. Therfore, backward/forward buttons should be added to inspector when jumping between features along relation links. Buttons should be hidden when they are not enabled in order to avoid confusing new user, who likely don't jump along relation links.

**Comment by jfirebaugh** [comment]
https://github.com/openstreetmap/iD/issues/2971#issuecomment-180173058

**Comment by slhh** [comment]
@jfirebaugh ,
This is especially useful for exploring the relation stuctures. Therefore it is a great advantage
for users after their startup phase when they need to understand our datastructures. Without the proposed function it is quite difficult to find the right way back, which makes exploring difficult.
In addition this feature has a qualily benefit because checking things is likely avoided by users if it is too complicated. Please reopen the issue.
