### ISSUE TITLE
Multiselect list: Store multiselection when opening the inspector by clicking an item

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2964]
When the user is opening the inspector by clicking an item of the multiselect list the multiselection is currently lost. This is very bad in case the user just wants to check, if the right feature has been selected. There are also other usecases.
Therefore, the multiselection should be stored. The inspector should have a button to go directly back to the multiselect list and to restore the multiselection. The item which has been shown in the inspector last, should be indicated in the multiselection list.
The inspector should have a checkbox indicating and changing, if the feature is contained in the hidden multistelection. This is useful when browsing along relation links.
Preferably each item of "All Relations" and "All Members" should have such a checkbox too.

**Comment by jfirebaugh** [comment]
https://github.com/openstreetmap/iD/issues/2971#issuecomment-180173058
