### ISSUE TITLE
Should not display "planned" (and maybe "platform") for "highway"

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#2966]
Draw a line, then manually add `highway` and start typying `pla` as the value.
Note how it displays a `planned` value (while we should be using `proposed` instead).

`planned` should be removed from this list.

I guess that `platform` should also not be suggested/autocompleted in this list (as, most probably, it should be represented as `public_transport=platform`)

**Comment by bhousel** [comment]
Yes, you can try this search on taginfo too and get the same results.
Go to http://taginfo.openstreetmap.org/keys/highway?filter=ways#values and search for "pla"

**Comment by naoliv** [comment]
So what does this mean?
iD is using the same autocomplete values from taginfo?

**Comment by bhousel** [comment]
Yes, the autocomplete values in the raw tag editor and in some of the combo dropdown fields are just the results we get from the taginfo service.

There are a few hundred ways tagged `highway=planned` in OSM, so that's why they show up in the list when you type "pla".

**Comment by naoliv** [comment]
Could some values be filtered?

**Comment by bhousel** [comment]
`highway=planned` actually gets a boost because it has a wiki page.

If you really don't want it to show up, any of the following would work:
* find the 300ish ways and tag them with something else
* delete the wiki page
* don't search for "pla"
