### ISSUE TITLE
Make icons for disused and abandoned railways more clear

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#2967]
According to the docs, disused railways still have rails. When they are removed, it's abandoned. ~~The icons kind of suggest the reverse~~:
![railways](https://cloud.githubusercontent.com/assets/4283376/12816232/777291ea-cb4b-11e5-9e88-9e0ee8cbfe6c.png)

**Comment by M1dgard** [comment]
Wait, now I understand: the disused railway has tracks _crossed through_ with a dashed line, while the abandoned railway has it _crossed through_ with a full line.
So it may be me, or it's not really really clear at first sight.

**Comment by bhousel** [comment]
> So it may be me, or it's not really really clear at first sight.

I agree it's not really clear.  Maybe I could sneak some weeds into the "Disused Railway" icon and a tree into the "Abandoned Railway" icon..
