### ISSUE TITLE
Multiselect list: Each item should have a checkbox differentiating two subsets of the selection

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2970]
Each item of the multiselect list should have a checkbox differentiating two subsets of the selection.
This is intended to enable more complex operations requiring two different sets of operands. For example a copy tags operation needs to know from which feature the tags have to be copied to which other feature(s).

The checkbox could be styled as a flag, which can be empty or red filled, so we can talk about flagged and unflagged features.

Preferably some additional controls, like keyboard shortcuts, shoud exit, which allow to add a feature to the selection directly having the desired flag state.

**Comment by jfirebaugh** [comment]
Closing; see https://github.com/openstreetmap/iD/issues/2971#issuecomment-180173058.
