### ISSUE TITLE
Make it more clear that "Building" is a category

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#2972]
I've been to a few mapathons lately where newbies are confused about tagging buildings: often they'll click Building (the category) and assume that it's tagged, rather than scrolling down and clicking Building again (which then makes it pink and building=yes.) It's confusing to them to pick it twice, even when I have explained the first is the category and the second is the specific type. (Recognition versus recall and all that.)

Maybe call the category "Types of buildings" or "Building types" or something that makes it more apparent that the first time you click you're selecting a category and the second is the specific type? There's the little paper overlap thing on the categories, but I think that's too subtle for new people to understand or notice. 

Or maybe even have it so when you click the building category it automatically tags it as building=yes, and then you can choose another kind if you want from the dropdown.

I wonder if part of the confusion is that on smaller laptops or lower resolutions, the generic "building" is at the bottom of the list, and thus off the page, so they don't think to pick it.

**Comment by bhousel** [comment]
This is also mentioned in #2383 
I agree that we should style categories a little more clearly, maybe add a little more contrast to the stack of paper style, and add an expand/collapse triangle.

**Comment by aawiseman** [comment]
I think those sound like good ideas! And I agree with what @jfirebaugh said on the other issue, people didn't seem to understand it was a category even after doing it multiple times.
