### ISSUE TITLE
iD's scope and required operations

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2976]
@jfirebaugh , concerning your comment in #2971, I agree on  iD being a basic to mid-level editor; I don't see any chance to make it an advanced editor due to technical limitations anyway.

Some advanced mapping tasks like automatic changeset reverts, audio- and videomapping, mechanical edits experimental tagging styles don't need to be supported by iD.

We can't assume to have advanced mappers using JOSM everywhere. The typical local mapper will likely be an iD user. Therefore, iD needs to support all of the local mapping tasks; and iD needs to do this efficiently, because we must not waste the manpower of the local mappers, and we also need to avoid frustrating the mappers due to an inefficient editor.

Local mapping tasks to be supported efficiently do also include landuses, cycle-routes, bus lines etc.
I don't think iD users should be excluded from mapping such things.

The intended audience of iD need a **simple** way **to do** the **desired** edits **correctly**, without ignoring **efficiency**. But an editor, which is too simple, and doesn't provide the required functions, is not a simple solution. Experts might be able to do the job using insufficient editors, but less expierienced users need better tools.

Does the intended audience of iD mean, that iD's operations need to be less complex? I'd strongly disagree, and I think the reverse is truer. The complexity of the operation is mainly an issue for the developers. What needs to be simple in iD is using the operations; therefore, we need to built the complexity of using the operations into the operation itself. What is really complex to do in JOSM is not using a known operation, but to find the right set operations a a stragtegy to use these in order to achieve the desired result.

Operations in iD should be result oriented. JOSM's operations seem to be more data structure oriented.
Unfortunately, iD's current operation seem to be more UI driven, which is violating the form follows function principle. One example is its current 1-point area split, I would doubt there is any relevant usecase for it, it does just has a simple UI, but it is unusable for any relevant tasks.

JOSM has a large number of very specific operations; iD should have more universal operations to require less operations, reducing the pain of finding the right operation. When an user has found the right operation, it is much easier to find out how to use it; maybe looking at respective help page.
Basic operations should be intuitive,  but more advanced operations, may require using help or manual to discover them. This way we can keep the UI simple for for new users, because the full power of the operations can be partially hidden.

I will add more thoughts later, how to provide a **simple** way **to do** the **desired** edits **correctly**, without ignoring **efficiency**.

**Comment by jfirebaugh** [comment]
@slhh, suffice it to say that our opinions on what makes software simple and enjoyable for users appear to differ. The philosophy of the core developers has been guided by experience with many mapping tools, experience with similar vector editing software, feedback from mappers at numerous mapathons and meetups, and professional usability studies. We believe that in order to keep iD usable for entry level to mid-level users, we have to say "no" to many well intentioned feature requests and enhancements. Every additional feature dilutes all existing features, and we are all too familiar with software that accreted features until it felt bloated and unpleasant for even experienced users. We're going to try to avoid that happening to iD.
