### ISSUE TITLE
Option to make invisible relations visible

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2980]
The inspector should have a control to make invisible relations visible.
A graphical representation of routes seems to be easy. For other relation a net of lines connecting the members could be drawn.
If a relation has lost all of its members, it should be represented by a point. Of course this point and the relation must not be uploded. The user should get a warning with option to delete or rework instead. 

When the last member relationship is removed, the user should have an option to delete the relation or keep it temporarily as the virtual point. I believe this could simplify rework of relations.

**Comment by jfirebaugh** [comment]
We already have issues covering route relations: #659, #1575. When you select a relation, all members are highlighted on the map.

iD isn't going to gain a bunch of features for advanced relation editing, as you seem to want. Sorry. That's just not it's domain.
