### ISSUE TITLE
Inspector could have a menu on top

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2981]
The inspector could have a menu on top. 

* This would be a natural position for the controls of #2979 and #2980
* Moving the delete operation from the radial menu to this menu might be useful, especially in view of #2977 
* Moving some other operations from the radial menu to this menu could free space in the radial menu in case this is required in future.
* The control to go back to the multiselect list according to #2964 could be placed in this menu.

**Comment by jfirebaugh** [comment]
This may well be where #1994 ends up. But I don't think we need a separate issue.
