### ISSUE TITLE
iD repositions to a random place on zoom out

### ISSUE THREAD

**Issue by kepta** [openstreetmap/iD#2991]
I think this screen recording explains the best.
 [![Video](http://img.youtube.com/vi/prn241Kv2eE/2.jpg)](https://youtu.be/prn241Kv2eE).

**Steps to reproduce**
1. Zoom in to a place.
2. Pan to some place.
3. Zoom out. *(Used Macbook Trackpad)*

**Expected result**
Zoomed out view

**Actual result**
iD repositions to a random place 
*Chance event*

** Details **

At exactly 00:16 of the video I try to zoom out and the screen goes blank and shows multiple errors *(26 in this case)* in console.
```
Uncaught TypeError: Cannot read property '0' of null

translateTo @ d3.v3.js:1793

mousewheeled @ d3.v3.js:1971

(anonymous function) @ d3.v3.js:1463

```

**Comment by bhousel** [comment]
This is a dup of #2773, but that is great that you were able to capture the errors in the console.

The handler code is trying to call `projection()` on an invalid / null / NaN value.  If it's really repeatable, you could add an `if (condition) debugger;` or other conditional breakpoint around that code.
