### ISSUE TITLE
Art shops described as 'Art gallery' in presets

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/iD#2999]
shop=art tag is currently described as "Art gallery" in the presets. It would be a lot less confusing to make that title "Art shop"

That's because art galleries are either mapped as tourism=gallery  ...or some people (depending on viewpoints in [this strange debate](http://wiki.openstreetmap.org/wiki/Talk:Tag:tourism%3Dgallery)) map them as tourism=museum   Some other people (who are wrong in a different way) may map *some* types of art gallery as shop=art, but I think we're all agreed that certain types of dinky little art shop get the shop=art tag. ...which doesn't fit with this preset title. All in all, I think the title adds to the confusion unnecessarily, and we can (hopefully) agree that "Art shop" goes better there.

![screenshot](https://i.imgur.com/yC94wFs.png)

**Comment by bhousel** [comment]
Oh thanks!  Yes this is definitely wrong.

It looks like I changed the preset label in f67ec4f, but I remember that day I was just going through the [`shop=*` wiki page](https://wiki.openstreetmap.org/wiki/Key:shop) to add missing presets, and I think the wiki may have lead me astray.

<img width="850" alt="screenshot 2016-02-24 09 08 48" src="https://cloud.githubusercontent.com/assets/38784/13287684/4edf4d82-dad6-11e5-88e6-dac7e3626e3c.png">

**Comment by harry-wood** [comment]
aha. [fixing the wiki too](http://wiki.openstreetmap.org/w/index.php?title=Template:Map_Features:shop&diff=1275786&oldid=1275151&rcid=&curid=11260)

**Comment by bhousel** [comment]
Thanks, I also did a few things in 80bbb44 that will hopefully make it easier for mappers to pick the right thing:
* Added a `tourism=gallery` preset for Art Gallery 
* Changed the Art Shop preset icon to be a shopping bag
* Adjusted the search terms

Here are how the search results look now:

"art" | "gal" | "paint"
--- | --- | ---
<img width="382" alt="screenshot 2016-02-24 09 34 53" src="https://cloud.githubusercontent.com/assets/38784/13288628/cfa5dc52-dada-11e5-9ed5-b36da3c0170a.png">|<img width="383" alt="screenshot 2016-02-24 09 35 10" src="https://cloud.githubusercontent.com/assets/38784/13288630/d5ea2730-dada-11e5-874b-072e7ceb0c8d.png">|<img width="371" alt="screenshot 2016-02-24 09 35 25" src="https://cloud.githubusercontent.com/assets/38784/13288633/da0ace1e-dada-11e5-96f8-a6121500f8a5.png">

And some taginfo / wiki expansions... These could be improved on the wiki side:

<img width="367" alt="screenshot 2016-02-24 09 37 12" src="https://cloud.githubusercontent.com/assets/38784/13288666/0042a458-dadb-11e5-8902-74d145167a0e.png">
<img width="371" alt="screenshot 2016-02-24 09 37 21" src="https://cloud.githubusercontent.com/assets/38784/13288665/00427082-dadb-11e5-8786-2c7bda9cfc11.png">
<img width="376" alt="screenshot 2016-02-24 09 37 28" src="https://cloud.githubusercontent.com/assets/38784/13288667/004421f2-dadb-11e5-9609-4b318da9c955.png">

**Comment by bhousel** [comment]
Kind of iffy on these too:

<img width="371" alt="screenshot 2016-02-24 09 52 42" src="https://cloud.githubusercontent.com/assets/38784/13289022/702ced68-dadc-11e5-845b-a677b08895fb.png">
<img width="370" alt="screenshot 2016-02-24 09 52 50" src="https://cloud.githubusercontent.com/assets/38784/13289023/702d67e8-dadc-11e5-90c7-632d03f6c5ce.png">
