### ISSUE TITLE
Support RTL layout

### ISSUE THREAD

**Issue by SafaAlfulaij** [openstreetmap/iD#3007]
Application layout should support RTL layout for languages written from right to left.
This is what I mean:
LTR layout (Default):
![LTR layout - Default](http://4.bp.blogspot.com/-EzUf6UQhhus/UR6ATD23lZI/AAAAAAAAB88/_APE31dL4zw/s1600/setings-ltr.png)
RTL layout:
![RTL layout](http://2.bp.blogspot.com/-txMrX6kMxtY/UR6AW28Jx9I/AAAAAAAAB9E/DhVAtPhkPSI/s1600/settings-rtl.png)
Notice how the layout is mirrored.

**Comment by HolgerJeromin** [comment]
Can this be closed?

**Comment by bhousel** [comment]
Yes!
