### ISSUE TITLE
404 on Loading traffico.css

### ISSUE THREAD

**Issue by davidchiles** [openstreetmap/iD#3011]
Trying to load the 'Traffic Sign Overlay (Mapillary)' layer no icons show up.

In the console I get:
```
Failed to load resource: the server responded with a status of 404 (Not Found) http://www.openstreetmap.org/iD/traffico/stylesheets/traffico.css 
```

**Comment by bhousel** [comment]
Yes, when I packaged the release up for openstreetmap.org, I missed including the traffico files needed to display the traffic signs.  Things are a bit complicated because of how the rails site handles assets, but I'm going to release a fixed version tonight.

**Comment by davidchiles** [comment]
@bhousel Thanks! Really looking forward to this feature. Great work.
