### ISSUE TITLE
If "show my location" is used, long lines or wide areas can result

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#3016]
I noticed someone add a large area with one end in London and the other Tanzania and wondered how they did it.

If I start adding a line, click "show my location" the browser (still in the iD editor) changes to show London at z9.  If I zoom in iD will eventually let me add other the end of the line, a long way from the start.  Example (on the dev site):

http://api06.dev.openstreetmap.org/way/4300424840

I don't know if this is how the London / Tanzania large area was created, but it's a route to creating long lines that should probably be blocked.

Edit: For info, this was with iD 1.9.0.

**Comment by bhousel** [comment]
Thanks for finding this!
