### ISSUE TITLE
I want to use OSM in opencart for find near by store from user

### ISSUE THREAD

**Issue by Imakerinfosoft** [openstreetmap/iD#3017]
I want to use OSM in opencart for find near by store from user

**Comment by manfredbrandl** [comment]
This is off topic.

**Comment by bhousel** [comment]
> I want to use OSM in opencart for find near by store from user

Cool, that's great!

This is just the issue tracker for the iD web-based editor.
Here are some links that can help you:  
* [Using OpenStreetMap](https://wiki.openstreetmap.org/wiki/Using_OpenStreetMap)
* [Applications of OpenStreetMap](https://wiki.openstreetmap.org/wiki/Applications_of_OpenStreetMap)
* [Commercial providers or OpenStreetMap Software and Services](https://wiki.openstreetmap.org/wiki/Commercial_OSM_Software_and_Services)
