### ISSUE TITLE
Use of HTML5 history API

### ISSUE THREAD

**Issue by kepta** [openstreetmap/iD#3018]
I was thinking that iD should remember major changes in the url.
Currently iD doesn't keep a record of the part in url after \#. 

For eg.
- The level of zoom.
- Major change in the latitudes or longitudes, *(jumping across a city)*.

**Comment by kepta** [comment]
*After discussing on IRC with @bhousel,
A use case for this enhancement.*

The user can suddenly find themself somewhere that they didn't expect to be.. whether due to the panning bug, or even just moving the minimal around.

**Comment by jfirebaugh** [comment]
I'm not sure this is a good idea. It's a pretty well established convention with web slippy maps that panning and zooming doesn't add history entries. I find the sites that do add history entries with every pan and zoom to be quite annoying to navigate back from. And adding history entries in some cases, but not others, sounds like it would introduce an unpredictability that would also be a poor user experience.
