### ISSUE TITLE
Label baseline not centered in IE11, Edge

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3020]
See #618, #715 for previous work on this related to Firefox, Opera.

`dominant-baseline` and `baseline-shift` [are not supported](https://msdn.microsoft.com/en-us/library/gg558060%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) in IE11 and Edge.

As a hacky workaround, we may just need to detect these browsers and set the `dy` attribute in the label code.  [details here](https://nelsonslog.wordpress.com/2011/09/12/svgtext-baseline-considered-harmful/)

<img width="274" alt="screenshot 2016-03-08 13 08 40" src="https://cloud.githubusercontent.com/assets/38784/13611163/039f139e-e52f-11e5-87d5-7625fd00f6fa.png">

**Comment by HolgerJeromin** [comment]
Perhaps you could drop all baseline stuff and use `.setAttribute("dy", "0.6ex");` for all browsers.

**Comment by bhousel** [comment]
@HolgerJeromin Yeah I will try that, it would be nice if that turns out to be a good enough solution for all browsers

Hoping to also fix #1645 while I'm in there touching the label code.

**Comment by HolgerJeromin** [comment]
Have you tried the dy for all? I had very good cross browser results in my project in 2012

**Comment by bhousel** [comment]
> Have you tried the dy for all? I had very good cross browser results in my project in 2012

I didn't try that, but it probably would work.  I'll try it out today now that I know we have something working.
