### ISSUE TITLE
When multiple relation rings meet, allow disconnecting but keep rings intact

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3021]
#1714 is a good check to keep users from disconnecting multipolygon rings. But at vertices where multiple rings meet, it should be safe to disconnect the rings from one another and keep them intact.

e.g. disconnect should be allowed here, leaving R1 and R2 intact but disconnected:
<img width="595" alt="screenshot 2016-03-08 15 55 13" src="https://cloud.githubusercontent.com/assets/38784/13616048/32992088-e546-11e5-9b86-f645d250799d.png">

see also: https://github.com/openstreetmap/iD/issues/2739#issuecomment-193823838

**Comment by slhh** [comment]
In case both multipolygon rings belong to the same multipolygon another valid variant to disconnect exists at that node by generating a single large ring containing R1 and R2.

**Comment by bhousel** [comment]
> In case both multipolygon rings belong to the same multipolygon another valid variant to disconnect exists at that node by generating a single large ring containing R1 and R2.

This might be true, but I don't trust our ability to handle that situation in code.

The example with 2 connected multipolygons is easy, because that vertex "sees" 2 parent relations and can keep them as 2 relations after disconnection.

The example with 1 multipolygon and multiple touching outer rings is trickier, because the vertex "sees" 1 parent relation and would need to intelligently decide which ways need to be kept together, possibly splitting some of the ways, in order to end up with 2 valid rings.

**Comment by bhousel** [comment]
Closing this because it is a harder problem than I thought initially.

I was thinking multipolygons, but the edges could be highways, and then this vertex could also include turn restrictions or transit routes, or any other kind of relation where disconnecting would cause big problems.  Not worth the time to figure out how to safely disconnect those other things.
