### ISSUE TITLE
Language auto-completion for Multilingual name doesn't work the same for all languages

### ISSUE THREAD

**Issue by yogiks** [openstreetmap/iD#3023]
While selecting languages for adding multilingual name, the auto-completion for language names doesn't work as expected for all languages when English names are used. In below example, Hindi works but not Tamil and Telugu -

![Latin script](https://cloud.githubusercontent.com/assets/6291913/13636031/890e47c4-e625-11e5-9f89-ff228cde718e.gif)

But when respective language scripts are used to add languages, it works as expected by completing the correct language name -

![Indic scripts](https://cloud.githubusercontent.com/assets/6291913/13636033/892f44f6-e625-11e5-8eb3-d2b0441e03a6.gif)

Since English is the default preferred language if the user hasn't set his own language preferences, I think the auto-completion should be working the same across all languages when typed in English.

**Comment by bhousel** [comment]
I agree that dropdowns for language should support both the natural representation and the latin character representation of the language name, if that's what you are proposing.

**Comment by yogiks** [comment]
Yes, it would great if drop-downs can support Latin character representation.
