### ISSUE TITLE
Support maki2

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3024]
This is just a placeholder issue to keep an eye on 
~~https://github.com/mapbox/maki-2/issues/46~~
~~Maki2 will likely be merged into Maki, which will get a major semver bump.~~

^UPDATE: this happened already, see https://github.com/mapbox/maki/pull/241

  This is good!

iD is currently pinned to Maki 0.5.0, so we don't need to do anything right away.

We might be able to [install both versions](https://github.com/npm/npm/issues/5499#issuecomment-129481232), and build 2 spritesheets so that we don't lose any of the Maki1 icons that aren't yet available in Maki2.

**Comment by bhousel** [comment]
related ticket in Maki:  https://github.com/mapbox/maki/issues/270

**Comment by pnorman** [comment]
https://github.com/mapbox/maki-2/issues/46 gives a 404

**Comment by bhousel** [comment]
Thanks @pnorman I updated the issue.
`maki2` repo is gone and its contents got folded into the main `maki` repo.
see https://github.com/mapbox/maki/pull/241

**Comment by nickidlugash** [comment]
@bhousel I just wanted to flag that Maki 2 icons are different sizes than Maki 1: they are 11px/15x versus 12px/18px/24px. It looks like you're currently using Maki 1 `-24` for the UI, resized to 32px, and Maki 1 at actual size for the map? Will it work for your purposes to use both versions at the same time?

/cc @natslaughter @aparlato

**Comment by bhousel** [comment]
> Will it work for your purposes to use both versions at the same time?

It would probably be ok, but we'll need to add some code to store what icon sizes are available and have iD pick the best size.  See #3025 for more info
