### ISSUE TITLE
Support different icon sets

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3025]
One actionable thing we can do to get ready for #3024 would be to support icon namespacing in the presets.

For example, we currently do:

``` js
{
    "icon": "bicycle",
    ...
    "tags": {"shop": "bicycle"},
    "name": "Bicycle Shop"
}
```

And we use a little bit of magic to know that `bicycle` is a Maki icon, and not one found in the iD spritesheet.

We should namespace this string to:
1. eliminate magic "is it maki or not" code 
2. support both maki1 and maki2
3. open up the possibility for people with custom presets to use other iconsets:

``` js
    "icon": "maki1:bicycle"
    "icon": "maki2:bicycle"
    "icon": "fontawesome:bicycle"
```

**Comment by kepta** [comment]
We change all the icons which we get from maki to "x" => "maki1:x",
and then in the file,
*id/ui/preset_icon.js:12*
``` Javascript
  icon = p.icon || (geom === 'line' ? 'other-line' : 'marker-stroked'),
```
we do some logic to determine whether it is coming from maki1, maki2 or fontawesome.
Is my understanding correct ?

**Comment by bhousel** [comment]
@kepta, it's more complicated than that.. I started to list out the places in code we would need to change, but it got to be quite a lot of things, and I'm still not sure myself if what I am thinking is the best way to support this.  I need to think about it for a few days to decide if it's even worth doing.

Key challenges to supporting multiple icon sets are:
- code in `defs.js` needs to namespace all of the svg id's to avoid DOM conflicts.
- different icon sets support different icon resolutions.. e.g. maki1 is `-12`, `-18`, `-24`, maki2 is `-11`, `-15`
- changes in `preset_icon.js`, `labels.js`, etc..
- do this in a way to support splitting out the presets into separate projects per #2656

Also forget what I said about fontawesome - it's really a [webfont, not a svg icon set](http://www.sitepoint.com/icon-fonts-vs-svg-debate/).  But I do hope more designers move towards offering svg icon sets now that GitHub has done it.   Even if an icon repository has the svg source files in it, we could package them up ourselves into a sprite they way we already do with maki.

**Comment by bhousel** [comment]
For now let's just support maki2 and we will revisit later the idea of supporting multiple spritesheets if an iD fork project needs this.

**Comment by bhousel** [comment]
This is happening anyway for the cleanups for #3924
I've split the internal iD poi icons out into a new library: https://github.com/bhousel/temaki
