### ISSUE TITLE
Bird hide mapping in ID

### ISSUE THREAD

**Issue by sylvain-m** [openstreetmap/iD#3026]
Hello,

Sorry if this is not the appropriate place for this kind of suggestion, but I'm not a regular on this platform (first message in this community).
As an ornithologist, I'm interested in mapping public bird hide (http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dbird_hide).
If possible, I would like that ID (which is for me a great editor, congratulations !!!) offers appropriate tags to this object category (and possibly also in my language, which as you can see, is not English!).
However, I do not know how to participate in enriching ID on this feature.
Thank you to you for your advice.

As this is a forum for suggestions, here's my suggestion:
Add the bird hide mapping in ID (tag leisure = bird_hide)
If you want, I can give you a specific rendering (png icon).

Sylvain M.

**Comment by bhousel** [comment]
Thanks @sylvain-m this is the right place.. I'm glad you like the editor! :)

We can add a preset for `leisure=bird_hide`.  I don't see a suitable icon in [maki](https://www.mapbox.com/maki/), so it will probably just look like a generic marker for now..

**Comment by sylvain-m** [comment]
> We can add a preset for leisure=bird_hide
Great ! Thank you very much.
In french, it is "Observatoire ornithologique". Could you add the french preset to ?
>  I don't see a suitable icon in maki
As I said, i could propose a marker that would be suitable (based on binocular, because this places are made for binocular owners). Where can i do it for maki ?
Thanks !

Sylvain M.

**Comment by bhousel** [comment]
> In french, it is "Observatoire ornithologique". Could you add the french preset too ?

All of iD's presets are translatable on [Transifex](https://www.transifex.com/ideditor/id-editor/dashboard/) to many different languages.  I'll add the preset now, and it should appear there for translation sometime tonight.

>As I said, i could propose a marker that would be suitable (based on binocular, because this places are made for binocular's owners). Where can i do it for maki ?

You can propose a new Maki icon [here](https://github.com/mapbox/maki/issues).

**Comment by sylvain-m** [comment]
Thank you very much for this improvement ! :)
I've made the translation in Transifex.
(i didn't know the term "machan" : could you tell me what it mean ?)

In how much time do you think this improvement will be operational in ID ?

**Comment by bhousel** [comment]
> (i didn't know the term "machan" : could you tell me what it mean ?)

It just means Bird Hide:  https://en.wikipedia.org/wiki/Bird_hide

>In how much time do you think this improvement will be operational in ID ?

Probably this month.  We don't have anything planned yet, but it is good to let translators catch up before we make a new release.
