### ISSUE TITLE
Multiselect list: All tags section

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3028]
This one is mainly intended as a safer substitute for #839 and #1791.

Like the inspector the multiselect-list should have an all tags section below it. This should list all tags which belong to any of the selected objects.

 A statistics block should be below each key value pair, and should have the following form:

- points: # set, # unset, # different
- vertices: # set, # unset, # different
- lines: # set, # unset, # different
- areas: # set, # unset, # different
- multipolygons: # set, # unset, # different
- other relations: # set, # unset, # different

"#" has to be replaced with the number of matching selected objects. "different" means same key but different value. Words can be replaced by icons with mouse-over explanation.

Lines without matching objects should be hidden. In most usecases only one or two lines of the statistics block would be visible.
Clicking on a line of the statistics block should offer offen an operations menue with the following operations (shown for the area case):
* remove tag from all areas
* set tag for all areas if unset
* set tag for all areas overwriting <list of values to be overwritten>

There should be a button to add a new tag similar to the inspector. The tag should not be automatically added to all selected objects after entering the key/value pair, but the statistics block should be shown. The user can use above operations to apply the tag to all desired object types. Therefore, the risk of applying the tag to the wrong type of objects or overwriting values accidentially is reduced.

**Comment by bhousel** [comment]
It sounds like you're looking for us to build a mass retagging tool into the multiselect list.  This really is out of scope for iD, but I think JOSM has a feature like this.

**Comment by slhh** [comment]
@bhousel You seem to have totally misunderstood my intention. This is intended for tagging many objects, but not for mass edits, and it is more focused on adding/copying tags than retagging.

The relevant information of the statistic numbers is to differentiate zero, one, or some objects.

JOSM is an excellent tool for mass retagging. Mass retagging should be done by advanced users only. Someone who is not able to understand JOSM is likely not the right person to do mass retagging.
iD cant become a good mass retagging tool anyway due to technical limitations and inappropriate concept for this application, for example a mass retagging tool needs to be able to load/filter large amounts of data and/or get filtered data from the (Operpass)-Api. Thus, there is no reason why I could wan't to build a mass retagging tool into iD.

You seem to support #839 and #1761. JOSM has such functions, which are very useful, but I do also know common errors using these functions. This issue is mainly a combination of both with some measures to prevent such errors as much as possible. Therefore, it should not be out of scope of ID. You should better think how a proposed feature can be a benefit for in-scope operations instead of searching any out-of-scope application which might have a benefit too.
