### ISSUE TITLE
waterway=dock is misleading to US_en speakers

### ISSUE THREAD

**Issue by cliffordsnow** [openstreetmap/iD#3030]
When facilitating a US mapathon recently, I was asked if they had added polygon dock feature correctly. Using the search facility the user added the dock tag to an area. I informed the user that it should be tagged as as man_made=pier. See https://wiki.openstreetmap.org/wiki/Tag:waterway%3Ddock for defination of a dock. As a US_en speaker, I can easily understand the confusion. Where I came from, if it extended out into a body of water, it was a dock. 

I believe that search for dock should return the tag man_made=pier or some indication that a dock is an enclosed feature for boats/ships.

**Comment by bhousel** [comment]
Ok, I agree we can change the search terms to make this better.

Should we change the caption to "Drydock" ?  That makes it much more clear to an en_US speaker what the preset is for.

**Comment by cliffordsnow** [comment]
Drydock is as close as we are going to get.

**Comment by pnorman** [comment]
I'd call man_made=pier "pier" in en_US, but also have dock as a search word. i.e. en_US dock is man_made=pier. I can't come up with a general en_US name for waterway=dock. Dock is obviously inappropriate. Drydock, dry dock, and wet dock are all appropriate for some types of docks.

Do we have any icons that make it clearer it's an area of water, or at least sometimes water?

**Comment by bhousel** [comment]
looking here: https://en.wikipedia.org/wiki/Dock_(maritime)

Maybe "Dockyard" or "Shipyard"?    Those words make it more clear to an en_US speaker that the feature is not for piers, and that it is for an area.

Are those words compatible with how `waterway=dock` is used in OSM?

**Comment by slhh** [comment]
Wikipedia: "A dockyard (or "shipyard") consists of one or more docks, usually with other structures."
Therefore, a dockyard seems to be a larger area than the dock itself.

Idea to solve the issue:
Provided that you find more clear name for all of the specific types of docks defined by dock=*, you could make an individual preset for each of these specific types, and a non-searchable preset for waterway=dock without dock=* which can still be named "Dock" according to British English. An American English speaker would likely convert it to one of the more specific types due to misunderstanding, but this is an improvement of OSM data and not an issue.

**Comment by bhousel** [comment]
> Therefore, a dockyard seems to be a larger area than the dock itself.

That's a good point. I did also take a look around [Cardiff Bay](http://www.openstreetmap.org/edit#map=16/51.4622/-3.1624) to see how the tag is used in UK.  It looks like the docks themselves really are the individual "parking spaces" for ships, so I agree calling it a "dockyard" is wrong.

> Provided that you find more clear name for all of the specific types of docks defined by dock=, you could make an individual preset for each of these specific types, and a non-searchable preset for waterway=dock without dock=

That's a good suggestion, but unfortunately taginfo shows that it's [not a common tag](http://taginfo.openstreetmap.org/keys/dock#values), and the most common values are "drydock" which is ok, and "floating" dock, which would be confusing to en_US speakers.

So what I've decided to do is call the feature a "Wet Dock / Dry Dock" in the source (en_US) preset name. 

I'll check in with the en_GB crowd tomorrow morning and ask them if they want it to remain as "Dock" in en_GB.

**Comment by bhousel** [comment]
<img width="378" alt="screenshot 2016-03-14 23 15 35" src="https://cloud.githubusercontent.com/assets/38784/13766720/d5e33726-ea3a-11e5-88fd-ed872883f866.png">

closed in f69714f

**Comment by boothym** [comment]
Still a few docks being added in the USA when they should tagged as be piers, but fortunately not that many in comparisons to proper piers.

@bhousel If I (en-GB) type in "dock", wet dock / dry dock comes up as expected. Is this the same for en-US users? If so could this be changed so pier appears at the top of the list?

Or does something like "landing stage" need to be added for en-US users to make it even clearer?

**Comment by bhousel** [comment]
Thanks for checking @boothym, it's good to revisit this to see if last year's change in the preset name made any improvement.  I think it's acceptable for a "a few" (dozens?) to be tagged wrongly, but it would be a problem if lots (hundreds?) of piers continue to be mistagged.

Here's what the preset suggestions look like in en-US:

### select point, type "dock":
<img width="400" alt="screenshot 2017-07-25 22 50 57" src="https://user-images.githubusercontent.com/38784/28602410-e3ccbbe4-718b-11e7-9bb0-133325f81ba4.png">

### select line, type "dock":
<img width="400" alt="screenshot 2017-07-25 22 51 08" src="https://user-images.githubusercontent.com/38784/28602423-f74e6762-718b-11e7-9f5f-47a73dfb2f06.png">

### select area, type "dock":
<img width="400" alt="screenshot 2017-07-25 22 51 20" src="https://user-images.githubusercontent.com/38784/28602426-fb4ba2f8-718b-11e7-910c-c44df87c265a.png">

### wiki:
Also worth mentioning that both presets have a really great wiki documentation, if the user clicks the ℹ️ 
<img width="377" alt="screenshot 2017-07-25 22 54 03" src="https://user-images.githubusercontent.com/38784/28602467-4780ef7a-718c-11e7-873f-511f6483e47e.png">

**Comment by boothym** [comment]
About 175 dock ways edited in the past 12 months in the USA, not including those which have been corrected to piers. In total there's about 400 docks tagged in the US.
I thought that was a lot, but then realised that about 9000 piers had been edited in that same time!

So in fact it's not a big problem and seems like the presets are doing their job, I just wondered if there was an en-US difference sorting order.

**Comment by bhousel** [comment]
Nice - that is good to hear that the presets are mostly being used correctly.  9000 piers is a lot!  👍   I won't change anything for now.
