### ISSUE TITLE
When loading multiple gpx files, labels from first file stay visible

### ISSUE THREAD

**Issue by st-anton** [openstreetmap/iD#3032]
When importing one track after the other (by drag and drop), the labels of the tags are wrong. Some of the labels from the first tracks are displayed on tags of the second track.
I added two tracks. First track has a tag with 'Lindenstraße 4 keine Moschee' in Furtwangen (48.05102/8.20671). Importing the second track afterwards, the label appears in Waldau (47.98213/8.16653) This should be the filename of an image (0DKl_dil--.1.jpg)

[twotracks_errorlabel.zip](https://github.com/openstreetmap/iD/files/170849/twotracks_errorlabel.zip)

**Comment by st-anton** [comment]
This NOT a duplicate of #3031 but a different issue.
It's really confusing, if you map one track after the other and see completly wrong tags on your editor. Filenames of images and text comments are mixed up, old and new tags are mixed up.
- May it be, that during loading of a new track the old 'database' is not cleaned up correctly?
- May it have to do with characters in the filename like <.> in the example <0DKl_dil--.1.jpg> ?

**Comment by bhousel** [comment]
Thanks for the bug report, I do see this issue with the gpx file labels..
