### ISSUE TITLE
Why doesn't "CNG" string exist in the translations ?

### ISSUE THREAD

**Issue by ibraheem5000** [openstreetmap/iD#3033]
Hi,

I can't find the "CNG" (CNG - Gas Station) in translations!!!

CNG refers to Compressed Natural Gas.

Why?

**Comment by kepta** [comment]
Hey @ibraheem5000, 
can you be a bit more specific about the problem and also which language are we talking about here?

**Comment by bhousel** [comment]
This is sort of related to #1987 

We don't yet support detailed tagging for the types of fuel that a Gas Station sells.
