### ISSUE TITLE
Multiselect checkbox field

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3034]
Some tags in OSM use this style of tagging where people can make up what they want in the `key` part of the tag.  iD doesn't really support it.  We can turn the most popular values into checkbox fields, but that takes up a lot of space in the sidebar and we will never be able to show all of the values that people care about:

```
recycling:cans = yes/no
recycling:clothes = yes/no
recycling:glass = yes/no
recycling:batteries = yes/no
recycling:paper = yes/no
```

Ideally we would have a field that
* allows mappers to add/remove terms
* turns those terms into labelled checkboxes
* takes up little space
* supports localization (this one is a stretch)

If we had this, it would unblock issues like:
#2873, #2872, #2827, #1987

@kepta want to take a shot at this?

**Comment by kepta** [comment]
Sure, let me assign it to myself.

**Comment by bhousel** [comment]
How Wordpress handles this is :ok_hand: 

![multiselect field](https://cloud.githubusercontent.com/assets/38784/13825368/9706cc76-eb88-11e5-9cda-316beb3ea1ec.gif)

**Comment by d1g** [comment]
https://github.com/selectize/selectize.js -  jQuery-based

--plugins=remove_button"

**Comment by kepta** [comment]
[Material chips](https://material.angularjs.org/latest/demo/chips) also look cool to me, but I don't know whether that will blend with iD.

**Comment by kepta** [comment]
This is what current implementation looks like.

![screen shot 2016-03-30 at 10 42 28 pm 2](https://cloud.githubusercontent.com/assets/6966254/14150931/115d6c46-f6c9-11e5-8f76-d73e903f8408.png)

Any suggestions, @bhousel @jfirebaugh ?

**Comment by bhousel** [comment]
That looks awesome!!   Can't wait to merge this in.  Design looks great to me, maybe @samanpwbb has suggestions?

What happens if the tag is `recycling:paper=no` - does it go into the "Accepts" bin.  The field should probably quietly ignore everything except for an explicit `yes` value.

**Comment by bhousel** [comment]
Oh I also just realized from the screenshot - it shouldn't offer to autocomplete `paper` or include in the dropdown list if that value is already selected.

**Comment by samanpwbb** [comment]
This is awesome! Tiny nitpick:
![screen shot 2016-03-30 at 1 52 00 pm](https://cloud.githubusercontent.com/assets/108094/14152017/e8e5c4ce-f67e-11e5-97eb-007277e7bf19.png)

**Comment by kepta** [comment]
@samanpwbb , wow, you have an eye for details. I will try to fix the alignment and add round corners.

@bhousel, I guess I need to update the combobox data and remove the used tokens.

**Comment by bhousel** [comment]
merged!  #3055 -> #3080

**Comment by TheAdventurer64** [comment]
Similar to what @bhousel said, shouldn't mappers have a way to say something like `payment:credit_cards=no`?

**Comment by quincylvania** [comment]
@TheAdventurer64 See #7035.
