### ISSUE TITLE
Unsaved changes are lost if window is closed before "restore" or "reset" is selected

### ISSUE THREAD

**Issue by gmaclennan** [openstreetmap/iD#3036]
I have seen several users be bitten by this. Steps to replicate:

1. Add data to iD without saving.
2. Close the window, ignoring warning there are unsaved changes.
3. Re-open the window --> Unsaved changes: "restore" or "reset" is shown.
4. Close the window without selecting either "restore" or "reset" - no warning is shown.
5. Re-open the window, unsaved changes are lost.

This behavior is unexpected for many users, and means that large pieces of work can be lost accidentally.

**Comment by SHARCRASH** [comment]
Good to know, thanks! I have restored edits in the wait of retrieval at the moment, can't save them because of another bug.
