### ISSUE TITLE
"Track" is now "Unmaintained Track Road" - but highway=track is including also maintained track roads

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#3038]
Reply to https://www.transifex.com/ideditor/id-editor/announcements/5464/

This change is not going to reduce confusion caused by fact that unfortunately highway=track is supposed to be used for all kinds of forestry/agriculture roads - including also maintained, high quality asphalt roads.

**Comment by bgirardot** [comment]
I wonder if "Farm/Forestry Road" or "Farm/Forestry Track" might be more clear. That is how I typically use it.

One of the main considerations is how far the labels for the buttons in iD diverge from the underlying osm tag values. For new mappers, osm road tagging is quite challenging (even for some more experienced mappers) so things that make it more clear to newer mappers what button to push to tag a road is good. More experienced mappers can probably adjust pretty easily to the slight difference between the button label and the underlying tag.

But another consideration is existing training material that mentions 'track' and not having 'track' show up on the button.

 "Farm/Forestry Track" I think it makes a good compromise.

Unmaintained in the label is also slightly confusing because tracks often are maintained in some fashion.

**Comment by bhousel** [comment]
Yeah I'm ok with that.

I'd rather see paved logging roads tagged as `highway=service` than residential dirt roads tagged as `highway=track`.

Feel free to discuss on the tagging mailing list, but I'm not changing the label again for a while.

**Comment by Nakaner** [comment]
Is [this](http://forum.openstreetmap.org/viewtopic.php?id=53953) discussion a qualified discussion from your point of view or has Tagging mailing list to be bothered with this topic?

**Comment by bhousel** [comment]
> Is this discussion a qualified discussion from your point of view or has Tagging mailing list to be bothered with this topic?

I'm not sure what you mean.  It is kind of difficult for me to follow the discussion on the German OSM forum.

I'm still taking the position that `highway=track` is for "any road where it is irresponsible to make assumptions about whether a sedan can be safely routed along it".  Unfortunately that phrase is too long to fit into a small box, so in English we are using the (admittedly imperfect) phrase "Unmaintained Track Road".   If Germans want to translate that to "Feldweg / Waldweg" that's fine with me - I don't think anybody expects every string in iD to be translated literally.

You can start a discussion on the tagging list if you want. I don't think it will be a bother for them, but I also don't think that it will "fix" the tag either.

**Comment by matkoniecz** [comment]
> I'm still taking the position that highway=track is for "any road where it is irresponsible to make assumptions about whether a sedan can be safely routed along it"

It may work in Europe, maybe also in USA - but it is really poor definition for regions like Siberia, Africa and other.

**Comment by bhousel** [comment]
> It may work in Europe, maybe also in USA - but it is really poor definition for regions like Siberia, Africa and other.

Why?  I would think it's a _better_ definition in those places.

**Comment by matkoniecz** [comment]
For example significant part of Kolyma Highwa is certainly "road where it is irresponsible to make assumptions about whether a sedan can be safely routed along it" - and it is not highway=track, it is correctly tagged as highway=trunk.

http://www.openstreetmap.org/way/360716708#map=5/60.930/138.032

![images duckduckgo com](https://cloud.githubusercontent.com/assets/899988/14927409/eeb39990-0e51-11e6-9e78-321f92d32b3f.jpeg)

https://www.openstreetmap.org/way/331381969#map=17/13.61762/13.26637 is another example of road that is mnot sedan friendly and clearly is not a track.

**Comment by matkoniecz** [comment]
In general - in Africa, Asia, interior of Astralia has significant amount of roads of quality that makes them unpassable by sedan what is not changing that these roads should not be mapped as highway=track.

**Comment by bhousel** [comment]
@matkoniecz Please stop trolling me.
