### ISSUE TITLE
Improve public_transport tagging

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#3041]
_highway=platform_ was obsoleted in 2011 (see http://wiki.openstreetmap.org/wiki/Tag:highway%3Dplatform ), but the ID editor still suggests it when adding a highway.
I suggest we keep the interface as it is, but change the tag added to public_transport=platform instead.

More details on the available option in http://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop .

**Comment by d1g** [comment]
Not just public_transport=platform, but all 3-4 tags from vastly approved proposal: http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Stop

IMO iD should treat older highway=platform/bus_stop/random tags as secondary.and public_transport=* family as primary.

Problem with highway=platform/bus_stop is that they are directly contradict [a highway=* tag definition: importance of road in a highway graph](https://wiki.openstreetmap.org/wiki/Proposed_features/Highway_key_voting_importance).

Relevant discussion: https://github.com/gravitystorm/openstreetmap-carto/issues/435#issuecomment-199094591

**Comment by bhousel** [comment]
I'm confused by this issue.. iD does not have a preset for `highway=platform`.

We do have one preset for `railway=platform` and one for `public_transport=platform`.

**Comment by d1g** [comment]
There separate paragraph you can use to quick search: http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Compatibility_with_well_known_tags - it says about following mapping:

No 1 railway case
railway=platform <-> public_transport=platform

trivial info: transportation mode (bus=yes, tram=yes) is omitted because nobody would use buses/trams in railways

No 2 highway case: is slightly more complex (see first 2 lines in table)

**Comment by bhousel** [comment]
@afmenez, @d1g, thanks for pointing me at the documentation for the `public_transport` tag. I'm ok with adding some of the new tags alongside the existing tags where it makes sense to do so, and adjusting the preset descriptions if it can help reduce mapper confusion, but I don't think it makes sense to remove any of the existing tags that are in widespread use.

I'll leave this issue open for now and let's try to make a list of actionable steps to improve the presets.

**Comment by afmenez** [comment]
Would it be possible to use a new platform template and automatically add the new tags whenever a highway=platform or railway=platform is edited or inserted?

**Comment by bhousel** [comment]
> Would it be possible to use a new platform template and automatically add the new tags whenever a highway=platform or railway=platform is edited or inserted?

"Inserted" - generally yes we could add the new tags when the user adds a new feature, but we wouldn't be able to build in any special logic about e.g. whether a bus stop is on the road or next to the road.

"Edited" - no, the osm community would not support iD silently upgrading tags of existing features.

**Comment by bhousel** [comment]
cc @JamesKingdom - want to look into this?  It might work like the recent `healthcare` tagging improvements.
