### ISSUE TITLE
shop=nutrition_supplements

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#3043]
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dnutrition_supplements
http://wiki.openstreetmap.org/wiki/File:Nutrition_supplements.svg
http://wiki.openstreetmap.org/w/index.php?title=Proposed_features/nutrition_supplements&oldid=1229431

**Comment by pnorman** [comment]
Only [132 uses](http://taginfo.openstreetmap.org/tags/?key=shop&value=nutrition_supplements)

**Comment by d1g** [comment]
@pnorman I would say these shops have a 250-1.5K convenience shops :1 nutrition_supplements ratio IRL. And you probably wouldn't find these shops in low populated cities/undeveloped areas.

Yellow pages in my locality lists ~30K items but only **11** nutrition_supplements shops.

**Comment by d1g** [comment]
On the other hand, this tag 
* only in English language at wiki and 
* a 6-7 month old tag? most items in Europe were created just 3-4 months ago
* was  never visible in presets
* only English-speaking Taginfo users know it's presence in OSM and other users who have been pointed to this tag individually via diverse communication channels (at least 3 objects were tagged after my recommendation)

**Comment by bhousel** [comment]
I think it's a good tag.   It obviously corresponds to a real kind of a store that people want to map.  And including all the various alternate tags like `shop=[supplements|nutrition|vitamin|vitamins]` it adds up to almost 500 uses.

It's better to establish the tag now than to encourage more tag fragmentation or mistagging while waiting for OSM to decide about something.  Going forward, "reasonableness" should be the deciding factor for adding a preset - not whether it is "approved" or frequently used or has a wiki page (All of those things are still super important, but they are red herrings that fail us sometimes).  see also: #2943
