### ISSUE TITLE
crossing=* was incorrect in presets (crossing / crossing_ref)

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#3049]
Original usage in 2008: http://wiki.openstreetmap.org/wiki/Approved_features/Road_crossings 

crossing=uncontrolled for crossings without lights
crossing=traffic_signals when there lights

crossing_ref=* should be used to denote all pelicans, toucans and pegasus crossings. For 80%+ crossings of the world crossing_ref should be zebra.

**Comment by bhousel** [comment]
Discussed on #2918.  I'm not planning to change this anytime soon as there is no better alternative at this time.  `crossing=zebra` is currently the 3rd most popular value for crossing.  Until the OSM community comes up with a plan for retagging these, lets leave them be.

**Comment by d1g** [comment]
>  is currently the 3rd most popular value for crossing

Only because it was entered after incorrect usage of this tag it iD presets?!

> Until the OSM community comes up with a plan for retagging these

It was decided in 2008, why community have to re-decide again if some OSM editor or mass import handled this tag in the wrong way?

**Comment by d1g** [comment]
@bhousel, so what does crossing=zebra means? Because I don't see it if was ever defined by anyone:

1. A node on highway (for cars)?
2. A node on highway (for pedestrians)?
