### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3051]
I'm adding a code of conduct for this project.   Basically, be nice to one another.

I realize that I have fallen short of this goal myself sometimes, and I apologize for that.  I'm resolving to do a better job of keeping this project a friendly place where anyone can feel comfortable contributing.  

When I fall short of this goal, please call me out on it.

Thanks!

**Comment by d1g** [comment]
> I realize that I have fallen short of this goal myself sometimes, and I apologize for that. I'm resolving to do a better job of keeping this project a friendly place where anyone can feel comfortable contributing.

Yeah, sorry that I have to _timely_ respond to some of your statements/claims yesterday, but it's never good idea to start an off-topic. (for readers: mostly off-topic to an iD editor and they were removed). Namely you used mix of https://en.wikipedia.org/wiki/Argument_from_authority or https://en.wikipedia.org/wiki/Appeal_to_accomplishment in it's weak form as an argument.

And it is also easy to claim biased statements so painfully hard to defend against them.

Sometimes it literally takes hours to quote all agreements and provide proper stats and explain how one person is incorrect or to explain how one person presumptions/assumptions are untrue.

Some people like to refer to a [Paul Graham pyramid](https://commons.wikimedia.org/wiki/File:Graham's_Hierarchy_of_Disagreement.svg) or  http://www.paulgraham.com/disagree.html

And sometimes people talk [ridiculous statements](https://en.wikipedia.org/wiki/Hyperbole) just to show how your argumentation is flawed and _for not sake of trolling_. 

And yes we are still humans and not telepaths. it gets only worse if these discussions were spread across OSM, without people knowing each other motivation.

Bad thing is that our documentation is spread across regions and sometimes was never represented at wiki (or in any single place) in the first place. So simply by judging at top world-wide tags or top local performers you may ignore other communities with better tagging/modeling schemes that were never utilized globally.

Yeah, any maintainer of "main and simple editor of osm.org" will be bombarded with questions, not less, sometimes this isn't funny role to play.

Also, database only tells you what is tagged but not _why_ it was tagged this way and not another (local laws, defaults, local agreements)

**Comment by d1g** [comment]
For example: 

> This is simply not true. The values in the database are what they are, and they have been that way since long before iD came around.

I don't think I would perform a A-B database compaction simply when it is possible to observe crossing=zebra entered only/mainly by iD and Poltach users:
http://overpass-turbo.eu/s/fgw

http://www.openstreetmap.org/node/663152195/history - 1 year, iD
http://www.openstreetmap.org/node/2921681350/history
http://www.openstreetmap.org/node/2921681377/history - 2 year, iD
http://www.openstreetmap.org/node/2910942323/history
http://www.openstreetmap.org/node/3002264972/history
http://www.openstreetmap.org/node/1601879227/history
http://www.openstreetmap.org/node/2921681337/history
http://www.openstreetmap.org/node/248044050/history - 6 months, iD
http://www.openstreetmap.org/node/259237395/history - 6 year old node had proper tags until 8 months ago
http://www.openstreetmap.org/node/580982941/history - 6 year old node with incorrect tags, Potlatch


In local laws, there no term "zebra" but:
- "пешеходный переход"
- "регулируемый пешеходный переход"
- "нерегулируемый пешеходный переход"

https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%88%D0%B5%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9_%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4

Also, according to [4.3](https://ru.wikisource.org/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0_%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D0%BD%D0%BE%D0%B3%D0%BE_%D0%B4%D0%B2%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%BE%D0%B9_%D0%A4%D0%B5%D0%B4%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8#4._.D0.9E.D0.B1.D1.8F.D0.B7.D0.B0.D0.BD.D0.BD.D0.BE.D1.81.D1.82.D0.B8_.D0.BF.D0.B5.D1.88.D0.B5.D1.85.D0.BE.D0.B4.D0.BE.D0.B2)

We allowed to cross a road EVERYWHERE (if a road is observable in both ways) if there no real crossing. Thus, you have/see crossing=unmarked only in Russian db.

Duck tagging won't help you to write a good software.
Duck tagging won't help you to tag properly in database.

Only with documentation you may get results in OSM, not within single community, but globally.
