### ISSUE TITLE
Lines around background imagery tiles

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#3053]
#1976 was about this issue when zoomed in/out, but it now happens when at 100% zoom.

![image](https://cloud.githubusercontent.com/assets/1190866/14198679/db872dc2-f791-11e5-9765-403d5d0ecc62.png)

Browser is 49.0.2623.110 (Official Build) m (64-bit) on Windows 8.1.

I'm not yet sure if this is is a regression in iD or a Chrome change.

**Comment by bhousel** [comment]
Yes, this is a regression related to #2849 

The seams between tiles could happen before but it was very unlikely because of the image dimensions being rounded to whole pixels.  But now it happens a lot more visibly.

I can close the seams by scaling up the image tiles very slightly.
