### ISSUE TITLE
ends of longer tags cut off making it impossible to distinguish

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#3054]
https://trac.openstreetmap.org/attachment/ticket/5394/ydg.jpg is a picture that proves that nobody can see the ends of the longer names of tags.

**Comment by bhousel** [comment]
I don't know if there is much we can do about this.. I think browsers do show the full text as a tooltip if you hover long enough on a value.

**Comment by jidanni** [comment]
Chromium doesn't. Anyway, you need to allow one to pull the sidebar
right, so the sidebar gets wider (and the map gets narrower.) or something.

**Comment by bhousel** [comment]
Ok, we can add the [`title` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) to any field so that long values will be visible when hovering.

**Comment by jidanni** [comment]
Good.
