### ISSUE TITLE
Conflict resolution at save time is slow

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3056]
1. We can probably restructure this code to try an optimistic save first and only enter the conflict resolution loop after the server returns 409 Conflict.
   - [x] try fast save before entering conflict resolution loop
2. Part of the slowness is [checking for modifications of related things](https://github.com/openstreetmap/iD/blob/master/js/id/modes/save.js#L72). So if a user modifies big multipolygon, we need to check the multipolygon members for conflicts too. 
   - [x] :warning: That code needs to handle circular relations, probably by adding the `loadMore` things to the `toCheck` array so they don't get refetched ad infinitum.
   - [x] A progress bar or updating the message with some kind of "Conflict Checking 1/50" message would help here.

**Comment by jjiglesiasg** [comment]
I recently have a warning for 3090 conflicts, that ID try to keep resolving but not solution ever came out, so I need to discard all my edits otherwise ID dosent work. How I could solve this if happen again?

**Comment by bhousel** [comment]
> I recently have a warning for 3090 conflicts, that ID try to keep resolving but not solution ever came out, so I need to discard all my edits otherwise ID dosent work. How I could solve this if happen again? Is anoying to loose so much data

I honestly didn't think it could go up that high.  Can you share more info about what kind of editing were you doing?   

I really can't give much guidance other than to just save frequently, especially if you think other users might also be editing in the same area.
