### ISSUE TITLE
add preset for route=horse relations

### ISSUE THREAD

**Issue by Hufkratzer** [openstreetmap/iD#3057]
Please add a preset for route=horse relations (Riding Routes = Reitrouten),
analogous to route=hiking (closed/merged issue https://github.com/openstreetmap/iD/pull/1785)-
The only difference seems to be that you need a new icon.
There are also different network values (ihn, nhn, rhn and lhn) 
but this does not seem to be interesting to iD.

(Riding Routes were recently also added to JOSM,
see https://josm.openstreetmap.de/changeset/10086/josm
and https://josm.openstreetmap.de/changeset/10090/josm)

**Comment by bhousel** [comment]
This was added in #3066

**Comment by Hufkratzer** [comment]
Thanks.

One question:
If I click on the 'i' right to "Riding Route" I only get the message 
![nodoc](https://cloud.githubusercontent.com/assets/5958184/15867622/6b244492-2ce4-11e6-88e7-c22e4568ae0e.jpg)

(The same happens with other route types (e.g. hiking, cycle).

What has to be done to let iD show some documentation or/and a link to the wiki page
(for Riding this would be http://wiki.openstreetmap.org/wiki/Tag:route=horse)?
