### ISSUE TITLE
Error in the diff3_merge module while trying to merge remote changes

### ISSUE THREAD

**Issue by deepbasu007** [openstreetmap/iD#3058]
For certain values of nodes and ways, the diff3_merge module fails to merge the remote changes correctly, even when there is no conflict.

Here's an example where issues occur:

a = ["n4100522632", "n4100697091", "n4100697136", "n-10000", "n4102671583", "n4102671584", "n4102671585", "n4102671586", "n4102671587", "n4102671588", "n4102677889", "n4102677890", "n4094374176"]

o = ["n4100522632", "n4100697091", "n4100697136", "n4102671583", "n4102671584", "n4102671585", "n4102671586", "n4102671587", "n4102671588", "n4102677889", "n4102677890", "n4094374176"]

b = ["n4100522632", "n4100697091", "n4100697136", "n4102671583", "n4102671584", "n4102671585", "n4102671586", "n4102671587", "n4102671588", "n4102677889", "n4105613618", "n4102677890", "n4105613617", "n4094374176"]

merged result from diff3_merge
= ["n4100522632", "n4100697091", "n4100697136", "n4102671583", "n4102671584", "n4102671585", "n4102671586", "n4102671587", "n4102671588", "n4102677889", "n4105613618", "n4102677890", "n4102671583", "n4102671584", "n4102671585", "n4102671586", "n4102671587", "n4102671588", "n4102677889", "n4102677890", "n4094374176"]

GNU diff3 result
= ["n4100522632", "n4100697091", "n4100697136", "n-10000", "n4102671583", "n4102671584", "n4102671585", "n4102671586", "n4102671587", "n4102671588", "n4102677889", "n4105613618", "n4102677890", "n4105613617", "n4094374176"]

As can be seen, the GNU diff3 result is as expected. However, the Diff3.diff3_merge fails to merge and creates ambiguities. Any clues as to what's happening here or how to fix it? Here's a screenshot of the artifacts this creates.
<img width="1052" alt="screen shot 2016-04-10 at 11 28 53 pm" src="https://cloud.githubusercontent.com/assets/3278006/14416246/b85dbff0-ff75-11e5-9151-c6c9abe8a43d.png">

**Comment by bhousel** [comment]
Discussion and possible fix here.. https://github.com/langram/node-diff3/issues/3
Thanks @deepbasu007 for finding this!
