### ISSUE TITLE
Setting "Gas station" removes building tag

### ISSUE THREAD

**Issue by maraf24** [openstreetmap/iD#3065]
When user adds to existing building (building=yes) gas station (amenity=fuel), the building tag is silenty being removed. That should never happen.

**Comment by bhousel** [comment]
Hi @maraf24 this is a common source of OSM confusion. (see #2857)

`amenity=fuel` is for the area around the gas station.  You can create a separate `building=yes` or `building=roof` for the convenience store, or the roof over the filling area, or other structures on that property.

See the [osm wiki page for `amenity=fuel`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel) for details about tagging recommendation.

iD tries to help here by rendering buildings and structures consistently (they are all red) and differently from other area features.  So removing the building tag isn't "silent" - it changes very much the appearance of the feature.

**Comment by maraf24** [comment]
This issue is not about incorrect mapping practice, but damaging valid data by an editor. 
If amenity=fuel is for area around gas station, why someone is trying to apply it to a building? Either this is an error, so iD should give a warning or just ask for confirmation. Or this is just what mapper wants. Yes, sometimes people add amenity=fuel to buildings. Especially if gas station is covered (building=roof). This really happens. And in that case this tag should remain.

The wiki doesn't say this tag shouldn't be applied to buildings. And this option name in iD is just "Gas Station", not "Gas Station Area". 

I don't use iD. I do QA of beginners' work. I just noticed object with source:building without building tag and traced it to iD. The mapper was unaware about damage.

The same problem is with amenity=school - this is not "School Grounds", because some schools have not grounds, just one building. And it is completely correct to add amenity=school to a building.
amenity=hospital - the same. Small hospitals sometimes don't have grounds, just a building.

Surprisingly amenity=police preserves building tag. So it can be done :)
