### ISSUE TITLE
Let user "play" in walkthrough

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3067]
Rather than finishing the walkthrough and rushing the user back to editing, the last step of walkthrough should:
1. Remove the `d3.curtain`
2. Add an "Exit Tutorial" button, and say something like "When you are ready to leave the tutorial, press this button"
3. Let the user play with the tutorial map as much as they want to.

Maybe even better would be to let the user play around at the end of each chapter and prompt them to "Click to advance to the next step when you are ready".

**Comment by pnorman** [comment]
My one concern is that a user ends up mapping in tutorial mode and loses their work

**Comment by bhousel** [comment]
> My one concern is that a user ends up mapping in tutorial mode and loses their work

Yes that a valid concern - we'd want to make the "Finish" button really obvious.  Not the sort of thing that a user would miss.

**Comment by 1ec5** [comment]
Maybe make the Finish button grow increasingly prominent as the user edits things, similar to what happens in real editing.

**Comment by bhousel** [comment]
Cool @1ec5, I did something sort of like that... 

Currently it works like: 
* Each chapter ends in a "free play" step
* The instruction tells the user that when they are ready to continue, they should click the button for the next chapter
* User clicks "OK" and the curtain goes away, so the user can do whatever they want
* The next chapter button pulses a little, so the user remembers to click it

You can try it out in the runnabot container! 🐻
https://github.com/openstreetmap/iD/pull/3921#issuecomment-288535643
(runnabot automatically updates the container every time I push to that branch on the PR)

![practice](https://cloud.githubusercontent.com/assets/38784/24573108/034e4b3a-164d-11e7-9f93-836ae56b475f.gif)
