### ISSUE TITLE
[Feature request] Merge area

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#3074]
Can you add a tool to merge 2 area (or more) with a ctrl+click to select and then just check:
- if there is, at least 2 poins in common (to be able to create a new area)
- if there is no conflict of tags, if there is a conflict, a "alert box" can be show with a highlight of difference, then the user can select which one to hold

**Comment by bhousel** [comment]
Yes, I really want to add this.. It's a long standing issue tracked on #435 
Ideally I want to use turf-union for this once https://github.com/Turfjs/turf/issues/88 lands.
