### ISSUE TITLE
provide a link for website= like wikipedia

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3075]
the `wikipedia` tag has a link to check the article. It would be nice if the same logic would be available for the `website` tag.

**Comment by bhousel** [comment]
I don't think it's a good idea to link to untrusted resources.   A malicious mapper could put anything in the `website=` tag, and trick unsuspecting users into visiting that link.

**Comment by HolgerJeromin** [comment]
Every website tag is transformed to a link on osm.org. Yes, a malicious mapper could put anything in the tag and all casual users can visit that link.
But Mappers using iD are IMO no unsuspecting users but people who want to check if the url is valid for this OSM poi.

**Comment by bhousel** [comment]
> Every website tag is transformed to a link on osm.org.

I'm not totally sure that's a good idea either..
