### ISSUE TITLE
When reversing a line, reverse tags on nodes

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#3076]
If someone reverse a line (because he want or make a mistake), all the direction become false. The it would be good if, in iD, when someone reverse a line the direction change to math the previous (or open a box to ask if it need to be done). This need to be reverse too:
backward <> forward
left <> right

**Comment by bhousel** [comment]
iD already does this.

**Comment by homersimpsons** [comment]
Sorry, misunderstanding, it's about POI on the road like stop sign.

**Comment by homersimpsons** [comment]
Thank you :) that wasn't too explicit in fact.

**Comment by bhousel** [comment]
Ok, that makes sense, although I don't think any of the other editors do this. 

The stop sign example is a good one.  I'm wondering if reversing the tags on child nodes would break any of the commonly used tags, but I can't think of any issues.

cc @pnorman

**Comment by pnorman** [comment]
I had to check taginfo, but the direction=forward/backward taghas about 35k uses. It's not the clearest data model, as a node can be a child of multiple ways.

**Comment by stephan75** [comment]
Maybe see http://wiki.openstreetmap.org/wiki/Forward_%26_backward,_left_%26_right as a kind of reference?

But as far as I have seen there is no mention of stop signs as node with direction=forward or =backward ... maybe wiki page needs updating?

**Comment by homersimpsons** [comment]
@stephan75 have a look to [stop on wiki](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dstop )

**Comment by bhousel** [comment]
or http://wiki.openstreetmap.org/wiki/Key:traffic_sign#As_part_of_a_way
(279k nodes mapped currently)

**Comment by bhousel** [comment]
closed by #3376, thanks @Psigio!
