### ISSUE TITLE
textinput field are too greedy with autocompletion

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3077]
I found this problem problem with the raw tag editor and the changeset comment dialog:

For example we have a `shop` entry and want to [prefix](http://wiki.openstreetmap.org/wiki/Lifecycle_prefix) it with `disused:`
I focus the cursor at start of the shop field and start typing:
First key (d) works, i have `dshop` but the second char kills the output with replacing the full text with 
`diameter_crown` while `ameter_crown` is marked. My old value shop is lost.

I often have this problem with the changeset comment dialog which replaces the current value, too.

My browser is the latest chrome

**Comment by bhousel** [comment]
Yeah I was noticing this too.. I think it might be a recent regression.  I'll try to improve this..
