### ISSUE TITLE
phone number placeholder text confusing in United States

### ISSUE THREAD

**Issue by dobratzp** [openstreetmap/iD#3083]
I'm looking at phone numbers in OSM in the United States and and seeing some users incorrectly entering phone numbers starting with `+01`.  The placeholder text is `+31 42 123 4567`, which doesn't really look like an [NANP](https://en.wikipedia.org/wiki/North_American_Numbering_Plan) phone number.  The [preferred form of a phone number in the United States](http://wiki.openstreetmap.org/wiki/Key:phone) is `+1-503-555-6789`.

**Comment by bhousel** [comment]
This was done, see #3084
