### ISSUE TITLE
Draw a square building in walkthrough

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#3085]
Drawing buildings is a common task, and buildings are frequently square. This could be a worthwhile addition to the walkthrough.

**Comment by bhousel** [comment]
Yes, I mentioned this in #2699, which adds a special mode for drawing orthogonal things.  I'm going to pick it back up and see if I can land that PR soon-ish.  I agree we need to do a better job of showing users how to draw buildings.
