### ISSUE TITLE
Is it possible to restore latitude and longitude to iD?

### ISSUE THREAD

**Issue by techlady** [openstreetmap/iD#3088]
I do a lot of mapping in rural areas, especially national parks and forests. Often, I have only coordinates for a POI. To place them correctly, I have to first place them on a map that includes coordinates (I use Maptech), then manually put a point at the same location. 
Aren't coordinates pretty basic in mapping?

**Comment by pnorman** [comment]
The functionality you're after is creating a POI without needing to place on a map with coordinates - where are your coordinates coming from? GPS trace, hand-written notes, etc?

**Comment by bhousel** [comment]
We have closed issues like this before in #2583 and #2590 

The risks of entering points numerically include: 
1. enter the numbers wrong and the node will disappear from view.
2. people with consumer GPS units may put too much emphasis on the numbers, which can be fairly inaccurate
3. it allows people to easily create lines that span large sections of the globe.

So, if you really want to work with numeric coordinates, we'd prefer for you to:
1. use an advanced tool like JOSM, or
2. enter the coordinates in the url hash, then place a point manually (as @kepta suggested on the other ticket), or
3. enter the coordinates in iD's search field, (it accepts lat/lng or sexagesimal), click on the result to go there, then place a point manually

**Comment by techlady** [comment]
Many sources. Most of them comes from 
visits to various sites. But does that matter?


At 05:15 PM 4/25/2016, you wrote:

>The functionality you're after is creating a POI 
>without needing to place on a map with 
>coordinates - where are your coordinates coming 
>from? GPS trace, hand-written notes, etc?
>
>­
>You are receiving this because you authored the thread.
>Reply to this email directly or 
><https://github.com/openstreetmap/iD/issues/3088#issuecomment-214569679>view 
>it on GitHub

Charlotte Wolter
927 18th Street Suite A
Santa Monica, California
90403
+1-310-597-4040
techlady@techlady.com
Skype: thetechlady

**Comment by jidanni** [comment]
> 2. enter the coordinates in the url hash, then place a point manually (as @kepta suggested on the other ticket), or
> 3. enter the coordinates in iD's search field, (it accepts lat/lng or sexagesimal), click on the result to go there, then place a point manually

But these just move the screen to the center. One still cannot guess where the exact point is.

OK I'll try to hack together a share with marker URL... which is maybe what you are talking about in 2, but I can't find it.

**Comment by jidanni** [comment]
In fact even if one uses
```
#!/bin/sh
set -eu
lat=$1 lon=$2
$BROWSER "https://www.openstreetmap.org/?mlat=$lat&mlon=$lon#map=19/$lat/$lon"
```
the problem happens when clicking Edit. The marker of course disappears.

One might think "As there is no way to tell where the center of the screen in, just put the marker in some corner, and then click Edit." But that doesn't work either. The corners on osm.org do not correspond to the corners of iD,

**Comment by jidanni** [comment]
OK, one probably should place the object on the map at the best guess spot. Then use the above shell script to see how close we got, then go back and adjust with second and third edits, etc. Frustrating.

**Comment by jidanni** [comment]
In fact all this trouble could be eliminated if the search box put a little marker like Google maps does when one searches for something.

**Comment by jidanni** [comment]
A little crosshairs, or a bouncing marker, so one doesn't mistake it for map data.

**Comment by jidanni** [comment]
I think OSM should have a special requests desk.
My special request for today is somebody place a point on the map,
(that I can then edit.)
I need the point placed at the exact coordinates of
https://commons.wikimedia.org/wiki/File:P_20190716_085105_vHDR_On.jpg
As you can see it is in the middle of a forest and thus not easy to see on an air imagery.

**Comment by tastrax** [comment]
I note that you have asked for this feature multiple times. This seems to be really important to you so can I suggest you try JOSM editor? Different editors have different abilities and personally I use the best editor for a particular task. No harm in learning different approaches.

https://help.openstreetmap.org/questions/864/how-to-add-node-with-exact-coordinates-in-josm

**Comment by jidanni** [comment]
(Yes @tastrax, but last time I tried that it [messed up my whole left right coordination skills for a whole month](https://help.openstreetmap.org/questions/28637/how-to-repurpose-mouse-buttons-in-josm). Perhaps worse than switching to a left/(right) side driving country.)

**Comment by bhousel** [comment]
@tastrax Please don’t feed the trolls. We have told him to use JOSM many times over the years.  He just keeps coming back to harass us.  I have his comments blocked and don’t see them unless somebody replies. :disappointed:

**Comment by jidanni** [comment]
Ah, no wonder he didn't see the results I posted above of the test of:

> 2. enter the coordinates in the url hash, then place a point manually (as @kepta suggested on the other ticket), or
> 3. enter the coordinates in iD's search field, (it accepts lat/lng or sexagesimal), click on the result to go there, then place a point manually

**Comment by macias** [comment]
> We have closed issues like this before in #2583 and #2590

This is unfortunate, because knowing and using coordinates in the mapping tool, at least IMHO, is fundamental.

> The risks of entering points numerically include:
> 
>     1. enter the numbers wrong and the node will disappear from view.

Countermeasure: checking against window boundaries

>     2. people with consumer GPS units may put too much emphasis on the numbers, which can be fairly inaccurate

So when person enters a number, that number 100% comes from consumer GPS, but when the GPS track is imported it comes where exactly from?

>     3. it allows people to easily create lines that span large sections of the globe.

I can easily do the same while importing the GPS track.
 
>     1. use an advanced tool like JOSM, or

This is not helpful at all.

>     2. enter the coordinates in the url hash, then place a point manually (as @kepta suggested on the other ticket), or

Seriously, the editor is for people, or for hackers?

>     3. enter the coordinates in iD's search field, (it accepts lat/lng or sexagesimal), click on the result to go there,

Ok, I did it, I see quite a big area and...

> then place a point manually

...where should I put it exactly?

Ok, back to the basics -- the purpose of any tool, not only program, is actually help people do their job. Better, more efficiently, easier, etc etc. So I don't understand this outcome, mapping tool disallowing using coordinates in a friendly fashion, because provided point could be outside of current window...? Disallowing this feature in iD editor makes life for others harder than it could be.

**Comment by jidanni** [comment]
A workaround would be: creating the object, exporting it to an .osc file, editing the file to change the coordinates, and then importing it back in. This last step awaits #7109.

**Comment by 1ec5** [comment]
I know you’re tired of me saying this, but [Level0](http://level0.osmz.ru/) supports uploading .osc and .osm files – and it also supports editing the coordinates directly as well. 🙂

**Comment by macias** [comment]
@jidanni , @1ec5 The scenario for me is -- I have coordinates at hand, I would like to search them (already implemented), on map shows up temporary indicator (no such feature), so I could click "add to map" (no such feature). From the user perspective dead simple.

Importing files are present in OSM, and then they can be used for edits in iD but this exactly what I would like to avoid in scenarios when I have literally one point to add.

I don't know Level0 but it is not even capable of searching coordinates, I input mine, page refreshes and it puts back the defaults. But this is just remark, let's not solve feature set by switching tools, unless alternative tool covers all the features of the original one.

**Comment by jidanni** [comment]
Indeed, I had to use level 0, or Vespucci, to put a international treaty boundary Turning Point into the bottom of a deep river! The only way to know where that is, is reading the coordinates from the treaty signed by the two parties. 

Better "ground truth" then most borders in rivers seen on Open Street Map.
