### ISSUE TITLE
I want to access Map Notes within iD

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3090]
My work flow is:
- switching on Map Notes
- finding a Note I can close
- switching to Edit mode (with iD Editor)
- editing
- saving
- switching back to "Normal Mode"
- switching on Map Notes
- closing Note

I would prefer the following loop:
- Note reading
- editing
- saving
- Note closing

**Comment by tyrasd** [comment]
Duplicate of #2629
