### ISSUE TITLE
name tag only on nodes

### ISSUE THREAD

**Issue by cliffordsnow** [openstreetmap/iD#3091]
A user can add a point with only a name= tag. iD should not allow saving of a point with only a name tag. 

Currently if a user adds a point, the last feature shown in the list is Point. When selected the user is given a text box to name the point. Additional tags can be added but I'm seeing users only add the name tag.

Example of a name only tag http://www.openstreetmap.org/node/4080838264

(The user has been contacted to fix.)

**Comment by bhousel** [comment]
That's a good point.. We have a validation to warn users if they have left a feature untagged, but this check should exclude the `name` tag.
