### ISSUE TITLE
Deleting relations on a way should immediately make way deletable

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/iD#3094]
After clicking on a way that has a relation on, the circle of actions around it has the delete (wastebin) icon grayed out, because the relation is present and has to be deleted first.

If the relation is then deleted, the delete icon stays grayed out, rather than then becoming available.

Re-selecting the way does make the delete icon available.

So there needs to be a listener which enables the delete button as soon as no relations are attached, rather than requiring a re-click.

**Comment by quincylvania** [comment]
This was fixed somewhere along the line since 2016.
