### ISSUE TITLE
Unclassified roads and tracks need to be different colors

### ISSUE THREAD

**Issue by techlady** [openstreetmap/iD#3095]
Unclassified roads and tracks both are drawn with very pale colors, almost white. This makes it very difficult to see them against the aerial photography when drawing in an area with pale soil or covered with snow. Some kind of color would make drawing much easier.
I'm also not wild about the new rendering colors. I prefer red for primary roads, orange for secondary and yellow for tertiary. That color scheme made sense. The current one is odd and often makes it difficult to tell the difference between roads.

**Comment by bhousel** [comment]
Yes, I know it can be frustrating when some of the colors on the map look like the colors on the background imagery.  I think no matter what colors we pick, there will be some large swaths of earth somewhere that look kind of like that color.   The best advice I have is to open the background pane and try darkening the background imagery if bright snow or soil is washing out the osm data layer.

<img width="295" alt="screenshot 2016-05-02 22 49 10" src="https://cloud.githubusercontent.com/assets/38784/14973656/9bd66914-10b8-11e6-80b8-76cb3fb1bd29.png">


I can tell you a secret too.. The legacy OSM colors are still in iD!  🐣 
If you're on http://openstreetmap.org, you can open a developer console and type this to get them back:

```js
frames['id-embed'].contentDocument.getElementById('id-container').classList.add('legacy-carto')
```

If you're on a site like https://openstreetmap.us/iD/master that doesn't have an iframe, the code is like this:
```js
document.getElementById('id-container').classList.add('legacy-carto')
```

The colors are all just CSS, so you could probably even override them using something like the Stylish extension on [Firefox](https://addons.mozilla.org/firefox/addon/stylish/) or [Chrome](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe).

**Comment by bhousel** [comment]
> The colors are all just CSS, so you could probably even override them using something like the Stylish extension on Firefox or Chrome.

^ Just a quick update to this..

I was curious to learn more about the Stylish browser extension - so I tried it today and it works great for customizing iD's css.  

Step 1.  Install the Stylish browser extension
Step 2.  Visit openstreetmap.org, click the "Stylish" button and choose "Find styles for this site"
Step 3.  Pick one of the 2 that I have made (or make your own):

https://userstyles.org/styles/128794/modern-id-colors
https://userstyles.org/styles/128803/legacy-id-colors

After you pick a style, you can keep those colors or click the colors to change them:

<img width="600" alt="screenshot 2016-06-09 14 15 05" src="https://cloud.githubusercontent.com/assets/38784/15941235/315197e6-2e4d-11e6-9ae4-0effea8ed809.png">

Step 4.  Click the big green "Install" button.

Now when you visit openstreetmap.org, you'll have the option to override the colors with your custom colors:

![stylish_extension](https://cloud.githubusercontent.com/assets/38784/15941857/f77011bc-2e4f-11e6-9aad-c08d653b7d9a.gif)

**Comment by Nick-Tallguy** [comment]
@techlady  I've created a style for both Firefox & Chrome - follow [the instructions from the link in above comment](https://github.com/openstreetmap/iD/issues/3095#issuecomment-224988925) and install the Stylish extension, visit <http://www.openstreetmap.org> and search - it's called **HOT colour buildings purple** (I'm really good at naming things......!)

I'm in the process of writing a more detailed 'howto' in terms of installation.

The creation / edit process is actually quite simple (thanks @bhousel for doing all the hard work side of this) - if anyone wants other colours or something different, let me know & I'll do my best.

![hot-purple-buildings](https://cloud.githubusercontent.com/assets/6763965/21468174/2bc6876c-c9fe-11e6-9dda-77e89571e93b.png)

**Comment by techlady** [comment]
Thanks Bhousel and Nick-Tallguy,
Stylish is very useful. Nick, I'm going to try your "purple" style as soon as I can.
