### ISSUE TITLE
Save button greyed out despite comment

### ISSUE THREAD

**Issue by scaidermern** [openstreetmap/iD#3096]
Multiple users report that the save button is still greyed out despite having entered a comment:

- [Why can't I save some edits?](https://help.openstreetmap.org/questions/49551/why-cant-i-save-some-edits)
- [Can't save edits in ID, despite comment](https://help.openstreetmap.org/questions/49434/cant-save-edits-in-id-despite-comment)

According to the first linked issue this happend with Chrome 48 on OSX. The second one still lacks more information.

Note: I didn't encounter this issue myself. Please try to investigate it nevertheless since it obviously affects multiple users, certainly more than the two linked above.

**Comment by muesliq** [comment]
I'm the Chrome user who reported this. Let me know if you need more information.

**Comment by artischocke** [comment]
I'm also experiencing this issue (Chrome Version 50.0.2661.94 m on Windows 7). After entering text in the comment text box, the Save button (on the Save Changes left panel) remains disabled. Clicking Cancel and Save (top editor bar) does show the Save changes panel with the Save button enabled. Let me know if you need more info.

**Comment by bhousel** [comment]
Thanks for the reports, I'll investigate this today..
