### ISSUE TITLE
Enable user to quit / exit without saving

### ISSUE THREAD

**Issue by SteveBower** [openstreetmap/iD#3099]
Users, especially new users (e.g. in a mapathon), may decide they want to quit without saving their edits. Currently the user must close the window, open OSM in a new window, and choose not to restore their edits. 'Quit without saving' is a pretty standard editor feature - a user could be confused not finding that option.

Perhaps the concensus will be to keep the UI simple rather than adding (for example) a 'Quit' button, but I'm curious to hear any discussion. I did not find this issue raised in current or previous issues.

**Comment by bhousel** [comment]
> Perhaps the concensus will be to keep the UI simple rather than adding (for example) a 'Quit' button, but I'm curious to hear any discussion.

Keeping the UI simple is my strong preference, but happy to discuss.  If a "Quit" button belongs anywhere, it's probably on the embedding site, see openstreetmap/openstreetmap-website#737

Would letting the user play around more in the walkthrough tutorial be an acceptable solution?  see #3067

**Comment by slhh** [comment]
The save button can be replaced by a quit button if save is not available. The quit button can have different color, shape or position than the save button in order to make active save button more visible.

In addition an "undo all" operation can be bound to the undo button with Ctrl pressed.

This way users can always exit using Ctrl-Undo + Quit.

**Comment by SteveBower** [comment]
@bhousel - Letting the user play around in the walkthrough might help some, but it's still the case that sometimes a user does a bunch of mapping, then realizes it was done wrong (assigned the wrong tags, digitized the wrong features, etc.) and just wants to start over.

I agree, keeping the UI simple is the right goal. I like @slhh 's option of using the 'undo' button, though Ctrl-click on the button would be an unusual UI feature, and might be hard to describe in the UI with minimal text.

Alternatively, maybe add to the 'undo' button rollover text : "Quit without saving: Ctrl-Q" (below "Shortcut: Ctrl-Z"), add a confirmation dialog for Ctrl-Q, and add to the [iD/Shortcuts wiki](http://wiki.openstreetmap.org/wiki/ID/Shortcuts). Extra credit: add the 'undo' and 'quit without saving' options to the end of the walkthrough.

I think 'quit without saving' would be better than just resetting iD, since the user might want to exit iD altogether. But they can always open OSM in a new window, so I think resetting iD would be enough if easier to implement.

**Comment by slhh** [comment]
Because not all data is rendered a quite common usecase seems to be:
Open the editor to add some data, or just to check something; detect that the data is already existing and ok; want to quit.

> I like @slhh 's option of using the 'undo' button, though Ctrl-click on the button would be an unusual UI feature, and might be hard to describe in the UI with minimal text.

Adding "Ctrl+Click:Undo all" to the hoover mode display of the undo button should make it discoverable, and users failing to discover can use the normal undo multiple times.

**Comment by SteveBower** [comment]
@slhh I think Ctrl-Q is a more common method for 'quit', and I don't recall ever seeing a Ctrl-Click used on a UI button to give it a different function. I would stick with the more conventional UI method, if the feature is implemented. With a confirmation dialog to confirm 'quit without saving' - either way.

**Comment by bhousel** [comment]
Sorry but I'm going to close this as I think it's unnecessary.

1. Normal browser shortcuts for closing (Ctrl-Q, Alt-F4, ⌘W) and refreshing the user's tab (F5, ⌘R) still work fine and we shouldn't change those.
2. Showing the "You have unsaved changes - do you want to restore them" message next time the user starts iD is neither burdensome nor confusing.
3. Any special "Quit editing and return to openstreetmap" UI belongs in the embedding site, not in iD.  There is already an issue for improving this on openstreetmap/openstreetmap-website#737
