### ISSUE TITLE
Text is hard to read on Firefox on Linux with dark GTK3 theme

### ISSUE THREAD

**Issue by jonnybarnes** [openstreetmap/iD#3100]
I’m running Firefox on Linux using a dark GTK3 theme. This means without any styling a form input would have white text on a dark background.

This is what trying to edit my local primary school looks like: 
![screenshot from 2016-05-04 18-07-40](https://cloud.githubusercontent.com/assets/108303/15022370/42266218-1223-11e6-8989-2ae32c2b7d3f.png)

**Comment by bhousel** [comment]
This isn't something I'll be able to look at anytime soon, but would welcome a PR that fixes the issue..

**Comment by jonnybarnes** [comment]
Excellent, just out of curiosity, how long do changes normally take to make it onto the website?

**Comment by bhousel** [comment]
@jonnybarnes I've been releasing about once or twice monthly.. We're kind of working on a big refactor now, so it would be a strange time to put out a release, but not impossible.
