### ISSUE TITLE
it's very easy to get somewhere else when zoom in

### ISSUE THREAD

**Issue by zhiqiangZHAO** [openstreetmap/iD#3112]
Hi,

This bug happened on my mac book pro 15 and chrome for several times. It's really annoying. I start from Hayward, CA. When I find a place and want to zoom in to edit, id editor took me to somewhere inside the ocean.

Don't know whether other people encounter the same issue.

**Comment by bhousel** [comment]
Thanks for the report, this is being tracked on #2773
