### ISSUE TITLE
Halo for roads without name tag

### ISSUE THREAD

**Issue by vespax** [openstreetmap/iD#3113]
I would like to suggest a feature within the Background Settings tab.  The default would not to be active but for users applying road names it is difficult to see which road segments do and don't have name tag applied.  The use of this feature may help create more comprehensive road name data.

This feature would display a red halo around roads that do not have a name tag.  I have attached an example from the GoMap!! app showing how it is done there.  We have found this feature to be very useful in the app and would love to see an option in iD that functions in a similar method.

![img_0009](https://cloud.githubusercontent.com/assets/1162711/15298595/50c79510-1b5d-11e6-8a61-fda8d6b27544.PNG)

**Comment by bhousel** [comment]
I'd prefer to keep validation specific styling out of iD and instead push users who are interested in validation towards dedicated QA tools like Osmose or Keepright or similar.

I'm also ok with having people build integrations between QA tools and iD.  This could work similar to our existing Mapillary integration:  checkboxes under the Map Data panel can toggle a data overlay showing users where issues are, and a floating div somewhere with action buttons like "mark as resolved" or "not an issue".

**Comment by vespax** [comment]
I would like to push back on this a little.  This feature could be very useful to users of iD to help identify where better mapping needs to occur in a city.  Also the QA tools typically don’t update in realtime making it awkward to use and less efficient.  Using tools like JOSM is more ‘powerful’ but I’d like to see this possible to average/new OSM users.

If the integration pane similar to Mapillary is a possibility, can you provide where that develop occurs and who integrates that into this repo?  A basic QA toolset in the “Map Data” area would really help improve data overall on a general level.

**Comment by bhousel** [comment]
> If the integration pane similar to Mapillary is a possibility, can you provide where that develop occurs and who integrates that into this repo?

Sure that's a fair question.. Like the Mapillary development, the work will probably be done by a third party that has some useful permissively licensed data that they they want to show up in iD.  I know that somebody is working on a QA integration with iD now and I'd love to get a PR from them and help them integrate it.
