### ISSUE TITLE
Refactor iD into ES6 modules (phase 1)

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3118]
---

Brief ( @tmcw )

- The work to modularize iD is underway and we are welcoming contributors!
- The approach is incremental so that we don't have to freeze iD development.
- We're using ES6 modules and rollup to bundle them.

Step 1 was https://github.com/openstreetmap/iD/pull/3148 and step 2 was https://github.com/openstreetmap/iD/pull/3161 .

We are using ES6 modules because iD's codebase includes many circular dependencies, for instance: `DeleteMultiple -> DeleteWay -> DeleteRelation -> DeleteMultiple`.

**How you can help**: if this feature push is important to you, please invest the time helping us make it real. This is an open source project and relies on its contributors. This is a great opportunity to get involved with OpenStreetMap and learn about this module system by following existing patterns.

**How to help**:

iD is split into multiple directories under [js/id/](https://github.com/openstreetmap/iD/tree/master/js/id):

* [x] actions #3161
* [X] behavior #3178
* [x] core #3174
* [x] geo #3172 
* [x] modes #3169
* [x] operations #3173 
* [x] presets #3168
* [X] renderer #3178
* [x] services #3175
* [x] svg #3177 
* [x] ui *(has PR #3167)*
* [x] util #3166
* [x] validations #3165 

These folders contain components of iD that are attached to each folder's namespace: for instance, everything under operations/ ends up as parts of iD.operations. Luckily we've followed a good pattern for how each component works: each one attaches a function to the namespace. With ES6 modules, we're instead going to `export` each function, and then import them.

So the flow is:

* Move a directory full of files from js/id/namespaceName to modules/namespaceName
* Convert each file to ES6 export and import style
* Add a new bit in the [Makefile](https://github.com/openstreetmap/iD/blob/master/Makefile) patterned off of the `actions.js` generation that generates a bundle file for the newly-modularized section of iD
* Update [test/index.html](https://github.com/openstreetmap/iD/blob/master/test/index.html) to point to this bundled file instead of the individual files from that part of iD.
* Run tests
* Submit a PR!

This is an incremental process, so this flow does not include everything that will eventually be part of this effort, only the things we can parallelize.

_After_ the initial batch of modularization is done and all the checkboxes above are checked, then we will move from multiple bundle files to one, and then move dependencies like lodash and d3 from globals to `import`'ed modules.

**How to start**:

When you have the time and energy to help out with a chunk of this work, post back to this ticket indicating which part you're working on, and then open a PR for that part. We can parallelize this fairly well but be careful not to lock a part until you're pretty sure that it's something you can work on immediately.

cc @substack @kepta @bhousel @dereklieu @gmaclennan @jfirebaugh @hallahan @kriscarle @smit1678

---

The murmurs and innuendos are true.  We're planning a refactor soon-ish to switch iD to a more modern project with ~~CommonJS~~ ES6 style modules, `require`, and a build tool like ~~`browserify`~~ `rollup`.   (The first comment [here](http://browserify.org/#who-section) sold me).

Anyway, this explains why I am pushing to clear out the backlog of open PRs.  
Expect major breakage in the next month!  🔨

**Comment by kepta** [comment]
Yay !!!, finally iD will get refactored to modules. I am super excited for this one.
I believe `Browserify` is really awesome, but in my opinion is getting or already is old and  [ECMAScript 6 modules](http://www.2ality.com/2014/09/es6-modules-final.html) are finally a possibility. 

It would really great if we we can have a discussion rolling about the various options JS community has to offer, in the best interest of iD.

Here is a list of options which I feel are worth considering.

- [Browserify](http://browserify.org)
   CommonJS, _*current choice, simple and sticks to the job*_

- [Webpack](https://webpack.github.io)
   AMD, CommonJS, _*currently most popular in reactJS-ish projects. Removes the clutter of grunt, gulp or any task runner. Setup is a bit confusing.*_

- [JSPM](http://jspm.io)
   ES6, CommonJS, AMD, _*Easy to setup and works out of the box, support for HTTP/2*_

- [Rollup](http://rollupjs.org) 
  ES6, **New thing in the town with ES6 tree shaking, worth considering**.

Some links I think might be interesting to read.
- [ES6 modules](http://www.2ality.com/2014/09/es6-modules-final.html)
- [MDN doc](https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import)
- [Webpack vs Browserify](https://medium.com/@housecor/browserify-vs-webpack-b3d7ca08a0a9#.nuew6krib)
- [Rollup](https://vkbansal.me/blog/rollup-first-impressions/)
-[JSPM](http://nervosax.com/2015/08/05/why-not-try-jspm-and-systemjs/)
-[webpack jspm browserify compared](http://www.slant.co/topics/3900/compare/~webpack_vs_jspm_vs_browserify)
-[JSPM vs webpack](http://ilikekillnerds.com/2015/07/jspm-vs-webpack/)

**Comment by kepta** [comment]
ES6 modules progress *(add more to the list)*
- [ ] iD.actions
- [ ] iD.geo
- [ ] iD.operations

**Comment by tyrasd** [comment]
I'll be working on these:
* [x] validations #3165

**Comment by beaugunderson** [comment]
I'll do `presets`!

**Comment by beaugunderson** [comment]
#3168 is open for presets ✨

**Comment by bhousel** [comment]
I'll take `services`

**Comment by beaugunderson** [comment]
PR for `svg` incoming ✨

**Comment by beaugunderson** [comment]
#3177 is open for `svg`!

**Comment by kepta** [comment]
@tmcw it is lonely out here
<img width="210" alt="screen shot 2016-06-17 at 5 19 55 pm" src="https://cloud.githubusercontent.com/assets/6966254/16149625/c454fc78-34af-11e6-97d7-49dbfe646cc0.png">

whats next for phase II.

**Comment by tmcw** [comment]
Now that https://github.com/openstreetmap/iD/pull/3167 has landed, we're on to stage 2! I owe @kepta @bhousel @tyrasd @beaugunderson and @davidchouse ☕ 🍵 or 🍺 ! Redeemable whenever I'm in your cities, you're in mine, or via bitcoin if you're into cybercurrency :)

On to phase 2! https://github.com/openstreetmap/iD/issues/3179
