### ISSUE TITLE
Data viewer for unregistered users based on iD.

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3119]
An intention of iD is to lower the entry threshold for new user. A way to do this would be making OSM users familar with iD's representation of data already before the user decides to register in order to edit something.
Therefore a special version or mode of iD should exist operating as a pure data viewer, which can be made available even to unregisterd users. An option to switch from data viewer mode to a sandbox editing mode would likely make the decision to register in order to contribute to OSM easier.

Currently OSM users are faced to the raw tags when exploring data on the OSM website, when starting to contribute they have to learn iD's abstraction of data.

**Comment by bhousel** [comment]
iD doesn't strictly require that users need to be registered and logged in to use it.  The iD embedded on openstreetmap.org does require this, but the mirrors on e.g. https://openstreetmap.us/iD/master or http://strava.github.io/iD wait until the user tries to save before authenticating them. 

If you're looking for a new project based on iD, it might be best to reach out to the OSM community and see if anyone wants to build it.  Or if you're looking for changes made on openstreetmap website, you'd need to discuss those on their repository: https://github.com/openstreetmap/openstreetmap-website
