### ISSUE TITLE
Change suggested text in "name" field

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#3121]
I've seen after a lot of mapathons that people put bad data into the name box, like a description ("house" or "dirt road") or some other duplicative or descriptive tag. Right now the placeholder/help text inside the name field is "Common name (if any)" 

I think we should change it to something like "Official name (if not known, leave blank)" or "Proper name (if known)" -- something that implies that it's a specific name and can be empty. I think "Common name" may be why people are putting things like "house" in there.

Thanks!

**Comment by aawiseman** [comment]
I should add that this name data is coming from remote mappers who definitely don't know what the actual name for that thing is.

**Comment by pnorman** [comment]
Name isn't for the official name of something. The problem is that "house" and similar aren't names at all.

**Comment by bhousel** [comment]
I also noticed that in the walkthrough we make users add names to everything, even the playground (we probably shouldn't).  And the walkthrough uses overly simple language, like "Add a name".   I think we can keep this simple, but add another sentence there about names.

**Comment by bhousel** [comment]
BTW, this was discussed in #1417.  Because this is a very common new user misconception, adjusting the walkthrough makes sense.

**Comment by aawiseman** [comment]
@pnorman Right, I'm just trying to make it seem more like a specific name than a description. Maybe "proper name" "actual name" ? 

@bhousel That's interesting about the walkthrough, I wonder if that's part of it.
