### ISSUE TITLE
Cookie_test doesn't always give/show the right result

### ISSUE THREAD

**Issue by maloumaris** [openstreetmap/iD#3122]
In an email I got a link to sign up for OpenStreetMap (https://www.openstreetmap.org/user/new?cookie_test=true). The website I got showed the sign up page, as expected, but also a message that I didn't have cookies enabled and I should enable them before going further. I've seen this in both Firefox and Chrome, see the attachment for a screen shot of the website in Chrome. I did have cookies enabled however, and simply changing the url to 'https://www.openstreetmap.org/user/new?cookie_test=false' made the message about cookies go away.

I've tried the same thing with cookies disabled. The same website, with the message about cookies being disabled was shown, and now changing the url to 'https://www.openstreetmap.org/user/new?cookie_test=false' did not make the message go away.

Especially the first case is confusing for people who don't know where to change their cookie preferences and whether they should do that, and even more so because the message shouldn't show when cookies are enabled.

![issue_osm](https://cloud.githubusercontent.com/assets/1774471/15387417/575a0244-1dad-11e6-8dcc-6737f8c0ead1.png)

**Comment by bhousel** [comment]
Thanks @maloumaris, but this issue tracker is for OpenStreetMap's browser-based map editor, iD.   

Any issues with the OpenStreetMap website itself should be opened here instead:  https://github.com/openstreetmap/openstreetmap-website

**Comment by maloumaris** [comment]
Sorry for the inconvenience, I've posted the issue in the right location this time.

**Comment by bhousel** [comment]
Not an inconvenience at all, thanks!
