### ISSUE TITLE
Make use of the inspector sidebar during active drawing mode

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3124]
While one of the drawing modes is active, the inspector sidebar ist showing object search, which is totally unrelated and useless for the mode. It migth be even confusing because it pops up when the mode button is pressed in case something was selected.

Therefore, we can replace it with something else being related to the drawing mode.
The top part of the sidebar can contain controls for drawing mode options like square drawing or remember tags options.

Below a "tags to be applied" section and a "fields to be applied"  should follow. These can have the same style as the all tags and all fields section of the inspector, but using a different background color might be useful in order to differentiate. It is important to place the "tags to be applied" first, because in case of remembering tags the user should be aware of all remembered tags. The "fields to be applied" section would be insufficient for this purpose because it is potentially incomplete and too long to be completely visible. 

In case there isn't any tag to be applied remembered by iD or already set by the user, tags/fields section should be replaced with the object type search. Allowing the user to preset the object type before drawing would allow iD to give object type specific drawing support like a special connectivity control.
This might avoid the requirement of many special drawing modes.

The controls for drawing mode options could contain:
- checkboxes and/or radio buttons for special drawing modes which could have a short textual despription and a link to a help page.
- A button to paste saved tags
- A button to paste tags of a Ctrl-C copied object to the tags to be applied section.
- A button to clear the tags to be applied. This can be hidden if no such tags exist.
- A button "save tags to be remembered" saving the current state of tags to be applied and setting the following checkbox. The storage should be separate for each mode.
- A checkbox "remember saved tags next time". If unchecked, it should be hidden because it is checked automatically by the previous button.
- A checkbox "make point/line/area mode sticky". If checked the mode is automatically reactivated after drawing the feature. This would allow drawing buildings for HOT tasks etc. very efficiently. It would prevent tagging directly after drawing, but this is not a real issue because even individual tags can be preset in the tags to be applied section before drawing. It might be useful to autoload remembered tags to the "tags to be appied section" in case the mode is sticky, but to offer a button to recall remembered tags explicitly otherwise. This could help to prevent applying remembered tags accidently because the user has forgotten that remember tags is still active. This additional button can be hidden if "remember tags is inactive or the mode is sticky.

**Comment by bhousel** [comment]
This is a lot more UI than I'm comfortable adding to iD.  Also, I don't want to add these settings to the sidebar while the user is in a draw mode.  Their focus should be on drawing.  And the sidebar is not empty - it displays information about features on the map as the user hovers over them.  This is important when they are drawing features that connect.

Try to remember, we are building iD primarily for people who have never edited a map before. 

If you want to fill up every available space with buttons and settings checkboxes, iD is not the right editor for you.   You'd probably be happier using JOSM, or maybe even forking one of the existing editors and changing things around until it looks like the editor you want.

**Comment by slhh** [comment]
The typical visual impact would likely be much lower than you expect and we can make it nearly zero.
The drawing mode options section can me made collappsed by default, but unfolded in case anything special is active.

In the standard usecase the only visual differences to the current state would be:
- An icon or headline to unfold the drawing mode options section
- Title of search box changed because of searching type instead of an object.

The hover use of the sidebar doesn't conflict, it can just override.
The drawing mode options dialog can already been hidden as soon as the first node is set, because the drawing mode needs to be known before drawing starts.
