### ISSUE TITLE
Unreadable part of the map

### ISSUE THREAD

**Issue by cherenok7** [openstreetmap/iD#3126]
The map of the city Aktobe (Kazakhstan) partially unreadable is also not for modification at the moment. Whether it is possible to update this part of the map?

**Comment by bhousel** [comment]
Thanks, can you post the url where you see the issue?

**Comment by cherenok7** [comment]
https://www.openstreetmap.org/edit#map=15/50.2956/57.1562   -  As you zoom in , the image becomes blurred , so the map  modification is not possible

https://www.openstreetmap.org/edit#map=14/50.3285/56.0058   -  There is a village , but it is not visible due to clouds

**Comment by bhousel** [comment]
> https://www.openstreetmap.org/edit#map=15/50.2956/57.1562   -  As you zoom in , the image becomes blurred , so the map  modification is not possible

One thing you can try is:  type "B" to open the background imagery panel and switch which background imagery is used.   It looks like in this area Mapbox Satellite is more detailed than Bing (the default).

> https://www.openstreetmap.org/edit#map=14/50.3285/56.0058   -  There is a village , but it is not visible due to clouds

Unfortunately in this area, neither Bing nor Mapbox Satellite look very good.

This link below contains some information about the background imagery, along with steps to report issues. 

https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery
