### ISSUE TITLE
Tracktype tag is filled with a translated preset value

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/iD#3129]
1. Create a line.
2. Make it a road → track.
3. Choose a track type.

Expected: `tracktype=gradeN`, got: `tracktype=Translated name of the preset value`.
Hasn't encountered this bug with other field, `smoothness`.
The bug occurs in the Russian version, not sure if other languages are affected.

![2016-05-23 18 55 49](https://cloud.githubusercontent.com/assets/766031/15476519/7e179d9e-2120-11e6-8792-4363f282da2b.png)

**Comment by bhousel** [comment]
Good catch, thanks!   Those translations have trailing spaces.  The fix was to compare cleaned values, not raw values.
