### ISSUE TITLE
Colored bar across screen from incomplete MPs

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#3132]
http://www.openstreetmap.org/edit?editor=id#map=17/34.07395/-84.01521
![image](https://cloud.githubusercontent.com/assets/1190866/15522223/d5e8e3d4-21c5-11e6-9dca-4238aab3073e.png)

This is from http://www.openstreetmap.org/way/34771311 which is landuse=transport as part of a landuse=meadow MP. I had to scroll fairly far to find the edge to be able to identify the way.

There's some data issues here, but I think the rendering issues would still occur with more sensible data.

Related #1201 #2945

**Comment by bhousel** [comment]
I see these sometimes too - I always assumed it was from a multipolygon with a multiple outers that weren't all downloaded?

**Comment by SHARCRASH** [comment]
There is no data issue, it is a indeed a MP with its multiple lines being outer relations and defining the area of that MP. It's just being misused. 

By viewing the entire [relation](http://www.openstreetmap.org/relation/142923), the MP is supposed to represent the surface of the transport network, so to have this correct, the meadow tag should be removed/relocated and all the transport tags should be transposed from the lines to the area part, where the type=multipolygon tag is.

PS: bafled by the lack of precision and the quantity of obsolete nodes on straight lines introducing usless data.

**Comment by bhousel** [comment]
Closing as a duplicate of #1201
