### ISSUE TITLE
Fugro imagery is no longer available

### ISSUE THREAD

**Issue by Hjart** [openstreetmap/iD#3135]
The 2005 [Fugro (Denmark) imagery](http://wiki.openstreetmap.org/wiki/Fugro) is severely outdated and is no longer available from any server (since at least 2 years), so removing it as an option in iD would be appropriate.

**Comment by bhousel** [comment]
Thanks @Hjart, can you open this issue in the [editor-layer-index](https://github.com/osmlab/editor-layer-index) repository?  That's where iD pulls its imagery from.
