### ISSUE TITLE
"no_u_turn" restrictins where "from and "to" are the same way

### ISSUE THREAD

**Issue by rabosm** [openstreetmap/iD#3138]
I see a lot of this turn restrictions. All of them were introduced by ID users. Please prevent users somehow, from creating this kind of restrictions. Please validate turn restrictions in general before uploading.
https://www.openstreetmap.org/relation/6242629

**Comment by bhousel** [comment]
See #2527 
This is valid tagging in most parts of the world where the restriction can be signed.  Having the restriction there even in cases where it is not strictly needed is fine.
