### ISSUE TITLE
Searching for "grill" doesn't show relevant result on the first page

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/iD#3139]
While [mapping a local park](https://www.openstreetmap.org/changeset/39648286) I noticed that when adding public grills, I couldn't find them in iD search. I added one manually and noticed the proper tag popped up, which is named "Barbecue/Grill". Typing `grill` into iD search doesn't yield the proper tag until I scroll down.

![screenshot 2016-05-29 14 21 02](https://cloud.githubusercontent.com/assets/1827881/15635334/03897456-25aa-11e6-9afa-11735063a19b.png)

I think the issue is that [the terms for `amenity=bbq`](https://github.com/openstreetmap/iD/blob/1683e3e8eb369cb7c48e4024765af98f104fc81d/dist/locales/en.json#L1612-1614) do not include "grill" (or "barbecue" for that matter).

FWIW these are [called `public grill` in JOSM (see L4005)](https://josm.openstreetmap.de/changeset/9638/josm).

**Comment by bhousel** [comment]
Sure, this just needs the word "grill" added to the `terms` array in `bbq.json` preset file, then run `make`.  After that it should sort highly in the list.

This is a great task for anyone looking to get started with iD..
