### ISSUE TITLE
GPX file import

### ISSUE THREAD

**Issue by speedbiker** [openstreetmap/iD#3141]
I would like to make the following proposal for importing and acquisition of tracks out of GPX files.
Currently it's just possible to display a GPX track as a colored line with ID editor. This imported track is displayed as a pink line. Then you must trace this pink line with the ID-editor's lines tool.
Would it be possible that the track (which may be optionally select the GPX import) will be displayed directly as a (untagged) line and you as a mapper just add the tag to the the existing line? That would save a lot of work and even at the same time increase the precision of the drawn paths under certain   circumstances.
![image](https://cloud.githubusercontent.com/assets/13400616/15735369/7cf70a6a-2898-11e6-972b-c35fbe408302.png)

**Comment by bhousel** [comment]
Sure, we're thinking of adding this.. Discussion is on #2586.
