### ISSUE TITLE
French translation for leisure/slipway is confusing

### ISSUE THREAD

**Issue by fab-girard** [openstreetmap/iD#3143]
Hello,
slipway is translated in french "Plan incliné" in `dist/locales/fr.json`.
http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dslipway
Contributors use this tag for "rampe d'accès pour fauteuil roulant" (correct tag is wheelchair=yes in this case) or when road is just sloping.

To avoid errors, I suggest the translation "Mise à l'eau". The json could be in this case : 
```
"leisure/slipway": {
  "name": "Mise à l'eau",
  "terms": "Cale de lancement, Cale, Cale de mise à l'eau, Rampe, Rampe de mise à l'eau"
}
```

Fab

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/ideditor/id-editor/dashboard/).  You can sign up for an account on that site to fix the translation, and then it will be included in the next release of iD.
