### ISSUE TITLE
Feature Request: Align nodes function

### ISSUE THREAD

**Issue by g4rpch** [openstreetmap/iD#3146]
Dear all

Would be great to have a function to align multiple selected nodes with the first one selected.
Example to align following shops:
![schermata 2016-06-06 alle 20 22 48](https://cloud.githubusercontent.com/assets/15292575/15833032/081fb288-2c25-11e6-954f-82a2ccd59f7d.png)

Many Thanks
G4rp

**Comment by bhousel** [comment]
Yes, see #2987
