### ISSUE TITLE
Add Strava Globalheat as a background data layer option

### ISSUE THREAD

**Issue by planemad** [openstreetmap/iD#3150]
Strava Globalheat is an excellent global source of GPS data and is [open for use in OSM for tracing](http://wiki.openstreetmap.org/wiki/Strava#Global_Heatmap). We should have this as a background layer option alongwith OSM GPS.

![openstreetmap_and_preferences](https://cloud.githubusercontent.com/assets/126868/15853998/322e34b4-2cc5-11e6-9753-24157ef7b429.png)

- Strava Globalheat homepage http://labs.strava.com/heatmap/
- TMS url: `http://globalheat.strava.com/tiles/both/color2/{zoom}/{x}/{y}.png` (upto z16 only)

cc @kepta

**Comment by kepta** [comment]
I think is a really good idea, @bhousel @jfirebaugh what do you guys think?

**Comment by bhousel** [comment]
The [last time we discussed Strava heatmap](https://github.com/openstreetmap/iD/issues/2716#issuecomment-121759915) we got confirmation that the heatmap can not be used outside of Strava.   Unless something has changed license-wise, we can't use this layer.

Would be happy to accept a pull request to the [editor-layer-index](https://github.com/osmlab/editor-layer-index) project from Strava, if their policy has changed.

**Comment by planemad** [comment]
Have mailed Strava maps for clarity on the policy which seems contradictory to what is documented in the [OSM Wiki](http://wiki.openstreetmap.org/wiki/Strava#Global_Heatmap).

**Comment by tordans** [comment]
@planemad did you hear back from Strava? Or managed to get information about this?
The OSM Wiki and also current reports(1) still say that using the map is allowed.
Isn't there a OSM licence mailing list that could be asked?

(1) http://blog.openstreetmap.de/blog/2018/02/wochennotiz-nr-393/
> Auch Soldaten diverser Nationen nutzen die Fitness-App Strava. Ob deren Gegner die Strava Global Heatmap, _welche übrigens auch von Mappern verwendet werden darf_, zur Open-Source-Aufklärung verwenden? Nach einem Tweet darüber überschlägt sich die Presse: Heise (Kommentar), FAZ, Guardian, …
(Italic part translated: the strava heatmap can be used for mapping.)

Stravas own iD editor seems to tell the same story. Unfortunatelly this version of iD seems old and the heatmap is not the same as the new one that was published recently.
Example: https://strava.github.io/iD/#background=Bing&map=17.41/14.04012/52.83764&overlays=,,,
vs. https://labs.strava.com/heatmap/#16.98/14.04080/52.83861/hot/all

**Comment by bhousel** [comment]
Current progress on securing permission to use the heatmap for OSM tracing is happening here:
https://github.com/osmlab/editor-layer-index/pull/373

@tordans The OSM Wiki and Wochennotiz Blog are not correct.  We've received no license from Strava that allows tracing outside of their iD fork.
