### ISSUE TITLE
Display Strava Globalheat as a reference layer automatically while adjusting imagery offset

### ISSUE THREAD

**Issue by planemad** [openstreetmap/iD#3151]
The imagery offset option is super valuable for critical projects like HOT, and we need a good reference layer to help users accurately adjust the offset to the best position.

The current mechanism only allows adjusting to OSM GPX, but the coverage is poor and is mostly from pre Bing days when the trace quality was not that good.

Further to https://github.com/openstreetmap/iD/issues/3150 Strava Globalheat has far better coverage and is of significantly higher quality that allows for better offset correction. This was also used to correct imagery offset in [complex scenarios in Japan](https://github.com/mapbox/mapping/issues/116#issuecomment-137688728) recently.

![screenshot 2016-06-07 15 24 05](https://cloud.githubusercontent.com/assets/126868/15853736/f6a46e96-2cc3-11e6-8004-32932634a4d1.png)
_OSM GPX vs Strava Globalheat(blue) for a random junction in India_

Automatically enabling Strava Globalheat during offset correction can aid a new user to accurately position the imagery. The layer can be hidden again once the layer panel is closed.

cc @kepta

**Comment by bhousel** [comment]
We can't "automatically" display a layer of imagery that has not yet been downloaded to the client.

The proper steps here are:

0. Get permission from Strava to use the heatmap
1. Tell users to enable the heatmap
2. User can adjust imagery offset as they currently do
