### ISSUE TITLE
Allow straightening of multiple contiguous lines

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#3176]
The straighten tool could be extended to work with contiguous line segments.  It is very common to have a straight street with multiple segments (different lanes, speeds and so on) and currently there is no way to make them straight from start to end.

What I am suggesting is that when there are multiple lines selected, if they are connected and contiguous the "straighten" button should be available, just like it is already done with the "+" button currently.

**Comment by homersimpsons** [comment]
As a workaround you can drow a line selecting all way note and straighten this line. (more explanation on #2987)

**Comment by bhousel** [comment]
duplicate of #2058
