### ISSUE TITLE
ES6 Modules: phase 2

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/iD#3179]
Phase 1 of iD's modularization is captured in https://github.com/openstreetmap/iD/issues/3118 and completed by our lovely community! Phase 2 is one task that @kepta is leading out and @bhousel is helping land:

So, phase 1 involved a lot of work and was split by the natural split points in iD: each module, like iD.ui and iD.svg. We have some degree of 'using modules for requiring their dependencies' but not 100% - the modules in `modules/*` still rely on the iD global all over the place. And we're creating a bundle per part of iD.

Phase 2 means

* Remove the iD global for the eslint configuration of `modules/*`, so that relying on global iD is forbidden
* Using `import` instead to require dependencies
* Instead of making a bunch of bundles, create one entry file that imports _all_ of iD, and goes through one rollup run to create the iD bundle.

---

I'll open a ticket for a moment for phase 3; the two tasks are/should be separable so that we can keep shipping little bits of work at a time.

**Comment by kepta** [comment]
@tmcw how should we tackle the file `js/id/id.js`....

**Comment by tmcw** [comment]
@kepta looks like that file serves 2 purposes: providing window.iD and then the [iife](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) for feature detection. It should probably end up in two files serving those two purposes.

**Comment by kepta** [comment]
@tmcw will we be needing `window.iD` anymore?

**Comment by tmcw** [comment]
@kepta I _think_ so - do some research into the [openstreetmap/openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website) repo to see if it uses the iD global to manipulate the map.

**Comment by tmcw** [comment]
Merged the core PR! @kepta want to keep rolling on this work? Next step could be to [remove the iD global](https://github.com/openstreetmap/iD/blob/master/.eslintrc#L55) and get all those errors fixed.

**Comment by kepta** [comment]
@tmcw, while working on `services` module, some of the test cases are failing. Because some test cases  (spec/directly manipulate `iD.services` eg `spec/ui/preset/wikipedia.js:32` ) and rollup freezes all the import objects.

**Comment by bhousel** [comment]
With #3231 merged I think this can _almost_ be closed.

I think we missed this part, so I'll do it now..
>@kepta looks like that file serves 2 purposes: providing window.iD and then the iife for feature detection. It should probably end up in two files serving those two purposes.

**Comment by kepta** [comment]
This is looking good.
Some points I wish to discuss: 
1. What is the future of iD global variable, are we totally removing going to remove it?
2. if 1: The `modules/index.js` should then some how stop exporting the iD object. And then we need to bootstrap the code somehow.
3. if 2: we need to create a new ticket to discuss the strategy for iD unit tests.

**Comment by tmcw** [comment]
> What is the future of iD global variable, are we totally removing going to remove it?

The goal is to export it in one place - iD itself, internally, won't use it, and we'll remove it from the eslint globals list. But we'll export it as umd with rollup, and that'll be the API integrating applications use to integrate with iD as a script.

> we need to create a new ticket to discuss the strategy for iD unit tests.

Yes, for parts of iD that aren't going to be part of the publicly-exposed iD object, we'll need a new strategy. That strategy will probably be similar to our existing one: tests will use import & export to acquire parts of iD for testing.
