### ISSUE TITLE
ES6 Modules: Phase 3

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/iD#3180]
Phase 2 is documented in https://github.com/openstreetmap/iD/issues/3179

---

In Phase 2, we condense the modules into one bundle and eliminate reliance on the iD global. Phase 3, we eliminate reliance on libs: we stop using a lodash global, same with ohauth and other lil libraries. End of the day, we have no global vars whatsoever, we remove vendored libraries from the source tree and instead use npm to install them.

This happens after phase 2 and can be @kepta or whoever wants to take it on :)

**Comment by bhousel** [comment]
Vendored libraries TODO:

- [ ] bootstrap-tooltip.js
- [ ] d3-compat.js
- [ ] d3.combobox.js
- [ ] d3.curtain.js
- [ ] d3.dimensions.js
- [ ] d3.geo.tile.js
- [ ] d3.jsonp.js
- [ ] d3.keybinding.js
- [ ] d3.one.js
- [ ] d3.trigger.js
- [ ] d3.v3.js  🌊 
- [ ] d3.value.js
- [ ] diff3.js
- [ ] jxon.js
- [ ] locale.js
- [ ] lodash.js 🌊 
- [ ] marked.js
- [ ] osmauth.js
- [X] rbush.js (#3196)
- [X] sexagesimal.js (#3191)
- [ ] togeojson.js

**Comment by bhousel** [comment]
I think all the remaining items were rolled into #3344 and this can finally be closed..
Thoughts @tmcw ?

**Comment by tmcw** [comment]
👍 Yep, the future is now!
