### ISSUE TITLE
Adding source maps for development build

### ISSUE THREAD

**Issue by kepta** [openstreetmap/iD#3185]
While working on  #3186  today, I realized we really need source maps for the developmental build.

We should discuss on how to setup this new development evironment for eg. live reloading, rollup watch etc.

cc: @tmcw @bhousel

**Comment by bhousel** [comment]
Live reloading is not interesting to me, but we really need source maps.  Developing anything is currently pretty painful.

**Comment by tmcw** [comment]
Eye on the prize: https://github.com/openstreetmap/iD/issues/3179 is the next step and will make sourcemaps and rebuilding simple. Trying to hit either before #3179 is done will be unnecessarily difficult.

**Comment by bhousel** [comment]
This was done
