### ISSUE TITLE
referer string for imagery request

### ISSUE THREAD

**Issue by althio** [openstreetmap/iD#3197]
Hi iD team,

Is there a 'referer' string or anything similar, that could be used to identify a request issued by iD?

The use case is to allow access to some imagery only for OSM tracing (hence trying to detect iD and JOSM users to provide them the tiles).

**Comment by bhousel** [comment]
The way we handle this in the Mapbox Imagery layer is to append an `access_token` parameter to the request:  see [editor-layer-index sources/world/MapBoxSatellite.json](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/world/MapBoxSatellite.json#L4)

**Comment by althio** [comment]
Good to know, but it looks like a public token. is it so?
Is that enough for a private/exclusive access?

What is the recommended way to handle private access to imagery, where imagery provider wants to allow usage for OSM tracing only, but restrict other uses?

**Comment by bhousel** [comment]
> Good to know, but it looks like a public token. is it so?
> Is that enough for a private/exclusive access?

Yes it's a public token that would need to be rotated if anybody abuses it.

If you want truly private access, I guess you could make users go to a page to accept terms, then set a browser cookie.   When iD requests images from that domain the cookie will be sent and you can check for it server side.  If the user clears their cookies or switches browsers they will need to go through the process again.
