### ISSUE TITLE
Incorrect spelling of off license for en-gb locale

### ISSUE THREAD

**Issue by SK53** [openstreetmap/iD#3204]
File dist/locales/en-GB.json uses "off license" for shop=alcohol, but using an American English spelling for a peculiarly British term seems rather odd. Correct British English is "off licence" or "off-licence".

It may be worth considering a more general phrase which would be more likely to be understood by non-British users of this locale than the rather specific "off licence".

**Comment by richlv** [comment]
i would strongly support calling it an "Alcohol shop" or similar. i thought tagging is wrong when i saw this in iD.

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/ideditor/id-editor/dashboard/), so that's the correct place to apply the fix. 

direct link:  https://www.transifex.com/ideditor/id-editor/translate/#en_GB/presets/11618612

**Comment by richlv** [comment]
@bhousel, does this mean that the preset is fixed, or that that fix should be applied elsewhere ?
in any case, the direct transifex link returns error 404

**Comment by bhousel** [comment]
> does this mean that the preset is fixed

I think @SK53 fixed it already.   It appears as "Off licence (Alcohol shop)" now in Transifex.

**Comment by richlv** [comment]
ah, sounds great - thank you all :)
