### ISSUE TITLE
Editor uses deprecated tag sloped_curb=*

### ISSUE THREAD

**Issue by Self-Perfection** [openstreetmap/iD#3210]
Editor suggests using [deprecated](http://wiki.openstreetmap.org/wiki/Key:kerb#Features.2FPages_affected) tag `sloped_curb=*` It was dropped in favor of [more general kerb=* scheme](https://wiki.openstreetmap.org/wiki/Key:kerb)

**Comment by bhousel** [comment]
Thanks!   We were probably just following the suggestions on the `crossing` wiki page, which still lists `sloped_curb` in the ["Additional Tags" section](http://wiki.openstreetmap.org/wiki/Key:crossing#Additional_tags).
