### ISSUE TITLE
Add traffic calming preset for nodes

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3218]
Instead of having to select a node, click on "Other", then manually type in highway=traffic_calming and traffic_calming=, please add a preset to populate those fields.

Better still, add the various traffic calming types as additional presets: http://wiki.openstreetmap.org/wiki/Key:traffic_calming

**Comment by homersimpsons** [comment]
Some traffic calming can be used on way too, e.g. table, rumble strip and some other...

**Comment by homersimpsons** [comment]
Thanks for implementing this. I hope the next release will be soon :)
