### ISSUE TITLE
Add address preset for nodes

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3219]
Although it's probably better to use JOSM for adding lots of addresses, this change would make it quicker to do so in iD.

Instead of having to select a node, click on "Other", then select Address from the Add field dropdown, an Address preset would show the address fields, like when a building is selected.

**Comment by homersimpsons** [comment]
There already exist an adress preset, just search 'adress'

**Comment by boothym** [comment]
Really?
![address](https://cloud.githubusercontent.com/assets/16965772/16557100/cfd85422-41d5-11e6-9925-ca0bc0d12074.png)

**Comment by homersimpsons** [comment]
It exist but the node need to be alone (not connected) this is why you can't find this I think. 
As a workaround you can put a single node, choose adress and drag it to the way

**Comment by homersimpsons** [comment]
The geometry need to be change in this file: https://github.com/openstreetmap/iD/blob/master/data/presets/presets/address.json

**Comment by bhousel** [comment]
Yes, I think the preferred way of tagging addresses is any of the following:

* tag isolated nodes or
* tag nodes on a building way or
* tag the building way

To handle each of these, iD will display the `address` fields on:
* the "isolated node" address preset (`address.json` in previous comment)
* node-on-way presets like "Building Entrance"
* way building presets like "Building"

I think that covers the normal use cases.  

@boothym What were you trying to add an address to where you didn't see the preset in the search list?

**Comment by homersimpsons** [comment]
I think that was to tag a node-on-way

**Comment by boothym** [comment]
I was trying to tag a node on a building way (whether it be the corner of a way or one created by double-clicking on the way) - normally where the approx door/entrance to that address is located.

@homersimpsons As you say, I could create a separate node, add the address and then drag it onto the building way, but that's basically the same amount of work once this issue is fixed :)

**Comment by homersimpsons** [comment]
@boothym If you select entrance preset, You will get adress field

**Comment by bhousel** [comment]
> @boothym If you select entrance preset, You will get address field

Yes, this is what I recommend also.. Thanks!

**Comment by boothym** [comment]
The problem with that is it adds entrance=yes to the node when it might not be an entrance. All of the other address examples I've seen in OSM don't add entrance tags to an address node.

Why can't the address preset be available on a building way like it is available for nodes on their own? It doesn't need to be in the list when you click on a node, just available to search for like entrance. That way it is then available in the list as a recently used preset.

**Comment by bhousel** [comment]
> The problem with that is it adds entrance=yes to the node when it might not be an entrance. All of the other address examples I've seen in OSM don't add entrance tags to an address node.

As I mentioned in https://github.com/openstreetmap/iD/issues/3219#issuecomment-230602262, if you don't know where the entrance is than just add the address to the building itself or make a point for the address someplace.  OSM considers either of these options acceptable too.
