### ISSUE TITLE
Show specific wiki information for Alley preset

### ISSUE THREAD

**Issue by virgilinojuca** [openstreetmap/iD#3227]
Currently, if you click on the “i” icon in the _Alley_ preset, it shows the same information as in the _Service Road_ preset, which is the text from the [`highway=service`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservice) article on the wiki. I think it should display the information from the dedicated article [`service=alley`](http://wiki.openstreetmap.org/wiki/Tag:service%3Dalley).

Actually, I suppose the same issue happens in all other presets for tags in the `service` key, such as `service=parking_aisle`.

**Comment by bhousel** [comment]
Yes, fields [support a `reference` property](https://github.com/openstreetmap/iD/blob/master/data/presets/schema/field.json#L17) to control how the tag documentation lookup works... Presets should support something this too.

**Comment by bhousel** [comment]
I just did this.  Previously, the preset reference code would just guess by picking the first key in the preset tags.  Now we can specify which tag combination is used to fetch documentation.  I also went through and updated a lot of presets to have better documentation.  This affects just about all presets that use some combination of tags.

#### Before:

<img width="350" alt="screenshot 2017-05-07 11 54 34" src="https://cloud.githubusercontent.com/assets/38784/25782608/3db01308-331c-11e7-8042-7de2eb289390.png">

#### After:

<img width="350" alt="screenshot 2017-05-07 11 54 44" src="https://cloud.githubusercontent.com/assets/38784/25782609/41f2062e-331c-11e7-9af1-c03fa9a94a57.png">
