### ISSUE TITLE
Add ref field to post box preset

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3232]
At the moment there are the fields for operator, collection times and drive-through - can a reference (ref=) field please be added so you don't have to type in "ref" manually? 

I assume this file https://github.com/openstreetmap/iD/blob/d130c517b0a98c470aef269176bda729532f8ff1/data/presets/presets/amenity/post_box.json would need to be edited?

**Comment by bhousel** [comment]
Yes, that's the right file!  Just add a `ref` field to the end of the `fields` array.

**Comment by boothym** [comment]
Thanks, but is it that simple or will there be an issue with ref versus reference (as the other fields are all spelled the same as their tag)?

**Comment by bhousel** [comment]
Yes, I think it is that simple.. Adding `ref` to the fields array will tell the iD ui to show [this `ref` field](https://github.com/openstreetmap/iD/blob/master/data/presets/fields/ref.json) in the sidebar.

**Comment by boothym** [comment]
Ok, I've edited the file and created a pull request - hope I've done it right!
