### ISSUE TITLE
POI presets are not recognized in interpolated address lines

### ISSUE THREAD

**Issue by virgilinojuca** [openstreetmap/iD#3241]
If you use lines for [interpolating house numbers](http://wiki.openstreetmap.org/wiki/Addresses#Using_interpolation), and there are POIs in it, they will not be recognized with presets. This happens either if they are in the middle of the line or on the end nodes. Not only they will not have an icon on the map, but they will also display a “Other” preset in the left sidebar if you click on it.

![Comparison of with and without interpolation line](http://i.imgur.com/bb5othY.jpg)

They are also not recognized if they are mapped on the edge of a building—a practice that I have noticed mainly in strip malls where I live. I don't know if this practice is correct in the first place though, so it may not be a problem there.

**Comment by bhousel** [comment]
ohhh #3219 asked for this and I didn't see the need - but yes I agree it's important for address interpolation lines.

**Comment by bhousel** [comment]
Thanks for this suggestion, I implemented it in 0d8fb87

We now treat entities on address interpolation lines as points, not vertices.. This affects both the rendering and the preset matching and preset suggestions:

<img width="206" alt="screenshot 2016-07-14 12 24 40" src="https://cloud.githubusercontent.com/assets/38784/16848324/48b8ff64-49c3-11e6-87c7-95b4c52e5dab.png">

**Comment by virgilinojuca** [comment]
Great! Thanks for considering my suggestion.
