### ISSUE TITLE
[UX] "Done" button of Walkthrough should be different from "Apply" button

### ISSUE THREAD

**Issue by gerdneuman** [openstreetmap/iD#3247]
I was at this step in the walkthrough:

![ux_osm](https://cloud.githubusercontent.com/assets/12525563/16871274/4d058e2a-4a86-11e6-8b65-caf95c235ca8.png)

I looked for the "check mark" :heavy_check_mark: 

I looked for it at the bottom of the form, because "Save" and "Apply" is usually at the bottom. Then I hit ":heavy_check_mark: Navigation" which brought me back to the beginning of the walkthrough and I was lost for a few moments.

Late I found the :heavy_check_mark: at the top of the form. 

Please change to :heavy_check_mark: Navigation to something else. I do not know what there must be some kind of emoji for Apply (:heavy_check_mark:) and one for Done, though I cannot find one at http://www.emoji-cheat-sheet.com/ maybe just :thumbsup: would do

**Comment by bhousel** [comment]
Good suggestion!   I agree that now that we use check mark in the sidebar, we shouldn't have them in the walkthrough navigation.

**Comment by bhousel** [comment]
Just fixed this.  We won't use checkmarks anymore in the navigation, instead we add the word "done" (translatable) when the step is completed.

<img width="295" alt="screenshot 2016-07-24 12 28 25" src="https://cloud.githubusercontent.com/assets/38784/17085975/daef203c-519a-11e6-985a-be961aac08fe.png">
