### ISSUE TITLE
Default Wikipedia language is set to english

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3265]
My browser has german as the default, my OSM Profile is german and i am editing in germany.
But the default languag for Wikipedia is still english in the dropdown

**Comment by bhousel** [comment]
That definitely sounds like a bug!  Which browser are you seeing this in?

**Comment by HolgerJeromin** [comment]
At least in Chrome on Linux. But I think I had this on chrome on Windows, too.

**Comment by HolgerJeromin** [comment]
Thank you for your work on id!
