### ISSUE TITLE
Use Foursquare's hoursparser.js to make hours entry in iD simple and lightning fast

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/iD#3269]
Foursquare uses a nifty bit of js to parse a venue's opening hours out of a free text field. This allows the user to simply copy the restaurant hours from a website, or other source and paste it into a box, which converts them into a format the Foursquare platform understands. Here's a demo:

![animation 2](https://cloud.githubusercontent.com/assets/1827881/17079604/34c00e7c-50e3-11e6-8b55-5aac79f1a5df.gif)

**I propose** that [since the code that does this is :octocat: open source](https://github.com/foursquare/hoursparser.js), we integrate this functionality into iD to make it easy for users to enter hours for OSM locations. 

![image](https://cloud.githubusercontent.com/assets/1827881/17079669/8758258c-50e5-11e6-8e8f-57c3f368c1d5.png)
### Current Method

The current method involves understanding the fairly complex `opening_hours` schema, and then manually translating hours into that format.

![image](https://cloud.githubusercontent.com/assets/1827881/17079640/87bdcc44-50e4-11e6-98fb-079f071193f5.png)

There are few online tools to do this, but the [best one I've found, YoHours, requires that the user "draw" the hour blocks](https://github.com/PanierAvide/panieravide.github.io/tree/master/yohours) on a weekly schedule graph. This is still a bit tedious and probably more than a casual editor is willing to do.

![image](https://cloud.githubusercontent.com/assets/1827881/17079652/ecb7c654-50e4-11e6-813f-917cdfb855ba.png)

**Comment by bhousel** [comment]
Looks like a nice tool!  There is some prior discussion on #974, and you're right there is no really great and intuitive way of entering osm-style opening hours data.

For me the bigger challenge is:  if we create a field for "simple" opening hours, we need to write code to parse existing opening hours data to make it work in that field.  I guess that would include dealing with some of the less established parts of the [opening hours specification](http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification) like `PH off`.

**Comment by bhousel** [comment]
let's keep everything related to `opening_hours` on #974
