### ISSUE TITLE
Error when trying to serve iD from dist

### ISSUE THREAD

**Issue by elusive-code** [openstreetmap/iD#3273]
When iD editor being served from `dist` it produces following error:
`index.html:45 Uncaught TypeError: iD.services.taginfo is not a function`

It looks like it happens because of the line
`.taginfo(iD.services.taginfo());`
as opposed to 
`.taginfo(iD.services.taginfo.init());`
in `index.html` in root folder

Later was changed in fc680a2

If line `dist/index.html` replaced with the one from `index.html` - it works.

**Comment by elusive-code** [comment]
Ah, sorry, used old version. Apparently it was fixed in 7ca6d06

**Comment by bhousel** [comment]
Yes!  Lots is moving on iD lately, and we fixed this recently.  Thanks for the report 👍
