### ISSUE TITLE
Preset for leisure=miniature_golf

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3279]
I edited a small leisure=golf_course which was named "Mini Golf", but noticed there was no preset for leisure=miniature_golf. 

Want to check I'm editing the correct file - do I simply take a copy of iD/data/presets/presets/leisure/golf_course.json, edit and rename it? 

Also, how do I make it so that it appears for anyone typing in "crazy golf", "mini-golf" or "putt-putt"? (which are mentioned as other terms in the wiki)

**Comment by tyrasd** [comment]
Yes, you're on the right track. Synonyms are added via the `terms` property.

See also https://github.com/openstreetmap/iD/blob/master/data/presets/README.md for some additional information about presets.

**Comment by bhousel** [comment]
closed with
ad11770 2016-07-27 Create miniature_golf.json 
5de925b 2016-07-27 Fix commas, run make
Thanks!
