### ISSUE TITLE
Multiple checkboxes

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#3285]
I was trying to write a preset for [blood donor centers](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dblood_donation). The tagging scheme is easy to apply manually, but I'm struggling to make the part about which blood components are collected look clear in iD. I was thinking of this:

![id_field_blood_components](https://cloud.githubusercontent.com/assets/4283376/17179216/ab63fba0-5418-11e6-8fa7-33305f4c943f.png)

But I didn't find a field type that looks like this. (It's like a hybrid of `access` and `check`.)

Would it be OK if I tried to make it? What name should it have? Something like "multiCheck"?

**Comment by bhousel** [comment]
For that I'd use the multiselect field that we added in #3080:
example: https://github.com/openstreetmap/iD/pull/3080#issuecomment-215933840

**Comment by M1dgard** [comment]
I did consider this, but it *feels* a bit odd. When I'm mapping a donor center, do I have to search for all components I can donate there?

Also, you have to be able to express that you *cannot* donate a specific component there (e.g. `blood:platelets=no`). Unlike `recycling:*=yes` it defaults to unknown, even when some components are given.

**Comment by bhousel** [comment]
> I did consider this, but it feels a bit odd. When I'm mapping a donor center, do I have to search for all components I can donate there?

We wrote the multiselect field in a way that (like combo fields) it can either be a fixed list of values or use free-tagging with suggestion from taginfo.

> Also, you have to be able to express that you cannot donate a specific component there  (e.g. blood:platelets=no).

Yes that's true.  I'm ok about this.  I think data consumers should just assume 'no' if a thing is not tagged with a 'yes'.  Encouraging users to tag the 'no's is unnecessary.

**Comment by M1dgard** [comment]
> Encouraging users to tag the 'no's is unnecessary.

I guess you're proposing to make no distinction between `no` and unknown. Or would you use `blood:platelets=unknown`? (not intended cynically)

I have mapped blood donor centers without knowing whether you can have stem cell samples taken there, and I quite like the fact that absent=unknown.

**Comment by bhousel** [comment]
In iD's multiselect fields we're only supporting `yes`.  It's ok if people want to use the raw tag editor to add `no` or other values.  But our main goal is getting people to tag the `yes` values (and not being confusing to new users).

> I guess you're proposing to make no distinction between no and unknown.

These tags in osm can contain other values like `maybe`, `sometimes`, `false`, `1`, etc, so it's easier for iD to just ignore anything thats not `yes`.   I'm not proposing anything, but if I were a data consumer, I would probably ignore anything that's not `yes`  (like `blood:platelets=unknown`).

**Comment by M1dgard** [comment]
If I were a data consumer, I'd ignore everything that's not either `yes` or `no`. I'd of course ignore `no` as well if my user wants to search for a facility where he can donate e.g. plasma.

There are other uses though. If my user wants to see information about a facility, and no tag is present, I don't know what I should tell him.

* I could interpret it as `no`, possibly giving him false information and hoping he doesn't rely on it.
* Alternatively I could say "unknown". Suppose this user then feels the urge to go mapping, in iD he won't find a way to add the information, even though I had to tell him the information is missing.
* Something in between, being intentionally vague. This is not user-friendly for my user.

But I hear you, you want to keep things simple for mappers, so as not to scare new contributors away, and that's a good thing too of course. Personally I think in this particular case 4 checkboxes with yes/no/unknown is very clear.

**Comment by bhousel** [comment]
> But I hear you, you want to keep things simple for mappers, so as not to scare new contributors away, and that's a good thing too of course.

Are you ok if I add the field as a multiselect (like recycling), just to close this out quickly?

> There are other uses though. If my user wants to see information about a facility, and no tag is present, I don't know what I should tell him.

Tell them to assume the value is `no` if no tag is present.

**Comment by M1dgard** [comment]
> Are you ok if I add the field as a multiselect (like recycling), just to close this out quickly?

Okay. I can make the preset and prepare a PR if you'd like.

**Comment by bhousel** [comment]
> Okay. I can make the preset and prepare a PR if you'd like.

yes please! 👍

**Comment by bhousel** [comment]
merged with #3290
