### ISSUE TITLE
Ambulance station is not only for buildings

### ISSUE THREAD

**Issue by maraf24** [openstreetmap/iD#3308]
Currently when I apply Ambulance Station preset to an area with landuse tag, editor
1. removes any landuse tag
2. adds bulding=yes tag

However http://wiki.openstreetmap.org/wiki/Tag:emergency%3Dambulance_station doesn't restrict usage of this tag to buildings.

**Comment by bhousel** [comment]
Yes, it defaults to a building, but iD makes it easy to remove the building tag, if it is just an open lot.  (The "Fire Station" preset works this way too.)

I'm happy with how it works currently:

![ambulance](https://cloud.githubusercontent.com/assets/38784/17302507/88710266-57ea-11e6-9b89-8f4e7dfc3089.gif)

**Comment by maraf24** [comment]
I reverted all changesets made by local iD user, who by using this function changed landuses to buldings.
So I was not sa happy with how it currently works. I guess he wasn't happy too.

It seems that removing certain tags in this editor is persistent problem, along with premature closing issues to prevent discussion.

**Comment by tmcw** [comment]
@maraf24 as you demonstrate with your comment, closing an issue doesn't prevent anyone from posting more details or continuing the discussion. Please lend a bit of kindness to @bhousel and the folks who work on the software you use: they have a very difficult job and are constantly juggling many priorities. @bhousel wasn't rude to you, and I'm sure that he'd be interested in a more detailed report, but should not be required to pick the informational part of the bug report out of the caustic tone.

**Comment by maraf24** [comment]
Closed issues are not listed as open isueas, so it makes them less likely to be viewed.

@bhousel closed this issue though his answer was only partial. He showed how to remove building tag.
What about landuse tag? It's still missing. Should I create another issue?

**Comment by bhousel** [comment]
> Closed issues are not listed as open issues, so it makes them less likely to be viewed.

Not at all, anyone subscribed to this repository still sees all the discussion related to it even though the issue is closed.  One reason I prefer to close issues like this is to prevent enthusiastic contributors from just jumping in and "fixing" an issue that maybe shouldn't be fixed.

> @bhousel closed this issue though his answer was only partial. He showed how to remove building tag.
> What about landuse tag? It's still missing. Should I create another issue?

Ok, so I really thought your initial issue was just about the `building` tag.  It's not really clear to me why you would want to keep the `landuse` tag on a feature that is also tagged with `emergency=ambulance_station`.   Can you elaborate?
