### ISSUE TITLE
save iD editor tags to a new database maybe different idea ?

### ISSUE THREAD

**Issue by FranciscoCosta** [openstreetmap/iD#3309]
Hello everyone, I am editing iD editor so i can put some more tags on it. i would like to have the my new tags saved in my own database and the tags from OSM saved in OSM database.

After my idea was to display all tags in one webpage using openlayers. Can someone tell me how can i do this?

Or instead ..

What if instead of upload all the tags , i only upload mine .
I mean in the "new" iD editor only have the new tags that i need and for the other tags i would simply redirect the user to osm id Editor?
then when i was going to display all the tags i just have to search in my database and in osm ? what do you think?

**Comment by bhousel** [comment]
Please don't open new issues for the same things.. You already opened #3307.
