### ISSUE TITLE
Edit id Editor

### ISSUE THREAD

**Issue by FranciscoCosta** [openstreetmap/iD#3310]
Hello everyone, I am editing iD editor so i can put some more tags on it. i would like to remove all the the preset tags and add my new ones i have to eddit the files in preset to had the new tags but how i get them to display in editor ? i have to eddit iD.js file right? 

thanks for all the help

**Comment by bhousel** [comment]
Please see [API.md](https://github.com/openstreetmap/iD/blob/master/API.md#customized-deployments) for more information about customized iD deployments.

This issue tracker is not the place to ask for general programming advice with your own iD fork.  I'd really like to see your project be a success, and I've given you some tips on #3307 on what to change in the code.  However if you keep opening up issues like this, I'm unfortunately going to need to restrict your access to the issue tracker.  

Please use other venues like stackoverflow, IRC, or other help forums to ask for advice on how to implement your project.
