### ISSUE TITLE
areaKeys emergency tag exceptions

### ISSUE THREAD

**Issue by ajashton** [openstreetmap/iD#3311]
The `emergency` key is sometimes used for tagging access of emergency vehicles\*. Values such as `yes`, `no`, `destination`, `designated` should not be area triggers.

\* I have no idea if this is a "correct" or "recommended" tagging approach, but `yes` is the [2nd most popular value](http://taginfo.osm.org/keys/emergency#values) for `emergency` and is causing issues for some downstream uses of https://github.com/osmlab/id-area-keys

**Comment by bhousel** [comment]
Hmm, yeah I can see how `emergency=yes` might be an issue.
We are basing this assumption based on presets from [emergency (facilities) wiki](http://wiki.openstreetmap.org/wiki/Key:emergency_(facilities)).

`landuse=yes`, `building=yes`, these are definitely areas..
But `emergency=yes`, not necessarily.  I think I can add a preset so that it gets blacklisted from the `areaKeys` list.

**Comment by manfredbrandl** [comment]
I doubt emergency=no to be reasonable. If access for Police car, Ambulance or fire patrol is neccesary and possible it will be allowed.

**Comment by pnorman** [comment]
The wiki describes this tag [very well](http://wiki.openstreetmap.org/wiki/Key:emergency)

> This is an ambiguous tag, and might have several meanings

On ways the most common is emergency=yes, most commonly found on [highways](http://taginfo.openstreetmap.org/tags/emergency=yes#combinations). There's a reasonable combination of emergency=yes access=no.

The next most common on ways is emergency=no which is [mainly found on](http://taginfo.openstreetmap.org/tags/emergency=no#combinations) amenity=hospital.

It is not often used to describe an emergency facility like an ambulance station, so about 90% of uses on ways are ones that shouldn't indicate an area.

**Comment by manfredbrandl** [comment]
So in case of emergency=no it should stay an area trigger?

**Comment by bhousel** [comment]
What I'm going to do is add dummy (not searchable) presets for _linear_ features with common `emergency` tags.  This will blacklist them from being included in the `areaKeys` datastructure.  

We'll still consider `emergency=*` to be area indicating.  (If we didn't, we would need to add `area=yes` to every emergency feature that was obviously an area, and that would be more annoying).

Again, a lot of this is based the [emergency (facilities) wiki page](http://wiki.openstreetmap.org/wiki/Key:emergency_(facilities)), which suggests that really anything can be tagged `emergency=*` and it's assumed to be a point/area.  The linear features are the exception even though they are very frequently occurring.
