### ISSUE TITLE
fields entry typeCombo not documented

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3319]
Some fields ([example](https://github.com/openstreetmap/iD/blob/d130c517b0a98c470aef269176bda729532f8ff1/data/presets/fields/barrier.json)) have a ` "type": "typeCombo"` which is not [documented](https://github.com/openstreetmap/iD/blob/master/data/presets/README.md). 
Is the readme old or are the presets wrong? :-)

**Comment by 1ec5** [comment]
Ah, good catch – and I just added a `networkCombo` type in #3302.

**Comment by bhousel** [comment]
I'll update this today!  There are a lot of field/preset settings that should be documented and aren't.
