### ISSUE TITLE
An error after saving changes

### ISSUE THREAD

**Issue by edpop** [openstreetmap/iD#3324]
There is an error here https://github.com/openstreetmap/iD/blob/master/modules/core/context.js#L143.

Most of services export objects with function _init()_, so it may be
```js
var reset = service.init().reset;
```
But nominatim's init() returns undefined and then _undefined.reset_ → error again.
So it needs some rewriting.

**Comment by bhousel** [comment]
Thanks @edpop, and sorry I thought I replied to this when you initially opened the issue.

yes we need to rethink the `init()` functions.

Originally the service code was implemented in closure-wrapped-modules, and in the move to es6 modules we couldn't think of a good way to preserve the old interface, whereby calling code would get access to the service through a function call.  This is something that we'll change before iD v2 lands.
