### ISSUE TITLE
Update name-suggestion-index

### ISSUE THREAD

**Issue by math1985** [openstreetmap/iD#3329]
The [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) has been updated again. In particular, the number of false hits (such as common nouns and misspellings) has been reduced.

Would it be possible to include the last version of name-suggestions.json in iD?

**Comment by bhousel** [comment]
> Would it be possible to include the last version of name-suggestions.json in iD?

Yes, lets move towards publishing the `name-suggestions.json` as a versioned npm package, then greenkeeper will keep it up to date for us, and we won't need to run `make suggestions` anymore.  I'll take care of it.

(Same with `editor-layer-index`, which is a bit more complicated as it's currently a Python project).

**Comment by math1985** [comment]
Great, thanks!
