### ISSUE TITLE
Problem with tag descriptions and wiki redirections

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#3337]
We were noticing that some key/tags don't have a proper description in iD, when using it in `pt_BR`
For example, a `highway=motorway` way is displayed with the `key:highway` description:

![](https://cloud.githubusercontent.com/assets/982338/17532379/ac3c2e7e-5e56-11e6-8c84-7125b942c4c4.png)

ie, it's displaying the description from https://wiki.openstreetmap.org/wiki/Pt-br:Key:highway instead https://wiki.openstreetmap.org/wiki/Pt-br:Tag:highway%3Dmotorway

And when trying to understand the problem we saw that https://wiki.openstreetmap.org/wiki/Pt-br:Tag:highway%3Dmotorway is actually a redirect to https://wiki.openstreetmap.org/wiki/Pt:Tag:highway%3Dmotorway (as can be see in https://wiki.openstreetmap.org/w/index.php?title=Pt-br:Tag:highway%3Dmotorway&redirect=no)

Could iD somehow detect such redirects and display the final wiki description?

**Comment by xendez** [comment]
Confirmed. In fact when is about a key pointing to a redirect page, it shows the message "There is no documentation available for this key" (in Portuguese, of course).

To replicate this: change the language in user preferences to "pt-BR", edit in iD, add a "source" key to any object and click in "i" to get the info. If we change the language in preferences to "pt" it shows the correct message. In the wiki, the page "[Pt-br:Key:source](http://wiki.openstreetmap.org/w/index.php?title=Pt-br:Key:source&redirect=no)" is redirecting to "[Pt:Key:source](http://wiki.openstreetmap.org/wiki/Pt-br:Key:source)". So iD is not using the redirect.

**Comment by bhousel** [comment]
Nice, looks like you found the linked issue in taginfo 👍   We get results from taginfo that say there is a wiki page, but the result is empty and has no description or image.

I'm not really comfortable with following the redirect and trying to scrape the wiki to get the updated documentation, but I can at least display a message to let the user know that there _is_ documentation for the tag, they just need to click through to the wiki to read it.

Here's what it looks like:

<img width="382" alt="screenshot 2016-10-25 10 58 49" src="https://cloud.githubusercontent.com/assets/38784/19691415/351a74d0-9aa2-11e6-858f-d6635667bd51.png">
