### ISSUE TITLE
Sometimes iD doesn't trim multiple consecutive spaces

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#3340]
I don't know how some users are able to do this (I did try to reproduce this problem), but sometimes I see users inserting names with multiple consecutive whitespaces.

For example, version 7 of this way https://www.openstreetmap.org/way/169886830/history (which was modified in https://www.openstreetmap.org/changeset/41179658)

`Rodovia␣Álvaro␣Brasil␣Filho␣␣␣␣␣␣␣␣␣␣SP-64`

**Comment by bhousel** [comment]
You're right iD doesn't trim multiple consecutive spaces.  Should we?

**Comment by naoliv** [comment]
Hum... actually I can reproduce it.
And I think that yes, they should be removed.
Is there any valid reason to have multiple consecutive spaces in object values?

**Comment by bhousel** [comment]
> Is there any valid reason to have multiple consecutive spaces in object values?

I don't know..  People can generally put whatever they want into OpenStreetMap.  Why try to prevent it?  Maybe some business out there really does have a lot of extra spaces in its name.

**Comment by naoliv** [comment]
If other tools count, osmose detects and warn about multiple spaces http://osmose.openstreetmap.fr/en/errors?item=5010&class=903 and JOSM also detects and fixes them

**Comment by pnorman** [comment]
Do any of the other editors have special handling for consecutive spaces?

**Comment by manfredbrandl** [comment]
I think most of the time multiple consecutive spaces are errourneous, so they can be delete if entered. In case it is really wanted we can keep consecutive spaces if entered in the key=value section at the bottom above relations. But how can users know that?

**Comment by homersimpsons** [comment]
I think that iD should not integrate checking tool, because:
- It should remain easy to use
- It is a web editor, then any checking tool will add data to download 
- Other software / web service do that 

If you want to indicate that there are multiple space, or a field value error (e.g. char instead of number), just show a little red cross at the right of the field value. User could put pointer over it to show what error type is it.

**Comment by naoliv** [comment]
> It should remain easy to use

What I was thinking will keep iD exactly as it is now for the user: it should remove the spaces after the user inputs the data (after pressing Enter, for example), without any warnings or anything else.

**Comment by bhousel** [comment]
I agree with @homersimpsons, let's include this idea in #2836.  The idea there is to highlight fields that look strange, rather than try to guess what the user wants to do and replace their values.

**Comment by naoliv** [comment]
Isn't it just better to silently remove the spaces instead unnecessarily highlight a field? (and make the user think "what did I do here?")

It's different to have a field with `yes;no` and a field with two consecutive spaces.
One is indeed an error and the other is a "cosmetic" issue.

All the times that I saw multiple spaces they were caused by the user accidentally pressing the space bar twice or trying to tag for the renderer (like the example in my first message, where he didn't know how to use `ref`)

**Comment by bhousel** [comment]
> Isn't it just better to silently remove the spaces instead unnecessarily highlight a field? (and make the user think "what did I do here?")

No.. That makes about as much sense as rewriting the text box on wikipedia.org to fix user's spaces.   Wikipedia has bots to check for little grammatical mistakes, and so should OSM.
