### ISSUE TITLE
Support custom icons

### ISSUE THREAD

**Issue by gmaclennan** [openstreetmap/iD#3346]
Similar to how the API currently supports other options for [customized deployments](https://github.com/openstreetmap/iD/blob/master/API.md#customized-deployments) it would be very useful to support custom icons associated with custom presets. Maintaining a fork for custom icons is challenging.

Potentially related: https://github.com/openstreetmap/iD/issues/3025

@tmcw this might already be happening as part of the refactor?

**Comment by bhousel** [comment]
Yes, #3025 was an idea related to this.. I'm not sure yet how we'll do it.
cc @jimmyrocks, who implemented a custom iconset for places editor - I know he was looking into this..

**Comment by sweco-semtne** [comment]
Is there any documentation on whats required to add custom icons besides what is described in #3025?
I mean if I were to add an icon to a custom build of iD, what is the current preferred way?

**Comment by bhousel** [comment]
We still use the `make` to compile assets like svg sprites. This will go away soon and be replaced with a node script or `npm run` command or something.

But for now I would:<br/>
1. Edit the `Makefile` to do the same thing we do to create the maki spritesheet:
```Make
MAKI_SOURCES = node_modules/maki/src/*.svg

dist/img/maki-sprite.svg: $(MAKI_SOURCES) Makefile
        node_modules/.bin/svg-sprite --symbol --symbol-dest . --symbol-sprite $@ $(MAKI_SOURCES)
```
...add some lines to do that for your own icons.<br/>
2. Then edit `modules/svg/defs.js` around [here](https://github.com/openstreetmap/iD/blob/master/modules/svg/defs.js#L103-L110) to import your icons into iD's `<defs>` svg element.<br/>
3. Then you can use them in iD, but that will require customization in different parts of the code that expect `maki` icons to exist.

**Comment by sweco-semtne** [comment]
Thanks for the great support. 
Is there a timeline for the refactor you mentioned?

**Comment by bhousel** [comment]
Closing this in favor of #3025 

Update: the Makefile is gone and we use npm scripts for building things now.
