### ISSUE TITLE
Crash when trying to edit "Black Sea"

### ISSUE THREAD

**Issue by verdulo** [openstreetmap/iD#3348]
When I tried to edit the "Black Sea", the browser starts using lots of CPU and memory and finally crashes. I checked multiple times, the problem occurs on both Firefox and IE; even changing background layer from satellite to "OpenStreetMap" or to "none" doesn't help.

**Comment by bhousel** [comment]
I'm not seeing any crash with the latest iD v2 beta, so hopefully this has been fixed.. Thanks for the report!
