### ISSUE TITLE
Presets - Swimming Pool - two presets for same thing

### ISSUE THREAD

**Issue by bgirardot** [openstreetmap/iD#3357]
When searching for a tag for an actual swimming pool, 3 presets are presented:

Swimming Pool (correct)
Swimming Pool Facility (not applicable)
Swimming Pool - Swimming Pool (adds name=Swimming Pool tag + amenity tag)

That last one should just go I think. I am not sure there should be a preset putting what the object is in to the name=* tag. At the very least it is a bit confusing which one to use "Swimming Pool" or "Swimming Pool - Swimming Pool"

![2016-08-16_22h14_54](https://cloud.githubusercontent.com/assets/265831/17714351/a942bc5c-63ff-11e6-92de-45d158fe18a0.png)

**Comment by bhousel** [comment]
Oh yeah - that third preset "Swimming Pool - Swimming Pool" was coming from the `name-suggestion-index` project.  This is supposed to be a list of chain stores or restaurants, but sometimes generic features sneak into there.

It looks this was already fixed this 9 days ago, so it should be filtered out in the next version of iD:
https://github.com/osmlab/name-suggestion-index/commit/0ed1dc3a2e54cfc0df0fe6d29f766a501b7bd7a5#diff-97a1954be10650d8cda311a27d2bd2afR383

**Comment by boothym** [comment]
I assume it's the same problem for all of these schools?
![sch](https://cloud.githubusercontent.com/assets/16965772/17769894/d52bdf90-6532-11e6-93a5-53084562e290.jpg)

**Comment by bhousel** [comment]
> I assume it's the same problem for all of these schools?

Yes, looks like those generic schools were removed from the index in the same commit:
https://github.com/osmlab/name-suggestion-index/commit/0ed1dc3a2e54cfc0df0fe6d29f766a501b7bd7a5#diff-97a1954be10650d8cda311a27d2bd2afR357
