### ISSUE TITLE
Imagery.json API / schema documentation incorrect

### ISSUE THREAD

**Issue by gmaclennan** [openstreetmap/iD#3359]
The [API docs](https://github.com/openstreetmap/iD/blob/master/API.md#imagery) state that custom imagery definitions should follow the structure defined by [editor-layer-index](https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json) however, it doesn't. `data/imagery.json` uses the `template`, `scaleExtent` and `polygon` properties which are not defined in that schema. It would be good to have updated docs about what the schema actually is.

**Comment by bhousel** [comment]
I'm updating the API docs today to include a note that iD's imagery structure doesn't match editor-layer-index.  I'll leave this issue open, because I agree we should document it better, or possibly change our structure to match editor-layer-index more closely.

**Comment by bhousel** [comment]
> I'll leave this issue open, because I agree we should document it better,

nevermind what I said here, I just updated the docs and closed the issue..
