### ISSUE TITLE
farmyard=kraal/motebo???

### ISSUE THREAD

**Issue by hakuchi** [openstreetmap/iD#3365]
what are this keys?
farmyard=kraal and farmyard=motebo is not a tagging what have any proposal or site with a description in the Wiki.
This is not an English word and therefore not OSM Standard.
I'm not able to translate these keys in a other language
Why is iD using this nonsense keys?

**Comment by boothym** [comment]
farmyard=motebo seems to have come from http://wiki.openstreetmap.org/wiki/WikiProject_Lesotho#Special_Lesotho_Content - e.g. http://www.openstreetmap.org/way/436120587

**Comment by bhousel** [comment]
Thanks for the report @hakuchi, iD does not have presets for these things.  If these tags were added by an iD user, then that user was using the raw tag editor, which allows them to type anything that they want to.

**Comment by hakuchi** [comment]
@bhousel if I tip in farmyard, iD give me in the scroll down menu the option to select Kraal/motebo/and other.
![iD immage](http://fs5.directupload.net/images/user/160819/xc2is368.jpg)

**Comment by bhousel** [comment]
@hakuchi, yes - these values are just the most popular ones that we get from taginfo.

http://taginfo.openstreetmap.org/keys/farmyard#values

It's not a very established tag.

value|count
---|---
yes|66
stables|17
dunghill|12
motebo|12
livery|5
poultry|2
kraal|2
equestrian|1
abandoned|1
corn|1
disused|1
horse_farm|1
mill|1
pisiculture|1

**Comment by hakuchi** [comment]
Oh...ok...so this is not a error inside the code from iD.
Sry
