### ISSUE TITLE
Use brand=* instead of name=* for some presets, add brand=* for hotels

### ISSUE THREAD

**Issue by Codain** [openstreetmap/iD#3371]
Most of the presets are based according to the name tag and not to the brand tag. This prevent the use of a full name (which allows to disambiguate between different amenities in the same area) for the benefit of the brand generic name.

For instance, an hotel of the Holiday Inn brand is usually tag like this:

```
name=Holiday Inn Phoenix West
brand=Holiday Inn
```

But presets encourage to set simply `name=Holiday Inn` and never set the brand tag.

Is it possible, for hotels, gas stations, restaurants, to set the brand tag instead of the name tag? This implies that the brand tag appears in the list of fields for those amenities.

**Comment by bhousel** [comment]
see also #2300

**Comment by bhousel** [comment]
done in #4907
