### ISSUE TITLE
double TypeError in showErrors()

### ISSUE THREAD

**Issue by edpop** [openstreetmap/iD#3373]
There is an error:
https://github.com/openstreetmap/iD/blob/master/modules/modes/save.js#L243
```js
function showErrors() {
    var selection = confirm(context.container());

    history.pop();
    loading.close();

    selection
        .select('.modal-section.header')
        .append('h3')
        .text(t('save.error'));

    addErrors(selection, errors);
    selection.okButton();
}
```
```context.container()``` returns Object, but ```confirm()``` needs a String, so user see alert message: "object Object"

After press "OK" or "Cancel" selection is a Boolean, then we get next TypeError:
```js
(true|false)
    .select('.modal-section.header')
```
Perhaps you meant to use another function instead of ```confirm()```

**Comment by bhousel** [comment]
I think line 3 needs to import it from `ui` module:

`import { Conflicts, confirm, Commit, Loading, Success } from '../ui/index';`
