### ISSUE TITLE
Don't force users to write text in changeset comments

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#3374]
It wouldn't make them write a Good change-set comment, but any string.

You couldn't make them more meaningful if users do not agree with 
http://wiki.openstreetmap.org/wiki/Good_changeset_comments
for every of their edit

Yes comments are strongly advised #2923 #2938 but not mandatory for every of your edit. Change-sets without comments will displayed as "uncommented" at osm.org.

**Comment by tmcw** [comment]
Previously

> It would be nice to suggest editors to provide a few words about what they were thinking they were doing. - May 2013 #1488 

> Maybe, if the user clicks on save without entering a comment, we could have a popup to nag him/her a bit more? - September 2014 #2370

> I propose that the upload dialogue tells the user that changeset messages are useful and should not be omitted before prompting the user to go back and add one or continue without. - Feb 2014 #2118

There are ~20 issue comments on this topic. This is an opinionated area but the majority opinion is decided in favor of requiring comments, so closing here. Unfortunately we can't make everyone happy with respect to features like this one.

**Comment by alexkmbk** [comment]
In my opinion, this issue makes sence. If you force users to comment while they don't have anything to say, then they will write some useless words just to get rid of this "stupid rule".

**Comment by tmcw** [comment]
Yep, about 3 people have agreed with this viewpoint about 9 have rallied for the opposite viewpoint. I respect your opinion, but it's in the minority and if we implemented your desire, we'd get another round of complaints from the other camp. Alas, in cases like this, a majority is our best signal.

**Comment by bhousel** [comment]
> If you force users to comment while they don't have anything to say, then they will write some useless words just to get rid of this "stupid rule".

You're right that some users will always write something useless just to quickly advance past the dialog box.  We know and accept that.

However one of the main design goals of iD is to guide new OpenStreetMap contributors towards good habits.  So for this reason, we'll always prioritize the needs of a user who _has never edited a map before_ over those of a user who simply wants to shave a few seconds off their editing time.

**Comment by alexkmbk** [comment]
> some users will always write something useless just to quickly advance
Well, I feel ashamed, because I am one of those users, to tell the truth

**Comment by d1g** [comment]
@bhousel, @tmcw fair close, okay let's not continue discussion No21, not worth it. But i wanted to show there opposite site of this (ein zweischneidiges Schwert)

http://www.openstreetmap.org/user/Anto110/history "правки", "правки", ...
https://www.openstreetmap.org/changeset/41433054 - alexkmbk "но при добавлении простого объекта, вроде родника или дороги, описывать это кажется лишним. " (when you add something trivial, like a spring, comments are superfluous)
