### ISSUE TITLE
Feature Suggestion: Flip

### ISSUE THREAD

**Issue by Treemanhero98** [openstreetmap/iD#3375]
I would like to suggest a feature which mirrors (vertical or horizontal) selected structures, especially buildings.
Is this possible to implement it into the editor?

**Comment by bhousel** [comment]
Yes, definitely possible.  Flip Horizontal / Flip Vertical are tools that people are accustomed to seeing,  from working with other vector drawing tools.  This is not a priority for iD, but I'll leave this open as a "maybe someday".

**Comment by slhh** [comment]
I don't see a real usecase of flipping existing objects, but in case of copying objects flippng could be useful. Some keys could have a special function in order to flip, rotate, or scale the copied object in the period between pressing Ctrl-V and placing the copied object by mouse click.

**Comment by bhousel** [comment]
Yes, the main usecase would be for copy/pasting of symmetrical building outlines.

<img width="609" alt="screenshot 2016-08-26 01 33 34" src="https://cloud.githubusercontent.com/assets/38784/17995142/33d5d244-6b2d-11e6-8523-848de0869eb1.png">

**Comment by bhousel** [comment]
This was done in #3375 (thanks @Psigio!)
Try it out in the mirror:  http://openstreetmap.us/iD/master
