### ISSUE TITLE
Auto-complete of genus tag values are incorrectly cast to lowercase

### ISSUE THREAD

**Issue by SK53** [openstreetmap/iD#3377]
A recent post on the tagging mailing list suggests that iD is automatically changing or auto-completing values of the key genus to lowercase values (see https://lists.openstreetmap.org/pipermail/tagging/2016-August/029889.html). A quick experiment shows that this is the case for autocompletion at least.

This is incorrect. Genus names **must** begin with a capital letter as they have since Linnaeus' day. The form of biological names are mandated by the ICZN & ICBN nomenclature codes. Technically a name in lowercase has not meaning.

This is non-trivial as when genus values are populated matching to external lists of valid generic names is the single best QA for these values, and particularly because people frequently add non-scientific names for genera in the field, such as oak, lime, ash.

This key should behave in exactly the same way as name, operator, architect, owner, etc.

Related keys species, taxon, taxon:*, dominant_taxon etc should also behave in the same way.

**Comment by bhousel** [comment]
This is in the raw tag editor value field, right?  Can you send a screenshot?

**Comment by SK53** [comment]
Yes exactly so. Example is when typing "Q" for "Quercus"

![screenshot 17](https://cloud.githubusercontent.com/assets/5452818/17977404/8a55f250-6ae9-11e6-9c7a-835f16ddf401.png)

**Comment by 1ec5** [comment]
#3280 may help, but indeed, when the first taginfo match happens to be lowercase, the entered text becomes lowercase too. At the application level, most autocompletion implementations either revert to the manually input case when rejecting the suggestion or keep the manually input case intact until the suggestion is accepted.

**Comment by SK53** [comment]
This may be my ignorance, but I thought that iD took most popular values from taginfo. Quercus for instance out-numbers quercus by about 250-fold (10k+ vs. 39) and therefore _ought_ to be the value presented for auto-completion.

**Comment by bhousel** [comment]
> This may be my ignorance, but I thought that iD took most popular values from taginfo. Quercus for instance out-numbers quercus by about 250-fold (10k+ vs. 39) and therefore ought to be the value presented for auto-completion.

That's true, but we have special logic in `taginfo.js` to say that when multiple search results are returned that differ only in case, to keep only the lowercase one.

For most fields in OSM (`cuisine`, `religion`, `denomination`) it's the behavior we actually want.  
e.g. prefer "french" instead of "French"... prefer "catholic" over "Catholic".

The taxonomy fields are the oddball ones, and need to be whitelisted like @1ec5 suggested - he's right because he just introduced similar logic for `network`.

**Comment by SK53** [comment]
@bhousel Thanks for clarification, makes a great deal of sense.
