### ISSUE TITLE
Bug when attaching trees to row of trees and the save

### ISSUE THREAD

**Issue by airotz** [openstreetmap/iD#3378]
I get an error when attaching trees (as nodes) to a tree rows (as line). When I try to save the modifications, I get the following error:

Version mismatch: Provided 1, server had: 2 of Node 4366696998
Server returned status code 409

I am using the in-browser editor iD.

Best regards,
Igor

**Comment by pnorman** [comment]
Because you conflicted with yourself this looks like a case of #1646

**Comment by bhousel** [comment]
Agree w @pnorman, this is likely an outlier issue that will probably get better after we process diff upload results.
