### ISSUE TITLE
Add "Campground" Type in Area

### ISSUE THREAD

**Issue by rlerner** [openstreetmap/iD#3385]
When outlining a campground (an area with several sites), I've seen several areas marked simply as "camp site", which is almost the equivalent of a "lot" in a "neighborhood"

Generally, these collections should be campgrounds and the individual parking pads/areas are camp sites.

Would like to see the addition of a "campground" type in areas, and possibly points.

**Comment by boothym** [comment]
Can you please give an example?

**Comment by rlerner** [comment]
Here's two:

ILSB: https://www.openstreetmap.org/edit#map=17/42.43578/-87.80754
Indiana Dunes: https://www.openstreetmap.org/edit#map=17/41.65950/-87.05485

**Comment by bhousel** [comment]
Looks like the tag is http://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcamp_site
and it is a point/area type for the _perimeter_ of the camp ground.

Camp Pitches could be tagged with the proposed:  `camp_site=camp_pitch`
http://wiki.openstreetmap.org/wiki/Proposed_features/camp_site_pitch
I'd prefer not to add a preset for camp pitch unless there is significant tagging of these already in osm (taginfo would tell us these numbers, but it's currently down)

**Comment by bhousel** [comment]
update now that taginfo is back up..
`camp_site=camp_pitch` has [1300+ uses](http://taginfo.openstreetmap.org/tags/camp_site=camp_pitch), which is good enough for me.

**Comment by bhousel** [comment]
Closed with these:
1692f5e Rename "Camp Site" to "Campground"
8cd2d70  Add preset for `camp_site=camp_pitch` for individual pitches 

We did have the "Camp Site" tag already, but I renamed its label to say "Campground" to make it clearer that it is for the overall area.. Then I added "Camp Pitch" preset for tagging individual pitches.

**Comment by boothym** [comment]
I assume we can change it back to camp site for the  en-gb translation?

**Comment by bhousel** [comment]
Yes, definitely.. we can change it on transifex tomorrow after the nightly job picks up the update.

**Comment by bhousel** [comment]
> I assume we can change it back to camp site for the en-gb translation?

FYI, I did this, it should show as "Camp Site" in `en-GB`

**Comment by rlerner** [comment]
Thanks for getting this added into OSM!
