### ISSUE TITLE
Railway crossing - pedestrian

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3395]
I notice there's no preset for a pedestrian railway crossing https://wiki.openstreetmap.org/wiki/Tag:railway%3Dcrossing

How should the preset be named and represented in the editor: Railway crossing (pedestrian) and a cross icon like level_crossing?

**Comment by bhousel** [comment]
> How should the preset be named and represented in the editor: Railway crossing (pedestrian) and a cross icon like level_crossing?

Yes, that sounds good.  I've never understood why OSM has 2 different tags for this.

Maybe name them like:

`railway=crossing` - "Railway Crossing (Path)"
`railway=level_crossing` - "Railway Crossing (Street)"

Both can use the cross 'X' icon.
