### ISSUE TITLE
German translation erroneous

### ISSUE THREAD

**Issue by DeBukkIt** [openstreetmap/iD#3416]
The tag _amenity=fire_station_ leads to the German translation "Feuerwehrmagazin". This is simply wrong. "Feuerwehrmagazin" is actually a commercial magazine (= journal, periodical, review, serial) and totally out of place.
The correct translation for "fire station" is "Feuerwache" or "Feuerwehrgerätehaus", which is also possible, but much longer.

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/ideditor/id-editor/dashboard/) and you can fix this yourself if you sign up for an account there.
