### ISSUE TITLE
Should not offer crossing=zebra in presets

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#3418]
(Yes, I know that it was "discussed" in #2918 and #3049)

And I guess you will also close this ticket as "iD didn't cause it; it's a valid tagging scheme; the problem is in OSM not in iD", but take a look at http://taghistory.raifer.tech/

![](https://cloud.githubusercontent.com/assets/982338/18476384/3326568a-79a0-11e6-9cce-8a0029816c4b.png)

iD should just not suggest `crossing=zebra` in the preset

**Comment by naoliv** [comment]
cc @d1g

**Comment by bhousel** [comment]
> And I guess you will also close this ticket as "iD didn't cause it; it's a valid tagging scheme; the problem is in OSM not in iD", but take a look at http://taghistory.raifer.tech/

You're right.  Invent a better tag for marked pedestrian crossings, and then we can revisit.
