### ISSUE TITLE
Batch Editing Mode to Speed Up Activities

### ISSUE THREAD

**Issue by eakers42** [openstreetmap/iD#3422]
A batch editing mode that does a couple things would speed up the adding of buildings.
1) Have an automatic "square corners" option when the "area" is finished
2) Preset the feature being edited. 

For example, the map I am working in has few residential buildings marked. I hit shortcut "3" for area, click the area, then click the Residential Building feature, then click the area and select "square corners". This is done over and again.

Instead, it would be nice if upon completion of the area, the preselected feature (Residential Building in this case) is already selected, and the square corners option is applied.

**Comment by eakers42** [comment]
It could be generalized to apply any field, like part of the address, state, and zip code.

**Comment by slibby** [comment]
just came here to :+1: this -- would be quite helpful for HOT tasks where tracing buildings is the primary task. Not sure about squaring automatically (there's much debate there) but could be an optional check-box.

**Comment by eakers42** [comment]
I don't think squaring corners should be required, but one of the options one could set if they wish to. There may be other parameters that could automatically be set as well. 

Or possibly, the square corners could be added as a shortcut. Would still make adding buildings easier.

**Comment by bhousel** [comment]
Lots of these ideas are covered on existing issues.. See #528, #590, #839, #1761
