### ISSUE TITLE
Not Show In Street map ? I can not edit Here 

### ISSUE THREAD

**Issue by Mosarof1** [openstreetmap/iD#3436]
Here Not Show In Street map ? I can not edit Here for This Problem.  https://www.openstreetmap.org/edit#map=15/24.6152/90.4857  Bangladesh Mymensingh Trishal Kanihari area.

**Comment by bhousel** [comment]
Thanks for the report.. You can click "B" to open the Background Settings and select other sources of imagery.  I see that Mapbox Satellite looks ok here, even though Bing is blurry.

<img width="197" alt="screenshot 2016-09-18 23 22 27" src="https://cloud.githubusercontent.com/assets/38784/18621853/d0fdd4d2-7df6-11e6-89b2-db3d72e66258.png">


Also please see [this FAQ item](https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery) on how to report issues with Bing and Mapbox imagery.

iD's background imagery sources come from the [editor-layer-index](https://github.com/osmlab/editor-layer-index) project.  If you know of a better imagery source that is licensed for this use, please open a request there with the link and license details.
