### ISSUE TITLE
add some more tags to your tag database

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#3439]
I suggest adding these tags to your tag database:
KEYS:
- ref:vatin
- service_times
- source:maxspeed
- tomb
- historic:civilization
- start_date
- alt_name
- old_name
- oven

VALUES:
- historic=road / roman_road

**Comment by bhousel** [comment]
Hey @dieterdreist, thanks for the suggestions.. iD doesn't really have a tag database.  OSM tags can be edited in the "All Tags" section of the editor, and iD will perform lookups using the taginfo service to suggest common keys and values.

Most users of iD interact with _presets_, which are common features that have the tags already set up for them.  The presets have _fields_, which are additional optional tags that appear in the sidebar.

If you think there are additional presets or fields that iD should support, could you revise this ticket?  It's also helpful to link to taginfo and the osm wiki, so that the iD developers can understand better what the tags are.

**Comment by dieterdreist** [comment]
I am not sure if I understand you correctly, because I have noticed that some tags are autocompleted and others aren't, and this is likely not based on usage alone, maybe there is kind of a blacklist? I am sure there is some human judgement involved, and I agree it is necessary because of inports distorting usage numbers. I am particularly interested in getting the ref:vatin tag supported (vat identification number of a business) and the source:maxspeed (formalized way of storing the reason for a maxspeed, like sign (explicit), or zones for implicit limits), the latter being used very frequently (almost a million usage). This iD tag list is used also in other editors like GoMap!! for iOS.

**Comment by dieterdreist** [comment]
What is your threshold for tag usage in order to consider a tag established/in use? Is it different for keys and values, and does it matter whether a tag is documented?

**Comment by dieterdreist** [comment]
As for your suggestion to add tags to the presets: any "historic" preset should likely have an historic:civilization field, at least those regarding old stuff (unlike memorials and monuments which often are recent but connected to history).
Any place of worship should offer a service_times field
Any shop and craft and maybe office and some amenities (e.g. fast food, pub, restaurant, cafe, bar) should offer a ref:vatin field
Any feature could have a start_date field
Any highway for vehicles a maxspeed and source:maxspeed field
tomb could be a new preset or extension of historic=tomb
oven=wood_fired/electric could be an extension for cuisine=pizza and shop=bakery

**Comment by tbertels** [comment]
See also #1554

**Comment by dieterdreist** [comment]
there is a problem with ref:vatin, it has 7700 uses currently but doesn't get autocompleted. Is it possible iD doesn't do autocompletion for ref-subtags in general? The vatin stands for VAT identification numbers, and (unlike many other ref subtags) has not been introduced via imports. The tag is also documented in the wiki on a key-page

**Comment by bhousel** [comment]
> there is a problem with ref:vatin, it has 7700 uses currently but doesn't get autocompleted. Is it possible iD doesn't do autocompletion for ref-subtags in general?

iD does autocomplete this tag, but you need to type up to `ref:v` first:
<img width="373" alt="screenshot 2017-02-26 07 37 24" src="https://cloud.githubusercontent.com/assets/38784/23339744/8a8fd968-fbf6-11e6-8d1c-38e52383c3ef.png">

7700 uses just isn't all that many compared to the other tags that match `ref:`

**Comment by bhousel** [comment]
I added a bunch of these..
- alt names are covered by #1554
- `ref:vatin` - Not sure how I would explain this to most users, so I didn't add it
- `service_times` - added 23f9431
- `source:maxspeed` - not added for now, not sure how to explain it, also highways are already pretty cluttered with fields
- `tomb` - added 0c1194b
- `historic:civilization` - added 4d64028
- `start_date` - added ec0e9c5
- `oven` - really limited use so didn't add it yet.  Also we don't have a special preset for pizza places.

**Comment by dieterdreist** [comment]
sent from a phone

> On 2 Mar 2017, at 05:18, Bryan Housel <notifications@github.com> wrote:
> 
> ref:vatin - Not sure how I would explain this to most users, so I didn't add it


tax identification number (VAT ident. number)
