### ISSUE TITLE
icon source for art(work/-gallery)

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3440]
OSM carto are looking to add an icon for shop=art, and I remembered iD has a similar one for tourism=art-gallery and artwork: https://github.com/gravitystorm/openstreetmap-carto/issues/2350

Couldn't find the "art-gallery" icon specified in presets anywhere in the repo - are you able to provide an svg source for it?

**Comment by bhousel** [comment]
Sure, this preset uses the Maki `art-gallery` icon.

The current version of Maki is here: 
 https://github.com/mapbox/maki/tree/master/icons

iD still uses an older version of Maki, which I have mirrored here:
 https://github.com/bhousel/maki/tree/mb-pages/src
