### ISSUE TITLE
Add shop=pastry

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#3444]
See https://wiki.openstreetmap.org/wiki/Tag:shop%3Dpastry

**Comment by Dgleish** [comment]
I'd quite like to tackle this one. It seems there are plenty of examples to draw from.
Should I add patisserie as a term even though pâtisserie is the correct French? It is more widely used in common English (eg _ Valerie)

**Comment by tbertels** [comment]
Yes, [it seems to be used in UK](https://en.wiktionary.org/wiki/patisserie#English), so I think you can definitely add it.
