### ISSUE TITLE
Resizeable / Responsive sidebar

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#3447]
for many tags the space is not sufficient to show the content (in the all tags view). See screenshot: 
![screen shot 2016-09-23 at 12 30 18](https://cloud.githubusercontent.com/assets/581288/18783056/f6d68ba4-8189-11e6-8a71-50402a99754b.png)

Why not allow users to resize the left column?

**Comment by dieterdreist** [comment]
alternatively the amount lines could be increased when needed. Otherwise checking what is there or what you have entered yourself becomes a real pain, e.g. opening hours, website, addr:street. 
Maybe the space the trash bin and the "i" take up could be reduced alternatively? The right margin up to the end of the left column could also be minimized.

**Comment by anushasingh** [comment]
Hello! Can I work on this issue?

**Comment by quincylvania** [comment]
Working on this.

**Comment by amchew** [comment]
Thanks @quincylvania ! +1 to @dieterdreist 's request.
