### ISSUE TITLE
Add support for JOSM backgrounds based on location

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#3450]
Support for location specific [JOSM backgrounds](https://josm.openstreetmap.de/wiki/Maps) should be added to iD.
Then, when editing a specific location, the backgrounds relevant to that location would be offered to the user, like it is with JOSM.
Each location specific background has a `<bounds>` property allowing the editor to select the relevant backgrounds.

**Comment by maxerickson** [comment]
iD has a similar feature, pulling sources from https://github.com/osmlab/editor-layer-index .

Most of the difference is that there is not yet support for some types of backgrounds in iD https://github.com/openstreetmap/iD/issues/1141 .

**Comment by bhousel** [comment]
Yes, if there are backgrounds available for tracing that don't yet show up in iD, Potlatch, Vespucci - the correct place to add them is the editor-layer-index project @maxerickson linked to above.  PRs welcome!

There is a related ticket in that repository about the JOSM imagery list:  https://github.com/osmlab/editor-layer-index/issues/88 

We don't have any tools for updating the JOSM list from editor-layer-index, or vice versa, or for link checking any of the imagery sources (they go stale sometimes).  Lots of room for improvement here for someone who wants to take this up.  For now, the lists are both manually curated.
