### ISSUE TITLE
Add Keep Right integration as new layer for QA data fixing

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/iD#3452]
[KeepRight](http://wiki.openstreetmap.org/wiki/Keep_Right) [1] provides excellent analysis of common errors such as connectivity errors, floating islands, etc.

It would be useful to get this integrated as a tickbox-enabled layer, as per Mapillary. This would bring to the forefront these kinds of errors.

[KeepRight recently added GeoJSON output](https://github.com/keepright/keepright/issues/52), with the relevant server headers, so at a technical level this should be feasible:

Note that this ticket is not asking for automated spotting of user problems while editing - this is specifically about bringing visibility of already-spotted errors into a centralised location where editors are already going, i.e. iD, rather than assuming they will find these other locations on the web.

**Comment by bhousel** [comment]
Nice!  Yeah we talk about Keepright occasionally on the iD issue list (I'm a big fan), but we don't have a specific ticket for it yet.  I totally support the idea of QA overlay layers in the map data panel.

**Comment by bhousel** [comment]
Tagging @thomas-hervey - this would be a great issue to tackle once the OSM Notes feature #5107 is merged and stable 👍

**Comment by bhousel** [comment]
This happened!  #5201
