### ISSUE TITLE
Use delete key as a delete shortcut

### ISSUE THREAD

**Issue by aibaraiduas** [openstreetmap/iD#3455]
The simplest delete shortcut is the key with that same name, without using a modifier key. It would be great to be able to use that to delete nodes, etc. Ctrl/Cmd+backspace could be kept as well since Mac keyboards don't have a dedicated delete key.

**Comment by bhousel** [comment]
#1698 has a lot of background on the decision to add the modifier for deleting..

So I agree we should keep the modifier for Windows Backspace / Mac Delete - but I'm ok with dropping the modifier for Windows Delete (i.e. keyboard with a dedicated delete key off to the side).
