### ISSUE TITLE
Path offers selection of IMBA Trail Difficulty, but feature is abandonned

### ISSUE THREAD

**Issue by st-anton** [openstreetmap/iD#3467]
Selection of highway=path offers three selections for difficulty:
hiking
mtb
IMBA
The last feature is marked abandonned, so it might be removed for selection (?)

**Comment by bhousel** [comment]
Thanks @st-anton, can you point me at a discussion where it was deprecated?  As far as I can tell the tag looks to be still used.

**Comment by st-anton** [comment]
Here it is: http://wiki.openstreetmap.org/wiki/Proposed_features/IMBA_Trail_Difficulty_Rating

**Comment by bhousel** [comment]
> Here it is: http://wiki.openstreetmap.org/wiki/Proposed_features/IMBA_Trail_Difficulty_Rating

That's just an abandoned proposal.. The tag is used about 16k times in the database.. 
Did anyone tell you that they want the tag deprecated for some reason?

**Comment by st-anton** [comment]
No, I just saw the abandonned marking in the proposal. This confused me.
That means, the tag is - more or less - accepted and can be used. It would be helpful to update the wiki page.
