### ISSUE TITLE
allow disconnecting connections if only one of two segments is part of relation

### ISSUE THREAD

**Issue by joostschouppe** [openstreetmap/iD#3468]
When you want to disconnect a road from another road at their junction, this is not allowed. That often makes sense. It isn't when the road with the relation is not split up at the junction (so just one "way"), and the other road at the T junction is not part of any relation.
I'm also missing a "trust me, I know what I'm doing" button :)

**Comment by bhousel** [comment]
I think what you're describing is covered by #2929

**Comment by joostschouppe** [comment]
@bhousel thanks, that's correct, with regards to the last sentence.

The rest of my message isn't addressed there though: this is talking about a false positive in the relation protection mechanism.

**Comment by bhousel** [comment]
> The rest of my message isn't addressed there though: this is talking about a false positive in the relation protection mechanism.

To be honest, I didn't really understand the rest of your message.  Can you point me to a specific junction in osm or draw a picture to make it clear?  I split junctions at T's all the time.

**Comment by joostschouppe** [comment]
Can't seem to be able to reproduce this, don't know what happened here. So good on you for closing the issue...
