### ISSUE TITLE
User defined preset?

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#3470]
Since there are many issues related to preset, this one might be a duplicate of one I could not find.

The idea is that adding a preset to iD requires:
1. git / github skills to clone the repository, commit the new preset, do a merge request, etc.
2. development skills to run a local instance to ensure that the preset works as expected, etc.
3. patience! The preset, once merged in master, will be available in next release (usually 1/2 months).

Finally my last arguments (but I am unsure there are valid one ;-)):
1. Some preset maybe culture specific/country specific/not useful for the all users.
2. If you map something specific (let's say fire hydrants), usually you use "fire hydrant" preset + you set the `fire_hydrant:type` + ref. To save a clic, one could have 2 presets `pillar fire hydrant` and `underground fire hydrant`. Also usually `ref` key has a specific value per region (`PK01`, `PK02`, etc), so it could be pre-filled with a pattern (here `PK`).

Finally my idea would be to have a `Save as custom preset` button in the preset form, that would save the current preset form locally on user local storage with a user chosen text. Then a new main category could be shown on the left sidebar `User presets`, as the existing ones.

I did not evaluate the technical complexity of that idea, but in a first place I would like to know if anyone find this useful/if it could be integrated in iD.

**Comment by bhousel** [comment]
#5049 will allow users to replace the presets at runtime.  Once that is implemented, you could define your own presets in a `.json` file somewhere and use them instead of the builtin ones.

**Comment by stragu** [comment]
Shame https://github.com/openstreetmap/iD/issues/5049 hasn't been touched in about 7 years.
I agree this would be very useful. Example use case that makes me wish for it at the moment:

I am mapping residential areas with many private oudoor pools. I want to have a subtype of the Swimming Pool preset with `access=private` and `location=outdoor` so I don't have to tick these two properties every single time I trace one.

I imagine a button that says "Save as user preset", which would prompt to give a name to it, but also would keep track of which preset it was based on, in case that original preset changes in the future and so the user can be asked if they want to "upgrade the tags based on original preset".

I have the same wish for the rooftop solar water heaters I often trace (a modified rooftop solar panel).

**Comment by tordans** [comment]
Just to add a reference: Once we go down this road, we should check with GoMap which already has a custom preset system and stores them in the OSM user profile section (AFAIK). I could not find good issue to reference, but https://github.com/bryceco/GoMap/issues/599 is one.

AFAIK EveryDoor it trying to solve this issue with their new Plugin System but they also track https://github.com/Zverik/every_door/issues/784 about using JOSM presets.

**Comment by bryceco** [comment]
@tordans For a while I was storing custom presets (and other data) in the OSM user profile, but then switched to storing such data in iCloud where it is automatically shared across user devices, and is immediately available if you delete/reinstall the app or purchase a new device.
