### ISSUE TITLE
Add surface preset

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#3476]
See https://wiki.openstreetmap.org/wiki/Key:surface
Very widely used.

**Comment by bhousel** [comment]
iD does have a surface field on all of the highway presets: 

<img width="358" alt="screenshot 2016-10-04 16 32 45" src="https://cloud.githubusercontent.com/assets/38784/19091333/37928b1a-8a50-11e6-8636-1ff311bd863a.png">

Is there anything else you think we should add?

**Comment by tbertels** [comment]
Indeed, I was going to say it. :)
/data/presets/fields/surface.json

It just needs the equivalent of /data/presets/fields/fire_hydrant/type.json

**Comment by bhousel** [comment]
> It just needs the equivalent of /data/presets/fields/fire_hydrant/type.json

We only provide translations for the dropdown values in cases where the list of possible values is fixed.  That's why `fire_hydrant:type` is translated and does not allow users to type anything, but `surface` is untranslated and allows freeform entry.

See also #2708
