### ISSUE TITLE
Lateral Water Hazard preset adds natural=water to ways

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#3483]
The [Lateral Water Hazard](https://github.com/openstreetmap/iD/blob/d130c517b0a98c470aef269176bda729532f8ff1/data/presets/presets/golf/lateral_water_hazard.json) preset adds `natural=water` to ways. It should only add it to areas, so there needs to be a separate version for “line” geometry.

/cc @bhousel @MateoV

**Comment by bhousel** [comment]
I agree - [per wiki](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course), looks like `golf=water_hazard` and `golf=lateral_water_hazard` both work this way.
