### ISSUE TITLE
Add possibility to connect/disconnect lines

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#3486]
Currently if you need to connect/disconnect lines you have to connect/disconnect each node manually. It would be nice to have a possibility to do that easier.
For example to connect lines you connect the first node and drag and drop the last node while holding Shift key and the nodes in between would get connected.
The same applies for when drawing a new line over an existing one, i.e. you click on the first node and then click on the last node while holding Shift key and connected nodes in between would get created.
To disconnect lines you select the first connected node and click on the last connected node while holding Shift key and the nodes in between would get disconnected.

**Comment by bhousel** [comment]
I think what you're describing is covered in #1614
