### ISSUE TITLE
Please change language field text for Burmese ( Myanmar ) 

### ISSUE THREAD

**Issue by takhanapa** [openstreetmap/iD#3488]
Hi iD Developers,
For the language tag in web editor for OpenstreetMap
It is now for language of Burma ( Myanmar ) the characters as here " မြန်မာဘာသာ "
As you see this text at the end is " ဘာသာ" is unnecessary as it is " language " in Burmese.
The first group of text " မြန်မာ " should be replaced with correct language name " ဗမာ  ".
It is correctly sourced from : A good source for locale data is CLDR: http://www.unicode.org/cldr/charts/latest/supplemental/locale_coverage.html

So the only text for Burmese ( Myanmar ) language should be " ဗမာ "

Thank you for your attention.

**Comment by bhousel** [comment]
Yes, I agree we should use CLDR for our language source instead of Wikimedia.  Let's track this on issue #2457
