### ISSUE TITLE
I wanna contribute in documentation de.json - how can I do it

### ISSUE THREAD

**Issue by Seandebasti** [openstreetmap/iD#3490]
I am using ID for a long time. I like to improve the documentation for tags which are not available in the current ID version.
Especially ID...dist/locales/de.json (or the english version)
How can I add some tags (and images) in this json? I dont wanna fork the full code of ID just this json to get better information into ID Edit mode.
Thanks
Sebastian

**Comment by bhousel** [comment]
Great, we love help!  The things you are asking about come from a few different places:

* To add support for new tags in iD, you can open issues here for the tags you want to see added.

* To change the translations of the tags as they appear in iD, you can sign up for an account on [Transifex](https://www.transifex.com/ideditor/id-editor/dashboard/) and anybody can change the translations there.

* The tag reference documentation and image that pops up when you click the "i" button - these come from the [OSM Wiki](http://wiki.openstreetmap.org/wiki/Map_Features), so you can change those things by editing the wiki.
<img width="367" alt="screenshot 2016-10-09 10 28 02" src="https://cloud.githubusercontent.com/assets/38784/19221133/1c1ac258-8e0b-11e6-84e8-8e1e58e1e954.png">

Hope this helps, let me know if you have any other questions!
