### ISSUE TITLE
RTL text along SVG textPaths is wrong in Chrome

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3491]
Just re-ticketing this comment from @mapmeld so we don't lose track of it:
https://github.com/openstreetmap/iD/pull/3087#issuecomment-252453324

> Thanks! As for the question of Arabic labels on ways @marrouchi , it's a bug with how Chrome displays text along a path using SVG textPath; it works in Firefox. So there isn't much iD can do (I tried adding lang, dir, other attributes and it wouldn't budge): 
> http://stackoverflow.com/questions/31362171/how-to-use-svg-textpath-in-persianrtl-text
> https://bugs.chromium.org/p/chromium/issues/detail?id=379149

Thanks @mapmeld for tracking this down.. We can keep an eye on the issue and close once it's fixed upstream.

**Comment by miladkdz** [comment]
I have an intial fix for this. Can I send pull-request?

**Comment by bhousel** [comment]
> I have an intial fix for this. Can I send pull-request?

Yes please!

**Comment by bhousel** [comment]
closed in #3707!
