### ISSUE TITLE
Add possibility to redraw

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#3492]
There is always space for improving geometries and sometimes it is much easier to redraw than to fix corners. It would be nice to have a hotkey and/or a menu item for that.

**Comment by bhousel** [comment]
I think what you are describing is covered in #1711

**Comment by yaugenka** [comment]
No. I'm saying about possibility to clear the entire geometry and start drawing it anew. Definitely you can delete the object and create a new one, but in you would loose the tags and history then.

**Comment by bhousel** [comment]
I still think we could handle this in #1711, if its what I'm thinking.  The idea there is that you would hold down a modifier key and click the map, and it would intelligently add new points and delete existing (uninteresting) points on the selected geometry.
