### ISSUE TITLE
Automatically convert phone numbers

### ISSUE THREAD

**Issue by rugk** [openstreetmap/iD#3495]
When entering [`phone`](https://wiki.openstreetmap.org/wiki/Key:phone) key (or `fax`) this number should automatically be converted into international format (E.164) and spaces should be added. Mobile phone (dialer) apps are quite good in this. :smile:

**Comment by bhousel** [comment]
Sure, I think [node-phone](https://www.npmjs.com/package/phone) can do this for us.

**Comment by pnorman** [comment]
👎 on following E164, as that only used in some regions in OSM

**Comment by bhousel** [comment]
> 👎 on following E164, as that only used in some regions in OSM

What's the harm?  Isn't it better to have consistency?

**Comment by rugk** [comment]
Really? But it is described as vest practise in the English wiki article (which I thought applies international).
In any case I'd also say consistency is good and an international standardised format is a good choice here.

**Comment by pnorman** [comment]
> What's the harm? Isn't it better to have consistency?

Because iD would be forcing a format which is inconsistent with other phone numbers mapped.

**Comment by bhousel** [comment]
eh, not worth arguing about this.. closing.

**Comment by rugk** [comment]
What? You was the one arguing for this feature. Please reopen. It is certainly worth.

**Comment by bhousel** [comment]
@rugk I think it's a good feature, but it's not worth arguing with @pnorman about it.  

Instead of having defined tagging that works everywhere, OSM has evolved tagging practices that are region specific.  It really limits the overall usefulness of the project, but... OSM gets what OSM wants.

**Comment by rugk** [comment]
Come on, you really care about one user here?
I'd say we currently have a 2:1 situation. Two people are in favour of this, one is against it.

I mean if you want to stay with regional-specifics than make it a regional feature, so it is only possible to disable/enable it in specific regions.
Also we should certainly hear more opinions on this.

**Comment by rugk** [comment]
For more opinions [I've asked here](https://gnusocial.de/notice/8257460).

**Comment by bhousel** [comment]
> Also we should certainly hear more opinions on this.

I would definitely be interested in hearing opinions from developers who are consuming phone number data from OSM.

**Comment by rugk** [comment]
I think until you get more feedback, you should open this issue. (So users know it is not fixed/done yet.)

**Comment by slhh** [comment]
The phone number field could have an E164 checkbox for autoconversion. When adding a phone number it could be set by default, at least for regions where applicable. In case of existing objects with phone numbers not matching the standard it should be unset by default. The user can set the checkbox in order to convert existing numbers, or unset it to enter non-standard numbers.

**Comment by rugk** [comment]
Yeah, maybe this is good.
In any case, please reopen this issue, @bhousel.

**Comment by bhousel** [comment]
> In any case, please reopen this issue, @bhousel.

No, my reading of @pnorman's comment above is that people are happy with phone numbers being tagged according to regional convention and not according to E164.  Considering this a WONTFIX issue for now.

**Comment by rugk** [comment]
My reading of @slhh's and @rugk's comment is that it is suggestest to implement this as an optional/regional-dependent feature. I don't know whether these users can say, how happy other users are, but they can both say that they suggested this and their suggestion seems to be ignored. They consider this as a "I have not read your comments" for now until it is reopened.

**Comment by tmcw** [comment]
@rugk & @slhh please take a breath and remember to be kind to your friendly project maintainer. There are many issues that @bhousel needs to keep track of.

While you may have the time and energy for a lively debate about the pros & cons of telephone formatting, it's quite reasonable and good for a maintainer's time and happiness to avoid contentious issues about minuscule details in favor of less contentious issues about larger issues.

If you'd like to submit a PR implementing an opt-in telephone formatting patch, and feel you can implement it in such a way as to make both sides happy, we're happy to review it and accept it if it does indeed meet that purpose! That would certainly be a way to move this need along in a positive, happy direction. In terms of this issue, it has clearly become more of a complaint than a suggestion, so I'm locking it to maintainers-only. Again, happy to accept a contribution if you'd like this to happen.
