### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3501]
I get a ENOENT error no such file or directory with packages.json. Anyone got that before?

**Comment by bhousel** [comment]
Can you paste the exact error here or in a gist?

**Comment by Monduiz** [comment]
Here is what I get:

npm WARN enoent ENOENT: no such file or directory, open '/Users/username/package.json'
npm WARN username No description
npm WARN username No repository field.
npm WARN username No README data
npm WARN username No license field.

**Comment by bhousel** [comment]
Do these commands work when you clone the project from scratch into a new folder?
```sh
git clone git@github.com:openstreetmap/iD.git
cd iD
npm install
npm run test
```

**Comment by Monduiz** [comment]
The first command gives me an error:
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by bhousel** [comment]
ok yes, your `git clone` command might need to use the https link:
```
git clone https://github.com/openstreetmap/iD.git
```

I guess my point was - after cloning the repository from scratch, can you run `npm install`?

**Comment by Monduiz** [comment]
It works! Thanks!

**Comment by bhousel** [comment]
👍 you're welcome!
