### ISSUE TITLE
Map features enabling/disabling

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3505]
Are there any examples of how to enable/disable the map features in Map Data by default?

**Comment by edpop** [comment]
There is no features vision saving between sessions. I made this task for my fork and I can send PR when I'm at work. The code is not very nice, that's why I am ashamed to send PR here.

**Comment by Monduiz** [comment]
What I want to do is very simple: I want to disable all features by defaults except for points of interest and buildings.

**Comment by edpop** [comment]
So [here ](https://github.com/openstreetmap/iD/blob/master/modules/renderer/features.js#L67)is your solution. Try to do after definition:
```js
features['points'].disable();
features['buildings'].disable();
```

**Comment by Monduiz** [comment]
edpop, thanks but I'm just not sure how to implement that. I have tried but I am missing something.

**Comment by Monduiz** [comment]
The following code achieves the desired result. Buildings and points of interest are the two features enabled by default.

var defFeat = context.features().keys();
	for (var i = 0, len = defFeat.length; i < len; i++) {
		var f = defFeat[i];
		  if((f != 'buildings') && (f != 'points')) {
		     clickFeature(f);
		 }
			}
