### ISSUE TITLE
mark public_transport=station as bus station

### ISSUE THREAD

**Issue by pksadiq** [openstreetmap/iD#3508]
mark public_transport=station as bus station. The wikipage says [0] that public_transport=station should better be used than amenity=bus_station. So tag bus stations as 'public_transport=station' by default.

Thanks

[0] http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbus_station

**Comment by bhousel** [comment]
It looks like [`public_transport=station`](http://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstation) can be used for Buses, Trams, Trains, etc.  We can't just call it a bus station right?

**Comment by pksadiq** [comment]
The amenity wikipage[0] says that both can be used for bus stations. If no additional information is given, it is marked as a bus station on osm. And the vote page says why it's recommended[1]. 

[0] http://wiki.openstreetmap.org/wiki/Key:amenity
[1] http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Main_problem_with_the_existing_schema

**Comment by pksadiq** [comment]
Also, please note that 'amenity=bus_station' isn't always required to be a bus station available for public. Say for example, a bus station inside an Airport that's solely use for the passengers to and fro to aircraft from the boarding station (That's very very rare though), or inside a police station, where the bus is used only for inmates.

public_transport=station also avoids that confusion.

**Comment by pksadiq** [comment]
Hm.. It seems like it isn't rendered right everywhere. So, as recommended in the wiki[0], the old amenity tag is to be kept.

[0] http://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform

**Comment by bhousel** [comment]
Can we continue discussion on #3041?

I'm still not really sure what to do about `public_transport` tagging.

If the tag `public_transport=station` can be _maybe_ a bus station, _maybe_ a tram station, _maybe_ a rail station - then we can't render it as a bus station and call it "Bus Station" in the preset list.  iD will need to continue to use the existing tags for these things that are already in widespread use.
