### ISSUE TITLE
Pop-up blockers interfering with crowdid.osmcanada.ca

### ISSUE THREAD

**Issue by berniejconnors** [openstreetmap/iD#3510]
Pop-up blocker is interfering with the initial load of https://www.crowdid.osmcanada.ca/.  Can you avoid the use of the pop-up window?  You will lose many novice users because they won't be aware of the pop-up blocker.

**Comment by bhousel** [comment]
I believe @Monduiz has already changed this in his fork.

The code to do this in iD uses the [osm-auth](https://github.com/osmlab/osm-auth) library, which can be set up to run either as a popup, or as a singlepage option that replaces the current window and returns the user to back to the application after they have authenticated.

**Comment by Monduiz** [comment]
I am trying to work on this.
