### ISSUE TITLE
Recent clone, adding points, lines, areas don't work

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3512]
I forked a new version and after installing it, Adding points, lines or areas don't work. Maybe I am missing something. I tried two times restarting from scratch with a new clone and still the same.

**Comment by bhousel** [comment]
Do you see any errors if you open the site in Chrome and use the developer tools?

**Comment by Monduiz** [comment]
I get: 
TypeError: entity is undefined
drawLabels()iD.js:100417
selection_call()iD.js:81604
drawVector()iD.js:107799
redraw()iD.js:107898
dispatch.prototype.call()iD.js:78546
change()iD.js:132689
coreHistory/history.perform()iD.js:132727
withDebouncedSave/<()iD.js:133954
start()iD.js:104379
dispatch.prototype.apply()iD.js:78550
behaviorAddWay/addWay/<()iD.js:103310
dispatch.prototype.call()iD.js:78546
click()iD.js:103194
mousedown/<()iD.js:103151
contextListener/<()iD.js:81228
1iD.js:100417:17

**Comment by bhousel** [comment]
Hm, looks like you caught a bug in `drawLabels` that I introduced yesterday.  

I just pushed some changes that fix that bug, along with improving label placement.  Can you pull in the latest changes and see if that fixes things?  You probably want to run something like the commands below:

Run one time to set `upstream` as a remote:
```sh
git remote add upstream https://github.com/openstreetmap/iD.git
```

Then every time you want to pull the latest code:
```sh
git pull upstream master
```

(You will want do your work in a branch that is not master.)

**Comment by Monduiz** [comment]
It's all good now! Thanks! Yes, I will create another branch to work on it.

Thank you again!

**Comment by Monduiz** [comment]
If I understood well, I forked the original, created a new branch to develop the app. Now, this is safe if I change the files and add new ones, etc.? This the workflow I should follow? This will be a modified app not meant to be a feature to merge back.

I was tempted to create a separate directory for it again.

**Comment by bhousel** [comment]
Yep, you got it!

from #3506, the link describes the process: https://rhonabwy.com/2016/04/04/how-to-maintain-a-git-remote-fork/

Unfortunately git is not very user friendly and its branching model is really different from traditional version control systems, but it does work well for what you want to do.  It will take some getting used to..

Your workflow will look kind of like this:

```sh
git checkout mystuff         # this is the branch where you do your work
#... work work work...
git add <files>
git commit
git push origin mystuff      # save your work to your fork stored at `origin`
#... repeat above steps...

#... let's sync up with upstream iD...
git checkout mystuff         # start off on your branch
git fetch --all --prune      # update the `master` branch
git rebase master            # put the `mystuff` commits on the end of `master`
#...you will need to resolve conflicts here...
git push -f origin mystuff   # overwrite your fork stored at `origin`

**Comment by Monduiz** [comment]
Now lets say I am modifying some of the functions and code in iD, how will that sync affect my modifications?

**Comment by bhousel** [comment]
> Now lets say I am modifying some of the functions and code in iD, how will that sync affect my modifications?

As long as you make your modifications in a branch that's not `master`, the sync won't affect them.  

You can always make more branches to test things out or keep work separate from other things.  When in doubt, make another branch.  You can merge changes between branches pretty easily.

**Comment by Monduiz** [comment]
Got it! Thank you!
