### ISSUE TITLE
Deactivate modes

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3513]
In trying to remove a mode from the UI, shouldnt // at AddLine in function uiModes in modes.js do the trick?
This time its not working.

**Comment by bhousel** [comment]
This works when I try it:
```js
    var modes = [
        modeAddPoint(context),
        // modeAddLine(context),
        modeAddArea(context)
    ];
```

Make sure you rebuild the iD.js bundle too.  If you start your local server with `npm run start` this should happen automatically and complete in a few seconds.

**Comment by Monduiz** [comment]
Oh snap, I forgot to rebuild! Thank you!
