### ISSUE TITLE
Change locale with url parameter

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3515]
OpenStreetMap.org already works with url parameter like ?locale=

With iD, I have to change `detected.locale = (navigator.languages && navigator.languages.length)
        ? navigator.languages[0] : (navigator.language || navigator.userLanguage || 'en-US');`
in iD.js

for `detected.locale = location.search.match(new RegExp("locale=([\\w\\-]+)")) ? RegExp.$1.replace(/%22/g, "\"").replace(/%20/g, "") : null;`

to get the same functionality.

Am I missing something?  I would rather not have to modify iD.js but I am not sure how else to implement this.

**Comment by Monduiz** [comment]
Also, If I may offer a comment on such implementations: detecting a user's OS or Browser settings is not really a desirable solution. In countries with more than one official language many users have their OS or browsers in the majority language but might wish to have  content shown in their language. A user activated functionality is always the more desirable solution. It shouln't be handled in a user's settings either.

The url parameter allows the implementation of a user activated language switch and a window.onload call.

**Comment by bhousel** [comment]
The `iD.Context` object has a [`locale` method](https://github.com/openstreetmap/iD/blob/b5c95af3b7eb6e213f35dc072d0a1b4e0f65f35a/modules/core/context.js#L314) to pass in the locale.  This is how openstreetmap-website passes the user's preferred locale to iD when it starts, ([code here)](https://github.com/openstreetmap/openstreetmap-website/blob/7725cd59b41a622a634a447d33fbda738a472748/app/views/site/id.html.erb#L28).

**Comment by Monduiz** [comment]
This is promising!  I dont suppose that simply doing this with the id definition would work:

` id = iD.Context(window)
            .presets(iD.dataPresets)
            .imagery(iD.dataImagery)
            .assetPath('dist/')
      	    .locale("<%= locale %>", "<%= asset_path("dist/locales/#{locale}.json") %>");`

I just cant get my head around this one.

**Comment by bhousel** [comment]
Yes, you just call the `locale` on the `Context` object when you create it.
For example, I tried [index.html](https://github.com/openstreetmap/iD/blob/master/index.html) to have this, and it put iD into Spanish:
```js
        id = iD.Context(window)
            .presets(iD.dataPresets)
            .imagery(iD.dataImagery)
            .assetPath('dist/')
            .locale('es');
```
You can also pass an optional path to `locale` to tell it where the `es.json` file resides.  If not supplied, iD will guess that it's under the asset path in a folder called `locales`.

**Comment by Monduiz** [comment]
This is incredibly cool! The more I dive into iD, the more I like it. There wouldnt be something similar to pass on a bounding box now would there? Like map=12.00/-75.7106/45.4241

Using the same Context object: 

.bound('map=12.00/-75.7106/45.4241')

That would be so convenient!

**Comment by bhousel** [comment]
>  Like map=12.00/-75.7106/45.4241

Instead of using a context function, iD will grab this from the [url parameters](https://github.com/openstreetmap/iD/blob/master/API.md#url-parameters) when it starts itself.

If you want to change the location later from code, you can do:

`id.map().centerZoom([-75.7106, 45.4241], 12);`

(There are a lot of helpful `map.` functions, see [map.js](https://github.com/openstreetmap/iD/blob/master/modules/renderer/map.js))

**Comment by Monduiz** [comment]
DO you have an example on how a map function is called in iD's definition? I tried to use the centerZoom call without success. I would like to set two things this way: background and centerZoom. Thanks again!
