### ISSUE TITLE
Select the outlines of a building

### ISSUE THREAD

**Issue by milanjelisavcic** [openstreetmap/iD#3520]
When I create a buildings outlines and then fill it in with building parts I am unable to reach the outlines any more. There should be some selector, or time span selector, or double-click that can be a switch between selecting a part of a building and the outlines.

Here is the example: http://www.openstreetmap.org/edit#map=20/43.85564/19.84390

**Comment by bhousel** [comment]
Is your question about how to select the multiple overlapping ways?  We don't have a good way to do it currently, but this feature is ticketed in #1239.
