### ISSUE TITLE
Undo while in area creation mode exists area creation mode

### ISSUE THREAD

**Issue by Thue** [openstreetmap/iD#3530]
Say I am in area creation mode, and misplace a node midway through creating a new area. Then I immediately hit the "undo" button (or CTRL-z) to remove the misplaced node. This currently unexpectedly drops me out of area creation mode (in addition to correctly deleting the offending node), which it obviously shouldn't.

According to bhousel on IRC:  "I agree, can you open an issue for this one?"

**Comment by bhousel** [comment]
FYI, bumping priority on this issue..  Several of the users I watched test the new walkthrough struggled with this.
