### ISSUE TITLE
Background default

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3534]
Loading iD with a different imagery background as a default:

iD loads with Bing as a default imagery but is there a function that can be used in either id.Context, id.ui or id.map to set a different default without having to rewrite the core files?

**Comment by edpop** [comment]
Btw, I still have an opened [PR](https://github.com/openstreetmap/iD/pull/3188) and need some answers to finish it.

**Comment by bhousel** [comment]
> Btw, I still have an opened PR and need some answers to finish it.

Thanks for being patient, I'm working to wrap these all up and release iD v2 maybe this week.  I think all the serious bugs from the d3 upgrade are fixed as of yesterday

**Comment by bhousel** [comment]
> iD loads with Bing as a default imagery but is there a function that can be used in either id.Context, id.ui or id.map to set a different default without having to rewrite the core files?

You can set the background in the url hash (I think you're doing that already?).  I'll see if there is a way in code too.

**Comment by Monduiz** [comment]
Yes, I am doing it but with window.location.replace(). I was wondering if its possible to set the default as easily as some of the other functions like locale and centerZoom.

**Comment by bhousel** [comment]
> Yes, I am doing it but with window.location.replace(). I was wondering if its possible to set the default as easily as some of the other functions like locale and centerZoom.

I was just poking around with the background imagery code last weekend (to improve our imagery blacklist testing) and I found it..

What you're looking for is [`rendererBackground.baseLayerSource(d)`](https://github.com/openstreetmap/iD/blob/master/modules/renderer/background.js#L128).

example:
```js
// switch to Mapbox Satellite..
var tileLayer = context.background();
var mapbox = iD.data.imagery.find(function(d) { return d.id === 'Mapbox'; });
tileLayer.baseLayerSource(iD.rendererBackgroundSource(mapbox));
```
