### ISSUE TITLE
Vehicle service multiselect

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3535]
Following out a side discussion from #3517..

Now that iD supports multicombo fields (see #3034, #3080), we have a really good way to allow people to tag multiple selections.

A few fields in OSM still prefer semicolon separated strings to represent multiple values.

For example:  `service=*` (see [`shop=car_service`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcar_repair)), 
>  `service=dealer;repair;parts;tyres;electrical;glass`

This one is especially bad because the `service=*` tag is overloaded for service highways.

(Compare to the [`service:bicycle:*`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle#Additional_keys) namespace, which already exists and handles multiple values cleanly.)

So my question is, when we encounter tags like this, where
1. the tag has obvious usefulness, and
2. the existing tag is barely used if at all, and
3. the wiki recommendation is clearly bad

_Can we just disregard what the wiki says, and create a multiselect preset that expands to tags like_ `service:vehicle:dealer` `service:vehicle:repair`,`service:vehicle:parts`, etc.

Does anybody care about this vehicle `service=` tag enough that changing it would cause major problems?

**Comment by willemarcel** [comment]
I agree with using the service:vehicle namespace tag for shop=car, shop=car_repair and shop=motorcycle.

**Comment by boothym** [comment]
Looks like service=* is only used in ~3800 of the ~100,000 shop=car_repair tags worldwide. So I agree with the change as it shouldn't cause major problems, and will make it easier to add services and bring that number up.

Though just wondering if the generic service:vehicle is correct or whether it should be service:car since it's car repair?

**Comment by bhousel** [comment]
I was mostly thinking "vehicle" so it covers cars, trucks, motorcycles, etc.

**Comment by bhousel** [comment]
I did this..
