### ISSUE TITLE
Mouse pointer position when dragging points

### ISSUE THREAD

**Issue by gmaclennan** [openstreetmap/iD#3536]
When you create a new point, it is created with the base of the icon centered on the mouse pointer:

<img width="93" alt="id-pointer-1" src="https://cloud.githubusercontent.com/assets/290457/19897946/54f2d804-a017-11e6-86e4-982aaa0b4969.png">

When you drag the point to move it, the mouse pointer changes to a more precise crosshair, but centered on the position on the icon where you start dragging, often near the center:

<img width="68" alt="id-pointer-2" src="https://cloud.githubusercontent.com/assets/290457/19898009/84aead5c-a017-11e6-9c9f-188a4f8d5bf3.png">

We have seen that this behavior confuses many users. They are unclear whether the 'true' position of the point is the base of the icon, or the center of the crosshair mouse pointer.

I'm not sure what the best solution is. My suggestion would be to move the point when the user starts dragging so that the crosshair is positioned where the point will be positioned. The current behavior easily leads to points being positioned inaccurately.

**Comment by bhousel** [comment]
I think @kepta might have fixed this already over the summer, but not sure - are you testing with the 1.9.x on osm.org or a 2.0 beta?

**Comment by gmaclennan** [comment]
I was testing on openstreetmap.org

**Comment by gmaclennan** [comment]
Just checked `master` - I see no change in behaviour.

**Comment by bhousel** [comment]
Thanks @gmaclennan for checking, I'll leave it open as something we should improve.

**Comment by bhousel** [comment]
We can hide the mouse pointer while dragging so there is no ambiguity.

**Comment by bhousel** [comment]
I ended up adding a little shadow shape to show the position of the feature while dragging

![marker move](https://cloud.githubusercontent.com/assets/38784/25420320/98631ade-2a25-11e7-9217-52d32d51be64.gif)
