### ISSUE TITLE
Eliminate symlinks in repository

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3545]
We can eliminate the symbolic links in our repository, and with them all the complicated instructions and extra `.bat` file for Windows users.   

Instead let's create the links with an npm build script.  `shx ln -s` should be able to create them in a cross platform way.

**Comment by slhh** [comment]
@bhousel Do you intend to fix this soon? Otherwise, some instructions how to run fixWinSymlinks.bat would be nice. I tried to run it from Git Shell under Windows 10, but after requesting admin rights it failed because git was not found. Git is found when typing git commands manually.

**Comment by bhousel** [comment]
Thanks, yes I think I can fix this pretty quickly.  The last time I tried the steps on windows, I used Cygwin, which is a little different from git bash shell in a few ways. 

Also, you might be able to avoid the symlink issues by testing with `dist/index.html`, I am not sure.

**Comment by slhh** [comment]
@bhousel The land.html symlink is still not built on Windows 10. I got "ln: EPERM: operation not permitted." It is the only one linking to a file, all others are linking to folders.
I tried to build a symlink to a file with shx manually, but got the same error.
Because it is a html file, can we link by html instead of a symlink?

**Comment by bhousel** [comment]
@slhh you need to run as administrator the first time so that the symlinks get created properly.  Can you try that and let me know if it resolves the issue?

**Comment by slhh** [comment]
@bhousel How to do that? I haven't been able to run GitShell as administrator, and in the normal shell npm install failed due to missing git.

I have installed shx globally and managed to make the symlink with admin rights manually.
Unfortunately, npm test does still fail with 20 (+19 pending) tests as before.
Why is the land.html symlink required? It doesn't seem to change anything.

**Comment by bhousel** [comment]
To run as administrator on windows, hold down the shift key and right click the icon, then choose "More >" and select "Run as administrator".  

I've successfully set up a working Windows environment a few different ways:

Prerequisite:  Install [Node.js for Windows](https://nodejs.org/en/download/) and [Git for Windows](https://git-for-windows.github.io/)

Then one of these options:

Option A:  Just adjust `%PATH%` to be able to find those things and use a normal DOS CMD shell or Powershell.

Option B:  Git for Windows includes its own version of Bash that works ok.

Option C:  Install [Cygwin](https://www.cygwin.com/) and use that.

Option D:  Some people just run a linux under something like [Virtualbox](https://www.virtualbox.org/), [VMWare Workstation](http://www.vmware.com/products/workstation.html) or similar.

Option E:  The official [Bash for Windows 10](http://www.pcworld.com/article/3106463/windows/how-to-get-bash-on-windows-10-with-the-anniversary-update.html) package should work.  This is the only option I haven't tried yet.

**Comment by bhousel** [comment]
> Unfortunately, npm test does still fail with 20 (+19 pending) tests as before.

Yes, I dont know why.  I don't think it is related to symlinks..

> Why is the land.html symlink required? It doesn't seem to change anything.

If you are running a localhost iD and attempt to save, it should ask you to authenticate against openstreetmap.org.  `land.html` needs to be located in the same location as `index.html` and is the page that completes an OAuth handshake. 

We only use a few symlinks in iD, but it would be great to not need them.
