### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by colejohnson66** [openstreetmap/iD#3547]
For a project of this size, logging seems like a must. Especially with bugs such as #2151. I recently had a consistent repro on Windows 10 64-bit in Chrome 56.0.2896.3 dev, but now that it's updated to 56.0.2906.0 dev, I no longer can consistently repro that bug. If there was a flag, say `debug=true` in the URL, then people who can consistently repro issues could post a log dump for those who can't.

**Comment by bhousel** [comment]
What would you want logged?   Chrome already includes a really great code profiler that can trace all the JavaScript calls.  It just seems like you'd get far more information by using the tool than from anything we could write to the `console.log`.

> For a project of this size, logging seems like a must. 

How big do you think this project is? 😁

**Comment by bhousel** [comment]
Closing, because as mentioned above, all the developer tools are great at code profiling and tracing.
