### ISSUE TITLE
Enhancement: Please add preset for "tourism=apartment"

### ISSUE THREAD

**Issue by geowOSM** [openstreetmap/iD#3548]
Hi, I'd like to suggest adding "tourism=apartment" as a preset (same datasat and icon as chalet)

"tourism=apartment" is an approved tag 
​http://wiki.openstreetmap.org/wiki/Tag:tourism%3Dapartment
and quiet popular in Central EU, currently >3.2k instances world wide, see
​http://taginfo.openstreetmap.org/tags/?key=tourism&value=apartment

Between tourism=apartment and tourism=chalet is a clear distinction: "Chalet" is for a detached holiday cottage which you rent exclusively, "apartment" is for one or several flats in a shared building.

Thanks for considering
geow

**Comment by bhousel** [comment]
Thanks for the suggestion!  I just added it..

<img width="374" alt="screenshot 2016-11-05 10 24 39" src="https://cloud.githubusercontent.com/assets/38784/20030766/2434b858-a342-11e6-825c-bc6de3bdfe7c.png">

**Comment by geowOSM** [comment]
Great, thanks!
