### ISSUE TITLE
App stuck after closing OSM log in popup

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/iD#3549]
Low prio issue I noticed while testing on https://openstreetmap.us/iD/master/, it doesn't happen on osm.org, as users are already logged on there.

After doing some edits and hitting the save button, I get a log on popup for OSM. If I just close this popup without actually logging on, most of the iD buttons are still disabled, the Save button has no effect at all. To continue from here, I have to use the browser Refresh [F5] and recover my session afterwards.

**Comment by bhousel** [comment]
yep that's actually #3546  - and I consider it high priority! :)
