### ISSUE TITLE
Add info icon to Opening hours

### ISSUE THREAD

**Issue by mitjajez** [openstreetmap/iD#3551]
Please, add info icon (i) next to _Opening hours_ field that will open box (just like on similar field) where should be link to http://projets.pavie.info/yohours OR may even be implemented as tool to select opening hours.

I can do this, just please point me to source code.

**Comment by bhousel** [comment]
The existing field already does have an info icon that will bring up a link to the OSM wiki.
For better opening hours support than that - #974 is the issue
