### ISSUE TITLE
iD automatically zooms out

### ISSUE THREAD

**Issue by GeoSebbo** [openstreetmap/iD#3552]
Hi!
I am using Firefox ver 49.0.2 under Win7 Professional (SP1).
Whenever I use any map controls (panning, zooming) iD automattically zooms out one level.
So for zooming in one level, I have to zoom in two steps. It's not only annoying, but also makes it impossible to use the editor.
Cheers.

**Comment by bhousel** [comment]
Thanks for the report, I will try it out

**Comment by slhh** [comment]
Official release and master deployment work fine with Firefox ver 49.0.2 under Windows 10 here.

**Comment by bhousel** [comment]
Just following up, I did test with Firefox and Windows 10 yesterday, and couldn't reproduce this issue. 

@GeoSebbo could there be any extensions or browser addons that are affecting the way the controls work?

When you use the controls, are you talking about clicking the zoom in/zoom out icons, or using the keyboard zoom controls `+`/`-`, or scrolling with the mousewheel?

The mousewheel is unusually touchy in Firefox, but this is a known issue - #3029

**Comment by bhousel** [comment]
Can't reproduce this issue.. Please reopen if it still happens, thanks!
