### ISSUE TITLE
Duplicate streets and cities in drop-down [2.0 beta]

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3553]
Random example - same happens for the street as well. In iD 1.9.7 there are no duplicates. FF 49.0.2, Win10 if that helps.

![addr](https://cloud.githubusercontent.com/assets/16965772/20030899/061539f0-a366-11e6-9f58-b8215d270397.jpg)

**Comment by bhousel** [comment]
Thanks, I'm working on a fix for this now.  I also noticed the Postcode field has some issues.
