### ISSUE TITLE
Swap url map order to zoom/latitude/longitude for iD v2

### ISSUE THREAD

**Issue by claudiush** [openstreetmap/iD#3554]
Tried to navigate via URL to 
[https://openstreetmap.us/iD/master/#background=Bing&map=16.00/46.9339/-123.4923](https://openstreetmap.us/iD/master/#background=Bing&map=16.00/46.9339/-123.4923)
but the longitude kept reverting to
https://openstreetmap.us/iD/master/#background=Bing&map=16.00/46.9339/-90.0000

**Comment by bhousel** [comment]
The mirror on openstreetmap.org uses longitude/latitude order..

**Comment by bhousel** [comment]
Hmm, maybe we should take this opportunity with the v2 release to switch the url hash order to the more familiar `zoom/latitude/longitude`?  

I'm definitely tired of having this conversation, and would prefer to have the default order that people expect to see in a url hash.

Does anyone care if I do this?  _And have good reasons for caring?_

**Comment by boothym** [comment]
Isn't the order already lat/lon on the main OSM website? (Unless I'm mistaken and you're referring to the OSM.us site!)

**Comment by pnorman** [comment]
> Isn't the order already lat/lon on the main OSM website?

The order on the OSM site isn't the order iD uses. osm.org overrides it.


> Does anyone care if I do this? And have good reasons for caring?

👍, it allows copy/paste from osm.org or other URLs. The minus I see is that it breaks any links to a specific location on a deployment of iD that isn't overriding the order already.

**Comment by bhousel** [comment]
> The order on the OSM site isn't the order iD uses. osm.org overrides it.

Yes openstreetmap-website contains special javascript code to workaround this iD "feature".

> it allows copy/paste from osm.org or other URLs. The minus I see is that it breaks any links to a specific location on a deployment of iD that isn't overriding the order already.

Yeah, this is why if we are going to change it, now is the time to do it - v2 already contains a number of other breaking changes.

**Comment by bhousel** [comment]
I did this. 😬
