### ISSUE TITLE
Enhancement: Please add preset for "amenity=internet_cafe" 

### ISSUE THREAD

**Issue by sguinetti** [openstreetmap/iD#3559]
Hi, I'd like to suggest adding "amenity=internet_cafe" as a preset ("cybercafé" or "lan party" in some countries)

"tourism=internet_cafe" is an approved tag
​http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dinternet_cafe
original proposed feature:
http://wiki.openstreetmap.org/wiki/Proposed_features/Internet_cafe

Description:
> An internet café is a place whose principal role is providing internet services to the public, usually for a fee based on the time used. In many countries, they offer phone cabins, fax services, and possibly other retail items like phone cards. 

Thanks for considering
Diego

**Comment by bhousel** [comment]
Sounds good to me, thanks for suggesting!
