### ISSUE TITLE
make it clearer which 𝘅 the walkthrough is referring to, when it says how to close the feature editor

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#3560]
In the walkthrough, the text "Click the (tick) button to close the feature editor" appears.  Unfortunately below the feature editor there's a big green tick next to "navigation" (indicating that the navigation section of the walkthrough has been gone through).

Could the text be changed to make it more claear that it's referring to the tick at the top right of the feature editor?

**Comment by bhousel** [comment]
Is this #3247?  If so, we did fix it already by removing the checks down in the navigation section, and you can see it in https://openstreetmap.us/iD/master . (If this is the case please close)

If it's something else, can you attach a screenshot?  thanks!

**Comment by SomeoneElseOSM** [comment]
Yes - it's https://github.com/openstreetmap/iD/issues/3247 - thanks.
