### ISSUE TITLE
Creating field presets that are Read-Only

### ISSUE THREAD

**Issue by ptivel** [openstreetmap/iD#3562]
Is it possible to create a read-only field in id editor presets? For example: to hold a feature identification number that should never be changed but could be useful to view, or a field that holds the original collection date.

**Comment by bhousel** [comment]
iD is primarily an editor for OpenStreetMap, which doesn't restrict editing of any of the tags.  So we don't have that capability in iD.

If the OpenStreetMap community decided that they wanted to add warnings or editing restrictions for certain features, I'd support that and implement it in iD.  But as of now, free tagging is the rule.

**Comment by ptivel** [comment]
Thanks for the response! How about If I were to customize a field for my own project and I wanted that field to display a read only value from the APIDB. What area of the code should I edit. Would I need to focus on the presets.js and raw_tag_editor.js file?

**Comment by bhousel** [comment]
>How about If I were to customize a field for my own project and I wanted that field to display a read only value from the APIDB. What area of the code should I edit. Would I need to focus on the presets.js and raw_tag_editor.js file?

Yes
