### ISSUE TITLE
Wikipedia language dropdown should default to user-preferred language

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#3574]
When you add a Wikipedia field to a feature, the language dropdown shows English initially, even if the user’s preferred language is some other language. If the user’s preferred language’s ISO code happens to match an existing Wikipedia language edition, that edition should be chosen by default, since the user would be more familiar with article titles in their own language.

/cc @bhousel

**Comment by boothym** [comment]
Seems similar to #3265 which was apparently fixed.

**Comment by 1ec5** [comment]
I’m seeing identical behavior in [master](https://openstreetmap.us/iD/master/) (2.0.0-beta.1) as in 1.9.7. Perhaps it regressed shortly after it got fixed?

**Comment by bhousel** [comment]
Thanks @1ec5, this regression was introduced in efd9e6d.. I just fixed it 👍
