### ISSUE TITLE
preset would be useful for FIXME

### ISSUE THREAD

**Issue by martenjj** [openstreetmap/iD#3575]
This tag is useful for leaving hints or notes to other mappers, so its use should be encouraged as much as possible.  It takes a lot of clicks, though, to add such a tag to a new way/node:

1. Select the feature of interest
2. If required to refer to a node of a way, select that node in the selected way.
3. If the node is not already tagged, click to focus "Search" and type "ot", then click on "Other".  You have to know this in order to add any tag to a node which does not already have any tags or a preset!
4. If the node is a junction, scroll down past the big "Turn restrictions" field (see #3136)
5. Click in the tag field and type 'fi"
6. Click the "down arrow" in the second field and select "yes", "continue" or whatever
7. Click the "tick" or deselect the object

There may be other ways, but none significantly less complex.

Presets for "fixme=yes", and maybe "fixme=continue", would make tagging FIXMEs a lot easier.

**Comment by bhousel** [comment]
iD does already include `fixme` as a universal preset field, which means you can add it to any feature with just 2 clicks:

![fixme](https://cloud.githubusercontent.com/assets/38784/20178039/957db814-a71d-11e6-9f53-47f84b4da4d9.gif)

**Comment by martenjj** [comment]
Sorry, maybe I didn't make my original report clear enough.  Yes, I know that any node has the "Add field - Fixme" as above, but to be even able to get to that dropdown to add the field means first having to set the node type to "Other" (assuming that is is not tagged already), which means searching down the scrolling list of node presets:

![a](https://cloud.githubusercontent.com/assets/10631760/20237547/90b5228e-a8cd-11e6-89f8-638a0cf074a6.png)

Having a preset in this list would save having to go through this first stage.
