### ISSUE TITLE
Enhancement: Preset for more leisures and aquariums.

### ISSUE THREAD

**Issue by sguinetti** [openstreetmap/iD#3579]
Similar to #3559 Add POIs of leisure places. The purpose is to make it more varied for family entertainment than mentioning "parks" or "gardens".

- leisure=resort (example: country clubs)
-- Info: https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dresort

- leisure=dance (example: salsoteca)
-- Info: https://wiki.openstreetmap.org/wiki/Tag:leisure%3Ddance
-- Proposed page: https://wiki.openstreetmap.org/wiki/Proposed_features/dance

- leisure=water_park
-- Info: https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dwater_park
-- Info 2: http://gestion.pe/tendencias/siete-parques-acuaticos-que-usted-conocer-2100377

- tourism = aquarium
-- Similar to zoos.
-- Info: https://wiki.openstreetmap.org/wiki/Tag:tourism%3Daquarium
-- Proposed page: https://wiki.openstreetmap.org/wiki/Proposed_features/Aquarium

Please and thanks.

**Comment by bhousel** [comment]
I think we have `leisure=water_park` already, but all the other ones sound good.. Thanks for the suggestions!
