### ISSUE TITLE
"Best" imagery not automatically selected

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3586]
e.g. this location should show the Cape Town imagery instead of Bing:
https://www.openstreetmap.org/edit#map=19/-33.94348/18.49801

Thanks for the report @Firefishy!

It's a `lat/lng` - `lng/lat` issue caused by #3554

**Comment by gplv2** [comment]
Any chance this release can be sped up a bit ?   It might not sound/look like a big issue but in .BE we've noticed this by spotting a bad edit based on some very obsolete background layer.  It would really help to prevent bad OSM data being entered.   aka: is it possible to hot-fix this today ?  Thanks a lot

**Comment by bhousel** [comment]
Yes, I'll make a patch release this morning..

**Comment by gplv2** [comment]
Much Appreciated!
