### ISSUE TITLE
Entering iD, the map is completely zoomed out

### ISSUE THREAD

**Issue by SHARCRASH** [openstreetmap/iD#3588]
Let's say a user is on the page details of an element with its location being highlighted. He notices an error and wants to edit. When he enters the editor, the map doesn't stay on the location, instead the map is completely zoomed out, which makes it tedious to find back the location.

Not browser specific and doesn't happen everytime.

**Comment by bhousel** [comment]
Good catch, I think I know what this is - similar causes to #3586 
There is some handoff that occurs between the main osm site and the embedded iD which needs to happen via the url hash.

**Comment by boothym** [comment]
Works fine when browsing the map, only occurs when you are viewing a node/way/relation and then try to edit.

**Comment by SHARCRASH** [comment]
I confirm the above! :)

**Comment by elgaard** [comment]
I can comfirm it too.
An thanks to boothym for the workaround. You just have to hit the x, to close the sidebar before you press "edit", then you have to find your object again.

**Comment by bhousel** [comment]
Awesome, thanks @tyrasd for fixing this..  Closing here as it's a bug I introduced in the openstreetmap-website code.
