### ISSUE TITLE
Presets for Healthcare

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#3589]
According to [this wiki page](https://wiki.openstreetmap.org/wiki/Key:healthcare) there are a lot of presets to add about healthcare:speciality or healthcare

**Comment by bhousel** [comment]
Wow there are really a lot of these.  

I don't agree with deprecating tags like `amenity=hospital` or `amenity=doctors`, which are in widespread use.  But we could probably add the new healthcare tags alongside the old ones.

**Comment by homersimpsons** [comment]
Yes, I was just talking about addig this one, not deleting the others.

**Comment by 1ec5** [comment]
I use the healthcare tags in conjunction with the longstanding `amenity` tags, to ensure maximum compatibility. Wouldn’t hurt to do that in the preset too.

**Comment by dalekunce** [comment]
huge upvote for better healthcare tags. Healthsites.io is working towards full integration with OSM so this would be great for everyone. I think Mark from healthsites could weigh in on minimal viable tags for healthcare as a preset for iD. cc @markherringer @smit1678

**Comment by smit1678** [comment]
👍  We mapped old and new healthsites tags here: https://github.com/hotosm/health/wiki/Health-facility-tagging-within-OSM-(proposal). Not wanting to create yet another healthcare proposal, but we should bring things together and inline to promote a good way forward. 

> I don't agree with deprecating tags like amenity=hospital or amenity=doctors, which are in widespread use. But we could probably add the new healthcare tags alongside the old ones.

Agreed.

**Comment by markherringer** [comment]
Thanks Dale and Nate.
@ViolaineCartONG and I were reviewing yesterday and planning another workshop to follow on from the workshop last year. We'll send through a schedule request. Thanks!

**Comment by ViolaineCartONG** [comment]
@smit1678 great work ! And totally agree with you ! Did you contact author of healthcare 2.0?

**Comment by smit1678** [comment]
@ViolaineCartONG Thanks!

> Did you contact author of healthcare 2.0?

No I did not yet actually. Our next step from the chat convo we held last year was to move from our Github wiki into a OSM wiki page to make a proposal.

**Comment by bhousel** [comment]
This was done!  Thanks @JamesKingdom 👍
