### ISSUE TITLE
localized authentication

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3595]
If iD is loaded using the .locale('fr') Context option, the authentication should also happen in the same language. Currently, if ID is loaded in French, as an example, when doing edit->save->authenticate, the login OSM popup window is in English.

In the context of Governmental use of iD in jurisdictions with more than one official language, this is a big issue. Is there a way to modify this behaviour?

**Comment by tmcw** [comment]
@Monduiz do you know if there's a way to tell the OSM website that you'd like the french translation? Is there a query string you can pass? Giving us a bit more information about how this issue might be fixed will help speed an implementation!

**Comment by Monduiz** [comment]
@tmcw I am using iD v2.0 for a project. I am loading iD with 
id = iD.Context()
            .assetPath('dist/')
            .locale('fr');

iD is then in French but the authentication is loading in English when attempting to save as its probably the default. The Website can be loaded in French if ?locale=fr is added to the URL but its not working with the authorization url.

**Comment by Monduiz** [comment]
@tmcw You can see what I am trying to do here: https://monduiz.github.io/CrowiD2/

Click on Francais and you will go to the french version. When you edit -> save, you load the auth window and its in English. I am trying to make it load in French when in that language.
