### ISSUE TITLE
Bad translation? or Bad tag?

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#3596]
Hello, there is a bad "translation" (at least in french) for Id.
drive_through is translated by Drive-in (which are completely different thing according to [wiki](http://wiki.openstreetmap.org/wiki/Key:drive_through)
To see that:
1. Add a new point
2. Select preset Burger King
3. See the field Drive-in
4. Checkin/Unchecking the box create the tag drice_through

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/ideditor/id-editor/dashboard/) and you can fix this yourself if you sign up for an account there.

**Comment by homersimpsons** [comment]
Okay, I didn't know if it was in all language or just fr, this is why I opened this issue.
I change the translation, as Drive-in are really rare (doesn't exist?) in France, I just put "Service Drive" without precision.

**Comment by bhousel** [comment]
Sure it's no problem to ask for clarification.. 

Yes you do have restaurants that offer Drive-Through service in France:
http://www.openstreetmap.org/edit#map=20/50.02697/4.03373

But it should be translated as "Drive Through" not "Drive In".. Hope that helps..

**Comment by homersimpsons** [comment]
Lot of fast food offers Drive Through. But I was talking about Drive In.
In fact there is a parking next to the drive through, but commonly this is to order in restaurant.

**Comment by Monduiz** [comment]
I am not sure if its relevant but in Canada the proper translation is "Service au volant". SO, maybe for the fr-CA it should be different.
