### ISSUE TITLE
Numbers and units in measurement box are unlocalized

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#3597]
The measurement box has unlocalized numbers and units. Here it is in Vietnamese; the decimal separator should be a comma but it’s a period instead. Similarly, the unit abbreviations can’t be localized.

![inspector](https://cloud.githubusercontent.com/assets/1231218/20453952/e53f10ba-ade8-11e6-9ff5-ab052d4c8a8f.png)

**Comment by kepta** [comment]
We could take a look at this library for [internationalisation](https://www.npmjs.com/package/i18n)

**Comment by 1ec5** [comment]
> We could take a look at this library for [internationalisation](https://www.npmjs.com/package/i18n)

The `i18n` package appears to handle [pluralization](https://www.npmjs.com/package/i18n#i18n__n) but not number or unit localization. [Globalize.js](https://github.com/globalizejs/globalize#pick-the-modules-you-need) is a popular package for a number of localization tasks, including formatting numbers and numbers with units. It uses a slice of data from CLDR, so it isn’t necessary for iD’s localizers to specify the number and unit formats.

**Comment by 1ec5** [comment]
Actually, [`Number.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) should be sufficient for localizing these values in modern browsers.
