### ISSUE TITLE
In editing mode RTL name tags appear reveresed

### ISSUE THREAD

**Issue by valleyofdawn** [openstreetmap/iD#3601]
On the visual elements themselves (street names etc.)
Written LTR instead of RTL.
True for line elements but point elements are OK
Applies to Arabic an Hebrew at a minimum.
I'm working with chrome on a windows machine.

**Comment by bhousel** [comment]
I think this might be #3491?  Can you let me know if it's different and I'll reopen..

**Comment by valleyofdawn** [comment]
Seems to be the same issue. Perhaps you can build in a chrome-specific
workaround, given that it's a browser used by more than half the users.
