### ISSUE TITLE
Fence type / height | Preset Suggestion

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/iD#3602]
_A suggestion for improving the [fence preset](https://github.com/openstreetmap/iD/blob/c8e4f76c230512dc82dc060bf337e3ba489b113e/data/presets/presets/barrier/fence.json)._

## Background
Fences add useful **walkability** and **access** information to the map. Fence data can be improved by including the `fence_type` and `height` tags. The type of fence is [currently tagged on about 8% of all fences](https://taginfo.openstreetmap.org/tags/barrier=fence?filter=ways#combinations) on the map.

## Suggestion
Add the [`fence_type=*`](https://wiki.openstreetmap.org/wiki/Key:fence_type) and [`height=*`](https://wiki.openstreetmap.org/wiki/Key:height) tag to the fence preset.

## Screenshot
![winproj_2016-11-20_12-56-57](https://cloud.githubusercontent.com/assets/1827881/20465036/36d29250-af22-11e6-9025-16144df3d967.png)

**Comment by bhousel** [comment]
Sounds good to me!  I just added `fence_type=*` to the fence preset, also `wall=*` to the wall preset, and added `height` field to a bunch of the `barrier` presets.
