### ISSUE TITLE
Add maximum height as a field for bridges | Preset suggestion

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/iD#3605]
![2016-11-20_22-12-33](https://cloud.githubusercontent.com/assets/1827881/20469649/72cc11b2-af6f-11e6-90fc-e2a081bb0fc5.gif)

Observe as I add the value `maxheight=14'1"` to the way under the bridge in the GIF. This value represents the [maximum height](https://wiki.openstreetmap.org/wiki/Key:maxheight) of a vehicle on the segment, typically called the [clearance 📜 ](http://safety.fhwa.dot.gov/geometric/pubs/mitigationstrategies/chapter3/3_verticalclearance.cfm) here in the :us: .

## Suggestion
* Add the `maxheight=*` any `highway=*` preset as one of the selections under _Add field_.

This value is useful for **truck routing**, something few digital maps do well. Truckers using OSM based routers can [prevent mishaps](http://11foot8.com/) if this attribute is present.

**Comment by bhousel** [comment]
That's a good suggestion.. I know our highway presets already have a lot of stuff on the sidebar, but I agree `maxheight` is an important tag.

Also +1 for putting Joppa Road in the screenshot, because Ween.
