### ISSUE TITLE
Add waterfall preset

### ISSUE THREAD

**Issue by Anton-Latukha** [openstreetmap/iD#3608]
I map a huge park now. We have many beautiful waterfalls.

There is no waterfalls in editor right now.

Of course they are in OSM specification.
https://wiki.openstreetmap.org/wiki/Waterfalls

To comply to specification, I manually convert chunks of streams by overwriting tag waterway=waterfall on them.

![waterfall](https://cloud.githubusercontent.com/assets/20933385/20528682/dcbdbbe0-b0d5-11e6-94c2-ff36c5fd733e.png)

I was wondered how huge waterfalls as Niagara was done. And there they done the same as I do. There is a dot waterway=waterfall 8)
![niagara](https://cloud.githubusercontent.com/assets/20933385/20529554/3689d8c2-b0d9-11e6-941d-de59e61b1a52.png)

https://www.openstreetmap.org/edit?relation=176131#map=17/43.07915/-79.07353

Thank you.

**Comment by bhousel** [comment]
Good suggestion, thanks!
