### ISSUE TITLE
exclude tags already on object from auto-completion in All Tags list

### ISSUE THREAD

**Issue by dobratzp** [openstreetmap/iD#3625]
When adding a new tag using the All Tags list, the tag key is auto-completed based on commonly used keys.  However, existing keys are are not excluded from the list.

You end up either taking longer to auto-complete to the desired key or end up inadvertently adding a duplicate key to the object with a `_1` silently appended to it.

For example, I often want to add an `addr:unit` tag to an object after I have already filled in `addr:city`, `addr:housenumber`, `addr:postcode`, `addr:state`, and `addr:street` using the address field presets.  When typing `addr` the first four entries in the list, that show without scrolling down, are `addr:housenumber`, `addr:street`, `addr:city`, `addr:postcode`.  All of 4 of these keys are already on the object.

**Comment by pnorman** [comment]
👍 , this is how JOSM handles it, and it helps autocomplete be more useful.

**Comment by bhousel** [comment]
Cool that sounds good to me.. Yes the `_1` behavior is pretty annoying and we probably should get rid of that too.  It's really a hack - we silently append the `_1` because the old behavior was to silently delete the existing tag (which was worse).

**Comment by 1ec5** [comment]
@mueschel [caught](http://www.openstreetmap.org/changeset/54231344) me [accidentally entering](http://www.openstreetmap.org/changeset/54149834) `turn:lanes:both_ways_1` tags while manually mapping lanes. I’ve probably introduced tags like `name_1` in the past by accident due to this bug.
