### ISSUE TITLE
All Tags editor makes value for service_times lowercase

### ISSUE THREAD

**Issue by dobratzp** [openstreetmap/iD#3629]
When attempting to add `service_times` to an object, `Su` gets auto-corrected to `su`, so when you try to enter the most common value of `Su 10:00`, it gets changed to `su 10:00` which is incorrect as this key is supposed to follow the opening hours spec.

**Comment by bhousel** [comment]
Thanks!  This is like #3377 
A simple fix is to get all of the 'opening_hours'-like fields to match in this regular expression [here](https://github.com/openstreetmap/iD/blob/1d7e2f76bde5cd891f16649037eec7e80a8fb619/modules/services/taginfo.js#L219)

A better fix would be to drop the regular expression entirely and consider only the values' popularities when deciding which one of several case-equivalent alternatives to present to the user.

e.g. user types 's'
"Su 10:00" has 519 uses
"su 10:00" has 4 uses

We should exclude the "su 10:00" result.

**Comment by bhousel** [comment]
Closed in e1a9e7e with the simple fix.
