### ISSUE TITLE
Add communication: multiCombo

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3630]
For man_made=mast and man_made=tower there should be a multiCombo for the communication:*=yes tag, e.g.:

communication:radio:yes
communication:television:yes
communication:mobile_phone:yes
communication:microwave:yes

Also the name for man_made=mast should be changed to just "Mast".

**Comment by bhousel** [comment]
> Also the name for man_made=mast should be changed to just "Mast".

I don't have any strong preference what it's called - maybe it was originally called "Radio Mast" to differentiate it from masts on boats?  The word "mast" also sometimes describes the riser where electrical service enters a building.

**Comment by boothym** [comment]
Radio Mast was added here: https://github.com/openstreetmap/iD/pull/2613 - no mention of boats. Just seems weird to have radio in the name when a mast might not be used as a radio transmitter.  

> The word "mast" also sometimes describes the riser where electrical service enters a building.
No idea what that is, you'll need to show me a photo! :)

All of the `man_made=mast` terms should also be copied over to `man_made=tower` as the latter doesn't have any defined.

**Comment by abdeldjalil09** [comment]
> Let's just leave it as "Radio Mast"

Masts are not always used for communication, this title is appropriate for man_made=mast + tower:type=communication tag

**Comment by slhh** [comment]
>>     Let's just leave it as "Radio Mast"
> 
> Masts are not always used for communication, this title is appropriate for man_made=mast + tower:type=communication tag
> 
Unfortunately, it fits even better to tower:type=radio which is less frequently used.

Some other "tower:type", which are used in combination with man_made=mast, are lighting, siren, lightning_protection, and radar.

The key tower:type is defined in the wiki to allow user-defined values, and many man_made=mast don't have any specified tower:type.

Maybe we can call man_made=mast "Mast (Radio etc.)", "Mast (e.g. Radio Mast)", or "Mast (small tower)".

**Comment by bhousel** [comment]
Ok, we can change it to just say "Mast".  I really don't care.

**Comment by 1ec5** [comment]
Maybe add “radio mast” as a synonym for this preset?
