### ISSUE TITLE
Selected vertexes including their halos covered by rendered names

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3636]
Currently the selection of a vertex might be invisible because any name of a highway etc. is rendered on top.

Rendered names are automatically hidden when
- the cursor is near to the name,
- or the named element is selected

Rendered names should also be hidden if any selected, related, or hovered entity is near to the name.

**Comment by bhousel** [comment]
Yes, I agree.. This regressed recently, probably when I did #1645
