### ISSUE TITLE
Orthogonal / isogonal angle drawing

### ISSUE THREAD

**Issue by edpop** [openstreetmap/iD#3637]
Hello.

I'll be glad to share some solution for https://github.com/openstreetmap/iD/pull/2699, https://github.com/openstreetmap/iD/issues/1957.
I made a feature in my iD for drawing angles multiple of 45°. It works for _next_ segments of lines, _next_ and _last_ segments of areas.

![default](https://cloud.githubusercontent.com/assets/13479292/20991887/98aff07c-bd2c-11e6-9c55-541e810c4378.png)

If you need It, I'll try to make my code/architecture not so ugly that it is now and send PR then.

**Comment by bhousel** [comment]
Cool, can you put a demo of it online?  I'd love to take a look and try it..

**Comment by edpop** [comment]
I think it is possible, I'll notify.

**Comment by edpop** [comment]
This dirty hack will be able for some time → [pretty-angles](http://api.map.vl.ru/assets/iD/).

**Comment by bhousel** [comment]
Nice, I tried it out and it does feel intuitive to have angles snap when holding down shift..

I did notice that after drawing some ways with this, the graph got corrupted, and I saw lots of stuff in the console like `graph.js:38 Uncaught Error: entity w-51 not found`.  But if you clean it up a bit, I'd be happy to merge it in..

**Comment by edpop** [comment]
I tried to repeat this error in different browsers and places, but my console still clear, except some 404s of mapbox tiles. My cartoghaphers are using this tool for a 5 months, so it should be stable.
Can you tell me, how to reproduce this error, please?

**Comment by bhousel** [comment]
> Can you tell me, how to reproduce this error, please?

I tried some more and I did find the error, but it turns out to be unrelated to your code.  It's in master too.  Sorry about that!  But at least trying out the drawing mode helped me find this other thing.  I'll ticket now separately.

**Comment by edpop** [comment]
Do you have additional wishes to merge it? Maybe you have some thoughts about not to use this function twice?

**Comment by bhousel** [comment]
> Do you have additional wishes to merge it?

I think it's good and I do want to merge it, just working on other things right now.   I'm making substantial changes to how draw_area/draw_way works, so I don't want to start merging the angles code until that other work is finished.

**Comment by tordans** [comment]
@bhousel @edpop did this code/idea make it into the live version?
I would love to see it there. It would make HOTOSM tasks soooo much easier.
If not, is there a change to revive it?

**Comment by bhousel** [comment]
> @bhousel @edpop did this code/idea make it into the live version?

It did not, sorry!

**Comment by tordans** [comment]
Any chance to revive it?

I know about the plans at https://github.com/openstreetmap/iD/pull/2699 and  https://github.com/openstreetmap/iD/issues/3123.

However both are big changes to the interaction in iD.
This feature would IMO not collide with the above. 
But it would make it a lot easier to work on projects like the HOT OSM Task (outlining buildings).

**Comment by bhousel** [comment]
> This feature would IMO not collide with the above.
> But it would make it a lot easier to work on projects like the HOT OSM Task (outlining buildings).

I tried this PR out and it really wasn't any better than just clicking and squaring.  You still need to do all the clicking, the clicks just turn out more square as you're doing them.

**Comment by slhh** [comment]
@bhousel 

> I tried this PR out and it really wasn't any better than just clicking and squaring. You still need to do all the clicking, the clicks just turn out more square as you're doing them.

I wouldn't agree for the following reasons:
- Closing the way orthogonally seems to save one click because 2 edges are added at the same time.
- Each click to place another segment seem to become faster because the mouse positioning needs to be precise in one direction only.
- Clicking and squaring might not work for buildings where at least one edge isn't orthogonal in reality. E.g. buildings with round structures.
- Clicking and squaring can damage touching buildings.
- Clicking and squaring results in angular misalignment between multiple buildings or building parts.
- Clicking and squaring results in bad size or angular alignment where one corner can't be positioned well, eg. where a tree hides a corner of the building on imagery.
