### ISSUE TITLE
Search for coordinates

### ISSUE THREAD

**Issue by rakta** [openstreetmap/iD#3649]
When editing spread places, e.g. information accumulated on a travel, it is needed to jump around a lot. Currently this involves zooming out, panning and zooming in or pasting the new coordinates in the url bar and reloading the whole page (which takes a bunch of time in Firefox). 
I propose to add a coordinate search function, simmilar to the one in OSMAND.

**Comment by rakta** [comment]
Sorry, i didn't figure out how to apply a label to the issue, but this is a feature request, i guess ;)

**Comment by bhousel** [comment]
While not obvious, you can paste coordinates into the search box - does that work for what you need?

**Comment by bhousel** [comment]
closing here, please reopen if you find an issue with entering coordinates in the search field.

**Comment by jidanni** [comment]
Perhaps same as #7435, #4218.
