### ISSUE TITLE
deleting character from housenumber field sets cursor to end of line

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3650]
When i delete a single character from the housenumber fied (i.d. "46b" -> "4b") by positioning
the cursur after the "6" and pressing backspace the "6" disappears. But the cursor moves to the end of the string after "b". I would prefer the cursor to stay before the "b". Wehe I insert a character the cursor also moves to the end of the housenumber field.

**Comment by edpop** [comment]
It caused by https://github.com/openstreetmap/iD/blob/v2.0.1/modules/ui/fields/address.js#L185
