### ISSUE TITLE
More presets

### ISSUE THREAD

**Issue by sguinetti** [openstreetmap/iD#3651]
Hello. In this continuation, I sugest new presets for easy categorization of POIs.

* Confectionery:
** http://wiki.openstreetmap.org/wiki/ES:Tag:shop%3Dconfectionery

* Perfumery
** http://wiki.openstreetmap.org/wiki/Tag:shop%3Dperfumery

* Diary shop (not kiosk)
** http://wiki.openstreetmap.org/wiki/Tag:shop%3Ddairy

* Gas shop (amenity=fuel). Example in Peru: Llamagas, Limagas.
** http://wiki.openstreetmap.org/wiki/Tag:shop%3Dgas

* Driving school
** http://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddriving_school
** Licenses A1, A2, B1...

* Animal boarding
** http://wiki.openstreetmap.org/wiki/Tag:amenity%3Danimal_boarding

* Crematorium
** https://wiki.openstreetmap.org/wiki/Tag:amenity=crematorium

I sugest two things too:

* Club centers
* http://wiki.openstreetmap.org/wiki/Key:club
* Proposed page: http://wiki.openstreetmap.org/wiki/Proposed_features/Club

* Quarters (more smalls than neighbourhoods)
* https://wiki.openstreetmap.org/wiki/Tag:place%3Dquarter
* Proposed page: https://wiki.openstreetmap.org/wiki/Proposed_features/place%3Dquarter

Thanks. -Diego

**Comment by bhousel** [comment]
Most of these seem ok.

I'm not sure what to do with `place=quarter` though.  I get that it's something smaller than a suburb and bigger than a neighborhood.  

e.g.  _I think these are about right..._
OSM Suburb = Manhattan
OSM Quarter = Midtown
OSM Neighbourhood = Chelsea

But the words for these things are used very differently in US English, so I'd have to think about about what to call them so that their hierarchy is clear to an untrained user.

iD currently labels OSM Suburbs as "Borough" and OSM Neighbourhoods as "Neighborhood", and I've avoided supporting OSM Quarters.

**Comment by sguinetti** [comment]
Thanks for the aclaration. Maybe "quarter" was not appropriate. My situation is that I have been reviewing some "human settlements" that occupy between 1 and 10 blocks. [PDF document]( http://www2.congreso.gob.pe/sicr/cendocbib/con4_uibd.nsf/B5BB9C6DBA9AF49A05257DC50081492E/$FILE/40_pdfsam_720450WP0SPANI0s0Lima0Metropolitana.pdf).

The solution for each "settlement" is [place=block](https://wiki.openstreetmap.org/wiki/Tag:place%3Dcity_block). Would it be okay to use this tag?

**Comment by bhousel** [comment]
> Thanks for the aclaration. Maybe "quarter" was not appropriate.

No problem, "quarter" is an accepted tag and we should find a way to support it in iD.  I just wanted to put my thoughts about why it's complicated.  

> The solution for each "settlement" is place=block. Would it be okay to use this tag?

It's probably best to ask your local OSM community for guidance on how to use the tag.  I really don't know.

**Comment by abdeldjalil09** [comment]
> Diary shop (not kiosk)
> ** http://wiki.openstreetmap.org/wiki/Tag:shop%3Ddairy

This tag website about shops selling dairy products not diary shops, about diary shop it's rare used (only 11 uses) and doesn't have a wiki page.


> Confectionery:
> ** http://wiki.openstreetmap.org/wiki/ES:Tag:shop%3Dconfectionery

We already have a preset for this tag !


> Crematorium
> ** https://wiki.openstreetmap.org/wiki/Tag:amenity=crematorium

We already have a preset for this tag !

**Comment by Hufkratzer** [comment]
If you add [Animal boarding](
http://wiki.openstreetmap.org/wiki/Tag:amenity=animal_boarding) (see above)
you can perhaps also add 
* [Animal breeding](
http://wiki.openstreetmap.org/wiki/Tag:amenity=animal_breeding) and 
* [Animal shelter](
http://wiki.openstreetmap.org/wiki/Tag:amenity=animal_shelter)

All approved and on [Animals](
http://wiki.openstreetmap.org/wiki/Animals#amenity-animal_breeding) :dog2: :horse:  :elephant:  :eagle:

**Comment by sguinetti** [comment]
Nice tip.

**Comment by bhousel** [comment]
- [ ] Perfumery - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dperfumery
- [ ] Gas shop - http://wiki.openstreetmap.org/wiki/Tag:shop%3Dgas
- [ ] Driving school - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddriving_school
- [ ] Animal boarding - http://wiki.openstreetmap.org/wiki/Tag:amenity%3Danimal_boarding
- [ ] Quarter - https://wiki.openstreetmap.org/wiki/Tag:place%3Dquarter
- [ ] Club - http://wiki.openstreetmap.org/wiki/Key:club
- [ ] Animal Breeding - https://wiki.openstreetmap.org/wiki/Tag:amenity%3animal_breeding
- [ ] Animal Shelter - https://wiki.openstreetmap.org/wiki/Tag:amenity%3animal_shelter
- [ ] Watering Place - https://wiki.openstreetmap.org/wiki/Tag:amenity%3watering_place

**Comment by bhousel** [comment]
I just added these..
