### ISSUE TITLE
Wrong translation for leisure=resort in french

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#3652]
Hi,
Current translation of resort in french is "Relaxation" but it's wrong , resorts are not used only for relaxation, but also used for recreations and accommodations, correct traduction is "Complexe touristique" or "Complexe hôtelier".

**Comment by bhousel** [comment]
Thanks for the report @abdeldjalil09..  Our translations are handled through [Transifex (link to French translation)](https://www.transifex.com/ideditor/id-editor/language/fr/) and you can fix this yourself if you sign up for an account there.

**Comment by abdeldjalil09** [comment]
But i can't find "Resort"

**Comment by bhousel** [comment]
Yes Transifex UI is kind of confusing.. Does this link work?
https://www.transifex.com/ideditor/id-editor/viewstrings/#fr/presets/101404809?q=Resort

**Comment by abdeldjalil09** [comment]
Yes, thanks
