### ISSUE TITLE
Don't highlight previous parent way

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3657]
Parent related highlight is currently used only when a vertex is selected (#3631 may expand its use for relations).  But we should not highlight the previous parent after selecting a new way.. see:

![related_highlight](https://cloud.githubusercontent.com/assets/38784/21275770/593e773a-c39c-11e6-91a9-a93e762a2edd.gif)

**Comment by slhh** [comment]
@bhousel I think this is fixed in my pull request anyway #3631. I have reworked the parent way logic substantially, and have also added relation support.
