### ISSUE TITLE
Minimap shortcut doesn't work in Firefox

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#3660]

**Comment by bhousel** [comment]
Are you using a non-US keyboard?  We do know that the `/` key does a different thing on German keyboard, see #2812, but I'm not sure about other layouts.

**Comment by abdeldjalil09** [comment]
It's works fine in chrome browser but in firefox it doesn't works

**Comment by bhousel** [comment]
Sounds like a duplicate of #2812

**Comment by abdeldjalil09** [comment]
No, this is not duplicate of this issue , #2812 is about german keyboard ,  I use french keyboard, please re open this issue

**Comment by bhousel** [comment]
We don't need an issue for every keyboard.. I've added your info about the French keyboard to the other issue so that it is tracked in one place.
