### ISSUE TITLE
military=barracks and military=airfield and military=danger_area presets should be combinated with landuse=military

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#3663]
Currently , military=barracks and military=airfield and military=danger_area is not combinated with landuse=military but according to wiki , military=barracks and military=airfield and military=danger_area in combination with landuse=military is obligatory

**Comment by bhousel** [comment]
Doesn't it make more sense to map things like buildings and airfields as their own features inside an enclosing `landuse=military` area?   This is how schools and hospitals and lots of other things in OSM are mapped.

I think maybe the wiki should be fixed if it is suggesting to put a `landuse=military` tag on every military feature.

**Comment by slhh** [comment]
> Doesn't it make more sense to map things like buildings and airfields as their own features inside an enclosing landuse=military area? This is how schools and hospitals and lots of other things in OSM are mapped.

I would agree in case of a building or airstrip, but barracks, airfield, or danger_area are the enclosing area. Unfortunately, these enclosing areas could be a part of a larger military area, or just be the complete military area, which makes presets difficult.

**Comment by bhousel** [comment]
Makes sense now, I didn't realize the military tags were hierarchical.

`landuse=military` + `military=*`
