### ISSUE TITLE
Radial Menu is full

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3671]
For closed ways, the radial menu is full.

The addition of the Reflect commands pushes the menu to 8 items, which is really too many.  

The radial menu was already problematic, and it's something we've put off dealing with, but now we really should do something about it. 

ccing @samanpwbb for advice

Not looking to bikeshed, but in absence of concrete suggestions or help, I'll probably just change it to be a wider circle, or a fixed menu someplace.

<img width="250" alt="screenshot 2016-12-22 16 06 38" src="https://cloud.githubusercontent.com/assets/38784/21440371/adf5b5a4-c860-11e6-83ac-03819cc1071d.png">

Also tooltip placement on the left side of the menu is broken:
<img width="250" alt="screenshot 2016-12-22 16 19 57" src="https://cloud.githubusercontent.com/assets/38784/21440756/8c5d1b1a-c862-11e6-8f7c-46b7fad2e403.png">

prior discussion
#2145
#1994
#548  
#226

**Comment by bhousel** [comment]
one option

<img width="1032" alt="screenshot 2016-12-22 16 40 03" src="https://cloud.githubusercontent.com/assets/38784/21441467/28779f40-c866-11e6-84a0-373edff5c087.png">

**Comment by samanpwbb** [comment]
I think we should opt for a more conventional menu, with visible labels:

![screen shot 2016-12-22 at 5 05 40 pm](https://cloud.githubusercontent.com/assets/108094/21441940/d78023b6-c868-11e6-90b7-38525f272079.png)

I also suggest that we show this menu on right click, which solves the problem of this thing being obtrusive while you're trying to select / move / edit features.

**Comment by bhousel** [comment]
Cool @samanpwbb I like it..

**Comment by bgirardot** [comment]
@samanpwbb I like it too, much easier for new mappers to understand and discover functionality.

**Comment by kepta** [comment]
I tried to work on this issue. The context menu looks good. Here is the demo:

![2017-01-13 11_06_25](https://cloud.githubusercontent.com/assets/6966254/21919423/583ea23e-d980-11e6-9377-faa5e040ebf5.gif)

@samanpwbb As you can see the tooltip is a bit of a problem. Personally I don't think I have ever seen a tooltip for right click menus. What do you think ?

**Comment by bhousel** [comment]
This is awesome @kepta!
I think the tooltip is ok, but defer to @samanpwbb's opinion.

My thinking on the tooltip is - even if it's not perfect, it's better than before where tooltips could show up really anywhere around the radial menu and even on top of it.

<img width="332" alt="screenshot 2017-01-13 11 13 57" src="https://cloud.githubusercontent.com/assets/38784/21919587/71bfc26e-d981-11e6-929f-1420d1751b7e.png">

**Comment by slhh** [comment]
@kepta The visual impression doesn't really associate the tooltip to a specific menu item. If the hover styling of the menu item were more visible, this would likely become clear. Maybe the hover styling of the item should include the text label area too.
