### ISSUE TITLE
Add a square buildings validation

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#3673]
If somebody adds some number of buildings that aren't square, give an error when you hit save saying they should check if they should be squared. I notice this a lot at mapathons, tons of non-square buildings.

**Comment by bhousel** [comment]
I'd prefer to teach users to draw a square building in the walkthrough (#3085) and then not bother them about it later. 

Many buildings have non-square parts to them, so a validation like this would trigger a lot of false positives.  And besides, it's something that a power user can fix with an overpass query and a few keystrokes in JOSM.

**Comment by bgirardot** [comment]
@bhousel Hi Bryan, is there still a "building tool" in the works for iD? I thought that was close to being merged in a few months ago.

**Comment by bhousel** [comment]
@bgirardot Yes I still want to add the building tool, but we pretty much needed to put everything on pause for about 6 months to ship iD v2 and upgrade d3.  Every file in the iD code was changed, but the project is in a much better place looking ahead for the next several years.  We can depend on other libraries now and keep things up to date in ways that we couldn't before.

**Comment by RicoElectrico** [comment]
@bhousel 
> And besides, it's something that a power user can fix with an overpass query and a few keystrokes in JOSM.
Or is it? I don't know how Overpass could access geometry.

**Comment by aawiseman** [comment]
@RicoElectrico you can do a query in JOSM that finds all buildings thens square them all, but it sometimes messes up things that shouldn't be square too

**Comment by bjohas** [comment]
@aawiseman , @bhousel, @bgirardot , @RicoElectrico  - I do think a validation process picking up non-square would be good, as an optional tool for validators. We always teach people to square buildings, but I've recently done some stats and often there are a few non-squared buildings left over. I.e. a user will square most buildings (as instructed), but there are some that aren't (and should be). It might be better to do this in JOSM (assuming validators are mainly using JOSM), and I've filed a ticket here https://josm.openstreetmap.de/ticket/14952#ticket

Of course, a building tool in iD would be great too, including automatically adding building=yes. Do you happen to know why there is not building=yes option in the searchable "objects menu" used for tagging?

**Comment by bhousel** [comment]
> Of course, a building tool in iD would be great too, including automatically adding building=yes.

Yes, this is still planned..

> Do you happen to know why there is not building=yes option in the searchable "objects menu" used for tagging?

There is a preset for `building=yes` - just choose "Building".  We even set it up as the first thing:

<img width="381" alt="screenshot 2017-06-19 17 57 39" src="https://user-images.githubusercontent.com/38784/27307732-15f09fa8-5519-11e7-9caa-7782cb5fcd79.png">

**Comment by bjohas** [comment]
@bhousel Ahhh.... I had forgotten that iD shows different options for line and area. Too much editing in JOSM :)
