### ISSUE TITLE
Midpoints adding by double click

### ISSUE THREAD

**Issue by edpop** [openstreetmap/iD#3682]
Hello.
Don't you think, that it would be awesome to add a vertex by double-clicking to midpoint, instead of zooming? I have a few lines of code to this feature and can send PR.
I'm afraid to overload you, imho [orthogonal angles](https://github.com/openstreetmap/iD/pull/3641) is more important.

**Comment by bhousel** [comment]
hmm, I thought this did work, but I realize now that double clicking on the midpoint triangle itself does still count as a zoom intent.  Double-clicking anywhere else on a line adds a point.

Yes send the PR, if it's just a few lines, I can merge it quickly. 👍
