### ISSUE TITLE
Perserve OSM history when merging, spiltting, etc.

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3694]
Many operation result in loosing OSM history in view of tags and/or geometry. For example:
- Merge ways or areas
- Splitting ways or areas
- Multipoygon <-> area conversions
JOSM has some methods to reduce history impact, but these need some user experience, and are not a full solution.

How about adding one or two tags to bridge the history gap? One tag has to describe which other object tags have been sourced from, and the second tag describes which other object the geometry has been sourced from. These tags can be discarded with the next revision of the object. It is sufficient to keep the tags in the OSM history only.

This can work in the following way:

When loading an entity a with id a.id and version a.vers from the database add two array properties a.tag_hist = a.geo_hist = [a.id+a.vers];

When splitting an entity a into b and c, set 
b.tag_hist = c.tag_hist = a.tag_hist; 
b.geo_hist = c.geo_hist = a.geo_hist;
 
When merging two entities a, b with result c, set
c.tag_hist = a.tag_hist + b.tag_hist; 
c.geo_hist = a.geo_hist = b.geo_hist;

When transfering tags from a to b (e.g. point/area merge), set
b.tag_hist = a.tag_hist + b.tag_hist; 
b.geo_hist = b.geo_hist;

When storing an object a with version a.new_vers into the database remove duplicate items and any occurences of a.id+(a.new_vers-1) from both arrays a.tag_hist and a.geo_hist.
Add the following tags:
key: 'editor_history:tags:'+a.id+a.new_vers, 
value: a.tag_hist converted to string, discard tag if empty
and
key: 'editor_history:geo:'+a.id+a.new_vers, 
value: a.geo_hist converted to string, discard tag if empty

If this is acceptable for iD we should discuss it with the JOSM developers too. I would expect JOSM to be the first one using the additional information.

**Comment by pnorman** [comment]
👎 to this, if we want to preserve this information, the right way is to change the API.

**Comment by HolgerJeromin** [comment]
:-1: too. These history tags will grow over time and use more space then the property itself.

**Comment by slhh** [comment]
> These history tags will grow over time and use more space then the property itself.

This is wrong. An editor supporting this concept would discard the old tags, new tags are added in case the stored object is the result of merging, spitting, or copying during the current edit session. Therefore, most objects wouldn't have any such tag. Editors which are not supporting the concept might propagate the tags to the next version, but don't add anything.

**Comment by slhh** [comment]
@pnorman An api change can't replace this concept because the api can't know what has happened during the edit session. The editor needs to provide this information. Changing the api to let us store this information (the two tag values) in a differnent way than using normal tags would be nice. A more general api change offering object version specific tags/properties (some kind of object specific changeset tags) would be sufficient, but is such an api change realistic?

**Comment by slhh** [comment]
@pnorman Instead of using normal tags we can use changeset tags which are more intended for such purposes of describing the edit. My concept would work with changeset tags without any significant changes, but I see some potential drawbacks:
- JOSM changesets can be quite large. In case of using merge, split, copy tags heavily during the edit session, this can result in a quite large number of such changeset tags. I don't know if there are any limitations in view of changeset tags. Maybe JOSM can split the changeset if required.
- Tracing the history of an object seems to require to load all the changesets, which can be quite time-consuming. If any efficient method to get the object related tags selectively exists or can be provided this will not be a problem. It is not mandatory to get this from the API directly. It would be sufficient to get it from the Overpass API or any other service, which is sufficiently current. Maybe it is easier to get the Overpass API changed than the API. We don't need to wait for this a change, because it is not required to store the extended history information, but we need to choose the right data format to enable this change if required.

**Comment by bhousel** [comment]
I don't really understand the proposal very well, but I think it should be vetted by the tagging community.  If I am understanding it correctly, the proposal is "whenever a new object is created from an old object, store the old object id and old object version in tags".  

It's not clear to me who actually wants this, or how it would help.  If people in OSM actually want it, and JOSM implements it, then we'd implement it too.  But until it picks up more support, let's leave the issue as closed.
