### ISSUE TITLE
Walkthrough - line - does not allow you to complete

### ISSUE THREAD

**Issue by Nick-Tallguy** [openstreetmap/iD#3695]
![walkthrough-line](https://cloud.githubusercontent.com/assets/6763965/21543700/b53cb03c-cdc0-11e6-8978-4ff74f7fad0e.gif)

Following the walkthrough - not possible to complete the line item as it does not recognise that you have joined to Flower Street.  

I've also tried this from 'the other end' - starting with a node on Flower Street and going North, but again it still does not recognise that I have made a junction with Flower Street.

**Comment by bhousel** [comment]
Looking carefully at the code and at your screencast, I think I might know what happened.  It looks like you had already gone through this step in the tutorial already, and there is a leftover node at the junction, and you are able to connect your new way to the existing node (which normally wouldn't be there), and this confuses the tutorial.

I was able to reproduce this by performing this step, then deleting the line and trying the step over again.

**Comment by Nick-Tallguy** [comment]
Thanks for investigating this.

I've just had another try and can't reproduce my earlier problem. I've started with the 'line' section of the walkthrough and completed that section without a problem. I'm using the same computer, OS & web browser as I was before. 

Whatever was the problem seems to have disappeared now.

I suggest this issue is closed now, unless you have a reason to keep it open.

Thanks again.

**Comment by bhousel** [comment]
I improved the code so that it should better catch line intersections now.
