### ISSUE TITLE
Add "social_facility=" field to social facility preset

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#3702]

**Comment by polarbearing** [comment]
iD/data/presets/presets/amenity/social_facility/
only contains 3 values (food_bank, group_home and homeless_shelter) ?

In particular ```social_facility=nursing_home``` is missing, which was a recent clarification in tagging in contrast to non-nursing elderly group_homes. In the repository, I see nursing home only mentioned along with hospitals, where it does not belong.

**Comment by bhousel** [comment]
> In particular social_facility=nursing_home is missing, which was a recent clarification in tagging in contrast to non-nursing elderly group_homes. In the repository, I see nursing home only mentioned along with hospitals, where it does not belong.

Thanks for the suggestion, I added a nursing home preset in 3e2d6ae.
