### ISSUE TITLE
Pluggable geocoder in feature_list.js

### ISSUE THREAD

**Issue by sweco-semtne** [openstreetmap/iD#3711]
We are using Pelias as a geocoder over openstreetmap data and would like to extract the functionality in feature_list.js to be able to use a pluggable geocoder instead of directly calling nominatim. 
I'm thinking that it could be a service that can be setup in the context in the same way as the nominatim service.

A simple API like the one below could be enough

```
function geocode(searchTerm, callback) {}
```

The simplest way to do introduce this would be to:

- [ ] Introduce new service geocode with the api above (model the response after Nominatim)
- [ ] Import service in feature_list.js 
- [ ] Change the eventlistener in feature_list.js to call imported service

I know that nominatim is more or less the standard but it would be nice to be pluggable in this regard and I don't think it would be intrusive to the users in any way. The default service would of course be Nominatim.

**Comment by bhousel** [comment]
Good suggestion, I agree...

**Comment by sweco-semtne** [comment]
Could the current nominatim service be used if we add a function geocode? 
In feature_list.js

```
 import { services } from '../services/index';
 ...
 function geocode() {
            services.nominatim.geocode(search.property('value'), function(resp) {
                geocodeResults = resp;
                drawList();
            });
        }
```

And in nominatim.js

```
var endpoint = 'https://nominatim.openstreetmap.org/', 
   nominatimCache;

   ...
   geocode: function(value, callback) {
        var searchVal = encodeURIComponent(value);
        d3.json(endpoint + 'search/' + searchVal + '?limit=10&format=json', function(err, resp) {
            callback(resp || []);
        });
    }

```

**Comment by sweco-semtne** [comment]
Btw, what's the correct/best way of making a service pluggable for the developer without modifying the library code?

**Comment by bhousel** [comment]
Everything in the `services` module is designed to be swappable at runtime.  See [API.md#services](https://github.com/openstreetmap/iD/blob/master/API.md#services)

So after we fix the issues in this ticket, it should ideally be as easy as a line like this before your page initializes the iD context object.

```js
iD.services.geocoder = replacementService;
```

**Comment by sweco-semtne** [comment]
Great! And I just want to thank you for the great work you and everyone else that has contributed to iD has done!
