### ISSUE TITLE
Context dependent task offering

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3726]
ID is simple to use due to the context-dependent offering of operations. The proposed taskbar #3123 seems to break with this concept, and would require the user to select more JOSM like from a growing list of tasks. This would be a badly scaling approch.

We can make it better scaling and more convienient to use by context-dependent task offering. To do this the taskbar needs to show:
- normal icons for all active tasks
- grayed-out icon for inactive task which are matching iD's current mode and/or selection
- nothing for all other inactive tasks

Clicking icon should toggle active/inactive state of the task.

We can support two kinds of such tasks, a permanent one, which is active until toggled off, and a one-off task, which is automatically deactivated as soon as it is no longer matching mode and/or selection.

Examples:
- An indoor tool can be offered for activation (show as inactive in the task bar) when an indoor element is selected.
- A special drawing tool (e.g. orthogonal mode) for areas can be offered while the area drawing mode is active.
- A task overriding a large-feature protection can be offered when a large feature is selected, and it can be made a one-off task to prevent staying in an unsafe task mode over a long time.

The matching of inactive tasks to current mode and/or selection should be made asynchronously, this allows a very specific (and therefore time-consuming) matching even of a large number of tasks (e.g. due to plugins) without impairing iD's performance for normal operations.

**Comment by bhousel** [comment]
This isn't really what I had in mind for the taskbar.  I don't want it to be mode dependent or show greyed out icons at all.  

It's possible that my explanation in #3123 is not clear, or it might just not be what you want me to build.  Either way, can you keep discussion on that issue, rather than opening issues for features that haven't been built yet?  Thanks!
