### ISSUE TITLE
GPX file recognized but not editable

### ISSUE THREAD

**Issue by MavEtJu** [openstreetmap/iD#3732]
I have this trace Track___2017_01_04T17_39_19__auto_.gpx at http://www.openstreetmap.org/user/Edwin%20Groothuis/traces/2334208.

The track shows up nicely, however when I edit it on the map, the track doesn't show up there.

Could you tell me where it goes wrong in the GPX file as I have full control over that?

Edwin

**Comment by bhousel** [comment]
> The track shows up nicely, however when I edit it on the map, the track doesn't show up there.

Hi @MavEtJu, iD doesn't currently have the ability to actually import gpx traces.  It's up for consideration however, and this functionality is being tracked in #2586.

For now, users are expected to manually draw their own lines over the gpx traces.

**Comment by boothym** [comment]
@MavEtJu what is the visibilty set as for that trace, as I'm unable to access it.

**Comment by MavEtJu** [comment]
Don't worry, after some forward-and-backwards uploading of files I found out that the import parser didn't mind the absence of the various xls attributes in the gpx tag, while the editor didn't show the tracks unless these xls attributes where in the gpx tag.

See https://github.com/MavEtJu/Geocube/commit/2e234595425011d7058a8ac3374aa069311c2238 for the change I needed to make. Easy!

Edwin
