### ISSUE TITLE
iD freezes when opening this place

### ISSUE THREAD

**Issue by tadanet3** [openstreetmap/iD#3737]
Hi,

Browser freezes when opening this place.
https://www.openstreetmap.org/#map=17/34.69410/135.38259

I'm using Ubuntu16.10+Firefox.

**Comment by edpop** [comment]
+1 Windows 7, Chrome 55

**Comment by manfredbrandl** [comment]
also freezes for Chromium Version 55.0.2883.75 Built on 8.6, running on Debian 8.6 (64-bit)

**Comment by kepta** [comment]
I was able to reproduce this as well  on Chrome 55.0.2883.95 (64-bit), running on Mac OS 10.12.2.

**Comment by edpop** [comment]
That is because of http://www.openstreetmap.org/relation/6677259 (25085 members). Try to edit over any boundary of Japan.

**Comment by kepta** [comment]
@edpop while I agree with you that there are 25085 members, but I get different performances from [way 131022503](https://www.openstreetmap.org/way/131022503) (very slow) and [way 131019312](https://www.openstreetmap.org/way/131019312) (reasonable), while both being in the same [relation 6677259](https://www.openstreetmap.org/relation/6677259)

**Comment by bhousel** [comment]
Some discussion of this on #1201

**Comment by pnorman** [comment]
The relation is 1.2 MB and downloads in <1s on a fast connection. The relation/full is 102MB and 3m to download, but that's not currently used so not relevant for **this** bug. My guess is something in iD scaling badly on the relations member list and some operation is O(n^too much).

I think there's a data modeling error in the OSM data too, but it still shouldn't crash iD, just take longer for the /map call.

**Comment by bhousel** [comment]
> My guess is something in iD scaling badly on the relations member list and some operation is O(n^too much).

Agree w this.. It could be in the sidebar code that lists the relation members, or the code that attempts to class them with select halos, or the feature classifier/filters, other any number of other things.   It wouldn't surprise me if there are plenty of places in iD that are just not designed to handle a relation with 25k members.

**Comment by 07pepa** [comment]
Vivaldi 1.6.689.4 not afected! 👍
