### ISSUE TITLE
Vector data

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3742]
We will need to support vector tiled data for #3152 anyway, but there are other vector sources (e.g. QA layers) that would be great to bring into iD.

**Comment by pnorman** [comment]
> We will need to support vector tiled data for #3152 anyway, but there are other vector sources (e.g. QA layers) that would be great to bring into iD.

There's lots of types of vector layers, what are we looking at supporting?

**Comment by bhousel** [comment]
> There's lots of types of vector layers, what are we looking at supporting?

Not sure yet.  It might be worth having something like (or built into) `editor-layer-index` but for vector layers that are useful for editing.  This ticket is just to kick around ideas, and also to track that we need something like [vector-tile-js](https://github.com/mapbox/vector-tile-js).

**Comment by slibby** [comment]
#4164 provides a starting point for bringing in vector QA layers from ArcGIS-based services, if that is of interest. Not vector tiles, but along the same lines and I think the implementation (in the Map Data expando-tab) could be similar. #3452 also mentions this and might be one way that #4164 could be helpful to start (read-only QA layers from ArcGIS sources).

**Comment by bhousel** [comment]
CC @kriscarle for visibility - I proposed this as a GSoC project, and would be great to get this support into iD sometime soon.

**Comment by mmd-osm** [comment]
Just cross linking: https://www.openstreetmap.org/user/Princi%20Vershwal/diary/43802

**Comment by vershwal** [comment]
The first step towards supporting vector tiled data is that a user can add a URL and have the vector tiles show up on the screen. It will look something like this :

<img width="992" alt="screen_shot_2018-05-23_at_6 34 08_pm" src="https://user-images.githubusercontent.com/17474532/41250877-d7ccd058-6dd5-11e8-80b8-e107400775a7.png">


For this, I have added another layer 'mvt'. Currently, it will support .pbf(Protocolbuffer Binary Format) and .mvt(Mapbox Vector Tiles) format. These files contain data in Protocolbuffer binary format which is converted to geojson using mapbox's [vector-tile-js](https://github.com/mapbox/vector-tile-js) and this data is passed directly to the D3 draw functions to show up the tiles on the screen.
All the code related to this will be [here](https://github.com/openstreetmap/iD/pull/5072).

**Comment by vershwal** [comment]
For some details: https://www.openstreetmap.org/user/Princi%20Vershwal/diary/44151

**Comment by bhousel** [comment]
This happened 🎉

**Comment by sahithiduddukuri** [comment]
I have tried the first step towards supporting vector tiled data is that a user can add a URL and have the vector tiles show up on the screen. It worked and it displayed as :
![Screenshot from 2020-01-09 11-16-06](https://user-images.githubusercontent.com/22541694/72041824-9276c680-32d2-11ea-9998-3a8e8dca201b.png)

but the problem am facing is it is not loading on specific lat and long where it has to be. can you help me to fix this problem

**Comment by quincylvania** [comment]
> but the problem am facing is it is not loading on specific lat and long where it has to be.

@sahithiduddukuri Hmm I'm guessing that your data does not match the expected projection. Make sure it's in [WGS84](https://epsg.io/4326).

**Comment by sahithiduddukuri** [comment]
@quincylvania I tried working with mvt/pbf drag and drop using github code(https://github.com/openstreetmap/iD/issues/3742#issuecomment-396352744). Follwed the same and added few UI features to the code. Can you tell me will mvt file contains coordinates(lat,long) which specifies/instructs it to display on specific geo location. When i grag and drop an mvt file it is displaying in a specific location as shown in below picture [9.72/39.7075/-74.0209].
In mvt.js how can i change [ var feature = layer.feature(i).toGeoJSON(150, 194, 4);] to my specific location

![ID](https://user-images.githubusercontent.com/22541694/74084030-a445b800-4a90-11ea-880f-577609ab1197.png)
