### ISSUE TITLE
Don't write history in the middle of draw_line/draw_way, etc

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3750]
It turns out that it is really easy to create a lot of these degenerate geometries in iD that we've spent years trying to track down.  (1-node ways, 2-node areas, etc)

1. Start drawing a thing
2. ⌘R Refresh your browser
3. Restore history
4. Partially drawn thing exists..  Oops! 😱 

So we should really disable history writes while the user is _in the process of_ drawing stuff.

**Comment by tyrasd** [comment]
very good find, Bryan! :shipit:
