### ISSUE TITLE
add suburb to address field

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#3752]
Important address field is missing : Suburb.
Some users are adding suburb in "street" field, please add "suburb" field.

**Comment by bhousel** [comment]
Address formats in iD are localized, and some of the country-specific address formats do include a `suburb` field.
See [address-formats.json](https://github.com/openstreetmap/iD/blob/master/data/address-formats.json)

Which country do you need this for?  If you send details of how you want addresses formatted for your country, we can set it up.

**Comment by abdeldjalil09** [comment]
I'm from Algeria

**Comment by bhousel** [comment]
Ok, let us know which OSM address tags should display in the address field.

**Comment by bhousel** [comment]
Hey @abdeldjalil09 just checking in.  This would be a really easy issue to close.
Can you let us know where the `suburb` field should appear in the address?  Thank you..

**Comment by bhousel** [comment]
Closing as stale

**Comment by abdeldjalil09** [comment]
Why the issue is closed ??? It's not resolved !

**Comment by bhousel** [comment]
We don’t know how to add this field without more information.

**Comment by 1ec5** [comment]
Specifically, we’d need to know where in a mailing address you’d expect to see the value of the `addr:suburb` tag. Mailing address formats differ from country to country.
