### ISSUE TITLE
Add language debugging mode

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3755]
This is an idea from today's show-and-tell which would help translators a lot.

It would be great to be able to switch iD into a mode where instead of the translation strings, you just see the translation keys.  This in itself isn't too hard to do by changing what [ the code in `locale.t()`](https://github.com/openstreetmap/iD/blob/master/modules/util/locale.js#L25) does.

The tricky part is that there are probably lots of components of iD that are only entered once and never updated again.  When switching the language, we'd really need to rebuild the ui from scratch.  [This code is in `ui/init.js`](https://github.com/openstreetmap/iD/blob/master/modules/ui/init.js) and is really not designed to be rerun.  It might be ok to preserve some of the map state and throw out all that stuff and reenter it - I don't know.  It's like how iD can switch in and out of the walkthrough, but probably more complicated.

This would enable #3120 too (switching languages on the fly).

**Comment by bhousel** [comment]
So, I did this today:

<img width="1279" alt="screen shot 2017-01-26 at 11 48 18 am" src="https://cloud.githubusercontent.com/assets/38784/22341036/74e7f088-e3bd-11e6-86a9-64e13cb9be9a.png">

It's kind of weird but it works.. Is this something that would be useful to people doing translations?

The idea is that now iD can switch languages on-the-fly, and I added a special language called `_tkeys_` that shows the keys instead of the strings.

Right now toggling languages can only be done through the dev console (we can add a proper field to pick the language later, closing #3120):

```js
id.ui().restart('it')
id.ui().restart('ru')
id.ui().restart('zh')
id.ui().restart('_tkeys_')
```

cc @1ec5 @manfredbrandl @slhh @tyrasd

**Comment by 1ec5** [comment]
Yes, that could be useful for zeroing in on an incorrect translation I spot while using iD. I sometimes use a similar mode when translating MediaWiki ([example](https://en.wikipedia.org/wiki/OpenStreetMap?uselang=qqx)), although fortunately Transifex’s search engine is much more usable than Translatewiki.net’s.

More commonly, I need to go in the other direction while translating in Transifex: figuring out where a string marked for translation is used within iD. For that purpose, I usually head over to this repository’s commit history and root around for the relevant change. (Thank you for descriptive commit messages!) One way to improve this workflow would be a mode where untranslated UI elements are highlighted prominently or greeked (replaced with lookalike ¢ħª®ä©¯ţǝ®§ or emoji).

**Comment by magol** [comment]
Another improvement is if you add a link to the Git commit in the transifex comment for each string.  In that way,  i can easy go directory to the relevant commit.

**Comment by bhousel** [comment]
Thanks for the feedback @1ec5 and @magol...

There isn't a great way to go from Transifex back to iD, aside maybe from looking at the key itself and then doing a search in the iD source code.  Even that is not great because it requires some familiarity with how the code draws the UI.

E.g. search for this key, or some part of it:

<img width="280" alt="screenshot 2017-01-27 10 19 58" src="https://cloud.githubusercontent.com/assets/38784/22376063/884472ce-e47a-11e6-8653-ad8df2664bd5.png">

Anyway I'll close this for now, and you can use the method above to switch languages until we close #3120

**Comment by bhousel** [comment]
BTW for anyone following this issue, I just setup the master mirror (#3912) so that it also pulls the latest translations from Transifex.  That means that every 10 minutes that mirror will have the latest code from master along with the latest translation strings applied on top of that code. 

I hope it will be helpful so that translators can see the effects of their work pretty quickly.  This will be useful because when #3921 lands, there will be a lot of translation work to do.
