### ISSUE TITLE
ID Editor v2.0.2 getting Fuzzy sections of USGS Topo map, why

### ISSUE THREAD

**Issue by gregcrago** [openstreetmap/iD#3757]
![fuzzy topo in id editorpng](https://cloud.githubusercontent.com/assets/7635234/21935007/95f7d0a2-d960-11e6-9ec9-3ef6495394c2.PNG)

When sliding around in Openstreetmap using USGS Topo overlay, I sometimes get extremely low resolution sections (see attached pic). I have tried Firefox and Google Chrome, both show the same low resolution sections. You can see that a higher resolution Topo does exists for this area.

**Comment by bhousel** [comment]
Thanks for the report.. There might be something going on with the USGS maps.  We have some discussion here https://github.com/osmlab/editor-layer-index/issues/151 about it.

The [editor-layer-index](https://github.com/osmlab/editor-layer-index) project is the best place to discuss issues with imagery layers in iD.  If the issue persists after a few days, can you open a ticket there including map coordinates where you see the artifacts?  Thanks!
