### ISSUE TITLE
Differentiate styling of connected vs unconnected node

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3775]
![screenshot 2017-01-18 18 36 25](https://cloud.githubusercontent.com/assets/38784/22065185/12ebda0e-ddad-11e6-8133-3410ee6cb1fb.png)

Connected nodes are already drawn with gray fill, but disconnected nodes are not drawn at all unless highlighted.  We should consider making this a little more obvious so people can see where ways are not connected.

Some ideas include:
* adjust the size or shape of the endpoint vertex if disconnected.
* render endpoints always (not just when selected).

**Comment by bhousel** [comment]
Endpoint vertices are now always drawn, and they're drawn slightly larger if not connected to anything.

Here's an example where I disconnected a parking aisle to show the difference.
<img width="220" alt="screenshot 2017-01-23 22 15 54" src="https://cloud.githubusercontent.com/assets/38784/22232858/111a9ad8-e1ba-11e6-99cc-844e11a7f2e6.png">

It does change slightly how some other map features look, but I think people will get used to it.  It is ok for people to pay slightly more attention to endpoints.
<img width="220" alt="screenshot 2017-01-23 22 24 36" src="https://cloud.githubusercontent.com/assets/38784/22232972/c514f8bc-e1ba-11e6-81c7-20917ba4af24.png">

**Comment by boothym** [comment]
Hmm they are quite big, though as you say people will get used to it. The more noticeable thing for me is the ends of hedges, wall, etc. which now appear to be much bigger than the line they represent,
