### ISSUE TITLE
Use Pt: wiki pages in pt-BR iD

### ISSUE THREAD

**Issue by virgilinojuca** [openstreetmap/iD#3776]
Recently, the Portuguese (`Pt:`) and Brazilian Portuguese (`Pt-br:`) wikis were unified into a single namespace (`Pt:`) so that the Portuguese-speaking community can join forces. There are no `Pt-br` pages with content in the wiki anymore. All of them were either merged with their correspondent `Pt:` pages or moved to `Pt:`. That means that the old `Pt-br:` pages are just redirects now.

So now we have a problem in iD. Currently, when in the pt-BR interface, which will continue to exist, iD looks up for documentation in the now deprecated `Pt-br:` namespace, so we only get a warning that the page was moved (#3337). Can you guys change the lookup namespace to `Pt:` in the pt-BR iD?

**Comment by bhousel** [comment]
Ok, I guess this is a step further beyond #3337.  Can someone else (@naoliv?) confirm that all `pt-BR:` pages on osm wiki are now just redirects to `pt:` pages?   If so, I'm fine with special casing this instead of showing the redirect text.

**Comment by naoliv** [comment]
Verified and they are all redirects now.
