### ISSUE TITLE
Make it clearer that the user needs to do something to save

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3777]
Sometimes a new user hits "Save", then thinks they are done and just continues editing, not realizing that they need to click another "Save" button.

We could callout the save panel somehow (motion?), and/or darken the map.  Also maybe consider renaming the "second" save button to "Upload"

![screenshot 2017-01-18 18 44 04](https://cloud.githubusercontent.com/assets/38784/22065576/ddaae162-ddae-11e6-9e8a-a607bf5b2c3a.png)

**Comment by boothym** [comment]
> Sometimes a new user hits "Save", then thinks they are done and just continues editing,

But you're unable to click on an object in the editing screen until you either save or cancel - or do they just close the tab? (though that should give a warning about unsaved changes from the browser)

**Comment by kepta** [comment]
@bhousel, since we are talking about the save button. 
It would be really nice to add an icon next to  `save` button (or whatever we rename it) to make it consistent with other buttons in the `bar`.

**Comment by bhousel** [comment]
> It would be really nice to add an icon next to save button (or whatever we rename it) to make it consistent with other buttons in the bar.

Yes I agree.. Just not a floppy 💾

**Comment by bhousel** [comment]
see also #2378

**Comment by bhousel** [comment]
Here's what I did:

- [x] When entering Save mode, map content transitions inactive: appears grayscale and dims slightly so colorblind users perceive a change.  The sidebar controls still let the user review their edits, or return to editing to address any warnings.
- [x] Adjusted the language a little bit "Save" -> "Upload" to make it clear that an Upload needs to happen.  No more 2 Save buttons. 👍 

This along with the previous changes in #2378 should make it impossible for a user to ignore that they have an extra step to complete in order for their changes to save.

![save inactive](https://cloud.githubusercontent.com/assets/38784/22258328/2a3337bc-e22f-11e6-8fda-bbbb7bb5316a.gif)

**Comment by bhousel** [comment]
Leaving this open so we can 
- [ ] Add Icon to Save Button

**Comment by tyrasd** [comment]
> Adjusted the language a little bit "Save" -> "Upload" to make it clear that an Upload needs to happen.

:+1: That should also improve the occasional confusion of users who don't realize that by clicking on "save" their changes actually get published for everyone (like this recent example: https://www.openstreetmap.org/changeset/45246084).

**Comment by bhousel** [comment]
Added the icon, looks nice 👌 
<img width="555" alt="screen shot 2017-01-25 at 11 59 11 pm" src="https://cloud.githubusercontent.com/assets/38784/22320497/db955b62-e35a-11e6-9bf3-05041f755bbe.png">

I also redrew some of the icons for consistency
