### ISSUE TITLE
building=train_station

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3779]
Just wondering why building=train_station is unsearchable? https://github.com/openstreetmap/iD/blob/c8e4f76c230512dc82dc060bf337e3ba489b113e/data/presets/presets/building/_train_station.json

**Comment by bhousel** [comment]
I'm not sure, but I think it's to encourage people to use the `railway=station` tag instead.

**Comment by boothym** [comment]
The reason I raised it is because there are many other building presets available, but no "Train Station Building", and I was surprised it was made unsearchable as if it was deprecated. Railway=station is a separate tag which should only be used once per station, but you can have multiple train_station buildings.
