### ISSUE TITLE
Allow saving without changeset comment

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#3781]
I perceive iD as a quick editor when you make a lot of small changes and save them often. So why is it mandatory to define a comment when saving? It could be resonable with extended support of changesets but it is not the case with iD and other tools allow saving changesets without comments.

**Comment by pnorman** [comment]
👎

Quoting https://wiki.openstreetmap.org/wiki/Good_changeset_comments

> There are situations where it is evident what a changeset is about – especially if it affects only a single object – but these situations are less common than you might think. If you have fixed a typo, a changeset comment of "fixed typo" still makes it clear that this was indeed what you intended, rather than your cat playing with the keyboard again!

I think this change would do more harm than good.

**Comment by yaugenka** [comment]
Imagine you make 100 different small changes a day several times a week. Just ask yourself how often you would input a meaningfull comment each time you save your changes? Instead of thinking what to put in the comment I would rather spend this time on drawing something valuable on the map.

**Comment by manfredbrandl** [comment]
There were days I did save 100 oder more times with small changes. Often the last changeset comment was good enough, sometimes I had to choose a new one, which is no problem as there are suggestions when you start typing. There was an annoying problem with duplicate suggestions, which was resolved recently.

**Comment by yaugenka** [comment]
Possibility to view object history would give much more benefit.

**Comment by Abbe98** [comment]
@manfredbrandl there should still be suggestions...

**Comment by tyrasd** [comment]
> Update: No suggestions any more, I miss them.

Can you please open a new ticket for that. I think this is a unwanted regression. See also #3759

**Comment by yaugenka** [comment]
JOSM is the master in changeset management but does not push you to define a comment. Neither Postatch does. It is good recommending but not forcing. If someone does not want to define a comment making the field mandatory won't make them do it, they will just use some meaningless one, which is worse than none.

**Comment by yaugenka** [comment]
Please link this ticket to 3374.

**Comment by bhousel** [comment]
(to link an issue, just type the issue number with a #)

see #3374, and all the related tickets that appear before it for why iD require users to enter a comment.  tldr: most people want this and it's not worth arguing over.

> If someone does not want to define a comment making the field mandatory won't make them do it, they will just use some meaningless one, which is worse than none.

I'm ok with this.

> JOSM is the master in changeset management but does not push you to define a comment.

So use JOSM.

**Comment by yaugenka** [comment]
> So use JOSM.
@bhousel I understand that references to other mapping tools irritate iD developers a lot, but both JOSM and Potlatch are community driven project like iD and my point of mentioning them was in that there have already been really many discussions around this topic.

**Comment by boothym** [comment]
What difference would it make anyway, given all your changesets seem to have a comment of `нз`? ;-) I think the benefits of requiring a comment from new users outweigh the small inconvenience for experienced users.

**Comment by yaugenka** [comment]
There is no sense continue arguing between two or three of us. Let's better wait for comments from others.

**Comment by Nick-Tallguy** [comment]
I happily add a changeset comment whatever editor I'm using & I train many people for 'missingmaps' and HOT, also trying to train them to add something meaningful.   
In attempting to work out what has happened and when in the history of an object I find the comments can be useful.  
**But** I also spend many hours clearing up and trying to sort out areas for HOT and Missing Maps, and my changeset comment is often the repetitive tags provided by a 'Tasking Manager' followed by my comment similar to 'squared a few buildings, corrected a few and adjusted the highways'. 
Under my particular circumstances a 'unique' comment would be pretty well impossible, but hopefully someone exploring the history of something I have 'tidied' would gain an insight from it.
.
Overall I'd go with 'a comment is useful'.

[Tallguy](http://www.openstreetmap.org/user/Tallguy)

**Comment by bhousel** [comment]
@yaugenka I'm sorry if I was short in my replies before, but this topic has come up many times over the years, and I interpreted your suggestion as trolling our issue list, rather than an earnest suggestion that dropping the comment requirement might somehow improve the quality of submissions to OSM.

Try to remember that there are many kinds of users who contribute to OSM through iD, and our primary design goal is not to make editing as efficient as possible, but rather to guide new users towards being productive members of the OSM community by steering them towards current best practices.

It does not take very long to add a comment to your edits.  In most cases my comment is something like "traced some buildings" or "road and landuse cleanup around [place]".

I'm locking this topic for now because we don't need to discuss it any further, and I'm not going to change what iD does anytime soon.
