### ISSUE TITLE
Translating highway, road, street etc.

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3792]
I translate iD into german and I want correct and coherent words for highway, road, street, etc.
In german "Weg" (way ?) is the most general word for a part of the landscape to move people and goods, i.e. "Straße" (street ?) "Schienenweg" (railroad), "Wasserstraße" (waterway), and even "Seilbahnen" (aerial way).
In iD sometimes highway is used as the general word ("highway such as roads and path should ..."), sometimes road is used for this pupose ("Roads can be all kinds: path, highways, trails, cycleways, and more ...")
Maybe someone can help me and write a hierarchy of english words as for "Weg" in German:
"Weg" is for "Straße", ... , "Seilbahn"
"Straße" is for "Autobahn", "Schnellstraße", ... , "Wohnstraße".

**Comment by pnorman** [comment]
> In iD sometimes highway is used as the general word ("highway such as roads and path should ..."), sometimes road is used for this pupose ("Roads can be all kinds: path, highways, trails, cycleways, and more ...")

This sounds like a bug if we're saying roads include paths and highways include roads and paths.

**Comment by bhousel** [comment]
> "Weg" (way ?) is the most general word for a part of the landscape to move people and goods, 

**"Way"** probably is the most generic English word for this also, but unfortunately has a special meaning in OSM so I try to avoid using it in this context.  In OSM anything can be a way, so people with prior OSM knowledge will be confused if we use "way" to mean only roads and paths.

> In iD sometimes highway is used as the general word ("highway such as roads and path should ..."), sometimes road is used for this pupose ("Roads can be all kinds: path, highways, trails, cycleways, and more ...")

I see what you mean.  We can use the generic word **"Road"** everywhere to mean "anything that's a line with a `highway=*` tag".  If "Wege" is the best German translation for "Road", that is ok.

To keep this consistent I'll change the English translation for that validation message:
_"highway such as roads and path should ..."_  to simply say _"roads should ..."_

**Comment by manfredbrandl** [comment]
Strictly speaking road should be translated as "Straße", but wherever iD uses road as a generic word I will try to translate that with "Weg".

**Comment by bhousel** [comment]
> So road is more general than street, which other feature are roads but not streets?

The wording here in the help screen seems ok to me:

<img width="300" alt="screenshot 2017-01-25 11 11 02" src="https://cloud.githubusercontent.com/assets/38784/22298569/fe504e12-e2ee-11e6-94c4-360de95eb220.png">

**Comment by bhousel** [comment]
I changed the validation message in d0ee157, let me know if there are any other messages we need to adjust, or close if it looks good 👌

**Comment by manfredbrandl** [comment]
Thank you, it may not be perfectly coherent now, but it's usable and that's enough.
