### ISSUE TITLE
Add new Bing imagery for Brazil

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#3793]
See https://blogs.bing.com/maps/January-2017/Over-8-5M-Square-Kilometers-Imagery-for-Brazil-Rel/

**Comment by bhousel** [comment]
There isn't anything we need to change in iD to get the new imagery.  If you use the Bing background layer, you'll see it as soon as Bing updates their imagery tiles and caches expire.

**Comment by picsi** [comment]
Thanks for the clarification!
