### ISSUE TITLE
Support OpenStreetCam

### ISSUE THREAD

**Issue by mvexel** [openstreetmap/iD#3795]
Let's work on supporting displaying OpenStreetCam (OSC) imagery in the same vein as the Mapillary layer.

What's needed right off the bat: 
* GeoJSON endpoint for OSC image locations 
* Endpoint for retrieving individual images

@alexandrui-telenav or a team member can help out from the OSC side.

**Comment by bhousel** [comment]
Sounds great!  I'm happy to help out with the implementation 👍

**Comment by mvexel** [comment]
We are looking at API support at the moment. Will check back in here when we know more. /cc @alexandrui-telenav

**Comment by mvexel** [comment]
I'm taking a stab at this.

**Comment by bhousel** [comment]
Updating status here - I've got some apidoc to work off of and will probably have something to show soon 🙏

**Comment by bhousel** [comment]
Done in #4499
