### ISSUE TITLE
Issue with dragging nodes on multipolygon outers

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3799]
The nodes on this multipolygon can't be dragged.
http://localhost:8080/#background=Bing&id=r276895&map=16.77/40.37391/-74.93380

**Comment by slhh** [comment]
Here is a non-local link:
https://openstreetmap.us/iD/master/#background=Bing&id=r276895&map=16.00/40.3769/-74.9077

The nodes can't be dragged when the multipolygon is selected, but they can be dragged when the way is selected.
