### ISSUE TITLE
Do something with the Mapillary viewer if WebGL not supported

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/iD#3804]
Mapillary images don't seem to show in Chrome (Mac). Safari does seem show them.

(The yellow markers do appear fine.)

However, I sometimes find that the image appears very briefly after clicking on the yellow marker, but then reverts to the blank display.

![screen shot 2017-01-27 at 10 38 58](https://cloud.githubusercontent.com/assets/361423/22368131/f71128b2-e47c-11e6-85e8-02f2199db095.png)

**Comment by bhousel** [comment]
I just tried this with Chrome 55.0.2883.95 on mac and it seems ok.
[direct link](http://www.openstreetmap.org//edit?node=1241742627)

Can you try again and let me know if you see any error messages in a dev console?  Maybe there was a network issue?

![screenshot 2017-01-27 08 36 23](https://cloud.githubusercontent.com/assets/38784/22372632/cd11af02-e46b-11e6-9e07-c18559a6eedd.png)

**Comment by mvl22** [comment]
Apologies - I should obviously have checked the console output.

Yes, there are WebGL errors:

![screen shot 2017-01-27 at 16 37 56](https://cloud.githubusercontent.com/assets/361423/22378882/17a07a1a-e4af-11e6-9f99-ff110e4cbbb1.png)

**Comment by bhousel** [comment]
No worries!  There isn't much we can do about this from the iD side, so I'm going to close the issue.

If the viewer can't create a WebGL context, there are many reasons why.  You could have some resource constraint (lot of tabs open using WebGL), or you might have an unlucky graphics driver/hardware combination that is on the Chrome blacklist (some info [here](https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists)).  You might be able to force it to work [using some of the tricks described here](http://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser).

**Comment by mvl22** [comment]
Would it not be sensible to attempt to catch the error, and in that scenario, give the user some indication? At present it just looks like the feature doesn't work, giving no indication what the problem could be or what to do about it.

Even overlaying in the box a simple overlaid textual message "Could not launch WebGL - system resources limited, or check your browser settings" would at least give some indication.

**Comment by bhousel** [comment]
I think that would depend on https://github.com/mapillary/mapillary-js/issues/165, but I can leave this open pending an implementation upstream.

**Comment by bhousel** [comment]
Looks like the update in #4310 includes a feature we can use for this.

**Comment by bhousel** [comment]
I added this - Mapillary viewer will be put into a fallback mode when WebGL is disabled.

<img width="1013" alt="screenshot 2018-01-26 16 27 11" src="https://user-images.githubusercontent.com/38784/35461436-f49c0496-02b5-11e8-90c7-473abad82a2f.png">
