### ISSUE TITLE
Cannot select lines or areas

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#3805]
This reminds me of #2151, but is different because I can still select points.

When I mouse over lines or areas they highlight and the cursor changes, but not happens when I click. Points work. I had been zooming in and out shortly before this.

Going through some of the debugging steps from 2151,

```
id.mode()
Object {id: "select", button: "browse"}
```

The `getHistory` JS returns null.

I went away and did some stuff, came back, turned on pause on caught exceptions, and it was working again.

Hard to say what caused it to work again.

Browser is 55.0.2883.87 on Windows 8.1

**Comment by jayuk1** [comment]
Same issue for me. I want to delete some areas that have been added incorrectly.  The area highlights, but thats it.

**Comment by magol** [comment]
It is the same for me to 😕

**Comment by bhousel** [comment]
@jayuk1 can you share the map URL linking to an area that won't delete?  Also browser/os details would be helpful.  Just saying "me too" doesn't help me figure out the issue.

**Comment by magol** [comment]
Most times im using id,  i can not spelet any ways or areas. I can only select nodes.  
I have windows 7 and chrome.

**Comment by boothym** [comment]
Same happened for me when editing on Chrome/Win10, never had a problem with Firefox.

**Comment by scaidermern** [comment]
[Related question at help.openstreetmap.org](https://help.openstreetmap.org/questions/54353/problem-with-id-editor).

**Comment by bhousel** [comment]
Still having trouble reproducing this issue.  I did try today with Chrome 56 and Windows 10.

**Comment by afmenez** [comment]
Same problem here with Firefox 51 and Windows 10.

**Comment by bborkmiller** [comment]
Ditto. I'm also experiencing #3824. The symptoms for both: When I hover over a line, area, or node, it highlights, but clicking does not select it. If I hold down shift, I can select the object. Sometimes even this fails, and I have to click around on different parts of the line before it gets selected.

Clearing the selection is also affected: Clicking in an empty area doesn't clear the selection. I have to press escape.

I'm on Chrome 55.0.2883.87 on Windows 7. Sorry this bug has reared its head again!

**Comment by bborkmiller** [comment]
OK, this is weird. I'm not sure if this will be helpful, but [I'm editing in this area](http://www.openstreetmap.org/edit#map=18/44.74652/-85.52830). The selection bug is happening to me right now. I can readily select most of the ways in this area by shift-clicking, but some of them are reliably hard to select, and often (although not always) take multiple clicks. The hard ones (in this area) are the one-way ways: the stream and the drive-through service ways. I also have trouble with the bridge section of the cycle path. Bizarre, right??

**Comment by boothym** [comment]
> Ditto. I'm also experiencing #3824. The symptoms for both: When I hover over a line, area, or node, it highlights, but clicking does not select it. If I hold down shift, I can select the object. Sometimes even this fails, and I have to click around on different parts of the line before it gets selected.

Clearing the selection is also affected: Clicking in an empty area doesn't clear the selection. I have to press escape.

I've been editing with Chrome to try to reproduce this again and it finally reappeared as described above. I was editing on and off for an hour or so without saving, and it also affected an instance of the Strava iD editor I had open (looking at heatmap data). Even after saving I could not select anything, closed both tabs but kept browser open but the problem persisted.

**Comment by hanchao** [comment]
I can reproduce it. @bhousel 

Chrome 56.0.2924.87 (64-bit) Windows 7

1.close and reopen chrome
2.open https://openstreetmap.us/iD/release/#background=Bing&map=18.05/39.91752/116.48161
3.open new tab. 
4.Back to id. Move mouse to the building(家乐福超市) ,click。 Cannot select the building.

**Comment by auhsor** [comment]
I can also reproduce the above around 75% of the time.

Chrome 56.0.2924.87 on Windows 10.

**Comment by homersimpsons** [comment]
Have this problem too (chrome 56.0.2924.87, windows 7), except that I can't select node too (using shift allow me to select).

**Comment by dkewley** [comment]
I'm on ChromeOS 57.0.2987.146 (Chromebook). I've used iD quite a bit this past week or two, and have noticed no behavior like that described here.

I tried hanchao's reproduction steps (except for step 1, closing and reopening Chrome, which is less convenient when it involves restarting the OS). Also, his iD link no longer works, so I simply used his coordinates in standard iD: http://www.openstreetmap.org/edit?editor=id#map=18/39.91752/116.48161.

It worked fine for me on three successive tries. So it does look like it may indeed be not only browser-specific (Chrome), but also OS-specific (Windows).

**Comment by pnorman** [comment]
> So it does look like it may indeed be not only browser-specific (Chrome), but also OS-specific (Windows).

#2151 was, so it's not surprising that this is too.

**Comment by bhousel** [comment]
I spent a lot of time on this issue today, but still can not reproduce it with Windows 10 and Chrome 58.0.3029.81.

I haven't found any obvious places in the code to change either.

Are people still able to reproduce this issue here?:   http://preview.ideditor.com/master

There were a handful of other issues that have been fixed recently that might have also fixed this.

**Comment by afmenez** [comment]
I reported this above, but it was a misunderstanding of the new select/drag behavior.  It is working for me.

**Comment by magol** [comment]
I have test the preview, and I have not seen the issues at all. Now it is usable again 😁

**Comment by homersimpsons** [comment]
Just experiencing this in 2.3.1, but using http://preview.ideditor.com/master works.

**Comment by Stalfur** [comment]
Had the bug on live, opened another tab with preview-editor and that worked fine. Looking forward to this being solved finally.

**Comment by quincylvania** [comment]
Closing this as stale and probably fixed. Let us know if it's still an issue.
