### ISSUE TITLE
Rotate map + Rectangle regions

### ISSUE THREAD

**Issue by jeffallen** [openstreetmap/iD#3817]
When making buildings in a village where the dominant floorplan is a simple rectangle (lots of places in Africa) being able to click two corners of a rectangle would be useful. And doing so on a grid that lines up with the streets would be easier as well. Take for instance Maiduguri, Nigeria. I would like to be able to rotate the map until the streets were horizontal/vertical, and then put rectangles on houses one after another, boom boom boom.

**Comment by pnorman** [comment]
I think this is covered by #528

**Comment by bhousel** [comment]
Yep, square building tool is coming soon.  It's becoming the "Duke Nukem Forever" of iD issues, but I did build one a little while ago and it worked great.

**Comment by kepta** [comment]
Dude Nukem forever 😂😂
