### ISSUE TITLE
Add support for Pic4Carto.js

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#3818]
Pic4Carto shows on the map geotagged images from not only Mapillary but also Wikimedia Commons and Flickr. An excellent mapping aide!

https://wiki.openstreetmap.org/wiki/Pic4Carto

**Comment by bhousel** [comment]
Is it a service with an API that iD can talk to?

**Comment by Abbe98** [comment]
@bhousel it seams to be a Leaflet plugin connecting to all the different APIs...

**Comment by picsi** [comment]
See more at https://framagit.org/PanierAvide/Pic4Carto

**Comment by PanierAvide** [comment]
Yes it is a client-side library to abstract pictures retrieval from several providers (mapillary, wikimedia commons, openstreetcam and flickr). By calling a simple function, you can retrieve all available pictures in an area. The function will call every API and give all the pictures in a simple format.

**Comment by bhousel** [comment]
I thought about this more and I don't think that fetching geotagged images in Wikimedia commons is likely to help mappers any more than the existing streetlevel photo services do.  Sorry, but I'm closing this.
