### ISSUE TITLE
highway = track: dropdown missing

### ISSUE THREAD

**Issue by speedbiker** [openstreetmap/iD#3823]
Since the latest version of ID-Editor is online, on the left side of screen, where taggs for highway = track can be choosen, the option/dropdown field concerning the grade of the highway is missing. Previously it was possible to choose between 4 grade types: grade 1, grade 2, grade 3 and grade 4. 
I mean, this tag is pretty important for this kind of highway, because the track/line is also visualized differently on openstreetmap.org.

**Comment by bhousel** [comment]
Because of it's importance, the tracktype field was moved up to the top position, see #3718 

<img width="250" alt="screenshot 2017-02-05 16 19 44" src="https://cloud.githubusercontent.com/assets/38784/22629968/f110668c-ebbe-11e6-9d1d-68eadd6075d8.png">
