### ISSUE TITLE
Merging lines with certain relations should be warned/forbidden

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#3825]
When merging lines (roads, rivers) with differing relations of some types (borders!), the user should be at least warned of the change.

**Comment by bhousel** [comment]
> When merging lines (roads, rivers) with differing relations of some types (borders!), the user should be at least warned of the change.

Can you give an example?  I thought that iD already prevents merging lines in some cases because they belong to relations.

**Comment by afmenez** [comment]
Sure.  Let's say a have a city limit that coincides with a river (like this one: http://www.openstreetmap.org/way/472662123).  In this case, only the river is shown on the editor interface (even when the line is selected you have to scroll way down to see that there's a relation attached to the river).  You can then shift select an adjacent section of the river (like this one http://www.openstreetmap.org/way/472662128) and merge them.  This should't be possible, or at least a warning should be given before the merge.
