### ISSUE TITLE
iD don't permit move individual nodes. Only delete it

### ISSUE THREAD

**Issue by CarlosBrys** [openstreetmap/iD#3829]
Trying to move an individual node, selecting it only appears the option to delete it
![captura de pantalla de 2017-02-07 09-34-12](https://cloud.githubusercontent.com/assets/6495550/22693360/b9f183ac-ed21-11e6-8a41-592edc0ca8f8.png)
![captura de pantalla de 2017-02-07 09-33-59](https://cloud.githubusercontent.com/assets/6495550/22693361/b9f6022e-ed21-11e6-9b18-c908a9ce1c0f.png)

**Comment by edpop** [comment]
Can't select any feature, except by lasso-selection on Win 7 Chrome 56.0.2924.87. In Firefox all works fine.

**Comment by bhousel** [comment]
> Trying to move an individual node, selecting it only appears the option to delete it

Once selected you should just be able to drag the node around.  Does this not work?  What browser/os?

**Comment by neuhausr** [comment]
I can reproduce this issue in FF and Chrome on Windows 7

**Comment by skorasaurus** [comment]
Confirmed; Firefox 51.0.1 64-bit, Linux and Chrome Version 56.0.2924.76 (64-bit)

**Comment by pertile** [comment]
Windows 7 and Mozilla 51.0.1 (32-bit). I can move a node when it's on on a way, but I can't when the node is alone.

**Comment by manfredbrandl** [comment]
Google Chrome Version 56.0.2924.87: Can't move points either.

**Comment by bhousel** [comment]
Thanks, I realized that in fixing dragging hovered vertices in 919234d, I broke dragging nodes. Sorry!

I just made some changes to make this code a bit easier to read, and I tested all the different dragging situations that I could think of.
