### ISSUE TITLE
Automatically add operator:wikidata=* when using a preset for a common franchise

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#3831]
For example, if I'm going to use the McDonald's iD preset to tag a restaurant, it would automatically add `operator:wikidata=Q38076`. 

The tag `brand:wikidata=*` can also be conceivably be used if any iD presets make use of `brand`.

**Comment by pnorman** [comment]
I thought there was a previous discussion on automatically adding wikidata tags other than wikidata=* which concluded against it, but can't find it.

Note: the common franchise stuff is coming from another repo, so changes would be needed there first.

**Comment by bhousel** [comment]
I'm not against the idea, but if we end up doing this, the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) project is the place to add it.

**Comment by picsi** [comment]
Thanks. This is the relevant discussion there if anyone is interested: https://github.com/osmlab/name-suggestion-index/issues/38
