### ISSUE TITLE
Enhance presets for information=guidepost and information=map

### ISSUE THREAD

**Issue by Hufkratzer** [openstreetmap/iD#3832]
Please add an easy way for [information=guidepost](http://wiki.openstreetmap.org/wiki/Tag:information=guidepost) and [information=map](http://wiki.openstreetmap.org/wiki/Tag:information=map) to add "yes" for the types of routes / activities (hiking, bicycle, mtb, horse, ski) to which the guidepost / map corresponds. (One should not need to look into the documentation to find out how it shall be done.)

In JOSM the presets forms look like this:

![josm-guidepost](https://cloud.githubusercontent.com/assets/5958184/22762617/a06efe9c-ee60-11e6-84ae-0a228fec8564.jpg)

![josm-map](https://cloud.githubusercontent.com/assets/5958184/22762625/a8b59ed0-ee60-11e6-8a81-0c18ed732dfd.jpg)

(You may perhaps find it strange to use these tags for this purpose. That may be true but it is nevertheless done and documented like this for 7 years now, it was described that way (for hiking, bicycle and ski) already in the [Initial Version of Key:information](http://wiki.openstreetmap.org/w/index.php?title=Key%3Ainformation&type=revision&diff=363962&oldid=320435) )

**Comment by bhousel** [comment]
Hmm, I don't really think that's a very good ui for adding the kinds of information that appears at a guidepost or trailhead.  If we could use a multicombo for this, it would be a lot cleaner.  

Can we change the tags to use `information:hiking=yes`, `information:cycling=yes`, etc.. ?

**Comment by Hufkratzer** [comment]
The ui can perhaps be a multicombo, but to change the tag names is probably next to impossible, they are already used a lot (see [taginfo guidepost](http://taginfo.openstreetmap.org/tags/information=guidepost#combinations) and [taginfo map](http://taginfo.openstreetmap.org/tags/information=map#combinations) ) and for a long time yet. They would have to be changed in many places simultaneously (database, wiki in different languages, other editors, unknown number of data consumers).

**Comment by bhousel** [comment]
Yeah I feel pretty icky reusing the `access=*` tags for information guideposts.. Let's not do this.
