### ISSUE TITLE
Second Sidebar for Plugins

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3836]
This is an idea to provide an user interface for a class of plugins (or internal tools) with very litte impact on the normal UI. There is only one always visible button required to open the second sidebar. This could be a small arrow button on the border of the inspector sidebar.

The second sidebar should open on the left side of the inspector sidebar in order to keep mouse movements between both sidebars short.

There should be the following controls on top of the second sidebar:

- A "Get" button to take the current viewport and selection from the map. In case the most recently used plugin fits to viewport and selection, it's taking control of the second sidebar.
Otherwise a selection list of fitting plugins is offered in the second sidebar.
- A button to show this selection list upon request.
- A checkbox to autorepeat the "Get". Availability of this checkbox can be dependent on the currently active plugin.
- A button to close the second sidebar. Maybe the button to open the second sidebar can be used to toggle the sidebar instead.

Some plugins (e.g.) might fit in case of certain zoom levels, certain content in the viewport, or a specific selection. Some plugins might fit in case of an empty selection only.

Some ideas of such plugins:
- 3d viewer
- Indoor viewer
- Lane visualizer for multiple consecutive ways.
- Public transport editor
- Relation tree view

In many cases the user should be able to select elements in the second sidebar view and edit them in the inspector.

**Comment by bhousel** [comment]
I'm having a hard time visualizing it.  Can you make a mockup?   

If we add a drawer for plugins I've always thought it would go on the right side, near Background, Map Data, Help.  But I haven't thought about it much.  (The left side inspector is all about OSM stuff and the right side buttons are all about iD stuff.)

**Comment by slhh** [comment]
Here is a mockup:
![second sidebar](https://cloud.githubusercontent.com/assets/13684947/23572345/c06564b4-006e-11e7-9448-ef85e8c05de4.png)
I tried to minimize the required UI controls. Therefore I have combined the "Get" button and the button to open the sidebar into a single leftwards arror in the inspector header.

The original leftwards arrow to go back to the feature type selection level has been replaced by an upwards arrow on the right of the "Edit feature" label.

The example content of the sidebar is taken from the OSM lane visualizer https://github.com/mueschel/OsmLaneVisualizer .

The list of available plugins can be shown by clicking on the Plugin name. Maybe it can have a little dropdown arrow on the right.

The checkbox with the toggleable reload icon is for autorepeating the get operation.

>The left side inspector is all about OSM stuff and the right side buttons are all about iD stuff.

The plugin content would be all about OSM stuff. The controls of the plugin would be more all about iD stuff, but the whole topbar is all about iD stuff anyway.

The main reason for placing  the second sidebar on the left is, that I would expect much user interaction between both sidebars. Therefore positioning it on the left seems to reduce the required mouse movement.

**Comment by bhousel** [comment]
Ok I think I understand.. I'm going to close this for now because until we have a coherent approach to plugins, there is nothing actionable for me.  But when we start talking more concretely about what plugins can do, I'll try to make sure they can be flexible enough to move the sidebar section around. 

There is another issue related, #3447, about making the sidebar more "responive".  It would be nice to be able to resize it, or show/hide/toggle it, etc, rather than just having it stuck as it is.
