### ISSUE TITLE
Feature type autocomplete in Safari refuses to select Minor/Unclassified Road

### ISSUE THREAD

**Issue by mvexel** [openstreetmap/iD#3839]
When trying to change a way to `highway=unclassified` using the feature type autocomplete field, the wrong type is selected on click:

![unclassified-bug](https://cloud.githubusercontent.com/assets/120452/22941050/3ab16d52-f2a1-11e6-8d5e-d7deed5bfda8.gif)

So far I've only been able to reproduce this with the 'Minor/Unclassified Road' type.

**Comment by bhousel** [comment]
Thanks @mvexel, I can reproduce this in Safari also.

**Comment by bhousel** [comment]
Looks like it is this again:  https://github.com/openstreetmap/iD/issues/2376#issuecomment-57925512

See how if you start typing "uncl" in "unclassified", Safari autosuggests to turn that into "uncle", which matches "Cut Line" and "Funicular" presets.

<img height="200" alt="screenshot 2017-02-14 15 32 38" src="https://cloud.githubusercontent.com/assets/38784/22948184/8ce92662-f2cb-11e6-988a-8681441489bd.png"> <img height="200" alt="screenshot 2017-02-14 15 32 45" src="https://cloud.githubusercontent.com/assets/38784/22948193/902b5dfe-f2cb-11e6-8424-632bf4e1bad6.png">

It can happen very fast or not even show the autosuggest prompt sometimes.  I'll try to find a way to turn this behavior off!
