### ISSUE TITLE
Unneeded area=yes generated

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3851]
Its an artefact of the internal separation of areas and linear ways.

Often i convert a node POI to an area. One example would be a school.

I draw an area around the poi and select nothing (building, school) in the sidebar.
After that i (direct or afterwards) select an node poi and click the + for merge.
Now the resulting ways has still `area=yes` plus the `amenity=school` tag.

Perhaps a new created way should get an internal meta data (for example autogenerated_areatag) in addition to the `area=yes` osm tag. After merging the `amenity=school` tag with this way iD could detect that `amenity=school` does not need an `area=yes` and the autogenerated_areatag is set and delete the `area=yes` osm tag.

**Comment by bhousel** [comment]
I agree, we should remove the unnecessary `area=yes` after a merge.
