### ISSUE TITLE
House number inside buildings

### ISSUE THREAD

**Issue by Spanholz** [openstreetmap/iD#3857]
Hey,

in my area a lot of buildings are tagged with their address as part of the building. But I always have to click on the building to see if there is an address added. Like in this example it's Schrödingers houses, some have an adress others not:

![Example 1](http://i.imgur.com/bVIzEQF.jpg)

Is it possible to modify the inside of the shape of buildings to see directly the house number or if there is an adress already added. Maybe an example how it could look like:

![Example 2](http://i.imgur.com/SE2nj21.jpg)

Thanks!

**Comment by bhousel** [comment]
Yes, @edpop is working on this 👍 
This will be a wonderful feature once it's ready..
See discussion on #3840 and #1524
