### ISSUE TITLE
Make sure all blacklist regexs present in API policy are being tested

### ISSUE THREAD

**Issue by mxa** [openstreetmap/iD#3858]
In Korea there is a serious issue because people are using 
http://xdworld.vworld.kr:8080/2d/Satellite/201612/{z}/{x}/{y}.jpeg
as a background and map their copyrighted imagery, making OSM a derived work. VWorld is a governmental source and is already informed about the situation.
We need a warning message or some other idea to prevent this from happening. Presumably it is also related to Pokemon Go, we are trying to find out.

**Comment by revi** [comment]
Maybe see also [talk-ko@lists.osm.org](https://lists.openstreetmap.org/pipermail/talk-ko/2017-February/thread.html)'s Feb archive.

**Comment by bhousel** [comment]
Can you open an issue in the [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website/issues) repository?

They have the ability to blacklist the source in the API level (see http://www.openstreetmap.org/api/capabilities), so if it is added as a `blacklist` property in the API, iD users won't be able to use it.

Thanks!

**Comment by HolgerJeromin** [comment]
This was implemented. Should this issue be closed here?

**Comment by bhousel** [comment]
I'm still able to use that custom background on openstreetmap.org, so we probably need to do something in iD.

**Comment by tyrasd** [comment]
fixed in master (224059b). @bhousel can you publish a bugfix release?

**Comment by bhousel** [comment]
Thanks @tyrasd 🎉

**Comment by bhousel** [comment]
Can confirm that the fix works, I'm making a bugfix release now..
