### ISSUE TITLE
zoom in: limited to level 17 ?

### ISSUE THREAD

**Issue by verdy-p** [openstreetmap/iD#3863]
Cannot zoom in in iD

e.g. open just this one:

https://www.openstreetmap.org/edit?editor=id#map=17/49.57083/6.15879

trying to zoom in to level 18 seems to work and immediately returns to level 17 (independantly of the imagery layer selected). It seems that you limit the zoom level only to the default layer selected (here the Ortho for Luxembourg), even if we change it to another layer such as Bing imagery.

Anyway, even if a background imagery is limited to level 17, I don't see why we could not zoom in to higher levels to see details or edit them more precisely (and then avoid merging things that should not be merged). The background layer should have no influence at all (at worsty, it could just turn to all black if you can rescale it in the browser or if there are issues for transforming bitmap images in browsers, possibly because of memory or missing rendering components to do it)

Please allow us to zoom in at higher levels: it is especially important for fixing details such as unconnected ways, or to avoid merging two conflicting nodes (such as two shops positioned extremely near of each other as they cannot be ditincguished by position only, but need to be both present as separate nodes due to their incompatible tags) !

**Comment by tyrasd** [comment]
confirming (chrome & firefox, iD 2.1.3 on osm.org, but not https://openstreetmap.us/iD/release/). We don't restrict zooming in on any imagery layer. So, this is a bug.

**Comment by tyrasd** [comment]
First guess: It could be some upstream changes (as only the osm.org integrated version is affected), maybe a6fa8cc273017c2673d6d76dae7f5ac811c2027d. //cc @tomhughes

**Comment by tyrasd** [comment]
it works again now. thanks for the quick [fix](https://github.com/openstreetmap/openstreetmap-website/commit/57443546f8395da089ee295cde05750a087fd6dd) @tomhughes!

**Comment by Slawek234** [comment]
Hallo. Zoom in ID not working properly. I can't mapp in ID!

**Comment by tyrasd** [comment]
@Slawek234 can you please try again? For me it works now.

**Comment by Slawek234** [comment]
Thanks! Zoom now works:)

**Comment by verdy-p** [comment]
I confirm this is now fixed ! Thanks for this very fast correction !
