### ISSUE TITLE
Add information about element type/id, and link(s)

### ISSUE THREAD

**Issue by verdy-p** [openstreetmap/iD#3879]
I can't see any place in the iD editor that displays the OSM element's type/id.
This should be made visible, with a link to browse that object on the OSM website, in a new tab of the browser.

I suggest placing this link on the right side of the "All tags". There's ample enough space to fit it.

For there there we could have access to last edits (history), or notes...

Ideally we should also be able to configure our own set of URL templates (saved in our local broser sesssion, if there's no server-side storage for settings of logged in users) for special actions on various online QA tools or to load it in an external editor, such as with JOSM remote control (JOSM allows easier viewing of the history and comparing changes: the basic history on the web OSM site is almost unusable), but may be a few common preconfigured links could be proposed, for things that are still not easily accessible or easy to do from iD.

**Comment by bhousel** [comment]
iD does have a "view on openstreetmap" link at the bottom of the inspector pane:

<img width="220" alt="screenshot 2017-03-06 13 14 07" src="https://cloud.githubusercontent.com/assets/38784/23623207/26d935a2-026f-11e7-8117-e6f28bd4db61.png">

Also you can pull up an infobox with more info about an object, including its OSM id and type, by selecting the object, then press <kbd>⌘I</kbd>  :

<img width="243" alt="screenshot 2017-03-06 13 14 18" src="https://cloud.githubusercontent.com/assets/38784/23623210/28ce4f32-026f-11e7-8ce6-244467bf9a65.png">

**Comment by verdy-p** [comment]
This does not address the issue that the id is not visible at all. And viewing the map is not the same as browsing the object.
the keyboard shortcut is also only for a Mac (and noone knows it as there's no hint about it). What is the real cost of having the id **visible** directly on the properties pane, and copiable from there for use in other tools?
