### ISSUE TITLE
Create watchlists

### ISSUE THREAD

**Issue by andischan** [openstreetmap/iD#3880]
I'm wishing watchlists to watch errors of Pokemon, Mapbox or HOT mappers.
That errors like 
![p](https://cloud.githubusercontent.com/assets/24589670/23624388/cd85385c-02a5-11e7-8511-2f3d3a4cbac0.png)
don't happen again.

**Comment by bhousel** [comment]
Thanks @andischan, I agree that watchlists for OpenStreetMap is a great idea, and there are several other projects dedicated to monitoring new users activity, but it is not in the scope of the iD editor.

Check out https://wiki.openstreetmap.org/wiki/Detect_Vandalism for a partial list of existing projects.

**Comment by andischan** [comment]
![osm-river-chaos](https://cloud.githubusercontent.com/assets/24589670/23792463/54e759e0-0587-11e7-95ab-7d2fdfe3bc64.png)
