### ISSUE TITLE
Add reference link for 'Enter a tile URL template. Valid tokens are {zoom}, {x}, {y} for Z/X/Y scheme and {u} for quadtile scheme.'

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#3887]
User sees ```Enter a tile URL template. Valid tokens are {zoom}, {x}, {y} for Z/X/Y scheme and {u} for quadtile scheme.```
User searches Google for the definition of what you want.
User doesn't find it.
Please add a link to that message saying exactly what you want in detail.

**Comment by jidanni** [comment]
Need a link to a list of examples, like http://wmts.nlsc.gov.tw/wmts/PHOTO2/default/EPSG:3857/{z}/{y}/{x}

**Comment by bhousel** [comment]
Can you suggest a good page to link to?
I found https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames  but I don't think it's very good.

**Comment by Abbe98** [comment]
It would be nice if the iD help pages could contain this information, but they are as far as I know not linkable.

**Comment by bhousel** [comment]
I couldn't find a good resource to link to, so I just added an example url to the prompt.

<img width="400" alt="screenshot 2017-06-20 00 37 18" src="https://user-images.githubusercontent.com/38784/27316893-f01b6668-5550-11e7-9f7b-e2a3be1bf422.png">

**Comment by jidanni** [comment]
OK but I think you need to explain there also what "switch" does.

**Comment by pnorman** [comment]
Let's use tile.openstreetmap.org fot the example. It shows the format, isn't tied to any company, and doesn't contain provider-specific patterns which people might think are generally required (e.g. `username.id` in the URL)

**Comment by bhousel** [comment]
> Let's use tile.openstreetmap.org fot the example. It shows the format, isn't tied to any company, and doesn't contain provider-specific patterns which people might think are generally required (e.g. username.id in the URL)

Yes, this is a good idea..

I think most people seeing this message are just there to paste the tile url, so we should keep it simple.

**Comment by jidanni** [comment]
Still do be sure to list and explain all "macros" available., e.g., "switch".

**Comment by bhousel** [comment]
@jidanni I'll see if I can add some more info without making the message too long.  I found that we unfortunately can't add a link in a `window.prompt()`.

BTW we do also document the custom URL parameters here: https://github.com/openstreetmap/iD/blob/master/API.md#id-standalone

**Comment by jidanni** [comment]
Maybe say
See also
https://github.com/openstreetmap/iD/blob/master/API.md#id-standalone
or
github.com/openstreetmap/iD/blob/master/API.md#id-standalone
which even if not hyperlinked, the user can (hopefully?!) copy with the
mouse and then browse in another window.

**Comment by bhousel** [comment]
> which even if not hyperlinked, the user can (hopefully?!) copy with the
> mouse and then browse in another window.

Unfortunately I'm not able to copy the dialog text in Chrome.
Instead I just added some more words describing the other replacement tokens:

<img width="450" alt="screenshot 2017-06-22 21 42 28" src="https://user-images.githubusercontent.com/38784/27463151-c4079732-5793-11e7-9246-9b0df923abfb.png">

I think it's ok for all of the supported tokens should be mentioned here, just so that nobody gets confused if they are given a url with a `{switch:a,b,c}` in it and they don't see it in the list.

**Comment by jidanni** [comment]
Looks great except the user will certainly be begging for more info.
How about the [Cancel] and [OK] buttons... could there be a third on
added, [Learn more] which could open the URL to learn more?
