### ISSUE TITLE
Allow more than one custom layer

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#3888]
Regarding the box titled ```Enter a tile URL template. Valid tokens are {zoom}, {x}, {y} for Z/X/Y scheme and {u} for quadtile scheme.```
Well the user might want to switch back and forth between two custom layers, due to varying cloud coverage.
But currently he must enter the URL all over again each time he switches.

**Comment by Abbe98** [comment]
Save all of the past ones in localstorage and display a dropdown in the dialog?

A new dialog window would be needed, is there any existing element that could be reused?

**Comment by bhousel** [comment]
Yes, agree.. this is covered in #2095
