### ISSUE TITLE
Some Taiwan custom maps do not work

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#3889]
For Custom maps,
http://wmts.nlsc.gov.tw/wmts/PHOTO2/default/EPSG:3857/{z}/{y}/{x}
works but
http://landmaps.nlsc.gov.tw/S_Maps/wmts/DMAPS/default/GoogleMapsCompatible/{z}/{y}/{x}
doesn't. It just gets white tiles.

**Comment by bhousel** [comment]
I checked and I see this too.. I don't know why, it seems to be an issue with the tileserver itself, not anything that iD is doing.
