### ISSUE TITLE
No OSM map in edit mode

### ISSUE THREAD

**Issue by POTTERIES** [openstreetmap/iD#3897]
Have been  editing OSM , mainly adding more detail from Bing base and Local knowledge for a few years.
However trying now and when I enter edit mode , I have no current OSM map to view ...just the Bing satellite image. One exception is where I  found a recent update locally , by another user. This showed up as apparently just the update detail.    I was able to update one of these ( I rounded off a small pond ) which I was able to upload. 
To compound my problem I was logged into a new account .I had an error message on the old account   "Sorry could not log in with those details." and password reset did no recognise my email.
I work in and previously worked in Chrome. Problem on 2 devices.

**Comment by bhousel** [comment]
Can you share a screenshot of the message?

**Comment by POTTERIES** [comment]
Hi

This email address is the one for my original account. The  other sening address
is my altrnative email , used for new accountsecond address

Screenshot of error message attempting to  open account attached.

The attached screenshots of editing  screens is in the new account that I
created.

1. Drawing a test path on the Bing base map with no OSM map shown  

2. An area where I think there have been recent updates...which  is the only OSM
detail to show.....I was able to edit the pond

Thanks for you assistance.

John Heaton

**Comment by bhousel** [comment]
Sorry @POTTERIES, I didn't receive the screenshot.  The best way to share your screenshot is probably to log into GitHub and drag the image onto a new comment on this thread.

**Comment by POTTERIES** [comment]
Screenshots  mentioned above .
![ashampoo_snap_2017 03 14_17h40m03s_006_](https://cloud.githubusercontent.com/assets/20781824/23925020/3bcbc0d2-0905-11e7-81eb-fd5fc90fc741.png)
![ashampoo_snap_2017 03 14_17h37m56s_005_](https://cloud.githubusercontent.com/assets/20781824/23925033/4598f8b4-0905-11e7-9518-8b1e86bd68bf.png)
![ashampoo_snap_2017 03 14_17h30m03s_004_](https://cloud.githubusercontent.com/assets/20781824/23925039/4dd22c80-0905-11e7-8d7d-1c723a696c00.png)

**Comment by bhousel** [comment]
Hmm, it definitely looks like you're having an issue with your account.  What happens if you log out and back in again using the openstreetmap account menu?:

<img width="255" alt="screenshot 2017-03-14 19 32 07" src="https://cloud.githubusercontent.com/assets/38784/23926861/09461ba2-08ed-11e7-8768-a6d1cb097251.png">

**Comment by POTTERIES** [comment]
Problem sorted. 
I have not used OSM for  a while and have been opening with a Google search and the following was top of my list.
hhps://master.apis.dev.openstreetmap.org/login?cookie_test=true&referer=%Fedit%Feditor%3Did#map=18/53.01239/-2.14307
Could not see simpler links, so I found one on the WIKIpedia page...
Created an Icon link on desktop to simplify in the future.
Thankyou
[Untitled 1.pdf](https://github.com/openstreetmap/iD/files/845372/Untitled.1.pdf)

**Comment by bhousel** [comment]
Glad you got it working 👍
