### ISSUE TITLE
Do not warn if path is connected to entrance

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3906]
I got a warning for a path connecting two entrances when selecting upload:
![image](https://cloud.githubusercontent.com/assets/5360273/24035924/c9934b6c-0af7-11e7-9fd2-3c94942f00d9.png)
Could you remove theses warnings?

**Comment by bhousel** [comment]
Good catch.  This is why validation is so tricky, and why I don't want to add very much of it to iD.
