### ISSUE TITLE
Master and Release mirrors have changed

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3912]
The master deployment links in Contributing.md result in "404 not found". It doesn't seem to be a short term server isuue, as the issue does already persist for at least one week.

**Comment by bhousel** [comment]
Yes, I need to find a better place for it (or at least a better name for it), but for now you can use:
http://id.openstreetmap.us.s3-website-us-east-1.amazonaws.com/master/

**Comment by iandees** [comment]
My suggestion is that we add CNAMEs to the `ideditor.com` DNS that points to the S3 website above. Something like `releases.ideditor.com` or `preview.ideditor.com`. That way the implementation of who or how the previews are run can be adjusted without adjusting the docs or other external links.

**Comment by iandees** [comment]
I just added it by forcing a release run. There hadn't been one since February, so it hadn't run since I made this change to S3.

**Comment by iandees** [comment]
@bhousel who has access to ideditor.com DNS? I'm happy to make those CNAMEs and get that running.

**Comment by bhousel** [comment]
Mapbox owns the domain, so in theory I can log in to our registrar and do this..

**Comment by bhousel** [comment]
Cool thanks @iandees for helping with this!  🎉 

The new links are:
http://preview.ideditor.com/master
http://preview.ideditor.com/release

I'll update the README..

**Comment by tyrasd** [comment]
maybe there should be some redirects in place on the old URLs which currently 404 (e.g. http://www.openstreetmap.us/iD/release/)?
