### ISSUE TITLE
Switch to `contact:`

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#3915]
Hello,

I think that, according to [this wiki](http://wiki.openstreetmap.org/wiki/Key:contact) iD should now use `contact:` as prefix for contact object.
At least this three item need to be switched :

- `phone`=> `contact:phone`
- `fax`=> `contact:fax`
- `website`=> `contact:website`

**Comment by bhousel** [comment]
That wiki says that the old tags are more popular, and the talk page suggests that a lot of people just regard `contact:` namespace as a failed experiment.  

I don't see us switching over unless there is a concerted effort to replace the old tags with the new ones, which doesn't seem likely.

It would actually make me really happy if OSM had a real process for replacing old tags with better ones.  Like: change is announced well in advance, database taken down during maintenance window, SQL is run, database comes back up with new tags and new version of iD.  That would be better I think.

**Comment by homersimpsons** [comment]
@bhousel thank you for your answer. In fact a General OSM Update would have been quite better to switch tags.
Just have to wait for a vote.

**Comment by bhousel** [comment]
> Just have to wait for a vote.

It has far more to do with people willing to do the work than collecting votes.

**Comment by bhousel** [comment]
Closing for now.  Switching from the more common address tags to the less common ones is just something we really can't do right now.

**Comment by carstenhag** [comment]
May it be time to re-assess this?

**Comment by quincylvania** [comment]
@carstenhag While `contact:` usage has increased somewhat, a tag like `phone` still has over a million more uses than `contact:phone`. iD isn't suited to changes of this magnitude. I agree with @bhousel's original assessment:

> I don't see us switching over unless there is a concerted effort to replace the old tags with the new ones, which doesn't seem likely.
>
> It would actually make me really happy if OSM had a real process for replacing old tags with better ones. Like: change is announced well in advance, database taken down during maintenance window, SQL is run, database comes back up with new tags and new version of iD. That would be better I think.

**Comment by jonsger** [comment]
I wonder if it makes sense to support `contact:` tags but not switch to them. In recent times I sometimes added `phone` and `website` tags not seeing that the object already had the `contact:` equivalent.

So it would be nice if ID could show `contact:` tags in the edit box. This would reduce duplication and wasted efforts...

**Comment by carstenhag** [comment]
Something like that would be great. I would prefer new phone numbers etc via ID to be made with the contact prefix, but if that's not currently how you want to do it, at least properly handle `contact:` prefixes when the data is there.

**Comment by bhousel** [comment]
> if that's not currently how you want to do it, at least properly handle contact: prefixes when the data is there.

IMO, the way to “properly handle `contact:` prefixes” is to remove them.

**Comment by carstenhag** [comment]
Why? It's the recommended way to tag. Of course it won't get used by more people, when the main editor refuses to support it.

**Comment by bhousel** [comment]
> Why? It's the recommended way to tag. Of course it won't get used by more people, when the main editor refuses to support it.

It is _not_ the recommended way to tag.  The `contact:phone` wiki page says today right now the literal words "To limit tag fragmentation, consider using the most used keys."

If it was seen as a failed experiment in 2017, why are we still discussing this in 2020?  What process led the OSM project to invent 2 competing tags for storing phone numbers?  

We on the iD team didn't want this, but now half the community seems annoyed at us for not supporting their favorite phone tag.  OSM could just pick one and change them all, but nah, instead let's gripe about how the "main editor refuses to support" your favorite phone tag.  

Sometime soon, we will be spinning the presets off into a separate project and the "OSM community" can take ownership of them.  Then you can fight about the phone tags elsewhere.
