### ISSUE TITLE
Human friendly interface for duration=* tag

### ISSUE THREAD

**Issue by DFyson** [openstreetmap/iD#3922]
It would be nice if ID parsed the [duration=*](https://wiki.openstreetmap.org/wiki/Key:duration) tag and made a more human readable interface for it, converting to and from the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations) standard (for example). Currently it's just a text field where people add whatever they want. The motivation behind this is better standardization for the OSM database especially since ID is used by occasional mappers. It would be a similar idea as is being discussed in #974 for opening_hours=*. I could imagine it being as simple as text boxes for each years, months, (weeks), days, hours, minutes and seconds for the user to fill out.

**Comment by bhousel** [comment]
It's ok to track this on an issue, but we don't currently support the `duration=*` tag on any presets, so the field wouldn't show up anywhere as of today.

iD does support these similar tags:
  * [`aerialway:duration`](https://wiki.openstreetmap.org/wiki/Key:aerialway#Aerialway_attributes) on several aerialway presets, which seems to prefer minutes, not ISO 8610.
  * [`maxstay=*`](https://wiki.openstreetmap.org/wiki/Key:maxstay) on `amenity=parking` which seems to prefer human readable values like HH:MM with units, not ISO 8601.

**Comment by Bibi56** [comment]
But the reason why non ISO 8601 is preferred is probably the lack of UI. Using proper UI (for reading or editing) you don't need a human readable duration stored in the database but a duration. Easier for computation (standard, ready to use parsers and UI).

**Comment by bhousel** [comment]
Closing this for now.. I might reopen if we ever add a duration field to iD that actually uses ISO 8601.  (Maybe ferries or alternating oneways work like this?  I don't know.)

**Comment by 1ec5** [comment]
Yes, ferry route durations are expressed in ISO 8601 ([example](http://www.openstreetmap.org/way/141294301)).

**Comment by pyrog** [comment]
Long hiking trails have usually durations in days 😉
