### ISSUE TITLE
Prevent generating multiple nodes by disconnect operation

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3926]
With a vertex selected, disconnect should not generate more than a single additional node. Otherwise the operation should be disabled.

Rationale:
The operation which is desired by the user is likely disconnecting a single way. When dragging the first node away after disconnecting has generated multiple nodes, there is some change that the dragged node is the intended one. In this case the user might not recognize that there are still multiple coincident unconected nodes left. This can easily break routing applications etc..

In many cases where disconnect would needs to be disabled, it can be made more specific by #3635 instead.

Btw, splitting at a vertex, where multiple ways are split, is a similar issue, but with somewhat less impact on data integrity.

**Comment by bhousel** [comment]
I like [your suggestion](https://github.com/openstreetmap/iD/issues/2206#issuecomment-275887808) on #2206.  The Disconnect operation can move the newly created points away from the original vertex by a few pixels to make it obvious that the ways are now disconnected.  Wouldn't that be better than just preventing the operation where multiple ways meet?

**Comment by slhh** [comment]
A special case of this issue is the Disconnect operation with a virtex and multiple ways selected. In this case we should generate a single new node which is common for all selected ways. This does also relax the requirement to disable the operation due to relation protection.

**Comment by bhousel** [comment]
> A special case of this issue is the Disconnect operation with a virtex and multiple ways selected. In this case we should generate a single new node which is common for all selected ways.

I think they way it works now is fine.  The user can select all the ways that they want disconnected.  In this example below, I wouldn't expect A and C to stay connected.  And if the user really wants them connected, they can just reconnect them.

![split](https://cloud.githubusercontent.com/assets/38784/24456406/ec2b097c-1460-11e7-8a0d-d43c025808a7.gif)

**Comment by slhh** [comment]
@bhousel 
> I think the way it works now is fine. The user can select all the ways that they want disconnected. In this example below, I wouldn't expect A and C to stay connected. And if the user really wants them connected, they can just reconnect them.

The main issue is that the user might not be able to split here because there is a relation on A+C. This is a frequent case in some regions, but maybe it is rare in your region due to sparsely mapped landuses, bus routes, etc..

Selecting B+D instead would be a workaround, but it needs some expert-knowledge and and induces some risk of leaving B+D unconnected. 

This workaround is impossible if there is another relation on B+D (D need to end at the connecting node).

At least in cases which would require the operation to be disabled otherwise, we should better generate the result where A and C stay connected. 

I would prefer to make the operation more uniform by always leaving A and C connected. The new node would be selected after performing the operation. And if the user really wants to have A and C separated, the disconnect shortcut key can just be pressed a second time.
In addition I would expect users to disconnect step by step using the more normal disconnect with a single way+vertex selection, in case fully separated ways are required. 


Btw., your video shows a rendering issue: After dragging the first unconnected node away, the node at the original position is rendered as a connected node, but there is still a coincident, unconnected node, which should get priority in view of rendering and selecting.
