### ISSUE TITLE
Visualise / show multiple points in the same location [Feature Request / Suggestion]

### ISSUE THREAD

**Issue by sweco-semtne** [openstreetmap/iD#3927]
Hi,
I've got at question / feature request on how to visualise multiple points with the same coordinate? 

We have several address points in the exact same location (with a different z-level) and it would be nice to be able to see that there are multiple points on the same location. 
And to be able to see that in the map. 

![points](https://cloud.githubusercontent.com/assets/2619813/24295998/88c1d710-109d-11e7-8879-0c3d40f3f081.gif)

**Comment by bhousel** [comment]
Thanks for the report - this isn't something that iD supports yet.
I agree it would be a useful feature, #2746 is the issue where we are tracking it.
