### ISSUE TITLE
Split area should be easy possible

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3934]
I often have the situation where a pitch is describing multiple fields. For example two adjoining tennis pitches.
With [JOSM with UtilsPlugin](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/utilsplugin2#Split_area_.28Alt.2BX.29) i would split the area at the right point and have two identically tagged areas. Problem solved.
The same is often needed when refining a large building for placing proper house numbers on different parts.

But with iD the only function i know breaks the area into two ways and constructs a MultiPolygon.

**Comment by bhousel** [comment]
Just realized this is a duplicate of #969
