### ISSUE TITLE
Add Conditional restrictions tagging to Restriction presets

### ISSUE THREAD

**Issue by Andygol** [openstreetmap/iD#3935]
In order to avoid using deprecated tags `day_on=*, day_off=*, date_on=*, date_off=*, hour_on=*, hour_off=*` it would be great to adopt in iD [Conditional restrictions](https://wiki.openstreetmap.org/wiki/Conditional_restrictions) schema.

```
maxspeed:conditional=60 @ (06:00-20:00)
```
or

~hour_off=19:00"~
~hour_on" v="15:00~
restriction:**conditional**=no_left_turn **@ (15:00-19:00)**
type=restriction

See also https://www.mapbox.com/mapping/mapping-for-navigation/adding-turn-restrictions/#adding-conditional-turn-restrictions

`restriction:conditional=no_left_turn @ (Mo-Sa 07:00-09:00,16:00-18:00)`

![](https://cloud.githubusercontent.com/assets/4470913/14850426/9d4643f8-0c96-11e6-8c0c-dc94887e1613.png)

/cc @bhousel

**Comment by bhousel** [comment]
Closing as duplicate, I just realized we already have #2906 for this, which is more about conditional turn restrictions but really could apply to any tag.
