### ISSUE TITLE
How to remove wrong data in Transifex?

### ISSUE THREAD

**Issue by riajuu** [openstreetmap/iD#3938]
![jimul](https://cloud.githubusercontent.com/assets/26794295/24505876/8c09806e-1596-11e7-9303-42f313c3e9ca.png)

I want to remove data ‘바다횟집 (Bada Fish Restaurant) - 음식점’ in OSM, because that data is ad as the PR. So I searched everywhere for a few days, but I can't find it.

Thanks.

* 바다 (Bada) = Sea / 횟집 (hoetjip) =Seafood restaurant / 음식점 (Eumsikjeom) = Restaurant

**Comment by bhousel** [comment]
iD pulls these suggested names automatically from the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) project.  Can you open the issue in that repository?  Thanks!

The way to get the name removed is to add it to the `discardedNames` list [here](https://github.com/osmlab/name-suggestion-index/blob/master/filter.json#L168), then someone will need to rebuild the name list, and iD will pickup the latest list next time I make an iD release.
