### ISSUE TITLE
Flip preset icons when RTL?

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3940]
Should we reverse the preset icons when the user is in RTL mode?

I never thought about this until today, but many of our icons have an implicit LTR-ness to them that looks a little weird when the interface is RTL (like the person is walking backwards).

Maybe other graphics too?  Maybe _all_ the graphics (geolocate icon, mode buttons, etc)?

@mapmeld @tmcw @samanpwbb any opinions?

<img width="392" alt="screenshot 2017-03-31 09 56 33" src="https://cloud.githubusercontent.com/assets/38784/24553557/90e3206a-15f8-11e7-9092-d23369f1b951.png">

<img width="391" alt="screenshot 2017-03-31 09 56 43" src="https://cloud.githubusercontent.com/assets/38784/24553565/96163b44-15f8-11e7-9780-529c21d07c38.png">

**Comment by mapmeld** [comment]
I'm not really sure - it might be worth sending this over to the OSM Tunisia email list which helped us out with the previous issue.

**Comment by pnorman** [comment]
Some icons shouldn't be flipped

![image](https://cloud.githubusercontent.com/assets/1190866/24638553/27d124c0-189e-11e7-9b64-695a44609ae2.png)

**Comment by bhousel** [comment]
Good point @pnorman 
I'll close this for now, but we can open separate issues for any icons that the OSM community wants changed, if needed. Thanks!
