### ISSUE TITLE
Don't autofill changeset comment from previous edit, if previous edit was older than some time limit

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3947]
I've seen some new users who keep using the same changeset comment as their first edit. Not a huge problem but a bit annoying, and sometimes new users from Missing Maps/HOT projects edit in their "home" area yet upload with the same comment full of hashtags.

Is this the intended behaviour in iD, to have the previous comment sitting in the box when saving? Tested it myself and the same thing happens when I save, in both Firefox and Chrome.

**Comment by bhousel** [comment]
Yes that's intended.  I don't personally have a preference, but some people like that behavior, especially people who make a lot of very similar edits and want to just change a few words in the comment, or people who save frequently.

**Comment by althio** [comment]
@bhousel 
> some people like that behavior, especially people who make a lot of very similar edits and want to just change a few words in the comment, or people who save frequently.

That is understandable, but what about a time limit? The changeset comment could get an expiry time so that a new mapping session comes with an empty field.

**Comment by boothym** [comment]
>but some people like that behavior, especially people who make a lot of very similar edits and want to just change a few words in the comment, or people who save frequently.

Can't there be a middle ground though, between allowing that behaviour and encouraging newbies to add a proper changeset comment on each upload? With autocomplete in the comment box, along with copy & paste, it shouldn't affect those people you are talking about too badly.

**Comment by bhousel** [comment]
I agree having the automatic comment expire after some time is a good idea...
