### ISSUE TITLE
Use window.top.location instead of window.location when embedded in iframe?

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3950]
see https://github.com/openstreetmap/openstreetmap-website/issues/1518

The issue here is that on openstreetmap.org, iD is running in an iframe.  We detect the host using [this line of code](https://github.com/openstreetmap/iD/blob/eb62e22a375aa0fa689befa9b1c3560dcbf1e8bf/modules/util/detect.js#L102).

`window.location.origin + window.location.pathname`
writes "https://www.openstreetmap.org/id" into the changeset `host` tag.

When embedded, we could do:
`window.top.location.origin + window.top.location.pathname`
to get "http://www.openstreetmap.org/edit" in the changeset `host` tag.

**Comment by HolgerJeromin** [comment]
Perhaps id should check if all needed libraries are loaded and abort gracefully with a message in the body. This could contain a link to the osm main page.

**Comment by HolgerJeromin** [comment]
You said 
> You're right that window.location when embedded in an iframe is not the true location.

But in a way that is the true location. /edit can give multiple editors depending on the user preference. 
Perhaps under this URL there could be id version 5 under a iframe /iD and a version 10 under /id10
Putting /edit in the tag would not differ both. But the version tag would... 

But still we had the problem with old URLs in the DB right now

**Comment by bhousel** [comment]
#2449 describes more why we have a `host` tag.  It's mostly so we can see which site is using iD so that we can track down mapping and translation issues caused by people running old versions.

In practice, people are not running multiple versions of iD in multiple iframes, and I think for usability purposes it is better to record a URL that people can actually visit.

**Comment by HolgerJeromin** [comment]
For the current stored (many) urls IMHO we should have a solution. So i am not really sure if changing the url in the future is really needed

**Comment by bhousel** [comment]
> For the current stored (many) urls IMHO we should have a solution. So i am not really sure if changing the url in the future is really needed

Just because there is existing stored changeset tags that point to the invalid url doesn't mean we can't fix the problem.  If anybody really cares, somebody could run a SQL update to change all the old values.
