### ISSUE TITLE
Do not offer RUR as a currency type

### ISSUE THREAD

**Issue by dmromanov** [openstreetmap/iD#3953]
Code 'RUR' for Russian Rouble is not used since 1998. Offering it as a hint in 'currency types' input fields leads to mistakes. Please remove it.

https://en.wikipedia.org/wiki/Russian_ruble

![rur](https://cloud.githubusercontent.com/assets/299059/24867651/88cb161e-1e16-11e7-81e1-b244888ce354.png)

**Comment by bhousel** [comment]
Thanks for the report @dmromanov.  iD pulls these values from taginfo based on values actually used in OpenStreetMap.  see: https://taginfo.openstreetmap.org/keys/currency#values

It looks like there are 22 instances of `RUR` in OpenStreetMap, so it should be pretty easy to replace all these uses with the correct type.  After that's done and taginfo refreshes their database (which happens daily), it will not show up as a suggested type anymore.
