### ISSUE TITLE
gender designation for amenity=toilets

### ISSUE THREAD

**Issue by micahcochran** [openstreetmap/iD#3954]
The gender field for gender designated restrooms is currently implemented as a "combo" field, which was a result of issue #2422. (I pretty much agree with @thekyriarchy original post that it takes a tagging expert to properly map public toilets correctly.)

Only being able to tag one gender, doesn't always mesh with reality.  Sometime, you'd place a node that would mean that male and female restrooms are here.

However, I think the "gender" should really should be implemented by 3 separate check marks for male, female, and unisex.  All of those values should be able to selected as "yes" (defaultCheck).  The interface look is great, the problem is the functionality.  Is there a "multi-check" box that would group 3 separate defaultCheck fields like the combo does?

**iD's UI for amenity=toilets**
![image](https://cloud.githubusercontent.com/assets/7433104/24872780/29e8094a-1de4-11e7-850c-97d3e5930988.png)

**JOSM's box for amenity=toilets**  (I prefer the way it implements "gender")
![image](https://cloud.githubusercontent.com/assets/7433104/24872555/6a86f48a-1de3-11e7-8e04-1ab8b05d085b.png)

Note: I use "gender" in scare quotes because unisex in and of itself is not a gender, but it is a gender/group designation applicable to restrooms.

**Comment by bhousel** [comment]
> Is there a "multi-check" box that would group 3 separate defaultCheck fields like the combo does?

iD does have a multicombo field that would let users pick multiple values.  If the gender fields were namespaced like `gender:male=yes/no`, `gender:female=yes/no`, I could support it pretty easily.

But since the tagging for gender does not work that way, it's not an easy change.

**Comment by micahcochran** [comment]
After I opened the issue,  I saw `amenity=recycling` has a multiCombo with the `recycling:` namespace.

I'm working on a [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Toilet_Tagging_Improvements) for public toilets, and I've not considered adding that type of namespace.  There is a chance that there may be other types of restroom designations that come up for handicap-only or family restrooms, but I had envisioned them being tagged as `toilets:disabledonly` or `toilets:family`.  

Thank you for the quick feedback.

**Comment by bhousel** [comment]
> After I opened the issue, I saw amenity=recycling has a multiCombo with the recycling: namespace.

Yes, you got it!   
[Here is the list](https://github.com/openstreetmap/iD/search?l=JSON&q=multiCombo&type=&utf8=%E2%9C%93) of other fields in iD that work this way.  

For tags like this, namespaced keys help me out a lot because then I don't need to maintain a list of "correct" values - iD will just fetch them from the taginfo service based currently accepted tagging.

**Comment by bhousel** [comment]
I guess I should mention, the other common way of tagging multiple values in OpenStreetMap is semicolon-delimited strings (`gender=male;female`) and iD supports that now too.

**Comment by micahcochran** [comment]
> `gender=male;female`

If I'm going to propose a `gender` tag or a `gender:` namespace, I better have a really good reason to propose it.  I've thought this type of approach, but I had dismissed it earlier for being too different from current tagging schemes.  However, a semi-colon separated tag for genders designations for restrooms could give flexibility to more easily add new designations for restrooms, for better or worse.  There could very well be some restrooms within a place that has all designation, so `gender=male;female;unisex;family;disabled_only`.  I will take another look at this.

Thanks for all the good ideas and for the help!

**Comment by bhousel** [comment]
@micahcochran Happy to help, and good luck with the proposal..

To summarize:
* Best choice:  `toilets:male=yes/no + toilets:female=yes/no + toilets:?=yes/no`
* Ok choice: `toilets=male;female;?`
* Can't support easily:  `male=yes/no + female=yes/no + ?=yes/no`

(or substitute `gender` for `toilets`)

**Comment by thekyriarchy** [comment]
There are many considerations here as well. 

- First, who the facilities are open to: men/women/unisex. 
- Second, whether the facilities are shared for multiple users or family/single-use. 
- Third, the type(s) of toilet(s) within the facilities: standing (urinals), sitting (western), squatting (non-western). 
- Fourth, of the sitting toilets, some may be accessible and some may not based on ADA definitions of required entry space, etc. At least in the United States, "disabledonly" is not a category, since "disabled" is no longer used to describe facilities and since accessible bathrooms are not restricted from non-disabled users.
- Lastly, though arguably least importantly, there may be certain things like baby changing tables, sanitary product dispensers, safer sex barrier dispensers, etc. within the facilities as well. 

At my university, the restrooms are not labelled by gender, but by the number of users and types of toilets within. There are signs that say private or single-user restroom, signs for restroom with urinals, and signs for restrooms without urinals. There are many different methods for labeling bathrooms around the world, so it's important to consider the functional needs of bathroom users.

**Comment by micahcochran** [comment]
@thekyriarchy 
Thanks for the comments.  Those concerns are important.  Please note that the iD editor is really just the interface that makes editing OpenStreetMap easier.  All of those types facilities and equipment are driven by tags.  If a new tag needed, those can be created by a proposal.  If approved, the proposal updates the OSM wiki, which is the place where the tagging documentation is stored.  Some tagging documentation should exist before the iD editor should add them.

OSM use British English for tags.  I don't think that disabled has fallen out of favor in British English.  (Yes, disabled sounds strange to me, too.)   I, too, share many of your concerns.  [I have a proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Toilet_Tagging_Improvements) that is trying to cover most of your first and second considerations.  The third one is already specified.  The fourth is already covered by adding the tag `wheelchair=yes` or `toilets:wheelchair=yes` to the public restroom.  Some of your last items tags are emerging.

Just hearing about your university, it sounds like all the restrooms are varying types of unisex single-occupancy and multi-occupancy restrooms.

**Comment by micahcochran** [comment]
@bhousel 
> * Best choice: `toilets:male=yes/no + toilets:female=yes/no + toilets:?=yes/no`

I anticipate that the `toilets:` namespace to accommodate many more tags in the future than just male/female/unisex (and other restroom designations).  Using the `toilets:` namespace would make the tagging of `amenity=toilets` and toilets within places (restaurants/pubs/supermarkets/so on) more similar.  Maybe I dunno `toilets:fee` tag needs to be added for a subway's restroom.

So based on that would the best choice be something like `toilets:gender:male=yes/no`,  `toilets:gender:female=yes/no`, or `toilets:gender:unisex=yes/no`?  So that `toilets:gender:` only contains the keys that restrooms  are for a designated group, such as a gender.  Am I missing something?

**Comment by bhousel** [comment]
> So that toilets:gender: only contains the keys that restrooms are for a designated group, such as a gender. Am I missing something?

Sounds ok to me..

**Comment by andischan** [comment]
I think it's only necessary to tag unisex, because normal toilets (99,9 %) are for both women and men.

**Comment by micahcochran** [comment]
My current thought is using `toilets:for:` is for male/female/unisex restrooms within places.  This could allow for expanding to other groups in the future, but I've run out of steam on the matter of creating tags for family restrooms and restrooms designated for other groups.

> I think it's only necessary to tag unisex, because normal toilets (99,9 %) are for both women and men.
That is an assumption based on is the norm in your part of the world (and mine). 

There are also instances of having male, female, and unisex restrooms in a building.

[In some countries, that assumption might be wrong.](https://lists.openstreetmap.org/pipermail/tagging/2017-March/031578.html)

**Comment by micahcochran** [comment]
I don't see the tagging of `amenity=toilets` changing in regard to `male`/`female`/`unisex` tags in the near future.  At this point, it would take a very persuasive proposal to change this tagging method.  I don't intend to pursue such a proposal, soon. Therefore, I'm going to close this issue.

**Comment by rory** [comment]
For the record, I've brought this up again on the [osm talk mailing list](https://lists.openstreetmap.org/pipermail/talk/2018-April/080559.html), as part of the [Diversity 2018Q2 quarterly project](https://wiki.openstreetmap.org/wiki/Diversity_Quarterly_Project/2018_Q2). I'm just working on unisex/gendered/gender neutral toilets.

Although 99.9% of toilets in EU/NA might be accessible to women & men, a gender neutral toilet is different from a gender segregated toilet. Many smaller public toilets (like the images on the [`amenity=toilets` wiki page](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets) are single occupancy, gender neutral toilets, and larger public toilets are gender segregated. So there are probably more gender segregated/gender neutral toilets than you think.
