### ISSUE TITLE
Automatic-Scroll Margin Is Too Large

### ISSUE THREAD

**Issue by techlady** [openstreetmap/iD#3956]
It's a good addition that the screen in iD scrolls automatically when one gets close to the edge. However, I feel the scroll margin is too large. When I get to about an inch from the edge it starts scrolling. That means that I have to avoid a large area of the screen when I'm editing to avoid scrolling that I don't want. The margin around the edge of the screen when scrolling starts should be much smaller, about 1/4 inch I feel.

**Comment by bhousel** [comment]
I agree, thanks for the suggestion 👍
