### ISSUE TITLE
It Takes 3-4 Clicks To Select a Feature

### ISSUE THREAD

**Issue by techlady** [openstreetmap/iD#3957]
With the new interface in iD it has become much more difficult to select certain features, especially points. In the past, when I wanted to select a point on a way in order to move it, all I had to do was click once on it and hold. Now, I have to click three or four times to select the point. This is not just annoying. It also makes editing much slower. 
I also have noticed a similar issue when I cut a way in order to delete part of it. In the past, after I cut the way, I just had to click on the part that I wanted to delete, and it would be selected. Now, after I cut the way, I have to click elsewhere to deselect the whole way, then I click on the part that I want to delete to select it. Again, this adds more time to editing.
In general, I would like to see the sensitivity of the selection process go back to what it was before the recent spate of changes to iD.

**Comment by bhousel** [comment]
Yes, this is being tracked on #3824.. It's a priority issue that I'd like to solve soon.

**Comment by techlady** [comment]
Brian, Thanks for the reply. I wish I could help, but I don't code. Good luck!
