### ISSUE TITLE
Make "untagged area" and other validation warnings more prominent

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#3959]
Hi! I’ve noticed at mapathons that people either don’t notice or ignore the yellow “untagged area” warning when they click save and upload on untagged things, resulting in a lot of buildings tagged as area=yes. Could we make it more prominent somehow? Thanks!

**Comment by aawiseman** [comment]
Also here's a thread about it on the HOT list https://lists.openstreetmap.org/pipermail/hot/2017-April/013288.html

**Comment by bgirardot** [comment]
I think a modal dialog would be good if someone still wants to upload data that has no tags but area=yes.

"Hey, those warnings on the left are almost always an ERROR, are you sure you want to upload them? Please ask somewhat what they mean before proceeding!"

**Comment by bhousel** [comment]
The next version of iD will have a significantly improved walkthrough that will teach people how to draw buildings, including how to tag them properly and square the corners.  See #3921 for more details.  I'm looking to wrap this up in the next day or so.

**Comment by aawiseman** [comment]
Awesome, thanks!

**Comment by PolyglotOpenstreetmap** [comment]
"area"="yes" all by itself on a closedway makes no sense at all. never has, never will. People should not be allowed to upload data that is obviously incorrect. How difficult would it be to have a dialog:

Hey you drew some polygons, they are not tagged. Did you mean for them to be buildings?

Yes? Oh would you like for them to be tagged building=yes?

You do? Wonderful, I'll do that before uploading them. Oh by the way, did you think of using 's' to make all those shapes rectangular, where appropriate?

Oh you didn't? Please revisit them. Don't make another human validator suffer needlessly cleaning them up.

OK, I'm exaggerating (just a bit0, but I think you get the point and believe me, we have been telling new mappers how to draw buildings with iD, but they still manage to get it wrong, so often that it hurts.

**Comment by bhousel** [comment]
@PolyglotOpenstreetmap Please be nice.  Lots of people map things in OpenStreetMap that are not buildings.  We're not going to ask our users to fill out a multi-step questionnaire for every upload.

We'll teach users how to draw nice buildings in the walkthrough (coming soon, see #3921) and we do already warn them when they upload things that are not tagged.  

If you find some features in OpenStreetMap that you don't like, you are free to delete them and redraw them.  You can also use Overpass and JOSM to change all the area=yes into buildings if you want.  

> we have been telling new mappers how to draw buildings with iD, but they still manage to get it wrong,

Why do you think that is?  At the mapping events you've been at, how is building tracing introduced to new mappers?  

Anyway, I have spent the past three weeks on improving our walkthrough and I think you will like the improvements that I've made.  I tested it with 4 people yesterday who have never mapped before, and they did still struggle with a few things that I'm going to try to further improve.

If you have the time to checkout the `walkthrough-updates` branch and run through it, I would love your feedback on #3921.  Thanks!

**Comment by PolyglotOpenstreetmap** [comment]
@bhousel Sorry, I didn't want to come across as mean. Somewhat desperate and rather frustrated, maybe, but I realise you are working hard on it.

I'm a strong believer in the incremental workflow of OSM. So deleting stuff people mapped to then redraw it, is not an option for me. I could invalidate those tasks, and try to communicate what went wrong, and believe me, I have been doing that.

When I do validate, it's relatively easy to do Ctrl-f in JOSM and retag all of those buildings as building yes. But that's not the end of the story. The buildings are still not rectangular, so I add all of them to the todo plugin and redraw the corners one by one, using the improve_way_accuracy plugin 'w', then square the using 'q'. All well and good, but this whole operation takes longer than if I had mapped them myself, in the first place and that's where the 'desperation' is coming from. Each and every one of us has only so much time they can dedicate to this project, so if things can be optimized, they should be.

I'm not sure how I can checkout and test things that aren't released yet, but I'll try it out as soon as I can.

At the mapping events I lead, I show how to get things done with JOSM right away. By the end of the day, I could show them how to validate other people's work. And then we were seeing what had happened at the other universities (Belgian National Mapathon a few weeks ago) and those were the exact same problems we were dealing with almost two years ago. (And that's were the frusttration was coming from)

Jo

**Comment by bhousel** [comment]
@PolyglotOpenstreetmap I just got Runnable container working again, so you can test out the new walkthrough with this link: http://265ykk-id-runnable-staging-openstreetmap.runnableapp.com:8080/

(This is a nice service that will host the pull request and update it every time I push code to it)

We've tested with untrained users and so far found a few usability issues that I'm tracking here: https://github.com/openstreetmap/iD/pull/3921#issuecomment-293134719

If you have feedback please add it to #3921, thanks!
