### ISSUE TITLE
Change automatic tag sorting behavior

### ISSUE THREAD

**Issue by BushmanK** [openstreetmap/iD#3960]
Currently, once you've added a key by clicking on "+" and typed it, tag list gets sorted automatically once a list cell with a new key loses focus (when you click on value cell or press Tab). Automatic sorting is a good feature, but it would be better to do that once the whole list or list row loses focus. There are several reasons for that.

First, it is distracting when an input field you supposed to fill suddenly jumps somewhere. It is an unnecessary distraction that makes UX worse, especially if an object has many tags.

Second, current sorting behavior breaks Tab key behavior consistency. Here is what happens now: once you've typed a new key name, you press Tab to switch to a value input field. Here, tag row might change its position in a list according to the first letter of a key. If it did, you can not use Tab to switch to "+" button to add another key. If it didn't, you can.

If tag list sorting would happen only when you go somewhere else from the list or when you go to another row of this list, it should be less distracting for a user and Tab switching should remain fully functional.

**Comment by bhousel** [comment]
I agree, I also find this annoying.. It regressed back when we did the D3 v4 upgrade.
