### ISSUE TITLE
lodash omit

### ISSUE THREAD

**Issue by kepta** [openstreetmap/iD#3965]
We have slipped a breaking change of omit in the v4.
`omit`'s 2nd param has the signature `@param {...(string|string[])} `.
[documentation](https://lodash.com/docs/4.17.4#omit).

At some places we are calling omit with a function as a 2nd param.
- https://github.com/openstreetmap/iD/blob/master/modules/behavior/paste.js#L69

**Comment by bhousel** [comment]
whoa I didn't know, good catch!
