### ISSUE TITLE
Write a changeset tag that says whether a user has completed the walkthrough

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3968]
I've spent a lot of time on improving the walkthrough (#3921).  It might be interesting to know whether new users are actually doing the walkthrough or not.  

For example, if we see a new user making some interesting pattern of mistakes, and we know they _did_ complete the walkthrough, we can improve the walkthrough to address those mistakes.

If we see that they _didn't_ do the walkthrough, we can ask them to complete the walkthrough in a changeset comment when we review their edits.

Thoughts?

**Comment by pnorman** [comment]
Do we reliably have this information? I've been asked several times to do the walkthrough. I suppose in the case of new users it might be valuable because it'd most likely be accurate.

**Comment by bhousel** [comment]
We don't have this information now. Instead we just set a flag in the browser's local storage if the user has never used iD before. But:
* we could start storing things in the user's OSM profile (see #3002)
* we do know from the OSM API if a user has never saved an edit before

**Comment by pnorman** [comment]
I'd go for #3002 and store walkthrough state server-side.
