### ISSUE TITLE
Walkthrough panning still problematic

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#3969]
@bhousel Great that you've worked on the walkthrough!

I'm afraid #2386 isn't yet fixed though.

![panning](https://cloud.githubusercontent.com/assets/4283376/25040217/3f1a8ff0-2108-11e7-8f46-d8114cd17378.gif)

Screencast of latest Firefox on Linux, 52.0.2. I had the same with Brave (which is based on Chromium).

Somtimes even the **shrinkwrapping effect misses** the City Hall, and focuses on another place. That happens quite often, but strangely never while I'm making a screencast*.

Other stages of the walkthrough also have this issue.

---

*This is not an attempt to be funny, I literally mean this.  
I tried 20+ times to reproduce it while screencasting, but never succeeded.  
Without screencasting, window at same size: **4/10 times glitched**.  
Procedure: start walkthrough from welcome screen, pan, observe effect, Ctrl+R, repeat.

**Comment by bhousel** [comment]
I can see from the screenshot that you're still testing with the old walkthrough code.  The new walkthrough is on #3921, which has not merged to master yet.

You can test the code on that branch by using the Runnable link (see first comment on that PR):
test link:  http://265ykk-id-runnable-staging-openstreetmap.runnableapp.com:8080/

Please let me know if that works for you, and put your comments on #3921, thanks!  Hoping to merge in the next day or so..

**Comment by M1dgard** [comment]
Great! I saw the PR in the list but totally forgot that green=open, purple=merged, I always found that very confusing on GitHub. Sorry for the noise!
