### ISSUE TITLE
Uncaught Error: entity w7409928 not found

### ISSUE THREAD

**Issue by tko** [openstreetmap/iD#3973]
Starting the editor seems to sometimes throw an exception leaving it in a state where not all details are loaded and seemingly never will. Reloading the page sometimes works, sometimes throws the same exception with different entity id (I've seen `w7409928` and `w59195767`)

```
id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:57 Uncaught Error: entity w7409928 not found
    at hd.entity (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:57)
    at hd.parentWays (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:57)
    at t (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:4)
    at Object.Rd.i.rebase (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:4)
    at Object.merge (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:11)
    at n (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:11)
    at o (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:11)
    at id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:59
    at t (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:59)
    at l (id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:59)
entity @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:57
parentWays @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:57
t @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:4
Rd.i.rebase @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:4
merge @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:11
n @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:11
o @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:11
(anonymous) @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:59
t @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:59
l @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:59
i.onreadystatechange @ id-63ec25b478c2af431aa10a2e5a9b6d4416ec6423217d481dc9b6d9cc3ee0bc11.js:59
```

http://www.openstreetmap.org/edit?editor=id#map=18/52.33752/4.59592 

Chrome 58.0.3029.41 beta (64-bit), OS X 10.11.6

**Comment by tyrasd** [comment]
I saw something very similar in Chrome `58.0.3029.54 (Official Build) beta (64-bit), V8 5.8.283.24` on Linux a few days ago:

![screenshot from 2017-04-17 15-41-01](https://cloud.githubusercontent.com/assets/1927298/25090581/586e1a0c-2384-11e7-9754-987696b8443d.png)

Note the debug commands I issued after hitting the breakpoint – very strange!

As far as I can see it's probably a race condition inside Chrome's V8 doing some overly optimistic optimization or something. Not sure how to best follow up on this… Wait and see if this even lands in Chrome 58?

**Comment by bhousel** [comment]
Hmm @tyrasd yeah that makes no sense.  It really does seem to be a V8 bug.

**Comment by oiva** [comment]
I'm seeing this too. Chrome 60.0.3107.4 (Official Build) dev (64-bit) and iD 2.2.1. Repeats on every load and as a result some of details are missing.

**Comment by oiva** [comment]
Not sure if this is related but bumped into an error in Firefox where entities were undefined in coreGraph rebase: https://github.com/openstreetmap/iD/blob/b07bf8eaa214518e4df468789a6f300952873c26/modules/core/graph.js#L130

I can make a separate issue of this if necessary.

**Comment by tyrasd** [comment]
We see this now even in the latest stable Chrome build (`59.0.3071.86 (Official Build) (64-bit)` / `V8 5.9.211.31`) on Linux (on Windows it's fine apparently, see https://github.com/openstreetmap/iD/issues/4094#issue-234415640). :unamused:

**Comment by tyrasd** [comment]
This is soo strange. No idea why and what is happening.

What I found is: If one adds `if (!entity) entity = this.entities.__proto__[id];` after [core/graph.js#L36](https://github.com/openstreetmap/iD/blob/07fa5fcc3416f4eda12bdf04ea395e7744435b29/modules/core/graph.js#L36), it seems to work again.

**Comment by bhousel** [comment]
Looking into this now.. What I've learned is that `this` gets broken when in tree.js, `updateParents()` calls `parentWays()`

#### call stack:
![screenshot 2017-06-08 10 46 32](https://user-images.githubusercontent.com/38784/26934587-c6f5cea8-4c37-11e7-98cd-fdf2124a6908.png)

#### caller:
![screenshot 2017-06-08 10 48 54](https://user-images.githubusercontent.com/38784/26934682-19a3aab2-4c38-11e7-9575-9c7ce4bbf271.png)

![screenshot 2017-06-08 10 49 24](https://user-images.githubusercontent.com/38784/26934703-2861d42a-4c38-11e7-8486-a409c101cca9.png)

#### callee:
![screenshot 2017-06-08 10 50 27](https://user-images.githubusercontent.com/38784/26934771-541d13ae-4c38-11e7-8602-98911d742c15.png)

![screenshot 2017-06-08 10 50 34](https://user-images.githubusercontent.com/38784/26934779-5821a226-4c38-11e7-80e0-4c0f74aaf2d1.png)

**Comment by bhousel** [comment]
> What I found is: If one adds if (!entity) entity = this.entities.__proto__[id]; after core/graph.js#L36, it seems to work again.

I spend most of the morning trying to understand what's going on, but got nowhere, so I added this code for now.. If we ever find what upstream bug in Chrome/V8 is causing this we can link to the ticket here and remove the line if it's ever fixed.

**Comment by tyrasd** [comment]
I went ahead and reported it upstream, because I really couldn't find anything related on their bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=731193&can=1&q=prototype%20inheritance&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by bhousel** [comment]
Nice, thanks @tyrasd!

**Comment by dkewley** [comment]
I see this on Chrome OS 59.0.3071.91 too.

A suggestion: Consider updating default iD to have this patch so that those of us using Chrome on Linux or Chrome OS have a usable default iD. I ended up using iD master at http://preview.ideditor.com/master/ in order to be able to do any editing on Chrome OS. Thank you for finding and implementing a workaround on master!

**Comment by bhousel** [comment]
> A suggestion: Consider updating default iD to have this patch so that those of us using Chrome on Linux or Chrome OS have a usable default iD.

Yes, I'm making a new release of iD tomorrow 👍

**Comment by tyrasd** [comment]
It's now fixed in chrome/v8: https://chromium-review.googlesource.com/c/539596/ :+1:

**Comment by bhousel** [comment]
Great!  I'm going to close this issue but I'll leave those extra lines of workaround code in the `entity()` function.  We can remove them someday when Chrome 58/59 is a distant memory.
