### ISSUE TITLE
Walkthrough does inconsistent capitalizing in German

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3977]
The street-attributes oneway and maxspeed translate to the german words Einbahnstraße und Höchstgeschwindigkeit. These are presented with and without capitalized first letter in the walkthrough:
![image](https://cloud.githubusercontent.com/assets/5360273/25288365/6a34965a-26c5-11e7-8028-754ef970c9fb.png)

**Comment by bhousel** [comment]
Ah, thanks for raising this, I forgot that capitalization works differently in German and some other languages.

I'll change those to use quoted strings instead.
