### ISSUE TITLE
Add addr:unit to U.S. address field

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#3980]
Some U.S. mappers put unit/suite/room numbers in the `addr:street` tag because that’s one of two places in a written address where the unit number may go. (It may also be a suffix on the house number.) For example, [this POI](http://www.openstreetmap.org/node/4064072925) is tagged `addr:housenumber=7220` `addr:street=Telegraph Square Dr Suite V`, and [this POI](http://www.openstreetmap.org/node/2480216595) is tagged `addr:housenumber=5825` `addr:street=University Research Court, Suite 3500`. The U.S. address field in iD should have a small text box corresponding to the `addr:unit` tag to the right of the `addr:street` text box, to encourage more structured tagging.

**Comment by bhousel** [comment]
Good suggestion!.. Is it just US addresses or maybe other addresses too?

Either way, the changes need to be made in [address-formats.json](https://github.com/openstreetmap/iD/blob/master/data/address-formats.json).  

BTW this is a good [get-started](https://github.com/openstreetmap/iD/labels/get-started) task, and I'd love to see someone new to contributing take this on.

**Comment by 1ec5** [comment]
> Good suggestion!.. Is it just US addresses or maybe other addresses too?

Yeah, good point. I'm not familiar enough with other countries' addresses to know for sure whether they also number or letter individual subunits and where in the address it goes.

**Comment by slhh** [comment]
> Is it just US addresses or maybe other addresses too?

It seems to be US and maybe Canada only with very rare exceptions:
https://taginfo.openstreetmap.org/keys/addr%3Asuite#map

There are only 3000 uses in total. Is it really worth to blow up the field for this?

I think it would be better to add a button, which is expanding the field to a generic complete form, next to the delete/undo buttons.
 I think this could be useful in other countries too. Exceptions from the regular country specific address format seem to be quite likely.

**Comment by 1ec5** [comment]
> There are only 3000 uses in total. Is it really worth to blow up the field for this?

Sorry, there was a typo in the title of this issue. The proposal is to add a text box corresponding to [`addr:unit`](https://taginfo.openstreetmap.org/keys/addr%3Aunit), not `addr:suite`. “Suite” just happens to be what they’re usually called in American English. There are 207,000 existing uses of `addr:unit`, and that doesn’t count all the instances of suite numbers (along with the word “Suite”) erroneously placed in `addr:street` and `addr:housenumber`.

> I think it would be better to add a button, which is expanding the field to a generic complete form, next to the delete/undo buttons.

Between the address field and raw tag editor, I think we’re in pretty good shape. Acknowledging suite numbers as part of the U.S. address format shouldn’t require an overhaul of the address editing UI. Perhaps wildly nonstandard addresses are common in some countries, but that should be addressed in a separate issue, because the U.S. is relatively consistent (even for Rural Routes).
