### ISSUE TITLE
Small incosistency ("Straßen..." vs. "Straßen") in Walkthrough

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3984]
In German there is "Straßen..." in the menu, but I shoud choose "Straßen" without trippledots.
![image](https://cloud.githubusercontent.com/assets/5360273/25429062/0534a806-2a78-11e7-972f-2f8c8586ac79.png)

**Comment by althio** [comment]
Note this is true in all languages, including English.

I don't think it is very misleading. I think it is more important to add quotes around the word {preset} or {category} for instance. 
If you want an exact match, as a workaround, you can modify the translation for German.
You could try:
https://www.transifex.com/ideditor/id-editor/translate/#de/core/111652267
with the string:
> `**Select {category} from the list**` 
translated as 
> `**Wähle "{category}…" aus der Liste**`

**Comment by bhousel** [comment]
I tried to see what it would look like if we just add the ellipses automatically in the tooltip the same way we do in the preset list, but it looks terrible in English:

<img width="622" alt="screenshot 2017-04-26 09 09 46" src="https://cloud.githubusercontent.com/assets/38784/25436078/2b2d19ca-2a60-11e7-8f99-d02ad70735a5.png">

I don't think anybody is going to get confused by this, so let's leave it as is.  As @althio said, if you really do want to put quotes or ellipses `&hellip;` in your translation, you can do it.  But make sure to preview it on http://preview.ideditor.com/master
