### ISSUE TITLE
wikidata tag is not really added

### ISSUE THREAD

**Issue by rmikke** [openstreetmap/iD#3987]
Automatic adding of wikidata does not work correctly.

Here are steps to reproduce the error:

1. Open an object for edition. I usually do it from OSMOSE or Overpass.
2. Add or change wikipedia field. You can see that wikidata is added automatically. So far so good.
3. Save the object (i.e. commit the changeset), close the tab in browser.
4. Reenter the same object. The wikidata tag is gone in most cases.

Sometimes I could even actually see wikidata tag vanishing from list of all tags the moment I clicked Save, before the list is replaced by the place for a changeset comment.

I can't see any regularity when the wikidata tag is saved and when it is discarded.

**Comment by tyrasd** [comment]
Confirming. As far as I can tell, this happens all the time when one saves when the cursor is still in the wikipedia field (i.e. one hasn't clicked/tabbed out of the input field or hasn't deselected the respective object).

**Comment by rmikke** [comment]
Yup, that's it. When I move focus out of the Wikipedia field, wikidata tag stays. What's more, when clicking out to the Wikipedia field, I can see wikidata tag being removed and reinserted again. I.e.it's inserted when I choose the value for wikipedia field, then removed and reinserted when I click or tab out.
