### ISSUE TITLE
Walkthrough: Right-Klick always counted twice

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3988]
I tried just now with IE 11.0.9600.18638 (Updateversionen 11.0.41), Firefox 53.0 (32-bit) and Chrome Version 56.0.2924.87.

**Comment by bhousel** [comment]
Thanks for the report, this makes some sense because `contextmenu` works a little differently on Windows.  Today I'll focus on the Windows issues and try to close them all out..
