### ISSUE TITLE
Walkthrough: IE does not close feature editor with ESC

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3989]
Pressing ESC (Escape) in  IE 11.0.9600.18638 (Updateversion 11.0.41) does not close the feature editor.

**Comment by bhousel** [comment]
I tried today, but I am able to close the feature editor with Escape on IE11 on Windows 10.. Was it a specific step where the feature editor would not close?

I have this version:

![ie11](https://cloud.githubusercontent.com/assets/38784/25495114/1499cf10-2b4a-11e7-913e-cde7bfc34f3d.png)

**Comment by manfredbrandl** [comment]
I think it was a kind of lock-up of the browser which is not reproducible. Will report again if it is reproducible.
