### ISSUE TITLE
Transifex question

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3990]
Where can i get help with this transifex-problem?
![image](https://cloud.githubusercontent.com/assets/5360273/25479589/b36d51f2-2b45-11e7-929d-d546029177c2.png)

**Comment by bhousel** [comment]
That's weird - I don't know!  The string doesn't appear that way for me in Chrome 57, maybe it is a browser specific issue.

I clicked on "Help" at the top and was taken to a documentation page.  That page doesn't help much with the issue, but there is a live chat feature in the bottom corner, and some text saying that I can send issues to support@transifex.com. 

Looks like this:
<img width="359" alt="screenshot 2017-04-27 09 35 50" src="https://cloud.githubusercontent.com/assets/38784/25485757/fa74b50e-2b2c-11e7-82f4-4925d82c7364.png">

Try out either the chat or the email and let me know what you find!  I'll close here.
