### ISSUE TITLE
Walkthrough: Extra Return in IE required

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3991]
Using the Walkthrough in IE it is not enough to select "description" ("Beschreibung" in German) from "add field" ("Feld hinzufügen" in German), pressing Return is additionally neded.
![image](https://cloud.githubusercontent.com/assets/5360273/25480045/575439d8-2b47-11e7-858a-1d8f86dd3d58.png)
Generally IE is clearly slower than Firefox or Chrome on my machine.

**Comment by manfredbrandl** [comment]
Retry looks like that:
![image](https://cloud.githubusercontent.com/assets/5360273/25480111/af4bfffe-2b47-11e7-8208-baf53dfcd18c.png)

**Comment by bhousel** [comment]
Thanks for this report! I do see that all combo boxes in iD seem to have this issue with IE11.
