### ISSUE TITLE
Is supporting iPad possible?

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3994]
Doing the walkthrough i found the following problems: no right-klick, no placing of second node of line, no shift-klick (can do editing without that).

**Comment by bhousel** [comment]
It's something I'd like to add support for eventually..
There are a bunch of open issues tagged with the label [touch-mobile-tablet](https://github.com/openstreetmap/iD/issues?q=is%3Aopen+is%3Aissue+label%3Atouch-mobile-tablet)

**Comment by bhousel** [comment]
Closing as there isn't anything actionable in this ticket, but there are others that better list the specific issues with mobile support, thanks!
