### ISSUE TITLE
Don't let window.location changes happen during draw modes

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3996]
Browser forward/back can jump the user to a faraway place, creating dangerously large geometries.  I noticed this because my mouse has extra buttons for forward/back, and I was accidentally able to navigate halfway around the world while drawing a building.

We try very hard to prevent the user from doing this.   e.g. there is code in the geolocate button to prevent the user from doing geolocating in the middle of a drawing or dragging.

**Comment by manfredbrandl** [comment]
I think OSM should prevent too large geometries to get uploaded. This should be done at the Stage of the Editor and also at the Stage of the API. Very large Geometries can be handled either with a "large-geometry-allowance" for privileged users or with relations.

**Comment by bhousel** [comment]
> I think OSM should prevent too large geometries to get uploaded. This should be done at the Stage of the Editor and also at the Stage of the API. Very large Geometries can be handled either with a "large-geometry-allowance" for privileged users or with relations.

Yes that's #3681
