### ISSUE TITLE
Cannot complete walkthrough as overlay blocks delete icon

### ISSUE THREAD

**Issue by ecksun** [openstreetmap/iD#3998]
OS: Debian stretch
Browser: Firefox ESR 45.8.0
Plugins: HTTPS Everywhere, Privacy Badger, Tab groups, Vimperator and YesScript.

The issue happens when going through the walk-through and getting to the step to delete the way-point, I think the screenshot below describes it well:

![screenshot_20170427_230958](https://cloud.githubusercontent.com/assets/135807/25504596/caacfaa8-2b9e-11e7-8f60-a4ec4b811388.png)

A workaround is to remove the `curtain` svg from the DOM.

The issue also happens with a new browser profile (without the plugins), screenshot:

![screenshot_20170427_231639](https://cloud.githubusercontent.com/assets/135807/25504826/a1d94e50-2b9f-11e7-99cf-9d4983d59ec6.png)

However, at least with the same new profile, the issue does not appear in http://preview.ideditor.com/master/

**Comment by bhousel** [comment]
Great thanks!  If it's fixed in http://preview.ideditor.com/master/ we can close it.. 👍
