### ISSUE TITLE
The template for secular cemetery has fields for religion/denomination

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#3999]
The template for secular cemetery has fields for religion/denomination, I believe it shouldn't.

**Comment by bhousel** [comment]
https://wiki.openstreetmap.org/wiki/Tag:landuse=cemetery
https://wiki.openstreetmap.org/wiki/Tag:amenity=grave_yard

In this case it looks like we are just following the recommendation on the OSM wiki under "useful combinations".  The short descriptions for these tags could be better too.

If you think it's wrong, can you start a discussion on the wiki or on the tagging mailing list?  I know these discussions can be frustrating and lead nowhere, but it's the best we have for right now at reaching consensus about how tags should be used.

**Comment by pnorman** [comment]
5% of landuse=cemetery have a religion=* tag and 8% of amenity=grave_yard. Leaving aside the messy parts of the tagging, a cemetery unassociated with a place of worship can still be dedicated to one religion.

**Comment by bhousel** [comment]
Let's close this issue for now, I think the current fields ok.
