### ISSUE TITLE
Updating Help

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4001]
The Help should contain the information from the walkthrough to reread without praticing and advanced Information (Imagery, GPS, Relations). Is it possible to take the text from the walkthrough for that and reorganise help that way?
Maybe relations should become an optional part of walkthrough.

**Comment by bhousel** [comment]
I've thought about adding an advanced walkthrough to cover relations.. It would be useful to do eventually.

I also agree that the help sections need some updating too.  Someone had mentioned that we should break the sections up a bit because very long paragraphs are too difficult to translate.  

This makes sense to me, but it would mean that translators would have to redo all of the content in the help section, and right now I'm somewhat frustrated that the existing translations are incomplete (aside from the top 10 languages which are at 100%).

**Comment by manfredbrandl** [comment]
Iit would help translators and readers if sections in the help will become shorter. Not so short as in the walkthrough but shorter than in the existing help.
I did some research on importance of languages and the completeness of translations for iD. Looking at the number of worldwide speakers the three biggest misses are Hindi (650 Mio Speakers, 5% Translation), Arabic (300 Mio, 3%) and Bengali (255 Mio, 23%). Many of those having access to a computer can read Englisch, so translation-status is not so bad!

**Comment by manfredbrandl** [comment]
Good news: Arabic translation completeness is already over 50%

**Comment by bhousel** [comment]
> Arabic translation completeness is already over 50%

That's great!!  👍 
New iD release is scheduled for May 9, so hopefully we can boost these numbers a bit over the weekend!

Please retweet or share this announcement if you can!  https://twitter.com/bhousel/status/860561709643247616

Tag someone who speaks an incompletely translated language 😄

**Comment by bhousel** [comment]
> Maybe relations should become an optional part of walkthrough.

Discussing this on #4012

**Comment by manfredbrandl** [comment]
@bhousel Do you want me to make suggestions for new help texts with shorter sections and updated to the renewed behaviour and terms in iD?

**Comment by bhousel** [comment]
> Do you want me to make suggestions for new help texts with shorter sections and updated to the renewed behaviour and terms in iD? Even if I am not a native speaker?

At this point we aren't quite ready to change the text just yet because I need to change the code first.  It's setup in a way that each section needs to be a single giant block of markdown.  I have to dig in and see what's the best way to split the help content into chapters.

**Comment by bhousel** [comment]
Let's track any discussion of updates to the builtin help on #4018
