### ISSUE TITLE
Preset matching failure on synonyms

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#4002]
It might be related to #3979 and/or #3236 but synonyms matching seems to fail half of the time:

![image](https://cloud.githubusercontent.com/assets/1451988/25579296/df718f50-2e76-11e7-8848-054e5ae924d9.png)

Trying on master, by typing the full synonym:

| synonym                 | works |
|-------------------------|-------|
| salle des fêtes         | KO    |
| salle festive           | OK    |
| centre communautaire    | OK    |
| maison de quartier      | KO    |
| maison des associations | KO    |
| salle des associations  | OK    |
| centre d'animation      | KO    |
| community centre        | KO    |

For instance:

![plop](https://cloud.githubusercontent.com/assets/1451988/25579417/1b999dd2-2e78-11e7-8285-8102bbed96f7.png)

**Comment by althio** [comment]
Hi,

I think the presets in Transifex (changed a few days ago) have not been pushed to the master instance.

**Comment by bhousel** [comment]
I just refreshed the http://preview.ideditor.com/master/ instance with new translations.  I didn't see any issue with the updates, but I will check the cron job to make sure it is still running.

It does seem like the searches for "salle des fêtes" are working better now.  Can you test again and let me know if this can be closed?  Thanks!

**Comment by bagage** [comment]
Strange, I thought these strings were added ages ago (by me actually 😆). Anyway, you are both right and it just works great!
