### ISSUE TITLE
Shortcuts for point/line/area should deselect tool

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#4003]
If you press 1, 2 or 3 on the keyboard to select the point/line/area tool, pressing the same key again should then deselect that same option. Saves using the mouse if you change your mind for example about adding a feature.

**Comment by bhousel** [comment]
Maybe.. You can also press <kbd>Esc</kbd> to go back to browse mode.

**Comment by bhousel** [comment]
FYI, I did this

**Comment by boothym** [comment]
Nice, thanks 👍
