### ISSUE TITLE
Bad alignment (background and tool)

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#4004]
Hello,

The issue: Check this picture :
![displaybug](https://cloud.githubusercontent.com/assets/16977446/25595024/895814fc-2ec3-11e7-871b-4ed15dc1a3fd.PNG)
The issue should be visible enough. This is the background that is at the bad position (Ieft clicked at the center of toolbox)
This happened on Chrome 57.0.2987.133 with iD 2.3.1

I experienced this issue twice without a valid reproduction. The only thing I can tell is that this happen when I select multiple objects (ways at least) and after some clicks it disappear.

**Comment by bhousel** [comment]
Thanks for the report - this happens when the old radial menu tries to fit 9 things into 8 spots.  It's been fixed already in master when using the radial menu in legacy mode, and won't be an issue when using the new right-click menu. 👍

**Comment by homersimpsons** [comment]
Okay, didn't found that issue this is why I opened this :)
Thank you for all your work 👍
