### ISSUE TITLE
prevent drawing invalid areas (spikes, self crossing)

### ISSUE THREAD

**Issue by Klumbumbus** [openstreetmap/iD#4013]
During work in maproulette challanges regarding buildings with spikes I noticed that there are alot buildings with the same error, e.g. https://overpass-api.de/achavi/?changeset=48431373
A possible scenario I can think of is that new users might do not know how to end the drawing of an area in iD resulting in such invalid areas. See possible scenario below:
![01](https://cloud.githubusercontent.com/assets/7115609/25754414/56e993a2-31bf-11e7-9c94-71b1c44964e5.gif)
The node order is AB

**Comment by bhousel** [comment]
done in #4602
