### ISSUE TITLE
Walkthrough's scroll exercise is lacking instructions

### ISSUE THREAD

**Issue by mikini** [openstreetmap/iD#4015]
Having trained clicking each left/right mouse buttons 5 times in the Welcome step, it is peculiar that the first exercise of Navigation just says "drag the map". Shouldn't the procedure be explained in painstaking detail for the total newbie?

Something like;
"Scroll the visible part of the map by pressing and holding the left mouse button while moving the mouse around. The map can also be scrolled by using the arrow keys on you keyboard."

**Comment by bhousel** [comment]
Sounds good - we should probably not assume that the user has any familiarity with web maps.

By the way, the clicking task is mostly to make sure the user can right-click, even if they don't have a real mouse with a right button.  There are so many different ways to right-click that it made sense for that to be its own step!
