### ISSUE TITLE
Don't allow to move objects with middle button

### ISSUE THREAD

**Issue by verdulo** [openstreetmap/iD#4020]
I noticed in the preview version of editor (walkthrough), that it's possible to move elements with middle mouse button. Could you please consider removing that 'feature' and restore the behaviour of version 2.1.3, because now it's really easy to accidentally move some points during moving the map?

EDIT: I noticed that in 2.1.3 it's also possible to move a point with middle button, but only after selecting it, while in the preview version you only need to hover cursor over the point to be able to move it with middle button. Anyway it would be nice to restore the previous behaviour…

**Comment by bhousel** [comment]
Yes, we reverted back to the old behavior with #3824 

We've gone back and forth a few times on whether points and vertices should be easily draggable or not, and we learned that requiring users to select things before dragging them was just too confusing.  Intuitively, things that look draggable should be draggable.

And - it's ok to accidentally drag things.  Just undo (which we now teach in the walkthrough) or drag it back like in any other drawing program.

**Comment by yaomtc** [comment]
@bhousel I also have this issue. Using the middle mouse button in iD should only be for zooming and panning, as is standard in many other applications. It should never be able to select or move any items. Is iD not able to distinguish between the left mouse button and the middle mouse button?

**Comment by yaomtc** [comment]
> Yes, we reverted back to the old behavior with #3824

This issue doesn't mention the middle mouse button. This older issue does: #3612

I see that iD *does* treat the left mouse button and the middle mouse button differently. The LMB *can* select nodes and paths, while the MMB *cannot* select. They can both move the selected object and add new nodes.
