### ISSUE TITLE
Walkthrough refers to Return key on Windows computers

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4028]
In several places, the walkthrough instructs the user to hit the “return” key, regardless of the user’s operating system. However, the key is labeled Enter on most Windows computers.

**Comment by magol** [comment]
+1
It was hard to translate "return" as it is no consensus what this key should be called.

**Comment by bhousel** [comment]
Ah, yeah I forgot. We can just call it "enter" in the instructions.

(btw, I just searched the iD codebase for "return" - that was dumb.)
