### ISSUE TITLE
Make background imagery names translatable

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4034]
Are these items from iD or do i have to translate somewhere else?
![image](https://cloud.githubusercontent.com/assets/5360273/25886495/1b7f48e6-355e-11e7-90d7-3f3cd0112405.png)

**Comment by bhousel** [comment]
Oh we actually have an issue for this in editor-layer-index: https://github.com/osmlab/editor-layer-index/issues/17

I'm not sure the best way to do it.  I could see it either being localized in that project, or in iD.  Maybe I should just add it as another resource to the id-editor team on transifex for the imagery list.  Then we wouldn't need to ask people to sign up for another project.

**Comment by althio** [comment]
@bhousel 
I think @manfredbrandl refered to "Locator Overlay" & "OpenStreetMap GPS traces" while I think you responded on the imagery list instead.

**Comment by bhousel** [comment]
> I think @manfredbrandl refered to "Locator Overlay" & "OpenStreetMap GPS traces" while I think you responded on the imagery list instead.

Yes, but they all come from the imagery list, the overlay sources just have checkboxes instead of radio buttons.

**Comment by manfredbrandl** [comment]
There is a PR in editor-layer-index to solve that problem https://github.com/osmlab/editor-layer-index/pull/343

**Comment by bhousel** [comment]
The upstream work was done and we now have a new [imagery resource](https://www.transifex.com/openstreetmap/id-editor/imagery/) attached to the iD project.  Next steps are for me to merge this resource into iD's language files and use `t()` in the Background pane to display the texts.

**Comment by manfredbrandl** [comment]
I can translate the layer names in transifex-ideditor-imagery and see the effect on preview.ideditor.com/master Thanks!

**Comment by bhousel** [comment]
Great, I just also added support to display translated attribution text too, so closing here 👍
