### ISSUE TITLE
Use temporary local bitmap background

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4035]
Sometimes i do have a local bitmap with a construction plan or better map than imagery. It would help if I could temporary use a local bitmap file as background. After import i would like to position two locations 
 (coordinates) from the background on the map data to get rotation and zoom right.

**Comment by bhousel** [comment]
A good site for this is http://mapwarper.net/
Once your image is uploaded there, you can adjust control points to align it, and then on the "Export" tab you will see a tile source that you can open in iD as a custom background layer.

Try it out and let me know if that works for you and we can close this issue 👍

**Comment by manfredbrandl** [comment]
Thank you, that a very good service. Maybe it should be mentioned somewhere in the help or near the option "user defined background".

**Comment by manfredbrandl** [comment]
@bhousel Now that you upgrade to more than one user defined backgroud, maybe you could mention the mapwarper service (and also other similar services if known) somewhere in iD?
