### ISSUE TITLE
Opening_hours are added with an underscore

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/iD#4038]
I choose "Mo-Sa 08:00-18:00" from the drop-down list, and in the tag I get is `Mo-Sa_08:00-18:00`, which is incorrect. Firefox 52, Russian locale.

![2017-05-12 14 20 41](https://cloud.githubusercontent.com/assets/766031/25996151/5e7a370c-371e-11e7-8ca2-5b64ad7694b6.png)

**Comment by bhousel** [comment]
Thanks ,this is #4030.. It's fixed already, and I'll be releasing a patch hopefully today 👍

**Comment by Zverik** [comment]
Awesome, thanks Bryan. I missed that ticket, since it was closed.
