### ISSUE TITLE
If wiki entry is moved, show the moved page's description

### ISSUE THREAD

**Issue by theel0ja** [openstreetmap/iD#4039]
**amenity=parking**'s **supervised** info page shows this:
![image](https://cloud.githubusercontent.com/assets/5832930/26027719/8172cd84-381b-11e7-8acb-6f1a73fb631e.png)

> This help has been moved to another page

This is because **Key:supervised** redirects to page **Proposed_features/supervised**

**Language used in iD**: Finnish (fi)

**Comment by bhousel** [comment]
Sorry, unfortunately iD can't really follow the links.  The only thing we can do for field documentation is specify which key/value to use for the lookup.

iD uses the taginfo service to determine the best wiki page to fetch.
e.g. https://taginfo.openstreetmap.org/keys/supervised#wiki
