### ISSUE TITLE
move map relatively

### ISSUE THREAD

**Issue by solariserj** [openstreetmap/iD#4040]
I make some buildings and roads? and after some times all was relatively moved at 3-8 meters on the map. What hapend? I want all be correct on the map  and map match reality

**Comment by bhousel** [comment]
It's hard to say what happened - can you share the location of the map where you see this?

If you used Bing to do your editing, they might have just updated their imagery in your area and now the map does not appear in the same place.  Bing's imagery might have gotten more accurate or less.  Press the <kbd>B</kbd> key to open the Background pane and compare different source.

The best solution is to compare the imagery to a reliable GPS trace to know if you can have confidence in the imagery.  You did mention that the imagery now looks 3-8 meters off, which is within the error of most GPS receivers.  You could also compare how things look on [Strava Slide](http://labs.strava.com/slide/), which aggregates GPS traces into a heatmap.

**Comment by bhousel** [comment]
Closing as there isn't anything actionable here for us to do, thanks!
