### ISSUE TITLE
Circle toolbar missing

### ISSUE THREAD

**Issue by jschleuss** [openstreetmap/iD#4041]
In the last few days I haven't seen the circle buttons that appear when you select a node/way/relation. So, I don't see the ability to delete or straighten items. 

I've noticed this in all browsers.
- Chrome (Mac)  57.0.2987.133 (64-bit)
- Safari (Mac) 10
- Firefox 53

![screen_shot_2017-05-14_at_1_53_19_pm](https://cloud.githubusercontent.com/assets/695934/26037667/de158626-38ac-11e7-87d8-424004ea94f2.png)

**Comment by manfredbrandl** [comment]
Please try right-click on these items to show the editing-menu, which is not circular any more since iD 2.2.0

**Comment by jschleuss** [comment]
@manfredbrandl that was it...I missed the announcement that it had changed. Thank you!
