### ISSUE TITLE
Why is there a redirection for the wiki-access

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4044]
When i open the wiki for highway=unclassified iD presents a redirection:
![image](https://cloud.githubusercontent.com/assets/5360273/26062406/0046a08e-398b-11e7-8e95-cd34fa03e086.png)
According to #4039 the wiki url comes from taginfo. There everything is okay:
![image](https://cloud.githubusercontent.com/assets/5360273/26062508/47724a80-398b-11e7-8712-887c170cc039.png)
![image](https://cloud.githubusercontent.com/assets/5360273/26062542/67e1e21c-398b-11e7-9246-de4b10663e93.png)
@bhousel Can you please tell me where the problems originates?

**Comment by bhousel** [comment]
I just looked at the code - iD shows the "redirected" message if taginfo returns a value for the wiki but no description.

I don't know why taginfo didn't pick up the description (Beschreibung), since it does appear in the tag template on the wiki page.

**Comment by slhh** [comment]
> I don't know why taginfo didn't pick up the description (Beschreibung), since it does appear in the tag template on the wiki page.

The code in the wike is:
`description = Nebenstraße mit geringerem Verbindungscharakter als highway=tertiary`
The wiki is handling this well, but maybe taginfo has a parser issue with the second equal sign in the line.

**Comment by manfredbrandl** [comment]
@slhh at https://github.com/taginfo/taginfo/issues/199 exactly that is what is supposed.

**Comment by manfredbrandl** [comment]
The Problem is within taginfo, changing a '=' in the wiki to 'is' solves the problem.
![image](https://cloud.githubusercontent.com/assets/5360273/26593510/9529b0e4-4564-11e7-94fd-3d58a0f23aee.png)
This is not an iD issue any more.
