### ISSUE TITLE
ActiveRecord::RecordNotUnique error occurs when save  .

### ISSUE THREAD

**Issue by sophia-xll** [openstreetmap/iD#4046]
I have an osm data. Both node and way ids are increasing from 1,so it is with changset. I use postgresql database to store , openstreetmap-website to show, and ID editor to edit.  All works well when edit.  However, When I try to save , It  occurs error:
**ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "changsets_pkey" DETAIL: Key (id)=(1) already exists. : INSERT INTO "changesets" ("created_at", "user_id") VALUES ($1, $2, $3) RETURNING "id"** 
Click save button again ,it occurs error: 
**ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "current_nodes_pkey1" DETAIL: Key (id)=(1) already exists. : INSERT INTO "current_nodes" ("latitude", "longitude", "changeset_id", "version", "visible", "timestamp", "tile") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"**
I guess id editor save node,way and changeset using ids increasing from 1. If I am right ,How to edit osm data which ids increasing from 1?

**Comment by bhousel** [comment]
closing, moved upstream to openstreetmap/openstreetmap-website#1542

**Comment by sophia-xll** [comment]
Thanks for your quick and detailed reply. it works well now.
