### ISSUE TITLE
Light version of the editor

### ISSUE THREAD

**Issue by AgentJay** [openstreetmap/iD#4055]
Hello,

I have a site aimed at protected area managers. I'm interested in allowing them to contribute aspects of their parks to OSM.

I was thinking to make a super light OSM editor in Javascript.  The idea would be to start with iD and remove many of the current options. Effectively restricting the kinds of node keys they could add and therefore simplifying the process slightly. 

For example when they add a point it is extremely unlikely that they will be indicating a Fast Food restaurant, a Bank or a Bar. So instead of listing all the available point keys it just gives keys for items that apply to protected areas like Natural Features, Animal Watering Place, Toilets, and Ticket Seller.

Of course we will encourage the option to go directly to OSM to have a fully featured editor. But within our local site interface it will be something far more basic.

Thoughts?

**Comment by manfredbrandl** [comment]
I understand you want to reduce the presets to objects usually found within a protected area. Do you also think of reducing the user interface / editing options?

**Comment by bhousel** [comment]
Nice @AgentJay!  If you want to run a copy of iD with your own presets, see:
https://github.com/openstreetmap/iD/blob/master/API.md#presets

I am going to double check that section of the API document to make sure it is still up-to-date.

Let me know if that's helpful..

**Comment by AgentJay** [comment]
Awesome, the presets are a perfect solution. I wouldn't mind trying to slim down the editing options as well. But the presets are an excellent start. The rest can come later if needed.

Thanks guys, the link to the docs is all I really needed :)  👍
