### ISSUE TITLE
Include a DigitalGlobe layer

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#4063]
According to [this blog post](https://www.openstreetmap.org/user/@kevin_bullock/diary/41132), DigitalGlobe imagery is available for OSM editing.  I saw people commenting of it on JOSM, but I don't see a layer available on iD.

**Comment by bhousel** [comment]
That's odd.. What backgrounds do you see when you press <kbd>B</kbd> to open the background pane?

**Comment by afmenez** [comment]
My bad, I see 2 DigitalGlobe layers actually.  Sorry for the noise.

**Comment by bhousel** [comment]
no problem, just glad they are there! 👍

**Comment by blogcraft** [comment]
How old are the DigitalGlobe Premium Imagery? Because looking at 19.5055/-98.9979 the images are at least 3 years old.

**Comment by bhousel** [comment]
> How old are the DigitalGlobe Premium Imagery? Because looking at 19.5055/-98.9979 the images are at least 3 years old.

I don't know, sorry!  @kevinbullock may be able to get the answer.  

We'd like to be able to show the age of imagery for sources that support it, but haven't built this feature yet, see #2492.
