### ISSUE TITLE
Wrong tagging of street crossing

### ISSUE THREAD

**Issue by Athoss9** [openstreetmap/iD#4066]
When selecting Street crossing, iD editor adds the highway=crossing and crossing=zebra tags, while the correct tags are highway=crossing and crossing_ref=zebra. There also should be a box asking wether the zebra is controlled or not, and write the answer in the crossing=traffic_signals or in the crossing=uncontrolled tag. See: https://wiki.openstreetmap.org/wiki/Key:crossing

**Comment by pnorman** [comment]
Duplicate of #3019. See also #2918.
