### ISSUE TITLE
Copying and pasting points with addresses

### ISSUE THREAD

**Issue by egofree71** [openstreetmap/iD#4067]
Hello,

A few months ago, a new feature has been added to the id editor : when you were copying and pasting  (with Ctrl-c and then Ctrl-v) points with addresses, the pasted points contained also the same address property. This was very useful when you had to create a lot of new addresses with points for a given street. Recently this feature has been removed. If you copy a point, all properties of the new point are lost. Do you know why ?

**Comment by bhousel** [comment]
Yes, being able to copy/paste address details was actually a bug fixed by #3965 .

There is a list of tags that get omitted when copy/pasting, [see here](https://github.com/openstreetmap/iD/blob/7072b260fe32a82d3658a6b1010287eb72192291/modules/behavior/paste.js#L23-L37).

The reasoning behind this is that most users probably _don't_ want to copy the name, address, etc. when copy/pasting features - it's more likely to introduce quiet errors in the data.

**Comment by egofree71** [comment]
Thanks for the answer. Well, if the user want to add a new point without any property, he can easily click on the point icon and click on the map to add a new point. What's the use of copy and paste then ? It's not very useful if no properties are copied. Well, that's my point of my view.
It was really a very useful feature for me as i enter a lot of addresses. For example, in a very long street  with a lot of numbers, with the previous copy and paste, i had only to modify the street number. With the new copy and paste, each time, i have to specify that it's a point, then to choose again the street name, and the town and finally the number. Much more longer.
Would it possible at least to have another option ? For instance when pasting, it would be possible to specify if the properties are copied or not.

**Comment by bhousel** [comment]
Yeah I agree that in some situations it's very useful to be able to copy address details.

What do other people think?

**Comment by manfredbrandl** [comment]
Copying Adress details is useful. Usually nearby Adresses only differ by the house number. So if I want to create many nearby adresses or buildings withAdresses i want addr:* tags to stay, I can modify later but keep Street, City and postal code, sometimes I will only expand the house number ("1" -> "1a", "1b", etc.)

**Comment by bhousel** [comment]
Ok, I'm convinced - I just changed copy/paste to copy _all_ the tags.  It's probably more intuitive than having certain tags omitted, and it actually is pretty useful to be able to copy everything.

**Comment by homersimpsons** [comment]
@egofree71 also considered using relation or line interpolation, this will certainly be faster for your edits :)

**Comment by egofree71** [comment]
Thanks !
