### ISSUE TITLE
why i see the old map ?

### ISSUE THREAD

**Issue by walidseven** [openstreetmap/iD#4069]
hi
i have edited in maps but with the new map ... but now i seen the old map ...

**Comment by bhousel** [comment]
The data as it appears on openstreetmap.org can take some time to re-render:
https://wiki.openstreetmap.org/wiki/FAQ#I_have_just_made_some_changes_to_the_map._How_do_I_get_to_see_my_changes.3F

This usually takes a few minutes but can take longer at low zoom levels.   If you go back to the location later, does it look refreshed?

Let me know if this resolves your issue.  If not, can you include the location where you are not seeing the update and a screenshot?   Thanks!
