### ISSUE TITLE
Public GPS traces loaded over http

### ISSUE THREAD

**Issue by gappleto97** [openstreetmap/iD#4070]
This causes people who use plugins like HTTPS Everywhere to not be able to overlay the traces. It's also generally ill advised.

**Comment by bhousel** [comment]
Sure, it's an easy change. I'll make the change upstream in the editor-layer-index project.

Do you find with HTTPS Everywhere that lots of other imagery sources won't load?  It does look like many of them are `http` but could be `https`.  

Because imagery is considered passive content in browsers, it does not generate a mixed content warning.

**Comment by gappleto97** [comment]
Normally everything is fine. I have noticed an issue every once in a while, though. For instance this one, and with OpenStreetCam. But most places are pretty consistent about which one they use, and even for iD it was only on this one component.

**Comment by gappleto97** [comment]
Actually, I take that back. I just noticed that a ton of the image tiles aren't right either. It's mostly the MapBox ones, but it's also Statmen, USGS, and USFS.

**Comment by pnorman** [comment]
> Do you find with HTTPS Everywhere that lots of other imagery sources won't load? It does look like many of them are http but could be https.

Quite a few sources will be http only, so any browser setup to randomly change them to https or not load over http is going to be horribly broken, so I wouldn't worry too much about it.

**Comment by gappleto97** [comment]
True enough. I just went through and tested which ones work anyways, and put through a PR about it. Might as well, right?

**Comment by bhousel** [comment]
Sure, I agree that sources that can be loaded via `https` should be.
