### ISSUE TITLE
Get rid of building=detached setting?

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/iD#4071]
It's not really clear how different it is from building=house. It only creates confusion. Looking at http://taghistory.raifer.tech/ it got pushed two times quite inorganically.

**Comment by bhousel** [comment]
Yes I did see on the discussion pages for [`building=house`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dhouse) and
 [`building=detached`](https://wiki.openstreetmap.org/wiki/Tag:building%3Ddetached) that some people think the overly-specific house tags should be deprecated, and I think they are confusing too.

However I'm not really comfortable removing a preset that's used around 900,000 times, so the right way forward would be to achieve consensus on the tagging@ mailing list and start a project to replace all those tags with better ones.

**Comment by RicoElectrico** [comment]
Can it be made kind of read-only as in "recognize, but don't suggest"?

**Comment by bhousel** [comment]
> Can it be made kind of read-only so iD recognizes it, but doesn't suggest it?

It could, but without real consensus about its removal it's likely someone else would come here and open an issue to have it put back.
