### ISSUE TITLE
Remove baseline hack

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#4074]
As mentioned in an [old comment](https://github.com/openstreetmap/iD/issues/3020#issuecomment-200552128), we could try to remove the [browser detection](https://github.com/openstreetmap/iD/blob/master/modules/svg/labels.js#L135) here and use  `.setAttribute("dy", "0.6ex");` for all browsers.
This would give good results for all browsers even if edge support `baseline` styles in the future.

**Comment by bhousel** [comment]
Just tried it, but now labels in Chrome are lowered.
There might still be a way around this, but would involve a different hack of using `baseline-shift` to adjust the baseline to whatever IE and Edge default to.

<img width="581" alt="screenshot 2017-06-01 16 02 20" src="https://cloud.githubusercontent.com/assets/38784/26698404/d585bfcc-46e3-11e7-82d6-2a7cc4e235ad.png">

**Comment by HolgerJeromin** [comment]
Wow. In my tests removing all baseline css and using only dy had similar results in all browsers...

**Comment by bhousel** [comment]
> Wow. In my tests removing all baseline css and using only dy had similar results in all browsers...

I might have missed some of the baseline css.. Would definitely accept a pull request if you get it working!
