### ISSUE TITLE
How do I update translations?

### ISSUE THREAD

**Issue by andischan** [openstreetmap/iD#4077]
I would like to change the string "Wenn du eine Maus anhängen willst, mach das jetzt und klicke dann OK." from https://github.com/openstreetmap/iD/blob/master/dist/locales/de.json into "Wenn du eine Maus anschließen möchtest, mach das jetzt und klick dann OK."

Unfortunately the string is not available at transifex. So is it possible to do a pull request for the translation files?

**Comment by tyrasd** [comment]
You can find instructions for contributing translations here: https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating

> Unfortunately the string is not available at transifex.

That's odd. I do see it on transifex: https://www.transifex.com/ideditor/id-editor/translate/#de/core/111652311?key=mouse

**Comment by manfredbrandl** [comment]
Thats odd, I did translate this a month ago and can still see it at transifex:
![image](https://cloud.githubusercontent.com/assets/5360273/26727697/02a5116e-47a8-11e7-90b7-3439a14f8b6e.png)
