### ISSUE TITLE
please allow changes of transifex glossary for German

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4078]
Please translate feature in the glossary as "Objekt", not "Eigenschaft", Same applies to:
zoom -> zoom not vergrößern
area -> Fläche not Gebiet
menu -> menu not ""

**Comment by bhousel** [comment]
@manfredbrandl can anybody update the glossary?  I haven't used this before, but I do see some of the languages are using it.  Let me know if you need special permission on Transifex.

**Comment by manfredbrandl** [comment]
@bhousel I will change the glossary if I get the required permissions to do so. See https://docs.transifex.com/setup/glossary/adding-terms

**Comment by bhousel** [comment]
@manfredbrandl I just made you a coordinator for German language team. Let me know if you're able to update the glossary.

**Comment by manfredbrandl** [comment]
@bhousel thanks for the extra powers, i have updated the glossary to get fewer warnings. i did not succeed removing the warnings for 'feature' but others like 'zoom' vanished.

**Comment by manfredbrandl** [comment]
@bhousel I might have lost access to the glossary as part of transferting iD to the OpenStreetMap Organisation on transifex.

**Comment by bhousel** [comment]
@manfredbrandl I still see you as a coordinator, but it looks like with the recent move, the glossary terms might not have moved over.  Can you try to re-add them?

<img width="389" alt="screenshot 2017-06-08 07 14 51" src="https://user-images.githubusercontent.com/38784/26926112-4c82686a-4c1a-11e7-9fba-8e4dd7498adc.png">

**Comment by manfredbrandl** [comment]
@bhousel there is still a glossary because i get glossary warnings, but i cannot access it any more.

**Comment by bhousel** [comment]
@manfredbrandl As far as I can tell the glossary is there, just empty.  What happens when you click on "Add Term" ?

<img width="663" alt="screenshot 2017-06-08 13 35 19" src="https://user-images.githubusercontent.com/38784/26942284-7b1c3842-4c4f-11e7-86d9-eb816dd29484.png">

**Comment by manfredbrandl** [comment]
Sorry, because of my monitor vertically I did not see "Add term" before. If I add a Term I see:
![image](https://user-images.githubusercontent.com/5360273/26943236-2547d742-4c85-11e7-8a9a-40696b8befa3.png)

**Comment by bhousel** [comment]
Great!  Looks like it is working.  As far as I can tell this is what the glossary does - it just warns you if your translation deviates too much from the ones in the glossary.
