### ISSUE TITLE
Localized keyboard shortcuts

### ISSUE THREAD

**Issue by magol** [openstreetmap/iD#4081]
All keyboard shortcuts are selected based on the US keyboard layout. This is problematic if you use a keyboard layout for another country as the characters are placed differently and you may have to use extra modification key(s) to reach some characters.

This means that some shortcuts that are easy to accomplish on an US keyboard may be difficult or impossible to do on other keyboard layouts.

In addition, many keyboard shortcuts are based on what things are called in English. It may not be obvious in some languages to press <kbd>S</kbd> to Save.

My suggestion is to enable localization of the keyboard shortcuts. This is really no controversial, many desktop applications already do so today. For example, if I want bold text in MS Word, I press <kbd>Ctrl</kbd>+<kbd>B</kbd> (Bold) in an English version and <kbd>Ctrl</kbd>+<kbd>F</kbd> (Fet) in a Swedish version.

Something to take into account is that the same language may have different keyboard layouts and that it differs between different platforms (Windows, Linux, Mac OS)

This issue is related to following issues:

 - #4079 - '?' zooms instead of opening the keyboard shortcuts screen on Swedish keyboard
 - #2885 - Keyboard shortcuts for zoom in/zoom broken on some keyboard layouts
 - #2812 - Cannot open Minimap on Non-US keyboards
 - #3770 - Configurable keyboard shortcuts

**Comment by bhousel** [comment]
> All keyboard shortcuts are selected based on the US keyboard layout. 

iD already does localize all the shortcuts for the operations.  (Rotate, Move, Reflect, Combine, etc)

We could do some of the other ones too, but I'd want the "system" kinds of shortcuts to match whatever the OS does.  (e.g. <kbd>Ctrl</kbd>+<kbd>S</kbd> Save, <kbd>Ctrl</kbd>+<kbd>C</kbd> Copy, <kbd>Ctrl</kbd>+<kbd>V</kbd> Paste - or whatever the OS does for that language)

Keys like <kbd>?</kbd> and <kbd>+</kbd> are especially problematic because they don't work the same in all browsers, even within `en-US` keyboard layout.

> Something to take into account is that the same language may have different keyboard layouts and that it differs between different platforms (Windows, Linux, Mac OS)

How would we handle that?

**Comment by manfredbrandl** [comment]
For me the (primary or only) aim of localizing keyboard-shortcuts is to be able to enable every user to use all shortcuts. Unusable shortcuts should not be shown at the '?'-shortcuts.

**Comment by slhh** [comment]
Supporting the different keyboard styles is neccessary, but this can't be a UI language based localization.
In general a localization of keyboard shortcuts has a severe disadvantage. Any explanation how to do things using shortcuts would be useless for users with different language setting. This does not only affect forum and mailing list content, but also direct support by PM.

**Comment by manfredbrandl** [comment]
I now realised that I oppose localized keyboard shortcuts, because it complicates communication. Copy&Paste simply is Strg-C / Strg-V or 'international': Ctrl-C / Ctrl-V. Differences between languages are complicated enough.

**Comment by bhousel** [comment]
> I now realised that I oppose localized keyboard shortcuts, because it complicates communication. Copy&Paste simply is Strg-C / Strg-V or 'international': Ctrl-C / Ctrl-V. Differences between languages are complicated enough.

Yes I agree we shouldn't localize things like <kbd>Ctrl-C</kbd> / <kbd>Ctrl-V</kbd>, but we do already localize many of the keys and there are probably some more that we could do.  I'll make a list.

This is an issue that might matter more to users of non-latin keyboards.  As far as I know, keyboards in Kanji or Cyrillic also have latin letters on the key caps and use <kbd>Ctrl-C</kbd> / <kbd>Ctrl-V</kbd> like anyone else - however asking them to type <kbd>H</kbd> for help or <kbd>B</kbd> for Background might be weird.

**Comment by bhousel** [comment]
The current state of keyboard shortcut localization is below.

Green = We already allow a language to change the key
Red = We don't provide option to localize the key but we probably should.
All others = We don't provide option to localize the key and we probably should not.

Let me know if I have this right
cc @1ec5, who has localized Vietnamese shortcut keys

<img width="938" alt="screenshot 2017-06-09 09 34 46" src="https://user-images.githubusercontent.com/38784/26977981-c12da9a8-4cf7-11e7-8333-c6fa3c8b2b4e.png">
<img width="946" alt="screenshot 2017-06-09 09 34 58" src="https://user-images.githubusercontent.com/38784/26977986-c6d30452-4cf7-11e7-90d2-c071a33435de.png">

**Comment by 1ec5** [comment]
Yes, that looks about right. It would be worthwhile to localize the “With node selected” shortcuts too: many European keyboard layouts (e.g., Danish, Finnish, French, German on the Mac) lack labeled square and curly brace keys.

I’m not entirely sure about the full screen shortcut. On macOS, ⌃⌘F is the standard full screen shortcut in all applications and in all locales. Similarly, in Firefox on all platforms, Ctrl+Shift+F or ⇧⌘F is mapped to full screen. On the other hand, ⇧⌘F in Chrome toggles the full screen toolbar instead. But I guess that would be a separate issue.

**Comment by manfredbrandl** [comment]
I do agree with the proposed localisation including 'with node selected'. For thoselanguages which are so unhappy as not having the same first letter for straighten and square (e.g. gerade biegen und rechtwinklig machen) please allow having extra keys. Btw: Do the icons before Shift, Return etc. stay? Then I would remove the symbols I added in the translation.

**Comment by bhousel** [comment]
> Btw: Do the icons before Shift, Return etc. stay? Then I would remove the symbols I added in the translation.

For display, the symbols are only shown if you're viewing it on a Mac, otherwise they are dropped, [see here](https://github.com/openstreetmap/iD/blob/d20e05305766e8f73e857e0ba0f7917a5f1513ad/modules/ui/cmd.js#L44-L56).   This code also converts the names of the keys depending if you are on a Mac or not.

So for the translation, you don't need to include the symbols.  
Also I just looked at Transifex - you definitely don't want to translate "Cmd" as "Win ⊞".   
[German Mac keyboards](https://i.stack.imgur.com/ErgQC.jpg) also say "Cmd".

**Comment by bhousel** [comment]
> . For those languages which are so unhappy as not having the same first letter for straighten and square (e.g. gerade biegen und rechtwinklig machen) please allow having extra keys.

Could you double check with the German community on their web forum and make sure this is really what they want, and if so open a new issue?

**Comment by bhousel** [comment]
> On macOS, ⌃⌘F is the standard full screen shortcut in all applications and in all locales.

Ok, in that case we should change it..

**Comment by 1ec5** [comment]
To be clear, both shortcuts currently work in iD. The only possible point of confusion is that it overrides Chrome's shortcut for toggling the toolbar.

**Comment by bhousel** [comment]
> To be clear, both shortcuts currently work in iD. The only possible point of confusion is that it overrides Chrome's shortcut for toggling the toolbar.

Yes, I think the intent was to just bind all of the common "full screen" OS shortcuts so that they all work no matter what OS or browser the user happens to be on.

So the fullscreen shortcuts should be <kbd>⌃⌘F</kbd> and <kbd>F11</kbd>

**Comment by manfredbrandl** [comment]
full screen shortcut with double shift instead of Strg Shift:
![image](https://user-images.githubusercontent.com/5360273/27000792-1fd8d33e-4dba-11e7-9814-95a278f60942.png)

**Comment by bhousel** [comment]
> full screen shortcut with double Strg instead of Strg Shift:

Oh yeah I think we should only offer <kbd>⌃⌘F</kbd> if the user is on a mac.  I just pushed a change for this.

**Comment by manfredbrandl** [comment]
Checked just now with Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.8 (64-bit),
there is still Strg + Strg +F oder F11 for Vollbildmodus (full screen mode). This seems to be complicated.

**Comment by bhousel** [comment]
> Checked just now with Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.8 (64-bit),
> there is still Strg + Strg +F oder F11 for Vollbildmodus (full screen mode). This seems to be complicated.

Sorry about that, I think I got it fixed this time.  Can you check http://preview.ideditor.com/master/ again 
 - should see version 7030c15

It unfortunately is complicated because the code does slightly different things for mac/windows/linux.

**Comment by manfredbrandl** [comment]
Check just now with Chromium on Debian as above, it reads F11 only for full screen mode.
Also checked with Firefox on Debian, where i cannot leave full screen mode (Neither F11, nor Esc nor Strg Shift F helps)

**Comment by bhousel** [comment]
> Check just now with Chromium on Debian as above, it reads F11 only for full screen mode.

Sounds good..

> Also checked with Firefox on Debian, where i cannot leave full screen mode (Neither F11, nor Esc nor Strg Shift F helps)

I'm not going to be able to figure out why it doesn't gets stuck on Firefox and Debian, but if you want to dig into that issue, the code is [here](https://github.com/openstreetmap/iD/blob/master/modules/ui/full_screen.js).

**Comment by manfredbrandl** [comment]
> I'm not going to be able to figure out why it gets stuck on Firefox and Debian, but if you want to dig into that issue, the code is here.
As the next Debian release will come soon I will not test the old one. Maybe the problem is gone in a week.

**Comment by bhousel** [comment]
I added ability to localize these shortcuts:

* <kbd>H</kbd> : Help
* <kbd>?</kbd> : Keyboard Shortcuts
* <kbd>⌘I</kbd> : Infobox
* <kbd>B</kbd> : Background
* <kbd>⌘B</kbd> : Switch Background
* <kbd>F</kbd> : Map Data
* <kbd>W</kbd> : Wireframe
* <kbd>/</kbd> : Minimap

I'd like to not change the vertex navigation keys right now.  We fixed handling of <kbd>AltGr</kbd>, so it might be easier for Germans to use <kbd>{</kbd><kbd>[</kbd><kbd>]</kbd><kbd>}</kbd><kbd>\\</kbd> now, and I don't see any other obvious keys that would work well as forward/backward.

A few of the default keys like <kbd>B</kbd> and </kbd>?</kbd> are still hardcoded in the help text, but updating and rewriting that is #4018
