### ISSUE TITLE
Please add craft=distillery

### ISSUE THREAD

**Issue by notramo** [openstreetmap/iD#4085]
I couldn't find a way to mark an object with this tag. Is it implemented?

**Comment by bhousel** [comment]
Not yet!  I'd love to see someone add this - it's a pretty easy change.
Copy the `data/presets/presets/craft/brewery.json` file to a `distillery.json` and change some of the values inside.

See the [presets README](https://github.com/openstreetmap/iD/blob/master/data/presets/README.md) for more details on how presets work.

https://wiki.openstreetmap.org/wiki/Tag:craft%3Ddistillery
