### ISSUE TITLE
How do we set locale for master deployment?

### ISSUE THREAD

**Issue by mertemin** [openstreetmap/iD#4086]
https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating says that we can view translations live on http://preview.ideditor.com/master/ How do we set locale for master deployment? Any way to do this with a url parameter?

**Comment by bhousel** [comment]
The iD that is on openstreetmap.org tries to use the language preference in your OpenStreetMap profile.  But any other iD elsewhere will use whatever language you have specified in your web browser settings.

Every browser does this a little bit differently, but [here are some instructions](https://www.w3.org/International/questions/qa-lang-priorities#changing) on how to change the language.
