### ISSUE TITLE
Zoom in / Zoom out by a lot : with the mouse wheel

### ISSUE THREAD

**Issue by althio** [openstreetmap/iD#4091]
I would like to `Zoom in / Zoom out by a lot`, just like keyboard shortcut `Ctrl`+`+`,`-`
but with the combo `Ctrl`+ [_mouse wheel_]

**Comment by bhousel** [comment]
I thought about this more today and it's something we could do, but I'd really like to know more about why.  

Doesn't giving the mouse wheel a good spin take you through like 4 zoom levels already?

We'd need to add listeners in `map.js` to see if the user is holding the button down and then if so, adjust the scroll speed [around here](https://github.com/openstreetmap/iD/blob/c22fa60b8a33fdfd9dc668619a797f8c2889f9ad/modules/renderer/map.js#L292-L313).

**Comment by bhousel** [comment]
Closing for now as something that would add more complexity to the map.js code than I'm comfortable with, but please let me know if there is an important usecase for fast-zooming that I'm not seeing, thanks!

**Comment by pnorman** [comment]
> Doesn't giving the mouse wheel a good spin take you through like 4 zoom levels already?

My mouse wheel moves about one zoom per finger movement

**Comment by althio** [comment]
>> Doesn't giving the mouse wheel a good spin take you through like 4 zoom levels already?
>
> My mouse wheel moves about one zoom per finger movement

Same here. If i want to change state/region/country, say going from zoom 19 to zoom 6, it requires something like 12 wheel spins through a good hundred increments.

Mouse wheel: 1 increment = about **0.1 level** of zoom; good spin = 10 to 12 times that, so about **1 to 1.5 level** of zoom ; no modifier
Mouse double-click: zoom in only, **1 level** ; no modifier
Keyboard: 1 increment = next integer zoom, then **1 level** ; modified with `Ctrl` = large step to integer zoom, then **4 levels**

**Comment by bhousel** [comment]
The mousewheel zoom depends on your scrolling speed, which is something you can change in your OS settings.  Browsers can also override this setting - some allow you to "smooth scroll" or "scroll by N lines at a time" - so I'd check both with the OS and browser settings to see if changing these values improves the scrolling in iD.
