### ISSUE TITLE
Copy-Paste not working on kubuntu

### ISSUE THREAD

**Issue by gappleto97** [openstreetmap/iD#4095]
Hi,

This might just be me, but I cannot seem to get copy-paste working. I'm running Kubuntu 17.04, under the latest Firefox, but this issue has been persistent over the last several Firefox updates.

The console is not throwing any errors, so I don't know what information I can provide.

**Comment by edpop** [comment]
Copy-Paste works fine on Ubuntu 14.04.5 LTS Firefox 53.0.3 and Chrome 59.0.3071.86.

**Comment by gappleto97** [comment]
Tomorrow I'll try to mess around with the javascript a little to see what might be causing this.

**Comment by bhousel** [comment]
hey @gappleto97 just checking in, any news on this?

**Comment by gappleto97** [comment]
Well, I have no idea what changed, but it started working now. Sorry for the difficulty.
