### ISSUE TITLE
Backslash key on German keyboard has no effect

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4096]
Pressing '\\' should do the same as pause (change line while walking thru nodes), but doesnt do so on German keyboard. The Problem may be, that the key is 'ß' without modifier, '?' with Shift-Modifier and '\\' with AltGr-Modifier.

**Comment by bhousel** [comment]
Yeah, based on https://github.com/openstreetmap/iD/issues/4079#issuecomment-306474674 I think we may be misinterpreting the keys which are generated with <kbd>Alt Gr</kbd>.

**Comment by bhousel** [comment]
I haven't been able to figure out why <kbd>Alt Gr</kbd> combos are not working in iD.  I had a few people test in IRC this morning, but nothing stood out as being an issue.

If you find that there is a key you can not type, can you go to this page https://codepen.io/bhousel/details/dRGpbO/ and type the key and let me know all of the output, also let me know your browser and OS and what kind of keyboard you have.

**Comment by magol** [comment]
Keyboard layout: Swedish
Browser: Chrome 58
OS: Windows 10

- key: <kbd>\\</kbd> 
  - which: 187 
  - keyCode: 187 
  - shiftKey: false 
  - altKey: **true** 
  - ctrlKey: **true** 
  - metaKey: false 
  - location: 0
- key: <kbd>}</kbd> 
  - which: 48 
  - keyCode: 48 
  - shiftKey: false 
  - altKey: **true** 
  - ctrlKey: **true** 
  - metaKey: false 
  - location: 0
- key: <kbd>]</kbd> 
  - which: 57 
  - keyCode: 57 
  - shiftKey: false 
  - altKey: **true** 
  - ctrlKey: **true** 
  - metaKey: false 
  - location: 0

**Comment by bhousel** [comment]
Awesome thanks @magol 
The `altKey` and `ctrlKey` are what's causing the issue 👍   Not everyone's <kbd>Alt Gr</kbd> key does this, but [some do, especially on Windows](https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute).

I think what I want to do is if _both_ are present to pretend _neither_ are present.  It means we can't define a keyboard shortcut in iD that uses both <kbd>Alt</kbd> and <kbd>Ctrl</kbd> but that's ok because we don't use <kbd>Alt</kbd> for anything right now other than disabling the point snapping in draw modes.

**Comment by bhousel** [comment]
@magol , @manfredbrandl I just pushed an update for this..
Can you test on http://preview.ideditor.com/master/ ?

**Comment by magol** [comment]
<kbd>[</kbd>, <kbd>]</kbd> and <kbd>\\</kbd> do works now :-D

<kbd>{</kbd> and <kbd>}</kbd> do still not works :-(

**Comment by bhousel** [comment]
> `{` and `}` do still not works :-(

Thanks, I just realized now that we did not have these keys in the code even though they were in the documentation .   I just added them.

<kbd>{</kbd> -or- <kbd>Ctrl</kbd><kbd>[</kbd> -or- <kbd>home</kbd>  = first vertex
<kbd>}</kbd> -or- <kbd>Ctrl</kbd><kbd>]</kbd> -or- <kbd>end</kbd>  = last vertex

I don't think the keyboard shortcuts screen has room for all of these though, so I'm going to leave off the <kbd>Ctrl</kbd> alternatives.
