### ISSUE TITLE
Untranslatable String 'Show the keyboard shortcuts screen'

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4100]
Just checked with transifex, all translated there:
![image](https://user-images.githubusercontent.com/5360273/27005687-af80a75a-4e23-11e7-8f59-13171de8f720.png)

**Comment by bhousel** [comment]
It's there now!  
I was playing around with the Transifex client (#4101) and now I can manually push new source files anytime 👍
