### ISSUE TITLE
Please include ⇧ for Shift in Shortcut Screen

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4103]
Now the ⇧ is missing at Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.8 (64-bit) with German language:
![image](https://user-images.githubusercontent.com/5360273/27009857-dcf7685c-4e98-11e7-9b14-b257d3b09a88.png)

**Comment by bhousel** [comment]
I'd really prefer to keep the keyboard symbols only for Mac users.  If we make it so that they show for certain keys and for certain languages, it introduces a bunch of complexity to the code.
