### ISSUE TITLE
Mouse-right-klick not fully displayed on short-cut-screen

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4105]
![image](https://user-images.githubusercontent.com/5360273/27050842-3d0f973e-4fb4-11e7-883c-dbe997f01c3a.png)
This can be seen on Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.8 (64-bit) and Firefox ESR 45.9.0 on Debian 8.8 (64-bit) and also on Safari on iPad.

**Comment by bhousel** [comment]
Thanks!  Yes I can see that the outline of the mouse icon is not being drawn in black.

**Comment by bhousel** [comment]
It looks like svgo might have removed the black fill when it built the iD-sprite asset on openstreetmap-website.  I'll see if I can restore the fill with css, or turn off that rule from the asset pipeline, or just set it to `#000001` or something hacky.

maybe this: https://stackoverflow.com/questions/26167106/svgo-killing-000000-fill

**Comment by bhousel** [comment]
I noticed that the fill is missing from the mouse in the tutorial walkthrough also.
Just opened openstreetmap/openstreetmap-website#1563 which hopefully will fix the issue.

![missing fill](https://user-images.githubusercontent.com/38784/27059193-33a419ec-4fa3-11e7-8331-0a3399e56bd6.gif)

**Comment by bhousel** [comment]
This was fixed in openstreetmap-website.  Thanks @tomhughes for help!

`svgo` was removing the black fill from the mouse symbol, and we fixed it by disabling the `removeUnknownsAndDefaults` svgo plugin.
