### ISSUE TITLE
Option for tags not translated to spanish

### ISSUE THREAD

**Issue by CarlosBrys** [openstreetmap/iD#4106]
Hello
When I added a node from a **security camera**, I found options for some tags that were not translated to **spanish language**.
Those options are not available in Transifex translations.
How can they be translated?
![captura de pantalla de 2017-06-12 16-51-59](https://user-images.githubusercontent.com/6495550/27052323-bc7e3a4a-4f8f-11e7-8036-cc0526456ee3.png)
![captura de pantalla de 2017-06-12 16-52-13](https://user-images.githubusercontent.com/6495550/27052324-bc812d54-4f8f-11e7-99e0-db7edc350e6b.png)

Thank you

**Comment by bhousel** [comment]
See #2708 - We thought about this a lot but we decided against translating the combo fields that display raw OSM values.  It would be too difficult to explain to the user that the field is supposed to contain English values if we present them with a mix of local and raw strings.

**Comment by CarlosBrys** [comment]
I guess you speak english and have no problem interpreting the values in your language. But this is not the case for everyone.

There are many people who map and if they find values in a language that does not understand could lead to misplacing the labels, and lowering the quality of the data.

In the specific case I mentioned (surveillance camera) the values of the tags already appear in different languages. And I think that's a problem.

**Comment by pnorman** [comment]
If a specific tag has only a defined list of possibilities then that list should be in the preset, which will present it as a dropdown and those can be translated. At least, that's my recollection.
