### ISSUE TITLE
Add url option to autostart walkthrough

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4111]
suggested here: https://github.com/openstreetmap/iD/pull/3921#issuecomment-309411195

It might be useful to provide a url option to put the user directly into the walkthrough.

**Comment by althio** [comment]
I tried http://preview.ideditor.com/master/#walkthrough=true and it works 🙇 
What will be the url on production http://www.openstreetmap.org/edit?editor=id once deployed?

**Comment by bhousel** [comment]
> What will be the url on production http://www.openstreetmap.org/edit?editor=id once deployed?

It will be similar, just add a `walkthrough=true` param to the hash part of the url, so something like `http://www.openstreetmap.org/edit?editor=id#walkthrough=true`
