### ISSUE TITLE
Fix translation for imagery with a '.' in the id

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4112]
see https://github.com/osmlab/editor-layer-index/issues/346#issuecomment-309551574

Some imagery sources, like 'basemap.at', have a dot '.' in their id.  This is a problem because Transifex uses the dot as a separator, so [this code in `t()`](https://github.com/openstreetmap/iD/blob/689bd38048eeccd7d8dbb36b14fbdc0aa2171b38/modules/util/locale.js#L28) splits the string at the '.' and can't lookup the translation string properly.

**Comment by bhousel** [comment]
This is fixed now!
@manfredbrandl  can you test that your translations are now appearing on http://preview.ideditor.com/master/ ?

**Comment by manfredbrandl** [comment]
@bhousel Translation is okay now. Maybe the mouse-over-text could be placed at bit higher?
![image](https://user-images.githubusercontent.com/5360273/27324946-17f16308-55a7-11e7-9e8c-603eb4f64cda.png)
