### ISSUE TITLE
Merging two objects as first edit does not activate the undo button

### ISSUE THREAD

**Issue by ToeBee** [openstreetmap/iD#4113]
If as your first action you choose a building outline and a point within it and use the "Merge" feature, the undo button is not properly activated. It is still grayed out and the hover text says "Nothing to undo". However if you click it, it does actually still work and undoes the merge.

I can reproduce this on both Chromium 58 and Firefox 54.

**Comment by bhousel** [comment]
Thanks - that does sound like a bug..

**Comment by ToeBee** [comment]
Additionally, if you do a merge and then do something else (for example, drop a new point feature) and then use the undo button, the merge will be silently undone when you undo that last action.

So:
1) Merge a way and a node
2) Create a new point feature
3) Undo point creation
4) Point creation is undone but so is the merge

**Comment by bhousel** [comment]
Ah yeah that makes sense.. We recently added an extra step to re-match the preset for the newly merged object (in order to cleanup unneeded tags like `area=yes` - see #3851).  It was that extra step that was messing up the undo/redo annotation.  

Thanks for reporting this @ToeBee!
