### ISSUE TITLE
Confirmation for reset

### ISSUE THREAD

**Issue by fqdb** [openstreetmap/iD#4117]
Could there be a confirmation dialog for the reset button?

Especially since 'reset' and 'restore' are the same size, it's easy to click another out of habit.

**Comment by bhousel** [comment]
Can you share a screenshot? I'm not sure which buttons you mean..

**Comment by fqdb** [comment]
![image](https://user-images.githubusercontent.com/2826336/27518718-8a993f0a-59e6-11e7-94fb-c69a9d225b72.png)

Maybe the buttons could also be redisigned or renamed, because the left symbol is also a common symbol to mean 'reset', and right one could seem like a 'cancel', as in 'do nothing and keep previous'.

**Comment by bhousel** [comment]
I think changing the icons would probably confuse people who are already very familiar with this dialog. 

But I think the text labels could be improved.  What if they said "Restore my changes" / "Discard my changes" ?

**Comment by fqdb** [comment]
Yes, that would be an improvement.
