### ISSUE TITLE
Tiles ans Overlay for Sweden

### ISSUE THREAD

**Issue by magol** [openstreetmap/iD#4119]
http://maps.openstreetmap.se have a number of great tiles and overlays. Is it possible to integrate them into iD?
In the list below, `{service}` can have following values: `tms` or `tiles`.

# Tiles

<table>
  <tr>
    <th colspan="2">Title</td>
    <th>Url</td>
    <th>Description</td>
  </tr>
  <tr>
    <td rowspan="3">Hydda</td>
    <td>Full</td>
    <td><code>{abcdef}.tile.openstreetmap.se/ hydda/full/{z}/{x}/{y}.png</code></td>
    <td rowspan="3">Tiles to support <a href="http://hydda.se">hydda.se</a></td>
  </tr>
  <tr>
    <td>Base</td>
    <td><code>{abcdef}.tile.openstreetmap.se/ hydda/base/{z}/{x}/{y}.png</code></td>
  </tr>
  <tr>
    <td>Roads and Labels</td>
    <td><code>{abcdef}.tile.openstreetmap.se/ hydda/roads_and_labels/{z}/{x}/{y}.png</code></td>
  </tr>
  <tr>
    <td colspan="2">Ekonomiska kartan</td>
    <td><code>http://mapproxy.openstreetmap.se/{service}/ 1.0.0/ek_EPSG3857/{z}/{x}/{y}.jpeg</code></td>
    <td>From Lantmäteriets from about 1950 to about 1980.</td>
  </tr>
  <tr>
    <td>Sverigekartan</td>
    <td>1994</td>
    <td><code>http://mapproxy.openstreetmap.se/{service}/ 1.0.0/sverigekartan94_EPSG3857/{z}/{x}/{y}.jpeg</code></td>
    <td>The Swedish map from 1994
  </tr>
  <tr>
    <td rowspan="2">Aerial imagery over Helsingborg</td>
    <td>2014</td>
    <td><code>http://mapproxy.openstreetmap.se/{service}/ 1.0.0/hborg2014_EPSG3857/{z}/{x}/{y}.jpeg</code></td>
    <td rowspan="2">Aerial imagery over Helsingborg</td>
  </tr>
  <tr>
    <td>2016</td>
    <td><code>http://mapproxy.openstreetmap.se/{service}/ 1.0.0/hborg2016_EPSG3857/{z}/{x}/{y}.jpeg</code></td>
  </tr>
  <tr>
    <td>Aerial imagery over Kalmar</td>
    <td>2012</td>
    <td><code>http://mapproxy.openstreetmap.se/{service}/ 1.0.0/kalmar2012_EPSG3857/{z}/{x}/{y}.jpeg</code></td>
    <td>Aerial imagery over Kalmar from 2012</td>
  </tr>
</table>

# Overlay

<table>
  <tr>
    <th colspan="2">Title</td>
    <th>Url</td>
    <th>Description</td>
  </tr>
  <tr>
    <td colspan="2">NVDB - Speed and cycle paths</td>
    <td><code>http://mapproxy.openstreetmap.se/{service}/ 1.0.0/nvdb_speeds/EPSG3857/{z}/{x}/{y}.png</code></td>
    <td rowspan="2">Speeds taken from the National Road Database (NVDB). Normal colors and with colors adapted for color-blind.</td>
  </tr>
  <tr>
    <td colspan="2">NVDB - Speed and cycle paths - alternative colors</td>
    <td><code>http://mapproxy.openstreetmap.se/{service}/ 1.0.0/nvdb_speeds_alt/EPSG3857/{z}/{x}/{y}.png</code></td>
  </tr>
  <tr>
    <td colspan="2">NVDB - Highway names</td>
    <td><code>http://mapproxy.openstreetmap.se/{service}/ 1.0.0/nvdb_names/EPSG3857/{z}/{x}/{y}.png</code></td>
    <td>Highway names taken from the National Road Database (NVDB)</td>
  </tr>
</table>

**Comment by bhousel** [comment]
Hi, thanks for the report. iD's background imagery sources come from the [editor-layer-index](https://github.com/osmlab/editor-layer-index) project. Can you open the request there with the links and license details?  Thanks!

**Comment by magol** [comment]
Ok, I have added request in the editor-layer-index project to add the sources.

- https://github.com/osmlab/editor-layer-index/issues/347 - Add Hydda for Sweden
- https://github.com/osmlab/editor-layer-index/issues/348 - Add "Ekonomiska kartan" for Sweden
- https://github.com/osmlab/editor-layer-index/issues/349 - Add Sverigekartan for Sweden
- https://github.com/osmlab/editor-layer-index/issues/350 - Add Orthophotograph of Helsingborg
- https://github.com/osmlab/editor-layer-index/issues/351 - Add Orthophotograph of Kalmar
- https://github.com/osmlab/editor-layer-index/issues/352 - Add overlay from Swedish National Road Database
