### ISSUE TITLE
Strings for Translation created again and again

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4123]
I have translated about 15 Strings in Transifex at least twice and the same strings apear again:
![image](https://user-images.githubusercontent.com/5360273/27674116-8e6476de-5ca4-11e7-848c-24ca18a90f0c.png)
Maybe there is a problem in the scripts or with transifex.

**Comment by bhousel** [comment]
Thanks, I'll check that - it should not be pushing strings to Transifex from my PR branch.

**Comment by manfredbrandl** [comment]
Thanks: There was not push in the last hour. But the translation do not come to preview.ideditor.com/master:
![image](https://user-images.githubusercontent.com/5360273/27694312-0a6bdb18-5cec-11e7-8e24-495e1fa4f4e1.png)
![image](https://user-images.githubusercontent.com/5360273/27694347-1bba14b6-5cec-11e7-9188-ea157cfe4bc7.png)

**Comment by manfredbrandl** [comment]
Thanks again, i have to wait for #4121 .

**Comment by bhousel** [comment]
yes, but #4121 should not be pushing strings to Transifex yet, so there's an issue on the TravisCI setup if it is doing so.

**Comment by bhousel** [comment]
fixed now on the `info-box` branch:
8dd7644 Fix permissions
ee783a0 Do not push translation strings to Transifex for pull requests
