### ISSUE TITLE
Wikidata tag gets deleted in iD when changing wikipedia article language

### ISSUE THREAD

**Issue by manoharuss** [openstreetmap/iD#4126]
I was able to reproduce this by trying an edit on my hometown.

![idbug](https://user-images.githubusercontent.com/8921295/27830658-0aad30a2-60e5-11e7-8366-c62fe5883727.gif)

- When we deleted the Wikipedia English article for a feature, wikidata tag gets deleted as well
- It does come back when we give the English Wikipedia article again
- But it does not get fetched if the wikipedia article is any other language

#### Problem 🚨 

- Changing Wikipedia article language is prevalent on OSM. Example changeset: https://www.openstreetmap.org/changeset/50019065
- Changing the article language is not wrong

cc @bhousel @kepta

**Comment by bhousel** [comment]
I just tested and it looks like this has already been fixed by e8bd6bf
I'm going to release a new version of iD with that fix and close for now, but please let me know if the issue still exists.

**Comment by bhousel** [comment]
p.s. If you are able, can you test this in http://preview.ideditor.com/master/ ?  Thanks!
