### ISSUE TITLE
Warn when adding shop=chemist without amenity=pharmacy nearby

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4127]
iD should issue a validator warning at publish time if the changeset includes a newly added `shop=chemist` point or area and no nearby `amenity=pharmacy`. Of course there are legitimate `shop=chemist`s without a pharmacy desk, especially in Europe, but the user can always choose to ignore the warning in that case.

In #3213, I noted this downside to labeling the `shop=chemist` preset as “Drugstore” in the U.S. English localization:

> Now an American iD user who wants to tag a Rite Aid may search for “drugstore” and end up tagging the building with `shop=chemist`; it’s unlikely that they’ll also tag the pharmacy counter separately, having already tagged a “drugstore”.

After discovering [this Walgreens](http://www.openstreetmap.org/way/452403891/history) tagged as a `shop=chemist` without a corresponding `amenity=pharmacy` (and fixing the issue), I wanted to get a sense of whether this incomplete mapping (not quite wrong, just incomplete) is widespread a year after the preset was renamed to “drugstore”. Here are the three largest standalone drugstore chains in the U.S.:

* CVS: Of the [38 `shop=chemist` POIs and areas](http://overpass-turbo.eu/s/qbR) in the contiguous U.S., [16 are also tagged `amenity=pharmacy`](http://overpass-turbo.eu/s/qbS). Only 3 have separate `amenity=pharmacy` nodes within 40 meters, all of them by JOSM users who were unaffected by the `shop=chemist` preset being named “Drugstore”.

* Walgreens: Of the [140 `shop=chemist` POIs and areas](http://overpass-turbo.eu/s/qbT) in the contiguous U.S., [12 are also tagged `amenity=pharmacy`](http://overpass-turbo.eu/s/qbU). [Only 46](http://overpass-turbo.eu/s/qbV) have separate `amenity=pharmacy` nodes within 40 meters, at least 34 of them by JOSM users (1 by an iD user other than myself).

* Rite Aid: Of the [43 `shop=chemist` POIs and areas](http://overpass-turbo.eu/s/qcg) in the contiguous U.S., [1 is also tagged `amenity=pharmacy`](http://overpass-turbo.eu/s/qch). [Only 22](http://overpass-turbo.eu/s/qci) have separate `amenity=pharmacy` nodes within 40 meters, 20 of them by JOSM users.

This shows that, for users who find the “Drugstore” preset in iD, the need to separately map the pharmacy desk is undiscoverable. A user looking to fill a prescription is going to search for pharmacies, not chemists, but they’ll get incomplete results unless they search specifically for “CVS” et al. Eventually this could become a significant phenomenon. However, if editors that call `shop=chemist` a “drugstore” were to also implement the validator proposed here, I think we could head off that outcome.

It’s worth noting that the low overall numbers of `shop=chemist`s here is probably due to the fact that the name-suggestion-index-powered presets for each of these brands adds `amenity=pharmacy` rather than `shop=chemist`.

/ref osmlab/name-suggestion-index#30
/cc @bhousel

**Comment by bhousel** [comment]
I discussed this with @1ec5 and we're going to close this in favor of #4138, because there are many situations where we want to suggest to a user that they might want to add another thing inside a thing, but validations for all those situations is not necessarily the best way to do it.

Also, the osmlab/name-suggestion-index#30 issue is legitimate and we should make that change.

**Comment by 1ec5** [comment]
I was recently asked about the pharmacy/drugstore situation, so here’s an update to the statistics. Overall, I’m seeing some signs of pushback against the drugstore-as-`chemist` tagging scheme, with `amenity=pharmacy` being added to a number of POIs that were formerly just `shop=chemist`. It could be that mappers see the toothbrush-and-toothpaste icon in the Standard renderer but expect to see a pill bottle, so they retag the drugstore POI instead of adding a separate pharmacy POI.

* CVS: Of the [58 `shop=chemist` POIs and areas](http://overpass-turbo.eu/s/qbR) in the contiguous U.S., [19 are also tagged `amenity=pharmacy`](http://overpass-turbo.eu/s/wa6). [Only 8](http://overpass-turbo.eu/s/wa9) have separate `amenity=pharmacy` nodes within 40 meters, 4 of them by JOSM users who were unaffected by the `shop=chemist` preset being named “Drugstore”.

* Walgreens: Of the [134 `shop=chemist` POIs and areas](http://overpass-turbo.eu/s/qbT) in the contiguous U.S., [44 are also tagged `amenity=pharmacy`](http://overpass-turbo.eu/s/wab). [Only 47](http://overpass-turbo.eu/s/wac) have separate `amenity=pharmacy` nodes within 40 meters, [10 of them by iD users](http://overpass-turbo.eu/s/wae).

* Rite Aid: Of the [53 `shop=chemist` POIs and areas](http://overpass-turbo.eu/s/qcg) in the contiguous U.S., [15 are also tagged `amenity=pharmacy`](http://overpass-turbo.eu/s/wag). [Only 25](http://overpass-turbo.eu/s/wah) have separate `amenity=pharmacy` nodes within 40 meters, none of them by iD users.

FYI @nickidlugash

**Comment by bhousel** [comment]
@1ec5 We never changed `name-suggestion-index` though, so all of those chains are still being added as `amenity=pharmacy`.

**Comment by 1ec5** [comment]
Right, I think that accounts for `shop=chemist` not being used all that much – the relatively few occurrences would be due to people manually naming a POI after classifying it. However, I do find it interesting that, unless my queries are erroneous, the number of pure `shop=chemist`s has been going down and the number of POIs dually tagged as `shop=chemist` and `amenity=pharmacy` has been going up.
