### ISSUE TITLE
Please allow translation of 'Vertex'

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4129]
This is 'Knoten' in German:
![image](https://user-images.githubusercontent.com/5360273/27900989-a2abcc0a-6230-11e7-8a0a-49d77484db49.png)

**Comment by bhousel** [comment]
The translation key for this one is `geometry.vertex`:

<img width="917" alt="screenshot 2017-07-06 08 07 36" src="https://user-images.githubusercontent.com/38784/27910229-3a6ff520-6222-11e7-8dd1-16ce8fc5ea6b.png">

**Comment by manfredbrandl** [comment]
sorry, my fault.
