### ISSUE TITLE
Highlight selected relation

### ISSUE THREAD

**Issue by planemad** [openstreetmap/iD#4130]
When a user selects a relation like a turn restriction, it opens the properties on the left, but does not visually indicate where it is on the map. This makes it cumbersome to locate the members, since it has to be done one by one.

Expected behavior would be to highlight the members of the relation just like for single objects, and focus on the individual member when one hovers over it in the member list.

![screen shot 2017-07-06 at 5 05 03 pm](https://user-images.githubusercontent.com/126868/27909237-5d9b1c00-626d-11e7-9620-004687812564.png)

Related https://github.com/openstreetmap/iD/issues/3604 https://github.com/openstreetmap/iD/issues/2946

**Comment by bhousel** [comment]
I agree this is important to do..
Closing here as we already have #659, #2980, and PR #3140 
The PR is not bad, but it hijacks the selection style and there are some downsides to doing it that way.
