### ISSUE TITLE
Small triangle in the middle of a marked line is hard to find

### ISSUE THREAD

**Issue by tkansgar** [openstreetmap/iD#4136]
Hi,

when I have clicked a line (e.g. a road or a path), it is marked with a blinking thicker line. That's ok. Somewhere between its start and end points there is displayed a small white triangle, which one can use to insert a new point on the line. When the mouse is nearby this triangle there is a small green '+' sign displayed next to the mouse cursor. But sometimes on very long lines it is quite hard to find this triangle, since it is very small. Could it be displayed in another colour, e.g. in Green too? Or could it be displayed somewhat bigger, so that it is easier to find?

tkansgar

**Comment by bhousel** [comment]
Thanks @tkansgar, the midpoint triangles are supposed to be subtle, but I will see if I can make them a little easier to see without making them look too much like the real points.

I'm not sure if you knew, but you can also double click on the line to make a new point - you don't strictly need to drag a midpoint.

**Comment by tkansgar** [comment]
Hi bhousel,

many thanks for your reply!

> I'm not sure if you knew, but you can also double click on the line to make a new point - you don't strictly need to drag a midpoint.

This I didn't know really. But I just tried it, and I will use it in future. Many thanks again for this note!

tkansgar

**Comment by bhousel** [comment]
No problem @tkansgar, I'm glad the double-click trick works for you!  I did update the walkthrough with new content to teach users that they can double click on a line to add a point, but it is not something that we taught until recently.

I did try adjusting the display of the midpoints a little bit, but I think I'm going to leave them as-is for now.

The bigger challenge with these midpoints is not making them more visible if there are few of them, but rather making them less visible if there are many of them and they compete with the real points and oneway markers for users' attention.  I think the current style strikes an acceptable balance here.

<img width="769" alt="screenshot 2017-07-10 18 47 27" src="https://user-images.githubusercontent.com/38784/28043557-704dff3a-65a0-11e7-81e1-297ed9147d9d.png">

**Comment by magol** [comment]
@bhousel This was news for me to. Maybe this should be added to the Shortcuts view?  Ok, it is not a keyboard shortcut, but it is still important information for the user. 

I now also noted that the "Place a point" in the "Shortcuts view" say that you only can place a point with the space bar. It should also say that you can do a single click with left mouse button.

**Comment by bhousel** [comment]
> I now also noted that the "Place a point" in the "Shortcuts view" say that you only can place a point with the space bar. It should also say that you can do a single click with left mouse button.

Oh yeah, you are right.  I just added this in 24a4f34

**Comment by bhousel** [comment]
> This was news for me to. Maybe this should be added to the Shortcuts view? Ok, it is not a keyboard shortcut, but it is still important information for the user.

Maybe, though I can't think of a good existing place in the keyboard shortcuts screen to add it right now.  We do teach the double-click trick now in the walkthrough, and it says this in the help under the "Roads" section (so there are other opportunities for people to learn it now):

>First click on the road you want to change. This will highlight it and show control points along it that you can drag to better locations. If you want to add new control points for more detail, double-click a part of the road without a node, and one will be added.

**Comment by tkansgar** [comment]
Hi bhousel,

> The bigger challenge with these midpoints is not making them more visible if there are few of them, but rather making them less visible if there are many of them and they compete with the real points and oneway markers for users' attention. I think the current style strikes an acceptable balance here.

Due to such difficulties I proposed to display the triangle in another colour, e.g. in same green as the '+' sign next to the mouse cursor. I think this wouldn't conflict with any other possible symbols on the line.

tkansgar

**Comment by magol** [comment]
@bhousel
> Maybe, though I can't think of a good existing place in the keyboard shortcuts screen to add it right now. 

I suggest to add it under "Place a point" in the keyboard shortcuts screen. I think that "Place a point" and the new "Place a point on a line" are related to each other. As a icon for the double click I suggest to add <sup>&#215;2</sup> to the normal Left-click icon  (For &#215;, I did use [\u00D7](http://www.fileformat.info/info/unicode/char/00d7/index.htm)).
