### ISSUE TITLE
Keeping to and from roles in turn restrictions

### ISSUE THREAD

**Issue by kreuzschnabel** [openstreetmap/iD#4140]
Imagine a way on a primary road, call it w1, with two nodes on its ends, n1 and n2. 

Some mappers tend to explicitly forbid U-turns on the ends of such ways by restriction=no_u_turn and the members

w1 as from
n1 as via
w1 as to

(and the same at the other end).

Now, whenever such a way is split using iD, say into w1 and w2 linked by the new node n3, it will put one of the parts in the to and the other into the from role:

w1 as from
n1 as via
w2 as to

This TR is technically no longer valid because the to-role is not connected to the via-role. However, this kind of restriction makes OsmAnd interpret the restriction as, „no_straight_on“ in the given order of from and to, ignoring the wrong via. We have had several routing misbehaviour because of that on primary roads in Germany in recent weeks. 

My suggestion: Whenever a way is split which is linked to both "to" and "from" role in a TR, after the split the same way (which touches the "via" node) should be in "to" and "from" on order to preserve the TR.

**Comment by bhousel** [comment]
Wow that sounds pretty bad, thanks for reporting this!
