### ISSUE TITLE
Problem writing data in ID.  The forest was saved 300km away

### ISSUE THREAD

**Issue by Slawek234** [openstreetmap/iD#4141]
Problem writing data in ID. Result https://www.openstreetmap.org/way/506072822. 
I recorded here https://www.openstreetmap.org/changeset/50134134. 
The forest was saved 300km away. How it's possible?

**Comment by bhousel** [comment]
It looks like the forest was saved correctly, but [rowers2](https://www.openstreetmap.org/changeset/50175785) later moved it in changeset [50175785](https://www.openstreetmap.org/changeset/50175785).  They used JOSM to do it, so it doesn't seem to be an iD bug.  Maybe try reaching out to the user in a changeset discussion?  It might have been an accident.

**Comment by Slawek234** [comment]
Thanks for the reply
