### ISSUE TITLE
Moving way changes shape

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#4146]
![id-move-simplify](https://user-images.githubusercontent.com/117278/28097422-66dad05a-66f3-11e7-98dc-528a4a264c1e.gif)

ID v2.3.1

**Comment by bhousel** [comment]
Thanks for the report!  This is kind of like #2731 and probably needs a similar fix.
I have noticed this before when mapping, and usually I just immediately re-circularize the way after I've moved it.

**Comment by bhousel** [comment]
Hey @andrewharvey I'm having trouble reproducing this issue locally - can you tell me the location of this roundabout?

**Comment by andrewharvey** [comment]
https://www.openstreetmap.org/edit#map=21/-33.86187/151.08778

I can still replicate the issue.

**Comment by edpop** [comment]
Similar as https://github.com/openstreetmap/iD/issues/3797

**Comment by bhousel** [comment]
I fixed this:
0b6183e2c 2018-01-29 Remove any duplicate vertex created during `replaceMovedVertex`
9b200cf51 2018-01-28 Code cleanups, changes to `replaceMovedVertex` in `moveAction`
