### ISSUE TITLE
Add clothes type preset for Clothing Store preset

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/iD#4149]
As of this writing, the clothing preset appears like this figure 1. I propose adding the `clothes=*` ([wiki](http://wiki.openstreetmap.org/wiki/Key:clothes)) key in the style iD uses for things like restaurant cuisine (see figure 2).

As of 2017-07-12 the counts for these tags are in table 1 ([via tag info](https://taginfo.openstreetmap.org/keys/clothes#values))

Sorry about the `@2x` screen grabs 🤓 

![image](https://user-images.githubusercontent.com/1827881/28126230-e4622fa2-66f6-11e7-85ef-130b1da465ab.png)
**Figure 1**

![image](https://user-images.githubusercontent.com/1827881/28126311-205de636-66f7-11e7-9966-b325f52db6f3.png)
**Figure 2**

| category  | count |
|-----------|-------|
| women     | 2674  |
| underwear | 1379  |
| children  | 1024  |
| men       | 1011  |
| wedding   | 545   |
| yes       | 323   |
| sports    | 299   |
| workwear  | 193   |
| babies    | 159   |
| denim     | 156   |
| lingerie  | 140   |
| fur       | 116   |
| fashion   | 112   |
| hats      | 112   |
| suits     | 107   |
| leather   | 72    |

**Table 1**

**Comment by bhousel** [comment]
Thanks!  I just added this field to Clothing Store (`shop=clothes`), and I also added it to the presets for `shop=boutique` and `shop=fashion`, because even the osm wiki admits that it's unclear what the difference is between all of these.
