### ISSUE TITLE
Add Background inspector button to Background flyout

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4151]
I’m not using the terms of art here, but the Background flyout (the sidebar on the right) could have a checkbox for showing and hiding the Background inspector (the little panel in the bottom-right). The Command-Shift-B shortcut is fairly undiscoverable, even for people who may be interested in using it. The Background flyout is a natural place to look for it.

**Comment by bhousel** [comment]
See what I wrote on https://github.com/openstreetmap/iD/issues/4152#issuecomment-315086801 for why I'm closing this.  Again, I might change my mind later, this isn't like a wontfix-ever.
