### ISSUE TITLE
Distinguish Service Roads from Parking Aisle

### ISSUE THREAD

**Issue by tjvp** [openstreetmap/iD#4157]
I don't know the best way of doing this (color, thickness) but have them distinguished would be very helpful.

**Comment by bhousel** [comment]
Service roads with a special `service=*` tag are now drawn with a different color.  This includes things like `service=parking_aisle`, `service=drive-through`, `service=alley` and probably some others I am forgetting.

I used the color `#dcd9b9`, which is the same color we use for `highway=unclassified`, but these service roads are drawn thinly.   (Thick roads are for normal traffic, thin roads are for service traffic).

<img width="852" alt="screenshot 2017-07-21 12 45 50" src="https://user-images.githubusercontent.com/38784/28473507-ea1fd5b6-6e12-11e7-8a8f-1e39d5bae88d.png">

**Comment by bhousel** [comment]
Well, this is a surprise.  A completely unintended, but useful, side effect is that now railways with a `service=*` tag (siding, yard, etc.) also use that same color `#dcd9b9` for their stroke:

<img width="913" alt="screenshot 2017-07-24 01 16 40" src="https://user-images.githubusercontent.com/38784/28509114-f8d8c2be-700d-11e7-87dc-3d10ca6fea61.png">
