### ISSUE TITLE
'All tags' collapses every time a tag is changed or added

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4159]

**Comment by bhousel** [comment]
I haven't seen anything like what you are describing.  What browser are you using?

Can you use [LICEcap](http://www.cockos.com/licecap/) or similar to record a screencast of what you see?

**Comment by SelfishSeahorse** [comment]
Hi! Thanks for replying. I'm using Safari on macOS:

![osm_id_editor_problem](https://user-images.githubusercontent.com/14875493/28307859-a1b9eb06-6ba4-11e7-8c4a-88ab1f44b450.gif)

I've just downloaded Firefox: the problem doesn't occur with it.

**Comment by bhousel** [comment]
Thanks for the update, that definitely looks like a bug!

**Comment by bhousel** [comment]
BTW, which version of Safari is this?   I am testing with Version 10.1.1 (12603.2.4) - and it doesn't do quite what your screenshot shows, but it does oddly flash the url bar when tabbing off the value field.

**Comment by bhousel** [comment]
@SelfishSeahorse Just a hunch, does clicking this button in Safari's Advanced Preferences screen fix the problem?

<img width="656" alt="screenshot 2017-07-22 11 44 54" src="https://user-images.githubusercontent.com/38784/28492518-4eaa8290-6ed3-11e7-9adc-90a29483acb3.png">

I've been playing with tabbing in Safari, and it definitely doesn't do what other browsers do when it reaches the end of the All Tags section.. Instead it tries to focus the address bar, but we steal that focus back a split second later when the new empty tag row is added.  

Safari also tries to send the user to the address bar when tabbing through the "All Fields" (if "All Tags" section is hidden).  Or it tries to send the user to the address bar when tabbing past the end of "All Relations" section.  Basically, Safari just does this after the user tabs away from whatever Safari decides is last tab-able thing in the sidebar.

I can possibly add a keyboard trap as a workaround.  This would be like a hidden fake input field that appears in the DOM after the other sidebar content and doesn't allow the user to tab out of it, thus preventing them from accidentally focusing the address bar. 

related: https://stackoverflow.com/a/1914496/7620

**Comment by SelfishSeahorse** [comment]
> BTW, which version of Safari is this? I am testing with Version 10.1.1 (12603.2.4)...

I'm using version 10.1.1 (12603.2.4), too (on MacOS Sierra 10.12.5). However, I've just found out that the problem only occurs in Private Browsing mode. So I won't use that again.

By the way, in Private Browsing mode, the 'All tags' section collapses not only when pressing the tab key, but also when moving from one field to the next with the mouse.

**Comment by bhousel** [comment]
> I'm using version 10.1.1 (12603.2.4), too (on MacOS Sierra 10.12.5). However, I've just found out that the problem only occurs in Private Browsing mode. So I won't use that again.
> 
> By the way, in Private Browsing mode, the 'All tags' section collapses not only when pressing the tab key, but also when moving from one field to the next with the mouse.

Oh this makes a lot of sense, thanks!    You can continue to use Private Browsing mode - I'll fix the issue that's causing the sidebar sections to collapse, and release a new iD in the next day or so.

**Comment by SelfishSeahorse** [comment]
Thank you!
