### ISSUE TITLE
Highway Legend

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4161]
Similar to the Keyboard Shortcuts popup (#3791), we could add a Highway Legend popup to explain what all the road styles mean.

It could look _exactly_ like this...
<img width="863" alt="screenshot 2017-07-18 23 24 29" src="https://user-images.githubusercontent.com/38784/28349570-aa2997ba-6c11-11e7-9848-b449125049fe.png">

**Comment by planemad** [comment]
A common question when showing OSM to someone new is what all those colors mean and where the legend is. Showing the map key helps, but users still find it difficult to match the similiar colors on the map and matching them to the legend.

<img width="301" alt="screen shot 2017-07-19 at 9 08 35 am" src="https://user-images.githubusercontent.com/126868/28349691-f9d063d4-6c61-11e7-9e34-612fe930c41d.png">

What if the map key was on the map features themselves. Like label the motorways as "Motorway" or "Motorway under construction". This would help interpret the features directly and avoid the step of matching the map to a separate visual legend.

**Comment by 1ec5** [comment]
> What if the map key was on the map features themselves. Like label the motorways as "Motorway" or "Motorway under construction". This would help interpret the features directly and avoid the step of matching the map to a separate visual legend.

This sounds like [balloon help](https://en.wikipedia.org/wiki/Balloon_help). iD could pick out some representative features for each preset and annotate them with balloons all at the same time until the user turns the balloons off. The main benefit is that the user doesn’t have to mouse over each feature to see what the sidebar calls it. But the unfortunate thing about balloon help is that it gets in the way very easily.

What if the legend were a step in the walkthrough tutorial instead of an entirely new mode?

**Comment by planemad** [comment]
> This sounds like balloon help

Was thinking more of direct labelling like this

<img width="640" alt="screen shot 2017-07-19 at 10 21 07 am" src="https://user-images.githubusercontent.com/126868/28351205-03bc3c24-6c6c-11e7-9f76-edbb6208d849.png">

**Comment by geohacker** [comment]
cc @rasagy

**Comment by manfredbrandl** [comment]
The fundamental information is that OSM roads are categorized according to importance within the road network and not according to form of way. This is as i understand den community consensus. For less important roads that means that fotos are not the best way to determine the category. Compare 'Landstraße' alias 'Secondary Road'
![image](https://user-images.githubusercontent.com/5360273/28355541-b7ee3d8a-6c64-11e7-9379-9f2e9f50670d.png) to 'Verbindungsstraße' alias 'Tertiary Road'
![image](https://user-images.githubusercontent.com/5360273/28355551-cc1e6d34-6c64-11e7-8e3f-88b42013a2be.png)

**Comment by bhousel** [comment]
Yes, @manfredbrandl, the goal here isn't to try to suggest road classifications.  This came up as an issue because someone was confused by something that they saw in iD.  We actually display a lot of highway information by using color, opacity, strokes, casings, but we don't communicate that anywhere to the user.

**Comment by bhousel** [comment]
I've decided I don't want to do this anymore 😆   closing..
