### ISSUE TITLE
Request: Create mode "click to duplicate" for power lines and tress, etc.

### ISSUE THREAD

**Issue by EwenH** [openstreetmap/iD#4170]
Hi,
   I have been attempting to create long high voltage power lines over hundreds of kilometers. 

It would be useful when adding a large number of trees is to have a duplicate mode. After you click it, it stores the previous node tags and then as you click around, it adds a duplicate of the original node at that point.

The same for power lines.  You create the first power pole or tower and then click the duplicate mode and every time you left click, it extends the power line (if connected) and creates a pole or tower (what ever was selected).  It would make adding large numbers of like nodes a whole lot easier.

**Comment by boothym** [comment]
In case you didn't know, you can select a tree node and then use ctrl+c and ctrl+v to copy and paste them.

Same goes for power poles or towers (although you need to manually input the tags as the preset doesn't for nodes). For a power line - if you left click on each pole or tower, you can then return to select each one individually and add a pole or tower from the preset list. Or use { } to move left/right through the nodes.

**Comment by bhousel** [comment]
Yes this would be super useful.. What you described is how I'm imagining #590 would work, so I'm closing here as a duplicate.
