### ISSUE TITLE
Storing `oauth_secret` in the JS is insecure

### ISSUE THREAD

**Issue by zdila** [openstreetmap/iD#4176]
OAuth client secret should never get to the browser. Please see also https://github.com/osmlab/osm-auth/issues/51.

**Comment by bhousel** [comment]
Hey @zdila, because iD is a browser-based application I don't think there is any other way to do this.  I agree that it's not ideal.  

As this is really an upstream issue, let's brainstorm on https://github.com/osmlab/osm-auth/issues/51 for ways we might improve this.
