### ISSUE TITLE
Give Reference field more specific labels

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4180]
The Reference field, which is backed by the `ref` tag and appears in numerous presets, tends to be [misinterpreted as a place to indicate a source](https://taginfo.openstreetmap.org/tags/?key=ref&value=http%3A%2F%2Fglobus.tut.by), similar to the purpose of a “Reference” section in a Wikipedia article. As far as I can tell, none of the use cases for `ref` is actually called “a reference” per se in English.

iD should head off this confusion and promote appropriate usage of `ref` by naming the field more appropriately based on the preset. For example:

* On Road Route, Bus Route, Bicycle Route, etc., call it “Route Number”.
* On Motorway, Trunk Road, Primary Link, etc., call it “Road Number” – or “Route Number” also?
* On Motorway Junction, call it “Junction Number” or “Exit Number”.
* On Airport and Airfield, call it “Airport Code”.
* On Stop Position, call it “Stop Number”.
* On Platform, call it “Platform Number”.

For any miscellaneous uses, “Reference Code” would be a good alternative to “Reference”.

There’s already a variant of the Reference field with a placeholder reading “Hole number”; I think it would be better to label the field itself “Hole Number”.

**Comment by bhousel** [comment]
Sounds good to me..

**Comment by magol** [comment]
the ref for airport should not be used according to [Tag:aeroway=aerodrome](https://wiki.openstreetmap.org/wiki/Tag%3Aaeroway%3Daerodrome). Instead of renaming it, it should be hidden so that you do not use it by mistake.

**Comment by bhousel** [comment]
Thanks for pointing that out @magol - I didn't realize `ref` on airports was deprecated.. I agree we should remove the field, since we have `iata` and `icao` already.
