### ISSUE TITLE
Railway Platform tagged as way displays as footpath

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4182]
When a way is tagged as "railway=platform", it shows like it is a footpath.
![screenshot](http://i.glideservers.com/u/jam7006468c-dc27-4560-b3d7-df581db3da3c.png)

If tagged with area=yes, it fixes
![screenshot2](http://i.glideservers.com/u/jam9b18eeba-bef8-4b2a-b2c2-5994973c2945.png)

**Comment by bhousel** [comment]
Yes, I did this by design in e55f680 - you don't like it?

My reasons were because, 1. the old rendering was very hard to see, 2. people should connect footpaths/sidewalks/steps to the platforms.  Platforms are really part of the pedestrian network.

I'm definitely open to changing it though.

**Comment by JamesKingdom** [comment]
I agree that it was quite hard to see before, but I also think that that design should be kept for footpaths.

Maybe the we change the colour slightly, to something that is not already used.
It's just that it confused me at first, as I thought that somebody had tagged this incorrectly as a path.

**Comment by bhousel** [comment]
> Maybe the we change the colour slightly, to something that is not already used.
> It's just that it confused me at first, as I thought that somebody had tagged this incorrectly as a path.

Ok that's fair.. Along the lines of #4157, people like special rendering to distinguish between "the default thing" and "a special thing", so this would be similar.  We can't support every kind of feature in OSM having it's own unique rendering, but we can use color to indicate that a feature is interesting.

**Comment by JamesKingdom** [comment]
Sounds good, thanks!

**Comment by bhousel** [comment]
The platforms are slightly different from the sidewalks now..

<img width="844" alt="screenshot 2017-07-29 21 33 30" src="https://user-images.githubusercontent.com/38784/28749923-a06cb634-74a5-11e7-8161-3c54b47aaf0a.png">
