### ISSUE TITLE
Validator for unjoined crossings

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4186]
It’s a common error to draw a pedestrian crossing as a line crossing a road but not intersecting it. It would be great if iD could warn when a connection is missing.

**Comment by jjiglesiasg** [comment]
As far as I understand when you draw in this way is just for visualization in the map, but has NO effect in the navigation features. The correct is to mark the Node as Pedestrian Crossing. 

Validation should be a VERY NICE tool to have in ID, not just the "Untagged" Warning

**Comment by bhousel** [comment]
Actually I think #1669 covers this one  (I agree it's a thing we should add somehow)
