### ISSUE TITLE
Remove bin=yes from excrement bag vending machine

### ISSUE THREAD

**Issue by michaelzangl** [openstreetmap/iD#4191]
Currently, there are two presets.

The dog waste basket sets:
* `amenity=waste_basket`
* `waste=dog_excrement`

The dog excrement bag vending sets:
* `amenity=vending_machine`
* `vending=excrement_bags`

They both conflict in the amenity tag. So far a OSM design issue...

Often, they are combined. Currently, this is mapped by adding a `bin=yes` to the vending_machine. This is not perfect but as good as it currently is. In Germany, those bags are often found on dog waste baskets. But most of the time, the dog waste basket is more dominant. So when new users enter it, they add a dog waste basket. Then, you have no way of adding the excrement_bags vending.

There should be a possibility to add the excrement bags after the dog waste basket was selected or some notice on how to fix this (select excrement bag vending first).

**Comment by JamesKingdom** [comment]
Thanks for the reminder, it's just that here in the UK having bags supplied on a bin is very uncommon, and I completely forgot about this when adding it.
I still think that we should leave the seperate vending machine for dog bags preset, as there might be a time where it is not in a location with a bin, but add a checkbox that allows you to specify if it vends bags, @bhousel , what do you think?

**Comment by michaelzangl** [comment]
Yes, I would keep them as separate items. We have many vending machines hanging on street signs/other things without a bin.

The problem I see is with the tagging inconsistency. There should be a consistent way to tag it if there are both.

Personally, adding a `vending=excrement_bags` would be enough for me, that is what I query for ;-).  It would at least allow to find them somehow and fix things when/if there is a common standard.

Adding a simple `bin=yes` to a `amenity=vending_machine` is not perfect either. Many times, that bin is only meant for dog waste, so the `amenity=vending_machine` preset should add `waste=dog_excrement` as well (dropdown?)

German forum suggests to [tag them as two nodes](https://forum.openstreetmap.org/viewtopic.php?pid=480408). But they are often combined in one housing.

Btw: The wiki is inconsistent on payment (`fee=no` and `payment:none=yes` as well)

**Comment by JamesKingdom** [comment]
The original "excrement bad vending machine", has other fields such as fee, operator and payment type, so I suspect that we should carry these over to the bin. That said, the bin doesn't have an operator field, and maybe it should.

**Comment by bhousel** [comment]
Can we just urge users to map the bag dispenser and the waste bin as 2 separate nodes?
I really don't want to invent something that conflicts with what the wiki says (unless there is a really good reason, like people adding really wrong data). 

for reference:  https://wiki.openstreetmap.org/wiki/Tag:vending%3Dexcrement_bags

I know that we could add a "dispenses bags" field to the wastebin, and an "accepts waste" field to the bag vender, but let's not do that.

**Comment by magol** [comment]
I think this discusion should be move to the taggig mailing list. The schema is should be changed to solve this issue.

**Comment by michaelzangl** [comment]
The problem I see is not with the tagging, but with the user interface (in fact, I don't care much about tagging and going the tagging list/proposal way takes years).

I am currently trying to convince a local dog community to help mapping. This is a easy task for starters and everyone finds a station that is not mapped. The problem is that the UI is confusing at the moment.

So I'd suggest:
1. Add a `vending=excrement_bags` to the dog waste bin (makes sense, since the dog waste bin is the more dominant thing most of the times) or
2. Simply drop the `bin=yes` for the vending.

**Comment by bhousel** [comment]
I agree we can drop the `bin=yes` from the "vending machine" to encourage people to map 2 nodes.

**Comment by simonpoole** [comment]
Sorry but using a bin=yes/no tag is established tagging for objects that have a waste paper bin attached and is used the small number of 58'174 times.

**Comment by bhousel** [comment]
@simonpoole see
https://taginfo.openstreetmap.org/tags/?key=vending&value=excrement_bags
https://taginfo.openstreetmap.org/tags/?key=vending&value=excrement_bags#combinations

There are 13 332 waste bag vending machines of which 1 407 have a `bin=*` tag, so this tagging is not as well established as putting `bin` on e.g. a bus stop.

Conversely 
https://taginfo.openstreetmap.org/keys/waste#values
There are 1 772 `waste=dog_excrement` tags. 

Both the wiki, and actual usage of the tags, and common sense, suggest that people should map the bag vending machine and the waste bin as two separate objects, so that's what we're going to support.

**Comment by alexwohlbruck** [comment]
I want to follow up years later and say that yes, we should update the editor to remove this conflated tag preset. I have not known how to tag these for a while and have hesitated to do so
