### ISSUE TITLE
More Railway Presets

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4193]
Following #4192, I took a look at https://wiki.openstreetmap.org/wiki/Key:railway, and there are a bunch of other common railway things that we don't have presets for.

We don't need everything, but I think these are easy to add:
* `railway=signal`  (I'll draw an icon - considered traffic light, but it should be different)
* `railway=switch` (`"icon": "poi-junction"`)
* `railway=derail` (`"icon": "roadblock"`)

@JamesKingdom want to add these (and whatever others you want to?)

**Comment by JamesKingdom** [comment]
Sure, I'll get started on these.
