### ISSUE TITLE
Unable to delete large objects

### ISSUE THREAD

**Issue by Mashin6** [openstreetmap/iD#4195]
Maybe it would be good to reconsider some parameters defining when object can be deleted.

Currently, if you have larger object (e.g. neighborhood or campus boundary) you can't delete it unless all parts of it are visible. But when you zoom out some of the objects start to become hidden because of overplotting, which disables the object removal (if the large object is connected to some of the hidden smaller objects).

**Comment by bhousel** [comment]
Yes, most people want for iD to have these protections.  

After #2929 we will have a way to override the protections, but the plan is to also audit what the user does and write some changeset tags so that OSMCha users will see that the changeset is suspicious (e.g. large objects were deleted).
