### ISSUE TITLE
Given X, Y, place a point there. So hard!

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4197]
User wishes to place a tower at exact coordinates X, Y which he knows.

He searches by entering the coordinates in the search box, but he still has to guess where exactly in the middle of the screen the point lies so he can place a tower there.

**Comment by jidanni** [comment]
Why don't you have a marker show up where the search result lies?
That is what Google does, even though it is not in editing mode.

**Comment by jidanni** [comment]
OK here is a workaround: Click ++++++++ until it zooms no more. Place the point, hoping that the center has stayed centered. Note: we might not even have any imagery, we just want to place a point at a certain long/lat pair.

**Comment by bhousel** [comment]
You can use the Location Panel to see where the mouse cursor is, and place your point exactly where you want it.  
On Mac: <kbd>Command+Shift+L</kbd>, On Windows: <kbd>Ctrl+Shift+L</kbd>

(Also like you said, you can zoom in a lot)

**Comment by jidanni** [comment]
I am afraid all that is no replacement for a marker appearing at the point the user entered.

What if the familiar red marker of Google map search results disappeared?

**Comment by pnorman** [comment]
iD is a tool designed for editing crowd-sourced map data, so isn't really comparable to a tool like Google map search results.

Are you editing something other than OSM where you want to input coordinates manually instead of a normal means of mapping?

**Comment by jidanni** [comment]
Long ago computers did not have graphical interfaces, and the only way
to enter a data item was with its exact coordinates.

Nowadays there are graphical interfaces, but let's not throw away the
ability to enter a data item via its coordinates.

E.g., Bill the busy executive wants to enter one oil well at
22.22222,33.33333 .

Yes I am talking about OSM.

Don't assume everything is always already on imagery.

**Comment by tyrasd** [comment]
> Nowadays there are graphical interfaces, but let's not throw away the
ability to enter a data item via its coordinates.

Note that iD is not OSM's only editor. Bill's probably better of using [Level0](https://wiki.openstreetmap.org/wiki/Level0) or JOSM for this job, which both provide a way to enter exact coordinates.

**Comment by jidanni** [comment]
Bill is a busy executive.
Bill just want to put oil well A123 at point 22.333,44.555.
What could be simpler? I really can't think of anything!
He clicks "Edit".
(Or, he click the little arrow next to "Edit":
and chooses "Potlatch2" and gets
"You need a Flash player to use Potlatch, the OpenStreetMap Flash editor."
or chooses "..JOSM..",
and nothing happens for him (of course.)
And there is no way he will hear about "Level0".

**Comment by bhousel** [comment]
Bill sounds like the kind of person who might mix up latitude and longitude.  That's why we don't let him enter coordinate data directly.

**Comment by bhousel** [comment]
This has already been discussed a lot in the past, and it's not something we are going to change..
see:  https://github.com/openstreetmap/iD/issues/3088#issuecomment-214594012

There are several reasons, but the main one is that if you are allowed to move the points along a way anywhere, a person can easily create ways that span across the world (intentionally or accidentally) which can cause significant breakage to OpenStreetMap by dirtying a lot of tiles or breaking coastlines or boundaries, or other kinds of things that really mess up the tileservers.

Also, you can just use JOSM or level0 or even make a fork of iD if you really want to do this.

**Comment by jidanni** [comment]
OK, replacing this bug with a rather harmless https://github.com/openstreetmap/iD/issues/4218

**Comment by jidanni** [comment]
Hack complete!

Hack to search for exact coordinate position and actually see where it is (instead of just "somewhere in the center of the screen")!:
1. Read https://developer.chrome.com/docs/devtools/device-mode/geolocation/ and set your favorite coordinates as shown.
2. Then simply type "l" as in https://github.com/openstreetmap/iD/issues/8399#issuecomment-830921127
3. voila:
![20210503T074142](https://user-images.githubusercontent.com/1230959/116831787-f74ee200-abe3-11eb-95b0-93606834b499.jpg)
