### ISSUE TITLE
Map data layer rendering suddenly disappears

### ISSUE THREAD

**Issue by TagaSanPedroAko** [openstreetmap/iD#4202]
While I am editing OpenStreetMap via iD, the data layer for existing map features suddenly disappears. I am editing from a tablet computer, but not known whether it is a glitch or something that only occurs when editing via on a mobile device. Please fix this.

**Comment by bhousel** [comment]
It's kind of hard to know what might be causing this.  Does the background disappear too and everything turns black?  It could be that something is causing the map to go to an invalid lng/lat. (e.g. NaN/NaN)

**Comment by TagaSanPedroAko** [comment]
It's just the data layer disappearing. The background remains, but the data becomes invisible, other than when drawing a line.

**Comment by bhousel** [comment]
Can you tell us more about your tablet computer, or the place on the map where you are editing?

**Comment by TagaSanPedroAko** [comment]
The data layer is okay after pressing the "Edit" button, but after swiping the map several times or undoing line edits, the data layer suddenly disappears. It wasn't normal, that I suspect that it is a bug, but I don't know if it is only on mobile, or even also on desktop.

**Comment by bhousel** [comment]
stale
