### ISSUE TITLE
Offer clone/copy item

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4205]
The user wishes to add a High Voltage Tower next to an existing one.
All the details are almost the same.
It would be so nice if he could click copy, from some context menu,
and then in a point he just made, dump all the details in from the old node, make minor adjustments, and then save.
In fact there are two ways of doing this: copying just the key / value pairs, or even cloning a whole node to a new spot.

**Comment by bhousel** [comment]
For now, copy and pasting the tower node with <kbd>⌘C</kbd> <kbd>⌘V</kbd> will work.  Just paste more towers near the power line and drag them onto where they should be.

We have some other open issues for copy/pasting tags (#839), or creating new items with the same tags as the previous items (#590).  Whenever we add these, editing similar things will become much more efficient.
