### ISSUE TITLE
User cannot make another High-Voltage Tower

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4206]
User click on an existing feature, and sees
 High-Voltage Tower
Clicking 'i' shows
 For towers or pylons carrying high voltage electricity cables. Normally constructed from steel latticework.
 View on OpenStreetMap Wiki

OK, but say the user wants to make another High-Voltage Tower
In the Search box, try as he might, he just can't get High-Voltage Tower.
He can get Tower, but not High-Voltage Tower.

**Comment by bhousel** [comment]
This is the same as #4205
