### ISSUE TITLE
Do not remove "Go to home location" from the user menu in the upper right corner.

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4208]
Do not remove "Go to home location" from the user menu in the upper right corner.

The user might often want to zoom to his home location there in the editor. No need to needlessly deprive him of it.

**Comment by jidanni** [comment]
Yes he wants to see his home location in the editor, without needing to exit the editor, go to his home location, and then start the editor again.

**Comment by jidanni** [comment]
Hmmm, missing when viewing ones profile, etc. too.
Anyways, you could put it back when in ID, making it especially zoom to the Home location, without leaving the editor.

**Comment by bhousel** [comment]
This is an [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website) issue, not something in iD.  We have no control over the user menu on openstreetmap.org - only the stuff that runs inside the iD iframe.

**Comment by jidanni** [comment]
(Yes but I suspect if I got them to put it back, it would leave the
editor...)

**Comment by bhousel** [comment]
> Yes but I suspect if I got them to put it back, it would leave the editor.

Yeah this makes sense.. We'd have to build some logic into that button to know if a user is editing to just change the frame and not refresh the whole page.
