### ISSUE TITLE
Please indicate IDs of entities in UI

### ISSUE THREAD

**Issue by ben-strasser** [openstreetmap/iD#4211]
Hi,

I'm using the ID editor in the version that is currently live on openstreetmap.org to fix turn restrictions. A turn restriction should usually have one to and one from role. This is not the case with this restriction:

https://www.openstreetmap.org/relation/2689543

The problem is that the person that created the restriction did not only add the ways directly incident to the via-node. He also added the ways one after and one before. Correcting this should not be a problem. We only need to remove the two superfluous ways and everything is fine. Unfortunately, ID only shows me this:

![screenshot from 2017-08-02 15 33 46](https://user-images.githubusercontent.com/11960463/28876131-68b79f06-7798-11e7-9441-2cb65b922e26.png)

As the OSM ways are part of the same road all of them have the same name. It is impossible to figure out from the UI which way is which. Adding the way IDs to the UI would make this clear.

**Comment by bhousel** [comment]
In this case it would be easier to just delete the restriction and redo it.   You can do this by deleting all the members, then the relation should go away (although this is not obvious).

But there are some things we could improve in iD:
- make it easy to see which member is which
- make it easy to do things (like delete) to relations, e.g. support some kind of right click menu for them

**Comment by ben-strasser** [comment]
Hi,

recreating a relation is IMO a bad idea as it changes the relation ID. All databases that reference it contain broken links after doing this operation. Why not just show the IDs so that the existing relation can be fixed? 

I have a list here of turn restriction IDs that come from my tool and are broken in some way that I am manually checking and fixing. Fixing relations with ID turned out to be very unpleasant because of problems such as this. For example, a simple operation of the form "add way 42 to relation 123 as from" is surprisingly difficult to do. I first need to look up the way because one cannot add members in the relation menu. Next, I need to select relation 123 in the menu of way 42. Unfortunately, I cannot just type 123 and am done. I need to go through the whole list and figure out which of the description probably is 123. This is problematic if the relation that I am looking for is a right turn and there are several right turn relations in the area. There is no way to figure out which is 123. Being able to refer to entities by ID or at least have entities labeled with their ID would make this task vastly easier.

**Comment by pnorman** [comment]
There's not any real issue deleting a restriction, although it's not ideal, and shouldn't be necessary.

I'm not sure that showing the object ID is the best way to make it clear what is what. Perhaps highlighting an object on the map when it's moused over in the relation editor would be clearer?

**Comment by 1ec5** [comment]
> Perhaps highlighting an object on the map when it's moused over in the relation editor would be clearer?

Yes, I really appreciate that feature in Potlatch 2. (Or was it Potlatch 1?) #3140 basically implements what you’re describing.

As a stopgap, we could also enhance [`utilDisplayName()`](https://github.com/1ec5/iD/blob/fc367e8e93f030823f4ba89293223791e9d12d15/modules/util/util.js#L60) to include the `name`s of the `to` and `from` ways of the restriction relations.

**Comment by bhousel** [comment]
iD has highlighting for relation members now
