### ISSUE TITLE
Invalid preset values for class:bicycle:mtb

### ISSUE THREAD

**Issue by anderfo** [openstreetmap/iD#4221]
Hi,
I heard from another OSM user (and had it confirmed when testing it myself today) that if you edit in iD, whenever you try to find a value for class:bicycle:mtb (probably also other class:bicycle versions), iD suggests to use values such as +3, 0+, 5 or 4. None of these are valid!
The only possible values are -3, -2, -1, 0, 1, 2 or 3. As described on the wiki: https://wiki.openstreetmap.org/wiki/Key:class:bicycle#Values

Please fix the issue.

**Comment by JamesKingdom** [comment]
Currently iD just pulls the values from taginfo, as seen [here](https://taginfo.openstreetmap.org/keys/class%3Abicycle%3Amtb#values).
![tag](http://i.imgur.com/hHxngTr.png)
But I agree that we could have some sort of preset list for this? @bhousel , something like we do for MTB trail difficulty.

**Comment by anderfo** [comment]
Yes, a preset list might help. As it works right now, it makes people believe that the invalid values are valid...

A preset list should be the same for all versions of class:bicycle (i.e. class:bicycle, class:bicycle:mtb, class:bicycle:mtb:technical, class:bicycle:commute, class:bicycle:roadcycling and class:bicycle:trailer).

**Comment by bhousel** [comment]
I don't think iD needs to add fields for all of these `class:` tags.  We already support a bunch of mtb fields, and reading the discussion on the osm wiki for this tag, even people who work on cycle routing do not want mappers using the tag.

The best way to avoid iD suggesting wrong values is to clean them up in OSM.  You can see from the taginfo output that values like +3, 0+, and 5 appear only a few times.  Anyone can use taginfo to open these features in level0 (the link is to the right of the screenshot) and replace them all with better values.
