### ISSUE TITLE
Kosovo border dashed - why?

### ISSUE THREAD

**Issue by MarcKosova** [openstreetmap/iD#4228]
Hello,
I have a problem.
The border between Kosovo and Serbia is dashed, and it´s also not at the right position (but it has already been changed), but it´s still wrong for many months in the editor, does somebody know why?

**Comment by bhousel** [comment]
Can you share a screenshot?

**Comment by MarcKosova** [comment]
![2017-08-11 1](https://user-images.githubusercontent.com/18039652/29230084-ad860582-7ee1-11e7-928b-3211e2c8ee23.png)
![2017-08-11 2](https://user-images.githubusercontent.com/18039652/29230082-ad820ce8-7ee1-11e7-85d0-d300caee01c7.png)
![2017-08-11 3](https://user-images.githubusercontent.com/18039652/29230083-ad835170-7ee1-11e7-8d6c-40f1dcdd7bde.png)
![2017-08-11 4](https://user-images.githubusercontent.com/18039652/29230085-ad87d074-7ee1-11e7-97f6-7b91d634b86c.png)

1. Real border on OSM
2. dashed border in the editor
3. wrong border positions
4. good border positions

**Comment by bhousel** [comment]
Oh I see.. That locator overlay layer that displays at low zooms is not part of the iD project - it is an external layer managed by Mapbox cartography team.  It is updated, but borders are not updated frequently.  I'm told that they are going to do a refresh in the next few months.  Hope this helps!
