### ISSUE TITLE
Please allow a shortcut for applying the last used type to the currently active geometry

### ISSUE THREAD

**Issue by sharazam** [openstreetmap/iD#4229]
Sometimes I want to map a bunch of buildings. Or a bunch of streets with the same classification. It would be very nice to have a keyboard shortcut to apply the last used type to the current geometry.

Currently, I have to draw a building and then click "building" on the sidebar. This isn't a problem if you are just mapping one building, but if you're mapping 50 or 200 buildings, it's incredibly annoying.

**Comment by bhousel** [comment]
Yes, I want this too!  This is captured in #1761 / #590
