### ISSUE TITLE
In save mode, escape should cancel and return to browse mode

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4230]
<kbd>esc</kbd> should cancel out of save mode.

**Comment by oiva** [comment]
Did it work like this at some point? I find myself pressing esc in save dialog pretty often.

**Comment by bhousel** [comment]
> Did it work like this at some point? I find myself pressing esc in save dialog pretty often.

I don't know - I think a long time ago the save screen was a modal popup, and those do have keybinding to cancel on <kbd>esc</kbd>.

Anyway I did just add this and it will be included when #4223 merges.
