### ISSUE TITLE
Unable to tab-navigate to All Relations

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4233]
Since #4159, hitting <kbd>Tab</kbd> does nothing when the last row of All Tags is focused, so it’s impossible to tab-navigate from the All Tags section to the All Relations section.

More broadly, the fix for #4159 surprises me a bit. I thought it’s supposed to be possible to tab-navigate from the webpage content to the address bar, for accessibility reasons.

**Comment by bhousel** [comment]
Which browser are you using?  
Also worth mentioning that we haven't repurposed <kbd>⌘L</kbd> for anything yet, which focuses the location bar in most browsers.

**Comment by bhousel** [comment]
Actually I think this behavior of <kbd>Tab</kbd> creating new tag rows and never leaving the raw tag editor - has been around for a long time, not just since #4159

**Comment by 1ec5** [comment]
> Which browser are you using?

* In Firefox 56.0b2 on the Mac, hitting Tab repeatedly causes the focus to get stuck on the value field in the blank row. Only Shift-Tab moves the focus to the key field.
* In Safari 10.1.2 and Chrome 60.0.3112.90, hitting Tab repeatedly causes the focus to alternate between the key and value fields in the blank row.

Neither behavior is consistent with the rest of iD or with how webpages and Web applications typically work in the browser. For example:

* Focus the search bar and hit Tab: the focus moves to the map.
* Focus the map and hit Tab twice: the focus moves to the location bar.

**Comment by quincylvania** [comment]
@1ec5 Thanks for reporting. Turned out to be an easy fix. Let us know if you find other areas where tabbing could be improved 🗂
