### ISSUE TITLE
Unconnected ways can't be flipped/mirrored

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4237]
I was trying to flip a semicircle in order to create an accurate running track, but because the ways are not connected, it won't let you flip

#### Unconnected

![1](http://i.glideservers.com/u/jam3b5c73c9-211c-4c0e-8b9e-8f3ef38d317a.png)

#### Connected

![2](http://i.glideservers.com/u/jam9cb4c769-1bb1-46d4-b280-91f9980984d3.png)

**Comment by bhousel** [comment]
I relaxed the rules a bit.  The old rules required some of the geometry to be closed areas, but really the math will work if:
- Rotation requires at least 2 unique nodes in selectedIDs
- Reflection requires at least 3 unique nodes in selectedIDs

This means now you can do reflections and rotations on lines and groups of points:
![reflect lines](https://user-images.githubusercontent.com/38784/29428385-0332fdd2-835b-11e7-8386-d7a2be42d928.gif)
![reflect points](https://user-images.githubusercontent.com/38784/29428132-20f30c32-835a-11e7-9105-299fcf1ae149.gif)
