### ISSUE TITLE
Improve handling of full fill area

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4244]
When editing with it enabled, the entire background is filled with whatever area it is in, even if the whole area is not showing. This is bad when editing in residential areas, as the entire screen turns yellow, and anywhere you click selects it.
![1](https://i.glideservers.com/u/jam791bebd8-ca6f-4cf8-958f-a2eadf68c158.jpg)
Maybe this could be fixed by only showing areas that are completely/partially visible in the editor screen, this would also stop iD loading the whole background area, like it does when working in this residential area.

**Comment by bhousel** [comment]
But not showing those large fills is why we have the partial fill option (which is the default).

**Comment by JamesKingdom** [comment]
> But not showing those large fills is why we have the partial fill option (which is the default).

Thinking more about it, I guess that is why this exists, closing.
