### ISSUE TITLE
Update instructions in README

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4246]
Because new versions of `npm` no longer automatically run `prepublish` on `install`, we should 
- [x] update the instructions for running iD in `README.md` to include a `npm run all` step.  
- [x] remove `prepublish` hook from `package.json`

cc @JamesKingdom

**Comment by slhh** [comment]
@bhousel 
Readme.md states Node.js version 4 or newer as a prerequisite. This needs to be updated.
I don't know which version is really required for iD. I had updated my system to the newest version due a failing 4.x.x version.

**Comment by bhousel** [comment]
> Readme.md states Node.js version 4 or newer as a prerequisite. This needs to be updated.
> I don't know which version is really required for iD. I had updated my system to the newest version due a failing 4.x.x version.

That's strange - we actually do matrix builds on travis against node 4, 6, and 8, and they have been succeeding:  https://travis-ci.org/openstreetmap/iD

@slhh if it happens again, can you open a new issue?  Node does occasionally get messed up and a clean reinstall of all dependencies (`rm -rf node_modules` then `npm install`) could fix things.
