### ISSUE TITLE
Don't have phone country codes disappear upon entry

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4247]
The **phone** entry field shows
```
Phone
+886 1 2345 6789
```
but when the user tries to fill it in, the ```+886``` disappears, necessitating the user to type it back in for each place in the whole country.

**Comment by bhousel** [comment]
Ohh this is just how `placeholder` text works in browsers.  It's only displayed as a hint and goes away as soon as the user starts typing.  Even the [html5 spec](https://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#the-placeholder-attribute) says this.   Sorry!

**Comment by jidanni** [comment]
Please use pre-filled text. It is the same for the entire country.

**Comment by jidanni** [comment]
A textbox with the value already filled in which the user can then edit.

**Comment by jidanni** [comment]
https://stackoverflow.com/questions/30516391/html-input-already-filled-in-text
https://www.w3.org/TR/html5/forms.html#attr-input-value
