### ISSUE TITLE
Only clone to depth 1

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4249]
Currently we tell the user to clone the entire repository, which is 141Mb, using --depth=1 reduces this to 28Mb.
From git:
> Create a shallow clone with a history truncated to the specified number of commits

It also only clones the `master` branch, so for people adding new things such as presets, do they really need 36 extra branches that will not be used?

cc @bhousel

**Comment by bhousel** [comment]
I like having the deep history but not everyone needs it.. If you want to add a note about this to the README, that's ok.
