### ISSUE TITLE
 Brunei Map NEED UPDATED VERSION

### ISSUE THREAD

**Issue by akakei** [openstreetmap/iD#4254]
the satellite image of Brunei is very 2005. No new updates, lots of missing places from satellite images which hard for us to add road and etc.

**Comment by bhousel** [comment]
see https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery

iD's list of available background imagery sources come from the [editor-layer-index](https://github.com/osmlab/editor-layer-index)
project.  If you know of a more recent imagery source that is licensed for this use,
please open a request there with the link and license details.
