### ISSUE TITLE
do not show "maxspeed" field on living_street-preset

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#4260]
highway=living_street means that vehicles have to drive very slowly, a walking-speed usually. Mappers should not add a maxspeed-tag to ways with highway=living_street, so I wanted to ask whether it would be possible to remove the "maxspeed" field from the living_street-preset?

**Comment by bhousel** [comment]
sounds good.. @JamesKingdom want to take care of this?

**Comment by maraf24** [comment]
In Poland every living_street has official maxspeed of 20 km/h. So we fill this field with this value. 
That's why I think this field should still be available in living_street preset.

**Comment by bhousel** [comment]
Thanks for the report @maraf24 - I definitely don't have a lot of experience with living streets.  
@Lukas458 are you ok if we put the `maxspeed` field back, since it does seem to be important in some places?

**Comment by pnorman** [comment]
I don't see a reason to not add maxspeed to living_streets in some cases

**Comment by Lukas458** [comment]
Oh, I did not see maraf24's argument until now. Okay, let's put the maxspeed fild back if you wnt to do so.
