### ISSUE TITLE
Allow *:wikipedia and *:wikidata tag auto-suggests

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/iD#4262]
Frequently, the `wikipedia` and `wikidata` tags are incorrect for an object. Per [key:wikipedia wiki page](https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_Wikipedia_links), McDonald's should not have a `wikipedia` or `wikidata` tags, but instead should use `operator:wikipedia`/`operator:wikidata`. Building's architect should be specified with `architect:wikipedia`, etc.

I think iD should automatically handle `*:wikipedia` and `*:wikidata` tags as pairs, allowing templates to specify them when needed.

Thanks!

**Comment by Abbe98** [comment]
Any ideas about a UI for this @nyurik ? Sounds tricky as one would need to enter the tag value before a key prefix can be suggested.

**Comment by nyurik** [comment]
@Abbe98 I agree, and I don't think it should be a wiki-tag specific solution. I think iD should have a generic "issues with this object" interface.  iD editor should highlight any tags that are "suspicious", with an optional "auto-fix" or "select from a list of fixes", and a detailed explanation of why this tag or a tag combination is a suspect, links to the wiki, etc.

A yellow exclamation mark triangle icon, plus showing the whole tag in yellow seems to be appropriate.  Clicking the icon would bring up a popup dialog, with a brief explanation, possibly a few pictures explaining this class of problems, and a list of auto-fix buttons.  The triangle icon may have some asterisks or a drop down arrow next to it to indicate when auto-fixes are available. To keep in sync with JOSM, we would also want a red icon to indicate an error, with the same interface.

Note that some errors/warnings relate to multiple tags or to geometry, so there should also be an icon at the top of the sidebar -- a single warning icon with a count (and possibly another one for errors).  The icon should remain at the top, and not be part of the scrolling area. Clicking it would bring up the same dialog, except that it should combine all of the issues with the object in a scrollable list, possibly hiding the per-issue detailed explanations until expanded. The auto-fixes should be available without expanding details first.

When the object is first clicked, iD may not know if there is a problem yet, so it could show a waiting spinner while it makes QA API calls. A nice green thumbs up icon would be shown if everything is fine.

**Comment by Abbe98** [comment]
Maybe having this UI at the changeset saving dialog? Then iD could have made required HTTP calls in the background on beforehand.

Minimal UI:

List(yellow items with icon) of suggestions of possible improvements at the changeset dialog, that on click brings the user to the edit dialog of the object that the suggestion applies to. 

Auto-fix button could go next to each list item in the future and they could expand to give more hints/provide a link.

More thoughts:

Each "issue detection feature" has registered to be triggered by specific tag keys and/or values and an interface for those "issue detection features" is trigged when new changes are pushed to Local Storage(or when the "Edit feature" dialog closes or changes target).

Each issue or suggestion gets pushed to an JSON array(of objects) in Local Storage and that's used to render the list at the changeset dialog.

**Comment by nyurik** [comment]
Agreed, the changeset saving dialog should also link to problematic objects.  Minimalist UI, IMO, should begin with the tag editor, because that's where users will be able to examine proposed changes, fix more tags, and look at the other objects. I wouldn't want to accept changes in the save dialog, and then be required to go back to the tag editor to actually examine changes in the context of other tags, or to make additional edits.

Registering per key is not very good, because many validations could be per tag combination, or tags+geometry. Performing a full scale object validation on every change is not very expensive, because most of it is done locally, plus any API calls that have the same parameters would be cached. I'm not sure why we would want to store validation results in the local storage - they are transient, and can be done on the fly and kept in the editor state. Full page refresh while editing would simply re-run them on load, possibly making extra validation API calls.  This could actually be good if the problem is in Wikidata - user would go there, fix it, go back, refresh (or click "re-validate"), and use updated values.

P.S. JOSM already has a large collection of validation rules in a CSS-like language. I feel declarative syntax here ends up causing more problems than solving them, but that's a separate discussion.

**Comment by bhousel** [comment]
This sounds hard, but I agree it would be nice to have more wikidata links in places where it makes sense.  

cc @1ec5, as it was something we were talking about recently.

btw @nyurik, I think the more accepted tag for your McDonald's example is `brand:wikidata` not `operator:wikidata`, but who really knows?

**Comment by nyurik** [comment]
@bhousel that's the example at [the OSM wiki](https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_Wikipedia_links) - I agree it might be a bit confusing, and perhaps we should change it.  Deciding these things are a bit hard :)

I wonder if we should rename this task to "Designing iD validation interface", as it seems this is far wider than wikipedia/wikidata.... Or perhaps create a new task with our discussion results as the main topic?

**Comment by bhousel** [comment]
> I wonder if we should rename this task to "Designing iD validation interface", as it seems this is far wider than wikipedia/wikidata....

I don't have the bandwidth to take on an iD validation interface right now.  We'll probably be getting some code for enhanced JOSM-like validation soon.

More broadly, I'd prefer for people to just open issues that say simply "I want to accomplish xxx" or "xxx is broken" - and then let the iD team figure out the most appropriate UI for it.

**Comment by bhousel** [comment]
Closing this issue in favor of more focused discussion on #4382

**Comment by nyurik** [comment]
@bhousel #4382 talks about how to best show Wikidata label, not about suggesting to change `wikidata` to `brand:wikidata` based on the analysis of the Wikidata. They are related, but pursue somewhat different goals.
