### ISSUE TITLE
Make arrow keys move map at same speed as when not editing

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4263]
Hold down a arrow key while editing.
The map inches along at a snails pace.

Please make it the same speed as when not editing (when just plain viewing on osm.org.)

(Why would we be using the arrow keys and not dragging as usual with the mouse?
Because we are doing delicate mouse operations (e.g. adding a way,) and have reached the edge of the screen.)

**Comment by bhousel** [comment]
I already fixed this for you in #4207

**Comment by jidanni** [comment]
Well it's broken again.

**Comment by bhousel** [comment]
It just hasn't been released on osm.org yet.  
Try it on http://preview.ideditor.com/master/ for comparison..

**Comment by jidanni** [comment]
That's much better.
