### ISSUE TITLE
Keep Area etc. button selected

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4264]
The user has fifteen houses to enter.

At some point he notices he has to click "Area" again for each new
house.

He wonders "why can't it just stay in Area entry mode until I click
otherwise? That would save me 14 clicks."

"Yes, I am digitizing 15 individual houses, but at least there should be
some way I can make the Area button stay pressed or whatever."

See comment 2 (which there is no way to link to) on
https://help.openstreetmap.org/questions/58785/id-editor-creating-multiple-points-ways-areas-without-having-to-click-area-etc-again-before-each-one

**Comment by jidanni** [comment]
(Yes we can copy houses with CTRL+C CTRL+V, but then we have to adjust their shapes from the last house. etc... Usually more work than starting fresh unless all houses are the same size.)

**Comment by bhousel** [comment]
We've discussed this.
