### ISSUE TITLE
A storage tank is not a building, so do not include a building=yes tag

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4265]
On https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dstorage_tank it says
```
A storage tank is not a building, so do not include a building=yes tag.
```
In ID, when adding a point, there is no problem.
But when adding an area, you slap the building=yes tag on!

**Comment by bhousel** [comment]
For years, the wiki said to add the `building=yes` tag, and so that's why the storage tank preset does this.

You should blame whoever it was who changed the wiki, not us.

**Comment by matkoniecz** [comment]
See https://wiki.openstreetmap.org/wiki/Talk:Tag:man_made%3Dstorage_tank#building.3Dyes_.3F for discussion on wiki.

**Comment by bhousel** [comment]
> Bryan Housel is simply wrong. Because there was (and still is) no rendering for years, people felt commited to add building=yes.

We're going to disagree sometimes on OSM tagging stuff.  That's ok.  

OSM evolves over time.  These days I consider `building` as "any structure with a height that should render on a 3D map".  This convention has been established for years on the OSM wiki and in software, so lots of things in OSM are now mapped as "buildings" that a layperson would not consider as buildings (like suspension bridge towers, silos, gasometers, storage tanks, gazebos).  

This is fine.  Similarly, nobody would consider a dirt footpath as a "highway", but anyway that is the tag and people accept it.  To be pedantic, `building` should really be renamed `structure`, but we don't have a way to rename tags in OSM at that scale.

Look at it this way too: if you wanted to detail map a storage tank in 3D, you'd probably use `building:part`, not `storage_tank:part`.

**Comment by Lee-Carre** [comment]
StreetComplete, for its building type quest, offers / accepts storage tank as an answer.

If I recall, there's a `building` tag value specifically for storage tanks, too.

**Comment by matkoniecz** [comment]
> StreetComplete, for its building type quest, offers / accepts storage tank as an answer.

Though they are not tagged as buildings if I remember right.
