### ISSUE TITLE
User cannot put point back where it was

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4266]
While adding a nearby feature, user accidentally moves a mountain peak
https://www.openstreetmap.org/node/2375998394/history

(He clicked the peak in order to copy some details, and then
accidentally also moved it a little.)

User needs to put the mountain peak back to
Location: 24.2905333, 120.8208167
before anybody finds out.

Alas in ID, one can search for
24.2905333, 120.8208167
and indeed there somewhere in the middle of the map, there is that
point.

But that won't help the user very much, even with a steady hand, to put
it back in that exact spot.

One might say well yes, ID is not listed on
https://wiki.openstreetmap.org/wiki/Change_rollback .

And he doesn't want to rollback an entire changeset. He just wants to
make version 3 of the point... matching version 1.

Anyway without the critical ability to put points at exact locations (#4197),
one will need more than ID to fix the problem that happened in ID.

**Comment by bhousel** [comment]
We've discussed this.
