### ISSUE TITLE
stale description url

### ISSUE THREAD

**Issue by jgravois** [openstreetmap/iD#4267]
not pressing, but it'd be sweet if someone with admin keys to the repo could update the url in the description header when they have a minute.

![screenshot 2017-08-24 12 55 36](https://user-images.githubusercontent.com/3011734/29685838-8e8011ac-88cb-11e7-8f65-852fc8fa6edb.png)
 
> becomes: http://www.openstreetmap.org/edit?editor=id

**Comment by bhousel** [comment]
Good suggestion - I just made the change.
