### ISSUE TITLE
More accessible colors

### ISSUE THREAD

**Issue by checkerap** [openstreetmap/iD#4270]
I have bad eyesight when it comes to colors and the editor UI lacks contrast in the texts.

I had to call someone to help me add a point as I couldn't use the UI.

Any plans to improve this? Or have another theme/toggle?

**Comment by bhousel** [comment]
Check out #3421 and #3095 - these issues have some info on how to use the Stylish browser extension to override the colors in iD.  The examples show changing the map style, but this would work for changing text colors also.

TODO:
- [ ] We should probably add some documentation about this to the FAQ.

**Comment by Nick-Tallguy** [comment]
http://learnosm.org/en/hot-tips/enhance/ may assist a little.

**Comment by pnorman** [comment]
> I have bad eyesight when it comes to colors and the editor UI lacks contrast in the texts.

Any in particular? I'd expect contrast problems in the rendered map because lots of features are being placed on a colourful background, but we should make sure the rest of the UI is usable by everyone.

**Comment by checkerap** [comment]
That and the sidepanel with the form/properties. At least to me, having a dark background / light text is way better that a light background. I'll have a look at the suggested enhance tip.
