### ISSUE TITLE
Add preset for landcover=trees

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#4272]
landcover=trees is used to mark the presence of trees. It does not imply the use nor origin of the trees.

The tag is distinct from landuse=forest (Managed forest or woodland plantation) and also distinct from geographical features as described with natural=wood (Natural primeval woodland)

https://wiki.openstreetmap.org/wiki/Tag:landcover%3Dtrees

https://wiki.openstreetmap.org/wiki/Forest (See Approach 5)

**Comment by bhousel** [comment]
We do already have a preset for [`natural=wood`](https://taginfo.openstreetmap.org/tags/natural=wood)

[`landcover=trees`](https://taginfo.openstreetmap.org/tags/landcover=trees) seems redundant, and not really used very much.

I kind of think we should just stick to the one that is already most widely accepted, but happy to hear other opinions.

**Comment by ignaciolep** [comment]
The need to have the landcover=trees preset arose because we detected mappings of tree groups within urban areas. These were mapped as mini woods (natural = wood) when they are not.

In that case the community decided to change the tag to landcover=trees, since the definition on the wiki is the one that best fits the reality even though the render does not support it. (See https://www.openstreetmap.org/changeset/51432496)

Anyway I understand your point, maybe the best would be to map these areas as gardens and each tree individually (natural=tree), but what is certain is that natural=wood is not right in this case.

**Comment by bhousel** [comment]
I guess we could just add a `landcover=trees` tag to the existing `natural=wood` and `landuse=forestry` presets.  There's no harm in that right?

**Comment by JamesKingdom** [comment]
> I guess we could just add a landcover=trees tag to the existing natural=wood and landuse=forest presets. 

I don't think this is a good idea, `landcover=trees` is (as I see it) used to map small areas of trees that are _not_ forests or woods, as said before:
>The tag is distinct from landuse=forest (Managed forest or woodland plantation) and also distinct from geographical features as described with natural=wood (Natural primeval woodland)

I think we should have this as a separate preset.

**Comment by slhh** [comment]
According to taginfo landcover=trees is mainly used in combination with natural wood or landuse=forest, but landcover=trees is essentially redundant in this case. Data consumers can imply a landcover=trees in a forest or wood anyway, where no other landcover is tagged.

A forest might contain areas where landcover=trees is wrong, e.g. a cutline. Therefore we must not add landcover=trees to every forest.

The real intention of the landcover=trees tag is a separate use for an area of trees outside a wood or forest, even if this use isn't the most frequent one. This needs a separate preset, but the forest or wood presets need to get priority in case of the combined use. E.g. a forest covered with trees is still a forest and not just a area of trees.

**Comment by bhousel** [comment]
Here is why I don't really want to add this tag as a new preset:

tag | uses
--- | ---
https://taginfo.openstreetmap.org/tags/natural=wood  | 4,346,557 uses
https://taginfo.openstreetmap.org/tags/landuse=forest | 3,306,152 uses
https://taginfo.openstreetmap.org/tags/landcover=trees | 11,128 uses

`natural=wood` is used, in practice, for all kinds of tree cover, (not just "primeval woodland" - why do people think this?).  I see it used pretty frequently for small groups of trees even in urban areas.
`landuse=forest` is also used, in practice, for all kinds of tree cover, but preferring towards places where the trees are managed by forestry.

I just don't see how the new `landcover` tags solve any problem not already handled by the `natural` tags.

**Comment by ignaciolep** [comment]
I think you are right @bhousel, landcover=trees is too generic and on the other hand natural=wood is used as a de facto for all kinds of tree covers.

**Comment by pnorman** [comment]
> I kind of think we should just stick to the one that is already most widely accepted, but happy to hear other opinions.

👍
