### ISSUE TITLE
Broken relative links to source in wiki

### ISSUE THREAD

**Issue by leegenes** [openstreetmap/iD#4274]
Current relative links to contributing guidelines, license, etc. are routed to create new wiki page. Relative path should have `../../blob/master/` preceding path.

ex.
`[CONTRIBUTING.md](CONTRIBUTING.md)` should be `[CONTRIBUTING.md](../../blob/master/CONTRIBUTING.md)`

Happy to make the change. Created issue to 2x check as first time contributor to iD, and any variation from source contributions.

**Comment by bhousel** [comment]
@JamesKingdom can you fix this?   It looks like the landing page for the project wiki is just a copy of the README.md.  Probably we should just link to the readme instead of maintaining a copy in 2 places.

**Comment by JamesKingdom** [comment]
The wiki is currently very developmental, I'm working on it in small bits but don't have much time at the moment.
Thanks for the info nonetheless, I will change it now.

**Comment by JamesKingdom** [comment]
I have updated it with a more appropriate message.
