### ISSUE TITLE
Missing preset for vending=feminine_hygiene

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#4275]
While there are currently 0 uses of the value in OSM, this may be a catch 22 situation that without a preset how to map such a facility is difficult to discover.

See http://wiki.openstreetmap.org/wiki/Tag:vending%3Dfeminine_hygiene

**Comment by bhousel** [comment]
I'm definitely 👍 on adding presets for things like this that are real world things that people want mapped, even if they have low usage.

**Comment by JamesKingdom** [comment]
Closed in #4331
