### ISSUE TITLE
zoomToEntity fails when selecting a relation from the search results

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4276]
<img width="250" alt="screenshot 2017-08-25 11 49 44" src="https://user-images.githubusercontent.com/38784/29721531-91e2c716-898b-11e7-897f-2609133df4c8.png">

### What is supposed to happen:  
You click on Philadelphia in the geocoder search results and the map moves to someplace around Philadelphia.

### What happens:
The map doesn't actually go anywhere.

### Why:
We fetch the Philadelphia relation from the OSM API using this `zoomToEntity` function:

https://github.com/openstreetmap/iD/blob/c0d224b7d4096353f38ef2a0288def2449e849ef/modules/core/context.js#L118-L126

It fetches the relation, _but not the members_, and so when `map.zoomTo()` tries to calculate an extent, it can't actually do this, and just returns without moving the map anywhere:

https://github.com/openstreetmap/iD/blob/c0d224b7d4096353f38ef2a0288def2449e849ef/modules/renderer/map.js#L650-L652

Interestingly, if you try these steps a second time, iD will actually go to Philadelphia because somehow some of its relation members got loaded.  I'm curious about how/where that happens, because it's not something I expected.

**Comment by willemarcel** [comment]
I couldn't reproduce with nodes, but this happens with ways that aren't part of relations.

**Comment by JamesKingdom** [comment]
The sidebar also opens and is buggy if you go direct to a relation from a url, here's an [example](https://osm.org/edit?editor=id&relation=21791).

You are left at zoom 2 at `0,0`, and if anything updates, the sidebar closes and changes to `Zoom in to edit`

**Comment by Zverik** [comment]
Heard a complaint about this from a fellow mapper. A test case: www.openstreetmap.org/edit?way=26233048 should zoom to way, but currently it shows the whole world. I understand this is not easy fixable and not of priority, but still it would be nice to have.

**Comment by 1ec5** [comment]
The same thing happens if you search for a way or node ID, like `w26233048`. As in the original post, iD zooms and pans correctly the second time you search for that ID and select the result.

**Comment by bhousel** [comment]
Looking at it more, the issue is probably this block of code.  

We can delay fetching and parsing the tiles, but we shouldn't delay `history.merge`.  The code below will call the `loadTiles` and `loadEntity` callbacks before those entities are actually merged into the graph.   This is almost certainly causing a bunch of random issues, including the intermittent history restore and conflict resolution bugs some people are reporting.

https://github.com/openstreetmap/iD/blob/9fa078b4b921a04ba6dfced8c431b198b4404d0e/modules/core/context.js#L114-L144

**Comment by Zverik** [comment]
It works! Thank you, Bryan!
