### ISSUE TITLE
Esri World Imagery vintage

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4280]
We can probably fetch imagery vintage for the Esri World Imagery layer, similar to how we can get it for Bing.  

details here: https://www.arcgis.com/home/item.html?id=c03a526d94704bfb839445e80de95495

**Comment by jgravois** [comment]
source/vintage is absolutely be queried and i'm happy to help land it as a feature in iD. 

given that it'd invoke a new web request, my first instinct is to add a context menu item in the background settings panel when the Esri imagery is active.

**Comment by bhousel** [comment]
Thanks @jgravois!  
The way I would approach this would be similar to how we fetch the Bing imagery vintage.

`rendererBackgroundSource.Bing` is special and it extends the generic `rendererBackgroundSource`, see here: https://github.com/openstreetmap/iD/blob/master/modules/renderer/background_source.js#L150

* So in that same file, you could make a `renderBackgroundSource.Esri` that is like the Bing one, but only has a single `getVintage` method.

* Then you'll need to update the `init()` code here:
https://github.com/openstreetmap/iD/blob/28b5eff7a2023254bfcb176e61241ff79935fd8a/modules/renderer/background.js#L244-L248

add something like this:
```js
  } else if (source.id === 'EsriWorldImagery') {
      return rendererBackgroundSource.Esri(source);
  }
```

**Comment by bhousel** [comment]
@jgravois I got this started for you in 1c9719d, while fixing #4327

**Comment by bhousel** [comment]
BTW to test this, just hit <kbd>⌘Cmd+Shift+B</kbd> (on Mac) / <kbd>Ctrl+Shift+B</kbd> (on Windows) to bring up the Background info pane.  This pane will display the vintage of the center tile, and there will be a button to toggle tile debugging info, to display vintage on all the tiles.  

This feature is toggleable and off by default, so it won't flood the server with requests.
