### ISSUE TITLE
Saving while zoomed out makes text overlap

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4286]
This is similar to #4184 , but instead when you try to save.

If you zoom out past Z16, so it says `Zoom in to edit`, then proceed to click `save`, the same problem happens:
![1](https://i.glideservers.com/u/jamf86e5b51-148e-404c-8379-1fd2db1c3a61.png)

**Comment by bhousel** [comment]
This was also fixed by #4279
