### ISSUE TITLE
Switching server while loading causes glitchy behavior 

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4288]
![ezgif com-optimize](https://user-images.githubusercontent.com/11473673/29753874-2781232a-8b72-11e7-88d3-19fcaa765c9e.gif)

Loading somewhere on the `live` server then switching to `dev` half way through causes the loaded data to remain and cause glitchy movement

**Comment by bhousel** [comment]
Good find @JamesKingdom - we have to cancel those async callbacks when the connection changes. 😢

**Comment by bhousel** [comment]
I added a bunch of code in 9b705a6 to avoid calling the OSM API callbacks after a connection reset or switch.

This _mostly_ works, but there are still issues if you switch from "live" -> "dev" -> "live" _very_ quickly.  

This means there is still some state being stored somewhere and referenced from a deferred call.  My suspicion is that this is in `map.js`.  I think we need to add a proper `Map.reset()` method, to _really_ throw out all the state and cancel all deferred work.   But it's good enough for now.
