### ISSUE TITLE
Hashtag detected in URL in changeset comment

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4289]
While I was composing [a changeset comment](http://www.openstreetmap.org/changeset/51492414) that refers to [this section of a wiki page](https://wiki.openstreetmap.org/wiki/Ohio/Map_features#ref), with the URL `https://wiki.openstreetmap.org/wiki/Ohio/Map_features#ref`, the Hashtag field appeared saying that the changeset had been tagged with `#ref`.

<img width="394" alt="hashtag ref" src="https://user-images.githubusercontent.com/1231218/29753908-aa34a000-8b2f-11e7-8144-bc64b8ee5b02.png">

Seen in version 2.4.1.

**Comment by 1ec5** [comment]
iD didn’t permit me to delete the `#ref` hashtag by clicking the ✖️. The changeset ended up getting tagged with `hashtags=#ref`.

**Comment by bhousel** [comment]
> iD didn’t permit me to delete the #ref hashtag by clicking the ✖️

Yeah, this is kind of annoying - as soon as you delete it, the code plucks it out of the comment and restores it.  I think in most cases that's fine, but you're right that it shouldn't have been detected in the first place.
