### ISSUE TITLE
oneway=reversible is displayed with oneway=yes direction arrows

### ISSUE THREAD

**Issue by artischocke** [openstreetmap/iD#4291]
![image](https://user-images.githubusercontent.com/19168045/29763580-07132ee6-8bd4-11e7-9c2c-f91cf08491fe.png)

The [I-595 Express Lanes](https://en.wikipedia.org/wiki/Interstate_595_(Florida)#Express_lanes) in Ft. Lauderdale change direction depending on the time of day, and are therefore tagged with [`oneway=reversible`](https://wiki.openstreetmap.org/wiki/Tag:oneway%3Dreversible). I'd expect these ways to be displayed with no direction arrows (or, if anything, arrows in both directions perhaps), but they're displayed with one-way arrows instead.

E.g. https://www.openstreetmap.org/way/332703663

**Edit:** it would probably make sense to apply the same rendering to [`oneway=alternating`](https://wiki.openstreetmap.org/wiki/Tag:oneway%3Dalternating) as well

**Comment by boothym** [comment]
> if anything, arrows in both directions perhaps
That sounds like a good idea, though perhaps with smaller arrows

**Comment by artischocke** [comment]
Whatever the rendering, perhaps it would be a good time to add support for  [`oneway=alternating`](https://wiki.openstreetmap.org/wiki/Tag:oneway%3Dalternating) as well by applying the same rendering.

**Comment by bhousel** [comment]
I did this today.. We'll now render `oneway=alternating` and `oneway=reversible` with dual arrowheads, and added those extra options to cycle through when using the oneway checkbox:

![reversible oneways](https://user-images.githubusercontent.com/38784/34579106-9e80b4f6-f155-11e7-87e9-6017dc301342.gif)

(I know it is weird to cycle through more options than yes/no on a checkbox, but whatever, it already had 3 states)

**Comment by bhousel** [comment]
I also changed the checkbox field to display non-standard values (other than 'yes'/'no') in the field label.  These are hopefully rare but obviously anything can happen in OSM.

### Before:
The box would render as unchecked.
<img width="500" alt="screenshot 2018-01-04 13 49 45" src="https://user-images.githubusercontent.com/38784/34579304-6849c778-f156-11e7-9a1a-1372ecef4555.png">

### After:
The box is checked and the "value" appears in quotes.
<img width="500" alt="screenshot 2018-01-04 13 48 58" src="https://user-images.githubusercontent.com/38784/34579311-721ef8f4-f156-11e7-8f5e-eb09e3d99058.png">

**Comment by iandees** [comment]
https://www.urbandictionary.com/define.php?term=lit
