### ISSUE TITLE
Hide administrative boundaries by default

### ISSUE THREAD

**Issue by artischocke** [openstreetmap/iD#4292]
Even though I understand why something like #2014 wasn't and won't be implemented, I would like to propose that the administrative boundary layer be hidden by default rather on the basis of its  **usefulness** as a feature in the overall context of the editor. I understand the arguments underpinning the decisions to close such tickets, but in practice 99% of the times I use iD, administrative boundaries just get in the way of my editing experience, and I can't imagine that if I were to, wanted to or had to work with admin boundaries, iD would be my editor choice.

What I do see quite often are roads intersecting admin boundaries because the editor gladly snaps the two together. In fact, given the "magnetic" way in which iD makes this happen, as a new user, I would think that they _want_ to be snapped together and, more importantly, that they _ought_ to be snapped together since it doesn't distinguish boundaries to highways when doing so.

Where the boundary is over a road (as is often the case in the US and I would imagine elsewhere), I often run into users using the unglue tool _on the whole way_, which results in long stretches of important (i.e. primary, secondary or tertiary) roads being disconnected entirely from the network (and fixing them in iD is a nightmare _precisely_ because of the presence of the admin boundary at the same location as the road in combination with the snapping functionality).

Clearly admin boundaries _underlie_ any highway or feature layer, but as no such concept exists in the editor, I think it best to disable the layer on the basis that it's **seldom useful** to have it on in iD. It can always be turned on, because yes, no such restriction should exist for users, new or old.

PS: By _hidden_ I mean, more specifically, that the _Boundaries_ checkbox be unchecked by default under Map Data > Map Features. If you want it on all the time, the editor could remember your choice for your next visit.

I can also see this being useful for census polygons in the US.

**Comment by bhousel** [comment]
We discussed in #2942, and at the time there wasn't enough interest to actually change what iD does, but I'm open to hiding the admin boundaries if that's what people prefer.

**Comment by bhousel** [comment]
I did this

**Comment by JamesKingdom** [comment]
> I did this

This is great, but now the text is wrong when disabled:
![](https://i.glideservers.com/u/jam23d606f6-285c-468b-97be-cb81fc5552d4.png)

**Comment by bhousel** [comment]
That screenshot is what it shows when the map is zoomed out (zoom < 16).  
Can you check on http://preview.ideditor.com/master/ and see how it looks at both low and high zoom?  
It should work like before, but with "Boundaries" unchecked by default until the user checks the box.

**Comment by JamesKingdom** [comment]
Sorry, this was the wrong issue, I was talking about https://github.com/openstreetmap/iD/commit/5a8709bc67c7b9e8db9b2b39bf94f6b78634efa6

We should have it say something different when the `OpenStreetMap data` box is unticked.

**Comment by bhousel** [comment]
It says this now: 
<img width="250" alt="screenshot 2017-09-19 17 08 11" src="https://user-images.githubusercontent.com/38784/30615561-477a61da-9d5d-11e7-9ab3-964c00cdf3e6.png">
