### ISSUE TITLE
The map on the iMac Retina 4K is not clear

### ISSUE THREAD

**Issue by hdd064** [openstreetmap/iD#4294]
The map on the iMac Retina 4K is not clear
<img width="2048" alt="screen shot 2017-08-29 at 9 32 18 am" src="https://user-images.githubusercontent.com/1020603/29805270-07905ee6-8c9e-11e7-9a2d-cf03b23c1a0f.png">

**Comment by JamesKingdom** [comment]
Does this happen when you are editing the map, or only viewing?
We only control the editor, and problems with the base map should be reported [here](https://github.com/openstreetmap/openstreetmap-website/issues)

**Comment by hdd064** [comment]
Just when viewing the map
I report the problem on that link
Thank you
