### ISSUE TITLE
Is "unit" really part of address in 21 countries

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4302]
Currently the "standard" address fields for 21 countries ("ad", "ba", "be", "cz", "dk", "es", "fi", "gr", "hr", "is", "it", "li", "nl", "no", "pl", "pt", "se", "si", "sk", "sm", "va") are "unit", "street", "housenumber" on first line and ["postcode", "city"] on second line. The three german speaking countries Austria, Germany and Switzerland have removed "unit" in PR #4301 . Is unit really appropriate for the remaining 21 countries?

**Comment by jjiglesiasg** [comment]
I will loved to have State instead of unit as part of the address

**Comment by JamesKingdom** [comment]
> I will loved to have State instead of unit as part of the address

But this would still be incorrect, here's `addr:state`.
![](https://i.glideservers.com/u/jam2291d5b6-8ee0-4ccf-9659-2ce929023e3f.png)

I will check over more countries with taginfo and update the addressing

**Comment by slhh** [comment]
@JamesKingdom 
The taginfo map doesn't really indicate where addr:steet is useful. E.g. it looks like it were useful in the German speaking countries according to the map, but it isn't. These countries do have states, but the state is not part of an address there. A very small fraction of addresses are tagged with addr:state by mistake, because the state exists. Due to the huge amount of tagged addresses in these countries, the small fraction of errors is sufficient to make the taginfo map red.

**Comment by jjiglesiasg** [comment]
In the Western Continent (Americas) all countries have some sort of Federal government, whatsoever the name Could be State, Departamento, Provincia o Region, basically encompasses the second administrative level below the National Country Government, Equivalent to “STATE”

 

I am not really sure of the data depicted in red, but I have travelled all Americas and with the exception of Canada, the State were the Address is located is an integral part of any “Address” as such, however some countries like Brazil do not named the whole “State” but a Code of normally 2 letter like SP: For Sao Paulo State or MG: For Minas Gerais; Chile instead do not have States as Such but they call them Regions, Venezuela and Argentina have States and Colombia and Bolivia have “Departments” in all cases the equivalent Government and Address indications is related to “State” level.

 

Thanks

 

JJ

**Comment by bhousel** [comment]
If you want the address field changed, please submit a PR.  I don't have the bandwidth to track down how it should look in all the different parts of the world.

This Wikipedia page lists them, and it looks like at least several European countries do have some notion of sub-building addressing (floor, apartment, unit, etc): 
 https://en.wikipedia.org/wiki/Address_(geography)#Format_by_country
