### ISSUE TITLE
detection of comma separated hashtags in changeset comment

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#4303]
The automatically detected hashtags from a comma separated list of hashtags in a changeset comment (as set by default in some tasking manager jobs) get kind of duplicated (once without the comma and once with the comma), as in this example: http://www.openstreetmap.org/changeset/51493981 (note that both `#nepal,` and `#nepal` are present in the hashtags field of the changeset).

I think punctuation should not be part of a hashtag string.

**Comment by bhousel** [comment]
I agree, thanks for the report @tyrasd  👍
