### ISSUE TITLE
automatically filled out hashtags shouldn't be cached

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#4304]
Here's what I see as potentially confusing: When a user loads iD from an external page that initializes the chanset comment with some text that includes some hashtags, these are also set in the new hashtags list (and `hashtags` field of the osm changeset). These hashtags are kept in the browser's cache just like manually entered hashtags. If a user is not aware about what hashtags are, they could continue to commit other changes with these hashtags, even though these hashtags likely don't apply anymore. A similar case is when a user opens jobs from multiple HOT tasking manager projects, without thinking about cleaning up the hashtags list when changing from one HOT project to another one. Here's an example, where the hashtags includes multiple `#hotosm-project-` ids, even though it obviously should only belong to one: http://www.openstreetmap.org/changeset/51495572

I think automatically parsed hashtags shouldn't be persisted/cached. Additionaly, if iD is opened with an external changeset-comment "template", and if that one includes any hashtags, the existing cached hashtags should probably be cleared (because it would be easy to overlook any existing hashtags that likely not fit the current task anymore in a longish list of automatically filled out list of hashtags).

**Comment by bhousel** [comment]
> I think automatically parsed hashtags shouldn't be persisted/cached. Additionaly, if iD is opened with an external changeset-comment "template", and if that one includes any hashtags, the existing cached hashtags should probably be cleared

I agree, this was something I wasn't too sure about when I implemented the feature - so I just made it work like the existing comments field - then added the automatic parsing later, which I realize now can conflict with the cached ones.
