### ISSUE TITLE
Edit multiple ways/nodes/areas

### ISSUE THREAD

**Issue by rebio** [openstreetmap/iD#4305]
I searched for a solution in the help files and documentation, but I didn't find anything - if I missed something please let me know.

When you want to assign a tag to eg. multiple nodes or ways it's a huge hassle right now.

Let's say you have 15 ways and you want to add maxspeed=50 and source:maxspeed=XX:urban. You can not select all 15 ways and add both tags to all ways in one go. You have to edit them one after the other and go through them one by one.
This is one of the major things why I dislike ID and only use it for minor edits with like 5-10 changes.

**Comment by JamesKingdom** [comment]
This is already open in #1761, and is something we hope to be implement soon!
