### ISSUE TITLE
Moving the new unit field below

### ISSUE THREAD

**Issue by egofree71** [openstreetmap/iD#4306]
Hello,

In the address, there is the new unit field . My problem is that now the street field, which is on the same row, is shorter. When i have to select the street name for a given address, often i see only the first letters. When there are several streets nearby, now it's a little bit more confusing to select the right street. Here is my proposal : what about putting the unit field on the second row, to the left of the address code ? As the city name in general is shorter than the street name, it should not be a problem if the city field would be shorter.

Update : another solution would be to have a drop down box where all items in the list are displayed fully when the user clicks on the arrow.

**Comment by bhousel** [comment]
Sure, this can be changed easily in [`address-formats.json`](https://github.com/openstreetmap/iD/blob/master/data/address-formats.json).  Please submit a PR to change it to however addresses are commonly written in your country.
