### ISSUE TITLE
Do not switch line selection when clicking on an attached node

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4307]
When you have a line selected and click on its attached node, the node of the other line gets selected although you expect it to be the node of the former line.

**Comment by bhousel** [comment]
Not sure what you mean by this - can you share an animation made with licecap?  or a screenshot with some annotations on it to say where you clicked and what you expected to happen?

Clicking on a node should just select the node, if I'm understanding what you mean.  It might also dimly highlight a related parent line, but that is only used for keyboard vertex navigation.

**Comment by yaugenka** [comment]
Here is a recording https://youtu.be/WbumFNSQYw0
This is expecially unconfortable when you are deleting nodes from a line with a shotcut key, get to an attached node, unattach it with a shotcut key and cannot proceed with deletion because the focus got changed. See this recording https://youtu.be/pEaQFa2Wrec

**Comment by bhousel** [comment]
Thanks @yaugenka, I understand now - yes I agree that this is very annoying.. We're tracking this on issue #2206
