### ISSUE TITLE
Wrong mapping of footbridges

### ISSUE THREAD

**Issue by GerdP** [openstreetmap/iD#4309]
It seems that ID is somehow misleading mappers to use a way with highway=crossing + traffic_calming=table for a footbridge.
I've seen several places where different mappers have added new ways like this or changed
existing correct tagging. I am not familiar with ID, so I have no idea why.
See also https://forum.openstreetmap.org/viewtopic.php?id=59608

**Comment by JamesKingdom** [comment]
It seems to happen with `Raised Pedestrian Crossing`:
![](https://i.glideservers.com/u/jam0f494930-bd13-41b1-97e0-2a0e0a34fd73.png)

This should be used on highways to map a _slightly_ raised section that is designated for pedestrians to cross, but the use case on [w518945321](https://www.openstreetmap.org/way/518945321), is incorrect. They have mistaken this for a bridge, but it is easy to see why, the name is pretty generic. 
Maybe we should consider naming it differently.

**Comment by GerdP** [comment]
The tag highway=crossing should only be used on nodes. The tag traffic_calming=table might be used on ways but I think it makes more sense when it is used on a node together with highway=crossing.

**Comment by bhousel** [comment]
It looks like iD's use of the preset matches up with current use of the tag and documentation on the OSM wiki.  If you find that users are confused, this is normal, and the right thing to do is send them a nice message on a changeset discussion to help them out, and to fix the tag according to how mapping is done in your part of the world.

**Comment by GerdP** [comment]
What tag do you mean? If ID encourages the user to use the tag highway=crossing on a way this is simply wrong.

**Comment by GerdP** [comment]
Please check also this CS diskussion:
http://www.openstreetmap.org/changeset/51182181

**Comment by bhousel** [comment]
> What tag do you mean? If ID encourages the user to use the tag highway=crossing on a way this is simply wrong.

Oh I see now, sorry.. there is an issue in here:  https://github.com/openstreetmap/iD/blob/master/data/presets/presets/traffic_calming/table.json#L17

We should probably just turn that into a single feature that's a combination of zebra crossing and traffic calming.

**Comment by GerdP** [comment]
My current understanding is that you can use trafifc_calming=table in two very different situations
1) as a node that is shared by a highway=footway way and another highway=* way which describes a road used by 4 wheel vehicles. In this situation the node should always be tagged as highway=crossing,
no matter if there is a traffic_calming
2) On a way . I am not sure what it should describe in this case, but when I see a highway=* with traffic_calming=* I assume that there is at least one such traffic_calming on this part of the road.
I would not encourage this usage with a preset.

So, I suggest to change the preset so that it is only used for nodes. If possible, only for nodes shared by a footway and another more important highway..

**Comment by GerdP** [comment]
Sorry, I've just noted that I added another comment in the forum instead of here:
https://forum.openstreetmap.org/viewtopic.php?pid=662265#p662265

**Comment by bhousel** [comment]
I did the following:
* Added presets for raised crossing and raised crosswalk, same as the existing
  crossing and crosswalk presets but with `traffic_calming=table` added
* Retained a generic `traffic_calming=table` preset without crossing tags,
  and for usage on vertex geometry only (removed line, which caused the issue)

**Comment by GerdP** [comment]
Thanks, I don't understand all changes, but what I understood looks promising ;-)
