### ISSUE TITLE
Phone number pattern for Benin and Ivory Coast

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#4313]
Currently, there is no phone number pattern in iD for Benin and Ivory Coast.

The E.123 format (what OpenStreetMap wiki asks for) is:

- for Ivory Coast: +225 ab uvwxyz
- for Benin: +229 ab uvwxyz

“ab” is the area code.

But in real-world life the phone numbers are _always_ structured by groups of two digits:
- for Ivory Coast: +225 ab uv wx yz
- for Benin: +229 ab uv wx yz

I would propose something like
- for Ivory Coast: +225 20 12 34 56
- for Benin: +229 20 12 34 56

(20 is in both countries a landline code.)

**Comment by bhousel** [comment]
Thanks for the info!  This is a great task for someone getting started to add those formats to [`phone-formats.json`](https://github.com/openstreetmap/iD/blob/master/data/phone-formats.json).

**Comment by manfredbrandl** [comment]
Already solved in PR #4314 .

**Comment by bhousel** [comment]
> Already solved in PR #4314 .

Thanks @manfredbrandl!  Sorry I didn't see that, first day back from vacation....

**Comment by sommerluk** [comment]
Thanks!
