### ISSUE TITLE
pedestrian crossing preset

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#4316]
iD adds the crossing=zebra tag when you select pedestrian crossing, but this is an undocumented tag. The documented tag (with double and longer standing usage) is crossing=uncontrolled. See this graph for reference.

![taghistory_crossing](https://user-images.githubusercontent.com/581288/30152517-a272b17c-93b3-11e7-93c9-3be29980ae7d.png)

Please fix it by changing the preset.

**Comment by bhousel** [comment]
This comes up for discussion so frequently we should really make a tagging FAQ.

please see #3244, #2918, #3049

The tag is (was?) documented, and we picked the best tag for marked pedestrian crossings that was available at the time.  

Also, zebra crossings are control devices, so calling them uncontrolled is not correct.

**Comment by dieterdreist** [comment]
I believe this comes up so frequently because there is an issue. The preset is contradicting the OSM wiki unless you live in the UK. [See here in the OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:crossing).
It says for **crossing=uncontrolled**: _A generic crossing with no traffic-signals of any type, just road markings. e.g. Zebra-crossings; Generally referred to as a "crosswalk" in the US). _

For **crossing=unmarked** _A crossing without road markings or traffic lights_

The only mention of crossing=zebra is as "UK Shortcut" for highway=crossing +
crossing=uncontrolled + crossing_ref=zebra

**Comment by bhousel** [comment]
> It says for crossing=uncontrolled A generic crossing with no traffic-signals of any type, just road markings. e.g. Zebra-crossings; Generally referred to as a "crosswalk" in the US)

Ugh, yeah that's wrong - can you change it?

> I have also checked the wiki history. The current definition is long standing, see July 17th 2008

Yeah, long standing mistakes are the worst kind 😞

**Comment by dieterdreist** [comment]
Personally, I am not against crossing=zebra, because requiring 3 tags to define something as simple as a zebra crossing seems overengineered. But the wiki has it this way for almost 10 years and people are used to it. Rather than creating facts through the backdoor by using presets in contrast to the documentation in the front page editor there should be a discussion and an agreement to switch to a more succint tag.

**Comment by dieterdreist** [comment]
IMHO, as a developer of one of the most used and promoted editors, you have to take great care not abusing the powers that come with the leverage of deciding on the presets in use. In this case it is very clear that crossing=zebra came to widespread use [when you added it as a preset in May 2014](https://github.com/openstreetmap/iD/commit/1f2420e5994c22c6c1fa0a5c006dbf0f819ecccc#diff-cd73aae34978f8a15318265b0f4b962b) (compare with the graph above).

**Comment by bhousel** [comment]
sigh
