### ISSUE TITLE
Feature suggestion - Lock features

### ISSUE THREAD

**Issue by dustinturp** [openstreetmap/iD#4317]
Feature suggestion for the editor. 

Locking or hiding features from the editor to reduce errors in streets, administrative boundaries, and more. Possibly have a toggle for advanced view with everything visible and editable. 
The other side of the switch can contain standard view with locks for streets and admin boundaries. saved preferences for returning users. 

A snap to feature toggle to turn the feature on and off would be great too. 

I love this editor! Thanks all!

Update: related to https://github.com/openstreetmap/iD/issues/4292

**Comment by bhousel** [comment]
Thanks for the kind words @dustinturp!

iD does have a feature filtering capability, but it is only for hiding and unhiding features, not locking them.. This is still pretty useful to make the administrative boundaries go away, or for making editing easier in very data-dense locations.  Let me know if you still want to keep this issue open.  We might be able to add ability to save the user's preference and to leave features locked but visible.

![feature filtering2](https://user-images.githubusercontent.com/38784/30220180-72210a94-948c-11e7-9939-7e2b3ff15969.gif)

**Comment by dustinturp** [comment]
I had no idea that that hiding features was possible. I will be sure to add this info to my workshop. 

This should work perfectly so this can be closed.

Keep up the awesome work! Thanks :)
