### ISSUE TITLE
make possible to add tourism=attraction as a field, display tourism tag as a field

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4323]
Currently in iD it is possible to easily add new object that is tourism attraction (create point, search for tourism attraction).

At the same time there is no way to easily add tourism=attraction to an existing object - in add field search searching for "atrakcja" "turystyka" (with pl as language, unfortunately iD somehow detected that I am in Poland and ignored browser setting to prefer English language for content) reveals no entries that can be added. 

tourism=attraction is also frequently invisible - for example http://www.openstreetmap.org/node/4026515099 or http://www.openstreetmap.org/way/231628291 is not displaying that it is already marked as a tourism attraction.

As result people, like ones editing with maps.me, add tourism=attraction as a separate object duplicating already existing ones.

http://www.openstreetmap.org/node/5043840886/history is example of case where somebody editing using iD added tourism=attraction as a separate object despite that church already existed.

**Comment by matkoniecz** [comment]
For reference - http://overpass-turbo.eu/s/ryE detect bare tourism=attraction tags.

https://josm.openstreetmap.de/ticket/15269 is a related JOSM ticket

**Comment by bhousel** [comment]
I guess we could make it a universal field..
