### ISSUE TITLE
Navigate presets with ↓↑

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#4324]
When typing a preset name, you can press Enter to accept the top one. It would be convenient to be able to select a different one with the arrow keys.

![screenshot_2017-09-08_18-16-16](https://user-images.githubusercontent.com/4283376/30220959-d389b27e-94c1-11e7-83a9-e4b4861499dd.png)

Pressing ↓ in this case should highlight Huishoudelijkeapparatuurwinkel, pressing again should go to the one below...

**Comment by bhousel** [comment]
Yeah this and also #3047 kind of go together - would be great to fix this 👍

**Comment by leegenes** [comment]
Happy to take this one [and related] on. Not sure I completely understand the related referenced issue though.

**Comment by leegenes** [comment]
Also, should the arrow key navigation replace the tab and shift+tab navigation through the results, or complement it?

**Comment by bhousel** [comment]
> Happy to take this one [and related] on. Not sure I completely understand the related referenced issue though.
> Also, should the arrow key navigation replace the tab and shift+tab navigation through the results, or complement it?

I think when the preset list is visible, ideally it should work like:
* <kbd>↓</kbd> and <kbd>↑</kbd> should navigate through the presets
* <kbd>enter</kbd> and <kbd>return</kbd> should select that preset
* <kbd>esc</kbd> should return to the previous screen without changing the preset

<img width="300" alt="screenshot 2017-09-13 09 35 18" src="https://user-images.githubusercontent.com/38784/30380190-ea5c21c8-9866-11e7-9380-20f9aada155d.png">

**Comment by bhousel** [comment]
Hey @leegenes just checking in - are you working on this issue?

**Comment by shadeofgreene** [comment]
I will work on this if no one else does.

**Comment by bhousel** [comment]
Sure @shadeofgreene, go for it!

**Comment by leegenes** [comment]
Sorry about that. Been away from the computer for a few weeks unexpectedly. Thanks, for taking it, @shadeofgreene

**Comment by shadeofgreene** [comment]
No problem, let me take a look at it.

**Comment by MaciejWWojcik** [comment]
What's the progress for this issue? Is there something to do?

**Comment by bhousel** [comment]
> What's the progress for this issue? Is there something to do?

Looks like nobody is working on it currently, you can give it a shot @MaciejWWojcik

**Comment by MaciejWWojcik** [comment]
ok, so I can start coding from master branch?

**Comment by bhousel** [comment]
> ok, so I can start coding from master branch?

A good way to stay organized is to do this (you might have done some of these steps already?):

#### Setup:
Fork your own iD, and make it easy to keep it in sync with ours..

1. Fork the repo into your personal GitHub account.  Now you have your own iD  🎊 
2. Clone your iD to your local machine:  
`git clone git@github.com:MaciejWWojcik/iD.git`
3. You'll have a "remote" called `origin`.  You can also add our repo as an "upstream" remote:  
`git remote add upstream git@github.com:openstreetmap/iD.git`
4. Never do anything in `master`.  This will be a branch that you just keep in sync with the main iD repo.

#### Keeping updated
Do these steps sometimes, before you want to work on stuff..

1. Make sure you are on your `master` branch:  
`git checkout master`
2. Replace your `master` with whatever is in our `master`: 
`git fetch --all && git reset --hard upstream/master`

#### Working on stuff
Changes go into your own iD, but pull requests go back to ours.

1. First make sure you are on your `master` branch:  
`git checkout master`
2. Create a working branch (choose a descriptive name) and switch to it :  
`git checkout -b <branch-name>`
3. Do some stuff, then commit it:  
edit, `git add <files>` ,  `git commit`  .. repeat 🔁as needed..
4. Push your changes to your own iD:  
`git push origin`
5. Go to GitHub for your iD:  https://github.com/MaciejWWojcik/iD
6. GitHub will already know about your recently pushed branch, and ask if you want to create a Pull Request for it.  You can have the Pull Request point back to the main upstream iD.

I think that's it!  Ping me on Slack if you want to chat about any of this....

**Comment by leegenes** [comment]
Also happy to help with questions, too, if bhousel is busy. Just didn't have the time to work on it a while back.

**Comment by MaciejWWojcik** [comment]
Thanks so much for the answer :) It's very clear for me what to do now. So I'm getting to work

**Comment by manfredbrandl** [comment]
@bhousel You wrote a great introduction to use git to create a pull request for iD. I would like to see this in CONTRIBUTING.md in the last section "Submitting Changes" (I have to find a better name).
Instructions to delete your branch after the merge should also be available:
$ git push --delete origin <branch_name>
$ git branch -d <branch_name>
Do you want me to create a PR?

**Comment by bhousel** [comment]
> Do you want me to create a PR?

Yes please!  I'm always happy to merge in improvements to the documentation 😄

**Comment by manfredbrandl** [comment]
@bhousel PR #5241 added.

**Comment by manfredbrandl** [comment]
@MaciejWWojcik Do you still plan to work on that issue?
