### ISSUE TITLE
Switch between area outlines

### ISSUE THREAD

**Issue by milanjelisavcic** [openstreetmap/iD#4336]
Some area outlines overlap and there is no possibility to access one of the two areas with iD. The example are buildings where one outline represent a building's outline and purpose, and other inner outlines define 3D features of specific parts of a building. To be able to access outer outlines, I have to detach one node, move it a bit, and then is possible to edit other area's tags. Could iD recognise this overlapping cases?

**Comment by bhousel** [comment]
Thanks for the report, this is a duplicate of #2225
