### ISSUE TITLE
Why do the topbar buttons move in Firefox when entering save mode?

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4348]
What are you doing firefox 😭 
FF 55.0.3
Mac OS Sierra 10.12.6

I think they are trying to move out of the way of the inspector pane, which is hidden underneath the map?

![firefox buttons](https://user-images.githubusercontent.com/38784/30444644-a0d64f9c-9951-11e7-948e-b095cb2ea155.gif)

**Comment by boothym** [comment]
Interesting, hadn't noticed that before! Same on Windows 10 here.
