### ISSUE TITLE
Sources longer than one line are displayed strangely 

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4349]
![](https://i.glideservers.com/u/jambc035c74-cff4-4843-a2d8-cb41125463d9.png)

**Comment by bhousel** [comment]
<img width="363" alt="screenshot 2017-09-18 10 23 56" src="https://user-images.githubusercontent.com/38784/30546808-9fc15266-9c5b-11e7-883c-770e29f5d2f2.png">

Fixed this by dropping the fixed height and switching layout to flexbox 👍
