### ISSUE TITLE
Minor issues with conflict resolution screen

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4351]
- [x] <kbd>esc</kbd> should not cancel save mode and return to browse mode (allowing users to edit during conflict resolution) - rather, <kbd>esc</kbd> should be the same as hitting the conflict resolution cancel button.
- [x] Don't show "all conflicts resolved" message and do not unlock save button, before the user has actually clicked anything (it's also possible that "use theirs" was actually selected by default but somehow the radio button did not update):
- [ ] Check if wrong username is being reported when there is a conflict with editing child nodes but displaying the username of the parent way. see https://github.com/openstreetmap/iD/issues/4351#issuecomment-338999345

<img width="392" alt="screenshot 2017-09-14 21 42 33" src="https://user-images.githubusercontent.com/38784/30462765-d51a60d8-9995-11e7-8170-dbec5dda21b7.png">

**Comment by jjiglesiasg** [comment]
By the way and happen to me often. How we can have a conflict resolution with ourselves?

**Comment by bhousel** [comment]
> By the way and happen to me often. How we can have a conflict resolution with ourselves?

I sometimes trigger one intentionally to test, but I do this by opening iD in two separate browser tabs.  

I think I have seen occasionally where I can generate a conflict with another user by moving some nodes of a way, however the my own name is displayed because they I touched the way.   I will check this and see if it's the cause and if we can improve the message.

**Comment by bhousel** [comment]
> I will check this and see if it's the cause and if we can improve the message.

Just an update - I couldn't spot anything obvious in the code that would cause the wrong username to display, but if this happens again, we can reopen this issue.
