### ISSUE TITLE
Add preset for route=piste

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4355]

**Comment by bhousel** [comment]
This is true, we don't have a preset for `route=piste`.. 
If we did have a preset, we wouldn't add the pistes to routes automatically (just as we don't do this for highways, railways, etc).

**Comment by bhousel** [comment]
osm wiki:  https://wiki.openstreetmap.org/wiki/Tag:route%3Dpiste
@danpat any strong opinions about these? ⛷

**Comment by SelfishSeahorse** [comment]
@bhousel: Sorry for asking, but what do you mean with 'we don't have a preset for ``route=piste``'?

If I draw a line/way and select 'Piste/Ski trail', iD only adds ``piste:type=yes``. Wouldn't it be possible that ``route=piste`` gets added too?

![untitled](https://user-images.githubusercontent.com/14875493/30532931-24045866-9c57-11e7-8430-0a02290fb023.png)

![untitled2](https://user-images.githubusercontent.com/14875493/30533078-cf937982-9c57-11e7-8377-4ae60080ba70.png)

**Comment by bhousel** [comment]
> @bhousel: Sorry for asking, but what do you mean with 'we don't have a preset for route=piste'?
> 
> If I draw a line/way and select 'Piste/Ski trail', iD only adds piste:type=yes. Wouldn't it be possible that route=piste gets added too?

iD doesn't add `route=piste` tag just because we didn't know about it.  It looks like [the `route=piste` proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:route%3Dpiste) accepted in 2014 was just for route relations, so I don't know how that tag ended up being recommended for ways too.  It doesn't make much sense in that context.

**Comment by SelfishSeahorse** [comment]
> It looks like the route=piste proposal accepted in 2014 was just for route relations, so I don't know how that tag ended up being recommended for ways too.

Apparently, this was a mistake and [has been corrected](https://wiki.openstreetmap.org/w/index.php?title=Tag:route%3Dpiste&diff=1515586&oldid=1515585) in the meantime. (See also <https://lists.openstreetmap.org/pipermail/tagging/2017-October/033854.html> and following emails.)

This issue can be closed then.

**Comment by bhousel** [comment]
> Apparently, this was a mistake and has been corrected in the meantime.

Great!

I will add a preset for `route=piste` on a relation (iD doesn't have this yet) and then close.

**Comment by SelfishSeahorse** [comment]
Thank you!
