### ISSUE TITLE
preview.ideditor.com/master no german on Firefox

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4359]
I want to try the preview to find errors in translation, e.g. in the walktrough.
On Windows 7 Enterprise 64-bit i do open openstreetmap.org an log in and open the preview on another tab.
Chrome 61.0.3163.79 64-bit is fine:
![image](https://user-images.githubusercontent.com/5360273/30638618-4e38137e-9dfc-11e7-843c-07fef4d30094.png)
Firefox 55.0.3 (32-bit) is english:
![image](https://user-images.githubusercontent.com/5360273/30638659-6dbe0082-9dfc-11e7-8883-be635020f6bc.png)
IE 11.0.960018792 Updateversion 11.0.46 (KB4036586) is fine:
![image](https://user-images.githubusercontent.com/5360273/30638705-9198cf1e-9dfc-11e7-84b1-2ce19d762e90.png)
I would like to test the preview in german on Firefox also. Any hint?

**Comment by bhousel** [comment]
I followed the instructions here, and was able to get Firefox to show German on preview.ideditor.com/master

https://www.lifewire.com/change-default-languages-in-mozilla-firefox-4103602
