### ISSUE TITLE
Add some more fields to the volcano preset

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4365]
The [wiki](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dvolcano) says that there are two more tags that can be added to a volcano.

**Comment by bhousel** [comment]
Sounds good 👍

**Comment by bhousel** [comment]
btw, I use the "preset" label for things that are .json config only, and the "field" label for things that require custom programming in the fields code - sorry that is confusing!
