### ISSUE TITLE
Add presets for fitness station equipment

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4373]
As we are adding playground presets in #4252 , we can add [fitness station](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfitness_station) presets at the same time.

**Comment by bhousel** [comment]
Sure, sounds good

**Comment by willemarcel** [comment]
It already exists: https://github.com/openstreetmap/iD/blob/master/data/presets/presets/leisure/fitness_station.json

**Comment by lakedistrictOSM** [comment]
Can we add "trim trail" to the terms for fitness_station please? Thanks.

**Comment by bhousel** [comment]
> Can we add "trim trail" to the terms for fitness_station please? Thanks.

I added this term in b0c50bcc3..

@willemarcel we do have a generic preset for the fitness station stuff, but I think this issue is about making presets for some of the specific pieces of equipment.
