### ISSUE TITLE
amenity=parking: missing access=yes

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4383]
`access=yes`, used to tag public car parks (see [Wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity=parking)), is missing for `amenity=parking`:

![screen shot 2017-10-02 at 10 33 51](https://user-images.githubusercontent.com/14875493/31069739-03de7d84-a75e-11e7-8511-39f1f7921879.png)

Thanks for adding it.

Edit: I just noticed that `access=yes` is missing for `amenity=bicycle_parking`, too.

**Comment by bhousel** [comment]
We used to have separate fields for toilets, which included a `yes` option (previously `public`)  vs. other simple fields like parking and swimming pools, which did not include `yes` option.

I just added the `yes` option to `access_simple.json` and removed the special `access_toilets.json` field - so now all the simple access fields use the same list.  I think the tagging has standardized enough that this is fine.
