### ISSUE TITLE
Feature request: please add layer element for waterway

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4384]
It would be nice if the waterway preset would include a `layer=*` element (below 'Tunnel'), like there is one for highway:
 
![screen shot 2017-10-02 at 11 44 30](https://user-images.githubusercontent.com/14875493/31072201-47b39db0-a767-11e7-8ccf-a09b93d0cdba.png)

Maybe this would help that less culverts added lack a `layer=-1` tag.

**Comment by SelfishSeahorse** [comment]
Wow, you were quick! :-) Thank you!

**Comment by bhousel** [comment]
I did this by adding a special radio field just for waterways.  It's a little weird to have a radio with just one option, but I think it's worth it to get the extra `tunnel` and `layer` fields with their builtin magic to deal with the OSM tags.

![tunnel](https://user-images.githubusercontent.com/38784/31085408-04d3adfc-a765-11e7-9dae-81e9c8127f19.gif)

**Comment by bhousel** [comment]
> Wow, you were quick! :-) Thank you!

You're welcome!
