### ISSUE TITLE
Problem saving map changes

### ISSUE THREAD

**Issue by eriqx2** [openstreetmap/iD#4386]
I have got this error while trying to save some map changes
ActiveRecord::StatementInvalid: PG::DiskFull: ERROR: could not extend file "pg_tblspc/16400/PG_9.5_201510051/16402/4000913336.6": No space left on device HINT: Check free disk space. : INSERT INTO "changesets" ("user_id", "created_at", "closed_at") VALUES ($1, $2, $3) RETURNING "id"

**Comment by Lukas458** [comment]
I do also have this problem!

**Comment by Lukas458** [comment]
I tried again to save my last map changes and it worked again yet, but there was a long duration until the changes were saved.

**Comment by bhousel** [comment]
Yes, looks like everyone is getting this issue right now.. It's an error reported by the OSM server, so not something to do with iD.  You might need to just wait a little while for the save to work again.

**Comment by eriqx2** [comment]
Looks like it is fixed already.
