### ISSUE TITLE
Add "sweet shop" as a term for shop=confectionery and distinguish from craft

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4388]
Can we add "sweet shop" as a term for shop=confectionery? It's what they're commonly called in the UK. 

Also, on a related note, when I search "sweet" in iD it comes up with "Confectionery" which is actually craft=confectionery. Can we change the name of this to make it more obvious that this is the craft tag and not the shop tag. Maybe craft=confectionery could be called "Confectionery Producer/Sweet Maker" or similar?

**Comment by bhousel** [comment]
* `shop=confectionery` is currently named "Candy Store" - this is ok

Somebody can do this: 
- [ ] `craft=confectionery` - rename to "Candy Maker"
- [ ] add "sweet" as a search term for both presets (and anything else that fits)
