### ISSUE TITLE
Way not zoomed to in search result

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#4392]
Sure I've seen this issue before, but can't find it - some weird search/zooming behaviour for ways:

If you put "n3191505807" into the search box and click on the result it zooms to the node. 
If you put in "w5182746" it shows the tags but it does not zoom. However if you click the X then re-enter the search and click on w5182746 it zooms to it.

**Comment by JamesKingdom** [comment]
Yes it seems @willemarcel commented about [this](https://github.com/openstreetmap/iD/issues/4276#issuecomment-327022027) on issue #4276.
Better to report twice than never :+1:
