### ISSUE TITLE
CCTV camera should be allowed on a vertex

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4394]
CCTV cameras are mounted on walls.

**Comment by bhousel** [comment]
Sounds good..

looks like you need to change:
- https://github.com/openstreetmap/iD/blob/master/data/presets/presets/man_made/surveillance.json
- https://github.com/openstreetmap/iD/blob/master/data/presets/presets/man_made/surveillance_camera.json
- https://github.com/openstreetmap/iD/blob/master/data/presets/presets/highway/speed_camera.json
