### ISSUE TITLE
Entry/Exit is shown but cannot be selected (in German: Eingang/Ausgang)

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4397]
When there is an Entrance/Exit it is shown correctly as "Eingang/Ausgang" (in German):
![image](https://user-images.githubusercontent.com/5360273/31214603-380e3b6c-a9ac-11e7-9135-ad8ab3b490c2.png)
When I want to declare a new point as an Entrance/Exit I cannot find it:
![image](https://user-images.githubusercontent.com/5360273/31215568-53295680-a9b0-11e7-9ffc-354db0b781a9.png)

**Comment by willemarcel** [comment]
@manfredbrandl this preset only works in a vertex (nodes that are part of a way)

**Comment by JamesKingdom** [comment]
As @willemarcel said, this is a vertex only preset, I tested it in German just to be sure:
![](https://i.glideservers.com/u/jamb4ed0d27-c85e-4c6c-87a6-00b3df53d3c0.png)

**Comment by bhousel** [comment]
Thanks @willemarcel & @JamesKingdom for investigating - this makes sense.. 
@manfredbrandl please close if this sounds ok..

Also check on transifex here:
https://www.transifex.com/openstreetmap/id-editor/translate/#de/presets/11582377?qt=eingang
to make sure that the preset has sufficient related terms that you can search for it.  For example it probably makes sense for "ausgang" to be a search term on its own, in case that is what somebody starts typing.

**Comment by manfredbrandl** [comment]
@bhousel I was not aware that OSM allows tags on vertices, I always created a point with tags and than snapped it onto a vertex. I imagined that a separate point is required and saved on top of the vertex. Now it seems that I was in Error. Anyway, maybe the Help or even the Walkthough can stress that. Or did I miss the information there?

**Comment by bhousel** [comment]
> I was not aware that OSM allows tags on vertices, I always created a point with tags and than snapped it onto a vertex. I imagined that a separate point is required and saved on top of the vertex. Now it seems that I was in Error.

What you did is ok too, just maybe less efficient..  

> Anyway, maybe the Help or even the Walkthough can stress that. Or did I miss the information there?

I'm not sure, and that's a good point.. We might not mention in the tutorial that vertices are their own special kind of node with different allowable presets.  "Vertices" is kind of a tough word to teach people....

**Comment by manfredbrandl** [comment]
In the German translation I did not use vertex but "Knoten" (node) which may be not so exact but more understandable. I extended the German translation of the Adress part of the help to introduce tags on vertices as addresses on entrance nodes.
