### ISSUE TITLE
Source Switcher should be disabled while walkthrough is active

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4401]
I know that the source switcher is mostly for local iD installs for debugging, but clicking it while the walkthrough is active throws away the walkthrough graph.

**Comment by bhousel** [comment]
For anyone who wants to work on this - it's real easy!
Just add a `if (context.inIntro()) return;` right after the `d3_event.preventDefault();` line.
This will make the button do nothing if the tutorial is active..

https://github.com/openstreetmap/iD/blob/dd40dd5fadf334659558814d26e345f571951553/modules/ui/source_switch.js#L14-L31

**Comment by pwelby** [comment]
I'm on it!
