### ISSUE TITLE
Cannot continue iD editor walkthrough in Areas chapter

### ISSUE THREAD

**Issue by vtmarvin** [openstreetmap/iD#4417]
OSX 10.12.6
Chrome 60.0.3112.113 64bit
Czech language
resolution 1440x900
not using mouse, just touchpad

When going through iD editor walkthrough in chapter "Areas" (Plochy), in a moment I sould add a property of playground, tutorial overlay highlights **app property field outside of visible screen area**. There is no simple way how to click on desired element or scroll through tutorial overlay.![picture 1 - field out of visible area](https://user-images.githubusercontent.com/32634656/31331406-75f91b84-ace2-11e7-9032-366df41c9e3f.png)

Workaround (lower font size in Chrome).
![picture 2 - field visible font size lowered](https://user-images.githubusercontent.com/32634656/31331405-75f655b6-ace2-11e7-88ff-bab70ab8c5bf.png)

Desired behavior is, that tutorial should scroll to desired filed if outside of visible area.

**Comment by bhousel** [comment]
Good catch, thanks!  I think that's because there are some new fields here now.
