### ISSUE TITLE
Notify translators prior to release

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4420]
Notifying translators is first action on release-checklist
![image](https://user-images.githubusercontent.com/5360273/31342886-469cd534-ad0e-11e7-93c0-854ebd27ac53.png)
but hat not been done:
![image](https://user-images.githubusercontent.com/5360273/31342849-2d4d944c-ad0e-11e7-870d-792b05af8e39.png)

**Comment by bhousel** [comment]
I should probably remove it from the checklist.. I really only do announcements if the release involves a lot of translation work. 

The big problem I see is that while the top 10 languages get fully translated within a few days, the rest of the 70 or so languages have very little activity.  This is true whether I make announcements or not, or even beg people on Twitter and OSM mailing lists to pitch in with translation.

**Comment by manfredbrandl** [comment]
Could you change it to notify only for languages which have less than e.g. 100 untranslated strings? If a few days (a week would be better but may be to long) prior a release no new strings for translation are introduced and the release is announced to me, i have a change to get a fully translated release.

**Comment by bhousel** [comment]
> If a few days (a week would be better but may be to longfor the developers) prior a release no new strings for translation are introduced and the release is announced to me, i have a change to get a fully translated release.

I usually let iD stabilize for a few days or even a week before doing the release just so the translation teams can catch up.  I didn't do that with 2.4.2, and I'm sorry..  

I'll be doing another release hopefully today, and possibly more releases later this month - there will be opportunities to fill in the missing translations.
