### ISSUE TITLE
Add preset for place=plot

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#4423]
Some users in few cities in Bolivia are starting to map Plots as "residencial areas" instead as Plots as such.
I have found difficult to map Plots because there is no allowance to change from Area to Place=Plot in ID.
Any suggestions?
Thanks
JJ

**Comment by bhousel** [comment]
We'd need to add a preset for 
https://wiki.openstreetmap.org/wiki/Tag:place%3Dplot

This is the first I'm hearing about it, but 27,000 uses makes it a well established tag, so we should add a preset for it.

**Comment by bhousel** [comment]
WIP at #4427
