### ISSUE TITLE
Fallback area preset loses its `area=yes` tag

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4424]
Seems like the `area=yes` tag is getting removed from the fallback "Area" preset - this turns it back into a normal line.  Not sure when this regressed, but we should fix it.

![areayes](https://user-images.githubusercontent.com/38784/31366018-e77a9666-ad3c-11e7-9b3d-03f0abd1e679.gif)

**Comment by willemarcel** [comment]
@bhousel why does this preset is available to an area feature? I think it should be available to lines, as sometimes we need to apply `area=yes` tag to a feature that was drawn as line.

**Comment by bhousel** [comment]
> @bhousel why does this preset is available to an area feature? I think it should be available to lines, as sometimes we need to apply area=yes tag to a feature that was drawn as line.

Yes, we should have a way to switch between area <-> line.  

I tried adding it here, but decided not to merge until we can limit it to closed features: https://github.com/openstreetmap/iD/issues/1828#issuecomment-256251820

**Comment by bhousel** [comment]
This broke in 9882cf1d7bade621a4f866f4c16474820b49830c, fixing #4114.  

It looks like the new code is correct (removing `area=yes` and adding it back only if needed per `areaKeys` lookup) - in all cases _except_ for the case where the preset is trying to set the `area` tag to something.  😅
