### ISSUE TITLE
"substance=" field to pipeline preset

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4430]
https://wiki.openstreetmap.org/wiki/Key:substance

**Comment by bhousel** [comment]
Sounds good to me 👍 

@TheGreenToaster - want to take care of this?
It would be similar to the steps you did for the trade shop in #4410..

- [ ] `git pull` and `npm install` to update your local copy of the repo
- [ ] copy a combo field like `data/presets/fields/site.json` to a new field `data/presets/fields/substance.json`, then change the "key" to say "substance" and the label to say "Substance"
- [ ] add "substance" to the "fields" array in `data/presets/presets/man_made/pipeline.json`
- [ ] `npm run build` to update the generated files

**Comment by xmile1** [comment]
Hi @bhousel, I am new to this project, If its okay for me to work on this let me know, I have my dev env setup.

**Comment by bhousel** [comment]
> Hi @bhousel, I am new to this project, If its okay for me to work on this let me know, I have my dev env setup.

Yes @xmile1 go ahead and work on it 👍   Thanks!

**Comment by xmile1** [comment]
so to be clear, following those highlighted step are what I need right?

**Comment by bhousel** [comment]
> so to be clear, following those highlighted step are what I need right?

Yes @xmile1 you got it... Check the [README under data/presets](https://github.com/openstreetmap/iD/blob/master/data/presets/README.md) if you want some more context, but it is really just adding one new .json file and editing another existing .json file.

**Comment by bhousel** [comment]
closed in #4432
