### ISSUE TITLE
Way created with duplicate nodes

### ISSUE THREAD

**Issue by paulmach** [openstreetmap/iD#4433]
Using ID 2.4.3 user created [way/531551165](https://www.openstreetmap.org/way/531551165), a rectangular building with two duplicate nodes (same lat/lon, different id) on one corner.  The nodes are [5159774882](https://www.openstreetmap.org/node/5159774882) and [5159774883](https://www.openstreetmap.org/node/5159774883)

This was all done as part of changeset [52806414](https://www.openstreetmap.org/changeset/52806414) by a new user.

I don't know how this is possible during a regular workflow so i'm posting it here to let you guys know in case you run into this sort of thing more often. Maybe you know what action could have caused this as a direction to look for some bugs.

**Comment by bhousel** [comment]
Thanks for reporting @paulmach.. I did a lot of work last year to prevent this, but there are still a few places in the code where the nodelist is directly mutated.

**Comment by jjiglesiasg** [comment]
We have several cases of duplicated ways and waterways with double nodes, just with OSM-Inspector we can detect. Looks like JOSM produce this issue for a short period of time

**Comment by bhousel** [comment]
I'm also looking at #3058 as a possible cause of duplicate nodes.  We've seen a handful of these lately and I'm fixing this today.

**Comment by bhousel** [comment]
This case is probably not #3058 after all (which I closed today). 

The nodelist contained unique (different id) coincident nodes, not duplicate (same id) nodes out of order.  This one might be related to #3797 though.

**Comment by paulmach** [comment]
Thanks for looking into this.  I've found another example of a line with this problem. The original example was an area.  I've also been finding these with OMS Inspector.

From what I've seen, it is likely that the user used "move" while making these edits. So https://github.com/openstreetmap/iD/issues/3797 could fit.

**Comment by bhousel** [comment]
@paulmach (cc @maxerickson, who was also discussing in IRC)

I also found it's kind of easy to just create geometries this way, see below..

I wonder if some of these are a case of where a user accidentally dragged a midpoint onto a corner, (e.g. clumsy with the mouse), and then just dragged another one to "fix" the problem?  

![duplicate nodes](https://user-images.githubusercontent.com/38784/32185687-4f8b76dc-bd76-11e7-87e7-6ff30a27cdf0.gif)
![screenshot 2017-10-30 13 27 43](https://user-images.githubusercontent.com/38784/32185693-55262d12-bd76-11e7-9602-3ed1b3b38b11.png)

**Comment by paulmach** [comment]
The examples I'm seeing (seeing a few more from OSM inspector) are all duplicate consecutive nodes. If you drag the two "problem" corners together iD cleans it up all nicely. 

@bhousel I think the above should be fixed with some validation/cleanup step. Not sure exactly what the logic would be.

**Comment by paulmach** [comment]
Here is a good example that supports the possibility this is caused by the "moving" https://github.com/openstreetmap/iD/issues/3797

https://www.openstreetmap.org/edit?editor=id&node=5172263001#map=20/38.49011/-122.67726

**Comment by SomeoneElseOSM** [comment]
For info neither of the couple that I've just seen (see https://github.com/openstreetmap/iD/issues/4509 ) were consecutive nodes.  Both were ways (but that could be selection bias) and both resulted in "a part of the way being reattached to an earlier / later part of the way".

**Comment by bhousel** [comment]
I _think_ I might have fixed this in 0b6183e2c
I'm going to close and push a new version, but if we see this occuring frequently in iD 2.6.1 or newer, let's reopen.

**Comment by SomeoneElseOSM** [comment]
@bhousel Does http://osmhv.openstreetmap.de/changeset.jsp?id=57730892 look like the same problem?  That "extra line" was added 2nd April.

**Comment by bhousel** [comment]
checking here:  https://osmcha.mapbox.com/changesets/57730892

Hm that's weird.
That user is using iD 2.4.1 and they have modified iD to hide the `host` tag from their changesets.
OSMCha flags it as an unrecognized iD instance, and the user as having several blocks already.

So, it could be this bug, but they are using a very old version.

**Comment by b-jazz** [comment]
Here is a similar situation with duplicate nodes. I'm not sure if you want this as a new bug or simply as comments on the old bug, so I'll start here.

https://www.openstreetmap.org/changeset/69938949

The user created a footway from north to south, and then started a new footway from the midpoint of that way and went east to the existing Echo Heights Drive. The starting point for the east/west footway has a node with the identical lat/long of the north/south footway. Both of the footways were created in the same changeset.
