### ISSUE TITLE
Copy all tags shortcut

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4434]
```
Ctrl+C	Copy selected features
Ctrl+V	Paste copied features
```
are great, e.g., #4067.

However there are times when one just wants to copy all the tags, but
not any geometries.

For instance say there are two houses already on the map, one with all
the tags nicely filled in, the other without any tags yet.

It would be nice if we could copy all the tags of house 1 to house 2,
and then just manually adjust the house number of house 2.

**Comment by JamesKingdom** [comment]
Yes, this is a nice feature, and an this issue is already open #839 .
Here's a mockup of what was in mind 
![](https://cloud.githubusercontent.com/assets/2410353/22181804/40af23bc-e094-11e6-8d50-c688d123f032.png)
