### ISSUE TITLE
Add an interface for specifying accepted payment methods on shops

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#4437]
I believe the following are valid
- payment:cash=yes/no
 - payment:coins=yes/no (implied by payment:cash)
 - payment:notes=yes/no (implied by payment:cash)
- payment:cheques=yes/no
- payment:credit_cards=yes/no
- payment:debit_cards=yes/no

**Comment by afmenez** [comment]
Are there tags for specific credit card operators (Visa, Master, American, ...)?

**Comment by bhousel** [comment]
We do have a payment field on vending machines - maybe we should add it to all the shop types too?

![payment types](https://user-images.githubusercontent.com/38784/31562597-17b18ba6-b02a-11e7-8435-7c4b486d22e0.gif)

The convention for credit cards is to just add the types of cards accepted to the list ([see osm wiki](https://wiki.openstreetmap.org/wiki/Key:payment#Credit_cards)):
<img width="356" alt="screenshot 2017-10-13 15 24 54" src="https://user-images.githubusercontent.com/38784/31562798-beeb5f5a-b02a-11e7-8fcb-710804dd3b9d.png">

**Comment by afmenez** [comment]
Seems to be exactly what I had in mind. :)

**Comment by afmenez** [comment]
And this would also be useful for restaurants too.

**Comment by bhousel** [comment]
I'm thinking if we do this it should probably be a "universal" field so that mappers can put it on any feature.  Otherwise we would need to add it to a lot of amenities and shops.  I'd like to hear what other people think too.

**Comment by bhousel** [comment]
I did this
