### ISSUE TITLE
Power transformer preset

### ISSUE THREAD

**Issue by gustavecha** [openstreetmap/iD#4442]
Hi,

An extension proposal had been accepted regarding power transformer mapping. Any preset involving power transformer and power pole with transformer should be updated.
​https://wiki.openstreetmap.org/wiki/Proposed_features/Transformer_extension_proposal

Tagging of power=transformer has been updated accordingly
​https://wiki.openstreetmap.org/wiki/Tag:power%3Dtransformer#Tagging

User should be prompted for the following tags (with according label), out of casual ones :
    

- transformer= {distribution, generator, converter, traction, auto, phase_angle_regulator, auxiliary, yes} (Function of transformer)
- location=* (Transformer location)
- phases=* (Number of phases)
- frequency=* (Operating frequency)
- voltage:primary=* (Primary "power plant side" voltage)
- voltage:secondary=* (Secondary "consumer side" voltage)
- voltage:tertiary=* (Tertiary "auxiliary side" voltage)
- windings=* (Number of windings)
- windings:configuration = {star, delta, open-delta, zigzag, open, scott, leblanc} (Windings configuration)
- rating=* (Rating in VA)
- devices=* (Number of different transformer devices)

voltage=* key shouldn't be used any more on power transformers.

Additionally, some validation rules should be created as follow and warn users :
    Check rating=* is given in VA and without any unit in the value (like multiples kVA, MVA,...)
    Check voltage=* isn't associated with power=transformer or transformer key

Thank you in advance to take care of this, all the best.

**Comment by bhousel** [comment]
Most of this is fine.. some opinions:
- transformer rating should be allowed to include the SI unit (like other OSM tags).  Besides, this is what is often stamped on the nameplate or written on the outside of the transformer.
- frequency seems kind of silly.. not sure whether we should even include it. 
- We probably won't do validations, but an external tool could do them.

**Comment by gustavecha** [comment]
> transformer rating should be allowed to include the SI unit (like other OSM tags). Besides, this is what is often stamped on the nameplate or written on the outside of the transformer.
VA is SI. You may look for multiple units like kilo, mega, giga.
According to a comment during voting, MVA, kVA and so on are time consuming for scripts. Not all OSM tags are provided with multiple units. voltage=* is a good example. We have voltage=400000, voltage=225000 instead of voltage=400kV, voltage=225kV. It may be a good advantage for editors to display kV, MVA... but store multiple-less values in DB.
Furthermore, it prevent a mess in values : voltage=400000 <=> 400kV <=> 400 kV <=> 400 k <=> 400 kilo

> frequency seems kind of silly.. not sure whether we should even include it.
Why ?
Frequency is a key figure of a transformer. Some places can actually use different frequencies than domestic grid. Look at 16.6 Hz in Switzerland and Germany for train power feeding systems.
Whereas frequency=* is overused on power=line objects while it's not relevant. It should only be used on "power route" relations (because a physical line can be operated at whatever frequency operant want)

> We probably won't do validations, but an external tool could do them.
No problem, i asked for it just in case.

**Comment by bhousel** [comment]
@gustavecha (sorry if what I said above sounds overly critical, I actually do like these proposals)

Can you also review the presets under here: https://github.com/openstreetmap/iD/tree/master/data/presets/presets/power
and open more issues for anything else that might be missing from what iD currently supports?

Just at a quick glance, we should probably add `voltage` to `power=line` and `power=minor_line`.  (but I still think `frequency` is silly)

**Comment by gustavecha** [comment]
Thnx @bhousel for kind remarks :)

Once switches and transformers fully cleaned up, I'll have a look to other presets

I agree for frequency regarding power=line / minor_line. This is a dynamic/operating information which is irrelevant on static/physical network items. No problem to remove it from power lines, cables...

**Comment by ToeBee** [comment]
During hack day at SOTM US today I was looking around for something new I could work on and maybe get done for Hacktoberfest. I ended up getting further than expected. What's the consensus on `frequency`? Right now I have this working:
![image](https://user-images.githubusercontent.com/348948/31872648-31a10612-b783-11e7-88c0-bffdc69a6307.png)

**Comment by ToeBee** [comment]
Oh and also, regarding the values for `rating`: it seems like the current convention in use is to specify units like `KVA`, etc. See [taginfo](https://taginfo.openstreetmap.org/keys/rating#values) for the most common values. I put the placeholder value in without units for now.

**Comment by bhousel** [comment]
Looks great @ToeBee!  Sorry I missed you today..
* `frequency` is fine, go ahead and add..
* Can you Title Case the field labels?

Yeah it would make me very happy if the power mapping people would be ok about using normal units like kVA and kV for power and voltage.  I have a degree in electrical engineering and it really bothers me to see things written without the SI prefix.  It's just not how people talk about electrical stuff.

**Comment by gustavecha** [comment]
Hi,

Nice one TooBee, this looks great :)

Regarding units, the problem regards how machine talk, not humans.
It's really more convenient to process values without units.
This do not prevent editors to display values with unit and store normalized values.
Furthermore, this has been asked while voting the proposal last month on wiki (for rating key) : 
https://wiki.openstreetmap.org/wiki/Proposed_features/Transformer_extension_proposal

Experience shows voltage key is more convenient than rating with units

**Comment by bhousel** [comment]
Ok, @gustavecha - so I don't _really_ care, and I will accept the pull request regardless of what the placeholder says, and I really don't want to continue an argument about power tagging, but I think you should strongly rethink this power proposal, given that it doesn't reflect how actual people in industry speak about power, and given that actual tags in widespread use already include the units that people use to talk about these things.

Additionally, both
- https://wiki.openstreetmap.org/wiki/Key:generator:output
- https://wiki.openstreetmap.org/wiki/Key:plant:output

allow for units.  This makes sense, as nobody would ever say a power plant has an output of 2000000000 watts.  It is the same for high voltage equipment.

If somebody made a new proposal to say that we're going to switch over the `maxspeed` tag to use m/sec instead of km/hr, people would likely ignore it regardless of whatever the wiki says or how many people are convinced to vote for it.

I understand that it is much easier to write overpass or SQL queries or mapcss rules if you don't need to think about units, but it makes things much easier for actual humans (my priority as the maintainer of iD) to be able to enter the values the way they appear in the real world.  And the computation to convert these things (even in SQL with a materialized view or a calculated column) is just not that complicated.

Again, I'll accept this regardless, but please reconsider.  You are proposing a thing that is contrary to how the rest of the numeric tags in OSM work.

**Comment by gustavecha** [comment]
> but I think you should strongly rethink this power proposal, given that it doesn't reflect how actual people in industry speak about power
We all spend many time here.
Such severe remarks doesn't allow us to make things better. I'm really sad to read you in such way.
RFC for proposal are announced on tagging ml, I took care of all comment received. All definitions are sourced on IEC encyclopedia. It takes me months to write it, no I won't rethink it.

> This makes sense, as nobody would ever say a power plant has an output of 2000000000 watts. It is the same for high voltage equipment.
That's basically why we use to separate view from db.
You assume people read directly in db while I have a different point of view

I'm not the one to blame for unit mess, nor the unit-less values.
voltage=* was used many without any unit years before I open my mapper account.
The transformer proposal initially propose rating=* with unit **but** someone asked for it without unit while voting and I would rather agree with him from a db point of view.

Come on guys please wake up!
