### ISSUE TITLE
landuse=brownfield/greenfield presets

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4444]
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dbrownfield
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dgreenfield

**Comment by manfredbrandl** [comment]
I am a git newbie. I did:
- fork iD to my repository with github
on linux shell:
> manfred@xyz:~/src$ git clone git@github.com:manfredbrandl/iD
Cloning into 'iD'...
remote: Counting objects: 72191, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 72191 (delta 0), reused 3 (delta 0), pack-reused 72184
Receiving objects: 100% (72191/72191), 125.11 MiB | 2.38 MiB/s, done.
Resolving deltas: 100% (51228/51228), done.
Checking connectivity... done.
manfred@xyz:~/src$ cd iD
manfred@xyz:~/src/iD$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
manfred@xyz:~/src/iD$ git checkout -b landuse-fields-preset
Switched to a new branch 'landuse-fields-preset'
manfred@xyz:~/src/iD$ cd data/presets/presets/landuse/
manfred@xyz:~/src/iD/data/presets/presets/landuse$ cp meadow.json brownfield.json
manfred@xyz:~/src/iD/data/presets/presets/landuse$ vi brownfield.json
manfred@xyz:~/src/iD/data/presets/presets/landuse$ cp brownfield.json greenfield.json
manfred@xyz:~/src/iD/data/presets/presets/landuse$ vi greenfield.json
manfred@xyz:~/src/iD/data/presets/presets/landuse$ cd ../../../..
manfred@xyz:~/src/iD$ git status
On branch landuse-fields-preset
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   data/presets/presets/landuse/brownfield.json
        new file:   data/presets/presets/landuse/greenfield.json

manfred@xyz:~/src/iD$ git commit -m "Add landuse=brownfield/greenfield presets"
[landuse-fields-preset 4d29c60] Add landuse=brownfield/greenfield presets
 2 files changed, 26 insertions(+)
 create mode 100644 data/presets/presets/landuse/brownfield.json
 create mode 100644 data/presets/presets/landuse/greenfield.json
manfred@xyz:~/src/iD$ git push origin landuse-fields-preset
Counting objects: 8, done.
Delta compression using up to 24 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 716 bytes | 0 bytes/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 5 local objects.
To git@github.com:manfredbrandl/iD
 * [new branch]      landuse-fields-preset -> landuse-fields-preset
--
on github:openstreetmap/iD "compare and create pull request"

did i miss anything?

**Comment by bhousel** [comment]
Awesome @manfredbrandl that looks really good...

There are 2 more commands you could run that would be helpful:
- `npm install`
- `npm run build`

These just install some libraries needed to build iD, and then rebuild the generated preset files.  It will touch several more files like `presets.json` and `en.json`, and you can commit that change also.

**Comment by manfredbrandl** [comment]
Okay, i did:
> manfred@xyz:\~/src/iD$ npm install
> ...
> manfred@xyz:\~/src/iD$ npm run build
> ...
manfred@xyz:\~/src/iD$ git status
On branch landuse-fields-preset
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   data/presets.yaml
        modified:   data/presets/presets.json
        modified:   data/taginfo.json
        modified:   dist/locales/en.json

no changes added to commit (use "git add" and/or "git commit -a")
manfred@xyz:\~/src/iD$ git add  data/presets.yaml
manfred@xyz:\~/src/iD$ git add data/presets/presets.json
manfred@xyz:\~/src/iD$ git add data/taginfo.json
manfred@xyz:\~/src/iD$ git add dist/locales/en.json
manfred@xyz:\~/src/iD$ git commit -m "Add landuse=brownfield/greenfield presets with npm run build"
[landuse-fields-preset 4b5ff8a] Add landuse=brownfield/greenfield presets with npm run build
 4 files changed, 50 insertions(+)
manfred@stvg-osm:~/src/iD$ git push origin landuse-fields-preset
Counting objects: 10, done.
Delta compression using up to 24 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 1.11 KiB | 0 bytes/s, done.
Total 10 (delta 9), reused 0 (delta 0)
remote: Resolving deltas: 100% (9/9), completed with 9 local objects.
To git@github.com:manfredbrandl/iD
   4d29c60..4b5ff8a  landuse-fields-preset -> landuse-fields-preset
- It looks like the new changes apeared in the existing pull request
- Was that right?

**Comment by bhousel** [comment]
yes perfect! - the changed files are in your feature branch now.
You will have to `git push` to send the latest commit up to GitHub so I can see and merge it.

**Comment by manfredbrandl** [comment]
Sorry, that did not work out:
> manfred@xyz:\~/src/iD$ git push
> fatal: The current branch landuse-fields-preset has no upstream branch.
> To push the current branch and set the remote as upstream, use
> 
>     git push --set-upstream origin landuse-fields-preset
> 
> manfred@xyz:\~/src/iD$ git status
> On branch landuse-fields-preset
> nothing to commit, working directory clean
> manfred@stvg-osm:~/src/iD$ git push upstream
> ERROR: Permission to openstreetmap/iD.git denied to manfredbrandl.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> manfred@xyz:\~/src/iD$ git push origin
> fatal: The current branch landuse-fields-preset has no upstream branch.
> To push the current branch and set the remote as upstream, use
> 
>     git push --set-upstream origin landuse-fields-preset
> 
> manfred@xyz:\~/src/iD$ git push --set-upstream origin landuse-fields-preset
> Branch landuse-fields-preset set up to track remote branch landuse-fields-preset from origin.
> Everything up-to-date
- On https://github.com/openstreetmap/iD/pull/4448/commits/4b5ff8a377e36bf797aca536daa66e74318b8445 there are changes to six files now. Is that not enough?

**Comment by bhousel** [comment]
looks good thank you @manfredbrandl
