### ISSUE TITLE
Suggestion: Drag and Drop image like tracks

### ISSUE THREAD

**Issue by st-anton** [openstreetmap/iD#4446]
In iD it is easy to overlay / 'import' my own gps track by drag and drop. Is it possible to have the same by drag and drop am image with geotagging? With this, the place of the image is identified immediatelly and you can jump very fast to the place you took a picture before.
Hint: irfan view is able to locate the GPS data of an image and show in OSM: Image -> Information -> EXIF Info -> Show in OSM

**Comment by bhousel** [comment]
This is #1502.. In the meantime you can upload your photos to Mapillary and view them in iD that way.   
(or use JOSM, which has this feature)
