### ISSUE TITLE
preset for leisure=pitch+sport=boules+boules=*

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4449]
https://wiki.openstreetmap.org/wiki/Tag:sport%3Dboules

**Comment by bhousel** [comment]
Someone can 
- [ ] copy `data/presets/presets/leisure/pitch/bowls.json` to `data/presets/presets/leisure/pitch/boules.json` and change values inside that file.  They're almost the same thing.
- [ ] do `npm install && npm run build`

**Comment by bhousel** [comment]
Done in #4451
