### ISSUE TITLE
Ways do not self-connect unless there is a node

### ISSUE THREAD

**Issue by neuhausr** [openstreetmap/iD#4455]
When creating features like a cul-de-sac, an iD user will create a line with a loop on the end. If the user connects the loop back to the line at a node, it will properly connect. But if the user tries to connect the loop back to the line at a place that isn't a node (for example, think of a p or d shape), it will not actually connect. That is, the user will then be able to move the end node without the line there also moving. 

I would expect the end node to connect back to the line whether there is a node at that location or not.

(I have noticed many of these cases when looking through the Self-intersecting Ways in OSM Inspector)

![image](https://user-images.githubusercontent.com/3976407/31776223-8c74c45a-b4b0-11e7-8466-c0a534a186fc.png)

**Comment by bhousel** [comment]
I agree, there is a bug here preventing a new way from self connecting.

**Comment by bhousel** [comment]
done in #4602
