### ISSUE TITLE
require minimal length for description of edit

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4457]
For example in case of

![selection_001](https://user-images.githubusercontent.com/899988/31844297-12e57316-b5f8-11e7-9daa-a81c40b7164a.png)

forcing longer descriptions (2 ASCII characters are not enough to fit a description) would make easier to distinguish a newbie from a vandal

**Comment by bhousel** [comment]
Maybe.. How many k's should we require?

**Comment by matkoniecz** [comment]
I would say that requiring at least 4 would be a good idea - long enough that typing gibberish would be obvious and hopefully will not block valid descriptions. Though now as I think again I worry about Japanese/Chinese - is it possible to fit useful description in that will be counted as 4 characters?

**Comment by bhousel** [comment]
I don't think length of the comment is a very good proxy for quality of the comment.  Whatever we make the min length, someone will fill up with gibberish right?

**Comment by matkoniecz** [comment]
Yes, but with 1 or 2 characters it is unclear whatever somebody is crypic, confused or typing gibberish.

With 4 or 5 signs gibberish is more obvious. Also, maybe at least some would type useful comment after getting a warning.

**Comment by Nakaner** [comment]
@bhousel wrote:
> I don't think length of the comment is a very good proxy for quality of the comment. Whatever we make the min length, someone will fill up with gibberish right?

I agree with that.

The requirement to add a changeset comment which was added a few months (?) ago was a good addition and I have the impression that the vast majority of changeset comments by newbies describes the edit or their motivation to edit OSM well. If someone does not enter a useful changeset comment and continues editing, point him to [Good changeset comments](https://wiki.openstreetmap.org/wiki/Good_changeset_comments).

If there is really a need to invest time into this issue (I think other issues are more important), a hint (either as text or less obstructive by changing the color of the input field) to the user would help more and reduce the frustration.

**Comment by bhousel** [comment]
> Yes, but with 1 or 2 characters it is unclear whatever somebody is crypic, confused or typing gibberish.

My opinion here is that if you find that a user is leaving cryptic comments, and if it is causing problems for reviewers, you should feel comfortable to contact them and ask for more information.  

Even a message like "Thanks for adding these buildings, but I had a difficult time knowing what you did - can you leave a more thorough comment next time?"  sends a message that _someone_ is watching what they do, and just this knowledge (more than any technical hack I can add to the editor) will lead to them being a more useful participant in OSM.

Going to close here for now but I am definitely willing to revisit this issue later if enough people ask for it.
