### ISSUE TITLE
Misleading waterway=drain icon (minor enhancement request)

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4460]
In my opinion, the icon used for waterway=drain is a bit misleading, as it looks more like a stream than an artificial, lined waterway. (In fact, the same icon is also used for streams.) It might be better to replace it with the icon that is used for ditches.

**Comment by bhousel** [comment]
Sounds good - this should be as easy as switching the “icon” property in drain.json to match whatever it says in ditch.json.

**Comment by bhousel** [comment]
This was done!
