### ISSUE TITLE
Do not update the picture

### ISSUE THREAD

**Issue by illiapoint** [openstreetmap/iD#4465]
Here you can see the inconsistency. It is necessary to force the system to redraw these areas.
http://a.tile.openstreetmap.org/13/4935/2783.png
http://b.tile.openstreetmap.org/13/4936/2783.png

Road "T-21-11"
http://www.openstreetmap.org/#map=13/49.8647/36.9166

**Comment by bhousel** [comment]
Hey @illiapoint - this isn't something that iD has any control over.  The tile server will just re-render those tiles after some short delay.  You can also force the tiles to re-render by appending `/dirty` to the end of the url.  ([more info](https://help.openstreetmap.org/questions/1049/how-to-trigger-a-repaint-for-a-specific-osm-map-tile))
