### ISSUE TITLE
slaughterhouse preset

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4466]
https://wiki.openstreetmap.org/wiki/Tag:industrial%3Dslaughterhouse

**Comment by bhousel** [comment]
Ahhh another one where somebody put a building style feature with `landuse=industrial` 👎 

Can we change this before it gains traction?

**Comment by maraf24** [comment]
This tag is for large industrial slaughterhouse. There is nothing wrong with it. Should be used on area, not on a building. Kind of man_made=works.
For small slaughterhouses (ie. building) wiki allows to use shop=butcher.

**Comment by bhousel** [comment]
Ok, I see now that it's one of these: https://wiki.openstreetmap.org/wiki/Key:industrial

I guess there is no use complaining anymore about how none of these things are landuse.  We can support these presets in a way similar to what we had to do for the `landuse=military` ones.

**Comment by simonpoole** [comment]
Following the logic  here and in https://github.com/openstreetmap/iD/issues/3387 we can now really simplify the presets and remove all shop presets and replay with landuse=retail. I think that is a really good idea (not).

**Comment by bhousel** [comment]
> Following the logic here and in #3387 we can now really simplify the presets and remove all shop presets and replace them with landuse=retail. I think that is a really good idea (not).

I'm confident that if you make a wiki proposal and a handful of sockpuppet wiki accounts, you can get it "approved" 👍 😆
