### ISSUE TITLE
Add search term to tourism=alpine_hut

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4469]
https://github.com/openstreetmap/iD/blob/8bcd44618869828fa5381b43f554f422ac3afcaa/data/presets/presets/tourism/alpine_hut.json

- In the UK, "climbing hut" is what we would describe tourism=alpine_hut as. Can we add "climbing hut" as a term?
- ~~The address section is greyed-out (see screenshot) in iD, I understand that some won't have postal addresses but many do, can we fix this?~~
![alpine_hut](https://user-images.githubusercontent.com/20193716/31959983-3e1eb1b6-b8ee-11e7-914c-66d34b5b9aaa.PNG)

Edit: address issue just seemed to be a glitch - it's working now :)

**Comment by bhousel** [comment]
Sure, this is a good starter task..

- open `data/presets/presets/tourism/alpine_hut.json`
- add    ` "terms": [ "climbing hut" ],`  (can go anywhere but we usually put it before the `"tags"`)
- `npm run build`

**Comment by bhousel** [comment]
> Edit: address issue just seemed to be a glitch - it's working now :)

This happens when your connection to nominatim fails and iD doesn't know what kind of address field to show based on the part of the world that you are editing.
