### ISSUE TITLE
Don't disable spellchecking for Changeset Comments

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4471]
When entering a Changeset Comment, the user finds the browser's spellchecker has been disabled.
No matter Firefox or Chromium.

But spellchecking when filling in Profile Description on ```https://www.openstreetmap.org/user/<ME>/account``` works fine, So it must be an id problem.

**Comment by bhousel** [comment]
You are right, spellcheck is disabled.  I guess we could turn spellcheck back on for just the `comment` field..

Here are some attributes that we set on all of the `<input>` fields in iD.  (added to fix #3839)

https://github.com/openstreetmap/iD/blob/9c6c82d883d1b95ecd09c445ad3df3acc9f7556e/modules/util/util.js#L257-L263

**Comment by pnorman** [comment]
I'd turn on spellcheck for changeset `comment`, and object `name`, `note`, and `fixme`.
I recommend keeping the auto* stuff off for name, particularly autocapitalize.

**Comment by bhousel** [comment]
I ended up just turning spellcheck back on for all the `textarea` type fields ([see list](https://github.com/search?utf8=%E2%9C%93&q=textarea+repo%3Aopenstreetmap%2FiD+extension%3A.json+path%3Adata%2Fpresets%2Ffields&type=Code&ref=advsearch&l=&l=))

**Comment by jidanni** [comment]
Good.
