### ISSUE TITLE
Names of nodes and vertexes overlap each other

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4473]
When I was browsing an area in iD editor, something strange caught my eye. 

![overlapping id](https://user-images.githubusercontent.com/31667811/32045173-e386fd1e-ba3f-11e7-87eb-68dc223bca3a.png)

The names of a node and a vertex were overlapping each other. I refreshed the tab, but still the problem remained. This does not happen when a node and another node are close to each other. Is this by design of is it simply a bug?

**Comment by bhousel** [comment]
Definitely a bug - I have seen this before too, and I don't know the cause.

**Comment by bhousel** [comment]
For anyone who wants to investigate this, the code to produce the labels is
https://github.com/openstreetmap/iD/blob/master/modules/svg/labels.js

**Comment by darthgera123** [comment]
ill work on this issue
