### ISSUE TITLE
Wrong reference for highway=crossing

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4480]
The description and wiki link for `highway=crossing` is wrong: it describes `footway=crossing` instead.

Seems it should be `"key": "highway",` here:

https://github.com/openstreetmap/iD/blob/17c6842ce65185baf52baddc157e05e3dc1112cb/data/presets/presets/highway/crossing.json#L14

**Comment by bhousel** [comment]
Thanks for reporting, I just fixed the documentation links..
