### ISSUE TITLE
Option to disable "Zoom in to edit" (Feature request)

### ISSUE THREAD

**Issue by jaller94** [openstreetmap/iD#4482]
On my laptop screen the "Zoom in to edit" is way too prominent. While it might be a good introduction to new mappers, I find it to be a blocker. The fact that there are no editable elements on the screen when one is zoomed out is indication enough for me.

It blocks zooming in with the mouse wheel at the center of the displayed map.

### Expected behavior:
- The "Zoom in to edit" is permanently dismiss-able or can be turned of in the settings.
- The option gets saved in the browser's local storage or similar.

**Comment by bhousel** [comment]
Hey @jaller94, I agree that we can improve this - would it be ok if we just allow the wheel events to pass through the button to the map?  I'd prefer not to need to add special code for adding an option.

**Comment by jaller94** [comment]
Sounds like a useful change.
I understand that introducing settings is not trivial and I like the ease of getting started in iD. 👍

(I might locally hide it using custom CSS rules.)

**Comment by bborkmiller** [comment]
+1 for allowing wheel events to pass through the button.
