### ISSUE TITLE
Create preset for tourism=wilderness_hut

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4483]
Wiki: https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dwilderness_hut

Similar to tourism=alpine_hut but more remote and with less facilities.

- name: Wilderness Hut
- search terms: wilderness hut, backcountry hut, bothy
- name, operator and maybe address would be useful fields
- ele (elevation) and capacity could also be useful
- internet_access fields not needed

**Comment by bhousel** [comment]
Sounds good.. Someone can:
- copy `data/presets/presets/tourism/alpine_hut.json` to `data/presets/presets/tourism/wilderness_hut.json`
- change what's inside (e.g. the name, tag, and remove internet fields)
- `npm run build`
