### ISSUE TITLE
Change the preset for `place=square` to make it more placelike

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4486]
It affects pedestrian squares.

area=yes + highway=pedestrian is displayed as "Pedestrian Street".

iD allows to retag it to feature described as "square" with icon depicting walking human.

User may think that this is a correct edit.

Unfortunately it removes highway=pedestrian and replaces it with place=square.

Adding place=square  is not incorrect but removing highway=pedestrian damages data.

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/262667394/history is an example where user confused by what iD displays repeatedly removes highway=pedestrian (situation is made worse by communication problems).

The same user thought that he found tagging mistake and repeated the same type of edit across entire country.

**Comment by matkoniecz** [comment]
And how it may be fixed:

- display area=yes + highway=pedestrian + place=square object as "pedestrian square" (so newbies making iD edit will not repeat damage to places already tagged place=square)
- display area=yes + highway=pedestrian as "pedestrian square" (so people will not be convinced that they fix data issue)
- display place=square without highway=* without human in the icon (so people will not think that place=square means pedestrian square)
- changing pedestrian area to place=square is not removing highway=pedestrian/footway but only adding place=square

**Comment by matkoniecz** [comment]
And as a quick fix: give place=square higher priority than area=yes + highway=pedestrian, so area=yes + highway=pedestrian + place=square objects will be displayed as "Square" rather than "Pedestrian Street".

**Comment by bhousel** [comment]
Hmm, can't routers just route pedestrian traffic across `place=square`?  
It's not clear to me why iD should change anything.  Both tags seem like basically the same thing to me.

**Comment by manfredbrandl** [comment]
There is a difference between highway=pedestrian and place=square according to the wiki:
A highway=pedestrian is a road or an area mainly or exclusively for pedestrians in which some vehicle traffic may be authorized ...
The place=square tag ... ncludes all objects on the square, including streets, pedestrian areas, green areas, buildings ...
So while walking on all of the area of highway=pedestrian is allowed, that is not the case for place=square, because it may include streets and green areas.

**Comment by matkoniecz** [comment]
And, in addition even if place=square was equivalent to highway=pedestrian + area=yes it would be still wrong to replace tagging scheme with widespread support by a new, with low support. For example it would break most data consumers rendering squares.

In addition place=square was invented to tag entire square, not only walkable part - so meaning is different. Simplest case where entire square is walkable would be tagged with both highway + area + optional place tags. More complex one would be tagged with place=square on geometry including entire square - what may include roads, vegetation etc.

**Comment by bhousel** [comment]
Ok, I've thought about the solutions

> display area=yes + highway=pedestrian + place=square object as "pedestrian square" (so newbies making iD edit will not repeat damage to places already tagged place=square)

We could make this preset, but it wouldn't fix the issue of people changing the preset from one thing to another, and it would be not completely right if the `place=square` tag is supposed to encompass many things.

> display area=yes + highway=pedestrian as "pedestrian square" (so people will not be convinced that they fix data issue)

That also seems not completely right, as area pedestrian highways are often not "squares".

> display place=square without highway=* without human in the icon (so people will not think that place=square means pedestrian square)

☝️ this one is easy, so we can do it.  Hopefully just removing the icon will help.

> changing pedestrian area to place=square is not removing highway=pedestrian/footway but only adding place=square

I don't want to add special code to watch for changing one specific tag to another.. We don't have anything in iD like this currently.

**Comment by bhousel** [comment]
It would be great if the `place=*` tags were just point features for where people wanted their labels placed.

**Comment by matkoniecz** [comment]
One more idea: area=yes + highway=pedestrian is displayed as "Pedestrian Street area".

**Comment by Lee-Carre** [comment]
> It would be great if the `place=*` tags were just point features for where people wanted their labels placed.

That would be [mapping for the renderer](//wiki.openstreetmap.org/wiki/Tagging_for_the_renderer).

Data should be semantic (thus, tagging the area itself as `place=square`). If that yields sub-optimal rendering, then it is the renderer which should change.

Some software is quite smart about when & how labels are shown (OsmAnd comes to mind).
