### ISSUE TITLE
describe area=yes + highway=pedestrian as "Pedestrian Area".

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4488]
It would help to reduce editor confusion described in #4486 

Currently both highway=pedestrian and area=yes + highway=pedestrian is displayed as "Pedestrian Street".

I think that separate name for area would give better information to editor.

Hopefully it will not encourage new type of unwanted edit - at least I am not predicting anything new.

**Comment by bhousel** [comment]
Oh yeah, this makes sense to me..   
Is `highway=pedestrian` the only one type of "street" highway that is regularly tagged as an area?

**Comment by matkoniecz** [comment]
Good point, footway and service are also typical. Residential, track are among unexpected and suspect for me but appearing. 

https://taginfo.openstreetmap.org/tags/area=yes#combinations

**Comment by matkoniecz** [comment]
> Residential, track are among unexpected and suspect for me but appearing.

From very quick check - all highway=residential/track with area=yes look like mistaggings. I know that in rare situations this ragging is valid, but it is more commonly used incorrectly - where higway=service or area:highway should be used.

I recommend "Pedestrian Area" for highway=pedestrian/footway, and something for highway=service if it is possible to avoid confusing it with area:highway ("Service Road Area" for example would not work).

**Comment by bhousel** [comment]
Thanks for checking @matkoniecz ... I think we should just do this for Pedestrian Area.   Any closed `highway=footway` mapped with an `area=yes` tag can probably just as well be tagged as `highway=pedestrian`.  

Any _other_ closed highways with an `area=yes` tag are probably either mistakes or extreme outliers.  I also agree that "service road areas" are confusing.  If this becomes an accepted practice (like for toll plazas?), I'd prefer for the guidance to come from the folks working on routers.

**Comment by matkoniecz** [comment]
> Any other closed highways with an area=yes tag are probably either mistakes or extreme outliers.

I would argue that highway=service + area=yes valid tagging is relatively common

> I think we should just do this for Pedestrian Area

I agree, highway=service + area=yes has problem with missing good name and is unlikely to be retagged like described in #4486

**Comment by matkoniecz** [comment]
Thanks, hopefully it will be enough to discourage misstagging.
