### ISSUE TITLE
missing some office=* presets

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4489]
office=association --> https://wiki.openstreetmap.org/wiki/Tag:office=association
office=advertising_agency --> https://wiki.openstreetmap.org/wiki/Tag:office=advertising_agency
office=surveyor --> https://wiki.openstreetmap.org/wiki/Tag:office=surveyor

**Comment by abdeldjalil09** [comment]
https://wiki.openstreetmap.org/wiki/Tag:office=advertising_agency
https://wiki.openstreetmap.org/wiki/Tag:office=surveyor

**Comment by Nmargolis** [comment]
Hello! I submitted a PR for this (#4491)

While I was working on it, I noticed that several other office=* presets were missing as well (see below). Should there be a new issue for that or should I include them in the same PR? I'm a first time contributor so not sure what the process is.

Here are the other missing presets that are on the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:office):
- adoption_agency
- charity
- energy_supplier
- forestry
- foundation
- guide
- logistics
- moving_company
- notary
- private_investigator
- quango
- religion
- tax
- tax_advisor
- travel_agent
- water_utility

**Comment by abdeldjalil09** [comment]
We need also office=tax_advisor, office=quango , office=water_utility , office=forestry and office=foundation.
