### ISSUE TITLE
Flash message if user is trying to edit a shape that is connected to a hidden feature

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4493]
When I was trying to draw an area, suddenly iD didn't allow me to add new nodes to the area. 

![adding node impossible](https://user-images.githubusercontent.com/31667811/32239700-8e95178e-be6b-11e7-82e7-d0a7bd9165e3.gif)

Changing the zoom level or deconnecting (or even deleting) some nodes doesn't help either. The workaround is to create a new node and drag it onto the area outline in order to add a new vertex to the area.

I'm using **Mac OSX Yosemite 10.10.5** and **Firefox 56.0.2**.

**Comment by bhousel** [comment]
That seems like it should work, can you share the osm id of the object? 
You can open the measurement panel with  <kbd>⌘ Cmd</kbd>+<kbd>⇧ Shift</kbd>+<kbd>M</kbd>, and on there it will display the id (some long number starting with 'w').

**Comment by hikemaniac** [comment]
There are two problems. The first one is that I couldn't finish drawing the area because of this bug and so I didn't upload it to the OSM server. The second problem is that even if I would upload it I don't believe it would help, because refreshing the tab will allow me to add nodes again (after restoring the changes).

I have absolutely no idea what causes this bug but it might have something to do with the fact that I connected the area to other areas at several points. However it is not the first time I experience this. Please let me know if there are more things I can tell you to help fix it.

**Comment by bhousel** [comment]
Thanks @hikemaniac .. It looks like you might have connected your new area to an existing area that also serves as a boundary, and the boundary is hidden.

Can you try this:   
* Open the "Map Data" panel (or press <kbd>F</kbd>)
* Expand "Map Features" and make sure "Boundaries" is checked (so they become visible)
* See if you can now change the shape?

<img width="296" alt="screenshot 2017-11-01 14 34 42" src="https://user-images.githubusercontent.com/38784/32290997-276e1324-bf12-11e7-9271-47a973740796.png">

**Comment by hikemaniac** [comment]
Thanks a lot, this really was the cause of the problem (ironically it was actually the section paths which I had disabled for _less confusion_ when mapping the area). Maybe we could add some kind of warning when trying to join a node with a hidden object?

**Comment by bhousel** [comment]
> Thanks a lot, this really was the cause of the problem (ironically it was actually the section paths which I had disabled for less confusion when mapping the area). Maybe we could add some kind of warning when trying to join a node with a hidden object?

Good to know that was the issue!   I think we can probably find a way to flash a message to the user that the thing they are trying to do is blocked.  If you try to use the right click menu to edit this shape, you'll see that all the operations are disabled and the reason - but that doesn't help someone who is just trying to move nodes around.
