### ISSUE TITLE
Do not support disused/abandoned/demolished=yes in rendering

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#4501]
Hello,
usually, areas like buildings or landuses are rendered with a solid border in iD. But if you add tags like "disused=yes", "abandoned=yes" or "demolished=yes", the border's style changes to a dashed line. I think it would be a good idea to remove these style-changes to show that tags like "disused=yes" are not supported anymore, because they are deprecated. The new scheme is to use "disused:" etc. as lifecycle prefixes. Even though I know that "disused=yes" and others are still widely used, the wiki says all uses should be transferred into the actual scheme. Same problem exists where "disused" or similar things are in the value and not in the key, e. g. the deprecated "highway=abandoned" etc.

**Comment by matkoniecz** [comment]
Data consumers should not be expected to check for "proposed=yes", "demolished=yes", "construction=yes", "completely_fictional=yes" or "end_date=1990".

This like tagging prison as amenity=hotel  involuntary=yes.

**Comment by bhousel** [comment]
These tags you want to deprecate are used hundreds of thousands of times. Please feel free to retag these features and rewrite the wiki if you think that the tag should no longer be used.

Sorry but I'm getting kind of tired dealing with requests like this. Changing the editor presets is not going to change the data already existing in OSM.

> Data consumers should not be expected to check for "proposed=yes", "demolished=yes", "construction=yes", "completely_fictional=yes" or "end_date=1990".

iD is a data consumer too.  Believe me, if it were up to me, the tagging would look very different than it currently does.  😠

**Comment by matkoniecz** [comment]
> These tags you want to deprecate are used hundreds of thousands of times.

demolished=yes is currently below 1000 ( https://taginfo.openstreetmap.org/tags/demolished=yes ).

Is it enough to remove support for this tag?

**Comment by bhousel** [comment]
> Is it enough to remove support for this tag?

iD doesn't have a field encouraging people to use the tag.  We just render ephemeral features with a dashed line.  This isn't "support".

**Comment by matkoniecz** [comment]
So, is it enough to remove this special rendering for demolished=yes? Or is it necessary to reduce its usage further before doing that?

> This isn't "support".

I would consider using tag for rendering as support (as it suggests to user that using it makes sense), but it is not really important.

**Comment by bhousel** [comment]
> So, is it enough to remove this special rendering for demolished=yes? Or is it necessary to reduce its usage further before doing that?

iD can't currently do special rendering (or any kind of support, however you want to define it) for the prefix-style lifecycle tags, so I don't think it matters right now. 

In case you're curious, these are the status tags iD will recognize and render with an ephemeral style:

https://github.com/openstreetmap/iD/blob/d6eb1b3f3759c2690fdac220f9592226dd8b5527/modules/svg/tag_classes.js#L11-L14

You can look through the rest of the file to see how this array is used, but basically iD tries to understand all the various creative combinations of the legacy tagging:
* `railway=abandoned`
* `railway=rail` + `abandoned=yes`
* `railway=rail` + `abandoned=railway`
* `abandoned=railway`
* `highway=path` + `abandoned=railway`   (the abandoned railway tag is ignored here)

So it's not like we have special handling for `demolished=yes` - more like a bunch of clever code that just tries to handle all the legacy lifecycle tags and it does a pretty good job.  Removing `demolished` from that array is not going to make iD better.

**Comment by matkoniecz** [comment]
> Removing demolished from that array is not going to make iD better.

By rendering demolished=yes with ephemeral style it suggests that this tag is something that makes sense. I think that it is misleading to user.

It would make sense if demolished=yes was popular, but currently it is both horrible tag idea and with low popularity.

But I understand that iD may have different priorities/philosophy about how important is to discourage usage of poor tagging schemes (that is why I asked here rather than start from writing PR).

**Comment by bhousel** [comment]
> But I understand that iD may have different priorities/philosophy about how important is to discourage usage of poor tagging schemes (that is why I asked here rather than start from writing PR).

Yes, please don't send a PR.   I'm not sure that you even read what I wrote above.
