### ISSUE TITLE
remove natural=fell preset

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4502]
as part of https://github.com/gravitystorm/openstreetmap-carto/issues/545 I checked how natural=fell is used

> Actual use of the tag for areas as of October 2017 includes different kinds of treeless areas, in particular areas vegetated primarily by grasses (Poaceae) which are commonly tagged as natural=grassland or landuse=meadow, areas mostly vegetated by dwarf scrubs which are more commonly tagged natural=heath, rain fed peat producing wetlands for which the established tagging is natural=wetland + wetland=bog and areas with very little or no vegetation which in most cases qualify as natural=scree or natural=bare_rock. When mapping preferably choose the tag that best and most precisely describes the specific setting you are looking at. Data users should not expect a particular type of surface or vegetation for areas tagged natural=fell. 

from https://wiki.openstreetmap.org/wiki/Tag:natural%3Dfell appears to be a good description of the situation

Therefore I think that natural=fell usage should not be encouraged. fell may be added as search term for natural=grassland, landuse=meadow, natural=heath, natural=wetland, natural=scree or natural=bare_rock to help users find more specific tags.

It is request to partially revert #1818

matching JOSM report: https://josm.openstreetmap.de/ticket/15515#ticket

matching Vespucci report: https://github.com/simonpoole/beautified-JOSM-preset/issues/41

**Comment by bhousel** [comment]
It's used like 13,000 times.  Please feel free to retag these features and rewrite the wiki if you think that the tag should no longer be used.

Sorry but I'm getting kind of tired dealing with requests like this.  Changing the editor presets is not going to change the data already existing in OSM.

**Comment by matkoniecz** [comment]
> Changing the editor presets is not going to change the data already existing in OSM.

But it changes what is added to OSM.

> rewrite the wiki if you think that the tag should no longer be used

report mentions that wiki already documents this tag as a horrible idea

**Comment by bhousel** [comment]
> report mentions that wiki already documents this tag as a horrible idea

It doesn't say that at all.  It just looks like a normal wiki page with some suggestion that there is some overlap with other tags, which is not at all unusual.

**Comment by matkoniecz** [comment]
My understanding of the quoted wikipage was that this tag is can be always replaced by more precise and better defined one 

and 

>  Data users should not expect a particular type of surface or vegetation for areas tagged natural=fell. 

for me means "this tag carries nearly no useful information and therefore is a horrible idea".

**Comment by bhousel** [comment]
> for me means "this tag carries nearly no useful information and therefore is a horrible idea".

I agree with you, but...  
A horrible idea that's used a few hundred times is "a horrible idea". 
A horrible idea that's used tens of thousands of times is "an accepted tag".

The OSM community can change bad tags that are well established if they have the will to do so.  It takes somebody to raise the issue and coordinate a lot of mappers to do the cleanup.  See @joto's recent effort to retag [deprecated multipolygon tags](https://github.com/osmlab/fixing-polygons-in-osm) for a great example of how to do it.

**Comment by matkoniecz** [comment]
>  A horrible idea that's used tens of thousands of times is "an accepted tag".

I agree, but I think that editors are not obligated to support every accepted tag (see JOSM validator for extreme case that strongly discourages some tags).

I know that it is tricky to balance between "this editor promotes wrong tag and ignores community" and "this editor promotes tags on its own and ignores community", and no matter what will be done somebody will complain.

I consider dropping support in editors as part of fixing bad tags. But as you mentioned different people have different opinion how bad given tag is and how much wide usage justifies continued support.
