### ISSUE TITLE
Minimum/Maximum age in Playground

### ISSUE THREAD

**Issue by jbelien** [openstreetmap/iD#4506]
There is an issue with the "wizard" for `leisure=playground` : the fields "Maximum age" and "Minimum age" are both linked to tag `max_age` and change at the same time.

![image](https://user-images.githubusercontent.com/1150563/32447308-f8fea51e-c30b-11e7-889b-895f20104bbd.png)

You have to add manually `min_age` tag to have both tags !

**Comment by bhousel** [comment]
Thanks for fixing @JamesKingdom 👍
