### ISSUE TITLE
UX(?) somehow suggests to users to duplicate nodes in ways

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#4509]
This is the second example I've seen of this, so I thought I'd better mention it.  I've no idea what buttons the mapper pressed to do it, though.  

Problem is as described on this changeset: https://www.openstreetmap.org/changeset/52867263 .  It's a very new mapper.

Actual change is just 1 node delete from way http://osm.mapki.com/history/way.php?id=468933242 , but lots of others already there got added again (as per the history link).  I narrowed the problem down by looking at http://overpass-turbo.eu/s/sOJ and changing the time used.  

Apologies in advance if I'm pointing the finger in an entirely wrong direction, just wanted to provide a "heads up".

EDIT:  Here's the other example:

http://overpass-turbo.eu/s/sOK
http://osm.mapki.com/history/way.php?id=326651822
http://www.openstreetmap.org/changeset/53274991

**Comment by bhousel** [comment]
Thanks for reporting - we're tracking this on #4433 
We think it's created by something the user does when they move the feature.
