### ISSUE TITLE
preset for landuse=industrial+industrial=port, add landuse=port as unsearchable tag

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4511]
https://wiki.openstreetmap.org/wiki/Tag:industrial%3Dport
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dport

**Comment by bhousel** [comment]
You're asking us to deprecate `landuse=port` and replace it with `landuse=industrial + industrial=port`
Also, you just added the `industrial=port` wiki page this morning.

People on the `landuse=port` discussion page disagree with this change.

Please don't make suggestions like this.  `landuse=port` is fine and does not need to change.

**Comment by abdeldjalil09** [comment]
we don't have preset for landuse=port

**Comment by bhousel** [comment]
> we don't have preset for landuse=port

But we have landuse=harbour already

**Comment by abdeldjalil09** [comment]
> But we have landuse=harbour already
"landuse=port" is used for commercial traffic , but "landuse=harbour" is used for fishing,...etc

**Comment by bhousel** [comment]
https://wiki.openstreetmap.org/wiki/Harbour 
and
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dharbour

both suggest that they can be used interchangeably with `landuse=port`, which has fewer uses. 

Then.. if ports are for "commercial traffic" as you say, then `landuse=industrial + industrial=port` _really_ makes no sense.
