### ISSUE TITLE
Make the selected Mapillary/OpenStreetcam track and photo viewfield more visible 

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4512]
It's hard to tell which one is highlighted..

<img width="1015" alt="screenshot 2017-11-07 00 24 29" src="https://user-images.githubusercontent.com/38784/32497790-afb87b7e-c39b-11e7-92e1-ee12cec91ad7.png">

**Comment by mvexel** [comment]
One thought is to add a date filter to reduce the number of visible trips. Not sure how to do this in a user-friendly way however. We do it in the OSC JOSM plugin:

![osc-josm-filter](https://user-images.githubusercontent.com/120452/32613518-58151fb0-c528-11e7-8945-b6eac8b7e2de.gif)

**Comment by bhousel** [comment]
> One thought is to add a date filter to reduce the number of visible trips. Not sure how to do this in a user-friendly way however. We do it in the OSC JOSM plugin:

I like this idea and I think we will need to implement filtering at some point.. I'll open another ticket for it, since I won't have time to get it into iD this week..

**Comment by bhousel** [comment]
here are some things I changed:

- traces are the only thing drawn at low zoom 
- circles appear at z16
- viewfield cones appear at z18
- everything is drawn very dim by default
- hovering a marker will brighten that marker, the parent trace, and other markers along the trace
- the selected marker is drawn bright yellow and scaled up to be extra visible

I've played around with this and I'm pretty happy for something that can be released this week. 😄 


![streetview-usability](https://user-images.githubusercontent.com/38784/32618309-558f7ac0-c545-11e7-9722-65b1c88739ea.gif)

**Comment by bhousel** [comment]
Just merged!
