### ISSUE TITLE
leisure=playground preset 

### ISSUE THREAD

**Issue by Gumeg** [openstreetmap/iD#4515]
Hi. 
Dont know that is an issue, but find one error in preset for leisure=playground. I'm using a russian translation od iD. 
Fields for maximum age and minimum age change same tag - max_age=. So if you write in top field a number, it appear in bottom.
![image_2017-11-09_10-35-42](https://user-images.githubusercontent.com/16100614/32598487-f74931d0-c54a-11e7-91f4-18cff49e4437.png)

**Comment by lakedistrictOSM** [comment]
Reported and fixed in #4506 :)
