### ISSUE TITLE
layer=-1 not needed when tunnel=building_passage

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4516]
When editing a highway I can select tunnel from the Structure field and iD adds the tags `tunnel=yes` and `layer=-1`. When I change tunnel type to building passage `tunnel=yes` becomes `tunnel=building_passage` but the `layer=-1` tag is kept. 

![layers1](https://user-images.githubusercontent.com/20193716/32607363-a6c1db58-c550-11e7-9d35-fed088e868c1.png)

Is it possible to remove `layer=-1` for building passages since they tend to be at layer 0? Users can always add the layer if it isn't at 0. (taginfo shows that only 13% of building passages are combined with a layer tag)

**Comment by bhousel** [comment]
Yuck.. yeah we can do this.. Are there any other special `tunnel=*` values that work like this?

**Comment by lakedistrictOSM** [comment]
Not that I'm aware of.
