### ISSUE TITLE
describe amenity=toilets as "public toilets" not "toilets"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4520]
It seems at least some people create amenity=toilets for toilets without public access. 

I think that it may be a good idea to explicit describe amenity=toilets as public ones.

**Comment by bhousel** [comment]
There is an `access=*` field for this...

<img width="365" alt="screenshot 2017-11-10 15 36 55" src="https://user-images.githubusercontent.com/38784/32677626-2251dab6-c62d-11e7-8a58-d38bab25fafe.png">

**Comment by matkoniecz** [comment]
The problem is that amenity=toilets is not supposed to be used for private toilets...

**Comment by bhousel** [comment]
> The problem is that amenity=toilets is not supposed to be used for private toilets...

No, there is no "supposed to be" in OSM.  People add what they want to add.  If somebody wants to micromap their bathroom, that's cool.
