### ISSUE TITLE
Add field for advisory speed limit to link presets

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4522]
Advisory speed limits are typically posted on freeway ramps and tight curves on surface roads. They can coexist with legal speed limits, but at least in the U.S., freeway ramps have only advisory speed limits, not legal speed limits. [`maxspeed:advisory`](https://wiki.openstreetmap.org/wiki/Key:maxspeed:advisory) indicates the advisory speed limit of a way. The link way presets could have an “Advisory Speed Limit” field in addition to (or instead of?) the existing “Speed Limit” field. I don’t think it’s as important to add the field to the rest of the Highway presets, since mapping advisory speed limits on curves is another level of micromapping beyond mapping them on ramps.

**Comment by MaciejWWojcik** [comment]
@1ec5 Hi, can you provide some example of this maxspeed:advisory? I'm new here and don't know where should I start.

**Comment by 1ec5** [comment]
[This way](https://www.openstreetmap.org/way/19051632) is tagged `highway=motorway_link` `maxspeed:advisory=30 mph` (and not tagged `maxspeed`):

[![openstreetcam](https://user-images.githubusercontent.com/1231218/37245832-0a67ec72-2453-11e8-8a3f-3619da9c6362.png)](https://openstreetcam.org/details/1121191/264)

[This way](https://www.openstreetmap.org/way/528915276) is tagged `highway=trunk` `maxspeed=45 mph` `maxspeed:advisory=25 mph`. You can legally go 45&nbsp;mph, but that would be dangerous around this curve.

**Comment by bhousel** [comment]
This was done in #4870
