### ISSUE TITLE
Street-level imagery permalink does not update after switching images

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4526]
As of v2.5.0, the link at the bottom-right corner of the Mapillary or OpenStreetCam imagery panel no longer updates as you switch from one image to another. mapillary.com always links to the first Mapillary image you view, even after you switch tracks; the same goes for openstreetcam.org.

/cc @bhousel

**Comment by bhousel** [comment]
> As of v2.5.0, the link at the bottom-right corner of the Mapillary or OpenStreetCam imagery panel no longer updates as you switch from one image to another. mapillary.com always links to the first Mapillary image you view, even after you switch tracks; the same goes for openstreetcam.org.

Thanks for reporting @1ec5 - I do see this issue for the mapillary.com sitelink, but not the openstreetcam.org sitelink.  

Can you double check the openstreetcam case?  If so, can you let me know a location where you see openstreetcam traces doing this?

**Comment by 1ec5** [comment]
> Can you double check the openstreetcam case? If so, can you let me know a location where you see openstreetcam traces doing this?

I thought I was seeing this last night, but it isn’t happening now, so I may’ve been imagining things.

**Comment by bhousel** [comment]
> Can you double check the openstreetcam case? If so, can you let me know a location where you see openstreetcam traces doing this?

This issue got autoclosed by the commit that fixed the Mapillary attribution.  I think OpenStreetCam is ok, but let me know if it's not and I need to reopen.

(can check http://preview.ideditor.com/master/  to confirm fix for Mapillary)

**Comment by bhousel** [comment]
> I thought I was seeing this last night, but it isn’t happening now, so I may’ve been imagining things.

Thanks for checking!
