### ISSUE TITLE
OpenStreetCam imagery doesn't load on https

### ISSUE THREAD

**Issue by alexandrui-telenav** [openstreetmap/iD#4527]
Awesome OpenStreetCam integration!! Didn't work the first time I tried it as I was on https, it seems that the OSC requests are http therefore blocked. 

<img width="1282" alt="screen shot 2017-11-14 at 12 29 41" src="https://user-images.githubusercontent.com/17335176/32775243-92f1e63c-c937-11e7-948c-a10b4fe03c4b.png">

**Comment by bhousel** [comment]
Oh good catch @alexandrui-telenav  - Can the OpenStreetCam API serve data over `https`?  Browsers really don't like to load insecure content onto a page that was loaded securely.  cc @mvexel 

This is the same sort of issue as #4381, which was preventing the HOT task squares from loading over `http` if users were in Chrome and if iD was loaded with `https`.

**Comment by bhousel** [comment]
FYI,  I tested it out and everything seems fine over `https`, so I just made the switch
