### ISSUE TITLE
preset for railway=light_rail

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4528]
https://wiki.openstreetmap.org/wiki/Tag%3Arailway%3Dlight_rail

**Comment by bhousel** [comment]
For anyone who wants to work on this,
- [ ] copy `/data/presets/presets/railway/tram.json` to `/data/presets/presets/railway/light_rail.json`
- [ ] edit `light_rail.json`, change "name", "tags", "terms"
- [ ] `npm run build`

**Comment by bhousel** [comment]
done in #4531
