### ISSUE TITLE
Do not always include real filename or URL in imagery_used

### ISSUE THREAD

**Issue by poevak** [openstreetmap/iD#4530]
Pull request #4440, initiated by issue #4385, changed so that the real filenames of local GPX files were made public.

I think this is pretty terrible from a privacy point of view. It's not at all evident in the editor that the filename will be made public: the only way to see that it will is to expand all the tags and then hover over the sources field (the field is only wide enough to show the satellite imagery reference).

In essence, the user is tricked into submitting more information than he or she might have intended to. If we accept that, why stop at sneaky submission of just metadata when we could simply upload and make the entire trace public?

As the editor does not allow the user to edit the filename about to be submitted, despite the fact that the user could have set any filename before doing any edits, it is necessary to redo the edits should a sensitive filename have been accidentally set.

I love the simplicity of the iD editor, so adding options or extra editing fields doesn't seem like the best idea to me. Is there really any real value of including local filenames or unrecognized URLs?

**Comment by JamesKingdom** [comment]
Maybe we could include the URL if it is on OpenStreetMap, but just say "Local GPX" if it's uploaded?

**Comment by bhousel** [comment]
I changed the code to generate a string like '.gpx data file' or '.geojson data file' depending on the extension:


<img width="659" alt="screenshot 2017-11-15 11 44 51" src="https://user-images.githubusercontent.com/38784/32848467-994e65dc-c9fa-11e7-87d3-736ef2daaefe.png">

**Comment by jidanni** [comment]
Allow us to recall that there are **four** levels of
https://wiki.openstreetmap.org/wiki/Visibility_of_GPS_traces .
So some consideration of at least the people choosing **Identifiable** should be made...

**Comment by jidanni** [comment]
Why not have a question pop up:
> Are you extra sure that you want <del>your</del> that
(already public) trace to be listed on ...?
Click this checkbox and press confirm.
