### ISSUE TITLE
preset for man_made=monitoring_station

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4532]
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmonitoring_station

**Comment by abdeldjalil09** [comment]
Could anybody try to create a pull request ?

**Comment by bhousel** [comment]
> Could anybody try to create a pull request ?

Yes, anybody can!

**Comment by abdeldjalil09** [comment]
>Could anybody try to create a pull request ?
Yes, anybody can!

I know, I mean nobody want to create a pull request until now ?

**Comment by bhousel** [comment]
> I know, I mean nobody want to create a pull request until now ?

It is not polite to ask that question.. You can look at the Pull Requests and see what has been created, or create one yourself. 👍
