### ISSUE TITLE
If Mapillary image is still being processed, street level panel shows stale image

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4536]
[This image](https://www.mapillary.com/app/?lat=39.84004263999998&lng=-83.08723330999999&z=17) is currently being processed by Mapillary, so if you click on it [right around here](http://preview.ideditor.com/master/#background=Bing&map=19/39.83998/-83.08716), you get a thumbnail image (which I think is for the correct image) with oversized Mapillary branding overlays:

![thumbnail](https://user-images.githubusercontent.com/1231218/32914412-5d3ebd14-caca-11e7-9133-1fd2cb1b145f.png)

However, if you’ve already previously viewed a Mapillary image that has been processed, then that image shows up in the street level panel along with the current image’s attribution. As you flip through the images along the in-processing track, the street panel appears to be stuck.

**Comment by 1ec5** [comment]
The image that’s in processing hasn’t been joined up into a track yet, as you can see on the map canvas:

<img width="393" alt="no track" src="https://user-images.githubusercontent.com/1231218/32914532-be56fda0-caca-11e7-84af-c3c272cae105.png">

The images going westbound are already processed; the images going eastbound have not been processed and exhibit this bug.

**Comment by peterneubauer** [comment]
So, the creation of the vector tiles for the sequences is sometimes lagging as it is asynchroneous and depends on a lot of other processing going through. We are working on a status pages exhibiting the processing time etc, coming soon. Eventually this data will catch up as the system is catching up to the load right now.

**Comment by 1ec5** [comment]
Thanks @peterneubauer, I appreciate that there’s a significant amount of processing going on. Is there anything iD can do to make the images’ status clear? Currently you can only tell that the image is processing if you know to click on the mapillary.com link.

**Comment by bhousel** [comment]
Following some suggestions from @oscarlorentzon, this should avoid the problem where the viewer starts out bound to an imageKey that it can't actually move to.  Now we initialize the viewer with a null key, and issue `moveToKey` immediately.  This also adds some basic exception handling to `moveToKey`, which actually returns a promise and might fail.  In that case, we just quietly log a message to the console.
