### ISSUE TITLE
Pan map to the last deleted node

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4541]
When you delete a node of a way with a hot key, the map is panned to the next node. But when you delete one but the last node the map is not panned to the last node because the last one is deleted automatically.
It would be nice to still pan the map to the last node.

**Comment by bhousel** [comment]
I'm a bit confused, so just asking so I understand..

Deleting the 2nd to last node of a way will delete the way (because you can't have a 1 node way).  Are you asking that iD pan to the spot where the last node would have been?  I'm curious why this would be useful?

**Comment by yaugenka** [comment]
Yes, you understood it correctly. It would be usefull because
a) it does so for all but the last node, and when it stops at the 2nd to last node it is somewhat unexpected
b) if the last node is outside the view you don't known that is happening at the end

**Comment by bhousel** [comment]
Ah thanks for clarifying.. I had not considered the situation where the final node may be out of view.
