### ISSUE TITLE
No data visible in Firefox 56.0

### ISSUE THREAD

**Issue by DXCanas** [openstreetmap/iD#4542]
On Linux Mint 
In Firefox 56.0:
![image](https://user-images.githubusercontent.com/9877852/32985662-afd77862-cc74-11e7-8bde-544c7d6e0982.png)

In Chromium:
![image](https://user-images.githubusercontent.com/9877852/32985651-85f6a284-cc74-11e7-9c25-0f59d7f430e0.png)

No Apparent network failures:
![image](https://user-images.githubusercontent.com/9877852/32985666-cec96604-cc74-11e7-8bc5-a3db98a3e994.png)

Or Console Errors:
![image](https://user-images.githubusercontent.com/9877852/32985709-336a1298-cc75-11e7-865c-4c8414972a3a.png)

Disabled uBlockOrigin and Privacy Badger to no avail. Any ideas?
Thanks!

**Comment by hikemaniac** [comment]
It could be that the OpenStreetMap Data overlay is disabled. 

![osm data](https://user-images.githubusercontent.com/31667811/32994010-602bbaba-cd61-11e7-9f50-8cc3f7410cfe.gif)

**Comment by bhousel** [comment]
Sorry @DXCanas, I'm stumped.  If it's not the thing that @hikemaniac suggested above, maybe you could try:

- use a local dev environment or http://preview.ideditor.com/master/ (so you can debug)
- then step through with the debugger and see why `context.loadTiles` is either not getting called, or not completing.

**Comment by DXCanas** [comment]
Seems to have solved itself :man_shrugging:. I'm pretty sure that all layers were visible @hikemaniac, but I can't even reproduce myself now.

**Comment by bhousel** [comment]
Glad to hear things are working again!  It might have just been a temporary network issue...
