### ISSUE TITLE
Deleted GPS traces do not disappear

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4543]
I've recently removed some inaccurate GPS traces from <http://www.openstreetmap.org/traces>, but they still show up in iD. (In JOSM, they disappeared immediately.)

**Comment by bhousel** [comment]
ah yeah this is #2450
The gps traces are a raster overlay tile layer and it I don't know when it gets updated.  
The code for this gpx layer is in https://github.com/ericfischer/gpx-updater

**Comment by SelfishSeahorse** [comment]
Wouldn't it be possible to download the GPS traces directly instead?

**Comment by bhousel** [comment]
> Wouldn't it be possible to download the GPS traces directly instead?

See #2450 - it's currently too slow, and the API returns .  If it got some cgimap speedup, and an API call that returned gps traces as linestrings (instead of just points), we would probably use it.  It would be easy to add to iD in the same way that OpenStreetCam or Mapillary APIs currently work.
