### ISSUE TITLE
Change "Where does this imagery come from?" link

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4546]
The "Where does this imagery come from?" link is strange and confusing.  I think it would be good to give users a link to learn more about imagery.  But with the current design, the imagery overlay checkboxes are positioned as if they answer that question.

Q: "Where does this imagery come from?"
A: "Locator Overlay"
🙅‍♂️ 

<img width="288" alt="screenshot 2017-11-19 23 07 58" src="https://user-images.githubusercontent.com/38784/33001863-8c6de9a0-cd7e-11e7-96cc-d2324d9ed42d.png">

**Comment by manfredbrandl** [comment]
Maybe "Where does this background come from?" directly below "Background"?

**Comment by bhousel** [comment]
I made a few design changes so the pane content works better: 
- changed the sections to be expandable
- added more separation between sections
- reworded the link text


<img width="295" alt="screenshot 2018-01-03 15 19 28" src="https://user-images.githubusercontent.com/38784/34538240-aa2a96d0-f099-11e7-9e43-a23923b03fcc.png">
