### ISSUE TITLE
Don't autocomplete a longer value if the user has typed a shorter value

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4549]
When you type "water" tag it gets auto filled with "waterway". So you have to delete -"way" manually.
It would be better not to make any autotype suggestions for complete tags.

**Comment by bhousel** [comment]
Can you show me a screenshot of which field is doing this?
If it's the raw tag editor, what did you enter for the `key` ?

**Comment by bhousel** [comment]
If it's this - I don't know if we can change it.  The results are ordered by popularity.
Honestly, just deleting the "way" or using the downarrow to pick the one you want should be no big deal.

![water tag](https://user-images.githubusercontent.com/38784/33040796-2b4b0f0e-ce0a-11e7-9e8f-b48b0dcc4178.gif)

**Comment by yaugenka** [comment]
Yes, it is about this one.

**Comment by yaugenka** [comment]
Here is the full case which actually moved me to submit this ticket.

1. I type in "water"
2. Pressed Tab key
3. Started typing "la.." and was expecting to get "lake" in the dropdown but it did not come up
4. So I went back to the key field and was surprised to find out that there was "waterway" instead of "water" in there.

From then on when I type "water" I know that I have to wait for a second for the autofil to appear, delete it and only then press Tab key.

**Comment by jjiglesiasg** [comment]
Ever happen when you type Water, goes straight to Waterway

**Comment by bhousel** [comment]
I fixed this.

**Comment by yaugenka** [comment]
Awesome! Thank you, @bhousel

**Comment by 1ec5** [comment]
Yay, this makes it so much easier to enter `turn:*` tags! 😄
