### ISSUE TITLE
Polygons consisting of several long lines are not always filled properly

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4550]
See an example screenshot attached below.
It is taken from this place
http://www.openstreetmap.org/edit#map=16/53.1133/30.1565
and is about this polygon
http://www.openstreetmap.org/relation/7745393

The issue is not constanct. It happens only sometimes with one and the same object.
I have not managed to figure out the exact steps yet but decided to submit it case this can be understood from the code.
The only thing which I noticed it happens quite often after submitting edits.

![openstreetmap](https://user-images.githubusercontent.com/14937001/33044757-30ee4e5c-ce5b-11e7-8e6a-6622c1f081be.png)

**Comment by bhousel** [comment]
Yep, this is #1201.  iD can't render multipolygons correctly if they are only partially downloaded.  Fully downloading them might take a while, but might be something reasonable to do in a background task.  

_Most_ multipolygons are small, but it's the outliers with thousands of member ways that make this issue scary.
