### ISSUE TITLE
autocomplete prevents entering value with capital letter

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#4558]
When saving a changeset, and adding a Sources manually, if I try to add a custom value of "LPI Imagery", I do a SHIFT+L to get a capital `L`, iD changes this to lowercase `l` to match the completion `local_knowledge` as I continue to type with SHIFT down to get capitals it ends up with `lPI Imagery` rather than `LPI Imagery`.

My workaround is to type `lLPI Imagery` then go back and delete the first character.

**Comment by bhousel** [comment]
iD already had some code to support case sensitive combo fields, but it was only used to avoid autocompleting the user's changeset comment.  I just added an option for other fields to enable this behavior, and added it to the `source=*` field.  

Put another way, it means that now the combo won't try to "correct" the user's typing to be lowercase.
