### ISSUE TITLE
Add outer role to the way which is linked to a new multipolygon relation

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4562]
When you have a way selected, click New Relation in the relations section and define Multipolygon type. The new relation is created with the way linked to it but with no role defined.
It would be nice to automatically define outer role in this case.

**Comment by bhousel** [comment]
I think that's a little more "magic" than I'm comfortable with adding to the iD code.  I'd rather have people who are building multipolygons by hand to need to set the role themselves, rather than trying to guess what the user wants.  Sorry!
