### ISSUE TITLE
building boundaries misshape

### ISSUE THREAD

**Issue by Vadi** [openstreetmap/iD#4567]
Not sure if this issue is just location specific. Or else a bigger issue - almost all these areas are messed up.

![image](https://user-images.githubusercontent.com/218148/33240642-518f0dd0-d2df-11e7-90f6-963b14f6695a.png)

**Comment by bhousel** [comment]
It just looks like the imagery is not aligned properly, and captured "off nadir" (at an angle).

The building footprints looks like they are carefully traced, so you should use the "Background Imagery" pane to see if there is another source of imagery in that area that better matches the data... 

You can also choose the best imagery layer and manually offset it to match the existing data - scroll to the bottom of the imagery pane, and use the "Adjust Imagery Offset" widget to slide the imagery to a better offset.
