### ISSUE TITLE
Drop office=administrative

### ISSUE THREAD

**Issue by matthijsmelissen** [openstreetmap/iD#4578]
Would it be possible to drop the office=administrative preset?

The tag has been marked as 'discouraged' http://wiki.openstreetmap.org/wiki/Tag:office%3Dadministrative after a discussion on the tagging mailinglist and a vote on the wiki in 2016: http://wiki.openstreetmap.org/w/index.php?title=Proposed_features/Government_offices

The main issue was that the meaning of this tag is not clear. The tag is often used for offices of national or local governments, for which office=government is more explicit.

**Comment by bhousel** [comment]
Sounds good to me, thank you for linking to the relevant discussion about the tag 👍
