### ISSUE TITLE
Several broken things when editing a route relation that doubles back over a way

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4589]
Reported to me over the weekend - it looks like we have an issue with splitting ways that belong to route relations.  After they split, they don't all belong to the route relation.

This probably used to work and we changed it to work like this for Turn Restrictions.

(When splitting a way with a turn restriction, you only want one of the roads to keep the relation, but when splitting a road with other kind of relations, you want all of the surviving ways to belong to the relation).

**Comment by slhh** [comment]
> When splitting a way with a turn restriction, you only want one of the roads to keep the relation,

When spitting a way which is a `via` member, both ways need to become via members.

> but when splitting a road with other kind of relations, you want all of the surviving ways to belong to the relation

At least for PTv2 routes, the members do also need to have in the correct order.

**Comment by bhousel** [comment]
Gotcha @slhh that makes sense.. So I guess there are 3 cases of what to do when splitting a relation member:

1. (multipolygons, sites, and other random relations) - all surviving ways become members
2. (routes) - all surviving ways become members, but order must be preserved
3. (turn restrictions) - only the ways attached to the `via` node remain as members of the relation / special code to consider the case where the way being split is a `via` way.

(1 and 2 might be the same thing actually)

**Comment by bhousel** [comment]
I realized today that this issue isn't what I thought it was.
We currently handle all of the situations above and have tests for them.  

This particular issue only occurs when a road is split that belongs to a relation _several times_, which can happen often with routes.

<img width="754" alt="screenshot 2018-01-09 13 38 13" src="https://user-images.githubusercontent.com/38784/34736902-82168fca-f542-11e7-88b9-877d94808fb2.png">

**Comment by bhousel** [comment]
Need to fix:
- [ ] actionAddMember
- [ ] actionSplit
- [ ] osmJoinWays (maybe?)

**Comment by bhousel** [comment]
This was done 🎉
