### ISSUE TITLE
Displaying Retail Building in Building Sub Menu

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#4590]
Hello. Is there any way that "Retail Building" could be added to the Building Features drop down sub menu in the editor? Thanks.

**Comment by bhousel** [comment]
I just added this.. To disambiguate, I used a "suitcase" icon for Commercial buildings and landuse, and a "storefront"-looking icon for Retail buildings and landuse.

<img width="320" alt="screenshot 2017-12-05 11 37 35" src="https://user-images.githubusercontent.com/38784/33622275-683d8178-d9bb-11e7-98de-6fc8d0583368.png"><img width="320" alt="screenshot 2017-12-05 12 56 47" src="https://user-images.githubusercontent.com/38784/33622424-ca00999a-d9bb-11e7-8014-c662b03fb70b.png">

**Comment by Adamant36** [comment]
That totally works. Thank you
