### ISSUE TITLE
The close `X` for the photo viewer appears above the keyboard shortcuts screen

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4596]
Too much z-index!

<img width="659" alt="screenshot 2017-12-06 14 04 09" src="https://user-images.githubusercontent.com/38784/33680075-82f96de6-da8e-11e7-974d-17146694aa05.png">

**Comment by briandaviddavidson** [comment]
PR submitted: https://github.com/openstreetmap/iD/pull/4640

**Comment by bhousel** [comment]
This was done.
