### ISSUE TITLE
Add additional "X" to close side menus

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4599]
The Background Settings, Map Data, and Help side menus all need an additional "X" to
close them placed in their upper left corners: ![d](https://user-images.githubusercontent.com/1230959/33720519-2a4efd70-db9f-11e7-8364-b7a7af3aa015.jpg)

Else the user thinks he must click the same spot, now blue, on the
rightmost side of the screen, that he used to open them, to close them.

That spot is far away from where he intends to continue working.

Yes it is true he can click outside of the menus to close them, but he
does not know that.

I think this second way to close the menus does not violate
https://www.nngroup.com/articles/duplicate-links/
too badly.

**Comment by bhousel** [comment]
> Else the user thinks he must click the same spot, now blue, on the
> rightmost side of the screen, that he used to open them, to close them.

Yes, that is how to close them..  But I'm open to the idea of adding an 'X', since we use this design element everywhere else.

If I move the side toolbar down slightly, the 'X' could be in the upper right of the pane, which is how we position all the other close 'X's in iD - would this be ok?

**Comment by jidanni** [comment]
Sure... however the user's next stop with his mouse is definitely to the left, not the right. So deep down he will be "cussing" the designers for, after he has chosen a radio button etc. from the menu, making him have to go back right to close the menu.

**Comment by bhousel** [comment]
> So deep down he will be "cussing" the designers for, after he has chosen a radio button etc. from the menu, making him have to go back right to close the menu.

I'm ok with this.  Anyone who wants to work quickly can just toggle the menu with <kbd>B</kbd>.  We should probably bind <kbd>esc</kbd> to close the menu too.  Mousing will always be slower, no matter where we put the 'X'.

**Comment by jidanni** [comment]
ESC is good. B should be called b if you ask me, else what do you call real B. OK never mind that. Mainly his hand is already on the mouse, and the next thing he wants to do also involves the mouse. So he shouldn't be expected to have to "fire up" his other hand to hit ESC. But anyway by this time he probably has learned that just clicking the map will close the menu. But he fears side effects. Anyway, he wishes that clicking the fat white left margin of the menu would close it.

**Comment by slhh** [comment]
The user will likely become aware that a click on the map is sufficient, but adding the 'X' makes this more unlikely to discover.
Adding the X in its natural position (upper right corner) wouldn't be an benefit anyway.

Maybe, we can place the side menus on the right side of their buttons, and openstreetmap.org does already do so. I think this would reduce the required mouse movement.

**Comment by jidanni** [comment]
Also drop the white menu margins.

**Comment by bhousel** [comment]
> Also drop the white menu margins.

Done 👌 

<img width="200" alt="screenshot 2017-12-07 21 13 28" src="https://user-images.githubusercontent.com/38784/33747892-837e1770-db93-11e7-8ab4-59cb4c24da63.png">

**Comment by jidanni** [comment]
Thanks, but wouldn't users be more happy to see more map, and less
green, to the left of the word "Background"? I.e., does the menu need a
green margin on its left side at all? And trimming its right side too
could even show more map.

**Comment by manfredbrandl** [comment]
Please do not drop the white menu margin, it looks good (tm).

**Comment by bhousel** [comment]
After having used the sticky side panes for a little bit, I agree that having a close 'X' would be useful.  (removing the "considering" label)

**Comment by mmd-osm** [comment]
Currently, the icon bar interferes a bit with the scrollbar. Wouldn't it make sense to have a larger right margin for the help window, say 50px:

![grafik](https://user-images.githubusercontent.com/5842757/38086687-9d5d4458-3355-11e8-9677-d340522443bf.png)

**Comment by bhousel** [comment]
Thanks @mmd-osm I'll check these and see if we can improve it.

**Comment by bhousel** [comment]
Hey @mmd-osm  - I restored the padding at the bottom of the panes.. 
I'm going to leave the position of the pane alone for now because it's already designed to fit around the buttons.  It does cover the scrollbar sometimes, but the previous version of these panels did too.
