### ISSUE TITLE
Allow to straighten a selection of ways (rather than only one segment)

### ISSUE THREAD

**Issue by Martin868** [openstreetmap/iD#4600]
In my area, people have been adding lots of turn restrictions. This causes long ways to be fragmented and they cannot be merged, because of those relations. Consequently the use of the "Straignten" (the S key) function is now very limited. What would be very useful I think it is allow to use the S key on a selection. The user select a few ways and if they are connected then allow the use of the S key. In this case ID would align all the nodes, but keep the way's fragments separated. Should be easy I think, it is just lining up a bunch of points based on the coordinate of the last and first point in the selection. This would be very useful to tidy-up streets and that all crooked yet should be in a straight line.

**Comment by bhousel** [comment]
Oh yeah, I would love this feature too.  This is being tracked already on #2058

**Comment by Martin868** [comment]
Do you know if the is a plan to implement ?

**Comment by bhousel** [comment]
> Do you know if the is a plan to implement ?

No plan - go for it!
If nobody else does, I'll do it some day when I have some free time.
