### ISSUE TITLE
"Background" menu title not zoom compatible

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4601]
Older etc. users will have hit CTRL+++... to make everything bigger.
A big congratulations goes out to the ID designers for making everything zoom compatible.
However there is only one spot they missed:
![b](https://user-images.githubusercontent.com/1230959/33721998-a2aa4550-dba3-11e7-8636-2c15885b5ef8.jpg)

**Comment by bhousel** [comment]
haha, I did not notice that the brightness control was not responsive, but I think you'll be happy to know that thing is going away soon, see #4575
