### ISSUE TITLE
Select Line or Area or Point Not working very well

### ISSUE THREAD

**Issue by Sirvanalie** [openstreetmap/iD#4603]
In 2.5.1 ID Editor version , when I want to choice Line or any of 3 tools like area and point, should be click multiple to work well. I test it in Google chrome and Firefox Mozilla, but both of them, have this bug. In previous version, I did't see this bug. Please make a solution  for this bug, because really when decide to edit on big area, this bug annoyed . Also sometime when draw a line or area draw Don't working very well .Thanks

**Comment by bhousel** [comment]
Thanks for reporting - what operating system are you using?   This might be a dup of #4547

**Comment by Sirvanalie** [comment]
I use Windows , and my browsers are : Google chrome and Mozilla. In previous version I have't this problem. Please solve, because really important when you want to edit map, I must several time click to choice very well. Thanks.

**Comment by bhousel** [comment]
I believe this was fixed with the iD v2.6 release - please comment here if it's still an issue and we'll reopen, thanks! 👍
