### ISSUE TITLE
Click counter stays around if you interrupt that walkthrough step

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4605]
If you get to the part of the walkthrough where you are asked to "left click 5 times" and then you skip ahead to a different section, the click counter doesn't go away.

<img width="261" alt="screenshot 2017-12-08 14 13 48" src="https://user-images.githubusercontent.com/38784/33781441-a8bedb52-dc22-11e7-9839-569f59fddeb7.png">

**Comment by ajlomagno** [comment]
I've made a PR for this issue.
