### ISSUE TITLE
Cannot select a node of a selected line after detach

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4607]
It s not always possible to select a node of a selected line after you detach that node from another line.
![line_detatch](https://user-images.githubusercontent.com/14937001/33790667-2bf996ae-dc93-11e7-84c9-a53cae44efc8.gif)

**Comment by bhousel** [comment]
I agree this is frustrating.. I'm considering this same as #2206.  My plan is to separate the points a little bit to make it easier to select which one you want.

**Comment by shrddr** [comment]
This is not the same... #2206 talks about what node will be selected immediately after the Disconnect. Current issue is about selecting a specific point in a set of points which share the same location. Such set of points is not always a result of Disconnect. It could carry on from another editing session or even another user and different editor.

At some time in the past it was possible to select a specific point by selecting its parent way beforehand. You can see in the gif the user is trying to do so but fails. I don't know if this behavior was intended and documented somewhere; I discovered it by accident. So the question is why this functionality was dropped and if we can get it back.
