### ISSUE TITLE
Light bulb icon

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4609]
I hate this icon.  Let's replace it with a light bulb:  💡 

<img width="364" alt="screenshot 2017-12-11 17 48 07" src="https://user-images.githubusercontent.com/38784/33857854-7e4256c6-de9b-11e7-88bd-0f11b4178ba9.png">

**Comment by iandees** [comment]
🚿

**Comment by bhousel** [comment]
Better icon now for the `highway=street_lamp` preset!  💡 
Now if only we could get people to pick better type values.. "soddium" currently [in third place](https://taginfo.openstreetmap.org/keys/lamp_type#values) 🙄 

<img width="376" alt="screenshot 2018-01-02 11 54 18" src="https://user-images.githubusercontent.com/38784/34491993-b922f948-efb3-11e7-84f4-f5ef35a2e4a4.png">



Also I did this for the `amenity=shower` preset because why not.. 🚿 

<img width="373" alt="screenshot 2018-01-02 11 53 36" src="https://user-images.githubusercontent.com/38784/34491959-9806a872-efb3-11e7-8981-b37adad3d9a7.png">

(BTW.. "supervised"  🤔 - not really something I'm looking for when I take a shower, but ok OSM).

**Comment by JamesKingdom** [comment]
@bhousel This looks great :+1: 
Also for the shower preset, I guess if it's some sort of showerblock with somebody on the entrance?

**Comment by althio** [comment]
I guess the `was-streetlamp / now-shower` icon is too ambiguous anyway.
Maybe it should not be used for shower either. Something with drops instead of rays?
Some other ideas https://thenounproject.com/term/shower/1417864/

**Comment by althio** [comment]
About "soddium" currently in third place: [1 road, 5000+ soddium](https://overpass-turbo.eu/s/ubi)
