### ISSUE TITLE
Changeset Comment Field Locks Up Browser Tab

### ISSUE THREAD

**Issue by IcyMidnight** [openstreetmap/iD#4611]
When using the iD editor on www.openstreetmap.org in Chrome (Version 62.0.3202.94 (Official Build) (64-bit)), typing in the changeset comment field causes the tab to lock up. 

It sort of looks like iD is trying to autocomplete the comment from some history and does a *lot* of work on each key press. In one instance, I blindly typed a sentence or so of a comment and then had to wait 5+ minutes for the tab to revive and become responsive. Most of what I typed did finally show up.

Things seem to get worse with larger changesets.

**Comment by bhousel** [comment]
This is #4587 but I thought was fixed server-side.  @IcyMidnight is this still an issue?
Can you follow the steps on #4587 to check whether the slowness is in something iD is doing vs. a slow response from the OSM API?  Thanks!

**Comment by boothym** [comment]
Unfortunately I get the same thing, but I've only noticed it in larger changesets. Will try to figure out how many changes it takes to become really slow.

I looked at the response time for the XHR request but it's ~400ms in total.

**Comment by IcyMidnight** [comment]
Still seeing it today. It's not crazy, but I have a 35 change changeset where typing is already noticeable delayed.

**Comment by boothym** [comment]
Same as above, entering text in the changeset comment box gets noticeably slower even at around 30 changes. And when I had over 150 changes, entering text in a normal text field was slower as well.

**Comment by bborkmiller** [comment]
This might sound crazy, but my seat-of-the-pants impression is that the changeset comment slowness has more to do with how much panning I've done in the map than how many changes I've made. A relatively small changeset that covers a lot of ground, [like this one](https://www.openstreetmap.org/changeset/55695836), can slow down the comment field.

**Comment by bhousel** [comment]
My guess is that with every keystroke it rebuilds the entire sidebar, and the more changes you've made, the longer it takes to build the changeset summary.  D3 does funny stuff like that if we're not careful with our data joins and enter/update/exit selections.

**Comment by talllguy** [comment]
My workaround is to type the entire comment without seeing any of it show up, then change to another tab and write an email or something, then come back to find my comment has appeared. 😆

**Comment by bhousel** [comment]
Yeah, I feel bad I didn't get this fixed in time for today's 2.6.1 patch release.  Maybe next week 😄

**Comment by homersimpsons** [comment]
@tallguy or maybe you can write your comment elsewhere and then copy paste?

**Comment by bhousel** [comment]
This is much better now.
