### ISSUE TITLE
Allow fallback presets to appear in recently used list

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4612]
When you select some feature category it gets to the top of the list as frequently used which a very handy thing. Why not let the emply Line category behave the same way?

**Comment by bhousel** [comment]
We try to discourage people from adding untagged features, so those "fallback" presets always appear last in the list.

**Comment by yaugenka** [comment]
I agree that it is good to have it at the end of the list by default, but a user selects is from their, he knows what he is doing. We shoud also take into account that the frequently used list is reset everytime you reload the page. And finally you are warned about untagged lines when saving changes.

**Comment by manfredbrandl** [comment]
Could you describe the use case and what the benefit is?

**Comment by yaugenka** [comment]
Untagged lines are frequently used in relations for almost anything, e.g. landuse=forest, natural=water etc.
So you have to aways scroll down to get to that preset.

**Comment by bhousel** [comment]
Oh ok, thanks @yaugenka for the example.. I hadn't considered that people manually assembling multipolygons might want to do that.  

I'm ok with changing the behavior so that the fallback presets also go into the recently used list if the user picks them.
