### ISSUE TITLE
focus to changeset comment not obvious (enough)

### ISSUE THREAD

**Issue by althio** [openstreetmap/iD#4613]
I finished my edits. 
When I click "Save" the map greys out and the left panel becomes "Upload to OpenStreetMap".
Everything looks pretty grey and washed out. Now I wonder, did my click on "Save" was enough? What happens now?
![changesetcommentid](https://user-images.githubusercontent.com/9863567/33989296-41c82db4-e0c7-11e7-8cd0-ecd0a4051857.PNG)

The cursor moved automatically to the box "Changeset Comment" but it is not obvious enough to my taste. The mention "(required)" is very discrete. 

Writing a changeset comment is the next action.
I would like the box "Changeset Comment" with some highlight (color, fill, soft blink, ...) as long as the text is empty.

![changesetcommentidcolor](https://user-images.githubusercontent.com/9863567/33989817-2bfd728a-e0c9-11e7-8eee-d2c237f4a414.PNG)

ref: The only similar issue I could find is old https://github.com/openstreetmap/iD/issues/588

**Comment by bhousel** [comment]
This is a good suggestion, and a great thing for someone to work on who wants to contribute to iD.

There is some code in `changeset_editor.js` that checks the user's comment to see if they have mentioned Google and if so issues a warning.: https://github.com/openstreetmap/iD/blob/master/modules/ui/changeset_editor.js#L93

Someone could add code right before here that also checks the comment for content and adjusts the style of the comment field using d3's [selection#classed](https://github.com/d3/d3-selection.selection_classed) method.

**Comment by althio** [comment]
The Google warning is also good, could be reused if so inclined.
