### ISSUE TITLE
Standardize opening hours placeholder

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4614]
Viewing a petrol station as a point - we see that it says `Mo-Su 09:00-21:00, Mo-Sa 08:00-18:00…`
![](https://i.glideservers.com/u/jam9154e0b2-c8b4-46ef-b0d4-345930c3b778.png),

but viewing a petrol station as an area, comes up as `24/7, Mo-Sa 08:00-20:00, sunrise-sunset…`
![](https://i.glideservers.com/u/jamaa51c9b2-ed51-4d70-be37-d3ae9ac1fc7c.png)

I feel like this might be taken off taginfo, but I'm not sure.

**Comment by bhousel** [comment]
Yes this is expected - the dropdown will include the geometry of the feature when asking taginfo for common values.  So you will see slightly different results for points or areas.  

On the taginfo website, you can also change your queries to filter by nodes/ways/relations:

<img width="500" alt="screenshot 2017-12-15 14 18 51" src="https://user-images.githubusercontent.com/38784/34056931-0371046e-e1a3-11e7-9843-6fa07c426beb.png">
