### ISSUE TITLE
Typo in walkthrough

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#4616]
Extra "be" here: "They can **be** also be used for more detailed mapping of many features you might normally map as points."
https://github.com/openstreetmap/iD/blob/3440b5523c857e2c71be7c7829283530fe4274c7/data/core.yaml#L880

A pokemon go player raised this on reddit so good that someone is paying attention to the walkthrough 😛

**Comment by bhousel** [comment]
Thanks for reporting!  This is a bug that makes me happy.  👏

**Comment by joostschouppe** [comment]
The same issue is also in these files: https://github.com/openstreetmap/iD/blob/3440b5523c857e2c71be7c7829283530fe4274c7/dist/locales/en.json
https://github.com/openstreetmap/iD/blob/add1bac3f2e5e1bfa7f2eff422cb56fda4347ee3/dist/locales/en-GB.json

(I also came here after reading that PokemonGo thread :) )

**Comment by SeanBarber** [comment]
I am working on this.

**Comment by SeanBarber** [comment]
I have finished this task and submitted a pull request.

**Comment by JamesKingdom** [comment]
This was done #4620
