### ISSUE TITLE
Display date sat images were taken

### ISSUE THREAD

**Issue by pnoll1** [openstreetmap/iD#4619]
Satellite images give no indication of when they were taken.  This makes it hard to determine which imagery source is best to use for the current area.

The [Bing REST API](https://msdn.microsoft.com/en-us/library/ff701716.aspx) is able to provide this information so it's feasible for at least one provider.

**Comment by JamesKingdom** [comment]
This can already be done!
If you use `CTRL + SHIFT + B`, you can open the background panel, which looks like this:
![](https://i.glideservers.com/u/jam40468cb7-9347-44ed-b71c-1d9a1452719e.png).
Clicking `Show Tiles`, overlays the vintage, and looks like this.
![](https://i.glideservers.com/u/jam6252c05d-1174-4e3f-b5d9-d5074c7b87c5.jpg)
There are also other panel's available, such as history or location. You can view these by opening the help menu by using `?`, then selecting `tools`.

**Comment by bhousel** [comment]
Thanks @JamesKingdom for answering!

**Comment by pnoll1** [comment]
Thanks for the quick response!  This is exactly what I need.

Is there a better way to document this panel? A mention in the background settings near the imagery options seems appropriate. It's also not documented in the imagery help.

 You need to go to help > keyboard shortcuts > tools to find CTRL + SHIFT + B turns on the background panel and you can't tell what what the background panel does until you open it.
