### ISSUE TITLE
Car Parking with Park and Ride Checked, should give amenity=car_pooling

### ISSUE THREAD

**Issue by gregcrago** [openstreetmap/iD#4623]
When you select EDIT/AREA/(search)Car Parking/Park and Ride (checked)
It tags amenity=car_parking. It would be better to tag amenity=car_pooling

**Comment by bhousel** [comment]
For comparison:
Car Pooling:  https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_pooling (e.g. Uber)
Car Sharing: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_sharing (e.g. Zipcar)
Car Parking:  https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking

I don't think `amenity=car pooling` is quite the same as `amenity=parking + park_ride=*`
But I do think we could add presets for these other car sharing things.

**Comment by lakedistrictOSM** [comment]
`amenity=parking` + `park_ride=yes` does not equal `amenity=car_pooling`

A Park + Ride car park is where you can park your car then get some sort of public transport (eg bus/tram) to your destination (eg city centre/a big tourist attraction).

It would be good to see a preset for car sharing created though.

@bhousel Uber is more like a taxi service than a car pooling service (see http://www.bbc.co.uk/news/business-42423627 for recent news article)

**Comment by simonpoole** [comment]
@bhousel just to confirm what @lakedistrictOSM has said: P+R has nothing to do with car pooling at all.

**Comment by bhousel** [comment]
Sorry you are right - I thought `amenity=car_pooling` was for those ride sharing pickup spots at airports, but I guess not.

**Comment by gregcrago** [comment]
In my state, Michigan (USA). Park and Ride IS Car_pooling. It is an empty lot, usually next to a freeway and there is no public transportation. It is not Uber because if you have a car to drive to this parking lot, why would you pay to be transported elsewhere? It was designed to as a place to park and car_pool with another person to a common destination, like a workplace. That is why I think amenity=parking and park_ride=yes does mean amenity=car_pooling

**Comment by gregcrago** [comment]
In my state, Michigan (USA). Park and Ride IS Car_pooling. It is an empty lot, usually next to a freeway and there is no public transportation. It is not Uber because if you have a car to drive to this parking lot, why would you pay to be transported elsewhere? It was designed to as a place to park and car_pool with another person to a common destination, like a workplace. That is why I think amenity=parking and park_ride=yes does mean amenity=car_pooling

**Comment by gregcrago** [comment]
In my state, Michigan (USA). Park and Ride IS Car_pooling. It is an empty lot, usually next to a freeway and there is no public transportation. It is not Uber because if you have a car to drive to this parking lot, why would you pay to be transported elsewhere? It was designed to as a place to park and car_pool with another person to a common destination, like a workplace. That is why I think amenity=parking and park_ride=yes does mean amenity=car_pooling

**Comment by simonpoole** [comment]
well that is not clearly not a global interpretation (see for example https://en.wikipedia.org/wiki/Park_and_ride ) which doesn't mean that there shouldn't be a car pool... whatever preset, just that the P+R checkbox should not imply it.

**Comment by bhousel** [comment]
@gregcrago, I added a preset for `amenity=car_pooling`.. I am not going to change what the `park_ride` checkbox does at this time, since it seems to have a mostly well-defined meaning as a parking lot with connections to public transit.
