### ISSUE TITLE
Saving coastline change locks up browser

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#4626]
Problem using Firefox 52.5.1 (64-bit) on CentOS 7 and CentOS 6 when editing coastline.

With this setup I can edit most things with iD (still suffering from issue #4547 but the workaround fixes that).  However, I turned a short section of coastline into a quay (split at two points, select relevant portion, add man_made=quay and name="Cambrian Quay").  When I tried to save that, the uploading message appeared and never went away.  Periodically Firefox would tell me a script on the page was slowing down the browser and did I want to stop the script or wait.  Clicking "wait" every 10 seconds gets rather boring after several minutes.  I have, in the past, edited coastlines successfully.

Could this be something to do with the server-side changes mentioned in #4587?  Or a change in iD itself since the last time I successfully edited a coastline?

**Comment by bhousel** [comment]
Yeah this is #3056 / #4361

> I have, in the past, edited coastlines successfully.

☝️ I'm curious about this - can you remember how long in the past this was , and which coastlines?  I'm guessing it was either a long time ago (years) or a very simple coastline (e.g. not Japan/Germany).

**Comment by eehpcm** [comment]
Remember that long ago?  I don't even remember posting about the problem a few hours ago. :)

After wading through a lot of my changeset history (is there any way of getting at the changesets relevant to a particular feature in iD?), it was changeset 52279126 from 3 months ago using id 2.4.1.  At some point around that time I actually edited the section of coastline that today I tried to turn into a quay (back then I made the coastline conform more closely to the edge of the quay but it was only recently I found out the name of the quay and realized I could tag it as such).  Dunno if you'd consider the river Teifi at Cardigan in Wales complicated coastline or not.

**Comment by boothym** [comment]
Had a similar problem saving coastline recently. I wanted to redraw a section, so I split and deleted a line before adding a new line in its place. I gave it five minutes but it failed to save. 

It was part of the big Great Britain island relation: https://www.openstreetmap.org/relation/6038068 so maybe that was why? I don't know if I've done this procedure successfully in the past, but I have saved coastline successfully when just moving/creating new points on a line.

To get it to work I ended up having to save the changes.osc file and use JOSM to upload my changes. 
However not before I encountered the dreaded "no save button" issue #4606 - I pressed undo until I got it back, then redo to go all the way back to my last change.

A couple of times the save button disappeared again, so I pressed save when I had an untagged line and clicked on the warning - seemed to fix things which is strange!

**Comment by eehpcm** [comment]
I know this issue is closed, but just to let you know, 2.6.0 fixed this for me.  I've successfully added a named quay.  Anti-climactically, mapnik doesn't render the quay name, but at least I can map it.

**Comment by bhousel** [comment]
Wonderful, thanks for the update!  Glad to hear #4361 is better now..

**Comment by boothym** [comment]
Seems to have been fixed here as well, when editing coastline as described above. 👍
