### ISSUE TITLE
Area presets for closed ways

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4631]
Sometimes it is more comfortable to start drawing an area with a way rather than an area because at some point you may decide to include the way into a multypolygon or just because you know that any area is actually a closed way. So why not allow selecting area presets for closed ways?

It will also require adding Line, Barrier and Highway way presets to the area presets list because these closed ways are treated as linear features.

**Comment by bhousel** [comment]
This relates to #1828 

My advise for now is to just try to start out by drawing the kind of geometry that you intend for it to be, and if you want to change it later, edit the tags in the All Tags section.
