### ISSUE TITLE
Adding new language to name tag list

### ISSUE THREAD

**Issue by yt9tp** [openstreetmap/iD#4632]
While editing using iD I noticed there is language name tag name:sr-Latn missing. How can new language tags can be added?

I know how to add custom name tag for missing language and I do it that way but it is slow. I'd rather like have it on predefined list for easier and quicker use.

List offers "српски / srpski" which adds name:sr which designates Serbian Cyrillic but for Serbian map we also need name:sr-Latn which is for Serbian Latin (our language uses both scripts equally). Missing name:sr-Latn optin also causes confusion as sometimes we find people entering Latin script in name:sr tag.

Proposed change is:

remove current definition:

српски / srpski -> name:sr

add new definitions:

српски ћирилица / srpski ćirilica-> name:sr
српски латиница / srpski latinica -> name:sr-Latn

**Comment by bhousel** [comment]
Thanks for reporting @yt9tp - this is already tracked on #2457
The goal there is to use the CLDR project for our list of languages, instead of the wikipedia locales.
