### ISSUE TITLE
Notary Office is duplicated?

### ISSUE THREAD

**Issue by magol** [openstreetmap/iD#4634]
Is it any difference  between this:

- [office/lawyer/notary](https://github.com/openstreetmap/iD/blob/8720f7e6d7796046d158b3bc4a45fa3d74a1eaa6/data/presets.yaml#L4148) (office=lawyer, lawyer=notary)

- [office/notary](https://github.com/openstreetmap/iD/blob/8720f7e6d7796046d158b3bc4a45fa3d74a1eaa6/data/presets.yaml#L4167) (office=notary)

They is both called "Notary Office", but the description on the wiki differs slightly.

**Comment by bhousel** [comment]
Yes we discussed on https://github.com/openstreetmap/iD/pull/4491#commitcomment-25316574 but never resolved this.  I think the right thing to do is just remove the preset for `office=lawyer + lawyer=notary` and encourage users to use the other one.

**Comment by tyrasd** [comment]
FYI: I did some research for a recent issue on the `id-tagging-schema` repository, and I believe there actually is some difference between these tags. See https://github.com/openstreetmap/id-tagging-schema/issues/300#issuecomment-1014411051:

> in some countries (the using the common law system, i.e., UK, Ireland, US, Canada, Australia, New Zealand and perhaps a few others) there exist two different kinds of notaries: _notaries public_ and _civil law notaries_. In other countries (e.g., continental Europe) this distinction does not seem to exist (anymore).
