### ISSUE TITLE
Flyouts open simultaneously

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4635]
All three flyouts can be opened simultaneously, but the Help flyout stays on top:

<img src="https://user-images.githubusercontent.com/1231218/34408558-6c92ca42-eb79-11e7-9d90-642da03891b0.png" width="110" alt="flyout">

Reproduces in 6d9e028a562b230751e363cdabc69b45536ddf2d but not v2.5.1. In v2.5.1 and below, any open flyout would close automatically before another flyout would open.

**Comment by bhousel** [comment]
I think this is fixed already in 1780954, which will go with #4575
