### ISSUE TITLE
Add bus guideway preset

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4638]
![](https://i.glideservers.com/u/jam70ff04fb-6afd-4b08-9d9c-800033ff5dfa.png)
Bus guideways are rendered as blue lines, but currently have no preset in iD.
![](https://i.glideservers.com/u/jam5d47ffba-503d-44c4-8cd9-be410805e64a.png)

**Comment by bhousel** [comment]
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_guideway

**Comment by tordans** [comment]
For our convenience …
URL for Screenshot 1: http://www.openstreetmap.org/#map=19/51.11520/-0.16590
URL for Screenshot 2: http://www.openstreetmap.org/edit#map=19/51.11520/-0.16637

**Comment by prattheev** [comment]
@JamesKingdom I'll take this!

**Comment by bhousel** [comment]
@prattheev Do you need guidance to get started on this?
