### ISSUE TITLE
Pushing enter multiple times when uploading causes multiple changesets 

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4641]
![](https://i.imgur.com/epNDNPR.gif)
Everytime you push enter it creates a new copy of the objects you have changed, and makes the screen darker.
Here's the changeset list, all exactly the same
![](https://i.glideservers.com/u/jam92c6ad86-ab3b-460b-a59a-b702526f8c30.png)

**Comment by bhousel** [comment]
Whoa thanks @JamesKingdom for finding this!  We've noticed a few users have been able to do this before but we didn't know what was causing it..

cc @simonpoole @maxerickson
