### ISSUE TITLE
Surveillance camera with direction only visible in wireframe mode

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4642]
A standalone Surveillance Camera point tagged with `camera:direction` is completely invisible on the map. Selecting it doesn’t make it visible, although the feature editor does behave normally. Enabling wireframe mode makes the point visible.

Reproduced in be5929d4dcec805bce3cf4a18c9a230c764d97d2. This regression was likely introduced in #4602.

**Comment by bhousel** [comment]
Thanks for reporting - I'm having trouble reproducing this (have tried Chrome, Safari, and Firefox). 
Can you point me at a nodeid that is showing up invisible?

![surveillance camera](https://user-images.githubusercontent.com/38784/34485934-208685aa-ef9b-11e7-900c-49344225083b.gif)

**Comment by 1ec5** [comment]
I’m seeing this in both Firefox 56.0b12 and Safari 11 on macOS 10.12.6. Unfortunately, I don’t know of any actual surveillance cameras to save into the live database, but the issue seems to affect any point so tagged; it isn’t specific to a particular existing POI.

![hidden-camera](https://user-images.githubusercontent.com/1231218/34504375-2b704a68-efd3-11e7-9ec4-4886f24296b6.gif)

**Comment by 1ec5** [comment]
Not sure if it means anything, but when the point icon goes away, the group for the icon also disappears from the `layer-points-points` group.

**Comment by 1ec5** [comment]
Apparently this issue only reproduces at exactly z18, but not at z17.9 or z18.1.
