### ISSUE TITLE
Updated Bing Aerial does not align with maps in Langley, BC

### ISSUE THREAD

**Issue by disc12** [openstreetmap/iD#4649]
Something is totally off with Bing Aerial Maps in Langley, BC.  It is normally great, but I am noticing that developed areas are showing up only as rural farmland and vice-versa.  Meanwhile, mapbox satellite shows urban and rural areas correctly.  e.g. 200 St at 56 Ave in Langley is a fully developed urban, yet it shows up as trees and grassland in Bing Aerial  Plus the roads don't line up at all between Bing Aerial and Openstreetmaps in the same area of Langley..

**Comment by bhousel** [comment]
Sorry!  There isn't anything we can do about issues with Bing imagery. 

See this FAQ entry about how to report the issue to the Bing Maps team:
https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery
