### ISSUE TITLE
Replace Help icon

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4650]
The current icon ![image](https://user-images.githubusercontent.com/5360273/34513250-a63d85be-f067-11e7-9dfa-0118b2590bf1.png) is not very intuitiv, ![image](https://user-images.githubusercontent.com/5360273/34513367-3a48ce58-f068-11e7-8c34-357297cfa019.png) may be better.

**Comment by 1ec5** [comment]
A question mark would be much easier to spot when looking for help. However, an “?” icon is confusingly also used for the feature querying function on the main map at osm.org. openstreetmap/openstreetmap-website#1712 proposes changing that icon to a pointer arrow. #4651 proposes moving the button outside the map area, which would also make it less likely to be confused with the Query Features button.

**Comment by bhousel** [comment]
Agreed, we can do better - the current icon says "bookmark" to me.

**Comment by manfredbrandl** [comment]
There may be another possible icon: 
![img_1319](https://user-images.githubusercontent.com/5360273/34661852-ad9c6ad0-f44c-11e7-9e9a-d7bff9d9ecd6.PNG)

**Comment by althio** [comment]
The [`i`](https://github.com/openstreetmap/iD/issues/4650#issuecomment-355896743) icon is a good choice; Maybe not universal and quite western-centric (is there such thing as internationalization for icon?) but at least the use is consistent with other parts of iD.

**Comment by Mxdanger** [comment]
When looking at the "i" icon I think of information, not necessarily a button for help.

**Comment by althio** [comment]
This panel includes : Short documentation (called Help) + Keyboard shortcut reference + Walkthrough.

Also note that `i` icon is used on the main map at osm.org: for the map key.

**Comment by manfredbrandl** [comment]
@althio Do you have an idea for an icon to express the contents of this panel?

**Comment by althio** [comment]
> Do you have an idea for an icon to express the contents of this panel?

I prefer to give all kinds of ideas and let several people give their feedback.
So, caution: this is a unrestricted braindump :smile: 
all examples only for illlustrative purpose, CC-BY on https://thenounproject.com

theme | icon
--- | ---
Question | ![question_diamond](https://user-images.githubusercontent.com/9863567/35199308-a545817c-fefc-11e7-886e-19a417e991b5.png) ![question_bubble](https://user-images.githubusercontent.com/9863567/35199312-a5aee72a-fefc-11e7-826d-118dede25b28.png) ![question_dialog](https://user-images.githubusercontent.com/9863567/35199310-a57b9532-fefc-11e7-9d91-60f49d49a535.png)
Information | ![i_italic_on_black](https://user-images.githubusercontent.com/9863567/35199296-a42ee97c-fefc-11e7-9d09-ce0f8808b361.png) ![i_roman_on_black](https://user-images.githubusercontent.com/9863567/35199297-a4475336-fefc-11e7-83ab-746fdef4853c.png) ![i_roman](https://user-images.githubusercontent.com/9863567/35199298-a45ced54-fefc-11e7-9fda-4dbe74ebdc26.png) ![i_italic_on_black](https://user-images.githubusercontent.com/9863567/35199326-a70ec022-fefc-11e7-801a-3c1d832f36ac.png) ![i_roman_on_black](https://user-images.githubusercontent.com/9863567/35199327-a724c0de-fefc-11e7-9391-0e0667f5a371.png)
Documentation | ![book_title](https://user-images.githubusercontent.com/9863567/35199346-a976e542-fefc-11e7-884f-7a5b7f8d5a1e.png) ![book_title](https://user-images.githubusercontent.com/9863567/35199330-a76b03d2-fefc-11e7-84d7-d4aba64b84d0.png) ![book_title](https://user-images.githubusercontent.com/9863567/35199322-a6ad8cb2-fefc-11e7-83ac-50a4c085464d.png) ![book_bookmark](https://user-images.githubusercontent.com/9863567/35199313-a5c89558-fefc-11e7-857f-0411000d279c.png) ![book_bookmark](https://user-images.githubusercontent.com/9863567/35199315-a5f6e4b2-fefc-11e7-8a77-80960cc69e9e.png) ![book_gears](https://user-images.githubusercontent.com/9863567/35199316-a6120b52-fefc-11e7-8164-704f1e54def3.png) ![book_wrench](https://user-images.githubusercontent.com/9863567/35199336-a822fe2e-fefc-11e7-8bcf-11711287cc05.png) ![book_magnf_glass](https://user-images.githubusercontent.com/9863567/35199317-a627398c-fefc-11e7-98fe-114379629388.png) ![book_magnf_glass](https://user-images.githubusercontent.com/9863567/35199318-a63d9f38-fefc-11e7-96cf-51af28748750.png) ![book_magnf_glass](https://user-images.githubusercontent.com/9863567/35199292-a3d0222a-fefc-11e7-9ff4-93cec4718ffb.png) ![checklist](https://user-images.githubusercontent.com/9863567/35199323-a6c533d0-fefc-11e7-8b52-66649e68c0de.png) ![checklist](https://user-images.githubusercontent.com/9863567/35199351-a9fa8a50-fefc-11e7-9b5d-1c6619113d59.png)
Help | ![lifebuoy](https://user-images.githubusercontent.com/9863567/35199290-a3a44902-fefc-11e7-8f1e-4d335928cc4e.png) ![lifebuoy](https://user-images.githubusercontent.com/9863567/35199300-a4854c54-fefc-11e7-8f10-30307c0a2f22.png)
First-aid | ![first_aid_kit](https://user-images.githubusercontent.com/9863567/35199321-a694e3d8-fefc-11e7-9b01-a855c9af1bab.png) ![first_aid_kit](https://user-images.githubusercontent.com/9863567/35199334-a7cdb946-fefc-11e7-9dce-d4ff0f5f150e.png)
Inner workings | ![bubble_gears](https://user-images.githubusercontent.com/9863567/35199303-a4c69466-fefc-11e7-8d83-fc7d9333152a.png) ![bubble_gears](https://user-images.githubusercontent.com/9863567/35199304-a4ec9846-fefc-11e7-858f-e2f7e6b8f2ef.png) ![gears](https://user-images.githubusercontent.com/9863567/35199305-a50428da-fefc-11e7-9e71-de83830bef5c.png)
Directions | ![compass](https://user-images.githubusercontent.com/9863567/35199293-a3e66d96-fefc-11e7-9e04-c383bd2abd28.png) ![compass](https://user-images.githubusercontent.com/9863567/35199306-a51a162c-fefc-11e7-8a4a-f9a3889022be.png) ![signpost](https://user-images.githubusercontent.com/9863567/35199299-a4711676-fefc-11e7-8dd2-d2afd63569ba.png) ![signposts](https://user-images.githubusercontent.com/9863567/35199324-a6deb454-fefc-11e7-95a3-bb6bfcd61999.png) ![signpost](https://user-images.githubusercontent.com/9863567/35199325-a6f56cbc-fefc-11e7-877c-c5d50e320441.png)
Training | ![graduate_hat](https://user-images.githubusercontent.com/9863567/35199328-a73bbcf8-fefc-11e7-9f56-f5d42c34ec4e.png) ![book_graduate_hat](https://user-images.githubusercontent.com/9863567/35199337-a83db214-fefc-11e7-8a34-e3b94ffd4323.png) ![graduate_with_hat](https://user-images.githubusercontent.com/9863567/35199340-a8bed2cc-fefc-11e7-9347-d256e14ef4a1.png) ![desk](https://user-images.githubusercontent.com/9863567/35199342-a912613a-fefc-11e7-9f24-9a25dbcd97f9.png) ![human_board](https://user-images.githubusercontent.com/9863567/35199309-a562721e-fefc-11e7-9d5a-7ba08fd365f0.png) ![human_board](https://user-images.githubusercontent.com/9863567/35199311-a5959270-fefc-11e7-9743-784412f30275.png) ![human_board](https://user-images.githubusercontent.com/9863567/35199349-a9c55844-fefc-11e7-980b-4c3736474d61.png) ![board_white](https://user-images.githubusercontent.com/9863567/35199347-a99478e6-fefc-11e7-96ce-20e6a530c41e.png) ![board_black](https://user-images.githubusercontent.com/9863567/35199348-a9ac7a86-fefc-11e7-89cb-b1960f1ddfb5.png)
Welcome | ![human_invite](https://user-images.githubusercontent.com/9863567/35199331-a781e6ba-fefc-11e7-9bc3-4c97931a1f91.png) ![human_invite](https://user-images.githubusercontent.com/9863567/35199332-a79bf212-fefc-11e7-8aca-4ea71adc4ad7.png)
Start/play | ![play](https://user-images.githubusercontent.com/9863567/35199319-a6552efa-fefc-11e7-8ad3-8bfca2a0e6f9.png) ![play](https://user-images.githubusercontent.com/9863567/35199320-a67806f0-fefc-11e7-8dc8-f146e8c71e5a.png) ![play_gears](https://user-images.githubusercontent.com/9863567/35199344-a93f96aa-fefc-11e7-8f92-90c5c195a477.png) ![play](https://user-images.githubusercontent.com/9863567/35199345-a9568c70-fefc-11e7-9004-1ddb1672158c.png)

**Comment by bhousel** [comment]
I stretched out the book a bit, added depth, removed the unnecessary bookmark, and stuck a '?' on it.   I think it's better!

<img width="84" alt="screenshot 2018-01-29 16 38 11" src="https://user-images.githubusercontent.com/38784/35535916-218658a8-0513-11e8-9e2a-a70b9dd700b2.png">

**Comment by bhousel** [comment]
I also tried out a version with an `i`.  It's not bad, but as @althio pointed out, it's maybe a bit more Western-centric.  Also it bothered me that you need to click <kbd>H</kbd> to activate a thing with an `i` on it.

Did not do:
<img width="69" alt="screenshot 2018-01-29 16 35 59" src="https://user-images.githubusercontent.com/38784/35535962-51224e1e-0513-11e8-8d33-a0ff88234922.png">

**Comment by althio** [comment]
back to my comment about consistency:
In other places, an `i` icon is already used (mini-doc for features, with description from wiki). What do you think about changing them? How about the same `book+?` icon?

**Comment by manfredbrandl** [comment]
@bhousel I really like the book with the ? on top of it, seen it on preview. Much clearer now.
