### ISSUE TITLE
Possibility to refresh data without reloading the entire page

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4653]
Sometimes you might need to refresh map data. Pressing F5 reloads the entire page and resets your current settings which is not good. So it would be nice to have a possibility to refresh just the map view.
This feature will not be used often and some workarround solution would work here, but it should trigger validation of your unsaved changes. Low priority.

**Comment by yaugenka** [comment]
Considering user preferences are not reset at page refresh since v2.6.0, this ticket probably has no value any more.

**Comment by bhousel** [comment]
Thanks @yaugenka .. I agree, we can close
