### ISSUE TITLE
Self intersection prevention is too aggressive

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4655]
It seemed like a good idea, but we should disable it when drawing new features

![self-intersecting-bad](https://user-images.githubusercontent.com/38784/34584195-d1d494e0-f168-11e7-8c10-d3008ec359c3.gif)

**Comment by slhh** [comment]
I don't think we need to disable it, but a slight modification seems to be required:

- For a target placing a new node or connecting to an existing one exclude the closing edge from the intersection check.
- For a target finishing the area keep the full intersection check

**Comment by bhousel** [comment]
Good suggestion @slhh, I'll try that 👍
