### ISSUE TITLE
Remove construction=* when building (or highway, landuse, railway) is completed

### ISSUE THREAD

**Issue by alphensebezorger** [openstreetmap/iD#4659]
Many buildings under construction are tagged the old-fashioned way:
`building=construction` and `construction=house`, for a house for example. This is recognized by iD and shown as _House under construction_.

When the building is completed users often change _House under construction_ to _House_,
but this unfortunately doesn't remove the `construction=house` tag. The same problem could occur with highways, landuse and railways under construction.

Is it possible to check for such a 'phantom' `construction=*` tag when a `highway=*`, `building=*` etc. tag is changed from construction to another value, and remove it if present?

**Comment by bhousel** [comment]
#2341 would be to build a magic field that takes care of all this complicated stuff.
