### ISSUE TITLE
Flag double tags as error

### ISSUE THREAD

**Issue by mueschel** [openstreetmap/iD#4662]
It happens quite often that people add the same tag twice to a single object. The result are two tags:

key = value
key_1 = value

Can iD flag such a case as error if two keys are identical apart from a "_1" suffix and the values are identical?

**Comment by 1ec5** [comment]
#3625 would exclude already used keys from the autocompletion list, which would make this scenario less likely. Alternatively, perhaps we could automatically focus the existing tag if the user selects the existing key.

**Comment by bhousel** [comment]
Yeah I'm closing in favor of #3625, which will make it harder to enter the `_1` tags (which are not necessarily errors).
