### ISSUE TITLE
Totals on save warning can be confusing

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4666]
Reported in IRC today, a user was confused when they saw this screen.  They didn't understand why it said they deleted 214 features, but only made 69 changes.  I think we should add some detail to list of what actually got deleted, so that the numbers make more sense.  

The user was also worried that they did a bad thing and almost quit completely.  Maybe we can reword this warning to make it a bit less scary. 

![citbrjg](https://user-images.githubusercontent.com/38784/34673439-45f4d242-f450-11e7-8bb7-90e818e2de9e.png)

**Comment by manfredbrandl** [comment]
I also do not understand 69 changes versus 214 deleted features. Is it possible that a single delete operation counts for more than one deleted feature?

**Comment by 1ec5** [comment]
In the example above, the deleted water area probably contained 214 nodes or so.

**Comment by manfredbrandl** [comment]
Then it should read: "You are deleting 214 nodes, xx lines, yy areas, zz relations".
