### ISSUE TITLE
Automatic building tag is not obvious

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#4668]
Like in #4639, but now (also) for **marketplace**.

[![screenshot_2018-01-08_17-23-48](https://user-images.githubusercontent.com/4283376/34680236-bd78e1b2-f498-11e7-8b15-8a77e82701b8.png)](https://www.openstreetmap.org/changeset/47831051)
This should not have been a building.

**Comment by bhousel** [comment]
I think it was obvious in #4639, and I think it's still obvious here.

**Comment by M1dgard** [comment]
Sorry to nag, but apparently it's not so obvious for the user who made the mistake. This could still be improved, although I hate to admit that I don't know how either.

**Comment by M1dgard** [comment]
FWIW I think marketplaces are an example of where it should definitely default to no building. Those are very often in open air.

**Comment by althio** [comment]
@M1dgard 
> FWIW I think marketplaces are an example of where it should definitely default to no building. Those are very often in open air.

I agree. 
[Tag:amenity=marketplace](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmarketplace) reads 
> - for both of them (indoor and outdoor)
> - as an area along the outline of the marketplace
> - [add] building=yes - if it is a market hall

**Comment by althio** [comment]
this is related to issue https://github.com/openstreetmap/iD/issues/4559 PR https://github.com/openstreetmap/iD/pull/4568

@M1dgard do you think it can be closed?

**Comment by bhousel** [comment]
> this is related to issue #4559 PR #4568
> @M1dgard do you think it can be closed?

Yes, sorry, this was already done and is closed (thank you for linking to the PR - I should have done that originally!)
