### ISSUE TITLE
Rearrange Panels Entries in Panels Background and Map Data (e.g. new Panel Overlays)

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4677]
Overlays are now the second section of Background settings:
![image](https://user-images.githubusercontent.com/5360273/34777206-e0a69cb0-f619-11e7-88f9-0ed204b0ff16.png)
I think Oberlays should be in Map Data together with Photo and Traffic Sign Overlay as the bottommost section. Now one could (wrongly) assume, that the Overlays can be edited like the OpenStreetMap data:
![image](https://user-images.githubusercontent.com/5360273/34777325-4acc9afe-f61a-11e7-99fc-830ea3b27acc.png)

**Comment by bhousel** [comment]
Yes, I've thought about this too.. It does make some sense conceptually.
Let's mark this one as "considering" and think about it.

**Comment by althio** [comment]
I would expect:
- Background+overlays together
- Map data on its own, without the Photo overlays
(so this becomes: *Move Photo Overlays to Background*)

Or a breakdown since all panels get busy:
- Backgrounds
- Overlays (includes Photo overlays)
- Map data
(so this becomes: *Move all Overlays to a new button*)

**Comment by bhousel** [comment]
Another thing to consider is that #3742 would introduce some kind of support for vector tiled data.  Many of these transparent overlay layer would really make more sense as vector data.  And I see vector tiles as being more like map data that overlays the map.  

I'm ok with adding a button and moving stuff around if we're outgrowing the current split between Background/MapData .. (Map Data was originally called Foreground, which is why it has the <kbd>F</kbd> key shortcut).

**Comment by manfredbrandl** [comment]
Rethinking that I suggest to have Background, Map Data and Overlays (or Foreground). In Overlays there should be settings for all data above the map data which you use to improve the map as GPX-Traces, Street Level Fotos, OSM-Issues and other QA-Layers (maybe also from user defined source). Being able to edit OSM-Issues would be very good also.

**Comment by willemarcel** [comment]
I also would like to see everything in a single panel! A lot of times I have clicked in the background when I would like to activate the mapillary layers...

I would like to suggest to put the overlay/map data section above the Background section in the settings panel. As we have much more background layers than the other, I think a lot of users don't perceive the existence of overlays. Furthermore, as they are shown over the Background on the map, maybe it'd be more logical to have them in the top of the panel.

**Comment by manfredbrandl** [comment]
Having Overlays, Map Data and Background settings in this order from top to bottom seems logical to me.
Giving everything in a single Panel will be to crowded, e.g. with all world visible Oberlays has 7 entries (Locator, GPS, Tiger / Photo-Mappilary, Sign-Mappilary, Photo-OpenStreetCam, Local file) and more to come (QA-Layers e.g. issues), Map data has 16 entries (OSM-data, 3 x Fill Areas and 12 x Map Features), Background settings has 21 entries (16 x Backgrounds, 4 x Display Options and Adjust imagery offset).
This is 34 lines or more.
@willemarcel Did you suggest that or did i got it wrong?

**Comment by willemarcel** [comment]
@manfredbrandl Yes, I suggested that, but I recognize it'd be too crowded. Maybe we could have one panel just to activate/deactivate layers and another to all the settings related to them? I believe the users shouldn't have to think about what kind of information they want to add to the screen, so I would prioritize to have all of them together.

**Comment by manfredbrandl** [comment]
@willemarcel I don't think that separting Layer activation and Layer settings would help the users. In the Background Settings panel user should be able to select the background imagery and select options (brightness, etc.) for that background and also adjust the offset if neccesary. In the Map Data panel users should be able configure the OSM-data they can edit (Area Fill, activate/deactive Types of OSM-Data-Features). In the Overlay Panel the users should be able to select what to put on top of that for their specific editing needs (GPS-Traces, Tiger Roads, Street Photo and Traffic Sign or custom overlay, hopefully later also OSM-Notes and other QA-infos). If something gets changed here, good panel names and easily recogniceable icon will be important.

**Comment by manfredbrandl** [comment]
A year after opening the issue: Is there still someone considering a change in the panel entries?

**Comment by bhousel** [comment]
> A year after opening the issue: Is there still someone considering a change in the panel entries?

Nope.. I guess we can close as stale..
