### ISSUE TITLE
Remove building=yes from leisure=sports_centre

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4682]
These often include outdoor facilities such as pitches so adding the building tag is wrong. Wiki says to draw it around the grounds (https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dsports_centre)

**Comment by bhousel** [comment]
Good catch, thanks for flagging

**Comment by bhousel** [comment]
This was done 🎉
