### ISSUE TITLE
Create preset for "dry stone wall"

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4685]
https://wiki.openstreetmap.org/wiki/Tag:wall%3Ddry_stone
`barrier=wall` and `wall=dry_stone`
There are over 88,000 ways with this tag combination already, it would be a useful preset to have in iD.

**Comment by bhousel** [comment]
Even though it is common, let's not add presets for all the different kinds of walls.  We already have a generic Wall preset, and users can pick what kind of a wall it is.
