### ISSUE TITLE
users are forced to read the whole Help manual via the claustrophobic right side panel

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4686]
User is here
![nj](https://user-images.githubusercontent.com/1230959/34901855-4ef29fce-f84b-11e7-8efb-0afd959ff0da.jpg)
but cannot figure out how to read that page or the rest of the manual in fullscreen or a separate window.
In Facebook Help there is always a Permalink one can click.
Alas the user is forced to read the whole manual via the claustrophobic right side panel.
Allow users to also read Help in separate browser window.
Add "expand" links at the top and bottom of each Help page.

**Comment by bhousel** [comment]
There is likely nothing I could do to the design of the sidebar that would satisfy you, sorry.

**Comment by bhousel** [comment]
I made the pane a little bit bigger (50% or 600px vs 41% or 500px) in 44234ede6

**Comment by jidanni** [comment]
Let's say I want to tell a friend, say, about the Measurement Panel.
Well currently I have to [cobble up a description by hand](https://help.openstreetmap.org/questions/469/where-can-i-see-the-length-of-a-certain-way-element-in-the-osm-data?page=1&focusedAnswerId=71694#71694)

Now, if the iD editor was like Google Maps, each help page of the online manual would have a permalink one could share.

Then I could say "Try the Measurement Panel" and give the URL where the reader could see the

> Keyboard shortcuts
> BrowsingEditingTools
> Information
> Ctrl+I	Toggle all information panels
> Ctrl+Shift+B	Toggle background panel
> Ctrl+Shift+H	Toggle history panel
> Ctrl+Shift+L	Toggle location panel
> Ctrl+Shift+M	Toggle measurement panel

page of the manual.
