### ISSUE TITLE
Allow adding interstitial nodes to lines via right click menu too

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4687]
There is no easy way for users to add more details to lines, as the number of nodes is fixed unless the user is editing one of the ends of the line.

For instance say an existing 160 degree hairpin highway turn consisting of three nodes needs to have more detail added by adding two new nodes between the three. Alas there is no (two) clicks that can currently do that. Users unfortunately must resort to more complicated procedures to achieve the job.

**Comment by jidanni** [comment]
Oh I see, it is not on the right click menu like all the other operations, but is something one can directly left click to create (when a little + appears.)
So do consider also putting it on the right click menu for completeness.

**Comment by bhousel** [comment]
Take the tutorial, it covers this.
