### ISSUE TITLE
shop=wholesale

### ISSUE THREAD

**Issue by HubMiner** [openstreetmap/iD#4689]
This is continuation to: https://github.com/openstreetmap/iD/pull/4657

Per documentation: https://wiki.openstreetmap.org/wiki/Tag:shop%3Dwholesale
...at least first 3 stores listed in the example section (Costco, Sam's Club, BJ's Wholesale Club) should be updated, possibly same for "Makro" and "Real Canadian Superstore".  (Pricesmart is not mentioned in topNames.json)

```
OLD: shop/supermarket OR shop/department_store
NEW: shop=wholesale AND wholesale=supermarket
```
Note, some items are tagged as "amenity/fuel", those should not be changed.

Additionally, there are many name variations especially for Costco fuel station.  These probably should be normalized to "Costco Gasoline".

I could attempt this change with some hints.  :)

**Comment by 1ec5** [comment]
Hi @HubMiner, please take a look at the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index#what-to-edit) project and open a PR there. Once the PR lands, we’ll pull the change into iD. Thanks!

**Comment by HubMiner** [comment]
Thanks, reopened: https://github.com/osmlab/name-suggestion-index/issues/82
