### ISSUE TITLE
building=garages and landuse=garages have the same name

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4697]
The presets for `building=garages` and `landuse=garages` both have the same name, `Garages`, in iD.
Can we change the names of them to make it more clear which is a building and which is a landuse?

Maybe `building=garages` could be `Garage buildings`, `Garages building` or `Block of garages`?
`landuse=garages` isn't a tag I've ever used so I'm not sure what it should be renamed to.

**Comment by bhousel** [comment]
Thanks for flagging @lakedistrictOSM - they should definitely have 2 different names

**Comment by manfredbrandl** [comment]
I suggest "Garage area" for the landuse tag. Garage alone describes a building for me, but maybe we should change both to be very clear.

**Comment by lakedistrictOSM** [comment]
`building=garage` uses `Garage`.
