### ISSUE TITLE
Name and Elevation fields were useful for information=guidepost

### ISSUE THREAD

**Issue by martenjj** [openstreetmap/iD#4700]
Until about a month ago, the "Guidepost" preset, setting tourism=information and information=guidepost, had the Name and Elevation fields shown by default.  Having these shown was most useful, especially for the sort of guidepost that is mainly worth mapping - see for example http://www.swissvistas.com/image-files/mountain-trail.jpg and the equivalent for other countries.

Now the fields are hidden, and to show and fill them in needs lots more mouse actions.  Click "Add Field" dropdown, scroll to Elevation, click, click to place cursor, type elevation. Repeat for the name.

From my point of view having these fields shown by default would be more useful than "Operator"/"Reference" and the big "Turn Restrictions" field (see #3136).

**Comment by JamesKingdom** [comment]
I added these, now it looks like this:
![](https://i.glideservers.com/u/jamf10c0c00-cf84-4dc2-8fd6-bc0586ce0ac2.png)

**Comment by bhousel** [comment]
Thanks @JamesKingdom 👍

**Comment by martenjj** [comment]
Thanks for the quick fix!
