### ISSUE TITLE
Add barrier=kerb preset

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#4702]
Important tag for mobility handicapped persons.
https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkerb

**Comment by tordans** [comment]
Could it be, that this change also triggered the new rendering of `kerb` on the edit-map?

It now looks like this:
[Example](https://www.openstreetmap.org/edit#map=19/52.47697/13.45030)
<img width="832" alt="bildschirmfoto 2018-08-10 um 18 26 00" src="https://user-images.githubusercontent.com/111561/43969656-2891b07a-9ccb-11e8-90b4-d3aa7ce93e07.png">

Inside the park there are real barrier=fence tags.
But along the street thats all barrier=kerb.

Which used to look like soft gray line but now is this really bold thing demanding a lot of attention.
It might just be something I need to get used to. But just in case: Is there a way to change the rendering to a softer style? Eg. a different line-width?

**Comment by bhousel** [comment]
> But just in case: Is there a way to change the rendering to a softer style? Eg. a different line-width?

Yes, right now all the barriers just look like that.. 

We could eventually have different styles of rendering for different barriers.  It is great that people want to map this much detail, and tools like iD will need to deal with more data density.  

I've also thought about having certain features only render at much higher zoom (z20ish?).. Or maybe assigning a minZoom to each preset.  🤔
