### ISSUE TITLE
Stop Mapillary from autoplaying when the viewer is closed

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4707]
Autoplay in the Mapillary viewer is fun!   But if you close the viewer, it just keeps autoplaying and there is no way to stop it 😆 

![mapillary](https://user-images.githubusercontent.com/38784/35134098-3868a93c-fca2-11e7-980d-5b8c117970f9.gif)

You can even remove the layer completely, but that doesn't stop the autoplay either, it just continues driving you around on a mystery trip 🚌 

![mapillary2](https://user-images.githubusercontent.com/38784/35134109-54c5c40c-fca2-11e7-828f-e2f349475876.gif)

**Comment by iandees** [comment]
To be honest I kind of like this idea for a screensaver or something. A random, neverending walk down the OSM graph. 🤔
