### ISSUE TITLE
Add religion, denomination fields to school preset

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4722]
In some countries, it’s common for a school to be affiliated with a particular religious denomination. The `amenity=school` preset should have a fields for the `religion` and `denomination` tags, just like the `amenity=place_of_worship` preset. According to [taginfo](https://taginfo.openstreetmap.org/tags/amenity=school#combinations), these tags are only used in combination with `amenity=school` about 0.45% and 0.32% of the time, respectively; if that isn’t enough to justify showing the fields by default, then at least they could be optional fields.

These fields were previously suggested in #1663. Apparently this combination was uncommon back in 2013, though I’ve been using it since 2008. 🤷‍♂️

**Comment by naoliv** [comment]
Is it possible to restrict this to some countries only? (or maybe remove from some specific countries)
While there are some schools affiliated/related with a religion or religiouns organization in Brazil, they are the minority, for example.

**Comment by willemarcel** [comment]
Although in some countries the number of schools affiliated with a religion is really relevant, I think the default fields of a preset should be the ones that are more generic and apply for almost all cases. In my opinion, `denomination` and `religion` are not a must have field, so I would suggest it to be optional.

**Comment by 1ec5** [comment]
Sure, I originally proposed that they be optional fields up above. I think that’s reasonable because government or unaffiliated schools are common enough even in countries where religiously affiliated schools are the norm.

**Comment by 1ec5** [comment]
> In my opinion, `denomination` and `religion` are not a must have field, so I would suggest it to be optional.

I agree with @willemarcel that `denomination` and `religion` should be hidden by default for the school preset. Unfortunately, I just realized iD doesn’t support optional fields for specific presets, so I opened #4871 to get that feature added.
