### ISSUE TITLE
Worldwide search uses english instead of local german

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4725]
Only german here ("Radweg", "Anliegerstraße")
![image](https://user-images.githubusercontent.com/5360273/35223696-a091be62-ff82-11e7-8585-6a0227f806b6.png)
1 extra entries after "Worldwide search" in german ("Radweg"), two others in english ("Residential", "Cycleway")
![image](https://user-images.githubusercontent.com/5360273/35223742-d3aedfc8-ff82-11e7-8648-5e7015e3ccac.png)
Link: https://www.openstreetmap.org/edit#map=19/47.06286/15.44139

**Comment by bhousel** [comment]
I think I fixed this - can you check on http://preview.ideditor.com/master/  and confirm?  Thanks!

**Comment by manfredbrandl** [comment]
Checked (on my iPad :-)) and localisation works fine now. On one try the worldwide search did not show the "Radweg" (Cycle path) but I cannot reproduce.
