### ISSUE TITLE
Keyboard shortcuts / Editing: Disconnect and Split are missing

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4726]
I think Disconnect and Split are the only operations in the editing menu not in the keyboard shortcuts.

**Comment by bhousel** [comment]
You don't see something like this?

<img width="620" alt="screenshot 2018-01-22 11 06 08" src="https://user-images.githubusercontent.com/38784/35230583-717b3784-ff64-11e7-9b24-40e9a6709d61.png">

**Comment by manfredbrandl** [comment]
i was blind, sorry.

**Comment by bhousel** [comment]
> i was blind, sorry.

No problem! I was worried that something got missed in localizing this screen..
