### ISSUE TITLE
Ctrl-S no longer saving?

### ISSUE THREAD

**Issue by Fizzie41** [openstreetmap/iD#4728]
Hi. 

Did some mapping yesterday, but when I used Ctrl-S to open the "Save" page, it jumped directly to "My Documents" on my laptop & wanted to save file "OpenStreetMap", as a "Web Page, Complete"?

As recently as Sunday, Ctrl-S was working normally to open the Save page.

Using Windows 8.1 via Chrome if this makes any difference? 

Thanks

**Comment by bhousel** [comment]
Thanks for reporting, I'll check it out..

**Comment by geowOSM** [comment]
Same here on macOS 10.12.6 with Safari when using cmd+s

Thanks for the great update! 👍

**Comment by Fizzie41** [comment]
Thanks for that, but sorry, seems like it's not quite fixed as still having problems :-(

Noticed this yesterday & again just now when I tested it - appears that the first time you use Ctrl-S it opens the save page correctly. However, subsequent saves then, once again, try to save to My Documents? If you close that OSM session & open a new one, same thing occurs - first save is OK, subsequent are wrong?

**Comment by bhousel** [comment]
> Thanks for that, but sorry, seems like it's not quite fixed as still having problems :-(
> 
> Noticed this yesterday & again just now when I tested it - appears that the first time you use Ctrl-S it opens the save page correctly. However, subsequent saves then, once again, try to save to My Documents? If you close that OSM session & open a new one, same thing occurs - first save is OK, subsequent are wrong?

Yes, this is fixed in the iD source code, but the fix is not deployed to openstreetmap.org yet.  You can test the fix on our development site:  http://preview.ideditor.com/master/
