### ISSUE TITLE
addr:unit not used in Switzerland

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/iD#4729]
like https://github.com/openstreetmap/iD/pull/4667
addr:unit is nearly never used in addressing for Switzerland
5 addr:unit (seems all wrong) / 900 000 addr:housenumber
it should be hidden until a housenumber is filled or hidden if empty like for France.

**Comment by ENT8R** [comment]
Are you sure that it is actually shown for Switzerland?
In the code is no `unit` value set for the country codes `at, ch, de, si`: https://github.com/openstreetmap/iD/blob/6570365413fb6dd321ba3af09c5ba5e46db94c1d/data/address-formats.json#L27

**Comment by Marc-marc-marc** [comment]
you're right, I noticed the problem before the update that just happened.
addr:unit doesn't show anymore.
