### ISSUE TITLE
building:levels in french

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/iD#4730]
Current translation : étages (meaning : levels EXCEPT the ground level).
Therefore for building:level=1, several french-speaking mapper fill 0 because the building has "aucun étage" (no level except the ground level).
In word-for-word translation, levels is "niveaux" but putting only "niveaux" is not enough to understand exactly the field ("niveau" has a lot of use in french)
an understandable translation is "nombre de niveau(x)" or "nombre d'étage(s) y compris le rez".
I put this in a issue because I have a alert for the (x)
https://www.transifex.com/openstreetmap/id-editor/translate/#fr/presets/11327130?qt=%C3%A9tage&q=levels
it is working like that ?

**Comment by bhousel** [comment]
Interesting - yes I see the warning here:
https://www.transifex.com/openstreetmap/id-editor/translate/#fr/presets/11327130?q=level

>The translation does not contain the same number of parenthèses ouvrantes '(' as the original phrase

I think what you did is fine - the important thing is making sure the translated phrase is easily understood by novice mappers.

Transifex will sometimes issue warnings for other things that are not serious issues.  I've tried turning off the warnings, but for now it's safe to ignore them.

 
<img width="654" alt="screenshot 2018-01-22 21 50 31" src="https://user-images.githubusercontent.com/38784/35255723-6f680fa8-ffbe-11e7-84b0-31cc75408cf1.png">

**Comment by althio** [comment]
@Marc-marc-marc 
You can safely ignore some warning of Transifex if needed.

I don't think it is necessary in this case: I think simply `nombre de niveaux` is more correct.

**Comment by Marc-marc-marc** [comment]
@bhousel thanks.
@althio why not. I change it to "nombre de niveaux"
