### ISSUE TITLE
Cant Save Edits Due to Login Window Issue

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#4734]
After the update I'm having problems saving edits. When I first click the edit tab a new pop up window shows up asking for my login in details even though I am already signed in. If I put my details in again nothing happens. I can choose to ignore it though and go to the editor window anyway, but then once I try to save an edit, it will just come back up and not work again. It seems weird its asking me for my login details to save stuff since I'm already signed in. 
![error first sign on](https://user-images.githubusercontent.com/30259065/35262285-d44dd772-ffc8-11e7-84a4-91a393d857f4.jpg)

**Comment by bhousel** [comment]
Interesting! I notice from the screenshot that you’re in incognito mode.. does it work if you turn that off?

Incognito might disable localStorage, which is needed for auth to work. If that is the issue, we could probably find a workaround.

**Comment by Adamant36** [comment]
Thanks for the idea. It seems to be working normally now. So I don't know what the deal was. I think I will close the issue for now. If it happens again I'll try saving the edits in normal browsing mode though and reopen the issue if there is anything else to add. At least the problem is on the record now in case it happens to someone else I guess.
