### ISSUE TITLE
Error moving nodes of residential area in 2.6

### ISSUE THREAD

**Issue by alex11123** [openstreetmap/iD#4741]
https://www.openstreetmap.org/edit#map=18/50.92584/-2.30736  
Starting today I can no longer move nodes of a certain residential area (linked above). Other residential areas I can move nodes. When trying to edit it just shows a stop sign then snaps back on mouse button release.
Other users on the forum have confirmed the error is present for them as well. There is no obvious reason to block it being moved.
thanks in advance
chrome,windows 10

**Comment by bhousel** [comment]
I agree that it looks like a bug.. I'll try to see what might be causing the node move from being blocked.  As a workaround, you can hold down the <kbd>alt</kbd>/<kbd>option</kbd> key while moving nodes.

**Comment by bhousel** [comment]
I relaxed the check a little bit for multipolygon rings.. Now you only get the nope cursor when you try to drag an outer across an inner.. (It's hard to tell what is going on here, but the `outer` is a `landuse=residential` and the `inner` is a `landuse=retail`)

![multipolygon ring nope](https://user-images.githubusercontent.com/38784/35369843-2981eee6-0158-11e8-958a-f565995b6cf6.gif)

I tried to make a simpler version to demonstrate what was wrong, but iD won't let me 😆 

![multipolygon ring nope2](https://user-images.githubusercontent.com/38784/35369934-bceb6f4a-0158-11e8-8384-546f875b22a7.gif)
