### ISSUE TITLE
remove address-field from amenity=parking preset

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#4748]
I want to ask what do you think about removing the addr(ess)-field from the amenity=parking preset. The issue is that the addr-tagging-scheme is being provided explicitly for objects that do have a real address, so e. g. They have also a post box. Most parking areas do not have that. The addr-tagging-scheme is not to add a geographical reference like street reference, for that you have to use other schemes like ref:street or similar. The problem is, that for most parking areas people might be seduced to add a fictive address because of the preset. Of course, multi-storeys do have addresses sometimes, but surface parking areas do nearly never have and I'm very sure there are many more parking spaces without a real address than the opposite situation. And for parking buildings maybe it might be also worth to think about adding an own preset for parking=multi_storey, if you want to keep the address-field there(?)

**Comment by bhousel** [comment]
Seems fine to me - I agree that most parking lots probably don't have an address.  And for the ones that do, a user can always use the "Add field.." dropdown to add one.
