### ISSUE TITLE
Letter box

### ISSUE THREAD

**Issue by ghost** [openstreetmap/iD#4749]
I think [`amenity=letter_box`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dletter_box) would be nice to have as a preset. It's a fairly new tag, not really used a lot yet: [614 times](https://taginfo.openstreetmap.org/tags/amenity=letter_box).

**Comment by bhousel** [comment]
It would be nice to see if this actually catches on before we add it.  The `post:` addressing scheme makes this kind of difficult too.  We'd have to duplicate everything the address field does, but for another tag.

**Comment by bhousel** [comment]
stale
