### ISSUE TITLE
Up/down arrow keys in changeset comments are counterintuitive, can lose lots of typing

### ISSUE THREAD

**Issue by martenjj** [openstreetmap/iD#4750]
The changeset comment box is longer than one line and normally displays more than one line of text (assuming that the user enters a reasonably descriptive comment).  Therefore the user may expect that the up/down arrow keys have their normal browser meanings within the box, moving the cursor up or down one line.  However, they do not seem to do that - they bring up the next/previous history entries, as if the box were only a single line edit.

This can lose lots of typing if the user isn't aware of this and does:

Type a long changeset comment, which wraps over more than one line.
Notice a mistake near the start, type up-arrow to try to get back there.
All of the typed input disappears and the box is filled with a previous changeset comment.
There appears to be now no way to get back the typed text.

For less user confusion, if the control looks like a multi-line input field then it should work like one.

The same may apply (although I haven't dared try it, because it may send bad or incomplete OSM comments) to the Enter or Return key in this box.

**Comment by bhousel** [comment]
Good point. It's not very clear that the changeset comment field is also a dropdown.  I would also expect up/down to work like in any other `textarea`.
