### ISSUE TITLE
Create new presets for shop=wholesale and shop=health_food

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4754]
shop=wholesale (https://wiki.openstreetmap.org/wiki/Tag:shop%3Dwholesale)
- Name: Wholesale shop/store
- Terms: warehouse club, cash and carry
- Additional field: wholesale=* (https://wiki.openstreetmap.org/wiki/Key:wholesale)

shop=health_food (https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhealth_food)
- Name: Health food shop
- Terms: wholefood, vitamins, vegetarian, vegan

**Comment by bhousel** [comment]
This was done in #4773
