### ISSUE TITLE
"direction" for speed_camera preset

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#4757]
We are starting to see a possible misunderstading after iD started to render and offer a `direction` in the speed camera preset.

The `direction` here is where the speed camera is pointed to, and not the direction of the street that it applies.

The direction that speed cameras apply were always given by an `enforcement` relation, using the `from` → `to` members.

Even though iD clearly states that the direction is in degrees:
![](https://user-images.githubusercontent.com/982338/35576018-20975c96-05c5-11e8-86fa-3c48b47168a3.png)

People are inserting `forward`, `backward` or `both`, thinking that this value is related with the way/street direction (exactly like it happens with `highway=stop`)¹

¹ `highway=stop` has `direction=forward|backward` [specified in the wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstop) while `highway=speed_camera` [don't.](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera)

People are also thinking that "now it's easier to map a speed camera, since we can include the direction that it applies to, without using a relation" (which is wrong).

Could this somehow be improved?
Maybe make it clear that direction is the value where the object points to, and not the direction that it applies? (specially for speed cameras)
Using something like "Direction where it points" (or some better and shorter text) instead a simple "Direction" in the field?

**Comment by bhousel** [comment]
It doesn't look like the wiki has any guidance for adding a `direction=*` for `highway=speed_camera`, and it's not really clear from [taginfo combinations](https://taginfo.openstreetmap.org/tags/highway=speed_camera#combinations)

I'm not really sure what iD can do better here.  iD does already render the view cone in the direction that the camera points, and the field caption is not misleading.

Also..

> People are also thinking that "now it's easier to map a speed camera, since we can include the direction that it applies to, without using a relation" (which is wrong).

Why is that wrong?  It seems pretty ok to me.

**Comment by Lukas458** [comment]
> People are also thinking that "now it's easier to map a speed camera, since we can include the direction that it applies to, without using a relation" (which is wrong).

This is then wrong, if the highway=speed_camera-Node is not part of _one_ way (the way it belongs to). If the node is positioned next to the street, a relation is necessary. But whether this is also necessary if the node is part of the street, you can argue about that...

**Comment by bhousel** [comment]
Here's my understanding of how to map speed cameras, based on reading the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera).

- The `highway=speed_camera` node can go on the way, or as a standalone point next to the way.
- Mappers can add an `enforcement` relation, but this is optional  (wiki says "consider using...").  We won't support these in iD anytime soon.
- There is no guidance on how to tag the direction that a camera faces, but this is an obvious thing people will want to tag, so I made it work just like other kinds of directional features in OSM. 

Anyway I don't see anything immediately actionable to change here, and I don't see anything wrong with what iD is doing, so I'm going to close for now.  If there is overwhelming opposition to tagging the direction that these cameras face, I'll just remove the field.
