### ISSUE TITLE
Remove "site" relations from the presets

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#4758]
While there are [140529](https://overpass-turbo.eu/s/vBu) [type=site](https://wiki.openstreetmap.org/wiki/Relations/Proposed/Site) relations (with most of them from an import, it seems), it still has a proposed status and [some controversies](https://wiki.openstreetmap.org/wiki/Talk:Relations/Proposed/Site).

Maybe iD could still recognize the relation, but remove it from the "New relation" preset?
![](https://user-images.githubusercontent.com/982338/35578656-e7b1443a-05cb-11e8-968a-aa8d104165b1.png)

**Comment by bhousel** [comment]
Sorry, but I'm inclined to close this - Site Relations are a legitimate thing in OSM.  
I think if we stopped supporting everything with a controversy on its wiki talk page, we'd have a pretty empty map.

If you see Site Relations being misued, raise the issue with the DWG or on one of the OSM mailing lists for a group cleanup effort..
