### ISSUE TITLE
Add shop=agrarian preset

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#4775]
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dagrarian
Shop selling agricultural inputs.

**Comment by bhousel** [comment]
iD has this already - the preset is called "Agriculture Shop".
(maybe needs a better name?) 

<img width="545" alt="screenshot 2018-02-06 09 08 19" src="https://user-images.githubusercontent.com/38784/35863654-512b5ad0-0b1d-11e8-8b81-76725365d60a.png">

**Comment by lakedistrictOSM** [comment]
I'd call it "Agricultural Supplies Shop". This would be understood in the UK at least and probably translates across to other languages better too. I can't see any pesticides in that little picture so the wiki description could do with fixing.

**Comment by bhousel** [comment]
Can we just call it a "Farm Supply Shop" ?
(simple is better!)

**Comment by lakedistrictOSM** [comment]
Yes that sounds good! Or "Supplies" maybe. :)

**Comment by higa4** [comment]
Oh, sorry. I just found this preset already implemented. "Farm Supply Shop" looks good.
