### ISSUE TITLE
Unblind user on session restore

### ISSUE THREAD

**Issue by mikini** [openstreetmap/iD#4779]
I frequently find myself in situations where I edit on a location and iD detects that I have unsaved changes from a previous session and pops up the "restore unsaved changes from a previous editing session" dialog ([restore.heading text](https://github.com/openstreetmap/iD/blob/master/dist/locales/en.json#L574)).

I'm a tab hoarder and hesitant to save edits so I'm somewhat responsible for this situation myself. However, I'm often blind trying to identify what changes I've left dangfling. Only if the newly opened area is intersecting the area where the unsaved changes are present iD is able to give hints on what the changes are (by undoing/redoing which then moves map focus to undo/redo area). If the areas doesn't intersect it is not possible to find out what changes will be stored on saving.

Some ways to improve this:
1. List/inspect changes in restore dialog to aid in restore decision
1. Add feature to always focus map on relevant area on undo/redo
1. Add a generic textual representation of the undo buffer

**Comment by bhousel** [comment]
Thanks for reporting @mikini - this is being tracked on #3814
