### ISSUE TITLE
Fix Kurdish translation

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4783]
per https://github.com/openstreetmap/openstreetmap-website/pull/1413
It looks like our current translation `ku.json` should really be `ckb.json` to better match the osm.org website.  (`ku` should be written in Latin, `ckb` in Arabic)

Todo: 
- [x] Upload all of the `ku` translations to Transifex as `ckb`
- [x] Empty the `ku` translation so that people can translate it the other way

**Comment by 1ec5** [comment]
This is now consistent with wmf-sitematrix as well. 👍

**Comment by Ghybu** [comment]
@1ec5 @bhousel
Thanks. But for the "ku" or "ku-latn" code (Latin script ) the layout of the page must be in LTR and for the "ckb" code (Arabic script ) the layout must be in RTL.
Currently, it's the opposite.

**Comment by bhousel** [comment]
Oh thanks for flagging ... It looks wrong here, and this is a value that I expected Transifex to update for us:

https://github.com/openstreetmap/iD/blob/837b297ec61daf94e2a2de71a626edfaa4153b35/data/locales.json#L30-L32

**Comment by Ghybu** [comment]
Sorry to come back again and again on this topic :)

Line [126 / 127](https://github.com/openstreetmap/iD/blob/837b297ec61daf94e2a2de71a626edfaa4153b35/data/locales.json#L126) must also be modified. As I said above, actualy "ku" and "ku-latn" is in RTL. It should be in LTR.

Another thing: when I choose "ku" in "My preferences --> Preferred Languages". I don't see a translation in Kurdish. Normally "ku" and "ku-latn" should give the same thing.

**Comment by bhousel** [comment]
No apology needed, we want to get this right 👍 
If Transifex is returning the wrong thing for these languages, we'll just hardcode the correct thing in our `update_locales.js` script.  I have to investigate whether the result is wrong or whether there is an issue in our query.

https://github.com/openstreetmap/iD/blob/837b297ec61daf94e2a2de71a626edfaa4153b35/data/update_locales.js#L53-L55

**Comment by bhousel** [comment]
Transifex is indeed returning the opposite of what we expect:
```
12:20 $ curl -i -L -X GET https://www.transifex.com/api/2/language/ckb

{
    "rtl": false, 
    "pluralequation": "language.pluralequation", 
    "code": "ckb", 
    "name": "Central Kurdish", 
    "nplurals": 2
}

12:20 $ curl -i -L -X GET https://www.transifex.com/api/2/language/ku

{
    "rtl": true, 
    "pluralequation": "language.pluralequation", 
    "code": "ku", 
    "name": "Kurdish", 
    "nplurals": 2
}
```

**Comment by 1ec5** [comment]
For reference, CLDR defines [`ckb`’s script](https://www.unicode.org/cldr/charts/32/supplemental/languages_and_scripts.html#ckb) as Arabic and [`ku`’s script](https://www.unicode.org/cldr/charts/32/supplemental/languages_and_scripts.html#ku) as either Cyrillic or Latin (with Arabic being a non-primary script). CLDR also defines Arabic as being written [right-to-left](http://unicode.org/cldr/trac/browser/trunk/common/properties/scriptMetadata.txt#L69) as part of its script metadata. These files can be useful for discovering other special cases we may need to add.

**Comment by Ghybu** [comment]
Kurdish is written in Arabic script or in Latin. Cyrillic script is no longer used.

Concerning the CLDR, see these discussions:
-  http://unicode.org/cldr/trac/ticket/6527
- http://unicode.org/cldr/trac/ticket/9964
- http://unicode.org/cldr/trac/ticket/9748

See also (phabricator):
- https://phabricator.wikimedia.org/T48235

And (OSM wiki)
- https://wiki.openstreetmap.org/wiki/Talk:WikiProject_Iraq#Suggestions

**Comment by bhousel** [comment]
I opened an issue with Transifex support, and they're looking into the issue.  In the meantime, I just hardcoded the RTL/LTR values in 13789cc86 so we can close this out.
