### ISSUE TITLE
Save still not working in ID Indoor

### ISSUE THREAD

**Issue by billtheblindlion** [openstreetmap/iD#4786]
Reviewed #4780  & #4772 .  Author seemed to think https would solve problem of saving work in ID indoor.  I tried to find a link with https to no avail.  when I typed in the added s to http to make it https in the current url my browser said the page had a bad certificate.  How do I find the correct web site?

**Comment by bhousel** [comment]
Can you open your issue on their issue tracker instead?  It's not really something we can do anything about in this project.. Thanks!

https://git.framasoft.org/PanierAvide/iD-indoor

**Comment by billtheblindlion** [comment]
Bryan:  Thanks for your note.  I did open an issue on the ID-indoor site.  Thanks for the link pointing me in the right direction.  I am new to OpenStreetMap and there is a lot to learn.

Thanks again,

In Lionism,

Bill Graham

Every Day is a Great Day to be a LION!

**Comment by PanierAvide** [comment]
The issue is now solved (was related to https).
