### ISSUE TITLE
Add "Restore Defaults" button to the four sliders in Background Settings > Display Options

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4789]
In Background Settings > Display Options there are four sliders.

Each needs a "Restore Default" button.
And / or also a single button to restore all four's defaults.

And no, the user does not know what percentage is each's default.

**Comment by bhousel** [comment]
Each slider does have a reset button, and the buttons have "reset" as the hover text.. 
Maybe in this case an actual link with the word "reset" would be better?  This part of the UI isn't really constrained by space, so a link would be ok.

![background_control_reset](https://user-images.githubusercontent.com/38784/36100447-4c0462fc-0fd4-11e8-9005-cc503fa84f5c.gif)

**Comment by jidanni** [comment]
Ah, you are right again. I must never noticed those curved arrows.
OK. But there are still problems.
![gg](https://user-images.githubusercontent.com/1230959/36102233-b7222584-1046-11e8-903c-a116f904ef6f.jpg)
Here we observe Grandpa has increased the zoom. Causing in this view
1. Not sure if each curved arrow controls the item above, or below.
1. Slider bars slide underneath other elements.

**Comment by quincylvania** [comment]
#5503 was essentially this.
