### ISSUE TITLE
Make entire line of Background Settings layers clickable

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4790]
In Background Settings each layer is
```
O DigitalBird Deluxe Imagery
O Wiburston II Satellite
O NerdSpot National PhotoScope
```
I.e., a radio button, along with a name.

Well it takes a lot of work to aim the mouse right on top of and click the radio button. So why not make the entire line clickable?

**Comment by bhousel** [comment]
Yes, the whole line is supposed to be clickable - what browser are you using?

I see this in Chrome 64:
![background_radios](https://user-images.githubusercontent.com/38784/36100332-e2f04114-0fd3-11e8-8008-16b1d38614b3.gif)

**Comment by jidanni** [comment]
Oh I see.
It just looks like the legacy pure radio button experience.
