### ISSUE TITLE
Implement showing all GPS traces ever made in this area

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4792]
Wishlist item: Implement
https://wiki.openstreetmap.org/wiki/JOSM/Guide#Download_other_people.27s_traces
in iD.
The idea would be the user would click a menu item "see all GPS traces ever made through this area"
and the screen would then be full of all the purple GPS traces, and he could choose the majority path through them to plot out the trail he wishes to add.

Maybe there should be some checks, so that if the screen is zoomed out, showing the entire continent, he won't accidentally start trying to pull gigabytes through the network.

**Comment by bhousel** [comment]
Ah yeah, this is #2450
The OSM API doesn't actually provide a "get all GPX traces in a given bounding box" call, (like e.g. Mapillary/OpenStreetCam) which would make this a lot more doable without hacks / slowness.

I've also kind of considered this a less interesting thing to implement, hoping that we might get permission to use the Strava Heatmap instead (stuff moving on https://github.com/osmlab/editor-layer-index/pull/373), which is way better anyway.
