### ISSUE TITLE
Change API limit text

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4793]
https://github.com/openstreetmap/iD/blob/master/API.md states that `The OpenStreetMap API has a limitation of 50000 nodes per request.`, but it has been changed to 10k for a while, #3810

**Comment by bhousel** [comment]
@JamesKingdom can you revert this change?

There are 2 different limits:
- max changes per changeset, which has been reduced to 10k (#3810)
- max notes requested per /map call which still stands at 50k nodes ([see here](https://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_2))

**Comment by JamesKingdom** [comment]
Ah, sorry for my mistake.
I reverted this in 73f78c3622b949270758306c88910214aeb41d37

**Comment by mmd-osm** [comment]
> max changes per changeset upload, which has been reduced to 10k

The limit is really enforced on the level of a changeset, i.e. when uploading multiple changes for the same changeset, the remaining number of objects could be much smaller. I know this doesn’t affect iD, as the changeset gets closed right away.
