### ISSUE TITLE
Support adding select through URL parameter

### ISSUE THREAD

**Issue by baditaflorin** [openstreetmap/iD#4797]
Similar to JOSM's select Remote Control parameters.

Use case would be for example enabling MapRoulette to select the specific way feature based on the Task. This could assist human-driven validation, so they spend more time fixing errors, instead of wasting time to find the specific object, after it is loaded into the ID editor. 

> Comma-separated list of objects that should be selected. Object specifiers are combinations of the words "way", "node", or "relation", and the numerical object id. Example: select=way38473,node12399,node54646.
--
https://josm.openstreetmap.de/wiki/Help/RemoteControlCommand

In JOSM you can see the difference between the 2 in this usecase

Load this and then you usually have to zoom in one more time, remember what was the object that you are searching, identify it, click it and perform the required action that you need

127.0.0.1:8111/load_and_zoom?left=-97.3049318790436&right=-97.3014745116234&top=32.74209971246654&bottom=32.74066711397886&new_layer=false&changeset_comment=Maproulette%20challenge%20-%20remove%20name%20from%20highway%20links&select=

Compared to this, that will load the map, automatically select the object that you want, so you just have to perform the required action that you need. 

127.0.0.1:8111/load_and_zoom?left=-97.3049318790436&right=-97.3014745116234&top=32.74209971246654&bottom=32.74066711397886&new_layer=false&changeset_comment=Maproulette%20challenge%20-%20remove%20name%20from%20highway%20links&select=way419288222

I know this is a 1-3 seconds difference, but in MapRoulette, were users are expected to do this behavior hundreds of time, this will add up.  and this could mean either more free time to the user, or more fixes done in the same amount of time,

**Comment by bhousel** [comment]
Thanks!  yes this is #3645
