### ISSUE TITLE
'Edit custom background' should have pencil icon, not magnifying glass

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4798]
![gm](https://user-images.githubusercontent.com/1230959/36222628-e309cafa-11fc-11e8-9a3b-c78b22bc137b.jpg)
'Edit custom background' should have pencil icon, not magnifying glass.

**Comment by bhousel** [comment]
Haha yeah this has always bothered me too..

**Comment by manfredbrandl** [comment]
"Edit custom background URL template" would be better, because you cannot edit the custom  background with iD.
