### ISSUE TITLE
Custom Background: always only a northwest tile

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4800]
On https://gist.github.com/typebrook/a61ccca5b3d46f36784c120bf30c4236 I
read about
http://www.historygis.udd.gov.taipei/arcgis/rest/services/Urban/DEM_2014/MapServer/WMTS/tile/1.0.0//Urban_DEM_2014/default/GoogleMapsCompatible/{zoom}{y}/{x}.png
but when I use it as a Custom Background, all I see is the northwest tile.

No matter where I move the map, there is only a northwest tile.

**Comment by jidanni** [comment]
https://www.openstreetmap.org/edit#map=16/24.1772/120.8831

**Comment by bhousel** [comment]
Ah yeah, that gist has it wrong.

It should be http://www.historygis.udd.gov.taipei/arcgis/rest/services/Urban/DEM_2014/MapServer/WMTS/tile/1.0.0/Urban_DEM_2014/default/GoogleMapsCompatible/{zoom}/{y}/{x}.png


I figured this out by looking up the server here:
http://www.historygis.udd.gov.taipei/arcgis/rest/services/Urban/DEM_2014/MapServer

Then clicking WMTS to get the actual capabilities and look up the template for that TileMatrixSet:
http://www.historygis.udd.gov.taipei/arcgis/rest/services/Urban/DEM_2014/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

**Comment by jidanni** [comment]
Well I am having even less luck with your URL than mine.

Therefore please give me a link
```
www.some_WMTS_online_viewer.com/?...DEM...
```
where I can 'prove' that your URL works.
I have had too many accidents pasting into the tiny box.

**Comment by bhousel** [comment]
https://www.openstreetmap.org/edit#map=11/25.0901/121.6112&background=custom:http://www.historygis.udd.gov.taipei/arcgis/rest/services/Urban/DEM_2014/MapServer/WMTS/tile/1.0.0/Urban_DEM_2014/default/GoogleMapsCompatible/{zoom}/{y}/{x}.png

**Comment by typebrook** [comment]
@jidanni 
Fixed gist, looks like I made some wrong when copy/pasting. (Since image is available, means link string in markdown is correct)
Thanks for your remind! Also, if you know any tiles useful in Taiwan, please feel free to add comment in the gist!
