### ISSUE TITLE
Deprecated include of L.Mixin.Events

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4801]
Checking the Chromium Console I see:
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at b (https://www.openstreetmap.org/assets/application-f2e7e19….js:4:22889)
    at Function.f.extend (https://www.openstreetmap.org/assets/application-f2e7e19….js:5:3394)
    at https://www.openstreetmap.org/assets/application-f2e7e19….js:9:11365

**Comment by bhousel** [comment]
That's a warning about the Leaflet that they use on openstreetmap.org, not something in iD.

**Comment by jidanni** [comment]
https://github.com/Leaflet/Leaflet.draw/issues/775
