### ISSUE TITLE
Allow seeing the whole Custom Background URL one is entering

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4802]
Allow seeing the whole Custom Background URL one is entering, like JOSM.
JOSM has an entire huge box, but iD has just this tiny textbox which is never enough.
![gm](https://user-images.githubusercontent.com/1230959/36225661-5c5ae73c-1206-11e8-8fa8-7ad815c7d863.jpg)
One needs to see the whole thing one entered, so one can be totally sure. Even if one can poke around the various parts.
Never mind my blue highlighting in the image.

**Comment by bhousel** [comment]
What does it look like in JOSM?

**Comment by jidanni** [comment]
https://josm.openstreetmap.de/wiki/Help/Preferences/Imagery

**Comment by bhousel** [comment]
If we change this, we'd need to replace this `window.prompt` call with a new modal dialog box that can show a textfield.   ([`window.prompt`](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) can only do one line, and we don't have any options to customize it)

https://github.com/openstreetmap/iD/blob/73f78c3622b949270758306c88910214aeb41d37/modules/ui/background.js#L106-L109

**Comment by manfredbrandl** [comment]
If it is possible I would like iD to remember the custom URL templates for me.

**Comment by bhousel** [comment]
tagging @vershwal - this is kind of the same as #4806

**Comment by bhousel** [comment]
More context - this issue will be closed if we replace the `window.alert` box with a modal screen.  We'll be able to replace the single line input with an actual `textarea` that shows multiple lines.

**Comment by bhousel** [comment]
This was done in #5207
