### ISSUE TITLE
Mapillary photo overlay can't get disabled

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4804]
Hello

After enabling Mapillary photo overlay and later disabling them, the overlay doesn't disappear:

![untitled](https://user-images.githubusercontent.com/14875493/36251840-eabac1f0-1242-11e8-8f70-ef1984c35346.gif)

There is no problem with OpenStreetCam overlay, though.

As this misbehaviour is new, I suspect it has been introduced with the last update of iD.

Browser used: Safari 11.0.3 on macOS 10.12.6

**Comment by fritruc** [comment]
I found out that this bug was introduced in commit https://github.com/openstreetmap/iD/commit/f54d201eb2dd8e41c083fe0ebe7d67c44d95d236 
If I comment the 4 lines of this commit in master, the bug disapears.
Nonetheless, I don't know how to fix it yet =)
