### ISSUE TITLE
Replace alert box with modal ui

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4806]
Allow copying the example (switch...) in
![1](https://user-images.githubusercontent.com/1230959/36260649-0450b1ba-129d-11e8-9614-d3c2d74e1e6c.jpg)
in fact allow copying the whole thing.
As it is currently, the user can't even do Inspect Element on it.

**Comment by bhousel** [comment]
All the normal window stuff like select/copy/paste works fine here for me (in chrome 64)... What else have you tried?   Are you sure this is a real issue?

![copy alert text](https://user-images.githubusercontent.com/38784/36260978-ea2cbd90-1230-11e8-9831-62212da32a0a.gif)

**Comment by jidanni** [comment]
I can do like you in Firefox.
I can copy the text mentioned in
https://bugs.chromium.org/p/chromium/issues/detail?id=5879


But, with

Package: chromium
Version: 64.0.3282.119-2
Kernel: Linux 4.14.0-3-amd64 (SMP w/2 CPU cores)

the pointer remains an arrow over the entire box.
There is no right context menu.

**Comment by bhousel** [comment]
It sounds like a browser bug outside of our control. 

If we swap out the `window.prompt` for a custom modal, as described here, https://github.com/openstreetmap/iD/issues/4802#issuecomment-365741541 then we wouldn't be relying on the browser behavior and this issue would go away.

**Comment by jidanni** [comment]
OK submitted https://bugs.chromium.org/p/chromium/issues/detail?id=812644

**Comment by jidanni** [comment]
In https://bugs.chromium.org/p/chromium/issues/detail?id=812644#c6
they say
> Could you provide HTML+CSS for alter box?
> It seems user-select CSS property prevents to select contents in alter box
> except for text box.

**Comment by bhousel** [comment]
> In https://bugs.chromium.org/p/chromium/issues/detail?id=812644#c6
> they say

You can point them at http://preview.ideditor.com/master as an example..

`user-select` should not affect the selectability of text in a `window.prompt`, and I'm using Chrome and I don't see this issue, so it might just be Chrome on Linux that has the issue.

**Comment by bhousel** [comment]
Assigned to @vershwal

**Comment by bhousel** [comment]
This was done in #5207!
