### ISSUE TITLE
Incorrect displaying of map after changing

### ISSUE THREAD

**Issue by lujo777** [openstreetmap/iD#4811]
I've changed my community in iD. So, it was changes since 15.02.2018 16:00
So, when I open OSM (*not editor*) first time (today) I didn't see any changes, but I saw, in different scales you can see changes, but incorrectly. 

1st screenshot - Map in editor
![ashampoo_snap_2018 02 16_20h06m06s_001_](https://user-images.githubusercontent.com/34795882/36320569-b39db5a4-1357-11e8-867a-06b4b0ca1d4b.png)
2nd screenshot - Map after changes
![ashampoo_snap_2018 02 16_20h06m33s_002_](https://user-images.githubusercontent.com/34795882/36320570-b3bcefbe-1357-11e8-8513-67885876b962.png)
3d screenshot - Map after changes *in another scale*
![ashampoo_snap_2018 02 16_20h25m16s_003_](https://user-images.githubusercontent.com/34795882/36320568-b37c3794-1357-11e8-9403-1ba813c25686.png)

**Comment by bhousel** [comment]
Hi @lujo777 - first, thank you for your edits!

What you're seeing is expected.  The rendered map on openstreetmap.org might not display the latest edits right away.  It takes some time (usually a few minutes) to update, and this will happen differently at different zoom levels.  

The data that you see in the iD editor is the raw OSM data that is current as you navigate around the map.

https://wiki.openstreetmap.org/wiki/FAQ#I_have_just_made_some_changes_to_the_map._How_do_I_get_to_see_my_changes.3F

**Comment by lujo777** [comment]
So, when we can see full changes?

**Comment by bhousel** [comment]
> So, when we can see full changes?

I don't know - it's not related to this project.

The FAQ I linked to has some info, and that contains links to some longer explanations:
https://wiki.openstreetmap.org/wiki/FAQ#I_have_just_made_some_changes_to_the_map._How_do_I_get_to_see_my_changes.3F
