### ISSUE TITLE
support {header()} in Custom Background URLs

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4812]
Please see https://help.openstreetmap.org/answer_link/55381/ .

**Comment by jidanni** [comment]
Also
> Normally JOSM ignores any elements that it does not recognize. However, it will skip the entire imagery entry, when one of the unsupported tags has the attribute mandatory='true'.

So iD, instead of sending such {header()} etc. unknown elements  down the pipe, still hanging on to the back of the URL, should at least strip them...

**Comment by bhousel** [comment]
Unfortunately that's not really possible to adjust the referrer header from within a web application.  The browser sets it for us and we can't change it.  Sorry!

This also came up for discussion on #3420

**Comment by jidanni** [comment]
OK, but it "behooves" you to throw an error:
```
Dear User: you tried to use a directive that we did not understand or
cannot support, within your URL template.

Rather than sending your directive, still embedded in the URL
uninterpreted, to the server, which would be ** NEVER what your intended
** and indeed ** possibly quite embarrassing ** and just plain looks silly too, please instead clean up
your URL template.

```

**Comment by bhousel** [comment]
> OK, but it "behooves" you to throw an error:

Isn't raising errors about custom imagery covered in one of the other half dozen issues you just opened?

**Comment by jidanni** [comment]
I don't see any for "catch unsupported URL template directives (that
should never be sent raw)'
