### ISSUE TITLE
Don't let unknown WMS URL template directives sail through

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4813]
In #4812 we discussed what happens when the user uses an unknown WMS
URL template directive.

Let's take this example

```
http://a.b.c?xzzz{Header,Dont-Let-Larry-Know,Yes}
```

OK, we can't deal with the {Header} directive.

Shall we strip it, and send just

```
GET http://a.b.c?xzzz
```

No. That will let Larry know! Disaster.
The user will hunt you down for this.

Shall we do as we do now, and just let it sail through,
```
GET http://a.b.c?xzzz{Header,Dont-Let-Larry-Know,Yes}
```

No. We not only let Larry know, we let him know we didn't want to let
him know. Our user will doubly hunt you down, if Larry doesn't get him
first.

Indeed, that is just like when we know what ftp://x and http://y are,
but not irc://z . So irc://z must mean http://irc://z . That is about
how much little sense it makes.

So what should we do?

We should not let the request go over the wires in the first place.

Instead we should tell the user to fix thier t
print out an error message 
: E.g.,
```
({x}: good, no fixing needed.)
($x}: Dear user, try removing the $.
{x|y}:Dear user, try "," instead of "|".
{zoom}:Dear user, try {z} instead.
{Header}:Dear user, see #4812.
{norfoblitz}: Dear user, unknown directive "norfoblitz"
{zzz,m,n}{qqq,t,v} Dear user, unknown directive "zzz", unknown directive qqq",
```
or at least
```
($x}: Dear user, syntax error at $
{x|y}:Dear user, syntax error at |
{zoom}:Dear user, unknown or illegal directive "zoom"
{Header}:Dear user, unknown or illegal directive "Header"
{norfoblitz}: Dear user, unknown unknown or illegal directive "norfoblitz"...
```
Or just all "unknown or illegal directives used: ...."

**Comment by bhousel** [comment]
Sorry but I'm not going to validate every possible problem with a user typing in bad custom imagery template strings, or messing up pasting them.  We have a lot of other more important things to focus on in iD that have a larger impact on improving the editing experience.

The usecase is not "Larry typing random things into the box to try to figure out how it works".    It's someone who actually runs a tile server will give Larry a url to paste there.

You just have to get these custom imagery urls from someone who knows what they are doing.  You've opened up a lot of issues about the custom imagery dialog box recently, and it's really becoming a nuisance.  Please stop.

**Comment by jidanni** [comment]
I'm just saying if you get a {xyz} you can't convert, fail instead of
passing it through raw, which could never be correct.

If they really wanted to pass it through raw, there is a different
syntax for that, %7Bxyz%7D etc.
