### ISSUE TITLE
Make better use of post-upload dialog

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/iD#4815]
Currently there is a ton of white space in this dialog.

It could be used for linking to local community medium of contact (whatever has largest activity - OSM forum sub-board, FB group (like in Japan), external forum (for France)).

Country detection could be done either by some GeoJSON (like currently for driving direction) or reverse coding in Nominatim (which returns country code).

Other generic resources could be linked (on a rotating basis maybe?) as well.

**Comment by manfredbrandl** [comment]
> Currently there is a ton of white space in this dialog.
It could be used for linking to local community medium of contact (whatever has largest activity - OSM forum sub-board, FB group (like in Japan), external forum (for France)).

I agree. @RicoElectrico could you write an example, maybe for France but in English?

**Comment by bhousel** [comment]
This is a good idea.. I'm ok with updating the "success" screen to point a new user towards a local community that's active and friendly around where they are editing.  We could keep this list in a file under `data/`.

Also we should remove the sharing buttons.. This isn't 2013 anymore , and sharing your edit on Twitter, Facebook and G+ seems silly these days.

**Comment by SK53** [comment]
Very interesting idea. We do occasionally add something in welcoming changeset discussions when new mappers are clearly local and a monthly meeting is coming up. Would be interested in hearing what kind of link you might suggest is most appropriate, and how one might delineate the geography. For instance in UK there are meetings in Birmingham, London, Nottingham/Derby and Edinburgh/Central Belt, and it would be useful if these were the entry points for mappers close enough to those centres. In the East Midlands we are continuing to experiment with additional meeting locations, but people are interested in travelling a fair way if its convenient, so the actual boundary may need to vary over time. At present the only landing page is on the wiki.

**Comment by bhousel** [comment]
We're moving ahead with assembling an index of local community resources!

Anyone following this issue with ideas on the kinds of things that we want to track - please head over here to discuss:  https://github.com/osmlab/osm-community-index

**Comment by bhousel** [comment]
Rough mockup:

<img width="712" alt="screenshot 2018-03-13 12 57 45" src="https://user-images.githubusercontent.com/38784/37357379-af1a3e6a-26be-11e8-919d-13f66ef5eafa.png">

**Comment by bhousel** [comment]
> The, rather obvious issue with this, is the amount of power wielded by whoever gets to choose what is displayed. 

Yeah that is a fair concern - at least in iD it will just display whatever people have contributed to the index, with preference given to most local (smallest area) resources.  This is the similar to how iD presents background imagery sources from editor-imagery-index.

> And while "friendly" sounds nice, there is a well founded suspicion that it is an euphemism for "that we control and select",

In this case, friendly just means "friendly".  I'd prefer for the sources to be something that a new user (or someone with just a passing interest in mapping) would feel comfortable participating in.  For example, I wouldn't suggest someone's early exposure to OSM to be via the osmf-talk or tagging mailing lists. 

> @bhousel could you clarify who "we" is in "We're moving ahead"?

Me from iD, and whoever wants to contribute to  https://github.com/osmlab/osm-community-index
There is some interest in including the index in other tools like OSMCha .  You should add it to Vespucci, it will be fun 👍

**Comment by simonpoole** [comment]
From a technical pov the thing is we already have https://www.openstreetmap.org/help for such information I would prefer for that to be more dynamic  (as in location aware) and than more effort duplication (and @mmd-osm has already pointed yet another source out in https://github.com/osmlab/osm-community-index/issues/23).

**Comment by bhousel** [comment]
I just merged this!  I'm happy with how it turned out...
It uses the data from [osm-community-index](https://github.com/osmlab/osm-community-index).

Some features
* Social sharing options are gone (was: share your edit on Facebook, Twitter, Google+)
* Community resources are displayed from local to global
* Nice icons come from FontAwesome
* Each resource has a name, short description, and extended description (all available for translation)
* Each resource can include a list of which languages are spoken (currently displays language codes)
* Resources can optionally have events. If events exist, the next upcoming 2 will be shown.
* Events can have a name, description, where, when
* Events can optionally be translated (this would be more useful for a big event like a State of the Map)

Preview:
![community index demo](https://user-images.githubusercontent.com/38784/38476516-274041d8-3b7c-11e8-9add-da6e628eb7fe.gif)

**Comment by magol** [comment]
@bhousel 
Is there any other way to get this information, in addition to saving?

Especially beginners benefit from this information, and I think they want to ask the community BEFORE they save.

So, please, make the information available somewhere else, for example under help.
