### ISSUE TITLE
(German translation) "Furt" leads to mapping errors.

### ISSUE THREAD

**Issue by FountainMapper** [openstreetmap/iD#4821]
The dialog for a highway offers structure (in german "Struktur") with bridge, tunnel, ..., ford.
The german translation of "ford" is "Furt". This is translated correct. A "Furt" is related to water crossings, see here https://de.wikipedia.org/wiki/Furt
However, some mappers (at least 2 in my city, they use iD) misunderstand this. They mix it up with "Fußgängerfurt", see here https://www.duden.de/rechtschreibung/Fuszgaengerfurt
As a consequence the map highways with ford=yes. These highways are not close to water, but now they show "water crossing symbols" in the standard map.
We need a better, more precise translation here, maybe "Furt (Gewässerquerung)". Any ideas?

**Comment by manfredbrandl** [comment]
Thanks for the hint, i changed the translation according to your suggestion, it will appear soon in preview.ideditor.com/master and later in the next release. @FountainMapper Translations are managed using the Transifex platform, see https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating
@bhousel could you close that issue please?

**Comment by FountainMapper** [comment]
Tested with preview. Looks fine. Thanks

**Comment by bhousel** [comment]
Thanks for the quick fix @manfredbrandl!
