### ISSUE TITLE
landcover=trees is not rendered

### ISSUE THREAD

**Issue by CarlosBrys** [openstreetmap/iD#4824]
Please, consider render the areas tagged as landcover=trees.
This tag is useful to represent groups of urban trees and parks, but actually is not visible on the render.
Actually exist landuse=forest and natural=wood, but neither is applicable to urban areas. In the cities do not exist forestal explotations or woodlands.

**Comment by manfredbrandl** [comment]
Do you mean the rendering in the iD-Editor? If not you may mean the Standard-Map-Tile, then there is another place to report this issue: https://github.com/gravitystorm/openstreetmap-carto/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Alandcover+trees

**Comment by bhousel** [comment]
This came up before on #4272 and we decided against it.  
I don't think the `landcover` tags have gained any traction in the past 6 months, and adding a preset for it would only further fragment things.
