### ISSUE TITLE
Add preset for building=farm_auxiliary and rename preset for building=farm

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4826]
`building=farm_auxiliary`
- https://wiki.openstreetmap.org/wiki/Tag:building=farm_auxiliary
- a non-residential farm building
- name: Farm Building

`building=farm`
- https://wiki.openstreetmap.org/wiki/Tag:building_farm
- a residential building on a farm
- name: Farm House

**Comment by MaciejWWojcik** [comment]
Hello, sorry for that stupid questions - I'm new and want to learn and help. 

I want to make this issue, so I writed my code in presets.yaml and then start npm test, because of contributing.md

There I have two problems:
1. My changes in yaml disappeared 
2. Test stuck at  iD.uiFieldWikipedia 2)"before each" hook

What I'm misssing?

**Comment by bhousel** [comment]
Hey @MaciejWWojcik thanks!   
We have a special readme just for working with presets and fields:
https://github.com/openstreetmap/iD/blob/master/data/presets/README.md

There is a lot of info in there, but the tl;dr is 
* presets and fields are all defined in the .json files
* run `npm run build` to rebuild the generated files (you found that the .yaml is one)

So for this request, the steps to do are:
1. copy `/data/presets/presets/building/farm.json` to `/data/presets/presets/building/farm_auxiliary.json`
2. edit `farm_auxiliary.json` and change the "tags" to contain `"building": "farm_auxiliary"`
3. edit `farm.json` and change the "name" from "Farm Building" to "Farm House"
4. `npm run build`

You can test whether it worked by running `npm run start` and using iD on localhost.  You should be able to find both presets "Farm House" (which will add the tag `building=farm`) and "Farm Building" (which will add the tag `building=farm_auxiliary`).

I'm not sure what is causing the other test failure, but it sounds probably unrelated.

**Comment by MaciejWWojcik** [comment]
Okay, thanks a lot! I will work on this ;)

**Comment by MaciejWWojcik** [comment]
#4839
