### ISSUE TITLE
Imagery that wasn't actually used added to imagery_used list

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#4827]
It is a minor nitpick: iD will always add the currently selected background layer to the imagery_used list even if the coverage area was never actually intersected by the edits (aka the imagery was never on the screen). This can be slightly confusing to somebody inspecting the changesets after the edits as the information would seem to make no sense (which is probably actually the case :-)).

**Comment by bhousel** [comment]
Trying to understand this issue better.  Is this like:

1. user selects a local (not global) imagery source
2. user pans map somewhere else where that imagery is not available
3. user edits something (presumably the background imagery is blank here)

What should iD do in this situation?

**Comment by simonpoole** [comment]
Yes (situation description).

what should iD do: add nothing to the list IMHO (to be on the save side ai would only add nothing if the current screen bounding box doesn't intersect with the imagery at all.

As said it is a minor nitpick nothing anybody is going to get upset about.

**Comment by bhousel** [comment]
Thanks for the clarification - I agree iD's imagery used code could be better.
