### ISSUE TITLE
Do the messages sent from ID delivered to Maps.me or OsmAnd?

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#4829]
We have several dozens of Edits (mostly adding places) made from maps.me, Osmand and other mobile applications and try to keep them under control using achavi and neis-one.org tools. And also try to be "proactive" in guiding good practices for editing, so sending comments on changesets or messages to the users. 
My question is: Are those messages or notifications being delivered to such applications users?
If not, there is ilogic to have people that add crazy data and we mappers have no way to guide them...
Please advise

**Comment by bhousel** [comment]
iD doesn't send messages to users.  The message sending stuff (either through personal messages or through changeset discussions) is a feature of openstreetmap-website.

There is some discussion on https://github.com/openstreetmap/openstreetmap-website/issues/526  about this.

Also #2367 mentions it, but we closed that issue as it's really not something we'd do in the iD code.

**Comment by jjiglesiasg** [comment]
Thanks for the input, will move the question to there...
