### ISSUE TITLE
Direction tag on a node that is part of a way and an area

### ISSUE THREAD

**Issue by rebio** [openstreetmap/iD#4830]
I like the feature that you have this little cone now that is displayed when there is a direction tag on a node in a way or an area. However, iD seems to be a bit _confused_ when the node is part of a way AND an area.

![id 2 6 1 direction bug way area](https://user-images.githubusercontent.com/10911084/36569065-8c8f80f8-182c-11e8-9b62-b7bfad3b6bd9.png)

The top node is only part of the way. The bottom node is part part of the way and the area.

**Comment by bhousel** [comment]
This makes sense to me, although I can see why it would be surprising behavior.  A direction tag like `forward`/`backward` applies relative to the direction that its parent way is drawn.  So if you put it on a node that has several parent ways, you'll get several viewfields.

I am not sure whether adding a directional node to both a node and a way is valid tagging, so I'm kind of ok if it renders like this to draw attention to what's probably a user mistake.

Inclined to close, but would like to hear more opinions...

**Comment by Nakaner** [comment]
I agree with @manfredbrandl. The other possible solution would be not render the angles at all if it is ambiguous. But that might confuse users, i.e. the current solution is the best. :-/

**Comment by bhousel** [comment]
Thanks for your feedback @Nakaner & @manfredbrandl ..  Closing this issue as "looks wrong because it is wrong" 😆
