### ISSUE TITLE
Overlaid Map is worst quality ever seen

### ISSUE THREAD

**Issue by tchchm1** [openstreetmap/iD#4832]
can you please tell me how do i even recognize the streets and other landmarks when the resolution is so bad? is there anyway i can re-upload the photos? How can we link to Google Map - Satellite view?

**Comment by tastrax** [comment]
Hi tchchm,

 

I dont think google makes its imagery available for use in ID however there are other choices in the panel on the right hand side

 



 

You may have to make some adjustments/offsets for some of this imagery to match existing mapping.

 

Cheers - Phil

**Comment by matkoniecz** [comment]
> How can we link to Google Map - Satellite view?


Note that it is not OK to map using Google imagery (such edits must be reverted once found) due to copyright issues.

**Comment by bhousel** [comment]
sorry to hear that @tchchm1 .. as others have pointed out:
1. You can use the Background Imagery pane to see if there are other sources of imagery in your area.  There are now 6 sources that cover the entire world, so maybe one of them looks better than the default choice in your location.
2. The OpenStreetMap project is not allowed to use proprietary sources like Google.

There are also options for reporting bad background imagery to some of the companies who have generously allowed us to trace from their imagery:
https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery
