### ISSUE TITLE
Graph corruption when drawing a line (was: Error Code 400)

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#4835]
I spent a lot of time drawing streams in a complex mountain region, and suddenly trying to save and upload I got a Error Code 400, in ID, and all my work is gone... any advise?

**Comment by bhousel** [comment]
Your edits should not be gone - iD will save them in your browser’s storage (this might not work if you are using incognito mode or if you open several iD tabs at the same time).  

You shouldn’t get a 400 error unless openstreetmap.org is down, but you should be able to stay the save again later, or even refresh your browser and restore your edits and try the save again.

**Comment by jjiglesiasg** [comment]
Hi Brian, I was drawing a line, them suddenly the line disappeared and just saw white dots, all map data disappeared and them when I try to save the error code 400 appeared, them all my data was lost and the only screen open do not restored any unsaved data after closing and reopened it. That was the sequence of events...

**Comment by manfredbrandl** [comment]
@jjiglesiasg I save regularly so that any problem will not loose me many edits. @bhousel may I suggest that you add the "refresh trick" to the help/documentation just above the keyboard shortcuts in edit&save ?

**Comment by bhousel** [comment]
> Hi Brian, I was drawing a line, them suddenly the line disappeared and just saw white dots, all map data disappeared and them when I try to save the error code 400 appeared, them all my data was lost and the only screen open do not restored any unsaved data after closing and reopened it. That was the sequence of events...

Ok, yeah that is pretty different than just a 400 server error.  If you can get it to happen again in a repeatable way, then it's a bug that needs fixing.  

Unfortunately it's not always easy to know what caused an error like this, but if it happens again, the best course is to open the dev console and look at the errors (for an error like this you'd probably see a lot of "Entity not found" stuff).

**Comment by bhousel** [comment]
> @bhousel may I suggest that you add the "refresh trick" to the help/documentation just above the keyboard shortcuts in edit&save ?

good idea!  @manfredbrandl can you write it up?

**Comment by jjiglesiasg** [comment]
Hi Brian, the white dot showed up again today, but this time I was able to save my previous work, not the line that I was drawing, and there were not Error Code at all... I tried to refresh but the line never showed, so I did it again, no other fault...

**Comment by bhousel** [comment]
closing as unreproduceable
