### ISSUE TITLE
Fully superimposed objects

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#4838]
This could be a feature request (if it's not currently possible), or a bug report on the help system (if it's possible but the help doesn't say how), or an admission of stupidity (it's possible, the help explains how, and I'm too stupid to comprehend), or an admission of colossal stupidity (it's a very stupid thing to want to do).

I have two fully superimposed objects.  All their respective nodes have the same locations.  There is no node or line that is present in one but not the other.  I can't find a way of selecting other than the last object I mapped.  I'd like to make a change to the one "underneath" but can't find a way other than deleting the upper object, changing the lower one, re-mapping the upper one.

Why am I doing such an apparently stupid thing?  Because the consensus over in the general mapping forum, including some old hands, was this was the way it should be represented.

What is it?  A house.  No, two houses.  But one building.  Not the usual split of a typical terraced (row) house, where they're side-by-side.  That would be easy.  Number 35, The Street, The Town is the lower floor of the building.  Number 36, The Street, The Town, is the upper floor of the building.  In saner parts of the world they might be Flat 1, Number 35 and Flat 2, Number 35.  They're not.  They're this crazy split.

The consensus was to map each as building:part=house with building:level=0 or 1.  So I have two fully superimposed objects and no (apparent way) of choosing which one to modify.

And yes, I simplified a little.  There are four such pairs terraced into a single building with two sets of stairs, so six external doors between them.  I could cheat with the stairway by assuming more about the internals than I know, but I know of a large housing estate at the other end of the country where such a cheat would be an outright lie.

Assuming building:part is the way to go, I would therefore like a way of selecting one or the other.  If it's possible.  I have a ctrl key not doing anything and a middle mouse button.  But I suspect the code is harder than assigning a key sequence. :)

**Comment by bhousel** [comment]
Hey @eehpcm yes this is a real issue!  What you describe with `building:part` is the current best-practice for mapping 3d buildings.

I'm going to close here and consider it part of #2746 
We need to better handle how to allow users to map features that are coincident (located in the same place) but on separate layers.  

My plan is that a toolbar like #3123 can unblock adding more options for tools like this that would otherwise just end up as "add a bunch of buttons around the edge of the map".

**Comment by eehpcm** [comment]
Oh my.  Those other proposals are way more complicated than I envisaged.  Probably better, in the long run.

All I was thinking was maybe control-click on a superimposed node or superimposed way opened a pop-up giving you a list of objects to select.  When there's no superimposed node/way it acts as normal.

Or maybe without needing control.  Click on it and get a "select object" pop-up.

Could get messy with multi-storey buildings.

Dunno.  Looks like whatever the solution is, it's not going to appear quickly.  So I'll fix up my mapping error the hard way.

**Comment by bhousel** [comment]
> All I was thinking was maybe control-click on a superimposed node or superimposed way opened a pop-up giving you a list of objects to select. When there's no superimposed node/way it acts as normal.

We might do something like that too - that's #1239
