### ISSUE TITLE
Improve style of slider controls

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4840]
The options looks like this that when the mouse is over the crossing but before click:
![turn-restriction-editor-options-before-click](https://user-images.githubusercontent.com/5360273/36859031-7b6d95b6-1d7d-11e8-82ed-6b25c7aae1af.png)
After selecting with click and moving the cursor to the object editor / turn-restrictions editor it look like this:
![image](https://user-images.githubusercontent.com/5360273/36859205-df4c61ca-1d7d-11e8-8468-a46785052dee.png)
Is this a bug or a feature?

**Comment by bhousel** [comment]
Looks a bit buggy - which browser is this?
Styling sliders is a bit complicated, so I've avoided messing with the style much.  Do the sliders under the Background Pane do this too?

**Comment by manfredbrandl** [comment]
This is Firefox Quantum 58.0.2 (64-Bit) on Windows 7. But i suspect it browser specific, because on Chrome Version 64.0.3282.167 (Offizieller Build) (64-Bit) and Opera 50.0.2762.67 (PGO) there is no such problem. Feel free to close.

**Comment by bhousel** [comment]
No problem @manfredbrandl, I'll leave it open.. It is actually possible to style sliders with CSS, and we should probably make them look a little bit more iD-like (clean, minimal), or at least more consistent.

**Comment by manfredbrandl** [comment]
On the latest version of firefix the sliders look very good.
