### ISSUE TITLE
"only_*" turn restrictions shouldn't affect turns in opposite direction of way

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#4849]
I noticed the following regression related to the reworked turn restrictions editor (see #4768 / #2622): When a short road segment in a (moderately) complex intersection is used as a _from_ member of a _only_-type turn restriction, not only are all "outgoing" turns marked as prohibited (i.e. turns one could otherwise take when driving on the road towards the _via_ node or way(s)), but also all turns on the other end of this road, basically transforming it into a dead-end road. Here's an example ([location](https://www.openstreetmap.org/edit#map=19/46.49506/11.35409)):

![turn-restriction-only-opposite](https://user-images.githubusercontent.com/1927298/37018776-e8410bd2-2115-11e8-8b13-057d2f22ed6c.gif)

Notice how the southern end of the selected way turns into an all-red situation after adding the only-restriction at the northern end of the road.

Another confusing follow-up effect of this is that some intersections are displayed differently on how far one is zoomed in, as seen here (same location as above):

![turn-restriction-only-zooming](https://user-images.githubusercontent.com/1927298/37018911-71ff41e0-2116-11e8-8ab7-ffdb37df7561.gif)

//edit: a second side effect of this is that all previously mapped _no_ restrictions on the opposite end of a way are removed after adding an _only_ restriction on one end. In this example, the initial southern _no_u_turn_ restricton is affected by this.

I think that _only_-type turn restrictions should only affect the direction of the way towards the respective _via_ member(s) (even though the osm wiki page about [turn restrictions](https://wiki.openstreetmap.org/wiki/Relation:restriction) doesn't state this explicitly). And as far as I can see, this is also how every routing software implements these.

**Comment by bhousel** [comment]
> I think that only-type turn restrictions should only affect the direction of the way towards the respective via member(s) (even though the osm wiki page about turn restrictions doesn't state this explicitly). And as far as I can see, this is also how every routing software implements these.

Yes, this is something that came up in our internal testing and I took an approach that might not be perfect.. I was trying to follow the rule on the [osm wiki](https://wiki.openstreetmap.org/wiki/Relation:restriction#Tags):

>  If it is "only_", then you know that the only routing originating from the "from" member leads to the "to" member. 

We agree that that this wording is probably an oversimplification - when the FROM way is bidirectional.  

I ended up adding some code in here to say "only follow this rule and restrict other paths that are _local_ to the intersection".  The situation we ran into with testing was that the FROM way could trail off for miles and that `only_` restriction was affecting another intersection far away, if we applied the rule literally as written.
https://github.com/openstreetmap/iD/blob/master/modules/osm/intersection.js#L468

I think your approach of "`only_` only applies to paths that leave the FROM way towards the VIA" is also good.

It would make me even happier if we could just say "`only_` restrictions require a oneway FROM" - but I've definitely seen a few "in the wild" that break this rule, so changing it would require a discussion with the wider community.

> Another confusing follow-up effect of this is that some intersections are displayed differently on how far one is zoomed in, as seen here (same location as above):

Yeah that's a consequence of the "local via" rule I mentioned above.. What is considered "local" depends on that slider.

**Comment by bhousel** [comment]
>  And as far as I can see, this is also how every routing software implements these.

Should also add - If this is the case then we should definitely change iD to match what they do 😆

**Comment by tyrasd** [comment]
here's an example: https://www.openstreetmap.org/relation/2227207#map=19/47.05882/15.47012&layers=N

OSRM and Graphhopper happly route across this turn restriction in both directions: 
https://www.openstreetmap.org/directions?engine=osrm_car&route=47.05877%2C15.47019%3B47.05915%2C15.46974

**Comment by bhousel** [comment]
Yeah I thought about this more.. I'll definitely change it and push out an update in the next day or so.

**Comment by slhh** [comment]
> > If it is "only_", then you know that the only routing originating from the "from" member leads to the "to" member.
>
> We agree that that this wording is probably an oversimplification - when the FROM way is bidirectional.

+1
Applying the rule literally would make the from member a dead end road in the other direction.
Only restrictions are likely used quite often with bidirectional roads. The German wiki requests to always use only restrictions where only one routing is allowed, because the restriction is signed this way. This does likely apply some to other countries too.

**Comment by bhousel** [comment]
This is fixed now - `only_` turn restrictions will only count if they leave the from way towards the via node or way(s).

<img width="365" alt="screenshot 2018-03-09 22 41 20" src="https://user-images.githubusercontent.com/38784/37238019-0f90b232-23eb-11e8-9def-386a9b3357df.png">
