### ISSUE TITLE
Name field missing from presets

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#4857]
The name field is missing from leisure=pitch and amenity=parking.

I'll get round to it eventually but if anyone else wants to create the PR then feel free :)

**Comment by umarpreet1** [comment]
I am new to OSM and id but i really want to contribute to OSM. So want to solve this issue to become familiar with the OSM and ID. Can you guide me for solving this issue.

**Comment by Nakaner** [comment]
This might be related to https://github.com/openstreetmap/iD/issues/4200.

@umarpreet1 wrote:
> I am new to OSM and id but i really want to contribute to OSM. So want to solve this issue to become familiar with the OSM and ID. Can you guide me for solving this issue.

The quick work around is to enter the name tag manually in the tag section below the preset form (left sidebar). So this issue should not keep you away from mapping. ;-)

**Comment by bhousel** [comment]
Done in #4865

**Comment by boothym** [comment]
@umarpreet1 Probably should have been clearer about this - I think the name field also needs to be added to the various sport pitch presets in here: https://github.com/openstreetmap/iD/tree/master/data/presets/presets/leisure/pitch
