### ISSUE TITLE
Splitting the road, breaks TR relation

### ISSUE THREAD

**Issue by maning** [openstreetmap/iD#4861]
When splitting a road with an existing TR, the from member is assigned to the other segment that does not connect to the via way.

To reproduce, select a from way, split the way. Check the relation membership.
![split-tr](https://user-images.githubusercontent.com/353700/37151037-fa6a45b8-22f9-11e8-99f7-06bed6658a91.gif)
_Not uploaded of course! 😄_

**Comment by bhousel** [comment]
Good catch @maning - I thought I included this fix but I missed it.  Will push out a patch for it this week.

**Comment by abhisheksaikia** [comment]
@bhousel Is this issue fixed? cc @maning

**Comment by bhousel** [comment]
Not sure @abhisheksaikia  - I looked into it a while back but wasn't able to reproduce the issue.

**Comment by slhh** [comment]
> we found 8 cases yesterday with unconnected roles in a relation for the via way no_u_turn relations. The from and via roles are not connected.

Turn restrictions can easily be broken in this way by deleting the node which is connecting the via and the from member. This is due to https://github.com/openstreetmap/iD/issues/3117#issuecomment-267831212.

**Comment by matkoniecz** [comment]
> https://www.openstreetmap.org/relation/8171240/history

I am confused how you know that this specific error caused this mangled relation

given that it is open for 8 years and I see no repeated reports, it looks like it was caused by some other problem

I also tried to reproduce it just in case and failed

**Comment by tyrasd** [comment]
Closing as stale / can't reproduce (and/or fixed by f8bbb99 or some other change in the meantime).

If there are steps to reproduce it still in new versions of iD: please open a new bug report
