### ISSUE TITLE
Train platform is incorrectly called "Subway Stop / Platform"

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4862]
![image](https://user-images.githubusercontent.com/20193716/37163722-6028e044-22f0-11e8-8e91-7f73b5393ae6.png)
This should really be called "Train Stop / Platform", given that there's nothing to suggest that this is a subway platform. Perhaps it's an issue with the "Train Stop / Platform" and "Subway Stop / Platform" presets having the same tags.

**Comment by bhousel** [comment]
Thanks for reporting - you're right that the tags should not be the same, and that's why iD is incorrectly recognizing the feature.
