### ISSUE TITLE
Line direction is reverted at merge

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4872]
When you merge two lines the direction is reverted but only if you select the last line first.
![linemerge](https://user-images.githubusercontent.com/14937001/37252467-294f27d8-2532-11e8-8447-2d4f67cf3c71.gif)

**Comment by bhousel** [comment]
Ah yeah, iD strongly prefers to generate a forward path..

The same code that joins ways also joins relation members.  This comment is right before the part that does the reversal.

https://github.com/openstreetmap/iD/blob/00c4c57fc1d932625f8eb5a38fa6274d55a77a1d/modules/osm/multipolygon.js#L131-L135

I'm going to close here, since it doesn't really affect anything..

**Comment by bhousel** [comment]
> @bhousel It seems there is something wrong there. The direction matters for waterways and one-way highways. Waterways can be very wandering and you can easily lose track of what direction the current segment is supposed to have. It has already occurred to me to save such incorrect reverting, but I was lucky to notice the mistake later on. With one-way highways such mistakes are especially dangerous due to usage in navigation.

Ok, I just tested this - the reversing doesn't actually affect oneway roads (the tag gets reversed to `oneway: -1`), but it does affect waterways.

I'll see if this is something we can fix.  The main issue is if those ways also belong to a relation that requires the members ordered in a forward direction.  Maybe I can skip that reversal code in most cases.

**Comment by yaugenka** [comment]
>  the reversing doesn't actually affect oneway roads (the tag gets reversed to oneway=-1)

Ok, the tag secures the navigation. But is it really correct to revert the line direction and then fix it by means of the tag in this case? Let's take for example this one-way highway which is part of a route
https://www.openstreetmap.org/edit?way=314718034#map=17/52.96646/29.87338
The direction of this way is correct and conincides with the direction of the proceeding and following ways.
If you cut this way and merge it back, its direction will be reverted and the oneway tag will get changed from 'yes' to '-1', whereas the proceeding and the following ways will reserve their initial correct direction.

**Comment by bhousel** [comment]
> I'll see if this is something we can fix. The main issue is if those ways also belong to a relation that requires the members ordered in a forward direction. Maybe I can skip that reversal code in most cases.

☝️ I did this  - now iD won't reverse the ways when it doesn't need to..

**Comment by yaugenka** [comment]
Thanks, @bhousel !
