### ISSUE TITLE
Pen/Stylus Input Bug 

### ISSUE THREAD

**Issue by Jbwalters22** [openstreetmap/iD#4877]
Currently now whenever I try to use my digitizer pen to edit OpenStreetMap in ID I can no longer move ways like driveways as it just zooms in and out of the map instead.  Please fix this issue as mapping with a stylus type input is used by a lot of people.

**Comment by bhousel** [comment]
Thanks for reporting @Jbwalters22 - which browser and OS are you using?

**Comment by Jbwalters22** [comment]
I am currently using Windows 10 Education Version 1709 and Maxthon browser but I just verified that it also is a bug when using Google Chrome


James Bradley Walters (J.B.)

Doing Business As (D/B/A)

Walters I.T. Consulting

Cell: 1.317.502.2853

Note: James Bradley Walters Is A Sole Proprietor Doing Business As Walters I.T. Consulting

**Comment by Jbwalters22** [comment]
This bug appears to be fixed now.

**Comment by kriscarle** [comment]
I think this is a bigger issue specifically with pen input in Windows 10 on MS Surface devices after the 2017 fall creators update. It changed the default behavior for the pen to fire touch events. I've been using an original MS Surface Pro pen with iD for years, now Chrome and Firefox are currently usable. Edge has the correct pen behavior (not sure why it is different) but still has a few problems that make it harder to use. I'm assuming problems with Edge are unrelated to the pen but I'll search the other issues.

The feedback here seems promising
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15008486/

**Comment by Jbwalters22** [comment]
What version of ID are you using, because I know a while back it was fixed, I have not used my digitizer pen lately, I can double check to see if I have the issue as well.  Are you experiencing the same issues that were first reported, or are they new issues?

James Bradley Walters (J.B.)

Doing Business As (D/B/A)

Walters I.T. Consulting

Cell: 1.317.502.2853

Note: James Bradley Walters Is A Sole Proprietor Doing Business As Walters I.T. Consulting
