### ISSUE TITLE
Allow user to zoom track text

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4880]
On https://www.openstreetmap.org/edit?gpx=2630876#map=24/24.17869/120.85616
see that number, 7438-35?

Well there is no way for the user to make it temporarily bigger to be sure he read it correctly, Zooming only helps for a second.

OK he can do CTRL++++ .

OK I suppose that will have to do.

**Comment by jidanni** [comment]
If he does CTRL++++ he will have to remember to do exactly CTRL+---, otherwise he will have messed up his original situation.

**Comment by jidanni** [comment]
Wait, CTRL++++ only helps for one second...

**Comment by bhousel** [comment]
Changing the size of this text is something you can do with Stylish:
see 
https://github.com/openstreetmap/iD/blob/master/FAQ.md#im-having-trouble-seeing-some-of-the-colors-is-there-a-way-to-customize-or-change-them
and
https://www.makeuseof.com/tag/fix-small-annoyances-web-stylish-firefox-chrome/


I think it would be fantastic if somebody made a Stylish theme for iD, specifically for mappers with poor vision - maybe to adjust the size of text and contrast of the rendered elements.

**Comment by jidanni** [comment]
Yes but that is a hack.

**Comment by jidanni** [comment]
Please add a slider.
If users were so smart that they could use external solutions, they probably wouldn't be using a web based editor in the first place.

**Comment by bhousel** [comment]
@jidanni It's not ok to insult the users.
