### ISSUE TITLE
Add preset for passing_place

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4883]
https://wiki.openstreetmap.org/wiki/Tag:highway=passing_place

For use on nodes on highways

Common in rural areas with single-track roads

**Comment by bhousel** [comment]
Sounds good.. Whoever wants to do this can just copy the `highway=turning_circle` preset and change the name and tag.

**Comment by Xavier-J-Ortiz** [comment]
Hello! I'd like to contribute to this project!

This will be my first contrib. Very excited to be part of the project! Will start to take a look at this today, but will probably have some more time during the weekend if I can't figure this out.
