### ISSUE TITLE
add some vending_machine presets

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#4888]
Hello,
what do you think about adding presets for some further vending_machines like vending=sweets or vending=chewing_gums? And something further: There are also many machines which sell two or more different products, too, so what are we going to do with these? Maybe for amenity=vending_machine, at least in some cases it would be better to have a field in the preset like that one for recycling containers, where you are able to add several things that are recycled / sold...

**Comment by bhousel** [comment]
Sure, we can add more if they are commonly used. I don't think we would want a preset for every kind of vending machine, but we do support most of the frequently used types:
(see https://taginfo.openstreetmap.org/keys/vending#values )


These are the ones we currently have presets for:

<img width="218" alt="screenshot 2018-03-15 01 25 07" src="https://user-images.githubusercontent.com/38784/37445693-bbc06982-27ef-11e8-8669-e9b0e5c47815.png">

> And something further: There are also many machines which sell two or more different products, too, so what are we going to do with these? 

We could make this Type of Goods a field that accepts multiple semicolon-delimited values (like the recycling one)

<img width="373" alt="screenshot 2018-03-15 01 26 48" src="https://user-images.githubusercontent.com/38784/37445743-fe4a9e44-27ef-11e8-8293-17f80c82b2c1.png">
