### ISSUE TITLE
Move Lines next to Points in the walkthrough

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#4894]
Currently, the user goes through Points, Areas, Lines and then Buildings.

It seems more logical to introduce Lines (two dimensions element) before Areas (three dimensions element), and to go through Buildings just after Areas.
Additionally, the toolbar buttons are in the order Point, Line and then Area.

![presse-papiers-1](https://user-images.githubusercontent.com/3265870/37455292-053734e0-283d-11e8-9671-4a347dfa2da4.jpg)
![presse-papiers-2](https://user-images.githubusercontent.com/3265870/37455297-089061f2-283d-11e8-87d6-bb28da70cec0.jpg)

**Comment by bhousel** [comment]
Oh, we have the walkthrough chapters ordered this way on purpose because the tasks increase in difficulty.
