### ISSUE TITLE
Consider using semantic elements wording (point, line, polygon, relation)

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#4895]
iD currently mixes [elements](https://wiki.openstreetmap.org/wiki/Elements) wording (node, way, area, relation) and [semantic elements](https://wiki.openstreetmap.org/wiki/Semantic_elements) wording (point, line, polygon, relation).
The culprit is area, which is used to add [buildings](https://wiki.openstreetmap.org/wiki/Buildings) and [areas](https://wiki.openstreetmap.org/wiki/Area), which may confuse new users. Since both are polygons, and multipolygons are best defined as multiple polygons (as opposed to multiple areas), it makes sense to rename area to polygon.

![37455297-089061f2-283d-11e8-87d6-bb28da70cec0](https://user-images.githubusercontent.com/3265870/37456509-e20e55b8-283f-11e8-8a14-3da3cd84a98a.jpg)

This would also avoid the possible confusion in the walkthrough.
Here, "Area" is used to refer to two different things:
![presse-papiers-3](https://user-images.githubusercontent.com/3265870/37455958-9bba3be6-283e-11e8-9ced-ee017e2f577a.jpg)
![presse-papiers-4](https://user-images.githubusercontent.com/3265870/37455963-9e5989ec-283e-11e8-9540-3fc6cc147725.jpg)

**Comment by bhousel** [comment]
> iD currently mixes elements wording (node, way, area, relation) and semantic elements wording (point, line, polygon, relation).
> The culprit is area, which is used to add buildings and areas, which may confuse new users. Since both are polygons, and multipolygons are best defined as multiple polygons (as opposed to multiple areas), it makes sense to rename area to polygon.

Sorry, but we wouldn't rename something like "Area" to "Polygon".  

We try very hard to make iD as approachable as possible for beginners.  When we worked on the walkthrough overhaul (#3921) last year, I did a bunch of focused testing with first time mappers, and I found that jargon words like _node_ and _way_ were extremely off-putting.  

This probably sounds silly to someone who is very familiar with OpenStreetMap or with mathematical language, but we'd actually have people get angry at their computer at the step saying "place some nodes around the edge of the playground."  We have to ease them into the idea of "nodes".  So renaming "Area" to "Polygon" would be a huge step backwards for iD's approachability.

>This would also avoid the possible confusion in the walkthrough. 
Here, "Area" is used to refer to two different things:

Sure!  "Area" is used to refer to many things. We list out a few of them in the walkthrough, and we encourage users to explore the map and see what kinds of things can be mapped as "areas", and no one I tested this with was confused by this concept.  And we are very consistent in how we render area vs linear features. 

Anyway thanks for your suggestion, but sorry I have to close it.  I do encourage you to attend some mapathons with first time users, and even show iD to neighbors or people in your family who have never tried editing a map before or heard of OpenStreetMap, and see what concepts they struggle with.

Aside: the current biggest thing I see new users struggle with at mapathons is choosing the best background imagery.  They've asked me "how do I know which one to use" and I don't have a great answer for them.  Beginners are confused by, not just having several choices, but making that informed choice based on recency, shadows, off nadir angles, offsets, resolution, etc.. This is a hard problem to explain to people, and we don't talk about it at all in the walkthrough.
