### ISSUE TITLE
Strava Heatmap overlay problems

### ISSUE THREAD

**Issue by scrapperuk** [openstreetmap/iD#4896]
Strava have recently made some changes to accessibility of their heat map dataset, meaning that you need to have a Strava loging to access the data at zoom levels required to match to openstreetmap editing using the heatmap as an overlay

The iD editor doesnt appear to give an option to access any login functionality to attach a strava account

Is anyone aware of a fix for this?

**Comment by bhousel** [comment]
This is pretty much out of scope for iD.  The main instance of iD is not allowed to use the heatmap for editing.

Strava made a fork of iD to allow editing with the heatmap, and the repository for that fork is: https://github.com/strava/iD

You could try raising the issue there, but as far as I know, the fork is not really maintained.

**Comment by alpter** [comment]
@bhousel sure Strava heatmap should not be allowed to edit in ID, but is a useful tool to help check and mantain OSM alive and update... a sort of help to implement it... https://github.com/bertt/wmts/issues/2
Here is the ticket from JOSM community... (also affected by the recent [heat map updates](https://blog.strava.com/press/heatmap-updates/).
https://josm.openstreetmap.de/ticket/16100
