### ISSUE TITLE
The first feature selected after save is not loaded properly

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4898]
When you select some feature after save, the information panel shows nothing. If you select another object or diselect and select the first one again everything works fine.
![screenshot_1](https://user-images.githubusercontent.com/14937001/37496172-04b03a1e-28c2-11e8-8d16-9c53532ef0fa.png)

**Comment by slhh** [comment]
I'm not sure what happens here, but maybe, #4903 can solve the issue.
