### ISSUE TITLE
Autocompleted relation roles are not saved

### ISSUE THREAD

**Issue by ghost** [openstreetmap/iD#4900]
When adding a relation role by typing the first few letters and then pressing the tabulator key, iD does not save it: the save button does not change and after selecting a different element and then selecting the first element again, the relation role has disappeared.

![untitled](https://user-images.githubusercontent.com/14875493/37528338-af627a2c-2934-11e8-9875-e9a14004b242.gif)

**Comment by jguthrie100** [comment]
I've just tried to replicate this and I can't. I've tried pressing tab and just clicking outside of the textbox, but every time the Save button highlights and the role remains after clicking onto another way and back again.

Can you try it in Firefox/Chrome and see if you still have the problem? (I'm on Linux and don't have Safari to try it on)

**Comment by SelfishSeahorse** [comment]
The problem doesn't seem to occur with Firefox.

**Comment by jguthrie100** [comment]
I've tried it on Chrome 64.0.3282.186 running on Ubuntu 16.04 and couldn't replicate it.

What operating system/browser are you using?

**Comment by SelfishSeahorse** [comment]
The problem occurs with Safari 11.1 on macOS 10.12.6, but not with Firefox 59.0.2 on macOS.

**Comment by bhousel** [comment]
I made some changes that I think should fix this.. Could you test in http://preview.ideditor.com/master/ and let me know if changing the role sticks now?

**Comment by SelfishSeahorse** [comment]
Yes, it does. Thank you!
