### ISSUE TITLE
Allow querying relations with id in "add-to-relation" section

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4902]
In some cases it would be really helpful if one could add objects to a distant relation by typing in its OpenStreetMap id. In my specific case, I wanted to add a city marker to an administrative border relation as admin_centre but iD made it impossible, because it only shows the closest relations. Would it be possible to add this low-impact but helpful feature?

**Comment by slhh** [comment]
https://github.com/openstreetmap/iD/issues/3622#issuecomment-372018186 seems to be the better solution for the usecase.

**Comment by hikemaniac** [comment]
Sorry, this is a duplicate of #3487. By the way, I agree with @slhh, that the solution suggested in #3622 (which also regards the same topic) would be even better.
