### ISSUE TITLE
Splitting complex multipolygons

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#4914]
When thinking about how to implement an area/multipolygon split (#969), I realized a special case seems to need a different UI: Complex multipolygons with multiple independent (non nested) outer rings.
Broken normal multypolygon with separated segments of a single outer ring might fall into this special case too. Nomal area splitting has priorty, but we should think about the complex multipolygons early to avoid duplicate work and later inconsistency. Especially in case of  choosing point 1 or 2 below, the complex multipolygon split could have some impact on how to do the normal area/multipolygon split.

ID should support splitting complex multipolygons, because in some regions landuses are mapped as quite complex multipolygons. This type of mapping isn't a good idea, but it does exist, and should not prevent other users from editing in that regions. In addition the multipolygons are often broken, but fixing this seems to be too hard for most users. Therefore, the user needs to be able to split even the broken multipolygons to reduce the complexity.

An area split along a line can  potentially result in multipolygons with multile outer rings. My preference is to prevent this, but if this fails, there will be another usecase to split the generated complex multipolygons

We could offer a splitting complex multipolygons in one of the following ways:

1. Operation based on the selection of the multipolygon plus a linestring (one or multiple consecutive selected lines):
The linestring does define a split well if it's extended to the convex hull of the multipolygon.
2. Operation based on the selection of the multipolygon plus a closed linestring:
Linestring might be an outer ring of the multipolygon.
3. Split operation based on the selection of the multipolygon only:
Generate a a separate multipolygon from each complete outer ring, including inner members which were enclosed by the outer ring. Other members, if any, remain in the original still broken multipolygon.
4. Split operation based on the selection of the multipolygon and the mouse position when opening the context menu/hitting :
Generate a a separate multipolygon from the outer ring next to the mouse position, including inner members which were enclosed by the outer ring. Other members remain in the original multipolygon.
5. Modify the member editor for multipolygons:
Use a hierarchical display grouping ring segments and nested rings, and offer a control there to split a full group of nested rings off.

I will discuss pros and cons in later comments.

**Comment by bhousel** [comment]
Its not clear to me why this is an issue.. The #969 split operation should probably just operate on a single outer ring.. It should be disabled if the split line crosses any inners, or if it tries to split two disjoint outers.

Anyway, can you put your thoughts on #969, instead of adding more issues?  I'm personally having a lot of trouble dealing with the iD issue backlog lately.  Thanks..

**Comment by slhh** [comment]
> The #969 split operation should probably just operate on a single outer ring.. It should be disabled if the split line crosses any inners, or if it tries to split two disjoint outers.

In essence I agree, but here the issues with complex multipolygons start.

- Usecases specific to complex multipolygons aren't covered:
Assume the forest in the screenshot is mapped as a single complex multipolgon. The desire to separate the forest into two parts, the rectangular one and the triangular one, seems to be quite natural.
How to address that is the topic of this issue.
- The operation is not well defined or results in invalid multipolygons:
Assume the user splits the forest along the highway. How many multipolygons should this result in? Which one should the triangular part belong to? This regards the split operation of #969, and we might discuss it there.

![grafik](https://user-images.githubusercontent.com/13684947/37571655-df6172f6-2aff-11e8-8715-7a39ee9c233b.png)

The issues will likely result in quite different operations, the discussion for both issues will likely be quite complex, and I think this issue might remain after solving #969. This was my reason to make it a separate issue.
