### ISSUE TITLE
Fix preview.ideditor.com (use node 6)

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4916]
I dropped support for node 4 in #4853
This is just a note for myself that I need to upgrade the preview.ideditor.com builder to use node 6

**Comment by iandees** [comment]
I forget: is this still using benzene?

**Comment by bhousel** [comment]
@iandees It is.. You might have just gotten a warning that I tried to run `sudo` 🙈

**Comment by bhousel** [comment]
This was done
