### ISSUE TITLE
Handling of allotments=plot

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#4917]
The editor currently doesn't seem to handle allotments=plot correctly (or I'm misunderstanding something, as usual).

According to the wiki [allotment=plot](https://wiki.openstreetmap.org/wiki/Tag:allotments=plot) is applied to an area.  Which I did.  But it seems that id is not treating it as a way with an implicit area=yes tag.

Why do I think that?  Because when I give the plot a name=* it is shown in the editor as a label on a way, not a label within an area.  This can be very confusing as allotments often have shared borders, so it's hard to determine which one the name applies to.  I kluge around this by adding an explicit area=yes just to get the name to show sensibly.  If tagging for the renderer is a venial sin then tagging for the editor is probably a mortal sin. :)

Should I be using name=* on a plot?  There's nothing to say I shouldn't and name applies to all objects.  True, the wiki on allotments=plot suggests using ref=whatever, but that doesn't get rendered.  Also, [the original proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:allotments%3Dplot) gives [this example](https://www.openstreetmap.org/way/237662256) by the proposal's author where the plot in question has a name=* not a ref=*.

Is it worth bothering since it doesn't get rendered anyway?  In [this](https://github.com/gravitystorm/openstreetmap-carto/issues/432) github issue, kocio-pl appears, in Oct 2017, to have taken cognizance of a desire to display plots, so it might appear in the near future.  Even if it never makes it into OSM's renderer, it's still useful to have such detail in the db and therefore it's nice if the editor handles it well.

If you want to check this on an allotment with more plots and the area=yes kluge, look [here](https://www.openstreetmap.org/way/552820707)

**Comment by bhousel** [comment]
> The editor currently doesn't seem to handle allotments=plot correctly (or I'm misunderstanding something, as usual).  According to the wiki allotment=plot is applied to an area. Which I did. But it seems that id is not treating it as a way with an implicit area=yes tag.

You're correct, we don't have a preset for `allotment=plot` yet.  We can add one for it.  After we add the preset, iD will know that it can be an area feature, and won't require the `area=yes` tag.

> Should I be using name=* on a plot? There's nothing to say I shouldn't and name applies to all objects. True, the wiki on allotments=plot suggests using ref=whatever, but that doesn't get rendered.

We can add fields for both `name` and `ref`.

> Is it worth bothering since it doesn't get rendered anyway?

Yes - if people are mapping it, we add a preset for it.  Taginfo shows over 9000 instances of `allotment=plot`, so that's good enough for me.  We don't care in this project whether it gets rendered or not.

**Comment by eehpcm** [comment]
Thanks. :)

**Comment by vershwal** [comment]
This is already been done in #4920. @bhousel do you think we can close this issue now? or is there anything that is to be done?

**Comment by bhousel** [comment]
Oh yeah, thanks for the reminder @vershwal - I did forget to close it.

A useful tip:  if your commit message contains special language, GitHub will automatically close the issue.  [See here for more info](https://help.github.com/articles/closing-issues-using-keywords/). 

The first line in a commit message is special, so I usually put the magic comment on a separate line.  For example:

```
Added Preset for allotments=plot
(closes #4917)
```

**Comment by vershwal** [comment]
> A useful tip: if your commit message contains special language, GitHub will automatically close the issue. See here for more info.

Thank you @bhousel. I'll be using this from the next time.
