### ISSUE TITLE
Life guard station preset

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4918]

**Comment by bhousel** [comment]
I found these possible tags.
https://wiki.openstreetmap.org/wiki/Key:emergency#Lifeguards
None of them have a lot of usage, and they seem overly specific (why not just `emergency=lifeguard`?), so let's not add a preset now.

tag|uses
---|---
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlifeguard_base|202
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlifeguard_place|39
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlifeguard_platform|24
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlifeguard_tower|424
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dwater_rescue_station|197

**Comment by Fizzie41** [comment]
Just found this thread as I was about to bring up a similar topic.

I live in a beach-focused tourist area, which has a number of surf-lifesaver clubs & life guard towers spread along the beaches to help keep swimmers safe.

Currently they only render as either buildings or towers, depending on how they have been tagged, with no indication that they are rescue facilities.

It would be very good, & (very dramatic I know, but also true!) potentially life-saving, if these facilities were rendered on the map so as to make it easier for people to get help in the event of somebody getting into trouble in the water.

I would suggest that the ideal icon would be a simple life-ring as shown at https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlife_ring (which actually includes an icon!)

What do you think?

**Comment by Fizzie41** [comment]
Thanks for that Bryan.

I agree that it's a lot of different tags for essentially the same thing, so just one emergency=lifeguard would probably work.

Might bring that up on the Tagging list for discussion?

**Comment by andrewharvey** [comment]
> It would be very good, & (very dramatic I know, but also true!) potentially life-saving, if these facilities were rendered on the map so as to make it easier for people to get help in the event of somebody getting into trouble in the water.

@Fizzie41 did you mean on the default OSM style? Best to open a ticket on the stylesheet issue tracker for that https://github.com/gravitystorm/openstreetmap-carto

**Comment by andrewharvey** [comment]
> I found these possible tags.
https://wiki.openstreetmap.org/wiki/Key:emergency#Lifeguards
None of them have a lot of usage, and they seem overly specific (why not just emergency=lifeguard?), so let's not add a preset now.

Sorry but I disagree. Yes they are similar, but not exactly the same, we have a well defined wiki page describing the differences between the tags and people are mapping based on this. If we add support to iD, I think we should support each individual tag.

**Comment by Fizzie41** [comment]
Feedback is that all the tags should remain separate, but that they should all be rendered.

"did you mean on the default OSM style? Best to open a ticket on the stylesheet issue tracker for that https://github.com/gravitystorm/openstreetmap-carto"

I'm obviously mistaken, but I thought that was what I was doing? 

Would I be right in now thinking that the icon has to be created in Carto by raising a suggestion there, & it will then appear in iD?

**Comment by bhousel** [comment]
> "did you mean on the default OSM style? Best to open a ticket on the stylesheet issue tracker for that https://github.com/gravitystorm/openstreetmap-carto"
> 
> I'm obviously mistaken, but I thought that was what I was doing?

Not quite - this repository is for the iD editor (the map editing software that runs on openstreetmap.org when you click "Edit").

> Would I be right in now thinking that the icon has to be created in Carto by raising a suggestion there, & it will then appear in iD?

No, the two projects are unrelated.  openstreetmap-carto renders a subset of OpenStreetMap data into the map that you see on openstreetmap.org.

The iD editor (this project) renders _everything_ already.  The editor also has support for well established features in OpenStreetMap, to make it easier for anybody to contribute data. 

The lifeguard stuff is not very established yet, so we haven't added it to the menu in iD or created an icon or description for it.  You can add a lifeguard tower in iD - but you need to know the tag to use, and it looks like this:

<img width="641" alt="screenshot 2018-06-09 00 51 47" src="https://user-images.githubusercontent.com/38784/41187812-910e010c-6b80-11e8-9b39-180a6c69aeab.png">

**Comment by bhousel** [comment]
> Sorry but I disagree. Yes they are similar, but not exactly the same, we have a well defined wiki page describing the differences between the tags and people are mapping based on this. If we add support to iD, I think we should support each individual tag.

@andrewharvey do you think we could change it to just `emergency=lifeguard` and then have another field like `lifeguard=tower/platform/base`?

The tag really isn't used much yet.  A few hundred uses could be changed pretty easily

I'm trying to think about how to present all these choices to an untrained mapper, and it seems kind of overwhelming.  The menu would need to have things like:
* Lifeguard Tower
* Lifeguard Platform
* Lifeguard Place
* Lifeguard Base

I'd need to use text and icons to distinguish between the different things.  And anyway why does "what the lifeguard sits on" matter?  Data consumers would need to consume several tags instead of just one.

**Comment by Fizzie41** [comment]
Ahh, thanks Bryan, think I've now got it - your side of things will set it up so that when you create something on the map using iD, & go to name it as emergency=lifeguard_tower, it will appear as an option (as well as _base etc); but I still have to ask Carto to create an icon.

Is that it?

**Comment by bhousel** [comment]
> Ahh, thanks Bryan, think I've now got it - your side of things will set it up so that when you create something on the map using iD, & go to name it as emergency=lifeguard_tower, it will appear as an option (as well as _base etc); but I still have to ask Carto to create an icon.
> 
> Is that it?

Yep you got it!

**Comment by Fizzie41** [comment]
Yay!

Will leave it a couple of days to see if there's any resolution on the everything vs lifeguard only discussion then will bounce it across to Carto.

**Comment by andrewharvey** [comment]
the tagging discussion has moved to https://lists.openstreetmap.org/pipermail/tagging/2018-June/036925.html and https://lists.openstreetmap.org/pipermail/tagging/2018-June/037080.html

**Comment by eehpcm** [comment]
> And anyway why does "what the lifeguard sits on" matter?

In an emergency, knowing what you're looking for when you need to alert the lifeguard might save a few seconds.

Sensible people would check the map before deciding to go to a particular beach to see if there was a lifeguard.  Sensible people would visually locate the lifeguard upon arrival.

Sadly, most people aren't sensible.  So the sequence is likely to be "Shit!  Is there a lifeguard nearby?  Look on the map.  Over there, somewhere.  Oh, there's a building in roughly the right place.  Shit, it's a surf-board rental hut.  Where's the lifeguard?"

In reality, though, it's probably not going to make a lot of difference either way, so being able to indicate what the lifeguard sits on is probably only required by those with obsessive mapping disorder.
