### ISSUE TITLE
List of all relation members in ID for TR editor window for selected segments

### ISSUE THREAD

**Issue by abhisheksaikia** [openstreetmap/iD#4922]
In the turn restrictions editor window it would be great to have list of all the members in a relation example all the `from`,`via` and `to` roles for all the relations a segment is a part of. Right now it only lists out all the roles for various turn restrictions the selected node is part of even when you click on a way segment

Example in the gif below 👇 

![id feature 3](https://user-images.githubusercontent.com/13744156/37697846-3caf058e-2d05-11e8-87da-131f038d656f.gif)

**Comment by bhousel** [comment]
> In the turn restrictions editor window it would be great to have list of all the members in a relation example all the from,via and to roles for all the relations a segment is a part of. Right now it only lists out all the roles for various turn restrictions the selected node is part of even when you click on a way segment

Sorry, I dont think we can do this.  The selected vertex is the only thing that the sidebar will show details for.  Selecting segments in the Turn Restriction editor can't change the contents of the sidebar (doing so would throw away the turn restriction editor).

The turn restriction editor operates on a limited subgraph that includes the selected vertex and whatever stuff is near it.  You can hover over ways in that editor to preview what turn restrictions the ways are a part of.
