### ISSUE TITLE
natural=mud preset

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4923]
https://wiki.openstreetmap.org/wiki/Tag:natural=mud

**Comment by bhousel** [comment]
Whoever wants to work on this can just:

- copy `data/presets/presets/natural/sand.json` to `data/presets/presets/natural/mud.json`
- Edit `mud.json` contents to have appropriate tags, name, terms

**Comment by Xavier-J-Ortiz** [comment]
I'll take a stab at this.
