### ISSUE TITLE
Providing space in conditional restriction not considered as a modification in iD

### ISSUE THREAD

**Issue by krishnanammala** [openstreetmap/iD#4925]
While trying to modify the conditional restriction for `School days` of adding space for `SH off` after `;` syntax `restriction:conditional=no_u_turn @ (Mo-Fr 09:00-10:00,15:00-16:00; SH off)` as per [wiki](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Syntax) the iD editor is not considering it as a modification and not allowing to upload the data to OpenStreetMap.

![id](https://user-images.githubusercontent.com/17470597/37757537-63826538-2dd3-11e8-81b8-d00f95478d8c.gif)

[iD link](https://www.openstreetmap.org/edit?editor=id&changeset=57411140#map=19/37.73653/-122.49782), [mapillary link](https://www.mapillary.com/app/?pKey=t1oL0nB0VojE3EJ1Dl2NRg&focus=photo&lat=37.736533055555554&lng=-122.49781805555556&z=17&x=0.4739524929994531&y=0.4081605711368631&zoom=1.231179759241473)

cc @bhousel

**Comment by bhousel** [comment]
Thanks for reporting @krishnanammala ... 

This is one of those weird OSM edge cases.  Most of the time OSM expects spaces around ';' removed, but inside of an opening hours string, they want the spaces kept.

We have special code in here to handle the situation:
https://github.com/openstreetmap/iD/blob/e1b72d2c0c1013cd1866bdaafebbdfb7bc92ad15/modules/ui/entity_editor.js#L219-L229

I'll have to change this code to apply the space keeping rule whenever a conditional clause is detected.   

(using this page for reference with some complex examples: 
 https://wiki.openstreetmap.org/wiki/Conditional_restrictions )

**Comment by bhousel** [comment]
Also, it seems like a value can have _multiple_ conditionals, and in this situation they are also semicolon-space delimited:

`maxspeed:conditional=120 @ (06:00-20:00); 80 @ wet`
