### ISSUE TITLE
Ability to resize Photo Viewer div (Mapillary / OpenStreetCam / Streetside)

### ISSUE THREAD

**Issue by theel0ja** [openstreetmap/iD#4930]
Mapillary and OpenStreetCam windows should be resizable because it looks small, while 1.5x the size of the default looks much better for small detail without zooming.

**Default**
[![](https://storage.theel0ja.info/theel0ja-img-up/ShareX/2018/03/opera_2018-03-23_14-11-09.jpg)](https://storage.theel0ja.info/theel0ja-img-up/ShareX/2018/03/opera_2018-03-23_14-11-09.jpg)

**1.5x height & width**
[![](https://storage.theel0ja.info/theel0ja-img-up/ShareX/2018/03/opera_2018-03-23_14-11-46.jpg)](https://storage.theel0ja.info/theel0ja-img-up/ShareX/2018/03/opera_2018-03-23_14-11-46.jpg)

**Comment by bhousel** [comment]
Good suggestion!  I've wanted this for a while, and I'm surprised we don't have an issue for it already.

**Comment by bhousel** [comment]
done in #5138
