### ISSUE TITLE
preset for amenity=monastery

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#4932]
It would be great to have a preset for monasteries. Basic tags are amenity=monastery with a name, religion and denomination tags (similar to churches). Advanced tagging would also include a monastery:type and community tag, see here for reference:

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmonastery
https://wiki.openstreetmap.org/wiki/User:FrViPofm/Community

There is also a historic=monastery tag for former monasteries (historic monasteries tend to remain significant building structures, often tourist attractions).

**Comment by Xavier-J-Ortiz** [comment]
I'll take a stab at this one If it's alright.

**Comment by bhousel** [comment]
Go for it @Xavier-J-Ortiz 👍
 
- copy `/data/presets/presets/amenity/place_of_worship.json` 
to `/data/presets/presets/amenity/monastery.json` 
- edit the file, give it the name "Monastery Grounds" to signal to users that they are supposed to tag the perimeter, not the building
- `npm run build`
