### ISSUE TITLE
autocomplete is harmful sometimes

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#4935]
In the speed limit field, if I type "10", it autocompletes to "100". I'd expect typing "10" and then clicking elsewhere would leave it as "10" and only use "100" if I select that option from the dropdown.

![maxspeed autocomplete](https://user-images.githubusercontent.com/117278/37862597-d1862714-2fa3-11e8-8351-ce6970146eee.png)

**Comment by bhousel** [comment]
Oh interesting.. Looks a bit like #4549 
This case is a bit different though.  We should probably not even attempt to autocomplete numbers.
