### ISSUE TITLE
Add fields to Taginfo file as well

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4937]
Currently only preset tags are included in iDs taginfo.json file. It think that it would be a great improvement to the Taginfo documentation if we also add field tags and keys to the file.

**Comment by bhousel** [comment]
Good suggestion @hikemaniac!  Anyone who wants to update our `taginfo.json` file generation could do this and #3598  together.

**Comment by mmd-osm** [comment]
So to recap: that's roughly translating into something like feeding https://github.com/openstreetmap/iD/blob/c8e89b7a0542a6ebf1c07f7d1cccbb01e7a52152/build_data.js#L66 into https://github.com/openstreetmap/iD/blob/c8e89b7a0542a6ebf1c07f7d1cccbb01e7a52152/build_data.js#L70 and iterating over `fields` as well very similar to how generateTranslations is doing it. Each entry in strings/options should then translate into a separate taginfo,json entry like in the JSON example?

**Comment by bhousel** [comment]
You're in the right place @mmd-osm  
What I'd do is pass both `presets` and `fields` into taginfo.json:

```js
var taginfo = generateTaginfo(presets, fields); 
```

Then in that function add a separate for loop for the fields.

The format of the project file is described here: https://wiki.openstreetmap.org/wiki/Taginfo/Projects
It doesn't have `on_node`, `on_way`,etc, but rather accepts an `object_types` array. I agree we should fill it with which types our presets support.
