### ISSUE TITLE
Add preset for shop=pet_grooming

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4939]
https://wiki.openstreetmap.org/wiki/Tag:shop=pet_grooming

- Name: Pet Grooming Shop
- Terms: "dog"
- Probably use same fields and icon as shop=pet

**Comment by Xavier-J-Ortiz** [comment]
@bhousel I'll have a go at this one.

**Comment by bhousel** [comment]
This was done, thanks @Xavier-J-Ortiz 👍
