### ISSUE TITLE
Allow "lock last tag" when adding features

### ISSUE THREAD

**Issue by mapninja** [openstreetmap/iD#4941]
I'd find it useful to be able to 'lock' the last tag used (building=yes, for instance) so when I'm digitizing buildings in HOT, I can just lay down a building, hit S, hit 3 and lay down another building.

**Comment by bhousel** [comment]
Hey @mapninja welcome!  I agree this would be a very useful feature, and it's something we want to add soon. 

#3123 will allow the user to toggle certain tools like this, and the first one of those will probably be #590 - a "repeat the last thing I just added" tool.  (I'll close here, as the feature is already tracked on a few other issues)

In the mean time, the fastest way I know to repeat the last preset is to hit <kbd>tab</kbd> then <kbd>enter</kbd>.  (I once met someone who mapped this key combination to a dedicated button on their mouse!)
