### ISSUE TITLE
Field "terms" inside presets tags

### ISSUE THREAD

**Issue by stefanocudini** [openstreetmap/iD#4945]
I wanted to know which database was used to fill the field **terms** in the configuration files of the individual tags.

like as here:
https://github.com/openstreetmap/iD/blob/be5929d4dcec805bce3cf4a18c9a230c764d97d2/data/presets/presets/natural/cave_entrance.json#L15

or here:
https://github.com/openstreetmap/iD/blob/be5929d4dcec805bce3cf4a18c9a230c764d97d2/data/presets/presets/amenity/atm.json#L12

I intended to build a taxonomic comparisons tool between Openstreetmap data and other data sources

**Comment by stefanocudini** [comment]
@napo

**Comment by bhousel** [comment]
The preset search terms are not filled from a database.  They are usually added by the person who added the preset.

Sometimes we add additional terms or remove terms if we see mappers having trouble selecting the correct preset.

The terms themselves are sometimes synonyms, and sometimes related words.

**Comment by stefanocudini** [comment]
@bhousel 
May be interesting to use an external service(or new iD module) for fill this field that deals with the generation of terms list with respect to the terms searched.
