### ISSUE TITLE
more PTV2-realtion's members need to be excluded from the way (re-)ordering code

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#4946]
see https://github.com/openstreetmap/iD/issues/4864
There seems to be another, let's call it "problem": Not only PTV2-relation's members with the roles stop and platform need to be excluded from the way reordering code ( which has been done a few days ago already, thank you! :) ), **but also members with the roles _stop_entry_only, platform_entry_only, stop_exit_only _and_ platform_exit_only_.** I know it's a bit complicated, but please could anyone help? :)

**Comment by bhousel** [comment]
> There seems to be another, let's call it "problem": Not only PTV2-relation's members with the roles stop and platform need to be excluded from the way reordering code ( which has been done a few days ago already, thank you! :) ), but also members with the roles stop_entry_only, platform_entry_only, stop_exit_only and platform_exit_only. I know it's a bit complicated, but please could anyone help? :)

Hmm, I have not heard of those before.  Are they documented anywhere?

**Comment by Lukas458** [comment]
Yes, it seems they are, please for example take a look here: https://wiki.openstreetmap.org/wiki/Tag:route%3Dbus
and then look under "members"
