### ISSUE TITLE
Upload button not showing

### ISSUE THREAD

**Issue by FTABoy** [openstreetmap/iD#4948]
hello , after i did some changes using iD , when i clicked the Save button and then i clicked Upload button the uploading process took so long time and then site showed me an error saying some thing like : error occurred please check your internet connection.... here i notice my internet connection is dropped(disconnected after pressing save button). reconnected to internet but still couldn't upload my changes, soi closed FireFox tab and reopened iD editor which it asked me to restore the previous changes so i did and i can see my changes :) but when i try to save and upload them , here is the problem. Upload button is not showing up! :( so basically i lost all my changes , this situation happened couple of time before to me and our group member. please take a look at screen shot bellow. thanks.
![untitled](https://user-images.githubusercontent.com/25687276/37966797-c015b12e-31de-11e8-81e6-cab34efca0ba.jpg)

**Comment by geoaria** [comment]
This problem was created several times for me. It is very unfortunate that after the overall change, we will encounter this message and not upload the changes.
Unfortunately, switching the Internet browser was also not worth it. (i.e. chrome, firefax).

**Comment by bhousel** [comment]
Yeah this is a frustrating bug, and we haven't been able to track it down yet. see #4108 

The fix seems to be to undo your changes back to a certain edit that caused the issue.  I don't think anybody has figured out yet what kind of edit it is that causes the issue.
