### ISSUE TITLE
`only_straight_on` shown as `no-turns`

### ISSUE THREAD

**Issue by srividyacb** [openstreetmap/iD#4952]
iD shows `only_straight_on` restriction as `No Turns` while listing the relations in a junction. This is confusing for a mapper seeing two different ways of showing a same relation type. 

_There is nothing incorrect about interpreting `only_straight_on` restriction as `no-turns`_
Having the names consistent according to tagging schema will be easy for mappers to follow what restriction is added.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/3423533/38027258-afcc5cfe-32ac-11e8-929f-15b04b1be50f.png">

cc @bhousel

**Comment by bhousel** [comment]
I agree. Also for clarity and consistency, I think all the `no_` restrictions should say "No" and all the `only_` restrictions should say "Only".

I also noticed that we don't have a `only_u_turn` preset (they are rare but we should support this), so I'll create that today while I am making the names a bit more consistent.

**Comment by bhousel** [comment]
looks like this now!

<img width="374" alt="screenshot 2018-03-28 16 03 37" src="https://user-images.githubusercontent.com/38784/38053298-b97b26be-32a1-11e8-86eb-a3ee052175fb.png">

**Comment by srividyacb** [comment]
Awesome @bhousel 🎉 I am not able to see it in OpenStreetMap iD 🤔 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/3423533/38083693-f7b3b48e-3367-11e8-82b7-16436e737880.png">

**Comment by bhousel** [comment]
> Awesome @bhousel 🎉 I am not able to see it in OpenStreetMap iD 🤔

Yep, @srividyacb we release updates to iD on openstreetmap.org about once a month.. I'll probably do it soon, since we have a few more bugfixes coming this week.

You can try iD on our development site (current copy of code in master) to see the change:  http://preview.ideditor.com/master/
