### ISSUE TITLE
Pressurised waterways presets

### ISSUE THREAD

**Issue by gustavecha** [openstreetmap/iD#4957]
Recently, waterway=pressurised was reviewed on osm wiki, encouraging the use of waterway=* key to map not only free space but pipe flow waterway features also, with content (waterway) vs containers (tunnels, pipeliens...) distinction 
​https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dpressurised

It may be good to add some new waterway presets as follow on iD:
==Penstock==
    waterway=pressurised
    man_made=pipeline
    substance=water
    location={underground,overground}
    usage=penstock
    name=*
    operator=*
    diameter=*
    material=* 

==Pipe flow tunnel (different from canal, canal is always free space - even underground) ==
    waterway=pressurised
    usage={headrace,tailrace,transmission,irrigation}
    location=underground
    tunnel=flooded
    name=*
    operator=* 

==Canal preset should be updated as follow==
    tunnel={culvert,flooded}
    usage={transportation,transmission,irrigation,headrace,tailrace} 

Main validation rules :
    usage=penstock requires man_made=pipeline and waterway=pressurised
    tunnel=yes and waterway=pressurised requires man_made=pipeline
    tunnel=flooded is highly improbable with man_made=pipeline
    waterway=canal shouldn't be used with tunnel=yes
    waterway=pressurised requires tunnel=flooded or man_made=pipeline 

It may be possible to render pressurised waterways with grey or white casing depending it is inside tunnel or pipeline.

These are all suggestions to make presets more comprehensive. Feel free to implement part of it only.

**Comment by bhousel** [comment]
Since this tag currently only has 24 uses, let's see if it catches on more before we add a preset for it.

Also from reading the tagging guidelines and the proposal, this looks like the sort of feature that a novice mapper wouldn't really be able to add correctly.  I worry that if we add this preset to iD, we would see more people using the tag incorrectly (to map water mains?) instead of correctly (to map hydro power plants?)

**Comment by gustavecha** [comment]
Both water mains and hydro power plants can be mapped with waterway=pressurised
Difference comes with usage=* key

I don't get how this tag can be more and correctly used if you expect novice mappers to act as advanced mappers (look at several wiki page on their own without editor guidelines)

**Comment by gustavecha** [comment]
Point is the current canal preset on iD have to be updated with usage=* key nevertheless how confusing waterway=pressurised can be
