### ISSUE TITLE
add billboard and column advertising preset?

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#4961]
Hello,
I think it could be a good idea to add presets for advertising=billboard and advertising=column, isn't it? Both are in very common use.
And some further: In the preset for amenity=clock, there is the key faces=* missing.

**Comment by bhousel** [comment]
Thanks for the suggestions!   iD already has a preset for `advertising=billboard`

We can:
- [ ] add preset for [advertising=column](https://wiki.openstreetmap.org/wiki/Tag:advertising%3Dcolumn)
- [ ] add [faces](https://wiki.openstreetmap.org/wiki/Key:faces) field to `amenity=clock`

**Comment by Xavier-J-Ortiz** [comment]
@bhousel I'll be happy to take this issue and get started on this soon.

**Comment by Lukas458** [comment]
Thank you! :)

**Comment by bhousel** [comment]
This was done..
