### ISSUE TITLE
Tell user better that his attempt to make a building edges squarer failed

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4965]
Some times if the angles are too skewed, the "square" function in the context menu does nothing.
One has to keep a sharp eye to see if it really does something or does nothing.
Therefore I propose that some kind of signal be given to the user if it fails.
E.g., a unhappy face that floats up and disappears.

**Comment by jidanni** [comment]
(At this point he would go back and adjust the angles and try again.)

**Comment by jidanni** [comment]
In fact the Square choice should be greyed out if it won't do anything.
But on the other hand, that would make the user think there was no way to ever use it.
So maybe it should just have a "🚫" mark on it there in the menu. With a mouseover saying his building is not squared enough yet.

**Comment by hikemaniac** [comment]
iD already gives visual feedback when the modified object is not even close to being rectangular.
![not squarish warning](https://user-images.githubusercontent.com/31667811/38365210-bd8b4c3a-38db-11e8-9708-acc32563b3e9.gif)
However it is really a bit unobtrusive. Maybe this could be improved, but I don't really have any good ideas about it.

**Comment by bhousel** [comment]
As @hikemaniac , iD already does this, if the object is really not at all "squarish".

If the object is "almost square" it can be difficult to tell whether the Square operation does anything, but I don't see that a serious enough issue that we need to spend development time on.  I think users can figure out whether something needs more squareness or not just by looking at it.

**Comment by jidanni** [comment]
Ahh... I see what the case I am talking about is!

It is the case where we expect all four corners to be made into right angles.

And when we click, e.g., only A and B are made into right angles. But not C and D, because they are too far from being right angles.

Now if our eyes are only looking at A and B we will think the operation succeeded.

If we are only looking at C and D we will think the operation failed.

If we click again we will see nothing happening, so think something is wrong.

Anyway, never in out wildest dreams did we think "square the corners of this area" would only work on **some** of the corners!

**Comment by jidanni** [comment]
Also if repeated operations do nothing, maybe do like the image you posted, saying that all the squaring possible has already been done.

As often we are operating on small objects and can't really be sure the operation has succeeded or not.
