### ISSUE TITLE
oneway=reversible is probably confusing in preset list 

### ISSUE THREAD

**Issue by SK53** [openstreetmap/iD#4970]
Anecdotally I, and others, have noticed an uptick in the use of oneway=reversible by new contributors. In the main they seem to believe that it is a synonym for twoway operation. 

I would suggest that reversible & alternate are sufficiently uncommon occurrences to warrant not being directly supported in the iD presets if this causes confusion.

Examples edits:

- B-road in English Midlands: https://www.openstreetmap.org/way/62683327#map=17/52.33541/-1.17866
- Danish cyclepath: https://www.openstreetmap.org/changeset/57869335
- Major road in Nottingham: https://www.openstreetmap.org/changeset/57603811
- Inner ring road Aurillac: https://www.openstreetmap.org/way/4602724#map=16/44.9294/2.4493

Note that although the reversible/alternate tags could be used on narrow 1-lane roads and bridges where traffic flow is controlled by signals this does not appear to be the general practice (at least in the UK 1 instance).

Alternative approaches to improving clarity would be to describe the implicit (no oneway tag) and explicit (oneway=no) options as two way rather than negations of oneway.

**Comment by bhousel** [comment]
Yes, I've seen a few too.. I think it's important to support these tags, but maybe we should change it so that the user can only enter them via the tag editor (not just toggling the checkbox).

**Comment by SK53** [comment]
I think that is pretty close to what I had in mind but failed to express very clearly.
