### ISSUE TITLE
Allow connecting nodes of a self-intersecting way when alt key is pressed

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4971]
In some cases such as resolving self-intersections it would be desirable to be able to connect nodes of a self-intersecting way to another object when overriding the checks with the alt key. However it is currently impossible to do so, because the alt key also seems to disable the possibility to connect nodes to each other in this case. Is this by design or is it an unwanted behaviour?

**Comment by bhousel** [comment]
The behavior of not connecting when holding down <kbd>alt</kbd> is by design.   

I couldn't think of a good reason to allow connections like that, but we will probably add a feature to allow users to disable the self intersection and other checks (#2929)
