### ISSUE TITLE
History tool: osm.org link for newly created objects

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/iD#4975]
When creating new objects, the history tool link "History on openstreetmap.org" points to the non-existing object `https://www.openstreetmap.org/node/-1/history`. Also the other fields in this toolbox are not immediately obvious (Last Edit "Unknown"). Maybe there's some different way to say: _this is a new object without history_.

![grafik](https://user-images.githubusercontent.com/5842757/38514325-2c1de92a-3c31-11e8-8d89-dbce90a4d7c7.png)

**Comment by bhousel** [comment]
Good suggestion.. it will show this now:

<img width="254" alt="screenshot 2018-04-09 14 33 04" src="https://user-images.githubusercontent.com/38784/38515782-3612915c-3c03-11e8-8c49-2ecfd2d9c693.png">
