### ISSUE TITLE
Custom WMS imagery

### ISSUE THREAD

**Issue by NKAmapper** [openstreetmap/iD#4977]
Now that WMS support is implemented, it would be great to be able to use WMS in the custom background menu as well.

**Comment by bhousel** [comment]
Tagging @vershwal, who is working on replacing the alert box with a proper dialog per #4806

**Comment by jidanni** [comment]
Currently all the user can find is
```
Custom Background Settings

Enter a tile URL template. Valid tokens are:
   {zoom} or {z}, {x}, {y} for Z/X/Y tile scheme... etc.
```
In https://www.alpinequest.net/en/help/v2/maps/on-demand-create#wms_servers they use a elegant $bbox.

**Comment by 1ec5** [comment]
A minimal implementation of WMS background imagery support was added in 2a28a03ca13f68f0d94ae0ca7aedb2b9b4530a3d as part of #7428, which was reverted for unrelated reasons. Reopening this issue to track either restoring 2a28a03ca13f68f0d94ae0ca7aedb2b9b4530a3d or finishing #6915.
