### ISSUE TITLE
OSMlab, and new tiles

### ISSUE THREAD

**Issue by AllroadsNL** [openstreetmap/iD#4979]
When is ID taking over the new tiles?

from editor-layer-index

There are now new 2017 tiles and **actual** tiles (important), people like to use it, we can in JOSM and Potlatsch.

[osm lab, editor-layer-index, last messages.](https://github.com/osmlab/editor-layer-index/pull/329)

**Comment by bhousel** [comment]
The imagery is updated whenever we release a new version of iD.  That should happen sometime this week.
