### ISSUE TITLE
Lit: No: unchecked checkbox very confusing

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4983]
Lit:
[✓] Yes
becomes
[   ] No
when unchecked, but when we try to check it, hoping to create
[✓] No
well... we are instead not supposed to touch it further if we really mean no.

Yes I know what your are doing but you will confuse most of the public.

**Comment by bhousel** [comment]
I think most people can figure out how the checkboxes work.  Users can always just click a few more times to learn what it does.
