### ISSUE TITLE
Reverse Geolocation for changeset not good enough, translation missing

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4989]
After uploading a changeset in Leibnitz, Steiermark (Styria, part of Austria) I see:
![image](https://user-images.githubusercontent.com/5360273/38855247-434a3d86-4223-11e8-84e3-4cb6fcc5c907.png)
The location is Leibnitz (County of Styria and main city there) in the Austrian state of Styria:
https://www.openstreetmap.org/changeset/58159266#map=14/46.7436/15.5616
![image](https://user-images.githubusercontent.com/5360273/38855320-7033bb06-4223-11e8-85fe-8caf79159d55.png)
Koglbauer is the name of a farm and a short road near Leibnitz:
https://www.openstreetmap.org/search?query=koglbauer#map=15/46.7605/15.5298
![image](https://user-images.githubusercontent.com/5360273/38855603-31c9187e-4224-11e8-924b-99662ddd0ed2.png)
So Styria is not translated to Steiermark which would be nice and Koglbauer is not apropriate.

**Comment by bhousel** [comment]
The current code that puts together the location string is here:
https://github.com/openstreetmap/iD/blob/85ae00dd05d998a8fbf14aba1fb78491fec498b4/modules/modes/save.js#L500-L511

What the code does is ask Nominatim to reverse geocode the center of the map where the user is looking when they did the save (their edits might not necessarily be there, but this is the place that they are looking at).

We get a result from Nominatim and iD tries to piece it together into something like City, Region..  

There are some things we can do to improve this.

1. Can you remember what you were looking at when you clicked save on that edit?  If you can give me the lat/long coordinates, I can do the Nominatim lookup again and see what data is returned and maybe pick a better subset of the results, or maybe issue the query better?    (BTW, the Location panel does the same lookup - so if you go to the same place and open that up, it should also say something about Koglbauer, Styria and a bunch more).

2. We could query based on the bounding box where the user's changes were, not necessarily the map where the user is looking at when they click Save.  I'm not sure whether this would be more confusing to a new user though.

**Comment by manfredbrandl** [comment]
I tried again and the map is contains nearly only "Leibnitz Bahnhof" (railstation):
![image](https://user-images.githubusercontent.com/5360273/38936385-edc6e7e8-4320-11e8-8358-f460c3efba43.png)
See https://www.openstreetmap.org/edit#map=20/46.78047/15.54668

**Comment by manfredbrandl** [comment]
This is shown when i do "Objektabfrage" at the red cross:
![image](https://user-images.githubusercontent.com/5360273/38936564-5b38451a-4321-11e8-8975-85477fb0e5c1.png)
Is this "Location Panel lookup"?

**Comment by bhousel** [comment]
> Is this "Location Panel lookup"?

"Location Panel" is this feature in iD  (for me it's <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> to show):

<img width="560" alt="screenshot 2018-04-18 10 03 34" src="https://user-images.githubusercontent.com/38784/38936897-d4d2f488-42ef-11e8-8c70-bb5ef3464535.png">

**Comment by manfredbrandl** [comment]
Koglbauer is also an isolated_dwelling:
![image](https://user-images.githubusercontent.com/5360273/38945484-e6c5d862-4336-11e8-9b97-08d20f74c933.png)
It would be better not to show isolated_dwellings unless they are very near to the map center.

**Comment by skylerbunny** [comment]
_It would be better not to show isolated_dwellings unless they are very near to the map center._

> We get a result from Nominatim and iD tries to piece it together into something...

Doesn't that mean that this is ultimately a problem for Nominatim to solve? All iD is doing is spitting out what Nominatim provides it. If reverse geolocation is finding an isolated dwelling 2.5 miles from where you're editing, that's an issue with them.

It seems like a Really Bad Idea to apply exceptions to what iD says a location "is" as Nominatim gives it, when the appropriate solution is to tell Nominatim to make their RG better. (In fact, an argument can be made that telling iD to make exceptions against Nominatim's RG would actually complicate bug reporting to that project.) Look at it this way: this is bringing visibility to Nominatim's reverse geolocation?

**Comment by skylerbunny** [comment]
To explain my position here: if you want to cut off what "near" means at a certain admin level, that's one thing. 'We will never show an admin_level lower than 8' in the output, because we'll just assume that 8 is close enough to be friendly to the user.'

It would be quite another to start throwing around 'Well, we'll use an isolated_dwelling with a lower admin level of 15, when you're really editing "close to it", EXCEPT if you're not.'

That second kind of "fix" would really make identifying Nominatim problems that come through that query difficult.

**Comment by bhousel** [comment]
> To explain my position here: if you want to cut off what "near" means at a certain admin level, that's one thing. 'We will never show an admin_level lower than 8' in the output, because we'll just assume that 8 is close enough to be friendly to the user.'

Yes, what you said here is what I would do to fix this issue.  I think we can construct our query to Nominatim in way that returns a more regional result.

**Comment by bhousel** [comment]
Ok, I swapped out `suburb` for `town` - this will probably display a more meaningful result on the post-save screen.

For info, here is the query and result.  We are already requesting a result at zoom=13, which seems fine. 

query:
https://nominatim.openstreetmap.org/reverse?addressdetails=1&format=json&lat=46.7804013&lon=15.5466538&zoom=13

result:
```js
{"place_id":"42083160","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"node","osm_id":"3096751413","lat":"46.7706284","lon":"15.5160898","display_name":"Koglbauer, Leibnitz, Styria, 8430, Austria","address":{"suburb":"Koglbauer","town":"Leibnitz","county":"Leibnitz","state":"Styria","postcode":"8430","country":"Austria","country_code":"at"},"boundingbox":["46.7705284","46.7707284","15.5159898","15.5161898"]}
```
