### ISSUE TITLE
Language Names not translated in post-upload-screen

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4990]
It would be nice to allow translation of "de", "en" etc.
![image](https://user-images.githubusercontent.com/5360273/38855813-e112a7aa-4224-11e8-99de-cd4b73bb4ef5.png)

**Comment by bhousel** [comment]
Ah yeah, I punted on that just to get something deployed quickly.  We might actually get this automatically when we do #2457 - I haven't looked into CLDR much lately, but #4964 will start pulling pieces of it into iD as a dependency.
