### ISSUE TITLE
New tag value is lost when tab is used

### ISSUE THREAD

**Issue by Bonbadil** [openstreetmap/iD#4991]
Hello,

When adding tags directly on new or pre-existing nodes and using TAB to add a new one, the new tag is added to the list but not its value:
![lost value of new tag](https://user-images.githubusercontent.com/833234/38862445-41145d8c-4235-11e8-88a8-ba270246483b.gif)
Also, the focus do not return to the first column.

I can reproduce the bug easily, but not systematically, on the same node and in the same changeset. 

I'm using Firefox Developer Edition 60.0b12 (64 bits) on Windows 10. I've several extensions, if you can't reproduce the bug.
The JS console say nothing at this moment.

**Comment by jguthrie100** [comment]
It works with Firefox 59.0.2 on Linux

**Comment by bhousel** [comment]
Thank you for the detailed report!   I will try this out on a few different browsers and see if I can reproduce the issue.

**Comment by govvin** [comment]
I confirm this on Firefox 59.02.
