### ISSUE TITLE
Can't find aera-type presets on polygon directly

### ISSUE THREAD

**Issue by Bonbadil** [openstreetmap/iD#4992]
Hello,

When I add a polygon, I would like to give it a polygon preset, like for a store for example, but ID only show me line-type preset (roads, etc.). I have to add an aera-type tag, like building, to be able to search a store preset.
![cant find polygons presets](https://user-images.githubusercontent.com/833234/38863353-abf2e540-4237-11e8-9361-12066d327cd9.gif)
I hope I'm understandable...

I'm using Firefox Developer Edition 60.0b12 (64 bits) on Windows 10. I've several extensions, if you can't reproduce the bug.

**Comment by bhousel** [comment]
Yep thats #1828!
