### ISSUE TITLE
Empty source tags on changeset

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4993]
Noticed in #4989 that the source tag has an empty value:

> ![](https://user-images.githubusercontent.com/5360273/38855320-7033bb06-4223-11e8-85fe-8caf79159d55.png)

Also seems to be happening for other users; see https://www.openstreetmap.org/changeset/58170337 and https://www.openstreetmap.org/changeset/58161104 for examples.

**Comment by bhousel** [comment]
Thanks for opening @lakedistrictOSM - I agree iD should not write anything here if the source is empty.
