### ISSUE TITLE
Changing the direction of the way should also change the 'decline' value

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#4996]
If you invert the direction of a way which is tagged with [`incline=up`](https://wiki.openstreetmap.org/wiki/Key:incline), iD should automatically change "up" to "down" (and vice-versa) to keep data consistent.

**Comment by bhousel** [comment]
> If you invert the direction of a way which is tagged with incline=up, iD should automatically change "up" to "down" (and vice-versa) to keep data consistent.

I just tested and it looks like iD does this.. Can you point to an example way where it's not working?

**Comment by picsi** [comment]
Apologies! I didn't think iD had this feature so I hadn't even tested it. You're right though, it works perfectly. Thanks!
