### ISSUE TITLE
Blank source changeset tag by default

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#5002]
See for example https://www.openstreetmap.org/changeset/58280255 which I've just created.

It's great to have more changeset tags but a blank source tag if the user didn't add a value for that doesn't make a lot of sense (imagery_used is there of course).

**Comment by bhousel** [comment]
Oh yeah, I just fixed this a few days ago in #4993. I'll release a new version that includes the fix soon.
