### ISSUE TITLE
Gates placed next to road

### ISSUE THREAD

**Issue by Hjart** [openstreetmap/iD#5004]
Inexperienced users quite commonly fail to properly make barrier=gate nodes part of roads (example: https://www.openstreetmap.org/node/5274322323). Routers of course will not be affected by such unconnected gates.

Can iD warn about this?

**Comment by bhousel** [comment]
Hmm, we can do even better and remove `point` from the list of allowable geometries.  
https://github.com/openstreetmap/iD/blob/068305e88a8b902f76828b73e2ac69c4b28d86fd/data/presets/presets/barrier/gate.json#L6-L10

Then users won't be able to create them unless they fall on a line.
