### ISSUE TITLE
Adjust imagery offset: hard with just one third of the screen to compare

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5010]
The user is trying to Adjust imagery offset, but at most he is given only **one third** of the screen to compare. Very frustrating.
![df1](https://user-images.githubusercontent.com/1230959/39279672-063b410e-492d-11e8-9bbe-f321daeaa85f.jpg)
Please invent some new way. Thanks.

**Comment by bhousel** [comment]
Just zoom in, its much easier.

**Comment by jidanni** [comment]
Zooming in is 100% wrong answer.

One needs to compare how roads align with the image in a wide enough
area as possible.

Zooming in and then making our offset would very likely produce a less
ideal offset than if more points were considered.
