### ISSUE TITLE
Events without time are shown in GMT time zone

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/iD#5011]
This event (https://github.com/osmlab/osm-community-index/blob/v0.4.1/resources/south-america/brazil/OSM-br-telegram.json#L26) has the date in `osm-community-index` as `2018-05-16`, but it's shown in iD as `2018-05-15 21:00`. The events with time information are correct.

![screenshot-2018-4-26 openstreetmap](https://user-images.githubusercontent.com/666291/39308225-4e00ae08-493b-11e8-9923-ba5464a5c023.png)

**Comment by bhousel** [comment]
Good catch, thanks for reporting @willemarcel  👍

**Comment by bhousel** [comment]
I got this working (I think)..  String-to-date parsing in JavaScript is pretty strange.  

<img width="300" alt="screenshot 2018-05-12 10 39 26" src="https://user-images.githubusercontent.com/38784/39958466-7d01ac82-55d1-11e8-8da7-97ce349f1de3.png"><img width="300" alt="screenshot 2018-05-12 10 39 33" src="https://user-images.githubusercontent.com/38784/39958467-8145c238-55d1-11e8-83bb-286a7b279598.png">
