### ISSUE TITLE
in ID white dots and everything is gone

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#5014]
I have spent almost 1 hour editing rivers and roads and them sudenly all the ways become white dots, it dosent allow me to save and upload, and all my edits are gone.

What the heck?? 

Any feature to recover this lost data? is anoying that this happen quite often...

**Comment by bhousel** [comment]
Hey @jjiglesiasg sorry to hear it happened again.. You opened this issue already as #4835 - What I said there:
> Unfortunately it's not always easy to know what caused an error like this, but if it happens again, the best course is to open the dev console and look at the errors (for an error like this you'd probably see a lot of "Entity not found" stuff).

I'd really need to know a lot more about exactly where on the map the error occurred and what specific editing steps you did.   If we can reduce it to a few steps, then fixing it should be no problem.
