### ISSUE TITLE
alias equivalent tags

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#5015]
OSM has a few tags which are unambiguously equivalent:

`email` and `contact:email` (246k / 86k)
`phone` and `contact:phone` (1.1m / 240k)
`fax` and `contact:fax` (98k / 52k)
`website` and `contact:website` and `url` (1.4m / 179k / 340k)

iD uses the non prefixed tags for the presets which is fine but for example in the case where `contact:phone` exists the preset won't be filled so it appears it doesn't have phone number so a new user will end up entering it again and we'll end up with both `phone` and `contact:phone` populated.

I propose presets support some kind of tag aliases where these equivalent tags are used to populate the preset.

**Comment by andrewharvey** [comment]
> I think reading from either of two tags would not be too difficult, but knowing which tag to write back to would be complicated.

Ideally iD would write back to whichever tag was originally present.

Corner cases where `phone` and `contact:phone` are both present already, being the same or being different.

> Do you think it would be ok if iD just writes to both tags? (e.g. user enters a phone number and iD sets both phone and contact:phone tags?).

No, I think that would just make the situation even worse. Someone else will come along with another editor and now when they want to change the phone number, they need to change both which is a burdensome and likely they'll miss changing one.

**Comment by andrewharvey** [comment]
> Isn't the only way to really fix this to have the community agree to a mass retag of all the contact information? That's what I suggested on #3915

Probably. Of course I'd prefer we bulk retag either one way or the other, the current situation is confusing for both mappers and data consumers and a mass retag appears an easy solution that's win win, but that's not something we can fix with a PR.

So this issue aims to do the best we can on the editor side to bandaid the problem until such time as the issue is fixed in OSM.

**Comment by matkoniecz** [comment]
> website and contact:website and url

This is not true.

> The website=* tag can be used to provide the full URL to the official website

https://wiki.openstreetmap.org/wiki/Key:website

> This tag is being used for very different types of content - official websites of an amenity or its operator, third-party pages, the object's Wikipedia entry, photographs featuring the object, or even documentation on the OSM wiki.

https://wiki.openstreetmap.org/wiki/Key:url

Maybe de-facto usage is closer than wiki documents, but it is not "unambiguously equivalent".

**Comment by andrewharvey** [comment]
@matkoniecz Is there clear documentation that `website`, `contact:website` and `url` are meant for different things? I can't work it out from the wiki :confused: 

Or do you have example of something which you think is correctly tagged that uses two or more of the tags? That would be really helpful.

> This tag is being used for very different types of content - official websites of an amenity or its operator, third-party pages, the object's Wikipedia entry, photographs featuring the object, or even documentation on the OSM wiki.

I think you could have all of those in any of the keys, or do you see any kind of segmentation between the groups?

That said, Wikipedia has it's own key, photos of the object probably shouldn't be in OSM best to go in Wikimedia Commons and link via wikidata, documentation best in the note key, website of the operator sometimes it can be a link to a specific page for this location.

**Comment by matkoniecz** [comment]
> there clear documentation that website, contact:website and url are meant for different things? I can't work it out from the wiki 

I just linked it. website tag is described as "full URL to the official website". URL tag is described as any sort-of-related website "official websites of an amenity or its operator, third-party pages, the object's Wikipedia entry, photographs featuring the object, or even documentation on the OSM wiki".

Second clearly allows not only official pages but also any other links.

**Comment by jjiglesiasg** [comment]
I am not sure about the website and contact:website but I am sure that having just 1 way to place the phones will be much appreciated either phone or contact:phone but just 1, too many duplicated tags, (ex survey_date and survey:date, etc)

**Comment by andrewharvey** [comment]
To be fair, it's an OSM wide problem that I feel should be solved outside the editor. Marking the redundant tags as deprecated and automatically migrate tags across, leaving a single tag for editors and data consumers, but at the moment it seems working around this in the editor is going to be the path of least resistance.

**Comment by bhousel** [comment]
> To be fair, it's an OSM wide problem that I feel should be solved outside the editor. Marking the redundant tags as deprecated and automatically migrate tags across, leaving a single tag for editors and data consumers, but at the moment it seems working around this in the editor is going to be the path of least resistance.

I agree that tagging is a thing that everyone should have a say in.  I thought that this was a thing that I could push for, but I've kind of given up hope after engaging the tagging mailing list for the past two weeks or so.

OSM is not ready for this.  (It might never be)

**Comment by GoodClover** [comment]
`website` and `url` are different tags (confusing, but that's that).

However afaik all `contact:xxx=` tags are equivalent to their non-namespaced `xxx=` version.

IMO `url` vs `website` is off-topic to this as that is discussion of those two separate tags and not the `contact:` namespace.

`contact:url=` == `url=`
`contact:website=` == `website=`
`url` vs `website` can be considered unresolved/"unknown" for our purposes.
