### ISSUE TITLE
iD suggesting nonsense as first choice

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#5016]
![screenshot_2018-04-30_18-25-09](https://user-images.githubusercontent.com/4283376/39438293-1fa22630-4c93-11e8-814f-3029628c42f4.png)

As far as I can see, the values `signal`(`s`), `crossing`, `pedestrian_crossing` are nonsense for the key `traffic_signals`. These may well be the most used values according to Taginfo, but they are not documented and not self-explanatory so no-one can know what they are supposed to mean!

**Comment by bhousel** [comment]
Yes, iD fetches these suggestions from taginfo, so there is not much we can do about this.  These values are suggested because they are the values that people use in OSM.  

See what I wrote on #4508 
> The OSM community needs to take responsibility for the tags, not expect editors to build in a bunch of extra logic to know which tags are better than which other tags. If sport=football is indeed deprecated, then somebody should make a Maproulette challenge or something to clean them up. iD will stop suggesting the tag when it is no longer in widespread use.

**Comment by M1dgard** [comment]
> not expect editors to build in a bunch of extra logic to know which tags are better than which other tags.

You already have a list of all tags and include logic to suggest useful combinations. Why wouldn't you keep a list of bad tags?

These tags are used 126,759 times. You know how the community frowns upon mechanical edits, so you know this isn't going to get fixed unless Taginfo and/or iD start blacklisting some tags, but you and [Taginfo](https://github.com/taginfo/taginfo/issues/66) consider this out of scope. So we're stuck, this is an unfixable issue?

**Comment by bhousel** [comment]
> These tags are used 126,759 times. You know how the community frowns upon mechanical edits, so you know this isn't going to get fixed unless Taginfo and/or iD start blacklisting some tags or looking at the "status" on the wiki. 

If you're talking about the traffic signals, the values are these:
https://taginfo.openstreetmap.org/keys/traffic_signals#values

There are 1458 with the value `signals` which should probably be renamed to `signal`.  This is not a very large number, and anybody who cares could just change them with overpass/JOSM/level0.   Below that, the numbers are even lower, and I don't see anything that stands out as obvious "nonsense" or "bad".

> Both you and Taginfo consider this out of scope. So we're stuck, this is an unfixable issue?

I don't see it that way. Last year a bunch of people cleaned up all the tags on [250,000 old multipolygons](http://area.jochentopf.com/).  That was a much bigger project, and the community got it done. 

I think for smallish tag updates (< a few thousand, obvious misspellings) someone could just do them in one shot, and for larger projects somebody just needs to tell the community and set up a challenge.

**Comment by M1dgard** [comment]
> There are 1458 with the value signals which should probably be renamed to signal. This is not a very large number, and anybody who cares could just change them with overpass/JOSM/level0. Below that, the numbers are even lower, and I don't see anything that stands out as obvious "nonsense" or "bad".

The main tag to map a traffic signal is **`highway=traffic_signal`**, so `traffic_signals=signal` is a subtag. Indeed: [it is used](https://taginfo.openstreetmap.org/tags/traffic_signals=signal#combinations) prevalently in combination with `highway=traffic_signal`. But it adds no meaning, it is nonsense.

A quick sample of some points suggests all of them are added with iD, starting about 2 years ago, like in https://www.openstreetmap.org/changeset/38976653. Do you have any idea why?

**Comment by bhousel** [comment]
> A quick sample of some points suggests all of them are added with iD, starting about 2 years ago, like in https://www.openstreetmap.org/changeset/38976653. Do you have any idea why?

Yes, `traffic_signals=signal` just means - a normal traffic signal.  It was the most common value in taginfo in late 2016, and I chose it as the default because it is the default.   
see #3838

> But it adds no meaning, it is nonsense.

That's just, like, your opinion man.

**Comment by M1dgard** [comment]
> That's just, like, your opinion man.

Okay if you disagree, no problem. I just wasn't expecting it.

It's already mapped as a traffic signal, so what meaning does it add according to you? That it's a "normal traffic signal"? What would constitute that? And most significantly: how are iD users supposed to figure it out? (And data users for that matter?)

**Comment by 1ec5** [comment]
[This discussion](https://wiki.openstreetmap.org/wiki/Talk:Key:traffic_signals#What_is_traffic_signal.3Dsignal_.28or_signals.29) points out that `signal` and `signals` both refer to a “classic” signal for vehicular traffic at an intersection. Typically, a user will see this field set to `signal` by default when choosing the “Traffic Signals” preset, so I’d be surprised if there’s outright confusion from users about the meaning of this value.

As an alternative to a blacklist, this preset could define a fixed set of allowed values or a whitelist of preferred values in a combo box, labeled with more human-readable names than the raw tag values. (This is also great for non-English speakers: #2708.) Presenting a combo box would require being more opinionated about what’s a valid `traffic_signal` tag and what isn’t, so the existing combo boxes in iD were created for tags where the standard values are generally agreed upon and there’s little tag pollution.

**Comment by M1dgard** [comment]
> Typically, a user will see this field set to signal by default when choosing the “Traffic Signals” preset, so I’d be surprised if there’s outright confusion from users about the meaning of this value.

So they just leave the default without questioning it's the right tag? Even more reason why this has to die.

**Comment by bhousel** [comment]
@M1dgard It's not going to change, and there is nothing wrong with having the field work this way.  

The `signal` value was already the most common value back in 2016 before iD added this default.  

I'm not going to try to explain to users "here's a field for you to use, but don't use it if the traffic signal is a normal kind of signal, only use it if it is a special kind of signal".
