### ISSUE TITLE
Change glaziery preset icon

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5018]
Well, it looks that way.

The same icon is used for a glaziery that is used for a firepit.  I think there is some mistake there.

It's also the same icon that is used for a fire station.  However, in OSM carto fire stations really are shown as a flame symbol.  I think that's very misleading, but that's really a different issue.

Basically, you're using the wrong icon for a glaziery.  Mark something as a glaziery and a flame symbol appears at the top of the info pane.

**Comment by bhousel** [comment]
Hmm, yeah we should change `glaziery.json` to use `"icon": "poi-tool"`  (generic tools icon).

**Comment by eehpcm** [comment]
> generic tools icon

I'm not sure a tools icon is a good match.  Tools are involved in cutting glass, but the product/service is glass cut to requested sizes.  The place I'm thinking of actually does frames and installation too, but glaziery is the closest OSM has to that sort of business.

**Comment by bhousel** [comment]
> I'm not sure a tools icon is a good match. Tools are involved in cutting glass, but the product/service is glass cut to requested sizes.

Oh I see.. We don't need to have an icon for every kind of thing, but what would an icon for this look like?  They install windows?  Or manufacture glass?  I really dont know what a glaziery is.

**Comment by bhousel** [comment]
I drew a simple window icon:

<img width="494" alt="screenshot 2018-06-01 11 45 04" src="https://user-images.githubusercontent.com/38784/40849924-45d47ea4-6591-11e8-9fc4-c374d73944e8.png">
