### ISSUE TITLE
Remove trailing space from shop=health_food preset

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#5022]
When an existing shop=health_food is edited in iD, rather than showing the Health Food Shop preset it just shows the standard Shop preset.

I think this is because of the space in this line of the preset:

https://github.com/openstreetmap/iD/blob/607859eac5524bce17012bcd7652899887afa65a/data/presets/presets/shop/health_food.json#L22

**Comment by bhousel** [comment]
yep, that seems wrong - thanks for flagging..

**Comment by bhousel** [comment]
I just fixed this in 13ed98bd3
