### ISSUE TITLE
Smart handling of `key=value` when pasting tags

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5024]
This is a feature request.
The goals is to make it easier to paste tags from the wiki.
The iD editor could behave smarter in this situation with a very nice UX touch.

### Workflow

1. I tag something, eg `leisure=garden` from the search bar
2. I click [on the wiki-link](https://wiki.openstreetmap.org/wiki/DE:Tag:leisure%3Dgarden) to learn how to tag details that are not part of the presets
3. [I learn about](https://wiki.openstreetmap.org/wiki/Key:garden:type) `garden:type` and copy the tag `garden:type=castle` from the wiki page
4. I go back to iD editor and paste `garden:type=castle` into a new tag on "all tags".

**Current behavior:**

The copied text shows up as key. I have to manually split it and remove the "=".

**Expected / nicer behavior:**

1. iD Editor recognizes that I copied a key-value-pair and splits the pair at the "="-sign into key and value.
2. It then add a new blank tag pair below and thereby completes the tagging and the (i) and such show up next to my tag

**Comment by bhousel** [comment]
I like this suggestion 👍

**Comment by AndreasHae** [comment]
I'm going to work on this

**Comment by tordans** [comment]
A quick thank-you-feedback @AndreasHae: I used it the other day and it was awesome ❤️. Thanks for adding this.
