### ISSUE TITLE
Improve After-Save-Screen: Do not hide languages behinde "more"

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#5030]
The After-Save-Screen shows many entries, most of them hide the languages (and nothing else) behind more. Can we unhide the languages and hide only the other information? Can we translate the language codes?
![image](https://user-images.githubusercontent.com/5360273/39750218-f5d280ac-52b4-11e8-9a1d-ef5569912554.png)

**Comment by bhousel** [comment]
I guess translating the names is #4990 

But I think if we switch from short codes to longer translated language strings, they will definitely need to stay in the "More" pulldown. Some resources like OSMF support many languages.
