### ISSUE TITLE
Exclude weird boundary type names from city name suggestions

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5034]
For example within https://www.openstreetmap.org/relation/4749311 (boundary=religious_administration) address suggestion fields include "Dekanat Kraków-Prądnik" in city dropdown menu in addition to expected "Kraków".

![selection_014](https://user-images.githubusercontent.com/899988/39987924-57c7c640-5766-11e8-8b15-d9f7658830a6.png)

**Comment by bhousel** [comment]
I think it's coming from this block of code: 

https://github.com/openstreetmap/iD/blob/de718002b991febc8053c9edf42167b77699f268/modules/ui/fields/address.js#L84-L99

**Comment by bhousel** [comment]
yeah it's the `admin_level=8` part
