### ISSUE TITLE
gnis:feature_id key can launch the GNIS feature page for an object

### ISSUE THREAD

**Issue by skylerbunny** [openstreetmap/iD#5041]
In the same way that iD allows you to go to a Wikipedia page when the Wikipedia tag exists (with the [->] launch icon, it is possible to do this with GNIS tags using this URL:

https://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:#######

(Where ####### is the GNIS feature ID, and leading zeroes are ignored, which is good, because some of our import data has leading zeroes). This can be very useful when trying to find alt_names, old_names, the endpoints (mouth and source) of a river...and so on. This direct URL, above, is _not_ intuitive, and is in fact described in a FAQ saying 'How do I link to an individual feature record?' https://geonames.usgs.gov/apex/f?p=gnispq:10 .

taginfo tells us that the most frequent appearances of this tag (using the GNIS id) are

gnis:feature_id (1.15M)
gnis:id (331K)
NHD:GNIS_ID (38K)
nhd:gnis_id (37K)

To be honest, it's probably most useful, just as for Wikipedia, if there is one recognized tag to do this external link launch, and by that, that tag would probably be gnis:feature_id. Doing this would eventually winnow down use of the ID into one single tag, and also makes the gnis:feature_id tag itself useful while editing.

**Comment by bhousel** [comment]
It seems kind of useful, but I'm not sure where it would go.  Maybe we could support some kind of links for certain tags that we know contain stable ids to linked data.

**Comment by bhousel** [comment]
I thought more on this and I'd rather not add this.  It sounds too specific to the USA.
