### ISSUE TITLE
motorway_junction node not show when node is dragged

### ISSUE THREAD

**Issue by srividyacb** [openstreetmap/iD#5045]
When a node with `highway=motorway_junction` is dragged to a nearest node, the `motorway_junction` icon is not shown at the merged node. The data at the junction is not affected but the visually it appears like the data is absent.

When the modified data is uploaded, `motorway_junction` icon appears, but while editing the icon is not shown.

To reproduce - follow the steps per 👇 gif at this `motorway_junction` - [OpenStreetMap Link](https://www.openstreetmap.org/node/485358951/history)

![ramp-icon](https://user-images.githubusercontent.com/3423533/40300116-ed4151e2-5d05-11e8-9c96-c97ea5bb6413.gif)

cc @bhousel

**Comment by bhousel** [comment]
Thanks for reporting @srividyacb - that does look like a rendering bug 🤔
