### ISSUE TITLE
Request for power=pole preset

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5051]
I'm not sure if this is a duplicate request, if so, please link to older.

I found this tagging many times, but it seems there is no preset for adding such standalone (power=pole) node.

https://wiki.openstreetmap.org/wiki/Tag:power%3Dpole
https://taginfo.openstreetmap.org/tags/power=pole

Thank you

**Comment by bhousel** [comment]
Yes, we currently only allow the `power=pole` to be a node along a way, for example a `power=line`.  Is it common to need just the pole with no line attached?

**Comment by my-na-me** [comment]
Hi - thanks for reading and checking.

Actually I'm not sure if I understand correctly, or if I didn't tell enough details for my preset request.

> Yes, we currently only allow the power=pole to be a node along a way, ...  

That's fine, if there is a preset available only for tagging key “power”=”pole” on node objects I'm would be very happy.

> Is it common to need just the pole with no line attached?

It's not common to use a pole without a line for my mapping process, and I also think for others. But sometimes you will not be able to see the next pole at the imagery => so there is no option to draw the power_line line (I meant at the beginning without local survey). But this is not my point, I usually don't want do a mapping of standalone power-pole nodes.

I try to explain.

My request is for increasing mapping speed. When I start mapping energy infrastructure (pole nodes and e.g. minor_line lines) I usually start mapping by drawing the pole nodes. For this step it would be convenient to have a preset. Maybe for search-word "pole" should be a preset item available, let’s say "Power Pole", it could be displayed at the left object list, and by selecting(clicking) the item it should automatically fill the "power"="pole" tag to the "All tags (1)" chapter.  So then there is no need to enter manually “power” and “pole“ for each object each time. (Currently I use a workaround: I copy a node with already given tagging "power"="pole" and I paste it to the area of the map where want to add the next pole object…)

Similar if you add a street lamp.
You can put "lamp" in the search-box, the first line of the search result will show "Street Lamp", when you left click on it, the tagging box is automatically filled with "highway"="street_lamp" (and the white color of the node circle area changes and shows a small icon of a lamp). Same I would prefer to have for power pole. (The icon is not important, because after drawing the “power”=”minor_line” tag to the nodes, then the node decreases to a size of a very small dot without icon => the icon is at the end useless)

Or is my common tagging procedure wrong? What is your procedure to map these kind of objects?

So I would appreciate to have a preset also combined which the nice function/feature that the most recent tagging objects will show on the top area of the recent list :-) so it’s even faster to add object 2,3,4, and so on.

Thank you

**Comment by EwenH** [comment]
@bhousel , It would be useful when you are trying to work out where the line goes to and from but what would be better would be that as you drop new nodes on a minor line, it drops a power pole by default.

Even better still would be to check the last node and replicate it if it is a tower or pole on line or minor line. Mapping the 300km line from Darwin to Katherine power line would be so much easier!

**Comment by bhousel** [comment]
> (Currently I use a workaround: I copy a node with already given tagging "power"="pole" and I paste it to the area of the map where want to add the next pole object…)

Oh that's a good way to do it.  I think Copy-Paste is probably what I would recommend for repetitive mapping in iD (street lamps or power poles or [picnic tables](https://blog.mapbox.com/mapping-picnic-sites-on-openstreetmap-dfed0d5e5421)).

If you really want to add the `power=pole` tags very quickly, I'd just draw the line however you want to, then in JOSM do an overpass query to select all the child nodes and add the tag all at once.

#590 also sounds kind of like what you want - the ability to just keep repeat adding the same thing.  I haven't added that to iD yet because I don't want to just add a bunch of buttons for things people want, but rather add another dedicated place for these toggle-able editing states to live (thats #3123)

**Comment by my-na-me** [comment]
Thanks a lot :-)
