### ISSUE TITLE
DigitalGlobe Premium Imagery is wrong

### ISSUE THREAD

**Issue by newnumber2** [openstreetmap/iD#5052]
I use both iD and Potlatch, depending on what I'm doing, so I go back and forth often.  The DigitalGlobe Premium imagery in iD is not the right imagery; I'm getting the right imagery in Potlatch, however.  This problem started just the other day, as far as I can tell.

**Comment by newnumber2** [comment]
However, the Mapbox imagery appears to be the same as the correct DigitalGlobe imagery, so I am using it instead.

**Comment by bhousel** [comment]
Closing - please reopen if the issue still exists!
