### ISSUE TITLE
Make it more obvious when things are filtered

### ISSUE THREAD

**Issue by EwenH** [openstreetmap/iD#5053]
Hi,
  I am trying to place trees in a farmland paddock however they are not displaying in ID 2.8.2 on Google Chrome 66. This appears to have been occurring during May 2018

** Validation Process **
Check changeset 59271085 https://www.openstreetmap.org/changeset/59271085#map=16/-34.2854/141.8505 and you should see four nodes created, all around the two areas of scrub.

Edit the area and you should see two trees to the east and one tree to the north west plus one to the south. All four should show nodes with natural=tree hover no nodes are located at any zoom level. This is the failure
![image](https://user-images.githubusercontent.com/4280493/40548480-387107c8-6078-11e8-8809-08a660d2d8ca.png)

Go to JOSM or Overpass to the area around -34.28331,141.85103 and you will be able to locate the multiple tree nodes (one tree from each past changeset) that exist proving that ID  is not rendering.
![image](https://user-images.githubusercontent.com/4280493/40548651-a3e23f0e-6078-11e8-95b5-d91b2744e965.png)

**Comment by bhousel** [comment]
Hmm weird.. I see the trees.. Do you have points filtered?

![point filter](https://user-images.githubusercontent.com/38784/40548870-f129fb3c-6003-11e8-9992-9fbb6a949229.gif)

**Comment by EwenH** [comment]
@bhousel , Thank you! I must have selected it accidentally when swapping the fill area style. Many thanks
I did notice the "19 hidden feature"s pop up in blue on the status bar but didn't put 2 and 2 together. Now to get rid of the duplicated trees.

**Comment by bhousel** [comment]
Thanks @EwenH - glad there was no loss of data 👍 
I do want to improve iD's filtering behavior to make it more obvious.  This is something that @geohacker and I were chatting about this week.

**Comment by quincylvania** [comment]
This was done in #5876.
