### ISSUE TITLE
Public GPS traces uploaded to OpenStreetMap doesn't include Identifiable

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5057]
Overlays > OpenStreetMap GPS traces
says ```Public GPS traces uploaded to OpenStreetMap.```

I thought "Identifiable" was even more Public than Public.

But maybe this really only means Public.

If not please change it to say "Public or Identifiable or Trackable" ...

Anyway, Identifiable traces I uploaded a week ago still aren't showing up.

**Comment by bhousel** [comment]
Ah yeah this is #2450.. I'll put a note on that ticket to see if anything has changed.
