### ISSUE TITLE
No way to disconnect a line at a point that just happens to have another line joining it

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5058]
No way to disconnect a line at a point that just happens to have another line joining it.
![df3](https://user-images.githubusercontent.com/1230959/40755926-3b997784-64b3-11e8-9e35-d639f78cc420.jpg)
On cannot break the NW-SE into two at that point. Because clicking on it selects the SW-NE line.

**Comment by bhousel** [comment]
I'm not sure what you mean.. From the screenshot it looks like they already are disconnected, and you'd just need to drag the node away from the line.

**Comment by jidanni** [comment]
OK first do something like 'disconnect' then move the point away from the line, to be able to disconnect the line into two portions. OK I think I figured it out.
