### ISSUE TITLE
Power pole should be directly searchable for faster tagging

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5059]
To tag a
https://wiki.openstreetmap.org/wiki/Tag:power=pole
one must first select e.g., Power Switch
and then change Switch to Pole.

**Comment by bhousel** [comment]
There is a preset for power pole.  Pick a node that is already a child of a way and it should be a choice..

![power pole](https://user-images.githubusercontent.com/38784/40780498-8ec6600a-64a6-11e8-88ce-7fc91b6ce7f7.gif)

**Comment by jidanni** [comment]
@bhousel please allow the user to add an independent pole without having to walk through the woods to map the entire way! Else he will just map a transformer instead of a pole.

**Comment by jidanni** [comment]
@bhousel All I know is there is a pole next to the road e.g., there in Alaska. The only one in many miles, and thus an important landmark. The user shouldn't need to trek the swamps to find even one other pole of this perpendicular line.
