### ISSUE TITLE
Support rendering of man_made=pier

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#5061]
Currently piers are just displayed as lines, but should have their own style.
![](https://i.glideservers.com/u/jam7167b249-97fc-453d-9759-9d8d4fdf7d4f.png)

This is also the same for areas :
![](https://i.glideservers.com/u/jam5836b0c5-b513-4f79-9998-9498ae3445f5.png)

**Comment by bhousel** [comment]
Good idea!.. Do you think it would be ok to reuse the "sidewalk/path" line style for these (or something visually similar)?  We also use this kind of rendering for train platforms, crosswalks, and maybe a few other things that should connect to the pedestrian network.

This screenshot shows what I mean - there are several "things you can walk on" in this picture that are cohesive in design, differentiated by color.

<img width="752" alt="screenshot 2018-06-01 12 42 46" src="https://user-images.githubusercontent.com/38784/40852714-553bc6b0-6599-11e8-8518-2b71c3f072e1.png">
