### ISSUE TITLE
Add an option for preferred background

### ISSUE THREAD

**Issue by deuzeffe** [openstreetmap/iD#5063]
Hello, 

As users can choose preferred editor or language(s) in settings, can we have the same for preferred (imagery) background?

Thx for the answer, whatever it is.

**Comment by bhousel** [comment]
Hey @deuzeffe - It sounds like you are asking about the settings on openstreetmap.org, which really falls outside the scope of this issue tracker.   This tracker is just for the iD editor.

iD should usually remember a user's chosen background between sessions.  This is stored in your browser's storage - so the only reason iD wouldn't remember the last background used is if you run your browser in incognito mode or clear out the settings.

Another thing you can do is add the `background=` [parameter to the url](https://github.com/openstreetmap/iD/blob/master/API.md#id-standalone) when you launch iD.  So you could create a browser bookmark that always starts iD with the background that you want to use.

**Comment by deuzeffe** [comment]
Ooops, I'm wrong, of course :( And you're right, obviously! Apologizes... Thx you for help&kindness.
