### ISSUE TITLE
Dutch translation of lanes is wrong

### ISSUE THREAD

**Issue by wdankier** [openstreetmap/iD#5064]
With the road, a user can specify how many lanes it has.
The dutch translation is now 'Rijbanen'
This is the wrong translation. It should be 'Rijstroken'.

When you have a highway with two directions and each direction has 3 lanes:
In Dutch that highway has two 'Rijbanen' and each 'Rijbaan' has three 'Rijstroken'

This is the official terminology, although many people mix up those terms

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/openstreetmap/id-editor/dashboard/), so you should sign up for an account there to fix issues with the translations.  Thanks!
