### ISSUE TITLE
No way to edit bridge

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5076]
See that bridge, "13-059",
https://www.openstreetmap.org/edit#map=23/24.18987/120.86389
well there is no way to select and edit it.

(Its "ref" gets so  loudly rendered in Mapnik
https://www.openstreetmap.org/#map=13/24.1899/120.8639
I had better move it to some other field.)

But it is "underneath" the road, so id cannot get at it.

**Comment by bhousel** [comment]
Oh yeah, iD is not great for working with lines that are stacked on top of one another.. (this is already tracked on #2746 and #1239 and maybe a few others)

One thing you can do is: double-click to add a shared point, then disconnect at that point and you will be able to pull the lines apart and work with them separately.

![colinear](https://user-images.githubusercontent.com/38784/41434191-e5a977f2-6fe8-11e8-95a5-bcc5b659e451.gif)

I agree this isn't at all intuitivie and a better solution would be to be able to select which feature you want to edit.  Maybe we could build something like: right-click there and navigate a "What's here -> Thing 1, Thing 2" hierarchical menu.

**Comment by jidanni** [comment]
(The user probably will first right click, and the only thing he finds in the menu that is usable is "reverse".)
