### ISSUE TITLE
Multipolygon inner/outer

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5080]
Hi,

Sometimes, multipolygons are very big and it's not easy to see, when it creates things strange, where is the pb.
1) A that time, all the ways are in orange : I suggest to put in one color the inner ways, in another color the outer ways and in a third color the ways that are neither inner nor outer
2) I suggest, when the outer way is not closed, to put the nodes making a break in red with a blink that you can easily see even with a big zoom (sometimes I use a road in the multipoligon, the road cross a river and I forget to put the bridge in the relation : very difficult to find it !)
3) it could be great, when we save modifications, to have an alert when an outer relation is not closed. Juste an alert because sometimes it takes a long time to create one and you need to save your intermediate creation before to go on the next day for example.
4) for an object, sometimes you have 2 relations with the same name : a wood on one side of a road and another wood on the other side. When you're adding a new relation, the editor proposes 2 woods with r+number, where 'number' is the number of the relation, which is perfect. I suggest, in the list of relations of one object, to be able to see the number of each relation, for example at the right of the name of the relation (for example in parentheses).

Thanks
Mahabarata

**Comment by bhousel** [comment]
Hey @Mahabarata thanks for the suggestions! I think all these items are covered by existing issues..

> 1. A that time, all the ways are in orange : I suggest to put in one color the inner ways, in another color the outer ways and in a third color the ways that are neither inner nor outer

I think this is #2946 (possibly others) - I agree it should be easier to tell which relations correspond to which features on the map.

> 2. I suggest, when the outer way is not closed, to put the nodes making a break in red with a blink that you can easily see even with a big zoom (sometimes I use a road in the multipoligon, the road cross a river and I forget to put the bridge in the relation : very difficult to find it !)

For this one we have several other already open issues that relate to integrating QA tools (#3452) or displaying on screen warnings (https://github.com/openstreetmap/iD/issues/4787#issuecomment-364979903) which can show you where multipolygons are broken.

> 3. it could be great, when we save modifications, to have an alert when an outer relation is not closed. Juste an alert because sometimes it takes a long time to create one and you need to save your intermediate creation before to go on the next day for example.

I think this is #3130

> 4. for an object, sometimes you have 2 relations with the same name : a wood on one side of a road and another wood on the other side. When you're adding a new relation, the editor proposes 2 woods with r+number, where 'number' is the number of the relation, which is perfect. I suggest, in the list of relations of one object, to be able to see the number of each relation, for example at the right of the name of the relation (for example in parentheses).

I think this is #4211

**Comment by Mahabarata** [comment]
I'm not agree with you : the 1st point is a new suggestion, specific for multipolygons. I found a lot of bad multipolygons because inner or outer are bad for some ways but it's impossible to see because you need to go to every object of the multipolygon to see which one(s) has/have a bad inner/outer.
To highlight under the mouse a member will improve that but sometimes a multipolygon has.a lot of members and to go on every member to highlight it, one after the other, is surely better than what we have today but is quite long
To use 3 different colors is THE solution because you will see IMMEDIATELY the bugs of inner/outer/nothing in the multipolygon (and you will also see immedaitely that all is perfect if colors make the differences). I suggest another thing : to be able to click on one way on the map to go directly on this way to be able to change the bad outer/inner/nothing. Or to highlight not from tje list of the relation to the map but from the map to the list (when the mouse will be over a way on the map, the line of the corresponding way in the list will be underline, like that it will be easy to go to this way in another tab to change it without losing in the first tab the map of all objects of the multipolygon : after the correction in the 2d tab, you will close it, go back to the first tab and open the second bad way in another tab and so on).

I agree with the 2de point ; KeepRight solves the pb I told and to integrate this add-on in ID would be great.

I'm not agree with the 3rd point : the 3130 talks about polygons or ways, I talk of multipolygons where sometimes an outer (or inner) polygon is made of a lot of ways. To solve the 3130 issue will not solve a multipolygon with a hole because multipolygons are not one object but are made of a lot of different objects : ID needs to follow one way after the other to see if it is closed and if 3130 is solved ID will not follow the different ways so ID will not see the hole.

I'm agree with the 4th point : the issue 4211 is the same.

Because of the 1rst and 3rd point, which are new suggestions, please open back this 5080 issue..

Best regards
--------------------------------------------
En date de : Ven 29.6.18, Bryan Housel <notifications@github.com> a écrit :

 Objet: Re: [openstreetmap/iD] Multipolygon inner/outer (#5080)
 À: "openstreetmap/iD" <iD@noreply.github.com>
 Cc: "Mahabarata" <the_mahabarata@yahoo.fr>, "Mention" <mention@noreply.github.com>
 Date: Vendredi 29 juin 2018, 18h49
 
 Hey @Mahabarata thanks
 for the suggestions! I think all these items are covered by
 existing issues..
 
 
 A that time, all the ways are in orange : I suggest to
 put in one color the inner ways, in another color the outer
 ways and in a third color the ways that are neither inner
 nor outer
 
 
 I think this is #2946
 (possibly others) - I agree it should be easier to tell
 which relations correspond to which features on the map.
 
 
 I suggest, when the outer way is not closed, to put the
 nodes making a break in red with a blink that you can easily
 see even with a big zoom (sometimes I use a road in the
 multipoligon, the road cross a river and I forget to put the
 bridge in the relation : very difficult to find it !)
 
 
 For this one we have several other already open issues
 that relate to integrating QA tools (#3452)
 or displaying on screen warnings (#4787
 (comment)) which can show you where multipolygons are
 broken.
 
 
 it could be great, when we save modifications, to have
 an alert when an outer relation is not closed. Juste an
 alert because sometimes it takes a long time to create one
 and you need to save your intermediate creation before to go
 on the next day for example.
 
 
 I think this is #3130
 
 
 for an object, sometimes you have 2 relations with the
 same name : a wood on one side of a road and another wood on
 the other side. When you're adding a new relation, the
 editor proposes 2 woods with r+number, where
 'number' is the number of the relation, which is
 perfect. I suggest, in the list of relations of one object,
 to be able to see the number of each relation, for example
 at the right of the name of the relation (for example in
 parentheses).
 
 
 I think this is #4211
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by bhousel** [comment]
> I'm not agree with you : the 1st point is a new suggestion, specific for multipolygons. I found a lot of bad multipolygons because inner or outer are bad for some ways but it's impossible to see because you need to go to every object of the multipolygon to see which one(s) has/have a bad inner/outer.
> To highlight under the mouse a member will improve that but sometimes a multipolygon has.a lot of members and to go on every member to highlight it, one after the other, is surely better than what we have today but is quite long

Oh, the different colors idea that you describe is how I would implement #2946.  It's not really specific to multipolygons - people want this feature for highlight turn restrictions and routes too.  Basically, each role gets a different shadow color, and we have to make it clear from the UI what the colors mean (having it make sense to an untrained mapper is the harder problem than just drawing a bunch of colored lines on the screen).

> I'm not agree with the 3rd point : the 3130 talks about polygons or ways, I talk of multipolygons where sometimes an outer (or inner) polygon is made of a lot of ways. To solve the 3130 issue will not solve a multipolygon with a hole because multipolygons are not one object but are made of a lot of different objects : ID needs to follow one way after the other to see if it is closed and if 3130 is solved ID will not follow the different ways so ID will not see the hole.

We might not be able to do exactly what you want.  For example, we couldn't really validate a multipolygon in iD that's not fully downloaded from the OSM server.  Also one of the big concerns is surfacing a warning to the user who is not able to actually understand the issue or fix it.  But #3130 is a general catch all for adding more validation, and I think making sure closed ways are actually closed is one of the points in there.

Anyway sorry if we disagree on some of the points, but hopefully we will be improving these items in iD a little more with each new version.
