### ISSUE TITLE
KB shortcut for History not in the help panel

### ISSUE THREAD

**Issue by deuzeffe** [openstreetmap/iD#5082]
Hello,

I find in wiki the KB shortcut for object's history (`ctrl` + `shift` + `H`) but I can't find it in Help-KB Shortcut-Tools. So, where is it shown ?

Thx for the answer whatever it is.

**Comment by bhousel** [comment]
It's on the "Tools" section:

<img width="779" alt="screenshot 2018-06-16 10 48 11" src="https://user-images.githubusercontent.com/38784/41499715-d27ccc68-7152-11e8-94ad-c3f27087129e.png">
