### ISSUE TITLE
Add building and bench fields to amenity=shelter preset

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#5084]
https://wiki.openstreetmap.org/wiki/Tag:amenity=shelter and https://taginfo.openstreetmap.org/tags/amenity=shelter#combinations

- The building field already exists in iD so should be easy to add
- The bench field can just be a simple yes/no toggle that adds bench=yes/no (just like the covered field on amenity=bicycle_parking)

**Comment by bhousel** [comment]
Doesn't `amenity=shelter` imply `building`?  The wiki page doesn't suggest adding an explicit `building=yes` but I'd definitely do that if it's what people want.

**Comment by lakedistrictOSM** [comment]
I thought not since osm-carto doen't show them as buildings (eg https://www.openstreetmap.org/way/598060975).

Also some shelters such as http://www.geograph.org.uk/photo/3196749 can't really be classed as buildings, whilst some sturdier structures (eg http://www.geograph.org.uk/photo/4262832) are definitely buildings. So a building field would be useful, with the default being no building tag added (as on leisure=sports_centre).

**Comment by matkoniecz** [comment]
> Doesn't amenity=shelter imply building?

I would not expect that, though building key in OSM has extremely wide coverage.

For example, at least I would not tag https://wiki.openstreetmap.org/wiki/File:R%C3%A9union_Ma%C3%AFdo_kiosque_pique-nique.JPG as a building

If I would encounter https://wiki.openstreetmap.org/wiki/File:Mudeford_De_Havilland_Way_bus_shelter.JPG tagged as building I would remove building tag from it.

>  The wiki page doesn't suggest adding an explicit building=yes

I changed wiki, https://wiki.openstreetmap.org/w/index.php?title=Tag:amenity%3Dshelter&diff=1619462&oldid=1523609 hopefully for better

> I thought not since osm-carto doen't show them as buildings

I would not use osm-carto as a good oracle for tagging conventions, especially for tricky cases.

**Comment by bhousel** [comment]
Ok I started a discussion on the tagging mailing list [here](https://lists.openstreetmap.org/pipermail/tagging/2018-June/037283.html)

It sounds like people are in agreement that while many shelters are buildings, there are enough that don't fit the criteria, so we should include a field for it and not assume.

**Comment by lakedistrictOSM** [comment]
@bhousel FYI - currently building=yes is being added automatically with the Shelter preset

**Comment by bhousel** [comment]
> @bhousel FYI - currently building=yes is being added automatically with the Shelter preset

Yes, I think this is the right thing to do.  Most shelters probably are largish permanent structures, and up until recently we were just assuming all the shelters were buildings.  Mappers can remove this tag if they're mapping temporary shelters or very small shelters (like at bus stops).

For example, I'd put a building tag on the gazebo pictured in the example picture:

<img width="300" alt="screenshot 2018-06-29 11 52 19" src="https://user-images.githubusercontent.com/38784/42102136-0d55582e-7b93-11e8-84cb-e249859c0f6b.png">

**Comment by lakedistrictOSM** [comment]
Thanks for the explanation. I agree that this is the best approach. 👍

**Comment by Lee-Carre** [comment]
> Doesn't `amenity=shelter` imply `building`?

They're related, but distinct.

Shelters can be different classes of buildings, depending on context.
Sometimes `building=roof`, sometimes an entire (wilderness / alpine) cabin (that may have a fireplace).

Building type doesn't imply particular shelter type, either. I've seen (surveyed) `building=roof` which have sometimes been a weather shelter, and sometimes for public transport.

For the likes of weather shelter, sometimes non-buildings also count.

iD shouldn't mess with existing (especially source=survey) tagging, unless obviously necessary (replacing values, radically changing the nature of the feature).

---

I've encountered this removal of `building=yes` tags recently, with other categories; such as tagging a building outline with what that building hosts (e.g. an amenity). So, preserving building tags should be across the board of presets.
