### ISSUE TITLE
Bug : separate 2 ways

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5086]
Hi,

I cut a way in 2 parts, then I separate the 2 parts, then I select one of the part.
If, with my mouse, I try to move the node at the separation, the node which is moving is everytime the one of the 2de part of the way (I mean, when you follow the direction of the way) rather that the node of the part I have selected.
So your need to put this node at another place, to move the node of the part you have selected at the good place, then to try to put back the node you didn't want to move at the place where it was : not great at all.

Thanks
Mahabarata

**Comment by bhousel** [comment]
I agree, this should be better.. I think what you're describing is #2206
