### ISSUE TITLE
Don't add width=0/lanes=0 if no value has been entered

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#5087]
If the cursor is in a empty width or lanes field (of a path/road preset), iD (since v2.9.0?) adds width=0/lanes=0 tags. I think this is dangerous as it can go unnoticed.

Steps to reproduce this problem:

- Select or draw a path or road with no width or lanes value
- Click in the width or lanes field (or jump there from the field above by pressing the tab key) but don't enter any value
- Click anywhere on the map
- Select the path or road again
- There's now a 0 in the concerning field (i.e. width=0 or lanes=0 has been added)

![untitled](https://user-images.githubusercontent.com/14875493/41506506-7d764fbe-721f-11e8-8928-8bf5b76c9f2d.gif)

**Comment by bhousel** [comment]
Thanks for flagging @SelfishSeahorse - I just fixed this.. 
I'll put out a new iD release early this week 👍
