### ISSUE TITLE
iD permits single-character changeset comments

### ISSUE THREAD

**Issue by Carnildo** [openstreetmap/iD#5091]
For unknown reasons, newbie mappers who can't think of a reasonable changeset comment are attracted to entering a single period as a comment.  Disallowing this and other single-character changeset comments might not get them to use meaningful summaries, but at least it'll force them to use ones that are easier to click on in the history.

**Comment by bhousel** [comment]
Yeah, we discussed a bit on #4457 but couldn't come to a reasonable limit of how many `.`s we want to make the user type.  Some people think a comment like `....` is better, but personally I don't think it conveys any more information than `.` .

I wrote this, and still think it's true:

> My opinion here is that if you find that a user is leaving cryptic comments, and if it is causing problems for reviewers, you should feel comfortable to contact them on a changeset discussion and ask for more information.
> 
> Even a message like "Thanks for adding these buildings, but I had a difficult time knowing what you did - can you leave a more thorough comment next time?" sends a message that someone is watching what they do, and just this knowledge (more than any technical hack I can add to the editor) will lead to them being a more useful participant in OSM.
