### ISSUE TITLE
Orthogonalizing paths

### ISSUE THREAD

**Issue by Ekleog** [openstreetmap/iD#5093]
Hello,

I just wanted to orthogonalize a path, and couldn't figure out a way to do so with iD. It looks like the “square” option (for areas) is replaced with a “straighten” option (for paths).

Is there a rationale for not supporting squaring paths? As squaring is strictly more powerful than straightening, I don't really understand why the two are treated differently.

Anyway, thank you for your work!

**Comment by bhousel** [comment]
> Is there a rationale for not supporting squaring paths? As squaring is strictly more powerful than straightening, I don't really understand why the two are treated differently.

I don't know why either.  You can currently orthogonalize a closed path, but not an open one.. I think the squaring algorithm only works on closed paths, but maybe we could change that.

**Comment by tordans** [comment]
Does this example fit this usecase? It would be awesome to be able to "square" this line in having 90° angles:

<img width="374" alt="bildschirmfoto 2018-09-17 um 07 29 13" src="https://user-images.githubusercontent.com/111561/45607283-aea28480-ba4b-11e8-8c5d-4d8fc7bbbc45.png">

[Source](https://www.openstreetmap.org/edit#map=20/52.49235/13.47920)

**Comment by bhousel** [comment]
> Does this example fit this usecase? It would be awesome to be able to "square" this line in having 90° angles:

Yes, exactly!
