### ISSUE TITLE
Custom Overlay

### ISSUE THREAD

**Issue by Kimball31** [openstreetmap/iD#5094]
It would be helpful to have the option of adding a custom layer as an overlay (not a background).

**Comment by bhousel** [comment]
Yep this request is being tracked on #3773 and #2095

**Comment by Kimball31** [comment]
I thought  #3773 and #2095 were for background transparency, and multiple backgrounds.  If they apply to overlays then I agree. I don't need to adjust transparency, or have more than one.

**Comment by bhousel** [comment]
> I thought #3773 and #2095 were for background transparency, and multiple backgrounds. If they apply to overlays then I agree. I don't need to adjust transparency, or have more than one.

Ah yeah, sorry, it's not very clear from the issue description, but I'm considering them both to apply to overlays too.
