### ISSUE TITLE
Add name field and search terms to natural=cliff preset

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#5095]
Wiki also suggests adding `height=*` but taginfo says that <1% have this tag so not sure if you want to add height too.

On a related note I always have to check the wiki page to remember which side the top of the cliff should be - any progress with #1475?

**Comment by bhousel** [comment]
> Wiki also suggests adding height=* but taginfo says that <1% have this tag so not sure if you want to add height too.

Sure, you can add both `name` and `height`.  Even if it's not used that often, it sounds like something people would want to add.

**Comment by bhousel** [comment]
> any progress with #1475?

Oh I haven't looked at it in a while.  It wouldn't be too difficult to do - for certain lines with interesting tags, we could draw an extra svg stroke beneath it.

**Comment by lakedistrictOSM** [comment]
At the same time these search terms can also be added: "crag" "rock face" "scarp"
