### ISSUE TITLE
Add DGT's two aerial photo layers for Portugal

### ISSUE THREAD

**Issue by ViriatoLusitano** [openstreetmap/iD#5096]
_Direção-Geral do Território_ ([DGT](http://www.dgterritorio.pt/a_dgt/)), Portugal's department of land use and town planning, freely [offers two types of aerial photos](http://www.dgterritorio.pt/dados_abertos/ortofotos/) under the European directive INSPIRE.

The first contains 50 cm resolution aerial photos for the [entirety of mainland Portugal](http://snig.dgterritorio.pt/geoportal/catalog/search/resource/detailsPretty.page?uuid=%7BF23EFF42-2C28-478A-BD9D-2FF9CDF2C461%7D) dating from 2004-2006. 

The second has recent and high-quality 10 cm resolution aerial photos of [territory near the coast](http://snig.dgterritorio.pt/geoportal/catalog/search/resource/detailsPretty.page?uuid=%7B00242A87-0287-4449-8387-1FE8E125A1D7%7D) dating from 2014-2015.

Both are [already included in JOSM](https://josm.openstreetmap.de/wiki/Maps/Portugal), so it would be without a doubt a beneficial addition to the project for those that map in Portugal.

**Comment by bhousel** [comment]
Hi, thanks for the report. iD's background imagery sources come from the [editor-layer-index](https://github.com/osmlab/editor-layer-index) project. Can you open the request there?

(We do have a bunch of volunteers that regularly pull sources from the JOSM page into the editor-layer-index, so it might have been done already)

**Comment by manfredbrandl** [comment]
@ViriatoLusitano at preview.ideditor.com/master one can see that good WMS-Services are available as backgrounds:
![image](https://user-images.githubusercontent.com/5360273/41660879-a028bbca-749d-11e8-8fa7-7d2917ee80fb.png)
Are these the ones you requested?
