### ISSUE TITLE
Zoom level is too high after searching for a node

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5099]
Search for a named building somewhere off the visible map area and iD zooms in to a level suitable to fill as much as possible of the map area with the building.  I just tried with a typical house and got level 22. This is good.  Maybe a little high, but I can see something sensible has been returned and change the zoom as necessary.

Now do the same for a named node.  Such as _Cardigan_ (a town in Cardigan, Wales).  Zoom level is 24 and all that can be seen is a vague blur of background imagery zoomed far beyond what is sensible, with a few segments of ways that could be anything.  Only at zoom level 22 does it start to become intelligible.

I suggest limiting the zoom to 22 (maybe even 21) when the search result is a node.  Maybe even lower than that, because some nodes do not make much sense without more surrounding context.  A level 24 zoom just leaves people wondering what has gone wrong because everything is a blur.  It's even worse for _St Dogmaels_ (a village in Pembrokeshire, Wales), which is in the middle of a field and probably ought to be moved closer to the centre of the village.

**Comment by bhousel** [comment]
Good suggestion, thank you!   I adjusted the default max zoom for points to z19.
