### ISSUE TITLE
Roads are too wide near the equator

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#5101]
Roads seem too wide at z17 in areas near the equator, such as [in central Vietnam](https://www.openstreetmap.org/edit#background=Bing&map=17/15.88910/107.64853):

![vietnam](https://user-images.githubusercontent.com/1231218/41740844-2d0363f0-754e-11e8-8cac-adff9beeda0a.png)

This road width can easily obscure nearby features, forcing the mapper to use wireframe mode more frequently and discouraging mappers from using more prominent `highway` tags as they would in higher latitudes.

That same width is much less pronounced at z17 in areas farther from the equator, such as [in Ohio](https://www.openstreetmap.org/edit#map=17/38.95079/-84.23186) in the Midwestern United States, due to the vagaries of Web Mercator:

![ohio](https://user-images.githubusercontent.com/1231218/41740935-741057f8-754e-11e8-9ade-97be9f12f2dc.png)

Perhaps the threshold for making roads thin and wide should vary not only by zoom level but also by latitude. Better yet, it could be based on a real-world distance; iD could convert from pixels to meters at the current latitude to decide whether to draw wide or thin roads.

/ref #1520

**Comment by bhousel** [comment]
Good suggestion.. We currently just stick a `low-zoom` css class on the map when the user is z16.  We could use a sliding scale based on latitude to decide when this class gets added.
