### ISSUE TITLE
Searching presets for "street" should bring up various types of road

### ISSUE THREAD

**Issue by Carnildo** [openstreetmap/iD#5103]
If you create a line in iD and do a preset search for "road", you get a wide selection of road-like tags to choose from.  If, on the other hand, you do a preset search for "street", the only option that looks even remotely street-like is "Living Street".

This could explain why new users tend to tag their newly-added ways as `highway=living_street`.

**Comment by bhousel** [comment]
Good suggestion 👍

**Comment by althio** [comment]
Good suggestion indeed @Carnildo and thank you for adding it @bhousel 

I am a bit surprised though that the term 'street' is applied to those presets:
- motorway
- trunk
- motorway link

**Comment by bhousel** [comment]
> I am a bit surprised though that the term 'street' is applied to those presets:
> 
> motorway, trunk, motorway link

yeah I just added it to everything
