### ISSUE TITLE
Refactor /services `loadTiles`

### ISSUE THREAD

**Issue by thomas-hervey** [openstreetmap/iD#5104]
Several services, including the image viewers like openstreetcam, mapillary, and streetside (along with notes and osm) require loading tiles. Besides checking for nullIsland (as the image viewer ones do), all of these files load tiles in a very similar way. See [openstreetcam](https://github.com/openstreetmap/iD/blob/2786974210f43e4ef62f0b23c4906f72caba4867/modules/services/openstreetcam.js#L107-L118) for example.

This could probably be refactored to a utility.

**Comment by bhousel** [comment]
Yes!  Strong 👍 on this one..
It's been something I've wanted to do for a while.

We do kind of have a utility already in [`d3.geo.tile.js`](https://github.com/openstreetmap/iD/blob/master/modules/lib/d3.geo.tile.js), so it might make sense to:
1. move a lot of the common code into there
2. while also adding the capability to use variable tile sizes (it's currently hardcoded to 256px)

For historical context, d3.geo.tile is an older library that we pulled into iD and changed a little bit.  The version we use works fine for our use.  An old version of it lives [here](https://github.com/d3/d3-plugins/tree/master/geo/tile) and hasn't been updated in years.  That d3 plugins repo is not maintained anymore. 

I think the best way forward might be to move our internal `lib/d3.geo.tile.js` module into a `/util/utilTile.js` module with a new name so it wouldn't be confused with the old D3 v3 plugin, then give it the superpowers listed above.

**Comment by thomas-hervey** [comment]
Several changes made in master after this merge including https://github.com/openstreetmap/iD/commit/e4d829ec06ccc9d73a8e45b8c627f95ca8fb0395 https://github.com/openstreetmap/iD/commit/d1fe81b9053d47e85dc0dfd687679f6e59afe95d https://github.com/openstreetmap/iD/commit/ff64455370b9a49679145d0b3e83c014e5d940c0 https://github.com/openstreetmap/iD/commit/02713e48fbeaa95fe3b82e4eae6c5c994f0cc262

**Comment by bhousel** [comment]
I'm still working on a few more cleanups, and supporting sizes other than 256px.
