### ISSUE TITLE
Dropdown for royal_cypher doesn't show most popular values

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#5109]
When [royal_cypher](https://wiki.openstreetmap.org/wiki/Key%3Aroyal_cypher) is added in all tags, it doesn't show the most popular values in the dropdown.

This is what it shows:
![royalcypher id](https://user-images.githubusercontent.com/20193716/41814374-10192a2c-7742-11e8-9945-e95fc1bdb883.png)

These are the top values ([from taginfo](https://taginfo.openstreetmap.org/keys/royal_cypher#values)) which it should show:
![royalcypher taginfo](https://user-images.githubusercontent.com/20193716/41814376-20c57fb0-7742-11e8-92df-fd1bd36b79f8.PNG)

It seems to ignore the values in all caps for some reason.

**Comment by bhousel** [comment]
Oh yeah this is like #3377
Most of the time iD ignores results from taginfo that begin with capital letters, but we have a whitelist for tags that are allowed to autocomplete this way.

I wrote on that issue:
For most fields in OSM (cuisine, religion, denomination) it's the behavior we actually want.
e.g. prefer "french" instead of "French"... prefer "catholic" over "Catholic".

**Comment by pnorman** [comment]
Whitelisting is the easy solution - perhaps an inherently "more correct" one is to ignore the one with capital letters when case insensitive matches something earlier in the list.

I'd probably just edit the whitelist ;)

**Comment by bhousel** [comment]
> I'd probably just edit the whitelist ;)

Yep - the history for this line of code is pretty great..

https://github.com/openstreetmap/iD/blob/a5b8e4b8bd4d1704e0e2896253058de2f19bae08/modules/services/taginfo.js#L263-L267

A more correct solution would probably be to filter whatever we receive from taginfo and keep only the most popular string in situations where there are multiple strings that disagree in how they are cased.

**Comment by bhousel** [comment]
I ended up just adding it to the whitelist and closing the issue
