### ISSUE TITLE
Can't see my own GPS Traces in iD on Firefox

### ISSUE THREAD

**Issue by osmgit** [openstreetmap/iD#5110]
I can't seem to see any of my own GPS Traces (both old ones and recently uploaded ones) in Firefox Quantum 60.0.2 (64-bit). The strange thing is I can see other people's GPS Traces, just not my own. 

I tried the Firefox mobile browser and my GPS Traces are showing OK just not on PC. It's a little frustrating as I can't edit on mobile.

This has only started to happen recently. My GPS Traces used to display fine. I've checked the Visibility Checklist https://wiki.openstreetmap.org/wiki/Visibility_of_GPS_traces and tried uploading with different permission but they are still not showing.

**Comment by bhousel** [comment]
Can you share a gpx trace that you'd expect to have show up?
Also, if you can open up the developer console in Firefox, it might be able to give some more information about why it won't show the trace.  (Maybe it wanted to download the trace, but refused to because of a mixed content issue - gpx is being served with `http` and iD served with `https`?)

**Comment by osmgit** [comment]
Here's an example of a GPS trace which is uploaded OK, but when I go to the map and turn on the GPS Traces, I can't see it: https://www.openstreetmap.org/user/explorewiki/traces/2730963


>

**Comment by osmgit** [comment]
Firefox Console Log when Viewing the Map:

`Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (508896 px). Occurrences of will-change over the budget will be ignored.`


Firefox Console Log when Editiing the Map:

`Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.`

**Comment by mmd-osm** [comment]
Aren't those traces pulled in as PNG layer via https://{a,b,c}.gps-tile.openstreetmap.org? Can you see your traces on https://gps-tile.openstreetmap.org?

I don't recall what the update interval of those GPS trace tiles is, but that might be the root cause for not seeing your traces.

**Comment by osmgit** [comment]
I can see every one else's traces on https://gps-tile.openstreetmap.org, but I still can't see my own traces.

I have given my recent traces over a week to update but I still can't see them. They used to show up within a few minutes. The thing is that I could see all my traces OK just a month ago. and now they are no longer showing for me.

**Comment by bhousel** [comment]
Oh, I guess this is about the generated GPS traces layer - we don't control this.
There are some things you can try on #2450

**Comment by mmd-osm** [comment]
Upstream issue was resolved. This should work now as expected.

**Comment by osmgit** [comment]
Oh great thanks, I'll check it out!

**Comment by osmgit** [comment]
I'm having this problem again, is there an issue with upstream again? I can't see my uploaded GPS traces once again.

**Comment by mmd-osm** [comment]
It was fixed again today: https://github.com/openstreetmap/openstreetmap-website/issues/1980#issuecomment-419708003
