### ISSUE TITLE
Add preset for railway=preserved

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#5111]
https://wiki.openstreetmap.org/wiki/Tag:railway=preserved

Fields should be the same as those on railway=rail

**Comment by bhousel** [comment]
I read up on this one and it looks controversial, so let's not.

**Comment by lakedistrictOSM** [comment]
Hmm, no warnings about its use on the wiki page, just a note saying that OpenRailwayMap don't like it and an alternative way of tagging them. The only reference seems to be a ORM meeting in 2014 - ORM are not OSM. There's also only a single comment on the wiki talk page - so not really enough comments to suggest it's controversial. I can't find any discussions in the tagging list about it being controversial, either.

railway=preserved is used on 10 259 ways
railway:preserved is used on 3 935 ways

railway=preserved also has its own rendering on osm-carto

**Comment by bhousel** [comment]
Sorry, I know it's rough to get a "no" answer, but I don't have the energy to participate in any more tagging discussions for a while.

**Comment by lakedistrictOSM** [comment]
No worries @bhousel, thanks for all your work with iD. 😄 

I might ask on the tagging mailing list in a few months time.
