### ISSUE TITLE
I run unsuccessfully during initialization

### ISSUE THREAD

**Issue by RanQiwu** [openstreetmap/iD#5115]
1. I cloned the project to my local.
2. cd iD 
3. npm install (an error occurred)

Error message：

![_20180629095200](https://user-images.githubusercontent.com/22112008/42069059-20829d0a-7b82-11e8-8f17-1c7a376ab4a3.png)

**Comment by bhousel** [comment]
Hmm, it looks like this is outside our control.. The error says that the `name-suggestion-index` dependency isn't found in the taobao mirror of npm.

**Comment by zhouLion** [comment]
right! In taobao mirror the lastest version of the name-suggestion-index is still 0.1.5.

**Comment by RanQiwu** [comment]
@zhouLion thanks.
