### ISSUE TITLE
Latitude/longitude enhancement request

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5117]
I see something similar was requested in #2583 and rejected as being out of scope for iD.  But there are reasons why this would be an actual enhancement to functionality.

Suppose you are given the lat/long of an object.  It's possible.  You contact some company by e-mail, can't figure out their exact location without referring to impermissible sources, so you ask them to give you lat/long of where they are.  Most people can do that one way or another, but asking them to send you a GPS trace in a format you can use is a lot harder for them.

So you have a lat/long.  I can type that into the search box of OSM itself: it takes me to the area and pops up a marker.  There doesn't seem to be an equivalent mechanism in iD.  So the only way I could get it to work as put my finger on the lat/long marker so I could use the leave a note facility to add a note where the lat/long marker was.  Then use a Mark I eyeball to compare the OSM map and the iD map and drop a node in roughly the right position.  Then use the aerial imagery to refine things.  It worked, but it's a real pain.

So some equivalent mechanism in iD would make life a lot easier.  Perhaps also use the empty space at the bottom of the window between the distance scale and the "Edits by" to display lat/long of the pointer.  To prevent it slowing things too much, maybe only provide lat/long when in add an object mode.  Or maybe have a button at the right to toggle the lat/long display.

**Comment by bhousel** [comment]
#3088 and #4197 contains some more reasons why we would prefer to not allow people to enter lat/lng coordinates directly.

> So you have a lat/long. I can type that into the search box of OSM itself: it takes me to the area and pops up a marker. 
> ...
> So some equivalent mechanism in iD would make life a lot easier.

Yes, you can do this in iD's search field too.  Paste a lat/lng into the search field, and iD will go there, then you can place place your point where it needs to go.

![latlng](https://user-images.githubusercontent.com/38784/42174849-9195e62a-7df1-11e8-8ffc-afa3975f30af.gif)

**Comment by eehpcm** [comment]
Hmmmm, I tried entering lat/long before and it didn't seem to do anything sensible, in that it might have put me in the right area but didn't show where on the map that point was.

However, the shift-control-L thing, which I hadn't realized was there, does everything I need.  It shows where the pointer is.  I can look at the aerial imagery when the pointer is at the right lat/long and add an object.  Or conclude I've been given silly co-ordinates.

As for the reasons you wouldn't add what people were asking for (the location window probably was what they were asking for but didn't phrase it well), are people really stupid enough to extend a way using lat/long and not check the imagery?  They probably are.
