### ISSUE TITLE
Network as preset for ATMs

### ISSUE THREAD

**Issue by theel0ja** [openstreetmap/iD#5119]
I would like to have Network as preset for ATMs.

`network=*` seems to be the tag for that.

https://wiki.openstreetmap.org/wiki/Tag:amenity=atm#Tagging

**Comment by JamesKingdom** [comment]
Now ATM's have a text field for `network`
![](https://i.glideservers.com/u/jamc25f2645-c223-47a0-aeed-21f1109a64f8.png)

**Comment by theel0ja** [comment]
Thank you!
