### ISSUE TITLE
Add site_type to Archaeological Site preset

### ISSUE THREAD

**Issue by shiftee** [openstreetmap/iD#5124]
In Ireland there are many [ringforts](https://en.wikipedia.org/wiki/Ringfort) scattered across the country.
Finding these is trivial using the Old British/Irish maps and the aerial imagery so sometimes I randomly wander around adding them.
The process is a bit tedious as I need to set the site_type and fortification_type keys and values manually.

Can a preset for this be added?

Tags:
    historic=archaeological_site
    site_type=fortification
    fortification_type=ringfort
    name=*

[OSM Wiki Page for Ringforts](https://wiki.openstreetmap.org/wiki/Tag:fortification_type%3Dringfort)

Thanks,
Mark

**Comment by bhousel** [comment]
I don't think it makes sense to add a preset for something as specific as `fortification_type=ringfort`, which has only a very local focus..

But we could add some more fields to the "Archaeological Site" preset to make it easier to map kinds of sites, or maybe add a "Historic Fortification" which has the `site_type=fortification` already filled in (if this is a common thing).

Right not the preset doesn't have very many fields:
<img width="400" alt="screenshot 2018-07-08 22 14 11" src="https://user-images.githubusercontent.com/38784/42427405-5c3059b0-82fc-11e8-9657-9fd1d80f1cef.png">

Also, worth mentioning that if you are mapping a lot of these things with very specific tags set, you can <kbd>Ctrl</kbd>+<kbd>C</kbd> / <kbd>Ctrl</kbd>+<kbd>V</kbd> to copy and paste them with the tags set up the way you like.

**Comment by shiftee** [comment]
Perfect, I didn't know you could copy & paste the nodes.
This solves the need to setup each node (boring, repetitive and error prone).

For me adding a site_type field to "Archaeological Site" would be an improvement.
A "Historic Fortification" preset can probably wait until there is more user interest.

Regardless, my primary issue is resolved, shall I close?

**Comment by bhousel** [comment]
>For me adding a site_type field to "Archaeological Site" would be an improvement.
> Regardless, my primary issue is resolved, shall I close?

I'll close this after I improve the Archaeological Site preset

**Comment by JamesKingdom** [comment]
I added `site_type`, with a combo box.
![](https://i.glideservers.com/u/jam21fe67e5-167e-4137-a7d1-e6bad4f6c576.png)

**Comment by bhousel** [comment]
Thanks @JamesKingdom !
