### ISSUE TITLE
Please render crossings different from sidewalks

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#5126]
In my opinion, it would be helpful, if `footway=crossing` would be rendered white-black-white even if there's no `crossing=*` tag present.

![untitled](https://user-images.githubusercontent.com/14875493/42396469-16eaac48-8162-11e8-89c7-4b3ca9321759.png)

**Comment by bhousel** [comment]
The black and white rendering is specifically to make the zebra crossings stand out more.  (The crossing in your screenshot - you should tag that as a zebra crossing).

**Comment by SelfishSeahorse** [comment]
Hi!

If the `highway=crossing` nodes are already tagged `crossing=*`, then there's no need to duplicate the `crossing=*` type on the `footway=crossing` way.

(Also note that the proposal that introduced `footway=crossing` [^1] didn't suggest to add a crossing=* tag to it).

[^1]: <https://wiki.openstreetmap.org/wiki/Proposed_features/Sidewalk_as_separate_way#Crossings>

Regards

Markus

**Comment by SelfishSeahorse** [comment]
I'm not sure if my previous post was clear enough. What I meant is that there are two ways of adding the information about the pedestrian crossing type: either by adding the crossing type (`crossing=traffic_signals` in the example on the screenshot above [^1]) to the `highway=crossing` node and tagging the crossing way only `footway=crossing`, or by tagging the crossing node only `highway=crossing` and adding the crossing type to the crossing way.

When using the first tagging scheme, it would be helpful to see which footways are already tagged `footway=crossing`.

[^1]: <https://www.openstreetmap.org/node/725887627>

**Comment by bhousel** [comment]
> When using the first tagging scheme, it would be helpful to see which footways are already tagged footway=crossing.

oh, ok.. If all you are asking is that crossings render slightly differently from the adjacent sidewalks - this makes sense.  I'll see if we can do it.

**Comment by bhousel** [comment]
Ok, I've added the ability to style `footway=crossing` and gave it the same style that we use for other "special" paths (this also includes public transport platforms, piers, etc).

The marked/zebra crossing also changed slightly, but still has noticebly darker strokes in it:

<img width="319" alt="screenshot 2018-07-10 15 46 52" src="https://user-images.githubusercontent.com/38784/42533712-abb5f794-8458-11e8-90b7-2c2eedffbff1.png">

**Comment by SelfishSeahorse** [comment]
Great! Thank you very much!
