### ISSUE TITLE
Naming of unmaintained track roads

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5128]
Any chance they could just be called track roads? The addition of "unmaintained" is misleading because some of them can be paved. Plus they are technically maintained by the people that use them. I also seem to remember the wiki saying something about how calling them track roads is due to their purpose and not condition. Although I don't see it on there now.

**Comment by bhousel** [comment]
Sorry, but this issue is settled and I'm not willing to change the name.  We have really good reasons for why `highway=track` is called that, as a result of a lot of prior discussion.

see https://github.com/openstreetmap/iD/issues/4092#issuecomment-306639206
