### ISSUE TITLE
Limitation for snapping objects

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#5132]
Sometimes I see relatively new mappers are connecting large area (park, landuse, etc) to lines (road, power line, etc). I suppose they don't know how to use alter key not to snap. 
https://www.openstreetmap.org/edit?editor=id#map=19/35.79966/139.98817
Therefore I separate these objects when adding detailed objects such as sidewalks.
Is it possible not to snap different type of shape (point, line and area) automatically?

Like this:
Same shapes: will be snapped without alt key and won't be snapped with alt key. 
Different shapes: won't be snapped without alt key and will be snapped with alt key.

**Comment by bhousel** [comment]
This was #2302, closed as stale.
Also got yelled at on #4692 for the same thing, so I'm kind of not interested in pursuing it right now.
