### ISSUE TITLE
Date of satellite images

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5134]
On google earth you can see the date of each tile of the satellite images : images are indicated with ©'2018 CNES Airbus but also with another date, older, which is the true date of shooting.
With Bing, for example, they are indicated © 2018 DigitalGlobe © 2018 CNES Airbus but images are not the same and there is no information of the true date of shooting : it's, in my opinion, a big problem.

Example :
I hiked in Argentina along a big river with a lot of gravel : https://www.openstreetmap.org/user/Fred73000/traces/2745751
When I look at my trek on osm with bing, mapbox or esri, it looks like I was sometimes very far from the river (up to 80 m) or sometimes on the other side of the river but I never crossed it. When I look at my trek on google earth, I walked along the river at the perfect places : satellite images on google earth are dated 2016, for the 3 others I don't know but I think they are quite older and the river is no longer at the same places.

I know that it's impossible to have google satellite images on osm (because of copyright).

1) it will be great to know the date of tiles of mapbox, esri and bing : they are files so they have informations, maybe the shooting date is defined ? Or at least the date of the files ?
2) Both google satellite and Bing satellite images are © 2018 CNES Airbus but they are not the same : why ? If they have the same copyright, is it really impossible to have these images on osm, maybe directly from CNES AIrbus ?

Best regards

**Comment by bhousel** [comment]
See #4619 for more info on how to open up the Background imagery pane.
We don't have this information available for all Background sources, but we do have it for Bing and Esri.

(Also for general questions about how to use iD, please ask first on help.openstreetmap.org or one of the other forums - thanks!)

**Comment by Mahabarata** [comment]
Thanks :
But you answer the first point, not the second
And your answer tells me to ask my questions on another forum to know how to use ID but it is not the pb : the pb is the one of the last comment made on #4619

I imagine you know the joke of Bill Gates and Henri Ford. Bill Gates says : with my computer you can do everything, your cars do only one. And Ford answers : yes but when someone wants to start my cars, he doesnt need to push in the same time on the buttons of the blinker, the washer and the radio !

CTRL+SHIFT+B responds to my answer but I agree with the comments of #4619 ; it could be better.

And before to ask my question I have made a research to know if the question was asked before : sorry if I didn't find #4619, I was looking for an opened issue, lol !

Best regards
