### ISSUE TITLE
Russian typo (not critical, but annoying)

### ISSUE THREAD

**Issue by SoNickRND** [openstreetmap/iD#5140]
I just edited "shop: motorcycle" template and noticed that "key: operator" description field have a typo.

"Обслуживающая компания, организация или отдельное лицо, ответсвенное за работоспособность объекта"
Correct one will be":
"Обслуживающая компания, организация или отдельное лицо, ответственное за работоспособность объекта"
Diffirence is one symbol only, so it's clearly a typo.

**Comment by manfredbrandl** [comment]
Duplikate with #5143

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/openstreetmap/id-editor/dashboard/), so you should sign up for an account there to fix issues with the translations.
