### ISSUE TITLE
Russian typo

### ISSUE THREAD

**Issue by SoNickRND** [openstreetmap/iD#5143]
I just edited "shop: motorcycle" template and noticed that "key: operator" description field have a typo.

"Обслуживающая компания, организация или отдельное лицо, ответсвенное за работоспособность объекта"
Correct one will be":
"Обслуживающая компания, организация или отдельное лицо, ответственное за работоспособность объекта"
Diffirence is one symbol only, so it's clearly a typo.

**Comment by manfredbrandl** [comment]
Are you aware about: https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating ?

**Comment by SoNickRND** [comment]
Github, it posted three times, every time said like "Error: we didn't post anythin'.

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/openstreetmap/id-editor/dashboard/), so you should sign up for an account there to fix issues with the translations.

**Comment by SoNickRND** [comment]
I found an "operator" but  I can't find where to fix that field. That Transifex is bit confusin'. T_T
