### ISSUE TITLE
manually clear cache

### ISSUE THREAD

**Issue by karissa** [openstreetmap/iD#5146]
Hey,

We have built an alternative back-end for iD that runs on the local machine, and have integrated iD into a desktop app. (https://github.com/digidem/id-mapeo, https://github.com/digidem/mapeo-desktop) I'm running into an issue where if the database is updated from the sever side (i.e., not using the 'save' button' or interface), the new data points aren't updated. I'm curious if there's a way in the API to manually refresh the data in the UI in this case. Right now, the only way I figured out how to do it is to refresh the window, which isn't great for user experience as the screen flashes white..

Thanks!

**Comment by bhousel** [comment]
Cool!  I'm a big fan of Mapeo ❤️ (I saw Emily Jacobi's talk year at last year's SOTM-US)

Calling `context.reset()` should clear all the cached data in iD:
https://github.com/openstreetmap/iD/blob/0d8792d4dec4de2aae3f6984a92d68e5330badb6/modules/core/context.js#L416-L427

(it is also aliased to `context.flush()` for backward compatibility)

We are starting to accumulate a lot of services for things like not just OSM itself, but Mapillary, OpenStreetCam, Bing Streetside, etc.   Each service can expose a `reset` function so they should all get their cached data cleared out too.

`context.flush()` is called after the user has saved successfully, or when switching between live and dev servers.  

hope that helps!
