### ISSUE TITLE
Gate preset not easily findable

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5147]
In the "select feature type" pane, "gate" doesn't produce useful results as a search term.  Instead, one has to know to search for "barrier."

It would be nice if this were more consistent with other types of barriers (admittedly, the apply to ways, not nodes).  I can search for fence, hedge or tree row and get what I want.  Gates, however, are harder to find.  Even though I now know I can't search for "gate" I almost always forget and try it anyway before the result forces me to remember that I have to search for "barrier."

**Comment by tohaklim** [comment]
The only way I can reproduce `gate` not being searchable is if I try it on a normal node.
Could you elaborate on how this comes about?

**Comment by bhousel** [comment]
Hey @eehpcm , I just checked this.. What @tohaklim said is true - the gate preset only works on connected nodes, not standalone nodes.
