### ISSUE TITLE
Support links in notes

### ISSUE THREAD

**Issue by theel0ja** [openstreetmap/iD#5151]
Tried on `4c9ef45`, hyperlinks aren't clickable.

**Comment by bhousel** [comment]
> Tried on 4c9ef45, hyperlinks aren't clickable.

This is true.. We'd have to consider how safe this is.
For now we're just displaying the notes as text only.

**Comment by thomas-hervey** [comment]
@theel0ja @bhousel and I discussed this as a possibility. Others have also requested this feature. Since it is present in osm.org, it's likely that we will introduce this feature.

**Comment by bhousel** [comment]
Yep, I added this by showing the html content that we receive the Notes API.  

We think that this should be safe, since the links are added on the OSM side by https://github.com/vmg/rinku , not by users themselves.
