### ISSUE TITLE
Filter notes by closed date / closed status

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#5153]
Showing all notes (inclusing closed notes) can be annoying, e.g.
![31f8eb64-337d-4abc-84f0-9e2673425b41](https://user-images.githubusercontent.com/5360273/42835876-d502baee-89f1-11e8-9d29-fe328dc8703a.jpeg)

**Comment by bhousel** [comment]
Yeah, I was thinking we could maybe add the ability to filter the notes (e.g. to not show the closed ones). 
I do think it is useful to show them sometimes, for example if they were accidentally closed and need to be reopened.

We're getting a lot of requests for more filtering of various data layers (including osm, notes, streetside photos) and I think this is a good thing to think about for this pane.

**Comment by bhousel** [comment]
whoa in your screen shot it shows "closed null" and "opened null".   Do you see this everywhere or just the null island notes?

**Comment by bhousel** [comment]
It should show actual localized dates:

<img width="300" alt="screenshot 2018-07-17 13 58 13" src="https://user-images.githubusercontent.com/38784/42836604-7f088a2e-89c9-11e8-8208-c85b6de4672a.png">

**Comment by manfredbrandl** [comment]
I see „null“ also on other notes
![1c9e8552-fd24-4017-b976-4d5fdf836847](https://user-images.githubusercontent.com/5360273/42836951-718e2982-89f4-11e8-8819-cc830c75d55b.jpeg)

**Comment by manfredbrandl** [comment]
> Yeah, I was thinking we could maybe add the ability to filter the notes (e.g. to not show the closed ones).
> I do think it is useful to show them sometimes, for example if they were accidentally closed and need to be reopened.

A filter would be great.

**Comment by mmd-osm** [comment]
> I see „null“ also on other notes

Same here, I've seen this before and thought that's maybe some artifact as iD isn't running on osm.org yet.

**Comment by thomas-hervey** [comment]
@manfredbrandl , I am currently working woth @bhousel and @kamicut on surveying how notes are used. Several people have suggested filtering by status, so I'll keep it in mind when adding improvements to notes (e.g., templates, filters, etc.).

**Comment by mmd-osm** [comment]
@thomas-hervey : you should probably also reach out to Pascal (@pa5cal) who provides lots of OSM stats to the community, including notes: http://resultmaps.neis-one.org/osm-notes - he should be able to pull just about any stat you could think of out of his db ;)

**Comment by thomas-hervey** [comment]
Thanks @pa5cal , I sent you an email via your website. When your website is back up, perhaps we can chat within the next week about how many notes are commented on and potential note filtering & templating.

**Comment by thomas-hervey** [comment]
Work is in progress (see [comment](https://github.com/openstreetmap/iD/issues/5172#issuecomment-449513599) and the [notes-filtering](https://github.com/openstreetmap/iD/tree/notes-filtering) branch).

**Comment by manfredbrandl** [comment]
just checked preview.ideditor.com/master and filtering works now.
