### ISSUE TITLE
Notes showing with date = "null"

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5154]
This is from https://github.com/openstreetmap/iD/issues/5153

@manfredbrandl is using German locale.

![1c9e8552-fd24-4017-b976-4d5fdf836847](https://user-images.githubusercontent.com/5360273/42836951-718e2982-89f4-11e8-8819-cc830c75d55b.jpeg)

**Comment by thomas-hervey** [comment]
This seems to be browser specific, perhaps in addition to language specific. I am getting "null" in Firefox and Safari. I'm going look into [localDateString](https://github.com/openstreetmap/iD/blob/4c9ef45448fde770aeca55f735f48ed09969aa0c/modules/ui/note_comments.js#L98-L104) to see if that's the issue.

**Comment by thomas-hervey** [comment]
a quick fix seems to be normalizing [inputs](https://github.com/openstreetmap/iD/blob/4c9ef45448fde770aeca55f735f48ed09969aa0c/modules/ui/note_comments.js#L102) for Date(), such as `s = s.replace(/-/g, '/'); // fix browser-specific`. Testing in German now...
