### ISSUE TITLE
Colour blindness - closed note looks same as open note with comment

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5156]
A closed note (green) has three dots - the same as a open note (red) with a comment. This will cause problems for those who are red/green colour blind. 

Can I suggest a tick is used on the closed note (like the OSM website), rather than just using colour to differentiate between the two?

The yellow for a selected note may also be a problem - there should be something else other than colour to show which note has been selected.

**Comment by bhousel** [comment]
> A closed note (green) has three dots - the same as a open note (red) with a comment. This will cause problems for those who are red/green colour blind.
> 
> Can I suggest a tick is used on the closed note (like the OSM website), rather than just using colour to differentiate between the two?

Good suggestions!   When I stuck the thread dots on the notes, it was kind of an experiment, but I agree that we can use that annotation to differentiate between kinds of notes, which should make them easier for colorblind users.  I'll mimic what the OSM website does with the check.

> The yellow for a selected note may also be a problem - there should be something else other than colour to show which note has been selected.

Yes, I am going to see if we can have them select and pulse like the other OSM objects.

**Comment by thomas-hervey** [comment]
a PR for new notes (https://github.com/openstreetmap/iD/pull/5162) handles the breathe pulsing on hover and select and mimics the OSM website icons.

**Comment by boothym** [comment]
@thomas-hervey thanks, please let me know when this is available in the preview so I can have a look 👍

**Comment by bhousel** [comment]
Working on merging this today @boothym 👍

**Comment by bhousel** [comment]
This was done in #5162 - please test in http://preview.ideditor.com/master/ thanks!

**Comment by boothym** [comment]
Looks much better thanks, good stuff 👍
