### ISSUE TITLE
Notes: View info about Notes in "Measurement" and "History"

### ISSUE THREAD

**Issue by magol** [openstreetmap/iD#5158]
When I select a Note, I expect that the information in the windows "Measurement" and "History" are updated.

The information can be something like this:

**Measurement**
> #note-id
> 
> Type: note
> Placing: xx°xx'xx''N, xx°xx'xx''E
>   xx.xxxxxxx, xx.xxxxxxx

**History**
> #note-id
>
> Created: 18 jul. 2018 21:00:00
> Created by: xxxxx
> Last commented: 18 jul. 2018 22:00:00
> 
> Note on openstreetmap.org

**Comment by jguthrie100** [comment]
I don't understand how this relates to iD? Are notes selectable in iD?

**Comment by bhousel** [comment]
> I don't understand how this relates to iD? Are notes selectable in iD?

Yes the osm note feature is available for preview in http://preview.ideditor.com/master/ and will be released pretty soon.

**Comment by magol** [comment]
@jguthrie100 
The ability to see note are added in PR  #5107

**Comment by bhousel** [comment]
This was done in 
68ed6b102 2018-08-10 Show selected note details History Panel (re: #5158)
9f33ca9a0 2018-08-09 Show location of selected Note in Measurement Panel (re: #5158)

and a few other follow on commits to make sure that the panels updated when users interact with the notes.
