### ISSUE TITLE
Enter button destroys entry

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5160]
User is entering Reference Code

![df1](https://user-images.githubusercontent.com/1230959/42917879-02d3344c-8b3e-11e8-9aa4-6d08f49986d1.jpg)

User hits the Enter button on his keyboard. As you know, data entry professionals all hit the Enter button upon finishing each data entry.

Next thing you know, all is lost. We see "Search"
![df3](https://user-images.githubusercontent.com/1230959/42917933-3b0736ba-8b3e-11e8-951d-71d5b5e8aae3.jpg)

**Comment by bhousel** [comment]
> User hits the Enter button on his keyboard. As you know, data entry professionals all hit the Enter button upon finishing each data entry.

I don't think the data is lost.. It's saved and the user is returned to browse mode. 
Can you confirm?

**Comment by jidanni** [comment]
Yes, if the user decided to select that feature from the map again, he will find painstakingly typed in data still there. But 99% of the other users will not know why we are now looking at something irrelevant and give up.

**Comment by bhousel** [comment]
We train users in the walkthrough that it's ok to press enter and that their edits are not lost.  iD has worked this way since the beginning, and I'm not changing it now.
