### ISSUE TITLE
Add the posibility to "pin" a preset to the preset list

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#5163]
Sometimes I wish for the feature to pin a preset that I use frequently to the preset list. This would mean that it always stays in the preset list until it is "unpinned" or the tab is closed. What is your opinion on that?

**Comment by manfredbrandl** [comment]
Last time I used iD previously used Features becomme kind of pinned automatically. Did that change recently?

**Comment by bhousel** [comment]
The ability to customize the preset list is #590
