### ISSUE TITLE
No background selected

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5165]
If you are viewing or editing in iD using a country specific background, and then close the tab and edit the map in another area - the background list shows nothing selected and the background is black

If possible, iD should default to Bing when this happens.

**Comment by bhousel** [comment]
Good suggestion, but unfortunately it's not really possible.  iD doesn't have a way to know whether the imagery that loads is actually usable.  For example, I just tried this with `#background=geodata.state.nj.us-Natural2015` in a spot of Earth far from New Jersey.   The image server returns white tiles but with the HTTP status 200 OK.

The other issue is more that I think doing this would be misleading.  We wouldn't want a user to think they are getting something and show the Bing instead.  I'd rather have broken things look broken.  

(I'm assuming that people are smart enough to figure out that if there is no imagery, and that they have previously played with the background imagery, they can go back into that pane and see what's going on.)
