### ISSUE TITLE
Notes: Not just notes, also fixme- and todo-keys

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5173]
I feel like the notes layer should not just show the notes objects, but also "fixme" and "todo" keys of elements on the map.

IMO those objects (notes and fixmes) have the same goal: Mark something that needs checking.

So for this UI, they should/could be treated the same.

Example: 
This fixme/todo https://www.openstreetmap.org/way/610367250#map=19/52.43189/13.41205 (https://www.openstreetmap.org/way/610367250#map=19/52.43189/13.41205) could just as well be a note. I added it as a tag to make the relation more clear. But the workflow attached to it is the same as with a note: Someone needs to check it locally and then resolve it.

**Comment by bhousel** [comment]
That's a good suggestion, but the way the code is written we can't combine notes and real OSM objects.  But we're considering adding other note-like validation/QA layers (#3452) that could do this.
