### ISSUE TITLE
Split roads in one click

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5174]
**My goal:** Split a raod.

**GIF of what I see when I try it:**

![id-editor-split-road mov](https://user-images.githubusercontent.com/111561/43120957-572c3a0c-8f1c-11e8-9f07-5ffd0edc3f88.gif)

**Expectation / Solution:**

Ideally there where a button on the node of a road that allows to split it and afterwards I can move the two road-parts separately. After splitting the one of the two road-nodes should be selected and moving with my cursor so I can re-place it.

**Issues:**

- a. There seems to be a difference between split ("Teilen") and disconnect ("Trennen"); that kind of makes sense; but not in this szenario?
- b. Therefore after I split the road I need to re-click the new node(s). But for some reason that does not work on the first try. I see the road/way context menu(?); but not the node menu.
- c. On my third try I see the disconnect ("Trennen") button; after I click it I need to re-click on the node to move it

**Ideas:**

- Add the disconnect/Trennen button to the road/way-node as well (below the split/Teilen) button, the disconnect button then should split+disconnect in one go
- After disconnecting, attach one node to the cursor so I can move it directly; I can alway cancel this with the esc-key.

**Comment by manfredbrandl** [comment]
There are eight actions to split and disconnect a road and move the nodes apart:
![split-and-disconnect-line](https://user-images.githubusercontent.com/5360273/43125820-6344ff18-8f2b-11e8-8a01-fcfe131897c2.gif)
What do you think about a combined actions split and disconnect where the node stays selected afterwards?

**Comment by bhousel** [comment]
also kind of like #3769 but not exactly the same

**Comment by quincylvania** [comment]
Hmm I'm not convinced disconnecting the ways after splitting is always desirable. The mapper might want to split a line to change the attributes on part of it, like tagging a different road surface or speed limit. They might split a road at an intersection to add a turn in a route relation. I can imagine mappers splitting ways and not realizing iD has disconnected them, which could break routing.

Still, I agree it would be great to be able to immediately disconnect after splitting if desired. We can have iD select the node after splitting so the mapper can do this with hotkeys.

> Add the disconnect/Trennen button to the road/way-node as well (below the split/Teilen) button

Do you mean splitting a way by right-clicking it at an arbitrary location without adding a midpoint first?

> Therefore after I split the road I need to re-click the new node(s). But for some reason that does not work on the first try. I see the road/way context menu(?); but not the node menu.

This sounds like a bug… can you still reproduce it?

> After disconnecting, attach one node to the cursor so I can move it directly; I can alway cancel this with the esc-key.

A similar feature was proposed in #6904. I posted there why I don't think it works well with touchscreens.

**Comment by quincylvania** [comment]
> We can have iD select the node after splitting so the mapper can do this with hotkeys.

I ended up doing this. I really don't think we can have iD disconnect stuff automatically after splitting, but now you can achieve it with one extra keypress instead of shuffling the selection manually.
