### ISSUE TITLE
Unable to create new note when using dev server

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#5175]
_Opening as per chat with @bhousel_ 

Trying to add a new note on the dev server fails, as it continues to ask for authentication and doesn't ever create the note.
![](https://vigi.cc/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWjg9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--71f45f084e2f93f5207168ec12167b9724e6d091/2018-07-24_23-06-12.gif)

**Comment by bhousel** [comment]
Thanks @JamesKingdom - the issues you're seeing might be related to the OSM server move happening now. I'd like to wait a few days to see if things resolve themselves.

**Comment by mmd-osm** [comment]
@JamesKingdom : could you maybe post the full URL you're using to reproduce this issue? AFAIK the dev server didn't move, so I'm wondering if this might be something else.

**Comment by JamesKingdom** [comment]
@mmd-osm Just go anywhere while using the dev server and try to create a note.

**Comment by mmd-osm** [comment]
@JamesKingdom : not sure i'm following you. dev.openstreetmap.org doesn't have the "notes" branch deployed, which would be needed to have the "notes" button like on your screenshot, and http://preview.ideditor.com/notes doesn't work either. Hmm..

**Comment by mmd-osm** [comment]
Ok, I think the issue is that the OAuth application on the dev instance hasn't been created with "modify notes." permission. The following screenshot lists all possible permissions for new OAuth apps on the left hand side, and on the right hand side the ones I'm confirming as an iD user. Clearly, "modify notes." is missing here.

![image](https://user-images.githubusercontent.com/5842757/43227304-a0c733ea-905e-11e8-8971-5ff52cfdedb1.png)

As a result, there's an error when creating notes, as the user won't have the permission to do so on the dev instance.

**Comment by bhousel** [comment]
Just flagging that this seems to be an issue on the main OSM server also, related to how openstreetmap-rails preauthenticates iD in the iframe.. cc @tomhughes

**Comment by mmd-osm** [comment]
Concerning the dev instance, I guess someone at Mapbox originally registered iD as back in 2012 at a time when "modify notes" wasn't available yet. That's probably not too bad, as that permission could still be added now by simply logging on the dev instance and adding the checking the "modify notes" box. Now sure how this would affect existing users. For new users, that should help.

Maybe, it would be useful to query a user's permission, and disable some features, if the respective permission hasn't been granted (such as "allow_write_notes"):

GET /api/0.6/permissions (as logged on user!)

```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="OpenStreetMap Server">
  <permissions>
    <permission name="allow_read_prefs"/>
    <permission name="allow_write_prefs"/>
    <permission name="allow_write_diary"/>
    <permission name="allow_write_api"/>
    <permission name="allow_read_gpx"/>
    <permission name="allow_write_gpx"/>
    <permission name="allow_write_notes"/>
  </permissions>
</osm>
```

**Comment by bhousel** [comment]
Yep @mmd-osm - I forgot to followup to my comment above that @tomhughes already fixed this on the live osm.  He can probably do the same for dev too when he has some time, but there's no rush.

**Comment by thomas-hervey** [comment]
also, @JamesKingdom when you place notes, do they appear in a different place than where you click? If so, this is another issue to address.

**Comment by tomhughes** [comment]
I think this should be fixed on the dev server master instance now.

**Comment by mmd-osm** [comment]
Just tried it via http://preview.ideditor.com/master  -> switch to dev.

When logging on to the dev instance, I'm getting the following popup without "allow_write_notes" on it:

![bildschirmfoto von 2018-07-28 10-40-50](https://user-images.githubusercontent.com/5842757/43354811-01027b2a-9253-11e8-9807-7f218363b72a.png)

**Comment by tomhughes** [comment]
I'm talking about the editor built in to https://master.dev.openstreetmap.org/ which is called "iD" with a capital so whatever that URL is doing it is not using the same client application.

**Comment by mmd-osm** [comment]
Indeed, the master instance on dev works with the built in editor.  preview.ideditor.com uses the following oauth keys/secrets for the dev instance, but I don't know under which user they have been created:

```javascript

'urlroot': 'https://api06.dev.openstreetmap.org',
'oauth_consumer_key': 'zwQZFivccHkLs3a8Rq5CoS412fE5aPCXDw9DZj7R',
'oauth_secret': 'aMnOOCwExO2XYtRVWJ1bI9QOdqh1cay2UgpbhA6p'
```

**Comment by tomhughes** [comment]
I've fixed that application record and associated tokens now.

**Comment by mmd-osm** [comment]
@tomhughes : many thanks, this works now as expected!

@JamesKingdom : I think we can close this one now, right?

**Comment by JamesKingdom** [comment]
This problem is fixed, thanks @tomhughes! :+1:
