### ISSUE TITLE
Uploaded GPS traces do not show in iD editor

### ISSUE THREAD

**Issue by seahorse41** [openstreetmap/iD#5177]
After logging in, from My GPS Traces, when I click on edit to the right of (any of the) traces, the magenta line does not show in the iD editor. This is not restricted to recently uploaded tracks, I tried several on my list, even a short track from 7 months ago does not show.

My system is: Debian 9 and Seamonkey-2.49 and iD 2.9.2
I also tried with Firefox ESR 52.5 and it took over 2 minutes to load iD (that could be a separate issue!) but also had no GPS track shown.

**Comment by bhousel** [comment]
which bug is that @seahorse41 ?

**Comment by seahorse41** [comment]
#3820
[](https://github.com/openstreetmap/iD/issues/3820)

**Comment by bhousel** [comment]
Thanks @seahorse41 - the issues you're seeing might be related to the OSM server move happening now.  I'd like to wait a few days to see if things resolve themselves.

**Comment by seahorse41** [comment]
It would be nice if there were a message at the login page, stating if the servers are down for maintenance. Especially if it is days and not hours. Thanks.

**Comment by bhousel** [comment]
I agree @seahorse41 - when the editing API is down, iD is able to display a message across the bottom of the screen.  (I've seen this message occasionally in the past few days).  

But when other services are down, like the GPS traces, iD wouldn't be able to tell the difference between the server being down, or the user entering the wrong thing into the `gpx=` url parameter.  All it knows is it tried to get a requested file and couldn't do that.  I do want to improve how errors appear in iD.

For now a good place to look is to open the developer console of your browser and see what is displayed there.

**Comment by mmd-osm** [comment]
@seahorse41 : I think the server error has been resolved in the meantime, so you won't see any error messages on the javascript console. About two hours ago, I could successfully load a gpx trace into iD.

**Comment by seahorse41** [comment]
Yes! This issue is fixed, and my unsaved changes were recovered and able to be saved. Now I'm happy.

**Comment by bhousel** [comment]
> Yes! This issue is fixed, and my unsaved changes were recovered and able to be saved. Now I'm happy.

Yay!  if you're happy, I'm happy..
