### ISSUE TITLE
Can't save any change 

### ISSUE THREAD

**Issue by laraMoovit** [openstreetmap/iD#5178]
this is the error I get:

<!doctype html> <html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1"> <title>We're sorry, but something went wrong: Web application could not be started</title> <style type="text/css">body{font-family:Arial,Sans-Serif;font-size:13px;color:#222;margin:0}.column{max-width:1000px;margin-left:auto;margin-right:auto;text-align:center}header{border-bottom:1px solid #e3e3e3;margin-bottom:45px}footer,header{margin-top:50px}footer{font-size:14px;color:#7f7f7f;border-top:1px solid #e3e3e3;padding:40px 0}h1{font-size:30px;margin-top:30px;margin-bottom:10px}.subtitle{margin-top:0;margin-bottom:110px;font-size:20px}#operator_info{display:none}#show_operator_info{font-size:17px;font-weight:400}.left{text-align:left;padding:8px}h3{margin-top:30px;margin-bottom:10px;font-size:23px}ul{padding-left:16px}a,li{color:#1781bf;text-decoration:none}.error,a,li{font-weight:700}.error{background:#e6f3fc;border-radius:5px;padding:7px 12px}.error.block{display:block}.bold{font-weight:700!important}pre{margin:0;overflow-x:auto;white-space:pre-wrap;word-break:break-all}dt{margin-top:16px;font-weight:700}dd{margin-left:0}.plain{color:inherit;font-weight:inherit}#content{overflow-y:scroll;height:800px}</style> </head> <body> <header> <div class="column"> <svg width="50" height="50" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"><path d="m731.234002 153.838666v-18.841339c0-4.417534-3.577416-7.997327-7.990382-7.997327h-6.414571c-4.417012 0-7.990383 3.580525-7.990383 7.997327v18.841339h-18.841339c-4.417534 0-7.997327 3.577416-7.997327 7.990383v6.414571c0 4.417011 3.580525 7.990382 7.997327 7.990382h18.841339v18.841339c0 4.417534 3.577416 7.997328 7.990383 7.997328h6.414571c4.417011 0 7.990382-3.580526 7.990382-7.997328v-18.841339h18.841339c4.417534 0 7.997328-3.577416 7.997328-7.990382v-6.414571c0-4.417012-3.580526-7.990383-7.997328-7.990383z" fill="#f87575" transform="matrix(.70710678 -.70710678 .70710678 .70710678 -593.80455139 424.48059756)"/></svg> <h1>We're sorry, but something went wrong.</h1> <p class="subtitle">The issue has been logged for investigation. Please try again later.</p> </div> </header> <div class="column"> <a id="show_operator_info" href="#" onclick="showOperatorInfo()">Technical details for the administrator of this website</a> <div id="operator_info"> <div class="left"> <h3>Error ID:</h3> <span class="error">2dea14d6</span> <h3>Details:</h3> <p>Web application could not be started by the Phusion Passenger application server.</p> <p class="bold">Please read <a href="https://www.phusionpassenger.com/library/admin/log_file/" class="plain">the Passenger log file</a> (search for the Error ID) to find the details of the error.</p> <p>You can also get a detailed report to appear directly on this page, but for security reasons it is only provided if Phusion Passenger is run with <i>environment</i> set to <i>development</i> and/or with the <i>friendly error pages</i> option set to <i>on</i>.</p> <p>For more information about configuring environment and friendly error pages, see:</p> <ul> <li><a href="https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_friendly_error_pages">Nginx integration mode</a></li> <li><a href="https://www.phusionpassenger.com/library/config/apache/reference/#passengerfriendlyerrorpages">Apache integration mode</a></li> <li><a href="https://www.phusionpassenger.com/library/config/standalone/reference/#--friendly-error-pages---no-friendly-error-pages-friendly_error_pages">Standalone mode</a></li> </ul> </div> </div> </div> <footer>  <div class="column"> This website is powered by <a href="https:<wbr>//www.phusionpassenger.com"><b>Phusion Passenger</b></a>&reg;, the smart application server built by <b>Phusion</b>&reg;. </div> </footer> <script> function showOperatorInfo() { document.getElementById('operator_info').style.display = 'block'; } </script> </body> </html>

**Comment by bhousel** [comment]
Yep, this is #5176 - it's a failure by the OSM servers, not iD.
If you wait until later the servers are available again and retry your save, it should work.

**Comment by laraMoovit** [comment]
thank you! :)
