### ISSUE TITLE
en-AU Localization

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#5183]
Apologies if this has been raised before, I couldn't find an existing issue.

We have translations for different languages, but what about localization to different regions? Is this supported?

eg. "Gas Station" isn't used in Australia, they are known as a Service Station or Petrol Station.
![selection_999 007](https://user-images.githubusercontent.com/117278/43261692-fcc009fc-9120-11e8-89fb-a21c62abc3e7.png)

We have "terms" but that doesn't change the display name.

- Same for Sidewalk which is known as a Footpath
- Drugstore
- Guest Apartment / Condo -> Serviced Apartment
- RV Park -> Caravan Park

**Comment by andrewharvey** [comment]
So sounds like Localization is already happening for the regions which are setup with translations in Transifex, so the issue here is we are lacking an `en-AU` on Transifex.

I feel this is important to make the editor more welcoming for all audiences.

**Comment by bhousel** [comment]
> So sounds like Localization is already happening for the regions which are setup with translations in Transifex, so the issue here is we are lacking an en-AU on Transifex.
> 
> I feel this is important to make the editor more welcoming for all audiences.

Yes, I'm happy to set this up.. @andrewharvey can you sign up for an account on Transifex and join our project page here:
https://www.transifex.com/openstreetmap/id-editor/dashboard/

Then click "Languages" and you should be able to put in a request for `en-AU`, which I'll approve.

**Comment by andrewharvey** [comment]
Did that , except en_AU isn't an option to suggest in Transifex.

**Comment by bhousel** [comment]
ok @andrewharvey - I just added `en-AU` (I had to click "more" to see it on the transifex list) and invited you as a coordinator

**Comment by pnorman** [comment]
Is it possible to make en_AU fall back to en_GB, then to en_US? That might help, because then the AU translation only needs to contain differences from GB English

**Comment by bhousel** [comment]
Sure @pnorman.. actually maybe we should do this for anything starting with `en` that’s not `en-US`?
