### ISSUE TITLE
Editor: Height Tag Forced to Integer Value

### ISSUE THREAD

**Issue by bryantcurto** [openstreetmap/iD#5184]
When specifying the height for a building as a decimal (eg. 4.7), the input field converted my input to an integer. Looking at the [wiki for Key:height](https://wiki.openstreetmap.org/wiki/Key:height), decimal values should be permitted.

**Comment by lakedistrictOSM** [comment]
I also had this problem yesterday. Has it always converted the input to an integer or is it a recent change/bug? Can't say I've noticed it before.

**Comment by bhousel** [comment]
Thanks for reporting @bryantcurto and @lakedistrictOSM - I looked into this earlier today and this regressed at the time we added the min/max numeric values to certain fields (#5043).
