### ISSUE TITLE
HTML error page not working

### ISSUE THREAD

**Issue by rebio** [openstreetmap/iD#5188]
For some reason the osm API is a bit wonky today and I got an error message about it.
For some reason the error widow just showed me the HTML code and did not _render_ it.
![bug](https://user-images.githubusercontent.com/10911084/43357544-9660b1ca-9283-11e8-993c-cb47ef0e0972.png)

**Comment by homersimpsons** [comment]
#3366

**Comment by bhousel** [comment]
yeah closing as a duplicate of #3366
