### ISSUE TITLE
HTML code displayed instead of track name

### ISSUE THREAD

**Issue by tkansgar** [openstreetmap/iD#5197]
Hi,

when editing the map while one of my tracks is displayed by a pink path line, now (since one week or so) there is some HTML code displayed instead of the name of my track (see attached screenshot). Should be fixed.

Best regards
tkansgar
![screenshot_editor_id](https://user-images.githubusercontent.com/25564954/43539739-04796270-95c6-11e8-98eb-b2ed6e9bd14e.png)

**Comment by bhousel** [comment]
Whoa interesting - can you share the gpx file in a GitHub gist, or a sharing site like Dropbox?

**Comment by tkansgar** [comment]
Hi Bryan,

I just sent it to notifications@github.com. Hope that's ok. It was recorded yesterday with the last version of Locus Map on my smartphone. I just testet some older ones recorded with older Locus Map versions. These are displayed correctly as before. So may be it's an issue with Locus Map but not your editor. Only my tracks recorded after 07/21/2018 are displayed in that strange manner. Should I post this issue in the Locus Map forum?

Best regards
tkansgar

**Comment by bhousel** [comment]
> I just sent it to notifications@github.com. Hope that's ok.

Unfortunately that won't work to get the file to me - It probably really needs to be shared some other way.

> Only my tracks recorded after 07/21/2018 are displayed in that strange manner. Should I post this issue in the Locus Map forum?

I'm don't know for sure but it's probably worth reaching out to the developers of Locus Map to see if anything has changed on their end..

**Comment by tkansgar** [comment]
Hi Bryan,

I have made it public on openstreetmap.org:

[https://www.openstreetmap.org/user/tkansgar/traces/2766753](https://www.openstreetmap.org/user/tkansgar/traces/2766753)

Does that work for you?

Best regards
tkansgar

**Comment by tkansgar** [comment]
Hi again,

I discovered some differences in the tracks recorded since 07/25/2018: After the `<name>...</name>` token now there follows a token beginning with`<desc><![CDATA[<!-- desc_gen:start -->`. And you see, here starts the string ID displays now as track name, where formerly just was displayed the string from the `<name>...</name>` token. Can this be fixed? Who has to do it, you or the Locus Map developer?

Best regards
tkansgar

**Comment by bhousel** [comment]
> I discovered some differences in the tracks recorded since 07/25/2018: After the <name>...</name> token now there follows a token beginning with<desc><![CDATA[. And you see, here starts the string ID displays now as track name, where formerly just was displayed the string from the <name>...</name> token. Can this be fixed? Who has to do it, you or the Locus Map developer?

It looks like the `<!CDATA` stuff is a mistake and needs to be fixed by the Locus Map developer.
(It's a way of saying "everything in here should be taken as-is, not as xml")

**Comment by tkansgar** [comment]
> It looks like the <!CDATA stuff is a mistake and needs to be fixed by the Locus Map developer.
(It's a way of saying "everything in here should be taken as-is, not as xml")
I just created a ticket there:
[http://help.locusmap.eu/ticket/14439](http://help.locusmap.eu/ticket/14439)

**Comment by menion** [comment]
Good day bhousel, tkansgar,
issue found in new Locus Map 3.32+ version. Will be fixed in next update. Thanks

**Comment by bhousel** [comment]
Thanks @menion for the update!

**Comment by tkansgar** [comment]
Hi Bryan again,

I now still have one question: Why takes the ID editor the section beginning with `<desc><![CDATA[<!-- desc_gen:start -->` as track name instead of the real track name, if both are present? Is it, because you prefer a "track description" over a track name? And if so, should the description not contain such html code?

Best regards
tkansgar

**Comment by bhousel** [comment]
> Is it, because you prefer a "track description" over a track name? And if so, should the description not contain such html code?

Yes, this is the code that prefers description over name.. We do this because the name is usually something like `12345.gpx`.  The description can contain anything, but storing a big block of CDATA there is definitely weird.

https://github.com/openstreetmap/iD/blob/ff9e60d205b420e7a2032da1eb5c5dbd0ee0df2b/modules/svg/gpx.js#L112-L114
