### ISSUE TITLE
extend railway=crossing and level_crossing presets

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#5203]
What do you think of extending the railway=crossing ands level_crossing presets, wouldn't it be useful to add at least the often used tags _crossing:barrier, crossing:light and crossing:bell_?

Maybe also:
crossing:saltire, crossing:supervision and for railway=crossing (pedestrian railway crossings) tactile_paving?

Here you see how often the tags are sued: https://taginfo.openstreetmap.org/search?q=crossing

**Comment by bhousel** [comment]
Unfortunately same thing I wrote in https://github.com/openstreetmap/iD/issues/5205#issuecomment-410784580 applies here too (but for the `crossing:` namespace instead of the `traffic_signals:` namespace)
