### ISSUE TITLE
add layer=* field to some more presets where it's appropiate

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#5204]
Hello,
beside bridges and tunnels, the layer-tag is also often used for some more things which are often covering something or laying (high) above or under some other objects.

So what do you think of adding the layer-tag-field to the **building=roof preset** (roofs are mostly covering something which is under them)
and to **power=line**, **power=minor_line** and **man_made=pipeline** presets?

**Comment by bhousel** [comment]
Thanks @Lukas458, I made the change

**Comment by alesarrett** [comment]
layer=1 on building=roof should be suggested only when some other features exist overlapping the roof. Could the warning be activated only where there is overlapping between the roof and some other features? Layer=1 should be used only in those cases: https://wiki.openstreetmap.org/wiki/Key:layer?uselang=en

**Comment by k-yle** [comment]
@alesarrett this issue is about something slightly different, you may want to post that comment on https://github.com/openstreetmap/id-tagging-schema/pull/227 instead
