### ISSUE TITLE
Unclosed ways validation: add an exception for tourism=artwork

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#5206]
The [unclosed ways validation](https://github.com/openstreetmap/iD/blob/015c8918f6ef1a6e2d8467a09d8b3b7359856729/modules/validations/tag_suggests_area.js) fire a warning when trying to save an unclosed way tagged with [tourism=artwork](https://wiki.openstreetmap.org/wiki/Tag%3Atourism%3Dartwork).
Some [types of artwork](https://wiki.openstreetmap.org/wiki/Key:artwork_type) are two dimensional, so the way shouldn't be closed.

**Comment by bhousel** [comment]
Thanks @tbertels - I've made the change.
