### ISSUE TITLE
Source tag ans

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5209]
One of the backgrounds available to me is OS OpenData StreetView (I don't know if this is available globally or only when mapping the UK or only when the mapper is in the UK, but it's there and it's useful).

According to [the wiki](https://wiki.openstreetmap.org/wiki/Ordnance_Survey_Opendata), if I trace over something using that background I should include source=OS_OpenData_StreetView and if I use that background merely to get a name for an object then I should include source:name=OS_OpenData_StreetView.  Sometimes it is appropriate to put that source on the object itself, sometimes it can be done in the change comments.  Either way, it's a lot of typing and rapidly becomes tedious.

Would it be possible that when I add a source tag or source:name tag then the dropdown for the values includes in its list whatever backgrounds are available (sometimes for streams I use a mix of background imagery and OS OpenData StreetView)?  It would make life a lot easier if I didn't have to keep typing it all in.

**Comment by bhousel** [comment]
> According to the wiki, if I trace over something using that background I should include source=OS_OpenData_StreetView and if I use that background merely to get a name for an object then I should include source:name=OS_OpenData_StreetView. Sometimes it is appropriate to put that source on the object itself, sometimes it can be done in the change comments. Either way, it's a lot of typing and rapidly becomes tedious.

I agree that sounds tedious - I'm not sure why the wiki would offer that advice to mappers.

iD will record that you used the layer in the `imagery_used` changeset tag, like `imagery_used=OS_OpenDataStreetView` and I think this is good enough.

**Comment by eehpcm** [comment]
> I agree that sounds tedious - I'm not sure why the wiki would offer that advice to mappers.

The wiki says a lot of things.  Some of them make sense, some do not.  That particular thing may make sense in the context of editors other than iD.  Or it may not.

> iD will record that you used the layer in the imagery_used changeset tag, like imagery_used=OS_OpenDataStreetView and I think this is good enough.

I'd think it good enough, too, if you can put my mind at rest on a couple of things.

1. What happens if I look at OS_OpenDataStreetView to get the name of a building but use (say) Bing to trace its outline?  Does iD record both or the one currently selected?  The wiki method does allow me to make the distinction between using that layer for tracing or for names.

2. Depending on the answer to the first question, what happens if I look at OS_OpenData_StreetView and decide it doesn't offer me anything useful?  Does it still get recorded in the changeset tag?

**Comment by bhousel** [comment]
> 1. What happens if I look at OS_OpenDataStreetView to get the name of a building but use (say) Bing to trace its outline? Does iD record both or the one currently selected? The wiki method does allow me to make the distinction between using that layer for tracing or for names.
> 2. Depending on the answer to the first question, what happens if I look at OS_OpenData_StreetView and decide it doesn't offer me anything useful? Does it still get recorded in the changeset tag?

iD will remember whichever background imagery was active while the edit was made.

So if you just look at the OS OpenData StreetView layer but do no edits, nothing is recorded.

If you switch to Bing and add a point, your changeset would be saved with `imagery_used=Bing aerial imagery`

If you then switch back to OS OpenData StreetView and move the point you added, your changeset would be saved with `imagery_used=Bing aerial imagery;OS OpenData StreetView`

Hope that helps..

**Comment by eehpcm** [comment]
> If you then switch back to OS OpenData StreetView and move the point you added, your changeset would be saved with imagery_used=Bing aerial imagery;OS OpenData StreetView

Which means if I've used both, which I sometimes do, the easiest way to get this into the changeset would be to save with a minor error, fix the error, switch backgrounds, and save again?  Better than typing in OS_OpenData_StreetView each time. :)

**Comment by bhousel** [comment]
> Which means if I've used both, which I sometimes do, the easiest way to get this into the changeset would be to save with a minor error, fix the error, switch backgrounds, and save again? Better than typing in OS_OpenData_StreetView each time. :)

I am not following your logic here..  If you have used the layer while editing, it's saved with the changeset.
  
You don't need to save with a minor error and then fix the error. 
Just use iD the way you would normally and it takes care of this detail for you.

**Comment by eehpcm** [comment]
> I am not following your logic here.. If you have used the layer while editing, it's saved with the changeset.

The logic is what do I do if I have made use of **two** layers while editing?

If I follow you correctly, the layer in use at the time of the save is placed in the changeset.  If I edit later and use a different layer that gets added to the changeset.  Introducing a minor error and double-saving with a layer switch appears to be the simplest way of getting both layers acknowledged.  Unless I'm missing something (which is often the case).

And yes, since I found OS_OpenData_StreetView I frequently do use more than one layer.  For buildings it's Bing or Esri for the outline, OS_OpenData_StreetView for the name (if I can't get it any other way).  For streams it's Bing or Esri where the course is visible, OS_OpenData_StreetView for when the course disappears into a wood.

**Comment by bhousel** [comment]
> If I follow you correctly, the layer in use at the time of the save is placed in the changeset.

No, all layers that were used while editing are included in the `imagery_used` tag.  If you use multiple layers, the names are separated by semicolons.
(please reread https://github.com/openstreetmap/iD/issues/5209#issuecomment-411511856)
