### ISSUE TITLE
Broken osmdata.asitvd.ch URLs

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#5211]
Hello

The TMS URLs from osmdata.asitvd.ch in the file openstreetmap/iD/master/data/imagery.json don't work. According to <http://osmdata.asitvd.ch>, the protocol should be HTTP instead of HTTPS. (I've tested them; they do work.)

**Comment by bhousel** [comment]
This issue was moved to osmlab/editor-layer-index#531
