### ISSUE TITLE
Overlapping layer panels

### ISSUE THREAD

**Issue by srividyacb** [openstreetmap/iD#5212]
When streetlevel viewer is expanded, layer panel is not minimised and overlaps with the viewer.

This makes the iD UI cluttered and makes difficuts to interact with the data. We should enable one panel at a time and close opened panels. 

<img width="989" alt="screenshot 2018-08-07 15 17 17" src="https://user-images.githubusercontent.com/3423533/43768445-083662d0-9a55-11e8-8d98-745134540800.png">

Also layers panel should close when clicked on map or map-data.

![image](https://user-images.githubusercontent.com/3423533/43769221-e0530c12-9a56-11e8-8b0c-06d20ae13228.png)

**Comment by bhousel** [comment]
I'll try to improve this, but I don't want to spend too much time on something that the user has total control over.

**Comment by quincylvania** [comment]
After flexboxing all the controls over the map for #4733, this became quick to fix!

![flex demo2](https://user-images.githubusercontent.com/2046746/56158773-d8873f80-5f77-11e9-974f-6be34e5abfd0.gif)
