### ISSUE TITLE
[FYI] Notes uneditable with old web-browser

### ISSUE THREAD

**Issue by deuzeffe** [openstreetmap/iD#5213]
Hello,

Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

In "Notes mode" (Notes layer ON), note **icon** is visible but not content. So, unclickable, uneditable and so on.

It's a bug-(veryveryold)browser-specific, I guess and maybe unuseful to be fixed. So my issue is only FYI ^^

**Comment by bhousel** [comment]
Thanks for flagging this @deuzeffe - does this work with a more recent version of Firefox?  
I think Firefox 52 is not that old really and I'd expect it to work, so this might be worth investigating.

**Comment by mmd-osm** [comment]
Test on Firefox Extended Support Release (ESR 52) (--> https://www.mozilla.org/en-US/firefox/organizations/) shows same result here: hovering over the "Notes" icon won't change the cursor and in general has no impact at all. It's like the notes icon doesn't even exist in the first place.

**Comment by deuzeffe** [comment]
Yes, it works with a Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:56.0) Gecko/20100101 Firefox/**56.0** eg (no more recent browser > 56.0 available here, sorry).
