### ISSUE TITLE
Notes: Show a small teaser of a note even if the notes feature is not active

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5215]
I wonder if there is a way to have the notes feature active by default but in a more silent way than when it is activated right now. 
Something like a on-the-map teaser/entry that helps guiding people to the full notes feature.

My issue is, that I get why the feature is not active by default – to keep the editor simple – but at the same time the notes could help mappers, especially new mappers, to work on the current area of the map.

Related: https://github.com/hotosm/tasking-manager/issues/1157 Right now notes are the best way to store important infos for other mappers on the map; but since the interface is so hidden by default, I cannot trust that other mappers will see those.

# Idea

Maybe there could be a really small note-icon representing a note on the map even if the feature is turned of. And once I click it, the UI activates the new notes feature and also shows a quick guide-overlay explaining the feature to me?

**Comment by bhousel** [comment]
#2524 would let someone enable the notes layer via a url parameter, which is what the task manager probably really wants to do.

(I just renamed that issue.  It was specific to enabling the Mapillary layer, but that's because it was an old issue from back when Mapillary was the only layer - now we have many more, including notes and other stuff).

**Comment by tordans** [comment]
@bhousel thanks, the URL param will make the task-manager issue possible.

However, this issue was more about **improving the discoverability of notes in iD in general**. 
Basically an idea to softly educate iD users about the notes feature and its potential.

Right now, notes are quite hidden behind this sidebar panel and the checkbox.
