### ISSUE TITLE
Add check before save: Overlapping ways

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5217]
When I enter the save screen, the editor already has a check for ways without attributes.

Could there also be a check for ways that overlap but don't connect?
Similar to https://github.com/openstreetmap/iD/issues/4646 (for creating ways), but as a check on the save menu.

Context: https://github.com/hotosm/tasking-manager/issues/893#issuecomment-340440306 – I would like to keep using iD to validate HOT OSM Tasks.

Example:
https://www.openstreetmap.org/edit#map=19/7.52498/80.24793

<img width="514" alt="bildschirmfoto 2018-08-12 um 10 27 41" src="https://user-images.githubusercontent.com/111561/44000126-873ee5fc-9e1a-11e8-8eff-64b3f1274f50.png">

Other ideas:
Maybe highlight those nodes inside the editor? Eg make them red.

Related:
I am unsure about the scope – only for ways or also for ways that cross rivers/streams without a bridge/tunnel?

**Comment by bhousel** [comment]
I'm actually thinking of having iD just add junction points automatically.  
It seems silly to even bother the user about this.

**Comment by tordans** [comment]
I like the idea. 
On a detailed level this interaction might create some edge cases. But thats probably easier to figure out with some prototype than just theorising about it, so I wont ;).

I does not really solve the validation issue. But it might just make it obsolete so that might be enough for the validation usecase.

**Comment by manfredbrandl** [comment]
Enterig non-crossing-Streets (e.g.: bridge/tunnel) should stay easy.

**Comment by Nakaner** [comment]
> I'm actually thinking of having iD just add junction points automatically.
> It seems silly to even bother the user about this.

Please don't do that! If a user draws a road over another road and adds the `bridge=yes` tag afterwards, the two roads are connected which is completely wrong.

I think that iD should not do too much things automatically in the background, especially if they can be harmful. Changes done automatically can lead to changeset comments by other mappers complaining about the automatic change but the mapper not knowing what they are complaining about.

A button to add the missing node in the validation view is good (similar to JOSM's "repair" button in the Validation panel).

**Comment by slhh** [comment]
> Yeah I would make it add the junction points only if the highways are on the same layer and remove junction points if they are not. I mean, this is obvious, right?

Junction nodes aren't redundant information. We do not model ramps between layers in OSM, and therefore, highways which are on different layers might need to be connected or not. This makes it impossible to remove the nodes automatically.

A potentially missing junction node indicates one of the following errors:
- the node is really missing
- layer tagging is wrong

In the later case, adding the node automatically would add another error and hide both errors from validation and inspectors.

**Comment by quincylvania** [comment]
This was done in #5830!
