### ISSUE TITLE
add internet_access:ssid tag to apartments feature's fields

### ISSUE THREAD

**Issue by prototype99** [openstreetmap/iD#5218]
relatively self explanatory. i went to add a known ssid and found that it was not considered a valid field

**Comment by bhousel** [comment]
Hmm, it is a "valid" field, but it might not be listed in the sidebar.  Can you share a screenshot of where you were trying to add it?

**Comment by bhousel** [comment]
OK I see.. In iD we don't have the wifi fields on the apartment building preset.  I think people probably do not typically want to map these, and the fields are for the most common things.  

You are still allowed to add it to the map if you want to.. You can add the `internet_access:ssid` tag in the raw tag editor like this:

![add_ssid](https://user-images.githubusercontent.com/38784/44070821-f43b5ab6-9f53-11e8-87b3-5cb94876d3bf.gif)
