### ISSUE TITLE
Perf issue: Imagery lookup is very slow

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5226]
iD needs to pretty frequently check what imagery is available in the area where the user is editing.  This has recently gotten very slow.   

We can speed this up a lot by:
- the imagery sources really need to use proper multipolygons, not how it currently works with an array of polygon rings (see https://github.com/osmlab/editor-layer-index/issues/217)
- index using `which-polygon`, same as what we do for the [community index here](https://github.com/openstreetmap/iD/blob/24f09fd6ecd8cbd1f9665c62fca452a8c7be6288/data/index.js#L30-L40)

It should not take 1 second to know what polygons cover the current view.. This is just really really bad.

![screenshot 2018-08-15 13 16 38](https://user-images.githubusercontent.com/38784/44162171-84952580-a08d-11e8-80c5-03a726e7c772.png)

**Comment by prototype99** [comment]
you mean the satellite imagery right? for me it isn't even rendering the imagery beyond a vague blur if i zoom in from the worldwide view. if i refresh it fixes, but otherwise....

**Comment by bhousel** [comment]
hey @prototype99  - yes this is about the satellite imagery.
I've fixed the performance issue in 8b3637e but it sounds like your issue is something else.

If you are still having issues with imagery not working, can you do these steps:
- verify the issue exists in http://preview.ideditor.com/master/ 
- open a new issue with details about where you are testing, your browser, and a screenshot?

Thanks!

**Comment by bhousel** [comment]
Just wanted to flag that I broke the "custom" and "none" options when I did this .
They currently don't show up because these options don't have a polygon, so the index doesn't find them.

I'm working on some other changes to custom backgrounds and data and will include a fix for this in an upcoming PR.
