### ISSUE TITLE
Conflict resolution popup, potential endless loop in conflict resolution

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/iD#5228]
Steps to reproduce:

1. JOSM: Create way with 2 nodes, tags= highway=path
2. JOSM: Upload change
3. iD: Load area, including way
4. JOSM: Add a third node in the middle of the way
5. JOSM: Upload change
6. iD: add a second tag to the way: surface=grass
7. iD: Upload changes
8. iD: Conflict detection kicks in, resolves conflict, and uploads again
9. iD gets stuck on the following screen:

![bildschirmfoto von 2018-08-16 09-36-26](https://user-images.githubusercontent.com/5842757/44194962-f164fa00-a137-11e8-9323-f41807e741fe.png)

There's also an exception on the javascript console:

![bildschirmfoto von 2018-08-16 09-43-40](https://user-images.githubusercontent.com/5842757/44195289-e3fc3f80-a138-11e8-891b-feae68c055e1.png)

Tested on http://preview.ideditor.com/master and dev instance. The change in question has been applied to the database: https://master.apis.dev.openstreetmap.org/way/4305175922 (note the 3 nodes, and the 2 tags).

Someone reported on the forum, that this counting up may also happen in an endless loop (!) going on for hours and hours. This is probably the case when the conflict resolution didn't work out at all, and the algorithm keeps trying and trying.

**Comment by bhousel** [comment]
Thanks for reporting @mmd-osm  - the exception on the console explains exactly what the issue is 👍

**Comment by mmd-osm** [comment]
Awesome. Any idea where this endless loop thing might come from? It would just show the popup, count from 0 to NNN, then start over again from zero and so on.

**Comment by bhousel** [comment]
> Awesome. Any idea where this endless loop thing might come from? It would just show the popup, count from 0 to NNN, then start over again from zero and so on.

Hmm yeah in this case it wasn't looping, iD resolved all the conflicts and sent the merged changeset just fine.  This bug happened because the uploading code failed to call the final callback and let the saving code know that it was done.

There's also #5114 - I think that's what the person on the forum might have encountered.
