### ISSUE TITLE
Whitelist listed_status to allow mixed-case tags

### ISSUE THREAD

**Issue by SK53** [openstreetmap/iD#5231]
Just noticed that [listed_status](https://wiki.openstreetmap.org/wiki/Key:listed_status) is autocompleting in the raw tag editor with all lower-case. The tag is widely used in the UK for storing the official listed building status verbatim. The tag is a local equivalent of, and perhaps earlier than, various heritage tags. 

Therefore I would like this tag to be added to the whitelist of tags allowing mixed case.

See #3280,#3377 for similar cases which have already been resolved.

**Comment by bhousel** [comment]
Thanks @SK53 - I just made this change.
