### ISSUE TITLE
Don't add building=yes to amenity=biergarten by default

### ISSUE THREAD

**Issue by SK53** [openstreetmap/iD#5232]
I notice if I tag an area with amenity=biergarten, a building=yes tag is added. The whole point of a Biergarten is that one is outside!

Can we lose this behaviour.

(Incidentally, it may not be a good idea to translate Biergarten to Beer Garden as these are different things (the former almost exclusively in DACH countries), the latter (amenity=beer_garden) quite often associated with pubs in Britain and Ireland.)

**Comment by bhousel** [comment]
Thanks @SK53 - I've changed the preset name to "Biergarten" and removed the default building tag.
