### ISSUE TITLE
Add "Check/Uncheck All" for Map Data > Map Features checkboxes

### ISSUE THREAD

**Issue by JAT86** [openstreetmap/iD#5234]
I could not find any **select/check/uncheck all** for the checkboxes under `Map Data > Map Features`. It is tedious to keep on toggling these boxes one by one when you want to display only a few features or one:

![screenshotosmideditorforgithub](https://user-images.githubusercontent.com/30237173/44303736-2d3bd180-a37b-11e8-9e20-bd7299c5225e.png)

**Comment by boothym** [comment]
I suggested this in #3288 - would still be good to have despite the on/off toggle for OSM map data.

**Comment by bhousel** [comment]
We're likely moving these to another screen, and will have more room for check all / uncheck all.

**Comment by quincylvania** [comment]
We can use the same design as for the validation rule controls. They're pretty subtle so I think we can do this without waiting.

![Screen Shot 2019-05-22 at 11 36 22 AM](https://user-images.githubusercontent.com/2046746/58188056-f8e89f00-7c85-11e9-8154-c515e62ed242.png)
