### ISSUE TITLE
make shop=chemist searchable with "Apothecary" (add synonym)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5235]
I know that apothecary is an outdated term, but it is quite likely to be remembered especially by people that have similar word for this shop in their native tongue.

Or at least I tried searching for "apothecary" and become surprised on not finding anything.

**Comment by matkoniecz** [comment]
I know that I can add synonyms to translated languages with Trasifex but I am not sure how to add them to root English language version.

**Comment by bhousel** [comment]
Good suggestion, I just added this search term.
