### ISSUE TITLE
Deletion of junction between outer ways of a relation creates a gap in the relation

### ISSUE THREAD

**Issue by maxerickson** [openstreetmap/iD#5240]
At the moment opening iD and right clicking on https://www.openstreetmap.org/node/19612725 offers deletion in the context menu. Deleting that node breaks rendering of Lake Michigan.

This is likely the action taken in https://www.openstreetmap.org/changeset/61784048 which temporarily hid Lake Ontario.

**Comment by bhousel** [comment]
Yep, not the first time this has happened.. We're tracking this on #3681
