### ISSUE TITLE
es6 syntax support?

### ISSUE THREAD

**Issue by wonga00** [openstreetmap/iD#5246]
Hi, just want to get clarification on whether es6 language is supported in this repo -- the linter seems to allow es6 syntax, and the js contribution section indicates the usage of Airbnb style, which seems to be es6 + babel. However using es6 causes the tests to not be able to load -- looks like loading a bundled `iD.js1` that has es6 syntax fails in phantomjs.

**Comment by bhousel** [comment]
> looks like loading a bundled iD.js1 that has es6 syntax fails in phantomjs.

Yes, I'd like to stick with ES5 syntax for now, mostly for 
* IE11, which about 15-20% of our users are still using the last time we checked with the OSM admins.
* PhantomJS which runs our tests (it would be great to replace this, but I don't have the time).

The only ES6 syntax we're currently using in iD is module `import`/`export`, which gets processed by Rollup.  

We've thought about using Map/Set in a few places (IE supports these), and polyfiling some useful ES6 features like Promises, but overall there's not much benefit to switching existing code that works ok, and a lot of debugging downside in introducing transpilation via Babel.  

Another point to consider is that a lot of iD is hot code, and most ES6 features are significantly slower than ES5.  (This has changed with the switchover to Turbofan in recent Chrome browsers).  So I still write a lot of c-style for loops for speed.

**Comment by bhousel** [comment]
BTW , to avoid confusion, I'll drop the mention of AirBnb style if they are now recommending ES6+Babel..

**Comment by wonga00** [comment]
ah thank you for the clarification, that is very helpful. curious, is there a way to configure the linter to detect es6 usage? seems like we need es6 on to be able to deal with rollup but not sure of how to exclude all other es6 usage.
