### ISSUE TITLE
PNOA and Catastro (Spain) are no longer shown in iD as of v2.11.0

### ISSUE THREAD

**Issue by Robot8A** [openstreetmap/iD#5250]
![imagen](https://user-images.githubusercontent.com/19521377/44628036-14ae5700-a939-11e8-8576-89d273cfe2c1.png)

**Comment by persep** [comment]
The are still not working with iD 2.11.1

**Comment by persep** [comment]
A workaround solution for having back the Spanish Catastro background is to define a custom background with these parameters: 
`http://whoots.mapwarper.net/tms/{zoom}/{x}/{y}/Catastro/http://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx`

**Comment by persep** [comment]
PNOA Spain and Catastro Spain are visible now in the background imagery and working ok
