### ISSUE TITLE
Is there an example of valid vector tile url template?

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#5252]
Is this vector tile url template below valid? 
https://cyberjapandata.gsi.go.jp/xyz/experimental_fgd/{z}/{x}/{y}.geojson
I can't check "custom map data" checkbox on after setting the url above on the Map Data pane. Source of the tile url template is from GSI Japan.
https://github.com/gsi-cyberjapan/vector-tile-experiment/blob/gh-pages/README_en.md

**Comment by bhousel** [comment]
> Is this vector tile url template below valid?
> https://cyberjapandata.gsi.go.jp/xyz/experimental_fgd/{z}/{x}/{y}.geojson

That doesn't seem valid - that looks experimental and actually sends geojson.

When we say vector tiles, we mean this specification: https://www.mapbox.com/vector-tiles/specification/
