### ISSUE TITLE
GPX file urls not working unless they actually end in .gpx 

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5253]
Yesterday all were OK (version 2.10.0 I belived ?)
Today (version 2.11.0), when I select a GPS track (one of mine or from another) and choose "modified", when using firefox, waterfox or  chrome, the track is not visible !

**Comment by mappingjunkie** [comment]
I am confirming this issue.  When I follow this path, I am not able to see the GPX track:
www.openstreetmap.com --> GPS Traces --> Edit

This makes it impossible to use ID to add new features using a GPX track.

**Comment by kevinp2** [comment]
I can confirm this issue and **would like to request that it be addressed urgently**.  I am in the process of mapping some forest roads in Colorado / New Mexico and my memory of these roads will fade soon.

**This was working properly only 2 - 3 days ago.**

Here is a test case: https://www.openstreetmap.org/user/kevinp2/traces/2788683

I have tried this under:
MacOS + Safari
Windows 7 + Chrome

In both cases, I follow this process:
GPS Traces > See my traces > Click on the edit hyperlink

The map opens at the correct starting point of the trace, but the trace itself is nowhere to be seen.

**Comment by iandees** [comment]
A workaround for this is to click the download link on your trace page and drag the resulting GPX file to iD. It will display it and let you map until this gets fixed.

**Comment by kevinp2** [comment]
Cool, that workaround worked, thanks!

**Comment by bhousel** [comment]
Ah yeah, this bug was introduced in the latest release.  Previously, iD tried to guess what kind of a data file it was based on its extension (.gpx, .kml, .geojson), but it would just assume that any file without an extension was a gpx file.  I didn't know that other sites were relying on this behavior.  

I'll put a fix in so that file urls passed in via the url like `gpx=` can continue to be assumed to be gpx.

**Comment by pinzaglia** [comment]
The problem is not this one.
Since the v2.11.0 it is not possible to display .gpx files, even if they have the .gpx extension.
The "custom map data" selection box is greyed since this release, and no .gpx file are displayed.
It worked fine with the previous release, (before the 26 august)

**Comment by pinzaglia** [comment]
The v2.11.1 does not fix the problem.

**Comment by Mahabarata** [comment]
For me all it ok now : I can see my tracks again
I'm ok with the closure of this issue
Thanks for your quick resolution
Best regards
