### ISSUE TITLE
Bounding box from Tasking Manager is no longer displayed

### ISSUE THREAD

**Issue by govvin** [openstreetmap/iD#5254]
Using current version of iD as editor, the magenta bounding box is no longer displayed automatically when working with tasks from the Tasking Manager. The work-around is to download the task GPX and upload it manually, which is accessible from the map data menu.

![image](https://user-images.githubusercontent.com/5821688/44649337-2580ca80-aa16-11e8-8beb-5cb151b35493.png)

**Comment by bhousel** [comment]
Dup of #5253
