### ISSUE TITLE
Loading a GPX file makes editor unusably slow

### ISSUE THREAD

**Issue by JesseCrocker** [openstreetmap/iD#5256]
After loading a 300kb GPX file iD is frequently taking over a second to respond to clicks. unchecking "Custom Map Data" returns performance to normal.
This seems to be a regression in 2.11.0.

**Comment by bhousel** [comment]
iD draws 2x the number of strokes now, to support hovering and selecting.  Can you share the gpx file somewhere so I can take a look sometime next week?

**Comment by RicoElectrico** [comment]
In fact, there's no reason to make GPX files selectable.
Users report this is annoying:
https://www.facebook.com/groups/500589303317858/permalink/1935196723190435

**Comment by jjiglesiasg** [comment]
I really agree that uploading a GPX for tracing routes under Custom Map Data, make the edition in ID annoying, becuase continuosly your are selecting the GPX trace and Not drawing the track/road; also it make much harder to make connections between roads/tracks. In the old way the GPX was just a line that you followed to trace, now you need to be selecting or unselecting so you can draw...

**Comment by bhousel** [comment]
I just tested with a 800kb GPX file and this seems better now post-#5479
