### ISSUE TITLE
Create preset for Amazon Lockers

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#5260]
Amazon Lockers are becoming more and more commonplace in the UK, and are often found at shopping centres, supermarkets and universities. If you don't want to call it an Amazon Locker and would like it to be more generic, then just add "amazon locker" as a search term.

https://en.wikipedia.org/wiki/Amazon_Locker
https://wiki.openstreetmap.org/wiki/Tag:vending=parcel_pickup

- Name: Amazon Locker
- Tags: amenity=vending_machine, vending=parcel_pickup, operator=Amazon
- Fields: ref, name (they tend to individual names)

**Comment by andrewharvey** [comment]
There are many different providers of parcel pickup lockers, so long as the preset allows people to map non-Amazon parcel lockers.

**Comment by Slawek234** [comment]
Examples: InPost, DHL, DPD, Deutsche Post, Australia Post, Poste Italiane, Omninova and many many other larger or smaller brands.

**Comment by RicoElectrico** [comment]
Isn't it an overlap with https://github.com/osmlab/name-suggestion-index ?

**Comment by bhousel** [comment]
I just added a Parcel Pickup Locker preset..

I'm also going to find a way to add it to name-suggestion-index also.  That project currently doesn't check the planet for `amenity=vending_machine` so I've added it to the list and will see what kinds of vending machines currently show up frequently.  (Downloading latest planet file now).
