### ISSUE TITLE
higher resolution Mapillary images

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#5263]
The embedded Mapillary image isn't as high resolution as on Mapillary.com, sometimes this makes the difference between reading a sign or not, I know there's probably not much that can be done on the ID side, but perhaps when the user zooms into the limit, we popup a hint for the user to link out to the Mapillary image directly?

**Comment by bhousel** [comment]
I'll see if there is anything in the viewer that we can adjust.  The viewer already has a link to the full size image on Mapillary.

**Comment by andrewharvey** [comment]
Some analysis of this was done for JOSM at https://github.com/JOSM/Mapillary/issues/60

> The viewer already has a link to the full size image on Mapillary.

That's really helpful, but most users won't know a higher res version exists when they click through, if we can't get a higher resolution version then it would be good to add a hint when users try to zoom past max zoom.

**Comment by bhousel** [comment]
It looks like upgrading the viewer in #5322 will also improve the resolution of the images.. 👍
