### ISSUE TITLE
Files with an uppercase extension are not displayed

### ISSUE THREAD

**Issue by pinzaglia** [openstreetmap/iD#5266]
Since v2.11.0 and even v2.11.1 a drag and drop of a .GPX file in the ID Editor windows has no effect.
In my case, the "Custom map data" field is unselected and it is not possible to select, because it's "greyed".
All was ok before the 26 august.

**Comment by vershwal** [comment]
Hey @pinzaglia !!

So the GPX layer is renamed as "Custom map data" and you can use it for drag and drop or directly browsing the file from your PC or even giving a URL.

> it is not possible to select, because it's "greyed"
Ya!! So, it remains grey until you select a file(or drag-drop), and it gets automatically selected once you give a .gpx/.geogson/.kml/.json file and after that, you can select/deselect it.

I checked with [run.gpx](https://www.mapbox.com/help/define-gpx/) it shows up like this : 
<img width="915" alt="screen shot 2018-08-31 at 12 49 12 pm" src="https://user-images.githubusercontent.com/17474532/44898714-56664580-ad1d-11e8-800b-f19a7bc3b27d.png">

**Comment by pinzaglia** [comment]
Hey Princi, thanks for your answer.
    
    I've found that:
    
    All my files are named xxxxx.GPX and not xxxxx.gpx
    If I rename them from .GPX to .gpx all is ok as it was before, the
    track is displayed.
    
    So, the title of the issue should be:
    
    Files with extension .GPX (upper case) are no more displayed since
    the v2.11 
    
    Thank you again. 
    
    
    
    
     
    
    Le 31/08/2018 09:28, Princi Vershwal a
      écrit :
    
    
      Hey @pinzaglia !!
      So the GPX layer is renamed as "Custom map data" and you can
        use it for drag and drop or directly browsing the file from your
        PC or even giving a URL.
      
        it is not possible to select, because it's "greyed"
          Ya!! So, it remains grey until you select a file(or
          drag-drop), and it gets automatically selected once you give a
          .gpx/.geogson/.kml/.json file and after that, you can
          select/deselect it.
      
      I checked with run.gpx
        it shows up like this :
        
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openstreetmap/iD","title":"openstreetmap/iD","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/openstreetmap/iD"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vershwal in #5266: Hey @pinzaglia !!\r\n\r\nSo the GPX layer is renamed as \"Custom map data\" and you can use it for drag and drop or directly browsing the file from your PC or even giving a URL.\r\n\r\n\u003e it is not possible to select, because it's \"greyed\"\r\nYa!! So, it remains grey until you select a file(or drag-drop), and it gets automatically selected once you give a .gpx/.geogson/.kml/.json file and afte
r that, you can select/deselect it.\r\n\r\nI checked with [run.gpx](https://www.mapbox.com/help/define-gpx/) it shows up like this : \r\n\u003cimg width=\"915\" alt=\"screen shot 2018-08-31 at 12 49 12 pm\" src=\"https://user-images.githubusercontent.com/17474532/44898714-56664580-ad1d-11e8-800b-f19a7bc3b27d.png\"\u003e\r\n"}],"action":{"name":"View Issue","url":"https://github.com/openstreetmap/iD/issues/5266#issuecomment-417577825"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openstreetmap/iD/issues/5266#issuecomment-417577825",
"url": "https://github.com/openstreetmap/iD/issues/5266#issuecomment-417577825",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [openstreetmap/iD] No more display of .GPX files, impossible to add new path or points  (#5266)",
"sections": [
{
"text": "",
"activityTitle": "**Princi Vershwal**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@vershwal",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"openstreetmap/iD\",\n\"issueId\": 5266,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"openstreetmap/iD\",\n\"issueId\": 5266\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/openstreetmap/iD/issues/5266#issuecomment-417577825"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 373753800\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by JamesKingdom** [comment]
Thank you @pinzaglia for finding this, I can reproduce this.

**Comment by JamesKingdom** [comment]
I just pushed a patch to fix this, you can try it here; http://preview.ideditor.com/master/ .
It will be available on the OSM website when iD is next released.

**Comment by pinzaglia** [comment]
Ok the patch works well. Thanks for this quick fix.
