### ISSUE TITLE
An Ordnance Survey background is missing

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5272]
Yesterday I noticed that one of the three Ordnance Survey backgrounds that were available to UK mappers has gone missing.  I don't use it often enough, or pay close attention to what's on the list, to be sure exactly when it disappeared, but it must have been 2.11.0 or 2.11.1 because I used it several times in 2.10.0.

Still available are OS New Popular Edition Historic and OS OpenData StreetView.  There used to be a third one (I can't even remember what it was called) which provided information (such as contours) that the other two do not.  It also had far more spot heights than the OpenData one.

The changelog doesn't seem to mention it.  Did it vanish because of copyright/licensing issues or was it an unintended accident?  If it was an accident, could we have it back please?

**Comment by JamesKingdom** [comment]
Related to #5250

**Comment by eehpcm** [comment]
@JamesKingdom 

Thanks for spotting the related issue.  I did look at recent issues but didn't spot that one as being relevant.  There's another one too, I see (which I also missed).

**Comment by boothym** [comment]
For me in Scotland there's three OS backgrounds - OpenData StreetView, OS Scottish Popular historic (this will be the NPE in England), and 7th Series (OS7). 

There used to be a lot more but iD took the decision to exclude imagery >20 years old, so once the age was added in the editor-layer-index then the older maps disappeared - see #3190 and #3453 

For the 7th Series however, that map background only covers certain areas - see https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/7thSeries-OS7.geojson So if you zoom into Edinburgh and select the 7th Series then zoom out to z8 or so - you will see that not much of the UK actually has coverage.

**Comment by bhousel** [comment]
This is working now!  The polygon array was being treated as an outer with holes, and I needed to rewrite it to be an array of outers.

 #5250 #5264 #5272 were all the same thing
