### ISSUE TITLE
Destination or exits on GPS 

### ISSUE THREAD

**Issue by dartmouvic** [openstreetmap/iD#5276]
Destination or exit does not show for Nova Scotia motorway exit on GPS

**Comment by bhousel** [comment]
I'm sorry, I don't understand what this issue is about?

**Comment by dartmouvic** [comment]
When the osm map is my garmin gps the highway exits show up as "ramp "ahead"

**Comment by manfredbrandl** [comment]
@dartmouvic Where did you get the osm map for your garmin? Maybe you can create an issue there, here are the issues for the iD-Editor for OSM.

**Comment by bhousel** [comment]
Yeah, closing here - this doesn't sound like an issue with the iD editor.
