### ISSUE TITLE
Topo

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5277]
In a older version of ID, I had maps with topo.
For a while it disappeared, with the last version of ID I found back some (looks like it depends of the country or region : so I'm not sure they disappeared).
I may of course use my own one's... and it is what I do.
But I think it will be a great thing if everyone could have that choice in the list of maps.
There is at least one I think you should add because it's open : in fact these are tiles from openstreetmap project :
https://a.tile.opentopomap.org/{zoom}/{x}/{y}.png

Best regards

**Comment by bhousel** [comment]
Ok, yeah some people do want this.
In the past, we were using opencyclemap, and even more recently, thunderforest-landscape (probably the best one): 
 `https://{switch:a,b,c}.tile.thunderforest.com/landscape/{zoom}/{x}/{y}.png`

I'll move this issue over to osmlab/editor-layer-index for discussion there.

**Comment by bhousel** [comment]
This issue was moved to osmlab/editor-layer-index#550

**Comment by bhousel** [comment]
Sorry - I realized after commenting above that the layer already exists in editor-layer-index, and I just needed to enable it on the iD side.
