### ISSUE TITLE
Can't view all options on combo boxes that are very near the bottom of the browser window

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5280]
I try on chrome and Firefox, both have the same pb so I think it's an ID problem.
I will explain with this example :
https://www.openstreetmap.org/edit?gpx=2785067#map=16/-34.7071/-70.0902
On left of the GPX you have a stream
Select it then, on the relation, delete the "tributary"
Then click outside then click back in the empty zone of the relation : a list of choice appears but all the list is not visible, the end of the list is out of my navigator, perhaps because my scrren is not too big.
If you don't see the pb, try to decrease the size of your navigator
I'm using a laptop, my resolution is at the max, my navigators are on all the screen so for me it's impossible to increase anything and the pb is real
Best regards

**Comment by bhousel** [comment]
This is covered in a bunch of existing issues #3622 / #3487 / #4128

**Comment by Mahabarata** [comment]
In fact no, there no relation between my issue and the 3 you told.
I wanted to add a capture to show you.
But I cannot... because the pb has disappeared because of a new bug !

For a river I select a waterway relation, then I put the focus in the role and then... nothing : no more list of roles ! So of course the list doesn't appears out of my navigator, it doesn't appears at all, lol !

Good luck
Best regards

**Comment by bhousel** [comment]
> For a river I select a waterway relation, then I put the focus in the role and then... nothing : no more list of roles ! So of course the list doesn't appears out of my navigator, it doesn't appears at all, lol !

Oh yeah - you aren't seeing the list of roles because http://taginfo.openstreetmap.org/ is not working today.  That list comes from another site.

**Comment by Mahabarata** [comment]
Ok, I will look in a few days and I will explain more clearly my pb
Thanks !

**Comment by bhousel** [comment]
Thanks @Mahabarata that does clear things up.  I'll retitle the issue.
