### ISSUE TITLE
relation waterway

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5283]
on wiki, we find that :
https://wiki.openstreetmap.org/wiki/Relation:waterway
so for the roles of this relation, only main_stream, side_stream and spring seems possible

On ID, we can find :
main_stream, side_stream, tributary, waterbody, main stream, riverbank, main_steam (again ?), inner, outer, spring and forward

I think wiki is not good ; tributary is clearly needed, on the right side (part taginfo), we can see it is quite used. I explain that with the fact that a tributary can clearly not to be changed to main_stream, side_stream or spring. And tributary needs sometimes to be indicated because some tributaries may be very important to explain to growth of the river.

We can see details of the use of roles here :
https://taginfo.openstreetmap.org/relations/?rtype=waterway#roles

A lot of used roles are not in your list on ID, looks like some peoble have great imagination.
So to update your list seems not to be a problem.

I will suggest to keep only :
main_stream (the first one), side_stream, tributary, and  spring

Some could want waterbody and riverbank but for me it looks like a bad use of the role.

Best regards

**Comment by bhousel** [comment]
I think you are talking about this - if not let me know.. (It would be great to include screenshots in your issues).

<img width="300" alt="screenshot 2018-09-04 12 20 15" src="https://user-images.githubusercontent.com/38784/45044050-f8976d80-b03c-11e8-9658-344a094c5298.png">

@Mahabarata said:
> We can see details of the use of roles here :
> https://taginfo.openstreetmap.org/relations/?rtype=waterway#roles

This taginfo query is the same query that iD does to fill the relation role list - we don't maintain our own list.  

(I think `main_stream` appears a few times because in taginfo it sometimes appears with a trailing space - somebody should clean up those in OSM, then they won't appear in the list twice anymore).

**Comment by Mahabarata** [comment]
Ok, I undertstand : thanks.
To clean up osm like you said, I imagine it's not possible with ID ? For example if I want to look for every "role == something where relation == waterway", I cannot with ID, I need another editor like JOSM ?
Best regards

**Comment by bhousel** [comment]
> To clean up osm like you said, I imagine it's not possible with ID ? For example if I want to look for every "role == something where relation == waterway", I cannot with ID, I need another editor like JOSM ?

Yes, JOSM + Overpass queries are probably the better tools for doing this kind of cleanup.

**Comment by bhousel** [comment]
> If I remember, relation=waterway had a lot of good roles (example, maybe 20000 roles "main_stream") and not a lot of bad roles of the same kind (maybe 600 "main stream", with a space rather than a _). To transform all the 600 bad roles to the good one, do I need to change them one by one by editing them one by one whaterver editor I choose ? Or it is possible, with JOSM or another tool, to do something like (I will use php or javascript for my example because i know quite well both) : if (relation == "waterway" && role == "main stream") then role = "main_stream" ?

I'm really not an expert on how to do it, but this might be helpful:
https://help.openstreetmap.org/questions/29022/overpass-turbo-query-wizard-output-to-josm-how

You might be able to search on that site or ask there for more details..

**Comment by Mahabarata** [comment]
Thanks for your answer, very kind indeed (and sorry to answer so late, my visa was almost at the and and I need to move a lot to enter another country).
The link you give me is quite old so versions of JOSM and overpass turbo are a little different but it was still useful : yesterday i install JOSM et have made a lot of changes with these softwares to OSM (still not visible with infotag but very soon I think : so I think bad versions of main stream will disappear in ID).
For me this issue is definitely closed, again a lot of thanks.
Best regards

**Comment by Mahabarata** [comment]
For curious people, if you look at the taginfo (the second link in my first post) and at the list in ID, you will see that they are different (despite the second post "This taginfo query is the same query that iD does to fill the relation role list").

In fact the lists are the same but you need to sort the list in taginfo by the ways (by clicking on the fourth column) : quite strange for me, a bug ?

Other thing : I spend a lot of time to clean up osm but for nothing : in fact, even if there is now less bad roles in OSM, ID still propose 10 roles in the list (11 roles before my clean up). The 11th had before the clean up 60 occurrences and the 10th has now only 29 occurrneces.

Looks like ID creates the list according to the total number of roles (70 roles). So I stop to cleanup because I'm pretty sure that, if I find and delete all the riverbank (for example) then in the list of ID will appear the 11th = canal and so on and I have no time to clean up the 65 bad roles.

Maybe ID should take a threshold to create the list ? For example the roles with more than 100 occurrences ? But before to do this, you will need to take care of all the roles, not only the roles of the ways because otherwise "spring" will disappear.

Best regards
