### ISSUE TITLE
Issue with French translations + Add highway/waterway milestone presets

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5284]
On ID in french, we can find "borne kilométrique ferrovaire" for railway:milestone, which is a good translation.
But the translation (and the icon) for highway:milestone is very bad (I also could say false) : "route".
A "route" (road) is a way, it cannot be a point.
I will suggest to changed that to "borne kilométrique routière" (and to used the same icon that for the railway).

On ID we find the relation:waterway translate to "voie navigable" : it is false.
"voie navigable" means that you can go with a boat on it. Some parts of the waterway clearly are not "navigable".
For me the best translation would be "cours d'eau". You will find this here for example : http://context.reverso.net/traduction/anglais-francais/waterway

Best regards

**Comment by manfredbrandl** [comment]
@Mahabarata You could do the Change yourself, see: 
https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating Are you intrested?

**Comment by bhousel** [comment]
Yes @Mahabarata - Our translations are handled through [Transifex](https://www.transifex.com/openstreetmap/id-editor/dashboard/), so you should sign up for an account there to fix issues with the translations. 

We don't have a preset for [highway milestone](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmilestone) or [waterway milestone](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dmilestone), so I'll just add those now.

**Comment by Mahabarata** [comment]
Hi,

sorry if I answer so late, I was in mountains with no Internet for a few days.
I create a count on transifex and I see that someone (robtat) did one change (the hightway: milestone) : thanks to him !
I have done the second one (waterway = cours d'eau).
But when going back to osm, I can see the translations are not in ID.
I think there is a delay but Robtat did the changes 5 days ago : is it normal that we cannot see it today ?

Best regards.

**Comment by bhousel** [comment]
> Robtat did the changes 5 days ago : is it normal that we cannot see it today ?

Yes this is normal.. New translations get bundled with iD whenever I release a new version.

> So my question is : how long to have them in the the 'true' ID ? I didn't find the answer in the help

Usually about once a month.

**Comment by Mahabarata** [comment]
OK, thanks !
Have a nice day
