### ISSUE TITLE
question: create another walkthrough, is it possible?

### ISSUE THREAD

**Issue by althio** [openstreetmap/iD#5290]
I wonder how much work it is to create another walkthough.
For example, one group might want to introduce mapping to specific features.
Could they use the walkthough as a framework, but propose specific tutorials (to a country, a local area, a thematic...)?

Is it possible? What does it take? How much tech/dev skills?

**Comment by bhousel** [comment]
Yeah I was thinking of making another "advanced" walkthrough (see #4012, #4007, #3610).  Also the current walkthrough feels slightly too long.

It would probably take me at least a week or more of time.  This is significant, but I think worth doing at some point.  

For another dev to tackle it, they'd already need to be really familiar with how the existing walkthrough works.  I think there are other more impactful things I'd rather see new contributors work on.

I'm kind of wary of the idea of country or local area specific walkthroughs.  Someone could make that, but OSM should really try to be a global project, and I put a lot of work into trying to make iD as universal as possible.

**Comment by althio** [comment]
Thanks for framing what is needed and the level of complexity here.

I still think the walkthrough is a gem, a great tutorial, one of the best
bit of iD.

For the sake of discussion though, I would argue that our imaginary little
town does still feel very green and somehow western. The idea of different
chapters in the walkthrough could come with other settings, other kind of
imageries, from other places and other continents. That would in my opinion
really suits the diversity and global aspect of the project.
That's for the default instance of iD of course.

Initially I was also wondering about maybe a separate instance of iD,
non-global, non-generic. It is already possible to (rather easily) adjust
the presets for a thematic and a region. My thoughts were: what about the
walkthrough, can this be adapted (easily) as part of a new instance? Your
answer is no, and thanks for the detailed response.
