### ISSUE TITLE
gpx tracks in 2.11.1

### ISSUE THREAD

**Issue by rebio** [openstreetmap/iD#5296]
In my opinion one of the worst updates iD got so far.

I can sill include a gpx track, but to get there I have to take another step. Dowloading something from the web is nice, but I will never use that. Where is the problem to put them below each other and not have them inside a sub menu.

The worst thing is that the gpx track is clickable. Since my GPS device is pretty accurate it's almost always on the way and selecting the way and not the gpx file is sometimes impossible. Grabbing a single node to move it? You can forget that one good Sir! Trump says "GPX file first!".

If there is a need to show the track stats (three of them so far and I couldn't care less about any of them) it can be moved over to the side menu where you select it from your HDD.

If you make such changes, please give me at least an option to switch back. The new version is nothing but garbage for me. It is so bad, it gives me cancer.

BTW: I'm pretty pissed if it wasn't clear until this point.

**Comment by bhousel** [comment]
Wow, not nice @rebio.  We've already got #5257 for this, you don't need to be a jerk.
