### ISSUE TITLE
Pressing command key deselects objects

### ISSUE THREAD

**Issue by ianthetechie** [openstreetmap/iD#5299]
Pressing the command key by itself seems to deselect whatever I was working on. I cannot find any documentation of this in the key shortcuts, so I presume it's a bug. I have my keyboard layout switcher mapped to command+space, and frequently switch keyboard layouts when contributing to Korea.

Browser: Safari 11.1.2 (13605.3.8) on High Sierra.

**Comment by bhousel** [comment]
I just tried also with Safari 11.1.2 on MacOS High Sierra , and I can't reproduce the issue.  I'm not sure what to suggest to debug further, other than checking again what keyboard shortcuts you have setup.

**Comment by ianthetechie** [comment]
@bhousel Interesting... I typically work with an external keyboard (plugged into the USB port on the back of my USB-C monitor that acts as a dock for my 2016 Retina MBP). It does not happen with the internal keyboard, which makes me think the issue may lie with the keyboard. If it occurs with a different keyboard, then that'd confirm it's something with the way the keyboard is sending chords. I'll update later tonight when I get home to my other workspace.

**Comment by ianthetechie** [comment]
Sorry for the delay updating this issue. It appears to be a problem with one specific keyboard. My other (higher quality) one does not exhibit the same issue.
