### ISSUE TITLE
Location panel does not open

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#5306]
Pushing `CTRL + SHIFT + L`, does not open the location panel.
All of the other panels work fine.
No errors appear on the console.
This could be related to #5305 ?

Can anyone reproduce this?

**Comment by todrobbins** [comment]
`CMD + SHIFT + L` works for me on macOS/Chrome

**Comment by manfredbrandl** [comment]
`Strg Shift L` works for me (Windows 10, Google Chrome Version 69.0.3497.81 (Offizieller Build) (64-Bit)) in a german language setting.

**Comment by bhousel** [comment]
<kbd>cmd</kbd><kbd>shift</kbd><kbd>L</kbd> is also working for me on MacOS/Chrome..

@JamesKingdom you're on Linux right?  I'm not sure what might cause the issue..

You can try adding some debug code or console.log statements in [testBindings](https://github.com/openstreetmap/iD/blob/master/modules/lib/d3.keybinding.js#L20) to see whether iD is getting the event, or whether something in the OS is blocking it.

**Comment by JamesKingdom** [comment]
This was on Win10/Chrome, but it works on my laptop, so I guess it might be a bad extension or something. I'll have another look soon.

**Comment by JamesKingdom** [comment]
I figured it out, my Dymo label printer software was using the same shortcut... 
Thanks for the help!

**Comment by jidanni** [comment]
Another case users should note, simply doing
1. Click e.g., https://www.openstreetmap.org/edit#map=21/24.13193/120.69307
2. CTRL + SHIFT L

will not work.

One observes an intermediate step is required: one mus t be sure to click somewhere on the map before using CTRL + SHIFT L. Then everything will be OK.
