### ISSUE TITLE
Show just one single user's Mapillary images

### ISSUE THREAD

**Issue by koninklijke** [openstreetmap/iD#5307]
Mapillary has collected many millions of photos, but it can be hard to pick the ones one contirbutor took of a particular feature from amongst the many green markers shown. This is irrespective whether those would be my own, or pics from someone whom I know visited that area and took pics of that particular feature, and would be as opposed to the standard straight-ahead traffic-sign stuff which may show that there is, for example a regional walking network marker, but lacks the detail which direction to go in order to reach which particular other node. 
That filter is already available on the Mapillary site, this request is to implement it when overlaying Mapillary photos in iD editor, please.

**Comment by nickplesha** [comment]
Hi, you can try the username filter in this PR: https://github.com/openstreetmap/iD/pull/7847 let me know if you have any feedback or suggestions.

**Comment by quincylvania** [comment]
Done by @nickplesha in #7847, followup in #8076.

You can now filter photos to those by one or more specific users for all layers: Mapillary, OpenStreetCam, and even Bing Streetside if you somehow wanted to 😄
