### ISSUE TITLE
Names of and Destinations of motorway exits not showing up on GPS device 

### ISSUE THREAD

**Issue by dartmouvic** [openstreetmap/iD#5312]
Names of and Destinations of motorway exits not showing up on GPS device unless a name is put on the way or exit junction like what happen when the names where removed in this changeset https://www.openstreetmap.org/changeset/62471942

**Comment by bhousel** [comment]
See #5276 - This project is just about the OpenStreetMap iD editor.. We can't do anything for your GPS device.
