### ISSUE TITLE
IBGE layers not showing on the map anymore

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#5319]
The official data layers from the Brazilian government are not working anymore:
- IBGE mapa de setores rurais
- IBGE mapa de setores urbanos

When I select them I get a blank background.

**Comment by afmenez** [comment]
This seems to be similar to #5272, #5264 and #5250.  Maybe it's all the same issue?

**Comment by bhousel** [comment]
I fixed the IBGE token in https://github.com/osmlab/editor-layer-index/issues/555 and these layers will show up in the next release of iD.

**Comment by afmenez** [comment]
Thanks!
