### ISSUE TITLE
Use multilingual description and images from OSM Wikibase

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/iD#5321]
Now that Wikibase has been [installed on OSM](https://wiki.openstreetmap.org/wiki/OpenStreetMap:Wikibase), and community has began filling in the missing descriptions, it should be fairly simple to start using it.

Given a key, you can use AJAX to first resolve it to the item ID.  For example, to get all available data about the `bridge:movable` key, with the labels and descriptions in both French and English, use this API call.  Add `&format=json` to remove html formatting. See [MW API documentation](https://wiki.openstreetmap.org/w/api.php?action=help&modules=wbgetentities).
* https://wiki.openstreetmap.org/w/api.php?action=wbgetentities&sites=wiki&titles=Key:bridge:movable&languages=en|fr

**Import:** due to API limitations, use this pseudo code to create `titles` parameter:  `"Key:" + key.replace('_', ' ').trim()`. Otherwise it may not work in some corner cases. Make sure to check if P16 exists to get the correct form of the key.  Also note that this does not guarantee 1:1 in some rare cases, e.g. if someone used spaces instead of underscores, etc.

There should also be a link to the Item page, so that users can inspect and possibly edit the data if needed.

Fields that might be useful:
* description
* [Image (P4)](https://wiki.openstreetmap.org/wiki/Property:P4)
* The types of features the key should be [used on (P5)](https://wiki.openstreetmap.org/wiki/Property:P5)
* labels might at some point also become very useful - they would offer a very short localized replacement of the keys, e.g. "Name in English" instead of "name:en".

**Comment by bhousel** [comment]
Nice @nyurik - It will be interesting to see what I can do with these.. Is there a good way on the OSM wiki to browse the existing wikidata?

**Comment by nyurik** [comment]
@bhousel I updated the description above to include a much better api call.  I plan to include all of that data into Sophox to make it much easier to run complex queries.  See the announcement link in [my twitter post](https://twitter.com/nyuriks/status/1042158529241640961) for some examples, or the full [docs of this project](https://wiki.openstreetmap.org/wiki/OpenStreetMap:Wikibase).

You can also use the regular on-wiki tools, e.g. "all pages" special page to [view all pages](https://wiki.openstreetmap.org/wiki/Special:AllPages?from=Q2&to=&namespace=120) in the "Item" namespace, or use "what links here" link, but those are not very suitable for automated usage.

**Comment by bhousel** [comment]
Thanks @nyurik  - I think what I am actually looking for is more like what real wikipedia does, how there is a link in the "tools" menu that goes to a wikidata page:

<img width="500" alt="screenshot 2018-09-20 09 37 53" src="https://user-images.githubusercontent.com/38784/45859656-472d5300-bd31-11e8-95b3-7be09c519391.png">

<img width="500" alt="screenshot 2018-09-20 09 47 20" src="https://user-images.githubusercontent.com/38784/45859724-70e67a00-bd31-11e8-85ab-228db4ad6118.png">

**Comment by nyurik** [comment]
@bhousel I'm not sure I understand.   The OSM wiki also has that link -- e.g. on [Key:bridge:movable](https://wiki.openstreetmap.org/wiki/Key:bridge:movable) there is a link on the left called `OpenStreetMap Wiki item` - which is exactly the same one - takes you to [OSM's Q104](https://wiki.openstreetmap.org/wiki/Item:Q104).  (It sucks that we also have to use Q-numbers on OSM wiki - confuses a lot of people, but Wikibase people don't want to make it easy to customize).

Unlike the `wikidata` tag case, where you look up the data by using user-entered Qid number, here you will have some key string or some tag string, e.g. `building` and `building=yes`.  And you would need to get the structured data that describes those keys. And for that you would need to use the API I specified.  Or maybe  I do not understand how you plan to use this feature.

**Comment by bhousel** [comment]
done in #5647
