### ISSUE TITLE
Prevent user from creating object that are hidden from map

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#5324]
The "new" ability feature to hide objects from map is quite useful (hide buildings / area / boundaries…), specially when you focus on a single object-type mapping.

However, it would be great to prevent user from mapping hidden features.

It's even more insidious that, since this is stored in user local storage, this is persisted across mapping sessions. So one **may have forgot* that he had hidden some features (for instance buildings), and in a later session, tags them again (create buildings when he sees some). Since the building will stay on the map, you haven't any clue that most of them are actually hidden!

Is it possible to gray out from presets list the hidden features? Or something else? I wouldn't say it already happened to me... but unfortunately it has :(.

ps : and thanks @bhousel for your dedicated work on iD, congratulation for it!

**Comment by bhousel** [comment]
Thanks for the kind words!  This is #2711 - I agree we should prevent users from using presets that would be hidden.  I like your idea about greying them out..
