### ISSUE TITLE
Fix Pavilion preset

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#5325]
Related to #5292 

https://wiki.openstreetmap.org/wiki/Tag:building%3Dpavilion

I was wanting to tag a building with building=pavilion so searched "pavilion" in the search box. However the tags added were amenity=shelter, building=yes and shelter_type=pavilion. Not sure if this is completely incorrect (pavilion isn't mentioned on the shelter_type wiki page), but adding a "Pavilion Building" preset would be useful.

**Comment by bhousel** [comment]
Ok, I changed the preset from being an `amenity=shelter` to being a `building=pavilion`. 
I was only familiar with the US usage of the word, and didn't realize that Pavilions in the UK were more like sports halls.
