### ISSUE TITLE
Nursing Home automatically adds building=yes

### ISSUE THREAD

**Issue by shiftee** [openstreetmap/iD#5335]
The [wiki](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dnursing_home) isn't clear if it should be a building or building & campus.

[Social Facility](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dsocial_facility) does the same but its wiki states: 

> Draw an area for the campus of the facility, comprising buildings and outdoor areas

and

> If there are no outdoor areas, the tags are applied to the building.

I noticed this when marking a facility spread over multiple buildings.

Could it be solved by presets for "Nursing Home Grounds" and "Social Facility Grounds"?

**Comment by shiftee** [comment]
Whatever way you do it is fine by me.
I'm no expert in this matter and just thought i'd point it out.
I'll leave it up to you if you want to leave the issue open/closed.

Thanks

**Comment by bhousel** [comment]
Leaving as is for now.
