### ISSUE TITLE
consider supporting short_name tag

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5336]
in minimal version just displaying existing tags would be great

in extended version it would be great to also show short name box below name box, if name tag is existing and it is quite long (>15 characters? >20 characters?)

See https://taginfo.openstreetmap.org/keys/short_name and https://wiki.openstreetmap.org/wiki/Names for documentation of the tag

**Comment by bhousel** [comment]
I didn't realize there were so many name types, but maybe we could build a nice way to add more of these like this and #5314 without cluttering the interface too much.

**Comment by bhousel** [comment]
I guess this can be part of #1554
