### ISSUE TITLE
Add Multilevel Car Parking preset

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5338]
- Path: `amenity/parking/multi-storey`
- Name: Multilevel Car Parking
- Geometry: `area`
- Fields: some useful combo of the fields for Car Parking and Building
- Tags: `"amenity"="parking"`, `"parking"="multi-storey"`
- Add/remove tags: `"building"="parking"`, `"amenity"="parking"`, `"parking"="multi-storey"`
- Reference: `"key": "parking"`, `"value": "multi-storey"`
- Terms: `multistorey car park`, `parking garage`, `parkade`, `parking structure`, `parking ramp`, `parking deck`, `parking building`, `indoor parking`
- Icon: `maki-parking-garage`

**Comment by lakedistrictOSM** [comment]
The levels field might be useful on this one.
