### ISSUE TITLE
Add Carport preset

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5339]
- Path: `building/carport`
- Name: Carport
- Geometry: `area`
- Fields: height, capacity, 
- Tags: `"building"="carport"`
- Terms: `covered parking space`

**Comment by lakedistrictOSM** [comment]
Additional search terms: garage, car, porch

**Comment by lakedistrictOSM** [comment]
Some carports are on the sides of houses above a door and can double up as a sort of porch. Also adding extra words can help people who don't know the correct word for something find the preset.
