### ISSUE TITLE
Parking preset icon should be recognizable regardless of language

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#5341]
The Parking Lot preset has an icon that consists of the letter “P”, for “parking”: ![](https://raw.githubusercontent.com/mapbox/maki/master/icons/parking-15.svg?sanitize=true). This icon isn’t recognizable in all languages and countries. For example, in Latin America, the equivalent symbol is an “E” for the Spanish _estacionamiento_ or Portuguese _estacionamento_, while in Spain and Portugal it’s a “P”, per the Vienna Convention.

A more universally recognizable icon would be a car ![](https://raw.githubusercontent.com/mapbox/maki/master/icons/car-15.svg?sanitize=true), for consistency with the Bicycle Parking ![](https://raw.githubusercontent.com/mapbox/maki/master/icons/bicycle-15.svg?sanitize=true) and Motorcycle Parking <img src="https://raw.githubusercontent.com/openstreetmap/iD/master/svg/fontawesome/fas-motorcycle.svg?sanitize=true" width="15" alt=""> icons. However, ![](https://raw.githubusercontent.com/mapbox/maki/master/icons/parking-15.svg?sanitize=true) is very appropriate in many languages and countries, so perhaps there should be a way for translators to define a letter that works best in a specific Transifex locale.

This same icon is being added to the Parking Space preset in #5340.

**Comment by bhousel** [comment]
I changed the icon from a  ![](https://raw.githubusercontent.com/mapbox/maki/master/icons/parking-15.svg?sanitize=true) to a  ![](https://raw.githubusercontent.com/mapbox/maki/master/icons/car-15.svg?sanitize=true)
