### ISSUE TITLE
Rename "Baseball Diamond" preset to "Baseball Field"

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5345]
While the term "baseball diamond" is sometimes used to refer to the entire play area in baseball, it more precisely refers to just the area within the four bases (which form a diamond). The [recommended way to map baseball pitches](https://wiki.openstreetmap.org/wiki/Tag:sport=baseball#How_to_Map_Baseball_Fields) in OSM is to cover the entire field, not just the infield. The English name of the `leisure/pitch/baseball` preset should be changed to "Baseball Field" to better indicate what should be mapped.

`baseball diamond` should be added under `terms` so it will still be searchable.

**Comment by Spotts9** [comment]
Wouldn't mind taking this one on.  I've forked and started looking at it

**Comment by quincylvania** [comment]
@Spotts9 Go for it!
