### ISSUE TITLE
Add Softball Field preset

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5346]
A [softball field](https://duckduckgo.com/?q=softball+field&iax=images&ia=images) has different dimensions than a baseball field, and often has a dirt infield. Softball fields are common in the U.S., especially around schools and universities.

Note: there is currently a page for a [`baseball=softball`](https://wiki.openstreetmap.org/wiki/Tag:baseball%3Dsoftball) tag. This proposal does not appear to be widely accepted and has fewer uses than [`sport=softball`](https://taginfo.openstreetmap.org/tags/sport=softball), so I'm ignoring it for now.

- Path: `leisure/pitch/softball`
- Name: Softball Field
- Geometry: `point`, `area`
- Fields: `name`, `lit`, possibly others
- Tags: `"leisure"="pitch"`, `"sport"="softball"`
- Reference: `"key": "sport"`, `"value": "softball"`
- Terms: `softball diamond`
- Icon: `maki-baseball`

**Comment by s-Hale** [comment]
Added :)
