### ISSUE TITLE
Add Picnic Shelter preset

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5347]
`picnic_shelter` is one of the most common values of [`shelter_type`](https://wiki.openstreetmap.org/wiki/Key:shelter_type), with over 22,000 uses. Especially now that the pavilion preset has been corrected to its British meaning—see #5325—a Picnic Shelter preset would prove useful.

- Path: `amenity/shelter/picnic_shelter`
- Name: Picnic Shelter
- Geometry: `point`, `area`
- Fields:`name`, `shelter_type`, `building_area`, `lit`, `bin`
- Tags: `"amenity"="shelter"`, `"shelter_type"="picnic_shelter"`
- Reference: `"key": "shelter_type"`, `"value": "picnic_shelter"`
- Terms: `pavilion`
- Icon: `maki-shelter`

**Comment by nadyafebi** [comment]
Hi! I'd like to take on this issue 😄
