### ISSUE TITLE
Add Amphitheatre preset

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5349]
Suggested on https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtheatre

- Path: `amenity/theatre/type/amphi`
- Name: Amphitheatre
- Geometry: `point`, `area`
- Fields: `name`, `operator`, `address`, `lit`
- Tags: `"amenity"="theatre"`, `"theatre:type"="amphi"`
- Reference: `"key": "theatre:type"`, `"value": "amphi"`
- Terms: `open air`, `outdoor`, `greek`
- Icon: `maki-theatre`

**Comment by lakedistrictOSM** [comment]
Although an incorrect spelling/pronunciation, I'd suggest "ampi" as an additional search term.
