### ISSUE TITLE
Add Escalator/conveying preset

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#5350]
https://wiki.openstreetmap.org/wiki/Key:conveying
highway=steps + conveying=yes
highway=footway + conveying=yes

**Comment by quincylvania** [comment]
My implementation suggestions:

**Conveying Field**
- Path: `conveying`
- Name: Movement Direction
- Type: `typeCombo`
- Key: `conveying`
- Strings: `yes` (perhaps labeled "Any"), `forward`, `backward`, `reversible`

**Escalator Preset**
- Path: `highway/steps/conveying`
- Name: Escalator
- Geometry: `line`
- Fields: `incline_steps`, `conveying`, `access_simple`, `lit`, perhaps others from the [steps preset](https://github.com/openstreetmap/iD/blob/master/data/presets/presets/highway/steps.json)
- Tags: `"highway"="steps"`, `"conveying"="*"`
- Reference: `"key": "conveying"`
- Icon: I'd swear there's an icon of a person riding an escalator but I can't seem to find it.

**Moving Walkway Preset**
- Path: `footway/conveying`
- Name: Moving Walkway
- Geometry: `line`
- Fields: `conveying`, `access_simple`, `lit`, perhaps others from the [footway preset](https://github.com/openstreetmap/iD/blob/master/data/presets/presets/highway/footway.json)
- Tags: `"highway"="footway"`, `"conveying"="*"`
- Reference: `"key": "conveying"`
- Terms: `moving sidewalk`, `autowalk`, `skywalk`, `travolator`, `travelator`, `travellator`, `conveyor`
- Icon: Walking person

**Comment by mchlp** [comment]
I'd like to work on this.

**Comment by quincylvania** [comment]
@mchlp Go for it! I just updated my suggestions with the icon names you might want to use.
