### ISSUE TITLE
(ski) piste:difficulty presets don't make sense ...

### ISSUE THREAD

**Issue by yvecai** [openstreetmap/iD#5354]
... except for north-American downhill ski runs.
Color scheme for the rest of the world is different for downhill, and also for nordic skiing.
Is there a way to change the preset according to:
1) the chosen piste:type
2) the edited coordinates ?

**Comment by bhousel** [comment]
> ... except for north-American downhill ski runs.
> Color scheme for the rest of the world is different for downhill, and also for nordic skiing.
> Is there a way to change the preset according to:
> 
> 1. the chosen piste:type
> 2. the edited coordinates ?

We can't change the text based on where the person is mapping, but I assumed people in other parts of the world would just translate the strings differently on Transifex.

**Comment by bhousel** [comment]
Closing for now.. Translate differently on Transifex if it is confusing outside of en-US 👍

**Comment by yvecai** [comment]
There is two things here:
* Black Diamond makes no sense in Europe
I get it, I'll check the french version on Transifex. 

* Downhill difficulties makes no sense for sled or cross-country
I'm about to make a PR to add some pressets for cross-country skiing, should I go along with skitour and all others documented piste:type or is there a usage limit ?
