### ISSUE TITLE
Adding leisure=sports_centre preset to a building removes building tag

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5366]
As it currently is, if the leisure=sports_centre preset is added to a building it removes the building tag from the area. I noticed that in issue #4682 that the building tag was removed from being part of the preset, but the building tag shouldn't also be removed from areas that already contain it when the preset is added to them. As sports centers can be in buildings.

**Comment by bhousel** [comment]
Yes, that's ok.. #4682 removes it because sports centers probably aren't buildings.  But there is still a building field in the sidebar, so that the user can put it back if they want to.

**Comment by Adamant36** [comment]
"sports centers probably aren't buildings"

Is the building tag removed by default if it is already there because of the assumption that the sports centers tagged as buildings are miss tagged or something? As it currently stands, 61,044 sports centers out of 169,427 have the building tag. Which is roughly 36 percent, or 1 out of 3. That's not enough for the building tag to not get removed by default if its already there huh? I can understand a tag not being part of the preset when its added, but having a preset remove preexisting tags seems like influencing tagging practices. Plus, it might cause people to not notice the building tag has been striped and then to save their work without it. Since it was already there originally and there's no logical reason it should be removed by adding another tag.

**Comment by Adamant36** [comment]
OK. It makes more sense now. Thanks for the extra explanation.
