### ISSUE TITLE
Add fields to amenity=bench preset

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5367]
As it is, the only field that the bench preset has is for backrests. It would be cool if it also had fields for the material, seats, and colour tags. Since they are all used on benches a lot. Especially material.

**Comment by manfredbrandl** [comment]
I support this, because taginfo tells me that usage of fields for material, seats and colour is high (nearly 400K to above 100k) of total over 950K benches.

**Comment by dryo** [comment]
Good idea! I'd also like this for leisure=picnic_table, especially if it has a roof or not (covered = yes/no)

**Comment by Adamant36** [comment]
@dryo, good call. I was actually thinking the same thing for picnic tables also. You should do a new issue for it.
