### ISSUE TITLE
Mapillary sign overlay not showing up

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#5374]
Judging by the lack of issues on here, I am the only one that can't bring up Mapillary traffic sign overlay?
The mapillary image cone overlay plugin works. 
Tried Chrome 60 and Edge

**Comment by bhousel** [comment]
@cbeddow fixed this with #5395, but there is a follow-on issue to fix.
The signs layer is working again, but the detections overlaid on each image are not working yet.
