### ISSUE TITLE
Add major/minor building type preset to building=yes

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5375]
As it is there is no way to select what type of building it is being mapped with the building=yes preset. Currently 256,607,511 buildings are just tagged with building=yes and are missing a building type tag. Although there are some options for major building types, in a lot of areas they are not being used. As there are many houses I have came across that are not tagged as building=residential. So having a building type in the main tag might help sway people to add the proper tags. Having a building type preset is even more important though for minor buildings like garages, which do not have their own building selection option on the main drop down list. 

If a preset for something like that doesn't work for some reason, more building types should be added to the main building drop down list, especially garages. As there is almost a million more of them then apartments, which has its own drop down category. Huts and sheds are pretty high up there also.

**Comment by bhousel** [comment]
> As it is there is no way to select what type of building it is being mapped with the building=yes preset.

I'm confused by this - wouldn't users just change the "yes" to something else?

<img width="300" alt="screenshot 2018-10-06 22 45 59" src="https://user-images.githubusercontent.com/38784/46577673-f9178100-c9b9-11e8-92d4-56ea1d7de2c2.png">

&nbsp;

> Having a building type preset is even more important though for minor buildings like garages, which do not have their own building selection option on the main drop down list.

I'm confused by this too - we have presets for Garages and Garage:

<img width="300" alt="screenshot 2018-10-06 22 47 08" src="https://user-images.githubusercontent.com/38784/46577668-e43aed80-c9b9-11e8-8ff1-a730689a2c00.png">

Can you share a screen shot of which dropdown you are expecting these items to appear?

**Comment by Adamant36** [comment]
On the first question, I'm wondering if people don't know that its a drop down menu because it doesn't say "type" and it already has "yes" filled in as an option instead of being blank. Unlike other similar type selectors. If you delete "yes" from the box it shows possible options in grey like "yes, house, residential." Insinuating it can be clicked on to select those options. I think that would be better as the default then how it currently is, where the type is pre-filled in for the person. Personally, I didn't even know that it was a drop down menu with more options until now. I thought it was just selecting "yes" for me and that was it. It could just be me though.   

Second, as you show, garage is selectable as an option if you specifically type the word "garage" in the search box. I'm saying it should be part of the main "building features" drop down menu without having to search for it first. Since its the third most popular building type. Maybe between apartments and retail or above apartments.

Hopefully that's clearer

**Comment by bhousel** [comment]
> On the first question, I'm wondering if people don't know that its a drop down menu because it doesn't say "type" and it already has "yes" filled in as an option instead of being blank.

Sure, I think people know about the dropdowns.

> Second, as you show, garage is selectable as an option if you specifically type the word "garage" in the search box. I'm saying it should be part of the main "building features" drop down menu without having to search for it first.

Ok, I just added it to the "Building Features" category list

**Comment by Adamant36** [comment]
@bhousel, thanks. That will do fine.
