### ISSUE TITLE
senseless proposals for postal_code

### ISSUE THREAD

**Issue by donovaly** [openstreetmap/iD#5377]
When I want to add or edit values in the field postal_code iD pops up with senseless proposals. This is not only annoying but also error prone because from time to time one clicks outside the filed and gets one of the proposals.

There should not be proposals because codes are different for every country so they are not helpful at all.

**Comment by bhousel** [comment]
AFAIK the postal codes that are suggested are the ones that are already tagged in the vicinity where you are editing.. can you share an example and screenshot where you see a bad postal code suggestion?

**Comment by donovaly** [comment]
> the postal codes that are suggested are the ones that are already tagged in the vicinity

No. I edited a lot of postal codes in Switzerland and there all codes have 4 ciphers. Nevertheless I get always the same proposals: 71019..., see this screenshot:

![grafik](https://user-images.githubusercontent.com/1828501/46584887-456dca00-ca69-11e8-97ca-fd1976b7c604.png)

**Comment by bhousel** [comment]
> No. I edited a lot of postal codes in Switzerland and there all codes have 4 ciphers. Nevertheless I get always the same proposals: 71019..., see this screenshot:

Oh I see - yes in the raw tag editor you just get whatever is stored in OSM.   iD doesn't have any special logic for those  (What I said above only applies to the address field)

However I don't know why you're seeing those results.  When I try it on Chrome 68.0.3440.106, I get this:

<img width="300" alt="screenshot 2018-10-07 14 07 55" src="https://user-images.githubusercontent.com/38784/46585068-d4fb8480-ca39-11e8-91e8-9331c0ac233d.png">

**Comment by donovaly** [comment]
Also in your case the proposal "5034" and "185034" is not helpful and even senseless (e.g. that the amount of ciphers differ makes no sense in general). They don't help at all. So either the proposal is a code from the vicinity or better no proposal is made.

**Comment by bhousel** [comment]
Ok I added a thing so taginfo won't lookup `postal_code` values anymore
done in 159622f57
