### ISSUE TITLE
Save and Cancel buttons disappeared

### ISSUE THREAD

**Issue by makednos** [openstreetmap/iD#5378]
Hi, I can't upload my changes because the 'save' and 'cancel' buttons are missing. I did some work on the map, so I don't want to clear the changes. 
What can I do to save/upload my recent changes while save button is missing?  
![screenshot_2018-10-07 openstreetmap](https://user-images.githubusercontent.com/43931305/46582816-89ef6a80-ca55-11e8-86e3-8cf8b8c84bf8.png)

iD 2.11.1
Mozilla Firefox 61.0.2 64-bit

**Comment by quincylvania** [comment]
@makednos I was unable to reproduce the issue on Firefox 62.0.3 on macOS. Here are some troubleshooting tips:

- Try updating Firefox to the latest version. I _think_ your OSM edits will be saved.
- Try disabling any browser add-ons that could interfere with iD.
- This looks like it could be a JavaScript error. Try [opening the Web Console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) and reporting any errors. here.

**Comment by bhousel** [comment]
ah yeah, this is #4108
