### ISSUE TITLE
Allow opt-out of underscoring behavior for typeCombo fields

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5379]
Currently, `typeCombo` fields replace all spaces with underscores when the user inputs values. This is useful for most keys, but some keys need to allow spaces. Examples of this are keys under the [`generator:output`](https://wiki.openstreetmap.org/wiki/Key:generator:output) namespace, as well as other tags with units.

**Comment by bhousel** [comment]
Oh!  We have this but it's undocumented..  If you set `"snake_case": false`, iD will not add underscores.

Can you add this property to the `presets/README.md`?
