### ISSUE TITLE
Make disconnecting areas from streets easier

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5385]
AFAIK there are two mapping styles when it comes to streets next to areas. Eg fields or commercial districts. 
a. Use the area to mark the sidewalk kurb, thereby giving shape to the road.
b. Connect the area to the street. And thereby allowing the renderer to cleanly draw a street over the area.

Apparently there is no consensus on how to map those situations.

Whenever I experience case B, it is very painful to change the mapping, eg. move the area, make it smaller or bigger.

The main issue is, that I need to disconnect the area-nodes, which are a lot of then. But the disconnect-feature does not really work well if there are multiple elements – eg a road (node 1), a second road (node 2), two areas (node 3+4); so I have 4 nodes above another.

*Example:*  
<img width="449" alt="bildschirmfoto 2018-10-08 um 15 12 14" src="https://user-images.githubusercontent.com/111561/46610962-98e52400-cb0c-11e8-86e1-b6b8371bc93c.png">

**What would be an easier way to solve this situations?**

_Update:_ It might also be, that my problem is - in part - because the area is part of a relation? There seems to be no way to disconnect this node …
([Source](https://www.openstreetmap.org/edit#map=19/50.81760/6.37607))
<img width="351" alt="bildschirmfoto 2018-10-08 um 15 35 52" src="https://user-images.githubusercontent.com/111561/46612142-ffb80c80-cb0f-11e8-883e-13f1eb8495fe.png">

**Comment by quincylvania** [comment]
> Update: It might also be, that my problem is - in part - because the area is part of a relation? There seems to be no way to disconnect this node …

Hi @tordans in this specific case, you can disconnect the node this way:

1. Select the area
2. Shift + right-click on the node
3. Select the disconnect option

**Comment by bhousel** [comment]
> Also: Is this issue the same that is discussed at #4245, but from the other point of view (areas, not ways)?

I think it's the same issue..
