### ISSUE TITLE
[Request] New feature type: Game/toy library

### ISSUE THREAD

**Issue by ChameleonScales** [openstreetmap/iD#5390]
Game and toy libraries don't really fit in any category. They're usually a mix between a social & cultural organization, a child care facility and a leisure facility, so I think it would be best to just give them their own feature type.
Would that be possible ?

**Comment by quincylvania** [comment]
@ChameleonScales I'm not aware of a common tag for game libraries. I'd recommend posting to the [tagging mailing list](https://lists.openstreetmap.org/listinfo/tagging) so the community can discuss what tag to use for this feature. If the tag gets support, then we can consider adding an iD preset for it.

**Comment by ChameleonScales** [comment]
Apparently Paul Allen added amenity=toy library

**Comment by ChameleonScales** [comment]
Thanks @quincylvania. After some discussing in the mailing list, I added this proposal in the wiki:
https://wiki.openstreetmap.org/wiki/Proposed_features/toy_library

**Comment by bhousel** [comment]
I didn't see any serious opposition to the idea, so I just added it.

**Comment by ChameleonScales** [comment]
Thanks !
Any idea when the release will be out?

**Comment by bhousel** [comment]
> Any idea when the release will be out?

Soon!

**Comment by ChameleonScales** [comment]
Yay! Thank you!
So, about the tags I proposed in the wiki page: https://wiki.openstreetmap.org/wiki/Proposed_features/toy_library

any chance some could also be added?
Do we have to discuss it further in the mailing list?

**Comment by quincylvania** [comment]
@ChameleonScales Possibly. We try not to promote new, low-usage tags without a very good reason. I'd suggest mapping as many toy libraries as you can to see how those tags work in practice, and/or going through a formal vote. It's easier to support a tag with even a few dozen uses than zero uses.

**Comment by ChameleonScales** [comment]
Thanks. I'll try again to reach some organization to discuss the details.
Right now there are 128 entities with this tag worldwide, but none of them are displayed on the map (you can find them with a search but you won't see the icon and/or name directly on the map like you would for a toy store). Is it normal ?

**Comment by quincylvania** [comment]
> Right now there are 128 entities with this tag worldwide, but none of them are displayed on the map (you can find them with a search but you won't see the icon and/or name directly on the map like you would for a toy store). Is it normal ?

@ChameleonScales Each map based on OSM data has its own rules for what tags to display, so new tags won't necessarily appear by default. You can request rendering for tags on the default openstreetmap.org map tiles over at https://github.com/gravitystorm/openstreetmap-carto.

**Comment by ChameleonScales** [comment]
Thanks, I requested it there:
https://github.com/gravitystorm/openstreetmap-carto/issues/3803
