### ISSUE TITLE
Set "source:height" with the height

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5393]
There is a `source:height=*` attribute, see https://wiki.openstreetmap.org/wiki/Key:height#Sources

It would be nice to have this set automatically whenever I choose "set height" via the height-measurement-tool.

Maybe something like

> source:height=Go Map!! in-app measurement feature

**Comment by tordans** [comment]
Sorry, wrong repository =(

**Comment by bhousel** [comment]
Did you mean to open this elsewhere? iD doesn’t have a height measurement tool 🤔
