### ISSUE TITLE
Adding a new point on a way should add a vertex, not a standalone point

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/iD#5409]
I'm not sure if the search index is automatically populated from existing data or if there's a hardcoded list somewhere, so feel free to close this if it makes no sense. However I recently, when demo'ing iD, wanted to add a gate, entered "gate" in the search field, and all it came up with was an airport gate. I had to enter "barrier" which is a bit un-intuitive to those without OSM exposure, and then I could select "gate" in the drop down. Could "gate" be added to the first-class search index?

**Comment by bhousel** [comment]
Oh I see what's happening - we have several kinds of gate presets, but they all work only on "vertex" geometry.  So users are only offered them as a choice if they select a node that belongs to a way. 

I wonder whether we can make this more intuitive, or at least mention it in the walkthrough.

<img width="629" alt="screenshot 2018-10-17 09 31 30" src="https://user-images.githubusercontent.com/38784/47089741-74b1d300-d1ef-11e8-9196-209042a403ca.png">

**Comment by bhousel** [comment]
> What I had done, is select "point" and then hover over a way to get it highlighted and plop a point _onto_ the way, somehow thinking that would make the point a vertex in the way, but now I see that's not the case (and the "map marker" icon should have given it away)

Ah yeah that makes sense...  But what you did makes sense, and really iD should do this (i.e. dropping a new point onto an existing way should put a vertex there, not add a standalone point).
