### ISSUE TITLE
Allow the search panel to be hidden

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5411]
Can we please have a way to simply click an X to have that search panel slide off to the left?
It is taking up 1/3 of the screen and as you see sometimes when one is trying to compare backgrounds there is only 1/3 left of the map to look at.

Sure it is important, so slide it back whenever you like, but just give us a way to temporarily have it go away.
![0](https://user-images.githubusercontent.com/1230959/47152359-11b75d80-d30f-11e8-8f6b-840497431266.jpg)

**Comment by JamesKingdom** [comment]
I think this is a good idea 👍

**Comment by Adamant36** [comment]
I was thinking either that or a way to smart resize it by clicking on the side and dragging it left. As it is, it takes up a lot of room. Especially if its empty.

**Comment by jidanni** [comment]
Here I needed to see more streets to see which aerial choice lined up best.
Yes the panel could slide back the moment I started editing something, but not yet please.

**Comment by bhousel** [comment]
yep that's #3447
