### ISSUE TITLE
Add maxspeed field to the Speed camera preset

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#5417]
Please, consider adding the a maxspeed field to the Speed camera preset.

Thanks!

**Comment by FrikanRw** [comment]
@JamesKingdom Can I help with this issue?

**Comment by JamesKingdom** [comment]
@FrikanRw Sure, go for it! 👍

**Comment by FrikanRw** [comment]
wip

**Comment by JamesKingdom** [comment]
This was done in #5421
