### ISSUE TITLE
Style unpaved Taxiway similarly to unpaved highways

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5419]
Some rural airports have unpaved taxiways. Their styling should indicate this.

Example: https://www.openstreetmap.org/edit#map=18/43.34154/-114.79322

<img width="1280" alt="screen shot 2018-10-19 at 4 25 19 pm" src="https://user-images.githubusercontent.com/2046746/47247972-e179c880-d3bb-11e8-963c-7cc028b4af95.png">

Note: unpaved runways could also benefit from similar styling, but that change would be more complicated and is not part of this issue.

**Comment by thefifthisa** [comment]
I'd like to work on this! To clarify, unpaved highways have a dashed outline instead of a solid one?

**Comment by quincylvania** [comment]
Yep! Generally, each line is made up of three layers. The `stroke`, the `casing`, and the `shadow`. The shadow is the pulsing red selection indicator, and the other two are based on the tags. You'll want to figure out how to apply the `unpaved` CSS to the `casing` of lines with `aeroway=taxiway`.
