### ISSUE TITLE
Localization of 'Custom Map Data' not working

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#5427]
Hi,

The Custom Map Data menu option and popup aren't applying the localized strings.

Transifex shows that the strings where translated to Spanish 2 months ago.

See attached screenshots in "Spanish":

![image](https://user-images.githubusercontent.com/13091755/47430185-0fba2800-d76f-11e8-80fe-96b03c3b1d7b.png)

![image](https://user-images.githubusercontent.com/13091755/47430210-22ccf800-d76f-11e8-9613-53de99513795.png)

**Comment by manfredbrandl** [comment]
The localisation are updated with every new iD-release for the osm-website and several times a day on the iD-preview at http://preview.ideditor.com/master . In German everything is localized at the preview:
![image](https://user-images.githubusercontent.com/5360273/47434035-fb435300-d7a1-11e8-96b0-34dfd57e073c.png)

**Comment by ignaciolep** [comment]
Oh! Thanks!
