### ISSUE TITLE
Add "query feature" to ID

### ISSUE THREAD

**Issue by wysiwia** [openstreetmap/iD#5428]
Sometime when editing it’s necessary to select an item which is completely hidden by other items. Currently I haven’t found a save way to get the lower item except for malicious mapping of upper item and fix this later.

IMO there should be an easier way. How about to introduce a “query feature” as is on OSM base page to get a list of items of a small area. Then any of the items can be selected.

Best solution would be the “query feature” in the context menu (right mouse button).

**Comment by bhousel** [comment]
Yep that's https://github.com/openstreetmap/iD/issues/2225#issuecomment-282736947
