### ISSUE TITLE
power substation vs sub_station confusion

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#5430]
There is no way to find the correct tag from iD itself when you view an "old" element. It would be nice if we could add "(deprecated)" or something like that behind the short "title".

There is an extra level of confusion at least in the german version of iD.
I look at an "old" element with `sub_station`, but gets in the title the [text of the new tag](https://wiki.openstreetmap.org/wiki/DE:Tag:power%3Dsubstation) `substation` and a link to the new `substation` wiki (see footer of the screenshot).
![image](https://user-images.githubusercontent.com/2410353/47526273-940bc880-d89f-11e8-8d01-573fac0ce33e.png)

**Comment by bhousel** [comment]
Yeah that's kind of #4591 which we decided not to do.
We don't expect iD users to understand tags or even to know that they're a thing, so the idea of telling somebody that a tag is "deprecated" and ask them to correct it is kind of a nonstarter.

**Comment by HolgerJeromin** [comment]
Ok, fine. 
But what about the wrong link to the wiki? Is it intentional to "lie" to the mapper?
