### ISSUE TITLE
Scale bar breaks when using browser a11y settings to zoom

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5437]
Scale bar missing in https://github.com/GNOME/epiphany browser.
https://github.com/openstreetmap/iD/issues/5435
Visible in chromium, missing in epiphany.
https://en.wikipedia.org/wiki/GNOME_Web
https://wiki.gnome.org/Apps/Web

**Comment by mmd-osm** [comment]
Cannot reproduce, scale bar is visible in epiphany here. Seems like some other issue on your machine.

**Comment by bhousel** [comment]
iD does have a scale bar. It does go away if your window really is too small.

I've included a screen shot, but you can also search the issue list for "scale bar" to find probably a dozen more screenshots and descriptions of this feature.

<img width="633" alt="screenshot 2018-10-26 14 13 29" src="https://user-images.githubusercontent.com/38784/47584796-94e93c80-d929-11e8-86c9-7250079ea9dd.png">

**Comment by jidanni** [comment]
**Ah ha**

Observe, at CTRL+0 zoom, scale bar present.
![d1](https://user-images.githubusercontent.com/1230959/47614927-c35e4780-dae2-11e8-85bf-b91940ba920c.jpg)


Now at CTRL++ zoom,
![d2](https://user-images.githubusercontent.com/1230959/47614937-d96c0800-dae2-11e8-829f-a2c95c026cb6.jpg)


1. Grey area where scale bar lives **taller**
1. "Help translate button" and "2.111" **larger**
1. **Plenty** of room left for scale bar, but...

**Poof** scale bar gone!

Please only make it go away when it finally bangs into something.

**Comment by jidanni** [comment]
> Wow you must be on a tiny screen - what is the resolution?
@tastrax Default resolution for IBM Thinkpad 50e, 1024x768 I recall...

**Comment by jidanni** [comment]
Now testing with Chromium at 1152x864. Scale bar remains until CTRL++++
zomm (150%) whereupon it disappears. But there is still plenty of room
for it:
![0](https://user-images.githubusercontent.com/1230959/47638678-2eb72080-db9a-11e8-8ea5-4dffc2694f9c.jpg)

**Comment by tastrax** [comment]
Why not just use the + key to zoom in? Why do you need everything magnified?

**Comment by jidanni** [comment]
> Why not just use the + key to zoom in? Why do you need everything magnified?

Usually because the fonts are too small, etc. (age 57).

**Comment by bhousel** [comment]
I’ll look into it , but your browser may be trying to zoom the scale bar itself like any other graphic element .  A zoomed-in scale bar will obviously be wrong and lie to you.

**Comment by slhh** [comment]
The scale bar does also disappear in Edge and Firefox. It doesn't seem to become lying as long as it is visible.
