### ISSUE TITLE
Multiline text fields for long tag values

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5444]
Spun off of https://github.com/openstreetmap/iD/issues/3447#issuecomment-249158986.

![f6d68ba4-8189-11e6-8a71-50402a99754b](https://user-images.githubusercontent.com/2046746/47610691-84f85800-da10-11e8-8d0c-b4f6f0c66048.png)

Currently, value text fields in the the raw tag editor are never taller than one line even if the text is very long. While #5443 will alleviate this issue by allowing the user to resize the sidebar and see more text, it would still be useful to allow the text to wrap onto multiple lines if needed.

**Comment by thefifthisa** [comment]
I'd like to work on this!

**Comment by quincylvania** [comment]
@thefifthisa Go for it!

I tried working on this and it appeared to be somewhat more difficult than it looks, but maybe you can find a better solution!

**Comment by thefifthisa** [comment]
@quincylvania Oh okay! Can I ask what approach you tried?

The comment mentioned that checking how long individual tag values are could get tedious, so I was thinking of having a set number of lines which the text can wrap onto before truncating with an ellipsis. What do you think?

**Comment by quincylvania** [comment]
That should be fine! The complicated part is that the existing implementation uses `<input type="text">` which really only works for a single line. For multiline text entry, a `<textfield>` is needed, but that may not work with the combobox control.

**Comment by quincylvania** [comment]
We may not need this anymore since we have the text raw tag editor in #6302.

**Comment by bhousel** [comment]
> We may not need this anymore since we have the text raw tag editor in #6302.

Good point, we can close it..
