### ISSUE TITLE
spelling mistake on french OSM /page editing / shortcut f

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [openstreetmap/iD#5448]
Spelling mistake here:

 https://www.openstreetmap.org/edit#map=16/50.0287/5.3807
shortcut "f" or "Données cartographiques" in french,

it is written "Sucouche photo (Bing Streetside)"
--> it should be "Surcouche..." with a R

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/openstreetmap/id-editor/dashboard/), so you should sign up for an account there to fix issues with the translations.
