### ISSUE TITLE
Implement new tagging scheme for fire hydrants

### ISSUE THREAD

**Issue by momu** [openstreetmap/iD#5452]
There was a [successful proposal for improving the hydrants tagging][0]. [According to the wiki][1] there are some changes regarding `emergency=fire_hydrant`. E.g. `fire_hydrant:type=pond` is deprecated, `fire_hydrant:type=pipe` is new.

Can someone add it?

[0]: https://wiki.openstreetmap.org/wiki/Proposed_features/Fire_Hydrant_Extensions_(part_2)
[1]: https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant

**Comment by momu** [comment]
I just started working on it: 

https://github.com/momu/iD/tree/fire-hydrants

If anybody is faster feel free to join.

**Comment by bhousel** [comment]
This happened
