### ISSUE TITLE
consider clearing branches in main repo

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5465]
iD has 59 branches - https://github.com/openstreetmap/iD/branches

It seems that many of them are stale and may be safely deleted.

It is not a significant problem but it leads to some overly long lists (both in Github and command line interfaces), minor annoyances with autocompletion etc.

Overall, it is not worth spending much time on it but deleting obviously useless branches would be nice.

**Comment by bhousel** [comment]
Sure - I just deleted a bunch of them, but I left the ones that were associated with PRs or that I want to refer back to.  It's ok for there to be a lot of branches.
