### ISSUE TITLE
Lost touchscreen capability in the map

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#5466]
Sudenly I lost the ability to navigate the map (moving) along the image with my touch screen in an HP computer. The sytem is working in the areas of menu, etc; but Not in the map images in ID. Any Idea?

**Comment by bhousel** [comment]
> Sudenly I lost the ability to navigate the map (moving) along the image with my touch screen in an HP computer. The sytem is working in the areas of menu, etc; but Not in the map images in ID. Any Idea?

I can't think of anything that would cause this.. Which browser and OS are you using?

**Comment by jjiglesiasg** [comment]
Hi Bryan

Windows 10 Home Version 1803
Google Chrome V 70.0.03538.77 (64 bit)

**Comment by jleedev** [comment]
I can also reproduce this on a touchscreen notebook (Chrome OS). Tapping the map results in the delay + grey flash that indicates Chrome is synthesizing them into mouse events.

However, touch works properly in https://preview.ideditor.com/master/

**Comment by quincylvania** [comment]
A lot has been changing with touchscreen input as we implement #5505. I don't have a way to test the issue with this platform but I'm closing it as stale. Let us know if it still happens on our development preview site: https://ideditor.netlify.com/

**Comment by jleedev** [comment]
As of late touch has been working in iD stable on Chrome OS.
