### ISSUE TITLE
Add preset for leisure=fishing

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5469]
I'm kind of surprised we don't have a preset for a "Fishing Spot" yet 🎣 
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfishing

**Comment by quincylvania** [comment]
Recommendations
- Name: Fishing Spot
- Geometry: `point`, `area`
- Fields: `name`, `access_simple`, …
- Terms: `angler`, …



@bhousel You beat me to it!

**Comment by bhousel** [comment]
> @bhousel You beat me to it!

Yeah I added this issue reel quick

**Comment by iandees** [comment]
omg.

>

**Comment by xmile1** [comment]
> I'm kind of surprised we don't have a preset for a "Fishing Spot" yet 🎣
> https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfishing

Hi, I can take this up, Its similar to [this](https://github.com/openstreetmap/iD/pull/4432/files) before I believe that i did before i believe.

**Comment by bhousel** [comment]
sounds good @xmile1 !    you can copy an existing file like `data/presets/presets/leisure/bird_hide.json` -> `data/presets/presets/leisure/fishing.json` and change the contents.
