### ISSUE TITLE
Save and undo buttons do not appear

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#5470]
I just checked out iD's current master and realised that the save and the undo/redo buttons were missing. Am I doing something wrong?

![no save button](https://user-images.githubusercontent.com/31667811/48082919-15465200-e1f4-11e8-8d5d-475e2d3d2d66.gif)

**Comment by bhousel** [comment]
Lots has moved in #5455, so this is probably fixed.. Just so I can be sure, which browser and OS are you testing on?

**Comment by hikemaniac** [comment]
Sorry, I should have mentioned that earlier. I'm using **Firefox 63.0** and **macOS 10.13.6**.

**Comment by bhousel** [comment]
Cool thanks @hikemaniac -  I'm pretty sure these rules were pushing some of the bar elements off the screen only for Firefox.    

https://github.com/openstreetmap/iD/blob/cf02ee6dd578cb02f7effa3652084c95972a8cc6/css/80_app.css#L60-L63

The new toolbar is more responsive and that old hack is not needed anymore, so I've removed it in bd98b87d4
