### ISSUE TITLE
Relation role dropdown carat is hidden beneath trash icon

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5473]
The role fields in the raw_membership_editor and raw_member_editor are actually dropdowns, but it's hard to tell because the trash button hides the carat.  

bad:
<img width="300" alt="screenshot 2018-11-08 09 32 06" src="https://user-images.githubusercontent.com/38784/48205166-bbe83b00-e339-11e8-9193-f7117b3718df.png">

We should move the carats over to be more like the raw_tag_editor.  I think the solution here is to wrap the `input` and carat in a div flex container.

ok:
<img width="300" alt="screenshot 2018-11-08 09 37 56" src="https://user-images.githubusercontent.com/38784/48205315-023d9a00-e33a-11e8-8a53-9d9b6514ab93.png">

@quincylvania - I think this is like #5467, can you do it?

**Comment by bhousel** [comment]
We should probably just always show the trash icon to keep them all the same width. It could be grey/disabled for undownloaded ways?

**Comment by quincylvania** [comment]
> @quincylvania - I think this is like #5467, can you do it?

Sure thing!
