### ISSUE TITLE
Autofill "operator:wikidata" using the Operator field

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#5484]
Currently, when typing in an operator for an object in iD, all I can enter is plain text.  Could a wikidata search be used to find the operator that the contributor is looking for and suggest it to them? 
For example, in the image below, I am editing a bus stop and trying to add the operator.  Instead of just including the text "Chapel Hill Transit", iD could autofill a tag, "operator:wikidata"="Q5073024".
![image](https://user-images.githubusercontent.com/37753777/48325262-bec98100-e602-11e8-9c22-16e21d6e3d79.png)
I think that something like this could be very useful if implemented.

Also, for anyone super interested in the image, it is of [this location](https://www.openstreetmap.org/edit#map=19/35.90602/-79.04464).

**Comment by Nakaner** [comment]
Automatically adding `operator:wikidata=*` is an automated edit which has to be discussed on the Talk mailing list and documented according to the [Automated Edits Code of Conduct](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct).

There are local communities in OSM which don't have a consensus (i.e. don't agree with) on the automatic addion of `*:wikidata=*`. Please respect their decision.

**Comment by bhousel** [comment]
> Automatically adding `operator:wikidata=*` is an automated edit which has to be discussed on the Talk mailing list and documented according to the [Automated Edits Code of Conduct](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct).

@Nakaner - This is simply not true, and I'd appreciate it if you stop spreading such a nonsense view on what "Automated Edits" means.  iD already will add wikidata tags automatically in some cases, and we will continue to automatically set tags for users where it makes sense.  This is no different than other kinds of automatic tag assignment that all editor software must do sometimes.

**Comment by BjornRasmussen** [comment]
I doubt that Wikidata has good enough coverage for this to work, and people might think that their operator value they entered is not valid if it didn't show up in the autofill dropdown, so I'll close this issue for now

**Comment by bhousel** [comment]
> I doubt that Wikidata has good enough coverage for this to work, and people might think that their operator value they entered is not valid if it didn't show up in the autofill dropdown, so I'll close this issue for now

Oh! don't close it yet... I was thinking of expanding [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) to do `operator:wikidata` too.  Random musings [here](https://github.com/osmlab/name-suggestion-index/issues/2243#issuecomment-451356517).  It already does such a good job with `brand:wikidata`.

The idea would be that instead of just expecting contributors to know all the `operator` `operator:wikidata` `operator:wikipedia` tags, they could pick them from a list, and get logos and stuff for assistance.

**Comment by 1ec5** [comment]
https://github.com/osmlab/name-suggestion-index/issues/2243#issuecomment-451356517 seems to be focused on `operator`s of public transportation networks. But `operator` can be used on just about anything. If the intention is to autofill `operator:wikidata` on anything where `operator` can appear, then it would be simpler and more effective to draw the autocompletion suggestions directly from Wikidata (or from the Wikidata Query Service) than to go through name-suggestion-index. After all, it would be quite unmanageable for name-suggestion-index to index all the school districts (for operators of schools), all the parks districts and cities (for operators of parks), all the healthcare companies (for operators of hospitals), etc.
