### ISSUE TITLE
Selected preset icons changing incorrectly

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5493]
Came across an issue where switching between presets doesn't change the feature's icon correctly - in fact it takes part of the old icon's style.

The issue seems to only happen in Firefox (Windows10) -  can't remember it occurring with Chrome and in testing doesn't seem to happen in Chrome.

It doesn't occur all the time - but I managed to recreate it by drawing a line, selecting the wall preset, then clicking back onto a primary road, which gives the following:

![screenshot_2018-11-16 openstreetmap](https://user-images.githubusercontent.com/16965772/48651140-62df6d80-e9f1-11e8-8135-b45afadf986a.png)
Did some more editing with walls, clicked onto the primary road again then onto a town outline:
![screenshot_2018-11-16 openstreetmap2](https://user-images.githubusercontent.com/16965772/48651244-daad9800-e9f1-11e8-8dbf-01515f5c390d.png)

**Comment by quincylvania** [comment]
@boothym Have you seen this lately? We've changed this code somewhat so it's possible it fixed itself.

**Comment by boothym** [comment]
@quincylvania no I don't remember seeing it recently, in both FF and Chrome, so assume it's been fixed, thanks.
