### ISSUE TITLE
Mapillary yellow highlight icon doesn't persist

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5494]
Small issue, but noticed some different behaviour between Bing Streetside and Mapillary.

If you click on a Mapillary marker to open an image, then select an OSM object or even move your mouse away the yellow highlight disappears. It only reappears if you mouse over a Mapillary trace again.

This does not happen with Streetside or OSC, where the selected image is always highlighted in yellow. Makes it much easier to see where the image is on the map, and where it's pointing.

Occurs in both Firefox and Chrome (Windows10).

**Comment by bhousel** [comment]
Thanks for reporting @boothym - I noticed this the other day too but forgot to open an issue for it 👍

**Comment by SilentSpike** [comment]
I've managed to fix persisting the highlight when selecting an OSM object then deselecting it.

However, on further testing I've found that if multiple street imagery layers are active at once they do not interact nicely at all.
