### ISSUE TITLE
Link to OSM Wiki for `traffic_sign:forward`

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5495]
I noticed that I don't get to the wiki from the key `traffic_sign:forward=*`.
There is no Wiki page for that, just for `traffic_sign=*`.

This is what I see:
<img width="373" alt="bildschirmfoto 2018-11-17 um 07 47 21" src="https://user-images.githubusercontent.com/111561/48658230-6c42f700-ea3e-11e8-86d9-44108a652d1f.png">

I wonder …

a. Could ID notice the missing wiki-page and instead link to the primary keys page `traffic_sign`?
b. Or should I add a redirect on the wiki?

About b: How to add a redirect?
[The missing page is `DE:Key:traffic_sign:forward`](https://wiki.openstreetmap.org/w/index.php?title=DE:Key:traffic_sign:forward&action=submit). But I could not find help how to add a redirect, only [something about categories](https://wiki.openstreetmap.org/wiki/Template:Category_redirect). I am also unsure about the process inside the OSM Wiki World for pages like this.

**Comment by tordans** [comment]
CC @quincylvania since you worked on traffic signs in https://github.com/openstreetmap/iD/issues/5331 and might have an opinion :).

**Comment by 1ec5** [comment]
I added redirects for [`traffic_sign:forward`](https://wiki.openstreetmap.org/w/index.php?title=Key:traffic_sign:forward&redirect=no) and [`traffic_sign:backward`](https://wiki.openstreetmap.org/w/index.php?title=Key:traffic_sign:backward&redirect=no) in English. To do the same for other languages, replace the `title` parameter in the URL and save the page with the code `#redirect [[…]]`. (If you use Visual Editor, click the ☰ button in the toolbar and select Page settings.)

More broadly, the taginfo API we’re using to get tag descriptions just looks at the literal tag’s page on the wiki. But perhaps iD should lop off common subkeys (`:forward`, `:backward`, `:both_ways`, `:left`, `:right`, and `:conditional`, and others) before asking taginfo for the description. That would be consistent with how the [`{{tag}}` template](https://wiki.openstreetmap.org/wiki/Template:Tag) is used on the wiki.

**Comment by bhousel** [comment]
Hey @tordans - thanks for raising the issue..
There are some [existing closed issues](https://github.com/openstreetmap/iD/issues?q=is%3Aissue+wiki+redirect+is%3Aclosed) about why iD can't really follow the documentation redirects.

For now, the best solution is to just make sure each tag has a documentation page.  #5321 might offer a better solution for looking up documentation to get around the limitations of what taginfo provides, and then we wouldn't need to follow redirects for moved documentation.

Incidentally, per #5333 - please avoid using `traffic_sign:forward` and `traffic_sign:backward` - iD can't support these!  😅   We will support `traffic_sign:direction=forward/backward` instead.
