### ISSUE TITLE
Add "reset all" button to background display options

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#5503]
I often tune up brightness and contrast for some spots of the aerial imagery, where the image is very dark. Occasionally I change other values as well. As soon as I leave these dark spots I don't need the effects anymore and I have to reset every option manually. In such cases it would be helpful to have a "reset all"-button. Is it possible to add such a minor but time-saving feature?

Related to #4789

**Comment by hardik-codes** [comment]
@bhousel May I start working on this issue??

**Comment by quincylvania** [comment]
@hardik-codes I don't think anyone else has started it so go ahead!

**Comment by hardik-codes** [comment]
Ok then @quincylvania

**Comment by bhousel** [comment]
Yes @hardik-codes - for this one, just add a small link with the text "reset all" somewhere in the bottom of the pane.

**Comment by co16353sidak** [comment]
Would love to work on this as my first issue. (if no one else is) @bhousel @quincylvania

**Comment by quincylvania** [comment]
@co16353sidak I'm not sure if @hardik-codes still plans to submit a PR but it's been awhile so you can probably give it a try!

**Comment by co16353sidak** [comment]
@quincylvania If you can give me a suggestion on where to start that would be wonderful.

**Comment by quincylvania** [comment]
@co16353sidak You'll want to add the button to the bottom of [modules/ui/background_display_options.js](https://github.com/openstreetmap/iD/blob/master/modules/ui/background_display_options.js). To add the translatable label text, add a value to [data/core.yaml](https://github.com/openstreetmap/iD/blob/master/data/core.yaml) and reference it with the `t` function.

I hope that's enough to get you started! Feel free to reach out to me or the iD channel on the [OSM US Slack](https://osmus.slack.com/).

**Comment by SahibArora** [comment]
Hi @quincylvania, if its still open, I can help :)

**Comment by quincylvania** [comment]
@SahibArora Well no one has submitted a PR yet so feel free to try it!

**Comment by alphagamer7** [comment]
Hi, just to be clear, the 'reset all' button is only for display options right?
Also, need an invite to join Slack(email - athif.shaffy@gmail.com) .

**Comment by SahibArora** [comment]
Thank you! @hikemaniac, I might ask for your help if needed, from the link you provided for slack.

**Comment by alphagamer7** [comment]
Hi @quincylvania, I am attempting this too, I did the functionality and it works but the `npm run all` gives the following error `Unexpected token name «key», expected punc «;»` Probably because I am using [ES6+ language features](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/78#issuecomment-335490047). Also when I do `npm run test` it gives the following `ReferenceError: Can't find variable: iD`, although `npm run build` works as expected. 

Also, Could I please have an invite for the slack group to ask further questions. (email - athif.shaffy@gmail.com )
Thanks!

**Comment by quincylvania** [comment]
@alphagamer7 Hmm I've never seen that error but it looks like a syntax problem. Try not using newer JavaScript features 😅

You can sign up for slack yourself [here](https://osmus-slack.herokuapp.com). Turns out I posted the wrong link for that!

**Comment by SahibArora** [comment]
Ok, then @alphagamer7, you go for it. Thanks @quincylvania for the chance, I will have a look if I could help in anything else.
