### ISSUE TITLE
Switch from legacy mouse/touch events to newer pointer events

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5505]
This is a followup from #5492 

iD's support for touchscreens is not great.  We have a lot of legacy code that is really built for mouse interaction, while everywhere people using touch devices.  

Supporting touch devices has been tricky because of browser incompatibilities.  iD builds on d3 (particularly [d3-zoom](https://github.com/d3/d3-zoom) ) for map interaction, and it works ok, but we need to add a lot of workarounds.

[Pointer Events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) are the more modern and now [better supported](https://caniuse.com/#feat=pointer) way of handling user input across different kinds of devices.

More info:
https://medium.com/@wesharehoodies/pointer-events-with-react-the-why-how-what-617a5b51dbb2 

There's no rush to switch, but some things to consider:
* iD currently supports 2 finger panning and pinch-zoom gestures in Chrome, Firefox, Safari (via `wheel` events)
* iD does not currently support these gestures in Edge or IE11 ([Edge didn't implement the `wheel` event](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7134034/) workaround)
* [caniuse](https://caniuse.com/#feat=pointer) shows Pointer Events are supported in all those browsers, except Safari
  * Safari tech preview supports them as experimental feature, so they are coming eventually
  * Safari supports something called [Gesture Events](https://developer.mozilla.org/en-US/docs/Web/API/GestureEvent) instead, and we handle them already.

_Originally posted by @bhousel in https://github.com/openstreetmap/iD/issues/5492#issuecomment-440421066_

**Comment by quincylvania** [comment]
All major browsers now support pointer events, covering 86% of global users according to caniuse. I imagine it's an even higher percentage of iD users. I think it's time to try making pointer events standard as we work towards better mobile support in v3. We can fallback to the old events for unsupporting browsers.

**Comment by quincylvania** [comment]
We've made a lot of progress with this switch! Here are a few things you can now do on touch devices that were impossible or buggy before:

- Draw ways
- Drag nodes
- Double tap to add nodes to ways
- Select features with one tap
- Pan and pinch the map on Edge
- Use styluses
- Drag to change the imagery offset
- Resize the photo viewer

While there are still more opportunities to improve touch interactions, I'm considering the meat of this issue complete. Further work can be split into more specific issues.
