### ISSUE TITLE
Enable zooming with modifier key + two-finger trackpad scroll

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5508]
With the recent addition of two-finger panning, it is no longer possible to zoom via scrolling on a trackpad. While pinch-to-zoom works as an alternative, apps such as Apple Maps also allow scroll-to-zoom while holding down Shift or a similar modifier key. iD should adopt this interaction.

**Comment by bhousel** [comment]
> With the recent addition of two-finger panning, it is no longer possible to zoom via scrolling on a trackpad. While pinch-to-zoom works as an alternative, apps such as Apple Maps also allow scroll-to-zoom while holding down Shift or a similar modifier key. iD should adopt this interaction.

The old style 2-finger scroll zoom will still work if you have the control key pressed..

That's actually the hack that all the browsers implemented so that the pinch zoom works - they turn the pinch zoom into a mousewheel event with ctrl key pressed.
https://medium.com/@auchenberg/detecting-multi-touch-trackpad-gestures-in-javascript-a2505babb10e

**Comment by quincylvania** [comment]
Oh neat! I didn't see that since I have control+scroll mapped to zoom the entire display. I can change that.

<img width="661" alt="screen shot 2018-11-20 at 6 10 21 pm" src="https://user-images.githubusercontent.com/2046746/48808670-9f5fe180-ecef-11e8-8b8a-93426be4ad6c.png">

What do you think of redundantly adding Shift or Alt/Option for this so users have a choice? I could work on it.

**Comment by bhousel** [comment]
> What do you think of redundantly adding Shift or Alt/Option for this so users have a choice? I could work on it.

Sounds good to me 👍   

I think the code to adjust might just be the two `else if` blocks here:

https://github.com/openstreetmap/iD/blob/152f658f3e4234b90b3ad80c9fda27821721f496/modules/renderer/map.js#L455-L479
