### ISSUE TITLE
Mouse scroll-zooming is very slow

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#5512]
The mouse scroll-zooming has become extremely slow for me (Firefox 63.0.3 (64-bit), in Win 7 x64 SP1, latest master as of now). I suspect it's related to recent zoom changes because it worked fine a couple days ago.

![superslowzoom](https://user-images.githubusercontent.com/3857299/48839203-595c5980-ed93-11e8-8f26-fc97227a62ee.gif)

**Comment by bhousel** [comment]
Thanks for reporting @RudyTheDev - 
The code is attempting to mimic the scrolling behavior in other browsers like Chrome or Edge.  
Can you compare to the wheel scrolling there and let me know if it's similar?

I'll try it myself later, and might adjust the terms a bit:

https://github.com/openstreetmap/iD/blob/152f658f3e4234b90b3ad80c9fda27821721f496/modules/renderer/map.js#L430-L434

**Comment by RudyTheDev** [comment]
I have to hold Ctrl in Chrome to scroll now, but otherwise it is smooth.

**Comment by bhousel** [comment]
> I have to hold Ctrl in Chrome to scroll now, but otherwise it is smooth.

🤔 You should not need to hold Ctrl to scroll with the mouse wheel.   
The Ctrl-modifier is only for when you want to do a 2-finger scroll on a trackpad.

It sounds like the delta events we are receiving from your mouse wheel are in integer pixels, which is a little weird..

I wonder if it's something in here:  https://www.thewindowsclub.com/change-mouse-scroll-speed-windows

**Comment by bhousel** [comment]
ok thanks @RudyTheDev - I will try it on my Surface Pro.

**Comment by bhousel** [comment]
hey @RudyTheDev - I think these issues are fixed now in  http://preview.ideditor.com/master
Can you confirm?

**Comment by RudyTheDev** [comment]
@bhousel Yep, works as before now. Chrome too.

**Comment by shiftee** [comment]
I'm testing http://preview.ideditor.com/master/ on Ubuntu 16.04 and 18.04.

Firefox 63.0.3 is still slow for me.
Chromium is nice and fast.

**Comment by bhousel** [comment]
Thanks @shiftee  - can you test on  http://preview.ideditor.com/master/ and let me know if it's any better now?  I just pushed a change to apply the same rule on Linux as on Windows.

**Comment by shiftee** [comment]
I tested on Firefox and Chromium.
It's working beautifully now.
Many thanks
