### ISSUE TITLE
Better display of long names from the name-suggestion-index

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5514]
Maybe we should just split these to 2 lines
<img width="374" alt="screenshot 2018-11-21 12 18 55" src="https://user-images.githubusercontent.com/38784/48857781-b520e580-ed87-11e8-9afe-10836301438f.png">

**Comment by quincylvania** [comment]
Two lines sound good. We should also flexbox it so the label doesn't run under the info button.
