### ISSUE TITLE
WMS Maps4BW

### ISSUE THREAD

**Issue by robybully** [openstreetmap/iD#5517]
The previous background source of Maps4BW (Baden-Württemberg, Germany) from webatlas.de WMS layer doesn't work any more.

Service is now available under https://www.lgl-bw.de/lgl-internet/opencms/de/07_Produkte_und_Dienstleistungen/Open_Data_Initiative/ respectively https://www.geoportal-bw.de

For more infos see https://josm.openstreetmap.de/ticket/16895

**Comment by bhousel** [comment]
This issue was moved to osmlab/editor-layer-index#592
