### ISSUE TITLE
Relation stays highlighted after it's deselected

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#5521]
If you select a line belonging to a relation and then select the relation from within the object, only the previously selected line will be highlighted in orange, while the others remain highlighted in blue. If you click somewhere else to deselect the relation, the other parts will stay highlighted. This only occurs in **Firefox 63.0.1** but some another short visual glitch can be observed in **Safari** on **macOS 10.13.6**.

Relation remaining highlighted in Firefox
![relation remains highlighted](https://user-images.githubusercontent.com/31667811/48968926-9ecc9100-eff6-11e8-9ed3-32138f4c2a84.gif)

Visual glitch in Safari (the not-selected part of the relation stays blue and then suddenly changes to orange)
![relation highlighting glitch](https://user-images.githubusercontent.com/31667811/48968935-c58ac780-eff6-11e8-8629-4ae3366080f6.gif)

**Comment by quincylvania** [comment]
Hi @hikemaniac, thanks for finding this! I believe I fixed this issue, but if you see it recur or find similar problems feel free to reopen the issue or log a new one.

**Comment by hikemaniac** [comment]
Thanks @quincylvania for fixing this bug! I checked today and everything is fine now. 😊
