### ISSUE TITLE
Translations: Where do the tooltips come from?

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5523]
I am referring to tooltips like this: 
> Predominantly houses and apartments buildings.
<img width="503" src="https://user-images.githubusercontent.com/111561/48970701-cbd96d80-f00f-11e8-884f-9288b70145d5.png">

# Where do they come from?

- I cannot find them in the repo https://github.com/openstreetmap/iD/search?q=predominantly&unscoped_q=predominantly
- And not in the translation tool https://www.transifex.com/openstreetmap/id-editor/translate/#en_GB/presets?q=text%3Apredominantly (however searching there is quite tricky)

# How can I add more of them?

I think this feature is great. I would like to extend it / contribute to it.

**Comment by hikemaniac** [comment]
It looks like they come from the OpenStreetMap Wiki. On [the wiki page about landuse=residential](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dresidential) the short description is "_Predominantly houses or apartment buildings._"

**Comment by tordans** [comment]
Thanks, @hikemaniac. I still wonder how it gets into iD. There is no axaj/live request, no json, no parser I could find.

```
{{ValueDescription
|key=landuse
|value=residential
|image=Image:Lawrenceville.jpg
|description=Predominantly houses or apartment buildings. 
…
```
([Link](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dresidential?action=edit&veswitched=1&oldid=1687611))

**Comment by manfredbrandl** [comment]
I think it would be great if the localized/translated text would be used. Now it is always englisch in the tooltip but localized in the "info":
![image](https://user-images.githubusercontent.com/5360273/48971506-d816f800-f01a-11e8-80b1-18f7edcf16c1.png)

**Comment by tordans** [comment]
Thanks for the localisation fix, that is great! ([Its live on the master-preview-iD](http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&id=w60710663&map=19.00/52.47233/13.44604).)

---

_The next part is for me or anyone who might google this later :)._

A quick documentation about what I learned about how things work together:

- Whenever I type in an key input, iD queries the taginfo API for keys
  - Example  [`https://taginfo.openstreetmap.org/api/4/keys/all?lang=de&page=1&query=&rp=10&sortname=count_ways&sortorder=desc`](https://taginfo.openstreetmap.org/api/4/keys/all?lang=de&page=1&query=&rp=10&sortname=count_ways&sortorder=desc) and [`https://taginfo.openstreetmap.org/api/4/keys/all?lang=de&page=1&query=landus&rp=10&sortname=count_ways&sortorder=desc`](https://taginfo.openstreetmap.org/api/4/keys/all?lang=de&page=1&query=landus&rp=10&sortname=count_ways&sortorder=desc)
- And once the key is given, iD queries the taginfo API for values
  - Example [`https://taginfo.openstreetmap.org/api/4/key/values?filter=ways&key=landuse&lang=de&page=1&query=&rp=25&sortname=count_ways&sortorder=desc`](https://taginfo.openstreetmap.org/api/4/key/values?filter=ways&key=landuse&lang=de&page=1&query=&rp=25&sortname=count_ways&sortorder=desc)
- Part of this value-response is the description that we see
  - Example `"data":[{"value":"residential","count":4829855,"fraction":0.2167,"in_wiki":true,"description":"überwiegend als Wohngebiet genutzte Fläche","desclang":"de","descdir":"ltr"}`
  - Also https://taginfo.openstreetmap.org/keys/landuse#values 
- Taginfo gets this description from the wiki pages
  - Example https://wiki.openstreetmap.org/wiki/DE%3ATag%3Alanduse%3Dresidential

So as long as there are no wiki pages for the values of `fence_type`, [Taginfo will not show](https://taginfo.openstreetmap.org/keys/fence_type#values) them, and iD will not show them.
  - In fact, Taginfo nudges to [add wiki pages per key-value-pair](https://taginfo.openstreetmap.org/tags/fence_type=chain_link#wiki) in the UI.
  - Personally I don't want to add all those wiki pages, they are too much effort to maintain. I hope https://github.com/openstreetmap/iD/issues/5321 will continue since looks like a solution that is easier to understand and contribute to.
