### ISSUE TITLE
Checkbox-ed tag editor is mis-aligned

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#5535]
Latest master, Firefox 63.0.3 (64-bit), Win 7 Ult SP1 x64

![b](https://user-images.githubusercontent.com/3857299/49290655-337c3680-f4b0-11e8-9075-35c34a42d1f7.png)

Chrome is the same, except not missing the "change direction" button:

![c](https://user-images.githubusercontent.com/3857299/49290714-5eff2100-f4b0-11e8-9d43-74577ecb055d.png)

**Comment by my-na-me** [comment]
Seems more generell behavior, noticed same for waterway/intermittent:

![waterway-intermittent](https://user-images.githubusercontent.com/27923772/49304237-08074500-f4cc-11e8-8c12-1b5000a35ea4.jpg)
