### ISSUE TITLE
Add preset tag boxes for contact:*=* scheme to potential POIs

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5538]
I found there are a very handy preset boxes available for `addr:*=*`

![address](https://user-images.githubusercontent.com/27923772/49308322-40148500-f4d8-11e8-905a-47d453ceadaf.png)

 :-)

I could image it could by also worth to offer similar boxes for `contact:*=*` scheme, see wiki:
https://wiki.openstreetmap.org/wiki/Key:contact

Usually I add attributes from `contact:*=*` scheme at least `contact:phone=*` and `contact:website=*`.

If this idea will be not rejected, then we could think about for which main-tags the `contact:*=*` preset-boxes would be potential reasonable. Maybe starting with `tourism`, `shop`, and some `amenity`...  Or is there any known overpass or taginfo query available for checking on which tags the `contact:phone=*` and `contact:website=*` (or `phone=*` / `website=*` / `url=*`) are currently used with higher frequency?

**Comment by bhousel** [comment]
Ah sorry, we decided a while ago not to support `contact:`  - see #3915
