### ISSUE TITLE
Add button to restore all defaults of the Background Panel

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5539]
At the bottom of the Background panel, please add a button to "Restore all defaults".
This would restore all the defaults of

- Backgrounds
- Overlays
- Display Options
- Adjust imagery offset

all with one click.

And/or please add Restore Default methods for each of them that still lack such methods.
E.g., the user has clicked some Overlay choices, but now cannot remember what the defaults were.
The work is already partially done (#4789).

**Comment by jidanni** [comment]
Otherwise the only way for the user to discover what the defaults are is to create a second account.

**Comment by bhousel** [comment]
same as #5503
