### ISSUE TITLE
Wikidata field should autocomplete labels

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#5544]
#5500 implemented a Wikidata field that contains a plain text Identifier box for the QID of a Wikidata item. As a Wikidata contributor, I would find this field to be much more intuitive if it behaves like the claim text boxes on Wikidata. I think it would also be more intuitive to mappers who are unfamiliar with Wikidata and wouldn’t know how to come up with a QID on their own (since the Wikipedia field doesn’t automatically appear when you show the Wikidata field).

On Wikidata, you can type in a label and autocompletion suggestions appear, similar to the Wikipedia field’s title box:

<img src="https://user-images.githubusercontent.com/1231218/49338890-78ea5200-f5dd-11e8-89b8-693c781112b3.png" width="461" alt="label">

But you can also paste in a QID and a matching item appears:

<img src="https://user-images.githubusercontent.com/1231218/49338902-cd8dcd00-f5dd-11e8-930b-fcb4c043813b.png" width="450" alt="qid">

Either way, once you select the suggestion, the label ends up in the text box:

<img src="https://user-images.githubusercontent.com/1231218/49338908-e8604180-f5dd-11e8-9eb2-1bb82c6277cc.png" width="448" alt="result">

Even though Wikidata is built atop QIDs, the QIDs are treated like a machine-readable implementation detail and deemphasized as much as possible in UI.

So I’d suggest rearranging the Identifier, Label, and Description boxes, so that once you select an item, the Label box at the top contains the label, the read-only Description box follows, and the read-only Identifier box contains the QID at the bottom.

<img src="https://user-images.githubusercontent.com/1231218/49338984-29a52100-f5df-11e8-828e-2a274c6a87e8.png" width="351" title="rearranged">

**Comment by picsi** [comment]
This would be particularly good when used for the Architect, Species/Animal, Operator, Network, Brand, Artist, Name Etymology and Subject fields.

So when typing out, for example, in an architect field "Santiago Calatrava", a Wikidata dropdown menu would appear, and upon selection we'd automatically set `architect=Santiago Calatrava` _and_ `wikidata:architect=Q168482`.

**Comment by bhousel** [comment]
> So when typing out, for example, in an architect field "Santiago Calatrava", a Wikidata dropdown menu would appear, and upon selection we'd automatically set `architect=Santiago Calatrava` _and_ `wikidata:architect=Q168482`.

I think people are generally in favor of the idea except for the "automatically" part  👍

**Comment by picsi** [comment]
@bhousel if we know that the fields _architect_ and _wikidata:architect_ are exact equivalents, what's the risk?

**Comment by 1ec5** [comment]
Here’s [an example Wikidata API query](https://www.wikidata.org/wiki/Special:ApiSandbox#action=wbsearchentities&format=json&uselang=vi&search=Junction%20City&language=vi&type=item&limit=10) that would be kicked off after typing in “Junction City” when iD is set to the Vietnamese locale. Notice how the labels and descriptions are in English as a fallback.

Note that this issue is specifically about the behavior of the existing `wikidata` field type, which is currently only used for the Wikidata field (corresponding to the `wikidata` tag). #5484 is about adopting that field type for the Operator field (`operator:wikidata`). I do think this issue would need to be addressed before Wikidata functionality could be added to any other fields, because there isn’t a straightforward mapping from taginfo autocompletion results to Wikidata QIDs.

**Comment by quincylvania** [comment]
I did this.

![wikidata demo](https://user-images.githubusercontent.com/2046746/55199726-69e16e00-5191-11e9-8af9-4c163df51437.gif)
