### ISSUE TITLE
Add autosave function for osmChange-file to local drive before osm-data-upload

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5547]
Hi, it seems the request (https://github.com/openstreetmap/iD/issues/5542) to add an abort or cancel button while uploading osm-data to osm-database is still in considering status, because it was a duplicate of this (see https://github.com/openstreetmap/iD/issues/4717).  Considering status maybe because of other internal issues.

So in meantime, please could you think about to add a function to autosave the OsmChange file (available since https://github.com/openstreetmap/iD/pull/4350) to local drive (for backup), before the new changes will be send to the osm-api for uploading into the database?

Last time, when I lost the data of a non-uploaded changeset, I think I lost app. 2h lifetime ...

PS: Maybe it's not needed for each upload (for small set of changes), the autosave could maybe only run for sets which contains more than 10 or 20 changes. Or which amount do you think could be suitable?

**Comment by bhousel** [comment]
Sorry, but browsers can not autosave files to your hard drive.. Could you imagine the kinds of terrible stuff that people would do?

There is a button at the bottom of the save screen to allow you to download the osc file manually.

Also, I hesitate to even say this but.. Don't wait 2 hours to save!

"iD crashed and I lost 30 seconds of work!"  -- said nobody ever.

**Comment by bhousel** [comment]
> Considering status maybe because of other internal issues.

It's tagged as "considering" "bluesky" and "waitfor-upstream" 

This means, "we might do it"  "it might be impossible" and "we can't even consider it until the OSM API supports such a thing".
