### ISSUE TITLE
Prevent browser page navigation when panning with trackpad or magic mouse

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5552]
Starting a pan with a horizontal gesture can cause the browser to navigate between pages in the tab's history, thus inadvertently closing iD.

- iD 2.12.0
- Safari, Chrome
- macOS 10.14
- Apple trackpad, magic mouse

**Comment by bhousel** [comment]
I think #5505 might make it more possible to fix this

**Comment by sookoll** [comment]
Well You can just remove this horrible two fingers panning and You are all good. I stopped editing OSM after You made this change, because it is just frustrating.

**Comment by bhousel** [comment]
> Well You can just remove this horrible two fingers panning and You are all good. I stopped editing OSM after You made this change, because it is just frustrating.

Sorry to see you go, but hope you will consider using another editor to continue to contribute to OSM.

**Comment by quincylvania** [comment]
I found a solution for this that works for a Macbook trackpad in testing. I don't have a magic mouse for testing at the moment but I expect this solution will also fix panning on that device.
