### ISSUE TITLE
Tons of data spontaneously disappeared from Maps in Rochester, NY Metro area

### ISSUE THREAD

**Issue by ibuddy66** [openstreetmap/iD#5554]
Upon logging in today, there is tons of missing data for places I added almost a year ago now on the map.  It is almost blank in some areas that had been previously worked on.  What is going on with OSM lately.  This isn't the first time this has happened here either and it makes the maps completely outdated.

**Comment by iandees** [comment]
Can you give a more specific link to the area you're talking about?

**Comment by ibuddy66** [comment]
Hey thanks for the response :) Sure can.  It's Rochester, New York, USA.  @iandees https://www.openstreetmap.org/#map=18/43.23756/-77.64584

For example here I have had to go back and re-add dairy queen, big lots, good will, and further up the screen is a Walmart plaza that I've had to redo the buildings for multiple times now and the area place for the plaza is missing again now.

**Comment by ibuddy66** [comment]
I added it last year.  I have no idea what changeset it would be now.

**Comment by ibuddy66** [comment]
Others had also added buildings there along Dewey Avenue on the other side too that have just seemingly disappeared recently.  Even though they're still there.  The bing imagery here is severely outdated and the only imagery I generally use for clarity is Mapbox because it is the most clear when editing.  That too, though can be outdated as well many times.  Not sure if that has anything to do with some edits in diffferent places.

**Comment by iandees** [comment]
I spent an hour or so looking through edit history and didn't see any edits that seemed to be deletions in the area. I would recommend that you go through your edits, find the changeset where you added the Dairy Queen, and look for the changeset that deleted it. You could then politely ask that mapper to double-check with other imagery sources before deleting map data.

Either way, this is not really a problem with iD, the map editor, so I'm going to close this ticket for now.
