### ISSUE TITLE
Name autocomplete makes it hard to enter names that start with common words

### ISSUE THREAD

**Issue by iandees** [openstreetmap/iD#5558]
There's a place nearby called "We Are Nuts". When I try to type "We" + space into the name field, it autocompletes to a store called "WE - somethingsomething", capitalizes the e for me, and it's hard to go back and fix that incorrect capitalization:

![nameautocompletebug](https://user-images.githubusercontent.com/261584/49529472-b2d88400-f87b-11e8-8488-70e41fcb5a4e.gif)

**Comment by bhousel** [comment]
Scope creeping on this issue (#5568 is related)...

- fix keyboard handling of up/down arrow and escape when a combobox is open (these keys should not do other iD things like trying to pan the screen or return to browse mode)
- escape should get rid of whatever autocompletion selected text is there
- up/down key navigation seems to not class the top item as `selected` if the list is too long / or scroll the item into view / or something
- this means that tabbing out of the list with the wrong item `selected` can accept an item that is not the one selected/displayed in the `input` field

I've added an option to disable autocomplete behavior.. I might keep it or get rid of it depending on how the combobox "feels" after I make it do all the things that I expect a combobox to do.  We could also start out autocompleting and then maybe put the combo into "no autocomplete" mode after the user starts backspacing or something.
