### ISSUE TITLE
Add traffic island area preset

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#5562]
This would add rendering for `traffic_calming=island` (i.e. [these separate areas](https://upload.wikimedia.org/wikipedia/commons/d/d4/LUMC-rotonde.JPG)) mapped as areas. It's [used de facto quite a bit](https://taginfo.openstreetmap.org/tags/traffic_calming=island), but not as much due to mistagging and imprecise tagging mentioned below.

![old](https://user-images.githubusercontent.com/3857299/49585908-5acb7b80-f968-11e8-91cb-d6106d7151d7.png)
to
![new](https://user-images.githubusercontent.com/3857299/49585783-07592d80-f968-11e8-804b-6a33f73884c8.png)

It's a typical example around my area of grassy lane-dividing traffic island with a paved pedestrian section and some railings for safety. The `surface` tag is what specifies the actual surface. (Notice also the poor grit box without an icon :sob:)

There are also:
* `traffic_calming=choker` [taginfo](https://taginfo.openstreetmap.org/tags/traffic_calming=choker)
* `traffic_calming=chicane` [taginfo](https://taginfo.openstreetmap.org/tags/traffic_calming=chicane)

The islands are commonly mapped with less precision as just `landuse=grass`/`natural=grass` (which is probably where the majority of improvable uses are hiding). These are also mapped with multiple features as `traffic_calming=island` and `landuse=grass`. These are also occasionally "forced" to render with `area=yes`. All these sounds as mapping for renderer.

A different tagging also exists: `area:highway=traffic_island`. iD treats `area:highway` as "Road Surface". Wiki also says `area:highway` is for roads: lanes, but not extras, like shoulders, parking, sidewalks. In practice, it's used for separated islands too. I'm not sure if iD should have a preset for these too? This scheme doesn't have choker or chicane supported. I'm not even sure if it doesn't just mean the flush painted/marked areas.

* `area:highway=traffic_island` [taginfo](https://taginfo.openstreetmap.org/tags/area%3Ahighway=traffic_island)

**Comment by bhousel** [comment]
> This would add rendering for `traffic_calming=island` (i.e. [these separate areas](https://upload.wikimedia.org/wikipedia/commons/d/d4/LUMC-rotonde.JPG)) mapped as areas. It's [used de facto quite a bit](https://taginfo.openstreetmap.org/tags/traffic_calming=island), but not as much due to mistagging and imprecise tagging mentioned below.

I like it!

> The islands are commonly mapped with less precision as just `landuse=grass`/`natural=grass` (which is probably where the majority of improvable uses are hiding). These are also mapped with multiple features as `traffic_calming=island` and `landuse=grass`. 

This seems ok too.

> These are also occasionally "forced" to render with `area=yes`. All these sounds as mapping for renderer.

Aside: I wish people would stop reflexively dismissing "mapping for the renderer".  Users want to be able to make maps out of this stuff, and I have tremendous sympathy for the developers who maintain the rendering software.  We should try to pick tags that make their job easier.  Thinking about it more, maybe `landuse=grass`/`natural=grass` is better for this.

> A different tagging also exists: `area:highway=traffic_island`. iD treats `area:highway` as "Road Surface". 

Oh yeah, `area:highway` is really for road surfaces, and for users who want to micromap the area of the pavement.  It's not for obstacles like islands.  If you find `area:highway=traffic_island` tags, please replace them with one of the other options above (and whoever feels like updating the wiki should do that too, so we can stop giving people bad advice).

**Comment by bhousel** [comment]
> Thinking about it more, maybe `landuse=grass`/`natural=grass` is better for this.

Yeah I thought about this even more, and I think mappers should just use other more widely used tags.

I think plain old `natural=grass` is better than `traffic_calming=island`+`surface=grass`

**Comment by RudyTheDev** [comment]
What does one use when the surface isn't grass?

**Comment by bhousel** [comment]
> What does one use when the surface isn't grass?

I'd do this:
![island](https://user-images.githubusercontent.com/38784/49708161-6b941f80-fbfc-11e8-998c-fd5b7e6dd36a.png)


p.s. Added a generic "box" icon for the grit bin in 05c24c95d

**Comment by RudyTheDev** [comment]
What about:

![ex](https://user-images.githubusercontent.com/3857299/49731127-00416080-fc83-11e8-9878-9d14f8447638.png)

Here, it's a raised island in the middle of the road splitting lanes. It's marked off and no pedestrians are allowed. The surface is asphalt. There are reflective poles along the edges.

**Comment by bhousel** [comment]
> Here, it's a raised island in the middle of the road splitting lanes. It's marked off and no pedestrians are allowed. The surface is asphalt. There are reflective poles along the edges.

Ohh ok!  Yeah that is a better example of a `traffic_calming=island`.  I think the first example you gave is not really one - it's just the space between a dual carriageway, not designed to slow the cars.

So an interesting thing - the OSM wiki has a contradiction..
- This page says they can be mapped as areas:
https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland
- But this page says nodes and ways only:
https://wiki.openstreetmap.org/wiki/Key:traffic_calming

That's probably the reason that we don't already have a preset for a traffic calming with `area=yes`.  But I agree now that I know what this is, we should support this.

**Comment by RudyTheDev** [comment]
> I think the first example you gave is not really one

Yeah, my bad. That example inadvertently muddles the waters with whether the pedestrian bit is a traffic calming or not.

Here's a better real example for posterity:

![ex](https://user-images.githubusercontent.com/3857299/49742183-ac457480-fca0-11e8-883c-8a4a1b9d7eba.png)

The left island is grass, the right one is asphalt. Both have a "pedestrian area".
