### ISSUE TITLE
Enable sidebar when clicked on "Save"

### ISSUE THREAD

**Issue by srividyacb** [openstreetmap/iD#5574]
Really loving the sidebar toggling feature which gives enlarged view to map bigger and longer features.

Can we enable sidebar by default when **Save** button is clicked so that the mapper will be shown changeset comment details before uploading ? (this reduces confusion on what is the next step specially for new mappers).

![sidebar-id](https://user-images.githubusercontent.com/3423533/49685048-ae71cc80-fb02-11e8-9794-dd0c208f7e0b.gif)

**Comment by bhousel** [comment]
Oh yeah - good suggestion!
