### ISSUE TITLE
Tabbing out of Name field *replaces* what I typed with a completely different name (iD 2.12.1)

### ISSUE THREAD

**Issue by jfburke3** [openstreetmap/iD#5578]
When typing in the Name field, iD 2.12.1 helpfully shows matches that you might want.  This is good.

When you finish typing a complete name and tab out of the name field, iD *replaces* what you typed with a name from its automatch database.  This is bad.  Not only does it replace the name, but it also adds additional fields and data that aren't relevant.

Examples:

"Quick Stop TIres" in Purvis MS became "Quick Schuh"
"Purvis Middle School" became "Puregold" (a supermarket)
"Cornerstone Baptist Church" became "Corporation Bank"

To make it worse, the Name field then becomes a non-edit box that I can't change.  I have to scroll down to the All Tags section and replace it there (and delete the extra tags that iD added).

iD version is 2.12.1, using Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by jfburke3** [comment]
Note:  this is kinda similar to #5558 but is NOT the same problem.  The issue I'm documenting occurs when you tab out of the Name field; it is not replacing the name while I type.

**Comment by bhousel** [comment]
> Note: this is kinda similar to #5558 but is NOT the same problem. The issue I'm documenting occurs when you tab out of the Name field; it is not replacing the name while I type.

The problem description is different from #5558, but the fix is the same - prevent the autocomplete from happening.

Can you test the fix in http://preview.ideditor.com/master and let me know if the current field in master is working better?

>To make it worse, the Name field then becomes a non-edit box that I can't change. I have to scroll down to the All Tags section and replace it there (and delete the extra tags that iD added).

The trash 🗑button above the name field should remove all those tags..

**Comment by jfburke3** [comment]
I think the trash button was nonclickable after I tabbed out.  Having an odd browser problem a.t.m. so can't reproduce to check that.

I'll try the preview site once I've gotten my browser issue worked out.  Thx!

**Comment by jfburke3** [comment]
On the production version, deleting the Name with the Trash button does *not* also remove the brand* tags.  Will try the preview version next.

**Comment by bhousel** [comment]
Tested a bunch with the preview version today, and this is fixed now..
