### ISSUE TITLE
Add checkbox option to tag eateries as vegetarian/vegan

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#5580]
The keys `diet:vegetarian` and `diet:vegan` allow three values: `yes`, `no` and `only`. Here are some more details:

* https://wiki.openstreetmap.org/wiki/Key:diet:vegetarian
* https://wiki.openstreetmap.org/wiki/Key:diet:vegan

This is particularly helpful to avoid the spread of `cuisine=vegetarian/vegan`, which is deprecated.

**Comment by bhousel** [comment]
I could see adding multicombo field for `diet:` as a moreField (recently added in #5582) .
I definitely don't want to add checkboxes for every kind of `diet:` that people think of.

**Comment by bhousel** [comment]
> I could see adding multicombo field for `diet:` as a moreField

☝️ I did this
