### ISSUE TITLE
Conditional field display based on tags

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5581]
Sometimes it only makes sense to display a field if certain tags are present on the feature. For example, the Payment Types field would be useful on presets such as Parking Lot, Telephone, or Toilets, but only when `fee=yes`. Another use would be in #5580, where the field for `diet:vegetarian` would be redundant if `diet:vegan=yes`.

I propose finding a generalized solution where conditions can be defined in JSON and not in code.

Related: #4871

**Comment by bhousel** [comment]
This sounds really hard..
