### ISSUE TITLE
Naming rule check

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5590]
On the wiki page for names there is a section called Name is the Name Only, which says that names   should be restricted to the name of the item only and not contain the official name such as categories, types, or descriptions of the objects. It also says not to invent names if the object doesn't have one. 

As it currently stands there a bunch of objects in the database that contain descriptive names. Some examples include name=park (2436 uses), name=school (2538 uses), name=shop (1635 uses),  name=parking (1635 uses). There's many others. Along with things containing category names, like name=public_toilet (395 uses). Although its to a lesser degree. 

given the amount of miss naming going on, would it be possible to have iD Edior do a check when someone saves their work to see if the key of the object matches the key of the name tag or something? If  that doesn't work, it would be good to at least  mention the naming rule when someone clicks on the more information button in the name preset or somewhere else before they add a value to it. So they know what the proper tagging is and don't just add a name because they think it needs one. I've talked to some new editors about it. All of them didn't know the rule existed and just wanted to put something in the name field since it was there. Even if the object didn't have a proper name. So, its obviously an issue for new mappers.

**Comment by bhousel** [comment]
Hmm we probably could create a validation for this

We actually have a pretty solid noiseword regex over in name-suggestion-index to filter out generic names.
https://github.com/osmlab/name-suggestion-index/blob/master/config/filters.json#L44

**Comment by bhousel** [comment]
It's worth mentioning that we do sort of tell users how to use the Name field in the walkthrough.  I don't want to overload new users with a bunch of complicated rules - I think the short explanation here is ok.

<img width="1002" alt="screenshot 2018-12-11 16 42 03" src="https://user-images.githubusercontent.com/38784/49832072-9f3d8980-fd63-11e8-8900-dd23e5aa3d50.png">

**Comment by Adamant36** [comment]
I don't blame you for not wanting to overload new users with complicated rules. They wouldn't necessarily follow it anyway. So a validation thing would be my preferred solution if its possible. I was actually thinking about something like or related to the name-suggestion-index when I created the issue.

**Comment by bhousel** [comment]
Ok  - I added a generic name validation that checks several common tags for a matching value (e.g. `leisure=park` tagged `name=park`) and then also checks the name filters from the name-suggestion-index.  It's not perfect, but it catches a lot of bad names 👍

**Comment by Adamant36** [comment]
Awesome. Thanks.
