### ISSUE TITLE
Change the riverbank preset to use "natural"="water" + "water"="river" instead of "waterway"="riverbank".

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#5591]
When adding a river's area, iD suggests the preset "riverbank".  The preset currently uses "waterway"="riverbank". 
According to [the wiki](https://wiki.openstreetmap.org/wiki/Key:water#Rivers_and_reservoirs):

> So, these are equivalent, while natural=water scheme is preferred:
>
> * waterway=riverbank is the same as natural=water + water=river
> * landuse=basin is the same as natural=water + water=basin
> * landuse=reservoir is the same as natural=water + water=reservoir
> * landuse=pond is the same as natural=water + water=pond

Using just the `natural=water` tagging would allow for much simpler data processing for data consumers, much easier Overpass queries, and more consistency.

**Comment by bhousel** [comment]
Oh interesting.. I didn't know there were 2 different ways to tag water.. But I do like `natural=water`+`water=*` better, for consistency. 

Should we just switch them all?

**Comment by BjornRasmussen** [comment]
Sure! Which others are there? I know that the preset "Reservoir" already uses the water=* system.

**Comment by bhousel** [comment]
> Sure! Which others are there?

I was thinking just 4 listed above..

**Comment by Lukas458** [comment]
but the problem might be, that the water which is in reservoirs or basins, doesn't have to be a "natural" feature, does it? I know we should not discuss this here bit in my opinion, "natural" is the right key only for some "water" features.

**Comment by BjornRasmussen** [comment]
Yeah, I see what you mean. A lot of keys in OpenStreetMap that don't make sense. For example, `landuse=grass` is not landuse, and neither is `landuse=reservoir`. Also, `highway=street_lamp` is not a highway.

Anyways, according to the wiki, 
>Note that despite key name it is also used for artificial structures like moats, basins of a wastewater treatment plants, canals etc.

Although the `natural=water` tag is confusing in artificial water bodies, I think that the benefit of consistency outweighs the disadvantage of confusing tag names. 

Thanks for sharing your thoughts!

**Comment by bhousel** [comment]
I did this.  I also added a preset for  `natural=water + water=stream`, although it is not mentioned on the wiki on [the `natural=water` page](https://wiki.openstreetmap.org/wiki/Key:water) or mentioned on the discussion page.

This is to keep things consistent with 
- `natural=water + water=river` "A body of river. Should contain waterway=river way inside."
- `natural=water + water=canal` "A body of a canal, a man-made channel for water. Should contain waterway=canal way inside."

Anyway, somebody should update the wiki page, thanks.

**Comment by jjiglesiasg** [comment]
This changes do not need to be discussed?
landuse=basin is for STORMWATERS a total different subjet than natural=water
waterway=riverbanks are variable amplitudes of water even intermitent, when main water=river is a permanent one. Suddenly they are changing the preset without any advise or consult to the Mappers.
I dissagre with this kind of behaviour if undisscussed....

**Comment by jjiglesiasg** [comment]
From the Wiki:
Do not:
a) tag objects with both variants (waterway=riverbank+natural=water)
b) tag parent relations with natural=water
c) convert from waterway=riverbank to natural=water tagging scheme (or vice verso) without a good reason because doing so can be very tricky and trigger errors which are not easily visible and not reported by QA tools. For example, it must be assured that the use of natural=riverbank/natural=water is consistent in parent and child relations.

**Comment by BjornRasmussen** [comment]
I don't see how this change violates anything, so please explain if I am wrong.
> landuse=basin is for STORMWATERS a total different subject than natural=water 
Perhaps, but by definition, the tags natural=water + water=basin mean the exact same thing as landuse=basin according to the wiki.

**Comment by BjornRasmussen** [comment]
> convert from waterway=riverbank to natural=water tagging scheme (or vice verso) without a good reason because doing so can be very tricky and trigger errors which are not easily visible and not reported by QA tools.

What errors could arise from changing a preset? Could you give examples?  In my opinion, gradually phasing out waterway=riverbank would actually reduce double tagging errors (if that is what you mean by errors).

**Comment by bhousel** [comment]
> This changes do not need to be discussed?

It was discussed here and @BjornRasmussen linked to the wiki pages where plenty of discussion happened going back years. You'll notice we also let the issue sit for a month to see if anyone would show up with a good reason to leave the presets along. To be honest, if I knew there were better ways to tag these things, I would have switched these presets years ago.

> From the Wiki:  Do not:
> a) tag objects with both variants (waterway=riverbank+natural=water)
> b) tag parent relations with natural=water
> c) convert from waterway=riverbank to natural=water tagging scheme (or vice verso) without a good reason 

for a) we don't do that.  
for b) we only do that if the parent relation is a multipolygon, but obviously the wiki author didn't think too deeply about parent relations when they wrote that.   
for c) we aren't converting anything, but mappers can do this if they want to.  Putting all the water features under `natural=water` is a "good reason".

Also... I say this a lot, but you really need to read everything on the wiki with extreme skepticism.   I'm considering just locking any issue that contains a phrase like "According to the wiki.."

**Comment by BjornRasmussen** [comment]
>This is not really something that should need to be discussed  
  
I meant dealing with the tagging@ list.
