### ISSUE TITLE
Not recognized as logged in when viewing notes

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#5593]
When viewing nodes in iD I am presented with the `You must log in to change or comment on this note` box and cannot open notes from in the editor.  
I have reloaded, refreshed the page cache, logged in and out of osm.org with no change.  
I can open notes from the osm.org main page just fine.

## Examples
![one](https://i.imgur.com/MY1QDuy.jpg)  
![two](https://i.imgur.com/8cBdwsE.jpg)

## Specs
Ubuntu 18.04 LTS
Vivaldi 2.1.1337.51 (64 bit)
OS is up-to-date.

**Comment by bhousel** [comment]
Thanks for reporting @rivermont  - can you check that your browser is able to write to `localStorage`?  Anything that prevents that (e.g. incognito mode or similar) will prevent iD from authenticating.

**Comment by rivermont** [comment]
It seems to have solved itself, either a browser restart or rebooting worked. Someone in OSM-US slack said they also had this happen only once and never again, so maybe it's a one-time issue. Feel free to reopen if we need a better explanation.
