### ISSUE TITLE
Give better results for "roof" search term (building=roof should appear before groyne)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5595]
![selection_001](https://user-images.githubusercontent.com/899988/49938101-1fd1c680-fed9-11e8-87ad-564280659170.png)

**Comment by bhousel** [comment]
You need to map the roof as an area not a line..

**Comment by matkoniecz** [comment]
I tested it with https://www.openstreetmap.org/way/654706823

I retested it again, on deleting building=roof tag and trying to search again it is giving exactly the same results.

All my checks indicate that it is a closed way.

**Comment by bhousel** [comment]
Yeah, you can't just delete the `building=roof` tag, that will make it a line again.  OSM doesn't have a real polygon data type, so we need to recognize which tags imply that a thing is a polygon (area).

If you map the roof as an area, you'll be suggested area presets (like "roof")
If you map it as a line, you'll be suggested line presets (like above). 

![building roof](https://user-images.githubusercontent.com/38784/49942989-ca83be00-feb4-11e8-9bda-f586d0da723f.gif)

**Comment by matkoniecz** [comment]
Sorry for misinterpretation of the situation.

I think that closed way without any tags should be considered as both line and area and get preset results for both but it leaves bug area and goes into design decisions.

**Comment by bhousel** [comment]
No problem, we were just discussing this on #5569 and the issue tracking this is #1828

It's probably also worth mentioning - this is one of those weird issues where only people with long term OSM experience who know about tags are always reporting it to me as an issue, but newbies who go through the tutorial and pay attention to the UI clues understand the difference between lines and areas right away.

It's really wild how the lack of a proper polygon/area datatype in OSM has distorted people's thinking.  In an alternative universe (or possibly a future one), OSM just used GeoJSON as its data model, everyone understands the difference between Polygons and LineStrings intuitively, and areas are impossible to break by deleting parts of them or mistagging.
