### ISSUE TITLE
Combobox should toggle on clicking anywhere on the field, not just the carat

### ISSUE THREAD

**Issue by phiphou** [openstreetmap/iD#5596]
Click on fields should show list of options. In the previous release, click on a field in the sidebar after selecting something showed list of options, now it doesn't work. We have to click on the arrow to show list of options. It would be great we can have the old behavior.

**Comment by bhousel** [comment]
> Click on fields should show list of options. In the previous release, click on a field in the sidebar after selecting something showed list of options, now it doesn't work. We have to click on the arrow to show list of options. It would be great we can have the old behavior.

Users can still press the up/down keys, click the carat, or start typing in order to get the menu to pop up.

I think the new behavior is a lot more in line with how other comboboxes/dropdowns work on other sites.  Can we just try it out this way for a little while?

**Comment by phiphou** [comment]
I use ID every day since three years so this change is a little confusing for me. But I will maybe accustom with this new behavior, even if I find the old behavior more convenient. Please let the ticket opened in order to see who agree with this. (sorry for my bad english, I'm french)

**Comment by RudyTheDev** [comment]
I actual prefer the new behavior. I don't always want to have the dropdown open obtrusively when I click the field to edit directly. Not that I have yet encountered a case where immediately opened dropdown was a problem.

**Comment by bhousel** [comment]
> Maybe it would be a compromise to increase & clear separation (add a vertical line) of the carat area...

I'm planning to make it so that you can click anywhere on the field to toggle the combo (not just on the carat area)

**Comment by bhousel** [comment]
@maxgrossman  you can look into this one too..
I *think* it's just that this block of code needs to move from the `carat` to the `input` and then the `carat` should get CSS `pointer-events: none` so the clicks don't go to it.

https://github.com/openstreetmap/iD/blob/f478fdbfbd3f9cb4f8ddd0b232c78d523dfefc3e/modules/ui/combobox.js#L69-L83
