### ISSUE TITLE
Define preset-specific fields to be removed from the "Add field" dropdown

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#5598]
As of [v2.12.2](https://github.com/openstreetmap/iD/blob/master/CHANGELOG.md#2122) we now have the option to specify additional fields present in the "Add fields" dropdown for different presets! :tada:

As kind of an inverse to #5582, could we specify certain fields to be ignored in the dropdown? Eventually some presets will have many things in the dropdown and it will get clogged up, and the defaults sometimes aren't relevant.

For example, "Parking Lot" doesn't need the `Fax` or `Seamark` fields.

Example code for "Parking Lot":
```
{
    "icon": "maki-car",
    "fields": [
        "name",
        "operator",
        "parking",
        "capacity",
        "fee",
        "access_simple",
        "supervised",
        "park_ride",
        "surface",
        "maxstay"
    ],
    "ignoreFields": [
        "email",
        "fax",
        "seamark",
        "tourism",
        "wikipedia",
        "wikidata"
    ],
    "geometry": [
        "point",
        "vertex",
        "area"
    ],
    "tags": {
        "amenity": "parking"
    },
    "terms": [
        "automobile parking",
        "car lot",
        "car parking",
        "rv parking",
        "truck parking",
        "vehicle parking"
    ],
    "name": "Parking Lot"
}
```

An alternative to this might be reducing the default fields to those that are immediately relevant to all objects.

**Comment by quincylvania** [comment]
Hi @rivermont! Now that we have `moreFields`, there's been talk about reducing or removing `universal` fields altogether. Rather than ignoring irrelevant fields, all relevant fields would be defined in either `fields` or `moreFields` for every preset.

**Comment by rivermont** [comment]
@quincylvania Awesome! I like that idea better, and if there's already a plan there I'll close this. Is there an issue already open regarding that?

**Comment by quincylvania** [comment]
No, there's no issue that I'm aware of. The details still have to be flushed out, since it also wouldn't be great to repeat the same five fields 100 times. Feel free to create some sort of "don't show irrelevant fields" issue if you want! Then we can discuss the best solution.
