### ISSUE TITLE
Boundaries still render when disabled if they are a relation

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#5601]
This happens whether all the parts are downloaded or now, just as this large one:

![bound](https://user-images.githubusercontent.com/3857299/50006986-2125f080-ffb8-11e8-869d-fd01cc1db7a6.png)

Versus a test small one:

![b 2](https://user-images.githubusercontent.com/3857299/50007193-d5277b80-ffb8-11e8-96ad-d7fe59ef2775.png)

Right one is hidden correctly. Left one remains visible.

**Comment by BjornRasmussen** [comment]
I know that new objects added by you in the changeset will not be hidden in iD.  Only existing elements will.  That might be the problem.

**Comment by bhousel** [comment]
#5406 is related
