### ISSUE TITLE
Fix area:highway rendering of alleys, parking aisles, and other subclasses of highway=service

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#5602]
![image](https://user-images.githubusercontent.com/37753777/50007748-e4d69e00-ff7f-11e8-9525-12cea5154580.png)
I am not entirely sure if this is the correct way to tag the area of an alley (or any other `area:highway=service` & `service=*` combination), but iD seems to render the area incorrectly. 

To fix, change the code that renders the `service=alley, driveway, etc` to only render if `highway=service` is also present on the element.

**Comment by bhousel** [comment]
hmm.. I'm also not sure if that is the correct way to tag it.

I would do `highway=service` + `service=alley` on a line down the center of the alley.  This part is required.  People really shouldn't map highways as areas and expect routers to work.

Then a separate polygon tagged `area:highway=yes` for the area of pavement.  iD has a preset for this called "Road Surface".  This part is very much optional, and really only people who want to micromap do it.

**Comment by BjornRasmussen** [comment]
In the image above, the correctly added alleys are hidden, since only `landuse` is enabled.

**Comment by bhousel** [comment]
> In the image above, the correctly added alleys are hidden, since only `landuse` is enabled.

oh good!  I will try to fix the rendering so that only linear service=alley get the thick yellowish style.
