### ISSUE TITLE
Add preset for sport=netball

### ISSUE THREAD

**Issue by CloCkWeRX** [openstreetmap/iD#5604]
https://en.wikipedia.org/wiki/Netball is a common sport in many commonwealth countries, with courts frequently found in schools or similar in Australia.

![image](https://user-images.githubusercontent.com/365751/50038327-cd75de80-006d-11e9-8b42-96f730c7c6e2.png)

Potential icons - https://commons.wikimedia.org/wiki/Category:Netball_icons

**Comment by bhousel** [comment]
done in 68a642119
