### ISSUE TITLE
Holes in ways

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5607]
Hi,
ID makes good things but not completely.
When we create a road and we "miss" the connexion to another road (the first node of the new road is very closed of the other road but there is an hole between them), when we wanted to save, we have a message of ID telling that a road is not connected.

But ID don't see all the holes and some should be I think :
- it doesn't see that a bridge (or a tunnel and so on) is correctly connected on **both** sides. A road connected only on one side is not a pb, a lot of roads of course end "nowhere". But a bridge (a tunnel...) has to be connected on both sides and ID don't warn us if any.
- there is another kind of holes very difficult to see : 2 times when driving with my GPS with OSM maps, it told me stupid things (calculate a very long route rather than a short one) not because a true hole between 2 roads but because one road was put like a one-way road by error. I explain with one of the 2 cases : there was a road with a separator. In OSM the road was displayed by 2 one-way ways, I will call them way 1 and way 2. At the end of the separator, the way 1 was stopped on one node of the way 2, no pb here. The pb was that the way after this node was not a new way (way 3) with no attribute but the same way (way 2) with of course the one-way attribute.
So, for the GPS (and the road), looks like an hole but only in one direction : you may drive from the separator to outside, following the way 2, but you were not allowed to enter the separator, it was impossible to drive on the way 1 because the way 1 begins nowhere, there was in fact no way arriving at the beginning of the way 1. For us difficult to see (like I said I found 2 times these error in OSM and my habit of OSM is not important so I imagine there are other cases) but very easy I think for ID (the first node of a one-way way has to be connected to a way with 2 directions or to a one-way way with the same direction).

Best regards
Mahab

**Comment by bhousel** [comment]
Q/A tools like KeepRight and others are probably currently the best way to catch these disconnected ways. 

KeepRight integration will be shipping in the next release of iD, see #5201, but we plan to add others soon also, as well as the capability to check the user's work for issues as they are editing.

**Comment by Mahabarata** [comment]
OK, perfect !
Best regards
