### ISSUE TITLE
Unnecessary nodes

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5608]
Hi,

A lot of times, I find in OSM 5 nodes on a straight road where only 2 nodes is necessary.
Or 5 nodes in a very short bend, each node maybe at 5 meters from each other with a very small difference in the direction of the lines between the nodes.
In the wiki, we can read that we can draw a roundabout with only 4 nodes. Of course it is not a good example because it's not very beautiful, better to have more and ID, when we are using the option to create a circle, makes a very good job by adding some nodes not to closed one of each other.
But sometimes a user creates a lot of nodes completely useless. And when we want to make changes to the ways, we have a lot of points to move (or to delete) and sometimes it's very difficult to keep all these points aligned or in a good 'circle'.
I had the same pb with my GPS : a lot of points were created when driving, making a very big file with a lot of useless data because of aligned points or points to close one from each other. When putting these files on Internet, it took a lot of time to be downloaded to see the tracks for example in goo... maps. So I have created a software to clean up these useless points (with parameters because you don't need the same accuracy when you want to see the result on a 1/100 map and a 1/100000 map). You have an example of the result here : <a href='http://montdm.free.fr/itineraire_google.php?ti=s20140723.'>my website</a>. If you zoom, we will see that a lot of points have been deleted because useless on a big map. If you choose another track, there are more points because map is more accurate so tracks are also more accurate.

When I look at the circle created by ID, I understand that you know how to make the difference between good nodes and useless nodes : so I will suggest that, when we save our works, ID cleans up the useless nodes.
I'm pretty sure that, if someone did the cleaning in the data of OSM of all the useless nodes, you would have more than half of the current data on the server meaning a computation to create the maps a lot much quicker (and a lot of free space on hard disks) which also means a lot of saved money : OSM is a free software for us but someone pays for that, no ?

Best regards
Fred

If you want to see an example of a crazy things with thousands of useless nodes, looks at https://www.openstreetmap.org/way/342862050

**Comment by bhousel** [comment]
Ah yeah, this is #3116

**Comment by Mahabarata** [comment]
Ok : I of course search in the open issues to find if someone told about the things I see.
I think that the title of the issue 3116 is not clear, too large : the subject of this issue is clealy to delete unnecessary nodes, the title "simplify ways ' could mean everything so nothing in particular. A lot of time you have change the title of issue I have proposed, maybe you could improve the title of 3116 ?
Best regards
