### ISSUE TITLE
False delete of ways

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5609]
Hi,

a very small bug, I'm pretty sure you will close this issue very quickly, lol.

If we merge 2 ways because they have the same informations, when we save the modification, we have a warning saying that we are deleting a line, that everybody will see our modifications and asking to confirm.
But to merge is not delete : all the nodes are there, all the informations are there, nothing desappeared except that before we had 2 small ways and after that only one bigger.

Best regards

**Comment by bhousel** [comment]
> But to merge is not delete : all the nodes are there, all the informations are there, nothing desappeared except that before we had 2 small ways and after that only one bigger.

Oh sorry, I don't think this is something that we can change.  Merging multiple ways does necessarily delete all but one of them.
