### ISSUE TITLE
Place of Worship preset: "Religion" field disappears after filling-in some data

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5611]
see movie:
![pow](https://user-images.githubusercontent.com/27923772/50050608-7836dd00-0100-11e9-800b-dd98a63c4bd9.gif)

**Comment by bhousel** [comment]
cc @quincylvania

**Comment by qsmmorgan** [comment]
Hi @my-na-me! So it looks like it’s working as intended, but I can see how it is confusing.

When you set the religion, the preset subtlety updates from Place of Worship to Church, which has the same fields except for Religion. We might improve this by calling the latter preset Christian Church and/or keeping the Religion field around so people can easily view or correct the religion tag.

**Comment by quincylvania** [comment]
Hi @my-na-me! So it looks like it’s working as intended, but I can see how it is confusing.

When you set the religion, the preset subtlety updates from Place of Worship to Church, which has the same fields except for Religion. We might improve this by calling the latter preset Christian Church and/or keeping the Religion field around so people can easily view or correct the religion tag.

**Comment by bhousel** [comment]
> When you set the religion, the preset subtlety updates from Place of Worship to Church, which has the same fields except for Religion. We might improve this by calling the latter preset Christian Church and/or keeping the Religion field around so people can easily view or correct the religion tag.

Oh yeah good catch @quincylvania ..  I like the proposed solution to make these presets less confusing.

**Comment by RudyTheDev** [comment]
I think the preset selector button should visibly highlight itself briefly whenever it gets changed other than directly.

**Comment by bhousel** [comment]
I made these changes per above comments:
- Make sure the "religion" field will not disappear (I added it for all the religion-specific amenities)
- Make sure that the religion appears in the preset label (e.g. renamed "Church" -> "Christian Church")
