### ISSUE TITLE
relation member highlighting don't disappear after delete of entire relation or also single relation member

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5612]
Thank you very much for the recent implemented great feature of highlighting relation members. This makes editing of relations really much more easier :-)

After delete of an entire relation, the highlighted objects should be switch to non-highlighted status?

![relation hihglighter](https://user-images.githubusercontent.com/27923772/50050767-15941000-0105-11e9-953f-854066ac37b6.gif)

Similar issue seems to occur when deleting a single relation member. See movie below:
![relation member hihglighter](https://user-images.githubusercontent.com/27923772/50050989-35c5ce00-0109-11e9-920f-847a0f7cfd62.gif)

**Comment by slhh** [comment]
@bhousel @maxgrossman 
Please reopen, the issue wasn't fixed.
I have just reproduced both variants of the issue with Firefox and Edge on Windows 10.
