### ISSUE TITLE
Source of tiles for OS 1:25k historic

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5615]
Abstract: please consider switching the source of tiles for this background.

OS 1:25k historic (OSM) has made a re-appearance.  Which is good, because although it's old information it has details that are useful, such as footpaths and old names.  That info has to be interpreted with care, but it provides clues as to what might be there now.

However, this background has always had problems because not all sheets were available when the tiles were created from National Library of Scotland sources.  If you happen to live in the wrong part of the UK (I do) then there are many missing tiles.  Take a look at [this part of the map](https://www.openstreetmap.org/edit#map=10/51.9433/-4.4800) with the OS 1:25k historic background.  Not good. :(

However, I found an alternative source of tiles in the editor layer index back when this background went walkabout.  These come from the NLS's own digitization of the OS maps.  Using https://geo.nls.uk/mapdata2/os/25000/{zoom}/{x}/{-y}.png as a custom layer gives me a background with full coverage.  I think their offset from true position may be a little greater than the OSM version, but that's OK.

So, would you consider either switching to the NLS version or offering both?  I can cope if you don't because I found out how to make use of the custom layer and found the NLS version in the editor layer index.  Other mappers may not figure out to do those things.

**Comment by boothym** [comment]
I think that background url you've provided is already in the editor-layer-index under the 1937-61 name: https://raw.githubusercontent.com/osmlab/editor-layer-index/f20589a74fd20e78c4222304f9148ce7c79c1a18/sources/europe/gb/NLS-OS125k1stSeries1937-61.geojson

However the only reason that the **OS 1:25k historic (OSM)** layer is available in iD is because there is no end_date parameter in the editor-layer-index file. If that was added, then iD would hide it - like the rest of the old OS maps - because it is > 20 years old. 

As you say - new mappers might not realise where to get the custom layers. See  #3453 where I raised this issue originally.

**Comment by eehpcm** [comment]
@boothym 

>I think that background url you've provided is already in the editor-layer-index under the 1937-61 name

I don't know which is the officially preferred URL but the one I use is a lot shorter.  I found mine at  [the interactive layer index](https://osmlab.github.io/editor-layer-index/) and assumed it was the official way of doing it.  If not, it still works. :)

> However the only reason that the OS 1:25k historic (OSM) layer is available in iD is because there is no end_date parameter in the editor-layer-index file. If that was added, then iD would hide it - like the rest of the old OS maps - because it is > 20 years old.

That is sensible for aerial imagery.  In my area Bing is 2012-2013 and Esri is 2016.  There is a small housing estate in town which is incomplete in Bing and complete in Esri (well, after getting house numbers by surveying it, it's clear that more houses are/were planned, but Esri matches what's on the ground right now).  Going back further with aerial imagery would rarely be useful.

However, for OS maps, the 1:25k historic **is** useful.  Not all the time, but occasionally.  It shows heights of peaks, which OpenData StreetView rarely (never?) does.  It has names for some very small settlements which are not shown on OD SV but which are used in current postal addresses.  It allowed me to correct a very short segment of the path of an already-mapped abandoned railway.  By showing me an old road layout it allowed me to figure out that a section of road that was mapped as part of Castle Street was actually Tenby Road, as postal addresses for some of the houses implied (Tenby Road essentially got bypassed by a new section of road and the layout changed so part of Tenby Road appeared to be a direct continuation of Castle Street).  More importantly, it shows footpaths, most of which are still valid (and visible in aerial imagery if you know they're there) and few of which (unless they pass through woodland) can be inferred from OD SV.

I know non-custom backgrounds, if used while making changes, get added to changeset details.  What happens with a custom layer?  Do I need to add a source tag to each object I add using that layer?  That would not meet the goal of making iD easier to use.

The 1:25k historic is **useful**.  Especially the version I'm currently using as a custom background which doesn't suffer from the missing sheets problem.  I think we need either separate cut-off dates for maps and aerial imagery, or a historic background sub-menu, or a warning pop-up when selecting an older background, or something.  Because, as has been repeatedly pointed out in #3453, these older OS maps are **useful**.

**Comment by bhousel** [comment]
Closing here as this is already covered on #3453 , which remains open until someone builds a friendly way of letting users filter or customize the imagery list.
