### ISSUE TITLE
Improve prominence of warning that changes won't be visible immediately

### ISSUE THREAD

**Issue by shiftee** [openstreetmap/iD#5616]
As can be seen in [the FAQ](https://wiki.openstreetmap.org/wiki/FAQ#I_have_just_made_some_changes_to_the_map._How_do_I_get_to_see_my_changes.3F) and on reddit, users are regularly asking why their changes aren't visible after saving their changeset.

After saving a changeset a message is displayed saying your changes should be visible within a few minutes.
Many first-time users seem to miss this.
It is also only sometimes true, and definitely not at all zoom levels.

Perhaps the text could be changed to something like:
Your changes should **begin to** appear ...

Would it be possible to highlight this text in red for novice users (e.g. less than 5 changesets)?

**Comment by bhousel** [comment]
Sorry but I'm going to close here as I'm pretty happy with the current screen.  We link directly to the FAQ.

If we bold something or make it red, users will think it's an actual problem that matters, and it's really not.  

It's ok for people to not know these details about OSM within their first few edit sessions and to ask questions about it on Reddit.

![screenshot 2018-12-19 11 51 23](https://user-images.githubusercontent.com/38784/50234783-71200100-0384-11e9-8343-5b97e28c9f6a.png)

**Comment by shiftee** [comment]
No worries
