### ISSUE TITLE
Field autocomplete can overwrite input

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#5618]
When entering custom tag data, there is a condition in which the autocompleted key or value will overwrite the user input after the type something else.  
Similar to #2376.

### Steps to Reproduce
 - Start typing in something that will autocomplete
 - Allow the highlighted autocomplete text to appear
 - Keep typing through that, but anything different than was going to autocomplete
 - Tab into the next field

What you typed will be gone and replaced by the autocompleted text.

Tested in Vivaldi and Firefox on Ubuntu 18.04.

**Comment by bhousel** [comment]
Thanks @rivermont , sounds like a bug

**Comment by bhousel** [comment]
I think this was fixed in #5637?
