### ISSUE TITLE
Error Message: Website under heavy load (queue full)

### ISSUE THREAD

**Issue by cliffordsnow** [openstreetmap/iD#5621]
Trying to upload change to OSM received a message that the website is under heavy load. 

![id error heavy load](https://user-images.githubusercontent.com/3290977/50130144-0d38f380-0231-11e9-8c6b-ed3f5999993a.png)

This issue isn't about the error - just that the error message has html tags ```<h2>  <p>```

**Comment by mmd-osm** [comment]
Looks like a duplicate of #3366

**Comment by cliffordsnow** [comment]
it looks like it. I'll close this issue.
