### ISSUE TITLE
uiDisclosure rendering contents extra times?

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5625]
Looks like there may be a regression that causes the expandable sections of the Background or Map Data panes to re-render multiple times as the user expands and contracts these.

Maybe related to recent commit 222b3f1b0

cc @quincylvania investigating

**Comment by quincylvania** [comment]
I _think_ I fixed this in https://github.com/openstreetmap/iD/commit/6e1dd344471b8a9f9f96fae3a703c5edab42fccf

**Comment by bhousel** [comment]
I guess in this case it might be up to the `content` to make sure it doesn't re-render.. 
(by using the data-bound-to-[0] singleton trick)

**Comment by bhousel** [comment]
Assuming this is fixed..
