### ISSUE TITLE
Better test coverage for modules/validations

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5628]
Continuing the theme of improving iD validation for our hack week..
We don't currently test any of the code under `modules/validations`, and it would be great to improve this!
cc @wonga00 

<img width="203" alt="screenshot 2018-12-19 11 11 06" src="https://user-images.githubusercontent.com/38784/50232401-d7098a00-037e-11e9-8c65-57d261ee2531.png">

**Comment by quincylvania** [comment]
We now have tests for most validation types. Hooray! (Not `maprules` or `many_deletions`.) Let's close this but continue to add tests for all new validations as well as more cases for those already covered.
