### ISSUE TITLE
Allow "continue" for joined nodes

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5633]
**Usecase:** I want to change a junction to a roundabout. So I need to split the roads and re-join them, continuing some roads with new nodes.

**Issue:** The continue feature is only available for roads that are not connected to another road.

**Example a:**
Road connected to other road, so no continue.
<img width="188" alt="bildschirmfoto 2018-12-20 um 07 53 04" src="https://user-images.githubusercontent.com/111561/50268829-894b5b00-042c-11e9-9baa-7a666efdaa36.png">

**Example b:**
Road connected/glued to area - here we have a continue.
<img width="423" alt="bildschirmfoto 2018-12-20 um 07 53 55" src="https://user-images.githubusercontent.com/111561/50268841-98caa400-042c-11e9-9741-9ea4a6218524.png">

**My case:**
<img width="318" alt="bildschirmfoto 2018-12-20 um 07 44 47" src="https://user-images.githubusercontent.com/111561/50268861-a1bb7580-042c-11e9-9825-decfa28cb858.png">

I want to continue the road even though there is a crosswalk and a connected footway attached to the end. Note: I did hide the areas for this screenshot, there are glued areas on the crossing as well.

**Solution in GoMap**

In https://github.com/bryceco/GoMap the solution to this is …
- first click the road you want to continue
- second click the node you want to continue
- then continue

|    |   |
| ------------- | ------------- |
|   ![img_0237](https://user-images.githubusercontent.com/111561/50269306-2b1f7780-042e-11e9-842c-30a5684650f3.png)  |  ![img_0238](https://user-images.githubusercontent.com/111561/50269320-35417600-042e-11e9-93ab-e32c6fe284ce.png)   |

**Current workaround**

I need to split and disconnect the elements, continue the road and put it all together again afterwards.

**Comment by bhousel** [comment]
iD does support this - you just need to select the vertex and the line you want continued together (with shift-click)

<img width="419" alt="screenshot 2018-12-20 02 18 51" src="https://user-images.githubusercontent.com/38784/50269860-ae74a500-03fd-11e9-98d0-5e1c51ec7b87.png">

**Comment by tordans** [comment]
Oh, wow. And its written right there in the tooltip too. 🤦‍♂️ 

What do you think about improving the wording so something like …

> Several lines can be continued here. To choose a line, press the Shift key and right click on the line you want to continue.

Otherwise I unselect the line again and need to start over.

**Comment by bhousel** [comment]
I think the wording is ok.. Generally I think a string needs to be really wrong to necessitate changing it, because doing so means all the translations have to change and that is more work for our volunteers.
