### ISSUE TITLE
Direction confused on city_limit sign

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5634]
Case: There is a road which is glued to the area next to it.

This is here: https://www.openstreetmap.org/edit?way=198948464#map=20/50.81705/6.37598

The direction indicator seems to be confused by the glued area + road.

_no direction:_
<img width="160" alt="bildschirmfoto 2018-12-20 um 08 15 00" src="https://user-images.githubusercontent.com/111561/50269838-e85e9f00-042f-11e9-8f79-c183b9eb5943.png">

_traffic_sign:direction=backward_
<img width="119" alt="bildschirmfoto 2018-12-20 um 08 14 46" src="https://user-images.githubusercontent.com/111561/50269859-f90f1500-042f-11e9-86d6-307ed64efd63.png">

_traffic_sign:direction=forward_
<img width="147" alt="bildschirmfoto 2018-12-20 um 08 14 54" src="https://user-images.githubusercontent.com/111561/50269865-00362300-0430-11e9-97dd-762a1999c240.png">

_traffic_sign:direction=both_
<img width="125" alt="bildschirmfoto 2018-12-20 um 08 18 26" src="https://user-images.githubusercontent.com/111561/50269831-e399eb00-042f-11e9-944b-05fd0f2c28b5.png">

Workaround: 
- unglue the node, which duplicate the sign-tag to the area as well as the road.
- move them around to see both
- remove the wrong sign tag on the area
- move the road back and find a new place for the area node

**Comment by bhousel** [comment]
I think the best thing to do here is just unglue the road from the landuse

**Comment by tordans** [comment]
In the spirit of documenting edge cases:

This issues does happen as well, when using `area:highway` with `highway=traffic_signal`. Ungluing those is not a good solution.

Example: https://www.openstreetmap.org/edit?note=3490280#map=20/52.48743/13.43160

---

This came up in a different context as well (https://www.openstreetmap.org/note/3490280). It looks like Garmin Navis do have similar rending effects as iD. The notes talk about a Garmin navi that showed 4 traffic lights instead of one.

**Comment by SupaplexOSM** [comment]
fyi: I just started [a thread in the forum](https://community.openstreetmap.org/t/direction-errors-in-applications-when-direction-dependent-nodes-e-g-traffic-signals-are-shared-with-areas-e-g-area-highway/7301) on this phenomenon.

**Comment by 1ec5** [comment]
#9013 tracks another case of this issue involving stop signs and non-roadway lines.
