### ISSUE TITLE
Two nodes in the same place: provide a way to specify which to move

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5635]
_Usecase:_ In https://github.com/openstreetmap/iD/issues/5634 I want to move the area, not the node, after un-glueing them. However, iD will always move the road, when I click on the node.

_Possible solution:_ When I click the area first and then the node, I move the node. See screenshots and description from GoMap in https://github.com/openstreetmap/iD/issues/5633 at the end of the issue.

**Comment by bhousel** [comment]
#1239
