### ISSUE TITLE
Improved save flow (with change highlighting)

### ISSUE THREAD

**Issue by samanpwbb** [openstreetmap/iD#564]
We should scrap the save modal and do this:

![Screen Shot 2013-01-30 at 11 20 26 AM](https://f.cloud.github.com/assets/108094/111520/383a51b2-6af9-11e2-877d-9d8876763ee7.png)

Advantages:
- Allows users to inspect their changes as part of the commit process, without leaving behind the commit panel.
- Clean way of integrating #538 & #549 into the UI
- Less ambiguity about "accidentally" making big changes. You'll know if you made a big change before saving. This'll give new users more confidence in actually committing their changes.

**Comment by bhousel** [comment]
@samanpwbb  this can be closed, yes?

**Comment by aaronlidman** [comment]
Still a big fan of that dark UI :sunglasses:

**Comment by samanpwbb** [comment]
Wow, this is really old!
