### ISSUE TITLE
Allow to overwrite editor language via URL

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5644]
I would be great to specify the language for iD, so I can test it the way most code contributors see it and make screenshots for issues that everyone understands.

Some research
- In https://github.com/openstreetmap/iD/issues/1666 (2013) is was said this is already possible, but I don't think that is true anymore, since I dont see any URL param
  - UPDATE: Its possible via the preferred language input on the OSM website user profile. See https://github.com/openstreetmap/iD/issues/3842 for an old screenshot of this UI element.
- I guess https://github.com/openstreetmap/iD/blob/master/modules/util/detect.js#L62-L63 is the place that handles the language

Suggested solution
- An optional URL param `language=en` to force the editor to english

**Comment by bhousel** [comment]
done in #5650
