### ISSUE TITLE
Aborting wikipedia entry adding removed wikidata

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#5648]
Element has only wikidata entry. I try to add the corresponding wikipedia. The is no help from the editor, but this is another story.
Situation is this ([osm](https://www.openstreetmap.org/way/103017862)) and i click on this drop down menu:
![image](https://user-images.githubusercontent.com/2410353/50375643-fdd6f300-0600-11e9-9cc3-6e24db973f07.png)

The drop down menu has no useful entry so I click away. Or we have a focusout because i switch browser window (to fill this issue :-)
Drop down menu closes => no wikipedia entry added, but wikidata is removed, too!

related but different #4322 @matkoniecz

**Comment by bhousel** [comment]
Can we please just capture all this on #4322
We have too many issues as it is.
