### ISSUE TITLE
highway=crossing has wrong "unmarked crossing" description 

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/iD#5652]
Hi,

`highway=crossing` has wrong description "Uncontrolled crossing". Uncontrolled crossing is `crossing=uncontrolled`. `highway=crossing` is umbrella for all crossings, often controlled ones too.

Context: https://github.com/openstreetmap/iD/commit/1ffca3ce85d630539c7ebb11454a91770bd76536

**Comment by bhousel** [comment]
Can you share a screenshot?

I think “Uncontrolled” has been used very inconsistently, and I didn’t think iD is anymore calling them that in the UI anymore. 

Ideally people would remap these as `marked` or `unmarked`, to resolve the ambiguity. 

There are lots of old tickets that you can read about this - I don’t feel like looking them up right now.

**Comment by tohaklim** [comment]
I believe this is what @Komzpa is referring to:
![image](https://user-images.githubusercontent.com/7071423/50388135-f574da00-071e-11e9-8597-6c7de55b984c.png)
Both options have the same generic description and the same wiki link. I am not necessarily against cleaning up crossing tags, but not sure if auto-completing a `crossing=marked` tag that is not even on the wiki is best? The aforementioned wiki page already has one example of iD introducing a questionable preset with `crossing=zebra`

**Comment by 1ec5** [comment]
If you select a feature that’s only tagged `highway=crossing`, or perhaps one that’s tagged `highway=crossing` `crossing=traffic_signals`, iD uses the Unmarked Crosswalk preset. It used to be that `highway=crossing` without a `crossing=*` tag would use the generic Pedestrian Crossing preset without referring to whether pavement markings are present, but the generic preset has been renamed to use the same title as the `crossing=unmarked` preset. I believe that’s what @Komzpa is referring to, not the fact that the documentation is identical between the two presets.

`highway=crossing` only | `crossing=unmarked`
----|----
![generic](https://user-images.githubusercontent.com/1231218/50388242-17da0980-06c5-11e9-844c-bf43e8e876de.png) | ![unmarked](https://user-images.githubusercontent.com/1231218/50388240-14df1900-06c5-11e9-808f-5255da26e94e.png)

Currently, the user has to pick between Marked Crosswalk and Unmarked Crosswalk when adding a new feature; there isn’t a generic Pedestrian Crossing preset to pick from anymore. But this edge case with the generic preset can come up when selecting an existing feature that only has the `highway=crossing` tag, or when changing the Type field to something other than `marked` or `unmarked`.

> The aforementioned wiki page already has one example of iD introducing a questionable preset with `crossing=zebra`

For what it’s worth, iD no longer introduces `crossing=zebra`. You could say `crossing=marked` was an attempt to fix the bug where iD added `crossing=zebra`. 😉

/ref https://github.com/openstreetmap/iD/issues/5205#issuecomment-435623938

**Comment by batyrmastyr** [comment]
It's was a good idea to fix legacy "zebra" with undocumented and upsupported "marked" trash (as of october).  
```
uncontrolled    | 661 122
zebra           | 525 573
traffic_signals | 514 832
marked          |   8 422
```

**Comment by Komzpa** [comment]
Thanks @tohaklim and @1ec5 for screenshots, yes, that is exactly the issue I was posting about.

**Comment by bhousel** [comment]
#5647 will fix the documentation issue, because then people will be able to make those descriptions say whatever they want to, instead of having the documentation show the generic text and image.
