### ISSUE TITLE
Where can I change names on boxs?

### ISSUE THREAD

**Issue by riajuu** [openstreetmap/iD#5655]
Hello.

Could somebody tell me where I can change names such as "읍/면/동" in below? Because some names on boxs are wrong, like https://github.com/openstreetmap/iD/issues/3802 and https://www.openstreetmap.org/user/garam+/diary/40591 So, I tried to find names on boxs on translatewiki and OSM wiki, but I could not find it. (Separately, I think name's explanations come from parameter "description" on OSM wiki.) And transifex's link on https://github.com/openstreetmap/iD/issues/3802 is already broken.

![image](https://user-images.githubusercontent.com/26794295/50399364-3b36ae80-07c2-11e9-9ee1-804e864b9a70.png)

Thanks.

**Comment by manfredbrandl** [comment]
See 
https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating

**Comment by riajuu** [comment]
@manfredbrandl Oh, thanks for your answer!

**Comment by riajuu** [comment]
@manfredbrandl Umm, I have one more question. Do you know how to create new language (e.g. "ko-kp" on mediawiki) on OSM? Thanks.

**Comment by riajuu** [comment]
And I want to improve address box on Korea like Japan style. Do you know how to improve it?

![image](https://user-images.githubusercontent.com/26794295/50400407-cff0da80-07c9-11e9-8ef2-219ab39c181a.png)

Thanks.

**Comment by manfredbrandl** [comment]
@riajuu There are more than 1.000 strings still untranslated for korean, so please reconsider introducing a variant of that. The Adresse Style per country is not part of the translations but somewhere in the source.

**Comment by bhousel** [comment]
Hey @riajuu  - I can create a separate locality for `ko-kp` on Transifex, but we only do this if there are significant differences from the `ko` strings.  Let me know if that's the case.

**Comment by riajuu** [comment]
@bhousel Sometimes it is different. Please see https://translatewiki.net/w/i.php?title=Special:Translate&language=ko&suppresscomplete=1&group=%21additions&filter=translated&action=translate and https://translatewiki.net/w/i.php?title=Special:Translate&language=ko-kp&suppresscomplete=1&group=%21additions&filter=translated&action=translate

**Comment by bhousel** [comment]
Sorry @riajuu - I just checked and it looks like `ko-kp` isn't supported on Transifex, so I can't add it as a separate language after all.  See list here:  https://www.transifex.com/explore/languages/

However you can still customize the address field  - just send a pull request with a change to this file:
https://github.com/openstreetmap/iD/blob/master/data/address-formats.json

**Comment by riajuu** [comment]
I think "ko_KR" may be an incorrect form of "ko_KP"...

And thanks for your help about address format. I will make a consensus on https://forum.openstreetmap.org/viewtopic.php?id=64892 , and then I will tell you the result.

Finally, do you know where I can change postpositional particle name, such as particle "and" ("와(과)" in Korean) of Map Key (i) on the right side at www.openstreetmap.org ? We, Korean users want to change particle "와(과)" to "및", but we don't find it on Translate Wiki and Transifex. https://translatewiki.net/wiki/Thread:Portal_talk:Ko/%E2%80%98%EC%99%80(%EA%B3%BC)%E2%80%99

Thanks.

**Comment by bhousel** [comment]
> Finally, do you know where I can change postpositional particle name, such as particle "and" ("와(과)" in Korean) of Map Key (i) on the right side at [www.openstreetmap.org](http://www.openstreetmap.org) ? We, Korean users want to change particle "와(과)" to "및", but we don't find it on Translate Wiki and Transifex.

Not really sure but this looks like the code to build the map key:
https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/site/key.html.erb

It's complicated because it uses the Rails [`to_sentence()`](https://apidock.com/rails/Array/to_sentence) function, which I guess will take an array of things and put the "and" at the end of it.  You could ask on the [openstreetmap/openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website) repo, or https://help.openstreetmap.org/ and maybe someone there would know more.
