### ISSUE TITLE
Suggestion: option to remove social media links post-save

### ISSUE THREAD

**Issue by mini-ika** [openstreetmap/iD#5657]
Hi there,

At present, iD shows me links to social media sites such as Facebook after I save, but I really abhor social media because of all the ongoing problems (fake news and poor community atmosphere).

I wonder if someone could add the option to hide social media links post-save, aka “Do not show this again”?

**Comment by manfredbrandl** [comment]
@mini-ika These links are provided from the OSM-Community (local to global), see 
https://github.com/osmlab/osm-community-index to allow mappers to get into contact with others. Isn‘t that a good idea?

**Comment by mini-ika** [comment]
I understand that such links are useful for new mappers, and I never implied that it should not appear by default.

However, I made a suggestion for serial iD mappers who may get bored of seeing such links, particularly when they have no faith in using social media.

I hope I am not putting too much pressure on you.

**Comment by Adamant36** [comment]
I have over 10,000 edits and I didnt even notice they were there until I saw this issue. So Im not sure its such a problem for "serial" mappers. As its easy to ignore.

**Comment by mini-ika** [comment]
To me it is an annoyance, but your mileage may vary.

I will voluntarily close the comment with a uBlock Origin filter that I found out this afternoon:

`! OpenStreetMap (no social media links)`
`openstreetmap.org##div.save-communityLinks`

**Comment by bhousel** [comment]
Thanks @mini-ika - We also have #5225 to track splitting up the index better.  I might add something to hide links.
