### ISSUE TITLE
Text of trace notes cut off

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5665]
Here the user is trying to extract the text of a trace note.
![df1](https://user-images.githubusercontent.com/1230959/50554786-23988200-0cfc-11e9-94d2-323e894f6123.jpg)
As the text is more than a few words, he has to pull the window wider to extract.
But it turns out the text is just too long, he cannot extract it all.

Solution: Instead of putting "..." in the box, put the whole text, wrapped.

**Comment by bhousel** [comment]
#5444
