### ISSUE TITLE
(Translation) Chemist is not "parapharmacie'

### ISSUE THREAD

**Issue by Rpnpif** [openstreetmap/iD#5671]
shop=chemist is translated in french as "parapharmacie". But it is not a parapharmacie in France.
In France, Parapharmacie is  a phamacy without a medical prescription needing.
shop=chemist is as a drug-store, "une droguerie" which sell chemical product for cleaning, brooms and brushes.
In France, a "droguerie" does not sell usually perfume or cosmetics.

Please, fix the translation.

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/openstreetmap/id-editor/dashboard/), so you can sign up for an account there to fix issues with the translations.
