### ISSUE TITLE
buttons bar that appear after right clicking an element is not displayed at the right place

### ISSUE THREAD

**Issue by phiphou** [openstreetmap/iD#5672]
Sometimes, buttons bar that appears after right clicking an element is not displayed at the right place.

Here, when I right click on the element, the delete button is not placed at the right position. It happens randomly, I was not able to provide a reproductible example. 

![sans-titre-4](https://user-images.githubusercontent.com/364418/50574024-a8a89780-0ddf-11e9-9708-8fce764839e7.jpg)

**Comment by quincylvania** [comment]
A lot has changed with the related code since this issue was filed. I haven't been seeing the bug so I'm closing this unless it reappears.
