### ISSUE TITLE
Add presets for highway=stop and highway=give_way

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5673]
As mentioned in title subject, see also wiki pages for both objects:

highway=stop
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstop
![200px-stop_sign](https://user-images.githubusercontent.com/27923772/50576180-0fdc4100-0e0c-11e9-9ed3-f2e9cb69fbd0.jpg)

highway=give_way
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dgive_way
![200px-give_way](https://user-images.githubusercontent.com/27923772/50576184-2a161f00-0e0c-11e9-8539-f321f9432aa6.jpg)

**Comment by bhousel** [comment]
iD has these already.. Can you try assigning the presets to a node that is already along a way (in the preset definitions we call this geometry a ‘vertex’)
