### ISSUE TITLE
Open help menu by pressing Persian equivalent of question mark

### ISSUE THREAD

**Issue by iriman** [openstreetmap/iD#5675]
In Persian keyboard layouts we have this char `؟` for question mark.
It is in the same place as the key `?` and we write it by holding down the `Shift` key, just like English.
But when I type `؟`, it toggles minimap.
It would be so good if we can use both of them to open the help pane.

**Comment by manfredbrandl** [comment]
You can „translate“ the shortcut key on Transifex 
https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating
You can test the latest translations: http://preview.ideditor.com/master

**Comment by 1ec5** [comment]
Specifically, the keys to translate are `help.key` and `minimap.key`.

**Comment by bhousel** [comment]
@iriman - try out the suggestion by @manfredbrandl and @1ec5 and let us know if that works.

**Comment by iriman** [comment]
Oh, sorry guys. I lost access to my PC for some days. I will check it as soon as possible.
Thank you for your really quick & kind guide.

**Comment by iriman** [comment]
Finally I get back to my PC :)
I translated `shortcuts.toggle.key` to `؟`, but now if I press `?` it has no reaction. 
It's best to have both `?` and `؟` shortcuts enabled, since mostly every one with a Persian keyboard layout has an English one, too. So every time we should check if it's Persian or not to have a working shortcut key.

To explain more precisely, now we have `H` for `help.key`.
Its translation is the same as source string: `H`.
On my Persian keyboard, the character alef (`ا`) is at the position of key `h`. 
If I press `h` or `ا` (alef) on my keyboard, help pane will be opened.

**Comment by bhousel** [comment]
ah ok, this will need something like I did for #5663 then.
