### ISSUE TITLE
Add "Edit Profiles" to focus on certain problems

### ISSUE THREAD

**Issue by Mannshoch** [openstreetmap/iD#5676]
As an example you could create a "Street" Profile where you could edit Streets and get more visual help than usually.
![grafik](https://user-images.githubusercontent.com/7795891/50695086-f4f01380-103b-11e9-8067-57e204233dae.png)

**Comment by bhousel** [comment]
I'm going to close here as it's not a really actionable issue, but I agree that allowing users to focus on runtime validation or detail mapping is useful and we'll be adding more things like this to iD.
