### ISSUE TITLE
Display barrier=bollard with appropriate access tags

### ISSUE THREAD

**Issue by famo** [openstreetmap/iD#5677]
According to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard) for `barrier=bollard`
the implied access tags are:
`access=no`, `foot=yes`, and `bicycle=yes`.

So it would be nice if iD would actually display these. :-)

See also issue #4344.

**Comment by bhousel** [comment]
Yes this is #4344
