### ISSUE TITLE
multipolygon invisible

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#5680]
Hi,

I have 2 pbs, one with ID and the other one with OSM. I open 2 issues, with the same text because my "story" mixes both.
I wanted to add a relation to a polygon (in ID) : the relation (multipolygon) is a very big one (scrub) and I'm in the middle, very far from the outer and from any inner. Visible here :
https://www.openstreetmap.org/query?lat=-27.70305&lon=-66.00780

1) when I select the polygon and go in its relations' part, the scrub is not listed : when zooming out (losing the possibility to edit the polygon), I found the outer line, found the number of the relation. But when I come back to the polygon (zoom in) and put this number in the relation, nothing happens. How to add a relation if the wanted relation is not listed and you can not add its number ?
2) Before to zoom, I opened a new tab (right click on the title "openstreetmap") to be out of ID but in the area of the polygon (see link above). I use the last button on the right (request on the objets) on the scrub. Result : the request don't see the scrub. The request sees the administrative limits and nothing else. But on the map we see only one (or almost) thing : the scrub, lol. Even if I found how to have the number of the scrub (see point 1), I think it should be better that the request find it directly.

Best regards
Mahab

**Comment by bhousel** [comment]
Thanks for the suggestion - I think this is #3487 / #3622

**Comment by Mahabarata** [comment]
My comments :
- #3622 was opened more than 2 years ago and no one is assigned to this issue. You can keep it like that because for me it is not the good solution for my pb and, more, it is not a real pb (and I agree with your comments in this issue)
- #3487 is clearly my pb. The solution is inside :
https://github.com/openstreetmap/iD/issues/3487#issuecomment-253847048
But today it doesn't work : I try for the polygon of my isssue. In the relation part, I added "r+number_of_relation" and I complete with "inner" and then nothing happened, the relation was not added (if I click outside the polygon and then back to the polygon, the relation I just added is not there).
So, if it was working in 2016, you will need to fix this because it is the good solution, very natural and very simple.

But there is another solution (new point 3 in my first message) :
- in the relation, you have the list of the members. If you can not add a relation to an object, you should be able to add a member to a relation : just need to add a <select> with the kind of object (node, way, relation) and an <input type='number'> to add the id of the object.

Best regards

**Comment by bhousel** [comment]
Hey @Mahabarata when you say "pb" you mean "problem" right?  Can you just type out "problem"?  
I don't mind really, but your issues are likely to confuse other people.

Also, it's not nice to complain about the pace of development on an open source project.  If you want the problems solved faster, you can dig into the code yourself and learn how it all works.

**Comment by Mahabarata** [comment]
yes, pb = problem, sorry. In french everybody uses these 2 letters rather than the complete word, I have not the habit of your language.
I don't complain about your project, I do love it ! And I saw that KeepRight will be there in a short time, very good improvement, thanks to you.
I just said that you have closed my issue because of the other one, that in the other one someone said it was working with 'r+number" which is perfect for me, in the next comment you said "nice" so I think you tested it in 2016 and was agreed that it was working, no ? But today when I do the test it doesn't work anymore. Not a complain, just a real fact that I thought you would like to know to make your choices of the developments of ID.
I would be very happy to help you in your project but I still do this with another one.
Best regards
