### ISSUE TITLE
Add English names to Japanese POIs with wikidata tags

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#5681]
It should be possible to extract the English name of Japanese POIs if they are using Wikidata tags. For example, the shop ダイソー is present in the name-suggestion-index, and pulls the Wikidata and Wikipedia tags correctly, and it would be more useful to pull its English name, by adding `name:en=DAISO`.

**Comment by bhousel** [comment]
> It should be possible to extract the English name of Japanese POIs if they are using Wikidata tags. For example, the shop ダイソー is present in the name-suggestion-index, and pulls the Wikidata and Wikipedia tags correctly, and it would be more useful to pull its English name, by adding `name:en=DAISO`.

I'm not sure what you're asking.   The name-suggestion-index already includes an entry for Daiso with a `name:en` tag:

```
  "shop/variety_store|ダイソー": {
    "count": 395,
    "countryCodes": ["jp"],
    "match": ["shop/variety_store|ザ・ダイソー"],
    "tags": {
      "brand": "ダイソー",
      "brand:en": "Daiso",
      "brand:wikidata": "Q866991",
      "brand:wikipedia": "ja:大創産業",
      "name": "ダイソー",
      "name:en": "Daiso",
      "shop": "variety_store"
    }
  },
```
So if a user picks this preset, the `name:en` tag should be set.

Are you asking iD to set the tag automatically on existing features, if the tag is missing?  I think it would be useful for iD to suggest tag upgrades like this to users (#4591 which I closed), but I think most people don't want iD automatically changing things.

**Comment by picsi** [comment]
You're right, for some reason I missed the fact that it adds an :en name. Sorry for the confusion!
