### ISSUE TITLE
Add Osmose Q/A layer

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5682]
Following #5201 - we can add a Q/A layer for [Osmose](http://osmose.openstreetmap.fr/en)

Some information about the ruleset and API can be found on the [osm wiki](https://wiki.openstreetmap.org/wiki/Osmose).

The list of checks that Osmose performs is [here](https://wiki.openstreetmap.org/wiki/Osmose/issues) - we'll want to support a reasonable subset of these.

Similar to KeepRight, we can just pick a single marker style and a few colors to differentiate, rather than trying to match the literal osmose icons, which don't seem to mean anything.

<img width="634" alt="screenshot 2019-01-07 12 28 39" src="https://user-images.githubusercontent.com/38784/50783083-d1b1a800-1277-11e9-85b7-b08803ffe73f.png">

**Comment by SilentSpike** [comment]
Osmose API is quite nice as it directly provides array of element IDs related to the error unlike KeepRight. [See "elems" key](https://osmose.openstreetmap.fr/en/api/0.2/error/22013534664).

Full error detail is not provided (by default) when fetching errors from `/errors` unless `full=true` parameter is specified in the query. Unsure whether implementation would want to fetch specific error detail separately when an error is interacted via `/error/ID` as a means to reduce the amount of data transfer or if that's not a big deal.

Just some food for though, I've messed around with my own half-baked implementation of this in the past, but I'm mostly commenting so this appears in my participating notifications 😛

**Comment by tordans** [comment]
For all wo are looking to test this feature, ATM its live at https://2-x--ideditor.netlify.com/#background=Bing&disable_features=boundaries&map=16.94/52.47562/13.44827
