### ISSUE TITLE
Add ImproveOSM Q/A layer

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5683]
Following #5201 - we can add a Q/A layer for [ImproveOSM](https://improveosm.org/)

The three types of errors that it detects are - possible missing oneways, possible missing turn restrictions, and possible missing roads.

There is no documentation for the API, but it seems very simple and similar to the KeepRight API (get issues, mark as fixed/invalid).  They use a fork of an older version of iD, and we can just inspect the network to see with their forked iD does.  

cc @mvexel 

<img width="935" alt="screenshot 2019-01-07 13 36 29" src="https://user-images.githubusercontent.com/38784/50786328-40473380-1281-11e9-86b0-5e9278409d75.png">

**Comment by boothym** [comment]
This would be a good addition, as the improve-osm iD fork is outdated.

**Comment by SilentSpike** [comment]
I have a semi-working implementation of this. Currently only retrieving missing one-ways and turn restrictions as they're easy to locate a specific point for.

Missing geometry issues are presented as a tile filled with points by ImproveOSM, assuming we want to be consistent across services and have errors displayed as an icon at a point, my current line of thinking is to just take an average of those (similar for one-ways which are found as way segments between two given nodes and shown as arrows, currently I just use the node at one end, but the midpoint makes more sense unless we want to display them differently).

Obviously the KeepRight icon shown here is just temporary, if anyone has a more suitable one for ImproveOSM let me know 😃 

![image](https://user-images.githubusercontent.com/5459452/51441250-9a0b1d00-1cc7-11e9-84e3-18c7f44b4fdc.png)

![image](https://user-images.githubusercontent.com/5459452/51441181-cbcfb400-1cc6-11e9-89ce-8715d01ed34c.png)

**Comment by bhousel** [comment]
done in #5739 🎉
