### ISSUE TITLE
Editor becomes unresponsive

### ISSUE THREAD

**Issue by shiftee** [openstreetmap/iD#5690]
Editor become unresponsive if you follow the steps below:

Link: http://preview.ideditor.com/master/#background=Bing&disable_features=boundaries&map=20.36/51.67344/-8.96983&overlays=osm-gps

1. Select node https://www.openstreetmap.org/node/3739112865
2. Type D to detatch
3. Move newly detached road away
4. Re-select node https://www.openstreetmap.org/node/3739112865 on track road
5. Type X to split
6. Delete upper section of newly split track road
7. Click end of road from step 3
8. Type A to append

The following message appears in the Firefox browser console:
Error: entity w-1 not found iD.js:36935:21

**Comment by bhousel** [comment]
I can confirm that I also get this error on Firefox 64 (but not Chrome 71)

**Comment by quincylvania** [comment]
This is likely one of a number of `entity not found` errors I inadvertently introduced in #5583 🙈

I'll attempt a fix on Monday.

**Comment by bhousel** [comment]
no worries @quincylvania - I'm in the code right now.
(I was _just_ about to `git blame` 😆)

**Comment by quincylvania** [comment]
@bhousel I think a quick fix would be to check `hasEntity` before re-rendering on changed tags in `form_fields.js`. But of course it would be better not to re-render on every tag change.

**Comment by bhousel** [comment]
Crash happens because it calls `formFields.tagsChanged()` here, which rerenders the formFields with a stale `_fieldsArr`.  At this point, it's really `null` but `formFields` doesn't know yet, and rerenders the fields for the previous selected thing, which was the way that got deleted, and the combo controls don't like that.

https://github.com/openstreetmap/iD/blob/6c9a57ffceb0a48c763ed4a4fd5c4eb3534b2e27/modules/ui/preset_editor.js#L120-L126

**Comment by bhousel** [comment]
> @bhousel I think a quick fix would be to check `hasEntity` before re-rendering on changed tags in `form_fields.js`. 

sounds good - I will try it!

> But of course it would be better not to re-render on every tag change.

Yeah this is complicated because tag changes can really change anything.  But I agree that we don't want to fire re-renders on input (e.g. user typing in the `name` field) if that's what you mean.
