### ISSUE TITLE
Support public domain icons from The Noun Project

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5691]
I saw this release of [public domain humanitarian icons](https://blog.thenounproject.com/how-the-united-nations-uses-icons-to-help-support-humanitarian-efforts-around-the-world-a51532b68e26
) today - some of them are pretty nice.

[The Noun Project](https://blog.thenounproject.com/) is interesting, and I have mixed feelings about it. 
 Most icons there do not match the style of the other icons that we use in iD, but occasionally there are some that might be useful.

They do have an [API](https://thenounproject.com/developers/) ([docs](http://api.thenounproject.com/)) and it looks like it would allow us to do this:
- use the free tier up to 5000 calls/month
- svg download available for public domain icons (the only ones we'd use anyway)

So I'm considering some limited support for using Noun Project icons as preset icons, as long as they are public domain, and we script occasional downloads into our repo.

**Comment by quincylvania** [comment]
This would be great to do for the next release in order to differentiate more presets. With the favorite preset buttons in #6010 the user has to hover over identical icons to see what the preset is.

<img width="402" alt="screen shot 2019-03-05 at 10 29 34 am" src="https://user-images.githubusercontent.com/2046746/53816687-fc477680-3f31-11e9-8d7a-2d2da0802f2c.png">

**Comment by bhousel** [comment]
This is awesome - Thanks @quincylvania  👏

**Comment by quincylvania** [comment]
@bhousel Yes! It's exciting to have a new icon source. Unfortunately, it looks like most icons on there aren't public-domain and [there's no way to filter by license](https://twitter.com/nounproject/status/1118303303975297024), which makes finding compatible icons difficult. Their API does have a search endpoint where you can filter by public domain, so we could theoretically build a search tool.

I was wondering if we could also use CCBY icons and put the attribution somewhere, but the API won't let you download those SVGs on a free account anyway so there's not much point in looking into it.
