### ISSUE TITLE
Who plans to be at State of the Map 2019, Heidelberg, Germany?

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5696]
I wonder who of those that are active here will be at https://2019.stateofthemap.org/ ?
Maybe we could do a session to work on some part of iD. Some code? Or some wireframing?

>STATE OF THE MAP
September 21 – 23
>
>ADDITIONAL EVENTS
HOT Summit
September 19 – 20

PS: This might be the wrong place for this question :). Maybe move it to https://github.com/osmlab/osm-planning ?

**Comment by bhousel** [comment]
This issue was moved to osmlab/osm-planning#24
