### ISSUE TITLE
Instagram Tagging

### ISSUE THREAD

**Issue by FeelinNice** [openstreetmap/iD#5698]
When I tag my business in my instagram post as a location, the information in text is correct and matches my current business and address. However, When I look at the thumbnail map it shows a map of my old location. Also, If I click the thumbnail it will give me directions to my old location which is incorrect. Is there any way to fix this issue or update my information so the map will stop doing this?

**Comment by bhousel** [comment]
Hey @FeelinNice - every site that uses OpenStreetMap data will import it on their own schedule.  The editor will show the most current data, but other sites will always lag behind.  It might be weeks or months until they update their copy.

https://help.openstreetmap.org/questions/102/i-have-made-edits-but-they-dont-show-up-on-the-map
