### ISSUE TITLE
Hard to distinguish nearby issues on KeepRight layer

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#5702]
Vertical higway=primary (萩津和野線) at the center of the screenshot below is separated at the junction around red circle. And there are two same issues.
![](https://i.imgur.com/bbEnnNE.png)
http://preview.ideditor.com/master/#background=finds.jp_KBN_2500&disable_features=boundaries&map=21.18/34.47166/131.77559
I want to add maxspeed=30 only to upper one, but I can't distinguish which issue points upper one. Isn't OSMID necessary for guidance message to identify correctly?

**Comment by bhousel** [comment]
If you mouseover the linked part in the error message, it should add a highlighting to the way that the error is about, and clicking on that link should select the way.
