### ISSUE TITLE
Please allow translation of 'riverbank' in new keepright-code

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#5703]
![bildschirmfoto von 2019-01-13 13-18-38](https://user-images.githubusercontent.com/5360273/51085192-e984a280-1735-11e9-9d2c-8c56eb73e54b.png)

There is only one 'riverbank' on transifex for translation:
![bildschirmfoto von 2019-01-13 13-20-31](https://user-images.githubusercontent.com/5360273/51085201-10db6f80-1736-11e9-8c4c-2d4bb4f31b6d.png)

**Comment by iriman** [comment]
Also for 'highway'

![image](https://user-images.githubusercontent.com/8467903/51086088-3dec4a00-1757-11e9-94f0-e95626b5aeec.png)
