### ISSUE TITLE
right padding for "member-entity-name" of relations section

### ISSUE THREAD

**Issue by iriman** [openstreetmap/iD#5705]
left padding present in ltr mode:

![en](https://user-images.githubusercontent.com/8467903/51088276-d512cb00-1772-11e9-903b-3162700e4bb7.png)

right padding missing in rtl mode:
![fa](https://user-images.githubusercontent.com/8467903/51088275-d512cb00-1772-11e9-841d-aaa4ab790a15.png)

**Comment by bhousel** [comment]
fixed in #5704
