### ISSUE TITLE
Add more links to the link bar of the inspector

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#5706]
iD has recently got a linkbar in the inspector (https://github.com/openstreetmap/iD/issues/5169#issuecomment-417882031).
In addition to the zoom, the following links or icons could be useful there:

1. Upgrade tags (https://github.com/openstreetmap/iD/issues/4591#issuecomment-453771534)
2. Download an incompletely downloaded relation (#5420). The shown link could also serve as an indicator of incompleteness.
3. Go back to:
    1. the parent relation, when the currectly selected element was selected by clicking an item in the all members section of the parent relation.
    2. the member, when the currect element (a relation) was selected by clicking an item in the all memberships section of the member.
4. Go forward (undo go back)
5. Restore the recent multiselection, when the currect element was selected by clicking an item in the multiseletion list.or any subsequent browsing through all members or all memberships item links.
6. Add the current element to the stored previous multiselection.
7. Add the current element to the stored previous multiselection.  

To prevent cluttering the UI, links should be hidden, when they are inapplicable. Most links are applicable in relatively rare cases only. They would be shown just when they are likely required. 
Typical workflows of a Newbie would unlikely led to activation of links 3. to 7., and activated links would get hidden again quite soon.

**Comment by bhousel** [comment]
I don't want to add a lot of stuff to the top link bar.  I still want to keep the sidebar mostly like

Simple / easy to use / universally understandable
        ↓↓↓
Complex / requires knowledge / fiddly osm details

I'm ok with adding link bars to the other sections though.. e.g. download all relations can go down near the relation parts.

**Comment by slhh** [comment]
> download all relations can go down near the relation parts.

We need to differentiate two different types of usecases for downloading of relation members.

1. When user intends to work with the member list., placing the download link in the all members section seem to be perfect. Downloading direct members of the relation might be sufficient in this case.
2. The usecase which I had in mind is the following: The user intends to use an edit memu operation, e.g. a geometrical one like a multipolygon area split. We need a full download including nodes to allow geometrical computations. A multipolygon is just a special area, and it is displayed in iD like an area. 
A user intending to modify the geometry should not need to go down to all members to download. Instead, the user should be able just to download missing data without any need to care about being a relation.

Maybe we can avoid single operand operations which need a complete download of the selected relation. In this case a download link to support usecase 2 could be placed in the multi-selection view. How about placing a link bar below the list of selected items there? It might be useful for other things too.

**Comment by bhousel** [comment]
If #5180 were implemented (a background worker queue), we could probably just fully download and parse _reasonable_ relations using a web worker and the user would not even need to be bothered by this.

**Comment by quincylvania** [comment]
For iD v3 I converted the "Zoom to this" link to a toolbar item. Most of the items in @slhh's original list could possibly be toolbar items as well. In any case, I don't really see us adding these links as described.
