### ISSUE TITLE
Clarify the "Forest" preset name

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5709]
[`landuse=forest`](https://wiki.openstreetmap.org/wiki/Tag%3Alanduse%3Dforest) and [`natural=wood`](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dwood) are often confused by new mappers since the names are generally synonyms. I suggest renaming the "Forest" preset to "Managed Forest" or something similar in order to indicate the difference. This is a simple change but I'm posting an issue to allow for discussion, if needed.

**Comment by bhousel** [comment]
> [`landuse=forest`](https://wiki.openstreetmap.org/wiki/Tag%3Alanduse%3Dforest) and [`natural=wood`](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dwood) are often confused by new mappers since the names are generally synonyms. I suggest renaming the "Forest" preset to "Managed Forest" or something similar in order to indicate the difference. This is a simple change but I'm posting an issue to allow for discussion, if needed.

Oh this is a good idea.. I'm going to just do it, since we have a bunch of other translation work in the pipeline.
