### ISSUE TITLE
Can't complete walkthrough because some presets are missing

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5718]
<img width="1129" alt="screenshot 2019-01-16 01 29 23" src="https://user-images.githubusercontent.com/38784/51230448-0388d580-192e-11e9-8adc-b5e115de4286.png">

**Comment by manfredbrandl** [comment]
Outside the walkthrough "Spielplatz" is found:
![image](https://user-images.githubusercontent.com/5360273/51253904-f60c3380-199f-11e9-9892-08e9aad12fd0.png)

**Comment by SilentSpike** [comment]
![image](https://user-images.githubusercontent.com/5459452/51261095-869a4200-19a7-11e9-9fc6-c38b1a438446.png)

🤔 Fixed already or inconsistent?

**Comment by bhousel** [comment]
I think this has since been fixed.. closing here.
