### ISSUE TITLE
Reduce use of universal fields

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5719]
Now that we have #5582 and #5712, we can reduce the number of universal fields. Users should feel confident that every field available in the `Add field:` dropdown is appropriate for use with the feature. This would reduce tagging mistakes and encourage detailed data entry.

These are the current universal fields (I recently removed Material and Seamark):

- Address
- Description
- Elevation
- Email
- Fax
- Fix Me
- Level
- Note
- Payment Types
- Telephone
- Sources
- Start Date
- Tourism
- Website
- Wheelchair Access
- Wikipedia
- Wikidata

I propose reducing the list to these:

- Description
- Elevation (remove at a later time)
- Fix Me
- Level (remove at a later time)
- Note
- Sources
- Start Date
- Wikipedia
- Wikidata

And moving these to `moreFields` of applicable features:

- [x] Address
- [x] Email
- [x] Fax
- [x] Payment Types
- [x] Telephone
- [x] Website
- [x] Wheelchair Access

Tourism should probably be removed altogether. Although it's useful for tagging arbitrary features as `tourism=attraction`, it also shows up as a duplicate field on `tourism` presets and enables errors like tagging a power line as `tourism=theme_park`.

**Comment by bhousel** [comment]
Awesome 👍 
I think iD might still instantiate all of the universal fields even if they are not shown, so they can be slightly costly.

**Comment by 1ec5** [comment]
This list looks OK, as long as we add stuff like Level, Telephone, and Website really liberally: a park might have a contact phone number, anything that can go inside a building could have a level, etc.

**Comment by quincylvania** [comment]
@1ec5 Yep, I've been trying to be expansive. I may actually keep Level universal for now since I'm not all that familiar with what presets people use it with in practice.

**Comment by bhousel** [comment]
> This list looks OK, as long as we add stuff like Level, Telephone, and Website really liberally: a park might have a contact phone number, anything that can go inside a building could have a level, etc.

I agree - it's easy to add the fields liberally now post-#5712 because most of the presets inherit fields from other presets, so for example, to add the "wheelchair access" field, it can just be done in one place.

**Comment by quincylvania** [comment]
I decided to leave both Level and Elevation as universal for now, since Elevation could apply to _nearly_ everything and Level could have many unexpected uses.

In the end I replaced seven fields and removed one entirely (tourism_attraction). Now would be a great time to check if your favorite presets have the correct fields, since I undoubtedly missed some.
