### ISSUE TITLE
Can't find "Spielplatz" in Walkthrough

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#5720]
Typing "Spielplatz" (German for playground) does not give a suggestion:
![image](https://user-images.githubusercontent.com/5360273/51253695-58b0ff80-199f-11e9-925f-1d3d2b1277ec.png)
In the last released version that works:
![image](https://user-images.githubusercontent.com/5360273/51253745-7bdbaf00-199f-11e9-963a-3d0d79e47c05.png)

**Comment by manfredbrandl** [comment]
Outside of the walkthrough "Spielplatz" is found:
![image](https://user-images.githubusercontent.com/5360273/51253946-150ac580-19a0-11e9-9a37-78cf1834428f.png)

**Comment by manfredbrandl** [comment]
@bhousel somehow we edited at the same time and your labels (bug-release-blocker, preset) got lost.

**Comment by bhousel** [comment]
weird!  lets' just keep this on #5718
