### ISSUE TITLE
Tag key occasionally mangled when tab pressed

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5722]
This is a problem I've only seen occur recently when adding heritage information to a building.  Maybe it's a post-2.12 or post-2.12.1 thing.

In the edit feature pane I go to "All Tags."  Click on the plus.  Type "her" which autocompletes to "heritage", press tab and enter the value.  Works fine.  Tab for new tag.  Type "her" which autocompletes to "heritage", press "end" key so I can add a colon, which autocompletes to "heritage:operator", press tab and enter the value "cadw" (Welsh organization responsible for maintaining the list of listed buildings).  Works fine.

Here's where it goes wrong.  Type "ref:cadw" and press tab to enter the value.  Mostly it works.  But occasionally after pressing tab the key is no longer "ref:cadw" but just "ref".  At first I thought it was my fault because I didn't see it happen, although 99 times out of 100 I start a key with the letters "ref" it's because it's going to be "ref:cadw" so it's pretty much automatic typing (I have to think about it to enter just "ref" or "ref:something_other_than_cadw".  Anyway, I took more care subsequent times and saw it happen.  I'd typed "ref:cadw" but as soon as I pressed the tab key it turned into "ref" all by itself.  I think that another time it turned into "ref:bag" but that could have been my fault (I wasn't paying attention for that one).

Maybe it's because ref:cadw isn't on the list of suggestions, but adding it would only mask the bug, not fix it.  But if you want to add it anyway, that would allow me to get away with typing "ref:cad" instead of having to type the whole thing. :)

It's possible this problem occurs with other keys, but "ref:cadw" is the only one I've noticed it on.

**Comment by eehpcm** [comment]
I can now confirm that occasionally, when I press tab, the key "ref:cadw" turns into "ref:bag".

Firefox 60.4.0esr.

**Comment by bhousel** [comment]
yep, I get this on Chrome too.  I think it happens because the `ref:bag` after being autocompleted gets classed as selected, and when tabbing off, the selected value is taken instead of the typed one.

![bad-combo-accept](https://user-images.githubusercontent.com/38784/51422219-ff042d00-1b78-11e9-8f44-a95571838187.gif)

**Comment by eehpcm** [comment]
@bhousel 

> yep, I get this on Chrome too.

That's good, to the extent that it's an easily-reproducible problem rather than one affecting only one browser or some weird combination of circumstances.

> I think it happens because the ref:bag after being autocompleted gets classed as selected, and when tabbing off, the selected value is taken instead of the typed one.

Maybe.  For me it tends to end up as just "ref" more often than it ends up as "ref:bag".  And it actually stays as "ref:cadw" slightly more often than either of those.  It's not consistent: three outcomes with "ref:cadw" most likely, then "ref" then "ref:bag".

My computer is slow and low on memory.  I wonder if it's a timing issue in how you're accessing the DOM.

What I can say is that over the course of over 6 months I've added around 360 instances of ref:cadw,  They tend to be added in clumps when I spend a day or two specifically adding listed buildings.  So I can't tell you exactly when this started happening, but I think it's within the last few weeks.  Which makes it likely a code change around 2.12.0 or 2.12.1 is the cause.
