### ISSUE TITLE
Wrong link to wiki field info

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5726]
Trying out the preview. If I expand a field I get the description and a link which says "Edit or translate description".
But it doesn't link to the wiki page for that field - instead it goes to some sort of wikidata-style page: https://wiki.openstreetmap.org/wiki/Item:Q253

Can't upload an image just now but I assume it's a en-gb problem... :) 

Seems to be in here:
https://github.com/openstreetmap/iD/blob/3e12a85fa16d03058be33c9989536c6149c590de/data/core.yaml#L428

**Comment by bhousel** [comment]
#5717 was supposed to add these links, but I also don't see them.
@nyurik can you check this?

**Comment by nyurik** [comment]
@boothym its coming - I need to import all that data into the data items. Currently it works with my "test" item - try  `bridge:movable` as a key, and it should work.

**Comment by bhousel** [comment]
Thanks @nyurik , I'll close here since it seems to be coming soon.
