### ISSUE TITLE
Drag-and-drop reordering of semiCombo field values

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5728]
Semicolon-delimited tag values have a particular order. In cases such as `destination`, the order matters. See https://github.com/openstreetmap/iD/issues/4178#issuecomment-455309081.

Users should be able to re-order values in the `semiCombo` field via drag-and-drop.

<img width="359" alt="51344282-4a79e680-1a66-11e9-95d1-b825d9851f0c" src="https://user-images.githubusercontent.com/2046746/51390659-e276df00-1afd-11e9-9b9c-4f0f23c90b61.png">

**Comment by Alamin02** [comment]
Hi I'm interested to work in this...

**Comment by quincylvania** [comment]
@Alamin02 Feel free to give it a shot! No one else is working on it at the moment. For reference, see [how we implemented drag-and-drop](https://github.com/openstreetmap/iD/blob/399b9be006fcfc8a5c056458968b7c6c4ce5c563/modules/ui/raw_member_editor.js#L241) for relation members.

**Comment by TAQ2** [comment]
>re-order values

Just curious, what is the advantage of this, will it change the ordering of the results?

@Alamin02 are you still looking into this? Otherwise I might give it a pop

**Comment by quincylvania** [comment]
@TAQ2 Yes, reordering the values in the field should reorder the semicolon-separated values in the tag. No one appears to be working on this right now so feel free to give it a try!

**Comment by TAQ2** [comment]
Ok got an initial implementation for `Destination` (below gif) but your screenshot asks about `Destination Road Numbers` which will require further work

1) How can I differentiate between `Destination` and `Destination Road Numbers`? This is needed for whether I need to drag and drop vertically (as shown) or horizontally so I assume this is something to do with the terminology of multi/semi combos?
2) Do want the dragging to apply for all combos? A nice iteration would be to implement it on one input and then go from there based on feedback/bugs but I'm questioning the long term

![Kapture 2019-10-31 at 14 23 46](https://user-images.githubusercontent.com/14198551/67955186-197c3400-fbea-11e9-8055-74760b672ad2.gif)

**Comment by quincylvania** [comment]
@TAQ2 Looks like a fantastic start, thanks for working on this!

> How can I differentiate between Destination and Destination Road Numbers?

The Destination field is hardcoded to have full-width values. You can examine the `key` property of the field in code.

> Do want the dragging to apply for all combos?

Yes, this issue is about reordering for all semiCombo fields. The destination fields are just an example where order particularly matters. I know this is a hard problem due to the way values flow to new lines.

**Comment by quincylvania** [comment]
This was done in #7024 thanks to @TAQ2!
