### ISSUE TITLE
Some of background imagery names and descriptions translation do not overwrite

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#5737]
There are four background layer on editor-layer-index project's geojson in asia/jp.
https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/asia/jp
I set "i18n": true for these and traslated all of these names and descriptions on transifex which are expected to be shown on the "Background" panel of [iD](http://preview.ideditor.com/master/#background=gsi.go.jp_airphoto&disable_features=boundaries&map=18.00/33.24006/130.25752).
But only 1/4 is correctly overwritten by translated text and other 3/4 are not. (red square below)
![](https://i.imgur.com/iTYKmIk.png)
correctly overwritten:
- 1)"Japan GSI KIBAN 2500" -> "国土地理院 基盤地図2500(NARO経由)"
https://github.com/osmlab/editor-layer-index/edit/gh-pages/sources/asia/jp/JapanGSIKiban2500.geojson

not overwritten:
- 2)"Japan GSI Standard Map" -> "国土地理院 標準地図"
https://github.com/osmlab/editor-layer-index/edit/gh-pages/sources/asia/jp/JapanGSIStandardMap.geojson
- 3)"Japan GSI airphoto Imagery" -> "国土地理院 簡易空中写真"
https://github.com/osmlab/editor-layer-index/edit/gh-pages/sources/asia/jp/JapanGSIairphotoImagery.geojson
- 4)Japan GSI ortho Imagery -> "国土地理院 電子国土基本図(オルソ画像)"
https://github.com/osmlab/editor-layer-index/edit/gh-pages/sources/asia/jp/JapanGSIorthoImagery.geojson

**Comment by bhousel** [comment]
These look like the translations are all available on  http://preview.ideditor.com/master  - is this right?

The dev mirror is updated frequently, whereas the iD on openstreetmap.org is only updated when we make a new release of iD.

**Comment by bhousel** [comment]
Thanks for reporting @higa4  - I just pushed a fix.. Can you check this again in preview later today?

**Comment by higa4** [comment]
I just checked and it looks fine. Thanks a lot!
