### ISSUE TITLE
Potential for KeepRight error status updates to be aborted

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#5748]
When posting an error update, the request is stored in the inflight cache:
https://github.com/openstreetmap/iD/blob/0499a76443a0b6c207ae85a5c39acbaa2b10582e/modules/services/keepRight.js#L424-L426

This is also where requests are stored for getting errors within tiles (notice unwanted requests are first aborted):
https://github.com/openstreetmap/iD/blob/0499a76443a0b6c207ae85a5c39acbaa2b10582e/modules/services/keepRight.js#L304-L315

The issue is that when unwanted requests are aborted, this cache is assumed to only contain tile updates (line 46 here):
https://github.com/openstreetmap/iD/blob/0499a76443a0b6c207ae85a5c39acbaa2b10582e/modules/services/keepRight.js#L37-L53

Thus any inflight error updates will also be aborted. I'm unsure of the likelihood that this can actually occur (as things seem to be working), but it seems like unwanted potential behaviour.

**Comment by bhousel** [comment]
good catch @SilentSpike 👍
