### ISSUE TITLE
Update the Museum icon to be effective regardless of language

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5751]
The current museum preset icon has an "M" character which does not make sense in most languages. We should find an alternative icon, preferably one that still indicates "museum" and not just some generic pillared building.

<img width="754" alt="screen shot 2019-01-23 at 2 55 22 pm" src="https://user-images.githubusercontent.com/2046746/51633171-00d64380-1f1f-11e9-8494-c564938aa1f1.png">

**Comment by manfredbrandl** [comment]
Do you think it can have any other form than this: 
![9e7f5ab8-e386-475d-8801-ce88006c371b](https://user-images.githubusercontent.com/5360273/51634375-642e9880-1f54-11e9-820f-1c5b4d9ceecb.jpeg)

**Comment by bhousel** [comment]
I agree - the "M" looks maybe too much like "Metro" station in many places.

I replaced it with the one we got from temaki (a generic pillared building for now, sorry 😂)
We were also using it for Planetarium preset, which I replaced with a globe.

<img width="300" alt="screenshot 2019-01-29 13 51 23" src="https://user-images.githubusercontent.com/38784/51932417-2787f480-23cd-11e9-8abc-8c6b30f9b33d.png">
