### ISSUE TITLE
shop preset now lacks opening hours

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5755]
Some recent change has dropped the opening_hours field for shops.  I get address (which I usually use), building type (which I sometimes change, but not often), and payment types (which I rarely know, because I rarely go into a shop I've surveyed to ask).  Opening hours I usually add because they're almost always visible from outside the shop and often listed on the shop's web site if armchair mapping.  It wouldn't bother me if payment type were harder to get to if that mean opening hours was as easily accessible as it used to be.

**Comment by quincylvania** [comment]
Hi @eehpcm! In 2.13.0 you can add the Hours field to any Shop preset under the "Add fields:" dropdown.

I do see your point that the hours are fairly easy to find and add. I think I'll add the field back to the default list.

<img width="498" alt="screen shot 2019-01-25 at 8 04 02 am" src="https://user-images.githubusercontent.com/2046746/51747546-d6e46480-2077-11e9-8374-ca4faff4d3c1.png">

**Comment by quincylvania** [comment]
Done in 5eda112bfae00a693200c3faa413c2f0d22ef98d

**Comment by eehpcm** [comment]
I can confirm my own suspicion.  Opening hours for toilets cannot be added from "Add field" so has to be done by a raw tag.
