### ISSUE TITLE
"cycleway" field doesn't initialise correctly if tag "cycleway" is set

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#5756]
It looks like the cycleway field only correctly initialises if individual lanes are set (`"cycleway:left"`/`"cycleway:right"`), but the field itself sets the `"cycleway"` tag if they are the same value.

Behaviour shown here (TIL github doesn't support webm files): https://giant.gfycat.com/RigidConcreteDuckbillcat.webm

I had a look at the UI code for this field, but couldn't suss out where the initial values of these comboboxes are set.

**Comment by my-na-me** [comment]
>  SilentSpike wrote:  (TIL github doesn't support webm files):

But ScreenToGif supports Gifs, which is also supported from GitHub :-)
(Had similar case, then I found it)

see here: https://github.com/NickeManarin/ScreenToGif/releases

> GitHub wrote: "Attach files by dragging & dropping, selecting them, or pasting from the clipboard."

Attaching files by "dragging & dropping" - works fine :-)
Attaching files by "selecting them, or pasting from the clipboard" - seems not working, or I do not understand correctly what to do. I copy (STRG c) the file when it is selected in the file manager, but then pasting (STRG v) here is not working :-(

**Comment by bhousel** [comment]
Offtopic, but I recommend [Licecap](https://www.cockos.com/licecap/) for recording animated gif screen captures.  It's open source and works great.  😄
