### ISSUE TITLE
Can't find basin preset using the search

### ISSUE THREAD

**Issue by LaszloEr** [openstreetmap/iD#5758]
The preset for landuse=basin can't be found by searching for "basin"  in the latest version 2.13.0.  This worked fine in the previous version of ID.

**Comment by jjiglesiasg** [comment]
Riverbanks also dissapeared from the Preset, even using the search tool.

**Comment by quincylvania** [comment]
The `landuse=*` for water features and `waterway=*` for areas presets were removed from search in favor of `nautral=water`+`water=*`, for consistency. See #5591 for details.

Let's add a new Basin preset for `nautral=water`+`water=basin`.

**Comment by bhousel** [comment]
Ah yeah I think these were supposed to be in https://github.com/openstreetmap/iD/commit/18ea434d021817505638c42de9802aedcf2937ad but got missed

**Comment by bhousel** [comment]
ok, I just restored it in 1a3a41150

> Riverbanks also dissapeared from the Preset, even using the search tool.

per #5591 these are superseded by `natural=water + water=river`.  The preset is just called "River" now, but I can add "riverbank" as a search term.
