### ISSUE TITLE
The contents of the name field are erased after pressing the tab key

### ISSUE THREAD

**Issue by rileysa1** [openstreetmap/iD#5760]
The contents of the name field are erased after pressing the tab key. This seems to happen whenever I make changes to a new point, line or area, before assigning a feature type and a name to it. The circumvent this problem, I either have to use the enter key (instead of tab) or click on another field using my mouse. Note: I'm using Firefox Quantum 64.0.2 and Google Chrome 71.0.3578.98 under Windows 10 with Adblock Plus 3.4.3. I believe the problem started sometime today.

**Comment by bhousel** [comment]
Thanks for reporting @rileysa1 - I'll dig into this tomorrow..
