### ISSUE TITLE
Barrier style not drawn along area edges

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#5761]
Suddenly the barriers depiction just dissapears from the areas tagged so, as stand alone lines are depicted, but in areas no..

**Comment by bhousel** [comment]
Can you share a screenshot?

**Comment by jjiglesiasg** [comment]
![screenshot 2019-01-25 17 33 09](https://user-images.githubusercontent.com/22849578/51748997-914f8800-20c7-11e9-8eaf-058ca0dfffb9.png)

**Comment by jjiglesiasg** [comment]
I guess self explanatory

**Comment by jjiglesiasg** [comment]
Sorry I closed by mistake

**Comment by jjiglesiasg** [comment]
Was it solved? still do not shows the barriers in the depiction of areas tagged so

**Comment by quincylvania** [comment]
@jjiglesiasg This is in the current branch (http://preview.ideditor.com/master) and will be in the next version of iD.

<img width="858" alt="screen shot 2019-02-04 at 8 59 47 am" src="https://user-images.githubusercontent.com/2046746/52212769-48cc6300-285b-11e9-8f4f-45b8df28ede1.png">

**Comment by jjiglesiasg** [comment]
Perfect, as it was before. Thanks
