### ISSUE TITLE
Using Themes in iD

### ISSUE THREAD

**Issue by erkinsergey** [openstreetmap/iD#5762]
I read issue  [More accessible colors #4270](https://github.com/openstreetmap/iD/issues/4270) , but did not understand, whether there are themes for iD.

I want to change the design styles for all my internal users.I mean styles for panels, lists, buttons, etc.The stylish extension plugin does not suit me.

I build from source codes and can add and change everything. What I need to change to slightly change the style of the editor?

**Comment by quincylvania** [comment]
Since you are building iD yourself, you can edit the styles via the CSS files in the [`css` directory](https://github.com/openstreetmap/iD/tree/master/css). Most of the user interface styling is defined in `css/80_app.css`. You can use the inspector in your browser to get the classes of elements you want to change.

Closing this since it's not really actionable.

**Comment by erkinsergey** [comment]
I just wanted to ask if there are any ready-made themes?
Thanks for the answer!

**Comment by quincylvania** [comment]
> I just wanted to ask if there are any ready-made themes?

No, not that I'm aware of. @bhousel made some for the Stylish browser extension (see https://github.com/openstreetmap/iD/issues/3095#issuecomment-224988925) but they are likely outdated and you mentioned that extension doesn't suit you anyway. There isn't really any other theme mechanism at the moment, but if somebody wanted to build one I'd be open to a discussion!

> Thanks for the answer!

You're welcome!

**Comment by bhousel** [comment]
Yes @erkinsergey  - for now everything in iD is rendered with SVG/CSS, so you an override these with Stylish (or obviously fork iD and change the CSS files).  [see FAQ](https://github.com/openstreetmap/iD/blob/master/FAQ.md#im-having-trouble-seeing-some-of-the-colors-is-there-a-way-to-customize-or-change-them)

We are probably going to outgrow this approach to styling soon.  iD's CSS is already so complex that it takes too long for browsers to recalculate the styles when things change, and we are looking into rendering some of the map data with something like canvas to improve performance.
