### ISSUE TITLE
Adding a multipolygon should open the area preset browser

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5765]
Currently when you select Multipolygon from the relation preset browser you are brought to the entity editor and have to go back to select the area preset. We should simplify this by bringing up the area preset browser immediately after selecting Multipolygon.

The will be especially important once the validation branch is merged. The user will be see an error on `type=multipolygon` relations with no other tags, but it does not make sense to warn them for new features.

**Comment by slhh** [comment]
@quincylvania 
I'd disagree.
When the user is reaching the multipolygon preset the multipolygon structure is typically either invalid (a single line) or it is at least not a reasonable multipolygon (a single closed way).
We need to encourage users to add the missing members.
If iD was using the area preset, the all members section would be hidden behind the potentially long all fields section.

**Comment by bhousel** [comment]
maybe related to #5450

**Comment by slhh** [comment]
@quincylvania 
To address your issue I came up with the idea of #5810.
