### ISSUE TITLE
Improve Highlighting the members of a selected relation

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#5766]
- [x] When a relation is one of multiple selected elements, relation members are highlighted as if they were selected themselves. Instead, they should be highlighted with a different style, possibly with a yellow halo.
- [x] When a relation is selected as the only element the members aren't highlighted at all. Instead they should be highlighted as suggested above.
- [ ] When a relation  is selected as the only element and requires a sequence of connected member ways, endpoints of such ways should also be highlighted. They need to be eye-catching to indicate small gaps in a route or turn restriction.

**Comment by bhousel** [comment]
Thanks @slhh , I agree that we can improve the styling of highlighted relations.

**Comment by quincylvania** [comment]
@slhh Good idea to use a different color for highlighting the members when only the relation is selected. I implemented that.

Your third bullet bullet point doesn't seem as pressing as the first two. If you definitely think we should do it then I suggest opening a new issue. I find bite-sized issues much easier to address than lists like this.

![Screen Shot 2019-06-18 at 2 25 51 PM](https://user-images.githubusercontent.com/2046746/59709553-105b6f00-91d5-11e9-862b-46f3cfdae95b.png)
