### ISSUE TITLE
Mapillary photo overlay showing blank images

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#5768]
It seems like some Mapillary images are failing to load. The ones at [this location](https://www.openstreetmap.org/edit#map=19/29.61682/-95.35997) exhibit this behaviour for me.

Console shows the following error:
```
Failed to cache node (HZ6oaXb7XeZ7epWkm4bttg) Error: Images (HZ6oaXb7XeZ7epWkm4bttg) could not be found.
    at e.project (mapillary.min.js:1)
    at e._next (mapillary.min.js:1)
    at e.o.next (mapillary.min.js:1)
    at mapillary.min.js:1
```

**Comment by bhousel** [comment]
Closing here, as I don't think this is something that we can control from the iD side. But I'm sure they would want to know about it, so you should open the issue on the [mapillary/mapillary-js](https://github.com/mapillary/mapillary-js) repo, which is for tracking issues with their viewer.
