### ISSUE TITLE
Continuing an already-tagged way re

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5770]
I just continued a way which had already been tagged (could have been a service road, could have been a hedge, the behaviour is the same).  After I double-clicked to finish the continuation, the "Select Feature" pane appeared when I expected the "Edit Feature" pane.

Clicking away then back on the feature sometimes brings the "Edit Feature" pane and sometimes doesn't.  I can't find a sequence of clicks that reliably gets what should have appeared anyway (and used to, prior to recent changes).

I haven't experimented to see what happens if I save it without clicking around to get the "Edit Feature" pane.  Maybe everything works as expected, maybe not.  Even if it saves correctly, current behaviour is counter-intuitive.  Firstly, it leads people to think something has gone wrong.  Secondly, it invites people to select a feature, possibly accidentally changing what the feature was previously (was I extending a service road or a driveway?).

**Comment by bhousel** [comment]
@eehpcm That is weird!  @quincylvania can you look into why the inspector shows the preset_list screen instead of the preset_editor screen here?

![extend_line](https://user-images.githubusercontent.com/38784/51791357-cc0cfb00-216f-11e9-9596-cc444a88da0c.gif)

**Comment by eehpcm** [comment]
Possibly related issue.

Draw a point, line or area.  The "Select feature type" pane appears (as expected).  Without choosing the feature type, click off the object for some reason (deliberately to check details of a different object or accidentally click on blank area of map).  Reselect the original object.  Now you get the "Edit feature" pane, with the feature type being either a point, line or an area (as in it has no tags at all).  I'm pretty sure it didn't work that way in the past.

**Comment by quincylvania** [comment]
> Draw a point, line or area. The "Select feature type" pane appears (as expected). Without choosing the feature type, click off the object for some reason (deliberately to check details of a different object or accidentally click on blank area of map). Reselect the original object. Now you get the "Edit feature" pane, with the feature type being either a point, line or an area (as in it has no tags at all). I'm pretty sure it didn't work that way in the past.

Yep, this was an intentional change made in #5632.
