### ISSUE TITLE
Differentiate between other feature and no feature

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#5809]
The "Other" preset is currently used regardless whether the feature type is unknown by iD or isn't tagged at all. Showing something like "Featureless Vertex" and "Featureless Point" would be more clear to describe the untagged ones.

In case of "Line", "Area", or "Multipolygon", we might also differentiate similarly.

In case there isn't any relation membership we might even call the untagged element as "useless", but this doesn't apply to vertexes.

Some technical tags like area=yes, type=multipolygon or created_by should not be considered to constitute a tagged feature.

**Comment by bhousel** [comment]
I do sometimes test iD with completely new mappers, and I’ve never heard anyone complain about the “Other” preset before. 

I would prefer to leave the names of the generic presets alone unless there is a real problem to solve.

**Comment by slhh** [comment]
@bhousel 
This is nothing to complain about, but I think we can do better in view of encouraging users to apply presets or tags where required, and to make real other features more noticeable in the inspector, in member lists, and in multi-selections.

The current presets seem to be sufficient in view of preset selection. Therefore, the featureless presets should be non-searchable.

The issue was less relevant in the past due to showing the preset selection instead of the inspector in case of untagged points, lines, and areas.
My suggesteion in #5810 would also show the preset for untagged vertexes more often.
Another reason is to allow #5810 to be specific for untagged elements.
