### ISSUE TITLE
Add a "feature type assignment" section for untagged elements

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#5810]
ID's behavior in view of untagged elements has recently been changed to show the inspector instead of the preset selection. How about adding the preset selection as a "feature type assignment" section below the "all relations" section in case of untagged elements?

The "feature type assignment" section" would likely be visible on the first sidebar page, because the other sections are typically short in case of untagged elements.

This can help to encourage users to apply presets where required.
I think this can also address the root cause of #5765.

In addition assigning feature types to vertexes is currently quite inconsistent. Untagged connecting highway vertexes show the inspector and other untagged vertexes show the preset selection instead. I think we should show the inspector and the preset search below in both cases of untagged vertexes.

**Comment by bhousel** [comment]
I don't really understand this request.  In my view "presets" are "feature types".  

We intentionally don't even call them "presets" anywhere in the UI because this is too jargony, so we use the phrase "feature type" extensively in the help and walkthrough.  

That "presets" are nothing more than bundles of OSM tags is not interesting to most users.

**Comment by slhh** [comment]
@bhousel 
> In my view "presets" are "feature types".

I agree.
>We intentionally don't even call them "presets" anywhere in the UI because this is too jargony, so we use the phrase "feature type" extensively in the help and walkthrough.

That's why I used "assign feature type" as the visible section name.
The issue is about additionally showing the preset selection in a more visible position in case of untagged elements, just to remind the user to do the missing step.

Here is a mockup for an untagged multipolygon:

![assign feature type section](https://user-images.githubusercontent.com/13684947/51880068-2ecfe380-2376-11e9-8e94-6954e231aa9f.PNG)

**Comment by bhousel** [comment]
oh ok, thanks for the explanation @slhh 
Quincy has some pretty great work in progress on the `validation` branch where we'll be able to surface tagging issues like this.  The validation issues will appear up near the top of the inspector (so we are adding a new section, but it won't be the way you pictured it above).
