### ISSUE TITLE
Don't snap to point features that can't be vertices when line drawing

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5811]
If the preset for a point feature does not include the `vertex` geometry, iD should avoid snapping to those nodes during line drawing.

One example where this would be useful is in adding buildings or sidewalks to a downtown area with many businesses tagged as points near their front entrances. While the user can hold down option to turn off snapping, they may not be aware of that feature or may be mapping on a touch device.

**Comment by bhousel** [comment]
Yes, this would be useful.. Also mentioning that address interpolation lines are special, and we have some hacky code in iD to treat them differently.  (in other words, points _can_ be vertices on address interpolation lines)
