### ISSUE TITLE
Drop name field from "Other" vertex preset

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#5812]
A name seems to be quite inappropiate for vertexes, especially without assigning a preset.
I think we can drop the "Name" field from the "Other" vertex preset. This would look better in view of the turn restriction editor, and possibly also in view of #5810.

**Comment by bhousel** [comment]
Sure this seems good - I moved it from `fields` to `moreFields` so a user won't see the Name field unless they really want to.
