### ISSUE TITLE
Read photo overlay layer name and image key from URL query string

### ISSUE THREAD

**Issue by cbeddow** [openstreetmap/iD#5813]
Currently it's possible to read the map coordinates (center) and zoom from query string, so for example I can be on mapillary's website and click the button to edit the same view on iD:

`https://www.openstreetmap.org/edit?editor=id#map=18/39.93450741752976/-105.0910279993947`

I would like on Mapillary, and I think similarly it would be useful for projects using OSC and Bing, to be able to specify the image layer and key:

`https://www.openstreetmap.org/edit?editor=id#map=18/39.93450741752976/-105.0910279993947?photo_overlay=mapillary&photo=o6y6pgnHjz7vdEbjY7YCtg`

This link, for example, would make sure the Mapillary photo overlay is turned on, and then initiate the MapillaryJS viewer and execute `moveToKey('o6y6pgnHjz7vdEbjY7YCtg')` which would open that specific image, so a user can start editing right away

**Comment by quincylvania** [comment]
So I added the `photo_overlay` API parameter. Here's its documentation:

> * __`photo_overlay`__ - The street-level photo overlay layers to enable.
>   _Example:_ `photo_overlay=streetside,mapillary,openstreetcam`
>   _Available values:_ `streetside` (Microsoft Bing), `mapillary`, `mapillary-signs`, `openstreetcam`

Adding the `photo` parameter is more involved so that part is still up for grabs!

**Comment by cbeddow** [comment]
@quincylvania awesome! I'll see if maybe we can pick up on our end from there, thanks!

**Comment by cbeddow** [comment]
I want to move to a next level here and see if we can include:

1) image key
2) token

@quincylvania I am not too knowledgeable about this but want to help @kratico understand what might be possible. Do you think you could summarize to us what we'd have to do to get that working?

**Comment by cbeddow** [comment]
Closing this and opening separate issues:

Image key: https://github.com/openstreetmap/iD/issues/6398
Token: https://github.com/openstreetmap/iD/issues/6399
