### ISSUE TITLE
Chrome address suggestions over-ride iD dropdowns

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#5818]
Not sure if it's a new issue, but Chrome now presents address field suggestions over iD's.
This only happens when selecting the address dropdowns in iD with a mouse. Navigating to the dropdown via keyboard and Alt-dropping still works.
Chrome version 71.0.3578.98

**Comment by bhousel** [comment]
Share a screenshot please.  I use Chrome and I haven't seen anything like this.

**Comment by quincylvania** [comment]
I was able to reproduce this by having an autofill address in Chrome's settings.

<img width="733" alt="screen shot 2019-01-28 at 10 44 49 am" src="https://user-images.githubusercontent.com/2046746/51847489-c5a28e80-22e9-11e9-8ac0-45decc296666.png">
<img width="377" alt="screen shot 2019-01-28 at 10 43 37 am" src="https://user-images.githubusercontent.com/2046746/51847391-9ee45800-22e9-11e9-8f8d-a67aec1b70d2.png">

**Comment by bhousel** [comment]
Ok cool, thanks @quincylvania .. iD does [automatically add a bunch of options to our fields](https://github.com/openstreetmap/iD/blob/3903e9347eb5abbb5a6dba1a747b5860f5d23b71/modules/util/util.js#L304-L312) to avoid stuff like this.  There might be another one that we need to add for this particular Chrome feature.
