### ISSUE TITLE
Walkthrough: Symbols to close feature editor do not match

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#5819]
In the explanation one should use "✓" to close the feature editor, but in the feature editor there is a "✘":
![image](https://user-images.githubusercontent.com/5360273/51841252-7cb10100-230e-11e9-9c59-e5b8e572c824.png)

**Comment by bhousel** [comment]
I just tested this again, and it doesn't look like it does this anymore.  @manfredbrandl if you are still seeing this, can you let me know which browser you use?

**Comment by manfredbrandl** [comment]
@bhousel I tried now (2019-02-08, 16:10 UTC) on Windows 10 (64 bit) the latest Versions of the following Browsers: Chrome, Firefox, Edge, Opera and Vivaldi. Only Firefox shows the "✓" in the top, all others show a "✘" which is not what it should be to close the feature editor. There cant be a cache problem on edge, opera and vivaldi, because i did not use them on this computer before.
