### ISSUE TITLE
Walkthrough: Cannot create Tank in Chrome

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#5820]
In the Walkthrough in Google Chrome Version 70.0.3538.110 there is a "hand" instead of the "crosshair" when one should create the tank area. In Firefox and IE this works as expected.

**Comment by quincylvania** [comment]
I could not reproduce this on Chrome 71.0.3578.98 / macOS.

**Comment by quincylvania** [comment]
@manfredbrandl Are you seeing this on `release` or `master`? `master` underwent a few changes in the past few days that could have caused issues at the time you tested it.

**Comment by bhousel** [comment]
@manfredbrandl Can you check this again?  It seems like it might be fixed.
