### ISSUE TITLE
For linked data, should help link to real wikidata instead of OSM wiki?

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5823]
This looks weird to me: 

<img width="300" alt="screenshot 2019-01-28 13 34 58" src="https://user-images.githubusercontent.com/38784/51857914-75cfc180-2301-11e9-81c1-fea3c3441811.png">

Maybe for the `name`/`brand` fields on a feature that's linked to wikidata, we should follow the wikidata link and get Starbucks's info, rather than show the OSM documentation.

**Comment by bhousel** [comment]
BTW, and offtopic, but "The primary tag used for naming an element." is not very beginner friendly.

**Comment by 1ec5** [comment]
Is it weird because the prepopulated name looks like the thing being documented? I guess the documentation has always been misplaced from an information architecture standpoint. How wedded are we to this slide-in-below-the-field treatment, versus a help bubble or a row inserted right below the field’s header?

> BTW, and offtopic, but "The primary tag used for naming an element." is not very beginner friendly.

[Reworded the description](https://wiki.openstreetmap.org/wiki/Special:Diff/1782404).

**Comment by SilentSpike** [comment]
🤔 I think showing the brand information doesn't provide much value to a map editor (other than perhaps confirming it's the right brand of that name). However, I see your point that it's a little funny to provide information on a field the user can't interact with.

**Comment by 1ec5** [comment]
How about placing the non-brand preset name, or the wikidata item’s label, in a header immediately above the documentation? That way at least it’s clear what the documentation refers to, even when it isn’t especially relevant.

**Comment by bhousel** [comment]
It's gotten worse.. check out this guy in the bowtie :bowtie: : 
<img width="422" alt="screenshot 2019-02-08 14 05 34" src="https://user-images.githubusercontent.com/38784/52499939-af7ab500-2baa-11e9-89b7-200211b2f38e.png">

**Comment by bhousel** [comment]
We're looking these up from real wikidata now.  Thanks for ruining my afternoon, bowtie dude. 😆 
I'll add proper sitelinks, then close.

<img width="375" alt="screenshot 2019-02-08 16 30 33" src="https://user-images.githubusercontent.com/38784/52507223-e3f86c00-2bbe-11e9-8429-fd9d0cfc209b.png">

**Comment by bhousel** [comment]
This was done!
