### ISSUE TITLE
Inspector can get stuck when tabbing off "New Relation.."  (Safari only?)

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5824]
Safari only, AFAIK..
In raw member editor, use arrow keys to pick "New Relation.." from the combo, then press tab to accept and blur.

It somehow does this, leaving the inspector stuck halfway between the preset list and the preset editor.

<img width="1183" alt="screenshot 2019-01-28 15 18 08" src="https://user-images.githubusercontent.com/38784/51863806-fe555e80-230f-11e9-8c59-36a6f0d6203a.png">

**Comment by bhousel** [comment]
Looks like this also happens from tabbing on the preset list screen search field.  You can even alt-tab from the name field to go back.  (maybe need to tabindex -1 this field?)

![safari-tab](https://user-images.githubusercontent.com/38784/51864603-35c50a80-2312-11e9-94e8-f53bd8f06e2e.gif)

**Comment by 1ec5** [comment]
Reminds me of #4233.

**Comment by 1ec5** [comment]
I’m not reproducing this issue in Safari 12.0.3. Incidentally, it’s impossible to tab _to_ the relation selector field in some cases (#4233), but the preset browser shows up OK for me.

**Comment by BjornRasmussen** [comment]
I wonder... is this still happening with the resigned preset choosing system?

**Comment by quincylvania** [comment]
> I wonder... is this still happening with the resigned preset choosing system?

Yeah, this whole preset selection UI has been replaced for v3.
