### ISSUE TITLE
Add Traffic Monitoring Station preset

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#5827]
This tag is useful to distinguish that the loops in the roadway are for counting the traffic and not maxspeed enforcement.

Tag: man_made=monitoring_station + monitoring:traffic=yes

Wiki: https://wiki.openstreetmap.org/wiki/Key:monitoring:traffic

**Comment by boothym** [comment]
I think just adding the man_made=monitoring_station first of all would be a good idea, then a dropdown for the various monitoring: values.

**Comment by bhousel** [comment]
> I think just adding the man_made=monitoring_station first of all would be a good idea, then a dropdown for the various monitoring: values.

iD has a "Monitoring Station" preset already:  https://github.com/openstreetmap/iD/blob/master/data/presets/presets/man_made/monitoring_station.json

**Comment by boothym** [comment]
Oh, then I've realised why it didn't show on a river node, as vertex is not listed in the preset - could that be changed?

**Comment by bhousel** [comment]
> as vertex is not listed in the preset - could that be changed?

☝️ I did this

I don't think we need to add presets for every kind of monitoring station, because now that the preset is available is it pretty easy for users to pick "traffic" from the multicombo.
