### ISSUE TITLE
Use a multi-touch gesture to precisely position points

### ISSUE THREAD

**Issue by dasjo** [openstreetmap/iD#583]
this is just an idea and i hope, this is the right place to put it. when using an editor like iD with touch-device like your smartphone, you have the problem of the area of focus to be hidden by your finger. its obvious that placing points on the map by finger can't really be accurate.

what i'm envisioning is a way of precisely positioning points by using a multi-touch gesture:  while dragging a point with one finger, pressing a second on the screen will essentially create a recangle and place the point in the center, for example visualized using two diagonals connecting the edges of the rectangle. think of your thumbs being either A+C or B+D of the following diagram and the point to be placed at E.
http://image.tutorvista.com/cms/images/38/rectangle-diagram.jpg

congratulations on your great project, regards dasjo

**Comment by bhousel** [comment]
Closing as stale... 
We have a lot of similar issues for touch devices, and I know it needs improvement.
#1981, #2700, etc
