### ISSUE TITLE
Bing imagery key

### ISSUE THREAD

**Issue by systemed** [openstreetmap/iD#5833]
iD uses the Bing imagery key that was originally set up for Potlatch 2: https://github.com/openstreetmap/iD/blob/898b2e3d0a01652bc5a821a601480a2d36d4a442/modules/renderer/background_source.js#L223

This key is registered to my email address. Occasionally I get emails like this:

> Thank you for being a valued Bing Maps Customer.
> You are receiving this notification as you have been identified as an owner of the Bing Maps Account ID 1041305. Your Basic Key(s) have consumed 90.2% of your Bing Maps Platform APIs' Terms of Use (TOU) limits for this calendar year. Account limits reset at the beginning of each calendar year. To continue using Bing Maps Platform APIs, you will need to either remain within the Terms of Use limits, or you will to upgrade to an Enterprise license. Having an Enterprise license will improve overall service quality and provide an increased level of support. 

I then try and get this fixed by emailing/tweeting people at Microsoft, who either say "oh sure we've fixed it" or point me towards a series of options I should supposedly set on my account, which would be fine if those options actually existed, which they don't. It's all a bit [beware of the leopard](https://www.goodreads.com/quotes/40705-but-the-plans-were-on-display-on-display-i-eventually). Then a few months later it happens again.

Frankly I have exhausted my patience for arguing with them, and won't be following it up any more.

It's therefore possible that Bing imagery may break in any app that uses this key. Personally I don't think this would be a bad thing as it might finally embarrass Microsoft into fixing it, but this is by way of a heads-up to warn you. If you feel like arguing with the Microsoft bureaucracy then I wish you godspeed.

**Comment by bhousel** [comment]
Thanks @systemed for staying on top of this over the years!  I'll see if I can get their attention.  

> Having an Enterprise license will improve overall service quality and provide an increased level of support.

Sounds wonderful 😄

**Comment by jharpster** [comment]
Thanks for opening the issue here @systemed. I thought we got this updated in the last round of emails but I guess not. Chatted with @bhousel and I think we have an idea for a more permanent solution for the ever expiring Maps key.

**Comment by systemed** [comment]
Received today:

> Thank you for being a valued Bing Maps Customer.

> You are receiving this notification as you have been identified as an owner of the Bing Maps Account ID 1041305. Your basic key(s) have exceeded the daily usage limits as per the Bing Maps Platform APIs' Terms of Use (TOU). Your basic key(s) will no longer work until either it is reset or it is upgraded to an enterprise key(s).

> If you do not currently hold a Bing Maps for Enterprise license, You can learn about the Bing Maps licensing options that are available by visiting the Bing Maps licensing website.

**Comment by don-vip** [comment]
It seems the API key has been revoked today: https://josm.openstreetmap.de/ticket/17744

**Comment by bhousel** [comment]
> It seems the API key has been revoked today: https://josm.openstreetmap.de/ticket/17744

Thanks for the ping - I'm following up with their team on a replacement key.

**Comment by jharpster** [comment]
Hey @bhousel do let me know if you need help getting to the right people. I can help expedite.

**Comment by don-vip** [comment]
> Thanks for the offer! We're working on getting a new key now.
> 
> Actually the existing key is still working, we think it might have just exceeded the daily 50k view limit yesterday. (It started working again last night even before the emails went out 😆)

Good to know! I was a bit surprised to not be spammed by bug reports today. Maybe this is time every editor get its own key? This way the probability to reach the 50k limit will decrease.

**Comment by pnorman** [comment]
> Maybe this is time every editor get its own key?

Yes, I think this would be the best, although for different reasons. It does increase the administrative workload since each editor needs to have contact with Bing for getting the key setup properly.

**Comment by bhousel** [comment]
> Maybe this is time every editor get its own key?

We are considering this, but from the sounds of it the 50k limit is per organization, not per application.  Working with the enterprise support team to decide best next steps.   We aren't even sure at this point whether all the traffic is actually ours.

**Comment by bhousel** [comment]
Update on this - we have a second nonprofit key that we may use for testing, and I've switched iD over to use it. (Will deploy a patch update to iD soon).

This should free up a significant number of mapviews so that other editors can continue the existing key without hitting the limit.  We will also be able to better tell whether all of the traffic is really ours, or whether someone else is using the other OSM key.

**Comment by HolgerJeromin** [comment]
> Update on this - we have a second nonprofit key that we may use for testing, and I've switched iD over to use it.

IIRC vespucci (cc @simonpoole ) has an own key, too.

**Comment by don-vip** [comment]
@bhousel thanks a lot!

**Comment by don-vip** [comment]
@bhousel  is the key change live in production? We just hit the quota again.

**Comment by bhousel** [comment]
I believe it is in production as of this morning, but have not checked yet.

**Comment by pnorman** [comment]
> @bhousel is the key change live in production? We just hit the quota again.

Is JOSM still using the P2 key?

**Comment by don-vip** [comment]
@pnorman yes. @bhousel did you check if osm.org is using the new key? We're still hitting the limit.

**Comment by bhousel** [comment]
> @bhousel did you check if osm.org is using the new key? We're still hitting the limit.

@don-vip  Yes current versions of iD are using the new key.. Looks like we are using about 20k-25k transactions per day.
