### ISSUE TITLE
Use URL formatter for tag values

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/iD#5838]
There is a growing list of tags whose values represent links to a site, such as `wikipedia` or `contact:yelp`.  Some of them have special handling in the top section _all fields_ (wikipedia, wikidata), and as a result have a well defined link:

![image](https://user-images.githubusercontent.com/1641515/52148588-31616000-2638-11e9-9495-d3a859b723f4.png)

While other tags do not shown as links at all -- _all tags_ section:
![image](https://user-images.githubusercontent.com/1641515/52148489-d596d700-2637-11e9-9901-1495f7f45596.png)

We should add a small external link icon next to all linkable entries in the _all tags_ section, using the formatter URL (P8) property of the data item.  For example see [contact:yelp formatter URL](https://wiki.openstreetmap.org/wiki/Item:Q8244#P8) (set to `https://www.yelp.com/biz/$1`)

**Comment by bhousel** [comment]
I'm kind of inclined to say no to this for a few reasons..
1. Design wise, I don't really want to add another button on some of the rows.
2. I don't know how we'd actually implement it.  iD doesn't really know what all the tags in OSM are.  So we'd need to do a SPARQL query for every row to know how/whether to add the link button?

**Comment by nyurik** [comment]
@bhousel the design could be something like this:
![image](https://user-images.githubusercontent.com/1641515/52153203-10ecd200-2647-11e9-8348-bfe0792ab621.png)
as for the second point, the current implementation actually will handle that in a single request -- if you look at https://github.com/openstreetmap/iD/blob/3e12a85fa16d03058be33c9989536c6149c590de/modules/services/osm_wikibase.js#L112 
it can be easily changed to handle multiple keys and tags -- it already retrieves 3 entity at once.  So just call `getEntity` the moment user clicks on any object, and once result is returned, update the style of the items that can be links.  Note that some of the results will be cached, so technically you could make it show cached results much faster. 

Note that this change would be needed for other stuff as well - for example you will be able to perform additional validations without an extra server hit, show description using tooltips, etc.

**Comment by bhousel** [comment]
Yeah, I thought more about this and I think it’s best to just close it.. I don’t think users need this feature.
