### ISSUE TITLE
Line icons used on Area features look ugly

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5839]
This happens when we use the wrong kind of icon on a feature.  

<img width="637" alt="screenshot 2019-02-01 16 01 02" src="https://user-images.githubusercontent.com/38784/52149320-4e972e00-263a-11e9-839c-7e9d0fb3a044.png">

I'd like to fix this by getting rid of the "line" and "relation" icons.  We could just have normal icons, then add the line/relation graphic below the icon with code, only if we need to.

<img width="400" alt="screenshot 2019-02-01 16 05 27" src="https://user-images.githubusercontent.com/38784/52149580-32e05780-263b-11e9-9f7c-169eec3a387e.png">

**Comment by bhousel** [comment]
Please do the relation ones also

**Comment by quincylvania** [comment]
Closing this in favor of #5926 since it's been split between releases.

**Comment by bhousel** [comment]
Sounds good- sorry for my crankiness above :persevere:

**Comment by quincylvania** [comment]
No worries!
