### ISSUE TITLE
Custom  Aerial layer Fugro

### ISSUE THREAD

**Issue by Neogeografen** [openstreetmap/iD#584]
For Denmark we have a 100 % coverage with the Fugro aerial layer it's possible to add it to iD -

Wiki OSM http://wiki.openstreetmap.org/wiki/Fugro

The tile should be http://fugro.openstreetmap.dk/fugro2005/$z/$x/$y.jpg (working in Potlach 2)

Bing only covers ca. 25 % of Denmark at the moment.

Thanks in advance

**Comment by winternet-studio** [comment]
The URL no longer works (tried it as a custom layer in the new iD editor).

**Comment by Neogeografen** [comment]
Hi all

Just remove the Fugro (2005) layer now - The maintainer Peter Brodersen is not running the service anymore. The reason is that we have Mapbox Sat & Geodatastyrelsen layer to trace from in Denmark now- it's two newer layer with geodata/images  from year 2011-2014 - Thanks in advance for removing it

Best 
Soren Johannessen

**Comment by bhousel** [comment]
Hi, thanks for the report. iD's background imagery sources are now pulled from the [editor-imagery-index](https://github.com/osmlab/editor-imagery-index) project.  Please open a ticket there to have the source removed.  Thanks!
