### ISSUE TITLE
Improvement: Show Relation ID to identify

### ISSUE THREAD

**Issue by st-anton** [openstreetmap/iD#5841]
OSM Relation Analyzer is a good tool for viewing the completeness of routes. But sometimes (?) it does not find anything even if the name of the route is given correctly. Does it have to do with database rescans?
Anyway: It would be an improvement to see the relation ID in the iD browser, e.g when the route information is displayed: 
![grafik](https://user-images.githubusercontent.com/2517417/52164743-9a0f1200-26f6-11e9-8f6d-eb9540c9621d.png)
With this, the relation can be found more easily and even double relations can be identified better.
Note: #5556 already shows the relation ID in the preview, this would be also a good way, but line length is somehow limited.

**Comment by slhh** [comment]
@st-anton The relation id is already available in the measurement panel, and also in the history panel.
You can use Ctrl-I, Ctrl-Shift-H, or Ctrl-Shift-M to toggle the panels.
