### ISSUE TITLE
Allow numeric up/down buttons to work on an empty field

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#5844]
### Expected behavior
the count of lanes could be changed from no value (empty cell) to 1 by hitting the arrow up button. 

### Actual behavior
clicking the arrow up button nothing changes 

### Links and screenshots illustrating the problem
![lanes](https://user-images.githubusercontent.com/47290585/52173609-d474bf80-2787-11e9-9a37-4adcf7255296.gif)

**Comment by AndreasHae** [comment]
I'm going to take a look at this.

**Comment by sun-geo** [comment]
:-)

Thank you!
