### ISSUE TITLE
tabbing through additional tags broken

### ISSUE THREAD

**Issue by GallusMax** [openstreetmap/iD#5847]
This seems to be unearthed in the latest (2019/01 !) version. More than annoying, when you trust the chosen value being committed by a TAB, when its not. Sometimes, often. Sometime it works ok.
PLEASE fix!

_Originally posted by @GallusMax in https://github.com/openstreetmap/iD/issues/1117#issuecomment-460056286_

**Comment by bhousel** [comment]
Can you provide some more details about what you're seeing? Also which browser you are using?

I think it has something to do with the tag editor, but it's not clear from your bug report.

**Comment by GallusMax** [comment]
Sure. 
Given You're in the advanced editing of item tags, altering tag / value pairs one by one.
The expected behaviour of the TAB would hop from a tag field to its value field, where after some typing several presets appear - or typing ends up with a new freetext value. Another TAB should ACCEPT the typed / selected value and hop to the next (possibly: new and empty) tag. 
(I didnt notice any other behaviour, yet my surprise)
In the current version a TAB will leave the value field empty from time to time. Even after manually entering free text(!). And its not even clear if it will then hop into a new line / a new and empty tag field.

Bowser version:
I often use Firefox (latest), but did never find any difference to Chrome e.g.

Hope to be helpful for you, bhousel, thanks!

**Comment by GallusMax** [comment]
How to reproduce:
Choose an item o the map (a street?)
Expand the "All Tags" Part on the left
Put the Cursor in the "Tag" field on the left
Type "hig" - completion  "hway" is offered
Type TAB - tag is set to "highway", as expected, Cursor blinks in Value field on the right
Type "ser" - completion "vice" id offered, which is what you want
Type TAB - Value field is EMPTY again (which is not what _I_ expected), Cursor goes haywire, or on the next empty Tag field, whe I would look after it.

Expected: the offered expansion is committed by the TAB, and the next Tag field is opened.

**Comment by GallusMax** [comment]
Duh - seems of course a Firefox Issue. Tested again with Firefox "Quantum" 59.0.1. Thats where it hurts. Will report whe I found an older version w/o this issue. (Sorry, did not user Chrome for editing for a long time)
