### ISSUE TITLE
Prevent deleting a feature with a Wikidata tag

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5853]
If a feature has a `wikidata` tag, iD can assume that it is likely a non-trivial feature due to notability guidelines ([Wikidata](
https://www.wikidata.org/wiki/Wikidata:Notability), [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Notability)). As an extra layer of protection against the accidental removal of important features, we should warn users if they delete these features .

See #5830 for upcoming UI improvements that will surface issues immediately as you edit.

**Comment by matkoniecz** [comment]
Note that in normal editing it is common to delete features with mistagged `wikidata` tag (for example duplicate shop nodes that were mistakenly tagged with `wikipedia` rather `brand:wikipedia`).

**Comment by pnorman** [comment]
> If a feature has a `wikidata` tag, iD can assume that it is likely a non-trivial feature due to wiki [notability guidelines](https://en.wikipedia.org/wiki/Wikipedia:Notability).

You've linked to the Wikipedia guidelines, not the Wikidata ones.

**Comment by matkoniecz** [comment]
And Wikidata has much lower ones: https://www.wikidata.org/wiki/Wikidata:Notability

**Comment by quincylvania** [comment]
@pnorman @matkoniecz Oops! Thanks for noticing, I update the post with both links since iD couples Wikipedia and Wikidata rather closely.

**Comment by pnorman** [comment]
The Wikidata policy allows

> It refers to an instance of a clearly identifiable conceptual or material entity. The entity must be notable, in the sense that it can be described using serious and publicly available references

I could create wikidata entries for all the houses on my block.

This feature might still be worth it, but because of what Wikidata contains in practice, *not* it's notability policies.

**Comment by bhousel** [comment]
Honestly I think we should just prevent users from deleting features with a `wikidata` tag - not just show them a warning.

**Comment by quincylvania** [comment]
> Honestly I think we should just prevent users from deleting features with a wikidata tag - not just show them a warning.

@bhousel I'm fine with this assuming users can delete the feature after removing the wikidata tag. Like with editing the name.
