### ISSUE TITLE
Add preset for Golf Paths / Cartpaths

### ISSUE THREAD

**Issue by chadrockey** [openstreetmap/iD#5859]
I'm looking to extend similar to this:
https://github.com/openstreetmap/iD/blob/6ce2c5ea46b6bb89f8a3a3dd9d5794a920bbf610/data/presets/categories/golf.json

For lines types to bundle Golf->Hole with Golf->path (intended only for foot traffic) and Golf->cartpath (available for golfcarts).

These presets should create something like: highway=path and golf_cart=designated

My main question is, in order to add a value to the tag key "golf", such as "golf":"path" or "golf":"cartpath" is this mostly communal and metadata driven or is there a formal review process?

Once I find out how much formality is needed, I'll create the relevant json files for the presets and make a PR.

Originating discussion:
https://github.com/gravitystorm/openstreetmap-carto/issues/3650

**Comment by bhousel** [comment]
This is all I could find about them on the OSM wiki:
https://wiki.openstreetmap.org/wiki/Key:golf_cart

What you suggested for `highway=path`+`golf_cart=designated` seems good.

> My main question is, in order to add a value to the tag key "golf", such as "golf":"path" or "golf":"cartpath" is this mostly communal and metadata driven or is there a formal review process?

Communal and metadata-driven.  It is already used [almost 10k times](https://taginfo.openstreetmap.org/keys/golf_cart) and it's a real thing that I'm sure people want to map, so adding a preset to iD is no problem.

**Comment by chadrockey** [comment]
Nice!  Both are in use!
https://taginfo.openstreetmap.org/keys/golf#values

I'll get started on this immediately.

**Comment by bhousel** [comment]
> I don't care which tags are chosen for this preset, but I have found that most golf cart paths are tagged as `highway=track` in osm, and not `highway=path`.

per https://github.com/openstreetmap/iD/pull/5862#issuecomment-460771112
We're going to use new `golf=*` tags because many of these paths don't connect to the main routing graph, and we don't want the disconnected golf paths to be flagged as routing errors.

**Comment by bhousel** [comment]
Done in #5862
