### ISSUE TITLE
Info icon on Multipolygon shows wrong info

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/iD#5860]
To reproduce: select any relation object, and click the big button at the top with the type of the relation, e.g. this one:
![image](https://user-images.githubusercontent.com/1641515/52251947-ab5e4700-28cd-11e9-9513-da1d34dc6526.png)

In the list of available relations, scroll to the multipolygon, and click the (i) next to it:
![image](https://user-images.githubusercontent.com/1641515/52251879-6508e800-28cd-11e9-9fb0-ae835e4f1dd8.png)

The "edit/translate" link in the above image actually links to [the data item for the `key=undefined`](https://wiki.openstreetmap.org/wiki/Item:Q15551)

Instead, it should perform a lookup for `Relation:multipolygon`, and get [Item:Q16053](https://wiki.openstreetmap.org/wiki/Item:Q16053).

Might be related to https://github.com/openstreetmap/iD/issues/5861

**Comment by bhousel** [comment]
I just fixed this 🎉 

<img width="300" alt="screenshot 2019-02-08 13 22 21" src="https://user-images.githubusercontent.com/38784/52497820-15fcd480-2ba5-11e9-9395-8ec28ca2c3df.png">
