### ISSUE TITLE
Relations info header should use relation instead of tag data item

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/iD#5861]
Clicking the (i) info icon on the relation header shows data from the 

[Item:Q4920](https://wiki.openstreetmap.org/wiki/Item:Q4920) (`Tag:boundary=administrative`) instead of [Item:Q16019](https://wiki.openstreetmap.org/wiki/Item:Q16019) (`Relation:boundary`)

![image](https://user-images.githubusercontent.com/1641515/52252734-1b6ecc00-28d2-11e9-8e0d-06371dcfa607.png)

This might be related to the https://github.com/openstreetmap/iD/issues/5860

**Comment by bhousel** [comment]
It looks like that relation preset is specifically requesting `Tag:boundary=administrative` with a `reference` property. 

https://github.com/openstreetmap/iD/blob/b340b65df48628d5e7ca9c83b89c319f809b2a10/data/presets/presets/type/boundary/administrative.json#L10-L18

**Comment by nyurik** [comment]
@bhousel, is it possible for a preset to reference a relation (e.g. `Relation:boundary`)?  On the other hand, I think this issue is incorrect because `administrative boundary` is more specific than just a boundary, so closing it for now.
