### ISSUE TITLE
Add Retry button to the "Unable to connect to API" error message

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5864]
When the user gets this message, they have to wait for a slow timer to fire or navigate to a new area to trigger a new data request. It would be nice to have a `Retry` button so users could manually request a retry.

<img width="720" alt="screen shot 2019-02-05 at 7 54 58 am" src="https://user-images.githubusercontent.com/2046746/52274700-74168700-291b-11e9-90c3-02460f399369.png">

**Comment by mmd-osm** [comment]
Not sure, if you would get the same error message in case of a server overloaded situation (_"This website is under heavy load (queue full)_" - in which case providing a retry option wouldn't be exactly helpful as it only adds extra load to a struggling server.

**Comment by quincylvania** [comment]
@mmd-osm Good point. Perhaps we could tell the difference between no connection and server overload and have different behaviors. There are times when the connection could be lost independent of the server status, such as closing and re-opening a laptop in the middle of editing.

Another idea is to show the countdown of how many seconds until automatic retry, although this could be distracting if the user wants to ignore the warning until they're done editing.

**Comment by mmd-osm** [comment]
> There are times when the connection could be lost independent of the server status, such as closing and re-opening a laptop in the middle of editing.

That shouldn't really hurt as all communication to external APIs would most likely follow some kind of REST based, stateless paradigm. Losing your network connectivity during an upload may be a different story, though.

> Another idea is to show the countdown of how many seconds until automatic retry,

JOSM has it that way, a modal window shows a count down, the user may cancel the operation at any time.

**Comment by mmd-osm** [comment]
I'm just adding a link here to the OSM API side of the discussion, which would enable a safe retriy behavior by discarding duplicate uploads. When working on this, maybe keep an eye on the following issue:  https://github.com/openstreetmap/openstreetmap-website/issues/2201

Other related issues around upload failures, retries, and duplicates:
#3366, https://github.com/openstreetmap/iD/issues/5200#issuecomment-410763937
