### ISSUE TITLE
Add presets for common place of worship denomination values

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5865]
Done in 44d4f2378d47042943e86f4c485a4fefd2e14e8b. Reverted in 23ab1b66fba64c830397116ae8a2b8f0fa7afa10.

https://taginfo.openstreetmap.org/keys/denomination#values

I did not add [`mormon`](https://wiki.openstreetmap.org/wiki/Tag%3Adenomination%3Dmormon) since there is debate as to whether that is the correct value. I did add `quaker` even though it isn't especially common since it's important not to call Quaker meeting places "churches".

<img width="361" alt="screen shot 2019-02-05 at 10 23 42 am" src="https://user-images.githubusercontent.com/2046746/52283306-3b34dd00-2930-11e9-9896-4117ca4574bf.png">
<img width="360" alt="screen shot 2019-02-05 at 10 23 23 am" src="https://user-images.githubusercontent.com/2046746/52283308-3b34dd00-2930-11e9-8cf0-9b1d00936bbf.png">
<img width="361" alt="screen shot 2019-02-05 at 10 23 32 am" src="https://user-images.githubusercontent.com/2046746/52283307-3b34dd00-2930-11e9-9e32-683a1e1810b9.png">

**Comment by bhousel** [comment]
Why not just leave it as a dropdown like it was before?   People have to translate all these now...

**Comment by quincylvania** [comment]
Translation was part of the reason I added these, since the dropdown isn't translatable. No problem if you want me to revert it!

**Comment by 1ec5** [comment]
For what it’s worth, denomination names are some of the more straightforward things to translate in my experience. A lot of denominations evangelize, so there are established translations for their names in many languages. (From my perspective it’s the piste presets that have become a rabbit hole! 😄)
