### ISSUE TITLE
Warnings for website and email address tags with invalid formats

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5866]
Email addresses and URLs are easy to validate with regex. We should flag errors with `email` and `website` tag format.

See #5830 for ~~upcoming~~ implemented UI improvements that will surface issues immediately as you edit.

**Comment by boothym** [comment]
I've noticed Firefox highlights the website box red if there is no http:// in the field as it's a type=url - be good to also have it highlight a missing protocol and offer to add it in that PR.

**Comment by SilentSpike** [comment]
Happy to acquaint myself with how validations are added by implementing this 😃

Have some questions on how strict we want to be though - I'm sure you're aware of [the very comprehensive email addresses regex](http://emailregex.com).

For website tags it seems safe to check that they match `^https?:\/\/`, beyond that though I don't know if we want to assume too much about the format they should be in.

Some related things we could also check:
- Websites are not given as a shortened URL
- Websites are not given as a search result link
- Websites are not given as a social media page (should be `contact:twitter`, etc.)

**Comment by quincylvania** [comment]
@SilentSpike It'd be awesome if you could work on this!

I haven't written validation documentation yet, but basically you can duplicate a file in the `modules/validations` directory and go off of that. Most validations just take an entity and context as arguments and return an array of issue objects. Any file in this directory will run automatically, but you can set the order manually in `modules/core/validator.js` (where the issue and fix object structures are also defined).

I think I'd make two separate validations for this issue, one for email addresses and one for websites. I'm not worried about shortened or social media URLs since those sound tricky to consistently validate and there may be okay reasons to use them.

Good luck 😄

**Comment by matkoniecz** [comment]
> Email addresses and URLs are easy to validate with regex

Not really. See for example https://stackoverflow.com/a/201378/4130619

But checking whatever @ character is present is a good idea.

For reference, RFC 5322 compliant regex is supposed to look like this

> (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])

**Comment by 1ec5** [comment]
We should probably allow [IDNs](https://en.wikipedia.org/wiki/Internationalized_domain_name) without requiring mappers to know Punycode. That might complicate the regex for websites and e-mail addresses a bit, because JavaScript `RegExp` character classes aren’t Unicode-aware by default.

**Comment by SilentSpike** [comment]
So right after I decided to implement this my university workload ramped right up 😝 

Now that that stress is over, here are my thoughts after some quick implementation and testing:
- We should probably only check for things that are absolutely invalid (example being missing `@` or `..` present in the local-part of email addresses). See [wikipedia](https://en.wikipedia.org/wiki/Email_address#Syntax) for more examples. This ensures we aren't creating false positives on complex but valid emails.
- Currently with validation of text input tagging it gets flagged as you type it in, this seems like it should be handled more gracefully (ideally validation would only have to run after focus is lost on the text input) which is probably beyond the scope of a PR for this issue.

**Comment by quincylvania** [comment]
> Currently with validation of text input tagging it gets flagged as you type it in, this seems like it should be handled more gracefully (ideally validation would only have to run after focus is lost on the text input) which is probably beyond the scope of a PR for this issue.

@SilentSpike I believe revalidation only occurs after losing focus now. It'd be great to get this rule in iD 2.15.2!
