### ISSUE TITLE
Disconnected highway warning should search deeper than a single connection

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5869]
iD has a warning for disconnected highways, but right now it can be satisfied by a single connection. Highways connected to each other but not the larger road network should still be flagged. This would help prevent "routing islands" like the one pictured:

<img width="501" alt="screen shot 2019-02-05 at 5 03 03 pm" src="https://user-images.githubusercontent.com/2046746/52307315-4c014500-2968-11e9-821e-b2f050e2472f.png">

**Comment by tordans** [comment]
I noticed a few of those while looking at KeepRight-Issues. So they are covered in some of the validation options at least.

**Comment by quincylvania** [comment]
We did this in 2.15!
