### ISSUE TITLE
Disable preset buttons for hidden layers

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5876]
It's not always obvious when a set of map features are hidden. This can lead to users re-mapping features that are already mapped but not shown. This is especially an issue with buildings, since they will automatically be hidden if there are too many.

We should disable the presets associated with the hidden layers, showing a tooltip on hover that informs users of the situation.

<img width="311" alt="screen shot 2019-02-08 at 4 15 27 pm" src="https://user-images.githubusercontent.com/2046746/52506585-07bab280-2bbd-11e9-8b49-8fd4711fd354.png">

<img width="308" alt="screen shot 2019-02-08 at 4 10 01 pm" src="https://user-images.githubusercontent.com/2046746/52506277-0b9a0500-2bbc-11e9-898b-5ab913f388e4.png">

**Comment by bhousel** [comment]
yeah this is actually kind of #2711 too
I like your mockup of disabling the buttons better than my crappy mockup in that thread. 😆

**Comment by quincylvania** [comment]
Oh yeah this is definitely #2711—I missed that! I'll leave this open anyway so we can target this solution.

**Comment by quincylvania** [comment]
This is the UI I added. It works for both manually and automatically hidden layers.

<img width="533" alt="screen shot 2019-02-20 at 1 13 37 pm" src="https://user-images.githubusercontent.com/2046746/53114362-9b6f7580-3511-11e9-96d8-b80335bec960.png">
<img width="472" alt="screen shot 2019-02-20 at 1 13 00 pm" src="https://user-images.githubusercontent.com/2046746/53114363-9b6f7580-3511-11e9-99d1-c5d89cd5e980.png">
