### ISSUE TITLE
Postcode value handling

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5887]
There is a quirk in the way iD handles the case of postcodes such as SA44 6JD (UK postcode).

If I enter it with the correct case, all is fine.  However, the problem occurs if my finger slips on the shift key and I'm not paying attention, so I end up with SA44 6jd.  As long as I don't click or tab away from the postcode field, it's correctable.  But if I click or tab away and later notice and try to correct it then iD **forces** lower-case on me.  I can't change it to 6JD because iD insists that 6jd is the only correct, one and true way, to do it.  I don't even have to save the object first, this happens even before a save.  If I've clicked or tabbed away, iD over-rules me.

If somebody has entered the same postcode, but partly or all lower-cased nearby, then iD helpfully "corrects" my attempt to enter the postcode correctly on another object.  Because iD already knows that particular postcode exists, and it exists with different case so I must be wrong.

I assume that the logic exempting postcodes from the general rule that tag values are lower-case is going a little awry in this situation.

Work-around: enter a nonsense letter into SA44 6jd to give SA44 6zjd, change that to SA44 6zJD, then 
delete the "z".  That's enough to fool iD into letting me do the right thing.

**Comment by bhousel** [comment]
Thanks for reporting @eehpcm 

> I assume that the logic exempting postcodes from the general rule that tag values are lower-case is going a little awry in this situation.

No It's not that - it's just that the postcode combo field looks nearby for existing postcodes and suggests those to you.  Even if it is the one that you already mistakenly typed.

We can make the combo field ignore the case so that you can overwrite the bad data.

**Comment by eehpcm** [comment]
@bhousel 

> No It's not that - it's just that the postcode combo field looks nearby for existing postcodes and suggests those to you.

That's a very strong suggestion.  More like an offer you can't refuse. :)

> We can make the combo field ignore the case so that you can overwrite the bad data.

That sounds good.  Thanks.

**Comment by quincylvania** [comment]
> Even if it is the one that you already mistakenly typed.

It should probably ignore the existing value too if it's the only nearby feature with that value.

**Comment by eehpcm** [comment]
@quincylvania 

> It should probably ignore the existing value too if it's the only nearby feature with that value.

I'm happy with existing behaviour.  Sometimes it's right, sometimes it's wrong.  But whether it's the second or third object with a postal address in the vicinity doesn't affect the probabilities.  As long as it's a suggestion, it's fine even if there's only one nearby feature with a postcode.  If it's right I tab off, if it's wrong I overtype.  It was just the lower-case thing that caused a problem.

Some more things you should know in case you're thinking of other ways in which iD could be more helpful...

There are places in my town where the postcode changes in the middle of a street.  Several houses with one postcode, a side street, the next house and subsequent houses have a different postcode.  That puzzled me for a while, until I realized it was because a mail delivery route went partway along the street then turned onto the side street.  Your proposed change wouldn't help, because the prediction would be wrong.  Fubar Road: seven houses with the same postcode, the next house on Fubar Road ought to have the same postcode, but it doesn't.

You can't fix it by looking at the road name, either.  Yes, postcodes in the UK are such that no two roads have the same postcode.  But (as in my example above) a single road can have more than one postcode.  And, more importantly, several houses along an _unnamed_ road can share the same postcode.  So if it's the same named road then guessing a house has the same postcode as other houses on that road is probably right, but can be wrong.  If it's a different named road the postcode ought to be different (but there may be obscure cases where it isn't).  And if it's an unnamed road all you can do is guess it might be the same postcode as something nearby.

Oh, and organizations that receive a lot of mail can get their own postcode.  Including banks, which in this internet age no longer receive large quantities of mail, but have their own postcode for historical reasons.

**Comment by bhousel** [comment]
I changed the address combos to be
- case sensitive (i.e. don't force user to accept the autosuggested case), and
- ignore the current entity's value when building the list of nearby suggestions
