### ISSUE TITLE
Better pane handling at narrow widths

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5890]
Now that the sidebar is resizable, it looks pointless to width-constrain the panes like this. Currently the user can drag the sidebar over the panes, which is okay. We should think of ways to make this more mobile-friendly.

<img width="398" alt="screen shot 2019-02-14 at 4 22 08 pm" src="https://user-images.githubusercontent.com/2046746/52818423-be62db00-3074-11e9-826b-f54ec7cb33cd.png">

**Comment by tordans** [comment]
@quincylvania do you see any chance to have a dedicated push to get iD ready for mobile and iPad? If so, I would start collecting some thoughts. But until now I had the feeling that this is not on the agenda of any able contributor, so I did not invest the time.
One thing is, that with GoMap!! and Vespucci there is a good(?) mobile solution for each environment.

**Comment by quincylvania** [comment]
@tordans We'd love to have great mobile support eventually but I think there have continued to be higher-priority issues ahead of it (like validation, imports). I see two steps to supporting mobile:

1. Touch support for iPad/Surface-sized screens. This involves adopting the UI to touch necessities such as increasing the size of touch target and creating alternatives to hovering/right-click workflows.
2. Support for smaller iPhone/Android-sized screens. This would involve all of the above plus dealing with limited screen real estate.

While I don't see a dedicated mobile push happening in the very near-future, we should continue to find and address bite-sized problems like this that can add up to something. It's also hard to spend time on a web app for mobile platforms where native apps are king. That said, if anyone wants to invest development in mobile iD then please get in touch!

At some point we'll probably create more encompassing touch/mobile issues where I'd love to hear your thoughts, @tordans!

**Comment by quincylvania** [comment]
I made the panes use the full width of the map up to a maximum width.

<img width="389" alt="screen shot 2019-02-20 at 1 46 07 pm" src="https://user-images.githubusercontent.com/2046746/53116212-1a66ad00-3516-11e9-8570-75b4b9696d1c.png">

**Comment by danieldegroot2** [comment]
> do you see any chance to have a dedicated push to get iD ready for mobile and iPad? If so, I would start collecting some thoughts. But until now I had the feeling that this is not on the agenda of any able contributor, so I did not invest the time. One thing is, that with GoMap!! and Vespucci there is a good(?) mobile solution for each environment.

_See #7639 ._

cc: @tordans
