### ISSUE TITLE
Highway crosses building validation feedback

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#5891]
![image](https://user-images.githubusercontent.com/5459452/52888429-88f0e700-3173-11e9-9583-223f72e84af3.png)

Location: `&map=19.20/57.11650/-2.08751`

Is this a valid quick fix? I think it would make more sense to recommend `covered` or `tunnel=building_passage`.

It's also a little confusing that the issue appears twice for the same entity (because it crosses twice).

**Comment by tordans** [comment]
For reference, I added a similar request to KeepRight at https://github.com/keepright/keepright/issues/93

Apparently there are cases where `building_passage` does not apply according to the last comment.

**Comment by quincylvania** [comment]
@bhousel raised a similar sentiment and I agree we could do better with highway/building crossings. The connection fix is somewhat useful when you want to add an entrance node or split the way and tag the part under the building as covered, but it doesn't do all the rest of that right now. Another option is for a fix that just tags the whole road as `covered=yes`, but this could cause inaccuracies with long roads. 

In any case, you're probably right that there should only be one issue here and not one per crossing.

**Comment by tordans** [comment]
A real time saver where to have a one click action "Split this road and make the part that goes through the building a building_passage".

Another solution might be https://github.com/openstreetmap/iD/issues/5900 to at least provide a place where people can read up on the different cases that one has to think about in such a situation.

**Comment by SilentSpike** [comment]
re: `covered=yes` I believe another valid way to map it is the same as `tunnel=building_passage` where you split the way and connect it to the building then tag the inner part with `covered=yes`. That was my interpretation of the wiki while mapping a while back.

**Comment by quincylvania** [comment]
As I understand it the main differences between `tunnel` and `covered` is that `covered` features are not entirely enclosed and may be anything, not just highways/railways/waterways. I don't really fancy having a quick fix for each though.

Automatically splitting and tagging the way gets complicated if the way crosses the building more than twice or goes through many adjoined buildings.

**Comment by quincylvania** [comment]
So I removed the connection fix from building-highway crossings and made it so only one issue is created per building-feature pair instead of one per crossing. I think this is sufficient for now. The automatic splitting and covering idea seems pretty complicated so I'm not going to worry about it for this issue.
