### ISSUE TITLE
Create preset for amenity=photo_booth

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#5892]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dphoto_booth

- Name: Photo Booth
- Tag: amenity=photo_booth
- Icon: Camera
- Fields: Payment types, operator, wheelchair?
- Terms: photobooth, photo, booth, kiosk, camera

At least in the UK, these are commonplace at shopping centres, train stations, airports etc

**Comment by quincylvania** [comment]
Done in #5894. Thanks, @danielwu830 🎉
