### ISSUE TITLE
Osmose issues list for selected feature

### ISSUE THREAD

**Issue by nlehuby** [openstreetmap/iD#5893]
As a follow up for #5830, it could be great to add Osmose issues list for the selected feature in the editor sidebar.

You can get the list of the Osmose issues for a feature with this endpoint:
http://osmose.openstreetmap.fr/en/api/0.3beta/issues?osm_type=relation&osm_id=2545707&full=true

**Comment by tordans** [comment]
This is a duplicate of https://github.com/openstreetmap/iD/issues/5682, right @nlehuby?

**Comment by nlehuby** [comment]
Not exactly:
* #5682 is about creating a new layer with Osmose issues around
* this one is about adding Osmose issues about a feature inside the sidebar of the selected feature

**Comment by bhousel** [comment]
Duplicate
