### ISSUE TITLE
I get `ground` twice for autocomplete `surface`

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5895]
Location: http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&map=18.21/52.61924/13.35056

Screenshot:
<img width="371" alt="bildschirmfoto 2019-02-17 um 08 01 26" src="https://user-images.githubusercontent.com/111561/52909543-538aed00-328a-11e9-8f72-2b4c071788dd.png">

**Comment by bhousel** [comment]
Me too.. Taginfo is returning 2 and I have no idea why..

- https://taginfo.openstreetmap.org/keys/surface#values
- [results as JSON](https://taginfo.openstreetmap.org/api/4/key/values?key=surface&filter=all&lang=en&sortname=count&sortorder=desc&page=1&rp=15&query=ground&qtype=&format=json_pretty)

**Comment by matkoniecz** [comment]
Looks like a data issue. See http://overpass-turbo.eu/s/HlP

**Comment by matkoniecz** [comment]
I am now running https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/elimination_of_nonprintable_characters_at_start_or_end_of_tags

**Comment by matkoniecz** [comment]
Taginfo updated, and this problem is now fixed. Feel free to ping me in case of similar cases.
