### ISSUE TITLE
Validation: Live validation hits too soon

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5898]
This is less of a usability and more a UX issue.
Right now, as soon as I click the first time, the validation starts screaming ERROR.
Which is true, technical, but not very nice, since I am not finished with my clicking, yet :).

Its a bit like bad pair programming where your peer point out any typo on keypress.

Suggestion: Find some kind of delay. 
Maybe only validate 3 sec after I finished the first drawing (place node, draw line/area)?
Or only once I added the object type?
Or only after I started the next drawing?
(They all have other disadvantages…)

ps: In some of his publications LukeW https://www.lukew.com/resources/web_form_design.asp talks about this for live validating input fields, but I could find the specific source.

**Comment by quincylvania** [comment]
@tordans I noticed this too. You're right that it shouldn't raise the "missing tags" error if the user hasn't finished or exited the feature creation workflow.

**Comment by quincylvania** [comment]
I updated it so the error doesn't appear until the user is done drawing a new line or area. Optimally the user could get all the way through selecting the preset without seeing an error.

**Comment by bhousel** [comment]
Done in #6140
