### ISSUE TITLE
New feature's default tags: remember recent past edits

### ISSUE THREAD

**Issue by nvkelso** [openstreetmap/iD#590]
It defaults to highway=residential now. 

But I've been editing (adding) man_made:pier all day. Each new pier I draw I have to type over these bad highway=residential defaults. 

Init to highway=residential, but build dict of recent tags:values and if a trend develops, default to top edit session tag:value pair.

**Comment by bhousel** [comment]
closing here as stale.. Lots has moved since 2013!
#6010, #6022 and others change the top bar to support "favorites" and "recents"
