### ISSUE TITLE
Re-validate features only as-needed due to further edits

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5901]
Post-#5830, validation occurs constantly while the user edits the map. This comes with a performance cost that increases with the number of features that are validated. Currently, all features are re-validated when any annotated change occurs (like the release of a dragged node, but not the intervening drag events). Instead, we should intelligently re-validate features only after changes occur that affect them. For instance, if the tags are changed on a node we can skip most of the validations for most features. The actual circumstance can get quite complex.

**Comment by bhousel** [comment]
Done in #6140
