### ISSUE TITLE
Option to browse all nearby issues, not just those for edited features

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5906]
Post-#5830, issues with features edited by the user are listed in the pane and issues for the currently selected feature are listed in the inspector. Some users also want to find issues with everything nearby. We should add a "validation mode" option that will list all nearby issues in the pane. This will be especially powerful combined with #5905 and will work similarly to how the KeepRight issues overlay now works.

**Comment by bhousel** [comment]
Done in #6140
