### ISSUE TITLE
Left and right are not languages

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5907]
Today I had to add a highway with left and right names.  Not the first time I've had to do it, but today I was amused by the changes to the edit window handlers (maybe it's been that way for a long time and I hadn't noticed).  After I added the raw tag name:left it displayed a Multilingual Name combo, with the language being "left."

Not a show-stopper, but perhaps a source of confusion to some.

Given fairly recent proposals to extend multilingual name support, you'll probably have to special-case "left" and "right" and a few others to deal with it, because it's no longer as simple as "2 letters = language, everything else is not-language."  If you think it's worth dealing with.

**Comment by bhousel** [comment]
Ah that’s a bummer.. I don’t think we can support this style of tagging.
