### ISSUE TITLE
Post Office preset not showing

### ISSUE THREAD

**Issue by shiftee** [openstreetmap/iD#5910]
If I create a node and type "post" in the search box then the "Post Office" preset is not showing up.

This behaviour is happening on http://preview.ideditor.com/master

Using iD on openstreetmap.org the "Post Office" preset appears.

**Comment by quincylvania** [comment]
Fixed in 3629f6b5b8fb27e85a2efffa9ce086a94cf0a0de. Thanks for finding this!
