### ISSUE TITLE
Move Photo Overlays to their own section

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5913]
<img width="349" alt="screen shot 2019-02-20 at 10 29 19 am" src="https://user-images.githubusercontent.com/2046746/53102855-86d3b300-34fa-11e9-9370-b3d8b943b26c.png">

It's weird that three of these have the same name, with the differentiating part put in parentheses. I propose placing this list in its own section organized like this:

**Photo Overlays**
- Bing Streetside
- Mapillary
    - Traffic Sign Overlay
- OpenStreetCam

**Comment by BjornRasmussen** [comment]
I think that a checkbox for "360 images only" would also be super useful - see this photo:  
[![image](https://user-images.githubusercontent.com/37753777/53527983-5968a580-3ab6-11e9-9d06-84cd8d0de343.png)](https://www.openstreetmap.org/edit#map=19/35.78576/-78.66149)
  
Clicking on 360 images gets very hard without zooming in a lot (Click on the image above to see the area in iD).
