### ISSUE TITLE
Add gambling preset

### ISSUE THREAD

**Issue by sguinetti** [openstreetmap/iD#5915]
With casino POIs, I recommend adding new preset for gambling centers (instead of using leisure: adult_gaming_centre).
* [Tag:amenity=gambling](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgambling) 
* List of gambling centers: [Overpass](http://overpass-turbo.eu/?template=key-value&key=amenity&value=gambling).
* Is popular in Japan (for example, Pachinko)
* Title: "Gambling"

Thanks.

**Comment by higa4** [comment]
amenity=gambling
gambling=pachinko
is an old style tagging of Pachinko.
Currently, we are using
leisure=adult_gaming_centre
instead.
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dadult_gaming_centre
Pachinko is officially not a gamble in Japan, but you can get gifts which have high cashability.

**Comment by quincylvania** [comment]
I'm reluctant to add yet another gambling preset since we already have `amenity=casino` and `leisure=adult_gaming_center`. I don't think most mappers could tell you the difference between these two. Having a third option would be even more confusing.

**Comment by sun-geo** [comment]
when you look here:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgambling#Similar_tags
(to similar tags section), it seems there is another one `leisure=amusement_arcade` available:
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Damusement_arcade
So at all there are 4 options instead of 2 ;-)

`amenity=casino`
`amenity=gambling`
`leisure=adult_gaming_center`
`leisure=amusement_arcade`

**Comment by quincylvania** [comment]
> So at all there are 4 options instead of 2 ;-)

😭 At least `leisure=amusement_arcade` isn't intended for gambling.

**Comment by sun-geo** [comment]
Ah ok, thanks for clarification.
(I'm not a native speaker, maybe it's a bit confusing, I thought "gaming" (leisure=amusement_arcade) is in some way included for gambling activities)

**Comment by bhousel** [comment]
Yeah I agree with @quincylvania. There are too many gambling tags and people won’t understand which one to use.  

Also, the usage on all these tags are so low that people could just change them to something more reasonable. 

Let’s instead encourage the OSM community to invent a less confusing schema for gambling stuff.
