### ISSUE TITLE
Suggestion: amenity=public_building -> building=public

### ISSUE THREAD

**Issue by sguinetti** [openstreetmap/iD#5916]
It is a suggestion to improve the validator that integrates iD Editor (#5830). Its feature proposes to replace the deprecated label to a actual building label.
* See: [amenity=public_building](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_building)

**Comment by quincylvania** [comment]
Thanks for the suggestion, @sguinetti.

**Comment by matkoniecz** [comment]
Note that building tag is for what building was constructed.

For example something constructed as a church now used as, for example, townhall should be still tagged `building=church`.
