### ISSUE TITLE
is there any plan for making iD supporting map rotation

### ISSUE THREAD

**Issue by kavinforever** [openstreetmap/iD#5919]
Hi:
   map rotation is a common behavior while editing tags of ways according to GPS and images. 
is there detailed plans for supporting map rotation?  

thank you~

**Comment by quincylvania** [comment]
We'd definitely like to support map rotation, but it's more complicated than you may think! See #4954. Closing this since we already have that issue for it.

**Comment by jidanni** [comment]
Indeed,  https://josm.openstreetmap.de/ticket/1981#comment:30 :
> And after all let's be frank: rotating a map is a BASIC of the BASICS.
