### ISSUE TITLE
Enter key does not work for selecting item in the search

### ISSUE THREAD

**Issue by LaszloEr** [openstreetmap/iD#5921]
Version: 2.14.1

Expected behavior: writing the name of an object type in the search and pressing enter should select the first item of the results.

Actual behavior in newest version: pressing enter does nothing.

**Comment by Seandebasti** [comment]
Thanks for opening this issue! I firstly did not realize this new update of ID. I had a lot of empty features. It is an automatism in my editing to know what is the common or first item. 

In Version iD 2.14.2 on Mac and Windows / Chrome it also does not work.

As an alternative I had always to click with the mouse to select the first item. This is not effective for my editing. It would be great to solve it.

**Comment by Seandebasti** [comment]
thanks a lot
