### ISSUE TITLE
raw editor - alphabetic order after adding new key

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#5925]
So far I remember* (hopefully correctly) the behavior for v2.13 was like:
after adding new tags through hitting the big plus-button (+) these new lines became sorted alphabetic

Using current v2.14 it seems this "instant-order-mechanism" is switched off.

*btw is there any option to use/test older versions (like v2.13) of iD?
Maybe similar like when you want to test the latest commits which is provided by these available links:
   * Stable mirror of release branch: http://preview.ideditor.com/release
   * Development mirror of master branch + latest translations: http://preview.ideditor.com/master

**Comment by bhousel** [comment]
Yes, the tags will now re-sort when you switch to a different feature.  Some people found it jarring to have the list change as people are using it, and I agree.   I’m pretty sure there was an issue for this but I can’t find it right now. 

> btw is there any option to use/test older versions (like v2.13) of iD?

No, sorry.. People really shouldn’t use older versions of iD.  We are always fixing bugs and making improvements designed to improve the quality of OSM data.

**Comment by sun-geo** [comment]
Thank you for quick response.

> Some people found it jarring to have the list change as people are using it, 

For me it is now jarring a bit if the second new line isn't sorted anymore, but maybe this needs for me some familiarization time... 
> and I agree. I’m pretty sure there was an issue for this but I can’t find it right now.

That's interesting, I would like to see the corresponding issue#


> > btw is there any option to use/test older versions (like v2.13) of iD?
> 
> No, sorry.. 

:-(
> People really shouldn’t use older versions of iD. 

I agree, people shouldn't use it for uploading data, maybe the upload-function could be disabled/blocked. 
But for comparing&testing any functions of an older version it would be a nice opportunity.

> We are always fixing bugs and making improvements designed to improve the quality of OSM data.

I agree - thank you again for the latest effort & changes to the raw editor :-)
