### ISSUE TITLE
Render relation route icon lines dynamically

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5926]
We should render the line part dynamically like did for for the line icons in #5888. This will give us more flexibility and also let us remove redundant icon files.

<img width="349" alt="screen shot 2019-02-21 at 3 53 25 pm" src="https://user-images.githubusercontent.com/2046746/53205467-5e33e200-35fc-11e9-9074-8f7aebe81859.png">

**Comment by quincylvania** [comment]
Not only do the route segments render dynamically now, the segments use the live CSS styles of line features that compose the route. I think they look pretty good!

<img width="342" alt="Screen Shot 2019-04-08 at 7 55 35 PM" src="https://user-images.githubusercontent.com/2046746/55770419-198fc900-5a39-11e9-9785-61965b89c18e.png">

**Comment by bhousel** [comment]
Nice!  looks great 👍
