### ISSUE TITLE
Display preset in issue message

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5929]
I came across an issue which said "<name of railway line> crosses Foot Path". I was confused at first until I realised the first part was referring to a railway line. 

It seems the object name replaces the preset name in the issue message. I think it would be a good idea to display both, to tell users what type of object is causing an issue?

For example: Rail (<name of railway line>) crosses Foot Path (name of path) would be better IMO

**Comment by quincylvania** [comment]
Hmm maybe! We do kinda do this for the relation member list. The downside would be longer issues, which is especially a problem for ways with lots of crossings.

>Contra Costa County Road 120 (Minor/Unclassified Road) crosses Concord Subdivision (Disused Railway)
>Contra Costa County Road 120 (Minor/Unclassified Road) crosses Concord Subdivision (Disused Railway)
>Contra Costa County Road 120 (Minor/Unclassified Road) crosses Martinez Subdivision (Disused Railway)

**Comment by boothym** [comment]
Whoops, seems like my examples got messed up - I had put the railway line name in angled brackets:
 "Rail (name of railway line) crosses Foot Path (name of path)" or "Primary Road (ref) crosses Path (name)"

In your example it is currently Contra Costa County Road 120 crosses Concord Subdivision. I think a new/casual mapper seeing this might be confused about what this means without the road/rail.

The other reason I suggested this is because you could have the exact opposite problem, where your issue message is too short. For example two features which don't have a name but have a ref, e.g. "A1 crosses M2" and be confused about what exactly the problem is, or what it is referring to?

**Comment by bhousel** [comment]
Lets close this.. Since clicking on the message takes you to the issue, and hovering the message will highlight the things, the user can clearly see what kind of features they are by looking, and doesn't need any extra guidance in the message.
