### ISSUE TITLE
Multifunctional site for different languages

### ISSUE THREAD

**Issue by KenyaLS** [openstreetmap/iD#5932]
It is better to make a normal multilingual website and not to highlight the languages of another nationality **Or these icons are not translated.**
![image](https://user-images.githubusercontent.com/20774076/53241838-be8e5680-36c4-11e9-8888-d7eee02e65b8.png)
![image](https://user-images.githubusercontent.com/20774076/53241854-ccdc7280-36c4-11e9-888e-35ca0d5a538d.png)

**Comment by manfredbrandl** [comment]
It Looks like „Road closed“ is not translated on transifex.
![5675f8cc-7a51-406d-8427-df1cf2105d3d](https://user-images.githubusercontent.com/5360273/53242158-37c98180-36a4-11e9-8272-5e7b44d7c2bd.jpeg)

**Comment by KenyaLS** [comment]
So a small part is not yet translated.

**Comment by manfredbrandl** [comment]
@KenyaLS If you translate on transifex you will see the result on preview.ideditor.com/master which gehts an update with the latest translations every ten minutes.

**Comment by KenyaLS** [comment]
@manfredbrandl This is another resource right?

**Comment by manfredbrandl** [comment]
You can translate as described here: 
https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating

**Comment by quincylvania** [comment]
@KenyaLS Yep, unfortunately not everything is always translated so sometimes iD has to fallback to English. It'd be awesome if you could volunteer some translations for everyone's benefit! iD on openstreetmap.org gets the latest translations upon every release.

@manfredbrandl Thanks for assisting with this!
