### ISSUE TITLE
Other features are hidden error

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5934]
Working on a busy area, I have hidden everything but roads and paths in the map data panel. I drew a line to create a foot path, however when typing "foot" in the preset search box all of the presets are greyed out.

I assume this is because I have "others" disabled, as it works when that is enabled. Bit too strict on the validation as every untagged line comes under the "others" category!

**Comment by quincylvania** [comment]
@boothym Hmm this is definitely a bug. Disabling "Other Features" shouldn't disable everything.

<img width="777" alt="screen shot 2019-02-22 at 10 10 10 am" src="https://user-images.githubusercontent.com/2046746/53251205-23788b00-368a-11e9-99fe-129a2f0fff3d.png">
