### ISSUE TITLE
Validation: Deprecated tags (footway= both / right / left / none)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#5935]
I saw here #5916 you are currently collecting deprecated tags.

I incidentally found footway= both / right / left / none
https://wiki.openstreetmap.org/wiki/Key:footway#Values

If it is not used for validation & it would make sense for adding, feel free to do so :-)

**Comment by sun-geo** [comment]
maybe one more:
`amenity=sauna` => `leisure=sauna`
see: https://wiki.openstreetmap.org/wiki/Tag:amenity=sauna

**Comment by quincylvania** [comment]
@sun-geo Thanks for the suggestion! We already had `amenity=sauna` 😄🧖‍♂️
