### ISSUE TITLE
highway line becomes thinner when key footway=* is added

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#5936]
See picture, is this on purpose?

![footway](https://user-images.githubusercontent.com/47290585/53250078-f8a62b00-36b9-11e9-8b4f-f4ad61459963.png)

**Comment by quincylvania** [comment]
Generally speaking, `footway=` should only be on a way with `highway=footway`, so while we can fix this I don't see it as a major issue. With #5935 people can easily upgrade erroneous `footway=` anyway!
