### ISSUE TITLE
Error when selecting preset

### ISSUE THREAD

**Issue by map93-osm** [openstreetmap/iD#5939]
1. Create a new feature.
2. Start typing in the search box to select a preset.
3. Press enter.

The first preset in the list should be selected (as it was until recently). Instead, nothing is selected, and an error occurs:

<img width="1433" src="https://user-images.githubusercontent.com/47910776/53282338-f1077600-36fb-11e9-933c-211e6f2a32cd.png">

**Comment by quincylvania** [comment]
Probably the same as #5921. Thanks for the stack trace!
