### ISSUE TITLE
Escape throws an error when drawing area with only one point

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5941]
```
[Error] TypeError: undefined is not an object (evaluating 'entity.id')
	isInvalidGeometry (iD.js:60348)
	checkGeometry (iD.js:60313)
	finish (iD.js:60522)
	call (iD.js:786)
	ret (iD.js:30157)
	testBindings (iD.js:28419)
	bubble (iD.js:28477)
	(anonymous function) (iD.js:1527)
```

Possibly related: #5911

**Comment by maxgrossman** [comment]
hmmm... seems to be a scenario where `graph.childNodes `does not return all nodes in the way...

![image](https://user-images.githubusercontent.com/15100429/53290862-4b461c80-3778-11e9-8435-23a3d9c56754.png)

Is there reason why we could not just use the parent's `node` property? I will keep digging into childNodes function too

**Comment by jguthrie100** [comment]
I think those are changes I made some time last year to check if an area self intersects.

It probably just needs an if() statement to avoid the instance when there is only 1 node (i.e. nodes.length-2 resolves to -1 and hence entity gets set to undefined)

**Comment by jguthrie100** [comment]
#4860

**Comment by jguthrie100** [comment]
@maxgrossman what happens if you inspect the node immediately after `graph.getChildNodes(parent) ` is called?

All the nodes should probably be there in that case, but in your screenshot, `nodes.splice()` has already been called, which will remove a node.

**Comment by jguthrie100** [comment]
@quincylvania Out of interest, `graph.childNodes(way)` might actually be slightly dangerous, in that modifying a variable that was set to `graph.childNodes(way)` will change the underlying `childNodes` value.

![image](https://user-images.githubusercontent.com/4670502/53580592-e02f8800-3b73-11e9-812a-8b22593a33b6.png)

Presumeably, the underlying `childNodes` data should always remain constant, regardless of what the user does with any assigned variables, unless its meant to be like this?

**Comment by bhousel** [comment]
> Presumeably, the underlying `childNodes` data should always remain constant, regardless of what the user does with any assigned variables, unless its meant to be like this?

Yes you should always `_clone()` the result of childNodes if you intend to modify it.

**Comment by jguthrie100** [comment]
Is it worth forcing it through in the childNodes method and _clone-ing it before returning?

**Comment by bhousel** [comment]
> Is it worth forcing it through in the childNodes method and _clone-ing it before returning?

I don't understand what you're asking.

**Comment by jguthrie100** [comment]
As in:
https://github.com/openstreetmap/iD/blob/c09171d0e2c597c4d8b51accfb3b4642f64d7094/modules/core/graph.js#L107

`return this._childNodes[entity.id]` could be `return _clone(this._childNodes[entity.id])`

**Comment by bhousel** [comment]
> `return this._childNodes[entity.id]` could be `return _clone(this._childNodes[entity.id])`

It's extremely hot code, so I'd rather not introduce an extra `_clone` when it's usually not needed.
