### ISSUE TITLE
"Use different layers" warning not clear

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/iD#5943]
This might be an example where reusing icons for different purposes hurts usability. Both the "Background settings" icon in the right panel, and the "Use different layers" warning share the same icon. Both of them talk about some "layers", but essentially they mean quite different things. The one talks about image layers, the other about adding/changing some `layer` tag to/on an existing object (at least that's what I assumed).

![layer1](https://user-images.githubusercontent.com/5842757/53290024-e5b95680-379e-11e9-8462-444a12714d91.png)

![layer2](https://user-images.githubusercontent.com/5842757/53290025-e6ea8380-379e-11e9-9124-050553ab02a2.png)

Unfortunately, there's no indication as to what a "layer" is supposed to be in this context. The UI lists a "levels" tag further down in the list, which again is some different concept:

![layer3](https://user-images.githubusercontent.com/5842757/53290105-eef6f300-379f-11e9-81be-31f81c06174e.png)

Overall, the UI gives me no indication on how to proceed, and how to fix that warning.

In case of two overlapping buildings. the wiki suggests to use the level=* key instead (according to the "Simple Indoor Tagging"). However, the validator isn't aware of this level=* tag and still reports the same warning.

**Comment by SilentSpike** [comment]
I think this is where something along the lines of #5900 would help

**Comment by quincylvania** [comment]
@mmd-osm Thanks for raising this issue, I agree it was somewhat confusing. I replaced the "Use different layers" fix with a pair of fixes where you just tell iD if the selected feature is a higher or lower layer than the other.

An example for crossing tunnels with equivalent `layer` tags:

<img width="336" alt="Screen Shot 2019-04-01 at 11 53 11 AM" src="https://user-images.githubusercontent.com/2046746/55341502-c3d58280-5474-11e9-8cba-52c746ac626b.png">
