### ISSUE TITLE
How can I help in contributing in the code of ID

### ISSUE THREAD

**Issue by Seandebasti** [openstreetmap/iD#5944]
Hi ID,

I am using ID for an long time. I am really thankful for the many updates the authors coded.

For example, I did realize the intermittent tag would be very useful to combine it with stream to have this as an own item. I like to set more combined tags which are useful. 
I saw the last update, with successful tags like communication mast.

How can I join to drop some improvements?

Thanks

**Comment by bhousel** [comment]
Welcome! 
[README](https://github.com/openstreetmap/iD/blob/master/README.md) and [CONTRIBUTING](https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md) should give you all you need to get started.. Also feel free to drop into Slack and say hi!
