### ISSUE TITLE
Rendering: highway osm-way-direction information concealed by name-value

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#5946]
**Current behavior:**
highway osm-way-direction triangle is concealed by highway name-value or highway ref-value

**Expected behavior:**
ideally to see osm-way-direction triangle and highway name-value at the same time.
But for the moment I don't know a fast idea for solution. :-(
Because I assume the triangle icon is placed by purpose in the middle of a line and I like to see it at this position because it is and very nice indicator if you want to add another node in the middle :-)
So adding more triangles I don't prefer...
Adding or moving the name/ref-text, could that work?

**Screenshot for illustrating the situation:**
![ref-dir](https://user-images.githubusercontent.com/47290585/53293948-f1783d80-37dd-11e9-9236-8ec20aa269db.gif)

**Comment by bhousel** [comment]
As you can see in the screenshot, the label goes away if you move the mouse over it. 

Also
- the direction that a way is drawn is not very interesting except in a few situations (steps, moving walkways?.. coastlines, oneways, directional vertices like cameras, traffic signals? We render markers and viewcones for many of those)
- the label on the way is very important
- your screenshot shows a worst case situation.. a short way with a long label

I will check and see if there is a simple fix in the label placement code, but I don’t want to render more triangles.

**Comment by Thorwynn** [comment]
IMO we only need to see the arrows while we are editing the element, so the desired behavior should be that the label(s) on the street should always disappear when the street is selected. (They always seem to obscure what I need to see while editing.) The name labels are easily seen in the tag panel on the left when selected so its not a big deal if they disappear from the map when selected. If something beyond this is wanted, then a toggle to switch off all labels might be nice.

**Comment by bhousel** [comment]
closing as low-impact, sorry..
