### ISSUE TITLE
Add bar=yes field

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5947]
Hello. Would it be possible to add a preset for bar=yes to the list of possible tagging options for restaurants, cafes, and hotels? 

Thanks

**Comment by quincylvania** [comment]
https://wiki.openstreetmap.org/wiki/Key:bar

**Comment by alphagamer7** [comment]
Hi @quincylvania @Adamant36 , 
Could I start working on this issue? If so can you kindly give me a suggestion on where to start.

**Comment by quincylvania** [comment]
@alphagamer7 That would be great! Check out the documentation for presets and fields: https://github.com/openstreetmap/iD/tree/master/data/presets

After getting iD setup, you'll want to add a new file with a `check` field for the `bar` key. Then add the field id to the `moreFields` arrays of the relevant presets (`amenity/restaurant` and so on). Run iD and make sure it works as expected. Then commit your changes, including the derived data.
