### ISSUE TITLE
Jeweler versus jewelry shop in search

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5948]
Currently when you do a search for jewelry the default says Jeweler. Although after you click it the tag it uses is shop=jewelry. There's a difference between a jeweler (someone who creates or repairs jewelry) and a jewelry shop (a place selling jewelry. Although I guess there can be some overlap, it would still be nice if the name the preset was jewelry shop. Since that's what the tag being used by it is. There's also a craft=jeweller for places that are specifically for that. Maybe it could have its own preset.

**Comment by quincylvania** [comment]
@Adamant36 I changed the name to Jewelry Store since you're right that not every place that sells jewelry is technically a jeweler. I didn't add `craft=jeweller` since I'm not sure people would necessarily know which to pick.

**Comment by Adamant36** [comment]
That's fine. Thanks.
