### ISSUE TITLE
Do not suggest amenity=public_building -> building=public

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5951]
Note that building tag is for what building was constructed.

For example something constructed as a church now used as, for example, townhall should be still tagged `building=church`.

Therefore assuming that all `amenity=public_building` should be converted to `building=public` is a poor idea.

So I suggest to revert https://github.com/openstreetmap/iD/commit/e5e547ff530f435c6556c195256f72e142fb2efc

@quincylvania @sguinetti

**Comment by quincylvania** [comment]
@matkoniecz Thanks for your suggestion, but I think the current behavior is okay.

- We're going [off the wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_building) here which expressly recommends using `building=public` as a replacement.
- Only about [4% of features](https://taginfo.openstreetmap.org/tags/amenity=public_building#combinations) with `amenity=public_building` have a building tag that would be overwritten anyway.
- This is a common deprecated tag. We're not just going to remove the warning entirely.
- You can ignore or manually resolve the warning without clicking the upgrade tags button, using any values you want.

**Comment by matkoniecz** [comment]
OK, I would do it a bit differently but I agree that even in the worst case there is no significant damage of data.

> We're going [off the wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_building) here which expressly recommends using `building=public` as a replacement.

I amended wiki a bit https://wiki.openstreetmap.org/w/index.php?title=Tag%3Aamenity%3Dpublic_building&action=historysubmit&type=revision&diff=1807446&oldid=1560426 (if you think that my edit made wiki page worse feel free to improve it)

**Comment by quincylvania** [comment]
@matkoniecz Thanks for understanding!

> if you think that my edit made wiki page worse feel free to improve it

I try my best not to touch the wiki 😆
