### ISSUE TITLE
add deprecation rules for popular wood/type values

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5958]
Ideas from https://josm.openstreetmap.de/browser/josm/trunk/data/validator/deprecated.mapcss not present in https://github.com/openstreetmap/iD/blob/master/data/deprecated.json appearing 1000+ times worldwide (less popular ones were ignored)

type=conifer https://taginfo.openstreetmap.org/tags/type=conifer

wood=mixed https://taginfo.openstreetmap.org/tags/wood=mixed

wood=deciduous https://taginfo.openstreetmap.org/tags/wood=deciduous#overview

**Comment by quincylvania** [comment]
@matkoniecz Thanks for the suggestion!
