### ISSUE TITLE
A vale of tears

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5962]
I just had problems trying to add a valley (which I did despite knowing that it currently won't render).

Firstly, I can't search for it in the select feature page.  So I search for "natural", select one of the two features it offers me, then manually change the tags.

Secondly, the issues inspector tells me that a valley should be a closed area based on the tag natural=valley.  That's not what [the wiki page](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dvalley) tells me.

Maybe the wiki page has it wrong, and if I made it an area it would render.  I doubt it.

**Comment by bhousel** [comment]
Oh, this is just because iD doesn’t have a valley preset yet so it doesn’t know that it’s an exception to the rule that `natural` features should be mapped as areas.

**Comment by quincylvania** [comment]
This is the same underlying issue as #5933.
