### ISSUE TITLE
Background "OpenStreetMap (Standard)" should fetch fresh tiles after each save

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5965]
Seems to make sense that background "OpenStreetMap (Standard)" should fetch fresh tiles (if "possible").
I mean we are tying to build upon our edits in an area... so maybe get fresh tiles exactly once after each save... not too wasteful indeed, just the tiles for the area we are looking at when we made the save.

**Comment by jidanni** [comment]
OK, I see it currently gets the tiles the same way as when not editing OSM.ORG. So the user will probably see a mix of old and new tiles as he zooms in and out. Hmm, well maybe make sure they all get refreshed...

**Comment by quincylvania** [comment]
The tiles are rendered and cached on external servers. iD has no control over when any of the tiles are refreshed.
