### ISSUE TITLE
Leave more features on the screen at zoom levels <= 15

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5966]
Try this experiment:

1. Go to https://www.openstreetmap.org/edit#map=16/24.2540/120.9076 .
2. Select Background: none. So far so good...
3. Now [zoom out one level](https://www.openstreetmap.org/edit#map=15/24.2540/120.9076).
4. Observe how almost everything on the map disappears. How frustrating.

No we don't want to actually edit at zoom level 15, but do kindly leave
more features there. Yes we could use background "OpenStreetMap
(Standard)", etc. but we were happy with background: none... until all those
features disappeared. Apparently a value judgment has been made for what
features shall disappear at zoom levels <= 15.

**Comment by bhousel** [comment]
> Apparently a value judgment has been made for what features shall disappear at zoom levels <= 15.

It's just - all features.  What you are seeing at lower zooms is just a raster overlay.  iD fetches no data at these zooms.  We might change it someday, but I'm closing it for now as it's not something we can really change without rewriting several parts of iD.
