### ISSUE TITLE
Perfect squares cannot be squared as they are not squarish

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#5967]
Currently when a perfectly square way (such as [this one](https://www.openstreetmap.org/way/542259792)) is attempted to be squared by either <kbd>s</kbd> or `right click` + `square`, it returns the message `This can't be made square because it is not squarish.`

This can be confusing as it obviously looks square and the user may experience an existential crisis as a result of being told a square is not squarish. This would seem to be a race case but it would be nice to have a condition of some sort that gives a different message or just squares it anyway.

**Comment by bhousel** [comment]
Ah yeah, this is because the code uses dot products to check for squareness, but a perfect 90° angle will have a dot product of 0.  

I'm going to take a pass over the orthogonalizing code today and try to fix this and a few old related issues.. (#1979, #2472)

**Comment by quincylvania** [comment]
We should also be smart with feedback on straightening lines if they're already straight.

**Comment by bhousel** [comment]
> We should also be smart with feedback on straightening lines if they're already straight.

Yeah - I almost put this into #5999 but I'm holding off until I merge #5740 to avoid conflicting @jguthrie100's work
