### ISSUE TITLE
Suggestion: railway=preserved (validation)

### ISSUE THREAD

**Issue by sguinetti** [openstreetmap/iD#5969]
I found, in addition of  #5968, [this page](https://wiki.openstreetmap.org/wiki/Deprecated_features) of the OSM wiki. One of them is [railway=preserved](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dpreserved).

The recommend solution is:
* railway=rail +
* railway:preserved=yes

 What is your opinion? Thank you.

**Comment by bhousel** [comment]
Please do not open issues just based on stuff you found on the OSM Wiki. 

We should check with taginfo how frequently the deprecated and replacement tags are used, and it’s even better if these requests come from someone who actually cares what the tags are and is using them for something.

**Comment by quincylvania** [comment]
@sguinetti It doesn't look like there's consensus on deprecating `railway=preserved` so we're not going to do this at the moment.
