### ISSUE TITLE
Cannot merge nodes on a certain road

### ISSUE THREAD

**Issue by rene78** [openstreetmap/iD#5973]
It is no longer possible to delete nodes by dragging one node on top of another one on a certain residential road:
https://www.openstreetmap.org/edit#map=17/9.48418/100.02637
The nodes of the unclassified roads nearby can be merged as usual.
Browser: Chrome V72.0.3626.109

**Comment by quincylvania** [comment]
@rene78 Thanks for reporting this! I'm closing this as a duplicate because I think #5942 is the same thing, but your description and link helped me figure out what they meant 😀
