### ISSUE TITLE
Preview edits before save

### ISSUE THREAD

**Issue by filips123** [openstreetmap/iD#5974]
There should be the support to preview edits before saving. There should be a button "Preview" next to "Save" which would render changes as normal OpenStreetMap.

This is because sometimes, objects are shown differently in the editor and real map.

**Comment by bhousel** [comment]
Sorry, this isn’t possible in an app like iD.

**Comment by filips123** [comment]
Why? Is there some alternative?

**Comment by bhousel** [comment]
OpenStreetMap’s map tiles are rendered on the server using a very different technology.  

Besides, the openstreetmap-carto rendering is just one of many that uses OSM data, and how they render things is not all that interesting.  Billions more people use OSM data on other maps.

**Comment by filips123** [comment]
Is it possible to export map of specific area from iD and then import it to openstreetmap-carto manually?

**Comment by bhousel** [comment]
This might be possible if you host your own copy of the openstreetmap stack. I’m not sure.

**Comment by jidanni** [comment]
Oh. I was just going to submit this... even if it is different technology...

Idea: add a simple "Preview" button.

We are all familiar with preview buttons. There is even one above this issue entry form while I am typing it in.

So as a **long term wishlist item** it would be great if iD had one too, before users, with best intentions, still [blow away bridges](https://github.com/gravitystorm/openstreetmap-carto/issues/3805#issuecomment-501146057), panic, and do not know how to recover. (Pressing "Undo" was for before pressing "Save". Pressing it again will just get the user into further trouble.)

Sure, one could say "Well which of the five layers (...cycle, humanitarian...) are we supposed to show the preview in? Not all are updated that soon anyway." Well, the standard layer.

Anyway, as even this GitHub has full "preview" and "undo after the save" capabilities (at least on Desktop.) Then the much more powerful/dangerous iD should have at least "preview" too.
