### ISSUE TITLE
OSM troubleshooting

### ISSUE THREAD

**Issue by VernonLangley** [openstreetmap/iD#5978]
Hello,
When I select an OSM link that has been saved in a google doc, the link sends me to the location however when I open different node links to other locations OSM sends me to the exact same location I had before. Has anyone experienced a similar issue or know how I might resolve this?

**Comment by quincylvania** [comment]
@VernonLangley Can you provide examples of these links?

**Comment by VernonLangley** [comment]
@[quincylvania](/quincylvania) https://www.openstreetmap.org/edit?node=42852478, https://www.openstreetmap.org/edit?node=42524611. These two are node location however they will send me to a location that I had loaded before with OSM.

**Comment by VernonLangley** [comment]
I ended fixing the problem. I went to My Setting and and made ID my preferred Editor.

**Comment by quincylvania** [comment]
@VernonLangley Great! I couldn't reproduce this issue so that makes sense.
