### ISSUE TITLE
JOSM Presets

### ISSUE THREAD

**Issue by mparrault** [openstreetmap/iD#5981]
Are iD presets available in the XML format required by JOSM (see [here](https://josm.openstreetmap.de/wiki/TaggingPresets))?  I know they are for the [Name Suggestion Index](https://github.com/osmlab/name-suggestion-index), which is great.  JOSM presets are much more limited than iD's, and having iD presets in JOSM would be very useful.

**Comment by bhousel** [comment]
> Are iD presets available in the XML format required by JOSM?

Not AFAIK, but someone could create this.

[id-area-keys](https://github.com/osmlab/id-area-keys) is an example of a project that just imports the iD presets and generates a file from them, so it's pretty easy to do.
