### ISSUE TITLE
Improve recommendations for node in building (vs roads)

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5982]
When I select a node that is part of a existing element like a road or a building, the recommendations in the preset panel could be more specific for the select element.

Road => Recommend `highway=turning_circle` and such
Building => Recommend `entrance=yes` and such

Right now the recommendations seem to be the same for all(?).

Let me know if more specs-ideas would help.

**Comment by bhousel** [comment]
this is #5326
