### ISSUE TITLE
selected element will not move always

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#5985]
### Expected behavior
after disconnecting a shared* node with tag (e.g. highway=bus_stop) then the node of the selected element (either way or area) should also used for a potential move afterwards
*shared e.g. with way(highway=tertiary) and area(landuse=residential) 

### Actual behavior
sometimes the other element is moved (this behavior is annoying and persist for a long time - i was just too lazy to report it... )

steps to reproduce:
0. have two shared elements: e.g. way highway=tertiary (should also happened for highway=*) and an area of e.g. landuse=residential (should also happened for landuse=*)
0. have a shared node on this structure with tag highway=bus_stop or highway=stop
1. select a shared node (e.g. highway=bus_stop)
2. right mouse click => disconnect
3. select the area (landuse=residential)
4. move the node (highway=bus_stop):
      => the node and line of area (landuse=residential) is modified:  OK   :-)
5. combine the nodes (highway=bus_stop) of way and area
6. select a shared node (e.g. highway=bus_stop)
7. right mouse click => disconnect
8. select the area (landuse=residential)
9. move the node (highway=bus_stop):
      => the node and line of way (highway=tertiary) is modified:  not OK   :-(

### Screenshots illustrating the current situation
by using the preview.editor.com:
![move selected5](https://user-images.githubusercontent.com/47290585/53437509-ffa4a480-39fd-11e9-9131-30075c16a4b1.gif)

**Comment by sun-geo** [comment]
ps: please correct/change the issue subject title text for better understanding

**Comment by bhousel** [comment]
This is #2206
