### ISSUE TITLE
Disconnect disconnects all roads

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5987]
"To disconnect a road from another feature, right-click the connecting
node and select the Disconnect command from the editing menu."

Alas, if the connecting node has other roads sharing it, the user ends
up disconnection **all** roads, with no workaround!

P.S., maybe use more general language than just "roads".
![1](https://user-images.githubusercontent.com/1230959/53460358-d0327e00-3a77-11e9-8022-47dcfd1b4ec7.jpg)

**Comment by quincylvania** [comment]
@jidanni If you select both the line and the node then disconnect them, only the selected line will be disconnected, leaving the other lines connected.

**Comment by jidanni** [comment]
Sure. But the more the user works on the problem, the more the impending
signs of disaster appear. Try it yourself.

Your job, at point
https://www.openstreetmap.org/?mlat=24.15400&mlon=120.69738#map=19/24.15400/120.69738
is to simply give only the road leading east (right), the name "自強街40
巷".

You will see if indeed, with various shift and control key plus click
combinations, he is able to do what you say, he still gets not one but
two warnings in the left panel that he is wrecking things etc.

Anyway, 100% not something that one could attempt merely reading the
help message I posted.

Hence such intersections will never get edited by normal users, who do
not want to wreck the map.

Yes even if it just seems they are wrecking the map.

The only way it is going to work is if you link a full page tutorial
from that help message.

Thank you.
