### ISSUE TITLE
hash-url-params treated differently from regular params? (Was: Is the `?locale=en`-feature broken?)

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5988]
With https://github.com/openstreetmap/iD/pull/5650 we introduced a feature that allows to set the editor locale via an url param ([API](https://github.com/openstreetmap/iD/blob/master/API.md)). However, I cannot get it to work anymore.

Example: https://www.openstreetmap.org/edit#map=19/50.81751/6.36161&locale=fr

Current behavior: It removes the param from the URL but does not change the language of the UI.

Did anything change? Or am I doing it wrong?

**Comment by mmd-osm** [comment]
You're doing it wrong™

Correct link is: https://www.openstreetmap.org/edit?editor=id&locale=fr#map=19/50.81751/6.36161

**Comment by tordans** [comment]
Thanks @mmd-osm.

I am pretty sure that at some point iD treated hash-params the same as regular params – in the PR I wrote "With the hash-url locale=en-US … one can force a locale and language".

But maybe that changes. I wonder if that is a bug or by design?

**Comment by mmd-osm** [comment]
Well, only the standalone iD version seems to support hash-url at this time:

http://preview.ideditor.com/release/#background=Bing&locale=fr&map=5.58/65.130/35.646
