### ISSUE TITLE
Remove Hashtag-Section with Trash-Button on the Save-Screen

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5989]
_Current behavior:_

- I write a save-message with a #hashtag.
- The editor reads the message and adds the hashtag-section with that tag. Which technically translates to the key-value pair of `hashtags="#hashtag"`.
- (⦿)But I dont want to add this hashtags-key, so I click the trash-button on the hashtag-section.
However, the editor does not allow removing the section as long as the save-message includes the given wording. So the trash-button does nothing.

In order to remove the section, I first have to …
- rewrite the save-message first
- then click the trash-icon – the editor does also not remove it automatically (which I agree with)

_Suggested improvement:_

At step (⦿), when I click the trash icon the section should be deleted, regardless of what the message says.

The section should only be re-added once I re-write the save-message. And after I finished rewriting, if there still is a hash-tag, the editor will re-add the section (which in some cases I might re-delete again).

_UseCase:_

Its a good thing that iD saves the last save-message. However, after saving something with a hashtag, my flow is: 
1. mouse based: click save, move to the side-panel, remove the section, click in the save-message
2. keyboard based: type the save-message
3. mouse based: click save

With the current behavior I need to switch more between mouse and keyboard, which is not ideal (https://en.wikipedia.org/wiki/GOMS).

**Comment by bhousel** [comment]
> But I dont want to add this hashtags-key, so I click the trash-button on the hashtag-section.

Why?
