### ISSUE TITLE
 complain about unreasonably narrow highway=pedestrian 

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5991]
What steps will reproduce the problem?
1. Create way
2. Tag it `highway=pedestrian` `width=0.5` `name=Foobar`
3. Run validator by selecting element or uploading

What is the expected result?

Validator offers automatic fix to `highway=footway`

What happens instead?

Nothing.

Please provide any additional information below. Attach a screenshot if possible.
I propose 2 m as the edge value. Optionally 1 m.

Inspired by https://lists.openstreetmap.org/pipermail/tagging/2019-February/043221.html

> Venice is a globally unique (or maybe almost unique) exception anyway, but
> what we currently have there is the result of people reclassifying all the
> footways as pedestrian roads, even if they are 50 cm wide. I have started
> in the past several attempts to open a discussion on this, but it felt like
> Don Quixote. See this as an example:
> https://www.openstreetmap.org/way/488627565/history I have surveyed it
> myself, like many others, where I began to reclassify the very narrow
> footpaths from pedestrian to footway, but I am not local and people destroy
> the finer grained distinction of footway and pedestrian as soon as you add
> them, I guess they do not want the red dots. It is unfortunate, because it
> makes the Venice map much harder to read and less useful. If you are local,
> please try to improve the situation, we do not need new tags, it would be
> sufficient to apply the existing ones consistently rather than
> indiscriminately.

JOSM equivalent at https://josm.openstreetmap.de/ticket/17391

**Comment by smz** [comment]
Hello! 

I live in Venice and AFAIK there are no roads which are 50 cm wide or less here.
The narrowest I know of is "Calle Varisco" which is about 53cm wide: https://www.openstreetmap.org/way/153884207 (see picture here: https://www.google.com/maps/@45.4411347,12.3392042,3a,75y,301.28h,88.18t/data=!3m6!1e1!3m4!1sILSBOGbqsP4gBQ7A2h-YvA!2e0!7i13312!8i6656)

There are anyway several narrow roads between 1 and 2 meters wide and trust me, it is not fun to go through those roads when a group of 10 or more tourists goes in the opposite direction with all their huge suitcases or when they stop in the middle checking their Google Maps or whatever.

Cheers,
Sergio

**Comment by dieterdreist** [comment]
The way that I referenced (and tagged) as 50cm was around 50cm wide, similar to the one in your link, I did not measure it and it may be actually 60 cm, at least it was less than one meter. Measuring to the cm is not possible anyway as the width slightly varies

**Comment by bhousel** [comment]
This sounds reasonable..

I wonder if there are other ways we could hint to the user that a `highway=pedestrian` is really for the sort of road where one might consider driving a vehicle but can’t.  (Eg they could render with thicker strokes)

**Comment by quincylvania** [comment]
This seems outside the scope of iD's current validation goals. Closing as low impact.
