### ISSUE TITLE
complain about access=restricted

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5992]
Someone decided that we need competing tagging scheme for tagging access and created `access=restricted`. See https://wiki.openstreetmap.org/wiki/Tag:access%3Drestricted and https://wiki.openstreetmap.org/wiki/Talk:Key:access#Maybe_introduce_a_Key:access.3Drestricted_.3F

JOSM already complains about it and it would be useful to do the same in iD ( note that it is used 6k times, not so often to consider it as a real competitor of standard access tagging but worth adding validator warning to stop it - see https://taginfo.openstreetmap.org/tags/access=restricted )

**Comment by bhousel** [comment]
So... Someone introduces a tag 5 days ago.. it's now used 6k times.. and you want us to write a validator to stop people from using it? 

come on...

**Comment by matkoniecz** [comment]
Tag is certainly much older - random example from 5 years ago ( https://www.openstreetmap.org/way/266904074/history )

http://taghistory.raifer.tech/ shows that most of uses was added by import/automatic edit and that usage is slowly decreasing since 2015 
![selection_005](https://user-images.githubusercontent.com/899988/53514252-99845400-3ac7-11e9-9478-d6970f21f245.png)

**Comment by bhousel** [comment]
> Tag is certainly much older - random example from 5 years ago ( https://www.openstreetmap.org/way/266904074/history )

Oh ok.. Sorry, it sounded like you wanted to use our validator as ammunition in some wiki edit fight you are currently having with some user.  

I don't see anywhere a consensus that the tag is deprecated, and I would expect to see more discussion of this for a tag that's been around for 5 years.  I just see that you created a wiki page today (and are continuing to edit it) and are talking to the other person on a forum and on wiki comments this week and maybe the tagging mailing list.  

I'm ok with having iD just suggest "upgrading" the tag to `access=private`.  As long as there is actual consensus and nobody is using the tag for anything.
