### ISSUE TITLE
New validation rule: no cuisine=vegetarian/vegan

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#5993]
In the same vein as #5580, to avoid a deprecated tag scheme.

**Comment by matkoniecz** [comment]
It probably should not be assumed that `cuisine=vegetarian` is `diet:vegetarian=only`, it probably may also be `diet:vegetarian=yes`.

Is there way already to offer two upgrade paths in iD validator?

**Comment by quincylvania** [comment]
> Is there way already to offer two upgrade paths in iD validator?

Not at the moment. I've considered this but I think it's nicer to have a single Upgrade button.

**Comment by matkoniecz** [comment]
Note that changing `cuisine=vegan` to `diet:vegan=yes` may be incorrect, where it should be `diet:vegan=only`.

"I think it's nicer to have a single Upgrade button." is OK but in that case validation rules that require it should not be introduced.

**Comment by quincylvania** [comment]
On the contrary, `diet:vegan=yes` would always be correct while `diet:vegan=only` would only sometimes be "more correct". We don't know if the original tagger would have meant `only` or `yes` anyway so we should go with the less restrictive option.

**Comment by matkoniecz** [comment]
But it means that while (AFAIK) people used `diet:vegan=yes` to mark "vegan food is available, but nonvegan is also available" now it mean "vegan food is available, nonvegan - who knows".

Though admit that it is not an ideal tagging scheme:(
