### ISSUE TITLE
Prioritise relation dropdown based on type

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5997]
I may have mentioned something similar elsewhere but I did a search and couldn't find anything.

I was looking to add a cycle route relation to a highway=cycleway - but had to scroll down to the bottom of the relation dropdown, past bus routes, coastline/island, railway, road, administrative relations to find the relation I wanted.

Two things iD could do to improve this example, first one would probably be the best and least disruptive:

- prioritise the cycle routes so they are displayed at the top
- only show the cycle routes, hiding every other relation that would be an invalid combination

**Comment by bhousel** [comment]
We can't really do this because iD doesn't currently have any knowledge about which kinds of relations go with which other kinds of other features.  

This makes sense if you think about it, because everything about OSM is totally made up and there is no real schema.

**Comment by boothym** [comment]
Ok, but what sets the order of relations in the dropdown? Because it seems a bit random.

What about if a bit of knowledge was added to iD - like some basic logic which prevents route=bus relations appearing in the dropdown on a highway=footway/cycleway/path?

**Comment by bhousel** [comment]
> like some basic logic which prevents route=bus relations appearing in the dropdown on a highway=footway/cycleway/path?

How would iD know that?

**Comment by boothym** [comment]
I don't know what goes on under the hood - but iD recognises a path as it displays the path preset, and the relation dropdown displays route=bus as "Bus route (name of relation)". 

Perhaps it preset files could hold information on which relations to exclude, and the code checks that before populating the relation dropdown?

**Comment by bhousel** [comment]
Closing here, as I can't think of a really great solution that doesn't involve creating a new mapping of all the things to all the other things.

**Comment by boothym** [comment]
@bhousel ok, but are you able to explain the ordering of the relations in the dropdown - is it random, or some sort of ordering by distance? 

My thinking was that when the relation dropdown is being populated with relations, the code could check what kind of preset is being currently displayed and prioritise relations - i.e. if (preset=cycleway) then order any cycle routes at the top of the dropdown.

**Comment by boothym** [comment]
@quincylvania I'm wondering if you're able to help with the question above, with regards to how relations are sorted in the dropdown? Because I've never been able to work it out!

**Comment by quincylvania** [comment]
@boothym Looks like the relations are [meant to be sorted by creation date](https://github.com/openstreetmap/iD/blob/d8dbc708b28676a9046ad02613a9c2844e43310c/modules/ui/sections/raw_membership_editor.js#L169-L171). This makes some sense so relations you've just added in your session appear first, but I agree it could be smarter.

**Comment by boothym** [comment]
@quincylvania Thanks, I've had a look when editing just now and that does seems to be the case. But would it be possible to sort by last modified, or have the most recently used relation at the top of the list? Because that was the most annoying thing recently - the relation I was changing was at the bottom of the list and I had to scroll down every time!
