### ISSUE TITLE
Unknown roads should be highlighted as an issue

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5998]
I think highway=road should be highlighted as an issue, with text asking users if they can map it with a more suitable highway type.

**Comment by quincylvania** [comment]
@boothym Thanks for the suggestion! I added a warning, it looks like this:

<img width="548" alt="Screen Shot 2019-03-17 at 11 55 37 AM" src="https://user-images.githubusercontent.com/2046746/54493972-dd3ed200-48ab-11e9-9613-e83dec25604c.png">
