### ISSUE TITLE
christian church versus church building

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#6007]
There are times when I map a disused church, and use the "Church building" preset which gives building=church.  I'm happy with that, it's the way I'd expect it to work.  The "Chapel building" preset gives similar results with building=chapel.

There are other times when I map an active church - it's still a place of worship and it's in a building that is recognisable as a church (the sort of building that, if you saw it without knowing what it was, you'd think "church").  But this gives building=yes, which I have to manually change to building=church.

The same thing applies to chapel, except there's no preset (that is obvious to me) for a chapel that is an active place of worship, just a preset for a building that looks like a chapel but no longer is used as such.

Yes, there are Christian places of worship in buildings that are not recognizable as churches or chapels.  One chapel near me (which looks like a chapel) is thinking of relocating to a larger, industrial building in a business park.  One church near me was purpose-built  as a church but is not recognizable as such (it looks like somebody on drugs was given a Lego set of mismatched parts, and would probably be in the top-10 list of "Ugliest churches in Britain").  But **most** active churches I map are building=church, not building=yes and **most** active chapels I map are building=chapel, not building=yes.

Any chance of optimizing the presets for the common case?

**Comment by bhousel** [comment]
It's a bit complicated, here's why:
The `building=yes` tag gets added because of the [`building_area`](https://github.com/openstreetmap/iD/blob/master/data/presets/fields/building_area.json) field.  This is a pretty common field that is used on a lot of presets that should probably get a `building` tag, but only when they are mapped as areas.  It doesn't do anything if the feature is mapped as a standalone node.

So for us to add a `building=church` tag, we'd need to make a different kind of `building_area` field just for churches.  And then people would want different building fields for everything.

If we instead added `building=church` directly to the Church preset `addTags` section, it would add that tag even if the Church were mapped as a node, and this not really correct.  (People don't like to see `building` tags on nodes).

I'm not sure what the best solution is.  A while ago I suggested creating a special kind of field for building details that could handle all of this stuff (also #1829, https://github.com/openstreetmap/iD/issues/2550#issuecomment-78273632).

**Comment by eehpcm** [comment]
@bhousel 

>  I'm not sure what the best solution is

Me neither.

It's not a major problem, but if you ever come up with something I'd appreciate it.

**Comment by matkoniecz** [comment]
> Any chance of optimizing the presets for the common case?

Note that as result of this uncommon cases (place of worship in non-church building) will start to be tagged poorly.

Is it so big problem to change that `building=yes`? If that is the issue then maybe interface can be improved?

**Comment by bhousel** [comment]
I agree, it's not a very big problem for the user to change the `building` field to say what it looks like on the ground, if they know it.  Let's close for now.

**Comment by eehpcm** [comment]
@matkoniecz 

> Note that as result of this uncommon cases (place of worship in non-church building) will start to be tagged poorly.

I understood that when I opened the issue.

> Is it so big problem to change that building=yes?

It is no more effort to change building=yes to building=church for places of worship in church buildings than it is to change building=church to building=yes for places of worship in buildings that are not churches.  Same effort involved either way **but** one situation occurs more frequently than the other.

In my town there are 6 christian places of worship and 4 of the 6 are in buildings that are churches or chapels.  In the surrounding area of small villages I've mapped dozens of christian places of worship and they're **all* in buildings that are churches or chapels and *none* have been in non-traditional buildings.

That's why I asked if this could be optimized for the *common* case rather than the uncommon case.  Maybe it's the other way around in your part of the world, but I suspect not - even modern churches are usually designed to look like churches (apart from the abomination in my town).  We can't check with taginfo because many mappers will have accepted whatever iD happened to give them.  Which is another reason to optimize it for the common case because it means if a mapper just accepts whatever the preset gives them it's more likely to be right than the current behaviour of being wrong.

**Comment by matkoniecz** [comment]
> but one situation occurs more frequently than the other.

But in one situation it is more obvious that something should be changed than in the other

**Comment by eehpcm** [comment]
@matkoniecz 

> But in one situation it is more obvious that something should be changed than in the other

Really?

I suppose _if_ you have "All tags" expanded, which newbies may not do, because they expect the presets to do it all.  Otherwise you won't even notice the problem.

And _if_ you think to check _each and every one_ of those tags, just in case iD optimized one of them for the uncommon case instead of the common case, which newbies may not do because they expect iD to get it right.  Otherwise you won't even notice the problem.

Do you see what an enormous additional workload it imposes if one has to assume that iD doesn't do the expected thing, such as to have the Church preset use building=church?  Because if that's the case for churches, it could be the case for any tag set by any preset.

Are you seriously trying to tell me that you think it a _good_ idea for presets to insert values that are wrong 90% of the time instead of inserting values that are right 90% of the time?  And that the additional workload this policy would impose on mappers who strive for accuracy is a selling point for iD?  I hope not, otherwise I'm going to have to check every preset I use, every time.

When  the reason for not making the change was "It would involve a lot of messy code changes" I was prepared to live with it.  Now the reason appears to be "We like doing things that make life harder for mappers" I'm wondering what my options are given that I don't really want to swicth to josm.  Hopefully I misunderstood your point.

**Comment by bhousel** [comment]
@eehpcm, please be nice.

The reason I closed this is still "it would involve a lot of messy code changes".

It's just one tag that most people aren't interested in.
