### ISSUE TITLE
Issues inspector and long ways

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#6008]
I just added an isolated farm building with a service road.  The service road needed tweaks.  So I clicked on it (at the farm end) and was told it wasn't connected anywhere.  I worked my way along it, tweaking as necessary, continuing to be warned that it wasn't connected anywhere.  Eventually the tertiary road it was supposed to connect to came into view.  I fully expected to see that the service road didn't quite connect to the tertiary road but it already did, and then the issue inspector stopped complaining about it.

So it appears the issue inspector only looks at what is currently visible rather than checking the full extent of the service road.

**Comment by eehpcm** [comment]
I was just browsing through other recent issues and suspect this is related to #5938.

**Comment by bhousel** [comment]
Yes, this is #5938
