### ISSUE TITLE
Carriage return sends user to a search panel

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6009]
User types a carriage return where I have put the word RET in:
![0](https://user-images.githubusercontent.com/1230959/53707036-12890000-3e68-11e9-9071-5026d510bcc3.jpg)

The result is the whole panel becomes "search", with seemingly no way to recover one's work.

**Comment by bhousel** [comment]
Yes, iD has worked this way pretty much since the beginning.. see #451

You can tab between fields and all your edits are remembered automatically - you don't lose work.  Pressing enter/return/escape will dismiss the inspector and show the search pane.
