### ISSUE TITLE
consider level and layer tags during validation

### ISSUE THREAD

**Issue by prototype99** [openstreetmap/iD#6012]
currently overlapping ways are marked as errors, even if they are separate levels or layers. this is relatively easy to test, just make two over lapping ways and set one to layer=-1; validation still says it's wrong. This is relevant for example in multilevel buildings where corridors may overlap each other but be on different levels.

**Comment by quincylvania** [comment]
iD doesn't flag overlapping ways on different levels for `highway=corridor` and anything with a `level` tag. Are you seeing other behavior?

The rationale for not using `layer` alone is that it's still ambiguous what structures are present. We want mappers to say which feature should have `bridge`, `tunnel`, or `covered`.

**Comment by prototype99** [comment]
ahhh. okay this can be flagged with invalid, after looking at it again with a fresh mind it turns out it was just a complex issue with layers and levels
