### ISSUE TITLE
cuisine: wrong separator and odd underscore with multiple values

### ISSUE THREAD

**Issue by scaidermern** [openstreetmap/iD#6013]
iD seems to create odd cuisine tags if multiple values are present. It uses a comma instead of semicolon to separate multiple values and it starts subsequent values with a underscore.

Examples:

- [node 4172949589](https://www.openstreetmap.org/node/4172949589), cuisine=`pizza,_italian_pizza,_pasta,_calzone,_lasagna,_vegan_pizza,_coffee`, iD 2.1.0
- [node 307535899](https://www.openstreetmap.org/node/307535899), cuisine=`italian,_pizza,_pasta`, iD 2.0.0
- [node 1329447976](https://www.openstreetmap.org/node/1329447976), cuisine=`regional,_pizza,_pasta,_burger`, iD 1.9.2

They are all over the place.

Unsure how to reproduce this error and if it is still present. However I couldn't find a related changelog entry or similar issue. Maybe this is a result of a free-form entry and a special rule to replace spaces in the value field with underscores?

**Comment by scaidermern** [comment]
Oh, easy to reproduce. Try adding a cuisine value and instead of typing a single word type something like `foo, bar` which then gets replaced to `foo,_bar`.

I guess iD should prevent users from adding spaces and commas to a single cuisine value. Is it possible to implement such a syntax check?

**Comment by quincylvania** [comment]
@scaidermern Thanks for finding this! iD should automatically split to a new value when the user types a comma or semicolon in a `multiCombo` or `semiCombo` field.
