### ISSUE TITLE
Consider a four states preset for tactile_paving=partial

### ISSUE THREAD

**Issue by phiphou** [openstreetmap/iD#6014]
Currently, tactile_paving preset is a three states checkbox : unknown, yes and no. Please consider adding a fourth one, adding "partial" choice.

**Comment by quincylvania** [comment]
Hi @phiphou! Thanks for the suggestion, but it looks like `tactile_paving=partial` only has [91 uses](https://taginfo.openstreetmap.org/keys/?key=tactile_paving#values) and isn't documented on the [wiki page](https://wiki.openstreetmap.org/wiki/Key:tactile_paving). We try our best to support values based on consensus and actual usage, so I don't see us being able to support this at the moment.

**Comment by phiphou** [comment]
Ok, I thought it is more used than that. I understand you won't fix it.
