### ISSUE TITLE
Indicate type of selected feature even when the sidebar is hidden

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#6027]
Editing with hidden sidebar adds some risk editing a different feature than the user assumes to edit.

To mitigate this risk, iD should show the feature type of the selected element, even when the sidebar is hidden. I suggest to show the feature type in the part of the top bar where its extends over the space of the sidebar.
 
Maybe, the sidebar can be modified to show the feature type always in the same place. #3848 is related here.

**Comment by quincylvania** [comment]
I added the preset icon to the assistant so you can get a sense of what's selected even with the inspector closed.

![Screen Shot 2019-06-18 at 11 58 50 AM](https://user-images.githubusercontent.com/2046746/59700033-9620ef80-91c0-11e9-93ca-80fce163ca60.png)
![Screen Shot 2019-06-18 at 11 58 27 AM](https://user-images.githubusercontent.com/2046746/59700035-9620ef80-91c0-11e9-8450-0974fa1a2936.png)
