### ISSUE TITLE
Background layer broken: europe/pl/polskae-mapanetBuildings

### ISSUE THREAD

**Issue by gjedeer** [openstreetmap/iD#6031]
Chromium 72, Linux. 

To see the broken map, edit something in the [Poland region](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/polskae-mapanetBuildings.geojson) and choose "polska.e-mapa.net: Buildings". There's a lot of 404 errors for tiles in Developer Tools network tab.

Link to example map: https://www.openstreetmap.org/edit#map=18/53.40102/14.71030

Broken tiles URL examples:

```
http://wms02.epodgik.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=budynki&STYLES=&SRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=0,-7.081154550627917e-10,20037508.34,20037508.34
http://wms02.epodgik.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=budynki&STYLES=&SRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=1636363.9013012701,7055443.457852785,1637586.8937536608,7056666.450305177
```

The XML describing the map seems to be here: http://integracja.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow?SERVICE=WMS&REQUEST=GetCapabilities

I have zero knowledge about map technology, but this URL seems to return an image - I swapped domain name from wms02.epodgik.pl to integracja02.gugik.gov.pl in one of the 404 URLs:

```
http://integracja02.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=budynki&STYLES=&SRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=1632083.4277178945,7055443.457852785,1632389.1758309922,7055749.205965878
```

**Comment by bhousel** [comment]
Thanks @gjedeer  -  looks like the PR you opened in editor-layer-index should fix it 👍
