### ISSUE TITLE
Changing between presets that have side arrows keeps the old arrow style

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#6032]
Repro: make a `man_made=embankment` line (line 1 in screenshot), change to `barrier=guard_rail` (expected line 2) -- observe that the side arrow style remains from embankment (line 3).

![arrow style bug](https://user-images.githubusercontent.com/3857299/54085061-f42c7400-4341-11e9-9674-0f25a062918b.png)

2.14.3, Firefox x64 65.0.2

**Comment by quincylvania** [comment]
@RudyTheDev Thanks for reporting! Turned out to be a simple fix once I tracked it down 👍
