### ISSUE TITLE
Rounded search fields on mobile Safari

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6034]
Apparently mobile Safari forces round corners on `<input type="search">`. This looks weird.

![IMG_1524](https://user-images.githubusercontent.com/2046746/54086453-fda4e480-431f-11e9-8570-941562679cc9.png)

**Comment by 1ec5** [comment]
Ah yeah, this is intentional on the part of Safari but suboptimal in this case. One of the conventions from the earliest days of Mac OS X is that search fields always have a magnifying glass and a capsule shape (to fit snugly around the magnifying glass).
