### ISSUE TITLE
Add dragging threshold to favourited presets

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#6040]
It currently takes 1 pixel to start moving/rearranging the new top row favourites/recents. As you can imagine, it's very easy to accidentally drag it instead of clicking, especially on high-resolution monitors.

1698be7

**Comment by quincylvania** [comment]
@RudyTheDev I made the threshold 5 pixels. I'm pretty sure browsers interpret "px" as logical points, so high vs. low-resolution monitors shouldn't see wildly different behaviors. Screens can definitely have varied point lengths though.

I kinda like how snappy it is with no drag threshold but I can see how it could lead to accidental drags.

**Comment by bhousel** [comment]
> I'm pretty sure browsers interpret "px" as logical points, so high vs. low-resolution monitors shouldn't see wildly different behaviors.

Yes this is correct - px is logical pixels.. Hidpi displays actually have something like half pixel native resolution 👍 

I'm also really curious to see whether users will try to drag the icons onto the map, thinking it will put a point there.

**Comment by RudyTheDev** [comment]
@quincylvania Shouldn't it click the button if below the threshold? It's not accidental dragging itself that's the issue, it's that the button doesn't get clicked because one accidentally moved their pointer by 1 pixel. (It probably doesn't need to go all the way to typical "pointer up on control = click"; for example, like the Github's "comment" button.)

**Comment by quincylvania** [comment]
> I'm also really curious to see whether users will try to drag the icons onto the map, thinking it will put a point there.

@bhousel I was wondering this too. It does close the gap and show the minus cursor, so hopefully that's enough to tip them off that it removes. If not, they'll learn quickly!

> Shouldn't it click the button if below the threshold?

@RudyTheDev Good point! I updated it for that.
