### ISSUE TITLE
Recommend adding missing tags from the addTags property

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6043]
Sometimes iD adds tags when creating a preset that aren't needed to match a preset. For completeness, we should use the validation system to recommend adding these tags to features that weren't added with the latest version of iD. For example, iD would recommend adding `healthcare=hospital` to `amenity=hospital`.

While the deprecated tags validation could theoretically handle this, that solution would result in duplicate data and misleading message text.

**Comment by BjornRasmussen** [comment]
I like this idea, especially for solar panels, which often don't have all the necessary tags.

**Comment by yvecai** [comment]
Sometimes there is no default value, any way to implement an "addKey" ? Otherwise there is still a risk that whatever default present in the preset being applied blindly.

**Comment by yvecai** [comment]
Ah, a key with an empty value in the preset addTags section do the job. Well done !
