### ISSUE TITLE
Allow recently used presets to be dragged and dropped into the favorite presets bar

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6044]
![image](https://user-images.githubusercontent.com/37753777/54230891-c54b0500-44dd-11e9-80a7-4925fc4f3927.png)
Dragging the "parking aisle" icon into the favorites bar (which currently had node, line, and area) is impossible.  This motion is very intuitive, and would be a simple way to make a recently used preset a favorite.
![image](https://user-images.githubusercontent.com/37753777/54231103-3a1e3f00-44de-11e9-8af8-9329c7ca5943.png)

**Comment by bhousel** [comment]
Closing here, I think they just appear in the "Recent" area of the ribbon now..

**Comment by quincylvania** [comment]
This is actually something I do want to get to eventually…

**Comment by bhousel** [comment]
oh ok.. Sorry, I'm just going through and closing a lot of things because I'm pretty overwhelmed by the issue list right now.

**Comment by quincylvania** [comment]
After using the ribbon for a few months, I'm still not sure I love splitting the quick presets into separate groups.

<img width="524" alt="Screen Shot 2019-08-02 at 3 49 07 PM" src="https://user-images.githubusercontent.com/2046746/62395164-790c6a00-b53d-11e9-8c42-ef54f58369b4.png">

I mocked up an alternative that I'd like to get feedback on. It keeps all quick presets in a continuous strip. There's now room to use the preset names as labels, abbreviated as needed. This helps differentiate presets with the same icon, especially on mobile where the tooltips are inaccessible.

<img width="530" alt="Screen Shot 2019-08-02 at 1 55 57 PM" src="https://user-images.githubusercontent.com/2046746/62389339-93d6e280-b52d-11e9-911e-a058ef7e186b.png">

When you click the label area, it can toggle to the number shortcuts for advanced users.

<img width="532" alt="Screen Shot 2019-08-02 at 1 56 08 PM" src="https://user-images.githubusercontent.com/2046746/62389338-93d6e280-b52d-11e9-9efa-d5d93683bb96.png">

The favorites could be specified via badges, as inspired by the [Mario Maker 2 UI](https://www.youtube.com/watch?v=bKjrbw7y3_k&feature=youtu.be&t=227). This would also let the mapper mix the order of recents and favorites. For example, you may want to always keep <kbd>1</kbd> as your most recent, followed by your favorites.

<img width="533" alt="Screen Shot 2019-08-02 at 3 47 33 PM" src="https://user-images.githubusercontent.com/2046746/62395162-7578e300-b53d-11e9-97f0-7a22096ba465.png">

**Comment by BjornRasmussen** [comment]
I personally don't like either ribbon.  Here's why:
When editing, the recent quickly gets very long.  The ribbon is then filled with 10 separate presets.  This is quite cluttered, however, and since the recent presets keep moving around, it's hard to memorize the different shortcuts.  Looking for the preset is also hard, because the ribbon is so cluttered.  
Because of this, I don't use the recent ribbon.  Instead, I often clear it out by dragging and dropping to make the ribbon less cluttered, and then adjust the favorites bar to whatever I'm mapping.

Also, the main issue with showing recent presets so prominently is that mappers often change what they're mapping, so the presets in the ribbon aren't relavent anymore.

So how do I think the ribbon should look?  I think that the recent presets should appear in the search list along with some "recommended" presets.  Then, the ribbon should only include favorites, and should be completely in the control of the mapper.

**Comment by slhh** [comment]
@quincylvania 
I would keep the Favorites and Recent sections separate, and make the separation dragable to adjust the number of shown recents. The labeling of the sections isn't essential, users will get used to it anyway. You might drop it in favor of preset names or shortcuts. Maybe section lables can be shown while dragging the separation.
Missing tooltips on mobile are a problem, but I'm not sure whether such short preset names labels do really work well, and this is likely language dependent.

If recents were dragable into favorites as requested in this issue, displaying a single recent would likely be a useful setting.

Assigning shortcuts to recents seems to be of very limited use. Maybe, shortcut 0 can be assigned to the most recent one, and no shortcut to the other recent ones. This is easy to memorize, and might give users a safer feeling when using shortcuts.

**Comment by BjornRasmussen** [comment]
Adding to my last comment, I still find the "recent" presets very useful when I first start editing and there aren't any presets still around from previous sessions, because I quite often add the same thing several times in a row.  The real issue is that I never use the recent shortcuts from previous editing sessions - they just sit there cluttering up the UI.

**Comment by quincylvania** [comment]
I think let's keep Favorites and Recents separate for now. This division seem pretty straightforward to understand. We could still cycle to the number shortcuts (and possibly the short preset names) when you click on the button labels.

@BjornRasmussen I agree that shortcuts are useful for getting started but can outlive their usefulness. Originally I had the recents maxing out at 5 instead of 10, maybe this would be better? Also, once we do #6717 then you can hide the recents at any time.

**Comment by BjornRasmussen** [comment]
Maximg out the recents at 5 good!  Does not tracking recent searches between changesets also seem reasonable?  I know that there was an issue about doing the opposite of this a while back, but that was before the ribbon UI.

**Comment by quincylvania** [comment]
@BjornRasmussen I think persisting the recents between changesets/sessions is more useful than not. Some mappers might focus on the same few things but not bother to favorite them. Though we could clear them out after a few days of not editing (like we do with unsaved changeset comments). We also might have a "Clear All" option for recents if we do #6024.

**Comment by jidanni** [comment]
I see no favorites bar.
Perhaps it is an unreleased feature.

**Comment by leifr-unc** [comment]
Yes, see https://preview.ideditor.com/master
