### ISSUE TITLE
Allow explicit preset upgrade paths

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6045]
We often maintain unsearchable presets for deprecated tags to give iD some data about the features and show users relevant icons and fields when they selecting an old feature. iD should recommend tag upgrades for all of these presets. The `deprecated.js` data can handle most of these situations, but not all. It would be cleaner to just let a preset specify a replacement preset.

**Comment by bhousel** [comment]
I agree - this would be great for any of the unsearchable legacy presets 👍
