### ISSUE TITLE
Relation members should be added with a default role

### ISSUE THREAD

**Issue by DujaOSM** [openstreetmap/iD#6048]
This is vaguely related to #5898 (validation kicking in too soon).

When adding a relation to an element (say, a line to a multipolygon), validation kicks in immediately, scrolls the sidebar, and forces me to choose the role (outer or inner). It helpfully suggests options, so I just have to select "set as inner" or "set as outer". However, it still requires an additional click per every member... slightly annoying.

Work would be much more efficient if iD selected a default role immediately after choosing the relation. Now, what the default role should be is open to discussion...

One approach is to define a default role depending on relation type. For multipolygons, typically some 90% ways are "outer" and 10% "inner". For waterways, typically "main_stream". For road routes, it should be blank. For administrative boundaries, ways are invariably "outer" and nodes "admin_centre", etc.

Another, simpler approach could be to just cache user's last selected role in the session and reuse it as default. For multipolygons, one would typically define outer ways first, then go to inner, so the user would need to explicitly select the role only once per relation.

**Comment by quincylvania** [comment]
Hi @DujaOSM! This is #4695. While iD could infer a default role, I don't think it should until we can be confident that it'll be correct 99% of the time. Many users would just accept a default and move on, creating errors. In the future we may build an easier workflow for creating relations.
