### ISSUE TITLE
Disable browser-zooming the interface on mobile

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6049]
While double-tapping or pinching the map correctly scales the map, doing so on other UI elements can zoom the entire UI. This is jarring, particularly on touch devices. If users need larger text for accessibility, we should add an option that increases text sizes instead of the entire UI.

![IMG_0010](https://user-images.githubusercontent.com/2046746/54438617-610e8800-470d-11e9-9c78-9aea36e6dbba.png)

**Comment by bhousel** [comment]
Yes this was the intent behind #5492 - but I didn't get it working for all the UI elements.
We should probably find a way to disable it everywhere and enable the gestures on the map only.

For normal apps, I get that the pinch zooming is nice for accessibility, but I feel like maps are special.

**Comment by quincylvania** [comment]
So I was able to disable this on mobile Safari by calling `preventDefault` on the `click` event at the container level.

This doesn't have any apparent side effects on the iOS and macOS browsers I've tested, but I don't have access to other platforms to see if it works or has problems. Feedback is welcome!

This also doesn't disable double-tap-to-zoom on desktop with a Macbook trackpad, but in my mapping this interaction has been hard to do by accident and easy to escape.

**Comment by quincylvania** [comment]
Thinking more about accessibility implications, I just tried out iD with iOS's built-in [Zoom tool](https://www.imore.com/how-use-zoom-accessibility-iphone-and-ipad). It gives you a smart on-screen magnifier that works for pretty much any app or webpage. I think it works better for a mapping app like iD than raw browser-zooming does, though I'm not vision-impaired so don't take my word for it.

We should continue to think of ways to improve iD's usability for everyone in this space.
