### ISSUE TITLE
When adding a feature allow to clone the preset of an existing feature

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#6050]
When adding a feature a feature of the same type does already exist nearby in most cases. Why should the user need to search the feature type? ID should allow to clone the preset of the existing element directly.

All users could benefit, but especially users of mobile devices.

Ideas to do this:

- Add the preset which is matching to the currently selected feature to the favorites ribbon temporarily (e.g. als long as the feature is selected, or until a different feature gets selected).
- Add a control to clone combined with the feature type indication of #6027 
 
A workflow to clone does already exist, but it is somewhat ugly:

- select the existing element which has the wanted feature type
- open the sidebar if not already open
- favorite the preset
- use the favorite to add the new feature
- remove the favorite

**Comment by bhousel** [comment]
> A workflow to clone does already exist, but it is somewhat ugly:
> 
> * select the existing element which has the wanted feature type
> * open the sidebar if not already open
> * favorite the preset
> * use the favorite to add the new feature
> * remove the favorite

Closing here because I'm pretty ok with the workflow of allowing users to temporarily favorite things - it doesn't seem "ugly" to me.
