### ISSUE TITLE
Allow to favorite preset groups

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#6051]
The favorite ribbon should also support favorites of groups of presets instead of favoritites of individual presets. For example "landuse features" would be a useful favorite.

When clicking such a group favorite, iD should not directly enter draw mode, but focus the feature type search field for refining optionally, and show the feature type selection dropdown, which is filterered according to the used group favorite.

Possible group favorites should include "all area features", "all line features", "all point features", which enables the "feature type selection before drawing" workflow to be as efficient as the old workflow.

The feature type selection dropdown does already have controls on lines of individual presets. To allow favoriting groups, such controls need also to be available on the other lines.

**Comment by bhousel** [comment]
Sorry, I'm going to close this issue.  We don't have a way to make groups of presets aside from the existing "categories" function.  From #6061 it's clear that categories are confusing, and I think we need to make them _less_ like presets..
