### ISSUE TITLE
Do not use a search box as the main control to add features

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#6052]
When the feature type search box isn't focused, it does not contain any useful information, but potentially confusing information. The unfocussed search box should be replaced with a "Add feature" button for the following reasons:

- The button seems to be more intuitive to add a feature.
- The button could be smaller than the seach box to save valuable space in the topbar.
- The seach box might be confusing due to containing the feature type of a recent search while the user is drawing a different feature by using a favorite, or while is diferent feature is selected.
- In browse mode with open sidebar two search boxes are shown, which might also confuse new users.

When pressing the add feature button, the button should open the focused seach box in place of the button.

**Comment by bhousel** [comment]
Sorry, but we are committed to the new search bar UI.  We'll rewrite the walkthrough, so it wont' be confusing..
