### ISSUE TITLE
Do not use directly discardNames name-suggestion-index 

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6055]
See https://github.com/openstreetmap/iD/issues/5930

`discardNames` from name suggestion index is directly used by iD.

So listing names there will cause iD to list them as invalid and encourage people to delete them. 

To avoid this one may add names to `discardKeys` that are not brands but can be used but it makes contributing to name-suggestion-index more complicated. See https://github.com/osmlab/name-suggestion-index/pull/2488#issuecomment-473830149

I think that it would be preferable to have iD maintain its own list, based on name-suggestion-index.

Just list filters in `discardNames` that are discarding invalid names (and use them in validator), list of filters that are harmful in iD and have ability to list filters not appearing in either first or second list.

---

In case of creation of separate set of entries it may be worth syncing with JOSM - see https://josm.openstreetmap.de/browser/josm/trunk/data/validator/unnecessary.mapcss#L93

**Comment by bhousel** [comment]
Worth mentioning too that name-suggestion-index only looks at a subset of OSM, so it wouldn't contain generic words like "park" or "school" which are worth warning the user about.  So maybe 2 lists does make sense.

**Comment by matkoniecz** [comment]
Also `amenity=place_of_worship religion=muslim name=mosque`,  `amenity=place_of_worship religion=muslim name=cami` ("mosque" in Turkish and used 1500+ in Turkey as a descriptive name), `amenity=place_of_worship religion=christian name=church`, `amenity=place_of_worship religion=christian name=Biserica` (meaning "church" in Romanian), `amenity=toilets name=Toilet`.

( from proposed JOSM patch https://josm.openstreetmap.de/ticket/17629#comment:7 )

**Comment by matkoniecz** [comment]
One of mappers reported that Kebabai is a valid name in some contexts, despite being (correctly) placed in discardNames.

**Comment by bhousel** [comment]
> One of mappers reported that Kebabai is a valid name in some contexts, despite being (correctly) placed in discardNames.

For stuff like this we usually just move it out of `discardNames` into one of the other discard lists.

**Comment by empersOSM** [comment]
Hey, the mapper that said that Kebabai may be a valid name is me, empers. In Lithuania, a lot of Kebab-style places are just named Kebabai, or something else generic. So thank you for doing something about it and thank you to Mateusz for raising the issue.

**Comment by matkoniecz** [comment]
@bhousel Thanks for a fix! I was unaware (or forgot) about this workaround.

@empersOSM Note that effect will not be visible immediately. NSI likely needs to make a release and so on.

Nice that it turned out to be fixable despite my earlier claims :)

And in cases of similar validator false positives - in general it makes sense to report them.
