### ISSUE TITLE
tab after value in "A ll tags" no longer works

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#6060]
Occasionally I have to add several tags in "All tags" (most frequently heritage=*, heritage:operator=* and ref:*=n).  My old way of doing it was to click on the plus, type "her" into the tag name, then tab to autocomplete and take me to the value (this still works).  Then type the value and press tab which opens up a new tag field for me to add the next tag (this no longer works).

What happens now is that pressing tab after entering the value takes me, without me realizing, to keyboard shortcuts, so I start to type the name of another tag and these keystrokes are interpreted as shortcuts.  With, as they used to say in teasers for unfunny comedy shows, hilarious results.  Oh how I laugh when, thinking I'm typing the tag name ref:cadw, what actually happens is I rotate the building I just added.  And sometimes worse.

**Comment by tordans** [comment]
This is the same as https://github.com/openstreetmap/iD/issues/6046, right?

**Comment by eehpcm** [comment]
@tordans 

> This is the same as #6046, right?

Yep.  Sorry, I missed that one.  I only come here when I have a problem rather than looking at every issue as it arises and the automatic "similar issues" suggestions didn't show #6046.
