### ISSUE TITLE
Issue with bus stops wanting users to "upgrade tags"

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6063]
For some reason, upgrading tags for bus stops changes tags but doesn't remove the warning.  
To reproduce, 
1) Click this link: http://preview.ideditor.com/master/#background=EsriWorldImagery&disable_features=boundaries&id=n5425683027&map=20.88/35.77980/-78.64544
2) Click "Upgrade tags".

**Comment by quincylvania** [comment]
@BjornRasmussen Thanks for logging this! This was a bug due to #6045.
