### ISSUE TITLE
validator - offer to remove pointless building:ruian:type tags

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6064]
See ​https://wiki.openstreetmap.org/wiki/Key:building:ruian:type?uselang=en documenting widespread duplication of many `building:ruian:type` tags.

For example many `building:ruian:type=18` are on `building=garage` and provide no additional information over a standard OSM tag.

Following is a just implemented rule in JOSM removing some blatant duplicates

```
*[building:ruian:type=2][building=farm_auxiliary],
*[building:ruian:type=7][building=house],
*[building:ruian:type=11][building=hotel],
*[building:ruian:type=12][building=warehouse],
*[building:ruian:type=13][building=barn],
*[building:ruian:type=18][building=garage],
*[building:ruian:type=21][building=greenhouse] {
  throwWarning: tr("{0} is unnecessary for {1}", "{0.tag}", "{1.tag}");
  group: tr("unnecessary tag");
  fixRemove: "{0.key}";
}
```

In addition following also look like a dulicates

```
1 ( průmyslový objekt industrial object building=industrial)
10 (stavba pro obchod commercial building building=commercial)
17 ( stavba pro dopravu building for transportation building=transportation)
26 ( jez weir waterway=weir)
```

See https://josm.openstreetmap.de/ticket/17482 for equivalent JOSM issue.

Note that some `building:ruian:type` may be on `building=yes` or be typically tagged on objects where are not 100% duplicating present tags, so just removing all `building:ruian:type` may be not a good idea.

**Comment by quincylvania** [comment]
We could do technically do this pretty easily, but I don't see much benefit. It's not like features have a `building:ruian:type` without a proper OSM tag, do they? I'd prefer not to bug users about simply removing harmless extra tags.

**Comment by matkoniecz** [comment]
Maybe it is not fitting as well in iD where tag removal requires more work from user than in JOSM (and tags are more hidden so cryptic tags from imports are less irritating).

**Comment by quincylvania** [comment]
I've thought about this more. Since the presence of these tags affects essentially nothing except the raw tag editing experience of a few users, I wouldn't want to bother iD mappers over it. Perhaps an approved mass-edit would be a better solution.

**Comment by pnorman** [comment]
I recommend building a consensus with the community that `building:ruian:type` can be discarded then adding it to https://github.com/openstreetmap/iD/blob/master/data/discarded.json
