### ISSUE TITLE
Cycleway crossing gets upgraded incorrectly

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#6065]
![before](https://user-images.githubusercontent.com/3857299/54609823-5715bd80-4a5c-11e9-922b-daf866dfed7b.png)

becomes

![after](https://user-images.githubusercontent.com/3857299/54609822-5715bd80-4a5c-11e9-8015-c80cf0ca522e.png)

I assume it should become `cycleway=crossing`.

I wonder what the validation rule and fix are? I can put `highway=whatever` and it still adds `footway=crossing`. It seems the upgrade does not consider the `highway` value.

**Comment by quincylvania** [comment]
@RudyTheDev Hmm I couldn't reproduce this on `master`. What is the geometry and other tags? Can you point to a live example I can test?

If a line has `crossing=marked` and no other preset, iD will try to add `highway=footway` and `footway=crossing`. It won't override an existing `highway` value though.

**Comment by RudyTheDev** [comment]
@quincylvania Oh, I see what's happening.

* Make a new line
* Add `crossing=marked` (it becomes Marked Crosswalk)
* Add `highway=cycleway`
* Click upgrade

Observe the above issue.

It won't reproduce if you
* Make a new line
* Add `highway=cycleway` (it becomes Cycle Path)
* Add `crossing=marked`

This isn't counted as a crossing, so no upgrade prompt is shown.

I think the presets are conflicting here due to tag order? I think that's a separate issue with what is considered a "crossing". I guess it only looks for `crossing` tag?

**Comment by quincylvania** [comment]
Oh weird. I feel like the tag order shouldn't matter when matching presets. @bhousel Thoughts on this?

**Comment by bhousel** [comment]
> Make a new line
> Add crossing=marked (it becomes Marked Crosswalk)

At this point, I don't know what preset it is matching.  This is weird.  `crossing=marked` by itself should only match a vertex geometry, not a line.  I also get the "upgrade tags" prompt, and I'm not sure why.

The current "Marked Crossing" as a line should match 
```
    "tags": {
        "highway": "footway",
        "footway": "crossing",
        "crossing": "marked"
    },
```

I don't think iD supports `cycleway=crossing` because I'm not sure that it's an actual tag.  Users can't just put `"anything=crossing"` and have it work.

> Oh weird. I feel like the tag order shouldn't matter when matching presets. @bhousel Thoughts on this?

Order doesn't matter, the matching algorithm runs through all the tags on the feature and adjusts weight as they start to match things..

**Comment by quincylvania** [comment]
> At this point, I don't know what preset it is matching. This is weird. crossing=marked by itself should only match a vertex geometry, not a line. I also get the "upgrade tags" prompt, and I'm not sure why.

It's because I changed the `highway/footway/marked` preset tags to this:

>     "tags": {
>         "crossing": "marked"
>     },
>     "addTags": {
>         "highway": "footway",
>         "footway": "crossing",
>         "crossing": "marked"
>     },

My rationale is that we can help users upgrade more features by reducing `tags` to the minimum  since iD now recommends adding missing `addTags`. This means that users can quickly add the missing tags on lines that only have `crossing=marked` for some reason. Otherwise, such a feature would just match the fallback preset and users would have to correct it manually. I think this behavior's useful but we can change it if you disagree.

**Comment by RudyTheDev** [comment]
> I don't think iD supports `cycleway=crossing` because I'm not sure that it's an actual tag. Users can't just put `"anything=crossing"` and have it work.

That's why I was confused how it matches the upgrade. According to Wiki [[1]](https://wiki.openstreetmap.org/wiki/Key:crossing), `footway=crossing` and `cycleway=crossing` are the two types of crossings that refine `highway=footway` and `highway=cycleway` ways respectively.

This is the typical (micro-mapped) designated cycle crossing as a way:

![cycle cross](https://user-images.githubusercontent.com/3857299/54623303-ed091280-4a73-11e9-9b9f-cd0eea1c9cb7.png)

They are on a designated cycleway with separate markings and separate traffic lights, and additional traffic laws.

There are 8600 usages of `highway=cycleway` + `cycleway=crossing` and 9100 of `highway=cycleway` + `footway=crossing` (which makes no sense to me since `footway` isn't refining anything and isn't a tag by itself).

For mapping purposes, I'd love to see this as a preset, with validation and upgrade, and a visual distinction similar to footpath crossings.

**Comment by RudyTheDev** [comment]
> My rationale is that we can help users upgrade more features by reducing `tags` to the minimum since iD now recommends adding missing `addTags`.

What does it do if some (but not all) `addTags` already exist on the feature but with different values?

**Comment by bhousel** [comment]
@quincylvania said:
> It's because I changed the `highway/footway/marked` preset tags to this:
> ...
> My rationale is that we can help users upgrade more features by reducing `tags` to the minimum since iD now recommends adding missing `addTags`. I think this behavior's useful but we can change it if you disagree.

Ok!  I was just confused because I haven't pulled the code in a few days 👍  That seems ok to me..


@RudyTheDev said:
> There are 8600 usages of highway=cycleway + cycleway=crossing and 9100 of highway=cycleway + footway=crossing (which makes no sense to me since footway isn't refining anything and isn't a tag by itself).
>For mapping purposes, I'd love to see this as a preset, with validation and upgrade, and a visual distinction similar to footpath crossings.

Sounds ok, I agree with adding a "Marked Cycle Crossing" preset or something similar.

**Comment by quincylvania** [comment]
I added "Unmarked Cycle Crossing" and "Marked Cycle Crossing" presets and added an upgrade path for `highway=cycleway` + `footway=crossing`. I'll work on the rendering next.

Should we now rename the footway crossing presets to "Marked Foot Crossing", etc.?

**Comment by RudyTheDev** [comment]
This does mean the new presets no longer offer to add `footpath=crossing` or `cycleway=crossing` when those are missing, since it no longer matches `highway=footpath/cycleway` + `crossing=marked` as a crossing preset but just a regular foot path or cycle way preset.

**Comment by quincylvania** [comment]
> This does mean the new presets no longer offer to add footpath=crossing or cycleway=crossing when those are missing, since it no longer matches highway=footpath/cycleway + crossing=marked as a crossing preset but just a regular foot path or cycle way preset.

I think so, yes. It will offer to add `highway=cycleway` or `highway=footway` if those are missing but the other tags are there.

**Comment by bhousel** [comment]
> Should we now rename the footway crossing presets to "Marked Foot Crossing", etc.?

"Marked Pedestrian Crossing" or "Marked Crosswalk" is better for normal people.  (we should make sure people can search for either and get that thing as the top result)

**Comment by RudyTheDev** [comment]
@quincylvania I guess the issue is that the preset can only "detect" one combination in `tags` even when several incomplete combinations from `addTags` imply the same preset.

* `highway=footway` + `crossing=` implies `footway=crossing`
* `footway=crossing` (+ `crossing=`) implies `highway=footway`

So the two incomplete cases are mutually exclusive.

How difficult would it be to add an optional alternate list of tags to the preset definition? That way both incomplete version are matched/detected and upgraded to the full tag list.

**Comment by quincylvania** [comment]
@RudyTheDev Interesting question. It'd be non-trivial to let presets match multiple sets of tags. `deprecated.js` could actually handle wither case and could be added as a complement.
