### ISSUE TITLE
Add preset for amenity=social_centre

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#6077]
The suggestion presets are giving this warning now, so we should add a preset for these.
[amenity=social_centre](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dsocial_centre)

Warning:  No preset "amenity/social_centre" for name-suggestion "American Legion"

**Comment by quincylvania** [comment]
I personally wouldn't know when to use this vs. `amenity=community_centre` vs. `club=*`. That's not to say we shouldn't support it necessarily…

**Comment by bhousel** [comment]
> I personally wouldn't know when to use this vs. amenity=community_centre vs. club=*. That's not to say we shouldn't support it necessarily…

Yeah I don't really know either 🤷‍♂️ 
Social center sounds more like you need to be a member and community center sounds more open?

**Comment by quincylvania** [comment]
I guess let's just see how people use them and eventually we might be able to define them better!
