### ISSUE TITLE
Curb preset icons

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6081]
The curb presets should each have unique icons that convey the shape of the curb. This will help users decide which one to use and let them differentiate curb features on the map at a glance

<img width="380" alt="Screen Shot 2019-03-21 at 4 13 47 PM" src="https://user-images.githubusercontent.com/2046746/54782095-76dfe980-4bf4-11e9-9a1b-5136fc4630e8.png">

**Comment by BjornRasmussen** [comment]
This has already been resolved, I think.
