### ISSUE TITLE
Treat closed ways tagged with indoor=* as areas, not lines.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6082]
Currently, when editing the indoor area of well mapped buildings, iD treats rooms as lines, making selecting a room difficult - I try to click on the outline of a room and end up clicking on the room next to it instead.  Would it be possible to treat objects mapped with `indoor=room`, `indoor=area`, or `indoor=corridor` as areas?  `indoor=wall` should not be treated as an area as far as I know, so closed areas with `indoor=wall` should still be treated as lines.
![image](https://user-images.githubusercontent.com/37753777/54796485-c7703a80-4c26-11e9-9560-2f4840b81021.png)

**Comment by matkoniecz** [comment]
In addition to `indoor=wall` - is `indoor=corridor` supposed to be an area or line?

**Comment by BjornRasmussen** [comment]
`indoor=corridor` is for areas, `highway=corridor` is for lines.
