### ISSUE TITLE
different language setting => different shortcut keys / preview-id-editor in German?

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6083]
I think the reason for different shortcut keys for different user account language setting is because the used intuitive starting letter of the actions which will perform.

examples
English - Square: shortcut **"Q"**
German - Square: (Rechtwicklig machen) shortcut **"S"**

English: Fill Areas No fill (Wireframe) shortcut **"W"**
German: "keine Füllung" (Gittermodus) shortcut **"G"**

I'm always little bit confused about the different keys, when I switch from work using the released id-editor version on German to the preview-id-editor on English.

So, where can I change the language setting for the preview-id-editor to German, if this is currently not possible, would it be lot of work to implement it?

Thank you

bold edit ...

**Comment by manfredbrandl** [comment]
@sun-geo is your browser configured for german as the main languge? My Chrome is and i see the german interface:
![image](https://user-images.githubusercontent.com/5360273/54809724-67a87c80-4c84-11e9-826a-0305cb61cfad.png)

![image](https://user-images.githubusercontent.com/5360273/54809666-3e87ec00-4c84-11e9-8604-425180882d0a.png)

**Comment by sun-geo** [comment]
Thanks for this hint. Didn't know this is browser language related.

For Chrome it's working.
Mostly i'm using brave: 64bit on win7 maschine (https://laptop-updates.brave.com/latest/winx64)
Now I changed brave language to German, but it seems still running on English.
Now I did removed English completely for brave and it works well :-)

=> ticket closed

**Comment by sun-geo** [comment]
Upps, did not check the keys.
=> reopened
See screenshot. @manfredbrandl do you have the same behavior?

id-editor-v2.13.4
![v2 13 4](https://user-images.githubusercontent.com/47290585/54816025-8cf0b700-4c93-11e9-90b8-43eb70d2646f.png)

id-editor-preview
![preview](https://user-images.githubusercontent.com/47290585/54816081-a691fe80-4c93-11e9-95cc-5aa985111f64.png)

**Comment by manfredbrandl** [comment]
@sun-geo the keyboard-shortcuts are somewhat translated, but S for Straighten and Q for sQuare stay unchanged:
![image](https://user-images.githubusercontent.com/5360273/54830108-2336d400-4cb8-11e9-8735-f8608cb54aed.png)
If you have a better scheme, you can change that in transifex https://www.transifex.com/openstreetmap/id-editor/translate/#de/core/

![image](https://user-images.githubusercontent.com/5360273/54830257-76108b80-4cb8-11e9-9e07-e6ee629161ec.png)

**Comment by bhousel** [comment]
Yes @sun-geo this is expected for the squaring shortcut to be different in preview
It changed from <kbd>S</kbd> to <kbd>Q</kbd> in #5999

**Comment by sun-geo** [comment]
OK - thank's for info'
