### ISSUE TITLE
Filter out deprecated values from combobox suggestions

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6084]
There are times when a deprecated tag value (such as `crossing=zebra`) is still common enough to appear as a combobox suggestion in iD. It's a jarring user experience to select a suggestion and immediately see a warning about it. We should just filter out deprecated values from the list.

**Comment by bhousel** [comment]
I agree with this!  Filtering out deprecated data has come up before on #5016 and #4508 and maybe going further back than that.

In the past I've taken the opinion that it's up to the OSM community to fix their data, but I've changed my mind.  iD has a validator now and we should be more opinionated about the tags that we encourage our users to map with.
