### ISSUE TITLE
Differentiate category and preset icons 

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6085]
It's difficult to tell at a glance which of these are categories and which are not. We should better differentiate the icons.

<img width="438" alt="Screen Shot 2019-03-22 at 9 45 58 AM" src="https://user-images.githubusercontent.com/2046746/54827022-6f1d5500-4c87-11e9-8963-8a06ed49382e.png">

**Comment by SilentSpike** [comment]
Perhaps a simple folder shaped outline around the icon for categories?

**Comment by quincylvania** [comment]
These look pretty good. Thanks for the idea, @SilentSpike 👍

<img width="452" alt="Screen Shot 2019-07-10 at 2 08 22 PM" src="https://user-images.githubusercontent.com/2046746/60993394-60cd7480-a31c-11e9-9768-cea92e997f93.png">

**Comment by quincylvania** [comment]
Implemented this for v2 since there's no reason to wait for v3, whatever that ends up looking like.

<img width="395" alt="Screen Shot 2020-12-03 at 1 13 47 PM" src="https://user-images.githubusercontent.com/2046746/101070488-6d81e680-3569-11eb-8609-e28931ef7617.png">
<img width="398" alt="Screen Shot 2020-12-03 at 1 13 31 PM" src="https://user-images.githubusercontent.com/2046746/101070489-6e1a7d00-3569-11eb-89d9-8cb2dc21d083.png">
