### ISSUE TITLE
Remove the tags entrance=yes and indoor=door from the door preset.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6089]
As far as I know, indoor doors are only supposed to be tagged with `door=*` and `level=*`, but the new preset for "Indoor door" includes the tags `entrance=yes` and `indoor=door`.  
* `indoor=door` is only used [2,624 times](https://taginfo.openstreetmap.org/tags/indoor=door "link to the taginfo page"), and has never been documented before.  Also, [OpenLevelUp](https://openlevelup.net) can easily render doors without this tag.  The tag `door=*` has been used [56,434 times](https://taginfo.openstreetmap.org/keys/door "link to the taginfo page") for comparison.
* `entrance=yes` should not be used on doors, since it is supposed to signify the entrance of a building.  It has also not been documented for indoor doors before.  
  
Thanks @quincylvania for the nice new indoor presets!  I hope that they will be the best possible before the next release.

**Comment by quincylvania** [comment]
@BjornRasmussen Thanks for catching this! For some reason I missed the existence of the `door` tag entirely. I took `entrance=yes` + `indoor=door` from [this diagram](https://wiki.openstreetmap.org/wiki/File:Stairs_and_landing_diagram_1.jpg) on [the Simple Indoor Tagging page](https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging) (yes, I now see the `door` key is also used there 😅). I hope someone can update the diagram with current best practices.

I'll remove the `entrance=yes` tag from the preset and add the `door` tag. However, I think it's important to also have `indoor=door` or `indoor=yes`. `door` appears to also be used as a subkey for `entrance` so we want to positively differentiate strictly indoor doors. Further, making sure every single indoor feature has an `indoor` tag helps data consumers and allows for useful validation like checking that all `indoor` features have a `level` tag.

**Comment by quincylvania** [comment]
So I had to make `indoor=door` define the preset instead of `door=*` since `door` is used so commonly as an `entrance` subkey. It's actually [documented that way on the wiki](https://wiki.openstreetmap.org/wiki/Key:door) but I agree we should only use `entrance` for building entrances. The `door` key is still added when the user selects the Indoor Door preset so data consumers can ignore `indoor=door` if they really want to.
