### ISSUE TITLE
Signal stop and direction

### ISSUE THREAD

**Issue by jeawrong** [openstreetmap/iD#6090]
Hi, when I add a direction to a signal stop it's show inverse range of view on the street.
Example: this way have direction West-Est, the signal is at the end of the stret, near to junction with another street, I have set the direction stop=forward, but the display of this direction is in opposite direction.

![Cattura2](https://user-images.githubusercontent.com/1963729/54864518-a90a5c00-4d58-11e9-8918-a4a599e4c048.PNG)

![Cattura](https://user-images.githubusercontent.com/1963729/54864494-80826200-4d58-11e9-88c8-1eb0fd8981dd.PNG)

**Comment by bhousel** [comment]
Ah yeah, sometimes people get confused about this.. (someone said the same thing on #4602)

The cone renders in the direction that the sign points, not the direction that the road points.

**Comment by jeawrong** [comment]
Ok, but in the direction of the sign the sign same is not visibile... is the rear of this, and look sam this... and create confusion... the signal is on the point, not affect the rear of the street. Very strange rendering!
![Opera Snapshot_2019-03-23_230430_www mapillary com](https://user-images.githubusercontent.com/1963729/54872154-1c938400-4dc0-11e9-9db7-e9c4b765044d.png)
