### ISSUE TITLE
Support subject:wikidata and subject:wikipedia for historic=memorial and tourism=artwork

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6093]
It is really popular to misuses `wikipedia` and `wikidata` tag for linking to depicted events.

See https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_Wikipedia_links

For example https://www.openstreetmap.org/node/4835533107 is not a synagogue burnt down by Germans (it is not existing anymore) but a memorial.

Unfortunately correct tagging using `subject:wikipedia` and `subject:wikidata` is currently not supported by iD.

**Comment by quincylvania** [comment]
I'd theoretically be fine with generalizing the Wikidata/Wikipedia fields for use with keys like `subject:wikidata` and `brand:wikidata`. My main hesitation is confusing new users with fields with names like "Subject Wikidata", but perhaps that's not a big deal if we put these in "moreFields".

**Comment by bhousel** [comment]
I agree with @quincylvania .. My thought on this is not that it's hard to add them, but more that it's hard to explain to users which ones to use.

**Comment by matkoniecz** [comment]
Maybe "Wikipedia about artwork subject"/"Wikipedia about memorial subject"?

**Comment by 1ec5** [comment]
This and other Wikidata keys are being tracked in openstreetmap/id-tagging-schema#168.

**Comment by matkoniecz** [comment]
Migrated as https://github.com/openstreetmap/id-tagging-schema/issues/533
