### ISSUE TITLE
Add top toolbar item labels

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6098]
With the new ribbon controls and the upcoming contextual top bar (#5960), we'll be using the top bar a lot more like an actual toolbar. We should add small labels below the controls to save space within the buttons themselves and help users (particularly mobile users) infer what the buttons do without hovering.

Below are some examples. We wouldn't actually show this particular combination of controls together.

<img width="694" alt="Screen Shot 2019-03-25 at 10 01 49 AM" src="https://user-images.githubusercontent.com/2046746/54925924-abe68780-4ee5-11e9-8e45-c7786669cf72.png">

**Comment by bhousel** [comment]
This looks awesome

**Comment by BjornRasmussen** [comment]
Could the `Search` label be changed into something more descriptive? `Add a feature`, `Create feature`, or no label under the search bar would make more sense.

**Comment by quincylvania** [comment]
@BjornRasmussen I considered this and I think "Search" is fine. The placeholder text already says "Add a feature". It would look unbalanced to not have a label at all. I expect we'll eventually add search of existing features to that field anyway.
