### ISSUE TITLE
Write validation code documentation

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6100]
In order to help potential contributors and developers of downstream branches of iD, we should add info on how the validation system works to [ARCHITECTURE.md](https://github.com/openstreetmap/iD/blob/master/ARCHITECTURE.md).

**Comment by bhousel** [comment]
I'm changing some stuff in #6140, so we can hold off on this

**Comment by quincylvania** [comment]
So I added a fair amount about the validation system including issue severities, rules, types, subtypes, and changeset tags. If someone is interested in more details then I'd be happy to write more at a later time.
