### ISSUE TITLE
Two-step deletion of features with addresses

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6103]
Mappers should delete defunct points of interest, such as restaurants that go out of business. However, the address tags of these features are likely still valid for geocoding. We should encourage preservation of addresses by having two-step deletion of addressed features:

1. User clicks delete. All tags are removed except `addr:*` and the preset is thus downgraded to "Address".
2. User clicks delete again to fully delete the feature.

The feature would remain selected after step 1, so totally deleting the feature could still be done quickly with just one extra keypress.

Ideally we should find a good place to explain this behavior.

**Comment by bhousel** [comment]
This is a good idea 👍

**Comment by quincylvania** [comment]
I did this in 8779e1a6dcf24cb3a44e6589898d218d3379d623. It works for points, vertices, and buildings. The icon and text make it clear that you're downgrading, but the keyboard shortcut is the same. You can delete immediately after downgrading if you so choose.

![downgrade demo](https://user-images.githubusercontent.com/2046746/55442404-4d637e00-5563-11e9-9fa8-a8240abf4402.gif)

**Comment by bhousel** [comment]
Does this break the “delete a point” step of the walkthrough ?

**Comment by quincylvania** [comment]
> Does this break the “delete a point” step of the walkthrough ?

Oh good point. I just tested this and it does break if the user enters address data while entering the cafe, which they can. I'll fix it.

**Comment by bhousel** [comment]
Cool.. It would probably be easiest to silently delete whatever data needs to go away so the user can easily perform the delete step (instead of trying to rewrite the tutorial text - please don’t do this!)

**Comment by quincylvania** [comment]
@bhousel Yep, that's what I'll do!
