### ISSUE TITLE
Add a hotkey to toggle the OSM data layer

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6104]
Even in wireframe mode the OSM data can obscure too much of the background imagery:

<img width="772" alt="Screen Shot 2019-03-25 at 5 46 41 PM" src="https://user-images.githubusercontent.com/2046746/54957591-89765d80-4f29-11e9-8b79-945738fa928a.png">

While the user can open the Map Data pane to turn off the layer, it'd be easier if there were a shortcut to quickly toggle the data. I recommend a two-key combination such as Cmd+W to reduce users accidentally turning off all data and no knowing what to do.

**Comment by bhousel** [comment]
I'm ok with this, but we shouldn't use <kbd>Cmd+W</kbd> because that is the "close tab" shortcut and I hit it probably a thousand times a day for tab closing.
