### ISSUE TITLE
link to node shows wrong part of map

### ISSUE THREAD

**Issue by Discostu36** [openstreetmap/iD#6106]
When using a link like this
 
https://www.openstreetmap.org/edit?way=16125284

the map doesn't center on the node but shows the area I last edited in.

**Comment by quincylvania** [comment]
I see this when I click the link, as expected. Note that the link is to a way but the issue title says node. What browser are you using?

<img width="633" alt="Screen Shot 2019-03-26 at 8 27 55 AM" src="https://user-images.githubusercontent.com/2046746/54997029-30e2a700-4fa1-11e9-80e1-40b318ea9748.png">

**Comment by Discostu36** [comment]
Firefox 66.0. It happened with ways and nodes. But at the moment, I cannot reproduce the bug anymore. 

@Flying-Duck: Can you try to reproduce the error?

**Comment by Flying-Duck** [comment]
It is no iD issue. I have JOSM selected as my favorite editor so it seems to be an problem with JOSM. Changing the favorite editor to iD -> Everything is fine :-)

**Comment by quincylvania** [comment]
@Flying-Duck @Discostu36 Great! Closing this.
