### ISSUE TITLE
deprecating shop=fashion (to shop=clothes)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6109]
It appears that there is no clear and consistent difference between `shop=fashion` and `shop=clothes`.

I think it would be desirable to deprecate `shop=fashion` and start proposing changing to `shop=clothes`.

I updated https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfashion with links to ml discussion and some other details that I collected.

`shop=fashion` was added to presets with

> Thanks! I just added this field to Clothing Store (shop=clothes), and I also added it to the presets for shop=boutique and shop=fashion, because even the osm wiki admits that it's unclear what the difference is between all of these.

comment ( https://github.com/openstreetmap/iD/issues/4149#issuecomment-317022371 ) in https://github.com/openstreetmap/iD/commit/fce4d36b9537dd6c6bdc46f6504c9cd04dc009d0

**Comment by bhousel** [comment]
Sounds good to me - Since people don't like [`shop=boutique`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dboutique) for the same reason, can we deprecate that one also?

**Comment by matkoniecz** [comment]
`shop=boutique` in addition is in addition problematic in French speaking regions as it is also name for a small shop.

I was not fully checking for `shop=boutique` discussions but from what I know it is also something that should be discouraged.

**Comment by phiphou** [comment]
In french, a boutique is a general name for a small place where you can by something. I think. it's not specific enough for Openstreetmap. It's also a bit "deprecated" in french, we use "magasin" that means shop in almost every case. Boutique is used as an old name, for some luxury shop, Like Dior or Chanel or in certain specific cases, like a "boutique of souvenirs".
