### ISSUE TITLE
Save button tooltip runs off screen

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#6112]
Observed in chrome. Title is self explanatory, here's an image too

![image](https://user-images.githubusercontent.com/5459452/55023925-b7c16f00-4ff5-11e9-9727-607067529b5c.png)

**Comment by quincylvania** [comment]
Yep. The some of the other toolbar tooltips are also misaligned. The toolbar is undergoing lots of changes but this will all get fixed before release.

**Comment by SilentSpike** [comment]
I figured as much, just thought I'd open for tracking purposes 👍

**Comment by quincylvania** [comment]
@SilentSpike Thanks for testing and finding things!!

**Comment by SilentSpike** [comment]
No problem, I love the direction the toolbar is going as it opens up so many possibilities.
