### ISSUE TITLE
Saving/Uploading is broken

### ISSUE THREAD

**Issue by shiftee** [openstreetmap/iD#6116]
On both Firefox and Chromium when I click save the sidebar goes blank.

The map darkens as normal.

This means I cannot save my changes.

I'm using http://preview.ideditor.com/master

![Screenshot from 2019-03-27 10-02-31](https://user-images.githubusercontent.com/1383407/55067754-2fd07900-5078-11e9-8a7f-136fa531be5d.png)

**Comment by shiftee** [comment]
Switching the url to the release version in the address bar allowed me to restore and save my changes.

From:
http://preview.ideditor.com/master/XXXXXXX
to:
http://preview.ideditor.com/release/XXXXXXX

**Comment by bhousel** [comment]
Thanks @shiftee - looks like I broke this last night 😱
