### ISSUE TITLE
Add checkbox for "flood_prone" key to "moreFields" of minor roads 

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6117]
https://wiki.openstreetmap.org/wiki/Key:flood_prone

**Comment by prateeklal** [comment]
Could you please share a rough mockup of where this should be added?

**Comment by quincylvania** [comment]
The documentation for adding fields to presets is `here`. Basically you would need to add a `flood_prone.json` file under `fields` that is a `check` type for the `flood_prone` key. Then add `flood_prone` to `moreFields` of some of files like `presets/highway/service.json`, `presets/highway/track.json`, and `presets/highway/residential.json`.

**Comment by quincylvania** [comment]
Done in #6120
