### ISSUE TITLE
Ajouter un lien vers les pages Facebook

### ISSUE THREAD

**Issue by hugobqd** [openstreetmap/iD#6121]
Beaucoup de petits commerces ne disposent pas de site web mais uniquement d'une page Facebook, c'est pourquoi il serai utile de **proposer dans les fiches le lien Facebook**, libre à l'utilisateur de le consulter ou non.

Je sais que Facebook n'est pas forcément bien vue par les défenseurs de la vie privé, néanmoins il ne s'agit là que de proposer un lien. Il est bien proposé des liens vers des sites qui effectue du tracking.

**Comment by hugobqd** [comment]
Pendant ce temps sur qwant : 
<img width="792" alt="Capture d’écran 2019-03-27 à 18 47 32" src="https://user-images.githubusercontent.com/35178/55100098-51098780-50c1-11e9-83ea-9ba7ab281d05.png">
https://www.qwant.com/maps/place/osm:node:4259000870@Linstant_Gourmand

**Comment by BjornRasmussen** [comment]
Je crois que le meillure solution est créer un « field » pour tout les resaux socials : Facebook, Instagram, Twitter, Whatsapp, Google+, Telegram, LinkedIn, XING, Skype, Flickr, YouTube, Pinterest, et peut être des autres si ils existent.
https://wiki.openstreetmap.org/wiki/Key:contact

**Comment by quincylvania** [comment]
https://wiki.openstreetmap.org/wiki/Key:contact

Hello, @hugobqd. This is a tough decision, but we cannot support a Facebook tag at this time. It would be difficult to support all the possible websites without making the UI too confusing. Many mappers would not support giving special treatment to Facebook and other large tech companies. It is okay to put a Facebook URL in the Website field if the business does not have a separate website. You can also add the `contact:facebook` tag manually at the bottom of the editor.

Auto-translated:

Bonjour, @hugobqd. C'est une décision difficile, mais nous ne pouvons pas prendre en charge une balise Facebook pour le moment. Il serait difficile de soutenir tous les sites Web possibles sans rendre l'interface utilisateur trop confuse. De nombreux mappeurs ne seraient pas en faveur de donner un traitement spécial à Facebook et d'autres grandes entreprises de technologie. Il est correct de mettre une URL Facebook dans le champ site Web si l'entreprise ne dispose pas d'un site Web distinct. Vous pouvez également ajouter la balise `contact:facebook` manuellement en bas de l'éditeur.

**Comment by hugobqd** [comment]
OMG I'm very sorry ! This issues was for https://www.qwant.com/maps/ (who display OSM data).
I'm very sorry to waste your time. Great job BTW, ID is getting better every days, love it !

**Comment by quincylvania** [comment]
@hugobqd 😂 Not a problem, thanks for the compliment!
