### ISSUE TITLE
For newly created objects with name matching entry from from name-suggestion-index suggest adding POI tags

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6122]
See for example https://www.openstreetmap.org/way/678166526/history - user added just `building=retail name=Lidl` without `shop=supermarket`.

In such case iD can suggest adding also presumably missing POI tags.

Preferably in way that will teach user how to fix this on their own (to avoid problem with people relying on this and being unable to add nonbrand shops).

**Comment by BjornRasmussen** [comment]
I think that the new outdated tags validation does this now.

**Comment by quincylvania** [comment]
> I think that the new outdated tags validation does this now.

iD does offer to upgrade features to brands where the preset tags and name match a brand. It does not offer to upgrade just a name, but we flag features with only names anyway so I think that is good enough.

**Comment by bhousel** [comment]
Yes but I read this as about flagging `building=yes` or `shop=yes` , which I don't think get flagged..

**Comment by quincylvania** [comment]
@bhousel I'm not sure how confident we can be about accuracy in those cases, but you'd know better than I. Go ahead and reopen this if you think we should do it!

**Comment by quincylvania** [comment]
I think #7197 was the same as this, which was closed and moved to https://github.com/osmlab/name-suggestion-index/issues/3454.

@bhousel What do you think?

**Comment by bhousel** [comment]
> @bhousel What do you think?

Oh yeah it is the same thing.. Back when this issue was originally opened, the NSI didn't have matcher code yet. 

I agree that we can put something in the NSI matcher to catch the `shop=yes` features.  I don't remember why I reopened it?
