### ISSUE TITLE
Add ignored warning counts to the changeset tags

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6123]
Users can ignore iD's warnings when uploading their changes, so we should tag changesets with the number of warnings of each type that iD found with the edited features. This will give validators better information when searching or checking changes.

The tags would not be to assign blame. iD can sometimes give false positives and show warnings that aren't the user's fault. Still, we can assume that a changeset with 100 warnings needs more attention than one with 2 warnings. Note that users can also turn off validation rules to silence warnings, preventing them from being tagged.

Examples:

- `warnings:crossing_ways=14`
- `warnings:disconnected_way=3`
- `warnings:outdated_tags=9`
- `warnings:private_data=1`

**Comment by mmd-osm** [comment]
In [this post](https://lists.openstreetmap.org/pipermail/talk/2019-April/082376.html), @simonpoole raised the point about _particularly problematic "recent" additions: recording the last position in the walk through and recording the number of warnings that have been ignored in changesets._. 

I'm not exactly sure why this is problematic, it could be some privacy issue, or invite people to fudge with the map to make those warnings go away, essentially creating questionable incentives to tweak their stats. Maybe Simon could elaborate a bit on his comment?

**Comment by simonpoole** [comment]
There is at least a privacy issue and a community issue. Not only on initial publishing but compounded by the information being available for eternity, even in medieval times we didn't put people on a pillory forever (at least not as the norm).
  
Now obviously there is some short term value in having the information available for scoring that could be used to justify making the counts available to QA tools, but how to do that needs some thinking.

**Comment by quincylvania** [comment]
@mmd-osm @simonpoole Speaking to the warning counts:

I don't see a privacy issue. The warnings are derived from the publicly-posted changes and the open-source version of iD (which is also noted in the changeset). A savvy developer could load the changeset into that version of iD and see the same warnings anyway.

I'll reiterate what I said in my original post:

> The tags would not be to assign blame. iD can sometimes give false positives and show warnings that aren't the user's fault. Still, we can assume that a changeset with 100 warnings needs more attention than one with 2 warnings. Note that users can also turn off validation rules to silence warnings, preventing them from being tagged.

These tags aren't for "scoring" nor punishing, they're to help changeset reviewers identify possible errors and places for improvement. Most users will never know the tags are even there. If the OSM community ends up alienating mappers based on these tags, then that's a reflection on the community, not this feature.

**Comment by mmd-osm** [comment]
Rules in QA tools evolve over time, though changeset tags will be immutable once the changeset has been closed, that's basically forever. I think what Simon alludes to is that changeset tags may not be the perfect place to store this kind of information.

I don't know if some people will be intimidated by such stats, or find it creepy. Hopefully that won't be the case...
