### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by KenyaLS** [openstreetmap/iD#6126]
#### Building iD

1. `cd` into the newly cloned project folder
2. Run `npm install`
3. Run `npm run all`
3. Run `npm start`
4. Open `http://localhost:8080/` in a web browser

![Снимок экрана от 2019-03-29 00-34-45](https://user-images.githubusercontent.com/20774076/55187568-49b1af00-5191-11e9-9bd1-e873c429e355.png)

### **npm start error**

> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! iD@2.14.3 start: `node development_server.js develop`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the iD@2.14.3 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Debug.log**

- 
- 0 info it worked if it ends with ok
- 1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start' ]
- 2 info using npm@6.9.0
- 3 info using node@v8.11.4
- 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
- 5 info lifecycle iD@2.14.3~prestart: iD@2.14.3
- 6 info lifecycle iD@2.14.3~start: iD@2.14.3
- 7 verbose lifecycle iD@2.14.3~start: unsafe-perm in lifecycle true
- 8 verbose lifecycle iD@2.14.3~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/yandai/node_modules/OpenSteetMap/node_modules/.bin:/home/yandai/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/root/.dotnet/tools
- 9 verbose lifecycle iD@2.14.3~start: CWD: /home/yandai/node_modules/OpenSteetMap
- 10 silly lifecycle iD@2.14.3~start: Args: [ '-c', 'node development_server.js develop' ]
- 11 silly lifecycle iD@2.14.3~start: Returned: code: 1  signal: null
- 12 info lifecycle iD@2.14.3~start: Failed to exec start script
- 13 verbose stack Error: iD@2.14.3 start: `node development_server.js develop`
- 13 verbose stack Exit status 1
- 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
- 13 verbose stack     at emitTwo (events.js:126:13)
- 13 verbose stack     at EventEmitter.emit (events.js:214:7)
- 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
- 13 verbose stack     at emitTwo (events.js:126:13)
- 13 verbose stack     at ChildProcess.emit (events.js:214:7)
- 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
- 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
- 14 verbose pkgid iD@2.14.3
- 15 verbose cwd /home/yandai/node_modules/OpenSteetMap
- 16 verbose Linux 4.18.0-16-generic
- 17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start"
- 18 verbose node v8.11.4
- 19 verbose npm  v6.9.0
- 20 error code ELIFECYCLE
- 21 error errno 1
- 22 error iD@2.14.3 start: `node development_server.js develop`
- 22 error Exit status 1
- 23 error Failed at the iD@2.14.3 start script.
- 23 error This is probably not a problem with npm. There is likely additional logging output above.
- 24 verbose exit [ 1, true ]

And Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
![Снимок экрана от 2019-03-29 02-12-37](https://user-images.githubusercontent.com/20774076/55193282-67394580-519e-11e9-8609-71cb391db4a8.png)

**Comment by bhousel** [comment]
I just tried this, and it seems ok now.
Did you ever find out what the issue was?
