### ISSUE TITLE
Where the form is stored so that it can add its code. Traffic Light Forms

### ISSUE THREAD

**Issue by KenyaLS** [openstreetmap/iD#6128]
![Снимок экрана от 2019-03-29 17-50-36](https://user-images.githubusercontent.com/20774076/55233728-4bc34e80-5221-11e9-8c6d-ec762778fca4.png)

Where the form is stored so that it can add its code. Traffic Light Forms, in your test server.

**Comment by bhousel** [comment]
The presets and fields are defined as `.json` files stored under the `/data/presets/` folder.

The traffic signal preset is here:
https://github.com/openstreetmap/iD/blob/master/data/presets/presets/highway/traffic_signals.json

This README has some more information about these files:
https://github.com/openstreetmap/iD/blob/master/data/presets/README.md
