### ISSUE TITLE
modify preset name: shop=farm

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6129]
current naming is like "Produce stand"
i propose new name "farm shop" or similar

see wiki: https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfarm

Or does that needs to be done in transiflex?

**Comment by bhousel** [comment]
The current name is fine

**Comment by sun-geo** [comment]
Why do you think so?

produce stand:   https://duckduckgo.com/?q=produce+stand&t=h_&iax=images&ia=images
vs
farm shop:   https://duckduckgo.com/?q=farm+shop&t=h_&iax=images&ia=images

**Comment by bhousel** [comment]
If we call it a "farm shop" people will mix it up with:
-  [shop=agrarian](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dagrarian).  We have a preset for that one called "Farm Supply Shop", but it's still really similar.
- [shop=greengrocer](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dgreengrocer). We have a preset for that one called "Greengrocer".

So let's just leave it alone.  There are too many similar shop tags like this, and it probably doesn't really matter what people pick most of the time anyway.

**Comment by BjornRasmussen** [comment]
I would understand "Farm shop" as meaning farm supply shop if I saw a preset named that in iD. +1 to keeping the current name.

**Comment by sun-geo** [comment]
OK, thank you for your input.

for central Europe there is a map available called: http://farmshops.eu/
You can find POIs where you can buy regional, seasonal, freshly harvested goods from the farmer.
Actually and not POIs for "farmer-suplly-products".

Is the naming for http://farmshops.eu/ also wrong?

**Comment by bhousel** [comment]
> Is the naming for http://farmshops.eu/ also wrong?

They are free to name their website whatever they want to.  🤷‍♂️ 

Can we just leave the preset name alone please.   In iD we have to think about what the specific phrase "Farm Shop" means to untrained people who see it on a list mixed in with all the rest of the things in the world.  Also it's Sunday and I just kind of want to enjoy my weekend.
