### ISSUE TITLE
Tag adding: iD adds tags on the next (wrong) way

### ISSUE THREAD

**Issue by bibi6** [openstreetmap/iD#6130]
Hi,

I experienced the following issue with iD yesterday and today.
**Steps to reproduce**
1) Go somewhere in the map where there are two ways. (As an example, I take ways 117331833 and 117331832).
2) Select one way.
3) Using the tag editor, add a new key/value tag:
3a) click on "+",
3b) enter the key,
3c) TAB, then enter the value.
4) Immediately after entering the value, click on the other way.

**What iD does:**
The second way gets the key/value tag. The first way gets a new tag with the correct key, but with an empty value.
**What is expected:**
Of course, the first way with the correct key/value tag, and the second without it.
Note that the update is correct as soon as the second way had already the corresponding key.
**Configuration**
Firefox 66.0.1 running on Ubuntu 16.04. iD version 2.14.3 .

**Comment by 1ec5** [comment]
I’m seeing this bug too on occasion. Seems to be easier to reproduce if there are a lot of changes or things are otherwise running kind of slow.

**Comment by bhousel** [comment]
This is #6028
