### ISSUE TITLE
Move toggles for KeepRight and ImproveOSM issues to the Issues pane

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6132]
The toggles for "KeepRight Issues" and the "ImproveOSM Issues" should live in the Issues pane instead of the Map Data pane. This will consolidate most of our QA tools to a single location. It also gives us more leeway with adding more controls for these services, like toggles for specific KeepRight rules or ImproveOSM detection types.

<img width="389" alt="Screen Shot 2019-04-01 at 3 41 50 PM" src="https://user-images.githubusercontent.com/2046746/55354963-fdb68100-5494-11e9-8c9d-f365c0c84200.png">

**Comment by bhousel** [comment]
I've been thinking about this a lot, and I kind of would prefer for the Issues pane to just be for iD's internal live validator.  

I know that the KeepRight and ImproveOSM issues are related to fixing issues, but they really are overlay layers of data fetched from somewhere else, which is very different from what the Issues pane can do. 

I am even ok with moving external validation services over there eventually somehow, but my worry is that someone will show up and do the simplest possible thing to close this issue, and it won't fit with what the Issues pane does today.  (So.. can we keep this as "considering"?)

**Comment by quincylvania** [comment]
@bhousel That's fine. There's been some talk about integrating server-side issues with native issues. I don't see that as a priority though. Feel free to close.

**Comment by abalosc1** [comment]
I would agree, I would consider KeepRight and ImproveOSM issues as data (which may even be out of date with the data that is being validated by the Issues Pane). They're also different workflows that might involve resolution, so it's good to make that distinction.
