### ISSUE TITLE
"Bike Lanes" dropdowns not initialized from cycleway:right and cycleway:left values

### ISSUE THREAD

**Issue by ejegg** [openstreetmap/iD#6141]
Note in 'all fields' that cycleway:right is set to 'track' but that in the 'Bike Lanes' field grouping, neither 'Left side' nor 'Right side' dropdowns have any value set. In this case, the 'Right side' dropdown should be initialized to 'track'.

![Screenshot from 2019-04-04 17-19-42](https://user-images.githubusercontent.com/1018606/55592547-563c8700-56fe-11e9-8989-c588ffc1b24d.png)

Browser: Chromium 73.0.3683.75 built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Comment by quincylvania** [comment]
In my testing I would see this when selecting a different feature and then clicking on the road. Selecting the road after having nothing selected would be okay.
