### ISSUE TITLE
Changing/creating the preset for embassies, consulate and liaison

### ISSUE THREAD

**Issue by lgiard** [openstreetmap/iD#6144]
Hello,
Since the **new method of tagging embassies and consulate** ([with office=diplomatic - WIKI link](https://wiki.openstreetmap.org/wiki/Tag:office=diplomatic)) has been approved end of last year ([look at the accepted proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/office%3Ddiplomatic)), it should be useful to support this in ID editor preset. The old tag "amenity=embassy" is now in the process of [being deprecated](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dembassy). 

I think that the only existing preset is the embassy preset, and it should be changed as follow:
- embassy : "office=diplomatic"+"diplomatic=embassy" (with the secondary tag "embassy=*" that get multiple possibilities if the mapper want to add further details - [look here for the values](https://wiki.openstreetmap.org/wiki/Tag:office=diplomatic#Tertiary_values)).

Then, we need to create two other new presets : 
- One for consulate : office=diplomatic + diplomatic = consulate (+ consulate=* )
- One for liaison : office=diplomatic + diplomatic = liaison (+ liaison=* ).

And of course, the others secondary tags common for the three categories : 
- diplomatic:services:non-immigrant_visas=[yes/no]
- diplomatic:services:immigrant_visas=[yes/no]
- diplomatic:services:citizen_services=[yes/no];
- name=*
- country=* (the two-character ISO 3166-1 alpha-2 code for the sending country or organization)
- target=* (the two-character ISO 3166-1 alpha-2 code for the receiving (accrediting) country or organization)

For more information, the description is quite detailed on the wiki page.

**Comment by bhousel** [comment]
Thanks for the links, this seems fine 👍
