### ISSUE TITLE
Transifex - Presets - empty terms not translatable?

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/iD#6148]
In the default English locale, the `terms` string is empty for some presets.

Now, in Transifex, the translation key [key:presets.presets.amenity/bus_station.terms](https://www.transifex.com/openstreetmap/id-editor/translate/#de/presets?q=key%3Apresets.presets.amenity%2Fbus_station.terms) seems to be missing. [key:presets.presets.amenity/bus_station.name](https://www.transifex.com/openstreetmap/id-editor/translate/#de/presets/28758534?q=key%3Apresets.presets.amenity%2Fbus_station.name) exists.

Apparently, empty strings are not properly exported to Transifex. This was reported in #1633 which was seemingly fixed back then.

**Comment by quincylvania** [comment]
The `amenity/bus_station` preset is unsearchable. We don't include search terms for unsearchable presets since they're not used anywhere in the app.

**Comment by westnordost** [comment]
Ah, okay

**Comment by quincylvania** [comment]
@westnordost Thanks for looking out for this stuff and thinking of ways to make the presets better!
