### ISSUE TITLE
Show background imagery dates / offer "order by date"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6150]
As a long term goal, it would be nice to have the dates of each
background listed in a new column at the right of

```
Background
￼
V Backgrounds
￼
Bing aerial imagery
￼
DigitalGlobe Premium Imagery
￼
DigitalGlobe Standard Imagery
￼
Esri World Imagery
￼
Esri World Imagery (Clarity) Beta
￼
Mapbox Satellite
￼
OpenStreetMap (Standard)
￼
OpenTopoMap
￼
Stamen Terrain
￼
```

as currently the user has no *easy* way to know which background was
snapped last year vs. five years ago.

**Comment by tastrax** [comment]
Hi Dan,

 

I suspect that is a huge ask given that individual tiles across the world are all taken at different times (and then post processed)

 

Cheers - Phil

**Comment by jidanni** [comment]
> Hi Dan, I suspect that is a huge ask given that individual tiles across the world are all taken at different times (and then post processed) Cheers - Phil 

Yes, so it is a long term wishlist item.
And just like these views updating constantly as one moves the current position when not editing,
![Q_0](https://user-images.githubusercontent.com/1230959/55678968-5ecad280-5935-11e9-8bbb-214316e59d8c.jpg)
One might say it would be a luxury feature.

**Comment by Adamant36** [comment]
I seem to remember this caming up before somewhere a few years ago and the general reason for not providing the dates for each tile back then was that it extremely dependent on source providing the details and in most cases they don't. So there's no way for it to be added to the interface. Although there is a list somewhere that says the years a lot of sets for the main image providers were taken in cases where the images were originally commissioned by local governments. Since its public information. I'll have to look into it again.

**Comment by jidanni** [comment]
I've gotten used to always having a date staring me in the face (Google
Earth).

Today I was editing a campground and had to compare the many layers back
and forth trying to figure out which was the newest.

Another idea is OK, actual dates are tough. But maybe order the layers
in the list by which one is newest (arrival at OSM.) OK, nobody wants
the familiar order changing every day, so maybe add a rank number to the
right of the layer name to denote which is newest (right not left as
this blank padded one or two digit number won't mess up the column
alignment.)

It could work like: OSM got more Norrfleburg Zeppelin photos today,
(not sure when taken. All we know is the "Norrfleburg truck dumped them
into the OSM warehouse this morning.")
therefore "pop Norrfleburg out of the list and push it back on the top",
now its rank is 1.

One might say well east of the lake Norrfleburg's photos are the newest,
but not west. So if possible this should not be a global variable, but
region dependent.

**Comment by jidanni** [comment]
So the user could still refer to the "relative freshness rank" without needing the "more expensive" exact date.

**Comment by jidanni** [comment]
Ah, I've got it, here,
![Q_1](https://user-images.githubusercontent.com/1230959/55679229-6a6cc800-593a-11e9-9397-cc20b13d7d38.jpg)
add a selector:
```
[x] order by name (the current order)
[ ] order by date
```

**Comment by bhousel** [comment]
Yeah, as said above we often don’t have the dates, so we can’t implement this.
