### ISSUE TITLE
Add preset for natural=shingle

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#6155]
Hi,

in Transifex, for natural=*, we can find the words scrub, wood, cliff and so on so these words can be translated in any langage.
But shingle is not in Transifex : so in ID natural=shingle has no translation but the general translation for 'natural' which is quite bad.

Could you fix that ?
Best regards

**Comment by bhousel** [comment]
sure, thanks for letting us know!
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dshingle

**Comment by Mahabarata** [comment]
Sorry to come back : I just try the other one (in the list of ID for "natural") and find some strange things :
- in ID, natural=valley is not translated in french : but natural=valley is in transifex with a good translation
- natural=rock (170 000 objects in taginfo) is, like shingle, not in transifex

Best regards
