### ISSUE TITLE
Change areaKey to linestring for advertising=sign

### ISSUE THREAD

**Issue by jeisenbe** [openstreetmap/iD#6157]
The areaKey for advertising=sign should be changed to linestring.

I just reviewed all of the features tagged with the key `advertising=*` and mapped as a way in the OSM database. Most of these are billboards, but 614 objects are tagged with other values of advertising. 

Of these, 396 are mapped as closed ways: 265 are advertising=column, 41=poster_box, 26 =yes and 25 =sign

218 objects are open ways (mostly with just 2 nodes). There are 92 advertising=sign and 52 poster_box (the rest are <10).

Currently, it appears that all features tagged with just "advertising=*" are considered polygons/areas, except for the value "billboard." I suggest adding the value "=sign" to the list of exceptions, based on the current mapping practice.

I can submit a PR to https://github.com/osmlab/id-area-keys/blob/master/areaKeys.json if desired.

**Comment by bhousel** [comment]
Sorry, but we are following the recommendation on the osm wiki to allow these features to be mapped as points or areas.  see #3386 and #4961

https://wiki.openstreetmap.org/wiki/Tag%3Aadvertising%3Dcolumn
https://wiki.openstreetmap.org/wiki/Tag%3Aadvertising%3Dsign

Going by the raw counts of what is actually mapped is not a great way to decide which geometries make sense to support.  I think in this case people just don't map a lot of advertising columns as circular areas, but that doesn't mean we should prevent them from doing so if they have good enough imagery to use as a reference.


> I can submit a PR to https://github.com/osmlab/id-area-keys/blob/master/areaKeys.json if desired.

No need, that project is automatically generated from the iD presets.  So the thing to change is the presets, if we were going to change anything.

**Comment by jeisenbe** [comment]
I'm sorry if I wasn't clear. 

The wiki and database usage both confirm that advertising=column should be considered an area feature, so the current status is correct. 

It's only advertising=sign that is mapped most frequently as a linear, unclosed way. Perhaps I was misunderstanding how the ID presets and the [areaKeys.json](https://github.com/osmlab/id-area-keys/blob/master/areaKeys.json) file works. 

Now I see that advertising=sign is probably not considered in the presets at all, and areaKeys.json is based on the presets, so this project is not making any decision about the geometry of this feature.

**Comment by tordans** [comment]
Hi jeisenbe!

> It's only advertising=sign that is mapped most frequently as a linear, unclosed way. Perhaps I was misunderstanding how the ID presets and the [areaKeys.json](https://github.com/osmlab/id-area-keys/blob/master/areaKeys.json) file works.

iD only has presets for advertising/billboard and advertising/column, see https://github.com/openstreetmap/iD/tree/master/data/presets/presets/advertising

> Now I see that advertising=sign is probably not considered in the presets at all, and areaKeys.json is based on the presets, so this project is not making any decision about the geometry of this feature.

Another indicator is, to add the key to a point in the editor and see that it is still described as a point:

<img width="386" alt="Bildschirmfoto 2019-04-09 um 18 56 53" src="https://user-images.githubusercontent.com/111561/55819666-997d6800-5af9-11e9-9b1b-1c315abeed7a.png">

--- 

Personally I don't see the need to suggest https://wiki.openstreetmap.org/wiki/Tag:advertising%3Dsign for the preset list. Does osm-carto render it?/How?
