### ISSUE TITLE
Change areaKey to linestring for attraction=roller_coaster and =log_flume

### ISSUE THREAD

**Issue by jeisenbe** [openstreetmap/iD#6158]
The tag attraction=roller_coaster should be considered a linestring feature.

Currently the key "attraction" is listed as an area, except for the values: dark_ride, river_rafting, summer_toboggan, train, and water_slide.

As of 7 April 2019, attraction=roller_coaster is tagged on a closed way 331 times, and 2 times on relations. Compare this to 1,572 non-closed ways tagged attraction=roller_coaster. I reviewed a number of these, and most of the linear / non-closed ways follow the route of the roller coaster tracks. 

It appears that the most common mapping method for attraction=roller_coaster is to map the path of the tracks. 

While there was a previous proposal to map roller_coaster tracks with roller_coaster=track and the "attraction" as an area, this method is less common. https://wiki.openstreetmap.org/wiki/Proposed_features/key:roller_coaster

Also, the tag attraction=log_flume is usually mapped along the route of the ride, similar to water_slide, river_rafting, and dark_ride. It is currently used 212 times, and 116 are unclosed ways. There are 69 closed ways, but I downloaded these and review several. Most of the closed ways appear to map the route of the water ride, the same as the open ways, but just don't have any parts that self-intersect.

While attraction=log_flume is fairly rare, it is more common than dark_ride which is currently listed, and is the #10 most common value for the key "attraction"

**Comment by jeisenbe** [comment]
Might also consider adding attraction=slide to the list of exceptions. It is only used on ways 32 times, but 22 are non-closed.

**Comment by bhousel** [comment]
Sorry, but we are following the recommendation on the osm wiki to allow these features to be mapped as points and areas. 

https://wiki.openstreetmap.org/wiki/Tag:attraction%3Droller_coaster

Going by the raw counts of what is actually mapped is not a great way to decide which geometries make sense to support.  

Please stop making requests like this.  When it comes to presets we are just doing our best to give people what they asked for and trying to follow what the wiki says to do, even though it's very inconsistent.  Because it changes frequently it's hard to take too seriously.

**Comment by bhousel** [comment]
Things to watch for over the next few days: 
- Someone will edit the roller coaster page to say that iD is pushing a broken view of roller coaster mapping.
- The German talk list will spread a conspiracy theory that evil corporations are pushing a hidden agenda to have roller coasters mapped a certain way.
- A long standing HOT troll will complain on a talk list about how iD users are not mapping their roller coasters with square enough corners and encourage everyone doing serious roller coaster mapping to switch to JOSM.
- Weekly OSM, a popular tabloid, will cover all of this as if it is actual news that affects the project in any significant way.
- The Anonymaps twitter account will amplify all this nonsense.  Look for them to win another award next year for doing so.
- 0 PRs will be submitted to iD to fix actual problems with anything.

**Comment by jeisenbe** [comment]
I'm sorry if this issue wasn't helpful. 

In this case, the usage is mixed for attraction=roller_coaster (and attraction=slide, though maybe this doesn't have a preset?), so it's fine to keep them imported as polygons, but I thought I should mention what I found in the data. 

I normally contribute to [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto), and I had really appreciated that @bhousel had [suggested](https://github.com/gravitystorm/openstreetmap-carto/issues/3611#issuecomment-454064706) that we look at [areaKeys.json](https://github.com/osmlab/id-area-keys/blob/master/areaKeys.json) to find which keys and tags should be imported as polygons vs linestrings. Since I am working on some PRs to address this at openstreetmap-carto, I had done research to find out if the use of the tags was consistent with the wiki documentation. 

As you mentioned, the wiki "it's very inconsistent. Because it changes frequently it's hard to take too seriously," though it many cases it is correctly documented. Ot's a good policy to occasionally check if the data on taginfo and the geometries of features in the database match what the wiki says.

I've found the the vast majority of the polygon vs linestring choices in [areaKeys.json](https://github.com/osmlab/id-area-keys/blob/master/areaKeys.json) are accurate, matching both the wiki and actual usage in the database, so it's been very helpful. For example, for the key "playground" the 3 features that ID excludes as linestrings are the ones that are by far most often mapped as open linear ways rather than closed ways/areas. There are just a few exceptions where the current presets in this repository do not match the wiki or common usage, so I thought they should be discussed.  

I don't have any experience with Javascript so I can't help close any major open issues, but researching tag usage and helping keep things consistent between ID and Openstreetmap-carto are things that I could help with, but if this isn't desired, I'll avoid opening more issues. I could certainly submit PRs for easy things; I'll see if any of the "good first issues" look doable.

**Comment by tordans** [comment]
@jeisenbe after reading your last comment I am not sure if there actually is something that maybe should be changed or not. In any case, the way I personally read the current "meta"/community-discussion about tagging and presets (and also Bryans comment) is: iD should be in sync with the wiki as far as possible. If the wiki is not in sync with the current tagging practice, ideally the wiki should be changed first – which involves community-discussion most of the time – and only then iD.
