### ISSUE TITLE
Is changing the "make square" shortcut a good idea?

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6159]
I read in some sub thread that the squareing-shortcut was changed from `s` to `q`. There was also a reason why, that I don't recall.

I just wanted to double check, that this change is really the best idea.

**Pro:**
- I believe there was an argument that it is more like josm now?
- I believe there was a conflict with another shortcut?
- ?

**Con:**
- my muscle memory has to be re-trained :-) 
- all the HOTOSM tutorials in most of the campaigns need to be updated, they all explain somethink like 
  > Please square your buildings ('S' key in the iD web editor) and keep them unattached from roads, landuse and other buildings unless they are physically attached.
  ([Source](https://tasks.hotosm.org/project/5885#bottom))
- ?

**Comment by bhousel** [comment]
Yes, #5999 is what you're looking for. 
We know it's a big change for a lot of people used to hitting <kbd>S</kbd>, but it allows us to both straighten or square lines too, which is a big benefit.

**Comment by tordans** [comment]
@bhousel thanks. I didn't get at first, that the s-key is still there but only to straighten lines now. It all makes sense now :).

Do you have an easy way to contact someone relevant at the HOTOSM crew so they update their help texts after the release?

We could also create an issue at https://github.com/hotosm/tasking-manager/issues/ to let them know now and post that in their slack as a FYI.

**Comment by bhousel** [comment]
> Do you have an easy way to contact someone relevant at the HOTOSM crew so they update their help texts after the release?
> 
> We could also create an issue at https://github.com/hotosm/tasking-manager/issues/ to let them know now and post that in their slack as a FYI.

You can if you want.  I quit their stuff last year.

**Comment by jidanni** [comment]
(Actually it should be called a rectangle tool, not square tool.)

**Comment by quincylvania** [comment]
> (Actually it should be called a rectangle tool, not square tool.)

@jidanni All the operations have verb names. "To square" means to make corresponding lines parallel and to make corners 90 degrees. "To rectangle" doesn't mean anything. But that has nothing to do with this issue.
