### ISSUE TITLE
Allow disconnecting multiple vertices at once

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6164]
Users should be able to run the disconnect operation on multiple nodes at once when more than one is selected. For example, a road could be connected to a landuse for only a few nodes. The user could use the lasso tool to select all the points and then press <kbd>D</kbd> to quickly separate them all.

See #4245 for disconnecting all the nodes of a way at once.

**Comment by BjornRasmussen** [comment]
Awesome! I've been wanting to request a feature like this for a while now.
