### ISSUE TITLE
Edit link with additional URL parameter 'newkey'

### ISSUE THREAD

**Issue by sfkeller** [openstreetmap/iD#6171]
More and more websites detect missing tags in OSM. What's desirable is to offer an "Add missing ..." text which contains an edit link to iD with an additional URL parameter e.g. '**&newkey=<any_key_name>**'. 

So for example Restaurant Woodward Table, Washington D.C., at https://www.openstreetmap.org/node/739150331 currently misses website "http://woodwardtable.com/". The corresponding link would then be 

  `https://www.openstreetmap.org/edit?node=739150331&newkey=website`

The effect would be that iD starts in edit mode with node 739150331 selected, and in addition key 'website' is being added to the tag list of the object. If key 'website' is already there, iD ignores it.

**Comment by bhousel** [comment]
Yes, this is #3645
