### ISSUE TITLE
Remove the validation fix that automatically adds "bicycle=designated" to cycleways

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6172]
The current situation has iD suggestion that I update the "outdated tags" of cycleways by automatically adding `bicycle=designated`, which is (according to the access tags editor in iD) already assumed.  
2 Solutions: 
* The upgrading system should ignore this "error"
* The access tags editor should not indicate that trails tagged as `highway=cycleway` are assumed to have `bicycle=designated`

**Comment by quincylvania** [comment]
This warning only appears when the cycleway also has `foot=designated`. The idea is to reduce the use of implicit access tags once the user starts making access explicit.

**Comment by BjornRasmussen** [comment]
Ok, that sounds good. I'm fine with closing this.

**Comment by quincylvania** [comment]
@BjornRasmussen Thanks for the thought!
