### ISSUE TITLE
Adopt crosshairs feature

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6173]
Here https://gis.swcb.gov.tw/ has a crosshairs in center of the screen feature we could adopt,
![Q_1](https://user-images.githubusercontent.com/1230959/56007278-c2c11280-5d0a-11e9-88b5-f440122ca2f5.jpg)
E.g., when activated there would be no doubt where e.g., searching for the point "24,121"
https://www.openstreetmap.org/edit#map=19/24.00000/121.00000
actually lies upon the screen.

**Comment by BjornRasmussen** [comment]
I really don't like this idea, since the location people searched for is usually just the area they want to edit in, not an exact location.  I don't see any use for this feature.

**Comment by bhousel** [comment]
The location panel does exactly this, but with your mouse pointer instead of a crosshairs.

![location](https://user-images.githubusercontent.com/38784/56049635-ed659800-5d17-11e9-9c05-bfe0c5c0ef4a.gif)

**Comment by jidanni** [comment]
> The location panel does exactly this, but with your mouse pointer instead of a crosshairs.

Works great if there is a certain different colored house that you can remember when you finally move the pointer to where the numbers all match up to what you want.

But if we want to put an object at an exact known X,Y, well there is an assumption that we must not really know the exact X,Y or else we would be using JOSM. Or that we can always base our edits on some satellite photo's nearby features.

**Comment by jidanni** [comment]
Problem:

On e.g.,
https://commons.wikimedia.org/wiki/File:P_20190317_124105_vHDR_On_1.jpg
the user sees
> Camera location	￼24° 07′ 54.93″ N, 120° 41′ 35.05″ E ￼	View this and other nearby images on: OpenStreetMap - Google Earth

And these lead to many links like
$ mech-dump --links 'https://tools.wmflabs.org/geohack/geohack.php?pagename=File:P_20190317_124105_vHDR_On_1.jpg&params=024.131925_N_0120.693070_E_globe:Earth_type:camera_&language=en' | grep openstreet
www.openstreetmap.org/?mlat=24.131925&mlon=120.69307&zoom=15&layers=M
https://nominatim.openstreetmap.org/reverse?lat=24.131925&lon=120.69307&zoom=8
https://openstreetbrowser.org/#map=8/24.131925/120.69307
http://agri.openstreetmap.org/?zoom=15&lat=24.131925&lon=120.69307
http://aerial.openstreetmap.org.za/?lon=120.69307&lat=24.131925&zoom=15

Alas there will never be a good "edit" link possible,
as even the best one could construct,
https://www.openstreetmap.org/edit#map=21/24.131925/120.69307
lacks crosshairs.

One might think "Well even trash bins are visible on the Bing background these days. No need for crosshairs." Alas we are trying to put the above palm-sized item on the map.

**Comment by jidanni** [comment]
P.S.,
> The location panel does exactly this, but with your mouse pointer instead of a crosshairs.

I can't find any "location panel." Perhaps it was removed.

**Comment by jidanni** [comment]
(Related: #4218.)

**Comment by jidanni** [comment]
> The location panel does exactly this, but with your mouse pointer instead of a crosshairs.

OK, today I tried it.
It took a very steady wrist, and several minutes of aiming.
And I was in luck, as I was able to find an exact X,
but for Y I had to settle either for a value either too high or too low!

So in fact often must be the case where one cannot indeed place a point at an exact coordinate with iD in its current state. Due to pixel size issues, often the exact X or Y one is trying to input is not available.

Let's go back and see (with a steady wrist) how precise we can get here
at zoom level 21. We observe increments

24.1317882,
24.1317888,

```
$ units $(perl -we 'printf "%f\n", 60 * (24.1317888 - 24.1317882);')nmiles cm
        * 6.6672
        / 0.149988
```
So we are forced to place our point upon a lattice of 6.7cm spaced dots.
The + on our survey marker's metal surface thus is forced to be up to
3cm off target!

**Comment by jidanni** [comment]
So we observe that any pixel-based solution, including crosshairs, is inadequate in the case where the user simply wants to get a pair of coordinates directly into the database intact.

I propose a simple dialog box, that upon right-clicking on a point, would open up and ask the user what are the coordinates he now wants to move this point to.

**Comment by jidanni** [comment]
This crosshair brings much confidence to the website:
https://skyvector.com/?ll=46,-85&chart=304&zoom=1
![20230419T083712](https://user-images.githubusercontent.com/1230959/232936363-eaf45a27-9156-4e73-b14c-5deb9f1c949f.jpg)
