### ISSUE TITLE
CSS "nowrap" for help dialogue

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6174]
When you view the help dialogue in German, the keyboard shortcuts have linebreaks. This makes the view less nice a harder to read and understand.

Testcase: https://www.openstreetmap.org/edit?locale=de

_Possible fix:_ Add `white-space: nowrap;` to the <td> `.modal-shortcuts .shortcut-keys`.

See screenshot before / after.

<img width="903" alt="with line breaks" src="https://user-images.githubusercontent.com/111561/56022211-7c1fe800-5d0b-11e9-9cb0-6b8b005b51bc.png">

<img width="902" alt="without line breaks and css fix" src="https://user-images.githubusercontent.com/111561/56022210-7b875180-5d0b-11e9-8b60-0e39ef5d60d7.png">

**Comment by manfredbrandl** [comment]
@tordans I shortend the explanations: "Festhalten verhindert Vereinigen beim Platzieren", "Trenne den Knoten von seinen Linien/Flächen", "Ecken eines Weges/einer Fläche rechtwinklig machen". Looks good:
![image](https://user-images.githubusercontent.com/5360273/56049276-64675480-5d49-11e9-8096-7ea41081659e.png)

**Comment by bhousel** [comment]
Thanks @manfredbrandl  that looks much better  👍 
I do agree with @tordans that we should `nowrap` the shortcut keys.

**Comment by quincylvania** [comment]
Done in 0c29054c36beda245bf77d672337eb7128bbec42. I also made this UI responsive so the two columns wrap to one on smaller displays.
