### ISSUE TITLE
Should we support `highway=elevator` as an area?

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#6175]
Some people are doing this.. What do you think @quincylvania ?
I'm tending to think "no" - or it should require a `area=yes` tag. 

https://wiki.openstreetmap.org/wiki/Tag:highway%3Delevator

<img width="879" alt="Screenshot 2019-04-12 13 41 30" src="https://user-images.githubusercontent.com/38784/56055913-c2d00b00-5d28-11e9-880b-f6484c66d408.png">
<img width="368" alt="Screenshot 2019-04-12 13 45 14" src="https://user-images.githubusercontent.com/38784/56056100-3d008f80-5d29-11e9-9414-add613c7e588.png">

**Comment by quincylvania** [comment]
Hmm I'm tending to think no at this point. Elevators are most important for accessible pedestrian routing tools, which are unlikely to handle areas well. While we could theoretically tag both vertices and areas (kind of like crossings as vertices and lines), I don't see an advantage to introducing this complexity.

In v3, iD should be able to tell users how to map things like elevators when they go to add them.

**Comment by bhousel** [comment]
Cool sounds good @quincylvania  👍

**Comment by TheAdventurer64** [comment]
One thing to note about this issue is that the wiki states that [you can map an elevator as a regular area](https://wiki.openstreetmap.org/wiki/Tag:highway%3Delevator). Thoughts on this?

**Comment by 1ec5** [comment]
Since 2019, [the wiki has been edited](https://wiki.openstreetmap.org/wiki/Special:Diff/2068703/2068705) to make the case that elevators are mapped as areas for indoor tagging. I’d suggest opening a new issue in id-tagging-schema to revisit the decision.
