### ISSUE TITLE
tunnel=covered suggested by user interface

### ISSUE THREAD

**Issue by alphensebezorger** [openstreetmap/iD#6181]
I noticed several highways on openstreetmap which were tagged `tunnel=covered`. As far as I could find his tag is not documented anywhere. I think this tagging is a mistake, `tunnel=yes` and `covered=yes` are documented of course.
To my surprise, when I changed a random unclassified road into a tunnel in iD, one of the types suggested was `covered`.
I can't find the preset where this value is stored, but I believe iD should not suggest this undocumented tagging.

iD 2.14.3, Firefox Quantum 64.0 (32-bit), Linux Mint 19.1

**Comment by bhousel** [comment]
For the `tunnel=*` field, iD suggests whatever common values are found in the OSM data, and we fetch this list from taginfo.
https://taginfo.openstreetmap.org/keys/tunnel#values
