### ISSUE TITLE
Many validator false positives on "Municipal" in airport names

### ISSUE THREAD

**Issue by Carnildo** [openstreetmap/iD#6182]
"[Name of town] Municipal Airport" is possibly the most common pattern for airport names in the United States (for example, 5% of the registered airports in Washington use it).  Flagging it as a generic name and offering to remove it risks having people "fix" the warnings by removing perfectly correct names.

**Comment by bhousel** [comment]
This is #5930.. We already removed `municipal` from the list in name-suggestion-index, so next version of iD won't warn about it.
