### ISSUE TITLE
Add control to set the locale

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6191]
Now that iD accepts a URL parameter to set the locale, there could be times where a user follows a link to iD set in an unfamiliar locale. Most users wouldn't know how to remove the URL parameter and reload the page. We should add a control to make it easier to change this value. We could force iD to reload after a change in order to avoid showing stale strings.

Giving users control over the locale at all has been debated, but I see the following advantages:

- We can make it quicker and more reliable to switch locales directly in iD than in the user's OSM account, browser, or device preferences.
- iD may be used in unexpected environments where an external locale is not passed in.
- This could be a basis for advanced behavior, like setting a preferred fallback locale other than English.

**Comment by tordans** [comment]
I wonder where such a UI would be located – there are no user settings in iD, yet.

For the usecase you describe – an external URL with an undesired locale – the UI would need to be very prominent / easy to find to solve the issue.

Another complexity is, that iD on osm.org is integrated in the information architecture and settings of the site. Which would be the first place to look for such a control/link.

I wonder …
- … are there (relevant) iD integrations outside of osm.org; so would the solution need to be great for stand alone + osm.org-IA; or even other site-contexts as well; or only for a standalone-iD-setup?
- … is this really an issue? Until now, the locale-param is super hidden (only those who know the API-doc know about it); are you aware of integrations that use it extensively? IMO it's just a debugging/advanced user feature ATM.

**Comment by bhousel** [comment]
this is also #3120
