### ISSUE TITLE
Validator: "Building crosses" but "building:min_level=1"

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6192]
I see this on http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&id=w553278769&locale=en&map=19.00/52.47903/13.45192

This is what it looks like in RL https://www.mapillary.com/app/?pKey=ujm1Rwmvxx0bnD9DtnbPVw&focus=photo&lat=52.47894457514562&lng=13.451897309587071&z=17.

> Building crosses Thiemannstraße - Tor 4
Use a bridge or tunnel
Reposition the features

The building is `building:min_level=1` which basically makes it "fly" above a street. https://wiki.openstreetmap.org/wiki/Key:building:min_level

IMO the message is not ideal ATM.

Some thoughts to improve it:

If the part covering the street is not very big (like in my example), the validator could just ignore the place IMO; at least for now.

The suggested "tunnel" and "bridge" are IMO both wrong whenever the validated object is a `building=* + building:min_level=*`.  At least that is, how I read most of https://wiki.openstreetmap.org/wiki/Key:covered. There is one part that gives me pause and suggests that "tunnel=building_passage" is a better fit, even in this situation (my example is not open to one side).
> For example, when a building has a way passing through it, the building and the way through it can not be assigned distinct layers. In this situation tunnel=building_passage is used when the way has outer building walls to all sides. The tag covered=* is used when the way is open at least at one side.

So depending on how we read the wiki, it should suggest `covered=yes` or `tunnel=building_passage` – or maybe both, with explanation to which should be used.

> Building crosses Thiemannstraße - Tor 4
Make the road a passage if it is narrowly enclosed by the building
Mark the road as covered if it is wide or open to one side
Reposition the features

(Or something like this.)

This tickets is very similar to https://github.com/openstreetmap/iD/issues/5891. Maybe the one-click-split action could at be available if the geometry is simple enough (like in my example above)?

**Comment by BjornRasmussen** [comment]
Using covered=yes on the highway under the building will get rid of the warning

**Comment by matkoniecz** [comment]
> This is what it looks like in RL mapillary.com/app/?pKey=ujm1Rwmvxx0bnD9DtnbPVw&focus=photo&lat=52.47894457514562&lng=13.451897309587071&z=17.

Can you attach also an image? Mapillary is completely broken for me (I reported the bug useing their requested method, but from what I see at https://forum.mapillary.com/ it seems that fix is unlikely).

**Comment by bhousel** [comment]
> Can you attach also an image?

looks like this:

<img width="793" alt="Screenshot 2019-05-02 09 44 11" src="https://user-images.githubusercontent.com/38784/57079693-e13d7c80-6cbe-11e9-90b9-aab43fa8d268.png">

Yes I would probably stick a `covered=yes` on there to eliminate the road-crosses-building warning.

**Comment by matkoniecz** [comment]
Thanks!

Right, `tunnel_building=passage` makes no sense here.

Even `covered=yes` is a bit too much (I would expect that `layer=1` + `building:min_level=2` (as two levels are skipped) on building would satisfy validator)

**Comment by bhousel** [comment]
> Even `covered=yes` is a bit too much (I would add `layer=1` + `building:min_level=2` (as two levels are skipped) on building and expect that it would satisfy validator)

Well I guess we disagree on that too.

**Comment by BjornRasmussen** [comment]
What exactly does covered mean? Covered from rain, or "something is above this feature"

**Comment by quincylvania** [comment]
@tordans Unfortunately I don't think we can expect every data consumer to interpret `building:min_level`, so I do think the crossing building/highway warning is valid here. We want mappers to provide additional info on the layering, such as adding `covered=yes`.

We still might need a way to make these easier to fix, but I think that's the idea behind #5924 so I'm going to close this as a duplicate.

> What exactly does covered mean? Covered from rain, or "something is above this feature"

@BjornRasmussen I usually consider `covered=yes` to mean that another mappable object is obscuring the feature on a higher layer, but it's not enclosed enough to be a tunnel.
