### ISSUE TITLE
Firefox is blocked from using latest master

### ISSUE THREAD

**Issue by shiftee** [openstreetmap/iD#6193]
Using Firefox 66.0.3 on Ubuntu 16.04 I get the following message:

> Sorry, your browser is not currently supported. Please use Potlatch 2 to edit the map.

The issue occurs when using:
http://preview.ideditor.com/master

The issue does not occur when using:
http://preview.ideditor.com/release/

**Comment by matkoniecz** [comment]
The same happens for me with 66.0.2 (64-bit), also on Ubuntu 16.04.

**Comment by sun-geo** [comment]
I think it's not a specific brower issue, same happens here using Chrome/Chromium on win7...

**Comment by BjornRasmussen** [comment]
Same here, on latest Chromium on Ubuntu

**Comment by quincylvania** [comment]
Yep, this was my fault in 2967d2d020da37848d47e8fdc26031a23d63671d due to editing the build script in such a way that it worked locally. Thanks for reporting.
