### ISSUE TITLE
Expandable / retractable top bar

### ISSUE THREAD

**Issue by puch4cz0wsky** [openstreetmap/iD#6197]
![openstreetmap top bar](https://user-images.githubusercontent.com/49727395/56305923-8f82e700-6141-11e9-955d-c5056dad08c1.png)

My suggestion concerns the possibility of retractabling the top bar because because it covers a lot of space on small monitors.

**Comment by bhousel** [comment]
<img width="474" alt="Screenshot 2019-04-17 14 26 00" src="https://user-images.githubusercontent.com/38784/56311836-e4f8cd00-611c-11e9-807a-6f44f1f39bf6.png">

Using Full Screen Mode will remove the top bar 👍

**Comment by quincylvania** [comment]
@bhousel 🤯 I had no idea about this feature!

**Comment by bhousel** [comment]
> 🤯 I had no idea about this feature!

haha yeah - It's actually a browser feature.

But apps like iD can ask the browser for permission to use it, and doing lets us fullscreen just the iD container without the openstreetmap iframe.  check out [ui/full_screen.js](https://github.com/openstreetmap/iD/blob/master/modules/ui/full_screen.js)

<img width="473" alt="Screenshot 2019-04-17 14 30 22" src="https://user-images.githubusercontent.com/38784/56312067-63556f00-611d-11e9-89c1-6907668dfb41.png">
