### ISSUE TITLE
Add the IBGE Street Names layer

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#6199]
There's a [new layer with street names available for Brazil](https://www.openstreetmap.org/user/naoliv/diary/47882), it would be nice to have it available with the other 2 IBGE layers.

**Comment by quincylvania** [comment]
Sounds good! iD gets the layers from the [editor-layer-index](https://github.com/osmlab/editor-layer-index) so you'll need to open the issue over there instead.
