### ISSUE TITLE
Add Wikidata tags to POIs with brand names

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#6200]
There are lots of amenity/shop POIs with records on Wikidata.  It would be nice to have the automatically tagged when inserted/edited, as is already done with other elements.
There's a [list of the existing Wikidata entries](http://osmlab.github.io/name-suggestion-index/brands/index.html) for these elements.

**Comment by quincylvania** [comment]
The name-suggestion-index project came out of iD and is primarily used here 😂

When adding a new POI, you can search for a specific brand and it will add the Wikidata tag if available. See #6122 for recommending the tags to the user after they set the name manually.

Note that the version of iD on openstreetmap.org doesn't yet include the extensive updates made to the brand index in the past few weeks.
