### ISSUE TITLE
Add link to another object history viewer ('pewu' / 'mapki')

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6202]
Adding another link to a history object viewer: "pewu"
pewu's main page looks like this: https://pewu.github.io/osm-history/
example node-object:   https://pewu.github.io/osm-history/#/node/153388690
example way-object:   https://pewu.github.io/osm-history/#/way/59407145
example relation-object:   https://pewu.github.io/osm-history/#/relation/3170598

When hitting Ctrl+Shift+H this [1] window will appear. In the bottom line there is already a link to the osm-object-history, please add (my favorite viewer) "pewu" somewhere (wherever it suits) to this history window. A proposal would look like window [2] (add pewu to bottom line), or [3] (add lines above), or [4] add above with even potential space for adding more other viewers, e.g. MAPKI: http://osm.mapki.com/history/).

What do you think about changing to this behavior?

[1] (current view)
![id-history-window](https://user-images.githubusercontent.com/47290585/56384620-2a9cbf00-621d-11e9-9415-da7a0e60dfc1.png)

[2] P1 add pewu at bottom line
![id-history-window-proposal1 2unten](https://user-images.githubusercontent.com/47290585/56386511-448cd080-6222-11e9-9d16-ddd47175c70b.png)

[3] P2 add two lines above
![id-history-window-proposal2 2oben](https://user-images.githubusercontent.com/47290585/56386669-bd8c2800-6222-11e9-8d97-6b1be1788962.png)

[4] P3 add above, even with potential space for more items, like Mapki
![id-history-window-proposal3 3oben](https://user-images.githubusercontent.com/47290585/56386684-c54bcc80-6222-11e9-8b1c-628fc821856b.png)

btw, this is a bit similar to issue #3761

**Comment by bhousel** [comment]
Wow pewu looks very nice.. Yes, I think it would be great to add more links to other tools here.  👍

**Comment by sun-geo** [comment]
Yes, I love pewu, especially for the graphical presentation per version of osm-ways.
Another potential option could be to add achavi (graphical presentation of changeset - https://overpass-api.de/achavi/) next to OSMCha...

**Comment by quincylvania** [comment]
@sun-geo Thanks for the suggestion and for the mockups! They made this quick to implement. This'll be a great addition for advanced mappers. Cc: @PeWu

I skipped the mapki viewer for now since I think the OSM and PeWu viewers cover all of its functionality pretty well.

![pewu link demo](https://user-images.githubusercontent.com/2046746/56391501-b4c83180-61e3-11e9-896f-7315ccca581e.gif)

**Comment by PeWu** [comment]
Thank you for integrating :smiley:

**Comment by sun-geo** [comment]
quincylvania: "I skipped the mapki viewer for now since I think the OSM and PeWu viewers cover all of its functionality pretty well."

That's fine, I use mapki from time to time only for relations...
