### ISSUE TITLE
Add "Extract" operation for building POIs

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6203]
POIs often exist as buildings, but points are typically preferable. It's currently cumbersome to create a new point and copy over the tags manually. I suggest we add an "Extract" operation for POIs tagged as building areas that:

- Creates a new point with the POI tags (e.g. `amenity`, `phone`)
- Enters the move mode so the user can immediately place the point
- Leaves the building tags (e.g. `building:levels`, `height`) on the building

This is similar to the new Downgrade operation (#6103), which just removes the non-building tags.

For iD v3, we should consider disallowing the addition of some POIs as buildings altogether.

**Comment by bhousel** [comment]
> For iD v3, we should consider disallowing the addition of some POIs as buildings altogether.

_I agree_ that it would be better for everyone if iD were bit more opinionated about which geometries can be used for which features.  However, we need to let OSM be OSM.  

So, I think maybe a better-stated goal of iD v3 should be to make it a generally great map editor, and compartmentalize all the messy OSM stuff into modules so that non-OSM projects that want to use iD as an editor aren't stuck with OSM's baggage ("what even is an area?").

**Comment by 1ec5** [comment]
Perhaps unsurprisingly, I’m in the POIs-are-OK-as-buildings camp. But even so, sometimes I do encounter situations where it becomes necessary to move tags from the building to a standalone POI. Instead of a dedicated operation for what’s presumably a relatively rare task, it would be nice to support this workflow more generally via tag copy-pasting (#839).

**Comment by quincylvania** [comment]
To be clear, I'm fine generally with POIs-as-buildings in OSM (though I don't prefer them). I'm imagining a new user searching "Starbucks" or something in the v3 ribbon and needing to pick between a point and a building. We could reduce complexity by just having the one option. I suppose a counter-argument is that more buildings might get drawn by having both options. I suppose it's not a major issue either way.

> So, I think maybe a better-stated goal of iD v3 should be to make it a generally great map editor, and compartmentalize all the messy OSM stuff into modules so that non-OSM projects that want to use iD as an editor aren't stuck with OSM's baggage ("what even is an area?").

@bhousel Sounds great!

> Instead of a dedicated operation for what’s presumably a relatively rare task, it would be nice to support this workflow more generally via tag copy-pasting (#839).

@1ec5 The advantages I see with the dedicated operation is that iD can suss out what tags belong on what feature and reduce several steps to one. With copying tags, the user needs to manually pick which tags to include or remove. The operation would be hidden in the right-click menu and only appear when needed, so I think the dedicated option is worth it.

**Comment by tordans** [comment]
For the feature / usecase / idea in general: It would be nice and I would use it. I had situations where I wished something like this existed. But the pain is not very big for me; personally other feature sound more useful.

> I'm imagining a new user searching "Starbucks" or something in the v3 ribbon and needing to pick between a point and a building. We could reduce complexity by just having the one option.

For this case, IMO being opinionated is very OK. Especially as long as there is a secondary way to edit the tagging for those who really want the building to be the amenity.

**Comment by 1ec5** [comment]
>> I'm imagining a new user searching "Starbucks" or something in the v3 ribbon and needing to pick between a point and a building. We could reduce complexity by just having the one option.
> 
> For this case, IMO being opinionated is very OK. Especially as long as there is a secondary way to edit the tagging for those who really want the building to be the amenity.

Ah, I hadn’t considered the ribbon. If we decide to present the user with just the POI option, then they can merge the POI with a building afterwards. On the other hand, if we decide to present just the building option, then it becomes more difficult to convert it into a POI. Either way, it’s still possible to do things the old way, by drawing the feature with the generic point or area preset before tagging it.

I don’t think it’s quite as simple as being opinionated about points or areas, though. Thinking back to the times I’ve wanted to perform an Extract operation, I’ve often found new mappers wanting to map a business with more detail than a point. They draw the various storefronts in a strip mall as individual connecting buildings, sometimes within a redundant building. Probably they want to emphasize that the strip mall’s anchor store takes up a lot more space than the barber shop next door. Relatedly, I see people inadvertently drawing a building area around the entire property of a gas station or car dealership. These outcomes could be viewed as a downside of exposing the POI-as-building presets, but I see it as a signal that we need to make it easier to draw areas that are tagged as POIs but not buildings.

**Comment by quincylvania** [comment]
@1ec5 Those are some interesting insights about how people map POIs, thanks. It seems like this is a struggle between simplicity for beginners and high-level detail for power-mappers.

One optimization I made for the ribbon UI is to use the the label "Building" instead of "Area" when a feature will be added as a building. With #6131, #6119, and #6079, we'll give users much more guidance as to how to map things like POIs, so maybe having both options is okay. If there was a way for users to tell iD they want more control, then we could theoretically show advanced users "Area" and "Indoor Room" options as well.

<img width="396" alt="Screen Shot 2019-03-07 at 1 17 39 PM" src="https://user-images.githubusercontent.com/2046746/56512733-1a1e6a00-64e5-11e9-8948-b20203471ee8.png">

In any case, the Extract operation will make working with POIs somewhat easier.

**Comment by quincylvania** [comment]
As per discussion with @bhousel, I renamed the Detach operation Extract (shortcut E) and extended it to work on areas. This makes for a great complement to the Merge operation.

![extract demo](https://user-images.githubusercontent.com/2046746/56534035-b78d9400-650d-11e9-9501-933a30411886.gif)

The operation moves all the tags except for those that should remain on the area, such as building tags. Address and source tags are kept on both features (though ideally they should be manually adjusted afterward). For non-buildings, this operation leaves an untagged area. I think this okay since the geometry may still be useful and validation system flags it anyway.
