### ISSUE TITLE
Validator: Warning on power=line and location=underground

### ISSUE THREAD

**Issue by famo** [openstreetmap/iD#6206]
Judging from https://github.com/gravitystorm/openstreetmap-carto/issues/3746 I think it would be useful to display a warning for tags with `power=line; location=underground`
Quote from the wiki https://wiki.openstreetmap.org/wiki/Tag:power=line?uselang=en-US:
> A power=line is carried on power=towers, but may be supported by poles, especially on lines in the subtransmission grid, that connects the main grids with the distribution grid. ...

and
> Use power=cable with location=underground for underground or underwater power cables. ...

**Comment by tordans** [comment]
It looks like, this does not happen often (it seems it does not even make the taginfo threshold). But the way I understood quincylvania in Slack is, that the count of errors is not the driving force to add is as validation. So this is just FYI.

<img width="990" alt="Bildschirmfoto 2019-04-20 um 00 21 43" src="https://user-images.githubusercontent.com/111561/56446310-4d54d380-6302-11e9-912b-1d9743b477af.png">

https://taginfo.openstreetmap.org/tags/location=underground#combinations

**Comment by BjornRasmussen** [comment]
There are only 164 instances of this error: https://overpass-turbo.eu/s/I7f
The impact is very low, so I don't think we should slow down iD any more without very good reason to.

**Comment by famo** [comment]
I agree and rest this case / issue :-)

**Comment by quincylvania** [comment]
@famo Interesting idea! I don't think we'd want a dedicated top-level validation rule for this, but I'm thinking more that we should have a validation rule that consumes a JSON file defining incompatible tag combinations. This could be one of those.

@BjornRasmussen said:

> The impact is very low, so I don't think we should slow down iD any more without very good reason to.

The work that @bhousel is doing in #6140 will make iD's validation considerably more performant, so this isn't a long-term concern! I'll admit that bottlenecks up until now have prevented us from adding more costly geometry validations like #5869 😕

**Comment by bhousel** [comment]
Yes - I think we can add a rule for this one to `deprecated.json` and it shouldn't affect the performance at all..

**Comment by BjornRasmussen** [comment]
Nice!  I would love more validation in iD, but really don't want it to become super slow.

**Comment by flacombe** [comment]
Hi

Wiki Data Items could solve this problem with P44 property : incompatible with.
https://wiki.openstreetmap.org/wiki/Data_items

power=line and location=underground is a compatibility matter and doesn't deal with deprecation, it never has been encouraged.
I've created location=underground page which will enable corresponding data item to make power=line incompatible with it shortly.

**Comment by bhousel** [comment]
> @bhousel is this possible to avoid a deprecated.json file and directly take validation rules with wiki data items?

Sorry, but I'm really not interested in adding anything wiki as a critical dependency on how iD works.

**Comment by flacombe** [comment]
Nevertheless the issue here doesn't regard deprecation but incompatibility. This doesn't make any deprecated.json legit

**Comment by quincylvania** [comment]
@flacombe You're right that this isn't strictly deprecation, but it doesn't make much difference from the user's perspective. Despite its name, deprecated.json contains many fringe tags that were never widespread and thus never "deprecated". The overall idea is to help users apply standard tagging to existing features.

**Comment by flacombe** [comment]
Thanks @quincylvania 

Then I don't get why iD should get a different list than JOSM or any other editor (assumed according @bhousel comment).
Maintaining such common things on different platforms is time consuming and error prone.

**Comment by quincylvania** [comment]
> Then I don't get why iD should get a different list than JOSM or any other editor

@flacombe We maintain tagging data that we thinks best suits the needs of iD. This is the same logic as iD having its own presets, which it has for years now. Other projects are free to use our data if they want.
