### ISSUE TITLE
Better placeholder for opening hours

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#6207]
Opening hours is a weird field.  The values are really inscrutable, which results in this placeholder that doesn't show a user what they should do.  Maybe we should instead have it say "Choose a value..." or  "Unknown" or something.

<img width="364" alt="Screenshot 2019-04-19 13 00 18" src="https://user-images.githubusercontent.com/38784/56434569-20bd9f00-62a3-11e9-9494-651c58612aad.png">

Compare to other fields which look a lot more "placeholdery"
<img width="366" alt="Screenshot 2019-04-19 13 02 25" src="https://user-images.githubusercontent.com/38784/56434635-6712fe00-62a3-11e9-804e-031791f9e8bd.png">

**Comment by iandees** [comment]
See also #974 😬

**Comment by tordans** [comment]
> Maybe we should instead have it say "Choose a value..." or "Unknown" or something.

How about "Read the wiki" (to learn the syntax). Which is honestly what one has to do ATM. But in earnest: This is IMO one of those cases where users cannot figure out by themselves what to do, so IMO iD should at least tell them where to learn more. Which in this case is, to click the info-(i) to go to the wiki. So maybe the field should show the wiki-link all the time?

The placeholder could emphasize this with something like "Opening houser in OSM syntax".

**Comment by bhousel** [comment]
> How about "Read the wiki" (to learn the syntax)

Lol no

**Comment by tordans** [comment]
> > How about "Read the wiki" (to learn the syntax)
> 
> Lol no

There is always https://github.com/openstreetmap/iD/issues/974 … :-)

**Comment by bhousel** [comment]
You all can stop linking back to the old issue.  We know about it.  This is just about improving the placeholder to make it look like a placeholder.
