### ISSUE TITLE
Include contextual info in the page title when changing URL parameters

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6209]
Changing the URL can add entries to the browser's page history. This would be significantly more useful if we could change the title to include the selected feature and/or map location. I'm not sure if this could work on osm.org but I think it's worth it for ideditor.com and localhost alone.

<img width="305" alt="Screen Shot 2019-04-20 at 4 21 02 PM" src="https://user-images.githubusercontent.com/2046746/56463588-2347f380-638c-11e9-91a8-b06f0ef8bb5a.png">

**Comment by bhousel** [comment]
We could do number of changes (the code that updates the save button count could do it)

```js
document.title = "iD (60)"
```

<img width="250" alt="Screenshot 2019-04-23 02 16 17" src="https://user-images.githubusercontent.com/38784/56558771-c3a93e00-656d-11e9-8c09-860265ed6f9f.png">

**Comment by CarycaKatarzyna** [comment]
I want to solve it. How exactly should title looks? Only 'iD' with number of changes as @bhousel proposed? Or for example with name of selected item like in Google Maps?

**Comment by quincylvania** [comment]
@CarycaKatarzyna I saw you started a branch for this, thanks!

I like the idea of showing the change count in the current title like in Bryan's mockup. This would remind people they have pending edits if they tab away from iD.

However, the titles in the browser history should not include the change count since selecting those links does not revert edits. Instead I think they should be linked to the selection/navigation states, which is #6783.

I'm pretty sure your branch works pretty much like this already 👍

**Comment by quincylvania** [comment]
I ended up removing the map location part since it was distracting and not particularly useful to most users. Perhaps we could include the local area name instead, e.g. "Tuba City, AZ".

> We could do number of changes

I added this too. I couldn't yet figure out how to show it in the current title but not in the history item title, but it's not a big problem.
