### ISSUE TITLE
LINZ imagery layer returning 403 

### ISSUE THREAD

**Issue by nigelramsay** [openstreetmap/iD#6210]
It appears that the API key embedded in the WMTS URLs has expired, or been de-authorised. It's not obvious who the API key is associated with. This results in the background layer not rendering. 

Hopefully someone from LINZ (Land Information New Zealand) or Koordinates can help provide a new key. This is the file that needs to be updated

https://github.com/openstreetmap/iD/blob/master/data/imagery.json

@edcorkery @palmerj @rcoup

**Comment by palmerj** [comment]
The key was allocated by @andrewharvey. Might want to check with him to ensure he didn't deactivate it. The other possibility, but not likely due to a 403 error, is some rate limit has been hit

**Comment by nigelramsay** [comment]
Looks like this is a known issue that is yet to be resolved. Looks like Koordinates may be in a position to help. 

https://github.com/osmlab/editor-layer-index/issues/602

**Comment by bhousel** [comment]
Closing here, as it is being tracked in the editor-layer-index project..

**Comment by andrewharvey** [comment]
Yep, known issue being tracked at https://github.com/osmlab/editor-layer-index/issues/602.
