### ISSUE TITLE
Add a way to tag bridge and tunnel names

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#6212]
There's a way to tag the name of a bridge, which is usually different from the name of the road passing over it. The matching tag is `bridge:name`, while the road stays with the usual name tag. You can also add foreign names using the language suffix scheme like `bridge:name:ja`. The same concept exists for tunnels as well: `tunnel:name`.

**Comment by bhousel** [comment]
You can do this by making the bridge its own object with its own name:

<img width="1008" alt="Screenshot 2019-04-22 11 36 22" src="https://user-images.githubusercontent.com/38784/56508658-dc284280-64f2-11e9-8fc9-7fce9c82edee.png">

**Comment by quincylvania** [comment]
@bhousel What do you think of supporting [`man_made=tunnel`](https://wiki.openstreetmap.org/wiki/Proposed_features/man_made%3Dtunnel) for the same usage on tunnels?

**Comment by bhousel** [comment]
> @bhousel What do you think of supporting [`man_made=tunnel`](https://wiki.openstreetmap.org/wiki/Proposed_features/man_made%3Dtunnel) for the same usage on tunnels?

yes definitely 👍   I thought we had it already..
