### ISSUE TITLE
A ford crossing a stream does an error in Id

### ISSUE THREAD

**Issue by Rpnpif** [openstreetmap/iD#6213]
Tagging a ford on a highway crossing a stream is refused by Id. It says that a bridge or a tunnel was required.

But a single ford should be accepted without error as a bridge or tunnel to cross a stream.
So I think that Id is wrong on this.

Fortunately, I can force id to accept this single ford but I think it is a bug. 

Regards.

**Comment by jguthrie100** [comment]
Where abouts is it? Id validates against ford crossings on main roads, which makes sense.

**Comment by quincylvania** [comment]
A ford is fine as long as you connect the road to the stream. Is iD not suggesting the connection fix? A screenshot might be helpful here.

**Comment by Rpnpif** [comment]
@quincylvania You are right! I am sorry that I had a bad reading and understanding of the "connect the features" suggestion.
I would suggest the sentence "Connect the two ways" or something as this.

Thank you.

**Comment by quincylvania** [comment]
@Rpnpif I'm glad it worked out! I think "connect the features" is okay, we introduce users to the concept of "features" in the tutorial but don't introduce "ways". Maybe we can reconsider it if others are confused as well.

**Comment by tastrax** [comment]
Here is an example where the ford exists but the validation still shows an error - lots of them in Timor Leste

https://www.openstreetmap.org/edit?editor=id#map=18/-8.22725/125.60061
