### ISSUE TITLE
Flag unsquare buildings

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6215]
If new users skip the tutorial, then they may not know how to square buildings (this was me when I first started mapping 😆). At its worst, this lack of knowledge can result in hundreds of unsquare buildings from mappers with good intentions.

<img width="908" alt="Screenshot 2019-04-19 13 21 01" src="https://user-images.githubusercontent.com/2046746/56538992-77341300-6519-11e9-90ee-ec1bcea91ec8.png">

As a hint, we should warn users when their buildings aren't square and include a quick fix to instantly run the orthogonalize operation. We [already have code](https://github.com/openstreetmap/iD/blob/e8c5c05b290dda6e57f8b3ede17dd03986ea2044/modules/ui/intro/helper.js#L113-L134) to check if a path is mostly square or not.

This has been proposed before (#3130, #3673, #2624), but to avoid historical baggage I'm creating a new, singular issue to target a warning in iD's modern validation system. We can now do things that weren't possible before or may not have made sense at the time.

**Comment by bhousel** [comment]
Awesome, we have wanted this for a while 👍

**Comment by tordans** [comment]
That will be great. Even though hopefully the "create a squared building tool" of the new toolbar will make it not-needed in the future.

I wonder, would this create an "infinite squaring loop" like https://github.com/openstreetmap/iD/issues/6226?

**Comment by tordans** [comment]
> I wonder, would this create an "infinite squaring loop" like #6226?

I tested ([Map](http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&locale=en&map=20.00/52.47319/13.44719)) and can say: Yes, it does create the loop. My my test I was able to iterate long enough to make both buildings square, which of course removed the warning. I still wonder if the warning should only apply to non-connected buildings to work around this. In dense cities the will likely create a domino effect of warnings and slightly changed geometries.

**Comment by quincylvania** [comment]
@tordans Thanks for testing that. The validation isn't perfect yet and we're still thinking of ways to make it better. Ignoring connected buildings might work. We're also considering ignoring buildings with more than some maximum number of nodes (7-15 somewhere), since they're more likely to be intentionally drawn non-squared.

I'm fine with being conservative around flagging since the main point of the validation is to help new users (who skipped the tutorial) realize they should be squaring things, not to detect everything that could be squared. We can flag more things if eventually we get more accurate "unsquare" detection and stronger resolution tools like #6226.
