### ISSUE TITLE
Impossible Oneways - flag waterways, etc with improper direction

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#6216]
<img width="715" alt="Screenshot 2019-04-23 01 26 42" src="https://user-images.githubusercontent.com/38784/56556803-ed129b80-6566-11e9-89ab-dac570d79ed5.png">

I guess we could do this for other directional things too:
- oneway roads
- pistes / ski lifts

**Comment by Nakaner** [comment]
The cases shown above is only an error if it is located inside the area downloaded in the editor. This should be taken into account by the implementation of that validation rule.

**Comment by quincylvania** [comment]
@Nakaner Good point. @bhousel added checks to ignore ways with nodes on undownloaded tiles for #5938, so we can use that code.

**Comment by quincylvania** [comment]
I did this for highways and waterways. Pistes and aerialways seem more prone to edge cases and less common anyway so I held off on those for now.

<img width="868" alt="Screen Shot 2019-04-26 at 12 09 43 PM" src="https://user-images.githubusercontent.com/2046746/56830804-33dceb80-681c-11e9-9bfe-3809dd540315.png">
