### ISSUE TITLE
Straighten / align multiple points

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#6217]
I'd like to be able to just select a bunch of points and hit <kbd>S</kbd> to straighten all of them.

![straighten points](https://user-images.githubusercontent.com/38784/56557985-23521a00-656b-11e9-8b61-7536e8752d87.gif)

**Comment by bhousel** [comment]
I did this!  Now POIs can be _perfectly_ straight  📏👌
My OCD is happy now. 

![straighten points2](https://user-images.githubusercontent.com/38784/56636207-0df5f200-6636-11e9-8d30-547a5241f0c0.gif)

**Comment by quincylvania** [comment]
@bhousel Looks awesome! It's been great to make the same operations work for different kinds of selections lately. Like extract for areas, disconnect for ways, square for open ways and vertices, straighten for multiple connected lines.
