### ISSUE TITLE
Selected elements no longer forced visible

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#6220]
Forcing visibility of selected entities was implemented in 151e2685d4d75323427c8cdfa7104d264fc6bb36. It looks as if that behaviour has been broken by something.

Reproduction steps (on latest preview):

1. Head to `map=19.60/57.15158/-2.1`
2. Hide the buildings data layer.
3. Check issues panel set to validate everything in view and select the "line has no role" issue.
4. The building selected is still not visible.

**Comment by SilentSpike** [comment]
On further testing, it looks like the issue title is not accurate. This seems to be something specific to this building (likely multipolygons in general).

**Comment by quincylvania** [comment]
@SilentSpike Thanks for reporting this! I made it so all the members of a selected relation will remain visible.
