### ISSUE TITLE
Handle all relations with from, via, and to members in the same manner as turn restrictions.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6221]
There are quite a few different relation types that can currently be broken by id with the "split way" functionality.  These include:
1) Manoeuvre relations
2) turnlanes:turns
3) Connectivity relations - [Proposal page](https://wiki.openstreetmap.org/wiki/Proposed_features/Connectivity)
... and possibly others as well.
All relations with this format should be handled identically by the split way tool.  I suggest modifying the code to improve the relation (remove duplicate from/to way) if the relation has from, via, and to members.  
The current design, which I _think_ already has this capability for turn restrictions, should no longer look for the tag `type=restriction` and instead look for `has from, via and to members`.

**Comment by bhousel** [comment]
Seems reasonable  👍
