### ISSUE TITLE
Add  Papiamento to Transifex

### ISSUE THREAD

**Issue by milovanderlinden** [openstreetmap/iD#6222]
Hello,

We are training kids on Curacao to map with fieldpapers and the iD editor. We would like to provide them with the  Papiamento language.

Can you please add the  Papiamento language to transifex? Transifex supports it as visible here: https://www.transifex.com/explore/languages/ I think it just needs to be activated on the iD editor translation project.

**Comment by bhousel** [comment]
I've approved the request on transifex. Thanks!

**Comment by quincylvania** [comment]
You can translate here: https://www.transifex.com/openstreetmap/id-editor/translate/#pap

Note that translations are only pushed to openstreetmap.org with new releases of iD. We're planning a release in the next week or two. After that, there probably won't be a release for several months.
