### ISSUE TITLE
Issues with user's edits not flagged when out of view

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6223]
If the user checks "In View" in the Issues pane, they won't see issues with things they edit that have gone offscreen. I think we should always show the user's issues in the list.

**Comment by bhousel** [comment]
I'd really prefer for "in view" to literally mean "in view".  We still nag them about their issues when they try to save. 

Anyway I expect some users will not care about validation and just turn all the rules off.

**Comment by quincylvania** [comment]
> I'd really prefer for "in view" to literally mean "in view".

I agree, but we could structure it so it only applies to the Everything option. I'm imagining new users (and myself, really) not seeing the little dot indicator after panning away and then going to save and being surprised by all the unresolved issues.

Actually, I'm assuming that "In View" is the default but I'm not sure that's right. If My Edits / Everywhere is the default then I'm fine leaving it as is, since this is the existing behavior and users would know if they changed it.

**Comment by bhousel** [comment]
> If My Edits / Everywhere is the default then I'm fine leaving it as is, since this is the existing behavior and users would know if they changed it.

Yes - "My Edits / Everywhere" is the default.. The user would need to change it on purpose to something else.

**Comment by quincylvania** [comment]
> Yes - "My Edits / Everywhere" is the default.. The user would need to change it on purpose to something else.

Sounds good, let's leave it then. Thanks for letting me talk this through!
