### ISSUE TITLE
Improve "Everything looks fine" message when filters are on

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6224]
Since we're validating everything in the background anyway, we could change this message to be more descriptive when filters are on.

<img width="350" alt="Screen Shot 2019-04-23 at 9 53 02 AM" src="https://user-images.githubusercontent.com/2046746/56600938-bc565480-65ae-11e9-9683-c9f8ed0e30c6.png">

Something like:

**Your edits in view look fine**
17 issues detected elsewhere

**Comment by bhousel** [comment]
Oh yeah, I like this 👍 
It also encourages people to play with the buttons.

Our not-so-subtle goal is to get people who are interested in validation to get hooked on it and spend hours making the map better.

**Comment by BjornRasmussen** [comment]
> 17 issues detected elsewhere

Please no!  I don't think that iD should be using all that processing power in the background if the contributer hasn't activated the validation for all objects.

**Comment by quincylvania** [comment]
@BjornRasmussen Have you edited on master in the past few days? iD is already validating everything in the background, even when set to My Edits 😆

**Comment by quincylvania** [comment]
I did this along with #6242!

![ignore issues demo](https://user-images.githubusercontent.com/2046746/57055494-abfa4580-6c50-11e9-9b78-73325fbcf0d2.gif)
