### ISSUE TITLE
Filter for layer="<0" + level!=0

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6225]
I am missing a sidebar filter option to get rid of …
a. all objects that are under ground (layer="<0" I guess?)
Example: http://preview.ideditor.com/master/#background=Bing&disable_features=boundaries,past_future&id=w527564041&map=19.32/52.49946/13.39224

b. all indoor-mapping-objects
Example: https://www.openstreetmap.org/edit#map=19/52.47916/13.45396

Those might actually be better two filters:
- one for underground things
- one for building-related objects, which could also include indoor + building:part ?

I suggest splitting those two, since for underground, there is likely no relation with the ground floor (except for stairs and such I guess), but for the indoor+building:part there is a strong relation to the main buidling object, so they should be considered more closely.

**Comment by bhousel** [comment]
This is kind of the same as #2746

**Comment by famo** [comment]
Is there an update on this issue?
#2746 is a wall of text with prose - I really don't get it...

I suggest two additional filters:

1. Underground features: `location=underground` and `location=underwater`
2. Indoor features: `indoor=yes`

Should be simple, or?
