### ISSUE TITLE
Still problems with left and right within keys when reversing a way's direction

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#6235]
You might know the thing already: If reversing a way's direction, all "left" and "right" values are reversed to the opposite value. The same when "left" and "right" are part of a key. But at the moment in keys it only works when "left" or "right" is at the end, such as cycleway:left=track or something. But when "left" for example is _within_ the key, it's not changed to the opposite value when reversing the way-direction. So the problem occurs when there are keys like **cycleway:left:surface, parking:lane:right:parallel** etc.

**Comment by bhousel** [comment]
Ok we will try to fix this.  

Aside: It's amazing the amount of tagging gymnastics some people will go through just to avoid drawing another line for a thing.
