### ISSUE TITLE
 recommend migrating from barrier=embankment to man_made=embankment 

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6236]
`barrier=embankment` was mostly imported, current tagging is to use `man_made=embankment`

See ​https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dembankment

in this case usage numbers are quite powerful argument - ​https://wiki.openstreetmap.org/wiki/File:Embankment-man_made-vs-barrier.png

4k uses (https://taginfo.openstreetmap.org/tags/barrier=embankment) are enough to make sense to create validator warning

equivalent JOSM issue: https://josm.openstreetmap.de/ticket/17643#ticket

**Comment by sun-geo** [comment]
> `barrier=embankment` was mostly imported [...]

Do you have by chance the link/reference to the corresponding documentation of the main import?

**Comment by quincylvania** [comment]
Sounds okay. Barriers are confusing so it's always nice to find alternatives.

**Comment by matkoniecz** [comment]
> Do you have by chance the link/reference to the corresponding documentation of the main import?

No, though I was not looking for it.

**Comment by donalhunt** [comment]
Sorry for commenting on a closed issue but the consensus around `man_made=embankment` and `barrier=embankment` is not 100% clear.

The wiki page for `man_made=embankment` specifically calls out that it is primarily for roads and railways (i.e. it's a manmade construct for placing other things on top of). However there are specific use cases for `barrier=embankment` where a bank of earth exists purely as a barrier. In some cases, the barrier may be 2m high. In others it may just be 0.3m high (opposite of a firebreak furrow).

Can we get some clarity on this?

**Comment by lectrician1** [comment]
@donalhunt This point is specifically about tagging conventions, not iD. Please bring this up on the Wiki, tagging mailing list, or other communication channels.
