### ISSUE TITLE
Changing feature tags doesn't enable the save button

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#6239]
As discussed in slack.

Reproduction steps:

1. Visit any random feature ([example](http://preview.ideditor.com/master/#id=n2354912368&map=18.20/52.01401/-3.07932))
2. Change the fields arbitrarily (e.g. add a name)
3. Observe that the save button does not become active

**Comment by BjornRasmussen** [comment]
I have run into this issue (earlier today), but noticed that the button is just greyed out - not disabled.  This means that you can still save changes by clicking the save button, but it just looks wrong, since it is greyed out.

**Comment by sun-geo** [comment]
same here - saving seems working, but the save-button isn't highlighted...

**Comment by jguthrie100** [comment]
I'm not sure if its always been like this, but it seems that the Save count only goes up when something new is created. If you modify a way by dragging an existing node then the count stays the same, whereas if you drag it from one of the arrow markers (creating a new node), then the count goes up

**Comment by BjornRasmussen** [comment]
Moving nodes in a way increases the count by 1 unless nodes have already been moved in that same way.
