### ISSUE TITLE
ImproveOSM layer certificate invalid

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6240]
When I turn on the ImproveOSM layer nothing shows up and I get these types of errors in the Safari console:

> Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “turnrestrictionservice.skobbler.net” which could put your confidential information at risk.

This happens for iD on localhost, preview, and osm.org. I'm not sure there's anything we can do about it.

**Comment by SilentSpike** [comment]
Can confirm I see this too. Trying to visit one of the servers in chrome gives:

> This server could not prove that it is turnrestrictionservice.skobbler.net; its security certificate expired 25 days ago.

@beataj-telenav may be able to investigate this on their end

**Comment by beataj-telenav** [comment]
We have solved the issue, thanks for signaling the issue. Please tag me for future issues related to ImproveOSM.

**Comment by SilentSpike** [comment]
Thank you, can confirm the data layer is now working again for me

**Comment by quincylvania** [comment]
Hmm the layers still isn't working for me, checking on osm.org.

**Comment by quincylvania** [comment]
Oh it looks like only the turn restrictions server has an invalid certificate now. The other issue types are displaying. @beataj-telenav 

> Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “turnrestrictionservice.skobbler.net” which could put your confidential information at risk.
https://turnrestrictionservice.skobbler.net/turnRestrictionService/search?client=iD&confidenceLevel=C1&east=-103.3154296875&north=20.50935458871459&south=20.529933125170764&status=OPEN&west=-103.29345703125&zoom=19

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue, I will let you know when the issue is fixed.

**Comment by beataj-telenav** [comment]
We have fixed the issue.

**Comment by quincylvania** [comment]
@beataj-telenav Awesome, thanks!
