### ISSUE TITLE
Flag duplicate or extremely close adjacent nodes in a way

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6241]
It's generally undesirable to have adjacent nodes in a way that are actually or nearly in the same place, but it can be difficult to find such instances visually. iD should flag these and offer to merge the points.

<img width="404" alt="Screen Shot 2019-04-24 at 5 10 01 PM" src="https://user-images.githubusercontent.com/2046746/56701458-2147a280-66b4-11e9-924b-310b1d025e57.png">

**Comment by bhousel** [comment]
Haha strong agree.. these drive me nuts.

**Comment by BjornRasmussen** [comment]
Same here

**Comment by SilentSpike** [comment]
Semi-related to this, what about offering to simplify straight lines with multiple untagged/connected nodes along their length?

**Comment by bhousel** [comment]
> Semi-related to this, what about offering to simplify straight lines with multiple untagged/connected nodes along their length?

We don't currently offer a great line simplification operation in iD.  This is being tracked on #3116.

**Comment by bhousel** [comment]
done in #6267
