### ISSUE TITLE
Option to ignore specific issues to keep them from reappearing

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#6242]
In Japan, there's a very clear background layer which we can trace the shape of features easily and precisely as attached below and many buildings (rather older ones) have non (but) near 90/180 degree corners in real.
Is it possible to flag such issues as OK or no problem so that they won't be shown repeatedly as issues to solve, although I don't know if it's a common case.
http://preview.ideditor.com/master/#background=finds.jp_KBN_2500&disable_features=boundaries&map=19.00/35.78448/139.90681

![](https://i.imgur.com/kbWJZqO.png)
(buildings with red circle are marked as issue but it is unappropriate to change the shape)

**Comment by manfredbrandl** [comment]
You can simply switch off the rule:
![image](https://user-images.githubusercontent.com/5360273/56739351-bc04b780-676e-11e9-99f3-7373e23915ac.png)

**Comment by quincylvania** [comment]
@higa4 Yep, you can turn off the rule if you want.

However, we've wanted to add some kind of "Ignore this issue" option for awhile so I'll leave this issue open for that.

**Comment by higa4** [comment]
> some kind of "Ignore this issue" option

Thanks! I think It's a very important function to avoid careless almost automated edit. I know I can switch off, but others (many newbies) may not. Also those who are tracing other (lower resolution)  background imagery will not notice the small difference of the degree of the corners and they may make it square.

**Comment by quincylvania** [comment]
@higa4 Are you 100% sure that the buildings themselves aren't square in the real world? Is it possible that the background layer just incorrectly shows them as unsquare? I'm afraid that they look like a mistake to me and that others may square them anyway if they didn't know better.

**Comment by higa4** [comment]
Although I don't know so much about other countries, but I suppose there are much square buildings than unsquare ones totally. But unsquare small buildings can be commonly seen in rural area (old house) or high density population area because of the lack of enough square space to build buildings.

**Comment by higa4** [comment]
Those who trace easily and fast tend to make the building square (use rectify "Q" command in iD or use building draw plugin in JOSM). Those who trace carefully tend to distinguish the buildings to use "Q" command or not.
