### ISSUE TITLE
noexit being suggested for all disconnected nearby ways

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#6243]
Suggesting `noexit` to denote the end of a way that is close to, but not connecting with another way, seems like a good idea. However, it appears to take "no exit" too literally.
Last time I checked, this was a tag for two ways that are close, but separated by an impassable feature (as is illustrated on the wiki page for the tag).
iD suggests noexit for such cases as for example a parking aisle close to a footway, where the footway is not connected to the road, but one could walk between the two (on grass). 
Is this rule being applied correctly?

**Comment by manfredbrandl** [comment]
If people are walking „on gras“ between a road and a footpath, isn‘t there a path them, which should be mapped? This would allow routers (mode: walking) to use this connection.

**Comment by tohaklim** [comment]
They do not (generally) walk there, but it is physically possible. In my mind noexit is for where it is not physically possible to walk from one way to another

**Comment by bhousel** [comment]
The "noexit" suggestion is just a suggestion.  It's one of several choices, and users can choose to do something else instead, like connect the ways, or map a separate way (maybe as a footpath) to eliminate the disconnection.
