### ISSUE TITLE
Don't suggest adding "crossing=unmarked" to crossings without "crossing=*"

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6244]
20% of all crossings in my area that don't have the crossing=* tag (but do have highway=crossing or footway=crossing") should be given **crossing=marked**, not **crossing=unmarked**  Unfortunately, iD offers me the option to "upgrade tags" automatically for hundreds of objects at once, making it possible to incorrectly tag hundreds of objects at once.

I would suggest removing this rule and instead replacing it with two options: **tag as marked crossing**, and **tag as unmarked crossing**.

**Comment by bhousel** [comment]
I agree that in the case where there is no existing crossing tag, we should probably ask the user to supply one instead of assuming `unmarked`.

**Comment by quincylvania** [comment]
I fixed this by adding unsearchable presets for crossings without a `crossing` tag. Once we do #6101 we can prompt users to select a crossing type.
