### ISSUE TITLE
Question: "Deep" presets possible?

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/iD#6247]
The title is perhaps misleading, I couldn't come up with a better word for it, so I start with an example:

### Example
In German, a `shop=car` is commonly called a _"Autohaus"_. If it is a dealer that only deals in used cars (`second_hand=only`), the common word for it is completely different: _"Gebrauchtwagenhändler"_ (_second hand carriage dealer_).

I know many more examples where when a POI is given an extra tag, **which doesn't need to be a subcategory**, the common word for it completely changes.

### Question
I wonder, is it possible to map this in the iD preset system so that if a user searches for _"Gebrauchtwagenhändler"_, he will get `shop=car` + `second_hand=only`, and the other way round?

And again, I do not mean subcategories, sometimes, a tag that does not exactly form a subcategory will lead to a different name. I can provide many more examples to illustrate if you wish.

**Comment by bhousel** [comment]
> I wonder, is it possible to map this in the iD preset system so that if a user searches for _"Gebrauchtwagenhändler"_, he will get `shop=car` + `second_hand=only`, and the other way round?

Yes, iD already supports many presets like this. The convention we follow is to just add another folder under the main one for the sub-presets.

You can browse through the folders here and look for nestings: https://github.com/openstreetmap/iD/tree/master/data/presets/presets

Some examples
- [presets/amenity/fast_food](https://github.com/openstreetmap/iD/tree/master/data/presets/presets/amenity/fast_food) - specific kinds of fast food 
- [presets/shop/clothes](https://github.com/openstreetmap/iD/tree/master/data/presets/presets/shop/clothes) - specific kinds of clothing stores
- [presets/amenity/vending_machine](https://github.com/openstreetmap/iD/tree/master/data/presets/presets/amenity/vending_machine) - specific kinds of vending machines

For your example, we could could have
-  `/presets/shop/car.json` - for any kind of car dealer.
-  `/presets/shop/car/used.json` - for specific used car dealer.

(should I create this, or are you just asking a question if it's possible?)

**Comment by westnordost** [comment]
Thank you! No, I was just asking the question. I am currently going through a private list of possible preset-y things and wondering what of it I can contribute. The second hand car shop was just an example, I am not sure if it should be added only because in German, it is a different word. In other languages, it might not be a different word and as far as I know, it is not possible to define presets that should only exist in certain languages.

**So, just to understand clearly**: Supposedly, if I wanted to make a preset for a _"second hand clothes store"_ (`second_hand=only`), this would work and could exist alongside the _"underwear clothes store"_ (`clothes=underwear`) preset that already exists?

**Comment by quincylvania** [comment]
> Supposedly, if I wanted to make a preset for a "second hand clothes store" (second_hand=only), this would work and could exist alongside the "underwear clothes store" (clothes=underwear) preset that already exists?

@westnordost Yep, the preset hierarchy isn't too strict since OSM tagging is so messy.

Hypothetically I would add that as `shop/clothes/second_hand` even though `second_hand` isn't the value of the `clothes` key. A similar example would be `highway/footway/conveying` living alongside `highway/footway/sidewalk`.
