### ISSUE TITLE
Question: Reasons why a preset is not searchable

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/iD#6248]
The readme reads:

> Deprecated or generic presets can include the property "searchable": false. This means that they will be recognized by iD when editing existing data, but will not be available as an option when adding new features.

I noticed that the [notary](https://github.com/openstreetmap/iD/tree/master/data/presets/presets/office/lawyer) preset is not `searchable` and also some others that are neither deprecated according to the wiki (and the `deprecated.json`) nor are "generic presets".
Is there a third reason why a preset may be flagged as `searchable: false` that is not mentioned in the readme?

**Comment by quincylvania** [comment]
@westnordost Oh, that's supposed to be deprecated but wasn't. Thanks for noticing!

To answer this question:

> Is there a third reason why a preset may be flagged as `searchable: false` that is not mentioned in the readme?

A preset may be unsearchable if it is very similar to another preset and so may be confusing. The main example I'm thinking of is `building/_train_station`.

**Comment by westnordost** [comment]
Ok, then I'll open a ticket everytime I notice something like this. Maybe a short comment could be added to each searchable:false as to describe why it isn't to acoid confusion in the future. Just a suggestion.

**Comment by bhousel** [comment]
> Ok, then I'll open a ticket everytime I notice something like this.

Please don't.  GitHub is not a Q&A site.  We already have plenty of issues and the maintainer fatigue is hitting me pretty hard.  I'll try to answer your questions, but a nicer thing to do would be to hop into Slack and ask them, or even better would be to use the history and blame features on GitHub to try and figure out when things were added and why.

For this question, it's not hard at all to click on the file, and browse it's history and learn that in https://github.com/openstreetmap/iD/issues/4634 , and a previous linked discussion, someone asked us to remove the duplicate way of tagging notaries.

**Comment by westnordost** [comment]
Ok, I understand
