### ISSUE TITLE
Low performance of changeset comment field

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6249]
For the changeset comment field, I still have the issue from https://github.com/openstreetmap/iD/issues/6054

> Its really bad when I type my commit message. I type and nothing happens and then the text appears all at once.

I took some of those Google Chrome performance screenshots. But I don't really know how to read them, so I don't know what parts are useful. 

Do I read it right, that every key press triggers some big re-rendering action?

<img width="1512" alt="Bildschirmfoto 2019-04-28 um 06 39 16" src="https://user-images.githubusercontent.com/111561/56858830-0e1d2700-6981-11e9-8ba3-ced961e3ca74.png">

<img width="1512" alt="Bildschirmfoto 2019-04-28 um 06 39 30" src="https://user-images.githubusercontent.com/111561/56858834-170df880-6981-11e9-9152-aafd4a39fedc.png">

<img width="1512" alt="Bildschirmfoto 2019-04-28 um 06 40 14" src="https://user-images.githubusercontent.com/111561/56858838-20976080-6981-11e9-8938-4b9b21498c1e.png">

**Comment by bhousel** [comment]
Yes thanks for ticketing - I know about this and tried addressing it in https://github.com/openstreetmap/iD/pull/6140/commits/ae06e28f9ba7068efcfe082376f7ba7fa1fbcf51
But realized then that it didn't completely fix the issue.

This is why I'm pushing on the d3 upgrade this week in #6245 - to eliminate that as one potential source that might trigger the style recalculation.

**Comment by bhousel** [comment]
Also worth mentioning - if you are using the profiler, you should uncheck the "screenshots" feature, because that will slow things down even more and possibly mask the actual source of the slowness you're investigating.

**Comment by tordans** [comment]
I can confirm, the changeset comments field feels snappy again.

For comparison:
(From "click on save-button to click on commit-button")

<img width="1400" alt="Bildschirmfoto 2019-05-01 um 07 22 22" src="https://user-images.githubusercontent.com/111561/57006597-4ec7ab00-6be2-11e9-8eee-2459937cd2d7.png">

<img width="957" alt="Bildschirmfoto 2019-05-01 um 07 23 31" src="https://user-images.githubusercontent.com/111561/57006607-5edf8a80-6be2-11e9-968c-476c0a1db0d3.png">

<img width="1371" alt="Bildschirmfoto 2019-05-01 um 07 24 07" src="https://user-images.githubusercontent.com/111561/57006609-669f2f00-6be2-11e9-95b0-43a658fce606.png">
