### ISSUE TITLE
Don't add "public_transport:version=2" to stop_area relations

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6250]
Is this a valid update suggestion?

I don't know enough about the public transport schema. But just adding `public_transport:version=2` without any other changes feels weird. 

Does it basically mean: "This object does follow the public transport version 2 schema, so we might as well add the version-tag to it so its "official"."?

Location: http://preview.ideditor.com/master/#background=GEOSN-DOP-RGB&id=r3652527&map=20.00/51.03082/12.83603

<img width="372" alt="Bildschirmfoto 2019-04-28 um 07 31 21" src="https://user-images.githubusercontent.com/111561/56859209-da91cb00-6987-11e9-8b54-cb671b728eb4.png">

**Comment by tordans** [comment]
PS: If someone who knows about public transport opens the link, please also check the other validations; I don't know if they are a match here since I don't know enough about the details of the schema.

**Comment by BjornRasmussen** [comment]
This is most definitely unnecessary. No data consumers would ever need that tag, since stop areas are by default PTv2.

**Comment by bhousel** [comment]
> This is most definitely unnecessary. No data consumers would ever need that tag, since stop areas are by default PTv2.

As far as I know, the tag is still in use.
We are following the recommendation from here:  https://wiki.openstreetmap.org/wiki/Key:public_transport:version

**Comment by Nakaner** [comment]
> As far as I know, the tag is still in use.
> We are following the recommendation from here: https://wiki.openstreetmap.org/wiki/Key:public_transport:version

That's partially true only. To quote the wiki page you linked (highlight by myself):

> This key is used by JOSM/Validator and Osmose to distinguish between public transport **route** relations of old and new scheme for proper validation and usage of both schemes.

@tordans complains that the validation warning is shown for a stop area relation. `type=public_transport` + `public_transport=stop_area` do exist for version 2 only. The tag was invented by the JOSM developers to decide which validation and autocompletion rules to use for **routes**. Therefore, this ticket is a valid bug report.

**Comment by bhousel** [comment]
> @tordans complains that the validation warning is shown for a stop area relation

Ohhh ok, he didn't specifically say this, but I understand now that the real issue is that it shouldn't be suggested for `stop_area`.
