### ISSUE TITLE
Validation: Suggest area residential where buildings are

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6264]
The validator could suggest to add an area `landuse=residential` around private buildings.

Example: http://preview.ideditor.com/master/#background=GEOSN-DOP-RGB&disable_features=boundaries&locale=en&map=16.93/50.97227/12.82492
For some reason there are missing landuse-areas in this village.

I also remember some HOTOSM tasking manager tasks that tried to explain to me when I should draw the landuse=residential area. This could be a bit automated by this.

The validator could suggest to add the area manually. But maybe even provide an "add landuse area" quick-link which creates the area around all buildings in the visible area?

Or maybe there could be a quick-action feature for the validator that basically starts the mapping of this type: I click "Start drawing residential area", the editor selects the preset and I just need to click around the buildings to add the area.

This validation might also be based on the reverse of the planned(?) preset-relation.
There is a school building, suggest the school ground. There are residential houses, suggest the landuse=residential. And so on.

**Comment by bhousel** [comment]
I kind of think this is getting nitpicky..

**Comment by tordans** [comment]
> nitpicky

Yeah. It might be, that the ease of the new UI makes me wish the UI would just take over all my mapping clicks and just lets me do the thinking and directing … :-)
