### ISSUE TITLE
Internet Access Fee (feature request)

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#6265]
When I add a holiday cottage (aka chalet) the preset field for Internet Access is present.  What would be nice is, if I enter any value other than "no", the "Internet Access Fee" field appears automatically without me having to type "i" into additional fields.  Some holiday cottages offering internet access charge for it, these days most do not; either way it is useful to make the distinction because that may influence a person's decision to stay at the holiday cottage.

Other internet access subtags are far less useful and rarely mapped.  But fee is one I add every time I add internet access and can determine if it is free or not.  It's rare that I encounter a case where I cannot determine if there is a fee or not.

The same thing applies to any other type of facility where internet access is one of the displayed fields: pub, hotel, etc.

**Comment by quincylvania** [comment]
@eehpcm Sure, this is fine since the fee field won't appear until you set a positive Internet Access value anyway so we're not cluttering the default UI.

**Comment by eehpcm** [comment]
@quincylvania 

>  Sure, this is fine since the fee field won't appear until you set a positive Internet Access value anyway so we're not cluttering the default UI.

It was removed in the big decluttering™ but that introduced conditional visibility for some things so I figured you might be happy with this suggestion.  Thanks.
