### ISSUE TITLE
bug?: node extracted while merging nodes

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6268]
map area:
http://preview.ideditor.com/master/#background=none&disable_features=boundaries&map=23.20/40.77057/-73.99401

Is this related to new validation? https://github.com/openstreetmap/iD/pull/6267 (very close node on road)

By the way, this validation (very close node on road) brings a lot of maybe "false positives" results for areas with high coverage density of map objects, maybe you could change the validation-check of node distance from2m to 1m? 

![extract](https://user-images.githubusercontent.com/47290585/56942851-1dd17280-6b1d-11e9-9b2e-6103ed3410e5.gif)

**Comment by BjornRasmussen** [comment]
Somewhat related: these false positives especially bad on sidewalks, where fixing all warnings will result in very bad alignments.  Could this validation for paths and sidewalks have a reduced distance to perhaps 0.3 meters instead of 2?

For most roads, though, I love this new validation!

**Comment by bhousel** [comment]
Thanks @sun-geo and @BjornRasmussen for your feedback - we'll adjust the threshold 👍

**Comment by BjornRasmussen** [comment]
Thanks! 
Here is an example of what I was talking about: http://preview.ideditor.com/master/#background=Bing&disable_features=boundaries&id=w16545896&map=19.40/35.94239/-78.91871 and set the validation to "Everything" "In view"

**Comment by BjornRasmussen** [comment]
Another issue that should be fixed together with this for sure is that junction nodes are merged with nearby nodes, with the resulting node having the "average" location between the two nodes.  The actual location should be on the node shared by another way so that the junction is not moved to a new inaccurate location.

**Comment by BjornRasmussen** [comment]
Another issue: Nodes can be connected between different roads, creating invalid alignments.

**Comment by quincylvania** [comment]
I just had the extracted node happen to me during a crossing ways connection fix. There was an "entity not found" error doing async validation, so I don't think the displayed issue was with the operation itself. I think the thing to do is edit a lot and just add defensive code every time something appears to go awry.

**Comment by sun-geo** [comment]
Interesting.

Additional information: 2 days ago, when I reported this, I had a 100% reproducibility rate for that area and that action steps (see movie) to extract a node. When I try to reproduce it now (same area same action), it don't happened anymore.

**Comment by sun-geo** [comment]
Thanks for changing the threshold in https://github.com/openstreetmap/iD/issues/6292

:-)

**Comment by quincylvania** [comment]
@sun-geo We change a bunch of things since you opened this so the problem may be fixed. Let us know if you see it again anywhere!

**Comment by sun-geo** [comment]
I agree :-)
