### ISSUE TITLE
In zh displaying the local order should be from bigger place to smaller place

### ISSUE THREAD

**Issue by Supaplextw** [openstreetmap/iD#6269]
As title, In zh, zh-tw, zh-hk lang setting, when you upload your changeset, the message says that thank for your contribution, the order of place should be from bigger place to smaller place, like country, city, district, suburban. In the current setting, the grammar is wrong in Chinese.

**Comment by quincylvania** [comment]
@Supaplextw Is there a way to change the grammar of the offending strings on the zh localizations instead?

**Comment by bhousel** [comment]
I think we are just pulling it from nominatim but I will check if we can improve it.. (this morning I started searching for an old issue maybe related to this and got sidetracked)

**Comment by quincylvania** [comment]
@quincylvania Oh I misunderstood the issue. I thought it meant the community index entries should be reversed based on the phrasing of the message, but I guess it's that the place order of the geocoded part of the message needs reversing.

**Comment by bhousel** [comment]
> I think we are just pulling it from nominatim but I will check if we can improve it.. (this morning I started searching for an old issue maybe related to this and got sidetracked)

oh I was wrong, it's just this code here - we can localize it with a translation string probably:

https://github.com/openstreetmap/iD/blob/d026f2f296c0c929aa7a84ea44f43a2dc5bccd16/modules/modes/save.js#L482-L489

**Comment by 1ec5** [comment]
Also, the components would normally be joined together, not separated by a comma or space. This might get a little weird if one of the components isn’t in Chinese characters, though. As far as I can tell, Japanese and Korean follow the same convention as Chinese (but Korean uses spaces).

**Comment by bhousel** [comment]
Thanks for you feedback @Supaplextw & @1ec5 👍 
We support more localization options now:

```yaml
    thank_you_location: "Thank you for improving the map around {where}."
    thank_you_where:
      format: "{place}{separator}{region}"
      separator: ", "
```

Separator will only be inserted if the reverse geocode actually returns both placelike and regionlike results:

```js
    var addr = result.address;
    var place = (addr && (addr.town || addr.city || addr.county)) || '';
    var region = (addr && (addr.state || addr.country)) || '';
    var separator = (place && region) ? t('success.thank_you_where.separator') : '';

    _location = t('success.thank_you_where.format',
        { place: place, separator: separator, region: region }
    );
```

**Comment by Supaplextw** [comment]
Thanks for the help. Hope the next update will see a better improvement.

Supaplextw
