### ISSUE TITLE
Creating a new feature doesn't automatically start the "choose feature type" option

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6271]
Using http://preview.ideditor.com/master, try drawing a new line or area.  When you finish, an error will show up saying to "choose feature type."  Instead, iD should, as it did before, automatically start the "choose feature type" option after a new line / area is drawn.

**Comment by quincylvania** [comment]
Fixed. Thanks for posting @BjornRasmussen 👍
