### ISSUE TITLE
Cannot disconnect more than two ways with relations

### ISSUE THREAD

**Issue by famo** [openstreetmap/iD#6272]
(accidentally hit enter)

**Comment by famo** [comment]
If there are two ways (each with there own relation) which share a node, you can easily disconnect the two ways by selecting the common node and hitting `D`. The result will be the two ways (still connected within), each with there relation - as expected.
However once you add a third way with a third relation, you get the error message on `D` that you are trying to disconnect relations... :confused: 

Is there a reason for this limitation to only two ways & relations?

**Comment by quincylvania** [comment]
@famo Can you post a location where this is reproducible? Or a screencapture?

**Comment by famo** [comment]
@quincylvania sure here is a good area to test:
https://www.openstreetmap.org/edit#map=20/52.49812/13.37296

Connect the railway lines and try to disconnect them.

![Screenshot_20190512_175543](https://user-images.githubusercontent.com/692646/57584746-39565900-74df-11e9-9b18-d75ecc4de3de.png)

**Comment by quincylvania** [comment]
@famo This is actually working as expect since the two ways are members of the same relation. If you connect them by accident, you can still undo.
