### ISSUE TITLE
[Good first issue][preset] Add preset for: Windsock

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#6282]
[Wiki](https://wiki.openstreetmap.org/wiki/Tag%3Aaeroway%3Dwindsock)

`aeroway=windsock`  
Possibly also `seamark:landmark:category=windsock`  
Check box for `lit=*`?

**Comment by quincylvania** [comment]
@rivermont Thanks, this was already been added to the master branch and will be in the next release of iD. Test it on http://preview.ideditor.com/master
