### ISSUE TITLE
Mapillary window: resizing doesn't work properly.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6286]
To reproduce: 
1) Open a mapillary image with preview.ideditor.com/master
2) Make the window of the image larger.
3) Observe this: 
![image](https://user-images.githubusercontent.com/37753777/57046071-418bda00-6c3d-11e9-8884-b8f29399f3b1.png)

**Comment by tordans** [comment]
_A bit of debugging:_ I could not see any relevant css that is different from osm.org to preview. So I guess its not about the reworked css for the panels (that was recently, right). Maybe it has to do with https://github.com/openstreetmap/iD/pull/6166? Not from the release notes, though (https://github.com/mapillary/mapillary-js/releases). But they did change a lot with https://blog.mapillary.com/update/2019/04/16/mjs-combined-panning.html.

**Comment by quincylvania** [comment]
Yeah, I'm not sure this is an iD-specific issue. Note that a workaround is to resize the viewer, close it, then reopen it.

**Comment by quincylvania** [comment]
@cbeddow Any thoughts on this?

**Comment by tohaklim** [comment]
I remember this happening quite a while ago, then seemingly fixed, and now it's back again - Mapillary codebase changes?..

**Comment by cbeddow** [comment]
It seems like a CSS conflict, but not clear as mentioned. MapillaryJS should automatically upgrade itself, but we'd want to debug and find the current version. Can we check somehow if it's 2.18.0? When you resize, then MJS calls a resize() function on itself, but maybe is trying to target the wrong div, or an empty variable. I assume overall it may be some lag time causing this to not find what it's trying to resize sometimes.

**Comment by carstenhag** [comment]
It would be great if this would be fix. I now need to open another tab which is prett annoying.

**Comment by cbeddow** [comment]
Testing today for me as well and not working here. I will see if we can get this fixed ASAP but it probably is a failure to recognize the window resize and apply .resize() to the Mapillary viewer div.

![image](https://user-images.githubusercontent.com/10554922/63511888-ac11a000-c4e2-11e9-9c8d-4891052ec8de.png)

**Comment by carstenhag** [comment]
Thanks!

Quincy Morgan <notifications@github.com> schrieb am Do., 22. Aug. 2019,
17:20:

**Comment by quincylvania** [comment]
This turned out to be an iD issue after all. Oops!

The viewer `resize` event was only getting sent to the last viewer to register for it. This also meant that Bing Streetside images would get stretched instead of scaled. Congrats to OpenStreetCam on landing last alphabetically 😅

Thanks for your patience on this everyone!
