### ISSUE TITLE
Validation rule: disconnected from other roads - but ferry stops...

### ISSUE THREAD

**Issue by Stalfur** [openstreetmap/iD#6287]
Found an issue where ferry stops don't count as the continuation of the road network. Validation rule should probably take ferry stops in account

![image](https://user-images.githubusercontent.com/4370958/57052428-939d2180-6c76-11e9-885e-9e4ffeb4bdae.png)

https://www.openstreetmap.org/edit#map=17/-5.59720/23.46122

**Comment by bhousel** [comment]
Good suggestion @Stalfur 👍
