### ISSUE TITLE
Reduce false positives raised by the square building validation

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6288]
Currently, it's possible to square buildings like this one without looking at them: http://preview.ideditor.com/master/#background=Bing&id=w44318672&map=19.95/35.95211/-79.00788
Note: you need to change a tag on the building for the warning to show up.

I see 2 solutions to this:
1) Making the quick fix only work if the building is very close to being square - as in not the shape above.
2) Or, use a more clever solution and change the `building is very close to being square but isn't` method to look at **distances** of nodes moved by squaring (or just building size in general), not just angles.  This would mean that a small building that is almost square would have a warning show up, but a larger building with the exact same shape would not.  The reasoning for this is that the inaccuracies in mapping buildings are roughly the same _distance_, not angle, so smaller buildings will often get mapped with less detail relative to their size than larger buildings.  For example, a mapper mapping a small house with 5 foot accuracy for each node would create a very lopsided shape.  Using 5 foot accuracy to map a large warehouse would result in a very square looking shape. This difference means that smaller buildings should have a larger angle threshold for being "almost square" than larger buildings should.

**Comment by BjornRasmussen** [comment]
Much of the imported buildings in my area are square in the real world, but not in the imported dataset.  iD has been very useful lately for improving the alignments of these buildings to be square.  JOSM has a more aggressive squaring algorithm that would ruin 45 degree angles, so iD has been a real time saver over JOSM in that way. 
Ignoring buildings with a source tag would make this type of cleanup impossible.

**Comment by bhousel** [comment]
Thanks @BjornRasmussen, based on your feedback I've made a few changes..
- I adjusted the thresholds a bit so that it would flag fewer false positives
- I disabled the "autofix" option for buildings that have additional tags (presuming that they are mapped to a better standard).  If unsquare, they will still appear on the list, but the wrench fix button won't be available, to prevent people from just squaring them without a proper review.
