### ISSUE TITLE
In RTL mode panes fly from/to the middle of screen instead of leftside

### ISSUE THREAD

**Issue by iriman** [openstreetmap/iD#6290]
_this is about preview release of iD_

![ltr](https://user-images.githubusercontent.com/8467903/57060137-94ad6d80-6ccd-11e9-879d-247a9aa985e4.gif)

That's nice! but in rtl looks a bit odd:

![rtl](https://user-images.githubusercontent.com/8467903/57060138-94ad6d80-6ccd-11e9-8c0b-042e6ee8e721.gif)

It should fly from/to the leftside. thanks

**Comment by quincylvania** [comment]
Fixed. Thanks for posting, @iriman!

**Comment by iriman** [comment]
many thanks for fixing! :)
