### ISSUE TITLE
make waterway=riverbank areas more blue

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6291]
White or whiteish rendering is not making clear that it a water area, checking that requires clicking on it - and even then it may be not clear for newbies.

![Selection_003](https://user-images.githubusercontent.com/899988/57071925-39cf4280-6cdc-11e9-8f2a-7eb1df053c49.png)

https://www.openstreetmap.org/edit?editor=id&node=4306153491#map=18/15.35375/73.99960

Compare with natural=water

![Selection_004](https://user-images.githubusercontent.com/899988/57072000-769b3980-6cdc-11e9-89f1-42f191475cd7.png)

**Comment by BjornRasmussen** [comment]
With the next release of iD, anything tagged with waterway=riverbank will be flagged as depreciated with an option to upgrade to natural=water + water=river.

**Comment by bhousel** [comment]
Yes, previously we've supported rendering deprecated tagging, but going forward we are using generic styling for deprecated features to encourage users to upgrade them.
