### ISSUE TITLE
Too many warnings about "too close points"

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#6292]
In Graz there are really many warnings about too close points, many of which are simply exactly mapped:
![image](https://user-images.githubusercontent.com/5360273/57078492-ab17f100-6cee-11e9-8d07-9d324a247551.png)
I still wand to find very close points (< 0,5 meters), but not see close points (< 2,0 meter).
Is this legitimate?

**Comment by bhousel** [comment]
Ah yeah #6268 also mentions the high numbers of false positives, and I agree. I'm going to close here as a duplicate..  I know @quincylvania is already working on improvements to this validation.

**Comment by quincylvania** [comment]
I'm actually going to keep this open since #6268 is primarily focused on some bizarre node extraction behavior.

**Comment by BjornRasmussen** [comment]
The new validation is much better! Thanks!
