### ISSUE TITLE
takeaway=only with amenity=restaurant (should be amenity=fast_food)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6293]
2k+ cases worldwide - maybe I am missing something but this combination seems to make no sense

http://overpass-turbo.eu/s/IDq

**Comment by westnordost** [comment]
Feature presets in iD only define what fields should be shown, not what value these fields are (allowed to) have. JOSM works the same.

![image](https://user-images.githubusercontent.com/4661658/57106389-83944900-6d2d-11e9-8133-a8086891bb82.png)

The cases you cite were entered by users deliberately, there is no preset in iD that would specifically add `amenity=restaurant + takeaway=only`

**Comment by quincylvania** [comment]
I don't see a great way to address this in iD. Maybe some of these should be `fast_food`, but some could also be `cafe` or a caterer or whatever, we don't know.

**Comment by matkoniecz** [comment]
@westnordost I though about validator warning if such combination would be set.

@quincylvania Good point that `fast_food` is not the only correct version. Is it already possible to show warning with custom message on specific tag combination or is it still only 1:1 upgrade button?

**Comment by quincylvania** [comment]
@matkoniecz It's still 1:1 at the moment.
