### ISSUE TITLE
Changeset tags: Add source tag based on editor layer index attribution

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6300]
Some editor layer should be named with a specific term in the changeset `source`-tag.

For example: `source=Geoportal Berlin/Digitale farbige Orthophotos 2018` ([Link](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/de/Berlinaerialphotograph2018.geojson?short_path=20f3a31#L13))

More are listed at https://wiki.openstreetmap.org/wiki/Contributors; browser search for "source" show 104 results

The editor layer index has a field for `attribution`.
Schema: https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json#L145-L160

This field is currently used in iD to show the attribution on the map.
**In addition, it should also be added as a value for the changesets `source`-key.**

**I suggest adding it using the same logic that is used for the `imagery_used` and extend it to add the `source` as well.**

I suggest ignoring the `required=true/false` attribute of the editor layer index schema since it cannot be too bad to have it even if required=false.

---

Additional key `source:url`?

The wiki for source does not specify a pattern to add an URL https://wiki.openstreetmap.org/wiki/Key:source. However, https://taginfo.openstreetmap.org/keys/source%3Aurl is used >120k times.

So maybe it makes sense to also add `source:url=[<attribution.url>](https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json#L148-L150)` to the changeset?
However, I don't know how to handle multiple sources then.

**Comment by bhousel** [comment]
> Some editor layer should be named with a specific term in the changeset `source`-tag.

I'm not saying "no" but.. this just seems like some thing you made up.

I'm really ok with adding more changeset tags for things, but I'd really like some indication that other editors are doing this also.  Or that somebody wants it.

What I really don't want is for us to start adding `source` tags for certain imagery, and then have someone later complain that "iD is adding useless tags".  And then we just have to say "well it was just some idea that Tordans had, I dunno".

We already set `imagery_used`, which seems like enough.  Anyone can just compare the string there with the `id` in editor-layer-index.

**Comment by tordans** [comment]
@bhousel how about iD changes the text it uses for imagery_used?

Currently: 
`imagery_used={properties.name}` ([Link](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/de/Berlinaerialphotograph2018.geojson?short_path=20f3a31#L5)) (the name that is used in the layer selection side panel

New
`imagery_used={properties.attribution.text}` ([Link](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/de/Berlinaerialphotograph2018.geojson?short_path=20f3a31#L13))

The name is used for users to look nice. The attribution is used to follow the formal wording required by the data provider. So IMO its a good fit for the changeset.

I agree, duplication is not a good thing. And AFAIK its not about the source-key, just about the wording.

--- 

> … this just seems like some thing you made up.

Maybe. I am just trying to interpret what is written. For Berlin …
- here https://wiki.openstreetmap.org/wiki/Contributors#Berlin
- here https://forum.openstreetmap.org/viewtopic.php?pid=367583#p367583
- here https://wiki.openstreetmap.org/wiki/Geoportal_Berlin#Verf.C3.BCgbare_Dienste

It says: The city wants a specific string to be assosiated with the change. The string is in `attribution.text`, not in `name`.

On https://wiki.openstreetmap.org/wiki/Contributors there are more cases, where a specific string is given to add as source-value to the changeset. Eg Moers, Bonn, Hungary, maybe Slovakia, maybe Slovenia, "Natural England data", "Ordnance Survey OpenData", "Public Rights of Way Data from local councils" and other on the page.

--- 

Checking other editors:

- JOSM: It looks like nothing is added automatically; the user has to set it manually. At least I don't see any pattern in the wording of the source-value. [OSMCha Search](https://osmcha.mapbox.com/changesets/69827753?filters=%7B%22geometry%22%3A%5B%7B%22label%22%3A%7B%22type%22%3A%22MultiPolygon%22%2C%22coordinates%22%3A%5B%5B%5B%5B13.088345%2C52.4196325%5D%2C%5B13.75531%2C52.441587%5D%2C%5B13.4142585%2C52.6412391%5D%2C%5B13.088345%2C52.4196325%5D%5D%5D%2C%5B%5B%5B13.5034382%2C52.6189926%5D%2C%5B13.5054362%2C52.6196852%5D%2C%5B13.5054513%2C52.6198896%5D%2C%5B13.5034382%2C52.6189926%5D%5D%5D%5D%7D%2C%22value%22%3A%7B%22type%22%3A%22MultiPolygon%22%2C%22coordinates%22%3A%5B%5B%5B%5B13.088345%2C52.4196325%5D%2C%5B13.75531%2C52.441587%5D%2C%5B13.4142585%2C52.6412391%5D%2C%5B13.088345%2C52.4196325%5D%5D%5D%2C%5B%5B%5B13.5034382%2C52.6189926%5D%2C%5B13.5054362%2C52.6196852%5D%2C%5B13.5054513%2C52.6198896%5D%2C%5B13.5034382%2C52.6189926%5D%5D%5D%5D%7D%7D%5D%2C%22editor%22%3A%5B%7B%22label%22%3A%22JOSM%22%2C%22value%22%3A%22JOSM%22%7D%5D%2C%22source%22%3A%5B%7B%22label%22%3A%22Berlin%22%2C%22value%22%3A%22Berlin%22%7D%5D%7D).

- GoMap seems to have the same behaviour as iD, it adds the display name as imagery_used. [Changeset Example](https://www.openstreetmap.org/changeset/69783508), [OSMCha Search](https://osmcha.mapbox.com/changesets/69784939?filters=%7B%22geometry%22%3A%5B%7B%22label%22%3A%7B%22type%22%3A%22MultiPolygon%22%2C%22coordinates%22%3A%5B%5B%5B%5B13.088345%2C52.4196325%5D%2C%5B13.75531%2C52.441587%5D%2C%5B13.4142585%2C52.6412391%5D%2C%5B13.088345%2C52.4196325%5D%5D%5D%2C%5B%5B%5B13.5034382%2C52.6189926%5D%2C%5B13.5054362%2C52.6196852%5D%2C%5B13.5054513%2C52.6198896%5D%2C%5B13.5034382%2C52.6189926%5D%5D%5D%5D%7D%2C%22value%22%3A%7B%22type%22%3A%22MultiPolygon%22%2C%22coordinates%22%3A%5B%5B%5B%5B13.088345%2C52.4196325%5D%2C%5B13.75531%2C52.441587%5D%2C%5B13.4142585%2C52.6412391%5D%2C%5B13.088345%2C52.4196325%5D%5D%5D%2C%5B%5B%5B13.5034382%2C52.6189926%5D%2C%5B13.5054362%2C52.6196852%5D%2C%5B13.5054513%2C52.6198896%5D%2C%5B13.5034382%2C52.6189926%5D%5D%5D%5D%7D%7D%5D%2C%22editor%22%3A%5B%7B%22label%22%3A%22Go%20Map%22%2C%22value%22%3A%22Go%20Map%22%7D%5D%7D)

- [iD Changeset Example](https://www.openstreetmap.org/changeset/69402897#map=19/52.46873/13.44218)

**Comment by bhousel** [comment]
> > … this just seems like some thing you made up.
> 
> Maybe. I am just trying to interpret what is written. For Berlin …
> 
> * here https://wiki.openstreetmap.org/wiki/Contributors#Berlin
> * here https://forum.openstreetmap.org/viewtopic.php?pid=367583#p367583
> * here https://wiki.openstreetmap.org/wiki/Geoportal_Berlin#Verf.C3.BCgbare_Dienste

Again.. you're just linking to stuff on the OSM wiki. 

I know it says that a specific message should be in the changeset.  But I'd prefer for this request to come from someone from Geospatial Berlin.  Not just because you read something on a wiki that says a thing and you are interpreting it to mean that we literally need to include an attribution line in every changeset.  

Nobody has yet told us that we needed to put attribution messages into changeset tags before now, and no other software is doing it, so it's a _really_ weird request.  

If Geospatial Berlin asked me to do it, I'd explain to them that we already do include an `imagery_used` tag so that people can see which imageries were used in the edits, and that nobody else's imagery license has a request like this.  If they absolutely required it, I'd probably just, roll my eyes and hardcode a line for them, rather than interfering with everyone elses changesets.

**Comment by tordans** [comment]
Closing note: I talked to Bryan and [DD1GJ](https://www.openstreetmap.org/user/DD1GJ) further. Lets close this for now until there is a more clear path to what really needs to be done.

**Comment by matkoniecz** [comment]
It appears to be discussed and rejected also in #7876

Also the same request was rejected in JOSM: https://josm.openstreetmap.de/ticket/19911
