### ISSUE TITLE
Area after removing all tags changes into a line

### ISSUE THREAD

**Issue by RafalR** [openstreetmap/iD#6305]
After removing all tags from the area, iD editor proposes templates only for lines, items for areas are missing.

**Comment by bhousel** [comment]
Unfortunately this is a consequence of OpenStreetMap's data model.  The tags are what determines whether a feature is a line or an area - so if you remove them all, iD wouldn't know that you want to see area choices.  

You can add an `area=yes` tag back onto the feature to let iD know that you want to see the area choices.
