### ISSUE TITLE
Wrong warning about highway crossing building

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#6308]
Have a `building=roof` + `layer=1` object with a `highway=secondary` crossing it.
iD is warning with:

![](https://user-images.githubusercontent.com/982338/57163034-6d869700-6dc6-11e9-87de-f0460cf77bee.png)

If the `building` is in another `layer` it means that the objects are not really crossing.

**Comment by BjornRasmussen** [comment]
I do agree with you about this, but iD currently wants you to use covered=yes on the way underneath to resolve this issue.  This should probably be added to the list of "fixes" currently available to make it more clear.

**Comment by bhousel** [comment]
This is #5924
