### ISSUE TITLE
Potential missing links to wiki documentation pages for several tags

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6310]
Using iD V2.14.3

example object:
https://www.openstreetmap.org/edit?way=463568165#map=19/34.14604/-118.15302

I would expect links like **"View documentation"** for the marked items to:

- https://wiki.openstreetmap.org/wiki/Key:addr:city
- https://wiki.openstreetmap.org/wiki/Key:addr:street
- https://wiki.openstreetmap.org/wiki/Key:contact:email
- https://wiki.openstreetmap.org/wiki/Key:contact:fax
- https://wiki.openstreetmap.org/wiki/Key:contact:phone
- https://wiki.openstreetmap.org/wiki/Key:contact:website

![image](https://user-images.githubusercontent.com/47290585/57174710-52a63800-6e43-11e9-8ea5-25913f73f12a.png)

![image](https://user-images.githubusercontent.com/47290585/57174715-5cc83680-6e43-11e9-8649-3526f2121e59.png)

**Comment by tordans** [comment]
@sun-geo I think we have to solve those on the Wiki / Wikidata side of things.

I started talking with @nyurik about a similar issue at
- https://wiki.openstreetmap.org/wiki/Talk:Data_items#How_to_document_.2A:both:.2A.2C_.2A:left:.2A.2C_.2A:right:.2A_keys.3F
- https://wiki.openstreetmap.org/wiki/Talk:Data_items#Wildcard_.28namespace.29_data_item_proposal

@nyurik the way to go ATM is, to add Wikidata items for each key, right?
- Where do we create new keys? I cannot find anything at https://wiki.openstreetmap.org/wiki/Data_items#Item_Creation_Process

And will we keep those keys without a Wiki page?

**Comment by nyurik** [comment]
@tordans correct. The easiest is to edit wiki pages:
* Go to a page like [Key:contact:email](https://wiki.openstreetmap.org/wiki/Key:contact:email)
* If there is a redirect, you will end up on Key:contact, but it will have a `(Redirected from Key:contact:email)` at the top - click on that.
* Edit that page and add a `{{KeyDescription|...}}` template there, while keeping the `#REDIRECT` line intact.

A bot should (hopefully) update/create data items soonish (in half a day in the worst case)

**Comment by sun-geo** [comment]
tordans - thanks for reading and checking!

> @sun-geo I think we have to solve those on the Wiki / Wikidata side of things.

Without reading and understand you posted links to the talk pages.
I don't hope & think so. By the way, do you mean with "wikidata" the osm.wiki-data items (https://wiki.openstreetmap.org/wiki/Data_items)?

**Comment by sun-geo** [comment]
to nyurik:
Redirected pages should be already available, so far I understand to system...

**Comment by nyurik** [comment]
Correct, so just add a description there. Many other redirects already have it. Add it only to the primary English ones. Translations should only be done in data items.

**Comment by tordans** [comment]
> @tordans correct. The easiest is to edit wiki pages: …

Thanks! I tried it for https://wiki.openstreetmap.org/w/index.php?title=Key%3Acontact%3Aemail&type=revision&diff=1848902&oldid=433904 by adding similar data to https://wiki.openstreetmap.org/wiki/Key:email.

Lets see what happens ;-)

**Comment by nyurik** [comment]
Bummer, I didn't see that there is already a data item associated with that redirect. You could have just clicked "osm data item" while on the redirect page. Oh well. The bot should still update it I hope, if not right away than in half a day. Our you can just enter the needed info in the data item

**Comment by nyurik** [comment]
Also, I just realized that if the data item was there all along, iD knew about it, and should have offered a way to add description. Which it did (there was a pencil icon), but it confused even me. I think we should show a different text in this case, e.g. "add description" being a link itself?

**Comment by sun-geo** [comment]
Just to clarify - the main intention of this ticket.

My main inportant point is, I would like to get this link (**"View documentation"**) for each tag:
.
![red](https://user-images.githubusercontent.com/47290585/57175597-3fe53080-6e4e-11e9-847f-40c9a2032f6f.png)

The second link (sometimes missing e.g. for contact:email) which is used for editing the data item is not so important for this ticket...:
.
![green](https://user-images.githubusercontent.com/47290585/57175595-3c51a980-6e4e-11e9-8c37-dce35cb9c1ae.png)

**Comment by tordans** [comment]
> Just to clarify - the main intention of this ticket.
> My main inportant point is, I would like to get this link (**"View documentation"**) for each tag:

Sorry, I was on the wrong track with the wiki data part, then.

AFAIK those links are sourced from the preset files. I don't know more that
- https://github.com/openstreetmap/iD/pull/6261/files
- example https://github.com/openstreetmap/iD/blob/master/data/presets/fields/address.json#L27

**Comment by bhousel** [comment]
Closing here, as it's not really an iD issue..

**Comment by nyurik** [comment]
@sun-geo I think I also misunderstood your question. The answer is - yes, data items need to be updated for redirects too. My bot currently does not handle it, but I hope I will have time to modify it.  Once modified, it will automatically add all redirect links to the data items.

**Comment by tordans** [comment]
OK, it took me a while to understand all the parts of it.

This does not really fit in the iD repo, but it kind of fits in this discussion. However, we might want to extend the ["translation" and "documentation" part of the docs](https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating) to explain a bit about where those texts come from. Would a PR be helpful for this?

Below is what I learned:

- in iD: A Key without a Data item description will show `There is no documentation available.` (which is `no_documentation_key`).
- in iD: (Only) If iD finds a Data item for this key, the item description will also have an Edit-Icon-Link (`.tag-reference-edit`).
- in iD: (Only) If iD finds a wiki-Link in this Data item, the Wiki-page is linked below the description (`.tag-reference-link`, [Example Data item])(https://wiki.openstreetmap.org/wiki/Item:Q1185)).
- to add a Data item to the wiki:
  1. Add a Key/Tag-Wiki-Page
  2. Add the `KeyDescription` template
      ```
      {{KeyDescription
      |key=contact
      |value=
      |image=
      |description=The contact tag is the prefix for several contact:* keys to describe contacts
      |group=
      |onNode=yes
      |onWay=yes
      |onArea=yes
      |onRelation=yes
      |implies=
      |status=
      |seeAlso=* {{Tag|phone}}
      * {{Tag|fax}}
      }}
      ```
  3. A bot will grab those info and create the Data item "in half a day"
  The KeyDescription can also be added to redirect pages. The bot will use it, but Users will not see it unless they look at the redirect closely ([Example](https://wiki.openstreetmap.org/w/index.php?title=Key:contact:email&redirect=no)).
- Wiki navigation: To get from a Wiki page to the Data item. On the Wiki-page > Left side navigation > Link "OpenStreetMap Wiki-Dataobject" (the page "links to this page" does not work for this).
- Wiki navigation: To get from the Data item to the wiki: Big link next to the title
- Wiki search for data items: Use the [advanced search](https://wiki.openstreetmap.org/w/index.php?search=contact%3Aemail&title=Special:Search&profile=advanced&fulltext=1&ns120=1&searchToken=9ridsa6xry0z6qmfqbh72124w) to filter for Data items.

**Comment by sun-geo** [comment]
> > Just to clarify - the main intention of this ticket.
> > My main inportant point is, I would like to get this link (**"View documentation"**) for each tag:
> 
> Sorry, I was on the wrong track with the wiki data part, then.
> 
> AFAIK those links are sourced from the preset files. I don't know more that
> 
> * https://github.com/openstreetmap/iD/pull/6261/files
> * example https://github.com/openstreetmap/iD/blob/master/data/presets/fields/address.json#L27

@tordans 
After bhousel did close the ticket I was wondering how it can be managed to get finally the desired blue "**View documentation**"-links.

Now I figured out how to do this.
For example for contact:website (data item: https://wiki.openstreetmap.org/wiki/Item:Q1186) 
In the data item there is an option to change the description text, but important for the blue "view documentation" links there is also an option to add(change) the pointer to the (international) wiki-pages by adding P31 "documentation wiki pages"/"Dokumentation im Wiki") statements. 
I did this for example by this changeset https://wiki.openstreetmap.org/w/index.php?title=Item:Q1186&diff=next&oldid=1849924 and now it looks like I want to have it, see here:

![image](https://user-images.githubusercontent.com/47290585/57298869-7da6bb00-70d3-11e9-8b49-5e2a13567afc.png)

:-)

**Comment by sun-geo** [comment]
@nyurik

btw I found different behaviors
For example for "oneway=yes" when i hit the pen icon it sends me to: https://wiki.openstreetmap.org/wiki/Item:Q19421 (Tag:oneway=yes)

The other example is "lanes=x" it sends me to https://wiki.openstreetmap.org/wiki/Item:Q372 (Key:lanes).

So, sometimes it sends me to a Key and for others to a Tag. How I change this, if it is needed?
Let's say if anybody want to change (not sure if it usefully for this case) for "oneway=yes" to send to (Key:oneway) instead of pointing to (Tag:oneway=yes).

**Comment by nyurik** [comment]
@sun-geo when you click the (i) icon, iD will try to get both the `key` and the `tag` data items.  If `tag` exists, it will use it, otherwise it will use the `key`.

I don't think it is good to create links (P31) by hand, because the bot will never update those for you -- it will see that a human edited them.  I will try to update my bot soon to do it, but the next few weeks are mega busy - big conference coming up for me, need to prepare.

The `Tag:oneway=yes` wiki page should be a redirect to `Key:oneway` -- and once I update my bot, it will create a redirect in the data item.

**Comment by sun-geo** [comment]
@nyurik 
for this one https://wiki.openstreetmap.org/wiki/Item:Q1833 the P31 statements are also missing.
For when is your bot scheduled to add these missing items?

**Comment by nyurik** [comment]
@sun-geo yes, because [Key:restriction](https://wiki.openstreetmap.org/w/index.php?title=Key:restriction&redirect=no) is a redirect page itself, without even a `{{KeyDescription}}` template.   Once I implement redirect support, it will have it too.

**Comment by sun-geo** [comment]
@nyurik

OK - thanks.
There is another one (i think it is the same issue with redirection) for 
https://wiki.openstreetmap.org/wiki/Item:Q6135 (Tag:building=yes)
I just added again manually the P31-statement at least for DE, see here:
https://wiki.openstreetmap.org/w/index.php?title=Item:Q6135&diff=next&oldid=1839634

So, please revert this edit before you start your upcoming bot, if your bot can't handle these manual update-edits.

**Comment by nyurik** [comment]
update:  all redirects are now automatically added to the data items
