### ISSUE TITLE
shop=money_transfer vs amenity=money_transfer

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6318]
It would be useful to handle `shop=money_transfer`

Maybe with validation rule adding `amenity=money_transfer`? Or replacing `shop=money_transfer` with `amenity=money_transfer`?

Note that `amenity=money_transfer` is in presets and documented at https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmoney_transfer (I just added mention that `shop=money_transfer` exists) but shop=money_transfer is used a bit more often.

Found thanks to https://github.com/osmlab/name-suggestion-index/issues/2598

EDIT: related JOSM preset issue - see https://josm.openstreetmap.de/ticket/17681#ticket

**Comment by bhousel** [comment]
It looks like we already have a deprecation rule to replace `shop=money_transfer` with `amenity=money_transfer`..

https://github.com/openstreetmap/iD/blob/66e4564ae7e490160cae7ea593d2a98aa168548e/data/deprecated.json#L664-L667
