### ISSUE TITLE
Warn if feature mismatches because of geometry

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6319]
Currently `amenity=bank` node used as a building corner is neither treated as a bank nor triggering a validator warning. Currently it results in a bit confusing handling of this situation.

Given that tagging is dubious second is probably preferable.

See https://www.openstreetmap.org/edit?editor=id&node=2065667950#map=19/36.70793/4.03434

![Selection_007](https://user-images.githubusercontent.com/899988/57197201-9775c000-6f64-11e9-89a6-262a67bc6c73.png)

Note difference between BNP Paribas bank and Société Générale bank (displayed with a black dot icon).

Obviously, most of features are unsuitable to be used on a nodes of a building area - banks are not unique and warning may be more general.

**Comment by bhousel** [comment]
Yes, I agree it would be good to warn about situations like this.

**Comment by quincylvania** [comment]
I'm thinking we can make this validation part of "Lines Tagged as Areas" and give it a better name like "Mismatched Geometry".

**Comment by quincylvania** [comment]
> I'm thinking we can make this validation part of "Lines Tagged as Areas" and give it a better name like "Mismatched Geometry".

I did this and added warnings for both points-as-vertices and vertices-as-points.

<img width="492" alt="Screen Shot 2019-09-26 at 10 53 31 AM" src="https://user-images.githubusercontent.com/2046746/65674179-6b122b80-e04c-11e9-9252-11bb16aa842b.png">
<img width="598" alt="Screen Shot 2019-09-26 at 10 53 44 AM" src="https://user-images.githubusercontent.com/2046746/65674187-6e0d1c00-e04c-11e9-81b0-11567d1b7679.png">

**Comment by tordans** [comment]
@quincylvania this looks great.

I wonder, might this be a case for the "Extract" Action as a second link-action (next to the "Ignore this issue")?

From the initial example by matkoniecz at https://preview.ideditor.com/master/#background=Maxar-Premium&disable_features=boundaries&locale=en&map=19.00/36.70793/4.03434&node=2065667950 the extract would be a good way to solve the issue.

<img width="977" alt="Bildschirmfoto 2019-09-28 um 16 33 06" src="https://user-images.githubusercontent.com/111561/65818046-0b637e00-e20e-11e9-8d46-0ee0130a7efe.png">

**Comment by quincylvania** [comment]
> I wonder, might this be a case for the "Extract" Action as a second link-action (next to the "Ignore this issue")?

Yep, good suggestion. This is followup work.

**Comment by quincylvania** [comment]
![extract fix demo](https://user-images.githubusercontent.com/2046746/65981075-a1024600-e478-11e9-8c54-79280052a5af.gif)

**Comment by Lukas458** [comment]
But what is, when the feature has the tags support=wall_mounted and location=outdoor, e. g. a veding machine like this https://www.openstreetmap.org/node/1261048099 ?

Isn't it allowed there to make this feature as a member of a building=*-way? I don't understand why it should not. You can add location=outdoor to denote that the feature isn't in the building.

**Comment by quincylvania** [comment]
@Lukas458 These warnings are based on preset tags. If you're seeing an erroneous warning then we can consider updating the geometry types allowed for the preset in question.

**Comment by Lukas458** [comment]
> @Lukas458 These warnings are based on preset tags. If you're seeing an erroneous warning then we can consider updating the geometry types allowed for the preset in question.

Yes, i think that's what I'd be fine with. I understand sense of those warnings for some presets but still not for vending machines.
