### ISSUE TITLE
noname=yes

### ISSUE THREAD

**Issue by Bibi56** [openstreetmap/iD#6320]
I was willing to had the common noname=yes (300,000 occurrences worldwide) and was very disappointed to see the rare, undocumented validate:no_name=yes (1,000 occurrences worldwide or.... DC wide).
Please propose common tags.
https://taginfo.openstreetmap.org/compare/noname=yes/validate:no_name=yes

**Comment by bhousel** [comment]
I really don't understand what you are asking us to do.. Can you attach a screenshot?

**Comment by Bibi56** [comment]
Today I tried again and when typing nona, noname was correctly proposed.
It must be a slightly different scenario where validate:no_name was proposed. I had to type noname entirely.
As I can't reproduce it I close it.
