### ISSUE TITLE
Complain about blatant duplicates - like amenity=bank nodes with the same name, within 50 meters

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6323]
For start running this check for shops and banks would be nice.

![Selection_008](https://user-images.githubusercontent.com/899988/57209173-b2354c80-6fd7-11e9-9dbf-0efeaea36dc5.png)

(this one was fixed in https://www.openstreetmap.org/changeset/69923368 )

**Comment by andrewharvey** [comment]
To be fair sometimes banks or shops of the same brand really are only 25m.

We'd want to be careful that a new user doesn't see this error/warning and think oh somethings wrong, let's just delete the other one to fix this message, without checking there really is only one on the ground.

**Comment by matkoniecz** [comment]
> To be fair sometimes banks or shops of the same brand really are only 25m apart.

I am curious - can you give an example? It may be next case of cultural differences, but I want to check because I encountered cases where every distributor at fuel station was tagged as `amenity=fuel` or where every teller in bank had own `amenity=bank`.

**Comment by bhousel** [comment]
> I am curious - can you give an example?

There's kind of a running joke about Starbucks's being close to each other.  In NYC it is not that uncommon for them to be across the street from each other (each one mostly serves whatever building it is in).
https://www.quora.com/Where-are-the-two-closest-Starbucks-in-the-world

**Comment by matkoniecz** [comment]
>  quora.com/Where-are-the-two-closest-Starbucks-in-the-world

It mentions two separated by 9 meters. I was not expecting this. Note sure whatever skipping this check of skipping this amenity type would be better.

**Comment by andrewharvey** [comment]
> I am curious - can you give an example?

Two bank branches of the same brand 70m apart
https://www.openstreetmap.org/node/3922986258
https://www.openstreetmap.org/node/20930525

Two pharamcies of the same brand 35m apart
https://www.openstreetmap.org/way/485494532
https://www.openstreetmap.org/way/485452094

**Comment by matkoniecz** [comment]
I guess that it is not going to work as well as I thought
