### ISSUE TITLE
Cannot enter upper case carriageway_ref

### ISSUE THREAD

**Issue by Chaz6** [openstreetmap/iD#6324]
When I try to enter A or B for carriageway_ref it auto changes it to a or b respectively. Example: https://www.openstreetmap.org/way/20003947

**Comment by sun-geo** [comment]
"Cannot enter upper case carriageway_ref"

I can, but it's not so convenient ;-)
![b](https://user-images.githubusercontent.com/47290585/57302361-4b995700-70db-11e9-9a2f-bf9b17712502.gif)

**Comment by sun-geo** [comment]
And when using the preview.editor (new v2.15) 
http://preview.ideditor.com/master/#background=none&disable_features=boundaries&id=w20003947&map=17.00/51.47547/0.26579
it's even more easy ;-) :

![b2](https://user-images.githubusercontent.com/47290585/57302761-34a73480-70dc-11e9-8fda-c1f0d0a5700a.gif)

**Comment by Chaz6** [comment]
Thank you!
