### ISSUE TITLE
Feature disconnected warnings not updated when user creates highways to connect to them

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6335]
To reproduce:
1. Go here: http://preview.ideditor.com/master/#id=w197031752&map=19.00/55.89498/12.53787
2. Add a path connecting the selected pier to the nearby road.
3. Reselect the pier - the `disconnected` warning will still be there.

**Comment by quincylvania** [comment]
This is a cacheing issue. When you connect the line to an existing node in the pier or change the tags on the connected line, the pier isn't considered updated so it's not revalidated. Thanks for the example!
