### ISSUE TITLE
Label field is messed up

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6344]
![Screen Shot 2019-05-10 at 1 37 03 PM](https://user-images.githubusercontent.com/2046746/57545579-c30ff600-7328-11e9-9872-c851b5cd7cbd.png)

**Comment by bhousel** [comment]
This reminds me, we should really add a `man_made=manhole` tag for these.  

I know the wiki doesn't say to, but it's dumb for `manhole=*` to be a toplevel tag, and makes more sense for it to nest under `man_made=*`.

**Comment by rodolv1979** [comment]
Hi @quincylvania and @bhousel, I am taking a look into that. Thanks!

**Comment by rodolv1979** [comment]
Hello @quincylvania, I have a question. As you can see from the attached screenshot, currently under **Label** a `textarea` element is rendered. Is that correct? 
I am seeing that others like **Operator** as well **Reference Code** have `input` elements.
![Screenshot 2019-05-12 at 18 03 01](https://user-images.githubusercontent.com/18237060/57584893-e5e50a80-74e0-11e9-9b2d-964d59280fa3.png)

**Comment by tordans** [comment]
@rodolv1979 I see it as a textarea as well, but it does not look like your screenshot but the one from quincylvania above (Chrome, Mac). It looks like the label-key was added with this preset about 2 years ago as a textarea – https://github.com/openstreetmap/iD/commit/3ebb90a9d278a6c037d6ecd551da071ca2b24043#diff-1373b3b5742f4d2a477bf8d5cc0c6e51R860.

I wonder, what does the label-key stand for? **Maybe it could just be removed.**
- Wiki: Page was deleted; doen't really say why https://wiki.openstreetmap.org/wiki/Key%3Alabel
- Wiki Data Item: https://wiki.openstreetmap.org/wiki/Item:Q366 does not say anything useful.
- ~3,000 x used https://taginfo.openstreetmap.org/keys/label
- The manhole wiki page does not talk about a label either https://wiki.openstreetmap.org/wiki/Key:man_made, not even on the discussion page https://wiki.openstreetmap.org/wiki/Talk:Key:man_made

**Comment by rodolv1979** [comment]
@tordans thank you for your answer. You have right about the screenshot but It is different because I removed the bug (mostly a css job). That is from my local env.   
However, your question is target the main issue here. How it should look like, from an UI and UX point of view. Also the right clickable Info Icon does not work, in practice it does not render any meaningful info.

**Comment by tordans** [comment]
> Also the right clickable Info Icon does not work, in practice it does not render any meaningful info.

You mean it just stays "Label."? That is not a bug. iD just pull https://wiki.openstreetmap.org/wiki/Item:Q366 which does not have good content, yet. – For more on how this works, see https://github.com/openstreetmap/iD/issues/6310#issuecomment-489921050.

**Comment by rodolv1979** [comment]
Ok, I guessed wrongly, thanks for the link. 
I am not so that familiar with this very cool project.

**Comment by quincylvania** [comment]
@rodolv1979 Thanks for looking into this! It was more than just a CSS issue so I just took care of it.
