### ISSUE TITLE
Threshold of checking "Two points in {way} are very close together"

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#6347]
Isn't it better to change the threshold or exclude natural/landuse features to check very close points?
I can't see what's wrong with the mapping below: 
http://preview.ideditor.com/master/#background=gsi.go.jp_seamlessphoto&disable_features=boundaries&id=w681046350&map=20.00/35.68447/139.84926
![](https://i.imgur.com/EDIEhvb.png)
natural=scrub
waterway=riverbank
natural=wetland

**Comment by manfredbrandl** [comment]
See #6292

**Comment by quincylvania** [comment]
These warnings have been useful in my testing precisely because they find very close nodes you can't see at a glance. Try hovering over the issue to see what nodes are affected.

![Screen Shot 2019-05-13 at 9 40 25 AM](https://user-images.githubusercontent.com/2046746/57626119-4026af80-7563-11e9-9a2a-8b92e56fef8e.png)

Let use know if you find locations with false positives, but otherwise I think the warning is working as expected.

**Comment by higa4** [comment]
No. You are not porhibited to connect such close points, but there is not such norm or good practice that such close points (between areas) should be connected. Rather, I prefer disconnecting these points because as mapping become precisely (micro mapping), sometimes there can be seen some small/thin mapping objects between two areas. For example, guard_rail, kerb, manhole, wall, hedge, sidewalk, etc as i raised before in #5132

**Comment by quincylvania** [comment]
@higa4 To be clear, this feature does not connect nodes between different ways, only within ways. The threshold is quite small, currently 20 cm on the surface of the Earth.

**Comment by higa4** [comment]
@quincylvania Sorry, I misunderstood it about different area. But, Even on the same way, I think natural features usually does not have straight line so much. So I still think it's better to exclude the areas of natural features.

**Comment by quincylvania** [comment]
> Even on the same way, I think natural features usually does not have straight line so much. So I still think it's better to exclude the areas of natural features.

Maybe! This is less about straight lines and more about reducing complexity. This will result in smaller data sizes, faster algorithms, and faster rendering for OSM data consumers.

This validation already skip some features don't make sense, namely boundaries and indoor features. Can we just let iD check natural features unless we discover actual problems?

**Comment by higa4** [comment]
I don't know if I understood your wording well (because I'm not a native English speaker), it's OK for now. Thanks for considering.
