### ISSUE TITLE
Tutorial: Buildings: Corners error message

### ISSUE THREAD

**Issue by Zian** [openstreetmap/iD#6353]
Browser: IE11
OS: Windows 10 version 1809
Loaded add-ons: Skype for Business Browser Helper, Lync Click to Call, Send to OneNote, and OneNote Linked Notes

Steps to replicate:
1. Go to https://www.openstreetmap.org
2. Login
3. Edit| iD
4. Start the tutorial
5. Get to the Buildings section
6. Try to digitize a house as shown below
![image](https://user-images.githubusercontent.com/1581929/57590203-0ad87e00-74df-11e9-9b16-43aca4feec6a.png)

Expected Result:
A happy message

Actual Result:
It looks like you had some trouble placing the nodes at the building corners. Try again!

![image](https://user-images.githubusercontent.com/1581929/57590309-cdc0bb80-74df-11e9-8e46-95e886085239.png)

**Comment by bhousel** [comment]
Thanks @Zian .. It does look like your building is probably barely-not-square enough for the squaring tool to fix it.  The message is correct.  If you make your corners a little more square, does it let you on to the next step?

**Comment by Zian** [comment]
Do you think the average user will realize that you intend to run the squaring tool after the initial digitizing? I can't find anything about the tool in the instructions.

**Comment by quincylvania** [comment]
@Zian The user doesn't necessarily have to use the square operation. I think the issue is some of the nodes at the bottom are unexpected.

![Screen Shot 2019-05-13 at 9 31 05 AM](https://user-images.githubusercontent.com/2046746/57625472-e8d40f80-7561-11e9-8403-40a0ea2a18a7.png)

**Comment by Zian** [comment]
Assuming you're right, maybe the message should say that the polygon should have fewer nodes. I'm pretty sure I didn't create any nodes in non-existent corners.

**Comment by quincylvania** [comment]
> I'm pretty sure I didn't create any nodes in non-existent corners.

@Zian Check the corners on the lower right. The light driveway may have created an optical illusion.
