### ISSUE TITLE
Issue fixes can be clicked multiple times

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6354]
There is a small delay between clicking a fix and revalidating issues, meaning the user can apply a fix multiple times by clicking very quickly. This can lead to problems like adding duplicate nodes at way crossings. Ideally we should just get rid of the delay to fix this and to make the UI snappier.

**Comment by bhousel** [comment]
Yes, we should remove the delay usually, but I'd like to leave it at least for the orthogonalization fix, so people can see what the fix is doing.  As a first step, add a variable to `validationIssueFix` to say whether the fix ran, and make sure it can't run twice.

**Comment by quincylvania** [comment]
@bhousel Sounds okay, though a fix is not guaranteed to fix an issue immediately and could run more than once. "Select a feature type" is the only one like this that I can think of at the moment.
