### ISSUE TITLE
Warning when footway crosses tunnel highway

### ISSUE THREAD

**Issue by phiphou** [openstreetmap/iD#6357]
Hi,

Here, [https://www.openstreetmap.org/edit#map=21/48.88758/2.29466](https://www.openstreetmap.org/edit#map=21/48.88758/2.29466), we've got a footway that cross an highway. The highway is tagged as a tunnel. Why this warning ?  

![FireShot Capture 088 - OpenStreetMap - www openstreetmap org](https://user-images.githubusercontent.com/364418/57715959-2fb42900-7678-11e9-8030-1c196bfcc778.png)

**Comment by quincylvania** [comment]
@phiphou It looks like iD is flagging where the footway crosses the pedestrian area, not the tunnel. You can hover over the issue to highlight the related features.
