### ISSUE TITLE
Curb Presets with type dropdown

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6360]
Right now, the curb presets are split is very specific small presets.

I suggest to add the "type" to the preset, so I can easily switch from one preset to the other.
AFAIK once I switch the type, iD will automatically change the preset.
So its just a shortcut to going back to the search and selecting a different kerb.

Also, the preset only has two fields, so adding the `kerb=*` type would not make it too complex.

I found for myself: I select the first one from the search results and only then remember to check if there is one that fits better.

<img width="376" alt="Bildschirmfoto 2019-05-15 um 07 00 27" src="https://user-images.githubusercontent.com/111561/57749819-f4e5db80-76df-11e9-97bf-2d02df3d7bdf.png">

--- 

Off topic (but I did not want to open another issue): **Could the search results be improved?** I see 44 results for "kerb" and "curb" which include quite a lot that are not curbs. Should I create another ticket for this?

<img width="385" alt="Bildschirmfoto 2019-05-15 um 07 00 48" src="https://user-images.githubusercontent.com/111561/57749832-fd3e1680-76df-11e9-8138-dbfcb57fb623.png">

**Comment by quincylvania** [comment]
@tordans Sounds good. I generally like to hide fields with untranslated tags where possible, but I agree in this case it's convenient to be able to switch curb types quickly.

Search can always be improved 😅. In this case I'm fine the results since the top five are indeed the most relevant.
