### ISSUE TITLE
Prefer Wikidata SVG logos over social media icons for brand presets

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6361]
When a brand entry in the name-suggestion-index has an SVG image as its Wikidata logo, prefer that image over any Facebook or Twitter logo.

Official Facebook and Twitter accounts are not always as reliable as Wikidata items for brand logos. A brand may adopt a non-logo as its social media photo as part of a marketing campaign. However effective the marketing message may be in the context of a social media profile, it’s simply jarring when it appears in iD preset search results, where the user isn’t expecting an advertising message.

<img src="https://user-images.githubusercontent.com/1231218/57750257-6731ce00-7696-11e9-99ad-96d6f9761e7f.png" width="400" alt="KFC search">
<img src="https://user-images.githubusercontent.com/1231218/57750263-6d27af00-7696-11e9-8f47-182f9e8bce39.png" width="264" alt="KFC name-suggestion-index">

_Wikidata on the left._

Here, the SVG logo from Wikidata is much more recognizable than the profile picture KFC is currently displaying on Facebook and Twitter, which is meant to be viewed in the context of a larger profile cover photo. As I understand it, the point of putting these icons in the search results is to increase the presets’ recognizability.

KFC’s marketing campaign may be ephemeral, but some brands choose social media photos that are still less recognizable than a logo would be:

<img src="https://user-images.githubusercontent.com/1231218/57750390-ee7f4180-7696-11e9-86d1-cc089c2a218f.png" width="294" alt="In-N-Out name-suggestion-index">

This isn’t to say that logos in Wikidata are always the most suitable for iD. But most of the time, an image from Wikidata would be unsuitable because it’s a photo of a store location or a very wide logo. To mitigate these issues, we could keep the current behavior whenever the Wikidata logo has an illegible aspect ratio like 1:6 or wider, or when the Wikidata logo is a JPEG or PNG.

https://github.com/openstreetmap/iD/blob/ddc9d16b62c2e84f3d3716bbcca01930686052ca/build_data.js#L253-L260

**Comment by bhousel** [comment]
For the record, I see absolutely nothing wrong with this 😆
<img width="214" alt="Screenshot 2019-05-15 09 53 49" src="https://user-images.githubusercontent.com/38784/57781023-5c5b5580-76f7-11e9-90d3-67561160a4f5.png">

**Comment by bhousel** [comment]
ok.. So I did this, and it didn't work as well as I had hoped..
The main problem is that these wiki commons logos are often really not square.  I left the code in `build_data.js` commented out for now, because it was producing noticeably worse results.

commons:
<img width="363" alt="Screenshot 2019-05-17 00 53 30" src="https://user-images.githubusercontent.com/38784/57903939-98e59900-783e-11e9-9ae5-1fbdfbca6e71.png">

facebook:
<img width="358" alt="Screenshot 2019-05-17 00 59 07" src="https://user-images.githubusercontent.com/38784/57904012-00034d80-783f-11e9-83c8-402d7a773a05.png">

**Comment by matkoniecz** [comment]
Is non squareness sole problem or is it worse?

**Comment by bhousel** [comment]
> Is non squareness sole problem or is it worse?

That's the sole problem.  They just don't look good in the space where we are using them, in the way that a profile picture would..

**Comment by matkoniecz** [comment]
Is allowing only relatively square ones too complicated or is it just case "someone needs to code it"?

**Comment by BjornRasmussen** [comment]
> Is allowing only relatively square ones too complicated or is it just case "someone needs to code it"?

Currently, iD only flags buildings if they are very close to being square (some corners are almost 90°), don't have too many nodes, and aren't connected to other buildings.  A triangular building, for example, would not be flagged

**Comment by bhousel** [comment]
> Is allowing only relatively square ones too complicated or is it just case "someone needs to code it"?

We'd need to fetch the images to determine their dimensions.  
Also they can change at any time, and I wouldn't expect the Wikipedia folks to change all their logos to accommodate iD.  I understand the appeal of using Wikipedia commons logos, but it really feels like a dead-end to me.

**Comment by bhousel** [comment]
> Currently, iD only flags buildings if they are very close to being square (some corners are almost 90°), don't have too many nodes, and aren't connected to other buildings. A triangular building, for example, would not be flagged

This issue isn't about buildings - it's about logos.  😆 

But for the record.. iD can detect and square triangular buildings just fine 👍 
![triangular building](https://user-images.githubusercontent.com/38784/57950414-28c62a00-78b5-11e9-9cfe-b92feaa5e474.gif)

**Comment by BjornRasmussen** [comment]
Yikes!  I confused two issues I've been following - plus I'm used to people not understanding the square validation.
I meant above that a triangle with only 60° angles won't get turned into a square.

**Comment by 1ec5** [comment]
We do have some triangular logos in the index, but thankfully they’re encased in rectangular images. 😉

> We'd need to fetch the images to determine their dimensions.

The Wikimedia Commons API can fetch file metadata in bulk without fetching individual images: osmlab/name-suggestion-index#2641.

**Comment by 1ec5** [comment]
KFC is back to being… less buff… but now Burger King has joined in on the fun: osmlab/name-suggestion-index#2798.
