### ISSUE TITLE
Building crosses highway validation rule should check layer=*

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/iD#6364]
The intersection of a [highway=footway](https://www.openstreetmap.org/way/545473798) with a [building=roof + layer=1](https://www.openstreetmap.org/way/219815184) is flagged by the validator. The validator suggests to use a bridge or tunnel.

![buildingsense](https://user-images.githubusercontent.com/3611273/57769097-58d2c900-770d-11e9-8ac6-277ad25b7f4c.png)

That' wrong. If it were a normal building, not a roof, `tunnel=building_passage` were correct in **some** circumstances except indoor mapping (you don't want to have `tunnel=yes` added to any indoor footway).

The simplest and IMHO most sensible approach is to check if both objects are on the same `layer=*` (defaults to 0 in OSM). In the example given above, the roof has `layer=1` and therefore there is no reason to complain.

**Comment by BjornRasmussen** [comment]
I agree with you about this, but @quincylvania has set up the validation such that adding `covered=yes` to the highway underneath will satisfy the validator.  This same issue keeps coming up from mappers unaware of this behavior, so clearly we need to add a covered option to the list of fixes to prevent the mistagging of a large number of features.  I consider either understanding the layer tag or letting people know about using covered a big priority for v2.15.0 if we don't want people to be opening new issues and mistagging features all summer long.

**Comment by quincylvania** [comment]
I agree we need to make this easier soon. I almost always skip mapping or fixing these instances myself because it takes too many clicks.

**Comment by bhousel** [comment]
> I agree we need to make this easier soon. I almost always skip mapping or fixing these instances myself because it takes too many clicks.

Strong agree - @quincylvania can you just add a fix like "Tag the highway as covered" and just close all the open issues related to this?  👍

**Comment by bhousel** [comment]
This is a dup of #5924 where we already decided that we're not going to expect data consumers to know what levels building footprints exist at or guess at the default building levels that certain building types tend to exist at.

**Comment by BjornRasmussen** [comment]
> This is a dup of #5924 where we already decided that we're not going to expect data consumers to know what levels building footprints exist at or guess at the default building levels that certain building types tend to exist at.

Yes, but this asks for layer, not level
