### ISSUE TITLE
allow natural=bay on lines

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6379]
See for example https://www.openstreetmap.org/way/561794024#map=9/60.3392/6.2897

Triggered by https://github.com/gravitystorm/openstreetmap-carto/pull/3754

> However, there are almost 400 bays mapped as linear ways, especially in areas with fjords such as Norway, Greenland and Chile. Many of these bays are long, narrow and curving, so it is reasonable that some mappers like to map these as linear ways.

Wiki was changed in https://wiki.openstreetmap.org/w/index.php?title=Tag:natural%3Dbay&diff=1727691&oldid=1696854 on 21 December 2018 (and I agree with that change)

Equivalent JOSM issue: https://josm.openstreetmap.de/ticket/17727 (implemented)

**Comment by bhousel** [comment]
This is ok, but it means bays mapped as areas will now get `area=yes`.

**Comment by matkoniecz** [comment]
What about existing bay mapped as areas without `area=yes`? Will it cause problems?

Maybe for workaround for iD design here it would be OK to have two entries - `natural=bay` as line and `natural=bay` as an area?

**Comment by bhousel** [comment]
> What about existing `natural=bay` mapped as areas without `area=yes`? Will it cause problems?

It will probably cause problems for someone (as any change in the geometry rules will), but not for iD.
