### ISSUE TITLE
Mapillary shows less sequences in preview.ideditor?

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6382]
The preview-version shows less Mapillary sequences.

Is this a bug or a feature? I don't remember something like a "only show most recent mapillary images in iD"-default-filter, so I guess its a bug?

**Details:**

For http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&locale=en&map=18.00/52.47275/13.44729&photo_overlay=mapillary

=> Only one sequence

<img width="396" alt="Bildschirmfoto 2019-05-18 um 07 31 16" src="https://user-images.githubusercontent.com/111561/57965086-8d2dcb80-793f-11e9-84ef-13cf7f48b176.png">

For https://www.openstreetmap.org/edit#map=18/52.47275/13.44779

=> Many sequences

![Bildschirmfoto 2019-05-18 um 07 35 04](https://user-images.githubusercontent.com/111561/57965101-b8181f80-793f-11e9-9751-f49f43953a0f.png)

For https://www.mapillary.com/app/user/tordans?lat=52.4727519214901&lng=13.447678669338757&z=17.61692366536272&focus=map

=> Many sequences

<img width="591" alt="Bildschirmfoto 2019-05-18 um 07 31 53" src="https://user-images.githubusercontent.com/111561/57965096-afbfe480-793f-11e9-9cef-54cf1ed1dbb3.png">

**Comment by sun-geo** [comment]
This is a interesting behavior which could actually lead to a real feature.
I recently did a mapping for a highway (motorway) section, for which there was a really high density of Mapillary and OpenStreeCam data available. It took me a while to find one of freshest suitable data. So for this case I would like to have a check-box:
_"show only young (maybe 1 year or 2 year old) Mapillary picture tracks/sequences"_

What do you think about this kind of filter function?

**Comment by quincylvania** [comment]
> for this case I would like to have a check-box:
"show only young (maybe 1 year or 2 year old) Mapillary picture tracks/sequences"

@sun-geo This is #4518, which I agree is a good idea but is unrelated to this bug.

**Comment by quincylvania** [comment]
@tordans Thanks for finding this!
