### ISSUE TITLE
Validator, current view and Issue tab

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/iD#6384]
http://localhost:8080/#background=Bing&disable_features=boundaries&id=w4305413655&map=19.00/40.56751/-74.68305  (dev instance)

When I hover over the warning message "Sunset Motel has unsquare corners", none of the objects are highlighted.

![htl](https://user-images.githubusercontent.com/5842757/57969901-da7b5e80-797a-11e9-92d6-3c77d0e46768.png)

With transparent background, you can see that the motel was in fact hiding behind the "Issues" tab:

![htl2](https://user-images.githubusercontent.com/5842757/57970005-1236d600-797c-11e9-9351-872e04aff1db.png)

Somehow, the current view calculation doesn't take the issues tab into account and assumes all objects to be visible nonetheless. The left tabstrip works as expected here.

**Comment by BjornRasmussen** [comment]
Clicking an issue in the sidebar won't center that issue for some reason.  Clicking on an issue in the inspector on the left does center the issue though.
Whatever happens when you click the issue in the inspector should happen when you click it in the issues pane
