### ISSUE TITLE
This church has the wrong label

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#6388]
http://preview.ideditor.com/master/#background=Mapbox&disable_features=boundaries&id=n357746007&map=20.76/40.56727/-74.63485&offset=5.16,-2.98

<img width="813" alt="Screenshot 2019-05-18 21 48 44" src="https://user-images.githubusercontent.com/38784/57976782-c2c1cb80-79b6-11e9-9079-52db615bd919.png">

**Comment by mmd-osm** [comment]
Those are 2 nodes at exactly the same location, only one of them has the "historical" suffix.

https://www.openstreetmap.org/node/357746012
https://www.openstreetmap.org/node/357746007

**Comment by bhousel** [comment]
Thank you @mmd-osm !!   That was driving me nuts.

**Comment by quincylvania** [comment]
@bhousel Can we close this?

**Comment by bhousel** [comment]
Yes, sorry!  I forgot to.

**Comment by mmd-osm** [comment]
What about the rendering vs. object selection thing? Is there some obvious reason why they differ in this case?

**Comment by bhousel** [comment]
> What about the rendering vs. object selection thing? Is there some obvious reason why they differ in this case?

The markers are sorted by latitude, so if they are coincident we don't really know which one with be drawn.

The labels aren't sorted, but they get inserted into a collision index in whatever order they happen to be in, and this will depend on whatever is already in the index and whether the name is short enough to not cause a collision.

So, I'm considering both these things to be nondeterministic for coincident points.  We could probably adjust the sort functions in both places to decide what happens in that situation, but I don't think it's important enough to change now.

**Comment by mmd-osm** [comment]
By the way, Keep right! has an option to report multiple nodes on the same spot: 
https://www.keepright.at/report_map.php?zoom=19&lat=40.56737&lon=-74.63466&layers=B0T&ch=0%2C20&show_ign=1&show_tmpign=1

**Comment by quincylvania** [comment]
> Keep right! has an option to report multiple nodes on the same spot

Neat! We should probably add this to iD's native validator. Possibly as part of "Very Close Points".
