### ISSUE TITLE
Issue with Imagery for quite some time

### ISSUE THREAD

**Issue by ibuddy66** [openstreetmap/iD#6390]
Imagery around the upstate, NY area in particular throughout Monroe County, New York State, USA is severely outdated in all levels of imagery.  In particular, mapbox satellite is highly outdated here, Esri is also outdated here.  I have been using the other report sections to report this for well over a year now.  Even though the imagery seems to be updated in other places such as their own systems of the above mentioned imagery layers, this imagery in ID is not updated to a more current time frame.   In particular ESRI clarity and Mapbox are very important here for visibility when editing as the bing layers are horrific as far as visibility here.   I am unsure how else to report this or what else to do at this point, but it is to a major fault for the area because it is many years old now.  I also am not savvy enough to add in the different imagery code, etc. as I am not a coder.

**Comment by bhousel** [comment]
Thanks for reporting @ibuddy66 .. There isn't really anything we can do about this on the iD side, we just use whatever imagery is available to us.  If you know of a better source, we can add it to the [editor-layer-index](https://github.com/osmlab/editor-layer-index) project.

I did take a look around this area and it luckily NY State makes their orthos available to the public.  If you use the "NYS Orthos Online" source, you can see some imagery from 2017.  This is pretty recent!

For comparisons, I've been looking around [Seneca Park Zoo here](http://preview.ideditor.com/master/#background=orthos.dhses.ny.gov_latest&disable_features=boundaries&map=17.97/43.20706/-77.62245) which has been doing a lot of construction the past few years.
