### ISSUE TITLE
Validator: highway=incline_steep

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6392]
Location: http://preview.ideditor.com/master/#background=EsriWorldImagery&disable_features=boundaries&id=n290635120&map=19.00/50.81794/6.34606

Suggested change:
- highway=incline_steep
+ highway=road
+ incline=up

I wonder, if the highway-tag is really needed here since the way is usually already a highway.

The wiki also just talks about the incline key, not the highway key: https://wiki.openstreetmap.org/wiki/Tag:highway%3Dincline

Btw, its really just used on nodes https://taginfo.openstreetmap.org/tags/highway=incline_steep

I could not find anything about it in the git history about the story behind this.

**Comment by bhousel** [comment]
`highway=incline_steep` is [only used 669 times](https://taginfo.openstreetmap.org/tags/highway=incline_steep).  
Instead of us doing anything... why not just change it with JOSM or level0?

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dincline

**Comment by quincylvania** [comment]
@tordans I added this way back when building up the deprecation list. I assumed it was used on lines, but apparently not! iD's validator can't really handle this scenario so I removed it from the deprecation list altogether. Like Bryan said, people can use other tools.
