### ISSUE TITLE
Pipeline valve preset

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#6393]
Hello

Currently, iD shows no particular preset for pipeline valves despite some can be seen on ground.
https://www.openstreetmap.org/node/6448156547

See https://wiki.openstreetmap.org/wiki/Tag:pipeline=valve
At least valve, location, operator, actuator and handle should be available.

You'll find a simple icon I've designed (CC BY-SA-NC) which corresponds to any valve with handle (actuator or handle+actuator) are also available
[vanne_handle.zip](https://github.com/openstreetmap/iD/files/3195293/vanne_handle.zip)

Thanks in advance to take care of this issue.

**Comment by bhousel** [comment]
Sounds like a good suggestion, thanks!

I'll probably just redraw the icon - I only really use public domain icons in the project for simplicity.
(also FontAwesome, which is CC-BY-SA but we credit them in a few places).

**Comment by flacombe** [comment]
Ok no problem, you can redraw it.
Mine doesn't follow ususal iD design guidelines anyway.

**Comment by quincylvania** [comment]
I went ahead and added this without an icon. We can add the icon as soon as we find or draw a suitable one.

**Comment by flacombe** [comment]
Hi

On iD 2.15.4, a node with pipeline=valve won't get any preset despite commit b2d406d
Is there any additional action to do for that?

**Comment by quincylvania** [comment]
@flacombe To match the preset, the feature must also:

- Have `man_made=pipeline`
- Be part of a way (presumably a pipeline)

**Comment by flacombe** [comment]
> Have man_made=pipeline

This is where I got lost
pipeline=valve doesn't expect man_made=pipeline, because man_made=pipeline is on the way the valve should be member of.
https://wiki.openstreetmap.org/wiki/Tag:pipeline%3Dvalve

**Comment by quincylvania** [comment]
iD is following the advice of the wiki here. This makes sense since `pipeline` isn't a top-level key.

<img width="234" alt="Screen Shot 2019-08-20 at 4 37 57 PM" src="https://user-images.githubusercontent.com/2046746/63386564-02f36a00-c369-11e9-90cc-cbf9540c68e9.png">

See https://wiki.openstreetmap.org/wiki/Key:pipeline:

>    See also: man_made=pipeline
>
> Tags within this key further describe features on or related to pipelines.

**Comment by flacombe** [comment]
Indeed, that's right... and probably a mistake due to dataitems bot edits.
Last bot dance add P22 property with man_made=pipeline without any justification.
https://wiki.openstreetmap.org/w/index.php?title=Item%3AQ4978&type=revision&diff=1832281&oldid=1783550

I've edited the item to remove it, valves never expect man_made=pipeline, this was never proposed nor reviewed, sorry for mistake and noise.

**Comment by flacombe** [comment]
Hi all

I confirm that man_made=pipeline isn't required on pipeline=valve objects.
Could you consider updating the preset in id please?

**Comment by quincylvania** [comment]
@flacombe Okay, I did this. I'm not sure I like how `pipeline` is used as a top-level tag but if this is the OSM tagging then iD will support that ✌️

**Comment by flacombe** [comment]
Thanks

This is indeed reviewed tagging
Pipeline is "top level" key for valves, surge tanks, substations and proposed for disusage marker. There will be a proposal for pumps as well.
This is just like power or waterways IMHO.
