### ISSUE TITLE
Valid error? "Aerialway should be a closed area" error

### ISSUE THREAD

**Issue by DFyson** [openstreetmap/iD#6395]
For some reason when tagging a line with "[aerialway=](https://wiki.openstreetmap.org/wiki/Aerialway)" (eg aerialway=zip_line), an error comes up "Aerialway should be a closed area based on the tag "aerialway="; Connect the end"

This error doesn't make sense since arialways should be an open way.

**Comment by bhousel** [comment]
Can you share a location / way id where you are seeing this warning?
I just tried adding a `aerialway=zip_line` and I don't see a warning like that..

**Comment by quincylvania** [comment]
This appears on osm.org since iD 2.14.3 doesn't know about `aerialway=zip_line`.

@DFyson This has been fixed and will be in the next release of iD!

![Screen Shot 2019-05-21 at 8 43 05 AM](https://user-images.githubusercontent.com/2046746/58097373-36293000-7ba5-11e9-848d-072ab30c7ef6.png)
