### ISSUE TITLE
Phone numbers should be valid on businesses inside converted houses

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6404]
A house that has been converted to a law office would be tagged `building=house` `office=lawyer` and would ideally be tagged with a phone number. But the validator flags the phone number as being a potential privacy violation:

<img src="https://user-images.githubusercontent.com/1231218/58131961-eb271100-7bd4-11e9-91b4-1d5628b715c7.png" width="399" alt="personal">

Per https://github.com/openstreetmap/iD/issues/5850#issuecomment-475033614, there is logic to exempt features with certain keys. Any business-specific key like `office`, `brand`, or `website` should be added to that heuristic. (Regarding `website`, self-hosted personal homepages are less common these days, so I figure it’s more likely to indicate the presence of a business.)

**Comment by bhousel** [comment]
Oh yeah, I've seen this a few times too.  Usually I end up just changing the building type to - not one of these:
https://github.com/openstreetmap/iD/blob/d4d78b408154b4c32b21987d8f48fc673c5c17e1/modules/validations/private_data.js#L10-L18

**Comment by quincylvania** [comment]
iD won't flag residential buildings that are also one of these tags, so we can just add `office` to this list.

https://github.com/openstreetmap/iD/blob/d4d78b408154b4c32b21987d8f48fc673c5c17e1/modules/validations/private_data.js#L20-L28

**Comment by 1ec5** [comment]
>  Usually I end up just changing the building type to - not one of these

`building=house` is correct tagging – it remains architecturally a house – though `building:use` could be set to something else like `commercial`.
