### ISSUE TITLE
Add "Greenway" as a search term for "Cycle and Foot Path"

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6406]
As far as I can tell, this is the iD preset equivilant to greenways, so it would be good to ensure that people adding a greenway tag it correctly.

**Comment by gogo25171** [comment]
Voici comment on peut avoir ce type de panneau.
Et voici les caractéristiques de cette voie https://fr.wikipedia.org/wiki/Voie_verte par rapport au voie t-elle que les trottoir, bande cyclable où autre.

![111-IMG_2308_min](https://github.com/openstreetmap/iD/assets/31017668/c1d343ab-d41d-480b-ac5e-c79f1f91c061)
