### ISSUE TITLE
Applying validation fix deletes latest added tag via raw tag editor

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/iD#6407]
To reproduce:

* Open iD.
* Create a new point, select the basic preset "Point".
* Open raw tag editor.
* Add `amenity=dentist`.
* Add `name=Test` (or any other string as name).
* optional (does not have any influence on behaviour): Press tab, enter or click into any input field of the doctor preset (e.g. opening hours)
* Validation warning pops up, click on "update properties".
* The name disappears from raw tag list. This is the bug.

It happens with some other tags (description, note, …) as well but I haven't figured out which.

Firefox 66.0.5 amd64 for Ubuntu 16.04

**Comment by bhousel** [comment]
Thanks for reporting @Nakaner .. I've pushed a fix which should resolve the problem for this validation rule, but I'm going to check all the rules to see whether others would have the same problem.

**Comment by bhousel** [comment]
This was done!  For a few rules which manipulated tags, we needed to make sure to use the current tags at time of fix, not reuse previous tags at time of detection.

**Comment by bhousel** [comment]
> This was done! For a few rules which manipulated tags, we needed to make sure to use the current tags at time of fix, not reuse previous tags at time of detection.

149a0b43b 2019-05-23 Use latest entity at time of fix for private_data validation too 
5440467db 2019-05-23 Undo 5b8db55b4 and instead get latest entity at time of fix
