### ISSUE TITLE
Warn when changing a name to the wrong name

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6411]
The title sounds amazingly infeasible, but hear me out.

Every once in a while, a local mapper gets frustrated that armchair mappers from elsewhere keep changing a road name to something it shouldn’t be. Perhaps the street-level imagery is outdated or misleading or an official source like TIGER is simply incorrect. The local mapper can tag the road with [`not:name`](https://wiki.openstreetmap.org/wiki/Key:not:name) (optionally with [`not:name:note`](https://taginfo.openstreetmap.org/keys/not:name:note) or [`source:not:name`](https://taginfo.openstreetmap.org/keys/source%3Anot%3Aname)). If an armchair mapper later comes along changing `name` to the same value as `not:name`, iD should issue a validation warning.

There are [some other `not:*` tags](https://taginfo.openstreetmap.org/search?q=not%3A) too.

**Comment by 1ec5** [comment]
@jleedev gave an example of [this road](https://www.openstreetmap.org/way/456793503), which was changed to the same misspelling on [two](https://www.openstreetmap.org/changeset/65119981) [separate](https://www.openstreetmap.org/changeset/65113240) occasions.

**Comment by 1ec5** [comment]
[This POI](https://www.openstreetmap.org/node/3648453571) has two names in `not:name`. Changing `name` to either or both of them should result in a warning.

**Comment by quincylvania** [comment]
@1ec5 Interesting. I do think iD should honor semicolon-separated `not:name` values for this validation.

**Comment by quincylvania** [comment]
@1ec5 Is there consensus on how to tag incorrect names in different languages? I see a little usage of `not:name:cy` and `not:name:en`, but are these supposed to map only to `name:cy` and `name:en`? Or if a value in `not:name` equals `name:de`, should iD issue a warning?

I think I'd prefer the latter, so all incorrect names in all languages go in `not:name`. This could lead to some edge cases, but iD already has a field for `not:name`.

**Comment by 1ec5** [comment]
In general, `not:x` should only apply to `x`, and subkeys `not:x:y` should only apply to `x:y`, not `x:z` or `x`. A namespace is just that, not a specific variation of the namespaced key.

Imagine a situation where mappers feel the need to clarify that the Spanish name of a place is not the same as the local name (which happens to be in English). This seems like quite a corner case, so I guess we can wait and see if iD’s use of `not:name` for all languages happens to cause any problems.

**Comment by quincylvania** [comment]
@1ec5 Hmm I see your point about not crossing namespaces. Might have to re-evaluate this.
