### ISSUE TITLE
Using "Crosswalk" for highway=crossing in UI is US-centric

### ISSUE THREAD

**Issue by eliotb** [openstreetmap/iD#6413]
I'm in New Zealand, browser preferred language British english.

highway=crossing is 'translated' to Crosswalk in the feature editor and in the issues list.
I don't know how to tell if I'm seeing a US specific translation, or if this is the general English  label?  

I suggest "Crossing"  is a more universal name for these things. As used in the wiki.
or "Pedestrian Crossing" for GB, NZ and probably others if this is an option...

**Comment by bhousel** [comment]
Thanks for letting us know, @eliotb 👍 
We have both `en_GB` and `en_AU` localizations available for iD. 
I've replaced "Crosswalk" with "Crossing" in these localizations.  
(The change will go live for everyone next time we release a version of iD, but you should be able to preview it within an hour or so on our preview site at http://preview.ideditor.com/master/  )

If you see anything else that looks odd, you can sign up for an account on Transifex and make improvements yourself.  We're always looking for help with this!  The link to the iD localizations is below:
https://www.transifex.com/openstreetmap/id-editor/languages/

**Comment by eliotb** [comment]
@bhousel Thanks for the pointer. I joined transifex and applied to id-editor for en_AU (also would look at en_GB and es)
