### ISSUE TITLE
Extra autocomplete popups appearing in Chrome

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6414]
second layer with label "designated"over combo-box for bicycles (eg when using barrier=bollard tag), see:
![bicycle bollard](https://user-images.githubusercontent.com/47290585/58221172-e3b95200-7d11-11e9-9c4a-67b7d9071d41.gif)

**Comment by BjornRasmussen** [comment]
Chrome creates a list of recent entries on top of iD's list, so something is needed here to override Google Chrome

**Comment by sun-geo** [comment]
I can agree, it doesn't happened using Firefox. For the movie/screenshot sequence i used Chromium.

**Comment by quincylvania** [comment]
Related: #5818

**Comment by quincylvania** [comment]
It looks like inputs without an `id` attribute don't get autofilled like this, so I removed them for these inputs. Let us know if this issue reappears anywhere!

**Comment by sun-geo** [comment]
I just checked barrier=bollard and bicycles. The "designated" doesn't appears anymore.

Seems solved.
:-)
Thank you
