### ISSUE TITLE
complain where wikipedia tag is used instead of correct brand:wikipedia (or wikidata instead of brand:wikidata)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6416]
For example see https://www.openstreetmap.org/node/6489549531

`wikidata=Q1689380`, `wikipedia-en:Jimmy John's` originally used was incorrect, `brand:wikidata=Q1689380`, `brand:wikipedia-en:Jimmy John's` are preferable in such case

In general any wikidata id from https://github.com/osmlab/name-suggestion-index and any wikipedia page linked to such id can be never correctly used in `wikidata` and `wikipedia` tag and switching to `brand:wikipedia`/`brand:wikidata` is always a good edit.

It would be a good idea to have autofix encouraging to swap such tags to ones with `brand:` prefixed.

In principle it would be easy to generate deprecation rules and add them to https://github.com/openstreetmap/iD/blob/master/data/deprecated.json (and I can do that) but it would be preferable to generate them dynamically from nane-suggestion-index that is anyway used in iD

Note that associated `wikipedia` also should be moved to `brand:wikipedia`

**Comment by 1ec5** [comment]
The only exceptions I can think of would be features tagged with `office=company` or `office=financial` (for a bank brand), which are more likely to be the headquarters.

There are additional cases where `wikidata` should become `operator:wikidata`, but that’s more difficult for us to detect than cases that should be `brand:wikidata`.

**Comment by matkoniecz** [comment]
> The only exceptions I can think of would be features tagged with office=company or office=financial (for a bank brand), which are more likely to be the headquarters.

In this case `wikidata` and `wikipedia` is also incorrect (name-suggestion-index should contain links to articles/entries about companies, not about buildings)

**Comment by 1ec5** [comment]
What I meant is that a particular chain’s locations are all tagged with `brand:wikidata=Q123`, but its head office may be tagged `wikidata=Q123`, consistent with how company headquarters in general are often tagged with the company’s QID.

**Comment by matkoniecz** [comment]
> its head office may be tagged `wikidata=Q123`

I would argue that it is incorrect in exactly the same way as tagging as individual shops with `wikidata` (or `wikipedia`) would be in case where linked article/entry describes company rather than specific shop or specific office.
