### ISSUE TITLE
Issues not cleared by corrective action

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#6419]
I added an area.  Before I chose a preset I moved one of the vertices (a hard habit to break because I tend to fix things like that as I notice them).  This, as of 2.14.x made it choose the area preset and flag an issue.  So I set it as a building.  Issue didn't clear.  Change the reporting from "Everything" to "My Edits."  That cleared it.  Switched back to "Everything" and it was still clear.

**Comment by eehpcm** [comment]
Ho hum.  At the moment of writing, the Heisenbug I raised in #6417 isn't misbehaving.  Nor is this bug.  The issues flag gets cleared when I set the building tag on an area.

Looks like they may be related.

**Comment by quincylvania** [comment]
@eehpcm Okay, it makes sense that if iD is acting slow and buggy then stuff like this could break too. Closing this so we can focus on the other issue.

**Comment by bhousel** [comment]
yeah I was going to say, I can imagine this being related to #6407 but a little different.
