### ISSUE TITLE
Display mofa moped motorcycle on barrier.

### ISSUE THREAD

**Issue by AllroadsNL** [openstreetmap/iD#6420]
Every transportation mode have the right of good routing possibilities in OSM, I think.
But when editors do not mention them, this is very negative for these transportation mode in routing.
It is counter productive, multiplied by a factor x.

As people forget, did not get the hint, to set the tags correct for these transportation modes.
Common failure, hint set "Motor Vehicle"motor_vehicle, so it is set motor_vehicle=no because they can do it in the editor. Thinking about double_tracked_motor_vehicle. 

OSM Tag motor_vehicle also include mofa, moped, motorcycle. the single_tracked_motor_vehicle transportation modes.
If it was mentioned, people think.

As the editor layout is now,

> ![bicycle bollard](https://user-images.githubusercontent.com/47290585/58221172-e3b95200-7d11-11e9-9c4a-67b7d9071d41.gif)

The effect is that, this is a big disadvantage for these transportation modes. And should be avoided.
There is a minority of these transportation mode active on OSM. This minority get more, more work, to set it correct.

A editor must not facilitate that, must make a good play field.

> <img alt="screenshot 2017-09-13 08 55 11" width="701" src="https://user-images.githubusercontent.com/38784/30378463-485f02e6-9861-11e7-91c0-3297bc357e44.png">

A other point related:
Motor Vehicle is in the layout, is translated to languages, for example Dutch," Motorvoertuigen", this means in that country, by law, that mofa and moped are excluced. When a Dutch tagger do it right, click "Motorvoertuigen", then motor_vehicle is set, what is not correct.
These keys are needed, mofa, motorcycle, moped.

The "Motor Vehicle" must be set at the bottom of the list, it is a collection of transportation modes.

Why horses, the others are equally important. "mofa, motorcycle, moped"

**Comment by bhousel** [comment]
Thanks for the suggestion - this is #3945 
Access tags in OSM are.. really something.  

When we are finally ready to tackle this issue, all I can promise is that we will do our best to support [some of what is here](https://wiki.openstreetmap.org/wiki/Key:access) but we will probably not get it all.

**Comment by AllroadsNL** [comment]
I searched for moped and mofa and there was no related issue of this kind, that why a new issue.

"Some of what is here"

Ongoing thoughts. Be prepared!

About the access hierachy, the heirachy is not complete:
key motorcar use in OSM, motorcar is not a motorcycle. At parkings theis shiedls only for personalcar (motorcar OSM, side symbol motorcar)

The misunderstanding of motor_vehicle key.
The use of opposite tagging ( devalue) for other transportion modes, =yes, which gives 
Therefore the missing of a key like double_tracked_motor_vehicle, which express exactly, what is written by law, visualise a traffic_sign. C6, no need for the other =yes keys. "motorvoertuigen op meer dan twee wielen" more than 2 wheels other countries write 2 tracks. (front image car, as already avisual OSM icon at double_tracked, access page)

[NL:Overzicht_Nederlandse_Verkeersborden#C:_Geslotenverklaring](https://wiki.openstreetmap.org/wiki/NL:Overzicht_Nederlandse_Verkeersborden#C:_Geslotenverklaring)

motor_vehicle=no & motorcycle=yes & moped=yes & mofa=yes & traffic_sign=NL:C6
 
THIS ! is where mofa, moped and motorcycle have also a "disadvantage".
People forget to set =yes to devalue.

Devaluing must be stopped. It is not a good working method.

And when there is double_tracked, there is single_tracked_motor_vehicle. (not used in law often)

Also there rules at traffic_sign, that writes:

"gehandicaptenvoertuigen" disabled_vehicle
"gehandicaptenvoertuigen zonder motor" disabled_non_ motor_vehicle, opposite is disabled_motor_vehicle.
"gehandicaptenvoertuigen met in werking zijnde motor" with working motor, when motor not in use, they could.

I am thinking about introduction of double_tracked_motor_vehicle or simple dt_motor_vehicle.
To make the access hierarchy complete and more preset workable (devaluing). Therefore the traffic-sign table must be correct. Above link.
To solve the failure use of motorcar. (is not a motorcycle)
To express motorcar (personal car ) correctly.
So directly as possible translation of a traffic_sign.

This have a big impact on routing systems, the use of a new tag.
A big step. Struggling to make the step.
