### ISSUE TITLE
validation - when clicking on an issue - not centred

### ISSUE THREAD

**Issue by tastrax** [openstreetmap/iD#6424]
Issue identified so click to find it
![Issue1](https://user-images.githubusercontent.com/8775395/58321260-09a13c80-7e61-11e9-92c1-01c2490fde16.JPG)

Result

![Issue2](https://user-images.githubusercontent.com/8775395/58321270-11f97780-7e61-11e9-97f0-313486f80223.JPG)

**Comment by Nakaner** [comment]
Is it a relation? Click on "view on openstreetmap.org" to find out.

**Comment by tastrax** [comment]
Not in a relation

https://www.openstreetmap.org/edit?editor=id#map=18/-8.25802/125.60750

**Comment by tastrax** [comment]
Zoom out to 400 metres then click on 'Kiosk has the suspicious name "Kios"' and it fails to centre - object hidden under panel on LHS

**Comment by mmd-osm** [comment]
That's a bit similar to #6384, i.e. objects hiding behind one of the two panels.

**Comment by quincylvania** [comment]
Yep, this is #6384.
