### ISSUE TITLE
Validator: Unterground parking vs. footpath

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6425]
Location: http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries,past_future&id=w315548158&locale=en&map=19.02/52.49980/13.39400

IMO those features are tagged correctly, right?
Parking is "unterground", layer -1, level -1.

Is this a false positive for the validator? – Or am I missing something.

**Comment by quincylvania** [comment]
@tordans For that I would remove the `building` tag on the parking. I'm not sure how people feel about using `building` on underground structures, but I would advise against it. Renders may get the layering correct, but it still looks wrong.

![Screen Shot 2019-05-24 at 8 54 09 AM](https://user-images.githubusercontent.com/2046746/58329164-e98e6080-7e01-11e9-806d-d5bafbb49b3d.png)

**Comment by quincylvania** [comment]
Closing this. I'm pretty sure removing the `building` tag is the right way to go.

**Comment by tordans** [comment]
Sorry for keeping this unsolved. Did it now at https://www.openstreetmap.org/changeset/71305467#map=18/52.49964/13.39386 which indeed solved the issue.
