### ISSUE TITLE
Stores are missing in the branch

### ISSUE THREAD

**Issue by eduaddad** [openstreetmap/iD#6431]
The following stores are missing from ID.

Burger King (World)
Lojas Cem (Brazil) 
Lojas Renner (Brazil)
RiHappy (Brazil)
Drogaria São Paulo (Brazil)
Pernambucanas (Brazil)
Cybelar (Brazil)
Hipermercado Extra (Brazil) 
Tok&Stok (Brazil)

**Comment by bhousel** [comment]
Hi, thanks for the report. iD's brand presets come from the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) project. You can open an issue there for the missing items, but it might be worth checking first to see whether they exist under a different name or tagging than you are expecting.  (For example, I'm pretty sure we do have a preset for Burger King).

There is a browsable list here!
http://osmlab.github.io/name-suggestion-index/brands/
