### ISSUE TITLE
Pharmacy are missing logo at the branch

### ISSUE THREAD

**Issue by eduaddad** [openstreetmap/iD#6432]
The following pharmacies are missing their icon.

Drogaria Raia 
Drogasil

**Comment by bhousel** [comment]
Thanks for the report - the brand icons come from Wikidata.

To add a logo to the index, find the brand in this list here:
http://osmlab.github.io/name-suggestion-index/brands/

Then edit the brand's Wikidata page to include either a wiki commons logo, or some links to that brand's social media accounts (Facebook, Twitter, etc) and it will be picked up.
