### ISSUE TITLE
Add Field or Relation: lower items in the list are below browser screen

### ISSUE THREAD

**Issue by st-anton** [openstreetmap/iD#6436]
When adding a new relation or a new field of the object, the lower items of the drop down list are below the browser screen. This happens even with the slider of the tool area ('Seitenleiste') pushed to the lowest position.
![grafik](https://user-images.githubusercontent.com/2517417/58365726-af3bc680-7ec8-11e9-92d1-89b695d8c438.png)
Happens with the latest changes of iD (2.15.0), was not present with earlier versions. Using a Firefox browser 67.0 (latest)

**Comment by quincylvania** [comment]
Oh this was fixed awhile back.
