### ISSUE TITLE
Tag autocomplete wrong behavior

### ISSUE THREAD

**Issue by Bibi56** [openstreetmap/iD#6437]
When entering defibrillator:location, ID proposes user_defined_other.
Proposed tags should only be approved tags present in the Wiki.
As said in the Wiki:
`Don't use this tag. There are proper alternatives for all used values`

**Comment by bhousel** [comment]
same as #6441 
Again usage of these tags is so low that you can just change them yourself.  All the possible values here have like <30 uses worldwide.  We're not going to add code to iD to correct a value that is basically never used.

https://taginfo.openstreetmap.org/keys/defibrillator%3Alocation#values

**Comment by Bibi56** [comment]
Here it's about keys, not values, over 3 000 usages. 
https://taginfo.openstreetmap.org/keys/defibrillator%3Alocation#overview
You're proposing instead a tag that is used less than 400 times and that shouldn't be used at all.
