### ISSUE TITLE
 inconsistent state for iD-Editor after stopping area draw function (2 times hitting Esc key needed)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6438]
to reproduce

1. browse to:  http://preview.ideditor.com/master/#background=none&disable_features=boundaries&map=20.00/50.94165/10.06553
2. start to create an area
3. place the first node to a line of an existing area, (here natural=scrub)
4. stop the area drawing function by hitting Ecs key.
=> expected behavior stop the draw function and remove the node (vertex i don't know if this is the right wording for the node at the area-line)
=> noticed current behavior the natural=scrub area is deleted and the iD-Editor has reached an interesting inconsistent state (then you can funny things by pressing back and forward buttons, if you did same editing before)

(5.) there are two current workarounds to stop this inconsistent state:
a) to hit save button and cancel the saving procedure afterwards before final upload, or
b) hitting Esc key a second time 

wrong behavior:
![stop draw an area](https://user-images.githubusercontent.com/47290585/58372969-408d5600-7f26-11e9-90c5-d51885011438.gif)

expected behavior:
![stop draw an area2](https://user-images.githubusercontent.com/47290585/58373002-a37eed00-7f26-11e9-9e70-ce11659ad055.gif)

**Comment by quincylvania** [comment]
@sun-geo I couldn't recreate this issue recently. Are you still seeing it?

**Comment by sun-geo** [comment]
No. I now used 3 different browsers. It works fine for all.
Maybe any other of the many changes did fix it in the meantime.
Thanks for checking.
Please feel free to close it. Oh it seems the close function is also accessible for me.
So I will close it.
