### ISSUE TITLE
Expand guidepost preset, by adding field "road user type" (hiking / bicycle)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6439]
the current guidepost preset adds tags like
`information=guidepost`
`tourism=information`

maybe for hiking:
add tags like `hiking=yes` **and** `guidepost=hiking`
maybe for bicycle:
add tags like `bicycle=yes` **and** `guidepost=bicycle`

if there is a guidepost with combined hiking and bicycle information, then i assume these tags would be match:
add tags like `hiking=yes` and `bicycle=yes` **and** `guidepost=hiking;bicycle`

edit: see wiki: https://wiki.openstreetmap.org/wiki/Tag:information%3Dguidepost

**Comment by bhousel** [comment]
Sorry, I don't think we can really support this.. Things like `bicycle` and `horse` are access tags.   They don't really fit in this situation.

**Comment by sun-geo** [comment]
Thanks for checking.
_"`bicycle `and `horse `are access tags."_

Correct, I also don't like it to use it in this context with a guidepost/signpost. 
(and the wiki seems in meantime also to say so, wiki wrote: "_To describe the type(s) of the shown route(s) use the tags hiking=yes, bicycle=yes, mtb=yes, horse=yes or ski=yes. They don't describe the legal access to the guidepost. To make this explicitly clear instead of e.g. hiking=yes you could alternatively use **guidepost:hiking=yes or guidepost=hiking**, though this is less common, not widely supported and would add no additional meaning."_)

For me it's not really an issue to use these (in large count used https://taginfo.openstreetmap.org/tags/information=guidepost#combinations) access tags here, because information=guidepost is only allowed to use for node-elements which generally are not used for routing and these nodes maybe even are not placed(located) as vertex at a 2D-naviagtion-line(routing-network) object. I also usually put to node for the guidepost next to 2D-navigation-line (way) to the real physical position of the signpost, to avoid any routing-access-conflicts.

But I would also like to use here for the preset the other proposed tags like `guidepost:bicycle=yes` **and** / **or** `guidepost=bicycle` instead of `bicycle=yes`.

**Comment by rugk** [comment]
I also like this idea.
