### ISSUE TITLE
highway=crossing nodes with the tag kerb=* are updated to curb nodes

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6440]
Upgrading the tags of this crossing causes unexpected results: http://preview.ideditor.com/master/#background=Mapbox&disable_features=boundaries&id=n5489547638&map=20.00/36.07148/-79.81034

**Comment by BjornRasmussen** [comment]
This also seems very wrong: http://preview.ideditor.com/master/#background=EsriWorldImagery&disable_features=boundaries&id=n5381175621&map=20.17/35.94621/-79.05827

**Comment by bhousel** [comment]
Ugh yeah - a `kerb` tag on the crossing-road junction node is really wrong.  Not sure whether this is a widespread enough practice that iD should include code to remove it.

**Comment by BjornRasmussen** [comment]
The combination of highway=crossing + kerb=* is used 80,767 times according to taginfo.

**Comment by danielwhogan** [comment]
>> Ugh yeah - a kerb tag on the crossing-road junction node is really wrong.
>
>The combination of highway=crossing + kerb=* is used 80,767 times according to taginfo.

The kerb=* value is commonly used, and is permitted by the [key:kerb page](https://wiki.openstreetmap.org/wiki/Key:kerb) on the wiki. The barrier=kerb is definitely not correct. I can't think of a reason why a node would ever have both barrier=kerb and highway=crossing. This pair of tags is currently on 216 nodes that were modified within the last 10 days, according to Overpass (`node["barrier"="kerb"]["highway"="crossing"](newer:"{{date:10day}}")({{bbox}});`).

There's relevant discussion in the comments on [changeset 70648272](https://www.openstreetmap.org/changeset/70648272).

**Comment by quincylvania** [comment]
I agree that `kerb` shouldn't be used on crossings anymore, but it is a bug that iD treats crossings with these tags as curbs.

**Comment by Lukas458** [comment]
So what's about 
- either just ignore highway=crossing + kerb=* 
- or showing a kind of field or something when getting onto highway=crossing + kerb=* that shows something like "try to add barrier=kerb nodes on the crossing way"...
