### ISSUE TITLE
Make issue warning clearer when offering to add brand/wikidata

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#6443]
First time using the new version of iD, I moused over a node for a Premier Inn hotel and saw it had the issue "Premier Inn has outdated tags".

I thought this was a bit strange, as it simply had name=Premier Inn and tourism=hotel tagged on the node - a perfectly valid and current combination.

Decided to click "upgrade the tags" anyway, therefore iD added brand, brand:wikidata and brand:wikipedia - which is fair enough. However clearly just because something doesn't have brand data doesn't mean it has "outdated tags".

It would be great if you could change the issue warning text so it's clear to the user what the actual problem is, and what will happen if they click "upgrade the tags".

**Comment by BjornRasmussen** [comment]
In the next version of iD, 2.15.1, which was released a few days ago and should be deployed to the main website soon, iD complains about "incomplete tags" if only new tags are being added.

**Comment by boothym** [comment]
Ok, thanks - though it's not really incomplete, it would be better saying "add brand information" or something.

**Comment by SilentSpike** [comment]
If information is missing, is it not incomplete? 🤔

I think it's fine as a catch-all heading, to make more clear what will be added something along the lines of #6408 seems more useful.

**Comment by boothym** [comment]
Aye, but does adding the brand data make it complete? Plenty more that could be added to a hotel (address, rooms, etc.) but iD doesn't highlight the feature as incomplete when it's missing that kind of information.

**Comment by SK53** [comment]
I've just come across this myself with Tesco Express. It's good to hear that the text will be changed, but I think "incomplete" is a serious misrepresentation of current OSM practice. I would suggest instead something like "this object is missing information which can be useful, would you like to enhance it?"

Whereas I have some sympathy with the view that OSM tagging ultimately tends to be more-and-more explicit, it is a misrepresentation to state that this is a) the consensual position; b) widespread practice. In addition it is, for obvious reasons, inconsistent in not nagging for speed limits, surface, sidewalk etc on roads.

These additional tags can be useful, but I'm chary about insisting on them: mainly this can be addressed by slightly different phraseology. Ideally users should get some context: not just "outdated".

Lastly "Tesco Express" is not the brand of the store: the brand is "Tesco" as the wikidata tags imply. "Tesco Express" is a format.

**Comment by matkoniecz** [comment]
It is a big problem. For example at https://www.openstreetmap.org/way/488118123 iD wants to add `brand:wikidata` and `brand:wikipedia` tags based solely on name match, without verification from user.

It makes no sense at all - if name is sufficient for identification, then what is the point of `brand:wikidata` and `brand:wikipedia` tags?

If it is not sufficient for identification - then why user is not asked to review but instead it is misleading described as "upgrading tags"?

**Comment by matkoniecz** [comment]
I propose to remove this "upgrade" until interface allowing a real review is added.

**Comment by matkoniecz** [comment]
I plan on making PR that reverts this misuse of name-suggestion-index. 

First step is finding a commit that added it. Just in case that someone knows where it was added - please let me know, it would be helpful!

**Comment by BjornRasmussen** [comment]
I think it's a better idea to just remove the autofix option (in validation pane, you can upgrade all brands in the area without looking at each POI).

**Comment by matkoniecz** [comment]
Currently even for individual items it is completely broken.

**Comment by quincylvania** [comment]
I think it's worth asking users to add brand tags since POI coverage is so uneven in OSM, but I agree this could be improved.

- Make the message more specific than just "outdated" or "incomplete"
- Don't allow "autofixing" from the Issues pane
- Ensure that country codes are taken into account
- Make name-suggestion-index coverage even better!

**Comment by quincylvania** [comment]
I did these:

> - Make the message more specific than just "outdated" or "incomplete"
> - Don't allow "autofixing" from the Issues pane

![Screen Shot 2019-06-10 at 11 40 37 AM](https://user-images.githubusercontent.com/2046746/59207224-a7407f80-8b74-11e9-931c-0fa963709008.png)

See #6513 for the country code filtering.

**Comment by matkoniecz** [comment]
Thanks for disabling autofix! I still think that it should be improved so I opened #6517
