### ISSUE TITLE
Google Chrome suggests it's own list of autocomplete values for almost all fields

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6444]
Similar to #6414 
Chrome likes creating it's own list of autocomplete labels based on what I've typed in before in **fields**.  The raw tags editor and access tags editor and _not_ affected by this.
![image](https://user-images.githubusercontent.com/37753777/58439962-10b88c80-80a5-11e9-8ded-1cb26bf10926.png)

**Comment by quincylvania** [comment]
I was wondering if this would happen. Chrome appears to remember and suggest values for text inputs with `id` attributes. Most fields use an `id` on the `input` to match the `for` value of the `label`. This makes the field focus when you click the label. We either need to remove the ids and forgo this behavior, or randomize the ids with each render.

**Comment by quincylvania** [comment]
> randomize the ids with each render.

I ended up doing this ☝️. It _should_ fix the issue, but browsers are persistent little rascals so let me know if it shows up again.
