### ISSUE TITLE
Feature Request: OSMC Symbol Builder

### ISSUE THREAD

**Issue by kolgza** [openstreetmap/iD#6445]
[OSMC Symbols](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol) are an underutilized feature that allow trail way-markers to be saved in a machine readable format. The problem with them is that they're relatively difficult to create.

**Comment by BjornRasmussen** [comment]
That specification seems very confusing and difficult to read.  If it were split into 5 tags, with namespaces indicating what each tag represents (instead of just making putting it all in one tag), then I think it would be more manageable.

**Comment by BjornRasmussen** [comment]
Perhaps 
```
osmc:symbol=waycolor:background[:foreground][[:foreground2]:text:textcolor]
```
could instead be tagged as 
```
osmc:symbol:waycolour=*
osmc:symbol:background=*
osmc:symbol:foreground=*
osmc:symbol:foreground2=* (or better)
osmc:symbol:text=*
osmc:symbol:text:colour=*
```

**Comment by bhousel** [comment]
closing as too hard
