### ISSUE TITLE
Only upgrade to brands with matching country code

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6448]
iD flags a POI as outdated and in need of upgrade even when it matches a brand that’s limited to a different country.

[This pizzeria](https://www.openstreetmap.org/node/392512318) is tagged `amenity=restaurant` `cuisine=pizza` `name=Cosmo` with no brand tags. It’s located in the United States, but iD recommends “upgrading” it to [a buffet chain named Cosmo](https://en.wikipedia.org/wiki/Cosmo_%28restaurant%29) that, according to osmlab/name-suggestion-index@d0568242825cfd00d6bf0feef1e7c827d1b451c9, only exists in Ireland and the UK. As far as I can tell, there’s no relation to the British chain.

<img src="https://user-images.githubusercontent.com/1231218/58469680-d37beb00-80f4-11e9-8c84-209c4264c59f.png" width="399" alt="cosmo">

In this case, upgrading only added brand tags, but I could imagine another case where it changes the `cuisine` tag to something incorrect too.

**Comment by bhousel** [comment]
moved to #6513
