### ISSUE TITLE
The mouse pointer is a "hand" shape when moving nodes, instead of a locator. 

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6450]
Try going to preview.ideditor.com/master and dragging a vertex of a way.  
Then, try doing the same on osm.org
The "hand" icon isn't converted into a locator or "plus" symbol on preview/master.

**Comment by quincylvania** [comment]
Yep, #6113 and related changes are causing various weirdness with click targets and cursors in the map. We've started work on iD v3, so breaking changes are expected. Feel free to continue documenting bugs, but be aware that bug-free code isn't the priority at the moment. Thanks for testing iD and bearing with us!
