### ISSUE TITLE
v3  switch of mouse icon behaviors (hand-icon and crosshairs-icon isn't switching) 

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6452]
Hi together,

today i'm surprised the iD-v3 features (new title-bar) seems released for the preview.ideditor :-)
http://preview.ideditor.com/master/#background=EsriWorldImagery&disable_features=boundaries&map=17.20/45.58769/-97.27568

The mouse icons are not so stable compared to v2.x

What I saw are 2 behaviors:

- Sometimes the hand-icon isn't switching to the crosshairs-icon while drawing a feature, (to watch at second 11 or 25 in the movie below)
- Sometimes the crosshairs-icon isn't switching back to the hand-icon after the drawing of an object is finished. (to watch at second 40 in the movie below)

![hand icon missing](https://user-images.githubusercontent.com/47290585/58513879-d207fc80-81a0-11e9-94ad-a2efbf3ae436.gif)

**Comment by quincylvania** [comment]
@sun-geo Thanks for the screen capture! This is similar to #6450, but I'll leave it open for the moment since I'm not sure it's a total duplicate.

**Comment by sun-geo** [comment]
Thank you - looks good so far :-)
