### ISSUE TITLE
Drawing segment type toolbar item

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6453]
Breaking this off from #5960: we should have a toolbar item while drawing to switch between normal (straight) and orthogonal drawing. The user could switch between them while drawing a feature, with the orthogonal segment relative to the previous segment. This would work for both lines and areas. See also #2699.

![Screen Shot 2019-05-29 at 10 03 48 AM](https://user-images.githubusercontent.com/2046746/58563474-33f45080-81f9-11e9-93d5-0294946f232b.png)

**Comment by quincylvania** [comment]
I did this! The orthogonal drawing is fairly primitive, but it gives us a place to start from. We should target the functionality shown in #2699.

![ortho segments demo](https://user-images.githubusercontent.com/2046746/58572065-fb5c7300-8208-11e9-9549-04b79f71fe94.gif)

**Comment by BjornRasmussen** [comment]
This is AMAZING!  I just tried it out on preview.ideditor.com/master and love it!
I do have couple of suggestions, though: 
* allow for 45, 30, & 60 degree angles:
JOSM looks like this:
![Screenshot from 2019-05-29 12-19-16](https://user-images.githubusercontent.com/37753777/58573593-17154880-820c-11e9-9824-1645a1172740.png)
* snap to places where a previously added node in the way is 90 degrees to the right or left.
JOSM looks like this: 
![image](https://user-images.githubusercontent.com/37753777/58575474-21394600-8210-11e9-9eab-2cec27e3eede.png)
this makes it easier to end a way as a squared shape.

**Comment by BjornRasmussen** [comment]
JOSM also has a quick way to switch between the two drawing modes: pressing the keyboard shortcut `A`.  This might make sense for iD too, since I find myself switching between the two modes a lot.

**Comment by quincylvania** [comment]
> JOSM also has a quick way to switch between the two drawing modes: pressing the keyboard shortcut A. This might also make sense in iD, since I find myself switching between the two modes a lot.

I was considering either this or a different shortcut for each segment type, since we'll eventually have a circular type as well. I guess a single shortcut is fine since there should never be too many options.
