### ISSUE TITLE
v3 title bar: ability to drag&drop generic item buttons to left side of new "Add feature" / search-button

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6458]
It seems i'm still an old school user of iD and always happy to not loose hundred per cent of the great history of iD and the rawish workflow. ;-)
Could use please let me drag&drop the “Favorites” buttons for adding the 3 generic items (node, line & area) to the left side of the new "Add feature" / search-button?

And if they fall down to these left hand side, please increase the width of these 3 buttons, at least to the same width of the current "Add feature" / search-button.

Screenshot 
![node left side](https://user-images.githubusercontent.com/47290585/58647769-8cfeda00-8308-11e9-990d-2e3a23daeb87.gif)

**Comment by quincylvania** [comment]
@sun-geo Does it make a difference in your workflow that these are on the right side instead of the left side? The keyboard shortcuts are the same. I'd really prefer not to privilege the generic presets over the normal ones.

**Comment by sun-geo** [comment]
regarding the button width...

before
![before](https://user-images.githubusercontent.com/47290585/58648736-ac970200-830a-11e9-8609-f3cc0946a808.png)

after
![after](https://user-images.githubusercontent.com/47290585/58648744-b1f44c80-830a-11e9-97f4-636cab8e2858.png)

**Comment by sun-geo** [comment]
quincylvania: _"Does it make a difference in your workflow that these are on the right side instead of the left side? The keyboard shortcuts are the same. I'd really prefer not to privilege the generic presets over the normal ones."_

Hmm not 100% sure yet, but makes it a difference of other users they don't use the generic item button at all?

**Comment by quincylvania** [comment]
> does it make a difference of other users they don't use the generic item button at all?

Maybe not, but any new feature requires an investment of initial development and long-term support.

Our goal with iD v3 is to build a next-generation editor, and sometimes this may mean changing old functionality. In this case the functionality is backwards-compatible. Can we give this some time and see how people feel?

**Comment by sun-geo** [comment]
Yes, I understand to get a "real" change of UI especially when there will be happen an increase of v2 to v3.
But i think you did already a lot & hard work for the new features
- Recent, Repeat, Search, 
- changing availability/grey out for buttons (like Segments, Undo&Redo, Finish, Deselect, Circularize, Square and so on) which already exist now & which will already legitimate the change from v2 to v3 in my opinion :-)

An other minor proposal, maybe the wording from "Favorites" to "Add basic element" (or somewhat) could be modified, see here:
![after2](https://user-images.githubusercontent.com/47290585/58650453-04376c80-830f-11e9-9495-a7751a8adb07.png)


I assume new iD-users will even newer see these generic buttons, if they don't need/like it...

**Comment by quincylvania** [comment]
@1ec5 wrote this [in OSMUS Slack](https://osmus.slack.com/archives/CBK3JLUJU/p1567945216115900): 

> I get why the workflow is oriented towards presets over geometry types and appreciate that there’s still a toggle while using a preset. But I think the paradigm shift is a tradeoff rather than an unqualified improvement. Some people are certainly going to find it more intuitive to focus on the type of business rather than the geometry.
>
> On the other hand, there are people who benefit from the current workflow, which is more like a drawing program. (In Illustrator, you choose the drawing tool and draw before choosing the stroke color, dash pattern, etc.)
>
> Potlatch compromised by having both a palette of presets and affordances for drawing before tagging, to accommodate both ways of thinking. The new drawing modes in v3 like repeat have me imagining a drawing-first mode as an option that wouldn’t be as prominent as the presets. It’s still possible to favorite the point/way/area presets, but that feels like a hacky workaround.

And I think he might have a point! I think there are great possibilities for the new workflow but perhaps the old one has its place. In any case, we did #6717 so now we can have a single toolbar item to recreate the legacy workflow. It's enabled by default upon upgrade from iD 2 but disabled by default for new users.

<img width="677" alt="Screen Shot 2019-09-17 at 6 20 54 PM" src="https://user-images.githubusercontent.com/2046746/65084411-1e0dc580-d979-11e9-8298-fe36bdb0b71b.png">

("Base Types" may not be the best name for this but I thought it better than "Generics").

**Comment by 1ec5** [comment]
> ("Base Types" may not be the best name for this but I thought it better than "Generics".)

It is better than “Generics”. Other options could be “Add Shape”, “Geometries”, or “Drawing Tools”.

**Comment by bhousel** [comment]
I really like this a lot, thanks @quincylvania !
FWIW I like "Geometries"

**Comment by sun-geo** [comment]
Thanks for adding these new options (checkboxes), even if my initial request (possibility of dragging the base types to left side and increasing width for base type buttons would not implemented) Meanwhile I'm ok to let it like it is now.

Regarding the wording. I still would prefer to maybe use/have the same wording like the wiki is using.
https://wiki.openstreetmap.org/wiki/Elements
But I know & i see there is a little difference between these types
iD-editor offers: point, line, area
wiki-elements: node, way, relation

**Comment by quincylvania** [comment]
> I really like this a lot, thanks @quincylvania !

@bhousel Good, I hope it helps!

> FWIW I like "Geometries"

Agreed, let's try this for awhile.

> Thanks for adding these new options (checkboxes), even if my initial request (possibility of dragging the base types to left side and increasing width for base type buttons would not implemented)

@sun-geo Now that we have an advanced toolbar system some of this might actually be possible. I'm sure at some point someone will request the ability to reorder toolbar items. We might also consider showing the preset/geometry names when there's space.

Also note: you can hide the Add Feature tool and only use the generic workflow if you want!

> Regarding the wording. I still would prefer to maybe use/have the same wording like the wiki is using.

We couldn't really do this even if we wanted to since the types don't map directly—OSM doesn't have an `area` type.
