### ISSUE TITLE
"Oudated tag" conversion overwrites modern tags that are already there

### ISSUE THREAD

**Issue by danstowell** [openstreetmap/iD#6462]
Hi - I edited a restaurant and saw the "Outdated tags. Update?" dialog so I clicked yes. I think it was referring to the outdated `cuisine=vegetarian`. However, the object already had the more modern tag in place, it had `diet:vegetarian=only`. The iD editor automatically deleted the old tag but overwrote the modern tag with `diet:vegetarian=yes` which is a worse tag than what was already there. I'm not here to debate only-vs-yes, the general point is:

If the modern tag is already in place, iD should now overwrite it with autogenerated values.

**Comment by SilentSpike** [comment]
What was the restaurant?

**Comment by danstowell** [comment]
https://www.openstreetmap.org/node/1936469261

**Comment by SilentSpike** [comment]
Ah I see now what you mean, I thought it might be something to do with the name suggestion index and a branded location at first.

Interesting edge case. Basically iD should defer to an existing value for a key when adding tags in an quick fix.

**Comment by quincylvania** [comment]
@danstowell Thanks for finding this! It was definitely unintentional and has been fixed.
