### ISSUE TITLE
Improve restore UI

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6467]
![Screen Shot 2019-05-31 at 8 22 08 AM](https://user-images.githubusercontent.com/2046746/58712558-cc700980-838e-11e9-99e7-60fb5ab5fef0.png)

There are a number of things we could add to improve this screen to encourage the user and tell them what's going on.

- A friendly "welcome back" message
- The number of changes that will be restored
- How much time has passed since these changes were stored
    - Perhaps the user hasn't mapped in a long time and wouldn't want to restore stale edits
- Where the changes were made
    - Perhaps the user followed a link to a specific map location and wouldn't want the viewpoint to change

For example:

_Welcome back! You have 29 unsaved changes around Atlanta, Georgia, from 3 weeks ago. Would you like to restore them?_

**Comment by todrobbins** [comment]
Love these proposals! 👍🏻

**Comment by quincylvania** [comment]
I implemented the message changes and also moved the restore functionality into the new assistant panel. This is much less intrusive than the fullscreen splash and allows you to poke around the UI before making a decision. Editing is still disabled until you decide.

With this UI it'll be simple to show the changed in the map once we build a visual diffing feature.

<img width="633" alt="Screen Shot 2019-06-05 at 5 28 47 PM" src="https://user-images.githubusercontent.com/2046746/58991999-9af4a500-87b7-11e9-885b-c356e7f0de3c.png">

**Comment by todrobbins** [comment]
Ha, I like it!

**Comment by jidanni** [comment]
(The code is [here](https://github.com/openstreetmap/iD/blob/develop/data/core.yaml).)
OK, for now, please at the bottom of the two choices,
have the words:
"_If not sure, just press Restore. You can always undo those changes again before saving._"
