### ISSUE TITLE
stop adding/nie dodawać/ne aldoni "brand:wikipedia"

### ISSUE THREAD

**Issue by verdulo** [openstreetmap/iD#6471]
PL:
Obecnie edytor iD obok użytecznych znaczników "brand", "brand:wikidata"; niestety dodaje również znacznik "brand:wikipedia", zwykle w obraźliwym imperialistycznym języku angielskim. Ręczne usuwanie jest średnio skuteczne, ponieważ edytor posiada opcję "napraw wszystkie", która automatycznie dodaje „brakujące” znaczniki.

[Próbowałem](https://github.com/osmlab/name-suggestion-index/pull/2720) zasugerować zmianę odnośników do Wikipedii na język kraju z którego pochodzi firma, lecz zostałem zablokowany przez nacjonalistów z name-suggestion-index.

**Proszę o zaprzestanie sugerowania dodawania tego (potencjalnie) obraźliwego i zbędnego (odnośniki do Wikipedii znajdziemy na Wikidanych, poza tym odnośnik do brand:wikipedia jest nieklikalny na openstreetmap.org) znacznika.**

EO: 
Nuntempe la redaktilo iD krom uzeblaj etikedoj "brand" kaj "brand:wikidata" bedaŭrinde aldonas la etikedon "brand:wikipedia", kutime en ofenda kaj imperiisma angla lingvo. Permana forigo estas nesufiĉe efika, ĉar la redaktilo oferas la funkcion "ripari ĉion", kiu aŭtomate aldonas “mankantajn” etikedojn.

[Mi provis](https://github.com/osmlab/name-suggestion-index/pull/2720) proponi ŝanĝi lingvon de ligiloj al Vikipedio al lingvo de lando el kiu firmao devenas, sed mi estis blokita de naciistoj el name-suggestion-index.

Bonvolu ĉesi proponi aldoni tiun (eble) ofendan kaj malnecesan (ligiloj al Vikipedio troviĝas en Vikidatumoj, krom tio la ligilo al brand:wikipedia estas neklakebla ĉe openstreetmap.org) etikedon.

EN:
https://www.bing.com/Translator
https://translate.google.pl/

**Comment by quincylvania** [comment]
Hi @verdulo, thanks for your concern. I assume you refer to issues like [this](https://github.com/osmlab/name-suggestion-index/pull/2712).

The name-suggestion-index project is an important dependency of iD and we're not going to stop using it because of a simple tagging disagreement. I admit OSM tagging is imperfect and it's regrettable that the `brand:wikipedia` tag only really supports a single language at a time. However, I trust the maintainers' judgement in picking the best possible tags for each brand based on real conditions, not some conspiratorial imperialist agenda. Please listen to their arguments about why they use certain tags and assume good faith.

If you're really worried about English hegemony then I'd take a look at all OSM tagging, not six clothing stores.

**Comment by verdulo** [comment]
@quincylvania 
PL:
Jakie argumenty?! Moja zmiana została zamknięta i zostałem zablokowany we wszystkich projektach osmlab!
Co jest złego w mojej propozycji, aby całkowicie usunąć brand:wikipedia, lub nie oznaczać tak oznaczonych punktów jako „błędnych” (mających niepełne znaczniki)?

EO; Kiuj argumentoj? Mia ŝanĝo estis fermita kaj mi estis blokita de ĉiuj projektoj osmlab!
Kio estas malĝusta pri mia propono: tute forigi brand:wikipedia aŭ ne marki tiel markitajn punktojn kiel “erarajn” (havantaj nekompletajn etikedojn)?

**Comment by quincylvania** [comment]
This is the argument I saw, which makes sense to me. The `brand:wikipedia` tag value should be in the primary language overall for where the brand operates.

>  These aren't mainly Polish brands and English is spoken in a lot more places where they are located than Polish is. If they were confined to Polish countries I'd zero problem with them being linked to Polish Wikipedia articles. As it is though, I suggest we reject this. It's not like people can't go to the Polish Wikipedia articles pretty easily from the Wikidata entries anyway.

I don't know about the block but I imagine making inflammatory comments or repeatedly proposing changes that are against the project guidelines could be grounds for blocking. If you feel the block is unwarranted then I suggest discussing that elsewhere. This issue has ceased to be relevant to the iD project.
