### ISSUE TITLE
Showing the tag status to help contributor's decision

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#6473]
I believe it would be helpful to show the status(P6) of each tag as below somewhere when selecting/upgrading a tag so that people can concider if they would use it or not.
- Undefined
- Draft
- Proposal
- Voting
- Abandoned
- Canceled
- Rejected
- Approved
- In use
- De facto
- Discardable
- Obsolete
- Deprecated

I suppose these values may be able to get thru Sophox though uncertain about details.
https://wiki.openstreetmap.org/wiki/Property:P6

**Comment by quincylvania** [comment]
@higa4 Hmmm I don't see us doing this. The wiki can be chaotic and contradictory. iD mappers should feel confident that all tags suggested by iD are okay to use. I'm not saying that iD's presets are perfect, but I wouldn't want to put the burden of parsing tag status onto users. Feel free to open issues for any tags you feel iD handles incorrectly!

**Comment by bhousel** [comment]
Agree, and #6370 is a good example.
