### ISSUE TITLE
cannot create a new addr:housenumber

### ISSUE THREAD

**Issue by Rpnpif** [openstreetmap/iD#6476]
The addr:housenumber is now gray and I cannot enter a new house number is the box.
Actually this attribute is not usable in Id.

Regards.

**Comment by quincylvania** [comment]
@Rpnpif Could you post a screenshot and/or a link to the location where this is happening? It could be that iD does not know the address format for the location.

**Comment by Rpnpif** [comment]
Sorry, i am wrong.
Wrong way to enter the number.

I am very sorry for this report and I am closing.

**Comment by quincylvania** [comment]
@Rpnpif No problem at all! I'm glad you were able to resolve the issue.
