### ISSUE TITLE
Add corrector for ways that have Speed Limit, but are missing Max Speed

### ISSUE THREAD

**Issue by sanecito** [openstreetmap/iD#6478]
The KeepRight layer flags highways that are missing MaxSpeed. This isn't an attribute that's automatically shown in the modification left panel, you have to manually add it. When committing things w/ issues like outdated tags for crosswalks that you've touched, you're alerted before you save the commit and basically given a 1 click button to fix certain things like outdated tags in addition to whatever changes you made.

It would be nice if there's a similar quickfix button for roads where there's a SpeedLimit, but not a MaxSpeed so this KeepRight issue can be more easily caught and cleaned by anyone who touches these ways in iD.

**Comment by quincylvania** [comment]
@sanecito I understood your suggestion as deprecating tags like `speed_limit` and `speedlimit`. If you meant something else then let us know!
