### ISSUE TITLE
Name field suggestions don't respect country codes from name suggestion index

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#6479]
Example:
- Editing [this node](http://preview.ideditor.com/master/#id=n595491205&map=19.00/57.14720/-2.09465) change the name field to just "Vue" and notice that both the UK and Netherlands' brands are suggested (from NSI where country codes are correctly configured).
- If you instead go to change the preset and search for "Vue", only the UK brand is suggested as expected.

**Comment by matkoniecz** [comment]
I was unable to trigger brand suggestion. Creating new point and searching Vue gives me just cinema (with a bit poorly formatted name)

![Selection_001](https://user-images.githubusercontent.com/899988/58831829-dd01d780-864d-11e9-8bd3-65d2cfdda686.png)

**Comment by SilentSpike** [comment]
What it suggests for me:

![image](https://user-images.githubusercontent.com/5459452/58832369-b1c7ba00-8646-11e9-9c06-1694890e6658.png)

**Comment by matkoniecz** [comment]
Now I see it! It was caused be me doing

> Editing this node change the name field to just "Vue"

by deleting " Cinema"

To trigger autocompletion one may delete name and start *typing* it. Sorry for a confusion.
