### ISSUE TITLE
Make `Ctrl-Z` (undo) work during the repeat mode.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6482]
When adding curb nodes with the repeat mode, I accidentally placed one in the wrong location.  I tried undoing with `Ctrl-Z`, but it didn't work, so I had to use `Esc` -> `Ctrl-Z` -> `1` (one of my `favorite` shortcuts - used for curb nodes) -> `R`. 
Undoing should be possible when in the point-adding repeat mode.  It is already available for adding ways, but not for undoing incorrectly placed points.

**Comment by quincylvania** [comment]
@BjornRasmussen Thanks for posting. I agree we should do this.

**Comment by BjornRasmussen** [comment]
Awesome!!

**Comment by quincylvania** [comment]
It's always great to make editing even faster!
