### ISSUE TITLE
Improve the welcome screen

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6486]
When a user launches iD for the first time in their browser, they see this splash screen:

<img width="611" alt="Screen Shot 2019-06-04 at 3 50 21 PM" src="https://user-images.githubusercontent.com/2046746/58909591-7d550c00-86e1-11e9-9cca-83644c63f905.png">

I see two primary issues with this:

- _It dominates the entire screen._ You can't do anything without making a decision. This is reminiscent of popup ads or blogs that ask you to sign up for a mailing list. My instinct as a new user would be to either close the window immediately or to click "Edit now" just so I can poke around.
- _It's too technical._ Normal people don't care about version numbers or bug reports. New users are probably still trying to understand what OpenStreetMap is, so trying to explain iD isn't too helpful.

We could improve on this screen by moving it to the assistant panel. Users could explore before deciding to take the tutorial. The message would persist until the user edits something.

<img width="392" alt="Screen Shot 2019-06-04 at 3 49 48 PM" src="https://user-images.githubusercontent.com/2046746/58910218-f6089800-86e2-11e9-92c4-2aa428cfb332.png">

With this method, we could also have a welcome screen for returning users. It could include news and encouragement.

<img width="380" alt="Screen Shot 2019-06-04 at 3 49 59 PM" src="https://user-images.githubusercontent.com/2046746/58910406-6fa08600-86e3-11e9-90ea-cf8b5ec5721c.png">

**Comment by BjornRasmussen** [comment]
`You've edited 468 features in the past week.  Why not aim for 500?`
Hmm... I would read that sentence as telling me to do something I don't want to do, even if that's not the intention of the sentence.  People don't just start iD to "get some mapping done and earn points" - they start it to improve a certain thing.  Perhaps something that doesn't ask people to map a specific amount would be better, such as `You've edited 468 features in the past week.  Keep up the good work!`.

**Comment by quincylvania** [comment]
@BjornRasmussen Good point. The messages aren't set in stone. I'm thinking we could have variable messages. Some more ideas:

- You've mapped every day for past 30 days. Congrats!
- There's a **mapathon** going on right now.
- You've been mapping a lot around Philadelphia. Do you know about the **GeoPhilly Meetup**?
- You've edited over 5,000 features today. Maybe it's time for a break?

Now that I think of it, some of these could also appear after saving.
