### ISSUE TITLE
Bring back the resize function for the left sidebar

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6488]
In v2.5x there is and option to increase the width of the left sidebar.
The current preview v3 doesn't allow this. :-(

I assume this could be related to one of these changes https://github.com/openstreetmap/iD/issues/6461, https://github.com/openstreetmap/iD/issues/6468 or https://github.com/openstreetmap/iD/issues/6119 .

**Comment by BjornRasmussen** [comment]
For me, it's letting me do it as usual.

**Comment by quincylvania** [comment]
@sun-geo What browser are you using? It's working on Safari.

**Comment by quincylvania** [comment]
Scratch that, it's not working on Safari. I must have broken it today.

**Comment by BjornRasmussen** [comment]
I must have had some old javascript cached in the tab, since it's not working for me anymore.

**Comment by sun-geo** [comment]
Thanks for fixing!
