### ISSUE TITLE
deleting a multilingual name hides all multilingual names

### ISSUE THREAD

**Issue by richlv** [openstreetmap/iD#6491]
Have an object with names in several languages. Delete one of the languages - all of the multilingual name entries disappear (although the actual tags are not removed).

Firefox 67.0 on a Mac.

**Comment by DujaOSM** [comment]
I can confirm that it has worked like this for at least a year. I consider it a minor annoyance, and a quick workaround is to delete the tags directly rather than the corresponding "Name" entry.

**Comment by richlv** [comment]
Yes, you can also collapse-expand attributes, and then the missing entries re-appear.
This could be very confusing for new users, as they would have tag section likely collapsed by default, and would not know the removal was only visual.

**Comment by richlv** [comment]
Yay, thank you for the fix :)
