### ISSUE TITLE
iD wants to use lithuanian shop details in latvia

### ISSUE THREAD

**Issue by richlv** [openstreetmap/iD#6495]
Select this shop in iD: https://www.openstreetmap.org/way/67623510 .

Notice how it says "Aibe has outdated tags".
It suggests these changes:

    + brand=Aibė
    + brand:wikidata=Q1022952
    + brand:wikipedia=de:Aibė
    - name=Aibe
    + name=Aibė

This is incorrect, as it uses Lithuanian character, and the [wikidata entry](https://www.wikidata.org/wiki/Q1022952) points at the Lithuanian website as well.

**Comment by quincylvania** [comment]
@richlv Thanks for finding this! iD gets brand data from the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) project, so you'll have to get it fixed there.

**Comment by richlv** [comment]
Thanks, created https://github.com/osmlab/name-suggestion-index/issues/2759 .
