### ISSUE TITLE
Web app crashes on saving

### ISSUE THREAD

**Issue by sidati** [openstreetmap/iD#6496]
Hi,
After doing some edits on my neighborhood 😎, clicking **Save** (Ctrl+S) the app crashes and screenshot the error on my console log : 

![image](https://user-images.githubusercontent.com/4185345/59008066-b3e17280-8818-11e9-964c-626194cbecf7.png)

Hope you fix it so i can save my edits :)
Thanks in advance ;)

**Comment by quincylvania** [comment]
@sidati Thanks for reporting! It looks like you probably had unsaved changes stored in the browser from before the 2.15 update. I believe I've fixed the issue for the next release of iD.

**Comment by sidati** [comment]
Great, waiting for the release so i can save my edits ;)
