### ISSUE TITLE
Flag URL-shortened website tag values

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6498]
iD now flags [`website`](https://wiki.openstreetmap.org/wiki/Key:website) values without an `http` or `https` scheme (see #6494).

We should also flag URLs from [common URL shortening services](https://www.techmaish.com/list-of-230-free-url-shorteners-services/). A legitimate point of interest isn't going to have one of these as their official URL. A shortened URL can mask all kinds of unpleasantness like spam, fraud, and advertising that don't belong in OSM.

One potentially legitimate use of a URL shortener would be for websites longer than the 256 character tag value limit, but these seem uncommon.

**Comment by pnorman** [comment]
I had a look at the data for tinyurl and bitly. Of 54 usages, 15% were custom URLs (e.g. https://www.openstreetmap.org/node/3242616361). I can see a store having one of those as its official URL. Of the others, most were linking to something that should be a source, or was the page of the POI on some other service. goo.gl appeared to all be linking to something that was used as a source.

**Comment by quincylvania** [comment]
Closing this as low-impact. We can reconsider it if there are signs of actual abuse.
