### ISSUE TITLE
v3 03b16a8: Make upload possible :-)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6499]
upload seems currently not working at all, see:
![no upload possible](https://user-images.githubusercontent.com/47290585/59062999-71b34200-88a7-11e9-9ed7-f03a9d00145d.gif)

**Comment by quincylvania** [comment]
@sun-geo Oops! Thanks for bearing with us during the iD v3 churn 😅

**Comment by sun-geo** [comment]
Thanks for quick fix :-)
