### ISSUE TITLE
Adding a member to a multipolygon twice is irreversible

### ISSUE THREAD

**Issue by DujaOSM** [openstreetmap/iD#6504]
When you erroneously add a member to the same multipolygon twice (didn't test with other relation types), you cannot remove it just once. Reproducible on both 2.15.1 and on http://preview.ideditor.com/master:

- Create a multipolygon relation (or take an existing one)
- Draw a new line
- Add it to the relation as outer
- Add it once more to the relation.
- Try removing the latter. It removes both instances. 
- Try adding the relation back. Both instances are back. 

The line is apparently now in an inconsistent state and there's no way to add it to the relation once, short of redrawing it from scratch (AFAICT).

**Comment by DujaOSM** [comment]
Followup: It is broken with route relations as well. Undo does help, though (if you spot the issue soon enough, otherwise it's an [uphill battle](https://www.openstreetmap.org/changeset/70931808)).

**Comment by quincylvania** [comment]
@DujaOSM Thanks for finding and posting this! It was a weird edge case where only one member was actually deleted but it appeared as if both were deleted in the UI due to cacheing. Fixed.
