### ISSUE TITLE
Validation: barrier=entrance vs. entrance=yes

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6506]
Location: http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&id=n5433955187&locale=en&map=20.00/52.48679/13.44062

**Issue:**

There is a barrier which has (had) barrier=entrance.
The suggested auto-edit is to change it to entrance=yes.

The way I read the wiki is, those two tags are meant to be for different things. https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dentrance
(Someone commented on this page 6 days ago about iD but did not open an issue AFAIK.)

**Suggested change:**

- Do not suggest this auto-change whenever the node is on a barrier.
- Do the opposite now: Suggest to use barrier=entrance whenever there is a entrance=yes on a barrier

**Alternative to this change in iD:**

The other thing where  to update the wiki.

**Comment by quincylvania** [comment]
I think it's a clear problem to have a `barrier` tag that means the opposite of a barrier, but if there's no consensus on this then I'll just remove the deprecation for now.
