### ISSUE TITLE
show more information about used brand:wikidata/brand:wikipedia tags

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6507]
For example - maybe show start of wikipedia article on hovering above the tag in a popup? Or link Wikipedia article?

It would have chance to reduce effects of things like https://github.com/osmlab/name-suggestion-index/issues/2769

![Selection_001](https://user-images.githubusercontent.com/899988/59147532-2c088d80-89fd-11e9-8e7a-c8ff3701c886.png)
https://www.openstreetmap.org/edit?editor=id&way=584317196#map=19/42.68144/-83.19182

**Comment by quincylvania** [comment]
Hmm I really don't want to start adding tag-specific functionality to the raw tag editor. I personally think #5823 is sufficient for giving mappers more info about the currently-linked brand. We also have the `brand` field which surfaces the brand name.

**Comment by matkoniecz** [comment]
On looking at it again: showing it in normal tag editor also would be desirable

**Comment by bhousel** [comment]
We already show the brand's logo at the top of the inspector screen (cut off in your screen shot), and this is why - so users can easily identify that the brand is the correct one...  lots of discussion in #5167 about why we do this.

I don't think we need to add any extra capability to the raw tag editor (which most users aren't using anyway) or to add a special ui field which makes this brand link any more explicit than it already is.
