### ISSUE TITLE
Validation: railway=crossing + highway=crossing ?

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6508]
Location: https://www.openstreetmap.org/node/945141621

I wonder, if this validation is correct. What are your thoughts?

The way I read the short desc (wiki data) and the wiki, the railway=crossing already implicitly says highway=crossing, but for the specific case of railways. Or, to put it differently, there seem to be two keys to describe a crossing, one for non-railways, one for railways.

> Pedestrians can cross a railway here
(https://wiki.openstreetmap.org/wiki/Item:Q4948)

> A point where pedestrians may cross a railway.
(https://wiki.openstreetmap.org/wiki/Tag:railway=crossing)

And on the highway=crossing-tag it say:
> Similar tags
railway=crossing used where a footway, railway=level_crossing where a road crosses a railway.
(https://wiki.openstreetmap.org/wiki/Tag:highway=crossing)

I wonder if this validation is by accident or by design (eg. "each crossing should have the same highway=crossing tag so we can treat them all the same").

In any case, is the goal to have both keys with the value of "crossing" on the same node, after the validation? Because after following the validation the node above will look like this:
```
railway=crossing
highway=crossing
crossing=unmarked
```

**Comment by quincylvania** [comment]
@tordans Using both tags is not by design. iD doesn't intentionally recommend `railway=crossing` and `highway=crossing` on the same node, but if it's adding one of those due to a crossing ways fix it won't check to see if the other is already present.

iD aims for tags on intersection nodes like this:

- road/path: `highway=crossing`
- rail/path: `railway=crossing`
- rail/road: `railway=level_crossing`

Does that answer your question?

**Comment by tordans** [comment]
@quincylvania thanks for the help. I either missunderstand you – or there is a bug. 
My analysis:

- the crossing is `highway=footway` with `railway=tram`
- so IMO from what you wrote, it should be
  > rail/path: railway=crossing
  right?
- before my change https://www.openstreetmap.org/node/945141621/history the node had `railway=crossing`
- but iD does suggest to add the highway=crossing as well => which is a bug(?)

<img width="650" alt="Bildschirmfoto 2019-06-16 um 22 13 48" src="https://user-images.githubusercontent.com/111561/59569020-168e0600-9084-11e9-8205-88e0800712aa.png">

**Comment by quincylvania** [comment]
@tordans Oh, now I see what's going on. iD doesn't expect `crossing=unmarked` on a node to be a subkey of `railway=crossing`, just `highway=crossing`. That's where the suggestion comes from. This is a bug if people actually tag rail crossings this way—I'm not sure how common that is. I'm okay with not suggesting the tag.
