### ISSUE TITLE
Bunkers + landuse?

### ISSUE THREAD

**Issue by Hjart** [openstreetmap/iD#6509]
Why does iD want to tag bunkers (like i.e. https://www.openstreetmap.org/way/531205744) landuse=military? Adding building=bunker in most cases would be ok, provided that it's actually overground, but landuse=military, I consider a clear mistake.

**Comment by bhousel** [comment]
Because the `landuse=military` page says to dual tag them.
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dmilitary

**Comment by SilentSpike** [comment]
Initially reading this I thought it sounded wrong too. However after seeing the wiki it doesn't seem like an iD issue - more of a general tagging consensus issue (for what it's worth, it seems silly to me too). Perhaps take it up with the tagging list?

**Comment by Hjart** [comment]
I guess it's a mistake that this is the wiki at all more than a "general tagging consensus issue" I don't think many will agree with it. It was added in https://wiki.openstreetmap.org/w/index.php?title=Tag%3Alanduse%3Dmilitary&type=revision&diff=1312820&oldid=1304889 and I'll remove it unless there are objections to it : https://wiki.openstreetmap.org/wiki/Talk:Tag:landuse%3Dmilitary

**Comment by matkoniecz** [comment]
> Because the landuse=military page says to dual tag them.

I would interpret this page as "`landuse=military` may have this tags", not "this tags must have `landuse=military`.

For example see German-build bunkers in occupied Poland that nowadays are tourism attraction/abandoned/memorial sites and not used by military. `landuse=military` for them would be incorrect.

**Comment by Hjart** [comment]
We have tons of abandoned german WW2 (and some WW1) bunkers just sitting around in Denmark too (see i.e. https://commons.wikimedia.org/wiki/Category:Atlantic_Wall_in_Denmark). The vast majority are not in any kind of military area and many are freely accesible to the public. I can't even find any situation in which tagging a bunker landuse=military would be correct.

**Comment by bhousel** [comment]
see also #3663 where I wrote:
> I think maybe the wiki should be fixed if it is suggesting to put a landuse=military tag on every military feature.

**Comment by matkoniecz** [comment]
It seems a wider problem, multiple features defined `/data/presets/presets/landuse/military` may need to be modified.

> I think maybe the wiki should be fixed if it is suggesting to put a landuse=military tag on every military feature.

Is there a wiki page where it is still suggested?

**Comment by bhousel** [comment]
> Is there a wiki page where it is still suggested?

yes, the main page (that you just edited) still says to do it.
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dmilitary

<img width="300" alt="Screenshot 2019-06-10 15 18 18" src="https://user-images.githubusercontent.com/38784/59220447-fc8b8980-8b92-11e9-9019-a7c7852a37d1.png">

**Comment by matkoniecz** [comment]
I added explicit note that military=* is not always added

![Selection_005](https://user-images.githubusercontent.com/899988/59221551-d3392080-8bc7-11e9-98ee-3f9992ebc8fc.png)
