### ISSUE TITLE
Alt-G crashes iD

### ISSUE THREAD

**Issue by famo** [openstreetmap/iD#6519]
While in editing mode, pressing `Alt+G` crashes iD (not the browser).
Hot to reproduce:
1. choose new line or area feature
2. create first point
3. press `Alt+G`
4. iD crashes (freeze)

**Comment by Thorwynn** [comment]
Well I am not sure if this is related but ever since Chrome browser did it's last update, it has crashed to desktop for me several times while editing with iD. Another user on discord reports the same.

**Comment by bhousel** [comment]
This is a dup of #6584
