### ISSUE TITLE
Regression: Cannot enter key=value anymore

### ISSUE THREAD

**Issue by famo** [openstreetmap/iD#6520]
Since the new release pasted `key=value` pairs in the tag field are no longer parsed correctly.
Instead of splitting in `key` and `value`, the key just becomes `key=value`.

**Comment by quincylvania** [comment]
@famo [This was intentional](https://github.com/openstreetmap/iD/issues/6185#issuecomment-488692351). You can use the new text editor instead. Sorry if you like the old way!
