### ISSUE TITLE
Add deprecation warning for wifi=yes

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6524]
It looks like iD’s Internet Access field adds `internet_access=wlan` when set to “Wi-Fi”. So even though [the wiki page for `wifi`](https://wiki.openstreetmap.org/wiki/Key:wifi) equivocates, a deprecation warning for `wifi` would promote internal consistency within iD:

* `wifi=yes` → `internet_access=wlan` (combined with any existing value of `internet_access`)
* `wifi=free` → `internet_access=wlan` `internet_access:fee=no`
* `wifi=no` → ? (this doesn’t necessarily mean there’s no wired Internet access)

**Comment by matkoniecz** [comment]
Note that in case that `internet_access` already has some value it should not be overwritten.
