### ISSUE TITLE
man_made bridge is for areas only and is invalid for lines, so line tagged with man_made=bridge should not get a bridge icon

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6525]
![Selection_001](https://user-images.githubusercontent.com/899988/59330322-70dc3f00-8cf1-11e9-8f86-5d1c373d108a.png)

Spotted in https://github.com/gravitystorm/openstreetmap-carto/issues/3805#issuecomment-501146057

It is likely that it applies to all area-only objects.

**Comment by bhousel** [comment]
We could probably reduce the matchScore on `man_made=bridge` preset so it doesn't match that one, and matches the `highway=tertiary` instead.

**Comment by quincylvania** [comment]
From what I can tell, this isn't a match score issue. iD is treating the pictured feature as an area, so it can't match `highway=tertiary`. This could have happened if iD triggered a "tags suggest area" warning after the user added `man_made=bridge` and erroneously allowed connecting the endpoints. I just fixed a bug where a stale fix could appear, allowing the creation of invalid geometry.

**Comment by tyrasd** [comment]
reopening as the fix for this (67f7995559b6eddb98f756b0cddc583b70d9092c) was reverted in 24c72b64d10a2ef8cc30fa692fb1e0c4138e286c.

**Comment by tyrasd** [comment]
fixed in 5f1360ed0
