### ISSUE TITLE
barrier=guard_rail has no distinct sides, is rendered with arrows on one side

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6526]
For some barrier like cliffs sides matter. But for example `barrier=guard_rail` is symmetric and there is no difference in meaning depending on direction of way.

Based on rendering I though that someone mapped cliff instead of guard rail here.

https://www.openstreetmap.org/edit?editor=id#map=21/50.05410/19.92860

![Selection_002](https://user-images.githubusercontent.com/899988/59330659-5a82b300-8cf2-11e9-9173-0ec34290fe8c.png)

**Comment by BjornRasmussen** [comment]
Isn't the right side just the side that faces traffic?  Some guard rails in my area have two sides facing traffic, which is confusing to map, but the rest have just one side, which faces traffic.  I think of the spikes as the side that faces traffic.

**Comment by matkoniecz** [comment]
OK, Wiki even has

> If there is a clear inner/outer demarcation to the guard rail, construct the line so that the right side is inner and left side is outer.

Still, at least to me meaning of spiky symbols was unclear.

**Comment by Langlaeufer** [comment]
Spikes to the traffic is misleading! Looks like the posts. I opened a new issue
