### ISSUE TITLE
Outdated tags fix for diet will overwrite tags in some scenarios

### ISSUE THREAD

**Issue by tas50** [openstreetmap/iD#6532]
It looks like if there is a cuisine: vegetarian tag then the upgrade of the tags will overwrite any diet tags that already exists. See the screenshot below for what appears to be a incorrect fix.

<img width="388" alt="Screen Shot 2019-06-12 at 10 57 25 PM" src="https://user-images.githubusercontent.com/1015200/59407364-ceaa6e80-8d65-11e9-931b-491193ec1154.png">

**Comment by quincylvania** [comment]
This is #6462 and will be fixed in 2.15.2.

**Comment by tas50** [comment]
Oh sweet. Thanks @quincylvania
