### ISSUE TITLE
Is it correct to use word "grounds" in the description?

### ISSUE THREAD

**Issue by victor-yarema** [openstreetmap/iD#6533]
I am talking about descriptions like "Preschool/Kindergarten Grounds". We have it here: https://github.com/openstreetmap/iD/blob/becb968650665828612aaf0887a56dd195d9b763/data/taginfo.json#L130
It in turn shows up as a description of the building (!) as soon as the user adds the tag https://wiki.openstreetmap.org/wiki/Tag:amenity=kindergarten .
I find it a little bit confusing to see the word "grounds" on the building.
Here's an example: https://www.openstreetmap.org/edit?way=28758131 .
BTW, the OsmWiki page doesn't use the word "grounds".
I guess it also makes sense to review all other descriptions with word "grounds".

**Comment by bhousel** [comment]
Yes this is intentional..
We use this word specifically for tags where the convention is to tag the grounds, not the building.

**Comment by victor-yarema** [comment]
> Yes this is intentional..
> We use this word specifically for tags where the convention is to tag the grounds, not the building.
How about the OsmWiki page that clearly states that this tag is NOT solely about the grounds/area but it is about the AMENITY?
How should we map the amenities without own grounds?

**Comment by Adamant36** [comment]
> How about the OsmWiki page that clearly states that this tag is NOT solely about the grounds/area

**How to map** "The campus of a should be drawn as an area tagged with amenity=kindergarten."

Sounds like it's about the grounds/area to me. 

> How should we map the amenities without own grounds?

Id like to see an example. Likely, there will always be grounds for kindergarten schools. Places without dedicated grounds aren't really schools anyway and are better tagged as social facilities for children (like day care centers). At least in this case.

**Comment by SilentSpike** [comment]
I think the disconnect is because physically this feature is mapped as the area of the school grounds, but tagging wise you're tagging for the school entity not the grounds themselves (which could be considered as a separate entity).

I recently corrected some tagging which was for the grounds and not the school.

**Comment by quincylvania** [comment]
I agree these are somewhat confusing, but this is just a case of iD trying to help users make sense of OSM's messy tagging. If the grounds and amenity were actually two different tags, we could be clearer.

However, we might consider only using "grounds" for area features and not for the point features.
