### ISSUE TITLE
Validator sets highway=bus_stop on platform nodes even if already mapped (for the render) on stop_position nearby

### ISSUE THREAD

**Issue by emergency99** [openstreetmap/iD#6536]
The new validator/warning feature of iD wants people to set the highway=bus_stop tag onto platform nodes where bus=yes. However, that is not necessarily correct. The, in the pt_v2 scheme not even required tag needs to be on node, but as not every platform is a node (there are lines and polygons as well) it makes more sense to put it (if at all) onto the (optional but often set) stop_position tag.

- So I'd like to have this rule removed from the validator as it can, depending on local mapping styles, mess more up than it is useful.
Not mapping for the render, in p_t:v2 a platform needs: 
public_transport=platform
name=*
(bus=yes)
(network=*)
(tram=yes)

it can also be highway=platform/footway / area=yes if not only a node, so the legacy tag bus_stop should be phased out, rather than added in more!

If anything, the tag should check around a platform-node, if any node with that legacy tag is nearby. If yes, do nothing, if no, then you may add that tag.

I do not want to start another endless discussion about the p_t scheme here, that is being discussed on the topical mailing list anyway. 

Hope this makes sense to the devs here.

Kind Regards
RobinD. (emergency99)

**Comment by quincylvania** [comment]
Hi @emergency99! Thanks for the feedback, but I'm pretty confident that the existing behavior is correct.

`highway=bus_stop` is supposed to be a node where people wait for the bus, not the stop position. This is equivalent to `public_transport=platform`. While the newer tags might be preferable, over 2 million features still have the old tags so iD is supporting both for the time being. `highway=bus_stop` isn't even listed as deprecated on the wiki.

**Comment by emergency99** [comment]
The thing is, that if the platform is mapped as a line or polygon, the highway=bus_stop tag cannot exist on it as it needs to be on a node. So it would ne on the way out if everyone would map exact extends of stations anyway. And as you say, the newer tags are preferable. So if anything, the validator should just not insist on that feature!

**Comment by quincylvania** [comment]
@emergency99 iD is just following OSM tagging here. We cannot drop support for a tag with 2 million uses without a very good reason. Legacy applications may not support PT v2.

If you really want people to stop using `highway=bus_stop`, I suggest proposing a formal deprecation of that tag and automated edits to remove it from the database. This kind of change is outside the scope of what we can do in iD.
