### ISSUE TITLE
Karaoke box preset

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#6538]
Karaoke boxes, or karaoke lounges, are extremely common in Asia, but extremely rare in OSM. I think this is partly because there are no presets for it, so mappers end up tagging these establishments as bars. Currently the best accepted practice seems to tag it as `amenity=karaoke_box`.

**Comment by 1ec5** [comment]
In [this wiki page](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dkaraoke_box), you suggest pairing `amenity=karaoke_box`, but my understanding is that karaoke bars and restaurants should be tagged as bars and restaurants with the [`karaoke=yes`](https://taginfo.openstreetmap.org/keys/karaoke) tag. See also [this proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Karaoke_box). A separate preset does make sense for standalone karaoke boxes that only have karaoke and no food or drink, though.

**Comment by picsi** [comment]
I agree. I actually didn't propose it, I just followed what was outlined in the proposal when creating the wiki page.
