### ISSUE TITLE
Background is greyed out during resolve conflicting edits

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#6547]
![image](https://user-images.githubusercontent.com/1190866/59634568-f4d46380-9103-11e9-8ef5-0636f9251e12.png)

This might be a conscious design decision, but I couldn't find anything about greying out the background during resolve conflicting edits and the features were developed independently.

During conflicting resolve conflicting edits the user needs to examine the map data to see which version should be kept. This is more difficult when the map data is greyed out.

**Comment by quincylvania** [comment]
@pnorman Thanks, this was incidental and has been fixed.
