### ISSUE TITLE
Logos should be tied to the brand and not to the name

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#6550]
It seems that, at least for `amenity=fuel`, the logo displayed in iD should be tied to `brand` instead to `name`

For example, when using only `brand=Shell` we can't see a logo:

![](https://user-images.githubusercontent.com/982338/59695908-62929500-91c1-11e9-95d3-5e3438254477.png)

But when using `name=Shell` we have it displayed:

![](https://user-images.githubusercontent.com/982338/59695935-72aa7480-91c1-11e9-8f67-d235e0903363.png)

This is causing unwanted data to be inserted and confusion amongst the users here, where they think that _"if the logo isn't appearing then I am inserting a wrong data"_ + _"I need to use 'Shell' in name, since this is how it's properly displayed"_

Here in Brazil the fuel stations have a name which is distinct from their brands (ie, `brand` really isn't the same as `name`).

With the current state people are wrongly inserting objects with the same values in `brand` and `name`.

**Comment by bhousel** [comment]
These presets actually match on `brand:wikidata` tag + whatever the primary tag is (e.g. `amenity=fuel`.  It doesnt use `name` anymore)

**Comment by naoliv** [comment]
This new behavior will be available in a next update then?

**Comment by bhousel** [comment]
It’s been this way since last year.. even in the screenshot you showed, you can change the name.  It will stay as a Shell brand.  The `name` doesn’t matter.

**Comment by AntMadeira** [comment]
Hi there.
I'm revisiting this issue, because it still persists. 
The name field shouldn't be used to be filled with the brand, but that's what iD is (still) doing. Please, don't add names automatically when inserting brands and their respective icons.

**Comment by quincylvania** [comment]
> The name field shouldn't be used to be filled with the brand, but that's what iD is (still) doing. Please, don't add names automatically when inserting brands and their respective icons.

@AntMadeira The brand presets integration is undergoing a major upgrade at #8305. It may address this but I'm not certain.

**Comment by AntMadeira** [comment]
That's good to know.
Thanks, Quincy.
