### ISSUE TITLE
preview (v3): improvement of rapid workflow for create building + repeat + squaring

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6554]
Hi.
I just tried the new function "repeat" while creating a bunch of new buildings.
I wonder how I can manage to combine the rapid-repeat-create-building flow together with the squaring function (Ctrl+Q)?

My intent was to add a building with the pressed "repeat" button. Once the first building is done I want to square it, but it seems like I have to leave the "repeat" status for squaring, or I'm doing something wrong?

**Comment by quincylvania** [comment]
@sun-geo You're right, you can't square features while repeat drawing at the moment.

I wonder if the orthogonal drawing tool alone could be sufficient instead of squaring after every feature. (The tool is still in development and doesn't work exactly how it should yet.)

**Comment by BjornRasmussen** [comment]
I think that if the orthogonal drawing tool had all of the basic capabilities of the JOSM one, this would rarely be necessary.

**Comment by quincylvania** [comment]
> I think that if the orthogonal drawing tool had all of the basic capabilities of the JOSM one, this would rarely be necessary.

Exactly. We'll be building out its functionality before the v3 release.

Another helpful component would be if all features added while repeat-drawing were selected together when you finished and could be squared at once.

**Comment by quincylvania** [comment]
Closing this since I implemented an alternative solution. All added features are now selected after repeat-drawing and you can square them all at once.

![repeat add building squaring](https://user-images.githubusercontent.com/2046746/60736659-b45b4f00-9f25-11e9-940a-113e2953cd94.gif)
