### ISSUE TITLE
Make waterway=dam less confusing by changing its color

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6555]
It would be useful to give additional mapstyle hint that `waterway=dam` is supposed to be used for dam itself, not the reservoir.

Also, correctly(?) mapped dam area is rendered quite poorly, I would expect area rendering with something indicating that it is a built structure, for example brown/gray fill.

https://www.openstreetmap.org/edit?editor=id&changeset=67741985#map=17/-30.04786/29.12939

(in this case lake was mapped not as an area, but a broken line was probably confused mapper further)

`waterway=dam` used incorrectly for a dam lake:

![Selection_003](https://user-images.githubusercontent.com/899988/59837598-c9dd5000-934d-11e9-8389-607167d19602.png)

`waterway=dam` used correctly for a dam area, incorrect `waterway=dam` was removed from lake:

![Selection_004](https://user-images.githubusercontent.com/899988/59838153-c39ba380-934e-11e9-9fc1-5d5c22fe2958.png)

general view:

![Selection_002](https://user-images.githubusercontent.com/899988/59836663-39ead680-934c-11e9-850b-90eab7ac32ae.png)

**Comment by quincylvania** [comment]
I changed dams-as-lines to be grey. Dams-as-areas need to have `area=yes` in order to render as areas in iD.
