### ISSUE TITLE
Google warning should exempt Google Books

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6556]
[This route relation](https://www.openstreetmap.org/relation/2661060) is tagged `source=Automobile Blue Book Volume 4, 1918, Routes 708 and 775 (http://books.google.com/books?id=sNQNAAAAYAAJ)`, citing [a book on Google Books](https://books.google.com/books?id=sNQNAAAAYAAJ) that’s in the public domain due to its publication date. Yet any time the user modifies the route relation – such as by splitting one of its member ways – iD flags the relation as containing proprietary data from Google (Maps). An exception should be made for the phrase “Google Books“ and URLs with the domain “books.google.com”, since Google Books contains many public domain works.

**Comment by bhousel** [comment]
Can you just delete the source in this case?  Surely there is a more recent source of info about this route relation than a book from 1918.

**Comment by quincylvania** [comment]
This does seem like a far edge case but it was quick to add an exception.
