### ISSUE TITLE
Don't focus the `Add feature` button on `Tab` if save sidebar is open

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6560]
When saving edits, I always use `Ctrl-S`, type my message, and then `Tab` my way over to the `Upload` button and hit `Enter`.  This was super fast and efficient, but with the new `Add feature` option being selected on `Tab`, I have to use my mouse.

For most `Tab` operations, the `Add feature` bar isn't focused, but when switching over from `Cancel` to `Upload`, the bar _is_ focused, interrupting the flow.

**Comment by quincylvania** [comment]
I've been thinking a lot about the use of the <kbd>Tab</kbd> hotkey and I fear that lots of little workflows like this will be messed up. I recommend we try switching to the <kbd>`</kbd> key for adding features and use a different key for collapsing the sidebar.
