### ISSUE TITLE
Allow squaring multiple detached features at once

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6565]
We should allow users to select multiple features and square them all with one click. This would just apply the squaring operation to each feature, not square them together like #6226 or #3046. This would help solve #6554 along with #6563.

**Comment by BjornRasmussen** [comment]
This would be complicated in situations where a user selects 20 buildings that are detached and then 2 attached to each other.  What would happen to those 2?

**Comment by quincylvania** [comment]
@BjornRasmussen I left it so it lets you square connected features together, it just won't necessarily have the nice results expected by #6226.
