### ISSUE TITLE
Add operator:type to kindergarten / school / college / university

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#6566]
Please, consider adding the `operator:type` field to the `amenity=kindergarten` / `school` / `college` / `university` templates.

Possible values would be: `public` / `private`

Reference: https://wiki.openstreetmap.org/wiki/Key:operator:type

Thanks!

**Comment by Adamant36** [comment]
@ignaciolep, in case your interested another possibility for tagging that kind of information is the ownership tag. Which I personally prefer over operator:type.
