### ISSUE TITLE
Gender for toilets should be a check box to allow for 2+

### ISSUE THREAD

**Issue by tas50** [openstreetmap/iD#6569]
Right now in most editors you can select multiple options for the allowed genders in a toilet, but iD makes it a radio form so you can only select male, female, or unisex. This doesn't really make sense. Most people tag a bathroom as a single amenity and then select the gender of the bathrooms. This is generally male and female, which you can't do in iD.

**Comment by picsi** [comment]
Unisex should mean both male and female, no?

**Comment by quincylvania** [comment]
> Unisex should mean both male and female, no?

There is no consensus, [according to the wiki](https://wiki.openstreetmap.org/wiki/Key:unisex). It kinda depends on whether `male` and `female` indicate "who can use this" or "whether there are designated facilities".

**Comment by tas50** [comment]
If I saw there was a unisex bathroom I’d assume there was a small 1 person bathroom or a family bathroom and not 2 distinct bathrooms for men and women. I think that might be a common assumption in the US where the unisex bathroom is usually it’s own thing.

**Comment by bhousel** [comment]
Discussed a bit in #5221 (and #4076 and #3954)
We are encouraging people to map each room as a point node and use the radio button to say who may use the room.  AFAIK it's been this way since iD was launched about 6 years ago.
