### ISSUE TITLE
Which better JOSM or iD to edit OSM ? What is the difference ?

### ISSUE THREAD

**Issue by FatimaAlmashi** [openstreetmap/iD#6570]

**Comment by BjornRasmussen** [comment]
iD is good for editing at a small scale.  You can add some buildings, some roads, fix invalid data, and everything else.
JOSM is meant for larger scale edits.  It isn't as simple to use as iD, but can let you change tons of features at once.  For example, it's possible to download an entire neighborhood, and then select buildings that are in a certain size range and not attached to any other features, and then square all of them at once.  Or, you could use plugins to quickly trace building footprints faster than with iD using a plugin.
