### ISSUE TITLE
iD editor graphical interface expansion proposal (not an issue)

### ISSUE THREAD

**Issue by EmpireFall** [openstreetmap/iD#6571]
I have very little hope that the spectrum of features outlined in this succinct proposal will get implemented, as it would be quite the task to do so, however, I think that it would really help to demystify what a lot of the stuff in the left hand sidebar represents and therefore the respective elements upon which they pertain

the descriptions in openstreetmap wiki articles can sometimes be difficult to grasp due to the lack of images made available in them and sketchy presentation or lack of proper application of logic on the readers side, which can lead readers to misinterpret what certain tag values actually represent

therefore, I was hoping that, aside from using 'keys' and 'tags' to set the values of elements on the map, would it not be an added convenience to provide an interface into the iD editor that better graphically portrays all the information in the left sidebar (of an element), so that users would not only 'see' and expanded 'visual' representation of an element's properties (e.g. number of lanes, lane speed limits, road markings, parking lane configuration etc, somewhat like the following http://osm.mueschelsoft.de/cgi-bin/render.pl) but also be able to 'construct' what they intend to implement onto the map through a selection of graphic images, that when selected will output the value that the graphic represents as an additional or modified tag in the 'all tags' section  (I like  to play a lot of video games, most modern games such as city-building games, place a lot of emphasis on providing intuitive graphical means for the user to convey what they would like to do)

**Comment by BjornRasmussen** [comment]
Something similar to this is already planned, but with an emphasis on mapping the individual lanes of a road.  
See #387

**Comment by EmpireFall** [comment]
😳😁 that is pretty much the gist of the notion I had in mind, I have yet to read all the other entries regarding the iD editor

[ https://user-images.githubusercontent.com/2046746/56142696-f773da80-5f53-11e9-8145-e8361e371d31.png ]
I think that the above image was a great example of what I had in mind

thanks for pointing this out to me, so as to avoid any sort of ambiguity that can occur when designating tags to elements, it is reassuring to know that steps are being taken towards adding an interface to the iD editor that is more graphically oriented

**Comment by quincylvania** [comment]
@EmpireFall Thanks for your interest in ways to make iD even better! I'm all for taking usability cues from video games. Interfaces are really hard to get right and games still manage to make editor software "fun".

Features like the lane editor are definitely on our agenda, but the iD team is quite small and resource-constrained so development can take a long time. It'll happen eventually.

I'm closing this issues since it isn't really actionable and we have #387. Feel free to open more issues for any specific ideas you have!

**Comment by EmpireFall** [comment]
Understood Quincy, I'll keep a keen eye on #387 , thank you for the consideration 👍🏾
