### ISSUE TITLE
Complain about an unreasonably small buildings for types indicating bigger buildings

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6573]
Some 3D mappers instead of using `building:part` use `building` areas.

For example see https://www.openstreetmap.org/way/302589861/history https://www.openstreetmap.org/way/302589873/history

"hospital" with 4 or 8 square meters is always wrong and it would be useful to have an explicit warning.

Note that some building like kiosks may be extremely small so it makes only for cases where `building` tag was explicitly specified and area is below say 10 square meters or area is smaller than say 0.5 square meter.

JOSM issue: https://josm.openstreetmap.de/ticket/17846#ticket

**Comment by quincylvania** [comment]
While I agree with the basic ideas of this warning, it seems too nitpicky for iD and low impact overall. The specific case you pointed to seems uncommon and can be fixed manually. Future cases could be mitigated by better 3D mapping instruction.

This is the kind of issue that would be better suited for after #6483, when people can argue over tagging minutia outside the scope of core iD functionality.
