### ISSUE TITLE
Add preset for fords as ways

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6576]

**Comment by BjornRasmussen** [comment]
This seems more like a new kind of structure rather than a preset.  Similar to not adding `man_made=bridge` to highways that are bridges.

**Comment by Adamant36** [comment]
> This seems more like a new kind of structure rather than a preset. Similar to not adding man_made=bridge to highways that are bridges.

Could be. I'm not that up on my structures. So I went with a preset. I can change the name of the issue or whatever though if need be.

**Comment by quincylvania** [comment]
@Adamant36 I'm pretty sure [`ford=yes`](https://wiki.openstreetmap.org/wiki/Tag:ford%3Dyes) shouldn't be added as lines independent of highways. However, we can add an unsearchable preset in case someone comes across an untagged ford.

**Comment by Adamant36** [comment]
@quincylvania, while I'm perfectly fine with how implemented it, the way I originally imagined it was that I split a track road at points, select the resulting way in the middle, and then add a ford to it through a preset. In that case it would still have a highway tag attached to it. I probably could have explained it better in my original post. Can something like that be done or am I miss understanding how ways and highway's work?

Thanks

**Comment by quincylvania** [comment]
@Adamant36 So a feature can only have one preset and changing presets replaces all the tags. This means that selecting a `ford=yes` preset would remove any `highway` tag. We _could_ have preset for say `highway=track` + `ford=yes`, but that takes us down the rabbit hole of endless way+structure combinations.

Can you just use the Structure field for this?

![Screen Shot 2019-06-26 at 9 11 20 AM](https://user-images.githubusercontent.com/2046746/60182661-b9682200-97f2-11e9-84bd-ac2c6c7a5798.png)

**Comment by Adamant36** [comment]
Oh ok. That makes sense. Thanks for explaining it. I'm fine with using the Structure field to do it.
