### ISSUE TITLE
Location of note is to the right of screen centre

### ISSUE THREAD

**Issue by jnicho02** [openstreetmap/iD#6578]
When I add a note, it is created to the right of where the screen is currently centred. This isn't a problem on a monitor, but on a mobile phone it leads to panning the screen over a could times then dragging and dropping the note back...which can be quite a pain on a small device. If the map is zoomed out then the distance is bigger.

Is it intentional to create the note away from centre?...or maybe the centre-point is not being returned to the function?

**Comment by SilentSpike** [comment]
I think you should be able to drag the note - though not sure how it works on mobile. Even if true, perhaps UX can be improved somewhat.

**Comment by jnicho02** [comment]
Well yes.....I can do pan, pan, pan, select, drag, pan, drag, drop on a tiny screen, with my clumsy fingers, whilst in the middle of the street....but that sort of negates its usefulness as an outdoor note maker :)  I've been using it because Vespucci can be a bit too much control for a simple "remember to update the name of this shop when you get home" use case.

**Comment by RobJN** [comment]
Hi @jnicho02. Is this an iD editor issue or a website issue? If the later then this isn't the right place to post. There is another GitHub repo for the main site.

As for adding Notes via mobile you can try an app. Street Complete or OSM Contributor both allow this. I'm sure other apps will too.

**Comment by Nakaner** [comment]
OsmAnd can add or close notes as well.

**Comment by jnicho02** [comment]
Bah, sorry, Rob is right! I conflated iD with all editing on the website. Will re-raise elsewhere
