### ISSUE TITLE
Search for coordinates in D°M.MM' format gets wrong position. 

### ISSUE THREAD

**Issue by DFyson** [openstreetmap/iD#6582]
Searching for coordinates such as N 45° 25.495'   W 075° 41.740' returns the incorrect location. Both OSM and Google maps are correct.

**Comment by jguthrie100** [comment]
If you change the format to _45° 25.495' N, 75° 41.740' W_ it works

**Comment by DFyson** [comment]
Good to know for now, thanks. Although the other format should still work as it does on other platforms. And at the very least not return an incorrect position.

**Comment by quincylvania** [comment]
@DFyson Thanks for reporting! We use the [sexagesimal](https://github.com/mapbox/sexagesimal) package to interpret DMS. I opened an issue there: https://github.com/mapbox/sexagesimal/issues/8

**Comment by quincylvania** [comment]
@bhousel Fixed this in https://github.com/mapbox/sexagesimal/commit/7d8e87dc77c21e247f3ccc508e6e79d9c7ddbe87.
