### ISSUE TITLE
Unable to resolve no-tag warning by deleting feature

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6588]
Touching [this way](https://www.openstreetmap.org/way/577294299) triggers an error about a feature with no tags. The error comes with an option to “Delete this feature”, but clicking it does nothing, presumably because I’m zoomed in to z20 and can’t see enough of the feature to delete it. Either I should be allowed to delete the feature, or the option should be disabled with some sort of note explaining why.

**Comment by BjornRasmussen** [comment]
The old behavior was that the way would be deleted just like that, and up to hundreds of nodes outside of the downloaded area would get deleted.  This was very bad, so @quincylvania changed it to the new behavior.  
I think that a note explaining why the object couldn't be deleted would be a nice improvement.

**Comment by quincylvania** [comment]
Okay, now the deletion fix will be enabled or disabled based on the circumstances when the feature is selected, not when the issue was created. If it's disabled there's a tooltip explaining why.

**Comment by 1ec5** [comment]
Thanks!
