### ISSUE TITLE
Add multitouch support for zoom while editing in Edge and IE11

### ISSUE THREAD

**Issue by omgitsgela** [openstreetmap/iD#6598]
Multitouch support works when viewing the map on openstreetmap.org, but when you go into edit the map, multitouch no longer works. It would be wonderful for editing on touch compatible devices to enable the following:

1. Single finger drag - pans the map around
2. Double finger drag - Zoom in and out of the map. Snaps to the closest zoomlevel on release.
3. Single finger tap - On an object, selects that object. On empty space, deselects any selected objects.

**Comment by quincylvania** [comment]
@omgitsgela Thanks for opening this! iD already supports these gestures, at least on iOS devices. If it's not working for you then it might be a device- or browser-specific bug. Can you give more details about your setup?

**Comment by quincylvania** [comment]
Hmm it looks like iD doesn't support touch gestures on IE 11 or Edge, that must be what you mean. This could be fixed via #5505.

**Comment by thibaultmol** [comment]
For me this problems also happens on chrome though (77.0.3865.105 (Official Build) (64-bit))  on a chromebook with a touch screen

**Comment by quincylvania** [comment]
So I'm pretty sure I fixed this but I don't have a touchscreen Chromebook or Windows device to test on.

@omgitsgela @thibaultmol Would you mind seeing if pan and zoom touch interactions work for your devices on our development preview site? https://2-x--ideditor.netlify.com/

**Comment by jidanni** [comment]
On chromebook (ChromeOS 120), no matter one finger or two, we can drag east, west etc. but at the same time we end up also zooming.

So far on chromebook have have ended up backing out of all edits I start. A 0% upload rate.
