### ISSUE TITLE
Move the "Zoom to this" button to the toolbar

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6601]
The current button looks sort of out of place and takes up vertical height. With the contextual toolbar, we can show a Zoom To item when a feature or note is selected.

![Screen Shot 2019-07-01 at 11 23 15 AM](https://user-images.githubusercontent.com/2046746/60448102-e6ea0c80-9bf2-11e9-930d-fc14bc1cb92e.png)

**Comment by quincylvania** [comment]
This seems better.

![Screen Shot 2019-07-01 at 1 08 57 PM](https://user-images.githubusercontent.com/2046746/60454283-74ccf400-9c01-11e9-9d8d-c9444d974615.png)

**Comment by bhousel** [comment]
Nice 👍 I like this better too..

**Comment by quincylvania** [comment]
Reflecting more on this, it's not great for a zoom control to live alongside edit controls. I'm going to try putting this in the map alongside the other zoom controls. It'd be disabled when nothing is selected. We'll have the space after #7368.

<img width="84" alt="Screen Shot 2020-02-26 at 4 21 14 PM" src="https://user-images.githubusercontent.com/2046746/75400450-26691580-58b4-11ea-8b74-e5f050603f4c.png">
