### ISSUE TITLE
Add "edit raw node" button

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6602]
The editor has
v All fields
v All tags
v All relations
But that is still not the entire node.

If at the very bottom there was an "advanced" or "edit raw node" button,
the user could edit 100% of the node,
without needing to buy a computer to install JOSM, etc.

Just like wikipedia has Edit raw watchlist.
Or Developer Tools lets one Edit raw HTML in browsers.

**Comment by quincylvania** [comment]
@jidanni Do you mean edit the longitude and latitude of the node?

**Comment by jidanni** [comment]
Sure, any anything else hiding in the corners of the node currently
inaccessible via the editor.

Implementation could be as simple as one big HTML textbox,
where the user is editing the raw XML.

Also this should work for nodes that don't exist yet,
but that the user is in the process of adding via the editor.

**Comment by BjornRasmussen** [comment]
What else is there that people should be _allowed_ to edit?

**Comment by bhousel** [comment]
we've been through this many times before - see also #5117 #4197 #3088 #2590 #2583
No iD doesn't allow people to directly edit latitude and longitude. 
We allow users to edit everything else.

**Comment by jidanni** [comment]
Anything they want to add, as long as it is valid XML.

For instance maybe they want to paste in a long block of XML items that
they have ready and would be tedious to do with the 'help' of the editor.

As far as lat/lon people mentioned, here is a challenge:

Let's say you discover a point in the middle of the Pacific ocean.
It turns out it was simple +/- minus coordinate error.
We need to remove the "-" from the latitude to get the point back in the
proper hemisphere.
Alas, we are helpless without purchasing our own computer to install a
program just to change that one single ASCII.

The best one could do with the mouse would be place the point on the
closest pixel, thus ruining the lesser digits of both of the coordinates.

**Comment by 1ec5** [comment]
> Let's say you discover a point in the middle of the Pacific ocean. It turns out it was simple +/- minus coordinate error. We need to remove the "-" from the latitude to get the point back in the proper hemisphere. Alas, we are helpless without purchasing our own computer to install a program just to change that one single ASCII.

[Level0](http://level0.osmz.ru/) is a good tool for the situation you’re describing. It’s a Web application, so you can run it on any computer just like iD.

**Comment by jidanni** [comment]
(OK, I'll need a few days to learn/review if Level0 is better thing to
suggest than just a MediaWiki style textbox...)

**Comment by 1ec5** [comment]
Level0 is indeed just a big textbox. I use it frequently to undelete nodes and relations, since Potlatch 1 can only undelete ways.

**Comment by jidanni** [comment]
Looking at https://wiki.openstreetmap.org/wiki/Level0
it will take our user who just wants to edit the lon/lat at least an hour to understand all of that.

If iD just provided a textbox for lon/lat editing like it does already in this image:
![10884-0](https://user-images.githubusercontent.com/1230959/61179116-8b764080-a62e-11e9-8205-5cf5d3781493.jpg)
the user could solve his problem in 35 seconds!

**Comment by jidanni** [comment]
And well...... trying level0 ........ tried it for five minutes ........ conclusion:

I could do lots of damage to the map!

Not suitable.

Not even suitable if one could understand what all the buttons mean.

Sorry.

**Comment by JamesKingdom** [comment]
> I could do lots of damage to the map!

Which is why bill isn't allowed to enter coordinate data directly. https://github.com/openstreetmap/iD/issues/4197#issuecomment-320346010
