### ISSUE TITLE
DigitalGlobe Standard & Premium Imagery Removal 

### ISSUE THREAD

**Issue by ilansim** [openstreetmap/iD#6605]
I saw you recently removed two background imagery layers in iD.
These imagery despite sometimes being outdated had (in some regions of the world) very good lighting conditions, good orthophoto qualities (no tilt) and the imagery had very low offset. 

Could you please reintroduce DigitalGlobe Standard Imagery & Premium Imagery?
Currently these layers still exist in JOSM so it should be possible.

**Comment by tastrax** [comment]
Digital Globe is no more - its now Maxar

https://www.digitalglobe.com/company/maxar-family

No doubt JOSM will also remove their links at some stage as they swap to the new provider.

**Comment by quincylvania** [comment]
@ilansim Like @tastrax said, the change was made at the request of the provider, Maxar. OSM editors are subject to the generosity of imagery providers.

Try out the Maxar backgrounds and see what you think! Kevin said to expect content parity so if you see a regression you can let Maxar know, but there's nothing iD can really do about it.

![Screen Shot 2019-07-02 at 8 57 03 AM](https://user-images.githubusercontent.com/2046746/60514436-7a7d1500-9ca7-11e9-80f2-5d4115bd97b8.png)
