### ISSUE TITLE
use some icons from OSM Carto

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6606]
Looking at https://osmlab.github.io/name-suggestion-index/index.html that is using iD icons, it seems that some may be used from OSM Carto map style, though I am not sure how many fill fit also iD requirements. Some examples from quick look at https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop :

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/variety_store.svg `shop=variety_store`

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/beverages.svg `shop=beverages`

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/beauty.svg `shop=beauty`

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/interior_decoration.svg `shop=interior_decoration`

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/carpet.svg `shop=carpet`

I looked up to interior_decoration on nsi list.

OSM Carto is CC0 licensed.

**Comment by bhousel** [comment]
Nice thanks @matkoniecz - I didn't realize these were CC0 licensed.. I'll pull some of the better ones into temaki.

**Comment by matkoniecz** [comment]
In general @nebulon42 made many, many great SVG icons (and there were also other contributors!).

**Comment by quincylvania** [comment]
A couple other useful ones I noticed are [perfumery](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/perfumery.svg) and [coffee](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/coffee.svg) for the corresponding shops.

**Comment by quincylvania** [comment]
Would it be possible/desirable to add OSM carto icons as another icon source for iD? Like be able to reference `osmc-shop-coffee` and have the build do the rest?

**Comment by bhousel** [comment]
> Would it be possible/desirable to add OSM carto icons as another icon source for iD? Like be able to reference `osmc-shop-coffee` and have the build do the rest?

I took another look and I don't really like any of them, but the coffee one is ok.
I think I'll just add one like that to temaki later today.

**Comment by quincylvania** [comment]
Okay, that's fine. I think most of them look alright but they also overlap with icons we already have. If I want to use others from there I'll just submit them to temaki manually.
