### ISSUE TITLE
Railways (rails) in train depot are detected as error (wrongly)

### ISSUE THREAD

**Issue by 07pepa** [openstreetmap/iD#6607]
There is bug.... it detects a problem if rail crosses building (and yes it is in 99% of times wrong) but when it is in depot there is litteraly a rail in building...

 I suggest add depot class of building that **require** to contain certain type of communication inside of it.. 

subclasses would need to contain precise type of communication
(if it is car,train/airplane/ship depot a road/railway/waterway or road for airplanes)

There is no any valid workaround there is no tunnel, bridge or something... just rail, road or part of river inside of building... (except to ignore "issue" in map)

**Comment by BjornRasmussen** [comment]
The solution is to set the rail underneath as "covered" .

**Comment by BjornRasmussen** [comment]
This should probably made more obvious, though.

**Comment by quincylvania** [comment]
@07pepa A rail crossing a train depot is still ambiguous without more information. The rail could be on a bridge over the building or a tunnel under the building. If it goes through the building you can just connect the rail to the edge of the building, then add `indoor=yes` or `covered=yes` to the inside part.

I agree we should make this easier. We're tracking that general concept over at #5924.

**Comment by 07pepa** [comment]
@07pepa understood and agreeing with @BjornRasmussen  should be more obvious :) THX
