### ISSUE TITLE
add undo center function

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6611]
Thanks for move the center function to the new v3 top button bar. :-)
(https://github.com/openstreetmap/iD/issues/6601)

I wonder if i could make sense, to add a function to switch back(center undo), to the previous (not centered zoom level) view?

**Comment by quincylvania** [comment]
@sun-geo Hmmm is this a feature you find yourself needing? This might be useful but I'm not sure how necessary it is.

**Comment by sun-geo** [comment]
I think it's just nice-to-have.

If you are mapping in any zoom-level you like, it could be interesting to zoom-in to the preset-zoom level of the center function. Afterwards when the details are maybe checked, (and this is not more your preferred zoom level for upcoming work) the same button (center) could change the functionality (and text) to undo/uncenter and send you back to your preferred zoom level before...

I'm sure if is really needed and if it makes sense, but maybe give it a try (if the implementation would not so time consuming). And if it doesn't work together with all other UI-work flow revert the implementation...

**Comment by quincylvania** [comment]
I've been using the Center tool a lot more recently and I think we should do this issue. It's frustrating to end up far away from where you were editing with no great way to get back.

**Comment by BjornRasmussen** [comment]
How about if the center button becomes a "return" button for some time after the button is pressed?  This would allow for using the same button for all center related purposes.

One note: if the button instantly returns to the "center" state after the map is moved, this wouldn't be that useful.  I think that keeping it as "return" until the object is deselected or gets decentered by the button would be good.  If people want to center the object while the button is in "return" mode, they could just use it twice.

**Comment by quincylvania** [comment]
@BjornRasmussen That sounds like a pretty good solution 👍

**Comment by quincylvania** [comment]
I added this for the toolbar item. Still need to make it work with the keyboard shortcut but it's a good start.

**Comment by SilentSpike** [comment]
👍 Very nice QOL addition

**Comment by sun-geo** [comment]
Thank you

**Comment by quincylvania** [comment]
Here's a demo I captured but had trouble uploading before.

![undo center demo](https://user-images.githubusercontent.com/2046746/62964123-ffd80700-bdc7-11e9-848e-2b0b541a15b6.gif)
