### ISSUE TITLE
Don't flag very close points on different layers/levels

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6612]
It's valid for features to be in exactly the same location if they vary on the z-axis.

**Comment by 1ec5** [comment]
Tags to consider in this heuristic: `ele`, `layer`, `level`. Maybe also `height` for mounted features such as antennae, sirens, and flags, since it’s easier to ascertain than the absolute elevation? `repeat_on` is interesting but maybe nonessential for this issue.

**Comment by quincylvania** [comment]
@1ec5 I hesitate to use elevation only because I've seen overlapping points from different imports with slightly different `ele` values, though that's probably not very common.

**Comment by 1ec5** [comment]
Oh that’s a good point. I’ve seen that happen with coincident POIs imported from GNIS. Come to think of it, it wouldn’t be unreasonable to expect mappers to use `layer` to explicitly avoid this warning, since that’s what avoids crossing ways warnings for bridges and buildings.
