### ISSUE TITLE
'Use a bridge' message should provide the bridge it had in mind

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6617]
User sees
```
Service Road crosses 食水嵙溪
￼
Connect the features
Use a bridge or tunnel
Reposition the features
Ignore this issue
Highways crossing waterways should use bridges, tunnels, or fords.
```
User clicks 'Use a bridge or tunnel' and nothing happens.
Perhaps a ready made bridge should appear where the message thinks it should.
Then the user could
- grab and adjust its shape, if necessary.
- hit Undo to make it go away.

Indeed providing the bridge would be much better than the user doing it himself, as it is not that simple as first laying down a bridge, and then laying down a road.

**Comment by quincylvania** [comment]
I'm pretty sure this is similar to https://github.com/openstreetmap/iD/issues/6501#issuecomment-500100028. I think we should try it.

**Comment by jidanni** [comment]
Yes!
All I know is that user A makes a stream.
And later user B makes a highway that crosses the stream.
So even before saving, at some point suddenly the editor should "burst in" and say, "would you like me to create a properly attached bridge for you? Just remember to stretch it if it doesn't fit correctly..."

**Comment by quincylvania** [comment]
This was done by @CarycaKatarzyna in #7055 🎉
