### ISSUE TITLE
unlock entries with deleted wikidata id

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6619]
optionally also

- propose deleting `wikidata` tag
- describe deleted `wikidata` tag as deleted in description field
- highlight `wikidata` tag field in red

Example of API response indicating deleted entry https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q60606547&format=json

Example of edit deleting Wikidata IDs that become invalid, requiring use of raw tag editor - https://www.openstreetmap.org/changeset/71896957

**Comment by quincylvania** [comment]
I agree this warning might be useful.

I do wish that OSM could/would automatically check and fix these kind of issues on the whole database instead of relying on editors like iD. It's not great to bother mappers with a little technical thing where an automated fix would have 100% accuracy.

**Comment by bhousel** [comment]
Oh I'm just seeing this now.. Let's not do this..
iD shouldn't be making calls out to Wikidata just to double check the validity of their QIDs.

The NSI project already does this during the `npm run wikidata` step and can raise these things as errors.  We should just mass edit anything where a QID has changed or gone away.

**Comment by matkoniecz** [comment]
> We should just mass edit anything where a QID has changed or gone away.

Is there somewhere feed of Wikidata ids that stopped being valid? Or is it requiring manual processing of Wikidata dumps?

If someone would be interested in list for (sem)manual processing - https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/ has some areas (I can add more if someone is intrested)

**Comment by bhousel** [comment]
> Is there somewhere feed of Wikidata ids that stopped being valid? Or is it requiring manual processing of Wikidata dumps?

I don't think there is a feed - we use the mediawiki api.  
NSI has 4307 entries currently with `brand:wikidata`, so that doesn't take too long to process.

The other thing is that - sometimes Wikidata will remove or merge a QID and it's really their mistake, so we have to ask them to put it back.  (like https://github.com/osmlab/name-suggestion-index/issues/3065).  So it's pretty rare that a QID will go invalid, and when it does, we don't necessarily want to change OSM right away.

**Comment by matkoniecz** [comment]
> I don't think there is a feed - we use the mediawiki api.

This works fine for NSI, not so well for detecting wikidata ids that went bad across all OSM , with 1 156 355 distinct values ( https://taginfo.openstreetmap.org/keys/wikidata#values ).
