### ISSUE TITLE
Speed limit fields should default to miles per hour in Puerto Rico

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6626]
The Speed Limit and Advisory Speed Limit fields default to kilometers per hour in Puerto Rico, but speeds are measured in miles per hour in Puerto Rico, just like in the mainland United States. (Distances are metric, but speed limits, height restrictions, and weight restrictions are not.)

[![santurce](https://user-images.githubusercontent.com/1231218/60751711-7e42bd00-9f6f-11e9-9364-3da3e276bb38.png)](https://www.mapillary.com/map/im/SROF-1QWqXWUG6fCyKsh9w)

**Comment by 1ec5** [comment]
Thanks @quincylvania! By the way, there are [a few more countries and territories](https://en.wikipedia.org/wiki/Miles_per_hour#Road_traffic) that use miles per hour, mostly in Central America and the Caribbean.

**Comment by quincylvania** [comment]
@1ec5 Oh great, I'll add more of these.

**Comment by 1ec5** [comment]
In case it helps, [here’s a similar GeoJSON](https://gist.github.com/1ec5/561f34a30231631f935a72149d8296c1) I made a while back of regions that use non-metric speed limit units or non-Vienna-style speed limit signs. Not sure whether it’s simplified enough for iD’s needs, though.
