### ISSUE TITLE
adding new multilingual name languages

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#6632]
I'd like to add `aus` Australian languages, and a few others to `Multilingual Name` language dropdown, but can't find where this is set, could someone please point me to it?

**Comment by 1ec5** [comment]
iD gets the list of languages from [wmf-sitematrix](https://github.com/osmlab/wmf-sitematrix/), which is really just a list of Wikipedia language editions. There aren’t any Wikipedias in Australian languages yet, so they aren’t in the site matrix. #2457 tracks migrating the name field to CLDR. Then wmf-sitematrix would only populate the list of Wikipedias in the Wikipedia field.

**Comment by andrewharvey** [comment]
Thanks @1ec5, so it looks like for now it's not possible to change this just for iD. I'll close this in favour of #2457 which as you say, will untie the list from Wikipedia language editions.

However given [Australian languages](https://en.wikipedia.org/wiki/Australian_Aboriginal_languages) aren't in CLDR as far as I can tell from https://www.unicode.org/cldr/charts/latest/supplemental/index.html, that still wouldn't resolve this issue :thinking: .

**Comment by 1ec5** [comment]
Hm, that’s unfortunate. Maybe a special case is warranted if there are enough mappers who would use iD to enter Australian-language names. So far [`name:aus`](https://taginfo.openstreetmap.org/keys/name%3Aaus)-tagged features appear to have been edited by 35 people, which isn’t a lot, but maybe you have a better sense of how many people would be inclined to use the tag if it were more accessible?

**Comment by andrewharvey** [comment]
> but maybe you have a better sense of how many people would be inclined to use the tag if it were more accessible?

To be honest I don't think it would make any difference at all. We already have a note on the Australian Tagging Guidelines page to use `name:aus` https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines#Aboriginal_.26_Torres_Strait_Islander_Place_Names

I guess I was hoping this would be an easy one line change somewhere to add it in, for completeness.
