### ISSUE TITLE
Use different icons for Tree and Park

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6633]
This is just confusing. We can still use a tree icon for Park as long as it's notably different.

<img width="324" alt="Screen Shot 2019-07-08 at 10 11 54 AM" src="https://user-images.githubusercontent.com/2046746/60817022-e0b2dd80-a168-11e9-8042-48c01210ec35.png">
<img width="89" alt="Screen Shot 2019-07-08 at 10 10 30 AM" src="https://user-images.githubusercontent.com/2046746/60817017-ddb7ed00-a168-11e9-9e66-c56436c2e821.png">

**Comment by bhousel** [comment]
oh yeah I agree.. Let's use `maki-pitch` (generic activity icon) for parks.

**Comment by quincylvania** [comment]
> Let's use maki-pitch (generic activity icon) for parks.

That would be an improvement, though we already use that icon for park-related things like pitches, running tracks, and fitness stations. It seems more important to have unique preset icons when possible in v3 since the ribbon relies more heavily on them.

**Comment by quincylvania** [comment]
This was done in 394396326c03970740e4a35a67f0f856f964452c by using a tree+bench design for park.

<img width="846" alt="Screen Shot 2019-12-09 at 12 48 49 PM" src="https://user-images.githubusercontent.com/2046746/70459497-4e4d9780-1a82-11ea-8d31-5c1cdb2a4c97.png">
