### ISSUE TITLE
Enable all feature types before starting walkthrough

### ISSUE THREAD

**Issue by thomas-hervey** [openstreetmap/iD#6634]
I believe the walkthrough currently assumes that all feature types are visible when a user starts. If one is hidden, a user cannot select it. Consider when updating walkthrough https://github.com/openstreetmap/iD/issues/6025.
<img width="556" alt="Screen Shot 2019-07-08 at 12 28 03 PM" src="https://user-images.githubusercontent.com/1840672/60834294-a30c7f80-a17d-11e9-8a09-95e7c544b10e.png">

**Comment by quincylvania** [comment]
@thomas-hervey Thanks for reporting! I either never saw this or promptly forgot about it after you first posted it. It was a quick fix.
