### ISSUE TITLE
Wants to add extra tag when upgrading to bike+foot path

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#6635]
When editing a Cycleway with `foot=designated`, iD thinks it's an 'incomplete' Cycle & Foot Path and wants to upgrade by adding `bicycle=designated`. However `bicycle=designated` is already assumed on Cycleways so this tag is extraneous.

![](https://i.imgur.com/mjeKnfi.png)

![](https://i.imgur.com/tAfYzrt.png)

**Comment by quincylvania** [comment]
@rivermont This is intentional, see #6172. I know the tag isn't critical but neither does it hurt anything.
