### ISSUE TITLE
amenity=preschool validator warning should also add preschool=yes

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6636]
The validator warning about the deprecated `amenity=preschool` tag should suggest adding [`preschool=yes`](https://wiki.openstreetmap.org/wiki/Key:preschool) in addition to setting `amenity=kindergarten`. Otherwise, the suggested fix would potentially lose information.

**Comment by quincylvania** [comment]
Did this. Also added a checkmark field for Preschool.

**Comment by DaveF63** [comment]
Kindergarten is a preschool. This tag duplicates data.

**Comment by tas50** [comment]
@DaveF63 see https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpreschool

**Comment by DaveF63** [comment]
@tas50 See https://en.wikipedia.org/wiki/Kindergarten

**Comment by quincylvania** [comment]
> Kindergarten is a preschool. This tag duplicates data.

> The suggestion on the wiki seems super wrong to me as here on the west coast of the US a pre-school and a kindergarden are VERY different things.

In the US these are similar but are generally considered different things. This tagging scheme isn't perfect but at least it accommodates both situations. In places where there's a difference, the `preschool` tag differentiates them. In other places the tag can be ignored.

**Comment by DaveF63** [comment]
@quincylvania 
1) OSM doesn't tag to suit interpretations on one side of the pond. 
2) Duplication in OSM is to be avoided at all costs. it just leads to errors. I thought you'd have learnt about that after the platform/footway mess.

**Comment by quincylvania** [comment]
@DaveF63 iD is following the advice of the wiki here. Feel free to disagree. I don't care to argue further and I don't have time to.
