### ISSUE TITLE
iD suggests bus=yes for trolleybus and share_taxi stops

### ISSUE THREAD

**Issue by Prince-Kassad** [openstreetmap/iD#6639]
In OpenStreetMap, highway=bus_stop is not just used for bus stops but also for trolleybus and share taxi/marshrutka stops. These are defined separately in the public transport system (they use route=trolleybus and route=share_taxi) but reuse highway=bus_stop because there is no highway=trolleybus_stop or highway=share_taxi_stop. These are very common in Eastern Europe.

However, iD will suggest to add bus=yes to a highway=bus_stop even if it is a stop only for trolleybuses and/or share taxis, and even if the bus stop node is already correctly mapped as a member of a public transport relation tagged route=trolleybus.

Note that iD recognizes trolleybus=yes (not share_taxi=yes) on a highway=bus_stop and will not suggest to add bus=yes if this tag is present.

Example illustrating the problem: https://www.openstreetmap.org/node/1667500083

So my suggestion:

* share_taxi=yes, if present, should inhibit the suggestion for bus=yes just like trolleybus=yes does currently
* If at all possible (I don't know the technical details) there should be a check to see if a highway=bus_stop is a member of only trolleybus relation, so iD knows that it's likely that no buses actually stop here and it's not a bus=yes.
* maybe rethink the bus=yes suggestion in general? It definitely will need ground survey in many cases, as e. g. it could also be a stop only for school buses (I see this often in Germany), in which case it should probably not be present in the database to begin with, or at least not as highway=bus_stop which suggests a stop for public buses.

**Comment by BjornRasmussen** [comment]
Using highway=bus_stop for these is incorrect, as far as I know.  `public_transport=platform` means any place where people wait for transit, so that tag would be more appropriate.  Unfortunately, osm carto is unwilling to support this tag at this time.

**Comment by quincylvania** [comment]
@Prince-Kassad Thanks for your concern, but transit tagging is really tricky in OSM and I'm not sure we can support different behavior.

We try to follow the [advice of the wiki](https://wiki.openstreetmap.org/wiki/Public_transport) when it comes to public transport. The tag `highway=bus_stop` was supposed to have been replaced by `public_transport=platform`, but little effort has been made to update usage in the database. So iD tries to support both, leading to these issues.

> Note that iD recognizes trolleybus=yes (not share_taxi=yes) on a highway=bus_stop and will not suggest to add bus=yes if this tag is present.

Yes, this is how you should silence the warning for trolleybuses. There is also a "Trolleybus Stop" preset that uses the right tags for you.

> Using highway=bus_stop for these is incorrect, as far as I know. public_transport=platform means any place where people wait for transit, so that tag would be more appropriate.

I agree with @BjornRasmussen here. While there's no "incorrect" tagging in OSM, a "bus stop" should only be assumed to mean a place where a bus stops. You can use `public_transport=platform` + `share_taxi=yes` instead.
