### ISSUE TITLE
"Return to profile" link wrong

### ISSUE THREAD

**Issue by tricki** [openstreetmap/iD#6640]
**Steps to reproduce:**
- Go to https://www.openstreetmap.org/user/YOURUSERNAME/account and log in.
  - Replace "YOURUSERNAME" with your username.
- Set "Display Name" to the name of another user and submit the form.
- Click on "Return to profile".

**What happens:**
You're taken to the profile page of the user whose name you entered.

**What should happen:**
You're taken to your own profile page.

**Comment by bhousel** [comment]
Sorry @tricki, this repository is for the iD editor only... 
Issues with the OpenStreetMap website can be reported here:  https://github.com/openstreetmap/openstreetmap-website
