### ISSUE TITLE
changeset comment too easy to get reused without noticing it until it is too late

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6642]
Users find out only too late that their previous changeset comment has been reused, perhaps many times.

And now there is no way to fix it.

"Sludge retaining wall" on my supermarket, day care center edits! - he exclaims.

At least have a checkbox
[ ] and use this comment for my next edit.

Or OK, still fill in the box with the comment from last edit, but force the user to at least click somewhere in the textbox to acknowledge he is aware that it is going to be reused again.

All I know is that it had a blue background (selected text) when it happened.

**Comment by quincylvania** [comment]
I suppose the intention is to make it faster to upload subsequent changesets of the same task. However, I agree it's also easy to forget to change the comment—I've done this myself.

Let's just leave the initial comment blank. It's easy enough to click in the box and then click the last-used comment from the suggestion list.
