### ISSUE TITLE
Make the changeset number clickable

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6644]
This linking is not intuitive:
![14200-1](https://user-images.githubusercontent.com/1230959/61168191-f8c99900-a57c-11e9-90e4-2c7020d13969.jpg)

It would be best if the number was the clickable part.

So instead of saying:

[View Changes on OSM](https://www.openstreetmap.org/changeset/72203264)
Your changeset #: 72203264

please say something like:

View Changes on OSM:
Your changeset #: [72203264](https://www.openstreetmap.org/changeset/72203264)

**Comment by quincylvania** [comment]
I just made them both clickable.

<img width="271" alt="Screen Shot 2019-08-08 at 3 02 45 PM" src="https://user-images.githubusercontent.com/2046746/62734095-bfeed980-b9ed-11e9-96b8-aedd78a11895.png">
