### ISSUE TITLE
Help panel: Areas: add Converting a Point to an Area

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6645]
In the help panel one sees

- **Points or Areas?**
- Adding Areas
- Modifying Areas
- Deleting Areas

Please also add

- Converting a **Point to an Area**
Select both and use the C shortcut.

https://github.com/openstreetmap/iD/issues/839#issuecomment-511093625

**Comment by bhousel** [comment]
Let's not do this.   I don't think there is consensus whether to map every kind of feature as a point or area, and it's hard to explain to new users why they would choose one method over another.
