### ISSUE TITLE
Allow entering a second phone number of the same type

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6647]
Often places have [multiple phone numbers](https://wiki.openstreetmap.org/wiki/Talk:Key:phone#Plain_old_multiple_phone_numbers) but in iD one can only enter one*.

Therefore upon entering the first one, a + etc. button should appear so the user can enter a second one etc.

Note I am not talking about one mobile, one main landline, etc.

I am talking about two main landline, two mobile, etc. with no difference between the two.

After iD collects the numbers from the user, they would become a string joined by semicolons, as the value to a single tag.

**Comment by jidanni** [comment]
Currently the user has to press on the "i for info" button, click to see more info on the wiki, and read way down to "The character ';' is sometimes used to separate multiple phone numbers.". And then try it.

Compare this to e.g., entering phone numbers in Google Contacts. There is always a friendly "+" for the more the merrier.

**Comment by quincylvania** [comment]
I guess there's no harm in using a `semiCombo` field so mappers can enter multiple semicolon-separated values. We could consider doing this for `email` too.

**Comment by bhousel** [comment]
> I guess there's no harm in using a `semiCombo` field so mappers can enter multiple semicolon-separated values. We could consider doing this for `email` too.

TBH I think this is a mistake.. Anything is OSM can technically be a semicombo.  But you do what you want 🤷‍♂

**Comment by BjornRasmussen** [comment]
I'm personally also against this.  I've never actually run into any situation where this is needed when mapping in the US and in Europe.

**Comment by quincylvania** [comment]
Looks like there are a fair number of `phone` values with semicolons, but mappers can always just add them manually. Let's keep it simple for now and leave it as-is.

**Comment by jidanni** [comment]
OK, but as we [observe](https://www.openstreetmap.org/way/704109665),
- OSM website properly parses and displays these semicolon "arrays".

But iD editor:
- Does not parse these arrays, and just shows them as a raw string. In fact as the boxes are only designed for short width strings, any of these long strings (two phone numbers separated by a semicolon) become very hard to edit. Compare this to how nicely iD sets up address entry, Zip Code, City, etc. nicely stacked.

Anyway, with no guidance as how to add a second entry, expect various non-standard methods to accrue in the database. 

In fact it currently takes the user a large research effort to finally determine ";" is the proper way.

**Comment by quincylvania** [comment]
@jidanni Yes, some parsers will understand the semicolons but some may not. The bigger issue is ease-of-use. If only one phone number is needed almost all the time then it's nicer to keep the field simple. Also, if the two phone numbers are equivalent then just one is needed anyway.

If you're having trouble editing long field values then you can drag the divider to resize the sidebar.

If other people run into issues then we could think of better ways to address this in the future, but for now let's move on.
