### ISSUE TITLE
Recommend the most used image source for a region

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6648]
**Situation:**

In some regions there is no "best" image source in the editor layer index, so Bing is used as a default. (This is how it works, right?)

I am watching a set of changesets in a region that is quite complex to decipher and – in some place where it is needed – hard to revert/fix. The root cause seems to be, that the mapper used Bing as a base layer but in the area Esri is used most often and the better choice.

So I wonder, what could iD do, to help in such situations?

**Idea / Brainstorming:**

Could iD maybe recommend the image layer based on which image layer is most used in this region (in the last 6 month)? Maybe even select it automatically or give some info about it.

I wonder, where could such an information come from?
- Does iD load the changesets of the visible region, so could iD evaluate the changeset "images used" tags?
- Is there an external API that could provide the "image used" tags of all changesets of a region?

--- 

Is this worth thinking about or and edge case that is too hard to solve?

**Comment by manfredbrandl** [comment]
If there is no „best“ source than the „most used“ source should be used. The „most used“ Layer should be calculated automatically before each release and iD should select it. The „most used“ used source can be shown with „+“ instead of „*“. I do not know if calculating the most used source can be done in reasonable time.

**Comment by tohaklim** [comment]
this seems subjective, as sometimes freshest imagery can have horrible offsets or poor quality.
Proper vintage data and an offset database would be more useful?

**Comment by 1ec5** [comment]
Some prior discussion: osmlab/osm-planning#18 osmlab/editor-layer-index#130.

**Comment by tordans** [comment]
Thanks for you thoughts.

Most ideas require some external service that generates static information and requires to be updated regularly. That would certainly work, but is a lot of work to build for this use case.

Those ideas are discussed elsewhere (thanks 1ec5), so maybe lets set a different focus here: Could we create the information as a by product by analysing data that is already in the editor. 

Could we use the changeset data of the currently loaded bbox to use the `imagery_used` + creation data to create a list of "image layer most used in the last 6 month for the visible are".

This list could then be used to suggest or auto-select an image layer.

Some first look at the data: Id does not load changeset data ATM.

Looking at the the API call ([example](http://preview.ideditor.com/master/#background=Berlin-2019&disable_features=boundaries&locale=en&map=20.48/52.47762/13.44972)) I see calls to 
- https://www.openstreetmap.org/api/capabilities
- https://www.openstreetmap.org/api/0.6/map?bbox=13.447265625000501,52.47608904123887,13.452758789063,52.47943475885923

Both do not include the changeset data.

We could call the API again:
- Docs https://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets
- Same example from above https://www.openstreetmap.org/api/0.6/changesets?bbox=13.447265625000501,52.47608904123887,13.452758789063,52.47943475885923&time=2018-07-21T00:00:00+00:00&closed=true (only closed changesets that where created in the last 12 month for the bbox from the example).

However, this result also includes changesets that are not really or only very roughly related to the area that I am mapping. Eg https://osmcha.mapbox.com/changesets/72072716/ is a huge area which uses Bing and has no direct relation to my mapping-view.

Therefore the imagery_used seems returns:
> BDOrtho IGN;PNOA Spain;OpenStreetMap (Standard)
Berlin aerial photography 2018;Berlin aerial photography 2019
Berlin aerial photography 2019
Berlin aerial photography 2019
Berlin aerial photography 2019
Berlin aerial photography 2019
Bing Aerial
Bing aerial imagery
Bing aerial imagery
Bing aerial imagery
Bing aerial imagery
Bing aerial imagery
Bing aerial imagery;Esri World Imagery;USGS Topographic Maps;U.S. Forest Service roads
Mapbox Satellite
Saxony latest aerial imagery;Maxar Premium Imagery (Beta)

Which does suggest Bing as a very valid source where I expected the local "Berlin aerial photography 201x" (the "best" in the Editor layer index) to be the winner.

So even if we call the changesets api, the results still need to be worked on …
- stronger bbox filter after we receive the data - is this feasible?
- cleanup/normalization of imagery_used-values and mapping to the layer ids of the editor layer index

Looking into this, this idea does not look too promising. Any thoughts?

**Comment by matkoniecz** [comment]
> In some regions there is no "best" image source in the editor layer index

It seems the fix would be to add best image source to editor layer index.

**Comment by bhousel** [comment]
Closing for now.. 
1. I just don't see a way of doing this without keeping track of imagery use metrics somewhere, and
2. I don't see any reason to believe that imagery that people have used previously is necessarily still the best imagery to use.
