### ISSUE TITLE
camp pitch tags

### ISSUE THREAD

**Issue by Martin868** [openstreetmap/iD#6649]
In the iD editor, if you tag a node with the "camp pitch" composite, you will see there is a typo in the tag that it creates. the tourism= tag is misspelled torism and consequently is not a valid tag.

**Comment by tastrax** [comment]
https://github.com/openstreetmap/iD/issues/6608

**Comment by BjornRasmussen** [comment]
This has been fixed, but not updated to osm.org.  I've been converting torism=camp_pitch to tourism=camp_pitch worldwide, and others might have also, so there are currently no instances of this in the osm database.

**Comment by quincylvania** [comment]
@Martin868 Yep, thanks for noticing. This was just a typo, sorry about that! We'll do a release in the next week or so with the fix.
