### ISSUE TITLE
"Unable to connect to API" never disappears on intermittent connection failures

### ISSUE THREAD

**Issue by Prince-Kassad** [openstreetmap/iD#6650]
If you have an internet connection with intermittent packet loss, and that triggers the red "Unable to connect to API" bar, and then you drag the screen and the request succeeds, iD works as normal (i. e. you can edit, save etc.) but the red bar doesn't disappear and stays for the entire session. This is purely a minor visual annoyance.

**Comment by quincylvania** [comment]
@Prince-Kassad Thanks for reporting!

> This is purely a minor visual annoyance.

I'd say a false error message like this is a real usability problem. Users could rightly become confused, frustrated, or fearful of losing work.
