### ISSUE TITLE
species:wikidata for attraction=animal

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#6652]
A common mistake when tagging zoos is for editors to link the animal attraction enclosure directly to the wikipedia/wikidata entry for the animal, instead of using `species:wikidata`. This could be fixed by replacing the usual Wikidata/Wikipedia fields with some a field like 'Wikidata/Wikipedia entry for this taxon'.

**Comment by picsi** [comment]
This mistake should also pop up in the validator, too.

**Comment by quincylvania** [comment]
Related: #6093. I think "Species Wikidata" would be a bit more self-explanatory than "Subject Wikidata"—maybe we should just add it under `moreFields`. It'd be useful for mappers who want to add the tag and everyone else could pretty much ignore it.

**Comment by aphisit182534-ui** [comment]
https://github.com/user-attachments/assets/69db5482-e504-460b-8e0c-e6760aa02981
