### ISSUE TITLE
Help user draw constant width buffers along a linear feature

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6653]
Looking at the [slob job](https://www.openstreetmap.org/way/704461199) I did trying to make a constant width buffer area along roads (a street market that spills over onto the sidewalks),
![24494-0](https://user-images.githubusercontent.com/1230959/61211256-b7c6b580-a731-11e9-9ab2-1140bfb5bccd.jpg)
a long-term wishlist item for iD would be a way to do it for the user. He just needing to specify a width, one or both sides, and a start and end point along a linear feature.

**Comment by BjornRasmussen** [comment]
This sounds too complicated.  I think that having an operation for "create parallel way" like in JOSM, which would create a way parallel to an existing way more intuitively would be better.

**Comment by BjornRasmussen** [comment]
So basically, I think that rather than making this a new drawing mode for new ways, this should be a new operation for existing ways.

**Comment by jguthrie100** [comment]
> So basically, I think that rather than making this a new drawing mode for new ways, this should be a new operation for existing ways.

Thats what I'd think. Right click the road and select "draw buffer" or "draw parallel way" which creates the buffer area. The intuitive bit would be working out how to determine the desired depth of the buffer.

**Comment by jidanni** [comment]
Actually we see the editor uses buffer areas all the time:
![17936-1](https://user-images.githubusercontent.com/1230959/61213559-f5c6d800-a737-11e9-96e2-24626593c7f0.jpg)
They are just not available yet as something one can leave on the map.

As far as how the person drew that parallel road, I can only wince... so yes add that ability too.

**Comment by jidanni** [comment]
> working out how to determine the desired depth of the buffer.

Maybe the user could just "pull it out, wider and wider with his mouse,"
until finally clicking to finalize the width.

**Comment by quincylvania** [comment]
I'm not sure this kind of feature is necessary or suitable for iD, but we should think about it more. Also, note that the "partial fill" for areas is calculated by the browser and isn't something iD could turn into data.

**Comment by manfredbrandl** [comment]
Maybe we can have a warning for features with width=<anyvalue> if there are area objects partially inside and partially outside the described area?

**Comment by quincylvania** [comment]
Just found #1931. Closing this in favor of that.
