### ISSUE TITLE
Brand icons not displaying in Firefox private window

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6660]
Brand icons seem to display fine in a normal Firefox window on Windows 10, but not in a private one for some reason. 
![2019-07-19](https://user-images.githubusercontent.com/30259065/61531754-a2c17f00-a9dc-11e9-8cc7-24ab2ca5c4d9.png)

**Comment by quincylvania** [comment]
@Adamant36 Hmm the the brand icons are all hosted remotely on Wikimedia, Facebook, and Twitter. It's likely that private Firefox blocks images referenced on 3rd-party sites. If that's the case, then there's no way to show the brand logos since iD won't be redistributing them.

**Comment by Adamant36** [comment]
It looks like there is the same issue with the Bing street level images to. So more then likely your right that it's blocking 3rd-party referenced images. 

![2019-07-19 (2)](https://user-images.githubusercontent.com/30259065/61572329-9e36ae00-aa50-11e9-9587-c11ec8d30115.png)
