### ISSUE TITLE
Inspecting relation members, parent relations, or items of a multiselection

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#6661]
Inspecting relation members, parent relations, or items of a multiselection is currently hard, because the original selection is lost. 

Dragging an item of the member, membership, or multiselection list on the map could open a second inspector overlay there to inspect or edit the feature which is represented by the item.
While the second inspector is focused/hovered selection halos can highlight related element.
Context menu operations might be disabled while the second inspector is open.

**Comment by quincylvania** [comment]
While I agree it can be tricky to regain a prior selection in some cases, I don't think we should allow multiple inspectors. Perhaps we can have a quick way to undo a selection change instead.

**Comment by quincylvania** [comment]
> Perhaps we can have a quick way to undo a selection change instead.

Let's target this with #6783 or something similar instead.
