### ISSUE TITLE
Make large features selectable at low zoom

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#6662]
The recently added editing at low zoom levels would be even more useful if large features were selectable at that zoom level.

When clicking on the map, a small area around that position could be downloaded, all small feature be discarded, and lare features with an edge near to the click position could be offered in a list for selection like a search result list.

A small area means a reasonable area to get all edges around the click position.

**Comment by quincylvania** [comment]
@slhh This behavior seems like it would be unexpected. This workflow would be:

`Click on an empty section of map` -> `Something random appears and gets selected`

This would be doubly unexpected if the user just accidentally clicked or clicked to deselect something. Perhaps people would get used to it and some would find it useful, but I'm afraid some people would be frustrated and stop mapping or just generally have a sense that iD it touchy and therefore more stressful to use.

**Comment by slhh** [comment]
@quincylvania Good point!

A query tool button on the top bar could initiate the selection workflow, and this would be similar to the query workflow of the OSM website.

**Comment by quincylvania** [comment]
@slhh Perhaps! I really don't think this is something most people need, but I have been considering a sort of "toolbox" feature where the user could customize the toolbar with optional, advanced tools. Stuff like this and #6541 could live there.

**Comment by quincylvania** [comment]
I've thought a lot more about this and it seems easier for mappers to just zoom in than use a "query" tool. The OSM website needs this tool because it doesn't have direct selection.
