### ISSUE TITLE
Complain about free-floating `barrier=gate`

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6666]
Currently free floating `barier=gate` have separate icon but no explanation what is wrong with them. It would be nicer to give user feedback what is wrong.

Similar to #6319 but in this case it is object tagged on correct geometry (node) but with node not attached to other objects.

In image below top-left has freefloating `barrier=gate`, bottomright is correctly attached to a way.

![Selection_006](https://user-images.githubusercontent.com/899988/61579903-b4557480-ab0b-11e9-8300-adfcfa4424e1.png)

JOSM has already warning for that situation so it should be considered OK to complain about this.

Situation on the image was fixed in https://www.openstreetmap.org/changeset/72462119

**Comment by quincylvania** [comment]
Thanks, @matkoniecz, this is the same as #6319. Under the hood in iD we take "geometry" to mean `point`, `vertex`, `line`, `area`, or `relation`, not just the OSM types. So if a point should be a vertex based on tags like this then iD would trigger a warning.
