### ISSUE TITLE
MedPlus Pharmacy preset

### ISSUE THREAD

**Issue by txtsd** [openstreetmap/iD#6667]
Here's the wikidata page: https://www.wikidata.org/wiki/Q65684234

`brand` is `MedPlus Pharmacy`
`name` is `MedPlus`
`dispensing` is `yes`

**Comment by matkoniecz** [comment]
Note - such issues belong rather to https://github.com/osmlab/name-suggestion-index

(BTW - can you look at https://github.com/osmlab/name-suggestion-index/pull/2910#issuecomment-513753133 ?)

**Comment by quincylvania** [comment]
@txtsd Yep, iD gets brand presets from the name-suggestion-index project.

**Comment by txtsd** [comment]
Thanks!
