### ISSUE TITLE
Split the graph into multiple levels

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#6669]
iD has recently be changed to download more data. Putting all this data in the graph seems to be a performance issue up to freezing iD.

We should split the graph into up to four levels:

0. All modified, new, or deleted elements.
1. All non-modified elements which are required for rendering or most operations.
2. Further non-modified elements which are required for the member editor or some special operations requiring more data than usual (e.g. straighten)
3. Further downloaded elements, potentially stored in a compressed format.

Levels 0 and 1 together essentially contain what was stored in iD's graph in the past.
The current access functions of the graph should be changed to check level 0 first, and level 1 afterwards if not found in level 0. Most parts of iD (rendering, most operations, etc.) do only need to access these levels and can remain unchanged, and their performance isn't degraded by the number of elements in level 2 and 3.

A second set of access functions should check all levels, but move elements from level 3 to 2 when they are requested.

History operations can be limited to the level 0 graph. This does likely remove much overhead of merging downloaded elements into the history.

**Comment by quincylvania** [comment]
Hmm interesting idea, but I'm not sure this would be a performance savings and it would certainly cause months worth of work and bugs.

I'm not even sure that merging downloaded data is a performance bottleneck. It's likely that all the `merge` event handlers such as re-rendering are at issue. But in any case we shouldn't invest in a huge core change that may or may not fix a problem we may or may not have.

I agree that performance should be improved, but let's please take a methodical approach to diagnosing and remedying specific issues.

**Comment by slhh** [comment]
@quincylvania 
This concept is targeting multiple potential performance issues, essentially including the performance of rerendering and other D3 operations.
Let's discuss a simplyfied, easy to implement variant first, where the benefit is hopefully more obvious.
Assuming that handling the history isn't a bottleneck, level 0 can be integrated into level 1.
Assuming that compression isn't a benefit, level 3 can be integrated into level 2.

Then we have a level 1 containing all the elements which were used to be the graph before extra downloads were recently added. The essentially unchanged code of the graph can handle this level 1, and all the code accessing the graph can be kept unchanged, with a few exceptions mentioned below.
D3, most operations and also other parts of iD do only need to access this smaller sized level 1 graph, which is a performance improvement.

In addition we have a level 2 containing the extra downloads then. Assuming that handling the history isn't a bottleneck, level 0 can be integrated into level 1. level 2 graph is essentially a single global object storing the elements. A modified set of access functions has to be added to the graph to check level 1 first and level 2 afterwads. Only the relation editor and a few operations requiring extra data need to be reworked to use these access functions, and the download operations need to be modified to put the data of the extra download into level 2.

Another benefit of the concept is, that different rules could apply for the levels. Most parts of iD do likely rely on vertexes and parent relations being completely downloaded. Changing this would be quite hard because many parts of iD are affected, but we could drop this rule for level2. Only the few parts of iD accessing level 2 would need to consider this. E.g. this would allow to download direct members of routes only, which is a significant reduction in the number of elements to be downloaded and stored. The relation editor doesn't need more than the direct members.
