### ISSUE TITLE
playground=structure as a way

### ISSUE THREAD

**Issue by joostschouppe** [openstreetmap/iD#6670]
The [playground wiki](https://wiki.openstreetmap.org/wiki/Key:playground) allows the use on point, line and area. iD gives a warning for unclosed ways. So I think that warning should probably be dropped.

**Comment by quincylvania** [comment]
Sounds fine. Note that iD will now treat these features without `area=yes` as lines even if they were previously added as areas.

**Comment by tordans** [comment]
@joostschouppe i know this is more of a tagging discussion - so off topic here - but why would we want structures as ways? 
I understand them as basically buildings. So they are either nodes (as in „not yet fully mapped building“) or areas. What example do you have in mind for a way?

I assumed this was consensus but unfortunately it cannot be confirmed  / checked since https://taginfo.openstreetmap.org/tags/playground=structure does not split areas and ways.

**Comment by joostschouppe** [comment]
Thanks @quincylvania .
@tordans : maybe you're right for the particular case of structure. The playground=* tag contains some things where line is a probable candidate. You could export the data from overpass and do some checks as to the number of closed ways.

**Comment by quincylvania** [comment]
Yeah, I wouldn't map these as lines but I figured there are countless variants of what could be called a playground "structure" so in some instance it might make sense.

We've been trying to be more permissive with OSM tagging lately and just go with whatever people ask for unless there's a big issue with it. Let me know if you change your mind.

If only OSM had an `area` type this would be so much easier 😭

**Comment by tordans** [comment]
@joostschouppe 
> maybe you're right for the particular case of structure. The playground=* tag contains some things where line is a probable candidate.

In case you dont have a strong opinion to change this structure-value, I would really prefere it the way it was before.

> The playground=* tag contains some things where line is a probable candidate.

I agree; but IMO not for "structure". Also advanced mapper can always add their tags manually. The question for me is, how many choices does a new mapper need to make (as in, between how many preset-variations does she need to choose) before mapping a swing?

I hope that playground tagging will get a bit more common and more standardized once we have some data consumers that help define what way of mapping will help to consume the data. Maybe https://github.com/QwantResearch/qwantmaps/issues/71 will be the first prominent case.

**Comment by quincylvania** [comment]
> I agree; but IMO not for "structure". Also advanced mapper can always add their tags manually. The question for me is, how many choices does a new mapper need to make (as in, between how many preset-variations does she need to choose) before mapping a swing?

Good point. In the v3 search we'd be asking the user to pick between three things.

![Screen Shot 2019-07-26 at 10 20 41 AM](https://user-images.githubusercontent.com/2046746/61958308-10e2e480-af8f-11e9-9ed4-332cd4f13486.png)

> In case you dont have a strong opinion to change this structure-value, I would really prefere it the way it was before.

Thinking even more about it, I agree. This seems more like a case of #6629 where the wiki recommends something that's confusing to support and mostly unnecessary in practice.

I'm going to change this back and let advanced mappers add this to lines manually if they want to. You can always ignore the warnings.
