### ISSUE TITLE
Download issues in preview

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#6675]
The currect preview has some OSM data download issues of visible tiles, even without selecting anything.

I have tested with Firefox 68.0.1 on Windows 10.

Btw, when a tile download has failed a reload button should be offered in case the download is not periodically repeated.

**Comment by quincylvania** [comment]
@slhh Can you point us to some locations that exhibit this behavior? I don't think I've seen it.

Also, if a tile fails then we should just make sure iD keeps requesting it rather than bugging the user.

**Comment by quincylvania** [comment]
Closing this since I haven't seen it happen and no followup occurred. @slhh Let us know if you see this again!
