### ISSUE TITLE
Incorrect Tile. 

### ISSUE THREAD

**Issue by AlmarRido** [openstreetmap/iD#6676]
It looks like it's an incorrect tile/tiles. Street names are mixed in with it. Didn't find this, but issue had not yet been solved after 3 months. Pretty sure this cannot be fixed by someone out of OSM itself. 
![Here you go](https://user-images.githubusercontent.com/53245024/61760640-bb0a1300-adbb-11e9-8137-85d936054bc8.PNG)

**Comment by bhousel** [comment]
This issue tracker is for the iD editing software, not for the OpenStreetMap website or tile generation software.  

You might be able to ask on http://help.openstreetmap.org/ or one of the other OSM community forums to find out what's going on with the data in this location.
