### ISSUE TITLE
Arabic numbers rendering incorrectly on line labels

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6679]
Instead of an Arabic number character, iD renders "undefined" backwards.

https://www.openstreetmap.org/edit#map=19/32.40140/48.36779

![Screen Shot 2019-07-25 at 10 46 34 AM](https://user-images.githubusercontent.com/2046746/61884129-a4ea7880-aec9-11e9-9a7a-7a01ae423f4f.png)

**Comment by bhousel** [comment]
cc @mapmeld
