### ISSUE TITLE
Perhaps add tip on combining features on final screen before combining

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6680]
Maybe say "Press C to combine these features" somewhere on this screen.
![X2](https://user-images.githubusercontent.com/1230959/61890537-38f42880-af3a-11e9-8648-089142fc6847.jpg)
(Yes, it is listed in the Help panel already.)

**Comment by quincylvania** [comment]
In iD 3 the merge function will be in the toolbar when multiple features are selected, making this command more discoverable.

![Screen Shot 2019-07-25 at 1 21 37 PM](https://user-images.githubusercontent.com/2046746/61894807-2993c180-aedf-11e9-882c-6c9af9c96f5b.png)

**Comment by jidanni** [comment]
by the way, this screen is also a great place to allow the user to reorder the items to make a point merged into a rectangle or a rectangle merged into a point or a line merged into  an area r an area merged into a line , whatever.
