### ISSUE TITLE
Focus issue with text tag editor

### ISSUE THREAD

**Issue by jleedev** [openstreetmap/iD#6685]
1. Ensure that the "all tags" section is open and set to text mode
2. Select a linear feature
3. Click on the endpoint of the feature
4. Press <kbd>A</kbd> to continue drawing from the end

Behavior in 2.15.3:
- When the endpoint is selected, the "select feature type" panel comes up
- Pressing <kbd>A</kbd> works

Behavior in master (f35f415):
- When the endpoint is selected, instead of "select feature type", the regular sidebar comes up for that node
- Since "all tags" is set to text mode, it steals focus: All text entry goes there
- Even clicking on the node a second time does not put focus back in the main editor window

There are really two issues here:
1. "All tags" in text mode steals focus in text mode after every selection change
2. Clicking on the same feature again to focus the editor doesn't work

**Comment by quincylvania** [comment]
@jleedev I couldn't reproduce this anymore on `master` or `2.x`. Are you still seeing it? If so, what browser?

**Comment by jleedev** [comment]
A second click on the node now focuses the node and not the text tag editor. Point 2 seems fixed.

The first point is still happening: The text tag editor takes focus after every focus change. (macOS, Chrome and Firefox.) Master be3a79c.

**Comment by jleedev** [comment]
Aha, it only happens when "Fields" is collapsed.

**Comment by quincylvania** [comment]
> Aha, it only happens when "Fields" is collapsed.

@jleedev Oh thanks, now I can reproduce this! Looks like it's actually working as intended…

https://github.com/openstreetmap/iD/blob/c735dc8c963dbf2e0c80c1bfc6476d417fa28d44/modules/ui/raw_tag_editor.js#L147-L153

@bhousel What do you think of not autofocusing the tag editor so people can use the shortcuts immediately?

**Comment by bhousel** [comment]
> @bhousel What do you think of not autofocusing the tag editor so people can use the shortcuts immediately?

Ah yeah, I thought this would be helpful when I built it initially but I realize now that it messes things up if the user just wants to perform an operation on something with a hotkey.  I've removed that code in a54561ce7, thanks for the ping..
