### ISSUE TITLE
Shift Select select hidden feature

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6692]
Situation
1. hide some features
2. use shift select to select nodes in an area with hidden feature
3. the nodes of hidden features get selected

I saw it here: http://preview.ideditor.com/master/#background=Berlin-2019&disable_features=boundaries&map=20.59/52.47480/13.45476

Screenshot:
<img width="1392" alt="Bildschirmfoto 2019-07-28 um 13 58 44" src="https://user-images.githubusercontent.com/111561/62006439-d751db00-b140-11e9-9ca5-cd9e2f83278f.png">

Personally, I dont think its an important issue. But wanted to report it anyway.

**Comment by hackily** [comment]
Might be fixed - I could not reproduce.

I disabled all the features, shift clicked, and selected nothing.

![image](https://user-images.githubusercontent.com/8202335/67659028-9b353e80-f918-11e9-85b7-d22525b2547b.png)

**Comment by tordans** [comment]
@hackily agreed. Could not reproduce it either => closing :).

**Comment by quincylvania** [comment]
I also haven't seen the bug in practice—I'm glad it worked itself out somehow!

@hackily Thanks for looking into this!
