### ISSUE TITLE
public_transport=station field / validator

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#6694]
A new user added some train stations through iD, the Train Station preset automatically adds railway=station + public_transport=station.

In this case they were adding freight train stations which are not part of any public transport network, but there is no field for "is this station a public transport station or not", so it's only exposed down in "All tags".

Further more, once you delete the public_transport tag, the validator has a warning that the tags are outdated and you should update them.

This is all a bit overwhelming for a new user, but the current presets and validator are pushing them into incorrectly tagging the train station.

**Comment by quincylvania** [comment]
Interesting. iD assumes that all `railway=station` are public transit stations but I guess that's not the case. Though many of them are, so leaving off `public_transport=station` alone doesn't really solve the problem of differentiating one from the other. Is there a tag we can use to distinguish a "Freight Train Station" preset? Maybe [`cargo`](https://wiki.openstreetmap.org/wiki/Key%3Acargo)?

**Comment by manfredbrandl** [comment]
From the wiki: "While railway=station is about all railway stations (i.e. including cargo), the public_transport=station tag is used only on the stations interesting for passenger transport." To become consistent we could use "freight_transport=station".

**Comment by quincylvania** [comment]
From my perspective the tag can be anything as long as people won't push back on iD for being the first to use it.

**Comment by manfredbrandl** [comment]
@quincylvania How can i help?

**Comment by quincylvania** [comment]
@manfredbrandl Feel free to propose a tag on the wiki/mailing list. If something gets support elsewhere then iD can likely support it 👍

**Comment by jeisenbe** [comment]
@andrewharvey could you show an example of a `railway=station` which is not used for passenger transport? I suspect that the wiki might not be correct about how that tag is used.

**Comment by jeisenbe** [comment]
There are only 11 stations with `station=freight` for example. https://taginfo.openstreetmap.org/tags/station=freight

**Comment by andrewharvey** [comment]
> @andrewharvey could you show an example of a railway=station which is not used for passenger transport? I suspect that the wiki might not be correct about how that tag is used.

My initial post was sparked by https://www.openstreetmap.org/changeset/72670000 where the user added public_transport=station when adding a train station that was not part of the public transport network. I tried to explain that the shouldn't use the public transport tag and recommended removing the tag, but they instead deleted the whole station, and never added it back in again. Since the land isn't accessible to the public I can't survey to check and don't have the local knowledge or technical knowledge about train infrastructure to know if it should be considered a station or not.

I'm not too fussed, because I know this is not a common case so if this issue is closed that's okay, unless anyone else can add to it.

**Comment by quincylvania** [comment]
@andrewharvey @jeisenbe Thanks for the discussion. This does seem like a fairly uncommon case so I'm going to close this as low impact. If someone comes up with a good freight train station tag at some point then I'd be happy to add it to iD 👍

**Comment by quincylvania** [comment]
Looks like [`railway=yard`](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dyard) is defined for freight stations. See #7119.

**Comment by tohaklim** [comment]
Sorry to bring this back, but it came up during a regional discussion. 
There appears to be some confusion between the approved usage of station tags as [documented on the wiki](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dstation) (both passenger and freight, the latter being distinguished by absence of public transport tags).
Yard still has <3k uses, doesn't seem to have gone through a proposal process, and the page says:

> This tag has also been used for mapping freight-only stations, which are railway stations without passenger traffic where freight trains are loaded or unloaded, and which are often found in a rail yard.

So it doesn't seem to be the main/intended use of the tag. 
Hence I'm not sure if this validation rule remains correct/best practice

**Comment by thompehw** [comment]
It's not just freight - in my area there are lots of childrens' railways in parks, zoos, etc, with nodes tagged with railway=station, and then people are helpfully adding public_transport=station because they believe they are fixing a tagging issue.
