### ISSUE TITLE
How to reset comment auto fill

### ISSUE THREAD

**Issue by phiphou** [openstreetmap/iD#6699]
How to delete old autocomplete comment field ? When I hit "p", I got "p" and "passage piétons paris" choice, want to remove the "p" choice.

**Comment by BjornRasmussen** [comment]
You can't, since iD uses the last 100 changesets you created.  The solution is then to create 100 more changesets and the suggestion will disappear.

**Comment by phiphou** [comment]
Thank you for your clear answer ;)

**Comment by quincylvania** [comment]
Yep, @BjornRasmussen is right. There's no way to manually edit the list.
