### ISSUE TITLE
Encourage adding tree type

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6706]
When adding a tree to the map, the user sees leaf type, etc. But no field to say if it is a maple, etc. at least. If not full blown species and genus tags.

**Comment by quincylvania** [comment]
We recently added a `species:wikidata` field to trees that you can use for this.

**Comment by jidanni** [comment]
Well it's not working:

![X1](https://user-images.githubusercontent.com/1230959/62315276-99014680-b4c7-11e9-9e6a-1f08b62b5b7e.jpg)

**Comment by quincylvania** [comment]
I just added yesterday so it's not released yet. It will be under the `Add field:` list.

**Comment by jidanni** [comment]
Wait... under the Add field: list?!
Sorry. Not good enough.
Because it is still prompting the user:
```
Leaf Type
Leaf Cycle
Denotation
Diameter
```
￼up front. Think of it this way:

> "Say, little Jimmy. What tree is that?"
> ￼
> "Maple!"
> 
> (Other kid raises their hand.) "Oak!"

No kids would ever think of the other items currently there.

So tree type must be first, up front.

Sure, Latin names are fine, but tree type must be right there at top of the exposed questions/items.

**Comment by quincylvania** [comment]
It sounds simple to have a field where mappers can enter "Oak" or "Maple" but it's not. One has to consider common names in different languages/regions, common names vs. scientific names, and genus vs. species. See #4240 for why a species field wasn't added before.

The `wikidata:species` field is a compromise that lets mappers unambiguously link to a defined taxon. It's hidden by default because it's an advanced field and not critical for general-purpose mapping. We might do something like #5734 where you can customize what default fields are shown.

**Comment by jidanni** [comment]
OK. (How would Google do it... they would have a menu where the user would pick "Pin oak" and the interface would say '"Pin oak - Quercus palustris" Confirm?' and then  '"Pin oak" , "Quercus palustris"   would be recorded somewhere.)

**Comment by quincylvania** [comment]
> they would have a menu where the user would pick "Pin oak" and the interface would say '"Pin oak - Quercus palustris" Confirm?' and then '"Pin oak" , "Quercus palustris" would be recorded somewhere.

This could be nice, but it would require us to translate thousands of species into iD's dozens of languages or integrate a species database. Either way it'd be a mountain of work to benefit a few mappers. Open source software is about compromise and prioritization. We have much more important features to work on right now.

**Comment by jidanni** [comment]
> I just added yesterday so it's not released yet. It will be under the `Add field:` list.

Nope, still not there:
![6579-1](https://user-images.githubusercontent.com/1230959/94264204-da28a580-ff68-11ea-9121-e054c6d8ce29.jpg)

OK, I see, we need to type a "W" to find it.
![27218-2](https://user-images.githubusercontent.com/1230959/94264318-14924280-ff69-11ea-9bfb-5aedbabcd5a1.jpg)

Well all I can say is that this aspect of a tree, that we can tell from very far away (pine vs. oak), is rather buried when it comes time to enter the data.

**Comment by jidanni** [comment]
Actually it would be nice if right at the top, before
Leaf Type
￼￼Leaf Cycle etc.
there was
Species,
and that would link to Wikidata matches.

**Comment by jidanni** [comment]
> The `wikidata:species` field is a compromise that lets mappers unambiguously link to a defined taxon. It's hidden by default because it's an advanced field and not critical for general-purpose mapping. 

Hmm, https://wiki.openstreetmap.org/wiki/Key:species:wikidata says "It should be used for plants that do not have their own Wikidata item and are not relevant enough to justify their own Wikidata item."  Uh oh... sounds rather wrong.

**Comment by jidanni** [comment]
OK: This works!:
E.g., I know a tree is https://en.wikipedia.org/wiki/Myrica_rubra
OK, I found https://www.wikidata.org/wiki/Q311617
I enter that into the wikidata:species field and voila it all completes to even the local name!
 
OK, this means `wikidata:species` is currently working well enough to put it permanently on top even in front of

Leaf Type
￼￼Leaf Cycle
etc.
