### ISSUE TITLE
List local multilingual name languages first

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6712]
Usually places are likely to have only one or two multilingual name language possibilities.
Therefore perhaps put e.g.,

```
French
English
--------
Abbziphian
Amaranthailian
Aproprolalian
...
```
 based on where we are first. Lest the user be forced to dig way down each time.

![X6](https://user-images.githubusercontent.com/1230959/62331270-0aec8680-b4ee-11e9-9938-13ec169ff3d1.jpg)

(In fact maybe always list English at the end of the priority list, when not in English speaking countries anyway.)

**Comment by DujaOSM** [comment]
+1. The standard in Serbia is to fill Serbian Cyrillic, Serbian Latin and English names, and populating those via the standard UI is so time-consuming that I keep a raw-text-tag list template on side, ready for copying. English appears in the list only after you type "en", and there are "helpful" Ænglisc and eʋegbe to choose from. This could really use some improvement, being a very frequently used feature. Perhaps pull the list of languages somewhere from user preferences (like Wikidata does for descriptions, except that I can't figure out where it's configured)?

I didn't check in v3 preview, can selection of name tags be part of user-defined presets, or is that something orthogonal_

**Comment by 1ec5** [comment]
> like Wikidata does for descriptions, except that I can't figure out where it's configured

MediaWiki’s [ULS](https://www.mediawiki.org/wiki/Universal_Language_Selector) extension is what enables Wikidata to display descriptions in the relevant languages and enables Wikipedia to list interwiki links in the relevant languages. (There are also user preferences to override the default.)

ULS ultimately gets its language data from [CLDR](http://cldr.unicode.org/). #6702 introduced a subset of CLDR for the translated language names. A similar mechanism could pull in the [language-territory table](https://www.unicode.org/cldr/charts/latest/supplemental/language_territory_information.html). If there are any gaps in coverage, we could supplement the table with a cached index of [`default_language`](https://wiki.openstreetmap.org/wiki/Key:default_language) tags on administrative boundaries, using either Overpass or Sophox.

**Comment by jidanni** [comment]
Or simply remember the last few recent languages the user has picked,
and put them up front in the choices...

**Comment by quincylvania** [comment]
@1ec5 Thanks for the tip on CLDR! I found the [matching info](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/territoryInfo.json) in the `cldr-core` module that iD now uses. It'd be easy to read this.

> Or simply remember the last few recent languages the user has picked,
and put them up front in the choices...

@jidanni Sure this could supplement. We could also prioritize languages tagged on nearby features, similar to how iD recommends address field values.

**Comment by DujaOSM** [comment]
While I'm at it, by a local convention Serbian Latin names have been tagged with `sr-Latn`  rather than `sr_Latn` as it's spelled in CLDR. There's currently [74000 objects](https://taginfo.openstreetmap.org/keys/name%3Asr-Latn) marked with one, and there's even a JOSM extension which supports its population. It might easily be the _only_ `lang-sublang` identifier in widespread use (although I might easily be wrong), so please consider accommodating it.

**Comment by quincylvania** [comment]
> While I'm at it, by a local convention Serbian Latin names have been tagged with sr-Latn rather than sr_Latn as it's spelled in CLDR. 

Our integration with CLDR accounts for this 👍

**Comment by quincylvania** [comment]
I did this using the CLDR list. I also made it so iD's locale language (presumably the user's language) is first in the list.

Editing in the US (`en-US` locale):

<img width="332" alt="Screen Shot 2019-08-08 at 4 22 21 PM" src="https://user-images.githubusercontent.com/2046746/62739006-61c7f380-b9f9-11e9-8a61-f60743705c3a.png">

Editing in India (`en-US` locale):

<img width="312" alt="Screen Shot 2019-08-08 at 4 23 02 PM" src="https://user-images.githubusercontent.com/2046746/62739015-655b7a80-b9f9-11e9-8a7e-d5bee3a6d410.png">

Supplementing with nearby name tag languages or recently used languages can be further work.

**Comment by DujaOSM** [comment]
Thanks for the quick implementation, @quincylvania. It worked great for sr-Latn; alas, for Serbian (Cyrillic) iD v3 generated `name:sr-Cyrl` rather than bare `name:sr` [here](https://www.openstreetmap.org/way/405570169/history). I understand that the current convention is somewhat asymmetric, but it is what it is and we have to accommodate it.

**Comment by quincylvania** [comment]
> It worked great for sr-Latn; alas, for Serbian (Cyrillic) iD v3 generated name:sr-Cyrl rather than bare name:sr

@DujaOSM Thanks for the heads up. I made it account for this.
