### ISSUE TITLE
Add trailing slash on website example

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6714]
Please make this, 
![X8](https://user-images.githubusercontent.com/1230959/62333165-f495f900-b4f4-11e9-8ee0-b70802f05b2e.jpg)
say
```
https://example.com/
```

In fact browsers won't even let you copy such links without that slash after the domain. They always add the slash for you.

Here, do right click and copy link address on https://example.com .
See, you copied a trailing slash too.

(And as I suppose the user is probably pasting the URL in and not typing by hand, I guess there is no need to fill in the "https://" like in #6713, as that would probably just create more cleaning (up the field so one can paste the URL) work.)

**Comment by quincylvania** [comment]
@jidanni The presence of the trailing slash makes no material difference. Leaving it off is a stylistic choice.

**Comment by jidanni** [comment]
Yes, and it is the style that all the big players now use in such cases.

**Comment by quincylvania** [comment]
> Yes, and it is the style that all the big players now use in such cases.

I don't really know who you mean. In any case we're not going to use something just because another app does, especially something so minor. We have much bigger priorities to address in iD at the moment.
