### ISSUE TITLE
Add ability to continue areas

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6715]
It would be great if there was a way to reattach to an area and continue mapping it, like can currently be done with lines.

**Comment by quincylvania** [comment]
This is #2272

**Comment by Adamant36** [comment]
My bad. I did a search for similar issues, but it didn't come up for some reason.

**Comment by quincylvania** [comment]
No problem, I find the GitHub search isn't always the best, especially considering how many issues there are for iD.
