### ISSUE TITLE
Convert access=public to access=yes

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6716]
See

- dropping this tag in iD https://github.com/openstreetmap/iD/issues/2280
- dropping this tag in JOSM https://josm.openstreetmap.de/ticket/10007
- JOSM deprecation ticket https://josm.openstreetmap.de/ticket/18007
- deprecation sanity check on mailing lists https://lists.openstreetmap.org/pipermail/tagging/2019-July/046871.html
- https://wiki.openstreetmap.org/wiki/Tag:access%3Dpublic describing it as deprecated
- https://taginfo.openstreetmap.org/keys/access#values
- https://taghistory.raifer.tech/

![Selection_001](https://user-images.githubusercontent.com/899988/62408089-165db180-b5c3-11e9-8f5d-10d635f16ad9.png)

**Comment by quincylvania** [comment]
@matkoniecz Sounds fine. Thanks for going through the diligence of discussing this kind of deprecation in other channels.
