### ISSUE TITLE
Add letterbox preset

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6718]
[Sometimes](https://www.openstreetmap.org/node/4015808389) an inexperienced mapper will map the letterbox (private mailbox) in front of a house as `amenity=post_box` (postbox or mail collection box). A dedicated [`amenity=letter_box`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dletter_box) preset would make this tagging mistake less common.

Terms include “letter box”, “letterbox”, “letter plate”, “letter hole”, “mail slot”, “mailbox”, and “private mailbox”. Note that the `addr:*` scheme is replaced by a `post:*` scheme.

**Comment by bhousel** [comment]
Having a good icon for this will help mappers tell the difference 📬

**Comment by quincylvania** [comment]
I added this, including a field for the `post:*` scheme. I preemptively used the `temaki-letter_box` icon ID, meaning the icon is blank now but will appear once we merge the svg I drew for temaki and do a release.
