### ISSUE TITLE
Editor suggests landuse on power plant under ground

### ISSUE THREAD

**Issue by Gazer75** [openstreetmap/iD#6727]
When I map a hydro plant I do it at the generator hall inside the mountain. This is quite common in Norway.
The editor then suggests users to add landuse=industrial even if the polygon is tagged with location=underground.

**Comment by bhousel** [comment]
iD is following the guidance on the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:power%3Dplant) to add `landuse=industrial` for power plants.

**Comment by Gazer75** [comment]
Problem is that the wiki assumes power plant is over ground. That is not always the case.
Pretty much all of the large hydro plants in Norway built after WW2 are inside mountains.
![Hydro plant under ground in Norway](https://user-images.githubusercontent.com/13599949/62594490-1fa89000-b8db-11e9-9252-6fa5059efcf9.jpg)

**Comment by quincylvania** [comment]
We could possibly have an "Underground Power Plant" preset that adds `location=underground` instead of `landuse=industrial`.

**Comment by bhousel** [comment]
I agree that the guidance on the wiki is pretty questionable in this case.  I've taken the position for years that it's a bad idea to recommend adding `landuse` tags to things that can reasonably be mapped as points.  But anyway, OSM gets what OSM wants.
