### ISSUE TITLE
specific tool for parking_space (create a table ?)

### ISSUE THREAD

**Issue by JLZIMMERMANN** [openstreetmap/iD#6728]
I discovered that the main osm.org rendering displays the tag amenity=parking_space
What is interesting is that we are able to draw each space to give more explicit mapping like here 
![image](https://user-images.githubusercontent.com/4929752/62633389-552d9780-b934-11e9-9701-6d81e613a442.png) 
But doing this kind of geometry would be much more easy if here was a way to create a table with rows and culumns.
Here there is a link on another area https://www.openstreetmap.org/#map=19/48.91456/2.30538

**Comment by quincylvania** [comment]
I can imagine a tool like this but I'm not sure how widely useful it'd be. Perhaps it's something someone can build once we do #6717.

**Comment by quincylvania** [comment]
So I think this is outside the scope of iD right now. I'd suggest finding or writing a JOSM plugin for it.
