### ISSUE TITLE
Display the list of values on hover over "Multiple Values" in multi-select text editing.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6730]
When I selected two motorway links, It wasn't possible to see what the values were for those two highways without selecting just one of them at a time.  

![Image of iD](https://user-images.githubusercontent.com/37753777/62644299-c9a60d80-b917-11e9-83d1-b6fc1938c13b.png "Several objects selected, with the mouse hovering over a value with the text Multiple Values in it")

When I select the two and hover over the value, the hint `Multiple Values` is displayed.  Would it be possible to instead change this to show something like `1 "asphalt"; 1 "concrete"`?  
Other selections would show something else like `23 "asphalt"; 12 undefined; 2 "paved"`, `4 undefined; 3 "asphalt"; 1 "ashpat"`, or `192 "asphalt"; 33 "dirt"; 25 undefined`.

This clearly wouldn't fit inside of the value space, but showing it on mouse hover could be very useful for data cleanup and completeness mapping.

**Comment by quincylvania** [comment]
@BjornRasmussen You can focus the field to open the suggestions list, which are the populated from the combined values of the selected features. I suppose the tooltip could be more useful though.
