### ISSUE TITLE
Download all parent relations when a child is selected in low zoom editing.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6731]
When editing at super high zooms, I found myself selecting objects that had been downloaded but weren't in the downloaded area in order to look at the parent relations (huge multipolygons) of those objects.  Unfortunately, since they weren't downloaded already, the relations section of those objects said "Relations (0)". 

I think that when an object is selected in low zoom editing, all parent relations should be downloaded so that they can be shown in the "Relations" section of that object.  Obviously, the members of those relations should _not_ be downloaded, since doing so would destroy performance on most machines.

**Comment by BjornRasmussen** [comment]
Also, note that the current code doesn't update the relations section when new relations are downloaded.  This should be fixed, such that the finishing of downloading an area (or tile?) triggers the redraw of the relations section of the selected object.

**Comment by quincylvania** [comment]
I'm going to consider this a bug since a feature's relations should always be available when it's selected. Note that I moved the low-zoom inspection behavior to 2.17.0 but not the functionality where the `id` URL parameter will override the `map` parameter, which could cause this bug most easily.

**Comment by slhh** [comment]
I would expect the following sequence to potentially cause the issue:

1. The user selects a large relation
2. Missing members are automatically downloaded, but without their parent relations.
3. In extra low zoom, the user selects one of these members (on the map or in all members). 

iD does likely need to do some bookkeeping whether the parent relations of an element have been downloaded (element has been returnend from a map API call or parent relations have been explicitly requested), and download missing parent relations of the selected element when entering mode select.

**Comment by quincylvania** [comment]
Looks like there's an [endpoint](https://wiki.openstreetmap.org/wiki/API_v0.6#Relations_for_element:_GET_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id.2Frelations) for this that iD isn't using yet.
