### ISSUE TITLE
Offer way to enter exact dimensions when creating new circles and lines segments

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6735]
Problem: user wishes to create an storage tank with an exact known diameter

He can fill in all the other fields precisely,
- building=yes
- capacity=3
- colour=black
- content=water
- man_made=storage_tank
- material=plastic
- height=2.1

but when it comes to diameter, well, all he can do is grasp his mouse
and hope for the best.

Solution: When creating circular or square objects, have a field
somewhere asking for diameter, radius, length etc. Perhaps somewhere via
the right click... In fact even for simple line segments, have something
in the right click menu where one can adjust length. Perhaps restricted
to newly created objects only, perhaps not.

One might say "Use JOSM. Case closed." But if you think about it just a
little extra entry field would save tons of work.

Start with basic items:
- Diameter of circles we are creating
- Length of straight (two nodes only) line segments we are creating

How? Maybe add a `Diameter: ______` field within the white box here,
under the words "Make this area circular."
![21763-1](https://user-images.githubusercontent.com/1230959/62751340-ee27f400-ba95-11e9-9baf-2b3a48393776.jpg)
Maybe such input fields are impossible. OK, then there should be some other way...

**Comment by BjornRasmussen** [comment]
Why not just have that user enter the value with the existing diameter tag?  The radius of shape the isn't all that exact anyway, so the tag is more useful for the data consumers were thinking about.  

The "circular" operation doesn't actually make the object a perfect circle, but rather a many sided polygon, so getting a radius for that isn't really useful to data consumers.  There are ways, but since the shape is not an exact circle, having an _exact_ radius is useless.

**Comment by jidanni** [comment]
https://wiki.openstreetmap.org/wiki/Key:diameter is used for pipelines etc. And in the case of point objects like trees.

**Comment by quincylvania** [comment]
@jidanni Sorry, I don't see this as a fit for iD. The point of tracing stuff on the map is that it's intuitive and users don't have to worry about inputting parameters. The usefulness seems extremely limited. The only advantage I can think of would be exactness, but as @BjornRasmussen pointed out, there's no circle or ellipse type in OSM so all "circular" features are approximate polygons anyway.

**Comment by jidanni** [comment]
OK, but here we are entering a 350m feature,
![31182-4](https://user-images.githubusercontent.com/1230959/62827347-06b41d80-bc00-11e9-8c22-146a9b624c86.jpg)
not so bad.
But what if we wanted to enter a 325m feature?
It all relies on estimates to that scale bar.
The scale bar doesn't have intermediate tick marks either.
Another idea could be the length of each segment would have a dynamic counter incrementing in the corner as we pull on the segment.

**Comment by quincylvania** [comment]
> OK, but here we are entering a 350m feature,
> not so bad.
> But what if we wanted to enter a 325m feature?

You can press <kbd>Cmd</kbd> +  <kbd>Shift</kbd> +  <kbd>M</kbd> (on Mac) to open the Measurement panel. This will give you the length of selected lines.

<img width="833" alt="Screen Shot 2019-08-11 at 9 53 32 AM" src="https://user-images.githubusercontent.com/2046746/62835419-f0b55580-bc1d-11e9-82b4-4f7e702657eb.png">

**Comment by jidanni** [comment]
Ah, the very last item in the Help menus.
Good. This helps a lot. Also helps with #6602, #6173, #4197.
(And with areas reported, helps confirming diameters are at least close before saving.)

**Comment by quincylvania** [comment]
@jidanni I'm glad you find this helpful!
