### ISSUE TITLE
Using the validation fix "Continue drawing from start" corrupts iD V3

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6737]
To reproduce:
1: Create a oneway road that ends on another road, but doesn't connect to anything at the start.
2: Select the feature, and then select the validation fix "Continue drawing from start"
3: iD is now corrupted, and these issues are printed to the console:
![image](https://user-images.githubusercontent.com/37753777/62807885-994fa200-bac4-11e9-9fd8-7ae1e8243597.png)

**Comment by BjornRasmussen** [comment]
Doing the same thing for the "has no outlet" issue produces this: 
![image](https://user-images.githubusercontent.com/37753777/62808244-8d181480-bac5-11e9-949b-d24ae3dfcf0c.png)

**Comment by quincylvania** [comment]
@BjornRasmussen Thanks for reporting. This is now fixed.
