### ISSUE TITLE
Add field for stroller tag

### ISSUE THREAD

**Issue by carstenhag** [openstreetmap/iD#6739]
It's similar to the wheelchair field, see https://wiki.openstreetmap.org/wiki/Key:stroller.

https://github.com/babykarte/babykarte.github.io uses it. (Yes, it's not on taginfo yet. See https://github.com/babykarte/babykarte.github.io/issues/110)

Additionally, `stroller:description=*` is used too. Not sure if that can be added, as I haven't seen it for the wheelchair tag.

**Comment by quincylvania** [comment]
@carstenhag Thanks for the suggestion. I added the field to the relevant highway presets. Let us know if there are other presets that you think should have this tag.

> Additionally, stroller:description=* is used too. Not sure if that can be added, as I haven't seen it for the wheelchair tag.

Yeah, we don't have a great way to support this kind of tag right now.

**Comment by carstenhag** [comment]
Sorry that I had not looked at it before the release, but `stroller` is the same as the wheelchair tag, there are "yes", "limited" and "no" values. Right now there's just a checkmark for yes or no.

Should I create a new issue for that?

**Comment by quincylvania** [comment]
@carstenhag Up to you. Checkmark fields are easiest to reason about since they involve the fewest decisions, but the added detail might be worth the complication.

**Comment by simonpoole** [comment]
@carstenhag FYI stroller is AE not BE, imho the key should not be promoted as a very confusing departure from BE:

**Comment by carstenhag** [comment]
@simonpoole what do you mean with AE/BE?

**Comment by simonpoole** [comment]
AE == American English

BE == British English aka the language we draw upon for OSM tags

**Comment by carstenhag** [comment]
Oh, I guess just nobody noticed until now. I'll make some people aware of this

**Comment by carstenhag** [comment]
Sow hat word would you recommend?

On the German osm telegram channel we talked about this. Perhaps buggy, pushchair or  baby_carriage?

Imo pushchair sounds best, but we could vote on that. Not sure.

**Comment by simonpoole** [comment]
This the wrong place (just as telegram imho) to discuss this. But the wiki picture is clearly for pram and not a buggy and personally given the nature of prams vs buggies imho access for the former is more important to record.
