### ISSUE TITLE
Issues with the Issues panel: link "Issues with other features:"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6741]
Here "Issues with other features: 14" should be hyperlinked to some place where the user can see those 14 features.
![15244-0](https://user-images.githubusercontent.com/1230959/62835568-b8009500-bc8c-11e9-9457-9448f4411038.jpg)
Or else he perhaps will think "they are probably referring to those 14 items below."
Anyway he perhaps thinks "the school principal says I have 14 demerits, but won't let me know what they are." (Even if not related to him.)

**Comment by DujaOSM** [comment]
Nah, I think the target audience for iD are persons with IQ over 90 or so. We wouldn't like others to edit the map anyway; or at least, not to try fixing the map issues created by others.

**Comment by tastrax** [comment]
I suspect it is because you only have "my edits" ticked - change that to "everything" and all will become clear

**Comment by Adamant36** [comment]
> not to try fixing the map issues created by others

Really? People do it all the time. Otherwise, nothing would ever get fixed.

**Comment by bhousel** [comment]
Closing here.  I think people can figure out that by playing with the radio buttons, they'll see different things here.

@DujaOSM Please be nice.  iD is for everyone.

**Comment by DujaOSM** [comment]
@bhousel  Acknowledged, with an apology.

**Comment by jidanni** [comment]
I see.
One would have never expected it to check things even that

**Comment by quincylvania** [comment]
> And in fact "Everything" could be changed to "All edits" or "Everybody's edits".
>
> And "Everywhere" should be changed to "Nearby" or "Within 14km" else it
means "for the whole world."

"Everything" and "Everywhere" are purposefully encompassing so users can be sure that no loaded features are being left out. It's self-evident that iD isn't checking the entire planet.

**Comment by jidanni** [comment]
OK but it would still be good to know how far it is checking.

**Comment by quincylvania** [comment]
> OK but it would still be good to know how far it is checking.

There's no set distance. "Everywhere" checks the tiles that were downloaded since starting iD, so whatever places you've viewed. If you edit in Japan and then start editing in the US, the issues you encountered in Japan will still display.

**Comment by jidanni** [comment]
OK. I would have never ever guessed that.
One usually assumes some radius rectangle.
So perhaps a "?" or "i" information button could explain that.
Else 100% of users would never guess that.

**Comment by quincylvania** [comment]
> So perhaps a "?" or "i" information button could explain that.
> Else 100% of users would never guess that.

Advanced mappers could deduce this or ask us. Casual mappers (to the extent they even know about this feature) should never have to care—it's intuitive that unseen data is ignored.
