### ISSUE TITLE
public transport platforms with kerb=raised are updated to kerb barriers

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#6742]
Hi,
please have a look at: https://www.openstreetmap.org/way/292050994

iD wants to upgrade this to a barrier=kerb way, but I think this doesn't fit because it's a public_transport=platform, just with a raised kerb. kerb=* is another usage there where it is **_not_** intended to be an under-tag of barrier=kerb, just like kerb=* on highway=crossing nodes.

**Comment by quincylvania** [comment]
@Lukas458 Hmm this is unintentional behavior since iD was not aware that `kerb` might be used on platforms. I personally wouldn't recommend that pattern since it's not obvious what it means and could probably be replaced by mapping in higher detail, but I fixed the bug in any case.
