### ISSUE TITLE
Deleting area Help message improvement

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6743]
Help says: `To delete an area,  right-click on the area to select it and show the edit menu, then use the  Delete command.`

Add: `you may have to use the Downgrade command first before being able to Delete.`

P.S., the user also might see
![6498-3](https://user-images.githubusercontent.com/1230959/62836508-4b8a9380-bc96-11e9-82fc-b9b7f16adb18.jpg)
which by the way, should say "area" not "line" in this case.

**Comment by bhousel** [comment]
I think users can figure this out.
