### ISSUE TITLE
Measurement panel had weird internal codes showing

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6746]
The Measurement panel shows:
n-10 for nodes
w-2 for lines
w-3 for areas
which do not make any sense to the user and should not be shown.

**Comment by jidanni** [comment]
Or add a "i" information button or "?" button or mouseover to say what they are all about.

**Comment by bhousel** [comment]
These are just temporary ids.  I think people can figure out that as they draw new features, they get temporary ids until the user chooses to upload them..  Anyway, the info panels are for advanced users.
