### ISSUE TITLE
"Line has no tags" is not easily fixable for closed lines

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6750]
To reproduce: draw closed line without tags to represent a building (relatively common mistake).

"Line has no tags" error appears.

"Select feature type" and typing "building" into search box is not going to succeed as iD decided that it is line, not area.

Workaround is to manually enter tag value, but AFAIK iD mappers are supposed to be by design able to make common edits without using raw tag values (or maybe it considered as an uncommon edit and it is fine to require ability to use freeform tag values?).

**Comment by DujaOSM** [comment]
I slightly lean on the side of "considered as an uncommon edit...". If anything is to be done, it can be one of:
- Provide a "Convert to Area" option in the UI (but where to put it?)
- Make iD smart enough to deduce that the line is closed, and in that case offer areal presets for it along with line presets.

**Comment by quincylvania** [comment]
This is #1828. Also, the v3 ribbon reduces the risk of mappers drawing lines when they meant to draw areas.
