### ISSUE TITLE
Creating a new relation is tedious

### ISSUE THREAD

**Issue by DujaOSM** [openstreetmap/iD#6751]
Creating a new relation is non-intuitive and quite tedious in v2, and in v3 it is even slightly worse. Very often, users need to create very small relations (2-3 members), and they have to go through the following hoops (v3):

- **Click** [+] to even access relation options
- **Click** to open the dropdown, then **Click** to select "New relation..."
- A nebulous "Relation" is created in the sidebar (v3). Visually find "Type" (non-intuitive), **Click** to open the dropdown, **Click** to select "Multipolygon".
- A nebulous "Multipolygon" is created in the sidebar, along with a warning that it's, um, nebulous. **Click** on the header (non-intuitive) to assign a type to it, then find an appropriate preset (Farmyard, for example) and **Click** it
- If the relation requires that your object has a role, **Click** once more "Set as outer" and... you're done.
(In v2, steps 3-4 are more streamlined and require slightly fewer clicks).

Ideally, the process should start up with a straightforward choice of adding to a new or creating a new relation of readily accessible type (why would one ever create a bare "Relation" or "Multipolygon"?). If you want to keep the initial [+] (not necessary), then make it a two-fold choice immediately: add to existing or create a new relation:
![New Relation](https://user-images.githubusercontent.com/48584318/62929509-ebd9d880-bdba-11e9-9bc4-237da811f48f.png)

**Comment by quincylvania** [comment]
@DujaOSM I'd like to improve this via #6551. This would let you select the relation type as you add it.

**Comment by ArloJamesBarnes** [comment]
In 2.x, making a secondary-click menu entry 'add to relation: existing1, existing2, new' would help with the first bit.
