### ISSUE TITLE
Make all toolbar items accessible on small displays

### ISSUE THREAD

**Issue by ralfhauser** [openstreetmap/iD#6755]
For example, I try to edit Node: 5757320970 , but in the end, I cannot save it
(https://www.openstreetmap.org/edit?node=5757320970#map=19/47.36958/8.55640)

![image](https://user-images.githubusercontent.com/1681677/62970096-faea7600-be0e-11e9-8d07-2428432a745c.png)

because the button if "off" the visible area

**Comment by ralfhauser** [comment]
I get there e.g. from https://h2o.do/ch-zh?l=de&i=Q55170218 
klicking on the bottom-right button
![image](https://user-images.githubusercontent.com/1681677/62970304-76e4be00-be0f-11e9-90a1-57149abfa138.png)
of
![image](https://user-images.githubusercontent.com/1681677/62970218-443ac580-be0f-11e9-8fee-8e5fbc5a685e.png)

**Comment by quincylvania** [comment]
I made the toolbar horizontally scrollable so you can access controls like Save that might be offscreen on small displays. This will be in iD v3 which is still many months away.

![scrollable toolbar demo](https://user-images.githubusercontent.com/2046746/64038410-9ec96680-cb1d-11e9-8bea-4cf5fe74e32f.gif)
