### ISSUE TITLE
Transifex Error Checking

### ISSUE THREAD

**Issue by yarons** [openstreetmap/iD#6759]
https://github.com/openstreetmap/iD/blob/7497bdce25a343600c21437062e55711ace14620/build_data.js#L449

Transifex interprets the terms generated by this function as JSON and when I try to translate them I'm getting an error saying that the number or objects is different.

There are 2 possible solutions:
1. Switch back to <>.
2. Remove the check/convert it to warning (my preferred solution).

Thanks!

**Comment by bhousel** [comment]
Thanks for flagging - can you check this again on Transifex? I _think_ I removed the warning a few days ago.

**Comment by yarons** [comment]
Done, it's working, thanks!
