### ISSUE TITLE
Remove geometry selection from preset browser

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6760]
In OSM, many feature types can be mapped using more than one geometry, but typically a single geometry is sufficient or most common. The iD 3 preset browser currently prompts the mapper to select a geometry type if there are multiple options.

<img width="327" alt="Screen Shot 2019-08-15 at 12 30 05 PM" src="https://user-images.githubusercontent.com/2046746/63113990-545ebc00-bf59-11e9-8318-8e449c7aeced.png">

This decision is burden for new mappers and we should remove it.

A simpler solution is to simply enter the "add mode" for the best geometry immediately after the user picks a feature type. Advanced mappers could then switch the geometry if needed. iD would remember the preferred geometry for each preset.

<img width="382" alt="Screen Shot 2019-08-15 at 12 36 05 PM" src="https://user-images.githubusercontent.com/2046746/63113999-59bc0680-bf59-11e9-9f4a-1a369f40f6dc.png">

**Comment by quincylvania** [comment]
Here's a demo.

Remaining work:
- Pick a keyboard shortcut to toggle the geometry type
- Review presets and determine the preferred geometry type for each. iD interprets the array's item order as the preference order

![one geom demo](https://user-images.githubusercontent.com/2046746/63114978-d223c700-bf5b-11e9-8299-f961d13c6027.gif)

**Comment by SilentSpike** [comment]
@quincylvania For the keyboard shortcut, what about using `1/2/3` while in the "add mode"? Currently the numbers continue to change between presets, but since they aren't shown on screen in that mode I think it could be fine to override that (if someone did want to change preset they can hit escape first).

**Comment by quincylvania** [comment]
@SilentSpike Maybe. I like how you can still switch between quick presets after selecting one in case you accidentally select the wrong one.
