### ISSUE TITLE
'Game' stores marked as suspicious name due to generic store name

### ISSUE THREAD

**Issue by doublah** [openstreetmap/iD#6761]
![image](https://user-images.githubusercontent.com/11699874/63116857-26de3680-bf8a-11e9-8f34-f45db9a59495.png)

iD suggests to remove the name, but then the object has the issue of having non-standard tags, so it suggests to re-add the name and continues in a loop.

**Comment by quincylvania** [comment]
@doublah Thanks for reporting. I just merged #6754 by @SilentSpike which fixes this.
