### ISSUE TITLE
Remove start up message when not needed

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6769]
![image](https://user-images.githubusercontent.com/37753777/63191548-cd801100-c036-11e9-9653-f6679cbf447e.png)

I'm not sure exactly how this is useful for regular mappers.  Other situations, such as when there are saved changes or the user is new are currently handled quite well, in a similar way.  For returning mappers, however, this is just another thing to click away before starting with mapping.

I think that this step in the assistant should be skipped entirely and replaced with what the assistant looks like after clicking the `Start Mapping` button, since it doesn't really serve any purpose.

**Comment by quincylvania** [comment]
@BjornRasmussen The returning welcome screen hasn't really been filled out yet, but I'd like to try making it more interesting before discarding it. As I mentioned in https://github.com/openstreetmap/id/issues/6486#issuecomment-498889789, we could add various news items or mapper statistics here.

I kinda like the "Start Mapping" button but I can see how it feels like an unnecessary thing to press. Maybe we can try replacing it with an X button so mappers can close it but not feel like it's obligatory.

**Comment by SilentSpike** [comment]
I must admit this UI element often doesn't register for me.

Multiple times I've opened up the preview, zoomed in to start mapping and immediately wonder why the OSM data isn't loading in, check the menu and then realise I need to choose "restore" or "discard" on the left.

I actually do like the message that says you have X edits in Y area though and the greeting is a nice touch.

**Comment by quincylvania** [comment]
> Multiple times I've opened up the preview, zoomed in to start mapping and immediately wonder why the OSM data isn't loading in, check the menu and then realise I need to choose "restore" or "discard" on the left.

We should probably use the de-saturated map filter to indicate that editing isn't available, like we do with upload.

**Comment by quincylvania** [comment]
In 9713fbed53b1ce17bea5d6ee95cbb5b8ff2d3dda I enhanced this screen somewhat. More info is now shown when you're logged in.

![Screen Shot 2019-09-04 at 1 46 14 PM](https://user-images.githubusercontent.com/2046746/64278697-5d6cf880-cf1b-11e9-91d2-28c7f49cab95.png)

**Comment by quincylvania** [comment]
Closing this since the v3 sidebar still needs a lot of reworking.
