### ISSUE TITLE
Change wording of the "Keep Mapping" button to "Continue Mapping"

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6770]
![image](https://user-images.githubusercontent.com/37753777/63191912-be4d9300-c037-11e9-9ff2-a4f0e3d9f2a4.png)

I personally think that "Keep Mapping" sounds weird in this context, and should be replaced with "Continue Mapping" or "Resume Mapping" if there's enough space.

The word "keep" would be better in situations where the user is _currently_ in a mapping mode, and is prompted with several options, one of which is to just keep mapping.  Because the mapper is not "mapping" when they see the save screen, the word "continue" (or alternatively "resume") makes more sense.

**Comment by quincylvania** [comment]
@BjornRasmussen Nice suggestion. This is one of those things where the label sounds fine to me but there's a better way to phrase it 👍
