### ISSUE TITLE
Not easily translatable

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#6771]
This how it looks in transifex:
![DEEC1AA0-5EA9-485E-B84D-B99A7CD36343](https://user-images.githubusercontent.com/5360273/63192499-88c29d00-c06b-11e9-8abd-ed6b85ec0351.jpeg)

**Comment by quincylvania** [comment]
@manfredbrandl Yep, this is something we want to improve but need to be careful not to discard hundreds of existing translations. See #4326 and discussion in #6738.

Also, do you have any insight as to whether #6759 has been fixed? It's an issue that arose when we switched from `<>` to `[]` for field terms.
