### ISSUE TITLE
Add sorting office preset

### ISSUE THREAD

**Issue by doublah** [openstreetmap/iD#6773]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_depot
https://en.wikipedia.org/wiki/Sorting_office

Should probably have similar fields to post office. Not sure if the name 'Sorting Office' or 'Post Depot' is better.

**Comment by quincylvania** [comment]
> Not sure if the name 'Sorting Office' or 'Post Depot' is better.

I went with "Post Sorting Office" since it seems the most self-explanatory. We don't want mappers accidentally tagging regular post offices as these.
