### ISSUE TITLE
iD suggests "upgrading" tags on demolished roads

### ISSUE THREAD

**Issue by tas50** [openstreetmap/iD#6775]
If a road has the service tag and a demolished tag, but not the highway tag iD will suggest you upgrade the road with to add the service tag. I missed this one while upgrading some other tags and unleashed an angry local mapper. iD should probably just ignore tag upgrades when the demolished tag is on the node.

<img width="386" alt="Screen Shot 2019-08-19 at 10 45 11 AM" src="https://user-images.githubusercontent.com/1015200/63274994-c5aab180-c26e-11e9-8d08-96d56261cf8f.png">

<img width="391" alt="Screen Shot 2019-08-19 at 10 45 18 AM" src="https://user-images.githubusercontent.com/1015200/63275004-ca6f6580-c26e-11e9-9200-45095ac2faaf.png">

**Comment by bhousel** [comment]
I don't think iD should match the preset for `service=driveway` without `highway=service`
https://github.com/openstreetmap/iD/blob/master/data/presets/presets/highway/service/driveway.json

It looks like this was changed in 94096beb686510
(cc @quincylvania)

**Comment by quincylvania** [comment]
> I don't think iD should match the preset for service=driveway without highway=service

Yeah that's fine. I hadn't considered OSM's lifecycle tagging system at the time.

**Comment by bhousel** [comment]
Thanks for the quick fix! 🙇
