### ISSUE TITLE
Establish Special Request Desk for seldom needed operations

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6778]
I have an idea, for seldom needed operations: have a Special Request Desk, documented in the iD Help Menus.
That way software features need not be added to the editor, but users could still be able to get special tasks done, e.g.,
https://github.com/openstreetmap/iD/issues/3088#issuecomment-522949463 via staff doing it for them.
Users could get one-time tasks done without needing to learn a whole new tool (JOSM, etc.)
Maybe call it Special Edit Desk, or "Operator assisted editing" (like an Operator assisted phone call.)
Anyway, that is to distinguish it from generic "help: how do I do this?" being instead "please do this for me."

**Comment by quincylvania** [comment]
@jidanni This is an interesting idea. It might be hard to convince other people to do work for you, but there could be some people in the OSM community interested in helping with unique and challenging tasks if you ask politely.

However, this sort of system is outside the scope of iD. I suggest discussing it on through another channel:

https://lists.openstreetmap.org/listinfo
https://forum.openstreetmap.org/
