### ISSUE TITLE
power=transformer should only be used on nodes

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#6779]
Hi

Currently, iD doesn't warn about the usage of power=transformer on polygons or relations.
Mappers can easily confuse the device (the transformer) and the site (the substation) which houses the first.

As transformers are devices, they should get their own node and not be confused with buildings or surrounding fences instead of substations.
power=transformer is incompatible with building=*, ways and areas.

Is this possible to warn users when power=transformer is encountered on any other object than a node please?
See wiki : https://wiki.openstreetmap.org/wiki/Tag:power%3Dtransformer

We currently have dozen of mistakes on Osmose item 9100/class 91001 and rising
http://osmose.openstreetmap.fr/fr/errors/?item=9100&class=91001
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=9100&class=91001

All the best

**Comment by quincylvania** [comment]
@flacombe I don't know why iD allowed `power=transformer` on areas before, but it looks like JOSM doesn't so I'm comfortable switching despite the nearly 15,000 ways with this tag. It's really nice to limit features to fewer geometries.

> Is this possible to warn users when power=transformer is encountered on any other object than a node please?

iD should do this automatically once we do #6319.

**Comment by bhousel** [comment]
> @flacombe I don't know why iD allowed `power=transformer` on areas before

Looks like the wiki was changed back in 2013:  https://wiki.openstreetmap.org/w/index.php?title=Tag%3Apower%3Dtransformer&type=revision&diff=952869&oldid=932395

My best guess is iD probably just was following the old recommendation from before.

**Comment by flacombe** [comment]
What a quick fix, that's really nice guys, thank you :)

> My best guess is iD probably just was following the old recommendation from before.

Indeed, tagging has became more precise after the substation refinement proposal.
No offense with that, iD isn't responsible of increasing osmose error rate I mentioned at the start of the discussion. And it will surely help to reduce it in next weeks ;)

**Comment by flacombe** [comment]
Hi guys,

There must have been an error in this update because in iD 2.17.2, I still don't get a warning when adding power=transformer to an area
What am I doing wrong?

**Comment by bhousel** [comment]
> There must have been an error in this update because in iD 2.17.2, I still don't get a warning when adding power=transformer to an area
> What am I doing wrong?

2.17.2 is just 2.17.1 but with the Maxar layers restored.
Both our `master` and `2.x` branches are un-deployable right now. 😓

**Comment by bhousel** [comment]
Sorry, I misspoke, this was supposed to be in 2.15.  I'll have to investigate what happened.

**Comment by quincylvania** [comment]
I closed this issue because I removed the `area` geometry from the Transformer preset. There's no warning because iD doesn't yet warn about areas that are expected to be another type of geometry…

**Comment by flacombe** [comment]
The point is not only about areas

Users should also get a warning when they mix a building and a transformer (see incompatibility in wiki).
Currently I can put them both on an area (or a node) without any warning.

That cause dozen of objects being mapping as such in France because common people use to call a minor distribution substation a "transformer". They see transformer in the list and use it without idea to look at wiki. Then the only thing to encourage them to discover power=substation is a warning in the editor.
Example (I'm @InfosReseaux and @deuzeffe is a colleague of mine at OSM FR board) : https://twitter.com/R1Rail/status/1232622770883846147?s=20

**Comment by quincylvania** [comment]
Closing in favor of #8231, which is generalized.
