### ISSUE TITLE
Telecom exchanges preset

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#6780]
Hi

Currently, iD doesn't have any preset for recently reviewed telecom=* key.
It is designed to gather visible features of telecommunication networks.

Most wanted value is ''exchange'' to map sites hosting switching devices connecting customers to services. There are millions of them worldwide, mostly in dedicated buildings.
https://wiki.openstreetmap.org/wiki/Tag:telecom%3Dexchange

Is it possible to add a "Telecom exchange" preset with following keys please ?
* telecom=exchange
* telecom:medium=[copper,fibre,coaxial]
* operator=*
* ref=*
* building=*

It comes in replacement of several existing keys and a warning should raise in any situation involving them :
* man_made=MDF
* man_made=telephone_exchange
* man_made=telephone_office
* telecom=central_office
* telecom=shelter
* building=central_office

This would finally help us a lot in the cleaning effort made with telecom=exchange
All the best

**Comment by flacombe** [comment]
Dear maintainers,

Lack of presets and validation on those values encourage the use of other tags and increase noise in the db.

Do you guys have some time to handle this issue please?
Related to #7389

**Comment by quincylvania** [comment]
Thanks for your patience, @flacombe, looks like this slipped through the cracks. I added the preset 👍

**Comment by flacombe** [comment]
That looks great, thank you Quincy
