### ISSUE TITLE
iD preview became unusable 

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6788]
![image](https://user-images.githubusercontent.com/37753777/63481286-ff440e00-c462-11e9-96c6-4a2a3a579a85.png)

This happened just as I was about to add a driveway with preview.  I had searched for "driveway" in the add feature list, selected that choice, and then pressed R to start repeat mode.  Then, the map got all weird and things were messed up.  
That one message just kept repeating on the console.

**Comment by quincylvania** [comment]
@BjornRasmussen Thanks for reporting. I accidentally introduced this when implementing the solution for #5701.
