### ISSUE TITLE
iD shouldn't try to convert footway=crossing ways to areas based on "tactile_paving=no"

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6791]
To reproduce,
1) Go to http://preview.ideditor.com/master/#id=w662955806&map=21.71/35.95177/-79.07310
2) Observe the incorrect warning.

**Comment by quincylvania** [comment]
This is an interesting bug. We have a "Tactile Paving" preset for `tactile_paving=yes` that allows both `line` and `area` geometry. iD computes the implied area key whitelist based on the key alone `tactile_paving` but the line exception blacklist basted on a full tag `tactile_paving=yes`. Thus iD thinks any other value for `tactile_paving` should be an area.

@bhousel Thoughts?

**Comment by bhousel** [comment]
Oh yeah, I don't think iD can support this kind of preset. 
https://wiki.openstreetmap.org/wiki/Key:tactile_paving

If we limit tactile paving to just being a property on another feature that's fine..

But if it can be mapped as its own feature that can be a node, a line, or an area, it's just impossible to derive the context when combined with other stuff mapped with a different geometry type. 

The wiki looks pretty ok, in that it hints that the tag is to be combined with other things.  It says not to map areas with `tactile_paving=yes`.

My gut says to:
- remove the preset
- leave it as a field and put it on whatever presets it's appropriate for

**Comment by quincylvania** [comment]
@bhousel Sounds okay. We can only do so much without a native area type. Mostly this will only be used with footways, curbs, or platforms anyway.
