### ISSUE TITLE
Vertices of selected way need updated when zooming in from non-editable

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#6797]
To reproduce:
- select anything with multiple nodes
- zoom lower than 16 to magic the feature away
- zoom back in and the nodes are still displayed

For v2, fixed in v3.

**Comment by bhousel** [comment]
I dug into this a bit last night and posted on Slack, just copying here for posterity:

I see what’s going on
In `vertices.js` we cache `_currSelected`.  this gets updated sometimes - whenever `drawSelected` gets called.
From `map.js` we call this whenever something might have happened that affects the selection..
This kind of helps performance by not calling it all the time, like on every render. 
The mode `enter.map` handler in `map.js` is a time when we do it, but it skips that step when the map is not editable.. so when you zoom out, it switches to browse mode, it jumps into that code, but then doesn’t actually update the vertices.

I'm not sure if there is a way to fix this in v2.15 that can easily be merged into the v3 branch (code has diverged a bit), but I will think about it.  It's pretty low priority as it only affects which vertices are drawn after zooming out and back in again.

**Comment by rivermont** [comment]
Closing as unable to replicate in v2.20.4.
