### ISSUE TITLE
Add label to "change feature type" button in inspector

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6811]
Compared to other controls, it's not particularly obvious that the big preset button is a button nor what it will do when clicked. #1376 dealt with the same question and added a tooltip, which is nice, but seems incomplete and doesn't help on touchscreens.

<img width="371" alt="Screen Shot 2019-08-28 at 3 12 34 PM" src="https://user-images.githubusercontent.com/2046746/63889488-bdf1b800-c9a6-11e9-862c-f08e5f654ba5.png">

I think we should add a "Feature Type" label, possibly in a collapsible section like Fields, Tags, etc. We might also add a disclosure icon (⌄) to indicate that it's a dropdown button with other feature type options.

**Comment by BjornRasmussen** [comment]
What about a button labeled "(change)" under the preset?

**Comment by quincylvania** [comment]
So now that we show the preset switcher during multiselection a label here is more of a necessity. It personally took me some time to adjust but after doing some mapping I hardly noticed the change.

<img width="1042" alt="Screen Shot 2020-01-22 at 9 36 56 AM" src="https://user-images.githubusercontent.com/2046746/72903198-cf8f7f80-3cfa-11ea-90a9-07fe7a8c779b.png">
<img width="1042" alt="Screen Shot 2020-01-22 at 9 36 43 AM" src="https://user-images.githubusercontent.com/2046746/72903202-d3bb9d00-3cfa-11ea-97c1-d22b3d77558b.png">
