### ISSUE TITLE
Validator: highway elevator

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6812]
I was wondering if there is a preset available, then I learnt in https://github.com/openstreetmap/iD/issues/5351 (and https://github.com/openstreetmap/iD/issues/4068) it is only available for vertex.

Could it be interesting to warn if there is no connection between the node (highway=elevator) and the rest of the navigation network?

**Comment by quincylvania** [comment]
@sun-geo Thanks for the suggestion! Elevators are critical in accessible routing for persons with limited mobility, so hopefully this warning will improve that use case of OSM.

![Screen Shot 2019-09-13 at 3 20 50 PM](https://user-images.githubusercontent.com/2046746/64889135-a9feb500-d63a-11e9-8ad8-abf56e99c786.png)
