### ISSUE TITLE
Better gate icon

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6814]
We currently use the generic barrier icon for gates, but the "road block" style icon seems too restrictive. Gates are generally passable by some access groups. An actual gate icon would differentiate these properly from other barriers.

<img width="162" alt="Screen Shot 2019-08-29 at 8 36 02 AM" src="https://user-images.githubusercontent.com/2046746/63944964-318fd580-ca38-11e9-9754-2dc1fc0098ad.png">
<img width="165" alt="Screen Shot 2019-08-29 at 8 36 19 AM" src="https://user-images.githubusercontent.com/2046746/63944965-32286c00-ca38-11e9-948b-24874f3a277f.png">

**Comment by sun-geo** [comment]
Thats true.
Carto is using these:

https://wiki.openstreetmap.org/wiki/Key:barrier#Access_control_on_highways
https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/barrier

Maybe there is one, which suits a little bit better...

**Comment by hackily** [comment]
fas-dungeon might fit the bill.
https://fontawesome.com/icons/dungeon?style=solid

**Comment by quincylvania** [comment]
@hackily Maybe. I'm thinking something a bit more generic. The dungeon looks rather foreboding 😂
