### ISSUE TITLE
No Traditional Chinese name label in zh_TW

### ISSUE THREAD

**Issue by Supaplextw** [openstreetmap/iD#6815]
In the new iD editor, multi-name field there is only simplified Chinese language even in zh_TW setting, should be fix also in zh_HK setting which is also use traditional Chinese

**Comment by quincylvania** [comment]
@Supaplextw Hmm I'm not seeing this bug. We have all these options, and the language list doesn't depend on the locale. 

<img width="313" alt="Screen Shot 2019-08-29 at 10 36 34 AM" src="https://user-images.githubusercontent.com/2046746/63954685-17aabe80-ca49-11e9-96ef-45eba83dbc0e.png">

**Comment by Supaplextw** [comment]
![螢幕截圖 2019-08-30 00 20 08](https://user-images.githubusercontent.com/1209326/63957973-02bb4300-cabc-11e9-89d5-810ad1b29753.jpg)
You should have someone familiar with both Traditional Chinese and Simplified Chinese.  It is the UI issue, when iD is set to zh_TW, it should be in Traditional Chinese langage label, not in Simplified Chinese

**Comment by 1ec5** [comment]
When running iD in a Traditional Chinese locale (zh-Hant, zh-TW, zh-HK), all the language names are written in Simplified Chinese (zh-Hans). For example, Traditional Chinese (zh-TW) is listed as 繁体中文 but should be 繁體中文.

<img src="https://user-images.githubusercontent.com/1231218/64002876-f76a1680-cabf-11e9-9bc5-f8e39a125c64.png" width="310" alt="chinese">

CLDR has [language names in Traditional Chinese](http://www.unicode.org/cldr/charts/latest/summary/zh_Hant.html#45), but perhaps it’s relevant that CLDR’s code for Traditional Chinese is `zh_Hant`, not `zh-Hant`.

**Comment by quincylvania** [comment]
@1ec5 Thanks for the additional info, now I understand what's going on.

**Comment by Supaplextw** [comment]
@1ec5  Thanks for the further explanation.

**Comment by quincylvania** [comment]
@Supaplextw Thanks for reporting, I think I fixed this for the next release. Let us know if you see other errors!
