### ISSUE TITLE
Moving a node to a specific location (Lat/Long)

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#6819]
A problem frecuently found are nodes wrong located, that were either imported or created in the wrong place; the normal process is to drag them to the actual correct location; but this is no practical if that new position is quite far from the present position. 

Could be a way to create a process to send this actual node to another location, without deleting the actual one and creating another in the correct and current position?

Thanks

**Comment by jidanni** [comment]
See also #6602, #4197.

**Comment by quincylvania** [comment]
> See also #6602, #4197.

@jjiglesiasg Yep, we've decided this type of advanced feature isn't a fit for for iD. You might try another editor like JOSM for this.

Feel free to copy the node, delete it, and paste the copy at the correct location. The OSM entity history is nice to have, but is by no means critical.

**Comment by jidanni** [comment]
@jjiglesiasg let me know how you finally do indeed 100% achieve:
> paste the copy at the correct location

**Comment by jjiglesiasg** [comment]
Hi Quincy. How do we copy, delete, paste in another location a node, if ID only give you chance to Edit or Delete that node?

**Comment by quincylvania** [comment]
> How do we copy, delete, paste in another location a node

@jjiglesiasg Like with other software, you can use <kbd>Ctrl</kbd><kbd>C</kbd> to copy and <kbd>Ctrl</kbd><kbd>V</kbd> to paste selected features (<kbd>Cmd</kbd> on Mac).

Unfortunately we don't have these operations in the right-click menu yet, that's #2508.

**Comment by 1ec5** [comment]
If you’re really determined to preserve history while moving a point across a great distance, here’s a workaround:

1. Draw a line and connect it to the point. (In more recent builds, you have to drag the point onto the line instead.)
1. Right-click the line and choose Move.
1. Enter the coordinates into the search bar and select the result.
1. Delete the line, leaving the point.
1. Adjust the point’s location as needed using the Measurement panel.

Or just use [level0](http://level0.osmz.ru/) to edit the coordinates.

**Comment by jidanni** [comment]
> 5\. Adjust the point’s location as needed using the Measurement panel.

(i.e., move to the closest pixel available.)
