### ISSUE TITLE
Add waste key/values to waste_basket, waste_disposal

### ISSUE THREAD

**Issue by carstenhag** [openstreetmap/iD#6821]
Hey, it would be great if there was a checkmark list to check things for the waste key.

Currently, `waste` seems unrecognized by ID.

See https://taginfo.openstreetmap.org/keys/?key=waste#values.  
I'm one of the few people tagging `trash;cigarettes` combinations, but I think this is a good idea. Often, waste baskets have one container for trash and another for cigarettes.

So ideally, ID would support more than one value.

**Comment by carstenhag** [comment]
Sorry, I couldn't find it in the commit: where are the values defined (trash, cigarettes, etc)?

**Comment by quincylvania** [comment]
@carstenhag iD doesn't define values for most fields, but instead uses the top values from taginfo.

**Comment by carstenhag** [comment]
Oh I see, thanks! Is there a way to blacklist entries? Having both dog_excrement and dog for example seems wrong.

**Comment by quincylvania** [comment]
iD excludes (and offers to upgrade) values from [`deprecated.json`](https://github.com/openstreetmap/iD/blob/master/data/deprecated.json). If some values are clearly wrong we can add them there.

**Comment by carstenhag** [comment]
Okay. I'll make sure to update the wiki/post to the tagging list first to get this right and deduplicate tags. Then I'll be back here.
