### ISSUE TITLE
Suggest tagging semi-detached house for 2 adjacent houses

### ISSUE THREAD

**Issue by Chaz6** [openstreetmap/iD#6822]
When two house polygons are connected by a line, suggest changing them to Semi-detached house (building=semidetached_house). This should not match when there are more than 2 houses (e.g. in a terrace).

Also see #2776

**Comment by quincylvania** [comment]
@Chaz6 Thanks for the suggestion. Though unfortunately I'm not sure this would improve the data enough to bother iD users about, but I'm willing to have my mind changed.

While I acknowledge that `semidetached_house` is more correct than `house` for these situations, I can't think of a data consumer that would care about the difference.

Have you seen this mistake in practice or have any sense of how common it is? We also don't want to spend time building a validation rule that only affects a few dozen entities.

**Comment by quincylvania** [comment]
Lacking further discussion, I'm closing this as low impact.
