### ISSUE TITLE
Searching for "cycle" should display bicycle presets

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#6825]
Typed in "cycle" rather than bicycle or bike, but only one of the seven bicycle presets appeared. Surely matching five out of seven letters in a word should put the bicycle presets appear above all the seemingly unrelated other presets shown?
![cycle](https://user-images.githubusercontent.com/16965772/64181747-fbe75400-ce5e-11e9-93f4-265c8617b6aa.PNG)

**Comment by quincylvania** [comment]
@boothym Thanks for reporting. This was due to iD really only looking at the start of preset names and `terms` for search results. I added "cycle" and "cycling" as terms for more bike-related presets.
