### ISSUE TITLE
allow to set the exact coordinates of a new amenity

### ISSUE THREAD

**Issue by ralfhauser** [openstreetmap/iD#6830]
In https://commons.wikimedia.org/wiki/File:26.77-Hatuniye_%C3%87e%C5%9Fmesi-1876_01.jpg, I get the exact camera location "39° 06′ 58.28″ N, 27° 10′ 39.72″ E"

Then I create this as "amenity=fountain" on osm and with lots of trying get to 
https://www.openstreetmap.org/edit?node=6769578220

==> please allow to edit the location of the node by entering the above geolocation string

**Comment by quincylvania** [comment]
As previously discussed in #4197, #6602, and #6819, we have no plans to enable manual location entry.

You can press <Cmd><Opt><M> or equivalent to open the Measurement panel, which shows the exact location of the selected node. You got it pretty close!

![Screen Shot 2019-09-04 at 9 12 34 AM](https://user-images.githubusercontent.com/2046746/64257937-49fa6700-cef4-11e9-8f4f-89d7d69bbcd5.png)

**Comment by sun-geo** [comment]
Off topic @ralfhauser,
The tagging for object https://www.openstreetmap.org/edit?node=6769578220 as `amenity=fountain` seems wrong.
Please check https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddrinking_water and for more options the "see also" subtitle enties:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddrinking_water#See_also
