### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by RisingGeek** [openstreetmap/iD#6832]
When trying to login using a third party(Google), the server responds with 500 error.
![Screenshot from 2019-09-05 15-56-25](https://user-images.githubusercontent.com/37294158/64334434-27507700-cff6-11e9-91d0-0d01e982447e.png)

**Comment by mmd-osm** [comment]
Try refreshing/reloading the error page via "F5" browser refresh. I had to do this several times until the logon finally succeeded. Looks like some timeout issue to me.

By the way, this repo is about the iD editor, you're reporting an error with the OSM website, i.e. this should be reported here: https://github.com/openstreetmap/openstreetmap-website

**Comment by RisingGeek** [comment]
got it
