### ISSUE TITLE
different node colors (grey vs white) for connection (shared) nodes

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6834]
I just noticed the different colors (grey or white) for connection (shared) nodes, see below. Is this OK?

![node color](https://user-images.githubusercontent.com/47290585/64378344-cabc7e80-d02c-11e9-87f9-cce3f1334388.gif)

**Comment by quincylvania** [comment]
@sun-geo This is intentional. The color indicates whether a vertex node is connected to one or multiple ways. In the lower case in your gif, the node is connected twice but to the same way, so it is not grey.

**Comment by sun-geo** [comment]
Ah yes, I was wondering how I can differ the unconnected white dot to the connected white dot. Now I see the difference, in the lower case (connected) the diameter of the dot is smaller than the unconnected top left dot.
