### ISSUE TITLE
v3 preview editor down?

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6835]
https://preview.ideditor.com/master/#background=none&disable_features=boundaries&map=10.60/20.03546/5.02997

![preview v3 down](https://user-images.githubusercontent.com/47290585/64378770-b3ca5c00-d02d-11e9-87cf-f55d2d042afb.png)

**Comment by BjornRasmussen** [comment]
It was working fine for me in North Carolina USA at 2:PM, two hours ago. Haven't tested it since.

**Comment by jomo** [comment]
can confirm both https://preview.ideditor.com/release and https://preview.ideditor.com/master are currently down

**Comment by mmd-osm** [comment]
Maybe try https://preview.ideditor.com/master/index.html and https://preview.ideditor.com/release/index.html

(There might be a redirect missing in the config somewhere)

**Comment by iandees** [comment]
The configuration for preview.ideditor.com should default to `index.html` now, so https://preview.ideditor.com/master/ and https://preview.ideditor.com/release/ should work when the configuration propagates.

I don't think we ever had a page at https://preview.ideditor.com/index.html, though.

**Comment by mmd-osm** [comment]
It used to work for a day or two, now somehow both redirects to index.html seem to be broken again.

**Comment by iandees** [comment]
This should be fixed now.

For posterity: I set up CloudFront in front of the S3 website that the builder is uploading to. Before, CloudFront was going straight to the S3 bucket and not doing the automatic index.html lookup.

Side note: I also set up Netlify so pull requests will get preview deploys and you can see `master` branch at https://ideditor.netlify.com/.

**Comment by bhousel** [comment]
Thank you for fixing this @iandees 🙇

**Comment by mmd-osm** [comment]
Cool, netlify supports gzip compression :+1:

**Comment by sun-geo** [comment]
Thank you for reactivation! :-)
