### ISSUE TITLE
copy & paste buttons

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6837]
Copy & paste works well for objects. Its seems currently implemented for using the common key combinations CTRL+C & CTRL+V. I'm not sure if it should also have buttons for these actions in the "context menu" when right click to an element or even to show buttons in the new top line button area for v3.

**Comment by quincylvania** [comment]
Yes, I think we should try doing this! We're tracking it over at #2508.

**Comment by sun-geo** [comment]
OK
