### ISSUE TITLE
Add preset for amenity=loading_dock

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6849]
Any chance you can add a preset for amenity=loading_dock? There's some additional tags that can be added on to it in the wiki.

Thanks

**Comment by quincylvania** [comment]
@Adamant36 Thanks for the suggestion! I added this. I would suggest someone update the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dloading_dock) to not recommend this tag for lines or areas, since it seems a natural fit for simply nodes along buildings.
