### ISSUE TITLE
Reverse operation for directional nodes

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6850]
It'd be useful if mappers could quickly invert the `direction` tag of nodes using the same Reverse buttons and <kbd>V</kbd> shortcut as for ways. Errors like the one below would then be fixable without opening the inspector.

![Screen Shot 2019-09-13 at 4 24 19 PM](https://user-images.githubusercontent.com/2046746/64892898-a58aca00-d643-11e9-99f7-6819e6138cc9.png)

**Comment by bhousel** [comment]
Oh yeah I have wanted this too!

A frustrating thing is that the direction dropdown currently has options like "Forward" / "Backward" / "All Ways", and I seem to always pick wrong.

**Comment by quincylvania** [comment]
> A frustrating thing is that the direction dropdown currently has options like "Forward" / "Backward" / "All Ways", and I seem to always pick wrong.

Same. Unless there's a directional arrow visible there's a 50/50 chance you'll have to reverse the node.

**Comment by quincylvania** [comment]
> A frustrating thing is that the direction dropdown currently has options like "Forward" / "Backward" / "All Ways", and I seem to always pick wrong.

Thinking about this more, a cool solution would be to preview the direction cones on the map as you hover over the options.

**Comment by quincylvania** [comment]
I realized I hadn't uploaded a demo yet… I think it works really nicely!

![reverse nodes demo](https://user-images.githubusercontent.com/2046746/65625628-7756a400-dfcc-11e9-8c98-20d415386c73.gif)
