### ISSUE TITLE
Unlimited scrolling to zoom in past z24

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#6851]
Firefox/Win10. I can zoom in as far as z24 using the + button, and at that point I also cannot use the scroll wheel to zoom in any further.

However at z23 or below I can use the scroll wheel and keep zooming in, basically to an unlimited number as indicated in the address bar.

**Comment by quincylvania** [comment]
@boothym Is the issue here that you shouldn't be able to infinitely zoom? Because I'd agree with that… we're not mapping atoms yet 😄

**Comment by boothym** [comment]
@quincylvania yes sorry, should've made myself more clear - basically, zooming past z24 shouldn't be allowed. I'm sure I don't remember being able to do it until recently.

**Comment by MegaArthur** [comment]
I'd say letting the user choose would be a nice idea though. Some inexperienced mappers don't know how to join nodes and you have to zoom way past z24 in JOSM to see that they are separated

**Comment by quincylvania** [comment]
> I'd say letting the user choose would be a nice idea though. Some inexperienced mappers don't know how to join nodes and you have to zoom way past z24 in JOSM to see that they are separated

I think there are better ways of telling if nodes are connected in iD, like noting if a vertex is grey vs. white or simply dragging one of them. I could see upping the max zoom to 25 or 26 but beyond that I don't think the benefit is worth the hit to usability and dev support.

**Comment by boothym** [comment]
@MegaArthur I'm not sure how allowing scrolling past z24 would help enable inexperienced mappers to join nodes? 😕 I doubt people go around zooming into nodes just to see if they are connected - iD turns the node colour from white to grey*, and now also issues warnings for crossing roads/paths etc. 

Plus, iD already prevents people from zooming in past z24 by clicking on the zoom in button. My suggestion is to stop people accidentally zooming in too far with their scroll wheel.

* perhaps the node could be change to a different shape if people don't notice the colour change?
