### ISSUE TITLE
Suggest both amenity=kindergarten and amenity=childcare as replacements for amenity=nursery?

### ISSUE THREAD

**Issue by jeisenbe** [openstreetmap/iD#6854]
Currently the deprecated features list suggests replacing `amenity=nursery` with `amenity=kindergarten`. Often this is correct, but the tag `amenity=childcare` is also common.

Is it possible technically feasible to offer this as an option as well, since not all nurseries are a preschool/kindergarten?

See https://wiki.openstreetmap.org/wiki/Deprecated_features and  https://wiki.openstreetmap.org/wiki/Tag:amenity=childcare

**Comment by quincylvania** [comment]
@jeisenbe iD doesn't support multiple upgrade paths right now, which is great for its simplicity. There's a mental cost to decision-making, so we shouldn't ask users to pick between two very similar tags if we don't really need them to. The new tags will always be an improvement even if they aren't perfect.

In this case there are fewer than 300 features with `amenity=nursery`, which is so few that someone could fix them all manually or make a MapRoulette challenge for them.
