### ISSUE TITLE
changeset viewer Achavi

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6855]
If welcome, please add Achavi [1] as another changeset viewer next to OSMCha in the History window view. (SHIFT+CTRL+H)

![History](https://user-images.githubusercontent.com/47290585/64908976-5d80ab80-d706-11e9-92bc-3eebdbb28050.png)

It seems Achavi even has advantage against OSMCha, because it can be used without login.

Similar to: ref https://github.com/openstreetmap/iD/issues/6202

By the way, it seems there is no option to translate the yellow word "History"(see screenshot) via transiflex, i'm right?

[1]
https://wiki.openstreetmap.org/wiki/Achavi
https://overpass-api.de/achavi/?changeset=cs-id
https://nrenner.github.io/achavi/?changeset=cs-id
Examples
https://overpass-api.de/achavi/?changeset=70637044
https://nrenner.github.io/achavi/?changeset=70637044

**Comment by Swyter** [comment]
I find `achavi` infinitely more useful than OSMCha for inspecting specific changes, and much more lightweight and practical to use, OSMCha is comparatively laggier and clunkier. It would be great having direct access to it.

**Comment by quincylvania** [comment]
@sun-geo Thanks for the suggestion! Looks like a cool tool.

> By the way, it seems there is no option to translate the yellow word "History"(see screenshot) via transiflex, i'm right?

The path is `info_panels.history.title`.

https://github.com/openstreetmap/iD/blob/191d0b9434d7a583c4b230c04995a5d62d53bc0e/data/core.yaml#L453

**Comment by sun-geo** [comment]
Thank you.

Yes, Achavi works very well for nodes and way changes, for big and changessets and changesets which touches relations i still using OSMCha...
