### ISSUE TITLE
4 ways, one node. Split one. Move this one.

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6858]
I know there are other issues related to this (https://github.com/openstreetmap/iD/issues/5635), but maybe this will help split them into separate tasks that make it easier to untangle the bunch of them (https://github.com/openstreetmap/iD/issues/1239). 

If not, please just close it again :).

**Situation:**
- 4 regular streets connect in one node
- I want to move one street away from the connection point
- But I dont want to change the geometry of the other streets / not create a changeset for those to keep my edits local. (Otherwise I could just move everything here and there and back to a similar position to get to the nodes I am looking for.)

**Current behavior:**
*Preparation*
- I click the street
- I shift right click the node, which - AFAIK - tells iD to select the node that belongs to the selected street
- I select "split" x

No the way is disconnected and selected.

=> This part works great (once you understand the shift click behavior).

<img width="400" alt="Bildschirmfoto 2019-09-15 um 07 34 05" src="https://user-images.githubusercontent.com/111561/64917320-3cb06880-d78f-11e9-80be-69e88358a6a5.png">

*Moving / Try 1*
The street is selected.
- I click the node where the streets connect
- move it
- => The other streets move, not the one I had just selected or just disconnected

*Moving / Try 2*
The street is selected.
- I shift click the node where the streets connect
- move it
- => The other streets move, not the one I had just selected or just disconnected

<img width="300" alt="Bildschirmfoto 2019-09-15 um 07 34 21" src="https://user-images.githubusercontent.com/111561/64917328-800ad700-d78f-11e9-9d31-2ee5d29e08e4.png">

Example Location: https://preview.ideditor.com/master/#background=Berlin-2019&disable_features=boundaries&id=n29790212&locale=en&map=19.50/52.49158/13.42088

*Ideas*
- The way I read https://github.com/openstreetmap/iD/issues/1239 is, that the idea is to detect overlapping nodes and handle situations like this
- This situation could also be solved by changing the "z-index" (if there is such a thing in d3) of selected ways/nodes: I select street A, all nodes of this street get a higher z-index. So once I click on the pile of nodes, mine is selected instead of the others.

**Comment by quincylvania** [comment]
@tordans Thanks! I'm pretty sure this is #2206. We do need a fix for #1239 but this specific issue would be addressed by always putting the node for the selected node on top.
