### ISSUE TITLE
Left Sidebar shortcut

### ISSUE THREAD

**Issue by hugobqd** [openstreetmap/iD#6864]
Despite many tests with the '`' key, I can't open the left sidebar with shortcut. I'm on a azerty (french) mac keyboard. Those keyboards neither have a "²" key.
Is it possible to add a universal key for that very important action ?

**Comment by quincylvania** [comment]
@hugobqd Thanks for reporting. What key is to the left of the number row? Is it <kbd>#</kbd>?

**Comment by hugobqd** [comment]
@quincylvania Precisely that's the `@`, you must add caps key to get `#`.
https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp13touch-space-select-201807_GEO_EMEA_LANG_FR?wid=1892&hei=1820&&qlt=80&.v=1531167628616
