### ISSUE TITLE
Add amenity/stripclub preset

### ISSUE THREAD

**Issue by tas50** [openstreetmap/iD#6867]
There's a large number of these to map here in Portland. It would be nice to have the preset in iD.

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dstripclub

**Comment by simonpoole** [comment]
While I don't necessarily agree with it, I believe there was a conscious decision not to include such facilities in the iD presets, so you might want to double check before going live with this.

**Comment by simonpoole** [comment]
See https://lists.openstreetmap.org/pipermail/osmf-talk/2014-September/002634.html ff

**Comment by quincylvania** [comment]
@simonpoole Thanks the context. I initially wrote a nuanced response inviting input but ultimately decided this issue isn't worth the potential aggravation right now and reverted the commit.

@tas50 We're thinking of ways to make mapping non-presets easier, like having an "Add more like this" button for the selected feature. Maybe something like this would suffice instead.

**Comment by EvanCarroll** [comment]
@tas50 @quincylvania @simonpoole  if this is something you want to see, I made the patch and it seems there is no resistance shy of not having an icon. So if someone can get the icon accepted, we're good.

https://github.com/openstreetmap/id-tagging-schema/pull/648

These issues are for the icon,

* https://github.com/FortAwesome/Font-Awesome/issues/8254#issuecomment-1321023839
* https://github.com/ideditor/temaki/issues/80
