### ISSUE TITLE
Imagery Request Error for Mapbox

### ISSUE THREAD

**Issue by ibuddy66** [openstreetmap/iD#6874]
When you go to request refreshed Imagery from Mapbox, it brings you to the page where you can view the imagery live on Mapbox, but then when you go to select the area it sends a 404 page not found error so you can't actually request new imagery which stinks because it's the most clear to use on ID.   

Going here as suggested by ID under the imagery/report problem https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery 

Then going to the link for Mapbox Imagery refresh. https://www.mapbox.com/bites/00240/#3/0.00/0.00

Then attempt to select and area to request and you'll get an error 404 page.

**Comment by tordans** [comment]
I just asked @pratikyadav about it at SOTM, this is a ping for him :-)

**Comment by ibuddy66** [comment]
Thanks!  Hopefully it can be fixed soon :)  Let me know if you need anything from my end at all.

**Comment by quincylvania** [comment]
@ibuddy66 Thanks for reporting! Hopefully the Mapbox folks can get this sorted out. It's not exactly an issue with iD though, so I'm closing this as non-actionable.

**Comment by ibuddy66** [comment]
@quincylvania is there anyone I should report it to at Mapbox?

**Comment by quincylvania** [comment]
@ibuddy66 I'm not sure who works on that specifically but you can report it to technical support [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231).

**Comment by 1ec5** [comment]
The feedback form has moved to [a centralized Feedback tool](https://apps.mapbox.com/feedback/satellite/), which you can access by clicking any “Improve this map” link on a Mapbox map and choosing “Fix satellite map”. The old “bite” page doesn’t appear to be maintained and is only accessible through a single years-old blog post.

**Comment by 1ec5** [comment]
Updated the FAQ in d908b2a7fdf95b8ce5376fa4fa61e645c2526c50.

**Comment by quincylvania** [comment]
@1ec5 Thanks for updating that!

**Comment by ibuddy66** [comment]
Hello all, @1ec5 I have contacted Mapbox about the issue which they said was an oversight that should have been updated when they did some switchover on their site.  They said it should be active again NOW I believe through the centralized form you mentioned.

**Comment by quincylvania** [comment]
@ibuddy66 Thanks for working through this with them!

**Comment by pratikyadav** [comment]
👋 Sorry for coming late on this post as I was traveling after SOTM. Thank you all for resolving this.
