### ISSUE TITLE
Removing a generic name should remove multilang name tags

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#6876]
Haven't found a similar issue so opening a new one.
Currently if iD detects a generic name in the _name_ field, validation catches it and offers to delete the tag as one of the options. I think it should also delete any _name:lang_ values as well.
Also related to this, a validation rule could highlight/warn if specific language name tags were not updated.

**Comment by quincylvania** [comment]
@tohaklim How about instead of removing all multilingual names automatically iD validates each name tag separately? There could be cases where the `name` tag is generic but `name:en` or `name:es` is okay.

**Comment by quincylvania** [comment]
> How about instead of removing all multilingual names automatically iD validates each name tag separately?

I did this. It should help mappers catch even more naming mistakes 👍

<img width="364" alt="Screen Shot 2019-09-24 at 1 23 59 PM" src="https://user-images.githubusercontent.com/2046746/65507642-a555be80-dece-11e9-9aad-f572779186bc.png">

**Comment by tohaklim** [comment]
Wow, I thought this would be too complicated with the validation rules, great work!

**Comment by quincylvania** [comment]
@tohaklim Thanks! We use custom code in iD for validation instead of rule files so it's straightforward to add highly-specific behavior like this.
