### ISSUE TITLE
Suggest adding an entrance node when mapping a building

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6877]
https://github.com/gravitystorm/openstreetmap-carto/issues/962#issuecomment-534077799 says perhaps iD should somehow suggest adding an entrance node when mapping a building.

Maybe when the user creates the area, have a "bump" stuck to one of its sides, which the user is supposed to then grab and move to where the entrance is, before being allowed to save the edit.
Or he should click on it where there would then be a choice "this building doesn't have a primary entrance / or unknown."

**Comment by quincylvania** [comment]
Once we do #6101 we could possibly have an option like "show me buildings without entrances." This isn't a blocking error though—mappers shouldn't be discouraged from contributing because they don't know or care about some detail.

**Comment by jidanni** [comment]
Actually as 95% of buildings are perhaps made by people tracing from imagery, maybe it should just be a button in the left panel when entering the building details, with button label "Add entrance", which then would trigger a dot the user could move to and release upon the entrance position.

**Comment by jidanni** [comment]
In fact it doesn't seem iD helps the user enter any https://wiki.openstreetmap.org/wiki/Key:entrance at all.

**Comment by 1ec5** [comment]
Note that a footpath or driveway could go right up to a building wall and touch it without an entrance being present. An “inquisitive warning” would be appropriate in this case.

In the case where a footpath only connects two buildings, there’s already a warning, which would ideally come with an option to add the entrances: #6341.

Perhaps iD v3 could have a toggle button in the toolbar that automatically adds entrance nodes when connecting paths to buildings or vice versa.

**Comment by quincylvania** [comment]
> Note that a footpath or driveway could go right up to a building wall and touch it without an entrance being present. An “inquisitive warning” would be appropriate in this case.

Yeah, I don't think we'd necessary offer to infer the entrance location.

> maybe it should just be a button in the left panel when entering the building details, with button label "Add entrance", which then would trigger a dot the user could move to and release upon the entrance position.

This actually might be fine. The prompt could include a "fix" that enters the mode to place an entrance feature.

**Comment by jidanni** [comment]
One also notes a standard procedure would be to grab the arrow in the line representing the front of the house, thus creating a new node. Then upon that node attach an address.
This works fine but leaves the front of the house a little bent :-(

**Comment by quincylvania** [comment]
> One also notes a standard procedure would be to grab the arrow in the line representing the front of the house and tug a little, thus creating a new node.

@jidanni If your input device supports it, you can double-click on any part of a way to add a point without without changing the shape.

**Comment by bhousel** [comment]
> mappers shouldn't be discouraged from contributing because they don't know or care about some detail.

This ☝️
