### ISSUE TITLE
	Company identification numbers

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6880]
When entering a business we see suggestion to fill in tons of items, from air conditioning to various payment methods... But what is lacking is the [Company identification number](https://wiki.openstreetmap.org/wiki/Talk:Key:shop#Company_identification_numbers). The prime way of uniquely identifying any company in many countries, and the biggest numbers printed on any receipts.

**Comment by BjornRasmussen** [comment]
How do you propose we tag this?

**Comment by quincylvania** [comment]
@jidanni I'm not sure that there's any way to tag these right now. The tags have to be resolved before we can consider supporting something in iD.

**Comment by 1ec5** [comment]
Company identification number schemes vary by taxing jurisdiction. Some of these schemes are already being tagged, most frequently [`ref:vatin`](https://taginfo.openstreetmap.org/keys/ref%3Avatin) for VAT identification numbers.

**Comment by quincylvania** [comment]
The only way I see this working is if we add some sort of `countryCodes` property for fields so they don't appear in unsupported regions. There are probably lots of uses for such field restrictions, like a GNIS code field.

**Comment by quincylvania** [comment]
I added a field for `ref:vatin` to countries that have VAT identification numbers. If this list needs adjusting let us know.
