### ISSUE TITLE
Change state of keepright issues after closing

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#6881]
Currently, after closing a keepright issue in iD for either reason, it simply exits the issue window. The issue is still on the map until a reload, and can be closed again with the same result. It would be nice if either:
 - closing it indicated so in the same fashion as closing a note, or
 - closing it removes it from the map altogether

**Comment by kymckay** [comment]
I fixed this in https://github.com/openstreetmap/iD/commit/51efd5b7144fda0d9771cf1f6995b9a7bb4cdbe7

Issue was caused by use of `.then` on the request promise because the KeepRight request errors (but still works), so I changed it to use `.finally`

**Comment by kymckay** [comment]
See:
https://github.com/openstreetmap/iD/blob/83d2656bbc604758657a40ceebe6bef4c7fa3ff1/modules/services/keepRight.js#L436-L459
