### ISSUE TITLE
Incorrect tagging of cycleway+footway

### ISSUE THREAD

**Issue by tomass** [openstreetmap/iD#6882]
iD is breaking years old standard of tagging ways, which are designated for both foot as well as bicycle. Such ways have always been tagged with:
```
highway=path
foot=designated
bicycle=designated
segregated=yes|no
```
Now iD is braking this and changing `highway` to `footway` or `cycleway`. If a way has `foot=designated` - it cannot be `cycleway`. If a way has `bicycle=designated` - it cannot be `footway`. Therefore path is the only possible value.

**Comment by quincylvania** [comment]
@tomass Thanks for your feedback. It turns out cycle paths with pedestrian access are tagged differently in different parts of the world. See #6836 for discussion on this topic in France.

Just let me know what other countries use the `highway=path` pattern and I will prevent iD from showing the preset in them.

**Comment by tomass** [comment]
Thank you.
Lithuania uses the original OSM tagging scheme described in the first post.

**Comment by quincylvania** [comment]
@tomass Okay, I made it so the preset in question won't appear in Lithuania. This will be live in the upcoming 2.15.6 release.

FYI in most places `highway=cycleway` is about more than access—it's considered a class in the road hierarchy with higher status than `highway=path`.

**Comment by rmikke** [comment]
Please add Poland as well. We only use highway=cycleway where there are no pedestrians allowed and the standard OSM tagging for shared paths.

**Comment by quincylvania** [comment]
> Please add Poland as well.

@rmikke This was done in 1bde4dd936d2514118bd69e4d42021b34fd8bfbe. Somebody messaged me about it outside GitHub.
