### ISSUE TITLE
8-Digit Hex Colour Tag

### ISSUE THREAD

**Issue by guylamar2006** [openstreetmap/iD#6884]
Adding support for 8 digit HEX color codes to the colour building:colour and roof:colour tags.

**Comment by quincylvania** [comment]
@guylamar2006 iD lets you put anything you want in the color field, so I'm not sure what you mean by this.

**Comment by guylamar2006** [comment]
On the main OSM screen the color preview shows for 3 and 6 digit codes but not for 8 digit codes after the # sign.
![Screenshot 2019-09-26 at 12 47 36 PM](https://user-images.githubusercontent.com/4555064/65712147-fc3cce80-e05b-11e9-8112-06a03992f675.png)

**Comment by quincylvania** [comment]
@guylamar2006 Ah I see. You'll have to ask over at https://github.com/openstreetmap/openstreetmap-website. The main OSM website is actually a different app than iD 😅
