### ISSUE TITLE
Allow enforcing rectangular building entry

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6885]
Got an idea. Sort of like #2277.
As 95% of houses one traces from air photos have all their walls at 90 degree angles,
and as the usual entry method is to click out the area, then use the right-click Square item (Shortcut: Q) to make it tidy...
Perhaps instead have a checkbox, remembered, that somehow keeps ones angles 90 degrees during entry, eliminating the final Q.

So it would be the same 5 clicks for a four sided house, and same 8 clicks for an L-shaped house, but all without the final Q.

(The final Q usually does a pretty good job, however it does add a little uncertainty as what the result will be.) 

(Note one cannot just hit Q after the fifth click, as the system thinks we want to choose "q(uarry)" etc. So an additional click is needed first too.)

(OK this is just for buildings, not for golf courses etc. areas.)

**Comment by quincylvania** [comment]
@jidanni Yep, we'll be adding a square drawing tool in iD v3. See #2699.
