### ISSUE TITLE
n-sided regular polygon building drawing tool

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6889]
Glad for https://github.com/openstreetmap/iD/pull/2699 however there is also the case of needing to produce exact triangular, square, etc. buildings. Imagine a [pentagon](https://en.wikipedia.org/wiki/The_Pentagon) beneath trees thus hard to trace from imagery.

https://www.openstreetmap.org/way/728244230 was supposed to be a perfect hexagon, and indeed doesn't look too bad at zoom level 19, but that is the limitation of ones hand, moving around the vertexes while trying to also match the exact number of square meters listed on the building permit using the CTRL+SHIFT+M Measure tool. (Building standing. No imagery yet.)

One notes that circles (tool (right click) exists already) are just a special case (high "n" number).
(So maybe just reuse the code for that tool, with the addition of allowing the user to specify "n"!)

Anyway one can think of some keyboard shortcuts: ...3 to make a triangle, ...4 to make a square, etc.

Some optional inputs it could take:
Length of a side ____
Total area____

https://en.wikipedia.org/wiki/Regular_polygon

Yes, after we create the polygon we can rotate and translate it into the desired position using current technology. (But that brings up the point that we are still using manual rotation trying instead of being able to input an exact azimuth, if known.) (And manual transport attempts to an otherwise known exact center point coordinates.)

**Comment by quincylvania** [comment]
My gut reaction is that regular polygons don't occur often enough in imagery to warrant their own tool, but then I remember the trials of tracing hexagonal gazebo roofs. Let's sit on this a bit.

**Comment by bhousel** [comment]
So far out of scope for iD, this will never happen.

**Comment by 1ec5** [comment]
I only ever find myself wanting this feature for hexagonal and octagonal shapes, which the existing Square operation doesn’t handle so well. But making the Square operation clean up those shapes would be a better fix.

That said, occasionally someone notices JOSM can create a perfect square using the Align Nodes in Circle tool and asks if iD has something similar. iD’s Circularize operation forms something like a dodecagon. This is usually more helpful than a square, but if you really need a square for some reason, here’s another 1ec5® Elaborate Workaround™:

<img width="800" height="200" alt="A series of four drawings. An almost square rectangle, with a vertex at the midpoint of each edge. The same but with a rhombus inscribed within the square, based on the midpoint vertices. The same but with the rhombus compressed into a square, distorting the original rectangle. The same but just the square." src="https://github.com/user-attachments/assets/ba3fdee2-606c-4e7d-9e62-59ef2d24988d" />

1. Draw an area that’s almost square (not too long along either axis). Use the Square operation to turn the quadrilateral into a rectangle. Double-click on the ‣ at the midpoint of each edge to add a vertex there.
2. Draw a second area by connecting the midpoints in step 1, forming an rhombus that inscribes the rectangle.
3. Use the Square operation on the area from step 2 to turn the rhombus into a square.
4. Delete the area from step 1. Rotate and resize the square as needed using the <kbd>R</kbd> and <kbd>Shift</kbd><kbd>+</kbd> and <kbd>Shift</kbd><kbd>−</kbd> shortcuts.

I haven’t looked into why this works or how fragile it is, but at a glance it does seem to yield perfect squares for me.

**Comment by jidanni** [comment]
Sounds kinda complex.
Maybe if iD simply has standard `ST_` GIS operations like `union` and `intersection` etc., the user could just draw a smaller rectangle upon the larger rectangle, and hit some command that would "rip of the knee patch we put on Johnny's trousers, taking the underlying cloth with it, leaving a neat rectangular hole."
