### ISSUE TITLE
Information panel appears to left of info buttons

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#6891]
Should be in between the buttons and right side of viewport as in previous versions. Started happening sometime this week.

![image](https://user-images.githubusercontent.com/25139386/65796724-595b8180-e13b-11e9-9a00-e28f00c1ecf4.png)

**Comment by quincylvania** [comment]
@rivermont Thanks for reporting. I've been fighting with these panes to have them behave in the flexbox but also scale to small screens. I think I finally got it now.
