### ISSUE TITLE
ID shows Warnings, but no corrective actions suggested

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#6898]
ID used to show the Warning (Tags, Conections, etc) and also Corrective actions to be taken. Now is just the Warnings.

**Comment by quincylvania** [comment]
@jjiglesiasg We didn't remove the fixes. Can you provide a screenshot of where you are seeing the issue?

**Comment by quincylvania** [comment]
Closing this as unable to reproduce and lacking further info.
