### ISSUE TITLE
Some presets are understood by users incorrectly

### ISSUE THREAD

**Issue by SviMik** [openstreetmap/iD#6899]
It is not clear for editors to what kind of object some presets must be applied.

For example:
`amenity=school`
`amenity=kindergarten`
&dash; people keep applying these presets on buildings instead of, for example, school grounds like the wiki says.

Please fix your UI to make it clear that these presets are not meant to be applied on buildings.

**Comment by Discostu36** [comment]
It could be a rule for the validator, that the user has to decide between one of the two.

**Comment by bhousel** [comment]
We've been through this many times
https://github.com/openstreetmap/iD/issues/5883#issuecomment-462830659

Please stop trolling our project.
