### ISSUE TITLE
Render patterns in area preset icons

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6900]
A few areas use pattern images instead of solid colors for fill rendering. The preset icons can look weird when they don't support these.

<img width="257" alt="Screen Shot 2019-09-30 at 11 19 43 AM" src="https://user-images.githubusercontent.com/2046746/65866535-3c11f780-e375-11e9-8cc9-13a409a79f9b.png">

**Comment by quincylvania** [comment]
I did this. I'm not sure I like them all but maybe that means we could use some better patterns overall. I'll leave them for a bit to get some feedback. Not sure if they'll make the release.

<img width="164" alt="Screen Shot 2019-09-30 at 12 22 45 PM" src="https://user-images.githubusercontent.com/2046746/65870842-72ec0b80-e37d-11e9-89f2-3c262bd40841.png">
<img width="188" alt="Screen Shot 2019-09-30 at 12 23 37 PM" src="https://user-images.githubusercontent.com/2046746/65870841-72ec0b80-e37d-11e9-9980-d3d0091b352d.png">

**Comment by bhousel** [comment]
Sorry but I really hate this, would you consider reverting?
(I've never been a fan of the patterns, but they look really bad like this on the preset area fill).

**Comment by quincylvania** [comment]
@bhousel Sure will do. Figured it was worth a try but you're right they don't look great.

**Comment by quincylvania** [comment]
I just made the Construction icons yellow instead.

<img width="183" alt="Screen Shot 2019-09-30 at 2 22 27 PM" src="https://user-images.githubusercontent.com/2046746/65878244-db42e900-e38d-11e9-8bcb-7d2537df9e5b.png">
