### ISSUE TITLE
Add method to adjust diameter of existing circles

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6903]
Circles are very easy to create using the right click circle tool.
However such circles are very hard to later resize if needed.
Perhaps also add methods of decreasing and increasing the diameters of such circles.

**Comment by BjornRasmussen** [comment]
A general "expand" or "resize" tool might be better than something just for circles, since iD shouldn't treat circles any differently than other polygons.

**Comment by quincylvania** [comment]
> A general "expand" or "resize" tool might be better than something just for circles, since iD shouldn't treat circles any differently than other polygons.

Yep, this is #3372.
