### ISSUE TITLE
jsdelivr no longer serving iD assets

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#6908]
We sometimes use iD assets like icons in other projects (e.g. our `taginfo.json` file and nsi.guide reference them), so we try to make them available from a CDN.

We previously used [rawgit.com](rawgit.com) for this, but it's being shut down, so I switched to [jsdelivr.com](https://www.jsdelivr.com/?docs=gh) in 36f3a29.

Now jsdelivr is not indexing iD anymore because our repo size has started to exceed 50MB.

This works (an icon that was indexed a while ago):
  https://cdn.jsdelivr.net/gh/openstreetmap/iD/svg/fontawesome/fas-leaf.svg
This is broken (an icon recently added):
  https://cdn.jsdelivr.net/gh/openstreetmap/iD/svg/fontawesome/fas-laugh-beam.svg

So we have to do one of these:
1. make iD smaller (recent size increase is due to the new cldr locale data)
2. move assets like preset icons to a separate repo, something that jsdelivr can handle
3. use something other than jsdelivr, maybe switch back to raw.githubusercontent.com, but suffer a speed hit.

**Comment by MartinKolarik** [comment]
Hi, Martin from jsDelivr here.

That link serves the latest release, v2.15.5, which doesn't have that file. To serve files from master branch, use: https://cdn.jsdelivr.net/gh/openstreetmap/iD@master/svg/fontawesome/fas-laugh-beam.svg

Regarding the limit, for `/gh/` links, we're able to serve files (up to 20 MB) regardless of the total repo size, you just won't get directly listings.

**Comment by bhousel** [comment]
Wow thanks @MartinKolarik for stopping by!
I was misreading the 50 MB error message, and thought it meant the whole repo size 😄  We do want to serve the files from master, so I'll give that a shot..

**Comment by MartinKolarik** [comment]
> I was misreading the 50 MB error message, and thought it meant the whole repo size 😄

It does, because if fetching the individual file fails (like here because it doesn't exist), we attempt to fetch the whole tarball, which then triggers this message. Either way, you should be fine with `@master`.
