### ISSUE TITLE
Search missing final mouseover step

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6914]
Can iD please show the user where
![X3](https://user-images.githubusercontent.com/1230959/66255225-da59ef00-e7b3-11e9-9722-e8478a43140f.jpg)
is talking about?
Currently one must leave the editor and do
![X4](https://user-images.githubusercontent.com/1230959/66255236-f2ca0980-e7b3-11e9-9071-7430d83dcc6c.jpg)
which shows the user where, upon mouseover of the lat,lon.

Please have iD do the same.
iD is missing the mouseover part.
Thanks.
Else we cannot tell where it is talking about.
All we know is it is on the screen somewhere.

**Comment by jidanni** [comment]
(Bob: Which house out of the rows and rows is the museum? I want to put
it on the map.

Mary: It's in my notes: the one at 31.123456,42.345678.

Bob: I'm unable to use that. Do you know what color the roof was?

Mary: I think it was the same color as the rest.

Bob: Can you go back and tell me which house it was from the start of
the block.

Mary: (one year later) the third.

Bob: Can you go back and tell me which block it was from the start of
the town.

Mary: (one more year later) the fifth.

Bob: Can you go back and tell me which side of the street it was on...)

**Comment by quincylvania** [comment]
@jidanni When you click the coordinate result the location is the center of the map. If that's hard to determine then you can use the `+` shortcut to zoom in. I think this is fine for most use cases but I suppose it would be nice to also show some kind of marker.

**Comment by jidanni** [comment]
No no no no no no no no .... no.
Sorry.
The vague area in the center is just too vague.
Painfully vague.
Yes please add this tiny missing oversight. Thanks.
Indeed that would close a lot of (already closed) issues about never being able to put something somewhere even if one knows where...

**Comment by quincylvania** [comment]
@jidanni You can zoom in so far that the entire map shows just a few square meters, which should be sufficiently specific. OpenStreetMap does not operate at minuscule resolution.

iD is also not designed for entering features at predetermined coordinates, as you are well aware. This is not an oversight.

**Comment by jidanni** [comment]
Yes however with the OSM website style marker, the user is assured that the center is not slipping to the side as one zooms. With a uniform pixel background it may be hard to tell.

**Comment by jidanni** [comment]
I am guessing the center of the screen is somewhere below "Area".
![X6](https://user-images.githubusercontent.com/1230959/66525628-a4f13080-eb28-11e9-8cb4-67e8b13fdaa7.jpg)
OK I tried to hold up a ruler to my screen but it was not long enough. I got a USB cable to fold over and find the halfway point but I risk falling off the bed and knocking over the monitor.

I could take a marker and draw a big X on the monitor but I might knock it over and would have to wipe it off.

This is so frustrating, and not something I recall having to do in all my collage years.

**Comment by jidanni** [comment]
I tried to reverse engineer
![X8](https://user-images.githubusercontent.com/1230959/66526376-04e8d680-eb2b-11e9-853e-8a3b28626283.jpg)
and
![X7](https://user-images.githubusercontent.com/1230959/66526394-17fba680-eb2b-11e9-9987-e66d4498b034.jpg)

I suppose I will just have to paste rulers on the sides of my monitor.

**Comment by jidanni** [comment]
OK. One workaround I found was (X axis example:) make the window very narrow,
![X9](https://user-images.githubusercontent.com/1230959/66526586-d61f3000-eb2b-11e9-83ff-c3897d2470bf.jpg)
then click the coordinate search. OK, now we have a pretty good idea where the X axis of the center lies.

**Comment by eehpcm** [comment]
@jidanni 

> OK. One workaround I found ...

I've been down this route before.  I suspect what you're asking for and what iD's developers think you're asking for are different things, because that's how it seemed when I tried it.  What came out of that discussion was something they mentioned that turned out to do what I needed.

Shift-control-L is your friend.  Try it and see.  I think it may do what you want.

**Comment by bhousel** [comment]
@Firefishy or @tomhughes  would you please ban @jidanni from our repo.
I can't take this guy anymore.  I've had him blocked for years but he continues to troll our project.
