### ISSUE TITLE
Cliff directional arrow has different colour to the line

### ISSUE THREAD

**Issue by huonw** [openstreetmap/iD#6918]
It seems cliffs had their colour changed in https://github.com/openstreetmap/iD/commit/5f9bea67da0377ce96a514a1b890e89d1d1e525c, but the directional arrow remained green.

<img width="154" alt="image" src="https://user-images.githubusercontent.com/1203825/66268806-ce8e2b80-e88c-11e9-9606-9702d93e9cf0.png">

**Comment by AbidemiT** [comment]
Hello, I'm interested in taking this up.

**Comment by bhousel** [comment]
> Hello, I'm interested in taking this up.

sorry @AbidemiT , it looks like #6919 already addresses the issue.
