### ISSUE TITLE
Restriction mini-editor displays misleading arrows when allowing via ways with loop drive-through

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6922]
A typical Kroger store has [a pharmacy drive-through that loops around](https://www.openstreetmap.org/#map=19/39.21991/-84.51874), overlapping the side access road that leads to the loading docks. Notice the pavement marking that loops around:

[<img width="269" alt="kroger" src="https://user-images.githubusercontent.com/1231218/66332207-0b880b80-e8e9-11e9-8238-b41bc5ef0b20.png">](https://www.openstreetmap.org/#map=19/39.21991/-84.51874)

At least theoretically, once a driver enters the drive-through, they shouldn’t exit onto the access road, so there would be an `only_straight_on` restriction relation. There would also be `only_straight_on` restrictions in both directions of the access road, because a driver shouldn’t cut in line by ignoring the part of the drive-through that bows out to the south.

When I attempt to add an `only_straight_on` restriction relation to the drive-through, it adds an `only_right_turn` restriction, though it does involve the correct ways, so I can easily correct the restriction type:

<img src="https://user-images.githubusercontent.com/1231218/66332680-214a0080-e8ea-11e9-83aa-cb1eb3cf19fd.png" width="357" alt="drive-through">

Unfortunately, when I attempt to add an `only_straight_on` restriction relation to the access road going westbound, the mini-editor thinks the way already has an `only_right_turn` or `only_straight_on` restriction onto the northern part of the drive-through:

<img width="359" alt="westbound" src="https://user-images.githubusercontent.com/1231218/66332840-8867b500-e8ea-11e9-809e-97ff6b2995da.png">

Clicking the straight and right turn arrows has no effect.

I would’ve expected the mini-editor to indicate that no restrictions currently apply to the access road, just as when selecting the eastbound approach:

<img width="359" alt="eastbound" src="https://user-images.githubusercontent.com/1231218/66332997-dda3c680-e8ea-11e9-80e3-073c712e0280.png">

In these screenshots, “Via” is set to “Up to 1 way”. If I change “Via” to “Node only”, then the westbound configuration looks like the eastbound configuration, as expected. Apparently, the mini-editor wants to show that, if the driver heads _eastbound_ on the westbound approach, then enters the southern part of the drive-through, they must continue on the drive-through:

<img width="359" alt="Ảnh chụp Màn hình 2019-10-07 lúc 10 07 21" src="https://user-images.githubusercontent.com/1231218/66333335-9e29aa00-e8eb-11e9-8c5f-ac86e12db8ba.png">

But this is less important than allowing the user to indicate whether the driver can go _westbound_ on the westbound approach and turn right onto the drive-through.

**Comment by bhousel** [comment]
My guess is that the restriction editor is walking all the paths of the graph and just happens to draw the red and blue arrows for that via-loop exactly on top of whatever green arrows it would draw for the direct westbound travel.  

> In these screenshots, “Via” is set to “Up to 1 way”. If I change “Via” to “Node only”, then the westbound configuration looks like the eastbound configuration, as expected. 

Can we close this and say that if users want to edit a thing like this they need to have it set to "node only" ?   I actually think we should have the default be "node only" and users should need to opt into the via way restrictions.

**Comment by 1ec5** [comment]
Yeah, I think changing the default to node only, if it isn’t already, would address this issue. It’s quite an edge case, so it can be one of the tradeoffs for opting into via ways.

Incidentally, is there a good place in the help documentation to explain what you’re getting into when you adjust that setting? Not that we’d describe this edge case, but just to make sure we don’t lead mappers to prematurely fiddle with the setting.

**Comment by bhousel** [comment]
> Incidentally, is there a good place in the help documentation to explain what you’re getting into when you adjust that setting? Not that we’d describe this edge case, but just to make sure we don’t lead mappers to prematurely fiddle with the setting.

Not really.. there is a "?" icon to explain the turn restrictions field, but I really don't go into too many details.  I mostly just try to suggest that people use the simplest possible way to encode the restriction.
