### ISSUE TITLE
"There is no documentation available.  View documentation"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6923]
After clicking the "i", the user sees this:
![X3](https://user-images.githubusercontent.com/1230959/66362594-fb8a2d80-e9b5-11e9-8121-8b4b846f1b62.jpg)

"There is no documentation available.  View documentation"
Sure, they are referring to different things, but look funny juxtaposed.

**Comment by bhousel** [comment]
So click the pencil and write some.  FFS

**Comment by jidanni** [comment]
> So click the pencil and write some. FFS

Writing some will fix it for that page only, but not the rest of the pages.
I am only talking about juxtaposition.
And please mind your own https://github.com/openstreetmap/iD/blob/master/CODE_OF_CONDUCT.md .
Thank you.

**Comment by jidanni** [comment]
See also https://github.com/openstreetmap/iD/issues/6442
