### ISSUE TITLE
Measurement Tool: add final segment distance

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6924]
The Measurement Tool lacks one important feature: the distance between the last nodes.
```
Measurement
w-34  (? what's this)
Geometry:line
Number of nodes:7
Length:161.7 m
Last segment length: 4.1 m <====== Add this
Centroid:24°11′26″N, 120°52′25″E24.1906301, 120.8736610
Metric
```

Proof: let's say one wishes to place utility poles at the following
intervals along a road: 3, 9, 10, 8, 13, 3, 6 meters.

With our "Last segment length" field we can easily make a line with nodes
at those distances:

```
=========Nordsburg=======Estates======Drive==========
---o--------o---------o-------o------------o--o-----o
```
Then edit each node and finally remove the line,
```
=========Nordsburg=======Estates====Drive============
   o        o         o       o            o  o     o
```
without having to make an accrued distance table to match the tool.
(3, 12, 22, 30, 43, 46, 52.)

**Comment by bhousel** [comment]
> Proof: let's say one wishes to place utility poles at the following
> intervals along a road: 3, 9, 10, 8, 13, 3, 6 meters.

No.  Just place the points where the poles are on the imagery.
Stop asking us for this stuff.

**Comment by jidanni** [comment]
They are not always on the imagery. For instance the foundations of a ruins in a dense jungle.

Let's say we need to enter a 5x10 meter house, or 50x100 meter playing field.
OK, with the Measurement tool we are very happy that we can get the first side, 5, or 50 meters wall entered fine.

But then things fall apart.

Therefore, aside from just showing the accumulated distance, please also show the length of the current segment too.

Sure, 150-50=100, and 250-200=50, and 300-250=50, but please...
