### ISSUE TITLE
Warn point will render within road

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6925]
In the editor one places a point on the side of a road,
https://www.openstreetmap.org/node/4778301333
but it gets rendered in the **middle** of a road.

> Didn't some alarm go off in the editor that "you are putting an
> electric pole in the middle of a highway where cars will slam into it!?"

No. And zooming in the editor you will see I put it on safely the side
of the road.

> Well didn't the editor warn you that even so, it is too close to the
> road, and will probably get rendered inside the road?

Nope.

> Well didn't you simply observe from the imagery that roads are a
> little thicker than the stick figures / wire frame used in the editor?
> That's what the imagery is for. Is your computer screen too dim?

It was in a forest. All there are are trees in the imagery. My boss is
asking me "Were you drunk? You put all those electric poles right in the
middle of the road. Autopilots are now avoiding our community. People
are laughing at the map!"

**Comment by jidanni** [comment]
> At zoom level 18 it **is** within the road in the editor.

Well not at zoom level 17 or 19.

**Comment by leifr-unc** [comment]
I don't think anybody else is confused by this, and even if they are, this is still quite low impact.

**Comment by BjornRasmussen** [comment]
I don't think anybody else is confused by this, and even if they are, this is still quite low impact.

**Comment by jidanni** [comment]
So experienced editors have the common sense to keep a bit of distance outside of roads, like experienced drivers know to keep a bit of distance within roads. Each avoiding the curb. Hmmm. OK, I guess.

**Comment by jidanni** [comment]
Actually this is very much not OK.
Even armed with the knowledge that I should keep a safe distance from roads, just seconds ago I managed to drag many poles from too far away from the road, right into the path of vehicles now.
https://www.openstreetmap.org/changeset/75437022

In fact it seems that your average electric poll **will** end up within a road,
https://www.openstreetmap.org/#map=16/24.1940/120.8760
and perhaps this is more a https://github.com/gravitystorm/openstreetmap-carto issue...

**Comment by jidanni** [comment]
Yup. Must be a rendering issue. Closing.
