### ISSUE TITLE
Don't say "Search features"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6928]
![X0](https://user-images.githubusercontent.com/1230959/66511892-677daa80-eb0a-11e9-96c1-643b44038d73.jpg)
Don't say "Search features" because some people will think "gate", "tree", "chain" are features.
Say perhaps instead "Search placenames" or "Search place names" as "Nordsbury Heights" are place names, and in fact the type of item one can search for with this box.

**Comment by BjornRasmussen** [comment]
The UI of V3 eliminates this.  See preview.ideditor.com/master

**Comment by jidanni** [comment]
@BjornRasmussen Sorry. Problem 100% still there.
![X5](https://user-images.githubusercontent.com/1230959/66522500-21cbdc80-eb20-11e9-9499-928cb023e5d0.jpg)

**Comment by bhousel** [comment]
#5214 would give people hints about what things they can type here.
