### ISSUE TITLE
Bing background blurred

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#6929]
For the past few weeks, I occasionally notice that when I pan the map using Bing background imagery, the new area is blurrier than the old area (even when part of the old area is still visible for comparison).  It looks like the new tiles have been fetched at a lower resolution.  It doesn't appear to be preloading a lower-res version then the high-res version taking a long time to load as I've waited several minutes.  Switching to a different background layer then immediately back to Bing fixes it.

It's not reproducible at will, it happens randomly and rarely.  I have no idea if it's a problem with iD or with Bing.  It does seem to be relatively new, though, so if you've changed anything to do with fetching tiles recently it might be worth a quick look.

Firefox 60.8.0esr (64-bit).

[edited to add this]

I just got lucky.  It happened again and this time I was smart enough to screengrab it.  Sadly, not an area of the map where it's easy to see the problem.

![blurred on left](https://user-images.githubusercontent.com/3224921/66526521-e1089f00-eaf0-11e9-8d2c-6cd8c02e3bbe.jpg)

Then I did a quick ctrl-b, ctrl-b to clear the blur.

![back to normal](https://user-images.githubusercontent.com/3224921/66526539-01d0f480-eaf1-11e9-8094-284697aa3318.jpg)

The difference is rather subtle with the images displayed inline here.  If you can't spot the difference, the blurring is to the left of the B4459 road label.  At full size it's more obvious.

[edited again to add more]

Must be my very lucky day.  Just happened again.  This time where it's easier to see.  Sorry about the slight pan of the map between grabs, it wasn't intentional.

![with blur](https://user-images.githubusercontent.com/3224921/66527098-cdf6ce80-eaf2-11e9-86ee-8b718d9e1a89.jpg)

![without blur](https://user-images.githubusercontent.com/3224921/66527108-d8b16380-eaf2-11e9-8295-b1b33cc1b64b.jpg)

**Comment by rivermont** [comment]
This sounds more like a connection issue than a problem with iD. If the tileserver is overloaded, or a connection anywhere from your browser to the server is throttled or broken, this can happen. The random nature would also indicate that.

Do you get the same problems using iD v3 on the [preview site](https://preview.ideditor.com/master/index.html)?

**Comment by eehpcm** [comment]
@rivermont 

> This sounds more like a connection issue than a problem  with iD.

Could be almost anything.

> If the tileserver is overloaded, or a connection anywhere from  your browser to the server is throttled or broken, this can happen.

I'm tethered via my mobile.  Signal strength is, and always has been, variable since before I started mapping.  But this is recent behaviour with iD although my connection is as good (or bad) as ever.  For some reason, something is giving me lower-res images and this has only been happening for a few weeks despite years of having the same poor connection.

>  The random nature would also indicate that.

Maybe, maybe not.  Most times this has happened, I've panned back to an area I've previously looked at only minutes before.  Something, somewhere, cached the tiles I'd previously seen because they were displayed briefly (less than a second).  Something, somewhere, decided those cached tiles were invalid (even though it had been less than a couple of minutes since it had grabbed them).  And the replacement tiles were lower res, because I saw a sharp area go blurred as the new tiles loaded.

Maybe you're right, but I'm not sure how anything in the chain would be keeping track of my connection speed and deciding which version of tiles to give me based on that speed.  There are times, when the connection is particularly bad, that the tiles can take a minute or even two to load, but when they appear they are sharp.

If you forced me to bet on it, I'd go with one of Microsoft's many load-balanced tileservers being misconfigured and occasionally the load-balancer gives me tiles from that.  But I have no standing to deal with Microsoft so I have no way of investigating.  All I can do is mention it here just in case there have been changes to iD recently in that area.  It's a long shot, but about the only one I have.

> Do you get the same problems using iD v3 on the preview site?

I've not tried it.  And since this happens maybe once or twice a week, I'm not sure how conclusive that would be anyway.  I'm not keen to play with something that's likely to change a lot as the design is refined.

**Comment by bhousel** [comment]
My guess is that iD is failing to load a tile because of a network issue, so it tries to load the tile at one zoom level lower and continues doing that until it happens to succeed.  It appears blurry because that tile has less resolution than the one that should appear in that spot.

You can check by opening the developer tools in Firefox and seeing what the network connections are doing.  I really don't think anything in iD code has changed recently that would affect this.

**Comment by eehpcm** [comment]
@bhousel 

> My guess is that iD is failing to load a tile because of a network issue, so it tries to load the tile at one zoom level lower and continues doing that until it happens to succeed.

Ah, OK.  That makes sense.  I think I'd actually prefer iD not to back off.  Because when I do a double ctrl-B to unblur, the connection has become fast enough that it's OK.  So it was only a temporary blip.  Yeah, it means the tile load would be slower, but my computer is old and slow and I'm old and slow so I can put up with that. :)

> You can check by opening the developer tools in Firefox and seeing what the network connections are doing

My computer is slow enough that running with dev tools open would be painful.  And since it tends to be a one-off with days (usually) between occurrences, opening dev tools after I got a blur would be bolting the stable door after the barn burned down.

But thanks for checking and explaining.
