### ISSUE TITLE
Can't tell which is the editor via the browser tabs

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6931]
Which tab is the iD editor, which tab is the (Carto map) OSM website?
![X3](https://user-images.githubusercontent.com/1230959/66522575-55a70200-eb20-11e9-935d-c03a40ce133a.jpg)
- Same icons
- Same HTML <title>

(I thought this was fixed.)

**Comment by bhousel** [comment]
This is an issue for https://github.com/openstreetmap/openstreetmap-website
iD runs inside an iframe there, so we don't control the title and icon.
