### ISSUE TITLE
Uninformative error raised by presence of junction=spui on motorway links

### ISSUE THREAD

**Issue by weech** [openstreetmap/iD#6933]
The `junction=spui` tag is used frequently in some parts of the US to tag motorway links, and in iD this raises an error 'Motorway Link should be a closed area based on the tag "junction=spui"'. It offers to connect the ends to make a closed loop, which is not good. In the OSMUS Slack, @bhousel mentioned that this has been discussed before in #4637 and in [this comment](https://github.com/openstreetmap/iD/commit/781158874aa19cc6f5d1202e6f2ae4ca53ac722f#commitcomment-32675728), and, from what I understood, it stems from `junction=yes` being an implicit area technically when it often is not tagged that way on the ground. An example SPUI interchange can be found at https://www.openstreetmap.org/edit#map=19/40.62017/-111.90319.

**Comment by bhousel** [comment]
Made these changes in 6dfdec06a:

Ignore `junction` in areaKeys code and remove the unsearchable presets
(closes #6933)
    
We should not be adding unsearchable junction presets for every kind of
junction as a hacky workaround to treat `junction=yes` as an area.
    
This should remove the special treatment of junction tag.
* `junction=*` will not be treated as an area by default
* `junction=*` will not trigger validator warnings that they should be closed
* `junction=yes` mapped as an area _will_ need an `area=yes` now, which iD will add
(afaik this is the only junction tag that should be treated as an area)

**Comment by bhousel** [comment]
History for this can be found on 
#2484, #4637, and 781158874a
