### ISSUE TITLE
Show resolved issue counts in the UI

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6935]
Now that #6459 is done, iD knows how many preexisting issues were fixed by the mapper. We should surface this in the UI to encourage mapping for QA.

**Comment by ferdinand0101** [comment]
Would this also be a thing which could be called by an API like hdyc already does for errors

I believe that this would help motivate people

**Comment by quincylvania** [comment]
@ferdinand0101 Woah, I had no idea that HDYC looked at iD warning counts. Seems like it already has support for resolved issues too! You can see them on [my page](https://hdyc.neis-one.org/?quincylvania) since I've been testing the feature.

<img width="572" alt="Screen Shot 2019-10-11 at 4 41 23 PM" src="https://user-images.githubusercontent.com/2046746/66660970-6e113c80-ec46-11e9-9d69-662b231703f9.png">

So to answer your question, yes, apps can query changesets to see resolved issue counts.

**Comment by quincylvania** [comment]
CC: @pa5cal 👏

**Comment by pa5cal** [comment]
Great that it's now working.
Yes, I implemented this back in June, see https://twitter.com/pascal_n/status/1144515284453273600
