### ISSUE TITLE
Deleting nodes: don't jerk screen if next node nearby

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6936]
When one deletes a node of a polygon, the screen is reentered on the next node.
This works perfectly when one is working with e.g., high voltage lines, where the next node might be many screens (kilometers) away.

However such jerking is unwanted when the next node is merely an inch away on the screen, whereupon such jarring is unexpected and makes us lose our concentration. Therefore it should be limited to cases where the next node is farther away. 

Yes we probably want to delete the next node too, but often not. So in fact might not be prepared to sail kilometers away either, with no easy way to get back. So maybe in addition to a trash can, there should be a trash can plus wing icon, so we can choose if we want to be transported to the next node or not, upon deletion.

**Comment by BjornRasmussen** [comment]
I disagree, because the map moving is one of the visual cues of vertex deletion I've gotten accustomed to.  Losing this visual feedback would have a cost to many users, and would not be worth it.

**Comment by jidanni** [comment]
OK. Maybe I will grow to like it too.

**Comment by jidanni** [comment]
No, no, no... it is really undesirable.
Yes it is OK if the nearest node is somewhat far away.
But please consider the case where we are editing an outhouse, etc. small building. Just removing an extra node (5 becomes 4.)
Sending the screen flying into the next neighborhood just doesn't make sense.
We have to look around and find the building we were editing again for each node we delete.
The screen should simply stay put in such cases.
