### ISSUE TITLE
Non-default fields are sorted in ASCII order

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6937]
The non-default field dropdown list is always sorted in ASCII order, but it should be sorted in a language aware way. For example, in Vietnamese, “Đ” comes after “D” but before “E”, whereas 
ASCII order means it comes at the end of the list:

<img width="336" alt="english" src="https://user-images.githubusercontent.com/1231218/66697436-7c814780-ec8a-11e9-840b-5a2e4e6838f7.png">

This is only a minor annoyance in Vietnamese, but I can imagine it being a bigger hurdle in a language written in a non-Latin script that may not be laid out alphabetically in Unicode.

The code that sorts these field names should use [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) rather than a simple `>` operator:

https://github.com/openstreetmap/iD/blob/d01bb7870772f8f8a73ccf660708ae094502da2a/modules/ui/preset_editor.js#L57-L59

**Comment by quincylvania** [comment]
@1ec5 Thanks for reporting, I switched this to use the [`localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) function.
