### ISSUE TITLE
Consider renaming `amenity=post_box` preset in English

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6939]
Now that we have an `amenity=letter_box` preset (#6718), mappers have to distinguish between that and `amenity=post_box`. I think the icons do an okay job of differentiating them, but the word "mailbox" can refer to either of these things in the US. I'd like to change "Mailbox" to something like "Post Box", "Mail Collection Box", or "Mail Drop Box" (see https://en.wikipedia.org/wiki/Post_box).

<img width="285" alt="Screen Shot 2019-10-14 at 1 32 10 PM" src="https://user-images.githubusercontent.com/2046746/66748323-2d543600-ee87-11e9-97c5-29840ee5ff88.png">

**Comment by GenericError** [comment]
Personally, I think "Mail Collection" would be the way to go. Whilst yes you could say that it is collected by the individual at the residence, I would assume more people would assume it collected by the relevant postage agency. Also the icons are great for distinguishing as you said. Perhaps if "post box" was added as a synonym when searching?

**Comment by Nakaner** [comment]
The icons might be understandable for US Americans but post boxes by the national mail service look different in each country – even in their shape. None of the shapes depicted above is common in Germany. I presume that this is no different elsewhere. Please take the time and travel ~around the world~ [through Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:Mailboxes_by_country) (the category mixes the two features we discuss about).

The EN-US locale is the default locale and not used by native speakers only. Relying on subtle differences in wording could work if the user comes from the same country (maybe even the social group?!) but it is likely to be understooden differently if the shared knowledge differs too much. Therefore, relying on the icon is risiky. It is small and partially eye candy only.

Therefore, I suggest to rename "Mailbox" to "Mailbox (mail service/collection)" and "Letter Box" to "Letter Box (personal/recipient)".

**Comment by bhousel** [comment]
> Therefore, I suggest to rename "Mailbox" to "Mailbox (mail service/collection)" and "Letter Box" to "Letter Box (personal/recipient)".

In the German localization on Transifex, you can translate the presets to say you want.  I've suggested this to you before several times.

**Comment by 1ec5** [comment]
This would get even more complicated if we ever start distinguishing relay postboxes (which letter carriers use but the general public do not). I think it would be fine if even the English labels of the presets were more explicit and technical, like “Mail Collection Box” versus “Mail Delivery Box”, as long as more colloquial terms like “mailbox”, “postbox”, and “letterbox” remain on the applicable presets as synonyms. These technical names would be pretty intuitive, especially if the user sees them both at the same time when searching for “mailbox”.

Putting “personal” in the `letter_box` preset could be problematic because the tags don’t necessarily distinguish between personal and commercial delivery service. But “private” could work.

**Comment by Nakaner** [comment]
@1ec5 The exact wording of my suggested terms should be seen as an example. My aim is to have descriptive titles for the presets.

**Comment by quincylvania** [comment]
@Nakaner Thanks for your thoughts. I realize that these icons aren't universal. One day we should figure out a way to localize iD's preset icons.

I agree it might be nice to show more information in the list so users can be more confident in selecting presets. #6131 would address that without complicating preset names.

**Comment by quincylvania** [comment]
I went with "Mail Drop Box" since this indicates what you do there: you drop mail into a box. Other locales should use whatever term makes sense these.

**Comment by sun-geo** [comment]
> > Therefore, I suggest to rename "Mailbox" to "Mailbox (mail service/collection)" and "Letter Box" to "Letter Box (personal/recipient)".
> 
> In the German localization on Transifex, you can translate the presets to say whatever you want. I've suggested this to you before several times.

Thats true, it seems there was an update already 7 days ago, see:

[letter box](https://www.transifex.com/openstreetmap/id-editor/translate/#de/$/179561369?q=text%3A'letter+box')
