### ISSUE TITLE
Error when run all

### ISSUE THREAD

**Issue by cuongnc5** [openstreetmap/iD#6942]
The latest version v2.15.5 i can not run all and start in local.
i always got warning
"Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
No name was provided for external module 'util' in output.globals – guessing 'util$1'
Creating a browser bundle that depends on Node.js built-in module ('util'). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins"
And when i start app, i got errorr
Uncaught ReferenceError: util$1 is not defined

please help me how to fix them.

**Comment by quincylvania** [comment]
@cuongnc5 Hi, did you run `npm install` before building? What system are you using?

**Comment by cuongnc5** [comment]
@quincylvania Thanks for your reply
I run "npm install" --> It work, no error
 "npm run all" --> i got the warning
"npm start" --> browser nothing. F12 --> i got error: Uncaught ReferenceError: util$1 is not defined
I tried run on both linux, window, Node js node-v10.16.3, npm version 6.4.1. I always got warning.
I try build and start master branch. It work very good

**Comment by cuongnc5** [comment]
@quincylvania  I got and build branch https://github.com/openstreetmap/iD/tree/2.15
It work normal

**Comment by quincylvania** [comment]
@cuongnc5 I'm glad you got it working. The `2.15` branch is relatively stable and targets use on openstreetmap.org. The `master` branch contains experimental features. You'll probably want to work with one of these.

The commit tagged `v2.15.5` is on the `release` branch and is a distribution of iD intended for embedding as a dependency, not for development.
