### ISSUE TITLE
Fail more gracefully when invalid OSM id passed in querystring

### ISSUE THREAD

**Issue by mvexel** [openstreetmap/iD#6943]
[Example](https://www.openstreetmap.org/edit?editor=id&way=547298880000001#map=19/-3.486086763304581/36.57259047031403&comment=overlapping%20edges%20in%20Tanzania%20%23maproulette&source=)

<img width="1188" alt="Screenshot 2019-10-15 15 35 37" src="https://user-images.githubusercontent.com/120452/66871716-7aa4d600-ef61-11e9-9039-3ac7fdc90938.png">

Obviously there is something wrong with the MapRoulette challenge that produced this link in the first place... But perhaps iD could fail more gracefully by just ignoring the invalid OSM id?

**Comment by quincylvania** [comment]
Hi @mvexel, I believe that's an issue with [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website/). The part before the `#` in the URL is handled by the container page which passes the parameters into iD.

**Comment by mvexel** [comment]
Thanks, @quincylvania for your response.
