### ISSUE TITLE
Add "add shared node" function

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6946]
For https://github.com/gravitystorm/openstreetmap-carto/issues/3929#issuecomment-541630441
I was looking for a simple clean way to add a shared node at the intersection of two lines (which do not have a shared node.)
![df4](https://user-images.githubusercontent.com/1230959/67080139-26029480-f1c7-11e9-81d7-9e4e495b7ad6.jpg)
However there currently is no simple way apparently.

**Comment by JamesKingdom** [comment]
There's no shortcut, but all you need to do is double click one of the ways to add an extra node and then drag that node onto the other line.
![](https://i.falcons.cloud/u/XB7DhsTL3u.gif)

**Comment by jidanni** [comment]
OK, but shouldn't there be a clean way, without distorting the geometry, even if just slightly?
