### ISSUE TITLE
Upgrade "station" tags correctly

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6948]
There are over 18,000 uses of the [`station`](https://wiki.openstreetmap.org/wiki/Key%3Astation) tag. iD should upgrade combinations like `railway=station` + `station=subway` to have `public_transport=station` + `subway=yes`. Also, iD recommends adding missing `station` tags to some presets. We could consider dropping this recommendation to better align with PTv2. iD wouldn't necessarily offer to remove the tags.

**Comment by Nakaner** [comment]
No, please do not upgrade this tag. `railway=station` (with and without `station=*`) is a valid tag. `railway=station/halt/tram_stop/platform` and `highway=bus_stop` have not been deprecated by PTv2. I would like to ask to discuss such significant decisions on a suitable mailing list first.

**Comment by quincylvania** [comment]
@Nakaner Perhaps I did not explain the issue clearly. This issue is about looking at `station=subway` and adding `subway=yes` instead of `train=yes`. `station=subway` would not be removed. Public transport is one of the only cases where iD supports both the old and new schemes simultaneously since the transition was never fully completed.
