### ISSUE TITLE
NSI tags applied verbatim when combining features

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6951]
When combining two features, one of which is associated with a preset based on name-suggestion-index, the combined feature prefers the NSI tags over any tags that were found on one of the two original features.

Steps to reproduce:

1. Draw a building area.
1. Draw a point and tag it with the “United States Post Office” preset.
1. Rename the point to “Smallville Post Office”, because most U.S. post offices are named after the towns they’re in.
1. Combine the point into the building area.

The combined feature is named “United States Post Office”. It should have retained the name “Smallville Post Office” given in step 3.

Alternative steps to reproduce:

1. Draw a hospital area.
1. Draw a point and tag it with the “VA Medical Center” preset.
1. Rename the point to “Metropolis VA Medical Center”.
1. Combine the point into the building area.

The combined feature is named “VA Medical Center” rather than “Metropolis VA Medical Center”.

Perhaps this is happening due to the same mechanism described in https://github.com/openstreetmap/iD/issues/6920#issuecomment-544296790. Would it help if NSI were more explicit about which brands can have individually named locations?

**Comment by bhousel** [comment]
Map POIs as points separately from building footprints and this isn't a problem.

**Comment by 1ec5** [comment]
This isn’t just about buildings. Did you see the alternative steps to reproduce, which is about hospital grounds (`amenity=hospital` areas)?

**Comment by bhousel** [comment]
I think that's #6561 
People want to be able to have the `name` tag not applied strictly for some brands.

**Comment by 1ec5** [comment]
Yes, a fix for #6561 would probably fix the merging issue “for free”. 👍
