### ISSUE TITLE
highway preset: "Allowed Access"

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6953]
What is the detailed meaning of "Allowed Access"-options which you can find at highway preset?
Is this what traffic signes surveyors tell when they walking along the street?
If so, please could you add this to addional information in a text, eg "Allowed Access, by traffic sign"

![allowed access](https://user-images.githubusercontent.com/47290585/67169759-bbf81400-f3ad-11e9-8c1d-7a70289928d1.png)

**Comment by bhousel** [comment]
> What is the detailed meaning of "Allowed Access"-options which you can find at highway preset?

Nobody really can say for sure, because every mapper will probably have their own opinion about what things mean - but the best descriptions of these tags are captured here:
https://wiki.openstreetmap.org/wiki/Key:access
