### ISSUE TITLE
tagging public_transport platform

### ISSUE THREAD

**Issue by martin-scholtes** [openstreetmap/iD#6960]
I would appreciate it if iD adhered to the proposal for public_transport version 2.
Specifically, it is about the addition of bus = yes, subway = yes, train = yes and other similar values to the stops and stops areas of the public transport.
In the proposal to find [here](https://wiki.openstreetmap.org/w/index.php?oldid=625726#Platform), such a procedure is not provided!
Only at the breakpoint, marked by public_transport = stop_position is the use of the above values provided and also necessary.

**Comment by quincylvania** [comment]
@martin-scholtes We try our best to adhere iD's tagging to the wiki, but sometimes we need to account for actual usage or practical considerations. Also the wiki can be confusing, contradictory, incomplete, and can change at any time.

In this case, how are PTv2 data consumers supposed to know the difference between a bus stop and a tram stop or between a train station and a ferry terminal without vehicle tags? And what harm does it cause to have them? Are you working on an OSM project where these tags are a problem?

**Comment by matkoniecz** [comment]
> In this case, how are PTv2 data consumers supposed to know the difference between a bus stop and a tram stop or between a train station and a ferry terminal without vehicle tags?

According to the proposal itself - by using standard tags like `highway=bus_stop`, `railway=tram_stop`. PTv2 is not a replacement for simple tagging (sometimes called PTv1), it was at least described as an optional extension that is not deprecating anything.

Later some mappers (or maybe a separate group?) started using vehicle tags also for stop positions, with some voices calling for deprecation of tags like `highway=bus_stop` with `public_transport`=`platform` + `bus=yes` style tagging.

Note 

> This proposal does not replace, deprecate or obsolete the already existing and well known tags. The usage of the proposed tags is recommended but not mandatory.

in the proposal

**Comment by quincylvania** [comment]
Again, iD errs on the side of practical usage. It's better to be able to get all bus infrastructure via `bus=yes` then needing to know about five different tags. Also, tags like `amenity=bus_station` collide with `amenity=ferry_terminal`. What if the same facility serves as both?

I think it was a tragic mistake that the old transit tags weren't fully deprecated and replaced by PTv2. iD tries to support both schemes but it can never please everyone because the tags are so inconsistently applied and understood.

**Comment by matkoniecz** [comment]
To clarify: I was not suggesting to remove ability to easily use vehicle tags. I was just answering how it was supposed to be done according to the PTv2 proposal.

**Comment by martin-scholtes** [comment]
> We try our best to adhere iD's tagging to the wiki, but sometimes we need to account for actual usage or practical considerations. Also the wiki can be confusing, contradictory, incomplete, and can change at any time.
>
If you already talk about iD tags, it seems to me like there would be his own soup.

>Also the wiki can be confusing, contradictory, incomplete, and can change at any time.
>
That the wiki is in constant change is normal. In order to still have guidelines, there is the proposal process.
>
>In this case, how are PTv2 data consumers supposed to know the difference between a bus stop and a tram stop or between a train station and a ferry terminal without vehicle tags? And what harm does it cause to have them? Are you working on an OSM project where these tags are a problem?
>
I am a simple mapper and not a data evaluator in OSM.
A distinction can be made by querying the existing public transport routes.
However, I think it is extremely wrong to additionally mark a platform with the tag's bus = yes and etc. Just to meet the evaluator that there can hold a bus.

Nowhere in the wiki is such an approach adequately documented. A way out would be to bind such a procedure by means of a proposal to the tags *=station. For example. public_transport=station, bus=yes

**Comment by quincylvania** [comment]
@martin-scholtes Thanks for your concern, but iD has been using this tagging for years without complaint from people who use the data. Useful data consumption is the end goal of OpenStreetMap and my job is to make sure the data coming out of iD is as useful as possible. Sometimes this means filling in gaps where wiki proposals fall short. There are countless tags in OSM that came into use without wiki proposals.

**Comment by matkoniecz** [comment]
> In order to still have guidelines, there is the proposal process.

Primary role of Wiki is to document how tags are actually used. Note that only minority of popular tags went through proposal process (try to find proposal for `highway=motorway`).

> Nowhere in the wiki is such an approach adequately documented.

Usually it means that wiki should be improved

**Comment by slhh** [comment]
The usage of vehicle type tags is limited to stop positions according to the PTv2 proposal, and there is a  good reason:
The vehicle type tags are partially reusing access keys (e.g. bus). When used on platforms, there is a potential ambiguity with the tagging of the access on the platform.

There isn't an ambiguity in case of stop positions, access tags doesn't really make sense there, or would have the same meaning as the vehicle type tags.
