### ISSUE TITLE
Don't put "terms" for unsearchable presets in derived data files

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6961]
I don't think unsearchable terms are ever used by iD so there's no point in asking people to translate them. I'm posting this issue first in case someone is actually using them.

**Comment by bhousel** [comment]
I think we stopped doing this a long time ago and there was an issue for it. Will look when I’m at my desk later.

**Comment by quincylvania** [comment]
Oh you're right. What I'm seeing is the terms appearing in `dist/en.json`. 

https://github.com/openstreetmap/iD/blob/7c846baa317e845bbd1dafd5e7cdd0140569e37a/dist/locales/en.json#L8802-L8805
