### ISSUE TITLE
barrier=lift_gate icon would be nice

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6968]
Currently it is using generic barrier icon. Maybe one from OSM Carto is acceptable? It is very simple, maybe too simple.

**Comment by bhousel** [comment]
Oh thanks for the reminder, @quincylvania added one to temaki so we can use that

**Comment by bhousel** [comment]
Looks like one of us did this already?   I see this in preview:

<img width="319" alt="Screenshot 2019-10-23 19 49 37" src="https://user-images.githubusercontent.com/38784/67442321-5171ee80-f5ce-11e9-8c6c-78c2b0c008d2.png">
