### ISSUE TITLE
Shortcuts for "Highlight unsaved edits" off in German

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6972]
On the EN version  https://preview.ideditor.com/master/#background=Mapbox&disable_features=boundaries,building_parts,buildings,power,rail&locale=en&map=20.06/52.47607/13.43960 I see …

![en shortcut Kopie](https://user-images.githubusercontent.com/111561/67622591-dbfb5d80-f81b-11e9-99f7-bb5fb4150a73.jpg)

- w = wireframe toggle
- g = highlight toggle

However, on the DE/GER version https://preview.ideditor.com/master/#background=Mapbox&disable_features=boundaries,building_parts,buildings,power,rail&locale=de&map=20.06/52.47607/13.43960 I see …

![german shortcut Kopie](https://user-images.githubusercontent.com/111561/67622602-f6cdd200-f81b-11e9-8f04-1ee7195d0966.jpg)

- g = wireframe
- g = highlight
- pressing w does not do anything
- pressing g does toggle the highlight

**Comment by manfredbrandl** [comment]
I have changed the last G to U in Transifex. Please test and close.

**Comment by quincylvania** [comment]
@manfredbrandl Tested and appears to be working. Thanks!!
