### ISSUE TITLE
Can I edit a custom map?

### ISSUE THREAD

**Issue by sosopop** [openstreetmap/iD#6973]
like this
https://leafletjs.com/examples/crs-simple/crs-simple.html

**Comment by mmd-osm** [comment]
Do you mean editing a map with a different projection?

**Comment by sosopop** [comment]
yes, like starmap

**Comment by bhousel** [comment]
Currently this editor is only for editing OpenStreetMap, or a fork of OpenStreetMap.  We're hoping to generalize the code to make it much more widely useful though!

see #6483 for more info
Also we recently talked about this at SOTM-US!   [here's a link to the talk and video](https://2019.stateofthemap.us/program/sat/id-v3.html)
