### ISSUE TITLE
Could not use the Square tool with Wireframe

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6974]
Of

> Fill Areas
> ￼
> No Fill (Wireframe)
> ￼
> Partial Fill
> ￼
> Full Fill

I could not use the Square tool with Wireframe. In fact there is no way to get to the right click menu.

Its shortcut (Q) still worked though.

**Comment by mmd-osm** [comment]
While in partial or full fill mode, it doesn't matter if you're clicking inside a building or on the building's way. Wireframe mode is a bit different, it's no longer possible to click inside the building - you need to right click, well, on the "wire" (or the building's way in this case). iD will highlight the object in red for you. This is a visual indication that you can use right click now.

![6974](https://user-images.githubusercontent.com/5842757/67641353-f1e34e00-f901-11e9-9dc0-0ee0b1ab637f.png)

**Comment by quincylvania** [comment]
@jidanni Yes, see @mmd-osm's answer. Since the fill is hidden in wireframe mode, you have to access the menu by right-clicking on the perimeter or pressing spacebar. A future version of iD will also show the Square tool in the toolbar when a feature is selected so you don't need to right-click.
