### ISSUE TITLE
Add sugestions based on Wikidata

### ISSUE THREAD

**Issue by ferdinand0101** [openstreetmap/iD#6975]
Since some tags like names ... can translate 1:1 into tagging it would seem usefull to suggest those as changes as well

**Comment by IgorEliezer** [comment]
> Can you elaborate? I'm not really sure what you're asking for, sorry..

If I may, I had similar need as to manually copying data from Wikidata to OSM. We were mapping this historical downtown which comprises ~250 heritage buildings: https://www.openstreetmap.org/relation/9963374

For instance, say I click on this building (https://www.openstreetmap.org/way/720714962) and add the wikidata Q65936743 (https://www.wikidata.org/wiki/Q65936743), the editor iD could "query" the wikidata page and suggest a few useful properties, such as name, name:<lang>, image, inception (i.e. start_date), etc. The mapper then must review and confirm the data.

**Comment by bhousel** [comment]
ok yeah #4382 and #5566 have some thoughts on this.
I'm going to close this in favor of #5566.

It would be nice to support a UI that lets people better sync up the data between OSM tags and Wikidata claims.
