### ISSUE TITLE
Rotating multiple points blanks OSM data layer

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6977]
Rotating a multiple selection of three points in close proximity causes the entire OSM data layer to go blank.

Steps to reproduce:

1. Go to https://preview.ideditor.com/master/#map=20.00/39.27909/-84.40139
1. Select all three picnic tables (nodes [6923427636](https://www.openstreetmap.org/node/6923427636), [6923427637](https://www.openstreetmap.org/node/6923427637), and [6923427638](https://www.openstreetmap.org/node/6923427638)).
1. Rotate this multiple selection.

Expected results: Two of the picnic tables rotate around the middle one.

Actual results: The entire OSM data layer goes blank. Sometimes undoing momentarily restores some of the data, but it quickly vanishes again when changing the selection. The data model seems to be unaffected; I’m able to save existing changes up to but not including the rotation even after things go haywire.

The same thing happens if I duplicate the three points and rotate those points, but not if I draw three new points from scratch and rotate them. So I think it may be specific to the coordinates of these points relative to each other.

Reproduces in both Safari and Firefox, in both 2.16.0 and master (as of defcbe7088bbaa165bc9cfe7c4896904c17ff7a2). In the Firefox console, I see a warning about `translate(NaN,NaN)` being [set on the `transform` attribute](https://github.com/d3/d3-selection/blob/8b260d2529bcf87a7d78a00a8395584ad0e052ff/src/selection/attr.js#L31).

**Comment by hackily** [comment]
Thanks for the detailed reproduction steps!

**Comment by bhousel** [comment]
done in #6979
