### ISSUE TITLE
New tagging for utility markers

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#6978]
Hi iD maintainers,

A new tagging has recently been reviewed for utility markers. It changes a bit established tagging for pipeline markers.
https://wiki.openstreetmap.org/wiki/Proposed_features/Utility_markers_proposal

It introduces two keys to describe more markers than previously possible, and is compatible with other usages (highway milestones and private property boundaries) if necessary.
https://wiki.openstreetmap.org/wiki/Key:marker
https://wiki.openstreetmap.org/wiki/Key:utility

Could you please change your presets accordingly :
* pipeline=marker, power=marker and cable=marker are no longer used
* Add marker=* + utility=* to a preset "Utility marker" with main values described on wiki

Warning should be raised when using those combinations
* pipeline=marker (deprecated)
* power=marker (deprecated)
* marker=* + cover=* (cover isn't encouraged with markers any more since marker=aerial exists)
* marker=* and voltage, pressure, diameter, substance are set incompatible and shouldn't be used on the same object

Thanks in advance

**Comment by quincylvania** [comment]
@flacombe Ooooo I really like the `utility` tag. I was wishing for something like that in #6848 to avoid having multiple tags for features of the same "form", like `power=pole` vs. `communication=pole`. Hopefully we can expand usage of this pattern.

I don't love `marker` as a top-level tag (maybe `man_made=marker`?) but it's still better than the old tagging, as per my previous comment.

**Comment by flacombe** [comment]
Hi @quincylvania 

You're welcome.
utility=* is may replace many specific tagging referring to the same concept: street_cabinet=*, power=tower/pole/portal, (theoretical telecom=pole) and so on...
This is long term thinking, moving dozen of million of existing features will be hard.
The most probable incoming move is street_cabinet=* to begin with.
But you're right, I'm highly puzzled by defining telecom=pole and no good solution for shared supports.

What man_made=marker will be about?
there are already historic=boundary_stone, railway=milestone, highway=milestone, boundary=marker. marker=* is compatible with all of them.
marker=* is enough to state there is a marker of various nature with a given shape/function, aren't you?

**Comment by quincylvania** [comment]
> What man_made=marker will be about?

> marker=* is enough to state there is a marker of various nature with a given shape/function, aren't you?

The problem is there's no way to define a marker without also defining its shape. iD mappers shouldn't be expected to always know and enter the shape. I'd like to add a "Utility Marker" preset but there aren't generic tags for this that I can see. `man_made=marker` would align with `man_made=street_cabinet`, `man_made=utility_pole`, and countless other primary/secondary tag patterns.

**Comment by flacombe** [comment]
> The problem is there's no way to define a marker without also defining its shape.

According to OSM's practices, you can still use marker=yes to state it's a marker without any precise function or shape.

I saw you propagate the utility=* key to street cabinet, which isn't a bad thing but note this hasn't been discussed for now.

**Comment by quincylvania** [comment]
> you can still use marker=yes to state it's a marker without any precise function or shape.

Generally the `thing=yes` pattern means that a feature _has_ a thing, while `*=thing` means the feature _is_ a thing. Like `bridge=yes` is used on roads while `man_made=bridge` is used for bridges themselves. A node with `marker=yes` doesn't look like it has a primary tag.

**Comment by flacombe** [comment]
Hello and sorry for this time took to think a bit about it.

You can't argue thing=yes is _generally_ the feature has a thing when building=yes is used on most buildings without any man_made=building tag.
Nevertheless I understand it would be semantically more convenient to have man_made=marker.
man_made=marker hasn't been reviewed, used nor documented so I don't think it should be included in a preset for now, but it's a topic we can discuss about.

Currently, iD should react on marker=* only, or use historic=boundary_stone, railway=milestone, highway=milestone, boundary=marker to make the layout more evocative

**Comment by quincylvania** [comment]
> You can't argue thing=yes is generally the feature has a thing when building=yes is used on most buildings without any man_made=building tag.

I was using "generally" in the sense that this is mostly, but not always true. `building` is an old tag and is special in a lot of ways.

I added the presets using `marker=*`, which I don't think is ideal but should work for now.

**Comment by flacombe** [comment]
Thank you Quincy

I'll keep in mind the comment about another tag to state it's a marker in cas of opportunity to add it
Be sure utility=* will be used on another concepts
