### ISSUE TITLE
Remove issue "natural=cape should be a standalone point based on its tags"

### ISSUE THREAD

**Issue by Janjko** [openstreetmap/iD#6982]
The wiki for natural=cape says that it should be a node as a part of the coastline. So this issue is in direct conflict with the wiki.

https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcape#How_to_map

**Comment by bhousel** [comment]
Looks like this wording was just added a year ago in [this change](https://wiki.openstreetmap.org/w/index.php?title=Tag:natural%3Dcape&oldid=1682773)

The [talk page](https://wiki.openstreetmap.org/wiki/Talk:Tag:natural%3Dcape) and [history](https://wiki.openstreetmap.org/w/index.php?title=Talk:Tag:natural%3Dcape&action=history) suggest that some disagreement going on about how to use this tag.

We can't really enforce the rule that a cape has to be a vertex along a coastline.  Can we leave it as-is?  It seems a lot more intuitive to me to let people just drop a point where they want the label for the cape to be.

**Comment by BjornRasmussen** [comment]
I think the best solution is to just add vertex as a valid geometry for capes and let people map as they see fit.

**Comment by bhousel** [comment]
> I think the best solution is to just add vertex as a valid geometry for capes and let people map as they see fit.

Good suggestion 👍   this is what I did..
