### ISSUE TITLE
Add better icon for communication tower

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6985]
checked in preview - still has icon that fits best for observation tower 

https://preview.ideditor.com/master/#background=Bing&disable_features=boundaries&map=16.97/59.77751/9.06189

**Comment by bhousel** [comment]
I made some new icons for these..

<img width="373" alt="Screenshot 2019-11-04 13 24 47" src="https://user-images.githubusercontent.com/38784/68146686-8d7a4d00-ff06-11e9-90ac-ca83825c3361.png">

**Comment by quincylvania** [comment]
@bhousel Love these! Now mappers (myself included) can finally figure out the difference between towers and masts.
