### ISSUE TITLE
Use blue for "waterway" group and waterfall to make them easier to recognize

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6986]
Currently icons for both of them are not really recognizable. I see that at leas some icons are using color, but I am not sure about strategy for doing this (I checked https://github.com/openstreetmap/iD/blob/master/data/presets/README.md ).

![Selection_003](https://user-images.githubusercontent.com/899988/67716721-a3e74c80-f9cc-11e9-87b1-2c22f1059d35.png)

**Comment by quincylvania** [comment]
@matkoniecz Good suggestion. I'm pretty sure there's a difference because the category icons with colors have them hardcoded into the SVG while most icons get their colors from CSS. Should be a quick fix though.

**Comment by jjiglesiasg** [comment]
Indeed it will be nice if the Waterways Folder is distinguised from the others using also the blue color in the main Icon...

**Comment by abhisheknaiidu** [comment]
@quincylvania Could you check pr #7256
