### ISSUE TITLE
Support for recreational node networks

### ISSUE THREAD

**Issue by pelderson** [openstreetmap/iD#6992]
I would like to raise the issue of more support in Id for recreational node networks. These live mainly in Netherlands and Belgium for cycling and walking/hiking, but the system is spreading to other modes of transport (boating, paddling, mtb, horse, inline skating) and to other countries, mainly Germany. The Dutch used network=rwn, rcn to mean "node network". Recenty, the additional tag network:type=node_network had been implemented. Now rXn no longer means node network. Only if the tag network:type=node_network is added, the element is part of a node network, and this holds for all geografical ranges (l ocal, r egional, n ational and i nternational) and all recreational transport modes as found in the network=XYn tag. 

Because of this move I think specific support (checks, defaults, templates, lookups) could now be implemented in editing tools for node network maintenance. It concerns nodes, route relations and network relations.

I am not familiar with the workings of Id, so I would like to hear if this is feasible and what I need to provide or do to bring this issue further!

**Comment by quincylvania** [comment]
@pelderson Thanks for the idea, though I'm not entirely sure what you'd like us to do on this. I can add a Network Type field to appropriate presets so mappers can view and set the `network:type` value. Have any tags been deprecated? Do any tags now imply other tags? Are there new validation rules or feature types?

**Comment by pelderson** [comment]
I'm not sure either! Presets sound ok. For a network node, it would be an a priori choice I think. For a route relation it would be an extra choice besides the network=... tag. 
No tags have been deprecated, no new features have been added, and no implications have been added. 
Maybe one thing: if a XYn_ref=* value is added to a node, it would make sense to offer the "network:type" key with the "node_network" value (it's the only value defined, for now.). But there are XYn_ref nodes which do not belong to a node network, so this cannot be automated. 

One other thing: in Nederland and Belgium the tag network=rYn was previously used to indicate node_network. In the Dutch template for a walking route relation the value for "Netwerksoort" is still given as "Regionaal (o.a. wandelknooppunten)". This should now just read "Regionaal".

**Comment by quincylvania** [comment]
@pelderson Okay, I added a preset for the network node features that will appear in the countries that have these. That plus the network type field should hopefully cover what you need.

> In the Dutch template for a walking route relation the value for "Netwerksoort" is still given as "Regionaal (o.a. wandelknooppunten)". This should now just read "Regionaal".

I changed this on our [translation platform](https://www.transifex.com/openstreetmap/id-editor/translate). Feel free to review and edit any translations that need work.

**Comment by pelderson** [comment]
Just for my information, why only in the countries that have node network features, and how do you know / choose which countries have them? Because the definitions are now global and the node network system is spreading.

**Comment by quincylvania** [comment]
> why only in the countries that have node network features

Because I'm from a country that doesn't really have these and it took me a lot of effort to figure out what a "node network" actually means. The name isn't self-explanatory. I think they're worth supporting in iD because they're real things, but users shouldn't have to worry about them if they're not mapping in a country where they exist.

> how do you know / choose which countries have them

I used the [map page](https://taginfo.openstreetmap.org/keys/?key=network%3Atype#map) for this key on taginfo and ran some overpass queries to get higher detail. Note that the uses in northeast Spain appear to be for healthcare networks so I didn't include those.

> the definitions are now global and the node network system is spreading.

I'm happy to expand the preset to relevant countries! The codes are listed [here](https://github.com/openstreetmap/iD/blob/master/data/presets/presets/network/type/node_network.json). Feel free to open PRs or issues for adding codes.

**Comment by grischard** [comment]
Today I learned that Luxembourg has these - a small hiking network in the very north of the country. Thank you :)
