### ISSUE TITLE
aerialway=station causes warning about outdated tags

### ISSUE THREAD

**Issue by DFyson** [openstreetmap/iD#6994]
Tagging a building with aerialway=station in iD gives a warning about outdated tags and the option to update them by replacing the `aerialway=station` and `building=yes` tags with `aerialway=yes` and `public_transport=station` tags.
However this is not reflected in the wiki for [Aerialway](https://wiki.openstreetmap.org/wiki/Aerialway), [key:aerialway](https://wiki.openstreetmap.org/wiki/Key:aerialway) and [aerialway=station](https://wiki.openstreetmap.org/wiki/Tag:aerialway%3Dstation) where there is no mention of this new tagging scheme.

**Comment by quincylvania** [comment]
@DFyson This is a tricky case. iD supports `public_transport=*` + `whatever_transport_type=yes` for PTv2 tagging. We try to support the old public transport tags redundantly, but in this case `aerialway=yes` and `aerilway=station` collide so we can only support the new tagging.

**Comment by quincylvania** [comment]
@DFyson Okay, I made it so iD prefers `aerialway=station` instead of `aerialway=yes` since the former has much more usage and OSM as a whole doesn't seem too concerned about moving on from PTv1 tags.

**Comment by DFyson** [comment]
Thanks! I was not aware of this. I see it mentioned in [public transport](https://wiki.openstreetmap.org/wiki/Public_transport#Cable_cars). I don't mind which tagging scheme is used, so long as it's consistent as described by the wiki. So maybe the real issue is the wiki needs updating.
