### ISSUE TITLE
Allow setting offset of satellite imagery when calling iD

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/iD#6999]
It can be useful being able to set the offset of a certain satellite imagery from outside of iD. E.g. Tasking Manager might want to set this on a per project base and when calling iD the imagery could be set accordingly (see related [Tasking Manager issue](https://github.com/hotosm/tasking-manager/issues/1948) by @Geocruizer.

**Comment by bhousel** [comment]
@xamanu iD does support an `offset=east,north` url parameter.. is it working?
https://github.com/openstreetmap/iD/blob/master/API.md#url-parameters

**Comment by xamanu** [comment]
oh, nice. didn't know about it. Many thanks! Will close here. We are going to test it and in case there are problems open another issue.

**Comment by bhousel** [comment]
Sounds good!
