### ISSUE TITLE
Validator incorrectly suggests to remove primary `amenity=fuel`

### ISSUE THREAD

**Issue by Bibi56** [openstreetmap/iD#7001]
If I edit an [amenity=fuel named Carrefour (brand=Carrefour)](https://www.openstreetmap.org/edit?editor=id&node=6832642791), id suggests to use standard tags for the brand.

What I expect according to this message is that iD adds the brand* tags.
Only if I click on i I see what it will do:

_All features of the same brand should be tagged the same way._
_Suggested updates:_
_- amenity=fuel_
_--_
Making the amenity useless: it may considered as added value only if the value is strictly negative...

In France it's common practice to name the fuel station like the supermarket it is related too. 
Anyway an amenity tag is more important than a brand tag.

At least it should suggest to remove the name and brand tags so doing pretty much the opposite!
It would be still rather wrong but ways better.

Changing the nature of an object is something we do shouldn't do in the background but explicitly ask for: "*Are you sure you you want to change this Gas Station into a useless point?*" would be the right question you should ask for...
According to Overpass, in France we have currently 226 amenity=fuel, 272 shop=supermarket, and 7 shop=convenience named Carrefour.
All of them named Carrefour.
Of course it's pretty much the same for other brands.

**Comment by bhousel** [comment]
I agree that it shouldn't remove `amenity=fuel` here, and this this is a real bug that needs fixing.

Please assume good intent - we are not trying to create "vandalism".  I will dig into the code and see what is causing this.

**Comment by Bibi56** [comment]
> Please assume good intent - we are not trying to create "vandalism". 

I do. But vandalism is the correct word when you deteriorate the database. Well "Vandalism is _intentionally_ ignoring the consensus norms of the OpenStreetMap community." and no I don't think it was intentional.

**Comment by bhousel** [comment]
> Well "Vandalism is _intentionally_ ignoring the consensus norms of the OpenStreetMap community." and no I don't think it was intentional.

I accept your apology.

**Comment by Bibi56** [comment]
I've another similar case, let me know if you prefer another ticket but I think it's safe to rename the ticket to `Validator incorrectly suggests to remove primary tag`.
As the solution may be slightly different it may make sense.

For a [ferry terminal](https://www.openstreetmap.org/way/53715582):

_- building=yes_
_--_
_+ ferry=yes_
_+ public_transport=station_

building is correct and shouldn't be removed. 
According to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity=ferry%20terminal?uselang=en), we should remove the ferry related tags to the way and create a node on the centroid to held the ferry related tags. Or not to propose the modification on ways.

**Comment by bhousel** [comment]
The issue with the Carrefour fuel is happening because the `amenity=fuel` tag is [missing from name-suggestion-index](https://github.com/osmlab/name-suggestion-index/blob/017d6df069621d86bbf7bd5c35db587a195f2a55/brands/amenity/fuel.json#L472-L477).  I'll add it now, and release an update soon.

**Comment by Bibi56** [comment]
Thanks for the explanation, that should solve this issue.
For other possible missing brands, it shouldn't remove the primary tag without proper warning anyway.
That's a second, IMHO needed, check.

**Comment by bhousel** [comment]
> For other possible missing brands, it shouldn't remove the primary tag without proper warning anyway. That's a second, IMHO needed, check.

I will have to check what happens after this next update.  The Carrefour node that you linked to has 2 primary tags:  `amenity=fuel` but also `shop=gas`.  The validator might suggest to remove the `shop=gas`, which I would tend to agree with.  That tag is really [for stores selling bottled gas](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dgas).   

That node also has `vending=fuel` and `vending_machine=fuel` which are [really for tagging individual pumps](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dfuel).  The primary tag in that case should be `amenity=vending_machine`.   I think it's wrong to put the gas pump tags on the gas station node, but I doubt the validator would complain about these tags.

**Comment by Bibi56** [comment]
For `amenity=fuel` and `shop=gas`, that's normal in France: in most supermarkets, at the fuel station you can also buy bottled gas: if you want bottled gas you will ask and pay at the same place you could pay if you use the pump as simple pump and not as vending machine. 
On this [picture](https://www.mapillary.com/app/?lat=47.98453230707128&lng=-4.110062834527525&z=17&focus=photo&pKey=yRvmKRpsGPoeRR34glFSpA), you see the bottles just under "Caisse" on the right.
The left lines "24/24" i.e. 24/7 are `vending_machine=fuel` the right ones "Caisse" (Checkout) are for payment without vending machine (when the checkout is open) and for bottled gas.

> That node also has vending=fuel and vending_machine=fuel which are really for tagging individual pumps
agreed. I came to this node only to add a reference ;-).

**Comment by doublah** [comment]
Just noticed this for removing the building=yes tag for seemingly no reason for this bus station: https://www.openstreetmap.org/way/140147695
![firefox_rW4MyURoIH](https://user-images.githubusercontent.com/11699874/68066396-2ce4e780-fd2f-11e9-9aa2-78b338a9be81.png)

**Comment by Bibi56** [comment]
> Just noticed

Not only for "seemingly no reason", but IMHO, any tag removal, even for "good reasons", shouldn't occur behind the scene; this information should always be present. For 2 reasons at least:
- for check (and therefore be able to select want we want to change, all selected by default): here we would just uncheck `building=yes` - this information could be stored by iD to check later what is by default not accepted. N.B.: quite similar to the edit and the false positive buttons in Osmose.
- for learn. iD is one editor, not the only one, and knowing the tagging schema helps to contribute better and faster.

**Comment by quincylvania** [comment]
The original issue was resolved in 8c67d7e8605256b080e81b7c61a0736f6aa7ee2b.

If needed, you can make separate issues for the other presets in question. Please keep discussion scoped and on-topic in this repo. Thanks!
