### ISSUE TITLE
Validator: Warning for overlapping highways

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7004]
See title and screen capture below. The north part of the service road is on top of a residential road. At that area this short north part of the service road is uses the same position of a way part from the  residential road. I think these kind of situations should be prevent or solved. Therefore, this could lead to a warning message from iD-Editor validator. If you want to see an implemented similar function, the current validator of the JOSM editor is telling such cases.

By the way, I assume for these kind of issues, there will be not an easy function for automated solving it. But I would just be happy, if there is at least a warning display. Or maybe ask for adding fixme tags "overlapping highway" to the involved ways.

![overlapping highways](https://user-images.githubusercontent.com/47290585/68062930-af5caf80-fd0d-11e9-87bf-917ba82faf1f.gif)

**Comment by quincylvania** [comment]
@sun-geo Good idea, I think this is #5977.

**Comment by sun-geo** [comment]
Yes - exactly, didn't run a deep search, thanks for linking!
