### ISSUE TITLE
more addable fields for the amnity=telephone preset

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#7010]
Hello,
I think it's a good idea to add some **more addable fields** (I think they don't need to be fields which are directly present but those which you can add, like you just can do with "indoor=yes" etc.)
to the **amenity=telephone** preset.

In my mind predominantly important are:
- sms=yes/no field
- video=yes/no field
- internet_access=terminal/wlan/no field
- **ref=*** field for telephones, e. g. in germany, they having a ref and _not_ a phone=* number you can call to.

What do you think?

See also https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtelephone

**Comment by quincylvania** [comment]
@Lukas458 Sounds fine, thanks for the suggestion 👍
