### ISSUE TITLE
Changing way to motorway link changes existing oneway=no to oneway=yes

### ISSUE THREAD

**Issue by Prince-Kassad** [openstreetmap/iD#7012]
How to reproduce:

* Select any road that is not already a motorway link
* Add oneway=no if not already present
* From the top menu select Major roads -> Motorway link

Expected result:

iD changes the tag to highway=motorway_link but leaves oneway=no alone

What happens instead:

iD automatically changes oneway=no to oneway=yes without notifying the user in any way about it. This can potentially break existing routing.

It is okay to add oneway=yes if no oneway tag is present yet, but changing oneway=no to oneway=yes automatically is highly problematic.

**Comment by bhousel** [comment]
Adding an explicit `oneway=yes` to `highway=motorway_link` was requested in #2555, and I still agree that it's the right thing to do.  

You said:
> iD automatically changes oneway=no to oneway=yes without notifying the user in any way about it. This can potentially break existing routing.

I think this is a bit silly - iD renders oneway markers, so you can't say that we aren't notifying the user in any way.  It's pretty easy to see that the road gets switched to oneway.  We are optimizing for the case where users are drawing new motorway links.  The situation where a user finds an existing road with an explicit `oneway=no` and wants to turn it into a bidirectional motorway link has got to be pretty rare.  And for that user to miss that there are suddenly oneway markers on there - I dunno, I feel like this is a made-up issue that doesn't really happen in practice.

Also, that you and @nakaner both opened almost identical issues about motorway links on a Sunday within 10 minutes of each other, I kind of feel like you guys are trolling me again.  Please knock it off and close your issues if this is just some prank.

**Comment by Prince-Kassad** [comment]
Talk about civility. 

I only found out about this from a forum post - https://forum.openstreetmap.org/viewtopic.php?id=67889 - where someone reported this specific bug. Sometimes bugs end up being reported there but not in the proper channels (i. e. here) because people don't speak enough English or are unfamiliar with Github/don't have an account here. Everything else is pure chance.

**Comment by BjornRasmussen** [comment]
This does seem pretty bad, actually.  Even if it's rare, it still doesn't make sense that iD changes these types of tags like this.  This has been brought up before where iD adds/ removes building tags inappropriately.

I think that a good general solution to this, and other issues with iD messing up tags when the preset changes, would be to separate the tags related to a preset into two groups: preset defining tags (like `highway=motorway_link`), and tags that are added only if they aren't already set to something else.  
Any thoughts?

**Comment by bhousel** [comment]
per #7013 we won't add the `oneway=yes` anymore, so this issue can be closed.
