### ISSUE TITLE
Drop default to oneway=yes for highway=motorway_link

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/iD#7013]
When adding a `highway=motorway_link`, iD automatically adds `oneway=yes`. In addition, it complains about missing `oneway=yes` if `oneway=*` is missing.

While there might be a default `oneway` value for motorways in OSM, there is no such for their link roads. There are too many motorway links which are (and should be) mapped as one way for both directions because they have no physical separation between forward and backward lanes.

The current oneway handling seems to be introduced after issue #4727. I agree that adding explicit tagging in this single case might be helpful but assuming defaults should happen with caution.

Therefore, I would like to ask
* to remove this default from the tagging preset and
* to remove the default operation from the validation rule and changing the wording to something like "explicitly adding oneway=yes/no is recommended for the sake of clarity"

The default of the preset is not needed any more since iD has validation rules warning its users.

EDIT: Changed reference to correct ticket.

**Comment by bhousel** [comment]
I think #2555 adds the explicit `oneway=yes` (per wiki direction) and #4727 changed the message so that a missing `oneway` tag doesn't display the message "Assumed to be yes" anymore (also I guess per wiki direction).

> The default of the preset is not needed any more since iD has validation rules warning its users.

Yes, I think defaulting the tag is still important.  We don't want to let users add stuff and then use the validator to nag them that it's incomplete.  That's just mean.

**Comment by dieterdreist** [comment]
generally, defaults in OpenStreetMap mean fallback if not explicitly stated. According to user feedback iD currently even changes oneway=no to yes when you apply the motorway link preset, is this intentional?

**Comment by bhousel** [comment]
> iD currently even changes oneway=no to yes when you apply the motorway link preset, is this intentional?

Yes, again _please_ see #2555
It even says on there "Pointed out by @dieterdreist." so it sounds like you asked for this feature and we added it for you over 4 years ago.

> IMHO it would be better to ask the mapper when she applies the preset: is it a oneway road? yes / no / dunno

iD doesn't ask users questions like this.. It would get very tedious to get asked for every road whether you wanted it to be oneway or not.

Anyway I will remove the default `oneway=yes` for motorway links.. It doesn't look like we do this for any of the other `_link` roads, so it seems weird to add it for these ones.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 4 nov 2019, alle ore 01:24, Bryan Housel <notifications@github.com> ha scritto:
> 
> Yes, again please see #2555
> It even says on there "Pointed out by @dieterdreist." so it sounds like you asked for this feature and we added it for you over 4 years ago.
> 


no, from what I read there it seems I pointed out that explicit oneway-tagging is common for motorway links, but surely I didn’t say that 4% error rate is fine (i.e. tagging them all as oneway=yes).

> IMHO it would be better to ask the mapper when she applies the preset: is it a oneway road? yes / no / dunno
> 
> iD doesn't ask users questions like this.. It would get very tedious to get asked for every road whether you wanted it to be oneway or not.
> 


not for every road, for every motorway link...
