### ISSUE TITLE
retitle man_made=bridge from "Bridge" to "Bridge area" or "Bridge outline"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7015]
Currently searching for bridge is a bit confusing, I think that more explicit help here would help.

**Comment by bhousel** [comment]
Thanks @matkoniecz, good suggestion..
I renamed these presets:
* "Bridge" -> "Bridge Area"
* "Tunnel" -> "Tunnel Area"
* "Road Surface" -> "Road Area"

**Comment by quincylvania** [comment]
I also did this for waterways-as-areas since they're also mapped differently than their line counterparts.
