### ISSUE TITLE
Update.

### ISSUE THREAD

**Issue by alirezap2** [openstreetmap/iD#7017]
Hi ! I like using it and it's really interesting, but there's one fact that you need to update the map because as you see for ex in this link of gmap: 
[https://www.google.com/maps/@35.2626327,33.9007405,542m/data=!3m1!1e3](url) 
the facilities of this place are totally different. like the pools-buildings-etc....

Thanks a lot 
![bug2](https://user-images.githubusercontent.com/38366463/68165257-9a7b5880-ff67-11e9-8b52-d280c7ece82e.JPG)

![bug1](https://user-images.githubusercontent.com/38366463/68165256-9a7b5880-ff67-11e9-8c03-3eff5d0993d2.JPG)

**Comment by bhousel** [comment]
Thanks for checking out the OpenStreetMap project @alirezap2  👋 

In the iD editor you can try out the different available imagery by opening the Background pane. 
![imagery compare](https://user-images.githubusercontent.com/38784/68173624-92142500-ff49-11e9-8be9-13c3ac09392f.gif)

We can't use the Google imagery as a source, but there are at least 6 others to choose from that are licensed openly for us to trace from, and they will all have different age and quality.   Each imagery provider has their own schedule for updates and we don't have control over this, but it is overall improving all the time.

Hope this is helpful!
