### ISSUE TITLE
Locator Overlay needs updated data

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#7025]
The Mapbox powered Locator Overlay `openstreetmap.map-inh76ba2` used by default at low zooms, looks like it hasn't seen any data updates in at least two years?

I couldn't find any further details, is it using mapbox-streets tilesets? Perhaps it's using Mapbox Streets v6 or lower which are no longer receiving data updates from OSM?

original report https://lists.openstreetmap.org/pipermail/talk-nz/2019/000166.html

**Comment by andrewharvey** [comment]
moved to https://github.com/osmlab/editor-layer-index/issues/692

**Comment by quincylvania** [comment]
@andrewharvey Sounds good, thanks for tracking this.

**Comment by quincylvania** [comment]
The overlay endpoint was recently updated in https://github.com/osmlab/editor-layer-index/pull/840 by @mikelmaron. While this change isn't specific to iD, most users won't know that, so it's worth promoting in the next release.
