### ISSUE TITLE
iD gets corrupted every time I edit from my phone

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#7034]
Every time I use my Google pixel 2 with chrome to edit osm with iD, it gets corrupted in the middle of drawing something.  This is usually just after undoing an incorrectly drawn point.
See this screen recording (near the end):

https://drive.google.com/file/d/1RjbsUiuta4uPqLpFaB0FydPYQcZWQzb5/view?usp=drivesdk

**Comment by quincylvania** [comment]
@BjornRasmussen Interesting, thanks for reporting and for the recording. I'm sure iD v3 still has lots of lurking bugs like this we need to work out.

**Comment by quincylvania** [comment]
Closing this since we're still working on the v3 features and I expect bugs like this to come and go. Once we hit a true beta we'll hunt down stuff like this.
