### ISSUE TITLE
add support for payment:others=no

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#7035]
Hello,
I think it might be a good propose for having directly under the field where people can specify a shop's/restaurant's etc. **accepted** payment methods
a "check" field where people can set a stick for "the list of accepted payments is complete". This would then set the **payment:others=no**-tag. This is for marking that all accepted payments are listed. The tag's usage on taginfo is here: https://taginfo.openstreetmap.org/keys/payment%3Aothers#values

**Comment by Lukas458** [comment]
and the wiki-related line is here: https://wiki.openstreetmap.org/wiki/Key:payment#Showing_that_the_list_of_accepted_payments_is_complete

**Comment by quincylvania** [comment]
We could possibly do this but we'd need to make a custom field element.

**Comment by Lukas458** [comment]
I see. This seems to be a bit difficult as I read from your post?

**Comment by quincylvania** [comment]
> This seems to be a bit difficult as I read from your post?

@Lukas458 Yes, we don't have any other fields like this right now that we could copy.

**Comment by bhousel** [comment]
I don't think we can do this easily with the multivalued fields.
