### ISSUE TITLE
shop=chocolate icon is quite poor

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7051]
At least for me it doe not look like a chocolate at all or even suggest chocolate.

See https://github.com/openstreetmap/iD/blob/master/data/presets/presets/shop/chocolate.json

Screen from test shop added in preview version - https://preview.ideditor.com/master/#background=Bing&disable_features=boundaries&map=18.04/41.30248/-77.06886

![Selection_001](https://user-images.githubusercontent.com/899988/69093226-55b6ed80-0a4e-11ea-8132-da4f608896cd.png)

**Comment by SilentSpike** [comment]
I guess it's like a Hershey's kiss, but would agree that a better icon could be used

**Comment by bhousel** [comment]
Well the good news is I only spent like 5 minutes on it.

**Comment by tas50** [comment]
Seemed pretty spot on to me, but I doubt it has the same impact for those outside the US.

**Comment by matkoniecz** [comment]
> Seemed pretty spot on to me, but I doubt it has the same impact for those outside the US.

Yes, it is probably cultural thing. Hershey's kiss is not something that is familiar to me.

> Well the good news is I only spent like 5 minutes on drawing it.

And reason for why this issue ended created is because I am looking for a `shop=chocolate` icon for JOSM https://josm.openstreetmap.de/ticket/18338 as part of shop tagging overview and failed so far.
