### ISSUE TITLE
Add "packstation" as generic alternative name for Parcel Pickup/Dropoff locker

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7052]
Note that DHL may be trying to keep "packstation" as their brand, rather than a generic term for such object.

But for me it seems that "packstation" (or Polish "paczkomat") should be treated rather than as a generic term.

See also an equivalent Vespucci issue - https://github.com/MarcusWolschon/osmeditor4android/issues/1045

**Comment by matkoniecz** [comment]
Curently searching "packstation" gives "DHL Packstation" but not generic "Parcel Pickup/Dropoff locker"

For example, searching "packstation" while in Poland gives no useful matches.

**Comment by quincylvania** [comment]
@matkoniecz Thanks for the suggestion. It doesn't really matter if it's a generic term, we can put in whatever words people might think to search for.
