### ISSUE TITLE
"agrcultural_machinry" tag on "shop=agrarian"

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7053]
Hi,

there is a duplicate/misspelled tag under the agrarian tag.
There is both "agricultural_machinery" as an option in the dropdown menu, but also "agrcultural_machinry" 

Cheers

**Comment by quincylvania** [comment]
@thibaultmol Welcome, thanks for reporting! iD populates those suggestion values automatically based on [top usage from taginfo](https://taginfo.openstreetmap.org/keys/agrarian#values). The best way to fix this is to update all 100 uses of the misspelled tag across OSM, but in the meantime I added a deprecation that blacklists that value from appearing 👍

**Comment by thibaultmol** [comment]
@quincylvania I've made a changeset to correct the 10 misspelled tags (seems like it's only 10 according to taginfo https://taginfo.openstreetmap.org/tags/agrarian=agrcultural_machinry#overview ) https://www.openstreetmap.org/changeset/77295116
Does anything else need to happen now or is that it?

**Comment by quincylvania** [comment]
@thibaultmol Thanks! That'll fix the issue. I'll leave the deprecation in iD in case there's some buggy tool or confused mapper that continues to insert these.
