### ISSUE TITLE
Support wmts imagery endpoints

### ISSUE THREAD

**Issue by grischard** [openstreetmap/iD#7056]
https://josm.openstreetmap.de/wiki/ImageryCompare shows that JOSM has about 100 wmts sources that ELI doesn't have. The current hack is to hardcode parameters in ELI URLs, like `https://geoservices.buergernetz.bz.it/geoserver/gwc/service/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=P_BZ_OF_2011_EPSG3857&STYLE=default&TILEMATRIXSET=GoogleMapsCompatible&TILEMATRIX=GoogleMapsCompatible%3A{zoom}&TILEROW={y}&TILECOL={x}&FORMAT=image%2Fjpeg`.

See also #4828.

**Comment by bhousel** [comment]
let's just use #4828 for this
