### ISSUE TITLE
area=yes moves to new node while extract function

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7057]
Thanks again for the convenient extract function, see #6203

I noticed, that the `area=yes` tag in the current version v2.16 will move to the new created node while running the extract function.
Example test object:
https://www.openstreetmap.org/way/140524172

Is this behavior intended?

**Comment by quincylvania** [comment]
@sun-geo This was definitely not intended. Thanks for reporting, let us know if you find anything else like this.

**Comment by sun-geo** [comment]
Thanks - for instant code modification :-)
