### ISSUE TITLE
Only show worldwide backgrounds at low zooms

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7062]
Right now, all backgrounds with coverage that overlaps the shown map extent are always included in the backgrounds list. This means that at low zooms when the entire Earth is visible, all possible backgrounds are listed. This is unhelpful at best and overwhelming at worst. Instead, iD should only show backgrounds with global coverage when zoomed far out.

**Comment by pnorman** [comment]
One way to do this would be to only show imagery that fully covers the viewport

**Comment by quincylvania** [comment]
> One way to do this would be to only show imagery that fully covers the viewport

Yep, or to hide sources that cover less than some small percentage of the viewport. For now I just cut off all non-global sources at zoom levels lower than 6. Let's see how far that gets us.
