### ISSUE TITLE
Allow us to change the max editing zoom level

### ISSUE THREAD

**Issue by IgorEliezer** [openstreetmap/iD#7063]
Currently you can edit the map from z24 to z16. I would like to be able to change it to, for instance, z18 or z19.

### The reason
There's a benefit in zooming out above the editing zoom level cap: I can pan the map quite fast without the risk of grabbing or moving an object by accident, since the map editing is disabled and the screen loads no objects.

The current issue is that I have to zoom out from z21 or 20 to z16, pan, and then zoom in several times. This can be sluggish in well mapped areas, such as city centres or downtowns. It would be very handy If I could change the zoom level cap to z18 or z19, perhaps with increments of z0.25, the process of zooming-out-pan-zooming-in would be faster.

**Comment by quincylvania** [comment]
@IgorEliezer Thanks for posting! I think instead of having users manage this manually, iD can and should adjust limits automatically. This is #1520.
