### ISSUE TITLE
Make Mapillary id's hyperlinks

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7064]
When viewing an object that has the mapillary tag; It would be nice if the actual Mapillary ID that's set would be a hyperlink instead of just text. 
If you want to view the image, you can just click on it

**Comment by quincylvania** [comment]
@thibaultmol Thanks for the idea. We should probably have a Mapillary field that links to the site and possibly displays the photo or opens it in the photo viewer. I'd suggest this for OpenStreetCam and Bing Streetside too but people don't seem to be linking those with tags right now.

Related: #6196

**Comment by thibaultmol** [comment]
Making tags with :wikidata at the end also be hyperlinks would be nice. Should I make a new issue for that? @quincylvania

**Comment by quincylvania** [comment]
@thibaultmol Well we wouldn't be making the tags hyperlinks but instead adding fields that have a link button. There are some Wikidata fields already like for `species:wikidata`.

**Comment by thibaultmol** [comment]
That's what I meant, yeah

**Comment by sun-geo** [comment]
Good idea, 

Little bit offtopic, would such extra link-buttons also make sense/possible for keys:
https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons and
https://wiki.openstreetmap.org/wiki/Key:image
?

**Comment by quincylvania** [comment]
@sun-geo We could link `wikimedia_commons`, but people can link anywhere in `image` so we shouldn't link to those for the same reasons we don't provide links to `website` values.

> and maybe i would like the position of the link-button in the raw-editor ("all tags" area) in the tag-line left of remove- and info-button?

Hmm we can just do this with fields so I'd say let's not put tag-specific functionality under the "All tags" section.

**Comment by thibaultmol** [comment]
Is there a reason btw why only species:wikidata gets a link. 
Why can't we just have all tags that end with :wikidata be hyperlinked?
Like right now in iD it gives the ui for species:wikidata but not for taxon:wikidata.
Even though the wikidata id i'm trying to link isn't the species, it's technically the cultivar. So just going with the general taxon:wikidata tag instead

**Comment by quincylvania** [comment]
Okay, I added basic fields for the `mapillary` and `wikimedia_commons` tags that link to those sites. In the future we could make these more dynamic for #6196.

> Why can't we just have all tags that end with :wikidata be hyperlinked?

@thibaultmol There's no mechanism to show fields for arbitrary tags with a format like that, so all Wikidata fields must be added manually. Only some of the most common ones are supported right now.

**Comment by doublah** [comment]
Wonder if we could auto-add `wikimedia_commons` for `wikidata` tags like we do with `wikipedia` tags. @quincylvania 

e.g. for https://www.openstreetmap.org/way/369161987 we could use the [`wikidata=Q173882`](https://www.wikidata.org/wiki/Q173882) to add the commons sitelink of [`wikimedia_commons=St Paul's Cathedral`](https://commons.wikimedia.org/wiki/St_Paul%27s_Cathedral)
