### ISSUE TITLE
man_made=water_tap preset

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#7066]
This tag seems to be less popular than drinking_water, however a lot of places would tend to have water taps that serve technical-use/non-drinkable water.
An icon that does not cross over with am=drinking_water might be tricky

**Comment by quincylvania** [comment]
@tohaklim Thanks for posting. I'm okay with using the same icon for now, though eventually we could use a tap with a knob but no water glass.

I also added a field for `drinking_water` so mappers can specify potability.
