### ISSUE TITLE
stop making issues to remplace local language by english language wikipedia page

### ISSUE THREAD

**Issue by bikepunk** [openstreetmap/iD#7067]
The wiki specifies
"a link to a single Wikipedia article, which should be to the article in the primary language for the subject."
https://wiki.openstreetmap.org/wiki/Key:wikipedia

surprisingly iD reports local langages wikipedia pages as issues
![Screenshot from 2019-11-25 20-23-08](https://user-images.githubusercontent.com/14958221/69571051-7688c100-0fc1-11ea-8d16-0fd6f61beed7.png)

according to the wiki iD shall not report wikipedia pages in local language as issues

**Comment by bhousel** [comment]
Oh these are the `brand:wikipedia` tags.. They come from [Name Suggestion Index](https://github.com/osmlab/name-suggestion-index), and volunteers there have decided which `brand:wikipedia` tag is the best one to use for each brand.  

Wikipedia pages are not particularly stable, but I agree that it's better to use the French Wikipedia page for a French bank.   I opened https://github.com/osmlab/name-suggestion-index/issues/3400 there to switch the `brand:wikipedia` tag for LCL to use the French Wikipedia page.

`brand:wikidata` is a much more useful tag, as it is a stable identifier that can link you much more information about the brand, and all of the wikipedia pages in all the languages that are available.


> according to the wiki iD shall not report wikipedia pages in local language as issues

pretty sure it doesn't say that, but ok.

**Comment by bikepunk** [comment]
oh, ok !
 I didn't know about the Name Suggestion Idex.
I'll report other issues there then.
thanks for the super quick reply !
