### ISSUE TITLE
Unable to get custom TMS map background (Strava heatmap) to work

### ISSUE THREAD

**Issue by kylebarron** [openstreetmap/iD#7070]
After seeing that OSM is [allowed to trace from Strava Heatmap data](https://www.reddit.com/r/openstreetmap/comments/e1vbll/we_got_permission_to_trace_from_strava/), I've been trying to set up those tiles as a custom layer in iD. The URL works when setting `{z}/{x}/{y}`, but nothing is displayed with `{z}/{x}/{-y}` or `{z}/{x}/{ty}`.

**Example**:

Set to `{z}/{x}/{y}`:
![image](https://user-images.githubusercontent.com/15164633/69677196-9ec6fd00-105f-11ea-863f-9ddde66f0081.png)

Bing map:
![image](https://user-images.githubusercontent.com/15164633/69677225-aab2bf00-105f-11ea-96a2-2b0c00be6e51.png)

Set to `{z}/{x}/{-y}` or `{z}/{x}/{ty}`:
![image](https://user-images.githubusercontent.com/15164633/69677239-b43c2700-105f-11ea-9ce6-05c401defae6.png)

**To reproduce:**

To use the high-res authenticated heatmap tiles, I'm following [these instructions](https://help.openstreetmap.org/questions/62803/strava-heatmap-no-longer-useful-for-osm-mappers-anything-we-can-do?page=1&focusedAnswerId=62842#62842).

```
https://heatmap-external-{switch:a,b,c}.strava.com/tiles-auth/run/bluered/{zoom}/{x}/{y}.png?Key-Pair-Id=.....&Policy=.....&Signature=.....
```
with OAuth values of mine pasted in that I found from my logged-in Strava cookies.

The same URL works in JOSM set to TMS style.

**Comment by quincylvania** [comment]
@kylebarron Hmm this is a weird problem that appears to have something to do with offsets. This is the heatmap at the same zoom level and approximate position at Strava's site:

![Screen Shot 2019-12-02 at 11 15 53 AM](https://user-images.githubusercontent.com/2046746/69975764-cac9fe80-14f5-11ea-8077-e0614249c49b.png)

And as a custom layer in iD:

![Screen Shot 2019-12-02 at 11 16 01 AM](https://user-images.githubusercontent.com/2046746/69975769-cef61c00-14f5-11ea-8a44-b867a2b9094d.png)

It's fetching and displaying the tiles at the wrong zoom level. I think #6198 could address this. I'm not sure how tools like JOSM account for this automatically.

**Comment by bhousel** [comment]
> It's fetching and displaying the tiles at the wrong zoom level.

Some tiled sources use 512px tiles - maybe it just needs a workaround this?  (This update-imagery script checks the things we get from [editor-layer-index](https://github.com/osmlab/editor-layer-index) and makes a few adjustments).

https://github.com/openstreetmap/iD/blob/7a5576953cfe18073884bc883f94c508f9d6172d/data/update_imagery.js#L96-L102

**Comment by quincylvania** [comment]
> Some tiled sources use 512px tiles - maybe it just needs a workaround this?

Oh okay it's definitely this. I tried hardcoding the tile size to 512 and the layer displayed correctly.

Seems like we might need some UI to set the size.

**Comment by kylebarron** [comment]
Awesome! How long does it usually take for updates to make it to production?

**Comment by quincylvania** [comment]
@kylebarron We usually do a release per month or so. We're due for one, so maybe this week or next!
