### ISSUE TITLE
Tests fail in `2.x` branch

### ISSUE THREAD

**Issue by chapko** [openstreetmap/iD#7072]
**Node version:** v8.16.2 (installed via `nvm`)
**NPM version:** 6.4.1
**OS**: macOS catalina 10.15.1

Failing tests:
```
...

  1844 passing (49s)
  16 pending
  4 failing

  1) iD.Map
       #zoomIn
         increments zoom:
     Uncaught TypeError: undefined is not a constructor (evaluating 'ArrayBuffer.isView(x)') (file:///Users/eugene/workspace/iD/dist/iD.js:9720)


  2) iD.Map
       #zoomOut
         decrements zoom:
     Uncaught TypeError: undefined is not a constructor (evaluating 'ArrayBuffer.isView(x)') (file:///Users/eugene/workspace/iD/dist/iD.js:9720)


  3) iD.Map
       "before each" hook:
     Uncaught AssertionError: expected 2 to be close to 5 +/- 0.000001 (file:///Users/eugene/workspace/iD/node_modules/chai/chai.js:9449)


  4) iD.Map
       #centerEase
         sets center:
     Uncaught TypeError: undefined is not a constructor (evaluating 'ArrayBuffer.isView(x)') (file:///Users/eugene/workspace/iD/dist/iD.js:9720)

...
```

Full tests output: https://gist.github.com/chapko/3998710d31f6529b3db689efa46a7bf9

Steps to reproduce:
```
git clone git@github.com:openstreetmap/iD.git
cd iD
git checkout 2.x
npm install
npm test
```

---

I suspect it is caused by incompatible dependencies, which can be fixed by checking in the working package-lock.json file.

**Comment by bhousel** [comment]
Thanks @chapko!
Can you share your package-lock file in a gist too?

We haven't checked this file in because I'd prefer for the tests to break when there are incompatible dependencies (rather than having them seem to work although there is a problem).

**Comment by chapko** [comment]
@bhousel here it is: https://gist.github.com/chapko/84933c9eff707992eb69c31c2bb7ea51

**Comment by bhousel** [comment]
Thanks @chapko - it turns out that a recent update to D3's number interpolator https://github.com/d3/d3-interpolate/pull/77 introduced a check for ArrayBuffers, and the support for these is incomplete in PhantomJS (where our tests run).  

I added a workaround to our spec-helpers file in b9f41bb
