### ISSUE TITLE
Download of osmChange file blocked on osm.org

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7073]
<img width="386" alt="Screen Shot 2019-11-27 at 10 06 26 AM" src="https://user-images.githubusercontent.com/2046746/69734807-a210c600-10fd-11ea-9354-8da2de6a566d.png">

The download button doesn't currently work on modern browsers when iD is embedded in an iframe (e.g. on osm.org).

Firefox 70 throws this warning:

> Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.

and this error:

> Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://www.openstreetmap.org/fa1ef581-08cb-3a4f-977e-53ab3b38d8e7 (“frame-src”).

While Safari 13 throws a similar error:

> Refused to load blob:https://www.openstreetmap.org/f106047b-c9d2-4024-94b2-d87e0678022d because it does not appear in the frame-src directive of the Content Security Policy.

**Comment by quincylvania** [comment]
Investigating further, this is probably an issue with https://github.com/openstreetmap/openstreetmap-website.

**Comment by boothym** [comment]
I noticed this as well, although you can right click to copy the url and paste into a new tab to then save. I did this today, however when I tried to load it into JOSM, it did not find any data in the file. This has worked in the past - do you know why it would not work now?

**Comment by sun-geo** [comment]
The ability to save the changeset as an osmChange file is really a nice feature and i use it from time to time.

Btw. it seems working for google chome & chromium browsers under win7 64b... (i can confirm, it's not working for firefox)

**Comment by mmd-osm** [comment]
Upstream issue https://github.com/openstreetmap/openstreetmap-website/issues/2582

**Comment by mmd-osm** [comment]
Upstream issue has been resolved...

**Comment by quincylvania** [comment]
@mmd-osm Terrific, thanks for the info.
