### ISSUE TITLE
[Feature] Show a warning when trying to merge address nodes with building in Denmark

### ISSUE THREAD

**Issue by MegaArthur** [openstreetmap/iD#7081]
"Danish community does not approve of merging the imported address nodes with buildings". https://wiki.openstreetmap.org/wiki/Addresses#Denmark

Would be nice if iD showed a warning when someone tries to merge an address node with a building in Denmark

**Comment by BjornRasmussen** [comment]
I'm not sure about this.  I feel like the real problem is that the address bot doesn't recognize areas with addresses.
Anyway, I think that making a warning just for addresses in Denmark would be difficult and of limited benefit.

**Comment by quincylvania** [comment]
@MegaArthur Thanks for the idea. Do you know if this is causing actual problems? Not sure if we need to worry about this if the merging is uncommon or is cleaned up automatically by the bot.

**Comment by quincylvania** [comment]
Lacking further information, I'm closing this as low impact.
