### ISSUE TITLE
Allow limiting fields to specific countries/regions

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7085]
There's the potential for certain advanced fields that only apply to particular countries such as a business's VAT number (see https://github.com/openstreetmap/iD/issues/6880#issuecomment-535122656) or [GNIS ID](https://wiki.openstreetmap.org/wiki/Key%3Agnis%3Afeature_id). Now that we've done #6941, looking up country codes is relatively free. Like presets, we could have `countryCodes` and `notCountryCodes` properties for fields.

**Comment by bhousel** [comment]
Oh hey! You beat me to this..  
I'm working on a general way of representing these for other projects too (name-suggestion-index, osm-community-index, whatever we decide to do with editor-layer-index), and I'll have this working in the [location-conflation](https://github.com/ideditor/location-conflation) project in the next few days.

👉 Would you consider a schema like:
```js
locations: {
  include: [Array],
  exclude: [Array]
}
```
The arrays may contain anything that [country-coder](https://github.com/ideditor/country-coder) recognizes, but I'm also supporting _other stuff_ too (like a `example.geojson` filename).  This gives us the flexibility to support non-country-coded things like "Scotland" or "French-speaking Canada", which we need for some communities in OCI, or some brand extents in NSI.

**Comment by quincylvania** [comment]
@bhousel Sure, it'd be great to have more flexibility and take advantage of that project 👍

We can also switch the preset properties, though that will be a breaking change.
