### ISSUE TITLE
Add GNIS Feature ID field

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7086]
Similar to Wikidata, GNIS is a geodatabase for US feature names. Over a million features have a [`gnis:feature_id`](https://wiki.openstreetmap.org/wiki/Key:gnis:feature_id) tag. We should add a field for it limited to the US (see #7085) with a link out to the feature's [stable URL](https://geonames.usgs.gov/apex/f?p=138:10:27205236604342::NO:::). This will help mappers verify information, especially since most GNIS features were imported and may require review and adjustment.

**Comment by 1ec5** [comment]
[This page](https://wiki.openstreetmap.org/wiki/Key:gnis:feature_id) documents five “synonyms” of `gnis:feature_id`, most notably `gnis:id`. Should iD ignore those keys, somehow display the same field for different keys, or offer to migrate them to the most popular one (`gnis:feature_id`)?

**Comment by quincylvania** [comment]
@1ec5 Good catch. I think we should try letting iD's validator offer to upgrade the alternatives to `gnis:feature_id`. Though I wish someone would do this with a mass edit to keep iD mappers from seeing 400,000 new tagging issues for some imported tags they probably don't care about.

**Comment by quincylvania** [comment]
> I think we should try letting iD's validator offer to upgrade the alternatives to `gnis:feature_id`

On second thought this sounds like the kind of thing that could cause undue controversy so I'm going to let it sit.
