### ISSUE TITLE
raw-editor: plus button functionality

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7087]
The raw-editor is running quite stable and has a good usability so far. I noticed a minor, most likely, unwanted behavior.

I'm not sure if this is already reported or if it has some relation which case #7027, if so please close it. Using following setup:
- Firefox 70.0.1 - 64bit (win7).
- iD-v2.16 (edit2 happens also using iD v3 preview)
- (edit1 happens also using Chrome browser v78.0.3904.108 (offical build) (64-Bit))

The plus (+) button of the "All tags"-section doesn't adds a new bottom line (at the expected position), when there were before some deletions, e.g. of two other lines. A new line appears, but mostly as a fresh **second** last line (sometimes, so far i remember, even somewhere in the middle of the entire line stack, but can't reproduce this for the moment). And the cursor is active in the last line which stores some existing old parameters.

It's sometimes a bit confusing, when you are on rush editing flow...

This behavior should be relatively easy to be reproduced.

![raw-editor lines moved after deletion](https://user-images.githubusercontent.com/47290585/70102447-7d09df00-1638-11ea-9e62-7ece84b1e95a.gif)

**Comment by quincylvania** [comment]
@sun-geo I've seen this bug too. Thanks for the detailed explanation, per usual.

**Comment by sun-geo** [comment]
Great, thx for instant change.
Seems working well already for v3 preview :-)
