### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::8080

### ISSUE THREAD

**Issue by abhisheknaiidu** [openstreetmap/iD#7088]
While running npm start or sudo npm start command, getting this as an error

![id](https://user-images.githubusercontent.com/55599878/70175196-45fd0180-16fc-11ea-9e5c-c00a7000db0f.png)

**Comment by quincylvania** [comment]
Hello and welcome @abhisheknaiidu 👋

Looks like you must have another process already using port 8080. Check out [this post](https://stackoverflow.com/questions/9898372/how-to-fix-error-listen-eaddrinuse-while-using-nodejs) for a possible fix.
