### ISSUE TITLE
Ghost menu items after undoing 'create bridge'

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#7090]
iD v3 d415f36

Steps to reproduce:
1. Have highway over waterway
2. Select highway and choose 'add bridge' option in Crossing Way error box
2a. Should have three ways selected; the three sections of the road
3. <kbd>CTRL</kbd>+<kbd>Z</kbd>, don't deselect
4. Should now have menu that matches picture. iD thinks the three roads are still there and menu is for editing multiple objects

![image](https://user-images.githubusercontent.com/25139386/70199241-33c09a80-16df-11ea-91ee-17bac11035f8.png)

**Comment by quincylvania** [comment]
@rivermont Thanks, this also happens on the `2.x` branch so we should try to fix it before release.

**Comment by quincylvania** [comment]
Fixed for v2 in 9aa27f68c3dc7b9d6bd08bf1f3fbf58546459aa5 and for v3 in #7103.
