### ISSUE TITLE
Warning from autoprefixer

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/iD#7091]
We recently upgraded the version of [autoprefixer](https://github.com/postcss/autoprefixer) that we're using for the web site and I noticed it has started issuing this warning:

```
autoprefixer: /home/tom/src/osm/rails/app/assets/stylesheets/id.css:4777:5: end value has mixed support, consider using flex-end instead
```
It comes from the included iD CSS and refers to this [line](https://github.com/openstreetmap/iD/blob/master/css/80_app.css#L2510) and [caniuse](https://caniuse.com/#feat=mdn-css_properties_align-items_flex_context_start_end) does seem to confirm that while it works in Firefox it doesn't work in Chrome for example.

**Comment by quincylvania** [comment]
@tomhughes Thanks for letting us know, I fixed this for the next release.
