### ISSUE TITLE
Brands in the name field are not geofenced

### ISSUE THREAD

**Issue by jnicho02** [openstreetmap/iD#7092]
Brands from the Name Suggestion Index (NSI) https://nsi.guide/index.html?k=amenity&v=fast_food are displayed when typing a brand name into the feature type search of iD. The records can be tagged as being for a specific country and are geofenced in the editor. However, the name field does not geofence it. 

e.g. I am in the UK and if typing 'Extreme Pita', a Canadian/US brand name
<img width="379" alt="Screenshot 2019-12-06 at 12 30 48 pm" src="https://user-images.githubusercontent.com/83251/70323385-8bb4e980-1824-11ea-950d-2dc1d4bffb37.png">

After selecting 'Fast food', in the name field....
<img width="355" alt="Screenshot 2019-12-06 at 12 30 14 pm" src="https://user-images.githubusercontent.com/83251/70323402-953e5180-1824-11ea-8db4-956decfd0513.png">

**Comment by quincylvania** [comment]
Hi @jnicho02 👋

The country-aware name suggestion issue is #6479 and has been fixed for the next release 👍

For the preset search, it looks like it's working correctly but there's a data issue. Extreme Pizza isn't limited by country right now:

https://github.com/osmlab/name-suggestion-index/blob/5cfcbbc119190f0eb58699d681ab80eb1b2fc20e/brands/amenity/fast_food.json#L839-L849
