### ISSUE TITLE
Add demolished:building as "recently demolished building"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7098]
This way 

(1) recently demolished buildings remapped to `demolished:building` will be more effective at protecting from recreation based on outdated aerial images

![Selection_002](https://user-images.githubusercontent.com/899988/70390185-0dde1300-19c9-11ea-9487-cc6e972e9184.png)

![8274](https://user-images.githubusercontent.com/899988/70390167-e5561900-19c8-11ea-8567-ca2f2a38acaa.jpg)

https://www.openstreetmap.org/changeset/78109471

(2) People will not start mapping unwanted historical data like long gone buildings (just "demolished building" may invite people to add buildings that are at no risk from remapping).

For bonus points: do no present it in search for new objects, just during changing building feature and for existing objects.

**Comment by quincylvania** [comment]
@matkoniecz Thanks for the idea. I added the preset and made these render as dashed areas.

> For bonus points: do no present it in search for new objects, just during changing building feature and for existing objects.

We don't have a way to do this right now so I just made the whole preset unsearchable. I'm worried that if the iD shows this preset in search then disaster mappers will start using using it.
