### ISSUE TITLE
Don't add tag swimming_pool=... on swimming pool

### ISSUE THREAD

**Issue by alphensebezorger** [openstreetmap/iD#7100]
Currently the editor offers a field "Type" when editing a swimming pool, which results in a tag swimming_pool=.... According to the wiki, this key is only used indicate the presence of a swimming pool in another facility (swimming_pool=yes), not on objects tagged leisure=swimming_pool. I feel adding this key should be avoided, possibly by removing the "Type" field alltogether.

**Comment by 1ec5** [comment]
Thanks for pointing out this ambiguity – I added `swimming_pool` to the index of [homonymous keys](https://wiki.openstreetmap.org/wiki/Homonymous_keys) for awareness.

**Comment by bhousel** [comment]
yes I remember that when we did #5301 the tag was already being used this way..
