### ISSUE TITLE
Multilingual labels (Arabic + Latin alphabets)

### ISSUE THREAD

**Issue by mapmeld** [openstreetmap/iD#7104]
This is my mistake (as it relates to prior work on #6679 and before). I noticed during a HOT task, that in Chrome-based browsers, road labels such as "Avenue Franchet d'Esperey شارع فرانشيت دسبيراي" currently appear with Latin text reversed

![Screen Shot 2019-12-10 at 1 56 45 PM](https://user-images.githubusercontent.com/643918/70559619-09466580-1b55-11ea-8e2f-0b2584c1d947.png)

https://www.openstreetmap.org/way/28785429

I will try to fix this later in the week, while staying compatible with Latin and Arabic numerals

**Comment by quincylvania** [comment]
@mapmeld Thanks for noticing this! And for your work in this area, as always.
