### ISSUE TITLE
Add connectivity relation preset

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#7105]
There are more about 1000 relations (https://taginfo.openstreetmap.org/tags/type=connectivity) with `type=connectivity`.  A simple preset for these relations would make editing them easier for inexperienced users.

The preset would have a single field, much like the turn restriction preset, labeled `Connectivity`.  It would allow for plain text to be entered.

See https://wiki.openstreetmap.org/wiki/Relation:connectivity for details.

**Comment by 1ec5** [comment]
This would also have the benefit of making them distinguishable in the relation list under the raw tag editor. Right now it just says “Relation”.
