### ISSUE TITLE
ImproveOSM public service URL changes

### ISSUE THREAD

**Issue by beataj-telenav** [openstreetmap/iD#7110]
The ImproveOSM projects were transitioned from [Telenav to Grab](http://blog.improveosm.org/en/2019/12/openstreetcam-and-improveosm-are-moving-to-grab/). As a result of this transition the ImproveOSM publicly available services URLs has been changed as follows:

* Missing Geometry Service: https://grab.community.improve-osm.org/missingGeoService/
* Direction of Flow Service: https://grab.community.improve-osm.org/directionOfFlowService/
* Turn Restriction Service: https://grab.community.improve-osm.org/turnRestrictionService/

The old service URLs that are currently used by the iD tool were redirected to the new ones and will work for a couple of weeks. Can you schedule to change the ImproveOSM service URLs used by the iD tool?
 
Thank you.

**Comment by quincylvania** [comment]
@beataj-telenav Thanks for keeping iD in mind! I'll make the change for the next release (before the end of the month). Good luck with the transition.

**Comment by beataj-telenav** [comment]
@quincylvania : Thank you :)
