### ISSUE TITLE
Show entities of all three geometry types when searching OSM ID without prefix

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7112]
OSM creates entity IDs in three namespaces, one each for `node`, `way`, and `relation`. This means there are three features for each numeric ID, e.g. `7238389`. Users can search for features by ID in iD, but they need to prefix them with the type letter, e.g. `n7238389`. However, even experienced OSMers may not know this. I know when I first started in OSM it wasn't obvious to me. See also https://github.com/openstreetmap/iD/issues/5214#issuecomment-563137165.

<img width="397" alt="Screen Shot 2019-12-12 at 12 19 47 PM" src="https://user-images.githubusercontent.com/2046746/70734191-c235ad00-1cd9-11ea-9008-0e01f7d9fa97.png">

We should just show all three possibilities when users search for a number without a prefix.

**Comment by maro-21** [comment]
Great!
I didn't know it was possible to search by a node number. When I tried to type a node ID, it didn't work. This will really help :)
