### ISSUE TITLE
Can't always reach bottom of Choose parent relations group

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7115]
Sometimes one cannot always scroll down to see the full parent relations choices. They just don't fit.
![32444-6](https://user-images.githubusercontent.com/1230959/70762159-9de5d900-1d8a-11ea-858f-3c897aafec5a.jpg)
One needs a few CTRL+--- to finally see all of them.

**Comment by sun-geo** [comment]
I agree, noticed same behavior many times, when working on public_transport or other route relations.

**Comment by bhousel** [comment]
Ah yeah, this was #5280, which I fixed in c5ad8ad by adding a bunch of extra space to the bottom.
I guess it regressed..

**Comment by quincylvania** [comment]
@bhousel Thanks for the link. Turns out I made a CSS typo that nullified that style [here](https://github.com/openstreetmap/iD/commit/0781b70f382b06706dcceb8ed1537069451b7a10#diff-698ee7529ca50c8359982b3c174bddf2R2573).
