### ISSUE TITLE
"Zoom in to edit" not always appropriate for long boundary operations

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7116]
Let's say the Sahara Desert countries X and Y have agreed to realign their long border.

Rather than handing out Shapefiles, they instead hold a joint news conference right there with both kings and a team of OSM mappers with the iD editor open. And them pointing at which mountain contains the border corners etc. 

This would be a simple mapping task if iD didn't assume all operations are done at city street magnification.
The moment one tries to deal with larger objects (boundaries) it becomes, though still possible, quite a task, as one needs to zoom in each time to grab a node...

**Comment by jidanni** [comment]
Sure, allowing editing at lesser zoom levels might overwhelm the computer with data... However often we are talking about rural areas with little data to worry about.

**Comment by jidanni** [comment]
Yes, allowing editing at lower zoom levels might easily allow people to accidentally grab the entire Korean DMZ and paste it into the ocean.
But still there should be some override button somewhere to allow the user to grab things at lower zoom levels.

**Comment by jidanni** [comment]
In fact the entire line we are working with,
![4638-7](https://user-images.githubusercontent.com/1230959/70763547-69c0e700-1d8f-11ea-8950-d2f663f0b32d.jpg)
disappears entirely from the screen, at just one lower zoom level,
![8418-8](https://user-images.githubusercontent.com/1230959/70763557-72b1b880-1d8f-11ea-9d92-f6707ea2212b.jpg)
Perhaps iD could be kind enough to at least leave the item we selected still on the screen, while we zoom out to find its next node, etc. Thanks.

**Comment by jidanni** [comment]
Zoom level 16, background: none.
![2158-9](https://user-images.githubusercontent.com/1230959/70763911-b78a1f00-1d90-11ea-8800-6a1032e1e2f2.jpg)
Zoom level 15, background: none.
![2377-10](https://user-images.githubusercontent.com/1230959/70763933-d38dc080-1d90-11ea-9ddf-56ea635b0c1a.jpg)
As you see, it is all black...

**Comment by jidanni** [comment]
And... "this feature cannot be deleted because not enough of it is visible."
![25330-14](https://user-images.githubusercontent.com/1230959/70764290-1603cd00-1d92-11ea-8dac-af44b75963dc.jpg)
But when the user tries to see more of it (by zooming out) the feature disappears!

Workaround: split the line into smaller segments, and delete them one by one.

**Comment by quincylvania** [comment]
@jidanni This is covered by #1520 and #5001. Large, consequential geometry edits like you described are outside the current scope of iD and should be addressed in an editor like JOSM.
