### ISSUE TITLE
Administrative Boundary preset not overriding Boundary preset

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7118]
Starting on this screen, attempt to use the "^" button to hopefully increment Admin Level 1,2,3,4...
![10126-15](https://user-images.githubusercontent.com/1230959/70768686-4868f680-1da1-11ea-9d29-64e1fd857f5c.jpg)

But before our finger can move, suddenly "1" is "pre selected for us!"
![32717-16](https://user-images.githubusercontent.com/1230959/70768717-659dc500-1da1-11ea-9336-38af0f5ede17.jpg)

The only remedy now is to fix it at the bottom.

**Comment by sun-geo** [comment]
You talking about the up/down button functionality for an empty field similar to compared to this talk?:
https://github.com/openstreetmap/iD/issues/5844

**Comment by quincylvania** [comment]
@jidanni This is a bug and we'll fix it. But note that saying unprompted that this is "stuffed down your throat" is inexcusably rude. You've been repeatedly asked to use a professional tone in line with this project and have repeatedly failed to do so. This would be grounds for blocking you from this repository if we had the ability to do so.

**Comment by jidanni** [comment]
I should have just said "suddenly chosen automatically".
