### ISSUE TITLE
Prevent user from adding duplicate relations

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7120]
Perhaps prevent the user from accidentally adding duplicate relations.
![21135-0](https://user-images.githubusercontent.com/1230959/70843681-41111e00-1e71-11ea-9696-197b185d87a1.jpg)
At least during the Save Edit processing.

**Comment by jidanni** [comment]
In fact after we add the first, it should be removed from the hints offered when making the second.

**Comment by jidanni** [comment]
Here if I type an "A" the same item as just entered above is suggested.
![14696-1](https://user-images.githubusercontent.com/1230959/70844006-c72f6380-1e75-11ea-9752-ded775660602.jpg)
(I don't know what the rest of the list was as it was off the screen due to other bug.)

**Comment by quincylvania** [comment]
@jidanni Some types of relations can have the same feature as a member multiple times, such as a road that a bus route traverses twice. Boundaries don't work like that, but I'm not sure if this is a big enough problem to spend time addressing.

**Comment by jidanni** [comment]
Here's some more that I'm not sure how I made.
![7882-1](https://user-images.githubusercontent.com/1230959/71323650-5e4c8900-2510-11ea-8bb2-05659fd47d9c.jpg)
Clicking the "工" also showed the same two at top.
Only upon saving did they finally become resolved into one.

**Comment by quincylvania** [comment]
@jidanni Your screenshot shows duplicate tags, not duplicate relations. Let us know if you can reproduce that problem.

**Comment by jidanni** [comment]
(OK trying again today with the tags part, I found it very hard to get a duplicate tag tip. So the tags part is working OK.)

**Comment by quincylvania** [comment]
Closing in favor of #7648.
