### ISSUE TITLE
Warn when (re)using a river in an international boundary relation

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7127]
Perhaps warn when (re)using a river in an international boundary relation.
(See e.g., [Paradox of the Moving Boundary: Legal Heredity of River Accretion and Avulsion](http://www.water-alternatives.org/index.php/allabs/137-a4-2-4/file),)
or even on state/territory etc. borders. Also when using trails too perhaps. Telling the user "unless you are sure that they define the border as in treaties, etc.

However one might say that this is an area that goes beyond the job of the editing program. If so just close this bug.

**Comment by quincylvania** [comment]
@jidanni Yes, there can be issues with this pattern but I'd rather leave the decision up to mappers than make iD have throw a warning anywhere.
