### ISSUE TITLE
Indicate units of measurement for elevation, height

### ISSUE THREAD

**Issue by cbeddow** [openstreetmap/iD#7129]
Related issues: https://github.com/openstreetmap/iD/issues/929, https://github.com/openstreetmap/iD/issues/5658

I know that when I add a `peak` for example I should add it in meters. I am in the US looking at USGS maps of Montana and dropping peak points, so first I convert on my own from feet to meters. It'd be good to have a reminder in the OSM iD interface for `elevation (meters)` so users don't just enter feet. But I think as some mention, having like a dropdown option for the units would be cool so when the user submits the changeset the units are taken into account, and the meters altitude is still submitted to OSM even if they want to use feet for input.

**Comment by 1ec5** [comment]
Also related: #3614.

**Comment by quincylvania** [comment]
Closing this in favor of #3614. We should solve this for the general case so all fields that take length measurement values can have unit dropdowns.
