### ISSUE TITLE
Outsourcing presets

### ISSUE THREAD

**Issue by ValorNaram** [openstreetmap/iD#7130]
Hey,

wouldn't it be wonderful to outsource https://github.com/openstreetmap/iD/tree/master/data/presets to its own repository so other projects like osmmybiz or onosm can benefit from them?

**Comment by bhousel** [comment]
Yea this is #2656  - we've made a few attempts at this but it never happened.  Lots of history on that ticket and in linked discussions.  It probably will happen eventually, but it's not a priority for the iD team right now.

For now, having the presets tightly coupled with the iD code lets us make changes to them easily (such as adding field types or changing the way documentation works, or adding validation).  Other projects can and do still use them by depending on the generated files in `dist/`.

**Comment by bhousel** [comment]
#6483 is a good issue too, to get a sense of where we are heading with iD development.
(also see [our talk](https://2019.stateofthemap.us/program/sat/id-v3.html) from SOTM-US 2019).

Me closing this issue doesn't mean that we don't want to extract the presets - it's more that we want to modularize everything a lot more including the presets, and this will take a while and we're working on it slowly.
