### ISSUE TITLE
Hide Denomination field if religion=none

### ISSUE THREAD

**Issue by lukf** [openstreetmap/iD#7135]
When tagging a School Grounds object, defining a “religion” value always triggers iD to show a “Denomination” field. Instead, Denomination should not be shown if religion=none.

**Comment by quincylvania** [comment]
@lukf This sounds fine, but I don't see this tag documented anywhere despite having [>1200 uses](https://taginfo.openstreetmap.org/tags/religion=none). It'd be great if you or someone could add info about it to the [`Key:religion`](https://wiki.openstreetmap.org/wiki/Key:religion) wiki page.
