### ISSUE TITLE
City of Turku background maps

### ISSUE THREAD

**Issue by ilmaisin** [openstreetmap/iD#7136]
City of Turku has released it's map data in CC-BY 4.0 with an [OSM waiver](http://dev.turku.fi/openstreetmap-lupa.pdf). The iD editor could include some maps from City of Turku as background maps.

Specifically, I would like to have two maps from [this feed](https://opaskartta.turku.fi/TeklaOGCWeb/WMS.ashx):

- "Turun asemakaava" (Zoning plan of Turku)
- "Turun maastokartta" (Terrain map of Turku).

**Comment by quincylvania** [comment]
Sounds great, @ilmaisin. iD gets its imagery from the [editor-layer-index](https://github.com/osmlab/editor-layer-index/issues) so you'll need to open this issue over there. Thanks!
