### ISSUE TITLE
Consider renaming "Bunker" to "Golf bunker"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7138]
At least for me "Military bunker" is something that would be a match for "Bunker".

There is a separate icon but this way it would be harder to make this kind of mistake.

**Comment by bhousel** [comment]
I see this:
<img width="300" alt="Screenshot 2019-12-19 10 02 49" src="https://user-images.githubusercontent.com/38784/71183908-ccf6c180-2246-11ea-8c33-c6dbbe843fdf.png">

It seems pretty ok to me.. Are you seeing something different?

**Comment by matkoniecz** [comment]
On https://preview.ideditor.com/master/#background=Bing&disable_features=boundaries I see 

![Selection_006](https://user-images.githubusercontent.com/899988/71208428-42937980-22a9-11ea-9e7f-d7ce4108d961.png)

**Comment by quincylvania** [comment]
Turns out this was translated to "Bunker" in the British English localization. I changed it to "Golf Bunker".

https://www.transifex.com/openstreetmap/id-editor/translate/#en_GB/presets/19250911?q=text%3Atrap
