### ISSUE TITLE
Consider using military bunker icon from OSM Carto

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7139]
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/bunker.svg - CC0 icon

Specific idea for #7068 (I can make more such issues if it is useful)

**Comment by quincylvania** [comment]
@matkoniecz Thanks for the suggestion. I ended up drawing a new icon based on the OSM-carto one.

<img width="372" alt="Screen Shot 2019-12-19 at 5 09 14 PM" src="https://user-images.githubusercontent.com/2046746/71213726-4e1f7a00-2282-11ea-8f0a-06930cdc0842.png">
