### ISSUE TITLE
standalone query builder

### ISSUE THREAD

**Issue by stefanocudini** [openstreetmap/iD#7140]
hi 
I would like to create an generic UI component to built a overpass query that is user friendly.

how can I separately and independently use the part of iD that deals with building overpass queries? Is there a possibility that we can separate as a independ component?
Only to build a overpassquery without.. geometry editing and others..
I would like to create one using Bootstrap or other as a base
![Screenshot at 2019-12-19 17-51-43](https://user-images.githubusercontent.com/47107/71192285-46fb6a80-2288-11ea-8e70-82ce5a241bef.png)

**Comment by quincylvania** [comment]
Hi @stefanocudini, iD doesn't actually build nor run overpass queries. Tag suggestion in iD's combo dropdowns are returned from the [TagInfo API](https://wiki.openstreetmap.org/wiki/Taginfo/API). See [this file](https://github.com/openstreetmap/iD/blob/2.x/modules/services/taginfo.js) for our implementation.

I'd try looking into the [Overpass Turbo project](https://github.com/tyrasd/overpass-turbo) which has a wizard for building queries. Hope that helps, good luck!

**Comment by stefanocudini** [comment]
@quincylvania  thank you so much for the tips!
I apologize for writing an issue here, but iD's tag suggestion is the closest thing to what I had in mind

**Comment by quincylvania** [comment]
@stefanocudini Happy to help! I know it can be hard at first to figure out how all the pieces fit together and what questions to ask. You can also check out our Slack group where some overpass experts hang out: https://slack.openstreetmap.us/
