### ISSUE TITLE
potential validation natural/landuse forest/wood

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7141]
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dwood
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dforest

`natural=forest` => maybe ask for `natural=wood` or `landuse=forest `
`landuse=wood` => maybe ask for `natural=wood` or` landuse=forest `

**Comment by quincylvania** [comment]
@sun-geo Hmm we can't know what the correct tags are for these features. And iD intentionally doesn't have a mechanism right now for users to decide between different upgrade paths. There are fewer than 1000 of these mistags, so I'd recommend a MapRoulette campaign or something similar to manually review them all.

**Comment by sun-geo** [comment]
Thanks for checking.
Is okay.
