### ISSUE TITLE
Persistent menu after clicking off of object

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#7143]
It is sometimes possible to right click an object and then deselect the object but glitch the menu to stay visible. The menu cannot then be closed except by using one of the menu actions and then undoing it. I am unable to reliably reproduce it but it has happened to me many times.

![image](https://user-images.githubusercontent.com/25139386/71191238-07b32680-2254-11ea-953a-90bc5040a732.png)

**Comment by quincylvania** [comment]
@rivermont Did changing the title mean you also see this in v2?

**Comment by rivermont** [comment]
No I only removed it when it was added to 3.0.0 milestone; sorry for confusion. I can't say that it's _not_ possibly in v2, though.

**Comment by forteller** [comment]
This happened to me now when I right clicked an then used a keyboard shortcut to do one of the things in the context menu (V). Just in case it's helpful to know what can trigger this.

**Comment by quincylvania** [comment]
@forteller Thanks for the tip. I was able to reproduce this in the `develop` branch.
