### ISSUE TITLE
Maxar imagery does not load (expired connect ID)

### ISSUE THREAD

**Issue by hexaguin** [openstreetmap/iD#7144]
It looks like the connect ID used for Maxar is expired. Attempting to use either of the Maxar layers returns 403 errors for every tile, with the following error: `HTTP Status 403 - Login failed - an expired connect ID was specified.Credentials[username=null, connectId=d9c5e3ef-6300-4cec-9562-c1f27da6b2d9]`.

**Comment by bhousel** [comment]
Yes, we had a few days notice about this..
I removed these layers in editor-layer-index here:  https://github.com/osmlab/editor-layer-index/pull/752
so future releases of iD will not include it.. We will release a new version soon..

**Comment by hexaguin** [comment]
Darn, that's disappointing that people were taking advantage of the API key like that. Hopefully something gets worked out soon.
