### ISSUE TITLE
Submit buttons have inconsistent spacing

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#7146]
![image](https://user-images.githubusercontent.com/25139386/71302125-a4211a00-2375-11ea-9df7-43da5c6424b2.png)

![image](https://user-images.githubusercontent.com/25139386/71302129-ab482800-2375-11ea-9cec-55964461c508.png)

v3 ef3ccca

**Comment by quincylvania** [comment]
@rivermont Thanks for reporting. We'll fix stuff like this before shipping v3 but I don't think we need an open issue since the branch is still undergoing churn.
