### ISSUE TITLE
Add breastfeeding area / baby care tag hints

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7152]
Typing "breastfeeding area" and "baby feeding" etc. only comes up with hints for shops. Please add breastfeeding area tag hints.
https://wiki.openstreetmap.org/wiki/Tagging_in_Support_of_Women_and_Girls
https://wiki.openstreetmap.org/wiki/Proposed_features/babycare
OK I note at least amenity=childcare comes up.

**Comment by animesh-007** [comment]
ok, I would like to work on it.

**Comment by animesh-007** [comment]
Hi, Thank you for allowing me to work on this issue. I was able to solve the issue. Also, I have attached a screenshot of my work. I wanted to ask what would you suggest the branch commit name and it would be great if you could let me know if there are any further modification needed with the current change.
<img width="880" alt="issue_1" src="https://user-images.githubusercontent.com/53366877/71424908-02733300-26bd-11ea-943d-cf4993d0e58b.png">

**Comment by jidanni** [comment]
Great work.
(All I know is how to report bugs. Not what file to change. Maybe someone else knows.)

**Comment by quincylvania** [comment]
@animesh-007 Thanks for working on this! You can name the branch whatever you want, like `breastfeeding-area-preset`, and [open a pull request](https://github.com/openstreetmap/iD/compare) targeting the `2.x` branch.

I can't tell from the screenshot if changes are needed, but I can review your code once you open the PR.

**Comment by animesh-007** [comment]
Thank you for the suggestions, btw I have already made a PR and hers's the link to it https://github.com/openstreetmap/iD/pull/7183
Hope to hear your comments soon 😃

**Comment by quincylvania** [comment]
@animesh-007 This issue turned out to be more complicated than it first appeared, so I just handled it myself. Let us know if there are any other issues you'd care to work on!
