### ISSUE TITLE
adding multilingual names broken

### ISSUE THREAD

**Issue by mueschel** [openstreetmap/iD#7156]
It seems that adding multilingual names is broken. 
Example: I try to add the tag "name:oc=ZZZ"
1. I write 'oc' to the language field for multi-lingual names
2. This is automatically changed to 'Oc', resulting in a tag "name:Oc=ZZZ" on the object
3. I manually correct 'Oc' to 'oc'
4. Now a tag "name:Okzitanisch=ZZZ" is added. My browser language is set to German - if I change it to English "name:occitan=ZZZ" is added instead.

**Comment by quincylvania** [comment]
This issue was due to Occitan being missing from the CLDR language list. I added it manually.

**Comment by mueschel** [comment]
Occitan was only one example. The same thing happens with other languages, e.g. xmf / Mingrelian

**Comment by quincylvania** [comment]
Okay, we can look into this further.

**Comment by 1ec5** [comment]
Try comparing the CLDR list to the wmf-sitematrix list. wmf-sitematrix includes [several nonstandard codes](https://phabricator.wikimedia.org/T22547) for [historical reasons](https://phabricator.wikimedia.org/T10217), but most of the codes found in wmf-sitematrix are standard codes worth adding here.

**Comment by mueschel** [comment]
It doesn't seem to be a problem with tables of codes, but rather a software issue when entering language codes.
I can reproduce it with Serbian as well - If I enter 'sr', it auto-corrects to 'Sr' (and adds 'name:Sr'), I change the spelling back to 'sr' and it changes to "Serbisch"/"Serbian"  (and adds 'name:Serbisch' or 'name:Serbian')
