### ISSUE TITLE
Checking for Conflicts endless loop

### ISSUE THREAD

**Issue by Thorwynn** [openstreetmap/iD#7163]
I had edited a street in JOSM then later edited the same street in iD. When I saved my changes in iD I had to resolve 19 conflicts which I did successfully. The changeset is still open (https://www.openstreetmap.org/changeset/78828292/). But iD gets stuck at "Checking for Conflicts" it loops from 0 to 457 then starts again. 
![image](https://user-images.githubusercontent.com/47923400/71422033-cb653900-264c-11ea-87eb-4e61715f31f4.png)

Not sure if this is related but the inspector in my Chrome browser has this:
![image](https://user-images.githubusercontent.com/47923400/71422102-5e9e6e80-264d-11ea-81d3-1cc65e762b6a.png)

**Comment by bhousel** [comment]
Oh yeah #3056 was about this too.  Pointers in there to relevant code..

**Comment by Thorwynn** [comment]
Not sure if this helps and I have no idea how to use this console but I clicked on verbose and it added this: 
![image](https://user-images.githubusercontent.com/47923400/71422513-a5da2e80-2650-11ea-95dc-dc1d59537cf9.png)

**Comment by Thorwynn** [comment]
Looks like after letting this loop approximately 4000 times for about an hour the changeset is closed but no changes were applied. And iD still keeps checking for conflicts after changeset is closed (40 more minutes now)

**Comment by bhousel** [comment]
Yeah at this point you should probably just cancel it. It will probably go forever.

**Comment by bhousel** [comment]
#7199 looks like the same thing, but more details
