### ISSUE TITLE
Add gender field to shop=hairdresser

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7165]
Could we add the same field "Gender" for shop=hairdresser as we have for amenity=toilets?

Gender
male=\*, female=\*, unisex=\*

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhairdresser

**Comment by quincylvania** [comment]
@maro-21 Hmm I'm not sure these tags are actually suitable for any kind of shop. The gender tags usually describe what gender is allowed access to the feature. While hairdressers sometimes focus on persons of one gender, others are not typically prohibited, at least in most regions.

**Comment by IgorEliezer** [comment]
Barber shop, which is men only and differs from a hairdresser, is shop=hairdresser + male=yes.

> Tag to indicate if it's unisex or for men (aka barbers shop) or for women. (see [wiki](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhairdresser#Tags_to_use_in_combination))

**Comment by maro-21** [comment]
So what is the way to indicate that a hairdresser is for men or women? Is there any other tag?

male/female/unisex tags are commonly used:
We have around 211,566 `shop=hairdresser`s and
`[shop=hairdresser] + [male]`: 3682 features
`[shop=hairdresser] + [female]`: 2598 features
`[shop=hairdresser] + [unisex]`: 3534 features

> I'm not sure these tags are actually suitable for any kind of shop. The gender tags usually describe what gender is allowed access to the feature.

In this case it has a different meaning. Like `service=` key is also used in different ways.

**Comment by quincylvania** [comment]
So I'm really not comfortable with this tagging. The `service` key has different, documented values for different domains. The gender tags are explicitly defined in the wiki like this: 

> Denotes that access is restricted to persons of the female sex or gender. This is an access tag following the same rules as those described in access=*, though the presence of this tag with a yes value necessarily implies a no for all other gender-based access tags.

I don't care how the tags are applied in practice or if the wiki is outdated. We can't support tags could be inaccurately read as exclusionary.

I suggest coming up with alternative tags for branding and services offered to help differentiate different types of hairdressers. Like `hairdresser=barber` / `hairdresser=salon`, for example.
