### ISSUE TITLE
Warnings for unedited features appearing in some locations

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7166]
I added just a hotel and a building, I didn't even touch any other features and while saving, I had a long list of warnings. After saving, the changeset says that I resolved a lot of issues which is not true. I didn't even have a railway on the screen.

https://www.openstreetmap.org/changeset/76369935

resolved:crossing_ways:highway-railway 	24
resolved:help_request:fixme_tag 	1
warnings:close_nodes:vertices 	3
warnings:crossing_ways:building-highway 	6
warnings:crossing_ways:building-railway 	12
warnings:outdated_tags:deprecated_tags 	1

another examples with the same bug:
https://www.openstreetmap.org/changeset/77283896
https://www.openstreetmap.org/changeset/77483846
https://www.openstreetmap.org/changeset/77644003
https://www.openstreetmap.org/changeset/77748235
https://www.openstreetmap.org/changeset/77748273
https://www.openstreetmap.org/changeset/78736850

**Comment by quincylvania** [comment]
@maro-21 Whoa, that looks like a nasty bug. I just loaded that area and it said my edits had tons of warnings before I touched anything. Thanks for reporting!

**Comment by maro-21** [comment]
Another example:
https://www.openstreetmap.org/changeset/80835833
A user added only 4 address nodes, so how is it possible that he resolved `crossing_ways:building-highway` and `mismatched_geometry:vertex_as_point`?

**Comment by quincylvania** [comment]
@maro-21 Weird! This must be a separate underlying issue since the changeset was made with the lastest version of iD. There's likely another edge case that causes a validation rule to error out, but I couldn't reproduce it immediately.

**Comment by maro-21** [comment]
Another example, the same as the above one: https://www.openstreetmap.org/changeset/83900919

**Comment by maro-21** [comment]
Strange tags added to the changeset:
```
resolved:crossing_ways:highway-railway=76
warnings:crossing_ways:highway-railway=76
```
https://www.openstreetmap.org/changeset/90788701
https://www.openstreetmap.org/changeset/90788958
