### ISSUE TITLE
[Translation Error] PT-PT

### ISSUE THREAD

**Issue by DiogoBaptista98** [openstreetmap/iD#7167]
Amazing new feature on the new update:

> You can now add bridges and tunnels with a single click to fix crossing roads, rails, and waterways. Thanks to @CarycaKatarzyna for working on this!
Find the "Add a bridge" and "Add a tunnel" fixes for each crossing in the Issues inspector.

But there is a translation error on portuguese from portugal, where it says Add a bridge-Adicionar uma pont**a** should be Adicionar uma pont**e**

Thank you,
Merry Christmas
Diogo Baptista

**Comment by maro-21** [comment]
You yourself can correct this error here: https://www.transifex.com/openstreetmap/id-editor/language/pt/

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/openstreetmap/id-editor/dashboard/), so you should sign up for an account there to fix issues with the translations.
