### ISSUE TITLE
Link to privacy notice in splash screen is untranslatable

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#7171]
The privacy notice added to the splash screen in #7040 is mostly translatable, but the link to the privacy policy has a hard-coded label “here” that can’t be translated. As a result:

> By using this software, you agree to do so in accordance with the iD privacy policy, which can be found [here](https://github.com/openstreetmap/iD/blob/master/PRIVACY.md).

would become this in Vietnamese:

> Nếu bạn sử dụng phần mềm này, bạn đồng ý với chính sách về quyền riêng tư của iD có sẵn [here](https://github.com/openstreetmap/iD/blob/master/PRIVACY.md).

The link text should be made translatable as well, but while we’re at it, I think it would read better if the words “iD privacy policy” were linked instead.

https://github.com/openstreetmap/iD/blob/ada4fb5814a51c3e49e451149a54e1469b6c971c/modules/ui/splash.js#L55-L58

**Comment by bhousel** [comment]
sorry about that - just fixed it.
