### ISSUE TITLE
Add 'X' to close "Welcome to the iD OpenStreetMap editor" as additional method

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7172]
Add a "X" closer button in the upper right of
![X2](https://user-images.githubusercontent.com/1230959/71452346-1f902a80-27bf-11ea-9120-6e990f3ae890.jpg)
(Yes even if there is "Edit now" further below.)

**Comment by jidanni** [comment]
Do like this one, from the OSM website:
![X4](https://user-images.githubusercontent.com/1230959/71453246-3afe3400-27c5-11ea-9c3f-0d47370bc795.jpg)

**Comment by quincylvania** [comment]
This would be okay… but I'm closing it as low impact since it's not a strong pain point and we're probably redesigning this screen for v3 anyway.
