### ISSUE TITLE
A1303 label is truncated

### ISSUE THREAD

**Issue by occultations** [openstreetmap/iD#7173]
The map at https://www.openstreetmap.org/#map=15/52.2117/0.0875 has a "3" in a box on top of Madingley Road. It's part of "A1303", which appears correctly if you zoom in. It's just at this zoom level that it appears incorrectly.

**Comment by quincylvania** [comment]
Hi @occultations, this repository is for the iD editing tool. This looks like an issue with the rendered map tiles which you might try bringing up at the [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto) repo instead. Good luck!
