### ISSUE TITLE
entrance = secondary_entrance is a void tag

### ISSUE THREAD

**Issue by opendcc** [openstreetmap/iD#7174]
Hello,

iD suggests entrance = secondary_entrance, however this key is not found in the wiki nor was it discussed on tagging talk lists.

best regards

**Comment by quincylvania** [comment]
Hi @opendcc, I assume you mean that tag appears in the suggestion list like this?

![Screen Shot 2019-12-26 at 2 25 21 PM](https://user-images.githubusercontent.com/2046746/71487908-c7bbe880-27eb-11ea-8281-a895fccddf70.png)

These suggestions are the most-used values and are automatically retrieved from the [TagInfo API](https://wiki.openstreetmap.org/wiki/Taginfo/API) when the field loads. There are thousands of undocumented tags in the OSM database that could potentially get suggested. If a tag is deprecated, let us know and we can filter it out of the list.

**Comment by opendcc** [comment]
Sorry, I can not confirm.

You're claiming, according to TagInfo this value is amoung the most commonly used. However, it was iD with its proposal who pushed up TagInfo. You're claiming 'common used', but yourself are creating this usage count. That is not the correct way to define values, you're not alone.

The same applies to main_entrance. There is already a value main, iD comes up with a new value with same meaning.

br Wolfgang

**Comment by BjornRasmussen** [comment]
The way it works is that the most commonly used values get suggested to users _unless iD has marked them as depreciated_.  If those values are duplicates or just bad in particular, then letting the maintainers know which values should no longer be suggested would be helpful.
Another solution is to do a large scale edit removing the tag from the OpenStreetMap database.  This is update iD within 24 hours.

**Comment by opendcc** [comment]
Hello,

thanks for answering.

entrance=main_entrance is deprecated, use entrance=main instead. entrance=main_entrance was used around Cambridge back in 2012 and never got standard. Then there was large gap and in 2019 this value popped up with iD entries again.

According to discussions on the openstreetmap forum, entrance=secondary_entrance should no be used, please use entrance=secondary instead.

We will try to update all existing main_entrance / secondary_entrance to the approriate value.

best regards

**Comment by 1ec5** [comment]
> You're claiming 'common used', but yourself are creating this usage count.

In general, the use of taginfo in field suggestions can only exacerbate already popular values, not cause them to be popular in the first place, since the suggestions are sorted starting with the tags that are already most frequently used. (However, some tags have only a few popular values followed by a long tail of uncommon ones, so any list of more than a few values can generate some organic usage, especially as users type in the first few characters of the value they want.)

According to [osm tag history](https://taghistory.raifer.tech/), the tag’s usage has been steadily increasing since 2016. I don’t see any [changes to the preset](https://github.com/openstreetmap/iD/commits/master/data/presets/presets/entrance.json) from that timeframe, so there must’ve been some other factor at play besides iD.

For those of us who don’t follow the forums very closely, can you link to the discussion wheee it was decided that `secondary_entrance` should no longer be used? Thanks!

**Comment by opendcc** [comment]
Hello,

if you run a overpass query on secondary_entrance ( http://overpass-turbo.eu/s/PhI ), you'll find a hotspot of usage in Cambridge (UK), all changesets created by user davidearl. That is the single source of secondary_entrance, back in 2011/2012. In this case, the strategy of iD (expanding a uncommon, single user value as selection value) lead to a wider introduction of a this tag - without any documention in wiki and with syntax errors in other tools. That is not the way a collaberate work should go. 

A discussion on https://forum.openstreetmap.org/viewtopic.php?id=68307 showed the common feeling, that similar to entrance=main a secondary entrance should be tagged as entrance=secondary.

In general: I think it would be good method to do a check on the wiki before offering a uncommon, selden use tag value in iD to newbies.

**Comment by opendcc** [comment]
Hello,

I also set up a request for mechanical edit (unify secondary and entrance_secondary) on talk@openstreetmap.org.

**Comment by 1ec5** [comment]
I guess I don’t understand why iD didn’t lead to wider usage between 2013 (when the preset was added) and 2016 (after which usage began to climb).

In an ideal world, iD would have dedicated presets and fields for every established key and value, but there are a lot of established keys and values, so this is a fallback for when no dedicated field is available. If iD didn’t have a taginfo-powered Type field, it would still “promote” it via the raw tag editor, which would be much less useful without taginfo.

If someone were to contribute a PR that turns the field into a combo field with a fixed set of values, that would allow us to translate the values and generally improve the user experience for this preset.

> In general: I think it would be good method to do a check on the wiki before offering a uncommon, selden use tag value in iD to newbies.

It wouldn’t be prudent to do this in an automated fashion for the taginfo-based fallback field. Unfortunately, plenty of approved values don’t have their own pages on the wiki yet – they’re only documented on the key’s page or on the page of some related tag. Wikignomes like me are chipping away at the problem, but it’s going to be a problem for a long time. There are also keys whose values are open-ended (documented as “User-defined values” on the wiki).

On the other hand, if someone were to contribute a custom combo field for the `entrance` key, they could manually curate the list, taking into consideration the approved status of any value. iD has accepted many such PRs in the past.

> In this case, the strategy of iD (expanding a uncommon, single user value as selection value) lead to a wider introduction of a this tag - without any documention in wiki and with syntax errors in other tools.

This might be a feature request for taginfo itself. Taginfo already collects statistics on how many people have last touched a feature with a given key, but it doesn’t collect that statistic for values. Additionally, the taginfo API doesn’t expose that statistic or offer a way to [filter suggestions](https://taginfo.openstreetmap.org/taginfo/apidoc#api_4_key_values) by a minimum number of mappers.

As an aside, OSM is partly a folksonomy based on mappers coining new tags when appropriate, those tags percolating up as other mappers embrace and eventually document them. At least that’s the OSM I started out with years ago. iD’s integration with taginfo effectively ensures that a broad spectrum of mappers can participate, not just those who know about taginfo. The wiki’s tag proposal process exists parallel to this organic process, but the tension between the two won’t be resolved solely by hiding unapproved values from iD users. (Not all of us are newbies. 🙂)

**Comment by opendcc** [comment]
Hello,

I understand your arguments, however we must improve the current situation. There is some wrong mapping around (like entrance=female, entrance=no or entrance=main_entrance), currently iD helps to spread out this wrong mapping and it takes a lot of effort to catch and fix all this stuff. Effectively, this unreflected offering of the 'top 30' tags brings in a lot of chaos and messes up the data base. (As a former collegue used to say: hey guys, eat shit, millions of flies can't be wrong). 

I would agree to maintain a list of acceptable items in the combo field.
------------
> As an aside, OSM is partly a folksonomy based on mappers coining new tags when appropriate, those tags percolating up as other mappers embrace and eventually document them.

I think there is still a way to enter value not on the list. So restricting the list to a managed selection will not stop invention of new tags (but will stop spreading of wrong tags!).

Please help to keep OSM clear and usable!

**Comment by opendcc** [comment]
(bold was not intended ..)

**Comment by opendcc** [comment]
Hello Quincy,

looking more closer to this issue: 
The university of cambrigde (see https://wiki.openstreetmap.org/wiki/University_of_Cambridge#Building_entrances)  is using it's own tagging values to create their university map. These tagging values have never been documented in a wiki. This leads to different tagging for the same situation: inside Cambridge, an main entry is entrance=main_entrance (below 1000 targets), all other places in the world use entrance=main (except those places, where a newbie has used the iD proposal of main_entrance) 400000 targets. 

For emergency exits the wiki declared entrance=emergency as correct value (9000 targets). Cambridge uses fire_exit (300 targets). And iD is offering this value as proposal.

Also interesting is entrance=private (should be entrance=*, access=private): again this value spreads out in the world.

This behavior leads to questions and discussions with newbies (why is this values offered in the menu when it not the recommended one, why is my entry not shown in the map) an I think we should work on reducing this errors.

What needs to be done to get a list fo correct values? I've seen some entries on /iD/blob/master/data/presets/, however the documentation is not fully clear to me.

best regards

**Comment by quincylvania** [comment]
> What needs to be done to get a list fo correct values?

@opendcc The [`options`](https://github.com/openstreetmap/iD/tree/2.x/data/presets#options) property of fields can be used to limit the list to known values. But again, a cleaner solution is just to mark all the errant values as deprecated so they'll be filtered out and iD can offer to upgrade them.
