### ISSUE TITLE
"Recreational network node" preset not available in preset list, and missing a tagbox

### ISSUE THREAD

**Issue by pelderson** [openstreetmap/iD#7176]
(Maybe I don't understand the Id preset system? ) 
1. When I edit a node, a list of node types appears, but the new Recreational network node is not one of them. But when I add the tag network:type=node_network, the node type changes to (Dutch for) "Recreational network node" and appropriate tag boxes appear. It would be nice to be able to choose the type from the node type list.
2. There is a specific tag "expected_rwn_route_relation=N" for walking network nodes (expected_rcn_route_relations=N for cycling network nodes). This tag is very helpful in maintaining the node network, the checking system detects lots of errors by comparing this expected number with the actual number of relations ending/beginning on this node.  It is a visible and easily verifiable attribute of the actual feature in the field: the number of other rXn_refs the recreational network node points to, so offering the tagbox in the preset will help to maintain actuality and quality of the network greatly. 
Note that a single node can be in a cycling node network and a walking node network at the same time. Best workflow would be: 
1. User clicks the node and chooses Recreational network node from the list. This sets network:type=node_network and offers tagboxes for rcn_ref and rwn_ref.
2. User sets rcn_ref to a value <> '', then a tagbox for expected_rcn_route_relations appears. Same with rwn_ref and expected_rwn_route_relations.

I don't know how this works if a node already has a different type, e.g. a bollard or crossing. These can be network nodes at the same time. So recreational network node is like a complementary type, it should not replace existing tagging.

**Comment by quincylvania** [comment]
Hi @pelderson…

Where exactly are you trying to add this preset? It's only available in certain regions.

The `expected_rwn_route_relation` tag really sounds too advanced for most iD mappers. I suggest using the raw tag editor to maintain these.

iD only supports one preset per feature since most OSM features are tagged this way. Changing a preset will always remove the tags for the existing preset. The "Recreational Network Node" preset has a low "matchScore", meaning iD will prefer most other presets if the node has other significant tags.

**Comment by pelderson** [comment]
I am in the Netherlands, at the moment the nr 1 country for recreational node networks.

The expected.... tags too advanced? Why? Any mapper who recognizes a recreational network node and can count, will understand and can enter the value just by looking at the network node. It's just how many other nodes this node points to. 
Would it be a problem to include them in the preset? The caption could be something like "Cycling node routes at this node" and "Walking node routes at this node". 

The tag names are awkward, that's exactly why having them in the preset would help a lot.
Would it help the matter if the tags and the network node system were documented better?

**Comment by quincylvania** [comment]
> I am in the Netherlands, at the moment the nr 1 country for recreational node networks.

I'm seeing the preset in search here. Make sure you're selecting a node that's part of a way. Where approximately in the Netherlands are you mapping? There could be inaccuracies in our country coding near the borders.

> The expected.... tags too advanced? Why? Any mapper who recognizes a recreational network node and can count, will understand and can enter the value just by looking at the network node. It's just how many other nodes this node points to.

Oh I misunderstood, I read "expected_rwn_route_relation" as containing the OSM ID of the connected relation, but I guess the tag is actually "expected_rwn_route_relations" and contains the number of relations. This is still a bit advanced for most iD mappers, but I suppose if someone is using this preset anyway they could handle it.

Oh also, in the future could you split up separate concerns into different GitHub issues as best you can? This makes them easier to address 🙂

**Comment by quincylvania** [comment]
> Would it help the matter if the tags and the network node system were documented better?

Yes! Clear and detailed tag documentation makes it easier to support, map, and consume tags.

**Comment by pelderson** [comment]
Vr gr Peter Elderson


Quincy Morgan <notifications@github.com>:

> I am in the Netherlands, at the moment the nr 1 country for recreational
> node networks.
>
> I'm seeing the preset in search here. Make sure you're selecting a node
> that's part of a way. Where approximately in the Netherlands are you
> mapping? There could be inaccuracies in our country coding near the borders.
>
I am at https://www.openstreetmap.org/edit#map=19/51.96879/4.60947  then
choose a node that's part of a way.  I click Punt (Dutch for point or
node). A numer of node types appear, but Knooppunt van recreatief netwerk
(Recreational network node) is not one of them. I see no option to expand
the list! Maybe I don't understand the preset system?

**Comment by pelderson** [comment]
Op di 31 dec. 2019 om 16:36 schreef Quincy Morgan <notifications@github.com
>:

> Would it help the matter if the tags and the network node system were
> documented better?
>
> Yes! Clear and detailed tag documentation makes it easier to support, map,
> and consume tags.
>
> https://wiki.openstreetmap.org/wiki/Key:network:type  shows the system in
a nutshell!
The photo shows a cycling node no. 32 (rcn_ref=32) It points to three other
nodes (39, 30, 55) so expected_rcn_route_relations=3.
Anyone slightly familiar with this type of network will regocnise this as a
recreational network node, network:type=node_network.

 That's it!

**Comment by quincylvania** [comment]
> I click Punt (Dutch for point or
node). A numer of node types appear, but Knooppunt van recreatief netwerk
(Recreational network node) is not one of them. I see no option to expand
the list!

@pelderson Oh! The default list doesn't contain all possible presets. You have to search to find this one 😄

<img width="719" alt="Screen Shot 2019-12-31 at 12 06 58 PM" src="https://user-images.githubusercontent.com/2046746/71628477-17245f00-2bc6-11ea-87aa-d103585b7ea4.png">

> The photo shows a cycling node no. 32 (rcn_ref=32) It points to three other
nodes (39, 30, 55) so expected_rcn_route_relations=3.

Oh man this is a confusing tag. If it refers to the number of adjacent nodes why isn't it called `expected_rcn_route_nodes`?

**Comment by pelderson** [comment]
For a route mapper it gives the expected number of node2nodes routes landing on this node. From the user perspective it gives the number of adjacent nodes it points to, which is exactly the same. I guess the key was invented by mappers, not users.

**Comment by quincylvania** [comment]
> From the user perspective it gives the number of adjacent nodes it points to

Okay, I guess this isn't too entirely complex for someone who wants to map these. I added these two fields:

![Screen Shot 2020-01-06 at 4 16 16 PM](https://user-images.githubusercontent.com/2046746/71849458-1bf28280-30a0-11ea-8d1d-00a58f3dca15.png)

**Comment by pelderson** [comment]
Thanks! This will help mappers to map and maintain recreational node networks in the OSM.
