### ISSUE TITLE
Mapillary wrong object select

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7177]
Hi,

I recently came across this location: https://www.openstreetmap.org/edit#map=19/51.09104/3.44218
Where if I click on this 'give way' sign, it for some reason selects a different location.
And Mapillary street sign integration just seems to break down after a couple minutes of editing (even though I've only edited a couple nodes.
https://drive.google.com/file/d/1scgtjiYm4xzRoq_oqOQ959pp8KdhD1xL/view
Just look at this footage where it's stopped showing boundary boxes around the traffic signs.
And at the very end does show a boundary box but it's not even for the right object.
EDIT: also that 30 sign at the end of the video doesn't even exist there irl (the one that thought the sign from some other location was actually there for some reason. Although this part might be mapillary's fault)

Cheers

**Comment by quincylvania** [comment]
#7885 made the Mapillary traffic sign/photo linkage more robust and hopefully fixed these issues.
