### ISSUE TITLE
Add Belgium road sign icons

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7178]
Hi,

On the OSM wiki there is a page of all the common road signs we use in Belgium: https://wiki.openstreetmap.org/wiki/Road_signs_in_Belgium
When editing in Belgium, when selecting those tags (ex  "traffic_sign"="BE:F4a")
It'd be nice if it showed the actual sign icons like on the wiki

Cheers

**Comment by quincylvania** [comment]
@thibaultmol Yep, adding country-specific traffic sign presets is #5666. I'd love for there to be a traffic sign index where we can support Belgium and any place.

**Comment by 1ec5** [comment]
`traffic_sign` is one of several common tags whose values are prefixed by a country code and a colon. (`network` is another example.) These tags would benefit from a country selector like #7123 (which can default to the current country), plus a subfield of some sort that appends to the same tag.

A sign index would be really cool, though one complication is that `traffic_sign` technically accepts a complex syntax intended to describe the sign’s layout and contents. So unfortunately it’s more like `opening_hours` than the `brand` tag that has so successfully been indexed.
