### ISSUE TITLE
Allow to turn on specific features using url options

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7180]
Situation: You look at Osmose and see an issue about a traffic sign not being mapped yet: http://osmose.openstreetmap.fr/en/map/#item=xxxx&level=2&tags=&fixable=&bbox=3.326892%2C51.024075%2C3.446005%2C51.101173&zoom=18&lat=51.0784&lon=3.409878

You click on 'osm-edit' to open iD at that location.
Right now it just does exactly what it says BUT it would be ideal if it could also turn on the Mapillary layer and the Mapillary - Traffic signs layers trough options in the url. (since having those enabled while mapping a traffic signed detected BY Mapillary makes sense).

I imagine the url being instead of this:
https://www.openstreetmap.org/edit#map=18/51.0783956/3.4100272
This:
https://www.openstreetmap.org/edit#map=18/51.0783956/3.4100272?PhotoLayers=Mapillary;MapillaryTS (traffic signs)

**Comment by quincylvania** [comment]
@thibaultmol So iD already supports this with the `photo_overlay` parameter. You can check out all the API parameters [here](https://github.com/openstreetmap/iD/blob/2.x/API.md#url-parameters). 

It's possible some of these aren't working correctly on osm.org. We're having some issues with parameters getting passed to iD.
