### ISSUE TITLE
Key P multiple uses in German translation

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#7181]
iD shows the privacy policy setting after pressing 'P' in the german translation:
![image](https://user-images.githubusercontent.com/5360273/71484506-031adf00-280d-11ea-8e60-524747f7be22.png)

According to the keyboard shortcuts there are two uses for 'P'
![image](https://user-images.githubusercontent.com/5360273/71484478-e5e61080-280c-11ea-86f4-252b78145154.png)

I cannot find the translation strings in transifex:
![image](https://user-images.githubusercontent.com/5360273/71484550-3e1d1280-280d-11ea-939b-f7e8af6f7953.png)

Can anyone help please?

**Comment by mmd-osm** [comment]
The two field you've highlighted correspond to "Toggle validation issues pane" and "Toggle user preferences pane" in the English version:

 https://github.com/openstreetmap/iD/blob/96b2b42ba7503a15c4bb87fe443c607e186cb66a/data/core.yaml#L1968-L1969

Maybe transifex hasn't pulled those strings yet?

**Comment by manfredbrandl** [comment]
Transifex has pulled the text but I can’t find the shortcut key ‚P‘.

**Comment by quincylvania** [comment]
Here are the two strings in Transifex that are currently both `P` in the German locale. One will have to be changed.

https://www.transifex.com/openstreetmap/id-editor/translate/#de/$/164551831?q=key%3Aissues.key

https://www.transifex.com/openstreetmap/id-editor/translate/#de/$/188721724?q=key%3Apreferences.key

**Comment by manfredbrandl** [comment]
I changed the first key (issues.key) back to the english Original ‚I‘.

**Comment by manfredbrandl** [comment]
12 Hours later I still see the two ‚P‘ for different options on https://preview.ideditor.com/release and https://preview.ideditor.com/master. Do I have to wait longer or is there anything wrong?

**Comment by mmd-osm** [comment]
Translations are only updated after running `npm run translations`  and committing the changes to this repo, it doesn't happen automatically simply by changing something in transifex.

**Comment by manfredbrandl** [comment]
Is there a chance to get the translations automatically in some preview?

**Comment by bhousel** [comment]
The updated translations should show up automatically in the preview site, but we will need to push a commit first for it to rebuild.

**Comment by mmd-osm** [comment]
Even better, I thought this is a manual step. Now looking at https://github.com/openstreetmap/iD/blob/2.x/CONTRIBUTING.md, is the following hint still good?

_You can check your translations in the master deployment (http://preview.ideditor.com/master/), which is updated every 10 minutes with the latest code and translation strings._

**Comment by bhousel** [comment]
Yes I think it’s still working

**Comment by manfredbrandl** [comment]
I just checked and can confirm that translations go automatically to preview.../master but NOT to preview.../release. Question: Is it worth doing that for release also or will iD v3 be deployed so soon that there is no reason to think about that?

**Comment by quincylvania** [comment]
@manfredbrandl We'll release a 2.17.1 patch soon.

**Comment by quincylvania** [comment]
Looks like this has indeed been resolved. I did #7185 so in the future we can catch these conflicts before we do a release.
