### ISSUE TITLE
Try to read property _zoom of undefined object

### ISSUE THREAD

**Issue by sjarrossay** [openstreetmap/iD#7184]
On Google Chrome
Version 79.0.3945.88 (Build officiel) (64 bits)

When we use layer cluster property and you embed the map, we got an error in script 
`TypeError: Cannot read property '_zoom' of undefined`
As result we just have a marker on map when you expected cluster marker
Result :
<img width="195" alt="Capture d’écran 2019-12-26 à 19 17 45" src="https://user-images.githubusercontent.com/43173739/71486040-a1f70980-2814-11ea-9ef1-1e7fef7a50b7.png">

Expected :
<img width="301" alt="Capture d’écran 2019-12-26 à 19 19 48" src="https://user-images.githubusercontent.com/43173739/71486064-ba672400-2814-11ea-9fcc-e5453749f2ab.png">
 
It's appear in a method addLayer :
<img width="1207" alt="Capture d’écran 2019-12-26 à 19 10 30" src="https://user-images.githubusercontent.com/43173739/71485971-24cb9480-2814-11ea-96ad-26463bf668c6.png">

**Comment by sjarrossay** [comment]
A work-arround of this bug is to open fullscreen link and back to embed map

**Comment by mmd-osm** [comment]
This looks a bit like https://umap.openstreetmap.fr
Is this the website you were using?

**Comment by sjarrossay** [comment]
Yes I forgot to said that : 
Is there any other repo for that ?

**Comment by mmd-osm** [comment]
Yes, umap has its own repo: https://github.com/umap-project/umap/issues

Thank you!

**Comment by sjarrossay** [comment]
Thanks to you
I report it here then

**Comment by quincylvania** [comment]
Thanks for assisting, @mmd-osm. Good luck, @sjarrossay!
