### ISSUE TITLE
[Feature Request] allow for precise moving of objects using arrow keys

### ISSUE THREAD

**Issue by sevku** [openstreetmap/iD#7186]
Some times I found it to be a struggle to move objects and nodes precisely using the mouse. Therefore I would suggest a functionality that allows to move objects using the arrow keys after pressing the m button.

**Comment by BjornRasmussen** [comment]
Aren't arrow keys already used for the map?  I personally think this would be confusing and marginally helpful.  I have no issues with using `shift-<arrowkey>` though, since it doesn't conflict with existing usages.

**Comment by sevku** [comment]
> Aren't arrow keys already used for the map? I personally think this would be confusing and marginally helpful. I have no issues with using `shift-<arrowkey>` though, since it doesn't conflict with existing usages.

I don't think we are talking of the same thing

**Comment by BjornRasmussen** [comment]
I'm pretty sure that we are.  I just think it would be confusing if the arrow keys, which normally move the map, behaved differently in this situation.

**Comment by 1ec5** [comment]
This could be useful for those with motor disabilities. What do drawing tools normally do in this situation? I know some drawing tools allow you to “bump” features with the arrow keys; how do they distinguish between moving the object and moving the canvas? Does it depend on whether an object is selected?

**Comment by Prince-Kassad** [comment]
In JOSM, Ctrl+arrow keys moves the canvas and Shift+arrow keys moves the currently selected object.

**Comment by quincylvania** [comment]
> I know some drawing tools allow you to “bump” features with the arrow keys; how do they distinguish between moving the object and moving the canvas? Does it depend on whether an object is selected?

@1ec5 Sketch works like this, but being able to bump the canvas during selection seems more useful in an app like iD where the features can sprawl far and wide. I'd be okay with using `shift-<arrowkey>` for bumping selected features.

**Comment by quincylvania** [comment]
Looks like this was raised before in #1348. I think it's worth doing now with a modifier key.

**Comment by sevku** [comment]
The issue I got with this is that every single nudge is added to the edit history, so reverting can become pain in the a**.
