### ISSUE TITLE
Warning: Names of Traffic signs

### ISSUE THREAD

**Issue by mfbehrens99** [openstreetmap/iD#7189]
When a traffic sign has a name like "give way" or "stop" or any other name of a traffic sign it should be announced that this is a suspicious name.

![image](https://user-images.githubusercontent.com/58851724/71541277-68c2b480-294e-11ea-9894-c848d0fe9d3b.png)

**Comment by manfredbrandl** [comment]
Do we really want people to add names to traffic signs? There may be rare cases where a traffic sign really has a name, but we should not show the name field by default.

**Comment by mfbehrens99** [comment]
I would like to have a message like this

![image](https://user-images.githubusercontent.com/58851724/71549472-f1c10680-29b5-11ea-86f3-ede7bfc042a1.png)

But usually the name input is not shown, only when the sign has a name.

**Comment by quincylvania** [comment]
@mfbehrens99 I've never seen this issue in practice… do you know how common it might be?

**Comment by mmd-osm** [comment]
traffic_sign=give_way has exactly one node with a name: 5890628171
traffic_sign=stop_sign has 5 nodes named stop: https://overpass-turbo.eu/s/Ppk

**Comment by quincylvania** [comment]
@mmd-osm Based on the screenshot, this issue appears to be about `highway=stop`.

**Comment by mmd-osm** [comment]
Ok, let's take a look at highway=stop nodes instead::

* name like "stop" : 29 nodes - https://overpass-turbo.eu/s/Ppm  
* any name: ~ 800 nodes 

Global breakdown by name: https://overpass-turbo.eu/s/Ppn

Most notably: 
* 185 times: Give Way
* 13 times: Stop Sign

**Comment by quincylvania** [comment]
@mmd-osm Thanks for your overpass wizardry! This indeed seems like a really uncommon issue. Instead of spending time on a warning, I'd say the 185 "Give Way" stops can undergo manual review—they probably shouldn't even be changed automatically in case some are actually stops.
