### ISSUE TITLE
Bing should no longer be the default imagery

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7193]
Examining an average Bing HTTP header,
```
X-VE-TILEMETA-CaptureDatesRange: 4/19/2011-4/19/2011
```
reveals it is already around "10 times" older than the others, so perhaps should no longer be the default iD imagery.

I.e., a different radio button should be preselected.

I currently have no opinion on the order of the Background imagery list. I'm just talking about which button should be preselected for the first time user.

**Comment by quincylvania** [comment]
@jidanni Sorry, but an HTTP header is not indicative of the imagery quality. The capture dates for every global imagery layer vary throughout the world. Overall I've found Bing to be fine for general-purpose mapping. Also, iD can default to a different imagery source if it's been marked as "best" by the local community.
