### ISSUE TITLE
Several imagery layers actually produce many HTTP 404s under the hood for higher zoom levels

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7194]
Currently every background layer loads fine. Everything looks great.

However if we look under the hood (Using browsers' Developer Tools console,) we note that these three layers,

- Esri World Imagery
- Esri World Imagery (Clarity) Beta
- Stamen Terrain

make plenty of requests that result in '404 Not Found', as the user zooms in and out.

Correct, the user is not bothered by this as it is all happening deep down. These three layers look just as good as the rest. But still it points to perhaps some kind of GetCapabilities misconfiguration or something.

Whereas for other imagery iD knows not to ask for zoom levels that don't exist on the tile server, but for the three above, the GetCapabilities etc. is not correct, so a doomed attempt to fetch them is sent anyway.

**Comment by quincylvania** [comment]
@jidanni The min/max zoom is defined for each source at the [editor-layer-index](https://github.com/osmlab/editor-layer-index). The layers you mentioned [seem to be bounded correctly](https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/world/StamenTerrainBackground.geojson), but perhaps don't have high-zoom coverage for every place on Earth. In any case, these 404s don't affect the user experience whatsoever.
