### ISSUE TITLE
Rename "None" background layer "black" and add additional "white" choice for Locator Overlay visibility

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7195]
In this situation the Locator Overlay is mainly cancelled out via the black "None" background:
![X3](https://user-images.githubusercontent.com/1230959/71567024-0e188c80-2af7-11ea-84b5-c10d8db3fdc2.jpg)
If "None" were renamed "Black", and an additional "White" radio button were available, one could finally see the locator overlay, without needing map tiles.

**Comment by jidanni** [comment]
It would look like this!:
![X4](https://user-images.githubusercontent.com/1230959/71567175-f7266a00-2af7-11ea-89be-3e4a8db25062.jpg)
(minus the blue lines and biggest names.)

**Comment by bhousel** [comment]
The overlay is going to get replaced because of https://github.com/osmlab/editor-layer-index/issues/692#issuecomment-565084602, so I think we can make the replacement visible on both light or dark backgrounds.
