### ISSUE TITLE
Match shop=yes against NSI brands

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7197]
I came across a node tagged shop=yes and name="Topps tiles". I changed this to shop=tiles and then iD offered to upgrade the tags with brand data.

For shop=yes objects where the name matches* would it be possible for iD to offer to upgrade the tags? This would be useful since these shops can be missed when looking at an area, as they are not otherwise highlighted by iD.

*a case insensitive match would be good

**Comment by quincylvania** [comment]
@boothym This sounds like it'd be a a useful improvement. However, the matching code is actually handled by the NSI package itself, [here](https://github.com/osmlab/name-suggestion-index/blob/master/lib/matcher.js). Could you open an issue in that repo instead? Then anyone using the index can benefit from the change.
