### ISSUE TITLE
Add bingo hall preset

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7198]
Saw this diary post and thought it would be a useful preset to have: https://www.openstreetmap.org/user/UKChris/diary/391755 Used over 100 times in the UK. 

name: Bingo Hall (or maybe it should be venue?)

terms: amenity=gambling, gambling=bingo

**Comment by quincylvania** [comment]
Okay, I added a Gambling Hall for preset for `amenity=gambling`. I don't think a specific preset for `gambling=bingo` is necessary since even the Buzz Bingo brand wouldn't match it since it has `gambling=bingo;slot_machines`.
