### ISSUE TITLE
Can't send changeset by iD

### ISSUE THREAD

**Issue by TastyComputer** [openstreetmap/iD#7200]
I trying send changeset by iD from yesterday without success. I get error "Please ensure you are connected to the internet." still. My login on OSM is JulesGabrielVerne

**Comment by quincylvania** [comment]
Hi @TastyComputer, and welcome.

Hmm it's hard to tell what's going on without more information. Can your computer still connect to other sites? Are there any [JavaScript errors](https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors)? A screenshot of the error page would be helpful too.

**Comment by TastyComputer** [comment]
Thanks quincylvania for response. I pressed Shift+Ctrl+J and after that dialog to resove conflict was appeared. I think this is not a coincidence. I've tried several times without success. Perhaps more people will have this problem in the future. At this point, the topic can be considered closed.
