### ISSUE TITLE
strange connection of two paths

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7201]
I found on Osmose two close paths that need connecting with each other and used iD's "connect features" function but, instead of extend one path to the other and connect endpoints, it created new node and the paths overlap.
https://www.openstreetmap.org/edit?way=684989044#map=22/51.09896/16.95324
![iD](https://user-images.githubusercontent.com/57260466/71727765-97072f00-2e3b-11ea-9d47-c4036639ac02.png)

**Comment by SilentSpike** [comment]
Hmm this is an interesting edge case where the ways are close to collinear.

Haven't looked at the code, but I imagine it just projects forward from the selected way's endpoint and connects to the other way where contact is made - so because of the slight difference in angle it misses the endpoint and comes out like this.

Perhaps taking the lines from both endpoints to the node before one of the endpoints and connecting the endpoints if the angular difference is small would solve this 🤔

**Comment by quincylvania** [comment]
@SilentSpike Your analysis seems on-point—the code only searches for edges and not endpoints. The screenshots don't indicate the scale but I would think the map's zoomed in pretty far.

**Comment by maro-21** [comment]
Yes, they are so close that this isn't even visible on the map that they're disconnected. The gap is around 50 cm.
https://www.openstreetmap.org/#map=22/51.09896/16.95324

**Comment by SilentSpike** [comment]
Had a look at the code and a bit of a think about this earlier.

Context:
- The code checks 5m ahead of an endpoint for intersections
- If the point of intersection would be within 0.75m of a node, the quick fix joins the endpoint to that node

As such I believe the two extremes where you could see such unexpected results:
- Endpoints are very close together, but angular difference between edges creates an intersection point between 0.75-5.75m from the endpoint (this is the OP case).
- Endpoints are ~4.25m apart and edges are close to collinear, but angular difference creates an intersection point just over 0.75m from the endpoint

I think the most valid solution would be:
1. Before checking for intersections, check if the endpoints are within 0.75m of each other and that joining them wouldn't create a crossing
    - Quick to check and mirrors the quick fix threshold
    - Would catch new cases of almost junction where the angular difference of edges produces no intersection
2. If an intersection is found and an endpoint is within 4.25m (and joining wouldn't create a crossing), check whether the respective edge is close to collinear
    - Could be the case that both endpoints are close, check both if so, use closest angle if both close to collinear
3. If either of the above is true, set the `cross_loc` and `edge` to the position of the end node
