### ISSUE TITLE
make magnificent "add bridge" even smarter

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7202]
Try to avoid gluing bridge to crossings. See

![Selection_001](https://user-images.githubusercontent.com/899988/71728491-85268b80-2e3d-11ea-9599-0654696ef83c.png)
![Selection_002](https://user-images.githubusercontent.com/899988/71728494-8657b880-2e3d-11ea-9ba5-900f140ed436.png)

in this case it would be better to create a new node to avoid creating crossing with both `bridge=yes` and nonbridge lines, even if bridge would be unexpectedly short.

**Comment by rivermont** [comment]
This is the preferred way to map, and is requested by the wiki ([Link](https://wiki.openstreetmap.org/wiki/File:Bridge-Junction-Connection.png)).

**Comment by quincylvania** [comment]
This seems like an okay change to try. The trick is not creating super small segments. If the junction is very close to the crossing then there's not enough space to do this and we'd have to leave it to the mapper to fix.

**Comment by quincylvania** [comment]
> If the junction is very close to the crossing then there's not enough space to do this and we'd have to leave it to the mapper to fix.

Actually, our threshold is so small that it seems we're running up against this issue already. Where are you seeing this problem in practice, @matkoniecz?

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/760527831
https://www.openstreetmap.org/way/760527829

Mapping is not ideal or 100% certain, imagery in China is quite bad and there are serious alignment issues.  At https://www.openstreetmap.org/note/2045102#map=19/39.89339/116.39750&layers=N I was unable to be sure that I spotted either waterway or road.

> The trick is not creating super small segments.

I think that it is OK to create super small segment. In case of not doing this original or subsequent mapper will need to do it anyway. Way with `bridge=yes` reaching crossing where there other ways without `bridge` tag is never going to be correct (or at least it is going to be ridiculously rare).
