### ISSUE TITLE
Custom background source link broken

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7207]
I used a custom background and after saving, the changeset imagery_used had "Bing" included as part of the hyperlink for the custom url:

<td class="browse-tag-v">﷐Custom (<a href="https://anygis.ru/api/v1/Tracks_Strava_All/{x}/{y}/{z});Bing" rel="nofollow">https://anygis.ru/api/v1/Tracks_Strava_All/{x}/{y}/{z});Bing</a> aerial imagery;OS OpenData StreetView;Esri World Imagery﷯</td>

![Screenshot_2020-01-03 Changesets OpenStreetMap](https://user-images.githubusercontent.com/16965772/71753075-4f06fd00-2e79-11ea-82cf-b6a1fcae443d.png)

**Comment by bhousel** [comment]
The hyperlink is something the openstreetmap-website adds, not iD.  

Anyway hyperlinks won’t work here because they are really template strings that need to be parsed and have the tokens replaced for them to work.

**Comment by boothym** [comment]
Ok thanks, I'll open an issue over at the osm/website repo. Not

**Comment by HolgerJeromin** [comment]
Id could add spaces around the URL it inserts.

**Comment by boothym** [comment]
@bhousel what about adding a space after each semi-colon, as that might prevent the website from including the source following the custom source in the url?

**Comment by bhousel** [comment]
> what about adding a space after each semi-colon, as that might prevent the website from including the source following the custom source in the url?

ok, I did this.
