### ISSUE TITLE
Allow to map man_made=works as an area

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7211]
Currently when I want to add a factory (`man_made=works`) as an area, iD adds `building=yes`. Usually factories are big areas with many buildings and even Wiki says "Draw a polygon around the whole area of the production site and tag accordingly. If you want to get detailed you can also add the single components inside the area and tag them as what they are."

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dworks

**Comment by quincylvania** [comment]
I see your point, but [over 60%](https://taginfo.openstreetmap.org/tags/?key=man_made&value=works#combinations) of `man_made=works` have a `building` tag right now. It makes some sense to look at each individual building that makes something and simply say "this is a factory". The `landuse=industrial` tag is suitable for the factory grounds.

People can write anything on the wiki, but it doesn't mean it works in all situations. If we switch the tag to refer only to the grounds then someone will ask us to switch it back, like the debate over where to put `amenity=school` 🤷‍♂️
