### ISSUE TITLE
Add wheelchair= to entrance=

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7214]
Some entrances to buildings may be adapted for wheelchairs, while others may not.

There are 61,524 uses of `wheelchair=` together with `entrance=` so we should also add it.

How about `ref=`? Some entrances are called "A", "B" etc. and they are not names I think.
`Ref=` is used more ofen (219,017 times) than `name=` (54,671 times).

https://taginfo.openstreetmap.org/keys/entrance#combinations

**Comment by quincylvania** [comment]
@maro-21 Good suggestion! We always want to make it easy to map for accessibility.
