### ISSUE TITLE
Change icon for shop=butcher

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7216]
Could we find a better icon for a butcher shop? This icon doesn't resemble meat for me:) It looks more like a river. What do you think?
https://cdn.jsdelivr.net/gh/openstreetmap/iD@master/svg/fontawesome/fas-bacon.svg

**Comment by SilentSpike** [comment]
🤔 Maybe a butcher's knife? Unsure if it would be very distinguishable at the icon scale though

**Comment by bhousel** [comment]
I think it used to be the maki cow before it got changed to the font awesome bacon.  Anyway we can draw a new one.

**Comment by hikemaniac** [comment]
We could use [fas-drumstick-bite](https://fontawesome.com/icons/drumstick-bite?style=solid). It's not perfect, but it clearly resembles meat.

**Comment by maro-21** [comment]
> We could use [fas-drumstick-bite](https://fontawesome.com/icons/drumstick-bite?style=solid). It's not perfect, but it clearly resembles meat.

This looks like a gnawed chicken :D So I don't think it fits to a shop where raw meat is sold :D
Anyway, we already use this icon for amenity=fast_food+cuisine=chicken.

> I think it used to be the maki cow before it got changed to the font awesome bacon. Anyway we can draw a new one.

Yes, there was maki-slaughterhouse before.

**Comment by quincylvania** [comment]
I just drew this cleaver icon for temaki. It's easier to make tools attractive than it is amorphous meat blobs 😂

<img width="181" alt="Screen Shot 2020-01-08 at 9 18 16 AM" src="https://user-images.githubusercontent.com/2046746/71984972-de087200-31f7-11ea-8a03-6c0343a2769c.png">

**Comment by bhousel** [comment]
temaki-cleaver is so good!   Love the smile on it 😃 

This amorphous meat blob approves..
![dancing_meat](https://user-images.githubusercontent.com/38784/71985708-13fa2600-31f9-11ea-9eca-198cc306ee16.gif)

**Comment by quincylvania** [comment]
> Love the smile on it 

Thanks! That was totally incidental 😆

**Comment by quincylvania** [comment]
<img width="352" alt="Screen Shot 2020-01-08 at 6 24 32 PM" src="https://user-images.githubusercontent.com/2046746/72024775-2c436280-3244-11ea-8274-9e341b2b3dc3.png">

**Comment by maro-21** [comment]
Cool:)
