### ISSUE TITLE
hospice preset

### ISSUE THREAD

**Issue by polarbearing** [openstreetmap/iD#7217]
Currently a Hospice is in data/presets.yaml tagged as
```
4809 healthcare/hospice:
4810 # healthcare=hospice
4811	 name: Hospice
4812# 'terms: terminal,illness'
```
However that is not a value agreed under healthcare. A Hospice is more a social facility comparable to a nursing home with additional grief management towards the relatives. 

It should therefore be tagged as 
```amenity=social_facility + social_facility=hospice```

See https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dhospice

**Comment by quincylvania** [comment]
Hi and welcome, @polarbearing.

While I see your point, hospice facilities provide both medial and social services. I don't think we can just change this since `healthcare=hospice` already has more than [three times as many](https://taginfo.openstreetmap.org/search?q=hospice#values) uses as `social_facility=hospice`.

Ultimately the actual tags are arbitrary as long as mappers can easily add them and consumers can easily parse them. In this case there are three different tags for the same thing, so I'd recommend a tagging proposal and automated edit to consolidate them into one. Then we can support that tag in iD.

**Comment by polarbearing** [comment]
Please re-open.

```healthcare=hospice``` tagging was not discussed anywhere before it had been introduced as a preset here in iD. I had analysed the usage in the data and found that all occurrences  were tagged from iD. Thus when you reason the presence in the preset with the slightly higher usage numbers, which are just caused by this preset, this is kind of a self-fulfilling prophecy, and an abuse if the influence of iD. 

A significant number of facilities called hospice do not provide any nursing or medical services at all, but only outreach to the relatives of the terminally ill person. Those that provide nursing are not medical facilities.

**Comment by quincylvania** [comment]
@polarbearing See #3589 and #4329. The `healthcare` presets were added three years ago with community input and support. iD followed the wiki page as it existed at the time, which included `healthcare=hospice`. [You yourself deleted this value](https://wiki.openstreetmap.org/w/index.php?title=Key%3Ahealthcare&type=revision&diff=1527892&oldid=1527280) after the fact, so please don't act like iD introduced it.

But regardless of how any tag gained traction, the important factor is current usage. Hundreds of popular OSM tags came into use without discussion. As I said in my earlier comment, we can change the hospice tag in iD if there is a formal consensus to do so. We can't make breaking changes like this based on a single argument.

**Comment by polarbearing** [comment]
Thanks for pointing to the PR, so indeed the commit in iD was on 19 Aug 2017, in between of the visibility of the feature on the healthcare=* page (19 May - 25 Nov 2017).

There is a general discussion about such facilities on the tagging list currently, waiting for outcome. But typically there is never a formal consensus about anything ;-)

**Comment by Adamant36** [comment]
@polarbearing what was the outcome of the tagging list discussion?
