### ISSUE TITLE
historic=building together with building=yes

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7219]
Assume we have a building:
```
addr:city=City
addr:housenumber=2
addr:postcode=00000
addr:street=Street
architect=Architect
building=yes
building:levels=2
building:levels:underground=1
building:material=brick
height=8
name=Building A
roof:colour=black
```
When I add `historic=building` to this, the preset changes to Historic Site where I can't edit levels, height, address and other tags in the editor, but only manually in "All tags". I can add only "inscription".

But when the value of `building=` is other than "yes", for example `building=commercial`, the preset doesn't change to Historic Site.
Such behaviour should be the same when the building is `building=yes`.

The other option is to mix fields from Building and Historic Site if it's possible.

But let's give a priority to Building preset than Historic Site if they are together.

**Comment by quincylvania** [comment]
I just added a Historic Building preset to make these easier to deal with.
