### ISSUE TITLE
Edit Pharmacy preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7220]
For the Pharmacy preset currently we have fields:
Name
Operator
Address
Drive-Through
Dispenses Prescriptions

I would like Drive-Through field be replaced with Opening Hours because it's used more often.

`amenity=pharmacy`: 281,788 features
`amenity=pharmacy`+`opening_hours`: 51,023 features
`amenity=pharmacy`+`drive_through`: 8,531 features (where 6,775 is drive_through=no).

I don't how common are pharmacies with drive-through service, but in my country there aren't any. So these 6,775 features with `drive_through=no` come probably from iD's preset because people click there.

**Comment by tas50** [comment]
In the US the majority of pharmacies have a drive-thru. It's pretty important for tagging here.

**Comment by quincylvania** [comment]
I just added the Hours field without removing the Drive-Through field.

**Comment by maro-21** [comment]
That's also a solution, thanks! :)
