### ISSUE TITLE
Edit Biergarten preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7222]
**Remove outdoor_seating:**
`Amenity=biergarten` is itself an outdoor seating so this tag doesn't make sense.

**Remove air_conditioning:**
`amenity=biergarten`+`air_conditioning`: 1 feature

**Remove building:**
Although there are 1166 features on OSM `amenity=biergarten`+`building`, I don't understand how can an open-air area be a building or inside a building. One excludes the other.
[Wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbiergarten): "A biergarten is an **open-air** area with benches ..."
See also photos there.

I think features with `amenity=biergarten`+`building` can come from people who confused biergarten with a pub.

**Add cuisine to More Fields.**
`amenity=biergarten`+`cuisine`: 276 features

`amenity=biergarten`: 10132 features
`amenity=biergarten`+`building`: 1166
`amenity=biergarten`+`outdoor_seating`: 546
`amenity=biergarten`+`cuisine`: 276
`amenity=biergarten`+`air_conditioning`: 1

**Comment by tas50** [comment]
I would suspect a lot of those biergarten tags on buildings are in the US. It's pretty common to have indoor shared table seating pubs with German beer here. People in the US would consider that to be a biergarten even if it doesn't strictly meet the guidelines of the wiki.

**Comment by quincylvania** [comment]
@maro-21 The extra fields are there to accommodate biergarten variations that may exist around the world. In the US, for example, alcohol generally cannot be consumed in public spaces, so biergartens may indeed be indoor "beer halls" or be covered by a `building=roof`.

That said, I'm okay with moving the Building field to `moreFields`.

**Comment by maro-21** [comment]
What about removing outdoor_seating?

**Comment by quincylvania** [comment]
> What about removing outdoor_seating?

I think it's okay for people to add this. Imagine a POI app that has an option to filter by "outside seating". This tag keeps the data model consistent with cafes, restaurants, etc. without making the app developer do more work.

**Comment by maro-21** [comment]
So either every biergarten should have it or none. Because now it looks like a world is divided into biergartens with an outdoor seating and biergartens without an outdoor seating...
