### ISSUE TITLE
Rename Arts and Crafts Store preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7224]
The name of a preset for `shop=craft` "Arts and Crafts Store" suggests the similar to Art Store 
[shop=art](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dart) , that they sell works of art there.

But it is an arts and crafts **supply** store.
[https://wiki.openstreetmap.org/wiki/Tag:shop=craft](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcraft)

**Comment by quincylvania** [comment]
I think "arts and crafts store" is unambiguous in North American English. Adding "supply" would be okay but unnecessarily verbose. I suggest updating the translation in Transifex for any locale where this isn't clear.

**Comment by sun-geo** [comment]
Right, you could manage this using transiflex (for german it seems already done, and is okay)

@quincylvania btw. could you have a look to the icons.
iD seems to use the opposide logic than carto-Rending.

Oh, maybe better I will open a seperate task, see here:

**Comment by maro-21** [comment]
> I think "arts and crafts store" is unambiguous in North American English. Adding "supply" would be okay but unnecessarily verbose. I suggest updating the translation in Transifex for any locale where this isn't clear.

If it's understandable and unambigious in English - ok :)
I understood this as "a store where you can buy arts and crafts". It was even translated in that way by other Polish translator and such wrong translated preset was for four years... I corrected it eight months ago, so now it's ok.

**Comment by quincylvania** [comment]
@maro-21 Yeah English can be confusing and translations are tricky! Thanks for noticing and fixing this.
