### ISSUE TITLE
Add tooltip to "I would like someone to review my edits"

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7227]
While checking the openstreetmap chat (on discord), I noticed a surprising amount of people that didn't actually know what the "I would like someone to review my edits" checkbox does (on the changeset submitting screen.

So maybe adding some kind of tooltip with an explanation about what exactly it does would be useful.
(Mentioning that it's useful for beginner mappers, but also for any level mapper of they're not a 100% sure about their edit)

**Comment by doublah** [comment]
Maybe as well if a user has gone through the walkthrough in the session we add an explanation of what that option does and recommend the user to try using it.

**Comment by MarrickLip** [comment]
I second this - we should probably make it clear that these changes will go live straight-away.

**Comment by quincylvania** [comment]
There, hopefully this will reduce some confusion. It's tough to get a sufficiently succinct description.

<img width="349" alt="Screen Shot 2020-12-03 at 1 51 33 PM" src="https://user-images.githubusercontent.com/2046746/101074413-ae302e80-356e-11eb-83c0-03784b41b743.png">
