### ISSUE TITLE
icons for shop=art / shop=craft

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7228]
Coming from here https://github.com/openstreetmap/iD/issues/7224

It might be make sense to change a bit these icons.

iD seems to use the opposide logic than carto-Rending.

iD
generic shop icon for `shop=art`
specified icon for `shop=craft` (same as https://wiki.openstreetmap.org/wiki/File:Art-14.svg)

carto
specified icon for `shop=art` (see https://wiki.openstreetmap.org/wiki/File:Art-14.svg)
generic shop icon for `shop=craft` (see https://wiki.openstreetmap.org/wiki/File:Shop-other-16.svg)

So for iD i tend to use for `shop=art` something similar or even the same like https://wiki.openstreetmap.org/wiki/File:Art-14.svg 
But for `shop=craft` maybe something similar like https://wiki.openstreetmap.org/wiki/File:Doityourself-16.svg - or a mix of a tool and a pen?

**Comment by quincylvania** [comment]
Hmm the wiki is clear that `shop=art` is for stores that sell completed pieces. Since a palette is associated with the act of painting itself, I suggest osm-carto reevaluate its icon here. I know it's tricky since there are also `tourism=gallery` and `tourism=artwork` to account for.

**Comment by bhousel** [comment]
some background here #2999

People have changed things around since 2016, but at one time we did want to differentiate between places that display art and places that sell art, and places that sell art supplies.

(Also whatever osm-carto does shoudn't really influence our decision. There is a lot I would change about the osm-carto icons!)

**Comment by sun-geo** [comment]
I agree a palette stands for just a tool to create art/artwork and i agree also to that `shop=art` is for stores that sell completed pieces.
Maybe i was biased from osm-carto icons & for the thinging that a palette icon has something to do with general art objects/galley/artwork which i did connect closer to an entire piece of art.

Also thanks for showing the background in 2999.

One other reason i ask for this, is because i was wondering a bit why `shop=craft` has already a specific icon even by a lower taginfo count and a `shop=art` has higher number but a generic icon ;-)

[shop=art](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dart) items ~ 10000 (https://taginfo.openstreetmap.org/tags/shop=art) (generic icon)
[shop=craft](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcraft) items ~ 7000 (https://taginfo.openstreetmap.org/tags/shop=craft) (specific icon)

Yeah, maybe because its tricky to find differentiation between `shop=art` / `tourism=gallery` / `tourism=artwork`

So than please don't switch the logic to osm-carto, but just add a more specific icon for `shop=craft` once there is a opportuneness for it.

**Comment by bhousel** [comment]
> So than please don't switch the logic to osm-carto, but just add a more specific icon for `shop=craft` once there is a opportuneness for it.

I changed it to use the fas-cut scissors icon:

<img width="300" alt="Screenshot 2020-01-06 16 54 15" src="https://user-images.githubusercontent.com/38784/71851734-2c592c00-30a5-11ea-812b-3402fe2f2bda.png">

**Comment by sun-geo** [comment]
Thank you.

Btw.

> There is a lot I would change about the osm-carto icons!

Which osm-carto icon you would change as a first action? :-)
