### ISSUE TITLE
"Building crosses Building" error

### ISSUE THREAD

**Issue by Fizzie41** [openstreetmap/iD#7230]
Apologies if this has been raised previously, but I can't see any reference to it?

I am frequently getting a "Building crosses Building" error after mapping building with shared / common walls eg https://www.openstreetmap.org/edit#map=20/-27.98013/153.38334

The suggested fix is to mark one of them as higher or lower than the other but they are actually the same height, single-level buildings.

Wouldn't a better fix be to merge them into a common line horizontally, rather than change the vertical height?, although this is what I've done when I've mapped them.

Thanks

**Comment by boothym** [comment]
Your link doesn't show any errors. But if a building shares a wall with another building on the ground, then it should be connected to that building in OSM.

Also, you have building:levels=0 here https://www.openstreetmap.org/way/758469875 - I assume this is meant to be 1 instead as otherwise you're saying the building has no height!

**Comment by Fizzie41** [comment]
Thanks.

This is the one that is apparently causing the error? https://www.openstreetmap.org/way/758470668

I thought that level referred to the number of floors above the ground level eg single story building is 0, two stories is 1 etc?

**Comment by boothym** [comment]
I clicked on that link and edited the map, the error flashed up for a split second then went away...

https://wiki.openstreetmap.org/wiki/Key:building:levels - it's the number of levels above the **actual ground/earth**, not above _ground level_ 😉 

As per the description: "The number of above ground levels in a building (if there's only the ground level, this is 1), not including the levels in the roof (use roof:levels to state the number of roof levels)."

**Comment by maro-21** [comment]
> This is the one that is apparently causing the error? https://www.openstreetmap.org/way/758470668

The building with the number 21 is connected only to a parking lot, but not to the building number 19.
When you click the building number 19, you will see a white dot - it means that this node is not shared with any other feature.
![crossing buildings](https://user-images.githubusercontent.com/57260466/71861743-aca87d00-30f7-11ea-91a9-ca03bed765ea.png)

**Comment by quincylvania** [comment]
@Fizzie41 Yep, it looks like this warning is working as expected but it's difficult to see the issue. #5980 will address this.

**Comment by Fizzie41** [comment]
Thank you!

That explains it (& I've just fixed it), but I don't know how it happened?

I drew the outline for 19, added it's carpark & driveway & saved it.

I then drew 21, starting & finishing with the common wall with 19, which
should have connected the common walls, before adding the carpark?

Anyway, if it happens again, I know what to look for!

Thanks

Graeme

**Comment by Fizzie41** [comment]
On Wed, 8 Jan 2020 at 00:02, Quincy Morgan <notifications@github.com> wrote:

> @Fizzie41 <https://github.com/Fizzie41> Yep, it looks like this warning
> is working as expected but it's difficult to see the issue.
>
Very! :-)

 Thanks

Graeme

>
