### ISSUE TITLE
WRONG: train=yes suggestion at public transport platforms

### ISSUE THREAD

**Issue by mapz-sdu** [openstreetmap/iD#7231]
For almost one year now the OSM database is continuously filled with train=yes tags, where it is completely wrong. All those edits are executed by the iD editor. 

As example see this way: 

https://preview.ideditor.com/master/#background=none&disable_features=boundaries&id=w137701947

This is a platform for trams, no train is going there. 

Instead of adding train=yes automatically it must add one kind of bus/tram/subway/train/...=yes. Adding always train=yes is wrong in many cases.

I suggest to completely delete train=yes from suggestions in iD.

Also see this (german) discussion:

https://forum.openstreetmap.org/viewtopic.php?id=68239

**Comment by quincylvania** [comment]
@mapz-sdu Thanks for your concern. If you've been seeing this issue for a year then I wish you'd spoken up sooner.

Also, while we the may be cultural barrier between us, writing "WRONG" like that is rude. Please try to keep things professional in the future.

**Comment by mapz-sdu** [comment]
Sorry, a rude expression was not intended!

I just found this error 2 weeks ago and corrected some of the wrong tags. The first wrong tagging occured about one year ago.

Thanks for looking after this issue.

**Comment by quincylvania** [comment]
> Sorry, a rude expression was not intended!

@mapz-sdu I was hoping as much! Thanks for reporting and welcome to the repo 👋
