### ISSUE TITLE
Add waterway=tidal_channel preset

### ISSUE THREAD

**Issue by jeisenbe** [openstreetmap/iD#7232]
The feature waterway=tidal_channel has been around for a year now, and usage is up to 2 325 ways. It is documented at https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dtidal_channel - 

"A natural intertidal waterway in mangroves, salt marshes and tidal flats with water flow in the direction of the tide"

These features are also know as a "tidal creek", "pill" or "tidal inlet"

JOSM already supports this feature with a preset.

**Comment by quincylvania** [comment]
@jeisenbe Thanks 👍
