### ISSUE TITLE
Fix Issue suggestion for outdated Railroad switches (and potentially other railroad features)

### ISSUE THREAD

**Issue by sanecito** [openstreetmap/iD#7236]
**Problem:**
Nodes tagged like this:

```
disused=yes
railroad=switch
```

Are being recommended in Id to be changed to
`disused:railroad=yes`

![image](https://user-images.githubusercontent.com/3056597/72038721-99b0bc80-325f-11ea-9d8c-6e1f3dabcdb9.png)

The issue here is that it removes a key identifier (such as it being a switch)

**Solution:**
[Per OSM Wiki](https://wiki.openstreetmap.org/wiki/Tag:railway%3Ddisused), have the add tag instead be `disused:railway=<feature>` such as `disused:railway=switch`. So ultimately it would instead look like:

![image](https://user-images.githubusercontent.com/3056597/72038881-34a99680-3260-11ea-8c21-52296553d52f.png)
Potentially worth fixing for [other railway features](https://wiki.openstreetmap.org/wiki/Key:railway#Other_railways) (e.g. signal) as well if similar Issue suggestion logic applies to them.

**Comment by IgorEliezer** [comment]
> Are being recommended in Id to be changed to
> `disused:railroad=yes`
> The issue here is that it removes a key identifier (such as it being a switch)

It seems it is not limited to switches. Disused train station `disused=yes + railway=station` is being replaced with `disused:railway=yes`.  The railway upgrade fix is not following the [Lifecycle prefix schema](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix).

**Comment by quincylvania** [comment]
Whoops, this was definitely a bug!

@IgorEliezer Sorry for not reading your comment on this closely.

@sanecito Thanks for reporting.
