### ISSUE TITLE
update of 'railway=platform_edge' rendering style

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7238]
I'm happy that there is a rending of `railway=platform_edge`. :-)
It seems the style is the same to `railway=rail` or `railway=xyz`.  (So it's sometimes a bit confusing)

Could you please consider to change it, maybe to a similar rendering which is currently used for `highway=platform`, so maybe using similar color & the same line-width or even a bit thinner.

Example object for `railway=platform_edge`: https://www.openstreetmap.org/edit?way=539877363#map=20/48.96116/2.36822
Example object for `highway=platform`: https://www.openstreetmap.org/edit?way=163986965#map=20/57.68993/11.97311

wiki for `railway=platform_edge`: https://wiki.openstreetmap.org/wiki/Tag:railway=platform%20edge

**Comment by bhousel** [comment]
I don't think we can easily support rendering certain _edges_ differently than other edges on a single feature.. Sorry.

**Comment by k-yle** [comment]
this was fixed in #9142
