### ISSUE TITLE
Preset query for "hours".

### ISSUE THREAD

**Issue by UKChris-osm** [openstreetmap/iD#7240]
Hello all,

I'm very new to the behind the scenes world of OSM, having only gotten into it via the [Name-Suggestion-Index](https://github.com/osmlab/name-suggestion-index/) after I noticed some names I thought would be suggested were missing, and have since learnt more about how the NSI works, and how GitHut is used to build the NSI, and the iD Editor.

In the iD Editor, I have been curious for a little while about the preset for "hours" when adding things like a bank, a cafe or a fast food restaurant, all places which I would think "hours" was an important addition, yet the "hours" input field doesn't appear when adding or editing any of these, and I was curious why this might be?

Is it a value that isn't overly important to OSM as a whole, or maybe considered a little to difficult for some people to edit? Maybe OSM has lots of invalid entries for hours in the database and doesn't want to make it to easy for people to dump any value in? Or Maybe because opening hours can change so often OSM doesn't want to many out of date entries?

Another reason I thought it odd that the iD Editor didn't bring up the "hours" input was that iD does ask if a bank is a "drive-through", which in the UK, is almost always "no", and to me seemed like an odd thing to ask in place of hours of operation, which I would think is highly useful information.

Would love to learn more, so thanks to anyone who can fill me in :)

**Comment by bhousel** [comment]
See #974 for background.. There is an `opening_hours` tag in OSM but the syntax for it is pretty complicated. 

As far as I know, most POI-like presets in iD already _do_ show the Hours field.  Though I just clicked on a bank and a few others and I don't see it now. 🤷‍♂
