### ISSUE TITLE
Validator: oneway & direction tagging

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7241]
It seems if there is an available `oneway=yes` tagging for a `highway `osm-way object, then the direction parameters `:forward` and `:backward` are dispensable?

Example object with `oneway=yes` & `"destination:forward"` tags:
- https://www.openstreetmap.org/way/528270430
- https://www.openstreetmap.org/edit?way=528270430#map=19/33.77959/-117.88326

Btw, i just checked the josm (validator) behavior: There you can see this warning message: _"suspicious tag combination - `oneway=yes` togehter with `destination:forward`"_

**Comment by SilentSpike** [comment]
Does iD want to have validations for tags that are only editable through the raw tag editor? Or should they be limited to only tags controlled with fields?

**Comment by quincylvania** [comment]
> Does iD want to have validations for tags that are only editable through the raw tag editor? Or should they be limited to only tags controlled with fields?

@SilentSpike Most tag upgrades aren't tied to the preset or fields, though many coincide. In this case iD supports `destination` but not `destination:forward` on motorway links so an upgrade would help.

**Comment by maro-21** [comment]
1. The message in this case is inappropriate: "{feature} has outdated tags" - they are not outdated...
2. What about such situation?
```
highway=primary
oneway=yes
destination:forward=Somewhere
destination:backward=Somewhere
destination:lanes:forward=something
destination:lanes:backward=something
turn:lanes:forward=something
turn:lanes:backward=something
```

It will change only `destination:forward`.

But how iD knows that it should change `destination:forward` to `destination`? Maybe `oneway=yes` is wrong here.

**Comment by bhousel** [comment]
@maro-21 I really think this validation is being overly nitpicky.

Also, the `oneway` tag is just for vehicles, so if you see `:backward` tags on a way with a `oneway`, it could just mean that they are for pedestrians or cyclists or a contraflow bus lane?.  It's definitely ok to warn about this, but people can always invent some situation where a road has a `oneway` but there are signs or conditions affecting the opposite way.

My preference would be to avoid trying to infer anything about the `:forward` and `:backward` tags.  Or issue warnings but not offer to remove or change tags.

**Comment by quincylvania** [comment]
> My preference would be to avoid trying to infer anything about the :forward and :backward tags. 

@bhousel Okay, this sounds fine. This is pretty advanced mapping anyway.
