### ISSUE TITLE
Add amenity=lavoir preset

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7243]
Hi there.
I don't know if this is the right place to ask for this, so forgive me if it's not and please point me to the right place to do it.

The tag lavoir is very used in Portugal and other European countries. 
I would like to suggest to add it's own feature in iD.
Wiki page: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlavoir

Regards.

**Comment by sun-geo** [comment]
Interesting request

A bit offtopic, @AntMadeira
Is the picture from the corresponding proposal: https://wiki.openstreetmap.org/wiki/Proposed_features/lavoir
https://wiki.openstreetmap.org/wiki/File:VaprioAdda_Lavatoio.JPG
showing a object of `amenity=lavoir` or even actualy object of `disused:amenity=lavoir` or `history=lavoir` ?

**Comment by AntMadeira** [comment]
Hi, sun-geo. 
Thanks for your reply.

That image is clearly from a lavoir which is not used anymore, but to me there are only two kinds of lavoirs: those with running water and usable and those without running water which are only historic buildings. Here in Portugal, is rare a lavoir not having running water and most of them are still used.

**Comment by quincylvania** [comment]
@AntMadeira Welcome and thanks for the suggestion 👋

This is indeed the right place to propose iD feature types. I just added Lavoir for you.

**Comment by AntMadeira** [comment]
Thank you, Quincy!
