### ISSUE TITLE
Tooltips are not working properly

### ISSUE THREAD

**Issue by abhisheknaiidu** [openstreetmap/iD#7245]
When loading the page, the tooltips are not working as it was assigned. Its working fine after we are hovering again on that icon. I mean at first hover, its not working properly but if we hover that icon again then it starts working fine.

![iD](https://user-images.githubusercontent.com/55599878/72439778-88bafa80-37cd-11ea-8f75-9b1525e1461e.png)

**Comment by quincylvania** [comment]
@abhisheknaiidu Thanks for reporting, but I'm closing this since it only appears to affect v3 and that code won't necessarily be shipped in its current form.
