### ISSUE TITLE
When multiple objects selected, tabbing to enter a new value is annoying [preview]

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7248]
Hi,

I'm using the preview version of iD and something that I find quite annoying is when you have multiple objects selected and you get the view to show all similar tags and such; on that view if you create a new tag and then try to instinctively press TAB to switch to the next field and actually enter the data for that tag, it bumps the newly created tag to whever it should be according to the alphabet. But the text cursor should end up in the right field but it doesn't. The focus is lost and when you start typing you start executing shortcuts for mapping.

(also, being able to just paste something like this and have it automatically put it in the right fields (while in that view) would be nice:
```
access=destination
foot=yes
bicycle=yes
agricultural=yes
maxspeed=30
emergency=yes
```
(I don't see an existing issue for this, but if there isn't, just tell me and I'll create a new one)

EDIT: https://whatsmybrowser.org/b/77FFGN3

**Comment by bhousel** [comment]
> if you create a new tag and then try to instinctively press TAB to switch to the next field and actually enter the data for that tag, it bumps the newly created tag to whever it should be according to the alphabet. But the text cursor should end up in the right field but it doesn't.

This might be  #6046

> (also, being able to just paste something like this and have it automatically put it in the right fields (while in that view) would be nice:

iD has a text view for the tag editor where you can copy and paste tag pairs like that.. see example:

![text tag editing](https://user-images.githubusercontent.com/38784/72454136-4c1bde80-378e-11ea-8a9c-7016677aa7c3.gif)

**Comment by thibaultmol** [comment]
I guess it's similar to that bug maybe?
Just to clarify I'm talking about this view:
![image](https://user-images.githubusercontent.com/1010226/72454773-cc0f6c00-37c1-11ea-9cbd-7dce807d5fce.png)
So when I click on that + to add a new tag. Type the name, then press TAB, it should just put my text cursor in the right side of the table but it doesn't.

Also, I know it has that 'raw text' view, and I use that a lot. But that mode isn't available when multiple objects are selected in the preview (like on my above screenshot)

**Comment by bhousel** [comment]
Ok thanks for the screenshot, that helps a lot. 👍 
It should have the text/grid toggle.

**Comment by quincylvania** [comment]
So in #7262 I brought multiselection tag editing to the `2.x` branch, fixed this bug, and added support for the text tag editor too.
