### ISSUE TITLE
newline in fields 

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7249]
Hi,

So I've had many moments where I accidentally put text on a new line within a tag. But technically that isn't supported by osm.

So while I guess it's good that we're not blocked from entering it (for the people that do it regardless, or when osm might change that in the future).
Having atleast a warning popup saying that it's not recommended would help. 

Because I've had a lot of moments where I'll submit a changeset and then 24h have Osmose yelling at me to not put newline chars in my tags

Cheers,
Thibault

**Comment by bhousel** [comment]
> So I've had many moments where I accidentally put text on a new line within a tag. But technically that isn't supported by osm.

Newlines are supported in some textlike fields like `inscription` or `fixme` etc.  I think they are allowed in any tag, just discouraged for most of them.

> Because I've had a lot of moments where I'll submit a changeset and then 24h have Osmose yelling at me to not put newline chars in my tags

That's.. everything working as expected right?  People make mistakes and Osmose flags them?   iD is not going to know what all the tags are where newlines are allowed or not.

**Comment by thibaultmol** [comment]
I didn't know that newlines were allowed on fixme's.
I put them on a note= and that cause osmose errors.

But yeah, I figured if iD could warm people about it on the tags that aren't supposed to use them, that would be less cumbersome

**Comment by bhousel** [comment]
> I didn't know that newlines were allowed on fixme's.
> I put them on a note= and that cause osmose errors.
> But yeah, I figured if iD could warm people about it on the tags that aren't supposed to use them, that would be less cumbersome

I agree!  #2836 is where we are tracking the idea of having some kind of highlighting for fields with suspicious values in them..

But in this case, I think it's just Osmose showing a false error.  It's ok to have newlines in notes.
