### ISSUE TITLE
iD not detecting duplicate nodes?

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7251]
Hi,

So I was using the preview yesterday to make a changeset to a schoolgrounds. But I had to remove some nodes so what I did was select the way of the schoolgrounds, press d (to disconnect all the nodes). But I didn't merge the nodes that remained back with the others. And so Osmose now looks like this:
![image](https://user-images.githubusercontent.com/1010226/72467469-3aacf380-37db-11ea-97db-10ab1b4e88a4.png)
The weird thing is though that iD isn't throwing any error in the validation regarding these duplicate nodes. So merging them isn't really possible (easily)

This is the changeset where I made the edit that caused it: https://www.openstreetmap.org/changeset/79574237

location in iD:
https://preview.ideditor.com/master/#id=w323438062&map=19.63/51.04198/3.39335

Cheers,

**Comment by quincylvania** [comment]
@thibaultmol Yes, this seems to be working as intended. iD warns about very close nodes that are both the same way or are both standalone points, but not any two nodes. There are various cases where two nodes in the sample place could be okay, like a boundary overlapping a building. It's ultimately up to the mapper to decide this, and whether disconnecting the entire way is suitable. You can alternatively use the lasso tool to select just a few points to disconnect.

**Comment by thibaultmol** [comment]
👍 I'll keep that in mind for the future.
 What would be the best way to fix something like this? Because all I know to combine the nodes in this case is to drag it away and then drag it back so it snaps into place? or is them some better way to do it? (is good to know if I see someone make the same mistake in the future)

**Comment by quincylvania** [comment]
> Because all I know to combine the nodes in this case is to drag it away and then drag it back so it snaps into place?

Yeah this is how I would do it now. We're considering #6913 to make reconnection easier.
