### ISSUE TITLE
Building part partial fill narrower

### ISSUE THREAD

**Issue by IgorEliezer** [openstreetmap/iD#7257]
Please, could you make the building part fill a bit narrower? Perhaps, slightly narrower than the half width of building outline fill (in red).

![image](https://user-images.githubusercontent.com/4673289/72637646-875e0f00-3940-11ea-9eb6-b5e363292338.png)
https://www.openstreetmap.org/changeset/79578964

Today I had to fix a changetset of a new mapper who wanted to reach the main building outline to add extra info and mistakenly deleted the building parts thinking they were separated buildings.

Regards,

Igor

**Comment by quincylvania** [comment]
@IgorEliezer Hmm the issue is that we actually have three levels of nested areas: indoor rooms are narrower than building parts. We need to leave room these.

We're tracking #6204 to render building parts differently plus #2225 and #5520 to make selecting overlapping areas easier. Those should address the underlying concern, no?

**Comment by quincylvania** [comment]
Here are the three levels together.

<img width="238" alt="Screen Shot 2020-01-17 at 3 07 13 PM" src="https://user-images.githubusercontent.com/2046746/72642747-19fbaf80-393b-11ea-9639-2749e7e5e66c.png">

**Comment by IgorEliezer** [comment]
> Hmm the issue is that we actually have three levels of nested areas: indoor rooms are narrower than building parts.

I didn't know there were 3 levels of building fill. As you said [here](https://github.com/openstreetmap/iD/issues/6204#issuecomment-491811958), using a pattern can be a good solution.

If you judge that this issue overlaps the other issues, feel free to close it. :+1:

**Comment by quincylvania** [comment]
@IgorEliezer Great, thanks for understanding! I agree we should make area selection better in iD.
