### ISSUE TITLE
Replace collection_times by opening_hours in recycling container presets

### ISSUE THREAD

**Issue by Klumbumbus** [openstreetmap/iD#7259]
For recycling containers opening_hours is the important key (=when you are allowed to enter trash to containers) and not collection_times (=when the operator empties the container).
This is different from e.g. post boxes where it is the other way round.

The current preset can lead users to accidentally tag "throw in times" with the key collection_times.

See also https://josm.openstreetmap.de/ticket/18374

**Comment by bhousel** [comment]
Sorry but I disagree.. Collection Times is more important for recycling containers.

Opening Hours (when you are allowed to access the container) is less important. Most public recycling containers are just sitting out and can be accessed whenever.   

I think it does work pretty similar to post boxes - there isn't any real difference.

**Comment by Klumbumbus** [comment]
Why would it be of interest for anyone when the operator empties the container? (Except for the operator itself, which much likely stores its data internally, not in OSM.)

At least recycling containers for glass bottles in Germany usually all have opening hours. There is no physical barrier, but it is forbidden by sign to throw in bottles out of the opening hours. This is because of noise protection for the nearby residents.

**Comment by bhousel** [comment]
> At least recycling containers for glass bottles in Germany usually all have opening hours. There is no physical barrier, but it is forbidden by sign to throw in bottles out of the opening hours. This is because of noise protection for the nearby residents.

That's interesting - I guess we can probably show both fields..

**Comment by Klumbumbus** [comment]
>show both fields

That would be fine.
