### ISSUE TITLE
Ability to sort/filter aerial imagery by date/resolution.

### ISSUE THREAD

**Issue by doublah** [openstreetmap/iD#7264]
Going through imagery to try and find the best and most recent for a new area is a long and annoying process (which also spams changeset tags), a way to sort/filter imagery would help.

**Comment by bhousel** [comment]
Oh yeah, since we don't really have all the imagery dates or resolutions available, I don't see this as a thing that's possible today.. But maybe someday?

A long time ago I wrote this:  https://github.com/osmlab/osm-planning/issues/18
