### ISSUE TITLE
Canceling dropdown via outside click adds incorrect default value

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#7265]
* Add point with Information Board preset.
* Click Board Type dropdown
* Click outside the dropdown
* Observe `board_type=yes` added to tags

![type](https://user-images.githubusercontent.com/3857299/72662434-bd0e0100-39ef-11ea-885a-ebd938a61cba.gif)

I briefly checked other dropdowns, but didn't see the same behaviour elsewhere.

2.17.1, Firefox 72.0.1 (64-bit), Win 10 Pro 64

**Comment by quincylvania** [comment]
Thanks for reporting, @RudyTheDev.

This is a little complicated, but basically we have `typeCombo` fields for presets matching wildcard tags like `amenity=*`. These don't show a `yes` value. The `board_type` field should have been a generic `combo` field instead of this special type.
