### ISSUE TITLE
Show what a feature is on mouseover

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7266]
It would be very nice if I could see what a feature is just on mouseover, IMHO. Sometimes I wonder if a road is tagged as the correct type of road, or stuff like that, but I have to click on it and wait a second for the Inspecting box to show up.

Maybe any fixme tag could also be shown on mouseover? Both type of feature and any fixme tags could for example be shown in a box straight below the Mapping box in the top left corner? Or just where the cursor is.

**Comment by quincylvania** [comment]
@forteller This preview-on-hover feature has been in iD for years but it's not present in the v3 branch right now. We're going to add it back before shipping the new UI. I'll leave this open so we can track it.

**Comment by quincylvania** [comment]
Actually I'm going to close this since we're basically just going to use the 2.x behavior instead of writing a new implementation.
