### ISSUE TITLE
Ask to zoom in to last location

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7267]
(I realized after writing this that this will ever only be needed in the preview website, so I'm not sure if you will think it's worth the effort. I'll post it in case you do, but I won't mind if you don't and close it :))

When you come back to iD after having saved your previous edits you are presented with the whole world. If you want to pick up roughly on the same place you last left off, you have to manually zoom in to that place. 

And honestly, how often do editors want to edit somewhere on the other side of the world as last time? :) This means that a lot of people spends extra seconds finding the correct place instead of mapping.

I suggest adding a way to get sent back to your last location.

Two possible ways this could be done:

1. Add an option in the greeter in the top left corner. "Click here to go back to your last location"
2. If you have not yet panned or zoomed the map at all, make the "Zoom in to edit" box take you back to your last location. This should probably be reflected in the text on the box. Something like "Go back to your last location to edit" first, then change the text to the regular "Zoom in to edit" if the user starts changing the view of the map.

**Comment by bhousel** [comment]
> (I realized after writing this that this will ever only be needed in the preview website, so I'm not sure if you will think it's worth the effort. I'll post it in case you do, but I won't mind if you don't and close it :))

Thanks for understanding..
