### ISSUE TITLE
Help with formating on dates

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7270]
Adding a date in a "Last checked Date" field I had to open the wiki to figure out which format I should write it in. It would be great if the info was there in some way, preferably as a grey "YYYY-MM-DD" in the text box, instead of "Unknown".

If we could also have a calendar drop down from the text box, that would be great :)

**Comment by maro-21** [comment]
Instead of opening the wiki you can edit https://wiki.openstreetmap.org/wiki/Item:Q1159 and change to for example "Date of latest review of the data using the format YYYY-MM-DD".

But yes, I agree that we should have a placeholder for this.

**Comment by forteller** [comment]
Ok, I edited the description there, so now I wait and see if it works. Thanks :)

But yeah, still…

**Comment by quincylvania** [comment]
Okay, I did this. It doesn't look especially amazing but I agree "Unknown" isn't helpful. 

<img width="373" alt="image" src="https://user-images.githubusercontent.com/2046746/74466375-edf52080-4e4b-11ea-917a-0f6cc37097e6.png">

**Comment by forteller** [comment]
It looks exactly as it should. Thanks! :)
