### ISSUE TITLE
Add historic=pillory preset

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7274]
Hi there.

In Portugal, there are thousands of pillorys like [this](https://commons.wikimedia.org/wiki/File:Pelourinho_Sardoal.jpg).
They're important historic and touristic monuments and I think this is would be a good preset to add to iD, and a very necessary one for many mappers of South of Europe.

Regards!

**Comment by animesh-007** [comment]
I would like to work on it.

**Comment by animesh-007** [comment]
Hi, I had few queries regarding the issue i.e, Do you need pillory as a suggestion in the suggestion list??

**Comment by AntMadeira** [comment]
> 
> 
> Hi, I had few queries regarding the issue i.e, Do you need pillory as a suggestion in the suggestion list??

Is this question for me? If so, can you explain better?

**Comment by animesh-007** [comment]
Do you want Pillory to come as a suggestion here?

![image](https://user-images.githubusercontent.com/53366877/73387551-c011c700-42f6-11ea-8122-77e3ea9aeb45.png)

**Comment by AntMadeira** [comment]
Yes, that's the scope of this request: add it to presets so that it can be searchable on iD.

**Comment by animesh-007** [comment]
Hi, Thank you for allowing me to work on this issue. I was able to solve the issue. Also, I have attached a screenshot of my work. I wanted to ask what would you suggest the branch commit name and it would be great if you could let me know if there are any further modification needed with the current change.
<img width="369" alt="Screen Shot 2020-01-31 at 7 05 39 PM" src="https://user-images.githubusercontent.com/53366877/73543805-c7071980-445d-11ea-8d79-3c84a3cc239a.png">

**Comment by AntMadeira** [comment]
I'm the one that has to thank you, not the other way around. ;)
If iD has included pillory into presets, that's perfect.

I would suggest a different image to the pillory, since it has a very peculiar shape.
You can check here for some inspiration:
https://es.wikipedia.org/wiki/Rollo_(administraci%C3%B3n)
https://pt.wikipedia.org/wiki/Pelourinho

**Comment by animesh-007** [comment]
I have updated the icon, Does it looks fine now??
<img width="374" alt="Screen Shot 2020-01-31 at 11 15 14 PM" src="https://user-images.githubusercontent.com/53366877/73562061-57eeec80-4480-11ea-8cf0-eeb249a1c066.png">

**Comment by bhousel** [comment]
For the icon, let's just use the generic `maki-star` for now, like other generic tourist attractions, and open an issue in https://github.com/ideditor/temaki for @quincylvania or me to draw a better one.

**Comment by bhousel** [comment]
> I would suggest a different image to the pillory, since it has a very peculiar shape.
> You can check here for some inspiration:
> https://es.wikipedia.org/wiki/Rollo_(administraci%C3%B3n)
> https://pt.wikipedia.org/wiki/Pelourinho

@AntMadeira - I looked at these images on these links and it's definitely not what I was expecting.

Aren't most pillories like this thing where they lock you in so people can throw vegetables at your face? 

![pillory](https://user-images.githubusercontent.com/38784/73564217-12ed9a80-442d-11ea-9b68-1ed63db0a5b4.jpg)

**Comment by bhousel** [comment]
Actually let's just leave it how it is with the monument icon.  That's fine too.. @animesh-007 can you send the PR?

**Comment by animesh-007** [comment]
Thank you for the suggestions, I have already made a PR and here's the link to it #7310 
Hope to hear your comments soon 😃

**Comment by AntMadeira** [comment]
> 
> 
> For the icon, let's just use the generic `maki-star` for now, like other generic tourist attractions, and open an issue in https://github.com/ideditor/temaki for @quincylvania or me to draw a better one.

A pillory is not a tourist attraction per se, it's more of a historic monument (almost every one of them are national monuments in Portugal) That image that you show above is not a pillory. It could be a pillory in the Middle Ages in central Europe, but they were provisory. These pillories are permanent (they existed in the middle of towns) and were made from various kinds of stone, granite, marble, sandstone, etc. Please, check Wikipedia or OSM wiki to see more adequate images.
Since this is such a peculiar monument (there's no other similar) it could have something different from a tower image, but that's not the most important. The preset is already in place, and that's the most important thing.

**Comment by AntMadeira** [comment]
> 
> 
> Thank you for the suggestions, I have already made a PR and here's the link to it #7310
> Hope to hear your comments soon 😃

That image seems ok. Thank you!
