### ISSUE TITLE
Move disable/enable all

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7275]
The disable all / enable all links require you to scroll all the way to the bottom of the map data panel - could these be moved up to the top of that dropdown instead?
![Untitled-1](https://user-images.githubusercontent.com/16965772/72743419-8ed12280-3ba3-11ea-87bc-235d89dd2f78.jpg)

**Comment by animesh-007** [comment]
I would like to work on this.

**Comment by animesh-007** [comment]
Hi, Thank you for allowing me to work on this issue. I was able to solve the issue. Also, I have attached a screenshot of my work. I wanted to ask what would you suggest the branch commit name and it would be great if you could let me know if there are any further modification needed with the current change.
<img width="355" alt="Screen Shot 2020-01-23 at 10 25 27 PM" src="https://user-images.githubusercontent.com/53366877/73008042-b0483d80-3e33-11ea-8c97-068a6815ac9e.png">

**Comment by bhousel** [comment]
I took a look a this, and I think it looks pretty bad when moved up to the top.  Let's leave where it is..

**Comment by boothym** [comment]
@bhousel I think in this case "looking bad" is the price to pay for having a more user friendly UI. 😉 

If I want to show only buildings or roads then having to scroll down to the bottom to click "disable all" first is not user friendly. And when I want to enable all the features again, I need to scroll down to the bottom. 

Fixing this would be a nice time saver, and would actually made the disable/enable feature more visible so new users will see it!

**Comment by quincylvania** [comment]
@boothym I get your point, but it's not really user-friendly to have the UI look broken even if it saves time for a few people. We could theoretically come up with a more elegant solution but we have limited resources and are prioritizing elsewhere right now 🤷‍♂️
