### ISSUE TITLE
Support fee tag for ATMs

### ISSUE THREAD

**Issue by doublah** [openstreetmap/iD#7279]
Currently adding fee values is more difficult than it should be with iD, and ATMs charging fees are common.

https://wiki.openstreetmap.org/wiki/Tag:amenity=atm

**Comment by bhousel** [comment]
I don't think iD can easily support a tag that works sometimes like a checkbox and sometimes like a number. 

Would you be ok if iD supported the tagging documented here:
https://wiki.openstreetmap.org/wiki/Key:fee
where `fee=yes/no` and `charge=*` or `fee:amount=*` contains the value?

It is sad (to me) that the guidance on the atm wiki page differs from the fee wiki page, and it would be nice if the community were to resolve that inconsistency.

**Comment by bhousel** [comment]
I think i'm just going to close all the "tag makes no sense to me" issues today.  There are too many.  

We've strayed pretty far from iD's original mission of making mapping fun and easy for everyone.
