### ISSUE TITLE
transifex location of text strings

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7280]
Where in transifex can be found the location of _"Tools"_ and _"Geometries"_ text strings?

![image](https://user-images.githubusercontent.com/47290585/72912209-95929d80-3d3b-11ea-82cb-39621ffa2b67.png)

**Comment by manfredbrandl** [comment]
There are some more text missing from transifex:
![image](https://user-images.githubusercontent.com/5360273/72916027-87e01680-3d41-11ea-98e5-4dcd015b8756.png)
![image](https://user-images.githubusercontent.com/5360273/72916075-9fb79a80-3d41-11ea-8a0f-c51ba1b6337c.png)

**Comment by quincylvania** [comment]
Strings specific to the `master` branch haven't been made translatable yet since they're very much subject to change…

**Comment by sun-geo** [comment]
Okay, thanks for checking. So we just wait a bit until corresponding dependencies are done.

**Comment by quincylvania** [comment]
> Okay, thanks for checking. So we just wait a bit until corresponding dependencies are done.

Yes, there will be plenty of time to translate the new strings before we ship them. Thanks for noticing 👍
