### ISSUE TITLE
Add deprecation for bicycle:oneway => oneway:bicycle

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#7281]
This seems to be a clear miss-tagging IMO:
https://taginfo.openstreetmap.org/keys/bicycle%3Aoneway (7440) should be https://taginfo.openstreetmap.org/keys/oneway%3Abicycle (107 0550)

I suggest adding a deprecation in iD.

I also added a redirect in the wiki https://wiki.openstreetmap.org/w/index.php?title=Key:bicycle:oneway&redirect=no but I cannot remember if this is enough to update the tag-description-bot …

**Comment by tordans** [comment]
Out of curiosity: Looking at the taginfo list again, I wonder if there are more tags like this, that should be deprecated.  There are a few that don't follow the same pattern or are not documented.

List: https://taginfo.openstreetmap.org/search?q=:oneway
(vs. https://taginfo.openstreetmap.org/search?q=oneway%3A)

A few examples with comment. For all of those: I don't see a clear better option, so the one deprecation above seems to be the only clear one.

- 11 579 piste:oneway - does not follow the pattern, but https://taginfo.openstreetmap.org/search?q=oneway%3Apiste does not exist and https://wiki.openstreetmap.org/wiki/Piste_Maps#Other_features recommends it this way. No better option here IMO.
- 9 772 cycleway:right:oneway 
  4 409 cycleway:left:oneway
  157 cycleway:both:oneway – I could not find a tag to represent the direction in the `oneway:<specifier>`-pattern. No better option here IMO.
- 642 sidewalk:right:oneway
  416 sidewalk:left:oneway – this looks controversial at https://wiki.openstreetmap.org/wiki/Key:oneway#Pedestrians. There is foot:backward=no and such but those are used less (https://taginfo.openstreetmap.org/search?q=foot%3A). No better option here IMO.
- 621 cycleway:oneway – this looks like it should be oneway:bicycle, but without checking a few examples I am not sure. The save bet is to not touch it IMO.
- 153 mtb:oneway – the other tag exists https://taginfo.openstreetmap.org/search?q=oneway%3Amtb, but with less usage (135). However, the oneway-wiki recommends the `oneway:<specifier>` system (https://wiki.openstreetmap.org/wiki/Key:oneway#Sub_keys_.2F_exceptions).  The save bet is to not touch it IMO.

**Comment by matkoniecz** [comment]
I opened an equivalent JOSM ticket - see https://josm.openstreetmap.de/ticket/18603#ticket
