### ISSUE TITLE
Pasting an OSM link in the search bar should detect the way/node/rel in that url

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7282]
Being able to just paste an osm link and have it realize what it means would be convenient 
For example "https://www.openstreetmap.org/way/323660491" should just show that way
If someone sends you a link, you wouldn't have to extract the id from the url. You can just paste the whole thing in the search box from your clipboard

**Comment by boothym** [comment]
You can already paste in w/323660491 and iD recognises it as a way (same with n or r). Perhaps iD could strip the OSM url and then the full word "way/node/relation" could also be detected?

As an aside, it would be good if "note/123456789" was recognised by iD so you could zoom to a particular note.

**Comment by kymckay** [comment]
Resolved in #7775
