### ISSUE TITLE
Add deprecation for building:height => height

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7285]
https://taginfo.openstreetmap.org/keys/building%3Aheight#overview

https://wiki.openstreetmap.org/w/index.php?title=Key:building:height&redirect=no

Is used on `building=*` and `building:part=*` where `height` tag would be perfectly fine and is a pointless duplicate.

And it is yet another thing that need to be handled during data processing (see for example https://github.com/westnordost/StreetComplete/commit/e4897e9bfd46801ebae6ba080974ff857bc647cb#diff-c3d4cf73bd9fd9dabd89d5ed73b9995bR21 ), without any benefit whatsoever.

JOSM issue: https://josm.openstreetmap.de/ticket/18605#ticket

**Comment by westnordost** [comment]
There is also [building:min_height](https://taginfo.openstreetmap.org/keys/building%3Amin_height) (800 uses).

**Comment by 1ec5** [comment]
Note that `min_height` is one of the [homonymous keys](https://wiki.openstreetmap.org/wiki/Homonymous_keys), having different interpretations depending on the feature.

**Comment by westnordost** [comment]
Where did you get this interpretation (“minimum height required to ride” ) of `min_height` from? I can't find anything related on the attraction wiki page.

**Comment by 1ec5** [comment]
It’s documented that way on the [`min_height`](https://wiki.openstreetmap.org/wiki/Key:min_height) page itself due to existing usage.

**Comment by westnordost** [comment]
Ah there, ok
