### ISSUE TITLE
Monastery preset self-conflicting

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#7287]
The monastery preset has the description of "Monastery grounds", yet the icon background is that for a building preset, and indeed a building value is added to the area when the preset is applied.
I think the [wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmonastery) does in fact prescribe that the tag is used on the grounds. (of course, this being osm, the first paragraph makes it sound like you can tag a building as well)

now in the correct repo!

**Comment by HolgerJeromin** [comment]
Same with some other presets. 
School, hospital, healthcare=rehabilitation

**Comment by quincylvania** [comment]
> Same with some other presets.
> School, hospital, healthcare=rehabilitation

@HolgerJeromin No, the Hospital Grounds and School Grounds presets are consistent since they don't add building tags.
