### ISSUE TITLE
building=unclassified/unidentified/undefined/unknown/true/Y/* to building=yes

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7288]
There is no value whatsoever in using `building=unknown` instead of `building=yes`. The meaning is the same, but this tag is harder to support by various tools. For example StreetComplete will ask about building type for `building=yes`, it will not happen with `building=unknown`. 

https://josm.openstreetmap.de/ticket/17786#comment:4 and https://josm.openstreetmap.de/ticket/18612#ticket are about a related JOSM validation rule

The same applies to `building=unclassified`, `building=unidentified`, `building=undefined`, `building=unknown`, `building=true`, `building=Y`, `building=*` (`*` treated as a text string with just this character, not in "any value" meaning). This values are listed in order of popularity in the OSM database.

See https://wiki.openstreetmap.org/wiki/Tag:building%3Dunclassified for OSM Wiki docs, other tags have very similar pages listed in "see also"

I tested using https://preview.ideditor.com/master/#background=Bing&disable_features=boundaries&map=19.93/28.53689/41.54163 that iD has no such rule currently

**Comment by bhousel** [comment]
OSM is full of weird tags.  Why should iD and JOSM do something special with these ones?

**Comment by bhousel** [comment]
I mean look.. [building=y](https://taginfo.openstreetmap.org/tags/building=y) is used 369 times.  If you don't like this tag, just change them all to `yes` with overpass and level0.  I could have done it in less time than it took to write this comment.

Why burden editor developers with inconsequential stuff like this.

**Comment by matkoniecz** [comment]
Mentioning rarely used values was probably a mistake.

But `building=unclassified` is used over 3k times.

> OSM is full of weird tags. Why should iD and JOSM do something special with these ones?

To reduce number of weird tags duplicating more popular and less weird tags.

**Comment by bhousel** [comment]
Sorry but I'm going to close this. 
If we make stuff like this in scope for iD, our file of deprecation rules will fill up forever.  There are millions of tags in OSM.

If the tag really is documented as having a value like `building=*` then really anything can go there. 

There is no complete list of "accepted" values.. People really have to stop thinking about OSM this way.
