### ISSUE TITLE
"amenity=place_of_worship" shouldn't get priority over " historic=wayside_shrine"

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7292]
I noticed when adding the `amenity=place_of_worship` tag that it causes the text at the top to change from "Wayside shrine" to "Chrisitian Church".
Even though the shrine is the more accurate title for such a node (since it's not a church).
![Screenshot 2020-01-27 at 12 16 11 AM ](https://user-images.githubusercontent.com/1010226/73143528-58ac0b00-409b-11ea-96f3-dd66a7ee9cb3.png)

**Comment by bhousel** [comment]
Yeah, these tags just can't go together like this.  It's just as much of a "Christian Church" as it is a "Wayside Shrine".   The software can't _just know_ to prioritize one tag over another when you stack them all up on a single feature.

**Comment by thibaultmol** [comment]
I mean. Isn't it fair that when it's tagged with wayside_shrine that it's that and not a church. 
A church is a proper building that can hold atleast 20-30+ people.
A wayside_shrine is just a small thing like this:
![image](https://user-images.githubusercontent.com/1010226/73181190-0b6d7f00-4117-11ea-9684-9474f223935e.png)

**Comment by bhousel** [comment]
> I mean. Isn't it fair that when it's tagged with wayside_shrine that it's that and not a church.
> A church is a proper building that can hold atleast 20-30+ people.
> A wayside_shrine is just a small thing like this:

You can't put `amenity=place_of_worship` here.  That tag is really for large churchlike things.  They will render like large churchlike things.

**Comment by thibaultmol** [comment]
Yeah, you're right. "A place where religious services are conducted"
Somehow read the wiki pages, but didn't look at the simple description of the tag on the right.
Sorry for that, thanks for pointing it out 👍

**Comment by bhousel** [comment]
> Sorry for that, thanks for pointing it out

No apology needed.. OSM has too many tags, and they are inconsistent and poorly documented.  Not your fault.
