### ISSUE TITLE
"payment:debit_cards" too generic

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7294]
An osmose error made me realize that the `payment:debit_cards` tag is too generic (and seems like the wiki agrees). But iD does suggest it in it's list.
https://wiki.openstreetmap.org/wiki/Key:payment#Debit_cards

> This should be mainly used when debit cards are not accepted. If cards are accepted, please indicate which by using a more specific key.

While I guess you could argue having it in the list is useful when you want to mark it as '=no', maybe it should be discussed some more if having it in there is a good or not

**Comment by bhousel** [comment]
I think this is another case where osmose is being too pushy..
