### ISSUE TITLE
emergency=mountain_rescue - Icon and more fields needed

### ISSUE THREAD

**Issue by MarkusGaugg** [openstreetmap/iD#7296]
In the Alps there are mountain rescue stations in many places. An icon in iD would be very good. In addition, certain fields should be activated by default, such as the address, the website, e-mail address and the operator.

<img width="297" alt="Ashampoo_Snap_2020 01 27_19h48m00s_001_" src="https://user-images.githubusercontent.com/2048093/73203954-64044280-413e-11ea-8f13-cd5da1ea8fdb.png">

**Comment by animesh-007** [comment]
I would like to work on it.

**Comment by animesh-007** [comment]
Hi, Thank you for allowing me to work on this issue. I was able to solve the issue. Also, I have attached a screenshot of my work. It would be great if you could let me know if there are any further modification needed with the current change.
<img width="393" alt="Screen Shot 2020-02-01 at 2 38 40 PM" src="https://user-images.githubusercontent.com/53366877/73589770-d4c1ab00-4500-11ea-82ef-6f3b0d0ff943.png">

**Comment by MarkusGaugg** [comment]
Looks good so far.

Maybe you could adjust the icon so that we can distinguish it from a regular rescue station.

Possibly a mountain with a red cross as an icon.

**Comment by animesh-007** [comment]
Does there exist any icon like this or I should leave it with an ambulance icon and create an issue for a new icon?
@bhousel

**Comment by animesh-007** [comment]
I have made a PR #7323 with an ambulance icon for now. Any suggestions on that?
@quincylvania @bhousel

**Comment by MarkusGaugg** [comment]
Icon is ready to be integrated: https://github.com/MarkusGaugg/iD/pull/1
