### ISSUE TITLE
Do not add healthcare=pharmacy to amenity=pharmacy and similar common amenity values

### ISSUE THREAD

**Issue by jeisenbe** [openstreetmap/iD#7300]
PR #4329 helpfully added a number of missing healthcare-related features and property tags, after a short discussion in #3589

However, it also added a unusual rule to always add duplicate tags of the form healthcare=pharmacy to features with amenity=pharmacy. At the time of the PR, healthcare=pharmacy was used under 500 times, compared to 220,000 amenity=pharmacy features at that time. Though it had been mentioned in a proposal back in 2010, it had never become popular. 

Since then it has only be used along with amenity=pharmacy (99.7% of the time),  most likely added mostly by this preset. (https://taginfo.openstreetmap.org/tags/healthcare=pharmacy#combinations)

The situation is similar for:
* amenity=hospital / healthcare=hospital
* amenity=clinic / healthcare=clinic
* amenity=doctors / healthcare=doctor
* amenity=dentist / healthcare=dentist

During the discussion in issue #3589 a maintainer and several contributors mentioned that the amenity tags should not be deprecated (see https://github.com/openstreetmap/iD/issues/3589#issuecomment-260979736) so it is unclear why the uncommon healthcare=* versions of these tags were added.

I recommend changing the presets and validation rules for these 5 features to just use the common amenity=* tags in these cases, to avoid tag fragmentation and duplicate tagging.

**Comment by bhousel** [comment]
They were approved, and people want them, so we support them..  It's that simple.

#3589 contains a bunch of people who are glad that we are taking a step towards improving healthcare tagging in OSM and who are stakeholders in consuming this data.

**Comment by jeisenbe** [comment]
They were approved in 2010, but not much used until 2017 when iD supported
them, as shown above.

What is the benefit of adding these tags?

So far the only argument presented on the Tagging list is that amenity=
should be deprecated because it contains too many features.

**Comment by jeisenbe** [comment]
> They were approved

The tag healthcare=pharmacy was not approved, and consensus is that this tag is not needed: amenity=pharmacy is the tag supported by other editors and all database users. 

See the history on the tag page:

"Multiple healthcare=* tags were introduced by healthcare proposal. This tag duplicating amenity=pharmacy was not introduced by this proposal. Author of the healthcare proposal wanted to deprecate amenity=pharmacy and replace it with shop=pharmacy, but due to strong opposition to deprecating amenity=pharmacy this was abandoned."

https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dpharmacy - the relevant text was added by another user (See https://wiki.openstreetmap.org/w/index.php?title=Tag%3Ahealthcare%3Dpharmacy&type=revision&diff=1951994&oldid=1951250)
