### ISSUE TITLE
Option of keyboard shortcut for "switch (background-)imagery view to next available (background-)imagery in list"

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7301]
See title, is something already possible/available? If not, is this an idea which would be worth for implementing?

(same question for JOSM editor: https://josm.openstreetmap.de/ticket/18637#ticket)

**Comment by sun-geo** [comment]
Imaging use-case, there is a removed building and the mapper changed the existing osm-object from `building=yes` to `demolished:building=yes` (or to `removed:building=yes` or to `razed:building=yes`) maybe because he want to reduce the risk, that the building outline will be mapped again from the next mapper which uses the outdated aerial imagery (background data) as source.

I would think, the lifecycle object relics (`demolished:*=yes` or `removed:*=yes` or `razed:*=yes`) could be latest removed from the osm-database at all, when all different available (for the relevant area) aerial imagery doesn't show the old buildings any more. So it would be convenient to scroll/browse fast (via keyboard shortcut) through all the potential available aerial imageries for that area.

**Comment by andrewharvey** [comment]
very similar to #5694

**Comment by quincylvania** [comment]
> very similar to #5694

Yes, I think we can group these together as "better background layer navigation".
