### ISSUE TITLE
potential renaming of preset "Recently demolished building"

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7305]
Potential follow up of #7098

Preset of tag: `demolished:building=*`

Proposal:

Renaming of preset _"Recently demolished building."_ to _"**Outline of** recently demolished building."_ or something similar, e.g. more meaningful adjusted to native English speaker.

btw.: Are there also presets available for:? 
- `removed:building=*` - https://taginfo.openstreetmap.org/keys/removed%3Abuilding ~ 8k db-units
- `razed:building=*` - https://taginfo.openstreetmap.org/keys/razed%3Abuilding ~ 3k db-units

**Comment by quincylvania** [comment]
> Renaming of preset "Recently demolished building." to "Outline of recently demolished building." or something similar, e.g. more meaningful adjusted to native English speaker.

@sun-geo Thanks for the idea, but I think "Recently Demolished Building" is already self-explanatory in English. Feel free to be more descriptive as needed when translating.

> Are there also presets available for:?

Nope, since the distinction between different types of former buildings isn't really significant in OSM. The point of the `demolished:building` preset is to prevent mappers from adding former buildings that are still visible in imagery. It would be nice if these were all tagged the same way.

**Comment by sun-geo** [comment]
> > Are there also presets available for:?
> 
> Nope, since the distinction between different types of former buildings isn't really significant in OSM. The point of the `demolished:building` preset is to prevent mappers from adding former buildings that are still visible in imagery. It would be nice if these were all tagged the same way.

It's true - the distiction is hard, it seems more or less these are the same kind of objects - but it also seems the community didn't yet clearly deside (there is no approved proposal so far i see) which variant is to use. So therefore i would like to have available at least for the top two (`demolished:building=*` & `removed:building=*`) the same hidden preset. (http://taghistory.raifer.tech/#***/removed:building/&***/demolished:building/&***/razed:building/)

**Comment by quincylvania** [comment]
> So therefore i would like to have available at least for the top two (demolished:building=* & removed:building=*) the same hidden preset. 

iD can't have one preset that matches multiple different tags. There's also no precedent for having multiple presets for the same thing. If the OSM community settles on one tag, then iD can support that and deprecate the others, but until then we're just going with the most-used pattern.

**Comment by sun-geo** [comment]
Oh sorry, of course, it was a misunderstanding from my side. Was maybe triggered because i see a maybe minor difference between `demolished:` (i thought it might be destroyed and maybe some rests of the destroyed parts are still there) and `removed:` (i thought all parts are completely removed). But you are right, about this should be talked first by a wider community.
