### ISSUE TITLE
[preset] Add the landcover=trees

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#7308]
Consider adding the landcover=trees preset

https://wiki.openstreetmap.org/wiki/Tag:landcover%3Dtrees

**Comment by quincylvania** [comment]
@ignaciolep Thanks, but I think it's already confusing enough for users to choose between iD's `natural=wood` and `landuse=forest` presets. I'd recommend these three tags get reconciled by the community to avoid further divergence 😕

**Comment by bhousel** [comment]
Ah yeah, there are some old issues where we said we weren’t doing `landcover`.. I can look them up later when I’m at my desk.

**Comment by ignaciolep** [comment]
Ok, understood. 👍
