### ISSUE TITLE
kneipp_water_cure - Icon and more fields needed

### ISSUE THREAD

**Issue by MarkusGaugg** [openstreetmap/iD#7313]
Kneipp Water Cure Places are now common. An icon in iD would be very good. In addition, certain fields should be activated by default, such as:
 
kneipp_water_cure:foot=yes/no
kneipp_water_cure:arm=yes/no
kneipp_water_cure:face=yes/no
fee=yes/no
opening_hours=*
barrier=handrail
leisure=barefoot

More info about possible Tags:
https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dkneipp_water_cure

**Comment by animesh-007** [comment]
I would like to work on it.

**Comment by animesh-007** [comment]
Well, I am trying to solve this issue but I am not able to get it how to define leisure = barefoot and barrier=handrail beforehand.
And barrier, leisure both are having the same label i.e Type. It would be better I guess if both show their name in the label?
@quincylvania 
<img width="390" alt="Screen Shot 2020-02-04 at 1 32 01 AM" src="https://user-images.githubusercontent.com/53366877/73688865-fa160b00-46f2-11ea-88fa-068ca4fe9792.png">

**Comment by bhousel** [comment]
Oh yeah, we can't really support the `barrier` or `leisure` tags.  I'd also probably skip the foot/arm/face tags, or maybe make them a multicombo.

**Comment by animesh-007** [comment]
Hi, Thank you for allowing me to work on this issue. I was able to solve the issue. Also, I have attached a screenshot of my work. It would be great if you could let me know if there are any further modification needed with the current change.
<img width="391" alt="Screen Shot 2020-02-05 at 10 52 08 AM" src="https://user-images.githubusercontent.com/53366877/73813415-eb6c4880-4805-11ea-95df-08444e9faa32.png">

**Comment by bhousel** [comment]
@animesh-007 we can't support the `barrier` or `leisure` tags..
This is why there are two "Type" fields showing in your screenshot.

Also please title case the name of the feature like "Kneipp Water Cure", thanks!

**Comment by animesh-007** [comment]
I have made the suggested changes. Please let me know if any other change is needed.
<img width="391" alt="Screen Shot 2020-02-05 at 8 48 32 PM" src="https://user-images.githubusercontent.com/53366877/73854873-36fc1200-4859-11ea-893b-56dc6002b3fd.png">

**Comment by quincylvania** [comment]
@animesh-007 Please remove the `barrier` field as well.

It's hard to tell what changes might be needed based on screenshots alone. It's easiest if you open a pull request first and then we can discuss it.

**Comment by bhousel** [comment]
> Please let me know if any other change is needed.

Why is "Type = handrail" still showing?

(I don't think this Water Cure thing is a hand rail)

**Comment by animesh-007** [comment]
Is it okay now?
<img width="386" alt="Screen Shot 2020-02-05 at 9 06 38 PM" src="https://user-images.githubusercontent.com/53366877/73856510-922f0400-485b-11ea-8b34-d06e50ff954a.png">
