### ISSUE TITLE
Can iD pre-fill entries with open data?

### ISSUE THREAD

**Issue by UKChris-osm** [openstreetmap/iD#7318]
This might already exist, and I'm just to new to have realised, but can iD pre-fill or auto-fill data if the data is openly available?

For example, in the UK, the Post Office have made available (via a Freedom of Information request) a CSV dataset that lists all of the open Post Office's, which includes the address, GPS location and opening hours of each Post Office.

This data is currently being used for a [Post Office Progress Tool](https://osm.mathmos.net/postoffice/) - created by one Robert Whittaker, but I do wonder, if I were to add a Post Office node / way using iD, could iD then use the Post Office dataset to grab the address and opening hours data automatically?

**Comment by forteller** [comment]
I don't know about your example, but if you add a link to a Wikipedia article on an element, it will fill out the information from that, which is pretty awesome :)

**Comment by quincylvania** [comment]
Hi @UKChris-osm. This is an interesting idea, but I think it's outside the scope of iD right now. If the post office progress tool can already match authoritative data to existing data, I'd recommend running an automated edit to sync them.

Eventually we'd like to add an assisted-editing workflow to iD that helps mappers manually review and copy over features from external datasets (similar to RapiD). But attempting to pre-populate attributes sounds like a big lift with unclear value.
