### ISSUE TITLE
No Crossing Types for Cycle & Foot paths

### ISSUE THREAD

**Issue by jonathonwpowell** [openstreetmap/iD#7321]
I think since there is a Cycle & Foot path, there should be an option for marked / unmarked crossings for it. I have seen a ton of locations where the crossings for Cycle & Foot paths don't define if bicycles can cross or not and are footpaths. I also selfishly want it as I deal with these crossings a lot

I am happy to make a PR to add this if someone with experience in the project agrees that this would be helpful.

**Comment by quincylvania** [comment]
Hi and welcome, @jonathonwpowell. I'm assuming you propose that we add two feature types? (We call these "presets" behind the scenes in iD.)

While I can see how these would be convenient for some mappers, they also mash together a lot of concepts. A name like "Unmarked Cycle & Foot Path Crossing" is really too long in English and would be even longer translated to other languages.

We already have presets for marked and unmarked cycle crossings. It's a bit slower, but would you mind using these and just adding the access values manually? The next version of iD will even let you edit multiple features at once (see #7306), making this kind of task pretty quick.

**Comment by jonathonwpowell** [comment]
I have been just manually doing it, my only concern is that other people won't do this.  I see tons of these done incorrectly in my area, where they are either marked for bikes or pedestrians but not both.  I understand the concern about the length of the name though.

**Comment by quincylvania** [comment]
@jonathonwpowell Okay, I added a "Cycle & Foot Crossing" preset. The mapper will still need to selected marked or unmarked on their own.

**Comment by sun-geo** [comment]
Thanks, btw. is this something related to tagging `crossing_ref=toucan`?, see:
https://taginfo.openstreetmap.org/tags/crossing_ref=toucan
https://wiki.openstreetmap.org/w/index.php?oldid=132309#Usage

**Comment by quincylvania** [comment]
> btw. is this something related to tagging crossing_ref=toucan?

@sun-geo No? Nothing in iD is related to `crossing_ref` 😅

**Comment by jonathonwpowell** [comment]
Awesome! Thanks @quincylvania
