### ISSUE TITLE
Message displays times are in UTC

### ISSUE THREAD

**Issue by sriramnpkt** [openstreetmap/iD#7322]
The time mentioned in the messages are in UTC, it would be helpful if it can be configured in the Settings. And the time format lacks the word UTC too.

**Comment by bhousel** [comment]
@sriramnpkt can you send a screenshot of where you are seeing this?

**Comment by quincylvania** [comment]
Closing as stale since we don't have enough information to address the problem.

**Comment by sriramnpkt** [comment]
> @sriramnpkt can you send a screenshot of where you are seeing this?

Sorry for the late reply.

I sent the message around "11:17 AM IST  28 Feb 2020", but the screenshot shows "28 February 2020 at 05:48".

PFA
![OSM_Screenshot from 2020-02-28 11-18-59](https://user-images.githubusercontent.com/26897463/75513917-38fe5e80-5a1c-11ea-9463-cbf6d5d26621.png)

**Comment by quincylvania** [comment]
@sriramnpkt No problem! Looks like an issue with the OpenStreetMap website, not the iD editor. You can open an issue for that project at https://github.com/openstreetmap/openstreetmap-website/issues.
