### ISSUE TITLE
Support circularizing multiple selected closed ways at once

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7326]
Continuing on multiselection editing issues like #6565 and #6810, we should let users circularize multiple features with a single operation. This functionality will be especially helpful after repeat drawing in the v3 UI.

This is different than shaping multiple lines into a single circle, though that would be interesting future work.

**Comment by ScottWalkerAU** [comment]
> This is different than shaping multiple lines into a single circle, though that would be interesting future work.

Hi @quincylvania, does there exist a ticket for this change I could follow?
