### ISSUE TITLE
Show house number of buildings

### ISSUE THREAD

**Issue by BathoryPeter** [openstreetmap/iD#7327]
It would be helpful to see the house number rendered on buildings. Now users have to click/highlight each building to check if it has address or not. It makes hard to do an address survey in iD.

I cannot see any open issue or pull request in this topic. There was a promissing PR #3840 several years ago, but sadly it wasn't merged. #1524 is similar but for address points.

**Comment by bhousel** [comment]
This is #1524

**Comment by BathoryPeter** [comment]
That issues is about icons of address points. I'm talking about buildings mapped as areas.

**Comment by bhousel** [comment]
> That issues is about icons of address points. I'm talking about buildings mapped as areas.

That issue is about rendering housenumbers, however they might be mapped.
