### ISSUE TITLE
Question: does iD use min/max_zoom for wms sources?

### ISSUE THREAD

**Issue by grischard** [openstreetmap/iD#7328]
Hi from the Editor Imagery Index!

I always thought that iD ignored the min_zoom and max_zoom layer parameters for wms sources, but now that I'm looking at `iD/modules/renderer/background_source.js` I'm not so sure.

Would it please be possible to confirm whether iD does ignore them, in which case I should drop them from ELI automatically, or doesn't, in which case I should tell my linter script that it's ok to have those parameters?

**Comment by bhousel** [comment]
> I always thought that iD ignored the min_zoom and max_zoom layer parameters for wms sources, but now that I'm looking at `iD/modules/renderer/background_source.js` I'm not so sure.

We do use the `min_zoom` and `max_zoom` if they are set.  They get combined into this `zoomExtent` variable:
https://github.com/openstreetmap/iD/blob/13ead256548b4ae419a166b013f5c3ab68c007f9/scripts/update_imagery.js#L125-L130
https://github.com/openstreetmap/iD/blob/13ead256548b4ae419a166b013f5c3ab68c007f9/modules/renderer/background_source.js#L39

**Comment by grischard** [comment]
Thank you very much Bryan!
