### ISSUE TITLE
Measurement panel should show more statistics on multiple selection

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#7329]
Currently, when I select multiple contiguous `highway` ways, the Measurement panel shows only the centroid of the overall selection, but it would be handy to see more statistics, namely the total number of nodes and the total length.

(Observed in iD [v2.17.1](https://2-x--ideditor.netlify.com/) and master.)

**Comment by quincylvania** [comment]
@1ec5 Great idea. First-class multiselection tools will be a focal point of the next release or two.
