### ISSUE TITLE
refresh preview.ideditor.com/master

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7335]
Would it be possible to refresh https://preview.ideditor.com/master ?
Looks like this is a version from 17 days ago.
I need it for translations and beta tests for new features. Sometimes it's difficult to translate without context.

**Comment by quincylvania** [comment]
@maro-21 So we've stopped updating the `master` branch as we focus on rebuilding v3. You can preview the `2.x` working branch at this link: https://2-x--ideditor.netlify.com.

As always, thanks so much for testing and translating!

**Comment by maro-21** [comment]
Thanks for the link.
But it looks like it's not the same as current branch 2.x. It looks strange. There are new features, like Osmose Issues but translations aren't updated. And there are strings which should be in my language like Fields, Tags and Relations in the editor but they are in English.
Searching an address/city doesn't work. It finds something but when I click, nothing happens.
I can't search for a beauty shop because it shows me blank preset and I can't click it.

Tanning salon looks like this:
![tanning salon](https://user-images.githubusercontent.com/57260466/74102029-04dffe00-4b40-11ea-961c-ab162af248b4.png)
no Fields.
And I can't remove beauty=tanning, when I click the icon, no reaction.
Similar behavior with restaurant + cuisine.

So this version is helpful for translations but it doesn't work properly...

**Comment by bhousel** [comment]
> no Fields.

Inherited fields are currently broken in 2.x branch - I broke them a few days ago and will fix them soon, sorry 😓
