### ISSUE TITLE
Allow for additional filtering on the Mapillary layer

### ISSUE THREAD

**Issue by tas50** [openstreetmap/iD#7337]
Hey folks. Thanks for all the hard work on iD. It's really great to see the progress over the years. I've found the Mapillary layer to especially useful when editing an area after capturing it with a car-mounted 360 camera. The problem is there's no way to filter the Mapillary data and in some areas it's hard to find the new data in the see of dated map data. Would it be possible to add the ability to filter based on the capture year and if the map data in 360 or not? I haven't looked at their API to confirm that this is something they expose, but they offer those filters on their website so I assume it's part of their API.

Thanks,
Tim

**Comment by quincylvania** [comment]
@tas50 Thanks for capturing this kind of data! We added the 360° filter in #5433. It appears after enabling the Mapillary layer in the Photo Overlays section. Date filtering is #4518 and user filtering is #5307, so I'm closing this as a duplicate. But we do want to make filtering better for all photo layers 👍
