### ISSUE TITLE
deprecation of created_by (object key)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7338]
The `created_by` seems in use for a changeset tags and also for object key.

For my understanding the object key could be deprecated, see wiki

https://wiki.openstreetmap.org/wiki/Key:created_by

See also tag evolution 

https://taghistory.raifer.tech/#***/created_by/

**Comment by bhousel** [comment]
Yes, your understanding is correct.

`created_by` is required as a changeset tag.

iD already does discard this tag from object tags and always has. 
This is the list of tags iD will discard:  https://github.com/openstreetmap/iD/blob/2.x/data/discarded.json

**Comment by sun-geo** [comment]
Oh interesting.

So why I don't get any validator message to remove this key (tag)
Example object: 
https://www.openstreetmap.org/edit?node=61346477#map=19/42.32791/-71.08767
Even after editing e.g. adding a name tag.

See movie:
![created_by validation](https://user-images.githubusercontent.com/47290585/73964793-2d36e500-4913-11ea-9171-50be18ef9b33.gif)

**Comment by bhousel** [comment]
iD should silently remove the tag when you save.  We don't use the validator for this.

**Comment by sun-geo** [comment]
I tested it, it works as described. 

Precisely because it is a silent function, I particularly like it because other mappers are not encouraged to remove objects only for this purpose (remove "created_by")

:)
