### ISSUE TITLE
StreetView link "View on Bing Maps" brings to boken page

### ISSUE THREAD

**Issue by blackboxlogic** [openstreetmap/iD#7341]
When using the Bing Streetview photo overlay in iD, the link to "View on Bing Maps" brings me to [a page](https://www.bing.com/maps?cp=43.63804~-70.258949&lvl=17&dir=1.099&style=x&v=2&sV=1) which works for a bit then freezes (with a js error) after a few seconds of looking around or navigating.

I'm noticing that `style=x` (which loads the streetview immediately) isn't mentioned in the [Bing Maps documentation](https://docs.microsoft.com/en-us/bingmaps/articles/create-a-custom-map-url#general-parameters)

I reported it to Bring Maps 'feedback'.

I tried `style=a` through `style=z` and found that `x` is the only "streetView" style.

![image](https://user-images.githubusercontent.com/31355456/74041849-6cf1e100-4994-11ea-9985-35d6bf8539b9.png)

**Comment by blackboxlogic** [comment]
Though style=x is missing from the documentation, it IS A SUPPORTED FEATURES since you get this link by clicking "share" from their map while in streetview. I've given feedback to their documentation to add style=x which "brings user to streetview and freezes because of a js error"
Since this IS a supported feature, I think bing should fix their page, and we should not make any changes to iD.

**Comment by blackboxlogic** [comment]
This issue appears to be resolved.

**Comment by quincylvania** [comment]
@blackboxlogic Terrific! Thanks for reporting and seeing this issue through 👍
