### ISSUE TITLE
Stadium (geometry) tool

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7345]
Long term wishlist item: tool to help make ovals. We can make perfect circles and rectangles. Seems like the next step is simply a combination of the two.
![26364-0](https://user-images.githubusercontent.com/1230959/74108421-3941d180-4bb5-11ea-9788-80e4f2f4d0a1.jpg)
(Best hand attempt given a reasonable amount of time for https://www.openstreetmap.org/way/771115229 .)

**Comment by jidanni** [comment]
(A tool to make a circle, that is pulled apart, with the break points connected with straight lines. That kind of oval.)
(=)

**Comment by jidanni** [comment]
https://en.wikipedia.org/wiki/Oval#In_common_speech
https://en.wikipedia.org/wiki/Stadium_(geometry)

**Comment by jidanni** [comment]
OK, as we see this is a high frequency shape.
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dstadium

**Comment by quincylvania** [comment]
So eventually we might do #2570 and/or add a circular segment drawing tool. These would make it easier to create curves in a variety of scenarios, not just "stadiums". Let's focus on general-purpose tools with high applicability rather than scenario-specific tools.
