### ISSUE TITLE
Add spike strip preset

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#7347]
[`barrier=spikes`](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dspikes) is for a spike strip, also known as traffic spikes, tire shredders, one-way traffic treadles, stingers, stop sticks, and a tire deflation device. An icon for this preset could depict the spikes themselves and possibly a tire being punctured. The preset should only appear for a node on a way.

**Comment by animesh-007** [comment]
I would like to work on it.

**Comment by animesh-007** [comment]
I tried to solve the issue. Any suggestions on it?
@bhousel @quincylvania

**Comment by animesh-007** [comment]
I tried to solve the issue with proper naming this time. sorry for the inconvenience.

**Comment by bhousel** [comment]
done in #7354
