### ISSUE TITLE
2.17.2: untranslatable strings

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7358]
After updating to 2.17.2 version, strings `All fields`, `All tags` and `All relations` are in English and it's not possible to translate them.
The same with Maxar layer tooltip.

**Comment by quincylvania** [comment]
Oh dear, this is because Transifex is pulling the strings from the latest `2.x` branch but 2.17.2 is based on an earlier version with slightly different strings. This will get addressed in the next feature update but I'm not sure if we need to fix it sooner.
