### ISSUE TITLE
2-x: Search Location Click does not work ATM

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#7359]
Just in case its not a known issue already…

To reproduce:
1. open https://2-x--ideditor.netlify.com/#background=Bing&disable_features=boundaries&map=2.00/0.0/0.0
2. search for "Böhmische STraße, Berlin"
3. => 3 results, clicking them does not zoom the map / do anything

**Comment by mmd-osm** [comment]
Error message on console: TypeError: o.loadEntity is not a function

```
s.zoomToEntity = function (r, e) {
!1 !== e && o.loadEntity(r, function (e, t) {
if (!e) {
```

**Comment by quincylvania** [comment]
Looks like this was due to ES6's `this` behavior in fat arrow functions.
