### ISSUE TITLE
Error is produced for a covered way crossing a building

### ISSUE THREAD

**Issue by elumbella** [openstreetmap/iD#7361]
Consider a building with an overhang and a footway underneath that overhang. The path is tagged with `covered=arcade`. The building is split up into two parts, one which is touching the ground and the other one above the path. Both parts are joined in a relation, and additionally a surface is created for the whole building (as described in [the wiki](https://wiki.openstreetmap.org/wiki/Key:building:part)).

![image](https://user-images.githubusercontent.com/2538681/74604621-04a3ad80-50c0-11ea-868d-cbdc61a3ece5.png)

iD now shows a warning about a path crossing a building without any level indications. However, both the building and the path are essentially on the same level. So this should not produce a warning.

**Comment by quincylvania** [comment]
Hi and welcome, @elumbella. iD used to consider the `covered` tag in this situation but that approach has a few issues. Mappers would add `covered=yes` to the entire way even if only part of it was covered. It's also ambiguous for something like a rooftop path covered by a second roof.

I agree `level` isn't right here, but you can use the `layer` tag to specify the relative vertical order of any intersecting ways in OSM.

**Comment by elumbella** [comment]
@quincylvania I have used the layer option. However, the layer only applies to the (in this case right) part of the building, not to the whole area. This is why the error appears I believe: not because of the intersection with the building _part_ but with the whole building.

I might add that I find this kind of mapping weird anyway. I have just complied to the wiki. Would you think that changing the procedure here might be the way to go? I.e. not add another area for the whole area?

**Comment by quincylvania** [comment]
@elumbella Hmm there are several ways to disambiguate this crossing and iD uses the one that's simplest for most mappers in most situations. If you don't want to tag the whole building with `layer` then instead you can tag the section of the path under the roof with `layer=-1` plus your `covered` tag.
