### ISSUE TITLE
left title string translations

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7364]
A bit related to https://github.com/openstreetmap/iD/issues/7280

Are these strings "_**All fields**_" / "_**All tags**_" / "_**All relations**_" also coved with

> quincylvania: _"Strings specific to the master branch haven't been made translatable yet since they're very much subject to change…"_

? Or is there an option to translate it right now? 

![all txt transifex](https://user-images.githubusercontent.com/47290585/74679211-7c0b3700-51bd-11ea-8ba4-c752bef762ca.jpg)

**Comment by quincylvania** [comment]
This is #7358…
