### ISSUE TITLE
Edit Tree preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7371]
We rather don't use `diameter=` with trees, but `circumference=`.
https://taginfo.openstreetmap.org/tags/natural=tree#combinations
So I suggest remove this key or replace it with `circumference=`.
We can also add `height=`.

**Comment by bhousel** [comment]
> We rather don't use `diameter=` with trees, but `circumference=`.

That sounds odd to me. I work with trees and they are generally measured as the [diameter at breast height (DBH)](https://en.wikipedia.org/wiki/Diameter_at_breast_height).  There are techniques to do this accurately, though I'm sure most people just eyeball it.

**Comment by maro-21** [comment]
For the protected trees in my region which are natural monuments, only the circumference is given.
Anyway, [Wiki](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree) doesn't even mention `diameter=`. There is only `diameter_crown=*` which is used 190,521 times. Where `diameter=` 7,325 times. And `circumference=*` 499,960 times.
Wikipedia in my language says:

> In forestry sciences and dendrometry, the measurement concerns the diameter of the trunk.
In nature protection, trunk circumference is usually measured, which is one of the basic criteria qualifying trees for protection in the form of natural monuments.

**Comment by quincylvania** [comment]
Any data consumer that cares about this can calculate one value from the other, so I'm not sure it's worth worrying about. I'd bet that the only reason `circumference` has almost 500,000 uses is data imports—I doubt people are measuring hundreds of thousands of trees just for OSM.

**Comment by maro-21** [comment]
They not measure it, it's a given value when the tree is a natural monument.
But the fact is that it is a commonly used key. We can also have both.

**Comment by quincylvania** [comment]
Okay, I guess there's no harm in adding this under `moreFields` since it has so much usage.
