### ISSUE TITLE
Do not prompt with non-existent features

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7372]
The user thinks he edited the map, but in many cases he didn't.

Let's review what the user sees.

https://www.openstreetmap.org/ says
"Welcome to OpenStreetMap!
OpenStreetMap is a map of the world, created by people like you... Start Mapping"

User creates an account and clicks Edit, draws a geometry, and in "Select feature type" is
prompted with plenty of feature names. User picks one.

User clicks Save, and sees:
"You just edited OpenStreetMap!
Thank you for improving the map around Nibblesburg.
Your changes should **appear** on OpenStreetMap within a few minutes. It may
take longer for maps elsewhere to receive updates. [Details](https://wiki.openstreetmap.org/wiki/FAQ#I_have_just_made_some_changes_to_the_map._How_do_I_get_to_see_my_changes.3F)"

However there is a big chance that his edit actually failed: nothing in
fact was put on the map. It turns out many of featues that iD prompts
the user with are in fact just experimental ones. Sure, "House" works,
but many others do nothing to the map. However the user isn't alerted to
this fact until his friends say they couldn't find that sawmill he was
talking about etc. and had to abandon their trip. He trusts the "Your
changes should appear" message and shouldn't have to double check each
time to see if it was telling the truth.

Therefore iD should not list such experimental features unless the user
has checked "Also prompt me with experimental invisible features." in say, some side panel.

Sure, the user [needn't worry](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer), his edits will show up in a year or two, if those experimental feature types
get implemented, but then the website shouldn't say "within a few minutes".

Yes, one might say "the more the people use a feature, the more likely it will get approved." But the user is not here to be a guinea pig. He just wants to "Start Mapping".

**Comment by jidanni** [comment]
If they are [specialist tags](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer#Clarification) then they should only appear if the user has checked [x] Include specialist tags, somewhere.

**Comment by bhousel** [comment]
We have no idea whether features will get rendered or not.  This doesn't mean they are "experimental"   or not.  

There is a lot of misleading information on the OSM wiki about how tags work, so I wouldn't read too much into that "specialist tags" stuff.
