### ISSUE TITLE
2-x: "Show my location" Click does not work

### ISSUE THREAD

**Issue by Shi-Jianmin** [openstreetmap/iD#7376]
2-x: "show my location" does not work
Even brower's setting of location permission is already allowed
![image](https://user-images.githubusercontent.com/58833713/75000438-a8ff6880-54a1-11ea-9863-9ac2dfc0d30b.png)

**Comment by quincylvania** [comment]
Hi and welcome, @Shi-Jianmin.

I can't seem to reproduce this issue… What browser/platform are you using? Do you see any [JavaScript console](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers) errors?

**Comment by tordans** [comment]
Works for me as well on https://2-x--ideditor.netlify.com/#background=Bing&disable_features=boundaries&map=20.00/52.47365/13.44664.

**Comment by Shi-Jianmin** [comment]
@quincylvania @tordans 
Thank you very much  for relaying this.

@quincylvania 
I am sorry that I fogot to write the browser I used.
I used chrome version 80.0 and windows 10
I couldn't find any errors on console.
![no_error_javascripConsole](https://user-images.githubusercontent.com/58833713/75218558-eafc1780-57dd-11ea-8c4d-f0653d9574ed.PNG)

@tordans 
I access the site that you sent me. 
The "show my location" still doesn't work.

@quincylvania @tordans 
I try to use Edge 42.17134.1098. "Show my location" also doesn't work.
There may be a problem in my network

**Comment by quincylvania** [comment]
@Shi-Jianmin Hmmm are other sites able to show your location in those browsers?

**Comment by Shi-Jianmin** [comment]
@quincylvania 
Thank you for relaying!!
I try to use  other network,  it does work.
I am really sorry to make you confused.
I will close the issue.

**Comment by quincylvania** [comment]
@Shi-Jianmin No problem! Location sharing stuff is tricky. Good luck.
