### ISSUE TITLE
"Two points are very close" warning: Do not autofix when nodes are member of more than one way and angles are not 180°

### ISSUE THREAD

**Issue by sb12** [openstreetmap/iD#7379]
Hello,
I think there is a problem with the warning "Two points are very close" in regions that are mapped very detailed.
Example:
![grafik](https://user-images.githubusercontent.com/5783139/75093480-63669c80-5582-11ea-8390-414aaa74e142.png)
If you auto-join these nodes, you will change the geometry of the rectangle building (in some cases you might even end up with a two-node building by applying the autofix several times):
![grafik](https://user-images.githubusercontent.com/5783139/75093505-a163c080-5582-11ea-87b9-826bb0ca88bf.png)
I think these validator warnings should only be shown, when the angles for all ways sharing the nodes are close to 180°, otherwise there is a great chance that you destroy very detailled but completely valid data (3D buildings, indoor mapping etc.). 
The validator warnings suggest that there is something wrong in the data, so there are some OSM users that try to get their area free of warnings and just apply the autofixes without thinking. It is also very difficult to see the actual change in the iD-Editor because you have to zoom in very close.
I just spent 1 hour to fix geometries that were destroyed by this validator warning autofix.

**Comment by quincylvania** [comment]
Hello and welcome, @sb12. This does look like a problem… can you post a link to somewhere iD issues these warnings?

**Comment by sb12** [comment]
Places where these warnings are issued:
https://www.openstreetmap.org/#map=19/49.24827/8.50817
https://www.openstreetmap.org/#map=19/49.25159/8.50793

Problematic changeset: https://nrenner.github.io/achavi/?changeset=80921182
