### ISSUE TITLE
iPad: features not selected with single tap

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#7380]
I tried changing the type of road today on an iPad.
(Location: https://www.openstreetmap.org/way/773761965)

I was able to select the raod:
![select](https://user-images.githubusercontent.com/111561/75115036-8ca72b80-565b-11ea-8297-a3e273231770.jpg)

But I could not change the type. Once I clicked on "Zufahrtsweg", the searchform searched for a location:
![change](https://user-images.githubusercontent.com/111561/75115057-b06a7180-565b-11ea-9038-3968588c83f6.jpg)

I did not test this on the preview / 2-x-preview, yet.

**Comment by quincylvania** [comment]
Looks like the underlying issue here is that the feature isn't actually selected when first tapped, it's just in the hover state. So the inspector can't be interacted with. This is still a bug that needs fixing.
