### ISSUE TITLE
Incorrect suggestion of landuse=reservoir tag change

### ISSUE THREAD

**Issue by tomass** [openstreetmap/iD#7382]
Id is stating that _landuse=reservoir_ is "outdated" tagging and should be changed.
_landuse=reservoir_ is not outdated, it never was - it is the standard OpenStreetMap way of tagging reservoirs. And it is still more popular tagging than russian water scheme.
Therefore this suggestion should be removed as it is not true and it is damaging existing data.

**Comment by tastrax** [comment]
https://github.com/openstreetmap/iD/issues/6589
https://github.com/openstreetmap/iD/issues/5591

**Comment by bhousel** [comment]
@tomass you already opened #6589 for this. You can’t just keep opening issues for stuff you don’t like.

**Comment by tomass** [comment]
I do not follow development of iD, I do not use iD, and we actively tell people NOT to use iD because of its authoritarian handling of tags and bugs.
However we constantly have to fix mess made by iD and from time-to-time I do report that here.
I see that we also need some other "non standard" ways to discourage people from using iD as coders of iD just don't care about OpenStreetMap.

**Comment by bhousel** [comment]
> and we actively tell people NOT to use iD because of its authoritarian handling of tags and bugs.

Can you not read?  We did a thing because people asked us to.  That's.. the opposite of authoritarian. 

Please stop trolling us about the reservoirs.  

> However we constantly have to fix mess made by iD

OSM made this mess of having several ways to tag a thing.  Not us.
