### ISSUE TITLE
The options to fix an issue disappears if you adjust the line first

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7386]
Not sure if that title was understandable… :/

If you cross one road over another or over a sidewalk, you're asked if you want to connect them, and can do that with one click. But maybe the new road you drew needed an adjustment, and instead of having to drag two points you just want to drag one, so you first adjust the road, and the you want to click the button to connect to the road you crossed. Well, after adjusting the road, that option is now gone, and all you can do is ignore:

![Screenshot from 2020-02-26 21-01-11](https://user-images.githubusercontent.com/343561/75384302-2a119200-58de-11ea-8ee2-2e5c141eb014.png)

If you click away from the road and then mark it again, the other options reappears. But they should't disappear in the first place :)

**Comment by quincylvania** [comment]
Oh yeah this is a bug…
