### ISSUE TITLE
Style the "on" state of the geolocate button

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7390]
As a followup to #5587, we should show give the geolocate button an enabled style when the user's location is shown.

<img width="84" alt="Screen Shot 2020-02-26 at 4 21 14 PM" src="https://user-images.githubusercontent.com/2046746/75408068-8e762680-58c9-11ea-93d5-322870fbc457.png">

**Comment by forteller** [comment]
I would add that the icon used is very unintuitive, at least to me. I do not look at that and understand what it does. I would recommend to change the icon to either the pin/drop icon or this:

![Screenshot from 2020-02-27 12-42-47](https://user-images.githubusercontent.com/343561/75441877-bcf21100-595e-11ea-9796-fdf4ccd836a6.png)

I think these are more commonly used to indicate "Find my location"

**Comment by quincylvania** [comment]
@forteller Hmm I just checked the Google Maps and Apple Maps apps and both use a very similar icon to ours (at least in the US localization). But the Google Maps website uses one like you show.

I think both are valid icons and I personally don't like the crosshairs.
