### ISSUE TITLE
Add "Chicken coop", "pigsty", "farm auxiliary" as searchable terms

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7394]
Tested in https://preview.ideditor.com/master/#background=none&disable_features=boundaries&map=18.58/37.05832/17.37726

All three may map to `building=farm_auxiliary` or have specific `building=pigsty` `building=chicken_coop`

Farm auxiliary is kind of weird term, but may be used by people who remember its tag value (like I just did during testing)

**Comment by quincylvania** [comment]
@matkoniecz Sounds fine. Feel free to open pull requests for minor stuff like this.
