### ISSUE TITLE
Add Preset for natural=hill

### ISSUE THREAD

**Issue by mfbehrens** [openstreetmap/iD#7404]
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dhill
I would like to have a preset for this feature. The input boxes can be copied from natural=peak

**Comment by kymckay** [comment]
Not so sure about this one. My first instinct was "isn't a hill just a classification of a peak?" and the wiki page also discusses the same lack of distinction. I think it makes more sense for peaks to be consistently tagged and folks can differentiate as they individually desire by the `ele` tag and/or a calculated prominence.

**Comment by bhousel** [comment]
The difference between hill/mountain/peak is indeed subjective. 

As far as I can tell, the main reason for this feature to exist is [if the hill has a name](https://en.wikipedia.org/wiki/List_of_hills) and the style wants to render named natural things. 

People can really add whatever they want into the `natural=` namespace, so this seems ok:
<img width="632" alt="Screenshot 2020-03-02 08 59 31" src="https://user-images.githubusercontent.com/38784/75682903-29715680-5c64-11ea-82a1-066c1e94ac59.png">

**Comment by mfbehrens** [comment]
I agree that the difference is subjective however the difference is definitively there.

Additionally, the tag is used in OSM and is not deprecated by the OSM Wiki so I see no reason why this should not be implemented.

**Comment by bhousel** [comment]
> Additionally, the tag is used in OSM and is not deprecated by the OSM Wiki so I see no reason why this should not be implemented.

We don't just do everything the OSM Wiki says to.  A lot of it is wrong or just added by one person.

**Comment by quincylvania** [comment]
Yeah I think it's fine for people to use `natural=peak` for named hills instead of making iD mappers draw distinctions.
