### ISSUE TITLE
UI translation strings used before data is loaded

### ISSUE THREAD

**Issue by kymckay** [openstreetmap/iD#7406]
Reported this in Slack, but have realised it doesn't always happen and is something of a race condition. Opening this issue to better keep track of this.

My understanding is that with the changes to bundled data being pulled in live instead, the main UI is created before these translation strings are pulled in which results in:
![image](https://user-images.githubusercontent.com/5459452/75683539-3ce5e700-5c8f-11ea-8020-45c0e63532e1.png)

**Comment by bhousel** [comment]
Thanks for the reminder - yes I did forget about this.  A lot is changing with iD internals right now.
