### ISSUE TITLE
Add "visible remains of shop or unopened shop" for disused:shop

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7407]
Triggered by https://www.openstreetmap.org/node/1905952844/history where someone added incorrect `shop=kiosk` where correct `disused:shop=kiosk` was already present.

I suspect that showing that it explicitly tagged as remains of a shop would be helpful in this situation.

Tag is in actual use https://taginfo.openstreetmap.org/keys/disused%3Ashop

Related to #7098

It may be better to have it unsearchable to prevent people from mapping historic objects unverifiable by survey.

I know that proposed name is unreasonably long, but for now I have no good ideas how to improve it.

**Comment by gendy54** [comment]
In France we use the tag `shop=vacant` which corresponds to all types of shops.

**Comment by matkoniecz** [comment]
shop=vacant support would be a separate, possibly new issue

**Comment by quincylvania** [comment]
iD already has an unsearchable preset for `shop=vacant` in case mappers come across them. Since we can't have two searchable presets for equivalent things and since `disused:shop` has some advantages, I'd ask that we leave things as-is.
