### ISSUE TITLE
Add highway=toll_grantry to icon presets

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7408]
Hi there.

In Portugal and many other European countries, there are plenty of [electronic toll systems](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtoll_gantry) on highways.
It would be nice to add a specific preset to iD to differentiate these from the normal human operated [toll booths](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth).

Regards.

**Comment by quincylvania** [comment]
@AntMadeira Okay, I added this preset labeled "Open Road Toll", since I think that's more descriptive in American English. I also excluded in from Germany since the wiki discourages its use there.

**Comment by AntMadeira** [comment]
Thanks, Quincy.
