### ISSUE TITLE
Idea: Use the selection tool to draw areas

### ISSUE THREAD

**Issue by Spanholz** [openstreetmap/iD#7420]
If one press shift and moves the mouse it is possible to draw circles or any other shape. This tool could also be used to easily map ponds, small forests etc. Comparable to fast draw in JOSM. 

Problem: Self-Intersection of the drawn areas.

**Comment by quincylvania** [comment]
@Spanholz If your system has key-repeat turned on then your can achieve this effect by holding down the spacebar while moving the mouse.

At some point I'd like to investigate "click and drag" as an alternative drawing option, particularly for touchscreens, but that's a separate issue from this.
