### ISSUE TITLE
Add building=chapel to presets

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7433]
Hi there.
With thousands of chapels everywhere in Western Europe, it would be great to have a preset and its icon on iD.

Thanks!

**Comment by quincylvania** [comment]
Looks like we already[ have this](https://github.com/openstreetmap/iD/blob/2.x/data/presets/presets/building/chapel.json)—perhaps it's not translated correctly in whatever locale you're using?

<img width="380" alt="Screen Shot 2020-03-19 at 4 37 46 PM" src="https://user-images.githubusercontent.com/2046746/77124403-0387d800-6a00-11ea-8f28-525dc3322edb.png">

**Comment by AntMadeira** [comment]
Yes, you're right @quincylvania but only for areas, not for points.
It would be nice to have this also for points.

Regards.

**Comment by quincylvania** [comment]
@AntMadeira Hmm iD only supports adding `building` features as areas since this is the preferred mapping pattern in OSM. I don't think we can make an exception for this.

**Comment by 1ec5** [comment]
If I’m not mistaken, `building=chapel` only indicates that a building is built as a chapel. A chapel that’s currently in use as a chapel would be mapped as `amenity=place_of_worship`. If the Place of Worship present doesn’t show up in search results for “chapel”, the localization you’re using might need to be adjusted.

**Comment by AntMadeira** [comment]
> 
> 
> @AntMadeira Hmm iD only supports adding `building` features as areas since this is the preferred mapping pattern in OSM. I don't think we can make an exception for this.

@quincylvania: yes, you're right. I was not thinking about the difference between amenities and buildings. Anyway, it's stated in the wiki that chapels can be mapped as points in special situations.
For example: it's common to have chapels inside churches. How do you map those with an area? 

Edit: I checked that on the wiki, and states: 
"A chapel is often part of a larger entity, such as a church, monastery but also non-religious entities such as schools, airports... In this case where it is not a separate building, it should not be mapped as a separate building, but amenity=place_of_worship can and should be mapped. "
That's fine for me. Case closed!
