### ISSUE TITLE
warning when editing more than one country or continent

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7434]
How about adding a warning when a user edits features among countries or even continents?
Of course we can't forbid such edits, because there may be a road, a route or an area that passes through two countries, but when I add one POI in New York and one in Moscow and save my edits, my changeset is visible in, e.g., Germany where I didn't edit anything.
Examples:
https://www.openstreetmap.org/changeset/82193707
https://www.openstreetmap.org/changeset/82190398

It could be a popup window for example "You're editing features in more than one country. It is better to limit your edits to one country, save changeset, and continue with a new changeset."

**Comment by bhousel** [comment]
I'm kind of wary about adding a message for this, since it's not the sort of warning the user can actually do anything about.  I wouldn't expect mappers to undo their work from the save screen just because it spans a big area.

iD could probably automatically split big changesets up into a handful of smaller regional changesets.

**Comment by manfredbrandl** [comment]
I support automatically splitting up wide area changesets into regional changesets.

**Comment by hungerburg** [comment]
ID is the editor of choice for jerks. ID makes it too easy to create BIG changesets, littering the map with hundred pieces of junk spanning hundreds of kilometers. These are very tough to revert or even analyzing alone.

**Comment by carstenhag** [comment]
Agree with @hungerburg, perhaps with a "you are editing features which are apart more than 50km" warning we can lower this amount.

**Comment by hungerburg** [comment]
Splitting a changeset into areas will be hairy.

Look at https://www.openstreetmap.org/changeset/76399678 - while still live - it is far too easy to create. Perhaps a scheme, where one has to earn some credit and/or enrol into the feature, before being allowed at all to map anything that does exceed a range of 1km or 10 at most; 50km may already be too far off for someone to tell fact from fiction.

@maro-21 Sorry for hijacking the thread, I hope it is not completely off topic. If I understand you correctly, the warning will be final, with no way around it.

PS: There is nothing of value in linked changeset, yet they gained praise for, e.g. putting a ford into a road, where there is a culvert or a bridge. (Please leave for the while, user is blocked.)

**Comment by maro-21** [comment]
What about a limit for new users with less than 50 edits?
As we can see in the link above, this was a user with 20 edits and still with walkthrough tags.


> ID is the editor of choice for jerks. ID makes it too easy to create BIG changesets, littering the map with hundred pieces of junk spanning hundreds of kilometers. These are very tough to revert or even analyzing alone.

Not only iD. You can do the same in JOSM, but I think most of the edits spanning more than one country or continent come from MAPS.ME.

> km

Kilometers are not good measure I tihnk. Because you can edit one node which is a member of a big relation, like international bus route and your edit will be visible in these countries.
So relations should be excluded from checking.


> @maro-21 Sorry for hijacking the thread, I hope it is not completely off topic. If I understand you correctly, the warning will be final, with no way around it.

No problem.
For new users (with less than 50 edits) there could be a message preventing further editing, like "you started editing in another country, please save your edits now and you can continue after saving." And for others there could be two buttons under the warning, e.g.:
- "Ok iD, you're right, save my edits now and I will continue with a new changeset."
- "No, get lost! I know what I'm doing!!"

Or maybe... after clicking Save and before clicing Send, iD could suggest splitting (if it's possible) changeset into countries and give opportunity to write different changeset comments.

**Comment by hungerburg** [comment]
Thank you @maro-21 for pardoning me. Maps.me, osmand or wheelmap batch uploads, that might be another story, unless your only concern is, where a changeset shows in the OSM history tab.

If not, then I still think, country is too big an area - The measure should be "local area", because that resonates with the number one selling-point on the openstreetmap webpage, namely "local knowledge". Where "local" need not mean the home-base of the user, but the centre of an on-ground visit, e.g.

What makes an area a local area is up for debate, but the concept should boost this issue, shouldn't it?

**Comment by jidanni** [comment]
What if all the McDonald's hamburger stores changed their name to "MacDonald's" worldwide.
Well, that could be taken care of with one changeset (for better or worse.)
So perhaps look instead at the problems with changeset examination tools.

**Comment by hungerburg** [comment]
I wouldn't have though ID capable of that, but if it is, all the more reason to safeguard such a powerful tool!

**Comment by quincylvania** [comment]
Hey guys 👋. I'm just catching up on this thread.

> ID is the editor of choice for jerks. ID makes it too easy to create BIG changesets, littering the map with hundred pieces of junk spanning hundreds of kilometers. These are very tough to revert or even analyzing alone.

@hungerburg I take issue with your effective tone here, no matter how you meant it. iD mappers are good people working within the limits of the software. I encourage you to make your points professionally if you want to be welcome in this repository and taken seriously. 

> What if all the McDonald's hamburger stores changed their name to "MacDonald's" worldwide.
> Well, that could be taken care of with one changeset (for better or worse.)

@jidanni Such a changeset couldn't be performed with iD. Thus, it's beyond the scope of this discussion.

---

I agree with @bhousel that showing a warning isn't particularly actionable or helpful. Most mappers are volunteers, after all, and we shouldn't be creating another technical or mental barrier to contributing.

Automatically splitting up changesets by region sounds like an okay solution. That's #5424 so I'm closing this as a duplicate. Another strategy might be to encourage saving edits more often.

**Comment by hungerburg** [comment]
Hello quincy, just a volunteer mapper here, no professional. Obviously not an iD mapper though, at least not exclusively, because then, I would not have written such a piece. In the end, it does not matter what I meant, the only thing that matters is, how it is understood. I appreciate that there are people here with some sense of humour who can decode compliments, even those, that one would not wish for.

**Comment by InsertUser** [comment]
While I still think the ability to split widely spaced edits would be the best embodiment (#5424), I appreciate that that is probably quite a lot of work to implement. I think there is value in a banner message that says something like:

"Your other unsaved edits are more than XXX from the current viewport, please consider saving or discarding those edits before editing here." 

It would be especially useful if there as a button to re-centre the viewport on the other edits (makes it easier to give a good changeset comment). Basing this on viewport position would would mean there is no need to ask editors to revert something they have already done (@bhousel 's concern). 

This would be more of a gentle nudge to save more often and can be done based on a generic distance or angle threshold without interpretation of political boundaries. My first guess at an appropriate threshold would be based on the zoom level at which the edit button first appears. Maybe 8 tiles at away at zoom 13?

**Comment by hungerburg** [comment]
no comment - the area of local_knowldge of some persons is truly impressive
https://www.openstreetmap.org/changeset/84125088
https://www.openstreetmap.org/changeset/83842160
…

**Comment by dpalacio** [comment]
Please reconsider.

Out of my area that I monitor, half of multi country spanning changesets come from iD users. And it isn't rude to say that many of them are careless and make breaking and erroneous changes on the other side of the world.

> we shouldn't be creating another technical or mental barrier to contributing.

This warning won't ever be seen by users that take care of their local area. Users that modify data outside of their regions should be held to a higher standard

**Comment by jjiglesiasg** [comment]
I agree

**Comment by doublah** [comment]
This seems like a problem that should be fixed on the OSM-side as these huge changesets happen regardless of editing software used.

**Comment by hungerburg** [comment]
This seems like a problem that should be fixed on the user-side as these huge changesets happen regardless of editing software used.

PS: iD is OSM
