### ISSUE TITLE
Wrong point is selected for dragging after disconnecting elements

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7438]
Not sure how else to put it in the title :p 

To reproduce:

1. Find a point where multiple elements meet
2. Disconnect them
3. Now you want to move one of them, but how do you select which one? The only logical way is to click on the element you want to move first, then click and drag the point.
4. Notice that almost every single time you do this you end up dragging a different element than the one you selected.
5. Have no idea how to actually drag the one you want to drag and end up having to scatter all the points out before you get to the one you wanted.
6. Manually drag all the other points back to their original place afterwards, with great frustration.

So, would it be possible to change this so that the point you drag is the one connected to the selected element? Thanks! :)

**Comment by quincylvania** [comment]
@forteller Thanks, I'm pretty sure this is the same underlying issue as #2206 but correct me if I'm wrong.
