### ISSUE TITLE
Rename Tram preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7440]
Is "Tram" a correct name for `railway=tram`?
I think it should be renamed becasue "tram" is a vehicle...
Although there is a meaning for "tram" as "One of the rails of a tramway"
https://en.wiktionary.org/wiki/tram#Noun
but it's marked as "obsolete".

**Comment by doublah** [comment]
Maybe tramway would be better?

**Comment by quincylvania** [comment]
@maro-21 Good point. A bunch of the railway presets looked unclear so I added "Track" to them, like Tram Track, Train Track, etc.

**Comment by maro-21** [comment]
Great! Thanks!

What about Railway Under Construction preset and similar? Check please if they're ok, or should also be renamed.

Railway Under Construction: `railway=construction`
Abandoned Railway: `railway=abandoned`
Disused Railway: `railway=disused`
Disused Railway Feature: `disused:railway=*` (this one is ok I think, becasue it applies not only to tracks)
