### ISSUE TITLE
Open air theater entry oddities

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7441]
To enter an Open air theater, currently the user marks an area, then enters
"Open" or "Open air" in the Search box, and clicks on "Amphitheater" and then manually changes
theatre:type=amphi
to
[theatre:type=open_air](https://wiki.openstreetmap.org/wiki/Tag:theatre:type%3Dopen_air) after looking it up on the wiki.
Odd that iD knows that "Open" is related to "Amphitheater", but there are no "Open" names to click on.

**Comment by quincylvania** [comment]
Looks like someone recently updated these `theater:type` wiki pages to split a difference between `open_air` and `amphi`. I don't see a proposal for these so the wiki pages seem arbitrary. I doubt the average iD mapper knows or cares about the difference between the terms so let's just leave this alone. The tags have rather low usage anyway.
