### ISSUE TITLE
Combine tool needs to bring in full form after combine

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7450]
Start with an old existing point node
```
amenity=place_of_worship
name=Nurdsburg temple
```
Now draw an area around it and use the Combine Tool.

OK, the node and the area are now combined. But where are the address fields etc.?

OK, we must choose Place of worship again in the search box to generate them, as "Area" didn't get updated after the Combine.

I.e., even though at the bottom we see now
```
amenity=place_of_worship
name=Nurdsburg temple
building=yes
```
but the rest of the template for a building has not been brought in.

**Comment by quincylvania** [comment]
Hmm this was indeed a bug in 2.17.2 but has already been fixed for the next release.
