### ISSUE TITLE
Update branch names referenced in repo files

### ISSUE THREAD

**Issue by UKChris-osm** [openstreetmap/iD#7453]
Hello all,

Coming over from the [Name-Suggestion-Index](https://github.com/osmlab/name-suggestion-index/) the branch name change has affected the project with some missing icons now occurring, and I think this is down to the taginfo.json file still referring in places to the **@master** branch, which I gather now no longer exists.

As iD is a much larger project, I don't want to interfere with any code as I don't know which files are linked / required by other files, so I though I would just ask here, is it possible to have the taginfo.json file reviewed, and any entries that still refer to **@master** changed to **@develop** or **@release**??

**Comment by quincylvania** [comment]
@UKChris-osm Thanks again for reporting. Fixed.

**Comment by johanricher** [comment]
The use of the `master` branch should also be removed in all the other files on _all_ the branches, at least the [active ones](https://github.com/openstreetmap/iD/branches/active).

**Comment by quincylvania** [comment]
> The use of the master branch should also be removed in all the other files on all the branches, at least the active ones.

We typically only update branches as-needed. Let me know if you're relying on a particular branch.

**Comment by johanricher** [comment]
I'm just pointing out that the `master` branch is used in several parts of your code (for example in `FAQ.md` on all the branches, including the current `develop`) and removing those in anticipation could avoid future breakages that would be hard for users to diagnose, like we had to.

**Comment by quincylvania** [comment]
@johanricher Good point. I updated all the instances I could find in d669bbef2afe804318484df6127db5b360d900bd.

**Comment by UKChris-osm** [comment]
If a release of iD 2.17.3 is due soon, is it possible to have the Name Suggestion Index updated before it's published (@bhousel)??

Quite a few entries have been added to the NSI since NSIv3.7.0 which I believe is the current version associated with iD 2.17.2

**Comment by quincylvania** [comment]
> If a release of iD 2.17.3 is due soon, is it possible to have the Name Suggestion Index updated before it's published

@UKChris-osm Yep, we can include an NSI release.
