### ISSUE TITLE
Define better z-index levels

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/iD#7457]
We are having some problems with `z-index` when embedding iD (https://github.com/hotosm/tasking-manager/issues/2554). That one we can solve easily, but maybe it would be worth defining better the `z-index` levels for iD in order to avoid conflicts... Current values:

![image](https://user-images.githubusercontent.com/666291/77431441-76f06780-6dbb-11ea-8834-63a83db7a221.png)

**Comment by quincylvania** [comment]
@willemarcel Hmm good point. I can audit these and try limiting them to a smaller range.

**Comment by quincylvania** [comment]
Turns out we can make all of iD's elements stack relative to the container and not sandwich external elements. This way we can leave all the internal `z-index` values alone.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
