### ISSUE TITLE
Gap on combobox dropdowns

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/iD#7458]
![image](https://user-images.githubusercontent.com/666291/77433099-b455f480-6dbd-11ea-8a16-0d2952b9e59f.png)

When running iD embedded on Tasking Manager, there is a gap between the add field select position and the dropdown contents. it happens even without scrolling the page.

**Comment by willemarcel** [comment]
It also happens on other dropdowns

![image](https://user-images.githubusercontent.com/666291/77435047-87571100-6dc0-11ea-95d6-ef847c1adfb3.png)

**Comment by quincylvania** [comment]
Looks like the vertical positioning code uses the client bounding rect, so it's offset by the height of your top toolbar. We should make it relative instead.
