### ISSUE TITLE
Add azimuth to Measurement tool

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7459]
Azimuth would be a very simple addition to the measurement tool.

Much more simpler than the current Centroid.

The user currently can get the length, but not the azimuth.

Have it only active on the first segment of a line, fine. But at least provide it.

Azimuth is a basic component of all other such "ruler" tools I have ever seen.

**Comment by jidanni** [comment]
https://support.google.com/maps/forum/AAAAQuUrST8LqY4a9_vWKA

**Comment by quincylvania** [comment]
@jidanni Sorry, but this doesn't make any sense to me. The measurement panel isn't some multipurpose "ruler" tool, it gives basic geometry info about the selected feature. You can't calculate the azimuth for a line with more than two points, and only using the first segment would be arbitrary and confusing. In any case, I don't know how showing this would help with mapping. Please use a data viewing tool instead.

**Comment by jidanni** [comment]
Well I filed https://help.openstreetmap.org/questions/73733/make-a-house-of-given-size-and-angle .

**Comment by jidanni** [comment]
Well all I can say is the Measurement Tool has many many length features, but no angle features.
One can measure Area:0.9182 m², Perimeter:9.139 m, lengths, centroids, but nothing about angles (directions). As we know the simplest vector is composed of a length and a direction.

**Comment by jidanni** [comment]
(I forgot to add examples)
Viking:
![viking_ruler](https://user-images.githubusercontent.com/1230959/77830819-2cc60800-7166-11ea-8657-0465da5892aa.jpg)

Google Earth:
![google_earth](https://user-images.githubusercontent.com/1230959/77830827-3c455100-7166-11ea-8d14-04c437074a8c.jpg)

**Comment by Mahabarata** [comment]
I agree with this issue, it would be a great improvement of the measurement tool.

**Comment by jidanni** [comment]
Just today wanted to make sure my two point wall was 177&deg;. Oh well&hellip;
