### ISSUE TITLE
Edit Geocode Reverse address

### ISSUE THREAD

**Issue by megaboxbrasil** [openstreetmap/iD#7461]
How to edit the addresses that appear in the Geocode Nominatim search (Reverse geocode)

**Comment by quincylvania** [comment]
Hi and welcome, @megaboxbrasil.

I'm not totally sure what you're asking, but updating an address in OpenStreetMap should eventually update it in Nominatim search.

**Comment by megaboxbrasil** [comment]
When decoding latitude and longitude on a given street, it returns a wrong street name. Where can I change this?

**Comment by quincylvania** [comment]
You can make sure the street and all nearby addresses have the correct street name in OpenStreetMap.

<img width="580" alt="Screen Shot 2020-03-25 at 12 54 21 PM" src="https://user-images.githubusercontent.com/2046746/77579623-dcb22180-6e97-11ea-8ca6-b20e344fe855.png">
<img width="549" alt="Screen Shot 2020-03-25 at 12 54 32 PM" src="https://user-images.githubusercontent.com/2046746/77579622-db80f480-6e97-11ea-9f7e-311359027f27.png">

If they are all correct then try asking the [help forums](https://forum.openstreetmap.org/viewforum.php?id=10) or the [Nominatim project](https://github.com/osm-search/Nominatim). I don't think your question is about the iD project in particular.

**Comment by megaboxbrasil** [comment]
This was done, but it remains with the wrong name in geocoding. The name on the map layer is ok
![wk3](https://user-images.githubusercontent.com/62397353/77580044-12680200-6eba-11ea-9740-6288fc671464.png)

**Comment by megaboxbrasil** [comment]
This same street also looks wrong in the organization's own, but with a different third name
![wk4](https://user-images.githubusercontent.com/62397353/77580418-bce02500-6eba-11ea-8d39-22d96f518133.png)

**Comment by megaboxbrasil** [comment]
A name appears on my server, another name appears on the organization's server. Only on the map layer that is right

**Comment by quincylvania** [comment]
@megaboxbrasil Different servers update at different schedules. I can't really help you any more than that.

**Comment by megaboxbrasil** [comment]
Understand.

But it is wrong on the OpenStreetMap website. Only the name of the map layer is right. The geocoding service is wrong. I wish I could contribute to that, but from what it seems to me, so you can contribute with a map layer
