### ISSUE TITLE
Bridges: prompt for name and ref fields

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7462]
![29999-6](https://user-images.githubusercontent.com/1230959/77509818-636efa80-6ea8-11ea-8f10-914c4d8b616b.jpg)
Besides "Type" and "Layer", the very important "Name" (Washington Memorial Bridge), and ref fields should also be listed at the bottom. (Else the bridge will only have the name of the highway it carries.)

**Comment by jidanni** [comment]
(I am not clear about the [technicalities](https://wiki.openstreetmap.org/wiki/Talk:Key:bridge#Naming) underneath the hood.)

**Comment by jidanni** [comment]
However [my try](https://www.openstreetmap.org/way/784403030) didn't [work](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer).

**Comment by jidanni** [comment]
I am saying iD needs a way for the user to say this is Washington bridge, and also Highway 1, in the right recipe so the user later will see all that in the renderer.

**Comment by quincylvania** [comment]
@jidanni The current best practice is to map bridges separately as areas using `man_made=bridge`. This is even mentioned on the wiki at [`bridge:name`](https://wiki.openstreetmap.org/wiki/Key:bridge:name). This follows [one feature, one element](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element), will let you easily enter multilingual bridge names, and will make the bridge name render on the default map.
