### ISSUE TITLE
Lopsided bridges sometimes created during problem resolution

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7463]
In [certain cases](https://www.openstreetmap.org/changeset/82602496), a lopsided bridge is created, 
![15156-9](https://user-images.githubusercontent.com/1230959/77514246-6d492b80-6eb1-11ea-934e-9cc4f005b656.jpg)
when the user chooses "Add a bridge" from the problem resolution choices.

It would be better to always create bridges that have the same length on both sides of the stream they cross.

**Comment by quincylvania** [comment]
The way this works is that the bridge length is estimated heuristically and then one side is shortened since there's a junction. Though I suppose the junction could indicate that the other side of the bridge might also be shorter.

**Comment by jidanni** [comment]
Here's a scale bar to see what we are talking about,
![10861-1](https://user-images.githubusercontent.com/1230959/77579820-e4b0a680-6f15-11ea-8875-fe5f32ecd3ce.jpg)

**Comment by jidanni** [comment]
So maybe always make bridges end 5 meters beyond the item being crossed, snapping to anything nearer, or anything farther if within one meter. Something like that. 

Hmmm, I bet the current algorithm is the same, except using 20 meters. Hmmm.

**Comment by jidanni** [comment]
Well [here](https://wiki.openstreetmap.org/wiki/File:Bridge_Name_And_Ref_Taiwan.jpg)'s the bridge. [Itty bitty](https://goo.gl/maps/Qs6Ysn9ARPqyAWnW9).

**Comment by jidanni** [comment]
Well, maybe there is no one-size-fits-all. Some bridges are longer, some shorter. That there are some approach ramps close to the east side shouldn't have some side effect on the west side.
So maybe "if the user isn't happy with the result he can edit it before saving." So I suppose we should close this bug.

**Comment by quincylvania** [comment]
> So maybe "if the user isn't happy with the result he can edit it before saving." So I suppose we should close this bug.

Sounds good 👍
