### ISSUE TITLE
Offer to add a gate when path crosses fence

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7464]
Too many people forget to add this, and so you wonder if there's something wrong: Does the path really cross the fence here? Is there really a fence? etc.

It would be helpful if iD could remind people of adding a gate, and offer a one-click way of doing it. If you in addition have any way of reminding people to add information about who's allowed to pass the gate, that would be great :)

**Comment by quincylvania** [comment]
@forteller Thanks, this is #6349.

**Comment by forteller** [comment]
I promise I searched! :)

**Comment by quincylvania** [comment]
> I promise I searched! :)

I'm sure! I've done the same thing, even for issues I'd already opened 😆

**Comment by forteller** [comment]
I'm glad I'm not the only one! 😁 #7387
