### ISSUE TITLE
Make it easier to add parking spaces for disabled people

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7465]
I _try_ to spend most of my time mapping on things that I think will have real world value for people, and especially for people with special needs (benches, drinking water, toilets, etc), and so I think marking where there are parking spaces for disabled people is especially important.

Unfortunately, trying to do this in iD was a difficult and frustrating task for me.

First there's no specific feature for this in the Feature dropdown. Second, after choosing Parking lot there's no visible field for this. Then there's nothing obviously relevant in the Fields drop-down, except for "Wheelchair access", but I'm almost positive that's just to indicate if you can access the area with a wheelchair, not if the parking space is exclusively for disabled people. Lastly, there's no obvious tag in the Tags dropdown either.

Then I looked in the wiki, and I found this total mess: https://wiki.openstreetmap.org/wiki/How_to_map_for_the_needs_of_people_with_disabilities#Designated_parking_space I mean, seriously, am I supposed to choose the best way of all those possibilities and do all of that for every single parking space?

Please do something with this. Either add a specific feature for this, or a field that's visible by default for tagging it as a space for disabled people.

I know this is the editor only, and I'm not asking you to change how these spaces are tagged, just asking that we shouldn't have to tag them manually.

Thanks! :)

**Comment by quincylvania** [comment]
Thanks, @forteller, I didn't realize this tagging was so well developed already. It's always great to make accessible mapping easier. I added an Accessible Parking Space preset and an Accessible Spaces field to parking presets.

**Comment by forteller** [comment]
Wow, that was fast! Thank you! :)
