### ISSUE TITLE
Use distinct mouse pointer styles for point and area

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7468]
I have a few features that I use a lot, but also switch between using as points or as areas (bike parking, playgrounds, etc). When I select one of them and click where I want it I sometimes have forgotten that last time I used it I changed it from one to the other. This really annoys me, because then my rhythm is broken and I must cancel what I did, change style and click on the place again. 

All of this horribleness (:P) could easily be avoided if the mouse pointer gave you some hint of whether clicking would set a point or start an area. For example area could still be the crosshairs used today and point could be a circle, or a drop shape. 

Or something else. As long as you can tell the difference at a glance that would make mapping faster and more fun. Thanks!

**Comment by quincylvania** [comment]
@forteller I assume you're talking in reference to the v3 toolbar? I agree we need to make it clearer what geometry you're drawing—I really like this cursor style idea 👍

**Comment by forteller** [comment]
Yes, exactly. In the toolbar in v3 you can often choose between point, line and area, or just point and area, but the cursor stays the same so there's no visual cue on the area where you're working what type of thing you will get when you click :)

**Comment by forteller** [comment]
This was only relevant for the discontinued v3 workflow, so I'm closing this.
