### ISSUE TITLE
"Add a bridge" should use new practices

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7469]
Regarding the warning

*Residential Road crosses stream*
- *Connect using a ford*
- *Add a bridge*
- etc.

Choosing "Add a bridge" currently creates
```
highway=residential
bridge=yes
layer=1
```
it instead should be updated to use the practices mentioned in https://github.com/openstreetmap/iD/issues/7462#issuecomment-604061422

**Comment by jidanni** [comment]
So as far as the geometry issues, it should start making areas instead of lines.
I suppose the length of the area could be the same as the length of the current lines it makes.
But for width, I suppose it needs to make a standard width, based on the highway grade it is operating on. I guess for the rare case it didn't make the bridge wide enough (some ceremonial bridges) the user could stretch it out manually with his mouse.
 
And then there are the different tags needed (man_made=bridge instead of bridge=yes, etc.)

I suppose this (problem resolver) tool will become the main way of entering bridges: no reason to try to figure out how one is supposed to manually create bridges these days (long hours pouring over the wiki manuals that change often). Instead just drape a road over a stream, and try to save, triggering the resolver, and then choose "Add a bridge" and fill out the form!

OK reading https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge apparently this tool needs to also attach the area to the road running on top of it, but not attach the area to the stream running under it... but at the same time not anymore triggering "road crosses stream"...

**Comment by quincylvania** [comment]
@jidanni The `man_made=bridge` tag should be used on separate features entirely and does not replace `bridge=yes` + `layer=1` on the road. It's also not really relevant to the crossing ways issue so it'd be weird to start adding them automatically.

**Comment by polarbearing** [comment]
@jidanni - "make a standard width, based on the highway grade" / "attach the area to the road":

I tried to explain you in the wiki talk page already: The bridge outline (man_made=bridge) is a separate object from the road over the bridge, only the road is tagged bridge=yes. Assumptions of width shout **not** be done automatically, e.g. a bridge could carry multiple highways.

**Comment by jidanni** [comment]
I used to make bridges separately as areas. But then for the last few month I have let the problem resolver help me make them (as lines).
OK, could somebody edit 
https://www.openstreetmap.org/way/784403030
for me making it perfect. And then from then on I shall make them that way. Thanks! You can see there is a wikimedia_commons link so you can see how it looks on the ground.

**Comment by polarbearing** [comment]
@jidanni - I have shortened the road and added the man_made=bridge object for the bridge you asked for, and transferred the bridge:name and bridge:ref to the man_made object as name and ref.
