### ISSUE TITLE
Unable to close KeepRight issue

### ISSUE THREAD

**Issue by MRVDH** [openstreetmap/iD#7470]
Pressing Close (Error Fixed) does not do anything

![image](https://user-images.githubusercontent.com/6686385/77766782-67358500-7040-11ea-9736-f62bc1f0eb44.png)
![image](https://user-images.githubusercontent.com/6686385/77766838-7ae0eb80-7040-11ea-9593-f7d7b64b7bd0.png)
![image](https://user-images.githubusercontent.com/6686385/77766876-846a5380-7040-11ea-99bc-b15428541d16.png)
![image](https://user-images.githubusercontent.com/6686385/77766893-8a603480-7040-11ea-9c07-5c83e2f36027.png)

**Comment by kymckay** [comment]
Duplicate of #6881

Should be fixed in development version and so next release (can test this at https://ideditor.netlify.com if you'd like to confirm)

**Comment by MRVDH** [comment]
Yep, just tested and seems to work as expected there. Thanks!
