### ISSUE TITLE
Drop up when drop down will go bellow screen

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7471]
The situation in the screenshot is a bit annoying. Could the drop down drop up in these situations (and only in these)?
![Screenshot from 2020-03-26 21-23-54](https://user-images.githubusercontent.com/343561/77791513-0b322700-7067-11ea-808a-9d646afd7e6c.png)

**Comment by quincylvania** [comment]
@forteller You should just be able to scroll the sidebar up? We could possibly do this automatically. I'm not sure "dropping up" would be a great experience.

**Comment by forteller** [comment]
I could, but it's one more step. If I have to do this for many similar features in the same area having one more step for every single one of them might be the thing that makes me not bother doing it.

**Comment by jgscherber** [comment]
"Dropping up" is a common UI pattern. I think from a usability perspective, it is the expected behavior.

As a quick example - this is the hamburger menu in Chrome "dropping up" when the browser is near the bottom of the screen.

![image](https://user-images.githubusercontent.com/6207661/80818664-3ee9fa80-8b99-11ea-9e46-d0f1fe174e2c.png)

**Comment by quincylvania** [comment]
> "Dropping up" is a common UI pattern.

@jgscherber Yes, it is common to position menus and popovers. But not for showing search suggestions in a text input, methinks.

**Comment by quincylvania** [comment]
Closing this for now as low-impact. You can just scroll down or type the value you want.

> If I have to do this for many similar features in the same area having one more step for every single one of them might be the thing that makes me not bother doing it.

The next version of iD will have field editing for multiselection, so you can just select all these features and change the value for all of them at once. Try it out [here](https://ideditor.netlify.app/).
