### ISSUE TITLE
Suggestion: Optionally using whole viewport as single bounding box for layers

### ISSUE THREAD

**Issue by kallejre** [openstreetmap/iD#7473]
I recently made pull request to editor-layer-index about adding some new layers for Estonia. What I noticed, was that all layers there but one were based of WMS layers, that supported bounding boxes with any aspect ratio (not just squares). All these layers are built for web app, which native behaviour is to use on-demand rendering, where bounding box of requested layer is browsers viewport.

I understand that iD uses boundaries of tiles as bbox value for several optimisation reasons. For example, treating each tile as separate box reduces amount of code written and makes integrating such layers to rest of iD app easier. Loading tiles in smaller chunks allows user to see results quicker (single downloaded file is smaller) and server owners could set up caching to save time on rendering by sharing primarly standardized tiles.

Now problem is that some servers are designed from ground up to natively serve requests to render on demand (including primary Estonian tile server). They have highly optimized internal rendering and database query systems, but lack serving loads of parallel requests. Things can get worse. If each tile is rendered independently from vector-based text layer, things will get clogged. Picture of how iD-based tile testing app shows city name in middle of each tile (unwanted behaviour): 
![Screenshot of unwanted behaviour](https://user-images.githubusercontent.com/22601238/77793966-bf39af00-7073-11ea-9e14-737420d6973d.png)

My suggestion to counter it is to choose big non-standard bounding box based on size of editor window. To avoid redownloading tile every time user moves map, box should have small buffer depending on size of viewport (100-300 px in each direction), screen resolution and prediction, in which direction map will be moved next.

Decision, whether to use tiles or full-size bbox should be made by end user or imagery index contributor.

**Comment by quincylvania** [comment]
Interesting. Do you know how widespread this pattern is? It'd be a lot of development work to build an alternative rendering flow and that screenshot doesn't really look that bad. The data is visible and the repeated labels seem like a relatively minor annoyance.

You might actually be able to tick iD into fetching bigger tiles by setting `tile-size`, but I'm not sure.

**Comment by kallejre** [comment]
I honestly don't think it's common pattern/problem. It only applies to (some niche WMS) layers, where text is positioned on map tiles based on user's bounding box. Situation could look worse if there are longer text phrases, clipping could occur. Example from testing layer (not added to imagery index yet): 
![pilt](https://user-images.githubusercontent.com/22601238/79501814-583a6500-8037-11ea-9039-cb9e9abccddf.png)
Using bigger tiles (1000x1000px) could be reliable workaround. Unfortunately, iD's UI doesn't seem to have such feature or does it?

PS on other loosely related note. Is iD hardcoded to use very limited set of global CRSs? I tried to understand code on my own, but no gain. Adding support for Estonian EPSG:3301 would allow use of 150+ more layers, mostly benefiting OHM project.

**Comment by quincylvania** [comment]
> I honestly don't think it's common pattern/problem. It only applies to (some niche WMS) layers, where text is positioned on map tiles based on user's bounding box.

Okay, in this case I'm closing this issue as low-impact. We don't have the development resources to make every possible tile layer look perfect, unfortunately. Though if a volunteer contributor wants to take this on then that could be okay.

> Is iD hardcoded to use very limited set of global CRSs?

Yes, and adding support for more would be non-trivial. iD would have to either warp raster tiles or project all vector data and neither sound pleasant if they're avoidable.
