### ISSUE TITLE
Bing Streeetside overlay persists after disabling

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#7474]
Preview site, 0328e10

Noticed that the overlay was still there after I disabled the feature. Didn't change after checking and unchecking a few times. I think I could load images, and it definitely was loading new areas. Can't reproduce; it went away after uploading changeset.

![screenshot](https://user-images.githubusercontent.com/25139386/77815205-02554b80-708f-11ea-978f-fc7bcdbc6ac8.jpg)

**Comment by quincylvania** [comment]
@rivermont Hmm I have no idea what's going on here but I don't see this on the `develop` branch. Since we've stopped development on the v3 prototype branch I'm closing this as won't fix. Elements of that branch are being manually pulled back to `develop`.
