### ISSUE TITLE
Edit Kebab Fast Food preset - change icon

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7475]
The icon for Kebab Fast Food preset is the same as for a restaurant preset. It should be the same as for Fast Food preset.

**Comment by quincylvania** [comment]
Let's just make a custom icon for this preset. Re: #7068

**Comment by quincylvania** [comment]
<img width="281" alt="Screen Shot 2020-04-10 at 11 26 59 AM" src="https://user-images.githubusercontent.com/2046746/79013742-38c6a800-7b1e-11ea-91cd-1110868a2bff.png">
