### ISSUE TITLE
Edit Nail Salon preset - change icon

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7476]
Currently the icon for Nail Salon preset is a shopping cart icon. It should be the same as for Beauty Shop preset.

**Comment by quincylvania** [comment]
This has already been updated for the next version of iD. You can check out the development preview at: https://ideditor.netlify.com

<img width="383" alt="Screen Shot 2020-03-28 at 1 19 28 PM" src="https://user-images.githubusercontent.com/2046746/77832934-c786fe00-70f6-11ea-8054-d687fa01487e.png">

Re: #7068
