### ISSUE TITLE
Add smoothness to Parking Lot and Service Road presets

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7477]
Smoothness key is used together with `surface=`. Parking Lot and Service Road presets already have a `surface=` key, but they don't have `smoothness=`.

**Comment by maro-21** [comment]
What about parking lots?

**Comment by quincylvania** [comment]
@maro-21 I'd rather not add these for `amenity=parking` features since they can also have `parking=multi-storey` or `parking=underground`. Asking "what's the smoothness of a parking garage" sounds weird. You can add `smoothness` to the parking aisles instead.
