### ISSUE TITLE
Add amenity=vacuum_cleaner

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7483]
A vacuum cleaner is often found at gas stations or car washes.
It is used 682 times.
https://taginfo.openstreetmap.org/tags/amenity=vacuum_cleaner
We already have a preset for Compressed Air, it would also be good to have a Vacuum Cleaner preset.

**Comment by quincylvania** [comment]
I've held off on this so far because I think we need a decent icon. At least in the US, most people who hear "vacuum cleaner" first think of the portable household appliance, which this is not. An icon will help. I'm also considering the name "Vacuum Station" or something like that.

**Comment by maro-21** [comment]
How about "vacuum cleaner for cars"?

**Comment by 1ec5** [comment]
Sometimes this equipment is called an “automotive vacuum”, but that can also be confused with handheld vacuums that one might buy to keep their car tidy. “Vacuum Station” sounds pretty intuitive to me (in American English), but it does have [an unrelated meaning](https://en.wikipedia.org/wiki/Vacuum_sewer), so how about “Vacuum Cleaning Station” or (if we can make this assumption) “Self-Service Vacuum Station”? Both terms are apparently used to describe this kind of facility.
