### ISSUE TITLE
Add healthcare=nutrition_counseling

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7484]
I know that this tag is not used very often, but there is no other way to map a dietitian...
Maybe after having its preset in iD, there will be more correctly tagged dietitians?
https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dnutrition_counselling

**Comment by jeisenbe** [comment]
The page https://wiki.openstreetmap.org/wiki/Key:healthcare is not very clear, but seems to suggest using the combination of `healthcare=counselling` + `healthcare:counselling=nutrition`, which has been used 59 times (http://overpass-turbo.eu/s/Tn1), or `healthcare=counselling` + `healthcare:counselling=dietitian`, used 116 times. (http://overpass-turbo.eu/s/Tn2), compared to 34 uses of `healthcare=nutrition_counselling`

**Comment by maro-21** [comment]
Oh, it's a pity that there isn't one tag for this but three!
I was influenced by the icon on Wiki for OSM Carto, but looks like it's not true, it's not rendered.
You can close the issue.
