### ISSUE TITLE
I want to update our community

### ISSUE THREAD

**Issue by ghost** [openstreetmap/iD#7495]
It is about the Galician community in Galicia: https://openstreetmap.community/

There have been changes in the telegram link for this: https://t.me/osmgalicia

It would be interesting to add this twitter: https://twitter.com/xeoinquedos

And finally add that these things are in the Galician language! It would not hurt to add the Portuguese community within Galicia too, since there are things that we share...

Thanks a lot!

**Comment by quincylvania** [comment]
Hello and welcome, @Ivans-Git. The OSM communities listed in iD actually come from the [osm-community-index](https://github.com/osmlab/osm-community-index) project, so you'll need to open an issue or pull request over there 👉
