### ISSUE TITLE
Driving school mostly not buildings

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7497]
Aren't [driving schools](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddriving_school) mostly not indoors, so maybe the preset should not have building=yes.
Or help the user make the choice: is this the office of the school, or the grounds of the school, or at least the parking lot of the school. OK, some don't have their own driving range but use city streets, yes.

**Comment by quincylvania** [comment]
The majority of these drawn as areas have `building` tags so I think it's fine as-is. Mappers can always remove the `building` tag as-needed.
