### ISSUE TITLE
Edit Transit Stopping Location

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7499]
Do we need `level=` for `public_transport=stop_position`s?
https://github.com/openstreetmap/iD/blob/72a99673a0328ba4f44c58dd110797cc733f7007/data/presets/presets/public_transport/stop_position.json#L9-L10
Although it is used with `public_transport=stop_position` in 0.36% cases, I think we can remove it from MoreFields because it's not one of the basic tags:
https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_position
https://taginfo.openstreetmap.org/tags/public_transport=stop_position#combinations
I didn't check if they're used correctly, but shouldn't it be rather used with `public_transport=platform`?

**Comment by tomasokol** [comment]
public_transport=stop_position must be used on a line (a node on a line). So the level must be the same – defined by said line. 
So I agree with @maro-21

**Comment by quincylvania** [comment]
> public_transport=stop_position must be used on a line (a node on a line). So the level must be the same – defined by said line.

This makes sense. Though I don't see much harm if mappers add `level` on the stop position redundantly. Frankly this type of issue is of pretty minor concern.
