### ISSUE TITLE
Description for Cliff feature links to non-existent wiki page

### ISSUE THREAD

**Issue by DavidMetcalfe** [openstreetmap/iD#7500]
The infobox description for "Cliff" appears to have a broken URL attached to it.

![image](https://user-images.githubusercontent.com/80915/78328225-872ee200-7533-11ea-857e-7feac3ef768b.png)

When clicking "View documentation," the destination URL is "https://wiki.openstreetmap.org/wiki/V" instead of what should probably be "https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcliff"

**Comment by quincylvania** [comment]
Hello and welcome, @DavidMetcalfe. Looks like the link was broken in the [wikibase item](https://wiki.openstreetmap.org/wiki/Item:Q4715). I'd guess someone was trying to copy-and-paste and missed the modifier key. In any case, I've fixed it now.

<img width="941" alt="Screen Shot 2020-04-03 at 10 18 27 AM" src="https://user-images.githubusercontent.com/2046746/78387851-d822f280-7594-11ea-9263-c5a045aaa685.png">
