### ISSUE TITLE
Assure iD loads with the changeset comment set on the URL

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/iD#7504]
On the embedded iD on TM4, we start iD with the `comment=` param on the URL. On the first time we load iD, the changeset comment is set correctly, but...

- If I modify (or erase the comment), but don't save the changeset, it loads the modified (or empty) comment next time.
- If I modify and save the changeset, it loads the project's comment.

I tried setting the comment field on localStorage, but it didn't solve the problem. I would like to assure that every time a user loads iD on TM, the changeset comment is set, because right now it's the way we can identify the changesets related to the projects.

I also tried to set the hashtag with the URL query param, but the same behaviour occurs.

When pressing F5, or loading a new browser window, it loads the correct changeset comment.

**Comment by clearJSer** [comment]
hi,@willemarcel  , I need your help for develop iD .  Local development and debugging is particularly slow. Have you encountered it? How to solve?

**Comment by quincylvania** [comment]
@willemarcel I _think_ I fixed these issues but please test the latest [2.17.3](https://github.com/openstreetmap/iD/tree/2.17.3) branch.

@clearJSer As you've seen, instead of posting unrelated comments you can simply post a separate issue and someone will respond within a day or two 🙂
