### ISSUE TITLE
How do I develop a debug ID ？？？

### ISSUE THREAD

**Issue by clearJSer** [openstreetmap/iD#7506]
![image](https://user-images.githubusercontent.com/29148598/78986919-025d4d00-7b5f-11ea-8d68-7095e22e12ef.png)
Why is the development and debugging mode so slow? How did you develop and debug?
The command I executed: npm run start
release branch

2. Found under the develop branch can not be developed and debugged? How to do?

For help. . .

**Comment by quincylvania** [comment]
@clearJSer Build time is something we recently worked to reduce. The default branch, [`develop`](https://github.com/openstreetmap/iD/tree/develop), compiles in under 20 seconds on my laptop. The `release` branch takes considerably longer.

**Comment by quincylvania** [comment]
See also https://github.com/openstreetmap/iD/issues/7505#issuecomment-612126213.
