### ISSUE TITLE
Excluded area is shown as a part of multipolygon area

### ISSUE THREAD

**Issue by soshial** [openstreetmap/iD#7511]
This national park has several excluded parts. Let's look at the top-middle part which excludes this town, called Ķaunata.

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/100644/79065253-b70a8200-7cb7-11ea-941b-d6b512261ca7.png">

The excluded town is marked by red circle:

![image](https://user-images.githubusercontent.com/100644/79065298-f6d16980-7cb7-11ea-8769-0ceba2f3253e.png)

**THE BUG**. Why does iD displays the excluded city as if this park is inside this city? And the border band (that show difference between a line and an area), should be outside of the border. Isn't it? 

![image](https://user-images.githubusercontent.com/100644/79065307-02bd2b80-7cb8-11ea-8f88-f9b6adf5d2c2.png)

**Comment by quincylvania** [comment]
Hi and welcome, @soshial.

This is a longstanding issue we've been tracking at #1201. For efficiency, iD only downloads the relation members in view. In your example, no outer members are downloaded so SVG renders the inner part as an outer part. You can manually download more parts in the Members section of the inspector and watch the rendering update.

#6656 would address this problem, but we're waiting for an OSM API endpoint that returns many full entities in a performant manner. See https://github.com/openstreetmap/openstreetmap-website/issues/2348.

**Comment by soshial** [comment]
Thanks for the profound explanation.
