### ISSUE TITLE
remove maxspeed=* field from living street preset in Germany

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [openstreetmap/iD#7513]
Hi,
as I saw that #7085 was merged, 
would it then be possible to drop the "maxspeed" field from highway=living_street in Germany?

In Germany, living streets are maxspeed=walk not only as default, but **implicit**. There not just only should not, but mappers consensed that there has no to set any maxspeed=* value on these ways, because "walk" is ca. 7 Km/h but some courts are not clear about, and the second thing is that **there is no speed limit sign** at all.

Readable under "Hinweise" here: https://wiki.openstreetmap.org/wiki/DE:Tag:highway%3Dliving_street (in german, so country-specific).

**Comment by quincylvania** [comment]
Yes, we can now limit fields to specific countries, but not also for specific presets. So we'd need to add a duplicate `maxspeed` field with different properties to accomplish this. Which is a bit hacky and breaks stuff like multiselection field editing. Is it really a problem to continue showing this field or is it just an inconvenience?

**Comment by Elefant-aus-Wuppertal** [comment]
Hmm, nah, calling it a problem might be a bit too much, but people just have the feeling to fill something into this field when it is there. But if it would be too difficult to change this, I could live with letting it stay.

**Comment by quincylvania** [comment]
@Lukas458 Okay, thanks for understanding. Maybe in the future we could come up with a better solution if more situations like this arise.
