### ISSUE TITLE
Add ability to map quarries as nodes

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#7515]

**Comment by quincylvania** [comment]
Hmm we really try not to support any `landuse` features as points. Looks like `landuse=quarry` is used on over 35,000 nodes but most of those are from GNIS imports.

**Comment by quincylvania** [comment]
> we really try not to support any `landuse` features as points

I guess we already break this a few times and the wiki recommends tagging plenty of `landuse` features as points, including `quarry`. Gotta let OSM be OSM.

**Comment by Adamant36** [comment]
Thanks. It does seem like OSM is a little inconsistent on tagging landuse as points. I think it's fine in this situation though.
