### ISSUE TITLE
Use different icon for power pole vs. utility pole

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7516]
![29541-9](https://user-images.githubusercontent.com/1230959/79541970-616e1500-80bd-11ea-9fab-27bce3108c42.jpg)
![32659-10](https://user-images.githubusercontent.com/1230959/79541984-67fc8c80-80bd-11ea-9e5f-f291bd89484a.jpg)
Could a slightly different icon be used for power vs. utility (telephone) poles please?

**Comment by jidanni** [comment]
Put lightning bolts on its insulators, make it look rougher and tougher, anything...
[Plenty of choices](https://www.google.com.tw/search?q=utility+pole+icon&tbm=isch) for both. No need to use 100% the same.

**Comment by manfredbrandl** [comment]
I suggest a "heavier" Icon for Power Pole maybe like this: ![image](https://user-images.githubusercontent.com/5360273/79581603-f3c8e580-80ca-11ea-9473-87bf45a33d6e.png)

**Comment by quincylvania** [comment]
<img width="376" alt="Screen Shot 2020-04-22 at 12 10 04 PM" src="https://user-images.githubusercontent.com/2046746/80023344-3bb48780-8492-11ea-9c26-e3ca7a27716d.png">
