### ISSUE TITLE
Add healthcare:speciality explanation when hovering over the terms

### ISSUE THREAD

**Issue by fenymufyd** [openstreetmap/iD#7517]
Add healthcare:speciality explanation when hovering over the terms

When you add speciality in a hospital, i dont know that "Pediatrics is the branch of medicine that involves the medical care of infants, children, and adolescents" but i know the hospital has speciality in children so i keep searching what those word means over and over.  
It might help to know what the word means when you hover over it

heres a picture if it helps
![picture](https://user-images.githubusercontent.com/20435546/79630636-9d6cad00-8185-11ea-809a-573a94caf658.png)

**Comment by quincylvania** [comment]
Hi and welcome, @Jinkiesz. Looks like this issue fell through the cracks back in April.

Anyway, iD pulls those values from TagInfo, which I believe gets the descriptions from the OSM wiki. Check out the [Description column for `healthcare:speciality` values](https://taginfo.openstreetmap.org/keys/healthcare%3Aspeciality#values). Compare it to a [key where all common values have wiki pages](https://taginfo.openstreetmap.org/keys/amenity#values). Essentially this isn't an iD issue, but if the community adds the documentation then iD will get it automatically.
