### ISSUE TITLE
Validator: power=station deprecated

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7520]
It seems `power=station` could be added to the list of https://github.com/openstreetmap/iD/blob/develop/data/deprecated.json
see also the wiki: https://wiki.openstreetmap.org/wiki/Tag:power%3Dstation
see also carto v5.1.0 removed rendering: https://github.com/gravitystorm/openstreetmap-carto/pull/4088

**Comment by bhousel** [comment]
I think we can only add things to `deprecated.json` that have an unambiguous replacement (but I haven’t looked at the code in a while and could be mistaken).

**Comment by sun-geo** [comment]
> _"...unambiguous replacement ..."_

Your are right, the mapper has to decide to choose a new value and for this case (`station`) there are 3 options (`generator`, `substation` or `plant`)

**Comment by sun-geo** [comment]
By the way, a bit of topic, i made a quick look into this overview 
https://wiki.openstreetmap.org/wiki/Deprecated_features - because i wanted to understand if the case of "_deprecated and having more options for the new value"_ is more often existing. I found this seems happened also for deprecation of `landuse=farm` (wiki https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfarm). The wiki gives a recommendation for 2 option of using a new value (`farmyard` or `farmland`).
The current iD-validation process for `landuse=farm` asks to update the value only to `farmland`, so the other option (change to `farmyard`) seems missing. 
Example object: https://www.openstreetmap.org/edit?way=764144252#map=18/40.22274/15.21964

Is this val.-rule setup for `landuse=farm` in this way made by intention?

**Comment by bhousel** [comment]
> Is this val.-rule setup for `landuse=farm` in this way made by intention?

I don't know. It was introduced in b21dd1d

If you want to see when code was changed, you can open the file on GitHub and use the "Blame" view to look at specific lines of the file, see what commits changed the lines, and what issues were referenced.

**Comment by sun-geo** [comment]
> _"..."Blame" view..."_

Thanks a lot, :-)
I never used the blame-view.
I will try next time, to find information by myself.

**Comment by quincylvania** [comment]
> I think we can only add things to deprecated.json that have an unambiguous replacement

☝️ This is true. iD can't handle multiple upgrade paths and I think that's okay—the validator is primarily for checking new edits, not complex re-tagging. I'd suggest a MapRoulette challenge for manually reviewing and upgrading `power=station` tags. There are currently just around 2300 instances.

> The current iD-validation process for landuse=farm asks to update the value only to farmland, so the other option (change to farmyard) seems missing.

Looks like I added this early on when building the validator. At the time I must not have realized that there were two possible options or decided to proceed anyway for some reason. I can remove it now.
