### ISSUE TITLE
When a boundary relation only has 2 ways, there'll be some rendering errors.

### ISSUE THREAD

**Issue by Daredemodaisuki** [openstreetmap/iD#7525]

**Comment by Daredemodaisuki** [comment]
like this
![image](https://user-images.githubusercontent.com/64051837/79815563-9925d700-83b3-11ea-9b9c-f38a747f3c41.png)

**Comment by quincylvania** [comment]
Hi and welcome, @Daredemodaisuki. The screenshot you shared is related to a different project, the [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/) rendered tiles. You'll need to try asking over there. Good luck!
