### ISSUE TITLE
A concrete chain-link fence, and other impossible combinations

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7526]
Perhaps when the user selects "chain-link",
![18643-0](https://user-images.githubusercontent.com/1230959/79828692-d1d5a880-83d3-11ea-939b-f2ce68372e5f.jpg)
"concrete" and "stone" should be moved off, or at least later, in the Material selection list.
Same with other impossible combinations in other presets.
Perhaps mark this issue as a long term goal.

**Comment by bhousel** [comment]
> "concrete" and "stone" should be moved off, or at least later, in the Material selection list.
> Same with other impossible combinations in other presets.
> Perhaps mark this issue as a long term goal.

No, this is OSM and people can generally enter whatever they want.  We can't curate lists of e.g. what materials go with what kinds of fencing.  In a schemaless system, you have to just be ok with seeing some bad or weird data.
