### ISSUE TITLE
我创建了一个中国iD开发者交流群，欢迎加入。

### ISSUE THREAD

**Issue by clearJSer** [openstreetmap/iD#7527]
群名称：iD Editor 开发者交流群
QQ 群：165444936
欢迎中国的开发者加入一起交流关于地图编辑器的代码，如果你感兴趣的话。
谢谢。

**Comment by bhousel** [comment]
translation: 

Group name: iD Editor Developer Exchange Group
QQ Group: 165444936
Developers in China are welcome to join and exchange code about the map editor if you are interested.
Thank you.

**Comment by quincylvania** [comment]
@clearJSer Thanks for the info.
