### ISSUE TITLE
Using a shortcut with right-click menu prevents menu from closing

### ISSUE THREAD

**Issue by jgscherber** [openstreetmap/iD#7528]
After selecting an object (way, node, or area) and right-clicking, if a keyboard shortcut that's available on the right-click menu is used, the right-click menu stays open after clicking away

e.g. select an area and right-click it. While the context menu is still open, press `O` on the keyboard to circularize. Observe the area has been circularized. Click away. The context menu remains

![image](https://user-images.githubusercontent.com/6207661/79911161-862bfa80-83e5-11ea-87b1-f49985657551.png)

**Comment by quincylvania** [comment]
Hi and welcome, @jgscherber. Thanks for reporting. This looks like a known bug we've fixed on our development branch for a future release of iD. See #7143.
