### ISSUE TITLE
iD 2.17.3?

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7530]
It's been already over 3 months since the last update of iD.
Are you planning to release a new version soon? Because we've been waiting for a long long time for a layer to add to editor-layer-index. It was added after a few months and it was added on March 3.
Currently, I can't map my city, because the last available aerial photos are from 2015. This new added layer is from 2018.

If you're not planning to release a new version, could you at least update layers and translations?

Or, you can completely ignore my request if you help me with addding a custom background.
Unfortunately the link I type in "Custom" doesn't work
http://gis1.um.wroc.pl/arcgis/services/ogc/OGC_ortofoto_2018/MapServer/WmsServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&WIDTH={x}&HEIGHT={y}

**Comment by pawelcegiela** [comment]
I agree with @maro-21 that the current situation can discourage some people from mapping. Since my neighbourhood has been developing rapidly for the last several years, this "freshest" good quality layer from 2015 is not an alternative for me anymore.

**Comment by quincylvania** [comment]
@maro-21 Yes, we'll be releasing a 2.17.3 patch very soon including the latest editor layers. Issues included in this patch can be browsed [here](https://github.com/openstreetmap/iD/milestone/17?closed=1).

**Comment by maro-21** [comment]
Ok, thanks.

And how to make this custom background work?
http://gis1.um.wroc.pl/arcgis/services/ogc/OGC_ortofoto_2018/MapServer/WmsServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&WIDTH={x}&HEIGHT={y}

**Comment by quincylvania** [comment]
> And how to make this custom background work?

@maro-21 I don't think you can right now. See #4977 and #7510 about custom WMS imagery.
