### ISSUE TITLE
Add a preset for man_made=reservoir_covered 

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7534]
wiki: https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dreservoir_covered
It seems well distributed nowadays:
taginfo map: https://taginfo.openstreetmap.org/tags/man_made=reservoir_covered#map
history chart (steady growth): https://taghistory.raifer.tech/#***/man_made/reservoir_covered

**Comment by quincylvania** [comment]
I wish there weren't all these different tags for water tanks but so be it.

**Comment by sun-geo** [comment]
That's right, for me it was also not so easy to find the right one ("Covered Reservoir") via the wiki-pages. Sometimes i try to improve the wiki by adding interlinks to the "See also" sections. Hope that helps a bit the user who is searching for it after me.

Thanks!

**Comment by quincylvania** [comment]
>  Sometimes i try to improve the wiki by adding interlinks to the "See also" sections.

This definitely helps me navigate the wiki 👍
