### ISSUE TITLE
tag personalizada de Farmácia no Editor ID. 

### ISSUE THREAD

**Issue by raphaelpe** [openstreetmap/iD#7542]
Gostaria de saber como faço para criar uma tag pernsonalizada para o Editor ID com pagina na wikipedia,

queria incluir uma nova rede de Farmacias que nao está no OpenstreetMap mais não sei como fazer, sempre vejo tag personalizadas de outras farmácias e queria incluir essa tag personalizada dessa rede de farmácia, 

alguem que possa me ajudar..

atenciosamente,
============================================================
I would like to know how do I create a custom tag for Editor ID with page on wikipedia,

I wanted to include a new pharmacy chain that is not on OpenstreetMap but I don't know how to do it, I always see personalized tags from other pharmacies and I wanted to include this personalized tag from this pharmacy chain,

someone who can help me ..

Sincerely,

Raphael de Assis 
Membro da FOSM

**Comment by UKChris-osm** [comment]
I think you mean you wish to add a new [Pharmacy chain](https://nsi.guide/index.html?k=amenity&v=pharmacy) to what is known as the [name suggestion index](https://github.com/osmlab/name-suggestion-index/)??

**Comment by raphaelpe** [comment]
isso, um rede de novas farmácias! 
=====================================

this, a chain of new pharmacies!


Raphael de Assis.
Membro da FOSM.

**Comment by raphaelpe** [comment]
how to create this tag for this pharmacy network

**Comment by quincylvania** [comment]
You can open an issue here and someone will assist you: https://github.com/osmlab/name-suggestion-index/issues
