### ISSUE TITLE
Hide name field for some buildings which typically don't have names

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7543]
Residential buildings usually don't have names... So this field is not filled in very often.
Could we move Name field to moreFields?

Why?
- It will prevent adding values like "Garage" for building=garage or "House" for building=house. Some newcomers think they should fill in every field. Example: https://www.openstreetmap.org/way/791172314
- There will be more space in the screen because now when I want to add other tags, like address, I have to scroll down.
- We don't remove the field, just move it below to the list of less used fields.

building=residential
<s>building=apartments</s>
building=house
building=detached
building=hut
building=terrace
building=semidetached_house
building=cabin

building=garage
building=garages
building=shed
building=roof
building=greenhouse
building=barn
building=farm_auxiliary
building=carport
building=stable
and maybe other.

**Comment by kymckay** [comment]
I think is sensible

**Comment by andrewharvey** [comment]
Maybe this is regional, from my experience in Australia many apartment buildings will have a name.

**Comment by andrewharvey** [comment]
Instead perhaps build into the validator a warning when the name is "Garage" or "House" etc.

**Comment by jjiglesiasg** [comment]
In mostly of South America, all residential and commercial buildings have a name , apart from the cadaster number given by the municipality

**Comment by maro-21** [comment]
Yes, there are 1851 `building=apartments` with `name` in Australia.
So we can exclude some of them from the list in my first message.

> In mostly of South America, all residential and commercial buildings have a name , apart from the cadaster number given by the municipality

Which countries?

**Comment by quincylvania** [comment]
Yeah, I don't think iD needs to go down the path of worrying about what type of building might be likely to have a name in what country. It's okay to show fields that aren't always needed. If we do openstreetmap/id-tagging-schema#2051 then we might not even have all these building presets by default. Closing for now as low impact.

**Comment by maro-21** [comment]
>  I don't think iD needs to go down the path of worrying about what type of building might be likely to have a name in what country

The previous message was only about apartment buildings which I deleted from my first post.
There is still a long list with buildings which typically don't have a name and my idea was to prevent typing a common name to the field like "garage" for building=garage.

iD hides names on some features like `amenity=bicycle_rental` or `amenity=parking` - it's becasue they usually don't have names or name is not one of the most used tag with such features. Why can't we do the same on buildings?
The set of visible fields in iD are usually the most important tags connected with the feature. A suggestion what should be filled in.

I changed the title of the issue.

**Comment by andrewharvey** [comment]
I think this is getting into tricky territory, hiding the field just because many don't have a name is at the direct expense of those that do and could mean a new mapper doesn't add a name where they could have. My counter point is many parking lots are named and so the name field should be shown for these, same for bicycle rental many of these are shops that rent bikes with a name. So where these features could have a name, and it's not a very rare case, then we should make it easier for people to add the name, not harder.

**Comment by jjiglesiasg** [comment]
I dissagre. Name field should be ALWAYS shown for buildings (even for everything in OSM), placing generic names however not encouraged, is better than hide the field and preclude that the data is Not added, existing it.

**Comment by jjiglesiasg** [comment]
In mostly of South America, all residential and commercial buildings have a name , apart from the cadaster number given by the municipality
 
Which countries?

Following the tradition of Spanish and Portuguese heritage almost in all countries on Latam (Spanish or Portuguese speaking ones) the buildings have a distint name, I have lived in 6 of them (Venezuela, Colombia, Brazil, Argentina, Costa Rica and Bolivia), if you take a look of Street pictures in major and not major cyties, you will realize that buildings are mostly named.

**Comment by jjiglesiasg** [comment]
> Instead perhaps build into the validator a warning when the name is "Garage" or "House" etc.

This could be tricky as well we have a massive edition where "casa", "vivienda", "habitacion", and others synonymous in spanish were used, all meaning more or less "house" so a warning should be for all languages, wich I guess is impossible

**Comment by andrewharvey** [comment]
> This could be tricky as well we have a massive edition where "casa", "vivienda", "habitacion", and others synonymous in spanish were used, all meaning more or less "house" so a warning should be for all languages, wich I guess is impossible

Yes my suggestion wasn't limited to English, it would also include variants in other languages too.

**Comment by jjiglesiasg** [comment]
As a note some countries in Latam also have the tradition to place names to actual uni-familiar houses, Venezuela for example; the cadaster number or number in the street is not shown... mostly other countries here do not have name for houses but yes for buildings at least residential, apartments, terrace, garage, commercial, roof, etc

**Comment by 1ec5** [comment]
Doesn’t iD already warn about generic names in the Name field? Maybe it isn’t working in some languages or needs to check for some additional generic words related to buildings?

**Comment by maro-21** [comment]
> the buildings have a distint name

Isn't it `addr:housename`?

> but yes for buildings at least residential, apartments, terrace, garage, commercial, roof, etc

Can you give examples of garages and roofs with names?


> Doesn’t iD already warn about generic names in the Name field? Maybe it isn’t working in some languages or needs to check for some additional generic words related to buildings?

Yes, it does for some features, but the list is short. Unfortunately it mixes languages. For example "mercado" was added as a generic name for amenity=marketplace for Spanish, but in my city there is a Spanish restaurant named "Mercado" and iD warns about it. The same for "Casa" - it can be a generic name in Spanish, but this is a short word and in other languages it may be a proper name.
