### ISSUE TITLE
Unnececery autocomplete in `preset-input-entrance` input (new MS Edge)

### ISSUE THREAD

**Issue by skfd** [openstreetmap/iD#7544]
I F12ed `autocomplete="off"` instead of `autocomplete="new-password"` as an `<input>` attribute and it stopped auto-completing. Could this help?

Could we do browser-dependant tags if this is only works for some brower?

![image](https://user-images.githubusercontent.com/159640/80048142-005c9c00-8518-11ea-98c2-26eccedd67b8.png)

**Comment by quincylvania** [comment]
This should be fixed on the `develop` branch for a future release. We're now using different element IDs for fields each time they're rendered so the browser can't store an autocomplete history. See #6444.
