### ISSUE TITLE
"uses google as a data source" warning shouldn't count googledrive.com URLs?

### ISSUE THREAD

**Issue by dbaron** [openstreetmap/iD#7545]
Showing all of the warnings in Palo Alto, California, has the problem that it shows a very large number of "building shows google as a data source" warnings:

![Screenshot from 2020-04-27 18-23-17](https://user-images.githubusercontent.com/248721/80436648-76645880-88b4-11ea-8295-b7eae66caede.png)

This is because of a building import that referenced the source of the datafile, which was hosted on Google Drive; see [this example building](https://www.openstreetmap.org/way/230392400).

This makes it generally more difficult to use (and fix things based on) the warnings in this area.

Would it be possible to structure the "uses google as a data source" warning in a way that it doesn't how up if the source is a URL on https://googledrive.com/ ?

**Comment by dbaron** [comment]
Also, this request is quite similar to #6556 and could hopefully be fixed in a similar way.

**Comment by quincylvania** [comment]
@dbaron Sounds reasonable, thanks for reporting.
