### ISSUE TITLE
pls display id of node or way on select when hilighted.

### ISSUE THREAD

**Issue by prasadrajuv** [openstreetmap/iD#7546]
id editor is not user friendly some time because zoom level restriction to edit. building alignments is not possible because of poor satellite map image in india. i want use api to update building using osm id number but it is not displaying in editor. pls provide id info below properties window on select.
our streets are congested and houses area approx 60 to 100 yards. map showing one or two houses in street. i have all building coordinates properly aligned. if i have osm id of buildings i will update those and remaining will insert as new. 
i want osm id info when node or way selected in Id editor

**Comment by JamesKingdom** [comment]
I think what you're wanting is already possible, if the node/way has already been saved to OSM, you can click "View on openstreetmap.org" in the bottom left when you select the node, showing you the way or node id.
<img width ="300" src="https://i.imgur.com/rQr77Y9.png">
You could also find the node/way id by opening the history panel with `CTRL` + `Shift` + `H`, which will show you the id.
![](https://i.imgur.com/v8HAoRc.png)

**Comment by quincylvania** [comment]
Hi and welcome, @prasadrajuv.

Check out @JamesKingdom's helpful comment for ways to view entity IDs already. We do need to make the History panel more discoverable in the future, see #6397.

Happy mapping!
