### ISSUE TITLE
add newly allowed real estate cadastre wms-layer for Brandenburg, Germany

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [openstreetmap/iD#7547]
As we did for the German distrcit Baden-Württemberg already, would it now be possible to add the new allowed wms-layer for the real estate cadastre of the district Brandenburg, Germany?

The release is documented here: https://wiki.openstreetmap.org/wiki/Brandenburg/Geoportal but unfortunately, only in german.

The address for the layer would be the following: wms:https://isk.geobasis-bb.de/ows/alkis_wms?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=adv_alkis_gebaeude&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}

**Comment by quincylvania** [comment]
I believe you're looking for https://github.com/osmlab/editor-layer-index/issues.

**Comment by Elefant-aus-Wuppertal** [comment]
Oh yes it seems so, thank you for the link
