### ISSUE TITLE
Rename Metal Construction preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7549]
Isn't the name for craft=metal_construction "Metal Construction" ambiguous in English?
It suggests that this is a kind of construction, but this supposed to be an office of a company.
Maybe we should change it to "Metal Construction (company)" or similar?

**Comment by 1ec5** [comment]
“Metalworking” would be more intuitive from my (American English) perspective.

**Comment by animesh-007** [comment]
@1ec5 I have made suggested changes.

**Comment by maro-21** [comment]
Suggested name was "Metalworking", not "Metal Working".
https://en.wikipedia.org/wiki/Metalworking

The tag remains the same, `craft=metal_construction`, but you changed it to `craft=metal_working`.

**Comment by animesh-007** [comment]
Thanks for reviewing.
I have made the suggested changes.

**Comment by quincylvania** [comment]
Done in #7568.
