### ISSUE TITLE
Rendering bug: magic select looking control appears

### ISSUE THREAD

**Issue by skfd** [openstreetmap/iD#7550]
![image](https://user-images.githubusercontent.com/159640/80551420-16f96c00-89cc-11ea-84a7-928304bad2e4.png)

**Comment by kymckay** [comment]
What are the circumstances under which this occurred?

**Comment by skfd** [comment]
I had selected polygon/way and shift-selected point and pressed Detach command. Was in process of detaching landuse from way.

Sorry for no steps, will try to repro

**Comment by quincylvania** [comment]
The selection code has changed a lot since April, so I'm thinking this was a bug that's been fixed.

@skfd Please do let us know if you see this happen again.
