### ISSUE TITLE
Stop inserting Features/Tags manually every release and base it off of TagInfo/Wiki Presence

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/iD#7552]
**Issue**
When recently mapping, I came across the Curb and Basin preset and found that there were _many_ more preset values for each of the tags than even used or documented in the Wiki. There are only 3 Basin values documented and yet there are about 15 different presets, many of them very similar. 

**Reasoning**
What I don't understand is why Quincy has to go in every release and manually accept and add new Features/Tags. It wastes so much time during the development process and only makes their respective files in the /data/ folder larger and more disorganized (it's literally a long list).

**Solution**
Instead, why don't the presets correspond live with TagInfo, checking to see if a tag has a documented Wiki page, and is say, used over 100 times. Then it will automatically insert that preset into some database (or it could just request TagInfo using an API every time some user opens a preset dialogue), and retrieve and display them. This would mean that new Tags both commonly used _and_ that have a wiki page, and that aren't depreciated - would automatically be updated to iD and Quincy wouldn't have to do anything!

**Comment by quincylvania** [comment]
Hello and welcome, @lectrician1. Thanks for your concern about my time and workload!

A lot of folks don't realize how much finessing it takes to turn OSM's thousands of tags into presets and fields that a casual mapper can readily understand. We have to separate type tags from attribute tags and determine which attributes belong on which types. We have to give each preset and field a short, clear, unique label and then translate that into dozens of languages. We have to add search terms for anything a mapper might type to find a preset or field. We have to find or draw an icon that adequately represents the feature at small sizes and differentiates it from similar features. We have to avoid problematic or old tags with high usage while supporting niche or newly approved tags with low usage.

In sum, in my view it's technically impossible to automatically generate iD's presets as proposed, or at least generate presets of the same quality. Though it's true our preset update workflow could be improved and that some of this metadata would be better if retrieved upstream of iD. For now, feel free to open issues about any presets you find confusing!
