### ISSUE TITLE
Moving end of self-looped way causes loop to break

### ISSUE THREAD

**Issue by jgscherber** [openstreetmap/iD#7553]
Moving a self-looped ways endpoint to another node causes the self-loop break (see vid)

![breaking_loop](https://user-images.githubusercontent.com/6207661/80604260-2215c180-89f7-11ea-96d6-d61b3b85ab12.gif)

This can be reproduced on w566763593. This is reproducible on the `develop` branch (https://ideditor.netlify.app/)

**Comment by quincylvania** [comment]
@jgscherber Thanks for reporting! This was a weird bug that'd probably been around for quite awhile.
