### ISSUE TITLE
unable to find "terrain de sport" with french locale

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/iD#7556]
after drawing a polygon, I search "terrain de sport". not found.
adding leisure=pitch by hand show the object as a "terrain de sport"

**Comment by quincylvania** [comment]
Hmm I was able to find it without issue… Were you expecting it to be the first result?

<img width="393" alt="Screen Shot 2020-04-30 at 9 17 09 AM" src="https://user-images.githubusercontent.com/2046746/80734053-6ff7fb80-8ac3-11ea-8b18-57f711e01fdc.png">

**Comment by Marc-marc-marc** [comment]
if I add a new polygon and search for "terrain de ", it works.
I delete the tag, clic on "choisir un type d'élément" and search again, it doesn't return "terrain de sport"
![Capture d’écran de 2020-05-07 14-01-05](https://user-images.githubusercontent.com/31963329/81292455-ec627f80-906b-11ea-8175-244dc4cb1f17.png)
![Capture d’écran de 2020-05-07 14-01-13](https://user-images.githubusercontent.com/31963329/81292461-ed93ac80-906b-11ea-8bfa-f059dfff1eac.png)

**Comment by quincylvania** [comment]
Oh I see. So OpenStreetMap doesn't have an "area" geometry type. iD and other apps know that tags like `leisure=pitch` or `building=yes` imply an area geometry. By removing the tags you're switching to line geometry and so searching for an area type doesn't work.

Issue #1828 is about making it easier to switch between closed lines and areas. For now, you can add the tag `area=yes` to make an untagged way an area.
