### ISSUE TITLE
WMS 1.3.0 EPSG:4326 reverse axis

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#7557]
This is an old issue from Leaflet and other WMS clients that is affecting iD and GoMap!! [link](https://github.com/bryceco/GoMap/commit/b15b14c840c7a43e6dd4898dbe557ed7d9031ff6) - thanks @bryceco for finding this!

The Leaflet bug:  https://github.com/Leaflet/Leaflet/pull/1897
This article details the problem http://viswaug.wordpress.com/2009/03/15/reversed-co-ordinate-axis-order-for-epsg4326-vs-crs84-when-requesting-wms-130-images/ 

The x/y coordinates needs to be switched only for EPSG:4326 and when talking to a WMS 1.3 server.

Relevant code is around here, but need to add a test for WMS 1.3. https://github.com/openstreetmap/iD/blob/af0477d3886921b68a187b478e9607c731e27501/modules/renderer/background_source.js#L105-L117

**Comment by 1ec5** [comment]
Fixed in 964c2e6b129d69af8ce1d2b6cb3f16ce56cc042b.

**Comment by 1ec5** [comment]
Oh never mind, that was just a workaround for particular layers.

**Comment by bryceco** [comment]
The fix for this is pretty easy, if you look at https://github.com/bryceco/GoMap/blob/60f2846d921477525d1416b3400c032a9751745e/src/Shared/MercatorTileLayer.m#L313
