### ISSUE TITLE
Mapping line brings up scroll bars

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#7560]
Not really sure why, but in Chrome when I map a line and move it around the screen it activates the scroll bars on the bottom and side of the screen. Even though I'm not going out of the current window with it or anything. Also the scroll bars will self adjust depending on how I move the line around. 

![iD Editor Scroll Bar](https://user-images.githubusercontent.com/30259065/80851955-960fbf80-8bd9-11ea-89e4-cf7a10a05f84.png)

**Comment by boothym** [comment]
Same here on Firefox/Win10

**Comment by quincylvania** [comment]
@Adamant36 @boothym Thanks for reporting. This was a weird bug where iD had been adding some helper text that was supposed to follow the cursor the first time you mapped, but the element was outside iD's container and positioned beyond the bounds of the app. I submitted a CSS hotfix to the OSM website and also fixed it on iD's side by removing the text element altogether.
