### ISSUE TITLE
Is the direction service down in the web page?

### ISSUE THREAD

**Issue by AlphaWong** [openstreetmap/iD#7561]
Hi,

If I try to build a route between two points on the web page. The webpage seems not to work.
https://www.openstreetmap.org/directions?from=22.2865%2C113.9421&to=22.28231%2C113.93928

When I open the console, I find it throws some error. Are they related?
![image](https://user-images.githubusercontent.com/5622516/80857929-6370d000-8c88-11ea-9bb9-229059da07a5.png)

Best,
Alpha

**Comment by 1ec5** [comment]
The directions service is a different part of the [OpenStreetMap website](https://github.com/openstreetmap/openstreetmap-website/), not part of iD. The URL you posted above seems to work for me. It might’ve been temporary downtime on the part of the [FOSSGIS routing service](https://routing.openstreetmap.de/about.html) that powers the default “Car (OSRM)” option. If the request continues to fail for you, please see the [FOSSGIS routing service](https://routing.openstreetmap.de/about.html) page for contact options.
