### ISSUE TITLE
Water land-use being rendered outside boundary instead of inside

### ISSUE THREAD

**Issue by jgscherber** [openstreetmap/iD#7567]
See [here](https://www.openstreetmap.org/way/391695097#map=17/-35.99398/146.39982) in OSM and compare to how it's rendered with iD (below). The water should be inside the river.

![image](https://user-images.githubusercontent.com/6207661/81013627-170cc800-8e21-11ea-9a9e-f81839115976.png)

**Comment by quincylvania** [comment]
Looks like this is #1201.
