### ISSUE TITLE
mouse symbol on mapillary link position

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7570]
**Current behavior:**
When the mouse is reaching the position of the mapillary link the mouse symbol shows a picture like this: ![map-icon](https://upload.wikimedia.org/wikipedia/commons/1/16/Commons-emblem-hand.svg)

Example test object:
https://www.openstreetmap.org/edit?node=2458001035#map=20/48.84865/2.34839
(Tested with firefox browser)

![map-icon](https://user-images.githubusercontent.com/47290585/81122159-9e952c80-8f30-11ea-8578-4d0e9048dede.png)

**Expected behavior:**
When the mouse is reaching the position of the mapillary link the symbol could switch to grey hand symbol, similar which is shown when the mouse is over the "remove"- or "info"-button next to it.

**Comment by quincylvania** [comment]
Looks like this is present in v2.17.3 but has already been fixed in the `develop` branch.

You can test here: https://ideditor.netlify.app/#background=Maxar-Premium&disable_features=boundaries&id=n2458001035&map=20.00/48.84865/2.34839
