### ISSUE TITLE
No trash icon on the bar for multilingual names

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7572]
If a feature has a name in other language [name:en], but no [name], there is no icon of a trash bin to delete it, but anyway I can click anywhere on the bar and the name will disappear.

When I add a name, the icons reappear.

![name_en](https://user-images.githubusercontent.com/57260466/81209293-a4424f00-8fd0-11ea-8df9-0fd4c0a362ef.jpg)

**Comment by quincylvania** [comment]
This happens since the trash button only appears when a tag is present, but I agree it'd be nice to have a way to close that UI anyway.
