### ISSUE TITLE
Background info decimal places

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7573]
Not a massive issue, but it would be good to trim the excess decimal places off the resolution and accuracy numbers in the background panel.
This is the ESRI (clarity) imagery, but on the normal ESRI imagery it just displays 0.31m
![Screenshot_2020-05-03 OpenStreetMap](https://user-images.githubusercontent.com/16965772/81300746-f8e8d700-906f-11ea-9d7c-ab8cecaf9351.png)

**Comment by quincylvania** [comment]
@boothym I think I fixed this but could you link a test location?

**Comment by boothym** [comment]
Weird - I've looked at many of the locations I normally edit in and where I have seen this before, but now the Esri (clarity) imagery only shows the zoom information. Very strange! 

Thanks for making the changes, will let you know if the info reappears...
