### ISSUE TITLE
Create preset for orthodontics

### ISSUE THREAD

**Issue by mfbehrens** [openstreetmap/iD#7575]
As far as I know there is no preset for orthodontics. The tag should be **healthcare=dentist** and **healthcare:speciality=orthodontics**

**Comment by maro-21** [comment]
I don't think we should have presets for every medical speciality.
And orthodontics is just a subspeciality of stomatology, so what about other specialities: implantology, endodontics etc?

**Comment by quincylvania** [comment]
> I don't think we should have presets for every medical speciality.

I agree, but it's useful to have them for relatively common ones with technical tags like this.

**Comment by tas50** [comment]
Orthodontics practices are incredibly common in the US and often mistagged as general dentistry in OSM. This is going to really help fix that up so we can get folks to use the correct tags. There's obviously a lot of other kinds of specialized dentistry practices, but at least in the US, this is the most common by a few orders of magnitude.
