### ISSUE TITLE
Edit Parking Lot preset: add parking=rooftop

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7578]
- [x] add `parking=rooftop` to the menu in Parking Lot preset
- [x] reorder the list
- [x] deprecate `parking=park_and_ride` -> `park_ride=yes`

Current order:
"surface": "Surface",
"multi-storey": "Multilevel",
"underground": "Underground",
"sheds": "Sheds",
"carports": "Carports",
"garage_boxes": "Garage Boxes",
"lane": "Roadside Lane"
https://github.com/openstreetmap/iD/blob/72a99673a0328ba4f44c58dd110797cc733f7007/data/presets/fields/parking.json#L6-L13

Reordered after taking current usage into account:
"surface": "Surface",
"underground": "Underground",
"multi-storey": "Multilevel",
"lane": "Roadside Lane"
"carports": "Carports",
"garage_boxes": "Garage Boxes",
--> add rooftop here
"sheds": "Sheds",

https://taginfo.openstreetmap.org/keys/parking#values

**Comment by quincylvania** [comment]
I kind of wish people would use [`location`](https://wiki.openstreetmap.org/wiki/Key:location) for some of these but so it goes.
