### ISSUE TITLE
Edit Yield Sign preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7581]
I think `direction=both` should be removed from the menu because it's not possible. It's not like with traffic lights that we can put a node on the crossing for all directions.

**Comment by animesh-007** [comment]
I am not able to find the exact file which needs to be changed.
Can you tell me where to look at?

**Comment by quincylvania** [comment]
@maro-21 Yeah, I guess it doesn't make sense for no direction to have the right of way 😂

@animesh-007 We had to add another field to change the options. Check out the commit to see how to do this in the future.

**Comment by maro-21** [comment]
We should change `highway=stop` as well, I think...

**Comment by quincylvania** [comment]
> We should change highway=stop as well, I think...

We can't since `direction=both` is used for [all-way stops](https://en.wikipedia.org/wiki/All-way_stop), which are very common in the US and some other places.

**Comment by maro-21** [comment]
I see, ok.
