### ISSUE TITLE
Change category for Recently Demolished Building

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7582]
I think `demolished:building=yes` preset should be in the category Future/Past or Buildings, not Landuse.

I think Buildings will be better because it will prevent from adding a building again from aerial imagery.

**Comment by quincylvania** [comment]
I agree it makes sense for features with this type of lifecycle-prefixed tag and no primary feature type to be in the future/past category. We just have to be careful about checking this performantly.

**Comment by maro-21** [comment]
Currently the preset for `landuse=construction` is in both categories: Landuse and Future/Past, so I think Recently Demolished Building should be in both too: Buildings and Future/Past.

**Comment by maro-21** [comment]
waiting...
