### ISSUE TITLE
add insurance=health for some "Krankenkasse" presets in Germany

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [openstreetmap/iD#7583]
In Germany, there is a preset for "Techniker Krankenkasse" which is a common health-insurance brand here. The tag insurance=health (https://wiki.openstreetmap.org/wiki/Tag:insurance%3Dhealth) is used not so often but specifies those insurance offices which are specialized (only) on health insurances. On the tagging-mailing list, people said it would be a good purpose to use an under-tag for this. So I think this tag should be added to the preset.

**Comment by Elefant-aus-Wuppertal** [comment]
The same would fit for the "DAK Gesundheit" and for the "AOK" presets, as it seems to me.

**Comment by quincylvania** [comment]
@Lukas458 Thanks, the brand presets are managed in the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) project so you'll have to bring it up there.

**Comment by Elefant-aus-Wuppertal** [comment]
Okay, thank you. I will do this.
