### ISSUE TITLE
Edit Storage Tank preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7587]
I don't know if `man_made=storage_tank` needs `building=*` tag, but iD currently adds `building=yes` to `man_made=storage_tank`. Could it add [`building=storage_tank`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dstorage_tank) instead?

**Comment by quincylvania** [comment]
> I don't know if man_made=storage_tank needs building=* tag, but iD currently adds building=yes to man_made=storage_tank.

Yes, the `building` tag is important here so renderers can automatically treat these as 3D extruded objects instead of landuse.

> Could it add building=storage_tank instead?

iD doesn't really have a mechanism for setting the default `building` value for a preset like this, and in any case the tag seems a bit redundant…
