### ISSUE TITLE
New preset: shop=collector

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7588]
Add [shop=collector](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcollector) preset
with the field `collector=*` that works like `cuisine` for restaurants.

**Comment by quincylvania** [comment]
Hmm shouldn't the `shop` tag indicate what the store sells? Like `shop=comics` or `shop=stamps`? I'm not sure "collector's items" is an identifying or unifying label for a store. People could collect anything.

**Comment by maro-21** [comment]
It sells collector's items :)
Such stores are not as popular as grocery stores. There are very few of them. So it's practical to have one tag for many types of collector's shops than for each store separately. I think the tag was created for stamps and coins, and then others were added.

There are mores shop=* tags that don't indicate what the store sells, like shop=variety_store, shop=general.

Wiki:  "[A general store. Selling various things](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dgeneral)"

Shop=electronics doesn't indicate what the store sells too. It may be all kind of electronic stuff or it may sell only car navigation.

**Comment by 1ec5** [comment]
In the U.S., these stores are often signposted as “We Buy …”, “We Collect …”, or “Cash for …”, though there may be a different, more obscure name in each case.

`shop=collector` is an attempt to collect (hah!) multiple related kinds of shops into one tag. It might be more intuitive to create a preset for each of the common collector’s items mentioned in the [`shop=collector` documentation](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcollector). For example, “Coin Dealer” is the usual American term for `collector=coins`, while `collector=stamps` might be called a “Stamp Collector Store”. If an umbrella `shop=collector` preset is needed, it could be called “Collector’s Item Store” or “Collectible Store”.

**Comment by maro-21** [comment]
Collector's shops in my country sell usually stamps and coins together.
Having separate tags for these stores (shop=stamps, shop=coins) would cause the problem how to tag them.

As you can see on Taginfo
https://taginfo.openstreetmap.org/keys/collector#values
`collector=stamps;coins` is very popular

**Comment by 1ec5** [comment]
True, that would be a reason to add a general preset for “Collectible Store”, but we could still have more specific presets for shops that specialize. (iD does the same thing with restaurants and the `cuisine` tag.)
