### ISSUE TITLE
snapping incompatible nodes

### ISSUE THREAD

**Issue by hungerburg** [openstreetmap/iD#7591]
ID is the editor of choice for newbies; can you make it so, that drawing a highway does not snap to nodes of a power line or ways of that kind, or other kind of furniture, where it does not make any sense?

**Comment by maro-21** [comment]
It is already in iD.
"<kbd>Alt</kbd> Hold to disable point snapping"

**Comment by hungerburg** [comment]
Well, I actually meant, for newbies…

**Comment by quincylvania** [comment]
This is #4173. It's a nontrivial problem since iD would have to maintain a list of what features can and cannot connect to what other features, plus compute validity in real time.
