### ISSUE TITLE
Please add helipad/port presets for points

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7594]
Please add
https://wiki.openstreetmap.org/wiki/Tag:aeroway:helipad
<s>https://wiki.openstreetmap.org/wiki/Tag:aeroway:heliport</s>
presets for single points, not just areas. Their wiki pages say points are OK too.

**Comment by quincylvania** [comment]
iD already supports helipads as points and it doesn't have a heliport preset at all.
