### ISSUE TITLE
Node types/rendering legend and handling (tutorial)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7597]
When working with iD, you can notice different kind of nodes rendering, e.g. small white dot, small grey dot and big grey dot. Did I miss some others?
Example object which shows currently (v#2) all types of rendering:
https://www.openstreetmap.org/edit?relation=9933393

(1) small white dot: https://www.openstreetmap.org/edit?node=6781452953 
(2) small grey dot: https://www.openstreetmap.org/edit?node=2142052526
(3) big grey dot: https://www.openstreetmap.org/edit?node=2142052705

Is there a legend or beginners tutorial (walk-through) available to explain the differences?
Regarding case (2) and (3), both seems to be shared nodes (grey), but (2) is small and (3) is bigger, why?
Is there a tutorial how to manage handling of (3) nodes, e.g. for beginners and/or more advanced users? (In regard of the blocked disconnect function due to the relation membership.)

![node types](https://user-images.githubusercontent.com/47290585/81813121-62ad2900-9527-11ea-8baf-0aba157b904d.png)

**Comment by manfredbrandl** [comment]
In the walkthrough people get practise in connecting streets and see grey circles in connections and big circles at endpoints but there is no explanation.
![image](https://user-images.githubusercontent.com/5360273/81909042-56c67300-95ca-11ea-85e1-176db640e33c.png) In the HelpChapter on Lines under Connecting Lines you find "The connections between roads are drawn with gray circles. The endpoints of a line are drawn with larger white circles if they don't connect to anything." For me that is clear enough, small white dots (circles) are just standard, grey means connected, big means endpoint. Big grey circles were new to me, they seem to occur seldom, in your example a line endpoint is connected to a house.

**Comment by manfredbrandl** [comment]
@sun-geo The big grey circle (dot) is so unusual because the are-relation "March Field" is deprecated. See https://wiki.openstreetmap.org/wiki/Relation:multipolygon "Simple areas are mapped in OSM by creating a closed way". Having a foot and part of a house also there does not harm, if the area really starts by the house and the footpath is really on the March Field outline.

**Comment by quincylvania** [comment]
I agree with @manfredbrandl that the existing tutorial and help documentation are good enough for most users. There are always more details to explain in an app as complex as iD, but there's a limit to the amount of instruction people can tolerate at once. iD doesn't have a legend at all—the symbols are meant to be as self-explanatory as possible.

If we do #6079 then we could potentially make deep-dive tutorials for various aspects of iD like cartography.
