### ISSUE TITLE
Complain about wikipedia links to disambiguation pages

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7602]
To replicate: 

- create an empty node.
- select adding a Wikipedia tag
- add `fr:Micromania`
- description will show "Wikipedia disambiguation page" and https://www.wikidata.org/wiki/Q3312213 has "instance of Wikimedia disambiguation page"

But validator is not complaining and not making clear that it is a certainly wrong link.

Examples from Poland recently added by iD users: https://www.openstreetmap.org/node/6955967403 https://www.openstreetmap.org/node/7419077047 https://www.openstreetmap.org/node/7439953503 

Related:  #4414

**Comment by quincylvania** [comment]
This is an okay idea in theory, but it'd take a lot of development work only to detect a few stray mistags. iD doesn't yet have validations that make server requests so we'd need to do a lot of refactoring. Plus checking every downloaded feature could cause performance issues.

I'd say let's fix #4414 to prevent new mistags and then perhaps someone can create a MapRoulette campaign to fix existing mistags.
