### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7604]
"Center and zoom the map to focus on this feature." isn't on Transifex.

**Comment by quincylvania** [comment]
@maro-21 That strings has been removed the `develop` branch and replaced with this one for the next release:

![Screen Shot 2020-05-17 at 3 35 32 PM](https://user-images.githubusercontent.com/2046746/82158151-124e0800-9854-11ea-80cf-109398726017.png)
