### ISSUE TITLE
Point reverts location when changing type

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7606]
When I move a POI to a new place and then change the type of amenity, the POI returns to the original location.

**Comment by quincylvania** [comment]
@maro-21 Hmm I couldn't reproduce the bug. Are you seeing this on osm.org or on a preview site? Could you be more specific about your setup and what exact steps made this happen? A screencapture is always helpful if that's possible.

**Comment by maro-21** [comment]
This bug only occurs occasionally.

**Comment by maro-21** [comment]
This bug occurs only occasionally.

**Comment by quincylvania** [comment]
Lacking steps to reproduce this or further information, I'm closing this as non-actionable.

**Comment by maro-21** [comment]
I still can see this bug.

What I've done:
- create a point
- add some tags
- move the node
- edit some tags and after it the node goes back to the previous location

**Comment by quincylvania** [comment]
@maro-21 I still can't reproduce this. It might help if you could share what browser/system you see this on, or what location of the map.

**Comment by maro-21** [comment]
I use Firefox but I don't think it depends on the browser;)
More details:
- open any location
- add a point and choose restaurant
- add name, cuisine and opening hours
- move the point to a different location
- add another tag, for example website - when you type any letter, the point goes back to the previous location.

**Comment by quincylvania** [comment]
Ah, I was able to reproduce this when changing the Name field first.

**Comment by maro-21** [comment]
I'm glad you found a solution!:)
