### ISSUE TITLE
all objects i Nuuk area is misplaced, about 25m towards W

### ISSUE THREAD

**Issue by bjarnephys** [openstreetmap/iD#7608]
this fixpoint is placed at the outerwall in the Asiaq building:
utm22: y=7116148.640   =464353.901    
(lat,lon): 64 10 11.527693 N  51 43 59.680975 W (64.16986880361111  , - 51.73324471527778 )

Who knows the 'story' behind the Nuuk objects. I guess the creator
<img width="452" alt="misplacement-in-Nuuk" src="https://user-images.githubusercontent.com/988296/82133515-fd2d9680-97cb-11ea-92fc-4c6e9a7cbc46.png">
 has used utm22 from official source, Asiaq, but used a wrong transformation to (lat,lon)

**Comment by quincylvania** [comment]
Hello and welcome, @bjarnephys.

I'm not sure I understand the issue. This repository is for the iD map editor project, but the screenshot looks like a different application. You can ask more general questions about OpenStreetMap in the [forums](https://forum.openstreetmap.org/).

**Comment by maro-21** [comment]
The buildings countours are at the same place as on Bing imagery.
So if they are in the wrong place, then imagery offset may not be properly set.
How did you measure this difference?

**Comment by bjarnephys** [comment]
I know the position of the reference/fix point; it is placed in the building correctly in the utm22 map I have worked for the official map organization in Greenland, Asiaq, the fixpoint must be correct!
---------------------------------------------------------Bjarne Hansen Mobil:(+299)565535, Suloraq 3-504, 3905 Nuuk, Greenland, DK
Email: bjarnephys@yahoo.dk. 
Kontakt mig per facebook, har kontoen:https://www.facebook.com/bjarne.hansen.102Kontakt mig per Skype: 'bjarnephys' -er på alle dage omkring kl 21:15 dansk tid. 

 

    Den mandag den 25. maj 2020 20.35.43 GMT-2 skrev maro-21 <notifications@github.com>:  
 
 


The buildings countours are at the same place as on Bing imagery.
So if they are in the wrong place, then imagery offset may not be properly set.
How did you measure this difference?

**Comment by bjarnephys** [comment]
I know the position of the reference/fix point; it is placed in the building correctly in the utm22 map. I have worked for the official map organization in Greenland, Asiaq. OpenStreetMap objects must come from an import of objects from Asiaqs map, but something has gone wrong with the projection -I would really like to know, what was done in this process.  

---------------------------------------------------------Bjarne Hansen Mobil:(+299)565535, Suloraq 3-504, 3905 Nuuk, Greenland, DK
Email: bjarnephys@yahoo.dk. 
Kontakt mig per facebook, har kontoen:https://www.facebook.com/bjarne.hansen.102Kontakt mig per Skype: 'bjarnephys' -er på alle dage omkring kl 21:15 dansk tid. 

 

    Den mandag den 25. maj 2020 20.35.43 GMT-2 skrev maro-21 <notifications@github.com>:  
 
 


The buildings countours are at the same place as on Bing imagery.
So if they are in the wrong place, then imagery offset may not be properly set.
How did you measure this difference?
