### ISSUE TITLE
Osmose layer icons turn white after uploading changes

### ISSUE THREAD

**Issue by kymckay** [openstreetmap/iD#7609]
I have some inkling of what's causing this.

So there's currently a bit of a race condition when first enabling the Osmose layer:
1. Issue details (strings and colours) are all requested from the API upon first toggling the layer.
2. Independently, the rendering begins to tell the Osmose service to request issue tiles from the API as needed to cover the viewport.
3. If any issue tile requests are resolved before all of the detail requests resolve, then it's possible for issues to be rendered (in white) before their appropriate colour is known.

I've looked into forcing the layer rendering to wait for all the detail promises (requests) to resolve in the past and seem to remember finding it wasn't trivial because of the way data layers are implemented currently. If I'm not mistaken it's not so simple to implement logic to delay a specific layer from being shown, you'd need to tweak the framework to allow for that first.

For this more specific and noticeable scenario (after upload), it's interesting that the icons all become white because iD shouldn't need to re-request that colour information.

**Comment by kymckay** [comment]
Actually it does seem like the initial race condition that happens when the layer is enabled for the first time is not related to the icons becoming white after uploading OSM changes.

It seems like iD is purging that cached detail information (because panning the viewport to new tiles still loads white issues) and so it doesn't get re-requested until the layer is toggled off and on again.

I think this must be the `reset` method of the service being called which reassigns the `_cache` variable, so presumably this can be fixed by retaining the static information (`strings` and `colors`).

**Comment by quincylvania** [comment]
@SilentSpike Thanks for reporting and fixing!
