### ISSUE TITLE
iD adds building=yes when offering to upgrade amenity=bus_station tag

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7613]
When an amenity=bus_station is upgraded, it adds the following tags: building=yes, bus=yes, and public_transport=station.

This is a problem when the bus_station is an area around the place where buses stop / turn, and not just on the bus station building. And it's also something that users might not even notice when clicking to upgrade the tag in iD. 

Simply, iD should not add building tags in this situation.

**Comment by RobJN** [comment]
Thanks for the quick fix. Same issue appeared in Coventry, England where I had to revert part of an edit. Came here to raise an ticket and found it had already been solved :+1:
