### ISSUE TITLE
Don't add capacity=1 to amenity=parking_space

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7616]
Capacity=1 shouldn't be added by default. I often use `amenity=parking_space` to map more than one single space. So for such features iD suggests that `capacity=1` is missing. Everyone can add capacity manually.

[Wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space): "If an area represents more than one parking space (of equal kind), use capacity=* to define the number of parking spaces it represents. The default value for capacity=* is "1" if not mapped otherwise."
"Exceptions for using one area to represent more than one space:
- A lot of similar parking spaces side by side without any differing attributes and you don't want to put that much effort into it (for example bicycle parking).
- Spaces are just too small to map (for example for bicycle parking)
- Satellite images aren't good enough and don’t allow the mapping of single parking spaces, but you can still make out separate groups of spaces."

**Comment by quincylvania** [comment]
@maro-21 The `amenity=parking_space` tag exists only to delineate singular units of parking. Adding `capacity=1` by default helps convey this to mappers and encourages them to be explicit if they decide to break this guideline for some reason. Personally I don't understand those supposed exceptions—if you can't accurately map single spaces then there's no need to map spaces at all, I'd just use the parking lot tags.
