### ISSUE TITLE
Search OSM notes by ID

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7618]
Similar to how you can search for nodes, ways and relation ids in the search box, it would be good to have this option for OSM notes as well.

![Screenshot_2020-05-19 OpenStreetMap](https://user-images.githubusercontent.com/16965772/82342837-0136ff80-99ea-11ea-8f3b-9d7dbf6a285f.png)

I don't know if it would even be possible to fetch the highest current note id and use that as an upper limit (plus a margin), but there could be a way for iD to recognise that a note doesn't exist for a given id number?

Same could be done for ways or relations where their id number is much lower than nodes.

**Comment by maro-21** [comment]
What would you use it for?
If I see a note that I can resolve, I press Edit on this area.

**Comment by boothym** [comment]
Well, if there is more than one note to fix in the area, they can be edited at the same time.
Just like with you can do with a node or way id just now. 

Would also help when trying to find the next note to edit if there are many notes in the same area. Going directly to it is better than dragging the map around with all the OSM data, trying to find it.

**Comment by k-yle** [comment]
This was fixed in #10062
