### ISSUE TITLE
Crossing way-waterway not warning shown in ID

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#7623]
Dont know if reported already, but in any crossing way-waterway there is NO Warning from the system if they share a connection node with any attribute, if there is NO node shared between the way-waterway crossing, them the system raise a warning in Issues and suggest correction.

The connecting node should be a Ford, or be added a Tunnel or a Bridge for this crossing (way-waterway)..

**Comment by quincylvania** [comment]
Yep, this is #7418.
