### ISSUE TITLE
Taxiway's are treated as non-routable

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#7626]
As seen here ![](https://i.imgur.com/jXOwKpI.png) The taxiway is the only way to access the service road, so shouldn't it be counted as routable?

**Comment by manfredbrandl** [comment]
I think that’s okay. The solution is to have a highway-tag for (part of) the taxiway.

**Comment by quincylvania** [comment]
@JamesKingdom I've also been annoyed by this in the past, but I don't see how we can change this behavior given the limits of the OSM data model. Routers aren't expected to treat lines without a `highway` or `route=ferry` tag as routable, so silencing the warning in iD wouldn't actually fix the connection issue. Piers, athletic tracks, and transit platforms suffer from the same problem. @manfredbrandl is right, you can add a tag like `highway=service` to the taxiway, though be sure to add proper access restrictions. iD shouldn't add such a tag automatically lest routers start sending unsuspecting cars out onto the tarmac 😬.

I really wish there was a single base tag in OSM for all thoroughfares, but there isn't, so here we are.
