### ISSUE TITLE
Adjust Imagery Offset not easy for hundred meter cases

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7633]
Adjust Imagery Offset works great.
But it has never been tested in cases where one needs to tug it 100 meters,
![8527-0](https://user-images.githubusercontent.com/1230959/82842763-5359b280-9f0d-11ea-9b57-e3116e00d389.jpg)

https://www.openstreetmap.org/edit?#map=18/24.29681/121.03853 (Bing).

A few adjustments would make it easier for users to adjust longer distances with each mouse grab.

Sure, "report a bug to Bing." Yes, but iD still could do a better job at letting the user adjust longer distances.

**Comment by quincylvania** [comment]
@jidanni The vast majority of imagery that needs adjusting only requires a few meters offset, so we're going to tune the UI for this use case. A few extra clicks for a rare, extreme offset seems fine. You can always just type the offset if dragging is a pain.

**Comment by jidanni** [comment]
> You can always just type the offset if dragging is a pain.

(Yes, but we don't know that yet. That's is why we are tugging on the map, little by little.)
