### ISSUE TITLE
Adding JOSM terracer feature into iD editor

### ISSUE THREAD

**Issue by MASangys** [openstreetmap/iD#7635]
As a user from Malaysia, almost 80 percent of houses in Malaysia are in terrace form (locally call it as Taman or Garden in English). Plus commercial building are also in terrace form. So, I would like to request JOSM terracer that can spilt way equally into several block plus auto filling housenumber to be added in iD. JOSM is pretty hard to use compare to iD and there would be more easier if someone added this feature in the upcoming iD version. Thank You.

**Comment by quincylvania** [comment]
Greetings and welcome, @MASangys. We're tracking this feature at #6988—other mappers have been missing this tool as well.
