### ISSUE TITLE
New preset: highway=proposed

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7636]
It's a very popular tag, used over 85,993 times.
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dproposed

I often use it because in my city they often create new name for a future street and create addresses with this street, although sometimes the road isn't physically build.

Fields:
- Type
- Name
- Source

The last tag is important, because proposed roads are not visible on the ground so filling in this field is important.

It can be even unsearchable preset, but at least this. It will be easier to fill in the fields even after typing `highway=proposed` manually.

**Comment by quincylvania** [comment]
Hmm this one's tricky. As the wiki notes, proposed features are controversial since they're not verifiable on-the-ground. Plus there could be plans for non-authoritative sources, multiple different plans, plans that change dozens of times, plans that get pushed back years, and plans that get cancelled altogether. I definitely don't think we can have an addable/searchable preset; I'm not sure about an unsearchable one. I'm okay making it relatively hard to add things like this with iD.

**Comment by maro-21** [comment]
But it's used anyway. So it would be good to see the preset name if someone click such feature while editing. That's why I suggested to be unsearchable.

**Comment by quincylvania** [comment]
We don't add presets just because people are using a tag. People can make up tags for anything and often do.

Unsearchable presets have their place, but mappers who encounter them may understandably assume the feature type is "official" and get confused when they can't add their own.

**Comment by matkoniecz** [comment]
I would strongly against promoting this kind of unverifiable, controversial type of data that is never based on survey on mapping from aerial images.

**Comment by quincylvania** [comment]
@maro-21 After further consideration, I think this type of change needs to be discussed in the broader OSM community first. An unsearchable preset may seem like a minor thing, but it'd be a significant change to support proposed features in any way.

**Comment by maro-21** [comment]
> 
> 
> I would strongly against promoting this kind of unverifiable, controversial type of data that is never based on survey on mapping from aerial images.

Proposed highways aren't rendered on maps anyway. No one will be hurt.
This tag is often used anyway, no matter if there is a preset or not.

Quincy: Why? This preset is for mappers, not for renderers. Not having a preset won't stop people from adding such roads.

**Comment by matkoniecz** [comment]
> No one will be hurt.

Collecting in OSM data that should not be collected in OSM in undesirable (`highway=proposed` is quite controversial here)

> Not having a preset won't stop people from adding such roads.

But it will reduce it and they will be lower chance of misleading people. Adding such data is controversial among OSM community.

> Proposed highways aren't rendered on maps anyway.

There is more than one map, see for example https://jakdojade.pl/krakow/trasa/ that for some reason shows them (along with other random stuff like names of religious administrative boundaries). http://overpass-turbo.eu/s/UEz

![screen](https://user-images.githubusercontent.com/899988/83623813-16875e80-a592-11ea-9afd-729b798c503f.png)
![screenshot-f88786a52](https://user-images.githubusercontent.com/899988/83623809-14bd9b00-a592-11ea-9094-f8748acf6719.png)
