### ISSUE TITLE
Mid-way toggle is too close to top bar to easily grab

### ISSUE THREAD

**Issue by jgscherber** [openstreetmap/iD#7640]
![image](https://user-images.githubusercontent.com/6207661/83298662-752b9180-a1ba-11ea-947d-21b4fc5aa0e9.png)

The toggle seems to stay a fixed distance from any edge of the map view, but with the top bar coverting part of the view the mid-way toggle is right on edge of it, making it hard to grab.

**Comment by quincylvania** [comment]
What an interesting little usability bug. I'd never noticed this but now I can't unsee it. The minimum distance is probably just hard-coded somewhere and was set before we made the toolbar taller to add the labels.
