### ISSUE TITLE
Do not show current relation in dropdown

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7648]
When adding a new bus route relation, I accidentally clicked a relation in the dropdown next to the one I wanted to choose, as it had a similar name.

However this relation was already added to the way - should it even be available to select from the dropdown? Surely relations can only be added to a way once?

**Comment by 1ec5** [comment]
I’ve previously mapped bus routes that loop back over themselves, requiring double membership, but I don’t know how common that is.

**Comment by quincylvania** [comment]
Even if it's really uncommon, if it's possible then we should support it in iD. But I agree it's too easy to accidentally add the same relation twice. We should at least style these values differently in the list and possibly add a label.

**Comment by boothym** [comment]
Let's say a route uses the same roads in and out of a bus station, or the same roundabout twice - how would that work? Would you just add the same relation to the way twice (perhaps with forward and backward roles?) 

Maybe another issue should be opened for this, but what about listing recently used relations first in the dropdown? That way you don't have to scroll down to find your last used relation.

Sorting the relation dropdown by type would also be useful #5997

**Comment by BjornRasmussen** [comment]
>Let's say a route uses the same roads in and out of a bus station, or the same roundabout twice - how would that work? Would you just add the same relation to the way twice (perhaps with forward and backward roles?)

A long time ago, this was not possible to represent in OSM, so people created a newer system for mapping bus routes called PTv2, which requires that the roads be added to the bus route relation in the order that they are covered by the bus.  If a bus route uses the same road twice, then the road will be part of the relation twice, but in different parts of the parent relation.  See [this wiki page](https://wiki.openstreetmap.org/wiki/Buses#Adding_a_bus_route_to_OpenStreetMap), specifically the section on adding a bus route, for a better explanation.  

Also note that in the newer system, all roles were dropped for roads, so no `forward` or `backward` roles are used.

**Comment by 1ec5** [comment]
We should visually distinguish any existing relation membership without preventing the user from adding it: #10501.
