### ISSUE TITLE
make covered=* for amenity=telephone to a three-options field and booth=* to an undertag

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [openstreetmap/iD#7654]
Usually, the key covered=* has the values "yes" and "no", but for telephones there is a third special value, covered=booth to show that a phone has a full-cover.

This tag exists on the one hand to differentiate between a full-cover (booth) and just a roof (covered=yes) for a phone, and on the other hand because shelter=yes would not really fit for a telephone (it has not a shelter in sense of what an amenity=shelter is).

See also https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtelephone and https://wiki.openstreetmap.org/wiki/Key:covered

iD does support this tag already by showing covered=booth, but there is not the possibility to _add_ this, except adding this manually. But the **main problem** is that booth=* , which is an under-tag of covered=booth, is a "required" or "standing" tag, but covered=* is only an addable tag. So mappers use booth=* just as a "yes" and "no" tag sometimes (booth=no has 194 uses), because they see it first. But this tag is not intended for that. It should be added only when there is covered=booth, and when there is no booth, covered=no should be tagged and not really booth=no.

(The problem might be also that the name of the key is booth=* , while the name, according to the tag's meaning, should actually be booth:type=* or something like this, this would make it clearer). But it's grown historically.

I think booth=* should be made to an addable tag, as covered=* is already. Maybe it would be also worth to make covered=* to a three-options field for telephones, like choosing between covered=no/yes/booth, and then showing booth=* for the type of booth only when covered=booth is tagged.

Why is "booth" not a yes/no-tag?
Because covered=* is for describing how a feature is covered. It is like you would use amenity=shelter and shelter_type=*, but when there is not shelter, you use shelter_type=no instead of shelter=no to show that there is no shelter.

**Comment by bhousel** [comment]
see #5088

**Comment by Elefant-aus-Wuppertal** [comment]
Hmm, okay. I see some mappers don't like covered=booth. But then, my suggestion would be to make booth=* to an addable and not a standig tag, because not every telephone at all does have still a booth in these times. Some ones do have, but many others not. Some other tags would apply on many many more phones, like payment:coins=yes etc.

booth=* is needed, but should be an addable one.

**Comment by Elefant-aus-Wuppertal** [comment]
Or maybe I should start a discussion about how telephone covers get tagged? There a some options: covered by a roof, by a "hood", and by a "booth".

**Comment by Elefant-aus-Wuppertal** [comment]
Oh yes, okay, I'm going to do that

**Comment by bhousel** [comment]
For context, around the summer of 2018 I tried working through this and a few other seemingly simple issues with the folks on the tagging mailing list. https://lists.openstreetmap.org/pipermail/tagging/2018-June/037336.html

I don't think it went particularly well, and that was 2 years ago.

**Comment by Elefant-aus-Wuppertal** [comment]
Oh yes you are right. I read the discussion and see what you mean. But I might try making another propose again and then will look what "the folks" say. It might work or not. Maybe this could be set as waitfor-info until then...

**Comment by Elefant-aus-Wuppertal** [comment]
I created a proposal for tagging telephone's covers more detailed, maybe someone wants to look at it: https://wiki.openstreetmap.org/wiki/Proposed_features/extend_telephone_covers
please place any comments on the discussion page.

I know the key covered=* is used for it and some people do not like to see this, but covered=* isn't a yes/no boolean key at all. We also have covered=colonnade and arcade for roads. It's like departures_board, this is also a tag describing equipment of something (equipment of a platform) and it also has more values than yes and no.

**Comment by quincylvania** [comment]
I think #5088 already addressed this. You can add `booth=yes` if there's a phone booth.
