### ISSUE TITLE
Create Preset for destination_sign relation

### ISSUE THREAD

**Issue by mfbehrens** [openstreetmap/iD#7655]
This is a request for a new **Relation**-Preset.

Wiki article can be found here: https://wiki.openstreetmap.org/wiki/Relation:destination_sign

Required tag: **`type=destination_sign`**

Fields:
- `destination` (multiple: dest_1;dest_2;dest_3)
- `distance` or `time` (also multiple: time_dest_1;time_dest_2;time_dest_3)
- `destination:ref`

Optional Fields:
- `colour:back`
- `colour:text`
- `colour:arrow`

I don't know in how far it is possible to define roles for a preset but if it is, here they are:
- `sign` (required)
- `to` (required)
- `intersection`
- `from`
- `via`

**Comment by quincylvania** [comment]
Thanks, this is #6970.
