### ISSUE TITLE
Magic mouse horizontal scroll doesn't start a map pan

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7659]
Scrolling vertically with a magic mouse on macOS properly starts to pan the map, and from there you can scroll-to-pan in any direction. However, the same does not work as expected when starting to scroll horizontally. Previously a horizontal scroll could start browser page navigation, but since fixing #5552 it just does nothing.

**Comment by quincylvania** [comment]
Turns out this was caused by iD ignoring scroll events without a vertical component, because historically these would not affect the map's transform. It now appears to work correctly.

I don't think this addresses #7134, since iD tries to treat events from physical scroll wheels differently than gesture scroll events, but I don't have a mouse with a horizontal scroll wheel so I can't test it.

**Comment by 1ec5** [comment]
> I don't have a mouse with a horizontal scroll wheel so I can't test it.

How about a trackpad where you scrub the bottom edge to scroll horizontally? Would it be interpreted the same way as a mouse with a horizontal scroll wheel?

**Comment by quincylvania** [comment]
> How about a trackpad where you scrub the bottom edge to scroll horizontally? Would it be interpreted the same way as a mouse with a horizontal scroll wheel?

@1ec5 Not sure, I'm not familiar with this interaction… I have a MacBook.

**Comment by 1ec5** [comment]
Yeah, I’m thinking of Windows laptops mainly. I’ve previously owned Dell and Toshiba laptops with this sort of scrolling before.
