### ISSUE TITLE
Catch 22: Not enough visible to let me delete; have to zoom out too far

### ISSUE THREAD

**Issue by newnumber2** [openstreetmap/iD#7676]
I was trying to delete a section of power line so that I could re-do it from scratch rather than edit the existing line. I selected it but iD would not let me Delete it because not enough of it was visible. However, for enough of it to be visible, I had to zoom out too a level where iD tells me I need to zoom in to do ANY editing. Of course, then, when I do, not enough of it is visible again.

The only workaround I can think of is to split the miles-long power line into smaller lengths and then delete those.

By the way!  The reason I decided to do this was because copying and pasting in iD apparently only works for creating new features, not copying keys/tags to existing features. I wanted to add new pylons (power=tower) to this power line; the existing ones each had four tags (design, material, structure included) and I didn't want to have to add those every time I added a new pylon. In Potlatch I can duplicate tags with each new pylon using the "R" hot key. Isn't there any way in iD to do the same?

I would also like to be have the PARALLEL tool in Potlatch available in iD.

**Comment by quincylvania** [comment]
>  I selected it but iD would not let me Delete it because not enough of it was visible. However, for enough of it to be visible, I had to zoom out too a level where iD tells me I need to zoom in to do ANY editing.

Yep, deleting large features in iD is intentionally difficult. It's a problem if someone can carelessly delete Iceland or some large stretch of the Nile or the Pacific Coast Highway. But if the entire feature fits on screen with all the nearby features visible, then at least the mapper will see the results of their actions.

That said, we've also been trying to make iD scale to the needs of advanced mappers. #2929 would let you override some safety checks and #1520 would let you edit at lower zoom levels in rural areas.

For your specific need of copying tags to many existing features, the next release of iD will let you edit the combined tags of multiselections. Try it on our [preview site](https://ideditor.netlify.app/), simply shift+click to extend a selection and use the text tag editor to copy and paste.

> I would also like to be have the PARALLEL tool in Potlatch available in iD.

You can open a separate issue for this if you want to discuss it further, we try to keep issues pretty scoped here.
