### ISSUE TITLE
Moving many kilometers while zoomed out is slow

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7679]
Let's say there is a complicated node,

> communication:mobile_phone=yes
> height=5
> man_made=mast
> mimics=water tank
> name=行動電話基地台
> tower:construction=lattice;concealed
> tower:type=communication

that we want to copy to a place, 10 km to the north.

(If it were a simple node, then we might just create it afresh. But it is not.)

OK, our journey begins by doing CTRL+C to copy it.
Then we zoom out, and drag ourselves 10 km. to the north,
and then zoom back in, and then do CTRL+V to place it on the map.
Simple.

However as you will notice even with a fast computer (but slow network) it turns out
to be much more time consuming than other methods that might get us to our destination directly... (yes, we could have just put coordinates in the search box.)

So perhaps some work could be done on making moving many kilometers  while zoomed out faster. Thanks.

**Comment by jidanni** [comment]
Ah! The problem is:
1. User zooms out, (to a "Zoom in to edit" message level)
1. User pans one screen to the north.
1. At first this screen is all black
1. Now the imagery is pulled in
1. Now the major roads are carved (black) into the imagery.
1. Now the user has an idea of where he is and where to move from here.

**Comment by jidanni** [comment]
At least in rural areas, if the few roads were shown first, then he wouldn't have to wait for the imagery to be pulled in, and could continue panning right away.
(But that would be black upon black in the current arrangement.)

**Comment by quincylvania** [comment]
I don't see how we can make this faster if the bottleneck is a slow network connection. iD can't show imagery tiles it hasn't downloaded yet. A slow network is certain to make data-dependent workflows slower, and map editing requires a lot of data by definition. #1520 might help with your problem if the data is already downloaded.
