### ISSUE TITLE
Validator: check for crossing=traffic_lights (pedestrian light)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7685]
While manual adding a highway crossing (`highway=crossing`) I tried also maually add the details for a pedestrian crossing light/signal (which is mainly tagged by using the `crossing=traffic_signals`). The list for key `crossing` of the dropdown menu shows e.g. items for
`traffic_signals`
and
`traffic_lights`
It is a bit confusing to select the right one, when you see these two similar values.

![image](https://user-images.githubusercontent.com/47290585/84096780-0c86b500-aa03-11ea-8639-a2f68f6331a4.png)

Currently there are not many items of (the potential wrong selection) https://taginfo.openstreetmap.org/tags/crossing=traffic_lights#overview
in the database (~600).
But maybe because of the long run risk, that people will sometimes use light instead of signal, it could be worth to add validation check. What others think about it?

PS: btw i also found `crossing=pedestrian_signals` (~2000) in the list https://taginfo.openstreetmap.org/keys/crossing#values, don't know who did invent it and if this is a suited alternative, or also worth for validation.

**Comment by boothym** [comment]
The best way to fix this would be to edit the map and lower the number of traffic_lights values, so that iD no longer shows the wrong value from taginfo 😉 (though the value only appears near the top when you begin typing "traffic")

More importantly, the presets and fields for crossings need to be improved so that most people wouldn't need to manually edit crossings.

**Comment by sun-geo** [comment]
@boothym 

> The best way to fix this would be to edit the map and lower the number of traffic_lights values, so that iD no longer shows the wrong value from taginfo 😉

This request is to add a rule which displays a warning message for `crossing=traffic_lights` objects & this would most likely be exactly reduce the database amount for this tag over time. I don't want to do any mechanical edits. ;-)

> More importantly, the presets and fields for crossings need to be improved so that most people wouldn't need to manually edit crossings.

Agree, would you open a separate issue for that idea?

**Comment by sun-geo** [comment]
Thank you
