### ISSUE TITLE
Issue "Foot Path crosses House" still shown althoug covered=yes was added

### ISSUE THREAD

**Issue by der-dirk** [openstreetmap/iD#7689]
In the following section I marked a path that contains a passage through a house with "covered=yes": https://www.openstreetmap.org/edit#map=21/48.16523/11.76064

According to these entries in the wiki I guess that was correct:

- https://wiki.openstreetmap.org/wiki/Key:covered
- https://wiki.openstreetmap.org/wiki/DE:Key:covered

Nevertheless the issue "https://wiki.openstreetmap.org/wiki/DE:Key:covered" is still shown.

**Comment by matkoniecz** [comment]
Main problem is that node/point where `covered=yes` starts/end should be also attached to building.

bad:
![screen](https://user-images.githubusercontent.com/899988/84213533-3c948d80-aac1-11ea-91f4-1adda6ca132e.png)

good:
![screen05](https://user-images.githubusercontent.com/899988/84213536-3d2d2400-aac1-11ea-8de0-ef367b6a3b79.png)

I edited this specific case. Maybe iD can communicate this better.

**Comment by der-dirk** [comment]
Thank you very much for this quick response and the immediate fix. Sorry for posting this as a bug.
