### ISSUE TITLE
Pharmacies in Quebec province are dispensing prescriptions by default, but are set to dispensing=no

### ISSUE THREAD

**Issue by kaligrafy** [openstreetmap/iD#7693]
Jean-Coutu, Pharmaprix, Proxim, Brunet, Familiprix and Uniprix pharmacies are dispensing prescriptions by default, but are set to dispensing=no in iD. They should be set to dispensing=yes

**Comment by quincylvania** [comment]
@kaligrafy Thanks, iD's brand presets are handled over at the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) so you'll have to open an issue there 👉
