### ISSUE TITLE
Replace PhantomJS for headless browser testing

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7697]
PhantomJS was [abandoned in 2018](https://github.com/ariya/phantomjs/issues/15344) and the mocha-phantomjs-core project used by iD for testing [followed suit](https://github.com/nathanboktae/mocha-phantomjs-core/commit/562125f41e4248a9ae19b91ed2e23a95f92262e9). We've been coasting until now, but mocha just [deprecated](https://github.com/mochajs/mocha/pull/4178) some of the functions used by mocha-phantomjs-core (#7695). This means we can't keep up-to-date with mocha with our current setup, which is an unsustainable proposition. Testing is fundamental.

There's been [talk in the past](https://github.com/openstreetmap/iD/issues/5246#issuecomment-415636003) of switching away from PhantomJS, but now it's become a more immediate priority. I'm sure there are good, modern solutions out there, but we need to make sure we're still testing legacy browsers where possible. PhantomJS uses the same polyfills as Internet Explorer and as a result, tests for compatibility issues that might otherwise be difficult to find. See #6087 for related work.

**Comment by HolgerJeromin** [comment]
Can this issue be closed?
