### ISSUE TITLE
render sidewalk &/ verge with road

### ISSUE THREAD

**Issue by j47996** [openstreetmap/iD#7700]
The renderer used for https://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=52.809367&lon=-0.86894 shows sidewalk info, though does not distinguish left/right/both detail

**Comment by boothym** [comment]
Similar to #1762 - iD could show the sidewalk info in a field like the cycle lanes.

**Comment by kymckay** [comment]
#5659

**Comment by boothym** [comment]
@SilentSpike didn't realise you'd submitted a PR back then. The sidewalk tag is used a lot of more than cycleway=* on highways yet we have a cycle lane field in iD...

**Comment by quincylvania** [comment]
This is similar to #2701, which was closed as stale. I agree with Bryan in #5659 that sidewalks should really be mapped as separate ways. In any case, I wouldn't want to visualize sidewalks on roads without also bike lanes, probably as part of full lane rendering/editing. So I'm closing in favor of #387 .
