### ISSUE TITLE
Move the presets folder into an own repository

### ISSUE THREAD

**Issue by PhilippRigoll** [openstreetmap/iD#7702]
I propose to move the presets folder into an own repositiory and include it here using git submodules. This way presets are separated from the rest of the codebase. I think the code and the presets should be unrelated. This also enables other editors to easily use these presets via git submodules.

**Comment by manfredbrandl** [comment]
Also Quality Assurance Tools could use the repository and automatically find inconsistencies between the presets and other resources (wiki, new trending tags, etc).

**Comment by kymckay** [comment]
Some history of this:

#2656
#6483
#7130

**Comment by quincylvania** [comment]
I'd say it's high time to do this. Beyond the technical advantages to modularity, it'd be a huge benefit organizationally if tagging issues could live in a separate repository from the rest of iD.
