### ISSUE TITLE
Edit Organic Goods Store preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7714]
Why Organic Goods Store is a supermarket in iD? Isn't it possible to have Organic Goods Store which is a convenience store? Supermarkets are bigger than convenience shops. I think one can use `organic=only` on `shop=convenience` too.

In my country organic goods stores are usually very small, there are almost no stores big enough to call them supermarkets.

We should do someting about it. Either:
- rename the preset to Organic Goods Supermarket
- or add a preset for `shop=convenience + organic=only` too (this isn't a good idea)
- or remove this preset and add [`organic`](https://wiki.openstreetmap.org/wiki/Key:organic) key to proper presets (`shop=farm`, `shop=convenience`, `shop=supermarket`, `amenity=restaurant`) - for me this would be the best solution.

**Comment by quincylvania** [comment]
Oh yeah we should rename this. Looks like the name comes from the original `shop=organic` preset from before that tag was deprecated. See #2348.
