### ISSUE TITLE
Edit presets/README.md

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7715]
I've noticed some broken links in the file.

Because you renamed the branch `master`, it should be fixed in two places:
- _Upon merging with `master`_
- _`* [iD's spritesheet](https://github.com/openstreetmap/iD/tree/master/svg/iD-sprite/presets)`_

And
- Link to Maki works, but it's a redirection
- Link to Temaki doesn't work: 404

**Comment by quincylvania** [comment]
@maro-21 Thanks, these have already been changed in the `develop` and `release` branches. Did you follow a link that needs updating?

**Comment by maro-21** [comment]
Oops, it looks like I saw an old version, sorry :)
