### ISSUE TITLE
Consider complaining about amenity=school inside amenity=school, amenity=hospital inside amenity=hospital...

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7719]
Repeated mistake made by various iD mappers is to retag `building=school` within `amenity=school` area into `amenity=school` what due to #5883 removes building tag.

Appearing complain about `menity=school` within `amenity=school` would increase chance of reverting that edit or at least spotting that school was mapped already.

It would help reduce impact of #5883 and allow to spot some type of mistagging (like mapping every building of `amenity=hospital` as a separate hospital).

Triggered by https://forum.openstreetmap.org/viewtopic.php?pid=791369#p791369 where someone was not expecting iD bug and was sure that it was a deliberate damage of map data.

**Comment by boothym** [comment]
Wouldn't that be an issue if you have two buildings, each with separate schools in them but on the same campus? 

As in - the campus grounds are marked as amenity=school, but inside them each building is also tagged as a school? Is that even the correct way of doing things?

**Comment by sun-geo** [comment]
btw, see also use case 3 
(_"here more than one education type (school, kindergarten, colleage, university) are located in a larger campus."_)

https://wiki.openstreetmap.org/wiki/Tag:landuse=education#Use_cases

**Comment by SK53** [comment]
Whereas I agree that there is much egregious use of amenity=hospital for indivdual services within a hospital, I'd exercise caution with this suggestion. I can think of several valid uses of both school within school and hospital within hospital. Some specific examples:

* [Military hospital](https://www.openstreetmap.org/node/2492690989) within major teaching hospital. 
* [Djanogly Sherwood Academy](https://www.openstreetmap.org/way/337493764): overflow class area for a primary school in the grounds of a related secondary school (Djanogly City Academy)
* [NHS Treatment Centre, Nottingham](https://www.openstreetmap.org/way/30891414). Despite its name this is a private hospital in the grounds of a public hospital undertaking out-patient & day case work. In the main hospital there is a separate "day hospital" for day cases (not mapped) and the children's services are still known as Nottingham Children's Hospital (also not mapped). 
* [Cambridge Biomedical Campus](https://www.openstreetmap.org/way/4040865#map=18/52.17379/0.13975). Currently mapped as a single hospital with that name (incorrectly IMO), contains at least 3 hospitals: Addenbrookes, the Rosie & the Royal Papworth Hospital in addition to several university buildings and biomedical research institutes.
* [Hartford Campus](https://www.openstreetmap.org/#map=16/53.2471/-2.5315). All the schools at this site share facilities, and although mapped separately the actual area labelled Hartford Campus should include all the schools not just the playing fields.

I think the Cambridge situation is what may happen when a one hospital/school rule is enforced. The common problem with these cases is a shared campus with multiple facilities as pointed out by others.

**Comment by doublah** [comment]
Maybe one of the QA tools integrated into iD could ask the user if the tag is correct if it's used inside the same tag?
