### ISSUE TITLE
Feature request: change point to way or area

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#7721]
Platforms are often mapped as point with many relations.
![image](https://user-images.githubusercontent.com/5360273/85130207-c9171c80-b234-11ea-9beb-b62601100664.png)
It would help a lot if iD could change this object into way or area and keeping relation membership and attributes.
See https://www.openstreetmap.org/#map=19/47.38820/16.00108

**Comment by quincylvania** [comment]
@manfredbrandl You should be able to accomplish this already by drawing a line or area, selecting that with the point, and using the Merge operation.

**Comment by rahullli** [comment]
I would like to work on this issue , can you please explain more about the issue ?

**Comment by quincylvania** [comment]
@rahullli Thanks for your interest! We're still looking into this particular issue, but you can check out [beginner](https://github.com/openstreetmap/iD/labels/good%20first%20issue) or [intermediate](https://github.com/openstreetmap/iD/labels/help%20wanted) issues to work on. Please review the [contributing guidelines](https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md) too.

**Comment by manfredbrandl** [comment]
Works like a charm! Is this documented anywhere?

**Comment by quincylvania** [comment]
> Is this documented anywhere?

Perhaps not! We should really detail the operations in the help panel.
