### ISSUE TITLE
layout of "choose object type" improvement request

### ISSUE THREAD

**Issue by sevku** [openstreetmap/iD#7722]
So, I don't know what title would suite this best, so please just edit it.

The problem I have is the following:
![OSM_Layout_Screenshot_0](https://user-images.githubusercontent.com/23403917/85268405-c0ae2400-b476-11ea-9561-58c4bda4c0e7.png)

At least in german, "markierter / gekennzeichneter Übergang" is a very long word. Additionally, there are two versions of it, a "normal" one and one that is "erhöht".

To see which is which, I'd have to pull the sidebar out every time, or just remember which is which:
![OSM_Layout_Screenshot_1](https://user-images.githubusercontent.com/23403917/85268581-fce18480-b476-11ea-9e49-efcff861dabc.png)

So my sugesstion would be to have two lines of text.

**Comment by quincylvania** [comment]
Thanks, @sevku, looks like we've already fixed this for the next release! You can test at https://ideditor.netlify.app.

![Screen Shot 2020-06-22 at 9 28 36 AM](https://user-images.githubusercontent.com/2046746/85293061-d289ca00-b46a-11ea-821c-4cbeeee57922.png)
