### ISSUE TITLE
Add line_management and discourage tower:type usage on power supports

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#7726]
Dear maintainers,

Recently, line_management key has been reviewed on osm wiki.
Mappers are now encouraged to use it to describe particular topology situations of power lines around their supports.
https://wiki.openstreetmap.org/wiki/Key:line_management

Furthermore, tower:type and pole:type are now discouraged on power=tower, power=pole, power=portal, power=insulator and power=terminal

Could you add line_management to power=tower, power=pole, power=insulator, power=terminal and power=portal presets please?

Use of tower:type=* or pole:type=* with any power=* value should raise a warning.
See approved proposal for replacement scheme : https://wiki.openstreetmap.org/wiki/Proposed_features/Lines_management#Values_to_be_replaced

Thanks in advance to get this done, all the best

François

**Comment by flacombe** [comment]
This is great, thank you @quincylvania

**Comment by maro-21** [comment]
How do you call _line management_ in other words? Because I'm thinking of the right translation. [Wikipedia](https://en.wikipedia.org/wiki/Line_management) doesn't help.

**Comment by quincylvania** [comment]
> How do you call line management in other words?

I'm not sure, but I'm open to suggestions for the English label. "Line Management" isn't very intuitive, but I left it since it matches the tag directly and only power-mappers are likely to see it anyway.

**Comment by flacombe** [comment]
Line management is definitely an OSM vocabulary chosen accordingly with line_attachment=* key.
It deals with particular topologies of any kind of line (both underground and overhead) around their supports or particular waypoints.

It could be rephrased as Line topology pattern IMHO.
