### ISSUE TITLE
Add "sand pit" to presets (landuse=quarry)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7730]
"sand pit" as in sand mining https://commons.wikimedia.org/wiki/Category:Sand_mining

"sandpit" as in playground feature is present

Optionally autoadd `resource=sand` if that is supported and shown by iD

**Comment by quincylvania** [comment]
@matkoniecz What exact tags are you proposing for this?

**Comment by quincylvania** [comment]
I changed the `playground=sandpit` preset name to "Play Sandbox" to hopefully avoid people using it for industrial sandpits.

**Comment by matkoniecz** [comment]
`landuse=quarry` + `resource=sand` 

(I have no strong opinion here, but it is standard tagging Poland and tagging that I use myself)

https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dquarry seems to agree (disclaimer: I am very active on OSM Wiki so as usual the page may be written by myself)

https://help.openstreetmap.org/questions/2351/tagging-a-gravel-pit is related and demonstrates that it not some new tagging scheme

> I changed the playground=sandpit preset name to "Play Sandbox" to hopefully avoid people using it for industrial sandpits.

Good idea! I have not encountered this, but given scale of iD use it probably will save some people :)

**Comment by matkoniecz** [comment]
After editing PL translation - maybe `landuse=quarry` should match to "sand pit" and "sandpit"? Not sure is it going to be confusing for native speakers of English.

Though `resource=sand` sounds like a good idea anyway.

**Comment by quincylvania** [comment]
@matkoniecz Hmm I don't think we need to start adding presets for every type of quarry, but we can definitely add more search terms.

**Comment by quincylvania** [comment]
> we can definitely add more search terms.

I did this ⬆️
