### ISSUE TITLE
OSM Japan Slack Invite is no longer valid

### ISSUE THREAD

**Issue by scottAnselmo** [openstreetmap/iD#7731]
When making a commit to OSM via iD among other social network sites/services, it presents an invalid Slack invite for OSM Japan that has expired:

https://join.slack.com/t/osm-japan/shared_invite/zt-d0my5ek2-SRxGCIsPPIyaOWkJOZ4EMg

![image](https://user-images.githubusercontent.com/3056597/85513754-dba1a500-b5ea-11ea-95bc-d9b65d7e0af3.png)

This should be changed to a permanent Slack invite

**Comment by matkoniecz** [comment]
Thanks for reporting!

iD is pulling this data from https://github.com/osmlab/osm-community-index and it should be fixed there

Do you know which invite would be correct!

**Comment by quincylvania** [comment]
> iD is pulling this data from https://github.com/osmlab/osm-community-index and it should be fixed there

Yep, someone can open an issue or PR there.
