### ISSUE TITLE
Change the title and definition of "polska.e-mapa.net: Buildings" layer

### ISSUE THREAD

**Issue by geo-system** [openstreetmap/iD#7734]
polska.e-mapa.net is a map portal run by us (Geo-System; commercial company),
whereas the current url of the layer is https://integracja02.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow (WMS service owned by GUGiK; Head Office of Geodesy and Cartography in Poland), so there's a clear mismatch.

To fix this the layer should use metadata entries from the service capabilities (https://integracja.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow?SERVICE=WMS&REQUEST=GetCapabilities):

- title should be changed to "Krajowa Integracja Ewidencji Gruntów" (official name of the service, matching the URL) or a more descriptional "Parcels and buildings"

- The proper URL should point to **integracja**.gugik.gov.pl (main server that does the loadbalancing) or switch between integracja**01**.gugik.gov.pl and integracja**02**.gugik.gov.pl

- the layer should also use _dzialki_ (parcels), not only _budynki_ (buildings), so the part of the url should be changed from ..._&LAYERS=budynki_... to _&LAYERS=dzialki,budynki_

- Proposed icon: https://integracja.gugik.gov.pl/ikonki/kieg/mapa_ewidencyjna.png

**Comment by quincylvania** [comment]
Hi and welcome, @geo-s. iD gets most tile layers from the [editor-layer-index](https://github.com/osmlab/editor-layer-index/issues), so you'll have to open this issue over there 👉
