### ISSUE TITLE
Idea: Row of houses (cells) tool

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7735]
The houses on the left were made by CTRL+C CTRL+V CTRL+V CTRL+V ...
More ideal are the houses on the right.
![26369-1](https://user-images.githubusercontent.com/1230959/85737372-e7e44a00-b731-11ea-816f-e9fe43f5d7ac.jpg)
Perhaps a tool could be made:
"Split current rectangle into [___] equal sized rectangles; (x) Lengthwise, ( ) widthwise; (x) clone all tags, ( ) clear all tags, ( ) clear___tag..."

See also
https://help.openstreetmap.org/questions/28409/id-how-do-i-divide-a-linear-row-of-residential-dwellings-to-single-buildings

**Comment by quincylvania** [comment]
Thanks, this is #6988.
