### ISSUE TITLE
add some more keys to the post_box-preset

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [openstreetmap/iD#7738]
Hi,
I think for amenity=post_box, there could be added some more things to its preset:
- how is the post box supported (support=*)
- how is the post box constructed (post_box:type=*, see https://wiki.openstreetmap.org/wiki/Key:post_box:type)
- what colour is it (colour=*)
- what material is it (material=*)

**Comment by Samarath** [comment]
I would like to work on this.

**Comment by quincylvania** [comment]
@Samarath Great, welcome! Check out our [contributing guide](https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md) and the [presets readme](https://github.com/openstreetmap/iD/blob/develop/data/presets/README.md). Let me know if you have any questions.

**Comment by manvisingh07** [comment]
I am interested, I would like to work on this.

**Comment by Adamant36** [comment]
@Lukas458 I was looking at the usage for post_box:type and they all seem to be about the type of support. So, do you know how it would be different then the support tag? Because it looks like they are used the same to me.

**Comment by Elefant-aus-Wuppertal** [comment]
Hmm, okay. In my thoughts there would be a difference between these keys. When you look at post_box:type's wiki page, you can for example find the value "lamp". A post box "lamp" is the kind of its shape to me. Here is what we call "lamp" as a post box in Germany: https://wiki.openstreetmap.org/wiki/File:BRIEFKASTEN_DER_DEUTSCHEN_POST_in_BREITH%C3%9CLEN.JPG

As support, the picture shows a pole. But the support of the "lamp" post box could also be a wall, please look at it in this pic: https://wiki.openstreetmap.org/wiki/File:Gelber_Briefkasten_der_Deutschen_Post.JPG

The same thing for post_box:type=pillar. The post box can be mounted onto the ground directly, but in Germany there's often a little concrete pedestal: https://wiki.openstreetmap.org/wiki/File:Briefkasten_Gie%C3%9Fen_2.jpg
A little one, but its there.

**Comment by Adamant36** [comment]
Hhhmm, that sorta makes sense. I guess. But then you have stuff like `post_box_type=wall + support=wall`. Same goes for the others possibilities. Which just seems wierd and redundent. Everyone knows that a wall post box is supported by the wall that its in. Same goes wiyh a pillar post being supported by the piller. Although technically wall post boxes aren't "supported" by the wall in a traditional sense, but I don't that's something mappers will get. So, I think my main thing is using the support tag. Although it would help describing post boxes like ones that are fences. It could also be the general peoblem with "type" tags. Which aren't really clear and include types of things that aren't really types of things. Like with wall post boxes its more about the location then a type of post box. So I don't know. Id at least say they both need better clarification as to how they are different if both are going to be used and maybe only going with one would be a better option so people don't just duplicate things like with my examples. I do this a lot and even id probably confused as to which tag to use to describe what. It seems rather subjective.

**Comment by Elefant-aus-Wuppertal** [comment]
I see, but at the moment I have no idea how to solve that. So maybe it would be better to exclude adding post_box:type first...

**Comment by Adamant36** [comment]
I would say just leave post_box:type out of it. It looks like its an abandoned mostly reject proposal anyway that mainly only worked in UK. There's a post_box:design tag and post_box:mounting. Both of which have semi-high numbers and would be way better then post_box:type. Although they don't have wiki articles or much discussion from what I can tell. But the best options sounds like just going with the support tag for now and waiting until the other tags get worked out.

**Comment by quincylvania** [comment]
Done in #7777 by @yyazdi13
