### ISSUE TITLE
combine tool doesn't update big block at top

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7746]
I found a restaurant on the map, but it was only a point.
So I drew an area around it and used the combine tool "c", to convert the point into an area.
![X0](https://user-images.githubusercontent.com/1230959/85908488-cb3a3600-b847-11ea-978c-982e90c98900.jpg)

Well, if one wants "area" at the top there to become "restaurant", one need to save the edit.

After saving click the area again.

![X2](https://user-images.githubusercontent.com/1230959/85908601-4996d800-b848-11ea-8a85-821e131a96db.jpg)

Not only has the big block at top finally updated to "restaurant", but we can now also comfortably edit the address, etc. in full detail.

Yes it would be better if we didn't need to wastefully save just to get all that to refresh, but alas the combine tool just currently lacks that step in the things it remembers to do.

[changes.osc.txt](https://github.com/openstreetmap/iD/files/4839636/changes.osc.txt)

**Comment by quincylvania** [comment]
@jidanni You opened this issue in #7450 and we'd already fixed it for the next release. I understand this release is taking awhile, but I ask for your patience. You can try out the new version at https://ideditor.netlify.app.
