### ISSUE TITLE
 Enable Relations section for multiple selected features

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7753]
Similarly to #7324, we should make the Relations inspector section compatible with multiselections. This is tricky, since the memberships may have different roles and the same member can appear multiple times in one relation.

**Comment by AntMadeira** [comment]
This is something I would like to see implemented. When I want to create a long route relation, for example, I have to use JOSM, where is very simple to select the lines I want and add them to an existing or new relation. Of course not all relations are so straightforward, but opening the relations menu and add multiple features to a relation is something that only experienced and savvy mappers would do. I believe the risk of doing something silly here would be minimal.
