### ISSUE TITLE
Consider piers for routing disconnected ways

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#7757]
Currently if a `route=ferry` is connected to a larger network only by `man_made=pier`'s, iD throws the `Disconnected from other roads and paths` error.  
Piers are routable according to [Osmose](https://github.com/osm-fr/osmose-backend/blob/703f6bac7d56b623c193363fb22398f5f24fc93b/analysers/analyser_osmosis_highway_floating_islands.py#L42) and [the wiki](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpier#How_to_map) (kinda).

**Comment by quincylvania** [comment]
The existing behavior is intentional. Not all routers will necessarily treat piers as routable and people use the `man_made=pier` tag for all sorts of things you can't really walk on, like bridge pilings.

You can manually add `highway=footway` or `highway=service` to routable piers.
