### ISSUE TITLE
Spelling German -> "Wald ohne forstwirtschafliche Nutzung"

### ISSUE THREAD

**Issue by SpaeterAendern** [openstreetmap/iD#7758]
"Objekttyp auswählen" shows the term 
"Wald ohne **forstwirtschafliche** Nutzung" without the "t"
"Wald ohne forstwirtschaftliche Nutzung" is the correct term :) 

![Bildschirmfoto_2020-07-01_09-08-58](https://user-images.githubusercontent.com/3099922/86213797-86c9d580-bb7a-11ea-9fdd-7449eac75c37.png)

**Comment by manfredbrandl** [comment]
This was a typo in the Translation, i did correct that:
![image](https://user-images.githubusercontent.com/5360273/86215784-4ddf3000-bb7d-11ea-843a-6737f172d9aa.png)

This will be unrolled to https://ideditor.netlify.app/ when the next change in the develop branch occurs.
With the upcoming release 2.18.0 it will be unrolled to https://openstreetmap.org/.
Can you please close this issue?

**Comment by SpaeterAendern** [comment]
thx!
