### ISSUE TITLE
preview tiles in edit mode are outdated

### ISSUE THREAD

**Issue by 532910** [openstreetmap/iD#7760]
https://www.openstreetmap.org/way/37631652
![image](https://user-images.githubusercontent.com/14617699/86295663-c5ee3a00-bbff-11ea-92b6-2c2b83fac8c5.png)
![image](https://user-images.githubusercontent.com/14617699/86295672-cc7cb180-bbff-11ea-9efb-e203ef6e4e7b.png)

**Comment by quincylvania** [comment]
@532910 Hi and welcome. This is #7025 and has been fixed for the next release.
