### ISSUE TITLE
"zoom in to edit" is not disappearing on zooming in until user dismiss welcome dialog

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7769]
It is a bit confusing, I just completely missed welcome dialog with "start mapping" button (banner blindness?)

Encountered in https://preview.ideditor.com/master/

**Comment by quincylvania** [comment]
@matkoniecz We're not updating that preview site anymore. Let us know if you see this on the `develop` branch: https://ideditor.netlify.app.
