### ISSUE TITLE
Add shop=model preset 

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#7776]
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dmodel - Scale model shop would probably be the best name for it? One of the terms would be "hobby".

To give some context, I saw a shop tagged as shop=hobby and checked the wiki, which said the hobby tag was undocumented and that a more descriptive tag should be used https://wiki.openstreetmap.org/wiki/Tag:shop=hobby

I would tend to agree, especially after looking at how it is used - it seems to cover shops which are better tagged as model, craft, anime etc. Maybe some additional terms can help iD mappers?

An example is this shop was recently added by an iD used as shop=hobby: https://lordandbutler.com/ - so hopefully the shop=model preset will help improve the tagging situation.

**Comment by quincylvania** [comment]
Done in #7779
