### ISSUE TITLE
Wrong shortcuts

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7778]
In the new version of iD, in the settings "Style Options", the tooltip for both "Partial Fill" and "Full Fill" suggests that Space key is the shortcut for toggling this option. It's not true - [W] key is to toggle between "No Fill (Wireframe)" and "Partial Fill". "Full Fill" doesn't have a shortcut.

I also noticed that there is too much unnecessary space between "Data Layers" and "Photo Overlays" (and the other below).

![image](https://user-images.githubusercontent.com/57260466/87223207-54d72100-c37b-11ea-8a9b-57fd1ccdf091.png)

**Comment by quincylvania** [comment]
@maro-21 Thanks for reporting, the tooltip key was a bug. I'm not worried about this spacing, I think it looks fine and helps visually separate the sections.

**Comment by maro-21** [comment]
Could you also add a shortcut tooltip for "Partial Fill"? Because `W` key actually toggles these two options.

**Comment by quincylvania** [comment]
> Could you also add a shortcut tooltip for "Partial Fill"? Because W key actually toggles these two options.

`W` toggles between wireframe and either partial or full fills (whichever was last used). I agree we should make the tooltip key indicate which one, like with the background imagery selection.

**Comment by maro-21** [comment]
You're right, I didn't know it! I thought it toggles only between Wireframe and Partial Fill. It actually toggles between any two of them last used.
