### ISSUE TITLE
Wrong update proposal

### ISSUE THREAD

**Issue by Bibi56** [openstreetmap/iD#7782]
On https://www.openstreetmap.org/node/5904541271, iD [suggests](https://www.openstreetmap.org/edit?editor=id&node=1370801481#map=16/48.3241/-4.7753) to add `seamark:type=light_major`.

Adding `seamark:type=` on `man_made=lighthouse`is a good idea but 2 values are equally making sense:
`seamark:type=light_major`
`seamark:type=light_minor`.
Adding almost silently a refining attribute is a very bad idea, it makes `seamark:type=light_major` useless as after that we don't know if it's an observation or a "decision" made by an editor.

Suggestions:
- remove the "advice"
- ask if it's a major lighthouse (yes/no/don't know) to infer the correct value.

Note: here the (French) name strongly suggest that it's a minor light (`tourelle` not `phare`).
Here the correct node https://www.openstreetmap.org/node/1370801481 is missing the `man_made=lighthouse`. 
I'll correct the nodes after the case has been observed.

**Comment by quincylvania** [comment]
@Bibi56 Thanks, this was fixed in #7621.

**Comment by Bibi56** [comment]
@quincylvania, thanks I looked in the tickets - open or closed - and couldn't find a related issue.

**Comment by quincylvania** [comment]
@Bibi56 No problem, the issue search doesn't include pull requests even though they use the same numbers.
