### ISSUE TITLE
Add portapotty preset

### ISSUE THREAD

**Issue by jleedev** [openstreetmap/iD#7783]
I think the correct tags for a portapotty are `amenity=toilets` and `toilets:disposal=chemical`, but I'm not smart enough to remember this.

Actual: Type in 'portapotty' and come up with nothing. Try the 'toilets' preset, then frown at the refinement options, since I'm not sure if this only applies to indoor facilities.

Expected: Select the 'portapotty' preset and be happy.

**Comment by quincylvania** [comment]
I'd add [`portable=yes`](https://taginfo.openstreetmap.org/tags/portable=yes) too.

**Comment by Nimisha94** [comment]
Hi! I'm new to open source and want to give this a shot! @quincylvania  If you can give me a suggestion on where to start that would be helpful.

**Comment by mohit2872** [comment]
Can you assign this to me?

**Comment by quincylvania** [comment]
@Nimisha94 asked first so let's give them a shot. @mohit2872, you could try #7818 if you want, which is similar.

Check out the presets README for info on how to add one: https://github.com/openstreetmap/iD/tree/develop/data/presets

**Comment by mohit2872** [comment]
@quincylvania  yeah sure

**Comment by TheAdventurer64** [comment]
Shouldn’t this be closed?

**Comment by TheAdventurer64** [comment]
Adding to this, according to [the wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#/media/File%3AECO_Toilets_at_the_Station_Groningen%2C_Groningen_(2019)_02.jpg), shouldn’t `toilets:type=mobile` be added as well?

**Comment by quincylvania** [comment]
@TheAdventurer64 Looks like `toilets:type=mobile` is an informal tag with only 60 uses. `portable` is much more widely used. If different tagging is determined by the community in the future then we can change the iD preset.

**Comment by maro-21** [comment]
Why was this preset added?? There are **6** features tagged `[amenity=toilets][portable=yes]` on OSM and there is no mention on Wiki about mapping portable toilets. On OpenStreetMap we [don't map](https://wiki.openstreetmap.org/wiki/Good_practice#Don.27t_map_temporary_events_and_temporary_features) temporary and movable objects.

**Comment by quincylvania** [comment]
@maro-21 All features are ultimately temporary—it's up to the mapper to decide if a feature will exist long enough to merit adding. Portable toilets can be stationed for months or years in places like parks or encampments, and I'd argue mapping them as "portapotties" instead of toilets is useful information. The [`portable`](https://taginfo.openstreetmap.org/keys/portable) key has over 1300 uses, so it seemed like a natural fit.

That said, if there's wide disagreement here we can change the tagging or revert this.

**Comment by maro-21** [comment]
> [`portable`](https://taginfo.openstreetmap.org/keys/portable) key has over 1300 uses

Where 1201 of them were used in one city by one user to map portable swimming pools ;)

**Comment by quincylvania** [comment]
I hadn't looked into the distribution, but that doesn't sound unlike OSM 😅
