### ISSUE TITLE
Publish Release 2.18 after Friday

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#7786]
I cannot translate 100+ strings to German before Friday. Can you please publish 2.18 on Saturday (or later) or plan an extra translation update?

**Comment by quincylvania** [comment]
@manfredbrandl Sure thing, there's no need to rush. I've been checking in on Transifex to see how things are coming along. I'm planning to wait until the usual top languages are close to 100% again.

Thanks again for your translation work! Sorry we had to change so many strings at once.

**Comment by maro-21** [comment]
> I'm planning to wait until the usual top languages are close to 100% again.

Please note that for Polish 100% is 125 strings :)
Presets and Core I translate usually within a day. These 125 strings from Community resource are long descriptions of YouthMappers groups from Africa...

**Comment by quincylvania** [comment]
@maro-21 Yeah, presets and core are what I mean primarily 😄

**Comment by manfredbrandl** [comment]
@quincylvania Is there still a preview site where I can test my translations as German is finished now and I seek for quality assurance tools.

**Comment by maro-21** [comment]
manfredbrandl: good job! You can preview translations here: https://ideditor.netlify.com
