### ISSUE TITLE
Set Maxar as default background imagery

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#7787]
Consider setting Maxar as default background imagery.

Bing (current default) is, at least in Argentina, far more outdated than Maxar. 

The problem is that new editors use the default setup and make changes that doesn't reflect reality due to outdated imagery.

Check this location for example: https://www.openstreetmap.org/edit#map=17/-40.14195/-71.29770 (Switch between Maxar and Bing)

**Comment by pnorman** [comment]
It's important to set it to what is best in most locations where mapping is done. Each layer has places where it's best.

I've been meaning to do a worldwide evaluation of bing vs maxar vs esri but haven't gotten around to it, and probably won't soon.

**Comment by quincylvania** [comment]
Unfortunately a single layer isn't likely to be "best" in every location. We should really add a way to specify the default global layer for each region when a preferred local layer isn't available. We could do this pretty easily at the country level since iD already has [local country coding](https://github.com/ideditor/country-coder).

**Comment by AntMadeira** [comment]
This is also an issue in Portugal, where Bing is outdated and highly distorted. All newcomers use Bing because it's iD's default, so it would be great to be able to change it to ESRI, which is the most up to date and with minimum distortion.

**Comment by SK53** [comment]
Also apparently in [China](https://www.openstreetmap.org/user/SK53/diary/399392#comment52789).

**Comment by tyrasd** [comment]
With #9710 the question concerning Maxar imagery is (for now) obsolete, unfortunately. The more general question about more fine grained imagery defaults is discussed at #8956, closing here.
