### ISSUE TITLE
Remember where we last edited

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7790]
It would be great if
- https://preview.ideditor.com/release/
- https://ideditor.netlify.app/

would, via cookie, remember where we were last editing.

That way a second run wouldn't start from map=2.00/0.0/0.0 all over again.

Just like browsing OSM.ORG remembers where we were last time, so should iD.

Yes, iD is usually invoked via the Edit button on OSM.ORG, so this isn't a problem.

However for the two website above, it isn't.

Yes, we can control it via URL, but it would be great if it would remember the last place edited in case we don't want to bother putting the coordinates into the URL.

**Comment by VictorIE-OSM** [comment]
I'm not sure if I am addressing your issue properly.

This page https://www.openstreetmap.org/user/VictorIE/history#map=7/53.448/-7.287 lists all my recent edits. Clicking on the first item will bring me to where I last mapped. You would need to change the end half of the URL to suit your OSM account.

**Comment by jidanni** [comment]
Thanks. But I am just saying if I do
1. https://ideditor.netlify.app/#background=Bing&disable_features=boundaries&map=17/24.18169/120.86617 , and then the next day just:
1. https://ideditor.netlify.app/

I am hoping that the second run should start up within a few kilometers of the first.

**Comment by quincylvania** [comment]
Sounds reasonable that iD would pick up where you left off if the URL didn't specify a new location. I enjoy this functionality for the raster map tiles on osm.org.

**Comment by tyrasd** [comment]
implemented in #9146
