### ISSUE TITLE
Feature Search is empty

### ISSUE THREAD

**Issue by GalenWong** [openstreetmap/iD#7794]
I am new to the iD editor but the feature type search is always empty for me. I have tested in Chrome with all extensions disabled (incognito mode). 

![image](https://user-images.githubusercontent.com/33505320/87651227-593d7880-c785-11ea-8d43-67e6d201835d.png)

There are 34 results but no option is showing up, using version 2.17.3.

**Comment by quincylvania** [comment]
Hi and welcome, @GalenWong. Looks like you're using iD in Tasking Manager, which often restricts the types of features you can add. Making this UI clearer is #7767.
