### ISSUE TITLE
Broken link to ImproveOSM

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7798]
A link to https://improveosm.org/en/ doesn't work. I don't know if it's temporary.

**Comment by quincylvania** [comment]
The link was correct. Their site was temporarily down, but it seems to be working now.

**Comment by maro-21** [comment]
I still can see
```
Forbidden
You don't have permission to access /en/ on this server.
```

**Comment by quincylvania** [comment]
@maro-21 Hmm I see. I swear it was working for me when I typed that 😂

**Comment by maro-21** [comment]
> when I typed that

Oh, you typed but didn't click?
There is another website with "www", https://www.improveosm.org, but I don't know if it's the same.
