### ISSUE TITLE
Can't select the node behind when displaying Osmose layer/icon

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#7799]
Osmose icon seems to be covering whole poi icon so that one can't select the poi to correct. Can select when displaying Keepright layer/icon.
Checked it at https://ideditor.netlify.app/#background=Bing&disable_features=boundaries&map=19.00/35.58539/140.28348 (v2.18.0 preview)
![](https://i.imgur.com/tIccmnw.png)

**Comment by higa4** [comment]
Ah, I found I can select by clicking the blue colored link titled 'にんじん八街店'.

**Comment by quincylvania** [comment]
@higa4 Yep, the features are linked. You can also lasso the node by using shift+click+drag. I'm not sure how else we could do this better right now, so I'm closing this as low-impact.
