### ISSUE TITLE
Parking Type should include Rooftop

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7800]
As you can see in the photo, rooftop is not a type of parking you can add to the map. This needs to be fixed.
[image](https://user-images.githubusercontent.com/50059322/87848858-a00f9900-c87f-11ea-91a2-751703837511.png)

**Comment by maro-21** [comment]
It has been added in #7578.

**Comment by quincylvania** [comment]
Hi and welcome, @TheAdventurer64. This will be in the next release (coming very soon!)
