### ISSUE TITLE
Add a placeholder for grades field

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7802]
I suggest changing current type of this field by removing suggesting values and add a placeholder, where every country can put their own suggested values.
It's because: 
- people tend to copy one of the suggested values instead of typing a proper one
- as we can see from [Taginfo map](https://taginfo.openstreetmap.org/keys/grades#map) it is most commonly used in Norway and Australia, so the suggested values come from there but every country has its own school system.

**Comment by quincylvania** [comment]
@maro-21 What's the problem with the suggested values? The grades field just takes a range of numbers.

**Comment by quincylvania** [comment]
I'm seeing this, which I think is fine for any country even if some countries might not use these ranges.

![Screen Shot 2020-11-06 at 6 15 19 PM](https://user-images.githubusercontent.com/2046746/98423237-0d784d00-205c-11eb-97bf-0059216e6a61.png)
