### ISSUE TITLE
Board Type should include Welcome Sign

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7806]
This issue needs to be fixed ASAP

**Comment by quincylvania** [comment]
@TheAdventurer64 What exactly is the issue here? A screenshot might be useful.

> This issue needs to be fixed ASAP

iD is an open source project with limited resources, so this isn't a helpful thing to say without even providing a reason. Feel free to fix the issue yourself and open a pull request if something's urgent to you.

**Comment by TheAdventurer64** [comment]
#7846
