### ISSUE TITLE
Add leisure=sports_hall

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7818]
A sports hall is a sufficiently large single room, typically enclosed with walls and ceiling, that is suitable to exercise one or more sports indoor. It might contain subordinated locker/changing rooms, showers, and a depot room for devices. It can be a standalone building, or part of a larger building.

A sports hall can often be found on a campus of a school, as part of a school building, or in a sports centre.

In some parts of the world, such sports facilities are called gym or gymnasium, however these values are discouraged in OSM since they have a multitude of different meanings.

Tag with `leisure=sports_hall`. If connected to a building, use `building=sports_hall`.

**Comment by quincylvania** [comment]
Might call this a Gymnasium in iD since the default language is North American English. We can change it for other English locales.

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dsports_hall

**Comment by VictorIE-OSM** [comment]
I think leisure=sports_hall is the best description. It refers to a room and not the contents. Typical use is by teams.

Gymnasium has too much hint of somewhere with tread mills and weights and use by individuals.

In Germany, a gymnasium is a type of school.

**Comment by quincylvania** [comment]
@VictorIE-OSM Yes, the tag would be `leisure=sports_hall`, but a "sports hall" is British English and isn't a term in the US. They're usually called "gymnasiums". https://www.merriam-webster.com/dictionary/gymnasium

**Comment by jleedev** [comment]
More discussion as to the two meanings of "gym" is here: https://wiki.openstreetmap.org/wiki/Gym_/_Fitness_centre

iD uses "Gym / Fitness Center" for `leisure=fitness_centre`, so it would be reasonable to see "Gymnasium" for `leisure=sports_hall` and understand which of the two presets is correct.

**Comment by mohit2872** [comment]
can you assign this issue to me?

**Comment by manfredbrandl** [comment]
@mohit2872 Will you create a PR for this?

**Comment by mohit2872** [comment]
@manfredbrandl yes I will

**Comment by quincylvania** [comment]
@mohit2872 Are you still planning on doing this?

**Comment by mohit2872** [comment]
@quincylvania yeah

**Comment by quincylvania** [comment]
@mohit2872 Thanks for your interest, but it's been over a month so I just handled this. You can look for more issues to attempt [here](https://github.com/openstreetmap/iD/labels/good%20first%20issue).
