### ISSUE TITLE
iD's error message when OSM is busy is incorrect

### ISSUE THREAD

**Issue by tas50** [openstreetmap/iD#7819]
Hey folks,

It looks like iD isn't properly parsing the error message when OSM is busy:

openstreetmap.org right now

```
This website is under heavy load (queue full)
We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.
```

iD error shown in the netlify deploy:

![image](https://user-images.githubusercontent.com/1015200/88081226-f0635100-cb34-11ea-930f-3ce8572f083a.png)

**Comment by quincylvania** [comment]
Thanks, I think this is #7796.

**Comment by tas50** [comment]
Certainly is. Thanks
