### ISSUE TITLE
Panning on selection is 

### ISSUE THREAD

**Issue by polychloriert** [openstreetmap/iD#7820]
It seems to me that an auto-centering feature was added that engages when an object is selected. The map will pan to the center of the object, irrespective of where I selected the object. This makes editing large objects, such as long paths, very cumbersome and annoying as the editor will pan away from the part of the object that I wanted to edit. Thanks.

**Comment by VictorIE-OSM** [comment]
I have also noticed this. Sometimes the object is even off screen, e.g. a length of road that goes around a hill, and the map centres at the focal point of the arc, with no arc visible.

**Comment by quincylvania** [comment]
Welcome, @polychloriert. iD shouldn't be moving the map just because you click on something. Do you have steps to reproduce this behavior? Or a screencapture?

**Comment by polychloriert** [comment]
Thanks for the quick reply. I just checked again and the described behavior is no longer present. Weird. Thanks anyway :)

**Comment by polychloriert** [comment]
Ah, got it again. If I had to speculate, it's probably some kind of state bug during editing.
How to reproduce it:
1. Edit a feature that is considerably larger than the current map pane
2. Let the editor pan the map at least once to focus on the next/current node (happens during repeated node deletion for example)
3. Now, when seleting another feature, the editor will always pan to the feature's center of mass
The behavior can be fixed temporarily by reloading the page. Only until the above steps are repeated, of course.

**Comment by quincylvania** [comment]
@polychloriert Weird!! Definitely a bug. Thanks for reporting and for the detailed steps.

**Comment by polychloriert** [comment]
No, thank YOU for working on iD - it keeps getting better and better :)
