### ISSUE TITLE
Kanton ZH background imagery broken in iD 2.18.2

### ISSUE THREAD

**Issue by brainwad** [openstreetmap/iD#7823]
After getting the update, imagery from the local government in Zürich, Switzerland is broken. Other backgrounds work fine. This is especially problematic because iD defaults to the Kanton ZH Orthofoto Summer 2018 layer.

Repro: https://www.openstreetmap.org/edit#map=11/47.3880/8.4932

**Comment by brainwad** [comment]
Works when setting a custom background with the exact URL in the config, e.g. `https://wms.zh.ch/OGDOrthoZH?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=ortho&FORMAT=image/jpeg&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}`. So the problem isn't the server, it's something iD is doing when reading from imagery.json?

**Comment by quincylvania** [comment]
Looks like the issue arose from iD using the `EPSG:4326` endpoint whereas the custom URL used the `EPSG:3857` endpoint. Not sure if the issue is with iD or with the WMS server, but preferring `EPSG:3857` works fine for now.

**Comment by rbuffat** [comment]
I assume this is related to https://github.com/openstreetmap/iD/issues/7557

**Comment by quincylvania** [comment]
@rbuffat Oh, quite possibly yes.
