### ISSUE TITLE
leisure=track preset checkbox for 'area'

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7825]
It seems a `leisure=track` can be round course (closed way) or can be a straight line e.g. for a 100-metre dash.
Both could be mapped as an area (closed way or relation) or line object.

The wiki https://wiki.openstreetmap.org/wiki/Tag:leisure=track tells to distinguish between a line and area object it should be added the tag `area=yes` for the areas.

I'm not sure if there could be i kind of `leisure=track` preset checkbox for `area`. And the area checkbox could switch between area=yes / area=no / area not tagged.
I found some examples which represents the 4 different cases which i can imaging. Hoping such a checkbox could be implemented, handle the request and help while mapping.  

100-metre dash cases
Example line object:
https://www.openstreetmap.org/way/593987707
Example line object (area=yes):
https://www.openstreetmap.org/way/718067765

Round course cases
Example way object (explicit area=no or area is not tagged):
https://www.openstreetmap.org/way/353940251
Example closed way / area object (area=yes):
https://www.openstreetmap.org/relation/7503730

**Comment by quincylvania** [comment]
Is this #1828? I'm not sure it makes a difference if the track is a closed circuit or not.

**Comment by sun-geo** [comment]
Yes, i think so. Thanks for linking to 1828.

I think it makes a difference. The possibility to add `area=yes` should only enabled for ring objects, like
https://www.openstreetmap.org/way/718067765
See this comment: [""Convert to Area" should really be allowed only on linear rings."](https://github.com/openstreetmap/iD/issues/1828#issuecomment-256251820)
Maybe this (to check and detect these kind of objects) is the complex issue which is hard to implement & the reason why the old ticket is open.

**Comment by quincylvania** [comment]
@sun-geo Okay great. It isn't complex to detect which lines are closed and can be converted to areas, but adding a new UI element to a usability-focused app like iD is always tricky.

**Comment by sun-geo** [comment]
I see! It's regarding the UI handling.

Before writing the initial post for 7825 I had in mind the UI could just look like a preset checkbox. But i missed to add a picture.
A similar case see `leisure=track` like the tagging of `lit` information box (lit=yes / lit=no / without lit tag), as mentioned above which could used for `area`, but only enabled for ring elements, otherwise greyed-out, see
![image](https://user-images.githubusercontent.com/47290585/88240087-704d0080-cc86-11ea-8edf-5dae2eb535ff.png)
