### ISSUE TITLE
Line presented with Point label

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/iD#7827]
I discovered a bug in the Line preset. Steps to reproduce:
- Create a line
- Edit a point
- Select the line again and you'll see the line labelled as "Point"

I recorded a video that shows how I found it https://drive.google.com/file/d/1ldsud0BTqQSjE8m7WIdJOGD9h_i0IKA9/view?usp=sharing

**Comment by quincylvania** [comment]
@willemarcel Thanks for reporting 👍
