### ISSUE TITLE
Rearrange Blocks in "Editing" within Shortcuts to save screen space

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#7830]
![image](https://user-images.githubusercontent.com/5360273/88188737-8a5ff200-cc38-11ea-95f1-2ecd4b078dea.png)

**Comment by quincylvania** [comment]
Hmm it already works like this in English, but I agree we should make it work better for languages with longer labels.

<img width="1008" alt="Screen Shot 2020-07-22 at 10 47 50 AM" src="https://user-images.githubusercontent.com/2046746/88190895-d3984d80-cc08-11ea-984d-11ea6943d1b5.png">

**Comment by bhousel** [comment]
I'm pretty sure this screen just lets flexbox handle the layout.  Translators need to just use shorter labels.

**Comment by manfredbrandl** [comment]
The left tab (Browsing = Ansicht) works also in German:
![image](https://user-images.githubusercontent.com/5360273/88195389-47098180-cc40-11ea-85b4-1a87eec6aca2.png)

The problem is with the middle tab (Editing = Bearbeitung).

**Comment by manfredbrandl** [comment]
@bhousel Using shorter labels did the job.
