### ISSUE TITLE
validator / spell checker: customers vs. customer

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7831]
Based from this view:
![image](https://user-images.githubusercontent.com/47290585/88215333-c5275180-cc5b-11ea-9800-2a163b862d49.png)

i wonder if this could be make sense for a validator rule.

According to the wiki `access`:
https://wiki.openstreetmap.org/wiki/Key:access#List_of_possible_values
the osm value is `customers`

PS, See also taginfo overviews:
https://taginfo.openstreetmap.org/search?q=customers#values
vs
https://taginfo.openstreetmap.org/search?q=customer#values

**Comment by quincylvania** [comment]
Sure, we can deprecate `access=customer` in [deprecated.json](https://github.com/openstreetmap/iD/blob/develop/data/deprecated.json).

**Comment by sun-geo** [comment]
:-)

**Comment by sun-geo** [comment]
Tried to bring the second edit (regarding the modification of the taginfo.json file) in the same #7836 pull request.
 
Seems i accidentally created meanwhile a branch "patch-2". How can i delete such a apparently now unnessecary branch? 

Now i modified the taginfo.json file a second time (in branch patch-1) and hopefully the edit is moved automatically to the same pull & it is okay now.

**Comment by quincylvania** [comment]
> Seems i accidentally created meanwhile a branch "patch-2". How can i delete such a apparently now unnessecary branch?

@sun-geo [This article](https://www.freecodecamp.org/news/how-to-delete-a-git-branch-both-locally-and-remotely/) should help.

**Comment by sun-geo** [comment]
Thanks for merging.



> @sun-geo [This article](https://www.freecodecamp.org/news/how-to-delete-a-git-branch-both-locally-and-remotely/) should help.

@quincylvania Seems the article describes how to delete via cmd commands.
I wonder if i could also do this via the webpage.

For the current pull quest (add area field for leisure=track), i did again 2 mistakes by creating unwanted branches patch-4 & patch-5.
I can see this screen:
![image](https://user-images.githubusercontent.com/47290585/88594704-f8098500-d061-11ea-8d19-518a66bac0e7.png)
