### ISSUE TITLE
Small correction in Help > Background Imagery

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7840]
In iD's Help > Background Imagery you can read:
`By default, a [Bing Maps](https://www.bing.com/maps/) satellite layer is chosen as the background image.`
which is not true...

**Comment by manfredbrandl** [comment]
@maro-21 Do you know what the default is?

**Comment by maro-21** [comment]
I think it's different for every country.

**Comment by quincylvania** [comment]
The global default is Bing but certain regions have a designated "best" layer that's used instead.

**Comment by maro-21** [comment]
Should I change the translation then?

**Comment by manfredbrandl** [comment]
@maro-21 you should change the original english text first, can you prepare a PR?

**Comment by maro-21** [comment]
I don't know if they want to keep this line there. I run iD in a random place in England and I can see that Bing isn't default imagery there and there isn't any other default layer.

**Comment by manfredbrandl** [comment]
You are running iD in England and want to change this sentence in which language?

**Comment by maro-21** [comment]
I looked there to check if Bing is really a default imagery. There wasn't any default imageries there so the sentence "By default, a Bing Maps satellite layer is chosen as the background image." isn't true.
