### ISSUE TITLE
Add text ‚note‘ behind note-icon.

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#7841]
In the toolbar there are texts Point, line and area behind their icons. There should be the text note behind the icon. Currently it isn‘t. In Help it is described like that. German Screenshot from iPad:
![ACD7984E-BAB6-40F5-9325-427FBDCF7C9E](https://user-images.githubusercontent.com/5360273/88448322-ec894480-ce3c-11ea-8053-afc4531ffa20.jpeg)

**Comment by quincylvania** [comment]
@manfredbrandl Thanks, the help label should have matched the toolbar button label. I don't think we need two labels for this toolbar item.
