### ISSUE TITLE
Add Welcome Sign preset

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7846]
Description: A sign welcoming users to a place/city, without further (detailed) information about the place.

Tag with `information=board`, `tourism=information`, and `board_type=welcome_sign`.

**Comment by mikenath223** [comment]
Hey, I'll love to contribute to this. Could someone please provide me a bit more context on what this involves?

Best regards,
Michgolden Ukeje

**Comment by TheAdventurer64** [comment]
@quincylvania

**Comment by quincylvania** [comment]
@mikenath223 Thanks for your interest! Check out our [contributing guide](https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md) and the [presets readme](https://github.com/openstreetmap/iD/blob/develop/data/presets/README.md) for info on how to add this. See #7912 for a similar example.

@TheAdventurer64 I get notified about everything that's posted in this repo, so there's no need to ping me. I can't respond to everything immediately.

**Comment by mikenath223** [comment]
Fixing issue #7846

**Comment by mikenath223** [comment]
Hi, @quincylvania please kindly check this

**Comment by quincylvania** [comment]
I noticed that [`information=board`](https://wiki.openstreetmap.org/wiki/Tag:information%3Dboard) tends to be used for detailed information displays, not signage. `board_type=welcome_sign` looks like the primary outlier here. Since this is the accepted tagging I'm okay supporting it in iD, but I'd still recommend looking into a tagging change.

**Comment by mikenath223** [comment]
Alright. I made a few changes just now as requested. I added `information=board` to the tags. Do I remove it?

**Comment by quincylvania** [comment]
> Alright. I made a few changes just now as requested. I added information=board to the tags. Do I remove it?

Nope, it's okay. We're supporting the tags as they are, not how I want them to be 😂
