### ISSUE TITLE
Moving a node is not possible after long left mouse click (& holding left mouse button)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7849]
See title, because it will be shown the same context menu as it happened when right clicking.
I assume this function comes with the new iD version (v2.18), which provides the touch-pad functionality.
But in this case (when using a a mouse) for moving existing nodes the handling isn't comfortable anymore, because you have to be very fast to start the move-action (after left mouse clicking).

**Comment by AntMadeira** [comment]
Yes, I second this. It's not helpful and it disturbs when editing the map.

**Comment by quincylvania** [comment]
@sun-geo Thanks, this is a bug we're tracking in #7826.
