### ISSUE TITLE
Viewpoint and hunting stand have the same icons in ID

### ISSUE THREAD

**Issue by NotSoImportant** [openstreetmap/iD#7851]
Currently in the editor you cannot distinguish between both (without selecting them).

However their purpose is very different:
- One is for orientation and only allows access for hunters
- The other is a point of touristic interest, but has itself no specific structure to be recognized

Please introduce a different icon for one or the other.

**Comment by maro-21** [comment]
... and shop=hunting as well.

For a viewpoint it would be good to have a similar icon as in OSM Carto:
https://wiki.openstreetmap.org/w/images/thumb/c/c2/Viewpoint-16.svg/240px-Viewpoint-16.svg.png

**Comment by quincylvania** [comment]
Welcome, @NotSoImportant. iD is often forced to reuse icons since there are a huge number of presets and only so many suitable icons. However, with #7068 we've lately been on a quest to find or draw as many unique icons as possible, so we should be able to address this.

**Comment by NotSoImportant** [comment]
Thanks @quincylvania 
I understand the effort of maintaining a lot of presets. And I think it is even ok to have the same icon for similar things. 

Just wondering as
_amenity=hunting_stand_
has no overlap with
_tourism=viewpoint_

Looking forward to see it fixed :-)
