### ISSUE TITLE
Allow adding to relation with multiselection

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7853]
In the recent iD update I was very happy to see a better feature multiselection, which allows us to change fields of several features at the same time. Thanks for that.
Unfortunately, there's no option to add selected features to a relation. This would be very useful and I don't see major problems allowing this to be done.
Is there a reason for not allowing relations in multiselection, or is it a technical issue?

Regards.

**Comment by manfredbrandl** [comment]
Each member of a relation can have a (different) role in the relation, the members are also ordered, sometimes the order depends on the time a member is added to a relatio. Some relation types (e.g. restriction) require roles for their members. Adding several members to a relation can break the relation. Anyway I am NOT opposed to add several members to a relation, it just has to be done right.

**Comment by quincylvania** [comment]
@AntMadeira This is definitely something I'd like to try. #7753 is about enabling the Relations section for multiselections, so let's focus discussion over there.
