### ISSUE TITLE
Add "Snorkel Shop" as a search term for "Scuba Shop"

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7857]
Since a snorkeling shop and a scuba shop are the same thing, I propose we allow the user to search for "snorkel shop" to pull up the Scuba Shop preset.

**Comment by fakeharahman** [comment]
I am new to open source and I would like to take up this issue.

**Comment by quincylvania** [comment]
@fakeharahman Great! Please review our [contributing guidelines](https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md) and the [presets readme](https://github.com/openstreetmap/iD/blob/develop/data/presets/README.md) for how to do this. You'll want to look at the `terms` property of the relevant preset file.

**Comment by fakeharahman** [comment]
I've submitted a pull request #7874 fixing the issue. Can you please review? 
Thank you

**Comment by fakeharahman** [comment]
It says test failed at the pull request but the test passes on my computer. Please advice.

**Comment by SinghalSaksham** [comment]
Hello, I am new to open source and want to work on this issue. Can you please guide me through

**Comment by quincylvania** [comment]
This was done in #7874 by @fakeharahman!

@SinghalSaksham There are a few [similar issues](https://github.com/openstreetmap/iD/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) you can work on.
