### ISSUE TITLE
Some streets not rendering

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#7858]
In this area https://www.openstreetmap.org/edit#map=17/62.77698/27.50262 some of the roads do not render (latest FF) for no apparent reason (editing in other editors seems just fine).

Reported here: https://forum.openstreetmap.org/viewtopic.php?pid=796045#p796045

**Comment by st-anton** [comment]
This appears on other places in the world as well. Sometimes the points of the roads and polygons are rendered, sometimes nothing at all. Curious: Some roads from the outside of the actual area are rendered. Changing the zoom level jumps around and does not effectively change the zoom, in the end the background image is shifted.
The iD editor cannot be used currently.

**Comment by tastrax** [comment]
even more strange - click on the nodes that are showing and things appear?

![strange](https://user-images.githubusercontent.com/8775395/88886673-57dc7780-d27e-11ea-8bb7-f98cc044621b.JPG)

**Comment by st-anton** [comment]
Obviously some areas in the world are affected, other not.

**Comment by simonpoole** [comment]
> 
> 
> Obviously some areas in the world are affected, other not.

While just idle (not quite) speculation it seems to be triggered by a specific data situation that causes rendering to abort at that point, the console output does report an error, but best leave tracking that down to the devs.

**Comment by quincylvania** [comment]
@simonpoole Thanks for reporting. I'm seeing console errors like `e.uid is undefined` and `entity n231109719 not found`, which are usually pretty serious errors which will exit the rendering code and leave an incomplete map. I'll work on debugging further.

**Comment by st-anton** [comment]
Some more examples:
[https://www.openstreetmap.org/edit#map=15/51.2277/13.6119](https://www.openstreetmap.org/edit#map=15/51.2277/13.6119)
[https://www.openstreetmap.org/edit#map=19/51.16365/13.56454](https://www.openstreetmap.org/edit#map=19/51.16365/13.56454)

**Comment by quincylvania** [comment]
Looks like this was happening since iD wasn't accounting for the possibility of undefined `uid` on entities returned by the JSON endpoints of the OSM API. Simple fix for a nasty bug.

**Comment by simonpoole** [comment]
Ah revenge of the anonymous users :-)

**Comment by SK53** [comment]
Looks like I encountered this editing in Devon a day or so ago. I made a screen grab but hadn't followed it up as I moved to using other editors.  I guess the S Devon coastal areas were mapped fairly early on. Glad there's an explanation.

![Screenshot (3)](https://user-images.githubusercontent.com/5452818/88977614-27b0cb00-d2b6-11ea-8554-46f4019b372c.png)

**Comment by mmd-osm** [comment]
Argh, too bad I missed this, I should’ve known better. 🙄

**Comment by tomhughes** [comment]
Are we going to get a new build with this at some point? I held off rolling back yesterday assuming we would get a quick fix but if that's not going to happen I probably will need to roll back to a working version.

**Comment by mmd-osm** [comment]
By the way, both uid and user fields would be absent for anonymous users. Would you need an empty string as fallback for „user“ as well?

Version would never be missing otherwise you couldn’t upload any changes for this object.

**Comment by quincylvania** [comment]
I'll release a patch today.

**Comment by mmd-osm** [comment]
@quincylvania : did you read my last post? You didn’t change the user bit before releasing the new version. Just wanted to be sure there’s no further issue here.

**Comment by quincylvania** [comment]
> did you read my last post? You didn’t change the user bit before releasing the new version.

@mmd-osm Yes, sorry. It should be fine for `user` to be undefined rather than an empty string since the XML parser worked the same way. For instance, iD properly displays an "Unknown" label in the UI for features last edited by anonymous users.

![Screen Shot 2020-07-31 at 10 45 28 AM](https://user-images.githubusercontent.com/2046746/89046561-22399c00-d31b-11ea-83f4-a5b3e7dc2424.png)
