### ISSUE TITLE
When you extract a point from a building part, the building part tags come with the point

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7862]
![image](https://user-images.githubusercontent.com/50059322/88855639-e376db00-d18e-11ea-8a9b-0cfbcc8d7d27.png)

**Comment by manfredbrandl** [comment]
This behavior generally meets my expectations. @TheAdventurer64 What are your expectations?

**Comment by maro-21** [comment]
What meets you expectations? Tags `building:levels` and `roof:material` are building tags and should never be on a node.

**Comment by manfredbrandl** [comment]
I generally expect the point extracted from a way (line or area) to have the same tags as the way. With the command merge these tags can then be transferred to another way. @maro-21 Your expectation appears to be that tags that are not allowed on a node should be removed by the extract command. Correct?

**Comment by quincylvania** [comment]
@manfredbrandl The intention has been for the Extract operation to easily separate out a POI from an area in one click. It already leaves behind building tags if the area has `building=*`, so I think it should also do this for `building:part=*`. Mappers can use the raw text tag editor to copy and paste all the tags between features.

**Comment by manfredbrandl** [comment]
@quincylvania Good to know, will use that for the section „edit menu“ in the help.

**Comment by TheAdventurer64** [comment]
Any progress?

**Comment by quincylvania** [comment]
@TheAdventurer64 Any progress will be posted here. Changes may take awhile since iD doesn't have any paid or full-time developers right now.

**Comment by maro-21** [comment]
Oh, what happened? Quincy will you come back?

**Comment by quincylvania** [comment]
@maro-21 I'd love to come back to full-time and will probably be able to soon! There's a [change in the support model ](https://lists.openstreetmap.org/pipermail/osmf-talk/2020-August/006997.html)underway.

**Comment by maro-21** [comment]
> I'd love to come back to full-time and will probably be able to soon!

Oh, that's good because I still have about 50 unreported issues for iD :-)
