### ISSUE TITLE
Increasing of direction step size

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7867]
The current step size for changing the `direction` value is 1, see:

![dir-step-size](https://user-images.githubusercontent.com/47290585/89094730-77cb8280-d3c7-11ea-9afd-0572984b7835.gif)

I propose to increase the step size a bit, maybe to (2 or) 5 (or 10)?

Who even still what's to use a more detailed figure below a raster of 5 would still have an option to manually enter a more detailed value in the left box directly.

**Comment by quincylvania** [comment]
The increment is probably something we could encode in the field data files. Some field like electricity output or water tank volume are measured in the thousands so an increment of one is a bit trite.

**Comment by pnorman** [comment]
> Some field like electricity output or water tank volume are measured in the thousands so an increment of one is a bit trite.

Agreed. Voltage might need different increments in different ranges. Sometimes it's a multiple of 10, sometimes 100, and sometimes 1000.
