### ISSUE TITLE
Raw tag editor - no horizontal scroll bar

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7869]
No possibility to copy a long link in raw tags editor if it's too long - there is no horizontal scroll bar (but it used to be in the previous versions).

**Comment by thibaultmol** [comment]
Just to note: there is a horizontal scrollbar on the raw tag editor of the V3 Preview: [https://preview.ideditor.com/master/](https://preview.ideditor.com/master/)

**Comment by maro-21** [comment]
But I mean normal, current version.

**Comment by quincylvania** [comment]
@maro-21 Thanks for reporting, this was definitely a regression.
