### ISSUE TITLE
Remove unsuitable imagery sources

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#7871]
We've found a number of imagery sources in ELI that are not suitably licensed. Background: this is imagery owned and produced by the Swiss federal GIS office, that was mistakenly offered by two cantonal GIS offices on their open data WMS servers (with other words an unintentional mess). 

ELI has been updated, so a rebuild and redeploy of iD will remove the sources.

**Comment by nitram9** [comment]
@simonpoole, is it possible that now, following the Open Government Data announcement (https://shop.swisstopo.admin.ch/en/products/free_geodata) of March 2021, that the previously not suitably licensed sources are now free to be used once again? It would be excellent for mapping purposes to once again use Switzerland's base map.

**Comment by simonpoole** [comment]
@nitramwin see https://sosm.ch/use-of-swisstopo-data-and-products-with-and-in-openstreetmap/ this has been widely reported and mentioned (twitter, OSM weekly, etc etc). And the (acceptable) sources have long been added to ELI and JOSM.

**Comment by nitram9** [comment]
Thank you for the comment. I am waiting now on the inclusion via iD. Wish
you a nice day.
