### ISSUE TITLE
https://preview.ideditor.com/master/ not yet /develop/

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/iD#7872]
I noticed that url hasn't changed yet from master to develop (btw, if possible. Make it so that preview.ideditor.com/master/ does redirect to /develop so that people's bookmarks and previous mentions of that link still work)

**Comment by quincylvania** [comment]
So the v3 prototype branch at https://preview.ideditor.com/master is a significantly different app than the current `develop` branch at this point. We're not updating it anymore. Though a handful of people are still using it, so I think it's best to leave it for now.

You can preview the current `develop` branch at https://ideditor.netlify.app/.
