### ISSUE TITLE
Include imagery attribution in imagery_used tag of changesets

### ISSUE THREAD

**Issue by rbuffat** [openstreetmap/iD#7876]
If I'm not mistaken, currently, only the ["properties"]["name"] value of imagery sources is written in the imagery_used tag of changesets. ["properties"]["attribution"]["text"] is displayed when the map is shown, but I was wondering if it would not also be a good idea to use ["properties"]["attribution"]["text"] in combination with "name" instead. For my personal taste, this would give a better attribution to the origins of the imagery that is used.

I don't know about the technical aspects behind it and what is commonly used by other editors. https://github.com/openstreetmap/iD/issues/2181 mentions a 255 length limit, but I don't know if this is still valid.

**Comment by Nakaner** [comment]
The 256 character (not bytes) limit still exists in the OSM API.

**Comment by quincylvania** [comment]
Hi and welcome, @rbuffat.

There is a character limit, so we can't put too much in this tag. The attribution might be more human-readable, but I'm afraid it'd be noise for tools trying to process this tag if we included both. You can cross-reference the name with [entries in the editor-layer-index](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources) to find the attribution text or any other metadata. We're actually having a discussion over in #7842 about (intentionally) using the layer ID instead of the name to make this easier.

**Comment by rbuffat** [comment]
@quincylvania Thanks for your insights! I see this limit makes it difficult. I agree in most cases it is possible to cross-reference with ELI, but as names can change at any time, there is no guarantee that this will be easy or even a unique match can be found. 

Personally, I think a good attribution of the used sources is important. Some kind of a [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) system where a unique id would reference a dataset even if it is modified in or deleted from the index could be a solution.

**Comment by quincylvania** [comment]
I agree using a unique ID would be better than a name. ELI has these and with #7842 we'll probably switch to them. The nice thing with Github is that you can always go back to see what the identifier used to refer to even if it's been changed or deleted.

**Comment by rbuffat** [comment]
That's true, as long as github exists, respectively git is used for the index.

**Comment by matkoniecz** [comment]
It appears to be discussed and rejected in  #6300

Also the same request was rejected in JOSM: https://josm.openstreetmap.de/ticket/19911

**Comment by quincylvania** [comment]
@matkoniecz This is about the `imagery_used` tag, while #6300 is about the `source` tag. They're related, but different.

**Comment by rbuffat** [comment]
@quincylvania @matkoniecz 

It's not the same, but I think it is still appropriate to leave the issue closed / wont-fix.

I still believe that for better attribution of the used data a DOI like system that would allow to easily see the data's origin, license, homepage etc. (which are sometimes required) would be something good. But this would involve modifying the OSM homepage and would require "a central" imagery repository. Thus, it is outside of the scope of iD.

**Comment by tordans** [comment]
@rbuffat this tool is great! What is the best place to discuss it (questions, suggestions). It would be off topic for this thread.

**Comment by tordans** [comment]
(Sorry @rbuffat wrong thread :-D. Deleted the message and will delete this one as well.)
