### ISSUE TITLE
Add telephone and website to standard preset

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7877]
So, I'd like a feature that adds the telephone and website fields to the standard preset, rather than having to go to `Add `Field` to insert them.

**Comment by maro-21** [comment]
Which preset do you mean?
It depends on a preset, sometimes you have these fields visible, sometimes they're hidden.

**Comment by DujaOSM** [comment]
Almost any type of business should have those fields enabled. Accommodation and restaurants in particular.

**Comment by quincylvania** [comment]
Yes, could you be specific about which presets you mean, @TheAdventurer64? I agree that website is now a more important tag than ever considering many people are staying home and only visiting businesses online.

**Comment by TheAdventurer64** [comment]
Since all places usually have a phone number or website, I think the two fields should be on most `shop=*` and `amenity=*`tags.

**Comment by quincylvania** [comment]
See also #7865

**Comment by maro-21** [comment]
I think we shouldn't have phone and website automatically for every shop preset.

I can't imagine to have a phone for shops like
convenience
supermarket
clothes
bakery
kiosk
butcher
alcohol


These are one of the most popular shops and they're usually in a chain of shops, selling everyday goods.
Even if there are some that have, most of them don't have and people will try to fill in every field in the editor.

**Comment by quincylvania** [comment]
@maro-21 I think these details are fair game for any type of business given the COVID pandemic. While it's true some shops are more likely than others to have a website or phone number, consistency is also good. If we do #5734 then maybe we can pare down the default fields again, since mappers would be able to customize them.

**Comment by TheAdventurer64** [comment]
^ Also, this sort of info will be helpful to people resolving onosm notes, as it can be a hassle to go down to Add Field to get the fields for Telephone and Website. Also, this standardizes iD with other business editors, as most of them have the `website` and `phone ` fields shown by default. 
![image](https://user-images.githubusercontent.com/50059322/93839133-a62b4880-fc27-11ea-9a36-f740427839b6.png)
![image](https://user-images.githubusercontent.com/50059322/93839132-a592b200-fc27-11ea-8bee-274d9fd89206.png)
![image](https://user-images.githubusercontent.com/50059322/93839270-23ef5400-fc28-11ea-8f8a-45d3b23eba69.png)

**Comment by forteller** [comment]
Hi. I see that this issue is closed, but I came here to open a similar issue, because the website field is not actually shown be default when I add a business. It would be very helpful if it did!

Thanks!

**Comment by maro-21** [comment]
How are you adding a business? Which preset do you mean?

**Comment by forteller** [comment]
I add a node and select an option from the sidebar (after searching), are there any other ways?

I tried more presets now, and see that some of them do have website by default, but lots does not, like:

shop=camera
shop=supermarket
shop=bicycle
amenity=bicycle_rental
shop=mall
shop=yes
shop=books
shop=anime
leisure=sports_centre
amenity=bar
amenity=ice_cream
amenity=library

etc

**Comment by k-yle** [comment]
I would suggest opening a new issue in https://github.com/openstreetmap/id-tagging-schema, we could reopen this issue, but this discussion belongs in the other repository anyway

**Comment by forteller** [comment]
Thank you, I opened this: https://github.com/openstreetmap/id-tagging-schema/issues/1413
