### ISSUE TITLE
New preset: shop=wigs

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7878]
A shop selling wigs.
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dwigs

**Comment by fakeharahman** [comment]
Hey, can I try solving this issue?

**Comment by quincylvania** [comment]
@fakeharahman Yes! Take a look at our [contributing guidelines](https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md) and the [presets readme](https://github.com/openstreetmap/iD/tree/develop/data/presets).

**Comment by quincylvania** [comment]
@fakeharahman Oops, I forgot I already linked you to those in #7857 haha

**Comment by fakeharahman** [comment]
I'm on it!

**Comment by quincylvania** [comment]
Done in #7912 by @fakeharahman
