### ISSUE TITLE
Deprecate bench+capacity in favor of bench+seats

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#7886]
There are quite a few `amenity=bench + capacity=<int>` out there.
- About 6k https://taginfo.openstreetmap.org/tags/amenity=bench#combinations
- Query https://overpass-turbo.eu/s/WR3

But the wiki says, that it should be `amenity=bench + seats=<int>` instead.
- https://wiki.openstreetmap.org/wiki/Key:seats
  > Do not use capacity=* in this context
- https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench
  > seats=* Number of seats
- And it is used a lot more: 200k+ https://taginfo.openstreetmap.org/tags/amenity=bench#combinations

There was a proposal about this, which was rejected, but the seats key has won "de facto" regardless based on Wiki + Numbers.
- https://wiki.openstreetmap.org/wiki/Proposed_features/Attributes#seats.3D.2A

**Suggested change:**

Deprecate the capacity value on amenity=bench to be updated via the validator to seats.

In case both exist, remove the capacity and keep the seats.

**Comment by fakeharahman** [comment]
Can I please give this a shot?

**Comment by tordans** [comment]
> Can I please give this a shot?

AFAIK the actual doing is more or less one line of code. It's more a question of decision - if the change is wanted. 

Update: but since @quincylvania added the good-first-issue-label I guess the PR would be welcome.

**Comment by fakeharahman** [comment]
Thank you @tordans! Could me please guide me on where to go?

**Comment by quincylvania** [comment]
@tordans I try to defer to what people ask for unless I see a reason not to. In this case one tag has overwhelmingly more usage and community support, so it sounds fine to me.

@fakeharahman Tag deprecations like this are usually encoded in the [data/deprecated.json](https://github.com/openstreetmap/iD/blob/develop/data/deprecated.json) file.

**Comment by mikenath223** [comment]
Perhaps it's ok I work on this?
