### ISSUE TITLE
Adding a preset field "parking=*" (amenity=parking_entrance)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7900]
Adding a preset / field of `parking=*` (for main tag `amenity=parking_entrance`), see wiki:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_entrance#Additional_tags

**Comment by nafees87n** [comment]
@sun-geo @quincylvania I want to do this. What I understood is that I'll have to add the `parking.json` field to the fields key array in `data/presets/presets/amenity/parking_entrance.json` . 
I am new to open source. I need help to understand the work to be done for this issue.

**Comment by quincylvania** [comment]
Done in #7909 by @brokemyspoke.
