### ISSUE TITLE
Use tram crossing tags when connecting trams and roads/paths

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7902]
_Broken out from https://github.com/openstreetmap/iD/issues/5990#issuecomment-674419342._

Tram tracks are rather different from other train tracks. There are separate crossing tags to indicate this: [`railway=tram_level_crossing`](https://wiki.openstreetmap.org/wiki/Tag%3Arailway%3Dtram_level_crossing) and [`railway=tram_crossing`](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dtram_crossing). iD should have presets for these and account for them in the validator.

**Comment by maraf24** [comment]
So status=proposed doesn't actually mean anything?

**Comment by quincylvania** [comment]
@maraf24 I'm not sure what you're referring to. The [`status=proposed`](https://taginfo.openstreetmap.org/tags/status=proposed) tag has only two uses and isn't supported by iD.
