### ISSUE TITLE
Add juice bar preset

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7904]
A juice bar is a place where people can order drinks, usually made with fresh fruit. Sometimes, they offer health food products, such as acai and breakfast bowls. At some places, they also offer indoor seating as well.

Tag with `amenity=fast_food` and `cuisine=juice`

**Comment by quincylvania** [comment]
This sounds a little funky, but I think the preset name should be something more like "Juice Fast Food". This better indicates the type of establishment, since `cuisine=juice` could also be used on cafés, bars, restaurants, etc. We already do this with presets like "Pizza Fast Food" to avoid confusion with pizza restaurants or stores.

**Comment by TheAdventurer64** [comment]
Ah, alright. Thanks for the feedback!

**Comment by maro-21** [comment]
For such places I use `amenity=cafe` + `cuisine=juice`.

**Comment by maro-21** [comment]
Could you tell me what is Juice Fast Food? Any photos, description, link to Wiki etc.
Because I don't know what it actually is so I don't know how I should translate it.
Why is it amenity=fast_food and not amenity=cafe? And why does it deserve a separate preset?

**Comment by TheAdventurer64** [comment]
> Could you tell me what is Juice Fast Food? Any photos, description, link to Wiki etc.
> 
> Because I don't know what it actually is so I don't know how I should translate it.
> 
> Why is it amenity=fast_food and not amenity=cafe? And why does it deserve a separate preset?

Well, I'm planning on adding a wiki page for this. The reason behind using `amenity=fast_food` instead of `amenity=cafe` is because juice bars are tagged with `amenity=fast_food`, as described [here](https://wiki.openstreetmap.org/wiki/Proposed_features/Juice_bar)

**Comment by quincylvania** [comment]
@maro-21 The preset supports [brands from the name-suggestion-index](https://github.com/osmlab/name-suggestion-index/blob/main/brands/amenity/fast_food.json), which use this tagging.

![Screen Shot 2020-09-17 at 8 07 25 PM](https://user-images.githubusercontent.com/2046746/93540541-f81b5800-f921-11ea-9112-3fe084adf1ed.png)

Not all juice bars should necessarily be tagged this way, but there are many that look [essentially like a McDonald's](https://lh3.googleusercontent.com/-dy4ioZZvcTI/VjLCSElpqJI/AAAAAAAAe0U/3hwlIHiHQik/s640/blogger-image--675881356.jpg) for juice beverages. If the tagging changes then we can change the preset.

**Comment by TheAdventurer64** [comment]
https://wiki.openstreetmap.org/wiki/Juice

**Comment by maro-21** [comment]
https://wiki.openstreetmap.org/wiki/Proposed_features/Takeaway_drink_shops
