### ISSUE TITLE
Vineyards & Wineries

### ISSUE THREAD

**Issue by SK53** [openstreetmap/iD#7907]
Currently iD expects to set both craft=winery with landuse=vineyard. I don't think this is appropriate, at least in Europe, for a range of reasons:

- many vineyards are not associated with wineries (particularly small scale vineyards in Europe which may sell their grapes to a co-operative winery. Furthermore the actual production of wine often occurs away from the vineyards. For instance the village of Kolimbari on Crete has a communal winery and each farmer brings their crop, usually heaped high on a trailer behind a tractor - large queues form.
- in some areas (notably Bourgogne) each individual vineyard (which may be impossible to discern as distinct from aerial imagery) has a distinct name (see Climats de Bourgogne), and many vineyards will be associated with the producer.
- larger wineries often represent tourism destinations in their own right with associated infrastructure of car parks, warehousing & logistics.
- vineyards associated with a winery may be highly dispersed, or inter-digitated amongst vineyards of other producers.
- vineyards are easy to locate on aerial imagery, the production facilities less so.

I would therefore suggest that the validation rules calling landuse=vineyard without craft=winery as "incomplete tagging" be dropped.

**Comment by quincylvania** [comment]
@SK53 Where are you seeing this? iD should only recommend `crop=grape` on `landuse=vineyard`. Wineries are separate.

**Comment by quincylvania** [comment]
Lacking further info, I'm closing this as unreproducible.
