### ISSUE TITLE
Unable to copy text in panels

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#7908]
As of v2.18.4, when I select some text in a panel, such as the coordinates in the Measurement panel, then hit command-V, iD copies the selected feature instead of the selected text, so nothing is added to the pasteboard. To copy coordinates, I have to select the text, right-click, and choose Copy from the context menu. The command-V keyboard shortcut previously worked for selected text.

Reproduces in both Firefox 79 and Safari 13 on macOS 10.13.

**Comment by quincylvania** [comment]
@1ec5 Thanks for reporting. This was due to under-the-hood changes for #2508.
