### ISSUE TITLE
Popover not positioned correctly in Walkthrough

### ISSUE THREAD

**Issue by aa-deet-eeya** [openstreetmap/iD#7913]
While going through the walkthrough on the Navigation tab the popover is positioned half out of the screen (see the attached image).

**Steps to reproduce:**
1. Go to http://www.openstreetmap.org/edit?editor=id and sign in
2. Select walkthrough 
3. Select the Navigation from the bottom tab

**My config:**
- Ubuntu 18.04.5 LTS
- Mozilla Firefox 79.0

![OpenStreetMap_issue](https://user-images.githubusercontent.com/26107248/90474850-db81d980-e143-11ea-816c-ba13df1ddd7d.png)

**Comment by maro-21** [comment]
Duplicate of #7807.

**Comment by aa-deet-eeya** [comment]
Sorry for the duplicate, I'll close this one @maro-21
