### ISSUE TITLE
New preset: Emergency Water Tank

### ISSUE THREAD

**Issue by tastrax** [openstreetmap/iD#7915]
https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dwater_tank

In Australia emergency water supplies are now mandated in some areas of high fire risk. It would be useful to have a preset for both nodes and ways to quickly add these to the map. It would also be good to have the volume of the tank (litres) as a standard field. I am also seeking to get these rendered on the standard OSM map to assist local fire fighting resources.

**Comment by quincylvania** [comment]
Looks like iD already has a point preset for this, but we could improve it and support areas as well.

**Comment by tastrax** [comment]
Suggestions for extra tags

capacity=xx
content=water
drinking_water=no
emergency=water_tank
height=xx
man_made=storage_tank
material=xx
operator=xx
ref=xx

**Comment by quincylvania** [comment]
@tastrax Despite the name, it looks like this tag can also be used on `man_made=reservoir_covered`, so we can't assume `man_made=storage_tank`.

**Comment by tastrax** [comment]
No worries - I would be happy with all the other tags and having to manually add the man_made=storage_tank
