### ISSUE TITLE
Show "diet" field by default

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7918]
Hi again :) 

Whether or not a place to eat offers vegetarian, vegan or other dietary foods is one of the most important pieces of information about a place to eat for a lot of people. But since this field is hidden in iD by default, the majority, who don't mostly care about this, is more likely to not add this information, even if they know or very easily can find out.

I would very much appreciate it if you could make this visible by default.

Thank you again for all your great work!

**Comment by quincylvania** [comment]
Hi @forteller. I agree this info is at least as important as `cuisine`, so I'm okay making it more visible. This will also help mappers avoid common mistakes like `cuisine=vegan`.

**Comment by forteller** [comment]
Could you please add this to amenity:fast_food too? Thanks! :)

**Comment by forteller** [comment]
Hi again. Diet type is still not shown by default for fast food.
![Screenshot from 2021-11-12 18-13-46](https://user-images.githubusercontent.com/343561/141507450-600b516a-284e-4235-8219-245d389a46df.png)

**Comment by 1ec5** [comment]
openstreetmap/id-tagging-schema@11f552486ca946bb6ecf2fef6d4448d12dd68db9 went into v3.1.0, which iD hasn’t been able to upgrade to yet: #8600.

**Comment by forteller** [comment]
I see. Then I want to request that it's also added to the current branch :)
