### ISSUE TITLE
Admin boundary way stops rendering when edited

### ISSUE THREAD

**Issue by kymckay** [openstreetmap/iD#7921]
Was editing some admin boundaries and while dragging a node the way it was part of just stopped rendering. No errors in the console window.

At first I thought I'd never reproduce this, but after a bit of debugging I've determined it's related to the "Boundaries" and "Other Features" map feature layers. The easiest way to reproduce:
1. Disable all map features except for boundaries
2. Find a boundary line which isn't tagged and only exists as a relation member
3. Drag a node belonging to the way, then deselect the way
4. At this point the line disappears, but will render again if you enable "Other Features"

![image](https://i.imgur.com/7GppM8o.gif)

**Comment by maro-21** [comment]
If the line isn't tagged `boundary=administrative`, it is treated as "other feature", not like a boundary. iD probably doesn't check if it's a member of a relation.
I don't think it's a bug, you can solve it by enabling "Other Features" when editing boundaries.

The similar behavior is when you disable e.g. Buildings but open a building to edit by typing its number in the editor.

**Comment by kymckay** [comment]
@maro-21 Then why does it show up to begin with? The rendering is inconsistent, it should either always show when boundaries are enabled without "other features", or it should only show when other features is enabled.

**Comment by DujaOSM** [comment]
I know about the described behavior and I've always considered it a feature, although I concur there's a minor bug in there.

There is general inconsistence about untagged lines that are members of relations (either multipolygons or boundaries). Sometimes iD recognizes their relation membership and filters them according to it, and sometimes not, bundling them with "other features". I haven't recognized a pattern, sometimes different lines of the same type behave differently on the same screen. 

The "right" answer is probably to treat those lines according to the relation they make up.

**Comment by quincylvania** [comment]
#6277 is about lines that are members of boundary relations not hiding when they should be hiding, so I think this is a duplicate. It seems to have something to do with the order features are downloaded and added to the graph, or some kind of race condition.
