### ISSUE TITLE
Implement plural forms on Transifex

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7922]
I didn't know before, that Transifex supports plural forms. Now I can see it's possible.
https://cdn.transifex.com/docs-images/plurals_editor_180404_161717.png
Could you enable pluralized strings on Transifex? There aren't many:
- `Copied {n} features.`
- `Add {n} duplicate features here.`
- `Pasted {n} features.`
- `Deleted {n} features.`
- `Downgraded {n} features to basic buildings.`
- `Downgraded {n} features to addresses.`
- `Downgraded {n} features.`
- `Merged {n} features.`
- `Split {n} lines/area boundaries.`
- `Extracted {n} points.`
- `{n} results for {search}`
- `Changes ({count})`

https://docs.transifex.com/localization-tips-workflows/plurals-and-genders

More info: http://cldr.unicode.org/index/cldr-spec/plural-rules

**Comment by 1ec5** [comment]
Related: #597.

**Comment by maro-21** [comment]
That thread was created many years ago, I'm not sure if this support for plurals was already there on Transifex then.

**Comment by quincylvania** [comment]
Yep, this is #597. Thanks for putting it back on my radar though, I'd like to address it soon.
