### ISSUE TITLE
Presets: Implicit ordering of presets from name suggestion list

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/iD#7927]
I noticed the following entries (shortened) in the `presets.json`. Two times McDonald's, the first in English, the second in Cryllic.  <details>

```
{
	"amenity/fast_food/burger/McDonald's": {
		"name": "McDonald's",
		"tags": {
			"brand:wikidata": "Q38076",
			"amenity": "fast_food",
			"cuisine": "burger"
		},
		"addTags": {
			"amenity": "fast_food",
			"brand": "McDonald's",
			"brand:wikidata": "Q38076",
			"brand:wikipedia": "en:McDonald's",
			"cuisine": "burger",
			"name": "McDonald's",
			"takeaway": "yes"
		},
		"reference": {
			"key": "cuisine",
			"value": "burger"
		},
		"matchScore": 2
	},
	"amenity/fast_food/burger/Макдоналдс": {
		"name": "Макдоналдс",
		"tags": {
			"brand:wikidata": "Q38076",
			"amenity": "fast_food",
			"cuisine": "burger"
		},
		"addTags": {
			"amenity": "fast_food",
			"brand": "Макдоналдс",
			"brand:en": "McDonald's",
			"brand:ru": "Макдоналдс",
			"brand:wikidata": "Q38076",
			"brand:wikipedia": "en:McDonald's",
			"cuisine": "burger",
			"name": "Макдоналдс",
			"name:en": "McDonald's",
			"name:ru": "Макдоналдс",
			"takeaway": "yes"
		},
		"reference": {
			"key": "cuisine",
			"value": "burger"
		},
		"matchScore": 2
	}
}
```
</details>

The problem here is that both have the same `tags`, so both would match a search by tags in no defined order.

If there is no defined order, it is a problem because it is undefined what would be the first entry in the resulting match list when one searches presets by tags: _McDonald's_ or _Макдоналдс_?

Not sure how iD ensures that always the correct (probably: English?) entry is shown first, maybe by looking at whatever brand preset is defined further up in the JSON file? If yes, actually according to the [JSON spec](https://www.rfc-editor.org/rfc/rfc7159.txt), a JSON object is 
>    An object is an **unordered** collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.

I am opening this issue because when using the [Java osmfeatures library](https://github.com/westnordost/osmfeatures) which is using the presets from iD to do this....

```kotlin
val names = featureDictionary.byTags(mapOf(
    "brand:wikidata": "Q38076",
    "amenity": "fast_food",
    "cuisine": "burger"
)).find().map { it.name }
println(names)
```
the following is printed: `["Макдоналдс", "McDonald's"]` (and sometimes other orders too)

The reason is that the default Java JSON parsing library treats JSON objects as unordered (as defined in the JSON spec), so there is no intrinsic meaning to in which order the items in an object are defined.

### Proposed solution
Introduce an `order` field for a preset that would order give an explicit order to presets that do have the **same** tags.

**Comment by bhousel** [comment]
Hey @westnordost , glad to see you are using the name-suggestion-index.. 
This issue should probably go over there instead of in the iD repo.

I'm doing some groundwork there to rethink how we represent the entries better (https://github.com/osmlab/name-suggestion-index/issues/3995)

> If there is no defined order, it is a problem because it is undefined what would be the first entry in the resulting match list when one searches presets by tags: McDonald's or Макдоналдс?

The reason iD can match this preset is because it boosts the preset score if the `addTags` match, see #6802 / [this code](https://github.com/openstreetmap/iD/blob/develop/modules/presets/preset.js#L70-L76)
(the Java osmfeatures library should probably do this too)

I'm wary about introducing an `order` field, because really the _correct_ preset to pick will depend on the location the user is mapping.  I'd like to see the NSI entries be more geographically distinct - so it's not like a user should ever need to pick between "McDonald's" or "Макдоналдс" - we already know where each of these presets are valid.  

We could also order them by area, giving more preference to more local presets (this is already what we do for imagery sources and community index entries).

**Comment by westnordost** [comment]
Nice, good to see the NSI is being developed further to be even more flexible. 

> The reason iD can match this preset is because it boosts the preset score if the addTags match, see #6802 / this code
(the Java osmfeatures library should probably do this too)

Thank you for the hint, will do that!

I understand that the better solution would be to add country code(s) to such "sub-branches"/translations of the same brand. Since this is not done right now for McDonald's, is it eligible to create an issue or PR for this over at the NSI?

**Comment by bhousel** [comment]
> I understand that the better solution would be to add country code(s) to such "sub-branches"/translations of the same brand. Since this is not done right now for McDonald's, is it eligible to create an issue or PR for this over at the NSI?

Maybe?  My take is that entries should be "geographically distinct"?  i.e. closing an issue like that would involve writing a check to catch NSI entries that overlap?

**Comment by westnordost** [comment]
Mh, on that note, a smart sort order would also be to if the search is not limited to a locale, sort those matches that are not geographically limited first. So for example if the Russian McDonalds preset is being limited to the Russian-speaking world in the future and one searches through the presets without saying "I only want results for my country", then any presets that are not limited to a country ("McDonalds") is sorted before any that are ("Макдоналдс"). Just implemented this in osmfeatures as well.

Not sure if this is relevant for iD, I imagine the search might always be bound to a certain locale/geographic location.
