### ISSUE TITLE
need improvements

### ISSUE THREAD

**Issue by prasadrajuv** [openstreetmap/iD#7933]
osm api as documentation create nodes and add ref to way to create. is  it posible single request for way with nested nodes to create with lat lngs. so it create nodes and way create at once so that using way id later request full to get all node ids. and also include nd ref to pass already exist node.
<osm>
 <way changeset="12">
   <tag k="note" v="Just a way"/>
   ...
   <nd ref="123"/>        //existing node
   <nd ref="4345"/>
   ...
<nd lat="..." lon="...">   // new node to create
   <tag k="note" v="Just a node"/>
   ...
 </node>
 </way>
</osm>

2) in id editer provide id number on select any node or way exist. provide edit mode and insert mode to stop mistakenly modify existing. because any node created at intersection drag or delete can cause change old exit way or node

**Comment by manfredbrandl** [comment]
I do not understand what that issue is about.

**Comment by mmd-osm** [comment]
I'm afraid I don't understand your issue either. I can read your words, but nothing more. So this is a wild guess at the first part of your text:

You can upload new nodes and ways (which referece those new nodes) via the API 0.6 changeset upload endpoint. This is what iD is already doing. The API also provides an endpoint to fetch a way including all nodes: https://api.openstreetmap.org/api/0.6/way/4972913/full - this is however out of scope for iD.

**Comment by quincylvania** [comment]
Hi @prasadrajuv. I'm also not exactly sure what you're asking, but I'll try to answer.

You've asked before about seeing node IDs in #7546.

You can ask about the OSM API at https://github.com/openstreetmap/openstreetmap-website.

We don't plan to add advanced functionality like inserting nodes with specific IDs or manually managing modification histories.
