### ISSUE TITLE
wrong QA warning "crossing ways" between a linear and an area-way on different levels

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [openstreetmap/iD#7935]
Hi,

please have a look at this footway: https://www.openstreetmap.org/way/589491916 in iD, its on level 0. It is claimed that it would cross with the pedestrian-multipolygon way https://www.openstreetmap.org/relation/3687928 , which is on level 1.

When there are two linear ways crossing on different levels, no warning is shown. But when a linear and an area-way are crossing on different levels, there is this warning which I think isn't necessary.

I know the footway in my example is indoor and might should be highway=corridor instead, but this has nothing to do with this, because it would have no effect, the same warning would appear.

**Comment by sun-geo** [comment]
+1 

This seems a similar case:
https://www.openstreetmap.org/edit?way=839971909#map=19/47.56084/7.59054
Is it?

**Comment by Elefant-aus-Wuppertal** [comment]
Yes, it is.

**Comment by quincylvania** [comment]
@Lukas458 Thanks for reporting. This was an issue with tags like `level` and `layer` getting ignored on all multipolygon crossings, such as highway areas and buildings.
