### ISSUE TITLE
Incorrect offer to add layer to building

### ISSUE THREAD

**Issue by cebderby** [openstreetmap/iD#7938]
I had noticed a number of cases of inexperienced and poor users adding layer to building, especially where ways (correctly) enter or leave.   I note that iD highlights ways crossing buildings and makes a number of 'fix' proposals, including changing layer values.
Layer is not a building tag.  It shall not be added to buildings by iD by any automated/semi-automated process.
Layer is used to define the local layering of crossing ways.  Not buildings.  iD shall not offer to add layer to ways on seeing a way crossing a building boundary.  The offers shall be:
- if the way really enters the building, do nothing
- if the way is supposed to remain outside/inside, adjust the geometry
- if the way is a building passage, add tunnel=building_passage
I note a history of refusing proper suggestions to preserve the integrity of OSM, I hope this will be properly actioned.

**Comment by quincylvania** [comment]
Some background on the use of `layer` in the validator: #5943, #5924, #6367, #7809.

As I understand it, the `layer` tag simply specifies the vertical ordering of ways when it's ambiguous. I'm not sure what's wrong with using it on buildings… how else would you specify the order when one building physically overlaps another? A tag like `building=roof` tag is combined with `layer` [over 570,000 times](https://taginfo.openstreetmap.org/tags/building=roof#combinations). The iD validator didn't invent this tagging.

While ideally a crossed highway could have info like `tunnel`, `covered`, `indoor`, or `bridge`, the `layer` alone is enough to clarify what's going on for renderers and is simple for the typical mapper to add.

That said, we can reevaluate if this is causing issues for data consumers or the community at large decides this isn't correct.

**Comment by quincylvania** [comment]
Lacking further discussion, I'm closing this as not-a-bug.
