### ISSUE TITLE
#help-wanted How to add few custom imagery sources in iD?

### ISSUE THREAD

**Issue by pedjas** [openstreetmap/iD#7939]
I want to set few custom tile sources to be available forusers of iD instance on my server.

I found out that I can edit index.html and add

`iD.fileFetcher.cache().imagery = customImagery;`

before

`context.init();`

That works. My custom imagery shows in iD but all other imagery is lost. 

I want to add my custom imagery to the the list of existing imagery, something like `iD.fileFetcher.cache().imagery.push(customImagery);`. This does not work as `iD.fileFetcher.cache().imagery` is undefined.

I've spend quite a time lurking through iD code trying to find out how to do this. I failed to find where list of preloaded imagery is kept so I can add to it.  Is this at all possible?

**Comment by quincylvania** [comment]
Hi and welcome, @pedjas. Always great to hear from others developing with iD downstream.

iD currently loads its imagery from dist/data/imagery.min.json, which is bundled via the [scripts/update_imagery.js](https://github.com/openstreetmap/iD/blob/develop/scripts/update_imagery.js) script. You can either edit the script or add sources to [data/manual_imagery.json](https://github.com/openstreetmap/iD/blob/develop/data/manual_imagery.json). Use `npm run imagery` to run the script.

**Comment by pedjas** [comment]
> iD currently loads its imagery from dist/data/imagery.min.json, which is bundled via the [scripts/update_imagery.js](https://github.com/openstreetmap/iD/blob/develop/scripts/update_imagery.js) script. You can either edit the script or add sources to [data/manual_imagery.json](https://github.com/openstreetmap/iD/blob/develop/data/manual_imagery.json). Use `npm run imagery` to run the script.


I know abut that, but I would like to avoid to alter ID source, as it means I have to manually take care of each update. I hope imagelry list is exposed somehow so I can simply add new imagery programatically.

If it is not, then this can be treated as new feature suggestion.

**Comment by quincylvania** [comment]
> I hope imagelry list is exposed somehow so I can simply add new imagery programatically.

Good point, we can look into this.
