### ISSUE TITLE
Allow natural=cave_entrance on nodes that are part of ways

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#7945]
At least some caves can be correctly tagged on nodes belonging to ways

For example see https://www.openstreetmap.org/changeset/90314885#map=19/50.20174/19.81875 - cave visited each (covidless) year by 90 000 people. And yes, there is footway leading to its entrance.

iD claims that it must be always on a standalone node.

![screen01](https://user-images.githubusercontent.com/899988/92011475-63becc00-ed4b-11ea-9ce8-642610e9d105.png)
.

**Comment by quincylvania** [comment]
@matkoniecz Thanks, sounds fine.
