### ISSUE TITLE
Add preset amenity=lounger

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#7947]
I think it would be useful to have https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlounger as a preset, even if usage is not so high with 440+ cases ATM.

For search terms, I suggest to also add "bench", so people who are looking for a sub-tagging of bench will find this Preset and can choose between a regular bench or a lounger.

Additional fields on the preset
- I think, all of those that `amenity=bench` has
- I would skip the seasonal field for now and wait if people are missing it; I saw controversial discussions about it

Btw, one could also tag those loungers with `amenity=bench + bench:type=lounger` (see https://wiki.openstreetmap.org/wiki/Key:bench:type), but the main tag makes more sense and it also has more usage.

Personally, I would vote for deprecating the bench:type=lounger (and similar values, see https://taginfo.openstreetmap.org/keys/?key=bench%3Atype#values).

**Comment by quincylvania** [comment]
I had some hesitation about adding a new `amenity` value for this, since data consumers won't automatically support it, but I see the tag was already discussed and approved via vote so I guess there's not much more to say.
