### ISSUE TITLE
Edit Elevator preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7950]
Remove wrong field "maxweight" which is used for "legal access restriction for vehicles that exceed the specified actual weight".

The tag maxweight is well described on Wiki and there is no mention about using it for elevators.
https://wiki.openstreetmap.org/wiki/Key:maxweight

![iD elevator](https://user-images.githubusercontent.com/57260466/92236631-114dee80-eeb6-11ea-959b-802d6329ffd1.png)

**Comment by quincylvania** [comment]
@maro-21 Thanks, but just because the wiki doesn't mention a usage doesn't mean it's wrong. I see elevators as part of the accessible routing network. Many even support vehicles. Elevators always have a legal maximum weight posted in them, at least in the US, which is akin to a max weight sign along the highway.

Let us know if this is causing problems for data consumers, but otherwise I'm certain this is fine.

**Comment by maro-21** [comment]
But we can't use the same tag for two different things.
As you can see on the screenshot, the description and image doesn't fit to elevator maximum weight.

You previously said that there should be community consensus to add or remove something from iD preset.
If there was consensus, there would be mention on the Wiki.

**Comment by quincylvania** [comment]
> But we can't use the same tag for two different things.

This actually happens all the time. A few examples are `ele`, `height`, `width`, `access`, and `lit`, which encode the same information on all kinds of different types of features.

The wiki also says "a number of navigable structures may be tagged with a weight restriction", and then gives examples such as railways, helipads, roller coasters, and zip-lines in addition to roads. An elevator is a navigable structure too.

> As you can see on the screenshot, the description and image doesn't fit to elevator maximum weight.

I'd recommend updating these and the wiki page to reflect broader usage patterns.

> If there was consensus, there would be mention on the Wiki.

Unfortunately, we can't make this assumption about the wiki. It's written be a small number of volunteers and is often outdated or incomplete.

> You previously said that there should be community consensus to add or remove something from iD preset.

Community consensus is just one of the factors, but yes, if there is actually controversy here then I'm happy to change this until it's sorted out. But I don't see evidence of controversy.
