### ISSUE TITLE
Make More Fields more visable

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7957]
To help improve the visibility of More Field tags, I propose we make them more visible by replacing the More Fields field with something like this: 
![image](https://user-images.githubusercontent.com/50059322/92423341-80c51780-f11c-11ea-97c6-96fefd555bba.png)

**Comment by quincylvania** [comment]
@TheAdventurer64 Is this just a screenshot of an old version of iD? It'd be worth mentioning. Every change is made for a reason, so we can't just revert something without understanding the history. I agree we should be thinking about ways to improve the inspector.

**Comment by quincylvania** [comment]
Lacking further discussion, I don't see a compelling reason to pursue a reversion. The newer design isn't perfect but it has a number of advantages I'm happy to discuss should anyone be interested.

![Screen Shot 2020-09-23 at 9 30 33 AM](https://user-images.githubusercontent.com/2046746/94019396-bd7d4980-fd7f-11ea-99ea-f0508b59917c.png)
