### ISSUE TITLE
Add amenity=mortuary to presets

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7958]
I would like to recommend the addition of `amenity=mortuary` to iD's presets.
I think it's a very common amenity in every country and deserves a preset of its own.

Regards.

**Comment by quincylvania** [comment]
Sounds fine, but I'd prefer to call this preset "Morgue". A mortuary can also refer to funeral homes, which iD already has a preset for.

**Comment by AntMadeira** [comment]
Actually, the term is a bit vague, even on the wiki. The request still applies, because there's no preset for a morgue, but I was thinking about the place where the dead await to be buried, usually with a ceremony or just some other private event, usually on a proper house next to or inside the cemetery.
For that, maybe it's best to wait for the approval of the funeral_hall tag:
https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Funeral_hall
