### ISSUE TITLE
real time validation

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7962]
Seems working depending on the order of deleting items (tags and relation members).

a) real time validation is displaying a issue when first delete relation members and delete tags afterwards:
![rt-val 1members](https://user-images.githubusercontent.com/47290585/92613498-552c6380-f2bb-11ea-87a6-fb80bec3c27b.gif)

b) real time validation is not displaying a issue when first delete tags and delete relation members afterwards:
![rt-val 1tags](https://user-images.githubusercontent.com/47290585/92613520-59f11780-f2bb-11ea-9bb1-6cc93b4b14c5.gif)

**Comment by quincylvania** [comment]
@sun-geo Thanks for reporting! We manually rerun validation in iD since doing so on every change would be inefficient. Turns out we haven't been revalidating after member or membership changes, but it at least it was a quick fix 🔧

**Comment by sun-geo** [comment]
Thanks a lot.
