### ISSUE TITLE
Add tram-bus stop preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7970]
In my city (and I think in other cities with tram system too) there are many combined tram+bus stops.
Would it be possible to add such preset to iD?

```
public_transport=platform
highway=bus_stop
bus=yes
tram=yes
```

Because currently such stops are displayed as "Bus Stop".
https://wmiasto.files.wordpress.com/2015/12/img_8202_3000x2000.jpg?w=510
https://wmiasto.files.wordpress.com/2011/11/imgp4743.jpg?w=510

**Comment by quincylvania** [comment]
I just did #6142 which adds a field to set and manage vehicle types. Would that be sufficient or do you still think we need this preset?

**Comment by maro-21** [comment]
I think we need it!
It could be even a non searchable preset, because what I wanted is to display a name "Bus-Tram stop" (or similar) instead of "Bus stop".
Combination bus-tram is common, other combinations are rare or almost don't exist. All I wanted was not to display "Tram Stop" or "Bus Stop" for mixed stops, but "Bus-Tram Stop" :)
So this is from a perspective of an editor who edits existing feature, not for someone who wants to add a Tram-Bus Stop.

**Comment by maro-21** [comment]
Thank you!:)
