### ISSUE TITLE
[2.18.5] [bug] Can't create new node by just clicking on the halfway point

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#7972]
- Ways have a little triangle halfway between nodes that can be dragged to create a new node.
- Double-clicking on a way elsewhere will create a new node.
- Previously you could double-click on the triangle to create a new node exactly at halfway
- This doesn't work anymore.

**Comment by quincylvania** [comment]
This is a weird one. The bug occurs in 2.18.5, but not in Firefox, and it already seems fixed in the `develop` branch, despite no changes to the files I would have expected. I suppose we can just close this and not worry unless it reappears.
