### ISSUE TITLE
Bing Street View - Click area doesn't fill zoom button

### ISSUE THREAD

**Issue by jgscherber** [openstreetmap/iD#7974]
See gif

ER: The entire plus-button is clickable to zoom (same as minus-button)
AR: Only the top edge of the plus-button is clickable

![ezgif-7-db09b67c18b3](https://user-images.githubusercontent.com/6207661/92772005-f6b9c080-f360-11ea-9e1e-ffa176b94a05.gif)

**Comment by quincylvania** [comment]
@jgscherber Thanks for reporting!
