### ISSUE TITLE
Add support to show Mapillary/OSC imagery in separate window

### ISSUE THREAD

**Issue by Jakuje** [openstreetmap/iD#7975]
I often struggle to use mapillary images as they are really small, I have to zoom through them all the time and move around. If I would like to see them larger, it is against the size of the map that I am editing.

I have two screens so it would be very handy to move the image to the second display (probably in separate window) to use the space better.

**Comment by quincylvania** [comment]
Welcome, @Jakuje. Have you used the external links in the photo viewer? These open the images in a separate window. You can also drag the sides of the viewer to make it larger.

<img width="355" alt="Screen Shot 2020-09-28 at 4 46 29 PM" src="https://user-images.githubusercontent.com/2046746/94484308-32021f00-01aa-11eb-8767-77042d93d95e.png">

**Comment by Jakuje** [comment]
Hi. I know that the viewer can be stretched, but it is always at the expense of the map, which I am editing. If I fill one third of the screen with the image, one third of the screen with side panels (yes, they can be hidden but it is quite inconvenient), the map is very small with very bad ratio to orient in and edit.

Opening in bing maps is I think only for the streetside imagery. Indeed mapillary has also its permalinks that can be opened in new window, but they would not follow the map I edit -- I would have to move on the mapillary map on the second screen while comparing where it should fit in the map I am editing, which is very inconvenient.

**Comment by quincylvania** [comment]
@Jakuje Hmm okay, I agree it'd be nice to pop stuff like this out into a separate window, but this isn't really a common pattern in web apps. We'd have to think about the user experience and if this is even possible.

**Comment by Jakuje** [comment]
Technically, it is possible to open a new browser window and talk with it from the main one (or get updates from there). Lets take google slides for example, where you open slides in new window for presenting and then open a separate speaker notes window, where slides are changing synchronously.

**Comment by quincylvania** [comment]
> Technically, it is possible to open a new browser window and talk with it from the main one

@Jakuje Yes, but iD is embedded in an iframe on osm.org, so I'm not sure about that dynamic. Browsers can also be cagey about how they handle popup windows.

**Comment by danieldegroot2** [comment]
Superseded by #10388.

cc: @tyrasd
