### ISSUE TITLE
Presets: Add ramp=yes to highway=stairs

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#7977]
The preset for `highway=stairs` https://github.com/openstreetmap/iD/blob/develop/data/presets/presets/highway/steps.json does not have information about the `ramp`-key https://wiki.openstreetmap.org/wiki/Key:ramp.

The key is "in use" with 30k+ uses.

Unfortunatelly the values that are documented on the wiki page dont allow for an easy UI. Maybe a first step would be to have a dropdown with fixed values: `ramp=yes|separate|no|NULL/Unknown`. The other, special ramp types could be added later, IMO.

---

PS: https://github.com/westnordost/StreetComplete/issues/2036 is thinking about this key as well.

**Comment by quincylvania** [comment]
@tordans Supporting `ramp=yes`/`no` sounds okay. But I find `ramp=separate` confusing since these are mapped as distinct ways anyway. It has [less that 1%](https://taginfo.openstreetmap.org/keys/ramp#values) of the uses, so I'm inclined to leave it off.

**Comment by tordans** [comment]
@quincylvania thanks. For reference, see also https://github.com/westnordost/StreetComplete/issues/2036#issuecomment-703252986 with thought about the separate-value.
