### ISSUE TITLE
Move node from a detached area

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7984]
Hi there.
I don't know if this was already addressed here, but a somewhat thorough search didn't show the issue I want to bring here.

Every time I detach an area from a line (say a parking lot which is drawn over a street) I'm unable to move some of its nodes (even if I have the area selected) _**if those nodes belong to more than one line**_.
Here's what happens:
- detach area from line
- select area
- select one of the area's node, which also belongs to two lines (a node from a junction)
- as a result, if I want to move that node, iD always selects the line, even while pressing shift
- this doesn't happen if the node is shared by the area and just one line

The behaviour I would like to see is:
- if I have an area selected and I select one of its nodes to drag it, the selected node should always belong to that area and not to other elements.

Hope this makes any sense...

**Comment by quincylvania** [comment]
#2206 is a similar longstanding issue, but for disconnecting a selected node, not a selected way. This is easier if a way is already selected.

> if I have an area selected and I select one of its nodes to drag it, the selected node should always belong to that area and not to other elements.

I agree this would be the expected functionality 👍

**Comment by quincylvania** [comment]
Superseded by #8174.
