### ISSUE TITLE
Stop spliting all ways when spliting on a node

### ISSUE THREAD

**Issue by SHARCRASH** [openstreetmap/iD#7992]
As an ex OSM contributor on iD, i've found the latest split function very inconvenient to handle elements since it splits all overlapping ways. This was one of the reasons why i abandoned iD. Obviously you wanted it to behave this way.... But even for other contributors not using iD it is a hassle: we can find out many equal ways having the same tags side by side for no reason and we also find MP perimeters split (having less than 2000 nodes) in several sections. This makes it difficult to handle them when trying to add or enhance further and creates futile data.
Example on this MP:
https://www.openstreetmap.org/way/44000597/history
https://www.openstreetmap.org/way/844627379/history
https://www.openstreetmap.org/way/844627375/history
https://www.openstreetmap.org/way/842229027/history 

So, please, would you mind change this to a more convenient split function?

**Comment by maro-21** [comment]
I don't like it either. But there is a way to bypass it: you can first disconnect the roads from each other, split and then connect again in the same node.

**Comment by SHARCRASH** [comment]
> I don't like it either. But there is a way to bypass it: you can first disconnect the roads from each other, split and then connect again in the same node.

I know, before posting here i tested again the split function but many users do not care in doing these extra manipulations, understandably it is a hassle.

**Comment by sun-geo** [comment]
maro-21 :
> I don't like it either. But there is a way to bypass it: you can first disconnect the roads from each other, split and then connect again in the same node.

Same here, but my workaround looks bit different (without disconneting), see movie below.

@SHARCRASH Do you have any suggetion how do you would change iD's split procedure?

![prevent split](https://user-images.githubusercontent.com/47290585/93262551-b44f1400-f7a4-11ea-972e-edee6b63672d.gif)

**Comment by quincylvania** [comment]
@SHARCRASH The workflow for this in iD is to use shift+click to select a line along with the node. Then when you split, only the selected line is affected. I think this works pretty well, I'm not sure how else iD would know which line to split.

**Comment by SHARCRASH** [comment]
> The workflow for this in iD is to use shift+click to select a line along with the node. Then when you split, only the selected line is affected. I think this works pretty well, I'm not sure how else iD would know which line to split.

@quincylvania Indeed that does the trick, thanks! But as you could see with some people here, they were not aware of that and use a workaround. It's not obvious that this is possible and it seems that many contributors, specially new ones don't know it. I've read the Help section in iD, it's not specified neither. 

In the left "Edit Features", it looks like that the "Features" section shows which elements are selected but:
1) it is not clear, why not rename it "Features Selected"
2) when i click on the cross from one of the features, all are deselected instead of only the specific feature which was clicked. 
3) The "Tags" section shows which tags are common or not, great! Pitty that the "Relations" section is not shown with similar information.

**Comment by quincylvania** [comment]
>  It's not obvious that this is possible and it seems that many contributors, specially new ones don't know it. I've read the Help section in iD, it's not specified neither.

True, this is one of many areas where iD could use better documentation materials.

> it is not clear, why not rename it "Features Selected"

Maybe! "Selected" could be considered implied, but maybe not.

> when i click on the cross from one of the features, all are deselected instead of only the specific feature which was clicked.

I can't reproduce this, can you point to a location where this happens? Or share info about your browser/setup?

> The "Tags" section shows which tags are common or not, great!

Thanks! We added this only a few months ago in v2.18.0.

> Pitty that the "Relations" section is not shown with similar information.

This is #7753. I'd definitely like to enable it.

**Comment by SHARCRASH** [comment]
@quincylvania Sorry for not having replied. I couldn't reproduce it neither, after you had replied, nor recall where i had tried. I gave it a few tries elsewhere and each time it did only unselect where i clicked on the cross. 

Thanks for all the help!
