### ISSUE TITLE
Line disappears while zooming and changing background

### ISSUE THREAD

**Issue by jeffdefacto** [openstreetmap/iD#7999]
If you have an in progress line and then zoom while changing the background with (cmd B) the current edit gets drops. 

Here is video of the bug https://vimeo.com/458412998/58cf42de99

**Comment by quincylvania** [comment]
@jeffdefacto Welcome, thanks for reporting! I'd seen this issue but I couldn't reliably reproduce it. I didn't realize zooming was the key factor 🗝

**Comment by boothym** [comment]
Noticed this as well, but couldn't work out what was causing it - I'll try to avoid zooming and see if that prevents it happening.

**Comment by boothym** [comment]
@quincylvania I've avoided zooming but it's still happened a couple of times - seems to also occur when panning.
