### ISSUE TITLE
Create a data consumer navigation app for iD

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#8005]
So, there are many issues with OpenStreetMap, but these are the two we could solve with my proposal.

1. There aren't enough mappers on OpenStreetMap 
2. Most data consumers (at least in the US) don't support tags like `opening_hours:covid19` or `toilet:disposal=flush`. 
A navigation app created as a companion to iD would solve this, as it would encourage people to improve the OpenStreetMap, as well as be one of the only North American data consumers to support tags like the ones mentioned above. Elaborating on the mapping encouragement, the app could possibly have a gamification system, which rewards users points for updating places, adding images, and reporting issues to the map using Notes. There could also be a review system, which allows users to share their thoughts on a restaurant or a hairdresser. The gamification system could also have a "survey", where users would be asked questions like: `  Does this place have air conditioning?`   (`  air_conditioning=yes/no`   )

**Comment by mmd-osm** [comment]
Do you know StreetComplete? It already has the gamification you've asked for towards the end. Otherwise, how is any navigation app related to iD? Those tags you've mentioned are not "iD-only", so it's not clear why you're asking this on the iD issue tracker.

**Comment by TheAdventurer64** [comment]
> Do you know StreetComplete? It already has the gamification you've asked for towards the end. Otherwise, how is any navigation app related to iD? Those tags you've mentioned are not "iD-only", so it's not clear why you're asking this on the iD issue tracker.

For the "iD only" issue, I am asking it here because of these two reasons:
1. iD has detailed presets that aren't used anywhere else (eg. Drugstore, Bubble Tea Cafe)
2. iD seems to have a good, organization system, and by my standards, seems to be the

**Comment by mmd-osm** [comment]
Ok, so this is definitely off topic for this repo. Better try somewhere else, maybe on talk ml, Slack...

**Comment by matkoniecz** [comment]
> iD has detailed presets that aren't used anywhere else (eg. Drugstore, Bubble Tea Cafe)

iD presets are used in Go Map!! (instead of maintaining own presets) and StreetComplete (via https://github.com/westnordost/osmfeatures ). Maybe also in other projects.

> iD seems to have a good, organization system, and by my standards, seems to be the

It does not mean that they are obligated to implement and maintain separate unrelated (beyond "OSM based" and "is using iD presets") project.

Feel free to start such project if OsmAnd is not displaying enough detail. Or help to implement this features in other projects - if they would want to support it. Personally I would consider `toilet:disposal=flush` displayed in my navigation app as a pointless and unwanted clutter.

**Comment by matkoniecz** [comment]
> iD seems to have a good, organization system, and by my standards, seems to be the

It does not mean that they are obligated to implement and maintain separate unrelated (beyond "OSM based") project.

Feel free to start such project if OsmAnd is not displaying enough detail (or help to implement this features in other projects - if they would want to support it, personally I would consider `toilet:disposal=flush` displayed in my navigation app as a pointless clutter).

**Comment by quincylvania** [comment]
@TheAdventurer64 Thanks for your enthusiasm. I'm humbled that you have such faith in iD, but the fact remains that it's only a data editor with limited resources. We need to stay focused.

You might have better luck requesting these features from existing OSM navigation apps, or building one yourself. OpenStreetMap is an ecosystem of tools after all, not a monolith.

When we do #6483, it'll be easier to use parts of iD in other apps.
