### ISSUE TITLE
Street view viewer window missing arrow glyphs

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/iD#8011]
The arrows that normally appear to advance the street view imagery viewer are missing. Here's an example:
![image](https://user-images.githubusercontent.com/1827881/93776502-985ad080-fbf1-11ea-8cfb-f933db4ba044.png)

The arrow buttons are still functional, just invisible to me.
![mappy-advance](https://user-images.githubusercontent.com/1827881/93776866-0dc6a100-fbf2-11ea-9eee-f0584c4a3ace.gif)

### System info

🍎 | 🍋
-- | --
Microsoft Edge | 85.0.564.51 (Official build) (64-bit)
Revision | 626274a16bb350129a74ead7a3d8d53a5ad39364
Operating system | Windows 10 OS Version 2004 (Build 19041.388)
JavaScript | V8 8.5.210.20
Flash | 32.0.0.433 C:\Users\elliott.plack\AppData\Local\Microsoft\Edge\User Data\PepperFlash\32.0.0.433\pepflashplayer.dll
User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51

**Comment by quincylvania** [comment]
@talllguy This is #7920, but thanks a lot for the extra info! Should help track this down 🕵️‍♂️

**Comment by talllguy** [comment]
Ah, I did do a search first but missed that one.
