### ISSUE TITLE
Use pluralize localizable strings for "This" and "These"

### ISSUE THREAD

**Issue by magol** [openstreetmap/iD#8014]
It is many string pairs that is of the form "`This feature...`" and "`These features...`" and I suggesting to use pluralize localizable strings for these type of  strings (see #4964).

**Comment by maro-21** [comment]
<s>Can you give an example in your language how the translation would look like?</s>

Oh, I think you meant to merge two strings into one pluralizable?

**Comment by maro-21** [comment]
Oh, I think you meant to merge two strings into one pluralizable?

**Comment by magol** [comment]
Exactly, merge the string pairs into pluralizable strings.

**Comment by quincylvania** [comment]
@magol Just to confirm, some languages need this even if the actual number isn't included in the string?

**Comment by maro-21** [comment]
> some languages need this even if the actual number isn't included in the string?

You're asking the same what I asked before :)
I think Indo-European languages don't need `few/many/other` forms when there is no numeral but they just need singular and plural forms, like English.
So current situation is:
two strings: "This feature..." and "These features..."
They are translated into my language as "Ten obiekt..." and "Te obiekty..."
If you turn these two strings into one pluralizable, in English there will be still two strings but in Polish 4 strings, but all plural will be the same:
one: "Ten obiekt..."
few: "Te obiekty..."
many: "Te obiekty..."
other: "Te obiekty..."
So I don't know if we need to change it, unless there is a language which distinguish them.

**Comment by magol** [comment]
@quincylvania
> some languages need this even if the actual number isn't included in the string?

I don't know for other languages, Swedish work the same as English.

The reason I suggest this is to make it symmetric. If strings containing `{n}` is handled this way, why not similar strings pairs without the `{n}`. It also make it easier to translate when string pairs is grouped.

**Comment by quincylvania** [comment]
@magol I agree it sounds nice, but @maro-21 indicates it would cause unnecessary work for some languages. So I think we need to leave this as-is unless we find some languages actually need these plural forms.
