### ISSUE TITLE
Renaming Preset of relation: type=route / route=foot 

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#8019]
`type=route` & `route=foot` wiki: https://wiki.openstreetmap.org/wiki/Relation:route#Route_types_.28route.29

The current wording of the preset is "Foot Route", see example: https://www.openstreetmap.org/edit?relation=2400284

I'm not native speaking, but would e.g. match "Walking Route" a bit better?

**Comment by quincylvania** [comment]
@sun-geo Sounds fine to me.

**Comment by Shramkoweb** [comment]
I took

**Comment by quincylvania** [comment]
Done by @irevenko in #8023.
