### ISSUE TITLE
Keyboard Shortcuts list

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8021]
From version 2.18.0, when a new keyboard shortcut `Ctrl+ Shift + ↑, ←, →, ↓` was added, the shortcut list doesn't fit on the screen. Would it be possible to fix it somehow?

old version:
![shortcuts_old_version](https://user-images.githubusercontent.com/57260466/94144474-75d6ea80-fe71-11ea-9a11-8aea4939e655.png)

new version:
![shortcuts_new_version](https://user-images.githubusercontent.com/57260466/94144486-7a9b9e80-fe71-11ea-83b1-65f471102a38.png)

**Comment by quincylvania** [comment]
I added a little more space, but this also depends on the length of the text for the locale. See #7830.
