### ISSUE TITLE
Add warning for buildings tagged as isolated dwelling

### ISSUE THREAD

**Issue by soshial** [openstreetmap/iD#8024]
For a long time I was thinking, that if an `isolated_dwelling` consists of only 1 household, I may tag the building itself with this tagset: 
```
place=isolated_dwelling
building=yes
name=<...>
```

Tagging so made `name` tag visible only at zoom level 17:
<img width="70%" alt="Screenshot 2020-09-24 at 09 01 36" src="https://user-images.githubusercontent.com/100644/94307857-3518c780-ff7e-11ea-8559-7c40623ed420.png">

At zoom level 15 (point with `isolated_dwelling` are visible; the circled building is not):
<img width="70%" alt="Screenshot 2020-09-24 at 09 01 12" src="https://user-images.githubusercontent.com/100644/94307878-3cd86c00-ff7e-11ea-8afc-2e1a45dea462.png">

As it turned out, it is not a recommended practice and `isolated_dwelling` is an area without, and not a building. We should show a warning to users if they tag building with `isolated_dwelling` tag.

**Comment by quincylvania** [comment]
@soshial Hmm iD doesn't support this type of warning yet, where certain combinations of tags are flagged without an upgrade path. (iD can flag tags like this for removal, but not for extraction.) While we could theoretically add it, I'm afraid it could become an endless source of tagging disagreements about what tags are okay together. This doesn't mean we shouldn't add it necessarily, but we should be deliberate.

Looks like there are [3500 uses](https://taginfo.openstreetmap.org/tags/place=isolated_dwelling#combinations) of this particular tag combo, so perhaps there is some subset of mappers who like it?

**Comment by quincylvania** [comment]
Lacking further discussion, I'm closing this as low impact.
