### ISSUE TITLE
Can't disconnect a path

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8025]
I have a path connected to the tram track. I wanted to disconnect it but I couldn't because
"This can't be disconnected because it connects members of a relation.".
Indeed there are many tram relations on the tram track. iD doesn't allow me to disconnect it, but I can remove that shared node without any problem.

![iD_disconnect](https://user-images.githubusercontent.com/57260466/94342770-a35b9980-0013-11eb-914e-cb94979be78e.png)

However, it can be ommited by adding a node on a line, split it, and remove that connected line. That's the only possibility I know now, which doesn't spoil relations.

Is it a bug, feature, or is possible to disconnect it somehow? If I can delete a node, why can't I disconnect it?

**Comment by TheAdventurer64** [comment]
I believe this is to serve iD's purpose: To not damage other users' data.

**Comment by manfredbrandl** [comment]
@maro-21 Can you try to select the path first and then shift right-klick on the connecting node? Are you offered the operation disconnect?

**Comment by quincylvania** [comment]
> Can you try to select the path first and then shift right-klick on the connecting node? Are you offered the operation disconnect?

I tested the scenario and this should work. Disconnecting the node alone would disconnect all the ways, so iD is blocking you from disconnecting the railways (which are in the same relation). If you only want to disconnect the path, you have to select that along with the node.

Theoretically we could allow iD to disconnect the ways which aren't relation members. I'm not sure if this would be confusing.

**Comment by DujaOSM** [comment]
> Theoretically we could allow iD to disconnect the ways which aren't relation members. I'm not sure if this would be confusing.

I think it would. However, I think a hint towards the workaround in the error message would be in order. Along the lines of "Try to Shift+Select specific objects to disconnect" -- it's difficult to formulate a short but understandable message.

**Comment by maro-21** [comment]
Answering my own question: I can disconnect this path by selecting the path, holding Shift, clicking the node, then clicking D. Then only the path is disconnected from the tram track, and the rails are still connected. This is not a bug, so I'm closing the issue.
