### ISSUE TITLE
Make "{labeled} and {count} more" pluralizable

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8026]
Could you make it pluralizable on Transifex?
`labeled_and_more: "{labeled} and {count} more"`

**Comment by quincylvania** [comment]
@maro-21 Thanks, I missed this one since both the English plural forms are the same.

**Comment by manfredbrandl** [comment]
@quincylvania There are two variables, which one is used for the distinction "one" versus "other"?

**Comment by quincylvania** [comment]
@manfredbrandl The `{count}` is the number. `{labeled}` is just a text label.


<img width="643" alt="Screen Shot 2020-09-28 at 11 10 27 AM" src="https://user-images.githubusercontent.com/2046746/94450411-411da880-017b-11eb-8784-24d853e3988f.png">

**Comment by maro-21** [comment]
> There are two variables, which one is used for the distinction "one" versus "other"?

Actually neither of them. In English these strings don't depend on the number in {count}.

`{labeled} and {count} more` is for example:
`Restaurant and 2 more`
