### ISSUE TITLE
Add red flags when attempting to insert Wikidata

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8028]
Here after the user inserts the Wikidata,
![X2](https://user-images.githubusercontent.com/1230959/94392536-1cc9c800-018b-11eb-8e03-6aaedd44469c.jpg)
wouldn't it be good if the Name field gets filled in for the user too, so he doesn't have to copy it manually:
![X3](https://user-images.githubusercontent.com/1230959/94392629-61edfa00-018b-11eb-8f9a-81c543b04e30.jpg)
Yes, have this only work for empty Name fields.
And yes, if the user isn't happy with what gets copied, he can always adjust it manually.

**Comment by andrewharvey** [comment]
You have to be careful here because of https://wiki.openstreetmap.org/wiki/Wikidata#Importing_data_from_Wikidata_into_OSM so you should not be doing this and tools shouldn't be doing it for you either.

**Comment by jidanni** [comment]
Hmmm, during the whole process no red flags occurred, and most fields were filled in for me.
So this tool needs the red flags added!

**Comment by jidanni** [comment]
Without big warnings (at every step?), most users will think "wiki"="cool", plus "the preset is encouraging me to fill this in".

**Comment by quincylvania** [comment]
> Hmmm, during the whole process no red flags occurred, and most fields were filled in for me.

iD doesn't fill in any tags with values from Wikidata except the Wikipedia link. Mappers are free to do this themselves if they're sure it's okay. If the OSM wiki is right, then iD can't know which values are safe and which aren't, and we're not going to set ourselves up for license conflicts.

**Comment by jidanni** [comment]
> iD doesn't fill in any tags with values from Wikidata except the Wikipedia link.

Well all I know is I didn't type e.g., that Description in the above image. It got entered for me after I fed it the Wikidata link.

**Comment by andrewharvey** [comment]
> Well all I know is I didn't type e.g., that Description in the above image. It got entered for me after I fed it the Wikidata link.

The description showing there is not actually saved into the OSM database, iD shows it to help make sure you've added the right wikidata ID.
