### ISSUE TITLE
Gocery tag in iD editor

### ISSUE THREAD

**Issue by colonelm** [openstreetmap/iD#8032]
shop=grocery tag is not not available in iD editor https://wiki.openstreetmap.org/wiki/Tag:shop=grocery

This is the most appropriate tag to map Ration Shop (as popularly called) / Fair Price Shop (newer name not popular). The Ration Shop's sell non-perishable food items such as Rice, Wheat, Sugar, Cooking Oil and Pulses. Only exception is Kerosene oil. There are ~500,000 shops that exists in India.  There may be similar shops in  developing countries.

Alternatively we need to define a tag for Ration Shop/Fair Price Shop.

**Comment by matkoniecz** [comment]
Note 

> U.S. and Canadian "grocery stores" are mostly not shop=grocery in the sense of this tag.

problem describe at wiki. If added it probably should not appear in US/Canada or should be described differently than "grocery"

**Comment by colonelm** [comment]
What about adding it through nsi.guide  ? Or a new tag  shop=public_distribution / public_food_distribution.  What would be the best way ? These shops are very very important.

**Comment by matkoniecz** [comment]
> What about adding it through nsi.guide ? 

If there are some widely appearing brands that are not present in name suggestion index then pull requests would be very useful and welcomed! Issues listing shop band and their wikipedia page or wikidata entry also would be useful at https://github.com/osmlab/name-suggestion-index

**Comment by matkoniecz** [comment]
>  Or a new tag shop=public_distribution / public_food_distribution

This would be likely best handled at tagging mailing list discussion or via wiki ( https://wiki.openstreetmap.org/wiki/Proposal_process ) or via discussion with other mappers in your region ( https://github.com/osmlab/osm-community-index may list their preferred discussion channels )

**Comment by bhousel** [comment]
There already is a PR at the NSI project where someone is trying to introduce the `shop=grocery` tag:
  https://github.com/osmlab/name-suggestion-index/pull/4215

I have asked them to please pick another tag that's more widely used, and it turns out the Indian community had already decided in 2017 to use `shop=convenience` for these shops.
