### ISSUE TITLE
Disposal methods for Portable Toilet roundabout entry

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8044]
This is an odd user experience for the user wanting to choose "unknown" as disposal method for Portable Toilet.

He cannot choose it, or manually enter it here, no matter how hard he tries,
![29844-9](https://user-images.githubusercontent.com/1230959/94884176-4c384780-049f-11eb-8ea9-ab8a80cb902f.jpg)

However, he discovers he can choose it below,
![12084-11](https://user-images.githubusercontent.com/1230959/94884184-522e2880-049f-11eb-95f0-c6144c5d34e7.jpg)

Which indeed gets it chosen at top,
![431-12](https://user-images.githubusercontent.com/1230959/94884306-b6e98300-049f-11eb-9fe1-c91aac66bb91.jpg)

So he thinks "All that trouble and roundabout way of getting things done."

**Comment by quincylvania** [comment]
Yes, iD limits some fields to the recommended values in order for them to be translated. The raw tag editor exists for situations where you still want custom values. If we re-implement #7411 then we could have both translated and custom values.

Also, `unknown` isn't a recommended value for any tag since it's usually the same as not tagging anything. In fact, it can troll data consumers by making them think there's an actual value.

**Comment by jidanni** [comment]
(Actually in this case simply hitting the trash can icon on Disposal gave:
```
Portable Toilet has incomplete tags
￼
Upgrade the tags
Ignore this issue
```
So indeed users do need to do the _dirty_ work of finding out just what kind of toilet they are sitting on...)

**Comment by quincylvania** [comment]
@jidanni Are there common portable toilets without chemical disposal? If so then we can remove this warning.

**Comment by jidanni** [comment]
Well even though https://www.toiletsforsale.com/10-common-types-portable-toilet/ lists various types,
I'm just saying the simple mapper shouldn't be required to "thrust his head into the hole to find out exactly what kind of portable toilet it is, before being allowed to leave (his edit.)"

And even if he isn't the toilet user, snooping around toilets at sporting events to find out what kind they are might arouse suspicions. So just let him say it is a portable toilet "and (be able to) get out of there (and save the edit properly.)" 

Anyway, 98 out of 100 portable toilet users, at a sporting event, couldn't answer the question.

Well if it is portable, why are we mapping it, when it might be rolled away tomorrow? Well some get parked for years at farms where I live...

**Comment by jidanni** [comment]
P.S., I note "Portable" isn't mentioned on
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets
and in fact the fact that it is portable or not only appears in the prompts,
and is lost when the final tags are composed.
Rather surprising.
OK, one could say "that it has wheels or can be picked off the ground doesn't matter for mapping."

**Comment by quincylvania** [comment]
Okay, we can remove the warning. Refer to #7783 for discussion on this preset. This stuff isn't all that important in the grand scheme of the map—you can ignore warnings or leave things blank or map these are plain toilets or not map these at all.
