### ISSUE TITLE
Deprecate barrier=chicane to barrier=cycle_barrier

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#8045]
I find those tags very confusing and it would be great if iD helped me by updating the wrong one.

The confusing part to me is, that chicane is a valid value, but as traffic_calming=chicane https://wiki.openstreetmap.org/wiki/Key:traffic_calming for slowing down traffic.

However, the same principle of infrastructure to slow down bikes is tagged barrier=cycle_barrier and not barrier=chicane, see https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier#Alternative_tags.

I think it would be a good idea to update those tags to the one, that was approved:
https://taginfo.openstreetmap.org/search?q=barrier%3Dchicane
374 usages barrier=chicane

https://taginfo.openstreetmap.org/tags/barrier=cycle_barrier
to 88.000+ usages barrier=cycle_barrier

**Comment by quincylvania** [comment]
@tordans Thanks, nonstandard `barrier` tags like this are a real problem since routers will often be cautious and prevent all traffic for unrecognized values.
