### ISSUE TITLE
Show search results of the same type of thing first when changing object type

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#8047]
Ok, not sure if this is even possible without too much work for it to be worth it, but it's been bothering me, and it probably results in errors in OSM, I think, so I will post it, and let you decide what/if to do anything about it.

Here's my scenario:

I find a building that's only tagged as a "building", but I know it's a kindergarten. So I select it, click on the object type to change it and search for "kinder". 

The first result is kindergarten/preschool..., so I press enter to select it and move on to the next task.

Except the first result was not kindergarten building, it was kindergarten area (amenity). But I did not notice that, because I was editing something already tagged as a building.

My wish then is that if you edit something that is already a building the top search result, when there are more than one results that match your query, should also be a building. The same when you edit a path, the top result should be a path, and not, for example, a crossing. And so on.

I hope my wish was clear. I'm sorry I'm not very good at explaining complicated thoughts in English :)

Thank you so much for all your hard work! Feel free to change the title to make it more clear, if you can/want, or to just tell me it's impossible if it is, or to just explain better :)

**Comment by quincylvania** [comment]
@forteller Thanks, iD should definitely be smarter about this kind of thing, but it doesn't have the data for it yet. I'm going to group this into #4139 since it's about adjusting the preset list based on context.
