### ISSUE TITLE
Add: That address is already in the database warning

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8048]
Long term wishlist (so please don't close the bug that fast):
Add: "That address is already in the database" warning.

This will effectively prevent duplicate addresses from entering the database. A condition which could lead to problems during emergency situations. Thanks.

**Comment by jidanni** [comment]
One might think: "So simple, just look around the street.  It's obvious if you're creating a duplicate address." Well it's not so simple, especially in hilly areas, where the same address might get accidentally entered kilometers away.

**Comment by jidanni** [comment]
Sure, some Twin Towers might share the same address. In this case the user would just click "Yes, I know."

**Comment by TheAdventurer64** [comment]
> Sure, some Twin Towers might share the same address. In this case the user would just click "Yes, I know."

All warnings come with an "Ignore this Issue" button. I personally don't support this issue, as it would be problematic in [these situations](https://www.openstreetmap.org/#map=16/19.4896/-154.9417). I think it would cause a lot of clutter.

**Comment by jidanni** [comment]
I see. All buildings there,
https://www.openstreetmap.org/way/493120847
https://www.openstreetmap.org/way/493120848 ...
have the same address.
OK, maybe have the warning appear only when the address (attempted, not yet saved edits) tally goes from 1 to 2.
Beyond that, 3, 4, 5... assume that users know what they are doing.

**Comment by quincylvania** [comment]
Thanks, we're considering a version of this in #7740.
