### ISSUE TITLE
Save button's yellow color should clear upon resolution of all issues

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8049]
Here we choose "Delete this feature",
![25385-4](https://user-images.githubusercontent.com/1230959/95006534-37db8280-0638-11eb-84f3-6de76cd9c13c.jpg)

OK, that decrements the changes counter, but doesn't clear the yellow color!:
![9380-5](https://user-images.githubusercontent.com/1230959/95006553-635e6d00-0638-11eb-9601-9d3bab24884f.jpg)

(Clicking the Save button now confirms that no other issues were still present.)

**Comment by mmd-osm** [comment]
That color is just a reminder for you to upload your changes. The more changes you made, the more red the background turns. It’s unrelated to the number of issues.

**Comment by quincylvania** [comment]
> That color is just a reminder for you to upload your changes. The more changes you made, the more red the background turns. It’s unrelated to the number of issues.

This is true, but it's also a similar shade of yellow to iD's warnings 🤔

I don't think we need to make any immediate changes, but we can keep this in mind going forward.

**Comment by jidanni** [comment]
That's the first time I've ever encountered gradual color change style warnings/messages. Sounds like an enormous usability issue, to be interpreted by different people in different ways depending on how bright their screen is etc. Sounds like a nightmare.

**Comment by jidanni** [comment]
There really only should be two states, 1: you have things to upload. 2: you don't have things to upload.
As far as warnings,  that should be on a separate indicator,  next to the upload button. Perhaps a red triangle with an exclamation point in the middle.

**Comment by jidanni** [comment]
Indeed, if there's nothing to upload then the upload button could be greyed out. Perhaps it already is,  I'm not at a terminal at this moment.

**Comment by jidanni** [comment]
Anyway , as you can see, users are not going to understand this (Save (/upload) button) as it is currently.

**Comment by quincylvania** [comment]
> Sounds like an enormous usability issue

No, an enormous usability issue would be if people couldn't perform iD's basic functions. The changing button color is purely cosmetic. It's been around for years and this is the first time anyone has reported a problem. It's intentionally subtle until you have lots of unsaved edits.
