### ISSUE TITLE
Mapillary sprite request seems to block map object request

### ISSUE THREAD

**Issue by MRVDH** [openstreetmap/iD#8061]
Mapillary sprites need some time to load when there are a lot of pictures. Requests after that, such as getting ways, points, areas etc seem to load only after the mapillary request has been completed.

![image](https://user-images.githubusercontent.com/6686385/95308835-ab74ce00-088a-11eb-9137-bc7f0595ea81.png)

**Comment by quincylvania** [comment]
@MRVDH This looks like the release version of iD on osm.org? I recently did #7982 which delays loading these photo overlay resources until the mapper enables those layers, instead of always loading them on launch. This makes things more efficient and I believe fixes the problem 👍
