### ISSUE TITLE
Cannot insert a node exactly in the middle of a line if direction marker is present

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8062]
Here, even though the pointer (not shown) is "<+", when we hold it over the edge,
![X3](https://user-images.githubusercontent.com/1230959/95390297-bc275180-0927-11eb-926f-db7ec6ac4aad.jpg)
However, if we hold it exactly on top of any of those four direction arrows (<),
no matter single click, nor double click, there is no way to insert a node in the line there (for no good reason.)
I.e., we cannot insert a node exactly in the middle of a line if a direction marker is present.
We must insert it, oh, at 55/100ths of the line, and the clumsily drag it back to 50/100, usually distorting the line in the process.

**Comment by quincylvania** [comment]
@jidanni Thanks, this is probably #7972, which has been fixed for the next release.
