### ISSUE TITLE
Capacity missing units for water tank

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8078]
Here (for water tank), we see "Height (meters)" but Capacity units is left for a research mission.
![X5](https://user-images.githubusercontent.com/1230959/95873921-f454e700-0da2-11eb-80bf-2074cd5d1515.jpg)
OK, I found [it](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dstorage_tank): capacity in cubic metres...
Consider putting that on the panel like already done for Height. Thanks.

**Comment by maro-21** [comment]
"Capacity" string should be split into multiple strings because the same label is used for example on amenity=restaurant - in my language it's not the same word ("objętość" for storage_tank and "liczba miejsc" for restaurant).

**Comment by karmanya007** [comment]
@jidanni Do i have to change the label in presets.yaml file or fields.json or in capacity.json file??

**Comment by quincylvania** [comment]
@karmanya007 Change the label in capacity.json and then run `npm run build` and commit the derived data as well.

**Comment by karmanya007** [comment]
@quincylvania Thanks 😄

**Comment by quincylvania** [comment]
@karmanya007 Actually, for this you'll have to create a new field like `capacity_volume.json` and leave the existing capacity field alone, since it's used for other things too. Check out the [presets guide](https://github.com/openstreetmap/iD/tree/develop/data/presets#presets).

**Comment by karmanya007** [comment]
@quincylvania Okay. One more thing. Do i have to switch to the dev server on the localhost version?

**Comment by quincylvania** [comment]
@karmanya007 You only have to use the dev server if you need to upload fake data, so probably not for this issue. If you're unsure about something, feel free to open a draft pull request and we can discuss things there.

**Comment by karmanya007** [comment]
@quincylvania I have add the units to both the water tank and the storage tank (They both use the same key=capacity). Is this fine or only the water tank needs the units (cubic meter)?

**Comment by karmanya007** [comment]
@quincylvania [PR Opened](https://github.com/openstreetmap/iD/pull/8112)

**Comment by karmanya007** [comment]
@quincylvania Could you review #8112

**Comment by quincylvania** [comment]
Done by @karmanya007 in #8112.
