### ISSUE TITLE
A water tank holds compressed gases?

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8079]
A water tank holds compressed gases?
![X6](https://user-images.githubusercontent.com/1230959/95874565-970d6580-0da3-11eb-8b8c-66ade95ca8f6.jpg)
Wouldn't that be a gas tank?
(Wait, that's for a car.)
(Well anyway, yes this is indirectly calling the Storage Tank documentation, for Water Tank, so ends up looking funny.)

**Comment by quincylvania** [comment]
Yes, there's not a one-to-one mapping of iD's presets to OSM tags or wiki pages, so little inconsistencies like this happen. I doubt it's preventing anyone from contributing useful data.
