### ISSUE TITLE
Move Imagery Offset higher in Background panel

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8081]
In the Background panel, of these,
- Overlays
- Display Options
- Imagery Offset

I bet Imagery Offset is used 100 times more than the others, so should perhaps be placed above the others.

![14545-1](https://user-images.githubusercontent.com/1230959/95973632-7fd38400-0e46-11eb-8f64-252da040299b.jpg)

**Comment by quincylvania** [comment]
@jidanni While I agree the offset is probably used more than the display options, I'm worried changing the order would be disorienting for longtime users. Plus it doesn't seem that hard to scroll a little bit more. The scroll position persists when closing and opening the background pane as well.

I think we could revisit this as part of a larger redesign of this UI, but I'm not worried about it right now.

**Comment by matkoniecz** [comment]
This display options seem to be used extremely rarely and scrolling to imagery offset is quite annoying
