### ISSUE TITLE
Can't get Street Cabinet preset anymore

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8082]
I don't seem to be able to make new
![1202-6](https://user-images.githubusercontent.com/1230959/95995715-72c58d80-0e64-11eb-81d5-fb1facffb13c.jpg)
anymore. No matter what I type when making a point,
Street....
it can't find it.
(Above I'm showing an existing one.)

**Comment by quincylvania** [comment]
@jidanni Are you setting the preset on a standalone point? I'm not seeing this issue.

![Screen Shot 2020-10-14 at 9 46 27 AM](https://user-images.githubusercontent.com/2046746/95997817-2f3a3780-0e02-11eb-94c8-f6b06c54a1a4.png)

**Comment by jidanni** [comment]
OK it is working again today.
