### ISSUE TITLE
Continue drawing lines and areas from a mid-point

### ISSUE THREAD

**Issue by DujaOSM** [openstreetmap/iD#8088]
Drawing lines and areas from scratch is intuitive and easy -- just go clicking on the map to define successive points. However, if  you have to adjust an existing line or area, the process is much slower: you have to double-click the line or grab an arrow on it to define a new point and move it around, then repeat for every new point - a lot of RSI-inducing mousework.

As an usability enhancement, it would be nice to allow "continuing" existing lines and areas from a mid-point (using "Continue" from context menu or [A] shortcut key). As the result, the selected point can be moved, and any subsequent click would define a new adjacent point, connected to the neighboring points (just as in the current Area drawing mode). 

Currently, I can achieve something similar by cutting [X] the line, then continuing it [A], drawing as much as I want, and connecting it back near the cut point. That, however, is not always feasible due to relation breaking, and may produces some side-effects such as converting areas to multipolygons. 

There are obviously details to work out, but you get the idea...

**Comment by quincylvania** [comment]
@DujaOSM This is a neat idea. I'm not sure how it'd feel in practice but we can look further into it. This and #2272 would probably work the same way.

**Comment by DujaOSM** [comment]
Yes, this is basically a duplicate of #2272 (my search failed to find it), and there are several ideas I like, particularly the @slhh's neat video. The video is probably the best illustration how it should work, perhaps only differing how the action is initiated. There's still an open issue as to direction...

**Comment by quincylvania** [comment]
Okay, I'll close this in favor of #2272.
