### ISSUE TITLE
Handle removal from the DOM when integrated in React apps

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/iD#8090]
We are having some problems when running iD inside Tasking Manager.

What I noticed is that if I have a task open on iD in TM, then I move to another React view and go back (both using the back button or selecting to resume the task), iD will load but won't download the data again. It's working like if we didn't restart iD, but just went back to the instance that were running (although the OSM data is not rendered). Users reported also that if they try to load a neighbour task, iD doesn't download data.

Maybe a solution is to add a destroy action on iD that would remove it from the DOM, like it's explained on: https://reactjs.org/docs/integrating-with-other-libraries.html#integrating-with-dom-manipulation-plugins

**Comment by quincylvania** [comment]
@willemarcel Thanks for opening this, it's a big bug! I wouldn't be surprised if iD isn't caching/uncaching things properly since it hasn't historically been restarted like this, but we'll need to look further into it.

**Comment by jayenashar** [comment]
not sure if it helps, but i've got a related report from a user (@tastrax) of the oceania tasking manager.  he gave me this stack trace.  i checked the network traffic and it looks ok (i.e. nodes before ways from OSM's API).

```
iD.min.js:1 Uncaught Error: entity n7921680851 not found
    at coreGraph.entity (iD.min.js:1)
    at coreGraph.childNodes (iD.min.js:1)
    at osmWay.<anonymous> (iD.min.js:1)
    at coreGraph.transient (iD.min.js:1)
    at osmWay.asGeoJSON (iD.min.js:1)
    at r (iD.min.js:1)
    at Array.filter (<anonymous>)
    at iD.min.js:1
    at Selection.selection_call [as call] (iD.min.js:1)
    at iD.min.js:1
```

**Comment by willemarcel** [comment]
@jayenashar I'm solving it with https://github.com/hotosm/tasking-manager/pull/3792

**Comment by jayenashar** [comment]
fantastic.  i'll pull it into our TM so @tastrax can use it

**Comment by quincylvania** [comment]
> @jayenashar I'm solving it with hotosm/tasking-manager#3792

🕺
