### ISSUE TITLE
NEW TAG 

### ISSUE THREAD

**Issue by lukethemapper** [openstreetmap/iD#8094]
a shop_stairlift tag is needed

**Comment by manfredbrandl** [comment]
already in #8087 please close here

**Comment by manfredbrandl** [comment]
Taginfo show that there are 3 shop=stairlift and 1 show=stairlifts. It may be too early to include this tag into iD.

**Comment by lukethemapper** [comment]
Quite a few round me are tagged as a retail building with the name @manfredbrandl

**Comment by quincylvania** [comment]
Hello and welcome, @lukethemapper. I'm afraid with iD we can really only support presets for tags that are already approved or widely used. If there are lots of these shops near you, I suggest adding the tag manually to promote usage. You might also write a tagging proposal and/or documentation page on the OSM wiki. Until then, we can't take action on iD's side.
