### ISSUE TITLE
Remove `direction_cardinal` field

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#8096]
I added a [new check](https://github.com/openstreetmap/iD/commit/83df29ccf2a123d8295d9dfe536a46418b673461) to the build_data.js script to warn about fields that aren't used by any presets or anywhere else in iD. Looks like the only existing one is [`direction_cardinal`](https://github.com/openstreetmap/iD/blob/develop/data/presets/fields/direction_cardinal.json). I'm opening this issue before removing it since there are lots of translatable values that some downstream iD consumers could possibly be using.

The benefit of removing unused fields is that we won't be asking people to translate the strings for no reason.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/w/index.php?search=direction_cardinal https://taginfo.openstreetmap.org//search?q=direction_cardinal

Seems to be unused, undocumented and without clear purpose. I think that removal is clearly a good idea, even if for some reason translations for this specific tag are used somewhere.

**Comment by quincylvania** [comment]
@matkoniecz To be clear, the field is for cardinal values of the `direction` key: `N`, `S`, `E`, `W`, `NE`…

If iD ever used this field then it must have since been replaced by the numeric direction field, which I contend is easier to deal with anyway.
