### ISSUE TITLE
iD wipes "source:date" tag when "downgrading" an address node with store metadata

### ISSUE THREAD

**Issue by joepie91** [openstreetmap/iD#8097]
Example case: https://www.openstreetmap.org/changeset/92596968

When applying the 'downgrade' action to an address node that also includes other (eg. store) information, it leaves the `source` tag intact but removes the `source:date` tag, which is apparently necessary for those working with BAG (Dutch government) datasets to determine the age of certain information.

I'm guessing that the reason is that iD has `source` in its tag exclude list for downgrading, but not `source:*`. Also keeping any subtags of `source` intact upon downgrading (ie. treating them as address data) seems like a reasonable solution to me, though I realize I haven't worked with OSM much and so there may be issues with that that I'm not aware of.

Edit: Sorry, forgot the platform information. Firefox 81.0 (64-bit), NixOS 20.03 (Linux).

**Comment by quincylvania** [comment]
Hi and welcome, @joepie91. Thanks for bringing up this issue, I've fixed it for today's patch release.

**Comment by joepie91** [comment]
Excellent, thanks!
