### ISSUE TITLE
Prompt: does this power pole also serve as a street lamp? and vice-versa

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8098]
Many power poles [also serve as street lamp poles](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstreet_lamp#Variations_.28not_currently_tagged.29).
Or one could say many street lamps are mounted on [power poles](https://wiki.openstreetmap.org/wiki/Tag:power=pole).

Therefore, in iD, no matter if the user types "Street Lamp" or "Power
pole", there should be a box at the end
[ ] This pole also serves as a street lamp, or
[ ] This pole also serves as a power pole.
Which upon clicking/adding a check mark,
would open up appropriate additional entry fields.

And in the editor, there needs to be a new icon, for such combined poles.

**Comment by matkoniecz** [comment]
Vast majority of power poles are not used as street lamps, the same for street lamps - vast majority are not a power poles

**Comment by DujaOSM** [comment]
FWIW, see the ongoing [Utility poles proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Utility_poles_proposal) on the OSM wiki.

**Comment by jidanni** [comment]
> Vast majority of power poles are not used as street lamps, the same for street lamps - vast majority are not a power poles

Where I live 100% of street lamps are mounted on power poles.
Why (would the utility company) waste a whole new pole when there is a ready made one nearby?
Yes if the power lines are underground then separate light poles would be needed.
Where I live only telephone poles never have street lamps mounted on them,
as the government rules say the systems must be separate (so they don't fail at the same time due to a pole falling down, etc.)

**Comment by quincylvania** [comment]
Hmm this is a tricky situation because it's one structure that's functionally two different things. OSM and iD aren't great about features tagged with multiple types. Closing this since the tagging isn't really settled yet and the iD repo isn't the place to discuss it.
