### ISSUE TITLE
Update NSI to get updates/fixes to suggestions

### ISSUE THREAD

**Issue by rjw62** [openstreetmap/iD#8107]
Currently the iD editor is erroneously suggesting that Tesco Express stores that have corrected tagged with brand:wikidata=Q98456772 should be changed to the less specific brand:wikidata=Q487494. This was an issue in the Name Suggestion Index, but it was fixed in that project there over a month ago. However, iD doesn't seem to have updated from the NSI recently. I'm sure this won't be the only such issue that needs an update from the NSI to fix.

Because of the interface design choices in iD, many users do not bother validating iD's suggestions and just click to apply them without any checks. This puts a lot of responsibility on iD to ensure that these suggestions are always valid. iD must therefore ensure timely updates from any third-party sources that it is relying on for these.

**Comment by quincylvania** [comment]
Hi and welcome, @rjw62. We keep iD up-to-date with all new releases of NSI, but [there hasn't been one since April](https://github.com/osmlab/name-suggestion-index/releases). I don't know the details, but I think NSI has had some internal changes that will make the next release non-trivial. Thanks for your patience.

Closing this since we have #7924 open and there's not a lot we can do on iD's side.

**Comment by rjw62** [comment]
Sorry, but I have to disagree about closing this as a non-iD issue. There is an issue here with iD.

iD has chosen to use a third-party source for suggestions, and presents them in a way that encourages OSM mappers to apply them without checking. It is therefore iD's responsibility to ensure that there are timely re-imports of the source data to correct any issues that occur. If it can't do that, whatever the reason might be, then there either needs to be an over-ride mechanism for iD to stop making specific erroneous suggestions, or more warning to users before they click to apply the suggestions, or iD needs to (temporarily) stop using the source altogether.

Fair enough though, if you want to make these issues part of #7924 instead.

**Comment by quincylvania** [comment]
Okay, I can remove the `wontfix-not-iD` label if it's bugging you.

NSI is one of iD's many dependencies, and the deal with dependencies is that we trust other people to handle parts of our app. Regardless of changes to development branches, v4.0.2 is the current version, thus iD is up-to-date and its suggestions are still considered valid.

I'd imagine a new release is coming sometime soon, in which case I don't think we need to do anything special in iD.

**Comment by tordans** [comment]
For Reference: https://github.com/osmlab/name-suggestion-index/issues/4543
