### ISSUE TITLE
make ID load in a tiny bit faster 

### ISSUE THREAD

**Issue by lukethemapper** [openstreetmap/iD#8118]
**above **

**Comment by quincylvania** [comment]
@lukethemapper Do you mean faster relative to 2.18.5 on osm.org? We've already made a number of startup speed improvements for 2.19.0 🏋️‍♂️

**Comment by matkoniecz** [comment]
@lukethemapper Do you have any specific idea how to do this or noticing cases with unusual slowness?

**Comment by quincylvania** [comment]
@matkoniecz Internet speed is a big factor in startup time, since iD needs to download a few things. I did #7982 and #7994 for 2.19.0, which reduced the initial downloads.

**Comment by lukethemapper** [comment]
@quincylvania I have a new superfast internet and a I5 processor

**Comment by quincylvania** [comment]
I'm just going to group this into #8091…
