### ISSUE TITLE
Custom Background Settings: mention comment syntax

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8120]
In "Custom Background Settings" we see

> Enter a tile URL template below.
> 
> Supported WMS tokens:
> {proj}: requested projection (EPSG:3857 only)
> {wkid}: same as proj, but withou...

All that is great, but let's say we have two frequently used favorite URL templates.
Well, if we could at least know how to comment:
```
<!-- TEMPLATE1 -->
TEMPLATE2
```
Then we wouldn't have to type the whole thing in again when switching.
(Sure, if you would help us keep track of our favorite templates separately, that would even be better. But still, a comment syntax should be documented.)

**Comment by quincylvania** [comment]
@jidanni You already opened #7426 which is about support for multiple custom backgrounds. I'd say let's focus on that solution rather than spending time on an advanced workaround. You can always just keep your endpoints in a notes files separate from iD and copy-and-paste them as needed.

**Comment by jidanni** [comment]
OK, but,
1. There is plenty of room in that box for comments:
![11220-3](https://user-images.githubusercontent.com/1230959/97180344-e6f12100-17d4-11eb-87d8-f51d54911582.jpg)

2. Nobody gets it right at the first attempt,
so there should always be room for comments:
```
# https://{switch:a,b,c}.mmmr.openstreetmap.org/{zoom}/{x}/{y}.png
# https://{switch:a,b,c}.pppz.openstreetmap.org/{zoom}/{x}/{y}.png
https://{switch:a,b,c}.tileqq.openstreetmap.org/{zoom}/{x}/{y}.png
```
without having to resort to Notepad etc.

**Comment by quincylvania** [comment]
If someone wants to open a PR for this then that sounds okay. But it takes real work to build and maintain features and unfortunately we don't have the resources to do something just because there's space for it.

**Comment by jidanni** [comment]
(OK, but pssst... tell me the comment syntax. I mean there is already fancy preprocessing  of those URLs, so I bet you guys didn't forget to add one... Or just add `{ignore: ..............} `.)

**Comment by quincylvania** [comment]
@jidanni There is no comment syntax. You paste in a URL, we replace the tokens with the parameters, and that's it. "URL comments" aren't really a thing.

**Comment by jidanni** [comment]
Every 'language' needs them,
https://stackoverflow.com/questions/2524367/inline-comments-for-bash
Anyway with `{comment: ..............}` syntax, iD could have them too in a jiffy!

**Comment by quincylvania** [comment]
@jidanni I thought this went without saying but it's just a URL input box, it's not a bash script.

**Comment by tordans** [comment]
This thread got me thinking: One could miss-use a hash-syntax to kind off comment out parts of an URL. I don't think its really useful, but it does work :-).

Format: 

`URL1#URL2`
And to switch the URL, I can manually copy-paste the URL to `URL2#URL1`.

Example: 

Input for the custom map dialogue:
`https://isk.geobasis-bb.de/ows/dop20c_wms?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=bebb_dop20c&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}#https://isk.geobasis-bb.de/mapproxy/dgm/service/wms?FORMAT=image/jpeg&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=dgm&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}`

As an URL:
https://www.openstreetmap.org/edit#background=custom:https://isk.geobasis-bb.de/mapproxy/dgm/service/wms%3FFORMAT%3Dimage/jpeg%26TRANSPARENT%3DTRUE%26VERSION%3D1.1.1%26SERVICE%3DWMS%26REQUEST%3DGetMap%26LAYERS%3Ddgm%26STYLES%3D%26SRS%3D{proj}%26WIDTH%3D{width}%26HEIGHT%3D{height}%26BBOX%3D{bbox}%23https://isk.geobasis-bb.de/ows/dop20c_wms%3FFORMAT%3Dimage/png%26TRANSPARENT%3DTRUE%26VERSION%3D1.1.1%26SERVICE%3DWMS%26REQUEST%3DGetMap%26LAYERS%3Dbebb_dop20c%26STYLES%3D%26SRS%3D{proj}%26WIDTH%3D{width}%26HEIGHT%3D{height}%26BBOX%3D{bbox}&disable_features=boundaries&map=18.60/52.41051/12.54939

**Comment by jidanni** [comment]
See @quincylvania, without a documented comment syntax, users will hack up their own, doubling the size of each request ☹☺
