### ISSUE TITLE
Edit (this feature) should always zoom in to a piece of a (O, U. V shaped) feature

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8122]
1. Visit https://www.openstreetmap.org/way/863780195
2. Click "Edit" in the upper right.
2. Click "+ Zoom in to edit."

As you see the feature we wanted to edit is very much off the screen.

OK, let's try again, crafting this URL on our own,
https://www.openstreetmap.org/edit?way=863780195

OK, that's better. But still, then pressing "+ Zoom in to edit" puts the
feature off the map.

Conclusion: iD should detect that we have a /way/ in the URL,
and assist us in finally getting to edit that way.

E.g., we just want to change a tag of the entire way. Well, iD should be
sure that a piece of the way still shows up on the screen.

One could say there is no easy way iD could zoom in to the center of a (large) U or V
or O shaped way, and still show a piece of it.

Well in this case then don't just always zoom in to the center.

(Another idea might be adding a fourth item to this menu:
![28813-0](https://user-images.githubusercontent.com/1230959/97258307-23fbf880-1853-11eb-9b2d-c9b3c7ee6ea1.jpg)
called "Edit this feature.")

**Comment by quincylvania** [comment]
For this we could try to have iD select the feature even if you're zoomed out, so that it will appear without needing to zoom in at all.
