### ISSUE TITLE
Bug: If you put a tag on a road, and you then suddenly click away, you'll get this:

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#8126]
![image](https://user-images.githubusercontent.com/50059322/97377738-b40b6380-188e-11eb-90da-78da37bea7ac.png)

**Comment by quincylvania** [comment]
@TheAdventurer64 Thanks for reporting, I just fixed this in b2582dcf9e8498b1f3675122e4ad1ee68b6d6e82. It's a nasty bug so I'll push out a patch.

Screenshots are helpful, but they're not always self-explanatory. In the future I'd ask please describe the actual problem as well.
