### ISSUE TITLE
Misrendering of large relations (line placed where multipolygon has no border)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#8129]
I searched for https://github.com/openstreetmap/iD/issues?q=is%3Aissue+large+relation because I though that it may be reported/WONTFIXed already

Open https://www.openstreetmap.org/edit?editor=id#map=18/54.43957/19.61258 and note water area rendering that is misplaced from actual https://www.openstreetmap.org/relation/8140878#map=15/54.4400/19.6196&layers=N

![screen06](https://user-images.githubusercontent.com/899988/97427436-cd56f300-1914-11eb-8cb9-3609f87a6d0a.png)

EDIT: Right - incomplete, not large.

**Comment by quincylvania** [comment]
@matkoniecz Thanks, this is #1201. The rendering of incomplete multipolygons is a longstanding issue with no clear solution aside from always downloading the full data.
