### ISSUE TITLE
v2.19.0 Allowed Access adds [object Event] = yes tag

### ISSUE THREAD

**Issue by gregcrago** [openstreetmap/iD#8130]
I have NoScript 11.1.4 installed, but disabled.
I found a PATH that did not have foot=yes tag, so I normally use ALLOWED ACCESS and select YES for FOOT. Normally all settings are GHOSTED. Upon fist try, I noticed [object Event]=yes and the YES in ALLOWED ACCESS is still GHOSTED. I tried again and I get an additional [object FocusEvent] = yes added to the tags and I get a UNGHOSTED YES in ALLOWED ACCESS box. If I select anything else, I noticed the UNGHOSTED foot=yes in ALLOWED ACCESS box disappears.

**Comment by tordans** [comment]
@gregcrago this sounds like https://github.com/openstreetmap/iD/commit/24ad7fcb820c74647d67d37fd880b6a24fbc797e

**Comment by quincylvania** [comment]
Yep, this is #8126 and was fixed in the 2.19.1 patch. @gregcrago Try reloading the page and check the bottom corner—iD should be updated.
