### ISSUE TITLE
Map data not loading while editing.

### ISSUE THREAD

**Issue by gmckone** [openstreetmap/iD#8131]
While completing a HOTOSM task. (this has happened before). 
link to page: https://tasks.hotosm.org/projects/9677/map/?editor=ID#background=Maxar-Premium&gpx=https://tasking-manager-tm4-production-
api.hotosm.org/api/v2/projects/9677/tasks/queries/gpx/%3Ftasks%3D1663&map=18.80/2.16804/35.41325 
Working in Google Chrome. (logged into OSM/ HOTOSM.)
Google Chrome is up to date
Version 86.0.4240.111 (Official Build) (64-bit)
Browser extensions I have include:
adblock plus, Grammarly, bit.ly, 1password, bot sentiel,

The screen loads with the pink boundary for the task and a black background. (no imagery) So I press "B" and load up the Maxor premium imagery as requested in the task.
The imagery loads up and I see an area I was viewing several minutes ago.  I recall that this area has a path mapped (previously) and also a path mapped by myself just minutes ago.  But I see no OSM map data, just the pink.
When I check my settings (B) I see map data is enabled.  The task is not locked by anyone else as far as I can tell. (it allowed me to choose the task).

The bug is that while editing I don't see map data. 
1. I'm in danger of recreating it.
2. I can't reference what has been completed.

See partial screenshot to understand what is visible.
![image](https://user-images.githubusercontent.com/195155/97471702-3aaf5780-1906-11eb-8e7d-8ebde08235ea.png)

See the background / data settings here.
![image](https://user-images.githubusercontent.com/195155/97471863-68949c00-1906-11eb-820e-f4daf45c018a.png)

See the data settings here.
![image](https://user-images.githubusercontent.com/195155/97471931-7d712f80-1906-11eb-93ec-f95ffd9f9367.png)

after typing this entire entry, I reloaded the screen F5 and saw this.
![image](https://user-images.githubusercontent.com/195155/97473148-e60cdc00-1907-11eb-9ee4-6cd8e4d7463c.png)

So... while a reload didn't seem to work at the beginning, it did work eventually.
I'm going to still submit this bug because something went wrong and I've seen this behaviour before.

I hope this is a helpful bug report.
Thanks.
Greg.

**Comment by quincylvania** [comment]
Greetings and welcome, @gmckone. We've been monitoring this issue over at #8090. I've been working with @willemarcel to resolve this on the Tasking Manager side and I think we're pretty close.

Closing this as a duplicate.

**Comment by gmckone** [comment]
Thank you quincylvania I appreciate the link to the issue. Great news!
