### ISSUE TITLE
Mouse hover in dropdown no longer highlights the relation

### ISSUE THREAD

**Issue by DujaOSM** [openstreetmap/iD#8134]
Another apparent 2.19 regression:

When i want to add an object to a relation, and hover the mouse pointer over the list of available ones, they are no more highlighted blue (or was it yellow?). Used to work fine in 2.18, and was immensely helpful to identify the desired relation. 
![NoRelationHighlight](https://user-images.githubusercontent.com/48584318/97559102-4b7ecc80-19dd-11eb-8ee1-d5d27a700802.png)

**Comment by quincylvania** [comment]
Thanks for reporting, @DujaOSM. I'll ship a patch out today for this.
