### ISSUE TITLE
Shortcuts missing - 2.19.2

### ISSUE THREAD

**Issue by tastrax** [openstreetmap/iD#8137]
When you initially go into the shortcuts (?) the browsing shortcuts appear but if you click on editing or tools, they disappear, never to return

![image](https://user-images.githubusercontent.com/8775395/97646149-08872c80-1aa3-11eb-9adc-e413b88e91e5.png)

![image](https://user-images.githubusercontent.com/8775395/97646165-1937a280-1aa3-11eb-82ee-26da3f81f619.png)

**Comment by tastrax** [comment]
Shortcut key ? also fails

**Comment by quincylvania** [comment]
@tastrax Thanks for reporting!
