### ISSUE TITLE
iD adding tags  [object Event]   [object FocusEvent] - cleanup necessary

### ISSUE THREAD

**Issue by mueschel** [openstreetmap/iD#8142]
SInce a few days iD users have added hundreds of objects with two obviously wrong keys:

[object Event]
[object FocusEvent]

This happens world-wide and by more than 100 different users:
http://overpass-turbo.eu/s/Zzb

This needs to be cleaned up in the database.

**Comment by RAytoun** [comment]
This is probably where that key originated ... https://wiki.openstreetmap.org/wiki/Key:object

**Comment by mueschel** [comment]
No, this is #8130, but the damage to the database needs to be repaired as well.

**Comment by RAytoun** [comment]
OK. Thank you for clearing that misunderstanding.

**Comment by quincylvania** [comment]
Unfortunately I think we have to remove these tags entirely since we can't be sure what key the mapper intended.

**Comment by zdila** [comment]
> Unfortunately I think we have to remove these tags entirely since we can't be sure what key the mapper intended.

I think we should also comment those changesets so that mappers would be aware of this and would have a chance to re-add correct tags.

**Comment by quincylvania** [comment]
Looks like someone must have taken care of this since I'm seeing no results in the overpass query now.
