### ISSUE TITLE
Show what changes are suggested along with the apply button rather than hiding what changes will be done by default

### ISSUE THREAD

**Issue by lgommans** [openstreetmap/iD#8143]
![being asked to apply unspecified changes](https://user-images.githubusercontent.com/5626710/97785000-d5c45d80-1ba2-11eb-976d-f5683e70904d.png)

Rather than asking people to apply unspecified changes and requiring an extra click to see what change you will be making, iD should show what tagging changes it is proposing. Honestly, nobody should be clicking automatic edit buttons unless it's an approved import and their click is part of that approved process, but these tag upgrades are not an import or they could be done mechanically. I'm not proposing an annoying confirmation pop-up or anything, just fold out the proposed changes by default so people can tell, often at a glance, if it is expected and good.

![expanded](https://user-images.githubusercontent.com/5626710/97785025-f5f41c80-1ba2-11eb-94b5-4b4f8e61ba8b.png)

The sentence "Some features should have additional tags." seems redundant to me, if we want to save some space while we're at it. The info button could be made into a collapse symbol or removed altogether since people can collapse the Issues section if they don't want to see this.

If there is no objection, I could write a patch to resolve this issue.

**Comment by lectrician1** [comment]
I like this. I would prefer this format better:
![image](https://user-images.githubusercontent.com/22477298/97808775-6b58ff00-1c2e-11eb-9503-046f4090de96.png)

**Comment by lgommans** [comment]
@lectrician1 I would like that format too!

**Comment by maro-21** [comment]
I support this change, because I always click [i] button to expand even though I am experienced with the tags and I usually know what is going to change.

**Comment by quincylvania** [comment]
Welcome, @lgommans. I think #6408 covers this…
