### ISSUE TITLE
Empty shortcuts menu

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8149]
When I press [?] I can see the first of three menus, but when I click "Modifying" or "Tools", the menu disappears.

![help menu](https://user-images.githubusercontent.com/57260466/97812855-ae45c180-1c84-11eb-9c09-2515c9851b9b.png)

**Comment by tordans** [comment]
Same for me in German.

**Comment by quincylvania** [comment]
Thanks, this is #8137.
