### ISSUE TITLE
point-area merge action is not discoverable

### ISSUE THREAD

**Issue by jups23** [openstreetmap/iD#815]
Inexperienced users make a point for a village, add data to it. Later, advanced mappers want to make it correct and mark the area of that village and have to transfer data. 
Therefore it would be nice to have a comfortable way to copy that data from the point to the area or be able to turn a point into an area.

**Comment by polarbearing** [comment]
This is bad editing style anyway. 
It would be better to keep the node alive so it can be used prominently, e.g. as the entrance. This preserves the history of the node and makes the changeset better reviewable.

**Comment by bhousel** [comment]
> It would be better to keep the node alive so it can be used prominently, e.g. as the entrance. This preserves the history of the node and makes the changeset better reviewable.

Hey @polarbearing - you are commenting on a very old issue!
Since #3683, iD does now preserve the history of the merged node.

**Comment by BjornRasmussen** [comment]
Isn't this fixed by the new ribbon UI?

**Comment by quincylvania** [comment]
@BjornRasmussen Good find! The Merge operation is now shown in the toolbar when a point and area are selected, so I think that's more discoverable. See #6680.
