### ISSUE TITLE
warehouses should have telephone number prompts

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8150]
We are prompted to fill in the address of
https://wiki.openstreetmap.org/wiki/Tag:building=warehouse
but how about also telephone numbers?

This is important info for hazards teams too.  

Workaround:
1. Enter details
2. Switch to corporate office
1. Enter phone number
2. Switch back to warehouse

**Comment by maro-21** [comment]
I don't agree. I think only POIs can have phones. Building=warehouse is just a building. If there is a phone, it should be connected to a company (shop / office).

**Comment by jidanni** [comment]
@maro-21 , the bug spray company's office is in Taipei.
But they have five warehouses scattered around the country.
They don't have any shops. They are B2B, not B2C.
The do have a factory though, in Kaohsiung.
