### ISSUE TITLE
× button in multiple selection list selects the feature instead of deselecting it

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8151]
If you select multiple features and click the ✖️ button on one of the rows in the list of selected features, that feature should be deselected, leaving the rest of the features selected. Instead, iD selects only the feature corresponding to that row, deselecting the others.

**Comment by quincylvania** [comment]
@1ec5 Thanks for reporting. I wasn't seeing this problem in Firefox 82, but I imagine some browsers might treat nested buttons differently. I un-nested them.
