### ISSUE TITLE
Tags disappear from the editor

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8155]
How to reproduce the bug:
- Add gas station
- add fuels
- add payment types
- select any other feature and select this gas station again
- the tags are still there but not in the editor.

![gas_station](https://user-images.githubusercontent.com/57260466/97910287-d5b29200-1d49-11eb-8fb0-46a49190ca3a.png)
----
after:
![gas_station2](https://user-images.githubusercontent.com/57260466/97910301-d814ec00-1d49-11eb-9585-7a09f323158d.png)

**Comment by MakiWolf** [comment]
It also affects other categories
![grafik](https://user-images.githubusercontent.com/73300633/98407381-d9a72280-206f-11eb-807c-966e197a4761.png)

**Comment by quincylvania** [comment]
@maro-21 Thanks for reporting! This regression was most likely introduced in 2.19.0.
