### ISSUE TITLE
Can't enter name:xxx in Multilingual Name box

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8165]
Here on the right (another browser window, looking at OSM.ORG, and a different place), we see `name:hak`,
![16674-3](https://user-images.githubusercontent.com/1230959/98177476-aceef000-1f35-11eb-8ab8-ab8f88256bab.jpg)

OK, but try as we might, there is no possible way to be able to get that on the left.
Any attempt at `hak` becomes `Hak`, and other weird languages are suggested to us instead.

The only way to enter it would be manually way down in the Tags box.

Wait, even before we tamper with the Tags box, now having a second look, the box has turned into
![19960-4](https://user-images.githubusercontent.com/1230959/98177750-461e0680-1f36-11eb-8afa-0018fa722461.jpg)

OK, that is good. But we will still have to change it by hand in the Tags box at the bottom, from Hak, to hak.

Anyway, we see the "supreme difficulties" involved in getting our [hak](https://en.wikipedia.org/wiki/Hakka_Chinese) language name entered.

Wait! After entering it in Tags, presto,
![30047-5](https://user-images.githubusercontent.com/1230959/98178360-89c54000-1f37-11eb-82d5-0eb2f7194c0c.jpg)
it turns out iD knew about what we wanted all along. It just wasn't in the prompting!

**Comment by quincylvania** [comment]
In cc1e512f445c8f5a51caa4f8c91085c20b8a2991 I added this and a lot more languages that iD previously had translations for in English but weren't shown in the dropdown.

**Comment by soshial** [comment]
Do you mind adding these Kartvelian languages as well:
* https://en.wikipedia.org/wiki/Mingrelian_language
* https://en.wikipedia.org/wiki/Laz_language
* https://en.wikipedia.org/wiki/Svan_language
* https://en.wikipedia.org/wiki/Judaeo-Georgian
