### ISSUE TITLE
Translate description for "YouthMappers de Universidad de Costa Rica" to English

### ISSUE THREAD

**Issue by magol** [openstreetmap/iD#8168]
The description for "YouthMappers de Universidad de Costa Rica" is written in Spanish when it should be in English.

https://github.com/openstreetmap/iD/blob/8ecb98323bbec077dc072dd7d8e7316f31238ff6/dist/locales/en.json#L13162

**Comment by jjiglesiasg** [comment]
Why?, Universidad de Costa Rica is the correct name of the institution. We do not translate University of Oxford or Yale, or so, because those are the Correct Names in their Languages, Why Universidad de Costa Rica needs to be Translated to English?

 

I don’t see the rationale behind this request…

**Comment by maro-21** [comment]
> Why?, Universidad de Costa Rica is the correct name of the institution. We do not translate University of Oxford or Yale, or so, because those are the Correct Names in their Languages, Why Universidad de Costa Rica needs to be Translated to English?

Not the name of the university, but the **description** which is entirely in Spanish and translators translate strings from English.

**Comment by magol** [comment]
@jjiglesiasg The name should not translate as you say. But the description must be translated as all other strings are i English in en.json. I have updated the title of this issue to point out this.

**Comment by jjiglesiasg** [comment]
Agree… BsRgds

**Comment by quincylvania** [comment]
Thanks, @magol. This data is actually handled over at the [osm-community-index](https://github.com/osmlab/osm-community-index) so you'll need to open the issue there.

**Comment by magol** [comment]
Thanks @quincylvania 
I have created a new issue: https://github.com/osmlab/osm-community-index/issues/386
