### ISSUE TITLE
Copy and paste from nsi.guide

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#8176]
I wanted to copy and paste a brand from nsi.guide which wasn't yet in iD, e.g. "brand": "Bannatyne Health Club". Unfortunately that means a little bit of extra work changing the colon into an equals sign so that iD recognises it as a tag/value pair in the tag text area.

So my suggestion would be to recognise a colon and space or two spaces as a separator along with "=". That would also allow copying a list of tags from an object on osm.org

**Comment by bhousel** [comment]
I just changed the formatting on https://nsi.guide so tags can be easily copied into iD now.

**Comment by boothym** [comment]
Thanks!
