### ISSUE TITLE
Use local osm data in iD editor 

### ISSUE THREAD

**Issue by amiormu** [openstreetmap/iD#8177]
Hello, it's a great honor to use such excellent code.

As the scientific research needs to extract the road by AI, we need to develop the map editing system based on local OSM data. At present, we have successfully modified the API for obtaining road information into our own API and obtained the road information and tags under the longitude and latitude.

However, when our results are displayed on the website, there are no different styles of rendering.

What is the problem? How to realize the rendering of different ways? Is there a problem with the format of the tags we responded to the API? Or other key issues that I didn't find.

Looking forward to your reply

**Comment by DujaOSM** [comment]
It sounds as if you are in a wrong place. iD is only an editor for the OpenStreetMap database. Apparently, you want to change rendering of the map, which is done by different software pieces entirely. 

The default OSM renderer is called "OSM Carto", and its repositories are located at https://github.com/gravitystorm/openstreetmap-carto There are numerous other renderers around, as well as extensive tutorials how to roll or fork your own.

**Comment by quincylvania** [comment]
Welcome, @amiormu, and thanks for the kind words.

Could you include a screenshot to show what you're seeing?

**Comment by amiormu** [comment]
Thank you for your quick reply！:)
Here are a few screenshots of mine.
My road looks like this in the browser:
<img width="357" alt="1" src="https://user-images.githubusercontent.com/35089815/99643412-9abd9780-2a87-11eb-9bb4-a7ea8472a6f9.png">


My response is like this:
<img width="727" alt="WX20201110-221831@2x" src="https://user-images.githubusercontent.com/35089815/99644100-7910e000-2a88-11eb-8a13-5a07ac8298ce.png">

The road has a tag:"highway:residential", but it doesn't show on the browser.




> Welcome, @amiormu, and thanks for the kind words.
> 
> Could you include a screenshot to show what you're seeing?

**Comment by quincylvania** [comment]
Hmm it's sort of hard to say what's going on since I'm not sure what you changed. But one thing is that iD expects the `id` of entities to be strings prefixed with a letter for the type, like `n49120400`, `w69600304`, `r689293292`.

The map styling is managed in CSS using classes calculated in [this file](https://github.com/openstreetmap/iD/blob/develop/modules/svg/tag_classes.js), so you can try tracing that code if no classes are added.
