### ISSUE TITLE
The purpose of multiple index.html files

### ISSUE THREAD

**Issue by theshem** [openstreetmap/iD#8179]
I've been trying to understand the reason of having multiple `index.html` files in the project but I couldn't figure it out. There are two files, [one at the root](https://github.com/openstreetmap/iD/blob/release/index.html) of the project and the other in `dist` folder.

I was thinking if the [`dist/index.html`](https://github.com/openstreetmap/iD/blob/release/index.html) is somehow generated from the other one but it seems that's not the case. Would you clarify please?

Besides, in `dist/index.html` file the following [line](https://github.com/openstreetmap/iD/blob/release/dist/index.html#L36) that confused me:

```js
// currently all minified files are legacy ES5 because of uglifyJS
newScript.src = isIE11 ? 'iD.min.js' : 'iD.min.js';
```

So the `iD.js` file is not being used at all? Why is this line written like this?

P.S. the html files are not following the contribution guide for 4-space indentation.

**Comment by quincylvania** [comment]
Hi and welcome, @theshem. 

> I was thinking if the dist/index.html is somehow generated from the other one but it seems that's not the case.

Nope, these look similar but are both manually-maintained. I honestly don't know why there are two index files though. Any insight, @bhousel?

> So the iD.js file is not being used at all?

iD.js is used by the index.html file at the root level for local development. The minified file takes too long to build and makes debugging much harder.

> Why is this line written like this?

The line is supposed to reinforce the idea that iD.min.js is compatible with legacy browsers, I think.

> P.S. the html files are not following the contribution guide for 4-space indentation.

Yeah, the indentation guideline must be outdated.

**Comment by bhousel** [comment]
> Nope, these look similar but are both manually-maintained. I honestly don't know why there are two index files though. Any insight, @bhousel?

Not sure.. #464 suggests that it was so that the root html file could be more for our internal use, having a dev/prod source switcher and raw code, and the `dist/` html file is more for consumers, no source switch and minified code only.

**Comment by theshem** [comment]
Thank you for the response @bhousel @quincylvania

I was going to change the build system to split the iD bundle into separate chunks (having `[hash]` in filename) for better caching in production. Therefore, I needed to know which `index.html` file is the one. I can send a PR if you will.

Should I open a new issue to ask further questions regarding the code splitting?

**Comment by bhousel** [comment]
> Thank you for the response @bhousel @quincylvania
> 
> I was going to change the build system to split the iD bundle into separate chunks (having `[hash]` in filename) for better caching in production. Therefore, I needed to know which `index.html` file is the one. I can send a PR if you will.
> 
> Should I open a new issue to ask further questions regarding the code splitting?

It's probably fine to ask them here, but I wouldn't spend time on code splitting.  
There are plenty of other important bugs to fix or more impactful features to deliver.
