### ISSUE TITLE
Already selected key-value pairs do not appear in selection menu

### ISSUE THREAD

**Issue by rene78** [openstreetmap/iD#8180]
_service:bicycle:repair_ and _service:bicycle:retail_ don't appear in selection menu, even though they are in the key-value list for the node. 

Problem appears on this node:
https://www.openstreetmap.org/node/371237899

![Unbenannt](https://user-images.githubusercontent.com/36115705/98481398-49491900-21fa-11eb-8d17-0e6c7170a1af.png)

**Comment by maro-21** [comment]
It's already been fixed in https://github.com/openstreetmap/iD/issues/8155.

**Comment by rene78** [comment]
Thanks @maro-21! Gonna close the issue.

**Comment by quincylvania** [comment]
Yep, I'll push out a patch with this fix today or tomorrow.
