### ISSUE TITLE
Missing catalan community info after a successful edition

### ISSUE THREAD

**Issue by jmaspons** [openstreetmap/iD#8181]
After editing with iD, no info about the [catalan community](https://wiki.openstreetmap.org/wiki/WikiProject_Catalan) is shown.

We have the following channels:
- Telegram -> https://t.me/osmcat
- Twitter -> https://twitter.com/OSMcatala
- Mail list -> https://lists.openstreetmap.org/listinfo/talk-cat
- Facebook -> https://www.facebook.com/OSMcatala

And we work on this area https://osm.org/relation/11747082

I have no experience with js but if somebody points me to the relevant files, I can try to do a merge request replicating how other communities are included

**Comment by maro-21** [comment]
You should open an issue here: https://github.com/osmlab/osm-community-index

**Comment by quincylvania** [comment]
Welcome, @jmaspons. Like @maro-21 indicated, the communities are handled at the community index project and you can find more info there about how to open a pull request.

**Comment by jmaspons** [comment]
Thanks for the tip! Pull request at #osmlab/osm-community-index/pull/387
