### ISSUE TITLE
Lines mapping in OpenStreetMap

### ISSUE THREAD

**Issue by EliLardieri** [openstreetmap/iD#8186]
I'm not able to map streets in OpenStreetMap because I don't see line types in the element selection (as in the image attached). I tried to write both in italian and in english, but nothing appears in the list on the left.
<img width="1414" alt="Schermata 2020-11-09 alle 12 09 09" src="https://user-images.githubusercontent.com/74185168/98534821-58c17400-2285-11eb-8489-318702ae2b46.png">

**Comment by lectrician1** [comment]
https://www.reddit.com/r/openstreetmap/comments/jq4p41/hot_tasking_manager/?utm_source=share&utm_medium=ios_app&utm_name=iossmf 

See this.

Close this issue.

**Comment by EliLardieri** [comment]
Thank you so much lectrician.

**Comment by quincylvania** [comment]
Welcome, @EliLardieri. #7767 is about avoiding this type of confusion.
