### ISSUE TITLE
Don't interpret click-and-drag as a click when in move mode

### ISSUE THREAD

**Issue by ghost** [openstreetmap/iD#8187]
It might be difficult to find the right way to handle this given the various HID methods iD supports, but if it can be improved I think it would be worthwhile. I decided to open this ticket after not finding either an open or closed issue about this specific behaviour using the issues search, but my perusal was not exhaustive so it's possible I missed it and this is a duplicate.

Expected behaviour:
1. I select an entity or several entities and then press `m` or otherwise enter move mode.
1. After moving my pointer and the entity/ies along with it to where I want it, then I click to exit move mode and place the entity/ies.
1. Between the first and second steps, I pan as normal in order to reach the target area, including 'grabbing' the map with click-and-drag.

Observed behaviour:
1. I select an entity or several entities and then press `m` or otherwise enter move mode.
1. I go to pan the map, but rather than waiting to exit move mode until my click has released and seeing if the on-click is at a sufficiently far offset from the off-click to determine whether the action was a click or click-and-drag, the initial click exits move mode.
1. I thus must alternate between moving the entity/ies across the viewbox using move mode, and panning/zooming the map so that the entity/ies are still in the viewbox but there is now again room to move them in the desired direction.

I imagine there is an analogous algorithm for touch interaction, but I could be wrong about that; and I saw in one of the issues that modeless touch moving was and/or is a goal.

**Comment by quincylvania** [comment]
Hmm I see how this is annoying. It's definitely not intended (and might be a regression). We should be able to patch it.

**Comment by lectrician1** [comment]
Something related, has it ever been thought of to make right-click the panning tool? Typically most vector-art editors and other types of software do this.

**Comment by quincylvania** [comment]
Looks like this probably wasn't a regression. Definitely a nice usability improvement.

> Something related, has it ever been thought of to make right-click the panning tool?

@lectrician1 Not sure, but iD has to be more beginner-friendly than most vector software. It's a web map—people are used to clicking and dragging them to pan around. We also don't expect every map to have a two button mouse.

**Comment by ghost** [comment]
Thanks [@quincylvania] for the fix and [@mbrzakovic] for deploying it! I am enjoying the new functionality.
