### ISSUE TITLE
How accurate is the line length measurement?

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8193]
How accurate is the line length measurement in iD?

**Comment by quincylvania** [comment]
@maro-21 I'm not sure! It's just a quick reference for armchair mapping. I wouldn't use it for surveying, navigation, or anything important. It's calculated with [d3.geoLength](https://github.com/d3/d3-geo/blob/master/README.md#geoLength) and is called here:

https://github.com/openstreetmap/iD/blob/82bce000b0dad8a30ee32ebee9bd7b06cab56dd5/modules/ui/panels/measurement.js#L80-L81

Are you seeing nonsensical results?

**Comment by maro-21** [comment]
> Are you seeing nonsensical results?

Not exactly. I didn't even say that measurements are wrong. I've been adding some linear objects with a known length, but the measurement was always longer in iD. For a 70 meters long line, in iD it was around 5 meters longer, so just wanted to know what measurement error [±n] is.
