### ISSUE TITLE
closed: Fixed

### ISSUE THREAD

**Issue by lukethemapper** [openstreetmap/iD#8194]
images below

**Comment by lukethemapper** [comment]
![screenshot-www openstreetmap org-2020 11 13-08_22_08 (1)](https://user-images.githubusercontent.com/72900280/99045650-937b2300-2589-11eb-8c6c-55d9caeb0dfc.png)

![screenshot-www openstreetmap org-2020 11 13-08_22_08](https://user-images.githubusercontent.com/72900280/99045653-94ac5000-2589-11eb-9dc6-2bed7b3b37c0.png)

**Comment by lukethemapper** [comment]
and lots of other features have the same issue

**Comment by quincylvania** [comment]
@lukethemapper I can't reproduce this issue. Are you working on osm.org? Do they appear if you reload the page?

**Comment by lukethemapper** [comment]
They didn't (also i work on osm.org)

**Comment by quincylvania** [comment]
@lukethemapper What browser are you using? Do you see any [console errors](https://appuals.com/open-browser-console/)?
