### ISSUE TITLE
Local presets

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8197]
Is it already possible or would it be possible to do: local preset - a preset visible only in a given city, region or country?

I know that it's possible to exclude a preset in some countries - but is it possible to do something opposite?

**Comment by lectrician1** [comment]
What are you proposing? Most tags are made to correlate to specific features throughout the world, irregardless of region.

**Comment by quincylvania** [comment]
@maro-21 iD's presets already support this at the country level. The name-suggestion-index has [incorporated a mechanism](https://github.com/osmlab/name-suggestion-index/blob/main/CONTRIBUTING.md#features) for specifying custom smaller regions that we'll probably also incorporate into iD's presets.

> Most tags are made to correlate to specific features throughout the world, irregardless of region.

@lectrician1 This is true, and would be the ideal, but unfortunately there are some irregularities between some countries in OSM.
