### ISSUE TITLE
Add suggestion alias for amenity=vehicle_inspection : "MOT testing centre"

### ISSUE THREAD

**Issue by Nekojimi** [openstreetmap/iD#8208]
In the UK, the mandatory vehicle inspection test is commonly known as the "[MOT test](https://en.wikipedia.org/wiki/MOT_test)", and so testing centres are often called "MOT centres", and signed as such. It took a lot of typing and searching on the wiki to find amenity=vehicle_inspection, so I think this would be a good tag suggestion.

**Comment by bhousel** [comment]
I've added "mot test" and "mot centre" as search terms for this preset in the `en-GB` localization.
https://www.transifex.com/openstreetmap/id-editor/translate/#en_GB/presets/156857821?q=text%3A'vehicle+inspection'

**Comment by Nekojimi** [comment]
That was quick! Thanks!
