### ISSUE TITLE
UX problem in the background shortcut modal

### ISSUE THREAD

**Issue by Suburbanno** [openstreetmap/iD#8221]
Hi!
it is impossible to close the modal, as the control panel is overlaying the X button

![image](https://user-images.githubusercontent.com/13632826/100263526-62f19c80-2f2c-11eb-94b4-697e2abc004d.png)
when using any control panel option, the modal is pushed aside and you can see the X button
![image](https://user-images.githubusercontent.com/13632826/100263664-916f7780-2f2c-11eb-8135-40fcf4add16c.png)

**Comment by quincylvania** [comment]
Welcome, @Suburbanno. This is #7133.
