### ISSUE TITLE
Add "Undo all", "Redo all" buttons

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8222]
Let's say for some reason we want to "Undo all."
![12545-9](https://user-images.githubusercontent.com/1230959/100268733-63238380-2f90-11eb-884d-9f4a6c17ea7a.jpg)
Well I tried it starting at the state in the picture, and it took about 20 clicks.
All that clicking doesn't seem too scientific.
Therefore perhaps add an "Undo all" button somewhere on the interface.

Don't worry, with an additional "Redo all" button nearby it, nobody would ever lose any work.

**Comment by quincylvania** [comment]
If you want to reset everything then you can just reload the page and click "Discard my changes" when iD offers to restore your work. I don't think we need dedicated buttons for destructive and relatively uncommon actions.
