### ISSUE TITLE
`M` to move has no effect on a single node / Hard to precisely act upon overlapping nodes

### ISSUE THREAD

**Issue by jleedev** [openstreetmap/iD#8225]
Steps to reproduce:
1. Find an intersection where multiple roads come together, and select it.
2. Press <kbd>D</kbd> to disconnect the ways.
3. Attempt to drag one particular road away from the intersection

Expected results: I can easily choose which node/way I want and drag it away from the intersection. I should be able to select the way I'm interested in, then hop to the intersection and act upon that way's node there. Or, I shift+drag to select all the nodes, then choose the one I want and act upon it without my selection changing further. Being able to select the proper node and press <kbd>M</kbd> to move it would solve this.

Actual results: iD seems to pick one node at the intersection and stack it on top, and requires me to drag that node away first, or it appears to behave randomly. Eventually I just drag the entire intersection apart and reassemble the ways I didn't need (but to be fair, I'd have to reattach them anyway).

Having multiple nodes that are on top of each other may be a weird edge case in saved map data, but it's easy to produce when attempting to disconnect an intersection.

Other ideas that would address this:
- When a way is selected, dragging overlapping nodes should prefer the nodes that belong to the way, not other nodes
- When a node is selected, dragging that node should not change the selection to some other coincident node

**Comment by DujaOSM** [comment]
This seems to be the same as #8174 and #7984.

**Comment by quincylvania** [comment]
Yeah this is #8174. But we can also make the Move operation work for a single node, that's a separate issue.
