### ISSUE TITLE
Warn about tagging used on wrong geometry

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#8231]
Dear maintainers,

It seems that iD currently doesn't check for tagging versus geometry used. I don't blame anyone on this, it's only an opportunity to propose something that could improve data quality and offer better guidance to iD users.
A quick look at existing issues didn't find duplicate of this problem

Some OSM tags are only valid on nodes, like barrier=block
https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dblock

Using such tags on a way, area or relation should raise a warning as to encourage mappers to check documentation and change their topology.

Similar situation exist with highway=primary for instance, only valid on ways.
Using it on a node should raise a warning as well

This is related to #6779 with power=transformer and transformer=* that are only valid on nodes.
Current usage of 14 500 power=transformer and 5 800 transformer=* on ways are errors but iD users may be not aware of this.

All the best

**Comment by quincylvania** [comment]
Sure, iD flags a few "Mismatched Geometry" situations already so it would be nice to be more encompassing.

**Comment by quincylvania** [comment]
Okay, I think I added all the remaining combinations of mismatched points/vertices/lines/areas. These might need some tweaking but will make for some useful checks.

![Screen Shot 2020-12-04 at 4 26 19 PM](https://user-images.githubusercontent.com/2046746/101216419-7815ac00-364d-11eb-9881-aa999e6dbd4e.png)

**Comment by flacombe** [comment]
Thank you Quincy, how fast you are :+1:

**Comment by quincylvania** [comment]
> Thank you Quincy, how fast you are 👍

Sometimes!
