### ISSUE TITLE
Unable to drag nodes at the bottom of the screen

### ISSUE THREAD

**Issue by jgscherber** [openstreetmap/iD#8233]
The imagery attribute tag is contained in a DIV element that blocks mouse events from reaching the map layer. See images. This is in Firefox v. 84.0b7 (64-bit)

### DIV vertical space
![div_location](https://user-images.githubusercontent.com/6207661/101190553-20ac1780-361e-11eb-9859-e44ac5065ea7.png)

### Click-and-drag selects text instead of grabbing node
![misgrab](https://user-images.githubusercontent.com/6207661/101190564-2570cb80-361e-11eb-8e3b-66becdf8e66b.gif)

### Cursor change when dragging node over the effected area
![cursor-change](https://user-images.githubusercontent.com/6207661/101190578-29045280-361e-11eb-81f0-053b07d0b88f.gif)

**Comment by quincylvania** [comment]
@jgscherber Thanks, I think this is the same underlying issue as #8192.

**Comment by quincylvania** [comment]
Actually, #8192 was two parts, but I fixed this part in 67773d12a82033c30cf4804db93a6a5ebe7fcdd9.
