### ISSUE TITLE
Duplicate way bug

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/iD#8236]
A few months ago I was trying out the v3 editor. I must have fixed some issues about footways crossing highways without being connected.

Today, I look at Osmose and Osmose tells me that 2 ways I edited produced 2 exact way geometries and tags on top of each other. The nodes for the ways were connected.
![image](https://user-images.githubusercontent.com/22477298/101269308-63134880-3733-11eb-9f08-29b4097210e1.png)
_The two ways_

Changeset:
https://osmcha.org/changesets/84280014

The iD version was `iD 0328e10`.

**Comment by quincylvania** [comment]
@lectrician1 While relatively stable, that v3 prototype was never "finished" and may have bugs. We've stopped development of that branch, so I'm closing this unless you've seen this bug on a release version of iD.
