### ISSUE TITLE
Name-suggestion-index preset pack

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#8237]
Following #8229, iD now fetches preset data at runtime instead of bundling it with the release. The name-suggestion-index maintains its own presets, and has started generating iD-compatible files (see https://github.com/osmlab/name-suggestion-index/issues/4718). We need to update iD to integrate presets from multiple sources.

**Comment by bhousel** [comment]
Yep!  My plan is to get this into RapiD and then send a PR your way 👍
