### ISSUE TITLE
Divide only one of the roads at an intersection

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8247]
Yes there probably is a way to divide only the east-west road, or only the north-south road, but it is not obvious.
![20201213T232128](https://user-images.githubusercontent.com/1230959/102016110-2af6b000-3d9a-11eb-84c2-07f45c908197.jpg)
So some tip should appear.

**Comment by jidanni** [comment]
I already clicked the east-west road before I clicked the point.
So that should be remembered.
If I really want to also divide the north-south road, I could do that in a subsequent step.

**Comment by jidanni** [comment]
I suppose the only way to only divide the east-west road, would be a hack: make a new node a little bit away from the intersection...
![20201213T232846](https://user-images.githubusercontent.com/1230959/102016305-339bb600-3d9b-11eb-9b18-fc687e3bd457.jpg)
And then drag it back,
![20201213T232959](https://user-images.githubusercontent.com/1230959/102016321-51691b00-3d9b-11eb-998a-b21127a71547.jpg)

**Comment by lectrician1** [comment]
Or there could be a prompt ask the user which ways they want to split (or disconnect too), before they actually split. 

I agree the current implementation isn't intuitive.

**Comment by IgorEliezer** [comment]
Select the way; hold Shift-key down; right-click the node where you want to split the selected way at; use scissor.

Using shift-key limits the edition to the selected ways only.

**Comment by quincylvania** [comment]
> Select the way; hold Shift-key down; right-click the node where you want to split the selected way at; use scissor.
> 
> Using shift-key limits the edition to the selected ways only.

Yep, this is the way to do it. This workflow is documented in the Operations section of the Help pane.

**Comment by jidanni** [comment]
OK. (But I observe that Shift normally is for when you want to operate on two things at once.
Here it is for when you don't want to operate on two things at once!!)

**Comment by quincylvania** [comment]
> Here it is for when you don't want to operate on two things at once!!

@jidanni You need to have both the line and the point selected. These are two things.

**Comment by jidanni** [comment]
All I know is I first click the line (only one of the two lines) then I click the point..
