### ISSUE TITLE
Help user type the "+" in phone numbers

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8248]
All the world's phone numbers should start with a "+"...

Well, currently the user will still have to type it in themselves.

Couldn't it be already sitting in the textbox?

Sure the user could delete it if they really want to.

I'm not talking about this grey stuff that disappears,

![20201213T233940](https://user-images.githubusercontent.com/1230959/102016559-8f1a7380-3d9c-11eb-9c79-15eb62d3c615.jpg)

I'm taking about a real black "+" sign.

**Comment by quincylvania** [comment]
> All the world's phone numbers should start with a "+"...

It's common to leave off the calling code in many countries in OSM, so not everyone would want this.

You already opened #6713 about a calling code dropdown. Please don't open duplicate issues about the same thing

**Comment by jidanni** [comment]
> It's common to leave off the calling code in many countries in OSM,

I never knew that, as I only map in the same one country.
https://wiki.openstreetmap.org/wiki/Key:phone is rather complex to read too.

Anyway that is great news. No more typing +886 each time. The computer can add it if needed. That's how Google Maps does it.
