### ISSUE TITLE
User clicks single choice, destroying it

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8249]
If the user chooses "Upgrade tags" here,
![20201213T233803](https://user-images.githubusercontent.com/1230959/102016690-12d46000-3d9d-11eb-8b20-ba8a7f0b241e.jpg)

The next thing they will see is the Yamaha logo. 
![20201213T233829](https://user-images.githubusercontent.com/1230959/102016706-2aabe400-3d9d-11eb-8774-374fa7eb1a64.jpg)

"Yes, that's the correct one!" they think. So they click it, and...
![20201213T233849](https://user-images.githubusercontent.com/1230959/102016753-68107180-3d9d-11eb-908b-e80988861533.jpg)
Disaster strikes! They are getting deeper and deeper in trouble. Yamaha: gone.  Motorcycle: gone. Now it might as well be a pizza shop.

Sure, they shouldn't have clicked it.  They should have realized "Feature Type" is special... They should have "quit while still ahead" (at the casino.)

Anyway, I'm just worried that some older users will get fooled this way. Well, at least there is an Undo button. Better than Las Vegas :-)

**Comment by quincylvania** [comment]
This is just the UI working as expected… I don't really see how we can do this better right now.

Feature Type tells you what the entity is. Clicking the button means you want to change it. Mappers are expected to learn this early on.

The list of quick fixes under the warnings pretty much all work instantly. If you click one and the issue disappears, then you don't have to do anything else to solve the issue.

And as you said, you can easily recover here if you click the wrong thing. Nothing is "destroyed".
