### ISSUE TITLE
Automatic undo when modifying a polygon to a bad polygon as first change triggers save

### ISSUE THREAD

**Issue by boxer4** [openstreetmap/iD#8250]
Normally when one tries to move a node of a polygon such that it crosses itself (bad polygon), iD will reject that change and return the node and polygon to the original shape.  However I've noticed that it still records that something got changed and allows one to "save" the change despite it rejecting that change.  I dared not to try saving it to see what was actually in the change buffer whether the illegal node move/bad polygon will get saved or not, despite the GUI returning the polygon to its original geometry.

It did report the area got changed in the changelist so something is there, whether it's a null move or not, I can't tell without actually saving.  The expected behavior is that illegal node moves that got undone by iD should not count as a node move and should not trigger a changeset that needs to be uploaded.

This is with Firefox 68.12 if it matters.

**Comment by quincylvania** [comment]
Hi and welcome, @boxer4. I'm not seeing this, but I'm running Firefox 83 so something may have changed. Can you link to a feature that has this behavior?

**Comment by boxer4** [comment]
Strange, I am not able to reproduce this morning either with as far as I can tell, the same conditions other than whatever version of the software my browser picked up.  I'll go ahead and close and mark as an invalid bug for now, not sure what triggered this problem, last night was the second time I was able to trigger the issue but now I'm unable to.  Thanks.
