### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#8251]
A lot of the time when I go to save an edit iD Editor will load the OpenStreetMap login screen in a new window and either just not except my login details, give a page not found error, or it will just be blank page. It shouldn't be asking me for my login details to save an edit when I'm already logged in. Let alone error out when it does. BTW, I'm using Chrome. 

![Screenshot 2020-12-14 033328](https://user-images.githubusercontent.com/30259065/102077252-d402d200-3dbd-11eb-9058-de41c35eb33a.png)

**Comment by zaizone** [comment]
Same issue with firefox on the main editor (https://www.openstreetmap.org/edit#map...). I have just tested with the OSMfr version (https://id.openstreetmap.fr) and it does the same thing

**Comment by rene78** [comment]
Same problem here. Those are the error messages that I get:
![image](https://user-images.githubusercontent.com/36115705/102079624-55358580-3e0d-11eb-8be2-996e7d82a74a.png)
![image](https://user-images.githubusercontent.com/36115705/102079750-84e48d80-3e0d-11eb-9050-c6746dd60c64.png)
Looks like OSM server error, I guess.

**Comment by mmd-osm** [comment]
Yes, OAuth on the Rails port appears to be broken. Issue belongs to https://github.com/openstreetmap/openstreetmap-website

**Comment by Adamant36** [comment]
> Yes, OAuth appears to be broken. Issue belongs to https://github.com/openstreetmap/openstreetmap-website

I was thinking it was probably something with the website. There should still be a clear consistent error message on Id Editors side if nothing else though.

**Comment by mmd-osm** [comment]
It started about an hour ago:

![image](https://user-images.githubusercontent.com/5842757/102080176-4a2f2500-3e0e-11eb-8d62-2c1f5f709c61.png)

**Comment by mmd-osm** [comment]
Follow up in https://github.com/openstreetmap/operations/issues/480

**Comment by rene78** [comment]
Wonder whether it is related to what is happening to many Google services at the moment. GMail, YouTube and many others are down as well...

**Comment by mmd-osm** [comment]
Should be fixed now.

**Comment by mmd-osm** [comment]
ok, let's close this. It was unrelated to any Google issue by the way.

**Comment by quincylvania** [comment]
@mmd-osm Thanks for the info! Glad this was fixed quickly and wasn't iD.

**Comment by Adamant36** [comment]
Would it be possible to have a connection error or something on iD Editor's side when it can't save instead of just a blank pop up window?

**Comment by quincylvania** [comment]
@Adamant36 There're some improvements in #7850.
