### ISSUE TITLE
Mapillary picture viewer not working properly

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#8257]
In the mapillary viewer, seems that no sequence of pictures could be seen once pressed the play button. Individually each picture open, but there is NO play option slower or faster.

This problem is also common to RAPID, as well.

**Comment by nickplesha** [comment]
@jjiglesiasg Try clicking on the button just to the right of the "move forward" at the top of the viewer. This should expand a drawer with a couple of extra options. One of these is the speed setting ("rabbit" icon) which opens up a slider that allows you to choose the playback speed for when you press the "play" button.

<img width="186" alt="Screenshot 2021-04-15 at 14 36 48" src="https://user-images.githubusercontent.com/3823786/114870123-184bc080-9df8-11eb-9447-7a102eedd17a.png">

**Comment by nickrsan** [comment]
Hi all, I'm triaging the backlog of issues in this repository - are you still having this problem with the mapillary viewer? I'm not able to reproduce this now, so it was likely fixed or possibly limited to the browser. If you'd like this issue reopened, please comment back here, or open a new issue with as many details as possible. Thanks!
