### ISSUE TITLE
iD 2.19.5 cannot distinguish gas station and c-store with the same name

### ISSUE THREAD

**Issue by cicku** [openstreetmap/iD#8271]
I'm having this issue for multiple gas brands in the US:

Here is the reproduction: https://imgur.com/a/Pabf2TN

When two kinds of places share the same name, iD cannot pick up the one I clicked. And reselect category from "Feature Type" does not help. I can only bypass this weird behavior by deleting tag first then reselect the correct type of feature.

**Comment by matkoniecz** [comment]
See also #8304 - it affects even cases where someone have not selected brand at all, just typed name in different shop type
