### ISSUE TITLE
For the past few weeks I've observed significant delay in map updates appearing in the tiles.

### ISSUE THREAD

**Issue by papac25** [openstreetmap/iD#8272]
For the past few weeks I've observed significant delay in map updates appearing in the tiles.
While lately updates appeared in the matter of minutes (satisfying, helpful to spot mistakes, great in mapping events), currently some changes do not appear for days.
This does not seem to be local browser cache related, as dropping the cache and trying other browsers shows the same effect.
Example area - https://www.openstreetmap.org/#map=18/57.07964/24.32793 had footways and other detail added yesterday, still not showing up.

__Originally posted by @richlv in https://github.com/openstreetmap/operations/issues/489__

**Comment by tas50** [comment]
This doesn't seem related to iD. Rendering of tiles on openstreetmap.org happens independently of anything iD does. iD is just sending changesets to the OSM API. As the operations staff point out in that thread there is a high level of tiles updates waiting in the queue which impacts the time it takes to update views.
