### ISSUE TITLE
objets without main tag (only name/source)

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/iD#8273]
https://www.openstreetmap.org/changeset/96660672
objets doesn't have any main tag, only a name/name:fr/source
validator should warn the user to add a main tag (amenity, shop, craft, ....)

**Comment by quincylvania** [comment]
Looks like the `name:fr` tag is silencing the warning. We should give iD more info about tags that are only attributes. We can never be comprehensive though, since anyone can make up a new primary tag at any time.
