### ISSUE TITLE
Network field should not lowercase its value

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8275]
As of ea4b30d12bc951473cc11981c7706a4e28a5ba5b, the Network field for the Road Route and Cycle Route relation presets automatically lowercase their contents, even though the `network` and `cycle_network` keys often need to be set to an all-caps value like [`US:OH:SCI`](https://wiki.openstreetmap.org/wiki/Tag:network%3DUS:OH:SCI). It doesn’t reproduce for the most common values of `network` or `cycle_network` that initially appear in the dropdown.

**Comment by bhousel** [comment]
Yes the fix is the same as what I said on https://github.com/openstreetmap/iD/issues/8609#issuecomment-891205853
