### ISSUE TITLE
Encourage smaller/more localised changesets?

### ISSUE THREAD

**Issue by smopucilowski** [openstreetmap/iD#8277]
When reviewing history at osm.org, it is not uncommon to see changesets that span the entire world. Frequently these are made by the iD editor at osm.org. (Recent example: https://www.openstreetmap.org/changeset/96809971 )

Given changesets should be localised and small (experts will know when to violate this), it would be nice to suggest to commit changes before working on a different area: that is, track modifications and warn when it looks like they're far away.

**Comment by pnorman** [comment]
My experience is that iD's workflow tends to encourage small changesets already

**Comment by maro-21** [comment]
Duplicate of https://github.com/openstreetmap/iD/issues/7434

**Comment by quincylvania** [comment]
> Duplicate of #7434

Yep, see this and #5424.
