### ISSUE TITLE
Render hiking route relations

### ISSUE THREAD

**Issue by Mashin6** [openstreetmap/iD#8283]
This one is similar or in some way an upgrade to this: #659 

New users often add color or name of hiking route to the name field of the footway/path/road itself. One reason is that they want to have it shown in default OSM map, but also often they don't even know that there is a relation hiding on that path.

I would imagine that at some close enough zoom level iD would render a parallel line in color of the route (either taken from osmc:symbol or color tags) next to the path/footway itself. If the way is part of multiple relations then multiple parallel ways would be shown. Something similar what ["OSMC hiking"](https://josm.openstreetmap.de/wiki/Styles) mapstyle for JOSM is doing.

<img src="https://user-images.githubusercontent.com/5265707/103694947-c1695c00-4f69-11eb-8c4f-e497e249d1d1.png" width="500" />

bonus: nice would be also to show the name of the trail from relation name tag
bonus2: to have two color routes (blue_red::blue_stripe:red_rectangle) rendered as alternating two-color dashed line

**Comment by quincylvania** [comment]
Thanks @Mashin6, I'd consider this part of #659 but we'll keep these ideas in mind.
