### ISSUE TITLE
Enable Maxar imagery in v3 preview site

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#8285]
Please, consider enabling Maxar imagery in the v3 preview site (https://preview.ideditor.com/master/).

Until now the alternative was to use RapiD/Esri editor (based on v3 with Maxar) but it seems to be down after Rapid 1.1.0 added Esri dataset capabilities.

Thanks.

**Comment by diegokrein** [comment]
The version of Mapwith.ai (https://mapwith.ai), the one implemented by ERSI with version 3 of the ID editor, was very good for completing the map, until it stopped working. The link is: https://mapwith.ai/rapid-esri#background=Maxar-Premium.

I would like version 3 of the ID editor to be implemented. It allows you to reduce the editing time, or map more terrain features, in the same time.

**Comment by arch0345** [comment]
The v3 instance referenced in this issue was removed in https://github.com/openstreetmap/iD/issues/9295
