### ISSUE TITLE
Internationalize the key binding for selecting a parent way

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8298]
ddf868221a893c528454a510188dfcac48bce606 changed the key binding for selecting a parent way (#8264) from ⌘↑ to <kbd>|</kbd> and made it so that repeatedly pressing <kbd>|</kbd> would toggle between a vertex and its parent way. <kbd>|</kbd> makes some sense on an English QWERTY keyboard, where `|` is strongly associated with `{` and `}`, but it’s problematic for users of other languages and keyboard layouts. For example, among Mac keyboard layouts:

* Belarusian, Russian, Serbian, Ukrainian – ⇧⌥1 requires three fingers
* Croatian, Slovene – ⇧⌥Ž requires three fingers on two hands
* French (AZERTY) – ⇧⌥L requires three fingers on two hands
* German (QWERTZ), Finnish, Spanish – ⌥7 requires two hands and is difficult to touch-type
* Italian, Macedonian, Norwegian, Swedish – **no way to type `|`**
* Polish – ⌥9 requires two hands and is difficult to touch-type
* Romanian – ⇧⌥Ț requires three fingers on two hands

⌘↑ would’ve been more universal while remaining reasonably intuitive to English speakers. It could’ve formed part of a system of arrow shortcuts for navigating “up” and “down” among nodes, ways, and relations. It would be pretty straightforward to restore ⌘↑ as an alternative key binding for <kbd>|</kbd>, but it wouldn’t make sense to keep the toggling behavior with ⌘↑ – it would be necessary to introduce a ⌘↓ as well. Separate ⌘↑ and ⌘↓ shortcuts would be easier to describe in help than the current <kbd>|</kbd> toggle.

**Comment by quincylvania** [comment]
@1ec5 Thanks for this followup, I did read your [feedback](https://github.com/openstreetmap/iD/pull/8264#issuecomment-755600345) and definitely think we need to resolve this before release!

**Comment by mbrzakovic** [comment]
Thanks @1ec5 on incredible descriptions, and for ensuring iD accessibility. I agree with your proposal above.
