### ISSUE TITLE
iD craftily changes POI type

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8304]
I just typed the name of a butcher shop and after it, I clicked somewhere and the butcher shop was magically changed to a shoe shop with Russian name. WTH?
iD didn't even ask me if there are some "missing tags", just changed it.

![Marko](https://user-images.githubusercontent.com/57260466/104960007-aec43d80-59d3-11eb-859c-b35cef739995.png)
![Marko2](https://user-images.githubusercontent.com/57260466/104960013-b4218800-59d3-11eb-9bbb-65bee614d0fa.png)

**Comment by matkoniecz** [comment]
I can confirm that it happens. As workaround limited to iD - one may user raw tag editor.

**Comment by matkoniecz** [comment]
Seems to be #8271

**Comment by quincylvania** [comment]
> Seems to be #8271

Sounds likely.
