### ISSUE TITLE
Remove changes before save

### ISSUE THREAD

**Issue by Wassini** [openstreetmap/iD#8312]
Before saving some changes it would be nice to undo/delete a specific change.

**Comment by manfredbrandl** [comment]
Often a specific change can only be undone with all following changes also become undone.

**Comment by Wassini** [comment]
OK - but it is not even possible to discard ALL changes. You are forced to save it or it will stay on the list forever.

**Comment by matkoniecz** [comment]
> You are forced to save it or it will stay on the list forever.

You can reload browser tab and select option to discard changes or simply undo all of them.

**Comment by quincylvania** [comment]
Hello and welcome @Wassini. We're tracking this issue at #3445. I agree it would be a useful feature, but a complex one to implement.
