### ISSUE TITLE
Add support water=oxbow in presets

### ISSUE THREAD

**Issue by fqdb** [openstreetmap/iD#8314]
Please consider adding water=oxbow in the preset picker, just like for lake, pond, reservoir etc.

`natural = water`
`water       = oxbow`

https://wiki.openstreetmap.org/wiki/Tag:water%3Doxbow 

![image](https://user-images.githubusercontent.com/2826336/105628226-092e2580-5e3c-11eb-87c4-a02694fe0881.png)

**Comment by matkoniecz** [comment]
Note that if this is/should be defined in presets (rather than from taginfo suggestions) then you should likely report it at https://github.com/openstreetmap/id-tagging-schema instead, tagging presets are/were separated into that repository.
