### ISSUE TITLE
Support for region selecting polygons

### ISSUE THREAD

**Issue by ManDay** [openstreetmap/iD#8316]
I had to map a few hundred houses and I thought I can do this by pressing *3*, clicking around the outline of the building, pressing *enter*, clicking besides the building to deselect, and repeat. Then later, I wanted to bulk-select all the polygons I had so created and assign feature type "House", move them to account for the imagery offset, and make the corners rectangular. Only then I found no way to select all the polygons other than by Shift-Clicking them individually (due to being a bit clumsy, I once lost my meticulously prepared selection of hundreds of houses when accidentally clicking somewhere -- touchpad -- but that's another story).

It would be nice if I could have selected the polygons with a region selection. Similar to the Shift-dragging out a region which, however, only selects all points (which I could not work with).

**Comment by manfredbrandl** [comment]
Did you try to use the Lasso (Hold Shift and the mouse button) and move around all the newly created buildings?

**Comment by ManDay** [comment]
Yes, that's is what I meant by "Shift-dragging out a region". This selects the nodes, not the polygons. I can neither set a feature type nor can I orthogonalize the corners that way.

**Comment by 1ec5** [comment]
As a workaround, you can select the parent ways of those nodes using the shortcut added in #8264. This shortcut will be available in the next release, or you can [use the latest development mirror](https://ideditor.netlify.com/).

**Comment by ManDay** [comment]
I don't think that's a workaround; I find that a great solution. In my opinion this issue can be closed.

**Comment by quincylvania** [comment]
Yep, we should have a better solution for this. Line and area selection with the lasso tool is #7375.
