### ISSUE TITLE
Add Aerial Imagery of Uruguy(Ortofotos 2018-2019 (IDEuy)) to imagery.json

### ISSUE THREAD

**Issue by c-leitner** [openstreetmap/iD#8317]
In 2019 the Oriental Republic of Uruguay has released all of the Orthophotos under their [open data license ](https://www.gub.uy/agencia-gobierno-electronico-sociedad-informacion-conocimiento/comunicacion/publicaciones/licencia-datos-abiertos-uruguay-0). Therefore I think it would a good idea to add them one of the default imagery sources when editing in Uruguay. WMS is with EPSG:3857 available.
More info here: [https://wiki.openstreetmap.org/wiki/Aerial_imagery#Uruguay](https://wiki.openstreetmap.org/wiki/Aerial_imagery#Uruguay)
[WMS Link](https://mapas.ide.uy/geoserver-raster/ortofotos/ows?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=ORTOFOTOS_2019&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox})

**Comment by matkoniecz** [comment]
If I am not mistaken, iD takes aerial layer info from https://github.com/osmlab/editor-layer-index  (seems confirmed by https://github.com/openstreetmap/iD/search?q=Editor+Layer+Index ) - so it should be changed there

**Comment by c-leitner** [comment]
Thank you! I will report it there.
