### ISSUE TITLE
iD should not merge two segments if one of them have a note and the other does not have that

### ISSUE THREAD

**Issue by cicku** [openstreetmap/iD#8323]
Could it be a suggestion or not, but I'd like to say that iD should not merge two segments if one of them has a note (but the other one does not have it). The note is important but others may not be able to notice before any merging attempt. If these two are merged, it could bring more issues.

There might be some better tags to prevent that happening, but I could not find any so far.

**Comment by mxdanger** [comment]
Any merging is done by a user operation by pressing <kbd>C</kbd>. It would be unintuitive for ways or nodes with `note=*` to be excluded from being merged.

**Comment by quincylvania** [comment]
@cicku Can you give some examples of features with notes where merging would cause problems? Many types of edits could change the meaning of certain notes. But notes are really meant for humans and not for software, so I'm inclined to leave this up to mappers rather than block common operations out of an abundance of caution.

**Comment by boothym** [comment]
I suppose this could be a problem with any tag which is present on one segment but not on the other, e.g. lit=yes on a road when merged with another road that does not have a lit= value.

**Comment by cicku** [comment]
I failed to have a clue after submitting the issue.

My original thought was, for some tags, when one has and some other do not have, are being merged together, a warning or error should be thrown out.

But it turns out that it is a broad topic...

**Comment by quincylvania** [comment]
Okay, the existing behavior has been in place for years, so I'm inclined to leave it as-is unless some concrete problems arise.
