### ISSUE TITLE
"Connect the feature" repurposes stop node

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#8326]
reported in the RapiD repo here: https://github.com/facebookincubator/RapiD/issues/194
The "connect this way" validation should avoid repurposing an existing node with interesting tags.

> Situation:
> I had a place where there was a road that crossed a footpath and there was no node so RapiD warns that the two ways cross without a node - all good.
>
> The Issue:
>When I click on the "Connect the features" it took a stop node on the road that was close to the crossing and moved it and made it into a crossing (and stop) node.
>
>What I expected:
>I would think that we would not want to combine stop and crossing nodes when connecting ways since the stop is specific to the car navigable highway and should not be on the pedestrian highway because there is no stop on the pedestrian way. I think that a new node should have been created at the intersection with highway=crossing and then the stop node should have been left alone.

cc  @atiannicelli

**Comment by jleedev** [comment]
Unfortunately, this was desirable behavior when connecting a `footway=crossing` way to a `highway=crossing` node.

![image](https://user-images.githubusercontent.com/23022/111473682-afdac800-8701-11eb-9d75-3c6dc9486bc0.png)

**Comment by bhousel** [comment]
> Unfortunately, this was desirable behavior when connecting a `footway=crossing` way to a `highway=crossing` node.

good point - I can revisit it and maybe do something a bit better.
