### ISSUE TITLE
iD breaks public transport relations on way split

### ISSUE THREAD

**Issue by Janjko** [openstreetmap/iD#8330]
Public transport routes have ways in a particular order, and when you split one of those ways, iD can put the new way inside that relation in the wrong order. It depends on the direction of the way you are splitting.

I tried to test it, and I chose a way with two routes, each in a different direction. I split a way in the middle of the routes, and it put the new part of the split way on the wrong side of the old part of the split way, in both routes. So it broke both routes. But then I reversed the way I was splitting, and then it put the new split way on the right side, in both relations. I expected iD to break only one route each time, but it seems to be a bit more complicated.

Anyway, this bug is breaking a lot of public transport routes around the world, and it should be fixed fast.

**Comment by Janjko** [comment]
I am willing to bet the issue #8286 is also caused by this bug. I tried the same procedure on a boundary, and it also reversed ways depending on the direction of the split way.

**Comment by Janjko** [comment]
There is an old issue, probably also related to this #4876. It seems this bug has been breaking public transport relations and administrative borders for years.

**Comment by bhousel** [comment]
Yes, see #4876
