### ISSUE TITLE
Improve the opening hours preset, like in StreetComplete

### ISSUE THREAD

**Issue by letypequividelespoubelles** [openstreetmap/iD#8339]
As iD is a "beginner" OSM editor, I think the opening hours preset is a bit difficult to apprehend. Maybe it could be easier if there was a screen to help ? The StreetComplete quest "What are the opening hours of " is a very good example of easy and complete ux. Screenshots are below.
![photo_2021-02-01_19-03-58](https://user-images.githubusercontent.com/54240434/106499032-5d7e7880-64c0-11eb-95d7-a39788fe1276.jpg)
![photo_2021-02-01_19-04-04](https://user-images.githubusercontent.com/54240434/106499041-60796900-64c0-11eb-85ce-a2ef6dcdb410.jpg)

If it's more complex (ie differs for months) we can specify it :

![photo_2021-02-01_19-04-10](https://user-images.githubusercontent.com/54240434/106499049-62432c80-64c0-11eb-8354-d3c364f6b34c.jpg)
![photo_2021-02-01_19-04-14](https://user-images.githubusercontent.com/54240434/106499057-640cf000-64c0-11eb-8090-6e461aa31897.jpg)

Thanks everyone for maintaining iD ! :)

**Comment by mxxcon** [comment]
Or show UI similar to https://projets.pavie.info/yohours/

**Comment by quincylvania** [comment]
@letypequividelespoubelles Thanks, this is #974.
