### ISSUE TITLE
Moving a point moves not the point of the selected line

### ISSUE THREAD

**Issue by martinstingl** [openstreetmap/iD#8343]
Steps to Reproduce:
1. Select a way
2. Right click on a point
3. Split
4. Right click on the point
5. Disconnect

6. Select one one of the two splitted ways
7. Click on the endpoint and try to move this point

Result: The endpoint of the other way on the same position is moved instead of the point of the selected way.

Sometimes iD moves the point of the right line, then choose the other line to produce this behaviour.

**Comment by quincylvania** [comment]
Hi and welcome, @martinstingl. We're tracking this over at #8174.
