### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by GamerInTheGame14** [openstreetmap/iD#8350]
When trying to use iD offline, the presets.min.json file gives error like this, '**_invalid json response body at http://localhost/dist/presets.min.json reason: Unexpected token < in JSON at position 0_**"  but there is no < symbol in that file

**Comment by matkoniecz** [comment]
What you are exactly trying to do? iD is not capable of working offline without internet connection (from what I know).

Are you maybe trying to run iD locally? Have you followed https://github.com/openstreetmap/iD#installation ?

**Comment by GamerInTheGame14** [comment]
Firstly I did not know that iD is not capable of working offline. But now know and trying to run it locally, thanks

**Comment by quincylvania** [comment]
Welcome, @GamerInTheGame14. iD is a web app that downloads data on startup and throughout use, even if you're running it locally. I think you can use [JOSM](https://josm.openstreetmap.de) for some types of offline editing, but you will still need Internet access for download and upload of edits. If you're just trying to install iD, see [our guide](https://github.com/openstreetmap/iD#installation).
