### ISSUE TITLE
Don't require the user to "+ Zoom to edit" if they simply changed some tags

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8353]
1. Visit https://www.openstreetmap.org/edit?way=863780195
2. In the left panel, change some tags.
3. Press Save.

Alas, at this point, we can't save... because we have to first push "+ Zoom to edit", as a mere formality.

We did nothing on the map. All we did was change some tags in the left panel. But the map needs to be zoomed, before we can proceed.

OK, we  push "+ Zoom to edit" (which in fact zooms to the centroid, of our L-shaped object, i.e., so now it is completely off the map. Invisible. But at least we can now proceed with our save. Total user experience: very bad.)

It is good that we were able to change the tags without needing to first press "+ Zoom to edit".
The goodwill should extend to also being able to save the edit.

**Comment by maro-21** [comment]
It works for me. You should type a comment to save, that's all.

**Comment by jidanni** [comment]
Odd, works OK now.
