### ISSUE TITLE
Typo in Estonian translation of unmarked cycleway crossing.

### ISSUE THREAD

**Issue by kallejre** [openstreetmap/iD#8363]
I became so annoyed by a small typo that decided to open issue for that.

* **Current behaviour:** Preset that corresponds to tags `crossing=unmarked; cycleway=crossing; highway=cycleway` is listed in Estonian locale of iD as "Märgista**matta** lõikumine (jalg- ja) jalgrattateega".
* **Expected behaviour:** Correct name of preset should be "Märgista**mata** lõikumine (jalg- ja) jalgrattateega"
* **Possible solution:** Locate translation file and remove unnecessary `t`.

**Comment by mbrzakovic** [comment]
https://github.com/openstreetmap/id-tagging-schema/blob/main/dist/translations/et.json
line: 1785

**Comment by kallejre** [comment]
Thanks for reply mbrzakovic. I red through that translation file and noticed few more issues (line numbers are listed at beginning of each):

* Line 621 - (Parking type options) "Angaar" sounds bit misguiding, implying parking is located within hangar. ~~Sadly wiki doesn't have page for that tag, so i don't know more appropriate translation.~~ Wiki does have photo on a [archived proposal](https://wiki.openstreetmap.org/w/index.php?oldid=1351413#How_To_Tag) page and i also looked up streetlevel images of parking sheds in [neighbouring countries](https://cdn.discordapp.com/attachments/428214296695144458/813854750902452275/unknown.png), but still have no idea what it is.
  *  Missing translation for rooftop parking. Fix by adding: `"rooftop": "Katusel"`
* Line 633 - Phone number doesn't have label translation: `"label": "Telefon", "terms": "Telefoninumber"`
* Line 697 - Translation for label of `second_hand`. Currently "Komisjonimüük" implies very specific legal situation of (used car) sales where shop is just middleman and actual purchase is made from 3rd party private person. Fix: `"label": "Müüb kasutatuid",` (just like in English version).
* Line 749 - In label of `Smoking=isolated` is word "suitsetamiseks" is using incorrect case which implies some*thing* should be brought to isolated place before smoking it. Fix: `"isolated": "Suitsetamine eraldatud kohtades",`
* Line 827 - Another potentially confusing use of wrong case with tidal range. `"label": "Loodeline"` instead of "Loodetest", which implies events caused by tides happening on geological scale of millions of years. Personally i would add tooltip or description of `"Kas veekogu jääb loodelise veetaseme kõikumise piirkonda?"`, which is virtually wiki page's first sentence formed as question.
* Line 842 - Label of track type (used for highway track). Currently translated as "path type", suggesting `"label": "Tee kõvadus",` meaning track (road) hardness, because sample values used before describe only hardness/softness of road.
* Line 928 - Wholesale. Current value "Hulgikaubandus" means literally whole-trading. Suggesting `"label": "Hulgimüük"` as correct term.
* Line 1793 - Typo in "Jalakäia ülekäik". Fix: `"name": "Jalakäija ülekäik"`
* Line 3022 - Tatoo shop is missing umlaut. `"name": "Tätoveeringu salong", "terms": "tatoveering"`
* Lines 3245, 3248, 3254 and 3266 - "pöör**e**" instead of "pöör**d**". Example: `"name": "Vasakpööre keelatud"`. "pöörd" is military drill command while "pööre" is commonly used for turning.

Also, around line 197 (parking space capacity) is worth adding `"capacity/disabled_parking": { "label": "Invakohtade arv"},` because people might become surprised, when they encounter disabled and may think of spaces that have been disabled (as unavailable).

**Comment by pnorman** [comment]
Translations are managed in Transifex and need to be fixed there. See https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md#translating for more info.

**Comment by kallejre** [comment]
Fixed all there. I must say Transifex has terrible search functionality when it comes to adding alternative search terms.
