### ISSUE TITLE
Crossing between Railways (dissued) and roads should generate a warning

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#8368]
The crossing between a railway dissused (abandoned) and any road (from tracks to Highways) should generate a warning to share a node with crossing (level_crossing), not becuase there is danger of an incoming train, but becuase normally the rails are still there and becomes an obstacle in the way, that navigation programs should consider.

Thanks

**Comment by quincylvania** [comment]
@jjiglesiasg iD worked this way when we initially added the crossing warning. But in many countries mappers use `railway=abandoned` to map rail lines where the rails have been removed, so in these cases there are no level crossings. This is an OSM tagging problem where it's ambiguous whether or not any rails are there. You can use `railway=disused` if you want to be sure data consumers will know rails exist.
