### ISSUE TITLE
Location-specific brand preset not applying correctly

### ISSUE THREAD

**Issue by jarek** [openstreetmap/iD#8370]
Hello,

Given the following specification in the name-suggestion-index: https://github.com/osmlab/name-suggestion-index/blob/96674bb954ea29c4d3a862a05b5160366e73f16b/data/brands/shop/supermarket.json#L5980-L6006, I would expect Walmart Supercentres in Canada to be named "Walmart Supercentre". However iD wishes to upgrade these tags to "Walmart Supercenter". Sample screenshot of https://www.openstreetmap.org/edit?way=148808775 with name changed manually:

![centre](https://user-images.githubusercontent.com/47415/109454129-96f3c680-7a21-11eb-89e0-6fa004a8d4ee.png)

Do you have any ideas why the Canadian brand preset isn't working and how this could be fixed?

**Comment by bhousel** [comment]
Hey @jarek , this is #8305 .  I have a work-in-progress pull request to bring the latest NSI data into iD ..

**Comment by jarek** [comment]
Ah I see! From git history I saw that the name-suggestion-index entry is at least 6 months old, I hadn't realized that the data in iD is older than that.
