### ISSUE TITLE
Practice mode for iD

### ISSUE THREAD

**Issue by IgorEliezer** [openstreetmap/iD#8376]
Hello,

I would like to show people who don't have an account yet how iD works and that it doesn't look as threatening as it may sound to some people, like "mapping must be hard, so it's for nerds only". But there's a barrier: they still need an account. People may be wary of creating an account and giving their email address in any site they don't know (well, they should).

How about iD to have a trial mode like Waze does. There's a link "Try practice mode" (https://www.waze.com/en-US/editor) so you can open their editor and edit the map to see its inner workings without an account and saving, while you're invited to do their tutorials. If you feel that mapping is for you, you then create an account.

I could for instance send a friend or someone a link like `https://www.openstreetmap.org/edit#map=18/-23.16869/-47.75786?practice_mode=true` so they can see how their neighborhood is mapped.

Regards,

Igor

**Comment by stephan75** [comment]
Maybe see https://github.com/openstreetmap/iD#participate where you can start mirrored test instances of the Editor without the need to log in.

**Comment by kymckay** [comment]
https://ideditor-release.netlify.app is a mirror of the release build which allows you to edit and only asks for a login on attempting to save.

I think what you're asking for is a request for the website itself and the way iD is deployed there.

**Comment by IgorEliezer** [comment]
> https://ideditor-release.netlify.app is a mirror of the release build which allows you to edit and only asks for a login on attempting to save.

I was looking for a way to show someone who hasn't become a mapper how iD works. I'll add that link in our manual/guide and must suffice. Thank you.
