### ISSUE TITLE
Barracks has incomplete tags

### ISSUE THREAD

**Issue by tvage** [openstreetmap/iD#8378]
Id displays "Barracks has incomplete tags" when military=barracks is tagged without also having landuse=military. However, if the barracks is a single building, then building=military should be used instead. I suggest the rule be changed to accept either. The "Upgrade the tags" fix needs to check whether there is already a building tag - if so, change its value to military; if not offer the  user the choice of either building=military or landuse=military.

Cheers,
Mike

**Comment by Fizzie41** [comment]
Just came here to discuss this! Now that military=base has replaced military=barracks to show the area of a military establishment, the requirement for landuse=military should be removed from military=barracks altogether.

**Comment by mxdanger** [comment]
This issue should be moved to: https://github.com/openstreetmap/id-tagging-schema

**Comment by Fizzie41** [comment]
Thanks! How do we do that?

**Comment by tyrasd** [comment]
closing in favor of https://github.com/openstreetmap/id-tagging-schema/issues/158
