### ISSUE TITLE
Phone number hint has the wrong localization

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#8380]
Steps to reproduce:

– Open iD
– Choose a country different from the current locale of your browser (in my case: Firefox)
– In this country, search a node with a supermarket, which has no phone number.
– The grey phone number hint displayed in the dedicated field for “phone=” is correctly localized for the country in which you are editing.
– Now go to properties, add a new tag, put “phone” as key and press the Tab key, so that the text cursor moves on to the “value” field.

Current results:
– The grey phone number hint displayed in the dedicated field for “phone=” is now wrongly localized: It hasn’t any more the locale of the country in which you are editing, but the locale of the country as provided by your browser.

Expected results:
– The grey phone number hint displayed in the dedicated field for “phone=” is still correctly localized for the country in which you are editing.

Note:
The wrong grey phone number hint persists even when you delete the incomplete “phone=” tag from the property list, make a mouse click on an empty place of the map to deselect the object, and then make a mouse click again on the very same object: Still the wrong phone number hint.

**Comment by danieldegroot2** [comment]
On some POIs I'm getting the correct hint initially but then the next time I select them it is the one based on my settings.
(also I should be getting the right area code for Kilkenny then "(0)56" but am getting "20" instead.)

**Comment by CorruptComputer** [comment]
Yeah, it seems that adding a new field breaks the localization on the phone number:

https://user-images.githubusercontent.com/5573038/190224624-c58fb6c2-bad2-4fb1-97d8-c933f144701e.mp4
