### ISSUE TITLE
name suggestion index was not updated in 2.19.6

### ISSUE THREAD

**Issue by cicku** [openstreetmap/iD#8381]
Hi,

It looks like I need to wait for another few months to get something new from index.

Is it OK to directly pull the data from [dist](https://github.com/osmlab/name-suggestion-index/tree/main/dist) when you release any newer version in the future? The official "release" of index serves little value IMO because the list is being frequently updated.

**Comment by bhousel** [comment]
@cicku I'm working on this in #8305 and it's just about ready
You can use the NSI v5 data on this branch:  https://ideditor.org/nsi-v5/
But please be careful with using the validator to upgrade tags, and post any issues that you find on #8305
