### ISSUE TITLE
New man_made=pump preset

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#8385]
Dear maintainers,

Earlier this year, pumping proposal has been reviewed and approved on osm wiki.
​https://wiki.openstreetmap.org/wiki/Proposed_features/Pumping_proposal

It reinforces tagging associated to man_made=pump and some presets could be useful to encourage mappers to use it accordingly.

Is this possible to add a preset "Pump" for man_made_pump please?
​https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpump

Some combinations could be done with man_made=pump and could also be added to man_made=windpump, man_made=water_well or man_made=petroleum_well.

* pump_mechanism=* see values ​https://wiki.openstreetmap.org/wiki/Key:pump_mechanism
* mechanical_driver=* see values ​https://wiki.openstreetmap.org/wiki/Key:mechanical_driver
* mechanical_coupling=* see values ​https://wiki.openstreetmap.org/wiki/Key:mechanical_coupling
* handle=wheel,cross,lever,crank,button,no ​https://wiki.openstreetmap.org/wiki/Key:handle
* pressure=*
* flow_rate=*
* operator=*
* manufacturer=* 

handle is already in use with pipeline=valve

Very simple validation rules apply

* when combined, handle=* is only valid with mechanical_driver=manual
* pump_mechanism=* requires man_made=pump, man_made=windpump, man_made=water_well or man_made=petroleum_well 

Thanks in advance

**Comment by matkoniecz** [comment]
tagging scheme issues are now handled in https://github.com/openstreetmap/id-tagging-schema

**Comment by flacombe** [comment]
Thanks, moved to https://github.com/openstreetmap/id-tagging-schema/issues/149
