### ISSUE TITLE
Pumps and wells related deprecations

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#8386]
Dear maintainers,

Following the approval of pumping proposal on osm wiki, some keys are ready for deprecation.
​https://wiki.openstreetmap.org/wiki/Proposed_features/Pumping_proposal

Could you raise a warning regarding the use of following key and propose the according replacement please?
* pump:type => pump_mechanism
* man_made=pumping_rig => man_made=petroleum_well + pump_mechanism

Wiki is up to date
https://wiki.openstreetmap.org/wiki/Key:pump:type
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpumping_rig

Thanks in advance, all the best

**Comment by matkoniecz** [comment]
Deprecations and other tagging scheme issues are now handled in https://github.com/openstreetmap/id-tagging-schema

**Comment by flacombe** [comment]
Moved to https://github.com/openstreetmap/id-tagging-schema/issues/150
