### ISSUE TITLE
Menu doesn't roll up even if we enter a choice that is not listed

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8403]
OK, we have typed in "20 mm", which is not one of the choices,
![20210314T220617](https://user-images.githubusercontent.com/1230959/111071544-9ecb6480-8511-11eb-955d-ec5e470dfc9a.jpg)
but the list doesn't roll up on its own at this point.
It should roll up so we can start to work on the next question (field).
At this point the user will probably start clicking around the edges somewhere, in order to get it to roll up.

(Same menu as  in #8401.)

**Comment by mxdanger** [comment]
This is intended functionality. The drop-down menu is revealed while the text field is in focus unless there is no suggestions. You can use <kbd>Tab</kbd>, <kbd>Shift</kbd>+ <kbd>Tab</kbd>, <kbd>Enter</kbd>, or click anywhere on the edit feature side panel to unfocus the text field.
