### ISSUE TITLE
Impossible to select ways or areas that share nodes

### ISSUE THREAD

**Issue by dafadllyn** [openstreetmap/iD#8405]
Clicking on ways or areas that share the same nodes (for example a `highway=track` and a `pist:type=nordic`), iD just selects one of them, but it is impossible to select the other way(s) or area(s) "behind". It would be very handy if iD asks which way or area should be selected (e.g. with a pop-up dialog) or if there were an option to choose the desired way or area (e.g. by repeatedly clicking on the way/area).

**Comment by 1ec5** [comment]
This is the same as #1239, which is fixed by #8264 (not yet released).
