### ISSUE TITLE
Mapbox imagery doesn't show on v3

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/iD#8409]
https://preview.ideditor.com/master/#background=Mapbox doesn't show imagery.

**Comment by mmd-osm** [comment]
While this is still open, you can probably add a custom background and add the URL that's being used on osm.org

**Comment by mikelmaron** [comment]
@lectrician1 the mapbox endpoint for imagery was changed, and that version of iD deployed on osm.org.

@quincylvania are you still regularly deploying to preview.ideditor.com ?

**Comment by arch0345** [comment]
The v3 instance referenced in this issue was removed in https://github.com/openstreetmap/iD/issues/9295

**Comment by lectrician1** [comment]
Okay, closing then.
