### ISSUE TITLE
Support street side parking as preset

### ISSUE THREAD

**Issue by wmisener** [openstreetmap/iD#8420]
It would be nice if `parking=street_side` were supported by iD, either as a preset that comes up when typing in parking to the feature search bar and/or at least as a menu option under "Type" (which it is not currently, see below).
<img width="361" alt="Screen Shot 2021-03-23 at 6 09 57 PM" src="https://user-images.githubusercontent.com/58491489/112239033-0a44be80-8c03-11eb-95fa-3b2e10ab179f.png">

This tag is approved (https://wiki.openstreetmap.org/wiki/Tag%3Aparking%3Dstreet_side), commonly used (25k, already the 4th most used `parking=*` tag: https://taginfo.openstreetmap.org/keys/parking#values, ahead of other presets and Type options), and may soon be rendered on carto (https://github.com/gravitystorm/openstreetmap-carto/pull/4301).

**Comment by matkoniecz** [comment]
note that it should be reported at https://github.com/openstreetmap/id-tagging-schema (and AFAIK is reported already)

**Comment by JamesKingdom** [comment]
Yes there is a PR for this already under https://github.com/openstreetmap/id-tagging-schema/pull/73
