### ISSUE TITLE
iD wants to change shop value despite better match in NSI

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#8426]
Yves Rocher can be tagged as `shop=beauty` or `shop=cosmetics` and both are valid an in NSI

But iD want to "upgrade" while changing shop type, without a good reason

https://www.openstreetmap.org/edit?editor=id&node=3845799681#map=19/51.05281/16.97383
![screen06](https://user-images.githubusercontent.com/899988/112729863-ac7be380-8f2e-11eb-85e5-73f6c8c7646d.png)

From what I see NSI has correctly also `shop=cosmetics` - see https://github.com/osmlab/name-suggestion-index/blob/ea9d441ffb3e1594fca160910219929b4393eb12/data/brands/shop/cosmetics.json#L390

----------

triggered by https://forum.openstreetmap.org/viewtopic.php?pid=823920#p823920 where local mapper complains about people incorrectly changing `shop=cosmetics` into `shop=beauty` due to "upgrade" button in iD

**Comment by matkoniecz** [comment]
triggered by https://forum.openstreetmap.org/viewtopic.php?pid=823920#p823920 where local mapper complains about people incorrectly changing `shop=cosmetics` into `shop=beauty`

**Comment by bhousel** [comment]
<img width="300" alt="Screen Shot 2021-03-29 at 9 14 29 AM" src="https://user-images.githubusercontent.com/38784/112842092-329f4380-906f-11eb-8cc4-cbb9e2cc8495.png">

This is working as correctly with the current code from #8305 deployed at https://ideditor.org/nsi-v5/
