### ISSUE TITLE
OS OpenData StreetView Layer

### ISSUE THREAD

**Issue by UKChris-osm** [openstreetmap/iD#8448]
When using the iD Editor, I see that is has "_OS OpenData StreetView_" available as a layer, which seems to be from 2019.

Looking at [https://os.openstreetmap.org/](https://os.openstreetmap.org/) which I think is the hosting site for the "_OS OpenMap Local_" as it's known, I see it has a 2020 version selectable, so was wondering how this layer could be used within iD?

There has also been a [new 2021 release](https://osdatahub.os.uk/downloads/open/OpenMapLocal) this month (April) so how would this new update be made available within iD - would it be via the [editor-layer-index](https://github.com/osmlab/editor-layer-index)?

**Comment by RobJN** [comment]
That's correct. You need to add a new geojson file to the imagery list within the GB folder : https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/gb

I suggest copying the street view geojson file and adapting that. Shout if you need a hand (although it might take me a while as quite busy at the moment).

**Comment by UKChris-osm** [comment]
Thank you @RobJN 

Looking at the geojson file you referenced, I see the line:
**"url": "https://{switch:a,b,c}.os.openstreetmap.org/sv/{zoom}/{x}/{y}.png",**

... which I guess is the reference to the tile server, but how would I go about having the "_April 2021_" imagery uploaded to the https://os.openstreetmap.org web site in the first place?

**Comment by RobJN** [comment]
I'm not sure who runs that site but as it's on a openstreetmap.org domain you could reach out to Grant Slater or Tom Hughes. They are however busy volunteers so my recommendation is just to be patient. All other years have been added and it is only 8 April! Give it a month at least.

**Comment by 10992-osm** [comment]
I had a look just now, and the April 2021 version is now available on https://os.openstreetmap.org/.  Is it now available in iD?

**Comment by boothym** [comment]
This issue can be closed as the layer is now available. @tyrasd

**Comment by tyrasd** [comment]
> This issue can be closed as the layer is now available.

I'm slightly confused. In iD's layer list I can only find the 2016 version of the layer titled: `OS OpenData StreetView (April 2016)` [^1]. Is only the title incorrect now?


[^1]: it uses the url `https://{switch:a,b,c}.os.openstreetmap.org/layer/gb_os_sv_2016_04/{zoom}/{x}/{y}.png`, see https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/OSOpenDataStreetView.geojson

**Comment by boothym** [comment]
Not sure where you are looking, but in Great Britain there is definitely a OS OpenMap Local (April 2021) available in iD.
![oslocal](https://user-images.githubusercontent.com/16965772/144606261-2cf1f209-269d-47c0-9de0-bcee3984f9f4.JPG)


https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/OSOpenMapLocal.geojson

**Comment by tyrasd** [comment]
Oh, sorry. I was looking for a layer called _OS OpenData StreetView_ because this issue is titled that way. :see_no_evil: 

So, this was indeed resolved in https://github.com/osmlab/editor-layer-index/pull/1151 we can close the issue here.

**Comment by UKChris-osm** [comment]
I'm still somewhat confused as to who manages the hosting of the OS tiles on [os.openstreemap.org](https://os.openstreetmap.org) as it seems the entry within the [editor-layer-index](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/OSOpenMapLocal.geojson) is a reference file, but doesn't control the hosted tiles itself.

I'd like to be able to try and add the latest [OS OpenData](https://osdatahub.os.uk/downloads/open/OpenMapLocal) (Oct 2021) to the ELI and make it available within iD!

**Comment by boothym** [comment]
Apparently it's a server @Firefishy manages, perhaps they will update it with the Oct/Nov OS map update soon.

https://github.com/search?q=org%3Aopenstreetmap+openmap&type=commits

**Comment by UKChris-osm** [comment]
Thanks @boothym I'll have a look over on the [chef repo](https://github.com/openstreetmap/chef).

Would it be worth removing the _OS OpenData StreetView (April 2016)_ layer from iD, seeing as its now been superseded with **OS OpenMap Local**?

**Comment by boothym** [comment]
I would say no, because the blue line for MWHS is actually more detailed in OSSV than the smoothed one in OSOML - useful for updating inaccurate old coastline from PGS - and sometimes there's differences with names etc. so I'd say keep it for now.

**Comment by Firefishy** [comment]
https://github.com/openstreetmap/chef/pull/471

**Comment by boothym** [comment]
Many thanks!

**Comment by UKChris-osm** [comment]
Thank you @Firefishy 👍
