### ISSUE TITLE
How to (easily) add an MTB route relation

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#8451]
I'm trying provide an answer to [this](https://help.openstreetmap.org/questions/79382/bicycle-park-mtb-city-road-help?page=1&focusedAnswerId=79391#79391) question.  What I think** I want to do is add a route=mtb as per [the wiki](https://wiki.openstreetmap.org/wiki/Cycle_routes#Relations).  Unfortunately in iD although it's possible (without resorting to direct tag editing) to add a "route=bicycle" I can't see a way to add "route=mtb" (despite it being [pretty popular](https://taginfo.openstreetmap.org/keys/route#values)).

My test data FWIW is on the [dev server](https://api06.dev.openstreetmap.org/relation/4304892673).

I may, of course, have completely got hold of the wrong end of the stick somewhere - please let me know if I have (and by all means improve the "community" help answer too).

Somewhat tangentially to the above, in this case it has proved a bit difficult for a user new to editing to figure out how to add a route relation in iD, despite it being suggested that that is what they need to add.  That's a bit offtopic for this issue though - if it would be helpful to provide a description of what happened and what confusions occurred then I can provide that.

 ** actually the jury's still out on whether route=bicycle or route=mtb is best in this actual case, but the "how do I add an MTB route without manually editing tags" question stands.

**Comment by RudyTheDev** [comment]
The preset already exists at https://github.com/openstreetmap/id-tagging-schema/blob/9f092d884f4aa194e2b512d5d1d933e53096cab7/data/presets/type/route/mtb.json per https://github.com/openstreetmap/id-tagging-schema/issues/99, but a new version with this change hasn't yet been released.
