### ISSUE TITLE
Feature: Allow editing of notes

### ISSUE THREAD

**Issue by dreua** [openstreetmap/iD#8465]
This might be not the right place to ask, but maybe you can move or point me to the correct place:

I'd like map notes to be editable like, for example, issues and comments on GitHub. I think that everyone who creates a note every now and then made mistakes, typos and spotted them only after creating the note or comment. Like in Github and many other places it would be nice to be able to fix those yourself.

Thanks!

**Comment by manfredbrandl** [comment]
You may open an issue here https://github.com/openstreetmap/openstreetmap-website/issues/ but please search first if there already is an issue covering your request.

**Comment by dreua** [comment]
Thank you!

**Comment by dreua** [comment]
Found https://github.com/openstreetmap/openstreetmap-website/issues/1849 which is not exactly about editing but close enough.
