### ISSUE TITLE
Feature: Select a lower element in a layered construction

### ISSUE THREAD

**Issue by dreua** [openstreetmap/iD#8469]
Someone else already asked this: https://help.openstreetmap.org/questions/78767/select-a-lower-element-in-a-layered-construction

Example: https://www.openstreetmap.org/edit#map=20/49.99921/8.26509

I'm not able to select the actual building outline because it is overlaid by building parts. (I can select those but I'd like to inspect / change tags on the main building.)

Is this a missing feature or lacking documentation?

Workaround: Add a point in the outline, disconnect, move, change building, remove extra point (tedious, error prone)

**Comment by 1ec5** [comment]
As of #8264, you can select one of the nodes along the outer wall of the building and press <kbd>|</kbd> to select all the lines and areas that touch that node. From there you can select the building in the sidebar. This feature hasn’t been released yet, but it is present in [the development preview](https://ideditor.netlify.app/).

**Comment by 1ec5** [comment]
Even better, as long as Partial Fill is selected under Style Options in the Map Data pane, the border for the building is slightly thicker than the border for the building parts, so you should be able to select the building with one click and no key presses.

**Comment by dreua** [comment]
Thank you!

**Comment by sekerob** [comment]
Just as the doctor prescribed. Tried the key combo on ID 2.19.6 and nothing happens, did same on the preview and shift+| did the listing of all that's linked to the selected node.

NB On multipart layered buildings found a while ago that if the mapper had created an outline relation, choosing any 'part' would list all the parts in the relation through which one could get at the lower ones, but this new function is definitely superior and I think all situation applicable, mapped relation or not.
Thanks so much for carrying the issue forward.
