### ISSUE TITLE
Better tagging of railway crossings

### ISSUE THREAD

**Issue by ZEE6de** [openstreetmap/iD#8481]
There are many tags to define "[railway=level_crossing](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dlevel_crossing)" - and these could be used in the Editor: 
![example](https://user-images.githubusercontent.com/81919424/116705993-6c949a00-a9cd-11eb-940c-01afffc9d641.png)
A quick example how this _could_ look, made with paint.

**Comment by mxdanger** [comment]
The issue you posted does not relate to this repo and cannot be implemented here. Please move your issue to the project that handles tagging and presets: https://github.com/openstreetmap/id-tagging-schema/issues
