### ISSUE TITLE
Lateral water hazard has incomplete tags warning.

### ISSUE THREAD

**Issue by jumbanhounc** [openstreetmap/iD#8482]
I'm getting warnings that `golf=lateral_water_hazard` is missing tags because there is not `natural=water` tag on the way.  In this [case](https://www.openstreetmap.org/edit#map=19/36.02251/-78.93697): , the water hazard are the steep outer banks of a creek that are usually not full of water.  There is a stream centerline running through the center of the hazard polygon.  

Here is the relevant recommendation from the [wiki](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course): "Usually defined by red stakes or lines (Rule 26) - Always tag natural=water for the water areas **if they exist.**"

**Comment by mxdanger** [comment]
The issue you posted is unrelated to this repo. Please move your issue to the project that handles tagging: https://github.com/openstreetmap/id-tagging-schema/issues
