### ISSUE TITLE
Display of cycleways in map view

### ISSUE THREAD

**Issue by hungerburg** [openstreetmap/iD#8485]
There are several ways to mark up cycleways. They are considered equal, see  #6836. Yet, the iD editor does not show them the same! Recent discussion in the Austrian forum about useless re-tagging of cycleways circled around opting out of the preset, but the preset was considered valuable.

If correctly mapped cycleways would appear as what they are (like in OSM-Carto e.g.), this re-tagging might not happen at all.

Pictures: User sees a path; Searches for bicycle; Creates a cycleway - which it was, from the start

![bikepath-1](https://user-images.githubusercontent.com/586972/116808432-0593f400-ab39-11eb-8489-72e4bb3a804c.jpg)
![bikepath-2](https://user-images.githubusercontent.com/586972/116808439-09c01180-ab39-11eb-8a32-c8845e800026.jpg)

**Comment by ppete2** [comment]
There's another similar problem - at least within Austria: iD doesn't list these common bicycle+foot ways in its "Way"-menu at all. So if a less OSM-experienced user just chooses the attribute of a way by scanning through iD's menu on the left, he will choose a wrong way-type, e.g "cycleway" (="Radweg" in German). These prevents Routers to use this combined way for hikers.

![Shot1](https://user-images.githubusercontent.com/22689568/116809525-b6e95880-ab3e-11eb-8285-b754a412094f.jpg)

Right now just if the user uses the Searchbox and enters "Rad" (="bicycle" in German), iD shows the entry for combinded bicyle+footway (="Rad- und Fußweg" in German)

![Shot2](https://user-images.githubusercontent.com/22689568/116809674-7ccc8680-ab3f-11eb-98ca-1aeecf9a0086.jpg)

Please make iD show the popular combined version too in its menu by default which will prevent unexperienced users choose the wrong type of way.

**Comment by hungerburg** [comment]
@ppete2 Thank you for splitting out from this a related, but different issue.

**Comment by kkofler** [comment]
Well, it is still disputed whether these `highway=path` are actually "correctly mapped cycleways".

**Comment by hungerburg** [comment]
In a recent poll the Austrian community re-affirmed that highway=cycleway is the preferred base for shared bicycle and foot traffic ways. https://community.openstreetmap.org/t/at-preset-fur-josm-verkehrszeichenerweiterung/108245/54

This issue here though is on the appearance of such in the iD editor. And following from that, useless retagging.

To make matters complete, I close this issue: I have not observed such useless re-tagging for a long time.
