### ISSUE TITLE
Suggesttion to split a map update in spatially-smaller changes

### ISSUE THREAD

**Issue by zenfiric** [openstreetmap/iD#8489]
Have you tired of getting in OSM recent changes all this polygons that are covering half of the planet? That is because people are making a small edit in Australia and another small one in New York.  It would be great if iD would suggest before asving to split edits into two+ map updates.

**Comment by 10992-osm** [comment]
What sort of size do you think would be appropriate?

**Comment by mmd-osm** [comment]
See #7434

**Comment by kymckay** [comment]
iD isn't actively maintained at the moment of writing this, but I'll go ahead and close this as a duplicate of #5424 as a matter of housekeeping
