### ISSUE TITLE
Please add Swissimage and Amtliche Vermessung vereinfacht background imageries

### ISSUE THREAD

**Issue by dafadllyn** [openstreetmap/iD#8506]
Please add the following background imageries to the editor:

* Swisstopo: Swissimage (aerial imagery of Switzerland): https://wms.geo.admin.ch/?FORMAT=image/vnd.jpeg-png8&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=ch.swisstopo.images-swissimage&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox} (see https://sosm.ch/use-of-swisstopo-data-and-products-with-and-in-openstreetmap/)
* Amt für Geoinformation des Kantons Bern: Amtliche Vermessung vereinfacht (ground plans of the Canton of Bern): https://tile.osm.ch/bbe/{zoom}/{x}/{y}.png (see https://wiki.openstreetmap.org/wiki/Canton_of_Bern_Address_Import#Import_Data)

**Comment by boothym** [comment]
@dafadllyn I think iD gets its background imagery from the **editor-layer-index** project, so you might want to open an issue over there: https://github.com/osmlab/editor-layer-index/issues

**Comment by dafadllyn** [comment]
Okay, thanks, I'll do that.

**Comment by dafadllyn** [comment]
One of the two imageries, Swisstopo Swissimage, is already included in editor-layer-index. Why isn't it available in iD?

**Comment by boothym** [comment]
Could be because iD hasn't been updated since 3rd March - https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md - and the imagery was added to ELI on the 18th. Unfortunately there's no active developer on here at the moment to update things.

Maybe try using the url as a custom background?

**Comment by dafadllyn** [comment]
Thanks for your explanation!

I'm already using the URL as a custom background. I just thought it were easier to have it "built-in".
