### ISSUE TITLE
barrier=cycle_barrier is possible, but option is not shown in iD editor dropdown options

### ISSUE THREAD

**Issue by DavidMetcalfe** [openstreetmap/iD#8514]
When editing a barrier, the options shown in the dropdown menu do not match the complete list shown in the [OSM wiki key](https://wiki.openstreetmap.org/wiki/Key:barrier). It's not clear if this is intentional, so an issue is being submitted.

**Comment by mxdanger** [comment]
The options listed in the dropdown is randomly generated based on the most common values used for that tag.

**Comment by boothym** [comment]
I think the dropdown is based on the most common values (with over 0.01% usage) found here: https://taginfo.openstreetmap.org/keys/barrier#values 

Seems like some values are removed depending on whether or not it is a node or way you are editing. For example, fence is not shown for nodes.

If that doesn't answer your issue, then could you list what is shown versus what you expect to be shown?

**Comment by DavidMetcalfe** [comment]
@boothym Hmm. Cycle_barrier is the one I was looking for and according to the linked website, it accounts for 0.59% of barrier values, but it wasn't shown in the drop-down options. Any ideas?

**Comment by boothym** [comment]
It seems like that is only shown when editing a node, not a way/area - there's an element column in the wiki indicating this for each value.

**Comment by DavidMetcalfe** [comment]
@boothym That might be the cause. I'll have to keep an eye out for this next time to see if I was using a node or way. I think this can be closed for now.
