### ISSUE TITLE
cutted way filled in route in oposite direction

### ISSUE THREAD

**Issue by Axel490** [openstreetmap/iD#8519]
We have lots of errors in bus-route relations from iD-Editor-users. The editor seems to look sensible for the way to paste the cutted way, but then uses the oposite direction to paste.
Example: way/334914447 relation/1732028 (going east) and relation/1732029 (going west)
changeset/105406069  I cut the way in two ways way/334914447 and way/947627779
In result both relations are sorted in the wrong order of ways at way/334914447 and way/947627779.

**Comment by HttTavares** [comment]
If you think this can be tackled by a beginner, i'd love to do it. How do I start?

**Comment by tordans** [comment]
> How do I start?

I would start by reading all the comments about relations in this Repo - especially from the maintainers / core committer – especially about ordering member. This will likely show that routes in general and in ID are not an easy topic.

**Comment by 1ec5** [comment]
#8839 will fix this regression.
