### ISSUE TITLE
Is IE11 still supported?

### ISSUE THREAD

**Issue by joepie91** [openstreetmap/iD#8527]
According to [the contributing document](https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md#css):

> Since iD targets modern browsers, (Chrome, Firefox, Safari, Opera, IE11, and Edge) feel free to use newer features wisely.

Aside from the nowadays somewhat anachronous use of "modern" for this list of browsers, it's odd that it would still list IE11, considering that it will go officially EOL in August and the [current marketshare](https://gs.statcounter.com/browser-market-share) is about 0.62%. Is IE11 really still supported, or has this text simply not been updated yet?

**Comment by bhousel** [comment]
All the work to support IE11 was done a while ago (see #1908, #2511 and related).  This might surprise people, but the tricky issues were all related to CSS and SVG quirks, not JavaScript.

The project now includes core-js polyfills and has a Babel transpile step to produce a legacy build, so there really isn't a reason to _un_-support IE11 now.  Also, there's still a dependency on PhantomJS in the test suite, so to keep the tests passing, we should keep the legacy build around. 

So the short answer is, yes it is still supported.  It would be work to remove that support and there is nobody to do the work anyway.

**Comment by joepie91** [comment]
Right, my question was specifically about the CSS/SVG parts; I should've probably mentioned that explicitly.

AFAIK there are a *lot* of CSS/SVG features that become available when dropping IE11 support, so that seems like a good reason to un-support it - though if the testing setup hasn't been migrated to something like headless Chromium yet, that set of features may not yet be big enough to warrant it.
