### ISSUE TITLE
Activating missing mapillary layer

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#8535]
See title, it seems the mapillary layer is down. Anybody else can confirm this?

**Comment by tastrax** [comment]
Yes - Probably related to Mapillary updates that came in to effect yesterday

https://blog.mapillary.com/update/2021/06/09/platform-updates-june.html

**Comment by 1ec5** [comment]
#8372 switches to a new Mapillary API that appears to still be working. You can use [this preview deployment](https://id-mapillary-tiles.netlify.app/) as a temporary workaround.

**Comment by nickplesha** [comment]
Mapillary layer is now back on https://www.openstreetmap.org/edit

**Comment by sun-geo** [comment]
@nickplesha Thank you => closed
