### ISSUE TITLE
Holiday gas stations mapping as convenience stores

### ISSUE THREAD

**Issue by newnumber2** [openstreetmap/iD#8538]
When selecting "Holiday" for a gas station, it adds a convenience store (Holiday StationStore) instead of a gas station.

**Comment by kjonosm** [comment]
iD takes its suggestions from the name-suggestion-index (NSI) which has "Holiday" already correctly [listed](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#holiday-c5cf43) in the gas stations tree. Unfortunately iD still pulls an old NSI version from last year. See #8305
