### ISSUE TITLE
nycdoitt:bin building tags stripped on "Extract" and "Downgrade" operations

### ISSUE THREAD

**Issue by jmapb** [openstreetmap/iD#8539]
This issue concerns the `nycdoitt:bin` tag, which is part of the New York City building footprint import. This tag holds the building id number (BIN) of the imported building. It's associated with the physical structure, not with the building's use or contents.

**Expected behavior:** `nycdoitt:bin` tags will be considered building tags and will remain on a building way (or multipolygon) after "Downgrade" or "Extract" operations. They will not be copied to POI nodes created during "Extract" operations.

**Observed behavior:** `nycdoitt:bin` tags are removed from buildings during "Downgrade" and "Extract" operations, and are copied to the newly created POI node during "Extract."

**Steps to reproduce:**
1. Right-click on an imported New York City building footprint that also has POI tags (eg [https://www.openstreetmap.org/way/265796841](https://www.openstreetmap.org/way/265796841))
2. Select "Downgrade" from context menu
3. Observe tags of building way -- `nycdoitt:bin` has been removed
4. Undo to restore building way tags
5. Right-click and select "Extract" from context menu
6. Observe tags of building way and newly created POI node -- `nycdoitt:bin` has been removed from way and added to node

**Comment by mxxcon** [comment]
Any progress with this issue?
I could be mistaken, but based on RapiD's changes it seems like just need to update https://github.com/openstreetmap/iD/blob/d6a4130f42b2db20c4355106a939d5a97c0bf631/modules/actions/extract.js#L47 and https://github.com/openstreetmap/iD/blob/d6a4130f42b2db20c4355106a939d5a97c0bf631/modules/operations/downgrade.js#L65
