### ISSUE TITLE
Include OpenAerialMap as imagery source

### ISSUE THREAD

**Issue by Tomagori** [openstreetmap/iD#8562]
[OpenAerialMap](https://openaerialmap.org/) is a wonderful project that offers people a way to upload their aerial footage (mostly drone imagery) for other people to access. As of today, OEM has AFAIK not been implemented natively in any major editor, but I think this is a considerable omission. OEM offers resolutions that no other imagery source can, and it can be updated by anyone with the necessary equipment at any time. Adding OEM support to iD would strengthen both projects, as it would give editors fresh, detailed imagery and give OEM contributors more incentive to contribute, as they know their work will find its way on the map. Especially for areas in the third world that don't have public local government surveys and very out of date satelite data, OEM + iD would give people a very easy way to contribute massively.

Two considerations to take into account right off the bat, however: 

1. OEM has, obviously, very low coverage, as all the imagery is manual labour by normal individuals, not some great regional, national or global survey. This doesn't have to be a problem, though. As with other local imagery sources, it should only be offered when imagery is available for a location.
2. There might be multiple images of the same location. There's nothing preventing multiple people from uploading their imagery of the same place, which, in principle, is good. However, iD will have to find a way to deal with that. One option would be to offer a dropdown when clicking the imagery source, but I'm sure people can come up with other, better solutions. This doesn't need to be fancy in my opinion, but it's something to solve.

**Comment by tordans** [comment]
Another approach is described in https://github.com/hotosm/OpenAerialMap/issues/136 and https://github.com/osmlab/editor-layer-index/issues/509 which would be to add OAM to ELI in some (semi) automated manner so that all ELI consumer like iD can use it automatically.

**Comment by cicku** [comment]
Does iD support loading multiple layers at the same time?

**Comment by govvin** [comment]
> Does iD support loading multiple layers at the same time?

It can switch between several background, including a custom one, but not at the same time. If you need that feature, you should look into the JOSM editor.

**Comment by govvin** [comment]
I'd like to add that OpenAerialMap (OAM) support is missing in iD, and OSM is missing an opportunity to provide contributors with (possibly) better sources for imagery. This is probably not an issue for experienced mappers, but for newer contributors, many may think that all they have is whatever is listed in the available background.

Another plus for using imagery from the OAM project is that all imagery, by default, gives special tracing permission for OpenStreetMap contributors

However, not all OAM contributors has bothered to add their imagery to the editor layer index (ELI), so perhaps, for a better user experience for iD users, they can be given an ability to select whatever OAM imagery dataset is avaible for the area their editing within iD?

This obviates the need for OAM contributors to manually submit their project to ELI, which can take weeks, usually.

**Comment by cicku** [comment]
ELI is not a dumpster, if iD supports reading multiple imageries simultaneously, that’d be great to have OAM added. Otherwise, OAM will not work well.

If your imagery covers a very small place like a new parking lot or few new buildings, they are not worth being added to ELI just for better experience. Also, no one examines OAM’s quality, unlike commercial imageries or government imageries.

**Comment by govvin** [comment]
Hey @cicku , nobody said anything about ELI being a "dumpster."

**Comment by cicku** [comment]
Well, I’m just saying here. Our goal is the same, making OSM better. But, instead of adding thousands of imageries on the same website, we need to push iD to have this issue solved as a better solution.

**Comment by govvin** [comment]
Good to see you qualify that statement  :+1: 

You're correct, the contributor community's goal is to improve OpenStreetMap. Unfortunately (or fortunately), the huge ecosystem of OSM-centric , -related tools are not conveniently usable for most mappers.

Without being specific about the quality or fitness of purpose of any OAM-hosted imagery, iD can certainly add the necessary caveats about their use, in case they decide to make that resource more accessible.

**Comment by matheusgomesms** [comment]
Should this be closed given [it was implemented on ELI](https://github.com/osmlab/editor-layer-index/pull/1649)?

**Comment by Tomagori** [comment]
That seems reasonable, thanks
