### ISSUE TITLE
Bug: Layers, Map Key, Share and Query Features sidebar buttons not working on Safari

### ISSUE THREAD

**Issue by spilth** [openstreetmap/iD#8579]
I'm trying to use https://www.openstreetmap.org/ in Safari but the Layers, Map Key, Share and Query Features buttons in the right sidebar don't work - they don't open up the selected tool.

## Details

- Browser: Safari Version 14.1.1 (16611.2.7.1.4)
- Operating System: macOS Big Sur Version 11.4
- Extensions: None

## Steps to Replicate

1. Open Safari
2. Navigate to https://www.openstreetmap.org/
3. Click on the Layers, Map Key, Share or Query Features buttons on the right side of the window
4. Expected: The corresponding sidebar opens up
5. Actual: Nothing happens

No errors show up in the Console. I have tried this on a few different Macs.

### Google Chrome

![osm-chrome](https://user-images.githubusercontent.com/13157/125520192-5ce6e241-6e4c-4592-a3fe-6052ed896bce.gif)

### Safari

![osm-safari](https://user-images.githubusercontent.com/13157/125520209-41b0c5e0-ab3d-48d0-af97-41a0640351c1.gif)

**Comment by bryceco** [comment]
If you have a mouse you can right-click to activate them.

**Comment by spilth** [comment]
@bryceco Is that by design? Or a workaround?

**Comment by bryceco** [comment]
I have no idea about the design, but it is a workaround and possibly a hint for the fix.

**Comment by spilth** [comment]
@bryceco Thanks on both points!

**Comment by mbrzakovic** [comment]
This is osm website functionality.
Please if needed continue discussion under this repo: https://github.com/openstreetmap/openstreetmap-website
Thanks.

**Comment by spilth** [comment]
@mbrzakovic Ah, you are correct! When I'm in Edit mode, the buttons work as intended.
