### ISSUE TITLE
It is not possible to see a layer of data on OSM

### ISSUE THREAD

**Issue by felypeforte** [openstreetmap/iD#8592]
Hi,

Can anyone help me with the following issue:

I used to use a layer called 'Cartas Topográficas do Exército Brasileiro' [Topographic Charts of the Brazilian Army] in Brazil, to map the peaks from my region, and now I cannot see anything when I select the layer. What could be happening?

**Comment by mbrzakovic** [comment]
Hi!

Can you please add some screen-shots, or describe the endpoint url that you are using + iD version in the bottom right corner?
Thanks!

**Comment by mbrzakovic** [comment]
I see iD populating url pattern correctly, i suppose the imagery url needs to be updated.
@felypeforte please file an issue here: https://github.com/osmlab/editor-layer-index/issues
This file needs an update: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/south-america/br/Brazilian_Army_Topographic_Maps.geojson

**Comment by felypeforte** [comment]
Here's a screenshot of the layer:

![image](https://user-images.githubusercontent.com/60555739/127339026-0be0f878-ea0f-49e8-bda4-6c89dd57938e.png)
