### ISSUE TITLE
iPad scroll zoom issue

### ISSUE THREAD

**Issue by hb0nd** [openstreetmap/iD#8595]
I am unable to scroll-zoom when using an iPad with a dedicated mouse or magic keyboard trackpad. The issue happens on both the embedded version of iD on osm.org, and on http://ideditor.netlify.app/

Tried Firefox and Safari, it happened on both

Video of the issue:
https://www.youtube.com/watch?v=sKRmxKWuCIc

**Comment by mbrzakovic** [comment]
Hi @endim8!
Which version of os is your iPad using?

**Comment by hb0nd** [comment]
iPadOS 15 Beta 3, although it's been happening at least since 14.6 (I only got my iPad recently, so I haven't tried before 14.6)

**Comment by hb0nd** [comment]
I've sold my iPad so can't test this specific issue anymore, however I was having a similar issue on my MacBook that replaced it.
After looking at https://github.com/openstreetmap/iD/issues/5550 and then https://github.com/webcompat/web-bugs/issues/73148, It seems that setting `dom.event.wheel-deltaMode-lines.disabled` to false in Firefox's about:config fixes it

**Comment by mbrzakovic** [comment]
For reference: #5492,
https://github.com/openstreetmap/iD/commit/68be75af094f98c09bc37b54becd65e9378e7ceb#diff-a1008158a41859a7de040d1a3db175073f92aeab5433ea6d1f958319993555aa
https://github.com/openstreetmap/iD/commit/4f8f45ec52c679c7e039fa3eaf92feabd588fda2

Issue: delta y value for both 2 finger panning and mouse scroll on mac os mozila firefox was always integer and therefore mouse scroll was being treated as 2 finger panning mode.
Solution implemented: Remove 2 finger panning handling for mac os firefox as map zoom in/out is of higher importance.

**Comment by mbrzakovic** [comment]
@endim8  please double check this on https://ideditor.netlify.app/

**Comment by hb0nd** [comment]
> @endim8 please double check this on https://ideditor.netlify.app/

Can confirm, it's fixed 😄 thank you!

**Comment by 1ec5** [comment]
The scrolling in Safari on iPad, seen in the original video, looks more like #7576 than #5550 or webcompat/web-bugs#73148.
