### ISSUE TITLE
OSM Editor Background Images are 11 years old

### ISSUE THREAD

**Issue by slhemphi** [openstreetmap/iD#8596]
I'm trying to Edit new OSM data, but the background image is an 11 year old Bing image ( https://blog.openstreetmap.org/2010/11/30/microsoft-imagery-details/ ) , so I can't Trace current buildings and roads which are now different.  I can't find where I can apply more updated ArcGIS or Bing images.
This area on the map is not there anymore   https://www.openstreetmap.org/edit#map=17/42.51540/-83.03109  
Thanks

**Comment by fullsailor** [comment]
Hi @slhemphi, the Bing map background is the default, but there are other background options. At that location the "Esri World Imagery" background has an Oct 22, 2019 vintage.

<img width="1173" alt="Screen Shot 2021-07-27 at 5 05 23 PM" src="https://user-images.githubusercontent.com/154187/127227387-57b8aebf-f357-429b-903d-7c844a8c5505.png">

If you have another source of imagery you can also use a Custom background by configuring a template tile URL. 

<img width="574" alt="Screen Shot 2021-07-27 at 5 06 38 PM" src="https://user-images.githubusercontent.com/154187/127227443-b62ecdd2-9f5b-4c26-b905-633216f1e216.png">

**Comment by boothym** [comment]
As mentioned above there are other imagery sources you can use in the background settings menu @slhemphi - perhaps also try the Maxar Premium Imagery (Beta) imagery as the new buildings seem less distorted.

But make sure you align the imagery first - use the imagery offset tool in the background settings to move the ESRI/Maxar imagery to match the data already there in OSM.

**Comment by mbrzakovic** [comment]
Hi @slhemphi I am sorry to heat that.
Can you please provide some more information to this issue?
1) We had v2.20.0 release to production yesterday. Did this outdated bing image show prior to yesterday?
2) Can you please go to Background Panel -> Show Background panel and screen-shot the Vintage?
It is quite possible that this is not really an iD issue, it could be just that bing imagery does not have fresh data for these tiles. In this case I suggest you look into comments above and try alternative imagery source.

**Comment by slhemphi** [comment]
@mbrzakovic my default "Bing aerial imagery" was still very old as of this post.   And Thanks @fullsailor and @boothym  for explaining how to change Background base-maps.   The "Maxar Premium Imagery" is spot-on, up-to-date.  I'll begin making more accurate road and structure updates now.
