### ISSUE TITLE
Installation: npm run all

### ISSUE THREAD

**Issue by cortazar11** [openstreetmap/iD#8599]
Sorry, might be this is not the proper place to put my issue.
I try installing the code according to instructions. but arriving to 'npm run all' I got command not found. I installed the npm-run-all package ind devDependencies of package.json, but still the same

**Comment by mbrzakovic** [comment]
Hi this is a proper place :)
Can you double check that you are positioned inside iD root dir when you are executing this command?
Can you please paste snippet/screenshot of your console of provide full command log?

**Comment by cortazar11** [comment]
Hi,

Sorry, this morning I reinstall (npm i) and npm run all has worked.

So, I can access the map without problem in localhost:8080
