### ISSUE TITLE
https://ideditor-release.netlify.app/ OAuth issue

### ISSUE THREAD

**Issue by hb0nd** [openstreetmap/iD#8602]
**Issue:**
on the Netlify mirror of iD, OAuth login doesn't redirect to the right location on completion, resulting in being unable to upload changes.

**To Reproduce:**
1. Open https://ideditor-release.netlify.app/ in an incognito tab (so no login information is remembered)
2. Add a point or line or something and try to save the change
3. It will open an OSM OAuth login window, log in and grant access 
4. It opens `https://ideditor-release.netlify.app/land.html?oauth_token=<oauth_token>`
![Screenshot from 2021-07-28 20-19-10](https://user-images.githubusercontent.com/26939824/127383609-20521d68-743a-4fa5-bcf6-22590c086157.png)
5. This results in the login failing, and you're unable to upload your changes.

**Found Fix:**
1. When in the Grant Access page of the pop-up, find the line:
`<input value="https://ideditor-release.netlify.app/land.html" type="hidden" name="oauth_callback" id="oauth_callback">`
2. And change the value of `input_value` to `https://ideditor-release.netlify.app/dist/land.html`
3. Then press Grant Access, and it will sign in correctly.

From this, I think it's an issue with this symlink definition, however I don't have the OAuth know-how to submit a pull-request to fix it :( https://github.com/openstreetmap/iD/blob/1ee45ee1f03f0fe4d452012c65ac6ff7649e229f/scripts/build_data.js#L41

**Comment by mbrzakovic** [comment]
It seems that ideditor-release endpoint requires a redeployment. I have already started working on this :)

**Comment by mbrzakovic** [comment]
Done. @endim8 try now: https://ideditor-release.netlify.app/

**Comment by hb0nd** [comment]
> Done. @endim8 try now: https://ideditor-release.netlify.app/

It works! Thank you 😄
