### ISSUE TITLE
address Interpolation not working for alphanumeric interpolations

### ISSUE THREAD

**Issue by hNdrX77** [openstreetmap/iD#8608]
addr:interpolation is working for numeric start/end-point and house-numbers in between can be found - using a alphanumeric start/end-point interpolation house-numbers can NOT be found (e.g. interpolation 1a - 1f: 1b,1c,1d,1e can not be found as individual address/house-numbers; only streetname is to be found/shown).

**Comment by matkoniecz** [comment]
> using a alphanumeric start/end-point interpolation house-numbers can NOT be found

What exactly cannot be found? Is it about editor or search on the main website

**Comment by hNdrX77** [comment]
It is about search on main website - trying to find any address in between the start/end-points, only streetname is recognized/shown.
E.G. "Haus 9, Distelacker, Petershof-Siedlung, Neugraben-Fischbek, Harburg, Hamburg, 21149, Deutschland" IS WORKING
"Haus 13b, Distelacker, Petershof-Siedlung, Neugraben-Fischbek, Harburg, Hamburg, 21149, Deutschland" IS NOT WORKING. Only Streetname is found and shown.

**Comment by matkoniecz** [comment]
Then it is a https://github.com/osm-search/Nominatim issue, unrelated to iD (sole common point is that both deal with OSM data and are deployed at openstreetmap.org)

Note that it may be already reported there.
