### ISSUE TITLE
Traffic Sign field should not lowercase its value

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8609]
As of v2.20.0, the Traffic Sign field in the Traffic Sign preset automatically lowercases its contents, even though the `traffic_sign` key often needs to be set to an all-caps or mixed-case value like `US:CA:SW-59` or `US:OH:R3-H8dt`.

Similar to #8275 and probably introduced at the same time.

**Comment by bhousel** [comment]
I guess the fix for this needs to be in id-tagging-schema now.

Open [this file](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/traffic_sign.json) and add `"snake_case": false`

https://github.com/ideditor/schema-builder#snake_case
