### ISSUE TITLE
Bus network TUA, Abruzzo Italy forced to 'upgrade' brand wiki tags of TUA, Toronto, Canada.

### ISSUE THREAD

**Issue by sekerob** [openstreetmap/iD#8611]
The Abruzzo bus network, https://www.tuabruzzo.it, Transporto Unico Abruzzese goes by the acronym TUA. This is used as network reference for bus stops, stations and route relations. Since ID Editor 2.20.0 uses a database reference source, any time trying to update a way that has a link set up to the bus system, an 'upgrade' warning pops up wanting to insert wikidata and wikipedia tags of the Toronto Transit Authority. Of course mappers who don't know could hit yes and insert false information or or ignore, but that's till next time and those who don't understand as already observed with another mapper, had 22 warnings recorded on a change set related to Flixbus, EU wide operating bus network. Me forcing the hand recorded this and logged 1 on https://www.openstreetmap.org/changeset/108956122 warnings:outdated_tags:noncanonical_brand. The only way to escape the vicious loop is to change the network acronym TUA to it's full name, which of course is not correct. TUA should remain TUA for the Abruzzo mappers in Italy on the bus network tag.

Please fix ASAP, some geographical coordinates, country restriction or whatever so we don't get presented with this false message.

Thanks.

**Comment by bhousel** [comment]
Thanks for reporting @sekerob - this data comes from the [Name Suggestion Index](https://github.com/osmlab/name-suggestion-index) project.  If you find any other issues with brand or transit suggestions, it is best to report them on that project.

It looks like the Toronto Transit's wikidata was accidentally added to the TUA item in this commit:
https://github.com/osmlab/name-suggestion-index/commit/6c2872e1c01556fe7d6d62512c00db267b28adbc

I replaced that wrong wikidata with the correct tags for TUA a few minutes ago in this commit:
https://github.com/osmlab/name-suggestion-index/commit/5e9b5dc3a3acbf92e681cf8c24e1d66de41da4bb

I'll push out an update to the NSI data tomorrow.

**Comment by sekerob** [comment]
OK, great and thanks for adding the 'real' TUA to your database, wiki-pedia/data and adding a country control. I'll test on Monday night or Tuesday morning. (Did wonder how TTC got linked to TUA but now we know). I'll bookmark the link to the NSI.

BTW There's Ajax, the crane company, Ajax the branded floor cleaner and Ajax the famous football club from Amsterdam. Names can be (re)used as long as they are not in the same branch. Hope this is considered in the NSI coding.

**Comment by bhousel** [comment]
> BTW There's Ajax, the crane company, Ajax the branded floor cleaner and Ajax the famous football club from Amsterdam. Names can be (re)used as long as they are not in the same branch. Hope this is considered in the NSI coding.

Yes, NSI code can handle the same name being used with different tagging or different locations, and also supports matching  alternate tags and alternate names.

**Comment by sekerob** [comment]
To confirm, as a side effect to editing a road with a bus route relation, got the same warning as seen before, BUT \o/, the proper wiki tags were offered for Trasporto Unico Abruzzese (TUA). Even the ones where I had manually added the wiki tags, but left the work around full name in the network field had TUA returned in proper, i.e. the routine matches all 3 relevant bus network tags, so goodos.

**Comment by bhousel** [comment]
> BUT \o/, the proper wiki tags were offered for Trasporto Unico Abruzzese (TUA).

Awesome!  It's really great to see this working in production.  Even if people did add the wrong tag for Toronto Transit last week, iD will flag those features to assign the correct tag today.  I built the NSI code in a way that it would "self-correct" over time..

**Comment by sekerob** [comment]
Permit me to keep this thread going on the subject, I've encountered a few times where when TUA is entered as the network it refuses to add the network wikidata and wikipedia tags i.e. the 'upgrade' is not offered. The difference per tag swap testing is in public_transport=station. When changing this to platform it offers the upgrade option immediately, switch back to station and it wont.  It's operated and used by TUA only.

**Comment by bhousel** [comment]
> I've encountered a few times where when TUA is entered as the network it refuses to add the network wikidata and wikipedia tags i.e. the 'upgrade' is not offered. The difference per tag swap testing is in public_transport=station. When changing this to platform it offers the upgrade option immediately, switch back to station and it wont.

Ah yeah, you're seeing an artifact of https://github.com/osmlab/name-suggestion-index/issues/4765
The NSI matcher needs to match on some `k=v` pair to know what a thing is, and OSM's PTv2 schema spreads this information across multiple keys.  I don't know how to fix it just yet.

**Comment by sekerob** [comment]
Fortunately there are just few station nodes, but regular bus stops have shown to be resistant at times too, 1 in 50 or so and there are over 900 and those are only the numbered ones. Long as I know about the idiosyncrasies I'm fine.., plugging in the wikidata value gets it moving. Finding the ones not upgraded yet is easy too. Just opening the route relation will show which don't show the TUA(full name) tag. 120 today, a monks patience needed.
