### ISSUE TITLE
outstanding issues viewed are being counted towards ignored outstanding issues

### ISSUE THREAD

**Issue by boxer4** [openstreetmap/iD#8613]
With the recent iD update on live, it seems that it's all around easier to trigger an ignored outstanding issue, even if the user did not touch a feature, perhaps even just viewing (sometimes not even clicking on) a feature that has some issue in iD seems to now be sufficient to trigger the warning which gets tracked with the check-in.  Recently I've been touching turn restriction relations (without touching ways) and iD decides to include me as ignoring bus route warnings.  These are unrelated features/relations as I didn't split ways, etc., and perhaps this issue is the same as the FIXME issue #8603 .

This "ignored warning" count that gets tagged with each check-in seems quite silly and also untenable.  For those people doing user metrics, perhaps it's just HDYC, this number will become ridiculously large and impossible to reduce to zero.  For each warning ignored, everyone ignores them, and keeps on going up.  Every time we fix an error whether in iD or not, only ONE person is credited for fixing an error (and it could even be fixed in another editor) and the ignored warning count becomes an ever increasing, meaningless number.  These warning/issues are already being checked with OSMI, KeepRight, Osmose, etc. and these at least will clear credits for everyone when something gets fixed.  Is there any specific reason a problem warning ignored in iD needs to be tracked but not through JOSM/Potlatch/Merkaartor/or any other editor?  Suggestion is to stop including this count with the checkins.  In my opinion the QA should be done at the check-in server so it doesn't matter which editor software is used, not any specific editor software.

Just my observation/opinion/rant/2 cents/...

**Comment by mbrzakovic** [comment]
@boxer4 thanks for raising this.
I acknowledge the issue and will try to pinpoint the bug.

**Comment by bhousel** [comment]
I'm looking into this already - it's probably things I did around 11201eb82
