### ISSUE TITLE
Missing translation message

### ISSUE THREAD

**Issue by kjonosm** [openstreetmap/iD#8619]
Maybe related to #8610? This missing translation message pops up after starting iD [here](https://www.openstreetmap.org/edit#map=20/48.31384/10.98519):

![Bildschirmfoto 2021-08-02 um 20 50 33](https://user-images.githubusercontent.com/51236777/127909679-733d688c-050a-4a19-8a17-f36c1272cd36.png)

(Language set to German)

**Comment by mbrzakovic** [comment]
Managed to repo this. Looking into it.

Doesn't look like its strongly related to #8610 as this item seems more like a singular edge case for translation string.

**Comment by 1ec5** [comment]
Oh yeah, that would be related to #8276. I didn’t consider that a route could have just a `network` but no `ref`.

**Comment by kjonosm** [comment]
@1ec5 
I came across another bug which might be related. It's another a missing translation for a network of ATM's.

![Bildschirmfoto 2021-08-07 um 18 40 43](https://user-images.githubusercontent.com/51236777/128607668-50eb7603-b7e2-4844-97b5-925ebc3c4628.png)

https://www.openstreetmap.org/node/1179590255

**Comment by 1ec5** [comment]
Yes, that’s probably the same thing. The bug affected any feature that had a `network` without a corresponding `ref`. The code in question doesn’t consider the feature’s type.
