### ISSUE TITLE
Lack of brand:wikipedia=* or operator:wikipedia=* should not count as incomplete tag

### ISSUE THREAD

**Issue by dafadllyn** [openstreetmap/iD#8620]
iD shows a warning if a "common feature" doesn't have a `brand:wikipedia=*` or `operator:wikipedia=*` tag. 

In my opinion, `brand:wikidata=*` and `operator:wikidata=*` is enough information. Someone interested in the corresponding Wikipedia article can get this information via Wikidata. Besides, Wikidata lists Wikipedia articles in all languages, while it is only possible to set a Wikipedia article in a single language in `brand:wikidata=*` and `operator:wikidata=*`, which is problematical in multilingual countries.

**Comment by matkoniecz** [comment]
wikdata tag is an alphanumeric gibberish and to decipher it one needs full wikidata database or online connection

Therefore it is preferable to use also wikipedia tags in addition to wikidata tags as wikipedia tags are human-readable (though some people disagree with this)

**Comment by bhousel** [comment]
This comes up for discussion in NSI sometimes: https://github.com/osmlab/name-suggestion-index/issues/4672

We really don't mind with the redundancy because many OSM contributors expect it to be there and we are following an accepted tagging convention.

Maybe someday in the future OSM will standardize around `*:wikidata`, but as of today there's no harm in adding both `*:wikidata` and a companion `*:wikipedia` tag.

**Comment by dafadllyn** [comment]
> wikdata tag is an alphanumeric gibberish and to decipher it one needs full wikidata database or online connection

You also need a copy of Wikipedia or an active internet connection to check Wikipedia tags. 🙂

I'm not opposed to Wikipedia tags, especially not of the feature itself. I just think that it shouldn't count as an issue if `brand:wikipedia=*` or `operator:wikipedia=*` is missing but `brand:wikidata=*` or `operator:wikidata=*` is present.

**Comment by dafadllyn** [comment]
> This comes up for discussion in NSI sometimes: [osmlab/name-suggestion-index#4672](https://github.com/osmlab/name-suggestion-index/issues/4672)
> 
> We really don't mind with the redundancy because many OSM contributors expect it to be there and we are following an accepted tagging convention.

I'm not sure if `brand:wikipedia=*` and `operator:wikipedia=*` really are a widely acepted tagging convention. The most used `brand:wikipedia=*` and `operator:wikipedia=*` values have zero occurrences 1–2 years ago and suddenly a steep increase in no time.

Please also note that Wikidata items usually don't change while Wikipedia articles sometimes do. What if e.g. the French Wikipedia article *La Poste (entreprise française)* gets renamed to *La Poste (France)*? More than 9,600 objects would have to be edited.

**Comment by matkoniecz** [comment]
> You also need a copy of Wikipedia or an active internet connection to check Wikipedia tags.

In detail? Yes. But basic check can be done based on just article name, what catches most of utterly invalid ones.
