### ISSUE TITLE
Some field values missing formatting

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#8629]
Seems to have occurred since 2.2.0.

In the screenshot it happens in the surface field, however I've seen it in other field as well.

![id220](https://user-images.githubusercontent.com/16965772/128574963-59a5bdb9-171a-46d9-b6af-e406cda56c8a.jpg)

**Comment by 1ec5** [comment]
The values shown in blue, variable-spaced font and title-cased are the ones explicitly listed for translation, although translations aren’t getting pulled in yet: #8600. The monospaced font is intended to emphasize that the other values are raw values that haven’t been manually curated but were instead pulled in from taginfo based on frequency in the database.

https://github.com/openstreetmap/id-tagging-schema/blob/e8d86eb0bdbad8e466a6e06a62899f422440175a/data/fields/surface.json#L6-L19

**Comment by boothym** [comment]
@mbrzakovic have you closed this issue because it has been or will be fixed?

Because I also noticed the opening hours field with a monospaced font for its text.

**Comment by 1ec5** [comment]
That’s intentional: the Opening Hours field accepts a raw value rather than a translatable one. The use of monospaced font in fields is new in v2.20.0.

**Comment by mbrzakovic** [comment]
1ec5 gave correct explanation. Shortly: What you are seeing is a feature, not an issue.

**Comment by boothym** [comment]
Hmm. What's the need for this feature? Does an end user need to know whether a value is translatable or not?

In other fields like buildings the monospaced font is used for the entire set of values in the dropdown. Was this change to add worse looking text discussed anywhere on here?

**Comment by mbrzakovic** [comment]
Sorry for not providing more context earlier. Please take a look at following: https://github.com/openstreetmap/iD/pull/8238, https://github.com/openstreetmap/iD/issues/2708

**Comment by boothym** [comment]
Thanks - my next question is where can people contribute to these translations and is it publicised anywhere so that users who see the monospaced font can go and help with the translations? 😉

**Comment by mbrzakovic** [comment]
https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md#translating. What should be of interest to you is 'Presets' translations that would be pulled in https://github.com/openstreetmap/id-tagging-schema
