### ISSUE TITLE
Can't save a changeset - "Foot Path has no tags"

### ISSUE THREAD

**Issue by gjedeer** [openstreetmap/iD#8634]
I'm trying to save a line tagged as a Foot Path and an error saying "Foot Path has no tags" is appearing. I have about 70 others in the changeset, tagged the same way, which aren't a problem.

![osm-id-bug-2021-08-10_10 30 06](https://user-images.githubusercontent.com/315648/128835756-e7995a0b-3755-40de-8e18-132262d70e6f.gif)

I've also tried deleting said line and I'm getting an empty error message:
![image](https://user-images.githubusercontent.com/315648/128835422-762a98b1-f9a3-4dde-9e23-e22561e9e6e4.png)

Firefox 90.0.2, Ubuntu 20.04, iD 2.20.0 on OSM.org.

There are probably unrelated errors in error console:

```
Uncaught Error: entity w-1 not found
    entity https://www.openstreetmap.org/assets/id-a7caaa0f3f6288026cbae41d1ab0115f47bca016cdcd62a2d26e56bb35e42903.js:61
    extent https://www.openstreetmap.org/assets/id-a7caaa0f3f6288026cbae41d1ab0115f47bca016cdcd62a2d26e56bb35e42903.js:10
    extent https://www.openstreetmap.org/assets/id-a7caaa0f3f6288026cbae41d1ab0115f47bca016cdcd62a2d26e56bb35e42903.js:10
    focusIssue https://www.openstreetmap.org/assets/id-a7caaa0f3f6288026cbae41d1ab0115f47bca016cdcd62a2d26e56bb35e42903.js:13
    d https://www.openstreetmap.org/assets/id-a7caaa0f3f6288026cbae41d1ab0115f47bca016cdcd62a2d26e56bb35e42903.js:26
    contextListener https://www.openstreetmap.org/assets/id-a7caaa0f3f6288026cbae41d1ab0115f47bca016cdcd62a2d26e56bb35e42903.js:4
id-a7caaa0f3f6288026cbae41d1ab0115f47bca016cdcd62a2d26e56bb35e42903.js:61:31920
```

**Comment by mbrzakovic** [comment]
Oh, sorry for this. Thanks for filing this issue, I am suspicious that it is related to #8632.
@gjedeer can you please help us by providing some more info:
- Did this foot path's issues exist prior to your editing? Did you create/edit this entity?
- Did you use undo/redo in your session?
- Did you refresh page + restore changes?

If possible, can you please try to repro this issue in few steps and describe them here?

**Comment by gjedeer** [comment]
Thank you for your quick answer.

* The foot path was created by me in that changeset. It did not exist before.
* I have used undo, yes
* Refreshing + restoring worked! Thank you.

I have tried reproducing but no luck. It was the first line I added, and it had that issue ever since I added it. I just drew a line and marked it as foot path, that's it. Other lines in the changeset did not have this problem.

**Comment by gjedeer** [comment]
@mbrzakovic  I think I got this. Things I did in order to reproduce:
- Restarted browser (which clears all cookies in my configuration)
- Connected start and end of path to existing points

https://user-images.githubusercontent.com/315648/128850457-d39a48da-d633-4ccc-b875-c87b77338ad4.mp4

**Comment by mbrzakovic** [comment]
Thanks @gjedeer!
Can you please try to do the same on https://ideditor.netlify.app/. There have been some validator improvements that might've solved this.

**Comment by gjedeer** [comment]
I was not able to reproduce the problem on that instance. Yay!

**Comment by mbrzakovic** [comment]
Cool. Lets close for now and re-open if this still persists in v2.20.1
