### ISSUE TITLE
Display vintage on maxar layer

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/iD#8644]
Maxar has a WFS API to display the metadata and vintage (imagery acquisition dates and mosaic cutlines) for the Maxar Premium Imagery. This can be made available for integration into iD.

A couple of links related to the Maxar Mosaic WFS:

* [User documentation](https://securewatchdocs.maxar.com/en-us/Miscellaneous/DevGuides/WFS/WFS_Feature.htm?Highlight=wfs%20mosaic  )
  * **MaxarCatalogMosaicProducts** This Feature type provides users with access to Vivid Mosaic product metadata via a single Feature.
  * **MaxarCatalogMosaicSeamlines** This Feature type provides users with access to the seamline information that is available for each Vivid production block.
* [GitHub link](https://github.com/DigitalGlobe/CloudServices/tree/master/ogc-services/wfs/Postman)
 
Maxar is available to discuss access when needed.

**Comment by tyrasd** [comment]
With #9710, this is obsolete at the moment. If access to Maxar imagery were restored at some point in the future, we should definitely try to implement this, though!
