### ISSUE TITLE
Deprecating Maxar standard imagery

### ISSUE THREAD

**Issue by mbrzakovic** [openstreetmap/iD#8647]
From Maxar: 
- Over the last couple years, Maxar imagery services (Standard and Premium) have essentially merged, and quite frankly the Premium is the best layer to use, and most of the pixels are redundant in Standard.

**Comment by jjiglesiasg** [comment]
But right now Premium is not wirking in many areas of the World

**Comment by matkoniecz** [comment]
Layer list is pulled from https://github.com/osmlab/editor-layer-index

**Comment by mbrzakovic** [comment]
Maxar is a special case. It's actually specified in iD in [manual imagery](https://github.com/openstreetmap/iD/blob/develop/data/manual_imagery.json)

**Comment by mbrzakovic** [comment]
@jjiglesiasg could you please state which areas are not covered with Premium imagery?
This can potentially be something that Maxar devs can prioritize.
