### ISSUE TITLE
Add preset for amenity=dog_parking

### ISSUE THREAD

**Issue by carstenhag** [openstreetmap/iD#8648]
I had noticed that this tag was only documented informally at a german OSM page about animals, so I decided to create a page for it: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddog_parking

Would be really helpful to have it inside ID :)

Example: https://www.openstreetmap.org/changeset/109896985

**Comment by matkoniecz** [comment]
That would be on https://github.com/openstreetmap/id-tagging-schema

Note that it was used just 45 times worldwide

**Comment by carstenhag** [comment]
Thanks @matkoniecz, I created it at https://github.com/openstreetmap/id-tagging-schema/issues/233 :).

I'm aware that it only had 48 usages, but I just documented it ~ a month ago. In my small town I already found 3 places, so I do think there would be many to tag. Also, it's really useful for dog owners.
