### ISSUE TITLE
Don't show `name` field for `water=river|stream` and `waterway=riverbank`

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#8668]
Currently iD shows the name field (https://imgur.com/a/y8I7Yk1) for objects tagged with `water=river|stream` or `waterway=riverbank`. It should not suggest adding a name since these areas are not supposed to have names.

Edit: I should've sent this issue in id-tagging-schema repo.

**Comment by jjiglesiasg** [comment]
As far as I know Rivers and water courses are supposed to have names, at least in the latin origin speaking countries. Perhaps we shall remove the Thames, Nile, Volga, Ebro, Danube, Amazon, La Plata, etc, etc. names

**Comment by Dimitar5555** [comment]
Yes water courses are supposed to have names but the areas are not supposed to have.

**Comment by Dimitar5555** [comment]
@mbrzakovic May I know why you choose to close the issue? The comment by jjiglesiasg is clearly referencing water courses, not their areas.

**Comment by mbrzakovic** [comment]
@Dimitar5555 apologies for late reply. I've closed this issue here because I assumed that it was opened in id-tagging-schema which I agree is appropriate place.
