### ISSUE TITLE
iD become unusable after selecting a polygon due to an Uncaught TypeError

### ISSUE THREAD

**Issue by foenyx** [openstreetmap/iD#8673]
(iD version 2.20.1, Firefox 92.0 on Linux, UI Language : French)

I wanted to update an existing polygon, but just after selecting another polygon, a JavaScript exception occurred and iD became unable to select any other polygons.

The exception is probably related to a name validation check, on a polygon with names in French and Breton languages (the stacktrace mentions **uiSectionValidationIssues** and **languageName**)

I trimmed down some attributes and found this short repro method :

1. create (or select) a polygon with :
- `amenity=restaurant`
- `building=yes`
- `name=Restaurant Universitaire`
- `name:br=Preti Skol-veur`
2. select another polygon, it may then yield (not always but pretty often) : 
- two validation warnings (with the 2nd being empty, which is very suspect) 
`<span class="issue-message"><span class="localized-text" lang="fr">Restaurant possède le nom suspect « Restaurant Universitaire »</span></span>` (...) `<span class="issue-message"></span>`
![screenshot_bug_2021-09-03_15-34-53](https://user-images.githubusercontent.com/2771980/132023441-031ca4c1-a960-409b-a1f6-f3bc18b82f9b.png)
- and a JavaScript exception which seems related : 
`
Uncaught TypeError: p is undefined

    languageName https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:6
    message https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:12
    o https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:28
    htmlFunction https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:4
    selection_each https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:4
    selection_html https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:4
    o https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:28
    selection_call https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:4
    a https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:28
    selection_call https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:4
    l https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:21
    selection_call https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:4
    n https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:21
    selection_call https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:4
    reRender https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:21
    uiSectionValidationIssues https://www.openstreetmap.org/assets/id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:28

id-00dd4f5e18aa7be11851e223ed8693582b3f29198d18cff43d1c1c49dcaca813.js:6:24094
`
3. The user cannot select other nodes or polygons in iD, needing a reload of the page and maybe some edit loss if iD is unable to restore all previous-changes.

Hope this will be helpful, cheers!

**Comment by Fabe56** [comment]
Same isssue with iD version 2.20.1, Microsoft Edge Version 93.0.961.38 on Windows 10, UI Language : French.

**Comment by foenyx** [comment]
update one year later (iD 2.21.1) :

There's some kind of improvement. An exception is still occurring, and nearly everything on the work area UI becomes unresponsive (can't select nodes, lines or polygons, can't press most buttons) **except** for the undo button, which salvage the situation as the UI works again. Well ... as long as the user thinks to try to undo.

> Uncaught TypeError: p is undefined
    languageName https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:4
    message https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:10
    o https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:26
    htmlFunction https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:2
    each_default https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:2
    html_default https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:2
    o https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:26
    call_default https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:2
    a https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:26
    call_default https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:2
    l https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:18
    call_default https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:2
    n https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:18
    call_default https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:2
    reRender https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:18
    uiSectionValidationIssues https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:26
    requestIdleCallback handler*uiSectionValidationIssues/< https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:26
    call https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:38
    l https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:10
    promise callback*l https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:10
    o https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:10
    validate https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:11
    call https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:38
    redo https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:9
    n https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:27
    action https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:25
    s https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:25
    contextListener https://www.openstreetmap.org/assets/id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:2
id-0ac2d4ce47c510bb7126ddaaff5ce431b29900dd9c2a7c83badd8a7be7e7d453.js:4:25407

**Comment by foenyx** [comment]
Small update another 10 months later : The bug is still present in v2.25.2 

The initial repro still triggers it. 

Another example would be clicking a polygon with those properties : 

> amenity=townhall
> building=yes
> name=Mairie
> name:br=Ti-kêr

Which will trigger that dreaful error and break the edit area
> Uncaught TypeError: p is undefined
>    languageName https://www.openstreetmap.org/assets/id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:4
> (...)

Thus it's sadly impossible to edit those genericly named breton townhalls or uni restaurants in iD at the moment.

**Comment by Dimitar5555** [comment]
Are you using `fr-FR` locale by any chance? I was able to reproduce the bug using `fr-FR` but not with `fr`.

**Comment by k-yle** [comment]
I've made a PR which fixes this issue: #9737

on a related note, the `wikidata` field will work for `fr-FR` locale soon 🎉 #9638
