### ISSUE TITLE
When merging ways, older ways should be kept

### ISSUE THREAD

**Issue by Discostu36** [openstreetmap/iD#8687]
When merging two ways (e.g. two parts of a highway), the older object should be kept to preserve as much history as possible.

For example: https://www.openstreetmap.org/changeset/111077685

Way ID 12305929 with a history of 14 years should have been kept. 
Way ID 928506251 with a history of 5 months should have been deleted.

Alternatively, ID could ask which way to keep.

**Comment by k-yle** [comment]
this is fixed in #8708
