### ISSUE TITLE
highlight changes in changeset

### ISSUE THREAD

**Issue by sevku** [openstreetmap/iD#8696]
It would be nice if in the view for the changeset there wouldn't just be a rectangle but if the changed nodes and ways were highlighted. It would make it a lot easier to see what exactly has been changed.

**Comment by tordans** [comment]
What view are you referring to exactly?

What I use, is the highlight changes feature:
![image](https://user-images.githubusercontent.com/111561/133552242-eeb9892c-ad6c-4fc1-b3ff-29760cb9dea3.png)

Added things are very easy to see, modified things a bit harder, but in general a good overview.

---

Talking about this, it might be a good idea to add this toggle "highlight changes" to the commit-changes panel in the section that lists all the changes. The map is grayed out at this point, but still it would be a good place to discover that feature…

![image](https://user-images.githubusercontent.com/111561/133552420-83dd1d79-e593-459b-8bbb-612453fd6cc0.png)

**Comment by sevku** [comment]
I mean for example [/changeset/111275430](https://www.openstreetmap.org/changeset/111275430).

**Comment by sevku** [comment]
Oh wait this is not part of iD. Sorry for that.
