### ISSUE TITLE
Need a place to input ```ref=*``` for ```railway=subway_entrance```

### ISSUE THREAD

**Issue by LaoshuBaby** [openstreetmap/iD#8698]
In fact a lot of subway entrance will have a English character or number as its ```ref=*```

But iDeditor don't give mapper a place to input it, ```ref=*``` can only be added manually, this cause unconvenience to mapper, and sometimes people will forget to input.

![图片](https://user-images.githubusercontent.com/42690037/133764335-5b6cedf1-593c-431c-be5c-fd6d7c41a7f2.png)

I think there should someplace to input the ref

**Comment by boothym** [comment]
I think the presets are now in https://github.com/openstreetmap/id-tagging-schema

**Comment by k-yle** [comment]
This was fixed quite a while ago

**Comment by LaoshuBaby** [comment]
> I think the presets are now in https://github.com/openstreetmap/id-tagging-schema

https://github.com/openstreetmap/id-tagging-schema/issues/465

Yes, it was fixed in https://github.com/openstreetmap/id-tagging-schema/commit/540e0004640816fc69562557b0313f92ba2a90c2

I didn't open the issue at the right place in 2021, I'm very sorry! Now it was solved!
