### ISSUE TITLE
Add copyright warning for some commercial mapservice in China

### ISSUE THREAD

**Issue by LaoshuBaby** [openstreetmap/iD#8700]
I noticed a road with ```source=google``` touched a rule and iDeditor give a warning about removing it. I think this good and want to add some canonical commercial mapservice such as "baidu" or  "amap" to the list.

![图片](https://user-images.githubusercontent.com/42690037/133443031-4fa548fa-8e98-4a54-b1da-5a8cc9bfb04b.png)

Where should I go? If in other repository, which files should I edit?  Thanks!

（This issue was first open in [NSI‘s issues](https://github.com/osmlab/name-suggestion-index/issues/5343) and were re-raise in there）

**Comment by tordans** [comment]
I think this could be the list at https://github.com/openstreetmap/iD/blob/fc6c71160c6378fa16e70436304a3e3d6fdb30e2/modules/validations/incompatible_source.js#L10

**Comment by bhousel** [comment]
> I think this could be the list at

Yep, sending a fix for this now 👍

**Comment by bhousel** [comment]
@LaoshuBaby leave it open for now - when PR is accepted it will close automatically..
