### ISSUE TITLE
iD taginfo file seems to be gone

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#8704]
See https://taginfo.openstreetmap.org/projects/id_editor

See for example https://taginfo.openstreetmap.org/tags/natural=tree#projects not listing iD anymore

**Comment by 1ec5** [comment]
#8175 moved it to the id-tagging-schema repository. taginfo/taginfo-projects#119 updates taginfo.

**Comment by 1ec5** [comment]
Also, openstreetmap/id-tagging-schema#238 updates the taginfo project’s name and description to reflect the repository split.

**Comment by matkoniecz** [comment]
ok, then this can be closed I think
