### ISSUE TITLE
Obsolete attributes

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#8715]
Hi,

I have 2 problems when I check "obsolete attributes" in the tab "problems" :
- at Cayenne (French Guyana), the name of the bus network is "agglo'bus". In wikidata you will find one agglo'bus (city of Guéret) and one agglobus (city of Bourges). In Wikipedia, you have 4 agglobus (Bourges, Rodez, Saumur, Fréjus) and one agglo'bus (Gueret). There is no page in wikidata and wikipedia for the agglo'bus network of Cayenne. When I check "obsolete attributes", ID wants to change the name of the network "agglo'bus" to "agglobus". Why ? I can understand that it wants to add tags for wididata and wikipedia (even if there is nothing for Cayenne), but why to change the name of the network when this name exists in wikidata and wikipedia ?
- In Guyana, the official seller for Caterpillar machines is Surmac Guyane Cat. When I check "obsolete attributes", ID wants to add tags for wikidata and wikipedia (to Caterpillar) but also wants to change the name "Surmac Guyane Cat" to  "Caterpillar". If I accept the changes and put back the good name, ID still wants to change the name of the shop. Why ?

Best regards

**Comment by Mahabarata** [comment]
Hi,
the last version of ID (with the new tag "not the same as...") solved the first problem, thanks a lot for this improvement.

But the second one is still there (some shops belong to a trademark but have a local name, not the trademark name) so I don't close this issue.
Best regards

**Comment by 1ec5** [comment]
> In Guyana, the official seller for Caterpillar machines is Surmac Guyane Cat. When I check "obsolete attributes", ID wants to add tags for wikidata and wikipedia (to Caterpillar) but also wants to change the name "Surmac Guyane Cat" to "Caterpillar". If I accept the changes and put back the good name, ID still wants to change the name of the shop. Why ?

Caterpillar coincidentally came up in osmlab/name-suggestion-index#5647. I’d suggest following that discussion instead, since that repository is what supplies the brand-related data and validator rules to iD. Please consider contributing entries about Cayenne’s bus networks to that repository too.
