### ISSUE TITLE
Caterpillar

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#8716]
Hi,

I'm not sure that it is a problem of ID. If not and you know where I should post this message, please tell me.

When I create a new point and if I research "caterpillar", I find one. But the informations are bad : ID gives the tag "shop:trade" and the tag "trade:agricultural_equipement" which are false : they don't work for agriculture (even if they also sell tractors and combine harvesters). The good tag should be "shop:construction_equipement" because their first job is to sell bulldozers, asphalt pavers, excavators, loaders, dump trucks, road rollers and so on.

For example on wikipedia, you will find for the definition of the compagny : Caterpillar Inc. is "the world's largest construction-equipment manufacturer". And this wikipedia page was not written by me ;)

Best regards

**Comment by 1ec5** [comment]
[name-suggestion-index](https://github.com/osmlab/name-suggestion-index/) is where the brand presets come from, so that repository would be the right place to report issues like this.

**Comment by Mahabarata** [comment]
Ok, thanks.

I have posted my message there so I close this one.

Best regards
