### ISSUE TITLE
Filter misspelled twins

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8725]
Here it would be nice if user was only offered the correctly spelled choice, 
![20210928T092842](https://user-images.githubusercontent.com/1230959/135007515-994faa4a-afd7-493a-ae84-6a4a8b28cadb.jpg)

**Comment by jjiglesiasg** [comment]
There are several of those same duplicates wrong written, the choice should be just the correct one.

**Comment by tordans** [comment]
A bit of knowhow on this topic: Those suggestions from the screenshot are sourced from Taginfo. AFAIK with some condition, like "only if x %"(?).

You can find multiple issues in this repo about similar tickets. As far as I remember the answer on those was, that the raw tag editor is for users that know what they are doing. The presets are curated, but the raw tag editor is a sharp knife that is only as good as the source material (AKA what Taginfo shows what we tag).

There was the idea of spellchecking in https://github.com/openstreetmap/iD/issues/7754#issuecomment-716580344.

One way to solve this would be to cleanup the misspelled tags so Taginfo does not show them, but that tuns out to be a lot more complex that it sounds a first, as a few recent discussions about global cleanup efforts show.

**Comment by tastrax** [comment]
In this case its only a couple of records that you could easily fix @jidanni and then in the future the misspelt items will disappear from the ID interface

https://overpass-turbo.eu/s/1bAh

**Comment by jidanni** [comment]
Mappers already have a tough time in the field avoiding bees and thunderstorms, to go around fixing things.

**Comment by tastrax** [comment]
Fixed on your behalf @jidanni (in about 30 seconds) .... no bees or thunderstorms encountered from the comfort of my study.

Consider this closed

**Comment by bhousel** [comment]
Thanks @tastrax
