### ISSUE TITLE
Translator problem on Transifex - no Reviewer

### ISSUE THREAD

**Issue by misibacsi** [openstreetmap/iD#8726]
There are 44 translators in Hungarian language, but no Reviewers. 
81% of texts are translated.
I am willing to be a Reviewer to enable translated texts for users.
I wrote to the so called "Team managers", but received no answer.
The Transifex staff can do nothing to help, they just give the technical background.

What can I do to be a Reviewer in Transifex in "iD Editor team" for Hungarian?

**Comment by mbrzakovic** [comment]
Thanks for reaching out.
Apologies for late reply.
I've looked into your contribution and found it sufficient to appoint you for reviewer position.

**Comment by misibacsi** [comment]
Thank you! In the name of translators to Hungarian, too!
They will be happy.

Milos Brzakovic ***@***.***> ezt írta (időpont: 2021. szept.
29., Sze, 11:30):

**Comment by misibacsi** [comment]
I received the right.
