### ISSUE TITLE
Use Bing when the last user selected imagery isn't available somewhere 

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/iD#8732]
To reproduce:

1. Open https://www.openstreetmap.org/edit#map=18/50.34364/5.15747
2. Change the imagery to Bing then back to the one marked as best (SPW).
3. Open https://www.openstreetmap.org/edit#map=17/28.75531/-97.51904

Result:
The SPW imagery is selected though it isn't available and there isn't any imagery with "best" set, so no imagery is shown.

Expected:
Bing imagery is selected.

**Comment by sudarshbuxyyes** [comment]
@mbrzakovic I would like to work on this issue

**Comment by mbrzakovic** [comment]
@sudarshbuxyyes thanks, feel free to do so.
Please checkout: https://github.com/openstreetmap/iD/blob/develop/README.md#participate
This code https://github.com/openstreetmap/iD/blob/develop/modules/renderer/background.js is related to the bug.

**Comment by Aditya-eddy** [comment]
can i work on this issue?

**Comment by tbertels** [comment]
Instead of just selecting the Bing imagery, it would be even better to select the best available one, and Bing if no best one is available.
