### ISSUE TITLE
Validator dismantles fully-qualified name of branch location

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8734]
[Mathnasium of Blue Ash](https://www.openstreetmap.org/node/4283822858) is tagged `name=Mathnasium of Blue Ash` `brand=Mathnasium` `branch=Blue Ash`. The validator wants to turn it into `name=Mathnasium` `brand=Mathnasium` `branch=Blue Ash`. I would regard this suggestion as mild dataloss.

One could argue that `name=Mathnasium` would reduce clutter on a rendered map and avoid redundancy in search results (avoiding “Mathnasium of Blue Ash, Blue Ash, Ohio”[^1]). But a search engine would benefit from indexing “Mathnasium of Blue Ash” in case it receives that string as input. It shouldn't be expected to know that the fully qualified name can be derived from “`brand` of `branch`” for this particular brand, whereas another brand would derive the fully qualified name from “`branch` `brand`”, and a chain in a language other than English would have a completely different formulation.[^2]

This validator rule is already disabled for some POI types that are commonly known by a fully qualified name, such as `shop=car`. But the POI in question is an `amenity=prep_school`: some `amenity=prep_school` chains like Mathnasium routinely qualify the name with the branch name, while others like Kumon usually do not. There may even be inconsistency within some chains that operate as franchises. This is messy enough that I think the validator should take a less prescriptive approach.

The validator rule should be disabled when `branch` is already tagged. At the very least, the suggestion should move the fully qualified `name` to `official_name` to avoid dataloss.[^3] This would override some `official_name`s coming from NSI, like “Applebee’s Neighborhood Grill”, but those brand-wide tags are less important than the branch-specific one being dismantled here.

[^1]: It just so happens that the `branch` in this case is the name of the surrounding city, but for some chains it can be the name of the neighborhood, the street, or the owner, or the owner’s favorite child.
[^2]: Or if it is expected to know this, then the name suggestion index should store a format string for each brand. Perhaps it could also store some grammar rules, for languages that would apply the locative case.
[^3]: openstreetmap/id-tagging-schema#215 adds an Official Name field, so that it wouldn’t appear to the user as though the information had gone missing.

**Comment by bhousel** [comment]
> This validator rule is already disabled for some POI types that are commonly known by a fully qualified name, such as `shop=car`. But the POI in question is an `amenity=prep_school`: some `amenity=prep_school` chains like Mathnasium routinely qualify the name with the branch name, while others like Kumon usually do not. There may even be inconsistency within some chains that operate as franchises.

Yes I think we can just mark this Mathnasium brand (or even the entire category) with a `preserveTags` property in the NSI to prevent this.
https://github.com/osmlab/name-suggestion-index/wiki/Category-Property-Reference#preserveTags


> The validator rule should be disabled when `branch` is already tagged.

I agree - I thought it was already doing this but I will double check it.
