### ISSUE TITLE
BIG BUG : problems are no more showed

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#8738]
Hi,

a very big bug : when I create an error, for example when I create a new node with no tag, ID doesn't react : nothing in the tab "problems", nothing when I select the node (no problem shown in the left), nothing when I want to save (yesterday and before, it was a blocking error : it was impossible to save. Today you may !!).

Best regards

**Comment by mbrzakovic** [comment]
Hi @Mahabarata, Apologies however, I can't repro the issue, (tried both dep/prod endpoints). 
Could you (or anyone else) please include a screenshot or recording of the stated behavior?

**Comment by Mahabarata** [comment]
Hi,

the next day everything was working again.
It was not a problem of internet connexion because i'm using public internet, I can use 2 different connexions and I had the same problem with both.
Maybe the server was out or so slow that the controls never arrived.
For 4 days all is working  so I close this issue.

Best regards
