### ISSUE TITLE
Mapillary: Re-add the filter by username

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#8742]
In https://github.com/openstreetmap/iD/pull/8372 the filter by username was removed from iD as part of the update to the new Mapillary API.

Current UI:
![image](https://user-images.githubusercontent.com/111561/136526116-d7928407-ed2c-4969-bd95-61f895774b55.png)

@nickplesha hinted in https://github.com/openstreetmap/iD/pull/8372#issuecomment-793721229 that is will be possible, to re-add the filter.

We did have two Mapillary users in our area that have a special setup that results in very good image quality (one with 360°, [one with a high point of view](https://www.openstreetmap.org/user/tordans/diary/395215)), so having such a filter is very helpful to get to the best data. Therefore, it would be great to re-add the filter once possible.

---

A quick look at the technical part of this:

The way I understand the implementation is, that filtering is done in the client after all data was loaded first. I think the used API is https://www.mapillary.com/developer/api-documentation/#coverage-tiles – and it looks like, the username is still not available there. 

The Mapillary Website [still has (and always had even during the migration) a filter by username](https://www.mapillary.com/app/?lat=52.464286882950006&lng=13.45294573390936&z=16&username%5B%5D=tordans), so it has to be possible somehow.

**Comment by simonpoole** [comment]
There is currently no public API for this in mapillary's V4 API. It only works on their website because they -don't- use the public API.

See https://forum.mapillary.com/t/api-v4-sequence-search-and-image-search-with-username-user-key/5406

**Comment by tordans** [comment]
Closing this as duplicate of https://github.com/openstreetmap/iD/issues/10136
