### ISSUE TITLE
render paths under construction thinner than roads

### ISSUE THREAD

**Issue by k-yle** [openstreetmap/iD#8743]
iD normally renders paths thinner than roads, but for roads/paths under construction the width is the same regardless of whether it is a road or path.

It would be nice if `highway=construction` + `construction=path/footway/cycleway/bridleway/steps` was rendered thinner than `highway=construction` + `construction=(any other value)`

Perhaps something like this:

<table>
<tr>
	<td><strong>Before
	<td><strong>After
<tr>
	<td><img src="https://user-images.githubusercontent.com/16009897/136644791-fa9dc801-eb5f-40b3-be62-8d8fa7d5f82c.png"/>
	<td><img src="https://user-images.githubusercontent.com/16009897/136644679-e209bcb1-84f7-48b2-8718-462dc13c4822.png"/>
</table>

**Comment by tastrax** [comment]
Hi Kyle,

 

I think this is a carto rendering issue not an ID issue. There are several issues listed re construction rendering.

 

https://github.com/gravitystorm/openstreetmap-carto/issues/3579

 

Cheers - Phil

**Comment by k-yle** [comment]
Hi @tastrax, distinguishing paths under construction vs roads under construction seems to work well in OSM carto - here's the same example from above.

![image](https://user-images.githubusercontent.com/16009897/136687027-683d5ef7-7da1-418f-a96d-ceba569f6b92.png)

The cycleway under construction is much thinner than the busway under construction

**Comment by tastrax** [comment]
Apologies - my mistake
