### ISSUE TITLE
Include operator tags in data checks

### ISSUE THREAD

**Issue by Johnmapper** [openstreetmap/iD#8752]
Same as issued with the tags network and brand, the tages operator / operator:wikidata /operator:wikipedia should be implemented in the data checking prozess to ensure completing tags for common features.

**Comment by bhousel** [comment]
This was included in #8305, which went live in iD about 3 month ago.  
Are there some features where you're expecting this to work but it doesn't?  

The source dataset for this validation is the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) project, and you can browse https://nsi.guide to see which items are supported.
