### ISSUE TITLE
When a 'contact:*' is already present, ask for key uniformity like 'phone' → 'contact:phone' ecc. and vice-versa

### ISSUE THREAD

**Issue by valerio-bozzolan** [openstreetmap/iD#8770]
### Preamble

While it's unclear whether to prefer one form (`contact:phone=`) or the other one (`phone=`), mixing them up is terrible.

You can say that `phone` is more widespread than `contact:phone`, but `contact:facebook` is more widespread than `facebook`. Here it happens that you mix the two types of contacts and this should probably be discouraged.

### Description

When a `contact:phone=` is already present together with another contact information (like `website=`) iD could ask the user to uniform these keys.

*  https://wiki.openstreetmap.org/wiki/Key:contact

### Example

The situation highlighted in this image should trigger the question:

> ![Screenshot OpenStreetMap iD contact key](https://user-images.githubusercontent.com/6052909/138849787-28f125a4-c1cf-4c24-b20f-64970b829ee3.png)
> https://www.openstreetmap.org/changeset/112866385

* _How do you want to uniform your contact tags?_
   * _Apply shorter tags (most popular)_
   * _Apply Dedicated "contact:" block_

→ If the answers is *Apply shorter tags (most popular)* then `contact:facebook` should be converted to just `facebook`.

→ If the answer is *Apply Dedicated "contact:" block* then `phone` should be converted to `contact:phone`.

In this way we should be able to do not to encourage mixing of the two standards.

**Comment by valerio-bozzolan** [comment]
Note that, at the moment, iD does not populate any Phone/Website/... input text fields if `contact:phone` / `contact:website` / `contact:...` are provided. So these tags in use would maybe need UI coverage.

Since I am not sufficiently opinionated about one standardization or the other one, I hope someone else with these interests will speak up. At the moment I tried to reach a compromise to simply avoid the mix of the two standards.

**Comment by mxdanger** [comment]
> → If the answers is _Apply Default_ then `contact:facebook` should be converted to just `facebook`.

This is not advised. There is already a consensus that social media/web services *should* be prefixed, see examples [here](https://wiki.openstreetmap.org/wiki/Key:contact#Social_media.2C_messengers.2C_web_services). Additionally a [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Social_media_contact_prefix) (by me) has been made that once approved will officially mark unprefixed social media, including `facebook=*` as deprecated.

**Comment by valerio-bozzolan** [comment]
@mxdanger Right. To be more neutral I've renamed "Apply Default" to "Apply shorter tags (most popular)" since a "default" is not an objective observation, while popularity is.

**Comment by danieldegroot2** [comment]
- This issue adds redundant complexity for the user and UI.
- If the mentioned proposal is approved -deprecates short variants for social media tags-, the suggested options would have to be limited to non-social media tags. However, if the user now chooses the shorter, more populair tags for those they'll be met with inconsistency between the social media and non-social media contact tags. ( https://github.com/openstreetmap/id-tagging-schema/issues/121 (ignore facebook `website` discussion))
- iD simply picks one variant to avoid complicating things ( https://github.com/openstreetmap/iD/issues/3915#issuecomment-595818412 )
- If you still want all contact tags to be uniform, there should be a [(new,) succesful proposal](https://wiki.openstreetmap.org/wiki/Proposal_process#Reviving_old_proposals) which gets community consensus. See above mentioned issue, related issues and discussions (esp. tagging mailing list).

**Comment by valerio-bozzolan** [comment]
Understood. Feel free to close since I will not fight for this. I will just use the most popular version.

**Comment by tyrasd** [comment]
559a4ba72 adds support for displaying both variants for the "basic" contact fields, e.g. `website` and `contact:website`. That solves the problem that some existing data is not displayed and users might enter duplicates (or in worst case conflicting data) in the ui fields.

> mixing them up is terrible.

As it was already pointed out above, this could only be really fixed if there was a consensus in the community about which tagging schema to use. As that is unlikely to happen any time soon, data consumers need to handle (by consuming and potentially conflating) both tagging variants anyway. So, mixing the tagging variants up (e.g. `contact:website=… + phone=…`) is only _terrible_ from an esthetic point of view. Which is not great, but I guess something we can live with.
