### ISSUE TITLE
`associatedStreet` relation does not mean its members shouldn't be disconnected

### ISSUE THREAD

**Issue by stragu** [openstreetmap/iD#8771]
### URL

https://www.openstreetmap.org/way/887735280

### How to reproduce the issue?

1. Select way [887735280](https://www.openstreetmap.org/way/887735280) and its node joining it to Gladstone rd (way [991574385](https://www.openstreetmap.org/way/991574385))
2. Right-click the node to see that it is not possible to disconnect it "because it connects members of a relation"

This kind of relation is not related to routable networks or a specific order of members, and therefore iD should let contributors disconnect features that are members of the same relation.

(As to the reason I am editing this: I surveyed the area and the two roads do not connect anymore and now have a physical barrier between them).

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
Fixed in 
c85456438987715e9d243e519200bb4b9134087e for #8804.
