### ISSUE TITLE
Provide a copy/link function for segment id in measurement heading

### ISSUE THREAD

**Issue by cicku** [openstreetmap/iD#8780]
### Description

It would be great to:

1. Hover on the header, it becomes a link which opens `https://www.openstreetmap.org/{way,node,relation}`;
2. Add a button/icon next to the header copying the link above.

This feature would significantly increase the efficiency when trying to get a history of a segment because when there are too many segments in the map, the query feature will often timeout.

### Screenshots

![image](https://user-images.githubusercontent.com/686438/139464772-23e494be-ef21-4ef6-9b01-27057b21fbcb.png)

![image](https://user-images.githubusercontent.com/686438/139465065-1b75238b-60fb-4217-91f6-ea8a261d64c2.png)

**Comment by 1ec5** [comment]
> Hover on the header, it becomes a link which opens `https://www.openstreetmap.org/{way,node,relation}`;

The “View on openstreetmap.org” link at the bottom of the left sidebar opens the element’s page.

**Comment by tyrasd** [comment]
closing because this functionality is already present and the measurement box would not be the right place to put such a link.
