### ISSUE TITLE
Editing lines are too thin

### ISSUE THREAD

**Issue by DeznekCZ** [openstreetmap/iD#8783]
### How to reproduce the issue?

Hello Devs,

last month I have realized that editing view is now displaying all lines in width of 1px.
Was there any update which could break it or is only my fault in some settings

Thanks, DeznekCZ

### Screenshot(s) or anything else?

![OSM_lines](https://user-images.githubusercontent.com/9643627/139739855-75303271-25e7-4731-b9e9-1dc6871e698c.PNG)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by bhousel** [comment]
It looks like you are in Wireframe mode - you might have pressed <kbd>W</kbd> to enter it? 

(The shortcut may use be a different key in other languages, but I think you can press <kbd>?</kbd> to get a list of the key shortcuts)

**Comment by DeznekCZ** [comment]
> It looks like you are in Wireframe mode - you might have pressed W to enter it?
> 
> (The shortcut may use be a different key in other languages, but I think you can press ? to get a list of the key shortcuts)

Yes it was it, I have found it now after second try.
When I was disabling I was thinking it may be applied only on areas, but it also applied on lines.

Thank you for help
![OSM_lines_fixed](https://user-images.githubusercontent.com/9643627/139740906-a5c7b439-f5d2-4a6e-8920-e0b85f168c7f.PNG)

My fault
