### ISSUE TITLE
Improve history panel

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#8784]
### Description

I recently discovered that the "OSM" link in the history panel actually links to the history of an object. However this is not very clear, so I would like to suggest an edit to the text to improve this.

At the first pink dot, it should say "OSM History" and at the second pink dot, it should say "OSM Profile". Unfortunately I wasn't able to edit the text in browser!
![osmh](https://user-images.githubusercontent.com/16965772/139749648-f8125e48-6824-45f6-ab1f-cafefd33ddd1.PNG)

**Comment by mbrzakovic** [comment]
I agree that these link informations can be more user-friendly.

**Comment by 1ec5** [comment]
On the first row of links, each link opens the feature’s history but using different tools. On the second row, each tool opens the user’s profile but using different tools. It would be less confusing to have an unlinked “History:” and “Profile:” label right before the list of links on each row.

**Comment by mbrzakovic** [comment]
What @1ec5 recommended makes sense, although I do have to point out that the tab name is 'History' so the additional History label can seem somewhat redundant. Perhaps in this case a better wording would be: 'View X on/via: '

I would recommend that a better alignment can go a long way in this case, and with the help of simple tooltips it could achieve making more obvious which item each link describes.

e.g. (sketch):
![image](https://user-images.githubusercontent.com/78906108/140306710-49fbc689-8b57-46f7-9ac6-153298a6de1c.png)

**Comment by boothym** [comment]
The reason I opened this issue is because I associated the first "OSM" with just opening the node/way/relation on osm.org - like the "view on osm.org" one in the bottom left already does. It didn't occur to me that would go direct to the history, so anything that makes it clearer is good.

>It would be less confusing to have an unlinked “History:” and “Profile:” label right before the list of links on each row.

I would probably be fine with that.

**Comment by LaoshuBaby** [comment]
> 
> e.g. (sketch): ![image](https://user-images.githubusercontent.com/78906108/140306710-49fbc689-8b57-46f7-9ac6-153298a6de1c.png)

Looks interesting! ♥👍

And this new 2 column can decrease the height of history panel to avoid this kind of hidden: https://github.com/openstreetmap/iD/issues/8699

(And I also have a question, why not add a OSMCha link to the latest editor.)

(Maybe deep history can added to Feature too)

**Comment by tyrasd** [comment]
#8834 improves the ambiguous `OSM` link texts.
