### ISSUE TITLE
Can't merge blank line with relation member

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#8785]
iD v2.20.2 in Vivaldi browser (Chromium) v4.3.2439.56, Linux 64-bit

1. Create multipolygon relation
2. Split at some point
3. Make line with no tags connecting to the split
4. Select the line and the attached relation member
5. <kbd>c</kbd> to merge; it does nothing with the message 'These features can't be merged because they belong to conflicting relations.'

**Comment by 1ec5** [comment]
Duplicate of #8779.
