### ISSUE TITLE
Drop changes when uploading 

### ISSUE THREAD

**Issue by ChildishGiant** [openstreetmap/iD#8787]
### Description

It'd be really nice if one was able to remove certain changes without having to undo and lose everything since that. 

### Screenshots

![image](https://user-images.githubusercontent.com/13716824/139908487-9a7105bc-373c-4492-b842-9ff5ea60a7ce.png)
A bin icon could be added to the right of each change and when clicked those changes would be dropped/reverted.

**Comment by bhousel** [comment]
oh yeah this is #537
