### ISSUE TITLE
Geoportal 2 imagery: Longer loading times than expected

### ISSUE THREAD

**Issue by Asteliks** [openstreetmap/iD#8789]
### How to reproduce the issue?

1. Open the iD editor over any city in Poland [link](https://www.openstreetmap.org/#map=19/52.20700/20.95771).
2. Use the `Geoportal 2: Ortofotomapa` layer
3. Note how long its taking to open in iD
4. Do the same in JOSM - there the same layer seems to load instantly

### Screenshot(s) or anything else?

Something seems to be wrong with iD editor. In Poland the Geoportal 2 layers are loading painstakingly long. At first I thought that this is something with the provider but the exact same layers load instantly in JOSM. Thus I'll need some help concerning this topic.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Microsoft Edge

**Comment by tyrasd** [comment]
Hi. I can partially confirm the issue. The responses from the WMS layer are indeed very slow. But I see the very same behaviour also in JOSM when using the `Geoportal 2: Orthophotomap (latest aerial imagery)` layer. In JOSM there exists also a layer called `Geoportal 2: Orthophotomap (aerial image) WMTS` which is fast and seems to deliver the same results as the WMS layer used by iD.

Can you confirm that the following URL used in iD as a custom imagery source works and delivers the same imagery as the slow `Geoportal 2: Ortofotomapa` layer? If yes, we should simply update the [editor-layer-index](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson?short_path=e7ec024) to use the quicker WMTS endpoint.


````
https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTOFOTOMAPA&STYLE=default&FORMAT=image/jpeg&tileMatrixSet=EPSG:3857&tileMatrix=EPSG:3857:{zoom}&tileRow={y}&tileCol={x}
````

**Comment by Asteliks** [comment]
Yes geoportal shares the same layers via both WMS and WMTS. You can find all of the available layers here: https://www.geoportal.gov.pl/uslugi/usluga-przegladania-wms

Unfortunately the given link doesn't work. Are you sure that iD can work with WMTS? If yes, that would be great

**Comment by tyrasd** [comment]
> Unfortunately the given link doesn't work. Are you sure that iD can work with WMTS? If yes, that would be great

Pretty sure, yes. :wink: 

![image](https://user-images.githubusercontent.com/1927298/140123863-b1fd6495-85b1-4602-b255-7e950c6965de.png)

PS: AFAIR there is a glitch in iD: if you previously used the "Custom Background" option for a WMS layer the tool doesn't correctly detect WMTS/TMS links until iD is restarted. Maybe that's why it didn't work for you?

Anyway, would you like to open a PR for the change on the editor-layer-index?

**Comment by simonpoole** [comment]
@Asteliks if the WMTS server provides a Google/OSM compatible tileset then you can use the corresponding url as a "TMS"  url. But that isn't "WMTS" support to be clear.

**Comment by Asteliks** [comment]
yea I thought so that we didn't have proper WMTS support
