### ISSUE TITLE
iD couldn't proceess a conflict

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#8790]
### How to reproduce the issue?

1. Open a location and edit a node without uploading
2. Open the same area from another profile in iD and update the same node
3. Upload from the first account
4. Try to upload from the second account

### Screenshot(s) or anything else?

The check for conflicts is stuck in an infinite loop. The console is overfilled with the same error
![image](https://user-images.githubusercontent.com/19364673/140080384-cff392c1-8a17-4e3d-a748-9a6dd8748814.png)
Here is a video of the result from the issue

https://user-images.githubusercontent.com/19364673/140080515-60afc752-4101-4e50-aeca-ddc0c1894e0f.mp4

:

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by bhousel** [comment]
this is also #7199
