### ISSUE TITLE
Spurious "[street name] has no tags" error when saving new features

### ISSUE THREAD

**Issue by SammyTheSnake** [openstreetmap/iD#8793]
Adding streets and houses from a gpx trace I took, I tried to save it and got an error saying "Wilkshire Road has no tags" but it has 4 tags :-/

Attached:

* screenshot of the error showing the tags
![image](https://user-images.githubusercontent.com/3084398/140615028-8b72cce2-8354-4cab-9f10-af6417e68750.png)

* changeset file (with a txt extension because github): 
[changes.txt](https://github.com/openstreetmap/iD/files/7490749/changes.txt)

**Comment by tyrasd** [comment]
This looks like a bug, but I can't reproduce it on my side. Can you tell the exact steps you took to get to this error message?

**Comment by LaoshuBaby** [comment]
Sometimes on slow computer the warn may remain for few seconds, I think this is a kind of validator caused dalay with my experience.

( And looks like you are using RapiD, is this also occur in original iD ?

**Comment by DujaOSM** [comment]
This happens to me regularly in iD. I tend to create quite large changesets with long ways, and after a number of changes iD gets generally slower. It's just a minor annoyance, it tends to disappear after a second or two.
