### ISSUE TITLE
iD NSI Integration splits Costa Drive-Thru into a branch of Costa called "Drive-Thru"

### ISSUE THREAD

**Issue by peternewman** [openstreetmap/iD#8794]
### URL

https://www.openstreetmap.org/node/7155289750/history

### How to reproduce the issue?

cc @bhousel - I don't know if you want this here, or we should gather the regional variations in NSI?

Select a Costa called "Costa Drive-Thru", note how it offers to set the branch name to "Drive-Thru" and tag it as a Costa.

Ideally it should drop the branch name at this point, probably see also "Drive Thru" and "Through" variants.

For bonus points it could tag drive_through=yes

Or I guess alternatively does NSI just need separate "Costa" and "Costa Drive-Thru" brands added?

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by bhousel** [comment]
hey @peternewman !

> Or I guess alternatively does NSI just need separate "Costa" and "Costa Drive-Thru" brands added?

This should fix the problem quickly, and I can do that.  For a brand that has a few variations, we can just provide items for each one (Similar to "Gap", "Gap Kids", "Gap Factory").

I was wondering whether the name of these businesses is _really_ "Costa Drive-Thru" but looking at some examples I found, it seems reasonable for people to name them that way: https://myvirtualcoffeehouse.com/costa-coffee-drive-thru-locations-near-me
![Costa-drive-thru](https://user-images.githubusercontent.com/38784/140951143-b6a84c9d-6f4e-4e04-8fd7-2ff8fbff032f.png)

**Comment by peternewman** [comment]
> hey @peternewman !
> 
> > Or I guess alternatively does NSI just need separate "Costa" and "Costa Drive-Thru" brands added?
> 
> This should fix the problem quickly, and I can do that. For a brand that has a few variations, we can just provide items for each one (Similar to "Gap", "Gap Kids", "Gap Factory").

Great, that sounds like a plan then. I've opened https://github.com/osmlab/name-suggestion-index/pull/5676 to resolve it, so I'll close this.

> I was wondering whether the name of these businesses is _really_ "Costa Drive-Thru" but looking at some examples I found, it seems reasonable for people to name them that way: https://myvirtualcoffeehouse.com/costa-coffee-drive-thru-locations-near-me ![Costa-drive-thru](https://user-images.githubusercontent.com/38784/140951143-b6a84c9d-6f4e-4e04-8fd7-2ff8fbff032f.png)

Pedantically they don't seem to have a hyphen in the name:
https://www.geograph.org.uk/tagged/Costa+Drive+Thru
