### ISSUE TITLE
Radio buttons where there are multiple keys chosen show the first one alphabetically as selected

### ISSUE THREAD

**Issue by peternewman** [openstreetmap/iD#8796]
### URL

https://www.openstreetmap.org/way/423881224

### How to reproduce the issue?

Look at an object which has some form of radio button interface implemented via multiple keys, which appears to currently be just these two fields:
https://github.com/openstreetmap/id-tagging-schema/blob/bde8a416c80cbbb27a0ad36df3c6dcec3151ec8b/dist/fields.json#L2805-L2812
https://github.com/openstreetmap/id-tagging-schema/blob/bde8a416c80cbbb27a0ad36df3c6dcec3151ec8b/dist/fields.json#L1083-L1095

I know the second one has been somewhat divisive:
https://github.com/openstreetmap/iD/issues?q=is%3Aissue+toilet

So without wishing to re-open those debates, given a radio button is currently used to render these (and hence you can't select more than one choice), wouldn't it be better if no option was selected on the radio when more than one was chosen (so the blue highlighting was more obvious).

Logically I could imagine the second existing and indeed a bit of Overpass searching found some fords in tunnels, so they're both real world scenarios.

Example node:
Structure: https://www.openstreetmap.org/way/423881224
Toilet: https://www.openstreetmap.org/node/411286195

### Screenshot(s) or anything else?

Structure:
![image](https://user-images.githubusercontent.com/6216436/140804091-151a536f-af7b-4ba2-96ae-a2562cfaedab.png)
![image](https://user-images.githubusercontent.com/6216436/140804160-98290a7b-a4b7-46a8-9af4-717dd4669d4e.png)

Toilets:
![image](https://user-images.githubusercontent.com/6216436/140802322-9a7d3f78-7f91-4728-bd0c-5b3294c98472.png)
![image](https://user-images.githubusercontent.com/6216436/140802446-a7fda29b-4f3a-4c23-84d6-1bcc2c30d9fd.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
I think what you’re seeing is that the field checks the radio button that comes last visually, not first alphabetically. The radio buttons have the same `name` attribute, so the browser only allows one to be checked at a time, but this code checks each applicable radio button in order, regardless of the other radio buttons. That causes the browser to uncheck all the previously checked radio buttons:

https://github.com/openstreetmap/iD/blob/2f9285e0115e6bc0aebd46664e84c6a7e0e02755/modules/ui/fields/radio.js#L269-L274

The blue highlighting for multiple selection is subtle indeed. I wonder if that’s a side effect of implementing simultaneous editing of multiple features in #7306. It looks slightly different when selecting two features with different values for the same key, but none of the radio buttons is checked, which is good:

<img src="https://user-images.githubusercontent.com/1231218/140814875-e98a3aca-1a2a-423a-870d-30e4cf43cf53.png" width="359" alt="toilets">

**Comment by peternewman** [comment]
> I think what you’re seeing is that the field checks the radio button that comes last visually, not first alphabetically.

Well spotted @1ec5 , I clearly hadn't tested well enough and just made assumptions.

Thanks for fixing it @tyrasd !
