### ISSUE TITLE
Tags blocks easily bypassable

### ISSUE THREAD

**Issue by martinoscag** [openstreetmap/iD#8806]
### How to reproduce the issue?

**name tag block when having wikidata associated**
1. Go on an element with wikidata query number
2. You will see that the name tag is grey and can't be modified unless removing wikidata tag
3. This is no longer true if editing the name value in the tags.
But this is not a major problem

This is
**upload page default tags blocked**
1. Go in the page for uploading changeset
2. Open the changeset tags page
3. You will see that you can't edit them
4. All you have to do to edit them is switching to text mode for entering tags.
Now, I don't know if this works or if the software restore all the tags when you upload.

I know that is not strictly a bug, but I couldn't find a better option when creating the issue.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by bhousel** [comment]
> **name tag block when having wikidata associated**
> 
> 1. Go on an element with wikidata query number
> 2. You will see that the name tag is grey and can't be modified unless removing wikidata tag
> 3. This is no longer true if editing the name value in the tags.
>    But this is not a major problem

Yes, this is expected.. When I built this feature, I did intend for users who know what they are doing to be able to edit the `name` values in the raw tag editor.


> **upload page default tags blocked**
> 
> 1. Go in the page for uploading changeset
> 2. Open the changeset tags page
> 3. You will see that you can't edit them
> 4. All you have to do to edit them is switching to text mode for entering tags.
>    Now, I don't know if this works or if the software restore all the tags when you upload.

In this situation it does _look_ like the user can can modify the readonly tags, but actually they are not editable and they retain their readonly values.  I wasn't able to make this textbox in a way that parts of it were editable and parts not.
