### ISSUE TITLE
KartaView name not updated

### ISSUE THREAD

**Issue by martinoscag** [openstreetmap/iD#8807]
### How to reproduce the issue?

I know this isn't a bug but this GitHub doesn't give enough options to select type of issue.
KartaView is still referred to as OpenStreetCam in <Map Data<Photo Overlays.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by 1ec5** [comment]
Looks like these strings need to be updated (and their translations):

https://github.com/openstreetmap/iD/blob/5f58b533fffc4c85deefa6e4dc7589073cce1544/data/core.yaml#L1408-L1412

**Comment by matkoniecz** [comment]
not sure is it desirable to rename also string names

**Comment by martinoscag** [comment]
> not sure is it desirable to rename also string names

Why not? I'm no expert.

**Comment by tyrasd** [comment]
> not sure is it desirable to rename also string names


I've renamed also the internal modules/variables/css-classes/etc. :see_no_evil: 

Everything should still work as before, but a little double testing on the develop instance at https://ideditor.netlify.app would be very much appreciated.

<hr>

> I know this isn't a bug but this GitHub doesn't give enough options to select type of issue.

off topic, but there is an option to open a blank ticket. It's quite well hidden, though :see_no_evil: 
<img src="https://user-images.githubusercontent.com/1927298/142021013-2ab62da9-f868-4cf7-9622-334ce31ac4a9.png" width=250px>

**Comment by 1ec5** [comment]
I’m getting an `SSL_ERROR_BAD_CERT_DOMAIN` error in Firefox 94 when attempting to access https://www.kartaview.org/:

https://github.com/openstreetmap/iD/blob/c85456438987715e9d243e519200bb4b9134087e/data/core.yaml#L1612

The www.kartaview.org domain still has an SSL certificate restricted to OpenStreetCam branding:

> openstreetcam.org, api.openstreetcam.org, dashboard.openstreetcam.org, internal.openstreetcam.org, www.openstreetcam.org

https://kartaview.org/ appears to be unaffected.

**Comment by 1ec5** [comment]
e2a5345c7fa8f6555b4c2b22d14a4f4eca717bbc replaces www.kartaview.org with kartaview.org.

**Comment by tyrasd** [comment]
thanks for the fix @1ec5!
