### ISSUE TITLE
Allowing ferry transportation for all vehicles for specific route

### ISSUE THREAD

**Issue by berkantdeniz** [openstreetmap/iD#8809]
### Description
**[Question]**
I have been trying to draw a route from  Geyiklii / Turkey to Bozcaada / Turkey 
--> https://osm.org/go/x0jEq99

There were no routes defined before and I added proper tags with using iD Editor to allow routes with using OSRM service. 
After adding proper tags to the route and two waypoints, OSRM returns a bicycle and walk modes but the service is not returning a route for traveling on a car. Log of changes I made for this particular route  
-->https://www.openstreetmap.org/user/berkantdenizaktas/history#map=14/39.8271/26.1172

Just like bicycle and foot tags, related car tags are defined on the route. However, there is still no route defined between these two locations. If I am not mistaken, OSRM Service is updated every 24 hours by using the https://www.geofabrik.de/ data which is imports OSM Data every day. Thus, observing changes and interpreting them has a buffer on the user's side.

I wonder if the root cause of the problem is a bug? or some missing/wrong tags or not related with OSM rather related with other sources(maybe OSRM Lua profiles)?

Thank you for your works and contributions,
Regards

**Comment by tyrasd** [comment]
I strongly suspect that the absence of the `highway` tag on https://www.openstreetmap.org/way/331475482 is the culprit. However, this is not an issue with the iD editor at all. Please ask general mapping related questions on an appropriate platform, such as https://help.openstreetmap.org/ or another of [OSM's communication channels](https://wiki.openstreetmap.org/wiki/Contact_channels).
