### ISSUE TITLE
Unclear validator warning about standalone node with vertex-only tag

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8812]
If you create standalone node and tag it with a tag that iD only expects to appear on a vertex, such as `highway=toll_gantry`, the resulting message isn’t clear enough about how to resolve the issue:

<img src="https://user-images.githubusercontent.com/1231218/142155091-35b6dca0-7e40-436f-9eaa-0d64ffd398a2.png" width="359" alt="Open Road Toll should be part of a line or area based on its tags">

“Part of a line or area“ could be misinterpreted to mean “tagged on a line or area”. [This user](https://lists.openstreetmap.org/pipermail/tagging/2021-November/062958.html) tried to redraw the toll gantry as a line and got a different error message, “Highway Feature should be a point, not a line.”

It’s probably a good thing that the message avoids mathematical jargon like “vertex” and OSM jargon like “node”, but what’s a better way to phrase the message so that the user knows to drag the point over to the nearest line or area? Maybe “should be attached to a line or area”?

**Comment by matkoniecz** [comment]
+1 to 

> should be attached to a line or area

**Comment by tyrasd** [comment]
also a +1 from me for _"attached to"_ as a more explicit wording here.
