### ISSUE TITLE
Black tiles using CyclOSM background

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8815]
### URL

https://www.openstreetmap.org/edit#map=18/24.17702/120.86780

### How to reproduce the issue?

Choose CyclOSM background

### Screenshot(s) or anything else?

![20211119T010425](https://user-images.githubusercontent.com/1230959/142462467-8c9c7835-32b1-40e6-b61b-bd7df6e9b1f4.jpg)

### Which iD Editor versions do you see the issue on?

Official

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
I can't reproduce the issue right now. Also, this is unrelated to iD and would need to be reported to the [CyclOSM](https://wiki.openstreetmap.org/wiki/CyclOSM) project. :blush:
