### ISSUE TITLE
Add "Use Shift click first to select just one line."

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8818]
### Description

Here "Divide these lines at this point" needs added "(Use Shift+click instead to just work on the current line.)" Else the user needs to read #7992.

### Screenshots

![20211119T032358](https://user-images.githubusercontent.com/1230959/142483618-e5506850-2d24-4442-b23c-5fa0c1d4cefb.jpg)

**Comment by tyrasd** [comment]
> the user needs to read #7992

(Slightly joking:) It would be sufficient to read the built-in help:
<img src="https://user-images.githubusercontent.com/1927298/143057245-49b98b73-cff0-4436-9875-bb57cac3e9e0.png" width="450px">
:wink: 

On topic, after actually reading #7992, I still don't get what the big deal is about users accidentally splitting a way on one additional intersection point. Generally speaking, shorter lines are easier to handle when mapping than long ones (e.g. in terms of a reduced potential of upload conflicts and easier precise mapping of properties such as road surfaces, number of lanes, etc.). Also for relations such as multipolygons or routes it does not make a difference if the consisting ways are split.

That said, I guess it would also not hurt to put a small hint in the tooltip. The benefit would be that users could find out about the other functionality of the split operation via that. I'll think about it.

**Comment by jidanni** [comment]
Actually more buttons should appear in such cases:
- One button for splitting the current line.
- One button for splitting all lines.

**Comment by jidanni** [comment]
(I am usually splitting the case where the ~~two~~ four roads have three names, not two as assumed by the previous mapper.)

**Comment by boothym** [comment]
Funnily enough I came here to post about the same issue. With the image below I wanted to split the service road and delete it between the other two roads - so I clicked on it, then selected the point and pressed X. However that split the tertiary road as well. At least I now know to select the road + point using shift before splitting! 😃 
![idsplit](https://user-images.githubusercontent.com/16965772/143662067-97347ab5-c919-4087-a3c6-64463c9b52ab.PNG)

> On topic, after actually reading #7992, I still don't get what the big deal is about users accidentally splitting a way on one additional intersection point. Generally speaking, shorter lines are easier to handle when mapping than long ones (e.g. in terms of a reduced potential of upload conflicts and easier precise mapping of properties such as road surfaces, number of lanes, etc.).

Sure, but if I need to have more precise mapping then I will split it intentionally. In the example above, after the tertiary road has been split then I would need to rejoin or select both sections if I wanted to add a surface tag to it. Suppose it is just unexpected and perhaps unnecessary behaviour from the editor :wink:

**Comment by jidanni** [comment]
> I still don't get what the big deal is about users accidentally splitting a way on one additional intersection point. Generally speaking, shorter lines are easier to handle when mapping than long ones...

Well if the government changes Norfsberg Lane to Nerfsburg Lane, and somebody has for no reason split it into five lines, then we must edit five slices instead of one. 

> easier precise mapping of properties such as road surfaces, number of lanes, etc.).

Well we usually know and map the name of a road, and only if we later have spare time, go and visit it to find out what kind of pavement it is.

**Comment by 1ec5** [comment]
The Shift-modified context menu items feel more natural on macOS, where [dynamic menu items](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/#dynamic-menu-items) are pervasive. But this convention is less familiar to users on Windows and Linux, where menu items are typically shown regardless of modifier keys and only [Office](https://kb.iu.edu/d/ajww) hides lesser-used items. Dynamic menu items are great for reducing clutter and making the most common operations convenient to access, but there is a tradeoff in discoverability. Adding a hint to the tooltip is a great idea; users would be much more likely to read that than the full help documentation.

**Comment by tyrasd** [comment]
this is how this looks now: 

<img src="https://user-images.githubusercontent.com/1927298/144076549-d84439c2-df72-4e2a-bd01-3f6a72c560b9.png" width=380>
