### ISSUE TITLE
Switching custom layer does change the layer

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#8822]
### URL

https://www.openstreetmap.org/edit#map=19/52.47597/13.44778

### How to reproduce the issue?

This is my custom layer URL:

`https://mapproxy.codefor.de/tiles/1.0.0/strassenbefahrung/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/alkis_30/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/zoom/mercator/{z}/{x}/{y}.png#`

The `#` is there to allow for a quick switch between layers even though only one custom layer can be configured.

When I change the URL and click OK, the layer does not change. Even panning / zooming so fresh images are loaded still loads the custom layer selected before.

There is a another active issue (#8057) with switching TMS and WMS, but those are all TMS layer, so I assume this might be something new.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
can you please share step-by-step instructions for how to reproduce this bug.

I am able to paste the above mentioned custom layer URL without any issues of changing layers of to a different custom layer URL. I assume the exact order of the performed operations might be relevant to trigger this bug. :thinking:

**Comment by tordans** [comment]
I cannot reproduce the issue anymore either. No idea what went wrong the last time … – Will keep a lookout for this, but for now all is good. Thanks for checking.

**Comment by tordans** [comment]
I have this issue again on ATM https://www.openstreetmap.org/edit?editor=id&way=127361055#map=19/52.51351/13.45877.

The last time I used the editor yesterday ways with this custom tiles, which as a WMS service.
```
https://isk.geobasis-bb.de/ows/alkis_wms?EXCEPTION=inimage
&FORMAT=image/jpeg
&TRANSPARENT=false
&VERSION=1.1.1
&SERVICE=WMS
&REQUEST=GetMap
&LAYERS=adv_alkis_gesetzl_festlegungen,adv_alkis_bodensch,adv_alkis_oeff_rechtl_sonst_festl,adv_alkis_tatsaechliche_nutzung,adv_alkis_gewaesser,adv_alkis_vegetation,adv_alkis_verkehr,adv_alkis_siedlung,adv_alkis_gebaeude,adv_alkis_flurstuecke
&styles=
&SRS={proj}
&WIDTH={width}
&HEIGHT={height}
&BBOX={bbox}#https://mapproxy.codefor.de/tiles/1.0.0/strassenbefahrung/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/alkis_30/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/zoom/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020_true/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2021/mercator/{z}/{x}/{y}.png#
```

Today I opened OSM again, switched the layer to a TMS layer:

```
https://mapproxy.codefor.de/tiles/1.0.0/strassenbefahrung/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/alkis_30/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/zoom/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020_true/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2021/mercator/{z}/{x}/{y}.png#https://isk.geobasis-bb.de/ows/alkis_wms?EXCEPTION=inimage
&FORMAT=image/jpeg
&TRANSPARENT=false
&VERSION=1.1.1
&SERVICE=WMS
&REQUEST=GetMap
&LAYERS=adv_alkis_gesetzl_festlegungen,adv_alkis_bodensch,adv_alkis_oeff_rechtl_sonst_festl,adv_alkis_tatsaechliche_nutzung,adv_alkis_gewaesser,adv_alkis_vegetation,adv_alkis_verkehr,adv_alkis_siedlung,adv_alkis_gebaeude,adv_alkis_flurstuecke
&styles=
&SRS={proj}
&WIDTH={width}
&HEIGHT={height}
&BBOX={bbox}#
```

My console shows this URL:
[`https://mapproxy.codefor.de/tiles/1.0.0/strassenbefahrung/mercator/%7Bz%7D/%7Bx%7D/%7By%7D.png#https://mapproxy.codefor.de/tiles/1.0.0/alkis_30/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/zoom/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020_true/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2021/mercator/{z}/{x}/{y}.png#https://isk.geobasis-bb.de/ows/alkis_wms?EXCEPTION=inimage&FORMAT=image/jpeg&TRANSPARENT=false&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=adv_alkis_gesetzl_festlegungen,adv_alkis_bodensch,adv_alkis_oeff_rechtl_sonst_festl,adv_alkis_tatsaechliche_nutzung,adv_alkis_gewaesser,adv_alkis_vegetation,adv_alkis_verkehr,adv_alkis_siedlung,adv_alkis_gebaeude,adv_alkis_flurstuecke&styles=&SRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=1487158.8221093756,6887893.4918749975,1506726.701347656,6907461.371113281#`](https://mapproxy.codefor.de/tiles/1.0.0/strassenbefahrung/mercator/%7Bz%7D/%7Bx%7D/%7By%7D.png#https://mapproxy.codefor.de/tiles/1.0.0/alkis_30/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/zoom/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2020_true/mercator/{z}/{x}/{y}.png#https://mapproxy.codefor.de/tiles/1.0.0/2021/mercator/{z}/{x}/{y}.png#https://isk.geobasis-bb.de/ows/alkis_wms?EXCEPTION=inimage&FORMAT=image/jpeg&TRANSPARENT=false&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=adv_alkis_gesetzl_festlegungen,adv_alkis_bodensch,adv_alkis_oeff_rechtl_sonst_festl,adv_alkis_tatsaechliche_nutzung,adv_alkis_gewaesser,adv_alkis_vegetation,adv_alkis_verkehr,adv_alkis_siedlung,adv_alkis_gebaeude,adv_alkis_flurstuecke&styles=&SRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=1487158.8221093756,6887893.4918749975,1506726.701347656,6907461.371113281#)

The page shows 
> invalid request (/tiles/1.0.0/strassenbefahrung/mercator/{z}/{x}/{y}.png)

So it looks like, the `{}` does not get interpreted.

I tried hard reloading, which did not change anything. I tried resetting the local storage value but that did not change anything either.

**Comment by tordans** [comment]
Ah, know where this issue is coming from: Once I remove the WMS layer, which I only added yesterday, the logic that decides to pick WMS or TMS works again. This logic seems to look at the whole string (a fair assumption, the equivalent to `window.location.href`), not just the part without the hash (which is not relevant for the WMS/TMS service).

**Comment by tyrasd** [comment]
Yeah, your URL contains both WMS and tile/TMS tokens, which confuses the [layer type detection](https://github.com/openstreetmap/iD/blob/v2.20.4/modules/renderer/background_source.js#L119-L130), because it doesn't "know" about the hash part of an URL.
The way you use the custom imagery input field (which is to be able to store more than one source) is kind of a niche use case to be honest, but it should also not be too hard to fix.
