### ISSUE TITLE
Website link in editor links to openstreetmap.org when http/https prefix missing

### ISSUE THREAD

**Issue by andrewpmk** [openstreetmap/iD#8827]
### How to reproduce the issue?

Website link redirects to openstreetmap.org when http:// or https:// is missing.

To reproduce:
- Enter a website link in the website field of editor with the http:// or https:// prefix missing
- Click the "visit website" link to the right of the website (the arrow pointing up and to the right)
- For example, I was editing a funeral home and entered website www.turnerporter.ca
- Click on link, redirects me to https://www.openstreetmap.org/www.turnerporter.ca
- Should either redirect to https://turnerporter.ca/, or display a warning/error that the http:// or https:// prefix is missing and suggest that you add the prefix

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/10249827/143688251-6c13d970-957f-4d8e-8c64-fff151b64c9c.png)
![image](https://user-images.githubusercontent.com/10249827/143688259-5f2caa85-416f-4390-b9b1-e5a41a4c7bd4.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
I think the field was set to `type="url"` at one point, so that the browser would highlight a malformed URL, as seen in https://github.com/openstreetmap/iD/issues/5658#issuecomment-450235505. These days, it’s just a `type="text"`. I wonder if that changed as part of factoring out id-tagging-schema as a separate repository (#8175 etc.).

**Comment by tyrasd** [comment]
Btw: there used to be a validator for this, but it was removed in #6831
