### ISSUE TITLE
Unable to change tag key on selection when objects have multiple values

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#8836]
Selected two buildings, each with different building values (yes and residential). Then I tried to edit the building tag key to be "demolished:building" - but iD would not let me edit the tag at all. 

IMO this is not expected behaviour, and I'm not sure why it would not be supported (it is in JOSM).

**Comment by tyrasd** [comment]
> IMO this is not expected behaviour, and I'm not sure why it would not be supported

I agree that this is a bug: The key of a tag in a multi-selection with non-multiple values can be changed without problems (say you selected two buildings with the `yes` value in your example) – therefore it should also be allowed to do the same for tags with conflicting values.

**Comment by boothym** [comment]
Thanks, I'll try and remember to use the word "key" next time 😃
