### ISSUE TITLE
Add a Feature Type for the emergency=assembly_point tag

### ISSUE THREAD

**Issue by CoderThomasB** [openstreetmap/iD#8849]
### Description

Currently the emergency=assembly_point is not accessible from the Feature Type selection menu meaning that the emergency=assembly_point has to be added manually; this makes mapping of assembly point much harder. It would be nice to have an "Emergency Assembly Point" type listed in that menu.

[https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dassembly_point](https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dassembly_point)

**Comment by tyrasd** [comment]
can you open a ticket for this in the [`id-tagging-schema` repository](https://github.com/openstreetmap/id-tagging-schema/issues/new) please?

**Comment by CoderThomasB** [comment]
Ok, I have move this to [https://github.com/openstreetmap/id-tagging-schema/issues/292](https://github.com/openstreetmap/id-tagging-schema/issues/292)
