### ISSUE TITLE
Order imagery layers

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#8854]
### Description

Recently, some imagery layers were added to iD, but some mappers are complaining that, for example, CyclOSM (which is not a satellite layer) is the second layer in the list now, which shouldn't have such priority position. Is there a way to organize the layers for a given country by relevance in descending order?

**Comment by tordans** [comment]
This sounds like https://github.com/openstreetmap/iD/pull/8826

**Comment by AntMadeira** [comment]
Yup. Missed that one. Thanks, @tordans.
