### ISSUE TITLE
AU phone numbers

### ISSUE THREAD

**Issue by Fizzie41** [openstreetmap/iD#8855]
### How to reproduce the issue?

When entering telephone numbers in Australia, iD usually displays an example as +61 1 2345 6789, which is a correctly formatted example of a fake Australian phone number.

Recently (the last month or so?) though, I've noticed that it sometimes displays +61 2 9000 0000? While also correctly formatted, this is actually a valid, connected telephone number!, so I'm wondering if it should be shown? 

It's very hard to show a live example of this problem though, because even when I've taken a screen-shot as below, when I've then gone back to it, it has corrected itself to the 2345 6789 number?

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/35707521/146475060-45c599c6-41f7-41ea-b0ab-dcc279aae9a0.png)

![image](https://user-images.githubusercontent.com/35707521/146475817-7f467ce4-9ac2-4af3-82bf-b4d6e2bf2c88.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by tastrax** [comment]
Mmmm - maybe its related to a particular preset? Any idea which preset you may have been using?

**Comment by tastrax** [comment]
dist/translations/en-AU.json and dist/translations/en-AU.min.json in the id-tagging-schema

**Comment by Fizzie41** [comment]
Possibly shop=clothing? As mentioned, I've seen it a few times, then I went looking at already mapped shops to try to find one without a phone number already listed.

The one I found was here: https://www.openstreetmap.org/edit#map=19/-28.03551/153.42807, & it was "Zara" clothing. When I've just looked at it now, it was once again showing the 9000 0000 number, but if you click on anything else, then go back to it, it's changed to 2345 6789.

**Comment by Fizzie41** [comment]
Sorry, that should be shop=clothes!

**Comment by LevinGar** [comment]
@Fizzie41 Did that situation occurs if you click on the telephone box? or just by clicking the Edit Feature side bar?
Btw, I am trying to reproduce it using Chrome but nothing appears

**Comment by tastrax** [comment]
I think the issue in the id-tagging-schema as listed above. Alas I am no coder so unsure how to fix it

![image](https://user-images.githubusercontent.com/8775395/146495344-b5e10c2e-b6d9-4490-b5d0-0fc64dcf299f.png)

**Comment by Fizzie41** [comment]
> @Fizzie41 Did that situation occurs if you click on the telephone box? or just by clicking the Edit Feature side bar? Btw, I am trying to reproduce it using Chrome but nothing appears

With Zara as mentioned above, when I click on the existing icon, the side-bar opens, & 9000 0000 shows, greyed out, in the Telephone field.

I did another clothing shop this morning, & I think that was another time I noticed it?

As mentioned though, if you leave Zara, click on any other feature, then return to Zara, the "proper" 2345 6789 number shows. If you then close that tab / window, then open a new one & look at Zara again, it's back to 9000 0000!

Just looked at a few other clothing shops to try & duplicate it & yes, same thing happens:
https://www.openstreetmap.org/edit#map=17/-28.20181/153.54435 : Best & Less top right & Volcom bottom left - look at the first one 9000 0000, look at something else then return to it & it's gone to 2345 6789, & if you then look at the other clothing shop, it's also 2345 6789. Close that tab, reopen it & look again & back to 9000 0000! 

May be something weird in Firefox?

Having posed a fun Friday afternoon challenge for a clever coder my work here is done! :-)

**Comment by tastrax** [comment]
If i go to the link above and hover over Best and Less i get the correct phone number sample. If I click on Best and Less I get the following

![image](https://user-images.githubusercontent.com/8775395/146497924-4f56cff1-c912-4791-97ee-2ea0425de334.png)

**Comment by tastrax** [comment]
https://github.com/openstreetmap/id-tagging-schema/pull/303
https://github.com/openstreetmap/id-tagging-schema/pull/302

to update the +61 2 9000 0000 to +61 1 2345 6789

This should stop one issue

**Comment by Fizzie41** [comment]
Thanks, Tas!
