### ISSUE TITLE
Can't drag marker across antimeridian

### ISSUE THREAD

**Issue by GPSpilot** [openstreetmap/iD#8862]
Browser: CHrome 96.0
macOS 11.2.3

Steps to replicate:

1. Go to https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=66.6378%2C179.9788%3B66.6392%2C179.9848
2. Drag the red marker a little bit closer to the antimeridian.  (This is just a demo of Directions working correctly... so far so good.)
3. Drag the red marker east of the antimeridian.  This does not work.  Furthermore, _even if you drag the marker back to the west side of the antimeridian without having released your mouse button while it was on the east side,_ OpenStreetMap is now messed up.  The little gray wheel never stops spinning.  Directions will never be calculated correctly again until you right-click on the map and specify a new point for "Directions to here."

The above example is in Russia.   The following URL provides another example of the problem, in Fiji:

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-16.8001%2C179.9927%3B-16.7987%2C179.9943#map=16/-16.7960/179.9996

**Comment by mmd-osm** [comment]
Seems like you’re reporting this in the wrong repo. This needs to go here: https://github.com/openstreetmap/openstreetmap-website/issues

**Comment by GPSpilot** [comment]
Sorry about that.  I created issue 3407 over there.
