### ISSUE TITLE
Add field species: wikidata for plant objects

### ISSUE THREAD

**Issue by afanasovich** [openstreetmap/iD#8864]
### Description

I suggest adding the ability to add a field `species: wikidata` for plant objects:
*`barrier=hedge`
*`natural=tree_row`
*`natural=wood`
*`natural=scrub`

Сurrently the field `species: wikidata` available only for `natural=tree` and `natural=shrub`.

### Screenshots

![species-wikipedia](https://user-images.githubusercontent.com/75438207/147570193-6d13ddae-6d2c-4d60-9fe7-bdbb129710aa.png)

**Comment by tordans** [comment]
@afanasovich please move this suggestion over to https://github.com/openstreetmap/id-tagging-schema which is where the presets are discussed and maintained.

**Comment by tordans** [comment]
I created https://github.com/openstreetmap/id-tagging-schema/pull/320/files to solve this.
