### ISSUE TITLE
allow to search presets by tag

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#8869]
Some people might remember a preset by its OSM tag, or want to look up a preset which matches a tag documented in the OSM wiki.

The preset search bar could show presets if (one of) their tags matches the entered search text (e.g. `landuse=railway` should match the _Railway Corridor_ preset). This could also be relaxed to match any one or two word input which corresponds to an OSM tag's key and/or value. 

See https://github.com/openstreetmap/id-tagging-schema/issues/301

**Comment by 1ec5** [comment]
The search results already include matches based on the value, but not the key=value syntax:

https://github.com/openstreetmap/iD/blob/fc6c71160c6378fa16e70436304a3e3d6fdb30e2/modules/presets/collection.js#L124-L126
