### ISSUE TITLE
Name fields that are disabled by having wikidata do not disable their language dropdown

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#8871]
As per title.

Repro:

```
name=The 123
name:de=Das 123
wikidata=Q123
```

Then try to click dropdown arrow and select a different language

![lang](https://user-images.githubusercontent.com/3857299/147938998-85f66ec6-a34a-4f28-905a-ad779ffcda65.png)

Observe the `name:de` changing to new language.

Tried in both Firefox and Chrome.

**Comment by tyrasd** [comment]
fixed in #8912, thanks @hodigabi
