### ISSUE TITLE
To select the way we want

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#8875]
### How to reproduce the issue?

I wanted to select one way. On this way there was another way. Impossible to select the first one.

So I created a temporary node on these 2 ways. I separated the 2 ways at this node. I was able to do what I wanted on the first way (change some tags). Then I deleted the temporary nodes.
conclusion = the first way had the tags I wanted and the second way was the same (because I deleted the node).

But...
On the second way, there are a lot of relations because it is used for administrative boundary of a country , a region, a municipality, a group of municipalities and so on.
After I saved my changes, I was amazed to see that all the relations (and the second way) are in a new version as if I had changed all these boundaries which is false, they are exactely like before.
For me it is a big problem to say that I have changed something when I did not.

### Screenshot(s) or anything else?

It wouldn't have happened if I could have selected directely the first way and not the second.

I don't know how you can fix that but I tried something which looks "natural" to me, it didn't work but maybe you will like it :
I tried to select the 2 ways together with the SHIFT key. Then I wanted, with a right click, to be able to see the 2 ways and to be able to select the one I wanted.

Best regards

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by 1ec5** [comment]
> I wanted to select one way. On this way there was another way. Impossible to select the first one.

If I understand correctly, the two ways were joined to each other, sharing nodes. You can select the node that joins the two ways, then press Ctrl+Shift+UpArrow (⇧⌘↑ on macOS) to select the two ways, then select the way you want from the list at the top of the left sidebar.

> After I saved my changes, I was amazed to see that all the relations (and the second way) are in a new version as if I had changed all these boundaries which is false, they are exactely like before.

If you feel comfortable sharing the changeset number, it would be easier to investigate the issue. It’s possible that iD rearranged the order of the members in the relation, but that behavior would depend on the situation, so having a concrete example would be helpful. For example, #8578 seems to pertain to certain relations with loops in them.

**Comment by Mahabarata** [comment]
Perfect answer, thanks a lot !
I knew the keyboard shortcut CTRL+UpArrow (no need of the SHIFT) (even if I used more the CTRL+DownArrow to have all the nodes of a way) but I had never seen that it seleted all the ways on the node.
So this bug is not.
For the second case :
I try to redo the problem but it seems ok so I think I was mistaken.
I close this issue.
Best regards
