### ISSUE TITLE
Selecting a road preset should remove construction=*

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#8877]
If you come across road which is tagged highway=construction + construction=residential and you want to mark it as open - the easiest way to do this to use the residential road preset rather than editing the raw tags.

However this leaves behind the construction=* tag - which is not needed and can be problematic for some routers. So iD should remove this as well - since it already removes access=no if that is also tagged.

**Comment by tyrasd** [comment]
fixed in https://github.com/openstreetmap/id-tagging-schema/commit/dd1705e5a7b1b3e83fe37eeb1ad91a45605c0d04

**Comment by boothym** [comment]
Thanks for sorting this.

I said above that "since it already removes access=no if that is also tagged." - but having found a road with highway=construction + construction=residential + access=no, it turns out that selecting the residential preset only removes the construction tag and still leaves access=no on the way. 

Can this be fixed so that access=no is removed as well?

**Comment by tyrasd** [comment]
This was actually changed on purpose (see https://github.com/openstreetmap/id-tagging-schema/pull/416#issuecomment-1062130913 and https://github.com/openstreetmap/id-tagging-schema/issues/443). I think it is reasonable to expect mappers to check and if needed adjust the values of the access field after changing a road back from the construction preset. Similar to how values of other tags should be checked whether they have changed (e.g. surface, maxspeed, lit, etc.).
