### ISSUE TITLE
Address fields show `false` as title

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#8894]
### URL

https://www.openstreetmap.org/edit#map=20/42.72185/23.27184

### How to reproduce the issue?

1. Click on the building that's in view
2. Hover over any of the address fields
3. The `title` of these elements is `false`

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/19364673/148895875-ab5048b9-ddd0-442f-88d1-141509f5044a.png)
![image](https://user-images.githubusercontent.com/19364673/148895922-5a83188b-f0e6-48b1-b0ae-e6b598d77042.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by Mrinalrepo** [comment]
Hi Dimitar,

Not facing the same issue? Selected one hospital and try to click the address bar working perfectly fine.

**Comment by boothym** [comment]
Chrome/Windows also gives false in the title for me, both in Bulgaria and elsewhere.

**Comment by Dimitar5555** [comment]
> Hi Dimitar,
> 
> Not facing the same issue? Selected one hospital and try to click the address bar working perfectly fine.

It displays it when hovering and only when there is a single value for that field.

**Comment by hodigabi** [comment]
Hi Dimitar, Contributors,

What would be the expected behaviour here? Not to show anything when hovering over?

**Comment by k-yle** [comment]
This bug was fixed in https://github.com/openstreetmap/iD/pull/8782#discussion_r739928290, but that change hasn't been released yet.

**Comment by Dimitar5555** [comment]
> This bug was fixed in [#8782 (comment)](https://github.com/openstreetmap/iD/pull/8782#discussion_r739928290), but that change hasn't been released yet.

Should I close this issue or wait until the fix is released?

**Comment by k-yle** [comment]
@Dimitar5555 this fix has been released btw

**Comment by Dimitar5555** [comment]
Thank you for reminding me.
