### ISSUE TITLE
Road flagged as "disconnected from other roads and paths" after connected to road network

### ISSUE THREAD

**Issue by andrewpmk** [openstreetmap/iD#8897]
### URL

http://localhost:8080/#background=Bing&disable_features=boundaries&id=w-4&map=19.00/43.64168/-79.67474

### How to reproduce the issue?

A road is flagged as "disconnected from other roads and paths" when initially drawn as initially disconnected from the road network, then later connected to the road network using a second road.

Steps to reproduce:
1. Draw a road disconnected from the road network (in screenshot, service road on northeast side of industrial building). "XXX is disconnected from other roads and paths" warning is displayed.
2. Draw a road connecting the first road to the road network (in screenshot, service road connecting first service road to Kennedy Road). "XXX is disconnected from other roads and paths" warning does not disappear and should disappear.

Relevant code is in modules/validations/disconnected_way.js

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/10249827/149608567-1d07346f-5252-4ee4-bda2-6cce3f89fd68.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.com

### Which browsers are you seeing this problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by andrewpmk** [comment]
I played around with the JavaScript debugger using the development version (I'm new to iD development) and it seems like what is going on is:

First when you create the first way that is red in the screenshot (w-1) validator.validate in core/validator.js runs on w-1 and its nodes. Way w-1 is disconnected from the way and is flagged with the "disconnected from other roads and paths" warning.

Then when you create w-2 in the editor (the service road to the left of the red way in the screenshot), validator.validate runs on w-2 and its nodes. It will also run on w-1 as long as w-1 connects to the middle of w-2 (therefore modifying w-2) rather than the end. w-2 is untagged at that point.

Then when you tag w-2 as a service road then validator.validate is run on w-2 and its nodes but NOT w-1 because only the tagging of w-2 is being changed and iD doesn't understand that this should remove the disconnected warning from w-1. Therefore w-1's status as being disconnected is NOT reset which results in this bug. Note that if you create w-2 which is initially connected to Kennedy Road but disconnected from w-1, tag it as a service road then connect to w-1 (the red way) then this bug does not occur because both w-1 and w-2 are validated in that case.

**Comment by bhousel** [comment]
Yes you got it! This is #8758
