### ISSUE TITLE
Add https://nominatim.org/qa/ as a validator overlay

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#8898]
### Description

Would be nice to have https://nominatim.org/qa/ directly in iD

### Screenshots

![screen03](https://user-images.githubusercontent.com/899988/149618058-d45efe02-7bd3-4e1e-a620-00b57f5beea5.png)

**Comment by matkoniecz** [comment]
Pinging @AntoJvlt @lonvia in case that idea is a bad one for some reason not obvious to people from outside. Hopefully such ping is acceptable.

Also, thank again to them for a great tool.

**Comment by lonvia** [comment]
I'd like to see the service mature a bit first. In particular, I don't think the layer documentation is yet sufficient for OSM mappers with average or low OSM experience.

**Comment by matkoniecz** [comment]
So lets close it for now.
