### ISSUE TITLE
The Area part of the walkthrough is broken

### ISSUE THREAD

**Issue by hodigabi** [openstreetmap/iD#8906]
### Description

This issue is present on the [develop ](https://ideditor.netlify.app/) version only. The live version is working well. The broken part is with yellow on the below image.

### Screenshots

![image](https://user-images.githubusercontent.com/12541454/150389326-7bedca0c-9c72-4a9e-b31d-a27f0128c377.png)

**Comment by hodigabi** [comment]
I'd like to fix this.

**Comment by TheAdventurer64** [comment]
> I'd like to fix this.

You could probably do so by opening a Pull Request.

**Comment by tyrasd** [comment]
Thanks again for the fix @hodigabi!

PS: I'm wondering why the highlighted box doesn't align with the UI field in the screenshot above… Do you remember what caused it?

**Comment by hodigabi** [comment]
@tyrasd Maybe because I opened/closed the dev tools but I can't reproduce the misalignment any more.
