### ISSUE TITLE
Add a preset for avalanche transceiver

### ISSUE THREAD

**Issue by letypequividelespoubelles** [openstreetmap/iD#8910]
### Description

Hi, 

A new tag has been approved for [avalanche transceiver](https://wiki.openstreetmap.org/wiki/Key:avalanche_transceiver) training zone and checkpoint. Would it be possible to have a preset in the iD editor for this two objects ? 
Thanks a lot !

**Comment by matkoniecz** [comment]
This should be in https://github.com/openstreetmap/id-tagging-schema

**Comment by letypequividelespoubelles** [comment]
you're right, my bad. Done [here, issue 379](https://github.com/openstreetmap/id-tagging-schema/issues/379).
