### ISSUE TITLE
Turn off text autocorrect for network tag

### ISSUE THREAD

**Issue by Mashin6** [openstreetmap/iD#8922]
### How to reproduce the issue?

When trying to paste text to network tag in route relations (`type=route` + `route=road`) iD changes the text to all lower case. Lot of motorway routes have uppercase letters network names like: `RO:A` or `AT:A-road` and iD autocorrects the entered text to `ro:a`, `at:a-road`, etc. 

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by 1ec5** [comment]
I meant to fix this as part of openstreetmap/id-tagging-schema#212 after reporting the issue in #8275, but it looks like I only touched `cycle_network`, not `network`.
