### ISSUE TITLE
2.20.3 has broken display of KeepRight issues

### ISSUE THREAD

**Issue by CorruptComputer** [openstreetmap/iD#8928]
### URL

https://www.openstreetmap.org/edit#map=21/33.98965/-84.27306

### How to reproduce the issue?

Click the link above, enable KeepRight overlay, look at the names and descriptions of issues. 

This release has broken them.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/5573038/152053327-212e9d2c-af79-44c7-be0c-3f7b8d3386d6.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

**Comment by arch0345** [comment]
This also seems to be the case for the ImproveOSM overlay:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/85302075/152067751-ceebf496-14a4-4f69-93ef-4ca3fe81cf0a.png">

**Comment by CorruptComputer** [comment]
I believe this issue was caused by the change in PR #8817
