### ISSUE TITLE
Warning of exceeding local storage quota gradually fills screen if editing is continued in 2.20.3

### ISSUE THREAD

**Issue by PeterLeGras** [openstreetmap/iD#8930]
### How to reproduce the issue?

When the local storage quota is exceeded (for example by making a large changeset with many edits), the footer warning displays "You have made too many edits to back up. Consider saving your changes now". Since the 2.20.3 release, the warning message is appended to itself in the footer when additional edits are made (screenshot shows issue). This gradually fills the editing screen.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/52308086/152084861-381e4a15-38b8-47ef-8178-c96cb963942f.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by cicku** [comment]
Regression introduced by https://github.com/openstreetmap/iD/pull/8817

**Comment by 1ec5** [comment]
FYI, your browser may have a setting that increases the local storage quota. For example, in Mozilla-based browsers such as Firefox and SeaMonkey, set [`dom.storage.default_quota`](http://kb.mozillazine.org/Dom.storage.default_quota) in `about:config`.

**Comment by cicku** [comment]
I'm more interested if there will be a hotfix released as 2.20.4. Why should users modify such settings?

**Comment by tyrasd** [comment]
Yes, there will be a hotfix v2.20.4 for this and #8928 released very soon.
