### ISSUE TITLE
HTML code `<br>` in Localization string still be shown

### ISSUE THREAD

**Issue by LaoshuBaby** [openstreetmap/iD#8936]
### URL

(This bug may not related to place, but I suggest you reproduce it in Mainland of China)

### How to reproduce the issue?

1. Set browser in zh-CN locale
2. Create a cafe (you can search "咖啡馆" in feature type)
3. Name it with "Starbucks" (……or any brand in NSI, need correct feature type)

### Screenshot(s) or anything else?

The `<br>` in zh-CN translation string are still can be displayed after #8813

![图片](https://user-images.githubusercontent.com/42690037/152192873-e336e78f-1458-46f1-ba7b-373bb9081572.png)

in other locale this problem don't occur (such as zh-TW)

![图片](https://user-images.githubusercontent.com/42690037/152195595-f9b407ac-eb62-4c0c-8e8f-ffa5147b0b59.png)

---

The reason why string include a `<br>` maybe mis paste clipboard (the wrong paste is in 2021.11.23)

![图片](https://user-images.githubusercontent.com/42690037/152193714-afd933e7-ffe1-4a66-920c-853f0f9a8c7d.png)

But before 2.20.3 [released](https://github.com/openstreetmap/iD/blob/release/CHANGELOG.md#2203) (22.02.01), I haven't see this bug.

---

**I feel sorry for wrong (and maybe toxic) translation, for my mistake. I've already fix it in Transifex.**

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit （2.20.3）

### Which browsers are you seeing this problem on?

Firefox (But this may not browser related, Chrome, Edge, and other browser will occur this when in zh-CN)

**Comment by tyrasd** [comment]
Hello. Thanks for the report. Yes, there are still a few places where strings from transifex are rendered as raw HTML. Some of these are harder to fix. That's why they are not fixed in #8817 (see https://github.com/openstreetmap/iD/pull/8817#issuecomment-981907721).

Thanks for fixing this in the `zh-CN` translation on transifex already. :+1:
