### ISSUE TITLE
Value ordering in access lists

### ISSUE THREAD

**Issue by nc011** [openstreetmap/iD#8945]
A (recent?) change has introduced some new values into the ```foot=*``` access list - which is fine. However, the [second most popular](https://taginfo.openstreetmap.org/keys/?key=foot#values) value (```designated```) has been relegated to the bottom of the list which requires scrolling (at least on my display).

Is there any way the ordering of these value lists, I guess for all access modes, can reflect the most likely value for the key based on usage?

**Comment by tyrasd** [comment]
Are you sure this changed recently? Because as far as I can tell, the code always added the value `designated` at the end of the list, see https://github.com/openstreetmap/iD/blame/v2.20.4/modules/ui/fields/access.js#L82-L86

But ok, what did change is that with the current release, two new values were added in the middle of the list, causing the need to scroll to see the entry for `designated`. Which is indeed not ideal. Let's improve it! :+1:

**Comment by nc011** [comment]
Yep - the recent change was the new additions. You're right, I think designated has been at the bottom but it's not been too much of a problem until the need for scrolling.

**Comment by tyrasd** [comment]
I think it would make sense to

1. keep the order of the values the same for all modes of transportation (excluding options which are specific to a single mode, like `bicycle=dismount` of course)
2. have a sorting which is somewhat "logically" ordered: generic before specific ones, and permissive ones before restrictive ones
3. have more common values at the top

What about the following ordering, which IMHO balances these 3 requirements quite well:

    yes
    no
    designated
    permissive
    destination
    (dismount)
    customers
    private
    permit
    unknown

**Comment by nc011** [comment]
Sure - some of those options are very rarely used for some modes of transport but at least they're towards the bottom.

Whilst we're on this topic, it might be worth adding ```use_sidepath``` for non-vehicular access modes. It's the [fifth most common](https://taginfo.openstreetmap.org/keys/foot#values) value for foot and [fourth most](https://taginfo.openstreetmap.org/keys/bicycle#values) for bicycles. Some minor usage for horses too.

**Comment by tyrasd** [comment]
> `use_sidepath`

:+1: but that one would need to be added to the tagging schema first, see https://github.com/openstreetmap/id-tagging-schema/issues/5 for that
