### ISSUE TITLE
Speed Limit field no longer appears in the United States and Canada

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8947]
### URL

https://ideditor.netlify.app/#background=Bing&disable_features=boundaries&id=w648312143&locale=en&map=19.00/39.44204/-83.82872

### How to reproduce the issue?

1. Select a street.
2. Observe that the Speed Limit field is no longer present in the inspector, even though Advisory Speed Limit is available as a field that can be added.

### Screenshot(s) or anything else?

openstreetmap/id-tagging-schema#217 added a `maxspeed` field specific to the United States and Canada, but it isn’t showing up for some reason. Meanwhile, the global `maxspeed` field is being correctly excluded. As a result, iD ends up with no Speed Limit field at all.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.com

### Which browsers are you seeing this problem on?

Firefox

**Comment by tyrasd** [comment]
oh that's bad :cry: it was my mistake in [id-tagging-schema/commit/8c59cdac6e0ed07ef7c83ecd0c42ea62567c24c3](https://github.com/1ec5/id-tagging-schema/commit/8c59cdac6e0ed07ef7c83ecd0c42ea62567c24c3), where I forgot to remove the `locationSet -> exclude` from the `maxpeed` field.
