### ISSUE TITLE
No more sidebar to zoom in/out with ID editor

### ISSUE THREAD

**Issue by pinzaglia** [openstreetmap/iD#8949]
### How to reproduce the issue?

The right sidebar containing the zoom command has disapeared on the last version of ID,
with Firefox 51.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by tyrasd** [comment]
Hey!

> with Firefox 51

Oh, that version is about 5 years old now.

I can't reproduce the issue with a recent version of Firefox (version 96.0). Realistically, we simply can't really provide support for such a long outdated version of a browser. Can you not update to an up to date version of Firefox?

**Comment by pinzaglia** [comment]
Hi,
What a pity... as all worked ok since yesterday.
At home I have more recent browsers, but when I travel I have an old portable PC, with XP.
I think, but I'm not sure, that this version of Firefox is the last one supported on XP. 
So, anyway, thanks for your quick answer.

**Comment by tyrasd** [comment]
XP :scream: … perhaps you should consider installing some lightweight Linux distribution on your device :wink: 

FWIF, the regression was probably caused by #8791.
