### ISSUE TITLE
add "today" button for `check_date` field

### ISSUE THREAD

**Issue by stragu** [openstreetmap/iD#8951]
### Description

When the `check_date` key field (titled "Last Checked Date") is visible in the left sidebar, it would be great to have a button associated to it to easily add today's date in one click. It doesn't necessarily make sense to have that for _all_ date fields, but for this one in particular, many people will be adding or modifying something they surveyed the same day, or simply "touching" the feature to confirm that the tags are still valid. In my case, I use the field the most for construction sites: confirming that it is still currently under construction.

The iOS application GoMap!! has this handy feature.

**Comment by furkanmutlu** [comment]
Hi, already checked the IOS app, I will be working on this to create similar experience.

**Comment by alanb43** [comment]
@jdabapo or I could get started on this, but embarrassingly after searching for a while, I could not find where the code lies for the last checked date within the iD package. If someone points me in the right direction, that would be great!

**Comment by 1ec5** [comment]
The Last Checked Date field itself is defined along with all the other fields [in the id-tagging-schema repository](https://github.com/openstreetmap/id-tagging-schema/blob/c123e31a82d254715b2363e4bfe834d04d9a66ad/data/fields/check_date.json). However, that just defines the field as a standard `text` field. ideditor/schema-builder#76 requests a new `date` field type that would apply to other fields such as Start Date and provide convenient UI for selecting the date. As a temporary workaround, it might be possible to implement a special case somewhere around here:

https://github.com/openstreetmap/iD/blob/41aa127d236fc70baba7c3509db305e4b114b49c/modules/ui/fields/input.js#L100

**Comment by Dimitar5555** [comment]
@stragu It has been implemented. This issue can be closed.
![image](https://user-images.githubusercontent.com/19364673/226272853-b3206b76-95aa-47c8-bbc3-99abeb2614ae.png)

**Comment by stragu** [comment]
Fabulous, thank you!
