### ISSUE TITLE
Requesting a review of potential issues found in current `develop` branch code

### ISSUE THREAD

**Issue by CorruptComputer** [openstreetmap/iD#8959]
Just read through a portion of the source code, as well as my code editors warnings/errors shown for the code in this repo, and the following has been observed by me. Not all of these are necessarily issues with this, just things that I was able to easily find and not personally able rule out as false positive issues. 

---

* [x] `behavior/select.js`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/behavior/select.js#L338
`&` instead of `&&` here might cause issues with short circuiting logic of boolean operations,

---

* [x] `modes/drag_node.js`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/modes/drag_node.js#L237
The whole `if` will always evaluate to `false` since both `hasRelationConflict()` and `hasInvalidGeometry()` called above can never return either of these values.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/modes/drag_node.js#L247
Same as above with this line, neither of these ever return `line` as a value.

---

* [x] `ui/tools/modes.js`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/modes.js#L59
Passes `mode` variable to the `enabled()` function, but that function takes no args. This might be expecting a different return value from that function than is being used.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/modes.js#L102
Same as above with this line.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/modes.js#L140 
Same as above with this line.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/modes.js#L141
Same as above with this line.

---

* [x] `ui/tools/notes.js`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/notes.js#L38
Same as above with this line. (different file than above issue though)

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/notes.js#L77
Same as above with this line.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/notes.js#L110
Same as above with this line.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/notes.js#L111
Same as above with this line.

---

* [x] `ui/tools/save.js`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/ui/tools/save.js#L67
Same as above with this line. (different file and function name than above issue though)

---

* [x] `30_highways.css`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/30_highways.css#L19
Duplicate selector, can be combined with one earlier in this file.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/30_highways.css#L22
Same as above with this line.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/30_highways.css#L430
Same as above with this line.

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/30_highways.css#L631
Same as above with this line.

---

* [x] `css/35_aeroways.cs`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/35_aeroways.css#L42
Same as above with this line. (different file than above issue though)

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/35_aeroways.css#L46
Same as above with this line.

---

* [x] `css/40_railways.css`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/40_railways.css#L48
Same as above with this line. (different file than above issue though)

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/40_railways.css#L51
Same as above with this line.

---

* [x] `css/50_misc.css`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/50_misc.css#L81
Same as above with this line. (different file than above issue though)

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/50_misc.css#L247
Same as above with this line.

---

* [x] `css/80_app.css`

https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/css/80_app.css#L3074
The `display` attribute here is duplicated, may lead to unexpected issues with rendering this element.

---

Will continue reviewing from there tomorrow, but its late for me and I'm going to bed. 
Any further problems found will be raised in a separate GitHub issue.

(This was submitted as of commit # https://github.com/openstreetmap/iD/commit/8e8d00ae8b4d43643db16af413406a3df0c6e5ad)

## Edit:
Removed un-needed parts added by the issue template and replace `method` terminology with `function` (am more used to using C# currently, not JS).

**Comment by tyrasd** [comment]
Hey. Thanks, I will take a look through these. :+1: 

> code editors warnings/errors shown for the code in this repo

Just out of curiosity: which code editor is this?

**Comment by tyrasd** [comment]
> [`iD/modules/modes/drag_node.js`](https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/modes/drag_node.js#L237)
> 
> `if (isInvalid === 'relation' || isInvalid === 'restriction') { `
> 
> The whole if will always evaluate to false since both hasRelationConflict() and hasInvalidGeometry() called above can never return either of these values.
> 
> `var errorID = isInvalid === 'line' ? 'lines' : 'areas';`
> 
> Same as above with this line, neither of these ever return line as a value.

:thinking: I think these are false positives: `restriction` can be returned by `hasRelationConflict` ([from here](https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/actions/connect.js#L172-L174)), while `relation` and `line` are potentially returned by `hasInvalidGeometry` ([here](https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/modes/drag_node.js#L343)).

**Comment by CorruptComputer** [comment]
> Hey. Thanks, I will take a look through these. 👍
> 
> > code editors warnings/errors shown for the code in this repo
> 
> Just out of curiosity: which code editor is this?

No problem, thank you for taking a look at these!
Its just VS Code with some plugins, the one which produces most of the warnings I've looked through is [SonarLint](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode).



> > [`iD/modules/modes/drag_node.js`](https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/modes/drag_node.js#L237)
> > `if (isInvalid === 'relation' || isInvalid === 'restriction') { `
> > The whole if will always evaluate to false since both hasRelationConflict() and hasInvalidGeometry() called above can never return either of these values.
> > `var errorID = isInvalid === 'line' ? 'lines' : 'areas';`
> > Same as above with this line, neither of these ever return line as a value.
> 
> 🤔 I think these are false positives: `restriction` can be returned by `hasRelationConflict` ([from here](https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/actions/connect.js#L172-L174)), while `relation` and `line` are potentially returned by `hasInvalidGeometry` ([here](https://github.com/openstreetmap/iD/blob/8e8d00ae8b4d43643db16af413406a3df0c6e5ad/modules/modes/drag_node.js#L343)).

Ah, these two may be false positives. 
I tried to rule out most the false positives myself, and only give the ones I couldn't personally rule out.

**Comment by tyrasd** [comment]
Implemented in #8965 

Thank you for the suggestions!

PS: I left some of the css selectors as they were, because in some cases I thought that the separation of styling that affects color and thickness (for example) makes the files more tidy and easier to extend.
