### ISSUE TITLE
Keepright Issues still broken in 2.20.4

### ISSUE THREAD

**Issue by Njorlpinipini** [openstreetmap/iD#8963]
### How to reproduce the issue?

Keepright issues are now invariably blank. Additionally, attempting to select a different feature after clicking or mousing over a keepright issue locks up the sidebar like so:
![image](https://user-images.githubusercontent.com/99146227/152702393-0b82214f-4eff-4344-915f-ce10ef8ed7a7.png)~
While the sidebar is in this state, I can still freely inspect objects, but I cannot interact with any tags (except for switching between presets using the button at the top.) Scrolling no longer works either. The only way I have been able to restore functionality to the sidebar has been by refreshing the page. 

-This applies to all keepright issues regardless of type.
-Osmose/ImproveOSM issues are not affected by this, only the feature editor.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome, Microsoft Edge

**Comment by tyrasd** [comment]
Confirming. This is caused by a typo in the fix for #8928 at [`modules/ui/keepRight_header.js#L17-L19`](https://github.com/openstreetmap/iD/pull/8932/files#diff-ee3fd1ed14fe44f0d313b805f488fc0006f7756c74b6035d7e1536ac8299995bR17-R19). Sorry for the mistake!
