### ISSUE TITLE
Left panel will continuous accumulation specific texts

### ISSUE THREAD

**Issue by LaoshuBaby** [openstreetmap/iD#8987]
### URL

https://www.openstreetmap.org/edit#map=17/19.70261/109.43984

### How to reproduce the issue?

Click or focus on the [river](https://www.openstreetmap.org/way/558287575) in the [edit view](https://www.openstreetmap.org/edit#map=17/19.70261/109.43984).

### Screenshot(s) or anything else?

Here is a video of this bug (or feature?)

Maybe a little long, but at last you will see it very distinct

https://user-images.githubusercontent.com/42690037/154831068-604318ec-f4ca-4870-899b-ce82bab1ccb2.mp4

-----

If video can‘t be played：

* At first

![图片](https://user-images.githubusercontent.com/42690037/155098928-9459f4e4-9401-4ae6-b08c-baf0ad7db439.png)

* Then

![图片](https://user-images.githubusercontent.com/42690037/155099014-08c1822b-81b8-463b-b1b8-8e7fd1d48263.png)

* At last

![图片](https://user-images.githubusercontent.com/42690037/155099133-18c2abf6-37a5-4c8d-8ba8-8ec3af999efa.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit （2.20.4）

### Which browsers are you seeing this problem on?

Firefox

**Comment by LaoshuBaby** [comment]
## This problem affected not only S/T Chinese, but also English! Even RTL language like Hebrew!
---
Tested browser :  (Looks like don't relevent to browser core)

* Firefox 97 (`zh-CN` test conducted in this browser)
<img alt="图片" src="https://user-images.githubusercontent.com/42690037/154831192-8d221adb-b814-46a6-a643-83ea5df58d8e.png" width=400px />

* Edge 98 (`zh-TW`, `en-US`, `he` are tested in this browser)
<img alt="图片" src="https://user-images.githubusercontent.com/42690037/154831570-88e6eef7-f012-4deb-a6fe-df165e718254.png" width=400px />


---

2022-08-09

I found 3 video that screenrecord that day:

in zh-TW:

https://user-images.githubusercontent.com/42690037/183687483-08dc56cd-0a57-49cb-a79a-b98b5f76a79d.mp4

in en:

https://user-images.githubusercontent.com/42690037/183687464-b53eba1d-1c1c-41b3-9ee8-f8dc9f56304b.mp4

in he(RTL lang):

https://user-images.githubusercontent.com/42690037/183687437-6c07423c-cfe4-4619-a591-c54030cff363.mp4

**Comment by LaoshuBaby** [comment]
I tested in latest 2.21.1 and this issue not occur, but another mapper also reported this problem in a non-public group.

I'll close this out-of-date issue, hope that nobody will meet this strange bug again.

**Comment by 1ec5** [comment]
This was a duplicate of #8984 that was fixed in cd4f4f37f13dd87b00e1640c02442863e608f191.
