### ISSUE TITLE
node, way, area

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#8990]
### URL

all

### How to reproduce the issue?

Hi,

in osm we have 3 kinds of elements : node, way and relation. When a way is closed, it is an area.

But in ID :
*  when I want to create a node, the button at the top of the window has the name "Point". And when I have created it, if I follow the link to see the changeset, my 'point' now is a 'node'. Could you use the same word and change the name on the button ?
* when I want to create a way, the button at the top of the window has the name "Line". But when I have created it, if I follow the link to see the changeset, my 'line' now is a 'way'. Could you use the same word and change the name on the button ?

Best regards

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by 1ec5** [comment]
What you’re seeing is a mismatch between [raw elements](https://wiki.openstreetmap.org/wiki/Elements) and [semantic elements](https://wiki.openstreetmap.org/wiki/Semantic_elements). Semantic elements are a more user-friendly abstraction over the raw elements, just as presets are an abstraction over raw tags. osm.org’s element browser is look into the raw data in the database, so it does differ from iD’s UI by design.

**Comment by Mahabarata** [comment]
Except that Area is not a geometry (which is the definition of semantic elements), the geometry of closed ways (what I create when I click on your button "Area") is Polygon.

And when I click on you button Line, I'm not creating a line (a line is defined, in geometry, with points aligned) but a polyline.

So the true semantic elements, geometry speaking, are : point, polyline, polygon.

To me there are 2 problems : you use words nobody else uses and your choices don't fit what you want to do.

Best regards

**Comment by Mahabarata** [comment]
I just opened a talk about the template "elements" in the wiki because the template "elements" is currently wrong, see [here](https://wiki.openstreetmap.org/wiki/Template_talk:Elements#List_of_semantic_elements)

**Comment by 1ec5** [comment]
The UI is aiming for intuitiveness to a lay audience, not necessarily mathematical correctness. “Line” and “[area](https://wiki.openstreetmap.org/wiki/Area)” are very frequently used in OSM contexts with these meanings, including in the [`area`](https://wiki.openstreetmap.org/wiki/Key:area) key that determines whether a way represents a line or an area if it is not implied by a feature tag.
