### ISSUE TITLE
Adding Curved Roads

### ISSUE THREAD

**Issue by d-e-v-esh** [openstreetmap/iD#8992]
### Description

Curved and Circular roads are very common across the world. If there was a way to add curved roads on the map then that would be really convenient for people to add them instead of clicking 10s of times on the path to give it a curved shape.

I could be wrong but I think it could be implemented the same way `border-radius` works in CSS. We can make each point have a `curvature` property which will define the amount of curvature that will be applied to the 2 lines that the point is joining. 
It can create curvature by adding more points on the line automatically or by any other better means.

---

If this works then we develop further on this feature and make it easy for users to make oval shape areas. We can circularise a closed road or area but making it oval is difficult. Most of the structures are not a perfect circle. Users can create points on that oval shape and give that oval whatever shape they like and sculpt it however the area is on the map. This can make creating water bodies, parks, or any other curved structures, very easy and quick.

---

Is this a good idea?
Is it possible to add curvature to lines in any way other than adding more points?
I am really interested in this and would love to know more. 👍

---

### Screenshots

It can look something like this:

![mspaint_9HaFEeRa43](https://user-images.githubusercontent.com/59534570/154941944-4c66e992-0dd9-4a97-8a6d-1c45296988e9.png)

**Comment by mmd-osm** [comment]
Downvote as it’s not really supported by the osm data model.

**Comment by d-e-v-esh** [comment]
Ok I'll close the issue then

**Comment by d-e-v-esh** [comment]
@mmd-osm But what about another way of creating a customizable oval path. We can already do a circular path and area. Should I make an issue on that? Would that be a good issue? I would like to work on that feature.

**Comment by mmd-osm** [comment]
The data model doesn't support splines or curved ways. You can of course have some tool support to place nodes in a certain way or add additional nodes. That's about it what is possible today.

**Comment by d-e-v-esh** [comment]
@mmd-osm  Yes, that's what I am talking about, adding more nodes on the line so it appears curved. Just like the `circularize` function, we can make another tool so that people can create ovals made with lots of nodes and control the shape of that oval to fit the object on the map.

**Comment by mmd-osm** [comment]
Ok, this makes sense now. As long as we don't add any additional tags, or maybe rely on data consumers to figure out what those tags mean, we should be ok.

Regarding the data model, there's even some proposal to add curved segments (https://wiki.openstreetmap.org/wiki/API_v0.7#Curved_segments_for_ways), hence my reference to the current data model which doesn't support those concepts natively. I hope this provides some additional context why this is in fact a tricky topic, depending on what exactly you're after.

**Comment by d-e-v-esh** [comment]
I'll think about this and come up with an idea. Thanks 👍
