### ISSUE TITLE
Dropdown menu does not go away by clicking on the map

### ISSUE THREAD

**Issue by d-e-v-esh** [openstreetmap/iD#8993]
### URL

https://www.openstreetmap.org/edit

### How to reproduce the issue?

1.  Click on the edit dropdown menu
2.  Then click away on the map

The dropdown menu should disappear as we are now interacting with the map but it does not go away. We need to click on the dropdown button again to make it disappear. This bug is not available on the normal website.

### Screenshot(s) or anything else?

https://user-images.githubusercontent.com/59534570/155006492-2c764ba7-de94-4753-81e2-2b38ca916840.mp4

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by mmd-osm** [comment]
The popup is part of the osm website code and outside of this repository. Here’s probably the wrong place to report this issue.

**Comment by d-e-v-esh** [comment]
Ok I'll make this issue on the other repository and close this 👍

**Comment by mmd-osm** [comment]
Related issue https://github.com/openstreetmap/openstreetmap-website/issues/3464
