### ISSUE TITLE
Notes: Resolve with comment requires double click

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#8994]
### URL

edit*

### How to reproduce the issue?

1. Open a note.
2. Write a comment.
3. Click "resolve with comment". Nothing happens.
4. Click it again.
(Optionally, exit the note between step 3 and 4, this action is still saved)

### Screenshot(s) or anything else?

This does work in one click on the `https://mapwith.ai/rapid` version.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.com

**Comment by matheusgomesms** [comment]
True, I saw that too.

**Comment by waldyrious** [comment]
Copying reproduction steps from #9217, for convenience:

> ### How to reproduce the issue?
>
> 1. Open the editor in an area of the map with an unresolved note
> 2. Address the note.
> 3. Click the "New Comment" box under the note's text
> 4. Enter some text
> 5. Click the "Close and Comment" button under the text box 
> 6. The note doesn't get closed, nor the comment added (However, and crucially, **the text box loses focus**)
> 7. Click the "Close and Comment" button again
> 8. This time, the note is actually closed.

> ### Screenshot(s) or anything else?
>
> Here's a short recording of the bug. The context is I had written a comment, and was about to close the note with it.
>
> ![2zfuVj6G2b](https://user-images.githubusercontent.com/478237/181114233-41a60f89-e2b6-4626-9fcd-e6ad1d8d6510.gif)
>
> Note that I first hovered the "Close and Comment" button, but didn't click it, because I realized I had lost focus of the text box when I started the screen recording. So to reproduce the issue, I clicked the text box again (notice how its background color becomes a slightly darker gray), and _then_ clicked the button. That didn't have the desired effect (i.e. the bug manifested); then I clicked the button a second time, and the note was closed.

**Comment by maro-21** [comment]
Thanks, it helps. I often had this issue and didn't realise it was a bug.

**Comment by maro-21** [comment]
This error still occurs!

**Comment by danieldegroot2** [comment]
> This error still occurs!

Use the development mirror. It will be pushed to the live version eventually.
https://github.com/openstreetmap/iD?tab=readme-ov-file#participate

It works fine on my end.

**Comment by maro-21** [comment]
But it was released with the version 2.29.0 and I'm using this version. I found this topic because of changelog.

**Comment by danieldegroot2** [comment]
Yes, understandable. However, for the current version the change is broken by accident. It has since been resolved for a future version.
https://github.com/openstreetmap/iD/pull/10205#issuecomment-2075052817
