### ISSUE TITLE
KartaView images not shown completely when resizing+zooming

### ISSUE THREAD

**Issue by FinixFighter** [openstreetmap/iD#8997]
### URL

https://www.openstreetmap.org/edit#map=19/59.40386/17.93796

### How to reproduce the issue?

Go to iD, enable KartaView photo overlay, open any KV image, change the size of the image window (from the top right corner, make it bigger), zoom in and then try to move the image: you'll see that you can reach the top of the image and the left side, but you can't reach the bottom and the right side of the images. It's like if the image gets cropped on two sides, the right and the bottom.

### Screenshot(s) or anything else?

Watch video at: https://odysee.com/@Finix:d/kvbug022022:c

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by derkrasseleo** [comment]
I am also experiencing this issue. But it doesn't seem to be browser-specific. I tested with brave and firefox.

**Comment by derkrasseleo** [comment]
This issue still persists. It seems that the image is cropped every time the outer frame is moved, or the image is zoomed in, which is not the expected behavior.

**Comment by tyrasd** [comment]
fixed in 59734d172 (and d0e061c47)
