### ISSUE TITLE
OSM Notes reminder

### ISSUE THREAD

**Issue by Fizzie41** [openstreetmap/iD#9005]
### Description

This isn't just an iD issue, but couldn't think of anywhere else to raise it!

Would there be any way of modifying OSM Notes so that, if the Note hasn't been resolved after a set period e.g. 3 months, the system sends you a reminder that it is still open?

Naturally, this wouldn't work if the Note has been added by a non-mapper e.g. by somebody using OSMAND, but it would help with those Notes that have been created as an aide-memoir by active mappers, who have then forgotten about them! :-)

Thanks,

Graeme

**Comment by tordans** [comment]
@Fizzie41 iD would not be able to send reminders. It's a browser app without any server component that could do such a thing. This is something for https://github.com/openstreetmap/openstreetmap-website.

**Comment by Fizzie41** [comment]
Thanks! 

I knew that some bright person would know where I had to go :-)

I'll raise it over there.
