### ISSUE TITLE
Add scrollbar to list of backgrounds

### ISSUE THREAD

**Issue by Hufkratzer** [openstreetmap/iD#9006]
### Description

When there are many backgrounds available in the list, the ones at the bottom may not be visible/selectable because the is no scrollbar, see example below.

### Screenshots

![id-mapslist](https://user-images.githubusercontent.com/5958184/155898130-1db0cc33-fd10-4f31-8e12-321601d15226.jpg)

**Comment by sammansch** [comment]
There looks to be a very skinny scrollbar on the far right that's hidden behind the grey menus.
I was able to scroll with the current code and also online.

**Comment by Hufkratzer** [comment]
Indeed. Thanks.
