### ISSUE TITLE
Directions from stop signs visualized on ways without highway tag.

### ISSUE THREAD

**Issue by BubbaJuice** [openstreetmap/iD#9013]
### URL

https://www.openstreetmap.org/edit#map=23/32.28756/-110.97337

### How to reproduce the issue?

1. Have a stop sign, tagged with `direction` on a highway node.
2. Create an area or line that connects with the stop sign node.
The issue should be present after following the two steps above.

### Screenshot(s) or anything else?

When a stop sign (`highway=stop`) is tagged with a `direction` and a way or area without `highway` on it, the direction visualization is present. It is my belief that this should not be visualized on ways/areas without a `highway` tag.

The issue was present on the OSM website, RapiD, and the development version. I tested it on Firefox, Chrome, and Edge.
![image](https://user-images.githubusercontent.com/68205167/156699852-f9d8440b-50b7-4efc-9068-e4f08b8fd4f1.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.com, RapiD version at mapwith.ai/rapid

### Which browsers are you seeing this problem on?

Firefox, Chrome, Microsoft Edge

**Comment by 1ec5** [comment]
Whenever a node is tagged with a generic direction keyword such as `forward` or `backward`, the following code is responsible for inferring the direction from the node’s parent ways. For starters, it should be limited to parent ways that aren’t areas: #5634. But this would also be an opportunity to exclude some other things like (presumably) road markings:

https://github.com/openstreetmap/iD/blob/3dde091fdd3f8c5e54abd9923d642e67adb05064/modules/osm/node.js#L117-L129
