### ISSUE TITLE
Collapse

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#9024]
### Description

Hi,

in transifex, we have to translate a single word ; "collapse".
The id of this string in transifex is 7014, the context is :
![Capture d’écran 2022-03-08 125510](https://user-images.githubusercontent.com/3121119/157275179-4f4f4466-9a3c-4974-a362-c00bf00a35fa.png)

I don't know where we can see this icon and this text so I need your help to be able to translate it.

Best regards

**Comment by danieldegroot2** [comment]
C'est le description pour fermer (collapse) -et ouvrir (expand)- les categories comme 'usage de terre' (='zone residentielle', 'zone industrielle', etc.), ici marqué en rouge.

It is the tooltip (description on hovering over the button) for closing/collapsing -and opening/expanding- a preset category, here highlighted in red.

([la clé sur GitHub / the key on GitHub](https://github.com/openstreetmap/iD/blob/69aa69153dad569fabde03687eddd8405576fe53/modules/ui/preset_list.js#L280))

**'fermer' ou 'réduire'(comme utilisé par brouter) / collapse**
![image](https://user-images.githubusercontent.com/67521919/158888262-697b71f9-b1f1-4cc5-a041-ef7b32bc913b.png)

**ex. 'ouvrir' / expand**
![image](https://user-images.githubusercontent.com/67521919/158886974-bad264d0-346b-4e34-a594-cb0596451db3.png)

**Comment by Mahabarata** [comment]
Ok, thanks !
