### ISSUE TITLE
[Erroneous:] Observed: v2.20.2 used recently by user, well after v2.20.4 released

### ISSUE THREAD

**Issue by Lee-Carre** [openstreetmap/iD#9028]
### URL

[Changeset #118249424](//www.openstreetmap.org/changeset/118249424).

### How to reproduce the issue?

Unsure. Observed via [changeset #118249424](//www.openstreetmap.org/changeset/118249424).

Also don't know the user's environment. Though, perhaps they'll respond to a PM asking them.

### Screenshot(s) or anything else?

Unfortunately not.

### Which iD Editor versions do you see the issue on?

`host=https://tasks.hotosm.org/projects/12003/map/`

So, could be that HOTOSM simply haven't updated their version.

Noticed this only *after* submitting the report. If it turns out to be a false-positive, then apologies (feel free to close without remark).

### Which browsers are you seeing this problem on?

Unknown; observed rather then experienced.

The affected user might respond to a PM, though.

---

### Speculation & analysis …

… as to the cause & remedy, from the cited changeset.

May now be redundant, due to where the instance is hosted.

> Comment from SekeRob […]
> 
> > Oddly the change set uses version 2.20.2 when we're on 2.20.4 suggesting a stale browser application cache.
> 
> Comment from Lee Carré […]
> 
> > […]
> > 
> > > stale browser application cache.
> > 
> > Depends what the caching-related HTTP headers have declared. If the browser has been told that it may use the resources for a year+ (without re-checking with the server), then (strictly) the cache isn't stale (even though the data within is outdated, in this case).
> > 
> > Which, from a Web-dev PoV, indicates that this wasn't thought about in iD's implementation (or possibly how it's been deployed on the host site; which goes back to how iD has been implemented).
> > 
> > Users shouldn't have to (know (how) to) flush their HTTP cache (think about those behind shared caches, administered by someone else, which they can't flush).
Even if they did know; when are they supposed to, or how would they know when to (without being expected to watch the GH repo)?
> > Having to manually flush cache is a workaround or troubleshooting step. Shouldn't be part of normal operations. Caching (done correctly) is good. Flushing an entire cache (adversely) affects other sites.
> > 
> > The naive retort (of developers) would be ‘how are we supposed to know how to set the caching headers, since we don't know when we'll release a new version?’.
> > 
> > Well, firstly, regularly scheduled releases (say, monthly) wouldn't be a bad idea.
> > 
> > However, the strategy which is commonly used with images is (in simplified terms) to set long-lived caching headers on each image. If there's need to change which image is used, then point to a another one at a different URL, with the HTML set to have relatively short-lived caching headers.
> > If a script is selecting images, then give it the conditional logic to figure out which image is the right on, among a set.
> > 
> > For iD, there could be a small file for checking version, which has headers declaring it to be cached only for somewhere between an hour and a day (I'll let the server admins determine that), and then differently-versioned files of iD sit at different URLs (perhaps use the version-number in the URL), which each have long-lived caching headers.
> > The version file points to the current stable version (or uses a mini-language, or a terse well-known language (JSON?), to specify each of stable, previous, beta testing, development, or whatever the developers / admins wish).
> > 
> > If things are done sensibly, then it should be possible to invoke different versions of iD (for testing purposes) by hacking the URL.
> > 
> > Besides easily testing for regressions, keen users could also easily test beta / development / nightly versions.

**Comment by 1ec5** [comment]
This is completely out of the control of the iD project itself. Once a new version is released, it’s up to each deployment to upgrade and configure their caching headers appropriately.

The HOT Tasking Manager [depends on a fork of iD](https://github.com/hotosm/tasking-manager/blob/259f16d068617293edbdcdd983168c56c26cf4b1/frontend/package.json#L11) that’s still on v2.20.2. You’ll want to open an issue in the [hotosm/tasking-manager](https://github.com/hotosm/tasking-manager/issues/) repository instead or contact one of the [`@hotosm/id`](https://www.npmjs.com/package/@hotosm/id) package’s maintainers directly.
