### ISSUE TITLE
Ajout de voie verte

### ISSUE THREAD

**Issue by gogo25171** [openstreetmap/iD#9032]
### Description

Bonjour,
J'aimerai savoir si vous pouvez ajouter les voies vertes car je mets actuelle les routes non carrossables comme ce qui est marquer sur le wiki. Merci d'avance, cordialement.

**Comment by manfredbrandl** [comment]
Translated to english „ Hello,
I would like to know if you can add the greenways because I currently put the roads that are not passable as it is marked on the wiki. Thank you in advance, cordially.“

Can someone please close this?
