### ISSUE TITLE
**Describe the bug**

### ISSUE THREAD

**Issue by Catclaws12** [openstreetmap/iD#9038]
**Describe the bug**
I cannot find old articles which I could read at https://developers.google.com/web platform. For example, I cannot find Jake Archibald article about service-workers lifecycle. When I try to open this url: https://developers.google.com/web/fundamentals/primers/service-workers, I will be redirected to https://developer.chrome.com/docs/workbox/service-worker-overview/ what is different. What's more If I open https://developer.chrome.com/docs/workbox/service-worker-lifecycle/ in the end I can find such information:

>For those interested in a deeper dive into this subject, it's worth checking out [this article by Jake Archibald](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle). There's tons of nuance in how the whole dance around the service lifecycle goes, but it is knowable, and that knowledge will go far when using Workbox.

But this article by Jake Archibald is not available, if I click this link it points to the same page (https://developer.chrome.com/docs/workbox/service-worker-lifecycle/)

**To Reproduce**
1. Go under this link https://developer.chrome.com/docs/workbox/service-worker-lifecycle/
2. Scroll to the bottom (just the end of the article)
3. click [this article by Jake Archibald](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle)
4. Page has been refreshed, I am redirected to the same page

**Expected behavior**
Be able to find and open old articles. Links should redirect to correct source

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [chromium]
 - Version [99.0.4844.51 (Official Build) Arch Linux (64-bit)]

**Additional context**
I really don't like  that I cannot find old articles. I also have prepared a presentation for GDSC workshops where I was showing this article, and now it is impossible, so it breaks my presentation some way.

__Originally posted by @kaczor6418 in https://github.com/GoogleChrome/developer.chrome.com/issues/2291__

**Comment by manfredbrandl** [comment]
Can someone please close this?

**Comment by bhousel** [comment]
sure
