### ISSUE TITLE
Multilingual field exceptions 

### ISSUE THREAD

**Issue by ramen2581** [openstreetmap/iD#9043]
### Description

The multilingual field shows up for all tags containing name: such as name:prefix , name:etymology , name:right, name:left , name:source , name:signed etc.  This can cause confusion and issues such as what's seen in https://www.openstreetmap.org/changeset/118595559

### Screenshots

![image](https://user-images.githubusercontent.com/57199493/159137225-52d8a6cc-d097-4be3-979f-ce468c60f3c3.png)

**Comment by 1ec5** [comment]
Some related considerations regarding `name:etymology`: openstreetmap/id-tagging-schema#256.
