### ISSUE TITLE
Tiling - Add Camp Pitch

### ISSUE THREAD

**Issue by scottAnselmo** [openstreetmap/iD#9047]
### Description

Problem: Currently Camp Pitch while a tag preset is not displayed on rendered tiles at any zoom level. It is useful to show at campgrounds where a pitch + ref exists

Solution: When creating tiles use the same icon that's used for the Camp Pitch tag preset w/ the ref value next to it if there's a ref value (e.g. 'A11'). Other icons are fine, but since once already exists might as well reuse it.

**Comment by 1ec5** [comment]
Hi, thanks for this feature request. The iD project isn’t responsible for generating tiles or rendering. You may be looking for [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/issues/), which is the default renderer on openstreetmap.org, or another of the [featured tile layers](https://wiki.openstreetmap.org/wiki/Featured_tile_layers).
