### ISSUE TITLE
`location=yes` added to `leisure=swimming_pool`

### ISSUE THREAD

**Issue by habi** [openstreetmap/iD#9052]
### URL

https://overpass-turbo.eu/s/1h6g

### How to reproduce the issue?

I *don't* know how to reproduce the problem, but today found out that *all* swimming pools which are tagged with `location=yes` (in Switzerland) have been edited with iD (versions 2.15.1, 2.15.4, 2.18.4, 2.18.5, 2.19.6, 2.19.6).
Some of the changes were done by *very* seasoned members of the Swiss OSM community or even board members of the SOSM :)

I tried to reproduce this by drawing a random pool, but couldn't find a way to add the `location=yes`-Tag without typing it in myself.
Can someone with more insight into iDs code help with finding out how swimming pools are (wrongly) tagged like that?

[1]: OK, maybe not *all*, but I checked at least 10 of the ~25 ways in Switzerland.

**Comment by habi** [comment]
The problem also exists in Germany (https://overpass-turbo.eu/s/1h6c) and in France (https://overpass-turbo.eu/s/1h6e).
In France `location=yes` might mean something with rental, though, but a quick check only showed the tag on swimming pools, too...

**Comment by 1ec5** [comment]
The Swimming Pool preset [includes](https://github.com/openstreetmap/id-tagging-schema/blob/6beccb2acf38c5a09778a23b295d42497056485b/data/presets/leisure/swimming_pool.json#L7) a Location field that only offers [`outdoor`, `indoor`, and `rooftop`](https://github.com/openstreetmap/id-tagging-schema/blob/6beccb2acf38c5a09778a23b295d42497056485b/data/fields/location_pool.json#L7-L9) as options and [disallows selecting other values](https://github.com/openstreetmap/id-tagging-schema/blob/6beccb2acf38c5a09778a23b295d42497056485b/data/fields/location_pool.json#L13) (unless you use the raw tag editor below). This version of the preset was first introduced in v2.20.0. Before that, the field [did allow custom values](https://github.com/openstreetmap/iD/blob/v2.19.6/data/presets/fields/location_pool.json#L3). Unless you’re noticing new `yes` values being introduced inadvertently in a newer version of iD, we can consider this issue resolved, right?

**Comment by habi** [comment]
Thanks for the insight Minh!

> This version of the preset was first introduced in v2.20.0.

Ok, then this is an issue stemming from an old iD version, at least for all of the changes I checked.
There's a ton of swimming pool nodes/ways tagged like this, I'll probably set up a maproulette challenge for cleaning up the meaningless `location=yes` tags.

**Comment by simonpoole** [comment]
@1ec5 Doesn't the fix have more to do with the autoSuggestions field being set to false and values from taginfo not being pulled in than disallowing custom values? The probability that location=yes was of taginfo provenance would seem to higher (in particular as we've tracked down at least one clear source of the tag), than people entering it on purpose.

See also https://github.com/openstreetmap/iD/blob/e66edcbc997a33963b108153da6d0f88d8a11573/modules/ui/fields/combo.js#L30

**Comment by 1ec5** [comment]
Yes, it’s both those factors and one more: it was previously a `typeCombo` field, which defaults to `yes` if you open and dismiss the dropdown without selecting another value:

https://github.com/openstreetmap/iD/blob/e66edcbc997a33963b108153da6d0f88d8a11573/modules/ui/fields/combo.js#L80-L82

`typeCombo` fields work this way because they’re meant for feature keys like `entrance`. If you open and dismiss the dropdown for the Type field on the Entrance preset, you want the feature to remain tagged `entrance=yes`; you don’t want `entrance` to be removed, kicking you out of the Entrance preset. It was incorrect to make the Location field a `typeCombo` field, but fortunately, that was also resolved as part of the migration to id-tagging-schema.

**Comment by habi** [comment]
BTW: I've set up a [MapRoulette challenge](https://maproulette.org/browse/challenges/26820), nearly all of the 'offending' pools have been fixed by the community by now.
