### ISSUE TITLE
Render golf=hole ref in edit mode

### ISSUE THREAD

**Issue by tastrax** [openstreetmap/iD#9054]
### Description

I have recently been auditing golf courses mainly for where folks have added 'name' tags to tees, fairways, bunkers, golf holes. By far the largest error is golf=hole having something like '18th' or '18th Hole' in the name field, i suspect so it shows in the editor interface. Just about all also had the correct hole number as ref. It seems to me folks are adding the name tag just to orientate themselves around the course whilst **editing**. This is the obvious way to orientate yourself on a golf course (I am not a player)

Would it be beneficial to display the ref tag as the label in the edit interface (same as the standard OSM render)? I think this would prevent many, many folks from also adding a name tag as well.

### Screenshots

![golf_1](https://user-images.githubusercontent.com/8775395/160347948-12599ed6-3d6b-409c-99dd-406f72072675.JPG)
Render with incorrect use of names (forget the named tees etc)

![golf_2](https://user-images.githubusercontent.com/8775395/160348016-dd734d9f-2e6b-470e-bccd-4cd24e81fc05.JPG)
as incorrectly named objects look in editor - easy to orientate yourself

![golf_3](https://user-images.githubusercontent.com/8775395/160348091-e74fd91c-92a4-4ced-8880-f6532f4eff48.JPG)
how a correctly tagged course looks in the editor - harder to orientate around the course

![golf_4](https://user-images.githubusercontent.com/8775395/160349180-e6c31fa2-92f7-42d7-a744-081f73f6ac2c.JPG)
Correctly tagged holes  without 'name' tagging (forget the tees etc)

**Comment by 1ec5** [comment]
This would be doable with a change similar to #6188 or #8707. (The display name of a feature in the relation member list or relation membership list can also be the display name on the map.)

/cc @k-yle

**Comment by tastrax** [comment]
The more I audit golf courses, the more I think the name key is a bit of a waste on the preset for holes. I only found a couple of courses in all of Australia that had named holes but maybe its just that folks have done the digitising from aerial with no local knowledge?

**Comment by k-yle** [comment]
It's worth noting that `ref` is already rendered in many situations, such as ways tagged as `highway=*`, `waterway=*`, `building=*`, and probably more. Not sure why `ref` doesn't render in some situations like `golf=*`

**Comment by tastrax** [comment]
ref is rendered on the OSM map but its not rendered in edit mode using the ID editor. That's what I am asking for consideration for ref to be displayed in this case.

**Comment by k-yle** [comment]
I can't work out why some of these features show the ref and others don't... (all have `ref=12`)

![image](https://user-images.githubusercontent.com/16009897/160739315-2da1048e-808a-4f20-a7f0-fce9c5b1ca92.png)

**Comment by tastrax** [comment]
What are the two golf features top right? Is Golf hole one of the lines? Do they also have 12 in the name?

**Comment by k-yle** [comment]
yep, they all have `12` as the `ref`, and no `name` tag.

<details><summary>Here's an annotated version (click to expand)</summary>

![annotated](https://user-images.githubusercontent.com/16009897/160760811-41e5f0cd-1b98-4d2e-88e1-d486425091d5.png)
</details>

**Comment by tastrax** [comment]
I am no coder but does it come from here or from the presets?

https://github.com/openstreetmap/iD/blob/develop/modules/util/util.js#L247

**Comment by k-yle** [comment]
I found [the list](https://github.com/openstreetmap/iD/blob/bd1836f/modules/svg/labels.js#L30-L63) that limits which features can use the `ref` as a label. I've opened #9061 to propose removing this restriction for `ref`

**Comment by tastrax** [comment]
Many thanks - should ref be the last resort after name? In most cases a name , where it exists, should probably be the priority before ref (thinking of all tagging here, not just golf features)

**Comment by k-yle** [comment]
yep, `name` is preferred over `ref` - the usual rules from [here](https://github.com/openstreetmap/iD/blob/fab6dfa/modules/util/util.js#L182-L222) apply.

**Comment by sekerob** [comment]
Applied to Miglianico Golf Course... seeing in the ID edit view what one works on is great for orientation, highlighted same hole number used twice on the in and out of the 9th and 18th which run parallel.
