### ISSUE TITLE
'Network' Tag refuses to be capitalized

### ISSUE THREAD

**Issue by cotesta** [openstreetmap/iD#9069]
### URL

https://www.openstreetmap.org/edit#map=17/39.96762/-81.90011

### How to reproduce the issue?

1. Create/Find a road relation
2. Attempt to capitalize the sections in the 'Network' tag via the 'Network' field
3. Click away from the route so it no longer shows on the left bar
4. Return to the road relation by re-selecting it
5. Become annoyed as you realize that the capitalization is all gone and it's in lowercase for some reason

Note that this does NOT happen if you edit the tag manually in the tags list below, it only happens on the 'Network' field specifically in the iD sidebar.

### Screenshot(s) or anything else?

https://user-images.githubusercontent.com/103306302/162562232-9f567ff3-5af6-489b-bebb-bbcd9ff2d329.mp4

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
Thanks for your bug report. This was fixed in openstreetmap/id-tagging-schema#375, which hasn’t been released yet.
