### ISSUE TITLE
Access to Kartaview photos blocked in id-editor

### ISSUE THREAD

**Issue by RobinGoix** [openstreetmap/iD#9075]
### URL

https://www.openstreetmap.org/edit#map=15/48.8696/2.3205

### How to reproduce the issue?

In OSM ID-editor, we should be able to see photos uploaded on Kartaview. This is not the case anymore on my laptop (and others), although it used to work well until a few weeks ago.

To reproduce the bug:
1. open id-editor https://www.openstreetmap.org/edit#map=15/48.8696/2.3205
2. try to display Kartaview photos in the contextual menu "Map Data" on the right

Nothing is displayed on my side, and I obtain the following access errors in the developer tools:

![bug_osm_kartaview](https://user-images.githubusercontent.com/7251843/163127746-27d1426a-a739-406c-8149-6bc27f4fd3ef.JPG)

Thanks a lot for your help!

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox, Chrome, Microsoft Edge

**Comment by mmd-osm** [comment]
You need to get in touch with Kartaview and ask them to fix their server settings.

**Comment by mmd-osm** [comment]
upstream issue has been fixed in the meantime -> let's close this issue.

**Comment by RobinGoix** [comment]
Yes, it is working now. Thanks!
