### ISSUE TITLE
html tags displayed in error message

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/iD#9077]
### How to reproduce the issue?

This bug can only be seen when osm.org returns a 503

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/85302075/163700791-370fcf0f-b871-450a-82f7-a2597a3ff52b.png)

This might be related to #8928

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by danieldegroot2** [comment]
Duplicate of #3366.

**Comment by arch0345** [comment]
Thanks for mentioning that @danieldegroot2, didn't realize how old this issue was
