### ISSUE TITLE
User is able to save single empty node

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9085]
### URL

https://www.openstreetmap.org/changeset/120203963

### How to reproduce the issue?

Unknown.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

**Comment by 1ec5** [comment]
iD doesn’t prevent untagged, standalone nodes from being saved, but the validator does flag it as an error immediately and also on the save screen. Normally the validator adds a changeset tag indicating how many errors or warnings the mapper ignored when saving, but that doesn’t seem to have happened here.

**Comment by danieldegroot2** [comment]
@1ec5 It prevents me from clicking the save button at least.
![image](https://user-images.githubusercontent.com/67521919/165340243-9e188323-4999-441c-bb53-2cfcfb49d754.png)

**Comment by 1ec5** [comment]
Ah, you’re right, that’s the difference between an error and a warning. I wonder if the user managed to save so quickly that the validator didn’t run?

**Comment by danieldegroot2** [comment]
Closing in favour of #9553.
