### ISSUE TITLE
Firefox can't display Street-level imagery

### ISSUE THREAD

**Issue by derkrasseleo** [openstreetmap/iD#9087]
### How to reproduce the issue?

1. Open Openstreetmap iD editor in firefox
2. enable Mapillary
3. A viewer window pops up, but it is just black.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/16163571/165754703-b3b672b7-89c8-4c49-8883-73a778fe5cb1.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by derkrasseleo** [comment]
It was because firefox blocked the facebook trackers, therefore no picture could be loaded

**Comment by Zaczero** [comment]
Just a small follow-up. Mapillary is owned by Facebook and they are using the Facebook CDN - that's why. Cheers
