### ISSUE TITLE
KeepRight: edit field is empty, does not disappear

### ISSUE THREAD

**Issue by st-anton** [openstreetmap/iD#9099]
### How to reproduce the issue?

Enable the KeepRight Problems let you see the all the problems found by KeepRight. Klicking on any KeepRight flash sign, opens the edit field on the left. But there is no description but simply an empty field. If you wand to close the edit field, is does not disappear, but keep persistent.
Seen on Mozilla 100.0 and Edge

### Screenshot(s) or anything else?

![grafik](https://user-images.githubusercontent.com/2517417/167264634-bf7c8f86-16c3-4a06-93f9-e02babc63a1a.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox, Edge

**Comment by mmd-osm** [comment]
Likely duplicate of #9068

**Comment by st-anton** [comment]
Yes, this is a duplicate -> closed here
