### ISSUE TITLE
Changing shop brand leaves wrong `brand:wikipedia`

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#9103]
### How to reproduce the issue?

Create object with 

```
addr:city=Złotów
addr:city:simc=0967423
addr:housenumber=6
addr:postcode=77-400
addr:street=Aleja Piasta
brand=Stokrotka
brand:wikidata=Q9345945
brand:wikipedia=en:Stokrotka
name=Stokrotka
opening_hours=Mo-Sa 07:00-21:00; Su 09:00-20:00
shop=supermarket
```

tags

Select object, search for "JYSK" object to change shop brand. Select the new one.

Now it is tagged

```
addr:city=Złotów
addr:city:simc=0967423
addr:housenumber=6
addr:postcode=77-400
addr:street=Aleja Piasta
brand=JYSK
brand:wikidata=Q138913
brand:wikipedia=en:Stokrotka
name=JYSK
opening_hours=Mo-Sa 07:00-21:00; Su 09:00-20:00
shop=furniture
```

Note mismatching

```
brand:wikidata=Q138913
brand:wikipedia=en:Stokrotka
```

Preferably neither `brand:wikidata` nor `brand:wikipedia` would be added (added based on blind matching of location + name, therefore not adding anything useful) but if `brand:wikidata` is changed then `brand:wikipedia` should be removed or changed.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
This is a side effect of name-suggestion-index getting out of the business of suggesting the very unpopular `brand:wikipedia`, `network:wikipedia`, and `operator:wikipedia` keys: https://github.com/osmlab/name-suggestion-index/issues/6481#issuecomment-1105592768. (Personally, I’m glad to no longer field angry e-mails about these keys anymore.)

Changing `brand:wikidata` could delete `brand:wikipedia` as being outdated, but adding `brand:wikidata` where there wasn’t one previously probably shouldn’t delete `brand:wikipedia`, in case someone has deliberately added that key.
