### ISSUE TITLE
direction

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/iD#9114]
### Description

Hi,

when we open the measurement panel, we have, for a simple line with 2 nodes, its length.
When we want to create a roof in 3D, an important tag is the roof:direction : https://wiki.openstreetmap.org/wiki/Key:roof:direction
If would be great to have, in the measurement panel, for a simple line, its direction.
(Or any tool to know an angle).

Best regards

**Comment by danieldegroot2** [comment]
This is already suggested as part of https://github.com/openstreetmap/iD/issues/5530#issuecomment-1065971502
(the list of examples is shortened to avoid clutter)

**Comment by Mahabarata** [comment]
Not sure of that (I don't want to give a specific direction to a way, I want to know the currently direction of this way).
But clearly my issue is the same as #7459.
So I close mine.
