### ISSUE TITLE
Enhance preset for leisure=horse_riding

### ISSUE THREAD

**Issue by Hufkratzer** [openstreetmap/iD#9118]
## 1. Rename preset to Horseback Riding Center

I think it is better to name this preset Horseback Riding **Center** instead of Horseback Riding Facility because:

* The tag [leisure=horse_riding&nbsp;(wiki)](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dhorse_riding) is often misused for all kinds of stuff related to horseback riding, especially for riding arenas and buildings. To reduce this, apart from solving related https://github.com/openstreetmap/id-tagging-schema/issues/413, renaming this preset may help. **Facility** is not wrong but it is too general and ambiguous, as you can see on these webpages:
  * ​http://www.peacefulbaystables.com/our-facility.html
  * https://lilacthymestables.com/our-history/our-facilities
  * https://www.blackberry-stables.com/our-facilities
  * https://www.edwardsequestrianfacility.com/facilities--amentities
  * ​https://www.lancingequestrian.co.uk/Facilities
  * http://netherclayliverycentre.com/facilities
  * https://www.pontispool.co.uk/our-facilities
  * https://www.mceq.com.au/our-facilities

* According to ​https://www.bhs.org.uk/enjoy-riding/find-a-place-to-ride/results?cat=Riding+Centre of the _British Horse Society_ Riding Centres can be named differently and all these names can be found more often in the OSM database together with leisure=horse_riding than Facility:
  * 594 centre/center (467+127)
  * 422 farm/ranch (160+262)
  * 267 stables/stable (233+34)
  * 11 facility/facilities (10+1)

  For use independant from OSM see ​[Google Trends camparison](https://trends.google.com/trends/explore?date=today%205-y&q=riding%20facility,riding%20center,riding%20centre).

Corresponding JOSM request is [here](https://josm.openstreetmap.de/ticket/21907#comment:28).

## 2. Change background color for icon
I think the gray background color for the icon of the Horseback Riding Facility preset may arouse false associations and be inappropriate:
![hbrfcolor2](https://user-images.githubusercontent.com/5958184/162467877-2a4d9ce3-8388-4b28-baa4-a3bc0c9d69f7.jpg)

I think the color that is used for the icon in the Farmyard preset might be more appropriate.

Related: https://github.com/openstreetmap/id-tagging-schema/issues/273 (already done)

**Comment by tyrasd** [comment]
1. was fixed in https://github.com/openstreetmap/id-tagging-schema/commit/2be67fdc9dffa30e58288af479f62d8f38b001f3
2. will need to be adjusted in iD's code (the colors are essentially defined by how the features are rendered on the map) – I'll move the issue to iD's issue tracker

**Comment by Hufkratzer** [comment]
Then I close this in the hope that one day the background color will improve automatically. Thanks.
