### ISSUE TITLE
Bike icon now missing

### ISSUE THREAD

**Issue by tdelmas** [openstreetmap/iD#9136]
### URL

https://www.openstreetmap.org/edit#map=20/48.82366/2.39720

### How to reproduce the issue?

Edit a map with a bicycle parking.

Should display a parked bike icon, but it's blank. (both in the map and on the left tab)

It worked before.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/1955774/170891298-8ec4eca0-5224-410e-9b00-946514a55adb.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by danieldegroot2** [comment]
This is because some new presets link to icons which are not yet bundled with iD. It will be resolved with the next release of iD, which should be ready soon.

If this resolves the issue, feel free to close it yourself. You can find the purple Close issue button below alongside the green Comment button.

**Comment by FloEdelmann** [comment]
Search keyword for others that try to find this issue: bicycle_parking

**Comment by danieldegroot2** [comment]
> Search keyword for others that try to find this issue: bicycle_parking

"bicycle parking" is already in the reproduction description
> Edit a map with a bicycle parking.

It looks in all of the title, description and comments. It shouldn't matter if you're searching -the tag- with an underscore.

**Comment by FloEdelmann** [comment]
I tried searching `bicycle_parking` first, and didn't find this issue. So it seems like the underscore really matters. But now, since the comment mentions the word with underscore, it works. I'm going to hide my comments as off-topic to not further distract from the issue.

**Comment by arch0345** [comment]
The version on osm.org just got updated and the new bike parking icon now shows up:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/85302075/172659114-cdce7fa5-9f8c-4679-a615-4b8669c0f8b0.png">

**Comment by tdelmas** [comment]
I confirm, perfect, thank you everyone!
