### ISSUE TITLE
Add Carpet Hanger

### ISSUE THREAD

**Issue by Coolawik** [openstreetmap/iD#9145]
### Description
Carpet hanger was approved in OSM Wiki in 2018 (https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcarpet_hanger). Can you add it to presets?

### To do
Add:
- man_made=carpet_hanger

### Screenshots

![Zrzut ekranu 2022-06-01 180306](https://user-images.githubusercontent.com/106607132/171449097-8c975718-4aac-4437-bb08-3bb2d70ec692.jpg)
(in Polish)

**Comment by arch0345** [comment]
A preset for `man_made=carpet_hanger` was added in https://github.com/openstreetmap/id-tagging-schema/pull/452, but it looks like the files missing the .json extension. I'll open a PR on id-tagging-schema to fix this

**Comment by Coolawik** [comment]
@arch0345 thanks!
