### ISSUE TITLE
Empty node icon has moved to empty areas, leaving empty nodes part of areas without icon.

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9157]
Standalone nodes still have the empty node icon.

But nodes part of areas use the fallback 'icon'.

![image](https://user-images.githubusercontent.com/67521919/173197088-24a53aa8-8abb-4a4d-a808-4ded8354f32e.png)

Also, empty areas themselves inherit the empty node icon.

![image](https://user-images.githubusercontent.com/67521919/173241922-67bad3d0-796a-4221-b59c-acf3e23347c6.png)

(related to earlier issue);

> The version on osm.org just got updated and the new bike parking icon now shows up:

( https://github.com/openstreetmap/iD/issues/9136#issuecomment-1150084562 )

**Comment by tyrasd** [comment]
interesting… it works for me 

![image](https://user-images.githubusercontent.com/1927298/173423804-02a96f2a-b254-4828-9099-2d304352122a.png)

Can you please explain how exactly you managed to trigger the bug?

**Comment by danieldegroot2** [comment]
Browser: Chrome

**Comment by danieldegroot2** [comment]
@tyrasd I just ran into another issue, was about to submit it but saw your reply. Sorry for the multiple edits, but I've changed my top post now to describe the issue correctly.

**Comment by danieldegroot2** [comment]
Also, empty ways now look like this (white-on-white):
![image](https://user-images.githubusercontent.com/67521919/173446348-6285cad6-f387-446e-adb3-bac234cecb47.png)

**Comment by tyrasd** [comment]
I still cannot reproduce the issue. I tried it with chrome using the integrated version of iD (v2.21.0) on osm.org, and it appears to work just fine. :thinking: 

> Also, empty ways now look like this

this is how it is supposed to look like, isn't it?

**Comment by danieldegroot2** [comment]
Summary;
![image](https://user-images.githubusercontent.com/67521919/173564526-46e78efe-ca47-4ea3-85e6-c955c6cc57ee.png)

Expected behaviour: Area should show an empty square, not a point icon. node part of area or way should show a point icon.

> this is how it is supposed to look like, isn't it?

Mostly it makes sense, but you should be able to see at least the nodes (black casing). If you want to display an empty line, you could do the same and give it black casing

![image](https://user-images.githubusercontent.com/67521919/173564395-2f6a19e6-2a71-4bf7-a20b-dc3afaef03ab.png)

![image](https://user-images.githubusercontent.com/67521919/173565650-eb5bf67d-1451-4798-897e-c569c1bc215d.png)

**Comment by tyrasd** [comment]
Ah, the missing icon is for vertex nodes. Sorry, I somehow didn't get that info in your first post.

This regression was introduced in bd1836fd0cf53254ed88352eb69a78da51092692.
