### ISSUE TITLE
HTML escaping issue in "Errors occurred while trying to save" modal

### ISSUE THREAD

**Issue by CorruptComputer** [openstreetmap/iD#9161]
### URL
n/a

### How to reproduce the issue?
1. Make some changes
2. Try to upload while osm.org is down or under heavy load

### Screenshot(s) or anything else?
![image](https://user-images.githubusercontent.com/5573038/173598676-af121f25-5e58-4d8c-9962-abb7abad8b84.png)

### Which iD Editor versions do you see the issue on?
Released version at openstreetmap.org/edit
(2.21.0 at the time of reporting)

### Which browsers are you seeing this problem on?
Vivaldi (not an option in the browsers list, but is Chromium based)

**Comment by bhousel** [comment]
Yep that's #3366

**Comment by CorruptComputer** [comment]
Ah, sorry I had searched for the title of the modal "Errors occurred while trying to save" when looking for duplicate issues and didn't find that one. Closing this one since its a duplicate.
