### ISSUE TITLE
iD editor just recently broke: regex problem

### ISSUE THREAD

**Issue by hobbit-ns** [openstreetmap/iD#9163]
### URL

[any editing link]

### How to reproduce the issue?

Is this even the right place to report bugs?   I can only repost [what I put in one of the forums](https://help.openstreetmap.org/questions/84771/id-editor) and hope the right eyeballs see it:

Sometime between 1 - 2 months ago when I last edited and now, the in-browser editor has been rendered nonfunctional for me. The problem I can dig up in the debugger reads thusly:
```
   SyntaxError: invalid regular expression flag s
   id-6172ebd02911868e7b330b540a9baa13d0fcf18c6f57ad447234ca1ec33f4e0f.js:11:8250
```
in file
https://www.openstreetmap.org/assets/id-6172ebd02911868e7b330b540a9baa13d0fcf18c6f57ad447234ca1ec33f4e0f.js,
the code fragment in question reads
```
   {var n=o.replace(/#.*/us,"");
```
"s" is a rather recent regex modifier, and is NOT guaranteed to be present in some number of even recent-ish vintage browsers. It's not even shown at regex101.com yet, a very common go-to reference. This gratuitous type of change has probably broken functionality for a lot of people, who are perhaps not at liberty to rip up their whole browser environment for a bleeding-edge upgrade they don't need.

The workaround for the functionality of the "s" flag is to use '[\s\S]' instead of '.', then matching works across newlines. Someone should FIX this, if they care about keeping the community accomodating and welcome. Coming home from an afternoon of mapping trails that aren't in the database yet, being blocked from adding them is not exactly what I expected.

After a bit of research, I confirmed that the regex "s" flag fails on firefox 78, and works okay on firefox 91ESR which I am able to run in a very limited test environment.  This is still suboptimal, and doesn't help anybody with a browser that's not even all that old, but unable to upgrade for any of a host of reasons.  Please just make the code a little better WRT backward-compatibility.

If this wasn't the right way to report this, someone more familiar with github please move it appropriately.

_H*

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
Hi, thanks for taking the time to report this issue. I know how frustrating it can be to get blocked from mapping for such a small reason.

I can reproduce the error in older versions of Firefox. This regular expression was introduced in 352f244d68a32db3785f1ddf6973a24f9bfe9f8f, released [a couple weeks ago](https://github.com/openstreetmap/iD/releases/tag/v2.21.0) and deployed to the website last week in openstreetmap/openstreetmap-website#3561. This release intentionally dropped support for Internet Explorer 11 (#8811), but I don’t see any documentation about which other browser versions this project intends to support. The workaround is suitable in any case; see #9165.

**Comment by hobbit-ns** [comment]
Excellent, thanks very much!

_H*
