### ISSUE TITLE
Text from preset selections ends up in tags

### ISSUE THREAD

**Issue by mueschel** [openstreetmap/iD#9164]
Recently I fixed a couple dozen nodes of recycling containers with strange tags like

recycling:any_glass_(tempered_glass
recycling:etc.)
recycling:tout_type_de_verre_(cristal)
recycling:jakékoliv_sklo_(temperované_sklo
recycling:jedes_glas_(gehärtetes_glas

This is a recent phenomenon and happens only with edits from iD.

**Comment by arch0345** [comment]
Relates to https://github.com/openstreetmap/id-tagging-schema/pull/400

**Comment by 1ec5** [comment]
I can reproduce this issue in v2.22.0. It was a latent bug that got triggered by both openstreetmap/id-tagging-schema#349 and openstreetmap/id-tagging-schema#400. Previously, the multiCombo field expected users to enter the raw subkey names, but now localized options are presented to the user.

For example, in the Vietnamese localization, if I select “Chai Thủy tinh” (`glass_bottles`) from the dropdown menu, this code sets `k` to `glass_bottles` but `value` to `Chai Thủy tinh`:

https://github.com/openstreetmap/iD/blob/d0b1fb1ebe35cab057c7095adc513134ef399d61/modules/ui/fields/combo.js#L223-L229

**Comment by atarom** [comment]
Does it seem like the bug is back?
https://osmlab.github.io/osm-deep-history/#/node/10021318492
with my 2.21.1 and this node is reproducible

**Comment by 1ec5** [comment]
openstreetmap/iD#9168 hasn’t been released yet, so unfortunately mappers are still able to hit this bug as before.
