### ISSUE TITLE
Using `Connect the features` with Crossing With Pedestrian Signals doesn't work as expected

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/iD#9176]
### How to reproduce the issue?

1. Add a `Crossing With Pedestrian Signals` way that crosses a street
2. While selecting this new way, click on `Connect the features`
3. A generic `highway=crossing` node is added

When using `Connect the features` with a `Unmarked Crossing` or `Marked Crossing` way, it adds an `Unmarked Crossing` or `Marked Crossing` node respectively. Because of this, I think it makes sense for it to add a `Crossing with Pedestrian Signals` node instead of just a generic `highway=crossing` node

### Screenshot(s) or anything else?

<img width="516" alt="image" src="https://user-images.githubusercontent.com/85302075/174866121-374c4206-5ce5-4858-a4ba-ff18c86f7e8e.png">
<img width="514" alt="image" src="https://user-images.githubusercontent.com/85302075/174866280-f37e38ca-4218-4165-98a9-de5acda91c0c.png">

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
fixed in #9181
