### ISSUE TITLE
Bing vintage no longer visible

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/iD#9197]
### URL

https://ideditor.org/id-2.21.1/#background=Bing

### How to reproduce the issue?

Click on 'Show Background Panel' in the Background menu. The vintage of the imagery no longer shows up in the Background Panel and clicking on 'Show Tiles' shows that the vintage is unknown. Only v2.21 is affected

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/85302075/177671082-b9689b9a-dd5d-4d31-9524-834a1a3e2c2c.png)
v2.21.1 (https://ideditor.org/id-2.21.1/)

![image](https://user-images.githubusercontent.com/85302075/177671167-406d17a0-cce1-41c1-979d-9b2e5fe48729.png)
v2.20.4 (https://ideditor.org/id-2.20.4/)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by timothywashere** [comment]
Probably caused by #9153
BING imagery is not loading, what you see is actualy ESRI

**Comment by tyrasd** [comment]
let's track this together with #9153

**Comment by tyrasd** [comment]
FYI: Bing's vintage information seems to be available again (at least today), see https://github.com/openstreetmap/iD/issues/9153#issuecomment-1189895832
