### ISSUE TITLE
Osmose QA layer no longer loading, returns 422 error

### ISSUE THREAD

**Issue by Njorlpinipini** [openstreetmap/iD#9208]
### Screenshot(s) or anything else?

Usually when the Osmose layer doesn't work its a problem with Osmose itself, but their website is working fine this time. I know they updated their API recently, so maybe the Osmose database doesn't recognize the Id editor's requests anymore. 

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.21.0

### Which browsers are you seeing this problem on?

Chrome, Firefox, Microsoft Edge

**Comment by tyrasd** [comment]
Should be fixed now. You can test it on https://ideditor.netlify.app/

> I know they updated their API recently

For the future, it would be good to know about upstream API changes in advance. Do you know where these changes are announces? //cc @frodrigo

**Comment by frodrigo** [comment]
`.json` reestablish using a rewrite rules on Osmose API side.

**Comment by tyrasd** [comment]
@frodrigo the redirect from the `.json` endpoints seem to not send the `access-control-allow-origin` CORS header anymore at the moment, resulting in client side errors:

![image](https://user-images.githubusercontent.com/1927298/190437971-0f534031-004b-4e1e-9583-d484b88c2d48.png)

**Comment by frodrigo** [comment]
> @frodrigo the redirect from the `.json` endpoints seem to not send the `access-control-allow-origin` CORS header anymore at the moment, resulting in client side errors:

Fixed. On server side. But note it is due to an HTTP redirect. The current URL is in `.geojson` and no more in `.json`

**Comment by tyrasd** [comment]
> The current URL is in .geojson and no more in .json

yes, iD will use the new `.geojson` URL starting with the next release.
