### ISSUE TITLE
addr:direction=South renders like direction=180

### ISSUE THREAD

**Issue by andrewpmk** [openstreetmap/iD#9219]
### URL

https://www.openstreetmap.org/edit#map=18/28.39285/-81.50416

### How to reproduce the issue?

A tag of addr:direction=South renders an arrow pointing south, as if it were tagged as direction=South or direction=180.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/10249827/181133961-bb3db46b-7f5b-4c6d-a873-e3382cc108f6.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.21.1

### Which browsers are you seeing this problem on?

Chrome, Firefox, Microsoft Edge, Safari

**Comment by bhousel** [comment]
Oh!  Please don't do this..

The correct address street of this Winn-Dixie is **11957 South Apopka Vineland Road**
https://www.winndixie.com/storedetails/orlando/fl/?search=2215&zipcode=32836

In OSM tags, this should be 
`addr:housenumber=11957` and `addr:street=South Apopka Vineland Road`

The "South" really should be entered part of the `addr:street` tag.  There is no `addr:direction` tag - that's not a thing.

It looks like you are listing the `source:addr:*` tags as "Orange County GIS".   That's good that you are using a public source to improve OSM, but the process to convert GIS data into OSM tags can be kind of tricky, you need to follow the OSM conventions for addresses.   I guess what I'm asking is : if you were told to enter the data this way, or if you're working with data formatted this way, we need to raise an issue with the training or with the script that prepared the data.

**Comment by bhousel** [comment]
ok I looked into the history of this Winn-Dixie node:
https://pewu.github.io/osm-history/#/node/892054121

It looks like NE2 added the `addr:direction` tag a long time ago in 2011.   So this is good news - I'm now not so worried about someone's current editing process introducing nonstandard address tags.  (Sorry @andrewpmk if my comment above came across as accusing you, I didn't mean it in that way).

Maybe the correct course of action is a maproulette challenge to find any instances of `addr:direction` and merge them back into the `addr:street`?

**Comment by danieldegroot2** [comment]
This custom address formatting should be discussed with the local communities in Florida (for NE2) and Italy (with [totera](https://www.openstreetmap.org/user/totera))

@tyrasd I'd suggest to close as not planned.

**Comment by tyrasd** [comment]
Initially, I was thinking that changing the rendering of the direction tags could be limited to an allowlist of keys, because it doesn't make too much sense to render these for undocumented and/or invalid tags (like the one reported above, or for example something like `disused:direction`). But looking at taginfo, these cases seem to be pretty rare and probably not worth the effort to maintain an extra list
