### ISSUE TITLE
Add open FHRS:id page from editor like wikipedia

### ISSUE THREAD

**Issue by hb0nd** [openstreetmap/iD#9220]
### Description

it'd be nice to be able to open an FHRS:id page in the same way that you can open a wikipedia page.

Link format: https://ratings.food.gov.uk/business/{{FHRS:id}}

**Comment by boothym** [comment]
Would also be good to have a FHRS field for cafes, restaurants, pub presets in the UK.

**Comment by flacombe** [comment]
Shouldn't it be moved to https://github.com/openstreetmap/id-tagging-schema/?

**Comment by hb0nd** [comment]
> Shouldn't it be moved to https://github.com/openstreetmap/id-tagging-schema/?

you're right :) moved to https://github.com/openstreetmap/id-tagging-schema/issues/1022
