### ISSUE TITLE
Line not connected QA bug

### ISSUE THREAD

**Issue by natfoot** [openstreetmap/iD#9221]
### How to reproduce the issue?

I don't know how to recreate this bug but I get it when adding new lines to the map on a regular basis.  The Quality Assurance tell me that the line is not connected and is free floating when it clearly is not. 
![False](https://user-images.githubusercontent.com/5571588/181371053-56f85d74-94d4-4018-b622-5f434027b362.jpg)
 

### Screenshot(s) or anything else?

![False Negative](https://user-images.githubusercontent.com/5571588/181370749-1e61e418-433e-4e95-b58a-e2211b457c03.jpg)
I can either save past the warning or move one of the ends of the line and this issue is removed. 

### What version numbers does this issue effect?

2.21.1

**Comment by danieldegroot2** [comment]
Duplicate of #8758.

**Comment by natfoot** [comment]
Duplicate of https://github.com/openstreetmap/iD/issues/8758.
