### ISSUE TITLE
`autoSuggestions` option seems to pull in low-use values as well

### ISSUE THREAD

**Issue by jdhoek** [openstreetmap/iD#9227]
In openstreetmap/id-tagging-schema#553 I am seeing that `autoSuggestions` set to `true` (the default if missing) is pulling in tag values from TagInfo with as little as 16 uses. Is this by design?

Because anyone can create and use new tag values (and tags), the values used are not necessarily useful or correct. Misspellings and synonyms for more common tag-values are a common occurrence. To prevent propagating such tag values, editors that implement an auto suggestion feature should probably set a lower limit to the number of uses for a tag. A very safe limit is `1000`, which matches the level at which TagInfo starts keeping usage graphs etc. for that tag-value as well.

Possibly, such a lower limit could be lowered for specific fields eventually, if needed.

**Comment by 1ec5** [comment]
The specific behavior of the `autoSuggestions` flag is up to the client applications that implement schema-builder, such as iD. iD currently requires [at least 10 occurrences](https://github.com/openstreetmap/iD/blob/1efdcb60ba98d1fd5000b68c2ccf2e6ca64387da/modules/ui/fields/combo.js#L199) of a tag coming from taginfo before it’ll show up in the list. However, there are a bunch of other heuristics in the same method, such as omitting deprecated values.

I suspect taginfo’s 1,000-occurrence threshold is for performance reasons; it would be expensive to generate usage graphs and compute most frequent combinations for the long tail of tags, regardless of validity. Taginfo has a different threshold of [100 occurrences](https://github.com/taginfo/taginfo/blob/34676f568d61c1a3a6b8fd965107e04a6b645524/sources/db/post_grades.sql#L25-L27) for considering an alphanumeric key “good”.

openstreetmap/iD#7174 was a similar case where some very rare values were showing up unexpectedly. There are two existing solutions to that problem: either mark the problematic values as deprecated or turn off `autoSuggestions`, as you’ve done in openstreetmap/id-tagging-schema#554. The advantage of this approach is that we know which values of `parking:orientation` are valid and which are invalid (all the rest); on the other hand, we don’t have as much visibility into which keys will be adversely affected by a much higher threshold.

**Comment by jdhoek** [comment]
> on the other hand, we don’t have as much visibility into which keys will be adversely affected by a much higher threshold.

Conversely, it may be hard to see if many bad tags get propagated with the limit set to 10 as well. 10 is awfully low for most tags; in my experience any tag value below 100 (excepting tags that document things like opening hours or monetary amounts which shouldn't suggest values at all anyway) should probably be ignored by tools. These are not bad values per se, but they tend to include lots of synonyms, misspellings, and unconventional notations. Could that limit perhaps be raised from 10 to 100?

**Comment by 1ec5** [comment]
A minimum of 100 occurrences doesn’t seem like a painfully high bar to clear for keyword-like values, so I think that would be a decent thing to try. Maybe we could also exempt documented values from the minimum, like taginfo does. That would accommodate tags like [`marker=paddle`](https://wiki.openstreetmap.org/wiki/Tag:marker%3Dpaddle) that aren’t mere typos sneaking in under the radar. I think the filter has access to taginfo’s wiki-based description strings (though not the description strings that come from data items).

You’re right that some keys with non-keyword values, like `opening_hours` and `maxweight`, may be impacted by this change. Of course the best solution would be to have dedicated support for special syntaxes (e.g., openstreetmap/iD#974 ideditor/schema-builder#15), but in the meantime, maybe a [per-field property](https://github.com/ideditor/schema-builder/blob/main/schemas/field.json) could indicate the minimum number of occurrences required for inclusion in the taginfo-powered list for that key.

**Comment by jdhoek** [comment]
> A minimum of 100 occurrences doesn’t seem like a painfully high bar to clear for keyword-like values, so I think that would be a decent thing to try. Maybe we could also exempt documented values from the minimum, like taginfo does.

Yeah, that seems like it would cover most desirable values, although usually documented values exceed 100 uses anyway. Exceptions are perhaps the long-tail tags like `shop=*`.

**Comment by tyrasd** [comment]
> 100 occurrences

Yeah, 10 seems indeed to be too low for the cut-off point. I tried to look for some valid tags which might get hidden when increasing it to 100, and didn't find many. There are some examples:

* `traffic_calming=choked_island` – [62 objects](https://taginfo.openstreetmap.org/tags/traffic_calming=choked_island), [_approved_ status](https://wiki.openstreetmap.org/wiki/Tag%3Atraffic_calming%3Dchoked_island)
* `seamark:buoy_lateral:colour=red;green;red;green`  [66 objects](https://taginfo.openstreetmap.org/keys/seamark:buoy_lateral:colour#values), [_de facto_ status](https://wiki.openstreetmap.org/wiki/Key:seamark:buoy_lateral:colour)
* `amenity=dog_parking` – [75 objects](https://taginfo.openstreetmap.org/tags/?key=amenity&value=dog_parking), [_unspecified_ status](https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Ddog_parking)

I think it is also important to keep in mind that the autocomplete/suggestion functionality is meant to be a way for users to discover the more niche, less often used tags. In a2cacaa I went with a similar metric which is already used for filtering out uncommon tag keys: by only returning values which are either used more than 100 times **or have a wiki page**. This still lets a few "bad" tags slip through, i.e. ones where the wiki page describes them as spelling mistakes or similar error cases of another tag value, but those cases should probably be best modeled in the `deprecated` tags list of the _id-tagging-schema_.
