### ISSUE TITLE
Data Layer Osmose Issues does not show any issues

### ISSUE THREAD

**Issue by turbotimon** [openstreetmap/iD#9245]
### URL

https://www.openstreetmap.org/edit#map=12/48.8615/2.3844

### How to reproduce the issue?

1. Go to a mayor city like Paris, which should have thousand of osmose issues
2. Enable the Osmose Issue data layer in the right toolbar
3. See that no icons are shown while KeepRight Issues and ImproveOSM Issues are functioning well

Tested in Chrome and Firefox. Several 302 and a few CORS errors appearing in the dev console.

### Screenshot(s) or anything else?

![2022-08-16 09_45_36-2022-08-16 09_39_33-Greenshot2](https://user-images.githubusercontent.com/57718207/184825928-ef4f381c-01c0-46b3-8509-3119421be317.png)

![osmoselayer302](https://user-images.githubusercontent.com/57718207/184835584-f5d87b64-b231-4b96-8648-637885a30d34.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by turbotimon** [comment]
Update: It seems as this bug is already fixed, because in the the current develop branch, the api url is changed to `.geojson` which should solve this error: https://github.com/openstreetmap/iD/blob/develop/modules/services/osmose.js#L126

**Comment by turbotimon** [comment]
Update: It seems as this bug is already fixed, because in the the current develop branch, the api url is changed to `.geojson` which should solve this error: https://github.com/openstreetmap/iD/blob/develop/modules/services/osmose.js#L126

**Comment by tyrasd** [comment]
see also https://github.com/openstreetmap/iD/issues/9208#issuecomment-1248228039
