### ISSUE TITLE
Ajout datation fond de carte

### ISSUE THREAD

**Issue by gogo25171** [openstreetmap/iD#9254]
### Description

Bonjour,
J'aimerai savoir s'il pourrait y avoir un datation de la donner des fonts de cartes car parfois je ne sais pas la quel est la plus récente.
Merci d'avance, cordialement.

**Comment by danieldegroot2** [comment]
Pour les fotos aeriennes, utilise `Ctrl` + `Shift` + `B`. Quelques fotos n'a pas de datation, parce que c'est difficile les obtenir..
Les cartes OpenStreetMap, OpenTopoMap sont 'en direct' mais ont pas tes changements dans l'editeur.

(Shortcuts: utilise `?` <=> le panneau 'Aide' dans le menu droit, ou https://wiki.openstreetmap.org/wiki/FR:ID/Shortcuts )

**Comment by gogo25171** [comment]
Ok merci
