### ISSUE TITLE
iD Editor currently not accessible

### ISSUE THREAD

**Issue by tkansgar** [openstreetmap/iD#9289]
### Description

Hi,
I'm not sure, whether this is the correct place to ask this, but I don't know, where to ask elsewhere. Today I cannot access any version of the iD Editor. https://www.openstreetmap.org/edit?editor=id as well as https://preview.ideditor.com/release/ don't work currently. Is this issue known, and could iD Editor be made accessible again in the short term?
BR
tkansgar

**Comment by manfredbrandl** [comment]
For me iD is okay:
![EA4A225D-BCEB-462E-9C58-1CDB3F202A65](https://user-images.githubusercontent.com/5360273/189511527-c00f00e6-ef7f-4ee2-acb5-bc1b773ba24b.jpeg)

**Comment by tkansgar** [comment]
Yes, you're right, the normal release version now works for me too. The cause of my issue was NoScript suppressing one URL, which seems to be needed for iD to work. Don't know, whether it was due to a change in iD or NoScript, but this doesn't matter for me. I have allowed that URL in NoScript, and now iD is working again.

But nevertheless the normal release version of iD isn't really useful for me due to my issue #8105, which seems to be not resolved until now. So I'm missing the older version, which was available under https://preview.ideditor.com/release/ until a few days ago, but now isn't. So I would be very grateful, if either #8105 could be resolved or https://preview.ideditor.com/release/ could be accessible again.

**Comment by cicku** [comment]
```
➜  ~ dig preview.ideditor.com

; <<>> DiG <<>> preview.ideditor.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6465
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;preview.ideditor.com.          IN      A

;; AUTHORITY SECTION:
ideditor.com.           3600    IN      SOA     daisy.ns.cloudflare.com. dns.cloudflare.com. 2288060409 10000 2400 604800 3600

;; Query time: 70 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sun Sep 11 12:13:34 PDT 2022
;; MSG SIZE  rcvd: 109
```

**Comment by tkansgar** [comment]
@cicku: And what is that supposed to tell me now? I don't know.

**Comment by cicku** [comment]
It means `preview.ideditor.com` does not exist.

If you cannot access OSM website, please check your internet connection.

**Comment by manfredbrandl** [comment]
As we all agree that the iD Editor is currently accessible, can anyone please close that issue?

**Comment by tkansgar** [comment]
> As we all agree that the iD Editor is currently accessible, can anyone please close that issue?

I will do.

**Comment by tyrasd** [comment]
Regarding preview.ideditor.com: this subdomain was accidentally switched off while recently moving the domain ownership to the OSMF. It should now be operational again (in form of a redirect to our new preview instances[^1]), thanks @Firefishy!

[^1]: https://ideditor-release.netlify.app/ is the current place where the latest released version of iD is hosted (replacing https://preview.ideditor.com/release/)
