### ISSUE TITLE
Scroll wheel gets stuck after using the colour picker tool

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9296]
### How to reproduce the issue?

1. create i.e. a bench (any object with a colour field by default for ease)
2. click on the colour menu button to the right of the colour input field
3. click on the colour picker
4. pick a colour with the colour picker (from satelite or street level imagery)
5. the mouse scroll wheel is now stuck

This can be fixed by going to a different tab in the browser and going back.

(Have not tested on different setups yet.)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit
Development mirror at https://ideditor.netlify.app/

### What version numbers does this issue effect?

2.21.1

### Which browsers are you seeing this problem on?

Chrome 105.0.5195.102, 105.0.5195.127 on Windows 7
Can't reproduce on Chrome -or Edge- on Windows 10.

The colour picker itself seems to be specific to Chrome and Edge. Firefox only has default colour selection.

**Comment by tyrasd** [comment]
This sounds very much like a bug in the browser. On the other hand, I'm not able to reproduce it here (Chrome version 105.0.5195.52, 64 bit, Ubuntu). On which version of chrome and operating system did you encounter this?

**Comment by danieldegroot2** [comment]
This bug seems to be specific to Windows 7. I haven't tested it with Edge on Windows 7, but it may have the same behaviour, as it seems to share the same colour picker.

**Comment by tyrasd** [comment]
Is the buggy behavior only present in iD, or on all pages that offer a color picker, say this one for example: https://www.w3schools.com/colors/colors_picker.asp ?

**Comment by danieldegroot2** [comment]
It is specifically the colour picker button (inside the colour selection menu, on the left), which allows to pick colors from anywhere on the screen.

![image](https://user-images.githubusercontent.com/67521919/190631280-a854ed42-3767-4f07-b3fb-b26066855330.png)

**Comment by tyrasd** [comment]
yes, that's understood. I was just curious whether the "scroll wheel stuck" state bug is only occurring in iD, or also on other websites when the color picker button of the HTML color picker element is used. On the page I linked above you can access the color picker where it says "Or Use HTML5".

**Comment by danieldegroot2** [comment]
It also occurs on the website you linked.

**Comment by tyrasd** [comment]
ok, then this means, that there is unfortunately not much we can do to fix this in iD. The only thing you could do it to report it on chrome's bug tracker (https://bugs.chromium.org/p/chromium/issues/list), if it's not a known issue already.
