### ISSUE TITLE
Biggest Salt Flatland in the world not rendered in the Map

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#9305]
The "Salar de Uyuni" the biggest Salt Flatland in the world is not rendered in any way in the Map.

Could this be solved? 

Please review: https://www.openstreetmap.org/relation/1769713.

Also surface=salt should be a valid value for any kind of ways in and around salt flatlands areas.

Thanks and Best Regards

**Comment by tyrasd** [comment]
For the map rendering question, I assume you mean the rendered map on openstreetmap.org, right? If yes, please refer that question to a better suited forum like [community.osm.org](https://community.openstreetmap.org/) or [the issue-tracker of the openstreetmap-carto project](https://github.com/gravitystorm/openstreetmap-carto/issues).

Support for `surface=salt` was added in https://github.com/openstreetmap/id-tagging-schema/commit/d5fece12ce028df382ff27791abc4a290391ba22
