### ISSUE TITLE
I can' save my changes on ID

### ISSUE THREAD

**Issue by toygaralak** [openstreetmap/iD#9324]
### Screenshot(s) or anything else?

![osmissue](https://user-images.githubusercontent.com/95170414/194088895-e71da292-101c-4037-9946-e7bcfe786fcc.png)

### Which browsers are you seeing this problem on?

Chrome

**Comment by toygaralak** [comment]
In this screen, I can't press left menu, please help me!

**Comment by tyrasd** [comment]
This is probably related to a failed resolving of conflicts on an object which was simultaneously modified by another user. A duplicate of issue #7199. see https://github.com/openstreetmap/iD/issues/7199#issuecomment-571424902 for a possible workaround to restore your edits.
