### ISSUE TITLE
Not defaulting to Bing imagery

### ISSUE THREAD

**Issue by jleedev** [openstreetmap/iD#9325]
### URL

https://ideditor.netlify.app/

### How to reproduce the issue?

1. Load https://ideditor.netlify.app/
2. Look at the background imagery iD chooses by default

Expected: Bing
Actual: "© GeoBasis-DE/LVermGeo LSA, ATKIS_BU" (Shape of buildings in saxony-anhalt)

### Screenshot(s) or anything else?

![Screenshot 2022-10-04 14 18 37](https://user-images.githubusercontent.com/23022/194116499-3739f079-3e3e-485a-91e2-46e747e869a9.png)

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.23.0-dev, 2.22

### Which browsers are you seeing this problem on?

Chrome, Firefox

**Comment by tyrasd** [comment]
Confirming. This bug surfaced after 841789621f0743bcadc84f05d7556a30e4f193eb, but it was "kind of" present for a long time, only not triggered in certain circumstances (here's an example URL where it is present in v2.21: https://id.raifer.tech/sotm-2022/v2.21/#disable_features=boundaries&map=8/52.14/11.58).

I think to fix this there's two things to be done:
1. take imagery source's extent into account when choosing the background to load: if a source is much smaller than the current map view, we shouldn't use it 
2. ~~select "best" overlays independently from "best" background~~ only automatically activate imagery layers which are not classified as an overlay
