### ISSUE TITLE
Background "X“ half covered

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9327]
### Screenshot(s) or anything else?

![www openstreetmap org_edit](https://user-images.githubusercontent.com/1230959/194386657-8499462e-f81d-4991-818d-d0901797df74.png)

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
hmm, I cannot confirm this issue locally. which browser do you use?

**Comment by tyrasd** [comment]
or does this happen when the browser window's height is very small?

**Comment by jidanni** [comment]
All I know is I was using my aunt in law's old Acer laptop using Chrome on the Windows operating system.

**Comment by tastrax** [comment]
Occurs if you have a tiny map window. Must be a very old laptop with very small screen. Maybe maximise the window.

![image](https://user-images.githubusercontent.com/8775395/198185583-73ed03a1-129e-4244-9316-7f1293d8428e.png)

**Comment by rivermont** [comment]
@tyrasd can this be closed? Should be a non-issue, sidebar can still be closed with the toggle or keybind.
