### ISSUE TITLE
Render name on waterway=* with tunnel=culvert

### ISSUE THREAD

**Issue by svenr3d** [openstreetmap/iD#9336]
### Description

When tagging a `waterway ` with `tunnel=yes` or `tunnel=culvert`, the name of the waterway is not rendered.

**Comment by tyrasd** [comment]
Hi. I cannot reproduce the issue, for me it works fine (see screenshot below).

![image](https://user-images.githubusercontent.com/1927298/196404767-14aee81f-a847-4383-aac9-404e9bc09911.png)

Which browser are you using? Can you point me to a location where you noticed this?
