### ISSUE TITLE
restriction:hgv=only_left_turn rendered incorrectly in turn restriction view

### ISSUE THREAD

**Issue by easbar** [openstreetmap/iD#9337]
### URL

https://www.openstreetmap.org/edit?relation=12417310#map=19/53.49531/9.91726

### How to reproduce the issue?

Take a look at this relation

![image](https://user-images.githubusercontent.com/17603532/196610478-c5e30418-edac-4bd8-9a0f-24768f3095fa.png)

It is an 'only_...' restriction, but it is shown as if it was a 'no_...' restriction:

![image](https://user-images.githubusercontent.com/17603532/196609401-67fa8bff-2777-4644-95c8-df468ea08b6b.png)

And when I change it from `restriction:hgv=only_left_turn` to `restriction=only_left_turn` it actually does look like this:

![image](https://user-images.githubusercontent.com/17603532/196609740-e1391ebd-a75d-47d1-be59-3f04c3e37cc5.png)

So it seems like the turn restriction panel works correctly for the `restriction=only_left_turn` tag, but not the `restriction:hgv=only_left_turn` tag?

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.22.0

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
This issue reproduces with any subkey of `restriction`, for example `restriction:bicycle=*`. The intersection editor only checks whether `restriction=*` begins with `only_`:

https://github.com/openstreetmap/iD/blob/1ee45ee1f03f0fe4d452012c65ac6ff7649e229f/modules/osm/intersection.js#L389

The fix would be to also run this same test over any value in `restriction.tags` whose key begins with `restriction:`. However, I’m unsure how the editor should treat a relation that’s tagged with both `restriction=no_` and `restriction:hgv=only_` or vice versa.

**Comment by easbar** [comment]
> I’m unsure how the editor should treat a relation that’s tagged with both restriction=no_ and restriction:hgv=only_ or vice versa.

Ok not sure about this either, but all I can say is that this is very rare. Actually I have been in the process of fixing this when I noticed this bug. There are some cases where both the restriction and restriction:hgv tag is present (like only a dozen cases for the entire planet and even less for other vehicles). But these are just tagging mistakes and in almost any case at least the value is the same. Something like `restriction=x,restriction:hgv=y` maybe does not exist at all.

But note that there is also `restriction:conditional` and combined usage of `restriction` and `restriction:conditional` happen rather frequently (around 540 cases for the planet file currently according to overpass-turbo).

**Comment by easbar** [comment]
Also considering this issue: https://github.com/openstreetmap/iD/issues/8670 maybe a first step would be making it easier to recognize that there are complex restrictions already present?

**Comment by 1ec5** [comment]
Also related: #6460.

**Comment by tyrasd** [comment]
Strictly speaking, iD never supported any vehicle-type dependent turn restrictions. The fact that these were still rendered (like a `no_*` restriction relation) was merely a bug caused by overly lax parsing. After 097c6bd, any restriction relation without a "supported valid" `restriction` tag (i.e. one starting with either `only_` or `no_`) is not rendered in the turn restriction editor 
anymore, which "kind of" fixes this bug.

Proper support for vehicle dependent turn restrictions would still be useful. Let's track that in #6460, though.

**Comment by 1ec5** [comment]
> However, I’m unsure how the editor should treat a relation that’s tagged with both `restriction=no_` and `restriction:hgv=only_` or vice versa.

Thanks to @easbar for following up [on the tagging list](https://lists.openstreetmap.org/pipermail/tagging/2022-October/066263.html).
