### ISSUE TITLE
geometry of features stores more digits than osm server - the rounding at the upload causes a shift of nodes

### ISSUE THREAD

**Issue by gbgoiny** [openstreetmap/iD#9338]
### Description

i found out about this in JOSM but i think its also relevant for ID because the same change of angles at ID-features downloaded from OSM Server occures.

when creating features in JOSM, the coordinates have 11 decimal places. but when i download features from OSM Server, they only have 7 decimal places. because of the rounding to 7 decimal places at the upload, there is a small shift for every node, depending on the amount of rounding. this also changes the angles of features, so that for example a building has no longer 90° angles.

i think that the same thing happens with ID features and i think this is the source of the problem, that for example sometimes in JOSM the extrude tool  has problems.
also, squaring tools like mapathoner plugin need to work with tolerances to exclude these small angle differences from 90° in their selection.

if it would be possible to reduce the decimal places in ID and JOSM to 7, the upload of features might not cause these small placement changes for every node due to the rounding.

**Comment by tyrasd** [comment]
I don't see how truncating the decimal places in the editor would solve the issue that angles of the (uploaded) features are not perfectly square after using the make-square operation. Thus, implementing your suggestion wouldn't actually solve the problem, and as far as I can see it is actually impossible to solve it, as any limited precision number will always eventually lead to rounding errors, which in turn cause small differences in measured properties such as angles. Tools just need to take these small deviations into account. There's just no way around that. :shrug:
