### ISSUE TITLE
Don´t remove building tags when adding amenity=school

### ISSUE THREAD

**Issue by Eifelkobold** [openstreetmap/iD#9341]
Hi, someone in my area fixed an note and added a new school. After that the building tag is missing. I saw that ID was used and tried to reproduce it with another building and checked the tags. Unfortunately the building-Tags were removed.

How to reproduce
1. Open ID and go to an building
2. Seklect the building an search in the sidebar for school
3. Select the preset and chosse it
5. building=* is removed

This also happened in the past with other objects in combination with buildings, for example restaurants. Maybe thats a bigger problem, because building tags should not removed when they are marked as an POI. The building remains there an does not magically disappear when it is used fully as an POI.

Greetings Eifelkobold

**Comment by Hufkratzer** [comment]
I agree, it's a bigger problem.
Related issues: https://github.com/openstreetmap/iD/issues/9104, https://github.com/openstreetmap/iD/issues/5883

**Comment by yvecai** [comment]
Would it also work when adding a 'highway' field to the ski (piste:type=) presets? From time to time highway=tracks are disappearing from the map this way.

**Comment by tyrasd** [comment]
@yvecai yes, that should work. Would you mind opening a new issue for this on https://github.com/openstreetmap/id-tagging-schema/issues, so that we can fix that in the presets accordingly?
