### ISSUE TITLE
Wrong phone number format for Ivory Coast

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#9352]
### How to reproduce the issue?

Open an OSM node in the Ivory Coast which represents a supermarket and does not have a phone number.

**Actual behavior:** In the dedicated field for phone numbers appears in gray: +225 20 12 34 56

**Expected behavior:** In the dedicated field for phone numbers appears in gray: +225 27 20 12 34 56

**Additional information**: +225 20 12 34 56 was the correct format in the past. However, [in the night from 30 to 31 of January 2021 Ivory Coast changed its number format from eight digits to ten digits: two additional digits had been introduced at the very beginning of all numbers.](https://fr.wikipedia.org/wiki/Liste_des_indicatifs_t%C3%A9l%C3%A9phoniques_en_C%C3%B4te_d%27Ivoire)

**Comment by arch0345** [comment]
This looks like a duplicate of #8379

**Comment by sommerluk** [comment]
Yep. Sorry, I just run into the problem and did not remember I had yet reported this previously. Closing this one as duplicate.
