### ISSUE TITLE
Validation: `barrier=jersey_barrier` line and point geometries

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#9362]
### URL

https://www.openstreetmap.org/edit?node=8285084738

### How to reproduce the issue?

Go to the provided link above, and see the yellow warning message at the issue area: _"Jersey Barrier should be a line, not a point"_

According to the `barrier=jersey_barrier` wiki:
https://wiki.openstreetmap.org/wiki/Tag:barrier=jersey_barrier
these objects can have line or point geometries.

Please remove the validation message,

### What version numbers does this issue effect?

current v2.22.0

**Comment by arch0345** [comment]
This was fixed in https://github.com/openstreetmap/id-tagging-schema/pull/614

**Comment by arch0345** [comment]
@sun-geo I'm not seeing this validation message anymore in v2.23.2

**Comment by sun-geo** [comment]
Thanks - closed
