### ISSUE TITLE
Select all nodes in a way

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9370]
In  https://community.openstreetmap.org/t/tag-nodes-and-way-at-same-time/5328 we see powerful uses of "select all nodes in a way" functionality. It would be great if that was possible in iD too.

**Comment by 1ec5** [comment]
This was implemented in #8264.

**Comment by jidanni** [comment]
Sounds good! What are the Linux key bindings?

**Comment by 1ec5** [comment]
If I’m not mistaken, it would be the same as on Windows by default: <kbd>Ctrl</kbd>+<kbd>DownArrow</kbd>. Also, <kbd>Ctrl</kbd>+<kbd>UpArrow</kbd> goes in the other direction, selecting any ways that the selected nodes are a part of.

**Comment by jidanni** [comment]
Indeed, there in the iD help panel:

> With way selected
> Ctrl+↓	Select child nodes

and it works great! Thanks.
