### ISSUE TITLE
Cannot change to Service Road if highway=service AND service=*

### ISSUE THREAD

**Issue by pardthemonster** [openstreetmap/iD#9372]
### How to reproduce the issue?

If a road is `highway=service` with `service=*`, example service=alley, changing to just a Service Road (`highway=service`) cannot be done with iD editor buttons, but only tag editing by removing `service=*`.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.23.1

### Which browsers are you seeing this problem on?

Safari

**Comment by 1ec5** [comment]
Probably related to 96bac0650b7a129cd2c138721f1728a5590834af.

**Comment by 1ec5** [comment]
Fixed in 21e54f956daa739a009be0dbd878e730562ce12f (there was a typo in the commit message).
