### ISSUE TITLE
Too long description value got pruned

### ISSUE THREAD

**Issue by sdicke** [openstreetmap/iD#9374]
### How to reproduce the issue?

1. Add a description field to an object.
2. Write text in the large textbox, which is longer than the 255 characters allowed by the API for a tag value.
3. Upload the changeset.

Result: In the resulting changeset there are just the first 255 characters of the typed text, the rest got pruned. The editor noticed the user not about the issue.

Expected result: The Editor should warn the user that the text is too long. It would be nice if there were an indicator of the remaining characters (at least when you typed already more then the allowed maximum). Additionally there should be a warning or an error indicated in the upload dialog to avoid information lost unintended by the user.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.23.2

### Which browsers are you seeing this problem on?

Firefox

**Comment by tordans** [comment]
Sounds like https://github.com/openstreetmap/iD/issues/7943, right?

**Comment by sdicke** [comment]
It sound similar, right.

**Comment by alanb43** [comment]
I know this is a duplicate, but I'm working on a small but simple change to help from a usability standpoint. I've read through the other related issues and have noted concerns regarding special characters / emojis. Let me know if there's anything I should do to be 'assigned' this, or if I'm not able to be please :)

**Comment by tordans** [comment]
> ... but I'm working on a small but simple change to help from a usability standpoint.

Did you see https://github.com/openstreetmap/iD/pull/9390? I guess efforts are best consolidated there (at this stage likely code review and edge case testing).

**Comment by alanb43** [comment]
I'm still going to submit a pull request for consideration, but will be reviewing that change too (mine is much smaller / to the point I feel)
