### ISSUE TITLE
Parking maxstay= uses abbreviations instead of full units

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap/iD#9387]
### URL

https://www.openstreetmap.org/way/1094557831/history

### How to reproduce the issue?

1. Create a street-side parking
2. Add field: _Max Stay_
3. Pick the "2 hr" option
4. Investigate the **Tags**

### Screenshot(s) or anything else?

`maxstay=` documentation on the wiki:
https://wiki.openstreetmap.org/wiki/Key:maxstay?uselang=en#Time_unit

> The unit should not be abbreviated

---

![image](https://user-images.githubusercontent.com/10835147/203878619-9136b1c6-d3f1-47d3-8606-4acbba9ab2d7.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.23.2

### Which browsers are you seeing this problem on?

Chrome

**Comment by 1ec5** [comment]
These incorrect values are currently hardcoded in a different repository, but it should be a quick fix:

https://github.com/openstreetmap/id-tagging-schema/blob/e1ab5130ce897d92710443f1803688c5d4009883/data/fields/maxstay.json#L9-L14

A longer-term fix for this issue would be to replace this freeform text field with one that lets you enter durations with a predetermined selection of units. This would have the benefit that non-English speakers would see words like “hour” and “minute” translated into their own languages. This would be easier if the schema for id-tagging-schema would support a general measurement field type: ideditor/schema-builder#15.

**Comment by Zaczero** [comment]
Now that the fix has been merged, I suppose we are just waiting for the next iD release.

**Comment by Zaczero** [comment]
![image](https://user-images.githubusercontent.com/10835147/204661411-b2ad54e0-fe74-48b1-acb5-b7afdda606a8.png)

Closing, fixed and deployed.
