### ISSUE TITLE
Alternative input strategies to avoid repetitive strain syndrome

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9395]
Let's say there is an office worker who, for 8 hours a day, has been assigned to digitize ways.

They're going up and down curvy sidewalks on the aerial imagery clicking ever so often with their right index finger.

Sure, you might say that there are computer programs that could do that for them. Well then okay, how about pipelines that you can't just see with your eyeballs or something.

Anyway there they are clicking all day long until one day they got to go to the hospital and their insurance might not cover it or something.

So here's the brilliant idea: let's say we right  click at the end of a way, and we see that we can append to the way. Well how about if there's  also an alternative way to append to the way as an additional choice:

Wherever they put their mouse for more than one second,  a  node on the way would be created. Until they put their mouse somewhere for 2 seconds...  then the node that's created would  be the last, and we exit that alternative input method!

Okay, does that mean we must first create ways, and then we are able to find the choice  to start this wonderful method in the right click menu? Well I'm sure there's better ways to start it right from the start.

**Comment by bryceco** [comment]
Back when I was having issues with RSI I used a system-wide utility that did exactly what you describe. Here’s an example: https://download.cnet.com/RSI-AutoClick/3000-2084_4-75929608.html

I think your hypothetical worker should use a solution like that rather than modifying iD.

Edit: P.S. Also buy an ergonomic mouse and use a stylus on your phone.

**Comment by 1ec5** [comment]
It isn’t a full solution to your problem, but in case you’re unaware, you can also strike the spacebar as an alternative to clicking while drawing. Sometimes when I’m drawing something particularly tedious, I’ll position multiple fingers over the spacebar and strike it like an arpeggio on a piano keyboard. The swipe-to-pan behavior is also intended to minimize RSI, though it’s currently broken in some browsers: #8649.

**Comment by jidanni** [comment]
Well that's all great news.
As far as add-ons, well, the help manual perhaps at Lines->Adding Lines should mention add-ons are available (for at least Windows) for those "sentenced" to vector entry. Else they will never know.
