### ISSUE TITLE
Destination field gets converted to lowercase

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9396]
### URL

https://www.openstreetmap.org/edit#map=17/42.53782/26.41959

### How to reproduce the issue?

1. Select a `motorway_link`
2. Enter anything in the destination field with at least one capital letter
3. Press Enter

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/19364673/205072437-350fc6be-ef3e-4510-81a6-9c82e736ddc5.png)
![image](https://user-images.githubusercontent.com/19364673/205072480-84da9514-e0af-4199-98be-fe812b3b0cf7.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.23.2

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
I think openstreetmap/id-tagging-schema@bd476266d0327ab94a60bdea2ac57e5b64e59169 should fix this, but I’m not sure if it’s been deployed yet.

**Comment by Dimitar5555** [comment]
Is it possible to test it somehow before it's deployed?

**Comment by tyrasd** [comment]
This fix was released with [v5.1.0](https://github.com/openstreetmap/id-tagging-schema/releases/tag/v5.1.0) 3 days ago (November 29). Your browsers caches the presets data for up to a week, though. You can test it by clearing your browser's cache and reloading iD.
