### ISSUE TITLE
Select all areas?

### ISSUE THREAD

**Issue by EvanCarroll** [openstreetmap/iD#9410]
### Description

Frequently I want to select all areas visible and change their _type_ while this can be a dangerous operation, sometimes, it's frequently very useful. For example, in a suburb.

Let's assume I add all these houses with RapId, there is no way to easily change them to "Detached Houses" which is far more correct than buildings. Even though I can tell with 100% certainty they're all detached houses in this new master-planned neighborhood.

![Screenshot_2022-12-06_17-53-05](https://user-images.githubusercontent.com/19922/206051138-4b221fc3-09df-4ad2-adfb-7cfef2b2165b.png)

I think these kinds of features would be very useful even if hidden behind a feature flag and reserved for just some.

Better than select all ways, which would work for me would be to be able to query the viewing window... Maybe even an overpass turbo query executor?

```
way["building":"yes"]({{bbox}});
```

**Comment by 1ec5** [comment]
(RapiD is developed in [a different repository](https://github.com/facebook/RapiD/), so this response may not apply to the candidate features specifically.)

In iD, you can hold down Shift and drag a lasso around the nodes you want to select. To select the ways that those nodes are a part of, press <kbd>Ctrl</kbd><kbd>↑</kbd> (⌘↑ on a Mac). Then you can change the tags of all the selected ways simultaneously, including changing the preset to something else.

**Comment by EvanCarroll** [comment]
This isn't just a problem in RapiD. I add to the problem in RapiD, but I can't resolve it in iD either. I didn't know about <kbd>Ctrl</kbd>+<kbd>Up</kbd>, but it seems <kbd>Ctrl</kbd>+<kbd>Up</kbd> selects ways too, not just areas. It would be nice if there was a way to differentiate. I don't want to alter driveways, sidewalks, and roads.

**Comment by 1ec5** [comment]
Before selecting anything, open the Map Features panel on the right and disable all the feature categories except for Buildings.

**Comment by EvanCarroll** [comment]
Thanks @1ec5 ! Nice tricks. That'll get done everything I want!

**Comment by EvanCarroll** [comment]
@1ec5 When I do this trick, even if hiding the non-buildings if they're attached to the buildings they show up after I do <kbd>Ctrl</kbd>+<kbd>Up</kbd>. Is this a bug? Is there a way around this behavior so I only get the buildings after doing <kbd>Ctrl</kbd>+<kbd>Up</kbd>.

https://user-images.githubusercontent.com/19922/206058632-35c27c08-a298-45d4-89be-b017b6d12035.mp4

**Comment by 1ec5** [comment]
I suppose it could make sense for the select-parent-ways operation to ignore hidden ways. On the other hand, there are already situations where a normally hidden feature becomes temporarily unhidden when selecting it; I’m not sure what the best behavior would be when selecting its parent ways: do nothing, or show those ways too. If you think the behavior should change for this operation, let’s track that in a separate issue to keep things clear.

In any event, when an unwanted feature winds up selected, you can modify the selection by clicking the ✖️ button next to individual features at the top of the left sidebar, or by shift-clicking the feature on the map.
