### ISSUE TITLE
Enhancement: Add the key A as shortcut to start drawing an Area.

### ISSUE THREAD

**Issue by sekerob** [openstreetmap/iD#9430]
### Description

Flip-flopping back and forth between JOSM and ID Editor, each having their pros and cons, I find the key 'a' as  keyboard shortcut to start drawing an area is greatly missing in ID.

Alternate, to reduce lots of mousing mileage, an addition to the right click pop-up menu with an A for _Area_ drawing commencement and L for _Line_, P for _Point_ would be a great addition. As the eye is already focused on the mouse pointer, no need to look up to screen top to find where those buttons are near top of screen.

**Comment by 1ec5** [comment]
Just in case you’re unaware, the <kbd>1</kbd> key draws a point, <kbd>2</kbd> starts drawing a line, and <kbd>3</kbd> starts drawing an area. Press <kbd>?</kbd> to view a full list of keyboard shortcuts.

**Comment by sekerob** [comment]
Ah, greatly appreciate those hints, particular the ? key. Have pinned tabs at moment to the keyboard shortcut cheat sheet  https://wiki.openstreetmap.org/w/images/9/99/JOSM_Keyboard_shortcuts_cheat_sheet.png

Did discover many shortcut keys when moving area/relation mapping to JOSM are mimicked in ID, or vice versa if you will, Think it would not harm to add more functional mirroring,

**Comment by tyrasd** [comment]
The `A` key is already used for a different shortcut in iD: It is used to **a**ppend (i.e. **a**dd further nodes to) an existing ways.

>  it would not harm to add more functional mirroring,

in general I agree, but here I'd rather avoid the double functionality on a single shortcut

**Comment by sekerob** [comment]
I failed to mention that in the OP, that in JOSM if one has selected the last node of a line (either end), and hits the A key, it in effect continues the drawing of that line i.e. appends. Need to remember that ID shortcut function.

cheers
