### ISSUE TITLE
razed:waterway=stream should not be expected as an area

### ISSUE THREAD

**Issue by Langlaeufer** [openstreetmap/iD#9436]
**Describe the bug**
warning tells that razed:waterway=stream should be an area
In most cases waterway:stream are lines: (17 M line / 41 k area features)

**To Reproduce**
[Steps to reproduce the behavior:
1.got to way https://www.openstreetmap.org/way/1109163077)
remove area=no

**Expected behavior**
no warning for this feature

**Comment by tyrasd** [comment]
This is most likely a bug in iD itself, and not caused by the tagging presets. I'll move the issue to the other repository.

**Comment by biswajit-k** [comment]
It is working fine now. I guess it is fixed.

**Comment by tyrasd** [comment]
I do still have the issue here. :thinking:

**Comment by biswajit-k** [comment]
Ops! I reported it wrongly. However, I looked into the issue and I guess I have found the bug and raised a PR above, please let me know if anything is wrong.

PS: Thanks @tyrasd! Your tip to use debugger actually helped a lot. 😊
