### ISSUE TITLE
Destinations get converted to lowercase

### ISSUE THREAD

**Issue by mdykierek** [openstreetmap/iD#9440]
### How to reproduce the issue?

1. Put a name in the Destinations field for example in Trunk link.
2. The name gets converted to all lower case which for proper names (which cities are) is plain wrong.
One has to go to tags and fix it there.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.23.2

### Which browsers are you seeing this problem on?

Chrome, Firefox

**Comment by 1ec5** [comment]
Looks like openstreetmap/id-tagging-schema@bd476266d0327ab94a60bdea2ac57e5b64e59169 made the main Destinations field case-sensitive but not [the one that appears in link road presets](https://github.com/openstreetmap/id-tagging-schema/blob/bcc07f24b2a5901ba60323f7d8ef189efd84346d/data/fields/destination_oneway.json) when `oneway=yes` is present.

/ref openstreetmap/id-tagging-schema#515

**Comment by WizoneDE** [comment]
anything new about a fix date?
