### ISSUE TITLE
`planned:man_made=pipeline` should not be an area

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9447]
### URL

https://www.openstreetmap.org/edit?way=1057595981#map=17/42.91492/22.92276

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/19364673/210243175-d4645faa-a2ae-4569-8978-ad06f578d107.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.23.2

### Which browsers are you seeing this problem on?

Firefox

**Comment by k-yle** [comment]
this was fixed in #9483 but it hasn't been merged yet

**Comment by 1ec5** [comment]
Fixed in #9483.
