### ISSUE TITLE
Fire extinguisher icon is rendered with `colour` unlike other POIs

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9448]
https://www.openstreetmap.org/node/10089768614/history
is shown in red. noteably, it has the tag `colour=red`.

- When the colour is changed/removed, nothing changes (I have not saved these changes, so can't check the aftermath)
- Other fire extinguisher **without `colour`** renders fine. https://www.openstreetmap.org/node/9915072688/history
- A newly added fire extinguisher, also with colour=red, will be rendered in black. (I have not saved said non-existent fire extinguisher, so same as above.)

This rendering seems to be inconsistent with any other POIs and makes it appear as if there is an issue with this object.

![image](https://user-images.githubusercontent.com/67521919/210258697-8e42004c-9a3a-4a2d-8e2a-b37f9d816b70.png)

**Comment by k-yle** [comment]
It's caused by the tag `location=... red ...`, probably because `location=underground` gets special treatment.

you can mess with iD by tagging a feature with `location=... selected ...` or any other special class name

**Comment by Gua00va** [comment]
Hey!! Is this issue still open? I would like to work on it.

**Comment by k-yle** [comment]
Hi @Gua00va, yes this issue is still open. You're welcome to work on any issue, you don't need to wait for someone to assign the issue to you
