### ISSUE TITLE
Blue bar appears on input field for one plaque

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9479]
### How to reproduce the issue?

A blue bar, resembling a scroll bar -it does not move when scrolling or on interaction-, appears when entering the input field for the inscription [of this plaque](https://www.openstreetmap.org/node/10579712128). It does not seem to appear on other plaques (I've checked ones with long descriptions as well as short descriptions).

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/67521919/215351624-2c6afbbb-fd6e-4614-a91e-6172cd94472c.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.24.1

### Which browsers are you seeing this problem on?

Chrome (outdated version)

**Comment by 1ec5** [comment]
This is a new feature telling you how many characters you have left before hitting the API limit on value lengths: #9390. I can see how it might look like a rendering glitch, when it underlaps the button separators in the button bar above the text field.

**Comment by danieldegroot2** [comment]
Closing in favour of discussion on #7943.
