### ISSUE TITLE
Disconnected road warning still showing after connecting other road with that road

### ISSUE THREAD

**Issue by xnousnow** [openstreetmap/iD#9485]
### How to reproduce the issue?

1. Go anywhere.
2. Create a disconnected road. and the warning will be shown.
3. Create a connected road but disconnected from the road (in step 2).
4. Move the path from the road (in step 3) to the road (in step 2).
5. The warning in step 2 is still shown on the road (in step 2).

More direct ASCII art:
1:
```
+---------------+
|  o            |
|   \\          |
|    \\         |
|     o         |
+---------------+
```
2:
```
+---------------+
|  o        o   |
|   \\     /    |
|    \\ o-o     |
|     o         |
+---------------+
```
3:
```
+---------------+
|  o        o   |
|   \\     /    |
|    o----o     |
|     o         |
+---------------+
```
4:
```
+---------------+
|  o        o   |
|   \\     /    |
|    o----o     |
|     o         \
|     /\         \
|     ||          \-------+
| the warning still shows |
+-------------------------+
```

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.24.1

### Which browsers are you seeing this problem on?

Chrome, Firefox, Microsoft Edge, Opera, Safari, Vivaldi

**Comment by DujaOSM** [comment]
Duplicate of #8900.

**Comment by xnousnow** [comment]
#8900 is same issue.
