### ISSUE TITLE
Warning given about linear disused:aeroway=runway 

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#9491]
### URL

https://master.apis.dev.openstreetmap.org/changeset/253299

### How to reproduce the issue?

Using taginfo, note that disused:aeroway=runway is used both on linear and area objects:
13 closed in Lincs
https://overpass-turbo.eu/s/1r3F
19 open in Lincs
https://overpass-turbo.eu/s/1r3G

In iD, add an "aeroway=runway"
Save
Note no warning
Changed to "disused:aeroway=runway"
Save
Warning given incorrectly saying it should be an area feature.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.24.1

### Which browsers are you seeing this problem on?

Firefox

**Comment by k-yle** [comment]
this was fixed in #9483 but it hasn't been merged yet

**Comment by 1ec5** [comment]
Fixed in #9483.
