### ISSUE TITLE
HTML tags not rendered in error message

### ISSUE THREAD

**Issue by rbovard** [openstreetmap/iD#9494]
### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/4549666/217254293-429235cd-a2c3-4da7-aed7-87f2f4429333.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

**Comment by arch0345** [comment]
Duplicate of #3366/#8127

**Comment by rbovard** [comment]
Oops, sorry for the noise.
