### ISSUE TITLE
Cannot enter exact commons value

### ISSUE THREAD

**Issue by ivanbranco** [openstreetmap/iD#9506]
### How to reproduce the issue?

I wanted to add this image: https://commons.wikimedia.org/wiki/File:Theodor-K%C3%B6rner-Stra%C3%9Fe_4;_3.jpg
as a wikimedia_commons=* value, using the syntax as wiki. The syntax would be wikimedia_commons=File:Theodor-Körner-Straße 4; 3.jpg 
but iD automatically edit it as File:Theodor-Körner-Straße 4;3.jpg deleting the space before the last "3" therefore linking to a non existent image.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.24.2

### Which browsers are you seeing this problem on?

Chrome

**Comment by Dimitar5555** [comment]
The semicolon is used as a separator for most tag values. Even if it didn't remove the space, no software would recognise it as a single image. You have to change the name of the file so that there is no semicolon in it.

**Comment by ivanbranco** [comment]
makes sense, I asked a rename request (the image isn't mine), thx
