### ISSUE TITLE
Post Box Update, NSI not following the update

### ISSUE THREAD

**Issue by UKChris-osm** [openstreetmap/iD#9524]
With the merging of [id-tagging-schema#804](https://github.com/openstreetmap/id-tagging-schema/pull/804) I see the updated tagging options for UK Post Box's is now live. However, it seems when applying an NSI preset ([Royal Mail](https://nsi.guide/index.html?t=operators&k=amenity&v=post_box&tt=royal%20mail#royalmail-f65bfd)) the new tags are not available, and are removed from the field section if the NSI preset is applied after the initial post box is placed on a map (though the tagging remains).

Is this just a case of certain files haven't filtered down into the latest release, or is there something within iD / NSI that's causing a conflict?

![post-box-osm-id](https://user-images.githubusercontent.com/59393694/222896498-d7fd3561-3dd2-4c2b-ba26-265dd59a9e46.png)
![post-box-osm-nsi](https://user-images.githubusercontent.com/59393694/222896503-c18377f0-b2e8-4b33-988d-ddfa19d433ca.png)

@bhousel @tyrasd

**Comment by 1ec5** [comment]
openstreetmap/id-tagging-schema#804 implemented an alternative preset keyed to `amenity=post_box`, but apparently the preset matching code found the original `amenity=post_box` preset instead. Not sure how best to distinguish the two presets – maybe it could prefer the preset whose `locationSet` matches the NSI entry?
