### ISSUE TITLE
iD recommends adding barrier=kerb to kerb=* where there isn't a barrier

### ISSUE THREAD

**Issue by osmuser63783** [openstreetmap/iD#9533]
### URL

https://www.openstreetmap.org/edit?node=9623109621#map=19/52.53948/13.44384

### Background
When **barrier=kerb** is used on a node that is part of a highway, it marks the exact location where someone travelling along the highway has to cross a kerb. There is agreement that it shouldn’t be used anywhere else. For example, a barrier=kerb on a highway=crossing is most likely wrong as it implies that someone travelling along either of the two highways has to cross the kerb.

**kerb=*** seems to be used for two purposes on nodes. 

(1) At the actual location of the kerb, for example where a footway or a service road crosses the kerb. This is the same as  how barrier=kerb is used on nodes. It is sometimes but not always accompanied by barrier=kerb. When one encounters such a case and it doesn't have barrier=kerb, it is appropriate to add barrier=kerb. The kerb= tag effectively becomes a subtag of barrier=kerb that indicates the type of kerb.
(2) On a node other than a barrier=kerb, for example on a highway=crossing, or a public transport stop. In this use it is more like an additional tag, like tactile_paving = yes. It indicates that there is a kerb somewhere near this node that someone visiting the node might want to know about, but the kerb is not necessarily at the exact location of the node and this tagging therefore does *not* imply a barrier=kerb on all the ways that this node might be part of.

Importantly, usage (2) also occurs on its own, on a node with no other tags. Whatever one may think about this usage, it is [fairly common](https://overpass-turbo.eu/s/1rTZ). A lot of nodes tagged this way are the result of StreetComplete asking "Are there kerbs where this way meets this road here? What kind?" When the user answers "high kerb", StreetComplete adds kerb=raised, but they don't want to add highway=crossing, because it's unclear if it's actually possible (legally or practically) for the user of the footway to cross the road there.

### The bug

Whenever kerb=* appears alone on a node, iD tells the user that it has "incomplete tags" and suggests "upgrading" the tags by adding barrier=kerb to the node at the click of a button. To reproduce the issue, find any "lonely kerb" that is part of a road ([Overpass query](https://overpass-turbo.eu/s/1rTZ)) and open it in iD. Most likely, someone travelling along the road does not have to cross the kerb, so adding barrier=kerb would be wrong.

Adding barrier=kerb to such nodes has already resulted in [quite a few nodes](https://overpass-turbo.eu/s/1rU0) that are probably mistagged.

I think iD needs to include some logic to guess whether adding barrier=kerb to a "lonely kerb" is likely to be appropriate (e.g. where only one way is involved; or at the end of a road, where a footway begins) or not (e.g. anywhere on a road).

See also [this discussion](https://community.openstreetmap.org/t/tagging-kerbs-on-crossings/9290) in the Community forum, and see previous similar issues #6440 (about adding barrier=kerb to highway=crossing) and #6742 (about adding barrier=kerb to public_transport=platform).

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.25.1

**Comment by Famlam** [comment]
Spotted it a couple of times too, where there are now barriers on cycleways and 'car ways'. For example:
https://www.openstreetmap.org/changeset/133512675

**Comment by osmuser63783** [comment]
Thanks. This issue has led to quite a bit of discussion, because it leads to routing problems for routers (such as OSRM) that (correctly) avoid nodes with`barrier=kerb`. See the [examples](https://community.openstreetmap.org/t/barrier-kerb-kann-zu-routing-problemen-fuhren-osrm/97348) here.

**Comment by Nadyita** [comment]
I would like to see this behaviour changed as well. StreetComplete deliberately adding kerbs without barrier and iD suggesting to add a barrier-tag is slowly destroying routing in several areas.

**Comment by matkoniecz** [comment]
now also in https://community.openstreetmap.org/t/tagging-kerbs-on-crossings/9290/16

**Comment by osmuser63783** [comment]
Now also in https://github.com/openstreetmap/id-tagging-schema/issues/858

I initially thought iD could include some logic to guess whether or not adding `barrier=kerb` is likely to be appropriate, but a much simpler solution would be stop adding `barrier=kerb` to `kerb=raised` altogether.

**Comment by tyrasd** [comment]
closing here as indeed, https://github.com/openstreetmap/id-tagging-schema/issues/858 will be fixed with https://github.com/openstreetmap/id-tagging-schema/pull/862 and thus no special logic be required in iD to handle this.
