### ISSUE TITLE
"Objects for routing are only connected to themselves"

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9554]
### How to reproduce the issue?

1. Draw a line that's not connected to anything
2. Apply the footway preset to it
3. Draw another line that starts from the first line and ends in a road/another path
4. Apply the footway preset to the second path
5. Select the first footway (note the warning on it)

In order to force revalidation of that way, the user needs to move any of it's nodes.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/19364673/226168046-8c87415f-0b5b-48f0-9aeb-50b4d0e6a08e.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.25.1

### Which browsers are you seeing this problem on?

Firefox

**Comment by arch0345** [comment]
See also:
* #8758
* #8900
* #8981

**Comment by Dimitar5555** [comment]
Sorry for the duplicate, closing it since #8900 describes the same issues.
