### ISSUE TITLE
Be sure to have a store number or ref field when mapping convenience stores

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9605]
### Description

https://wiki.openstreetmap.org/wiki/Talk:Tag:shop%3Dconvenience#store_number_or_ref

**Comment by Marc-marc-marc** [comment]
because there could be 2 shops with the same name in the same building, what would you like to do? make it mandatory to add a ref that doesn't exist for the majority of shop=convenience ?

**Comment by pnorman** [comment]
It's not clear what you're asking here. Many stores don't have a store number or ref, so it wouldn't be possible to require it. Even for stores that have it, it's not always known when mapping. I don't know ref numbers for any local convivence stores, even when they have them.

**Comment by jidanni** [comment]
It's right there, on the receipt you get.

Also on the convenience store's website, that's one of the items in each store's profile.

**Comment by Marc-marc-marc** [comment]
if it's a rule that applies to all the conveniences stores in your country, it's not impossible to create a preset for your country.

But it's not a global rules : In Belgium, France, Switzerland and Luxembourg, there is no shop reference number on the ticket.
sometimes the vat (tax) number isn't even on the ticket, sometimes there isn't even the name of the shop on the ticker for the smallest of them.

**Comment by jidanni** [comment]
OK, but the chain's website's store locator search page results will have the store number.
That is needed when sending packages from store 1234 to 4567, or ordering items for store pickup.

**Comment by pnorman** [comment]
Not all convenience stores are part of chains. People map them without purchasing from the store. Not all receipts have store numbers on them.

**Comment by 1ec5** [comment]
(And not all stores have websites.)

**Comment by jidanni** [comment]
I'm just saying, to remind users to that they can fill it in, if it is available. 

Otherwise, it's like how many toilet brushes there are in the bathroom. Users wouldn't remember to fill it in.

**Comment by nickrsan** [comment]
Hi there - requests for changes to presets and available fields should be sent to https://github.com/openstreetmap/id-tagging-schema/ - I'm going to close this request here since it's not actionable in this repository. Feel free to recreate the request there if you like and link to the discussion here along with as many details on what you want to appear and the use case for it.
