### ISSUE TITLE
Distinguish iD entries in chrome://history/ 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9617]
### Description

Just the other day I was looking in e.g., chrome://history/ 
and well, it would be nice to be able to tell which entries are _definitely_ from iD without needing to hover the mouse upon each and every one!

### Screenshots

![20230501T074418](https://user-images.githubusercontent.com/1230959/235381609-140ffae1-5203-4cc2-97c7-3933bbc35857.jpg)

**Comment by 1ec5** [comment]
Duplicate of #8202.
