### ISSUE TITLE
Imagery Offset Database support

### ISSUE THREAD

**Issue by mglsj** [openstreetmap/iD#9663]
### Description

Please add support for imagery offset database. https://wiki.openstreetmap.org/wiki/Imagery_Offset_Database

**Comment by riQQ** [comment]
Related to #4764

**Comment by tsmock** [comment]
Also related: #1124

**Comment by nickrsan** [comment]
Going to close this as a duplicate of #4764, which is still open - but also thank you to both of you for the context. At one point, work was started on this in #4166, but it went stale and it looks like this is still unplanned right now.
