### ISSUE TITLE
Indonesia address format

### ISSUE THREAD

**Issue by TagaSanPedroAko** [openstreetmap/iD#9684]
### Description

Add address format for Indonesia, which is as follows:

**unit, house name, street, house number, neighbourhood, subdistrict, district, 
city, province, postal code**

example address (in Indonesian):

**Jalan Surya [No.] 10, RT.05/RW.02, 
Cempaka Putih, Cempaka Baru
Jakarta Pusat 10640**

neighbourhood in this case can either be _rukun tetangga/rukun warga_ (RT/RW: community unit/neighborhood unit, the subdivisions of urban subdistricts or _kelurahan_), hamlet (_dusun_), housing complex, private commercial developments or industrial parks, and tagged as addr:neighbourhood. subdistrict can refer to _kelurahan_ in urban areas or villages (_desa_) in rural areas, and tagged as addr:subdistrict. district will refer to _kecamatan_, and tagged as addr:district. city will refer to both cities (_kota_) and regencies (_kabupaten_). province is not generally used in Indonesian addresses, but added here in cases where they are used.

**Comment by tyrasd** [comment]
Thank you for the detailed explanation. One suggestion: It would probably be nice to add this information also on the osm wiki page about [country specific address tagging](https://wiki.openstreetmap.org/wiki/Addresses#Country_specific_rules_and_sources). :blush:
