### ISSUE TITLE
Tab navigation skips most background layers

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9686]
### How to reproduce the issue?

Use (keyboard TAB key, on the left side of your keyboard) to navigate around the Background menu.

At first TAB press we see:
![20230602T170154](https://github.com/openstreetmap/iD/assets/1230959/a1232f44-a2c7-4b52-9b82-53a219087a4f)

The next jumps to here:
![20230602T170218](https://github.com/openstreetmap/iD/assets/1230959/1922422e-38f1-4087-9cc7-30edb92d0dc4)

And the next:

![20230602T170248](https://github.com/openstreetmap/iD/assets/1230959/096636c3-101f-47cd-a991-5ab11ebb4772)

So all the other background layer choices get skipped over, inaccessible via Tab navigation!

Further down the background layer menu every checkbox is accessible.

It is only the section I have mentioned above that has the bug.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by k-yle** [comment]
it's a bit unintuitive, but it seems like it's working as intended[^1] - once you've focussed on the list of layers using <kbd>↹ Tab</kbd>, you then need to use the <kbd>⬆️ Up</kbd> and <kbd>⬇️ Down</kbd> keys. 

I agree though, it would be nicer if you could <kbd>↹ Tab</kbd> through the list...

[^1]: https://www.w3.org/wiki/RadioButton

**Comment by jidanni** [comment]
I see. Different than checkboxes.
