### ISSUE TITLE
Ban some (copyrighted) custom background

### ISSUE THREAD

**Issue by zbycz** [openstreetmap/iD#9708]
### Description

We have this issue in czech community: some begginers are using copyrighted custom background when editing OSM. 

In the whole database, there is around [11000 edits so far](https://osmcha.org/?aoi=0c8c392a-2104-4382-a8ed-7bed8745975c). Of course members of community are educating those users and reverting the changes, but we would like to ask, if it could be somehow banned in iD itself. It is becoming a little tedious :-)

- Proposed change: when custom background hostname contains "mapy.cz", warn the user and disable the Save button.

.

Here is our thread in czech: https://openstreetmap.cz/talkcz/c3793 ([translator](https://openstreetmap-cz.translate.goog/talkcz/c3793?_x_tr_sl=cs&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp))

**Comment by 1ec5** [comment]
iD has a validation rule for warning about the use of some common copyrighted sources. mapy.cz can be added to this object:

https://github.com/openstreetmap/iD/blob/446133d1a468611cd374cdfa95ab080217c85db0/modules/validations/incompatible_source.js#L8-L22

**Comment by pnorman** [comment]
> iD has a validation rule for warning about the use of some common copyrighted sources. mapy.cz can be added to this object:

Aren't these rules about source tags, while this issue is about imagery URLs? Blocked imagery URLs are set by the editing API in the /capabilities response, which are set at https://github.com/openstreetmap/openstreetmap-website/blob/0e00857d51f2890071698b8ac9e699ce444aa3a3/config/settings.yml#L85

**Comment by tyrasd** [comment]
@pnorman is right: The proper place to add this restriction is at the imagery policy of the OSM API. Please open a ticket for that on the [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website/issues/new/choose).

**Comment by Jakuje** [comment]
Filled openstreetmap/openstreetmap-website#4085 for this.

**Comment by tyrasd** [comment]
perfect. :+1:

Just a small nit-pick: 

> they do not have a way to fix it on their side

this is not quite right… we could fix it on iD's side, but it just doesn't make sense: it's much better to do this using the existing [functionality of the OSM API](https://wiki.openstreetmap.org/wiki/API_v0.6#Capabilities:_GET_/api/capabilities), as it will then have an effect in all (properly implemented) OSM editors, not just in iD. :blush:
