### ISSUE TITLE
Remove Maxar Imagery

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9710]
### How to reproduce the issue?

Maxar imagery is now only useful for mapping outlines of continents.
Any closer and it is just a blur, worldwide.
So if it cannot be fixed, might as well remove it.
It has seen better days, https://github.com/openstreetmap/iD/issues/7787 .

**Comment by jidanni** [comment]
https://github.com/osmlab/editor-layer-index/issues/1951

**Comment by JackW6809** [comment]
This only happens when OSM's token for Maxar expires, they are usually pretty quick to release an update to rotate the token, so no point removing it. Though it seems they are taking their time to rotate the token this time.

**Comment by danieldegroot2** [comment]
Part of https://github.com/osmlab/editor-layer-index/issues/1889 .

**Comment by nickrsan** [comment]
More information on what's going on is available here: https://community.openstreetmap.org/t/maxar-imagery-not-working-was-maxar-is-blurred-in-id-and-other-similar-topics/100524/28

Removal may make sense (Maxar says this is "permanent"), but probably worth keeping as a temporary removal on iD's end.

**Comment by tyrasd** [comment]
Sadly, our attempts to restore the service have not been successful yet. There is still an ongoing joint effort of the OSMF and HOT on this, but from what I can tell it's probably not going to be a quick process, unfortunately. :unamused:  I have, for now, removed the Maxar Premium layer from the background selection list.
