### ISSUE TITLE
The "Point Tutorial" gets stuck when searching for "Café"

### ISSUE THREAD

**Issue by motla** [openstreetmap/iD#9712]
### How to reproduce the issue?

1. Launch ID
2. Get to the help icon
3. Launch the guide
4. Select the Points tutorial
5. Add the point on a road
6. When the tutorial says to type Café in the search bar, it gets stuck when we type Café

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/16179413/7dd1d792-9968-4267-b2d8-1c62b6978b32)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.25.2

### Which browsers are you seeing this problem on?

Chrome

**Comment by motla** [comment]
Okay I found the issue, it is because I added the point on the road instead of clicking inside a building.

So it's a duplicate of #9439 

You should tell the user that the point is set at the wrong place before launching the search box, otherwise the tutorial gets stuck as it never finds the result for "Café".

**Comment by nickrsan** [comment]
Hi there - thanks for reporting this and noting that it's a duplicate. I'm going to close this one as a duplicate but leave #9439 open.
