### ISSUE TITLE
Error adding bus stopping location to vertex

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#9719]
### How to reproduce the issue?

1. Select a node along a line or area (regardless of the way’s tags).
2. Choose the [Bus Stopping Location](https://github.com/openstreetmap/id-tagging-schema/blob/8b53e8ff39a4bdcc39862a3c088ab077c3470c4b/data/presets/public_transport/stop_position_bus.json) preset.

Nothing happens.

### Screenshot(s) or anything else?

The following error appears in the console:

```
Uncaught TypeError: S is undefined
    g preset.js:315
    moreFields preset.js:46
    Y1 change_preset.js:19
    choose preset_list.js:427
    p history.js:45
    g history.js:63
    perform history.js:168
    m context.js:273
    choose preset_list.js:422
    AL on.js:3
3 preset.js:315:14
```

https://github.com/openstreetmap/iD/blob/b1121b11753cfe8919e5665df315060d2ec04139/modules/actions/change_preset.js#L19 https://github.com/openstreetmap/iD/blob/b1121b11753cfe8919e5665df315060d2ec04139/modules/presets/preset.js#L315

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.26.0-dev

### Which browsers are you seeing this problem on?

Firefox

**Comment by Deeptanshu-sankhwar** [comment]
Hello @1ec5 , thanks for sharing the issue. I have been trying to reproduce it by trying to select a node along a line and changing its preset to `Bus Stopping Location`, but unfortunately I am not able to encounter any bug on console. Could you please verify if I am doing something wrong here?

![ScreenRecording2024-12-04at5 06 44PM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/03e09edb-48fd-4c69-949c-7e50a2c32587)

**Comment by 1ec5** [comment]
I’m no longer able to reproduce the issue either. (This time, I was using Firefox 134.0b3 and looking at a location around 39.28228°N, 84.28452°W.) Given the age of the bug report, we can close this one as not reproducible and reopen it if it ever comes up again.
