### ISSUE TITLE
Error adding ticket sales preset to object

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9724]
### How to reproduce the issue?

On the dev environment, this seems to have been resolved or does not seem to be an issue. I could not directly find the related change. If it exists, this issue can simply be linked to said change and be closed.

1. add a building (e.g. `building=yes`)
2. add the "ticket sales" preset.
3. throws some empty warnings with errors in the console and then blocks further interaction (mainly reselecting the object after canceling out.)
4. undo(, then go into and cancel out of the save menu) to regain the ability to interact with the object. (switching tabs shortly may also help if the undo/save button can't be interacted with)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'en')
    at r.languageName (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:4:23922)
    at validationIssue.message (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:10:25116)
    at HTMLSpanElement.<anonymous> (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:26:23533)
    at Selection.each_default [as each] (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2:19012)
    at o (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:26:23506)
    at Selection.call_default [as call] (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2:18558)
    at a (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:26:22621)
    at Selection.call_default [as call] (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2:18558)
    at l (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:19:4312)
    at Selection.call_default [as call] (id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2:18558)
r.languageName @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:4
message @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:10
(anonymous) @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:26
each_default @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2
o @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:26
call_default @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2
a @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:26
call_default @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2
l @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:19
call_default @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2
n @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:19
call_default @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2
reRender @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:19
(anonymous) @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:26
requestIdleCallback (async)
(anonymous) @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:26
call @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:38
(anonymous) @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:11
Promise.then (async)
d.validate @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:11
n.choose @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:23
(anonymous) @ id-072ff9dbedfd7c677e735e44abb42e92be82b1a975cc4d5b550daaf556f909e4.js:2
```

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/67521919/9ff7687d-2be3-4f00-9886-26fd86b4e25f)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.25.2

### Which browsers are you seeing this problem on?

Chrome

**Comment by nickrsan** [comment]
Did a quick attempt to reproduce in a different environment (thanks for including the steps) and I wasn't able to - I don't get any problems in Firefox 114.0.2 on Windows 10 with an en-US locale. I wonder if any of the three of those prevent it. I'll try in Chrome soon on the same machine to better match your situation. In the en-US locale, the ticket sales preset I added was Ticketseller (resulted in tag of `shop=ticket`)

In the meantime, can you answer a few clarifying questions for me?
1. How are you initially adding the building tag? Are you using the building preset on a new area? Or setting the `area=yes` preset then adding the `building=yes` tag. 
2. What version of Chrome are you running?
3. What OS are you running?

Thank you!

**Comment by danieldegroot2** [comment]
> setting the area=yes preset then adding the building=yes tag.

1. Drawing an area, then adding the `building=yes` Building preset and finally adding the `shop=ticket` Ticketseller preset.

> version of Chrome

2./3. Both are outdated, in this case. Chrome 109.0.5414.120 on Windows 7. I don't think either has much influence on one specific preset, however.

**Comment by pnorman** [comment]
Works for me on Chrome 114.0.5735.199 on Windows 10. I tried with the osm.org locale set to `nl` to see if that had any impact.

Can you try updating Chrome? It would narrow down what the difference is.

**Comment by nickrsan** [comment]
OK, I just tried on an old (portable apps) version of Google Chrome I had around - version 83.0.4103.116 on Windows 10 - and still had success. In addition to @pnorman's suggestion of updating Chrome, can you confirm that this issue persists after restarting the browser? Ideally, it'd would be helpful to test in a new profile as well in case an addon is interfering (https://support.google.com/chrome/answer/2364824?hl=en&co=GENIE.Platform=Desktop)

**Comment by danieldegroot2** [comment]
Let's close this issue for now, as it does not seem to happen (anymore) on an up-to-date OS (at least for others), and regardless would not happen for me on the development version (as originally posted at the top of this issue).

**Comment by danieldegroot2** [comment]
This issue should now be fully redundant, as it's working for me.
