### ISSUE TITLE
Have the "subject:wikipedia" tag display the same way as "subject:wikidata"

### ISSUE THREAD

**Issue by Necessarycoot72** [openstreetmap/iD#9726]
### Description

Currently, only subject:wikidata pop when the tag in inputted. I recommend doing the same for subject:wikipedia. 

I attached an image of how only subject:wikidata is being displayed.

### Screenshots

![Screenshot 2023-07-03 192819](https://github.com/openstreetmap/iD/assets/21312478/a5973736-8382-4a5a-afe0-c47523f8f7a3)

**Comment by nickrsan** [comment]
Hi there - to clarify the request, which information would you want it to pull in from Wikipedia? The title and identifier make sense, but would you want something like the first paragraph of the article to give you something similar to the `description` field in wikidata? Or just leave that out?

**Comment by 1ec5** [comment]
This looks like a request for a “Subject Wikipedia” field to correspond to `subject:wikipedia`, which would be a feature request for the openstreetmap/id-tagging-schema repository. So far, only `wikipedia` has a field, but no `*:wikipedia` key has a field. There are multiple `*:wikidata` fields, including `subject:wikidata`.

/ref openstreetmap/id-tagging-schema#533

**Comment by nickrsan** [comment]
I've moved this request to id-tagging-schema at https://github.com/openstreetmap/id-tagging-schema/issues/947

I'm closing this issue here, please track and comment on it over there. Thanks!
