### ISSUE TITLE
crash when selecting multiple ways with numeric fields

### ISSUE THREAD

**Issue by k-yle** [openstreetmap/iD#9739]
### URL

https://ideditor.netlify.app/#map=20.40/-36.76850/174.76593

### How to reproduce the issue?

- go to https://ideditor.netlify.app/#map=20.40/-36.76850/174.76593
- select two road segments
- note how the editor crashes and an error appears in the console

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/16009897/059f5bdd-1a68-4db3-b61b-227749c714e8)

![image](https://github.com/openstreetmap/iD/assets/16009897/403a00e1-4dc8-4784-80ce-6b251ad4b892)

possibly caused by 2b64d703523a2856bd41b894dff9fcd5dc4bdc75 ? ~~from memory I think the raw tag editor uses arrays instead of strings when you switch to mutli-select mode~~

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

does not affect production, only the prerelease version at https://ideditor.netlify.app

### Which browsers are you seeing this problem on?

Microsoft Edge

**Comment by tyrasd** [comment]
:eyes: interesting. At first glance, this should be the culprit: https://github.com/openstreetmap/iD/commit/559a4ba72855c370e7499248609030b4967045ef#diff-20bad07a0a50747d3c088cd4cfd32014b21edec39c11f9c71998bb0f46ef876cL423.
