### ISSUE TITLE
Improve "Report User" notifications

### ISSUE THREAD

**Issue by julcnx** [openstreetmap/iD#9743]
### Description

The current implementation of the "Report User" feature in iD editor does not appear to notify the originator of the process.

I have used it several times to report spammers, and it seems to have been effective. However, I never received any email notifications regarding the reports. I had to manually search for the conflicting comments in the original changeset and find the user ID.

Ideally, the originator should receive:
- an email notification when the report has been acknowledged
- an email notification when action has been taken against the reported user (such as account deletion, user block, or no action).

If there are technical limitations preventing this, perhaps it could be implemented through the original changeset comments system.

**Comment by 1ec5** [comment]
The “Report User” feature is part of the [OSM website](https://github.com/openstreetmap/openstreetmap-website/), not iD specifically. My understanding is that it goes into a queue that the [Data Working Group](https://wiki.osmfoundation.org/wiki/Data_Working_Group) sees. I don’t know if it results in an automated receipt. If you aren’t getting expected updates about your report, you can [contact them directly](https://wiki.osmfoundation.org/wiki/Data_Working_Group#Contact).

**Comment by AntonKhorev** [comment]
There are two queues. Only users reported as vandals go to the queue visible to DWG. Other reports are either handled by admins or reassigned by admins to the DWG queue.
