### ISSUE TITLE
Easier submission of changesets

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9744]
### Description

Currently after writing a changeset description in the box, the user needs to reach for their mouse and click on "Upload changes". Instead it should be possible to do it by pressing Ctrl + Enter. This is similar behavior to most forms, where pressing Ctrl + Enter submits the form.

**Comment by 1ec5** [comment]
Some previous discussion in #4234.

**Comment by bhousel** [comment]
#7108 too

**Comment by nickrsan** [comment]
Great - thanks - I was thinking this might be a duplicate and was just beginning to search - I appreciate the pointers. Closing as duplicate. If anyone wants to revisit the prior decision on this, I'd recommend opening a discussion thread on the topic.
