### ISSUE TITLE
iD crashes when an email field is rendered

### ISSUE THREAD

**Issue by k-yle** [openstreetmap/iD#9752]
### URL

https://ideditor.netlify.app/#background=LINZ_NZ_Aerial_Imagery&disable_features=boundaries&id=w267161693&map=19.00/-36.97841/174.78714

### How to reproduce the issue?

(this only affects the beta version of iD, not production)

- select the hotel building (the "hotel" preset shows the email field by default)
- note how the editor gets stuck, and the sidebar no longer responds to changes

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/16009897/b25abdbb-a92e-481e-8bb2-377e255087bd)

![image](https://github.com/openstreetmap/iD/assets/16009897/18e267d6-d650-49d0-a845-60fea585782b)

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

master branch

### Which browsers are you seeing this problem on?

Microsoft Edge

**Comment by k-yle** [comment]
hey @tyrasd, i would consider this a https://github.com/openstreetmap/iD/labels/bug-release-blocker, any chance it could urgently be fixed? the new version of iD [released this morning](https://github.com/openstreetmap/openstreetmap-website/pull/4086) is constantly crashing...

I lost my progress because of this crash, since i couldn't upload my changes due to a validator error ("Point has no tags"). But it's impossible to fix that validator error once iD is in this broken state

**Comment by tyrasd** [comment]
:scream: 
taking a look right now

**Comment by tyrasd** [comment]
a hotfix is prepared and waiting to be applied on the openstreetmap-website repo
