### ISSUE TITLE
Tag raw editor is empty

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/iD#9762]
As of 2.26 or 2.26.1 the raw tag editor list is empty:

![empty tag list](https://github.com/openstreetmap/iD/assets/3857299/52b7e1b8-1a75-41bd-9623-3b92ce4f922d)

You can add text to it, but it generally leads to broken tagging, as it won't preserve existing ones.

This happens on any selected element - existing, new, modified.

No errors in console.

Win 10 Enterprise x64, Firefox and Opera.

**Comment by matheusgomesms** [comment]
And some fields can't even be edited (like name, for example). Also, in the map itself, some geometries can't be deleted (tested with buildings, but if you delete point by point or selecting an area with Shift it's still possible).

Tested on a Mac, Safari and Firefox.

**Comment by Zaczero** [comment]
> And some fields can't even be edited (like name, for example). Also, in the map itself, some geometries can't be deleted (tested with buildings, but if you delete point by point or selecting an area with Shift it's still possible).
> 
> Tested on a Mac, Safari and Firefox.

This sounds like a separate issue, not related to raw editor.

**Comment by Dron007** [comment]
I confirm the problem on Chrome. It is impossible to copy tags and it deletes all tags if I keep empty input.

**Comment by tastrax** [comment]
Confirmed - if you place the cursor in the text area it **deletes ALL tags** and you need to undo to recover tags.

**Comment by cotesta** [comment]
Confirmed on Windows Firefox, 2.26.1. Thankfully the separated tag editor still functions correctly, but yeah this is definitely a critical issue.
