### ISSUE TITLE
addr:street is missing an icon from address selector dropdown

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap/iD#9763]
### URL

https://www.openstreetmap.org/edit#map=19/51.74659/20.77788

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/10835147/624ea076-a995-4e15-9929-57a6474abad7)

![image](https://github.com/openstreetmap/iD/assets/10835147/216403d7-7d3c-4d75-affc-c039ac893c60)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.26.1

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
oh, I used a slightly outdated screenshot for the announcement. The icon was actually omitted on purpose for the case of "regular" streets after https://github.com/openstreetmap/iD/pull/9603#discussion_r1180891096. Do you think this could be confusing?

**Comment by Zaczero** [comment]
I do think there should be a unique icon for each type because it looks odd without it. But I agree, that the line icon is a little confusing too. I suppose the no icon is a better choice so I'll close the issue now :-)
