### ISSUE TITLE
addr:housenumber is glitchy during typing

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap/iD#9764]
### URL

https://www.openstreetmap.org/edit#map=19/51.74659/20.77788

### How to reproduce the issue?

1. Select an address
2. Clear the house number field
3. Start typing at least 2 char long number: 123
4. Result is 231

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.26.1

### Which browsers are you seeing this problem on?

Chrome

**Comment by pca7070** [comment]
Same issue here.

**Comment by Zaczero** [comment]
This issue appears to be caused by code located at this specific location: https://github.com/openstreetmap/iD/blob/cc740be721bbc48c872a0ab67b18e7575cbe4547/modules/ui/fields/address.js#L284

When a user inputs a value, the cursor moves forward, but the update logic seems to reevaluate all the fields, often using outdated tags. This results in the temporary replacement of a value like "12" with "1" (since the tags are not updated at this point), followed by another call shortly after, which correctly replaces the value with "12".

You can see the `utilGetSetValue` being called multiple times for the same element with different parameters per change.

In my opinion, the best approach to address this issue would be for the change event to update only the currently edited field, or at the very least prioritize updating those fields first to prevent overwriting them with outdated values.
