### ISSUE TITLE
Changeset comment dropdown does not work

### ISSUE THREAD

**Issue by sjorford** [openstreetmap/iD#9767]
### How to reproduce the issue?

Clicking the changeset comment box produces a dropdown list of recent comments, but clicking those comments no longer works - the dropdown disappears but the comment box is still empty

### Screenshot(s) or anything else?

![2023-07-13 09_52_06-OpenStreetMap — Mozilla Firefox](https://github.com/openstreetmap/iD/assets/10633357/5e352af7-56ec-48d5-821f-5175058a7e64)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.26.1,2.27.0-dev

### Which browsers are you seeing this problem on?

Chrome, Firefox

**Comment by k-yle** [comment]
This was fixed a few minutes ago in #9766

**Comment by 1ec5** [comment]
Yep, fixed in #9766.
