### ISSUE TITLE
Cannot select recent changeset comment

### ISSUE THREAD

**Issue by CasGroenigen** [openstreetmap/iD#9773]
### URL

Anywhere

### How to reproduce the issue?

1. Make changes on OSM
2. Click save
3. Click the textbox where the changeset comment should go to see all the recent changeset comments you can select
4. Click on a changeset comment you'd like to select
5. The changeset comment did not get added to the textbox

### Screenshot(s) or anything else?

This is the area I'm talking about
![image](https://github.com/openstreetmap/iD/assets/89485738/5ec309bf-7ac0-4e98-8dc2-4a599b069ac8)

Furthermore, the textbox was already supposed to be filled because I am doing a Maproulette challenge that auto fills the textbox. 
Also, whenever I type one character of the top suggestion, so in this case #, it will suggest the top comment and fill it in if I click tab.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

iD 2.26.1

### Which browsers are you seeing this problem on?

Microsoft Edge

**Comment by DujaOSM** [comment]
Worse still, it does not remember the comment previously entered in _the same session_. I have a habit to type the changeset comment some time mid-session, and go on to fix any outstanding issues before saving the changeset. When I do that now, my meticulously typed comment has gone.

**Comment by k-yle** [comment]
This was fixed in #9766

**Comment by nickrsan** [comment]
K-yle and tyrasd fixed and deployed as iD 2.26.2 - closing this issue, but please let us know if you continue to see behavior like this.
