### ISSUE TITLE
Wrong Earth radii are used in calculations

### ISSUE THREAD

**Issue by Dron007** [openstreetmap/iD#9791]
### How to reproduce the issue?

There are wrong constants for  Earth radii here: 

https://github.com/openstreetmap/iD/blob/46a2d6365f5609f66cfffe8d8b018516b82443d4/modules/geo/geo.js#L3-L4

Radii are reversed. See https://en.wikipedia.org/wiki/Earth_radius.
It is probably hard to notice but it is still a bug which may give additional error. Unit tests compare results with wrong constants too and not fail.

**Comment by tyrasd** [comment]
Good catch. Thank you!
