### ISSUE TITLE
Place search is broken

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#9822]
### How to reproduce the issue?

It looks like the same issue Ben describes in https://github.com/facebook/Rapid/issues/1007 applies to iD as well. I get a CORS error when searching for Huston.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

**Comment by nickrsan** [comment]
Confirming that I also get a 404 for the request to https://nominatim.openstreetmap.org/search/ and that only POIs/data loaded in the current view display in search, in agreement with what Ben noted.

**Comment by k-yle** [comment]
This is caused by osm-search/Nominatim#3134, although I thought openstreetmap/operations#920 would have temporarily fixed the issue...

**Comment by tordans** [comment]
@k-yle I still get the CORS error. Is this maybe something different from the other "search/" issues?

**Comment by tordans** [comment]
I see this was fixed by @tyrasd last week via https://github.com/openstreetmap/iD/commit/a454aa35c1c32d1bea2d648c65ff1abb50c2d7d4 and https://github.com/openstreetmap/iD/commit/a460013991416a26cb2c03a87dbcbf21c77249f5.
I can confirm it works on https://ideditor.netlify.app/

@tyrasd since the change referenced in https://github.com/openstreetmap/iD/issues/9822#issuecomment-1670462560 does not solve the issue on production, maybe this is something for a hotfix release?

I will close the issue now, since it is handled pending deployment…

**Comment by tyrasd** [comment]
@tordans yeah, I thought so as well, but as I had planned to do a full release soon anyway, it is now included in [v2.27.0](https://github.com/openstreetmap/iD/blob/release/CHANGELOG.md#2270), which should be deployed soon. :relaxed:
