### ISSUE TITLE
Remove Osmose issues checkbox 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9830]
In the Map Data menu, there is a checkbox for Osmose issues.

However checking it does not show the Osmose issues, as seen in other editors.

Therefore please consider removing it.

Or have a ~~strike line~~ through it with a mouseover saying it doesn't work currently.

**Comment by tyrasd** [comment]
It does work fine for me. See screenshot:

![image](https://github.com/openstreetmap/iD/assets/1927298/09293f9b-a3be-49b9-bdad-027a3ad9d742)

Maybe it was just a temporary issue of the service? Do you see any errors in the javascript console (or network tab) of the browser developer tools? Is anything else special in your setup?
