### ISSUE TITLE
Move `boundary=protected_area` to "Boundaries" category

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9833]
Currently `boundary=protected_area` is part of the "Landuse" category in the map data panel. That makes it difficult to map landuses. It would be nice if it gets moved to the "Boundaries" category. If this issue is for the main iD repository, feel free to transfer it.

**Comment by tyrasd** [comment]
Can you show an example where this is happening? Because for me it is (correctly) associated with the _boundary_ data type, except if the same object is also tagged using a tag like `landuse=forest` or `landuse=grassland` for example. But in these cases, you would want to see them if you are mapping landuses, wouldn't you?

**Comment by Dimitar5555** [comment]
https://www.openstreetmap.org/edit#map=17/43.65852/26.26761 with https://www.openstreetmap.org/relation/4273641.

![image](https://github.com/openstreetmap/iD/assets/19364673/cd1efd02-d0ad-4056-82df-e8d4760620ef)



> if the same object is also tagged using a tag like `landuse=forest` or `landuse=grassland` for example. But in these cases, you would want to see them if you are mapping landuses, wouldn't you?

In practice yes, but there are no `landuse`, `natural` or other "polygon" tags in this case (apart from `type=multipolygon`).

**Comment by DujaOSM** [comment]
This should really be tagged with `type=boundary` rather than `type=multipolygon`. I suppose iD presumes that a multipolygon maps a "landuse" feature and looks no further, and I'd expect some renderers to have an issue with that too.

**Comment by Dimitar5555** [comment]
Thank you @DujaOSM, that was the problem. It also seems like there ~22k wrongly tagged `boundary` relations (of which ~11k are `boundary=protected_area`) which is yet another can of worms.
