### ISSUE TITLE
KartaView is returning 404 errors on some images

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9844]
### How to reproduce the issue?

_Development version is broken for me, see seperate issue._

Example error
` ` `
1295397_41_038f8_28.jpg:1     GET https://storage9.openstreetcam.org/files/photo/2018/10/3/lth/1295397_41_038f8_28.jpg 404 (Not Found)
Image (async)
(anonymous) @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:2
each_default @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:2
attr_default @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:2
selectImage @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:66
(anonymous) @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:14
Promise.then (async)
c @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:14
(anonymous) @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:2
` ` `

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/67521919/d3fcd88d-1d51-49e4-b45f-e18f5768d21f)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.0

### Which browsers are you seeing this problem on?

Chrome

**Comment by danieldegroot2** [comment]
Seems to resolve itself upon clearing cache.

**Comment by danieldegroot2** [comment]
Some do not seem to resolve themselves by clearing cache. Example

URL https://www.openstreetmap.org/edit#map=20/40.69316/-73.95475
image https://kartaview.org/details/402532/194

` ` `
402532_26158_592dba7baa648.jpg:1     GET https://storage4.openstreetcam.org/files/photo/2017/5/30/lth/402532_26158_592dba7baa648.jpg 404 (Not Found)
Image (async)
(anonymous) @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:2
each_default @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:2
attr_default @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:2
selectImage @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:66
(anonymous) @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:14
Promise.then (async)
c @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:14
(anonymous) @ id-dcae40b437277267aa4eccf48416d1e826e1bb8fca4cc7a9c205daaeab91f19b.js:2
` ` `

**Comment by elevenchars** [comment]
Happening as well with the segment which is at this location.
https://www.openstreetmap.org/edit?changeset=140828429#map=18/48.31701/-89.33319

**Comment by tyrasd** [comment]
I took a look at this and as far as I can see, this is not an issue in iD, but with @kartaview's API. The same issue also occurs on the JOSM plugin (I assume this was reported as https://github.com/kartaview/josm-plugin/issues/52 already). I have now contacted KartaView directly via email, which can hopefully resolve the bug on their end soon. :crossed_fingers:
