### ISSUE TITLE
Dev view rendering seems broken

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9845]
### How to reproduce the issue?

The `dev` view on the development version seems to be broken for me, at least its rendering is questionable..
It is returning mostly nothing, only some POIs of which some with a 'geo-...'  name and some crossing way segments. No buildings are returned on zooming in.

Made sure settings are normal (data on, unfiltered)

No errors are returned, only one which is also returned on the current live version where it renders fine.

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/67521919/5e37f40f-6666-4d2f-8282-629b5a3f0797)

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.28.0-dev

### Which browsers are you seeing this problem on?

Chrome

_Is not resolved by clearing cache.._

**Comment by arch0345** [comment]
If you're talking about clicking the ![image](https://github.com/openstreetmap/iD/assets/85302075/09870392-bee5-4024-ab8b-0d6b95087120) button, this switches to a different database that's used for testing purposes:
https://wiki.openstreetmap.org/wiki/Sandbox_for_editing#Expierment_with_the_API#(advanced)

**Comment by danieldegroot2** [comment]
Yes, sorry. Forgot it worked like that.
