### ISSUE TITLE
Unexpected scrolling on iD / iPadOS

### ISSUE THREAD

**Issue by jerome-0** [openstreetmap/iD#9853]
### URL

https://www.openstreetmap.org/edit#map=19/45.89474/6.63837

### How to reproduce the issue?

After selecting a building, when trying to set a value to the « power » tag, it scrolls unexpectedly to the field « operator ».
But the bug occurs with every field, not only « power ». So iD is almost unusable, because it scrolls again and again at every selection.
It is the same with Firefox for iPad and Chrome for iPad.

The bug appeared 2 days ago.

Thank you for your help.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.0

### Which browsers are you seeing this problem on?

Chrome, Firefox

**Comment by tyrasd** [comment]
This is most likely the same bug as #9848

**Comment by tyrasd** [comment]
PS: @jerome-0  could you please verify if the fix in `v2.27.1` does indeed also solve the bug you were experiencing?

Until it is rolled out on osm.org, you can test it for example at https://ideditor-release.netlify.app/

**Comment by jerome-0** [comment]
I confirm the problem is solved with version 2.27.1 😀
