### ISSUE TITLE
Trace uploaded via StreetComplete not displayed

### ISSUE THREAD

**Issue by aikencz** [openstreetmap/iD#9869]
### URL

https://www.openstreetmap.org/user/Luk%C3%A1%C5%A1%20Jel%C3%ADnek/traces/9644640

### How to reproduce the issue?

1. Create a trace using StreetComplete.
2. Open the iD editor.
3. Enable GPS traces.

### Screenshot(s) or anything else?

The given trace (see URL) isn't displayed even if it has public visibility (I tried to set various visibility levels but it had no effect). Older traces (both mine and other users') are displayed correctly. The given trace isn't displayed in the OSM itself too.

It is possible that StreetComplete uploads corrupted data but the given trace appears good at its page (see URL).

![Traces in editor](https://github.com/openstreetmap/iD/assets/3749240/ec706226-0f36-476f-80bf-c3d8f7103daf)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.1

### Which browsers are you seeing this problem on?

Firefox

**Comment by tordans** [comment]
@aikencz the traces service is something that is handled in https://github.com/openstreetmap/openstreetmap-website. iD just takes the pre-rendered images and shows them. I will close this for this Repo and suggest you open an issue over there should the issue still persist. However, I assume this might have been a timing thing or caching issue.
