### ISSUE TITLE
Null hiding among "multiple values"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9876]
### Description

Here there are multiple values.
But we only see one value.
Then how could there be multiple values?
Because the other value is the null value.

What would the use of also displaying a second line
"(null)" or "(empty)"?

Well besides being able to click on the one named value, in order to
change all items to use that single value,
we could also click "(null)" to make them all null.

But OK, if we were smart we could also just click on the trash can.

But at least showing "(null)" would reveal the mystery behind the single
"multiple" value.

Also consider the case where there are three values, A, B, and null.

Well when the user clicks, s/he will just see A and B, and go home thinking s/he knows the whole story.

But that isn't the whole story at all!!

So one should see
- A
- B
- (null)

### Screenshots

![20230830T044303](https://github.com/openstreetmap/iD/assets/1230959/22c84dd9-929c-4867-94fa-462320d09da3)

**Comment by matkoniecz** [comment]
how this can be reproduced?

**Comment by Dimitar5555** [comment]
> how this can be reproduced?

1. Add `tag=yes` to an element
2. Add `tag` without adding a value to another element (leaving the value box empty)
3. Select both elements
4. Hover over the box that corresponds to `tag` (it will say "Multiple values" but only `yes` will be shown). If you click on it, only `yes` will be suggested
