### ISSUE TITLE
Hard to tell which is the connection point of a closed loop

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9895]
### Description

Start a Line. Make a triangle. Now do the circle command.

Now hunt around for the endpoints.

You cannot tell which ones they are.

You might need to right click on most of each of the 19 nodes, looking for the one that offers the disconnect function, not greyed-out, before you find it.

One might say that that node should look different than the others, just like it does when connected to another way.

### Screenshots

![20230910T015932](https://github.com/openstreetmap/iD/assets/1230959/276f020a-c6ed-4a76-9494-8251cea2d9e5)

**Comment by jidanni** [comment]
By the way, I connected right to that node, and still got this error:

![20230910T021030](https://github.com/openstreetmap/iD/assets/1230959/a7c30f8e-b49c-4cd0-8cea-3462e107733e)

**Comment by jidanni** [comment]
In fact the same unconnected warning happens with any node on that closed loop. Must be something about being closed that is causing it.
![20230910T021511](https://github.com/openstreetmap/iD/assets/1230959/81dba379-1825-4a80-a3b4-6e1596a27be3)

**Comment by jidanni** [comment]
In such cases, letting iD connect it for us always works,
![20230910T021727](https://github.com/openstreetmap/iD/assets/1230959/cc530985-8483-4799-b97f-7ea0ca96b9e9)
Click "connect the features" and it does it in a way that it is happy with.

And it turns out, if we have picked the right one of the 19 nodes, then after the connection, selecting both features, and hitting C to combine, works!

(Afterwards, looking closely at the arrows
![20230910T022521](https://github.com/openstreetmap/iD/assets/1230959/30e451c6-98c2-4452-ad36-970f39841b16)
we can tell if our circular driveway has ended up in US vs. UK driving direction.)

**Comment by Dimitar5555** [comment]
> By the way, I connected right to that node, and still got this error:
> 
> 

This is an old bug that has been fixed at least two times yet it still appears. It's a problem with the validator. Moving a node and them pressing Ctrl + Z should fix it.

**Comment by 1ec5** [comment]
> You might need to right click on most of each of the 19 nodes, looking for the one that offers the disconnect function, not greyed-out, before you find it.

I hadn’t thought of this method. What I normally do is to press <kbd>Shift</kbd><kbd>{</kbd> or <kbd>Shift</kbd><kbd>}</kbd> to navigate to one of the endpoints.

> By the way, I connected right to that node, and still got this error:

> In fact the same unconnected warning happens with any node on that closed loop. Must be something about being closed that is causing it.

This is #8900.

**Comment by jidanni** [comment]
OK I pressed `Shift {` and indeed found an endpoint.
But then right clicking to append should work,
because I should somehow have indicated my choice of which of the two (stacked) ends I want to append to, but alas, I still cannot append.

**Comment by 1ec5** [comment]
> because I should somehow have indicated my choice of which of the two (stacked) ends I want to append to, but alas, I still cannot append.

This is #9894, which is #2272.

> Now hunt around for the endpoints.
> 
> You cannot tell which ones they are.

https://github.com/openstreetmap/iD/issues/9301#issuecomment-1256148978 tracks visually indicating the connected endpoint of a closed way.

> And it turns out, if we have picked the right one of the 19 nodes, then after the connection, selecting both features, and hitting C to combine, works!

#7732 tracks making it easier to combine the turning loop with the rest of the street, regardless of where the loop technically begins and ends.

Closing because I think all the feedback is already tracked in other issues.

**Comment by jidanni** [comment]
(Another way of finding the connection point is:
- Select the loop.
- Right click
- Hover over the Disconnect icon

The node that can be disconnected will be revealed.

Clicking it will make it disconnected (and thus bigger, too.)
