### ISSUE TITLE
Autocomplete changes its mind after 0.3s

### ISSUE THREAD

**Issue by lgommans** [openstreetmap/iD#9898]
**Reproduce:** Type "g", "gr", or "gra" in the `surface=` field

**Video:** https://github.com/openstreetmap/iD/assets/5626710/3c398fcb-a0c6-4c1b-8e3f-e35b5c4c9899

**User story:**

Earlier, I typed "gr" and saw it already completed to grass, so I tabbed out of the field, only for it to last-second change to ground!

Now at the current road, I was aware of the problem so I typed "gra", see it complete to grass, and tab out of the field :)  ...... wait .... gravel?! That's not what I selected!

Someone on Telegram suggested arrow keys: I'm using my left hand to type (qwerty) and right for the mouse, so arrow keys are far out of reach. I like the autocomplete a lot but please don't show it before it has made up its mind about what value it'll use! :D

**iD version:** Released version at openstreetmap.org/edit

**Browser:** Firefox 116.0.3 on Linux

**Comment by navyn13** [comment]
I was working on this issue and now on giving input it is woking well. This is related video to it.

https://github.com/openstreetmap/iD/assets/121725696/26741dc0-4a0a-4a78-9b14-db3e3523b319

**Comment by lgommans** [comment]
Thank you @tyrasd!
