### ISSUE TITLE
Show shared golf course boundaries

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9902]
### Description

- High class snob club exclusive golf course A
- Low class public golf course B

are neighbors. It is very important to show the boundary between them, yes, even if there is no fence or hedge.

**Comment by 1ec5** [comment]
Can you provide an example or screenshot to demonstrate the issue? Thanks!

**Comment by nickrsan** [comment]
Yes, this sounds like a mapping/data problem or a rendering problem elsewhere - iD should be rendering a line between them if the polygons are separately mapped. It will help if you provide the information 1ec5 asked for.

**Comment by jidanni** [comment]
https://www.openstreetmap.org/node/11183824677 is a node on the boundary.

**Comment by danieldegroot2** [comment]
Hey Jidanni,

This is https://github.com/gravitystorm/openstreetmap-carto/issues/2069#issuecomment-442052897 (it seems noone is working on this specific case yet).
In iD most areas have an outline. See below for regular and wireframe rendering.
![image](https://github.com/openstreetmap/iD/assets/67521919/0def5874-324c-4714-89a5-0d087f2944b4)
![image](https://github.com/openstreetmap/iD/assets/67521919/d46ec059-814b-4b0c-bb88-3d43052feeeb)

**Comment by jidanni** [comment]
Oops. Oh yeah. I filed a Carto issue under iD. I'm very sorry. I'll close it right away.

**Comment by jidanni** [comment]
OK, I made https://github.com/gravitystorm/openstreetmap-carto/issues/4870
