### ISSUE TITLE
Add `building=riding_hall` as new type

### ISSUE THREAD

**Issue by simonschaufi** [openstreetmap/iD#9915]
### Description

Currently `building=riding_hall` can only be entered manually in the tags but not selected via the search. It would be more convenient if it would be available.

See https://wiki.openstreetmap.org/wiki/Tag:building%3Driding_hall

**Comment by nickrsan** [comment]
Hi Simon - you'll need to file this request over on https://github.com/openstreetmap/id-tagging-schema - that's the repository where presets that show up in search are configured. I don't have permissions to just transfer it across, so I'm going to close it here, but encourage you to open a new issue there (sorry for the extra work)

**Comment by simonschaufi** [comment]
See https://github.com/openstreetmap/id-tagging-schema/issues/1012
