### ISSUE TITLE
new geo-images has buggy UX

### ISSUE THREAD

**Issue by zander** [openstreetmap/iD#9918]
### How to reproduce the issue?

Should work like this:
- click "edit" to launch iD
- open "Map data" (shortcut U) from the right-hand panel
- go down to "georeferenced photos"
- click the three dots to open the "load photos" dialogue
- select a random NOT geo-tagged image.

The result is the attached images.

Problems:

* the actual image filename (IMG_etc) is in the same color as the frame. It is not black, like all other text.
* the alert icon is too easy to miss. There is nothing else in the app to show that there are issues so you create a UX problem with people missing there is a detected issue because your alert image is light gray. Even less conspicuous than plain text.
* hovering over the warning icon shows a warning that is cut off.

### Screenshot(s) or anything else?

![Screenshot_20230927_103451](https://github.com/openstreetmap/iD/assets/63063/dcd2c1e6-4590-4410-a6f2-c32ce1eb03e3)

While hovering the 'alert' icon:

![Screenshot_20230927_102756](https://github.com/openstreetmap/iD/assets/63063/7b641882-0565-4447-be79-5e14ac9d1e99)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by nickrsan** [comment]
I'm able to reproduce this issue in Firefox as well and a related issue where one image uploaded then just disappeared. Tagging as a UX bug.

**Comment by navyn13** [comment]
@zander @nickrsan  changed the colour of alert svg
![Uploading Screenshot 2023-11-01 at 7.20.33 PM.png…]()

**Comment by navyn13** [comment]
@zander @nickrsan Changed svg to red
<img width="310" alt="Screenshot 2023-11-01 at 7 21 14 PM" src="https://github.com/openstreetmap/iD/assets/121725696/ab1d7598-63e0-45e6-8283-891818449649">
Looking ahead to solve other two tasks

**Comment by navyn13** [comment]
hey @zander @nickrsan  pls have a look at this

https://github.com/openstreetmap/iD/assets/121725696/7fd511a2-5322-4a47-a082-e5c710bfbfb2

**Comment by navyn13** [comment]
hey @zander @nickrsan have a look at this

https://github.com/openstreetmap/iD/assets/121725696/d180dd49-624a-40e2-9adc-55ce28a72841


I just changed some css and some added class to svg in js
Should I add some more changes before submitting pr
