### ISSUE TITLE
Add panoramax streetlevel image data

### ISSUE THREAD

**Issue by u4y0u** [openstreetmap/iD#9941]
### Description

Hello, It would be interesting to plan now to integrate the street imagery of the **panoramax** instances ( [osm](https://panoramax.openstreetmap.fr/#focus=map&map=1.46/12.5/31.7&speed=250) , [ign](https://panoramax.ign.fr/#focus=map&map=5.7/47/3&speed=250) ...etc ) in the same way as that of Mapillary.
With, just like this one, the possibility of seeing the captured image by clicking on the point of the panoramax overlay (https://api.panoramax.xyz/...map/{z}/{x}/{y)}.pbf) and choose the direction of view in the thumbnail or click on a link to access high-resolution [imagery](https://api.panoramax.xyz/#focus=pic&map=19.41/47.901861/1.9090413&pic=56ddb766-e929-4e86-b7ce-f5df894a6442&speed=250&xyz=73.77/4.88/30) .
Panoramax provides openstreetmap contributors with **high resolution images** which will greatly facilitate the enrichment of the OSM database if their integration into the ID editor is carried out.

Available on the meta catalog:
in the sequence
https://api.panoramax.xyz/#focus=pic&map=19.41/47.901861/1.9090413&pic=56ddb766-e929-4e86-b7ce-f5df894a6442&speed=250&xyz=73.77/4.88/30

in the url    '... pic='...  **uuid** of the image

the link is: https://api.panoramax.xyz/api/pictures/uuid/hd.jpg
like:
https://api.panoramax.xyz/api/pictures/56ddb766-e929-4e86-b7ce-f5df894a6442/hd.jpg
and then redirecting on the OSM instance...
https://panoramax.openstreetmap.fr/images/56/dd/b7/66/e929-4e86-b7ce-f5df894a6442.jpg

### Screenshots

osm panoramax instance and GeoVisio viewer. 
![image](https://github.com/openstreetmap/iD/assets/54479065/e502c144-7212-448b-8e43-8b0bc786b5fa)

**Comment by thibaultmol** [comment]
(Something that i've mentioned before somewhere os that I hope there will be some kind of system if the same image is on Mapillary and on GeoVisoo, that it doesn't display two dots on the map for the same image. But GeoVisio doesn't have a metadata field for matching Mapillary image key... Yet)

**Comment by tuxayo** [comment]
> But GeoVisio doesn't have a metadata field for matching Mapillary image key... Yet

How would that field be populated? In addition to that question, the same wish for such a field could be directed at Mapillary.

Regardless of that, to circumvent those problems, would it work to have ID on image load identify that two images have the same coords from different providers (accounting for an eventual rounding error) and then ignore one of the duplicates?

The last part of ignoring duplicates (and which provider keep when there is duplication) is the same if one image provider had a field to indicate the image is also in another base. So the difference is having duplication identification based on coordinates and not a field that one of the duplicates would have.

**Comment by brunnerpaul** [comment]
@thibaultmol, IMHO an image deduplication across different services falls into the "nice to have" category.
iD currently offers previews of 4 different services plus local images, my experience is I mostly have only 1 of them open at a time anyways.
<img width="344" alt="Screenshot 2024-04-01 at 22 36 35" src="https://github.com/openstreetmap/iD/assets/63242083/7a6a1a18-db81-44c4-8b83-57e995d8aab7">

And generally, yes, it would be great to see imagery from the Panoramax instances in iD!

**Comment by thibaultmol** [comment]
@tuxayo 
> How would that field be populated? In addition to that question, the same wish for such a field could be directed at Mapillary.

Not really, they're the 'market leader', they won't do that
There is a way to add the mapillary key on the EXIF data of the images on Panoramax

> Regardless of that, to circumvent those problems, would it work to have ID on image load identify that two images have the same coords from different providers (accounting for an eventual rounding error) and then ignore one of the duplicates?

Same coordinates and same time, should be enough to identify images yeah

---

Also good to add to this issue, there is a Google Open Summer of Code project to add Panoramax viewing support to iD: https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2024/Project_ideas#Support_display_of_images_from_Panoramax_in_iD

**Comment by pietervdvn** [comment]
Hi all,

With [MapComplete](https://mapcomplete.org), we are looking into Geovisio/Panoramax as well. @thibaultmol entered a proposal at NlNet for me.

For our usecase, we would like to:

1) Query which pictures are around a certain point and display them
2) Upload to a geovisio instance

It might be interesting to work together or to reuse your work. Ideally, if all the functionality would be packaged into TS-library, then we could just reuse all of this.


As such, I'm a bit wondering how the functionality would be implemented and if this kind of reuse would be possible.

**Comment by tordans** [comment]
> For our usecase, we would like to:
> 
> 1. Query which pictures are around a certain point and display them
> 2. Upload to a geovisio instance

I don't think those features are something that iD does or expressed interested to do before. I understand this ticket to be focussed on just displaying all the images of all instances in a given viewport and allow to view them in a viewing panel. (Ideally with some kind of image-key interaction similar to https://github.com/openstreetmap/iD/pull/10046).

**Comment by pyrog** [comment]
> 1. Query which pictures are around a certain point and display them

For a specific OSM object, application could query object id.
Not yet possible with Panoramax (but osm id could be stored in picture metadata).
FYI, this is possible with Wikimedia Commons ([OSM Hydrant](https://www.osmhydrant.org/fr/#zoom=19&lat=46.675578&lon=5.554034) do this)

… or the application could display pictures (tagged with `panoramax`)

**Comment by tordans** [comment]
For reference: According to [WeeklyOSM 723](https://weeklyosm.eu/archives/17244) @mattiapezzotti is working on this feature over at https://github.com/mattiapezzotti/iD/tree/panoramax

> Mattia Pezzotti, a Google Summer of Code 2024 participant, [presented](https://www.openstreetmap.org/user/Juicio/diary/404174) their project for integrating Panoramax imagery into the iD editor. The project aims to enhance map exploration by incorporating 360-degree imagery, providing users with valuable visual context and improving map visualisation and community engagement.

There is more info [in Mattia's blog post](https://www.openstreetmap.org/user/Juicio/diary/404174).

**Comment by tordans** [comment]
FYI the blogpost at https://www.openstreetmap.org/user/Juicio/diary/404174 receives weekly updates for the last 6 weeks on the project.

**Comment by tyrasd** [comment]
This was implemented in #10317 by @mattiapezzotti . 

You can already test it on iD's preview instance https://ideditor.netlify.app (here's an [example](https://ideditor.netlify.app/#background=Bing&disable_features=boundaries&locale=en&map=18.83/48.84190/2.58626&photo=panoramax/c55cded5-1910-449a-8e73-9a70606e72c3&photo_overlay=panoramax) location with good coverage on Panoramax). Please test it and report issues that you might find.
