### ISSUE TITLE
Use regex for discard list in imagery update script

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/iD#9946]
### Description

Rapid currently uses regex for the discard list in the update imagery script:
https://github.com/facebook/Rapid/blob/f9ff458c96d3857ad90be4f864739c175dda7af2/scripts/update_imagery.js#L28-L56

As mentioned in https://github.com/openstreetmap/iD/pull/9945#issuecomment-1770225887, it might be worth implementing this so that, for example, new eox.at sources won't have to be added every year.

**Comment by 0xAnon0602** [comment]
Hey, I would like to work on this issue.
Can you assign this to me ?

**Comment by 0xAnon0602** [comment]
@tyrasd  @arch0345 
Hey, I would like to work on this issue.
Can you assign this to me ?

**Comment by arch0345** [comment]
Unfortunately don't have perms to assign people, however you're more than welcome to work on this issue!

**Comment by 0xAnon0602** [comment]
@tyrasd 
Added a pull request 
Let me know if anything else needs to be added here

**Comment by arch0345** [comment]
Closed via #9975
