### ISSUE TITLE
Tool for making rectangles with less clicks

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9961]
### Description

Such tool is already implemented in JOSM (BuildingTools). It allows you to draw rectangles with 3 clicks (or 2 if you've selected another feature for snapping). It would make it a lot easier to draw buildings in iD (which requires 5 clicks for rectangles and even more for more complex shapes). It would also reduce the need of adjusting each node after squaring since iD shrinks or expands the building too much in some cases. It should go hand in hand with the extrude tool (#2986).

### Screenshots

Video of the workflow for drawing a building with BuildingTools and extrude tool: https://i.imgur.com/XQWvTAF.mp4

**Comment by tyrasd** [comment]
This is essentially what is proposed in #528 already, isn't it?

**Comment by Dimitar5555** [comment]
Yeah it is. I wasn't able to find it.
