### ISSUE TITLE
Wrong mouse symbol for mapillary link 

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#9992]
### URL

https://ideditor.netlify.app/#background=EsriWorldImageryClarity&disable_features=boundaries&id=n358249800&map=19.00/39.29168/-76.65332

### How to reproduce the issue?

Move the mouse pointer over the mapillary link area.

Expected behavior: the mouse arrow symbol should change to a hand symbol
Current behavior: the mouse arrow symbol changes to a stop (similar to https://wiki.openstreetmap.org/wiki/File:Commons-emblem-hand.svg) symbol

### Screenshot(s) or anything else?

![mapillary link symbol](https://github.com/openstreetmap/openstreetmap-website/assets/47290585/d070601b-449e-4d21-a0d0-1efa7ba96eba)

**Comment by sun-geo** [comment]
@ramith-kulal and @k-yle thanks for working on this!

In the meantime i noticed same behavior for the mouse pointer when moving over the link of a `wikimedia_commons` tag.

Example object:
https://ideditor.netlify.app/#background=EsriWorldImageryClarity&disable_features=boundaries&id=n10963301682&map=22.00/33.61970/-117.69989

If you want to fix this as well.

![image](https://github.com/openstreetmap/iD/assets/47290585/3578b7f9-c057-4db5-8f2f-fc9396a81d71)

**Comment by k-yle** [comment]
Hey @sun-geo, you're right, this bug affects many fields that have a "foreign link", except for special cases like `wikipedia` and `website`.
